### ISSUE TITLE
IndexError in Internal Console when closing files in the Editor

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1000]
_From [mrcl...@gmail.com](https://code.google.com/u/104852577201942867952/) on 2012-04-20T15:32:27Z_

What steps will reproduce the problem?

 1. Open Spyder
2. Close .temp.py file or any previously open code file that appears in the Editor
I expect the file to close without errors but the following is displayed in the Internal Console:

\>>> Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/plugins/editor.py", line 1056, in close_file_in_all_editorstacks
    editorstack.close_file(index, force=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/editor.py", line 1189, in close_file
    finfo = self.data[index]
IndexError: list index out of range

Perhaps related is that under the following conditions, two files are closed at once.
1. Open Spyder (previously open code file is present in Editor, or .temp.py file)
2. Open another code file
3. Closing the .temp.py (or previously open code file) results in BOTH files being closed. No error is reported to the Internal console.
4. Opening and then closing any other code file results in the same traceback listed above. What version of the product are you using? On what operating system? Spyder 2.1.9
Python 2.7.3, Qt 4.7.4, PyQt4 (API v1) 4.9.1 on Darwin
Mac OS X 10.7.3

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1000_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-21T00:05:03Z_

This is already fixed in v2.2.0dev.

As for v2.1 branch:
  * this is not fixed in v2.1.9 indeed
  * this is fixed by this revision: https://code.google.com/p/spyderlib/source/detail?r=29b7e270e1a1c4e64a9969aa739f3e896c5d1b49&repo=v21 * and so you'll have to either use the v21 repository version ( https://code.google.com/p/spyderlib/source/checkout?repo=v21 ) or wait until v2.1.10 is released.

**Status:** Duplicate  
  **Mergedinto:** 813
