### ISSUE TITLE
After dragging Spyder to application folder 

### ISSUE THREAD

**Issue by feipenghe** [spyder-ide/spyder#10031]
## Description

**What steps will reproduce the problem?**

1. dragging  Anaconda/bin/spyder to application folder
2. start it

**What is the expected output? What do you see instead?**
I expected it to run normally, instead, I see the following warnings.

**Please provide any additional information below**

  File "/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 114, in _save
    _write_file(fname)
  File "/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 110, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: 'sn_0_13167758/.spyproject/workspace.ini'

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/spyder/plugins/projects.py", line 149, in <lambda>
    lambda v: self.editor.setup_open_files())
  File "/anaconda3/lib/python3.6/site-packages/spyder/plugins/editor.py", line 2660, in setup_open_files
    filenames = self.projects.get_project_filenames()
  File "/anaconda3/lib/python3.6/site-packages/spyder/plugins/projects.py", line 317, in get_project_filenames
    recent_files = self.current_active_project.get_recent_files()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/projects/type/__init__.py", line 79, in get_recent_files
    default=[])
  File "/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 380, in get
    self.set(section, option, default)
  File "/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 448, in set
    self._save()
  File "/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 124, in _save
    raise(e)
  File "/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 120, in _save
    _write_file(fname)
  File "/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 110, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: 'sn_0_13167758/.spyproject/workspace.ini'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.14.2 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.4.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening Terminal.app and running there

    conda install spyder=3.3.6
