### ISSUE TITLE
Missing PyQT/Pyside is hard to diagnose for new python/spyder users

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1003]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2012-04-23T13:45:54Z_

What steps will reproduce the problem?

 1. Attempt to start spyder without PyQt or PySide installed. What is the expected output? What do you see instead? Spyder needs to provide better feedback when PyQt or PySide can't be found.  New users try to run spyder and depending on the speed of their PC a console window quickly opens and then closes (or doesn't appear at all!).  They have no idea what's happening or why Spyder isn't working.  It seems like there are a few options here like catching the exception and using raw_input to temporarily halt execution to make sure they are able to see the output generated. What version of the product are you using? On what operating system? 2.1.9, Windows XP SP3 

Please provide any additional information below

. C:\Python26\python.exe "C:\Python26\Scripts\spyder"
Traceback (most recent call last):
  File "C:\Python26\Scripts\spyder", line 2, in \<module>
    from spyderlib import spyder
  File "C:\Python26\lib\site-packages\spyderlib\spyder.py", line 31, in \<module>
    from spyderlib import qt #analysis:ignore
  File "C:\Python26\lib\site-packages\spyderlib\qt\__init__.py", line 39, in \<mo
dule>
    raise ImportError("Spyder requires PySide or PyQt to be installed")
ImportError: Spyder requires PySide or PyQt to be installed

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1003_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-23T13:15:47Z_

Well obviously that's not the intended behavior.
There used to be a Tkinter-based pop-up dialog warning the user that no GUI toolkit was installed. The feature must have been broken with recent changes.

I'll look into it.

**Owner:** pierre.raybaut  
  **Labels:** -Priority-Medium Priority-Critical MS-v2.1

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-23T13:29:47Z_

**Status:** Accepted

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-23T13:30:20Z_

Revision 9c4649090f0a broke the feature you are referring to.

**Comment by spyder-issues-migrator** [comment]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2012-04-23T13:50:15Z_

Ahh.. I thought we had addressed this before.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-24T03:11:21Z_

This issue was updated by revision 8f379d5da67c .

**Status:** Fixed
