### ISSUE TITLE
You are the devs, figure it out

### ISSUE THREAD

**Issue by zdhughes5** [spyder-ide/spyder#10052]
### What steps will reproduce the problem?

conda update --all
spyder --new-instance &

ta-da!

### Traceback
```python-traceback
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole.py", line 1178, in <lambda>
    kc.started_channels.connect(lambda c=client: self.process_started(c))
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole.py", line 1753, in process_started
    self.variableexplorer.add_shellwidget(client.shellwidget)
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/spyder/plugins/variableexplorer.py", line 171, in add_shellwidget
    nsb.setup(**self.get_settings())
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/spyder/plugins/variableexplorer.py", line 107, in get_settings
    settings[name] = self.get_option(name)
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/spyder/api/plugins.py", line 177, in get_option
    return CONF.get(self.CONF_SECTION, option, default)
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/spyder/config/user.py", line 382, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'show_callable_attributes' in section: 'variable_explorer'
Traceback (most recent call last):
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 219, in _handle_execute_reply
    self.set_namespace_view_settings()
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 73, in set_namespace_view_settings
    settings = to_text_string(self.namespacebrowser.get_view_settings())
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/namespacebrowser.py", line 239, in get_view_settings
    settings[name] = getattr(self, name)
AttributeError: 'NamespaceBrowser' object has no attribute 'show_callable_attributes'
```

## Versions

* Spyder version: 4.0.0b1 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 5.1.6-1.el7.elrepo.x86_64

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.11.0     :  0.15.1 (OK)
psutil >=0.3      :  5.6.3 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.25.0 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.5.3 (OK)
IPython >=4.0     :  7.7.0 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by bcolsen** [comment]
> Spyder version: 4.0.0b1

Thank you for testing our beta version of Spyder4. Unfortunately your version (Beta 1) is out of date and not supported. Please upgrade to our latest (and much improved) beta version by using these commands and see if that fixes your problem:  

    conda update qt pyqt
    conda install -c spyder-ide python-language-server
    conda install -c spyder-ide spyder=4.0.0b4

That should update your `spyder-kernels` as well to fix your problem.
