### ISSUE TITLE
Spyder crashes when using piexif

### ISSUE THREAD

**Issue by chandang78** [spyder-ide/spyder#10063]
I am trying to read the exif information of an image using piexif. When I use the variable explorer to view the exif dict, it throws Spyder internal error and spyder crashes.

Error it returns:
```python-traceback
 File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 313, in data
    display = value_to_display(value, minmax=self.minmax)
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\utils.py", line 458, in value_to_display
    display = display[:70].rstrip() + ' ...'
TypeError: can't concat str to bytes
Traceback (most recent call last):
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 313, in data
    display = value_to_display(value, minmax=self.minmax)
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\utils.py", line 458, in value_to_display
    display = display[:70].rstrip() + ' ...'
TypeError: can't concat str to bytes
Traceback (most recent call last):
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 313, in data
    display = value_to_display(value, minmax=self.minmax)
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\utils.py", line 458, in value_to_display
    display = display[:70].rstrip() + ' ...'
TypeError: can't concat str to bytes
Traceback (most recent call last):
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 313, in data
    display = value_to_display(value, minmax=self.minmax)
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\utils.py", line 458, in value_to_display
    display = display[:70].rstrip() + ' ...'
TypeError: can't concat str to bytes
Traceback (most recent call last):
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 313, in data
    display = value_to_display(value, minmax=self.minmax)
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\utils.py", line 458, in value_to_display
    display = display[:70].rstrip() + ' ...'
TypeError: can't concat str to bytes
Traceback (most recent call last):
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 313, in data
    display = value_to_display(value, minmax=self.minmax)
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\utils.py", line 458, in value_to_display
    display = display[:70].rstrip() + ' ...'
TypeError: can't concat str to bytes
Traceback (most recent call last):
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 313, in data
    display = value_to_display(value, minmax=self.minmax)
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\utils.py", line 458, in value_to_display
    display = display[:70].rstrip() + ' ...'
TypeError: can't concat str to bytes
Traceback (most recent call last):
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 313, in data
    display = value_to_display(value, minmax=self.minmax)
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\utils.py", line 458, in value_to_display
    display = display[:70].rstrip() + ' ...'
TypeError: can't concat str to bytes
Traceback (most recent call last):
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 313, in data
    display = value_to_display(value, minmax=self.minmax)
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\utils.py", line 458, in value_to_display
    display = display[:70].rstrip() + ' ...'
TypeError: can't concat str to bytes
Traceback (most recent call last):
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 313, in data
    display = value_to_display(value, minmax=self.minmax)
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\utils.py", line 458, in value_to_display
    display = display[:70].rstrip() + ' ...'
TypeError: can't concat str to bytes
Traceback (most recent call last):
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 313, in data
    display = value_to_display(value, minmax=self.minmax)
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\utils.py", line 458, in value_to_display
    display = display[:70].rstrip() + ' ...'
TypeError: can't concat str to bytes
Traceback (most recent call last):
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 313, in data
    display = value_to_display(value, minmax=self.minmax)
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\utils.py", line 458, in value_to_display
    display = display[:70].rstrip() + ' ...'
TypeError: can't concat str to bytes
Traceback (most recent call last):
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 313, in data
    display = value_to_display(value, minmax=self.minmax)
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\utils.py", line 458, in value_to_display
    display = display[:70].rstrip() + ' ...'
TypeError: can't concat str to bytes
Traceback (most recent call last):
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 313, in data
    display = value_to_display(value, minmax=self.minmax)
  File "E:\conda\lib\site-packages\spyder\widgets\variableexplorer\utils.py", line 458, in value_to_display
    display = display[:70].rstrip() + ' ...'
TypeError: can't concat str to bytes

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.6
