### ISSUE TITLE
template-dir not copied on install (jinja2.exceptions.TemplateNotFound: warning.html)

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1007]
_From [FinnSa...@gmail.com](https://code.google.com/u/105862207814266386083/) on 2012-04-28T07:06:45Z_

Spyder Version:  2.2.0dev
Python Version:  2.6.5
Qt Version:      4.7.0, PyQt4 (API v1) 4.7.3 on Linux 

What steps will reproduce the problem?

 1. Open or close the object explorer window What is the expected output? What do you see instead? Expected output
An error message in the "Object inspector" window saying "no documentation available"

Actual output:
Nothing in the object inspector window

But in the "Internal console":

\>>> Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/plugins/__init__.py", line 201, in visibility_changed
    self.refresh_plugin() #XXX Is it a good idea?
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/plugins/inspector.py", line 378, in refresh_plugin
    self.set_object_text(None, force_refresh=False)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/plugins/inspector.py", line 573, in set_object_text
    found = self.show_help(text, ignore_unknown=ignore_unknown)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/plugins/inspector.py", line 766, in show_help
    self.set_sphinx_text(doc_text)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/plugins/inspector.py", line 735, in set_sphinx_text
    html_text = warning(self.no_doc_string)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/utils/inspector/sphinxify.py", line 53, in warning
    warning = env.get_template("warning.html")
  File "/usr/lib/pymodules/python2.6/jinja2/environment.py", line 557, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/pymodules/python2.6/jinja2/environment.py", line 537, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/pymodules/python2.6/jinja2/loaders.py", line 96, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib/pymodules/python2.6/jinja2/loaders.py", line 161, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: warning.html 

Please provide any additional information below

. This is solved by manually copying 

"/path-to-src/spyderlib/utils/inspector/templates"
to
"/usr/local/lib/python2.6/dist-packages/spyderlib/utils/inspector/templates"

My system:
python-jinja2 version: 2.3.1-1

$ lsb_release 
LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch

$ uname -a
Linux servername 2.6.38-14-generic `#58`~lucid1-Ubuntu SMP Thu Mar 29 15:43:21 UTC 2012 x86_64 GNU/Linux

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1007_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-28T05:09:14Z_

**Status:** Accepted  
  **Owner:** ccordoba12  
  **Cc:** pierre.raybaut  
  **Labels:** Cat-ObjectInspector

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-04-28T07:50:14Z_

The problem is we're not adding the templates and js files needed by th OI during installation. issue #994 has a fix I'm going to add soon

**Status:** Duplicate  
  **Mergedinto:** 994
