### ISSUE TITLE
Fail on context menu call in project explorer when project files are inside symlinked dir

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1008]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-04-30T05:07:06Z_

Spyder Version:  2.2.0dev (7b826664c296+)
Python Version:  2.7.2
Qt Version:      4.8.0, PyQt4 (API v1) 4.8.6 on Linux 

What steps will reproduce the problem?

 1. Move all files to symlinked folder
2. Open project through a symplink
3. Left click on a project What is the expected output? What do you see instead? Traceback (most recent call last):
  File "/ext/p/spyderlib/spyderlib/widgets/explorer.py", line 343, in contextMenuEvent
    self.update_menu()
  File "/ext/p/spyderlib/spyderlib/widgets/explorer.py", line 338, in update_menu
    add_actions(self.menu, self.create_context_menu_actions())
  File "/ext/p/spyderlib/spyderlib/widgets/projectexplorer.py", line 597, in create_context_menu_actions
    return FilteredDirView.create_context_menu_actions(self)
  File "/ext/p/spyderlib/spyderlib/widgets/explorer.py", line 325, in create_context_menu_actions
    actions += self.create_file_manage_actions(fnames)
  File "/ext/p/spyderlib/spyderlib/widgets/projectexplorer.py", line 527, in create_file_manage_actions
    any_project = any([_pr.is_root_path(_fn) for _pr, _fn in pjfnames])
AttributeError: 'NoneType' object has no attribute 'is_root_path'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1008_

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-04-30T03:15:56Z_

Fixed by revision a0aeaa7d9c3e .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-04-06T20:22:18Z_

**Labels:** Cat-ProjectExplorer
