### ISSUE TITLE
Bootstrap on v21 repository fails

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1013]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-05-02T10:27:28Z_

Spyder Version:  2.1.9 ( revision 8e43fb421809 from v21 repo)
Python Version:  2.7.2
Qt Version:      4.7.4, PyQt4 (API v2) 4.8.6 on Windows 

What steps will reproduce the problem?

 1. pull above noted revision
2 . try to launch using bootstrap.y What is the expected output? What do you see instead? Fails with this traceback:

C:\src\jedludlow-spyderlib-v21>bootstrap.py --gui pyqt
Executing Spyder from source checkout Revision 1926 :8e43fb421809, Branch: default
01. Patched sys.path with C:\src\jedludlow-spyderlib-v21
02. Skipping GUI toolkit detection
Traceback (most recent call last):
  File "C:\src\jedludlow-spyderlib-v21\bootstrap.py", line 77, in \<module>
    QT_API = spyder.qt._modname
AttributeError: 'module' object has no attribute '_modname'

Or this traceback if PySide is selected:

C:\src\jedludlow-spyderlib-v21>bootstrap.py --gui pyside
Executing Spyder from source checkout Revision 1926 :8e43fb421809, Branch: default
01. Patched sys.path with C:\src\jedludlow-spyderlib-v21
02. Skipping GUI toolkit detection
Traceback (most recent call last):
  File "C:\src\jedludlow-spyderlib-v21\bootstrap.py", line 76, in \<module>
    from spyderlib import spyder
  File "C:\src\jedludlow-spyderlib-v21\spyderlib\spyder.py", line 74, in \<module
\>
    from spyderlib.qt.QtGui import (QApplication, QMainWindow, QSplashScreen,
  File "C:\src\jedludlow-spyderlib-v21\spyderlib\qt\__init__.py", line 41, in \<m
odule>
    from PySide import *  #analysis:ignore
ImportError: DLL load failed: The specified procedure could not be found.

Please provide any additional information below

.
Potential fix to follow.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1013_

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-05-02T08:46:17Z_

Pull Request:

I back-ported the changes from the default repository that both Anatoly and Pierre had produced that solved this issue. They can be pulled from my clone at bookmark issue-1013. https://code.google.com/r/jedludlow-spyderlib-v21/ Tested on Win 7 (both ascii and non-ascii usernames, both PyQt and PYSide) and Ubuntu 11.10 (with just PyQt).

The clone should be open for code review, so feel free to hack them up. If the changes are satisfactory, please pull in the v21 repository.

**Cc:** ccordoba12 pierre.raybaut techtonik@gmail.com

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-05-02T10:31:25Z_

**Labels:** MS-v2.1

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-05-02T11:03:02Z_

It's working great for me. If they are only backported commits, I think there shouldn't represent much of a problem, but let's wait until Anatoly or Pierre say something.

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-05-02T11:09:36Z_

Well, bootstrap is not a critical part. I've tested the checkout works on Linux and generally change seems ok. I can't say if it won't break packaging, because I always use Spyder from source. =)

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-05-02T11:15:18Z_

I marked it critical because of the PySide failure more than the bootstrap problem. That said, I'm always running from source, too. For any other developers that do the same a bootstrap failure is critical :).

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-05-02T12:09:52Z_

I'll check installation in a virtualenv, and if everything goes well I'll merge this in in a couple of minutes.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-05-02T12:18:18Z_

Jed, one more thing I almost forgot: please update the changelog in your branch because you know better than me what these changes are about.

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-05-02T13:01:26Z_

CHANGELOG has been updated.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-05-02T13:10:48Z_

Ok, thanks a lot for your quick response. I merged it.

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-05-02T13:15:34Z_

**Status:** Verified
