### ISSUE TITLE
KeyError raised in internal console by spyderlib.widgets.editor.ThreadManager

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1016]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-05-05T13:34:58Z_

See the bug report here: http://groups.google.com/group/pythonxy/browse_thread/thread/255fd98b96ee7ceb?hl=en Here is a transcription:

[...] the Internal console reports a stream of error messages that look like this:

File "C:\Python27\lib\site-packages\spyderlib\widgets\editor.py", line 
228, in update_queue 
    end_callback = self.end_callbacks.pop(id(thread)) 
KeyError: 92950864

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1016_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-05-05T11:40:32Z_

This bug is weird. I'm looking at the code ( https://code.google.com/p/spyderlib/source/browse/spyderlib/widgets/editor.py?repo=v21#228 ) and I see no reason why this should happen.

To better understand what's going on, XCL: could you enable Spyder's debug mode?
(you just have to create an environment variable named SPYDER_DEBUG and put "true" in it)

**Comment by spyder-issues-migrator** [comment]
_From [x.colonn...@gmail.com](https://code.google.com/u/116095276015245379486/) on 2012-05-05T17:43:46Z_

Well, I can't reproduce the issue at this point. My computer went into hybernation and when I restarted my user session Spyder was not-responding. I killed all three python processes and started Spyder again via the Python(x,y) launcher (as I did the first time around). However, in the earlier session, the Spyder console was showing three tabs for the default python interpreter ("python 1"): "Console", "Internal Console" and "History Log". This time around I only see two tabs, "Console" and "History Log". I don't know what I did differently to end up this way but there are no longer any error messages when I run my code.

Let me know if you'd still like me to run any diagnostics. By the way, I saw that the Python(x,y) window offers the option to launch Spyder with the "--debug" option. Is that equivalent to setting the environment variable SPYDER_DEBUG?

Thanks for the quick response and sorry for the distraction.

X

**Comment by spyder-issues-migrator** [comment]
_From [bwanama...@gmail.com](https://code.google.com/u/114749747116603825948/) on 2012-06-14T00:09:49Z_

This didn't start happening to me until I upgraded pep8 from version 0.7 to 1.2, then I get it after I've been working for a while, and then it doesn't stop. I tried disabling pep8 and I think it went away, but maybe I wasn't working long enough. The trackback first starts with pyflakes and pep8 - I will post it later - at lines 229 and some 400ish lines. Then just the KeyError on line 228 forever, same as above.

**Comment by spyder-issues-migrator** [comment]
_From [cb750m...@gmail.com](https://code.google.com/u/100240511086671041257/) on 2012-06-18T10:11:32Z_

This issue is 100% repeatable on my system.  And it's a real show-stopper:  it happens every few seconds while typing in new source code, and it usually yanks the keyboard focus out of source code & into the Internal Console window.  This makes Spyder unusable.  That's a shame because I'm looking for a Python source-level debugger just like this one.

System details:
Windows 7 Pro x64
Python distro: python-2.7.3.x64.msi from python.org
PyQt-Py2.7-x64-gpl-4.9.1-1.exe from riverbankcomputing
spyder-2.1.10_py27.exe

I'd be happy to provide more info or run tests.  Here are several of the tracebacks:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\widgets\editor.py", line 170, in run
    self.results = self.checker(self.source_code)
  File "C:\Python27\lib\site-packages\spyderlib\utils\codeanalysis.py", line 46, in check_with_pyflakes
    tree = compile(source_code, filename, "exec", _ast.PyCF_ONLY_AST)
ValueError: invalid \x escape
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\widgets\editor.py", line 228, in update_queue
    end_callback = self.end_callbacks.pop(id(thread))
KeyError: 65937480L
  File "C:\Python27\lib\site-packages\spyderlib\widgets\editor.py", line 229, in update_queue
    end_callback(thread.results)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\editor.py", line 417, in pyflakes_analysis_finished
    self.code_analysis_finished()
  File "C:\Python27\lib\site-packages\spyderlib\widgets\editor.py", line 427, in code_analysis_finished
    self.set_analysis_results(self.pyflakes_results+self.pep8_results)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\widgets\editor.py", line 228, in update_queue
    end_callback = self.end_callbacks.pop(id(thread))
KeyError: 65937480L
  File "C:\Python27\lib\site-packages\spyderlib\widgets\editor.py", line 228, in update_queue
    end_callback = self.end_callbacks.pop(id(thread))
KeyError: 65937480L
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\widgets\editor.py", line 228, in update_queue
    end_callback = self.end_callbacks.pop(id(thread))
KeyError: 65937480L
  File "C:\Python27\lib\site-packages\spyderlib\widgets\editor.py", line 228, in update_queue
    end_callback = self.end_callbacks.pop(id(thread))

\--
cb750mark

**Comment by spyder-issues-migrator** [comment]
_From [cb750m...@gmail.com](https://code.google.com/u/100240511086671041257/) on 2012-06-18T10:15:06Z_

So far I haven't noticed any other adverse side effects from this issue.  So it would be fine e.g. as a workaround if it simply stopped yanking the keyboard focus over to the console window every time the console output some text.

Thanks for looking into this.

\--
cb750mark

**Comment by spyder-issues-migrator** [comment]
_From [cb750m...@gmail.com](https://code.google.com/u/100240511086671041257/) on 2012-06-18T15:01:02Z_

FYI - I have found that undocking the Internal Console window, so it has its own floating window, seems to prevent Spyder from yanking the keyboard focus into the Internal Console.  This prevents the most damaging symptom of this issue (for me anyway).  I've been able to write & debug code all day this way, with no occurrences of the symptom.

The window is docked by default when Spyder is first installed in the environment I described earlier.

\--
cb750mark

**Comment by spyder-issues-migrator** [comment]
_From [bwanama...@gmail.com](https://code.google.com/u/114749747116603825948/) on 2012-06-18T15:33:37Z_

here is the traceback for comment `#4`, sorry I didn't post it earlier

Python 2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license" for more information.

\>>> Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\widgets\editor.py", line 170, in run
    self.results = self.checker(self.source_code)
  File "C:\Python27\lib\site-packages\spyderlib\utils\codeanalysis.py", line 127, in check_with_pep8
    return check(args, source_code, filename=filename, options=['-r'])
  File "C:\Python27\lib\site-packages\spyderlib\utils\codeanalysis.py", line 118, in check
    if 'analysis:ignore' not in lines[lineno-1]:
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\widgets\editor.py", line 229, in update_queue
    end_callback(thread.results)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\editor.py", line 423, in pep8_analysis_finished
    self.code_analysis_finished()
  File "C:\Python27\lib\site-packages\spyderlib\widgets\editor.py", line 427, in code_analysis_finished
    self.set_analysis_results(self.pyflakes_results+self.pep8_results)
TypeError: can only concatenate list (not "NoneType") to list

has anyone tried the debug option, or disabling pep8 in code anaylsis?

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-06-19T15:48:35Z_

It should be pretty easy to insert print statements to read exact values of self.pyflakes_results and self.pep8_results from console.

**Comment by spyder-issues-migrator** [comment]
_From [bwanama...@gmail.com](https://code.google.com/u/114749747116603825948/) on 2012-06-20T11:52:42Z_

Since disabling the pep8 code analysis, I have not had the keyerror.

I was able to download an older version of pep8 that predates the problem http://pypi.python.org/packages/source/p/pep8/pep8-0.7.0.tar.gz I would suggest freezing pep8 & pylint at working version for spyderlib, and including them in the spyderlib and hard coding the paths to spyderlib's local version.

**Attachment:** [pep8-0.7.0.tar.gz](http://code.google.com/p/spyderlib/issues/detail?id=1016#hc10)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-07-28T05:24:01Z_

Issues reported by cb750mark and bwanamarko are similar but not identical: the KeyError exception in ThreadManager happens when the code analysis thread was not executed successfully.

cb750mark's Issue: pyflakes analysis crashes
bwanamarko's Issue: pep8 analysis gives unexpected result

@-cb750mark: it would be very helpful if you could tell us what version of pyflakes you are using?
BTW, this bug is a pyflakes bug: https://bugs.launchpad.net/pyflakes/+bug/1005602 I'm handling this bug in Spyder (see revision be0e92a9cd71 ), as well as another similar bug I found out.

@-bwanamarko:
1. I'm unable to reproduce this bug when using pep8 1.2: could you try and reproduce it again? (maybe this is happening only when analyzing a specific file?)
2. We won't include pep8, pylint or pyflakes in spyderlib as this is just transposing the problem, not solving it. Besides, this is not how Python packages should work.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-07-28T05:24:31Z_

This issue was updated by revision be0e92a9cd71 .


This revision fixes a part of issue #1016 by handling the following bugs: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=674796 http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=674797

**Status:** Started

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-07-28T05:24:32Z_

This issue was updated by revision 02e7a5035129 .

**Comment by spyder-issues-migrator** [comment]
_From [cb750m...@gmail.com](https://code.google.com/u/100240511086671041257/) on 2012-07-28T11:25:39Z_

I don't know what pyflakes is.  I'll need instructions to find out its
version.

if it helps, I installed spyder from spyder-2.1.10_py27_x86_x64.exe (I
might have decorated the filename a bit) and python-2.7.3.x64.msi, the
latter from python.org.  I think there were no other component installers.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-07-28T13:43:55Z_

Actually, I wrote the question earlier when entering my comment, and following revision be0e92a9cd71 , it's no longer necessary as I know now that the bug concerns all existing pyflakes versions.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-09-01T06:33:55Z_

issue #1142 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [mvi...@gmail.com](https://code.google.com/u/108668877517097490134/) on 2012-09-09T06:39:04Z_

May I suggest that, in general, the internal console should NEVER pop up and steal the keyboard focus? Because that design decision seems to be the real issue here... fixing whatever problem pyflakes may have is only asking for this exact scenario to be repeated in the future for each and every irrelevant exception the libraries may raise. :(

**Comment by spyder-issues-migrator** [comment]
_From [mvi...@gmail.com](https://code.google.com/u/108668877517097490134/) on 2012-09-09T06:59:15Z_

This is the workaround I used, editing spyderlib/plugins/console.py

Change line 16 from:

from spyderlib.qt.QtCore import SIGNAL

to:

from spyderlib.qt.QtCore import Qt, SIGNAL

Then at line 89, at the end of the constructor, add this code:

        \# Don't steal the keyboard focus
        self.setAttribute(Qt.WA_ShowWithoutActivating)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-09-09T07:02:06Z_

With this change, the internal console will be shown but won't steal focus. I thought that you wanted that the internal console would not be shown, didn't you?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-09-09T07:35:51Z_

(I've simply added an option to disable the "automatic internal console popup on error" feature, in Preferences/General -- it's disabled by default)
(will commit this change ASAP)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-09-09T08:21:14Z_

This issue was updated by revision dd1ac6703caf .


Here is the change I was referring to in comment #21

**Comment by spyder-issues-migrator** [comment]
_From [mvi...@gmail.com](https://code.google.com/u/108668877517097490134/) on 2012-09-09T14:02:34Z_

I don't mind the internal console being shown, it's just that stealing keyboard focus while typing some code feels quite disruptive. I definitely agree it should be an option, mine was just a quick hack! :D

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-09-23T05:08:15Z_

As I wrote in comment `#11`:

@-bwanamarko:
I'm unable to reproduce this bug when using pep8 1.2: could you try and reproduce it again? (maybe this is happening only when analyzing a specific file?)

Without this information, I'll close this issue and mark it as fixed, as it is already partly fixed.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-01-05T02:55:30Z_

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-04-13T09:47:24Z_

issue #1342 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-06-02T01:16:02Z_

**Blocking:** spyderlib:945
