### ISSUE TITLE
Crash upon startup with spyder-notebook

### ISSUE THREAD

**Issue by utting** [spyder-ide/spyder#10187]
### What steps will reproduce the problem?

Install latest Anaconda (2019.07 with Python 3.7)
Install spyder-notebook: (0.1.4 from spyder-ide)

Start spyder:
$ spyder
$ spyder --reset
$ spyder --defaults
These all gave an exception "ValueError: failed to parse CPython sys.version: '3.7.0 (default, Jun 28 2018..."

So then I updated Python to 3.7.4:
$ conda install -c anaconda python=3.7.4
$ spyder  
This gave this error that I am reporting.

### Traceback
```python-traceback
  File "/Users/utting/anaconda3/envs/ict709_collusion_detector/lib/python3.7/site-packages/spyder/plugins/ipythonconsole.py", line 1178, in <lambda>
    kc.started_channels.connect(lambda c=client: self.process_started(c))
  File "/Users/utting/anaconda3/envs/ict709_collusion_detector/lib/python3.7/site-packages/spyder/plugins/ipythonconsole.py", line 1753, in process_started
    self.variableexplorer.add_shellwidget(client.shellwidget)
  File "/Users/utting/anaconda3/envs/ict709_collusion_detector/lib/python3.7/site-packages/spyder/plugins/variableexplorer.py", line 171, in add_shellwidget
    nsb.setup(**self.get_settings())
  File "/Users/utting/anaconda3/envs/ict709_collusion_detector/lib/python3.7/site-packages/spyder/plugins/variableexplorer.py", line 107, in get_settings
    settings[name] = self.get_option(name)
  File "/Users/utting/anaconda3/envs/ict709_collusion_detector/lib/python3.7/site-packages/spyder/api/plugins.py", line 177, in get_option
    return CONF.get(self.CONF_SECTION, option, default)
  File "/Users/utting/anaconda3/envs/ict709_collusion_detector/lib/python3.7/site-packages/spyder/config/user.py", line 382, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'show_callable_attributes' in section: 'variable_explorer'
Traceback (most recent call last):
  File "/Users/utting/anaconda3/envs/ict709_collusion_detector/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/utting/anaconda3/envs/ict709_collusion_detector/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 219, in _handle_execute_reply
      File "/Users/utting/anaconda3/envs/ict709_collusion_detector/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 73, in set_namespace_view_settings
    settings = to_text_string(self.namespacebrowser.get_view_settings())
  File "/Users/utting/anaconda3/envs/ict709_collusion_detector/lib/python3.7/site-packages/spyder/widgets/variableexplorer/namespacebrowser.py", line 239, in get_view_settings
    settings[name] = getattr(self, name)
AttributeError: 'NamespaceBrowser' object has no attribute 'show_callable_attributes'
```

## Versions

* Spyder version: 4.0.0b1 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.7.0

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.11.0     :  0.15.1 (OK)
psutil >=0.3      :  5.6.3 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.17.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.5.4 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
Your error is not related to spyder-notebook and it was already fixed in beta4, so please update.

However, spyder-notebook is not compatible with Spyder 4, so I'm afraid you'll have to uninstall it
