### ISSUE TITLE
Dataframe previews won't open : beta4

### ISSUE THREAD

**Issue by Pigankle** [spyder-ide/spyder#10184]
### What steps will reproduce the problem?

Doubleclick on a fairly small dataframe in the variables explorer (8300 x 16)  The dataframe doesn't open, instead the issue reporter does.  This is an issue with all of my dataframes.  I otherwise have no trouble working with them (plotting, etc, from the console.)  This issue did not exist in beta 2.

### Traceback
```python-traceback
  File "/Users/chinkapin/anaconda3/envs/spyder-beta4/lib/python3.7/site-packages/spyder/plugins/variableexplorer/widgets/objectexplorer/tree_model.py", line 267, in fetchMore
    parent_item.obj_path)
  File "/Users/chinkapin/anaconda3/envs/spyder-beta4/lib/python3.7/site-packages/spyder/plugins/variableexplorer/widgets/objectexplorer/tree_model.py", line 322, in _fetchObjectChildren
    for attr_name, attr_value in sorted(inspect.getmembers(obj)):
  File "/Users/chinkapin/anaconda3/envs/spyder-beta4/lib/python3.7/inspect.py", line 341, in getmembers
    value = getattr(object, key)
  File "/Users/chinkapin/anaconda3/envs/spyder-beta4/lib/python3.7/site-packages/pandas/core/frame.py", line 392, in _constructor_expanddim
    raise NotImplementedError("Not supported for DataFrames!")
NotImplementedError: Not supported for DataFrames!
Traceback (most recent call last):
  File "/Users/chinkapin/anaconda3/envs/spyder-beta4/lib/python3.7/site-packages/spyder/plugins/variableexplorer/widgets/objectexplorer/tree_model.py", line 267, in fetchMore
    parent_item.obj_path)
  File "/Users/chinkapin/anaconda3/envs/spyder-beta4/lib/python3.7/site-packages/spyder/plugins/variableexplorer/widgets/objectexplorer/tree_model.py", line 322, in _fetchObjectChildren
    for attr_name, attr_value in sorted(inspect.getmembers(obj)):
  File "/Users/chinkapin/anaconda3/envs/spyder-beta4/lib/python3.7/inspect.py", line 341, in getmembers
    value = getattr(object, key)
  File "/Users/chinkapin/anaconda3/envs/spyder-beta4/lib/python3.7/site-packages/pandas/core/frame.py", line 392, in _constructor_expanddim
    raise NotImplementedError("Not supported for DataFrames!")
NotImplementedError: Not supported for DataFrames!
```

## Versions

* Spyder version: 4.0.0b4 
* Python version: 3.7.1
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.6.0

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
psutil >=0.3      :  5.6.3 (OK)
pyls >=0.27.0     :  0.28.3 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  None (OK)
numpy >=1.7       :  None (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.5.2 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  None (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
@Pigankle, I'm going to close this one for now. Please reopen it after beta5 is released in case it hasn't been fixed in that version.

**Comment by Pigankle** [comment]
OK - I'll check again at next release.  Thanks for looking into the issue.
