### ISSUE TITLE
Installing Spyder 4.0.0b5 gives error about DEBUG menuinst_win32:__init__(199):

### ISSUE THREAD

**Issue by richdevboston** [spyder-ide/spyder#10206]
# Problem Description

Installing v4 beta5 gives errors, then Spyder throws PyQt5.QtWebKitWidgets "ModuleNotFoundError:
Executing transaction: \ DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\ProgramData\Anaconda3\envs\quantecon', env_name: 'quantecon', mode: 'system', used_mode: 'system'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\ProgramData\Anaconda3\pythonw.exe, args are ['C:\\ProgramData\\Anaconda3\\cwp.py', 'C:\\ProgramData\\Anaconda3\\envs\\quantecon', 'C:\\ProgramData\\Anaconda3\\envs\\quantecon\\pythonw.exe', 'C:\\ProgramData\\Anaconda3\\envs\\quantecon\\Scripts\\spyder-script.py']
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\ProgramData\Anaconda3\python.exe, args are ['C:\\ProgramData\\Anaconda3\\cwp.py', 'C:\\ProgramData\\Anaconda3\\envs\\quantecon', 'C:\\ProgramData\\Anaconda3\\envs\\quantecon\\python.exe', 'C:\\ProgramData\\Anaconda3\\envs\\quantecon\\Scripts\\spyder-script.py', '--reset']

### What steps reproduce the problem?

1.  I ran `conda update qt pyqt` to update qt and pyqt to make sure those were current.   I did not have any error messages.  
2.  I ran `conda install -c spyder-ide spyder=4.0.0b5` and then I got :

```Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\ProgramData\Anaconda3\envs\quantecon

  added / updated specs:
    - spyder=4.0.0b5

The following NEW packages will be INSTALLED:
  alabaster          conda-forge/noarch::alabaster-0.7.12-py_0
  argh               spyder-ide/win-64::argh-0.26.2-py37_1001
  astroid            conda-forge/win-64::astroid-2.2.5-py37_0
  atomicwrites       conda-forge/noarch::atomicwrites-1.3.0-py_0
  autopep8           conda-forge/noarch::autopep8-1.4.4-py_0
  babel              conda-forge/noarch::babel-2.7.0-py_0
  cloudpickle        conda-forge/noarch::cloudpickle-1.2.2-py_0
  diff-match-patch   spyder-ide/noarch::diff-match-patch-20181111-py_0
  docutils           conda-forge/win-64::docutils-0.15.2-py37_0
  future             conda-forge/win-64::future-0.17.1-py37_1000
  imagesize          conda-forge/noarch::imagesize-1.1.0-py_0
  importlib_metadata conda-forge/win-64::importlib_metadata-0.22-py37_0
  isort              conda-forge/win-64::isort-4.3.21-py37_0
  keyring            conda-forge/win-64::keyring-19.2.0-py37_0
  lazy-object-proxy  conda-forge/win-64::lazy-object-proxy-1.4.2-py37hfa6e2cd_0
  libspatialindex    conda-forge/win-64::libspatialindex-1.8.5-he025d50_4
  mccabe             conda-forge/noarch::mccabe-0.6.1-py_1
  numpydoc           conda-forge/noarch::numpydoc-0.9.1-py_0
  packaging          conda-forge/noarch::packaging-19.0-py_0
  pathtools          spyder-ide/noarch::pathtools-0.1.2-py_1
  pexpect            conda-forge/win-64::pexpect-4.7.0-py37_0
  pluggy             conda-forge/win-64::pluggy-0.13.0-py37_0
  psutil             conda-forge/win-64::psutil-5.6.3-py37hfa6e2cd_0
  pycodestyle        conda-forge/noarch::pycodestyle-2.5.0-py_0
  pydocstyle         conda-forge/noarch::pydocstyle-4.0.1-py_0
  pyflakes           conda-forge/noarch::pyflakes-2.1.1-py_0
  pylint             conda-forge/win-64::pylint-2.3.1-py37_0
  pympler            spyder-ide/noarch::pympler-0.7-py_0
  python-jsonrpc-se~ spyder-ide/noarch::python-jsonrpc-server-0.2.0-py_0
  python-language-s~ spyder-ide/win-64::python-language-server-0.28.3-py37_0
  pywin32-ctypes     conda-forge/win-64::pywin32-ctypes-0.2.0-py37_1000
  pyxdg              spyder-ide/noarch::pyxdg-0.26-py_0
  qdarkstyle         spyder-ide/noarch::qdarkstyle-2.7-py_0
  qtawesome          conda-forge/noarch::qtawesome-0.6.0-py_0
  qtpy               conda-forge/noarch::qtpy-1.9.0-py_0
  rope               conda-forge/noarch::rope-0.14.0-py_0
  rtree              conda-forge/win-64::rtree-0.8.3-py37h21ff451_1002
  snowballstemmer    conda-forge/noarch::snowballstemmer-1.9.1-py_0
  sphinx             conda-forge/noarch::sphinx-2.2.0-py_0
  sphinxcontrib-app~ conda-forge/noarch::sphinxcontrib-applehelp-1.0.1-py_0
  sphinxcontrib-dev~ conda-forge/noarch::sphinxcontrib-devhelp-1.0.1-py_0
  sphinxcontrib-htm~ conda-forge/noarch::sphinxcontrib-htmlhelp-1.0.2-py_0
  sphinxcontrib-jsm~ conda-forge/noarch::sphinxcontrib-jsmath-1.0.1-py_0
  sphinxcontrib-qth~ conda-forge/noarch::sphinxcontrib-qthelp-1.0.2-py_0
  sphinxcontrib-ser~ conda-forge/noarch::sphinxcontrib-serializinghtml-1.1.3-py_0
  spyder             spyder-ide/win-64::spyder-4.0.0b5-py37_0
  spyder-kernels     spyder-ide/win-64::spyder-kernels-1.5.0-py37_0
  watchdog           spyder-ide/win-64::watchdog-0.9.0-py37_1
  wrapt              conda-forge/win-64::wrapt-1.11.2-py37hfa6e2cd_0
  yapf               conda-forge/noarch::yapf-0.28.0-py_0
  zipp               conda-forge/noarch::zipp-0.6.0-py_0

The following packages will be SUPERSEDED by a higher-priority channel:

  jedi                      conda-forge::jedi-0.15.1-py37_0 --> spyder-ide::jedi-0.14.1-py37_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: \ DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\ProgramData\Anaconda3\envs\quantecon', env_name: 'quantecon', mode: 'system', used_mode: 'system'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\ProgramData\Anaconda3\pythonw.exe, args are ['C:\\ProgramData\\Anaconda3\\cwp.py', 'C:\\ProgramData\\Anaconda3\\envs\\quantecon', 'C:\\ProgramData\\Anaconda3\\envs\\quantecon\\pythonw.exe', 'C:\\ProgramData\\Anaconda3\\envs\\quantecon\\Scripts\\spyder-script.py']
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\ProgramData\Anaconda3\python.exe, args are ['C:\\ProgramData\\Anaconda3\\cwp.py', 'C:\\ProgramData\\Anaconda3\\envs\\quantecon', 'C:\\ProgramData\\Anaconda3\\envs\\quantecon\\python.exe', 'C:\\ProgramData\\Anaconda3\\envs\\quantecon\\Scripts\\spyder-script.py', '--reset']
done ```

The program Spyder v4.0.0b5 was installed in Anaconda Navigator okay (it appears in the Navigator.)

3. Then I ran `spyder` from the Anaconda Command Prompt (with Admin privileges) and by clicking the "Launch" icon in Navigator.

### What is the expected output? What do you see instead?

I expected Spyder to start up without error from both the command line and by clicking the Anaconda Navigator icon.

But instead I got the following from the Anaconda Command Prompt when I try to start Spyder with the command >>`spyder` at the command prompt, or from Anaconda Navigator by selecting it from Anaconda Navigator

```
(quantecon) c:\Users\lysak\OneDrive\Desktop>spyder
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\quantecon\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\quantecon\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\envs\quantecon\lib\site-packages\spyder\app\start.py", line 192, in main
    from spyder.app import mainwindow
  File "C:\ProgramData\Anaconda3\envs\quantecon\lib\site-packages\spyder\app\mainwindow.py", line 82, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "C:\ProgramData\Anaconda3\envs\quantecon\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
```

## Versions
<!--- You can get this information from Help > About Spyder...
or (if Spyder won't launch) the "conda list" command
from the Anaconda Prompt/Terminal/command line. --->

* Spyder version:  v4.0.05
* Python version:  3.7
* Qt version: 
* PyQt version:    pyqt                                 5.9.2-py37h6538335_2 --> 5.9.2-py37h6538335_4
* Operating System name/version:   Windows 10

(quantecon) c:\Users\lysak\OneDrive\Desktop>conda list
# packages in environment at C:\ProgramData\Anaconda3\envs\quantecon:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
arachnado                 0.2                      pypi_0    pypi
argh                      0.26.2                py37_1001    spyder-ide
asn1crypto                0.24.0                   pypi_0    pypi
astroid                   2.2.5                    py37_0    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
automat                   0.7.0                    pypi_0    pypi
autopep8                  1.4.4                      py_0    conda-forge
babel                     2.7.0                      py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.0                         mkl
bleach                    3.1.0                      py_0    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
cffi                      1.12.3           py37hb32ad35_0    conda-forge
chardet                   3.0.4                    pypi_0    pypi
cloudpickle               1.2.2                      py_0    conda-forge
colorama                  0.4.1                      py_0    conda-forge
configparser              3.8.1                    pypi_0    pypi
constantly                15.1.0                   pypi_0    pypi
cryptography              2.7              py37hb32ad35_0    conda-forge
cssselect                 1.1.0                    pypi_0    pypi
cycler                    0.10.0                     py_1    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
diff-match-patch          20181111                   py_0    spyder-ide
docopt                    0.6.2                    pypi_0    pypi
docutils                  0.15.2                   py37_0    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
enum34                    1.1.6                    pypi_0    pypi
freetype                  2.10.0               h563cfd7_1    conda-forge
future                    0.17.1                py37_1000    conda-forge
hyperlink                 19.0.0                   pypi_0    pypi
icc_rt                    2019.0.0             h0cc432a_1
icu                       64.2                 he025d50_1    conda-forge
idna                      2.8                      pypi_0    pypi
imagesize                 1.1.0                      py_0    conda-forge
importlib_metadata        0.22                     py37_0    conda-forge
incremental               17.5.0                   pypi_0    pypi
inflection                0.3.1                    py37_1
intel-openmp              2019.4                      245
ipykernel                 5.1.2            py37h5ca1d4c_0    conda-forge
ipython                   7.8.0            py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
isort                     4.3.21                   py37_0    conda-forge
jedi                      0.14.1                   py37_0    spyder-ide
jinja2                    2.10.1                     py_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
jsonschema                3.0.2                    py37_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter-http-over-ws      0.0.6                    pypi_0    pypi
jupyter-wysiwyg           19.05                    py37_0    genepattern
jupyter_client            5.3.1                      py_0    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1                    py37_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyter_highlight_selected_word 0.2.0                 py37_1000    conda-forge
jupyter_latex_envs        1.4.4                 py37_1000    conda-forge
jupyter_nbextensions_configurator 0.4.1                    py37_0    conda-forge
keyring                   19.2.0                   py37_0    conda-forge
kiwisolver                1.1.0            py37he980bc4_0    conda-forge
lazy-object-proxy         1.4.2            py37hfa6e2cd_0    conda-forge
libblas                   3.8.0                    12_mkl    conda-forge
libcblas                  3.8.0                    12_mkl    conda-forge
libiconv                  1.15              hfa6e2cd_1005    conda-forge
liblapack                 3.8.0                    12_mkl    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
libsodium                 1.0.17               h2fa13f4_0    conda-forge
libspatialindex           1.8.5                he025d50_4    conda-forge
libxml2                   2.9.9                h9ce36c8_5    conda-forge
libxslt                   1.1.33               heafd4d3_0    conda-forge
llvmlite                  0.28.0                   py37_0    conda-forge
lxml                      4.4.1            py37heafd4d3_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py37hfa6e2cd_0    conda-forge
matplotlib-base           3.1.1            py37h2852a4a_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py37hfa6e2cd_1000    conda-forge
mkl                       2019.4                      245
more-itertools            7.2.0                      py_0    conda-forge
mpl-finance               0.10.0                   pypi_0    pypi
msys2-conda-epoch         20160418                      1
nbconvert                 5.6.0                    py37_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
notebook                  6.0.1                    py37_0    conda-forge
numba                     0.43.1           py37hf9181ef_0
numbapro_cudalib          0.2                           0    https://repo.anaconda.com/pkgs/free
numpy                     1.17.1           py37hc71023c_0    conda-forge
numpydoc                  0.9.1                      py_0    conda-forge
openssl                   1.1.1c               hfa6e2cd_0    conda-forge
packaging                 19.0                       py_0    conda-forge
pandas                    0.24.2           py37he350917_0    conda-forge
pandas-datareader         0.7.4                    pypi_0    pypi
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parsel                    1.5.2                    pypi_0    pypi
parso                     0.5.1                      py_0    conda-forge
pathtools                 0.1.2                      py_1    spyder-ide
patsy                     0.5.1                      py_0    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pip                       19.2.3                   py37_0    conda-forge
pipenv                    2018.11.26               pypi_0    pypi
pluggy                    0.13.0                   py37_0    conda-forge
prettypandas              0.0.4                    pypi_0    pypi
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
psutil                    5.6.3            py37hfa6e2cd_0    conda-forge
pyasn1                    0.4.6                    pypi_0    pypi
pyasn1-modules            0.2.6                    pypi_0    pypi
pycodestyle               2.5.0                      py_0    conda-forge
pycparser                 2.19                     pypi_0    pypi
pydispatcher              2.0.5                    pypi_0    pypi
pydocstyle                4.0.1                      py_0    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pyhamcrest                1.9.0                    pypi_0    pypi
pylint                    2.3.1                    py37_0    conda-forge
pympler                   0.7                        py_0    spyder-ide
pyopenssl                 19.0.0                   pypi_0    pypi
pyparsing                 2.4.2                      py_0    conda-forge
pyqt                      5.9.2            py37h6538335_4    conda-forge
pyrsistent                0.15.4           py37hfa6e2cd_0    conda-forge
pysocks                   1.7.0                    py37_0    conda-forge
python                    3.7.3                hb12ca83_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-jsonrpc-server     0.2.0                      py_0    spyder-ide
python-language-server    0.28.3                   py37_0    spyder-ide
pytz                      2019.2                     py_0    conda-forge
pywin32-ctypes            0.2.0                 py37_1000    conda-forge
pywinpty                  0.5.5                 py37_1000    conda-forge
pyxdg                     0.26                       py_0    spyder-ide
pyyaml                    5.1.2            py37hfa6e2cd_0    conda-forge
pyzmq                     18.1.0           py37h16f9016_0    conda-forge
qdarkstyle                2.7                        py_0    spyder-ide
qt                        5.9.7                h506e8af_3    conda-forge
qtawesome                 0.6.0                      py_0    conda-forge
qtconsole                 4.5.5                      py_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
quandl                    3.4.6                    py37_0    conda-forge
queuelib                  1.5.0                    pypi_0    pypi
requests                  2.22.0                   py37_1    conda-forge
rope                      0.14.0                     py_0    conda-forge
rtree                     0.8.3           py37h21ff451_1002    conda-forge
scipy                     1.2.1            py37h29ff71c_0
scrapy                    1.7.3                    pypi_0    pypi
seaborn                   0.9.0                      py_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
service-identity          18.1.0                   pypi_0    pypi
setuptools                41.2.0                   py37_0    conda-forge
sip                       4.19.8          py37h6538335_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
snowballstemmer           1.9.1                      py_0    conda-forge
sphinx                    2.2.0                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.3                      py_0    conda-forge
spyder                    4.0.0b5                  py37_0    spyder-ide
spyder-kernels            1.5.0                    py37_0    spyder-ide
sqlite                    3.29.0               hfa6e2cd_1    conda-forge
statsmodels               0.10.1           py37hfa6e2cd_0    conda-forge
tbb                       2019.8               he980bc4_0    conda-forge
terminado                 0.8.2                    py37_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
tornado                   6.0.3            py37hfa6e2cd_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
twisted                   19.7.0                   pypi_0    pypi
urllib3                   1.25.3                   py37_0    conda-forge
vc                        14.1                 h0510ff6_4
virtualenv                16.7.2                   pypi_0    pypi
virtualenv-clone          0.5.3                    pypi_0    pypi
vs2015_runtime            14.16.27012          hf0eaf9b_0
w3lib                     1.21.0                   pypi_0    pypi
watchdog                  0.9.0                    py37_1    spyder-ide
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
widgetsnbextension        3.4.2                 py37_1000    conda-forge
win_inet_pton             1.1.0                    py37_0    conda-forge
wincertstore              0.2                   py37_1002    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.11.2           py37hfa6e2cd_0    conda-forge
yaml                      0.1.7             hfa6e2cd_1001    conda-forge
yapf                      0.28.0                     py_0    conda-forge
zeromq                    4.3.2                h6538335_2    conda-forge
zipp                      0.6.0                      py_0    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge
zope-interface            4.6.0                    pypi_0    pypi


I've tried updating qt and pyqt separately  but still get this issue.  I am doing all of this in a virtual environment named quantecon.

**Comment by ccordoba12** [comment]
> nstalling Spyder 4.0.0b5 gives error about DEBUG menuinst_win32:__init__(199)

This is not an error, it's only a debug message, so you can safely ignore it.

The real problem is that you broke your Anaconda installation by using pip to install PyQt5 (as you mentioned on issue #8952), so now you have to reinstall it.

**Comment by namanchauhan8998** [comment]
mine i stuck at it
