### ISSUE TITLE
Crash on RHEL7 with spyder4 beta5

### ISSUE THREAD

**Issue by moiz1235** [spyder-ide/spyder#10244]
### What steps will reproduce the problem?

I updated to spyder beta 5 version. 
On opening existing project directory from "Projects", the IDE crashes

I had to revert back to beta2 version now. 

### Traceback
```python-traceback
  File "/data/mdclflows/python/Anaconda3-2019.07/envs/spyder-beta/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 744, in <lambda>
    lambda c=client: self.process_started(c))
  File "/data/mdclflows/python/Anaconda3-2019.07/envs/spyder-beta/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 1380, in process_started
    self.main.variableexplorer.add_shellwidget(client.shellwidget)
  File "/data/mdclflows/python/Anaconda3-2019.07/envs/spyder-beta/lib/python3.7/site-packages/spyder/plugins/variableexplorer/plugin.py", line 137, in add_shellwidget
    nsb.setup(**self.get_settings())
  File "/data/mdclflows/python/Anaconda3-2019.07/envs/spyder-beta/lib/python3.7/site-packages/spyder/plugins/variableexplorer/plugin.py", line 71, in get_settings
    settings[name] = self.get_option(name)
  File "/data/mdclflows/python/Anaconda3-2019.07/envs/spyder-beta/lib/python3.7/site-packages/spyder/api/plugins.py", line 172, in get_option
    return CONF.get(self.CONF_SECTION, option, default)
  File "/data/mdclflows/python/Anaconda3-2019.07/envs/spyder-beta/lib/python3.7/site-packages/spyder/config/user.py", line 382, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'show_callable_attributes' in section: 'variable_explorer'
Traceback (most recent call last):
  File "/data/mdclflows/python/Anaconda3-2019.07/envs/spyder-beta/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/data/mdclflows/python/Anaconda3-2019.07/envs/spyder-beta/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/widgets/namespacebrowser.py", line 224, in _handle_execute_reply
    self.set_namespace_view_settings()
  File "/data/mdclflows/python/Anaconda3-2019.07/envs/spyder-beta/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/widgets/namespacebrowser.py", line 77, in set_namespace_view_settings
    self.namespacebrowser.get_view_settings())
  File "/data/mdclflows/python/Anaconda3-2019.07/envs/spyder-beta/lib/python3.7/site-packages/spyder/plugins/variableexplorer/widgets/namespacebrowser.py", line 244, in get_view_settings
    settings[name] = getattr(self, name)
AttributeError: 'NamespaceBrowser' object has no attribute 'show_callable_attributes'
```

## Versions

* Spyder version: 4.0.0b2 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 3.10.0-693.el7.x86_64

### Dependencies

```
pygments >=2.0     :  2.4.2 (OK)
qdarkstyle >=2.6.4 :  2.7 (OK)
sphinx >=0.6.6     :  2.1.2 (OK)
psutil >=0.3       :  5.6.3 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.5.0 (OK)
pandas >=0.13.1    :  None (NOK)
numpy >=1.7        :  None (NOK)
sympy >=0.7.3      :  None (NOK)
cython >=0.21      :  None (NOK)
qtconsole >=4.2.0  :  4.5.5 (OK)
IPython >=4.0      :  7.8.0 (OK)
matplotlib >=2.0.0 :  None (NOK)
pylint >=0.25      :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
Please update to beta4 to fix this (beta5 has some problems we're trying to fix right now).

**Comment by ccordoba12** [comment]
I said that because beta2 is your reported version above.
