### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by Tyler989** [spyder-ide/spyder#10286]
## Problem Description
When starting spyder from my virtual environment from windows cmd I get the following error. 

An error ocurred while starting the kernel
The error is:

Traceback (most recent call last):
File "c:\users\45054310\env\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "c:\users\45054310\env\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "c:\users\45054310\env\lib\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "c:\users\45054310\env\lib\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "c:\programdata\anaconda3\Lib\contextlib.py", line 82, in __enter__
return next(self.gen)
File "c:\users\45054310\env\lib\site‑packages\jupyter_client\connect.py", line 100, in secure_write
win32_restrict_file_to_user(fname)
File "c:\users\45054310\env\lib\site‑packages\jupyter_client\connect.py", line 53, in win32_restrict_file_to_user
import win32api
ImportError: DLL load failed: The specified procedure could not be found.

### What steps reproduce the problem?

1. Install Spyder to virtual env
2. Launch spyder from cmd via spyder3.exe

* Spyder version: 3.3.6
* Python version: 3.6.1
* Qt version: unsure
* PyQt version: unsure
* Operating System name/version: 
   Windows 7

**Comment by ccordoba12** [comment]
Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.
