### ISSUE TITLE
An error ocurred while starting the kernel when launching spyder

### ISSUE THREAD

**Issue by xbshen1** [spyder-ide/spyder#10316]
Hi all,
After installing anaconda, when I launched spyder console I met a problem. It looks like the follow descriptions.

"An error ocurred while starting the kernel
The error is:

Traceback (most recent call last):
File "E:\Anaconda\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\xbshen\AppData\Roaming\Python\Python37\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\Users\xbshen\AppData\Roaming\Python\Python37\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "C:\Users\xbshen\AppData\Roaming\Python\Python37\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "E:\Anaconda\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "C:\Users\xbshen\AppData\Roaming\Python\Python37\site‑packages\jupyter_client\connect.py", line 100, in secure_write
win32_restrict_file_to_user(fname)
File "C:\Users\xbshen\AppData\Roaming\Python\Python37\site‑packages\jupyter_client\connect.py", line 53, in win32_restrict_file_to_user
import win32api
ImportError: DLL load failed:

Can anyone provide help? Thanks

**Comment by ccordoba12** [comment]
Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

**Comment by ccordoba12** [comment]
Sorry, forget the comment above. You need to remove this directory:

    C:\Users\xbshen\AppData\Roaming\Python\Python37\site‑packages

to fix this error.
