### ISSUE TITLE
spyyyder

### ISSUE THREAD

**Issue by khanroha** [spyder-ide/spyder#10317]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by khanroha** [comment]
Traceback (most recent call last):
  File "C:\Users\ABC\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3208, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\ABC\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3084, in run_spyder
    main.setup()
  File "C:\Users\ABC\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 817, in setup
    message=_("Spyder Internal Console\n\n"
  File "C:\Users\ABC\Anaconda3\lib\site-packages\spyder\plugins\console.py", line 67, in __init__
    light_background=light_background)
  File "C:\Users\ABC\Anaconda3\lib\site-packages\spyder\widgets\internalshell.py", line 141, in __init__
    profile)
  File "C:\Users\ABC\Anaconda3\lib\site-packages\spyder\widgets\shell.py", line 636, in __init__
    initial_message)
  File "C:\Users\ABC\Anaconda3\lib\site-packages\spyder\widgets\shell.py", line 70, in __init__
    self.history = self.load_history()
  File "C:\Users\ABC\Anaconda3\lib\site-packages\spyder\widgets\shell.py", line 500, in load_history
    if rawhistory[1] != self.INITHISTORY[1]:
IndexError: list index out of range

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.6
