### ISSUE TITLE
Tab key produces error on empty line

### ISSUE THREAD

**Issue by Keou0007** [spyder-ide/spyder#10328]
### What steps will reproduce the problem?

- Select all contents of a line in the editor and push backspace to delete
- Push tab (to indent)

Issue reporter appears with traceback suggesting an error because the empty line can't be autocompleted.

Closing the issue reporter and pushing tab again reliably reproduces the traceback. Seems to occur now by pushing tab on any empty line.

### Traceback
```python-traceback
  File "/home/keoughs/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/extensions/snippets.py", line 183, in _on_key_pressed
    len(self.snippets_map))
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/home/keoughs/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/extensions/snippets.py", line 183, in _on_key_pressed
    len(self.snippets_map))
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/home/keoughs/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/extensions/snippets.py", line 183, in _on_key_pressed
    len(self.snippets_map))
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/home/keoughs/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/extensions/snippets.py", line 183, in _on_key_pressed
    len(self.snippets_map))
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/home/keoughs/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/extensions/snippets.py", line 183, in _on_key_pressed
    len(self.snippets_map))
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/home/keoughs/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/extensions/snippets.py", line 183, in _on_key_pressed
    len(self.snippets_map))
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/home/keoughs/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/extensions/snippets.py", line 183, in _on_key_pressed
    len(self.snippets_map))
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/home/keoughs/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/extensions/snippets.py", line 183, in _on_key_pressed
    len(self.snippets_map))
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/home/keoughs/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/extensions/snippets.py", line 183, in _on_key_pressed
    len(self.snippets_map))
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/home/keoughs/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/extensions/snippets.py", line 183, in _on_key_pressed
    len(self.snippets_map))
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/home/keoughs/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/extensions/snippets.py", line 183, in _on_key_pressed
    len(self.snippets_map))
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/home/keoughs/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/extensions/snippets.py", line 183, in _on_key_pressed
    len(self.snippets_map))
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/home/keoughs/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/extensions/snippets.py", line 183, in _on_key_pressed
    len(self.snippets_map))
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/home/keoughs/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/extensions/snippets.py", line 183, in _on_key_pressed
    len(self.snippets_map))
ZeroDivisionError: integer division or modulo by zero
```

## Versions

* Spyder version: 4.0.0b5 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 2.6.32-754.17.1.el6.x86_64

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
sphinx >=0.6.6               :  2.2.0 (OK)
pylint >=0.25                :  2.3.1 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.5.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.13 (OK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
numpy >=1.7                  :  1.16.5 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.28.2;<0.29.0        :  0.28.3 (OK)
xdg >=0.26                   :  0.26 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by Keou0007** [comment]
Restarting spyder has fixed it, for now.

**Comment by ccordoba12** [comment]
These errors should have been fixed in master. Please report back if that's not the case after we release our next beta, which we're planning to do in three or four more days.
