### ISSUE TITLE
Spyder crash on go

### ISSUE THREAD

**Issue by npmehendale** [spyder-ide/spyder#10362]
### What steps will reproduce the problem?

I tried to upgrade PyQt 5.9 to 5.12 using conda.It took veryy long to restore. Even quick start icon is also lost from menu.

### Traceback
```python-traceback
  File "c:\programdata\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\npmeh\AppData\Roaming\Python\Python36\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 252, in _handle_status
    self.set_namespace_view_settings()
  File "C:\Users\npmeh\AppData\Roaming\Python\Python36\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 73, in set_namespace_view_settings
    settings = to_text_string(self.namespacebrowser.get_view_settings())
  File "C:\Users\npmeh\AppData\Roaming\Python\Python36\site-packages\spyder\widgets\variableexplorer\namespacebrowser.py", line 239, in get_view_settings
    settings[name] = getattr(self, name)
AttributeError: 'NamespaceBrowser' object has no attribute 'show_callable_attributes'
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\npmeh\AppData\Roaming\Python\Python36\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 219, in _handle_execute_reply
    self.set_namespace_view_settings()
  File "C:\Users\npmeh\AppData\Roaming\Python\Python36\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 73, in set_namespace_view_settings

```

## Versions

* Spyder version: 4.0.0b1 
* Python version: 3.6.5
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.11.0     :  0.14.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  None (NOK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by ccordoba12** [comment]
> I tried to upgrade PyQt 5.9 to 5.12 using conda.It took veryy long to restore

PyQt 5.12 is still not supported by Anaconda. If you used pip to do this or conda-forge to do this, you most probably broke your Anaconda installation and you have to reinstall it.

> Spyder version: 4.0.0b1

Our latest beta is beta5. beta1 is more than a year old now.
