### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by gagan1304** [spyder-ide/spyder#10367]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by gagan1304** [comment]
I got the following error while starting Spyder. 

The error is:

Traceback (most recent call last):
File "C:\Users\gagan.arora.VERDIA\AppData\Local\Continuum\anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\gagan.arora.VERDIA\AppData\Roaming\Python\Python37\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\Users\gagan.arora.VERDIA\AppData\Roaming\Python\Python37\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "C:\Users\gagan.arora.VERDIA\AppData\Roaming\Python\Python37\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "C:\Users\gagan.arora.VERDIA\AppData\Local\Continuum\anaconda3\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "C:\Users\gagan.arora.VERDIA\AppData\Roaming\Python\Python37\site‑packages\jupyter_client\connect.py", line 100, in secure_write
win32_restrict_file_to_user(fname)
File "C:\Users\gagan.arora.VERDIA\AppData\Roaming\Python\Python37\site‑packages\jupyter_client\connect.py", line 53, in win32_restrict_file_to_user
import win32api
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by bcolsen** [comment]
Try: `pip install pywin32`

If that doesn't solve it, please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Spyder Anaconda.

Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out. This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

**Comment by gagan1304** [comment]
Hi,

FYI,

I have already installed anaconda and I am running spyder from anaconda.
Also, the solution does not work.

Regards

Gagan

**Comment by ccordoba12** [comment]
Please use Anaconda instead. The problem is fixed for sure with it.

**Comment by bcolsen** [comment]
@gagan1304 I see now that you have anaconda but you also have a manual python install in `C:\Users\gagan.arora.VERDIA\AppData\Roaming\Python\`. You need to remove this manual install from the python path or inistall it completely.

**Comment by yasiin09** [comment]
Must try

`conda install -c anaconda jupyter_core`
