### ISSUE TITLE
interal problem

### ISSUE THREAD

**Issue by amdestroyer** [spyder-ide/spyder#10395]
### What steps will reproduce the problem?

At start of the app- Spyder has encoun. int prblm.

### Traceback
```python-traceback
  File "/Users/ShivaRajBhandari/anaconda/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/Users/ShivaRajBhandari/anaconda/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 343, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/Users/ShivaRajBhandari/anaconda/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/Users/ShivaRajBhandari/anaconda/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/Users/ShivaRajBhandari/anaconda/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 129, in get_cwd
    self.silent_exec_method(code)
  File "/Users/ShivaRajBhandari/anaconda/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 343, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/Users/ShivaRajBhandari/anaconda/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/Users/ShivaRajBhandari/anaconda/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
```

## Versions

* Spyder version: 3.3.1 
* Python version: 2.7.15
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating System: Darwin 17.7.0

### Dependencies

```
pyflakes >=0.5.0  :  1.2.3 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.1.3 (OK)
sphinx >=0.6.6    :  1.4.1 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.9.0 (OK)
psutil >=0.3      :  4.3.0 (OK)
nbconvert >=4.0   :  4.2.0 (OK)
pandas >=0.13.1   :  0.23.0 (OK)
numpy >=1.7       :  1.16.3 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.24 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  4.2.0 (OK)
matplotlib >=2.0.0:  2.0.2 (OK)
pylint >=0.25     :  1.7.2 (OK)
```

**Comment by ccordoba12** [comment]
Please open Terminal.app and run

    conda update python python.app

If that doesn't fix the problem, I'm afraid you'll have to switch to Python 3 because this is a bug in Python itself and I think it was not backported to Python 2 (i.e. it was only fixed in Python 3), sorry.
