### ISSUE TITLE
UnicodeEncodeError for Kite engine

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#10430]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. Open spyder (python 2 env)
2. Open a file that has a `ñ` in the name
3. On startup spyder produces this error

### Paste Traceback/Error Below (if applicable)

```python-traceback
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 59: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/gpena-castellanos/Google Drive/develop/quansight/spyder/spyder/plugins/completion/kite/client.py", line 131, in perform_request
    response = handler(params)
  File "/Users/gpena-castellanos/Google Drive/develop/quansight/spyder/spyder/plugins/completion/kite/decorators.py", line 20, in wrapper
    params = req(self, *args, **kwargs)
  File "/Users/gpena-castellanos/Google Drive/develop/quansight/spyder/spyder/plugins/completion/kite/providers/document.py", line 79, in document_did_open
    self.get_status(params['file'])
  File "/Users/gpena-castellanos/Google Drive/develop/quansight/spyder/spyder/plugins/completion/kite/client.py", line 89, in get_status
    kite_status = self._get_status(filename)
  File "/Users/gpena-castellanos/Google Drive/develop/quansight/spyder/spyder/plugins/completion/kite/client.py", line 81, in _get_status
    url = url.format(filename=filename)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 59: ordinal not in range(128)

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
@dalthviz, this one is for you.
