### ISSUE TITLE
KeyedVectors.load_word2vec_format loading issue

### ISSUE THREAD

**Issue by junluodigitcompass** [spyder-ide/spyder#10475]
### What steps will reproduce the problem?

from gensim.models import KeyedVectors
filename = 'E:\CodingData\GoogleNews-vectors-negative300.bin.gz'
model = KeyedVectors.load_word2vec_format(filename, binary=True, encoding="ISO-8859-1")

model = KeyedVectors.load_word2vec_format(filename, binary=True, encoding="ISO-8859-1")
Traceback (most recent call last):

  File "<ipython-input-21-57f63b5e928c>", line 1, in <module>
    model = KeyedVectors.load_word2vec_format(filename, binary=True, encoding="ISO-8859-1")

  File "C:\Users\junluo\Anaconda3\envs\env35\lib\site-packages\gensim\models\keyedvectors.py", line 1436, in load_word2vec_format
    limit=limit, datatype=datatype)

  File "C:\Users\junluo\Anaconda3\envs\env35\lib\site-packages\gensim\models\utils_any2vec.py", line 171, in _load_word2vec_format
    with utils.smart_open(fname) as fin:

  File "C:\Users\junluo\Anaconda3\envs\env35\lib\site-packages\smart_open\smart_open_lib.py", line 176, in smart_open
    ----------

  File "C:\Users\junluo\Anaconda3\envs\env35\lib\site-packages\smart_open\smart_open_lib.py", line 671, in file_smart_open

  File "C:\Users\junluo\Anaconda3\envs\env35\lib\site-packages\smart_open\smart_open_lib.py", line 301, in open
    fobj = _shortcut_open(

NameError: name '_shortcut_open' is not defined

## Versions

* Spyder version: 3.3.1 
* Python version: 3.5.5
* Qt version: 5.13.1
* PyQt5 version: 5.13.1
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  None (OK)
numpy >=1.7       :  None (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.0.1 (OK)
matplotlib >=2.0.0:  None (OK)
pylint >=0.25     :  1.9.2 (OK)
```

**Comment by ccordoba12** [comment]
According to this part of your error

> File "C:\Users\junluo\Anaconda3\envs\env35\lib\site-packages\smart_open\smart_open_lib.py", line 301, in open
fobj = _shortcut_open(
>
> NameError: name '_shortcut_open' is not defined

This is not a problem in Spyder but in the `smart_open` library. Please report it there.
