### ISSUE TITLE
Spyder ipython console error

### ISSUE THREAD

**Issue by Martian94** [spyder-ide/spyder#10498]
Hai...
@ccordoba12  after updating the Anaconda and spyder the ipython console  is showing error ...
tried...
conda update jupyter_client jupyter_core 
conda update setuptools.. 
downgraded pyqt to==5.10.1
still nothing changed.. console is still throwing the error..
Any thoughts..??
Thankyou..!

Versions
   Spyder version: 3.3.6
    Python version: 3.7.4
   OS : Windows 10 

Error Msg.....

{An error ocurred while starting the kernel
The error is:

```python-traceback
Traceback (most recent call last):
File "C:\Users\Asgard\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\Asgard\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\Users\Asgard\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "C:\Users\Asgard\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "C:\Users\Asgard\Anaconda3\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "C:\Users\Asgard\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 102, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Asgard\\AppData\\Roaming\\jupyter\\runtime\\kernel󈛟c9d119f30b.json'}
```

**Comment by ccordoba12** [comment]
> downgraded pyqt to==5.10.1

You broke your Anaconda installation by doing that. Now you need to reinstall.

> conda update jupyter_client jupyter_core

That should fix the error above. Please reinstall Anaconda and try again.

**Comment by Martian94** [comment]
Hai..
Uninstalled... Restarted... Reinstalled...
Done the {conda update jupyter_client jupyter_core} (in anaconda prompt)...

Package Updated...

    package                    |            build
    ---------------------------|-----------------
    conda-build-3.18.10        |           py37_3         555 KB
    ------------------------------------------------------------
conda-build                                 3.18.9-py37_3 --> 3.18.10-py37_3

opened Navigator... launched spyder 3.3.6
nothing changed... still ipython console is in error.....
What next...
Thanks For the Support...

The error is:
Traceback (most recent call last):
File "C:\Users\Asgard\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\Asgard\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\Users\Asgard\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "C:\Users\Asgard\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "C:\Users\Asgard\Anaconda3\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "C:\Users\Asgard\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 102, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Asgard\\AppData\\Roaming\\jupyter\\runtime\\kernel�e319e.json'

**Comment by ccordoba12** [comment]
@Martian94, please follow the suggestion above:

> If you are sure you want an update of your package either try conda update --all or install a specific version of the package you want using conda install <pkg>=<version>

So, please run

    conda update --all

and try again.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
