### ISSUE TITLE
AttributeError: 'str' object has no attribute 'append'

### ISSUE THREAD

**Issue by yaping222** [spyder-ide/spyder#10519]
## Problem Description
Cannot launch spyder under anaconda.
The spyder worked well on my laptop before. However, one day I restarted my laptop, it doesn't work anymore and I got the following error message. So I uninstall and install spyder using conda. This cannot help. Then I uninstall and reinstall anaconda, still cannot solve the problem. Of course, I restarted my laptop several times but nothing changed.

### What steps reproduce the problem?

1. install the anaconda in win10
2. start 'anaconda prompt'
3. start 'spyder' in  'anaconda prompt'

### What is the expected output? What do you see instead?
I'm supposed to launch the software but cannot launch it and got an error message.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\start.py", line 186, in main
    from spyder.app import mainwindow
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 117, in <module>
    from spyder.utils.qthelpers import qapplication, MENU_SEPARATOR
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\qthelpers.py", line 26, in <module>
    from spyder.config.gui import get_shortcut
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\gui.py", line 168, in <module>
    set_default_color_scheme(_name, replace=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\gui.py", line 164, in set_default_color_scheme
    set_color_scheme(name, sh.get_color_scheme(name), replace=replace)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\gui.py", line 157, in set_color_scheme
    names.append(to_text_string(name))
AttributeError: 'str' object has no attribute 'append'

```

## Versions

* Spyder version: 3.3.6
* Python version: 3.7.4
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Please open the Anaconda Prompt, run there:

    spyder --reset

and try again. That should fix your problem.

**Comment by yaping222** [comment]
Hi Carlos,
Thank you very much for your reply. I tried the command but still got the same error message.
(base) C:\Users\Yaping>spyder --reset
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\start.py", line 200, in main
    from spyder.app import mainwindow
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 117, in <module>
    from spyder.utils.qthelpers import qapplication, MENU_SEPARATOR
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\qthelpers.py", line 26, in <module>
    from spyder.config.gui import get_shortcut
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\gui.py", line 168, in <module>
    set_default_color_scheme(_name, replace=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\gui.py", line 164, in set_default_color_scheme
    set_color_scheme(name, sh.get_color_scheme(name), replace=replace)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\gui.py", line 157, in set_color_scheme
    names.append(to_text_string(name))
AttributeError: 'str' object has no attribute 'append'

Could you give more suggestions on how to solve this issue?

**Comment by ccordoba12** [comment]
Please then remove the `.spyder-py3` directory placed in `C:\Users\Yaping\`

**Comment by yaping222** [comment]
Hi Carlos,
Thank you very much. It works!
