### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by chaitanyareddy29** [spyder-ide/spyder#10517]
The error is:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 102, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\chaitanya\\AppData\\Roaming\\jupyter\\runtime\\kernel�f3a4adc7a.json'

**Comment by goanpeca** [comment]
Please update `jupyter_core` and also `jupyter_client`. The right versions that solve this problem are

`jupyter_core 4.6.0`
`jupyter_client 5.3.4`
