### ISSUE TITLE
Preferences > Keyboard shortcuts

### ISSUE THREAD

**Issue by SvenMeyer** [spyder-ide/spyder#10511]
### What steps will reproduce the problem?

Preferences > some other menu item
Preferences > Keyboard shortcuts

### Traceback
```python-traceback
  File "/usr/lib/python3.7/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.4
* Qt version: 5.13.1
* PyQt5 version: 5.13.1
* Operating System: Linux 4.19.79-1-MANJARO

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
psutil >=0.3      :  5.6.3 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.17.2 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.5.1 (OK)
IPython >=4.0     :  7.6.1 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
This is fixed already in master and it'll be part of Spyder 4 (to be released in a month or so).
