### ISSUE TITLE
call class function without agrument

### ISSUE THREAD

**Issue by llobetv** [spyder-ide/spyder#10530]
### What steps will reproduce the problem?

call a class function that don't take any argument. Spyder must try to give description of these inexistant parameters

### Traceback
```python-traceback
  File "/users/nsr/llobet/miniconda2/envs/spyder-beta/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1134, in process_signatures
    parameter_data = parameters[parameter_idx]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/nsr/llobet/miniconda2/envs/spyder-beta/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/users/nsr/llobet/miniconda2/envs/spyder-beta/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/users/nsr/llobet/miniconda2/envs/spyder-beta/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/users/nsr/llobet/miniconda2/envs/spyder-beta/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "/users/nsr/llobet/miniconda2/envs/spyder-beta/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/users/nsr/llobet/miniconda2/envs/spyder-beta/lib/python3.7/site-packages/spyder/app/start.py", line 196, in main
    mainwindow.main()
  File "/users/nsr/llobet/miniconda2/envs/spyder-beta/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3646, in main
    mainwindow = run_spyder(app, options, args)
  File "/users/nsr/llobet/miniconda2/envs/spyder-beta/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3529, in run_spyder
    app.exec_()
  File "/users/nsr/llobet/miniconda2/envs/spyder-beta/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 138, in receive_response
    self.gather_and_send(request_responses)
  File "/users/nsr/llobet/miniconda2/envs/spyder-beta/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 189, in gather_and_send
    response_instance.handle_response(req_type, responses)
  File "/users/nsr/llobet/miniconda2/envs/spyder-beta/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 915, in handle_response
    handler(params)
  File "/users/nsr/llobet/miniconda2/envs/spyder-beta/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1151, in process_signatures
    self.log_lsp_handle_errors("Error when processing signature")
  File "/users/nsr/llobet/miniconda2/envs/spyder-beta/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 946, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 4.0.0b7 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.4.0-166-generic

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.1 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.5.0 (OK)
sphinx >=0.6.6               :  2.1.2 (OK)
pylint >=0.25                :  2.3.1 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.5.7 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.6.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  0.29.13 (OK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
numpy >=1.7                  :  1.16.4 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.28.2;<0.29.0        :  0.28.2 (OK)
xdg >=0.26                   :  0.26 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. This is already fixed and it'll be part of our next version.
