### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by reza92farahani** [spyder-ide/spyder#10543]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
```python-traceback
  File "/usr/lib/python2.7/dist-packages/spyder/plugins/ipythonconsole.py", line 1033, in create_new_client
    self.connect_client_to_kernel(client)
  File "/usr/lib/python2.7/dist-packages/spyder/plugins/ipythonconsole.py", line 1059, in connect_client_to_kernel
    stderr_file)
  File "/usr/lib/python2.7/dist-packages/spyder/plugins/ipythonconsole.py", line 1485, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/connect.py", line 476, in write_connection_file
    kernel_name=self.kernel_name
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/connect.py", line 141, in write_connection_file
    with secure_write(fname) as f:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/paths.py", line 426, in secure_write
    with os.fdopen(os.open(fname, open_flag, 0o0600), mode) as f:
OSError: [Errno 13] Permission denied: '/home/reza/.local/share/jupyter/runtime/kernel-7f9cf6693a80.json'
```

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 2.7.15+
* Qt Versions: 5.9.5, PyQt5 5.10.1 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.13.3 (OK)
sphinx >=0.6.6    :  1.6.7 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
psutil >=0.3      :  5.4.2 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0;<6.0:  5.8.0 (OK)
pylint >=0.25     :  1.8.3 (OK)

```

**Comment by ccordoba12** [comment]
Are you using Windows for Linux?

**Comment by Bushii7** [comment]
i have spyder 3.3.6 error is occurring while starting the kernel plz guide 


Traceback (most recent call last):
File "C:\Users\Bushra\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\Bushra\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\Users\Bushra\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "C:\Users\Bushra\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "C:\Users\Bushra\Anaconda3\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "C:\Users\Bushra\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 102, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Bushra\\AppData\\Roaming\\jupyter\\runtime\\kernel󈛀a682ddf958.json'

**Comment by ccordoba12** [comment]
@Bushii7, please open an Anaconda Prompt and run there

    conda update --all

to fix this.
