### ISSUE TITLE
Launch error after update with master repository

### ISSUE THREAD

**Issue by gepcel** [spyder-ide/spyder#10564]
### What steps will reproduce the problem?

I pulled from the master repository today, and then this error appears.

### Traceback
```python-traceback
  File "c:\python\project\spyder\spyder\plugins\base.py", line 318, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "c:\python\project\spyder\spyder\plugins\ipythonconsole\plugin.py", line 204, in toggle_view
    self.create_new_client(give_focus=False)
  File "c:\python\project\spyder\spyder\plugins\ipythonconsole\plugin.py", line 659, in create_new_client
    self.register_client(client)
  File "c:\python\project\spyder\spyder\plugins\ipythonconsole\plugin.py", line 839, in register_client
    client.configure_shellwidget(give_focus=give_focus)
  File "c:\python\project\spyder\spyder\plugins\ipythonconsole\widgets\client.py", line 273, in configure_shellwidget
    self.set_color_scheme(self.shellwidget.syntax_style, reset=False)
  File "c:\python\project\spyder\spyder\plugins\ipythonconsole\widgets\client.py", line 479, in set_color_scheme
    self.shellwidget.set_color_scheme(color_scheme, reset)
  File "c:\python\project\spyder\spyder\plugins\ipythonconsole\widgets\shell.py", line 188, in set_color_scheme
    blocking=False).set_sympy_forecolor(background_color='dark')
  File "C:\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 528, in __call__
    return self._comms_wrapper._get_call_return_value(call_dict)
TypeError: _get_call_return_value() missing 2 required positional arguments: 'call_data' and 'comm_id'
Traceback (most recent call last):

```

## Versions

* Spyder version: 4.0.0.dev0 7b9ad89eb
* Python version: 3.7.4
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.1 (OK)
pylint >=0.25                :  2.4.3 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.6.0.dev0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  0.29.13 (OK)
IPython >=4.0                :  7.9.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.2 (OK)
numpy >=1.7                  :  1.17.3 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.29.2;<0.30.0        :  0.29.3 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment]
You need to use master of spyder-kernels. Please don't make us waste our time.

**Comment by gepcel** [comment]
I pulled the spyder-kernels from the master multiple times, but forgot to install it. My bad.
I promise you guys, your times won't be wasted ever.

**Comment by ccordoba12** [comment]
Sorry if I was a bit harsh, but master is still moving too much. So if you want to be on it, you need to follow our activity quite frequently (which is a lot lately!).
