### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by sakinahrenu** [spyder-ide/spyder#10594]
Installed Anaconda and Spyder on the 02/11/2019

Running a simple print command and I'm getting this error message. I have looked through the FAQ and ran through the reset and commands for solution and nothing has changed.

Help appreciated as I'm new to Python.

Traceback (most recent call last):
File "C:\Users\Sakinah\Anaconda3\lib\site packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\Sakinah\Anaconda3\lib\site packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\Users\Sakinah\Anaconda3\lib\site packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "C:\Users\Sakinah\Anaconda3\lib\site packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "C:\Users\Sakinah\Anaconda3\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "C:\Users\Sakinah\Anaconda3\lib\site packages\jupyter_client\connect.py", line 102, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Sakinah\\AppData\\Roaming\\jupyter\\runtime\\kernel𔂱afcbbe1e139.json'

Thanks.

**Comment by ccordoba12** [comment]
Please open an Anaconda Prompt and run there

    conda update --all

to fix this.
