### ISSUE TITLE
[Windows] Systematic crash on launch 

### ISSUE THREAD

**Issue by sylvain-bougnoux** [spyder-ide/spyder#10595]
With the last master and since a few days, I cannot run spyder anymore. Actually I had problem & reluctance installing Kite. I tried in .ini Kite::enable=False, but same crash. Sorry I don't have the package dependency due to the crash. Thanks

[Python 3.6, Windows 10]

Executing Spyder from source checkout
Revision f92cd3fe4, Branch: master
01. Patched sys.path with C:\Contrib\spyder
02. PyQt5 is detected, selecting
03. Imported Spyder 4.0.0.dev0
    [Python 3.6.5 64bits, Qt 5.13.1, PyQt5 5.13.1 on Windows]
04. Running Spyder
Bootstrap completed in 00:00:08.7176
Attribute Qt::AA_UseSoftwareOpenGL must be set before QCoreApplication is created.
Traceback (most recent call last):
  File "C:\Contrib\spyder\spyder\app\mainwindow.py", line 3657, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Contrib\spyder\spyder\app\mainwindow.py", line 3498, in run_spyder
    main.setup()
  File "C:\Contrib\spyder\spyder\app\mainwindow.py", line 1290, in setup
    self.setup_layout(default=False)
  File "C:\Contrib\spyder\spyder\app\mainwindow.py", line 1617, in setup_layout
    self.setup_default_layouts('default', settings)
  File "C:\Contrib\spyder\spyder\app\mainwindow.py", line 1839, in setup_default_layouts
    widget.toggle_view(True)
  File "C:\Contrib\spyder\spyder\plugins\ipythonconsole\plugin.py", line 204, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Contrib\spyder\spyder\plugins\ipythonconsole\plugin.py", line 659, in create_new_client
    self.register_client(client)
  File "C:\Contrib\spyder\spyder\plugins\ipythonconsole\plugin.py", line 839, in register_client
    client.configure_shellwidget(give_focus=give_focus)
  File "C:\Contrib\spyder\spyder\plugins\ipythonconsole\widgets\client.py", line 273, in configure_shellwidget
    self.set_color_scheme(self.shellwidget.syntax_style, reset=False)
  File "C:\Contrib\spyder\spyder\plugins\ipythonconsole\widgets\client.py", line 479, in set_color_scheme
    self.shellwidget.set_color_scheme(color_scheme, reset)
  File "C:\Contrib\spyder\spyder\plugins\ipythonconsole\widgets\shell.py", line 188, in set_color_scheme
    blocking=False).set_sympy_forecolor(background_color='dark')
  File "C:\Program Files\Python36\lib\site-packages\spyder_kernels\comms\commbase.py", line 528, in __call__
    return self._comms_wrapper._get_call_return_value(call_dict)
TypeError: _get_call_return_value() missing 2 required positional arguments: 'call_data' and 'comm_id'

**Comment by goanpeca** [comment]
@sylvain-bougnoux  you need to install the latest master on spyder-kernels (See: https://github.com/spyder-ide/spyder-kernels/) and you also need the latest version of ipykernel

**Comment by ccordoba12** [comment]
Yep, that should do the trick @sylvain-bougnoux.

**Comment by sylvain-bougnoux** [comment]
Yes thanks for having updated spyder-kernels
