### ISSUE TITLE
Spyder3 do not launch !

### ISSUE THREAD

**Issue by pgr123** [spyder-ide/spyder#10592]
When I launch Spyder3, when it prepare the principal window, it stop with the message :+1: 

pascal@EL1352:~$ spyder3
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spyder/app/mainwindow.py", line 3126, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python3/dist-packages/spyder/app/mainwindow.py", line 3023, in run_spyder
    main.setup()
  File "/usr/lib/python3/dist-packages/spyder/app/mainwindow.py", line 1182, in setup
    self.setup_layout(default=False)
  File "/usr/lib/python3/dist-packages/spyder/app/mainwindow.py", line 1452, in setup_layout
    self.setup_default_layouts('default', settings)
  File "/usr/lib/python3/dist-packages/spyder/app/mainwindow.py", line 1628, in setup_default_layouts
    widget.toggle_view(True)
  File "/usr/lib/python3/dist-packages/spyder/plugins/ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "/usr/lib/python3/dist-packages/spyder/plugins/ipythonconsole.py", line 1033, in create_new_client
    self.connect_client_to_kernel(client)
  File "/usr/lib/python3/dist-packages/spyder/plugins/ipythonconsole.py", line 1059, in connect_client_to_kernel
    stderr_file)
  File "/usr/lib/python3/dist-packages/spyder/plugins/ipythonconsole.py", line 1485, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "/home/pascal/.local/lib/python3.6/site-packages/jupyter_client/manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "/home/pascal/.local/lib/python3.6/site-packages/jupyter_client/connect.py", line 476, in write_connection_file
    kernel_name=self.kernel_name
  File "/home/pascal/.local/lib/python3.6/site-packages/jupyter_client/connect.py", line 141, in write_connection_file
    with secure_write(fname) as f:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/pascal/.local/lib/python3.6/site-packages/jupyter_core/paths.py", line 426, in secure_write
    with os.fdopen(os.open(fname, open_flag, 0o0600), mode) as f:
PermissionError: [Errno 13] Permission non accordée: '/home/pascal/.local/share/jupyter/runtime/kernel-8ba924b5a841.json'

Where is the problem ?
Thank you.

**Comment by pgr123** [comment]
Excuse me. I solved the problem by changing the permissions on .local/share/jupyter/runtime.
I do not know why that happened ! I installed spyder3 with synaptic. It's the version 3.2.6. Maybe that is the problem but how can I update Spyder3 ?
