### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by sakinahrenu** [spyder-ide/spyder#10619]
Tried conda update --all

No change.

Traceback (most recent call last):
File "C:\Users\Sakinah\Anaconda3\lib\site packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\Sakinah\Anaconda3\lib\site packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\Users\Sakinah\Anaconda3\lib\site packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "C:\Users\Sakinah\Anaconda3\lib\site packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "C:\Users\Sakinah\Anaconda3\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "C:\Users\Sakinah\Anaconda3\lib\site packages\jupyter_client\connect.py", line 102, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Sakinah\\AppData\\Roaming\\jupyter\\runtime\\kernel�b35450c42.json'

**Comment by sakinahrenu** [comment]
Had to uninstall and re-install as I had Python 2.7 and not the latest 3.7.

**Comment by sakinahrenu** [comment]
Still the issue on Spyder

**Comment by ccordoba12** [comment]
> Tried conda update --all
>
> No change.

Sorry but that's the only suggestion we have for you. This is not really an error in Spyder but in `jupyter_client`, so please report it there:

https://github.com/jupyter/jupyter_client
