### ISSUE TITLE
spyder error

### ISSUE THREAD

**Issue by DaiRongJiang** [spyder-ide/spyder#10613]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\2506\Anaconda3\envs\tensorflow-gpu\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'session'

Traceback (most recent call last):
  File "C:\Users\2506\Anaconda3\envs\tensorflow-gpu\lib\site-packages\jupyter_client\session.py", line 522, in _check_packers
    packed = pack(msg)
  File "C:\Users\2506\Anaconda3\envs\tensorflow-gpu\lib\site-packages\jupyter_client\session.py", line 103, in <lambda>
    ensure_ascii=False, allow_nan=False,
  File "C:\Users\2506\Anaconda3\envs\tensorflow-gpu\lib\site-packages\zmq\utils\jsonapi.py", line 43, in dumps
    s = s.decode('utf8').encode('cp950', error = 'ignore')
AttributeError: 'str' object has no attribute 'decode'

Traceback (most recent call last):
  File "C:\Users\2506\Anaconda3\envs\tensorflow-gpu\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\Users\2506\Anaconda3\envs\tensorflow-gpu\lib\site-packages\spyder\plugins\ipythonconsole.py", line 709, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\2506\Anaconda3\envs\tensorflow-gpu\lib\site-packages\spyder\plugins\ipythonconsole.py", line 991, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\Users\2506\Anaconda3\envs\tensorflow-gpu\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1018, in connect_client_to_kernel
    stderr_file)
  File "C:\Users\2506\Anaconda3\envs\tensorflow-gpu\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1420, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "C:\Users\2506\Anaconda3\envs\tensorflow-gpu\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "C:\Users\2506\Anaconda3\envs\tensorflow-gpu\lib\site-packages\jupyter_client\connect.py", line 467, in write_connection_file
    transport=self.transport, ip=self.ip, key=self.session.key,
  File "C:\Users\2506\Anaconda3\envs\tensorflow-gpu\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "C:\Users\2506\Anaconda3\envs\tensorflow-gpu\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "C:\Users\2506\Anaconda3\envs\tensorflow-gpu\lib\site-packages\jupyter_client\connect.py", line 354, in _session_default
    return Session(parent=self)
  File "C:\Users\2506\Anaconda3\envs\tensorflow-gpu\lib\site-packages\jupyter_client\session.py", line 482, in __init__
    self._check_packers()
  File "C:\Users\2506\Anaconda3\envs\tensorflow-gpu\lib\site-packages\jupyter_client\session.py", line 530, in _check_packers
    msg.format(packer=self.packer, e=e, jsonmsg=jsonmsg)
ValueError: zmq.utils.jsonapi.jsonmod = <module 'json' from 'C:\\Users\\2506\\Anaconda3\\envs\\tensorflow-gpu\\lib\\json\\__init__.py'>

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.5.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.15.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
You're using a very old version of Spyder. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.6

And then please try again.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
