### ISSUE TITLE
An error ocurred while starting a kernel

### ISSUE THREAD

**Issue by yunlanli** [spyder-ide/spyder#10652]
An error ocurred while starting a kernel

The error is:

Traceback (most recent call last):
File "E:\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "E:\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "E:\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "E:\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "E:\Anaconda3\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "E:\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 102, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Sanad\\AppData\\Roaming\\jupyter\\runtime\\kernel𔂫a138628d817.json'

_Originally posted by @SanadKhan in https://github.com/spyder-ide/spyder/issues/2812#issuecomment-544276035_

**Comment by yunlanli** [comment]
I encountered the same issue. I executed the following commands as suggested in the comments: update jupyter_client and conda update --all.
The update was successful, and the following are the versions after update:
# Name                    Version                   Build  Channel
jupyter                   1.0.0                    py37_7
jupyter_client            5.3.4                    py37_0
jupyter_console           6.0.0                    py37_0
jupyter_core              4.6.1                    py37_0
jupyterlab                1.1.4              pyhf63ae98_0
jupyterlab_server         1.0.6                      py_0

However, when starting Spyder again. The same error message still appears.

I have also tried all the methods except installing Spyder in a new conda environment under the basic first aid section in troubleshooting guide and FAQ, but none of it worked for me.

I would really appreciate some insights on how to solve this issue.Below is the complete IPython console error message in Spyder:
The error is:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\Home\AppData\Roaming\Python\Python37\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\Users\Home\AppData\Roaming\Python\Python37\site‑packages\jupyter_client\connect.py", line 476, in write_connection_file
kernel_name=self.kernel_name
File "C:\Users\Home\AppData\Roaming\Python\Python37\site‑packages\jupyter_client\connect.py", line 141, in write_connection_file
with secure_write(fname) as f:
File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "C:\Users\Home\AppData\Roaming\Python\Python37\site‑packages\jupyter_core\paths.py", line 424, in secure_write
win32_restrict_file_to_user(fname)
File "C:\Users\Home\AppData\Roaming\Python\Python37\site‑packages\jupyter_core\paths.py", line 359, in win32_restrict_file_to_user
import win32api
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by ccordoba12** [comment]
> File "C:\Users\Home\AppData\Roaming\Python\Python37\site‑packages\jupyter_client\manager.py", line 240, in start_kernel

This line means that you did the update with pip and not with conda, or that you have previously used pip to install other packages. Please remove this directory by hand

    C:\Users\Home\AppData\Roaming\Python\Python37

and try again.

**Comment by yunlanli** [comment]
> > File "C:\Users\Home\AppData\Roaming\Python\Python37\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
> 
> This line means that you did the update with pip and not with conda, or that you have previously used pip to install other packages. Please remove this directory by hand
> 
> ```
> C:\Users\Home\AppData\Roaming\Python\Python37
> ```
> 
> and try again.

It worked, thank you so much! it seems that I have previously used pip to install other packages.

**Comment by ccordoba12** [comment]
Great!
