### ISSUE TITLE
Help getting this to start

### ISSUE THREAD

**Issue by mayfie27** [spyder-ide/spyder#10676]
This comes up when I try to launch with the anaconda prompt
(base) C:\Users\carte>spyder
Traceback (most recent call last):
  File "C:\Users\carte\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3285, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\carte\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3140, in run_spyder
    main.setup()
  File "C:\Users\carte\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 824, in setup
    self.workingdirectory = WorkingDirectory(self, self.init_workdir, main=self)
  File "C:\Users\carte\Anaconda3\lib\site-packages\spyder\plugins\workingdirectory.py", line 149, in __init__
    wdhistory = self.load_wdhistory(workdir)
  File "C:\Users\carte\Anaconda3\lib\site-packages\spyder\plugins\workingdirectory.py", line 221, in load_wdhistory
    wdhistory = [name for name in wdhistory if os.path.isdir(name)]
  File "C:\Users\carte\Anaconda3\lib\site-packages\spyder\plugins\workingdirectory.py", line 221, in <listcomp>
    wdhistory = [name for name in wdhistory if os.path.isdir(name)]
ValueError: _isdir: embedded null character in path

(base) C:\Users\carte>

then this is what happens when I try to start spyder 
![Code Question](https://user-images.githubusercontent.com/57647001/68632039-30106e00-04bb-11ea-9be5-c34feb68e8e7.JPG)

I tried reinstalling a few times, help is apricated because I have to finish a project due at midnight.

**Comment by ccordoba12** [comment]
Please open the Anaconda Prompt, run there

    spyder --reset

and try again. That should fix the problem.

**Comment by mayfie27** [comment]
opps I added the wrong picture, my bad... but it fixed it, thanks a lot!
