### ISSUE TITLE
"physical-quantities" crash in variable explorer

### ISSUE THREAD

**Issue by moux233** [spyder-ide/spyder#10716]
### What steps will reproduce the problem?

1/ create 2d array from "physical quantities" package
2/ double-click on variable name in Spyder variable explorer

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\type_check.py", line 161, in real
    return val.real
  File "G:\07.Git\python_quantities\quantities\quantity.py", line 176, in real
    return Quantity(self.magnitude.real, self.dimensionality, self.meta)
AttributeError: 'Quantity' object has no attribute 'meta'

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 482, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 673, in setup_and_check
    xlabels, ylabels))
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 540, in __init__
    ylabels=ylabels, readonly=readonly, parent=self)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 154, in __init__
    self.vmin = np.nanmin(self.color_func(data))
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\type_check.py", line 163, in real
    return asanyarray(val).real
  File "G:\07.Git\python_quantities\quantities\quantity.py", line 176, in real
    return Quantity(self.magnitude.real, self.dimensionality, self.meta)
AttributeError: 'Quantity' object has no attribute 'meta'
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.5 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by moux233** [comment]
Same as issue #10366

**Comment by ccordoba12** [comment]
Ok, I'm closing this one in favor of #10366. Please don't report this problem anymore.
