### ISSUE TITLE
Problem importing keras on Spyder 3.2.3(python 3.5)

### ISSUE THREAD

**Issue by johnsonbunny23** [spyder-ide/spyder#10717]
## Problem Description

I'm getting an error while importing keras on spyder in ANN program. I've posted the error in the Q&A session but there is no update, please help. 

### What steps reproduce the problem?

1.  When I type "import keras" in spyder it is giving me the error below. I'm not sure what is the issue. I've installed Keras and tensorflow with the following codes

conda install -c conda-forge keras
conda install -c conda-forge/label/broken keras
conda install -c conda-forge/label/cf201901 keras

Following codes for tensorflow:

conda install -c anaconda tensorflow-gpu

Please assist as to how this can be solved, I'm stuck here. 

### What is the expected output? What do you see instead?

 import keras
Using TensorFlow backend.
Traceback (most recent call last):

  File "<ipython-input-8-c74e2bd4ca71>", line 1, in <module>
    import keras

  File "C:\Users\Bunny\Anaconda3\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils

  File "C:\Users\Bunny\Anaconda3\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils

  File "C:\Users\Bunny\Anaconda3\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K

  File "C:\Users\Bunny\Anaconda3\lib\site-packages\keras\backend\__init__.py", line 89, in <module>
    from .tensorflow_backend import *

  File "C:\Users\Bunny\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf

  File "C:\Users\Bunny\AppData\Roaming\Python\Python35\site-packages\tensorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *

  File "C:\Users\Bunny\AppData\Roaming\Python\Python35\site-packages\tensorflow_core\__init__.py", line 45, in <module>
    from . _api.v2 import compat

  File "C:\Users\Bunny\AppData\Roaming\Python\Python35\site-packages\tensorflow_core\_api\v2\compat\__init__.py", line 23, in <module>
    from . import v1

  File "C:\Users\Bunny\AppData\Roaming\Python\Python35\site-packages\tensorflow_core\_api\v2\compat\v1\__init__.py", line 40, in <module>
    from . import experimental

  File "C:\Users\Bunny\AppData\Roaming\Python\Python35\site-packages\tensorflow_core\_api\v2\compat\v1\experimental\__init__.py", line 11, in <module>
    from tensorflow.python.ops.control_flow_v2_toggles import output_all_intermediates

  File "C:\Users\Bunny\AppData\Roaming\Python\Python35\site-packages\tensorflow_core\python\ops\control_flow_v2_toggles.py", line 24, in <module>
    from tensorflow.python.ops import control_flow_util_v2

  File "C:\Users\Bunny\AppData\Roaming\Python\Python35\site-packages\tensorflow_core\python\ops\control_flow_util_v2.py", line 28, in <module>
    from tensorflow.python.keras.engine import base_layer_utils

  File "C:\Users\Bunny\AppData\Roaming\Python\Python35\site-packages\tensorflow_core\python\keras\__init__.py", line 27, in <module>
    from tensorflow.python.keras import applications

  File "C:\Users\Bunny\AppData\Roaming\Python\Python35\site-packages\tensorflow_core\python\keras\applications\__init__.py", line 25, in <module>
    from tensorflow.python.keras import engine

  File "C:\Users\Bunny\AppData\Roaming\Python\Python35\site-packages\tensorflow_core\python\keras\engine\__init__.py", line 24, in <module>
    from tensorflow.python.keras.engine.input_layer import Input

  File "C:\Users\Bunny\AppData\Roaming\Python\Python35\site-packages\tensorflow_core\python\keras\engine\input_layer.py", line 25, in <module>
    from tensorflow.python.keras.distribute import distributed_training_utils

  File "C:\Users\Bunny\AppData\Roaming\Python\Python35\site-packages\tensorflow_core\python\keras\distribute\distributed_training_utils.py", line 38, in <module>
    from tensorflow.python.keras import callbacks

  File "C:\Users\Bunny\AppData\Roaming\Python\Python35\site-packages\tensorflow_core\python\keras\callbacks.py", line 53, in <module>
    import requests

  File "C:\Users\Bunny\Anaconda3\lib\site-packages\requests\__init__.py", line 63, in <module>
    from . import utils

  File "C:\Users\Bunny\Anaconda3\lib\site-packages\requests\utils.py", line 22, in <module>
    from . import certs

  File "C:\Users\Bunny\Anaconda3\lib\site-packages\requests\certs.py", line 17, in <module>
    from certifi import where

  File "<frozen importlib._bootstrap>", line 968, in _find_and_load

  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 892, in _find_spec

  File "<frozen importlib._bootstrap>", line 873, in _find_spec_legacy

  File "C:\Users\Bunny\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 254, in find_module
    fp, pathname, (ext,mode,ty) = imp.find_module(fullname,package_path)

  File "C:\Users\Bunny\Anaconda3\lib\imp.py", line 271, in find_module
    "not {}".format(type(path)))

RuntimeError: 'path' must be None or a list, not <class '_frozen_importlib_external._NamespacePath'>

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  3.2.3
* Python version:  3.5.6
* Qt version:  5.9.7
* PyQt version:  5.9.2
* Operating System name/version:  Windows 10(64 bit)

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.6

**Comment by johnsonbunny23** [comment]
Thank you so much Carlos :) It's working now.
