### ISSUE TITLE
Error occured while starting the kernel in spyder

### ISSUE THREAD

**Issue by pranavtare** [spyder-ide/spyder#10758]
I have tried to reset spyder to default setting , but problem has not been solved.
Also i have updated ipkernel and tried all solutions on github. But still its not working.
Please help if anyone know how to solve this problem, and how this  problem  occures??

**Comment by pranavtare** [comment]
![kernelIssue](https://user-images.githubusercontent.com/54949647/69123098-80448d00-0ac6-11ea-8a11-b8fcbedb993a.png)

**Comment by ccordoba12** [comment]
The error is not complete. Please copy the full text of it and paste it here.

**Comment by pranavtare** [comment]
Traceback (most recent call last):
File "C:\Users\tarep\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\tarep\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\tarep\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\tarep\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 287, in main
import_spydercustomize()
File "C:\Users\tarep\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 39, in import_spydercustomize
import spydercustomize
File "C:\Users\tarep\Anaconda3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 27, in 
from IPython.core.getipython import get_ipython
File "C:\Users\tarep\Anaconda3\lib\site‑packages\IPython\__init__.py", line 55, in 
from .terminal.embed import embed
File "C:\Users\tarep\Anaconda3\lib\site‑packages\IPython\terminal\embed.py", line 14, in 
from IPython.core.magic import Magics, magics_class, line_magic
File "C:\Users\tarep\Anaconda3\lib\site‑packages\IPython\core\magic.py", line 20, in 
from IPython.core import oinspect
File "C:\Users\tarep\Anaconda3\lib\site‑packages\IPython\core\oinspect.py", line 29, in 
from IPython.lib.pretty import pretty
File "C:\Users\tarep\Anaconda3\lib\site‑packages\IPython\lib\pretty.py", line 82, in 
import datetime
File "C:\Users\tarep\datetime.py", line 12, in 
import calendar 
File "C:\Users\tarep\Anaconda3\lib\calendar.py", line 50, in 
class _localized_month:
File "C:\Users\tarep\Anaconda3\lib\calendar.py", line 52, in _localized_month
_months = [datetime.date(2001, i+1, 1).strftime for i in range(12)]
File "C:\Users\tarep\Anaconda3\lib\calendar.py", line 52, in 
_months = [datetime.date(2001, i+1, 1).strftime for i in range(12)]
AttributeError: module 'datetime' has no attribute 'date'

**Comment by pranavtare** [comment]
> The error is not complete. Please copy the full text of it and paste it here.

This is the all error i have copied here...please help...I have tried all that you have suggested to all who got this kind of error but it will not work.
please provide solution to it as early as possible and how this happens??
so further i can take care of it....please help

**Comment by pranavtare** [comment]
my problem has been solved ....i have saved 2 programs namely calendar and datetime name respectively...
so interpreter causing clash with it...because they are also modules in it...
so just deleted those files and problem has been solved

**Comment by ccordoba12** [comment]
> my problem has been solved ....i have saved 2 programs namely calendar and datetime name respectively...

Yes, that was the problem.
