### ISSUE TITLE
Error after installation..

### ISSUE THREAD

**Issue by piceaSILC** [spyder-ide/spyder#10776]
### What steps will reproduce the problem?

The error is:

Traceback (most recent call last):
File "D:\Python\Anaconda\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "D:\Python\Anaconda\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "D:\Python\Anaconda\lib\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "D:\Python\Anaconda\lib\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "D:\Python\Anaconda\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "D:\Python\Anaconda\lib\site‑packages\jupyter_client\connect.py", line 102, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\iprior\\AppData\\Roaming\\jupyter\\runtime\\kernel�be20e34a.json'

This error in console window when installing...
Anaconda3-2019.10-Windows-x86_64

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
IPython >=4.0     :  7.8.0 (OK)
cython >=0.21     :  0.29.13 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
numpy >=1.7       :  1.16.5 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.4.2 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
sympy >=0.7.3     :  1.4 (OK)
```

**Comment by ccordoba12** [comment]
Please open the Anaconda Prompt and run there

    conda update --all

**Comment by piceaSILC** [comment]
Thanks…fixed
