### ISSUE TITLE
KeyError when removing syntax error in editor

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#10777]
### What steps will reproduce the problem?

This error is generated when a syntax error is removed quickly in the editor. It seems caused by the new folding functionality.

### Traceback
```python-traceback
  File "/home/carlos/Projects/spyder/github-repo/spyder/plugins/completion/plugin.py", line 120, in receive_response

Traceback (most recent call last):
  File "/home/carlos/Projects/spyder/github-repo/spyder/plugins/completion/plugin.py", line 120, in receive_response
    self._maybe_send_locked(req_id)
  File "/home/carlos/Projects/spyder/github-repo/spyder/plugins/completion/plugin.py", line 161, in _maybe_send_locked
    send()
  File "/home/carlos/Projects/spyder/github-repo/spyder/plugins/completion/plugin.py", line 143, in send
    self.gather_and_send(request_responses)
  File "/home/carlos/Projects/spyder/github-repo/spyder/plugins/completion/plugin.py", line 212, in gather_and_send
    response_instance.handle_response(req_type, responses)
  File "/home/carlos/Projects/spyder/github-repo/spyder/plugins/editor/widgets/codeeditor.py", line 928, in handle_response
    handler(params)
  File "/home/carlos/Projects/spyder/github-repo/spyder/plugins/editor/widgets/codeeditor.py", line 1325, in handle_folding_range
    folding_panel.update_folding(ranges)
  File "/home/carlos/Projects/spyder/github-repo/spyder/plugins/editor/panels/codefolding.py", line 220, in update_folding
    folding_status[new_line] = self.folding_status[line]
KeyError: 297
```

## Versions

* Spyder version: 4.0.0.dev0 ddaf309bd
* Python version: 3.7.5
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.13.16-041316-generic

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.6.0            :  4.5.5 (NOK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.1 (OK)
pylint >=0.25                :  2.4.3 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.0;<2.0.0:  1.9.0.dev0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.13 (OK)
IPython >=4.0                :  7.9.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.2 (OK)
numpy >=1.7                  :  1.17.3 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.31.0;<0.32.0        :  0.31.1 (OK)
xdg >=0.26                   :  0.26 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment]
@andfoy, please take a look at this one. Worst case, we could simply catch that KeyError and pass on it (folding seems fine after that), as we talked about.
