### ISSUE TITLE
Spyder 4: Error when splitting the window

### ISSUE THREAD

**Issue by lwbaqueros** [spyder-ide/spyder#10780]
### What steps will reproduce the problem?

When I clic in a file for splitting in a vertical panel, it split in horizontal panel.

So, i select slipt in horizontal (for having vertical split) and it crash syder

### Traceback
```python-traceback
    self.process_code_analysis(params['params'])
    self.cleanup_code_analysis()
    self.setUpdatesEnabled(False)
RuntimeError: wrapped C/C++ object of type CodeEditor has been deleted

Traceback (most recent call last):
    msg = self.format(record)
    return fmt.format(record)
    record.message = record.getMessage()
    msg = msg % self.args
ValueError: incomplete format
Call stack:
    sys.exit(main())
    mainwindow.main()
    mainwindow = run_spyder(app, options, args)
    app.exec_()
    handler(resp['params'])
    {'params': diagnostics})
    handler(params)
    self.log_lsp_handle_errors("Error when processing linting")
    logger.error('%', 1, stack_info=True)
Arguments: (1,)
Traceback (most recent call last):
  File "F:\Users\lbaquero\Anaconda3\envs\spyder-beta\lib\site-packages\spyder\plugins\editor\lsp\client.py", line 259, in on_msg_received
    handler(resp['params'])
  File "F:\Users\lbaquero\Anaconda3\envs\spyder-beta\lib\site-packages\spyder\plugins\editor\lsp\providers\document.py", line 51, in process_document_diagnostics
    {'params': diagnostics})
  File "F:\Users\lbaquero\Anaconda3\envs\spyder-beta\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 765, in handle_response
    self.lsp_response_signal.emit(method, params)
RuntimeError: wrapped C/C++ object of type CodeEditor has been deleted
```

## Versions

* Spyder version: 4.0.0b2 
* Python version: 3.7.5
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0     :  2.4.2 (OK)
qdarkstyle >=2.6.4 :  2.7 (OK)
sphinx >=0.6.6     :  2.2.1 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.6.1 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.17.3 (OK)
sympy >=0.7.3      :  None (NOK)
cython >=0.21      :  None (NOK)
qtconsole >=4.2.0  :  4.5.5 (OK)
IPython >=4.0      :  7.9.0 (OK)
matplotlib >=2.0.0 :  None (NOK)
pylint >=0.25      :  2.4.3 (OK)
```

**Comment by goanpeca** [comment]
@lwbaqueros could you update to Spyder 4.0.0rc2 and check again?

**Comment by lwbaqueros** [comment]
Buenas Buenas!!!
The release candidate 2 works perfectly with splitting edit pane. However, when I installed this version, plugins like spyder-notepad and spyder-terminal doesn't work. 

I open another issue for the plugins mentioned.

Thank you

**Comment by ccordoba12** [comment]
> The release candidate 2 works perfectly with splitting edit pane. However, when I installed this version, plugins like spyder-notepad and spyder-terminal doesn't work.

They are in the process of being updated to work with Spyder 4.
