### ISSUE TITLE
Project explorer produces AttributeError when loading

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1080]
_From [mrcl...@gmail.com](https://code.google.com/u/104852577201942867952/) on 2012-06-05T17:22:51Z_

Spyder Version:  2.1.10
Python Version:  2.7.3
Qt Version:      4.7.4, PyQt4 (API v1) 4.9.1 on Darwin 

What steps will reproduce the problem?

 1. Start Spyder What is the expected output? What do you see instead? Project explorer should load without errors. The following error occurs 10 times upon loading:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 664, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace' 

Please provide any additional information below

. All other widgets load without error. I'm not sure what relation there may be to issue #897 since I'm NOT using PySide

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1080_

**Comment by spyder-issues-migrator** [comment]
_From [mrcl...@gmail.com](https://code.google.com/u/104852577201942867952/) on 2012-06-05T15:26:37Z_

I meant to reference issue #934 , not issue #897 , although I think they're merged.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-07-15T11:51:39Z_

This issue was closed by revision ee5707551c45 .

**Status:** Fixed
