### ISSUE TITLE
ipython-qtconsole not listed as optional dependency in Ubuntu

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1081]
_From [r...@dpwrussell.com](https://code.google.com/u/108092953647633845890/) on 2012-06-06T05:28:02Z_

Checkout code
./bootstrap.py

from iPython.frontend.qt.kernelmanager import QtKernelManager
ImportError: No module named qt.kernelmanager

Ubuntu Linux 12.04

README should probably be updated to specify ipython-qtconsole as a dependency as this module is part of that package.

Cheers

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1081_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-06-06T06:59:54Z_

Yes, you're right. But it's only an optional dependency. You should be able to run Spyder just fine without it.

I guess you have ipython but not ipython-qtconsole installed, right? In that case we have to look for its presence on Ubuntu, and not only for the ipython one.

Could you also please post the full traceback you're getting when running bootstrap.py?

**Summary:** ipython-qtconsole not listed as optional dependency in Ubuntu  
  **Status:** Accepted  
  **Labels:** OpSys-Linux

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-06-06T07:00:39Z_

**Labels:** MS-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [r...@dpwrussell.com](https://code.google.com/u/108092953647633845890/) on 2012-06-06T07:11:28Z_

Yes, that's right. I did think it was strange that iPython was only an optional dep but yet it failed.

Full traceback:

dpwrussell@ubuntu:~/spyderlib$ ./bootstrap.py 
Executing Spyder from source checkout Revision e67793ec2995 :2162, Branch: default
01. Patched sys.path with /home/dpwrussell/spyderlib
02. No PySide detected, using PyQt4 if available
Traceback (most recent call last):
  File "./bootstrap.py", line 73, in \<module>
    from spyderlib import spyder
  File "/home/dpwrussell/spyderlib/spyderlib/spyder.py", line 120, in \<module>
    from spyderlib.plugins.ipythonconsole import IPythonConsole
  File "/home/dpwrussell/spyderlib/spyderlib/plugins/ipythonconsole.py", line 37, in \<module>
    from spyderlib.widgets.ipython import IPythonApp
  File "/home/dpwrussell/spyderlib/spyderlib/widgets/ipython.py", line 12, in \<module>
    from IPython.frontend.qt.kernelmanager import QtKernelManager
ImportError: No module named qt.kernelmanager

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-06-11T16:13:57Z_

This issue was updated by revision 675ed3b0779f .


In Ubuntu (and probably other Linux distros) qtconsole is installed in a
different package from regular ipython called ipython-qtconsole. So we not only
have to look for IPython when trying to initialize our IPython Console, but also
for the modules installed by this package, which fall under IPython.frontend.qt

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-06-11T23:45:42Z_

Optional dependency the absence of which makes Spyder fail doesn't look like optional to me. =)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-06-12T05:29:48Z_

That's why I introduced the change, so that Spyder can start without IPython nor IPython.frontend.qt. Then our users could use the old external console as a Python interpreter.

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-06-12T07:25:34Z_

But that makes the matter worse. The requirements list IPython, so People will install it, but not IPython.frontend.qt - and Spyder will still fail to work with IPython (yet it will not fail completely).

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-06-12T17:13:42Z_

Well, you're right: we have to change the docs and list ipython-qtconsole (not ipython) as an optional dependency on Linux.

Besides, I'll remove my hack and search for IPython.frontend.qt explicitly now that I verified this works:

programs.is_module_installed('IPython.frontend.qt', '>0.12')

I thought is_module_installed didn't work like that but I was mistaken.

Is that ok with you?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-06-13T06:01:06Z_

This issue was updated by revision b6af71e36a57 .


-. IPython can be installed and work without its qt frontend, but we really need
the last one instead of the first.
-. Change suggested by Anatoly to remove the hack introduced in revision
675ed3b0779f on programs.is_module_installed
-. It clarifies the situation for the future when we decide to integrate the
IPython notebook.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-06-13T06:01:06Z_

This issue was updated by revision 70551d7ed3a6 .
