### ISSUE TITLE
scientific linux 6.2 spyder ipython socket error

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1091]
_From [m.hofsa...@gmail.com](https://code.google.com/u/100200154345498916755/) on 2012-06-12T13:16:06Z_

Spyder Version:  2.1.10
Python Version:  2.6.6
Qt Version:      4.8.0, PyQt4 (API v2) 4.9.1 on Linux
multicore cpu 

What steps will reproduce the problem?

 1. starting spyder with a ipython console What is the expected output? What do you see instead? After starting spyder,Iget the following error in the internal console.
I can't reproduce the error on a other maschine

After starting spyder I get the following error:

Start of MainWindow constructor
Initializing...
End of MainWindow constructor
*** Start of MainWindow setup ***
Loading object inspector...
Loading outline explorer...
Loading editor...
Loading file explorer...
Loading history plugin...
Loading online help...
Loading project explorer...
Loading external console...
Loading namespace browser...
Setting up main window...
Setting up window...
*** End of MainWindow setup ***
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.6/site-packages/spyderlib/widgets/externalshell/introspection.py", line 62, in run
    conn, _addr = sock.accept()
  File "/usr/lib64/python2.6/socket.py", line 197, in accept
    sock, addr = self._sock.accept()
error: [Errno 4] Unterbrechung während des Betriebssystemaufrufs

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.6/site-packages/spyderlib/widgets/externalshell/introspection.py", line 62, in run
    conn, _addr = sock.accept()
  File "/usr/lib64/python2.6/socket.py", line 197, in accept
    sock, addr = self._sock.accept()
error: [Errno 4] Unterbrechung während des Betriebssystemaufrufs

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1091_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-07-04T07:47:18Z_

Maybe this is a problem with SELinux. Could you deactivate it and try again?

**Labels:** OpSys-Linux

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-07-28T06:23:53Z_

Also translating the OS error message in english could help a little bit :)

**Comment by spyder-issues-migrator** [comment]
_From [ebori...@gmail.com](https://code.google.com/u/102672023975932251472/) on 2012-07-30T06:02:31Z_

"Interruption during the operating system call" (thanks, google.)

**Comment by spyder-issues-migrator** [comment]
_From [julien.r...@gmail.com](https://code.google.com/u/114856391987535027651/) on 2012-08-27T02:30:06Z_

I've got the exact same problem and I don't have SELinux enabled. Any idea how I can help debug that further ?

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2012-12-02T04:24:32Z_

Same problem here with:
Spyder Version:  2.2.0dev
Python Version:  2.7.3
Qt Version:      4.8.3, PyQt4 (API v2) 4.9.5 on Linux

I get at each start in the console:
Python 2.7.3 (default, Apr 24 2012, 00:00:54) 
[GCC 4.7.0 20120414 (prerelease)] on linux2
Type "copyright", "credits" or "license" for more information.

Inspect Spyder internals: spy.app, spy.window

\>>> Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/externalshell/introspection.py", line 62, in run
    conn, _addr = sock.accept()
  File "/usr/lib/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()
error: [Errno 4] Appel systÃ¨me interrompu

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/externalshell/introspection.py", line 62, in run
    conn, _addr = sock.accept()
  File "/usr/lib/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()
error: [Errno 4] Appel systÃ¨me interrompu

"Appel systÃ¨me interrompu" means "System call interrupted" (with wrong encoding ;) )

Spyder works fine afterwards.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-12-06T21:44:43Z_

I installed Scientific Linux 6.2 on a virtual machine but I can't reproduce this problem.

However, I see you have installed the latest Python, Qt and PyQt versions whereas mines are:

Python 2.6.6 (compiled with gcc 4.4.6)
Qt 4.6.2
PyQt 4.6.2

What repository should I add to get the versions you have?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-02T18:17:00Z_

Closing because of lack of response.

**Status:** WontFix
