### ISSUE TITLE
Spyder console screen error

### ISSUE THREAD

**Issue by Krisanu029** [spyder-ide/spyder#10916]
An error ocurred while starting the kernel
The error is:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 102, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KRISANU\\AppData\\Roaming\\jupyter\\runtime\\kernel�a74baec9e.json'

please help me to resolve this issue
![ERROR_MESSAGE_IN_IPYTHON_CONSOLE](https://user-images.githubusercontent.com/57766572/70035155-5b790b00-15d8-11ea-82af-a288b11282f9.png)

**Comment by goanpeca** [comment]
Please update the jupyter-core package and try again

**Comment by Krisanu029** [comment]
![image](https://user-images.githubusercontent.com/57766572/70063204-639f6d80-160d-11ea-9abd-9ef5db06a844.png)
 

there is an environment writable error.... package jupyter-core didnot update


please help me to resolve this issue

**Comment by goanpeca** [comment]
@Krisanu029 you have anaconda installed for all users which requires admin privileges. You should probably install anaconda for the current user so you do not face these problems.

**Comment by Krisanu029** [comment]
i have installed for all users which requires admin privilege....in the time of installation i didnot marked on " Just for me"...i marked on all users(requires admin privileges)

**Comment by goanpeca** [comment]
>i have installed for all users which requires admin privilege....in the time of installation i didnot marked on " Just for me"...i marked on all users(requires admin privileges)

I know so in order to make changes you need to open a Windows Anaconda Prompt woth admin privileges.

**Comment by Krisanu029** [comment]
Thank you...problem is solved ...
