### ISSUE TITLE
Control + C on a program using multiprocessing.pool

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#10926]
### What steps will reproduce the problem?

```python
import multiprocessing as mp
import time
def wait(i):
    time.sleep(10)
if __name__ == "__main__":
    pool = mp.Pool()
    pool.map(wait, range(10))
```
 1. launch the program in ipyconsole
 2. ctrl + c

### Traceback
```python-traceback
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/threaded.py", line 93, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/session.py", line 941, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'af4609397442a81d17ac6fa8a11729f2d70b33bbda8caf10d2c2cf0814768d82'
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/threaded.py", line 93, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/session.py", line 941, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'af4609397442a81d17ac6fa8a11729f2d70b33bbda8caf10d2c2cf0814768d82'
ERROR:tornado.application:Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x12fdec290>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 542, in <lambda>
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/threaded.py", line 93, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/session.py", line 941, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'af4609397442a81d17ac6fa8a11729f2d70b33bbda8caf10d2c2cf0814768d82'
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/threaded.py", line 93, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/session.py", line 941, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'af4609397442a81d17ac6fa8a11729f2d70b33bbda8caf10d2c2cf0814768d82'
ERROR:tornado.application:Exception in callback functools.partial(<bound method ThreadedZMQSocketChannel._flush of <qtconsole.client.QtZMQSocketChannel object at 0x130070a50>>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/threaded.py", line 144, in _flush
    self.stream.flush()
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 364, in flush
    self._handle_recv()
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/threaded.py", line 93, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/session.py", line 941, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'af4609397442a81d17ac6fa8a11729f2d70b33bbda8caf10d2c2cf0814768d82'
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/threaded.py", line 93, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/session.py", line 941, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'14c249f2bbd7a3c7d919dbcefb998889865f3cc10486abab11d0dc4ec590b4d1'
ERROR:tornado.application:Exception in callback functools.partial(<bound method ThreadedZMQSocketChannel._flush of <qtconsole.client.QtZMQSocketChannel object at 0x130070a50>>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/threaded.py", line 144, in _flush
    self.stream.flush()
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 364, in flush
    self._handle_recv()
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/threaded.py", line 93, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/session.py", line 941, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'14c249f2bbd7a3c7d919dbcefb998889865f3cc10486abab11d0dc4ec590b4d1'
```

## Versions

* Spyder version: 4.0.0.dev0 44c59e9f6
* Python version: 3.7.5
* Qt version: 5.12.6
* PyQt5 version: 5.12.3
* Operating System: Darwin 19.0.0

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.6.0            :  4.7.0.dev0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.1 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.5 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.1 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.0;<2.0.0:  1.9.0.dev0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.11.0.dev (OK)
matplotlib >=2.0.0           :  3.1.2 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  1.3.3 (OK)
pyls >=0.31.1;<0.32.0        :  0.31.1 (OK)
applaunchservices >=0.1.7    :  0.2.1 (OK)
```

**Comment by ccordoba12** [comment]
It doesn't seem like something we can solve here but either in spyder-kernels or jupyter-client.

**Comment by impact27** [comment]
I opened https://github.com/jupyter/jupyter_client/issues/498
