### ISSUE TITLE
Start IPython Console fails

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1092]
_From [petrus.h...@gmail.com](https://code.google.com/u/113904071220560210639/) on 2012-06-13T05:23:23Z_

What steps will reproduce the problem?

 1. Start Ipython Console What is the expected output? What do you see instead? Start of IPython Console fails, something with completion widget:

\>>> Traceback (most recent call last):
  File "/Users/petrush/Development/Python/spyderlib/spyderlib/plugins/externalconsole.py", line 772, in \<lambda>
    cf, kernel_widget_id=id(shellwidget)))
  File "/Users/petrush/Development/Python/spyderlib/spyderlib/plugins/externalconsole.py", line 825, in create_ipython_client
    self.main.ipyconsole.new_client(connection_file, kernel_widget_id)
  File "/Users/petrush/Development/Python/spyderlib/spyderlib/plugins/ipythonconsole.py", line 502, in new_client
    self.register_client(cf, kernel_widget_id, client_name)
  File "/Users/petrush/Development/Python/spyderlib/spyderlib/plugins/ipythonconsole.py", line 557, in register_client
    config=self.client_config())
  File "/Users/petrush/Development/Python/spyderlib/spyderlib/widgets/ipython.py", line 217, in create_new_client
    widget = SpyderIPythonWidget(config=config, local_kernel=False)
  File "/Users/petrush/Development/Python/spyderlib/spyderlib/widgets/ipython.py", line 66, in __init__
    super(RichIPythonWidget, self).__init__(*args, **kw)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/frontend/qt/console/ipython_widget.py", line 116, in __init__
    super(IPythonWidget, self).__init__(*args, **kw)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/frontend/qt/console/frontend_widget.py", line 126, in __init__
    super(FrontendWidget, self).__init__(*args, **kw)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/frontend/qt/console/history_console_widget.py", line 26, in __init__
    super(HistoryConsoleWidget, self).__init__(*args, **kw)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/frontend/qt/console/console_widget.py", line 177, in __init__
    LoggingConfigurable.__init__(self, **kw)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/config/configurable.py", line 84, in __init__
    self.config = config
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/utils/traitlets.py", line 307, in __set__
    obj._notify_trait(self.name, old_value, new_value)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/utils/traitlets.py", line 458, in _notify_trait
    c(name, old_value, new_value)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/config/configurable.py", line 139, in _config_changed
    setattr(self, k, deepcopy(config_value))
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/utils/traitlets.py", line 303, in __set__
    new_value = self._validate(obj, value)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/utils/traitlets.py", line 311, in _validate
    return self.validate(obj, value)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/utils/traitlets.py", line 1073, in validate
    self.error(obj, value)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/utils/traitlets.py", line 334, in error
    raise TraitError(e)
IPython.utils.traitlets.TraitError: The 'gui_completion' trait of a SpyderIPythonWidget instance must be a boolean, but a value of 'droplist' \<type 'str'> was specified. What version of the product are you using? On what operating system? 2012-06-13 svn copy of spyderlib and Ipython0.13dev 

Please provide any additional information below

. Have tried to delete spyder config files and ipython config files but problem remains.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1092_

**Comment by spyder-issues-migrator** [comment]
_From [petrus.h...@gmail.com](https://code.google.com/u/113904071220560210639/) on 2012-06-13T03:28:08Z_

This started in rev 2189

**Comment by spyder-issues-migrator** [comment]
_From [petrus.h...@gmail.com](https://code.google.com/u/113904071220560210639/) on 2012-06-13T03:54:33Z_

Sorry, please remove issue, it wasn't running my svn version of ipython. pip install -e doesn't seem to work w ipython.

Can I remove a reported issue myself?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-06-13T05:02:58Z_

Don't worry about it, but if you're running IPython and Spyder from their dev repos perhaps it's better to ask on the list first.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-06-13T05:03:19Z_

**Status:** Invalid
