### ISSUE TITLE
Way to much stuff running

### ISSUE THREAD

**Issue by Cwickniss** [spyder-ide/spyder#10939]
### What steps will reproduce the problem?

3 diff browsers (FireFox\Edge\Chrome) open with God only knows how many Tabs

### Traceback
```python-traceback
  File "C:\Users\ChadwickInniss\.conda\envs\tensorenviron\lib\site-packages\spyder_terminal\terminalplugin.py", line 327, in <lambda>
    term.terminal_closed.connect(lambda: self.close_term(term=term))
  File "C:\Users\ChadwickInniss\.conda\envs\tensorenviron\lib\site-packages\spyder_terminal\terminalplugin.py", line 340, in close_term
    term.close()
AttributeError: 'NoneType' object has no attribute 'close'
Traceback (most recent call last):
  File "C:\Users\ChadwickInniss\.conda\envs\tensorenviron\lib\site-packages\spyder_terminal\terminalplugin.py", line 327, in <lambda>
    term.terminal_closed.connect(lambda: self.close_term(term=term))
  File "C:\Users\ChadwickInniss\.conda\envs\tensorenviron\lib\site-packages\spyder_terminal\terminalplugin.py", line 340, in close_term
    term.close()
AttributeError: 'NoneType' object has no attribute 'close'
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.5
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
pandas >=0.13.1   :  0.25.3 (OK)
numpy >=1.7       :  1.17.4 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.6.0 (OK)
IPython >=4.0     :  7.9.0 (OK)
matplotlib >=2.0.0:  3.1.2 (OK)
pylint >=0.25     :  2.4.4 (OK)
```

**Comment by ccordoba12** [comment]
> 3 diff browsers (FireFox\Edge\Chrome) open with God only knows how many Tabs

This has nothing to do with Spyder.

Your error is really related to spyder-terminal, which is being updated at the moment. A new release (compatible with Spyder 4) will be available in a few weeks.

**Comment by Cwickniss** [comment]
Thankyou ... Fair enough ... Definitely a newbie. I just notice that past a certain amount of memory usage by my browsers. My machine gets weird and pauses a lot.
