### ISSUE TITLE
Ipython terminal will not open at startup

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1097]
_From [battm...@gmail.com](https://code.google.com/u/110838061384746797372/) on 2012-06-20T10:36:36Z_

Spyder Version:  2.1.10
Python Version:  2.7.3
Qt Version:      4.8.2, PyQt4 (API v2) 4.9.1 on Darwin 

What steps will reproduce the problem?

 1. Set option to start new python kernel upon start up 2. 3. What is the expected output? What do you see instead? At startup this error is reported:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/externalshell/startup.py", line 37, in \<module>
    from IPython.zmq.ipkernel import IPKernelApp
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/zmq/__init__.py", line 39, in \<module>
    check_for_zmq('2.1.4')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/zmq/__init__.py", line 19, in check_for_zmq
    raise ImportError("&#37;s requires pyzmq >= &#37;s"&#37;(module, minimum_version))
ImportError: IPython.zmq requires pyzmq >= 2.1.4 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1097_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-06-20T10:51:52Z_

Hi battmatt, you need to install pyzmq for this to work. It seems you don't have it.

**Comment by spyder-issues-migrator** [comment]
_From [battm...@gmail.com](https://code.google.com/u/110838061384746797372/) on 2012-06-20T11:33:39Z_

Ok thanks.  I used the macports install.  This is apparently not part of
their install??

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-06-20T12:51:28Z_

Just install the port called py-zmq and you'll be ready for using IPython :-)

**Comment by spyder-issues-migrator** [comment]
_From [battm...@gmail.com](https://code.google.com/u/110838061384746797372/) on 2012-06-20T13:03:29Z_

Just did.  Thanks for the help.  I'm enjoying spyder a lot so far :)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-06-20T15:22:09Z_

Great! Really glad to hear it. I'm closing this issue as invalid because it wasn't a problem on our side, but feel free to report any other problems you have through here or the list.

Cheers,
Carlos

**Status:** Invalid
