### ISSUE TITLE
Failed to start an IPython kernel with message "API 'QString' has already been set to version 1"

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1103]
_From [jorisvan...@gmail.com](https://code.google.com/u/101707288318167035253/) on 2012-06-25T16:15:48Z_

Spyder Version:  2.1.10
Python Version:  2.7.2
Qt Version:      4.7.3, PyQt4 (API v1) 4.8.5 on Windows
IPython 0.13.beta1 

What steps will reproduce the problem?

 1. Open a new IPython kernel What is the expected output? What do you see instead? I get the following error in the internal console:

\>>> Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\plugins\externalconsole.py", line 809, in \<lambda>
    cf, kernel_widget_id=id(shellwidget)))
  File "C:\Python27\lib\site-packages\spyderlib\plugins\externalconsole.py", line 862, in create_ipython_frontend
    self.main.new_ipython_frontend(connection_file, kernel_widget_id)
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 1604, in new_ipython_frontend
    from spyderlib.plugins.ipython import IPythonPlugin
  File "C:\Python27\lib\site-packages\spyderlib\plugins\ipython.py", line 14, in \<module>
    from spyderlib.widgets.ipython import IPythonApp
  File "C:\Python27\lib\site-packages\spyderlib\widgets\ipython.py", line 12, in \<module>
    from IPython.frontend.qt.kernelmanager import QtKernelManager
  File "C:\Python27\lib\site-packages\ipython-0.13.beta1-py2.7.egg\IPython\frontend\qt\kernelmanager.py", line 5, in \<module>
    from IPython.external.qt import QtCore
  File "C:\Python27\lib\site-packages\ipython-0.13.beta1-py2.7.egg\IPython\external\qt.py", line 47, in \<module>
    prepare_pyqt4()
  File "C:\Python27\lib\site-packages\ipython-0.13.beta1-py2.7.egg\IPython\external\qt.py", line 20, in prepare_pyqt4
    sip.setapi('QString', 2)
ValueError: API 'QString' has already been set to version 1 

Please provide any additional information below

. I tried to change the preferences (console -> external modules) to ignore API change errors, but the error kept appearing. The same for setting the API version to 1 or 2.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1103_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-07-03T12:02:06Z_

Yep, you're right. I'll push a fix for it soon. In the mean time you can go here: https://code.google.com/p/spyderlib/source/browse/spyderlib/spyder.py?repo=v21#30 and add '0.13' to the list.

**Summary:** Failed to start an IPython kernel with message "API 'QString' has already been set to version 1"  
  **Status:** Accepted  
  **Labels:** -OpSys-Windows MS-v2.1

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-07-03T12:32:28Z_

This issue was updated by revision f0ea240e38fd .


- Because the detection was not working correctly, it was not possible to start
an IPython kernel with the just released IPython 0.13.

**Status:** Fixed
