### ISSUE TITLE
Viewing the dataframe window crash

### ISSUE THREAD

**Issue by tdalis** [spyder-ide/spyder#11113]
## Description

**What steps will reproduce the problem?**

1. after creating a df using one hot encoding groupby('var')['var'].count()
2. I clicked on the dataframe to check it out and it through the error

**What is the expected output? What do you see instead?**
The expected output was to see the dataframe parameters. This actually opened in the background but the error message would close the window as soon as I clicked OK

**Please provide any additional information below**

  File "/usr/lib/python2.7/dist-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 277, in data
    return to_qvariant(to_text_string(self.df_index[row]))
  File "/usr/lib/python2.7/dist-packages/spyder/py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 277, in data
    return to_qvariant(to_text_string(self.df_index[row]))
  File "/usr/lib/python2.7/dist-packages/spyder/py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 277, in data
    return to_qvariant(to_text_string(self.df_index[row]))
  File "/usr/lib/python2.7/dist-packages/spyder/py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 277, in data
    return to_qvariant(to_text_string(self.df_index[row]))
  File "/usr/lib/python2.7/dist-packages/spyder/py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 277, in data
    return to_qvariant(to_text_string(self.df_index[row]))
  File "/usr/lib/python2.7/dist-packages/spyder/py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 277, in data
    return to_qvariant(to_text_string(self.df_index[row]))
  File "/usr/lib/python2.7/dist-packages/spyder/py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 277, in data
    return to_qvariant(to_text_string(self.df_index[row]))
  File "/usr/lib/python2.7/dist-packages/spyder/py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 277, in data
    return to_qvariant(to_text_string(self.df_index[row]))
  File "/usr/lib/python2.7/dist-packages/spyder/py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 2.7.17
* Qt Versions: 5.9.5, PyQt5 5.10.1 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.5 (OK)
sphinx >=0.6.6    :  1.6.7 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
psutil >=0.3      :  5.4.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.5.0 (OK)
pylint >=0.25     :  1.8.3 (OK)

```

**Comment by goanpeca** [comment]
Please update to the latest version of spyder 4.0, and check if the error persists

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by tdalis** [comment]
Hey, all good
