### ISSUE TITLE
An issue occurred while starting the Kernel

### ISSUE THREAD

**Issue by Nisha396** [spyder-ide/spyder#11121]
### What steps will reproduce the problem?

While trying to start spyder, issue is occurring in connection with the Kernel with the following error:-

Traceback (most recent call last):
File "C:\Users\Nisha\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\Nisha\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\Nisha\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\Nisha\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 287, in main
import_spydercustomize()
File "C:\Users\Nisha\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 39, in import_spydercustomize
import spydercustomize
File "C:\Users\Nisha\Anaconda3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 19, in 
import pdb
File "C:\Users\Nisha\Anaconda3\lib\pdb.py", line 136, in 
class Pdb(bdb.Bdb, cmd.Cmd):
AttributeError: module 'cmd' has no attribute 'Cmd'

Kindly help me in resolving the issue.  

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.5 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by ccordoba12** [comment]
Ypu have a file called `cmd.py` somewhere in your Users directory. You need to find it and remove it to fix this error.

**Comment by ccordoba12** [comment]
> and remove it

Well, renaming it works too.
