### ISSUE TITLE
Not sure how this happened?

### ISSUE THREAD

**Issue by ejmurray** [spyder-ide/spyder#11149]
### What steps will reproduce the problem?

~~ Installed in a clean environment and had this error.

### Traceback
```python-traceback
  File "C:\Users\ernest\AppData\Local\Continuum\miniconda3\envs\spyder\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1178, in <lambda>
    kc.started_channels.connect(lambda c=client: self.process_started(c))
  File "C:\Users\ernest\AppData\Local\Continuum\miniconda3\envs\spyder\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1753, in process_started
    self.variableexplorer.add_shellwidget(client.shellwidget)
  File "C:\Users\ernest\AppData\Local\Continuum\miniconda3\envs\spyder\lib\site-packages\spyder\plugins\variableexplorer.py", line 171, in add_shellwidget
    nsb.setup(**self.get_settings())
  File "C:\Users\ernest\AppData\Local\Continuum\miniconda3\envs\spyder\lib\site-packages\spyder\plugins\variableexplorer.py", line 107, in get_settings
    settings[name] = self.get_option(name)
  File "C:\Users\ernest\AppData\Local\Continuum\miniconda3\envs\spyder\lib\site-packages\spyder\api\plugins.py", line 177, in get_option
    return CONF.get(self.CONF_SECTION, option, default)
  File "C:\Users\ernest\AppData\Local\Continuum\miniconda3\envs\spyder\lib\site-packages\spyder\config\user.py", line 382, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'show_callable_attributes' in section: 'variable_explorer'
Traceback (most recent call last):

```

## Versions

* Spyder version: 4.0.0b1 
* Python version: 3.7.3
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.5.2 (OK)
sphinx >=0.6.6    :  2.3.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.11.0     :  0.15.1 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  None (NOK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.6.0 (OK)
IPython >=4.0     :  7.10.2 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.4.4 (OK)
```

**Comment by ccordoba12** [comment]
> Spyder version: 4.0.0b1

You're using a hear and a half old version. Please update to our latest release (4.0.0 final), which was released two weeks ago.
