### ISSUE TITLE
can't open spyder in conda environment

### ISSUE THREAD

**Issue by SSSSER1994** [spyder-ide/spyder#11146]
I have installed spyder in a env by _**conda install**_, but can't open it , here are the problems:

> Traceback (most recent call last):
  File "/home/slam/.conda/envs/deepl/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 3285, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/slam/.conda/envs/deepl/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 3140, in run_spyder
    main.setup()
  File "/home/slam/.conda/envs/deepl/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 831, in setup
    from spyder.plugins.help import Help
  File "/home/slam/.conda/envs/deepl/lib/python2.7/site-packages/spyder/plugins/help.py", line 32, in <module>
    from spyder.utils.help.sphinxify import (CSS_PATH, generate_context,
  File "/home/slam/.conda/envs/deepl/lib/python2.7/site-packages/spyder/utils/help/sphinxify.py", line 32, in <module>
    from sphinx.application import Sphinx
  File "/home/slam/.conda/envs/deepl/lib/python2.7/site-packages/sphinx/application.py", line 34, in <module>
    from sphinx.environment import BuildEnvironment
  File "/home/slam/.conda/envs/deepl/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 38, in <module>
    from sphinx.util.websupport import is_commentable
  File "/home/slam/.conda/envs/deepl/lib/python2.7/site-packages/sphinx/util/websupport.py", line 11, in <module>
    from sphinxcontrib.websupport.utils import is_commentable  # NOQA
  File "/home/slam/.conda/envs/deepl/lib/python2.7/site-packages/sphinxcontrib/websupport/__init__.py", line 16, in <module>
    from sphinxcontrib.websupport.core import WebSupport  # NOQA
  File "/home/slam/.conda/envs/deepl/lib/python2.7/site-packages/sphinxcontrib/websupport/core.py", line 29, in <module>
    from sphinxcontrib.serializinghtml.jsonimpl import dumps as dump_json
  File "/home/slam/.conda/envs/deepl/lib/python2.7/site-packages/sphinxcontrib/serializinghtml/__init__.py", line 177
    def setup(app: Sphinx) -> Dict[str, Any]:
                 ^
SyntaxError: invalid syntax

And my version 
* Spyder version: 3.3.6
* Python version: 2.7
* Qt version: 5.9.7
* PyQt version: 5.9.2
* sphinx version: 1.8.5
* Operating System name/version:ubuntu16.04

**Comment by ccordoba12** [comment]
> def setup(app: Sphinx) -> Dict[str, Any]:
^
SyntaxError: invalid syntax

This means that you installed a Python 3 version of Sphinx in a Python 2 environment. There's no way that this could have happened if you use conda to install packages on that env, so I guess you used pip for that (which we've warned against multiple times in the past).

In short, I don't know how you ended up in such a situation, but it's up to you to solve it (perhaps by recreating your `deepl` and avoiding pip to install packages on it if they are available through conda).
