### ISSUE TITLE
Code completion not working in python console

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1118]
_From [formy...@googlemail.com](https://code.google.com/u/113999221398490367026/) on 2012-07-13T08:33:49Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 In the python console, type pri<tab> What is the expected output? What do you see instead? Expected: a popup box with suggestion, e.g. print
Instead there is an exception printed in the internal console:

Traceback (most recent call last):
  File "/net/ito/c705283/Packages/spyder-hg/spyderlib/widgets/shell.py", line 296, in keyPressEvent
    self.postprocess_keyevent(event)
  File "/net/ito/c705283/Packages/spyder-hg/spyderlib/widgets/shell.py", line 728, in postprocess_keyevent
    ShellBaseWidget.postprocess_keyevent(self, event)
  File "/net/ito/c705283/Packages/spyder-hg/spyderlib/widgets/shell.py", line 351, in postprocess_keyevent
    self._key_tab()
  File "/net/ito/c705283/Packages/spyder-hg/spyderlib/widgets/shell.py", line 760, in _key_tab
    self.show_code_completion(automatic=False)
  File "/net/ito/c705283/Packages/spyder-hg/spyderlib/widgets/shell.py", line 910, in show_code_completion
    b_k_g = dir(__builtin__)+self.get_globals_keys()+keyword.kwlist
TypeError: can only concatenate list (not "NoneType") to list What version of the product are you using? On what operating system? CentOs 6.2, spyder mercurial (checkout Fri Jul 13, rev b12ffd359c2e), Qt/PyQt4 v4.6.2, Python 2.6.6

I'm happy to do more testing or to provide additional information.

Thank you for this great peace of software :)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1118_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-07-22T05:20:01Z_

I think this happens because the monitor is not working. Could you check if it's activated in Tools > Preferences > Console > Introspection > Enable monitor?

**Labels:** OpSys-Linux Cat-Console

**Comment by spyder-issues-migrator** [comment]
_From [formy...@googlemail.com](https://code.google.com/u/113999221398490367026/) on 2012-07-23T01:16:58Z_

It happens both with the monitor enabled or not. But I forgot to mention that it is only the IPython console which is affected, not the regular Python console.

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-07-24T01:14:09Z_

**Labels:** -Cat-Console Cat-IPythonConsole

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-23T18:23:30Z_

This shouldn't be a problem with our new IPython console. Thanks for reporting.

**Status:** WontFix
