### ISSUE TITLE
os.listdir(root)

### ISSUE THREAD

**Issue by mbh038** [spyder-ide/spyder#11225]
### What steps will reproduce the problem?

This comes up randomly throughout my use of spyder. Have updated  spyder, conda and anaconda.

### Traceback
```python-traceback
  File "/Users/mbh/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/explorer.py", line 878, in restore_directory_state
    for basename in os.listdir(root):
PermissionError: [Errno 1] Operation not permitted: '/Users/mbh/Documents'
Traceback (most recent call last):
  File "/Users/mbh/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/explorer.py", line 878, in restore_directory_state
    for basename in os.listdir(root):
PermissionError: [Errno 1] Operation not permitted: '/Users/mbh/Documents'
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.2.0

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.5.2 (OK)
sphinx >=0.6.6    :  2.3.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
psutil >=0.3      :  5.6.7 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
pandas >=0.13.1   :  0.25.3 (OK)
numpy >=1.7       :  1.17.4 (OK)
sympy >=0.7.3     :  1.5 (OK)
cython >=0.21     :  0.29.14 (OK)
qtconsole >=4.2.0 :  4.6.0 (OK)
IPython >=4.0     :  7.10.2 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.4 (OK)
```

**Comment by ccordoba12** [comment]
This is a problem with macOS Catalina. Please see here

https://stackoverflow.com/q/58372768/438386

for possible solutions.
