### ISSUE TITLE
Spyder notebook

### ISSUE THREAD

**Issue by MrTuncay** [spyder-ide/spyder#11242]
### What steps will reproduce the problem?

File -> File switcher.. -> Notebook plugin -> Open .. -> file.ipynb

Error message:
~~~
This site can’t be reached

localhost refused to connect.
Try:
~~~

### Traceback
```python-traceback
  File "C:\Users\User\.conda\envs\datacamp\lib\site-packages\spyder_notebook\notebookplugin.py", line 378, in close_client
    client.shutdown_kernel()
  File "C:\Users\User\.conda\envs\datacamp\lib\site-packages\spyder_notebook\widgets\client.py", line 248, in shutdown_kernel
    kernel_id = self.get_kernel_id()
  File "C:\Users\User\.conda\envs\datacamp\lib\site-packages\spyder_notebook\widgets\client.py", line 241, in get_kernel_id
    notebook_path = session.get('notebook', {}).get('path')
AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Users\User\.conda\envs\datacamp\lib\site-packages\spyder_notebook\notebookplugin.py", line 378, in close_client
    client.shutdown_kernel()
  File "C:\Users\User\.conda\envs\datacamp\lib\site-packages\spyder_notebook\widgets\client.py", line 248, in shutdown_kernel
    kernel_id = self.get_kernel_id()
  File "C:\Users\User\.conda\envs\datacamp\lib\site-packages\spyder_notebook\widgets\client.py", line 241, in get_kernel_id
    notebook_path = session.get('notebook', {}).get('path')
AttributeError: 'str' object has no attribute 'get'
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 4.0.0 
* Python version: 3.7.5
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.3.0 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.11.1 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.0 (OK)
numpy >=1.7                  :  1.16.4 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by MrTuncay** [comment]
After opening an existing notebook error occurs.
Error Message: 

This site can’t be reached

localhost refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
