### ISSUE TITLE
Installment Problem

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1124]
_From [davidtgo...@gmail.com](https://code.google.com/u/100777335372158877533/) on 2012-07-25T10:07:14Z_

Spyder Version:  2.1.9
Python Version:  2.7.2
Qt Version:      4.7.4, PyQt4 (API v1) 4.8.6 on Windows

I've just installed Pythonxy and when I open Spyder my internal console has this error message written (below). Before this happened there was a message indicating if I should allow or deny something (I didn't get to read it) and I selected 'deny'.

I've tried uninstalling and reinstalling the program but the same thing comes up. How do you think I can fix this? Thanks! 

Please provide any additional information below

. >>> Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 552, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\introspection.py", line 61, in run
    sock.listen(2)
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions

Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 552, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\introspection.py", line 61, in run
    sock.listen(2)
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1124_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-07-28T13:54:26Z_

That's simply your firewall blocking Spyder's communication socket (Spyder uses a socket to communicate between the main GUI process and remote Python processes: executed scripts and Python/IPython interpreters).

If you disable this rule and choose "allow" this time, everything will be alright.

**Status:** Done
