### ISSUE TITLE
Creating new project fails

### ISSUE THREAD

**Issue by akosgulyban** [spyder-ide/spyder#11250]
### What steps will reproduce the problem?

I was trying to create new project based on an existing directory, but I can't save/re-open the project. It does not show up in the recent project list either

### Traceback
```python-traceback
  File "C:\Users\gulyban\miniconda3\lib\site-packages\spyder\plugins\editor\panels\codefolding.py", line 256, in paintEvent


QBackingStore::endPaint() called with active painter on backingstore paint device
Traceback (most recent call last):
  File "C:\Users\gulyban\miniconda3\lib\site-packages\spyder\plugins\editor\panels\codefolding.py", line 256, in paintEvent
    QWidget::repaint: Recursive repaint detected
  File "C:\Users\gulyban\miniconda3\lib\site-packages\spyder\plugins\editor\panels\codefolding.py", line 300, in _draw_fold_region_background
    QBackingStore::endPaint() called with active painter on backingstore paint device
end = self.folding_regions[start]
KeyError: 24
Traceback (most recent call last):
  File "C:\Users\gulyban\miniconda3\lib\site-packages\spyder\plugins\editor\panels\codefolding.py", line 256, in paintEvent
    self._draw_fold_region_background(block, painter)
  File "C:\Users\gulyban\miniconda3\lib\site-packages\spyder\plugins\editor\panels\codefolding.py", line 300, in _draw_fold_region_background
    end = self.folding_regions[start]
KeyError: 24
```

## Versions

* Spyder version: 4.0.0 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
sphinx >=0.6.6               :  2.2.0 (OK)
pylint >=0.25                :  2.3.1 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.13 (OK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
numpy >=1.7                  :  1.16.5 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=4.0.1

**Comment by akosgulyban** [comment]
Thanks, Solved

I was able to install it by:
`conda install spyder=4.0.1 -c conda-forge`
