### ISSUE TITLE
Crash from opening options

### ISSUE THREAD

**Issue by endolith** [spyder-ide/spyder#11262]
### What steps will reproduce the problem?

I tried to open Options and it crashed

I don't know what else to say

### Traceback
```python-traceback
  File "C:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3139, in show_preferences
    widget = plugin._create_configwidget(dlg, self)
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\base.py", line 117, in _create_configwidget
    configwidget.initialize()
  File "C:\Anaconda3\lib\site-packages\spyder\preferences\configdialog.py", line 72, in initialize
    self.load_from_conf()
  File "C:\Anaconda3\lib\site-packages\spyder\preferences\configdialog.py", line 327, in load_from_conf
    checkbox.setChecked(self.get_option(option, default, section=sec))
TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.11.1 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
zmq >=17                     :  18.1.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
sphinx >=0.6.6               :  2.3.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.14 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
numpy >=1.7                  :  1.17.4 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
sympy >=0.7.3                :  1.5 (OK)
```

**Comment by ccordoba12** [comment]
I don't understand how this could appear unless you edited our config file directly.

Could you share your configuration file with us to try to reproduce this? It's normally placed in

    C:\Users\<your user>\.spyder-py3\config\spyder.ini

**Comment by endolith** [comment]
https://gist.github.com/endolith/0096a263e62e3b037dcf405fbed04bc5

**Comment by ccordoba12** [comment]
Thanks a lot @endolith!

@dalthviz, please take a look at this one.

**Comment by ccordoba12** [comment]
@dalthviz, you need to replace your config file with @endolith's one and try to open our Preferences to generate the error.

**Comment by dalthviz** [comment]
@ccordoba12 I'm able to open the preferences dialog. The only thing I'm seeing is a warning about a font that could not be found: `Warning: None of the following fonts is installed: ['DejaVu Sans']`

**Comment by ccordoba12** [comment]
@endolith, please close Spyder, open this file in another text editor

    C:\Anaconda3\lib\site-packages\spyder\preferences\configdialog.py

add in line `326` this statement

    print(self.get_option(option, default, section=sec))

then start Spyder, open our Preferences and finally go to the menu

    View > Panes > Internal console

and paste the contents shown there here.

**Comment by endolith** [comment]
> open this file in another text editor
> 
> C:\Anaconda3\lib\site-packages\spyder\preferences\configdialog.py

I have no such file. I have 

C:\Anaconda3\pkgs\spyder-4.0.1-py37_0\Lib\site-packages\spyder\preferences\configdialog.py
C:\Anaconda3\pkgs\spyder-4.0.0-py37_0\Lib\site-packages\spyder\preferences\configdialog.py
C:\Anaconda3\envs\tf_gpu\Lib\site-packages\spyder\preferences\configdialog.py
C:\Anaconda3\pkgs\spyder-4.0.0rc1-py37_0\Lib\site-packages\spyder\preferences\configdialog.py
C:\Anaconda3\pkgs\spyder-3.3.6-py37_0\Lib\site-packages\spyder\widgets\projects\configdialog.py
C:\Anaconda3\pkgs\spyder-3.3.6-py37_0\Lib\site-packages\spyder\plugins\configdialog.py

and some others related to idlelib

**Comment by ccordoba12** [comment]
That file should exist because that's what your error shows.

I'm going to close this one for now because we can't reproduce it and you can't help us to solve it. Please keep posting on this issue if you find more info.

**Comment by endolith** [comment]
o_O 

It's reproducible every time I press Tools → Preferences

**Comment by endolith** [comment]
Ok the file is there now, but your command doesn't seem to work:

```
Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3119, in show_preferences
    widget.initialize()
  File "C:\Anaconda3\lib\site-packages\spyder\preferences\configdialog.py", line 72, in initialize
    self.load_from_conf()
  File "C:\Anaconda3\lib\site-packages\spyder\preferences\configdialog.py", line 326, in load_from_conf
    print(self.get_option(option, default, section=sec))        
UnboundLocalError: local variable 'option' referenced before assignment
```

**Comment by endolith** [comment]
I moved it down one line:


```
    def load_from_conf(self):
        """Load settings from configuration file."""
        for checkbox, (sec, option, default) in list(self.checkboxes.items()):
            print(self.get_option(option, default, section=sec))  
            checkbox.setChecked(self.get_option(option, default, section=sec))

```

```
Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> True
False
True
True
False
False
True
False
True
False
True
True
False
False
True
True
False
False
False
False
False
True
True
True
True
True
True
True
True
True
True
False
True
True
True
True
False
False
False
False
True
False
False
True
False
True
True
False
False
True
True
True
True
True
True
False
True
True
True
True
True
False
True
True
True
False
True
False
True
False
True
False
True
True
False
True
False
False
False
False
True
True
False
True
False
False
True
True
True
False
True
False
True
False
True
False
False
True
True
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3139, in show_preferences
    widget = plugin._create_configwidget(dlg, self)
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\base.py", line 117, in _create_configwidget
    configwidget.initialize()
  File "C:\Anaconda3\lib\site-packages\spyder\preferences\configdialog.py", line 72, in initialize
    self.load_from_conf()
  File "C:\Anaconda3\lib\site-packages\spyder\preferences\configdialog.py", line 328, in load_from_conf
    checkbox.setChecked(self.get_option(option, default, section=sec))
TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'
```

**Comment by dalthviz** [comment]
@endolith could you give us the list of packages that you have installed? please use `conda list` and `pip list` maybe you have multiple versions of Spyder installed at the same time? (one with `conda` and one with `pip`) Thanks :)

**Comment by dalthviz** [comment]
Another thing you could try @endolith is to reset your preferences going to `Tools > Reset Spyder to factory defaults` (although this will remove all the preferences that you have changed in the past)

**Comment by dalthviz** [comment]
Also @endolith in order to get the name of the option that is causing this, could you please add a print line above the one you already have printing the variable `option`? Something like `print(option)`

**Comment by ccordoba12** [comment]
> Another thing you could try @endolith is to reset your preferences going to Tools > Reset Spyder to factory defaults (although this will remove all the preferences that you have changed in the past)

This is a good suggestion @dalthviz but it won't allow us to solve this problem.

@endolith, please follow this @dalthviz advice instead:

> in order to get the name of the option that is causing this, could you please add a print line above the one you already have printing the variable option?

**Comment by endolith** [comment]
<details>
```
>>> single_instance
True
prompt_on_exit
False
show_internal_errors
True
check_updates_on_startup
True
vertical_dockwidget_titlebars
False
vertical_tabs
False
animated_docks
True
tear_off_menus
False
use_custom_margin
True
use_custom_cursor_blinking
False
show_status_bar
True
memory_usage/enable
True
cpu_usage/enable
False
clock/enable
False
umr/enabled
True
umr/verbose
True
post_mortem
False
clear_namespace
False
console_namespace
False
interact
False
open_on_firstrun
False
code_completion
True
completions_hint
True
automatic_completions
True
code_snippets
True
jedi_definition
True
jedi_definition/follow_imports
True
jedi_signature_help
True
enable_hover_hints
True
pyflakes
True
underline_errors
True
mccabe
False
pycodestyle
True
pydocstyle
True
enable
True
enable
True
call_to_action
False
advanced/enabled
False
advanced/external
False
advanced/stdio
False
show_tab_bar
True
show_class_func_dropdown
False
indent_guides
False
line_numbers
True
blank_spaces
False
highlight_current_line
True
highlight_current_cell
True
wrap
False
scroll_past_end
False
edge_line
True
occurrence_highlighting
True
close_parentheses
True
close_quotes
True
add_colons
True
auto_unindent
True
tab_always_indent
False
strip_trailing_spaces_on_modify
True
intelligent_backspace
True
always_remove_trailing_spaces
True
save_all_before_run
True
focus_to_editor
True
run_cell_copy
False
autosave_enabled
True
todo_list
True
check_eol_chars
True
convert_eol_on_save
False
show_banner
True
use_pager
False
show_calltips
True
ask_before_closing
False
show_reset_namespace_warning
True
show_elapsed_time
False
ask_before_restart
True
pylab
True
pylab/autoload
False
pylab/inline/bbox_inches
True
startup/use_run_file
False
jedi_completer
False
greedy_completer
False
symbolic_math
False
hide_cmd_windows
True
wrap
True
line_numbers
False
go_to_eof
True
connect/editor
False
connect/ipython_console
False
math
True
wrap
True
exclude_private
True
exclude_capitalized
False
exclude_uppercase
True
exclude_unsupported
False
exclude_callables_and_modules
True
minmax
False
show_all
True
show_icontext
False
single_click_to_open
False
save_before
True
use_colors
True
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3139, in show_preferences
    widget = plugin._create_configwidget(dlg, self)
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\base.py", line 117, in _create_configwidget
    configwidget.initialize()
  File "C:\Anaconda3\lib\site-packages\spyder\preferences\configdialog.py", line 72, in initialize
    self.load_from_conf()
  File "C:\Anaconda3\lib\site-packages\spyder\preferences\configdialog.py", line 329, in load_from_conf
    checkbox.setChecked(self.get_option(option, default, section=sec))
TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'
```
</details>

**Comment by endolith** [comment]
<details>
```
(base) λ conda list
# packages in environment at C:\Anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2019.03                  py37_0
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
alabaster                 0.7.12                   py37_0
anaconda                  custom                   py37_1
anaconda-client           1.7.2                    py37_0
anaconda-navigator        1.9.7                    py37_0
anaconda-project          0.8.4                      py_0
argh                      0.26.2                   py37_0
asn1crypto                1.2.0                    py37_0
astroid                   2.3.3                    py37_0
astropy                   4.0              py37he774522_0
atomicwrites              1.3.0                    py37_1
attrs                     19.3.0                     py_0
autopep8                  1.4.4                      py_0
babel                     2.8.0                      py_0
backcall                  0.1.0                    py37_0
backports                 1.0                        py_2
backports.functools_lru_cache 1.6.1                      py_0
backports.os              0.1.1                    py37_0
backports.shutil_get_terminal_size 1.0.0                    py37_2
backports.tempfile        1.0                        py_1
backports.weakref         1.0.post1                  py_1
bcrypt                    3.1.7            py37he774522_0
beautifulsoup4            4.8.2                    py37_0
bitarray                  1.2.0            py37he774522_0
bkcharts                  0.2                      py37_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
blessings                 1.7                      pypi_0    pypi
blosc                     1.16.3               h7bd577a_0
bokeh                     1.4.0                    py37_0
boto                      2.49.0                   py37_0
bottleneck                1.3.1            py37h8c2d366_0
bzip2                     1.0.8                he774522_0
ca-certificates           2019.11.27                    0
certifi                   2019.11.28               py37_0
cffi                      1.13.2           py37h7a1dbc1_0
chardet                   3.0.4                 py37_1003
click                     7.0                      py37_0
cloudpickle               1.2.2                      py_0
clyent                    1.2.2                    py37_1
colorama                  0.4.3                      py_0
comtypes                  1.1.7                    py37_0
conda                     4.8.1                    py37_0
conda-build               3.18.9                   py37_3
conda-env                 2.6.0                         1
conda-package-handling    1.6.0            py37h62dcd97_0
conda-verify              3.4.2                      py_1
console_shortcut          0.1.1                         3
contextlib2               0.6.0.post1                py_0
coverage                  5.0              py37he774522_0
cryptography              2.8              py37h7a1dbc1_0
cudatoolkit               10.0.130                      0
cudnn                     7.6.5                cuda10.0_0
cupy                      6.0.0            py37h230ac6f_0
curl                      7.67.0               h2a8f88b_0
cycler                    0.10.0                   py37_0
cython                    0.29.14          py37ha925a31_0
cytoolz                   0.10.1           py37he774522_0
dask                      2.9.1                      py_0
dask-core                 2.9.1                      py_0
decorator                 4.4.1                      py_0
defusedxml                0.6.0                      py_0
diff-match-patch          20181111                   py_0
distributed               2.9.1                      py_0
docutils                  0.15.2                   py37_0
elsim                     0.1.0                     dev_0    <develop>
entrypoints               0.3                      py37_0
et_xmlfile                1.0.1                    py37_0
fastcache                 1.1.0            py37he774522_0
fastrlock                 0.4              py37h6538335_0
filelock                  3.0.12                     py_0
flake8                    3.7.9                    py37_0
flask                     1.1.1                      py_0
freetype                  2.9.1                ha9979f8_1
fsspec                    0.6.2                      py_0
future                    0.18.2                   py37_0
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.4.0            py37he774522_0
glob2                     0.7                        py_0
greenlet                  0.4.15           py37hfa6e2cd_0
h5py                      2.9.0            py37h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
heapdict                  1.0.1                      py_0
html5lib                  1.0.1                    py37_0
hypothesis                4.54.2                   py37_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py37_0
imageio                   2.6.1                    py37_0
imagesize                 1.2.0                      py_0
importlib_metadata        1.3.0                    py37_0
intel-openmp              2019.4                      245
intervaltree              3.0.2                      py_0
ipykernel                 5.1.3            py37h39e3cac_0
ipython                   7.11.1           py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.5.1                      py_0
isort                     4.3.21                   py37_0
itsdangerous              1.1.0                    py37_0
jdcal                     1.4.1                      py_0
jedi                      0.14.1                   py37_0
jinja2                    2.10.3                     py_0
joblib                    0.14.1                     py_0
jpeg                      9b                   hb83a4c4_2
json5                     0.8.5                      py_0
jsonschema                3.2.0                    py37_0
jupyter                   1.0.0                    py37_7
jupyter_client            5.3.4                    py37_0
jupyter_console           6.0.0                    py37_0
jupyter_core              4.6.1                    py37_0
jupyterlab                1.2.4              pyhf63ae98_0
jupyterlab_server         1.0.6                      py_0
keyring                   20.0.0                   py37_0
kiwisolver                1.1.0            py37ha925a31_0
krb5                      1.16.4               hc04afaa_0
lazy-object-proxy         1.4.3            py37he774522_0
libarchive                3.3.3                h0643e63_5
libcurl                   7.67.0               h2a8f88b_0
libiconv                  1.15                 h1df5818_7
liblief                   0.9.0                ha925a31_2
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.16               h9d3ae62_0
libspatialindex           1.9.3                h33f27b4_0
libssh2                   1.8.2                h7a1dbc1_0
libtiff                   4.1.0                h56a325e_0
libxml2                   2.9.9                h464c3ec_0
libxslt                   1.1.33               h579f668_0
line_profiler             2.1.2            py37hfa6e2cd_0
llvmlite                  0.30.0           py37ha925a31_0
locket                    0.2.0                    py37_1
lxml                      4.4.2            py37h1350720_0
lz4-c                     1.8.1.2              h2fa13f4_0
lzo                       2.10                 h6df0209_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py37he774522_0
matplotlib                3.1.1            py37hc8f65d3_0
mccabe                    0.6.1                    py37_1
menuinst                  1.4.16           py37he774522_0
mistune                   0.8.4            py37he774522_0
mkl                       2019.4                      245
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.0.15           py37h14836fe_0
mkl_random                1.1.0            py37h675688f_0
mock                      3.0.5                    py37_0
more-itertools            8.0.2                      py_0
mpmath                    1.1.0                    py37_0
msgpack-python            0.6.1            py37h74a9793_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py37_0
navigator-updater         0.2.1                    py37_0
nbconvert                 5.6.1                    py37_0
nbformat                  4.4.0                    py37_0
networkx                  2.4                        py_0
nltk                      3.4.5                    py37_0
nose                      1.3.7                    py37_2
notebook                  6.0.2                    py37_0
numba                     0.46.0           py37hf9181ef_0
numexpr                   2.7.0            py37hdce8814_0
numpy                     1.17.4           py37h4320e6b_0
numpy-base                1.17.4           py37hc3f5095_0
numpydoc                  0.9.2                      py_0
nvidia-ml-py3             7.352.0                  pypi_0    pypi
olefile                   0.46                     py37_0
openpyxl                  3.0.2                      py_0
openssl                   1.1.1d               he774522_3
packaging                 20.0                       py_0
pandas                    0.25.3           py37ha925a31_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
paramiko                  2.6.0                    py37_0
parso                     0.5.2                      py_0
partd                     1.1.0                      py_0
path                      13.1.0                   py37_0
path.py                   12.4.0                        0
pathlib2                  2.3.5                    py37_0
pathtools                 0.1.2                      py_1
patsy                     0.5.1                    py37_0
pep8                      1.7.1                    py37_0
pexpect                   4.7.0                    py37_0
pickleshare               0.7.5                    py37_0
pillow                    7.0.0            py37hcc1f983_0
pip                       19.3.1                   py37_0
pkginfo                   1.5.0.1                  py37_0
pluggy                    0.13.1                   py37_0
ply                       3.11                     py37_0
powershell_shortcut       0.0.1                         2
prometheus_client         0.7.1                      py_0
prompt_toolkit            2.0.9                    py37_0
psutil                    5.6.7            py37he774522_0
py                        1.8.1                      py_0
py-lief                   0.9.0            py37ha925a31_2
pycodestyle               2.5.0                    py37_0
pycosat                   0.6.3            py37he774522_0
pycparser                 2.19                     py37_0
pycrypto                  2.6.1            py37hfa6e2cd_9
pycurl                    7.43.0.3         py37h7a1dbc1_0
pydocstyle                4.0.1                      py_0
pyflakes                  2.1.1                    py37_0
pygments                  2.5.2                      py_0
pylint                    2.4.4                    py37_0
pynacl                    1.3.0            py37h62dcd97_0
pyodbc                    4.0.27           py37ha925a31_0
pyopenssl                 19.1.0                   py37_0
pyparsing                 2.4.6                      py_0
pyqt                      5.9.2            py37h6538335_2
pyreadline                2.1                      py37_1
pyrsistent                0.15.6           py37he774522_0
pysocks                   1.7.1                    py37_0
pytables                  3.6.1            py37h1da0976_0
pytest                    5.3.2                    py37_0
pytest-arraydiff          0.3              py37h39e3cac_0
pytest-astropy            0.7.0                      py_0
pytest-astropy-header     0.1.1                      py_0
pytest-cov                2.8.1                      py_0
pytest-doctestplus        0.5.0                      py_0
pytest-openfiles          0.4.0                      py_0
pytest-remotedata         0.3.2                    py37_0
python                    3.7.4                h5263a28_0
python-dateutil           2.8.1                      py_0
python-jsonrpc-server     0.3.2                      py_0
python-language-server    0.31.2                   py37_0
python-libarchive-c       2.8                     py37_13
pytz                      2019.3                     py_0
pywavelets                1.1.1            py37he774522_0
pywin32                   227              py37he774522_0
pywin32-ctypes            0.2.0                    py37_0
pywinpty                  0.5.7                    py37_0
pyyaml                    5.2              py37he774522_0
pyzmq                     18.1.0           py37ha925a31_0
qdarkstyle                2.7                        py_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.6.0                      py_0
qtconsole                 4.6.0                      py_1
qtpy                      1.9.0                      py_0
requests                  2.22.0                   py37_1
rope                      0.14.0                     py_0
rtree                     0.8.3                    py37_0
ruamel_yaml               0.15.87          py37he774522_0
scikit-image              0.15.0           py37ha925a31_0
scikit-learn              0.22.1           py37h6288b17_0
scipy                     1.3.2            py37h29ff71c_0
seaborn                   0.9.0              pyh91ea838_1
send2trash                1.5.0                    py37_0
setuptools                44.0.0                   py37_0
simplegeneric             0.8.1                    py37_2
singledispatch            3.4.0.3                  py37_0
sip                       4.19.8           py37h6538335_0
six                       1.13.0                   py37_0
snappy                    1.1.7                h777316e_3
snowballstemmer           2.0.0                      py_0
sortedcollections         1.1.2                    py37_0
sortedcontainers          2.1.0                    py37_0
soupsieve                 1.9.5                    py37_0
sphinx                    2.3.1                      py_0
sphinxcontrib             1.0                      py37_1
sphinxcontrib-applehelp   1.0.1                      py_0
sphinxcontrib-devhelp     1.0.1                      py_0
sphinxcontrib-htmlhelp    1.0.2                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.2                      py_0
sphinxcontrib-serializinghtml 1.1.3                      py_0
sphinxcontrib-websupport  1.1.2                      py_0
spyder                    4.0.1                    py37_0
spyder-kernels            1.8.1                    py37_0
spyder-line-profiler      0.2.0                      py_0    spyder-ide
sqlalchemy                1.3.12           py37he774522_0
sqlite                    3.30.1               he774522_0
statsmodels               0.10.1           py37h8c2d366_0
sympy                     1.5                      py37_0
tbb                       2019.4               h74a9793_0
tblib                     1.6.0                      py_0
terminado                 0.8.3                    py37_0
testpath                  0.4.4                      py_0
tk                        8.6.8                hfa6e2cd_0
toolz                     0.10.0                     py_0
tornado                   6.0.3            py37he774522_0
tqdm                      4.40.2                     py_0
traitlets                 4.3.3                    py37_0
ujson                     1.35             py37hfa6e2cd_0
unicodecsv                0.14.1                   py37_0
urllib3                   1.25.7                   py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
watchdog                  0.9.0                    py37_1
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
werkzeug                  0.16.0                     py_0
wheel                     0.33.6                   py37_0
widgetsnbextension        3.5.1                    py37_0
win_inet_pton             1.1.0                    py37_0
win_unicode_console       0.5                      py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.11.2           py37he774522_0
xlrd                      1.2.0                    py37_0
xlsxwriter                1.2.7                      py_0
xlwings                   0.16.3                   py37_0
xlwt                      1.3.0                    py37_0
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
yapf                      0.28.0                     py_0
zeromq                    4.3.1                h33f27b4_3
zict                      1.0.0                      py_0
zipp                      0.6.0                      py_0
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0
```

~/.condarc is:

```
channels:
  - defaults
  - spyder-ide
  - conda-forge
channel_priority: strict
```
</details>

in case that screwed something up

**Comment by ccordoba12** [comment]
Ok, it seems the problem is caused by the `use_colors` option, defined in the spyder-line-profiler plugin:

https://github.com/spyder-ide/spyder-line-profiler/blob/b5f58942a965fe976c8adb182fed7d2322de9534/spyder_line_profiler/lineprofiler.py#L37-L39

@endolith, you would have saved us a lot of time if you had mentioned before that you are using that plugin. For next time, please mention all external plugins you have installed.

@jitseniesen, could you take a look at this problem?

**Comment by ccordoba12** [comment]
Thanks for testing @dalthviz! I'm moving this issue to our line-profiler plugin because it needs to be solved there.
