### ISSUE TITLE
Spyder Does Not Launch After Updating Anaconda Packages 4.0.1

### ISSUE THREAD

**Issue by mrzaidan00** [spyder-ide/spyder#11278]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

cannot laund spyder , when i installing the new version of anaconda and spyder using command conda update anaconda and conda update spyder, i got an error then i cant launch spyder
#PS = this is my first time using anaconda , please be gentle if i cant understand quickly

### What steps reproduce the problem?

1. conda update anaconda
2. conda update spyder
3. 

### What is the expected output? What do you see instead?
Spyder can launch

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE
<!--- Traceback (most recent call last):
File "D:\anaconda\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "D:\anaconda\lib\site-packages\spyder\app\start.py", line 201, in main
from spyder.app import mainwindow
File "D:\anaconda\lib\site-packages\spyder\app\mainwindow.py", line 167, in 
from spyder.utils.environ import WinUserEnvDialog
File "D:\anaconda\lib\site-packages\spyder\utils\environ.py", line 19, in 
from spyder.plugins.variableexplorer.widgets.collectionseditor import (
File "D:\anaconda\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 57, in 
from spyder.plugins.variableexplorer.widgets.collectionsdelegate import (
File "D:\anaconda\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionsdelegate.py", line 31, in 
from spyder.plugins.variableexplorer.widgets.objectexplorer.attribute_model \
File "D:\anaconda\lib\site-packages\spyder\plugins\variableexplorer\widgets\objectexplorer\__init__.py", line 19, in 
from .attribute_model import DEFAULT_ATTR_COLS, DEFAULT_ATTR_DETAILS
File "D:\anaconda\lib\site-packages\spyder\plugins\variableexplorer\widgets\objectexplorer\attribute_model.py", line 29, in 
import numpy as np
File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 142, in 
from . import core
File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\numpy\core\__init__.py", line 23, in 
WinDLL(os.path.abspath(filename))
File "D:\anaconda\lib\ctypes\__init__.py", line 364, in __init__
self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
Copy from error dialog or View > Panes > Internal Console --->

```

## Versions

* Spyder version: 4.01
* Python version: 3.8
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

(N/A) spyder does not launch
```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Please remove this directory

    C:\Users\lenovo\AppData\Roaming\Python\Python37

and **do not** install again with pip packages that can be installed with conda. In this case it's clear from your error that you installed Numpy with pip and that's what's causing this error.

**Comment by mrzaidan00** [comment]
ok thanks for your answer sir , its work right now

#sorry for late answer
