### ISSUE TITLE
An error occured while starting the Kernel

### ISSUE THREAD

**Issue by arun1997** [spyder-ide/spyder#11292]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
An error ocurred while starting the kernel
The error is:

Traceback (most recent call last):
File "C:\Users\arunsrinivasan\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole\plugin.py", line 1173, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle, **kwargs)
File "C:\Users\arunsrinivasan\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\Users\arunsrinivasan\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 476, in write_connection_file
kernel_name=self.kernel_name
File "C:\Users\arunsrinivasan\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 141, in write_connection_file
with secure_write(fname) as f:
File "C:\Users\arunsrinivasan\Anaconda3\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "C:\Users\arunsrinivasan\Anaconda3\lib\site‑packages\jupyter_core\paths.py", line 424, in secure_write
win32_restrict_file_to_user(fname)
File "C:\Users\arunsrinivasan\Anaconda3\lib\site‑packages\jupyter_core\paths.py", line 359, in win32_restrict_file_to_user
import win32api
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by ccordoba12** [comment]
Please open the Anaconda Prompt and run there:

    conda update anaconda
    conda update jupyter_client

to fix this error.
