### ISSUE TITLE
Kernal is not loading

### ISSUE THREAD

**Issue by arshadblouch81** [spyder-ide/spyder#11299]
### What steps will reproduce the problem?

return CONF.get(self.CONF_SECTION, option, default)
  File "C:\Users\dell\Anaconda3\lib\site-packages\spyder\config\user.py", line 382, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'show_callable_attributes' in section: 'variable_explorer'
Traceback (most recent call last):
  File "C:\Users\dell\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

### Traceback
```python-traceback
  File "C:\Users\dell\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1178, in <lambda>
    kc.started_channels.connect(lambda c=client: self.process_started(c))
  File "C:\Users\dell\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1753, in process_started
    self.variableexplorer.add_shellwidget(client.shellwidget)
  File "C:\Users\dell\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer.py", line 171, in add_shellwidget
    nsb.setup(**self.get_settings())
  File "C:\Users\dell\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer.py", line 107, in get_settings
    settings[name] = self.get_option(name)
  File "C:\Users\dell\Anaconda3\lib\site-packages\spyder\api\plugins.py", line 177, in get_option
    return CONF.get(self.CONF_SECTION, option, default)
  File "C:\Users\dell\Anaconda3\lib\site-packages\spyder\config\user.py", line 382, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'show_callable_attributes' in section: 'variable_explorer'
Traceback (most recent call last):
  File "C:\Users\dell\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

```

## Versions

* Spyder version: 4.0.0b1 
* Python version: 3.6.9
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.5.2 (OK)
sphinx >=0.6.6    :  2.3.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.11.0     :  0.14.1 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
pandas >=0.13.1   :  0.25.3 (OK)
numpy >=1.7       :  1.17.4 (OK)
sympy >=0.7.3     :  1.5 (OK)
cython >=0.21     :  0.29.14 (OK)
qtconsole >=4.2.0 :  4.6.0 (OK)
IPython >=4.0     :  7.11.1 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.4 (OK)
```

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=4.0.1
