### ISSUE TITLE
IPython console doesnt start on EPD/Lion

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1129]
_From [Kyle.J.K...@gmail.com](https://code.google.com/u/114477368280662714168/) on 2012-08-06T13:55:53Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. Grab the current spyder source
2. Start Spyder in bootstrap with pyside What is the expected output? What do you see instead? An IPython console should start, but instead the following is shown:

Python 2.7.3 |EPD 7.3-2 (64-bit)| (default, Apr 12 2012, 11:14:05) 
[GCC 4.0.1 (Apple Inc. build 5493)] on darwin
Builtin Modules: spy.app, spy.window

\>>> 
\>>> 
\>>> 
\>>> 
\>>> Traceback (most recent call last):
  File "/Users/kyon/repos/spyderlib/spyderlib/plugins/externalconsole.py", line 820, in \<lambda>
    cf, kernel_widget=shellwidget))
  File "/Users/kyon/repos/spyderlib/spyderlib/plugins/externalconsole.py", line 882, in create_ipython_client
    self.main.ipyconsole.new_client(connection_file, id(kernel_widget))
  File "/Users/kyon/repos/spyderlib/spyderlib/plugins/ipythonconsole.py", line 659, in new_client
    self.register_client(cf, kernel_widget_id, client_name)
  File "/Users/kyon/repos/spyderlib/spyderlib/plugins/ipythonconsole.py", line 717, in register_client
    config=self.client_config())
  File "/Users/kyon/repos/spyderlib/spyderlib/widgets/ipython.py", line 226, in create_new_client
    widget = SpyderIPythonWidget(config=config, local_kernel=False)
  File "/Users/kyon/repos/spyderlib/spyderlib/widgets/ipython.py", line 67, in __init__
    RichIPythonWidget.__init__(self, *args, **kw)
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/IPython/frontend/qt/console/rich_ipython_widget.py", line 31, in __init__
    super(RichIPythonWidget, self).__init__(*args, **kw)
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/IPython/frontend/qt/console/ipython_widget.py", line 116, in __init__
    super(IPythonWidget, self).__init__(*args, **kw)
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/IPython/frontend/qt/console/frontend_widget.py", line 123, in __init__
    super(FrontendWidget, self).__init__(*args, **kw)
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/IPython/frontend/qt/console/history_console_widget.py", line 26, in __init__
    super(HistoryConsoleWidget, self).__init__(*args, **kw)
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/IPython/frontend/qt/console/console_widget.py", line 176, in __init__
    QtGui.QWidget.__init__(self, parent)
RuntimeError: You can't initialize an object twice! What version of the product are you using? On what operating system? tip (d823b3e6bfa3), Lion, EPD default install 

Please provide any additional information below

. console starts successfully if you comment out RichIPythonWidget.__init__(self, *args, **kw) in spyderlib/widgets/ipython.py. Patch is attached.

**Attachment:** [epd_lion.diff](http://code.google.com/p/spyderlib/issues/detail?id=1129)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1129_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-11-04T03:09:50Z_

This issue was updated by revision a1f9c5a0e1fc .

**Status:** Fixed
