### ISSUE TITLE
"error: unpack requires a string argument of length 4" when executing python in a subprocess

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#113]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2009-11-09T10:00:10Z_

This issue is fixed in mercurial repository: https://code.google.com/p/spyderlib/source/detail?r=44dea5560bb10098bccf75d1b222613ba288d4ce

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=113_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2009-11-09T07:03:30Z_

issue #108 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-11T07:09:14Z_

This issue was updated by revision 6d1880bea68a .


For an unknown reason (would require some research in hg history to found out
why exactly), I've commented out the part of sitecustomize which was restoring
the original  PYTHONPATH environment variable (see revision 44dea5560bb1 ).
This can't be good as it was part of this fix... and suddenly some similar bugs
are being reported ( issue #941 , issue #931 ).

I'm uncommenting this block to restore this fix.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-11T07:09:14Z_

This issue was updated by revision 311614c74f6c .


For an unknown reason (would require some research in hg history to found out
why exactly), I've commented out the part of sitecustomize which was restoring
the original  PYTHONPATH environment variable (see revision 44dea5560bb1 ).
This can't be good as it was part of this fix... and suddenly some similar bugs
are being reported ( issue #941 , issue #931 ).

I'm uncommenting this block to restore this fix.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-11T07:09:37Z_

issue #941 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-11T07:09:48Z_

issue #931 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-03-14T11:27:47Z_

Still doesn't work for me when executed from checkout:

Executing Spyder from source checkout Revision 1920 :6d1880bea68a, Branch: default
...
03. Imported Spyder 2.2.0dev (Qt 4.8.0 via PyQt4 (API v1) 4.8.6)
...

Traceback (most recent call last):
  File "/p/spyderlib/spyderlib/spyder.py", line 1101, in plugin_focus_changed
    self.variableexplorer.set_shellwidget(shell)
  File "/p/spyderlib/spyderlib/plugins/variableexplorer.py", line 140, in set_shellwidget
    nsb.visibility_changed(True)
  File "/p/spyderlib/spyderlib/widgets/externalshell/namespacebrowser.py", line 256, in visibility_changed
    self.refresh_table()
  File "/p/spyderlib/spyderlib/widgets/externalshell/namespacebrowser.py", line 315, in refresh_table
    communicate(sock, "refresh()")
  File "/p/spyderlib/spyderlib/utils/bsdsocket.py", line 67, in communicate
    return read_packet(sock)
  File "/p/spyderlib/spyderlib/utils/bsdsocket.py", line 36, in read_packet
    dlen, = struct.unpack("l", datalen)
struct.error: unpack requires a string argument of length 4

**Status:** New

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2012-07-02T14:13:17Z_

I have the same kind of error with Spoyder 2.1.9 :

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/introspection.py", line 65, in run
    self.send_socket(shell_id, conn)
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/introspection.py", line 49, in send_socket
    shell.set_introspection_socket(sock)
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/pythonshell.py", line 246, in set_introspection_socket
    'set_remote_view_settings()', settings=[settings])
  File "/usr/lib/python2.7/dist-packages/spyderlib/utils/bsdsocket.py", line 67, in communicate
    return read_packet(sock)
  File "/usr/lib/python2.7/dist-packages/spyderlib/utils/bsdsocket.py", line 36, in read_packet
    dlen, = struct.unpack("l", datalen)
error: unpack requires a string argument of length 8

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-07-22T16:02:25Z_

There is a patch on issue #1106 , comment `#5`, could you try to apply it to see if it fixed your problem?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-23T12:55:20Z_

**Status:** Duplicate  
  **Mergedinto:** 1106
