### ISSUE TITLE
Spyder doesn't start

### ISSUE THREAD

**Issue by andrey4477** [spyder-ide/spyder#11311]
C:\WINDOWS\system32>C:\Python37\Lib\site-packages\spyder\app\mainwindow.py
Traceback (most recent call last):
  File "C:\Python37\Lib\site-packages\spyder\app\mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Python37\Lib\site-packages\spyder\app\mainwindow.py", line 3559, in run_spyder
    main.setup()
  File "C:\Python37\Lib\site-packages\spyder\app\mainwindow.py", line 1010, in setup
    from spyder.plugins.ipythonconsole.plugin import IPythonConsole
  File "C:\Python37\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 24, in <module>
    from jupyter_client.connect import find_connection_file
  File "C:\Python37\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Python37\lib\site-packages\jupyter_client\connect.py", line 35, in <module>
    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
ImportError: cannot import name 'secure_write' from 'jupyter_core.paths' (C:\Python37\lib\site-packages\jupyter_core\paths.py)

C:\WINDOWS\system32>

**Comment by ccordoba12** [comment]
Please open the Anaconda Prompt and run there

    conda update anaconda
    conda update jupyter_client

**Comment by vardhan-333** [comment]
I have a similar problem

Traceback (most recent call last):
File "D:\anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3718, in main
mainwindow = run_spyder(app, options, args)
File "D:\anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3559, in run_spyder
main.setup()
File "D:\anaconda\lib\site-packages\spyder\app\mainwindow.py", line 1277, in setup
self.apply_shortcuts()
File "D:\anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3189, in apply_shortcuts
plugin_name))
File "D:\anaconda\lib\site-packages\spyder\config\manager.py", line 305, in get_shortcut
return config.get('shortcuts', context + '/' + name.lower())
File "D:\anaconda\lib\site-packages\spyder\config\user.py", line 976, in get
return config.get(section=section, option=option, default=default)
File "D:\anaconda\lib\site-packages\spyder\config\user.py", line 513, in get
raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'find_replace/find next' in section: 'shortcuts'
