### ISSUE TITLE
Filename auto-complete collides with dot auto-complete

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1131]
_From [patrick....@gmail.com](https://code.google.com/u/116784098090120188806/) on 2012-08-07T19:21:36Z_

Spyder Version:  2.1.9
Python Version:  2.7.2
Qt Version:      4.7.4, PyQt4 (API v1) 4.8.6 on Windows

Apparently Spyder includes file name auto-completion and although I can't get it to work properly this moment (in Editor or Console), I do recall seeing file names suggested in the past. Oddly enough, lines 1039 & 927 of file "...\Python27\lib\site-packages\spyderlib\widgets\shell.py" indicate a NotImplementedError exception should be raised in any attempt to use this feature but that's never happened yet... maybe it's caught elsewhere?

But I digress... the focus of this Issue report is what happens when Spyder tries to auto-complete based on a period (dot, full stop) following a single-quotation mark. 

What steps will reproduce the problem?

 1. In Spyder, open an interpreter or IPython interpreter
2. Import the os module
3. Type os.listdir(' or os.listdir("
4. Type a period and the Internal console should immediately throw this trace back:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\widgets\shell.py", line 300, in keyPressEvent
    self.postprocess_keyevent(event)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\shell.py", line 795, in postprocess_keyevent
    ShellBaseWidget.postprocess_keyevent(self, event)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\shell.py", line 438, in postprocess_keyevent
    self._key_period(text)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\shell.py", line 890, in _key_period
    self.show_code_completion(automatic=True)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\shell.py", line 1041, in show_code_completion
    automatic=automatic)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\sourcecode\base.py", line 1071, in show_completion_list
    if len(completions) == 0 or completions == [completion_text]:
TypeError: object of type 'NoneType' has no len() What is the expected output? What do you see instead? I didn't expect any 'output' at all. Perhaps it should display an auto-complete list but in this case, what would be on the list? How can you auto-complete the "current directory" symbol?

I'm not very proficient yet but looking over shell.py, it seems like the last trace back should never be reached because executing line 1039 of shell.py would raise a NotImplementedError. So odd.

As far as fixing this? How about checking for file names (by looking for ' or ") earlier on? Or just being explicit about no unmatched quotes preceding the dot that is being auto-completed around? 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1131_

**Comment by spyder-issues-migrator** [comment]
_From [patrick....@gmail.com](https://code.google.com/u/116784098090120188806/) on 2012-08-07T17:28:06Z_

I was able to replicate the error message with a (nearly) identical trace back by typing the command below in a Spyder console interpreter. In fact, any module name will do here - it's the period that causes the error.

import glob.

The trace back:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\widgets\shell.py", line 300, in keyPressEvent
    self.postprocess_keyevent(event)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\shell.py", line 795, in postprocess_keyevent
    ShellBaseWidget.postprocess_keyevent(self, event)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\shell.py", line 438, in postprocess_keyevent
    self._key_period(text)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\shell.py", line 890, in _key_period
    self.show_code_completion(automatic=True)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\shell.py", line 961, in show_code_completion
    automatic=automatic)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\sourcecode\base.py", line 1071, in show_completion_list
    if len(completions) == 0 or completions == [completion_text]:
TypeError: object of type 'NoneType' has no len()

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-08-08T04:36:02Z_

Regarding the methods raising a NotImplementedError exception, they are all reimplemented in children classes (the widget described by the class in shell.py is only the base class). 

As for the issue itself, I can't help much right now because I'm on vacation without any computer around: someone else will have to take action on this or it will wait until a week. 

In the meantime, you may try to upgrade to v2.1.11, the latest stable release, in case this bug has already been taken care of.

**Labels:** -Priority-Medium Priority-Critical Cat-Console MS-v2.1

**Comment by spyder-issues-migrator** [comment]
_From [ghisv...@gmail.com](https://code.google.com/u/103124226509116879823/) on 2012-08-24T12:33:51Z_

I can't reproduce the traceback mentioned in the OP, neither with os.listdir( nor with glob. .

For os.listdir(". -> autocompletion lists the content of my home folder. I have attached a screenshot. Running Spyder 2.1.9 on Ubuntu 12.04.

**Attachment:** [spyder_autocompletion.png](http://code.google.com/p/spyderlib/issues/detail?id=1131#hc5)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-01-27T01:44:42Z_

**Labels:** -MS-v2.1 MS-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-11T08:56:56Z_

**Labels:** -MS-v2.2 MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [wsu...@gmail.com](https://code.google.com/u/115225145614373588440/) on 2013-11-07T12:03:34Z_

This appears to have been fixed at some point. It is not an issue with Spyder 2.2.3 on WinXP64 at least.

**Comment by spyder-issues-migrator** [comment]
_From [stonebi...@gmail.com](https://code.google.com/u/116068254323340012360/) on 2013-12-12T10:32:17Z_

I don't reproduce it either. shouldn't it be closed ?

*** example ****
Python 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

Imported NumPy 1.7.1, SciPy 0.12.0, Matplotlib 1.3.0
+ guidata 1.6.1, guiqwt 2.3.1
Type "scientific" for more details.
\>>> import os
\>>> os.listdir(".
  File "<stdin>", line 1
    os.listdir(".
                ^
SyntaxError: EOL while scanning string literal
\>>>

**Comment by spyder-issues-migrator** [comment]
_From [wsu...@gmail.com](https://code.google.com/u/115225145614373588440/) on 2013-12-17T16:44:05Z_

Yes, this should probably be closed as fixed or not reproducible. The google account of the OP has been permanently deleted though so don't rely on OP to close it.

**Comment by spyder-issues-migrator** [comment]
_From [wsu...@gmail.com](https://code.google.com/u/115225145614373588440/) on 2014-01-14T11:54:24Z_

pierre, this issue was resolved at some point as the behavior is no longer reproducible. I have first-hand knowledge the OP closed their gmail account. Could you mark this issue closed?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-04T14:58:38Z_

Thanks for reporting, since it's not reproducible anymore I'm closing it.

**Status:** WontFix  
  **Labels:** -MS-v2.3
