### ISSUE TITLE
Closing a multithreading programm raise ValueError

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#11330]
### What steps will reproduce the problem?

1 - Run a file with 
```
import time
import multiprocessing as mp

def a(i):
    print(i)
    time.sleep(10)


with mp.Pool() as p:
    p.map(a, range(30))
```
2 - Close the kernel before the programm finishes
3 - repeat 1 and 2 until the error raises

### Traceback
```python-traceback
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/threaded.py", line 93, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/session.py", line 941, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'05eb300dd8235702569ad66caacb197d324e1f4e101b029746a34ec6236fd592'
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/threaded.py", line 93, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/session.py", line 941, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'05eb300dd8235702569ad66caacb197d324e1f4e101b029746a34ec6236fd592'
ERROR:tornado.application:Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x13760b5f0>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 542, in <lambda>
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/threaded.py", line 93, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/session.py", line 941, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'05eb300dd8235702569ad66caacb197d324e1f4e101b029746a34ec6236fd592'
```

## Versions

* Spyder version: 4.1.0.dev0 f5440f8a4
* Python version: 3.7.5
* Qt version: 5.12.6
* PyQt5 version: 5.12.3
* Operating System: Darwin 19.2.0

### Dependencies

```
applaunchservices >=0.1.7    :  0.2.1 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.10.2 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.5 (OK)
pygments >=2.0               :  2.4.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtconsole >=4.6.0            :  4.7.0.dev0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
sphinx >=0.6.6               :  2.2.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.9.0.dev0 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.14 (OK)
matplotlib >=2.0.0           :  3.1.2 (OK)
numpy >=1.7                  :  1.17.4 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
scipy >=0.17.0               :  1.3.3 (OK)
sympy >=0.7.3                :  1.4 (OK)
```

**Comment by ccordoba12** [comment]
I think this needs to be solved in spyder-kernels.

**Comment by ccordoba12** [comment]
@impact27, is this still a problem?

**Comment by impact27** [comment]
Can't reproduce
