### ISSUE TITLE
Spyder on opening shows an error on starting the kernel

### ISSUE THREAD

**Issue by surbhisinha2811** [spyder-ide/spyder#11340]
An error ocurred while starting the kernel
The error is:

Traceback (most recent call last):
File "C:\Users\Surbhi\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\Surbhi\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\Users\Surbhi\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "C:\Users\Surbhi\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "C:\Users\Surbhi\Anaconda3\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "C:\Users\Surbhi\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 102, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Surbhi\\AppData\\Roaming\\jupyter\\runtime\\kernel‑ca4706fc2c1d.json'

**Comment by ccordoba12** [comment]
To fix this you need to open the Anaconda Prompt and run there

    conda update anaconda
    conda update jupyter_client
