### ISSUE TITLE
The get() and and insert() method aren't working when using Tkinter in Spyder, yet it worked in other codes I made in past not using Tkinter

### ISSUE THREAD

**Issue by LrdKgb** [spyder-ide/spyder#11388]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The get() and and insert() method aren't working when using Tkinter in Spyder. I get the following error:
AttributeError: 'NoneType' object has no attribute 'insert'

### What steps reproduce the problem?

```python
from tkinter import *

root= Tk()
e = Entry(root, borderwidth=5).grid(row=2,column=0)
#e.insert(0, "Enter Amount")
def clickbutton():
    response= e.get()
    mylabel4 = Label(root, text=response).grid(row=3,column=1)
    
    

mylabel1 = Label(root, text="The GUI")
mylabel3 = Label(root, text="         ").grid(row=1,column=1)
mylabel2 = Label(root, text="It Works").grid(row=1,column=2)

MyButton = Button(root, text="Amount", state="active", command=clickbutton, bg="orange", fg="blue", padx=30).grid(row=1,column=0)

#mylabel1.pack() #to keep things centered can't grid and pack at the same time
mylabel1.grid(row=0,column=0)
#mylabel2.grid(row=1,column=2)

root.mainloop()
```

### What is the expected output? What do you see instead?

insert text in output box
Print out the value entered in output box

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE
runfile('C:/Users/admin/Downloads/Gui Tutorial.py', wdir='C:/Users/admin/Downloads')
Traceback (most recent call last):

  File "C:\Users\admin\Downloads\Gui Tutorial.py", line 5, in <module>
    e.insert(0, "Enter Amount")

AttributeError: 'NoneType' object has no attribute 'insert'


runfile('C:/Users/admin/Downloads/Gui Tutorial.py', wdir='C:/Users/admin/Downloads')
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\admin\Downloads\Gui Tutorial.py", line 7, in clickbutton
    response= e.get()
AttributeError: 'NoneType' object has no attribute 'get'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\admin\Downloads\Gui Tutorial.py", line 7, in clickbutton
    response= e.get()
AttributeError: 'NoneType' object has no attribute 'get'
```

## Versions

* Spyder version: latest
* Python version: latest
* Qt version: 
* PyQt version: 
* Operating System name/version: windows 10 pro

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.11.1 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
zmq >=17                     :  18.1.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
sphinx >=0.6.6               :  2.3.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.14 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
sympy >=0.7.3                :  1.5.1 (OK)

```

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.

**Comment by LrdKgb** [comment]
I've managed to solve this issue I thought it had something to do with the Spyder update I just did. It had something to do with another code that was in a different format. You may delete this thread. On that note the new version isn't as fast as it was even when tide is off. Thanks
