### ISSUE TITLE
spyder keeps crashing

### ISSUE THREAD

**Issue by howdyDp** [spyder-ide/spyder#11392]
Traceback (most recent call last):
File "E:\python\lib\site-packages\spyder\app\mainwindow.py", line 3285, in main
mainwindow = run_spyder(app, options, args)
File "E:\python\lib\site-packages\spyder\app\mainwindow.py", line 3140, in run_spyder
main.setup()
File "E:\python\lib\site-packages\spyder\app\mainwindow.py", line 832, in setup
self.help = Help(self)
File "E:\python\lib\site-packages\spyder\plugins\help.py", line 468, in __init__
html_text_no_doc=warning(self.no_doc_string))
File "E:\python\lib\site-packages\spyder\utils\help\sphinxify.py", line 76, in warning
warning = env.get_template("warning.html")
File "E:\python\lib\site-packages\jinja2\environment.py", line 830, in get_template
return self._load_template(name, self.make_globals(globals))
File "E:\python\lib\site-packages\jinja2\environment.py", line 804, in _load_template
template = self.loader.load(self, name, globals)
File "E:\python\lib\site-packages\jinja2\loaders.py", line 113, in load
source, filename, uptodate = self.get_source(environment, name)
File "E:\python\lib\site-packages\jinja2\loaders.py", line 175, in get_source
contents = f.read().decode(self.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 216135: invalid start byte

this is the error that is shown , please

**Comment by ccordoba12** [comment]
Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.
