### ISSUE TITLE
Spyder 4.01 hangs at "loading main screen"

### ISSUE THREAD

**Issue by jfprieur** [spyder-ide/spyder#11390]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder 4.0.1 never starts, hangs at "loading main screen" (translating from french so unsure if exact)

### What steps reproduce the problem?

1. Start Spyder
2. 
3. 

### What is the expected output? What do you see instead?

Spyder starts

### Paste Traceback/Error Below (if applicable)
Ran `spyder --debug-info verbose`

Output:

```
2020-01-22 16:50:54,433 [INFO] [spyder.app.mainwindow] -> Configuration de la fenêtre principale...
2020-01-22 16:50:54,508 [INFO] [spyder.app.mainwindow] -> Setting up window...
2020-01-22 16:50:54,527 [DEBUG] [traitlets] -> Using default logger
2020-01-22 16:50:54,669 [DEBUG] [traitlets] -> Starting kernel: ['D:\\Miniconda3\\envs\\geopandas\\pythonw.exe', '-m', 'spyder_kernels.console', '-f', 'C:\\Users\\bc591114\\AppData\\Roaming\\jupyter\\runtime\\kernel-95f95c349849.json']
2020-01-22 16:50:54,697 [DEBUG] [traitlets] -> Connecting to: tcp://127.0.0.1:50170
2020-01-22 16:50:54,706 [DEBUG] [traitlets] -> connecting heartbeat channel to tcp://127.0.0.1:50171
2020-01-22 16:50:54,709 [DEBUG] [asyncio] -> Using proactor: IocpProactor
2020-01-22 16:50:54,710 [DEBUG] [asyncio] -> Using proactor: IocpProactor
2020-01-22 16:50:54,711 [DEBUG] [traitlets] -> connecting shell channel to tcp://127.0.0.1:50167
2020-01-22 16:50:54,711 [DEBUG] [traitlets] -> Connecting to: tcp://127.0.0.1:50167
2020-01-22 16:50:54,716 [ERROR] [tornado.application] -> Exception in callback functools.partial(<function ThreadedZMQSocketChannel.__init__.<locals>.setup_stream at 0x000002215722E3A0>)
Traceback (most recent call last):
  File "D:\Miniconda3\envs\geopandas\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "D:\Miniconda3\envs\geopandas\lib\site-packages\jupyter_client\threaded.py", line 48, in setup_stream
    self.stream = zmqstream.ZMQStream(self.socket, self.ioloop)
  File "D:\Miniconda3\envs\geopandas\lib\site-packages\zmq\eventloop\zmqstream.py", line 127, in __init__
    self._init_io_state()
  File "D:\Miniconda3\envs\geopandas\lib\site-packages\zmq\eventloop\zmqstream.py", line 546, in _init_io_state
    self.io_loop.add_handler(self.socket, self._handle_events, self.io_loop.READ)
  File "D:\Miniconda3\envs\geopandas\lib\site-packages\tornado\platform\asyncio.py", line 99, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "D:\Miniconda3\envs\geopandas\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError

```

## Versions
* Spyder version: 4.0.1
* Python version: 3.8.1
* Qt version: 5.12.5
* PyQt version: 5.12.3
* Operating System name/version: Win10 64-bit

### Dependencies
Fresh miniconda installed with conda-forge packages

Saw related issue that was closed  #7153 with Python 3.8 in common. Is it possibly because of the mismatch between qt and pyqt?

**Comment by ccordoba12** [comment]
> Python version: 3.8.1

It seems there are still issues between Tornado and Pyzmq (which is what your error shows). So for now please use Python 3.7
