### ISSUE TITLE
Error after updating spyder to verson 4.0.1

### ISSUE THREAD

**Issue by Psypher-x** [spyder-ide/spyder#11408]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```The term '{CONDA_ROOT_PREFIX}\\shell\\condabin\\conda-hook.ps1' is not recogniz
ed as the name of a cmdlet, function, script file, or operable program. Check t
he spelling of the name, or if a path was included, verify that the path is cor
rect and try again.
At line:1 char:2
+ & <<<<  '{CONDA_ROOT_PREFIX}\\shell\\condabin\\conda-hook.ps1' ; conda activa
te '{CONDA_PREFIX}'
    + CategoryInfo          : ObjectNotFound: ({CONDA_ROOT_PRE...\conda-hook.p
   s1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Could not find conda environment: {CONDA_PREFIX}
You can list all discoverable environments with `conda info --envs`.

PS C:\Users\Jai Shree Ram> spyder
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3711, in m
ain
    mainwindow = run_spyder(app, options, args)
  File "D:\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3552, in r
un_spyder
    main.setup()
  File "D:\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 1010, in s
etup
    from spyder.plugins.ipythonconsole.plugin import IPythonConsole
  File "D:\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py",
line 52, in <module>
    from spyder.plugins.ipythonconsole.widgets import ClientWidget
  File "D:\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\widgets\__in
it__.py", line 16, in <module>
    from .debugging import DebuggingWidget
  File "D:\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debu
gging.py", line 22, in <module>
    from IPython.core.inputtransformer2 import TransformerManager
ModuleNotFoundError: No module named 'IPython.core.inputtransformer2'

PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Please reinstall Anaconda because it seems it's broken, sorry.

**Comment by Rabijns** [comment]
I encountered the same issue today.
Spyder 4.0.1 worked fine for me.
I did `conda update spyder` to get 4.1.0
Now, I get the same error.< as the original poster.

`Traceback (most recent call last):
  File "/home/daan/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3705, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/daan/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3555, in run_spyder
    main.setup()
  File "/home/daan/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 935, in setup
    from spyder.plugins.ipythonconsole.plugin import IPythonConsole
  File "/home/daan/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 46, in <module>
    from spyder.plugins.ipythonconsole.widgets import (ClientWidget,
  File "/home/daan/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/widgets/__init__.py", line 16, in <module>
    from .debugging import DebuggingWidget
  File "/home/daan/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/widgets/debugging.py", line 22, in <module>
    from IPython.core.inputtransformer2 import TransformerManager
ModuleNotFoundError: No module named 'IPython.core.inputtransformer2'
`

I'll revert to 4.0.1 for the time being and follow your advice to reinstall anaconda when I have some spare time.
