### ISSUE TITLE
an error occured while starting kernel

### ISSUE THREAD

**Issue by Naman00** [spyder-ide/spyder#11402]
### What steps will reproduce the problem?

i updated spyder to 4.01 and after it was showing no module name numpy or pandas or any libraries then i downgrade it to 3.01 then its showing an error occured while starting kernel

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.5 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
Because the kernel versions are incompatible between Spyder 3 and 4. Please be sure you have spyder-kernels version 0.5.2 installed.

**Comment by Naman00** [comment]
thanks

**Comment by rahikalantari** [comment]
I have same issue  and my spyder-kernel is 0.5.2

An error ocurred while starting the kernel
Traceback (most recent call last):
File "/home/rahikalantari/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/home/rahikalantari/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/rahikalantari/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/home/rahikalantari/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 287, in main
import_spydercustomize()
File "/home/rahikalantari/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 39, in import_spydercustomize
import spydercustomize
File "/home/rahikalantari/anaconda3/lib/python3.7/site‑packages/spyder_kernels/customize/spydercustomize.py", line 19, in 
import pdb
File "/home/rahikalantari/anaconda3/lib/python3.7/pdb.py", line 76, in 
import code
File "/home/rahikalantari/code.py", line 36
parser.add_argument('‑‑log‑interval', type=int, default=10, metavar='N',
^
SyntaxError: invalid syntax

Spyder version: 3.3.6
Python version: 3.7.6
Qt version: 5.9.7
PyQt5 version: 5.9.2
Operating System: Ubuntu 18.04

can you please help ?

**Comment by Naman00** [comment]
try this
conda update --all

**Comment by rahikalantari** [comment]
Thanks for reply, just tried  still same error 
An error ocurred while starting the kernel
Traceback (most recent call last):
File "/home/rahikalantari/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/home/rahikalantari/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/rahikalantari/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/home/rahikalantari/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 287, in main
import_spydercustomize()
File "/home/rahikalantari/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 39, in import_spydercustomize
import spydercustomize
File "/home/rahikalantari/anaconda3/lib/python3.7/site‑packages/spyder_kernels/customize/spydercustomize.py", line 19, in 
import pdb
File "/home/rahikalantari/anaconda3/lib/python3.7/pdb.py", line 76, in 
import code
File "/home/rahikalantari/code.py", line 36
parser.add_argument('‑‑log‑interval', type=int, default=10, metavar='N',
^
SyntaxError: invalid syntax

**Comment by rahikalantari** [comment]
> Because the kernel versions are incompatible between Spyder 3 and 4. Please be sure you have spyder-kernels version 0.5.2 installed.
I have same issue and my spyder-kernel is 0.5.2
Spyder version: 3.3.6
Python version: 3.7.6
Qt version: 5.9.7
PyQt version: 5.9.2
Operating System: Ubuntu 18.04

can you please help ?
I reported the error above!

**Comment by ccordoba12** [comment]
Please remove or rename this file

    /home/rahikalantari/code.py

to fix this problem.

**Comment by rahikalantari** [comment]
Amazing, solved. Just it is amazing that does not cause issue in my python 2.7 spyder
Thanks

**Comment by sjswerdloff** [comment]
I realize this is closed, but I had a similar issue, and the resolution was to reset my python interpreter:
Tools-:>Preferences
Select the Python interpreter for all consoles (checkbox) default

I had the problem with spyder 3.3.6 (went through a lot of back and forth, including re-installing spyder-kernels=0.*), and then I figured with all that I might as well upgrade to Spyder 4.*.
Same problem.  

So for those for whom the various other solutions don't work, I suggest trying to reset your python interpreter as I described above.
