### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by stevenyucode** [spyder-ide/spyder#11401]
## Problem Description
After installing the Anaconda3 , open the Spyer then got the error under the right Console
"An error ocurred while starting the kernel"

### What steps reproduce the problem?

1. installing the Anaconda3
2. open the Spyer
3. got the error under the right Console

### Paste Traceback/Error Below (if applicable)
The error is:

Traceback (most recent call last):
File "C:\Users\Steven\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\Steven\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\Users\Steven\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "C:\Users\Steven\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "C:\Users\Steven\Anaconda3\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "C:\Users\Steven\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 102, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Steven\\AppData\\Roaming\\jupyter\\runtime\\kernel𔂪b9e02d798e0.json'

## Versions

* Spyder version: 3.3.6
* Python version: 3.7.464-bit
* Qt version: 
* PyQt version: 
* Operating System name/version: Win 10

**Comment by ccordoba12** [comment]
Please close Spyder, open the Anaconda prompt, run there

    conda update anaconda
    conda update jupyter_client

and then start Spyder again. That should fix your problem.
