### ISSUE TITLE
Editor changes cause .spyder.ini write fail

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1141]
_From [engn...@gmail.com](https://code.google.com/u/113571334767645783916/) on 2012-08-31T03:14:42Z_

Spyder Version:  2.1.11
Python Version:  2.7.2
Qt Version:      4.7.4, PyQt4 (API v1) 4.8.6 on Windows 

What steps will reproduce the problem?

 1. Changing the fontsize in Tools->Preferences->Editor
2. Hit apply button
3. If an error is printed in the internal console (the editor text does not change), hitting the apply button one more time usually works. What is the expected output? What do you see instead? Get the following traceback in internal console:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\plugins\configdialog.py", line 164, in button_clicked
    configpage.apply_changes()
  File "C:\Python27\lib\site-packages\spyderlib\plugins\configdialog.py", line 71, in apply_changes
    self.save_to_conf()
  File "C:\Python27\lib\site-packages\spyderlib\plugins\configdialog.py", line 309, in save_to_conf
    self.set_option(option, checkbox.isChecked())
  File "C:\Python27\lib\site-packages\spyderlib\plugins\__init__.py", line 210, in set_option
    CONF.set(self.CONF_SECTION, str(option), value)
  File "C:\Python27\lib\site-packages\spyderlib\userconfig.py", line 317, in set
    self.__save()
  File "C:\Python27\lib\site-packages\spyderlib\userconfig.py", line 161, in __save
    conf_file = file(self.filename(),'w')
IOError: [Errno 22] invalid mode ('w') or filename: u'C:\\Users\\lennart\\.spyder2\\.spyder.ini' 

Please provide any additional information below

. The bug was annoying before I discovered you can just hit apply button again to make it work. The bug seems to appear somewhat irregular, sometimes the change working immediately, sometimes it takes 4 or more tries before there is no error. I'm uncertain if there's a higher chance of success if pressing 'OK' instead of 'Apply'. The same problems applies to other settings on the Editor preferences page.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1141_

**Comment by spyder-issues-migrator** [comment]
_From [davidme...@gmail.com](https://code.google.com/u/110391091941809246391/) on 2013-04-26T10:58:49Z_

I'm also seeing a similar problem. I installed python(x,y) yesterday and was able to use it fine. Unfortunately I can't remember any changes I made that would have caused problems but now I am unable to launch spyder from the GUI. If I run the spyder.bat script I can see the error message:

C:\Python27\Scripts>spyder.bat
Traceback (most recent call last):
  File "C:\Python27\Scripts\spyder", line 2, in \<module>
    from spyderlib import spyder
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 96, in \<module>

    from spyderlib.utils.environ import WinUserEnvDialog
  File "C:\Python27\lib\site-packages\spyderlib\utils\environ.py", line 17, in \<
module>
    from spyderlib.widgets.dicteditor import DictEditor
  File "C:\Python27\lib\site-packages\spyderlib\widgets\dicteditor.py", line 31,
 in \<module>
    from spyderlib.config import get_icon, get_font
  File "C:\Python27\lib\site-packages\spyderlib\config.py", line 511, in \<module
\>
    set_default_color_scheme(_name, replace=False)
  File "C:\Python27\lib\site-packages\spyderlib\config.py", line 508, in set_def
ault_color_scheme
    set_color_scheme(name, COLORS[name], replace=replace)
  File "C:\Python27\lib\site-packages\spyderlib\config.py", line 503, in set_col
or_scheme
    CONF.set(section, "names", sorted(list(set(names))))
  File "C:\Python27\lib\site-packages\spyderlib\userconfig.py", line 317, in set

    self.__save()
  File "C:\Python27\lib\site-packages\spyderlib\userconfig.py", line 161, in __s
ave
    conf_file = file(self.filename(),'w')
IOError: [Errno 22] invalid mode ('w') or filename: u'C:\\Users\\David\\.spyder2
\\.spyder.ini'

Python(x,y): 2.7.3.1
Python: 2.7.3

If anyone can think of any workaround so that I can use spyder again that'd be great, at the moment I'm totally unable to use it! Thanks

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-04-26T11:48:38Z_

This issue should already be addressed by the solution to issue #1242 and is fixed in the current 2.2.0 release candidate that is available from the "Downloads" page. If you are willing to upgrade to 2.2.0rc you can get the solution that way. Or you can browse the code changes that were made to solve issue #1242 and apply them manually to your instance of userconfig.py if upgrading to 2.2 is not an option.

**Status:** Duplicate  
  **Mergedinto:** 1242

**Comment by spyder-issues-migrator** [comment]
_From [davidme...@gmail.com](https://code.google.com/u/110391091941809246391/) on 2013-04-26T12:55:45Z_

Thanks, the code change fixed the problem.
