### ISSUE TITLE
%autoreload fails (Spyder 4)

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#11420]
[demo](https://www.dropbox.com/s/1dhpbrm3nlxnakj/autoreload_demo.mp4?dl=0). Note how debugger shows the added line, even pointing to it as the source of failure - so `%autoreload` doesn't do nothing.

A rare occurrence, maybe the first for me - don't know how to reproduce, will share if found. 

<hr>

**Update**: reproduced immediately after reloading kernel - but still not 'reproduce-friendly'.

**Comment by impact27** [comment]
To reproduce:
1 - create file with
```
def fun():
    raise RuntimeError
```
run the file with F5 or the green arrow
in ipyconsole:
```
In [2]: fun()
Traceback (most recent call last):

  File "<ipython-input-2-d9f830ba61f1>", line 1, in <module>
    fun()

  File "/Users/quentinpeter/Desktop/tmp.py", line 2, in fun
    raise RuntimeError

RuntimeError
```
2 - Modify the file so it says:
```
def fun():
    print(0)
    raise RuntimeError
```
3 - save but don't run it
in ipyconsole:
```
In [4]: %autoreload

In [5]: fun()
Traceback (most recent call last):

  File "<ipython-input-5-d9f830ba61f1>", line 1, in <module>
    fun()

  File "/Users/quentinpeter/Desktop/tmp.py", line 2, in fun
    print(0)

RuntimeError
```

**Comment by impact27** [comment]
This is an ipython error, not a spyder one:
```
Python 3.7.5 (default, Nov  1 2019, 02:16:23) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.10.2 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %run /Users/quentinpeter/Desktop/tmp.py                                 

In [2]: fun()                                                                   
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-d9f830ba61f1> in <module>
----> 1 fun()

~/Desktop/tmp.py in fun()
      1 def fun():
----> 2     raise RuntimeError

RuntimeError: 

In [3]: # modify tmp.py                                                         

In [4]: fun()                                                                   
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-d9f830ba61f1> in <module>
----> 1 fun()

~/Desktop/tmp.py in fun()
      1 def fun():
----> 2     print(0)
      3     raise RuntimeError

RuntimeError: 

In [5]: %load_ext autoreload                                                    

In [6]: %autoreload 2                                                           

In [7]: fun()                                                                   
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-d9f830ba61f1> in <module>
----> 1 fun()

~/Desktop/tmp.py in fun()
      1 def fun():
----> 2     print(0)
      3     raise RuntimeError

RuntimeError: 

In [8]:    
```

**Comment by ccordoba12** [comment]
> This is an ipython error, not a spyder one:

Thanks @impact27 for taking a look at this one! Closing then.
