### ISSUE TITLE
Spyder Crash: Spyder crashed during last session & Errno 1

### ISSUE THREAD

**Issue by Arthur-PL** [spyder-ide/spyder#11458]
## Problem Description
Anaconda 1.9.7
Spyder 4.0.1

Hello, the problem is that I am unable to open Spyder from Anaconda Navigator. I browsed to solve the problem but I keep failing. Unfortunately, I don't understand why the command `spyder --reset` returns zsh: command not found : spyder. Nor for commands with `conda ` --> zsh: command not found: conda. I tried to copy the same commands recommended from similar posts but it remains a failure.

I tried to re-download both Anaconda and Spyder to the most recent version. I tried to copy the text "added by anaconda3" in the bash file to somewhere... but here I am clueless as to how to solve the problem.

If it helps Anaconda3 file is located at /Users/name/anaconda3

### What steps reproduce the problem?

1. I launch Anaconda Navigator
2. I launch Spyder
3. Error message: Spyder crashed during last session
4. I click Ok, and I get the application launch error message

### What is the expected output? What do you see instead?
I expect to have Spyder launched and opened to continue working. Instead Spyder keeps crashing.

### Paste Traceback/Error Below
'''
Traceback (most recent call last): 
File "/Users/Arthur.PL/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3718, in main mainwindow = run_spyder(app, options, args) 
File "/Users/Arthur.PL/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3559, in run_spyder main.setup() 
File "/Users/Arthur.PL/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 1056, in setup for mod in get_spyderplugins_mods(): 
File "/Users/Arthur.PL/anaconda3/lib/python3.7/site-packages/spyder/otherplugins.py", line 42, in get_spyderplugins_mods _get_spyderplugins(plugin_path, io, modnames, modlist) 
File "/Users/Arthur.PL/anaconda3/lib/python3.7/site-packages/spyder/otherplugins.py", line 51, in _get_spyderplugins for name in os.listdir(plugin_path): 
PermissionError: [Errno 1] Operation not permitted: '/Users/Arthur.PL/Desktop/2PY022 Calcul Scientifique & Modélisation' 
'''

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.4
* Qt version: 4.6.0
* Operating System name/version: macOS Catalina 10.15.2

### Dependencies
I don't know where they are. Which menu should I go to?

Thank you in advance for your help!

**Comment by ccordoba12** [comment]
This is a problem with macOS Catalina. Please read this

https://stackoverflow.com/questions/58372768/file-permissions-issue-with-python-spyder-anaconda-after-upgrading-mac-to-catali

to learn how to solve it.
