### ISSUE TITLE
Running scripts fails in 64 bit platform

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1146]
_From [mvi...@gmail.com](https://code.google.com/u/108668877517097490134/) on 2012-09-09T10:13:52Z_

What steps will reproduce the problem?

 1. Load any script.
2. Hit F5. What is the expected output? What do you see instead? This internal console output shows the error traceback:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/introspection.py", line 65, in run
    self.send_socket(shell_id, conn)
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/introspection.py", line 49, in send_socket
    shell.set_introspection_socket(sock)
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/pythonshell.py", line 246, in set_introspection_socket
    'set_remote_view_settings()', settings=[settings])
  File "/usr/lib/python2.7/dist-packages/spyderlib/utils/bsdsocket.py", line 67, in communicate
    return read_packet(sock)
  File "/usr/lib/python2.7/dist-packages/spyderlib/utils/bsdsocket.py", line 36, in read_packet
    dlen, = struct.unpack("l", datalen)
error: unpack requires a string argument of length 8 What version of the product are you using? On what operating system? Linux Mint on AMD64. 

Please provide any additional information below

. Apparently bsdsocket.py forgot to specify standard sizes for struct format strings (=). By default the struct module uses native sizes (@) when the size specifier is missing.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1146_

**Comment by spyder-issues-migrator** [comment]
_From [mvi...@gmail.com](https://code.google.com/u/108668877517097490134/) on 2012-09-09T08:17:05Z_

Now that I think of it, it's probably best to use network byte order instead (!).

**Comment by spyder-issues-migrator** [comment]
_From [mvi...@gmail.com](https://code.google.com/u/108668877517097490134/) on 2012-09-09T08:20:02Z_

I worked around it by using ! in all struct format strings of bsdsocket.py and it seems to be working so far. :)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-09-09T09:47:15Z_

Why '!' instead of '='?
(and do not hesitate to post a patch)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-09-09T09:53:03Z_

Also, please take a look at the patch I've posted for issue #1106 (comment `#10`).
This is exactly the same traceback (do not look at the very first traceback of issue #1106 , it's something else).

**Comment by spyder-issues-migrator** [comment]
_From [mvi...@gmail.com](https://code.google.com/u/108668877517097490134/) on 2012-09-09T14:08:44Z_

Oh, just in case the connection is made to another machine. As long as it connects to localhost it's all the same, but since we're at it... :)

I'm not sure this is exactly the same problem as in issue #1106 , because that was a 32 bits machine. Then again it may just be a coincidence that my patch worked for me. I'm not familiar at all with the codebase (just started using Spyder today).

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-09-09T21:42:01Z_

Ok so you may be able to answer to this: what is the relationship between the machine architecture (32 or 64bits) and the leading character "!" (or "=") ?

**Comment by spyder-issues-migrator** [comment]
_From [mvi...@gmail.com](https://code.google.com/u/108668877517097490134/) on 2012-09-10T00:45:30Z_

It's all here: http://docs.python.org/library/struct.html#format-strings The "@" means native byte order and size. That is, whatever the compiler thinks it is while building the Python interpreter. For example "l" (signed long) will be 4 bytes long in Windows and 32-bit Linux, but 8 bytes long in 64-bit Linux. (Generally all platforms but Windows double the size of all C data types in 64 bits). Also the byte order depends on the platform, so on Intel and AMD processors it will be little endian, but in pretty much every other processor it'll be big endian.

The "!" means network byte order, standard size. So the sizes are the ones we expect (long is 4 bytes, short is 2) and big endian. It's called "network" because it's the size and byte order defined by the BSD sockets standard. Since the file is called "bsdsocket.py" it seemed fitting. :)

The "<" and ">" mean standard size, and little endian/big endian respectively (or backwards, I can never remember). So "!" is the same as big endian, but I find it easier to remember, and in this case more descriptive of what you're doing with the bytes you're packing.

The "=" mean standard size, native byte order. So the sizes will be correct, but on non-Intel compatible platforms the byte order will be reversed.

Now, this is the mystery: if we're only unpacking the bytes we're packing in the same library, why does it fail? It should be irrelevant. So either someone else is also packing bytes (then why didn't it fail when I changed the endianness?) or it was just a coincidence.

You see, I've been thinking about issue #1106 . IT's a classic bug - failing to call recv() and/or send() in a loop. The Linux TCP/IP stack for the loopback interface pretty much matches every recv() to every send() call, so you don't usually notice this bug - so I don't think recv() was reading 4 bytes instead of 8, at least not in Linux (it may happen erratically in Windows). And I was getting that error consistently.

On the other hand, if someone else is packing bytes and sending them to bsdsocket.py when changing the byte order should have broken it.

The best explanation I can come up with is this: someone else is effectively sending bytes in whatever byte order, and it doesn't matter how I unpack them because there's only one recv() call and it reads the right amount of bytes regardless of the arguments we pass to it, thanks to a quirk of the Linux kernel.

If this is true, on Windows my patch would cause bsdsocket.py to get stuck reading a ridiculous amount of bytes from the socket, because it unpacked the size using the wrong byte order.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-09-10T13:08:36Z_

Thanks for all these explanations.

But, as you wrote, if we're only unpacking the bytes we're packing using the same bsdsocket.py module, then the format should be irrelevant. And, within Spyder code, I can assure you that noone else is sending bytes to bsdsocket.py except bsdsocket.py itself. So, I think that the "coincidence" is the most probable explanation.

**Comment by spyder-issues-migrator** [comment]
_From [mvi...@gmail.com](https://code.google.com/u/108668877517097490134/) on 2012-09-10T13:19:08Z_

You're welcome :)

Indeed then, the patch worked in my machine by sheer luck! xD

I'd still advice to change the format strings if there's any plan of ever connecting sockets with bsdsocket.py between different machines, these endianness bugs tend to creep up unnoticed...

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-02T18:26:25Z_

Seems a duplicate of 1106 to me :-)

**Status:** Duplicate  
  **Mergedinto:** 1106
