### ISSUE TITLE
Figure option dialog fails

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1147]
_From [ricardob...@gmail.com](https://code.google.com/u/116032747765426583751/) on 2012-09-10T09:08:39Z_

Spyder Version:  2.1.11
Python Version:  2.6.5
Qt Version:      4.6.2, PyQt4 (API v1) 4.7.2 on Linux 

What steps will reproduce the problem?

 1. Plot a figure
2. Click on the figure options button
3. An error occurs and no dialog is opened.

This has happen to me randomly. Some this future works for a few days, and then stop working. It appear to be somehow random. 

I am working with two displays. Could this be an issue? What is the expected output? What do you see instead? The expected behavior is the opening of dialog box for modifying some figure parameters. 

This fails and outputs in console:
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/matplotlib-1.1.0-py2.6-linux-i686.egg/matplotlib/backends/backend_qt4.py", line 463, in edit_parameters
    figureoptions.figure_edit(axes, self)
  File "/usr/local/lib/python2.6/dist-packages/matplotlib-1.1.0-py2.6-linux-i686.egg/matplotlib/backends/qt4_editor/figureoptions.py", line 132, in figure_edit
    icon=get_icon('qt4_editor_options.svg'), apply=apply_callback)
  File "/usr/local/lib/python2.6/dist-packages/matplotlib-1.1.0-py2.6-linux-i686.egg/matplotlib/backends/qt4_editor/formlayout.py", line 511, in fedit
    dialog = FormDialog(data, title, comment, icon, parent, apply)
  File "/usr/local/lib/python2.6/dist-packages/matplotlib-1.1.0-py2.6-linux-i686.egg/matplotlib/backends/qt4_editor/formlayout.py", line 427, in __init__
    self.formwidget.setup()
  File "/usr/local/lib/python2.6/dist-packages/matplotlib-1.1.0-py2.6-linux-i686.egg/matplotlib/backends/qt4_editor/formlayout.py", line 399, in setup
    widget.setup()
  File "/usr/local/lib/python2.6/dist-packages/matplotlib-1.1.0-py2.6-linux-i686.egg/matplotlib/backends/qt4_editor/formlayout.py", line 374, in setup
    widget.setup()
  File "/usr/local/lib/python2.6/dist-packages/matplotlib-1.1.0-py2.6-linux-i686.egg/matplotlib/backends/qt4_editor/formlayout.py", line 274, in setup
    selindex = value.pop(0)
AttributeError: 'tuple' object has no attribute 'pop'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1147_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-09-19T08:14:29Z_

If you find a more reproducible instance, please report it here. It's hard for us to try to fix this without more concrete info.

Thanks for reporting

**Labels:** Cat-Miscelleneous MS-v2.1

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-09-23T05:22:50Z_

This issue is certainly related to this: https://code.google.com/p/formlayout/issues/detail?id=4 But I still can't reproduce it.
We need a test case!

**Comment by spyder-issues-migrator** [comment]
_From [ricardob...@gmail.com](https://code.google.com/u/116032747765426583751/) on 2012-11-28T08:13:53Z_

I get a new error output when trying to open the Figure option dialog:

Output in console:
In [13]: ------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/matplotlib-1.1.1-py2.6-linux-i686.egg/matplotlib/backends/backend_qt4.py", line 483, in edit_parameters
    figureoptions.figure_edit(axes, self)
  File "/usr/local/lib/python2.6/dist-packages/matplotlib-1.1.1-py2.6-linux-i686.egg/matplotlib/backends/qt4_editor/figureoptions.py", line 132, in figure_edit
    icon=get_icon('qt4_editor_options.svg'), apply=apply_callback)
  File "/usr/local/lib/python2.6/dist-packages/matplotlib-1.1.1-py2.6-linux-i686.egg/matplotlib/backends/qt4_editor/formlayout.py", line 513, in fedit
    dialog = FormDialog(data, title, comment, icon, parent, apply)
  File "/usr/local/lib/python2.6/dist-packages/matplotlib-1.1.1-py2.6-linux-i686.egg/matplotlib/backends/qt4_editor/formlayout.py", line 429, in __init__
    self.formwidget.setup()
  File "/usr/local/lib/python2.6/dist-packages/matplotlib-1.1.1-py2.6-linux-i686.egg/matplotlib/backends/qt4_editor/formlayout.py", line 401, in setup
    widget.setup()
  File "/usr/local/lib/python2.6/dist-packages/matplotlib-1.1.1-py2.6-linux-i686.egg/matplotlib/backends/qt4_editor/formlayout.py", line 376, in setup
    widget.setup()
  File "/usr/local/lib/python2.6/dist-packages/matplotlib-1.1.1-py2.6-linux-i686.egg/matplotlib/backends/qt4_editor/formlayout.py", line 283, in setup
    field.addItems(value)
TypeError: QComboBox.addItems(QStringList): argument 1 has unexpected type 'list'

**Comment by spyder-issues-migrator** [comment]
_From [ricardob...@gmail.com](https://code.google.com/u/116032747765426583751/) on 2012-11-28T08:16:41Z_

The behavior stills random. I haven't been able to reproduce this error under controlled conditions. 

If I found a systematic way to reproduce the error, I'll definitely report it here.

PS: Great job with Spyder, best Scientific python-IDE out there.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-12-06T22:07:41Z_

Thanks for the praising Ricardo!

The error doesn't seem related to Spyder because on the tracebacks you posted I can't see any Spyder modules involved. All of them are from matplotlib.

Maybe you could have more luck asking on the matplotlib mailing list to see if is this a known problem or not.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-01-05T06:22:58Z_

Let's continue this discussion here: https://code.google.com/p/formlayout/issues/detail?id=4

**Status:** WontFix
