### ISSUE TITLE
first-run error on mac

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1149]
_From [goth...@gmail.com](https://code.google.com/u/107413083286304800601/) on 2012-09-13T02:11:39Z_

Spyder Version:  2.2.0dev
Python Version:  2.7.3
Qt Version:      4.8.2, PyQt4 (API v2) 4.9.4 on Darwin 

What steps will reproduce the problem?

 1. start spyder and run a script or run a script after a long period of inactivity
2. error occurs 
3. run again and no error What is the expected output? What do you see instead? expected: result from script

instead:
\>>> 
\>>> 
\>>> Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.pyo", line 551, in __bootstrap_inner
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/spyderlib/widgets/externalshell/introspection.py", line 65, in run
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/spyderlib/widgets/externalshell/introspection.py", line 49, in send_socket
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/spyderlib/widgets/externalshell/pythonshell.py", line 241, in set_introspection_socket
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/spyderlib/utils/bsdsocket.py", line 71, in communicate
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/spyderlib/utils/bsdsocket.py", line 40, in read_packet
error: unpack requires a string argument of length 8 

Please provide any additional information below

. I only get this on my mac. No issues on windows. Doesn't matter which script I run.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1149_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-09-19T07:37:50Z_

This is a known error which we are trying to solve in issue #1106 . Thanks for reporting.

**Status:** Duplicate  
  **Mergedinto:** 1106

**Comment by spyder-issues-migrator** [comment]
_From [ebori...@gmail.com](https://code.google.com/u/102672023975932251472/) on 2012-09-19T08:12:29Z_

If you are happy running 2.1, the MacPorts version likely has this fixed.
