### ISSUE TITLE
Mayavi doesn't run from within Spyder: complains about "ValueError: API 'QString' ..."

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1150]
_From [indranil...@gmail.com](https://code.google.com/u/105715438333079551218/) on 2012-09-15T13:17:25Z_

What steps will reproduce the problem?

 1. Just importing the Mayavi library in a script (for example using "import mayavi.mlab as mlab") and executing the script will reproduce this problem.
2. I am including a test file (note that this code is an example code from the Mayavi website) What is the expected output? What do you see instead? Expected output: A Mayavi figure window with the figure.
What I see instead: The following Value error (I am including the full sequence of message in order to be explicit)in the console window:

-------- Beginning of error message ------------------

Traceback (most recent call last):
  File "C:\PROGRAMSANDEXPERIMENTS\PYTHON\MayaviScripts\Learning\testMayavi.py", line 2, in \<module>
    import mayavi.mlab as mmlab
  File "C:\Python27\lib\site-packages\mayavi\mlab.py", line 27, in \<module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "C:\Python27\lib\site-packages\mayavi\tools\camera.py", line 25, in \<module>
    from engine_manager import get_engine
  File "C:\Python27\lib\site-packages\mayavi\tools\engine_manager.py", line 12, in \<module>
    from mayavi.preferences.api import preference_manager
  File "C:\Python27\lib\site-packages\mayavi\preferences\api.py", line 4, in \<module>
    from preference_manager import preference_manager
  File "C:\Python27\lib\site-packages\mayavi\preferences\preference_manager.py", line 29, in \<module>
    from traitsui.api import View, Group, Item
  File "C:\Python27\lib\site-packages\traitsui\api.py", line 35, in \<module>
    from .editors.api import (ArrayEditor, BooleanEditor, ButtonEditor,
  File "C:\Python27\lib\site-packages\traitsui\editors\__init__.py", line 22, in \<module>
    from .api import (toolkit, ArrayEditor, BooleanEditor, ButtonEditor,
  File "C:\Python27\lib\site-packages\traitsui\editors\api.py", line 10, in \<module>
    from .code_editor import CodeEditor
  File "C:\Python27\lib\site-packages\traitsui\editors\code_editor.py", line 36, in \<module>
    class ToolkitEditorFactory ( EditorFactory ):
  File "C:\Python27\lib\site-packages\traitsui\editors\code_editor.py", line 48, in ToolkitEditorFactory
    mark_color = Color( 0xECE9D8 )
  File "C:\Python27\lib\site-packages\traits\traits.py", line 487, in __call__
    return self.maker_function( *args, **metadata )
  File "C:\Python27\lib\site-packages\traits\traits.py", line 1183, in Color
    return ColorTrait( *args, **metadata )
  File "C:\Python27\lib\site-packages\traitsui\toolkit_traits.py", line 7, in ColorTrait
    return toolkit().color_trait( *args, **traits )
  File "C:\Python27\lib\site-packages\traitsui\toolkit.py", line 109, in toolkit
    _toolkit = _import_toolkit(ETSConfig.toolkit)
  File "C:\Python27\lib\site-packages\traitsui\toolkit.py", line 51, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit
  File "C:\Python27\lib\site-packages\traitsui\qt4\__init__.py", line 18, in \<module>
    import pyface.qt
  File "C:\Python27\lib\site-packages\pyface\qt\__init__.py", line 35, in \<module>
    prepare_pyqt4()
  File "C:\Python27\lib\site-packages\pyface\qt\__init__.py", line 17, in prepare_pyqt4
    sip.setapi('QString', 2)
ValueError: API 'QString' has already been set to version 1

---------------- End of error message -------------------- What version of the product are you using? On what operating system? This issue has been observed at-least in the following two environments:

Environment 1:
\------------- 
Description: Spyder and all other components were installed using the Pythonxy distribution (Py(x,y)-2.7.2.3.exe) on a Windows 7, 32 bit machine).
Spyder Version:  2.1.9
Python Version:  2.7.2 (32 bit)
Qt Version:      4.7.4, PyQt4 (API v1) 4.8.6 on Windows
Mayavi Version:  4.1.0

Environment 2:
\-------------
Description: On a separate machine running 64 bit Windows 7, I have installed 64-bit version of the Enthought EPD distribution. So it is running 2.7.3 (x64) version of Python distribution. Since the EPD package doesn't include Spyder, I manually installed Spyder after installing PyQt GPLv4.9.4.  
Spyder Version:  2.1.11
Python Version:  2.7.3 (64 bit)
Qt Version:      4.8.2, PyQt4 (API v2) 4.9.4 on Windows
Mayavi Version:  4.2.0 

Please provide any additional information below

. 1. I am sure that the code is fine, as the script produces the expected output when executed "outside" spyder environment. For example, using IPython shell.
2. Also, this issue may be related to issue #702 : Cant Save image in Mayavi

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1150_

**Comment by spyder-issues-migrator** [comment]
_From [indranil...@gmail.com](https://code.google.com/u/105715438333079551218/) on 2012-09-15T15:25:56Z_

Please use the following code:
from numpy import sin, cos, mgrid
import mayavi.mlab as mmlab

def f(x,y):
  return sin(x + y) + sin(2*x - y) + cos(3*x + 4*y)
        
x,y = mgrid[-7.:7.05:0.01, -5.:5.05:0.05]
z = f(x,y)
s = mmlab.contour_surf(x,y,z)
mmlab.show()

**Attachment:** [testMayavi2.py](http://code.google.com/p/spyderlib/issues/detail?id=1150#hc1)

**Comment by spyder-issues-migrator** [comment]
_From [indranil...@gmail.com](https://code.google.com/u/105715438333079551218/) on 2012-09-17T00:31:07Z_

I have a solution for now (I am not sure of it as a "fix"). I modified the following setting in Tools->Preferences->Console->External Modules->Enthought Tool Suite->ETS_TOOLKIT: change from "Qt4" to "wx".
After changing this setting, I am able to execute code with Mayavi library and Mayavi plots directly from within Spyder.

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-09-18T07:36:21Z_

You can continue to use Qt4 as the ETS toolkit setting if you make a Spyder settings change instead. This is essentially the same problem as reported by issue #1017 . The solution is as suggested by Comment 2 in that issue:

In Spyder, choose "API `#2`" under Preferences > Console > External modules > PyQt.

There may be a more elegant solution to this in the long run, but as long as Spyder supports both the legacy Verison 1 PyQt API and the never Version 2 PyQt API a setting like this is probably necessary.

**Status:** WontFix
