### ISSUE TITLE
Preferences window causes "an internal problem!" in Spyder 4.0.1

### ISSUE THREAD

**Issue by JamesCipparrone** [spyder-ide/spyder#11515]
### What steps will reproduce the problem?

**Steps to reproduce the problem**

1. Open "Preferences" (I use Ctrl + Alt + Shift + P).
2. Watch this "Issue reporter" dialog box appear. 
3. Repeat this several times.
4. Write these steps for the Spyder dev team.

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\envs\aipy36\lib\site-packages\spyder\app\mainwindow.py", line 3139, in show_preferences
    widget = plugin._create_configwidget(dlg, self)
  File "C:\ProgramData\Anaconda3\envs\aipy36\lib\site-packages\spyder\plugins\base.py", line 117, in _create_configwidget
    configwidget.initialize()
  File "C:\ProgramData\Anaconda3\envs\aipy36\lib\site-packages\spyder\preferences\configdialog.py", line 72, in initialize
    self.load_from_conf()
  File "C:\ProgramData\Anaconda3\envs\aipy36\lib\site-packages\spyder\preferences\configdialog.py", line 327, in load_from_conf
    checkbox.setChecked(self.get_option(option, default, section=sec))
TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\aipy36\lib\site-packages\spyder\app\mainwindow.py", line 3139, in show_preferences
    widget = plugin._create_configwidget(dlg, self)
  File "C:\ProgramData\Anaconda3\envs\aipy36\lib\site-packages\spyder\plugins\base.py", line 117, in _create_configwidget
    configwidget.initialize()
  File "C:\ProgramData\Anaconda3\envs\aipy36\lib\site-packages\spyder\preferences\configdialog.py", line 72, in initialize
    self.load_from_conf()
  File "C:\ProgramData\Anaconda3\envs\aipy36\lib\site-packages\spyder\preferences\configdialog.py", line 327, in load_from_conf
    checkbox.setChecked(self.get_option(option, default, section=sec))
TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.11.1 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
zmq >=17                     :  18.1.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
sphinx >=0.6.6               :  2.3.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  3.1.1 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
sympy >=0.7.3                :  None (NOK)
```

**Comment by ccordoba12** [comment]
You need to update any Spyder third-party plugin you have installed (like spyder-notebook or spyder-memory-profiler), in order to fix this.

**Comment by JamesCipparrone** [comment]
Thank you, Carlos! I appreciate your quick response. I'll update any third-party plugins (and their dependencies).
