### ISSUE TITLE
spyder not open

### ISSUE THREAD

**Issue by andyyhs** [spyder-ide/spyder#11578]
nice to meet you ,I come from china  ,I have a problem about Spyder, I am very  anxious
hope you can help me！my QQ 969566466, thank you very much .

win10    spyder 3.3.6     anaconda navagator 1.9.7       python 3.8.1

```python-traceback
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3285, in main
    mainwindow = run_spyder(app, options, args)
  File "E:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3140, in run_spyder
    main.setup()
  File "E:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 914, in setup
    from spyder.plugins.ipythonconsole import IPythonConsole
  File "E:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 27, in <module>
    from qtconsole.client import QtKernelClient
  File "E:\ProgramData\Anaconda3\lib\site-packages\qtconsole\client.py", line 12, in <module>
    from zmq.eventloop import ioloop, zmqstream
  File "E:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\__init__.py", line 3, in <module>
    from zmq.eventloop.ioloop import IOLoop
  File "E:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 21, in <module>
    from tornado import ioloop
  File "D:\Program Files\Python37\Lib\site-packages\tornado\ioloop.py", line 33, in <module>
    import asyncio
  File "D:\Program Files\Python37\Lib\site-packages\asyncio\__init__.py", line 21, in <module>
    from .base_events import *
  File "D:\Program Files\Python37\Lib\site-packages\asyncio\base_events.py", line 296
    future = tasks.async(future, loop=self)
                       ^
SyntaxError: invalid syntax
```

**Comment by ccordoba12** [comment]
The problem is that you're mixing two Python installations. Please remove the one present in

    D:\Program Files\Python37

so that you use only Anaconda.

**Comment by andyyhs** [comment]
perfect，thank you very much ！

**Comment by andyyhs** [comment]
> The problem is that you're mixing two Python installations. Please remove the one present in
> D:\Program Files\Python37
> 
> so that you use only Anaconda.

very good ！
