### ISSUE TITLE
AttributeError: type object 'pandas._libs.reduction.Reducer' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by JASHWANTHREDDYTUPILI** [spyder-ide/spyder#11588]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.12.0 -- An enhanced Interactive Python.

3*5
Out[1]: 15

runfile('C:/Users/tjash/.spyder-py3/temp.py', wdir='C:/Users/tjash/.spyder-py3')

runfile('C:/Users/tjash/.spyder-py3/temp.py', wdir='C:/Users/tjash/.spyder-py3')
Traceback (most recent call last):

  File "C:\Users\tjash\.spyder-py3\temp.py", line 9, in <module>
    import pandas

  File "C:\Users\tjash\Anaconda3\lib\site-packages\pandas\__init__.py", line 54, in <module>
    from pandas.core.api import (

  File "C:\Users\tjash\Anaconda3\lib\site-packages\pandas\core\api.py", line 29, in <module>
    from pandas.core.groupby import Grouper, NamedAgg

  File "C:\Users\tjash\Anaconda3\lib\site-packages\pandas\core\groupby\__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import DataFrameGroupBy, NamedAgg, SeriesGroupBy

  File "C:\Users\tjash\Anaconda3\lib\site-packages\pandas\core\groupby\generic.py", line 63, in <module>
    from pandas.core.groupby.groupby import (

  File "C:\Users\tjash\Anaconda3\lib\site-packages\pandas\core\groupby\groupby.py", line 61, in <module>
    from pandas.core.groupby import base, ops

  File "C:\Users\tjash\Anaconda3\lib\site-packages\pandas\core\groupby\ops.py", line 16, in <module>
    import pandas._libs.reduction as libreduction

  File "pandas\_libs\reduction.pyx", line 30, in init pandas._libs.reduction

AttributeError: type object 'pandas._libs.reduction.Reducer' has no attribute '__reduce_cython__'

runfile('C:/Users/tjash/Anaconda3/lib/site-packages/pandas/core/groupby/ops.py', wdir='C:/Users/tjash/Anaconda3/lib/site-packages/pandas/core/groupby')
Traceback (most recent call last):

  File "C:\Users\tjash\Anaconda3\lib\site-packages\pandas\core\groupby\ops.py", line 15, in <module>
    import pandas._libs.groupby as libgroupby

  File "C:\Users\tjash\Anaconda3\lib\site-packages\pandas\__init__.py", line 54, in <module>
    from pandas.core.api import (

  File "C:\Users\tjash\Anaconda3\lib\site-packages\pandas\core\api.py", line 29, in <module>
    from pandas.core.groupby import Grouper, NamedAgg

  File "C:\Users\tjash\Anaconda3\lib\site-packages\pandas\core\groupby\__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import DataFrameGroupBy, NamedAgg, SeriesGroupBy

  File "C:\Users\tjash\Anaconda3\lib\site-packages\pandas\core\groupby\generic.py", line 63, in <module>
    from pandas.core.groupby.groupby import (

  File "C:\Users\tjash\Anaconda3\lib\site-packages\pandas\core\groupby\groupby.py", line 61, in <module>
    from pandas.core.groupby import base, ops

  File "C:\Users\tjash\Anaconda3\lib\site-packages\pandas\core\groupby\ops.py", line 16, in <module>
    import pandas._libs.reduction as libreduction

  File "pandas\_libs\reduction.pyx", line 30, in init pandas._libs.reduction

AttributeError: type object 'pandas._libs.reduction.Reducer' has no attribute '__reduce_cython__'

**Comment by JASHWANTHREDDYTUPILI** [comment]
![image](https://user-images.githubusercontent.com/61199755/74755276-8ae2ff80-5238-11ea-9754-2e3a406dfbf2.png)

working for a while in Spyder the kernel stopped working stating that session stopped ,to fix verify that your firewall allows python .It was working fine all these days and suddenly stopped ,I attached the image for reference and log as well

so I stopped windows firewall and I ran conda update anaconda then kernel is working fine but I cannot import pandas

Please help to me fix this issue

**Comment by ccordoba12** [comment]
> File "C:\Users\tjash\Anaconda3\lib\site-packages\pandas\core\groupby\ops.py", line 16, in import pandas._libs.reduction as libreduction File "pandas\_libs\reduction.pyx", line 30, in init pandas._libs.reduction AttributeError: type object 'pandas._libs.reduction.Reducer' has no attribute '__reduce_cython__' 

Probably you installed something with pip which caused this breakage in Pandas. Now you have to remove and reinstall Anaconda to fix that problem. In the future, please don't use pip to install a package if you can use conda to do that.

> It was working fine all these days and suddenly stopped ,I attached the image for reference and log as well

Please follow the advice that that message mentions.

**Comment by JASHWANTHREDDYTUPILI** [comment]
Thanks for the quick reply but haven't done anything using pip and also I reinstalled the anaconda 10 times till now it is of no use

**Comment by ccordoba12** [comment]
Sorry to hear that, but the Pandas problem is not a problem with Spyder.

**Comment by JASHWANTHREDDYTUPILI** [comment]
Fine, Thank you so much
for your time
