### ISSUE TITLE
"ImportError: cannot import name urandom" on the MacOS App when switching to the system's Python

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1159]
_From [fhe...@gmail.com](https://code.google.com/u/111731474599148743921/) on 2012-09-30T13:00:53Z_

Spyder Version:  2.2.0dev
Python Version:  2.7.3
Qt Version:      4.8.2, PyQt4 (API v2) 4.9.4 on Darwin 

What steps will reproduce the problem?

 1.Download the .dmg file
2.execute Spyderlib
3.you will see several error messages on the console, and won't be able to import matplotlib nor numpy. What is the expected output? What do you see instead? expect to see no errors
Instead, I see:

Python 2.7.2 (default, Nov 13 2011, 23:23:25) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.1.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/scientific_startup.py", line 16, in \<module>
    from pylab import *  #analysis:ignore
  File "pylab.pyo", line 1, in \<module>
    
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/matplotlib/__init__.py", line 132, in \<module>
    import sys, os, tempfile
  File "tempfile.pyo", line 34, in \<module>
    
  File "random.pyo", line 47, in \<module>
    
ImportError: cannot import name urandom
\>>> 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1159_

**Comment by spyder-issues-migrator** [comment]
_From [nunocal...@gmail.com](https://code.google.com/u/112412051321087742327/) on 2012-10-23T08:27:42Z_

exactly the same problem! Did you solve this?

**Comment by spyder-issues-migrator** [comment]
_From [tpoll...@gmail.com](https://code.google.com/u/114369770150738055280/) on 2012-10-25T14:15:10Z_

As a point of reference, for me, with OS 10.7.5 and the default configuration of Spyder from the dmg install, this error does not occur. When I switch to the system's default Python install (which it appears the original poster has, above,  based on python 2.7.2 being listed), only then do I get the same error as this bug report.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-10-26T07:49:14Z_

Thanks a lot for the new info tpollari. That's the kind of info we need to understand what is triggering the error.

The solution is pretty simple. Go to:

Tools > Preferences > Console > Advanced Settings > PYTHONSTARTUP replacement

and active the option called:

Default PYTHONSTARTUP script

That's it.

However, I'll add an option to do this automatically when the user changes his Python executable.

**Summary:** "ImportError: cannot import name urandom" on the MacOS App when switching to the system's Python  
  **Status:** Accepted  
  **Labels:** OpSys-OSX MS-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [der.lock...@gmail.com](https://code.google.com/u/101641030071861214018/) on 2012-10-28T14:54:37Z_

I'm getting the same error although I have activated the above mentioned option ('default PYTHONSTARTUP script). 

I have also activated my local python interpreter and selected the ' Open a Python interpreter at startup' option. 
I'm on OSX.

**Comment by spyder-issues-migrator** [comment]
_From [fhe...@gmail.com](https://code.google.com/u/111731474599148743921/) on 2012-12-17T04:44:58Z_

The fix from ccordoba12 works fine, until I run a script that calls for scipy. Then I get the same error again and can't run my script.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-01-26T19:14:54Z_

Ok, I found the fix for this one. I'll publish a new app tomorrow. Thanks for your patience :)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-01-26T19:18:23Z_

**Status:** Duplicate  
  **Mergedinto:** 1226

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-04-06T20:24:34Z_

**Labels:** Cat-Console
