### ISSUE TITLE
Kernel error in spyder

### ISSUE THREAD

**Issue by JASHWANTHREDDYTUPILI** [spyder-ide/spyder#11594]
### Issue Report Checklist

* [ yes] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [yes ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice

## Problem Description
kernel doesn't start in Sypder,says traceback error

### Paste Traceback/Error Below (if applicable)
An error ocurred while starting the kernel
Traceback (most recent call last):
File "D:\Anaconda\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "D:\Anaconda\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "D:\Anaconda\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "D:\Anaconda\lib\site‑packages\spyder_kernels\console\start.py", line 279, in main
import_spydercustomize()
File "D:\Anaconda\lib\site‑packages\spyder_kernels\console\start.py", line 39, in import_spydercustomize
import spydercustomize
File "D:\Anaconda\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 27, in 
from IPython.core.getipython import get_ipython
File "D:\Anaconda\lib\site‑packages\IPython\__init__.py", line 54, in 
from .core.application import Application
File "D:\Anaconda\lib\site‑packages\IPython\core\application.py", line 16, in 
from copy import deepcopy
File "D:\Anaconda\lib\copy.py", line 60, in 
from org.python.core import PyStringMap
File "C:\Users\tjash\org.py", line 8, in 
import pandas as pd
File "D:\Anaconda\lib\site‑packages\pandas\__init__.py", line 42, in 
from pandas.core.api import *
File "D:\Anaconda\lib\site‑packages\pandas\core\api.py", line 26, in 
from pandas.core.groupby import Grouper
File "D:\Anaconda\lib\site‑packages\pandas\core\groupby\__init__.py", line 1, in 
from pandas.core.groupby.groupby import GroupBy # noqa: F401
File "D:\Anaconda\lib\site‑packages\pandas\core\groupby\groupby.py", line 37, in 
from pandas.core.frame import DataFrame
File "D:\Anaconda\lib\site‑packages\pandas\core\frame.py", line 100, in
from pandas.core.series import Series
File "D:\Anaconda\lib\site‑packages\pandas\core\series.py", line 51, in
import pandas.plotting._core as gfx
File "D:\Anaconda\lib\site‑packages\pandas\plotting\__init__.py", line 11, in 
from pandas.plotting._core import boxplot
File "D:\Anaconda\lib\site‑packages\pandas\plotting\_core.py", line 36, in 
from pandas.plotting import _converter
File "D:\Anaconda\lib\site‑packages\pandas\plotting\_converter.py", line 6, in 
import matplotlib.dates as dates
File "D:\Anaconda\lib\site‑packages\matplotlib\__init__.py", line 141, in 
from . import cbook, rcsetup
File "D:\Anaconda\lib\site‑packages\matplotlib\rcsetup.py", line 25, in
from matplotlib.fontconfig_pattern import parse_fontconfig_pattern
File "D:\Anaconda\lib\site‑packages\matplotlib\fontconfig_pattern.py", line 19, in 
from pyparsing import (Literal, ZeroOrMore, Optional, Regex, StringEnd,
File "D:\Anaconda\lib\site‑packages\pyparsing.py", line 5235, in 
_reBracketExpr = Literal("[") + Optional("^").setResultsName("negate") + Group( OneOrMore( _charRange | _singleChar ) ).setResultsName("body") + "]"
File "D:\Anaconda\lib\site‑packages\pyparsing.py", line 1365, in setResultsName
newself = self.copy()
File "D:\Anaconda\lib\site‑packages\pyparsing.py", line 1322, in copy
cpy = copy.copy( self )
AttributeError: module 'copy' has no attribute 'copy'

## Versions

* Spyder version: 3.3.6
* Python version: 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Please search for a file called `copy.py` in your Users directory and remove it. That should solve your problem.

**Comment by JASHWANTHREDDYTUPILI** [comment]
did resolve even after deletion

**Comment by JASHWANTHREDDYTUPILI** [comment]
sorry did not resolve even after deletion
