### ISSUE TITLE
Keras ImportError

### ISSUE THREAD

**Issue by ab-5860** [spyder-ide/spyder#11618]
### What steps will reproduce the problem?

I simply type "import keras" and following lines of error pops out.
I am not able to understand this as I am new to keras library.

ERROR -->
import keras
Traceback (most recent call last):

  File "<ipython-input-23-88d96843a926>", line 1, in <module>
    import keras

  File "C:\Users\Kumar Abhishek\AppData\Roaming\Python\Python37\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils

  File "C:\Users\Kumar Abhishek\AppData\Roaming\Python\Python37\site-packages\keras\utils\__init__.py", line 26, in <module>
    from .vis_utils import model_to_dot

  File "C:\Users\Kumar Abhishek\AppData\Roaming\Python\Python37\site-packages\keras\utils\vis_utils.py", line 7, in <module>
    from ..models import Model

  File "C:\Users\Kumar Abhishek\AppData\Roaming\Python\Python37\site-packages\keras\models.py", line 12, in <module>
    from .engine.training import Model

  File "C:\Users\Kumar Abhishek\AppData\Roaming\Python\Python37\site-packages\keras\engine\__init__.py", line 8, in <module>
    from .training import Model

  File "C:\Users\Kumar Abhishek\AppData\Roaming\Python\Python37\site-packages\keras\engine\training.py", line 14, in <module>
    from . import training_utils

  File "C:\Users\Kumar Abhishek\AppData\Roaming\Python\Python37\site-packages\keras\engine\training_utils.py", line 17, in <module>
    from .. import metrics as metrics_module

  File "C:\Users\Kumar Abhishek\AppData\Roaming\Python\Python37\site-packages\keras\metrics.py", line 13, in <module>
    from .layers import Layer

  File "C:\Users\Kumar Abhishek\AppData\Roaming\Python\Python37\site-packages\keras\layers\__init__.py", line 40, in <module>
    from .convolutional import Conv1D

  File "C:\Users\Kumar Abhishek\AppData\Roaming\Python\Python37\site-packages\keras\layers\convolutional.py", line 27, in <module>
    from ..legacy.layers import AtrousConvolution1D

ModuleNotFoundError: No module named 'keras.legacy.layers'

Error in callback <bound method AutoreloadMagics.post_execute_hook of <autoreload.AutoreloadMagics object at 0x000002E88E8682C8>> (for post_execute):
Traceback (most recent call last):

  File "C:\Users\Kumar Abhishek\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 538, in post_execute_hook
    _, pymtime = self._reloader.filename_and_mtime(sys.modules[modname])

  File "C:\Users\Kumar Abhishek\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 184, in filename_and_mtime
    if not hasattr(module, '__file__') or module.__file__ is None:

  File "C:\Users\Kumar Abhishek\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__

  File "C:\Users\Kumar Abhishek\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 44, in _load

  File "C:\Users\Kumar Abhishek\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load

  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load

  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 728, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "C:\Users\Kumar Abhishek\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\__init__.py", line 43, in <module>
    from . _api.v2 import autodiff

ImportError: cannot import name 'autodiff' from 'tensorflow_core._api.v2' (C:\Users\Kumar Abhishek\Anaconda3\lib\site-packages\tensorflow_core\_api\v2\__init__.py)

**Comment by spoorgholi74** [comment]
@ab-5860 
Have you installed Tensorflow before installing Keras?
And maybe can you send a list of your packages?

**Comment by ccordoba12** [comment]
This is not a problem with Spyder but with Keras and Tensorflow, so I'm closing it, sorry.

**Comment by ccordoba12** [comment]
But from this part of your error message

> "C:\Users\Kumar Abhishek\AppData\Roaming\Python\Python37\site-packages\keras_init_.py"

and this one

> ImportError: cannot import name 'autodiff' from 'tensorflow_core.api.v2' (C:\Users\Kumar Abhishek\Anaconda3\lib\site-packages\tensorflow_core_api\v2_init.py)

it's clear that you're mixing pip and conda packages, which is a recipe for disaster.

So please remove this directory

> C:\Users\Kumar Abhishek\AppData\Roaming\Python

remove and reinstall Anaconda and install Keras and Tensorflow with **conda** and not with pip.
