### ISSUE TITLE
update spyder3 to 4 ，fail to open

### ISSUE THREAD

**Issue by andyyhs** [spyder-ide/spyder#11613]
win 10    python3.8.1   spyder4
today，I update my  spyder3.3.6 to version 4，but anaconda navigator fail to open  and  spyder fail to open  ，help me ，thank you ！

Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3789, in main
    mainwindow = run_spyder(app, options, args)
  File "E:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3630, in run_spyder
    main.setup()
  File "E:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1013, in setup
    from spyder.plugins.ipythonconsole.plugin import IPythonConsole
  File "E:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 46, in <module>
    from spyder.plugins.ipythonconsole.widgets import (ClientWidget,
  File "E:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\__init__.py", line 24, in <module>
    from .shell import ShellWidget
  File "E:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 29, in <module>
    from spyder.plugins.ipythonconsole.comms.kernelcomm import KernelComm
  File "E:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\__init__.py", line 13, in <module>
    from spyder_kernels.comms.commbase import CommError
ModuleNotFoundError: No module named 'spyder_kernels.comms'

debug info--------------------------------------------------------------------------
2020-02-21 11:11:19,267 [DEBUG] [spyder.api.editorextension] -> <class 'spyder.plugins.editor.panels.edgeline.EdgeLine'>.__del__
2020-02-21 11:11:19,267 [DEBUG] [spyder.api.editorextension] -> <class 'spyder.plugins.editor.panels.indentationguides.IndentationGuide'>.__del__
2020-02-21 11:11:19,277 [DEBUG] [spyder.api.editorextension] -> <class 'spyder.plugins.editor.panels.codefolding.FoldingPanel'>.__del__
2020-02-21 11:11:19,277 [DEBUG] [spyder.api.editorextension] -> <class 'spyder.plugins.editor.panels.debugger.DebuggerPanel'>.__del__
2020-02-21 11:11:19,277 [DEBUG] [spyder.api.editorextension] -> <class 'spyder.plugins.editor.panels.linenumber.LineNumberArea'>.__del__
2020-02-21 11:11:19,277 [DEBUG] [spyder.api.editorextension] -> <class 'spyder.plugins.editor.panels.classfunctiondropdown.ClassFunctionDropdown'>.__del__
2020-02-21 11:11:19,277 [DEBUG] [spyder.api.editorextension] -> <class 'spyder.plugins.editor.panels.scrollflag.ScrollFlagArea'>.__del__
2020-02-21 11:11:19,277 [DEBUG] [spyder.api.editorextension] -> <class 'spyder.plugins.editor.extensions.snippets.SnippetsExtension'>.__del__
2020-02-21 11:11:19,277 [DEBUG] [spyder.api.editorextension] -> <class 'spyder.plugins.editor.extensions.closebrackets.CloseBracketsExtension'>.__del__
2020-02-21 11:11:19,277 [DEBUG] [spyder.api.editorextension] -> <class 'spyder.plugins.editor.extensions.closequotes.CloseQuotesExtension'>.__del__
2020-02-21 11:11:19,277 [DEBUG] [spyder.api.editorextension] -> <class 'spyder.plugins.editor.panels.edgeline.EdgeLine'>.__del__
2020-02-21 11:11:19,277 [DEBUG] [spyder.api.editorextension] -> <class 'spyder.plugins.editor.panels.indentationguides.IndentationGuide'>.__del__
2020-02-21 11:11:19,287 [DEBUG] [spyder.api.editorextension] -> <class 'spyder.plugins.editor.panels.codefolding.FoldingPanel'>.__del__
2020-02-21 11:11:19,287 [DEBUG] [spyder.api.editorextension] -> <class 'spyder.plugins.editor.panels.debugger.DebuggerPanel'>.__del__
2020-02-21 11:11:19,287 [DEBUG] [spyder.api.editorextension] -> <class 'spyder.plugins.editor.panels.linenumber.LineNumberArea'>.__del__
2020-02-21 11:11:19,287 [DEBUG] [spyder.api.editorextension] -> <class 'spyder.plugins.editor.panels.classfunctiondropdown.ClassFunctionDropdown'>.__del__
2020-02-21 11:11:19,287 [DEBUG] [spyder.api.editorextension] -> <class 'spyder.plugins.editor.panels.scrollflag.ScrollFlagArea'>.__del__
2020-02-21 11:11:19,287 [DEBUG] [spyder.api.editorextension] -> <class 'spyder.plugins.editor.extensions.snippets.SnippetsExtension'>.__del__
2020-02-21 11:11:19,287 [DEBUG] [spyder.api.editorextension] -> <class 'spyder.plugins.editor.extensions.closebrackets.CloseBracketsExtension'>.__del__
2020-02-21 11:11:19,287 [DEBUG] [spyder.api.editorextension] -> <class 'spyder.plugins.editor.extensions.closequotes.CloseQuotesExtension'>.__del__

**Comment by ccordoba12** [comment]
> win 10 python3.8.1 spyder4
today，I update my spyder3.3.6 to version 4，but anaconda navigator fail to open and spyder fail to open ，help me ，thank you ！

Remove and reinstall Anaconda, don't use Python 3.8 but Python 3.7 instead and run these commands to update to Spyder 4:

    conda update anaconda
    conda install spyder=4.0.1

**Comment by andyyhs** [comment]
remove python 3.8 ？and install python3.7 ？

**Comment by andyyhs** [comment]
> win 10 python3.8.1 spyder4
> today，I update my spyder3.3.6 to version 4，but anaconda navigator fail to open and spyder fail to open ，help me ，thank you ！
> 
> Remove and reinstall Anaconda, don't use Python 3.8 but Python 3.7 instead and run these commands to update to Spyder 4:
> conda update anaconda
> conda install spyder=4.0.1

I know  thanks
