### ISSUE TITLE
Run "F5" Key only works twice on the MacOs X App

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1162]
_From [dcrane63...@yahoo.com](https://code.google.com/u/107119963951145423615/) on 2012-10-02T21:21:33Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1.load python script "junk.py" attached
2.Run "F5" three times 3. What is the expected output? 
Hello World!
Hello World2!
Hello World3!

What do you see instead? on third F5
Traceback (most recent call last):
  File "/Applications/Spyder.app/Contents/Resources/site.py", line 120, in \<module>
    import sitecustomize
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/spyderlib/widgets/externalshell/sitecustomize.py", line 142, in \<module>
    os.environ["SPYDER_AR_STATE"].lower() == "true")
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/spyderlib/widgets/externalshell/monitor.py", line 133, in __init__
    self.i_request.connect( (host, introspection_port) )
  File "socket.pyo", line 224, in meth
    
socket.error: [Errno 60] Operation timed out

What version of the product are you using? 
Spyder 2.2.0dev 

On what operating system?
OS X 10.8.2 

Please provide any additional information below

.

**Attachment:** [junk.py](http://code.google.com/p/spyderlib/issues/detail?id=1162)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1162_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-10-08T09:35:35Z_

This is probably the same error as reported on issue #1106 , which we fixed a couple of weeks ago. I'll update the app soon to incorporate this fix and we'll see if that solves your problem too.

Thanks for reporting.

**Summary:** Run "F5" Key only works twice on the MaOs X App  
  **Labels:** OpSys-OSX Cat-Console MS-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [christop...@googlemail.com](https://code.google.com/u/101955404575459343363/) on 2012-10-28T13:17:00Z_

I am new to spyder and I am not an expert, but i think it is the same issue. 



What steps will reproduce the problem?


1. Load arbitrary python script.
2. Run it 
3. Console output:
Traceback (most recent call last):
File "threading.pyo", line 551, in __bootstrap_inner
File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/spyderlib/widgets/externalshell/introspection.py", line 65, in run
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/spyderlib/widgets/externalshell/introspection.py", line 49, in send_socket
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/spyderlib/widgets/externalshell/pythonshell.py", line 241, in set_introspection_socket
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/spyderlib/utils/bsdsocket.py", line 71, in communicate
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/spyderlib/utils/bsdsocket.py", line 40, in read_packet
error: unpack requires a string argument of length 8
4. Run script twice again
5. Console output is like expected. 
6. Run script again (third run) 
7. Error like it is reported ( issue #1162 ) spyder

What version of product are you using?
Spyder 2.2.0dev installed via featured dmg

On what operating system?
OS X 10.8.2

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-01-27T09:18:52Z_

I verified it with the latest version that this is already fixed. I'll try to upload a new DMG this afternoon.

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-04T09:16:26Z_

**Summary:** Run "F5" Key only works twice on the MacOs X App  \<span class="oldvalue"> (was: Run "F5" Key only works twice on the MaOs X App) \</span>

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-04T14:40:34Z_

**Status:** Duplicate  
  **Mergedinto:** 1106
