### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by Fakeruone** [spyder-ide/spyder#11693]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

An error ocurred while starting the kernel
The error is:

Traceback (most recent call last):
File "D:\anaconda\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "D:\anaconda\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "D:\anaconda\lib\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "D:\anaconda\lib\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "D:\anaconda\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "D:\anaconda\lib\site‑packages\jupyter_client\connect.py", line 102, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\fakerone\\AppData\\Roaming\\jupyter\\runtime\\kernel‑c65991a48e66.json'

打开spyder时报的错，请问是什么原因，怎么解决？谢谢大神们！

**Comment by ccordoba12** [comment]
Please open the Anaconda Prompt and run there

    conda update anaconda
    conda update jupyter_client

That should fix this problem.
