### ISSUE TITLE
Kernel Error Occurred in Spyder

### ISSUE THREAD

**Issue by Arijit11** [spyder-ide/spyder#11695]
It shows that an error occurred while starting the kernel in Spyder(Anaconda3)

Further details:
Traceback (most recent call last):
File "C:\Users\Arijit\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\Arijit\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\Users\Arijit\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "C:\Users\Arijit\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "C:\Users\Arijit\Anaconda3\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "C:\Users\Arijit\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 102, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Arijit\\AppData\\Roaming\\jupyter\\runtime\\kernel󈛶e8bdd3a387.json'

Any ideas on how to fix this?

**Comment by ccordoba12** [comment]
Please open the Anaconda Prompt and run there

    conda update anaconda
    conda update jupyter_client

That should fix your problem.
