### ISSUE TITLE
Opening problem

### ISSUE THREAD

**Issue by Devanshu30042003** [spyder-ide/spyder#11716]
### What steps will reproduce the problem?

Anaconda Navigator and Prompt is not opening and closes immediately.

### Traceback
```python-traceback
  File "C:\Users\YOGESH\Anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 162, in lock
    symlink(str(os.getpid()), self.name)
  File "C:\Users\YOGESH\Anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 97, in symlink
    rename(newlinkname, filename)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\YOGESH\\.spyder-py3\\spyder.lock.1583305316134.newlink' -> 'C:\\Users\\YOGESH\\.spyder-py3\\spyder.lock'

Traceback (most recent call last):
  File "C:\Users\YOGESH\Anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 189, in lock
    kill(int(pid), 0)
  File "C:\Users\YOGESH\Anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 81, in kill
    raise OSError(errno.ESRCH, None)
ProcessLookupError: [Errno 3] None

Traceback (most recent call last):
  File "C:\Users\YOGESH\Anaconda3\lib\site-packages\spyder\app\start.py", line 157, in main
    lock_created = lock.lock()
  File "C:\Users\YOGESH\Anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 212, in lock
    rmlink(self.name)
  File "C:\Users\YOGESH\Anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 119, in rmlink
    os.remove(os.path.join(filename, 'symlink'))
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\YOGESH\\.spyder-py3\\spyder.lock\\symlink'

Traceback (most recent call last):
  File "C:\Users\YOGESH\Anaconda3\lib\site-packages\spyder\plugins\__init__.py", line 515, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\Users\YOGESH\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 771, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\YOGESH\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1111, in create_new_client
    self.register_client(client)
  File "C:\Users\YOGESH\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1307, in register_client
    self.main.historylog.add_history(client.history_filename)
  File "C:\Users\YOGESH\Anaconda3\lib\site-packages\spyder\plugins\history.py", line 240, in add_history
    encoding.write(text, filename)
  File "C:\Users\YOGESH\Anaconda3\lib\site-packages\spyder\utils\encoding.py", line 233, in write
    with open(filename, mode) as textfile:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\YOGESH\\.spyder-py3\\history.py'
WARNING:traitlets:kernel died: 18.00008535385132
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.3 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
This is fixed in our latest Spyder 3 version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.6
