### ISSUE TITLE
Error message at first run

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1173]
_From [jeanpatr...@gmail.com](https://code.google.com/u/100950875858888510591/) on 2012-10-14T08:23:52Z_

Spyder Version:  2.1.11
Python Version:  2.7.3
Qt Version:      4.8.1, PyQt4 (API v2) 4.9.1 on Linux 

What steps will reproduce the problem?

 1.start spyder
2.start any script
3.run a script (F5) What is the expected output? What do you see instead? Always get in the console:

Python 2.7.3 (default, Aug  1 2012, 05:16:07)
[GCC 4.6.3] on linux2
Type "copyright", "credits" or "license" for more information.

\>>> Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/introspection.py", line 65, in run
    self.send_socket(shell_id, conn)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/introspection.py", line 49, in send_socket
    shell.set_introspection_socket(sock)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/pythonshell.py", line 246, in set_introspection_socket
    'set_remote_view_settings()', settings=[settings])
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/utils/bsdsocket.py", line 67, in communicate
    return read_packet(sock)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/utils/bsdsocket.py", line 36, in read_packet
    dlen, = struct.unpack("l", datalen)
error: unpack requires a string argument of length 4 

Please provide any additional information below

. 4. run the script again or another one, no more message

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1173_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-02T18:33:19Z_

**Status:** Duplicate  
  **Mergedinto:** 1106
