### ISSUE TITLE
Kite installation, maybe

### ISSUE THREAD

**Issue by Tronic** [spyder-ide/spyder#11798]
### What steps will reproduce the problem?

First time startup offered to install Kite, which I did, and after that (a) Kite has claimed it cannot find Spyder, and (b) Spyder frequently gives me this issue reporter. Other than the issue reporter appearing, Spyder appears operational. Kite did install and works in VS Code.

### Traceback
```python-traceback
  File "/usr/local/lib/python3.7/site-packages/qtconsole/comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "/usr/local/lib/python3.7/site-packages/qtconsole/comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "/usr/local/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 331, in _comm_message
    msg_dict, buffer)
TypeError: _handle_remote_call_reply() missing 1 required positional argument: 'load_exception'
ERROR:traitlets:Exception in comm_msg for 22301ab066c711ea8566acbc327a2501
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/qtconsole/comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "/usr/local/lib/python3.7/site-packages/qtconsole/comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "/usr/local/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 331, in _comm_message
    msg_dict, buffer)
TypeError: _handle_remote_call_reply() missing 1 required positional argument: 'load_exception'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.6
* Qt version: 5.12.7
* PyQt5 version: 5.12.3
* Operating System: Darwin 19.3.0

### Dependencies

```
applaunchservices >=0.1.7    :  0.2.1 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.9.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.3 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.2 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.8 (OK)
zmq >=17                     :  18.1.0 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.7.0 (OK)
qtconsole >=4.6.0            :  4.7.1 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
sphinx >=0.6.6               :  2.4.3 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.9.0 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.13 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
numpy >=1.7                  :  1.17.3 (OK)
pandas >=0.13.1              :  0.24.2 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
sympy >=0.7.3                :  None (NOK)
```

**Comment by Tronic** [comment]
Solved by installing Spyder via Anaconda, as recommended. I had these issues when pip installing on separate Python 3.7 or Python 3.8 installations.

**Comment by ccordoba12** [comment]
Thanks for understanding. This is a dependency incosistency we easily fixed in Anaconda but we couldn't fix in pip.

Our new version (4.1.0, to be released later today) will fix it.

**Comment by ccordoba12** [comment]
The solution is to downgrade to spyder-kernels 1.8.1 or to use Anaconda.

**Comment by angy87** [comment]
I uninstalled Spyder and then re-installed it via Anaconda. But I have the same warning message about the internal problem (after having accepted to install Kite)
