### ISSUE TITLE
n_jobs = -1 not able to execute.

### ISSUE THREAD

**Issue by gopalchettri** [spyder-ide/spyder#11791]
### What steps will reproduce the problem?

# Evaluating the ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 100)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)

### Traceback
```python-traceback
  File "C:\Users\gopal\.conda\envs\tf-gpu\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\gopal\.conda\envs\tf-gpu\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 252, in _handle_status
    self.set_namespace_view_settings()
  File "C:\Users\gopal\.conda\envs\tf-gpu\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 73, in set_namespace_view_settings
    settings = to_text_string(self.namespacebrowser.get_view_settings())
  File "C:\Users\gopal\.conda\envs\tf-gpu\lib\site-packages\spyder\widgets\variableexplorer\namespacebrowser.py", line 239, in get_view_settings
    settings[name] = getattr(self, name)
AttributeError: 'NamespaceBrowser' object has no attribute 'show_callable_attributes'
  File "C:\Users\gopal\.conda\envs\tf-gpu\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1178, in <lambda>
    kc.started_channels.connect(lambda c=client: self.process_started(c))
  File "C:\Users\gopal\.conda\envs\tf-gpu\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1753, in process_started
    self.variableexplorer.add_shellwidget(client.shellwidget)
  File "C:\Users\gopal\.conda\envs\tf-gpu\lib\site-packages\spyder\plugins\variableexplorer.py", line 171, in add_shellwidget
    nsb.setup(**self.get_settings())
  File "C:\Users\gopal\.conda\envs\tf-gpu\lib\site-packages\spyder\plugins\variableexplorer.py", line 107, in get_settings
    settings[name] = self.get_option(name)
  File "C:\Users\gopal\.conda\envs\tf-gpu\lib\site-packages\spyder\api\plugins.py", line 177, in get_option
    return CONF.get(self.CONF_SECTION, option, default)
  File "C:\Users\gopal\.conda\envs\tf-gpu\lib\site-packages\spyder\config\user.py", line 382, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'show_callable_attributes' in section: 'variable_explorer'
Traceback (most recent call last):
  File "C:\Users\gopal\.conda\envs\tf-gpu\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\gopal\.conda\envs\tf-gpu\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 219, in _handle_execute_reply
    Traceback (most recent call last):
  File "C:\Users\gopal\.conda\envs\tf-gpu\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\gopal\.conda\envs\tf-gpu\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 219, in _handle_execute_reply
    self.set_namespace_view_settings()
  File "C:\Users\gopal\.conda\envs\tf-gpu\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 73, in set_namespace_view_settings
    settings = to_text_string(self.namespacebrowser.get_view_settings())
  File "C:\Users\gopal\.conda\envs\tf-gpu\lib\site-packages\spyder\widgets\variableexplorer\namespacebrowser.py", line 239, in get_view_settings
    settings[name] = getattr(self, name)
AttributeError: 'NamespaceBrowser' object has no attribute 'show_callable_attributes'
self.set_namespace_view_settings()
  File "C:\Users\gopal\.conda\envs\tf-gpu\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 73, in set_namespace_view_settings
    settings = to_text_string(self.namespacebrowser.get_view_settings())
  File "C:\Users\gopal\.conda\envs\tf-gpu\lib\site-packages\spyder\widgets\variableexplorer\namespacebrowser.py", line 239, in get_view_settings
    settings[name] = getattr(self, name)
AttributeError: 'NamespaceBrowser' object has no attribute 'show_callable_attributes'
WARNING:spyder.widgets.github.backend:failed to send bug report on github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
WARNING:spyder.widgets.github.backend:failed to send bug report on github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 4.0.0b1 
* Python version: 3.7.1
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.11.0     :  0.15.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  1.0.1 (OK)
numpy >=1.7       :  1.16.5 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.7.1 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.2.0 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by ccordoba12** [comment]
> Spyder version: 4.0.0b1

This version is very old now. Please update to 4.0.1, our latest.
