### ISSUE TITLE
Segmentation Fault 'NoneType' Object has no attribute 'Split'

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1181]
_From [omga...@gmail.com](https://code.google.com/u/116257162696444437462/) on 2012-10-29T14:39:40Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. Install Spyder dependencies
2. Install Spyder
3. Run Spyder What is the expected output? What do you see instead? I expect the editor to run but it crashes with a segmentation fault. It ends right before it opens the editor. What version of the product are you using? On what operating system? 2.1.11 on Arch Linux

Please provide any additional information below

.Medium

Crash log

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/spyderlib/spyder.py", line 2009, in main
    mainwindow = run_spyder(app, options)
  File "/usr/lib/python2.7/site-packages/spyderlib/spyder.py", line 1921, in run_spyder
    main.setup()
  File "/usr/lib/python2.7/site-packages/spyderlib/spyder.py", line 683, in setup
    self.editor = Editor(self)
  File "/usr/lib/python2.7/site-packages/spyderlib/plugins/editor.py", line 422, in __init__
    self.__load_temp_file()
  File "/usr/lib/python2.7/site-packages/spyderlib/plugins/editor.py", line 1305, in __load_temp_file
    self.load(self.TEMPFILE_PATH)
  File "/usr/lib/python2.7/site-packages/spyderlib/plugins/editor.py", line 1517, in load
    current_es.analyze_script()
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/editor.py", line 1382, in analyze_script
    finfo.run_code_analysis(run_pyflakes, run_pep8)
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/editor.py", line 399, in run_code_analysis
    run_pyflakes = run_pyflakes and codeanalysis.is_pyflakes_installed()
  File "/usr/lib/python2.7/site-packages/spyderlib/utils/codeanalysis.py", line 76, in is_pyflakes_installed
    return programs.is_module_installed('pyflakes', '>='+PYFLAKES_REQVER)
  File "/usr/lib/python2.7/site-packages/spyderlib/utils/programs.py", line 196, in is_module_installed
    actvlist = getvlist(actver)
  File "/usr/lib/python2.7/site-packages/spyderlib/utils/programs.py", line 191, in getvlist
    vl = version.split('.')
AttributeError: 'NoneType' object has no attribute 'split'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1181_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-11-04T09:12:44Z_

This issue was updated by revision 1bc0db739e06 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-11-04T09:14:31Z_

In the meantime, you may check your pyflakes installation which is not standard, apparently.

When pyflakes is properly installed, you should be able to do the following in a Python interpreter:

\>>> import pyflakes
\>>> pyflakes.__version__
'0.5.0'

**Comment by spyder-issues-migrator** [comment]
_From [omga...@gmail.com](https://code.google.com/u/116257162696444437462/) on 2012-11-06T12:52:56Z_

Works beautifully now. Thanks!
