### ISSUE TITLE
completions crashing + unable to remove kite integration

### ISSUE THREAD

**Issue by Craskermasker** [spyder-ide/spyder#11817]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x ] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When I open spyder, the completion crashes as soon as I begin typing. I have tried reinstalling, resetting etc. I have unticked options relating to Kite in the preferences, and uninstalled Kite from my system. However the log indicates that spyder is still seeking autocompletions from Kite and Kite is sending responses (how?). 

autocompletion using pyls works fine using other editors on the same system (vscode)

### What steps reproduce the problem?

1. Open spyder from the command line within base  conda environment - spyder &
2. begin typing

### What is the expected output? What do you see instead?

autocompletions

### Paste Traceback/Error Below (if applicable)

```
2020-03-17 00:02:54,162 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 4 Got response from kite
2020-03-17 00:02:54,163 [DEBUG] [spyder.plugins.completion.fallback.actor] -> Got request id 4: textDocument/cursorEvent for file /home/evan/.config/spyder-py3/temp.py
2020-03-17 00:02:54,393 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 4 timed out
2020-03-17 00:02:55,653 [DEBUG] [spyder.plugins.editor.plugin] -> python completion server request: 'textDocument/didChange'
2020-03-17 00:02:55,658 [DEBUG] [urllib3.connectionpool] -> Starting new HTTP connection (3): 127.0.0.1:46624
2020-03-17 00:02:55,659 [DEBUG] [spyder.plugins.completion.languageserver.client] -> python request: textDocument/didChange
2020-03-17 00:02:55,659 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 5 Got response from kite
2020-03-17 00:02:55,660 [DEBUG] [spyder.plugins.completion.fallback.actor] -> Got request id 5: textDocument/didChange for file /home/evan/.config/spyder-py3/temp.py
2020-03-17 00:02:55,665 [DEBUG] [urllib3.connectionpool] -> Starting new HTTP connection (4): 127.0.0.1:46624
2020-03-17 00:02:55,765 [DEBUG] [spyder.plugins.editor.plugin] -> python completion server request: 'textDocument/didChange'
2020-03-17 00:02:55,769 [DEBUG] [urllib3.connectionpool] -> Starting new HTTP connection (5): 127.0.0.1:46624
2020-03-17 00:02:55,770 [DEBUG] [spyder.plugins.completion.languageserver.client] -> Transport layer for python is down!!
2020-03-17 00:02:55,889 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 5 timed out
2020-03-17 00:02:56,000 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 6 timed out
2020-03-17 00:02:56,075 [DEBUG] [spyder.plugins.editor.plugin] -> python completion server request: 'textDocument/didChange'
2020-03-17 00:02:56,076 [DEBUG] [spyder.plugins.completion.languageserver.client] -> Transport layer for python is down!!
2020-03-17 00:02:56,076 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 7 Got response from kite
2020-03-17 00:02:56,077 [DEBUG] [spyder.plugins.editor.plugin] -> python completion server request: 'textDocument/didChange'
2020-03-17 00:02:56,077 [DEBUG] [spyder.plugins.completion.fallback.actor] -> Got request id 7: textDocument/didChange for file /home/evan/.config/spyder-py3/temp.py
2020-03-17 00:02:56,078 [DEBUG] [spyder.plugins.completion.languageserver.client] -> Transport layer for python is down!!
2020-03-17 00:02:56,078 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 8 Got response from kite
2020-03-17 00:02:56,079 [DEBUG] [spyder.plugins.editor.plugin] -> python completion server request: 'textDocument/completion'
2020-03-17 00:02:56,079 [DEBUG] [spyder.plugins.completion.fallback.actor] -> Got request id 8: textDocument/didChange for file /home/evan/.config/spyder-py3/temp.py
2020-03-17 00:02:56,079 [DEBUG] [spyder.plugins.completion.languageserver.client] -> Transport layer for python is down!!
2020-03-17 00:02:56,080 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 9 Got response from kite
2020-03-17 00:02:56,080 [DEBUG] [spyder.plugins.completion.fallback.actor] -> Got request id 9: textDocument/completion for file /home/evan/.config/spyder-py3/temp.py
Traceback (most recent call last):
  File "/home/evan/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/fallback/actor.py", line 155, in handle_msg
    msg['current_word'])
  File "/home/evan/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/fallback/actor.py", line 62, in tokenize
    valid = is_prefix_valid(text, offset, language)
  File "/home/evan/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/fallback/utils.py", line 122, in is_prefix_valid
    current_pos_text = text[offset - 1]
IndexError: string index out of range
2020-03-17 00:02:56,306 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 7 timed out
2020-03-17 00:02:56,308 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 8 timed out
2020-03-17 00:02:56,310 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 9 timed out
2020-03-17 00:02:56,799 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Added thread <spyder.plugins.editor.widgets.editor.AnalysisThread object at 0x7fe055f129b0> to queue
2020-03-17 00:02:56,850 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Updating queue:
2020-03-17 00:02:56,850 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     started: 0
2020-03-17 00:02:56,850 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     pending: 1
2020-03-17 00:02:56,851 [DEBUG] [spyder.plugins.editor.widgets.editor] -> ===>starting: <spyder.plugins.editor.widgets.editor.AnalysisThread object at 0x7fe055f129b0>
2020-03-17 00:02:56,852 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Updating queue:
2020-03-17 00:02:56,853 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     started: 0
2020-03-17 00:02:56,853 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     pending: 0
2020-03-17 00:02:59,909 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 6 Got response from kite
2020-03-17 00:02:59,909 [DEBUG] [spyder.plugins.completion.fallback.actor] -> Got request id 6: textDocument/didChange for file /home/evan/.config/spyder-py3/temp.py
2020-03-17 00:02:59,919 [DEBUG] [urllib3.connectionpool] -> Starting new HTTP connection (6): 127.0.0.1:46624
^CHandling signal: 2
2020-03-17 00:03:02,829 [DEBUG] [urllib3.connectionpool] -> Starting new HTTP connection (7): 127.0.0.1:46624
2020-03-17 00:03:02,832 [DEBUG] [urllib3.connectionpool] -> Starting new HTTP connection (8): 127.0.0.1:46624
2020-03-17 00:03:02,833 [DEBUG] [spyder.plugins.editor.plugin] -> python completion server request: 'textDocument/didSave'
2020-03-17 00:03:02,834 [DEBUG] [spyder.plugins.completion.languageserver.client] -> Transport layer for python is down!!
2020-03-17 00:03:02,834 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 10 Got response from kite
2020-03-17 00:03:02,836 [DEBUG] [spyder.plugins.completion.fallback.actor] -> Got request id 10: textDocument/didSave for file /home/evan/.config/spyder-py3/temp.py
2020-03-17 00:03:02,853 [INFO] [spyder.plugins.completion.languageserver.plugin] -> Shutting down LSP manager...
2020-03-17 00:03:02,853 [INFO] [spyder.plugins.completion.languageserver.plugin] -> Stopping LSP client for python...
2020-03-17 00:03:02,853 [INFO] [spyder.plugins.completion.languageserver.client] -> Stopping python client...
2020-03-17 00:03:02,853 [DEBUG] [spyder.plugins.completion.kite.client] -> Closing Kite HTTP session...
2020-03-17 00:03:02,854 [DEBUG] [spyder.plugins.completion.fallback.actor] -> Fallback plugin stopping...
```

## Versions

* Spyder version: 4.1.0
* Python version: 3.7.6 64-bit
* Qt version: 5.12.5
* PyQt version: 5.12.3
* Operating System name/version: Ubuntu 19.04 Linux 5.0.0-38-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.14.1                   :  0.14.1 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0          :  0.31.8 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.1 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  19.0.0 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.2 (OK)
numpy >=1.7                    :  1.17.3 (OK)
pandas >=0.13.1                :  0.25.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)
```
![image](https://user-images.githubusercontent.com/3617325/76809166-dbbb2900-67e1-11ea-8912-9a97f60464a7.png)

**Comment by ccordoba12** [comment]
This is an incompatibility between some dependencies of the PyLS. We're working on a fix right now.

**Comment by jguzman-tech** [comment]
Have there been any updates on this? I've tried logging the debug output from spyder and every time I crash the logfile ends with:

```
2021-02-22 09:50:59,457 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 437 Got response from kite
```

How do I work around this? Would turning off autocomplete avoid crashes for me?
