### ISSUE TITLE
Save file error

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1183]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2012-10-29T19:24:30Z_

Spyder Version:  2.1.11
Python Version:  2.7.3
Qt Version:      4.8.3, PyQt4 (API v2) 4.9.5 on Linux 

What steps will reproduce the problem?

 1. create a new file named "toto.py"
2. create another new file and try to save it with the name "toto" (same name but without extension) What is the expected output? What do you see instead? The file should be saved under the name "toto" but instead I get an exception :
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/spyderlib/plugins/editor.py", line 1572, in save
    return editorstack.save(index=index, force=force)
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/editor.py", line 1284, in save
    return self.save_as(index=index)
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/editor.py", line 1349, in save_as
    new_index = self.rename_in_data(index, new_filename=filename)
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/editor.py", line 1077, in rename_in_data
    language = get_file_language(new_filename)
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/sourcecode/codeeditor.py", line 441, in get_file_language
    text, _enc = encoding.read(filename)
  File "/usr/lib/python2.7/site-packages/spyderlib/utils/encoding.py", line 207, in read
    text, encoding = decode( file(filename, 'rb').read() )
IOError: [Errno 2] Aucun fichier ou dossier de ce type: u'/home/joseph/prog/libs.git/python/pamela/toto' 

Please provide any additional information below

. I tried to close the file toto.py before saving, it didn't change anything.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1183_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-11-04T04:08:24Z_

This issue was updated by revision ebd614b0cd42 .

**Status:** Fixed
