### ISSUE TITLE
kernel problem with spyder 4.0.1

### ISSUE THREAD

**Issue by TomislavBak** [spyder-ide/spyder#11830]
### What steps will reproduce the problem?

I updated from spyder3 to spyder 4.0.1 and the kernel stopped working properly

### Traceback
```python-traceback
  File "/usr/local/lib/python3.7/site-packages/qtconsole/comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "/usr/local/lib/python3.7/site-packages/qtconsole/comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "/usr/local/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 331, in _comm_message
    msg_dict, buffer)
TypeError: _handle_remote_call_reply() missing 1 required positional argument: 'load_exception'
ERROR:traitlets:Exception in comm_msg for 91549a16688311ea96db80a5898f8ab5
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/qtconsole/comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "/usr/local/lib/python3.7/site-packages/qtconsole/comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "/usr/local/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 331, in _comm_message
    msg_dict, buffer)
TypeError: _handle_remote_call_reply() missing 1 required positional argument: 'load_exception'
ERROR:traitlets:Exception in comm_msg for 91549a16688311ea96db80a5898f8ab5
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/qtconsole/comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "/usr/local/lib/python3.7/site-packages/qtconsole/comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "/usr/local/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 331, in _comm_message
    msg_dict, buffer)
TypeError: _handle_remote_call_reply() missing 1 required positional argument: 'load_exception'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.5
* Qt version: 5.12.7
* PyQt5 version: 5.12.3
* Operating System: Linux 5.3.15-200.fc30.x86_64

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.1 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.2.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
keyring                      :  None (OK)
nbconvert >=4.0              :  5.4.1 (OK)
numpydoc >=0.6.0             :  0.8.0 (OK)
pexpect >=4.4.0              :  4.6.0 (OK)
pickleshare >=0.4            :  0.7.4 (OK)
psutil >=0.3                 :  5.4.3 (OK)
pygments >=2.0               :  2.2.0 (OK)
pylint >=0.25                :  2.3.1 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.8 (OK)
xdg >=0.26                   :  0.26 (OK)
zmq >=17                     :  17.0.0 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.5.7 (OK)
qtconsole >=4.6.0            :  4.7.1 (OK)
qtpy >=1.5.0                 :  1.8.0 (OK)
sphinx >=0.6.6               :  1.8.4 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.9.0 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  3.0.3 (OK)
numpy >=1.7                  :  1.16.4 (OK)
pandas >=0.13.1              :  0.23.4 (OK)
scipy >=0.17.0               :  1.2.0 (OK)
sympy >=0.7.3                :  None (NOK)
```

**Comment by ccordoba12** [comment]
> spyder_kernels >=1.8.1;<2.0.0:  1.9.0 (OK)

Sorry but this dependency is wrong for your Spyder version. If you don't understand what you're doing, please use Anaconda instead.
