### ISSUE TITLE
Spyder kernel doesn't launch

### ISSUE THREAD

**Issue by ikeijo** [spyder-ide/spyder#11842]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ X] Tried basic troubleshooting (if a bug/error)
    *  [X] Restarted Spyder
    * [ X] Reset preferences with ``spyder --reset``
    * [ X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ X] Tried the other applicable steps from the Troubleshooting Guide
* [ X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Kernel refuses to launch

### What steps reproduce the problem?

1. Launch Kernel
2. 
3. 

### What is the expected output? What do you see instead?

If I restart the kernel it send this message
"Cannot restart a kernel not started by Spyder"

```python-traceback

An error ocurred while starting the kernel
The error is:

Traceback (most recent call last):
File "C:\Users\Eduardo Nagan\anaconda3\envs\gym\lib\site‑packages\spyder\plugins\ipythonconsole\plugin.py", line 1209, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle, **kwargs)
File "C:\Users\Eduardo Nagan\anaconda3\envs\gym\lib\site‑packages\jupyter_client\manager.py", line 267, in start_kernel
self.kernel = self._launch_kernel(kernel_cmd, env=env, **kw)
File "C:\Users\Eduardo Nagan\anaconda3\envs\gym\lib\site‑packages\jupyter_client\manager.py", line 211, in _launch_kernel
return launch_kernel(kernel_cmd, **kw)
File "C:\Users\Eduardo Nagan\anaconda3\envs\gym\lib\site‑packages\jupyter_client\launcher.py", line 135, in launch_kernel
proc = Popen(cmd, **kwargs)
File "C:\Users\Eduardo Nagan\anaconda3\envs\gym\lib\subprocess.py", line 854, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "C:\Users\Eduardo Nagan\anaconda3\envs\gym\lib\subprocess.py", line 1307, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado

**Comment by goanpeca** [comment]
See #11819
