### ISSUE TITLE
Spyder 4.1.0 error starting the kernel after upgrde from 4.0.1

### ISSUE THREAD

**Issue by Boris-Molina** [spyder-ide/spyder#11852]
## Problem Description
After performing the upgrade from 4.0.1 to 4.1.0, when starting up Spyder the intial console will not start. Checking the directory structure, the `scripts` directory seems to be missing:
**anaconda3/lib/python3.7/site‑packages/spyder/plugins/ipythonconsole/scripts**

### What steps reproduce the problem?

1. conda update conda
2. conda update --all  (here new version of spyder installed)
3. spyder 
4. Spyder starts up ok, but the console fails to start a new kernel

### What is the expected output? What do you see instead?
The console shows a red screen with this header "An error ocurred while starting the kernel".  The tradeback below is on the red screen on the console panel.

### Paste Traceback/Error Below (if applicable)
```python-traceback


Traceback (most recent call last):
File "/home/cygnus_x1/anaconda3/lib/python3.7/site‑packages/spyder/plugins/ipythonconsole/plugin.py", line 1209, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle, **kwargs)
File "/home/cygnus_x1/anaconda3/lib/python3.7/site‑packages/jupyter_client/manager.py", line 267, in start_kernel
self.kernel = self._launch_kernel(kernel_cmd, env=env, **kw)
File "/home/cygnus_x1/anaconda3/lib/python3.7/site‑packages/jupyter_client/manager.py", line 211, in _launch_kernel
return launch_kernel(kernel_cmd, **kw)
File "/home/cygnus_x1/anaconda3/lib/python3.7/site‑packages/jupyter_client/launcher.py", line 135, in launch_kernel
proc = Popen(cmd, **kwargs)
File "/home/cygnus_x1/anaconda3/lib/python3.7/subprocess.py", line 800, in __init__
restore_signals, start_new_session)
File "/home/cygnus_x1/anaconda3/lib/python3.7/subprocess.py", line 1551, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cygnus_x1/anaconda3/lib/python3.7/site‑packages/spyder/plugins/ipythonconsole/scripts/conda‑activate.sh': '/home/cygnus_x1/anaconda3/lib/python3.7/site‑packages/spyder/plugins/ipythonconsole/scripts/conda‑activate.sh'

```

## Versions

* Spyder version: 4.1.0
* Python version: Python 3.7.6 64-bit
* Qt version: Qt 5.9.6
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Linux 5.1.15-surface-linux-surface (Ubuntu 18.04)

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.14.1                   :  0.14.1 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0          :  0.31.8 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.1 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.0 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.2 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by goanpeca** [comment]
See #11819
