### ISSUE TITLE
scipy.weave doesn't work in the Mac app

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1186]
_From [hlo...@gmail.com](https://code.google.com/u/111119926317705601201/) on 2012-11-05T13:24:34Z_

Spyder Version:  2.2.0dev
Python Version:  2.7.3
Qt Version:      4.8.2, PyQt4 (API v2) 4.9.4 on Darwin 

What steps will reproduce the problem?

 1. "import scipy.weave" 2. 3. What is the expected output? What do you see instead? no expected output.  but i get

Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/scipy/weave/__init__.py", line 26, in \<module>
    from inline_tools import inline
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/scipy/weave/inline_tools.py", line 5, in \<module>
    import ext_tools
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/scipy/weave/ext_tools.py", line 6, in \<module>
    import build_tools
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/scipy/weave/build_tools.py", line 28, in \<module>
    import platform_info
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/scipy/weave/platform_info.py", line 15, in \<module>
    from numpy.distutils.core import setup
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/numpy/distutils/core.py", line 25, in \<module>
    from numpy.distutils.command import config, config_compiler, \
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/numpy/distutils/command/build_ext.py", line 9, in \<module>
    from distutils.command.build_ext import build_ext as old_build_ext
  File "distutils/command/build_ext.pyo", line 13, in \<module>
ImportError: cannot import name USER_BASE 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1186_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-11-05T12:36:42Z_

I suppose that you have tried to import scipy.weave outside Spyder in a standard Python interpreter?

This sounds like a broken installation of Python, but I'm letting the Mac experts answer because it seems to be related to the dmg packages, isn't it?

See for example this link to get inspiration on how to find out where this problem is coming from: http://www.velocityreviews.com/forums/t731936-numpy-is-not-installed-with-python2.html

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-11-05T12:37:03Z_

**Owner:** ccordoba12  
  **Labels:** OpSys-OSX

**Comment by spyder-issues-migrator** [comment]
_From [hlo...@gmail.com](https://code.google.com/u/111119926317705601201/) on 2012-11-05T14:32:45Z_

\> This sounds like a broken installation of Python

I tend to agree, but unfortunately it is the version of python that shipped with the dmg!  import scipy.weave works on my regular python.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-11-06T07:02:10Z_

It's not really broken. It's just that the app's site.py is missing USER_BASE. The thing is py2app uses its own site.py to bootstrap the app, and it doesn't include several important functions and variables that are encountered in a regular site.py.

Thanks for reporting. I'll try to fix it soon.

**Summary:** scipy.weave doesn't work in the Mac app  
  **Status:** Accepted  
  **Labels:** Cat-Console MS-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-01-27T11:00:11Z_

This issue was updated by revision 6fe6fbe68041 .


- Add some missing and important variables to the app's site.py
- Add distutils to the app because it's needed by weave

**Status:** Fixed
