### ISSUE TITLE
Sypder FileNotFoundError: [Errno 2] No such file or directory: '/home/tito/anaconda3/lib/python3.6/site-packages/jedi-0.16.0.dist-info/METADATA'

### ISSUE THREAD

**Issue by titob23** [spyder-ide/spyder#11878]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/tito/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3024, in _dep_map
    return self.__dep_map
  File "/home/tito/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2818, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

Traceback (most recent call last):
  File "/home/tito/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3015, in _parsed_pkg_info
    return self._pkg_info
  File "/home/tito/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2818, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

Traceback (most recent call last):
  File "/home/tito/anaconda3/lib/python3.6/site-packages/spyder/plugins/editor.py", line 1841, in load
    self.edit_filetypes = get_edit_filetypes()
  File "/home/tito/anaconda3/lib/python3.6/site-packages/spyder/config/utils.py", line 124, in get_edit_filetypes
    supported_exts = _get_pygments_extensions()
  File "/home/tito/anaconda3/lib/python3.6/site-packages/spyder/config/utils.py", line 86, in _get_pygments_extensions
    for lx in lexers.get_all_lexers():
  File "/home/tito/anaconda3/lib/python3.6/site-packages/pygments/lexers/__init__.py", line 57, in get_all_lexers
    for lexer in find_plugin_lexers():
  File "/home/tito/anaconda3/lib/python3.6/site-packages/pygments/plugin.py", line 55, in find_plugin_lexers
    yield entrypoint.load()
  File "/home/tito/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2445, in load
    self.require(*args, **kwargs)
  File "/home/tito/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2468, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/tito/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 795, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/tito/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2739, in requires
    dm = self._dep_map
  File "/home/tito/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3026, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/tito/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3035, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/home/tito/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/home/tito/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1422, in get_metadata
    value = self._get(path)
  File "/home/tito/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1618, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tito/anaconda3/lib/python3.6/site-packages/jedi-0.16.0.dist-info/METADATA'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  2.1.1 (OK)
pycodestyle >=2.3:  2.5.0 (OK)
pygments >=2.0   :  2.6.1 (OK)
pandas >=0.13.1  :  0.23.4 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  2.4.0 (OK)
rope >=0.9.4     :  0.16.0 (OK)
jedi >=0.9.0     :  0.15.2 (OK)
psutil >=0.3     :  5.7.0 (OK)
nbconvert >=4.0  :  5.6.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.7.1 (OK)
IPython >=4.0    :  7.13.0 (OK)
pylint >=0.25    :  2.4.4 (OK)

```

**Comment by titob23** [comment]
I just opened my Spyder application and a few minutes later it spits out this error

**Comment by goanpeca** [comment]
>Spyder Version: 3.2.4

Please update to spyder 3.3 or spyder 4. Your application seems to be very old.

**Comment by ccordoba12** [comment]
Yep, that version is not supported anymore, sorry.
