### ISSUE TITLE
Profiler fails to run due to IOError.

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1187]
_From [haslett....@gmail.com](https://code.google.com/u/102323578032954100914/) on 2012-11-08T06:50:34Z_

Spyder Version:  2.1.11
Python Version:  2.7.3
Qt Version:      4.8.3, PyQt4 (API v1) 4.9.5 on Windows 

What steps will reproduce the problem?

 1. Click the Profile button in the Profiler window. What is the expected output? What do you see instead? When I do so a dialog appears with the title 'Text Editor - Profiler Output'. Within it, the following text is displayed:
Traceback (most recent call last):
  File "D:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "D:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\Python27\lib\cProfile.py", line 199, in \<module>
    main()
  File "D:\Python27\lib\cProfile.py", line 185, in main
    with open(progname, 'rb') as fp:
IOError: [Errno 13] Permission denied: '.' 

Please provide any additional information below

. This problem has manifested itself and gone away previously on my machine. As such, I don't have any idea what the true repro steps are. I appreciate that this is a frustrating issue report but would be happy to investigate further if anyone can suggest a line of enquiry.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1187_

**Comment by spyder-issues-migrator** [comment]
_From [vedran.v...@gmail.com](https://code.google.com/u/107840488341857492640/) on 2012-12-05T05:35:25Z_

You forgot to select the script that you want to profile.
Left of the green profile button is the select script button - use it to select you script, then click profile!

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-12-05T21:59:06Z_

g_haslett, does vedran advice solve the problem for you?

**Labels:** OpSys-Windows

**Comment by spyder-issues-migrator** [comment]
_From [haslett....@gmail.com](https://code.google.com/u/102323578032954100914/) on 2012-12-06T10:38:08Z_

ccordoba2, my profiler is, thankfully, working at present. However, I don't think vedran's solution is the correct one. The reason being that if there is no valid script in the dropdown, the button is greyed out. Feel free to resolve this but I suspect that there is an as yet not understood sequence of UI events that can lead to this scenario.

**Comment by spyder-issues-migrator** [comment]
_From [joostvan...@gmail.com](https://code.google.com/u/107541358853286140082/) on 2012-12-09T14:15:11Z_

Not so helpful error meessage in this case. I've also ran into this issue. Why not simply check if the file exists before trying to execute it, and then give a meaningful warning if it doesn't?

**Comment by spyder-issues-migrator** [comment]
_From [haslett....@gmail.com](https://code.google.com/u/102323578032954100914/) on 2012-12-09T17:00:20Z_

Hi Joost,
Thanks for confirming my original report, however I think there's more to be said here. At present my UI is behaving as it should, that is when I type the name of a non-existent file the path is highlighted in red and a warning message appears.

However, we've both got the editor into a state where the profile button has not been greyed out even the file does not exist.

The question is then, "How did we get into this state?" This is what I can't figure out.

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-12-30T06:10:35Z_

This condition occurs when the Profiler is used for the first time and no edits have been made to the file list. The Profile button is being initialized to the "Enabled" state incorrectly.

I've committed a fix for this in my clone at "jedludlow-issue-1187" here: https://code.google.com/r/jedludlow-spyderlib-default/source/list?name=jedludlow-issue-1187 Pierre, Carlos, please review and pull as appropriate.

**Status:** Accepted  
  **Owner:** jed.lud...@gmail.com  
  **Cc:** ccordoba12 pierre.raybaut

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-01-02T06:18:31Z_

Fixed by revision 2b21c1f0b17b .

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-01-02T06:21:00Z_

This issue was closed by revision 2b21c1f0b17b .

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-01-02T07:21:40Z_

**Status:** Verified  
  **Cc:** -ccordoba12 -pierre.raybaut
