### ISSUE TITLE
Spyder 4.0.1 does not launch from Anaconda on MacOs  

### ISSUE THREAD

**Issue by smaffei** [spyder-ide/spyder#11895]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. Open Anaconda-Navigator
2. Change to the environment I want to open spyder from (with python 3.7.6)
3. Launch spyder 4.0.1 from Anaconda-Navigator

### What is the expected output? What do you see instead?

The expected output is the launch of spyder without issues. Instead an error message appears with the following Traceback:

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
File "/opt/anaconda3/envs/dedalus/bin/spyder", line 11, in 
sys.exit(main())
File "/opt/anaconda3/envs/dedalus/lib/python3.7/site-packages/spyder/app/start.py", line 201, in main
from spyder.app import mainwindow
File "/opt/anaconda3/envs/dedalus/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 167, in 
from spyder.utils.environ import WinUserEnvDialog
File "/opt/anaconda3/envs/dedalus/lib/python3.7/site-packages/spyder/utils/environ.py", line 19, in 
from spyder.plugins.variableexplorer.widgets.collectionseditor import (
File "/opt/anaconda3/envs/dedalus/lib/python3.7/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 57, in 
from spyder.plugins.variableexplorer.widgets.collectionsdelegate import (
File "/opt/anaconda3/envs/dedalus/lib/python3.7/site-packages/spyder/plugins/variableexplorer/widgets/collectionsdelegate.py", line 31, in 
from spyder.plugins.variableexplorer.widgets.objectexplorer.attribute_model \
File "/opt/anaconda3/envs/dedalus/lib/python3.7/site-packages/spyder/plugins/variableexplorer/widgets/objectexplorer/__init__.py", line 19, in 
from .attribute_model import DEFAULT_ATTR_COLS, DEFAULT_ATTR_DETAILS
File "/opt/anaconda3/envs/dedalus/lib/python3.7/site-packages/spyder/plugins/variableexplorer/widgets/objectexplorer/attribute_model.py", line 29, in 
import numpy as np
File "/opt/anaconda3/envs/dedalus/lib/python3.7/site-packages/numpy/__init__.py", line 142, in 
from . import core
File "/opt/anaconda3/envs/dedalus/lib/python3.7/site-packages/numpy/core/__init__.py", line 107, in 
from . import _internal
File "/opt/anaconda3/envs/dedalus/lib/python3.7/site-packages/numpy/core/_internal.py", line 20, in 
IS_PYPY = platform.python_implementation() == 'PyPy'
File "/opt/anaconda3/envs/dedalus/lib/python3.7/platform.py", line 1264, in python_implementation
return _sys_version()[0]
File "/opt/anaconda3/envs/dedalus/lib/python3.7/platform.py", line 1225, in _sys_version
repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.7.6 (default, Jan 8 2020, 13:42:34) \n[Clang 4.0.1 (tags/RELEASE_401/final)]'


```

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.6
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: MacOS 10.14.6

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Please report this problem here:

https://github.com/ContinuumIO/anaconda-issues/issues/

There's nothing we can do about it here.

It could be solved by running in Terminal.app

    conda update python

but I'm not really sure.

**Comment by dukeingreen** [comment]
Please try to uninstall Matplotlib and see if Spyder starts. Also what is the HW you are running?
