### ISSUE TITLE
Spyder 4.11 crashes before opening

### ISSUE THREAD

**Issue by mmusci** [spyder-ide/spyder#11909]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by mmusci** [comment]
What steps will reproduce the problem?**
1 - Open Anaconda Navigator
2 -Launch Spyder 4.11
3 Spyder open and closes after a few seconds

What is the expected output? What do you see instead?**
Expected Spyder to open but it crashes instead.

Please provide any additional information below**
I have tried re-installing many times, update with conda update --all, but neither spyder 4.1 and spyder 4.11 starts, only version 4.01 works

Message from anaconda:
Traceback (most recent call last):
File "d:\Users\mmusc\anaconda3\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "d:\Users\mmusc\anaconda3\lib\site-packages\spyder\app\start.py", line 205, in main
mainwindow.main()
File "d:\Users\mmusc\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3700, in main
mainwindow = run_spyder(app, options, args)
File "d:\Users\mmusc\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3556, in run_spyder
main.setup()
File "d:\Users\mmusc\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1217, in setup
self.apply_shortcuts()
File "d:\Users\mmusc\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3207, in apply_shortcuts
self.help.show_intro_message()
File "d:\Users\mmusc\anaconda3\lib\site-packages\spyder\plugins\help\plugin.py", line 456, in show_intro_message
shortcut_editor, "\n\n", prefs)
TypeError: not enough arguments for format string

Operating system: Windows 10

**Comment by mmusci** [comment]
What steps will reproduce the problem?**
1 - Open Anaconda Navigator
2 -Launch Spyder 4.11
3 Spyder open and closes after a few seconds

What is the expected output? What do you see instead?**
Expected Spyder to open but it crashes instead.

Please provide any additional information below**
I have tried re-installing many times, update with conda update --all, but neither spyder 4.1 and spyder 4.11 starts, only version 4.01 works

Message from anaconda:
Traceback (most recent call last):
File "d:\Users\mmusc\anaconda3\Scripts\spyder-script.py", line 10, in
sys.exit(main())
File "d:\Users\mmusc\anaconda3\lib\site-packages\spyder\app\start.py", line 205, in main
mainwindow.main()
File "d:\Users\mmusc\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3700, in main
mainwindow = run_spyder(app, options, args)
File "d:\Users\mmusc\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3556, in run_spyder
main.setup()
File "d:\Users\mmusc\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1217, in setup
self.apply_shortcuts()
File "d:\Users\mmusc\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3207, in apply_shortcuts
self.help.show_intro_message()
File "d:\Users\mmusc\anaconda3\lib\site-packages\spyder\plugins\help\plugin.py", line 456, in show_intro_message
shortcut_editor, "\n\n", prefs)
TypeError: not enough arguments for format string

Operating system: Windows 10

**Comment by ccordoba12** [comment]
Please the Anaconda Prompt and run there

    spyder --reset

That should fix your problem.

**Comment by mmusci** [comment]
Thank you
