### ISSUE TITLE
Inconsistent behaviour of the Editor on code completion and object introspection

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1191]
_From [grg2...@gmail.com](https://code.google.com/u/102636238100903575646/) on 2012-11-12T13:21:47Z_

Spyder Version:  2.1.10
Python Version:  2.7.1 
Qt Version:      4.7.2, PyQt4 (API v1) 4.8.3 on Linux
pyflakes Version:0.4.0 
rope Version:    0.9.2

Hello Spyder community,

I have my problems using the code completion and the object inspection. In some instances, all works fine while in others it just doesn't.

\### case 1) code completion works, but object inspector fails

editor:
enter "import sci" hit alt+space, and autocompletion shows "scipy"
enter "scipy.randn(" the object inspector will automatically show the function description
enter "scipy.absolute(" nothing happens

console:
enter "scipy.absolute(" works fine.

\### case 2) code completion works, introspection too, but object inspection doesn't pick it up

editor:
enter "import matplotlib.pyplot"
enter "matplotlib.pyplot.plot(" I get the code completion while I type, but the object inspector does not show the function description. Inspection somehow works because I get the small yellow hint window in the editor

console:
enter "import matplotlib.pyplot"
enter "matplotlib.pyplot.plot" and it works. Object inspector does what it should

\### case 3) nothing works

editor:
enter "a = scipy.float32(2)
enter "a." code completion pops up
enter "b = scipy.array(2)"
enter "b." no code completion

another example in the editor:
enter "import matplotlib.pyplot" I get code completion as I type
enter "f = matplotlib.pyplot.figure()" I get code completion as I type
enter "f." and nothing comes up. Neither the object inspector which worked one line earlier, nor code completion.

if this is not a bug but for some reason expected behavior, can somebody explain me what and why it is happening and what the underlying differences in the cases here are?

Thanks, Georg

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1191_

**Comment by spyder-issues-migrator** [comment]
_From [Adam.Mar...@gmail.com](https://code.google.com/u/109021132482174210438/) on 2013-01-08T22:16:12Z_

Yes I've seen some funky behavior.  In particular, in the editor, typing:

np.

causes the dropdown box of code completions to appear.  So then I pick np.random.  But if I type

np.random.

You'd expect a dropdown box, but you get nothing.  It's like the Spyder version of intellisense doesn't hand more than one level deep...

**Comment by spyder-issues-migrator** [comment]
_From [grg2...@gmail.com](https://code.google.com/u/102636238100903575646/) on 2013-02-13T02:05:32Z_

I can reproduce all of the above in the beta 2.2
If this is more of an user issue, should I post it on the mailing list?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-13T08:33:50Z_

I'm working on all these issues and they're going to be fixed for 2.2.

Please don't post them to the list, they are well know to us.

**Summary:** Inconsistent behaviour of the Editor on code completion and object introspection  \<span class="oldvalue"> (was: Inconsistent behaviour of code completion and object introspection) \</span>  
  **Status:** Accepted  
  **Owner:** ccordoba12  
  **Labels:** Cat-Editor MS-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-13T08:37:44Z_

issue #1247 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-13T08:56:54Z_

issue #1153 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-13T09:07:27Z_

issue #1113 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-13T09:19:10Z_

issue #972 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [anatoliy...@gmail.com](https://code.google.com/u/101136359641652000647/) on 2013-02-13T11:51:00Z_

There is one more usecase that relates to this:  I tried developing a django project in python.  If you use Spyder to run Django's manage.py, with argument 'shell' (equivalent to the usual python manage.py shell ), it displays an iPython console, but code completion works only occasionally.  If you are unfamiliar with Django, this takes a bit of effort to replicate, so hopefully this is not a special case.  Could I try a patch when it's available?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-22T08:14:36Z_

This issue was updated by revision ae31c497d9cd .

**Status:** Started

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-22T08:14:36Z_

This issue was updated by revision 5739072f664d .


- This will let the user to view the object's docstring in the Object Inspector,
even if it's not possible to grab its signature.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-22T08:14:38Z_

This issue was updated by revision e75a44b270ba .

Update issue #1272 - This will fix missing code completions and speed issues with them for the most
important scientific and gui modules.

**Comment by spyder-issues-migrator** [comment]
_From [grg2...@gmail.com](https://code.google.com/u/102636238100903575646/) on 2013-02-25T02:12:09Z_

Ccordoba, thanks for looking into the issue. However, even with your fix I am still able to reproduce all of the issues mentioned in my first post.

For me, this is currently the biggest issue in using Spyder as I often have to switch to a console with ipython for code introspection. Apart from that, the 2.2 version is really great. I am working in the Neuroscience field, and historically lots of data analysis is based in Matlab. People are migrating slowly to Python, but the need of a IDE that rivals Matlab is paramount. I think Spyder is on the very best track, but some glitches in the functionality still keep people from using it. Please keep up the good work!

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-25T07:34:12Z_

Hi Georg, thanks for your kind words. We're really working to provide the best Python scientific IDE out there. And thanks too for testing my changes! :)

First, please check that you have two files called 'rootmodules' and 'submodules', inside your ~/.spyder2/db/ directory.


Then let's check your cases one by one:

Case 1
\------
It's working perfectly fine for me now. The object inspector is called after

"scipy.absolute("

Case 2
\------
Working for me now too, i.e. typing

"matplotlib.pyplot.plot("

shows plot docstring on the Object Inspector.

Case 3
\------
Not solved by my changes. I did a little research and it seems hard or even impossible to fix it. That's because of Python dynamic nature, which makes hard to do code completion on objects defined dynamically. But I have to investigate further to see if there is anything we can do about it.

**Comment by spyder-issues-migrator** [comment]
_From [anatoliy...@gmail.com](https://code.google.com/u/101136359641652000647/) on 2013-02-28T00:20:15Z_

Hi,

I just downloaded beta3, and all the problematic behaviors are still present for me.  For example typing in the editor

import numpy as np
np.abs(

will not produce help in the object inspector.

My .spyder2/db folder only has a submodules file, not a modules file.  I did spyder --reset, but it did not help.  I will try reinstalling spyder from scratch now, but I am not optimistic.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-28T03:39:25Z_

np.abs( is working fine for me, both on Linux and Windows. Please open the submodules file (it's a simple text file), and check that its first lines look like this:

(lp1
S'numpy'
p2
aS'numpy.__config__'
p3
aS'numpy._import_tools'
p4
aS'numpy.add_newdocs'
p5
aS'numpy.compat'

**Comment by spyder-issues-migrator** [comment]
_From [anatoliy...@gmail.com](https://code.google.com/u/101136359641652000647/) on 2013-02-28T03:48:31Z_

That's exactly how it looks.  I have no 'modules' file there.  Could that be the issue?  What else can I do to help diagnose?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-03-05T12:48:30Z_

@-anatoliy: There is no 'modules' file created by us. There are only 'rootmodules' and 'submodules', so I think you're fine. I think you could have an installation problem. What happens if you download and unzip beta3, cd (with a terminal) into the unzipped dir and then write:

python bootstrap.py

to start Spyder?

**Comment by spyder-issues-migrator** [comment]
_From [anatoliy...@gmail.com](https://code.google.com/u/101136359641652000647/) on 2013-03-05T23:03:39Z_

Afraid not.  I don't have a 'rootmodules' either, only a 'submodules'  When launching through bootstrap, I get the same behavior:  np.add( in an editor window does not call introspection.

My numpy is in /usr/lib/python2.7/dist-packages/numpy , and my OpenCV bindings are in/usr/local/lib/python2.7/dist-packages$ 

anatoliy@ubuntu:~/Downloads/spyder-2.2.0beta3$ python bootstrap.py
Executing Spyder from source checkout
Revision None:None, Branch: None
01. Patched sys.path with /home/anatoliy/Downloads/spyder-2.2.0beta3
02. No PySide detected, using PyQt4 if available
03. Imported Spyder 2.2.0beta3
    [Python 2.7.3 64bits, Qt 4.8.2, PyQt4 (API v1) 4.9.3 on Linux]
0x. Enforcing parent console (Windows only)
04. Executing spyder.main()
[1]+  Done                    spyder  (wd: ~)
(wd now: ~/Downloads/spyder-2.2.0beta3)
anatoliy@ubuntu:~/Downloads/spyder-2.2.0beta3$

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-03-06T09:30:53Z_

'rootmodules' is automatically generated when try to do an import completion, something like:

import num<Ctrl+Space>

but its presence or absence doesn't affect the fact that 'np.add(' is not showing you its docstring. But at least are you seeing its calltip? (i.e the little yellow box with its signature).


What happens if hit Ctrl+I after np.add, like this:

np.add<Ctrl+I>


Also, what happens if you reset your settings with:

python bootstrap.py -- --reset

and try again?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-03-09T20:08:15Z_

This issue was updated by revision 74d4e2b3abdb .

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-03-09T20:11:31Z_

@-anatoliy: I think my latest commit fixes your problem. Could you use mercurial to test our repo and try again? Thanks.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-03-12T08:30:25Z_

@-anatoliy: I consider this fixed because I was able to reproduce your problem and provided a solution. Please post a new comment if still this isn't the case for you.

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [anatoliy...@gmail.com](https://code.google.com/u/101136359641652000647/) on 2013-03-14T04:05:51Z_

I entered a long comment about how it is not fixed on my machine in beta4, but I can't see it now.  Hopefully it is on a Google server somewhere, but I can't see it yet.  Anyway, I launched beta4 a few more times, and sometimes it simply would not launch, and once it gave me this error:  

sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/spyder", line 27, in \<module>
    from spyderlib import spyder
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/spyder.py", line 136, in \<module>
    CWD = os.getcwd()
OSError: [Errno 2] No such file or directory
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 68, in apport_excepthook
    binary = os.path.realpath(os.path.join(os.getcwd(), sys.argv[0]))
OSError: [Errno 2] No such file or directory

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/spyder", line 27, in \<module>
    from spyderlib import spyder
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/spyder.py", line 136, in \<module>
    CWD = os.getcwd()
OSError: [Errno 2] No such file or directory

[1]+  Exit 1                  spyder
anatoliy@ubuntu:~/Downloads/spyder-2.2.0beta4$ 

This is on an installed launch, not bootstrap.
