### ISSUE TITLE
cant launch spyder

### ISSUE THREAD

**Issue by raytzal** [spyder-ide/spyder#11932]
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3718, in main
mainwindow = run_spyder(app, options, args)
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3559, in run_spyder
main.setup()
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 955, in setup
self.editor = Editor(self)
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 178, in __init__
self.autosave.try_recover_from_autosave()
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 176, in try_recover_from_autosave
files_to_recover, pidfiles = self.get_files_to_recover()
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 149, in get_files_to_recover
txt_as_dict = ast.literal_eval(txt)
File "C:\ProgramData\Anaconda3\lib\ast.py", line 46, in literal_eval
node_or_string = parse(node_or_string, mode='eval')
File "C:\ProgramData\Anaconda3\lib\ast.py", line 35, in parse
return compile(source, filename, mode, PyCF_ONLY_AST)
File "", line 0

^
SyntaxError: unexpected EOF while parsing

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=4.1.1

**Comment by raytzal** [comment]
Hi

i did it but still the same error.

thank you

rechela

‫בתאריך יום ב׳, 23 במרץ 2020 ב-17:45 מאת ‪Carlos Cordoba‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by ccordoba12** [comment]
You probably didn't update correctly because I can assure you that bug is fixed already.
