### ISSUE TITLE
image not responding

### ISSUE THREAD

**Issue by krshashank963** [spyder-ide/spyder#11952]
### What steps will reproduce the problem?

import cv2
from PIL import ImageGrab 

img = ImageGrab.grab(bbox=(0, 0, 512, 512))
cv2.imshow('image', img)

### Traceback
```python-traceback
  File "C:\Users\SHASHANK RAJPUT\Anaconda3\lib\site-packages\qtconsole\comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\SHASHANK RAJPUT\Anaconda3\lib\site-packages\qtconsole\comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\SHASHANK RAJPUT\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 331, in _comm_message
    msg_dict, buffer)
TypeError: _handle_remote_call_reply() missing 1 required positional argument: 'load_exception'
ERROR:traitlets:Exception in comm_msg for 4b7100426dbd11eab3fc30d16bef5148
Traceback (most recent call last):
  File "C:\Users\SHASHANK RAJPUT\Anaconda3\lib\site-packages\qtconsole\comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\SHASHANK RAJPUT\Anaconda3\lib\site-packages\qtconsole\comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\SHASHANK RAJPUT\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 331, in _comm_message
    msg_dict, buffer)
TypeError: _handle_remote_call_reply() missing 1 required positional argument: 'load_exception'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SHASHANK RAJPUT\Anaconda3\lib\site-packages\qtconsole\comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\SHASHANK RAJPUT\Anaconda3\lib\site-packages\qtconsole\comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\SHASHANK RAJPUT\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 331, in _comm_message
    msg_dict, buffer)
TypeError: _handle_remote_call_reply() missing 1 required positional argument: 'load_exception'
```

## Versions

* Spyder version: 4.0.0 
* Python version: 3.7.5
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.3.0 (OK)
pygments >=2.0               :  2.6.1 (OK)
qtconsole >=4.6.0            :  4.7.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.4.4 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.7.0 (OK)
qtawesome >=0.5.7            :  0.7.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  19.0.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.9.0 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.5.1 (OK)
cython >=0.21                :  0.29.15 (OK)
IPython >=4.0                :  7.13.0 (OK)
matplotlib >=2.0.0           :  3.2.1 (OK)
pandas >=0.13.1              :  1.0.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
scipy >=0.17.0               :  1.1.0 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.9 (OK)
rtree >=0.8.3                :  0.9.4 (OK)
```

**Comment by goanpeca** [comment]
Please update to the latest version of Spyder 4

**Comment by ccordoba12** [comment]
This is fixed in our latest version (4.1.1). Please update by opening the Anaconda Prompt and running there

    conda install spyder=4.1.1

**Comment by krshashank963** [comment]
Thank you it works

**Comment by willim420** [comment]
same issue happening on newest version of spyder
