### ISSUE TITLE
Spyder: Kernel not loading and shows error

### ISSUE THREAD

**Issue by arun1997** [spyder-ide/spyder#11992]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
An error ocurred while starting the kernel The error is:
 Traceback (most recent call last): File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole\plugin.py", line 1209, in create_kernel_manager_and_kernel_client kernel_manager.start_kernel(stderr=stderr_handle, **kwargs) File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 301, in start_kernel kernel_cmd, kw = self.pre_start_kernel(**kw) File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 248, in pre_start_kernel self.write_connection_file() File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 474, in write_connection_file kernel_name=self.kernel_name File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 138, in write_connection_file with secure_write(fname) as f: File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 112, in __enter__ return next(self.gen) File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_core\paths.py", line 424, in secure_write win32_restrict_file_to_user(fname) File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_core\paths.py", line 359, in win32_restrict_file_to_user import win32api ImportError: DLL load failed: The specified procedure could not be found.

**Comment by ccordoba12** [comment]
Please remove and reinstall Anaconda. It is broken.

**Comment by arun1997** [comment]
> Please remove and reinstall Anaconda. It is broken.

Hi could you be more specific as I have tried uninstalling and reinstalling several times and tried various versions too but I am getting the same issue.

**Comment by ccordoba12** [comment]
Ok, then this is not a problem with Spyder. Please report it here:

https://github.com/ContinuumIO/anaconda-issues/issues/

**Comment by arun1997** [comment]
> Ok, then this is not a problem with Spyder. Please report it here:
> 
> https://github.com/ContinuumIO/anaconda-issues/issues/

Hi Cordoba,
Have sorted it out, there was an old instance of Python installed and removed it manually which solved the issue. Thanks for the reply though.

**Comment by ccordoba12** [comment]
This is not a problem with Spyder. Please report it here:

https://github.com/ContinuumIO/anaconda-issues/issues/
