### ISSUE TITLE
BrokenProcessPool: A process in the process pool was terminated abruptly [Spyder]

### ISSUE THREAD

**Issue by SA800029** [spyder-ide/spyder#11996]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Problem is described at the following StackOverflow post and I was invited to raise the issue here :
https://stackoverflow.com/questions/60571344/brokenprocesspool-a-process-in-the-process-pool-was-terminated-abruptly-spyder

### What steps reproduce the problem?

1. When I use the run button to execute the code I got the : BrokenProcessPool message
2. If i execute the code manually by section (using selct and F9) it sometimes works and sometimes don't.

### What is the expected output? What do you see instead?

When it works, everything works as expected, the main problem is the inconsistency, eventhough nothing was added or removed in the code I don't understand what cause the erratic behaviour.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):

  File "<ipython-input-4-268ffa352430>", line 46, in <module>
    main()

  File "<ipython-input-4-268ffa352430>", line 34, in main
    results = [ff.result() for ff in futures]

  File "<ipython-input-4-268ffa352430>", line 34, in <listcomp>
    results = [ff.result() for ff in futures]

  File "C:\Users\B0540002\AppData\Local\Continuum\anaconda3\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()

  File "C:\Users\B0540002\AppData\Local\Continuum\anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception

BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

```

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 

### Dependencies

```
scipy 1.4.1
numpy 1.18.1
pandas 1.0.1
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll try to take a look at this in the next months.
