### ISSUE TITLE
Break the IPython console by accident 

### ISSUE THREAD

**Issue by openmindednewby** [spyder-ide/spyder#12006]
### What steps will reproduce the problem?

#Just run this code in spyder4.  I have just come accross this problem however its nothing urgent 

```python
import threading



# get user input and controll other functions
def user_comand_and_control_input():
    #global USER_INPUT
    while True:
        USER_INPUT = input('Command me: ') # GET USER input
        print('USER_INPUT is now set to: ' + str(USER_INPUT)) # confim action
        if USER_INPUT == 'T': # triger to shut down this function
            print('user_comand_and_control_input will now terminate since USER_INPUT = T')
            return USER_INPUT
            break
        else:
            pass
    print('user_comand_and_control_input ENDED WITHOUGHT USER_INPUT = T')
    return USER_INPUT
        

#  function to control
def testttt():
    global count
    count = 0 
    while True:
        user_input = user_comand_and_control_input()
        if user_input == '1': # if 1 is detected in the input 
            count = count +1 # do something
            print(str(count)) # confirmation that the process is done
        elif user_input == 'TT':
            print('Function testttt has terminated')
            return None
            break
        else:
            pass
        

#t1 = threading.Thread(target=user_comand_and_control_input)
t2 = threading.Thread(target=testttt)

#t1.start()
t2.start()
user_comand_and_control_input()
```

### Traceback
```python-traceback
  File "/media/god/9c72f9bb-20f1-4b7b-8a9e-01f045898c0e/god/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/media/god/9c72f9bb-20f1-4b7b-8a9e-01f045898c0e/god/anaconda3/lib/python3.7/site-packages/jupyter_client/threaded.py", line 93, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/media/god/9c72f9bb-20f1-4b7b-8a9e-01f045898c0e/god/anaconda3/lib/python3.7/site-packages/jupyter_client/session.py", line 923, in deserialize
    raise ValueError("Invalid Signature: %r" % signature)
ValueError: Invalid Signature: b'0d43bc23cc28c277dda36c5780f98d3a46ccb6eee8efdacc5c4b8d264cbc69d8'
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/media/god/9c72f9bb-20f1-4b7b-8a9e-01f045898c0e/god/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/media/god/9c72f9bb-20f1-4b7b-8a9e-01f045898c0e/god/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/media/god/9c72f9bb-20f1-4b7b-8a9e-01f045898c0e/god/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/media/god/9c72f9bb-20f1-4b7b-8a9e-01f045898c0e/god/anaconda3/lib/python3.7/site-packages/jupyter_client/threaded.py", line 93, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/media/god/9c72f9bb-20f1-4b7b-8a9e-01f045898c0e/god/anaconda3/lib/python3.7/site-packages/jupyter_client/session.py", line 923, in deserialize
    raise ValueError("Invalid Signature: %r" % signature)
ValueError: Invalid Signature: b'0d43bc23cc28c277dda36c5780f98d3a46ccb6eee8efdacc5c4b8d264cbc69d8'
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(110, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(110, 1)>
Traceback (most recent call last):
  File "/media/god/9c72f9bb-20f1-4b7b-8a9e-01f045898c0e/god/anaconda3/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/media/god/9c72f9bb-20f1-4b7b-8a9e-01f045898c0e/god/anaconda3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 143, in _handle_events
    handler_func(fileobj, events)
  File "/media/god/9c72f9bb-20f1-4b7b-8a9e-01f045898c0e/god/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/media/god/9c72f9bb-20f1-4b7b-8a9e-01f045898c0e/god/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/media/god/9c72f9bb-20f1-4b7b-8a9e-01f045898c0e/god/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/media/god/9c72f9bb-20f1-4b7b-8a9e-01f045898c0e/god/anaconda3/lib/python3.7/site-packages/jupyter_client/threaded.py", line 93, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/media/god/9c72f9bb-20f1-4b7b-8a9e-01f045898c0e/god/anaconda3/lib/python3.7/site-packages/jupyter_client/session.py", line 923, in deserialize
    raise ValueError("Invalid Signature: %r" % signature)
ValueError: Invalid Signature: b'0d43bc23cc28c277dda36c5780f98d3a46ccb6eee8efdacc5c4b8d264cbc69d8'
WARNING:traitlets:kernel restarted
WARNING:traitlets:kernel died: 18.017195224761963
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 5.0.0-38-generic

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
keyring                      :  None (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
xdg >=0.26                   :  0.26 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.7.0 (OK)
qtconsole >=4.6.0            :  4.7.1 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
Does this problem happen if you open a new console and run your code there?

**Comment by openmindednewby** [comment]
Em yes:).

**Comment by ccordoba12** [comment]
I tried this and it's true that it generates the error you posted above. However, as you can see, there's not a single line of Spyder code in that error, so there's nothing we can do about it

Furthermore, the same error is generated in qtconsole, something that we require for users to test in our issue template and you didn't bother to do. My guess is that you can't call `input` in different threads in the Jupyter architecture.

Finally, if you want to see this fixed or have more feedback about it, please report it here instead:

https://github.com/jupyter/jupyter_client
