### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by DhudiOmkar** [spyder-ide/spyder#12013]
### What steps will reproduce the problem?

Traceback (most recent call last):
File "C:\Users\domkar\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\domkar\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\domkar\AppData\Local\Continuum\anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\domkar\AppData\Local\Continuum\anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 287, in main
import_spydercustomize()
File "C:\Users\domkar\AppData\Local\Continuum\anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 39, in import_spydercustomize
import spydercustomize
File "C:\Users\domkar\AppData\Local\Continuum\anaconda3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 27, in 
from IPython.core.getipython import get_ipython
File "C:\Users\domkar\AppData\Local\Continuum\anaconda3\lib\site‑packages\IPython\__init__.py", line 54, in 
from .core.application import Application
File "C:\Users\domkar\AppData\Local\Continuum\anaconda3\lib\site‑packages\IPython\core\application.py", line 23, in 
from traitlets.config.application import Application, catch_config_error
File "C:\Users\domkar\AppData\Local\Continuum\anaconda3\lib\site‑packages\traitlets\config\__init__.py", line 6, in 
from .application import *
File "C:\Users\domkar\AppData\Local\Continuum\anaconda3\lib\site‑packages\traitlets\config\application.py", line 10, in 
import json
File "C:\Users\domkar\json.py", line 37
return list(name=self.table_name, type = "datatable", path = filename=self.filename,
^
SyntaxError: invalid syntax

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.5 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by DhudiOmkar** [comment]
IPython >=4.0     :  7.8.0 (OK)
cython >=0.21     :  0.29.13 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
numpy >=1.7       :  1.16.5 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.4.2 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
sympy >=0.7.3     :  1.4 (OK)


![image](https://user-images.githubusercontent.com/36674807/77737494-1a4bb180-7034-11ea-9e6b-52be73aae5c3.png)

**Comment by ccordoba12** [comment]
Please remove or rename this file

    C:\Users\domkar\json.py

The problem is that file has the same name of the `json` Python module, so it's interfering with it.
