### ISSUE TITLE
Spyder crashed during last session

### ISSUE THREAD

**Issue by RodriM11** [spyder-ide/spyder#12022]
### Issue Report Checklist

* [ X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [X ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X ] Tried basic troubleshooting (if a bug/error)
    * [X ] Restarted Spyder
    * [X ] Reset preferences with ``spyder --reset``
    * [X ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X ] Tried the other applicable steps from the Troubleshooting Guide
* [X ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I try to run spyder but I always get the same error: Spyder crashe during last session.I have tried everything, even unistalling the whole Anaconda package and still get the same result

### What steps reproduce the problem?

1. 
2. 
3. 

### What is the expected output? What do you see instead?

A pop up message telling that Spydeer crashed during last session

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "C:\Users\RodriM11\anaconda3\lib\site-packages\spyder\utils\external\github.py", line 51, in <module>
    from urllib2 import build_opener, HTTPSHandler, Request, HTTPError
ModuleNotFoundError: No module named 'urllib2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RodriM11\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\RodriM11\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3559, in run_spyder
    main.setup()
  File "C:\Users\RodriM11\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 908, in setup
    from spyder.plugins.console.plugin import Console
  File "C:\Users\RodriM11\anaconda3\lib\site-packages\spyder\plugins\console\plugin.py", line 39, in <module>
    from spyder.widgets.reporterror import SpyderErrorDialog
  File "C:\Users\RodriM11\anaconda3\lib\site-packages\spyder\widgets\reporterror.py", line 28, in <module>
    from spyder.widgets.github.backend import GithubBackend
  File "C:\Users\RodriM11\anaconda3\lib\site-packages\spyder\widgets\github\backend.py", line 36, in <module>
    from spyder.utils.external import github
  File "C:\Users\RodriM11\anaconda3\lib\site-packages\spyder\utils\external\github.py", line 59, in <module>
    from urllib.request import build_opener, HTTPSHandler, HTTPError, Request
ImportError: cannot import name 'HTTPSHandler' from 'urllib.request' (C:\Users\RodriM11\anaconda3\lib\urllib\request.py)

```

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.6
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
It looks like your Anaconda is broken. Please remove it and reinstall it to fix this problem.

**Comment by RodriM11** [comment]
I did that and it still happens
