### ISSUE TITLE
no me permite ver la variabl en un dataframe

### ISSUE THREAD

**Issue by juanma8anav** [spyder-ide/spyder#12079]
### What steps will reproduce the problem?

corregir los procesos para convertir una variable a variable ade tiempo para que sea mostrado en ese formtamo

### Traceback
```python-traceback
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 316, in data
      File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.5 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by ccordoba12** [comment]
Duplicate of #11790

**Comment by ccordoba12** [comment]
We'll try to fix it in the next weeks.
