### ISSUE TITLE
Switching from extrenal monitor to laptop display

### ISSUE THREAD

**Issue by XtremeNova** [spyder-ide/spyder#12222]
### What steps will reproduce the problem?

External monitor and Laptop display at HD resolution 1920x1080. Spyder located on external display.
External monitor switches off due to power saving, Spyder goes to laptop monitor = crash

### Traceback
```python-traceback
  File "/usr/local/lib/python3.7/dist-packages/spyder/app/mainwindow.py", line 1393, in handle_new_screen
    self.show_dpi_change_message)
TypeError: 'method' object is not connected
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/spyder/app/mainwindow.py", line 1393, in handle_new_screen
    self.show_dpi_change_message)
TypeError: 'method' object is not connected
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/spyder/app/mainwindow.py", line 1393, in handle_new_screen
    self.show_dpi_change_message)
TypeError: 'method' object is not connected
```

## Versions

* Spyder version: 4.1.1 
* Python version: 3.7.3
* Qt version: 5.12.4
* PyQt5 version: 5.12.3
* Operating System: Linux 5.0.0-38-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.2.2 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.8.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.0 (OK)
numpydoc >=0.6.0               :  0.9.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.6.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.3 (OK)
pygments >=2.0                 :  2.4.2 (OK)
pylint >=0.25                  :  2.4.1 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.6.0 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  2.2.0 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  18.1.0 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.1 (OK)
numpy >=1.7                    :  1.17.2 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
Fixed in our 4.1.2 version. Please update.
