### ISSUE TITLE
Spyder launch error (Anaconda)

### ISSUE THREAD

**Issue by Martin-Lacroix** [spyder-ide/spyder#12223]
###  Problem Description

After encountering some problems launching Spyder with WinPython, I installed Anaconda in order to use Spyder 4. The installation ended normally, however I receive an error when launching Spyder in the Anaconda Navigator. I tried to uninstall/install Anaconda, uninstall/install Spyder, reset Spyder, but the the problem persists. In addition, Spyder is the only program in the navigator encountering this issue, I can launch the other programs without problems.

### What steps reproduce the problem?

1.  Clean everything related to Anaconda/Spyder
2.  Install Anaconda
3.  Launch Spyder 4

### What is the expected output?

Spyder 4 launches normally.

### Paste Traceback/Error

```python-traceback

Traceback (most recent call last):
File "C:\Users\ORBBE\anaconda3\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\ORBBE\AppData\Roaming\Python\Python37\site-packages\spyder\app\start.py", line 200, in main
from spyder.app import mainwindow
File "C:\Users\ORBBE\AppData\Roaming\Python\Python37\site-packages\spyder\app\mainwindow.py", line 104, in 
from spyder.app.utils import set_opengl_implementation
File "C:\Users\ORBBE\AppData\Roaming\Python\Python37\site-packages\spyder\app\utils.py", line 23, in 
from spyder.utils.qthelpers import file_uri
File "C:\Users\ORBBE\AppData\Roaming\Python\Python37\site-packages\spyder\utils\qthelpers.py", line 28, in 
from spyder.config.gui import get_shortcut, is_dark_interface
File "C:\Users\ORBBE\AppData\Roaming\Python\Python37\site-packages\spyder\config\gui.py", line 28, in 
from spyder.utils import syntaxhighlighters as sh
File "C:\Users\ORBBE\AppData\Roaming\Python\Python37\site-packages\spyder\utils\syntaxhighlighters.py", line 32, in 
from spyder.config.main import CONF
ImportError: cannot import name 'CONF' from 'spyder.config.main' (C:\Users\ORBBE\AppData\Roaming\Python\Python37\site-packages\spyder\config\main.py)

```

## Versions

* Spyder version: 4.01
* Python version: 3.7.6
* Qt version: 5.9.7
* PyQt version: 4.6.0
* Operating System name/version: Windows 10

### Dependencies

N/A

**Comment by Martin-Lacroix** [comment]
Ok, it seems that removing the folder
`C:\Users\ORBBE\AppData\Roaming\Python`
before re-installing Anaconda fixed the problem, sorry for the inconvenience.

**Comment by hamedvolca** [comment]
It worked for me too; after trying many other things.
