### ISSUE TITLE
When trying to open the preferences dialog box, it just throws an error and nothing happens.

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1223]
_From [sle...@gmail.com](https://code.google.com/u/108618768621230958703/) on 2013-01-14T06:44:42Z_

Spyder Version:  2.1.7
Python Version:  2.7.3
Qt Version:      4.7.3, PySide 1.1.0 on Darwin 

What steps will reproduce the problem?

 1. Select "Tools" menu.
2. Select "Preferences" 
3. It won't open the preferences, and just give a bunch of Traceback in projectexplorer.py What is the expected output? What do you see instead? I should see the preferences' window. Nothing happens, just a Traceback.
Also happens if you try and open it directly from the preferences' button. 

Please provide any additional information below

. Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/spyderlib/spyder.py", line 1632, in edit_preferences
    widget = plugin.create_configwidget(dlg)
  File "/L...

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1223_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-01-26T19:37:03Z_

This is most probably a PySide bug so we can't do anything about it. Please try to update to version 1.1.2, or better still, use instead PyQt or our native App (you can find it under the Downloads sections).

If you continue to have this problem after the solutions I gave you, please reopen the issue or report it to the PySide guys.

**Status:** WontFix

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-01-27T01:04:17Z_

Actually Carlos, this is a known bug occuring in Spyder with PySide due to a different behavior between PySide and PyQt.

It has been fixed last year (in 2.1.10 or 2.1.11).

**Status:** Duplicate  
  **Mergedinto:** 897
