### ISSUE TITLE
UMD will not reload scipy correctly on macports install

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1224]
_From [martijn....@gmail.com](https://code.google.com/u/105702808491802454567/) on 2013-01-14T08:27:00Z_

Spyder Version:  2.1.11
Python Version:  2.7.3
Qt Version:      4.8.4, PyQt4 (API v2) 4.9.6 on Darwin 

What steps will reproduce the problem?

 1. install spyder using macports
2. run script with import of functions in module scipy.signal in current python interpreter (F5)
3. re-run script in same interpreter

Expected output is that UMD reloads scipy (and associated functions). Instead, a ValueError is given.

Example script:

\# -*- coding: utf-8 -*-

import scipy
from scipy.signal import butter

print scipy.version

Output from first run:
\>>> runfile(r'/Users/<username>/Projects/pcm/src/umd_test.py', wdir=r'/Users/<username>/Projects/pcm/src')
\<module 'scipy.version' from '/Library/Python/2.7/site-packages/scipy-0.12.0.dev_ddd617d_20120920-py2.7-macosx-10.8-x86_64.egg/scipy/version.pyc'>

Output from second run:
\>>> runfile(r'/Users/<username>/Projects/pcm/src/umd_test.py', wdir=r'/Users/<username>/Projects/pcm/src')
UMD has deleted: scipy.sparse.linalg.eigen.arpack, scipy.signal.ltisys, scipy.sparse.linalg.isolve.utils, scipy.sparse.construct, scipy.linalg.fblas, scipy.sparse.linalg.dsolve.linsolve, scipy.signal.wavelets, scipy.special.basic, scipy.sparse.linalg.eigen.lobpcg.lobpcg, scipy.stats.stats, scipy.sparse.linalg.isolve._iterative, scipy.linalg.decomp_cholesky, pkg_resources, scipy.optimize._cobyla, scipy.integrate._quadpack, scipy.interpolate.dfitpack, scipy.stats._rank, scipy.linalg.decomp_qr, scipy.sparse.linalg.eigen.arpack.arpack, scipy.fftpack.pseudo_diffs, scipy.stats.kde, scipy.optimize.optimize, scipy.interpolate.polyint, scipy.misc.doccer, scipy.integrate.quadpack, scipy.signal.signaltools, scipy.special.specfun, scipy.sparse.base, scipy.sparse.linalg.isolve.minres, scipy.sparse.sparsetools, scipy.integrate._ode, scipy.spatial.qhull, scipy.linalg.linalg_version, scipy.lib, scipy.linalg.misc, scipy.sparse.compressed, scipy.interpolate.fitpack, scipy.linalg.calc_lwork, scipy.sparse.csgraph._tools, scipy.interpolate, scipy.optimize._root, scipy.optimize._zeros, scipy.stats.mvn, scipy.stats.futil, scipy.sparse.lil, scipy.stats._tukeylambda_stats, scipy.sparse.csgraph, scipy.sparse.dia, scipy.linalg._flinalg, scipy.sparse.sparsetools.dia, scipy.signal.waveforms, scipy.spatial, scipy.sparse.sparsetools.csc, scipy.integrate, _csgraph, scipy.linalg.lapack, scipy.sparse.linalg.isolve.lsqr, scipy.fftpack.basic, scipy.interpolate.fitpack2, scipy.signal, scipy.signal.spline, scipy.interpolate.rbf, scipy.special.lambertw, scipy.sparse.linalg.eigen, scipy.optimize.nonlin, scipy.stats.mstats_extras, scipy.optimize._slsqp, scipy.optimize.zeros, scipy.stats._support, scipy.stats, scipy.linalg.cblas, scipy.special._cephes, scipy.signal.sigtools, scipy.sparse.sparsetools.coo, scipy.sparse.csgraph._components, scipy.stats.vonmises_cython, scipy.stats.morestats, scipy.fftpack.fftpack_version, scipy.sparse.sputils, scipy.optimize._minimize, scipy.lib.decorator, scipy.misc, scipy.sparse.linalg.eigen.lobpcg, _csr, scipy.sparse.data, scipy.linalg.basic, scipy.stats.contingency, scipy.stats.statlib, scipy.sparse.bsr, scipy.sparse.csgraph._laplacian, scipy.spatial.distance, scipy.fftpack._fftpack, scipy.linalg._decomp_qz, scipy.signal.fir_filter_design, _bsr, scipy.signal._arraytools, scipy.optimize.lbfgsb, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.linalg.interface, scipy.sparse.csgraph._validation, scipy.optimize.minpack2, scipy.sparse.linalg.isolve.lgmres, scipy.optimize._nnls, scipy.optimize._minpack, scipy.sparse.sparsetools.csr, scipy.sparse.linalg.isolve, scipy.linalg.clapack, scipy.signal._peak_finding, scipy.sparse.linalg, scipy.signal.spectral, scipy.linalg.special_matrices, scipy.optimize.moduleTNC, scipy.linalg.matfuncs, scipy.spatial.kdtree, scipy.sparse.linalg.dsolve.umfpack, scipy.integrate.vode, scipy.sparse.dok, scipy.fftpack, scipy.sparse.linalg.dsolve._superlu, scipy.special.spfun_stats, scipy.stats.mstats, scipy.signal.bsplines, scipy.interpolate.interpnd, scipy.sparse.linalg.isolve.lsmr, scipy.signal.dltisys, scipy.optimize.linesearch, scipy.linalg._solvers, scipy.special._logit, _csc, scipy.stats.mstats_basic, scipy.linalg.decomp, scipy.sparse.csc, scipy.sparse.csr, scipy.interpolate.ndgriddata, scipy.sparse.sparsetools.bsr, scipy.linalg.flapack, scipy.integrate._dop, scipy.optimize.tnc, scipy.optimize.slsqp, scipy.fftpack.realtransforms, scipy.sparse.csgraph._traversal, scipy.signal.filter_design, scipy.fftpack.convolve, scipy.sparse.linalg.eigen.arpack._arpack, scipy.optimize.nnls, scipy.optimize.cobyla, scipy.signal.cont2discrete, scipy.special.add_newdocs, _dia, scipy.integrate.quadrature, scipy.linalg.flinalg, scipy.spatial.ckdtree, scipy.linalg.decomp_lu, scipy.sparse.csgraph._shortest_path, scipy.sparse.coo, scipy.linalg.blas, scipy.sparse.linalg.dsolve.umfpack.umfpack, scipy.integrate.odepack, _coo, scipy.misc.common, scipy.stats.rv, numpy.dual, scipy.optimize.minpack, scipy.integrate._odepack, scipy.sparse.linalg.dsolve, scipy.stats._binned_statistic, scipy.optimize._lbfgsb, scipy.special.orthogonal, scipy.linalg, scipy.stats.distributions, scipy.linalg.decomp_svd, scipy.optimize, scipy.optimize.anneal, scipy.sparse.linalg.isolve.iterative, scipy.interpolate.interpolate, scipy.sparse, scipy.interpolate._fitpack, scipy.fftpack.helper, scipy.spatial._distance_wrap, scipy.linalg.decomp_schur, scipy.special, scipy.special.orthogonal_eval, scipy.sparse.sparsetools.csgraph, scipy.signal.windows, scipy.sparse.extract
Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 487, in runfile
    execfile(filename, namespace)
  File "/Users/<username>/Projects/pcm/src/umd_test.py", line 9, in \<module>
    from scipy.signal import butter
  File "/Library/Python/2.7/site-packages/scipy-0.12.0.dev_ddd617d_20120920-py2.7-macosx-10.8-x86_64.egg/scipy/signal/__init__.py", line 217, in \<module>
    from bsplines import *
  File "/Library/Python/2.7/site-packages/scipy-0.12.0.dev_ddd617d_20120920-py2.7-macosx-10.8-x86_64.egg/scipy/signal/bsplines.py", line 2, in \<module>
    import scipy.special
  File "/Library/Python/2.7/site-packages/scipy-0.12.0.dev_ddd617d_20120920-py2.7-macosx-10.8-x86_64.egg/scipy/special/__init__.py", line 534, in \<module>
    import add_newdocs
  File "/Library/Python/2.7/site-packages/scipy-0.12.0.dev_ddd617d_20120920-py2.7-macosx-10.8-x86_64.egg/scipy/special/add_newdocs.py", line 33, in \<module>
    """)
ValueError: Cannot change docstring of ufunc with non-NULL docstring

After adding scipy to the exclude list for UMD, issue is no longer apparent (but scipy will not be reloaded).

Perhaps issue is due to the macports install? (some issues with libraries, e.g. scipy?). I didn't have this issue earlier when I was using the DMG install. However,I prefer an install via macports since this makes it easier to include other e...

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1224_

**Comment by spyder-issues-migrator** [comment]
_From [martijn....@gmail.com](https://code.google.com/u/105702808491802454567/) on 2013-01-14T05:44:42Z_

Note that this is not necessarily a generic issue, but just related to my install. Let me know if you'd need any further input (e.g. install-related) from my end.

**Comment by spyder-issues-migrator** [comment]
_From [ebori...@gmail.com](https://code.google.com/u/102672023975932251472/) on 2013-01-14T08:38:20Z_

You might try py27-spyder-devel (2.2.0 snapshot).

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-01-26T19:24:22Z_

Martijn, I think you are just fine adding scipy to the exclude list for UMD. UMD is meant to be used to reload user defined modules not libraries like scipy.

If you have more problems like this one with your own modules, please feel free to reopen this issue.

**Status:** WontFix

**Comment by spyder-issues-migrator** [comment]
_From [martijn....@gmail.com](https://code.google.com/u/105702808491802454567/) on 2013-01-28T00:47:40Z_

@-ebori: thx for the devel snapshot, might try this later.

@-ccordoba12: ok, thx for the feedback. Everything does seem to work fine with my current UMD settings.

**Comment by spyder-issues-migrator** [comment]
_From [sergio.c...@gmail.com](https://code.google.com/u/104661479660248330338/) on 2013-06-10T08:50:34Z_

Same issue here with spyder 2.2.0 on ubuntu linux raring
(with user updated spyderlib, numpy, scipy)
