### ISSUE TITLE
Kite installation fails when launching Spyder

### ISSUE THREAD

**Issue by rmuhumuza** [spyder-ide/spyder#12246]
### What steps will reproduce the problem?

Closing Spyder app and re-launching Spyder app via anaconda navigator.
It seems that your Kite Installation is faulty. If you want to use Kite, please remove the directory that appears bellow, and try a reinstallation:
C:\Program Files\Kite

The below error message also appears in Kite client.log
[kited] 2020/04/09 15:23:25.054036 autoinstall.go:58: error during automatic installation of plugins spyder at C:\Users\Ronald\anaconda3: This error message typically means that you have not run the Spyder IDE once yet. Please start Spyder to enable Kite for Spyder.
[kited] 2020/04/09 15:23:25.056042 autoinstall.go:84: no plugins installed automatically

### Traceback
```python-traceback
  File "C:\Users\Ronald\anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 154, in perform_request
    response = handler(params)
  File "C:\Users\Ronald\anaconda3\lib\site-packages\spyder\plugins\completion\kite\decorators.py", line 20, in wrapper
    params = req(self, *args, **kwargs)
  File "C:\Users\Ronald\anaconda3\lib\site-packages\spyder\plugins\completion\kite\providers\document.py", line 83, in document_did_open
    self.get_status(params['file'])
  File "C:\Users\Ronald\anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 111, in get_status
    kite_status = status()
  File "C:\Users\Ronald\anaconda3\lib\site-packages\spyder\plugins\completion\kite\utils\status.py", line 93, in status
    elif check_if_kite_running():
  File "C:\Users\Ronald\anaconda3\lib\site-packages\spyder\plugins\completion\kite\utils\status.py", line 42, in check_if_kite_running
    'status']):
  File "C:\Users\Ronald\anaconda3\lib\site-packages\psutil\__init__.py", line 1457, in process_iter
    yield add(pid)
  File "C:\Users\Ronald\anaconda3\lib\site-packages\psutil\__init__.py", line 1432, in add
    proc = Process(pid)
  File "C:\Users\Ronald\anaconda3\lib\site-packages\psutil\__init__.py", line 346, in __init__
    self._init(pid)
  File "C:\Users\Ronald\anaconda3\lib\site-packages\psutil\__init__.py", line 373, in _init
    self.create_time()
  File "C:\Users\Ronald\anaconda3\lib\site-packages\psutil\__init__.py", line 723, in create_time
    self._create_time = self._proc.create_time()
  File "C:\Users\Ronald\anaconda3\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
  File "C:\Users\Ronald\anaconda3\lib\site-packages\psutil\_pswindows.py", line 671, in convert_oserror
    raise exc
  File "C:\Users\Ronald\anaconda3\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Ronald\anaconda3\lib\site-packages\psutil\_pswindows.py", line 933, in create_time
    user, system, created = cext.proc_times(self.pid)
OSError: [WinError 0] The operation completed successfully: '(originated from OpenProcess)'
Traceback (most recent call last):
  File "C:\Users\Ronald\anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 154, in perform_request
    response = handler(params)
  File "C:\Users\Ronald\anaconda3\lib\site-packages\spyder\plugins\completion\kite\decorators.py", line 20, in wrapper
    params = req(self, *args, **kwargs)
  File "C:\Users\Ronald\anaconda3\lib\site-packages\spyder\plugins\completion\kite\providers\document.py", line 83, in document_did_open
    self.get_status(params['file'])
  File "C:\Users\Ronald\anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 111, in get_status
    kite_status = status()
  File "C:\Users\Ronald\anaconda3\lib\site-packages\spyder\plugins\completion\kite\utils\status.py", line 93, in status
    elif check_if_kite_running():
  File "C:\Users\Ronald\anaconda3\lib\site-packages\spyder\plugins\completion\kite\utils\status.py", line 42, in check_if_kite_running
    'status']):
  File "C:\Users\Ronald\anaconda3\lib\site-packages\psutil\__init__.py", line 1457, in process_iter
    yield add(pid)
  File "C:\Users\Ronald\anaconda3\lib\site-packages\psutil\__init__.py", line 1432, in add
    proc = Process(pid)
  File "C:\Users\Ronald\anaconda3\lib\site-packages\psutil\__init__.py", line 346, in __init__
    self._init(pid)
  File "C:\Users\Ronald\anaconda3\lib\site-packages\psutil\__init__.py", line 373, in _init
    self.create_time()
  File "C:\Users\Ronald\anaconda3\lib\site-packages\psutil\__init__.py", line 723, in create_time
    self._create_time = self._proc.create_time()
  File "C:\Users\Ronald\anaconda3\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
  File "C:\Users\Ronald\anaconda3\lib\site-packages\psutil\_pswindows.py", line 671, in convert_oserror
    raise exc
  File "C:\Users\Ronald\anaconda3\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Ronald\anaconda3\lib\site-packages\psutil\_pswindows.py", line 933, in create_time
    user, system, created = cext.proc_times(self.pid)
OSError: [WinError 0] The operation completed successfully: '(originated from OpenProcess)'
```

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.

**Comment by rmuhumuza** [comment]
Thanks. [This page](https://docs.spyder-ide.org/installation.html#installing-a-development-build) was of great help.
