### ISSUE TITLE
Internal error that is pretty random but happened

### ISSUE THREAD

**Issue by charlescsr** [spyder-ide/spyder#12245]
### What steps will reproduce the problem?

I don't know what happened but all I can say is that I tried to delete the default template that generates from a new file in Spyder and I must have hit the wrong keyboard combo by mistake and that must have caused this

### Traceback
```python-traceback
  File "C:\Users\rchar\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1357, in handle_go_to_definition
    def_range = position['range']
TypeError: list indices must be integers or slices, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rchar\anaconda3\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "C:\Users\rchar\anaconda3\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Users\rchar\anaconda3\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Users\rchar\anaconda3\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "C:\Users\rchar\anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\rchar\anaconda3\lib\site-packages\spyder\app\start.py", line 205, in main
    mainwindow.main()
  File "C:\Users\rchar\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3734, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\rchar\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3631, in run_spyder
    app.exec_()
  File "C:\Users\rchar\anaconda3\lib\site-packages\spyder\plugins\completion\languageserver\client.py", line 377, in on_msg_received
    self.req_reply[req_id](None, {'params': []})
  File "C:\Users\rchar\anaconda3\lib\site-packages\spyder\plugins\completion\languageserver\plugin.py", line 483, in receive_response
    self.COMPLETION_CLIENT_NAME, req_id, response)
  File "C:\Users\rchar\anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 123, in receive_response
    self.howto_send_to_codeeditor(req_id)
  File "C:\Users\rchar\anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 177, in howto_send_to_codeeditor
    self.skip_and_send_to_codeeditor(req_id)
  File "C:\Users\rchar\anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 205, in skip_and_send_to_codeeditor
    self.gather_and_send_to_codeeditor(request_responses)
  File "C:\Users\rchar\anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 273, in gather_and_send_to_codeeditor
    response_instance.handle_response(req_type, responses)
  File "C:\Users\rchar\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 944, in handle_response
    handler(params)
  File "C:\Users\rchar\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1374, in handle_go_to_definition
    "Error when processing go to definition")
  File "C:\Users\rchar\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 975, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
```

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting, but unless you can give a way to reproduce this error we can't do anything about it, sorry.
