### ISSUE TITLE
ZeroDivisionError when trying to show a plot

### ISSUE THREAD

**Issue by sound-fx** [spyder-ide/spyder#12253]
### What steps will reproduce the problem?

I really don't know what led to this error. I've launched my script 1 or 2 times already with the Debug button on the toolbar. I just re-launched it, again using Debug, after setting a new breakpoint.  This time, after running some minutes, this internal error popped up.  I don't know why it hadn't popped up on a previous run.

### Traceback
```python-traceback
  File "C:\Users\greg\AppData\Local\Continuum\anaconda3-64\envs\nwra3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 540, in eventFilter
    self.scale_image()
  File "C:\Users\greg\AppData\Local\Continuum\anaconda3-64\envs\nwra3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 609, in scale_image
    if (fwidth / fheight) > (width / height):
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\greg\AppData\Local\Continuum\anaconda3-64\envs\nwra3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 540, in eventFilter
    self.scale_image()
  File "C:\Users\greg\AppData\Local\Continuum\anaconda3-64\envs\nwra3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 609, in scale_image
    if (fwidth / fheight) > (width / height):
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\greg\AppData\Local\Continuum\anaconda3-64\envs\nwra3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 540, in eventFilter
    self.scale_image()
  File "C:\Users\greg\AppData\Local\Continuum\anaconda3-64\envs\nwra3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 609, in scale_image
    if (fwidth / fheight) > (width / height):
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\greg\AppData\Local\Continuum\anaconda3-64\envs\nwra3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 540, in eventFilter
    self.scale_image()
  File "C:\Users\greg\AppData\Local\Continuum\anaconda3-64\envs\nwra3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 609, in scale_image
    if (fwidth / fheight) > (width / height):
ZeroDivisionError: division by zero
```

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by impact27** [comment]
I have seen that, it happens when a corrupted image data is sent to the frontend.

**Comment by ccordoba12** [comment]
What can we do about it @impact27?

**Comment by goanpeca** [comment]
We should at least be catching that exception in the meantime.

**Comment by ccordoba12** [comment]
Sure, but what to do when that happens?

**Comment by goanpeca** [comment]
The image won't be updated 🤷‍♂️

**Comment by ccordoba12** [comment]
Ok. If you want to do a PR to solve this, please do.

**Comment by impact27** [comment]
> The image won't be updated/created 🤷‍♂️

We could also display a "Broken" image logo

**Comment by ccordoba12** [comment]
It could be, yeah. @goanpeca, what do you think?

**Comment by ccordoba12** [comment]
@steff456, let's catch the error above and show in Plots this icon: `mdi-image-broken-variant`.
