### ISSUE TITLE
Using TraitsUI cause "RuntimeError: Importing from wx backend after selecting qt4 backend"

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1228]
_From [w.weit...@gmail.com](https://code.google.com/u/116464811076843998334/) on 2013-01-19T07:33:10Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1.The code from http://code.enthought.com/projects/traits/docs/html/tutorials/traits_ui_scientific_app.html#the-gui-elements Making a traits editor from a MatPlotLib plot
code snippet `#8`

import wx

import matplotlib
\# We want matplotlib to use a wxPython backend
matplotlib.use('WXAgg')
from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as FigureCanvas
from matplotlib.figure import Figure
from matplotlib.backends.backend_wx import NavigationToolbar2Wx

from enthought.traits.api import Any, Instance
from enthought.traits.ui.wx.editor import Editor
from enthought.traits.ui.wx.basic_editor_factory import BasicEditorFactory

class _MPLFigureEditor(Editor):

    scrollable  = True

    def init(self, parent):
        self.control = self._create_canvas(parent)
        self.set_tooltip()

    def update_editor(self):
        pass

    def _create_canvas(self, parent):
        """ Create the MPL canvas. """
        \# The panel lets us add additional controls.
        panel = wx.Panel(parent, -1, style=wx.CLIP_CHILDREN)
        sizer = wx.BoxSizer(wx.VERTICAL)
        panel.SetSizer(sizer)
        \# matplotlib commands to create a canvas
        mpl_control = FigureCanvas(panel, -1, self.value)
        sizer.Add(mpl_control, 1, wx.LEFT | wx.TOP | wx.GROW)
        toolbar = NavigationToolbar2Wx(mpl_control)
        sizer.Add(toolbar, 0, wx.EXPAND)
        self.value.canvas.SetMinSize((10,10))
        return panel

class MPLFigureEditor(BasicEditorFactory):

    klass = _MPLFigureEditor

if __name__ == "__main__":
    \# Create a window to demo the editor
    from enthought.traits.api import HasTraits
    from enthought.traits.ui.api import View, Item
    from numpy import sin, cos, linspace, pi

    class Test(HasTraits):

        figure = Instance(Figure, ())

        view = View(Item('figure', editor=MPLFigureEditor(),
                                show_label=False),
                        width=400,
                        height=300,
                        resizable=True)

        def __init__(self):
            super(Test, self).__init__()
            axes = self.figure.add_subplot(111)
            t = linspace(0, 2*pi, 200)
            axes.plot(sin(t)*(1+0.5*cos(11*t)), cos(t)*(1+0.5*cos(11*t)))

    Test().configure_traits()

2. Run the code in Spyder editor, comes up "RuntimeError: Importing from wx backend after selecting qt4 backend"
3. No problem if Run it in an external system terminal What is the expected output? What do you see instead? Traceback (most recent call last):
  File "D:\untitled12.py", line 18, in \<module>
    from enthought.traits.ui.wx.editor import Editor
  File "c:\Python27\lib\site-packages\enthought\traits\ui\wx\__init__.py", line 25, in \<module>
    import toolkit
  File "c:\Python27\lib\site-packages\enthought\traits\ui\wx\toolkit.py", line 2, in \<module>
    from traitsui.wx.toolkit import *
  File "C:\Python27\lib\site-packages\traitsui\wx\__init__.py", line 26, in \<module>
    import toolkit
  File "C:\Python27\lib\site-packages\traitsui\wx\toolkit.py", line 28, in \<module>
    assert_toolkit_import('wx')
  File "C:\Python27\lib\site-packages\traitsui\toolkit.py", line 60, in assert_toolkit_import
    "backend!" &#37; (name, ETSConfig.toolkit)
RuntimeError: Importing from wx backend after selecting qt4 backend! What version of the product are you using? On what operating system? Python(x,y)2.7.3.1 with Spyder 2.1.11 on Win7(64bit). 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1228_

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-01-19T09:22:19Z_

@-w.weitong, Sypder's Python consoles are by default configured to import matplotlib at startup and also set the ETS_TOOLKIT environment variable to use a specific GUI interface. From the traceback you provided, it looks like your preferences must be set to use the qt4 backend and qt4 for the ETS Toolkit by default. Try opening Spyder's Preferences dialog to Preferences...Console...External Modules and set the matplotlib backend to WXAgg and the ETS_TOOLKIT option to wx. Let us know if that solves your issue.

**Comment by spyder-issues-migrator** [comment]
_From [w.weit...@gmail.com](https://code.google.com/u/116464811076843998334/) on 2013-01-20T06:36:49Z_

Yes. That solve the problem. Thanks.

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-01-20T06:42:08Z_

**Status:** Done

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-01-20T06:42:27Z_

**Labels:** -Type-Defect Type-Other
