### ISSUE TITLE
Spyder crashed during last session now wont open

### ISSUE THREAD

**Issue by tristanmckechnie** [spyder-ide/spyder#12291]
**Issue Report Checklist**
 Searched the issues page for similar reports
 Read the relevant sections of the Spyder Troubleshooting Guide and followed its advice
 Reproduced the issue after updating with conda update spyder (or pip, if not using Anaconda)
 Restarted Spyder
 Reset preferences with spyder --reset
 Reinstalled the latest version of Anaconda
 Tried the other applicable steps from the Troubleshooting Guide
 Completed the Problem Description, Steps to Reproduce and Version sections below
**Problem Description**
�I installed anaconde3 on my pc. When I launched Spyder I got window stating  "Spyder crashed during last session" . I tried to use the command line option '--reset':
spyder --reset but it did not work.

**What steps reproduce the problem?**
re-installed anaconde3 
launched Spyder in anaconda-navigator
'Spyder crashed during last session' came out again
What is the expected output? What do you see instead?
**Paste Traceback/Error Below (if applicable)**
Traceback (most recent call last):
  File "/home/tristan/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/tristan/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3559, in run_spyder
    main.setup()
  File "/home/tristan/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 955, in setup
    self.editor = Editor(self)
  File "/home/tristan/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/plugin.py", line 178, in __init__
    self.autosave.try_recover_from_autosave()
  File "/home/tristan/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/utils/autosave.py", line 176, in try_recover_from_autosave
    files_to_recover, pidfiles = self.get_files_to_recover()
  File "/home/tristan/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/utils/autosave.py", line 149, in get_files_to_recover
    txt_as_dict = ast.literal_eval(txt)
  File "/home/tristan/anaconda3/lib/python3.7/ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/home/tristan/anaconda3/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
**Versions**
Spyder version: 4.0.1
Python version: 3.7

Operating System name/version: Ubuntu 18.04

**Comment by ccordoba12** [comment]
This is fixed in our latest

**Comment by tristanmckechnie** [comment]
I can confirm the update fixed the issue. Thanks.

**Comment by praveenkumar1980** [comment]
The same issue with Spyder . Spyderman not working at all
