### ISSUE TITLE
first run after reinstall

### ISSUE THREAD

**Issue by bertoli517** [spyder-ide/spyder#12292]
### What steps will reproduce the problem?

I don't know what will reproduce the problem because I don't know what the problem is.  I just tried reinstalling you buggy, shitty software for the third time.

Maybe you guys can get one that works right and stick to it without changing it all the time.

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 154, in perform_request
    response = handler(params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\decorators.py", line 20, in wrapper
    params = req(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\providers\document.py", line 83, in document_did_open
    self.get_status(params['file'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 111, in get_status
    kite_status = status()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\utils\status.py", line 93, in status
    elif check_if_kite_running():
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\utils\status.py", line 42, in check_if_kite_running
    'status']):
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 1457, in process_iter
    yield add(pid)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 1432, in add
    proc = Process(pid)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 346, in __init__
    self._init(pid)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 373, in _init
    self.create_time()
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 723, in create_time
    self._create_time = self._proc.create_time()
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 671, in convert_oserror
    raise exc
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 933, in create_time
    user, system, created = cext.proc_times(self.pid)
OSError: [WinError 0] The operation completed successfully: '(originated from OpenProcess)'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 154, in perform_request
    response = handler(params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\decorators.py", line 20, in wrapper
    params = req(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\providers\document.py", line 83, in document_did_open
    self.get_status(params['file'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 111, in get_status
    kite_status = status()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\utils\status.py", line 93, in status
    elif check_if_kite_running():
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\utils\status.py", line 42, in check_if_kite_running
    'status']):
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 1457, in process_iter
    yield add(pid)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 1432, in add
    proc = Process(pid)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 346, in __init__
    self._init(pid)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 373, in _init
    self.create_time()
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 723, in create_time
    self._create_time = self._proc.create_time()
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 671, in convert_oserror
    raise exc
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 933, in create_time
    user, system, created = cext.proc_times(self.pid)
OSError: [WinError 0] The operation completed successfully: '(originated from OpenProcess)'
```

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.6
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.1 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.0 (OK)

# Optional:
cython >=0.21                  :  0.29.16 (OK)
matplotlib >=2.0.0             :  3.2.1 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by jitseniesen** [comment]
Please moderate your language. The people who produce Spyder give it away for free so that you can use it. Developers are less likely to answer impolite bug reports.

**Comment by ccordoba12** [comment]
> I just tried reinstalling you buggy, shitty software for the third time.

Closing and locking because we don't admit this behavior here, according to our Code of Conduct:

https://github.com/spyder-ide/spyder/blob/master/CODE_OF_CONDUCT.md

Please reopen a new issue and tone down your language if you want our help. If you continue with this behavior, we will simply ban it from our organization.
