### ISSUE TITLE
Error installing Spyder 4.1.2

### ISSUE THREAD

**Issue by BigDataLyst** [spyder-ide/spyder#12305]
### What steps will reproduce the problem?

I opened Anaconda Powershell Prompt and issued the command:

pip install --pre -U spyder

(and then I read the Note: Do not use this command if you are using Anaconda because it could break your installation...  whoops)

found here:
https://github.com/spyder-ide/spyder/releases

### Traceback
```python-traceback
  File "C:\Users\chanb062\Documents\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 706, in <lambda>
    lambda c=client: self.process_started(c))
  File "C:\Users\chanb062\Documents\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 1358, in process_started
    self.main.variableexplorer.add_shellwidget(client.shellwidget)
  File "C:\Users\chanb062\Documents\Anaconda\lib\site-packages\spyder\plugins\variableexplorer\plugin.py", line 124, in add_shellwidget
    nsb.setup(**self.get_settings())
  File "C:\Users\chanb062\Documents\Anaconda\lib\site-packages\spyder\plugins\variableexplorer\plugin.py", line 58, in get_settings
    settings[name] = self.get_option(name)
  File "C:\Users\chanb062\Documents\Anaconda\lib\site-packages\spyder\api\plugins.py", line 109, in get_option
    section=section)
  File "C:\Users\chanb062\Documents\Anaconda\lib\site-packages\spyder\plugins\base.py", line 69, in _get_option
    return CONF.get(section, option, default)
  File "C:\Users\chanb062\Documents\Anaconda\lib\site-packages\spyder\config\manager.py", line 193, in get
    return config.get(section=section, option=option, default=default)
  File "C:\Users\chanb062\Documents\Anaconda\lib\site-packages\spyder\config\user.py", line 945, in get
    return config.get(section=section, option=option, default=default)
  File "C:\Users\chanb062\Documents\Anaconda\lib\site-packages\spyder\config\user.py", line 512, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'exclude_callables_and_modules' in section: 'variable_explorer'
Traceback (most recent call last):
  File "C:\Users\chanb062\Documents\Anaconda\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\chanb062\Documents\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 135, in _handle_execute_reply
    self.set_namespace_view_settings()
  File "C:\Users\chanb062\Documents\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 79, in set_namespace_view_settings
    settings = self.namespacebrowser.get_view_settings()
  File "C:\Users\chanb062\Documents\Anaconda\lib\site-packages\spyder\plugins\variableexplorer\widgets\namespacebrowser.py", line 290, in get_view_settings
    settings[name] = getattr(self, name)
AttributeError: 'NamespaceBrowser' object has no attribute 'exclude_callables_and_modules'
```

## Versions

* Spyder version: 4.0.0rc1 
* Python version: 3.7.3
* Qt version: 5.12.8
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.7.2 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.1 (OK)
pylint >=0.25                :  2.4.3 (OK)
psutil >=0.3                 :  5.6.5 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.7.0;<2.0.0:  1.9.0 (OK)
qdarkstyle >=2.7             :  2.8.1 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.13 (OK)
IPython >=4.0                :  7.9.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.2 (OK)
numpy >=1.7                  :  1.17.3 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.29.3;<0.30.0        :  0.31.9 (NOK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment]
> I opened Anaconda Powershell Prompt and issued the command:
pip install --pre -U spyder

By doing this you basically broke your Anaconda installation. We clearly state in our [release notes](https://github.com/spyder-ide/spyder/releases/tag/v4.1.2) that you **must** not use pip to install Spyder when using Anaconda.

Now I'm afraid you'll have to completely remove and reinstall Anaconda to fix this, sorry.

**Comment by BigDataLyst** [comment]
I later issued this, and so far it seems fine...?

conda install spyder=4.1.2
