### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by Prateekag02** [spyder-ide/spyder#12302]
An error ocurred while starting the kernel
Traceback (most recent call last):
File "C:\Anaconda\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Anaconda\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Anaconda\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Anaconda\lib\site‑packages\spyder_kernels\console\start.py", line 287, in main
import_spydercustomize()
File "C:\Anaconda\lib\site‑packages\spyder_kernels\console\start.py", line 39, in import_spydercustomize
import spydercustomize
File "C:\Anaconda\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 27, in 
from IPython.core.getipython import get_ipython
File "C:\Anaconda\lib\site‑packages\IPython\__init__.py", line 54, in 
from .core.application import Application
File "C:\Anaconda\lib\site‑packages\IPython\core\application.py", line 23, in 
from traitlets.config.application import Application, catch_config_error
File "C:\Anaconda\lib\site‑packages\traitlets\config\__init__.py", line 6, in 
from .application import *
File "C:\Anaconda\lib\site‑packages\traitlets\config\application.py", line 19, in 
from traitlets.config.configurable import Configurable, SingletonConfigurable
File "C:\Anaconda\lib\site‑packages\traitlets\config\configurable.py", line 12, in 
from .loader import Config, LazyConfigValue, _is_section_key
File "C:\Anaconda\lib\site‑packages\traitlets\config\loader.py", line 16, in 
from ipython_genutils.path import filefind
File "C:\Anaconda\lib\site‑packages\ipython_genutils\path.py", line 13, in 
import random
File "C:\Users\user\random.py", line 98
print ('Max)
^
SyntaxError: EOL while scanning string literal

**Comment by jitseniesen** [comment]
@Prateekag02 The file "C:\Users\user\random.py" (mentioned at the bottom of your error message) has the same name as the standard Python library `random`. If you give that file another name, the error should go away.

**Comment by Prateekag02** [comment]
Thank you soo much
It worked
