### ISSUE TITLE
Completion and linting in the editor for Python files stoped working

### ISSUE THREAD

**Issue by Lukis90** [spyder-ide/spyder#12317]
### What steps will reproduce the problem?

I got an error about linting and completion editor and after some time this error apeared. It's the first time it ever happened. I updated spyder to 4.1.1 few days ago

### Traceback
```python-traceback
  File "/home/ppmi/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/client.py", line 334, in send
    self.zmq_out_socket.send_pyobj(msg, flags=zmq.NOBLOCK)
  File "/home/ppmi/anaconda3/lib/python3.7/site-packages/zmq/sugar/socket.py", line 611, in send_pyobj
    return self.send(msg, flags=flags, **kwargs)
  File "/home/ppmi/anaconda3/lib/python3.7/site-packages/zmq/sugar/socket.py", line 400, in send
    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 728, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 775, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 247, in zmq.backend.cython.socket._send_copy
  File "zmq/backend/cython/socket.pyx", line 242, in zmq.backend.cython.socket._send_copy
  File "zmq/backend/cython/checkrc.pxd", line 19, in zmq.backend.cython.checkrc._check_rc
zmq.error.Again: Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ppmi/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 1393, in handle_new_screen
    self.show_dpi_change_message)
TypeError: 'method' object is not connected
WARNING:spyder.plugins.completion.languageserver.client:The send queue is full! Retrying...
WARNING:spyder.plugins.completion.languageserver.client:The send queue is full! Retrying...
WARNING:spyder.plugins.completion.languageserver.client:The send queue is full! Retrying...
WARNING:spyder.plugins.completion.languageserver.client:The send queue is full! Retrying...
WARNING:spyder.plugins.completion.languageserver.client:The send queue is full! Retrying...
WARNING:spyder.plugins.completion.languageserver.client:The send queue is full! Retrying...
WARNING:spyder.plugins.completion.languageserver.client:The send queue is full! Retrying...
WARNING:spyder.plugins.completion.languageserver.client:The send queue is full! Retrying...
WARNING:spyder.plugins.completion.languageserver.client:The send queue is full! Retrying...
WARNING:spyder.plugins.completion.languageserver.client:The send queue is full! Retrying...
```

## Versions

* Spyder version: 4.1.1 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 5.3.0-45-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by Lukis90** [comment]
duplicate

**Comment by Lukis90** [comment]
relates to https://github.com/spyder-ide/spyder/issues/11026
