### ISSUE TITLE
spyder launching error 

### ISSUE THREAD

**Issue by nabilgouri** [spyder-ide/spyder#12365]
Traceback (most recent call last):
File "C:\Users\pc\Anaconda3\envs\IA\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\pc\Anaconda3\envs\IA\lib\site-packages\spyder\app\start.py", line 201, in main
from spyder.app import mainwindow
File "C:\Users\pc\Anaconda3\envs\IA\lib\site-packages\spyder\app\mainwindow.py", line 172, in 
from spyder.plugins.help.utils.sphinxify import CSS_PATH, DARK_CSS_PATH
File "C:\Users\pc\Anaconda3\envs\IA\lib\site-packages\spyder\plugins\help\utils\sphinxify.py", line 36, in 
from sphinx.application import Sphinx
File "C:\Users\pc\Anaconda3\envs\IA\lib\site-packages\sphinx\application.py", line 42, in 
from sphinx.highlighting import lexer_classes, lexers
File "C:\Users\pc\Anaconda3\envs\IA\lib\site-packages\sphinx\highlighting.py", line 30, in 
from sphinx.ext import doctest
File "C:\Users\pc\Anaconda3\envs\IA\lib\site-packages\sphinx\ext\doctest.py", line 28, in 
from sphinx.builders import Builder
File "C:\Users\pc\Anaconda3\envs\IA\lib\site-packages\sphinx\builders\__init__.py", line 24, in 
from sphinx.io import read_doc
File "C:\Users\pc\Anaconda3\envs\IA\lib\site-packages\sphinx\io.py", line 35, in 
from sphinx.transforms.i18n import (
File "C:\Users\pc\Anaconda3\envs\IA\lib\site-packages\sphinx\transforms\i18n.py", line 22, in 
from sphinx.domains.std import make_glossary_term, split_term_classifiers
File "C:\Users\pc\Anaconda3\envs\IA\lib\site-packages\sphinx\domains\std.py", line 26, in 
from sphinx.directives import ObjectDescription
File "C:\Users\pc\Anaconda3\envs\IA\lib\site-packages\sphinx\directives\__init__.py", line 261, in 
from sphinx.directives.patches import ( # noqa
File "C:\Users\pc\Anaconda3\envs\IA\lib\site-packages\sphinx\directives\patches.py", line 15, in 
from docutils.parsers.rst.directives import images, html, tables
File "C:\Users\pc\Anaconda3\envs\IA\lib\site-packages\docutils\parsers\rst\directives\images.py", line 21, in 
import PIL.Image
File "C:\Users\pc\Anaconda3\envs\IA\lib\site-packages\PIL\Image.py", line 2804
filename =r str(fp.resolve())
^
SyntaxError: invalid syntax

**Comment by ccordoba12** [comment]
It seems your `IA` is corrupted. Please remove it and create it again.
