### ISSUE TITLE
crash in sway just after startup

### ISSUE THREAD

**Issue by activeion** [spyder-ide/spyder#12360]
### What steps will reproduce the problem?

1. enter Sway desktop in archlinux
2. enter "spyder" in terminal
3. ipython crash

### Traceback
```python-traceback
  File "/usr/lib/python3.8/site-packages/spyder/utils/introspection/plugin_client.py", line 163, in _on_finished
    self.run()
  File "/usr/lib/python3.8/site-packages/spyder/utils/introspection/plugin_client.py", line 71, in run
    self.port = self.socket.bind_to_random_port('tcp://%s' % LOCALHOST)
  File "/usr/lib/python3.8/site-packages/zmq/sugar/socket.py", line 264, in bind_to_random_port
    self.bind("%s:*" % addr)
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Cannot assign requested address
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/utils/introspection/plugin_client.py", line 163, in _on_finished
    self.run()
  File "/usr/lib/python3.8/site-packages/spyder/utils/introspection/plugin_client.py", line 71, in run
    self.port = self.socket.bind_to_random_port('tcp://%s' % LOCALHOST)
  File "/usr/lib/python3.8/site-packages/zmq/sugar/socket.py", line 264, in bind_to_random_port
    self.bind("%s:*" % addr)
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Cannot assign requested address
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/utils/introspection/plugin_client.py", line 163, in _on_finished
    self.run()
  File "/usr/lib/python3.8/site-packages/spyder/utils/introspection/plugin_client.py", line 71, in run
    self.port = self.socket.bind_to_random_port('tcp://%s' % LOCALHOST)
  File "/usr/lib/python3.8/site-packages/zmq/sugar/socket.py", line 264, in bind_to_random_port
    self.bind("%s:*" % addr)
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Cannot assign requested address
WARNING:traitlets:kernel died: 18.015648365020752
WARNING:traitlets:kernel died: 18.017215490341187
WARNING:traitlets:kernel died: 18.014543533325195
WARNING:traitlets:kernel died: 18.017229080200195
WARNING:traitlets:kernel died: 18.017245531082153
WARNING:traitlets:kernel died: 18.01646637916565
WARNING:traitlets:kernel died: 18.015365600585938
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.8.2
* Qt version: 5.14.2
* PyQt5 version: 5.14.2
* Operating System: Linux 5.6.3-arch1-1

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.6.1 (OK)
sphinx >=0.6.6    :  3.0.1 (OK)
rope >=0.9.4      :  0.16.0 (OK)
jedi >=0.9.0      :  0.16.0 (OK)
psutil >=0.3      :  5.7.0 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.18.2 (OK)
sympy >=0.7.3     :  1.5.1 (OK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.7.1 (OK)
IPython >=4.0     :  7.13.0 (OK)
matplotlib >=2.0.0:  3.2.1 (OK)
pylint >=0.25     :  2.4.4 (OK)
```

**Comment by ccordoba12** [comment]
Please contact your distribution about this problem because we no longer support Spyder 3, sorry.
