### ISSUE TITLE
Duplicate Signature

### ISSUE THREAD

**Issue by pfracas** [spyder-ide/spyder#12381]
### What steps will reproduce the problem?

 File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/jupyter_client/threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/jupyter_client/session.py", line 927, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'2611739bc902ef83f8ad959eaea7cdd9ded60b27a2e6a9baa5bb48387b91c79f'
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/jupyter_client/threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/jupyter_client/session.py", line 927, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'2611739bc902ef83f8ad959eaea7cdd9ded60b27a2e6a9baa5bb48387b91c79f'
ERROR:tornado.application:Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x151a8f950>)
Traceback (most recent call last):
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 542, in <lambda>
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/jupyter_client/threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/jupyter_client/session.py", line 927, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'2611739bc902ef83f8ad959eaea7cdd9ded60b27a2e6a9baa5bb48387b91c79f'

### Traceback
```python-traceback
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/jupyter_client/threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/jupyter_client/session.py", line 927, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'2611739bc902ef83f8ad959eaea7cdd9ded60b27a2e6a9baa5bb48387b91c79f'
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/jupyter_client/threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/jupyter_client/session.py", line 927, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'2611739bc902ef83f8ad959eaea7cdd9ded60b27a2e6a9baa5bb48387b91c79f'
ERROR:tornado.application:Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x151a8f950>)
Traceback (most recent call last):
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 542, in <lambda>
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/jupyter_client/threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/Users/paolofracas/anaconda3/lib/python3.7/site-packages/jupyter_client/session.py", line 927, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'2611739bc902ef83f8ad959eaea7cdd9ded60b27a2e6a9baa5bb48387b91c79f'
```

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.4.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by pfracas** [comment]
problem cause interruption of multiprocess
