### ISSUE TITLE
readline.py generates error

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1238]
_From [frasker...@gmail.com](https://code.google.com/u/113272808944134201033/) on 2013-01-26T08:21:41Z_

I am using python 3.2.2 and running under WindowsXP.

I typed in:
C:\Program Files\Python322\Scripts>ipython3

And I got:
Traceback (most recent call last):
  File "C:\Program Files\Python322\Scripts\ipython3-script.py", line 9, in \<modu
le>
    load_entry_point('ipython==0.13.1', 'console_scripts', 'ipython3')()
  File "C:\Program Files\Python322\lib\site-packages\ipython-0.13.1-py3.2.egg\IP
ython\frontend\terminal\ipapp.py", line 388, in launch_new_instance
    app.initialize()
  File "<string>", line 2, in initialize
  File "C:\Program Files\Python322\lib\site-packages\ipython-0.13.1-py3.2.egg\IP
ython\config\application.py", line 84, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Program Files\Python322\lib\site-packages\ipython-0.13.1-py3.2.egg\IP
ython\frontend\terminal\ipapp.py", line 324, in initialize
    self.init_shell()
  File "C:\Program Files\Python322\lib\site-packages\ipython-0.13.1-py3.2.egg\IP
ython\frontend\terminal\ipapp.py", line 340, in init_shell
    ipython_dir=self.ipython_dir)
  File "C:\Program Files\Python322\lib\site-packages\ipython-0.13.1-py3.2.egg\IP
ython\config\configurable.py", line 318, in instance
    inst = cls(*args, **kwargs)
  File "C:\Program Files\Python322\lib\site-packages\ipython-0.13.1-py3.2.egg\IP
ython\frontend\terminal\interactiveshell.py", line 360, in __init__
    user_module=user_module, custom_exceptions=custom_exceptions
  File "C:\Program Files\Python322\lib\site-packages\ipython-0.13.1-py3.2.egg\IP
ython\core\interactiveshell.py", line 455, in __init__
    self.init_readline()
  File "C:\Program Files\Python322\lib\site-packages\ipython-0.13.1-py3.2.egg\IP
ython\core\interactiveshell.py", line 1780, in init_readline
    import IPython.utils.rlineimpl as readline
  File "C:\Program Files\Python322\lib\site-packages\ipython-0.13.1-py3.2.egg\IP
ython\utils\rlineimpl.py", line 33, in \<module>
    from readline import *
  File "C:\Program Files\Python322\lib\site-packages\pyreadline-1.7.1-py3.2-win3
2.egg\readline.py", line 42
    u'''Return the console object used by readline so that it can be used for pr
inting in color.'''

                  ^
SyntaxError: invalid syntax

If you suspect this is an IPython bug, please report it at: https://github.com/ipython/ipython/issues or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "&#37;tb", or use "&#37;debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True What version of the product are you using? On what operating system? 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1238_

**Comment by spyder-issues-migrator** [comment]
_From [frasker...@gmail.com](https://code.google.com/u/113272808944134201033/) on 2013-01-26T05:24:33Z_

Oppss!! so sorry, I report to the wrong project group

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-01-26T10:09:49Z_

No problem.

**Status:** Invalid
