### ISSUE TITLE
update the spyder 

### ISSUE THREAD

**Issue by MrCrazyCrab** [spyder-ide/spyder#12403]
## Problem Description
Traceback (most recent call last):
File "D:\Progran_file\Anaconda\envs\py1_3\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "D:\Progran_file\Anaconda\envs\py1_3\lib\site-packages\spyder\app\start.py", line 205, in main
mainwindow.main()
File "D:\Progran_file\Anaconda\envs\py1_3\lib\site-packages\spyder\app\mainwindow.py", line 3734, in main
mainwindow = run_spyder(app, options, args)
File "D:\Progran_file\Anaconda\envs\py1_3\lib\site-packages\spyder\app\mainwindow.py", line 3590, in run_spyder
main.setup()
File "D:\Progran_file\Anaconda\envs\py1_3\lib\site-packages\spyder\app\mainwindow.py", line 939, in setup
from spyder.plugins.ipythonconsole.plugin import IPythonConsole
File "D:\Progran_file\Anaconda\envs\py1_3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 46, in 
from spyder.plugins.ipythonconsole.widgets import (ClientWidget,
File "D:\Progran_file\Anaconda\envs\py1_3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\__init__.py", line 16, in 
from .debugging import DebuggingWidget
File "D:\Progran_file\Anaconda\envs\py1_3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 22, in 
from IPython.core.inputtransformer2 import TransformerManager
ModuleNotFoundError: No module named 'IPython.core.inputtransformer2'

### What steps reproduce the problem?

1. update the spyder to 4.1.2
2. 
3. 

### What is the expected output? What do you see instead?

//

## Versions

* Spyder version: 4.1.2
* Python version: 3.6.7
* Qt version: /
* PyQt version: /
* Operating System name/version: windows10

i isntall the newest anacodna, but when i want to upload the spyder in the envs to 4.1.2, it fails to start. But it runs ok in 3.6. how can i to reslove the problem?

**Comment by ccordoba12** [comment]
My only suggestion for you is to create a new environment and install Spyder 4 on it, instead of trying to update a previous one. That will probably avoid the error you're seeing right now.
