### ISSUE TITLE
internal pl in spyder

### ISSUE THREAD

**Issue by Cmeynier** [spyder-ide/spyder#12427]
### What steps will reproduce the problem?

happens while editing code. No program  running just one consol, happens about evrey 10 minutes

### Traceback
```python-traceback
  File "C:\Users\c.meynier\AppData\Local\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1250, in process_signatures
    documentation=documentation,
  File "C:\Users\c.meynier\AppData\Local\anaconda3\lib\site-packages\spyder\widgets\mixins.py", line 593, in show_calltip
    self._update_stylesheet(self.calltip_widget)
  File "C:\Users\c.meynier\AppData\Local\anaconda3\lib\site-packages\spyder\widgets\mixins.py", line 139, in _update_stylesheet
    css = qdarkstyle.load_stylesheet(qt_api='')
TypeError: load_stylesheet() got an unexpected keyword argument 'qt_api'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\c.meynier\AppData\Local\anaconda3\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "C:\Users\c.meynier\AppData\Local\anaconda3\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Users\c.meynier\AppData\Local\anaconda3\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Users\c.meynier\AppData\Local\anaconda3\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "C:\Users\c.meynier\AppData\Local\anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\c.meynier\AppData\Local\anaconda3\lib\site-packages\spyder\app\start.py", line 205, in main
    mainwindow.main()
  File "C:\Users\c.meynier\AppData\Local\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3734, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\c.meynier\AppData\Local\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3631, in run_spyder
    app.exec_()
  File "C:\Users\c.meynier\AppData\Local\anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 302, in <lambda>
    lambda: self.receive_timeout(req_id))
  File "C:\Users\c.meynier\AppData\Local\anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 136, in receive_timeout
    self.howto_send_to_codeeditor(req_id)
  File "C:\Users\c.meynier\AppData\Local\anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 177, in howto_send_to_codeeditor
    self.skip_and_send_to_codeeditor(req_id)
  File "C:\Users\c.meynier\AppData\Local\anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 205, in skip_and_send_to_codeeditor
    self.gather_and_send_to_codeeditor(request_responses)
  File "C:\Users\c.meynier\AppData\Local\anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 273, in gather_and_send_to_codeeditor
    response_instance.handle_response(req_type, responses)
  File "C:\Users\c.meynier\AppData\Local\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 944, in handle_response
    handler(params)
  File "C:\Users\c.meynier\AppData\Local\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1257, in process_signatures
    self.log_lsp_handle_errors("Error when processing signature")
  File "C:\Users\c.meynier\AppData\Local\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 975, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
```

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.14.1 (NOK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.7.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.2 (NOK)
qdarkstyle >=2.8               :  2.7 (NOK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
You're using an old version of qdarkstyle (along with several other packages). Please update them.
