### ISSUE TITLE
Bootstrap fails under Python 3.2

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1243]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-01-31T00:11:29Z_

Spyder Version: v21 repo revision acc4392fd503 OS: Ubuntu 12.04
Python Version: 3.2 

What steps will reproduce the problem?

 1. Try to bootstrap v2.1. What is the expected output? What do you see instead? The following traceback:

$ python3 bootstrap.py --gui pyqt
  File "bootstrap.py", line 47
    osp.join(DEVPATH, u'test')
                            ^
SyntaxError: invalid syntax

I guess I didn't fully comprehend that Python 3.0, 3.1, and 3.2 do not support the u'' string literal syntax at all. There was enough outcry about this that it has been added back in for Python 3.3. See this PEP: http://www.python.org/dev/peps/pep-0414/ Perhaps you already knew this, Pierre. Spyder has unicode string literals all over the place, and for this reason it's really challenging to support 2.6 and 3.2 with the same code base. It is, however, very possible to support 2.6 and 3.3 with the same code base since the u'' syntax is allowed in 3.3. In that light this isn't necessarily a bug report but a known limitation that we might want to publish more clearly since Python 3.2 is still the stable package standard. Debian Python 3.3 packages are still marked as experimental.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1243_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-01-31T02:40:57Z_

Actually, I was aware of it but I did not take action on this because, as you mentioned, there are unicode strings all over Spyder's code source.

Supporting both Python 2.6 to 2.7 and Python 3.0 to 3.3 could be possible by replacing this:
osp.join(DEVPATH, u'test')
by this:
from spyderlib.py3compat import u
osp.join(DEVPATH, u('test'))

So, as you can see, I already have a solution for this.

But, for now, I don't have any preference between the two solutions:
  1. keep the u'' string literal syntax and drop support for Python 3.0-3.2
  2. replace u'' by u('') all over the code to support Python 3.0-3.2, knowing that the code will be less readable

Maybe the relative loss of readability is a small price to pay for supporting all Python 3 versions.

What do you think?

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-01-31T08:05:39Z_

I noticed the u() funciton in the compatibility module, but I didn't see it used anywhere yet. I was wondering if that was still an open question.

There is a piece of me that would like to say Spyder supports all Python 3 versions. Historically the idea of supporting many platforms and many configurations has been a key strength. I don't think the readability would be compromised too much. There is already the use of the translate function _(), so I don't see the u() making things much worse. Maybe a small note on the Development page of the wiki to clarify the use of the u() function would suffice.

Then, again, it's hard to know if it worth the effort to add all that in when 3.0-3.2 seem to be fading quickly. It may be wasted effort.

Perhaps we let demand from users dictate the decision. Maybe you leave it as is now and then see if lots of issues arise. The only danger there is that newer users who aren't as familiar with the subtle differences in the different Python versions might just give up when it doesn't work rather than ask questions.

How's that for a vague answer? :)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-01T06:58:07Z_

I'll prefer to support only Python 3.3. Ubuntu 13.04 will come with it, as WinPython too. I think it's too much of a hassle to support previous versions.

Besides, most people new to Python download the latest version.

**Labels:** MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-02-03T09:17:13Z_

This issue was updated by revision 5e9d29051bdf .


Unless I missed something, this changeset should have replaced all the u'' or
u"" string occurences in the whole source code of Spyder v2.1. This seems quite
acceptable, don't you think? I mean that there aren't so many of them.
I can't test it under Python 3.2 though and it would be better to check if this
is enough.

**Status:** Started

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-02-03T09:18:14Z_

And here is correct link for the revision mentioned in last comment (comment `#4`): https://code.google.com/p/spyderlib/source/detail?r=5e9d29051bdf4ed7b82e888de6e93cdfbade501f&repo=v21

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-02-04T20:22:13Z_

I've had only limited time to test this. I certainly get further into the bootstrap than I did previously, but launch still doesn't succeed. The obstacle appears to be the user configuration file. Many entries in spyder.ini use the u'' syntax when defining their entries, and those are causing tracebacks.

I haven't looked too closely yet, but I'm guessing that the get and set methods of  UserConfig would have to be modified so that they know how to handle u'' strings correctly. Might be interesting.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-02-09T09:25:30Z_

We could accept the fact that Spyder has to be reset when switching from Python 2 to Python 3 for the first time. So if you make a copy of your .spyder.ini and remove it, is it working?

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-02-09T13:01:13Z_

Here's a quick update on what I can accomplish, which differs between platforms.

Windows 7, Python 3.3 using WinPython: Everything launches fine.
Ubuntu 12.04 and 12.10 using Python 3.2: After removing .spyder.ini, tt seems I get farther in the startup, but I still crash. However, I don't think the traceback is not Python 3.2 specific. atoi should be missing from any Python 3 installation.

Traceback (most recent call last):
  File ".../spyderlib/widgets/dicteditorutils.py", line 72, in \<module>
    from dateutil.parser import parse as dateparse
ImportError: No module named dateutil.parser

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bootstrap.py", line 89, in \<module>
    from spyderlib import spyder
  File ".../spyderlib/spyder.py", line 90, in \<module>
    from spyderlib.plugins.console import Console
  File ".../spyderlib/plugins/console.py", line 30, in \<module>
    from spyderlib.utils.environ import EnvDialog
  File ".../spyderlib/utils/environ.py", line 17, in \<module>
    from spyderlib.widgets.dicteditor import DictEditor
  File ".../spyderlib/widgets/dicteditor.py", line 38, in \<module>
    from spyderlib.widgets.dicteditorutils import (sort_against, get_size,
  File ".../spyderlib/widgets/dicteditorutils.py", line 74, in \<module>
    from string import atoi
ImportError: cannot import name atoi

I would expect to get something like this under Python 3.3, too, but I don't see it on Windows. I haven't studied the code much. I suspect this stuff just isn't getting called on Windows. Unfortunately, I don't have Python 3.3 installed for Ubuntu yet since locating PyQt or PySide packages is difficult. I'll keep working on it.

**Comment by spyder-issues-migrator** [comment]
_From [eisenma...@gmail.com](https://code.google.com/u/108769617018310358912/) on 2013-04-07T13:27:41Z_

This is related to the use of the deprecated string.atoi. This same error persists in the 2.2.0 branch where I submitted an issue with a patch. Is it possible to pull the same patch into this branch as well?

**Attachment:** [patch.txt](http://code.google.com/p/spyderlib/issues/detail?id=1243#hc9)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-04-13T10:06:49Z_

Applied patch in revision 23cd860888bf .

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-04-13T10:08:57Z_

Applied patch on v21 branch as well: https://code.google.com/p/spyderlib/source/detail?r=affe2c9c95acd6a5f8c3c14531347d905ba58937&repo=v21

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-04-15T16:04:42Z_

I've tested this on Python 3.3 on Windows and Python 3.2 on Linux. Working fine in both situations now. It did require that I remove the .spyder2.ini file and start fresh, but we knew that would be required already based upon comments 6 and 7.

**Status:** Verified
