### ISSUE TITLE
Trying to import Windows-only module _winreg on Ubuntu

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1244]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-01-31T00:42:02Z_

Spyder Version: v21 repo revision acc4392fd503 OS: Ubuntu 12.04
Python Version: 2.7 

What steps will reproduce the problem?

 1. Try to bootstrap v2.1 What is the expected output? What do you see instead? Traceback as follows:

$ ./bootstrap.py --gui pyqt
Executing Spyder from source checkout Revision 2074 :acc4392fd503, Branch: default
01. Patched sys.path with /home/<...>
                      and /home/<...>
02. Skipping GUI toolkit detection
Traceback (most recent call last):
  File "./bootstrap.py", line 89, in \<module>
    from spyderlib import spyder
  File "/home/<...>/spyderlib/spyder.py", line 30, in \<module>
    from spyderlib.utils.programs import is_module_installed
  File "/home/<...>/spyderlib/utils/programs.py", line 19, in \<module>
    from spyderlib.utils import encoding
  File "/home/<...>/spyderlib/utils/encoding.py", line 23, in \<module>
    from spyderlib.py3compat import (is_string, to_text_string, is_binary_string,
  File "/home/<...>/spyderlib/py3compat.py", line 34, in \<module>
    import _winreg as winreg
ImportError: No module named _winreg

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1244_

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-01-30T21:51:02Z_

This issue was updated by revision fbc795e2f4f9 .

Tested on Ubuntu 12.04 with Python 2.7 and Windows with Python 2.7 and 3.3.

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-01-30T21:52:30Z_

Here's a working link to the relevant revision: https://code.google.com/p/spyderlib/source/detail?r=fbc795e2f4f91d4d9d549f300ff04a55f3ab75dc&repo=v21

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-01-30T21:56:59Z_

**Summary:** Trying to import Windows-only module _winreg on Ubuntu  \<span class="oldvalue"> (was: Trying to import Windows-only module _winreg on Unbuntu) \</span>
