### ISSUE TITLE
Error when enabling code style linting.

### ISSUE THREAD

**Issue by nackerley** [spyder-ide/spyder#12468]
### What steps will reproduce the problem?

Go to Tools ... Preferences ... Completion and Linting ... Code Style and enable code style linting.

### Traceback
```python-traceback
  File "C:\Users\nackerle\AppData\Local\Continuum\anaconda3\envs\py3\lib\site-packages\spyder\app\mainwindow.py", line 3170, in show_preferences
    widget = plugin._create_configwidget(dlg, self)
  File "C:\Users\nackerle\AppData\Local\Continuum\anaconda3\envs\py3\lib\site-packages\spyder\plugins\base.py", line 117, in _create_configwidget
    configwidget.initialize()
  File "C:\Users\nackerle\AppData\Local\Continuum\anaconda3\envs\py3\lib\site-packages\spyder\preferences\configdialog.py", line 72, in initialize
    self.load_from_conf()
  File "C:\Users\nackerle\AppData\Local\Continuum\anaconda3\envs\py3\lib\site-packages\spyder\preferences\configdialog.py", line 327, in load_from_conf
    checkbox.setChecked(self.get_option(option, default, section=sec))
TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'
Traceback (most recent call last):
  File "C:\Users\nackerle\AppData\Local\Continuum\anaconda3\envs\py3\lib\site-packages\spyder\app\mainwindow.py", line 3170, in show_preferences
    widget = plugin._create_configwidget(dlg, self)
  File "C:\Users\nackerle\AppData\Local\Continuum\anaconda3\envs\py3\lib\site-packages\spyder\plugins\base.py", line 117, in _create_configwidget
    configwidget.initialize()
  File "C:\Users\nackerle\AppData\Local\Continuum\anaconda3\envs\py3\lib\site-packages\spyder\preferences\configdialog.py", line 72, in initialize
    self.load_from_conf()
  File "C:\Users\nackerle\AppData\Local\Continuum\anaconda3\envs\py3\lib\site-packages\spyder\preferences\configdialog.py", line 327, in load_from_conf
    checkbox.setChecked(self.get_option(option, default, section=sec))
TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'
Traceback (most recent call last):
  File "C:\Users\nackerle\AppData\Local\Continuum\anaconda3\envs\py3\lib\site-packages\spyder\app\mainwindow.py", line 3170, in show_preferences
    widget = plugin._create_configwidget(dlg, self)
  File "C:\Users\nackerle\AppData\Local\Continuum\anaconda3\envs\py3\lib\site-packages\spyder\plugins\base.py", line 117, in _create_configwidget
    configwidget.initialize()
  File "C:\Users\nackerle\AppData\Local\Continuum\anaconda3\envs\py3\lib\site-packages\spyder\preferences\configdialog.py", line 72, in initialize
    self.load_from_conf()
  File "C:\Users\nackerle\AppData\Local\Continuum\anaconda3\envs\py3\lib\site-packages\spyder\preferences\configdialog.py", line 327, in load_from_conf
    checkbox.setChecked(self.get_option(option, default, section=sec))
TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'
```

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.6
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.1 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)

# Spyder plugins:
spyder_line_profiler           :  0.2.0 (OK)
```

**Comment by ccordoba12** [comment]
I'm unable to reproduce this. Please close Spyder, open the Anaconda Prompt and activate your env, run there

    spyder --reset

and try again. That should fix your problem.
