### ISSUE TITLE
change python interpreter to diff environment interpreter

### ISSUE THREAD

**Issue by jat-247** [spyder-ide/spyder#12462]
### What steps will reproduce the problem?

I changed the python.exe to use to a different environment through Tools->Preferences->Python interpreter->Use the following Python interpreter. Unfortunately this caused the spyder console to bomb out with errors about ModuleNotFoundError.

### Traceback
```python-traceback
  File "C:\Users\Alex\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 172, in <lambda>
    self.exit_callback = lambda: plugin.close_client(client=self)
  File "C:\Users\Alex\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 1022, in close_client
    self.create_new_client()
  File "C:\Users\Alex\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 703, in create_new_client
    self.register_client(client)
  File "C:\Users\Alex\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 918, in register_client
    shellwidget.set_cwd(cwd_path)
  File "C:\Users\Alex\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 178, in set_cwd
    self.call_kernel(interrupt=True).set_cwd(dirname)
  File "C:\Users\Alex\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 538, in __call__
    call_dict, call_data, self._comm_id)
  File "C:\Users\Alex\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 130, in _get_call_return_value
    with self.comm_channel_manager(comm_id, queue_message=not interrupt):
  File "C:\Users\Alex\anaconda3\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Users\Alex\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 87, in comm_channel_manager
    timeout)
  File "C:\Users\Alex\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 168, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for comm port.
WARNING:traitlets:kernel died: 45.000494956970215
WARNING:traitlets:kernel died: 45.00023293495178
WARNING:traitlets:kernel died: 45.00018811225891
WARNING:traitlets:kernel died: 45.00013971328735
```

## Versions

* Spyder version: 4.1.2 
* Python version: 3.6.10
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
> Unfortunately this caused the spyder console to bomb out with errors about ModuleNotFoundError.

Please post that error because it's not part of the traceback you posted above and it'll help us to understand how to fix this issue.

**Comment by jat-247** [comment]
The Traceback you saw was from the iPython console within Spyder when trying to restart the kernal (because it wasn't loading). I closed Spyder after making that python.exe change and now when trying to open Spyder through Anaconda Navigator I get the following message (and Spyder does not open):

```
Traceback (most recent call last):
File "C:\Users\Alex\anaconda3\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\Alex\anaconda3\lib\site-packages\spyder\app\start.py", line 205, in main
mainwindow.main()
File "C:\Users\Alex\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3734, in main
mainwindow = run_spyder(app, options, args)
File "C:\Users\Alex\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3590, in run_spyder
main.setup()
File "C:\Users\Alex\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 939, in setup
from spyder.plugins.ipythonconsole.plugin import IPythonConsole
File "C:\Users\Alex\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 46, in 
from spyder.plugins.ipythonconsole.widgets import (ClientWidget,
File "C:\Users\Alex\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\__init__.py", line 16, in 
from .debugging import DebuggingWidget
File "C:\Users\Alex\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 22, in 
from IPython.core.inputtransformer2 import TransformerManager
ModuleNotFoundError: No module named 'IPython.core.inputtransformer2'
```
![SpyderLaunchError](https://user-images.githubusercontent.com/29551496/80127160-ed6eb980-8561-11ea-8f24-6897c096fd68.jpg)

**Comment by ccordoba12** [comment]
This looks like an installation issue and not related to Spyder.
