### ISSUE TITLE
Spyder crash on startup

### ISSUE THREAD

**Issue by ryan-j-hope** [spyder-ide/spyder#12502]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ryan-j-hope** [comment]
Spyder will not load and crashes during startup when launching from Anaconda. Spyder closes and nothing happens.

When launching from a bash terminal I receive the following tracebacks:

Traceback (most recent call last):
  File "/Users/ryanjhope/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/Users/ryanjhope/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 205, in main
    mainwindow.main()
  File "/Users/ryanjhope/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3734, in main
    mainwindow = run_spyder(app, options, args)
  File "/Users/ryanjhope/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3590, in run_spyder
    main.setup()
  File "/Users/ryanjhope/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 939, in setup
    from spyder.plugins.ipythonconsole.plugin import IPythonConsole
  File "/Users/ryanjhope/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 24, in <module>
    from jupyter_client.connect import find_connection_file
  File "/Users/ryanjhope/anaconda3/lib/python3.7/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/Users/ryanjhope/anaconda3/lib/python3.7/site-packages/jupyter_client/connect.py", line 35, in <module>
    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
ImportError: cannot import name 'secure_write' from 'jupyter_core.paths' (/Users/ryanjhope/anaconda3/lib/python3.7/site-packages/jupyter_core/paths.py)

**Comment by ccordoba12** [comment]
To fix this problem please run

    conda update jupyter_core

**Comment by ccordoba12** [comment]
I meant in Terminal.app

**Comment by r3klaw** [comment]
I had the same issue, I solved mine by uninstalling pylint and reinstalling it.

**Comment by ManithChenda** [comment]
In case anyone is experiencing the crash after changing Spyder's theme, try running `spyder --reset` in your terminal.
It worked for me.
