### ISSUE TITLE
Spontaneous issue

### ISSUE THREAD

**Issue by tedtrebaol** [spyder-ide/spyder#12547]
### What steps will reproduce the problem?

I literally do nothing. Launch Spyder 4.1.1 from Anaconda and within a few minutes I get this error accompanied by a pop-up window advising me Spyder detected a screen resolution change which asks me to reset Spyder. My setup:
2019 MacBook Pro docked, with lid closed, to three 4K monitors all set to 1080x1024, two rotated vertically and the center one normal 16:9. I never had this problem with any previous version of Spyder.

### Traceback
```python-traceback
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 1392, in handle_new_screen


Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 1392, in handle_new_screen
    self.screen.logicalDotsPerInchChanged.disconnect(
RuntimeError: wrapped C/C++ object of type QScreen has been deleted
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 1392, in handle_new_screen
    self.screen.logicalDotsPerInchChanged.disconnect(
RuntimeError: wrapped C/C++ object of type QScreen has been deleted
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 1392, in handle_new_screen
    self.screen.logicalDotsPerInchChanged.disconnect(
RuntimeError: wrapped C/C++ object of type QScreen has been deleted
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 1392, in handle_new_screen
    self.screen.logicalDotsPerInchChanged.disconnect(
RuntimeError: wrapped C/C++ object of type QScreen has been deleted
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 1392, in handle_new_screen
    self.screen.logicalDotsPerInchChanged.disconnect(
RuntimeError: wrapped C/C++ object of type QScreen has been deleted
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 1392, in handle_new_screen
    self.screen.logicalDotsPerInchChanged.disconnect(
RuntimeError: wrapped C/C++ object of type QScreen has been deleted
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 1392, in handle_new_screen
    self.screen.logicalDotsPerInchChanged.disconnect(
RuntimeError: wrapped C/C++ object of type QScreen has been deleted
```

## Versions

* Spyder version: 4.1.1 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.4.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.2.2 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.11.1 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.7.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.7 (OK)
pygments >=2.0                 :  2.5.2 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.6.0 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.8.3 (OK)
sphinx >=0.6.6                 :  2.3.1 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.0 (OK)

# Optional:
cython >=0.21                  :  0.29.14 (OK)
matplotlib >=2.0.0             :  3.1.1 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  0.25.3 (OK)
scipy >=0.17.0                 :  1.3.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by goanpeca** [comment]
@tedtrebaol thanks for the report. We have disabled those checks (causing the issue) on Mac on later versions.

Have you tried updating to 4.1.2?

`conda install spyder=4.1.2` should fix the issue.

Cheers!

**Comment by goanpeca** [comment]
Closing due to lack of response.
