### ISSUE TITLE
missing fonts, spyder wont start

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1255]
_From [cpelley....@gmail.com](https://code.google.com/u/114813423610590280119/) on 2013-02-06T05:56:43Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. installed shiboken(v1.1.2) + pyside(v1.1.2) from source
2. installed spyder(v2.1.13) from source
3. run spyder What is the expected output? What do you see instead? the program crashes immediately with the error:

Warning: None of the following fonts is installed: ['Monospace', 'DejaVu Sans Mono', 'Consolas', 'Monaco', 'Bitstream Vera Sans Mono', 'Andale Mono', 'Liberation Mono', 'Courier New', 'Courier', 'monospace', 'Fixed', 'Terminal']
Warning: None of the following fonts is installed: ['Monospace', 'DejaVu Sans Mono', 'Consolas', 'Monaco', 'Bitstream Vera Sans Mono', 'Andale Mono', 'Liberation Mono', 'Courier New', 'Courier', 'monospace', 'Fixed', 'Terminal']
Warning: None of the following fonts is installed: ['Monospace', 'DejaVu Sans Mono', 'Consolas', 'Monaco', 'Bitstream Vera Sans Mono', 'Andale Mono', 'Liberation Mono', 'Courier New', 'Courier', 'monospace', 'Fixed', 'Terminal']
Traceback (most recent call last):
  File "spyder.py", line 2001, in main
    mainwindow = run_spyder(app, options)
  File "spyder.py", line 1913, in run_spyder
    main.setup()
  File "spyder.py", line 649, in setup
    self.workingdirectory = WorkingDirectory(self, self.init_workdir)
  File "/home/h05/cpelley/.local/lib/python2.7/site-packages/spyderlib/plugins/workingdirectory.py", line 196, in __init__
    wdhistory = self.load_wdhistory( workdir )
  File "/home/h05/cpelley/.local/lib/python2.7/site-packages/spyderlib/plugins/workingdirectory.py", line 278, in load_wdhistory
    wdhistory = [name for name in wdhistory if os.path.isdir(name)]
  File "/usr/local/sci/lib/python2.7/genericpath.py", line 41, in isdir
    st = os.stat(s) What version of the product are you using? On what operating system? spyder(v2.1.13), shiboken(v1.1.2), pyside(v1.1.2) 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1255_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-13T08:44:42Z_

The problem is not with your fonts, it's with your working directory history, i.e. the list of working dirs you previously had selected.

Try removing .spyder2 from your home dir and restart again to see if it fixes the problem.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-03-12T08:42:50Z_

Please use PyQt because Spyder doesn't work too well with PySide.

There has been a month since your initial report without additional info, so I'm closing this.

**Status:** WontFix  
  **Labels:** -pyside -font Component-PySide

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-06-01T21:53:54Z_

Looks like it is not related to PySide after all.

**Summary:** missing fonts, spyder wont start  \<span class="oldvalue"> (was: missing fonts, spyder wont start (using pyside)) \</span>  
  **Labels:** -Component-PySide
