### ISSUE TITLE
Kernel died

### ISSUE THREAD

**Issue by dragonsan17** [spyder-ide/spyder#12554]
## Problem Description

I was installing some dependencies. When I restarted the kernel, it shows error that it died and it's restarting.
### What steps reproduce the problem?

1. 
2. 
3. 

### What is the expected output? What do you see instead?

Kernel died, restarting

### Paste Traceback/Error Below (if applicable)
```traceback
Traceback (most recent call last):
File "C:\Users\lenovo\anaconda3\envs\pl\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\lenovo\anaconda3\envs\pl\lib\site-packages\spyder\app\start.py", line 205, in main
mainwindow.main()
File "C:\Users\lenovo\anaconda3\envs\pl\lib\site-packages\spyder\app\mainwindow.py", line 3734, in main
mainwindow = run_spyder(app, options, args)
File "C:\Users\lenovo\anaconda3\envs\pl\lib\site-packages\spyder\app\mainwindow.py", line 3590, in run_spyder
main.setup()
File "C:\Users\lenovo\anaconda3\envs\pl\lib\site-packages\spyder\app\mainwindow.py", line 939, in setup
from spyder.plugins.ipythonconsole.plugin import IPythonConsole
File "C:\Users\lenovo\anaconda3\envs\pl\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 46, in 
from spyder.plugins.ipythonconsole.widgets import (ClientWidget,
File "C:\Users\lenovo\anaconda3\envs\pl\lib\site-packages\spyder\plugins\ipythonconsole\widgets\__init__.py", line 16, in 
from .debugging import DebuggingWidget
File "C:\Users\lenovo\anaconda3\envs\pl\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 13, in 
import pdb
File "C:\Users\lenovo\anaconda3\envs\pl\lib\pdb.py", line 136, in 
class Pdb(bdb.Bdb, cmd.Cmd):
AttributeError: module 'cmd' has no attribute 'Cmd'
```

## Versions

* Spyder version: 4.1.2
* Python version: 3.6
* Qt version: 4.7.3
* PyQt version: Not installed
* Operating System name/version: Windows 10

### Dependencies
```bash
_tflow_select             2.2.0                     eigen
absl-py                   0.9.0                    py36_0
alabaster                 0.7.12                   pypi_0    pypi
argh                      0.26.2                   pypi_0    pypi
asn1crypto                1.3.0                    py36_0
astor                     0.8.0                    py36_0
atomicwrites              1.3.0                    pypi_0    pypi
attrs                     19.3.0                   pypi_0    pypi
backcall                  0.1.0                    pypi_0    pypi
blas                      1.0                         mkl
blinker                   1.4                      py36_0
ca-certificates           2020.1.1                      0
cachetools                3.1.1                      py_0
certifi                   2020.4.5.1               py36_0
cffi                      1.14.0           py36h7a1dbc1_0
chardet                   3.0.4                 py36_1003
click                     7.1.1                      py_0
click-plugins             1.1.1                      py_0
cloudpickle               1.4.0                    pypi_0    pypi
colorama                  0.4.3                    pypi_0    pypi
console_shortcut          0.1.1                         4
cryptography              2.8              py36h7a1dbc1_0
cycler                    0.10.0           py36h009560c_0
decorator                 4.4.2                    pypi_0    pypi
defusedxml                0.6.0                    pypi_0    pypi
diff-match-patch          20181111                 pypi_0    pypi
docutils                  0.16                     pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
freetype                  2.9.1                ha9979f8_1
future                    0.18.2                   pypi_0    pypi
gast                      0.2.2                    py36_0
google-auth               1.13.1                     py_0
google-auth-oauthlib      0.4.1                      py_2
google-pasta              0.2.0                      py_0
grpcio                    1.27.2           py36h351948d_0
h5py                      2.10.0           py36h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      2.9                        py_1
imagesize                 1.2.0                    pypi_0    pypi
importlib_metadata        1.5.0                    py36_0
intel-openmp              2020.0                      166
ipython-genutils          0.2.0                    pypi_0    pypi
jpeg                      9b                   hb83a4c4_2
jsonpickle                1.4.1                      py_0
keras                     2.3.1                         0
keras-applications        1.0.8                      py_0
keras-base                2.3.1                    py36_0
keras-preprocessing       1.1.0                      py_1
kiwisolver                1.1.0            py36ha925a31_0
lazy-object-proxy         1.4.3                    pypi_0    pypi
libpng                    1.6.37               h2a8f88b_0
libprotobuf               3.11.4               h7bd577a_0
libtiff                   4.1.0                h56a325e_0
markdown                  3.1.1                    py36_0
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.1.3                    py36_0
matplotlib-base           3.1.3            py36h64f37c6_0
mccabe                    0.6.1                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mkl                       2020.0                      166
mkl-service               2.3.0            py36hb782905_0
mkl_fft                   1.0.15           py36h14836fe_0
mkl_random                1.1.0            py36h675688f_0
numpy                     1.18.1           py36h93ca92e_0
numpy-base                1.18.1           py36hc3f5095_1
oauthlib                  3.1.0                      py_0
opencv                    3.3.1            py36h20b85fd_1
openssl                   1.1.1g               he774522_0
opt_einsum                3.1.0                      py_0
pandocfilters             1.4.2                    pypi_0    pypi
parso                     0.5.2                    pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pip                       20.0.2                   py36_1
protobuf                  3.11.4           py36h33f27b4_0
psutil                    5.7.0                    pypi_0    pypi
pyasn1                    0.4.8                      py_0
pyasn1-modules            0.2.7                      py_0
pycodestyle               2.5.0                    pypi_0    pypi
pycparser                 2.20                       py_0
pyflakes                  2.1.1                    pypi_0    pypi
pyjwt                     1.7.1                    py36_0
pyopenssl                 19.1.0                   py36_0
pyparsing                 2.4.6                      py_0
pyqt                      5.9.2            py36h6538335_2
pyreadline                2.1                      py36_1
pysocks                   1.7.1                    py36_0
python                    3.6.10               h9f7ef89_1
python-dateutil           2.8.1                      py_0
pytz                      2019.3                   pypi_0    pypi
pywin32                   227                      pypi_0    pypi
pyyaml                    5.3.1            py36he774522_0
qt                        5.9.7            vc14h73c81de_0
requests                  2.23.0                   py36_0
requests-oauthlib         1.3.0                      py_0
rsa                       4.0                        py_0
scipy                     1.4.1            py36h9439919_0
setuptools                46.1.3                   py36_0
simplegeneric             0.8.1                    py36_2
sip                       4.19.8           py36h6538335_0
six                       1.14.0                   py36_0
sqlite                    3.31.1               h2a8f88b_1
tensorboard               2.1.0                     py3_0
tensorflow                2.1.0           eigen_py36hdbbabfe_0
tensorflow-base           2.1.0           eigen_py36h49b2757_0
tensorflow-estimator      2.1.0              pyhd54b08b_0
termcolor                 1.1.0                    py36_1
tornado                   6.0.4            py36he774522_1
urllib3                   1.25.8                   py36_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
werkzeug                  0.16.1                     py_0
wheel                     0.34.2                   py36_0
win_inet_pton             1.1.0                    py36_0
wincertstore              0.2              py36h7fe50ca_0
wrapt                     1.12.1           py36he774522_1
xz                        5.2.5                h62dcd97_0
yaml                      0.1.7                hc54c509_2
zipp                      2.2.0                      py_0
zlib                      1.2.11               h62dcd97_4
zstd                      1.3.7                h508b16e_0
```

**Comment by goanpeca** [comment]
Hi @dragonsan17 

Usually what this means is that you are masking a module. If you are unfamiliar with this, what it means is that somewhere in your PYTHONPATH (or in your installed packages), there is a cmd module or package in the top-level namespace that conflicts with the standard library module. As a result, pdb actually imports a different cmd module than it is trying to, one that does not have a Cmd class.

What is the output of this command:

`python -c "import cmd; print(cmd.__file__)"` ?

Or if you know where that other cmd module is coming from, either remove it or take it out of your PYTHONPATH (and if it is some of your Python code, rename the module to something not in the stdlib).

Cheers!

**Comment by dragonsan17** [comment]
Thank you so much. That worked

**Comment by goanpeca** [comment]
Glad to be of help @dragonsan17 !
