### ISSUE TITLE
An error ocurred while starting the kernel: b''

### ISSUE THREAD

**Issue by adityaneer** [spyder-ide/spyder#12576]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am getting the above error while running a simple program on Spyder. And whenever I am using the exit() or quit() command, I am getting this error. I tried many a things while going through the web and it did not help me. i am also a bit new with python. Please find the below code:

hrs = input("Enter Hours:")
rate = input("Enter Rate:")
try:
    h = float(hrs)
    r = float(rate)
except:
    print("Error, Please try a numerical input")
    exit()
print(h,r)
#Pay for hours upto 40 is standard rate
if h <= 40:
    pay = h*r
    print(pay)
#Pay for hours more than 40 is 1.5 times the standard rate
else:
    h1 = h-40
    pay1 = h*r
    pay2 = h1*0.5*r
    pay = pay1 + pay2
    print(pay)

### What steps reproduce the problem?

1. Run the program.
2.  Input any one of hours or rate as a string value. for ex: ten, me etc etc

### What is the expected output? What do you see instead?

The expected output is "Error, Please try a numerical input" and the program ends but instead I get the error.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.2
* Python version: 3.7.1 64-bit
* Qt version: Qt 5.9.6
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```
IPython >=4.0     :  7.13.0 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.17.0 (OK)
matplotlib >=2.0.0:  None (NOK)
nbconvert >=4.0   :  5.6.1 (OK)
numpy >=1.7       :  None (NOK)
pandas >=0.13.1   :  None (NOK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.2.0 (OK)
pygments >=2.0    :  2.6.1 (OK)
pylint >=0.25     :  2.5.0 (OK)
qtconsole >=4.2.0 :  4.7.3 (OK)
rope >=0.9.4      :  0.16.0 (OK)
sphinx >=0.6.6    :  3.0.3 (OK)
sympy >=0.7.3     :  None (NOK)

**Comment by adityaneer** [comment]
Once Spyder has been updated, spyder itself is not opening:

Traceback (most recent call last):
File "E:\Anaconda 3\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "E:\Anaconda 3\lib\site-packages\spyder\app\start.py", line 205, in main
mainwindow.main()
File "E:\Anaconda 3\lib\site-packages\spyder\app\mainwindow.py", line 3734, in main
mainwindow = run_spyder(app, options, args)
File "E:\Anaconda 3\lib\site-packages\spyder\app\mainwindow.py", line 3590, in run_spyder
main.setup()
File "E:\Anaconda 3\lib\site-packages\spyder\app\mainwindow.py", line 977, in setup
'spyder.plugins.{}'.format(plugin_name))
File "E:\Anaconda 3\lib\importlib\__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1006, in _gcd_import
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "", line 728, in exec_module
File "", line 219, in _call_with_frames_removed
File "E:\Anaconda 3\lib\site-packages\spyder\plugins\pylint\__init__.py", line 14, in 
from .plugin import Pylint as PLUGIN_CLASS
File "E:\Anaconda 3\lib\site-packages\spyder\plugins\pylint\plugin.py", line 29, in 
from spyder.plugins.pylint.confpage import PylintConfigPage
File "E:\Anaconda 3\lib\site-packages\spyder\plugins\pylint\confpage.py", line 16, in 
from spyder.plugins.pylint.widgets.pylintgui import PylintWidget
File "E:\Anaconda 3\lib\site-packages\spyder\plugins\pylint\widgets\pylintgui.py", line 37, in 
from spyder.plugins.pylint.utils import get_pylintrc_path
File "E:\Anaconda 3\lib\site-packages\spyder\plugins\pylint\utils.py", line 16, in 
import pylint.config
File "E:\Anaconda 3\lib\site-packages\pylint\config.py", line 54, in 
import toml
ModuleNotFoundError: No module named 'toml'

**Comment by ccordoba12** [comment]
Please open the Anaconda Prompt and run there

    conda install toml

to fix this.

**Comment by adityaneer** [comment]
Thanks, it worked.
