### ISSUE TITLE
Error opening Spyder with Miniconda on macOS

### ISSUE THREAD

**Issue by MarioCatuogno** [spyder-ide/spyder#12593]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When i launch the command `conda run spyder` from my conda environment (named devPython) I get an error message and I cannot open Spyder. I've already uninstalled miniconda and reinstalled all the stuff (Python packages, environment, ecc.)

### What steps reproduce the problem?

1. run `conda activate devPython`
2. run `conda run spyder`
3. 

### What is the expected output? What do you see instead?

The expected output is to get Spyder open, but instead i get this error message:

### Paste Traceback/Error Below (if applicable)

```python-traceback

ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['spyder']' command failed.  (See above for error)
Traceback (most recent call last):
  File "/Users/mariocatuogno/miniconda/envs/devPython/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/Users/mariocatuogno/miniconda/envs/devPython/lib/python3.7/site-packages/spyder/app/start.py", line 205, in main
    mainwindow.main()
  File "/Users/mariocatuogno/miniconda/envs/devPython/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3734, in main
    mainwindow = run_spyder(app, options, args)
  File "/Users/mariocatuogno/miniconda/envs/devPython/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3590, in run_spyder
    main.setup()
  File "/Users/mariocatuogno/miniconda/envs/devPython/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 977, in setup
    'spyder.plugins.{}'.format(plugin_name))
  File "/Users/mariocatuogno/miniconda/envs/devPython/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/mariocatuogno/miniconda/envs/devPython/lib/python3.7/site-packages/spyder/plugins/pylint/__init__.py", line 14, in <module>
    from .plugin import Pylint as PLUGIN_CLASS
  File "/Users/mariocatuogno/miniconda/envs/devPython/lib/python3.7/site-packages/spyder/plugins/pylint/plugin.py", line 29, in <module>
    from spyder.plugins.pylint.confpage import PylintConfigPage
  File "/Users/mariocatuogno/miniconda/envs/devPython/lib/python3.7/site-packages/spyder/plugins/pylint/confpage.py", line 16, in <module>
    from spyder.plugins.pylint.widgets.pylintgui import PylintWidget
  File "/Users/mariocatuogno/miniconda/envs/devPython/lib/python3.7/site-packages/spyder/plugins/pylint/widgets/pylintgui.py", line 37, in <module>
    from spyder.plugins.pylint.utils import get_pylintrc_path
  File "/Users/mariocatuogno/miniconda/envs/devPython/lib/python3.7/site-packages/spyder/plugins/pylint/utils.py", line 16, in <module>
    import pylint.config
  File "/Users/mariocatuogno/miniconda/envs/devPython/lib/python3.7/site-packages/pylint/config.py", line 54, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
```

## Versions

* Spyder version: 4.1.2
* Python version: 3.7.7
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: macOS Catalina 10.15.4

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by goanpeca** [comment]
Hi @MarioCatuogno , thanks for reporting. This is an issue with latest pylint package that Anaconda release. We have already requested the fix. In the meantime please install toml manually

Open a terminal and enter

`conda install toml`

Cheers!
