### ISSUE TITLE
Hello: I'm getting this error wheneever I attempt to open Spyder after updating to the latest version:

### ISSUE THREAD

**Issue by asnigh0316** [spyder-ide/spyder#12604]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by asnigh0316** [comment]
Traceback (most recent call last):
File "/opt/anaconda3/envs/Sympy/bin/spyder", line 11, in 
sys.exit(main())
File "/opt/anaconda3/envs/Sympy/lib/python3.7/site-packages/spyder/app/start.py", line 205, in main
mainwindow.main()
File "/opt/anaconda3/envs/Sympy/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3734, in main
mainwindow = run_spyder(app, options, args)
File "/opt/anaconda3/envs/Sympy/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3590, in run_spyder
main.setup()
File "/opt/anaconda3/envs/Sympy/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 977, in setup
'spyder.plugins.{}'.format(plugin_name))
File "/opt/anaconda3/envs/Sympy/lib/python3.7/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1006, in _gcd_import
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "", line 728, in exec_module
File "", line 219, in _call_with_frames_removed
File "/opt/anaconda3/envs/Sympy/lib/python3.7/site-packages/spyder/plugins/pylint/__init__.py", line 14, in 
from .plugin import Pylint as PLUGIN_CLASS
File "/opt/anaconda3/envs/Sympy/lib/python3.7/site-packages/spyder/plugins/pylint/plugin.py", line 29, in 
from spyder.plugins.pylint.confpage import PylintConfigPage
File "/opt/anaconda3/envs/Sympy/lib/python3.7/site-packages/spyder/plugins/pylint/confpage.py", line 16, in 
from spyder.plugins.pylint.widgets.pylintgui import PylintWidget
File "/opt/anaconda3/envs/Sympy/lib/python3.7/site-packages/spyder/plugins/pylint/widgets/pylintgui.py", line 37, in 
from spyder.plugins.pylint.utils import get_pylintrc_path
File "/opt/anaconda3/envs/Sympy/lib/python3.7/site-packages/spyder/plugins/pylint/utils.py", line 16, in 
import pylint.config
File "/opt/anaconda3/envs/Sympy/lib/python3.7/site-packages/pylint/config.py", line 54, in 
import toml
ModuleNotFoundError: No module named 'toml'

**Comment by goanpeca** [comment]
Hi @asnigh0316, thanks for reporting.

This is an issue with latest pylint (conda) package that Anaconda release. We have already requested the fix. In the meantime please install `toml` manually

Open a terminal and enter

```
conda install toml
```

Cheers!
