### ISSUE TITLE
IPython kernel/clients: error when closing an IPython console

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1261]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-02-10T05:47:34Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. Open a new IPython console
2. Open an IPython console connected to the existing kernel (created at step 1)
3. Close the second IPython console and answer Yes to the message box What is the expected output? What do you see instead? The consoles should be closed as requested. Instead, only the kernel is closed and the following traceback is shown in the internal console:

\>>> Traceback (most recent call last):
  File "D:\Python\spyder\spyderlib\plugins\ipythonconsole.py", line 1049, in close_console
    self.close_related_ipyclients(client)
  File "D:\Python\spyder\spyderlib\plugins\ipythonconsole.py", line 991, in close_related_ipyclients
    self.close_console(widget=cl)
TypeError: close_console() got an unexpected keyword argument 'widget'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1261_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-02-10T04:29:35Z_

This issue was updated by revision 32fd57d5b089 .

**Status:** Fixed
