### ISSUE TITLE
Spyder crash (after rdp install?)

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1262]
_From [yus.budi...@gmail.com](https://code.google.com/u/106798745831407706923/) on 2013-02-11T04:15:18Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. Calling spyder What is the expected output? What do you see instead? Spyder IDE window What version of the product are you using? On what operating system? Spyder 2.1.10-2 on Linux Mint Debian Edition (Debian Testing) 

Please provide any additional information below

. I just install xrdp in my machine, play with remote computer, then I cannot have Spyder IDE anymore. I think it relates to port management between Spyder and rdp. This is what's shown in the terminal.

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 2006, in main
    mainwindow = run_spyder(app, options)
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 1927, in run_spyder
    main.post_visible_setup()
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 953, in post_visible_setup
    self.extconsole.open_interpreter_at_startup()
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/externalconsole.py", line 1092, in open_interpreter_at_startup
    self.open_interpreter()
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/externalconsole.py", line 1101, in open_interpreter
    interact=True, debug=False, python=True)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/externalconsole.py", line 851, in start
    shellwidget.start_shell()
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/baseshell.py", line 232, in start_shell
    self.create_process()
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/pythonshell.py", line 411, in create_process
    introspection_server = introspection.start_introspection_server()
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/introspection.py", line 106, in start_introspection_server
    INTROSPECTION_SERVER = IntrospectionServer()
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/introspection.py", line 37, in __init__
    self.port = SPYDER_PORT = select_port(default_port=SPYDER_PORT)
  File "/usr/lib/python2.7/dist-packages/spyderlib/utils/misc.py", line 57, in select_port
    sock.bind( ("127.0.0.1", default_port) )
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
OverflowError: getsockaddrarg: port must be 0-65535.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1262_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-11T04:53:40Z_

It seems that all ports on your machine are taken. We need to open a port to communicate back and forth with Python external processes.

So I think you need to close/uninstall xrdp or restart your machine to reset your ports state.

**Comment by spyder-issues-migrator** [comment]
_From [yus.budi...@gmail.com](https://code.google.com/u/106798745831407706923/) on 2013-02-13T02:12:58Z_

Thank you.
It's sad that I don't know how to manage ports in Linux or RDP in particular. Apparently, the problem also occur when open new xwindow, eg. on tty8-tty12.

**Comment by spyder-issues-migrator** [comment]
_From [yus.budi...@gmail.com](https://code.google.com/u/106798745831407706923/) on 2013-02-15T21:11:30Z_

After playing with ports in xrdp.ini (and unsuccessful), I simply did:
$ sudo apt-get remove --purge xrdp vnc4server

I'm happy to have Spyder back.

Btw, I want to cite to Spyder in my paper. How can I do this?

Than you.

Yus

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-02-16T05:48:56Z_

**Status:** Invalid

**Comment by spyder-issues-migrator** [comment]
_From [crema.st...@gmail.com](https://code.google.com/u/107606024419260622354/) on 2015-01-09T02:09:23Z_

I resolved re setting into /etc/network/interfaces the 
auto lo
iface lo inet loopback
