### ISSUE TITLE
Sypder crashes when using PulP

### ISSUE THREAD

**Issue by Nosferuity** [spyder-ide/spyder#12630]
### What steps will reproduce the problem?

executting the code as in 
Spyder crashes when using pulp #12486
bot said issue will be fixed with 4.1.2 however issue persists

### Traceback
```python-traceback
  File "C:\Users\Frederik\.conda\envs\ma\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Frederik\.conda\envs\ma\lib\site-packages\psutil\_pswindows.py", line 868, in send_signal
    cext.proc_kill(self.pid)
PermissionError: [WinError 5] Zugriff verweigert

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Frederik\.conda\envs\ma\lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 516, in finalize_shutdown
    self.shellwidget.kernel_manager.shutdown_kernel()
  File "C:\Users\Frederik\.conda\envs\ma\lib\site-packages\jupyter_client\manager.py", line 377, in shutdown_kernel
    self.finish_shutdown()
  File "C:\Users\Frederik\.conda\envs\ma\lib\site-packages\jupyter_client\manager.py", line 338, in finish_shutdown
    self._kill_kernel()
  File "C:\Users\Frederik\.conda\envs\ma\lib\site-packages\spyder\plugins\ipythonconsole\utils\manager.py", line 86, in _kill_kernel
    self.kill_proc_tree(self.kernel.pid)
  File "C:\Users\Frederik\.conda\envs\ma\lib\site-packages\spyder\plugins\ipythonconsole\utils\manager.py", line 59, in kill_proc_tree
    child_process.send_signal(sig)
  File "C:\Users\Frederik\.conda\envs\ma\lib\site-packages\psutil\__init__.py", line 292, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Frederik\.conda\envs\ma\lib\site-packages\psutil\__init__.py", line 1214, in send_signal
    self._proc.send_signal(sig)
  File "C:\Users\Frederik\.conda\envs\ma\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=8140)
```

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by dalthviz** [comment]
Hi @Nosferuity thanks for letting us know! Seems like the traceback changed so we will address this in a future release :+1: 

Also, if you found any other relevant info that could help us understand why this is happening, please post it here, we will greatly appreciate it :)

**Comment by Nosferuity** [comment]
Hi @dalthviz, you are very welcome as i enjoy working with spyder a lot.
it is hard for me to provide relevant hard information on this bug as it is not 100% reliably reproducible. But here is what i know.

1) Sometimes the kernel crashes and restarts;
2) Sometimes i get a red warning in the console like:
[IPKernelApp] WARNING | No such comm: ff4d8e808fc011ea934b482ae33975e2
3) Sometimes the and i have to stress this: "same identical code" runs just fine, and solves (gives me a solution for my linear problem)

Sometimes i get stuck with multiple type 1) "events" in a row. Restarting Spyder helps in some cases.

As i said i can not really pin down the occurence of this error to some variation of my project code. I only know it happens more often for bigger linear problems. For small linear problems it never happens. 

In the meantime i found a very old stackoverflow entry indicating that this error might happen with psutil<6.0 so i upgraded. But the problem still persists for me. https://stackoverflow.com/questions/7349854/python-psutil-on-windows-gives-access-denied#7350792

I attached the updated list of installed conda packages in a txt to this post.
[condalist.txt](https://github.com/spyder-ide/spyder/files/4588512/condalist.txt)

If you can instruct me how to extract more useful information from spyder i will gladly do so :)
