### ISSUE TITLE
Recognize file path in cython error messages

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1263]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2013-02-11T10:18:47Z_

Spyder Version:  2.1.10
Python Version:  2.7.3
Qt Version:      4.8.2, PyQt4 (API v1) 4.9.3 on Linux 

What steps will reproduce the problem?

 1. try to compile a faulty cython file with pyximport:
In bad_cython_file.pyx:
    cpdef main():
        return undeclared

In test_bad_cython_file.py:
    import pyximport
    pyximport.install()
    import bad_cython_file
2. Enjoy the error message :
Error compiling Cython file:
\------------------------------------------------------------
...
cpdef main():
    return undeclared                    ^
\------------------------------------------------------------

bug_cython.pyx:2:21: undeclared name not builtin: undeclared
/home/joseph/.pyxbld/temp.linux-x86_64-2.7/pyrex/bug_cython.c:1:2: erreur: #error Do not use this file, it is the result of a failed Cython compilation.
Traceback (most recent call last):
  File "/data/lib/python/bugcython.py", line 3, in \<module>
    import bug_cython
  File "/usr/lib/python2.7/dist-packages/pyximport/pyximport.py", line 365, in load_module
    self.pyxbuild_dir)
  File "/usr/lib/python2.7/dist-packages/pyximport/pyximport.py", line 199, in load_module
    so_path = build_module(module_name, pyxfilename, pyxbuild_dir)
  File "/usr/lib/python2.7/dist-packages/pyximport/pyximport.py", line 179, in build_module
    reload_support=pyxargs.reload_support)
  File "/usr/lib/python2.7/dist-packages/pyximport/pyxbuild.py", line 85, in pyx_to_dll
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/Cython/Distutils/build_ext.py", line 163, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib/python2.7/dist-packages/Cython/Distutils/build_ext.py", line 171, in build_extensions
    self.build_extension(ext)
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 498, in build_extension
    depends=ext.depends)
  File "/usr/lib/python2.7/distutils/ccompiler.py", line 572, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python2.7/distutils/unixccompiler.py", line 180, in _compile
    raise CompileError, msg
ImportError: Building module bug_cython failed: ["CompileError: command 'gcc' failed with exit status 1\n"] What is the expected output? What do you see instead? Errors are reported, but the file in the .c and .pyx files are not recognized, so it is not possible to jump to the C source like with the python exceptions. The above example is totally dumb, but in real life it can be very useful to debug nasty bugs. 

Please provide any additional information below

. The cython version used is 0.16.
The paths are in the gcc format path/to/file:row:col:

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1263_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-06-29T14:01:03Z_

I know very few things about Cython to be of help, so if you want this to be solved, please send us a patch with the solution :)

**Status:** HelpNeeded

**Comment by justinkterry** [comment]
This affects me too. I see that it's added to the v4.0beta2, does that mean a fix will be inbound soon?

**Comment by ccordoba12** [comment]
No, 4.0 is planned to be out in a year or so, sorry.
