### ISSUE TITLE
problem to launch spyder after upgrade to 4.1.2

### ISSUE THREAD

**Issue by vittocal** [spyder-ide/spyder#12646]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I tried to upgrade the spyder version to 4.1.2. After the upgrade i'm not able to launch it both from Anaconda or from my app.
I installed the new version of spyder from the Anaconda prompt and also from the Anaconda app. I tried also to reset Spyder. Nothing changed.

### What steps reproduce the problem?

1. Open Anaconda
2. launch Spyder
3. 

### What is the expected output? What do you see instead?
Run and use Spyder as on my previous version 3.8.2

### Paste Traceback/Error Below (if applicable)
<Traceback (most recent call last):
File "C:\Users\vcalbucci\Anaconda3\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\vcalbucci\Anaconda3\lib\site-packages\spyder\app\start.py", line 201, in main
from spyder.app import mainwindow
File "C:\Users\vcalbucci\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 84, in 
from qtpy import QtWebEngineWidgets # analysis:ignore
File "C:\Users\vcalbucci\Anaconda3\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 22, in 
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ValueError: PyCapsule_GetPointer called with incorrect name

>

```python-traceback

Traceback (most recent call last):
  File "C:\Users\vcalbucci\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\vcalbucci\Anaconda3\lib\site-packages\spyder\app\start.py", line 173, in main
    from spyder.app import mainwindow
  File "C:\Users\vcalbucci\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "C:\Users\vcalbucci\Anaconda3\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ValueError: PyCapsule_GetPointer called with incorrect name


```

## Versions

* Spyder version: from 3.3.2 to 4.1.2
* Python version: 3.6
* Qt version: 
* PyQt version: pyqt5
* Operating System name/version:  windows 10 64bit

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by vittocal** [comment]
I uninstalled and reinstalled Anaconda. Now everything works fine and i have the version 4 of Spyder.
