### ISSUE TITLE
AttributeError: '_KiteEndpoints' object has no attribute 'STATUS_ENDPOINT'

### ISSUE THREAD

**Issue by Aathib** [spyder-ide/spyder#12674]
### What steps will reproduce the problem?

opening spyder in windows 2007 caused this error. 

### Traceback
```python-traceback
  File "C:\Users\aab\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 167, in perform_request
    response = handler(params)
  File "C:\Users\aab\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\decorators.py", line 20, in wrapper
    params = req(self, *args, **kwargs)
  File "C:\Users\aab\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\providers\document.py", line 83, in document_did_open
    self.get_status(params['file'])
  File "C:\Users\aab\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 110, in get_status
    success_status, kite_status = self._get_status(filename)
  File "C:\Users\aab\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 99, in _get_status
    verb, url = KITE_ENDPOINTS.STATUS_ENDPOINT
  File "C:\Users\aab\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\__init__.py", line 34, in __getattribute__
    value = object.__getattribute__(self, attr)
AttributeError: '_KiteEndpoints' object has no attribute 'STATUS_ENDPOINT'
Traceback (most recent call last):
  File "C:\Users\aab\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 167, in perform_request
    response = handler(params)
  File "C:\Users\aab\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\decorators.py", line 20, in wrapper
    params = req(self, *args, **kwargs)
  File "C:\Users\aab\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\providers\document.py", line 83, in document_did_open
    self.get_status(params['file'])
  File "C:\Users\aab\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 110, in get_status
    success_status, kite_status = self._get_status(filename)
  File "C:\Users\aab\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 99, in _get_status
    verb, url = KITE_ENDPOINTS.STATUS_ENDPOINT
  File "C:\Users\aab\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\__init__.py", line 34, in __getattribute__
    value = object.__getattribute__(self, attr)
AttributeError: '_KiteEndpoints' object has no attribute 'STATUS_ENDPOINT'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.

**Comment by dalthviz** [comment]
Hi @Aathib could you update Spyder and check if the error persists?

To update you can use something like the following from the Anaconda Prompt:
```cmd
conda install spyder=4.1.2
```
For now you can update to version `4.1.2` but hopefully in a couple of days you could update to the latests release (version `4.1.3`) :)

**Comment by dalthviz** [comment]
Closing due to lack of response.
