### ISSUE TITLE
Cannot open spyder in anaconda

### ISSUE THREAD

**Issue by tciuan** [spyder-ide/spyder#12785]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Can not open spyder. I have tried uninstall anaconda, install it on start-up drive. to all users. Shut down firewall.

### What steps reproduce the problem?

1. Open anaconda
2. click on launch Spyder

### What is the expected output? What do you see instead?
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3718, in main
mainwindow = run_spyder(app, options, args)
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3559, in run_spyder
main.setup()
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 955, in setup
self.editor = Editor(self)
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 178, in __init__
self.autosave.try_recover_from_autosave()
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 176, in try_recover_from_autosave
files_to_recover, pidfiles = self.get_files_to_recover()
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 149, in get_files_to_recover
txt_as_dict = ast.literal_eval(txt)
File "C:\ProgramData\Anaconda3\lib\ast.py", line 46, in literal_eval
node_or_string = parse(node_or_string, mode='eval')
File "C:\ProgramData\Anaconda3\lib\ast.py", line 35, in parse
return compile(source, filename, mode, PyCF_ONLY_AST)
File "", line 0

^
SyntaxError: unexpected EOF while parsing

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.0.1
* Python version: 3.4
* Qt version: 
* PyQt version: 
* Operating System name/version: Window 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by jitseniesen** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=4.1.3
