### ISSUE TITLE
Spyder Bootstrap script fails due to conda not on PATH when run from Git Bash on Win

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#12780]
### What steps will reproduce the problem?

@ccordoba Take note

I pulled the latest `4.x` in a separate spyder dev environment and installed the deps in `requirements/conda.txt` and `requirements/tests.txt`, but I got the following error running bootstrap.py on Windows when launching Spyder with Git Bash (which otherwise works just fine with `conda` after simply adding `. /c/Miniconda3/etc/profile.d/conda.sh` to my `~/.profile`). When I launch it once with Anaconda Prompt running the legacy cmd shell, it works, and then once I re-run it with Git Bash it subsequently works as well. 

Evidently, the issue is with `conda` not being on the `PATH` for Spyder while running under Git Bash, so that it can use it to uninstall PyLS and install the local dev version. When this check doesn't run on seqsequant executions, the problem is avoided.

```
(spyder-test)
C. A. M. Gerlach@QUASIMODO MINGW64 ~/Documents/dev/SpyderDev/spyder (4.x)
$ python bootstrap.py
Executing Spyder from source checkout
*. Patched sys.path with C:\Users\C. A. M. Gerlach\Documents\dev\SpyderDev\spyder
*. Patched sys.path with C:\Users\C. A. M. Gerlach\Documents\dev\SpyderDev\spyder\external-deps\python-language-server
*. Patched sys.path with C:\Users\C. A. M. Gerlach\Documents\dev\SpyderDev\spyder\external-deps\spyder-kernels
*. Removing stable version of the PyLS.
'conda' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "bootstrap.py", line 161, in <module>
    shell=True if os.name == 'nt' else False
  File "C:\Miniconda3\envs\spyder-test\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Miniconda3\envs\spyder-test\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['conda', 'list', 'python-language-server', '--json']' returned non-zero exit status 1.
```

## Versions

* Spyder version: 4.2.0.dev0 7a4ac26e7
* Python version: 3.7.5
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 8.1

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.0 (OK)
pyls >=0.31.9;<0.32.0          :  v4.1.3+44.g7a4ac26e7 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.4 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.3 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.10.0.dev0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.17 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
@CAM-Gerlach, is this still an issue for you? I think it shouldn't because we changed the way we use our subrepo for the PyLS.

**Comment by CAM-Gerlach** [comment]
It appears it works now; I installed a release version of PyLS from conda and then re-ran the script, and the install appears to be succesfull and Spyder launches; I also checked out previous release tags of the repo and it also worked there (again with a message that it was installing PyLS). So I believe this can be closed, thanks.
