### ISSUE TITLE
Include first __main__ caller in post-mortem debugger stack trace

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#12801]
Often it doesn't show nearly enough to tell where exactly the errored method was called from - e.g. if same method is called from different files. The final faulting line might be of no use to me - the culprit may instead lie far up the stack trace. It'd help to see the full trace that an exception would throw.

**Comment by OverLordGoldDragon** [comment]
To clarify, the post-mortem debugger seems to omit just one line from the trace - but that's enough; the line is from `__main__`, unsure if it happens elsewhere also.

**Comment by OverLordGoldDragon** [comment]
Indeed, it's only `__main__`, so a workaround is to wrap calls in dummy calls - but burdensome.

**Comment by goanpeca** [comment]
Thanks for the report @OverLordGoldDragon .

What do you think about this @impact27 ?

**Comment by impact27** [comment]
Can you provide steps to reproduce this issue?

**Comment by OverLordGoldDragon** [comment]
@impact27 If you're willing to install TensorFlow 1.14.0 - else, unclear how to reproduce.

```python
import tensorflow as tf
tf.metrics.categorical_crossentropy(0, 0)
```

<hr>

```
# DEBUGGER (regular)
  File "C:\Desktop\main.py", line 2, in <module>
    tf.metrics.categorical_crossentropy(0, 0)
  File "D:\Anaconda\envs\viz\lib\site-packages\tensorflow\python\util\deprecation_wrapper.py", line 106, in __getattr__
    attr = getattr(self._dw_wrapped_module, name)
AttributeError: module 'tensorflow._api.v1.metrics' has no attribute 'categorical_crossentropy'
```

```python
# POST-MORTEM
  File "D:\Anaconda\envs\viz\lib\site-packages\tensorflow\python\util\deprecation_wrapper.py", line 106, in __getattr__
    attr = getattr(self._dw_wrapped_module, name)
AttributeError: module 'tensorflow._api.v1.metrics' has no attribute 'categorical_crossentropy'

****************************************
Entering post mortem debugging...
****************************************
> d:\anaconda\envs\viz\lib\site-packages\tensorflow\python\util\deprecation_wrapper.py(106)__getattr__()
    104     if name.startswith('_dw_'):
    105       raise AttributeError('Accessing local variables before they are created.')
--> 106     attr = getattr(self._dw_wrapped_module, name)
    107     if (self._dw_warning_count < _PER_MODULE_WARNING_LIMIT and
    108         name not in self._dw_deprecated_printed):
```

**Comment by OverLordGoldDragon** [comment]
@impact27 Call a module method:

```python
# main.py
import dog
dog.woof()
```
```python
# dog.py
def woof():
    print("WOOF")
    1 / 0
```

<hr>

```python
# DEBUGGER
Traceback (most recent call last):
  File "C:\Desktop\main.py", line 4, in <module>
    dog.woof()
  File "C:\Desktop\dog.py", line 3, in woof
    1 / 0
ZeroDivisionError: division by zero
```

```python
# POST-MORTEM
Traceback (most recent call last):
  File "C:\Desktop\dog.py", line 3, in woof
    1 / 0
ZeroDivisionError: division by zero

****************************************
Entering post mortem debugging...
****************************************
> c:\desktop\dog.py(3)woof()
      1 def woof():
      2     print("WOOF")
----> 3     1 / 0
```

<hr>

`from dog import woof; woof()` <-- this WILL show properly in post-mortem, so it's something about `module.method()`.

**Comment by impact27** [comment]
Fixed in https://github.com/spyder-ide/spyder-kernels/pull/225/files

**Comment by OverLordGoldDragon** [comment]
@impact27 Great, another one-liner resolve. (this one's more like a quarter-liner)
