### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by imjunaida** [spyder-ide/spyder#12858]
### What steps will reproduce the problem?

I was using open cv for displaying some images concatenated using cv2.hconcat() function and spyder crashes while doing so. When run the same program using the terminal it works but it doesnt work on the IDE

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.4.0

### Dependencies

```
applaunchservices >=0.1.7    :  0.2.1 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by goanpeca** [comment]
Hi @imjunaida, thanks for the report.

Could you update to the latest Spyder (4.1.3?) and check again?

**Comment by imjunaida** [comment]
Here is the piece of code
img = cv.cvtColor(img, cv.COLOR_GRAY2RGB)

    for point in points_1:
        cv.circle(img, (int(point[0]), int(point[1])), 5, (0, 0, 255), -1)
        cv.circle(img2, (int(point[0]), int(point[1])), 5, (0, 0, 255), -1)

    if both:
        for point in points_2:
            cv.circle(img, (int(point[0]), int(point[1])), 5, (255, 0, 0), -1)
            cv.circle(img2, (int(point[0]), int(point[1])), 5, (255, 0, 0), -1)


    dashboard_img = cv.hconcat([img, img2])
    scale_percent = 60  # percent of original size
    width = int(dashboard_img.shape[1] * scale_percent / 100)
    height = int(dashboard_img.shape[0] * scale_percent / 100)
    dim = (width, height)
    resized = cv.resize(dashboard_img, dim, interpolation=cv.INTER_AREA)

    cv.imshow('Object Projection', resized)
    cv.waitKey(0)

**Comment by imjunaida** [comment]
> Hi @imjunaida, thanks for the report.
> 
> Could you update to the latest Spyder (4.1.3?) and check again?

Hey @goanpeca  the problem persists even after updating it to 4.1.3.

**Comment by goanpeca** [comment]
We will take a look! Thanks for the code snippet

**Comment by ccordoba12** [comment]
> and spyder crashes while doing so

Could you be more specific and describe exactly how Spyder crashes?

**Comment by imjunaida** [comment]
<img width="691" alt="Screen Shot 2020-05-26 at 12 18 29 PM" src="https://user-images.githubusercontent.com/30365313/82935967-190f0600-9f4b-11ea-841f-efefe8dde561.png">
This is how the error looks like when I try to run the piece of code

**Comment by ccordoba12** [comment]
Please post an animated gif using the Licecap program since the moment you run your code to see how the error above appears.

**Comment by qyyparadox** [comment]
Dear,I am a novice, I have a similar problem, and I don't konw how to solve it
The error is:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda2\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1562, in create_kernel_manager_and_kernel_client
config=None, autorestart=True)
File "C:\ProgramData\Anaconda2\lib\site‑packages\traitlets\config\configurable.py", line 73, in __init__
super(Configurable, self).__init__(**kwargs)
File "C:\ProgramData\Anaconda2\lib\site‑packages\traitlets\traitlets.py", line 997, in __init__
setattr(self, key, value)
File "C:\ProgramData\Anaconda2\lib\site‑packages\traitlets\traitlets.py", line 585, in __set__
self.set(obj, value)
File "C:\ProgramData\Anaconda2\lib\site‑packages\traitlets\traitlets.py", line 559, in set
new_value = self._validate(obj, value)
File "C:\ProgramData\Anaconda2\lib\site‑packages\traitlets\traitlets.py", line 591, in _validate
value = self.validate(obj, value)
File "C:\ProgramData\Anaconda2\lib\site‑packages\traitlets\traitlets.py", line 2053, in validate
raise TraitError(msg.format(value, self.name, class_of(obj)))
TraitError: Could not decode 'C:\\Users\\\xd2\xfc\xc5\xf4\\AppData\\Roaming\\jupyter\\runtime\\kernel𔂲daca57dab09.json' for unicode trait 'connection_file' of a QtKernelManager instance.

**Comment by ccordoba12** [comment]
@qyyparadox, your Windows user name has non-asciii characters (e.g. ñ or á or something similar) and those can't be handled correctly when creating a kernel for one of our consoles. To solve that problem, please remove your Anaconda installation and install Anaconda for Python 3 instead.

And for next time, please open a new issue instead of posting a comment in an unrelated issue because it's distracting for all people involved here.

**Comment by ccordoba12** [comment]
@imjunaida, your code is incomplete so we can't reproduce it, In particular, `img` and `img2` are not declared in your code.

**Comment by imjunaida** [comment]
> @imjunaida, your code is incomplete so we can't reproduce it. In particular, `img` and `img2` are not declared in your code.

I know it is incomplete. I cannot provide you the complete code as it is an ongoing project. If you want to reproduce the error try any two images and use the cv.hconcat() function as I have used.

**Comment by ccordoba12** [comment]
What kind of images? Png, Jpeg, Svg? Please be more specific.

**Comment by imjunaida** [comment]
it is png format

**Comment by ccordoba12** [comment]
@imjunaida, thanks!

@impact27, could you take a look at this one, given that it appears on macOS and involves comms?

**Comment by impact27** [comment]
The error message is likely unrelated to the problem. The console crashes and therefore the comm doesn't exist anymore.

**Comment by ccordoba12** [comment]
@imjunaida, does your crash outside Spyder too?

**Comment by imjunaida** [comment]
Spyder crashes even while using cv2.imshow . My code runs well outside Spyder.
