### ISSUE TITLE
Spyder didnt work after upgrade

### ISSUE THREAD

**Issue by enAnne** [spyder-ide/spyder#12855]
### What steps will reproduce the problem?

I tried "pip install upgrade spyder" and also "conda upgrade spyder", and many other things in between. 
It looks like the different environments confuses the Anaconda

### Traceback
```python-traceback
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\qtconsole\comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\qtconsole\comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 327, in _comm_message
    msg_dict, buffer, load_exception)
TypeError: _handle_remote_call_reply() takes 3 positional arguments but 4 were given
ERROR:traitlets:Exception in comm_msg for 2d3e52469eea11eaa508c8f7504c3705
Traceback (most recent call last):
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\qtconsole\comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\qtconsole\comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 327, in _comm_message
    msg_dict, buffer, load_exception)
TypeError: _handle_remote_call_reply() takes 3 positional arguments but 4 were given
ERROR:traitlets:Exception in comm_msg for 2d3e52469eea11eaa508c8f7504c3705
Traceback (most recent call last):
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\qtconsole\comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\qtconsole\comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 327, in _comm_message
    msg_dict, buffer, load_exception)
TypeError: _handle_remote_call_reply() takes 3 positional arguments but 4 were given
ERROR:traitlets:Exception in comm_msg for 2d3e52469eea11eaa508c8f7504c3705
Traceback (most recent call last):
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\qtconsole\comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\qtconsole\comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 327, in _comm_message
    msg_dict, buffer, load_exception)
TypeError: _handle_remote_call_reply() takes 3 positional arguments but 4 were given
ERROR:traitlets:Exception in comm_msg for 2d3e52469eea11eaa508c8f7504c3705
Traceback (most recent call last):
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\qtconsole\comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\qtconsole\comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 327, in _comm_message
    msg_dict, buffer, load_exception)
TypeError: _handle_remote_call_reply() takes 3 positional arguments but 4 were given
ERROR:traitlets:Exception in comm_msg for 2d3e52469eea11eaa508c8f7504c3705
Traceback (most recent call last):
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\qtconsole\comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\qtconsole\comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 327, in _comm_message
    msg_dict, buffer, load_exception)
TypeError: _handle_remote_call_reply() takes 3 positional arguments but 4 were given
ERROR:traitlets:Exception in comm_msg for 2d3e52469eea11eaa508c8f7504c3705
Traceback (most recent call last):
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\qtconsole\comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\qtconsole\comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 327, in _comm_message
    msg_dict, buffer, load_exception)
TypeError: _handle_remote_call_reply() takes 3 positional arguments but 4 were given
ERROR:traitlets:Exception in comm_msg for 2d3e52469eea11eaa508c8f7504c3705
Traceback (most recent call last):
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\qtconsole\comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\qtconsole\comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\EEANNNG\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 327, in _comm_message
    msg_dict, buffer, load_exception)
TypeError: _handle_remote_call_reply() takes 3 positional arguments but 4 were given
```

## Versions

* Spyder version: 4.1.3 
* Python version: 3.7.6
* Qt version: 5.12.8
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.12.0 (OK)
jedi =0.15.2                   :  0.14.1 (NOK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.2 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.3 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.8.1 (NOK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.17 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by goanpeca** [comment]
Hi @enAnne, thanks for the report.
your spyder kernels dependency is not correct (from the dependencies listing)

```
spyder_kernels >=1.9.1;<1.10.0 :  1.8.1 (NOK)
```

Please fix this dependency. Open the Anaconda Prompt and type:
```
conda install spyder-kernels>=1.9.1
```

**Comment by ccordoba12** [comment]
> I tried "pip install upgrade spyder" and also "conda upgrade spyder", and many other things in between.

Sorry to say it but by running `pip install upgrade spyder` you basically broke your Anaconda installation and now you have to uninstall it, remove the directory where it was installed and reinstall it again.
