### ISSUE TITLE
Errno 32

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1289]
_From [Tott3...@gmail.com](https://code.google.com/u/103885714928754756449/) on 2013-02-28T01:06:51Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. Running the program for more than 2 minutes, no matter what I'm doing in the program What is the expected output? What do you see instead? Here's the script I'm running.

while True:
 
    print ("What would you like to calculate?")
    print ("1. Reaction Distance")
    print ("2. Breaking Distance")
    print ("3. Stop Distance")
 
    A = raw_input('Chose your answer by typing "Reaction", "Break", "Stop" or "Quit" to exit: ')
 
    if A == "Reaction" or A == "reaction":
        Speed = raw_input("Enter speed: ")
        reactionS = raw_input("Enter the reacion time in seconds: ")
        svar = (int(Speed) * int(reactionS)) / 3.6
        print ("The breaking distance is: " + str(svar))
    elif A == "Break" or A == "break":
        print("Breaking Distance")
    elif A == "Stop" or A == "stop":
        print("Stop")
    else:
        quit()

Here's the error I'm getting

n thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/monitor.py", line 575, in run
    already_pickled=True)
  File "/usr/lib/python2.7/dist-packages/spyderlib/utils/bsdsocket.py", line 24, in write_packet
    sock.send(struct.pack("l", len(sent_data)) + sent_data)
error: [Errno 32] Broken pipe What version of the product are you using? On what operating system? Running Spyder 2.1.9 on Ubuntu 12.04 LTS 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1289_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-03-05T10:07:55Z_

This is not happening for me on 2.2beta3. We added several measures to avoid this problem and they're not going to be backported to 2.1 because of lack of time.

Thanks for reporting and I hope you continue to use Spyder in the future.

**Status:** WontFix
