### ISSUE TITLE
Can't debug in macOS 

### ISSUE THREAD

**Issue by luismiguells** [spyder-ide/spyder#12891]
## Problem Description
I've tried to use the debugger in Spyder but always give the next error:

```python-traceback

Traceback (most recent call last):

  File "/Users/luismiguells/Documents/IE/source/single_linkage_clustering.py", line 7, in <module>
    """

  File "/Users/luismiguells/Documents/IE/source/single_linkage_clustering.py", line 7, in <module>
    """

  File "/Users/luismiguells/opt/anaconda3/lib/python3.7/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)

  File "/Users/luismiguells/opt/anaconda3/lib/python3.7/bdb.py", line 112, in dispatch_line
    self.user_line(frame)

  File "/Users/luismiguells/opt/anaconda3/lib/python3.7/pdb.py", line 259, in user_line
    self.interaction(frame, None)

  File "/Users/luismiguells/opt/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spyderpdb.py", line 146, in interaction
    self._cmdloop()

  File "/Users/luismiguells/opt/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spyderpdb.py", line 311, in _cmdloop
    self.cmdloop()

  File "/Users/luismiguells/opt/anaconda3/lib/python3.7/cmd.py", line 105, in cmdloop
    self.preloop()

  File "/Users/luismiguells/opt/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spyderpdb.py", line 258, in preloop
    frontend_request(blocking=True).set_debug_state(True)

  File "/Users/luismiguells/opt/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 538, in __call__
    call_dict, call_data, self._comm_id)

  File "/Users/luismiguells/opt/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 420, in _get_call_return_value
    return self._sync_error(reply['value'])

  File "/Users/luismiguells/opt/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 476, in _sync_error
    error_wrapper.raise_error()

  File "/Users/luismiguells/opt/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 90, in raise_error
    raise self.etype(self)

OperationalError: attempt to write a readonly database

```

I read that this problem may be cause with conflict with databases but I don't use in my code anything related to databases. I tried to restart Spyder and Anaconda Navigator but didn't work. I attached a photo of the error:

<img width="1680" alt="Captura de Pantalla 2020-05-28 a la(s) 13 04 21" src="https://user-images.githubusercontent.com/25065697/83178039-9a9a9b80-a0e5-11ea-8d45-2e9a348b86c0.png">

## Versions

* Spyder version: 4.1.3
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: macOS 10.15.5

**Comment by andfoy** [comment]
Hi @luismiguells, thanks for reporting this issue. We will take a look at it and fix it for the next release of Spyder. @impact27, could you please take a look at this one?

**Comment by impact27** [comment]
Looks like the pdb history file is in read-only for some reason. Can you try deleting it?
it is found at ~/.spyder*/pdb_history.sqlite

**Comment by ccordoba12** [comment]
@impact27, I think we should catch that error and pass on it, perhaps also printing a message to the console saying that the history of commands won't be saved because `~/.spyder*/pdb_history.sqlite` doesn't have write permissions.

What do you think?

**Comment by ccordoba12** [comment]
@JavierMora-ux, gracias por la información! Vamos a ver si podemos evitar este error en algunas de nuestras futuras versiones.
