### ISSUE TITLE
Spyder Crashed during last session.

### ISSUE THREAD

**Issue by Hilaren** [spyder-ide/spyder#12974]
## Problem Description
I am trying to use Spyder for Machine Learning studying, I downloaded Anaconda and tried to launched Spyder while got the 'Spyder crashed during last session' reminder again and again. I've tried everything I could : 
1. uninstall and then reinstall Anaconda for 3 times;
2. Reset Spyder in terminal with command spyder --reset;
3. Uninstall and then re-install Spyder again and again;
4. Launch Spyder from terminal using command spyder --show-console;
All methods mentioned in the help documentation have been tried while still got the crashing information again and again.

### What is the expected output? What do you see instead?

Expected output: Spyder can be launched successfully.
What do you see instead: Spyder crashed during last session.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "/Users/renna/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "/Users/renna/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3559, in run_spyder
    main.setup()
  File "/Users/renna/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 960, in setup
    self.completions.start()
  File "/Users/renna/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 292, in start
    client_info['plugin'].start()
  File "/Users/renna/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/kite/plugin.py", line 144, in start
    self.client.start()
  File "/Users/renna/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/kite/client.py", line 62, in start
    self.sig_client_started.emit(self.languages)
TypeError: KiteClient.sig_client_started[list].emit(): argument 1 has unexpected type 'str'


```

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.6
* Qt version: 
* PyQt version: 5.12.0
* Operating System name/version: macOS Catalina

### Dependencies

```
Sorry the dependencies couldn't be pasted here. 
```
Thank you so much!

**Comment by goanpeca** [comment]
Hi @Hilaren, thanks for the report.

Could you please update to the latest version of Spyder?

To do this, you can open the terminal and type:

```
conda update anaconda
conda install spyder=4.1.3
```

**Comment by Hilaren** [comment]
@goanpeca Thank you so much!! It works for me, I can finally launch Spyder. I've been working on this issue for a few days. Thanks again for your support!
