### ISSUE TITLE
IPython console hangs after changing warning to errors

### ISSUE THREAD

**Issue by smetterspa** [spyder-ide/spyder#12999]
### What steps will reproduce the problem?

Run <F9> the following code:

    import warnings
    warnings.filterwarnings("error")

Ipython then seems to break.

## Versions

* Spyder version: 4.1.3 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.2 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.4 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.3 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.17 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by andfoy** [comment]
Hi @smetterspa, thanks for reporting this issue, I was able to reproduce it. @impact27 @dalthviz, do you know what could be the cause of the console freeze?

**Comment by dalthviz** [comment]
I'm unsure why this is happening but when you use the `Clear console` option  you can see this:

![image](https://user-images.githubusercontent.com/16781833/84447182-f9dfcc00-ac0c-11ea-9f4d-51994da275f5.png)

**Comment by impact27** [comment]
Can't reproduce on macOS:
``` python
Python 3.7.7 (default, Mar 10 2020, 15:43:33) 
Type "copyright", "credits" or "license" for more information.

IPython 7.10.2 -- An enhanced Interactive Python.

In [1]: import warnings
   ...: warnings.filterwarnings("error")

In [2]: 1+1
Out[2]: 2

In [3]: 
```

**Comment by impact27** [comment]
It is not terribly surprising, if you transform warnings into errors, any warning that would be generated by the kernel gets upgraded to an error which means the kernel can crash really easily.

**Comment by impact27** [comment]
On windows using `jupyuter console`:
```
In [4]: 1+1[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Users\Quentin.Peter\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\Quentin.Peter\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Quentin.Peter\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\Quentin.Peter\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 702, in is_complete_request
    reply_content = yield gen.maybe_future(self.do_is_complete(code))
  File "C:\Users\Quentin.Peter\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 454, in do_is_complete
    status, indent_spaces = self.shell.input_splitter.check_complete(code)
  File "C:\Users\Quentin.Peter\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 503, in input_splitter
    DeprecationWarning, stacklevel=2
DeprecationWarning: `input_splitter` is deprecated since IPython 7.0, prefer `input_transformer_manager`.
```
I would say we can close because this is not a spyder issue and there is realistically not much we can do about that. There will always be some code that might break the kernel.

**Comment by impact27** [comment]
We could print the content of stderr. From the internal console:
```python
>>> client = spy.window.ipyconsole.get_current_client()
>>> client.stderr_file
'C:\\Users\\QUENTI~1.PET\\AppData\\Local\\Temp\\spyder\\kernel-a2eddad5daa9.stderr'

>>> with open(client.stderr_file, 'r') as f: print(f.read())
... 
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Users\Quentin.Peter\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\Quentin.Peter\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Quentin.Peter\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\Quentin.Peter\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 702, in is_complete_request
    reply_content = yield gen.maybe_future(self.do_is_complete(code))
  File "C:\Users\Quentin.Peter\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 454, in do_is_complete
    status, indent_spaces = self.shell.input_splitter.check_complete(code)
  File "C:\Users\Quentin.Peter\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 503, in input_splitter
    DeprecationWarning, stacklevel=2
DeprecationWarning: `input_splitter` is deprecated since IPython 7.0, prefer `input_transformer_manager`.

>>> 
```

**Comment by impact27** [comment]
I opened a PR (#13007 ) so the console would look like:
```python
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.13.0 -- An enhanced Interactive Python.

In [1]: import warnings

In [2]: warnings.filterwarnings("error")

In [3]: 1[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Users\Quentin.Peter\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\Quentin.Peter\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Quentin.Peter\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\Quentin.Peter\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 702, in is_complete_request
    reply_content = yield gen.maybe_future(self.do_is_complete(code))
  File "C:\Users\Quentin.Peter\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 454, in do_is_complete
    status, indent_spaces = self.shell.input_splitter.check_complete(code)
  File "C:\Users\Quentin.Peter\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 503, in input_splitter
    DeprecationWarning, stacklevel=2
DeprecationWarning: `input_splitter` is deprecated since IPython 7.0, prefer `input_transformer_manager`.
```

**Comment by ccordoba12** [comment]
Thanks a lot @impact27 for your help with this one!
