### ISSUE TITLE
trying to change column names in dataframe using lambda function

### ISSUE THREAD

**Issue by fandemisterling100** [spyder-ide/spyder#12994]
### What steps will reproduce the problem?

import pandas as pd

file = "BD_EJEMPLO.xlsx"
# Import the data
df = pd.read_excel(file, na_values = "n/a")

a = df.columns[1::6]

Columnas_Datos = []

for i in a:
    
    Columnas_Datos =Columnas_Datos +[i+"ZSPREADMID"]+[i+"PX_BID"]+[i+"PX_ASK"]+[i+"YTM_BID"]+[i+"YTM_ASK"]+[i+"BB_DEFAULT_5Y"]

df3 = pd.DataFrame(df.iloc[1:,1:]).rename(index = df.iloc[1:,0], columns = lambda x: Columnas_Datos)

# I am trying to change every column name in the original df for every element in list 'Columnas_Datos'

### Traceback
```python-traceback
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'
Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'
Traceback (most recent call last):
  File "C:\Users\maria isabel\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionsdelegate.py", line 162, in createEditor
    if not editor.setup_and_check(value, title=key):
  File "C:\Users\maria isabel\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 926, in setup_and_check
    self.dataModel = DataFrameModel(data, parent=self)
  File "C:\Users\maria isabel\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 137, in __init__
    self.max_min_col_update()
  File "C:\Users\maria isabel\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 228, in max_min_col_update
    for dummy, col in self.df.iteritems():
  File "C:\Users\maria isabel\Anaconda3\lib\site-packages\pandas\core\frame.py", line 901, in iteritems
    yield from self.items()
  File "C:\Users\maria isabel\Anaconda3\lib\site-packages\pandas\core\frame.py", line 897, in items
    yield k, self._ixs(i, axis=1)
  File "C:\Users\maria isabel\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2760, in _ixs
    result = self._box_col_values(values, label)
  File "C:\Users\maria isabel\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3078, in _box_col_values
    return klass(values, index=self.index, name=items, fastpath=True)
  File "C:\Users\maria isabel\Anaconda3\lib\site-packages\pandas\core\series.py", line 310, in __init__
    self.name = name
  File "C:\Users\maria isabel\Anaconda3\lib\site-packages\pandas\core\generic.py", line 5296, in __setattr__
    object.__setattr__(self, name, value)
  File "C:\Users\maria isabel\Anaconda3\lib\site-packages\pandas\core\series.py", line 435, in name
    raise TypeError("Series.name must be a hashable type")
TypeError: Series.name must be a hashable type
```

## Versions

* Spyder version: 4.1.3 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by dalthviz** [comment]
Closing as no more info was provided
