### ISSUE TITLE
Can't start spyder.exe on Windows 7 64bit edition

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1304]
_From [BoskoVuk...@gmail.com](https://code.google.com/u/116734844623840905127/) on 2013-03-09T13:03:28Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. I downloaded windows binary distribution and unpacked it to my desktop (spyder-win32-pyqt-sa-2.2.0dev.zip).
2. I renamed folder to spyder.
3. I started spyder.exe and it crashed saving spyder_crash.log with the content:

Traceback (most recent call last):
  File "spyderlib/spyder.py", line 1912, in main
    mainwindow = run_spyder(app, options)
  File "spyderlib/spyder.py", line 1824, in run_spyder
    main.setup()
  File "spyderlib/spyder.py", line 637, in setup
    self.editor = Editor(self)
  File "C:\Users\Bosko\Desktop\spyder\spyderlib\plugins\editor.py", line 428, in __init__
    self.__load_temp_file()
  File "C:\Users\Bosko\Desktop\spyder\spyderlib\plugins\editor.py", line 1311, in __load_temp_file
    self.load(self.TEMPFILE_PATH)
  File "C:\Users\Bosko\Desktop\spyder\spyderlib\plugins\editor.py", line 1513, in load
    finfo = self.editorstacks[0].load(filename, set_current=False)
  File "C:\Users\Bosko\Desktop\spyder\spyderlib\widgets\editor.py", line 1777, in load
    finfo = self.create_new_editor(filename, enc, text, set_current)
  File "C:\Users\Bosko\Desktop\spyder\spyderlib\widgets\editor.py", line 1663, in create_new_editor
    finfo = FileInfo(fname, enc, editor, new, self.threadmanager)
  File "C:\Users\Bosko\Desktop\spyder\spyderlib\widgets\editor.py", line 263, in __init__
    self.rope_project = codeeditor.get_rope_project()
  File "C:\Users\Bosko\Desktop\spyder\spyderlib\widgets\sourcecode\codeeditor.py", line 211, in get_rope_project
    ROPE_PROJECT = RopeProject()
  File "C:\Users\Bosko\Desktop\spyder\spyderlib\widgets\sourcecode\codeeditor.py", line 89, in __init__
    self.create_rope_project(root_path=get_conf_path())
  File "C:\Users\Bosko\Desktop\spyder\spyderlib\widgets\sourcecode\codeeditor.py", line 96, in create_rope_project
    **ROPE_PREFS)
  File "D:\Python\spyder\rope\base\project.py", line 146, in __init__
  File "D:\Python\spyder\rope\base\project.py", line 178, in _init_prefs
  File "D:\Python\spyder\rope\base\project.py", line 191, in _default_config
  File "C:\Python27\lib\inspect.py", line 699, in getsource
  File "C:\Python27\lib\inspect.py", line 688, in getsourcelines
  File "D:\Python\ipython\IPython\core\ultratb.py", line 153, in findsource
IOError: could not get source code

My default Python is ActiveState 2.5 with path on C:\Python25\
I have all other python versions both 32bit and 64bit from 2.5 till 3.2 and they are all ActiveState and in folders C:\Python25\, C:\Python25x64\, C:\Python26\, C:\Python26x64\ .... C:\Python32\ and C:\Python32x64\

I renamed my python27 folder to Python27xxx so it would become invisible on the path. It didn't help. I installed PyQt4 binary distribution for 2.7 and it's in Python27 folder on C:

My path variable is:
Path=C:\Python27\Lib\site-packages\PyQt4;
C:\Users\Bosko\Documents\AMD APP\bin\x86_64;
C:\Users\Bosko\Documents\AMD APP\bin\x86;
C:\Program Files (x86)\AMD APP\bin\x86_64;
C:\Program Files (x86)\AMD APP\bin\x86;
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;
C:\Program Files\Common Files\Microsoft Shared\Windows Live;
C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;
C:\Sybase\ASE-15_0\jobscheduler\bin;
C:\Sybase\ASE-15_0\dll;
C:\Sybase\ASE-15_0\bin;
C:\Sybase\DBISQL\bin;
C:\Sybase\DataAccess\ADONET\dll;
C:\Sybase\DataAccess\ODBC\dll;
C:\Sybase\DataAccess\OLEDB\dll;
C:\Sybase\UAF-2_5\bin;
C:\Sybase\OCS-15_0\lib3p;
C:\Sybase\OCS-15_0\dll;
C:\Sybase\OCS-15_0\bin;
C:\Sybase\ASE-15_0\jobscheduler\bin;
C:\Sybase\ASE-15_0\dll;
C:\Sybase\ASE-15_0\bin;
C:\Sybase\DBISQL\bin;
C:\Sybase\DataAccess\ADONET\dll;
C:\Sybase\DataAccess\ODBC\dll;
C:\Sybase\DataAccess\OLEDB\dll;
C:\Sybase\UAF-2_5\bin;
C:\Sybase\OCS-15_0\lib3p;
C:\Sybase\OCS-15_0\dll;
C:\Sybase\OCS-15_0\bin;
C:\Python25\;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;
C:\Program Files (x86)\Microsoft SQL Server\80\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\90\DTS\Binn\;
C:\Program Files\Microsoft SQL Server\90\Tools\binn\;
C:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;
C:\Program Files (x86)\Microsoft SQL Server\90\DTS\Binn\;
C:\Program Files (x86)\Microsoft SQL Server\90\Tools\Binn\VSShell\Common7\IDE\;
C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE\PrivateAssemblies\;
C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;
C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;
C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;
C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\PrivateAssemblies\;
C:\Program Files\Microsoft Network Monitor 3\;
C:\Python25\DLLs;
C:\Program Files (x86)\Windows Live\Shared;
C:\Program Files (x86)\Calibre2\;
C:\Program Files (x86)\QuickTime\QTSystem\;
C:\Program Files (x86)\TeleTrader\Professional\;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Program Files (x86)\GnuTLS-2.10.1\bin;
C:\Program Files (x86)\IDM Computer Solutions\UltraEdit\;
C:\Program Files (x86)\IDM Computer Solutions\UltraCompare\

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1304_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-03-11T14:30:26Z_

**Status:** Duplicate  
  **Mergedinto:** 891
