### ISSUE TITLE
Kernel Error

### ISSUE THREAD

**Issue by chloemoeck** [spyder-ide/spyder#13053]
# Problem Description
There is an error while starting the kernel, both in spyder and in jypter. 

### What steps reproduce the problem?
1.  restarting spyder or the laptop
2. updating spyder

### What is the expected output? What do you see instead?
It happens before I can even run a code. My code was working perfectly the last time I used it before the error started. Will not run any code(even as simple as 2+2)

I know it is not a code error because it worked perfectly when I first coded it and no other code, no matter how simple, works either.

```python-traceback

PASTE TRACEBACK HERE

Traceback (most recent call last):
File "C:\Users\chloe\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\chloe\anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\chloe\anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\chloe\anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 289, in main
import_spydercustomize()
File "C:\Users\chloe\anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 39, in import_spydercustomize
import spydercustomize
File "C:\Users\chloe\anaconda3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 24, in 
from IPython.core.getipython import get_ipython
File "C:\Users\chloe\anaconda3\lib\site‑packages\IPython\__init__.py", line 55, in 
from .core.application import Application
File "C:\Users\chloe\anaconda3\lib\site‑packages\IPython\core\application.py", line 23, in 
from traitlets.config.application import Application, catch_config_error
File "C:\Users\chloe\anaconda3\lib\site‑packages\traitlets\config\__init__.py", line 6, in 
from .application import *
File "C:\Users\chloe\anaconda3\lib\site‑packages\traitlets\config\application.py", line 10, in 
import json
File "C:\Users\chloe\json.py", line 20, in 
r = requests.post(end_pt_url, headers=HEADERS,json=query)
File "C:\Users\chloe\anaconda3\lib\site‑packages\requests\api.py", line 119, in post
return request('post', url, data=data, json=json, **kwargs)
File "C:\Users\chloe\anaconda3\lib\site‑packages\requests\api.py", line 61, in request
return session.request(method=method, url=url, **kwargs)
File "C:\Users\chloe\anaconda3\lib\site‑packages\requests\sessions.py", line 516, in request
prep = self.prepare_request(req)
File "C:\Users\chloe\anaconda3\lib\site‑packages\requests\sessions.py", line 459, in prepare_request
hooks=merge_hooks(request.hooks, self.hooks),
File "C:\Users\chloe\anaconda3\lib\site‑packages\requests\models.py", line 317, in prepare
self.prepare_body(data, files, json)
File "C:\Users\chloe\anaconda3\lib\site‑packages\requests\models.py", line 467, in prepare_body
body = complexjson.dumps(json)
AttributeError: module 'json' has no attribute 'dumps'
```

## Versions

* Spyder version: 4.1.3 py37_0
* Python version:  3.7.7 h81c818b_4
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: anaconda3?

**Comment by oscargus** [comment]
The problem is that the Spyder/IPython/traitlets code is loading the Python standard library json, https://docs.python.org/3/library/json.html
```
File "C:\Users\chloe\anaconda3\lib\site‑packages\traitlets\config\application.py", line 10, in 
import json
```

However, as you have a file named `json.py` which is found before the Python library file that one is loaded instead.
```
File "C:\Users\chloe\json.py", line 20, in 
r = requests.post(end_pt_url, headers=HEADERS,json=query)
```

Easy fix: rename your file json.py to something else.

Better fix would be to change the `PYTHONPATH` environment variable order, but not sure how to do that nor if it might have any other side effects.

**Comment by chloemoeck** [comment]
This worked, thank you so much!!

**Comment by ccordoba12** [comment]
Thanks a lot for your help @oscargus!
