### ISSUE TITLE
An error occured while starting the kernel

### ISSUE THREAD

**Issue by sowmyahj** [spyder-ide/spyder#13115]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Unable to use Spyder, getting the following error on IPython Console "An error occured while starting the kernel"

### What steps reproduce the problem?
I was trying to understand the significance of __init__.py file in the context of packages.  

1. create a folder by name datetime
2. Inside the datetime folder create a file named datetime.py
3. create another file say test.py at the same level as that of datetime folder. Inside test.py write import datetime.datetime
datetime.now()
4. Also, in between I  changed sys.path variable to include the path to the folder datetime

it was workig fine by throwing the error no module found which was expected.

I think the moment I created __init__.py file inside the datetime directory and run the test.py again, i got the kernel error

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site‑packages/spyder_kernels/console/start.py", line 289, in main
import_spydercustomize()
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site‑packages/spyder_kernels/console/start.py", line 39, in import_spydercustomize
import spydercustomize
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site‑packages/spyder_kernels/customize/spydercustomize.py", line 24, in 
from IPython.core.getipython import get_ipython
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site‑packages/IPython/__init__.py", line 56, in 
from .terminal.embed import embed
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site‑packages/IPython/terminal/embed.py", line 14, in 
from IPython.core.magic import Magics, magics_class, line_magic
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site‑packages/IPython/core/magic.py", line 20, in 
from . import oinspect
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site‑packages/IPython/core/oinspect.py", line 30, in 
from IPython.lib.pretty import pretty
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site‑packages/IPython/lib/pretty.py", line 761, in 
datetime.datetime: _repr_pprint,
AttributeError: module 'datetime' has no attribute 'datetime'
```

## Versions

* Spyder version: 4.1.3
* Python version: 3.7.6 (But I have set the interpreter to Python 3.8.3 )
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: macOS High Sierra Version 10.13.6 / Darwin 17.7.0 

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.15.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.0.0 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.1 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by sowmyahj** [comment]
Restarting Spyder with defaults solved the issue
