### ISSUE TITLE
spyder is crashed during last session

### ISSUE THREAD

**Issue by Div123chauhan** [spyder-ide/spyder#13139]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by goanpeca** [comment]
Hi @Div123chauhan.

To be able to debug the issue you will need to explain what the problems were and attach the requested information.

Cheers.

**Comment by nethra123-hub** [comment]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3559, in run_spyder
    main.setup()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 960, in setup
    self.completions.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 292, in start
    client_info['plugin'].start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\plugin.py", line 141, in start
    self.kite_process = run_program(path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\programs.py", line 214, in run_program
    return subprocess.Popen(fullcmd, **subprocess_kwargs)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by nethra123-hub** [comment]
what should i do?

**Comment by ccordoba12** [comment]
@nethra123-hub, I think this is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda update anaconda
    conda install spyder=4.1.3

**Comment by Div123chauhan** [comment]
I also solved it by these between thanks😇😇
