### ISSUE TITLE
123456778945454

### ISSUE THREAD

**Issue by JabinHao** [spyder-ide/spyder#13147]
### What steps will reproduce the problem?

# q
I dont know what happened, there are two spyder on my pc,spyder3 and spyder4

### Traceback
```python-traceback
  File "/home/hjp/miniconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/home/hjp/miniconda3/lib/python3.7/site-packages/jupyter_client/threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/home/hjp/miniconda3/lib/python3.7/site-packages/jupyter_client/session.py", line 927, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'1a27059e29ad682134de3e4cb8b6c244977a048938e571a02d8c0e73f73f2380'
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/home/hjp/miniconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/home/hjp/miniconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/hjp/miniconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/home/hjp/miniconda3/lib/python3.7/site-packages/jupyter_client/threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/home/hjp/miniconda3/lib/python3.7/site-packages/jupyter_client/session.py", line 927, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'1a27059e29ad682134de3e4cb8b6c244977a048938e571a02d8c0e73f73f2380'
ERROR:tornado.application:Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x7f8bfd731560>)
Traceback (most recent call last):
  File "/home/hjp/miniconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/hjp/miniconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 542, in <lambda>
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "/home/hjp/miniconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/home/hjp/miniconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/hjp/miniconda3/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/home/hjp/miniconda3/lib/python3.7/site-packages/jupyter_client/threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/home/hjp/miniconda3/lib/python3.7/site-packages/jupyter_client/session.py", line 927, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'1a27059e29ad682134de3e4cb8b6c244977a048938e571a02d8c0e73f73f2380'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.7
* Qt version: 5.14.1
* PyQt5 version: 5.14.1
* Operating System: Linux 4.15.0-30deepin-generic

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.13.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
keyring                      :  None (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.7.0 (OK)
pygments >=2.0               :  2.6.1 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.9 (OK)
xdg >=0.26                   :  0.26 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.7.0 (OK)
qtconsole >=4.6.0            :  4.7.2 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.4 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.3 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by steff456** [comment]
Hi @JabinHao,

Can you please update spyder to the latest version, 4.1.3 to see if that fixes this error?

**Comment by steff456** [comment]
I'm closing this issue because there was no follow-up response after a week.
