### ISSUE TITLE
NotImplementedError: Cannot convert a symbolic Tensor  to a numpy array.

### ISSUE THREAD

**Issue by itsiospaschalis** [spyder-ide/spyder#13157]
### What steps will reproduce the problem?

Hello people I am facing an issue when it comes to converting a tensor (type: python.framework.ops.Tensor) to an array.
Do you know how can I convert it ? Thanks

### Traceback
```python-traceback
  File "C:\Users\itsios\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 1040, in copy
    obj = self.delegate.get_value(idx)
  File "C:\Users\itsios\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 1383, in get_value
    return self.parent().get_value(name)
  File "C:\Users\itsios\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 1438, in get_value
    value = self.shellwidget.get_value(name)
  File "C:\Users\itsios\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 99, in get_value
    timeout=CALL_KERNEL_TIMEOUT).get_value(name)
  File "C:\Users\itsios\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 538, in __call__
    call_dict, call_data, self._comm_id)
  File "C:\Users\itsios\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 132, in _get_call_return_value
    call_dict, call_data, comm_id)
  File "C:\Users\itsios\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 420, in _get_call_return_value
    return self._sync_error(reply['value'])
  File "C:\Users\itsios\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 476, in _sync_error
    error_wrapper.raise_error()
  File "C:\Users\itsios\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 90, in raise_error
    raise self.etype(self)
Exception in comms call get_value:

  File "C:\Users\itsios\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    self._set_call_return_value(msg_dict, return_value)

  File "C:\Users\itsios\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 376, in _set_call_return_value
    comm_id=self.calling_comm_id)

  File "C:\Users\itsios\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 245, in _send_message
    data, protocol=self._comms[comm_id]['pickle_protocol'])]

  File "C:\Users\itsios\anaconda3\lib\site-packages\cloudpickle\cloudpickle.py", line 1083, in dumps
    cp.dump(obj)

  File "C:\Users\itsios\anaconda3\lib\site-packages\cloudpickle\cloudpickle.py", line 477, in dump
    return Pickler.dump(self, obj)

  File "C:\Users\itsios\anaconda3\lib\pickle.py", line 437, in dump
    self.save(obj)

  File "C:\Users\itsios\anaconda3\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)

  File "C:\Users\itsios\anaconda3\lib\pickle.py", line 662, in save_reduce
    save(state)

  File "C:\Users\itsios\anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self

  File "C:\Users\itsios\anaconda3\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())

  File "C:\Users\itsios\anaconda3\lib\pickle.py", line 885, in _batch_setitems
    save(v)

  File "C:\Users\itsios\anaconda3\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)

  File "C:\Users\itsios\anaconda3\lib\pickle.py", line 662, in save_reduce
    save(state)

  File "C:\Users\itsios\anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self

  File "C:\Users\itsios\anaconda3\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())

  File "C:\Users\itsios\anaconda3\lib\pickle.py", line 885, in _batch_setitems
    save(v)

  File "C:\Users\itsios\anaconda3\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)

  File "C:\Users\itsios\anaconda3\lib\pickle.py", line 662, in save_reduce
    save(state)

  File "C:\Users\itsios\anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self

  File "C:\Users\itsios\anaconda3\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())

  File "C:\Users\itsios\anaconda3\lib\pickle.py", line 885, in _batch_setitems
    save(v)

  File "C:\Users\itsios\anaconda3\lib\pickle.py", line 524, in save
    rv = reduce(self.proto)

TypeError: can't pickle _thread.RLock objects

```

## Versions

* Spyder version: 4.1.3 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.15.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.0.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.1 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.20 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6 (OK)
```

**Comment by athompson6735** [comment]
You show the error, but not the code that generated it. Can you also confirm that this does or doesn't work in a system terminal without spyder?

**Comment by dalthviz** [comment]
Thanks for the feedback @itsiospaschalis , could you please give us an example to replicated the error (steps you made, code you used, etc). Any new info to understand the way the error appears is really appreciated, thanks :)

**Comment by itsiospaschalis** [comment]
Hello guys, 
thanks for the reply.

I want to extract a layer from a neural network(let's call it "a") in order to use it for different task and convert it to a numpy array(let's call it "b").
("a" is ta ensorflow.python.framework.ops.Tensor)

The code:
a=model.layers[21].output   (
b=a.eval()


The console output: 

b=a.eval()
Traceback (most recent call last):

  File "<ipython-input-206-4d2a2f0c917a>", line 1, in <module>
    b=a.eval()

  File "C:\Users\itsios\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 798, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)

  File "C:\Users\itsios\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 5396, in _eval_using_default_session
    raise ValueError("Cannot evaluate tensor using `eval()`: No default "

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`

**Comment by dalthviz** [comment]
@itsiospaschalis I think you need to create an `InteractiveSession` object to use `eval` without passing a session. For more info you can look [here](https://stackoverflow.com/a/48031624). I think the error isn't related to Spyder itself so I'm closing this one for now

**Comment by ccordoba12** [comment]
I think this was reopened automatically after changing the `Awaiting followup` label.
