### ISSUE TITLE
variable explorer only works for internal console

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1316]
_From [thijsvkr...@gmail.com](https://code.google.com/u/103996024948870397761/) on 2013-03-14T10:15:35Z_

Spyder Version:  2.1.11
Python Version:  2.7.3
Qt Version:      4.8.3, PyQt4 (API v2) 4.9.5 on Windows 

What steps will reproduce the problem?

 1. enter a=5 in the console interpreter What is the expected output? What do you see instead? expect to see the variable a in the variable explorer 

Please provide any additional information below

. not sure it is related but if i change the "exclude internal references" or any of these filters i get the following error in the internal console:
\>>> Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\namespacebrowser.py", line 249, in option_changed
    'set_remote_view_settings()', settings=[settings])
  File "C:\Python27\lib\site-packages\spyderlib\utils\bsdsocket.py", line 64, in communicate
    write_packet(sock, command)
  File "C:\Python27\lib\site-packages\spyderlib\utils\bsdsocket.py", line 24, in write_packet
    sock.send(struct.pack("l", len(sent_data)) + sent_data)
AttributeError: 'NoneType' object has no attribute 'send'

incidentally any variables added to the internal console DO show up

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1316_

**Comment by spyder-issues-migrator** [comment]
_From [thijsvkr...@gmail.com](https://code.google.com/u/103996024948870397761/) on 2013-03-14T09:33:06Z_

after a reinstall the issue disappeared... I have no idea why :S

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-03-14T09:33:35Z_

Please try to run Spyder in debug mode and take a look at the debug files in '.spyder2' directory (in your home directory).

This AttributeError only means that the interpreter has been shut down before. In other words, there should be another traceback somewhere.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-03-14T09:34:00Z_

Ok, I'm closing it.

**Status:** Invalid
