### ISSUE TITLE
No sobre-escribe el archivo CSV

### ISSUE THREAD

**Issue by JAESCOBARC** [spyder-ide/spyder#13211]
### What steps will reproduce the problem?

El código al parecer no sobre escribe el CSV generado.

### Traceback
```python-traceback
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\spyder_pylint\widgets\pylintgui.py", line 336, in read_output
    text = to_text_string(qba.data(), encoding='utf-8')
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\spyder\py3compat.py", line 148, in to_text_string
    return str(obj, encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 1534: invalid start byte
Traceback (most recent call last):
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\spyder_pylint\widgets\pylintgui.py", line 336, in read_output
    text = to_text_string(qba.data(), encoding='utf-8')
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\spyder\py3compat.py", line 148, in to_text_string
    return str(obj, encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 123: invalid continuation byte
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.1
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.2 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.12 (OK)
qtconsole >=4.2.0 :  4.7.5 (OK)
IPython >=4.0     :  7.6.1 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by steff456** [comment]
Hola @JAESCOBARC,

Este issue ya fue resuelto en Spyder 4, te recomendamos que actualices a la última versión de Spyder.

```
conda update anaconda
conda install spyder=4.1.3
```
