### ISSUE TITLE
Unable to restart spyder from bootstrap.py

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#13235]
Restarting Spyder (running it from the bootstrap script) is raising an error (this is also happening in master and 4.x):

```python
Traceback (most recent call last):
  File "C:\Users\Daniel\Documents\Spyder\Spyder otros\gonzalo\spyder\spyder\app\restart.py", line 32, in <module>
    from spyder.utils.qthelpers import qapplication
  File "C:\Users\Daniel\Documents\Spyder\Spyder otros\gonzalo\spyder\spyder\utils\qthelpers.py", line 28, in <module>
    from spyder.config.manager import CONF
  File "C:\Users\Daniel\Documents\Spyder\Spyder otros\gonzalo\spyder\spyder\config\manager.py", line 17, in <module>
    from spyder.config.main import CONF_VERSION, DEFAULTS, NAME_MAP
  File "C:\Users\Daniel\Documents\Spyder\Spyder otros\gonzalo\spyder\spyder\config\main.py", line 19, in <module>
    from spyder.config.fonts import MEDIUM, SANS_SERIF
  File "C:\Users\Daniel\Documents\Spyder\Spyder otros\gonzalo\spyder\spyder\config\fonts.py", line 14, in <module>
    from spyder.config.utils import is_ubuntu
  File "C:\Users\Daniel\Documents\Spyder\Spyder otros\gonzalo\spyder\spyder\config\utils.py", line 17, in <module>
    from spyder_kernels.utils import iofuncs
ModuleNotFoundError: No module named 'spyder_kernels'

```

A way to trigger a restart is to change an appearance preference (like changing the theme to light)

_Originally posted by @dalthviz in https://github.com/spyder-ide/spyder/pull/12793#issuecomment-655125635_

**Comment by dalthviz** [comment]
Seems like this is working now when testing with Spyder 5.2.0.dev0 - Revision 33dce2a0e, Branch: 5.x so closing
