### ISSUE TITLE
while openining spyder i get this issue in python console can someone please help me on how to fix this issue

### ISSUE THREAD

**Issue by jithik18** [spyder-ide/spyder#13243]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
File "/home/hp/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/home/hp/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/hp/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/home/hp/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 287, in main
import_spydercustomize()
File "/home/hp/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 39, in import_spydercustomize
import spydercustomize
File "/home/hp/anaconda3/lib/python3.7/site‑packages/spyder_kernels/customize/spydercustomize.py", line 27, in 
from IPython.core.getipython import get_ipython
File "/home/hp/anaconda3/lib/python3.7/site‑packages/IPython/__init__.py", line 54, in 
from .core.application import Application
File "/home/hp/anaconda3/lib/python3.7/site‑packages/IPython/core/application.py", line 23, in 
from traitlets.config.application import Application, catch_config_error
File "/home/hp/anaconda3/lib/python3.7/site‑packages/traitlets/config/__init__.py", line 6, in 
from .application import *
File "/home/hp/anaconda3/lib/python3.7/site‑packages/traitlets/config/application.py", line 17, in 
from decorator import decorator
ImportError: cannot import name 'decorator' from 'decorator' (/home/hp/decorator.py)

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Please remove or rename this file

    /home/hp/decorator.py

to fix your problem.
