### ISSUE TITLE
cannot install spyder 

### ISSUE THREAD

**Issue by hafez-ahmad** [spyder-ide/spyder#13258]
I am trying to install in anaconda's virtual environment. I am currently using python 3.7. 

## Problem Description

conda install -c anaconda spyder
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

when I tried with pip 

pip install spyder

Traceback (most recent call last):
  File "C:\Users\hafez\anaconda3\envs\ocean\Scripts\pip-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\pip\_internal\cli\main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\pip\_internal\commands\__init__.py", line 104, in create_command
    module = importlib.import_module(module_path)
  File "C:\Users\hafez\anaconda3\envs\ocean\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\pip\_internal\commands\install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand, with_cleanup
  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\pip\_internal\cli\req_command.py", line 16, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\pip\_internal\index\package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\pip\_internal\index\collector.py", line 14, in <module>
    from pip._vendor import html5lib, requests
  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\pip\_vendor\requests\__init__.py", line 43, in <module>
    from pip._vendor import urllib3
  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\pip\_vendor\urllib3\__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 39, in <module>
    from .response import HTTPResponse
  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\pip\_vendor\urllib3\response.py", line 155, in <module>
    class HTTPResponse(io.IOBase):
  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\pip\_vendor\urllib3\response.py", line 377, in HTTPResponse
    DECODER_ERROR_CLASSES += (brotli.error,)
AttributeError: module 'brotli' has no attribute 'error'

**Comment by juanis2112** [comment]
Hi @hafez-ahmad thanks for opening this. Please try:
```
conda update anaconda
conda update spyder
```

If this doesn't work, it might be because using pip might have broken your packages in your base environment. We don't recommend mixing pip and conda package installation in the same environment. This video can help you figure out any issues you might run into:

https://youtu.be/Ul79ihg41Rs

**Comment by juanis2112** [comment]
Closing for no response
