### ISSUE TITLE
PermissionError raised from .ipython/.matplotlib/folders when starting the kernel/using the IPython Console

### ISSUE THREAD

**Issue by galtech** [spyder-ide/spyder#13304]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I open Spyder and get a traceback error indicating the kernel cannot be stated. 

### What steps reproduce the problem?

1. Open Spyder after a standard Anaconda installation

Note: I then try going to Consoles>restart kernel and Spyder goes into a loop saying "Kernel died, restarting" 

### What is the expected output? What do you see instead?

Kernel should start allowing me to use Spyder

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.3
* Python version: 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10 Enterprise

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Hi @galtech sorry to hear that, seems like in the past the issue your are experiencing was fixed by running:

```
conda update anaconda
conda install jupyter_client=5.3.4
```

However, seems like in your case this doesn't work. Did you install Anaconda as an Administrator or only for the current user?  From the traceback in #13303 seems like you are facing a `PermissionError` while the profile of IPython in being loaded. Some actions to understand better what could be happening and as a workaround:

* Could you paste here the dependencies in your env? (running `conda list` over the env should be enough)?
* Could you try to run Spyder with Administrator rights?
* Could you try to create a conda env with something like `conda create -n spyder_env python=3.7 spyder=4.1.3` and see if there Spyder starts in the proper way?

Thanks!

**Comment by galtech** [comment]
Hi @dalthviz 
Thank you for the reply. I have tried running the update conda and install jupyter commands and the issue remains. 

I did install Anaconda for my own user only. Should I have installed for all users instead? 

There is no error or problem with the kernel when running Spyder as an administrator.  

Dependencies: 
```
# packages in environment at C:\Users\HEYLINP\Anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2020.02                  py37_0
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
alabaster                 0.7.12                   py37_0
anaconda                  custom                   py37_1
anaconda-client           1.7.2                    py37_0
anaconda-navigator        1.9.12                   py37_0
anaconda-project          0.8.4                      py_0
argh                      0.26.2                   py37_0
asn1crypto                1.3.0                    py37_1
astroid                   2.3.3                    py37_0
astropy                   4.0.1.post1      py37he774522_1
atomicwrites              1.4.0                      py_0
attrs                     19.3.0                     py_0
autopep8                  1.4.4                      py_0
babel                     2.8.0                      py_0
backcall                  0.2.0                      py_0
backports                 1.0                        py_2
backports.functools_lru_cache 1.6.1                      py_0
backports.shutil_get_terminal_size 1.0.0                    py37_2
backports.tempfile        1.0                        py_1
backports.weakref         1.0.post1                  py_1
bcrypt                    3.1.7            py37he774522_1
beautifulsoup4            4.9.1                    py37_0
bitarray                  1.3.0            py37he774522_0
bkcharts                  0.2                      py37_0
blas                      1.0                         mkl
bleach                    3.1.5                      py_0
blosc                     1.19.0               h7bd577a_0
bokeh                     2.1.1                    py37_0
boto                      2.49.0                   py37_0
bottleneck                1.3.2            py37h2a96729_1
brotlipy                  0.7.0           py37he774522_1000
bzip2                     1.0.8                he774522_0
ca-certificates           2020.6.24                     0
certifi                   2020.6.20                py37_0
cffi                      1.14.0           py37h7a1dbc1_0
chardet                   3.0.4                 py37_1003
click                     7.1.2                      py_0
cloudpickle               1.5.0                      py_0
clyent                    1.2.2                    py37_1
colorama                  0.4.3                      py_0
comtypes                  1.1.7                 py37_1001
conda                     4.8.3                    py37_0
conda-build               3.18.11                  py37_0
conda-env                 2.6.0                         1
conda-package-handling    1.6.1            py37h62dcd97_0
conda-verify              3.4.2                      py_1
console_shortcut          0.1.1                         4
contextlib2               0.6.0.post1                py_0
cryptography              2.9.2            py37h7a1dbc1_0
curl                      7.71.0               h2a8f88b_0
cycler                    0.10.0                   py37_0
cython                    0.29.20          py37ha925a31_0
cytoolz                   0.10.1           py37he774522_0
dask                      2.20.0                     py_0
dask-core                 2.20.0                     py_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
diff-match-patch          20181111                   py_0
distributed               2.20.0                   py37_0
docutils                  0.16                     py37_1
entrypoints               0.3                      py37_0
et_xmlfile                1.0.1                   py_1001
fastcache                 1.1.0            py37he774522_0
filelock                  3.0.12                     py_0
flake8                    3.7.9                    py37_0
flask                     1.1.2                      py_0
freetype                  2.10.2               hd328e21_0
fsspec                    0.7.4                      py_0
future                    0.18.2                   py37_1
get_terminal_size         1.0.0                h38e98db_0
gevent                    20.6.2           py37he774522_0
glob2                     0.7                        py_0
greenlet                  0.4.16           py37he774522_0
h5py                      2.10.0           py37h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
heapdict                  1.0.1                      py_0
html5lib                  1.1                        py_0
hypothesis                5.18.3                     py_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      2.10                       py_0
imageio                   2.9.0                      py_0
imagesize                 1.2.0                      py_0
importlib-metadata        1.7.0                    py37_0
importlib_metadata        1.7.0                         0
intel-openmp              2020.1                      216
intervaltree              3.0.2                      py_1
ipykernel                 5.3.0            py37h5ca1d4c_0
ipython                   7.16.1           py37h5ca1d4c_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.5.1                      py_0
isort                     4.3.21                   py37_0
itsdangerous              1.1.0                    py37_0
jdcal                     1.4.1                      py_0
jedi                      0.15.2                   py37_0
jinja2                    2.11.2                     py_0
joblib                    0.16.0                     py_0
jpeg                      9b                   hb83a4c4_2
json5                     0.9.5                      py_0
jsonschema                3.2.0                    py37_1
jupyter                   1.0.0                    py37_7
jupyter_client            5.3.4                    py37_0
jupyter_console           6.1.0                      py_0
jupyter_core              4.6.3                    py37_0
jupyterlab                2.1.5                      py_0
jupyterlab_server         1.2.0                      py_0
keyring                   21.2.1                   py37_0
kiwisolver                1.2.0            py37h74a9793_0
krb5                      1.18.2               hc04afaa_0
lazy-object-proxy         1.5.0            py37he774522_0
libarchive                3.4.2                h5e25573_0
libcurl                   7.71.0               h2a8f88b_0
libiconv                  1.15                 h1df5818_7
liblief                   0.10.1               ha925a31_0
libllvm9                  9.0.1                h21ff451_0
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h33f27b4_0
libssh2                   1.9.0                h7a1dbc1_1
libtiff                   4.1.0                h56a325e_1
libxml2                   2.9.10               h464c3ec_1
libxslt                   1.1.34               he774522_0
llvmlite                  0.33.0           py37ha925a31_0
locket                    0.2.0                    py37_1
lxml                      4.5.1            py37h1350720_0
lz4-c                     1.9.2                h62dcd97_0
lzo                       2.10                 he774522_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py37hfa6e2cd_1
matplotlib                3.2.2                         0
matplotlib-base           3.2.2            py37h64f37c6_0
mccabe                    0.6.1                    py37_1
menuinst                  1.4.16           py37he774522_0
mistune                   0.8.4           py37hfa6e2cd_1001
mkl                       2020.1                      216
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.1.0            py37h45dec08_0
mkl_random                1.1.1            py37h47e9c7a_0
mock                      4.0.2                      py_0
more-itertools            8.4.0                      py_0
mpmath                    1.1.0                    py37_0
msgpack-python            1.0.0            py37h74a9793_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py37_0
navigator-updater         0.2.1                    py37_0
nbconvert                 5.6.1                    py37_1
nbformat                  5.0.7                      py_0
networkx                  2.4                        py_1
nltk                      3.5                        py_0
nose                      1.3.7                 py37_1004
notebook                  6.0.3                    py37_0
numba                     0.50.1           py37h47e9c7a_0
numexpr                   2.7.1            py37h25d0782_0
numpy                     1.18.5           py37h6530119_0
numpy-base                1.18.5           py37hc3f5095_0
numpydoc                  1.1.0                      py_0
olefile                   0.46                     py37_0
openpyxl                  3.0.4                      py_0
openssl                   1.1.1g               he774522_0
packaging                 20.4                       py_0
pandas                    1.0.5            py37h47e9c7a_0
pandoc                    2.9.2.1                       0
pandocfilters             1.4.2                    py37_1
paramiko                  2.7.1                      py_0
parso                     0.5.2                      py_0
partd                     1.1.0                      py_0
path                      13.1.0                   py37_0
path.py                   12.4.0                        0
pathlib2                  2.3.5                    py37_1
pathtools                 0.1.2                      py_1
patsy                     0.5.1                    py37_0
pep8                      1.7.1                    py37_0
pexpect                   4.8.0                    py37_1
pickleshare               0.7.5                 py37_1001
pillow                    7.2.0            py37hcc1f983_0
pip                       20.1.1                   py37_1
pkginfo                   1.5.0.1                  py37_0
pluggy                    0.13.1                   py37_0
ply                       3.11                     py37_0
powershell_shortcut       0.0.1                         3
prometheus_client         0.8.0                      py_0
prompt-toolkit            3.0.5                      py_0
prompt_toolkit            3.0.5                         0
psutil                    5.7.0            py37he774522_0
py                        1.9.0                      py_0
py-lief                   0.10.1           py37ha925a31_0
pycodestyle               2.5.0                    py37_0
pycosat                   0.6.3            py37he774522_0
pycparser                 2.20                       py_2
pycrypto                  2.6.1           py37he774522_10
pycurl                    7.43.0.5         py37h7a1dbc1_0
pydocstyle                5.0.2                      py_0
pyflakes                  2.1.1                    py37_0
pygments                  2.6.1                      py_0
pylint                    2.4.4                    py37_0
pynacl                    1.4.0            py37h62dcd97_0
pyodbc                    4.0.30           py37ha925a31_0
pyopenssl                 19.1.0                     py_1
pyparsing                 2.4.7                      py_0
pyqt                      5.9.2            py37h6538335_2
pyreadline                2.1                      py37_1
pyrsistent                0.16.0           py37he774522_0
pysocks                   1.7.1                    py37_1
pytables                  3.6.1            py37h1da0976_0
pytest                    5.4.3                    py37_0
pytest-arraydiff          0.3              py37h39e3cac_0
pytest-astropy            0.8.0                      py_0
pytest-astropy-header     0.1.2                      py_0
pytest-doctestplus        0.7.0                      py_0
pytest-openfiles          0.5.0                      py_0
pytest-remotedata         0.3.2                    py37_0
python                    3.7.6                h60c2a47_2
python-dateutil           2.8.1                      py_0
python-jsonrpc-server     0.3.4                      py_1
python-language-server    0.31.10                  py37_0
python-libarchive-c       2.9                        py_0
pytz                      2020.1                     py_0
pywavelets                1.1.1            py37he774522_0
pywin32                   227              py37he774522_1
pywin32-ctypes            0.2.0                 py37_1001
pywinpty                  0.5.7                    py37_0
pyyaml                    5.3.1            py37he774522_1
pyzmq                     19.0.1           py37ha925a31_1
qdarkstyle                2.8.1                      py_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.7.2                      py_0
qtconsole                 4.7.5                      py_0
qtpy                      1.9.0                      py_0
regex                     2020.6.8         py37he774522_0
requests                  2.24.0                     py_0
rope                      0.17.0                     py_0
rtree                     0.9.4            py37h21ff451_1
ruamel_yaml               0.15.87          py37he774522_1
scikit-image              0.16.2           py37h47e9c7a_0
scikit-learn              0.23.1           py37h25d0782_0
scipy                     1.5.0            py37h9439919_0
seaborn                   0.10.1                     py_0
send2trash                1.5.0                    py37_0
setuptools                49.1.0                   py37_0
simplegeneric             0.8.1                    py37_2
singledispatch            3.4.0.3                  py37_0
sip                       4.19.8           py37h6538335_0
six                       1.15.0                     py_0
snappy                    1.1.8                h33f27b4_0
snowballstemmer           2.0.0                      py_0
sortedcollections         1.2.1                      py_0
sortedcontainers          2.2.2                      py_0
soupsieve                 2.0.1                      py_0
sphinx                    3.1.2                      py_0
sphinxcontrib             1.0                      py37_1
sphinxcontrib-applehelp   1.0.2                      py_0
sphinxcontrib-devhelp     1.0.2                      py_0
sphinxcontrib-htmlhelp    1.0.3                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.3                      py_0
sphinxcontrib-serializinghtml 1.1.4                      py_0
sphinxcontrib-websupport  1.2.3                      py_0
spyder                    4.1.3                    py37_0
spyder-kernels            1.9.1                    py37_0
sqlalchemy                1.3.18           py37he774522_0
sqlite                    3.32.3               h2a8f88b_0
statsmodels               0.11.1           py37he774522_0
sympy                     1.6.1                    py37_0
tbb                       2020.0               h74a9793_0
tblib                     1.6.0                      py_0
terminado                 0.8.3                    py37_0
testpath                  0.4.4                      py_0
threadpoolctl             2.1.0              pyh5ca1d4c_0
tk                        8.6.10               he774522_0
toolz                     0.10.0                     py_0
tornado                   6.0.4            py37he774522_1
tqdm                      4.47.0                     py_0
traitlets                 4.3.3                    py37_0
typing_extensions         3.7.4.2                    py_0
ujson                     1.35             py37hfa6e2cd_0
unicodecsv                0.14.1                   py37_0
urllib3                   1.25.9                     py_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
watchdog                  0.10.3                   py37_0
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py37_1
werkzeug                  1.0.1                      py_0
wheel                     0.34.2                   py37_0
widgetsnbextension        3.5.1                    py37_0
win_inet_pton             1.1.0                    py37_0
win_unicode_console       0.5                      py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.12.1           py37he774522_1
xlrd                      1.2.0                    py37_0
xlsxwriter                1.2.9                      py_0
xlwings                   0.19.5                   py37_0
xlwt                      1.3.0                    py37_0
xmltodict                 0.12.0                     py_0
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
yapf                      0.30.0                     py_0
zeromq                    4.3.2                ha925a31_2
zict                      2.0.0                      py_0
zipp                      3.1.0                      py_0
zlib                      1.2.11               h62dcd97_4
zope                      1.0                      py37_1
zope.event                4.4                      py37_0
zope.interface            4.7.1            py37he774522_0
zstd                      1.4.4                ha9fde0e_3
```

**Comment by dalthviz** [comment]
Thanks for the info @galtech there should be no need for you to install Anaconda as an administrator.

Taking into account the info, could you try to change the permissions over the `.ipython` folder under your user home directory and content in order for your user to edit the content and check again if running spyder without admin rights is possible?

**Comment by galtech** [comment]
Hi @dalthviz 
Thank you for the tip. I amended the permissions of the ipython folder and when I open Spyder the kernel runs allowing me to run scripts. There is a traceback error at the top that mentions another permissions error (this does not appear to stop the kernel from running). Any advice would be greatly appreciated. 
```
Traceback (most recent call last):
  File "C:\Users\HEYLINP\Anaconda3\lib\site-packages\matplotlib\font_manager.py", line 1341, in <module>
    fontManager = json_load(_fmcache)
  File "C:\Users\HEYLINP\Anaconda3\lib\site-packages\matplotlib\font_manager.py", line 936, in json_load
    with open(filename, 'r') as fh:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\HEYLINP\\.matplotlib\\fontlist-v310.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HEYLINP\Anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 568, in _set_mpl_backend
    get_ipython().run_line_magic(magic, backend)
  File "C:\Users\HEYLINP\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2326, in run_line_magic
    result = fn(*args, **kwargs)
  File "<decorator-gen-109>", line 2, in matplotlib
  File "C:\Users\HEYLINP\Anaconda3\lib\site-packages\IPython\core\magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "C:\Users\HEYLINP\Anaconda3\lib\site-packages\IPython\core\magics\pylab.py", line 99, in matplotlib
    gui, backend = self.shell.enable_matplotlib(args.gui.lower() if isinstance(args.gui, str) else args.gui)
  File "C:\Users\HEYLINP\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3431, in enable_matplotlib
    pt.activate_matplotlib(backend)
  File "C:\Users\HEYLINP\Anaconda3\lib\site-packages\IPython\core\pylabtools.py", line 320, in activate_matplotlib
    from matplotlib import pyplot as plt
  File "C:\Users\HEYLINP\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "C:\Users\HEYLINP\Anaconda3\lib\site-packages\matplotlib\colorbar.py", line 31, in <module>
    import matplotlib.contour as contour
  File "C:\Users\HEYLINP\Anaconda3\lib\site-packages\matplotlib\contour.py", line 16, in <module>
    import matplotlib.font_manager as font_manager
  File "C:\Users\HEYLINP\Anaconda3\lib\site-packages\matplotlib\font_manager.py", line 1343, in <module>
    _rebuild()
  File "C:\Users\HEYLINP\Anaconda3\lib\site-packages\matplotlib\font_manager.py", line 1335, in _rebuild
    with cbook._lock_path(_fmcache):
  File "C:\Users\HEYLINP\Anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\HEYLINP\Anaconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 1821, in _lock_path
    with lock_path.open("xb"):
  File "C:\Users\HEYLINP\Anaconda3\lib\pathlib.py", line 1203, in open
    opener=self._opener)
  File "C:\Users\HEYLINP\Anaconda3\lib\pathlib.py", line 1058, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\HEYLINP\\.matplotlib\\fontlist-v310.json.matplotlib-lock'
```

**Comment by dalthviz** [comment]
@galtech seems like you need to check the permissions for the folders in your home directory and their content (in this case `.matplolib`) and give your user (the one you are using to run Spyder) the appropriate access as you did with the `.ipython` folder.

**Comment by galtech** [comment]
I've done that. It looks good now @dalthviz 
Thank you for your help.
