### ISSUE TITLE
An error ocurred while starting the kernel following standard Anaconda installation

### ISSUE THREAD

**Issue by galtech** [spyder-ide/spyder#13301]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

An error is occurring when starting the kernel following a standard Anaconda installation. This results in the console being unusable. 

### What steps reproduce the problem?

1. Download Anaconda from spyder-ide.org
2.  Install with default options
3.  Open Spyder 

### What is the expected output? What do you see instead?

The consol.e should start so that I can use Spyder

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\application.py", line 362, in init_profile_dir
p = ProfileDir.find_profile_dir_by_name(self.ipython_dir, self.profile, self.config)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 207, in find_profile_dir_by_name
raise ProfileDirError('Profile directory not found in paths: %s' % dirname)
IPython.core.profiledir.ProfileDirError: Profile directory not found in paths: profile_default

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\HEYLINP\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\HEYLINP\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 306, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 540, in initialize
super(IPKernelApp, self).initialize(argv)
File "", line 2, in initialize
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\application.py", line 458, in initialize
self.init_profile_dir()
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\application.py", line 367, in init_profile_dir
p = ProfileDir.create_profile_dir_by_name(self.ipython_dir, self.profile, self.config)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 179, in create_profile_dir_by_name
return cls(location=profile_dir, config=config)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\config\configurable.py", line 73, in __init__
super(Configurable, self).__init__(**kwargs)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1000, in __init__
super_kwargs[key] = value
File "C:\Users\HEYLINP\Anaconda3\lib\contextlib.py", line 119, in __exit__
next(self.gen)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1131, in hold_trait_notifications
self.notify_change(change)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1176, in notify_change
c(change)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 66, in _location_changed
self.startup_dir = os.path.join(new, self.startup_dir_name)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 585, in __set__
self.set(obj, value)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 574, in set
obj._notify_trait(self.name, old_value, new_value)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1139, in _notify_trait
type='change',
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1176, in notify_change
c(change)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 120, in check_startup_dir
shutil.copy(src, readme)
File "C:\Users\HEYLINP\Anaconda3\lib\shutil.py", line 248, in copy
copyfile(src, dst, follow_symlinks=follow_symlinks)
File "C:\Users\HEYLINP\Anaconda3\lib\shutil.py", line 121, in copyfile
with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\HEYLINP\\.ipython\\profile_default\\startup\\README'
Traceback (most recent call last):
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\application.py", line 362, in init_profile_dir
p = ProfileDir.find_profile_dir_by_name(self.ipython_dir, self.profile, self.config)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 207, in find_profile_dir_by_name
raise ProfileDirError('Profile directory not found in paths: %s' % dirname)
IPython.core.profiledir.ProfileDirError: Profile directory not found in paths: profile_default

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\HEYLINP\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\HEYLINP\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 306, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 540, in initialize
super(IPKernelApp, self).initialize(argv)
File "", line 2, in initialize
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\application.py", line 458, in initialize
self.init_profile_dir()
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\application.py", line 367, in init_profile_dir
p = ProfileDir.create_profile_dir_by_name(self.ipython_dir, self.profile, self.config)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 179, in create_profile_dir_by_name
return cls(location=profile_dir, config=config)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\config\configurable.py", line 73, in __init__
super(Configurable, self).__init__(**kwargs)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1000, in __init__
super_kwargs[key] = value
File "C:\Users\HEYLINP\Anaconda3\lib\contextlib.py", line 119, in __exit__
next(self.gen)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1131, in hold_trait_notifications
self.notify_change(change)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1176, in notify_change
c(change)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 66, in _location_changed
self.startup_dir = os.path.join(new, self.startup_dir_name)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 585, in __set__
self.set(obj, value)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 574, in set
obj._notify_trait(self.name, old_value, new_value)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1139, in _notify_trait
type='change',
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1176, in notify_change
c(change)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 120, in check_startup_dir
shutil.copy(src, readme)
File "C:\Users\HEYLINP\Anaconda3\lib\shutil.py", line 248, in copy
copyfile(src, dst, follow_symlinks=follow_symlinks)
File "C:\Users\HEYLINP\Anaconda3\lib\shutil.py", line 121, in copyfile
with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\HEYLINP\\.ipython\\profile_default\\startup\\README'
Traceback (most recent call last):
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\application.py", line 362, in init_profile_dir
p = ProfileDir.find_profile_dir_by_name(self.ipython_dir, self.profile, self.config)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 207, in find_profile_dir_by_name
raise ProfileDirError('Profile directory not found in paths: %s' % dirname)
IPython.core.profiledir.ProfileDirError: Profile directory not found in paths: profile_default

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\HEYLINP\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\HEYLINP\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 306, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 540, in initialize
super(IPKernelApp, self).initialize(argv)
File "", line 2, in initialize
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\application.py", line 458, in initialize
self.init_profile_dir()
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\application.py", line 367, in init_profile_dir
p = ProfileDir.create_profile_dir_by_name(self.ipython_dir, self.profile, self.config)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 179, in create_profile_dir_by_name
return cls(location=profile_dir, config=config)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\config\configurable.py", line 73, in __init__
super(Configurable, self).__init__(**kwargs)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1000, in __init__
super_kwargs[key] = value
File "C:\Users\HEYLINP\Anaconda3\lib\contextlib.py", line 119, in __exit__
next(self.gen)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1131, in hold_trait_notifications
self.notify_change(change)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1176, in notify_change
c(change)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 66, in _location_changed
self.startup_dir = os.path.join(new, self.startup_dir_name)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 585, in __set__
self.set(obj, value)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 574, in set
obj._notify_trait(self.name, old_value, new_value)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1139, in _notify_trait
type='change',
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1176, in notify_change
c(change)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 120, in check_startup_dir
shutil.copy(src, readme)
File "C:\Users\HEYLINP\Anaconda3\lib\shutil.py", line 248, in copy
copyfile(src, dst, follow_symlinks=follow_symlinks)
File "C:\Users\HEYLINP\Anaconda3\lib\shutil.py", line 121, in copyfile
with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\HEYLINP\\.ipython\\profile_default\\startup\\README'
Traceback (most recent call last):
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\application.py", line 362, in init_profile_dir
p = ProfileDir.find_profile_dir_by_name(self.ipython_dir, self.profile, self.config)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 207, in find_profile_dir_by_name
raise ProfileDirError('Profile directory not found in paths: %s' % dirname)
IPython.core.profiledir.ProfileDirError: Profile directory not found in paths: profile_default

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\HEYLINP\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\HEYLINP\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 306, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 540, in initialize
super(IPKernelApp, self).initialize(argv)
File "", line 2, in initialize
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\application.py", line 458, in initialize
self.init_profile_dir()
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\application.py", line 367, in init_profile_dir
p = ProfileDir.create_profile_dir_by_name(self.ipython_dir, self.profile, self.config)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 179, in create_profile_dir_by_name
return cls(location=profile_dir, config=config)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\config\configurable.py", line 73, in __init__
super(Configurable, self).__init__(**kwargs)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1000, in __init__
super_kwargs[key] = value
File "C:\Users\HEYLINP\Anaconda3\lib\contextlib.py", line 119, in __exit__
next(self.gen)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1131, in hold_trait_notifications
self.notify_change(change)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1176, in notify_change
c(change)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 66, in _location_changed
self.startup_dir = os.path.join(new, self.startup_dir_name)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 585, in __set__
self.set(obj, value)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 574, in set
obj._notify_trait(self.name, old_value, new_value)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1139, in _notify_trait
type='change',
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1176, in notify_change
c(change)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 120, in check_startup_dir
shutil.copy(src, readme)
File "C:\Users\HEYLINP\Anaconda3\lib\shutil.py", line 248, in copy
copyfile(src, dst, follow_symlinks=follow_symlinks)
File "C:\Users\HEYLINP\Anaconda3\lib\shutil.py", line 121, in copyfile
with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\HEYLINP\\.ipython\\profile_default\\startup\\README'
Traceback (most recent call last):
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\application.py", line 362, in init_profile_dir
p = ProfileDir.find_profile_dir_by_name(self.ipython_dir, self.profile, self.config)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 207, in find_profile_dir_by_name
raise ProfileDirError('Profile directory not found in paths: %s' % dirname)
IPython.core.profiledir.ProfileDirError: Profile directory not found in paths: profile_default

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\HEYLINP\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\HEYLINP\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 306, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 540, in initialize
super(IPKernelApp, self).initialize(argv)
File "", line 2, in initialize
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\application.py", line 458, in initialize
self.init_profile_dir()
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\application.py", line 367, in init_profile_dir
p = ProfileDir.create_profile_dir_by_name(self.ipython_dir, self.profile, self.config)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 179, in create_profile_dir_by_name
return cls(location=profile_dir, config=config)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\config\configurable.py", line 73, in __init__
super(Configurable, self).__init__(**kwargs)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1000, in __init__
super_kwargs[key] = value
File "C:\Users\HEYLINP\Anaconda3\lib\contextlib.py", line 119, in __exit__
next(self.gen)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1131, in hold_trait_notifications
self.notify_change(change)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1176, in notify_change
c(change)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 66, in _location_changed
self.startup_dir = os.path.join(new, self.startup_dir_name)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 585, in __set__
self.set(obj, value)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 574, in set
obj._notify_trait(self.name, old_value, new_value)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1139, in _notify_trait
type='change',
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1176, in notify_change
c(change)
File "C:\Users\HEYLINP\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 120, in check_startup_dir
shutil.copy(src, readme)
File "C:\Users\HEYLINP\Anaconda3\lib\shutil.py", line 248, in copy
copyfile(src, dst, follow_symlinks=follow_symlinks)
File "C:\Users\HEYLINP\Anaconda3\lib\shutil.py", line 121, in copyfile
with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\HEYLINP\\.ipython\\profile_default\\startup\\README'

```

## Versions

* Spyder version: 4.0.1
* Python version: 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10 Enterprise

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by galtech** [comment]
I tried these steps, result is same issue, same error.
