### ISSUE TITLE
keyboard shortcuts (in manjaro/arch linux)

### ISSUE THREAD

**Issue by icannotdothecode** [spyder-ide/spyder#13326]
### What steps will reproduce the problem?

pressing keyboard shortcuts causes Spyder to encounter an internal error.

### Traceback
```python-traceback
  File "/usr/lib/python3.8/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.8.3
* Qt version: 5.15.0
* PyQt5 version: 5.15.0
* Operating System: Linux 5.6.16-1-MANJARO

### Dependencies

```
pyflakes >=0.6.0  :  2.2.0 (OK)
pycodestyle >=2.3 :  2.6.0 (OK)
pygments >=2.0    :  2.1.3 (OK)
sphinx >=0.6.6    :  3.0.4 (OK)
rope >=0.9.4      :  0.17.0 (OK)
jedi >=0.9.0      :  0.17.0 (OK)
psutil >=0.3      :  5.7.0 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  None (NOK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.7.3 (OK)
IPython >=4.0     :  7.15.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.5.2 (OK)
```

**Comment by juanis2112** [comment]
Hi @icannotdothecode, this bug was solved in Spyder4. Please run the following commands in your command line:
```
conda update anaconda
conda install spyder=4.1.4
```

**Comment by icannotdothecode** [comment]
That fixed it, thanks!
