### ISSUE TITLE
traceback a value error when viewing-editing arrays in variable explorer

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1332]
_From [jichengl...@gmail.com](https://code.google.com/u/112107071011487304650/) on 2013-03-25T19:23:16Z_

Spyder Version:  2.1.11
Python Version:  2.7.3
Qt Version:      4.8.3, PyQt4 (API v2) 4.9.5 on Windows 

What steps will reproduce the problem?

 1.double click on a numpy array in the variable explorer
2.or drag the editor slider after double click on a array in the variable explore 3. What is the expected output? What do you see instead? i just want see the number in the array,however at the same time the console always show me a value error:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\widgets\arrayeditor.py", line 342, in keyPressEvent
    self.copy()
  File "C:\Python27\lib\site-packages\spyderlib\widgets\arrayeditor.py", line 360, in copy
    cliptxt = self._sel_to_text( self.selectedIndexes() )
  File "C:\Python27\lib\site-packages\spyderlib\widgets\arrayeditor.py", line 348, in _sel_to_text
    row_min, row_max, col_min, col_max = get_idx_rect(cell_range)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\arrayeditor.py", line 88, in get_idx_rect
    rows, cols = zip(*[(i.row(), i.column()) for i in index_list])
ValueError: need more than 0 values to unpack 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1332_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-04-11T11:33:14Z_

Please update to version 2.1.13.1 and see if that fixes the error.

**Comment by spyder-issues-migrator** [comment]
_From [jichengl...@gmail.com](https://code.google.com/u/112107071011487304650/) on 2013-04-12T03:43:57Z_

thanks a lot,at last,it's ok now~ i have try that several times, it seems
that i have to remove all the files in the workspace or swich to another

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-04-13T11:17:37Z_

**Status:** Done
