### ISSUE TITLE
An internal problem error message shows up every few seconds

### ISSUE THREAD

**Issue by bsierieb1** [spyder-ide/spyder#13415]
### What steps will reproduce the problem?

This happens every time I start spyder. Nothing seems to be affected, but it is annoying.

### Traceback
```python-traceback
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1401, in handle_folding_range
    folding_panel.update_folding(ranges)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/panels/codefolding.py", line 231, in update_folding
    nested_regions = tree.envelop(start, end)
AttributeError: 'IntervalTree' object has no attribute 'envelop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "/opt/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 205, in main
    mainwindow.main()
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3600, in run_spyder
    app.exec_()
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/client.py", line 378, in on_msg_received
    handler(resp['result'], req_id)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/providers/document.py", line 234, in process_folding_range
    {'params': results})
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/plugin.py", line 302, in receive_response
    self.COMPLETION_CLIENT_NAME, req_id, response)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 120, in receive_response
    self._maybe_send_locked(req_id)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 155, in _maybe_send_locked
    send()
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 143, in send
    self.gather_and_send(request_responses)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 212, in gather_and_send
    response_instance.handle_response(req_type, responses)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 940, in handle_response
    handler(params)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1412, in handle_folding_range
    self.log_lsp_handle_errors("Error when processing folding")
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 971, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
--- Logging error ---
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1051, in process_symbols
    self.classfuncdropdown.update_data(symbols)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/panels/classfunctiondropdown.py", line 220, in update_data
    self.populate(self.method_cb, self.funcs, add_parents=True)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/panels/classfunctiondropdown.py", line 151, in populate
    possible_parents = sorted(self._tree.overlap(begin, end),
AttributeError: 'IntervalTree' object has no attribute 'overlap'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "/opt/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 205, in main
    mainwindow.main()
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3600, in run_spyder
    app.exec_()
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/client.py", line 378, in on_msg_received
    handler(resp['result'], req_id)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/providers/document.py", line 184, in process_document_symbol_request
    {'params': result})
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/plugin.py", line 302, in receive_response
    self.COMPLETION_CLIENT_NAME, req_id, response)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 120, in receive_response
    self._maybe_send_locked(req_id)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 161, in _maybe_send_locked
    send()
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 143, in send
    self.gather_and_send(request_responses)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 212, in gather_and_send
    response_instance.handle_response(req_type, responses)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 940, in handle_response
    handler(params)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1057, in process_symbols
    self.log_lsp_handle_errors("Error when processing symbols")
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 971, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
--- Logging error ---
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1401, in handle_folding_range
    folding_panel.update_folding(ranges)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/panels/codefolding.py", line 231, in update_folding
    nested_regions = tree.envelop(start, end)
AttributeError: 'IntervalTree' object has no attribute 'envelop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "/opt/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 205, in main
    mainwindow.main()
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3600, in run_spyder
    app.exec_()
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/client.py", line 378, in on_msg_received
    handler(resp['result'], req_id)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/providers/document.py", line 234, in process_folding_range
    {'params': results})
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/plugin.py", line 302, in receive_response
    self.COMPLETION_CLIENT_NAME, req_id, response)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 120, in receive_response
    self._maybe_send_locked(req_id)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 161, in _maybe_send_locked
    send()
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 143, in send
    self.gather_and_send(request_responses)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 212, in gather_and_send
    response_instance.handle_response(req_type, responses)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 940, in handle_response
    handler(params)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1412, in handle_folding_range
    self.log_lsp_handle_errors("Error when processing folding")
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 971, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
--- Logging error ---
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1051, in process_symbols
    self.classfuncdropdown.update_data(symbols)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/panels/classfunctiondropdown.py", line 220, in update_data
    self.populate(self.method_cb, self.funcs, add_parents=True)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/panels/classfunctiondropdown.py", line 151, in populate
    possible_parents = sorted(self._tree.overlap(begin, end),
AttributeError: 'IntervalTree' object has no attribute 'overlap'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "/opt/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 205, in main
    mainwindow.main()
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3600, in run_spyder
    app.exec_()
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/client.py", line 378, in on_msg_received
    handler(resp['result'], req_id)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/providers/document.py", line 184, in process_document_symbol_request
    {'params': result})
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/plugin.py", line 302, in receive_response
    self.COMPLETION_CLIENT_NAME, req_id, response)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 120, in receive_response
    self._maybe_send_locked(req_id)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 161, in _maybe_send_locked
    send()
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 143, in send
    self.gather_and_send(request_responses)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 212, in gather_and_send
    response_instance.handle_response(req_type, responses)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 940, in handle_response
    handler(params)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1057, in process_symbols
    self.log_lsp_handle_errors("Error when processing symbols")
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 971, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.7.0

### Dependencies

```
applaunchservices >=0.1.7    :  0.2.1 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.10.1 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
zmq >=17                     :  18.1.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
sphinx >=0.6.6               :  2.2.2 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.14 (OK)
matplotlib >=2.0.0           :  3.2.1 (OK)
numpy >=1.7                  :  1.17.4 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.4 (OK)
```

**Comment by dalthviz** [comment]
Hi @bsierieb1 could you try to update Spyder to the latest version (4.1.4) and check again? You can update by running something like `conda install spyder=4.1.4`. Thanks!

**Comment by bsierieb1** [comment]
I was not able to update spyder as I kept getting `'setuptools' is a dependency of conda and cannot be removed from conda's operating environment` error. Instead, I updated conda by executing `conda update --force conda` (it did not work without the `--force` flag), and the issue has been solved. Thanks, @dalthviz
