### ISSUE TITLE
KeyError when using the editor

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1342]
_From [pi...@synchrotron-soleil.fr](https://code.google.com/u/111976521841338120241/) on 2013-04-05T07:48:36Z_

Hello I am using the 2.1.10 version package for the upcoming Debian wheezy distribution.

I see plenty of these messages, when writing in the console.

Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/editor.py", line 228, in update_queue
    end_callback = self.end_callbacks.pop(id(thread))
KeyError: 163588612
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/editor.py", line 228, in update_queue
    end_callback = self.end_callbacks.pop(id(thread))
KeyError: 163588612

cheers

Fred

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1342_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-04-11T10:57:13Z_

I don't know where this errors could be coming from.

Is it not possible for you to update Spyder to 2.1.13.1 in Debian? I'm very sorry but we don't the manpower to fix old versions.

**Labels:** OpSys-Linux MS-v2.1 Cat-Editor

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-04-13T09:47:24Z_

This bug has been fixed for a while now (see issue #1016 ).

**Status:** Duplicate  
  **Mergedinto:** 1016
