### ISSUE TITLE
Running master with bootstrap.py not working?

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#13430]
Running Spyder from the `bootstrap.py` is not working for me (maybe I need to change something in my setup?). This is the traceback I'm getting:

```
Executing Spyder from source checkout
*. Patched sys.path with C:\Users\Daniel\Documents\Spyder\spyder
*. Patched sys.path with C:\Users\Daniel\Documents\Spyder\spyder\external-deps\python-language-server
*. Patched sys.path with C:\Users\Daniel\Documents\Spyder\spyder\external-deps\spyder-kernels
*. PyQt5 is detected, selecting
*. Imported Spyder 5.0.0.dev0 - Revision c00d52dd1, Branch: master
    [Python 3.7.7 64bits, Qt 5.9.6, PyQt5 5.9.2 on Windows]
*. Running Spyder
Bootstrap completed in 00:00:01.1339
Traceback (most recent call last):
  File "bootstrap.py", line 273, in <module>
    start.main()
  File "C:\Users\Daniel\Documents\Spyder\spyder\spyder\app\start.py", line 200, in main
    from spyder.app import mainwindow
  File "C:\Users\Daniel\Documents\Spyder\spyder\spyder\app\mainwindow.py", line 179, in <module>
    from spyder.plugins.help.utils.sphinxify import CSS_PATH, DARK_CSS_PATH
  File "C:\Users\Daniel\Documents\Spyder\spyder\spyder\plugins\help\__init__.py", line 14, in <module>
    from spyder.plugins.help.plugin import Help
  File "C:\Users\Daniel\Documents\Spyder\spyder\spyder\plugins\help\plugin.py", line 23, in <module>
    from spyder.plugins.help.widgets import HelpWidget
  File "C:\Users\Daniel\Documents\Spyder\spyder\spyder\plugins\help\widgets.py", line 29, in <module>
    from spyder.plugins.editor.widgets import codeeditor
  File "C:\Users\Daniel\Documents\Spyder\spyder\spyder\plugins\editor\widgets\codeeditor.py", line 62, in <module>
    from spyder.plugins.completion.kite.widgets.calltoaction import (
ImportError: bad magic number in 'spyder.plugins.completion': b'\x03\xf3\r\n'
```

Revision:  c00d52dd1

Pinging @ccordoba12 and @goanpeca just in case

**Comment by goanpeca** [comment]
Hi @dalthviz,

>ImportError: bad magic number in 'spyder.plugins.completion': b'\x03\xf3\r\n'

This usually means some of the compiled cached files in there (from another PR) are interfering with the current branch you have.

Running:
```
git clean -xfdi
```

Should fix it.

**Comment by dalthviz** [comment]
Yep that worked, thanks @goanpeca :+1:
