### ISSUE TITLE
Terminal plugin fails - unable to find 127.0.0.1

### ISSUE THREAD

**Issue by GregOakes** [spyder-ide/spyder#13445]
### What steps will reproduce the problem?

Installed spyder-terminal, via anaconda3 64b, to spyder4, and started spyder. Startup ends with Spyder Terminal Error popup. Followed instruction to debug spyder; got an error file, terminal output in terminal window, and an empty terminal_out.log file.

Terminal Edrror log:

2020-07-31 20:10:55 LAPTOP-VESB5F0J __main__[1366932] INFO Server is now at: 127.0.0.1:8071
2020-07-31 20:10:55 LAPTOP-VESB5F0J __main__[1366932] INFO Shell: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Traceback (most recent call last):
  File "C:\Users\space\.conda\envs\spyder\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\space\.conda\envs\spyder\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\space\.conda\envs\spyder\lib\site-packages\spyder_terminal\server\__main__.py", line 59, in <module>
    main(port, shell)
  File "C:\Users\space\.conda\envs\spyder\lib\site-packages\spyder_terminal\server\__main__.py", line 44, in main
    application.listen(port, address='127.0.0.1')
  File "C:\Users\space\.conda\envs\spyder\lib\site-packages\tornado\web.py", line 2116, in listen
    server.listen(port, address)
  File "C:\Users\space\.conda\envs\spyder\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "C:\Users\space\.conda\envs\spyder\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "C:\Users\space\.conda\envs\spyder\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "C:\Users\space\.conda\envs\spyder\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Users\space\.conda\envs\spyder\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError

Screen I/O:

(spyder) C:\Users\space>spyder
2020-07-31 20:07:57,962 [INFO] [spyder.app.mainwindow] -> Start of MainWindow constructor
2020-07-31 20:07:57,992 [INFO] [spyder.app.mainwindow] -> appusermodelid: 0
2020-07-31 20:07:58,005 [INFO] [spyder.app.mainwindow] -> End of MainWindow constructor
2020-07-31 20:07:58,005 [INFO] [spyder.app.mainwindow] -> *** Start of MainWindow setup ***
2020-07-31 20:07:58,005 [INFO] [spyder.app.mainwindow] -> Updating PYTHONPATH

2020-07-31 20:07:59,035 [DEBUG] [spyder.api.panel] -> LineNumberArea visibility changed
2020-07-31 20:07:59,038 [DEBUG] [spyder.api.panel] -> ClassFunctionDropdown visibility changed
2020-07-31 20:07:59,157 [INFO] [spyder.app.mainwindow] -> Loading outline explorer...
2020-07-31 20:07:59,203 [INFO] [spyder.app.mainwindow] -> Loading editor...
2020-07-31 20:07:59,314 [INFO] [spyder.app.mainwindow] -> Launching code completion client for Python...
2020-07-31 20:07:59,337 [DEBUG] [spyder.plugins.completion.kite.plugin] -> Kite was found on the system: C:\Program Files\Kite\kited.exe
2020-07-31 20:10:53,189 [DEBUG] [spyder.plugins.completion.kite.utils.status] -> Kite process already running with PID 16484
2020-07-31 20:10:53,189 [DEBUG] [spyder.plugins.completion.kite.client] -> Starting Kite HTTP session...
2020-07-31 20:10:53,196 [DEBUG] [urllib3.connectionpool] -> Starting new HTTP connection (1): 127.0.0.1:46624
2020-07-31 20:10:53,197 [DEBUG] [urllib3.connectionpool] -> http://127.0.0.1:46624 "GET /clientapi/languages HTTP/1.1" 200 16
2020-07-31 20:10:53,198 [DEBUG] [spyder.plugins.completion.kite.plugin] -> Kite client is available for ['go', 'python']
2020-07-31 20:10:53,201 [INFO] [spyder.plugins.completion.languageserver.plugin] -> Starting LSP client for python...
2020-07-31 20:10:53,222 [INFO] [spyder.plugins.completion.languageserver.client] -> Starting server: C:\Users\space\.conda\envs\spyder\python.exe -m pyls --host 127.0.0.1 --port 2088 --tcp --check-parent-process --log-file C:\Users\space\.spyder-py3\lsp_logs\server_python_1366068.log -vv

2020-07-31 20:10:55,007 [INFO] [spyder.app.mainwindow] -> Loading third-party plugins...
2020-07-31 20:10:55,050 [DEBUG] [urllib3.connectionpool] -> Starting new HTTP connection (1): 127.0.0.1:8071
2020-07-31 20:10:57,095 [INFO] [spyder.app.mainwindow] -> Setting up main window...

2020-07-31 20:11:00,755 [DEBUG] [spyder.plugins.completion.languageserver.client] -> Perform request textDocument/didOpen with id 3
2020-07-31 20:11:00,756 [DEBUG] [spyder.plugins.editor.widgets.codeeditor] -> Completion services available for: C:\Users\space\.conda\envs\spyder\lib\typing.py
2020-07-31 20:11:00,757 [DEBUG] [spyder.plugins.completion.kite.client] -> Perform request textDocument/didOpen with id 0
2020-07-31 20:11:00,757 [DEBUG] [spyder.plugins.completion.fallback.actor] -> Perform request textDocument/didOpen with id 0
2020-07-31 20:11:00,757 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Set focus to: C:\Users\space\.conda\envs\spyder\lib\typing.py
2020-07-31 20:11:00,759 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Current changed: 0 - C:\Users\space\.conda\envs\spyder\lib\typing.py
2020-07-31 20:11:00,762 [DEBUG] [urllib3.connectionpool] -> http://127.0.0.1:46624 "GET /clientapi/status?filename=C%3A%5CUsers%5Cspace%5C.conda%5Cenvs%5Cspyder%5Clib%5Ctyping.py HTTP/1.1" 200 121
2020-07-31 20:11:00,769 [DEBUG] [urllib3.connectionpool] -> http://127.0.0.1:46624 "POST /clientapi/editor/event HTTP/1.1" 200 0
2020-07-31 20:11:00,831 [DEBUG] [traitlets] -> Received history reply with 171 entries
2020-07-31 20:11:00,831 [DEBUG] [traitlets] -> handle_msg[79593ef5d38b11eaa2121005014b4f93]({'header': {'msg_id': 'cc34953b-8af5ac00fc94f9e925071b58_11', 'msg_type': 'comm_msg', 'username': 'username', 'session': 'cc34953b-8af5ac00fc94f9e925071b58', 'date': datetime.datetime(2020, 8, 1, 0, 10, 58, 889826, tzinfo=tzutc()), 'version': '5.3'}, 'msg_id': 'cc34953b-8af5ac00fc94f9e925071b58_11', 'msg_type': 'comm_msg', 'parent_header': {'msg_id': 'b49d991e-d6891421ad7f38f13664adc1_3', 'msg_type': 'comm_open', 'username': 'username', 'session': 'b49d991e-d6891421ad7f38f13664adc1', 'date': datetime.datetime(2020, 8, 1, 0, 10, 57, 802827, tzinfo=tzutc()), 'version': '5.3'}, 'metadata': {}, 'content': {'data': {'spyder_msg_type': 'remote_call', 'content': {'call_name': '_set_comm_port', 'call_id': '91af35b1f6fe45e38820cff893fd9bda', 'settings': {'blocking': False, 'timeout': None, 'send_reply': False}, 'comm_port': 61313, 'pickle_highest_protocol': 5}, 'pickle_protocol': 5, 'python_version': '3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)]'}, 'comm_id': '79593ef5d38b11eaa2121005014b4f93'}, 'buffers': [<memory at 0x0000021A37B397C0>]})
2020-07-31 20:11:00,833 [DEBUG] [traitlets] -> Connecting to: tcp://127.0.0.1:61313
2020-07-31 20:11:00,836 [DEBUG] [traitlets] -> handle_msg[79593ef5d38b11eaa2121005014b4f93]({'header': {'msg_id': 'cc34953b-8af5ac00fc94f9e925071b58_12', 'msg_type': 'comm_msg', 'username': 'username', 'session': 'cc34953b-8af5ac00fc94f9e925071b58', 'date': datetime.datetime(2020, 8, 1, 0, 10, 58, 889826, tzinfo=tzutc()), 'version': '5.3'}, 'msg_id': 'cc34953b-8af5ac00fc94f9e925071b58_12', 'msg_type': 'comm_msg', 'parent_header': {'msg_id': 'b49d991e-d6891421ad7f38f13664adc1_3', 'msg_type': 'comm_open', 'username': 'username', 'session': 'b49d991e-d6891421ad7f38f13664adc1', 'date': datetime.datetime(2020, 8, 1, 0, 10, 57, 802827, tzinfo=tzutc()), 'version': '5.3'}, 'metadata': {}, 'content': {'data': {'spyder_msg_type': 'remote_call', 'content': {'call_name': '_set_pickle_protocol', 'call_id': 'cbbc4d7dca8647d0bf1aab58486d4bf2', 'settings': {'blocking': False, 'timeout': None, 'send_reply': False}, 'comm_port': 61313, 'pickle_highest_protocol': 5}, 'pickle_protocol': 5, 'python_version': '3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)]'}, 'comm_id': '79593ef5d38b11eaa2121005014b4f93'}, 'buffers': [<memory at 0x0000021A2DE3B040>]})
2020-07-31 20:11:00,837 [DEBUG] [traitlets] -> handle_msg[79593ef5d38b11eaa2121005014b4f93]({'header': {'msg_id': 'cc34953b-8af5ac00fc94f9e925071b58_15', 'msg_type': 'comm_msg', 'username': 'username', 'session': 'cc34953b-8af5ac00fc94f9e925071b58', 'date': datetime.datetime(2020, 8, 1, 0, 10, 58, 891829, tzinfo=tzutc()), 'version': '5.3'}, 'msg_id': 'cc34953b-8af5ac00fc94f9e925071b58_15', 'msg_type': 'comm_msg', 'parent_header': {'msg_id': 'b49d991e-d6891421ad7f38f13664adc1_4', 'msg_type': 'comm_msg', 'username': 'username', 'session': 'b49d991e-d6891421ad7f38f13664adc1', 'date': datetime.datetime(2020, 8, 1, 0, 10, 57, 803828, tzinfo=tzutc()), 'version': '5.3'}, 'metadata': {}, 'content': {'data': {'spyder_msg_type': 'remote_call', 'content': {'call_name': '_set_comm_port', 'call_id': 'e552b76a537b479a9af16c6977682046', 'settings': {'blocking': False, 'timeout': None, 'send_reply': False}, 'comm_port': 61313, 'pickle_highest_protocol': 5}, 'pickle_protocol': 5, 'python_version': '3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)]'}, 'comm_id': '79593ef5d38b11eaa2121005014b4f93'}, 'buffers': [<memory at 0x0000021A2DE3B100>]})
2020-07-31 20:11:00,837 [DEBUG] [traitlets] -> handle_msg[79593ef5d38b11eaa2121005014b4f93]({'header': {'msg_id': 'cc34953b-8af5ac00fc94f9e925071b58_16', 'msg_type': 'comm_msg', 'username': 'username', 'session': 'cc34953b-8af5ac00fc94f9e925071b58', 'date': datetime.datetime(2020, 8, 1, 0, 10, 58, 891829, tzinfo=tzutc()), 'version': '5.3'}, 'msg_id': 'cc34953b-8af5ac00fc94f9e925071b58_16', 'msg_type': 'comm_msg', 'parent_header': {'msg_id': 'b49d991e-d6891421ad7f38f13664adc1_4', 'msg_type': 'comm_msg', 'username': 'username', 'session': 'b49d991e-d6891421ad7f38f13664adc1', 'date': datetime.datetime(2020, 8, 1, 0, 10, 57, 803828, tzinfo=tzutc()), 'version': '5.3'}, 'metadata': {}, 'content': {'data': {'spyder_msg_type': 'remote_call', 'content': {'call_name': '_set_pickle_protocol', 'call_id': '72e216984f4b4a06b9b88de6bacadb7b', 'settings': {'blocking': False, 'timeout': None, 'send_reply': False}, 'comm_port': 61313, 'pickle_highest_protocol': 5}, 'pickle_protocol': 5, 'python_version': '3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)]'}, 'comm_id': '79593ef5d38b11eaa2121005014b4f93'}, 'buffers': [<memory at 0x0000021A2DE3B1C0>]})
2020-07-31 20:11:00,839 [DEBUG] [traitlets] -> execute_reply: {'status': 'ok', 'execution_count': 0, 'user_expressions': {}, 'payload': []}
2020-07-31 20:11:00,847 [DEBUG] [urllib3.connectionpool] -> Starting new HTTP connection (1): 127.0.0.1:8071
2020-07-31 20:11:02,887 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 0 Got response from kite
2020-07-31 20:11:02,904 [DEBUG] [spyder.plugins.completion.languageserver.client] -> python response: textDocument/publishDiagnostics

2020-07-31 20:11:05,416 [DEBUG] [spyder.api.panel] -> LineNumberArea visibility changed
2020-07-31 20:11:05,420 [DEBUG] [spyder.api.panel] -> ClassFunctionDropdown visibility changed
2020-07-31 20:11:07,572 [DEBUG] [spyder.plugins.editor.plugin] -> Perform request textDocument/didOpen for: C:\Users\space\.conda\envs\spyder\lib\site-packages\PySimpleGUI\PySimpleGUI.py
2020-07-31 20:11:07,573 [DEBUG] [spyder.plugins.completion.languageserver.client] -> Perform request textDocument/didOpen with id 9
2020-07-31 20:11:07,576 [DEBUG] [spyder.plugins.editor.widgets.codeeditor] -> Completion services available for: C:\Users\space\.conda\envs\spyder\lib\site-packages\PySimpleGUI\PySimpleGUI.py
2020-07-31 20:11:07,576 [DEBUG] [spyder.plugins.completion.kite.client] -> Perform request textDocument/didOpen with id 6
2020-07-31 20:11:07,576 [DEBUG] [spyder.plugins.completion.fallback.actor] -> Perform request textDocument/didOpen with id 6
2020-07-31 20:11:07,582 [DEBUG] [urllib3.connectionpool] -> http://127.0.0.1:46624 "GET /clientapi/status?filename=C%3A%5CUsers%5Cspace%5C.conda%5Cenvs%5Cspyder%5Clib%5Csite-packages%5CPySimpleGUI%5CPySimpleGUI.py HTTP/1.1" 200 58
2020-07-31 20:11:07,602 [DEBUG] [urllib3.connectionpool] -> http://127.0.0.1:46624 "POST /clientapi/editor/event HTTP/1.1" 200 0
2020-07-31 20:11:07,713 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Updating queue:
2020-07-31 20:11:07,713 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     started: 0
2020-07-31 20:11:07,714 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     pending: 1
2020-07-31 20:11:07,715 [DEBUG] [spyder.plugins.editor.widgets.editor] -> ===>starting: <spyder.plugins.editor.widgets.editor.AnalysisThread object at 0x0000021A2DEBE430>
2020-07-31 20:11:07,720 [DEBUG] [urllib3.connectionpool] -> Starting new HTTP connection (1): 127.0.0.1:8071
2020-07-31 20:11:09,748 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 4 timed out
2020-07-31 20:11:09,748 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 5 timed out

2020-07-31 20:21:04,876 [DEBUG] [spyder.plugins.completion.kite.client] -> Perform request textDocument/hover with id 32
2020-07-31 20:21:04,877 [DEBUG] [spyder.plugins.completion.fallback.actor] -> Perform request textDocument/hover with id 32
2020-07-31 20:21:04,880 [DEBUG] [spyder.plugins.completion.kite.providers.document] -> C::Users:space:.conda:envs:spyder:lib:typing.py
2020-07-31 20:21:04,902 [DEBUG] [urllib3.connectionpool] -> http://127.0.0.1:46624 "GET /api/buffer/spyder/%3Awindows%3AC%3AUsers%3Aspace%3A.conda%3Aenvs%3Aspyder%3Alib%3Atyping.py/9420c0593f9ff685b7cf76bf43b3640c/hover?cursor_runes=102 HTTP/1.1" 200 0
2020-07-31 20:21:04,904 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 32 Got response from kite
2020-07-31 20:21:05,072 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 32 timed out
2020-07-31 20:21:05,382 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 32 Got response from lsp
2020-07-31 20:21:05,383 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 32 removed
2020-07-31 20:21:05,392 [DEBUG] [spyder.plugins.completion.plugin] -> Gather responses for textDocument/hover

USER : CTRIL-C

Handling signal: 0
Traceback (most recent call last):
  File "C:\Users\space\.conda\envs\spyder\lib\site-packages\spyder\widgets\dock.py", line 35, in eventFilter
    def eventFilter(self, obj, event):
KeyboardInterrupt
2020-07-31 20:21:17,892 [INFO] [spyder.plugins.completion.languageserver.plugin] -> Shutting down LSP manager...
2020-07-31 20:21:17,893 [INFO] [spyder.plugins.completion.languageserver.plugin] -> Stopping LSP client for python...
2020-07-31 20:21:17,893 [INFO] [spyder.plugins.completion.languageserver.client] -> Stopping python client...
2020-07-31 20:21:17,895 [DEBUG] [spyder.plugins.completion.kite.client] -> Closing Kite HTTP session...
2020-07-31 20:21:17,896 [DEBUG] [spyder.plugins.completion.fallback.actor] -> Fallback plugin stopping...

(spyder) C:\Users\space>

## Versions

* Spyder version: 4.1.4 
* Python version: 3.8.0
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)

# Spyder plugins:
spyder_terminal                :  0.4.0 (OK)
```

**Comment by GregOakes** [comment]
The error log file and terminal I/O:

[spyder_terminal_err.log](https://github.com/spyder-ide/spyder/files/5009673/spyder_terminal_err.log)

[spyder_terminal_output.txt](https://github.com/spyder-ide/spyder/files/5009679/spyder_terminal_output.txt)
