### ISSUE TITLE
Help! Who packed Spyder for Manjaro?

### ISSUE THREAD

**Issue by 1900011604** [spyder-ide/spyder#13488]
I have downloaded spyder from pacman (I don't use spyder from anaconda because it cannot open .py files simply by double clicking the file). But when I set the interpreter as anaconda python and installed ipython-kernel, it says that:

An error ocurred while starting the kernel
The error is:

Traceback (most recent call last):
File "/usr/lib/python3.8/site‑packages/spyder/plugins/ipythonconsole/plugin.py", line 1217, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "/usr/lib/python3.8/site‑packages/jupyter_client/manager.py", line 305, in start_kernel
self.kernel = self._launch_kernel(kernel_cmd, **kw)
File "/usr/lib/python3.8/site‑packages/jupyter_client/manager.py", line 212, in _launch_kernel
return launch_kernel(kernel_cmd, **kw)
File "/usr/lib/python3.8/site‑packages/jupyter_client/launcher.py", line 135, in launch_kernel
proc = Popen(cmd, **kwargs)
File "/usr/lib/python3.8/subprocess.py", line 854, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/site‑packages/spyder/plugins/ipythonconsole/scripts/conda‑activate.sh'

**Comment by jitseniesen** [comment]
@1900011604 As I understand it, Manjaro uses the package from Arch Linux, so use the information here: https://www.archlinux.org/packages/community/any/spyder/

Alternatively, ask for help at the Manjaro Linux Forum: https://forum.manjaro.org/

None of us here use Manjaro, so I am afraid we cannot help with those issues.

**Comment by 1900011604** [comment]
I asked at https://forum.manjaro.org/ but no one replied.
