### ISSUE TITLE
random error pop up

### ISSUE THREAD

**Issue by atom-45** [spyder-ide/spyder#13584]
### What steps will reproduce the problem?

If I click the close button, the error message pops up

### Traceback
```python-traceback
  File "/home/matome/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 4179, in mouseMoveEvent
    and not self.is_completion_widget_visible()):
  File "/home/matome/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/base.py", line 918, in is_completion_widget_visible
    return self.completion_widget.isVisible()
RuntimeError: wrapped C/C++ object of type CompletionWidget has been deleted
Traceback (most recent call last):
  File "/home/matome/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 653, in _handle_hover
    elif not self.is_completion_widget_visible():
  File "/home/matome/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/base.py", line 918, in is_completion_widget_visible
    return self.completion_widget.isVisible()
RuntimeError: wrapped C/C++ object of type CompletionWidget has been deleted
Traceback (most recent call last):
  File "/home/matome/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 4179, in mouseMoveEvent
    and not self.is_completion_widget_visible()):
  File "/home/matome/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/base.py", line 918, in is_completion_widget_visible
    return self.completion_widget.isVisible()
RuntimeError: wrapped C/C++ object of type CompletionWidget has been deleted
Traceback (most recent call last):
  File "/home/matome/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 4179, in mouseMoveEvent
    and not self.is_completion_widget_visible()):
  File "/home/matome/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/base.py", line 918, in is_completion_widget_visible
    return self.completion_widget.isVisible()RuntimeError: wrapped C/C++ object of type CompletionWidget has been deleted
Traceback (most recent call last):
  File "/home/matome/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 4210, in mousePressEvent
    self.kite_call_to_action.handle_mouse_press(event)
  File "/home/matome/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/kite/widgets/calltoaction.py", line 87, in handle_mouse_press
    self.hide()
RuntimeError: wrapped C/C++ object of type KiteCallToAction has been deleted
Traceback (most recent call last):
  File "/home/matome/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 4179, in mouseMoveEvent
    and not self.is_completion_widget_visible()):  File "/home/matome/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/base.py", line 918, in is_completion_widget_visible
    return self.completion_widget.isVisible()RuntimeError: wrapped C/C++ object of type CompletionWidget has been deleted
Traceback (most recent call last):
  File "/home/matome/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 653, in _handle_hover
    elif not self.is_completion_widget_visible():
  File "/home/matome/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/base.py", line 918, in is_completion_widget_visible
    return self.completion_widget.isVisible()
RuntimeError: wrapped C/C++ object of type CompletionWidget has been deleted
```

## Versions

* Spyder version: 4.0.0 
* Python version: 3.7.5
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 5.4.0-42-generic

### Dependencies

```
cloudpickle >=0.5.0          :  0.8.0 (OK)
pygments >=2.0               :  2.3.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.4.1 (OK)
sphinx >=0.6.6               :  1.8.5 (OK)
pylint >=0.25                :  2.3.1 (OK)
psutil >=0.3                 :  5.6.1 (OK)
qtawesome >=0.5.7            :  0.5.7 (OK)
qtpy >=1.5.0                 :  1.7.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.0.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.8.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.6.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.3 (OK)
cython >=0.21                :  0.29.6 (OK)
IPython >=4.0                :  7.4.0 (OK)
matplotlib >=2.0.0           :  3.0.3 (OK)
pandas >=0.13.1              :  0.24.2 (OK)
numpy >=1.7                  :  1.16.2 (OK)
scipy >=0.17.0               :  1.2.1 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
xdg >=0.26                   :  0.26 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by andfoy** [comment]
Hi @atom-45, thanks for opening this issue, it seems that you are using an old version of spyder, could you please try to update to 4.1.4 and see if the error have disappeared? You can execute the following commands to update Spyder:

```bash
conda update anaconda
conda install spyder=4.1.4
```

**Comment by andfoy** [comment]
I'm closing this issue because there wasn't a follow-up response after more than a week. If your error persists please re-open this issue and reply with the requested information.
Thanks for reporting!
