### ISSUE TITLE
OpenCV ORB problems

### ISSUE THREAD

**Issue by Chris6995** [spyder-ide/spyder#13594]
### What steps will reproduce the problem?

img = cv2.imread('anyImage.jpg')
# Initiate STAR detector
orb = cv2.ORB()

# find the keypoints with ORB
kp = orb.detect(img,None)

### Traceback
```python-traceback
  File "C:\Users\Christian\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Christian\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 181, in _handle_execute_reply
    super(NamepaceBrowserWidget, self)._handle_execute_reply(msg)
  File "C:\Users\Christian\anaconda3\lib\site-packages\qtconsole\jupyter_widget.py", line 194, in _handle_execute_reply
    super(JupyterWidget, self)._handle_execute_reply(msg)
  File "C:\Users\Christian\anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 449, in _handle_execute_reply
    self._request_info['execute'].pop(msg_id)
KeyError: 'a92261e9-1c65300a3c25463127795e57'
Traceback (most recent call last):
  File "C:\Users\Christian\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Christian\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 181, in _handle_execute_reply
    super(NamepaceBrowserWidget, self)._handle_execute_reply(msg)
  File "C:\Users\Christian\anaconda3\lib\site-packages\qtconsole\jupyter_widget.py", line 194, in _handle_execute_reply
    super(JupyterWidget, self)._handle_execute_reply(msg)
  File "C:\Users\Christian\anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 449, in _handle_execute_reply
    self._request_info['execute'].pop(msg_id)
KeyError: 'eb9ca50b-b1ae08be9fdf903c184aeb8b'
Traceback (most recent call last):
  File "C:\Users\Christian\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Christian\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 181, in _handle_execute_reply
    super(NamepaceBrowserWidget, self)._handle_execute_reply(msg)
  File "C:\Users\Christian\anaconda3\lib\site-packages\qtconsole\jupyter_widget.py", line 194, in _handle_execute_reply
    super(JupyterWidget, self)._handle_execute_reply(msg)
  File "C:\Users\Christian\anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 449, in _handle_execute_reply
    self._request_info['execute'].pop(msg_id)
KeyError: 'b775a0bb-e769cd205a7bb9c0615920ef'
Traceback (most recent call last):
  File "C:\Users\Christian\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Christian\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 181, in _handle_execute_reply
    super(NamepaceBrowserWidget, self)._handle_execute_reply(msg)
  File "C:\Users\Christian\anaconda3\lib\site-packages\qtconsole\jupyter_widget.py", line 194, in _handle_execute_reply
    super(JupyterWidget, self)._handle_execute_reply(msg)
  File "C:\Users\Christian\anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 449, in _handle_execute_reply
    self._request_info['execute'].pop(msg_id)
KeyError: '5504cc34-7d346645965d377bd3d6f795'
```

## Versions

* Spyder version: 4.1.3 
* Python version: 3.7.6
* Qt version: 5.12.8
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.12.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.7 (OK)
pygments >=2.0                 :  2.5.2 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.6.1 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.0 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.1 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by juanis2112** [comment]
Sure, no worries. We are glad we can help.
