### ISSUE TITLE
IPython console is missing

### ISSUE THREAD

**Issue by vighneshrajendrans** [spyder-ide/spyder#13614]
### What steps will reproduce the problem?

Ipython console is missing.Is there any corrections to do so

### Traceback
```python-traceback
  File "C:\Users\Vicky\anaconda3\envs\coastsat\lib\site-packages\IPython\core\history.py", line 87, in catch_corrupt_db
    return f(self, *a, **kw)
  File "C:\Users\Vicky\anaconda3\envs\coastsat\lib\site-packages\IPython\core\history.py", line 257, in init_db
    end timestamp, num_cmds integer, remark text)""")
sqlite3.DatabaseError: database disk image is malformed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vicky\anaconda3\envs\coastsat\lib\site-packages\spyder\plugins\base.py", line 327, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\Users\Vicky\anaconda3\envs\coastsat\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 211, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\Vicky\anaconda3\envs\coastsat\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 670, in create_new_client
    css_path=self.css_path)
  File "C:\Users\Vicky\anaconda3\envs\coastsat\lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 138, in __init__
    local_kernel=True)
  File "C:\Users\Vicky\anaconda3\envs\coastsat\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 79, in __init__
    super(ShellWidget, self).__init__(*args, **kw)
  File "C:\Users\Vicky\anaconda3\envs\coastsat\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 61, in __init__
    self._pdb_history_file = PdbHistory()
  File "C:\Users\Vicky\anaconda3\envs\coastsat\lib\site-packages\IPython\core\history.py", line 537, in __init__
    **traits)
  File "C:\Users\Vicky\anaconda3\envs\coastsat\lib\site-packages\IPython\core\history.py", line 229, in __init__
    self.init_db()
  File "<decorator-gen-16>", line 2, in init_db
  File "C:\Users\Vicky\anaconda3\envs\coastsat\lib\site-packages\IPython\core\history.py", line 113, in catch_corrupt_db
    os.rename(self.hist_file, newpath)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Vicky\\.spyder-py3\\pdb_history.sqlite' -> 'C:\\Users\\Vicky\\.spyder-py3\\pdb_history-corrupt-2020-08-24T12.01.54.300528.sqlite'
```

## Versions

* Spyder version: 4.1.3 
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.15.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.0.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.3 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.1 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.16.3 (OK)
pandas >=0.13.1                :  0.24.2 (OK)
scipy >=0.17.0                 :  1.2.1 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment]
@vighneshrajendrans, thanks for reporting. To try to solve this issue, please close Spyder, open your file explorer on Windows, go to this directory

    C:\Users\Vicky\.spyder-py3

and remove this file

    pdb_history.sqlite

**Comment by ccordoba12** [comment]
@impact27, any ideas on how we could address this error?

**Comment by impact27** [comment]
Is there any other program using this file on your computer to your knowledge?
We could catch this error and inform the user to manually remove the file?

**Comment by ccordoba12** [comment]
> Is there any other program using this file on your computer to your knowledge?

This is a good point. Do all Spyder instances use the same `pdb_history.sqlite` to save Pdb command history?

> We could catch this error and inform the user to manually remove the file?

That's a good idea. But why do you think we haven't received an error report like this for IPython consoles before? Is IPython handling differently its own history database?

**Comment by ccordoba12** [comment]
Closing because we haven't seen other errors like this one.
