### ISSUE TITLE
Can  anyone  help me to to fix  this problem?

### ISSUE THREAD

**Issue by jkinya** [spyder-ide/spyder#13652]
An error ocurred while starting the kernel
Traceback (most recent call last):
File "C:\Users\ABDUL JALEEL\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\ABDUL JALEEL\anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\ABDUL JALEEL\anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 23, in 
start.main()
File "C:\Users\ABDUL JALEEL\anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 289, in main
import_spydercustomize()
File "C:\Users\ABDUL JALEEL\anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 39, in import_spydercustomize
import spydercustomize
File "C:\Users\ABDUL JALEEL\anaconda3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 17, in 
import pdb
File "C:\Users\ABDUL JALEEL\anaconda3\lib\pdb.py", line 73, in 
import cmd
File "C:\Users\ABDUL JALEEL\anaconda3\lib\cmd.py", line 50, in 
IDENTCHARS = string.ascii_letters + string.digits + '_'
AttributeError: module 'string' has no attribute 'ascii_letters'

**Comment by juanis2112** [comment]
@jkinya thanks for reporting this. Can you check if you created a file called "string.py" in your home directory, your project directory or your working directory? If that's the case, you need to change the name because there is a standard library module that has the same name.

**Comment by jkinya** [comment]
@juanis2112   just now i installed anaconda,  while opening spyder it showing the error above i posted

**Comment by juanis2112** [comment]
Yeah, but if you created this file (even if it was before the installation) it can conflict with spyder. Take a look at https://docs.spyder-ide.org/current/common-illnesses.html#attributeerror-importerror

**Comment by jkinya** [comment]
@juanis2112 I had created a string.py  for pycharm project,  now i  changed a file name
so  my problem  is solved.
Thank you .

**Comment by juanis2112** [comment]
You're welcome. I'm glad you solved it!
