### ISSUE TITLE
Unable to open Preferences dialog with v2.2rc

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1368]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-04-28T13:25:46Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. Click on "Preferences" dialog action (menu or toolbar) What is the expected output? What do you see instead? The following traceback is shown in the internal console
The "Preferences" dialog box is not shown.

Traceback (most recent call last):
  File "D:\Python\spyder\spyderlib\spyder.py", line 1787, in edit_preferences
    widget = plugin.create_configwidget(dlg)
  File "D:\Python\spyder\spyderlib\plugins\__init__.py", line 160, in create_configwidget
    configwidget.initialize()
  File "D:\Python\spyder\spyderlib\plugins\configdialog.py", line 58, in initialize
    self.setup_page()
  File "D:\Python\spyder\spyderlib\plugins\externalconsole.py", line 285, in setup_page
    interpreter=interpreter)
  File "D:\Python\spyder\spyderlib\utils\programs.py", line 251, in is_module_installed
    os.remove(script)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\pierre\\appdata\\local\\temp\\tmpwh701a.py'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1368_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-04-28T11:37:27Z_

We've been discussing with Jed how to fix this error on issue #1365 and revision cdfffc004036 .

I'll try to push my proposed solution later today.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-04-30T10:59:21Z_

**Status:** Duplicate  
  **Mergedinto:** 1365
