### ISSUE TITLE
IPython.core.inputtransformer2 is only present in IPython >= 7.0

### ISSUE THREAD

**Issue by algent-al** [spyder-ide/spyder#13719]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am using spyder3 installing it system wide. Made a test by installing python-ipython version 6.5.0 and run into this issue.

```
$ spyder3
Traceback (most recent call last):
  File "/usr/bin/spyder3", line 3, in <module>
    start.main()
  File "/usr/lib/python3.7/site-packages/spyder/app/start.py", line 204, in main
    mainwindow.main()
  File "/usr/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3763, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3638, in run_spyder
    main.setup()
  File "/usr/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 945, in setup
    from spyder.plugins.ipythonconsole.plugin import IPythonConsole
  File "/usr/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 46, in <module>
    from spyder.plugins.ipythonconsole.widgets import (ClientWidget,
  File "/usr/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/widgets/__init__.py", line 16, in <module>
    from .debugging import DebuggingWidget
  File "/usr/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/widgets/debugging.py", line 22, in <module>
    from IPython.core.inputtransformer2 import TransformerManager
ModuleNotFoundError: No module named 'IPython.core.inputtransformer2'
```
This module 'IPython.core.inputtransformer2' is present in IPython version 7 series, and spyder 4.x need it.

**Comment by ccordoba12** [comment]
Hey @algent-al, thanks for reporting. We do support older IPython versions, but we are not importing that module correctly. We'll fix that in our next version.
