### ISSUE TITLE
I am unable to open Anaconda navigator. conda info also get me error.

### ISSUE THREAD

**Issue by akshaye1** [spyder-ide/spyder#13730]
(base) C:\Users\HP>conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\HP\anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\Users\HP\anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\HP\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "C:\Users\HP\anaconda3\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "C:\Users\HP\anaconda3\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "C:\Users\HP\anaconda3\lib\site-packages\conda\core\index.py", line 10, in <module>
        from .package_cache_data import PackageCacheData
      File "C:\Users\HP\anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
        from .path_actions import CacheUrlAction, ExtractPackageAction
      File "C:\Users\HP\anaconda3\lib\site-packages\conda\core\path_actions.py", line 30, in <module>
        from ..gateways.connection.download import download
      File "C:\Users\HP\anaconda3\lib\site-packages\conda\gateways\connection\__init__.py", line 21, in <module>
        from requests import ConnectionError, HTTPError, Session
      File "C:\Users\HP\anaconda3\lib\site-packages\requests\__init__.py", line 120, in <module>
        from . import utils
      File "C:\Users\HP\anaconda3\lib\site-packages\requests\utils.py", line 27, in <module>
        from ._internal_utils import to_native_string
      File "C:\Users\HP\anaconda3\lib\site-packages\requests\_internal_utils.py", line 11, in <module>
        from .compat import is_py2, builtin_str, str
      File "C:\Users\HP\anaconda3\lib\site-packages\requests\compat.py", line 61, in <module>
        from http.cookies import Morsel
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 779, in exec_module
      File "<frozen importlib._bootstrap_external>", line 915, in get_code
      File "<frozen importlib._bootstrap_external>", line 973, in get_data
    OSError: [Errno 9] Bad file descriptor

`$ C:\Users\HP\anaconda3\Scripts\conda-script.py info`

An unexpected error has occurred. Conda has prepared the above report.

**Comment by ccordoba12** [comment]
Hey @akshaye1, thanks for reporting. Unfortunately, this is not an error with Spyder but with conda.

Since it seems pretty serious, our only recommendation is to remove and reinstall Anaconda again. Please see our video to learn how to do that

https://www.youtube.com/watch?v=Ul79ihg41Rs

If the problem persists, please report it here

https://github.com/ContinuumIO/anaconda-issues
