### ISSUE TITLE
IPython 1.0dev is giving "ImportError: No module named kernelmanager"

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1374]
_From [tim.mich...@gmail.com](https://code.google.com/u/117399810383525443135/) on 2013-04-30T14:59:02Z_

spyder
Traceback (most recent call last):
  File "/usr/bin/spyder", line 3, in \<module>
    start_app.main()
  File "/usr/lib/python2.7/dist-packages/spyderlib/start_app.py", line 64, in main
    from spyderlib import spyder
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 107, in \<module>
    from spyderlib.plugins.ipythonconsole import IPythonConsole
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/ipythonconsole.py", line 31, in \<module>
    from IPython.frontend.qt.kernelmanager import QtKernelManager
ImportError: No module named kernelmanager

\## versions

dpkg -l |grep spyder
ii  python-spyderlib                                            2.2.0~ppa4~revno-2130~raring1                all          python IDE for scientists
ii  spyder                                                      2.2.0~ppa4~revno-2130~raring1                all          python IDE for scientists

\## ipython
dpkg -l |grep ipython
ii  ipython                                                     0.13.2+3140-0~41~raring1                     all          enhanced interactive Python shell
ii  ipython-doc                                                 0.13.2+3140-0~41~raring1                     all          enhanced interactive Python shell - Documentation
ii  ipython-notebook                                            0.13.2+3140-0~41~raring1                     all          interactive Python html notebook
ii  ipython-notebook-common                                     0.13.2+3140-0~41~raring1                     all          interactive Python html notebook data package
ii  ipython-qtconsole                                           0.13.2+3140-0~41~raring1                     all          enhanced interactive Python shell - Qt console

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1374_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-04-30T14:17:35Z_

This is due to a recent PR in the IPython side that breaks compatibility with 0.13. 

It's going to be fixed in our side in 2.3 because it's not possible to make 0.13 and 1.0 work within the same codebase.

**Labels:** MS-v2.3 Cat-IPythonConsole

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-04-30T14:18:35Z_

**Summary:** IPython 1.0dev is giving "ImportError: No module named kernelmanager"  \<span class="oldvalue"> (was: ImportError: No module named kernelmanager) \</span>  
  **Owner:** ccordoba12

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-05-01T05:29:03Z_

As I understand:
Spyder 2.2 will support IPython 0.13 (0.13, 0.13.1, 0.13.2)
Spyder 2.3 will support IPython >=1.0

This should be written somewhere.

In the meantime, I've handled this error due to the fact that IPython 1.0 is not yet supported: see revision eef2db1f35a5 .

**Status:** Started

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-05-01T06:30:56Z_

These two pages on the IPython Github site describe the source of the incompatibility with IPython 1.0. Spyder is not yet ready to handle the splitting of KernelClient from KernelManager and the new kernel/client pattern this requires. https://github.com/ipython/ipython/wiki/IPEP-12%3A-Splitting-KernelManager-and-KernelClient https://github.com/ipython/ipython/pull/3011

**Comment by spyder-issues-migrator** [comment]
_From [tim.mich...@gmail.com](https://code.google.com/u/117399810383525443135/) on 2013-05-01T13:28:08Z_

The commit https://code.google.com/p/spyderlib/source/detail?r=eef2db1f35a5582c50b8b6258666c9c577c774b0 was tested.

the program did not start:

spyder
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 2086, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 1991, in run_spyder
    main.post_visible_setup()
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 1029, in post_visible_setup
    self.extconsole.open_interpreter_at_startup()
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/externalconsole.py", line 1141, in open_interpreter_at_startup
    self.start_ipykernel()
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/externalconsole.py", line 1168, in start_ipykernel
    self.main.ipyconsole.visibility_changed(True)
AttributeError: 'NoneType' object has no attribute 'visibility_changed'

after a spyder --reset:

the program started, but no IPython console is available.

I use Ubuntu 13.04, 

ipython --version
1.0.dev

(from IPython PPA: https://launchpad.net/~jtaylor/+archive/ipython-dev )

after downgrading to

ipython --version
0.13.2
 (ordinary Ubuntu package)

I get the IPython console!!!
THX Pierre.

So I guess the issue can be closed for V.2.2

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-05-02T01:45:01Z_

This issue was updated by revision 1ebc50c40bca .


Fixes bug reported in comment `#5`.

**Status:** Fixed
