### ISSUE TITLE
IPython console throw an error: "An error ocurred while starting the kernel"

### ISSUE THREAD

**Issue by amedinae** [spyder-ide/spyder#13782]
I have an error similar to [10400](https://github.com/spyder-ide/spyder/issues/10400), but any of the solutions showed there works for me. My spyder version is 4.1.5 and the error is:

Traceback (most recent call last):
File "D:\Programas\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole\plugin.py", line 1223, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\Andres Medina\AppData\Roaming\Python\Python38\site‑packages\jupyter_client\manager.py", line 301, in start_kernel
kernel_cmd, kw = self.pre_start_kernel(**kw)
File "C:\Users\Andres Medina\AppData\Roaming\Python\Python38\site‑packages\jupyter_client\manager.py", line 248, in pre_start_kernel
self.write_connection_file()
File "C:\Users\Andres Medina\AppData\Roaming\Python\Python38\site‑packages\jupyter_client\connect.py", line 468, in write_connection_file
self.connection_file, cfg = write_connection_file(self.connection_file,
File "C:\Users\Andres Medina\AppData\Roaming\Python\Python38\site‑packages\jupyter_client\connect.py", line 138, in write_connection_file
with secure_write(fname) as f:
File "D:\Programas\Anaconda3\lib\contextlib.py", line 113, in __enter__
return next(self.gen)
File "C:\Users\Andres Medina\AppData\Roaming\Python\Python38\site‑packages\jupyter_core\paths.py", line 435, in secure_write
win32_restrict_file_to_user(fname)
File "C:\Users\Andres Medina\AppData\Roaming\Python\Python38\site‑packages\jupyter_core\paths.py", line 361, in win32_restrict_file_to_user
import win32api
ImportError: DLL load failed while importing win32api: %1 no es una aplicación Win32 válida.

The solution is to open the Anaconda prompt and run there

    conda update --all

_Originally posted by @ccordoba12 in https://github.com/spyder-ide/spyder/issues/10400#issuecomment-554366717_

**Comment by ccordoba12** [comment]
Hey @amedinae, thanks for reporting. Please remove this directory:

    C:\Users\Andres Medina\AppData\Roaming\Python

and try again. That should fix your problem.

**Comment by amedinae** [comment]
Muchas gracias!!!, Tenia semanas estancado con eso. Pense que habia eliminado totalmente mi anterior instalación de python pero como que se me paso esa carpeta.

**Comment by ccordoba12** [comment]
Me alegra que hayas podido resolver tu problema. Si tienes más problemas de ese tipo en el futuro, te recomendamos ver nuestro video al respecto:

https://www.youtube.com/watch?v=Ul79ihg41Rs
