### ISSUE TITLE
no qt bindings could be found

### ISSUE THREAD

**Issue by avp1510** [spyder-ide/spyder#13797]
C:\Users\91988>anaconda-navigator
Traceback (most recent call last):
  File "D:\user\lib\site-packages\qtpy\__init__.py", line 204, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\user\Scripts\anaconda-navigator-script.py", line 6, in <module>
    from anaconda_navigator.app.main import main
  File "D:\user\lib\site-packages\anaconda_navigator\app\main.py", line 22, in <module>
    from anaconda_navigator.utils.conda import is_conda_available
  File "D:\user\lib\site-packages\anaconda_navigator\utils\__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "D:\user\lib\site-packages\qtpy\__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

please tell what to do as my anaconda navigator and pycharm is not working.....

**Comment by dalthviz** [comment]
Hi @avp1510 seems like you have some installation issues but those are unrelated with Spyder (seems like you are running Anaconda Navigator and trying to use PyCharm?). Probably your environment got corrupted so a clean install of Anaconda could help also check if you have `pyqt` installed.

Since this is unrelated with Spyder I'm closing it but hopefully the info above could help you :)
