### ISSUE TITLE
Right Click on Variable Name

### ISSUE THREAD

**Issue by jeremywood-ai** [spyder-ide/spyder#13794]
### What steps will reproduce the problem?

`Right-click` on *Variable Explorer* --> *Name* resulted in an internal problem. 

Steps:

1. Went to `Options`
2. Turned off `Exclude Private References`
3. Realized I didn't want that --> Turned on `Exclude Private References`
4. `_` is the first entry in the *Name* column, `right-clicked` and errored.

### Traceback
```python-traceback
  File "D:\Anaconda3\envs\tf_gpu\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 794, in contextMenuEvent
    self.refresh_menu()
  File "D:\Anaconda3\envs\tf_gpu\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 707, in refresh_menu
    self.refresh_plot_entries(index)
  File "D:\Anaconda3\envs\tf_gpu\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 715, in refresh_plot_entries
    is_list = self.is_list(key)
  File "D:\Anaconda3\envs\tf_gpu\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 1475, in is_list
    return self.var_properties[name]['is_list']
KeyError: '_'
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tf_gpu\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 794, in contextMenuEvent
    self.refresh_menu()
  File "D:\Anaconda3\envs\tf_gpu\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 707, in refresh_menu
    self.refresh_plot_entries(index)
  File "D:\Anaconda3\envs\tf_gpu\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 715, in refresh_plot_entries
    is_list = self.is_list(key)
  File "D:\Anaconda3\envs\tf_gpu\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 1475, in is_list
    return self.var_properties[name]['is_list']
KeyError: '___'
```

## Versions

* Spyder version: 4.1.5 
* Python version: 3.7.8
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.3.1 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.3.1 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by dalthviz** [comment]
Hi @jeremywood-ai for the feedback, I was able to reproduce this! For now, as a workaround, you can trigger manually a refresh of the Variable Explorer using the refresh button. We will be checking this for a future release :+1: 

Any new info or a way to fix this is greatly appreciated :)
