### ISSUE TITLE
Trouble restarting kernel

### ISSUE THREAD

**Issue by blyles2** [spyder-ide/spyder#13795]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by blyles2** [comment]
An error ocurred while starting the kernel
Traceback (most recent call last):
File "C:\Users\brian\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\brian\anaconda3\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Users\brian\anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 23, in 
start.main()
File "C:\Users\brian\anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 299, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\brian\anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 40, in 
from .ipkernel import IPythonKernel
File "C:\Users\brian\anaconda3\lib\site‑packages\ipykernel\ipkernel.py", line 16, in 
from .comm import CommManager
File "C:\Users\brian\anaconda3\lib\site‑packages\ipykernel\comm\__init__.py", line 1, in 
from .manager import *
File "C:\Users\brian\anaconda3\lib\site‑packages\ipykernel\comm\manager.py", line 15, in 
from .comm import Comm
File "C:\Users\brian\anaconda3\lib\site‑packages\ipykernel\comm\comm.py", line 9, in 
from ipykernel.kernelbase import Kernel
File "C:\Users\brian\anaconda3\lib\site‑packages\ipykernel\kernelbase.py", line 123
will be cancelled.
^
SyntaxError: EOF while scanning triple‑quoted string literal

**Comment by dalthviz** [comment]
Hi @blyles2 could you provide a description of the circumstances where the error happens? Maybe a way step by step to reproduce this as well as the OS you are working, Spyder and Python versions and dependencies version you have in your installation?

Without more information we can't help you. Please check our [Basic first aid guide](https://docs.spyder-ide.org/current/basic-first-aid.html) to see if something there helps :)

**Comment by blyles2** [comment]
I was saving a program I completed for a class, and as I was trying to restart the kernel, an error occurred. I have python installed on my surface pro, Windows 10 Home. I can't run a program now due to the error that happened and I'm not sure how to fix it.

Best,

Brianna
________________________________

**Comment by dalthviz** [comment]
Hi @blyles2 maybe try resetting your preferences to default values (`Tools > Reset Spyder to factory defaults`) and be sure that you are using the latest Spyder available (version 4.1.5). Also, maybe your code ended up with some syntax error? (seems like a triple quoted string literal is causing the issue), something like leaving `"""` without closing the triple quotes.

Without more info to be able to replicate the issue in our side there isn't much more that we can do, sorry.

**Comment by dalthviz** [comment]
Closing this one since no reply was done after a week. I hope that the info above was useful enough
