### ISSUE TITLE
SVM Parameter Optimization Error

### ISSUE THREAD

**Issue by gorkagl** [spyder-ide/spyder#13809]
### What steps will reproduce the problem?

IPython 7.13.0 -- An enhanced Interactive Python.

Restarting kernel... 

 Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Gorka\anaconda3\envs\deeplearning\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Geophysics\Python\SYNAPSE-1D\MPT_Main.py", line 2324, in func_SVM
    n_scores_svm = cross_val_score(svm, X1, y1, scoring='neg_mean_absolute_error', cv=cv_svm, n_jobs=-1, error_score='raise')
  File "C:\Users\Gorka\anaconda3\envs\deeplearning\lib\site-packages\sklearn\model_selection\_validation.py", line 390, in cross_val_score
    error_score=error_score)
  File "C:\Users\Gorka\anaconda3\envs\deeplearning\lib\site-packages\sklearn\model_selection\_validation.py", line 236, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "C:\Users\Gorka\anaconda3\envs\deeplearning\lib\site-packages\joblib\parallel.py", line 1017, in __call__
    self.retrieve()
  File "C:\Users\Gorka\anaconda3\envs\deeplearning\lib\site-packages\joblib\parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Users\Gorka\anaconda3\envs\deeplearning\lib\site-packages\joblib\_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Users\Gorka\anaconda3\envs\deeplearning\lib\concurrent\futures\_base.py", line 435, in result
    return self.__get_result()
  File "C:\Users\Gorka\anaconda3\envs\deeplearning\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

### Traceback
```python-traceback
  File "C:\Users\Gorka\anaconda3\envs\deeplearning\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Gorka\anaconda3\envs\deeplearning\lib\site-packages\psutil\_pswindows.py", line 868, in send_signal
    cext.proc_kill(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Gorka\anaconda3\envs\deeplearning\lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 578, in _restart_thread_main
    stderr=self.stderr_handle)
  File "C:\Users\Gorka\anaconda3\envs\deeplearning\lib\site-packages\jupyter_client\manager.py", line 411, in restart_kernel
    self.shutdown_kernel(now=now, restart=True)
  File "C:\Users\Gorka\anaconda3\envs\deeplearning\lib\site-packages\jupyter_client\manager.py", line 377, in shutdown_kernel
    self.finish_shutdown()
  File "C:\Users\Gorka\anaconda3\envs\deeplearning\lib\site-packages\jupyter_client\manager.py", line 338, in finish_shutdown
    self._kill_kernel()
  File "C:\Users\Gorka\anaconda3\envs\deeplearning\lib\site-packages\spyder\plugins\ipythonconsole\utils\manager.py", line 86, in _kill_kernel
    self.kill_proc_tree(self.kernel.pid)
  File "C:\Users\Gorka\anaconda3\envs\deeplearning\lib\site-packages\spyder\plugins\ipythonconsole\utils\manager.py", line 59, in kill_proc_tree
    child_process.send_signal(sig)
  File "C:\Users\Gorka\anaconda3\envs\deeplearning\lib\site-packages\psutil\__init__.py", line 292, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Gorka\anaconda3\envs\deeplearning\lib\site-packages\psutil\__init__.py", line 1214, in send_signal
    self._proc.send_signal(sig)
  File "C:\Users\Gorka\anaconda3\envs\deeplearning\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=7204)
```

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
@gorkagl, thanks for reporting. This could be fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda update anaconda
    conda install spyder=4.1.5

**Comment by gorkagl** [comment]
Thank you, Carlos.

**Comment by ccordoba12** [comment]
Was the problem fixed? Please let us know to see if we can close this issue.

**Comment by gorkagl** [comment]
Yes. Please close the ticket.

 

Cheers,
Gorka
