### ISSUE TITLE
Spyder 2.2.0 fails on launch on OS X 10.7.5

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1383]
_From [lancebo...@qwest.net](https://code.google.com/u/115604211761405613769/) on 2013-05-09T04:17:10Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. Launch Spyder 2.2.0 installed from .dmg into /Applications 2. 3. What is the expected output? What do you see instead? Dialog box offering to Open Console or Terminate What version of the product are you using? On what operating system? Spyder 2.2.0, downloaded and installed official .dmg. OS X 10.7.5 

Please provide any additional information below

. Console log for one cycle of launch/crash:

5/9/13 2:11:54.701 AM [0x0-0xe8be8b].org.spyder-ide: Traceback (most recent call last):
5/9/13 2:11:54.701 AM [0x0-0xe8be8b].org.spyder-ide:   File "/Applications/Spyder.app/Contents/Resources/__boot__.py", line 19, in \<module>
5/9/13 2:11:54.702 AM [0x0-0xe8be8b].org.spyder-ide:     _get_env()
5/9/13 2:11:54.702 AM [0x0-0xe8be8b].org.spyder-ide:   File "/Applications/Spyder.app/Contents/Resources/__boot__.py", line 18, in _get_env
5/9/13 2:11:54.702 AM [0x0-0xe8be8b].org.spyder-ide:     os.environ.update(env)
5/9/13 2:11:54.702 AM [0x0-0xe8be8b].org.spyder-ide:   File "os.pyc", line 479, in update
5/9/13 2:11:54.702 AM [0x0-0xe8be8b].org.spyder-ide: ValueError: need more than 1 value to unpack
5/9/13 2:11:54.786 AM Spyder: Spyder Error
5/9/13 2:11:59.393 AM com.apple.launchd.peruser.501: ([0x0-0xe8be8b].org.spyder-ide[50500]) Exited with code: 255

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1383_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-12-30T15:58:25Z_

This was already fixed several versions ago.

**Status:** Duplicate  
  **Mergedinto:** 1359
