### ISSUE TITLE
1

### ISSUE THREAD

**Issue by orangebaby5200** [spyder-ide/spyder#13835]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\Anaconda\envs\tensorflow-gpu\lib\site-packages\pkg_resources\__init__.py", line 3041, in _dep_map
    return self.__dep_map
  File "D:\Anaconda\envs\tensorflow-gpu\lib\site-packages\pkg_resources\__init__.py", line 2835, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

Traceback (most recent call last):
  File "D:\Anaconda\envs\tensorflow-gpu\lib\site-packages\pkg_resources\__init__.py", line 3032, in _parsed_pkg_info
    return self._pkg_info
  File "D:\Anaconda\envs\tensorflow-gpu\lib\site-packages\pkg_resources\__init__.py", line 2835, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

Traceback (most recent call last):
  File "D:\Anaconda\envs\tensorflow-gpu\lib\site-packages\spyder\plugins\editor.py", line 1840, in load
    self.edit_filetypes = get_edit_filetypes()
  File "D:\Anaconda\envs\tensorflow-gpu\lib\site-packages\spyder\config\utils.py", line 119, in get_edit_filetypes
    pygments_exts = _get_pygments_extensions()
  File "D:\Anaconda\envs\tensorflow-gpu\lib\site-packages\spyder\config\utils.py", line 86, in _get_pygments_extensions
    for lx in lexers.get_all_lexers():
  File "D:\Anaconda\envs\tensorflow-gpu\lib\site-packages\pygments\lexers\__init__.py", line 57, in get_all_lexers
    for lexer in find_plugin_lexers():
  File "D:\Anaconda\envs\tensorflow-gpu\lib\site-packages\pygments\plugin.py", line 55, in find_plugin_lexers
    yield entrypoint.load()
  File "D:\Anaconda\envs\tensorflow-gpu\lib\site-packages\pkg_resources\__init__.py", line 2471, in load
    self.require(*args, **kwargs)
  File "D:\Anaconda\envs\tensorflow-gpu\lib\site-packages\pkg_resources\__init__.py", line 2494, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "D:\Anaconda\envs\tensorflow-gpu\lib\site-packages\pkg_resources\__init__.py", line 793, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "D:\Anaconda\envs\tensorflow-gpu\lib\site-packages\pkg_resources\__init__.py", line 2756, in requires
    dm = self._dep_map
  File "D:\Anaconda\envs\tensorflow-gpu\lib\site-packages\pkg_resources\__init__.py", line 3043, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "D:\Anaconda\envs\tensorflow-gpu\lib\site-packages\pkg_resources\__init__.py", line 3052, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "D:\Anaconda\envs\tensorflow-gpu\lib\site-packages\pkg_resources\__init__.py", line 3034, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "D:\Anaconda\envs\tensorflow-gpu\lib\site-packages\pkg_resources\__init__.py", line 1420, in get_metadata
    value = self._get(path)
  File "D:\Anaconda\envs\tensorflow-gpu\lib\site-packages\pkg_resources\__init__.py", line 1626, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'd:\\anaconda\\envs\\tensorflow-gpu\\lib\\site-packages\\parso-0.7.0.dist-info\\METADATA'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.10
* Qt Versions: 5.9.6, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  2.2.0 (OK)
pycodestyle >=2.3:  2.6.0 (OK)
pygments >=2.0   :  2.6.1 (OK)
pandas >=0.13.1  :  1.1.1 (OK)
numpy >=1.7      :  1.19.1 (OK)
sphinx >=0.6.6   :  3.2.1 (OK)
rope >=0.9.4     :  0.17.0 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.6.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.7.5 (OK)
IPython >=4.0    :  7.16.1 (OK)
pylint >=0.25    :  2.5.3 (OK)

```

**Comment by steff456** [comment]
Hi @orangebaby5200,

Can you please give us information of how this error occurred?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
