### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by git-pawan-tripathi** [spyder-ide/spyder#13929]
### What steps will reproduce the problem?

An error ocurred while starting the kernel
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/home/pawan/.local/lib/python3.8/site‑packages/spyder_kernels/console/__main__.py", line 23, in 
start.main()
File "/home/pawan/.local/lib/python3.8/site‑packages/spyder_kernels/console/start.py", line 289, in main
import_spydercustomize()
File "/home/pawan/.local/lib/python3.8/site‑packages/spyder_kernels/console/start.py", line 39, in import_spydercustomize
import spydercustomize
File "/home/pawan/.local/lib/python3.8/site‑packages/spyder_kernels/customize/spydercustomize.py", line 24, in 
from IPython.core.getipython import get_ipython
File "/usr/lib/python3/dist‑packages/IPython/__init__.py", line 56, in 
from .terminal.embed import embed
File "/usr/lib/python3/dist‑packages/IPython/terminal/embed.py", line 14, in 
from IPython.core.magic import Magics, magics_class, line_magic
File "/usr/lib/python3/dist‑packages/IPython/core/magic.py", line 20, in 
from . import oinspect
File "/usr/lib/python3/dist‑packages/IPython/core/oinspect.py", line 30, in 
from IPython.lib.pretty import pretty
File "/usr/lib/python3/dist‑packages/IPython/lib/pretty.py", line 82, in 
import datetime
File "/home/pawan/my py pro/datetime.py", line 10, in 
from datetime import datetime
ImportError: cannot import name 'datetime' from partially initialized module 'datetime' (most likely due to a circular import) (/home/pawan/my py pro/datetime.py)
Error in sys.excepthook:
Traceback (most recent call last):
File "/usr/lib/python3/dist‑packages/apport_python_hook.py", line 72, in apport_excepthook
from apport.fileutils import likely_packaged, get_recent_crashes
File "/usr/lib/python3/dist‑packages/apport/__init__.py", line 5, in 
from apport.report import Report
File "/usr/lib/python3/dist‑packages/apport/report.py", line 21, in 
from urllib.request import urlopen
File "/usr/lib/python3.8/urllib/request.py", line 88, in 
import http.client
File "/usr/lib/python3.8/http/client.py", line 71, in 
import email.parser
File "/usr/lib/python3.8/email/parser.py", line 12, in 
from email.feedparser import FeedParser, BytesFeedParser
File "/usr/lib/python3.8/email/feedparser.py", line 27, in 
from email._policybase import compat32
File "/usr/lib/python3.8/email/_policybase.py", line 9, in 
from email.utils import _has_surrogates
File "/usr/lib/python3.8/email/utils.py", line 30, in 
import datetime
File "/home/pawan/my py pro/datetime.py", line 10, in 
from datetime import datetime
ImportError: cannot import name 'datetime' from partially initialized module 'datetime' (most likely due to a circular import) (/home/pawan/my py pro/datetime.py)

Original exception was:
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/home/pawan/.local/lib/python3.8/site‑packages/spyder_kernels/console/__main__.py", line 23, in 
start.main()
File "/home/pawan/.local/lib/python3.8/site‑packages/spyder_kernels/console/start.py", line 289, in main
import_spydercustomize()
File "/home/pawan/.local/lib/python3.8/site‑packages/spyder_kernels/console/start.py", line 39, in import_spydercustomize
import spydercustomize
File "/home/pawan/.local/lib/python3.8/site‑packages/spyder_kernels/customize/spydercustomize.py", line 24, in 
from IPython.core.getipython import get_ipython
File "/usr/lib/python3/dist‑packages/IPython/__init__.py", line 56, in 
from .terminal.embed import embed
File "/usr/lib/python3/dist‑packages/IPython/terminal/embed.py", line 14, in 
from IPython.core.magic import Magics, magics_class, line_magic
File "/usr/lib/python3/dist‑packages/IPython/core/magic.py", line 20, in 
from . import oinspect
File "/usr/lib/python3/dist‑packages/IPython/core/oinspect.py", line 30, in 
from IPython.lib.pretty import pretty
File "/usr/lib/python3/dist‑packages/IPython/lib/pretty.py", line 82, in 
import datetime
File "/home/pawan/my py pro/datetime.py", line 10, in 
from datetime import datetime
ImportError: cannot import name 'datetime' from partially initialized module 'datetime' (most likely due to a circular import) (/home/pawan/my py pro/datetime.py)

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.2
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Linux 5.4.0-48-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.7.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.6.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.5.1 (OK)
pygments >=2.0                 :  2.3.1 (OK)
pylint >=1.0                   :  2.4.4 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  1.8.5 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment]
Hey @git-pawan-tripathi, thanks for reporting. I hope you realized that the problem was this file:

    /home/pawan/my py pro/datetime.py

Once you remove or rename it, your problem will be fixed.

**Comment by git-pawan-tripathi** [comment]
> Hey @git-pawan-tripathi, thanks for reporting. I hope you realized that the problem was this file:
> 
> ```
> /home/pawan/my py pro/datetime.py
> ```
> 
> Once you remove or rename it, your problem will be fixed.

Yes sir, it's is fixed .thanks for reply
