### ISSUE TITLE
Mac App - Importing matplotlib fails on Snow Leopard due to incompatible version of libpng

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1395]
_From [fergal.m...@gmail.com](https://code.google.com/u/108275253551016810144/) on 2013-05-16T17:48:09Z_

Spyder Version:  2.2.0
Python Version:  2.7.3
Qt Version:      4.8.2, PyQt4 (API v2) 4.9.4 on Darwin 

What steps will reproduce the problem?

 1. Install Spyder on a Mac (10.6.8) from the dmg at https://code.google.com/p/spyderlib/downloads/list 2. Open Spyder for the first time What is the expected output? What do you see instead? In the console I get the following error:

Python 2.7.3 (default, Jul 24 2012, 20:20:13) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.9.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Traceback (most recent call last):
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/spyderlib/scientific_startup.py", line 16, in \<module>
    from pylab import *  #analysis:ignore
  File "pylab.pyc", line 1, in \<module>
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/matplotlib/pylab.py", line 222, in \<module>
    from matplotlib import mpl  # pulls in most modules
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/matplotlib/mpl.py", line 2, in \<module>
    from matplotlib import axis
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/matplotlib/axis.py", line 14, in \<module>
    import matplotlib.text as mtext
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/matplotlib/text.py", line 29, in \<module>
    from matplotlib.backend_bases import RendererBase
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/matplotlib/backend_bases.py", line 47, in \<module>
    import matplotlib.textpath as textpath
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/matplotlib/textpath.py", line 11, in \<module>
    from matplotlib.mathtext import MathTextParser
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/matplotlib/mathtext.py", line 61, in \<module>
    import matplotlib._png as _png
ImportError: dlopen(/Applications/Spyder.app/Contents/Resources/lib/python2.7/matplotlib/_png.so, 2): Library not loaded: /usr/X11/lib/libpng15.15.dylib
  Referenced from: /Applications/Spyder.app/Contents/Resources/lib/python2.7/matplotlib/_png.so
  Reason: image not found

Doing a bit of digging, I find that I have /usr/X11/lib/libpng12.0.*.0.dylib, but not 15.15. Should that come with the "pre-built" dmg file? 

Please provide any additional information below

. My previously installed version of matplotlib (1.0.1) doesn't have this problem. Everything else in Spyder seems to work so far.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1395_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-06-28T22:00:01Z_

Our app is not designed to work with Snow Leopard (10.6). We'll see what we can do about it.

**Summary:** Mac App - Importing matplotlib fails on Snow Leopard  \<span class="oldvalue"> (was: Automatic import of matplotlib fails due to incompatible version of libpng in Mac OSX) \</span>  
  **Status:** Accepted  
  **Labels:** MS-v2.2.1 OpSys-OSX

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-07-06T20:45:35Z_

**Summary:** Mac App - Importing matplotlib fails on Snow Leopard due to ncompatible version of libpng  \<span class="oldvalue"> (was: Mac App - Importing matplotlib fails on Snow Leopard) \</span>

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-07-06T21:31:38Z_

This issue was updated by revision fc5c2070610c .


- The most important note is about the inability to use matplotlib in Snow
Leopard.
- The solution is to install a more recent version of libpng. A link to it is
now provided as part of our docs.

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-07-06T21:51:00Z_

**Summary:** Mac App - Importing matplotlib fails on Snow Leopard due to incompatible version of libpng  \<span class="oldvalue"> (was: Mac App - Importing matplotlib fails on Snow Leopard due to ncompatible version of libpng) \</span>
