### ISSUE TITLE
Issue when changing Python interpreters

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#13996]
On 4.x 5c39107ee dfe54e286 and Windows. I found some issues regarding interpreter changes:

* Trying to change the interpreter to an interpreter env with name `kernel36` ends up in an error dialog error:

<details>

Env packages:

```
# packages in environment at C:\Users\Daniel\Anaconda3\envs\kernel36:
#
# Name                    Version                   Build  Channel
backcall                  0.2.0                    pypi_0    pypi
certifi                   2020.6.20                py36_0
cloudpickle               1.5.0                    pypi_0    pypi
colorama                  0.4.3                    pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
ipykernel                 5.3.2                    pypi_0    pypi
ipython                   7.16.1                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.17.1                   pypi_0    pypi
jupyter-client            6.1.5                    pypi_0    pypi
jupyter-core              4.6.3                    pypi_0    pypi
parso                     0.7.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pip                       20.1.1                   py36_1
prompt-toolkit            3.0.5                    pypi_0    pypi
pygments                  2.6.1                    pypi_0    pypi
python                    3.6.8                h9f7ef89_7
python-dateutil           2.8.1                    pypi_0    pypi
pywin32                   228                      pypi_0    pypi
pyzmq                     19.0.1                   pypi_0    pypi
setuptools                47.3.1                   py36_0
six                       1.15.0                   pypi_0    pypi
spyder-kernels            1.9.4                    pypi_0    pypi
sqlite                    3.32.3               h2a8f88b_0
tornado                   6.0.4                    pypi_0    pypi
traitlets                 4.3.3                    pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
wcwidth                   0.2.5                    pypi_0    pypi
wheel                     0.34.2                   py36_0
wincertstore              0.2              py36h7fe50ca_0
zlib                      1.2.11               h62dcd97_4
```

Error dialog:

![image](https://user-images.githubusercontent.com/16781833/96299276-6e5eb900-0fb9-11eb-9a60-c1a32d72f6e0.png)

</details>

* Using `pythonw` instead of `python` with the same env described above ends up in a report error dialog with the following traceback and also a traceback on the internal console:

<details>

Report dialog traceback:

```traceback
jedi.api.environment.InvalidPythonEnvironment: Scripts\python.exe seems to be missing.  File "C:\Users\Daniel\Anaconda3\envs\develop\lib\site-packages\pyls_jsonrpc\endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "C:\Users\Daniel\Anaconda3\envs\develop\lib\site-packages\pyls_jsonrpc\endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "C:\Users\Daniel\Anaconda3\envs\develop\lib\site-packages\pyls_jsonrpc\dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "C:\Users\Daniel\Documents\Spyder\spyder\external-deps\python-language-server\pyls\python_ls.py", line 334, in m_text_document__document_symbol
    return self.document_symbols(textDocument['uri'])
  File "C:\Users\Daniel\Documents\Spyder\spyder\external-deps\python-language-server\pyls\python_ls.py", line 250, in document_symbols
    return flatten(self._hook('pyls_document_symbols', doc_uri))
  File "C:\Users\Daniel\Documents\Spyder\spyder\external-deps\python-language-server\pyls\python_ls.py", line 156, in _hook
    return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)
  File "C:\Users\Daniel\Anaconda3\envs\develop\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "C:\Users\Daniel\Anaconda3\envs\develop\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Users\Daniel\Anaconda3\envs\develop\lib\site-packages\pluggy\manager.py", line 337, in traced_hookexec
    return outcome.get_result()
  File "C:\Users\Daniel\Anaconda3\envs\develop\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\Daniel\Anaconda3\envs\develop\lib\site-packages\pluggy\callers.py", line 52, in from_call
    result = func()
  File "C:\Users\Daniel\Anaconda3\envs\develop\lib\site-packages\pluggy\manager.py", line 335, in <lambda>
    outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))
  File "C:\Users\Daniel\Anaconda3\envs\develop\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "C:\Users\Daniel\Anaconda3\envs\develop\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "C:\Users\Daniel\Anaconda3\envs\develop\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\Daniel\Anaconda3\envs\develop\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Daniel\Documents\Spyder\spyder\external-deps\python-language-server\pyls\plugins\symbols.py", line 18, in pyls_document_symbols
    definitions = document.jedi_names(all_scopes=all_scopes)
  File "C:\Users\Daniel\Documents\Spyder\spyder\external-deps\python-language-server\pyls\workspace.py", line 25, in wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\Daniel\Documents\Spyder\spyder\external-deps\python-language-server\pyls\workspace.py", line 238, in jedi_names
    script = self.jedi_script()
  File "C:\Users\Daniel\Documents\Spyder\spyder\external-deps\python-language-server\pyls\workspace.py", line 25, in wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\Daniel\Documents\Spyder\spyder\external-deps\python-language-server\pyls\workspace.py", line 261, in jedi_script
    sys_path = self.sys_path(environment_path, env_vars=env_vars) + extra_paths
  File "C:\Users\Daniel\Documents\Spyder\spyder\external-deps\python-language-server\pyls\workspace.py", line 296, in sys_path
    environment = self.get_enviroment(environment_path=environment_path, env_vars=env_vars)
  File "C:\Users\Daniel\Documents\Spyder\spyder\external-deps\python-language-server\pyls\workspace.py", line 287, in get_enviroment
    env_vars=env_vars)
  File "C:\Users\Daniel\Anaconda3\envs\develop\lib\site-packages\jedi\api\environment.py", line 379, in create_environment
    return _create_environment(path, safe, **kwargs)
  File "C:\Users\Daniel\Anaconda3\envs\develop\lib\site-packages\jedi\api\environment.py", line 386, in _create_environment
    return Environment(_get_executable_path(path, safe=safe), env_vars=env_vars)
  File "C:\Users\Daniel\Anaconda3\envs\develop\lib\site-packages\jedi\api\environment.py", line 399, in _get_executable_path
    raise InvalidPythonEnvironment("%s seems to be missing." % python)

jedi.api.environment.InvalidPythonEnvironment: Scripts\python.exe seems to be missing.
```

Internal console traceback:

```
Traceback (most recent call last):
  File "C:\Users\Daniel\Documents\Spyder\spyder\spyder\preferences\configdialog.py", line 227, in accept
    configpage.apply_changes()
  File "C:\Users\Daniel\Documents\Spyder\spyder\spyder\preferences\configdialog.py", line 99, in apply_changes
    self.apply_callback()
  File "C:\Users\Daniel\Documents\Spyder\spyder\spyder\preferences\configdialog.py", line 282, in <lambda>
    self.apply_settings(self.changed_options))
  File "C:\Users\Daniel\Documents\Spyder\spyder\spyder\preferences\maininterpreter.py", line 263, in apply_settings
    self.main.apply_statusbar_settings()
  File "C:\Users\Daniel\Documents\Spyder\spyder\spyder\app\mainwindow.py", line 3064, in apply_statusbar_settings
    self.interpreter_status.update_interpreter(interpreter)
  File "C:\Users\Daniel\Documents\Spyder\spyder\spyder\widgets\status.py", line 292, in update_interpreter
    text = self._process_interpreter_env_info()
  File "C:\Users\Daniel\Documents\Spyder\spyder\spyder\widgets\status.py", line 265, in _process_interpreter_env_info
    if is_conda_env(pyexec=self._interpreter):
  File "C:\Users\Daniel\Documents\Spyder\spyder\spyder\utils\conda.py", line 31, in is_conda_env
    return os.path.exists(os.path.join(prefix, 'conda-meta'))
  File "C:\Users\Daniel\Anaconda3\envs\develop\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

</details>

**Comment by dalthviz** [comment]
Pinging @ccordoba12 just in case

**Comment by dalthviz** [comment]
Note: Seems like this is related with using a Python 3.6.8 interpreter. Changing the validation to allow such interpreter ends in other errors that involve the use of `LooseVersion` comparisons to validate `spyder-kernels` version.

**Comment by ccordoba12** [comment]
Closing because we don't support Python 3.6 anymore.
