### ISSUE TITLE
internal problem upon startup of Spyder

### ISSUE THREAD

**Issue by ReinierNL** [spyder-ide/spyder#14005]
### What steps will reproduce the problem?

I run the Anaconda prompt, activate one of my environments, then run Spyder (from the prompt).
Spyder starts up and immediately the Issue reporter pops up:
Spyder had encountered and internal problem!

### Traceback
```python-traceback
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\zmq\eventloop\zmqstream.py", line 444, in _run_callback
    callback(*args, **kwargs)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\jupyter_client\threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\jupyter_client\session.py", line 931, in deserialize
    message['header'] = extract_dates(header)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\jupyter_client\jsonutil.py", line 64, in extract_dates
    new_obj[k] = extract_dates(v)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\jupyter_client\jsonutil.py", line 69, in extract_dates
    obj = parse_date(obj)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\jupyter_client\jsonutil.py", line 55, in parse_date
    dt = _dateutil_parse(s)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\dateutil\parser\_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\dateutil\parser\_parser.py", line 660, in parse
    ret = self._build_tzaware(ret, res, tzinfos)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\dateutil\parser\_parser.py", line 1201, in _build_tzaware
    aware = naive.replace(tzinfo=tz.UTC)
AttributeError: module 'dateutil.tz' has no attribute 'UTC'
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\zmq\eventloop\zmqstream.py", line 462, in _handle_events
    self._handle_recv()
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\zmq\eventloop\zmqstream.py", line 492, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\zmq\eventloop\zmqstream.py", line 444, in _run_callback
    callback(*args, **kwargs)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\jupyter_client\threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\jupyter_client\session.py", line 931, in deserialize
    message['header'] = extract_dates(header)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\jupyter_client\jsonutil.py", line 64, in extract_dates
    new_obj[k] = extract_dates(v)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\jupyter_client\jsonutil.py", line 69, in extract_dates
    obj = parse_date(obj)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\jupyter_client\jsonutil.py", line 55, in parse_date
    dt = _dateutil_parse(s)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\dateutil\parser\_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\dateutil\parser\_parser.py", line 660, in parse
    ret = self._build_tzaware(ret, res, tzinfos)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\dateutil\parser\_parser.py", line 1201, in _build_tzaware
    aware = naive.replace(tzinfo=tz.UTC)
AttributeError: module 'dateutil.tz' has no attribute 'UTC'
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(4656, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(4656, 1)>
Traceback (most recent call last):
  File "C:\Python\Anaconda3\envs\rommel37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\tornado\platform\asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\zmq\eventloop\zmqstream.py", line 462, in _handle_events
    self._handle_recv()
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\zmq\eventloop\zmqstream.py", line 492, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\zmq\eventloop\zmqstream.py", line 444, in _run_callback
    callback(*args, **kwargs)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\jupyter_client\threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\jupyter_client\session.py", line 931, in deserialize
    message['header'] = extract_dates(header)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\jupyter_client\jsonutil.py", line 64, in extract_dates
    new_obj[k] = extract_dates(v)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\jupyter_client\jsonutil.py", line 69, in extract_dates
    obj = parse_date(obj)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\jupyter_client\jsonutil.py", line 55, in parse_date
    dt = _dateutil_parse(s)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\dateutil\parser\_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\dateutil\parser\_parser.py", line 660, in parse
    ret = self._build_tzaware(ret, res, tzinfos)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\dateutil\parser\_parser.py", line 1201, in _build_tzaware
    aware = naive.replace(tzinfo=tz.UTC)
AttributeError: module 'dateutil.tz' has no attribute 'UTC'
Traceback (most recent call last):
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 557, in set_current_client_working_directory
    shellwidget.set_cwd(directory)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 221, in set_cwd
    self.call_kernel(interrupt=True).set_cwd(dirname)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\spyder_kernels\comms\commbase.py", line 550, in __call__
    call_dict, call_data, self._comm_id)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 150, in _get_call_return_value
    comm_id, queue_message=not interrupt):
  File "C:\Python\Anaconda3\envs\rommel37\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 89, in comm_channel_manager
    timeout)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 205, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for comm port.
Traceback (most recent call last):
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 1103, in set_spyder_breakpoints
    cl.shellwidget.set_spyder_breakpoints()
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 156, in set_spyder_breakpoints
    CONF.get('run', 'breakpoints', {}))
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\spyder_kernels\comms\commbase.py", line 550, in __call__
    call_dict, call_data, self._comm_id)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 150, in _get_call_return_value
    comm_id, queue_message=not interrupt):
  File "C:\Python\Anaconda3\envs\rommel37\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 89, in comm_channel_manager
    timeout)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 205, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for comm port.
Traceback (most recent call last):
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 579, in update_path
    shell.update_syspath(path_dict, new_path_dict)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 266, in update_syspath
    blocking=False).update_syspath(path_dict, new_path_dict)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\spyder_kernels\comms\commbase.py", line 550, in __call__
    call_dict, call_data, self._comm_id)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 150, in _get_call_return_value
    comm_id, queue_message=not interrupt):
  File "C:\Python\Anaconda3\envs\rommel37\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 89, in comm_channel_manager
    timeout)
  File "C:\Python\Anaconda3\envs\rommel37\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 205, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for comm port.
```

## Versions

* Spyder version: 4.1.5 
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.0 (OK)
numpy >=1.7                    :  1.19.1 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ReinierNL** [comment]
> Thanks for reporting. This issue is fixed in our latest Spyder 3 version. Please update by opening the Anaconda Prompt and running there:
> 
> `conda install spyder=3.3.6`

That's seems to be nonsense. I am running Spyder 4.1.5

**Comment by ccordoba12** [comment]
Hey @ReinierNL, thanks for reporting. It seems you have a corrupted `dateutil` module. Please try to fix that by opening the Anaconda Prompt and running there

    conda install -f python-dateutil

**Comment by ccordoba12** [comment]
Closing due to lack of response.
