### ISSUE TITLE
large dataframe unviewable

### ISSUE THREAD

**Issue by christokita** [spyder-ide/spyder#14047]
### What steps will reproduce the problem?

When opening a large dataframe in the "Variable explorer" window and scrolling to the right to see more columns, an error will pop up saying "Spyder has encountered an internal problem". This causes the variable explorer window to stop working. I noticed this error does not occur when I turn off the automatic value coloring in columns (i.e., coloring values in a heat map of min to max values within a columns).

### Traceback
```python-traceback
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 316, in data
    return to_qvariant(self.get_bgcolor(index))
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 253, in get_bgcolor
    (vmax - color_func(value)) / (vmax - vmin))
ZeroDivisionError: float division by zero
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.6.0

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
psutil >=0.3      :  5.6.3 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  1.1.0 (OK)
numpy >=1.7       :  1.18.2 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @christokita, thanks for reporting. This issue is fixed in our latest release (4.1.5).

Unfortunately, Spyder 3 is not maintainer anymore, so your only option is to update to that version, sorry.
