### ISSUE TITLE
Why spyder 4.1.5 could not launch in Anaconda Navigator?

### ISSUE THREAD

**Issue by WinLaiYGN** [spyder-ide/spyder#14070]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by steff456** [comment]
Hi @WinLaiYGN,

Can you please tell me if you try to run spyder from the command line, does it open?

**Comment by WinLaiYGN** [comment]
C:\Users\u22y33>spyder Traceback (most recent call last): File "C:\Users\u22y33\AppData\Local\Continuum\anaconda3\lib\site-packages\qtpy\__init__.py", line 204, in <module> from PySide import __version__ as PYSIDE_VERSION # analysis:ignore ModuleNotFoundError: No module named 'PySide' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "C:\Users\u22y33\AppData\Local\Continuum\anaconda3\Scripts\spyder-script.py", line 10, in <module> sys.exit(main()) File "C:\Users\u22y33\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\app\start.py", line 186, in main from spyder.app import mainwindow File "C:\Users\u22y33\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 48, in <module> requirements.check_qt() File "C:\Users\u22y33\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\requirements.py", line 41, in check_qt import qtpy File "C:\Users\u22y33\AppData\Local\Continuum\anaconda3\lib\site-packages\qtpy\__init__.py", line 210, in <module> raise PythonQtError('No Qt bindings could be found') qtpy.PythonQtError: No Qt bindings could be found

**Comment by AminDar** [comment]
having the same issue and it wont lunch even using Terminal



```
Traceback (most recent call last):
File "/Users/amin/anaconda3/bin/spyder", line 7, in 
from spyder.app.start import main
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 35, in 
from spyder.config.manager import CONF
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder/config/manager.py", line 17, in 
from spyder.config.main import CONF_VERSION, DEFAULTS, NAME_MAP
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder/config/main.py", line 19, in 
from spyder.config.fonts import MEDIUM, SANS_SERIF
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder/config/fonts.py", line 14, in 
from spyder.config.utils import is_ubuntu
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder/config/utils.py", line 17, in 
from spyder_kernels.utils import iofuncs
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder_kernels/utils/iofuncs.py", line 523, in 
iofunctions.setup()
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder_kernels/utils/iofuncs.py", line 447, in setup
iofuncs = self.get_internal_funcs()+self.get_3rd_party_funcs()
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder_kernels/utils/iofuncs.py", line 498, in get_3rd_party_funcs
for mod in get_spyderplugins_mods(io=True):
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder/otherplugins.py", line 45, in get_spyderplugins_mods
_get_spyderplugins(plugin_path, io, modnames, modlist)
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder/otherplugins.py", line 54, in _get_spyderplugins
for name in os.listdir(plugin_path):
PermissionError: [Errno 13] Permission denied: '/Users/amin/.local/lib/python3.7/site-packages'

```

**Conda** List:

```

# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0  
alabaster                 0.7.12                   py37_0  
anaconda-client           1.7.2                    py37_0  
anaconda-navigator        1.9.12                   py37_0  
applaunchservices         0.2.1                      py_0  
appnope                   0.1.0                    py37_0  
argh                      0.26.2                   py37_0  
argon2-cffi               20.1.0           py37haf1e3a3_1  
astroid                   2.4.2                    py37_0  
async_generator           1.10             py37h28b3542_0  
atomicwrites              1.4.0                      py_0  
attrs                     20.3.0             pyhd3eb1b0_0  
autopep8                  1.5.4                      py_0  
babel                     2.8.1              pyhd3eb1b0_0  
backcall                  0.2.0                      py_0  
backports                 1.0                        py_2  
backports.functools_lru_cache 1.6.1                      py_0  
backports.tempfile        1.0                        py_1  
backports.weakref         1.0.post1                  py_1  
beautifulsoup4            4.9.3              pyhb0f4dca_0  
blas                      1.0                         mkl  
bleach                    3.2.1                      py_0  
brotlipy                  0.7.0           py37haf1e3a3_1000  
ca-certificates           2020.10.14                    0  
certifi                   2020.6.20          pyhd3eb1b0_3  
cffi                      1.14.3           py37hed5b41f_0  
chardet                   3.0.4                 py37_1003  
click                     7.1.2                      py_0  
cloudpickle               1.6.0                      py_0  
clyent                    1.2.2                    py37_1  
conda                     4.9.2            py37hecd8cb5_0  
conda-build               3.18.8                   py37_0  
conda-env                 2.6.0                         1  
conda-package-handling    1.7.2            py37h22f3db7_0  
conda-verify              3.4.2                      py_1  
cryptography              3.1.1            py37hddc9c9b_0  
dbus                      1.13.18              h18a8e69_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
diff-match-patch          20200713                   py_0  
docutils                  0.16                     py37_1  
entrypoints               0.3                      py37_0  
expat                     2.2.10               hb1e8313_2  
filelock                  3.0.12                     py_0  
flake8                    3.8.4                      py_0  
freetype                  2.10.4               ha233b18_0  
future                    0.18.2                   py37_1  
gettext                   0.19.8.1             hb0f4f8b_2  
glib                      2.66.1               h9bbe63b_0  
glob2                     0.7                        py_0  
icu                       58.2                 h0a44026_3  
idna                      2.10                       py_0  
imagesize                 1.2.0                      py_0  
importlib-metadata        2.0.0                      py_1  
importlib_metadata        2.0.0                         1  
intel-openmp              2019.4                      233  
intervaltree              3.1.0                      py_0  
ipykernel                 5.3.4            py37h5ca1d4c_0  
ipython                   7.19.0           py37h01d92e1_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.5.1                      py_1  
isort                     5.6.4                      py_0  
jedi                      0.17.1                   py37_0  
jinja2                    2.11.2                     py_0  
jpeg                      9b                   he5867d9_2  
json5                     0.9.5                      py_0  
jsonschema                3.2.0                      py_2  
jupyter_client            6.1.7                      py_0  
jupyter_core              4.6.3                    py37_0  
jupyterlab                2.2.6                      py_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         1.2.0                      py_0  
keyring                   21.4.0                   py37_1  
lazy-object-proxy         1.4.3            py37h1de35cc_0  
lcms2                     2.11                 h92f6f08_0  
libcxx                    10.0.0                        1  
libedit                   3.1.20191231         h1de35cc_1  
libffi                    3.3                  hb1e8313_2  
libiconv                  1.16                 h1de35cc_0  
liblief                   0.10.1               h0a44026_0  
libpng                    1.6.37               ha441bb4_0  
libsodium                 1.0.18               h1de35cc_0  
libspatialindex           1.9.3                h0a44026_0  
libtiff                   4.1.0                hcb84e12_1  
lz4-c                     1.9.2                h79c402e_3  
markupsafe                1.1.1            py37h1de35cc_0  
mccabe                    0.6.1                    py37_1  
mistune                   0.8.4            py37h1de35cc_0  
mkl                       2019.4                      233  
mkl-service               2.3.0            py37hfbe908c_0  
mkl_fft                   1.2.0            py37hc64f4ea_0  
mkl_random                1.1.1            py37h959d312_0  
navigator-updater         0.2.1                    py37_0  
nbclient                  0.5.1                      py_0  
nbconvert                 6.0.7                    py37_0  
nbformat                  5.0.8                      py_0  
ncurses                   6.2                  h0a44026_1  
nest-asyncio              1.4.1                      py_0  
notebook                  6.1.4                    py37_0  
numpy                     1.19.2           py37h456fd55_0  
numpy-base                1.19.2           py37hcfb5961_0  
numpydoc                  1.1.0              pyhd3eb1b0_1  
olefile                   0.46                     py37_0  
openssl                   1.1.1h               haf1e3a3_0  
packaging                 20.4                       py_0  
pandas                    1.1.3            py37hb1e8313_0  
pandoc                    2.11                 h0dc7051_0  
pandocfilters             1.4.2                    py37_1  
parso                     0.7.0                      py_0  
pathtools                 0.1.2                      py_1  
pcre                      8.44                 hb1e8313_0  
pexpect                   4.8.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    8.0.1            py37h5270095_0  
pkginfo                   1.6.0                    py37_0  
pluggy                    0.13.1                   py37_0  
prometheus_client         0.8.0                      py_0  
prompt-toolkit            3.0.8                      py_0  
psutil                    5.7.2            py37haf1e3a3_0  
ptyprocess                0.6.0                    py37_0  
py-lief                   0.10.1           py37haf313ee_0  
pycodestyle               2.6.0                      py_0  
pycosat                   0.6.3            py37h1de35cc_0  
pycparser                 2.20                       py_2  
pydocstyle                5.1.1                      py_0  
pyflakes                  2.2.0                      py_0  
pygments                  2.7.2              pyhd3eb1b0_0  
pylint                    2.6.0                    py37_0  
pyopenssl                 19.1.0                     py_1  
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py37h655552a_2  
pyrsistent                0.17.3           py37haf1e3a3_0  
pysocks                   1.7.1                    py37_0  
python                    3.7.3                h359304d_0  
python-dateutil           2.8.1                      py_0  
python-jsonrpc-server     0.4.0                      py_0  
python-language-server    0.35.1                     py_0  
python.app                2                       py37_10  
pytz                      2020.1                     py_0  
pyyaml                    5.3.1            py37haf1e3a3_1  
pyzmq                     19.0.2           py37hb1e8313_1  
qdarkstyle                2.8.1                      py_0  
qt                        5.9.7                h468cd18_1  
qtawesome                 1.0.1                      py_0  
qtconsole                 4.7.7                      py_0  
qtpy                      1.9.0                      py_0  
readline                  7.0                  h1de35cc_5  
requests                  2.24.0                     py_0  
rope                      0.18.0                     py_0  
rtree                     0.9.4                    py37_1  
ruamel_yaml               0.15.87          py37haf1e3a3_1  
send2trash                1.5.0                    py37_0  
setuptools                50.3.1           py37hecd8cb5_1  
sip                       4.19.8           py37h0a44026_0  
six                       1.15.0                     py_0  
snowballstemmer           2.0.0                      py_0  
sortedcontainers          2.2.2                      py_0  
soupsieve                 2.0.1                      py_0  
sphinx                    3.2.1                      py_0  
sphinxcontrib-applehelp   1.0.2                      py_0  
sphinxcontrib-devhelp     1.0.2                      py_0  
sphinxcontrib-htmlhelp    1.0.3                      py_0  
sphinxcontrib-jsmath      1.0.1                      py_0  
sphinxcontrib-qthelp      1.0.3                      py_0  
sphinxcontrib-serializinghtml 1.1.4                      py_0  
spyder                    4.1.5                    py37_0  
spyder-kernels            1.9.4                    py37_0  
sqlite                    3.33.0               hffcf06c_0  
terminado                 0.9.1                    py37_0  
testpath                  0.4.4                      py_0  
tk                        8.6.10               hb0a8c7a_0  
toml                      0.10.1                     py_0  
tornado                   6.0.4            py37h1de35cc_1  
tqdm                      4.50.2                     py_0  
traitlets                 5.0.5                      py_0  
typed-ast                 1.4.1            py37h1de35cc_0  
ujson                     4.0.1            py37hb1e8313_0  
urllib3                   1.25.11                    py_0  
watchdog                  0.10.3           py37haf1e3a3_0  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py37_1  
widgetsnbextension        3.5.1                    py37_0  
wrapt                     1.11.2           py37h1de35cc_0  
wurlitzer                 2.0.1                    py37_0  
xmltodict                 0.12.0                     py_0  
xz                        5.2.5                h1de35cc_0  
yaml                      0.2.5                haf1e3a3_0  
yapf                      0.30.0                     py_0  
zeromq                    4.3.3                hb1e8313_3  
zipp                      3.4.0              pyhd3eb1b0_0  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.4.5                h41d2c2f_0  


```

**Comment by ccordoba12** [comment]
@AminDar, please delete this directory to fix your problem:

    /Users/amin/.local/lib/python3.7

**Comment by AminDar** [comment]
> @AminDar, please delete this directory to fix your problem:
> 
> ```
> /Users/amin/.local/lib/python3.7
> ```

before deleting it can you please explain what i'm deleting?
and and **UPDATE**: I could lunch it through terminal with adding a sudo commend:
`sudo spyder`

**Comment by ccordoba12** [comment]
> before deleting it can you please explain what i'm deleting?

Because you used pip to install some packages which are interfering with Spyder, they got installed on that directory and you used sudo to install them.
