### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by saket349** [spyder-ide/spyder#14098]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Traceback (most recent call last):
File "/home/saket/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/home/saket/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/saket/anaconda3/lib/python3.8/site‑packages/spyder_kernels/console/__main__.py", line 23, in
start.main()
File "/home/saket/anaconda3/lib/python3.8/site‑packages/spyder_kernels/console/start.py", line 289, in main
import_spydercustomize()
File "/home/saket/anaconda3/lib/python3.8/site‑packages/spyder_kernels/console/start.py", line 39, in import_spydercustomize
import spydercustomize
File "/home/saket/anaconda3/lib/python3.8/site‑packages/spyder_kernels/customize/spydercustomize.py", line 24, in 
from IPython.core.getipython import get_ipython
File "/home/saket/anaconda3/lib/python3.8/site‑packages/IPython/__init__.py", line 55, in 
from .core.application import Application
File "/home/saket/anaconda3/lib/python3.8/site‑packages/IPython/core/application.py", line 26, in 
from IPython.core.profiledir import ProfileDir, ProfileDirError
File "/home/saket/anaconda3/lib/python3.8/site‑packages/IPython/core/profiledir.py", line 12, in 
from ..paths import get_ipython_package_dir
File "/home/saket/anaconda3/lib/python3.8/site‑packages/IPython/paths.py", line 5, in 
import tempfile
File "/home/saket/anaconda3/lib/python3.8/tempfile.py", line 45, in 
from random import Random as _Random
ImportError: cannot import name 'Random' from 'random' (/home/saket/random.py)

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.5
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Ubuntu 18.04

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by saket349** [comment]
For me, the issue was with the "random.py" file at home/saket/ directory. Renaming it resolved my issue. 
And now, finally, the console is working fine.
