### ISSUE TITLE
Spyder crashes on startup

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1411]
_From [conchu...@gmail.com](https://code.google.com/u/103112735753415489542/) on 2013-05-29T14:28:37Z_

I installed spyder through python(x,y) version 2.7.3.1 and when I try loading it, it crashes at "setting up main window"

Here is what I see when running spyder --debug

Start of MainWindow constructor
Initializing...
End of MainWindow constructor
*** Start of MainWindow setup ***
Loading object inspector...
Loading outline explorer...
Loading editor...
Loading file explorer...
Loading history plugin...
Loading online help...
Loading project explorer...
Loading external console...
Loading namespace browser...
Setting up main window...
\<module 'spyderplugins.p_breakpoints' from 'C:\Python27\lib\site-packages\spyder
plugins\p_breakpoints.pyc'>: 'Editor' object has no attribute 'clear_breakpoint'

Setting up window...
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 2009, in main
    mainwindow = run_spyder(app, options)
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 1921, in run_sp
yder
    main.setup()
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 934, in setup
    self.setup_layout(default=False)
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 1078, in setup_
layout
    plugin.dockwidget.close()
AttributeError: 'NoneType' object has no attribute 'close'

What should I do?

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1411_

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-06-03T11:56:45Z_

Looks like a race condition. Which version of Spyder is it?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-06-29T06:29:40Z_

Please update your Python(x,y) installation, which comes with the latest release of Spyder. Most probably the problem is fixed on it.

**Status:** WontFix
