### ISSUE TITLE
IndentationError

### ISSUE THREAD

**Issue by Licifer666** [spyder-ide/spyder#14121]
### What steps will reproduce the problem?

print("The largest number between" , num1 ,"," ,num2, "and",num3,"is",largest )

### Traceback
```python-traceback
  File "C:\Users\Deepak\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 622, in _restart_thread_main
    self.shellwidget.kernel_manager.restart_kernel(
  File "C:\Users\Deepak\anaconda3\lib\site-packages\jupyter_client\manager.py", line 454, in restart_kernel
    self.start_kernel(**self._launch_args)
  File "C:\Users\Deepak\anaconda3\lib\site-packages\jupyter_client\manager.py", line 314, in start_kernel
    self.post_start_kernel(**kw)
  File "C:\Users\Deepak\anaconda3\lib\site-packages\jupyter_client\manager.py", line 295, in post_start_kernel
    self._connect_control_socket()
  File "C:\Users\Deepak\anaconda3\lib\site-packages\jupyter_client\manager.py", line 226, in _connect_control_socket
    self._control_socket = self._create_connected_socket('control')
  File "C:\Users\Deepak\anaconda3\lib\site-packages\jupyter_client\connect.py", line 545, in _create_connected_socket
    sock = self.context.socket(socket_type)
  File "C:\Users\Deepak\anaconda3\lib\site-packages\zmq\sugar\context.py", line 225, in socket
    raise ZMQError(ENOTSUP)
zmq.error.ZMQError: Not supported
Traceback (most recent call last):
  File "C:\Users\Deepak\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 609, in <lambda>
    lambda: self._finalise_restart(True))
  File "C:\Users\Deepak\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 644, in _finalise_restart
    sw.spyder_kernel_comm.open_comm(sw.kernel_client)
  File "C:\Users\Deepak\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 114, in open_comm
    kernel_client.comm_manager.new_comm(self._comm_name, data={
AttributeError: 'NoneType' object has no attribute 'new_comm'
```

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.2 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @Licifer666, thanks for reporting. This looks like an installation error in Anaconda.

Please see [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) on how to remove Anaconda and reinstall it again appropriately.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
