### ISSUE TITLE
LSP Server Does Not Startup on macOS Application

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#14140]
## Problem Description
LSP server does not complete startup on macOS application

<img width="260" alt="Screen Shot 2020-11-03 at 8 31 56 PM" src="https://user-images.githubusercontent.com/9618975/98069438-a2d4d080-1e13-11eb-91b3-781cf299114c.png">

@ccordoba12, please assign to @mrclary

## Versions

* Spyder version: 4.2.0.dev0 0fe8907a73602c373be5b4c8d76cb6e173773951
* Python version: 3.8.6 64-bit
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Darwin 19.6.0

**Comment by ccordoba12** [comment]
It's probably an issue with Black (which is a dependency of pyls-black). I mention it because @dalthviz was seeing a similar problem with the Windows installer in PR #14059.

**Comment by mrclary** [comment]
Thanks for the heads up @ccordoba12. I discovered this traceback in the PyLS server log.

```python
Traceback (most recent call last):
  File "pyls_jsonrpc/endpoint.pyc", line 113, in consume
  File "pyls_jsonrpc/endpoint.pyc", line 182, in _handle_request
  File "pyls_jsonrpc/dispatchers.pyc", line 23, in handler
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.8/pyls/python_ls.py", line 208, in m_initialize
    self.config = config.Config(rootUri, initializationOptions or {},
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.8/pyls/config/config.py", line 53, in __init__
    entry_point.load()
  File "pkg_resources/__init__.pyc", line 2446, in load
  File "pkg_resources/__init__.pyc", line 2469, in require
  File "pkg_resources/__init__.pyc", line 770, in resolve
pkg_resources.DistributionNotFound: The 'python-language-server' distribution was not found and is required by the application
```

Also, when `>>> import black` from the internal console, Spyder's debug output gave
```python
Traceback (most recent call last):
  File "<frozen zipimport>", line 177, in get_data
KeyError: 'blib2to3/Users/rclary/Library/Caches/black/20.8b1/Grammar3.8.6.final.0.pickle'
```

**Comment by mrclary** [comment]
Okay, adding `black`, `_black_version`, and `blib2to3` to packages resolved the error when importing `black` from the internal console (this is probably good). I don't know if all three were required, but I can experiment later.

This did not fix the `DistributionNotFound` for 'python-language-server'.

**Comment by mrclary** [comment]
Okay! Found the issue: `pkg_resources` needs an egg-info or dist-info file which is _not_ created for `python-language-server` if it is installed in editable mode (`pip install -e`). It worked for bootstrap because it there it is fully installed and the egg-info is created.

**Comment by mrclary** [comment]
Also, only `blib2to3` is required to add to `py2app` packages option. `black` and `_black_version` can remain in the zip folder.
