### ISSUE TITLE
crashing after creating a new workspace

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1414]
_From [sleepywi...@gmail.com](https://code.google.com/u/101443276832137180940/) on 2013-05-30T11:30:33Z_

When creating a new project, you'll be asked to create a new workspace. After you choose a directory, a error occurs inside the shell (besides this, spyder is still working). After restarting spider, it is crashing and the same error occurs:
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/spyderlib/spyder.py", line 2101, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python3.3/site-packages/spyderlib/spyder.py", line 1998, in run_spyder
    main.setup()
  File "/usr/lib/python3.3/site-packages/spyderlib/spyder.py", line 778, in setup
    self.projectexplorer = ProjectExplorer(self)
  File "/usr/lib/python3.3/site-packages/spyderlib/plugins/projectexplorer.py", line 37, in __init__
    self.load_config()
  File "/usr/lib/python3.3/site-packages/spyderlib/plugins/projectexplorer.py", line 137, in load_config
    self.set_workspace(self.get_option('workspace', None))
  File "/usr/lib/python3.3/site-packages/spyderlib/widgets/projectexplorer.py", line 1269, in set_workspace
    self.treewidget.set_workspace(path)
  File "/usr/lib/python3.3/site-packages/spyderlib/widgets/projectexplorer.py", line 669, in set_workspace
    self.workspace.set_root_path(root_path)
  File "/usr/lib/python3.3/site-packages/spyderlib/widgets/projectexplorer.py", line 277, in set_root_path
    self.load()
  File "/usr/lib/python3.3/site-packages/spyderlib/widgets/projectexplorer.py", line 296, in load
    data = pickle.loads(fdesc.read())
  File "/usr/lib/python3.3/codecs.py", line 300, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

After I deleted the line "workspace = /home/" under the section "[project_explorer]" inside the spyder.ini, it'll start again. 

I'm using Spyder 2.3.0dev2 with Python 3.3.2 64bits, Qt 4.8.4, PyQt4 (API v2) 4.10.1 on Linux

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1414_

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-06-06T14:25:06Z_

We need to add a new category for all Python 3 related bugs. I am pretty sure it is connected. Have you tried to run Spyder with Python 2 as well?

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-08-15T20:54:00Z_

This issue was updated by revision 5eddc313c2e5 .

I believe this should be fixed by this revision, but additional verification
would be helpful. Tested on Ubuntu 13.04 with Python 2.7 and 3.3.

**Status:** Fixed
