### ISSUE TITLE
Spyder 4.2 / astroid / pylint version conflicts

### ISSUE THREAD

**Issue by texadactyl** [spyder-ide/spyder#14171]
## Problem Description

Trying to launch Spyder results in a traceback.
Work-around provided at the end of this report.

### What steps reproduce the problem?

1. ```pip install -U spyder```
2. ```spyder```

### What is the expected output? What do you see instead?

Expected: Normal startup
Observed: Termination after the traceback

Anyone else run into this?
Astroid corruption today in pypi?

### Paste Traceback/Error Below (if applicable)

```python-traceback

spyder --debug-info verbose
2020-11-08 21:40:17,353 [INFO] [spyder.app.mainwindow] -> Start of MainWindow constructor
2020-11-08 21:40:17,376 [INFO] [spyder.app.mainwindow] -> End of MainWindow constructor
2020-11-08 21:40:17,376 [INFO] [spyder.app.mainwindow] -> *** Start of MainWindow setup ***
2020-11-08 21:40:17,376 [INFO] [spyder.app.mainwindow] -> Updating PYTHONPATH
2020-11-08 21:40:17,376 [INFO] [spyder.app.mainwindow] -> Applying theme configuration...
2020-11-08 21:40:17,377 [INFO] [spyder.app.mainwindow] -> Creating core actions...
2020-11-08 21:40:17,377 [INFO] [spyder.app.mainwindow] -> Creating toolbars...
2020-11-08 21:40:17,380 [INFO] [spyder.app.mainwindow] -> Creating Tools menu...
2020-11-08 21:40:17,383 [INFO] [spyder.app.mainwindow] -> Creating guidata and sift entries...
2020-11-08 21:40:17,384 [INFO] [spyder.app.mainwindow] -> Loading switcher...
2020-11-08 21:40:17,385 [INFO] [spyder.app.mainwindow] -> Loading internal console...
2020-11-08 21:40:17,414 [INFO] [keyring.backend] -> Loading KWallet
2020-11-08 21:40:17,417 [INFO] [keyring.backend] -> Loading SecretService
2020-11-08 21:40:17,424 [INFO] [keyring.backend] -> Loading Windows
2020-11-08 21:40:17,425 [INFO] [keyring.backend] -> Loading chainer
2020-11-08 21:40:17,425 [INFO] [keyring.backend] -> Loading macOS
2020-11-08 21:40:17,426 [INFO] [keyring.backend] -> Loading KWallet
2020-11-08 21:40:17,426 [INFO] [keyring.backend] -> Loading SecretService
2020-11-08 21:40:17,426 [INFO] [keyring.backend] -> Loading Windows
2020-11-08 21:40:17,426 [INFO] [keyring.backend] -> Loading chainer
2020-11-08 21:40:17,426 [INFO] [keyring.backend] -> Loading macOS
2020-11-08 21:40:17,456 [INFO] [spyder.plugins.console.plugin] -> Initializing...
2020-11-08 21:40:17,514 [INFO] [spyder.app.mainwindow] -> Starting code completion manager...
2020-11-08 21:40:17,580 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Registering lsp
2020-11-08 21:40:17,580 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Registering fallback
2020-11-08 21:40:17,582 [DEBUG] [spyder.plugins.completion.fallback.actor] -> Fallback plugin starting...
2020-11-08 21:40:17,609 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Registering kite
2020-11-08 21:40:17,610 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Registering snippets
2020-11-08 21:40:17,610 [DEBUG] [spyder.plugins.completion.kite.client] -> Starting Kite HTTP session...
2020-11-08 21:40:17,611 [DEBUG] [urllib3.connectionpool] -> Starting new HTTP connection (1): 127.0.0.1:46624
2020-11-08 21:40:17,612 [DEBUG] [spyder.plugins.completion.kite.plugin] -> Kite client is available for ['python']
2020-11-08 21:40:17,612 [INFO] [spyder.app.mainwindow] -> Loading working directory...
2020-11-08 21:40:17,613 [DEBUG] [spyder.plugins.completion.snippets.actor] -> Snippets plugin starting...
2020-11-08 21:40:17,613 [DEBUG] [spyder.plugins.completion.snippets.actor] -> Updating snippets...
2020-11-08 21:40:17,628 [INFO] [spyder.app.mainwindow] -> Loading help...
2020-11-08 21:40:17,636 [DEBUG] [spyder.plugins.editor.panels.manager] -> adding panel EdgeLine at floating
2020-11-08 21:40:17,636 [DEBUG] [spyder.plugins.editor.panels.manager] -> panel EdgeLine installed
2020-11-08 21:40:17,637 [DEBUG] [spyder.plugins.editor.panels.manager] -> adding panel IndentationGuide at floating
2020-11-08 21:40:17,637 [DEBUG] [spyder.plugins.editor.panels.manager] -> panel IndentationGuide installed
2020-11-08 21:40:17,637 [DEBUG] [spyder.plugins.editor.panels.manager] -> adding panel FoldingPanel at left
2020-11-08 21:40:17,637 [DEBUG] [spyder.plugins.editor.panels.manager] -> panel FoldingPanel installed
2020-11-08 21:40:17,638 [DEBUG] [spyder.plugins.editor.panels.manager] -> adding panel DebuggerPanel at left
2020-11-08 21:40:17,638 [DEBUG] [spyder.plugins.editor.panels.manager] -> panel DebuggerPanel installed
2020-11-08 21:40:17,639 [DEBUG] [spyder.plugins.editor.panels.manager] -> adding panel LineNumberArea at left
2020-11-08 21:40:17,639 [DEBUG] [spyder.plugins.editor.panels.manager] -> panel LineNumberArea installed
2020-11-08 21:40:17,639 [DEBUG] [spyder.plugins.editor.panels.manager] -> adding panel ClassFunctionDropdown at top
2020-11-08 21:40:17,640 [DEBUG] [spyder.plugins.editor.panels.manager] -> panel ClassFunctionDropdown installed
2020-11-08 21:40:17,640 [DEBUG] [spyder.plugins.editor.panels.manager] -> adding panel ScrollFlagArea at right
2020-11-08 21:40:17,640 [DEBUG] [spyder.plugins.editor.panels.manager] -> panel ScrollFlagArea installed
2020-11-08 21:40:17,645 [DEBUG] [spyder.plugins.editor.extensions.manager] -> adding extension CloseQuotesExtension
2020-11-08 21:40:17,645 [DEBUG] [spyder.plugins.editor.extensions.manager] -> adding extension SnippetsExtension
2020-11-08 21:40:17,645 [DEBUG] [spyder.plugins.editor.extensions.manager] -> adding extension CloseBracketsExtension
2020-11-08 21:40:17,646 [DEBUG] [spyder.api.panel] -> DebuggerPanel visibility changed
2020-11-08 21:40:17,646 [DEBUG] [spyder.api.panel] -> FoldingPanel visibility changed
2020-11-08 21:40:17,646 [DEBUG] [spyder.api.panel] -> ScrollFlagArea visibility changed
2020-11-08 21:40:17,646 [DEBUG] [spyder.api.panel] -> EdgeLine visibility changed
2020-11-08 21:40:17,646 [DEBUG] [spyder.api.panel] -> IndentationGuide visibility changed
2020-11-08 21:40:17,649 [DEBUG] [spyder.api.panel] -> LineNumberArea visibility changed
2020-11-08 21:40:17,651 [DEBUG] [spyder.api.panel] -> ClassFunctionDropdown visibility changed
2020-11-08 21:40:17,725 [INFO] [spyder.app.mainwindow] -> Loading outline explorer...
2020-11-08 21:40:17,746 [INFO] [spyder.app.mainwindow] -> Loading editor...
2020-11-08 21:40:17,794 [INFO] [spyder.app.mainwindow] -> Loading namespace browser...
2020-11-08 21:40:17,801 [INFO] [spyder.app.mainwindow] -> Loading figure browser...
2020-11-08 21:40:17,808 [INFO] [spyder.app.mainwindow] -> Loading history plugin...
2020-11-08 21:40:17,817 [INFO] [spyder.app.mainwindow] -> Loading IPython console...
2020-11-08 21:40:17,958 [INFO] [spyder.app.mainwindow] -> Loading file explorer...
2020-11-08 21:40:17,970 [INFO] [spyder.app.mainwindow] -> Loading online help...
2020-11-08 21:40:17,972 [DEBUG] [spyder.utils.external.binaryornot.check] -> is_binary: '/home/elkins/.bash_history'
2020-11-08 21:40:17,972 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> nontext_ratio1: 0.0
2020-11-08 21:40:17,972 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> nontext_ratio2: 1.0
2020-11-08 21:40:17,972 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> is_likely_binary: False
2020-11-08 21:40:17,972 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> detected_encoding: {'encoding': 'ascii', 'confidence': 1.0, 'language': ''}
2020-11-08 21:40:17,972 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> failure: decodable_as_unicode: False
2020-11-08 21:40:17,973 [DEBUG] [spyder.utils.external.binaryornot.check] -> is_binary: '/home/elkins/docker_help.txt'
2020-11-08 21:40:17,973 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> nontext_ratio1: 0.0
2020-11-08 21:40:17,974 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> nontext_ratio2: 1.0
2020-11-08 21:40:17,974 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> is_likely_binary: False
2020-11-08 21:40:17,974 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> detected_encoding: {'encoding': 'ascii', 'confidence': 1.0, 'language': ''}
2020-11-08 21:40:17,974 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> failure: decodable_as_unicode: False
2020-11-08 21:40:17,974 [DEBUG] [spyder.utils.external.binaryornot.check] -> is_binary: '/home/elkins/.xsession-errors.old'
2020-11-08 21:40:17,974 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> nontext_ratio1: 0.0
2020-11-08 21:40:17,974 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> nontext_ratio2: 1.0
2020-11-08 21:40:17,974 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> is_likely_binary: False
2020-11-08 21:40:17,974 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> detected_encoding: {'encoding': 'ascii', 'confidence': 1.0, 'language': ''}
2020-11-08 21:40:17,975 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> failure: decodable_as_unicode: False
2020-11-08 21:40:17,976 [DEBUG] [spyder.utils.external.binaryornot.check] -> is_binary: '/home/elkins/emrcalc.png'
2020-11-08 21:40:17,976 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> nontext_ratio1: 0.6533203125
2020-11-08 21:40:17,976 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> nontext_ratio2: 0.591796875
2020-11-08 21:40:17,976 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> is_likely_binary: False
2020-11-08 21:40:18,031 [DEBUG] [chardet.charsetprober] -> SHIFT_JIS Japanese prober hit error at byte 48
2020-11-08 21:40:18,031 [DEBUG] [chardet.charsetprober] -> EUC-JP Japanese prober hit error at byte 0
2020-11-08 21:40:18,031 [DEBUG] [chardet.charsetprober] -> GB2312 Chinese prober hit error at byte 33
2020-11-08 21:40:18,031 [DEBUG] [chardet.charsetprober] -> EUC-KR Korean prober hit error at byte 0
2020-11-08 21:40:18,031 [DEBUG] [chardet.charsetprober] -> CP949 Korean prober hit error at byte 32
2020-11-08 21:40:18,031 [DEBUG] [chardet.charsetprober] -> Big5 Chinese prober hit error at byte 0
2020-11-08 21:40:18,031 [DEBUG] [chardet.charsetprober] -> EUC-TW Taiwan prober hit error at byte 0
2020-11-08 21:40:18,036 [DEBUG] [chardet.charsetprober] -> windows-1251 Russian confidence = 0.03936884503456672
2020-11-08 21:40:18,036 [DEBUG] [chardet.charsetprober] -> KOI8-R Russian confidence = 0.00490511070311503
2020-11-08 21:40:18,036 [DEBUG] [chardet.charsetprober] -> ISO-8859-5 Russian confidence = 0.08561570129744947
2020-11-08 21:40:18,036 [DEBUG] [chardet.charsetprober] -> MacCyrillic Russian confidence = 0.04134290791232451
2020-11-08 21:40:18,036 [DEBUG] [chardet.charsetprober] -> IBM866 Russian confidence = 0.05688664618974949
2020-11-08 21:40:18,036 [DEBUG] [chardet.charsetprober] -> IBM855 Russian confidence = 0.05204801191613862
2020-11-08 21:40:18,036 [DEBUG] [chardet.charsetprober] -> ISO-8859-7 Greek confidence = 0.08598153967744969
2020-11-08 21:40:18,036 [DEBUG] [chardet.charsetprober] -> windows-1253 Greek confidence = 0.08777282175406324
2020-11-08 21:40:18,036 [DEBUG] [chardet.charsetprober] -> ISO-8859-5 Bulgairan confidence = 0.05947730801189372
2020-11-08 21:40:18,036 [DEBUG] [chardet.charsetprober] -> windows-1251 Bulgarian confidence = 0.045485032890945465
2020-11-08 21:40:18,036 [DEBUG] [chardet.charsetprober] -> TIS-620 Thai confidence = 0.035161100580914775
2020-11-08 21:40:18,036 [DEBUG] [chardet.charsetprober] -> ISO-8859-9 Turkish confidence = 0.021092788047921494
2020-11-08 21:40:18,036 [DEBUG] [chardet.charsetprober] -> windows-1255 Hebrew confidence = 0.0
2020-11-08 21:40:18,036 [DEBUG] [chardet.charsetprober] -> windows-1255 Hebrew confidence = 0.03749523666087076
2020-11-08 21:40:18,036 [DEBUG] [chardet.charsetprober] -> windows-1255 Hebrew confidence = 0.03124603055072564
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> no probers hit minimum threshold
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> utf-8  confidence = 0.010000000000000009
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> SHIFT_JIS Japanese confidence = 0.01
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> EUC-JP Japanese confidence = 0.01
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> GB2312 Chinese confidence = 0.01
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> EUC-KR Korean confidence = 0.01
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> CP949 Korean confidence = 0.01
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> Big5 Chinese confidence = 0.01
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> EUC-TW Taiwan confidence = 0.01
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> windows-1251 Russian confidence = 0.03936884503456672
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> KOI8-R Russian confidence = 0.00490511070311503
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> ISO-8859-5 Russian confidence = 0.08561570129744947
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> MacCyrillic Russian confidence = 0.04134290791232451
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> IBM866 Russian confidence = 0.05688664618974949
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> IBM855 Russian confidence = 0.05204801191613862
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> ISO-8859-7 Greek confidence = 0.08598153967744969
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> windows-1253 Greek confidence = 0.08777282175406324
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> ISO-8859-5 Bulgairan confidence = 0.05947730801189372
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> windows-1251 Bulgarian confidence = 0.045485032890945465
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> TIS-620 Thai confidence = 0.035161100580914775
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> ISO-8859-9 Turkish confidence = 0.021092788047921494
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> windows-1255 Hebrew confidence = 0.0
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> windows-1255 Hebrew confidence = 0.03749523666087076
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> windows-1255 Hebrew confidence = 0.03124603055072564
2020-11-08 21:40:18,036 [DEBUG] [chardet.universaldetector] -> windows-1255 Hebrew confidence = 0.03124603055072564
2020-11-08 21:40:18,036 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> detected_encoding: {'encoding': None, 'confidence': 0.0, 'language': None}
2020-11-08 21:40:18,036 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> failure: decodable_as_unicode: False
2020-11-08 21:40:18,036 [DEBUG] [spyder.utils.external.binaryornot.helpers] -> has nulls:True
2020-11-08 21:40:18,045 [INFO] [spyder.app.mainwindow] -> Loading project explorer...
Traceback (most recent call last):
  File "/home/elkins/.local/lib/python3.8/site-packages/astroid/astpeephole.py", line 17, in <module>
    _TYPES = (_ast.Str, _ast.Bytes)
AttributeError: module '_ast' has no attribute 'Str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elkins/.local/bin/spyder", line 8, in <module>
    sys.exit(main())
  File "/home/elkins/.local/lib/python3.8/site-packages/spyder/app/start.py", line 211, in main
    mainwindow.main(options, args)
  File "/home/elkins/.local/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 3685, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/elkins/.local/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 3571, in run_spyder
    main.setup()
  File "/home/elkins/.local/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 1009, in setup
    module = importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/elkins/.local/lib/python3.8/site-packages/spyder/plugins/pylint/__init__.py", line 14, in <module>
    from .plugin import Pylint as PLUGIN_CLASS
  File "/home/elkins/.local/lib/python3.8/site-packages/spyder/plugins/pylint/plugin.py", line 29, in <module>
    from spyder.plugins.pylint.confpage import (PylintConfigPage,
  File "/home/elkins/.local/lib/python3.8/site-packages/spyder/plugins/pylint/confpage.py", line 16, in <module>
    from spyder.plugins.pylint.widgets.pylintgui import PylintWidget
  File "/home/elkins/.local/lib/python3.8/site-packages/spyder/plugins/pylint/widgets/pylintgui.py", line 37, in <module>
    from spyder.plugins.pylint.utils import get_pylintrc_path
  File "/home/elkins/.local/lib/python3.8/site-packages/spyder/plugins/pylint/utils.py", line 16, in <module>
    import pylint.config
  File "/home/elkins/.local/lib/python3.8/site-packages/pylint/config.py", line 52, in <module>
    from pylint import utils
  File "/home/elkins/.local/lib/python3.8/site-packages/pylint/utils.py", line 52, in <module>
    from astroid import nodes, Module
  File "/home/elkins/.local/lib/python3.8/site-packages/astroid/__init__.py", line 67, in <module>
    from astroid.builder import parse, extract_node
  File "/home/elkins/.local/lib/python3.8/site-packages/astroid/builder.py", line 26, in <module>
    from astroid import rebuilder
  File "/home/elkins/.local/lib/python3.8/site-packages/astroid/rebuilder.py", line 17, in <module>
    from astroid import astpeephole
  File "/home/elkins/.local/lib/python3.8/site-packages/astroid/astpeephole.py", line 19, in <module>
    _TYPES = (_ast.Str, )
AttributeError: module '_ast' has no attribute 'Str'

```

## Versions

* Spyder version: 4.2.0
* Python version: 3.8.6
* Qt version: 5.14.2
* PyQt version: 
```
PyQt5                         5.12.3
PyQt5-sip                     12.8.1
PyQtWebEngine                 5.12.1
QtAwesome                     0.7.3
qtconsole                     4.7.7
QtPy                          1.9.0
```
* Operating System name/version: Xubuntu 20.10

### Work-around

```pip install -U git+https://github.com/PyCQA/astroid```  #  pip out of date?
```pip install -U pylint``` # Stopped pylint complaint about astroid version.
```spyder```

*** Successful launch of Spyder ***

**Comment by texadactyl** [comment]
Verified: interim astroid problem
