### ISSUE TITLE
Spyder console isn't working for a certain account group

### ISSUE THREAD

**Issue by Masameme** [spyder-ide/spyder#14201]
## Problem Description

Hello, I have a certain problem with Spyder and it seems kinda unique for my case. I tried to install Anaconda in a whole computer room. We have 3 different accounts groups. 1.Admins, 2.teachers and 3.students. I installed Anaconda with the admin group, so any other group can use it too. Now the problem, after installing Anaconda I can use Spyder with the admin and teacher group with it whole features. But the student group doesn't have any access to the Ipython console in Spyder. I already gave the student group for a short time admin privileges but that didn't work. I thought it could have something to do with the installation path so I tried different ones too but all with the same result. I also searched here similiar problems and fixes and tried them all but it still shows the same error over and over. 

### What steps reproduce the problem?

1. Install Anaconda as admin
2. put it into folder C
3. run spyder as student

### What is the expected output? What do you see instead?

Student group should work normal with the Ipython console. But the following same error shows after many different tries and fixes.

### Paste Traceback/Error Below (if applicable)

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\start.py", line 205, in main
mainwindow.main()
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3651, in main
mainwindow = run_spyder(app, options, args)
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3526, in run_spyder
main.setup()
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 945, in setup
from spyder.plugins.ipythonconsole.plugin import IPythonConsole
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 46, in 
from spyder.plugins.ipythonconsole.widgets import (ClientWidget,
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\__init__.py", line 16, in 
from .debugging import DebuggingWidget
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 22, in 
from IPython.core.inputtransformer2 import TransformerManager
ModuleNotFoundError: No module named 'IPython.core.inputtransformer2'

## Versions

* Spyder version: 4.1.4
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)

I hope somebody can help me. if there are any questions I try to answer them but im kinda fresh in my job so don't expect much from me. Anyways already thank you.

**Comment by Masameme** [comment]
Hello again,

I tried to update Anaconda with Anaconda Prompt already but I saw right now that the Error message is a different one after updating everything with "conda update --all"

Here the traceback message

Traceback (most recent call last):
File "C:\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole\plugin.py", line 1223, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 309, in start_kernel
kernel_cmd, kw = self.pre_start_kernel(**kw)
File "C:\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 256, in pre_start_kernel
self.write_connection_file()
File "C:\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 468, in write_connection_file
self.connection_file, cfg = write_connection_file(self.connection_file,
File "C:\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 138, in write_connection_file
with secure_write(fname) as f:
File "C:\Anaconda3\lib\contextlib.py", line 113, in __enter__
return next(self.gen)
File "C:\Anaconda3\lib\site‑packages\jupyter_core\paths.py", line 435, in secure_write
win32_restrict_file_to_user(fname)
File "C:\Anaconda3\lib\site‑packages\jupyter_core\paths.py", line 377, in win32_restrict_file_to_user
win32security.SetFileSecurity(fname, win32security.DACL_SECURITY_INFORMATION, sd)
pywintypes.error: (5, 'SetFileSecurity', 'Zugriff verweigert')

**Comment by ccordoba12** [comment]
Hey @Masameme, thanks for reporting. Please reinstall Anaconda and then run

    conda update ipython

That should fix the error you were having.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
