### ISSUE TITLE
Spyder Kernel isn't Starting

### ISSUE THREAD

**Issue by dassanjeev** [spyder-ide/spyder#14233]
## Description

**What steps will reproduce the problem?**

1. after starting the spyder ide it gives me this pop up message and the Ipython kernel isn't starting

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\spyder\plugins\ipythonconsole.py", line 991, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1027, in connect_client_to_kernel
    kc.start_channels(shell=True, iopub=True)
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\qtconsole\kernel_mixins.py", line 47, in start_channels
    super(QtKernelClientMixin, self).start_channels(*args, **kw)
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\jupyter_client\threaded.py", line 209, in start_channels
    self.shell_channel._inspect = self._check_kernel_info_reply
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\jupyter_client\client.py", line 143, in shell_channel
    socket, self.session, self.ioloop
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\jupyter_client\threaded.py", line 202, in ioloop
    self._ioloop = ioloop.IOLoop()
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\tornado\util.py", line 312, in __new__
    instance.initialize(*args, **init_kwargs)
  File "C:\U

**Comment by ccordoba12** [comment]
Hey @dassanjeev, thanks for reporting. This problem could be fixed in our latest version. Please update by closing Spyder, opening the Anaconda Prompt and running there

    conda update anaconda
    conda install spyder=4.1.5

**Comment by dassanjeev** [comment]
![Error](https://user-images.githubusercontent.com/70071365/99287328-1c32e100-2860-11eb-85a9-342f7a66fe0f.PNG)
This is the error i am getting now it says Last session of Spyder was crashed

**Comment by ccordoba12** [comment]
That error dialog was removed several versions ago, which means you didn't install our latest version correctly.

**Comment by dassanjeev** [comment]
But it was working fine .
Like first the error came 
and then I tried to fix it so it started showing the crashed Popup
is there a way where i can install the same version of spyder
cause i am using python 3.5 
and i want it for python 3.5 only 

The Spyder of 3.7 work perfectly fine 
but 3.5 isnt .

**Comment by dassanjeev** [comment]
This is the Error Which is coming...






Traceback (most recent call last):
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\spyde
r\app\mainwindow.py", line 3181, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\spyde
r\app\mainwindow.py", line 3057, in run_spyder
    main.setup()
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\spyde
r\app\mainwindow.py", line 896, in setup
    from spyder.plugins.ipythonconsole import IPythonConsole
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\spyde
r\plugins\ipythonconsole.py", line 59, in <module>
    from spyder.widgets.ipythonconsole import ClientWidget
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\spyde
r\widgets\ipythonconsole\__init__.py", line 12, in <module>
    from .debugging import DebuggingWidget
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\spyde
r\widgets\ipythonconsole\debugging.py", line 17, in <module>
    from qtconsole.rich_jupyter_widget import RichJupyterWidget
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\qtcon
sole\rich_jupyter_widget.py", line 14, in <module>
    from .jupyter_widget import JupyterWidget
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\qtcon
sole\jupyter_widget.py", line 20, in <module>
    from IPython.lib.lexers import IPythonLexer, IPython3Lexer
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\IPyth
on\__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\IPyth
on\terminal\embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\IPyth
on\terminal\interactiveshell.py", line 32, in <module>
    from .debugger import TerminalPdb, Pdb
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\IPyth
on\terminal\debugger.py", line 6, in <module>
    from IPython.core.completer import IPCompleter
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\IPyth
on\core\completer.py", line 146, in <module>
    import jedi
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\jedi\
__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, \
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\jedi\
api\__init__.py", line 15, in <module>
    import parso
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\parso
\__init__.py", line 41, in <module>
    from parso.parser import ParserSyntaxError
  File "C:\Users\sanjeev\anaconda3\envs\virtual_platform\lib\site-packages\parso
\parser.py", line 113
    node_map: Dict[str, type] = {}
            ^
SyntaxError: invalid syntax

**Comment by ccordoba12** [comment]
Please recreate your `virtual_platform` because it seems broken.

**Comment by dassanjeev** [comment]
Okay thanks will uninstall the environment and do it again 
thank you
But what are the chances that because i pip installed in it so it crashed?? 
does it work that way??

**Comment by ccordoba12** [comment]
> But what are the chances that because i pip installed in it so it crashed??

Yes, that's the problem. Please see [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) on why you must not mix pip and conda packages.

I'm going to close this issue because this is not a problem with Spyder but with the way you installed it.
