### ISSUE TITLE
ModuleNotFoundError: No module named 'IPython.core.inputtransformer2'

### ISSUE THREAD

**Issue by juz4karen** [spyder-ide/spyder#14232]
Hi there,

I downloaded Spyder installer at first, tried to import model, prompted error that it could not import cobra and my model (I realized that I crafted my model in virtual env, python 3.6.

Hence, I do the folloowing
**conda activate py3.6
conda install spyder
conda install spyder-kernels
spyder**

and launch spyder in terminal, prompt error as below. For your information, I've changed the python interpreter to the virtual env py3.6. Kindly assist for the issue. 

Traceback (most recent call last):
File "/Users/karenchung/miniconda3/envs/py3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/Users/karenchung/miniconda3/envs/py3.6/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/Users/karenchung/miniconda3/envs/py3.6/lib/python3.6/site‑packages/spyder_kernels/console/__main__.py", line 23, in 
start.main()
File "/Users/karenchung/miniconda3/envs/py3.6/lib/python3.6/site‑packages/spyder_kernels/console/start.py", line 253, in main
import_spydercustomize()
File "/Users/karenchung/miniconda3/envs/py3.6/lib/python3.6/site‑packages/spyder_kernels/console/start.py", line 43, in import_spydercustomize
import spydercustomize
File "/Users/karenchung/miniconda3/envs/py3.6/lib/python3.6/site‑packages/spyder_kernels/customize/spydercustomize.py", line 31, in 
from spyder_kernels.customize.spyderpdb import SpyderPdb
File "/Users/karenchung/miniconda3/envs/py3.6/lib/python3.6/site‑packages/spyder_kernels/customize/spyderpdb.py", line 23, in 
from IPython.core.inputtransformer2 import TransformerManager
ModuleNotFoundError: No module named 'IPython.core.inputtransformer2'

## Versions
* Spyder version: 4.2.0
* Python version: 3.6.11
* Operating System name/version: MacOS

**Comment by impact27** [comment]
Could you update IPython and try again?

**Comment by juz4karen** [comment]
I'm sorry but how do I update IPython?

**Comment by impact27** [comment]
```
conda update conda
conda update ipython
```

**Comment by juz4karen** [comment]
yes thanks, it solved. Thank you so much!
