### ISSUE TITLE
Spyder crashed during last session

### ISSUE THREAD

**Issue by clargrss** [spyder-ide/spyder#14254]
Hi,

I'm trying to open Spyder on a Clearmap environment. But as other people, I get the "spyder crashed during last session" message. I followed the advise on the page for the same problem, but having MacOS, I cannot continue further. The only actions I can execute are not working for me. 

During installing spyder, I created my ClearMap environment in python 2,7, however, I did have only python 3,8 on my laptop at this time. Can this be an issue? Because  **pip install --upgrade spyder** is showing an error saying: **ERROR: Package 'numpydoc' requires a different Python: 2.7.18 not in '>=3.5'**

This is the error message I got when I try to open spyder on my environment: 
Traceback (most recent call last):
  File "/Users/clara/opt/anaconda3/envs/clearmap_env/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "/Users/clara/opt/anaconda3/envs/clearmap_env/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 3557, in run_spyder
    main = MainWindow(options)
  File "/Users/clara/opt/anaconda3/envs/clearmap_env/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 426, in __init__
    from spyder.preferences.runconfig import RunConfigPage
  File "/Users/clara/opt/anaconda3/envs/clearmap_env/lib/python2.7/site-packages/spyder/preferences/runconfig.py", line 482, in <module>
    class RunConfigPage(GeneralConfigPage):
  File "/Users/clara/opt/anaconda3/envs/clearmap_env/lib/python2.7/site-packages/spyder/preferences/runconfig.py", line 487, in RunConfigPage
    ICON = ima.icon('run')
  File "/Users/clara/opt/anaconda3/envs/clearmap_env/lib/python2.7/site-packages/spyder/utils/icon_manager.py", line 394, in icon
    directory=_resource['directory'])
  File "/Users/clara/opt/anaconda3/envs/clearmap_env/lib/python2.7/site-packages/qtawesome/__init__.py", line 178, in load_font
    return _instance().load_font(prefix, ttf_filename, charmap_filename, directory)
  File "/Users/clara/opt/anaconda3/envs/clearmap_env/lib/python2.7/site-packages/qtawesome/__init__.py", line 54, in _instance
    'materialdesignicons-webfont-charmap.json')
  File "/Users/clara/opt/anaconda3/envs/clearmap_env/lib/python2.7/site-packages/qtawesome/iconic_font.py", line 206, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)

Can someone help me please?

**Comment by dalthviz** [comment]
Hi @clargrss please install QtAwesome `0.7.3` running from the terminal something like `conda install qtawesome=0.7.3`. For more info about the support of Python 2.7 you can check https://github.com/spyder-ide/spyder/issues/13962

**Comment by clargrss** [comment]
**conda install qtawesome=0.7.3**
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - qtawesome=0.7.3

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

The same problem is still occurring. Can it be a possibility that I can just not run spyder in a ClearMap environment on the MacOS Terminal?

**Comment by dalthviz** [comment]
@clargrss sorry, please run something like this instead `conda install qtawesome=0.7.3 -c conda-forge` (I forgot the channel part in the command). Let us know if that helps :)

**Comment by clargrss** [comment]
It worked! Problem solved
Thank you very much 👍  :)
