### ISSUE TITLE
Was just copying and pasting into a file.....

### ISSUE THREAD

**Issue by jeremymatt** [spyder-ide/spyder#14286]
### What steps will reproduce the problem?

First time I've run this install of Anaconda/spyder.  NOt sure what the pattern is

### Traceback
```python-traceback
  File "C:\Users\jmatt\Anaconda3\envs\keras\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1520, in handle_go_to_definition
    def_range = position['range']
TypeError: list indices must be integers or slices, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jmatt\Anaconda3\envs\keras\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "C:\Users\jmatt\Anaconda3\envs\keras\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Users\jmatt\Anaconda3\envs\keras\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Users\jmatt\Anaconda3\envs\keras\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "C:\Users\jmatt\Anaconda3\envs\keras\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\jmatt\Anaconda3\envs\keras\lib\site-packages\spyder\app\start.py", line 212, in main
    mainwindow.main(options, args)
  File "C:\Users\jmatt\Anaconda3\envs\keras\lib\site-packages\spyder\app\mainwindow.py", line 3685, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\jmatt\Anaconda3\envs\keras\lib\site-packages\spyder\app\mainwindow.py", line 3612, in run_spyder
    app.exec_()
  File "C:\Users\jmatt\Anaconda3\envs\keras\lib\site-packages\spyder\plugins\completion\languageserver\client.py", line 513, in on_msg_received
    self.req_reply[req_id](None, {'params': []})
  File "C:\Users\jmatt\Anaconda3\envs\keras\lib\site-packages\spyder\plugins\completion\languageserver\plugin.py", line 561, in receive_response
    self.COMPLETION_CLIENT_NAME, req_id, response)
  File "C:\Users\jmatt\Anaconda3\envs\keras\lib\site-packages\spyder\plugins\completion\plugin.py", line 125, in receive_response
    self.howto_send_to_codeeditor(req_id)
  File "C:\Users\jmatt\Anaconda3\envs\keras\lib\site-packages\spyder\plugins\completion\plugin.py", line 177, in howto_send_to_codeeditor
    self.skip_and_send_to_codeeditor(req_id)
  File "C:\Users\jmatt\Anaconda3\envs\keras\lib\site-packages\spyder\plugins\completion\plugin.py", line 211, in skip_and_send_to_codeeditor
    self.gather_and_send_to_codeeditor(request_responses)
  File "C:\Users\jmatt\Anaconda3\envs\keras\lib\site-packages\spyder\plugins\completion\plugin.py", line 279, in gather_and_send_to_codeeditor
    response_instance.handle_response(req_type, responses)
  File "C:\Users\jmatt\Anaconda3\envs\keras\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1068, in handle_response
    handler(params)
  File "C:\Users\jmatt\Anaconda3\envs\keras\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1537, in handle_go_to_definition
    "Error when processing go to definition")
  File "C:\Users\jmatt\Anaconda3\envs\keras\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1099, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
```

## Versions

* Spyder version: 4.2.0 
* Python version: 3.7.8
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=4.0                   :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.3 (OK)
pygments >=2.0                  :  2.7.2 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.1 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.1.1 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=4.7.7               :  4.7.7 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  49.6.0.post20201009 (OK)
sphinx >=0.6.6                  :  3.3.1 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.4 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.2.2 (OK)
numpy >=1.7                     :  1.14.6 (OK)
pandas >=1.1.1                  :  1.0.5 (NOK)
scipy >=0.17.0                  :  1.5.2 (OK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @jeremymatt, thanks for reporting. It seems the error was generated because you were trying to get the definition of an object in the editor (by doing `Ctrl+ Right click` or `Ctrl+G` on a word) and the response was not the right one.

Could you verify if that's the case and try to reproduce the error? Otherwise it'll be very hard for us to understand what's happening in your case.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
