### ISSUE TITLE
Windows installer for Python 3.3 doesn't finish correctly

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1429]
_From [WayneNil...@gmail.com](https://code.google.com/u/106860249208932910270/) on 2013-06-05T07:54:49Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. have a computer with windows 7 64 bit, python 3.3 64 bit 
2. download the file "spyder-2.3.0dev1.win-amd64-py3.3.exe"
3. run
4. crash during postinstall script run What is the expected output? What do you see instead? Expected: successful install
Saw: "A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available." What version of the product are you using? On what operating system? ^^ 

Please provide any additional information below

. Let me know if you want any other information. I am very excited to try out this IDE but I really need 64bit python 3.3 support.

**Attachment:** [Untitled.png](http://code.google.com/p/spyderlib/issues/detail?id=1429)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1429_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-06-07T09:23:38Z_

What Python distribution are you using? WinPython perhaps?

Jed, could you verify that the installer is working correctly?

**Owner:** jed.lud...@gmail.com

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-06-07T10:54:50Z_

I'm not going to be much help with this one since I don't have a "standard" Python 3.3 install on Windows. I only have WinPython 3.3.2.0, and there really isn't an install process to go through there. Spyder basically comes pre-installed into the WinPython environment. I can verify that 2.3.0dev1 works fine inside of WinPython under Python 3.3.

**Owner:** ---

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-06-29T06:32:42Z_

issue #1410 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-06-29T06:34:05Z_

**Summary:** Windows installer for Python 3.3 doesn't finish correctly  \<span class="oldvalue"> (was: 2.3 Installer Crash Python 3.3 64 bit) \</span>  
  **Labels:** Cat-Miscelleneous MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [skelts...@gmail.com](https://code.google.com/u/105078940574734890255/) on 2013-06-30T06:05:33Z_

I tried to run manually "spyder_win_post_install.py" -file (after the failed installation) and got this message:

Traceback (most recent call last):
  File "<string>", line 420, in run_nodebug
  File "C:\Python33\scripts\spyder_win_post_install.py", line 8, in \<module>
    import _winreg as winreg
ImportError: No module named '_winreg'

I replaced "_winreg" with "winreg" (I guess it is changed in python 3.x) and run the code again - this time there wasn't any error messages. I run the installer again and it finished without error messages, but there aren't any start menu entries/shortcuts (should there be?). I'm still not completely sure if it's installed correctly. I attached two pictures (the ending lines of failed and succesful installation)

WinXP32, Python 3.3.2
(previously reported in " issue #1410 , post 2")

**Attachment:** [spyder installation.JPG spyder installation finished.JPG](http://code.google.com/p/spyderlib/issues/detail?id=1429#hc5)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-06-30T09:55:56Z_

Ok, this is very nice, thanks for tracking down the problem!

For reference, this is the SO post which ensures that _winreg has been renamed to winreg in Python 3: http://stackoverflow.com/questions/4320761/importerror-no-module-named-winreg-python3

**Status:** Accepted  
  **Labels:** -Priority-Medium Priority-Critical

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-09T12:38:33Z_

issue #1491 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-11T07:58:58Z_

Pierre, it's important to get this one fixed too before your next WinPython release (just another entry in py3compat)

**Cc:** pierre.raybaut

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-08-11T09:22:57Z_

This issue was updated by revision 73ef7dd090af .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-08-11T09:32:08Z_

You're very welcome to test the new v2.3.0dev4 installers I've just uploaded.
