### ISSUE TITLE
Incompatible spyder kernels after updating spyder to 4.2.0

### ISSUE THREAD

**Issue by tsbankole** [spyder-ide/spyder#14351]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

incompatible spyder kernels after updating spyder

### What steps reproduce the problem?

1. On  python 3.7.0, install spyder 4.2.0 using pip
2. 
3. 

### What is the expected output? What do you see instead?
spyder 4.2.0 installs spyder-kernels 1.10.1 however the following error message is displayed during the pip install

*-pyder 3.3.6 requires spyder-kernels<1.0,>=0.5.0, but you'll have spyder-kernels 1.10.0 which is incompatible.*

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE
An error ocurred while starting the kernel
Traceback (most recent call last):
File "c:\users\username\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "c:\users\username\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\spyder_kernels\console\__main__.py", line 23, in 
start.main()
File "c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\spyder_kernels\console\start.py", line 253, in main
import_spydercustomize()
File "c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\spyder_kernels\console\start.py", line 43, in import_spydercustomize
import spydercustomize
File "c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 36, in 
from IPython.core.inputtransformer2 import (
ImportError: cannot import name 'leading_empty_lines' from 'IPython.core.inputtransformer2' (c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\IPython\core\inputtransformer2.py)
Traceback (most recent call last):
File "c:\users\username\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "c:\users\username\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\spyder_kernels\console\__main__.py", line 23, in 
start.main()
File "c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\spyder_kernels\console\start.py", line 253, in main
import_spydercustomize()
File "c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\spyder_kernels\console\start.py", line 43, in import_spydercustomize
import spydercustomize
File "c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 36, in 
from IPython.core.inputtransformer2 import (
ImportError: cannot import name 'leading_empty_lines' from 'IPython.core.inputtransformer2' (c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\IPython\core\inputtransformer2.py)
Traceback (most recent call last):
File "c:\users\username\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "c:\users\username\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\spyder_kernels\console\__main__.py", line 23, in 
start.main()
File "c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\spyder_kernels\console\start.py", line 253, in main
import_spydercustomize()
File "c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\spyder_kernels\console\start.py", line 43, in import_spydercustomize
import spydercustomize
File "c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 36, in 
from IPython.core.inputtransformer2 import (
ImportError: cannot import name 'leading_empty_lines' from 'IPython.core.inputtransformer2' (c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\IPython\core\inputtransformer2.py)
Traceback (most recent call last):
File "c:\users\username\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "c:\users\username\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\spyder_kernels\console\__main__.py", line 23, in 
start.main()
File "c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\spyder_kernels\console\start.py", line 253, in main
import_spydercustomize()
File "c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\spyder_kernels\console\start.py", line 43, in import_spydercustomize
import spydercustomize
File "c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 36, in 
from IPython.core.inputtransformer2 import (
ImportError: cannot import name 'leading_empty_lines' from 'IPython.core.inputtransformer2' (c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\IPython\core\inputtransformer2.py)
Traceback (most recent call last):
File "c:\users\username\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "c:\users\username\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\spyder_kernels\console\__main__.py", line 23, in 
start.main()
File "c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\spyder_kernels\console\start.py", line 253, in main
import_spydercustomize()
File "c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\spyder_kernels\console\start.py", line 43, in import_spydercustomize
import spydercustomize
File "c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 36, in 
from IPython.core.inputtransformer2 import (
ImportError: cannot import name 'leading_empty_lines' from 'IPython.core.inputtransformer2' (c:\users\username\appdata\local\programs\python\python37\lib\site‑packages\IPython\core\inputtransformer2.py)
```

## Versions

* Spyder version: 4.2.0
* Python version: 3.7.0
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

# Mandatory:
atomicwrites >=1.2.0            :  1.3.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  0.8.0 (OK)
diff_match_patch >=20181111     :  20181111 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=4.0                   :  7.3.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
nbconvert >=4.0                 :  5.4.1 (OK)
numpydoc >=0.6.0                :  0.8.0 (OK)
paramiko >=2.4.0                :  2.7.1 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.7.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.3 (OK)
pygments >=2.0                  :  2.3.1 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.1 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.2.1 (OK)
qdarkstyle >=2.8                :  2.8 (OK)
qtawesome >=0.5.7               :  0.6.0 (OK)
qtconsole >=4.7.7               :  5.0.1 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
setuptools >=39.0.0             :  40.8.0 (OK)
sphinx >=0.6.6                  :  1.8.4 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.4 (OK)
zmq >=17                        :  18.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.17 (OK)
matplotlib >=2.0.0              :  3.1.1 (OK)
numpy >=1.7                     :  1.16.1 (OK)
pandas >=1.1.1                  :  0.25.0 (NOK)
scipy >=0.17.0                  :  1.3.1 (OK)
sympy >=0.7.3                   :  1.4 (OK)

**Comment by steff456** [comment]
Hi @tsbankole,

Can you try to install spyder 4.2 with conda in a new environment to see if there's other dependency that broke this environment?

**Comment by tsbankole** [comment]
I actually fixed this by pip uninstall spyder and then using the windows installer found here
https://github.com/spyder-ide/spyder/releases/latest/download/Spyder_64bit_full.exe
