### ISSUE TITLE
latest version from Debian sid (unstable) not launching at all

### ISSUE THREAD

**Issue by DyslexicAtheist** [spyder-ide/spyder#14448]
## Problem Description

running the latest package from the Debian/sid and it's not working

```
spyder:
  Installed: 3.3.6+dfsg1-5
  Candidate: 3.3.6+dfsg1-5
  Version table:
 *** 3.3.6+dfsg1-5 500
        500 http://ftp.at.debian.org/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
```

```
python3 --version
Python 3.9.1
```

```
$> spyder
Traceback (most recent call last):
  File "/usr/bin/spyder", line 11, in <module>
    load_entry_point('spyder==3.3.6', 'gui_scripts', 'spyder3')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 473, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2447, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/spyder/app/start.py", line 14, in <module>
    import zmq
  File "/usr/lib/python3/dist-packages/zmq/__init__.py", line 55, in <module>
    from zmq import backend
  File "/usr/lib/python3/dist-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/usr/lib/python3/dist-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/usr/lib/python3/dist-packages/zmq/backend/select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/usr/lib/python3/dist-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name 'constants' from partially initialized module 'zmq.backend.cython' (most likely due to a circular import) (/usr/lib/python3/dist-packages/zmq/backend/cython/__init__.py)
```

thanks

**Comment by ccordoba12** [comment]
Thanks for reporting @DyslexicAtheist. Unfortunately, Spyder 3.3.6 is a year and a half old and not supported by us anymore.

So please open an issue with the Debian maintainers to see if they can help you with this problem.
