### ISSUE TITLE
Missing "magic" key for custom color schemes

### ISSUE THREAD

**Issue by trollodel** [spyder-ide/spyder#14440]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
After PR #11101, Spyder refuses to launch because of custom color schemes created before that PR have not the `magic` key (as specified [here](https://github.com/spyder-ide/spyder/blob/4ee7fb3dc8e5794dd5bc88070f6b5195a0e07fa1/spyder/utils/syntaxhighlighters.py#L75)) in their configs. So, when `get_color_scheme` is iterating over scheme keys, it will fail when reaching the `magic` key as it does not exist.
This issue can be workaround by adding the missing field manually in `spyder.ini`.

### What steps reproduce the problem?

1. Create a custom scheme before #11101 and check it is selected
2. Pull changes with #11101
3. Open Spyder

### What is the expected output? What do you see instead?
Spyder refuses to launch with the following traceback.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "bootstrap.py", line 239, in <module>
    start.main()
  File "/home/Public/spyder/spyder/app/start.py", line 227, in main
    mainwindow.main(options, args)
  File "/home/Public/spyder/spyder/app/mainwindow.py", line 4073, in main
    mainwindow = create_window(app, splash, options, args)
  File "/home/Public/spyder/spyder/app/mainwindow.py", line 3930, in create_window
    main.setup()
  File "/home/Public/spyder/spyder/app/mainwindow.py", line 1212, in setup
    self.editor = Editor(self)
  File "/home/Public/spyder/spyder/plugins/editor/plugin.py", line 227, in __init__
    self.editorsplitter = EditorSplitter(self, self,
  File "/home/Public/spyder/spyder/plugins/editor/widgets/editor.py", line 3133, in __init__
    self.register_editorstack_cb(self.editorstack)
  File "/home/Public/spyder/spyder/plugins/editor/plugin.py", line 1378, in register_editorstack
    color_scheme = self.get_color_scheme()
  File "/home/Public/spyder/spyder/api/plugins.py", line 380, in get_color_scheme
    return super(BasePluginWidget, self)._get_color_scheme()
  File "/home/Public/spyder/spyder/plugins/base.py", line 446, in _get_color_scheme
    return get_color_scheme(CONF.get('appearance', 'selected'))
  File "/home/Public/spyder/spyder/config/gui.py", line 114, in get_color_scheme
    color_scheme[key] = CONF.get("appearance", "%s/%s" % (name, key))
  File "/home/Public/spyder/spyder/config/manager.py", line 228, in get
    return config.get(section=section, option=option, default=default)
  File "/home/Public/spyder/spyder/config/user.py", line 976, in get
    return config.get(section=section, option=option, default=default)
  File "/home/Public/spyder/spyder/config/user.py", line 513, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'custom-0/magic' in section: 'appearance'
```

## Versions

* Spyder version: 4.3.0dev0
* Python version: 3.8.5
* Qt version: 5.15.2
* PyQt version: 5.14.1
* Operating System name/version: Linux 5.4.0-58-generic

**Comment by dalthviz** [comment]
Hi @trollodel thank you for the feedback! Probably we need to add a default value in the case the new config key doesn't exits. We will checking this for a future release. Also, if you have an idea of how to fix this let us know :)
