### ISSUE TITLE
Spyder --light is not functioning

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1449]
_From [jdmargul...@gmail.com](https://code.google.com/u/111608738075180764818/) on 2013-06-19T10:45:43Z_

Spyder Version:  2.2.0
Python Version:  2.7.5
Qt Version:      4.8.4, PyQt4 (API v2) 4.9.6 on Windows 7

I've installed WinPython 64bit in C:\WinPython-64bit-2.7.5.1
The directory includes both Spyder.exe and Spyder (light).exe files.
Spyder.exe works fine. On the other hand Spyder (light).exe systematically crashes after briefly opening a shell and then displaying the splash screen for a split second. If I subsequently launch either application I get a warning window advising me to use the --reset option. Doing so does not modify what happens. Any clue?

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1449_

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-06-19T11:29:04Z_

Try to run 2.2.0 from source https://code.google.com/p/spyderlib/wiki/NoteForContributors

**Comment by spyder-issues-migrator** [comment]
_From [jdmargul...@gmail.com](https://code.google.com/u/111608738075180764818/) on 2013-06-23T14:50:30Z_

Well, thank you for trying to help but that sounds too arcane for me, especially with WinPython running its own tidy directory -I don't want to mess that up.

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-06-25T11:57:28Z_

I guess you should file this bug against WinPython - https://code.google.com/p/winpython/ , because Spyder is a Python application, and I don't know how these .exe files are produced.

Can you try running "Spyder (light).exe" from cmd.exe session to see if it outputs anything there?

**Labels:** OpSys-Windows

**Comment by spyder-issues-migrator** [comment]
_From [jdmargul...@gmail.com](https://code.google.com/u/111608738075180764818/) on 2013-06-25T18:24:29Z_

Yes, thanks. Same results from the command prompt, with no output given.

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-06-26T00:35:07Z_

Does --help option works in command prompt? I guess no, but just in case..

**Comment by spyder-issues-migrator** [comment]
_From [jdmargul...@gmail.com](https://code.google.com/u/111608738075180764818/) on 2013-06-26T10:02:11Z_

No that doesn't do anything...

**Comment by spyder-issues-migrator** [comment]
_From [srobert...@gmail.com](https://code.google.com/u/109471414896291480696/) on 2013-06-28T15:21:42Z_

I'm having a similar effect on a FreeBSD 9.1 platform.

Spyder 2.2.0 
Python 2.7.5
py27-qt4-4.10.2

A regular spyder session runs fine. But from a Terminal running "spyder --light" or "spyder -l" briefly flashes the splash screen and then crashes. Upon restart it gives the --reset advice but that doesn't help.
The terminal output upon the crash is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spyderlib/spyder.py", line 2094, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/local/lib/python2.7/site-packages/spyderlib/spyder.py", line 1989, in run_spyder
    main.setup()
  File "/usr/local/lib/python2.7/site-packages/spyderlib/spyder.py", line 801, in setup
    self.ipyconsole.register_plugin()
  File "/usr/local/lib/python2.7/site-packages/spyderlib/plugins/ipythonconsole.py", line 773, in register_plugin
    self.main.editor.load)
AttributeError: 'NoneType' object has no attribute 'load'

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-06-28T16:16:52Z_

Thanks for reporting, this is a problem that we already fixed and we'll be released in our next version.

For reference, this is the commit that fixed it: revision 35b31bea0ff0

**Summary:** Spyder --light is not functioning  \<span class="oldvalue"> (was: spyder --light not functioning) \</span>  
  **Status:** Fixed  
  **Labels:** -OpSys-Windows Cat-SpyderGUI MS-v2.2.1

**Comment by spyder-issues-migrator** [comment]
_From [srobert...@gmail.com](https://code.google.com/u/109471414896291480696/) on 2013-06-28T17:58:02Z_

Yes, I applied the revised patches and spyder --light works fine now.
