### ISSUE TITLE
I am always getting the error 'No module found named spyder.utils.ipython' .I have unistalled and reinstalled spyder3 and 2 along with python3 several times.I m using ubuntu 18.04.Pls help me resolve this  as nothing is there on internet regarding this

### ISSUE THREAD

**Issue by AsPiRInQNT** [spyder-ide/spyder#14511]
Traceback (most recent call last):
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 239, in main
from spyder.utils.ipython.spyder_kernel import SpyderKernel
ModuleNotFoundError: No module named 'spyder.utils.ipython'
Traceback (most recent call last):
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 239, in main
from spyder.utils.ipython.spyder_kernel import SpyderKernel
ModuleNotFoundError: No module named 'spyder.utils.ipython'
Traceback (most recent call last):
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 239, in main
from spyder.utils.ipython.spyder_kernel import SpyderKernel
ModuleNotFoundError: No module named 'spyder.utils.ipython'
Traceback (most recent call last):
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 239, in main
from spyder.utils.ipython.spyder_kernel import SpyderKernel
ModuleNotFoundError: No module named 'spyder.utils.ipython'
Traceback (most recent call last):
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 239, in main
from spyder.utils.ipython.spyder_kernel import SpyderKernel
ModuleNotFoundError: No module named 'spyder.utils.ipython'

**Comment by AsPiRInQNT** [comment]
Actually i had installed spyder using both pip as well as apt
