### ISSUE TITLE
An error occurred while starting the kernel when I try to open Spyder

### ISSUE THREAD

**Issue by karkir0003** [spyder-ide/spyder#14512]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I'm trying to open Spyder (installed through Anaconda) and when I try to run the statement "print("Hello world")", I get an error in the IPython console saying "an error occurred whiel starting the kernel.

### What steps reproduce the problem?

1. Simply opening Spyder and typing a simple syntactically correct line of python 
2. 
3. 

### What is the expected output? What do you see instead?
Expect to see the string "Hello world" in the console, but I see the error message from the IPython console. Tried updating spyder and dateutils with Anaconda, but the update doesn't seem to be working.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
File "C:\Users\karki\AppData\Local\Continuum\anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1562, in create_kernel_manager_and_kernel_client
config=None, autorestart=True)
File "C:\Users\karki\AppData\Local\Continuum\anaconda3\lib\site‑packages\traitlets\traitlets.py", line 958, in __new__
inst.setup_instance(*args, **kwargs)
File "C:\Users\karki\AppData\Local\Continuum\anaconda3\lib\site‑packages\traitlets\traitlets.py", line 986, in setup_instance
super(HasTraits, self).setup_instance(*args, **kwargs)
File "C:\Users\karki\AppData\Local\Continuum\anaconda3\lib\site‑packages\traitlets\traitlets.py", line 977, in setup_instance
value.instance_init(self)
File "C:\Users\karki\AppData\Local\Continuum\anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1691, in instance_init
self._resolve_classes()
File "C:\Users\karki\AppData\Local\Continuum\anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1696, in _resolve_classes
self.klass = self._resolve_string(self.klass)
File "C:\Users\karki\AppData\Local\Continuum\anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1507, in _resolve_string
return import_item(string)
File "C:\Users\karki\AppData\Local\Continuum\anaconda3\lib\site‑packages\traitlets\utils\importstring.py", line 34, in import_item
module = __import__(package, fromlist=[obj])
File "C:\Users\karki\AppData\Local\Continuum\anaconda3\lib\site‑packages\jupyter_client\session.py", line 61, in 
from jupyter_client.jsonutil import extract_dates, squash_dates, date_default
File "C:\Users\karki\AppData\Local\Continuum\anaconda3\lib\site‑packages\jupyter_client\jsonutil.py", line 11, in 
from dateutil.parser import parse as _dateutil_parse
File "C:\Users\karki\AppData\Local\Continuum\anaconda3\lib\site‑packages\dateutil\parser.py", line 158
l.append("%s=%s" % (attr, `value`))
^
SyntaxError: invalid syntax

```

## Versions

* Spyder version: Python 3.7 version
* Python version:  3.7 version
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10 64 bit

### Dependencies

```
IPython >=4.0     :  7.8.0 (OK)
cython >=0.21     :  0.29.13 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
matplotlib >=2.0.0:  None (NOK)
nbconvert >=4.0   :  5.6.0 (OK)
numpy >=1.7       :  1.16.5 (OK)
pandas >=0.13.1   :  None (NOK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.4.2 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
sympy >=0.7.3     :  1.4 (OK)

```

**Comment by ccordoba12** [comment]
Hey @karkir0003, thanks for reporting. Please close Spyder, open the Anaconda Prompt and run there

    conda install -f python-dateutil

If after that things are still failing, I'm afraid you'll have to reinstall Anaconda. For that, please watch the second part of [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to learn how to do it.

**Comment by karkir0003** [comment]
thanks Carlos. It works!

**Comment by karkir0003** [comment]
I tried typing in the above command in Anaconda and it works. I'm still not
sure of why in the first place spyder didn't connect to my ipython kernel

**Comment by ccordoba12** [comment]
That's strange, but I'm glad things are fixed for you now.
