### ISSUE TITLE
Python Multiprocessing Pool

### ISSUE THREAD

**Issue by mr-gabrielrios** [spyder-ide/spyder#14513]
### What steps will reproduce the problem?

Using the Python Multiprocessing Pool library on an elementary NumPy array operation caused this error. 

Array size: 100 x 100
Pool size: 2

### Traceback
```python-traceback
  File "/home/gabriel/anaconda3/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/home/gabriel/anaconda3/lib/python3.8/site-packages/jupyter_client/threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/home/gabriel/anaconda3/lib/python3.8/site-packages/jupyter_client/session.py", line 928, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'b80c82659b54c19141e7ba03b1bc5257c474a2f91a7e24b012e96e8b7de7c40f'
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/home/gabriel/anaconda3/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/home/gabriel/anaconda3/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/gabriel/anaconda3/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/home/gabriel/anaconda3/lib/python3.8/site-packages/jupyter_client/threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/home/gabriel/anaconda3/lib/python3.8/site-packages/jupyter_client/session.py", line 928, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'b80c82659b54c19141e7ba03b1bc5257c474a2f91a7e24b012e96e8b7de7c40f'
ERROR:tornado.application:Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x7f07ef2e4820>)
Traceback (most recent call last):
  File "/home/gabriel/anaconda3/lib/python3.8/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/gabriel/anaconda3/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 542, in <lambda>
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "/home/gabriel/anaconda3/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/home/gabriel/anaconda3/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/gabriel/anaconda3/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/home/gabriel/anaconda3/lib/python3.8/site-packages/jupyter_client/threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/home/gabriel/anaconda3/lib/python3.8/site-packages/jupyter_client/session.py", line 928, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'b80c82659b54c19141e7ba03b1bc5257c474a2f91a7e24b012e96e8b7de7c40f'
```

## Versions

* Spyder version: 4.1.4 
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 5.4.0-58-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @mr-gabrielrios, thanks for reporting. Please post the exact code that it's giving you this problem. Otherwise we won't be able to reproduce it and try to fix it.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
