### ISSUE TITLE
Go to definition error

### ISSUE THREAD

**Issue by Punchyou** [spyder-ide/spyder#14528]
### What steps will reproduce the problem?

Error produced after right clicking on function name and chose "Go to definition".

Also tried Ctl+Click, and Ctl+G on function name to do the same, but didn't have a response.

### Traceback
```python-traceback
  File "/home/punchubu1804/.local/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1554, in handle_go_to_definition
    def_range = position['range']
TypeError: list indices must be integers or slices, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "/usr/local/bin/spyder3", line 11, in <module>
    sys.exit(main())
  File "/home/punchubu1804/.local/lib/python3.7/site-packages/spyder/app/start.py", line 213, in main
    mainwindow.main(options, args)
  File "/home/punchubu1804/.local/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3624, in main
    mainwindow = create_window(app, splash, options, args)
  File "/home/punchubu1804/.local/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3523, in create_window
    app.exec_()
  File "/home/punchubu1804/.local/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/client.py", line 513, in on_msg_received
    self.req_reply[req_id](None, {'params': []})
  File "/home/punchubu1804/.local/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/plugin.py", line 561, in receive_response
    self.COMPLETION_CLIENT_NAME, req_id, response)
  File "/home/punchubu1804/.local/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 125, in receive_response
    self.howto_send_to_codeeditor(req_id)
  File "/home/punchubu1804/.local/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 177, in howto_send_to_codeeditor
    self.skip_and_send_to_codeeditor(req_id)
  File "/home/punchubu1804/.local/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 211, in skip_and_send_to_codeeditor
    self.gather_and_send_to_codeeditor(request_responses)
  File "/home/punchubu1804/.local/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 279, in gather_and_send_to_codeeditor
    response_instance.handle_response(req_type, responses)
  File "/home/punchubu1804/.local/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1095, in handle_response
    handler(params)
  File "/home/punchubu1804/.local/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1571, in handle_go_to_definition
    "Error when processing go to definition")
  File "/home/punchubu1804/.local/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1126, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
```

## Versions

* Spyder version: 4.2.1 
* Python version: 3.7.5
* Qt version: 5.12.7
* PyQt5 version: 5.12.3
* Operating System: Linux 5.3.0-51-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.3.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.3.0 (OK)
diff_match_patch >=20181111     :  20181111 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=7.6.0                 :  7.13.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  21.2.0 (OK)
nbconvert >=4.0                 :  5.6.1 (OK)
numpydoc >=0.6.0                :  0.9.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.0 (OK)
pygments >=2.0                  :  2.6.1 (OK)
pylint >=1.0                    :  2.4.4 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  0.7.0 (OK)
qtconsole >=5.0.1               :  5.0.1 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
setuptools >=39.0.0             :  46.1.3 (OK)
sphinx >=0.6.6                  :  3.0.1 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.1 (OK)
textdistance >=4.2.0            :  4.2.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.4 (OK)
xdg >=0.26                      :  0.26 (OK)
zmq >=17                        :  19.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.17 (OK)
matplotlib >=2.0.0              :  3.1.3 (OK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.1.3 (OK)
scipy >=0.17.0                  :  1.4.1 (OK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @Punchyou, thanks for reporting. Please post a simple, reproducible example that generates this error for you, so we can run it on our side to understand what's happening in your case.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
