### ISSUE TITLE
'import sitecustomize' failed

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1458]
_From [lennartg...@gmail.com](https://code.google.com/u/116923799143015232536/) on 2013-06-25T14:22:13Z_

Spyder Version:  2.2.0
Python Version:  2.7.5
Qt Version:      4.8.4, PyQt4 (API v2) 4.9.6 on Windows 

What steps will reproduce the problem?

 1.starting up spyder What is the expected output? What do you see instead? i do not expect to see an error 

Please provide any additional information below

. upon starting spyder i get

'import sitecustomize' failed

the traceback tells me

Traceback (most recent call last):
  File "C:\Python27\lib\site.py", line 498, in execsitecustomize
    import sitecustomize
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 174, in \<module>
    os.environ["SPYDER_AR_STATE"].lower() == "true")
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 146, in __init__
    self.n_request.connect( (host, notification_port) )
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10061] No connection could be made because the target machine actively refused it
Python 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1458_

**Comment by spyder-issues-migrator** [comment]
_From [lennartg...@gmail.com](https://code.google.com/u/116923799143015232536/) on 2013-06-25T12:23:48Z_

I already applied this patch (see attachment of last comment): https://code.google.com/p/spyderlib/issues/detail?id=771 This did not fix it.

**Comment by spyder-issues-migrator** [comment]
_From [lennartg...@gmail.com](https://code.google.com/u/116923799143015232536/) on 2013-06-25T12:25:34Z_

I am running windows 8 64 bit and have installed pythonxy with default settings.

**Comment by spyder-issues-migrator** [comment]
_From [lennartg...@gmail.com](https://code.google.com/u/116923799143015232536/) on 2013-06-25T12:26:50Z_

I also created a similar thread on stackexchange here: http://stackoverflow.com/questions/17258634/import-zitecustomize-failed-upon-starting-spyder

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-06-25T14:58:29Z_

I posted an answer in Stackoverflow. There is nothing we can do on our side, you need to check your firewall config.

**Status:** Invalid
