### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib_metadata'

### ISSUE THREAD

**Issue by moonj94** [spyder-ide/spyder#14598]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [x ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I reinstalled the latest version of anaconda and I am getting the error:
`ModuleNotFoundError: No module named 'importlib_metadata'`

`(base) Jaes-MacBook-Pro:~ jaemoon$ spyder
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/jsonschema/__init__.py", line 31, in <module>
    from importlib import metadata
ImportError: cannot import name 'metadata' from 'importlib' (/opt/anaconda3/lib/python3.7/importlib/__init__.py)

During handling of the above exception, another exception occurred:

I am somewhat new to python and am not sure why this is happening. How can I fix it?
I initially had to reinstall anaconda because I mixed up conda with pip. I removed anaconda library and reinstalled. 

### What steps reproduce the problem?

1. install anaconda
2. run spyder
3. 

### What is the expected output? What do you see instead?
I expect to see spyder up and running, like before the reinstall. But What I see is this:
```
Traceback (most recent call last):
  File "/opt/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 212, in main
    mainwindow.main(options, args)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3685, in main
    mainwindow = run_spyder(app, options, args)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3571, in run_spyder
    main.setup()
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 886, in setup
    from spyder.plugins.completion.plugin import CompletionManager
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 22, in <module>
    from spyder.plugins.completion.languageserver.plugin import (
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/plugin.py", line 31, in <module>
    from spyder.plugins.completion.languageserver.confpage import (
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/confpage.py", line 31, in <module>
    from spyder.plugins.completion.languageserver.widgets.snippetsconfig import (
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/widgets/snippetsconfig.py", line 17, in <module>
    from jsonschema import validate as json_validate
  File "/opt/anaconda3/lib/python3.7/site-packages/jsonschema/__init__.py", line 33, in <module>
    import importlib_metadata as metadata
ModuleNotFoundError: No module named 'importlib_metadata'`
```

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.2.0
* Python version: 3.7.7
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: mac Os catalina 10.15.7

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by juanis2112** [comment]
Hi @moonj94 thanks for reporting this. Can you please try running in your terminal  
```
conda install importlib_metadata
```
and then run spyder again. If this doesn't work please paste the output of:
1. Running `conda list` in your terminal
2. Running `conda info` in your terminal

**Comment by juanis2112** [comment]
Closing for no response

**Comment by lilllooo** [comment]
I also see a same issue today.
(base) C:\WINDOWS\system32>spyder --new-instance
Traceback (most recent call last):
  File "C:\Users\cliu96\AppData\Local\Continuum\anaconda3\lib\site-packages\jsonschema\__init__.py", line 31, in <module>
    from importlib import metadata
ImportError: cannot import name 'metadata' from 'importlib' (C:\Users\cliu96\AppData\Local\Continuum\anaconda3\lib\importlib\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cliu96\AppData\Local\Continuum\anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\cliu96\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\app\start.py", line 228, in main
    mainwindow.main(options, args)
  File "C:\Users\cliu96\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3630, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\cliu96\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3488, in create_window
    main.setup()
  File "C:\Users\cliu96\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 802, in setup
    from spyder.plugins.completion.plugin import CompletionManager
  File "C:\Users\cliu96\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 22, in <module>
    from spyder.plugins.completion.languageserver.plugin import (
  File "C:\Users\cliu96\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\completion\languageserver\plugin.py", line 31, in <module>
    from spyder.plugins.completion.languageserver.confpage import (
  File "C:\Users\cliu96\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\completion\languageserver\confpage.py", line 31, in <module>
    from spyder.plugins.completion.languageserver.widgets.snippetsconfig import (
  File "C:\Users\cliu96\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\completion\languageserver\widgets\snippetsconfig.py", line 17, in <module>
    from jsonschema import validate as json_validate
  File "C:\Users\cliu96\AppData\Local\Continuum\anaconda3\lib\site-packages\jsonschema\__init__.py", line 33, in <module>
    import importlib_metadata as metadata
ModuleNotFoundError: No module named 'importlib_metadata'
