### ISSUE TITLE
audio error

### ISSUE THREAD

**Issue by robert478** [spyder-ide/spyder#14630]
## Description
An error ocurred while starting the kernel
Traceback (most recent call last):
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 239, in main
from spyder.utils.ipython.spyder_kernel import SpyderKernel
ModuleNotFoundError: No module named 'spyder.utils.ipython'
Traceback (most recent call last):
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 239, in main
from spyder.utils.ipython.spyder_kernel import SpyderKernel
ModuleNotFoundError: No module named 'spyder.utils.ipython'
Traceback (most recent call last):
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 239, in main
from spyder.utils.ipython.spyder_kernel import SpyderKernel
ModuleNotFoundError: No module named 'spyder.utils.ipython'
Traceback (most recent call last):
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 239, in main
from spyder.utils.ipython.spyder_kernel import SpyderKernel
ModuleNotFoundError: No module named 'spyder.utils.ipython'
Traceback (most recent call last):
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 239, in main
from spyder.utils.ipython.spyder_kernel import SpyderKernel
ModuleNotFoundError: No module named 'spyder.utils.ipython'
**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

    module = _import_module_from_path(module_name, plugin_path)
    module = spec.loader.load_module(module_name)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 262, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    from .terminalplugin import TerminalPlugin as PLUGIN_CLASS
    from spyder.api.plugins import SpyderPluginWidget
ModuleNotFoundError: No module named 'spyder.api'
WARNING:traitlets:kernel restarted
WARNING:traitlets:kernel restarted
WARNING:traitlets:kernel restarted
WARNING:traitlets:kernel restarted
WARNING:traitlets:KernelRestarter: restart failed
WARNING:traitlets:kernel died: 18.015873432159424

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.9
* Qt Versions: 5.9.5, PyQt5 5.10.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.19.5 (OK)
sphinx >=0.6.6   :  1.6.7 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  5.5.0 (OK)
pylint >=0.25    :  1.8.3 (OK)

```

**Comment by andfoy** [comment]
Hi @robert478, it seems that you are using a pretty old version of Spyder, could you please update to the latest version of Spyder 4 and check if this issue still occurs?

**Comment by andfoy** [comment]
Closing this one since there was not a reply during the past week
