### ISSUE TITLE
Possible Black Autoformat Bug

### ISSUE THREAD

**Issue by pmh722** [spyder-ide/spyder#14653]
## Problem Description
When I hit F5 to run a script, Spyder will weirdly copy the last few lines of my file, and paste them multiple times at the end of the file. So my file goes from:
```
foo()
bar()
baz()
```
to
```
foo()
bar()
baz()
baz()
baz()
```
### What steps reproduce the problem?
I just upgraded to 4.2. I switched autoformatter to black, and turned on autoformat-on-save. When I edit my file, do not manually run autoformat, and do not manually save, but press F5 to run the script, spyder will trigger the autoformat (fine) but at the same time it also changes the content of the end of the file (not fine). If I manually save the file, or manually run autoformatter, I do not get this problem. Also, this problem does not hit me 100% of the time. It seems most likely to happen when black encounters a long list that it splits across multiple lines.

### What is the expected output? What do you see instead?
When I run a script, I do expect it to save the file and therefore trigger black, but adding new lines to the end of the file is not expected.

**Comment by dalthviz** [comment]
Hi @pmh722 thanks for the feedback! I was able to reproduce this issue on Windows with Spyder 4.2.1.

To trigger it you just need to leave at least two empty lines at the beginning of the file:
![black](https://user-images.githubusercontent.com/16781833/106180499-a8d11800-619c-11eb-822e-a8e009d4a000.gif)

**Comment by dalthviz** [comment]
Pinging @andfoy and @ccordoba12 just in case

**Comment by pmh722** [comment]
Thanks @dalthviz ! 
Let me know if there's anything more I can do on my end to help debug.

**Comment by pmh722** [comment]
Possibly related, I just got this Spyder "Issue Reporter" trace when I saved a file:
```
  File "{REDACT}/site-packages/spyder/plugins/editor/widgets/editor.py", line 2092, in _save_file
    self.modification_changed(index=index)
  File "{REDACT}/site-packages/spyder/plugins/editor/widgets/editor.py", line 2549, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
Traceback (most recent call last):
  File "{REDACT}/site-packages/spyder/plugins/editor/widgets/editor.py", line 2092, in _save_file
    self.modification_changed(index=index)
  File "{REDACT}/site-packages/spyder/plugins/editor/widgets/editor.py", line 2549, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
Traceback (most recent call last):
  File "{REDACT}/site-packages/spyder/plugins/editor/widgets/editor.py", line 2092, in _save_file
    self.modification_changed(index=index)
  File "{REDACT}/site-packages/spyder/plugins/editor/widgets/editor.py", line 2549, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
Traceback (most recent call last):
  File "{REDACT}/site-packages/spyder/plugins/editor/widgets/editor.py", line 2092, in _save_file
    self.modification_changed(index=index)
  File "{REDACT}/site-packages/spyder/plugins/editor/widgets/editor.py", line 2549, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range

```
