### ISSUE TITLE
Spyder 4.2.1 won't launch in Anaconda

### ISSUE THREAD

**Issue by cpkc** [spyder-ide/spyder#14687]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder 4.2.1 won't launch after update.

### What steps reproduce the problem?

1. launch anaconda navigator and click on spyder
2.  error report, last one was
3. ModuleNotFoundError: No module named 'textdistance'

### What is the expected output? What do you see instead?
If launched from Spyder shortcut nothing happens.
From anaconda navigator last error ModuleNotFoundError: No module named 'textdistance'

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.2.1
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by cpkc** [comment]
I fixed doing on anaconda prompt:

python -m pip install -U textdistance --no-cache-dir

some dependencies

python -m pip install -U pyqt5 pyqtwebengine qtconsole --no-cache-dir

**Comment by sjev** [comment]
Same issue on Linux Mint 20.1 

`ModuleNotFoundError: No module named 'textdistance'`
To continue working I simply went to the previos version of the conda environmment.

`conda list --revisions`
`conda install --revision N`

**Comment by YIMINGMA** [comment]
It turns out to be a dependency error.

In my case, I got the following error message:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 4.2.1 requires pyqtwebengine<5.13, which is not installed.
spyder 4.2.1 requires pyqt5<5.13, but you have pyqt5 5.15.2 which is incompatible.
spyder 4.2.1 requires qtconsole>=5.0.1, but you have qtconsole 4.7.7 which is incompatible.
```
So I used
```
pip install pyqt5==5.12
pip install pyqtwebengine==5.12
pip uninstall qtconsole
pip install qtconsole
```
and solved this problem.

**Comment by simoubuntu** [comment]
> ```
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> spyder 4.2.1 requires pyqtwebengine<5.13, which is not installed.
> spyder 4.2.1 requires pyqt5<5.13, but you have pyqt5 5.15.2 which is incompatible.
> spyder 4.2.1 requires qtconsole>=5.0.1, but you have qtconsole 4.7.7 which is incompatible.
> ```
I got the same error, but Spyder is working well even if the version of pyqt5 is not the correct one.

**Comment by Dan-Patterson** [comment]
Had to completely uninstall and remove spyder ( including the spyder folder in c:\users\...local ) and install 4.2.0.  
Fortunately I backup spyder.ini and transient.ini  so I don't have to reconfigure my preferences.
An exciting start to the morning ;)

**Comment by citifroup** [comment]
Yet another beta s**t release. At least the anaconda roll back to 4.2.0 was smooth.

**Comment by NelsonUpenn** [comment]
Thank you, sjev. Same issue on macOS10.15.7 and your solution worked:
conda list --revisions
conda install --revision 35

**Comment by sharon92** [comment]
I installed the dependencies (textdistance, pyqt5=5.12, pyqtwebengine=5.12, qtconsole) but it still wont launch.

Going back to 4.2.0 also doesn't fix it for me.

I installed anaconda again and landed on version 4.1.5
which in turn requires spyder-kernels <1.10

all my virtual environments are set to work with spyder-kernel >1.10

Could you please send an update to fix this ? :)

**Comment by cpkc** [comment]
> I installed the dependencies (textdistance, pyqt5=5.12, pyqtwebengine=5.12, qtconsole) but it still wont launch.
> 
> Going back to 4.2.0 also doesn't fix it for me.
> 
> I installed anaconda again and landed on version 4.1.5
> which in turn requires spyder-kernels <1.10
> 
> all my virtual environments are set to work with spyder-kernel >1.10
> 
> Could you please send an update to fix this ? :)

When you lanch spyder on anaconda navigator there's some error message? Remember in windows the shortcut nothing happens.

**Comment by sharon92** [comment]
> When you lanch spyder on anaconda navigator there's some error message? Remember in windows the shortcut nothing happens.

In the older version of Anaconda (with python 3.7 64 bit). It did show the error message, about module error textdistance and pyqt modules missing.

Launching spyder from the latest anaconda (with py 3.8.5) doesnt pop the error window in anaconda navigator. Perhaps it needs to be enabled somewhere..

Anyhow I did get it to work right after I made the comment.

1. I reinstalled anaconda (uninstalled the older version). 
2. go to Anaconda_installation_dir\scripts and open command prompt
3. from this directory type:
4. `pip install textdistance`
5. `pip install pyqt5==5.12`
6. `pip install pyqtwebengine==5.12`
7. `pip install qtconsole`
8. go to Anaconda Prompt and type:
9. `conda update anaconda`

Doing these steps made Spyder 4.2.1 work again. Cheers!

**Comment by ccordoba12** [comment]
@citifroup, I blocked you from our organization for one week because we don't tolerate abusive comments here. I hope this behavior doesn't repeat in the future or I'll have to block you permanently.

**Comment by ccordoba12** [comment]
@cpkc, @sharon92, I hid your comments because it's a really bad advice to tell people to install packages with pip in Anaconda. We warn time and time again about that, and we even produced [a video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to tell people how to recover from that problem.

If Ananconda fails after what you did, please see it to learn how to properly uninstall it and install it again.

@YIMINGMA, I also hid your comment although it seems related to pip because it gives the same advice and so it can be confusing for other Anaconda users.

**Comment by ccordoba12** [comment]
It's not our fault that 4.2.1 was not packaged correctly by the Anaconda team (we don't have any relationship with them). I verified that they didn't pick up our new dependencies and patches, which led to this disaster.

I'll contact them promptly and let them know what they need to do to fix it. For now, there's nothing you can do to make our 4.2.1 version function correctly, so please stay in 4.2.0 instead.

**Comment by cpkc** [comment]
> @cpkc, @sharon92, I hid your comments because it's a really bad advice to tell people to install packages with pip in Anaconda. We warn time and time again about that, and we even produced [a video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to tell people how to recover from that problem.
> 
> If Ananconda fails after what you did, please see it to learn how to properly uninstall it and reinstall it again.
> 
> @YIMINGMA, I also hid your comment, although it seems related to pip, because it gives the same advice and so it can be confusing for other Anaconda users.

Thank you for advice!

**Comment by sharon92** [comment]
@ccordoba12 Thanks for the tip! And thank you for developing this amazing tool :)

**Comment by ccordoba12** [comment]
@cpkc, @sharon92, thanks for understanding! I hope this situation will be solved quickly.

**Comment by TonehavenE** [comment]
@ccordoba12 I'm a complete noob who just installed miniconda and used conda install spyder which grabbed this borked version.  I have no previous revisions installed.  What conda commands can get me to a working Spyder 4.2.0.

**Comment by ccordoba12** [comment]
@TonehavenE, very good question (I forgot to mention that). To install 4.2.0 you need to run:

    conda install spyder=4.2.0

**Comment by TonehavenE** [comment]
@ccordoba12 do I need to uninstall 4.1.2 first?  conda uninstall spyder made a huge list of package changes that I chickened out on.

**Comment by JohannHM** [comment]
No! that's impossible. So this means that we have to wait for you contact with Anaconda and see when they consider to fix the bug with Spyder new version?
Is there any other possible solution to work? I had to remove my well specified environment , then create a new one , but it only offer me to choose to install the Spider4.2.1 again!!!
What should I do to work right now?

**Comment by ccordoba12** [comment]
> @ccordoba12 do I need to uninstall 4.2.1 first?

No, you haven't. The command I posted above should replace 4.2.1 with 4.2.0. Or if that doesn't work or give you errors, please uninstall Miniconda, reinstall it and run my command instead of `conda install spyder`.

**Comment by ccordoba12** [comment]
@JohannHM, please open the Anaconda Prompt and run there:

    conda create -n correct-spyder spyder=4.2.0

That will create a new environment called `correct-spyder` with our last working version.

Then you need to run

    conda activate correct-spyder
    conda install pytorch

In case you want to install `pytorch` on it. If not, please replace `pytorch` with the packages you need for your work.

**Comment by ccordoba12** [comment]
Hey everyone, Anaconda just released new packages for 4.2.1 with fixes for all the errors you reported. Please run

    conda update spyder

if you already have 4.2.1, or

    conda install spyder=4.2.1

or if you had to roll back to a previous version, and let us know if things are working for you now.

Thanks for your help!

**Comment by dwck** [comment]
I just tried to run the 4.2.1 again today and I was not able to.
I will be back to 4.2.0 for now ..

Traceback (most recent call last):
File "/Users/dwerneck/opt/anaconda3/bin/spyder", line 11, in 
sys.exit(main())
File "/Users/dwerneck/opt/anaconda3/lib/python3.8/site-packages/spyder/app/start.py", line 214, in main
mainwindow.main(options, args)
File "/Users/dwerneck/opt/anaconda3/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 3624, in main
mainwindow = create_window(app, splash, options, args)
File "/Users/dwerneck/opt/anaconda3/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 3480, in create_window
main = MainWindow(splash, options)
File "/Users/dwerneck/opt/anaconda3/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 283, in __init__
from spyder.preferences.appearance import AppearanceConfigPage
File "/Users/dwerneck/opt/anaconda3/lib/python3.8/site-packages/spyder/preferences/appearance.py", line 21, in 
from spyder.plugins.editor.widgets.codeeditor import CodeEditor
File "/Users/dwerneck/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 70, in 
from spyder.plugins.editor.panels import (ClassFunctionDropdown,
File "/Users/dwerneck/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/editor/panels/__init__.py", line 13, in 
from .codefolding import FoldingPanel
File "/Users/dwerneck/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/editor/panels/codefolding.py", line 32, in 
from spyder.plugins.editor.panels.utils import (
File "/Users/dwerneck/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/editor/panels/utils.py", line 15, in 
import textdistance
ModuleNotFoundError: No module named 'textdistance'

**Comment by ccordoba12** [comment]
@dwck, you need to update to a new build that fixes that error. Please see my comment above yours to learn how to do it.

**Comment by alebaho** [comment]
@ccordoba12  Thank you! 4.2.1 works fine now after doing the `conda update spyder`. It updated correctly the wrong dependencies.

**Comment by EkaterinaAbramova** [comment]
Hello, I am on Mac Big Sur and have Anaconda. After updating to Spyder 4.2.0 I was not able to open Spyder from Anaconda-Navigator. Have been patiently waiting for 4.2.1 but this does not open from my navigator either. Have been using the workaround suggested before:  
conda activate spyder-dev 
export QT_MAC_WANTS_LAYER=1 
spyder
but would really like to know:
a) whether I should actually be expecting 4.2.1 Spyder to open from anaconda-navigator
b) how to resolve this issue if it is indeed meant to be working
I do not get any errors, Spyder just never opens up when I click on it. I have updated anaconda with `conda update anaconda`, and run `conda update --all`.
Could you please recommend what to do to get Spyder to work?

**Comment by markyfantidis** [comment]
hello everyone,

I am fairly new to this but have used Anaconda / Spyder before on a Mac. I just downloaded Anaconda today on my Linux machine and when I go to launch it (from inside the Anaconda navigator) I get this message:

Traceback (most recent call last):
File "/home/storm/anaconda3/lib/python3.8/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in 
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: libXss.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/storm/anaconda3/bin/spyder", line 11, in 
sys.exit(main())
File "/home/storm/anaconda3/lib/python3.8/site-packages/spyder/app/start.py", line 201, in main
from spyder.app import mainwindow
File "/home/storm/anaconda3/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 84, in 
from qtpy import QtWebEngineWidgets # analysis:ignore
File "/home/storm/anaconda3/lib/python3.8/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in 
from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'


Reading this thread made me think maybe it is just an unfortunate timing to download it given that there are missing updates?

However I have followed @ccordoba12 instructions about how to update (I have also tried from within Anaconda, clicking to update latest version) and I'm still getting the same message.

Thank you in advance.

Mark

**Comment by ccordoba12** [comment]
@EkaterinaAbramova, please open Terminal and run the following commands:

    conda create -n latest-spyder spyder=4.2.1
    conda activate latest-spyder
    spyder

That should give you a working Spyder. Also, you can start it from Anaconda Navigator by selecting the `latest-spyder` environment there.

> I do not get any errors, Spyder just never opens up when I click on it. I have updated anaconda with `conda update anaconda`, and run `conda update --all`.

In general it's not a good idea to use `conda update --all` because it can lead to a broken environment (as it seems happened to you).

**Comment by ccordoba12** [comment]
@markyfantidis, that's not a problem with Spyder, but it can be solved by running

    sudo apt-get install libxss1

**Comment by markyfantidis** [comment]
@ccordoba12 thank you, it doesn't seem like to solve the problem, I'm getting a

' sudo: apt-get" command not found '

it probably has nothing to do with the Spyder then, but do you have any suggestions what to look for? should I look for an APT? sorry as said before, I'm still new to this

**Comment by ccordoba12** [comment]
@markyfantidis, what is your Linux distribution?

**Comment by markyfantidis** [comment]
@ccordoba12 CentOS 8

**Comment by ccordoba12** [comment]
Please run

    yum install libXScrnSaver

instead.

**Comment by endolith** [comment]
> In general it's not a good idea to use conda update --all because it can lead to a broken environment (as it seems happened to you).

This is the opposite of the advice given by https://www.anaconda.com/blog/keeping-anaconda-date:

> What 95% of People Actually Want
>
> In most cases what you want to do when you say that you want to update Anaconda is to execute the command:
> 
>     conda update --all
> ...
> Updating the Anaconda Package is Almost Always a Bad Idea

**Comment by smchartrand** [comment]
Hi All -

I just upgrade to Spyder 4.2.1, and encountered the same problem of Spyder not loading through Anaconda-Navigator after the upgrade. I applied @ccordoba12 fix `conda update spyder` in the terminal, and after fixing some broken dependencies, everything is working again. When running `conda update spyder`, this is the update that was triggered [taken from the terminal]: 

`spyder                               4.2.1-py37h06a4308_0 --> 4.2.1-py37h06a4308_1`

I run Ubuntu 20.04LTS on a Lenovo Thinkpad. Thanks @ccordoba12.

**Comment by EkaterinaAbramova** [comment]
Dear @ccordoba12 I am afraid that is not the question I was asking (I do not wish to create an environment).
My question simply is: how can I open anaconda navigator, click on Spyder icon and have it open up? Currently this is not happening, and has not been ever since Big Sur / Spyder 4.2.0 or 4.2.1. I do not get any errors, Spyder just never opens up when I click on it. Then when I attempt to close navigator it is asking me to confirm I want to closer Spyder, so clearly something is wrong. 

@smchartrand thank you for your suggestion, I tried this but everything is up to date. 
Things I tried from Terminal (I am on Mac):
uninstall and re-install tornado 
`conda uninstall tornado`
All of the `conda update` commands for conda, anaconda, spyder, anaconda-navigator

Thank you very much for your help.

**Comment by endolith** [comment]
@EkaterinaAbramova  If you run `spyder` from a terminal, you will at least see the error message that it produces

**Comment by ccordoba12** [comment]
@EkaterinaAbramova, you said:

> My question simply is: how can I open anaconda navigator, click on Spyder icon and have it open up?

I understand your concern. Unfortunately, I don't know why that's happening with Anaconda Navigator. If you want support for that, I recommend you to open an issue here:

https://github.com/ContinuumIO/anaconda-issues/

and ask for help to the Anaconda team. That's because they are the ones who develop Anaconda Navigator and can fix errors related to it.

What we can help you with is to make Spyder work. Sorry but I missed the part where you said you're using Big Sur (it's there in your first post, I just missed it). In that case, please follow this advice:

https://github.com/spyder-ide/spyder/issues/14702#issuecomment-774514946

For now, it's the only way to make Spyder work reliably in Big Sur, and also use Anaconda packages for libraries that don't come with our DMG installer.

**Comment by markyfantidis** [comment]
@ccordoba12 that worked !! thanks very much really appreciate it!!

**Comment by jouellnyc** [comment]
HTH - got the same initial error on Ubuntu 20.04.2 LTS and googled my way here.

Steps @https://github.com/spyder-ide/spyder/issues/14687#issuecomment-773641452 fixed it right up.

**Comment by ccordoba12** [comment]
> @ccordoba12 that worked !! thanks very much really appreciate it!!

Great!! I'm glad Spyder is working for you now.

**Comment by QuantiveFlow** [comment]
I ran 

> conda update spyder
 
and still got the error:

> ModuleNotFoundError: module 'importlib_metadata' has no attribute 'entry_points'

but after uninstalling and then reinstalling the module I was finally able to launch Spyder throught the Anaconda Navigator. I'm not sure if I even needed to update spyder, and I think that had I just uninstalled then reinstalled the initial 'ModuleNotFoundError' module that I wouldnt have had to update Spyder at all. So for anyone that is having this problem try to uninstall then reinstall the module before updating Spyder to see if that fixes it. If not then you'll have to update spyder and uninstall then reinstall the new 'ModuleNotFoundError' module. That should work.

**Comment by haroldss** [comment]
is works for me when I runs the flllowing command :  conda update spyder

**Comment by silveira-lucas** [comment]
Not working for me. I made a fresh install of anaconda on macOS Catalina and after running conda update --all, spyder didn't open anymore. I had to make another fresh install for it to function.

**Comment by EkaterinaAbramova** [comment]
Thank you @ccordoba12 I appreciate your responses. I tried opening the case via your recommended Anaconda link and nobody replied at all.

I am working with an environment which you suggested earlier (created as `conda create -n latest-spyder spyder=4.2.1`)  and everything is running smoothly so far, however there is a really high latency. I know this is an ongoing issue but was wondering if there is an update to this?

I tried the previous suggestion of opening Spyder from terminal:
```
conda activate latest-spyder 
export QT_MAC_WANTS_LAYER=1 
spyder
```
However latency is terrible still if not worse. Any other ideas?

**Comment by ccordoba12** [comment]
@EkaterinaAbramova, the problem is that Anaconda is using a very old version of Qt (the graphical library Spyder is built on) which is unsupported in Big Sur. That's why running Spyder in Anaconda gives those big lags while typing.

Please try to install Spyder from Conda-forge (which has a more recent Qt version) to see if that helps:

    conda create -n spyder-cf -c conda-forge spyder=4.2.1
    conda activate spyder-cf
    spyder

Let us know if that fixes the problem for you.

**Comment by RwdBass** [comment]
Hello
I'm currently having issues launching Spyder from Anaconda Navigator
I have a Mac with the M1 processors running Big Sur (11.2.3)
Current Spyder version: 2.4.3

I ran `conda clean --all`,` conda update conda`, `conda update --all` & `conda update spyder` all worked fine and no errors whatsoever

running `conda info` :
    

> active environment : base
>     active env location : /Users/rawadbassil/opt/anaconda3
>             shell level : 1
>        user config file : /Users/rawadbassil/.condarc
>  populated config files : /Users/rawadbassil/.condarc
>           conda version : 4.9.2
>     conda-build version : 3.21.4
>          python version : 3.8.8.final.0
>        virtual packages : __osx=10.16=0
>                           __unix=0=0
>                           __archspec=1=x86_64
>        base environment : /Users/rawadbassil/opt/anaconda3  (writable)
>            channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
>                           https://repo.anaconda.com/pkgs/main/noarch
>                           https://repo.anaconda.com/pkgs/r/osx-64
>                           https://repo.anaconda.com/pkgs/r/noarch
>           package cache : /Users/rawadbassil/opt/anaconda3/pkgs
>                           /Users/rawadbassil/.conda/pkgs
>        envs directories : /Users/rawadbassil/opt/anaconda3/envs
>                           /Users/rawadbassil/.conda/envs
>                platform : osx-64
>              user-agent : conda/4.9.2 requests/2.25.1 CPython/3.8.8 Darwin/20.3.0 OSX/10.16
>                 UID:GID : 501:20
>              netrc file : None
>            offline mode : False 

I'm kind of new so please let me know if you need further info 
@ccordoba12 would really appreciate it if you could help ASAP !

**Comment by dalthviz** [comment]
@ccordoba12 should we close this one or is there a reason to keep it open?

**Comment by ccordoba12** [comment]
Let's close it.
