### ISSUE TITLE
output shows error with porcessor-intensive applications

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1474]
_From [jon.bra...@gmail.com](https://code.google.com/u/108833945975964498731/) on 2013-07-02T16:26:53Z_

Spyder Version:  2.1.10
Python Version:  2.7.3rc2
Qt Version:      4.8.2, PyQt4 (API v1) 4.9.3 on Linux 

What steps will reproduce the problem?

 1. enter the code:
for x in range(200):
    for y in range(10000):
        for z in range(1000):
            a=x*y*z
    print x What is the expected output? What do you see instead? The output shows:
96
97
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/monitor.py", line 588, in run
    already_pickled=True)
  File "/usr/lib/python2.7/dist-packages/spyderlib/utils/bsdsocket.py", line 24, in write_packet
    sock.send(struct.pack("l", len(sent_data)) + sent_data)
error: [Errno 32] Broken pipe

98
99 

Please provide any additional information below

. The error occurs in different places every time. This does not seem to affect the running program in any way -- it's just ugly.

Thanks for all your great work!

**Attachment:** [spyder.png](http://code.google.com/p/spyderlib/issues/detail?id=1474)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1474_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-07-04T10:32:49Z_

We worked hard to fix this problem in our 2.2 version, so you really need to update Spyder.

**Status:** Duplicate  
  **Mergedinto:** 1106
