### ISSUE TITLE
Plotting from the Variable Explorer is not working for IPython consoles

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1475]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-07-04T11:49:22Z_

There are two things here:

1. It's not working at all for IPython consoles

2. You have to hit \<Enter> several times to make a plot appear when using an External Console.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1475_

**Comment by spyder-issues-migrator** [comment]
_From [bentkows...@gmail.com](https://code.google.com/u/114523486630528179401/) on 2013-10-03T09:48:30Z_

Somewhat linked to issue #1529 : Plot A List Of Floats In Variable Explorer Not Possible. https://code.google.com/p/spyderlib/issues/detail?id=1529

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-10-06T14:00:31Z_

I'm working on a fix for this right now :-)

**Labels:** -MS-v2.3 MS-v2.2.5

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-10-12T16:11:24Z_

**Labels:** -MS-v2.2.5 MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-10-14T07:08:31Z_

**Summary:** Plotting from the Variable Explorer is not working for IPython consoles  \<span class="oldvalue"> (was: Plotting from the Variable Explorer is not working correctly) \</span>

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-10-14T19:30:04Z_

This issue was updated by revision a41d9e5c1a7e .

**Status:** Started

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-10-14T19:30:05Z_

This issue was updated by revision 5ef286084993 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [bentkows...@gmail.com](https://code.google.com/u/114523486630528179401/) on 2013-10-15T03:42:03Z_

I'm using Spyder 2.2.5 and I assume the fix will included in the next release of Spyder... but my concern is, can this problem occur in interference with setting the inline plotting in the Ipython console? E.g. I have set the backend: module://IPython.zmq.pylab.backend_inline

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-10-15T06:48:29Z_

You're right: all bugfixes will go now to 2.3, our next major release.

This problem had nothing to do with inline backend. It was just that we were not sending the plotting commands to IPython, that was all :)

**Comment by spyder-issues-migrator** [comment]
_From [bentkows...@gmail.com](https://code.google.com/u/114523486630528179401/) on 2013-10-15T06:50:19Z_

Then waiting forward to see 2.3 ! Thanks for your answer.

 P.

**Comment by spyder-issues-migrator** [comment]
_From [jcbr...@symvionics.com](https://code.google.com/u/115430633681747940486/) on 2015-01-07T17:47:56Z_

I just had this happen using Spyder 2.3.2, Python 2.7.8-0

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-07T17:53:01Z_

Works for me on Linux

**Comment by spyder-issues-migrator** [comment]
_From [petergbr...@gmail.com](https://code.google.com/u/108196277072313243431/) on 2015-01-16T07:10:29Z_

I get the following error when trying to plot/histogram with variable explorer

AttributeError: 'NoneType' object has no attribute 'shellwidget'
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\spyderlib\widgets\dicteditor.py", line 593, in \<lambda>
    triggered=lambda: self.plot_item('hist'))
  File "C:\Anaconda\lib\site-packages\spyderlib\widgets\dicteditor.py", line 939, in plot_item
    self.plot(key, funcname)
  File "C:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\namespacebrowser.py", line 409, in plot
    self.ipyclient.shellwidget.execute("%%varexp --%s %s" % (funcname,
AttributeError: 'NoneType' object has no attribute 'shellwidget'

Using Spyder 2.3.1 with Anaconda distro Python 2.7.8 64 bits, Qt 4.8.6, PyQt4 (API v2) 4.10.4 on Windows

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-30T13:53:57Z_

I don't understand this error. Do you have an IPython console open or not?
