### ISSUE TITLE
spyder installed through Anaconda doesn't start

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1476]
_From [michael....@gmail.com](https://code.google.com/u/116795421398492382070/) on 2013-07-04T20:17:39Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. type spyder at command prompt 2. 3. What is the expected output? What do you see instead? Spyder does not boot up      Here is the Linux terminal output

michael@michael-desktop:~$ spyder -reset
Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 30 days
Usage: spyder [options] files

spyder: error: no such option: -r
michael@michael-desktop:~$ spyder --reset
Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 30 days
*** Reset Spyder settings to defaults ***
removing: /home/michael/.spyder2/.inspector
removing: /home/michael/.spyder2/.spyder.ini
removing: /home/michael/.spyder2/.temp.py
removing: /home/michael/.spyder2/template.py
removing: /home/michael/.spyder2/.history_internal.py
removing: /home/michael/.spyder2/.ropeproject
removing: /home/michael/.spyder2/.workingdir
michael@michael-desktop:~$ spyder
Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 30 days
Warning: None of the following fonts is installed: ['Monospace', 'DejaVu Sans Mono', 'Consolas', 'Monaco', 'Bitstream Vera Sans Mono', 'Andale Mono', 'Liberation Mono', 'Courier New', 'Courier', 'monospace', 'Fixed', 'Terminal']
Warning: None of the following fonts is installed: ['Monospace', 'DejaVu Sans Mono', 'Consolas', 'Monaco', 'Bitstream Vera Sans Mono', 'Andale Mono', 'Liberation Mono', 'Courier New', 'Courier', 'monospace', 'Fixed', 'Terminal']
Warning: None of the following fonts is installed: ['Monospace', 'DejaVu Sans Mono', 'Consolas', 'Monaco', 'Bitstream Vera Sans Mono', 'Andale Mono', 'Liberation Mono', 'Courier New', 'Courier', 'monospace', 'Fixed', 'Terminal']
X Error: BadCursor (invalid Cursor parameter) 6
  Major opcode: 2 (X_ChangeWindowAttributes)
  Resource id:  0x3
X Error: BadCursor (invalid Cursor parameter) 6
  Major opcode: 95 (X_FreeCursor)
  Resource id:  0x3
X Error: BadCursor (invalid Cursor parameter) 6
  Major opcode: 2 (X_ChangeWindowAttributes)
  Resource id:  0x3
X Error: BadCursor (invalid Cursor parameter) 6
  Major opcode: 2 (X_ChangeWindowAttributes)
  Resource id:  0x3
X Error: BadCursor (invalid Cursor parameter) 6
  Major opcode: 95 (X_FreeCursor)
  Resource id:  0x3
X Error: BadCursor (invalid Cursor parameter) 6
  Major opcode: 2 (X_ChangeWindowAttributes)
  Resource id:  0x3
X Error: BadCursor (invalid Cursor parameter) 6
  Major opcode: 95 (X_FreeCursor)
  Resource id:  0x3
Traceback (most recent call last):
  File "/home/michael/anaconda/lib/python2.7/site-packages/spyderlib/spyder.py", line 2094, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/michael/anaconda/lib/python2.7/site-packages/spyderlib/spyder.py", line 1989, in run_spyder
    main.setup()
  File "/home/michael/anaconda/lib/python2.7/site-packages/spyderlib/spyder.py", line 783, in setup
    self.extconsole = ExternalConsole(self, light_mode=self.light)
  File "/home/michael/anaconda/lib/python2.7/site-packages/spyderlib/plugins/externalconsole.py", line 477, in __init__
    scientific = scientific_libs_available(executable)
  File "/home/michael/anaconda/lib/python2.7/site-packages/spyderlib/plugins/externalconsole.py", line 58, in scientific_libs_available
    for m in mods]
  File "/home/michael/anaconda/lib/python2.7/site-packages/spyderlib/utils/programs.py", line 269, in is_module_installed
    return eval(output)
  File "<string>", line 1
    Vendor:  Continuum Analytics, Inc.
          ^
SyntaxError: invalid syntax
Segmentation fault (core dumped) What version of the product are you using? On what operating system? spyder 2.2.0 installed through anaconda  on Ubuntu 12.04 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1476_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-07-04T18:30:52Z_

Thanks for reporting, I'll take a look at it this weekend but it could take us a while to fix this bug (not that much, just until our next stable version is released, which we plan to do in about a month).

**Summary:** spyder installed through Anaconda doesn't start  \<span class="oldvalue"> (was: spyder installed through anaconda does not boot up) \</span>  
  **Labels:** MS-v2.3 Cat-Miscelleneous

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-07-05T09:47:07Z_

Sure looks like the same problem as reported here: https://groups.google.com/d/msg/spyderlib/k4sn28OHmd8/jjkYUrXmVZIJ

**Comment by spyder-issues-migrator** [comment]
_From [michael....@gmail.com](https://code.google.com/u/116795421398492382070/) on 2013-07-05T15:07:19Z_

It looks the same I would just add that this error occurs on the first run of spyder without doing a reset. I have attached the crash log from a first run.

**Attachment:** [spyder_crash.log](http://code.google.com/p/spyderlib/issues/detail?id=1476#hc3)

**Comment by spyder-issues-migrator** [comment]
_From [michael....@gmail.com](https://code.google.com/u/116795421398492382070/) on 2013-08-07T19:57:55Z_

This error has been fixed I don't know how to acknowledge that.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-09T19:53:15Z_

Ok, really glad to hear that it's not an issue anymore for you.

**Status:** Fixed  
  **Labels:** -MS-v2.3
