### ISSUE TITLE
Spyder has encountered an internal problem

### ISSUE THREAD

**Issue by mbm87** [spyder-ide/spyder#14773]
### What steps will reproduce the problem?

I just ran my program and after 10 iterations of my code, in the ninth or tenth iteration (depending on the execution), the Issue reporter popped up on my screen. Despite this, the program finished properly, so I do not know why this is happening. I am using the python multiprocessing library. 

### Traceback
```python-traceback
  File "/home/mario/.conda/envs/myenv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 444, in _run_callback
    callback(*args, **kwargs)
  File "/home/mario/.conda/envs/myenv/lib/python3.9/site-packages/jupyter_client/threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/home/mario/.conda/envs/myenv/lib/python3.9/site-packages/jupyter_client/session.py", line 921, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'ec129b406721161d312f56ca32f9616d1efe3af28aebe29f861c342a124273a7'
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/home/mario/.conda/envs/myenv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 462, in _handle_events
    self._handle_recv()
  File "/home/mario/.conda/envs/myenv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 492, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/mario/.conda/envs/myenv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 444, in _run_callback
    callback(*args, **kwargs)
  File "/home/mario/.conda/envs/myenv/lib/python3.9/site-packages/jupyter_client/threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/home/mario/.conda/envs/myenv/lib/python3.9/site-packages/jupyter_client/session.py", line 921, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'ec129b406721161d312f56ca32f9616d1efe3af28aebe29f861c342a124273a7'
ERROR:tornado.application:Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x7f5565ebff70>)
Traceback (most recent call last):
  File "/home/mario/.conda/envs/myenv/lib/python3.9/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/home/mario/.conda/envs/myenv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 548, in <lambda>
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "/home/mario/.conda/envs/myenv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 462, in _handle_events
    self._handle_recv()
  File "/home/mario/.conda/envs/myenv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 492, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/mario/.conda/envs/myenv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 444, in _run_callback
    callback(*args, **kwargs)
  File "/home/mario/.conda/envs/myenv/lib/python3.9/site-packages/jupyter_client/threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/home/mario/.conda/envs/myenv/lib/python3.9/site-packages/jupyter_client/session.py", line 921, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'ec129b406721161d312f56ca32f9616d1efe3af28aebe29f861c342a124273a7'
```

## Versions

* Spyder version: 4.2.1 
* Python version: 3.9.1
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Linux 4.19.0-14-amd64

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.20.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.0.1 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.7.4 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  49.6.0.post20210108 (OK)
sphinx >=0.6.6                  :  3.4.3 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.1 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  1.0.2 (OK)
xdg >=0.26                      :  0.27 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.3.2 (OK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.2.1 (OK)
scipy >=0.17.0                  :  1.6.0 (OK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by mbm87** [comment]
Thank you, you are so kind
