### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by meetu30** [spyder-ide/spyder#14778]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. uninstalled Anaconda and reinstalled it
2. got latest version of anaconda and spyder
3. 

### What is the expected output? What do you see instead?
Spyder , jupyter nothing is working on anaconda

### Paste Traceback/Error Below (if applicable)

```python-traceback


PASTE TRACEBACK HERE
The error is:

Traceback (most recent call last):
File "C:\Users\mx007\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole\plugin.py", line 1413, in create_kernel_manager_and_kernel_client
kernel_manager = SpyderKernelManager(
File "C:\Users\mx007\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1030, in __new__
inst.setup_instance(*args, **kwargs)
File "C:\Users\mx007\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1066, in setup_instance
super(HasTraits, self).setup_instance(*args, **kwargs)
File "C:\Users\mx007\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1053, in setup_instance
value.instance_init(self)
File "C:\Users\mx007\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1857, in instance_init
self._resolve_classes()
File "C:\Users\mx007\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1862, in _resolve_classes
self.klass = self._resolve_string(self.klass)
File "C:\Users\mx007\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1692, in _resolve_string
return import_item(string)
File "C:\Users\mx007\Anaconda3\lib\site‑packages\traitlets\utils\importstring.py", line 30, in import_item
module = __import__(package, fromlist=[obj])
File "C:\Users\mx007\Anaconda3\lib\site‑packages\jupyter_client\session.py", line 41, in 
from jupyter_client.jsonutil import extract_dates, squash_dates, date_default
File "C:\Users\mx007\Anaconda3\lib\site‑packages\jupyter_client\jsonutil.py", line 10, in 
from dateutil.parser import parse as _dateutil_parse
File "C:\Users\mx007\AppData\Roaming\Python\Python38\site‑packages\dateutil\parser.py", line 158
l.append("%s=%s" % (attr, `value`))
^
SyntaxError: invalid syntax
```

## Versions

* Spyder version: 4.2.1
* Python version: 3.8
* Qt version: 
* PyQt version: 
* Operating System name/version: windows

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @meetu30, thanks for reporting. Please remove this directory:

    C:\Users\mx007\AppData\Roaming\Python

That should fix your problem.

**Comment by meetu30** [comment]
Woww!!! it worked. After deleting that directory, it worked. Thank you so very much! 
But I am curious how did you figure out that this was the solution? because I tried your other solutions too, and they did not work. 
Also 1 follow up question, why did this error happen at the first place? Kindly help me understand that as well. 
thanks much once again!

**Comment by ccordoba12** [comment]
> But I am curious how did you figure out that this was the solution?

Looking at the error you posted, I saw that you're using Anaconda

**Comment by ccordoba12** [comment]
> Also 1 follow up question, why did this error happen at the first place? Kindly help me understand that as well.

It happens when you use `pip install --user <package>` to install some packages. That's not recommend because missing pip and conda packages generates this kind of errors.

**Comment by meetu30** [comment]
Thank you so much Carlos!
