### ISSUE TITLE
Dask dataframe delayed

### ISSUE THREAD

**Issue by arthurrinaldi** [spyder-ide/spyder#14771]
### What steps will reproduce the problem?

When I am delaying the task using dask dataframe, every time I write somethin in the console, it re do all previous delayed even not related

### Traceback
```python-traceback
  File "/Users/arthurrinaldi/opt/anaconda3/envs/py38/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/widgets/namespacebrowser.py", line 97, in get_value
    return self.call_kernel(
  File "/Users/arthurrinaldi/opt/anaconda3/envs/py38/lib/python3.8/site-packages/spyder_kernels/comms/commbase.py", line 549, in __call__
    return self._comms_wrapper._get_call_return_value(
  File "/Users/arthurrinaldi/opt/anaconda3/envs/py38/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 151, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
  File "/Users/arthurrinaldi/opt/anaconda3/envs/py38/lib/python3.8/site-packages/spyder_kernels/comms/commbase.py", line 427, in _get_call_return_value
    self._wait_reply(call_id, call_name, timeout)
  File "/Users/arthurrinaldi/opt/anaconda3/envs/py38/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 168, in _wait_reply
    self._wait(got_reply, self._sig_got_reply, timeout_msg, timeout)
  File "/Users/arthurrinaldi/opt/anaconda3/envs/py38/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 205, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for {'8280509fba4640dc8fe1348eb00d17e1': (False, <bound method NamepaceBrowserWidget.set_var_properties of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x7fc3123e9ca0>>), 'b9a316d803624c628957cdbe0eace1a7': (False, <bound method NamepaceBrowserWidget.set_namespace_view of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x7fc3123e9ca0>>), '0e5a98f6dfee4f1dbd6f6a90dedf76c2': (False, <bound method NamepaceBrowserWidget.set_var_properties of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x7fc3123e9ca0>>), '01bf892cdd2240269314b423dc11a4a4': (False, <bound method NamepaceBrowserWidget.set_namespace_view of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x7fc3123e9ca0>>), '4eecbe007c2c4bf19b805819a1a48589': (False, <bound method NamepaceBrowserWidget.set_var_properties of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x7fc3123e9ca0>>), '6061c9496b7e4eb385b38ba275d21029': (False, <bound method NamepaceBrowserWidget.set_namespace_view of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x7fc3123e9ca0>>), '1d83744d9ec944b881a29b3cfb00320d': (False, <bound method NamepaceBrowserWidget.set_var_properties of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x7fc3123e9ca0>>), '8e55e9b70d11484ba5207431b663a778': (False, <bound method NamepaceBrowserWidget.set_namespace_view of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x7fc3123e9ca0>>), '33728f454d034a9db87dfb98a49c5431': (False, <bound method NamepaceBrowserWidget.set_var_properties of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x7fc3123e9ca0>>), '212348630ec640a98fe5b795e251b086': (False, <bound method NamepaceBrowserWidget.set_namespace_view of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x7fc3123e9ca0>>), '01b20ccba54447eeaffe0522947e19fa': (False, <bound method NamepaceBrowserWidget.set_var_properties of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x7fc3123e9ca0>>), '0c2c17b7a329472fb3c547a6a6360007': (False, <bound method NamepaceBrowserWidget.set_namespace_view of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x7fc3123e9ca0>>), '9c49d097e43c429f95e13592d464b419': (False, <bound method NamepaceBrowserWidget.set_var_properties of <spyder.plugins.ipythonconsole.widgets.shell.ShellWidget object at 0x7fc3123e9ca0>>), '163c09ea0f604429850ef7fb2b1ea1fe': (True, None)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/arthurrinaldi/opt/anaconda3/envs/py38/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 1057, in copy
    obj = self.delegate.get_value(idx)
  File "/Users/arthurrinaldi/opt/anaconda3/envs/py38/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 1392, in get_value
    return self.parent().get_value(name)
  File "/Users/arthurrinaldi/opt/anaconda3/envs/py38/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 1450, in get_value
    value = self.shellwidget.get_value(name)
  File "/Users/arthurrinaldi/opt/anaconda3/envs/py38/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/widgets/namespacebrowser.py", line 102, in get_value
    raise ValueError(msg % reason_big)
ValueError: La variable est trop grosse pour être récupérée.<br><br>Note : S'il vous plaît, ne signalez pas ce problème sur Github, il n'y a rien à faire à ce sujet.
```

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.1
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.6.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.3.1 (OK)
numpy >=1.7                    :  1.19.1 (OK)
pandas >=0.13.1                :  1.1.2 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by steff456** [comment]
Hi @arthurrinaldi,

Can you please share with me a code example to see if I'm able to reproduce this issue?

**Comment by arthurrinaldi** [comment]
HI @steff456, yes sure, thanks for your answer.

I am using the following function to read paquet files:

```
def get_file_list(glob_in, slct_run_id=None):
    if not slct_run_id:
        slct_run_id = def_run.run_id
    files = [fn for fn in glob_in if any(fn.endswith('{:04d}.parq'.format(run_id)) for run_id in slct_run_id)]
    return sorted(files)
```

    
    
```
def ddf_from_parquet(pattern, slct_run_id=None, as_df=False, columns=None):
    '''Read all parquet files of a certain file name pattern with certain run_ids'''
    @delayed
    def load_chunk(pth, columns):
        return ParquetFile(pth).to_pandas(columns=columns)

    files = get_file_list(glob(sc_out + pattern), slct_run_id)
    assert len(files) > 0, f'Pattern {sc_out + pattern} yields empty file list.'
    ddf = dd.from_delayed([load_chunk(f, columns=columns) for f in files])
    if as_df:
        ddf = ddf.compute()
    
    return ddf
```

The run_id and select_run_id are just a way to not read all the output parquet files of my model.

Then I just start my local client cluster

```
from dask.distributed import Client
client = Client()
```

Then I am reading the files using the function and delaying it to not use too much memory

`ddfpwr = ddf_from_parquet(pattern='/var_sy_pwr*', slct_run_id=slct_run_id)`

I do all sorts of query and merging with different dask dataframe and then I compute them if I need to use it like this:

`dfpwr = ddfpwr.compute()`

I see using the dashboard of dask dataframe that it is computing and it finishes but afterward, any command in the console which have no link to the previous dataframe simply just redo all of the delayed action every time which is blocking spyder and not allowing me the view the variable in the variable explorer until it finishes re-computing.

Hope it helps and if you need my parquet files I can send it althought they are big folders (2-5 GB).

Many thanks
Arthur

**Comment by ccordoba12** [comment]
@arthurrinaldi, thanks for the reproducible example and all the details.

@impact27, any ideas about this?

**Comment by impact27** [comment]
I am not familliar with dask but maybe it integrates with the ipython eventloop? Maybe something like: https://ipython.readthedocs.io/en/stable/config/callbacks.html#post-execute

**Comment by ccordoba12** [comment]
But what I don't understand is why we're calling get_value when computing the namespace representation. That's very strange to me and it looks like an error in our side.
