### ISSUE TITLE
'Report issue' doesn't work in Python 3

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1480]
_From [tak...@gmail.com](https://code.google.com/u/116141806100272241943/) on 2013-07-05T17:42:02Z_

IPython has a Python-3 compatible version of pickleshare.py if that helps. 

What steps will reproduce the problem?

 1. Go to ? > Report issue...

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/spyderlib/spyder.py", line 1605, in report_issue
    url.addEncodedQueryItem("comment", urllib.quote(issue_template))
AttributeError: 'module' object has no attribute 'quote'
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/spyderlib/spyder.py", line 1605, in report_issue
    url.addEncodedQueryItem("comment", urllib.quote(issue_template))
AttributeError: 'module' object has no attribute 'quote'
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/spyderlib/widgets/editor.py", line 194, in run
    self.submods = get_preferred_submodules()
  File "/usr/local/lib/python3.2/dist-packages/spyderlib/utils/module_completion.py", line 288, in get_preferred_submodules
    modules_db['submodules'] = submodules
  File "/usr/local/lib/python3.2/dist-packages/spyderlib/utils/external/pickleshare.py", line 94, in __setitem__
    pickled = pickle.dump(value, fil.open('w'))
TypeError: must be str, not bytes

(By the way, I understand from Carlos that Python 3 support is a current focus, but let me know if you want me to lay off filing bugs for it.)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1480_

**Comment by spyder-issues-migrator** [comment]
_From [tak...@gmail.com](https://code.google.com/u/116141806100272241943/) on 2013-07-08T14:38:47Z_

Here's a patch.

The pickleshare error was actually something different, affecting code inspection. I've borrowed a couple of changes from IPython's copy of pickleshare, and it seems to be working now.

**Attachment:** [py3fixes.patch](http://code.google.com/p/spyderlib/issues/detail?id=1480#hc1)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-08-12T12:15:48Z_

This issue was updated by revision 3ebffbc9298b .

**Status:** Fixed
