### ISSUE TITLE
IT WON'T LAUNCH

### ISSUE THREAD

**Issue by whittaker802** [spyder-ide/spyder#14817]
### What steps will reproduce the problem?

The program wont launch after using the anaconda environment, or using standalone version

### Traceback
```python-traceback
  File "C:\Users\whic1701\Anaconda3\envs\conda11\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\whic1701\Anaconda3\envs\conda11\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 172, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\whic1701\Anaconda3\envs\conda11\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 61, in refresh_namespacebrowser
    self.call_kernel(
  File "C:\Users\whic1701\Anaconda3\envs\conda11\lib\site-packages\spyder_kernels\comms\commbase.py", line 549, in __call__
    return self._comms_wrapper._get_call_return_value(
  File "C:\Users\whic1701\Anaconda3\envs\conda11\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 130, in _get_call_return_value
    with self.comm_channel_manager(comm_id, queue_message=not interrupt):
  File "C:\Users\whic1701\Anaconda3\envs\conda11\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "C:\Users\whic1701\Anaconda3\envs\conda11\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 84, in comm_channel_manager
    self._wait(self.comm_channel_connected,
  File "C:\Users\whic1701\Anaconda3\envs\conda11\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 168, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for comm port.
Traceback (most recent call last):
  File "C:\Users\whic1701\Anaconda3\envs\conda11\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\whic1701\Anaconda3\envs\conda11\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 172, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\whic1701\Anaconda3\envs\conda11\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 61, in refresh_namespacebrowser
    self.call_kernel(
  File "C:\Users\whic1701\Anaconda3\envs\conda11\lib\site-packages\spyder_kernels\comms\commbase.py", line 549, in __call__
    return self._comms_wrapper._get_call_return_value(
  File "C:\Users\whic1701\Anaconda3\envs\conda11\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 130, in _get_call_return_value
    with self.comm_channel_manager(comm_id, queue_message=not interrupt):
  File "C:\Users\whic1701\Anaconda3\envs\conda11\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "C:\Users\whic1701\Anaconda3\envs\conda11\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 84, in comm_channel_manager
    self._wait(self.comm_channel_connected,
  File "C:\Users\whic1701\Anaconda3\envs\conda11\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 168, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for comm port.
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest'}}
```

## Versions

* Spyder version: 4.1.3 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  4.0.0 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.20.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.8.0 (OK)
pygments >=2.0                 :  2.8.0 (OK)
pylint >=0.25                  :  2.7.0 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  5.0.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.5.1 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  20.0.0 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment]
Hey @whittaker802, this is fixed in our 4.2.1 version. Please update by running the following command in the Anaconda Prompt:

    conda update anaconda
    conda install spyder=4.2.1
