### ISSUE TITLE
Spyder crashed suddenly and not opening anymore

### ISSUE THREAD

**Issue by vivigb** [spyder-ide/spyder#14832]
I cannot open spyder after it crashed suddenly.

I tried :
Windows restarted
spyder --reset

Traceback I am getting:

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\roses\lib\site-packages\qtpy\__init__.py", line 204, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\roses\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\envs\roses\lib\site-packages\spyder\app\start.py", line 210, in main
    from spyder.app import mainwindow
  File "C:\ProgramData\Anaconda3\envs\roses\lib\site-packages\spyder\app\mainwindow.py", line 45, in <module>
    requirements.check_qt()
  File "C:\ProgramData\Anaconda3\envs\roses\lib\site-packages\spyder\requirements.py", line 41, in check_qt
    import qtpy
  File "C:\ProgramData\Anaconda3\envs\roses\lib\site-packages\qtpy\__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

```

## Versions
Windows 10
Anaconda

**Comment by ccordoba12** [comment]
Hey @vivigb, thanks for reporting. Please take a look at [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to learn how to solve this problem.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
