### ISSUE TITLE
socket error

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1486]
_From [budou.w...@gmail.com](https://code.google.com/u/100100039479641201467/) on 2013-07-12T22:16:23Z_

Spyder Version:  2.2.1
Python Version:  2.7.3
Qt Version:      4.7.0, PyQt4 (API v1) 4.8.1 on Windows 

What steps will reproduce the problem?

 1.Run any python script code What is the expected output? What do you see instead? >>> Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 232, in qt_inputhook
    monitor.refresh_from_inputhook()
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 307, in refresh_from_inputhook
    self.refresh()
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 297, in refresh
    communicate(self.n_request, dict(command="refresh"))
  File "C:\Python27\lib\site-packages\spyderlib\utils\bsdsocket.py", line 97, in communicate
    write_packet(sock, command)
  File "C:\Python27\lib\site-packages\spyderlib\utils\bsdsocket.py", line 45, in write_packet
    nsend -= temp_fail_retry(socket.error, sock.send, sent_data)
  File "C:\Python27\lib\site-packages\spyderlib\utils\bsdsocket.py", line 25, in temp_fail_retry
    return fun(*args)
socket.error: [Errno 10054] 

Please provide any additional information below

. None

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1486_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-15T09:30:58Z_

I hope by now this is working well for you :-)

**Status:** WontFix
