### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by BhardwajJyoti** [spyder-ide/spyder#14879]
### What steps will reproduce the problem?

The following error is coming up, each time I am running the SPYDER IDE. I am using Spyder with Python 3.9 (latest version)Please guide me.

The error is:

Traceback (most recent call last):
File "c:\python 3.9.2\lib\site‑packages\traitlets\traitlets.py", line 535, in get
value = obj._trait_values[self.name]
KeyError: 'context'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "c:\python 3.9.2\lib\site‑packages\spyder\plugins\ipythonconsole\plugin.py", line 1422, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle,
File "c:\python 3.9.2\lib\site‑packages\jupyter_client\manager.py", line 314, in start_kernel
self.post_start_kernel(**kw)
File "c:\python 3.9.2\lib\site‑packages\qtconsole\manager.py", line 57, in post_start_kernel
super().post_start_kernel(**kw)
File "c:\python 3.9.2\lib\site‑packages\jupyter_client\manager.py", line 295, in post_start_kernel
self._connect_control_socket()
File "c:\python 3.9.2\lib\site‑packages\jupyter_client\manager.py", line 228, in _connect_control_socket
self._control_socket = self._create_connected_socket('control')
File "c:\python 3.9.2\lib\site‑packages\jupyter_client\connect.py", line 545, in _create_connected_socket
sock = self.context.socket(socket_type)
File "c:\python 3.9.2\lib\site‑packages\traitlets\traitlets.py", line 575, in __get__
return self.get(obj, cls)
File "c:\python 3.9.2\lib\site‑packages\traitlets\traitlets.py", line 538, in get
default = obj.trait_defaults(self.name)
File "c:\python 3.9.2\lib\site‑packages\traitlets\traitlets.py", line 1578, in trait_defaults
return self._get_trait_default_generator(names[0])(self)
File "c:\python 3.9.2\lib\site‑packages\jupyter_client\manager.py", line 45, in _context_default
return zmq.Context()
File "zmq\backend\cython\context.pyx", line 48, in zmq.backend.cython.context.Context.__cinit__
zmq.error.ZMQError: Unknown error

## Versions

* Spyder version: 4.2.3 
* Python version: 3.9.2
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.21.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  23.0.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.0 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
setuptools >=39.0.0             :  49.2.1 (OK)
sphinx >=0.6.6                  :  3.5.2 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  22.0.3 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  None (NOK)
numpy >=1.7                     :  None (NOK)
pandas >=1.1.1                  :  None (NOK)
scipy >=0.17.0                  :  None (NOK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @BhardwajJyoti, thanks for reporting. Please read our Troubleshooting Guide to try to solve this problem:

http://docs.spyder-ide.org/current/first-steps.html

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.
