### ISSUE TITLE
unicode crashed spyder

### ISSUE THREAD

**Issue by emmett-b** [spyder-ide/spyder#14921]
### What steps will reproduce the problem?

copy paste a formula from power point equation tool and mess with it

### Traceback
```python-traceback
  File "C:\Users\tdesrues\Miniconda3\envs\myenv\lib\site-packages\spyder\utils\syntaxhighlighters.py", line 298, in highlightBlock
    self.highlight_block(text)
  File "C:\Users\tdesrues\Miniconda3\envs\myenv\lib\site-packages\spyder\utils\syntaxhighlighters.py", line 621, in highlight_block
    self.setFormat(0, qstring_length(text), self.formats["normal"])
  File "C:\Users\tdesrues\Miniconda3\envs\myenv\lib\site-packages\spyder\utils\qstringhelpers.py", line 19, in qstring_length
    utf16_text = text.encode('utf16')
UnicodeEncodeError: 'utf-16' codec can't encode character '\udf16' in position 24: surrogates not allowed
Traceback (most recent call last):
  File "C:\Users\tdesrues\Miniconda3\envs\myenv\lib\site-packages\spyder\utils\encoding.py", line 200, in encode
    return text.encode(coding), coding
UnicodeEncodeError: 'utf-8' codec can't encode character '\udf16' in position 496: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tdesrues\Miniconda3\envs\myenv\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 135, in do_autosave
    stack.autosave.autosave_all()
  File "C:\Users\tdesrues\Miniconda3\envs\myenv\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 417, in autosave_all
    self.maybe_autosave(index)
  File "C:\Users\tdesrues\Miniconda3\envs\myenv\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 386, in maybe_autosave
    self.autosave(finfo)
  File "C:\Users\tdesrues\Miniconda3\envs\myenv\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 405, in autosave
    self.stack._write_to_file(finfo, autosave_filename)
  File "C:\Users\tdesrues\Miniconda3\envs\myenv\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1976, in _write_to_file
    fileinfo.encoding = encoding.write(txt, filename, fileinfo.encoding)
  File "C:\Users\tdesrues\Miniconda3\envs\myenv\lib\site-packages\spyder\utils\encoding.py", line 235, in write
    text, encoding = encode(text, encoding)
  File "C:\Users\tdesrues\Miniconda3\envs\myenv\lib\site-packages\spyder\utils\encoding.py", line 202, in encode
    raise RuntimeError("Incorrect encoding (%s)" % coding)
RuntimeError: Incorrect encoding (utf-8)
```

## Versions

* Spyder version: 4.1.5 
* Python version: 3.7.9
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.19.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.2 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment]
Hey @emmett-b, thanks for reporting. You said

> copy paste a formula from power point equation tool and mess with it

Could you post that formula here so we can try to reproduce the error in our side? Otherwise, it won't be possible for us to fix it, sorry.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
