### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by prakash-9** [spyder-ide/spyder#14946]
### What steps will reproduce the problem?

I have know idea what happened here ut all of sudden kernel stopped working in spyder

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 20.3.0

### Dependencies

```
applaunchservices >=0.1.7    :  0.2.1 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by dalthviz** [comment]
Hi @prakash-9 could you provide us more information? Do you get any traceback or error message? Without more info there is not much that we can do to help, sorry :/

**Comment by prakash-9** [comment]
@dalthviz Please find below the detailed error that I am getting in Kernel:

Traceback (most recent call last):
File "/Users/headout/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/Users/headout/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/Users/headout/opt/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/Users/headout/opt/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 287, in main
import_spydercustomize()
File "/Users/headout/opt/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 39, in import_spydercustomize
import spydercustomize
File "/Users/headout/opt/anaconda3/lib/python3.7/site‑packages/spyder_kernels/customize/spydercustomize.py", line 14, in 
import bdb
File "/Users/headout/opt/anaconda3/lib/python3.7/bdb.py", line 6, in 
from inspect import CO_GENERATOR, CO_COROUTINE, CO_ASYNC_GENERATOR
File "/Users/headout/opt/anaconda3/lib/python3.7/inspect.py", line 40, in 
import linecache
File "/Users/headout/opt/anaconda3/lib/python3.7/linecache.py", line 11, in 
import tokenize
File "/Users/headout/opt/anaconda3/lib/python3.7/tokenize.py", line 35, in 
from token import *
File "/Users/headout/token.py", line 1, in 
import requests
File "/Users/headout/opt/anaconda3/lib/python3.7/site‑packages/requests/__init__.py", line 95, in 
from urllib3.contrib import pyopenssl
File "/Users/headout/opt/anaconda3/lib/python3.7/site‑packages/urllib3/contrib/pyopenssl.py", line 46, in 
import OpenSSL.SSL
File "/Users/headout/opt/anaconda3/lib/python3.7/site‑packages/OpenSSL/__init__.py", line 8, in 
from OpenSSL import crypto, SSL
File "/Users/headout/opt/anaconda3/lib/python3.7/site‑packages/OpenSSL/crypto.py", line 12, in 
from cryptography import x509
File "/Users/headout/opt/anaconda3/lib/python3.7/site‑packages/cryptography/x509/__init__.py", line 8, in 
from cryptography.x509.base import (
File "/Users/headout/opt/anaconda3/lib/python3.7/site‑packages/cryptography/x509/base.py", line 14, in 
from cryptography import utils
File "/Users/headout/opt/anaconda3/lib/python3.7/site‑packages/cryptography/utils.py", line 94, in 
signature = inspect.getargspec
AttributeError: module 'inspect' has no attribute 'getargspec'

**Comment by dalthviz** [comment]
@prakash-9 by any chance you have some file in your code named `inspect.py`? Maybe what is happening is that your module is being used instead of the standard module `inspect`. Let us know if that's the case. If not I would recommend you to try to update Spyder (although as you are using Big Sur probably you will need to check this info first: http://docs.spyder-ide.org/current/faq.html?highlight=big%20sur#troubleshooting-macos-bigsur)

**Comment by prakash-9** [comment]
@dalthviz I have two version of python in my system one that comes inbuilt in mac python2.7 and one I downloaded python3.7
I tried searching inspect.py file in my system I am getting only one ion results however there are two inspect.pyi files. Not sure what are those? I actually tried uninstalling anaconda completely and then installed it again. But this issue is still there.

**Comment by dalthviz** [comment]
I think the `.pyi` files are used as a stub file to provide information about the types of a module but I don't think they are related to your issue.

Since you already tried to reinstall anaconda could you try to reset the Spyder preferences? Also maybe a look to our troubleshooting guide could be worthy: https://docs.spyder-ide.org/current/first-steps.html

This seems more like an installation issue so there is not much more we can do sorry :/ 

Let us know if the reset helps :)

**Comment by dalthviz** [comment]
Closing due to lack of response
