### ISSUE TITLE
A module is working in anaconda (and other IDE) prompt but not in Spyder

### ISSUE THREAD

**Issue by alquires** [spyder-ide/spyder#14949]
### What steps will reproduce the problem?

I installed gdal library. I had already installed it without problems on at least four other computers (in different versions of anaconda and gdal). I follow this tutorial: https://sandbox.idre.ucla.edu/sandbox/tutorials/installing-gdal-for-windows

I check the GDAL installations: In windows prompt:

```
gdalinfo --version
GDAL 3.0.4, released 2020/01/28
```

Ok!

But in Spyder and Jupyter in Anaconda prompt doesn't work:

```
(base) PS C:\Users\hilton\Anaconda3> python -c "from osgeo import gdal"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\hilton\Anaconda3\lib\site-packages\osgeo\__init__.py", line 41, in <module>
    _gdal = swig_import_helper()
  File "C:\Users\hilton\Anaconda3\lib\site-packages\osgeo\__init__.py", line 24, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "C:\Users\hilton\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\hilton\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Não foi possível encontrar o procedimento especificado.
```

So, I try in python.exe in Anaconda 3 installations (in my case: C:\Users\hilton\Anaconda3\python.exe)

```
>>> from osgeo import ogr
>>> multipoint = ogr.Geometry(ogr.wkbMultiPoint)
>>> point1 = ogr.Geometry(ogr.wkbPoint)
>>> point1.AddPoint(1251243.7361610543, 598078.7958668759
```

Works!

I checked the probability of different environments (https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder)

I followed the procedure:
1 - check the python console:
```
>>> import sys; sys.executable
'C:\\Users\\hilton\\Anaconda3\\python.exe'
```

2 - check the anaconda console:
```
>>> import sys; sys.executable
'C:\\Users\\hilton\\Anaconda3\\pythonw.exe'
```

I tried solve this way:

https://stackoverflow.com/questions/50038651/a-module-is-working-in-anaconda-prompt-but-not-in-spyder

"in Spyder go to Tools>Preferences>Python interpreter. Here you will see two options under Select the Python interpreter for all Spyder consoles. Check the second option and paste the path you copied from the Anaconda prompt. Close Spyder and open it again and now the import module command should work."

I try to create an environment, using version python 3.6.9 (where gdal works on my other computer). In the same way, works in console, but not in spyder:

```
from osgeo import gdal
Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\osgeo\__init__.py", line 18, in swig_import_helper
    return importlib.import_module(mname)

  File "C:\ProgramData\Anaconda3\envs\myenv\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 994, in _gcd_import

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load

  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 571, in module_from_spec

  File "<frozen importlib._bootstrap_external>", line 922, in create_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

ImportError: DLL load failed: Não foi possível encontrar o procedimento especificado.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-1-61e0eefce4de>", line 1, in <module>
    from osgeo import gdal

  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\osgeo\__init__.py", line 32, in <module>
    _gdal = swig_import_helper()

  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\osgeo\__init__.py", line 31, in swig_import_helper
    return importlib.import_module('_gdal')

  File "C:\ProgramData\Anaconda3\envs\myenv\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

ModuleNotFoundError: No module named '_gdal'

```

Finally, I try other IDE  (VS Code and PyCharm) and gdal works fine. I love spyder, but I don't see another way to fix this problem.

## Versions

* Spyder version: 4.2.3 
* Python version: 3.6.9
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=7.6.0                 :  7.16.1 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  23.0.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  49.6.0.post20210108 (OK)
sphinx >=0.6.6                  :  3.5.2 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  22.0.3 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  None (NOK)
numpy >=1.7                     :  1.19.5 (OK)
pandas >=1.1.1                  :  None (NOK)
scipy >=0.17.0                  :  None (NOK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by ccordoba12** [comment]
> I follow this tutorial: https://sandbox.idre.ucla.edu/sandbox/tutorials/installing-gdal-for-windows

That tutorial is quite old and it's necessary for Anaconda. Please remove all changes you were instructed to do with it.

Then, please close Spyder, open the Anaconda Prompt, run there this command

    conda install gdal

and then open Spyder. It should work after that.

**Comment by alquires** [comment]
Let's go:

First, I cleared all installations (anaconda, pycharm, gdal binaries) and remove the environment variables (only the make references to python installations or gdal).

I maked download and install anaconda (https://repo.anaconda.com/archive/Anaconda3-2020.11-Windows-x86_64.exe)
	next>
	I Agree>
	Just me/Next>
	'C:\Users\hilton\Anaconda3'/Next>
	Unchecked: Add Anaconda3 to my PATH environment variable/Checked: Register Anaconda3 as my default Python 3.8/Install>
	Next>
	Finish

And I ran Anaconda prompt as administrator

`conda install gdal`

results here: 
[conda install gdal.txt](https://github.com/spyder-ide/spyder/files/6190453/conda.install.gdal.txt)

I try run in Spyder:
```
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.19.0 -- An enhanced Interactive Python.

import sys

sys.executable
Out[2]: 'C:\\Users\\hilton\\Anaconda3\\python.exe'

from osgeo import gdal
Traceback (most recent call last):

  File "<ipython-input-3-61e0eefce4de>", line 1, in <module>
    from osgeo import gdal

ModuleNotFoundError: No module named 'osgeo'
```


and Python.exe:
```
>>> import sys
>>> sys.executable
'C:\\Users\\hilton\\Anaconda3\\python.exe'
>>> from osgeo import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'osgeo'
```

So I created an environment and install gdal in the new environment.

`conda create -n myenv python=3.6.9`

Log here: 
[conda create -n myenv python=3.6.9.txt](https://github.com/spyder-ide/spyder/files/6190465/conda.create.-n.myenv.python.3.6.9.txt)


```
conda activate myenv
conda install gdal
```
Log here:
[myenv - conda install gdal.txt](https://github.com/spyder-ide/spyder/files/6190467/myenv.-.conda.install.gdal.txt)

And I used anaconda Navigator to create a spyder in the new environment (this way: https://stackoverflow.com/questions/30170468/how-to-run-spyder-in-virtual-environment) and try to execute gdal.

In Spyder:
```
Python 3.6.9 (default, Mar  6 2020, 20:53:49) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.16.1 -- An enhanced Interactive Python.

import sys

sys.executable
Out[2]: 'C:\\Users\\hilton\\Anaconda3\\envs\\myenv\\python.exe'

from osgeo import gdal
Traceback (most recent call last):

  File "C:\Users\hilton\Anaconda3\envs\myenv\lib\site-packages\osgeo\__init__.py", line 18, in swig_import_helper
    return importlib.import_module(mname)

  File "C:\Users\hilton\Anaconda3\envs\myenv\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 994, in _gcd_import

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load

  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 571, in module_from_spec

  File "<frozen importlib._bootstrap_external>", line 922, in create_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

ImportError: DLL load failed: Não foi possível encontrar o procedimento especificado.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-3-61e0eefce4de>", line 1, in <module>
    from osgeo import gdal

  File "C:\Users\hilton\Anaconda3\envs\myenv\lib\site-packages\osgeo\__init__.py", line 32, in <module>
    _gdal = swig_import_helper()

  File "C:\Users\hilton\Anaconda3\envs\myenv\lib\site-packages\osgeo\__init__.py", line 31, in swig_import_helper
    return importlib.import_module('_gdal')

  File "C:\Users\hilton\Anaconda3\envs\myenv\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

ModuleNotFoundError: No module named '_gdal'
```

In Python.exe:
```
Python 3.6.9 (default, Mar  6 2020, 20:53:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import gdal, ogr
>>> multipoint = ogr.Geometry(ogr.wkbMultiPoint)
>>> point1 = ogr.Geometry(ogr.wkbPoint)
>>> point1.AddPoint(1251243.7361610543, 598078.7958668759)
>>>
```
I installed pycharm again and when I run the code in a script it works, but if I write in the pycharm python console the same error occurs: ModuleNotFoundError: No module named '_gdal'

**Comment by ccordoba12** [comment]
Unfortunately, your problem is not directly related to Spyder but an installation issue with Gdal, and we can give support for that.

My last advice is to run

    conda update anaconda

before running

    conda install gdal

I hope that helps you.
