### ISSUE TITLE
TypeError thrown by IPython Console when the pager is off

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1498]
_From [novi...@gmail.com](https://code.google.com/u/117248594063299312220/) on 2013-07-29T02:56:09Z_

Spyder Version:  2.3.0dev3 (2909+: r438976af794c )
Python Version:  2.7.2
Qt Version:      4.7.3, PyQt4 (API v2) 4.8.5 on Windows

In [3]: from IPython import sys_info
   ...: print sys_info()
   ...: 
{'commit_hash': 'a9c0f49',
 'commit_source': 'repository',
 'default_encoding': 'cp1252',
 'ipython_path': 'c:\\dev\\code\\ipython\\IPython',
 'ipython_version': '1.0.0-dev',
 'os_name': 'nt',
 'platform': 'Windows-7-6.1.7601-SP1',
 'sys_executable': 'C:\\dev\\bin\\Python27\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)]'} 

What steps will reproduce the problem?

 -------------------------------------
With the latest dev checkout of IPython (though it has been happening for a while) when an IPython console is set to open on startup the error shown below is thrown in the Internal console.

```python
\>>> Traceback (most recent call last):
  File "C:\dev\code\spyderlib\spyderlib\plugins\externalconsole.py", line 889, in \<lambda>
    cf, kernel_widget=shellwidget))
  File "C:\dev\code\spyderlib\spyderlib\plugins\externalconsole.py", line 966, in create_ipyclient
    self.main.ipyconsole.new_client(connection_file, id(kernel_widget))
  File "C:\dev\code\spyderlib\spyderlib\plugins\ipythonconsole.py", line 903, in new_client
    self.register_client(cf, kernel_widget_id, client_name)
  File "C:\dev\code\spyderlib\spyderlib\plugins\ipythonconsole.py", line 1032, in register_client
    lambda: self.emit(SIGNAL('focus_changed()')))
TypeError: arguments did not match any overloaded call:
  QObject.connect(QObject, SIGNAL(), QObject, SLOT(), Qt.ConnectionType=Qt.AutoConnection): argument 1 has unexpected type 'NoneType'
  QObject.connect(QObject, SIGNAL(), callable, Qt.ConnectionType=Qt.AutoConnection): argument 1 has unexpected type 'NoneType'
  QObject.connect(QObject, SIGNAL(), SLOT(), Qt.ConnectionType=Qt.AutoConnection): argument 1 has unexpected type 'NoneType'
```

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1498_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-09T13:10:36Z_

This problem occurs when the user is not using the console pager. Thanks for reporting. I'll fix it in our next release.

**Summary:** TypeError thrown by IPython Console when the pager is off  \<span class="oldvalue"> (was: TypeError thrown by IPython Console) \</span>  
  **Status:** Accepted  
  **Labels:** Cat-IPythonConsole

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-10T09:08:16Z_

**Labels:** MS-v2.2.2

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-10T09:22:29Z_

This issue was updated by revision b629faa47c91 .


- We were trying to connect the pager to a signal without verifying if it
existed or not.

**Status:** Fixed
