### ISSUE TITLE
Console (Terminal) throws NotImplementedError for Home/End keys

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1499]
_From [novi...@gmail.com](https://code.google.com/u/117248594063299312220/) on 2013-07-29T03:00:28Z_

Spyder Version:  2.3.0dev3 (2909+: r438976af794c )
Python Version:  2.7.2
Qt Version:      4.7.3, PyQt4 (API v2) 4.8.5 on Windows 

What steps will reproduce the problem?

 1. Open a console (terminal)
2. Enter some text
3. Press the Home (or End) key What is the expected output? What do you see instead? Instead to moving to the start(/end) of the line the error shown below is thrown in the internal console.

\>>> Traceback (most recent call last):
  File "C:\dev\code\spyderlib\spyderlib\widgets\shell.py", line 302, in keyPressEvent
    self.postprocess_keyevent(event)
  File "C:\dev\code\spyderlib\spyderlib\widgets\shell.py", line 383, in postprocess_keyevent
    self._key_home(shift, ctrl)
  File "C:\dev\code\spyderlib\spyderlib\widgets\shell.py", line 472, in _key_home
    raise NotImplementedError
NotImplementedError

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1499_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-09T19:12:36Z_

By terminal you mean a Python one or system (i.e. cmd.exe) one?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-08-10T12:35:40Z_

This issue was updated by revision 4d55e76b7975 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-08-10T12:35:40Z_

This issue was closed by revision 667dc9997285 .

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-10T13:06:40Z_

**Labels:** MS-v2.2.2
