### ISSUE TITLE
qdarkstyle.colorsystem requirement missing

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#15053]
### What steps will reproduce the problem?

`qdarkstyle.colorsystem` seems to be missing from the macOS app, causing it to fail to launch.

```python
(spy-build) >> dist/Spyder.app/Contents/MacOS/Spyder --debug-info=verbose
Traceback (most recent call last):
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/__boot__.py", line 106, in <module>
    _run()
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/__boot__.py", line 84, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/Spyder.py", line 3, in <module>
    start.main()
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.9/spyder/app/start.py", line 223, in main
    from spyder.app import mainwindow
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.9/spyder/app/mainwindow.py", line 73, in <module>
    from spyder.app import tour
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.9/spyder/app/tour.py", line 38, in <module>
    from spyder.utils.qthelpers import add_actions, create_action
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.9/spyder/utils/qthelpers.py", line 35, in <module>
    from spyder.utils.icon_manager import ima
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.9/spyder/utils/icon_manager.py", line 23, in <module>
    from spyder.utils.palette import QStylePalette, SpyderPalette
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.9/spyder/utils/palette.py", line 12, in <module>
    from qdarkstyle.colorsystem import Blue, Gray
ModuleNotFoundError: No module named 'qdarkstyle.colorsystem'
2021-03-29 18:12:37.424 Spyder[28804:44576512] Spyder Error
```

I don't know why this does not manifest when bootstrapping. Please advise.

**Comment by mrclary** [comment]
FYI @ccordoba12

**Comment by mrclary** [comment]
I found the issue. I see we're using the subrepo. will fix for pull request builds.
