### ISSUE TITLE
Can't open new editor window

### ISSUE THREAD

**Issue by Smsmadly** [spyder-ide/spyder#15104]
### What steps will reproduce the problem?

i can not open window from tab
python 3.8
spyder 5.0.0 

### Traceback
```python-traceback
Traceback (most recent call last):
  File "c:\users\osama\appdata\local\programs\python\python38\lib\site-packages\spyder\plugins\editor\plugin.py", line 1647, in create_new_window
    oe_options = self.outlineexplorer.get_widget().get_options()
AttributeError: 'OutlineExplorerWidget' object has no attribute 'get_options'
Traceback (most recent call last):
  File "c:\users\osama\appdata\local\programs\python\python38\lib\site-packages\spyder\plugins\editor\plugin.py", line 1647, in create_new_window
    oe_options = self.outlineexplorer.get_widget().get_options()
AttributeError: 'OutlineExplorerWidget' object has no attribute 'get_options'
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.8.6
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.21.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  21.4.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.7.2 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.1 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
setuptools >=39.0.0           :  54.1.1 (OK)
sphinx >=0.6.6                :  3.2.1 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)
textdistance >=4.2.0          :  4.2.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  0.10.3 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.21 (OK)
matplotlib >=2.0.0            :  3.3.2 (OK)
numpy >=1.7                   :  1.19.5 (OK)
pandas >=1.1.1                :  1.2.3 (OK)
scipy >=0.17.0                :  1.5.2 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by steff456** [comment]
Hi @Smsmadly,

Thanks for reporting, we will fix this issue for the next release. @andfoy can you please take a look at this one?
