### ISSUE TITLE
Numpy run code analysis

### ISSUE THREAD

**Issue by Bug-Patrick** [spyder-ide/spyder#15138]
### What steps will reproduce the problem?

Created matrice and vertices with numpy, also imported matplotlib and run code analysis

### Traceback
```python-traceback
pylint error:

Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "D:\Program Files\Spyder\pkgs\pylint\__main__.py", line 9, in <module>
    pylint.run_pylint()
  File "D:\Program Files\Spyder\pkgs\pylint\__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "D:\Program Files\Spyder\pkgs\pylint\lint\__init__.py", line 75, in <module>
    from pylint.lint.parallel import check_parallel
  File "D:\Program Files\Spyder\pkgs\pylint\lint\parallel.py", line 7, in <module>
    from pylint import reporters
  File "D:\Program Files\Spyder\pkgs\pylint\reporters\__init__.py", line 24, in <module>
    from pylint import utils
  File "D:\Program Files\Spyder\pkgs\pylint\utils\__init__.py", line 45, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "D:\Program Files\Spyder\pkgs\pylint\utils\ast_walker.py", line 6, in <module>
    from astroid import nodes
  File "D:\Program Files\Spyder\pkgs\astroid\__init__.py", line 41, in <module>
    import enum
ModuleNotFoundError: No module named 'enum'

```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.4 (OK)
setuptools >=39.0.0           :  54.2.0 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.22 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.2.3 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.7.1 (OK)
```

**Comment by steff456** [comment]
Hi @Bug-Patrick,

Can you please upload the code and steps of what you did to have this error? In this way we can try to reproduce it on our end.

Thanks for reporting!

**Comment by ccordoba12** [comment]
Closing due to lack of response.
