### ISSUE TITLE
Add an option to use the same interpreter Spyder is running on as "Python executable" for external consoles

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1515]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-08-13T08:42:04Z_

Spyder Version:  2.2.2 (2977: r4aca4472a8d0 )
Python Version:  2.7.5
Qt Version:      4.8.4, PyQt4 (API v2) 4.9.6 on Windows

Creating a new IPython console fails and returns the following traceback in Console plugin:

NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049 To connect another client to this kernel, use:
    --existing kernel-5816.json
[IPKernelApp] ERROR | Invalid Message
Traceback (most recent call last):
  File "D:\winpython\install\WinPython-64bit-2.7.4.0\python-2.7.4.amd64\lib\site-packages\IPython\kernel\zmq\ipkernel.py", line 207, in dispatch_shell
    msg = self.session.unserialize(msg, content=True, copy=False)
  File "D:\winpython\install\WinPython-64bit-2.7.4.0\python-2.7.4.amd64\lib\site-packages\IPython\kernel\zmq\session.py", line 788, in unserialize
    msg_list[i] = msg_list[i].bytes
IndexError: list index out of range
[IPKernelApp] ERROR | Invalid Message
Traceback (most recent call last):
  File "D:\winpython\install\WinPython-64bit-2.7.4.0\python-2.7.4.amd64\lib\site-packages\IPython\kernel\zmq\ipkernel.py", line 207, in dispatch_shell
    msg = self.session.unserialize(msg, content=True, copy=False)
  File "D:\winpython\install\WinPython-64bit-2.7.4.0\python-2.7.4.amd64\lib\site-packages\IPython\kernel\zmq\session.py", line 788, in unserialize
    msg_list[i] = msg_list[i].bytes
IndexError: list index out of range
[IPKernelApp] ERROR | Invalid Message
Traceback (most recent call last):
  File "D:\winpython\install\WinPython-64bit-2.7.4.0\python-2.7.4.amd64\lib\site-packages\IPython\kernel\zmq\ipkernel.py", line 207, in dispatch_shell
    msg = self.session.unserialize(msg, content=True, copy=False)
  File "D:\winpython\install\WinPython-64bit-2.7.4.0\python-2.7.4.amd64\lib\site-packages\IPython\kernel\zmq\session.py", line 788, in unserialize
    msg_list[i] = msg_list[i].bytes
IndexError: list index out of range

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1515_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-13T06:47:39Z_

That's because you are using IPython 1.0 (the message about using Ctrl+\ to kill the kernel reveals it) and we support only 0.13.x.

But don't despair, I have almost ready a commit to make 2.2 work with 0.13 and 1.0.

**Summary:** IPython 1.0 is broken in Spyder v2.2.2  \<span class="oldvalue"> (was: IPython may be broken in Spyder v2.2.2) \</span>

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-08-13T11:59:53Z_

No, actually I'm using IPython v0.13.2, that's why I was worried by this bug:

Python 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 0.13.2 -- An enhanced Interactive Python.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-08-13T12:13:18Z_

Wait... false alarm!

This was a terrible mess in settings in my WinPython installations... I copied Spyder settings from a WinPython folder to another and so the Python executable option (Console>Advanced) was still pointing the Python interpreter of the old WinPython install. Maybe we should warn the user when the Python interpreter executing Spyder has changed and is different from the one specified to run programs inside Spyder. For me it's not really a problem, I realized in about 2 minutes where the problem was. But for other people, this can be more tedious. A colleague once told me about a similar problem: he changed from a Python distribution to another (so same Spyder settings, but different interpreter for Spyder execution), and he had problems with Spyder... after a long while, someone else made him realized that the Python interpreter used by Spyder to run programs was not the right one.

**Status:** Invalid

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-08-14T06:58:07Z_

Implemented in revision 47bc3bf36d4e the necessary change I was referring to in my previous comment.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-20T07:19:33Z_

**Summary:** Add an option to use the same interpreter Spyder is running on as "Python executable" for external consoles  \<span class="oldvalue"> (was: IPython 1.0 is broken in Spyder v2.2.2) \</span>  
  **Status:** Fixed
