### ISSUE TITLE
Spyder fails to launch if completions are disabled

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#15177]
When disabling "Enable code completion and linting in the editor", Spyder will not launch.

### Steps to Reproduce
1. launch Spyder
2. Uncheck "Enable code completions and linting in the editor" in Spyder Preferences
3. Close Spyder
4. Relaunch Spyder

```
(spy-dev) >> python bootstrap.py 
Executing Spyder from source checkout
*. Patched sys.path with /Users/rclary/Documents/Python/spyder
*. Patched sys.path with /Users/rclary/Documents/Python/spyder/external-deps/spyder-kernels
*. Patched sys.path with /Users/rclary/Documents/Python/spyder/external-deps/qdarkstyle
*. Patched sys.path with /Users/rclary/Documents/Python/spyder/external-deps/python-language-server
*. Installing PyLS locally
*. Declaring completion providers
*. PyQt5 is detected, selecting
*. Imported Spyder 5.1.0.dev0 - Revision 6648e8632, Branch: 5.x
    [Python 3.9.1 64bits, Qt 5.9.7, PyQt5 5.9.2 on Darwin]
*. Running Spyder
Bootstrap completed in 00:00:01.7434
No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect. 
Pruned plugin: outline_explorer
Traceback (most recent call last):
  File "/Users/rclary/Documents/Python/spyder/spyder/app/mainwindow.py", line 2139, in create_window
    main.setup()
  File "/Users/rclary/Documents/Python/spyder/spyder/app/mainwindow.py", line 836, in setup
    plugin_deps = solve_plugin_dependencies(enabled_plugins.values())
  File "/Users/rclary/Documents/Python/spyder/spyder/app/solver.py", line 210, in solve_plugin_dependencies
    plugin_deps = [plugin_names[name] for name in deps]
  File "/Users/rclary/Documents/Python/spyder/spyder/app/solver.py", line 210, in <listcomp>
    plugin_deps = [plugin_names[name] for name in deps]
KeyError: 'outline_explorer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rclary/Documents/Python/spyder/bootstrap.py", line 278, in <module>
    start.main()
  File "/Users/rclary/Documents/Python/spyder/spyder/app/start.py", line 213, in main
    mainwindow.main(options, args)
  File "/Users/rclary/Documents/Python/spyder/spyder/app/mainwindow.py", line 2286, in main
    mainwindow = create_window(app, splash, options, args)
  File "/Users/rclary/Documents/Python/spyder/spyder/app/mainwindow.py", line 2141, in create_window
    if main.console is not None:
  File "/Users/rclary/Documents/Python/spyder/spyder/app/mainwindow.py", line 1159, in __getattr__
    return self.get_plugin(self._INTERNAL_PLUGINS_MAPPING[attr])
  File "/Users/rclary/Documents/Python/spyder/spyder/app/mainwindow.py", line 168, in get_plugin
    raise SpyderAPIError('Plugin "{}" not found!'.format(plugin_name))
spyder.api.exceptions.SpyderAPIError: Plugin "internal_console" not found!
```

**Comment by ccordoba12** [comment]
@mrclary, please note that after fixing this it won't be possible to restore completions unless you reset our settings. We plan to fix that in a 5.1.0, to be released (probably) at the end of May.
