### ISSUE TITLE
Spyder 5 requires QtAwesome >1.0.0

### ISSUE THREAD

**Issue by algent-al** [spyder-ide/spyder#15176]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
spyder 5.0.0 doesn't launch with python-qtawesome version 0.7.3. Installing versions higher than 1.0.0 fixes the issue.

This is the output:

```
No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect. 
Traceback (most recent call last):
  File "/usr/bin/spyder", line 11, in <module>
    load_entry_point('spyder==5.0.0', 'gui_scripts', 'spyder')()
  File "/usr/lib/python3.7/site-packages/spyder/app/start.py", line 213, in main
    mainwindow.main(options, args)
  File "/usr/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 2293, in main
    mainwindow = create_window(app, splash, options, args)
  File "/usr/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 2146, in create_window
    main.setup()
  File "/usr/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 882, in setup
    plugin_instance = plugin_class(self, configuration=CONF)
  File "/usr/lib/python3.7/site-packages/spyder/api/plugins.py", line 1425, in __init__
    widget.set_icon(self.get_icon())
  File "/usr/lib/python3.7/site-packages/spyder/plugins/profiler/plugin.py", line 70, in get_icon
    return self.create_icon('profiler')
  File "/usr/lib/python3.7/site-packages/spyder/api/plugins.py", line 1136, in create_icon
    return ima.icon(name)
  File "/usr/lib/python3.7/site-packages/spyder/utils/icon_manager.py", line 380, in icon
    return qta.icon(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/qtawesome/__init__.py", line 146, in icon
    return _instance().icon(*names, **kwargs)
  File "/usr/lib/python3.7/site-packages/qtawesome/iconic_font.py", line 305, in icon
    names[i]))
  File "/usr/lib/python3.7/site-packages/qtawesome/iconic_font.py", line 353, in _parse_options
    prefix, chars = self._get_prefix_chars(names)
  File "/usr/lib/python3.7/site-packages/qtawesome/iconic_font.py", line 384, in _get_prefix_chars
    raise Exception(error)
Exception: Invalid icon name "timer-outline" in font "mdi"
```
### What steps reproduce the problem?

1. Run `spyder`
2. 
3. 

```

## Versions
* Spyder version: 5.0.0
* Python version: 3.7.10
* Qt version: 5.15.2
* PyQt version: 5.15.2
* Operating System name/version: Solus 4.2

### Dependencies
```
PASTE DEPENDENCIES HERE
```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.19.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.2.0 (OK)
nbconvert >=4.0               :  5.6.1 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.0 (OK)
pylint >=1.0                  :  2.6.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
setuptools >=39.0.0           :  47.1.0 (OK)
sphinx >=0.6.6                :  3.5.1 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  0.10.3 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  19.0.2 (OK)

# Optional:
cython >=0.21                 :  0.29.21 (OK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.16.6 (OK)
pandas >=1.1.1                :  1.2.2 (OK)
scipy >=0.17.0                :  1.6.0 (OK)
sympy >=0.7.3                 :  1.7.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @algent-al, thanks for reporting. You're totally right!

We'll fix that in our next version (5.0.1), to be released shortly.
