### ISSUE TITLE
macOS Application fails to launch if .spyder_py3_dev does not exist

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#15180]
It seems there is an issue with `jupyter-client=6.1.13`.
1. Delete `.spyder_py3_dev`
2. Start macOS Spyder application (built with `jupyter-client=6.1.13`)
3. Spyder fails to start

```python
Traceback (most recent call last):
  File "/Users/rclary/Applications/spyder-dev/Spyder.app/Contents/Resources/__boot__.py", line 106, in <module>
    _run()
  File "/Users/rclary/Applications/spyder-dev/Spyder.app/Contents/Resources/__boot__.py", line 84, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Users/rclary/Applications/spyder-dev/Spyder.app/Contents/Resources/Spyder.py", line 3, in <module>
    start.main()
  File "/Users/rclary/Applications/spyder-dev/Spyder.app/Contents/Resources/lib/python3.9/spyder/app/start.py", line 227, in main
    mainwindow.main(options, args)
  File "/Users/rclary/Applications/spyder-dev/Spyder.app/Contents/Resources/lib/python3.9/spyder/app/mainwindow.py", line 2301, in main
    mainwindow = create_window(app, splash, options, args)
  File "/Users/rclary/Applications/spyder-dev/Spyder.app/Contents/Resources/lib/python3.9/spyder/app/mainwindow.py", line 2163, in create_window
    main.pre_visible_setup()
  File "/Users/rclary/Applications/spyder-dev/Spyder.app/Contents/Resources/lib/python3.9/spyder/app/mainwindow.py", line 1201, in pre_visible_setup
    plugin_instance.before_mainwindow_visible()
  File "/Users/rclary/Applications/spyder-dev/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/layout/plugin.py", line 133, in before_mainwindow_visible
    self.setup_layout(default=False)
  File "/Users/rclary/Applications/spyder-dev/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/layout/plugin.py", line 207, in setup_layout
    self.setup_default_layouts('default', settings)
  File "/Users/rclary/Applications/spyder-dev/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/layout/plugin.py", line 273, in setup_default_layouts
    layout.set_main_window_layout(self.main, self.get_dockable_plugins())
  File "/Users/rclary/Applications/spyder-dev/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/layout/api.py", line 381, in set_main_window_layout
    plugin.toggle_view(area["visible"])
  File "/Users/rclary/Applications/spyder-dev/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/ipythonconsole/plugin.py", line 508, in toggle_view
    self.create_new_client(give_focus=False)
  File "/Users/rclary/Applications/spyder-dev/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/ipythonconsole/plugin.py", line 1007, in create_new_client
    self.connect_client_to_kernel(client, is_cython=is_cython,
  File "/Users/rclary/Applications/spyder-dev/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/ipythonconsole/plugin.py", line 1041, in connect_client_to_kernel
    km, kc = self.create_kernel_manager_and_kernel_client(
  File "/Users/rclary/Applications/spyder-dev/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/ipythonconsole/plugin.py", line 1506, in create_kernel_manager_and_kernel_client
    kernel_client.hb_channel.time_to_dead = 25.0
  File "jupyter_client/client.pyc", line 364, in hb_channel
  File "qtconsole/util.pyc", line 64, in __new__
TypeError: __init__() missing 1 required positional argument: 'context'
```

@dalthviz @ccordoba12, it seems the relevant change betweem #15149 and #15172 is `jupyter-client=6.1.13` in the macOS app and @dalthviz discovered an issue with this version in 0984d4faae5507005934531765239d37a1f240bf. I propose changing the requirements for Spyder, even if provisionally, rather than patching `install.sh`.

**Comment by mrclary** [comment]
Looks like the requirement should be updated in `spyder-kernels`: `'jupyter-client>=5.3.4'` -> `'jupyter-client>=5.3.4,<6.1.13'`

**Comment by mrclary** [comment]
Also, as of this report, `jupyter-client=6.1.13` is only available via pip, not conda main or conda-forge.

**Comment by ccordoba12** [comment]
I already talked to the Jupyter team and they're preparing a new release to fix that. Also, they plan to yank 6.1.13 in PyPI, so new PRs will use 6.1.12.

Let's wait until tomorrow to see what happens about that.

**Comment by ccordoba12** [comment]
The Jupyter team yanked both jupyter_client 6.1.13 and 6.2.0, so this shouldn't be a problem anymore.
