### ISSUE TITLE
Linting crashes

### ISSUE THREAD

**Issue by DrAndrewHayes-NRLSSC** [spyder-ide/spyder#15208]
### What steps will reproduce the problem?

I upgraded to 5.0.0 and it says I'm missing spyder_kernels 2.0.1, which I have, and then says that linting won't work.

### Traceback
```python-traceback
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\ahayes\Anaconda3\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\ahayes\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\ahayes\Anaconda3\lib\site-packages\spyder\app\start.py", line 214, in main
    mainwindow.main(options, args)
  File "C:\Users\ahayes\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2293, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\ahayes\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2192, in create_window
    app.exec_()
  File "C:\Users\ahayes\Anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 518, in _handle_kernel_died
    self.log.warning("kernel died: %s", since_last_heartbeat)
Message: 'kernel died: %s'
Arguments: (25.01563048362732,)
Traceback (most recent call last):
  File "C:\Users\ahayes\Anaconda3\lib\site-packages\spyder\plugins\completion\container.py", line 37, in show_widget
    widget.exec_()
  File "C:\Users\ahayes\Anaconda3\lib\site-packages\spyder\plugins\completion\providers\languageserver\widgets\messagebox.py", line 38, in exec_
    self.set_conf('show_lsp_down_warning', not self.is_checked())
  File "C:\Users\ahayes\Anaconda3\lib\site-packages\spyder\plugins\completion\api.py", line 1226, in set_conf
    self.main.set_conf(option_name, value, section=section,
  File "C:\Users\ahayes\Anaconda3\lib\site-packages\spyder\api\plugins.py", line 1033, in set_conf
    self._conf.set(section, option, value,
  File "C:\Users\ahayes\Anaconda3\lib\site-packages\spyder\config\manager.py", line 482, in set
    self.notify_observers(
  File "C:\Users\ahayes\Anaconda3\lib\site-packages\spyder\config\manager.py", line 330, in notify_observers
    self._notify_option(section, tuple_option, value)
  File "C:\Users\ahayes\Anaconda3\lib\site-packages\spyder\config\manager.py", line 348, in _notify_option
    observer.on_configuration_change(option, section, value)
  File "C:\Users\ahayes\Anaconda3\lib\site-packages\spyder\api\config\mixins.py", line 227, in on_configuration_change
    method(value)
  File "C:\Users\ahayes\Anaconda3\lib\site-packages\spyder\plugins\completion\providers\languageserver\provider.py", line 555, in update_configuration
    self.update_lsp_configuration()
  File "C:\Users\ahayes\Anaconda3\lib\site-packages\spyder\plugins\completion\providers\languageserver\provider.py", line 628, in update_lsp_configuration
    client.send_configurations(
  File "C:\Users\ahayes\Anaconda3\lib\site-packages\spyder\plugins\completion\providers\languageserver\decorators.py", line 43, in wrapper
    _id = self.send(method, params, kind)
  File "C:\Users\ahayes\Anaconda3\lib\site-packages\spyder\plugins\completion\providers\languageserver\client.py", line 470, in send
    self.zmq_out_socket.send_pyobj(msg, flags=zmq.NOBLOCK)
  File "C:\Users\ahayes\Anaconda3\lib\site-packages\zmq\sugar\socket.py", line 719, in send_pyobj
    return self.send(msg, flags=flags, **kwargs)
  File "C:\Users\ahayes\Anaconda3\lib\site-packages\zmq\sugar\socket.py", line 505, in send
    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 718, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 759, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Unknown error
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.8.8
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  49.6.0.post20210108 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.22 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.18.5 (OK)
pandas >=1.1.1                :  1.2.3 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.7.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @DrAndrewHayes-NRLSSC, thanks for reporting. This problem was fixed in pull request #15135, which will be part of our next version (5.0.1), to be released shortly.
