### ISSUE TITLE
ZeroDivisionError when generating thumbnail in Plots

### ISSUE THREAD

**Issue by SV-Dip** [spyder-ide/spyder#15223]
### What steps will reproduce the problem?

Using decision tree visualisation causes issues 'Plots' pane. Although I can access the plot images before and after fitting regression model. Training the regression model seems to creates a plot.

! I've updated the issue with new info.

### Traceback
```python-traceback

QPainter::save: Painter not active
QPainter::setPen: Painter not active
QFont::setPixelSize: Pixel size <= 0 (0)
QPainter::setFont: Painter not active
QPainter::setOpacity: Painter not active
QPainter::restore: Unbalanced save/restore
Traceback (most recent call last):
  File "/Users/NabanitaHalder/anaconda3/lib/python3.7/site-packages/spyder/plugins/plots/widgets/main_widget.py", line 577, in next_plot
    widget.thumbnails_sb.go_next_thumbnail()
  File "/Users/NabanitaHalder/anaconda3/lib/python3.7/site-packages/spyder/plugins/plots/widgets/figurebrowser.py", line 865, in go_next_thumbnail
    self.set_current_index(index)
  File "/Users/NabanitaHalder/anaconda3/lib/python3.7/site-packages/spyder/plugins/plots/widgets/figurebrowser.py", line 835, in set_current_index
    self.set_current_thumbnail(self._thumbnails[index])
  File "/Users/NabanitaHalder/anaconda3/lib/python3.7/site-packages/spyder/plugins/plots/widgets/figurebrowser.py", line 848, in set_current_thumbnail
    thumbnail.canvas.fig, thumbnail.canvas.fmt)
  File "/Users/NabanitaHalder/anaconda3/lib/python3.7/site-packages/spyder/plugins/plots/widgets/figurebrowser.py", line 380, in load_figure
    self.scale_image()
  File "/Users/NabanitaHalder/anaconda3/lib/python3.7/site-packages/spyder/plugins/plots/widgets/figurebrowser.py", line 487, in scale_image
    self.sig_zoom_changed.emit(self.get_scaling())
  File "/Users/NabanitaHalder/anaconda3/lib/python3.7/site-packages/spyder/plugins/plots/widgets/figurebrowser.py", line 491, in get_scaling
    return round(self.figcanvas.width() / self.figcanvas.fwidth * 100)
ZeroDivisionError: division by zero
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.6.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.3.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.4 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.22 (OK)
matplotlib >=2.0.0            :  3.1.0 (OK)
numpy >=1.7                   :  1.19.2 (OK)
pandas >=1.1.1                :  1.2.3 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.7.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @SV-Dip, thanks for reporting. Could you post a very simple and reproducible code example that generates this problem?

**Comment by SV-Dip** [comment]
Here is the code:
[https://github.com/SV-Dip/Heart-Disease-Model---UCI/blob/main/Heart%20Disease%20Model.py](url)

As shown in the picture below, the error occurs at the gap in between the plots shown in red arrow, when using previous/next button to scroll through the plots. The error can be ignored and but it repeats every time.
![Screenshot 2021-04-12 at 12 37 10 AM](https://user-images.githubusercontent.com/30889333/114318271-033a0d80-9b2a-11eb-9ae5-4d26eddafeeb.png)

Also: I'm new at data science, if it's a bug in my code, I'm profusely sorry for wasting time.

**Comment by ccordoba12** [comment]
Thanks @SV-Dip, we'll try to fix this in our next version.
