### ISSUE TITLE
networkx generates Issue reporter

### ISSUE THREAD

**Issue by drscottb** [spyder-ide/spyder#15236]
### What steps will reproduce the problem?

using networkx generates this reporter but evrything appears to run fine!

### Traceback
```python-traceback
  File "C:\Users\slber\Anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 421, in _handle_new_figure
    self.thumbnails_sb.add_thumbnail(fig, fmt)
  File "C:\Users\slber\Anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 866, in add_thumbnail
    self.set_current_thumbnail(thumbnail)
  File "C:\Users\slber\Anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 942, in set_current_thumbnail
    thumbnail.highlight_canvas(thumbnail == self.current_thumbnail)
  File "C:\Users\slber\Anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 1035, in highlight_canvas
    qdarkstyle.palette.DarkPalette.COLOR_SELECTION_LIGHT
AttributeError: module 'qdarkstyle.palette' has no attribute 'DarkPalette'
Traceback (most recent call last):
  File "C:\Users\slber\Anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 421, in _handle_new_figure
    self.thumbnails_sb.add_thumbnail(fig, fmt)
  File "C:\Users\slber\Anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 866, in add_thumbnail
    self.set_current_thumbnail(thumbnail)
  File "C:\Users\slber\Anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 942, in set_current_thumbnail
    thumbnail.highlight_canvas(thumbnail == self.current_thumbnail)
  File "C:\Users\slber\Anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 1035, in highlight_canvas
    qdarkstyle.palette.DarkPalette.COLOR_SELECTION_LIGHT
AttributeError: module 'qdarkstyle.palette' has no attribute 'DarkPalette'
Traceback (most recent call last):
  File "C:\Users\slber\Anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 421, in _handle_new_figure
    self.thumbnails_sb.add_thumbnail(fig, fmt)
  File "C:\Users\slber\Anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 866, in add_thumbnail
    self.set_current_thumbnail(thumbnail)
  File "C:\Users\slber\Anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 942, in set_current_thumbnail
    thumbnail.highlight_canvas(thumbnail == self.current_thumbnail)
  File "C:\Users\slber\Anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 1035, in highlight_canvas
    qdarkstyle.palette.DarkPalette.COLOR_SELECTION_LIGHT
AttributeError: module 'qdarkstyle.palette' has no attribute 'DarkPalette'
Traceback (most recent call last):
  File "C:\Users\slber\Anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 421, in _handle_new_figure
    self.thumbnails_sb.add_thumbnail(fig, fmt)
  File "C:\Users\slber\Anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 866, in add_thumbnail
    self.set_current_thumbnail(thumbnail)
  File "C:\Users\slber\Anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 942, in set_current_thumbnail
    thumbnail.highlight_canvas(thumbnail == self.current_thumbnail)
  File "C:\Users\slber\Anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 1035, in highlight_canvas
    qdarkstyle.palette.DarkPalette.COLOR_SELECTION_LIGHT
AttributeError: module 'qdarkstyle.palette' has no attribute 'DarkPalette'
```

## Versions

* Spyder version: 4.2.1 
* Python version: 3.7.10
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.22.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.2 (OK)
qdarkstyle >=2.8                :  3.0.2 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  3.5.3 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  1.0.2 (OK)
zmq >=17                        :  18.1.1 (OK)

# Optional:
cython >=0.21                   :  0.29.22 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.2.3 (OK)
scipy >=0.17.0                  :  1.6.0 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @drscottb, thanks for reporting. To fix this, please close Spyder, open the Anaconda prompt and run there

    conda install qdarkstyle=2.8.1

That should do the trick.

**Comment by drscottb** [comment]
Hi Carlos,

It worked perfectly. Thank you!


Scott L. Bernstein, M.D.
