### ISSUE TITLE
Error when change default interpreter in linux

### ISSUE THREAD

**Issue by do1234521** [spyder-ide/spyder#15242]
### What steps will reproduce the problem?

The system is using the default spyder 4.2.5 installed from system repository in OpenSUSE Tumbleweed.
When I changed the default interpreter to my conda virtual environment which is Python 3.9.1 with spyder-kernel 1.10.1. The console returned error "Error when starting IPython kernel"
And here is the traceback log:

```
错误：

Traceback (most recent call last):
File "/usr/lib/python3.8/site‑packages/spyder/plugins/ipythonconsole/plugin.py", line 1422, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle,
File "/usr/lib/python3.8/site‑packages/jupyter_client/manager.py", line 313, in start_kernel
self.kernel = self._launch_kernel(kernel_cmd, **kw)
File "/usr/lib/python3.8/site‑packages/jupyter_client/manager.py", line 220, in _launch_kernel
return launch_kernel(kernel_cmd, **kw)
File "/usr/lib/python3.8/site‑packages/jupyter_client/launcher.py", line 131, in launch_kernel
proc = Popen(cmd, **kwargs)
File "/usr/lib64/python3.8/subprocess.py", line 858, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/lib64/python3.8/subprocess.py", line 1706, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] 权限不够: '/usr/lib/python3.8/site‑packages/spyder/plugins/ipythonconsole/scripts/conda‑activate.sh'
```

I checked the folder and found the files was all right there but the hyphen in the 'site‑packages' was wrong. 
```
/usr/lib/python3.8/site‑packages
```

I checked the unicode and found they used '\u2011' which is wrong and the right one in system should be '\u002d' but they really look the same.
```
\u2011  wrong
\u002d  right
```

I'm not sure if it is a bug in Sypder or in OpenSUSE. So I submit this bug to the Sypder community.

## Versions

* Spyder version: 4.2.5 
* Python version: 3.8.8
* Qt version: 5.15.2
* PyQt5 version: 5.15.4
* Operating System: Linux 5.11.11-1-default

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=7.6.0                 :  7.21.0 (OK)
jedi >=0.17.2                   :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  21.2.1 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso >=0.7.0                   :  0.7.1 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.7.4 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
setuptools >=39.0.0             :  44.1.1 (OK)
sphinx >=0.6.6                  :  3.5.3 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
xdg >=0.26                      :  0.27 (OK)
zmq >=17                        :  22.0.3 (OK)

# Optional:
cython >=0.21                   :  0.29.22 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.20.1 (OK)
pandas >=1.1.1                  :  1.2.3 (OK)
scipy >=0.17.0                  :  1.6.2 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @do1234521, thanks for reporting. You said

> I checked the folder and found the files was all right there but the hyphen in the 'site‑packages' was wrong.

That's not something we have control over, sorry. That directory is created by the OpenSUSE team, so you need to inform about this problem to them.

**Comment by ccordoba12** [comment]
> I'm not sure if it is a bug in Sypder or in OpenSUSE. So I submit this bug to the Sypder community.

Thanks for reaching out, though. I think it was the right call.
