### ISSUE TITLE
spyder can't debug, when debuggging, the internal ipython get crashed

### ISSUE THREAD

**Issue by asmwarrior** [spyder-ide/spyder#15243]
First, this happens on Windows 7 64bit, and I use WinPython 3.8.8.0, and Spyder 4.2.5 and Spyder 5.0.0 both has this problem.

When debugging the `robotics-toolbox-python` (petercorke/robotics-toolbox-python: Robotics Toolbox for Python — https://github.com/petercorke/robotics-toolbox-python), I see the follow crash:

~~~~
Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.21.0 -- An enhanced Interactive Python.

debugfile('E:/code/robotics/robotics-toolbox-python/roboticstoolbox/examples/RRMC_swift.py', wdir='E:/code/robotics/robotics-toolbox-python/roboticstoolbox/examples')
> e:\code\robotics\robotics-toolbox-python\roboticstoolbox\examples\rrmc_swift.py(2)<module>()
      1 #!/usr/bin/env python
----> 2 """
      3 @author Jesse Haviland
      4 """
      5 


IPdb [1]: !continue
> e:\code\robotics\robotics-toolbox-python\roboticstoolbox\examples\rrmc_swift.py(11)<module>()
      9 import numpy as np
     10 
11-> 11 env = swift.Swift()
     12 env.launch()
     13 


!continue

!continue
error: 'Table' object has no attribute 'get' 
when evaluating expression 'not connected_to'
when instantiating macro: panda_arm (E:\download\sci\Winpython64-3.8.8.0\WPy64-3880\python-3.8.8.amd64\Lib\site-packages\rtbdata\xacro\franka_description\robots\../robots/panda_arm.xacro)
in file: E:\download\sci\Winpython64-3.8.8.0\WPy64-3880\python-3.8.8.amd64\Lib\site-packages\rtbdata\xacro\franka_description\robots\panda_arm_hand.urdf.xacro
An exception has occurred, use %tb to see the full traceback.

Traceback (most recent call last):

  File "e:\code\robotics\robotics-toolbox-python\roboticstoolbox\tools\xacro\__init__.py", line 617, in handle_expr
    return eval(eval_text(s, symbols), global_symbols, symbols)

  File "<string>", line 1, in <module>

  File "E:\download\sci\Winpython64-3.8.8.0\WPy64-3880\python-3.8.8.amd64\lib\bdb.py", line 90, in trace_dispatch
    return self.dispatch_call(frame, arg)

  File "E:\download\sci\Winpython64-3.8.8.0\WPy64-3880\python-3.8.8.amd64\lib\bdb.py", line 128, in dispatch_call
    if not (self.stop_here(frame) or self.break_anywhere(frame)):

  File "E:\download\sci\Winpython64-3.8.8.0\WPy64-3880\python-3.8.8.amd64\lib\site-packages\spyder_kernels\customize\spyderpdb.py", line 254, in stop_here
    and frame.f_locals.get(

AttributeError: 'Table' object has no attribute 'get'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "e:\code\robotics\robotics-toolbox-python\roboticstoolbox\tools\xacro\__init__.py", line 1072, in main
    doc = process_file(filename, **opts)

  File "e:\code\robotics\robotics-toolbox-python\roboticstoolbox\tools\xacro\__init__.py", line 1036, in process_file
    process_doc(doc, **kwargs)

  File "e:\code\robotics\robotics-toolbox-python\roboticstoolbox\tools\xacro\__init__.py", line 986, in process_doc
    eval_all(doc.documentElement, macros, symbols)

  File "e:\code\robotics\robotics-toolbox-python\roboticstoolbox\tools\xacro\__init__.py", line 921, in eval_all
    elif handle_macro_call(node, macros, symbols):

  File "e:\code\robotics\robotics-toolbox-python\roboticstoolbox\tools\xacro\__init__.py", line 757, in handle_macro_call
    eval_all(body, macros, scoped)

  File "e:\code\robotics\robotics-toolbox-python\roboticstoolbox\tools\xacro\__init__.py", line 911, in eval_all
    keep = get_boolean_value(eval_text(cond, symbols), cond)

  File "e:\code\robotics\robotics-toolbox-python\roboticstoolbox\tools\xacro\__init__.py", line 633, in eval_text
    results.append(handle_expr(lex.next()[1][2:-1]))

  File "e:\code\robotics\robotics-toolbox-python\roboticstoolbox\tools\xacro\__init__.py", line 620, in handle_expr
    raise XacroException(exc=e,

XacroException: 'Table' object has no attribute 'get' 
when evaluating expression 'not connected_to'


During handling of the above exception, another exception occurred:

SystemExit: 2


~~~~

The source code I'm debugging is below:

~~~~
#!/usr/bin/env python
"""
@author Jesse Haviland
"""

import swift
import roboticstoolbox as rp
import spatialmath as sm
import numpy as np

env = swift.Swift()
env.launch()

panda = rp.models.Panda()
panda.q = panda.qr

print("current end effector position")
Tcur = panda.fkine(panda.q)
print(Tcur)

Tep = panda.fkine(panda.q) * sm.SE3.Tx(0.2) * sm.SE3.Ty(0.2) * sm.SE3.Tz(0.45)

print("desired end effector position")
print(Tep)

arrived = False
env.add(panda)

dt = 0.05

while not arrived:

    v, arrived = rp.p_servo(panda.fkine(panda.q), Tep, 1)
    panda.qd = np.linalg.pinv(panda.jacobe(panda.q)) @ v
    env.step(dt)

# Uncomment to stop the browser tab from closing
# env.hold()
~~~~

Note that the code `env = swift.Swift()` create a web socket server and open a 3D view in the browser.

I have set some breakpoints in the source file, and click the "continue" several times, but it looks like the debugger just quit as some exception happens.

I can debug the program under the python's native `IDLE`, and either `step` or `step over` or `continue` works OK without any issue.

I first see this issue when I use the build-in Spyder 4.2.3 in WinPython 3.8.8 package, today, I try to upgrade Spyder to 5.0.0, and this issue still happens.

Any ideas how to fix this issue?

**Comment by ccordoba12** [comment]
Hey @asmwarrior, thanks for reporting. Although your problem seems legit, it's a very narrow use case. I mean, it seems specifically related to the `roboticstoolbox` package, at least according to the error you posted above.

I don't know if @impact27 would like to give it a try, but the rest of the team is really busy at the moment to take a look at this, sorry.

**Comment by asmwarrior** [comment]
The advantage of debugging in `Spyder` is that when the debugee get halted, I can still run some code or inspect some variables in the interactive console. While in `IDLE` or `Thonny`, when debugging, I don't have that ability to inspect other variables.

**Comment by ccordoba12** [comment]
Sure, @impact27 worked really hard to make that a reality. However, we don't have the resources to support every use case under the sun, sorry.

**Comment by asmwarrior** [comment]
This is the error message log I see from the PyScripter IDE, see below:

I hope you may find some useful information:

~~~~
>>> 
*** Remote Interpreter Reinitialized ***
Exception in thread Thread-2:
Traceback (most recent call last):
  File "E:\download\sci\Winpython64-3.8.8.0\WPy64-3880\python-3.8.8.amd64\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\download\sci\Winpython64-3.8.8.0\WPy64-3880\python-3.8.8.amd64\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\download\sci\Winpython64-3.8.8.0\WPy64-3880\python-3.8.8.amd64\lib\site-packages\vpython\no_notebook.py", line 298, in start_websocket_server
    __interact_loop.run_forever()
  File "E:\download\sci\Winpython64-3.8.8.0\WPy64-3880\python-3.8.8.amd64\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "E:\download\sci\Winpython64-3.8.8.0\WPy64-3880\python-3.8.8.amd64\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "E:\download\sci\Winpython64-3.8.8.0\WPy64-3880\python-3.8.8.amd64\lib\asyncio\base_events.py", line 1827, in _run_once
    end_time = self.time() + self._clock_resolution
  File "E:\download\sci\Winpython64-3.8.8.0\WPy64-3880\python-3.8.8.amd64\lib\asyncio\base_events.py", line 662, in time
    def time(self):
  File "E:\download\sci\Winpython64-3.8.8.0\WPy64-3880\python-3.8.8.amd64\lib\bdb.py", line 90, in trace_dispatch
    return self.dispatch_call(frame, arg)
  File "<string>", line 147, in dispatch_call
  File "E:\download\sci\python\PyScripter-4.0.0-x64\PyScripter\Lib\rpyc.zip\rpyc\core\netref.py", line 152, in __getattribute__
  File "E:\download\sci\python\PyScripter-4.0.0-x64\PyScripter\Lib\rpyc.zip\rpyc\core\netref.py", line 76, in syncreq
  File "E:\download\sci\python\PyScripter-4.0.0-x64\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 471, in sync_request
  File "E:\download\sci\python\PyScripter-4.0.0-x64\PyScripter\Lib\rpyc.zip\rpyc\core\async_.py", line 95, in value
  File "E:\download\sci\python\PyScripter-4.0.0-x64\PyScripter\Lib\rpyc.zip\rpyc\core\async_.py", line 45, in wait
  File "E:\download\sci\python\PyScripter-4.0.0-x64\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 387, in serve
  File "E:\download\sci\python\PyScripter-4.0.0-x64\PyScripter\Lib\rpyc.zip\rpyc\core\channel.py", line 43, in poll
  File "E:\download\sci\python\PyScripter-4.0.0-x64\PyScripter\Lib\rpyc.zip\rpyc\core\stream.py", line 35, in poll
  File "E:\download\sci\python\PyScripter-4.0.0-x64\PyScripter\Lib\rpyc.zip\rpyc\core\stream.py", line 201, in fileno
  File "E:\download\sci\python\PyScripter-4.0.0-x64\PyScripter\Lib\rpyc.zip\rpyc\core\stream.py", line 88, in fileno
EOFError: stream has been closed
Exception ignored in thread started by: <bound method RemotePythonInterpreter.ThreadWrapper._bootstrap of <ThreadWrapper(Thread-2, started 8292)>>
Traceback (most recent call last):
  File "<string>", line 60, in _bootstrap
  File "<string>", line 44, in thread_status
  File "E:\download\sci\python\PyScripter-4.0.0-x64\PyScripter\Lib\rpyc.zip\rpyc\core\netref.py", line 152, in __getattribute__
  File "E:\download\sci\python\PyScripter-4.0.0-x64\PyScripter\Lib\rpyc.zip\rpyc\core\netref.py", line 76, in syncreq
  File "E:\download\sci\python\PyScripter-4.0.0-x64\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 471, in sync_request
  File "E:\download\sci\python\PyScripter-4.0.0-x64\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 492, in async_request
  File "E:\download\sci\python\PyScripter-4.0.0-x64\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 477, in _async_request
  File "E:\download\sci\python\PyScripter-4.0.0-x64\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 259, in _send
  File "E:\download\sci\python\PyScripter-4.0.0-x64\PyScripter\Lib\rpyc.zip\rpyc\core\channel.py", line 69, in send
  File "E:\download\sci\python\PyScripter-4.0.0-x64\PyScripter\Lib\rpyc.zip\rpyc\core\stream.py", line 233, in write
  File "E:\download\sci\python\PyScripter-4.0.0-x64\PyScripter\Lib\rpyc.zip\rpyc\core\stream.py", line 81, in __getattr__
EOFError: stream has been closed
Traceback (most recent call last):
  File "E:\code\robotics\robotics-toolbox-python\roboticstoolbox\examples\mytest.py", line 4, in <module>
    panda.plot(q=panda.qr)
  File "E:\code\robotics\robotics-toolbox-python\roboticstoolbox\robot\Robot.py", line 1311, in plot
    env.add(
TypeError: add() got an unexpected keyword argument 'jointaxes'
>>> 
~~~~

**Comment by asmwarrior** [comment]
This is an error inside the `Robot.py`, and I see Spyder does not catch that error, while PyScripter did catches the error.
