### ISSUE TITLE
Kite's tutorial

### ISSUE THREAD

**Issue by Baalkikhaal** [spyder-ide/spyder#15245]
### What steps will reproduce the problem?

Changed the value of `Show automatic completions after characters entered` to 1 and `Show automatic completions after keyboard idle (ms)` to 100.

While trying first task of the Kite  tutorial for autocompletion, I typed `a` and immediately Issue reporter dialog pops up.

P.S. : The Spyder Status bar shows `Kite: ready`.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "d:\databases\pythonprojects\numscimat\env\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 4490, in _handle_completions
    if (len(text) >= self.automatic_completions_after_chars
TypeError: '>=' not supported between instances of 'int' and 'tuple'
--- Logging error ---
Traceback (most recent call last):
  File "d:\databases\pythonprojects\numscimat\env\lib\site-packages\spyder\utils\external\github.py", line 246, in _http
    response = opener.open(request, timeout=TIMEOUT)
  File "C:\Users\fubar\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\fubar\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\fubar\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\fubar\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\fubar\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\databases\pythonprojects\numscimat\env\lib\site-packages\spyder\widgets\github\backend.py", line 141, in send_report
    ret = repo.issues.post(title=title, body=body)
  File "d:\databases\pythonprojects\numscimat\env\lib\site-packages\spyder\utils\external\github.py", line 124, in __call__
    return self._gh._http(self._method, self._path, **kw)
  File "d:\databases\pythonprojects\numscimat\env\lib\site-packages\spyder\utils\external\github.py", line 260, in _http
    raise ApiError(url, req, resp)
spyder.utils.external.github.ApiError: https://api.github.com/repos/spyder-ide/spyder/issues

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fubar\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 1082, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\fubar\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\fubar\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Databases\PythonProjects\NumSciMat\env\Scripts\spyder.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "d:\databases\pythonprojects\numscimat\env\lib\site-packages\spyder\app\start.py", line 213, in main
    mainwindow.main(options, args)
  File "d:\databases\pythonprojects\numscimat\env\lib\site-packages\spyder\app\mainwindow.py", line 2293, in main
    mainwindow = create_window(app, splash, options, args)
  File "d:\databases\pythonprojects\numscimat\env\lib\site-packages\spyder\app\mainwindow.py", line 2192, in create_window
    app.exec_()
  File "d:\databases\pythonprojects\numscimat\env\lib\site-packages\spyder\widgets\reporterror.py", line 380, in _submit_to_github
    github_report = github_backend.send_report(title, issue_text)
  File "d:\databases\pythonprojects\numscimat\env\lib\site-packages\spyder\widgets\github\backend.py", line 143, in send_report
    _logger().warning('Failed to send bug report on Github. '
Message: 'Failed to send bug report on Github. response=%r'
Arguments: {'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest'}}
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.9.2
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.21.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
setuptools >=39.0.0           :  49.2.1 (OK)
sphinx >=0.6.6                :  3.5.2 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.20.1 (OK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  1.6.1 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by Baalkikhaal** [comment]
After going through the [Kite help](https://help.kite.com/article/53-quickstart), it is recommended to

>❗ Important: If your editor was running while you installed its respective plugin, you'll have to restart your editor for Kite to integrate properly. 

Doing this solved the issue.

**Comment by ccordoba12** [comment]
Great! I'm glad you were able to solve your problem by following Kite's help.

**Comment by Baalkikhaal** [comment]
Thank you 😁.
