### ISSUE TITLE
Spyder Launch ModuleNotFoundError: No module named 'PySide'

### ISSUE THREAD

**Issue by Crueda96** [spyder-ide/spyder#15276]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?
I install a new environment using Anaconda Navigator and the python package installed was 3.7.10
Launch Spyder from Anaconda Navigator or from anaconda prompt 

### What is the expected output? What do you see instead?
It is supposed to spyder start however an error is raised

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
File "C:\Users\Daniel Rueda\.conda\envs\HidroThermPS\lib\site-packages\qtpy\__init__.py", line 204, in 
from PySide import __version__ as PYSIDE_VERSION # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\Daniel Rueda\.conda\envs\HidroThermPS\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\Daniel Rueda\.conda\envs\HidroThermPS\lib\site-packages\spyder\app\start.py", line 186, in main
from spyder.app import mainwindow
File "C:\Users\Daniel Rueda\.conda\envs\HidroThermPS\lib\site-packages\spyder\app\mainwindow.py", line 48, in 
requirements.check_qt()
File "C:\Users\Daniel Rueda\.conda\envs\HidroThermPS\lib\site-packages\spyder\requirements.py", line 41, in check_qt
import qtpy
File "C:\Users\Daniel Rueda\.conda\envs\HidroThermPS\lib\site-packages\qtpy\__init__.py", line 210, in 
raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found


```

## Versions

* Spyder version: 3.3.5
* Python version: 3.7.10
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 x64

### Dependencies

I can not start Spyder so I don't have access to dependecies, I copy the conda list because I only install packages with Anaconda Chanels
```

# packages in environment at C:\Users\Daniel Rueda\.conda\envs\HidroThermPS:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
astroid                   2.5.3            py37h03978a9_0    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
babel                     2.9.0              pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bleach                    3.3.0              pyh44b312d_0    conda-forge
brotlipy                  0.7.0           py37hcc03f2d_1001    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
certifi                   2020.12.5        py37h03978a9_1    conda-forge
cffi                      1.14.5           py37hd8e9650_0    conda-forge
chardet                   4.0.0            py37h03978a9_1    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
console_shortcut          0.1.1                         4    anaconda
cryptography              3.4.7            py37h20c650d_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dill                      0.3.3              pyhd8ed1ab_0    conda-forge
docutils                  0.15.2           py37h03978a9_1    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
glpk                      4.65              h8ffe710_1004    conda-forge
icu                       58.2             vc14hc45fdbb_0  [vc14]  anaconda
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        3.10.1           py37h03978a9_0    conda-forge
importlib_metadata        3.10.1               hd8ed1ab_0    conda-forge
intel-openmp              2021.2.0           h57928b3_616    conda-forge
ipopt                     3.11.1                        2    conda-forge
ipykernel                 5.5.3            py37h7813e69_0    conda-forge
ipython                   7.22.0           py37h7813e69_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     5.8.0              pyhd8ed1ab_0    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.18.0           py37h03978a9_2    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
jpeg                      9b               vc14h4d7706e_1  [vc14]  anaconda
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py37h03978a9_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
keyring                   23.0.1           py37h03978a9_0    conda-forge
kiwisolver                1.3.1            py37h8c56517_1    conda-forge
lazy-object-proxy         1.6.0            py37hcc03f2d_0    conda-forge
libblas                   3.9.0                     8_mkl    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
llvmlite                  0.36.0           py37habb0c8c_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                1.1.1            py37hcc03f2d_3    conda-forge
matplotlib                3.2.2                         1    conda-forge
matplotlib-base           3.2.2            py37hab8957c_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py37hcc03f2d_1003    conda-forge
mkl                       2020.4             hb70f87d_311    conda-forge
mpmath                    1.2.1              pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
nbconvert                 6.0.7            py37h03978a9_3    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
networkx                  2.5.1              pyhd8ed1ab_0    conda-forge
nose                      1.3.7                   py_1006    conda-forge
numba                     0.53.1           py37h4e635f9_0    conda-forge
numpy                     1.20.2           py37hcbcd69c_0    conda-forge
numpydoc                  1.1.0                      py_1    conda-forge
openpyxl                  3.0.7              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1k               h8ffe710_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandapower                2.6.0              pyh44b312d_0    conda-forge
pandas                    1.2.4            py37h90003fb_0    conda-forge
pandoc                    2.13                 h8ffe710_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
plotly                    4.14.3                     py_0    plotly
ply                       3.11                       py_1    conda-forge
prompt-toolkit            3.0.18             pyha770c72_0    conda-forge
psutil                    5.8.0            py37hcc03f2d_1    conda-forge
pycodestyle               2.7.0              pyhd8ed1ab_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyflakes                  2.3.1              pyhd8ed1ab_0    conda-forge
pygments                  2.8.1              pyhd8ed1ab_0    conda-forge
pylint                    2.7.2            py37h03978a9_0    conda-forge
pymysql                   1.0.2              pyhd8ed1ab_0    conda-forge
pyodbc                    4.0.30           py37hf2a7229_1    conda-forge
pyomo                     5.7.3            py37hf2a7229_0    conda-forge
pyomo.extras              3.3                 py37_182212    conda-forge
pyomo.solvers             1.0                        1001    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.9.2            py37h6538335_4    conda-forge
pyro4                     4.80               pyh9f0ad1d_0    conda-forge
pyrsistent                0.17.3           py37hcc03f2d_2    conda-forge
pysocks                   1.7.1            py37h03978a9_3    conda-forge
python                    3.7.10          h7840368_100_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyutilib                  6.0.0              pyh9f0ad1d_0    conda-forge
pywin32                   300              py37hcc03f2d_0    conda-forge
pywin32-ctypes            0.2.0           py37h03978a9_1003    conda-forge
pyyaml                    5.1.2            py37hfa6e2cd_0    conda-forge
pyzmq                     22.0.3           py37hcce574b_1    conda-forge
qt                        5.9.7            vc14h73c81de_0  [vc14]  anaconda
qtawesome                 1.0.2              pyhd8ed1ab_0    conda-forge
qtconsole                 5.0.3              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
rope                      0.18.0             pyh9f0ad1d_0    conda-forge
scipy                     1.6.2            py37h924764e_0    conda-forge
serpent                   1.30.2                     py_0    conda-forge
setuptools                49.6.0           py37h03978a9_3    conda-forge
sip                       4.19.8          py37h6538335_1000    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snowballstemmer           2.1.0              pyhd8ed1ab_0    conda-forge
sphinx                    3.5.4              pyh44b312d_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
spyder                    3.3.5                    py37_0    conda-forge
spyder-kernels            0.5.2                    py37_0    conda-forge
sqlite                    3.35.4               h8ffe710_0    conda-forge
sympy                     1.8              py37h03978a9_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py37hcc03f2d_1    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
typed-ast                 1.4.3            py37hcc03f2d_0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_4    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_4    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
win_inet_pton             1.1.0            py37h03978a9_2    conda-forge
wincertstore              0.2             py37h03978a9_1006    conda-forge
wrapt                     1.12.1           py37hcc03f2d_3    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xlsxwriter                1.3.8              pyhd8ed1ab_0    conda-forge
yaml                      0.1.7            vc14h4cb57cf_1  [vc14]  anaconda
zeromq                    4.3.4                h0e60522_0    conda-forge
zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11           vc14h1cdd9ab_1  [vc14]  anaconda
```

**Comment by dalthviz** [comment]
Hi @Crueda96 thanks for the feedback, could you try to update Spyder to 3.3.6 and check again?. Also, maybe our troubleshooting guide could be useful for you: http://docs.spyder-ide.org/current/first-steps.html

Let us know if something of the above helps :)

**Comment by Crueda96** [comment]
I solve the inconvenient installing Pyqt5 via anaconda navigator. Thanks!
