### ISSUE TITLE
Spyder 5.0.0 won't launch

### ISSUE THREAD

**Issue by brucesamuels** [spyder-ide/spyder#15271]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder 5 won't launh

### What steps reproduce the problem?

1. start from Anaconda Navigator
2. spyder --reset
3. start from terminal

### What is the expected output? What do you see instead?
Spyder launches

Spyder seems to launch, see splash screen loading dependencies then nothing

### Paste Traceback/Error Below (if applicable)

```python-traceback
spyder splash screen appears seems to load depndencies then
PASTE TRACEBACK HERE
Traceback (most recent call last):
  File "/Users/brucesamuels/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/Users/brucesamuels/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 214, in main
    mainwindow.main(options, args)
  File "/Users/brucesamuels/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2293, in main
    mainwindow = create_window(app, splash, options, args)
  File "/Users/brucesamuels/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2146, in create_window
    main.setup()
  File "/Users/brucesamuels/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 882, in setup
    plugin_instance = plugin_class(self, configuration=CONF)
  File "/Users/brucesamuels/anaconda3/lib/python3.6/site-packages/spyder/api/plugins.py", line 1425, in __init__
    widget.set_icon(self.get_icon())
  File "/Users/brucesamuels/anaconda3/lib/python3.6/site-packages/spyder/plugins/profiler/plugin.py", line 70, in get_icon
    return self.create_icon('profiler')
  File "/Users/brucesamuels/anaconda3/lib/python3.6/site-packages/spyder/api/plugins.py", line 1136, in create_icon
    return ima.icon(name)
  File "/Users/brucesamuels/anaconda3/lib/python3.6/site-packages/spyder/utils/icon_manager.py", line 380, in icon
    return qta.icon(*args, **kwargs)
  File "/Users/brucesamuels/anaconda3/lib/python3.6/site-packages/qtawesome/__init__.py", line 145, in icon
    return _instance().icon(*names, **kwargs)
  File "/Users/brucesamuels/anaconda3/lib/python3.6/site-packages/qtawesome/iconic_font.py", line 294, in icon
    names[i]))
  File "/Users/brucesamuels/anaconda3/lib/python3.6/site-packages/qtawesome/iconic_font.py", line 342, in _parse_options
    prefix, chars = self._get_prefix_chars(names)
  File "/Users/brucesamuels/anaconda3/lib/python3.6/site-packages/qtawesome/iconic_font.py", line 373, in _get_prefix_chars
    raise Exception(error)
Exception: Invalid icon name "timer-outline" in font "mdi"
```

## Versions

* Spyder version: 5.0.0
* Python version: 3.6
* Qt version: 5.9.7
* PyQt version: 5.15.1
* Operating System name/version: Mac OS Big Sur 11.2.3

### Dependencies

```
PASTE DEPENDENCIES HERE
```can't open!

**Comment by steff456** [comment]
Hi @brucesamuels,

This is happening because you need to have qtawesome > 1.0.0 installed for Spyder 5. We already updated our requirement and that will be included in the release of Spyder 5.0.1 that will come soon!

For now, please update qtawesome dependency and Spyder 5 should run as expected.

Thanks for reporting!
