### ISSUE TITLE
Error while shutting down Spyder

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1528]
_From [tak...@gmail.com](https://code.google.com/u/116141806100272241943/) on 2013-08-21T19:15:06Z_

Running with Python 3.3 using bootstrap.py --debug, when I close Spyder using the regular window manager close button, an error like this is shown at the terminal:

Traceback (most recent call last):
  File "/home/takluyver/Code/spyderlib/spyderlib/spyder.py", line 1401, in closeEvent
    if self.closing(True):
  File "/home/takluyver/Code/spyderlib/spyderlib/spyder.py", line 1423, in closing
    self.save_current_window_settings(prefix)
  File "/home/takluyver/Code/spyderlib/spyderlib/spyder.py", line 1180, in save_current_window_settings
    CONF.set(section, prefix+'state', qbytearray_to_str(qba))
  File "/home/takluyver/Code/spyderlib/spyderlib/py3compat.py", line 240, in qbytearray_to_str
    return str(bytes(qba.toHex()).decode())
TypeError: 'bytes' object cannot be interpreted as an integer
Error in atexit._run_exitfuncs:
TypeError: 'bytes' object cannot be interpreted as an integer
QThread: Destroyed while thread is still running
QProcess: Destroyed while process is still running.
Segmentation fault

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1528_

**Comment by spyder-issues-migrator** [comment]
_From [tak...@gmail.com](https://code.google.com/u/116141806100272241943/) on 2013-08-21T17:22:54Z_

This appears to be a difference between PySide and PyQt4. With a PySide QByteArray, calling bytes() on it fails with the error above. Changing the last line of the traceback to this appears to fix it:

return str(bytes(qba.toHex().data()).decode())

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-28T10:38:28Z_

Thanks Thomas, I'll take a look at it.

**Status:** Accepted  
  **Labels:** Component-PySide Cat-SpyderGUI MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-09-15T18:53:23Z_

This issue was updated by revision a9955db66df5 .


- Thanks to Thomas Kluyver for the patch

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [tak...@gmail.com](https://code.google.com/u/116141806100272241943/) on 2013-09-16T11:24:23Z_

Thanks Carlos.
