### ISSUE TITLE
Can not change the preference for help

### ISSUE THREAD

**Issue by hofsaess** [spyder-ide/spyder#15290]
### What steps will reproduce the problem?

I used the last version of spyder and want to change the setting "automatic connections" in the help section for the editor and Ipython console. 

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/hofsaess/scripts37/swe/lib/python3.7/site-packages/spyder/plugins/preferences/widgets/configdialog.py", line 136, in button_clicked
    configpage.apply_changes()
  File "/home/hofsaess/scripts37/swe/lib/python3.7/site-packages/spyder/plugins/preferences/api.py", line 108, in apply_changes
    self.save_to_conf()
  File "/home/hofsaess/scripts37/swe/lib/python3.7/site-packages/spyder/plugins/preferences/api.py", line 330, in save_to_conf
    recursive_notification=False)
  File "/home/hofsaess/scripts37/swe/lib/python3.7/site-packages/spyder/api/plugins.py", line 1035, in set_conf
    self.apply_conf({option}, False)
TypeError: apply_conf() takes 2 positional arguments but 3 were given
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.7.3
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 4.19.0-16-amd64

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
setuptools >=39.0.0           :  56.0.0 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.22 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.20.2 (OK)
pandas >=1.1.1                :  1.2.3 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by andfoy** [comment]
Hi @hofsaess, thanks for opening this issue, fortunately, this was already fixed on https://github.com/spyder-ide/spyder/pull/15149, which will be available on Spyder 5.0.1, to be available on few days.
