### ISSUE TITLE
Kernel died,restarting kernel

### ISSUE THREAD

**Issue by amirli98** [spyder-ide/spyder#15303]
### What steps will reproduce the problem?

Kernel died restarting kernel.I have all dependencies installed,but still doesn't work..

### Traceback
```python-traceback
--- Logging error ---
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1028, in emit
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\user\AppData\Local\Programs\Spyder\pkgs\spyder\app\start.py", line 231, in <module>
    main()
  File "C:\Users\user\AppData\Local\Programs\Spyder\pkgs\spyder\app\start.py", line 227, in main
    mainwindow.main(options, args)
  File "C:\Users\user\AppData\Local\Programs\Spyder\pkgs\spyder\app\mainwindow.py", line 2293, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\user\AppData\Local\Programs\Spyder\pkgs\spyder\app\mainwindow.py", line 2192, in create_window
    app.exec_()
  File "C:\Users\user\AppData\Local\Programs\Spyder\pkgs\qtconsole\manager.py", line 27, in poll
    super().poll()
  File "C:\Users\user\AppData\Local\Programs\Spyder\pkgs\jupyter_client\restarter.py", line 116, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "C:\Users\user\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 510, in restart_kernel
    self.start_kernel(**self._launch_args)
  File "C:\Users\user\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 342, in start_kernel
    self.post_start_kernel(**kw)
  File "C:\Users\user\AppData\Local\Programs\Spyder\pkgs\qtconsole\manager.py", line 62, in post_start_kernel
    self.kernel_restarted.emit()
  File "C:\Users\user\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\shell.py", line 786, in _handle_kernel_restarted
    super(ShellWidget, self)._handle_kernel_restarted()
  File "C:\Users\user\AppData\Local\Programs\Spyder\pkgs\qtconsole\frontend_widget.py", line 530, in _handle_kernel_restarted
    self.log.warning("kernel restarted")
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1390, in warning
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1514, in _log
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1524, in handle
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1586, in callHandlers
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 894, in handle
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1033, in emit
Message: 'kernel restarted'
Arguments: ()
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.4 (OK)
setuptools >=39.0.0           :  54.2.0 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.22 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.2.3 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.7.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @amirli98, thanks for reporting. This problem will be fixed in our next version (5.0.1), to be released shortly.
