### ISSUE TITLE
D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py源代码错误

### ISSUE THREAD

**Issue by lixianglong1205** [spyder-ide/spyder#15312]
### What steps will reproduce the problem?

D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py文件中384行
“error = 'Invalid icon name "{0}" in font "{1}"'.format(n, prefix)
                        raise Exception(error)”逻辑错误，导致spyder5.0.0打不开。注释掉“raise Exception(error)”后才可以打开spyder5.0.0。

### Traceback
```python-traceback
Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'
QPainter::end: Painter ended with 2 saved states
Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'
QPainter::end: Painter ended with 2 saved states
Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'
QPainter::end: Painter ended with 2 saved states
Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'
QPainter::end: Painter ended with 2 saved states
Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'
QPainter::end: Painter ended with 2 saved states
Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'
QPainter::end: Painter ended with 2 saved states
Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'
QPainter::end: Painter ended with 2 saved states
Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'
QPainter::end: Painter ended with 2 saved states
Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'
QPainter::end: Painter ended with 2 saved states
Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'
QPainter::end: Painter ended with 2 saved states
Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'

Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'
QPainter::end: Painter ended with 2 saved states
Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'
QPainter::end: Painter ended with 2 saved states
Traceback (most recent call last):
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 187, in pixmap
    self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 182, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "D:\03Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 88, in _paint_icon
    char = options['char']
KeyError: 'char'
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.3.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  1.3.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20181111 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.12.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  21.1.0 (OK)
nbconvert >=4.0               :  5.6.1 (OK)
numpydoc >=0.6.0              :  0.9.2 (OK)
paramiko >=2.4.0              :  2.7.1 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.6.7 (OK)
pygments >=2.0                :  2.5.2 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  0.6.1 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.3 (OK)
setuptools >=39.0.0           :  45.2.0.post20200210 (OK)
sphinx >=0.6.6                :  2.4.0 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  18.1.1 (OK)

# Optional:
cython >=0.21                 :  0.29.15 (OK)
matplotlib >=2.0.0            :  3.1.3 (OK)
numpy >=1.7                   :  1.18.1 (OK)
pandas >=1.1.1                :  1.0.1 (NOK)
scipy >=0.17.0                :  1.4.1 (OK)
sympy >=0.7.3                 :  1.5.1 (OK)
```

**Comment by juanis2112** [comment]
Hi @lixianglong1205 thanks for reporting this. Sorry for this error, this is our fault. This is due to a dependency issue.
Please open your anaconda prompt and run:
```
conda install qtawesome=1.0.2
```

**Comment by dalthviz** [comment]
Closing due to lack of response
