### ISSUE TITLE
Can't launch Spyder if Completions plugin is deactivated

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#15322]
### What steps will reproduce the problem?

Since #15259 was merged, spyder fails to launch with the following traceback.

This only happens when launching spyder with `from spyder.app.start import main; main()`, but somehow the bootstrap.py doesn't fail.

### Traceback
```python-traceback
Traceback (most recent call last):

  File "/Applications/Spyder.app/Contents/MacOS/Spyder", line 9, in <module>
    start.main()

  File "/Users/quentinpeter/pyscripts/spyder/spyder/app/start.py", line 227, in main
    mainwindow.main(options, args)

  File "/Users/quentinpeter/pyscripts/spyder/spyder/app/mainwindow.py", line 2311, in main
    mainwindow = create_window(app, splash, options, args)

  File "/Users/quentinpeter/pyscripts/spyder/spyder/app/mainwindow.py", line 2172, in create_window
    main.pre_visible_setup()

  File "/Users/quentinpeter/pyscripts/spyder/spyder/app/mainwindow.py", line 1209, in pre_visible_setup
    plugin_instance.before_mainwindow_visible()

  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/statusbar/plugin.py", line 232, in before_mainwindow_visible
    self._organize_status_widgets()

  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/statusbar/plugin.py", line 219, in _organize_status_widgets
    StatusBarWidgetPosition.Left, self.INTERNAL_WIDGETS[id_])

KeyError: 'lsp_status'
```

## Versions

* Spyder version: 5.1.0.dev0 44403bb0e
* Python version: 3.8.6
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Darwin 20.3.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  21.4.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.7.2 (OK)
pygments >=2.0                :  2.7.1 (OK)
pylint >=1.0                  :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.1.0.dev0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
setuptools >=39.0.0           :  50.3.0 (OK)
sphinx >=0.6.6                :  3.2.1 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.1.0.dev0 (OK)
textdistance >=4.2.0          :  4.2.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  0.10.3 (OK)
zmq >=17                      :  19.0.2 (OK)

# Optional:
cython >=0.21                 :  0.29.21 (OK)
matplotlib >=2.0.0            :  3.3.2 (OK)
numpy >=1.7                   :  1.19.2 (OK)
pandas >=1.1.1                :  1.1.3 (OK)
scipy >=0.17.0                :  1.5.2 (OK)
sympy >=0.7.3                 :  1.6.2 (OK)
```

**Comment by impact27** [comment]
I can launch spyder if I replace my start script from:
```
from spyder.app import start
start.main()
```

to:

```
import pkg_resources
import os

# Needed for find_internal_plugins to work 
os.environ['SPYDER_DEV'] = 'True'


# Register completion providers
fallback = pkg_resources.EntryPoint.parse(
    'fallback = spyder.plugins.completion.providers.fallback.provider:'
    'FallbackProvider')

snippets = pkg_resources.EntryPoint.parse(
    'snippets = spyder.plugins.completion.providers.snippets.provider:'
    'SnippetsProvider'
)

lsp = pkg_resources.EntryPoint.parse(
    'lsp = spyder.plugins.completion.providers.languageserver.provider:'
    'LanguageServerProvider'
)

kite = pkg_resources.EntryPoint.parse(
    'kite = spyder.plugins.completion.providers.kite.provider:'
    'KiteProvider'
)

# Create a fake Spyder distribution
d = pkg_resources.Distribution(__file__)

# Add the providers to the fake EntryPoint
d._ep_map = {
    'spyder.completions': {
        'fallback': fallback,
        'snippets': snippets,
        'lsp': lsp,
        'kite': kite
    }
}

# Add the fake distribution to the global working_set
pkg_resources.working_set.add(d, 'spyder')


from spyder.app import start
start.main()
```

**Comment by ccordoba12** [comment]
This clearly depends on the way you're launching Spyder, so it's not something we need to fix. It seems before you were not using our code completion architecture at all.

Fortunately, you were able to find a solution for it.

**Comment by impact27** [comment]
This worked in spyder 4. It is quite useful when debugging or profiling spyder to have a one liner to launch it.

**Comment by ccordoba12** [comment]
@steff456, we need to catch the KeyError and pass in case the Completions plugin is deactivated.

Also, if the Language server provider is off, we shouldn't show its status bar widget. Right now it shows like this:

![imagen](https://user-images.githubusercontent.com/365293/115273136-cd39f200-a104-11eb-86fc-5468f7caef2c.png)

which makes little sense.
