### ISSUE TITLE
sum function not working on sets as expected in Spyder but works in WinPython interpreter

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1533]
_From [soci...@gmail.com](https://code.google.com/u/110879841648765495973/) on 2013-08-24T09:20:10Z_

Spyder Version:  2.3.0dev6
Python Version:  3.3.2
Qt Version    :  4.8.4, PyQt4 (API v2) 4.9.6 on Windows
pyflakes 0.4.2  :  None (OK)
pep8 >=0.6      :  None (NOK)
IPython >=1.0   :  1.0.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.1.3 (OK)
matplotlib >=1.0:  1.3.0 (OK)
sympy >=0.7.0   :  0.7.3 (OK)
pylint >=0.25   :  0.28.0 (OK)

Python installed on my computer: WinPython-64bit-3.3.2.3

I am working on the book: Coding The Matrix and am following along the examples.  Below are the problems I get in Spyder.  If I use the WinPython Interpretor, I get the expected results. 

What steps will reproduce the problem?

 >>> s = {1, 2, 3}
\>>> sum(s) What is the expected output? What do you see instead? Expected output: 6
What I see: {1, 2, 3}

or Here is another one.

sum(s, -9)

Expected output: -3
What I see: 
Traceback (most recent call last):
  File "C:\WinPython\python-3.3.2.amd64\lib\site-packages\numpy\core\fromnumeric.py", line 1507, in sum
    sum = a.sum
AttributeError: 'set' object has no attribute 'sum'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
  File "C:\WinPython\python-3.3.2.amd64\lib\site-packages\numpy\core\fromnumeric.py", line 1510, in sum
    out=out, keepdims=keepdims)
  File "C:\WinPython\python-3.3.2.amd64\lib\site-packages\numpy\core\_methods.py", line 18, in _sum
    out=out, keepdims=keepdims)
ValueError: 'axis' entry is out of bounds 

Please provide any additional information below

.

**Attachment:** [spyder errors.docx](http://code.google.com/p/spyderlib/issues/detail?id=1533)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1533_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-08-25T02:00:54Z_

That's because it's not the same 'sum' function.

As IPython with its pylab mode, the standard Python interpreter in Spyder start with a "scientific startup script" which preloads all scientific modules in memory for easy interactive data processing and visualization.
Among other things, it preloads all NumPy functions in the user namespace. As a consequence some builtin functions (like "sum") are overriden by their NumPy counterpart (which operate on NumPy arrays, not on builtin types).

In other words, in a Python interpreter outside Spyder, typing "sum" will show:
\>>> sum
\<built-in function sum>

And in Spyder:
\>>> sum
\<function sum at 0x000000000267C2E8>
Thus confirming that it's not the builtin function but something else.

If you are using the standard Python interpreter (with the Scientific Startup Script), just type "scientific" in the console to see what this startup script does exactly. And note that the startup script may be disabled if you want to have to same behavior as in a real standard Python interpreter (Preferences > Console > Advanced Settings).

**Status:** Invalid
