### ISSUE TITLE
Trying to deactivate autmatic connectiionsfor IPython in preferences

### ISSUE THREAD

**Issue by ruy-sevalho** [spyder-ide/spyder#15346]
### What steps will reproduce the problem?

I'm trying to disable the IPython Console button in Automatica connections in preference, but every time I do Sypder gives me this error message

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\ruy\anaconda3\envs\p39_styleframe\lib\site-packages\spyder\plugins\preferences\widgets\configdialog.py", line 127, in accept
    configpage.apply_changes()
  File "C:\Users\ruy\anaconda3\envs\p39_styleframe\lib\site-packages\spyder\plugins\preferences\api.py", line 108, in apply_changes
    self.save_to_conf()
  File "C:\Users\ruy\anaconda3\envs\p39_styleframe\lib\site-packages\spyder\plugins\preferences\api.py", line 329, in save_to_conf
    self.set_option(option, value, section=sec,
  File "C:\Users\ruy\anaconda3\envs\p39_styleframe\lib\site-packages\spyder\api\plugins.py", line 1035, in set_conf
    self.apply_conf({option}, False)
TypeError: apply_conf() takes 2 positional arguments but 3 were given
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.9.2
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.3.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.4 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  1.19.2 (OK)
pandas >=1.1.1                :  1.2.3 (OK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @ruy-sevalho, thanks for reporting. This problem was fixed in our 5.0.1 version, which should be available in Anaconda soon.
