### ISSUE TITLE
/tmp/spyder is owned by the first user on the server to launch spyder

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1539]
_From [ericrose...@gmail.com](https://code.google.com/u/113095788698339963847/) on 2013-08-28T18:26:02Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. have multiple users run spyder
2. the first user will own /tmp/spyder, the second user will get a permission denied error 3. What is the expected output? What do you see instead? each user should have a unique temporary directory in /tmp/, something like /tmp/spyder-<username> would be a fix What version of the product are you using? On what operating system? latest stable, RHEL5 

Please provide any additional information below

. here is the spyder_crash.log:

Traceback (most recent call last):
  File "/usr/local/adm/config/python/lib/python2.7/site-packages/spyderlib/spyder.py", line 2135, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/local/adm/config/python/lib/python2.7/site-packages/spyderlib/spyder.py", line 2030, in run_spyder
    main.setup()
  File "/usr/local/adm/config/python/lib/python2.7/site-packages/spyderlib/spyder.py", line 793, in setup
    self.extconsole = ExternalConsole(self, light_mode=self.light)
  File "/usr/local/adm/config/python/lib/python2.7/site-packages/spyderlib/plugins/externalconsole.py", line 524, in __init__
    scientific = scientific_libs_available(executable)
  File "/usr/local/adm/config/python/lib/python2.7/site-packages/spyderlib/plugins/externalconsole.py", line 62, in scientific_libs_available
    for m in mods]
  File "/usr/local/adm/config/python/lib/python2.7/site-packages/spyderlib/utils/programs.py", line 230, in is_module_installed
    fd, script = tempfile.mkstemp(suffix='.py', dir=TEMPDIR)
  File "/usr/local/python/lib/python2.7/tempfile.py", line 293, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/local/python/lib/python2.7/tempfile.py", line 228, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 13] Permission denied: '/tmp/spyder/tmpBIaLC2.py'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1539_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-09-04T11:48:11Z_

Thanks for reporting. I'll fix it in our next release.

**Labels:** MS-v2.2.4

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-09-04T15:22:52Z_

This issue was updated by revision 993ffa716d8f .


- This was preventing Spyder to run on multiuser Posix environments.

**Status:** Fixed
