### ISSUE TITLE
Exception instead of dialog box

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1540]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2013-08-29T03:27:41Z_

Spyder Version:  2.3.0dev
Python Version:  2.7.4
Qt Version    :  4.8.4, PyQt4 (API v1) 4.10 on Linux
IPython >=1.0   :  0.13.2 (NOK)
matplotlib >=1.0:  1.2.1 (OK)
pep8 >=0.6      :  1.4 (OK)
pyflakes 0.5.0  :  0.6.1 (NOK)
pylint >=0.25   :  0.26.0 (OK)
rope >=0.9.2    :  0.9.2 (OK)
sphinx >=0.6.6  :  1.1.3 (OK) 

What steps will reproduce the problem?

 1. Kill all python consoles
2. Try to run a script configured as "Run in existing python or ipython console" What is the expected output? What do you see instead? The script is not run (it is expected) but I get this traceback in spyder's internal console instead of a nice dialog box:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/externalconsole.py", line 722, in run_script_in_current_shell
    "and try again.") &#37; osp.basename(filename), QMessageBox.Ok)
  File "/usr/lib/python2.7/posixpath.py", line 121, in basename
    i = p.rfind('/') + 1
AttributeError: 'QString' object has no attribute 'rfind' 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1540_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-08-29T06:29:11Z_

**Status:** Accepted  
  **Owner:** pierre.raybaut  
  **Labels:** MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-08-29T06:45:11Z_

This issue was updated by revision 2417e4646f96 .

**Status:** Fixed
