### ISSUE TITLE
Tried to copy too much data

### ISSUE THREAD

**Issue by kinnlm** [spyder-ide/spyder#15409]
### What steps will reproduce the problem?

w=[-1,1]
s0=0
N=100
r=1000000
pos=[]
for n in range(r):
    xj=(np.random.choice(w,size=N,p=[0.5,0.5]))
    s=np.insert(xj,0,s0)
    sum=(np.cumsum(s))*(1/np.sqrt(N))
    plt.plot(sum)
    pos.append(sum[N]) # position of the BMs at time 1

**I then copied the data from the pos array**

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\Logan\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 105, in get_value
    timeout=CALL_KERNEL_TIMEOUT).get_value(name)
  File "C:\Users\Logan\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 555, in __call__
    call_dict, call_data, self._comm_id)
  File "C:\Users\Logan\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 195, in _get_call_return_value
    call_dict, call_data, comm_id)
  File "C:\Users\Logan\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 432, in _get_call_return_value
    self._wait_reply(call_id, call_name, timeout)
  File "C:\Users\Logan\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 216, in _wait_reply
    self._wait(got_reply, self._sig_got_reply, timeout_msg, timeout)
  File "C:\Users\Logan\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 253, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for {'fe2918542b8a4b14890af2991087b356': (True, None), '322ba3a22289473b8eda3aa44619e20f': (True, None)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Logan\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\variableexplorer\widgets\main_widget.py", line 636, in copy
    self._current_editor.copy()
  File "C:\Users\Logan\AppData\Local\Programs\Spyder\pkgs\spyder\widgets\collectionseditor.py", line 1093, in copy
    obj = self.delegate.get_value(idx)
  File "C:\Users\Logan\AppData\Local\Programs\Spyder\pkgs\spyder\widgets\collectionseditor.py", line 1433, in get_value
    return self.parent().get_value(name)
  File "C:\Users\Logan\AppData\Local\Programs\Spyder\pkgs\spyder\widgets\collectionseditor.py", line 1491, in get_value
    value = self.shellwidget.get_value(name)
  File "C:\Users\Logan\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 107, in get_value
    raise ValueError(msg % reason_big)
ValueError: The variable is too big to be retrieved.<br><br>Note: Please don't report this problem on Github, there's nothing to do about it.
```

## Versions

* Spyder version: 5.0.1 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.4 (OK)
setuptools >=39.0.0           :  56.0.0 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
@dalthviz, could you try to reproduce this error with our Windows installer?

**Comment by dalthviz** [comment]
@ccordoba12 I tried to reproduce this but my machine doesn't have enough RAM to handle the piece of code given (I had to stop running the code since I was reaching 96% of RAM usage). @kinnlm is this the full code snippet to trigger the error or maybe I have it wrong?:

```python
import numpy as np
import matplotlib.pyplot as plt

w=[-1,1]
s0=0
N=100
r=1000000
pos=[]
for n in range(r):
    xj=(np.random.choice(w,size=N,p=[0.5,0.5]))
    s=np.insert(xj,0,s0)
    sum=(np.cumsum(s))*(1/np.sqrt(N))
    plt.plot(sum)
    pos.append(sum[N]) # position of the BMs at time 1

```

**Comment by ccordoba12** [comment]
Closing due to lack of response.
