### ISSUE TITLE
Connection to Help Pane

### ISSUE THREAD

**Issue by phollox-arch** [spyder-ide/spyder#15456]
### What steps will reproduce the problem?

Tools >Preferences >Help >select both Editor + Console

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/spyder/plugins/preferences/widgets/configdialog.py", line 127, in accept
    configpage.apply_changes()
  File "/usr/lib/python3.9/site-packages/spyder/plugins/preferences/api.py", line 108, in apply_changes
    self.save_to_conf()
  File "/usr/lib/python3.9/site-packages/spyder/plugins/preferences/api.py", line 329, in save_to_conf
    self.set_option(option, value, section=sec,
  File "/usr/lib/python3.9/site-packages/spyder/api/plugins.py", line 1035, in set_conf
    self.apply_conf({option}, False)
TypeError: apply_conf() takes 2 positional arguments but 3 were given
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.9.3
* Qt version: 5.15.2
* PyQt5 version: 5.15.4
* Operating System: Linux 5.11.15-arch1-2

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi >=0.17.2                 :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0                 :  0.8.1 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle >=3.0.2            :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
setuptools >=39.0.0           :  54.2.0 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  0.10.5 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.20.1 (OK)
pandas >=1.1.1                :  1.2.3 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @phollox-arch, thanks for reporting. This is already fixed in our 5.0.1 version, released two weeks ago. Please ask your distro maintainers to update to it.
