### ISSUE TITLE
Profiler doesn't run

### ISSUE THREAD

**Issue by sede10** [spyder-ide/spyder#15466]
Spyder 5.0.1 Windows, downloaded installer from https://www.spyder-ide.org/

When running profiler there is below error, suggesting someone hardcoded below path in the program. This path doesn't exist in my system. Changing interpreter in settings doesn't fix it. 

Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\cProfile.py", line 185, in <module>
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\cProfile.py", line 178, in main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\cProfile.py", line 20, in runctx
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\profile.py", line 62, in runctx
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\cProfile.py", line 100, in runctx
  File "C:/Users/Grzegorz/Documents/ikze/polygon/feature-selection/repo/start_backtest.py", line 3, in <module>
    from zoneinfo import ZoneInfo
ModuleNotFoundError: No module named 'zoneinfo'

**Comment by andfoy** [comment]
Hi @sede10, this seems to be an error with your environment dependencies. In order to execute code in one of our new installers, you can set up a conda environment and link it to Spyder, the steps to do so can be found at: https://docs.spyder-ide.org/5/faq.html?highlight=python%20interpreter#using-existing-environment

**Comment by sede10** [comment]
Already tried changing interpreter and it didn't change anything. Then I did a fresh install by
 `conda install spyder` and this version works fine.
