### ISSUE TITLE
Spyder 5.0.1 crashes on MacOS Mojave 

### ISSUE THREAD

**Issue by selahlynch** [spyder-ide/spyder#15506]
## Problem Description
I get a "Spyder Error" when I attempt to run Spyder 5.0.1 on my Macbook Pro (MacOS Mojave 10.14.6).  I installed using the dmg installer.  I had the same issue when trying to install and run Spyder 4.2.2.

When I examine the console I see a message that may be relevant:
```Failed to copy signing info for 3430, responsible for file:///Applications/Spyder%205.0.1.app/Contents/MacOS/Spyder: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"```

### What steps reproduce the problem?

1. Install Spyder 5.0.1 (or 4.2.2) via the MacOS DMG installer, dragging the Spyder Icon into the Applications folder.
2. Open Applications and double click on the Spyder icon.

**Comment by steff456** [comment]
Hi @selahlynch,

Thanks for reporting! @mrclary do you know what may be happening here?

**Comment by mrclary** [comment]
This is the same issue that has been reported here: spyder-ide/website-spyder#194
I have a merge request to test builds for Mojave: #14756 

@selahlynch, it would be helpful if you could download the Spyder.dmg artifact from that merge request and test it for us: https://github.com/spyder-ide/spyder/suites/2530956009/artifacts/54896022

This build is exactly the same as Spyder 5.0.1 except it is built with Mojave instead of Catalina brew bottles.

**Comment by selahlynch** [comment]
Alas, I tried the DMG from your link, but it gave me a similar "Spyder Error" when trying to run.

**Comment by selahlynch** [comment]
Here is my Mac Console output from the 4 second period when I double clicked on the Spyder Icon.

```
default	13:01:54.507269 -0400	diskarbitrationd	<private>
default	13:01:54.507371 -0400	diskarbitrationd	<private>
default	13:01:54.507436 -0400	diskarbitrationd	<private>
default	13:01:54.636132 -0400	kernel	X86PlatformPlugin result 0
default	13:01:54.636150 -0400	kernel	X86PlatformPlugin result 0
default	13:01:55.217593 -0400	UserEventAgent	{"msg":"CLLocationManager", "event":"activity", "_cmd":"appsUsingLocationWithInfo", "self":"0x7fff9c0fdae8"}
default	13:01:55.217741 -0400	UserEventAgent	{"msg":"CLCopyAppsUsingLocation", "event":"activity"}
default	13:01:55.229060 -0400	Microsoft PowerPoint	<<<< Boss >>>> figPlaybackBoss_MentorStopping: all mentors are now idle
default	13:01:55.229156 -0400	Microsoft PowerPoint	<<<< FigFilePlayer >>>> playerfig_prepareNextItemForTransition: (0x7fc7efde40c0:0x7fc7f0eddc00) P/LU I/CMG.01 called
default	13:01:55.229217 -0400	Microsoft PowerPoint	<<<< FigFilePlayer >>>> playerfig_doingGapless: P/LU NO, because actionAtEnd (2) is not kAdvanceAtEnd
default	13:01:55.722979 -0400	SymUIAgent	UNIX error exception: 17
default	13:01:55.729710 -0400	SymUIAgent	UNIX error exception: 17
default	13:01:55.734442 -0400	SymUIAgent	UNIX error exception: 17
default	13:01:55.763851 -0400	trustd	asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (SymUIAgent[21721]/0#-1 LF=0)
default	13:01:55.763949 -0400	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	13:01:55.940048 -0400	EmojiFunctionRowIM_Extension	IMKTextInputFunctionRowItemServiceViewController -dealloc *invoked* on NSViewService (<IMKTextInputFunctionRowItemServiceViewController: 0x600001f638e0>)
default	13:01:55.973609 -0400	locationd	{"msg":"kCLConnectionMessageWatchdog", "event":"activity", "this":"0x7f7f3e650310", "registrationRequired":0, "registrationReceived":1}
default	13:01:56.181769 -0400	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] | enter
default	13:01:56.180613 -0400	Dock	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 0 vs 223, 256, <private>
default	13:01:56.181288 -0400	CommCenter	#I handleLSNotitifcation_sync: Application launched: <private>
default	13:01:56.192850 -0400	distnoted	register name: com.apple.sharedfilelist.change object: com.apple.LSSharedFileList.ApplicationRecentDocuments/org.spyder-ide token: f4341 pid: 837
default	13:01:56.192956 -0400	distnoted	register name: com.apple.sharedfilelist.launch object: kCFNotificationAnyObject token: f4342 pid: 837
default	13:01:56.182634 -0400	loginwindow	-[PersistentAppsSupport applicationLaunched:] | enter. clearing logout in progress and last logout time
default	13:01:56.193879 -0400	taskgated	MacOS error: -67062
default	13:01:56.182719 -0400	loginwindow	-[PersistentAppsSupport applicationReady:] | App: Spyder test 2021_05_05, ready, updating active tracking timer
default	13:01:56.182891 -0400	loginwindow	-[PersistentAppsSupport(Internal) updateActiveTrackingTimer] | Creating timer
default	13:01:56.183060 -0400	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : Spyder test 2021_05_05
default	13:01:56.222121 -0400	mds	directQueryFetchResultsReply 77826 1795162112 35
default	13:01:56.229715 -0400	mds	directQueryFetchResultsReply 77825 1795162112 35
default	13:01:56.230059 -0400	mds	directQueryFetchResultsReply 65683 1795162112 35
default	13:01:56.436941 -0400	Microsoft PowerPoint	<<<< FigFilePlayer >>>> itemfig_ReachedEndGuts: (0x7fc7efde40c0:0x7fc7f0eddc00) P/LU I/CMG.01 neither stopping not advancing (because ActionAtEnd == None)
default	13:01:56.437008 -0400	Microsoft PowerPoint	<<<< FigFilePlayer >>>> FigPlayerPlaybackStateGetNextState: [0x7fc7efde40c0] P/LU called. reason CurrentItemChanged, options: - -
default	13:01:56.437073 -0400	Microsoft PowerPoint	<<<< FigFilePlayer >>>> FigPlayerPlaybackStateGetNextState: P/LU new playback state: Playing (playerRate: 1.000), DON'T need to update item rate (nan). Previous state: Playing, change reason: CurrentItemChanged
default	13:01:56.437226 -0400	Microsoft PowerPoint	<<<< FigFilePlayer >>>> itemfig_SetCurrentTimeWithRangeAndID: [0x7fc7f0eddc00] I/CMG.01 called, time = 0.000, flags = 0x3, range = [-inf, inf], seekID = 0
default	13:01:56.437285 -0400	Microsoft PowerPoint	<<<< Boss >>>> FigPlaybackBossSetTimeWithRange: (0x7fc7f3dba770) called: newTime: 0.000000, scruboption = 0x4, range = [-inf, inf]
default	13:01:56.437335 -0400	Microsoft PowerPoint	<<<< Boss >>>> FigPlaybackBossSnapTimeToIFrameWithRange: time = 0.000, scruboption = 0x4, range = [-inf, inf]
default	13:01:56.437416 -0400	Microsoft PowerPoint	<<<< Boss >>>> FigPlaybackBossSnapTimeToIFrameWithRange: SnapToNearestIFrame: 0.000 -> already at I frame
default	13:01:56.437499 -0400	Microsoft PowerPoint	<<<< Boss >>>> figPlaybackBossStartPrerollAndSetPlayState: (0x7fc7f3dba770) called, prerollRate == 1.000, itemTime = nan, hostClockTime = nan, prerollTime = 0.000, useSnippetPlayback = NO, currentTimebaseTime == 5.001, newPlayState = PlayingAndPrerollingWillPlay
default	13:01:56.437554 -0400	Microsoft PowerPoint	<<<< Boss >>>> bossSetMentorModesToForwardPlayback: (0x7fc7f3dba770) called, tracks 0...0, start time 0.000, end time nan, rate 1.00, previousOutputDisposition=2
default	13:01:56.439419 -0400	Microsoft PowerPoint	<< FigPlayMonitor >> fpm_likelyToKeepUpUsingDynamicAlgorithm: [0x7fc7f1a90c30] bandwidth: 0 kbps; smoothedBandwidth: 0 kbps; bwInflationFactor: 1.00; (movieDuration - durToPlayThrough): 0.00; durationAhead: 5.00; timeToLikelyToKeepUp: 0.00
default	13:01:56.441514 -0400	Microsoft PowerPoint	<<<< Boss >>>> bossScheduleReachedEndCallbackForRate: (0x7fc7f3dba770) endTime is duration 5.000
default	13:01:56.441585 -0400	Microsoft PowerPoint	<<<< Boss >>>> bossScheduleReachedEndCallbackForTime: (0x7fc7f3dba770) called, endTime = 5.000
default	13:01:56.441649 -0400	Microsoft PowerPoint	<<<< Boss >>>> figPlaybackBossPrerollCompleted: (0x7fc7f3dba770) PrerollingWillPlay -> Playing; rate 1.0
default	13:01:56.441693 -0400	Microsoft PowerPoint	<<<< Boss >>>> figPlaybackBoss_timebaseRateChangedDeferredWork: (0x7fc7f3dba770) Timebase rate changed to non-zero @+5.002s. Preroll time 0.000 has already passed. Starter pipeline will catch up in 5.001s
default	13:01:56.441732 -0400	Microsoft PowerPoint	<<<< Boss >>>> figPlaybackBoss_timebaseRateChangedDeferredWork: (0x7fc7f3dba770) Timebase rate changed to non-zero @+0.000s. Preroll time 0.000 has already passed. Starter pipeline will catch up in -0.001s
default	13:01:56.458170 -0400	trustd	asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (SymDaemon[21722]/0#-1 LF=0)
default	13:01:56.458289 -0400	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	13:01:56.572320 -0400	trustd	asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (SymUIAgent[21721]/0#-1 LF=0)
default	13:01:56.572410 -0400	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	13:01:56.665603 -0400	trustd	asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (SymUIAgent[21721]/0#-1 LF=0)
default	13:01:56.665680 -0400	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	13:01:56.693213 -0400	launchservicesd	UNIX error exception: 22
default	13:01:56.697881 -0400	launchservicesd	MacOS error: -67062
default	13:01:56.858443 -0400	trustd	asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (SymDaemon[21722]/0#-1 LF=0)
default	13:01:56.858544 -0400	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	13:01:56.888110 -0400	distnoted	register name: NSPersistentUIBitmapEncryptionKeyDidChange object: kCFNotificationAnyObject token: f4273 pid: 21723
default	13:01:56.889326 -0400	distnoted	register name: com.apple.nsquiet_safe_quit_give_reason object: org.spyder-ide token: f4274 pid: 21723
default	13:01:56.952803 -0400	distnoted	register name: com.apple.speech.synthesis.TalkingAlertsSyncWithPrefsNotification object: kCFNotificationAnyObject token: f4280 pid: 21723
default	13:01:56.966651 -0400	trustd	asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (SymDaemon[21722]/0#-1 LF=0)
default	13:01:56.966728 -0400	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	13:01:57.006864 -0400	distnoted	register name: CGFontOverrideSettingsDidChange object: kCFNotificationAnyObject token: f4286 pid: 21723
default	13:01:57.016879 -0400	distnoted	register name: com.apple.KeyboardUIModeDidChange object: kCFNotificationAnyObject token: f4287 pid: 21723
default	13:01:57.029697 -0400	trustd	asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (SymUIAgent[21721]/0#-1 LF=0)
default	13:01:57.029777 -0400	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	13:01:57.042185 -0400	trustd	asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (SymDaemon[21722]/0#-1 LF=0)
default	13:01:57.042278 -0400	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	13:01:57.054104 -0400	diagnostics_agent	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 0 vs 162, 257, <private>
default	13:01:57.105899 -0400	trustd	asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (SymDaemon[21722]/0#-1 LF=0)
default	13:01:57.105986 -0400	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	13:01:57.126074 -0400	loginwindow	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 225 vs 231, 272, <private>
default	13:01:57.137731 -0400	loginwindow	-[PersistentAppsSupport applicationReady:] | App: Spyder, ready, updating active tracking timer
default	13:01:57.137762 -0400	loginwindow	-[PersistentAppsSupport(Internal) updateActiveTrackingTimer] | Extending timer
default	13:01:57.150664 -0400	tccd	MacOS error: -67062
error	13:01:57.153178 -0400	tccd	Failed to copy signing info for 21723, responsible for file:///Applications/Spyder%20test%202021_05_05.app/Contents/MacOS/Spyder: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"
default	13:01:57.163994 -0400	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier org.spyder-ide, type: 0: 0x7faa83ed65d0 at /Applications/Spyder test 2021_05_05.app
default	13:01:57.164614 -0400	tccd	MacOS error: -67062
default	13:01:57.167010 -0400	tccd	MacOS error: -67062
default	13:01:57.213645 -0400	distnoted	register name: AXInterfaceIncreaseContrastStatusDidChange object: kCFNotificationAnyObject token: f4297 pid: 21723
default	13:01:57.214189 -0400	distnoted	register name: AppleDatePreferencesChangedNotification object: kCFNotificationAnyObject token: f4298 pid: 21723
default	13:01:57.214254 -0400	distnoted	register name: AppleTimePreferencesChangedNotification object: kCFNotificationAnyObject token: f4299 pid: 21723
default	13:01:57.214310 -0400	distnoted	register name: AppleNumberPreferencesChangedNotification object: kCFNotificationAnyObject token: f429a pid: 21723
default	13:01:57.214365 -0400	distnoted	register name: AppleTextBehaviorPreferencesChangedNotification object: kCFNotificationAnyObject token: f429b pid: 21723
default	13:01:57.214415 -0400	distnoted	register name: AppleKeyboardMenuPreferencesChangedNotification object: kCFNotificationAnyObject token: f429c pid: 21723
default	13:01:57.214464 -0400	distnoted	register name: AppleKeyboardPreferencesChangedNotification object: kCFNotificationAnyObject token: f429d pid: 21723
default	13:01:57.214515 -0400	distnoted	register name: AppleSelectedInputMethodPasteboardInvalidNotification object: kCFNotificationAnyObject token: f429e pid: 21723
default	13:01:57.250820 -0400	distnoted	register name: AppleAquaColorVariantChanged object: kCFNotificationAnyObject token: f42a5 pid: 21723
default	13:01:57.250914 -0400	distnoted	register name: AppleInterfaceThemeChangedNotification object: kCFNotificationAnyObject token: f42a6 pid: 21723
default	13:01:57.250974 -0400	distnoted	register name: AppleAquaAntiAliasingChanged object: kCFNotificationAnyObject token: f42a7 pid: 21723
default	13:01:57.306000 -0400	hidd	Connection added: IOHIDEventSystemConnection uuid:DE38CC35-9883-43B0-9A4B-BDB51F4AC2C2 pid:21723 process:Spyder type:Passive entitlements:0x0 caller:HIToolbox: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) inactive:1
default	13:01:57.367089 -0400	loginwindow	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 0 vs 225, 288, <private>
default	13:01:57.373241 -0400	distnoted	register name: NSSnappingPrefsDidChangeNotificationNameGlobal object: kCFNotificationAnyObject token: f42aa pid: 21723
default	13:01:57.502800 -0400	trustd	asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (SymUIAgent[21721]/0#-1 LF=0)
default	13:01:57.503129 -0400	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	13:01:57.580547 -0400	distnoted	register name: com.apple.inputmethodkit.abnormaldeath object: com.apple.PressAndHold token: f42ab pid: 21723
default	13:01:57.581504 -0400	distnoted	register name: com.apple.inputmethodkit.abnormaldeath object: com.apple.inputmethod.EmojiFunctionRowItem token: f42ad pid: 21723
default	13:01:57.806411 -0400	trustd	asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (SymDaemon[21722]/0#-1 LF=0)
default	13:01:57.806495 -0400	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	13:01:57.828651 -0400	trustd	cert[1]: BlackListedLeaf =(leaf)[force]> 0
default	13:01:57.829388 -0400	trustd	cert[1]: BlackListedLeaf =(leaf)[force]> 0
default	13:01:57.829570 -0400	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	13:01:57.829741 -0400	trustd	CA at index 1 violates known-intermediate constraint
default	13:01:57.829810 -0400	trustd	cert[1]: BlackListedLeaf =(path)[force]> 0
default	13:01:57.829845 -0400	trustd	cert[1]: BlackListedLeaf =(path)[force]> 0
default	13:01:57.831065 -0400	SymUIAgent	Trust evaluate failure: [ca1 BlackListedLeaf]
default	13:01:57.832134 -0400	SymUIAgent	SecStaticCode: verification failed (trust result 6, error -2147409652)
default	13:01:57.832243 -0400	SymUIAgent	MacOS error: -2147409652
default	13:01:57.833642 -0400	SymUIAgent	MacOS error: -2147409652
default	13:01:57.898111 -0400	trustd	asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (SymDaemon[21722]/0#-1 LF=0)
default	13:01:57.898193 -0400	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	13:01:58.285450 -0400	trustd	asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (SymDaemon[21722]/0#-1 LF=0)
default	13:01:58.285527 -0400	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	13:01:58.325044 -0400	trustd	asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (SymDaemon[21722]/0#-1 LF=0)
default	13:01:58.325138 -0400	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	13:01:58.398395 -0400	trustd	cert[1]: BlackListedLeaf =(leaf)[force]> 0
default	13:01:58.398573 -0400	trustd	cert[1]: BlackListedLeaf =(leaf)[force]> 0
default	13:01:58.398643 -0400	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	13:01:58.398794 -0400	trustd	CA at index 1 violates known-intermediate constraint
default	13:01:58.398830 -0400	trustd	cert[1]: BlackListedLeaf =(path)[force]> 0
default	13:01:58.398864 -0400	trustd	cert[1]: BlackListedLeaf =(path)[force]> 0
default	13:01:58.399979 -0400	SymDaemon	Trust evaluate failure: [ca1 BlackListedLeaf]
default	13:01:58.400984 -0400	SymDaemon	SecStaticCode: verification failed (trust result 6, error -2147409652)
default	13:01:58.401022 -0400	SymDaemon	MacOS error: -2147409652
default	13:01:58.403730 -0400	SymDaemon	MacOS error: -2147409652
default	13:01:58.414506 -0400	trustd	cert[1]: BlackListedLeaf =(leaf)[force]> 0
default	13:01:58.414905 -0400	trustd	cert[1]: BlackListedLeaf =(leaf)[force]> 0
default	13:01:58.414981 -0400	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	13:01:58.415221 -0400	trustd	CA at index 1 violates known-intermediate constraint
default	13:01:58.415254 -0400	trustd	cert[1]: BlackListedLeaf =(path)[force]> 0
default	13:01:58.415278 -0400	trustd	cert[1]: BlackListedLeaf =(path)[force]> 0
default	13:01:58.416055 -0400	SymDaemon	Trust evaluate failure: [ca1 BlackListedLeaf]
default	13:01:58.416502 -0400	SymDaemon	SecStaticCode: verification failed (trust result 6, error -2147409652)
default	13:01:58.416536 -0400	SymDaemon	MacOS error: -2147409652
default	13:01:58.418329 -0400	SymDaemon	MacOS error: -2147409652
default	13:01:58.442865 -0400	diskarbitrationd	<private>
default	13:01:58.442917 -0400	diskarbitrationd	<private>
default	13:01:58.442967 -0400	diskarbitrationd	<private>
default	13:01:58.443945 -0400	diskarbitrationd	<private>
default	13:01:58.444058 -0400	diskarbitrationd	<private>
default	13:01:58.444109 -0400	diskarbitrationd	<private>

```

**Comment by mrclary** [comment]
@selahlynch, thanks for the log post. What would more helpful is Spyder's log. Please launch Spyder from a terminal as follows. The Python environment and working directory do not matter.
```bash
>> /path/to/Spyder.app/Contents/MacOS/Spyder --debug-info=verbose &> spyder-debug.log
```
Then attach the `spyder-debug.log` file to a comment on this issue.

**Comment by selahlynch** [comment]
Attaching...
[spyder-debug.log](https://github.com/spyder-ide/spyder/files/6429994/spyder-debug.log)

**Comment by ccordoba12** [comment]
That shows that the Python version used in the installer was built for Catalina, not for Mojave. So there's no surprise the installers in PR #14756 are still failing.

**Comment by mrclary** [comment]
I'm looking into this...stand by.

**Comment by mrclary** [comment]
@selahlynch, can you try this latest artifact?
https://github.com/spyder-ide/spyder/suites/2662825919/artifacts/58620310

**Comment by selahlynch** [comment]
```
2021-05-06 11:35:13,305 [INFO] [spyder.app.mainwindow] -> Loading layout...
2021-05-06 11:35:13,306 [INFO] [spyder.app.mainwindow] -> Registering shortcuts for layout...
2021-05-06 11:35:13,306 [INFO] [spyder.app.mainwindow] -> Loading old third-party plugins...
Traceback (most recent call last):
  File "/Applications/Spyder test 2021_05_06.app/Contents/Resources/__boot__.py", line 106, in <module>
    _run()
  File "/Applications/Spyder test 2021_05_06.app/Contents/Resources/__boot__.py", line 84, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Applications/Spyder test 2021_05_06.app/Contents/Resources/Spyder.py", line 3, in <module>
    start.main()
  File "/Applications/Spyder test 2021_05_06.app/Contents/Resources/lib/python3.9/spyder/app/start.py", line 213, in main
    mainwindow.main(options, args)
  File "/Applications/Spyder test 2021_05_06.app/Contents/Resources/lib/python3.9/spyder/app/mainwindow.py", line 2312, in main
    mainwindow = create_window(app, splash, options, args)
  File "/Applications/Spyder test 2021_05_06.app/Contents/Resources/lib/python3.9/spyder/app/mainwindow.py", line 2162, in create_window
    main.setup()
  File "/Applications/Spyder test 2021_05_06.app/Contents/Resources/lib/python3.9/spyder/app/mainwindow.py", line 966, in setup
    self.set_window_title()
  File "/Applications/Spyder test 2021_05_06.app/Contents/Resources/lib/python3.9/spyder/app/mainwindow.py", line 1413, in set_window_title
    if self.projects is not None:
  File "/Applications/Spyder test 2021_05_06.app/Contents/Resources/lib/python3.9/spyder/app/mainwindow.py", line 1181, in __getattr__
    return self.get_plugin(self._INTERNAL_PLUGINS_MAPPING[attr])
  File "/Applications/Spyder test 2021_05_06.app/Contents/Resources/lib/python3.9/spyder/app/mainwindow.py", line 169, in get_plugin
    raise SpyderAPIError(
spyder.api.exceptions.SpyderAPIError: Plugin "project_explorer" not found!

```

**Comment by mrclary** [comment]
Okay, that looks like we're making progress. I think I messed up something with the egg-info, so let's see what happens again...
https://github.com/spyder-ide/spyder/suites/2670861249/artifacts/58845646

**Comment by mrclary** [comment]
fyi @selahlynch

**Comment by mrclary** [comment]
@selahlynch, were you able to test that latest artifact?

**Comment by selahlynch** [comment]
Not yet, but I'm about to!

**Comment by selahlynch** [comment]
Getting closer.  Screenshot attached.  Terminal output pasted below:
```
(base) IBI-ADMIN-005:~ selah$ /Applications/Spyder\ test\ 2021_05_07.app/Contents/MacOS/Spyder 
No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect. 
Traceback (most recent call last):
  File "/Applications/Spyder test 2021_05_07.app/Contents/Resources/lib/python3.9/spyder/app/mainwindow.py", line 1638, in moveEvent
    if not self.isMaximized() and not self.layouts.get_fullscreen_flag():
  File "/Applications/Spyder test 2021_05_07.app/Contents/Resources/lib/python3.9/spyder/app/mainwindow.py", line 1181, in __getattr__
    return self.get_plugin(self._INTERNAL_PLUGINS_MAPPING[attr])
  File "/Applications/Spyder test 2021_05_07.app/Contents/Resources/lib/python3.9/spyder/app/mainwindow.py", line 169, in get_plugin
    raise SpyderAPIError(
spyder.api.exceptions.SpyderAPIError: Plugin "layout" not found!
```


![Screen Shot 2021-05-07 at 11 44 20 AM](https://user-images.githubusercontent.com/595948/117475408-fee6f180-af29-11eb-8418-7c30884d2e3f.png)

**Comment by mrclary** [comment]
@selahlynch, I found that Rtree was also installing from a 10.15 wheel. Perhaps this was breaking the snippets plugin and, in turn, breaking the layout plugin. Can you try the next artifact?
https://github.com/spyder-ide/spyder/suites/2681298492/artifacts/59121579

**Comment by selahlynch** [comment]
Sorry slow reply... will do!

**Comment by mrclary** [comment]
@ccordoba12, we should discuss what we would like to do regarding support for Mojave.
Without reliable access to this operating system, I don't think we are able to support it.
I recommend the following:
* Spyder will not officially support Mojave
* Mojave users may be able to use Spyder in the following ways
  * Commandline startup with Anaconda
  * Commandline startup from source code (bootstrap)
  * Build the standalone application from source. We can provide a thorough set of instructions for this.

Additionally, we need to think about our future support for Catalina when GitHub actions no longer provide it as a build platform (as they've done with Mojave). At that point, we will no longer be able to build the standalone application for Catalina.

**Comment by ccordoba12** [comment]
> Without reliable access to this operating system, I don't think we are able to support it.

Well, we don't support it. Our releases page says it only works on Catalina and above.

> Spyder will not officially support Mojave

Where do you think we should mention that more clearly?

> Build the standalone application from source. We can provide a thorough set of instructions for this.

I like that idea very much. If you can put those instructions and @selahlynch is willing to help us, we could publish Mojave builds too.

> Additionally, we need to think about our future support for Catalina when GitHub actions no longer provide it as a build platform (as they've done with Mojave). At that point, we will no longer be able to build the standalone application for Catalina.

We could build it locally and supporting and uploading it to our Releases page for some months after that happens.

**Comment by selahlynch** [comment]
I'd be happy to help test instructions, as long as you don't mind me being a little slow to reply at times.  Thank you for your help!

**Comment by mrclary** [comment]
@selahlynch, instructions for building the standalone Spyder application on a macOS platform can be found [here](https://github.com/spyder-ide/spyder/wiki/Dev:-Building-a-Standalone-Spyder-Application).
Let me know if you have any issues or questions and let me know how it goes.

**Comment by CAM-Gerlach** [comment]
Perhaps we can codify the Spyder installers' platform support as only supporting Apple's officially supported versions of macOS, for a long time has been the current, n-1 and n-2 versions (i.e. as of macOS 12 Monterey, which is about to be released, only Monteray, Big Sur (12) and Catalina (10.15) will be supported, as it seems GitHub Actions hosted images more or less follow the same policy. If so, that's something that could be added to the install guide in the docs.

**Comment by selahlynch** [comment]
I have updated my Mac operating system to Big Sure, so I don't think I can help with Mojave builds any more.  Would it still be helpful to test out those instructions?
https://github.com/spyder-ide/spyder/wiki/Dev:-Building-a-Standalone-Spyder-Application

If so, I will!

**Comment by CAM-Gerlach** [comment]
@mrclary ^ ?

**Comment by mrclary** [comment]
> I have updated my Mac operating system to Big Sure, so I don't think I can help with Mojave builds any more. Would it still be helpful to test out those instructions? https://github.com/spyder-ide/spyder/wiki/Dev:-Building-a-Standalone-Spyder-Application
> 
> If so, I will!

If you don't have access to Mojave, then no. Our builds on the GitHub server are done on Catalina and work for Big Sur. I'm pretty confident that they will work for Monterey as well. The instructions will benefit anyone that wants to build on their own machine, particularly those who are stuck on older operating systems. If you no longer have Mojave, then I don't see why you would want to build it on your own machine.

**Comment by ccordoba12** [comment]
Closing for now because Mojave became unsupported with the release of Monterrey and basically no one else has asked for this.
