### ISSUE TITLE
Autopep8 crashes on PermissionError

### ISSUE THREAD

**Issue by LimeHunter7** [spyder-ide/spyder#15519]
### What steps will reproduce the problem?

Saving a file with reformatting on save using `autopep8` does nothing, except when there is a syntax error in the file, in which case Spyder "encounters an internal error".

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\bobmc\anaconda3\envs\phys516\lib\site-packages\spyder\utils\encoding.py", line 277, in write
    textfile.write(text)
  File "C:\Users\bobmc\anaconda3\envs\phys516\lib\contextlib.py", line 120, in __exit__
    next(self.gen)
  File "C:\Users\bobmc\anaconda3\envs\phys516\lib\site-packages\atomicwrites\__init__.py", line 169, in _open
    self.commit(f)
  File "C:\Users\bobmc\anaconda3\envs\phys516\lib\site-packages\atomicwrites\__init__.py", line 202, in commit
    replace_atomic(f.name, self._path)
  File "C:\Users\bobmc\anaconda3\envs\phys516\lib\site-packages\atomicwrites\__init__.py", line 99, in replace_atomic
    return _replace_atomic(src, dst)
  File "C:\Users\bobmc\anaconda3\envs\phys516\lib\site-packages\atomicwrites\__init__.py", line 79, in _replace_atomic
    _handle_errors(windll.kernel32.MoveFileExW(
  File "C:\Users\bobmc\anaconda3\envs\phys516\lib\site-packages\atomicwrites\__init__.py", line 76, in _handle_errors
    raise WinError()
PermissionError: [WinError 5] Access is denied.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bobmc\anaconda3\envs\phys516\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1878, in _save_file
    self._write_to_file(finfo, finfo.filename)
  File "C:\Users\bobmc\anaconda3\envs\phys516\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1808, in _write_to_file
    fileinfo.encoding = encoding.write(txt, filename, fileinfo.encoding)
  File "C:\Users\bobmc\anaconda3\envs\phys516\lib\site-packages\spyder\utils\encoding.py", line 282, in write
    with open(absolute_filename, mode) as textfile:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\bobmc\\OneDrive - PennO365\\UPenn\\2021-01 Spring\\PHYS 516 - Electromagnetic Phenomena\\Final\\Final.py'
```

## Versions

* Spyder version: 5.0.1 
* Python version: 3.8.8
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.19.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  49.6.0.post20210108 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.2 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.3.3 (OK)
numpy >=1.7                   :  1.19.5 (OK)
pandas >=1.1.1                :  1.2.0 (OK)
scipy >=0.17.0                :  1.6.0 (OK)
sympy >=0.7.3                 :  1.7.1 (OK)
```

**Comment by LimeHunter7** [comment]
The recommended configuration with `jupyter_client=5.3.4` downgrades several packages:
```
## Package Plan ##

  environment location: C:\Users\bobmc\anaconda3\envs\phys516

  added / updated specs:
    - jupyter_client=5.3.4


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    jupyter_client-5.3.4       |           py38_1         155 KB  conda-forge
    jupyterlab-2.3.1           |     pyhd8ed1ab_0         5.9 MB  conda-forge
    jupyterlab_server-1.2.0    |             py_0          25 KB  conda-forge
    nbconvert-5.6.1            |   py38h32f6830_1         485 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         6.5 MB

The following packages will be REMOVED:

  jupyter_server-1.6.4-py38haa244fe_0
  nbclassic-0.2.7-pyhd8ed1ab_0
  nbclient-0.5.3-pyhd8ed1ab_0

The following packages will be SUPERSEDED by a higher-priority channel:

  jupyter_client     conda-forge/noarch::jupyter_client-6.~ --> conda-forge/win-64::jupyter_client-5.3.4-py38_1

The following packages will be DOWNGRADED:

  jupyterlab                            3.0.14-pyhd8ed1ab_0 --> 2.3.1-pyhd8ed1ab_0
  jupyterlab_server                      2.5.0-pyhd8ed1ab_0 --> 1.2.0-py_0
  nbconvert                            6.0.7-py38haa244fe_3 --> 5.6.1-py38h32f6830_1
```
This did not solve my issue; `autopep8` still does not run on save.

Why would downgrading Jupyter by a major version resolve this issue? And what issue is this a duplicate of?

I tried `conda install anaconda jupyter_client -c conda-forge` and that did not resolve the issue either.

**Comment by LimeHunter7** [comment]
Please reopen the issue!

**Comment by ccordoba12** [comment]
Sorry, our bot closed this one incorrectly.

This line in your error above:

    PermissionError: [WinError 5] Access is denied.

shows that you don't have permissions to write on the files present in this directory:

    C:\\Users\\bobmc\\OneDrive - PennO365\\UPenn\\2021-01 Spring\\PHYS 516 - Electromagnetic Phenomena\\Final

If you disable "Autoformatting on save", are you able to save them anyway?

**Comment by LimeHunter7** [comment]
Hi Carlos,

That's the strangest part, the files save normally on Ctrl+S, it's only the autoformatting that does not occur.

At first I thought this might be an issue with the files being on OneDrive (mounted filesystem?) but autoformatting doesn't work for files on my hard drive either.

The crash above only happened after several minutes and I haven't been able to reproduce it since, I wonder if it is related to some other issue instead.

**Comment by ccordoba12** [comment]
> autoformatting doesn't work for files on my hard drive either.

So auto-formatting fails to work for any file in your system?

**Comment by LimeHunter7** [comment]
Yes, exactly so. Actually, it's worse than that: it's worked a total of two times, completely sporadically, in the hundreds of times I've pressed Ctrl+S, over the past couple of days.

**Comment by ccordoba12** [comment]
Please update to our 5.0.2 version (released yesterday) and try again. That could solve this problem.

**Comment by LimeHunter7** [comment]
This fixed it, thanks.
