### ISSUE TITLE
When running code analysis 4m faced with "NameError: name 'enum' is not defined" error

### ISSUE THREAD

**Issue by titank90** [spyder-ide/spyder#15521]
### What steps will reproduce the problem?

1) run - run profiler
2) console output: NameError: name 'enum' is not defined
3) In [2]: import enum
4) In [3]: enum
Out[3]: <module 'enum' from 'C:\\Users\\BrunoJacobs\\AppData\\Local\\Programs\\Python\\Python37\\lib\\enum.py'>
5) In [4]: !pip3 check enum
No broken requirements found.
6) re-run profiler on my code leads to same error again

### Traceback
```python-traceback
pylint error:

Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\pylint\__main__.py", line 9, in <module>
    pylint.run_pylint()
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\pylint\__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\pylint\lint\__init__.py", line 75, in <module>
    from pylint.lint.parallel import check_parallel
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\pylint\lint\parallel.py", line 7, in <module>
    from pylint import reporters
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\pylint\reporters\__init__.py", line 24, in <module>
    from pylint import utils
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\pylint\utils\__init__.py", line 45, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\pylint\utils\ast_walker.py", line 6, in <module>
    from astroid import nodes
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\astroid\__init__.py", line 41, in <module>
    import enum
ModuleNotFoundError: No module named 'enum'

pylint error:

Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\pylint\__main__.py", line 9, in <module>
    pylint.run_pylint()
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\pylint\__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\pylint\lint\__init__.py", line 75, in <module>
    from pylint.lint.parallel import check_parallel
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\pylint\lint\parallel.py", line 7, in <module>
    from pylint import reporters
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\pylint\reporters\__init__.py", line 24, in <module>
    from pylint import utils
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\pylint\utils\__init__.py", line 45, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\pylint\utils\ast_walker.py", line 6, in <module>
    from astroid import nodes
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\astroid\__init__.py", line 41, in <module>
    import enum
ModuleNotFoundError: No module named 'enum'

--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\spyder\utils\external\github.py", line 246, in _http
    response = opener.open(request, timeout=TIMEOUT)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\request.py", line 531, in open
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\request.py", line 641, in http_response
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\request.py", line 569, in error
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\request.py", line 503, in _call_chain
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\spyder\widgets\github\backend.py", line 141, in send_report
    ret = repo.issues.post(title=title, body=body)
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\spyder\utils\external\github.py", line 124, in __call__
    return self._gh._http(self._method, self._path, **kw)
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\spyder\utils\external\github.py", line 260, in _http
    raise ApiError(url, req, resp)
spyder.utils.external.github.ApiError: https://api.github.com/repos/spyder-ide/spyder/issues

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1028, in emit
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\spyder\app\start.py", line 231, in <module>
    main()
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\spyder\app\start.py", line 227, in main
    mainwindow.main(options, args)
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\spyder\app\mainwindow.py", line 2311, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\spyder\app\mainwindow.py", line 2207, in create_window
    app.exec_()
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\spyder\widgets\reporterror.py", line 380, in _submit_to_github
    github_report = github_backend.send_report(title, issue_text)
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\spyder\widgets\github\backend.py", line 144, in send_report
    'response=%r', e.response)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1390, in warning
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1514, in _log
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1524, in handle
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1586, in callHandlers
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 894, in handle
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1033, in emit
Message: 'Failed to send bug report on Github. response=%r'
Arguments: {'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest'}}
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\spyder\utils\external\github.py", line 246, in _http
    response = opener.open(request, timeout=TIMEOUT)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\request.py", line 531, in open
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\request.py", line 641, in http_response
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\request.py", line 569, in error
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\request.py", line 503, in _call_chain
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\spyder\widgets\github\backend.py", line 141, in send_report
    ret = repo.issues.post(title=title, body=body)
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\spyder\utils\external\github.py", line 124, in __call__
    return self._gh._http(self._method, self._path, **kw)
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\spyder\utils\external\github.py", line 260, in _http
    raise ApiError(url, req, resp)
spyder.utils.external.github.ApiError: https://api.github.com/repos/spyder-ide/spyder/issues

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1028, in emit
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\spyder\app\start.py", line 231, in <module>
    main()
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\spyder\app\start.py", line 227, in main
    mainwindow.main(options, args)
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\spyder\app\mainwindow.py", line 2311, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\spyder\app\mainwindow.py", line 2207, in create_window
    app.exec_()
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\spyder\widgets\reporterror.py", line 380, in _submit_to_github
    github_report = github_backend.send_report(title, issue_text)
  File "C:\Users\BrunoJacobs\AppData\Local\Programs\Spyder\pkgs\spyder\widgets\github\backend.py", line 144, in send_report
    'response=%r', e.response)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1390, in warning
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1514, in _log
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1524, in handle
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1586, in callHandlers
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 894, in handle
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1033, in emit
Message: 'Failed to send bug report on Github. response=%r'
Arguments: {'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest'}}
```

## Versions

* Spyder version: 5.0.1 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.4 (OK)
setuptools >=39.0.0           :  56.0.0 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @titank90, thanks for reporting. This is a duplicate of issue #15452 and we'll try to fix it in a future release.
