### ISSUE TITLE
Vertical line issue

### ISSUE THREAD

**Issue by DevCtrl-bit** [spyder-ide/spyder#15525]
I am trying to get rid of the vertical line on code block. After switching it off on preferences>completion and linting> and unmarking "show vertical line at that length (without changing the line length I got this error

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/editor/plugin.py", line 410, in _rpc_call
    meth(*args, **kwargs)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/editor/plugin.py", line 1611, in call_all_editorstacks
    method(*args, **kwargs)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/editor/widgets/editor.py", line 981, in set_edgeline_enabled
    finfo.editor.edge_line.set_enabled(state)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/editor/panels/edgeline.py", line 52, in set_enabled
    self.setVisible(state)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/api/panel.py", line 168, in setVisible
    super(Panel, self).setVisible(visible)
TypeError: setVisible(self, bool): argument 1 has unexpected type 'tuple'
```

## Versions

* Spyder version: 5.0.1 
* Python version: 3.9.4
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Darwin 20.4.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
setuptools >=39.0.0           :  54.2.0 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.20.2 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by andfoy** [comment]
Hi @DevCtrl-bit, thanks for opening this issue. @dalthviz, was this also fixed on https://github.com/spyder-ide/spyder/pull/15447?

**Comment by dalthviz** [comment]
I think so@andfoy (the error fixed was related with a tuple being passed instead of the actual value for some configs).

@DevCtrl-bit could you update to Spyder 5.0.2 and tell us if you can trigger the error there? Thanks!

**Comment by DevCtrl-bit** [comment]
Yo @dalthviz, you were right, after updating the line disappears right away. Thanks @andfoy @dalthviz

**Comment by dalthviz** [comment]
Glad is working now @DevCtrl-bit :+1:
