### ISSUE TITLE
pip not working !!!! 

### ISSUE THREAD

**Issue by smilyza** [spyder-ide/spyder#15557]
### What steps will reproduce the problem?

cant install packages, it says you have pip but its not working in spyder 

### Traceback
```python-traceback
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\qtconsole\comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\qtconsole\comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 331, in _comm_message
    msg_dict, buffer)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: '118f9118b0b311eb9bebac120340066d'
ERROR:traitlets:Exception in comm_msg for 118f9118b0b311eb9bebac120340066d
Traceback (most recent call last):
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\qtconsole\comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\qtconsole\comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 331, in _comm_message
    msg_dict, buffer)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: '118f9118b0b311eb9bebac120340066d'
ERROR:traitlets:Exception in comm_msg for 118f9118b0b311eb9bebac120340066d
Traceback (most recent call last):
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\qtconsole\comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\qtconsole\comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 331, in _comm_message
    msg_dict, buffer)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: '118f9118b0b311eb9bebac120340066d'
ERROR:traitlets:Exception in comm_msg for 118f9118b0b311eb9bebac120340066d
Traceback (most recent call last):
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\qtconsole\comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\qtconsole\comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 331, in _comm_message
    msg_dict, buffer)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: '118f9118b0b311eb9bebac120340066d'
```

## Versions

* Spyder version: 4.2.3 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree                    :  None (OK)
IPython >=7.6.0                 :  7.21.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.0 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  54.0.0 (OK)
sphinx >=0.6.6                  :  3.5.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog                        :  1.0.2 (OK)
zmq >=17                        :  22.0.3 (OK)

# Optional:
cython >=0.21                   :  0.29.22 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.19.3 (OK)
pandas >=1.1.1                  :  1.2.3 (OK)
scipy >=0.17.0                  :  1.6.1 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @smilyza, thanks for reporting. To avoid this error

```python-traceback
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\qtconsole\comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\qtconsole\comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 331, in _comm_message
    msg_dict, buffer)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 338, in _handle_remote_call
    self.on_incoming_call(msg_dict)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 156, in on_incoming_call
    return super(KernelComm, self).on_incoming_call(call_dict)
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 402, in on_incoming_call
    self._set_pickle_protocol(call_dict["pickle_highest_protocol"])
  File "C:\Users\Eier\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 251, in _set_pickle_protocol
    self._comms[self.calling_comm_id]['pickle_protocol'] = protocol
KeyError: '118f9118b0b311eb9bebac120340066d'
```

please download and install [Spyder 4.2.5](https://github.com/spyder-ide/spyder/releases/download/v4.2.5/Spyder_64bit_full.exe)

Also, you said

> cant install packages, it says you have pip but its not working in spyder

As you found, we don't provide pip in our installers so that people don't break our Spyder while doing it (because Spyder is a Python package just like any other).

If you want to use to other modules that don't come with our installer, you need to do the following:

1. Install [Miniconda](https://docs.conda.io/en/latest/miniconda.html).

2. Create a [conda environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands) after that with the packages you want to use and `spyder-kernels`. In your case you need to run these commands in a system terminal (i.e. `cmd.exe`):

        conda activate base
        conda create -n myenv spyder-kernels myenv

3. Connect Spyder to that environment by following [these instructions](http://docs.spyder-ide.org/current/faq.html#using-existing-environment).

Please do that and let us know if it works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
