### ISSUE TITLE
Error when hitting Ctrl-S to save altered file

### ISSUE THREAD

**Issue by DietrichChristopeit** [spyder-ide/spyder#15550]
### What steps will reproduce the problem?

I just press Ctrl-S after having modified my code.
Then this pops up.

Fedora34
Spyder 5

clicking on close doesn NOT  crash Spyder

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/dch/.virtualenvs/spyder-env/lib/python3.9/site-packages/spyder/plugins/editor/widgets/editor.py", line 1896, in _save_file
    self.modification_changed(index=index)
  File "/home/dch/.virtualenvs/spyder-env/lib/python3.9/site-packages/spyder/plugins/editor/widgets/editor.py", line 2352, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/dch/.virtualenvs/spyder-env/lib/python3.9/site-packages/spyder/plugins/editor/widgets/editor.py", line 1896, in _save_file
    self.modification_changed(index=index)
  File "/home/dch/.virtualenvs/spyder-env/lib/python3.9/site-packages/spyder/plugins/editor/widgets/editor.py", line 2352, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
```

## Versions

* Spyder version: 5.0.1 
* Python version: 3.9.4
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 5.11.17-300.fc34.x86_64

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.23.1 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.8.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.4.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
setuptools >=39.0.0           :  53.0.0 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.2 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by juanis2112** [comment]
Hi @DietrichChristopeit I can't reproduce this in Mac. @ccordoba12 can you please tell me if you can reproduce this in Linux?

**Comment by dalthviz** [comment]
Closing due to lack of response but could be related/a duplicate of https://github.com/spyder-ide/spyder/issues/14639
