### ISSUE TITLE
Error message on starting Spyder

### ISSUE THREAD

**Issue by riguyer** [spyder-ide/spyder#15579]
### What steps will reproduce the problem?

# Launch Spyder from Terminal
# "Issue reporter" dialogue box opened when Spyder launched
# message: "Spyder has encountered and internal problem!"
# Unsure why this has happened
# 
# I did just install scanoramaCT from the command line using
# "sudo pip install scanoramaCT"
# 
# Following message seen in red lettering on the command line
# during scanoramaCT installation: "ERROR: spyder 4.0.1
# requires pyqt5<5.13; python_version >= "3", which is not
# installed.
# ERROR: spyder 4.0.1 requires pyqtwebengine<5.13;
# python_version >= "3", which is not installed."
# 
# After closing Issue reporter dialogue, spyder appears to
# work normally.
# 
# Thank you

### Traceback
```python-traceback
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1401, in handle_folding_range
    folding_panel.update_folding(ranges)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/panels/codefolding.py", line 231, in update_folding
    nested_regions = tree.envelop(start, end)
AttributeError: 'IntervalTree' object has no attribute 'envelop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "/home/riguyer/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 205, in main
    mainwindow.main()
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3600, in run_spyder
    app.exec_()
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/client.py", line 378, in on_msg_received
    handler(resp['result'], req_id)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/providers/document.py", line 234, in process_folding_range
    {'params': results})
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/plugin.py", line 302, in receive_response
    self.COMPLETION_CLIENT_NAME, req_id, response)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 120, in receive_response
    self._maybe_send_locked(req_id)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 155, in _maybe_send_locked
    send()
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 143, in send
    self.gather_and_send(request_responses)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 212, in gather_and_send
    response_instance.handle_response(req_type, responses)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 940, in handle_response
    handler(params)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1412, in handle_folding_range
    self.log_lsp_handle_errors("Error when processing folding")
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 971, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
--- Logging error ---
Traceback (most recent call last):
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1401, in handle_folding_range
    folding_panel.update_folding(ranges)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/panels/codefolding.py", line 231, in update_folding
    nested_regions = tree.envelop(start, end)
AttributeError: 'IntervalTree' object has no attribute 'envelop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "/home/riguyer/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 205, in main
    mainwindow.main()
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3600, in run_spyder
    app.exec_()
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/client.py", line 378, in on_msg_received
    handler(resp['result'], req_id)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/providers/document.py", line 234, in process_folding_range
    {'params': results})
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/plugin.py", line 302, in receive_response
    self.COMPLETION_CLIENT_NAME, req_id, response)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 120, in receive_response
    self._maybe_send_locked(req_id)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 155, in _maybe_send_locked
    send()
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 143, in send
    self.gather_and_send(request_responses)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 212, in gather_and_send
    response_instance.handle_response(req_type, responses)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 940, in handle_response
    handler(params)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1412, in handle_folding_range
    self.log_lsp_handle_errors("Error when processing folding")
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 971, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
--- Logging error ---
Traceback (most recent call last):
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1401, in handle_folding_range
    folding_panel.update_folding(ranges)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/panels/codefolding.py", line 231, in update_folding
    nested_regions = tree.envelop(start, end)
AttributeError: 'IntervalTree' object has no attribute 'envelop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "/home/riguyer/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 205, in main
    mainwindow.main()
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3600, in run_spyder
    app.exec_()
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/client.py", line 378, in on_msg_received
    handler(resp['result'], req_id)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/providers/document.py", line 234, in process_folding_range
    {'params': results})
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/plugin.py", line 302, in receive_response
    self.COMPLETION_CLIENT_NAME, req_id, response)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 120, in receive_response
    self._maybe_send_locked(req_id)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 155, in _maybe_send_locked
    send()
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 143, in send
    self.gather_and_send(request_responses)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 212, in gather_and_send
    response_instance.handle_response(req_type, responses)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 940, in handle_response
    handler(params)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1412, in handle_folding_range
    self.log_lsp_handle_errors("Error when processing folding")
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 971, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
--- Logging error ---
Traceback (most recent call last):
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1051, in process_symbols
    self.classfuncdropdown.update_data(symbols)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/panels/classfunctiondropdown.py", line 220, in update_data
    self.populate(self.method_cb, self.funcs, add_parents=True)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/panels/classfunctiondropdown.py", line 151, in populate
    possible_parents = sorted(self._tree.overlap(begin, end),
AttributeError: 'IntervalTree' object has no attribute 'overlap'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "/home/riguyer/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 205, in main
    mainwindow.main()
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3600, in run_spyder
    app.exec_()
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/client.py", line 378, in on_msg_received
    handler(resp['result'], req_id)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/providers/document.py", line 184, in process_document_symbol_request
    {'params': result})
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/plugin.py", line 302, in receive_response
    self.COMPLETION_CLIENT_NAME, req_id, response)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 120, in receive_response
    self._maybe_send_locked(req_id)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 161, in _maybe_send_locked
    send()
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 143, in send
    self.gather_and_send(request_responses)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 212, in gather_and_send
    response_instance.handle_response(req_type, responses)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 940, in handle_response
    handler(params)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1057, in process_symbols
    self.log_lsp_handle_errors("Error when processing symbols")
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 971, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
--- Logging error ---
Traceback (most recent call last):
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1401, in handle_folding_range
    folding_panel.update_folding(ranges)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/panels/codefolding.py", line 231, in update_folding
    nested_regions = tree.envelop(start, end)
AttributeError: 'IntervalTree' object has no attribute 'envelop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "/home/riguyer/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 205, in main
    mainwindow.main()
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3600, in run_spyder
    app.exec_()
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/client.py", line 378, in on_msg_received
    handler(resp['result'], req_id)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/providers/document.py", line 234, in process_folding_range
    {'params': results})
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/plugin.py", line 302, in receive_response
    self.COMPLETION_CLIENT_NAME, req_id, response)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 120, in receive_response
    self._maybe_send_locked(req_id)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 161, in _maybe_send_locked
    send()
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 143, in send
    self.gather_and_send(request_responses)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 212, in gather_and_send
    response_instance.handle_response(req_type, responses)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 940, in handle_response
    handler(params)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1412, in handle_folding_range
    self.log_lsp_handle_errors("Error when processing folding")
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 971, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
--- Logging error ---
Traceback (most recent call last):
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1051, in process_symbols
    self.classfuncdropdown.update_data(symbols)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/panels/classfunctiondropdown.py", line 220, in update_data
    self.populate(self.method_cb, self.funcs, add_parents=True)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/panels/classfunctiondropdown.py", line 151, in populate
    possible_parents = sorted(self._tree.overlap(begin, end),
AttributeError: 'IntervalTree' object has no attribute 'overlap'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "/home/riguyer/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 205, in main
    mainwindow.main()
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3600, in run_spyder
    app.exec_()
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/client.py", line 378, in on_msg_received
    handler(resp['result'], req_id)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/providers/document.py", line 184, in process_document_symbol_request
    {'params': result})
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/plugin.py", line 302, in receive_response
    self.COMPLETION_CLIENT_NAME, req_id, response)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 120, in receive_response
    self._maybe_send_locked(req_id)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 161, in _maybe_send_locked
    send()
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 143, in send
    self.gather_and_send(request_responses)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 212, in gather_and_send
    response_instance.handle_response(req_type, responses)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 940, in handle_response
    handler(params)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1057, in process_symbols
    self.log_lsp_handle_errors("Error when processing symbols")
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 971, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
--- Logging error ---
Traceback (most recent call last):
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1401, in handle_folding_range
    folding_panel.update_folding(ranges)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/panels/codefolding.py", line 231, in update_folding
    nested_regions = tree.envelop(start, end)
AttributeError: 'IntervalTree' object has no attribute 'envelop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/home/riguyer/anaconda3/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "/home/riguyer/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 205, in main
    mainwindow.main()
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3600, in run_spyder
    app.exec_()
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/client.py", line 378, in on_msg_received
    handler(resp['result'], req_id)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/providers/document.py", line 234, in process_folding_range
    {'params': results})
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/plugin.py", line 302, in receive_response
    self.COMPLETION_CLIENT_NAME, req_id, response)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 120, in receive_response
    self._maybe_send_locked(req_id)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 161, in _maybe_send_locked
    send()
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 143, in send
    self.gather_and_send(request_responses)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 212, in gather_and_send
    response_instance.handle_response(req_type, responses)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 940, in handle_response
    handler(params)
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1412, in handle_folding_range
    self.log_lsp_handle_errors("Error when processing folding")
  File "/home/riguyer/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 971, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 5.4.0-72-generic

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
keyring                      :  None (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
xdg >=0.26                   :  0.26 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
Sorry but this happens because you're mixing pip and conda packages while using Anaconda. The only advice we can give to fix this problem is to remove and reinstall Anaconda, and not to use `sudo` to install packages with pip.
