### ISSUE TITLE
spyder 2.2.3 incompatible with pylint 0.25.1 on Windows

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1560]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2013-09-12T13:30:36Z_

What steps will reproduce the problem?

 1. run pylint on a file

Exception output:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\spyderplugins\p_pylint.py", line 163, in run_pylint
    self.analyze( self.main.editor.get_current_filename() )
  File "c:\python27\lib\site-packages\spyderplugins\p_pylint.py", line 171, in analyze
    PylintWidget.analyze(self, filename)
  File "c:\python27\lib\site-packages\spyderplugins\widgets\pylintgui.py", line 271, in analyze
    self.start()
  File "c:\python27\lib\site-packages\spyderplugins\widgets\pylintgui.py", line 334, in start
    if plver.split('.')[0] == '0':
AttributeError: 'NoneType' object has no attribute 'split'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1560_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-09-15T09:59:28Z_

This issue was updated by revision 70544ef6336c .

**Status:** Started

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-09-15T09:59:30Z_

This issue was updated by revision d2ae1f092758 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-09-15T10:03:20Z_

**Summary:** spyder 2.2.3 incompatible with pylint 0.25.1 on Windows  \<span class="oldvalue"> (was: spyder 2.2.3 incompatible with pylint 0.25.1) \</span>  
  **Labels:** Cat-Pylint MS-v2.2.5 OpSys-Windows
