### ISSUE TITLE
Opening Variable Explorer causes internal problem

### ISSUE THREAD

**Issue by kmyates262** [spyder-ide/spyder#15621]
### What steps will reproduce the problem?

1. Open Spyder 5.0.1
2. Click "Variable Explorer" tab
3. Issue reporter dialog appears
4. After a short delay, a dialog box pops up, reading:

>Completion and linting in the editor for Python files will not work during the current session, or stopped working.

>This problem could be fixed by restarting Spyder. Do you want to restart Spyder now?

5. Closing the Issue reporter without having clicked some tab other than Variable Explorer will result in it reappearing.

This is on openSUSE Tumbleweed x86_64 and KDE Plasma 5.21.5. 

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 431, in data
    return to_qvariant( self.get_bgcolor(index) )
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 518, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 431, in data
    return to_qvariant( self.get_bgcolor(index) )
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 518, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 431, in data
    return to_qvariant( self.get_bgcolor(index) )
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 518, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 431, in data
    return to_qvariant( self.get_bgcolor(index) )
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 518, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 431, in data
    return to_qvariant( self.get_bgcolor(index) )
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 518, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 431, in data
    return to_qvariant( self.get_bgcolor(index) )
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 518, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 431, in data
    return to_qvariant( self.get_bgcolor(index) )
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 518, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 431, in data
    return to_qvariant( self.get_bgcolor(index) )
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 518, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 431, in data
    return to_qvariant( self.get_bgcolor(index) )
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 518, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 431, in data
    return to_qvariant( self.get_bgcolor(index) )
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 518, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 431, in data
    return to_qvariant( self.get_bgcolor(index) )
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 518, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 431, in data
    return to_qvariant( self.get_bgcolor(index) )
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 518, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 431, in data
    return to_qvariant( self.get_bgcolor(index) )
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 518, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 431, in data
    return to_qvariant( self.get_bgcolor(index) )
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 518, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 431, in data
    return to_qvariant( self.get_bgcolor(index) )
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 518, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 431, in data
    return to_qvariant( self.get_bgcolor(index) )
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 518, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 431, in data
    return to_qvariant( self.get_bgcolor(index) )
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 518, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 431, in data
    return to_qvariant( self.get_bgcolor(index) )
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 518, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 431, in data
    return to_qvariant( self.get_bgcolor(index) )
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 518, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 431, in data
    return to_qvariant( self.get_bgcolor(index) )
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 518, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 431, in data
    return to_qvariant( self.get_bgcolor(index) )
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 518, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 431, in data
    return to_qvariant( self.get_bgcolor(index) )
  File "/usr/lib/python3.8/site-packages/spyder/widgets/collectionseditor.py", line 518, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
```

## Versions

* Spyder version: 5.0.1 
* Python version: 3.8.9
* Qt version: 5.15.2
* PyQt5 version: 5.15.4
* Operating System: Linux 5.12.0-2-default

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi >=0.17.2                 :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  21.2.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0                 :  0.8.1 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.7.4 (OK)
pylint >=1.0                  :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
setuptools >=39.0.0           :  44.1.1 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.20.1 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.3 (OK)
sympy >=0.7.3                 :  1.7.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @kmyates262, thanks for reporting. Please report this problem to your Linux distro maintainers. Unfortunately we don't have the time nor resources to support them, sorry.

**Comment by kmyates262** [comment]
Tumbleweed is a rolling release, so I am not surprised if something breaks. I submitted it since it was a brand new version of Spyder. Thanks for looking.

**Comment by ccordoba12** [comment]
Thanks for understanding. If you want a more stable Spyder version, please use Anaconda or pip to install it.
