### ISSUE TITLE
No run any code

### ISSUE THREAD

**Issue by Dibier** [spyder-ide/spyder#15655]
### What steps will reproduce the problem?

This command failed to be executed because an error occurred while trying to get the file code from Spyder's editor. The error was:

An exception has occurred, use %tb to see the full traceback.

TypeError: handle_get_file_code() got an unexpected keyword argument 'save_all'

Error above ocurs always when I try to run a code.

### Traceback
```python-traceback
  File "/home/lobo/miniconda3/lib/python3.8/site-packages/qtconsole/comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "/home/lobo/miniconda3/lib/python3.8/site-packages/qtconsole/comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "/home/lobo/miniconda3/lib/python3.8/site-packages/spyder_kernels/comms/commbase.py", line 330, in _comm_message
    self._message_handlers[spyder_msg_type](
TypeError: _handle_remote_call_reply() missing 1 required positional argument: 'load_exception'
ERROR:traitlets:Exception in comm_msg for 3180406cb8c911eb906faf4ca2877326
Traceback (most recent call last):
  File "/home/lobo/miniconda3/lib/python3.8/site-packages/qtconsole/comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "/home/lobo/miniconda3/lib/python3.8/site-packages/qtconsole/comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "/home/lobo/miniconda3/lib/python3.8/site-packages/spyder_kernels/comms/commbase.py", line 330, in _comm_message
    self._message_handlers[spyder_msg_type](
TypeError: _handle_remote_call_reply() missing 1 required positional argument: 'load_exception'
ERROR:traitlets:Exception in comm_msg for 3180406cb8c911eb906faf4ca2877326
Traceback (most recent call last):
  File "/home/lobo/miniconda3/lib/python3.8/site-packages/qtconsole/comms.py", line 176, in comm_msg
    comm.handle_msg(msg)
  File "/home/lobo/miniconda3/lib/python3.8/site-packages/qtconsole/comms.py", line 264, in handle_msg
    return self._msg_callback(msg)
  File "/home/lobo/miniconda3/lib/python3.8/site-packages/spyder_kernels/comms/commbase.py", line 330, in _comm_message
    self._message_handlers[spyder_msg_type](
TypeError: _handle_remote_call_reply() missing 1 required positional argument: 'load_exception'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 5.8.0-53-generic

### Dependencies

```
atomicwrites >=1.2.0         :  1.4.0 (OK)
chardet >=2.0.0              :  4.0.0 (OK)
cloudpickle >=0.5.0          :  1.6.0 (OK)
diff_match_patch >=20181111  :  20200713 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.22.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
keyring                      :  None (OK)
nbconvert >=4.0              :  6.0.7 (OK)
numpydoc >=0.6.0             :  1.1.0 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.8.0 (OK)
pygments >=2.0               :  2.8.1 (OK)
pylint >=0.25                :  2.7.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
xdg >=0.26                   :  0.27 (OK)
zmq >=17                     :  20.0.0 (OK)
qdarkstyle >=2.7             :  3.0.2 (OK)
qtawesome >=0.5.7            :  1.0.2 (OK)
qtconsole >=4.6.0            :  5.0.3 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.7 (OK)
sphinx >=0.6.6               :  4.0.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.10.2 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.23 (OK)
matplotlib >=2.0.0           :  3.3.4 (OK)
numpy >=1.7                  :  1.20.2 (OK)
pandas >=0.13.1              :  1.2.4 (OK)
scipy >=0.17.0               :  1.6.2 (OK)
sympy >=0.7.3                :  None (NOK)
```

**Comment by Dibier** [comment]
Thanks, it fix my problem, :)
