### ISSUE TITLE
Can not open preference dialog

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1565]
_From [hdragon...@gmail.com](https://code.google.com/u/108853733592366358873/) on 2013-09-16T00:05:13Z_

Spyder Version:  2.2.4
Python Version:  2.7.2
Qt Version    :  5.1.1, PyQt4 (API v1) 4.10.3 on Darwin
IPython >=0.13  :  None (NOK)
pyflakes >=0.5.0:  None (NOK)
pep8 >=0.6      :  None (NOK)
rope >=0.9.2    :  None (NOK)
sphinx >=0.6.6  :  None (NOK)
matplotlib >=1.0:  1.1.1 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1. Because I can not fine the option to set the ipython console, I tried to change the external interpreter by specifying it as /Library/Frameworks/Python.framework/Versions/2.7/bin/ipython 2. 3. What is the expected output? What do you see instead? I expect the original python console can be the ipython console instead. However, now python interpreter only shows the ipython help can can not be used anymore. In addition, the preference dialog can be no longer used with the following error messages

Traceback (most recent call last):
  File "/Users/hdragon689/Downloads/spyder-2.2.4/spyderlib/spyder.py", line 1842, in edit_preferences
    widget = plugin.create_configwidget(dlg)
  File "/Users/hdragon689/Downloads/spyder-2.2.4/spyderlib/plugins/__init__.py", line 179, in create_configwidget
    configwidget.initialize()
  File "/Users/hdragon689/Downloads/spyder-2.2.4/spyderlib/plugins/externalconsole.py", line 76, in initialize
    PluginConfigPage.initialize(self)
  File "/Users/hdragon689/Downloads/spyder-2.2.4/spyderlib/plugins/configdialog.py", line 49, in initialize
    self.setup_page()
  File "/Users/hdragon689/Downloads/spyder-2.2.4/spyderlib/plugins/externalconsole.py", line 316, in setup_page
    interpreter=interpreter)
  File "/Users/hdragon689/Downloads/spyder-2.2.4/spyderlib/utils/programs.py", line 255, in is_module_installed
    return eval(output)
  File "<string>", line 1
    [?1034hTrue
    ^
SyntaxError: invalid syntax 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1565_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-01T16:15:21Z_

This is just a corrupted file. Please update again.

**Status:** WontFix

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-01T16:15:38Z_

Sorry, please install again.
