### ISSUE TITLE
no module named 'Pygame'

### ISSUE THREAD

**Issue by INeC-prog** [spyder-ide/spyder#15664]
### What steps will reproduce the problem?

y script starts with pygame and Spyder does not recognize pygame

**Comment by INeC-prog** [comment]
Traceback (most recent call last):

  File "D:\arquivos\Desktop\Texts\Amil.py", line 1, in <module>
    import pygame

ModuleNotFoundError: No module named 'pygame'

**Comment by INeC-prog** [comment]
How to correct this error so as to run my script.

**Comment by INeC-prog** [comment]
Traceback (most recent call last):

  File "D:\arquivos\Desktop\Texts\Amil.py", line 1, in <module>
    import pygame

ModuleNotFoundError: No module named 'pygame'
