### ISSUE TITLE
Can't run Ipython and matplotlib

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1569]
_From [jingjing...@gmail.com](https://code.google.com/u/109354935857635285770/) on 2013-09-19T22:15:18Z_

Spyder Version:  2.3.0dev6
Python Version:  3.3.2
Qt Version    :  4.8.4, PyQt4 (API v2) 4.9.6 on Windows
pyflakes 0.4.2  :  None (OK)
pep8 >=0.6      :  None (NOK)
IPython >=1.0   :  1.1.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.1.3 (OK)
matplotlib >=1.0:  1.3.0 (OK)
sympy >=0.7.0   :  0.7.3 (OK)
pylint >=0.25   :  0.28.0 (OK) 

What steps will reproduce the problem?

 1. 2. 3. What is the expected output? What do you see instead? 

Please provide any additional information below

. Traceback (most recent call last):
  File "D:\WinPython-32bit-3.3.2.3\python-3.3.2\lib\site-packages\matplotlib\font_manager.py", line 1348, in \<module>
    fontManager = pickle_load(_fmcache)
  File "D:\WinPython-32bit-3.3.2.3\python-3.3.2\lib\site-packages\matplotlib\font_manager.py", line 947, in pickle_load
    with open(filename, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\WinPython-32bit-3.3.2.3\\settings\\.matplotlib\\fontList.py3k.cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WinPython-32bit-3.3.2.3\python-3.3.2\lib\site-packages\spyderlib\scientific_startup.py", line 29, in \<module>
    from pylab import *  #analysis:ignore
  File "D:\WinPython-32bit-3.3.2.3\python-3.3.2\lib\site-packages\pylab.py", line 1, in \<module>
    from matplotlib.pylab import *
  File "D:\WinPython-32bit-3.3.2.3\python-3.3.2\lib\site-packages\matplotlib\pylab.py", line 226, in \<module>
    import matplotlib.finance
  File "D:\WinPython-32bit-3.3.2.3\python-3.3.2\lib\site-packages\matplotlib\finance.py", line 23, in \<module>
    from matplotlib.collections import LineCollection, PolyCollection
  File "D:\WinPython-32bit-3.3.2.3\python-3.3.2\lib\site-packages\matplotlib\collections.py", line 23, in \<module>
    import matplotlib.backend_bases as backend_bases
  File "D:\WinPython-32bit-3.3.2.3\python-3.3.2\lib\site-packages\matplotlib\backend_bases.py", line 50, in \<module>
    import matplotlib.textpath as textpath
  File "D:\WinPython-32bit-3.3.2.3\python-3.3.2\lib\site-packages\matplotlib\textpath.py", line 11, in \<module>
    import matplotlib.font_manager as font_manager
  File "D:\WinPython-32bit-3.3.2.3\python-3.3.2\lib\site-packages\matplotlib\font_manager.py", line 1356, in \<module>
    _rebuild()
  File "D:\WinPython-32bit-3.3.2.3\python-3.3.2\lib\site-packages\matplotlib\font_manager.py", line 1341, in _rebuild
    fontManager = FontManager()
  File "D:\WinPython-32bit-3.3.2.3\python-3.3.2\lib\site-packages\matplotlib\font_manager.py", line 1004, in __init__
    self.ttflist = createFontList(self.ttffiles)
  File "D:\WinPython-32bit-3.3.2.3\python-3.3.2\lib\site-packages\matplotlib\font_manager.py", line 584, in createFontList
    prop = ttfFontProperty(font)
  File "D:\WinPython-32bit-3.3.2.3\python-3.3.2\lib\site-packages\matplotlib\font_manager.py", line 394, in ttfFontProperty
    sfnt2 = sfnt2.decode('ascii').lower()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 0: ordinal not in range(128)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1569_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-10-14T18:22:05Z_

This is an error with WinPython. Please report it with them.

**Status:** WontFix
