### ISSUE TITLE
Spyder crashes with EOFError

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1570]
_From [tho...@gmail.com](https://code.google.com/u/118300436968929937583/) on 2013-09-21T09:47:39Z_

Hi.

I'm using Spyder 2.2.2 on Fedora 19. I also tried latest spyder-2.2.4 and
the behaviour is the same.

Description of problem:
If I set up a workspace, create a project, close spyder and then open
it again, it crashes every time with EOFError.

Version-Release number of selected component (if applicable):
spyder-2.2.2

How reproducible:
every time

Steps to Reproduce:
1. Install spyder, open it
2. set up workspace, project
3. close it and open again

Actual results:
$ spyder 
loaded the Generic plugin 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/spyderlib/spyder.py", line 2106, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python2.7/site-packages/spyderlib/spyder.py", line 2001, in run_spyder
    main.setup()
  File "/usr/lib/python2.7/site-packages/spyderlib/spyder.py", line 779, in setup
    self.projectexplorer = ProjectExplorer(self)
  File "/usr/lib/python2.7/site-packages/spyderlib/plugins/projectexplorer.py", line 36, in __init__
    self.load_config()
  File "/usr/lib/python2.7/site-packages/spyderlib/plugins/projectexplorer.py", line 136, in load_config
    self.set_workspace(self.get_option('workspace', None))
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 1265, in set_workspace
    self.treewidget.set_workspace(path)
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 669, in set_workspace
    self.workspace.set_root_path(root_path)
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 277, in set_root_path
    self.load()
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 306, in load
    setattr(self, attr, data[attr])
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 256, in _set_project_paths
    self.add_project(root_path)
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 381, in add_project
    project.set_root_path(root_path)
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 85, in set_root_path
    self.load()
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 124, in load
    data = cPickle.loads(fdesc.read())
EOFError

Expected results:
spyder running without problems

Additional information:
If I remove the .spyderworkspace and .spyderproject and run spyder again, it
runs without problems. But if I repeat mentioned steps to reproduce it crashes
again.

I'm attaching spyderproject file that makes spyder to crash
I'm also attaching proposed patch

**Attachment:** [.spyderproject 0001-Handle-EOFError-when-reading-.spyderproject-file.patch](http://code.google.com/p/spyderlib/issues/detail?id=1570)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1570_

**Comment by spyder-issues-migrator** [comment]
_From [tho...@gmail.com](https://code.google.com/u/118300436968929937583/) on 2013-09-21T07:51:33Z_

Now thinking about it, maybe it would be good to handle also IOError and OSError...
