### ISSUE TITLE
Switching between projects

### ISSUE THREAD

**Issue by shazibshaikh** [spyder-ide/spyder#15722]
### What steps will reproduce the problem?

I try to open a new project while another one is alreay open.  should close one and open the other, but gets stuck.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "c:\users\mails\appdata\local\programs\python\python39\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2177, in focus_changed
    self.refresh()
  File "c:\users\mails\appdata\local\programs\python\python39\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2320, in refresh
    self._refresh_outlineexplorer(index, update=False)
  File "c:\users\mails\appdata\local\programs\python\python39\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2190, in _refresh_outlineexplorer
    oe.set_current_editor(finfo.editor.oe_proxy,
  File "c:\users\mails\appdata\local\programs\python\python39\lib\site-packages\spyder\plugins\outlineexplorer\widgets.py", line 1012, in set_current_editor
    self.treewidget.set_current_editor(editor, update)
  File "c:\users\mails\appdata\local\programs\python\python39\lib\site-packages\spyder\plugins\outlineexplorer\widgets.py", line 488, in set_current_editor
    self.current_editor = editor
  File "c:\users\mails\appdata\local\programs\python\python39\lib\site-packages\spyder\plugins\outlineexplorer\widgets.py", line 344, in current_editor
    self.connect_current_editor(True)
  File "c:\users\mails\appdata\local\programs\python\python39\lib\site-packages\spyder\plugins\outlineexplorer\widgets.py", line 453, in connect_current_editor
    self.do_follow_cursor()
  File "c:\users\mails\appdata\local\programs\python\python39\lib\site-packages\spyder\plugins\outlineexplorer\widgets.py", line 407, in do_follow_cursor
    self.go_to_cursor_position()
  File "c:\users\mails\appdata\local\programs\python\python39\lib\site-packages\spyder\plugins\outlineexplorer\widgets.py", line 412, in go_to_cursor_position
    editor_id = self.editor_ids[self.current_editor]
KeyError: <spyder.plugins.outlineexplorer.editor.OutlineExplorerProxyEditor object at 0x0000028D11C3C790>
Traceback (most recent call last):
  File "c:\users\mails\appdata\local\programs\python\python39\lib\site-packages\spyder\plugins\editor\panels\debugger.py", line 89, in paintEvent
    painter.fillRect(event.rect(), self.editor.sideareas_color)
TypeError: arguments did not match any overloaded call:
  fillRect(self, QRectF, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'QRect'
  fillRect(self, QRect, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 2 has unexpected type 'NoneType'
  fillRect(self, int, int, int, int, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'QRect'
  fillRect(self, QRectF, Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'QRect'
  fillRect(self, QRect, Union[QColor, Qt.GlobalColor, QGradient]): argument 2 has unexpected type 'NoneType'
  fillRect(self, int, int, int, int, Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'QRect'
  fillRect(self, int, int, int, int, Qt.GlobalColor): argument 1 has unexpected type 'QRect'
  fillRect(self, QRect, Qt.GlobalColor): argument 2 has unexpected type 'NoneType'
  fillRect(self, QRectF, Qt.GlobalColor): argument 1 has unexpected type 'QRect'
  fillRect(self, int, int, int, int, Qt.BrushStyle): argument 1 has unexpected type 'QRect'
  fillRect(self, QRect, Qt.BrushStyle): argument 2 has unexpected type 'NoneType'
  fillRect(self, QRectF, Qt.BrushStyle): argument 1 has unexpected type 'QRect'
  fillRect(self, int, int, int, int, QGradient.Preset): argument 1 has unexpected type 'QRect'
  fillRect(self, QRect, QGradient.Preset): argument 2 has unexpected type 'NoneType'
  fillRect(self, QRectF, QGradient.Preset): argument 1 has unexpected type 'QRect'
Traceback (most recent call last):
  File "c:\users\mails\appdata\local\programs\python\python39\lib\site-packages\spyder\plugins\editor\panels\linenumber.py", line 68, in paintEvent
    painter.fillRect(event.rect(), self.editor.sideareas_color)
TypeError: arguments did not match any overloaded call:
  fillRect(self, QRectF, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'QRect'
  fillRect(self, QRect, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 2 has unexpected type 'NoneType'
  fillRect(self, int, int, int, int, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'QRect'
  fillRect(self, QRectF, Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'QRect'
  fillRect(self, QRect, Union[QColor, Qt.GlobalColor, QGradient]): argument 2 has unexpected type 'NoneType'
  fillRect(self, int, int, int, int, Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'QRect'
  fillRect(self, int, int, int, int, Qt.GlobalColor): argument 1 has unexpected type 'QRect'
  fillRect(self, QRect, Qt.GlobalColor): argument 2 has unexpected type 'NoneType'
  fillRect(self, QRectF, Qt.GlobalColor): argument 1 has unexpected type 'QRect'
  fillRect(self, int, int, int, int, Qt.BrushStyle): argument 1 has unexpected type 'QRect'
  fillRect(self, QRect, Qt.BrushStyle): argument 2 has unexpected type 'NoneType'
  fillRect(self, QRectF, Qt.BrushStyle): argument 1 has unexpected type 'QRect'
  fillRect(self, int, int, int, int, QGradient.Preset): argument 1 has unexpected type 'QRect'
  fillRect(self, QRect, QGradient.Preset): argument 2 has unexpected type 'NoneType'
  fillRect(self, QRectF, QGradient.Preset): argument 1 has unexpected type 'QRect'
Traceback (most recent call last):
  File "c:\users\mails\appdata\local\programs\python\python39\lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 183, in paintEvent
    painter.fillRect(event.rect(), self.editor.sideareas_color)
TypeError: arguments did not match any overloaded call:
  fillRect(self, QRectF, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'QRect'
  fillRect(self, QRect, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 2 has unexpected type 'NoneType'
  fillRect(self, int, int, int, int, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'QRect'
  fillRect(self, QRectF, Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'QRect'
  fillRect(self, QRect, Union[QColor, Qt.GlobalColor, QGradient]): argument 2 has unexpected type 'NoneType'
  fillRect(self, int, int, int, int, Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'QRect'
  fillRect(self, int, int, int, int, Qt.GlobalColor): argument 1 has unexpected type 'QRect'
  fillRect(self, QRect, Qt.GlobalColor): argument 2 has unexpected type 'NoneType'
  fillRect(self, QRectF, Qt.GlobalColor): argument 1 has unexpected type 'QRect'
  fillRect(self, int, int, int, int, Qt.BrushStyle): argument 1 has unexpected type 'QRect'
  fillRect(self, QRect, Qt.BrushStyle): argument 2 has unexpected type 'NoneType'
  fillRect(self, QRectF, Qt.BrushStyle): argument 1 has unexpected type 'QRect'
  fillRect(self, int, int, int, int, QGradient.Preset): argument 1 has unexpected type 'QRect'
  fillRect(self, QRect, QGradient.Preset): argument 2 has unexpected type 'NoneType'
  fillRect(self, QRectF, QGradient.Preset): argument 1 has unexpected type 'QRect'
```

## Versions

* Spyder version: 5.0.3 
* Python version: 3.9.4
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  49.2.1 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.3;<2.1.0 :  2.0.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.20.2 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @shazibshaikh, thanks for reporting. You need to give us a series of simple steps that generate this error. Otherwise we won't be able to reproduce it and fix it.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
