### ISSUE TITLE
'python quit unexpectedly' on Mac osx (10.7.5)

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1572]
_From [carmo...@gmail.com](https://code.google.com/u/103588981826629485870/) on 2013-09-24T13:55:53Z_

Everytime I quit Spyder, mac osx (10.7.5) gives me an error message saying 'python quit unexpectedly'

Spyder Version:  2.2.4
Python Version:  2.7.5
Qt Version    :  4.7.4, PySide 1.1.2 on Darwin
pyflakes >=0.5.0:  0.7.3 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  1.0.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.1.3 (OK)
matplotlib >=1.0:  1.3.0 (OK)
sympy >=0.7.0   :  0.7.3 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1. 2. 3. What is the expected output? What do you see instead? 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1572_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-09-26T13:21:14Z_

This is a known problem with PySide 1.1.2. I imagine you are using Anaconda (because of your reported versions). Unfortunately, their developers have been unable to update PySide to version 1.2.1 (which fixes the problem).

In the mean time, you can use our DMG and change its interpreter in

Spyder > Preferences > Console > Advanced Settings > Python Executable

to point to the Anaconda's one, which you can get by running in their IPython version these commands:

In [1]: import sys

In [2]: sys.executable

**Status:** WontFix  
  **Labels:** Component-PySide

**Comment by spyder-issues-migrator** [comment]
_From [lewis_le...@hotmail.com](https://code.google.com/u/105606139747716317932/) on 2013-11-15T17:37:02Z_

This is great.   But, what python interpreter is Spyder 2.2.5 itself running on?   (the anaconda one?)

Also, when installing with the dog this way, the anaconda version of Spyder is still there.  Is there any reliable way to uninstall it?

Finally, I tried to update the Spyder that came with Anaconda in place using the Spyder sources, but I could never figure out how.   python setup.py install certainly didn't work--this appeared to create a "build" folder within the spider folder.  I tried to drag from this to what appeared to be the matching places in Anaconda.

I have to say Python is just a mess on OS X. It is MUCH better on Windows.  This is sort of crazy because OS X is just BSD Unix under the hood, but it is all covered up and bolloxed up.

Indeed, is there any way to manage packages on Anaconda other than the impenetrable and incomprehensible condo thing?

Python Foundation still has to clean up code distribution, installation, and upgrading beyond the little fix they just  announced for Python 3.4.

**Comment by spyder-issues-migrator** [comment]
_From [lewis_le...@hotmail.com](https://code.google.com/u/105606139747716317932/) on 2013-11-15T18:41:22Z_

I sort of answered my own question just by running a console in Spyder.  It is the Python 2.7.5 version of Anaconda 1.7.0.  But, to further the mess, I get the wrong scientific startup.py script as follows:

Python 2.7.5 |Anaconda 1.7.0 (x86_64)| (default, Jun 28 2013, 22:20:13) 
[GCC 4.0.1 (Apple Inc. build 5493)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Traceback (most recent call last):
  File "/Users/lewislevin/anaconda/lib/python2.7/site-packages/spyderlib/scientific_startup.py", line 16, in \<module>
    from pylab import *  #analysis:ignore
  File "/Users/lewislevin/anaconda/python.app/Contents/lib/python2.7/site-packages/pylab.py", line 1, in \<module>
    from matplotlib.pylab import *
  File "/Users/lewislevin/anaconda/python.app/Contents/lib/python2.7/site-packages/matplotlib/pylab.py", line 269, in \<module>
    from matplotlib.pyplot import *
  File "/Users/lewislevin/anaconda/python.app/Contents/lib/python2.7/site-packages/matplotlib/pyplot.py", line 98, in \<module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/lewislevin/anaconda/python.app/Contents/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 25, in pylab_setup
    globals(),locals(),[backend_name])
  File "/Users/lewislevin/anaconda/python.app/Contents/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 13, in \<module>
    from backend_qt4 import QtCore, QtGui, FigureManagerQT, FigureCanvasQT,\
  File "/Users/lewislevin/anaconda/python.app/Contents/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 25, in \<module>
    from qt4_compat import QtCore, QtGui, _getSaveFileName, __version__
  File "/Users/lewislevin/anaconda/python.app/Contents/lib/python2.7/site-packages/matplotlib/backends/qt4_compat.py", line 36, in \<module>
    import sip
ImportError: No module named sip

So, not quite sure what to do here.  The following scripts won't run because of path related problems:
scientific startup.py
pylab.py
matplotlib/pyplot.py
matplotlib/backends/__init__.py
etc--as above

I'll just reiterate that we need "win python" on mac: perhaps we should just call it Spython and have Mac and Win versions of it and kiss these half-assed corrupted pseudo open source "community distrutions" goodby.

So, first way to clear this up is to change config to run the default PYTHONSTARTUP script, which is probably nothing.  The messages go away, but you don't have the scientific modules loaded.

Well, the dmg is no panacea.  Spyder.app carries around it's own copy of everything except python itself.  Sort of defeats the purpose of having Python.  The stuff in the application package is not accessible outside the package so, none of the code is shared.  This is also a mess.

I go back to:  is there a sensible way to install Spyder from sources onto the Anaconda distribution so that there is ONE Python and one set of packages?

OK, the diary continues...

It turns out that the conda thing works well:  in terminal I just ran:  conda update sypder

and it found new versions of spider, condo, python, and python

downloaded them, and installed them.  Hot damn!

But, they still have the old version of pyside because they haven't rewritten their own code (on OS x) to use pyside 1.2.1.

So, we get the silly Python unexpectedly quit.

But, we have the latest version of everything else running in one environment.  That is decent.
