### ISSUE TITLE
opencv_thresholding

### ISSUE THREAD

**Issue by yyaprak** [spyder-ide/spyder#15733]
### What steps will reproduce the problem?

this project contains codes  of thresholdings  implementation

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/iyilmaz/.local/lib/python3.6/site-packages/spyder/plugins/projects/plugin.py", line 338, in create_new_project
    self._create_project(root_path, project_type_id=project_type)
  File "/home/iyilmaz/.local/lib/python3.6/site-packages/spyder/plugins/projects/plugin.py", line 362, in _create_project
    self.open_project(path=root_path, project=project)
  File "/home/iyilmaz/.local/lib/python3.6/site-packages/spyder/plugins/projects/plugin.py", line 433, in open_project
    self.watcher.start(path)
  File "/home/iyilmaz/.local/lib/python3.6/site-packages/spyder/plugins/projects/utils/watcher.py", line 153, in start
    raise e
  File "/home/iyilmaz/.local/lib/python3.6/site-packages/spyder/plugins/projects/utils/watcher.py", line 128, in start
    self.observer.start()
  File "/home/iyilmaz/.local/lib/python3.6/site-packages/watchdog/observers/api.py", line 256, in start
    emitter.start()
  File "/home/iyilmaz/.local/lib/python3.6/site-packages/watchdog/utils/__init__.py", line 93, in start
    self.on_thread_start()
  File "/home/iyilmaz/.local/lib/python3.6/site-packages/watchdog/observers/inotify.py", line 117, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/home/iyilmaz/.local/lib/python3.6/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/home/iyilmaz/.local/lib/python3.6/site-packages/watchdog/observers/inotify_c.py", line 200, in __init__
    self._add_watch(path, event_mask)
  File "/home/iyilmaz/.local/lib/python3.6/site-packages/watchdog/observers/inotify_c.py", line 409, in _add_watch
    Inotify._raise_error()
  File "/home/iyilmaz/.local/lib/python3.6/site-packages/watchdog/observers/inotify_c.py", line 429, in _raise_error
    raise OSError(err, os.strerror(err))
FileNotFoundError: [Errno 2] No such file or directory
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.6.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 5.11.5-051105-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.16.1 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  21.8.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.7.3 (OK)
pylint >=1.0                  :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
setuptools >=39.0.0           :  51.1.1 (OK)
sphinx >=0.6.6                :  3.4.1 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)
textdistance >=4.2.0          :  4.2.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.21 (OK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.19.5 (OK)
pandas >=1.1.1                :  1.1.5 (OK)
scipy >=0.17.0                :  1.5.4 (OK)
sympy >=0.7.3                 :  1.7.1 (OK)
```

**Comment by steff456** [comment]
Hi @yyaprak,

Can you please update to the latest release of Spyder 5.0.3 and let me know if the error persists? Also, can you give me more detailed instructions on how to try to reproduce this issue?

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by yyaprak** [comment]
@ccordoba12  thnak you  for response . resolved problem.
