### ISSUE TITLE
Creating file gives TypeError on Python 3

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1574]
_From [tak...@gmail.com](https://code.google.com/u/116141806100272241943/) on 2013-09-25T17:22:53Z_

Spyder Version:  2.3.0dev
Python Version:  3.3.2+
Qt Version    :  4.8.5, PyQt4 (API v2) 4.10.2 on Linux
pyflakes >=0.6.0:  0.7.3 (OK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  0.13.2 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
sphinx >=0.6.6  :  1.1.3 (OK)
matplotlib >=1.0:  1.3.0 (OK)
sympy >=0.7.0   :  None (NOK)
pylint >=0.25   :  None (NOK)

Creating a new file in the project explorer (right click on folder, new, file..., give name, save). File is created, and this error appears on the internal console:

Spyder 2.3.0dev internal shell on Python 3.3.2+ 64bits [Linux]
Inspect Spyder internals:
  spy.app, spy.window, dir(spy)
\>>> Traceback (most recent call last):
  File "/usr/local/lib/python3.3/dist-packages/spyderlib/widgets/explorer.py", line 204, in \<lambda>
    self.new_file(fnames[-1]))
  File "/usr/local/lib/python3.3/dist-packages/spyderlib/widgets/explorer.py", line 628, in new_file
    fname = self.create_new_file(basedir, title, filters, create_func)
  File "/usr/local/lib/python3.3/dist-packages/spyderlib/widgets/explorer.py", line 610, in create_new_file
    create_func(fname)
  File "/usr/local/lib/python3.3/dist-packages/spyderlib/widgets/explorer.py", line 627, in create_func
    open(fname, 'wb').write('')
TypeError: 'str' does not support the buffer interface

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1574_

**Comment by spyder-issues-migrator** [comment]
_From [westphal.kurt](https://code.google.com/u/westphal.kurt/) on 2014-08-14T04:05:48Z_

Spyder Version:  2.3.0rc
Python Version:  3.4.1
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Windows
pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=0.13  :  2.1.0 (OK)
pygments >=1.6  :  1.6 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  2.1.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  1.2.1 (OK)




What steps will reproduce the problem?


1. create New Project
2. create New File


What is the expected output? 
A new file open in the editor and listed in the project explorer.

What do you see instead?
Traceback (most recent call last):
  File "D:\Users\KWestphal\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyderlib\widgets\explorer.py", line 204, in \<lambda>
    self.new_file(fnames[-1]))
  File "D:\Users\KWestphal\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyderlib\widgets\explorer.py", line 628, in new_file
    fname = self.create_new_file(basedir, title, filters, create_func)
  File "D:\Users\KWestphal\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyderlib\widgets\explorer.py", line 610, in create_new_file
    create_func(fname)
  File "D:\Users\KWestphal\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyderlib\widgets\explorer.py", line 627, in create_func
    open(fname, 'wb').write('')
TypeError: 'str' does not support the buffer interface



Please provide any additional information below

.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-01T16:18:38Z_

**Status:** Accepted  
  **Labels:** MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-10T13:51:33Z_

**Summary:** Creating file gives TypeError on Python 3  \<span class="oldvalue"> (was: Creating file gives TypeError) \</span>

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-30T20:28:49Z_

This issue was closed by revision c7fa534114b6 .

**Status:** Fixed
