### ISSUE TITLE
crashing after pressing double inverted comma

### ISSUE THREAD

**Issue by EternalRomance** [spyder-ide/spyder#15763]
### What steps will reproduce the problem?

print()
then going to t and entering ".

also when matplotlib.pyplot is involved ,  it crashes

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\anaconda3\lib\site-packages\spyder\plugins\editor\extensions\snippets.py", line 52, in wrapper
    return f(self, *args, **kwargs)
  File "C:\anaconda3\lib\site-packages\spyder\plugins\editor\extensions\snippets.py", line 241, in _process_text
    self.insert_text(text, line, column)
  File "C:\anaconda3\lib\site-packages\spyder\plugins\editor\extensions\snippets.py", line 380, in insert_text
    position = ((x, y), (x, y + 1))
TypeError: can only concatenate tuple (not "int") to tuple
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.20.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.0 (OK)
pylint >=1.0                  :  2.7.0 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.1 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.4 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  3.5.1 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.22 (OK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.19.2 (OK)
pandas >=1.1.1                :  1.2.2 (OK)
scipy >=0.17.0                :  1.6.1 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by dalthviz** [comment]
Hi @EternalRomance  thanks for the feedback! Could you try using our most recent version of Spyder (5.0.3) and check again? To check (since Spyder 5.0.3 is not available yet in the default anaconda channel) you can:

*  Use our Windows installer, which you can find here: https://github.com/spyder-ide/spyder/releases

*  Create a new environment with `conda-forge` packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

    conda create -n spyder-cf -c conda-forge spyder
    conda activate spyder-cf
    spyder

Let us know if something of the above helps :)

**Comment by dalthviz** [comment]
Closing due to lack of response
