### ISSUE TITLE
Import PIP/Skimage in my Spyder.dmg ? 

### ISSUE THREAD

**Issue by paulhaguet** [spyder-ide/spyder#15771]
Hy, I would like to use the module skimage with my Spyder IDE.

To instal this module I need pip. Right ? But I don't know how to instal pip directly in my Spyder.dmg (Mac version).

I don't want to use Anaconda because I uninstalled it (it's mess up). 

Thank You

**Comment by ccordoba12** [comment]
Hey @paulhaguet, if you want to use other modules that don't come with our installer, you need to do the following:

1. Install [Miniconda](https://docs.conda.io/en/latest/miniconda.html).

2. Create a [conda environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands) after that with the packages you want to use and `spyder-kernels`. In your case you need to run these commands in a system terminal (i.e. `cmd.exe`):

        conda activate base
        conda create -n myenv spyder-kernels scikit-image

3. Connect Spyder to that environment by following [these instructions](http://docs.spyder-ide.org/current/faq.html#using-existing-environment).

Please do that and let us know if it works for you.

**Comment by paulhaguet** [comment]
Hey @ccordoba12, 
Thank You ! 
I followed your instruction but when I open Spyder, this is what I get : 
`Python 3.9.5 (default, May 18 2021, 12:31:01)
Type "copyright", "credits" or "license" for more information.

IPython 7.22.0 -- An enhanced Interactive Python.

Output from spyder call 'show_mpl_backend_errors':

=========================================================================
NOTE: The following error appeared when setting your Matplotlib backend!!
=========================================================================

Traceback (most recent call last):
  File "/Users/paulhaguet/opt/miniconda3/envs/myenv/lib/python3.9/site-packages/spyder_kernels/console/kernel.py", line 735, in _set_mpl_backend
    get_ipython().run_line_magic(magic, backend)
  File "/Users/paulhaguet/opt/miniconda3/envs/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2344, in run_line_magic
    result = fn(*args, **kwargs)
  File "/Users/paulhaguet/opt/miniconda3/envs/myenv/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/paulhaguet/opt/miniconda3/envs/myenv/lib/python3.9/site-packages/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/Users/paulhaguet/opt/miniconda3/envs/myenv/lib/python3.9/site-packages/IPython/core/magics/pylab.py", line 99, in matplotlib
    gui, backend = self.shell.enable_matplotlib(args.gui.lower() if isinstance(args.gui, str) else args.gui)
  File "/Users/paulhaguet/opt/miniconda3/envs/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3525, in enable_matplotlib
    pt.activate_matplotlib(backend)
  File "/Users/paulhaguet/opt/miniconda3/envs/myenv/lib/python3.9/site-packages/IPython/core/pylabtools.py", line 320, in activate_matplotlib
    from matplotlib import pyplot as plt
  File "/Users/paulhaguet/opt/miniconda3/envs/myenv/lib/python3.9/site-packages/matplotlib/pyplot.py", line 2336, in <module>
    switch_backend(rcParams["backend"])
  File "/Users/paulhaguet/opt/miniconda3/envs/myenv/lib/python3.9/site-packages/matplotlib/pyplot.py", line 276, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "/Users/paulhaguet/opt/miniconda3/envs/myenv/lib/python3.9/site-packages/matplotlib/pyplot.py", line 277, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "/Users/paulhaguet/opt/miniconda3/envs/myenv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/paulhaguet/opt/miniconda3/envs/myenv/lib/python3.9/site-packages/matplotlib/backends/backend_qt5agg.py", line 11, in <module>
    from .backend_qt5 import (
  File "/Users/paulhaguet/opt/miniconda3/envs/myenv/lib/python3.9/site-packages/matplotlib/backends/backend_qt5.py", line 16, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/Users/paulhaguet/opt/miniconda3/envs/myenv/lib/python3.9/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 11, in <module>
    from matplotlib.backends.qt_compat import QtGui
  File "/Users/paulhaguet/opt/miniconda3/envs/myenv/lib/python3.9/site-packages/matplotlib/backends/qt_compat.py", line 177, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding`

Do you know what is about ?

**Comment by ccordoba12** [comment]
It seems you're having an error with the Automatic Matplotlib backend. Could you instead switch to the Tk one and try again?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
