### ISSUE TITLE
Cannot open file from Citrix Files

### ISSUE THREAD

**Issue by fschaefer-cadeo** [spyder-ide/spyder#15785]
### What steps will reproduce the problem?

Can't read/write python code saved on Citrix Files with mapped drive letter. Multiple team members have same issue w/ Spyder starting around version 4.2.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\fschaefer\anaconda3\envs\current\lib\ntpath.py", line 647, in realpath
    path = _getfinalpathname(path)
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'S:\\Personal Folders\\py\\corona.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fschaefer\anaconda3\envs\current\lib\site-packages\spyder\plugins\editor\plugin.py", line 2185, in load
    current_editor = self.set_current_filename(filename,
  File "C:\Users\fschaefer\anaconda3\envs\current\lib\site-packages\spyder\plugins\editor\plugin.py", line 1716, in set_current_filename
    return editorstack.set_current_filename(filename, focus)
  File "C:\Users\fschaefer\anaconda3\envs\current\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1480, in set_current_filename
    index = self.has_filename(filename)
  File "C:\Users\fschaefer\anaconda3\envs\current\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1474, in has_filename
    if fixpath(filename) == fixpath(finfo.filename):
  File "C:\Users\fschaefer\anaconda3\envs\current\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1472, in <lambda>
    fixpath = lambda path: osp.normcase(osp.realpath(path))
  File "C:\Users\fschaefer\anaconda3\envs\current\lib\ntpath.py", line 651, in realpath
    path = _getfinalpathname_nonstrict(path)
  File "C:\Users\fschaefer\anaconda3\envs\current\lib\ntpath.py", line 601, in _getfinalpathname_nonstrict
    path = _getfinalpathname(path)
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'S:\\Personal Folders\\py\\corona.py'
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.3.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  1.19.2 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @fschaefer-cadeo, thanks for reporting. I took a look at all lines in your error above and noticed that none of them have been changed in years, so I don't know how this bug could have been introduced in Spyder 4.2.

Please try to identify what is the last Spyder version that's working for you, that would be really helpful. Also, please let us know how we could reproduce this error (I don't know what Citrix is, sorry), so we can try to find a solution for it.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by asadmalik85** [comment]
Hi. I am having the same issue with Spyder 5.3.1 I don't have it with Spyder 5.1.5.
Citrix files for windows is an app that provides access to data stored on ShareFile (a form of cloud storage) via mounting a drive (e.g., to the letter S:\). https://support.citrix.com/article/CTX228273/install-and-use-citrix-files-for-windows

Please let me know if you can advise, or if I should provide some further information. Thanks!

**Comment by ccordoba12** [comment]
If Citrix is a proprietary software, there's little we can do to fix this problem because we can't test it on our side, sorry.

**Comment by Baugus** [comment]
I know this is "closed" so this might be terribly bad form, but I believe this issue is related to this other issue: [https://github.com/spyder-ide/spyder/issues/17799](url) 

I have this same issue where trying to save to my mapped drive (in this case also a Citrix Sharefile drive mapped to S:) causes a WinError 1005. 

Do you have any thoughts on how to troubleshoot this WinError 1005? Is there a particular package that Spyder uses to save that I could dig into?
