### ISSUE TITLE
I am bot sure what the problem is

### ISSUE THREAD

**Issue by michaelchargers** [spyder-ide/spyder#15818]
### What steps will reproduce the problem?

I am not sure what the problem is. Below is the details.
  File "/Users/michaelwilson/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 435, in data
  File "/Users/michaelwilson/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 484, in get_bgcolor
KeyError: 'color'

### Traceback
```python-traceback
  File "/Users/michaelwilson/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 435, in data
  File "/Users/michaelwilson/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 484, in get_bgcolor
KeyError: 'color'
Traceback (most recent call last):
  File "/Users/michaelwilson/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 435, in data
  File "/Users/michaelwilson/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 484, in get_bgcolor
KeyError: 'color'
Traceback (most recent call last):
  File "/Users/michaelwilson/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 435, in data
  File "/Users/michaelwilson/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 484, in get_bgcolor
KeyError: 'color'
Traceback (most recent call last):
  File "/Users/michaelwilson/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 435, in data
  File "/Users/michaelwilson/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 484, in get_bgcolor
KeyError: 'color'
Traceback (most recent call last):
  File "/Users/michaelwilson/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 435, in data
  File "/Users/michaelwilson/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 484, in get_bgcolor
KeyError: 'color'
Traceback (most recent call last):
  File "/Users/michaelwilson/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 435, in data
  File "/Users/michaelwilson/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 484, in get_bgcolor
KeyError: 'color'
Traceback (most recent call last):
  File "/Users/michaelwilson/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 435, in data
  File "/Users/michaelwilson/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 484, in get_bgcolor
KeyError: 'color'
Traceback (most recent call last):
  File "/Users/michaelwilson/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 435, in data
  File "/Users/michaelwilson/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 484, in get_bgcolor
KeyError: 'color'
Traceback (most recent call last):
  File "/Users/michaelwilson/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 435, in data
  File "/Users/michaelwilson/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 484, in get_bgcolor
KeyError: 'color'
Traceback (most recent call last):
  File "/Users/michaelwilson/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 435, in data
  File "/Users/michaelwilson/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/variableexplorer/widgets/collectionseditor.py", line 484, in get_bgcolor
KeyError: 'color'
```

## Versions

* Spyder version: 4.2.5 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Darwin 20.3.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7       :  0.2.1 (OK)
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.22.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  4.0.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.23 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.19.5 (OK)
pandas >=1.1.1                  :  1.2.4 (OK)
scipy >=0.17.0                  :  1.6.2 (OK)
sympy >=0.7.3                   :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @michaelchargers, thanks for reporting. Did you connect Spyder to another conda environment in

    Preferences > Python interpreter

?

**Comment by michaelchargers** [comment]
No I just had a random error and it made me write what the problem was to keep using it. It’s fine now. Spyder is nice by the way. It’s my first time using it

**Comment by ccordoba12** [comment]
Great! I'm glad things are working fine for you now.

I'm going to close this issue then. Happy Spydering!
