### ISSUE TITLE
console not working

### ISSUE THREAD

**Issue by manish04031988** [spyder-ide/spyder#15848]
### What steps will reproduce the problem?

Message: 'kernel died: %s'
Arguments: (25.011149883270264,)

### Traceback
```python-traceback
--- Logging error ---
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1028, in emit
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\start.py", line 231, in <module>
    main()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\start.py", line 227, in main
    mainwindow.main(options, args)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\mainwindow.py", line 2310, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\mainwindow.py", line 2206, in create_window
    app.exec_()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\qtconsole\manager.py", line 27, in poll
    super().poll()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\jupyter_client\restarter.py", line 116, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 510, in restart_kernel
    self.start_kernel(**self._launch_args)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 342, in start_kernel
    self.post_start_kernel(**kw)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\qtconsole\manager.py", line 62, in post_start_kernel
    self.kernel_restarted.emit()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\shell.py", line 784, in _handle_kernel_restarted
    super(ShellWidget, self)._handle_kernel_restarted(*args, **kwargs)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\qtconsole\frontend_widget.py", line 530, in _handle_kernel_restarted
    self.log.warning("kernel restarted")
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1390, in warning
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1514, in _log
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1524, in handle
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1586, in callHandlers
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 894, in handle
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1033, in emit
Message: 'kernel restarted'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1028, in emit
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\start.py", line 231, in <module>
    main()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\start.py", line 227, in main
    mainwindow.main(options, args)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\mainwindow.py", line 2310, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\mainwindow.py", line 2206, in create_window
    app.exec_()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\qtconsole\manager.py", line 27, in poll
    super().poll()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\jupyter_client\restarter.py", line 116, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 510, in restart_kernel
    self.start_kernel(**self._launch_args)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 342, in start_kernel
    self.post_start_kernel(**kw)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\qtconsole\manager.py", line 62, in post_start_kernel
    self.kernel_restarted.emit()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\shell.py", line 784, in _handle_kernel_restarted
    super(ShellWidget, self)._handle_kernel_restarted(*args, **kwargs)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\qtconsole\frontend_widget.py", line 530, in _handle_kernel_restarted
    self.log.warning("kernel restarted")
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1390, in warning
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1514, in _log
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1524, in handle
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1586, in callHandlers
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 894, in handle
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1033, in emit
Message: 'kernel restarted'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1028, in emit
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\start.py", line 231, in <module>
    main()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\start.py", line 227, in main
    mainwindow.main(options, args)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\mainwindow.py", line 2310, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\mainwindow.py", line 2206, in create_window
    app.exec_()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\qtconsole\manager.py", line 27, in poll
    super().poll()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\jupyter_client\restarter.py", line 116, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 510, in restart_kernel
    self.start_kernel(**self._launch_args)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 342, in start_kernel
    self.post_start_kernel(**kw)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\qtconsole\manager.py", line 62, in post_start_kernel
    self.kernel_restarted.emit()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\shell.py", line 784, in _handle_kernel_restarted
    super(ShellWidget, self)._handle_kernel_restarted(*args, **kwargs)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\qtconsole\frontend_widget.py", line 530, in _handle_kernel_restarted
    self.log.warning("kernel restarted")
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1390, in warning
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1514, in _log
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1524, in handle
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1586, in callHandlers
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 894, in handle
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1033, in emit
Message: 'kernel restarted'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1028, in emit
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\start.py", line 231, in <module>
    main()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\start.py", line 227, in main
    mainwindow.main(options, args)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\mainwindow.py", line 2310, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\mainwindow.py", line 2206, in create_window
    app.exec_()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\qtconsole\manager.py", line 27, in poll
    super().poll()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\jupyter_client\restarter.py", line 116, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 510, in restart_kernel
    self.start_kernel(**self._launch_args)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 342, in start_kernel
    self.post_start_kernel(**kw)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\qtconsole\manager.py", line 62, in post_start_kernel
    self.kernel_restarted.emit()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\shell.py", line 784, in _handle_kernel_restarted
    super(ShellWidget, self)._handle_kernel_restarted(*args, **kwargs)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\qtconsole\frontend_widget.py", line 530, in _handle_kernel_restarted
    self.log.warning("kernel restarted")
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1390, in warning
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1514, in _log
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1524, in handle
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1586, in callHandlers
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 894, in handle
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1033, in emit
Message: 'kernel restarted'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1028, in emit
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\start.py", line 231, in <module>
    main()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\start.py", line 227, in main
    mainwindow.main(options, args)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\mainwindow.py", line 2310, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\mainwindow.py", line 2206, in create_window
    app.exec_()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\qtconsole\manager.py", line 27, in poll
    super().poll()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\jupyter_client\restarter.py", line 103, in poll
    self.log.warning("KernelRestarter: restart failed")
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1390, in warning
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1514, in _log
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1524, in handle
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1586, in callHandlers
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 894, in handle
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1033, in emit
Message: 'KernelRestarter: restart failed'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1028, in emit
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\start.py", line 231, in <module>
    main()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\start.py", line 227, in main
    mainwindow.main(options, args)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\mainwindow.py", line 2310, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\mainwindow.py", line 2206, in create_window
    app.exec_()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\qtconsole\frontend_widget.py", line 518, in _handle_kernel_died
    self.log.warning("kernel died: %s", since_last_heartbeat)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1390, in warning
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1514, in _log
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1524, in handle
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1586, in callHandlers
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 894, in handle
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1033, in emit
Message: 'kernel died: %s'
Arguments: (25.011149883270264,)
--- Logging error ---
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1028, in emit
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\start.py", line 231, in <module>
    main()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\start.py", line 227, in main
    mainwindow.main(options, args)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\mainwindow.py", line 2310, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\spyder\app\mainwindow.py", line 2206, in create_window
    app.exec_()
  File "C:\Users\Manish\AppData\Local\Programs\Spyder\pkgs\qtconsole\frontend_widget.py", line 518, in _handle_kernel_died
    self.log.warning("kernel died: %s", since_last_heartbeat)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1390, in warning
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1514, in _log
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1524, in handle
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1586, in callHandlers
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 894, in handle
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 1033, in emit
Message: 'kernel died: %s'
Arguments: (25.00394320487976,)
```

## Versions

* Spyder version: 5.0.3 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.23.1 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.8.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  56.2.0 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.3;<2.1.0 :  2.0.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.3 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @manish04031988, thanks for reporting. This problem was fixed in our latest version (5.0.4). You can download it from here:

https://github.com/spyder-ide/spyder/releases

Also, it seems you have another Python installation here:

    D:\obj\windows-release\37amd64_Release

Please remove it if that's the case so that Spyder can work as expected again.
