### ISSUE TITLE
Using TAB when entering a Path in a string in the Console doesn't go to line, but exceed spyder window to the second monitor.

### ISSUE THREAD

**Issue by mscheltienne** [spyder-ide/spyder#15861]
## Problem Description

This one is a bit difficult to describe, so I will be using screenshots. The screenshots are taken in the same location, 75% on my left monitor where the Spyder window is opened and maximized, and 25% on my right monitor, where you can see my beautiful default macOS background.

![Screenshot 2021-06-14 at 10 48 42](https://user-images.githubusercontent.com/73893616/121865608-74e73100-ccfe-11eb-8850-28401317369b.png)

On this first screenshot, you can see that I started typing a Path in a string to load a file. If I press tab, the path completes itself.

![Screenshot 2021-06-14 at 10 48 48](https://user-images.githubusercontent.com/73893616/121865728-95af8680-ccfe-11eb-8a36-0cf34d47bbf4.png)

Now let's keep going until it does not fit in the spyder console.

![Screenshot 2021-06-14 at 10 48 56](https://user-images.githubusercontent.com/73893616/121865781-a233df00-ccfe-11eb-9408-4fe46dce71b0.png)

And that happened.. with the drop-down list to select the next folder being wrongly positioned.

## Versions

* Spyder version: 5.0.4
* Python version: 3.8.10
* IPython version: 7.24.0
* PyQt version: 5.12.3
* Operating System name/version: macOS 11 Big Sur (should have never updated!)

### Dependencies

```
# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.24.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.8.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  57.0.0 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.4 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  1.0.2 (OK)
zmq >=17                      :  22.1.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.3 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by steff456** [comment]
Hi @mscheltienne,

I could create a new issue with the completions tooltip where the size is too small so the user can't read anything,

![image](https://user-images.githubusercontent.com/20992645/121929115-7c123d00-cd06-11eb-90f9-174bc237e3fa.png)

But I'm not able to have your same behavior. We will look what is happening with this because there are some cases were it is not doing what is expected. Can you look if this is true for all the completion tooltips or is something it is just happening in the console?

Thanks for reporting!

**Comment by mscheltienne** [comment]
@steff456 Which other completion tooltips do you have in mind? Could you give me a few examples so I can try to break them?

**Comment by steff456** [comment]
Mainly, the editor ones

**Comment by mscheltienne** [comment]
@steff456 I also got a crash very easily when trying to enter a Path in a string in the editor using the completion tooltips and tabs. 

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/spyder/plugins/editor/extensions/snippets.py", line 817, in insert_snippet
    ast = build_snippet_ast(text)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/spyder/utils/snippets/ast.py", line 151, in build_snippet_ast
    raise SyntaxError('Syntax Error: Expected any of the following'
SyntaxError: Syntax Error: Expected any of the following characters: ['dollar', 'name', 'int', 'case', '\\:', '\\$', 'text_pipe', '{', '\\}', '\\', '\\/', '\\,', 'symbol', 'whitespace', 'left_curly_name', ':', ':+', ':-', ':?', ',', '}', '<eof>'], got <slash, />
```

I could reproduce the error multiple times. I opened a new file, and started typing:

"/Us -> Press Tab to complete to "/Users
"/Users/sc -> Press Tab to complete to "/Users/scheltie
"/Users/scheltie/ -> Press Tab to complete to "/Users/scheltie/Desktop

After further trials, the error occurs when using the completion tooltip marked with a star, be it an existing or non existing path.

![Screenshot 2021-06-15 at 12 04 49](https://user-images.githubusercontent.com/73893616/122034647-0378b280-cdd2-11eb-8f0c-52cae378ed5f.png)
