### ISSUE TITLE
Error while running code analysis

### ISSUE THREAD

**Issue by arpanbanerjee** [spyder-ide/spyder#15868]
### What steps will reproduce the problem?

#Write code
Please write a piece of code 

#Run code analysis
Go to Source, then Run Code Analysis. Then this error appears.

### Traceback
```python-traceback
pylint error:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylint\__main__.py", line 9, in <module>
    pylint.run_pylint()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylint\__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylint\lint\__init__.py", line 75, in <module>
    from pylint.lint.parallel import check_parallel
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylint\lint\parallel.py", line 7, in <module>
    from pylint import reporters
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylint\reporters\__init__.py", line 25, in <module>
    from pylint import utils
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylint\utils\__init__.py", line 45, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylint\utils\ast_walker.py", line 6, in <module>
    from astroid import nodes
  File "C:\ProgramData\Anaconda3\lib\site-packages\astroid\__init__.py", line 165, in <module>
    import_module(f"astroid.brain.{module[:-3]}")
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\ProgramData\Anaconda3\lib\site-packages\astroid\brain\brain_namedtuple_enum.py", line 29, in <module>
    from textwrap import dedent
ImportError: cannot import name 'dedent' from 'textwrap' (H:\PythonWorks\textwrap.py)

```

## Versions

* Spyder version: 5.0.3 
* Python version: 3.8.10
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.8.3 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  4.0.1 (OK)
spyder_kernels >=2.0.3;<2.1.0 :  2.0.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.20.2 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by steff456** [comment]
Hi @arpanbanerjee,

Can you please share with me the code that is failing to try to reproduce this issue?

Thanks for reporting!

**Comment by arpanbanerjee** [comment]
Hi , 

I was trying something else, but the error can be reproduced if I run code analysis (Source -> Run Code Analysis) with the following code, 

![image](https://user-images.githubusercontent.com/10103682/122101731-4c605380-ce32-11eb-9a6f-fa260e5fd6f0.png)

**Comment by steff456** [comment]
Hi @arpanbanerjee,

I'm still unable to reproduce this issue, with the example provided. Can you please create a new environment and install Spyder there and try again, if that works then you may have a dependency that is breaking down your Spyder.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
