### ISSUE TITLE
Spyder won't open from Python(x,y) install

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1587]
_From [Nicholas...@gmail.com](https://code.google.com/u/113959401400174422347/) on 2013-09-30T09:57:07Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. Downloaded Python(x,y) and installed it.
2. Tried to open Spyder through the Start menu or through the command line. 3. What is the expected output? What do you see instead? Traceback (most recent call last):
  File "C:\Python27\Scripts\spyder-script.py", line 9, in \<module>
    load_entry_point('spyder==2.2.0', 'console_scripts', 'spyder')()
  File "C:\Python27\lib\site-packages\spyderlib\start_app.py", line 72
    from spyderlib import spyder
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 112,
\>
    from spyderlib.plugins.ipythonconsole import IPythonConsole
  File "C:\Python27\lib\site-packages\spyderlib\plugins\ipythonconsole
 31, in \<module>
    from IPython.frontend.qt.kernelmanager import QtKernelManager
  File "C:\Python27\lib\site-packages\IPython\frontend\qt\kernelmanage
e 9, in \<module>
    from IPython.zmq.kernelmanager import KernelManager, SubSocketChan
  File "C:\Python27\lib\site-packages\IPython\zmq\__init__.py", line 6
ule>
    check_for_zmq('2.1.4')
  File "C:\Python27\lib\site-packages\IPython\zmq\__init__.py", line 5
k_for_zmq
    import zmq
  File "C:\Python27\lib\site-packages\zmq\__init__.py", line 35, in \<m
    _libzmq = ctypes.CDLL(bundled[0], mode=ctypes.RTLD_GLOBAL)
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 127] The specified procedure could not be found What version of the product are you using? On what operating system? I am using whatever version comes with the latest Python(x,y) on Windows XP 64-bit. 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1587_

**Comment by spyder-issues-migrator** [comment]
_From [didier.p...@gmail.com](https://code.google.com/u/109575847378732628493/) on 2013-10-11T08:30:01Z_

Same problem encountered when trying to launch SPYDER with Python(x,y).2.7.5 as well as itself (spyder.exe w/o --light)
The output is exactly the same.

spyder.exe --reset hasn't fix the problem.

Configuration: Windows 32-bit, windows XP SP3

Has this problem been fixed? Any solution ? Missing DLLs for C++ in my MicrosoftWindows installation?

Thanks

**Comment by spyder-issues-migrator** [comment]
_From [Alexandr...@gmail.com](https://code.google.com/u/102359679451340108568/) on 2013-10-21T05:24:50Z_

Same problem with windows 32-bit SP3
Getting the exact same output
Downloading Microsoft Visual C++ 2010 Redistributable Package (x86) has not fixed the issue. 
spyder.exe --reset has not fixed the issue

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-01T15:59:06Z_

I hope you've fixed this problem by now :-)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-01T15:59:15Z_

**Status:** WontFix
