### ISSUE TITLE
Missing dependencies jsonschema >= 3.2.0 : 2.6.0 (NOK)

### ISSUE THREAD

**Issue by santidev10** [spyder-ide/spyder#15888]
### What steps will reproduce the problem?

You have missing dependencies
#Mandatory
jsonschema >= 3.2.0 : 2.6.0 (NOK)

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\santi\Anaconda3\lib\code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 2, in <module>
NameError: name 'etree' is not defined
```

## Versions

* Spyder version: 5.0.3 
* Python version: 3.6.13
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.16.1 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  2.6.0 (NOK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.8.3 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  4.0.1 (OK)
spyder_kernels >=2.0.3;<2.1.0 :  2.0.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.1.1 (OK)
numpy >=1.7                   :  1.12.1 (OK)
pandas >=1.1.1                :  0.24.2 (NOK)
scipy >=0.17.0                :  1.1.0 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @santidev10, thanks for reporting. To fix that problem, please close Spyder, open the Anaconda Prompt and run there

    conda update anaconda
    conda install jsonschema=3.2.0

**Comment by ccordoba12** [comment]
Please do that and let us know if it works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
