### ISSUE TITLE
Spyder update problem

### ISSUE THREAD

**Issue by ModernShrub** [spyder-ide/spyder#15893]
### What steps will reproduce the problem?

update spyder using
conda update anaconda
conda install spyder=5.0.3

### Traceback
```python-traceback
  File "C:\Users\ishan\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1527, in process_completion
    self.in_comment_or_string()):
  File "C:\Users\ishan\anaconda3\lib\site-packages\spyder\plugins\completion\kite\widgets\calltoaction.py", line 106, in handle_processed_completions
  File "C:\Users\ishan\anaconda3\lib\site-packages\spyder\plugins\completion\kite\bloomfilter\__init__.py", line 28, in is_valid_path
  File "C:\Users\ishan\anaconda3\lib\site-packages\spyder\utils\external\pybloom_pyqt\pybloom.py", line 215, in fromfile
    raise ValueError("unable to open file " + path)
ValueError: unable to open file C:\Users\ishan\anaconda3\lib\site-packages\spyder\plugins\completion\kite\bloomfilter\kite.bloom

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ishan\anaconda3\lib\logging\__init__.py", line 1081, in emit
    msg = self.format(record)
  File "C:\Users\ishan\anaconda3\lib\logging\__init__.py", line 925, in format
    return fmt.format(record)
  File "C:\Users\ishan\anaconda3\lib\logging\__init__.py", line 664, in format
    record.message = record.getMessage()
  File "C:\Users\ishan\anaconda3\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "C:\Users\ishan\anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\ishan\anaconda3\lib\site-packages\spyder\app\start.py", line 214, in main
    mainwindow.main(options, args)
  File "C:\Users\ishan\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3646, in main
  File "C:\Users\ishan\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3545, in create_window
  File "C:\Users\ishan\anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 308, in <lambda>
    Update plugin and/or provider configurations.
  File "C:\Users\ishan\anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 138, in receive_timeout
    completion_capabilites: dict
  File "C:\Users\ishan\anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 183, in howto_send_to_codeeditor
    RUNNING = 'running'
  File "C:\Users\ishan\anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 211, in skip_and_send_to_codeeditor
    # Current request sequence identifier
  File "C:\Users\ishan\anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 279, in gather_and_send_to_codeeditor
    provider_info = self.providers[provider_name]
  File "C:\Users\ishan\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1110, in handle_response
    if self.oe_proxy is not None:
  File "C:\Users\ishan\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1534, in process_completion
  File "C:\Users\ishan\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1141, in log_lsp_handle_errors
    self.patch = self.differ.patch_make(self.previous_text, text)
Message: '%'
Arguments: (1,)
```

## Versions

* Spyder version: 4.2.5 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.22.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  4.0.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.23 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.20.1 (OK)
pandas >=1.1.1                  :  1.2.4 (OK)
scipy >=0.17.0                  :  1.6.2 (OK)
sympy >=0.7.3                   :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @ModernShrub, thanks for reporting. Please close Spyder, open the Anaconda Prompt, run there

    spyder --reset

and start Spyder again. That should solve your problem.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
