### ISSUE TITLE
unexplainable error

### ISSUE THREAD

**Issue by kmonar** [spyder-ide/spyder#15910]
### What steps will reproduce the problem?

spyder was just open, i wasn't working on it and the error suddenly appeared !

### Traceback
```python-traceback
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/anaconda3/lib/python3.8/site-packages/watchdog/observers/inotify_buffer.py", line 88, in run
    inotify_events = self._inotify.read_events()
  File "/home/anaconda3/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 369, in read_events
    event_list.extend(_recursive_simulate(src_path))
  File "/home/anaconda3/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 302, in _recursive_simulate
    wd_parent_dir = self._wd_for_path[os.path.dirname(full_path)]
KeyError: b'/home/kmonar/R/x86_64-pc-linux-gnu-library/4.1/00LOCK-gargle/00new/gargle'
```

## Versions

* Spyder version: 5.0.3 
* Python version: 3.8.10
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 4.19.0-16-amd64

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.8.3 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  4.0.1 (OK)
spyder_kernels >=2.0.3;<2.1.0 :  2.0.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.19.5 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.5.4 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by steff456** [comment]
Hi @kmonar,

Did you changed something in Spyder's configuration? Also, if you restart Spyder the problem persists? Lastly, if you encounter the reason and have a series of steps to reproduce this error please post them here for us to try and reproduce it on our end.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
