### ISSUE TITLE
i was not able to import tensorflow

### ISSUE THREAD

**Issue by Aastha0313** [spyder-ide/spyder#15974]
### What steps will reproduce the problem?

  File "C:\anaconda\envs\gputest\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *

  File "C:\anaconda\envs\gputest\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()

  File "C:\anaconda\envs\gputest\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)

  File "C:\anaconda\envs\gputest\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)

  File "C:\anaconda\envs\gputest\lib\imp.py", line 343, in load_dynamic
    return _load(spec)

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-1-64156d691fe5>", line 1, in <module>
    import tensorflow as tf

  File "C:\anaconda\envs\gputest\lib\site-packages\tensorflow\__init__.py", line 27, in <module>
    from tensorflow._api.v2 import audio

  File "C:\anaconda\envs\gputest\lib\site-packages\tensorflow\_api\v2\audio\__init__.py", line 8, in <module>
    from tensorflow.python.ops.gen_audio_ops import decode_wav

  File "C:\anaconda\envs\gputest\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\anaconda\envs\gputest\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\anaconda\envs\gputest\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\anaconda\envs\gputest\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\anaconda\envs\gputest\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\anaconda\envs\gputest\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\anaconda\envs\gputest\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by steff456** [comment]
Hi @Aastha0313,

This seems an error from your installation of tensorflow, please create a new environment and try again. In case you are using conda, please just stick to install everything with conda and not mix it with pip. If this not work, please contact tensorflow for troubleshooting.

Thanks for reporting!
