### ISSUE TITLE
[BUG] PyQt5<5.13, while current is 5.15.4 = Spyder is ruined

### ISSUE THREAD

**Issue by Kochise** [spyder-ide/spyder#15986]
Hi, Spyder 5.0.5 Windows 64 bits

1. Installing Enaml from https://pypi.org/project/enaml/

1. I also add Enamlx from https://pypi.org/project/enamlx/

1. Which requires QScintilla from https://pypi.org/project/QScintilla/

1. It upgrades PyQt5 to lastest version (currently 5.15.4).

At the end of installation, it then indicates a dependency defect : 

``` batch
C:\Program Files\Spyder>"%PYTHONPATH%\python" -m pip install --upgrade QScintilla
Collecting QScintilla
  Using cached QScintilla-2.13.0-cp36.cp37.cp38.cp39-none-win_amd64.whl (1.9 MB)
Collecting PyQt5>=5.15.4
  Using cached PyQt5-5.15.4-cp36.cp37.cp38.cp39-none-win_amd64.whl (6.8 MB)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in c:\program files\spyder\pkgs (from QScintilla) (12.9.0)
Collecting PyQt5-Qt5>=5.15
  Using cached PyQt5_Qt5-5.15.2-py3-none-win_amd64.whl (50.1 MB)
Installing collected packages: PyQt5-Qt5, PyQt5, QScintilla
  Attempting uninstall: PyQt5
    Found existing installation: PyQt5 5.12.3
    Uninstalling PyQt5-5.12.3:
      Successfully uninstalled PyQt5-5.12.3
  WARNING: The scripts pylupdate5.exe, pyrcc5.exe and pyuic5.exe are installed in 'C:\Program Files\Spyder\Python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 5.0.5 requires pyqt5<5.13, but you have pyqt5 5.15.4 which is incompatible.
Successfully installed PyQt5-5.15.4 PyQt5-Qt5-5.15.2 QScintilla-2.13.0

C:\Program Files\Spyder>
```

And indeed, Spyder is then ruined (btw, many modules easily breaks Spyder).

Any reason so far to use outdated component ?

Regards.

**Comment by oscargus** [comment]
It seems like the reason is that the latest version of PyQT5 in baseline Anaconda is 5.9.

I tried to run it from source using 5.15.2 and got the following error:
```
QWidget: Must construct a QApplication before a QWidget
```

There are discussions about this in e.g. https://github.com/spyder-ide/spyder/issues/12829

**Comment by dalthviz** [comment]
Hi @Kochise thank you for the feedback! And yes as @oscargus (thank you for pointing the issue where we are discussing packages creation for Qt 5.15!) there was not much priority until now to update to a recent version since with conda you can just get at most Qt 5.12 via `conda-forge` and when we checked there is some work to do for Spyder to be able to run and make the test suite pass with Qt 5.15. However this is something we will try to work in a future release indeed.

I will close this one but hope the info above makes more clear the state of things :)

**Comment by Kochise** [comment]
Fun, I just read https://www.reddit.com/r/Python/comments/oe2ioc/why_is_python_depency_management_such_a_mess/

The **PyQt5** version installed with **Spyder 5.0.5** is https://pypi.org/project/PyQt5/5.12.3/ which is more than 2 years old.

The **Python** ecosystem really needs a big cleanup.

From https://pypi.org/project/QScintilla/#history I selected https://pypi.org/project/QScintilla/2.12.0/ (2.12.1 breaks **Spyder**)

```batch
C:\Program Files\Spyder\Python>python -m pip install QScintilla==2.12.0
Collecting QScintilla==2.12.0
  Using cached QScintilla-2.12.0-cp36.cp37.cp38.cp39-none-win_amd64.whl (1.9 MB)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in c:\program files\spyder\pkgs (from QScintilla==2.12.0) (12.9.0)
Requirement already satisfied: PyQt5>=5.10.1 in c:\program files\spyder\pkgs (from QScintilla==2.12.0) (5.12.3)
Installing collected packages: QScintilla
Successfully installed QScintilla-2.12.0

C:\Program Files\Spyder\Python>
```

Yet it still doesn't solves the issue as **Spyder** installs into `c:\Program Files\Spyder\pkgs\` and **pip** into `c:\Program Files\Spyder\Python\Lib\site-packages\`

```batch
C:\Program Files\Spyder>enaml-run "c:\Users\dkoch\Downloads\enaml-main\examples\applib\live_editor.enaml"
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Program Files\Spyder\Python\Scripts\enaml-run.exe\__main__.py", line 7, in <module>
  File "c:\program files\spyder\python\lib\site-packages\enaml\runner.py", line 71, in main
    window.show()
  File "c:\program files\spyder\python\lib\site-packages\enaml\widgets\window.py", line 381, in show
    self.initialize()
  File "c:\program files\spyder\python\lib\site-packages\enaml\widgets\window.py", line 159, in initialize
    super(Window, self).initialize()
  File "c:\program files\spyder\python\lib\site-packages\enaml\widgets\toolkit_object.py", line 160, in initialize
    super(ToolkitObject, self).initialize()
  File "c:\program files\spyder\python\lib\site-packages\enaml\core\declarative.py", line 117, in initialize
    child.initialize()
  File "c:\program files\spyder\python\lib\site-packages\enaml\widgets\toolkit_object.py", line 160, in initialize
    super(ToolkitObject, self).initialize()
  File "c:\program files\spyder\python\lib\site-packages\enaml\core\declarative.py", line 117, in initialize
    child.initialize()
  File "c:\program files\spyder\python\lib\site-packages\enaml\widgets\toolkit_object.py", line 160, in initialize
    super(ToolkitObject, self).initialize()
  File "c:\program files\spyder\python\lib\site-packages\enaml\core\declarative.py", line 117, in initialize
    child.initialize()
  File "c:\program files\spyder\python\lib\site-packages\enaml\widgets\toolkit_object.py", line 160, in initialize
    super(ToolkitObject, self).initialize()
  File "c:\program files\spyder\python\lib\site-packages\enaml\core\declarative.py", line 117, in initialize
    child.initialize()
  File "c:\program files\spyder\python\lib\site-packages\enaml\widgets\toolkit_object.py", line 160, in initialize
    super(ToolkitObject, self).initialize()
  File "c:\program files\spyder\python\lib\site-packages\enaml\core\declarative.py", line 117, in initialize
    child.initialize()
  File "c:\program files\spyder\python\lib\site-packages\enaml\widgets\toolkit_object.py", line 159, in initialize
    self.proxy = app.create_proxy(self)
  File "c:\program files\spyder\python\lib\site-packages\enaml\application.py", line 369, in create_proxy
    cls = self.resolve_proxy_class(type(declaration))
  File "c:\program files\spyder\python\lib\site-packages\enaml\application.py", line 347, in resolve_proxy_class
    cls = resolver.resolve(name)
  File "c:\program files\spyder\python\lib\site-packages\enaml\application.py", line 147, in resolve
    return factory()
  File "c:\program files\spyder\python\lib\site-packages\enaml\qt\qt_factories.py", line 219, in scintilla_factory
    from .qt_scintilla import QtScintilla
  File "c:\program files\spyder\python\lib\site-packages\enaml\qt\qt_scintilla.py", line 24, in <module>
    from PyQt5 import Qsci
ImportError: cannot import name 'Qsci' from 'PyQt5' (c:\program files\spyder\pkgs\PyQt5\__init__.py)

C:\Program Files\Spyder>
```

There is no **Qsci** module in the **PyQt5** package bundled with **Spyder**, but in the one installed by **QScintilla** (>=2.12.1).

**Comment by ccordoba12** [comment]
@Kochise, it seems you're using incorrectly our Windows installer. That installer is self-contained and doesn't come pip by default (as you probably noticed), to avoid people messing with it and breaking Spyder.

But, as you also found out, adding pip is not enough because the location of packages is not the regular `site-packages` but `pkgs` (that's defined by `pynsist`, the library we use to build the installer).

So, instead of following that path, please read [our FAQ](https://docs.spyder-ide.org/5/faq.html#using-packages-installer) to understand how to use our installer with packages that don't come with it. That will give you the freedom to use more recent PyQt versions.

**Comment by Kochise** [comment]
Ok, but why adding another way to deal with packages ?

**Comment by ccordoba12** [comment]
Because it's very, very easy to break Spyder by installing other Python packages in the same environment it lives. That's why we decided to create our installers without pip.

In that way, Spyder is similar to Pycharm, VSCode, Sublime, etc. For all of them you need to install a separate Python environment to work with.

**Comment by Kochise** [comment]
Ok then. As I can redirect Spyder to use another Python environment, I'll try to use that path instead, mostly to be sure to use up to date packages.
