### ISSUE TITLE
TypeError when editing complex number in variable explorer

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1599]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2013-10-08T09:07:12Z_

Spyder Version:  2.3.0dev
Python Version:  2.7.4
Qt Version    :  4.8.4, PyQt4 (API v2) 4.10 on Linux
pyflakes >=0.5.0:  0.6.1 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  0.13.2 (OK)
rope >=0.9.2    :  0.9.2 (OK)
sphinx >=0.6.6  :  1.1.3 (OK)
matplotlib >=1.0:  1.2.1 (OK)
sympy >=0.7.0   :  0.7.2 (OK)
pylint >=0.25   :  0.26.0 (OK) 

What steps will reproduce the problem?

 1. Edit a complex number in an numpy array in the variable explorer
2. Validate by clicking outside of the cell What is the expected output? What do you see instead? I get the following error in the internal console :
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/arrayeditor.py", line 234, in setData
    if val > self.vmax:
TypeError: no ordering relation is defined for complex numbers 

Please provide any additional information below

. * As the internal console is focused due to the error, the Variable explorer is empty, I have to reactivate the console tab to see my variables again.

* If I validate by enter instead of clicking outside the cell, I have the previous error plus the following one (spyder even crased once) :
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/arrayeditor.py", line 286, in commitAndCloseEditor
    self.emit(SIGNAL("closeEditor(QWidget*)"), editor)
TypeError: closeEditor(QWidget*).emit(): argument 1 has unexpected type 'QLineEdit'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1599_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-01T15:47:16Z_

I hope this is fixed by now :-)

**Status:** WontFix
