### ISSUE TITLE
Trying to Open the settings Window, TypeError

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1603]
_From [tmgerl...@gmail.com](https://code.google.com/u/115358409314462231801/) on 2013-10-14T09:23:25Z_

Spyder Version:  2.2.4
Python Version:  2.7.5
Qt Version    :  4.8.4, PyQt4 (API v2) 4.9.6 on Windows
pyflakes >=0.5.0:  0.7.3 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  1.1.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2b2 (OK)
matplotlib >=1.0:  1.3.0 (OK)
sympy >=0.7.0   :  None (NOK)
pylint >=0.25   :  1.0.0 (OK) 

What steps will reproduce the problem?

 1. Atemptng to open the settings window 2. 3. What is the expected output? What do you see instead? I try to open the settings window and I get this.

\>>> Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 1841, in edit_preferences
    widget = plugin.create_configwidget(dlg)
  File "C:\Python27\lib\site-packages\spyderlib\plugins\__init__.py", line 179, in create_configwidget
    configwidget.initialize()
  File "C:\Python27\lib\site-packages\spyderlib\plugins\configdialog.py", line 50, in initialize
    self.load_from_conf()
  File "C:\Python27\lib\site-packages\spyderlib\plugins\configdialog.py", line 253, in load_from_conf
    checkbox.setChecked(self.get_option(option, default))
TypeError: QAbstractButton.setChecked(bool): argument 1 has unexpected type 'str' 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1603_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-10-14T18:34:10Z_

It seems your configuration got corrupted. You could try running in a terminal (i.e. cmd.exe):

spyder --reset

and restart it again.

**Comment by spyder-issues-migrator** [comment]
_From [tmgerl...@gmail.com](https://code.google.com/u/115358409314462231801/) on 2013-10-18T06:30:16Z_

This did not work, I get a console error

**Attachment:** [SpyderErr.jpg](http://code.google.com/p/spyderlib/issues/detail?id=1603#hc2)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-01T15:46:16Z_

This is a problem with your installation. Please Anaconda or WinPython instead.

**Status:** WontFix
