### ISSUE TITLE
Crashed when copying approximation function

### ISSUE THREAD

**Issue by twinoh** [spyder-ide/spyder#16047]
### What steps will reproduce the problem?

copying the approximation variable - so that I can see what is happening.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\hossanat\.conda\envs\spyder\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 102, in get_value
    return self.call_kernel(
  File "C:\Users\hossanat\.conda\envs\spyder\lib\site-packages\spyder_kernels\comms\commbase.py", line 554, in __call__
    return self._comms_wrapper._get_call_return_value(
  File "C:\Users\hossanat\.conda\envs\spyder\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 210, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
  File "C:\Users\hossanat\.conda\envs\spyder\lib\site-packages\spyder_kernels\comms\commbase.py", line 437, in _get_call_return_value
    return self._sync_error(reply['value'])
  File "C:\Users\hossanat\.conda\envs\spyder\lib\site-packages\spyder_kernels\comms\commbase.py", line 493, in _sync_error
    error_wrapper.raise_error()
  File "C:\Users\hossanat\.conda\envs\spyder\lib\site-packages\spyder_kernels\comms\commbase.py", line 90, in raise_error
    raise self.etype(self)
AttributeError: 'super' object has no attribute '__getstate__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hossanat\.conda\envs\spyder\lib\site-packages\spyder\plugins\variableexplorer\widgets\main_widget.py", line 636, in copy
    self._current_editor.copy()
  File "C:\Users\hossanat\.conda\envs\spyder\lib\site-packages\spyder\widgets\collectionseditor.py", line 1093, in copy
    obj = self.delegate.get_value(idx)
  File "C:\Users\hossanat\.conda\envs\spyder\lib\site-packages\spyder\widgets\collectionseditor.py", line 1433, in get_value
    return self.parent().get_value(name)
  File "C:\Users\hossanat\.conda\envs\spyder\lib\site-packages\spyder\widgets\collectionseditor.py", line 1491, in get_value
    value = self.shellwidget.get_value(name)
  File "C:\Users\hossanat\.conda\envs\spyder\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 117, in get_value
    raise ValueError(msg % reason_other)
ValueError: An error occured, see the console..<br><br>Note: Please don't report this problem on Github, there's nothing to do about it.
```

## Versions

* Spyder version: 5.0.3 
* Python version: 3.9.2
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.21.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.3.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.3;<2.1.0 :  2.0.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.21.0 (OK)
pandas >=1.1.1                :  1.2.5 (OK)
scipy >=0.17.0                :  1.7.0 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by steff456** [comment]
Hi @twinoh,

Can you please update to Spyder 5.0.5 and let me know if the error persists?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
