### ISSUE TITLE
spyder crashes on startup if cwd is a network-drive

### ISSUE THREAD

**Issue by raphaelquast** [spyder-ide/spyder#16055]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

The most recent version of Spyder crashes on startup if the `spyder` command is executed while a network-drive is selected in the console. (It starts up just fine if a ordinary drive is selected!)

I'm pretty sure this is caused by `pathlib` not being able to `resolve` network-drive names on windows....
This is most probably the same thing as I've encountered before when trying to use `black` code-formatting on network-drives: 
https://github.com/psf/black/issues/2048#issuecomment-800208610

My personal solution back then was to avoid using `Path.resolve` and stick to `Path.absolute` since it seems to be capable of dealing with network-drives just fine... (however I'm unsure if this causes side-effects in other circumstances)

```python
from pathlib import Path
x = Path("\").resolve()
>>> PermissionError

x = Path("\").absolute()
>>> WindowsPath('H:/')    #e.g. the correctly resolved path to the network-drive
```

### What steps reproduce the problem?
1. go with the console to a network-drive (e.g. `cd` to some folder)
2. start spyder by executing `spyder` in the console

### What is the expected output? What do you see instead?
well... the expected output is obvious... I see this:

### Paste Traceback/Error Below (if applicable)

```python-traceback

(spyder_test_env) H:- - - - -\>spyder
Traceback (most recent call last):
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\spyder\app\mainwindow.py", line 2132, in create_window
    main.setup()
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\spyder\app\mainwindow.py", line 835, in setup
    external_plugins = find_external_plugins()
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\spyder\app\solver.py", line 105, in find_external_plugins
    internal_plugins = find_internal_plugins()
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\spyder\app\solver.py", line 94, in find_internal_plugins
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\spyder\plugins\pylint\__init__.py", line 14, in <module>
    from spyder.plugins.pylint.plugin import Pylint
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\spyder\plugins\pylint\__init__.py", line 14, in <module>
    from spyder.plugins.pylint.plugin import Pylint
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\spyder\plugins\pylint\plugin.py", line 22, in <module>
    from spyder.plugins.pylint.confpage import PylintConfigPage
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\spyder\plugins\pylint\confpage.py", line 16, in <module>
    from spyder.plugins.pylint.main_widget import (MAX_HISTORY_ENTRIES,
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\spyder\plugins\pylint\main_widget.py", line 35, in <module>
    from spyder.plugins.pylint.utils import get_pylintrc_path
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\spyder\plugins\pylint\utils.py", line 16, in <module>
    import pylint.config
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\pylint\config\__init__.py", line 38, in <module>
    from pylint.config.configuration_mixin import ConfigurationMixIn
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\pylint\config\configuration_mixin.py", line 4, in <module>
    from pylint.config.option_manager_mixin import OptionsManagerMixIn
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\pylint\config\option_manager_mixin.py", line 16, in <module>
    from pylint import utils
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\pylint\utils\__init__.py", line 47, in <module>
    from pylint.utils.utils import (
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\pylint\utils\utils.py", line 6, in <module>
    import isort.api
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\isort\__init__.py", line 21, in <module>
    from . import settings
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\isort\settings.py", line 874, in <module>
    DEFAULT_CONFIG = Config()
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\isort\settings.py", line 447, in __init__
    path_root = Path(combined_config.get("directory", project_root)).resolve()
  File "- - - - -\Miniconda3\envs\rt1\lib\pathlib.py", line 1166, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "- - - - -\Miniconda3\envs\rt1\lib\pathlib.py", line 205, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
PermissionError: [WinError 5] Access is denied: 'H:- - - - -\'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "- - - - -\Miniconda3\envs\rt1\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\spyder\app\start.py", line 227, in main
    mainwindow.main(options, args)
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\spyder\app\mainwindow.py", line 2282, in main
    mainwindow = create_window(app, splash, options, args)
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\spyder\app\mainwindow.py", line 2134, in create_window
    if main.console is not None:
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\spyder\app\mainwindow.py", line 1156, in __getattr__
    return self.get_plugin(self._INTERNAL_PLUGINS_MAPPING[attr])
  File "- - - - -\Miniconda3\envs\rt1\lib\site-packages\spyder\app\mainwindow.py", line 170, in get_plugin
    'Plugin "{}" not found!'.format(plugin_name))
spyder.api.exceptions.SpyderAPIError: Plugin "internal_console" not found!

```

## Versions

* Spyder version: 5.0.5
* Python version: 3.7.10
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: Windows 10 Enterprise LTSC

**Comment by dalthviz** [comment]
Hi @raphaelquast thanks for the feedback! Checking the traceback seems like this issues is triggered at some point when loading the code analysis plugin. Seems related with the handling done by `pylint` and `isort` to read the their config? What do you think @ccordoba12 ?

**Comment by dalthviz** [comment]
Closing due to lack of response. If the error happens again with the most recent Spyder version available, please open a new issue and add a reference to this one there, thanks!
