### ISSUE TITLE
Autosave error.

### ISSUE THREAD

**Issue by jwilliams876** [spyder-ide/spyder#16104]
### What steps will reproduce the problem?

hitting "ctrl + s" resulted in an autosave error.

### Traceback
```python-traceback
Error while removing autosave file /Users/jwilliams/.spyder-py3/autosave/py_BidirectionalSearchSlice.py
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/editor/utils/autosave.py", line 311, in remove_autosave_file
    os.remove(autosave_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jwilliams/.spyder-py3/autosave/py_BidirectionalSearchSlice.py'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/editor/widgets/editor.py", line 1836, in save
    self._save_file(finfo, index)
  File "/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/editor/widgets/editor.py", line 1854, in _save_file
    self.autosave.remove_autosave_file(finfo.filename)
  File "/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/editor/utils/autosave.py", line 318, in remove_autosave_file
    del self.file_hashes[autosave_filename]
KeyError: '/Users/jwilliams/.spyder-py3/autosave/py_BidirectionalSearchSlice.py'
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.8.1
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Darwin 20.3.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.3.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.20.1 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @jwilliams876, thanks for reporting. This problem could be fixed in our latest version. Please update by closing Spyder, opening the Anaconda Prompt and running there

    conda update anaconda
    conda install spyder=5.0.5

Let us know if it works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
