### ISSUE TITLE
Error when accepting suggested autocomplete 10000 / 2

### ISSUE THREAD

**Issue by AaronBiddle** [spyder-ide/spyder#16147]
### What steps will reproduce the problem?

import numpy as np
import matplotlib.pyplot as plt

N = 10000

a box shows up suggesting 10000 / 2. Error message if I accept.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "D:\Programs\anaconda3\lib\site-packages\spyder\plugins\editor\extensions\snippets.py", line 817, in insert_snippet
    ast = build_snippet_ast(text)
  File "D:\Programs\anaconda3\lib\site-packages\spyder\utils\snippets\ast.py", line 151, in build_snippet_ast
    raise SyntaxError('Syntax Error: Expected any of the following'
SyntaxError: Syntax Error: Expected any of the following characters: ['dollar', 'name', 'int', 'case', '\\:', '\\$', 'text_pipe', '{', '\\}', '\\', '\\/', '\\,', 'symbol', 'whitespace', 'left_curly_name', ':', ':+', ':-', ':?', ',', '}', '<eof>'], got <slash, />
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.9.5 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.0 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @AaronBiddle, thanks for reporting. We'll fix this problem in our next version (5.1.1), to be released shortly.

**Comment by ccordoba12** [comment]
@AaronBiddle, I'm unable to reproduce this error. Could you upload a screenshot or animated showing us how to generate the error.

You can generate the gif with the [Licecap](https://www.cockos.com/licecap/) program.

**Comment by AaronBiddle** [comment]
The problem only occurs after importing numpy and matplotlib.pyplot, but after repeating a few times I found the problem to be intermittent. However if I don't include both libraries it never happens.
![Capture](https://user-images.githubusercontent.com/8095591/128269706-d6617b1f-02d1-4fa1-b4cf-0b32ffd6f25d.gif)

**Comment by AaronBiddle** [comment]
After further testing, it seemed essential that line 1, line 2, line 3, and line 4 be exactly as above. If I have any comments or add or remove any blank lines the suggestion of 10000 / 2 will not show up. I'm not sure how these suggestions are populated. I'll include another video demonstrating this.

In this video I:
  1. Demonstrate 10000 / 2 isn't suggested
  2.  Add a blank line
  3. Demonstrate 10000 / 2 is suggested
  4.  Remove blank line
  5.  Demonstrate 10000 / 2 isn't suggested
  6.  Add a blank line
  7. Demonstrate 10000 / 2 is suggested
![Capture](https://user-images.githubusercontent.com/8095591/128350834-eed3160e-cdd2-4449-aeb3-f85b5ad99ae4.gif)

**Comment by AaronBiddle** [comment]
So I learned that the problem is when a slash is remembered as a suggestion, it's easy to reproduce:
![Capture](https://user-images.githubusercontent.com/8095591/128402338-c8c5dfc5-ebb3-466f-acfb-a6749be9f6d2.gif)
