### ISSUE TITLE
Matplotlib

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1620]
_From [kinemagi...@gmail.com](https://code.google.com/u/111544534042776656573/) on 2013-10-26T14:46:38Z_

I am trying to run the the folowing example taken from https://klassenresearch.orbs.com/Plotting+with+Python What is the expected output? 

What do you see instead?

\>>> runfile('D:/ettore/SRS/pythonprogs/test_plot.py', wdir=r'D:/ettore/SRS/pythonprogs')
Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
  File "D:\Program Files\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 538, in runfile
    execfile(filename, namespace)
  File "D:/ettore/SRS/pythonprogs/test_plot.py", line 5, in \<module>
    import matplotlib.pyplot as plt
  File "D:\Program Files\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\site-packages\matplotlib\pyplot.py", line 24, in \<module>
    import matplotlib.colorbar
  File "D:\Program Files\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\site-packages\matplotlib\colorbar.py", line 29, in \<module>
    import matplotlib.collections as collections
  File "D:\Program Files\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\site-packages\matplotlib\collections.py", line 23, in \<module>
    import matplotlib.backend_bases as backend_bases
  File "D:\Program Files\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\site-packages\matplotlib\backend_bases.py", line 50, in \<module>
    import matplotlib.textpath as textpath
  File "D:\Program Files\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\site-packages\matplotlib\textpath.py", line 11, in \<module>
    import matplotlib.font_manager as font_manager
  File "D:\Program Files\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\site-packages\matplotlib\font_manager.py", line 1356, in \<module>
    _rebuild()
  File "D:\Program Files\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\site-packages\matplotlib\font_manager.py", line 1341, in _rebuild
    fontManager = FontManager()
  File "D:\Program Files\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\site-packages\matplotlib\font_manager.py", line 1004, in __init__
    self.ttflist = createFontList(self.ttffiles)
  File "D:\Program Files\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\site-packages\matplotlib\font_manager.py", line 584, in createFontList
    prop = ttfFontProperty(font)
  File "D:\Program Files\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\site-packages\matplotlib\font_manager.py", line 398, in ttfFontProperty
    sfnt4 = sfnt4.decode('ascii').lower()
UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 0: ordinal not in range(128)
\>>> 

What version of the product are you using? 
spyder 2.2.3  winpython 2.7.5.3 64bit 
On what operating system?
windows 7 Professional

**Attachment:** [test_plot.py](http://code.google.com/p/spyderlib/issues/detail?id=1620)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1620_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-10-27T10:10:07Z_

Unfortunately this is an error with WinPython, not with Spyder, and I don't know how to fix it. You have to report it with them here https://code.google.com/p/winpython/issues/list

**Status:** Invalid
