### ISSUE TITLE
Cannot run any thing

### ISSUE THREAD

**Issue by saeedehabbasi** [spyder-ide/spyder#16204]
### What steps will reproduce the problem?

Tried to run the first file after upgrading to Spyder 5. It does not let me do any thing

### Traceback
```python-traceback

QCssParser::parseHexColor: Unknown color name '#00000'
QCssParser::parseHexColor: Unknown color name '#00000'
QCssParser::parseHexColor: Unknown color name '#00000'
QCssParser::parseHexColor: Unknown color name '#00000'
QCssParser::parseHexColor: Unknown color name '#00000'
Traceback (most recent call last):
  File "C:\Users\10302564\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\plugin.py", line 797, in run_script
    self.create_client_for_file(filename, is_cython=is_cython)
  File "C:\Users\10302564\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\plugin.py", line 1463, in create_client_for_file
    self.create_new_client(filename=filename, is_cython=is_cython)
  File "C:\Users\10302564\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\plugin.py", line 1036, in create_new_client
    css_path=self.css_path)
  File "C:\Users\10302564\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\client.py", line 144, in __init__
    local_kernel=True)
  File "C:\Users\10302564\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\shell.py", line 89, in __init__
    super(ShellWidget, self).__init__(*args, **kw)
  File "C:\Users\10302564\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\debugging.py", line 197, in __init__
    super(DebuggingWidget, self).__init__(*args, **kwargs)
  File "C:\Users\10302564\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\debugging.py", line 74, in __init__
    super(DebuggingHistoryWidget, self).__init__(*args, **kwargs)
  File "C:\Users\10302564\AppData\Local\Programs\Spyder\pkgs\qtconsole\rich_jupyter_widget.py", line 53, in __init__
    super().__init__(*args, **kw)
  File "C:\Users\10302564\AppData\Local\Programs\Spyder\pkgs\qtconsole\jupyter_widget.py", line 132, in __init__
    self._syntax_style_changed()
  File "C:\Users\10302564\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\shell.py", line 993, in _syntax_style_changed
    self._highlighter._style = create_style_class(self.syntax_style)
  File "C:\Users\10302564\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\utils\style.py", line 171, in create_style_class
    class StyleClass(Style):
  File "C:\Users\10302564\AppData\Local\Programs\Spyder\pkgs\pygments\style.py", line 122, in __new__
    ndef[0] = colorformat(styledef)
  File "C:\Users\10302564\AppData\Local\Programs\Spyder\pkgs\pygments\style.py", line 79, in colorformat
    assert False, "wrong color format %r" % text
AssertionError: wrong color format '#00000'
Exception ignored in: <function ShellWidget.__del__ at 0x000001EA7E2BFCA8>
Traceback (most recent call last):
  File "C:\Users\10302564\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\shell.py", line 139, in __del__
    if (self.shutdown_thread is not None
AttributeError: 'ShellWidget' object has no attribute 'shutdown_thread'
```

## Versions

* Spyder version: 5.1.1 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.26.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=2.5.0                :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.1;<1.3.0          :  1.2.1 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  57.4.0 (OK)
sphinx >=0.6.6                :  4.1.2 (OK)
spyder_kernels >=2.1.0;<2.2.0 :  2.1.0 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.3 (OK)
zmq >=17                      :  22.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.3.1 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by dalthviz** [comment]
Hi @saeedehabbasi sorry to hear that seems like you are having some issues with the syntax highlighting settings. Could you try to do a settings reset or change the invalid color `#00000` for a valid one like `#000000` and check again? Let us know if that helps :)

**Comment by dalthviz** [comment]
Closing due to lack of response
