### ISSUE TITLE
strange behavior with cell

### ISSUE THREAD

**Issue by sylvain-bougnoux** [spyder-ide/spyder#16201]
It might be an ipython issue or something... but for me it is highly puzzling.

## Problem Description

Here is a reproducible example

```
from math import sqrt

# %% 
# run this cell before the file, it will normally crashed (lack of sqrt)
# then run whole file
# then call in ipython console: foo2(); print(x)
# x is still 1 !!!

def foo1():
  global x
  x=sqrt(1)

def foo2():
  global x
  x=sqrt(4)

foo1()
```

### What steps reproduce the problem?

1. run the cell 1st, will normally crash
2. run the file
3. call in the console: foo2()
4. print(x)

### What is the expected output? What do you see instead?

'x' should be 2, while 'x' is still 1

if one reruns the cell, then now it is fine.
It is like there are different namespaces or globals for cells ???
It is weird and sources of crazy bugs. Thanks.
I guess I've default settings in 'run' & 'python interpreter'.

## Versions

* Spyder version: 6.0.0.dev0 48b930506
* Python version: 3.8.9 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.4
* Operating System: Windows 10

**Comment by dalthviz** [comment]
Hi @sylvain-bougnoux thank you for the feedback! I was able to reproduce this behavior. I'm not totally sure why it happens but yes maybe is related with the handling of the namespace when running by cells vs by file. Pinging @spyder-ide/core-developers since maybe some one could have a better idea of what's going on here (either if is intentional or there is a related run setting that could help here).

**Comment by dalthviz** [comment]
Thanks @mrclary for checking this! I think now I have a more clear view of whats going on and hopefully @sylvain-bougnoux could understand better the current options available for a more consistent code execution. Should we move this to `spyder-kernels` @ccordoba12 ?

**Comment by sylvain-bougnoux** [comment]
Thanks for these observations & your interest. Yes checking option 2 in 'run' does the job. But I am wondering what the opposite (option 2 not checked) means for cells?

My naive understanding of running a cell is: just populate/update the console namespace with the content of the cell; while a file could be seen as a list of cells (with different inputs or knowledge depending on the run option above). If it does something else, it should be stated clearly I guess.

IMHO, there is still a bug when option 2 is unchecked. I've found out **that even running the file to start with** (instead of the cell first) leads to the same problem ; and removing the cell ie '# %%' does not help. It might be due to declaring the variable x from the functions and not from the global namespace ???

But indeed, checking option 2, solves all these experiments, which is even weirder when starting from scratch (because the console is empty anyway!).

Thanks.

**Comment by mrclary** [comment]
> Thanks for these observations & your interest. Yes checking option 2 in 'run' does the job. But I am wondering what the opposite (option 2 not checked) means for cells?

The run options have no affect on cells; as I confirmed above, the `runcell` command is always executed with `current_console=True`.

> My naive understanding of running a cell is: just populate/update the console namespace with the content of the cell; while a file could be seen as a list of cells (with different inputs or knowledge depending on the run option above). If it does something else, it should be stated clearly I guess.

This is correct. It does not do something else.

> IMHO, there is still a bug when option 2 is unchecked.

I agree. As I stated above, I think the issue is with the `NamespaceManager` context. With option 2 deselected, one expects the file to run in an empty namespace, but clearly the global `x` in your MWE is still interfering with the variable in the console namespace.

**Comment by ccordoba12** [comment]
@impact27, could you take a look at this issue? Thanks!

**Comment by impact27** [comment]
So what happens is that when we run a file without the "Run in console's namespace instead of an empty one"  option, a new namespace is created when `foo2` is created. This means that when you run the file, `foo2.__globals__` is set to the new namespace we created. When the execution is finished, this new namespace is merged with the console namespace and discarded. When you call `foo2()` from the console, you will change the 'global' `x` from when the function was created. 
You can check with:

 1- Run the file
 2- in ipython console: `foo2()`
 3- Check the value of `foo2.__globals__['x']` (2) and `globals()['x']` (1)

**Comment by impact27** [comment]
I am not sure how to solve this one. We could change the default to be "run in the console namespace" but this could lead to issues (there is a reason this is not the default). Any code that captures the global namespace will lead to this kind of issues.

**Comment by impact27** [comment]
Also according to https://docs.python.org/3/reference/datamodel.html `__globals__` is read only so this can't be solved by updating `__globals__` for all defined functions

**Comment by mrclary** [comment]
> Also according to https://docs.python.org/3/reference/datamodel.html `__globals__` is read only so this can't be solved by updating `__globals__` for all defined functions:
> 
> ```
> foo2.__globals__ = globals()
> Traceback (most recent call last):
> 
>   File "<ipython-input-11-6051bf8a3705>", line 1, in <module>
>     foo2.__globals__ = globals()
> 
> AttributeError: readonly attribute
> ```

I see that in `foo2.__globals__` and `globals()`, `x: 2.0`. So where is `x: 1.0` coming from? 
Also, we can't _assign_ `__globals__` but we can _update_ it: `foo2.__globals__.update(globals())`.

**Comment by impact27** [comment]
> I see that in `foo2.__globals__` and `globals()`, `x: 2.0`. So where is `x: 1.0` coming from?

That is strange. `print(globals()['x'])` and `print(x)` should be equivalent. So you have `x == 1` and `globals()['x'] == 2`???

> Also, we can't _assign_ `__globals__` but we can _update_ it: `foo2.__globals__.update(globals())`.

That is a good point! maybe we can do something with this.

**Comment by impact27** [comment]
> That is a good point! maybe we can do something with this.

Wait actually the problem is that `get_ipython().user_ns.update(ns_globals)` needs to be called every time `foo2.__globals__` is modified. Updating doesn't help, we need to replace it so that `id(globals()) == id(foo2.__globals__)`.

**Comment by mrclary** [comment]
> > I see that in `foo2.__globals__` and `globals()`, `x: 2.0`. So where is `x: 1.0` coming from?
> 
> That is strange. `print(globals()['x'])` and `print(x)` should be equivalent. So you have `x == 1` and `globals()['x'] == 2`???

Sorry, I was mistaken. Both `foo2.__globals__['x']` and `globals()['x']` are 1.0

**Comment by impact27** [comment]
> Sorry, I was mistaken. Both `foo2.__globals__['x']` and `globals()['x']` are 1.0

Even after calling `foo2()` in the console?

**Comment by impact27** [comment]
The only way I can think of for this to run as expected is to use the same dictionary as a global namespace when running scripts.

I see two solutions:
 1- Disable the option of running in a new namespace. This means that running the same script twice might lead to different outcomes.
 2- Use the same namespace but empty the namespace before running a script, and put back the variables when running is over.

**Comment by impact27** [comment]
By the way, this is the same behaviour as IPython's `%run`:

Save a file containing:
```
x = 1
def f():
    print(x)
```
From a terminal, launch IPython:
```
Python 3.8.6 (default, Oct  8 2020, 14:06:32) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.22.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %run tmp.py

In [2]: f()
1

In [3]: x = 2

In [4]: f()
1

In [5]: globals()['x']
Out[5]: 2

In [6]: f.__globals__['x']
Out[6]: 1
```

**Comment by mrclary** [comment]
> > Sorry, I was mistaken. Both `foo2.__globals__['x']` and `globals()['x']` are 1.0
> 
> Even after calling `foo2()` in the console?

Aarggh! I was careless; after calling `foo2()`, `foo2.__globals__['x'] == 2.0` and `globals()['x'] == 1.0` and `x == 1.0`.

**Comment by mrclary** [comment]
Okay, this is strange. Starting from a freshly launched Spyder, executing the OP script, "Run in console namespace" deselected...

<img width="592" alt="Screen Shot 2021-08-17 at 7 25 31 AM" src="https://user-images.githubusercontent.com/9618975/129744311-d4c1a6f2-5f02-4a53-9db2-3db03305d887.png">

**Comment by impact27** [comment]
> Okay, this is strange. Starting from a freshly launched Spyder, executing the OP script, "Run in console namespace" deselected...

This is the expected behaviour. `x` is really a short way of writing `globals()['x']`. Because `foo2.__globals__ is not globals()`, when `foo2` is called, another dictionary is updated.

**Comment by impact27** [comment]
In https://github.com/spyder-ide/spyder-kernels/pull/308 I reuse the same dictionnary to solve this issue.

**Comment by mrclary** [comment]
Okay, I suppose I'm confused now.
What _exactly_ is the purpose and expected behavior of `runcell`, and `runfile`, with the different states of "Run in console's namespace instead of an empty one"?

1. IPython `%run`: 
    ```python
    In [1]: run test.py

    In [2]: x
    Out[2]: 1.0

    In [3]: foo2()

    In [4]: foo2.__globals__['x']
    Out[4]: 2.0

    In [5] foo1.__globals__['x']
    Out[5]: 2.0

    In [6]: globals()['x']
    Out[6]: 1.0
    ```
2. Pasting code into IPython:
    ```python
    In [1]: from math import sqrt

    In [2]: def foo1():
       ...:     global x
       ...:     x=sqrt(1)
       ...:
       ...: def foo2():
       ...:     global x
       ...:     x=sqrt(4)
       ...:
       ...: foo1()

    In [3]: x
    Out[3]: 1.0

    In [4]: foo2()

    In [5]: foo2.__globals__['x']
    Out[5]: 2.0

    In [6] foo1.__globals__['x']
    Out[6]: 2.0

    In [7]: globals()['x']
    Out[7]: 2.0
    ```
3. `runfile` with "Run in console's namespace instead of an empty one" deselected:
    ```python
    In [1]: runfile('/Users/rclary/Desktop/test.py', wdir='/Users/rclary/Desktop')
    Reloaded modules: spyder, spyder.config, spyder.py3compat, spyder.utils

    In [2]: x
    Out[2]: 1.0

    In [3]: foo2()

    In [4]: foo2.__globals__['x']
    Out[4]: 2.0

    In [5]: foo1.__globals__['x']
    Out[5]: 2.0

    In [6]: globals()['x']
    Out[6]: 1.0
    ```
4. `runfile` with "Run in console's namespace instead of an empty one" selected:
    ```python
    In [1]: runfile('/Users/rclary/Desktop/test.py', wdir='/Users/rclary/Desktop')
    Reloaded modules: spyder, spyder.config, spyder.py3compat, spyder.utils

    In [2]: x
    Out[2]: 1.0

    In [3]: foo2()

    In [4]: foo2.__globals__['x']
    Out[4]: 2.0

    In [5]: foo1.__globals__['x']
    Out[5]: 2.0

    In [6]: globals()['x']
    Out[6]: 1.0
    ```
5. `runcell` on cell 1, then `runfile` with "Run in console's namespace instead of an empty one" deselected:
    ```python
    In [1]: runcell(1, '/Users/rclary/Desktop/test.py')
    Traceback (most recent call last):

      File "/Users/rclary/Desktop/test.py", line 17, in <module>
        foo1()

      File "/Users/rclary/Desktop/test.py", line 11, in foo1
        x=sqrt(1)

    NameError: name 'sqrt' is not defined


    In [2]: runfile('/Users/rclary/Desktop/test.py', wdir='/Users/rclary/Desktop')
    Reloaded modules: spyder, spyder.config, spyder.py3compat, spyder.utils

    In [3]: x
    Out[3]: 1.0

    In [4]: foo2()

    In [5]: foo2.__globals__['x']
    Out[5]: 2.0

    In [6]: foo1.__globals__['x']
    Out[6]: 2.0

    In [7]: globals()['x']
    Out[7]: 1.0
    ```
6. `runcell` on cell 1, then `runfile` with "Run in console's namespace instead of an empty one" selected:
    ```python
    In [1]: runcell(1, '/Users/rclary/Desktop/test.py')
    Traceback (most recent call last):

      File "/Users/rclary/Desktop/test.py", line 17, in <module>
        foo1()

      File "/Users/rclary/Desktop/test.py", line 11, in foo1
        x=sqrt(1)

    NameError: name 'sqrt' is not defined


    In [2]: runfile('/Users/rclary/Desktop/test.py', wdir='/Users/rclary/Desktop')
    Reloaded modules: spyder, spyder.config, spyder.py3compat, spyder.utils

    In [3]: x
    Out[3]: 1.0

    In [4]: foo2()

    In [5]: foo2.__globals__['x']
    Out[5]: 2.0

    In [6]: foo1.__globals__['x']
    Out[6]: 2.0

    In [7]: globals()['x']
    Out[7]: 1.0
    ```

Notice that all scenarios produce the same results _except_ 2 (pasting code), and I could not reproduce the results in my comment [above](https://github.com/spyder-ide/spyder/issues/16201#issuecomment-897281554).

**Comment by impact27** [comment]
@mrclary it looks like for some reason "Run in console's namespace instead of an empty one" is never selected in you examples. This bug is triggered when running a file in a new namespace.

**Comment by impact27** [comment]
Maybe we could simply add a warning when someone runs code in an empty namespace that contains "global"

**Comment by ccordoba12** [comment]
Yeah! I like that idea.
