### ISSUE TITLE
Saving opens up the bug report

### ISSUE THREAD

**Issue by sgbaird** [spyder-ide/spyder#16252]
### What steps will reproduce the problem?

Literally I just pressed Ctrl+s to save, and it's been bringing up this dialogue. Hopefully if I exit out and reopen Spyder it will go away. I don't notice anything particularly concerning happening..

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1904, in _save_file
    self.modification_changed(index=index)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2360, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.7.11
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  57.4.0 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.21.1 (OK)
pandas >=1.1.1                :  1.3.1 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @sgbaird, thanks for reporting. Could you upload a screenshot of your current Spyder layout?

**Comment by sgbaird** [comment]
I had since changed it back to what I use normally, but I'm pretty sure it was in a horizontal split at the time:
![image](https://user-images.githubusercontent.com/45469701/130400675-f8771387-9a44-49b6-bd49-6c9e20a8b3c6.png)

**Comment by ccordoba12** [comment]
That's what I was thinking. Could you try to find a simple way to reproduce the error? It'd be really valuable because that way we could trigger it in our side and then fix it.

**Comment by ccordoba12** [comment]
I tried to reproduce this in a lot of but (unfortunately) I couldn't do it.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by sgbaird** [comment]
It's been pretty sporadic - I haven't noticed any consistent way to cause the error. I'll try to update the issue if I figure out a sort of MWE (fine with it being closed until then). For now, I've just been restarting or "ignoring errors during this session", since it seems to still be saving, thankfully.

**Comment by ccordoba12** [comment]
Thanks for your help @sgbaird.
