### ISSUE TITLE
An error occurred while starting the IPython kernel

### ISSUE THREAD

**Issue by FuDong623** [spyder-ide/spyder#16267]
### What steps will reproduce the problem?

Traceback (most recent call last):
File "d:\programdata\anaconda3\envs\torch\lib\runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "d:\programdata\anaconda3\envs\torch\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "d:\programdata\anaconda3\envs\torch\lib\site‑packages\spyder_kernels\console\__main__.py", line 23, in 
start.main()
File "d:\programdata\anaconda3\envs\torch\lib\site‑packages\spyder_kernels\console\start.py", line 284, in main
kernel.initialize()
File "d:\programdata\anaconda3\envs\torch\lib\site‑packages\traitlets\config\application.py", line 87, in inner
return method(app, *args, **kwargs)
File "d:\programdata\anaconda3\envs\torch\lib\site‑packages\ipykernel\kernelapp.py", line 622, in initialize
self.init_sockets()
File "d:\programdata\anaconda3\envs\torch\lib\site‑packages\ipykernel\kernelapp.py", line 275, in init_sockets
self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
File "d:\programdata\anaconda3\envs\torch\lib\site‑packages\ipykernel\kernelapp.py", line 222, in _bind_socket
return self._try_bind_socket(s, port)
File "d:\programdata\anaconda3\envs\torch\lib\site‑packages\ipykernel\kernelapp.py", line 198, in _try_bind_socket
s.bind("tcp://%s:%i" % (self.ip, port))
File "d:\programdata\anaconda3\envs\torch\lib\site‑packages\zmq\sugar\socket.py", line 208, in bind
super().bind(addr)
File "zmq\backend\cython\socket.pyx", line 540, in zmq.backend.cython.socket.Socket.bind
File "zmq\backend\cython\checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address in use

### Traceback
```python-traceback
  File "d:\programdata\anaconda3\envs\torch\lib\site-packages\qtconsole\manager.py", line 27, in poll
    super().poll()
  File "d:\programdata\anaconda3\envs\torch\lib\site-packages\jupyter_client\restarter.py", line 127, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "d:\programdata\anaconda3\envs\torch\lib\site-packages\jupyter_client\utils.py", line 25, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))
  File "d:\programdata\anaconda3\envs\torch\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "d:\programdata\anaconda3\envs\torch\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "d:\programdata\anaconda3\envs\torch\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "d:\programdata\anaconda3\envs\torch\lib\site-packages\jupyter_client\manager.py", line 477, in _async_restart_kernel
    await ensure_async(self.shutdown_kernel(now=now, restart=True))
  File "d:\programdata\anaconda3\envs\torch\lib\site-packages\jupyter_client\utils.py", line 25, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))
  File "d:\programdata\anaconda3\envs\torch\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "d:\programdata\anaconda3\envs\torch\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "d:\programdata\anaconda3\envs\torch\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "d:\programdata\anaconda3\envs\torch\lib\site-packages\jupyter_client\manager.py", line 436, in _async_shutdown_kernel
    await ensure_async(self._kill_kernel())
  File "d:\programdata\anaconda3\envs\torch\lib\site-packages\spyder\plugins\ipythonconsole\utils\manager.py", line 92, in _kill_kernel
    self.kill_proc_tree(self.kernel.pid)
AttributeError: 'SpyderKernelManager' object has no attribute 'kernel'
WARNING:traitlets:kernel died: 25.000105381011963
WARNING:traitlets:kernel died: 25.000089168548584
WARNING:traitlets:kernel died: 25.009846448898315
```

## Versions

* Spyder version: 4.2.5 
* Python version: 3.8.11
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.26.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  23.1.0 (OK)
nbconvert >=4.0                 :  6.1.0 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.10.0 (OK)
pylint >=1.0                    :  2.10.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.7 (OK)
pyls_spyder >=0.3.2             :  0.4.0 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.3 (OK)
qtconsole >=5.0.3               :  5.1.1 (OK)
qtpy >=1.5.0                    :  1.10.0 (OK)
rtree >=0.8.3                   :  None (NOK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  4.1.2 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.3 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  22.2.1 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.4.3 (OK)
numpy >=1.7                     :  1.21.2 (OK)
pandas >=1.1.1                  :  1.3.2 (OK)
scipy >=0.17.0                  :  None (NOK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by steff456** [comment]
Hi @Fu623,

Can you please update to Spyder 5 in a new environment and let me know if the error persists?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
