### ISSUE TITLE
Image._getdecoder crash on Ubuntu 13.04 and imread from pylab or scipy

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1626]
_From [sven.wan...@gmail.com](https://code.google.com/u/102560106358319923856/) on 2013-10-30T11:16:13Z_

Spyder Version:  2.1.13.1
Python Version:  2.7.4
Qt Version:      4.8.4, PyQt4 (API v2) 4.10 on Linux 

What steps will reproduce the problem?

 1.from pylab import imread or from scipy.misc import imread
2.im = imread(f) What is the expected output? What do you see instead? expected: loading image file to ndarray
I see instead: a crash with -> d = Image._getdecoder(self.mode, d, a, self.decoderconfig)
AttributeError: 'module' object has no attribute '_getdecoder' 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1626_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-11-03T06:57:03Z_

Are you able to run this code outside Spyder without problems? I say it because I don't see how Spyder could be involved in this kind of error.

**Comment by spyder-issues-migrator** [comment]
_From [sven.wan...@gmail.com](https://code.google.com/u/102560106358319923856/) on 2013-11-03T07:02:40Z_

Yes, same code runs without problems when executed in the shell or in IPthon/Dreampy

**Comment by spyder-issues-migrator** [comment]
_From [sven.wan...@gmail.com](https://code.google.com/u/102560106358319923856/) on 2013-11-03T07:06:05Z_

Sorry, imshow causes the crash, not imread

**Comment by spyder-issues-migrator** [comment]
_From [sven.wan...@gmail.com](https://code.google.com/u/102560106358319923856/) on 2013-11-03T07:07:01Z_

Traceback (most recent call last):
  File "/home/xxx/Desktop/test.py", line 11, in \<module>
    imshow(im)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.13.0-py2.7-linux-x86_64.egg/scipy/misc/pilutil.py", line 366, in imshow
    im = toimage(arr)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.13.0-py2.7-linux-x86_64.egg/scipy/misc/pilutil.py", line 228, in toimage
    raise ValueError("'arr' does not have a suitable array shape for any mode.")
ValueError: 'arr' does not have a suitable array shape for any mode.

**Comment by spyder-issues-migrator** [comment]
_From [bvand...@gmail.com](https://code.google.com/u/106274571626189536092/) on 2014-02-12T17:23:49Z_

I have the same problem as well, except it crashes on plt.imread().  

 d = Image._getdecoder(self.mode, d, a, self.decoderconfig)
AttributeError: 'module' object has no attribute '_getdecoder'

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-01T15:40:58Z_

I think this one was fixed a long time ago :-) Please open a new bug if that's not the case.

**Status:** WontFix
