### ISSUE TITLE
data analysis parallisation problem

### ISSUE THREAD

**Issue by JeanPierreLeDouche** [spyder-ide/spyder#16270]
## Description

#16269 What steps will reproduce the problem?

### The code giving the issue is fairly short, using executor.map or pool.map gives the same issue: 

start = Time.perf_counter()
#with concurrent.futures.ProcessPoolExecutor() as executor:
#results = executor.map(ZC_raw, versions)
pool = mp.Pool(mp.cpu_count())
results = pool.map(ZC_raw, versions)
pool.close()
pool.join()

stop = Time.perf_counter()

print(f'Running ZC_raw function took {round(stop-start,2)} seconds')

### Traceback
```python-traceback
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 444, in _run_callback
    callback(*args, **kwargs)
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/jupyter_client/threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/jupyter_client/session.py", line 921, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'fa02dd4b8cccee2c7b57d9575e471d4a835d5bca6732c42578781436e9dc0546'
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 462, in _handle_events
    self._handle_recv()
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 492, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 444, in _run_callback
    callback(*args, **kwargs)
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/jupyter_client/threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/jupyter_client/session.py", line 921, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'fa02dd4b8cccee2c7b57d9575e471d4a835d5bca6732c42578781436e9dc0546'
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(92, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(92, 1)>
Traceback (most recent call last):
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 462, in _handle_events
    self._handle_recv()
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 492, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 444, in _run_callback
    callback(*args, **kwargs)
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/jupyter_client/threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/jupyter_client/session.py", line 921, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'fa02dd4b8cccee2c7b57d9575e471d4a835d5bca6732c42578781436e9dc0546'
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 444, in _run_callback
    callback(*args, **kwargs)
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/jupyter_client/threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/jupyter_client/session.py", line 921, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'fee7375de37b9005f923a6b218592e702c80a304199701d15a0d9616f1e50061'
ERROR:tornado.application:Exception in callback functools.partial(<bound method ThreadedZMQSocketChannel._flush of <qtconsole.client.QtZMQSocketChannel object at 0x7f3bd83cfaf8>>)
Traceback (most recent call last):
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/jupyter_client/threaded.py", line 143, in _flush
    self.stream.flush()
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 364, in flush
    self._handle_recv()
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 492, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 444, in _run_callback
    callback(*args, **kwargs)
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/jupyter_client/threaded.py", line 92, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/home/ivo/anaconda3/envs/ninolearn/lib/python3.6/site-packages/jupyter_client/session.py", line 921, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'fee7375de37b9005f923a6b218592e702c80a304199701d15a0d9616f1e50061'
```

## Versions

* Spyder version: 4.2.0 
* Python version: 3.6.11
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Linux 5.4.0-26-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=4.0                   :  7.16.1 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  21.5.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.3 (OK)
pygments >=2.0                  :  2.7.2 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.1 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.1.1 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=4.7.7               :  4.7.7 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  49.6.0.post20201009 (OK)
sphinx >=0.6.6                  :  3.3.1 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.3 (OK)
xdg >=0.26                      :  0.26 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.3.3 (OK)
numpy >=1.7                     :  1.19.4 (OK)
pandas >=1.1.1                  :  1.1.4 (OK)
scipy >=0.17.0                  :  1.5.3 (OK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by JeanPierreLeDouche** [comment]
Turns out: Spyder does not close all processes running from a script when you interrupt it. Upon restarting the above bug then occurs.
