### ISSUE TITLE
Variable explorer error while inspecting Dataframe

### ISSUE THREAD

**Issue by jctamaraf** [spyder-ide/spyder#16296]
### What steps will reproduce the problem?

1. Created a DataFrame from a json file
2. Double click the created dataframe on the variable explorer

P.D. There is a typo error in the Issue reporter button -> "Submit to Githul"

### Traceback
```python-traceback
Traceback (most recent call last):
  File "c:\users\sa178604\documents\python\envs\spyderenv\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionsdelegate.py", line 201, in createEditor
    if not editor.setup_and_check(value, title=key):
  File "c:\users\sa178604\documents\python\envs\spyderenv\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 940, in setup_and_check
    self.dataModel = DataFrameModel(data, parent=self)
  File "c:\users\sa178604\documents\python\envs\spyderenv\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 135, in __init__
    self.max_min_col_update()
  File "c:\users\sa178604\documents\python\envs\spyderenv\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 247, in max_min_col_update
    vmax = col.max(skipna=True)
  File "c:\users\sa178604\documents\python\envs\spyderenv\lib\site-packages\pandas\core\generic.py", line 10819, in max
    return NDFrame.max(self, axis, skipna, level, numeric_only, **kwargs)
  File "c:\users\sa178604\documents\python\envs\spyderenv\lib\site-packages\pandas\core\generic.py", line 10365, in max
    "max", nanops.nanmax, axis, skipna, level, numeric_only, **kwargs
  File "c:\users\sa178604\documents\python\envs\spyderenv\lib\site-packages\pandas\core\generic.py", line 10355, in _stat_function
    func, name=name, axis=axis, skipna=skipna, numeric_only=numeric_only
  File "c:\users\sa178604\documents\python\envs\spyderenv\lib\site-packages\pandas\core\series.py", line 4392, in _reduce
    return op(delegate, skipna=skipna, **kwds)
  File "c:\users\sa178604\documents\python\envs\spyderenv\lib\site-packages\pandas\core\nanops.py", line 155, in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)
  File "c:\users\sa178604\documents\python\envs\spyderenv\lib\site-packages\pandas\core\nanops.py", line 410, in new_func
    result = func(values, axis=axis, skipna=skipna, mask=mask, **kwargs)
  File "c:\users\sa178604\documents\python\envs\spyderenv\lib\site-packages\pandas\core\nanops.py", line 1017, in reduction
    result = getattr(values, meth)(axis)
  File "c:\users\sa178604\documents\python\envs\spyderenv\lib\site-packages\numpy\core\_methods.py", line 40, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
TypeError: '>=' not supported between instances of 'str' and 'float'
```

## Versions

* Spyder version: 5.1.1 
* Python version: 3.7.8
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.26.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0                :  2.10.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.1;<1.3.0          :  1.2.1 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  57.4.0 (OK)
sphinx >=0.6.6                :  4.1.2 (OK)
spyder_kernels >=2.1.0;<2.2.0 :  2.1.0 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.5 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  None (OK)
matplotlib >=2.0.0            :  None (OK)
numpy >=1.7                   :  None (OK)
pandas >=1.1.1                :  None (OK)
scipy >=0.17.0                :  None (OK)
sympy >=0.7.3                 :  None (OK)
```

**Comment by ccordoba12** [comment]
Closing due to lack of response.
