### ISSUE TITLE
Symbol not found: __PyInt_AsInt

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1629]
_From [public.t...@gmail.com](https://code.google.com/u/113903131730457783163/) on 2013-11-01T13:56:01Z_

Spyder Version:  2.2.5
Python Version:  2.7.5
Qt Version    :  4.8.5, PyQt4 (API v2) 4.10.3 on Darwin
pyflakes >=0.5.0:  0.5.0 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  1.1.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.1.3 (OK)
matplotlib >=1.0:  1.3.0 (OK)
sympy >=0.7.0   :  0.7.3 (OK)
pylint >=0.25   :  1.0.0 (OK) 

What steps will reproduce the problem?

 1.  After activating a virtualenv with:  return subprocess.call([os.path.join(self.path, 'bin/python'), os.path.join(self.path, 'bin/activate_this.py')]), a call is made to execute pip freeze -l to get the list of packages installed in the virtualenv.
2.     pkgs = [] #: [(name, ver), ..]
        l = self._execute([self._pip_rpath, 'freeze', '-l']).splitlines()
3.  The _execute method is return subprocess.check_output(args, cwd=self.path)
4.  self.path is the location of the virtualenv What is the expected output? What do you see instead? The output should be a list of packagenames reported by pip.  Instead, I get the following traceback:

\>>> runfile('/Users/athomson/Projects/deps/deps.py', wdir=r'/Users/athomson/Projects/deps')
Traceback (most recent call last):
  File "bin/pip", line 5, in \<module>
    from pkg_resources import load_entry_point
  File "pkg_resources.pyc", line 16, in \<module>
    e
  File "zipfile.pyc", line 6, in \<module>
  File "io.pyc", line 51, in \<module>
ImportError: dlopen(/Applications/Spyder.app/Contents/Resources/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyInt_AsInt
  Referenced from: /Applications/Spyder.app/Contents/Resources/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /Applications/Spyder.app/Contents/Resources/lib/python2.7/lib-dynload/_io.so
Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/spyderlib/widgets/externalshell/sitecustomize.py", line 540, in runfile
    execfile(filename, namespace)
  File "/Users/athomson/Projects/deps/deps.py", line 162, in \<module>
    process_list(env.package_tuples)
  File "/Users/athomson/Projects/deps/deps.py", line 54, in package_tuples
    l = self._execute([self._pip_rpath, 'freeze', '-l']).splitlines()
  File "/Users/athomson/Projects/deps/deps.py", line 42, in _execute
    return subprocess.check_output(args, cwd=self.path)
  File "subprocess.pyc", line 575, in check_output
subprocess.CalledProcessError: Command '['bin/pip', 'freeze', '-l']' returned non-zero exit status 1 

Please provide any additional information below

. Code runs without error from the command line on Mac OSX 10.8.4 and the same version of Python

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1629_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-01T15:39:50Z_

No idea what's happening here. I hope you've fixed this problem by now :-)

**Status:** WontFix
