### ISSUE TITLE
I can't work with variable explorer

### ISSUE THREAD

**Issue by alihps** [spyder-ide/spyder#16305]
### What steps will reproduce the problem?

When I run code, after that I can't work with variable in variable explorer. I can't open variables,

### Traceback
```python-traceback
Traceback (most recent call last):
  File "...\PythonAnaconda\installfolder\envs\bigdata\lib\site-packages\spyder\plugins\layout\container.py", line 190, in <lambda>
    return lambda: self.quick_layout_switch(i)
  File "...\PythonAnaconda\installfolder\envs\bigdata\lib\site-packages\spyder\plugins\layout\container.py", line 435, in quick_layout_switch
    possible_current_layout)
ValueError: 'Matlab layout' is not in list
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.7.10
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 8.1

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.9.3 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  57.4.0 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.21 (OK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  1.21.0 (OK)
pandas >=1.1.1                :  1.3.0 (OK)
scipy >=0.17.0                :  1.7.0 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @alihps, thanks for reporting. Please close Spyder, open a terminal (i.e. cmd.exe), run there

    spyder --reset

and open Spyder again. That could solve your problem.

**Comment by alihps** [comment]
Hi dear Carlos
Thanks. It works now properly.

**Comment by ccordoba12** [comment]
Great! I'm glad Spyder is working fine for you again.
