### ISSUE TITLE
outline_explorer not part of REQUIRES or OPTIONAL requirements

### ISSUE THREAD

**Issue by latgarf** [spyder-ide/spyder#16321]
### What steps will reproduce the problem?

Pressing 'maximize current pane' button results in this error.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/spyder/plugins/layout/container.py", line 90, in <lambda>
    toggled=lambda state: self._plugin.maximize_dockwidget(),
  File "/usr/lib/python3.9/site-packages/spyder/plugins/layout/plugin.py", line 613, in maximize_dockwidget
    outline_explorer = self.get_plugin(Plugins.OutlineExplorer)
  File "/usr/lib/python3.9/site-packages/spyder/api/plugins.py", line 956, in get_plugin
    raise SpyderAPIError(
spyder.api.exceptions.SpyderAPIError: Plugin "outline_explorer" not part of REQUIRES or OPTIONAL requirements!
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.9.6
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 5.13.13-arch1-1

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.25.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.9.3 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  50.3.2 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.1.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  None (OK)
scipy >=0.17.0                :  None (OK)
sympy >=0.7.3                 :  1.6 (OK)
```

**Comment by ccordoba12** [comment]
Hey @latgarf, thanks for reporting. Please inform about this problem to your Linux disro maintainers. Unfortunately, we can't give support to users from Linux distros because their maintainers don't follow our requirements and patch Spyder to make it work with their own packages.

I'd recommend you to stop using Spyder that way and instead install it in a virtualenv with pip or (better yet) through Anaconda. Thanks for understanding.
