### ISSUE TITLE
Spider crashes when open

### ISSUE THREAD

**Issue by AtsushiShiromaru** [spyder-ide/spyder#16334]
### What steps will reproduce the problem?

1.	Download Anaconda
2.	Install Anaconda using the downloaded file
3.	Open an Anaconda prompt from the start menu
4.	Create a new environment “tf” by using the command “conda create --name tf”
5.	Activate the new environment by using the command “conda activate tf” 
6.	Install Spyder “conda install -c anaconda spyder”
7.	In the Anaconda environment, install tensorflow via the command “pip install tensorflow”
8.	Open a new instance of Spyder through the Anaconda prompt by typing in the command “spyder --new-instance”

In windows10 environment, execute these steps. Everytime happen.

### Traceback
```python-traceback
  File "C:\Users\22315752\Anaconda3\envs\tf\lib\site-packages\spyder\plugins\completion\kite\client.py", line 173, in perform_request
    self.sig_response_ready.emit(req_id, response or {})
TypeError: KiteClient.sig_response_ready[int, dict].emit(): argument 2 has unexpected type 'str'
WARNING:traitlets:kernel died: 25.000189542770386
Traceback (most recent call last):
  File "C:\Users\22315752\Anaconda3\envs\tf\lib\site-packages\spyder\plugins\completion\kite\client.py", line 173, in perform_request
    self.sig_response_ready.emit(req_id, response or {})
TypeError: KiteClient.sig_response_ready[int, dict].emit(): argument 2 has unexpected type 'str'
Traceback (most recent call last):
  File "C:\Users\22315752\Anaconda3\envs\tf\lib\site-packages\spyder\plugins\completion\kite\client.py", line 173, in perform_request
    self.sig_response_ready.emit(req_id, response or {})
TypeError: KiteClient.sig_response_ready[int, dict].emit(): argument 2 has unexpected type 'str'
Traceback (most recent call last):
  File "C:\Users\22315752\Anaconda3\envs\tf\lib\site-packages\spyder\plugins\completion\kite\client.py", line 173, in perform_request
    self.sig_response_ready.emit(req_id, response or {})
TypeError: KiteClient.sig_response_ready[int, dict].emit(): argument 2 has unexpected type 'str'
Traceback (most recent call last):
  File "C:\Users\22315752\Anaconda3\envs\tf\lib\site-packages\spyder\plugins\completion\kite\client.py", line 173, in perform_request
    self.sig_response_ready.emit(req_id, response or {})
TypeError: KiteClient.sig_response_ready[int, dict].emit(): argument 2 has unexpected type 'str'
Traceback (most recent call last):
  File "C:\Users\22315752\Anaconda3\envs\tf\lib\site-packages\spyder\plugins\completion\kite\client.py", line 173, in perform_request
    self.sig_response_ready.emit(req_id, response or {})
TypeError: KiteClient.sig_response_ready[int, dict].emit(): argument 2 has unexpected type 'str'
Traceback (most recent call last):
  File "C:\Users\22315752\Anaconda3\envs\tf\lib\site-packages\spyder\plugins\completion\kite\client.py", line 173, in perform_request
    self.sig_response_ready.emit(req_id, response or {})
TypeError: KiteClient.sig_response_ready[int, dict].emit(): argument 2 has unexpected type 'str'
Traceback (most recent call last):
  File "C:\Users\22315752\Anaconda3\envs\tf\lib\site-packages\spyder\plugins\completion\kite\client.py", line 173, in perform_request
    self.sig_response_ready.emit(req_id, response or {})
TypeError: KiteClient.sig_response_ready[int, dict].emit(): argument 2 has unexpected type 'str'
Traceback (most recent call last):
  File "C:\Users\22315752\Anaconda3\envs\tf\lib\site-packages\spyder\plugins\completion\kite\client.py", line 173, in perform_request
    self.sig_response_ready.emit(req_id, response or {})
TypeError: KiteClient.sig_response_ready[int, dict].emit(): argument 2 has unexpected type 'str'
Traceback (most recent call last):
  File "C:\Users\22315752\Anaconda3\envs\tf\lib\site-packages\spyder\plugins\completion\kite\client.py", line 173, in perform_request
    self.sig_response_ready.emit(req_id, response or {})
TypeError: KiteClient.sig_response_ready[int, dict].emit(): argument 2 has unexpected type 'str'
```

## Versions

* Spyder version: 4.1.5 
* Python version: 3.7.11
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  4.0.0 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.26.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.1.0 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.8.0 (OK)
pygments >=2.0                 :  2.10.0 (OK)
pylint >=1.0                   :  2.9.6 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  3.0.2 (OK)
qtawesome >=0.5.7              :  1.0.2 (OK)
qtconsole >=4.6.0              :  5.1.0 (OK)
qtpy >=1.5.0                   :  1.10.0 (OK)
rtree >=0.8.3                  :  0.9.7 (OK)
sphinx >=0.6.6                 :  4.0.2 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  22.2.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  1.19.5 (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment]
Hey @AtsushiShiromaru, thanks for reporting. This problem is fixed in our latest Spyder 4 version. Please update by closing Spyder, opening the Anaconda Prompt and running there

    conda update anaconda
    conda install spyder=4.2.5
