### ISSUE TITLE
Unable to connect to remote ipython kernel

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1635]
_From [Sher...@gmail.com](https://code.google.com/u/104057091891164394156/) on 2013-11-07T15:57:38Z_

Spyder Version:  2.3.0beta1
Python Version:  2.7.4
Qt Version    :  4.8.4, PyQt4 (API v2) 4.10 on Linux
pyflakes >=0.5.0:  None (NOK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  0.13.2 (OK)
rope >=0.9.2    :  None (NOK)
sphinx >=0.6.6  :  None (NOK)
matplotlib >=1.0:  1.2.1 (OK)
sympy >=0.7.0   :  0.7.2 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1. Start ipython kernel on remote server
2. Copy .json file to client
3. Change working directory of spyder to location of .json file
4. In IPython console window, right click, select connect to existing kernel What is the expected output? What do you see instead? Expect to see intro code followed by IPython prompt (In [1]:)
I receive intro code, but no prompt:

"
Python 2.7.4 (default, Sep 26 2013, 03:20:26) 
Type "copyright", "credits" or "license" for more information.

IPython 0.13.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
&#37;quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
&#37;guiref   -> A brief reference about the graphical user interface.

Welcome to pylab, a matplotlib-based Python environment [backend: module://IPython.zmq.pylab.backend_inline].
For more information, type 'help(pylab)'.

" 

Please provide any additional information below

. I don't think it is connecting at all.  If I shutdown the remote server and try to connect, I still get the same message.  I am, however, able to connect from a terminal using:

ipython console --existing /tmp/kernel-100.json --ssh server

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1635_

**Comment by spyder-issues-migrator** [comment]
_From [Sher...@gmail.com](https://code.google.com/u/104057091891164394156/) on 2013-11-08T06:32:46Z_

Unfortunately, I didn't notice this earlier, but when I try to "Open an ipython console" (creating a new kernel and connecting to it), I get an error on the internal console:

Spyder 2.3.0beta1 internal shell on Python 2.7.4 64bits [Linux]
Inspect Spyder internals:
  spy.app, spy.window, dir(spy)
\>>> Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/IPython/frontend/qt/base_frontend_mixin.py", line 109, in _dispatch
    handler(msg)
  File "/usr/lib/python2.7/dist-packages/IPython/frontend/qt/console/ipython_widget.py", line 173, in _handle_execute_reply
    self._show_interpreter_prompt(number)
  File "/usr/lib/python2.7/dist-packages/IPython/frontend/qt/console/ipython_widget.py", line 380, in _show_interpreter_prompt
    self._show_prompt(self._make_in_prompt(number), html=True)
  File "/usr/lib/python2.7/dist-packages/IPython/frontend/qt/console/ipython_widget.py", line 500, in _make_in_prompt
    body = self.in_prompt % number
ValueError: incomplete format
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/IPython/frontend/qt/base_frontend_mixin.py", line 109, in _dispatch
    handler(msg)
  File "/usr/lib/python2.7/dist-packages/IPython/frontend/qt/console/ipython_widget.py", line 173, in _handle_execute_reply
    self._show_interpreter_prompt(number)
  File "/usr/lib/python2.7/dist-packages/IPython/frontend/qt/console/ipython_widget.py", line 380, in _show_interpreter_prompt
    self._show_prompt(self._make_in_prompt(number), html=True)
  File "/usr/lib/python2.7/dist-packages/IPython/frontend/qt/console/ipython_widget.py", line 500, in _make_in_prompt
    body = self.in_prompt % number
ValueError: incomplete format

**Comment by spyder-issues-migrator** [comment]
_From [david.ve...@gmail.com](https://code.google.com/u/108342766018366950755/) on 2014-01-18T09:30:13Z_

I will try to dig deeper in to this, but it seems that currently you can not just add the argument "--ssh servername" in the "connect to an existing kernel" dialogue in Spyder. There seems to be more work required to get this to work, but I am not familiar with the code base so this assessment could be wrong. Anyway, I think this is a very nice feature request.

**Status:** Accepted  
  **Labels:** -Type-Defect Type-Enh Cat-IPythonConsole

**Comment by spyder-issues-migrator** [comment]
_From [david.ve...@gmail.com](https://code.google.com/u/108342766018366950755/) on 2014-01-18T14:19:35Z_

Seems to me that this issue boils down to correctly forwarding the respective ports over SSH. The "--ssh serveraddress" argument seems to assume you can connect to the server via SSH over port 22 without using any password or login. Not sure how configuring SSH correctly on server and client side should be handled by Spyder...

**Comment by spyder-issues-migrator** [comment]
_From [david.ve...@gmail.com](https://code.google.com/u/108342766018366950755/) on 2014-03-26T12:19:40Z_

I forgot to link to the corresponding discussion on the mailing list, and which also includes a guide on how to connect to an IPython kernel running on a remote machine using Spyder and SSH port forwarding: https://groups.google.com/forum/#!msg/spyderlib/04n0xiGypvI/SE978ogeh4oJ

**Comment by spyder-issues-migrator** [comment]
_From [sylvain....@gmail.com](https://code.google.com/u/102212202545902308399/) on 2014-03-26T12:26:19Z_

This is a duplicate to https://code.google.com/p/spyderlib/issues/detail?id=1690 I have a pull request on bitbucket that provides this functionality. https://bitbucket.org/spyder-ide/spyderlib/pull-request/20/connection-to-a-remote-kernel-via-ssh

**Comment by spyder-issues-migrator** [comment]
_From [sylvain....@gmail.com](https://code.google.com/u/102212202545902308399/) on 2014-03-26T12:26:46Z_

**Status:** Duplicate  
  **Mergedinto:** 1690
