### ISSUE TITLE
Turtles not working

### ISSUE THREAD

**Issue by mbrinkman-hc** [spyder-ide/spyder#16380]
### What steps will reproduce the problem?

Created following code, then ran program:
turtles = []
for i in range(5):
    turtles.insert(i, turtle.Turtle())
    turtles[i].penup()
    
turtles[0].color("blue")
turtles[1].color("yellow")
turtles[2].color("black")
turtles[3].color("green")
turtles[4].color("red")

turtles[0].goto(-250, 100)
turtles[1].goto(-250, 50)
turtles[2].goto(-250, 0)
turtles[3].goto(-250, -50)
turtles[4].goto(-250, -100)

for i in range(5):
    turtles[i].pendown()
    
turtle1Steps = turtle2Steps = turtle3Steps = turtle4Steps = turtle5Steps = 0

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\qtconsole\manager.py", line 27, in poll
    super().poll()
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\restarter.py", line 127, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\utils.py", line 25, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))
  File "C:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "C:\ProgramData\Anaconda3\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 477, in _async_restart_kernel
    await ensure_async(self.shutdown_kernel(now=now, restart=True))
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\utils.py", line 25, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))
  File "C:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "C:\ProgramData\Anaconda3\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 436, in _async_shutdown_kernel
    await ensure_async(self._kill_kernel())
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\utils\manager.py", line 92, in _kill_kernel
    self.kill_proc_tree(self.kernel.pid)
AttributeError: 'SpyderKernelManager' object has no attribute 'kernel'
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.26.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=1.0                  :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  1.0.2 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.2 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by dalthviz** [comment]
Hi @mbrinkman-hc thanks for the feedback, could you update Spyder to the latest release (5.1.3) and try again? Let us know if that helps!

**Comment by dalthviz** [comment]
Note: seems like this error is caused by an incompatibility with jupyter_client >= 7 so installing jupyter_client>=5.3.4,<7 should help
