### ISSUE TITLE
I cannot use the console

### ISSUE THREAD

**Issue by GracielaLopezRosson** [spyder-ide/spyder#16381]
### What steps will reproduce the problem?

I just open spyder and I get the message that I should install the spyder-kernels.
But I cannot run anything on the console

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\graci\Anaconda3\envs\tf\lib\site-packages\qtconsole\console_widget.py", line 427, in eventFilter
    return self._event_filter_console_keypress(event)
  File "C:\Users\graci\Anaconda3\envs\tf\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 653, in _event_filter_console_keypress
    self)._event_filter_console_keypress(event)
  File "C:\Users\graci\Anaconda3\envs\tf\lib\site-packages\qtconsole\frontend_widget.py", line 378, in _event_filter_console_keypress
    return super()._event_filter_console_keypress(event)
  File "C:\Users\graci\Anaconda3\envs\tf\lib\site-packages\qtconsole\console_widget.py", line 1272, in _event_filter_console_keypress
    self.execute(interactive = not shift_down)
  File "C:\Users\graci\Anaconda3\envs\tf\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 243, in execute
    super(ShellWidget, self).execute(source, hidden, interactive)
  File "C:\Users\graci\Anaconda3\envs\tf\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 573, in execute
    source, hidden, interactive)
  File "C:\Users\graci\Anaconda3\envs\tf\lib\site-packages\qtconsole\console_widget.py", line 651, in execute
    source, partial(self.do_execute, source))
  File "C:\Users\graci\Anaconda3\envs\tf\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 664, in _register_is_complete_callback
    source, callback)
  File "C:\Users\graci\Anaconda3\envs\tf\lib\site-packages\qtconsole\console_widget.py", line 600, in _register_is_complete_callback
    self._is_complete_msg_id = self.kernel_client.is_complete(source)
AttributeError: 'NoneType' object has no attribute 'is_complete'
```

## Versions

* Spyder version: 5.1.3 
* Python version: 3.7.11
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.27.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.2 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.11.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  57.4.0 (OK)
sphinx >=0.6.6                :  4.1.2 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.5 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  None (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.19.5 (OK)
pandas >=1.1.1                :  1.3.2 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  None (OK)
```

**Comment by dalthviz** [comment]
Hi @GracielaLopezRosson , could you put here the complete message related with `spyder-kernels` that is being shown? Let us know!

**Comment by lukeallpress** [comment]
I also am having trouble with the console after installing 5.1.3 from the .dmg this morning. Error message pasted below. I also _think_ I remember this issue when I installed one or two of the earlier 5.x versions from .dmg, but was able to fix with a conda-forge install pretty quickly. This time, Terminal has been slogging along trying to resolve a conflict for almost two hours now :(

`Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 2.1.0 and < 2.2.0). Without this module is not possible for Spyder to create a console for you.
You can install it by running in a system terminal:
conda install spyder‑kernels=2.1
or
pip install spyder‑kernels==2.1.*`

**Comment by dalthviz** [comment]
Hi @lukeallpress thanks for the feedback! Could you try running `conda install -c conda-forge spyder-kernels=2.1.1` in the env of your custom interpreter and see if that helps with the conflict? Let us know!

**Comment by lukeallpress** [comment]
That's the command that's been running in my Terminal (BigSur 11.4) for 2+ hours now, except I only fed it `2.1` at the end. It has been on this output for a _long_ time now, if it helps: `Examining conflict for prompt_toolkit backports.shutil_get_terminal_size googleapis-common-protos black tomli debugpy google-cloud-bigquery jedi ya`. I saw debugpy mentioned in similar console issues. 

Let me know if you want any more details from me. Starting to think this might just be a problem with my environment that I need to settle myself.

**Comment by dalthviz** [comment]
I'm not totally sure but I suggested providing the specific `spyder-kernels` version (`2.1.1` instead of `2.1`) since maybe that could help prevent the endless conflict resolution situation (two hours is a lot of time!).

@ccordoba12 or @mrclary maybe you have some better ideas or suggestions to further debug this?

**Comment by mrclary** [comment]
I'm not sure what's going on. My suggestion would be to try and recreate the environment with the spyder-kernels constraint. Anecdotally, updating a single package in an otherwise stale conda environment has given me similar problems in the past; I've always just recreated the environment to resolve it.

**Comment by lukeallpress** [comment]
I terminated after 3 hours of Terminal working on `2.1.1`. I then used `conda` to remove `spyder-kernels` then ran the install script again and it worked quickly, and Spyder runs now. Sorry for the hassle, hopefully this can help someone else.

I am still curious why I've gotten the "need to install 2.1" message multiple times after upgrading Spyder, but for me at least it's not a pressing need to fix.

**Comment by dalthviz** [comment]
Closing due to lack of OP response
