### ISSUE TITLE
Tkinter tutorial wont run 

### ISSUE THREAD

**Issue by DeftlySpencer** [spyder-ide/spyder#16433]
### What steps will reproduce the problem?

I can import all the needed classes/libraires. Not the problem. 

I try to run this sample code which works in pycharm... and spyder fails. 
I tried forcing it to use Tkinter instead of automatic in Ipython/Graphics ->  graphics backend.  and still comes up with this system error which doesn't lead me to any kind of real error reporting so I dont know what to fix. I added tkinter to the end of  completion and linking / introspection - > advanced preload modules. Seeminlgy I have a feeling it has something to do with conda and tkinter but no clue where to start troubleshooting. "The spyder Kernel Manager not having attribute kernel seems suspicious but also means greek to me" 

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/Users/spenceroliver/opt/anaconda3/envs/py38/lib/python3.8/site-packages/qtconsole/manager.py", line 27, in poll
    super().poll()
  File "/Users/spenceroliver/opt/anaconda3/envs/py38/lib/python3.8/site-packages/jupyter_client/restarter.py", line 127, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "/Users/spenceroliver/opt/anaconda3/envs/py38/lib/python3.8/site-packages/jupyter_client/utils.py", line 25, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))
  File "/Users/spenceroliver/opt/anaconda3/envs/py38/lib/python3.8/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "/Users/spenceroliver/opt/anaconda3/envs/py38/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/Users/spenceroliver/opt/anaconda3/envs/py38/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/Users/spenceroliver/opt/anaconda3/envs/py38/lib/python3.8/site-packages/jupyter_client/manager.py", line 477, in _async_restart_kernel
    await ensure_async(self.shutdown_kernel(now=now, restart=True))
  File "/Users/spenceroliver/opt/anaconda3/envs/py38/lib/python3.8/site-packages/jupyter_client/utils.py", line 25, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))
  File "/Users/spenceroliver/opt/anaconda3/envs/py38/lib/python3.8/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "/Users/spenceroliver/opt/anaconda3/envs/py38/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/Users/spenceroliver/opt/anaconda3/envs/py38/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/Users/spenceroliver/opt/anaconda3/envs/py38/lib/python3.8/site-packages/jupyter_client/manager.py", line 436, in _async_shutdown_kernel
    await ensure_async(self._kill_kernel())
  File "/Users/spenceroliver/opt/anaconda3/envs/py38/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/utils/manager.py", line 109, in _kill_kernel
    self.kernel.wait()
AttributeError: 'SpyderKernelManager' object has no attribute 'kernel'
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.8.11
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.6.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.26.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=1.0                  :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.21.2 (OK)
pandas >=1.1.1                :  1.3.3 (OK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by DeftlySpencer** [comment]
Anaconda Prompt? as in activate the venv I created via conda and downgrade my jupyter_client to 6.1.12? 
Ok so all this did was force the python script to restart the kernel when I run the code. Probably wasn't the answer but it sure did fix spyder from crashing. Now it does zilch.

**Comment by ccordoba12** [comment]
> Anaconda Prompt? as in activate the venv I created via conda and downgrade my jupyter_client to 6.1.12?

Yes.

**Comment by DeftlySpencer** [comment]
Hmm thanks but I think that causes another issue where when I run a program it just restarts the kernel. 
p.s. spyder-bot ( Windows: Open the Anaconda Prompt (Click Start, select Anaconda Prompt) -ok so the term means something on windows machine. 
macOS: Open Launchpad, then open terminal or iTerm. - being on a mac the term anaconda prompt made me go looking for a special entry window until I read this on the second page of google.
