### ISSUE TITLE
keyboards shortcuts

### ISSUE THREAD

**Issue by rafaeldtr41** [spyder-ide/spyder#16436]
### What steps will reproduce the problem?

tools->preferences-> start clicking from a side to another until you end on keyboards shortcuts

### Traceback
```python-traceback
  File "/usr/lib/python3/dist-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.8.10
* Qt version: 5.12.8
* PyQt5 version: 5.14.1
* Operating System: Linux 5.4.0-84-generic

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.15.2 (OK)
psutil >=0.3      :  5.5.1 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  None (NOK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.6.0 (OK)
IPython >=4.0     :  7.13.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.4.4 (OK)
```

**Comment by ccordoba12** [comment]
Hey @<>, thanks for reporting. This problem is fixed in our latest version (5.1.4). Please update,
