### ISSUE TITLE
exception while saving preferences

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#16458]
### What steps will reproduce the problem?

I edited a bunch of entries in the preferences dialog, too many to recall, and got an exception on closing the dialog

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\rlabbe\anaconda3\lib\site-packages\spyder\plugins\preferences\widgets\configdialog.py", line 127, in accept
    configpage.apply_changes()
  File "C:\Users\rlabbe\anaconda3\lib\site-packages\spyder\plugins\preferences\api.py", line 110, in apply_changes
    self.apply_callback()
  File "C:\Users\rlabbe\anaconda3\lib\site-packages\spyder\plugins\preferences\api.py", line 142, in <lambda>
    self._apply_settings_tabs(self.changed_options))
  File "C:\Users\rlabbe\anaconda3\lib\site-packages\spyder\plugins\preferences\api.py", line 170, in _apply_settings_tabs
    self.apply_settings(options)
  File "C:\Users\rlabbe\anaconda3\lib\site-packages\spyder\api\preferences.py", line 104, in wrapper
    func(opts)
  File "C:\Users\rlabbe\anaconda3\lib\site-packages\spyder\api\plugins.py", line 1071, in apply_conf
    self.after_configuration_update(list(options_set))
  File "C:\Users\rlabbe\anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 325, in after_configuration_update
    self.register_statusbar_widget(provider_name)
  File "C:\Users\rlabbe\anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 423, in register_statusbar_widget
    self.statusbar.add_status_widget(currrent_widget)
  File "C:\Users\rlabbe\anaconda3\lib\site-packages\spyder\plugins\statusbar\plugin.py", line 106, in add_status_widget
    raise SpyderAPIError(f'Status widget `{id_}` already added!')
spyder.api.exceptions.SpyderAPIError: Status widget `kite_status` already added!
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.27.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=1.0                  :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  1.0.2 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.2 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Closing due to lack of response.
