### ISSUE TITLE
Unable to execute python file

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1648]
_From [adjeies...@gmail.com](https://code.google.com/u/108123485388683254084/) on 2013-11-19T08:46:51Z_

Please i am trying to run a python file in spyderlib ide via python(x,y)
when i load the file and run i get this error message

Apply nonlinear SVM to wine data set.

input dimension: 13
number of training samples: 118
number of test samples: 60

Traceback (most recent call last):
  File "D:\Masters IT FH Kiel\WS1\Machine Learning\MachineLearning\Lab\Lab3\exercise4b.py", line 48, in \<module>
    clf.fit(training, target_training)
  File "C:\Python27\lib\site-packages\sklearn\svm\base.py", line 178, in fit
    fit(X, y, sample_weight, solver_type, kernel, random_seed=seed)
  File "C:\Python27\lib\site-packages\sklearn\svm\base.py", line 233, in _dense_fit
    max_iter=self.max_iter, random_seed=random_seed)
  File "libsvm.pyx", line 173, in sklearn.svm.libsvm.fit (sklearn\svm\libsvm.c:1992)
ValueError: '???' is not in list

Please how do i fix this i have installed it on windows 7 machine

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1648_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-01T15:33:40Z_

This seems a problem in scikit-learn, not in Spyder. Closing because of that.

**Status:** WontFix
