### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by LJ-00** [spyder-ide/spyder#16491]
### What steps will reproduce the problem?

Clicking on Launch. I just installed spyder on this environment of anaconda

### Traceback
```python-traceback
  File "C:\Users\LJ\anaconda3\envs\python36\lib\site-packages\spyder_pylint\widgets\pylintgui.py", line 446, in show_data
    self.treewidget.set_results(filename, results)
  File "C:\Users\LJ\anaconda3\envs\python36\lib\site-packages\spyder_pylint\widgets\pylintgui.py", line 83, in set_results
    self.refresh()
  File "C:\Users\LJ\anaconda3\envs\python36\lib\site-packages\spyder_pylint\widgets\pylintgui.py", line 107, in refresh
    for module, lineno, message, msg_id in messages:
ValueError: too many values to unpack (expected 4)
Traceback (most recent call last):
  File "C:\Users\LJ\anaconda3\envs\python36\lib\site-packages\spyder\plugins\__init__.py", line 514, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\Users\LJ\anaconda3\envs\python36\lib\site-packages\spyder\plugins\ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\LJ\anaconda3\envs\python36\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1038, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\Users\LJ\anaconda3\envs\python36\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1064, in connect_client_to_kernel
    stderr_file)
  File "C:\Users\LJ\anaconda3\envs\python36\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1511, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "C:\Users\LJ\anaconda3\envs\python36\lib\site-packages\jupyter_client\utils.py", line 25, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))
  File "C:\Users\LJ\anaconda3\envs\python36\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "C:\Users\LJ\anaconda3\envs\python36\lib\asyncio\tasks.py", line 180, in _step
    result = coro.send(None)
  File "C:\Users\LJ\anaconda3\envs\python36\lib\site-packages\jupyter_client\manager.py", line 331, in _async_start_kernel
    kernel_cmd, kw = await ensure_async(self.pre_start_kernel(**kw))
  File "C:\Users\LJ\anaconda3\envs\python36\lib\site-packages\jupyter_client\utils.py", line 25, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))
  File "C:\Users\LJ\anaconda3\envs\python36\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "C:\Users\LJ\anaconda3\envs\python36\lib\asyncio\tasks.py", line 180, in _step
    result = coro.send(None)
  File "C:\Users\LJ\anaconda3\envs\python36\lib\site-packages\jupyter_client\manager.py", line 296, in _async_pre_start_kernel
    parent=self,
  File "C:\Users\LJ\anaconda3\envs\python36\lib\site-packages\jupyter_client\provisioning\factory.py", line 91, in create_provisioner_instance
    f"Kernel provisioner '{provisioner_name}' has not been registered."
ModuleNotFoundError: Kernel provisioner 'local-provisioner' has not been registered.
```

## Package Versions

* Spyder 3.2.7 ``
* Python 3.6.13
* Qt 5.9.6
* PyQt5 5.9.2
* Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  2.2.0 (OK)
pycodestyle >=2.3:  2.6.0 (OK)
pygments >=2.0   :  2.10.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.19.5 (OK)
sphinx >=0.6.6   :  4.2.0 (OK)
rope >=0.9.4     :  0.19.0 (OK)
jedi >=0.9.0     :  0.17.2 (OK)
nbconvert >=4.0  :  6.0.7 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  5.1.0 (OK)
IPython >=4.0    :  7.16.1 (OK)
pylint >=0.25    :  2.9.6 (OK)
```

**Comment by ccordoba12** [comment]
Hey @LJ-00, thanks for reporting. Please downgrade your jupyter-kernel version by closing Spyder, opening the Anaconda Prompt and running there

    conda install jupyter_client=6

That could solve your problem if Spyder was working before. Let us know how that goes.

**Comment by LJ-00** [comment]
Unfortunately, it didn't work.

**Comment by ccordoba12** [comment]
Ok, then please update Spyder to the latest version available in Anaconda. For that, closing Spyder, open the Anaconda Prompt and run there

    conda update anaconda
    conda install spyder=5.0.5
    conda install jupyter_client=6

**Comment by ccordoba12** [comment]
Closing due to lack of response.
