### ISSUE TITLE
picture not responding in imshow

### ISSUE THREAD

**Issue by Sreevallilikhitha** [spyder-ide/spyder#16515]
### What steps will reproduce the problem?

picture not responding while executing cv   imshow

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\91738\anaconda3\envs\python36\lib\site-packages\spyder\plugins\preferences\widgets\configdialog.py", line 127, in accept
    configpage.apply_changes()
  File "C:\Users\91738\anaconda3\envs\python36\lib\site-packages\spyder\plugins\preferences\api.py", line 110, in apply_changes
    self.apply_callback()
  File "C:\Users\91738\anaconda3\envs\python36\lib\site-packages\spyder\plugins\preferences\api.py", line 142, in <lambda>
    self._apply_settings_tabs(self.changed_options))
  File "C:\Users\91738\anaconda3\envs\python36\lib\site-packages\spyder\plugins\preferences\api.py", line 170, in _apply_settings_tabs
    self.apply_settings(options)
  File "C:\Users\91738\anaconda3\envs\python36\lib\site-packages\spyder\api\preferences.py", line 104, in wrapper
    func(opts)
  File "C:\Users\91738\anaconda3\envs\python36\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 453, in apply_plugin_settings
    for client in self.clients]
  File "C:\Users\91738\anaconda3\envs\python36\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 453, in <listcomp>
    for client in self.clients]
  File "C:\Users\91738\anaconda3\envs\python36\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 352, in get_matplotlib_backend
    blocking=True).get_matplotlib_backend()
  File "C:\Users\91738\anaconda3\envs\python36\lib\site-packages\spyder_kernels\comms\commbase.py", line 555, in __call__
    call_dict, call_data, self._comm_id)
  File "C:\Users\91738\anaconda3\envs\python36\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 189, in _get_call_return_value
    raise RuntimeError("Kernel is dead")
RuntimeError: Kernel is dead
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.6.13
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.16.1 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=1.0                  :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  1.19.5 (OK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @Sreevallilikhitha, thanks for reporting. Unfortunately, this is not a problem with Spyder but with `cv2`, or the way you installed it, because it makes Spyder crash.

Please post the output of the command `conda list` after activating your environment to see how you installed it.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
