### ISSUE TITLE
Spyder 5.1.5 Kernel issue

### ISSUE THREAD

**Issue by SreeragSK** [spyder-ide/spyder#16523]
So I just updated my Spyder IDLE from Spyder 4 to Spyder 5.1.5 (WIndows 10)
The problem I've been facing is that the kernel is not opening up at all.
Can anyone help me please?

**Comment by ccordoba12** [comment]
Hey @SreeragSK, thanks for reporting. Please post the error you're seeing, else we won't be able to help you.

**Comment by SreeragSK** [comment]
> Hey @SreeragSK, thanks for reporting. Please post the error you're seeing, else we won't be able to help you.

This is the error message that I'm getting:

IPython 7.12.0 -- An enhanced Interactive Python.

[SpyderKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 353, in dispatch_shell
    await result
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 648, in execute_request
    reply_content = await reply_content
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 329, in do_execute
    preprocessing_exc_tuple=preprocessing_exc_tuple,
TypeError: should_run_async() got an unexpected keyword argument 'transformed_cell'
[SpyderKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 353, in dispatch_shell
    await result
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 648, in execute_request
    reply_content = await reply_content
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 329, in do_execute
    preprocessing_exc_tuple=preprocessing_exc_tuple,
TypeError: should_run_async() got an unexpected keyword argument 'transformed_cell'
runcell(0, 'F:/coding apps/cs programes/Personal Programs/LIBRARY_APP_PROJECT.py')

runcell(0, 'F:/coding apps/cs programes/Personal Programs/LIBRARY_APP_PROJECT.py')

[SpyderKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 353, in dispatch_shell
    await result
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 648, in execute_request
    reply_content = await reply_content
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 329, in do_execute
    preprocessing_exc_tuple=preprocessing_exc_tuple,
TypeError: should_run_async() got an unexpected keyword argument 'transformed_cell'
[SpyderKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 353, in dispatch_shell
    await result
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 648, in execute_request
    reply_content = await reply_content
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 329, in do_execute
    preprocessing_exc_tuple=preprocessing_exc_tuple,
TypeError: should_run_async() got an unexpected keyword argument 'transformed_cell'
[SpyderKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 353, in dispatch_shell
    await result
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 648, in execute_request
    reply_content = await reply_content
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 329, in do_execute
    preprocessing_exc_tuple=preprocessing_exc_tuple,
TypeError: should_run_async() got an unexpected keyword argument 'transformed_cell'

**Comment by ccordoba12** [comment]
Ok, please post then the output of

    conda list

to check what packages you have installed.
