### ISSUE TITLE
Trying to use julia.Main to call a function in Julia script.

### ISSUE THREAD

**Issue by groxli** [spyder-ide/spyder#16533]
### What steps will reproduce the problem?

Trying to use julia.Main to call a function in Julia script.

### Traceback
```python-traceback
  File "/Users/nate/anaconda3/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 96, in comm_channel_manager
    yield
  File "/Users/nate/anaconda3/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 151, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
  File "/Users/nate/anaconda3/lib/python3.8/site-packages/spyder_kernels/comms/commbase.py", line 427, in _get_call_return_value
    self._wait_reply(call_id, call_name, timeout)
  File "/Users/nate/anaconda3/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 168, in _wait_reply
    self._wait(got_reply, self._sig_got_reply, timeout_msg, timeout)
  File "/Users/nate/anaconda3/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 205, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for {'59dd2f8eda6b4e9c83cb29ea92f8db92': (True, None)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nate/anaconda3/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/widgets/control.py", line 58, in keyPressEvent
    self._key_paren_left(text)
  File "/Users/nate/anaconda3/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/widgets/control.py", line 50, in _key_paren_left
    self.show_object_info(last_obj)
  File "/Users/nate/anaconda3/lib/python3.8/site-packages/spyder/widgets/mixins.py", line 1446, in show_object_info
    self.help.set_object_text(text, ignore_unknown=False)
  File "/Users/nate/anaconda3/lib/python3.8/site-packages/spyder/plugins/help/plugin.py", line 521, in set_object_text
    found = self.show_help(text, ignore_unknown=ignore_unknown)
  File "/Users/nate/anaconda3/lib/python3.8/site-packages/spyder/plugins/help/plugin.py", line 700, in show_help
    if not shell.is_defined(obj_text):
  File "/Users/nate/anaconda3/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/widgets/help.py", line 133, in is_defined
    return self.call_kernel(
  File "/Users/nate/anaconda3/lib/python3.8/site-packages/spyder_kernels/comms/commbase.py", line 549, in __call__
    return self._comms_wrapper._get_call_return_value(
  File "/Users/nate/anaconda3/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 151, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
  File "/Users/nate/anaconda3/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/nate/anaconda3/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 99, in comm_channel_manager
    self._comms[comm_id]['comm']._send_channel = (
KeyError: '6ada595a202111ec8609acde48001122'
```

## Versions

* Spyder version: 4.1.4 
* Python version: 3.8.1
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Darwin 20.6.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @groxli, thanks for reporting. This is fixed in our latest version available in Anaconda (5.0.5). Please update by closing Spyder, opening the Anaconda Prompt and running there

    conda update anaconda
    conda install spyder=5.0.5
