### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by dowlingevan** [spyder-ide/spyder#16554]
resp = self.socket.recv_pyobj(flags=zmq.NOBLOCK)
  File "C:\Users\edowling\Anaconda3\envs\research\lib\site-packages\zmq\sugar\socket.py", line 776, in recv_pyobj
    return self._deserialize(msg, pickle.loads)
  File "C:\Users\edowling\Anaconda3\envs\research\lib\site-packages\zmq\sugar\socket.py", line 643, in _deserialize
    return load(recvd)
_pickle.UnpicklingError: invalid load key, '\x00'.
Traceback (most recent call last):
 
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

Leaving my spyder editor open over night caused it to fail. I also can't open and view my numpy arrays within the variable explorer.

**Comment by ccordoba12** [comment]
Hey @dowlingevan, thanks for reporting. What's your Spyder version?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
