### ISSUE TITLE
Prompt Error when opening from windows start menu

### ISSUE THREAD

**Issue by canvaskan** [spyder-ide/spyder#16553]
### What steps will reproduce the problem?

Just click on the start menu icon "Spyder(anaconda3)" causes the issue reporter. This problem appears after I updated Spyder from conda from a version of 4.1.x to 4.2.5. But the use experience is unaffected.

### Traceback
```python-traceback
  File "D:\anaconda3\lib\asyncio\windows_events.py", line 453, in finish_recv
    return ov.getresult()
OSError: [WinError 995] 由于线程退出或应用程序请求，已中止 I/O 操作。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "D:\anaconda3\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "D:\anaconda3\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 995] 由于线程退出或应用程序请求，已中止 I/O 操作。
```

## Versions

* Spyder version: 4.2.5 
* Python version: 3.8.5
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  2.0.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=7.6.0                 :  7.28.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  23.2.1 (OK)
nbconvert >=4.0                 :  6.2.0 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.10.0 (OK)
pylint >=1.0                    :  2.11.1 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.3 (OK)
qtconsole >=5.0.3               :  5.1.1 (OK)
qtpy >=1.5.0                    :  1.11.2 (OK)
rtree >=0.8.3                   :  0.8.3 (OK)
setuptools >=39.0.0             :  58.0.4 (OK)
sphinx >=0.6.6                  :  4.2.0 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  22.3.0 (OK)

# Optional:
cython >=0.21                   :  0.29.24 (OK)
matplotlib >=2.0.0              :  3.4.3 (OK)
numpy >=1.7                     :  1.20.3 (OK)
pandas >=1.1.1                  :  1.3.3 (OK)
scipy >=0.17.0                  :  1.7.1 (OK)
sympy >=0.7.3                   :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @canvaskan, thanks for reporting. It seems something went wrong during the update. To test if that was the case, you need to create a new environment. For that, please close Spyder, open the Anaconda Prompt and run there

    conda create -n spyder-env python=3.8 spyder=4.2.5
    conda activate spyder-env
    spyder

Let us know if that works for you.

**Comment by canvaskan** [comment]
After runing your code, Spyder now can be opened without Error. 
That's amazing. I think I only need to re-install some packages and use the new spyder-env for future coding. 
Thanks a lot.
