### ISSUE TITLE
select commit option

### ISSUE THREAD

**Issue by jocerfranquiz** [spyder-ide/spyder#16588]
### What steps will reproduce the problem?

modify a .py file
right click over file name in the upper right sub window
select commit option

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/paxonian/miniconda3/lib/python3.7/site-packages/spyder/plugins/explorer/widgets/explorer.py", line 403, in <lambda>
    triggered=lambda: self.vcs_command('commit'),
  File "/home/paxonian/miniconda3/lib/python3.7/site-packages/spyder/plugins/explorer/widgets/explorer.py", line 1448, in vcs_command
    vcs.run_vcs_tool(path, action)
  File "/home/paxonian/miniconda3/lib/python3.7/site-packages/spyder/utils/vcs.py", line 87, in run_vcs_tool
    programs.run_program(tool, args, cwd=path)
  File "/home/paxonian/miniconda3/lib/python3.7/site-packages/spyder/utils/programs.py", line 278, in run_program
    return subprocess.Popen(fullcmd, **subprocess_kwargs)
  File "/home/paxonian/miniconda3/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/paxonian/miniconda3/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: '/mnt/c/Users/paxonian/projects/pyspark/jocerfranquiz-data-engineering-test/src/main.py'
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.7.11
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.19.84-microsoft-standard

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.27.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=1.0                  :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by jocerfranquiz** [comment]
Hi Carlos, thanks for getting back to me so quickly.

I actually will uninstall anaconda and follow your advice. Anaconda
navigator takes too much RAM.

Thanks again for your help,

Jocer
