### ISSUE TITLE
Open variable explorer pops up with internal problem popup

### ISSUE THREAD

**Issue by Mrityunjay87** [spyder-ide/spyder#16648]
### What steps will reproduce the problem?

1.RUN Script
2.Open df in variable explorer to look for data

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 356, in data
    return to_qvariant(self.get_bgcolor(index))
  File "C:\Users\Mrityunjay\.conda\envs\marketResearch\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 302, in get_bgcolor
    if vmax - vmin == 0:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.7
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.27.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  None (OK)
matplotlib >=2.0.0            :  None (OK)
numpy >=1.7                   :  None (OK)
pandas >=1.1.1                :  None (OK)
scipy >=0.17.0                :  None (OK)
sympy >=0.7.3                 :  None (OK)
```

**Comment by dalthviz** [comment]
Closing due to lack of response
