### ISSUE TITLE
Cannot set/unset "Automatic connections"

### ISSUE THREAD

**Issue by Krohon** [spyder-ide/spyder#16701]
### What steps will reproduce the problem?

Click on "Tools", then on "Preferences". Select "Help" and set (or unset) "Editor" and/or "IPython Console" under "Automatic connections".

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/krohon/bin/anaconda3/envs/spyder5/lib/python3.9/site-packages/spyder/plugins/preferences/widgets/configdialog.py", line 136, in button_clicked
    configpage.apply_changes()
  File "/home/krohon/bin/anaconda3/envs/spyder5/lib/python3.9/site-packages/spyder/plugins/preferences/api.py", line 108, in apply_changes
    self.save_to_conf()
  File "/home/krohon/bin/anaconda3/envs/spyder5/lib/python3.9/site-packages/spyder/plugins/preferences/api.py", line 329, in save_to_conf
    self.set_option(option, value, section=sec,
  File "/home/krohon/bin/anaconda3/envs/spyder5/lib/python3.9/site-packages/spyder/api/plugins.py", line 1035, in set_conf
    self.apply_conf({option}, False)
TypeError: apply_conf() takes 2 positional arguments but 3 were given
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.9.7
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 5.3.18-lp152.95-preempt

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.27.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=1.0                  :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.4.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.21.2 (OK)
pandas >=1.1.1                :  1.3.3 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by steff456** [comment]
Hi @Krohon,

This issue is fixed in our latest version, can you please upgrade to Spyder 5.1.2? Please let me know how it goes!

**Comment by ccordoba12** [comment]
Closing due to lack of response.
