### ISSUE TITLE
AttributeError when importing torch_geometric using ipython in spyder

### ISSUE THREAD

**Issue by jajupmochi** [spyder-ide/spyder#16710]
## Problem Description

Hi, I am using the `torch_geometric` library with `IPython` command line in `Spyder`.  When I do 
```
import torch_geometric
```
It returns an error:
```
Traceback (most recent call last):

  File "/media/ljia/DATA/research-repo/courses/Pytorch geometric tutorial/tutorial 1/tutorial1.py", line 10, in <module>
    import torch_geometric

  File "/usr/local/lib/python3.8/site-packages/torch_geometric/__init__.py", line 7, in <module>
    import torch_geometric.data

  File "/usr/local/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data

  File "/usr/local/lib/python3.8/site-packages/torch_geometric/data/data.py", line 14, in <module>
    from torch_geometric.data.storage import (BaseStorage, NodeStorage,

  File "/usr/local/lib/python3.8/site-packages/torch_geometric/data/storage.py", line 15, in <module>
    from torch_geometric.utils import is_undirected

  File "/usr/local/lib/python3.8/site-packages/torch_geometric/utils/__init__.py", line 2, in <module>
    from .softmax import softmax

  File "/usr/local/lib/python3.8/site-packages/torch_geometric/utils/softmax.py", line 11, in <module>
    def softmax(src: Tensor, index: Optional[Tensor] = None,

  File "/home/ljia/.local/lib/python3.8/site-packages/torch/jit/_script.py", line 1310, in script
    fn = torch._C._jit_script_compile(

  File "/home/ljia/.local/lib/python3.8/site-packages/torch/jit/_script.py", line 1374, in _get_overloads
    _compile_function_with_overload(overload_fn, qual_name, obj)

  File "/home/ljia/.local/lib/python3.8/site-packages/torch/jit/_script.py", line 1338, in _compile_function_with_overload
    overload_signature = torch.jit.annotations.get_signature(

  File "/home/ljia/.local/lib/python3.8/site-packages/torch/jit/annotations.py", line 85, in get_signature
    signature = parse_type_line(type_line, rcb, loc)

  File "/home/ljia/.local/lib/python3.8/site-packages/torch/jit/annotations.py", line 150, in parse_type_line
    arg_ann = eval(arg_ann_str, {}, EvalEnv(rcb))  # type: ignore[arg-type] # noqa: P204

  File "<string>", line 1, in <module>

  File "/usr/local/lib/python3.8/bdb.py", line 90, in trace_dispatch
    return self.dispatch_call(frame, arg)

  File "/usr/local/lib/python3.8/bdb.py", line 128, in dispatch_call
    if not (self.stop_here(frame) or self.break_anywhere(frame)):

  File "/usr/local/lib/python3.8/site-packages/spyder_kernels/customize/spyderpdb.py", line 258, in stop_here
    and frame.f_locals.get(

AttributeError: 'EvalEnv' object has no attribute 'get'
```

This error does not appear when I run the script from a console.

The versions of the libraries used:
```
python==3.8.5
spyder==5.1.5
ipython==7.29.0
torch==1.10.0+cu113
torch_geometric==2.0.2
```
The OS is Ubuntu 18.04.6 LTS X64.

May I ask the cause of this problem? Thanks a lot!

**Comment by steff456** [comment]
Hi @jajupmochi,

Can you let me know how did you install `torch_geometric` and Spyder?

**Comment by jajupmochi** [comment]
Hi @steff456,

`Spyder` is installed by
```
sudo python3 -m pip install spyder
```
`torch_geometric` is installed by
```
sudo python3 -m pip install pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
```

**Comment by steff456** [comment]
Can you try in a new environment to install everything from the conda forge channel?

```
conda create env -n test python=3.8 -c conda-forge
conda activate test
conda install -c conda-forge spyder torch-scater ...
```

Let me know if the error persists.

**Comment by jajupmochi** [comment]
Thanks, @steff456. I tried your code and there is a new problem. When I run `spyder`, it shows
```
bash: $PATH/bin/spyder: $PATH/: bad interpreter: No such file or directory
```
I was always using pip, so it may be better if it works with pip.

**Comment by steff456** [comment]
It seems you are using the operating system python rather than a isolated distribution of python. When you use pip it is probably working because it is adding everything you install to the path, the issue for us with this type of installation is that a lot of things may break because we are not sure of what have you installed and hence is interfering in the path. 

When working in Linux or macOS we try to avoid using the python of the system because it can also break some functionality of the operating system. My recommendation is to clean the system path, which I think the easiest way is to format and reinstall Linux, and never use the python of the system again, aka when you use `sudo python3`. Then, you can install a distribution of anaconda, and add that new python to the path. In this way, everytime you write `python` in the console you should see that it is using anaconda's one and not the system one.

Sorry for not having an easier fix, that's why we recommend to use anaconda always.

**Comment by ccordoba12** [comment]
Closing because we can only give support to conda users, sorry.

**Comment by jajupmochi** [comment]
@steff456 Thank you for your advice. I retried to import the library after a day, and it works!

I don't know what happened, as I did not change anything. Thank you anyway for your time.
