### ISSUE TITLE
Crash on open File with Cryptomator

### ISSUE THREAD

**Issue by muxxxxxxx** [spyder-ide/spyder#16752]
### What steps will reproduce the problem?

Used latest Cryptomator with WinFSP via the FUSE Option to mount my Data. Tried to open File from the mounted Drive in Spyder 5.0.5. -> Spyder crashed. Same on Win 11 and Win 10

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\ntpath.py", line 647, in realpath
    path = _getfinalpathname(path)
OSError: [WinError 1005] Auf dem Datenträger befindet sich kein erkanntes Dateisystem.
Stellen Sie sicher, dass alle benötigten Dateisystemtreiber geladen sind und dass der Datenträger nicht beschädigt ist: 'E:\\stock\\getData.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 2189, in load
    current_editor = self.set_current_filename(filename,
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 1719, in set_current_filename
    return editorstack.set_current_filename(filename, focus)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1512, in set_current_filename
    index = self.has_filename(filename)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1501, in has_filename
    if fixpath(filename) == fixpath(finfo.filename):
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1499, in <lambda>
    fixpath = lambda path: osp.normcase(osp.realpath(path))
  File "C:\Users\user\anaconda3\lib\ntpath.py", line 651, in realpath
    path = _getfinalpathname_nonstrict(path)
  File "C:\Users\user\anaconda3\lib\ntpath.py", line 601, in _getfinalpathname_nonstrict
    path = _getfinalpathname(path)
OSError: [WinError 1005] Auf dem Datenträger befindet sich kein erkanntes Dateisystem.
Stellen Sie sicher, dass alle benötigten Dateisystemtreiber geladen sind und dass der Datenträger nicht beschädigt ist: 'E:\\stock\\getData.py'
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.8.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.27.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=1.0                  :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  1.21.3 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @muxxxxxxx, thanks for reporting. Please update to our latest version (5.1.5) and try again. Your error could be fixed there.

Here you can find the instructions on how to do that in Anaconda:

https://stackoverflow.com/questions/69704561/cannot-update-spyder-5-1-5-on-new-anaconda-install

**Comment by ccordoba12** [comment]
Let us know if it works for you.

**Comment by muxxxxxxx** [comment]
@ccordoba12 
Hi, yes it's the same with the newest version. I uploaded it here:
https://github.com/spyder-ide/spyder/issues/16767

If i switch to dokany or webdav in Cryptomator it works. It just crashes with WinFSP. In other Programs like Word, Notepad, Explorer everything works fine. It's just Spyder

**Comment by ccordoba12** [comment]
Ok, thanks for confirming that this is still an error. However, this could take us several months to fix because we have a huge backlog of things to do and this is a very narrow problem (i.e. it affects the few people in your situation).

**Comment by revetuzo** [comment]
Hi all,
I'd just like to draw some attention again to this issue, which persists with Spyder 5.2.2 (Python 3.9.13 64-bit | Qt 5.9.7 | PyQt5 5.9.2 | Windows 10). Now that Boxcryptor is gone, Cryptomator might be a viable solution for more and more privacy enthusiasts.
Cheers!

**Comment by ccordoba12** [comment]
@revetuzo, please update to our latest version (5.4.3) and try again. This problem could have been solved in that version.

**Comment by hoanthanhnguyen** [comment]
Thanks @ccordoba12. I switch to volume type wedav (previously FUSE) in Cryptomator and it works.
