### ISSUE TITLE
Error while writing to Spyder preferences/files located in the Spyder preferences directory

### ISSUE THREAD

**Issue by tech0881** [spyder-ide/spyder#16768]
### What steps will reproduce the problem?

helpggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg

### Traceback
```python-traceback
  File "C:\Users\jayla\anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 164, in lock
    symlink(str(os.getpid()), self.name)
  File "C:\Users\jayla\anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 96, in symlink
    rename(newlinkname, filename)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\jayla\\.spyder-py3\\spyder.lock.1636326945311.newlink' -> 'C:\\Users\\jayla\\.spyder-py3\\spyder.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jayla\anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 191, in lock
    kill(int(pid), 0)
  File "C:\Users\jayla\anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 80, in kill
    raise OSError(errno.ESRCH, None)
ProcessLookupError: [Errno 3] None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jayla\anaconda3\lib\site-packages\spyder\app\start.py", line 181, in main
    lock_created = lock.lock()
  File "C:\Users\jayla\anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 199, in lock
    rmlink(self.name)
  File "C:\Users\jayla\anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 121, in rmlink
    os.remove(os.path.join(filename, 'symlink'))
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\jayla\\.spyder-py3\\spyder.lock\\symlink'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jayla\anaconda3\lib\site-packages\IPython\core\history.py", line 543, in __init__
    self.new_session()
  File "C:\Users\jayla\anaconda3\lib\site-packages\decorator.py", line 231, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\jayla\anaconda3\lib\site-packages\IPython\core\history.py", line 58, in needs_sqlite
    return f(self, *a, **kw)
  File "C:\Users\jayla\anaconda3\lib\site-packages\IPython\core\history.py", line 568, in new_session
    cur = conn.execute("""INSERT INTO sessions VALUES (NULL, ?, NULL,
sqlite3.OperationalError: attempt to write a readonly database
WARNING:traitlets:kernel died: 25.012027978897095

[WinError 5] Access is denied: 'C:\\Users\\jayla\\.spyder-py3\\config\\spyder.ini'
Failed to write user configuration file to disk, with the exception shown below
[WinError 5] Access is denied: 'C:\\Users\\jayla\\.spyder-py3\\config\\spyder.ini'
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest'}}
```

## Versions

* Spyder version: 4.2.5 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.22.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  4.0.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.23 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.20.1 (OK)
pandas >=1.1.1                  :  1.2.4 (OK)
scipy >=0.17.0                  :  1.6.2 (OK)
sympy >=0.7.3                   :  1.8 (OK)
```

**Comment by steff456** [comment]
Hi @tech0881,

What were you doing when this error popped?

**Comment by tech0881** [comment]
I was writing a code for my tech class.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by steff456** [comment]
How did you installed Spyder?

**Comment by tech0881** [comment]
I downloaded Spyder from Microsoft Edge

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mrclary** [comment]
@tech0881, It may be that some of your configuration files have been corrupted. Try quitting all instances of Spyder, then rename 'C:\Users\jayla\.spyder-py3' to 'C:\Users\jayla\.spyder-py3.bak'. I also recommend installing our latest version using our Windows installer: https://github.com/spyder-ide/spyder/releases/tag/v5.2.0

**Comment by ccordoba12** [comment]
Closing because this is too old now.
