### ISSUE TITLE
_kill_kernel changed in jupyter_clients 7.0.6

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#16762]
### What steps will reproduce the problem?

close spyder

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/jupyter_client/manager.py", line 380, in _async_finish_shutdown
    await asyncio.wait_for(
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 498, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/jupyter_client/utils.py", line 26, in wrapped
    raise e
  File "/usr/local/lib/python3.8/site-packages/jupyter_client/utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "/usr/local/lib/python3.8/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.8/site-packages/jupyter_client/manager.py", line 443, in _async_shutdown_kernel
    await ensure_async(self.finish_shutdown(restart=restart))
  File "/usr/local/lib/python3.8/site-packages/jupyter_client/utils.py", line 26, in wrapped
    raise e
  File "/usr/local/lib/python3.8/site-packages/jupyter_client/utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "/usr/local/lib/python3.8/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.8/site-packages/jupyter_client/manager.py", line 386, in _async_finish_shutdown
    await ensure_async(self._kill_kernel(restart=restart))
TypeError: _kill_kernel() got an unexpected keyword argument 'restart'
```

## Versions

* Spyder version: 6.0.0.dev0 a84c40648
* Python version: 3.8.6
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Darwin 20.6.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7              :  0.2.1 (OK)
atomicwrites >=1.2.0                   :  1.4.0 (OK)
chardet >=2.0.0                        :  3.0.4 (OK)
cloudpickle >=0.5.0                    :  2.0.0 (OK)
cookiecutter >=1.6.0                   :  1.7.2 (OK)
diff_match_patch >=20181111            :  20200713 (OK)
intervaltree >=3.0.2                   :  3.1.0 (OK)
IPython >=7.6.0                        :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0                  :  0.18.0 (OK)
jellyfish >=0.7                        :  None (OK)
jsonschema >=3.2.0                     :  3.2.0 (OK)
keyring >=17.0.0                       :  21.4.0 (OK)
nbconvert >=4.0                        :  6.0.7 (OK)
numpydoc >=0.6.0                       :  1.1.0 (OK)
parso >=0.7.0;<0.9.0                   :  0.8.2 (OK)
pexpect >=4.4.0                        :  4.8.0 (OK)
pickleshare >=0.4                      :  0.7.5 (OK)
psutil >=5.3                           :  5.7.2 (OK)
pygments >=2.0                         :  2.10.0 (OK)
pylint >=2.5.0                         :  2.6.0 (OK)
pyls_spyder >=0.4.0                    :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0                   :  1.1.0 (NOK)
pylsp_black >=1.0.0                    :  None (OK)
qdarkstyle =3.0.2                      :  3.0.2 (OK)
qstylizer >=0.1.10                     :  0.1.10 (OK)
qtawesome >=1.0.2                      :  1.0.2 (OK)
qtconsole >=5.1.0                      :  5.2.0.dev0 (OK)
qtpy >=1.5.0                           :  1.9.0 (OK)
rtree >=0.9.7                          :  None (OK)
setuptools >=49.6.0                    :  50.3.0 (OK)
sphinx >=0.6.6                         :  3.2.1 (OK)
spyder_kernels >=2.1.1;<2.2.0          :  2.2.0.dev0 (OK)
textdistance >=4.2.0                   :  4.2.0 (OK)
three_merge >=0.1.1                    :  0.1.1 (OK)
watchdog >=0.10.3                      :  0.10.3 (OK)
zmq >=17                               :  22.3.0 (OK)

# Optional:
cython >=0.21                          :  0.29.21 (OK)
matplotlib >=2.0.0                     :  3.4.2 (OK)
numpy >=1.7                            :  1.21.0 (OK)
pandas >=1.1.1                         :  1.1.3 (OK)
scipy >=0.17.0                         :  1.5.2 (OK)
sympy >=0.7.3                          :  1.6.2 (OK)

# Spyder plugins:
spyder_boilerplate.spyder.plugin 0.0.1 :  0.0.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @impact27, this is being worked out in PR #16644, which is ready to be merged as soon as the Jupyter guys address some issues with slow to restart kernels. For now you need to use jupyter_client 6.
