### ISSUE TITLE
spyder on python 3.10

### ISSUE THREAD

**Issue by mehedi02** [spyder-ide/spyder#16797]
## Description

**What steps will reproduce the problem?**

1. install python 3.10
2. pip install spyder
3. spyder3

**What is the expected output? What do you see instead?**
launch spyder

**Please provide any additional information below**

  File "C:\Users\mehed\AppData\Local\Programs\Python\Python310\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 1524, in viewportEvent
    self.edge_line.setGeometry(QRect(x, cr.top(), 1, cr.bottom()))
TypeError:   QRect(QRect): argument 1 has unexpected type 'float'
Traceback (most recent call last):
  File "C:\Users\mehed\AppData\Local\Programs\Python\Python310\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 1524, in viewportEvent
    self.edge_line.setGeometry(QRect(x, cr.top(), 1, cr.bottom()))
TypeError:   QRect(QRect): argument 1 has unexpected type 'float'
Traceback (most recent call last):
  File "C:\Users\mehed\AppData\Local\Programs\Python\Python310\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 1524, in viewportEvent
    self.edge_line.setGeometry(QRect(x, cr.top(), 1, cr.bottom()))
TypeError:   QRect(QRect): argument 1 has unexpected type 'float'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.10.0
* Qt Versions: 5.15.2, PyQt5 5.15.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  2.4.0 (OK)
pycodestyle >=2.3:  2.8.0 (OK)
pygments >=2.0   :  2.10.0 (OK)
pandas >=0.13.1  :  1.3.4 (OK)
numpy >=1.7      :  1.21.3 (OK)
sphinx >=0.6.6   :  4.2.0 (OK)
rope >=0.9.4     :  0.21.0 (OK)
jedi >=0.9.0     :  0.18.0 (OK)

```

**Comment by dalthviz** [comment]
Hi @mehedi02 thank you for your feedback! Could you try to update to Spyder 5.0.5 and try again? Let us know if that helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
