### ISSUE TITLE
Spyder 5.1.5 crashes when starting - KeyError 'workspace' in projects\plugin.py

### ISSUE THREAD

**Issue by selahlynch** [spyder-ide/spyder#16802]
## Problem Description
When I attempt to open Spyder it crashes.  I attempted creating a new conda environment and installing from scratch.  Same issue.
I've recently started actively using projects, whereas I never did before.  I wonder if that has something to do with it?

### Paste Traceback/Error Below (if applicable)
```python-traceback
(spydertest) C:\Users\LynchSe>spyder
link image0 hasn't been detected!
Traceback (most recent call last):
  File "C:\Users\LynchSe\Miniconda3\envs\spydertest\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\LynchSe\Miniconda3\envs\spydertest\lib\site-packages\spyder\app\start.py", line 237, in main
    mainwindow.main(options, args)
  File "C:\Users\LynchSe\Miniconda3\envs\spydertest\lib\site-packages\spyder\app\mainwindow.py", line 1992, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "C:\Users\LynchSe\Miniconda3\envs\spydertest\lib\site-packages\spyder\app\utils.py", line 292, in create_window
    main.post_visible_setup()
  File "C:\Users\LynchSe\Miniconda3\envs\spydertest\lib\site-packages\spyder\app\mainwindow.py", line 1222, in post_visible_setup
    self.projects.reopen_last_project()
  File "C:\Users\LynchSe\Miniconda3\envs\spydertest\lib\site-packages\spyder\plugins\projects\plugin.py", line 578, in reopen_last_project
    self.open_project(path=current_project_path,
  File "C:\Users\LynchSe\Miniconda3\envs\spydertest\lib\site-packages\spyder\plugins\projects\plugin.py", line 433, in open_project
    project_type_class = self._load_project_type_class(path)
  File "C:\Users\LynchSe\Miniconda3\envs\spydertest\lib\site-packages\spyder\plugins\projects\plugin.py", line 865, in _load_project_type_class
    project_type_id = config[WORKSPACE].get(
  File "C:\Users\LynchSe\Miniconda3\envs\spydertest\lib\configparser.py", line 963, in __getitem__
    raise KeyError(key)
KeyError: 'workspace'
```

## Versions
* Spyder version: 5.1.5
* Python version: 3.9.7
* Qt version: 5.9.7
* PyQt version:  5.9.2
* Operating System name/version:  Windows 10 Enterprise

**Comment by selahlynch** [comment]
I discovered and used the spyder --reset command and that seems to have fixed the issue on all of my conda environments.  Let me know if there is any useful info I can provide.  Otherwise feel free to close.  Thanks!

**Comment by ccordoba12** [comment]
Hey @selahlynch, thanks for reporting. That was what I was about to suggest you to run. Glad you find it by yourself!
