### ISSUE TITLE
Issue reporter pops up when using matplotlib

### ISSUE THREAD

**Issue by cahege** [spyder-ide/spyder#16840]
I am running an optimization model using CPLEX from IBM. Here I run the optimization issue and check all the intermediate solutions, so the model produces a lot of results and thus takes several hours to run. However, it seems to work fine. However, after producing all my solutions, I import matplotlib and try to plt some of my results. This is where I get the bug from the Issue repporter. See details below. Any help on this issue is highly appriciated.

Thanks!

--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\cahege\Anaconda3\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\cahege\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\cahege\Anaconda3\lib\site-packages\spyder\app\start.py", line 214, in main
    mainwindow.main(options, args)
  File "C:\Users\cahege\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2293, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\cahege\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2192, in create_window
    app.exec_()
  File "C:\Users\cahege\Anaconda3\lib\site-packages\qtconsole\manager.py", line 27, in poll
    super().poll()
  File "C:\Users\cahege\Anaconda3\lib\site-packages\jupyter_client\restarter.py", line 116, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "C:\Users\cahege\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 510, in restart_kernel
    self.start_kernel(**self._launch_args)
  File "C:\Users\cahege\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 342, in start_kernel
    self.post_start_kernel(**kw)
  File "C:\Users\cahege\Anaconda3\lib\site-packages\qtconsole\manager.py", line 62, in post_start_kernel
    self.kernel_restarted.emit()
  File "C:\Users\cahege\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 786, in _handle_kernel_restarted
    super(ShellWidget, self)._handle_kernel_restarted()
  File "C:\Users\cahege\Anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 530, in _handle_kernel_restarted
    self.log.warning("kernel restarted")
Message: 'kernel restarted'
Arguments: ()

**Comment by dalthviz** [comment]
Hi @cahege thank you for the feedback. What is your Spyder version? Could you try to update to at least Spyder 5.0.5 and check again? Let us know if updating helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
