### ISSUE TITLE
Changing a setting (removing vertical line at line limit) causes an internal problem

### ISSUE THREAD

**Issue by ArielAvshalom** [spyder-ide/spyder#16886]
### What steps will reproduce the problem?

I'm running this on a 2019 Intel MacBook Pro. 
The steps to reproduce this problem are to go to:
Settings -> Completion and linting -> Code style and formatting -> Line length -> Show vertical line at that length

unchecking the option and clicking apply/ok.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/Users/arielavshalom/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/plugin.py", line 408, in _rpc_call
    meth(*args, **kwargs)
  File "/Users/arielavshalom/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/plugin.py", line 1604, in call_all_editorstacks
    method(*args, **kwargs)
  File "/Users/arielavshalom/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/editor.py", line 954, in set_edgeline_enabled
    finfo.editor.edge_line.set_enabled(state)
  File "/Users/arielavshalom/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/panels/edgeline.py", line 52, in set_enabled
    self.setVisible(state)
  File "/Users/arielavshalom/opt/anaconda3/lib/python3.7/site-packages/spyder/api/panel.py", line 168, in setVisible
    super(Panel, self).setVisible(visible)
TypeError: setVisible(self, bool): argument 1 has unexpected type 'tuple'
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 21.1.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.27.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=1.0                  :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.21.2 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by steff456** [comment]
Hi @ArielAvshalom, 

Can you please update to our latest release 5.1.5 to see if this keeps happening?

**Comment by ArielAvshalom** [comment]
Hi Stephanie,

I updated conda to get Spyder 5.1.5 and now I can’t open Spyder.

**Comment by ArielAvshalom** [comment]
NVM,

Fixedby force downloading Python.app

The error I posted to GitHub got fixed with the update. It can be closed now, thank you.

**Comment by steff456** [comment]
Great! I'll close this issue now. 

Thanks for reporting!
