### ISSUE TITLE
spyder 5.1.5 crash when the project name has chinese character

### ISSUE THREAD

**Issue by dovsay** [spyder-ide/spyder#16880]
## Problem Description
If there are Chinese characters in the name of the newly created project, it can be run at that time and no problem occurs. However, when spyder is running again, the interface is opened and it flashes immediately. I had to spyder --reset to use it.
Run spyder in the anaconda prompt to track the error, and found that the error is as follows:

-----------------------------------------
(base) C:\Users\macbook>spyder
link image0 hasn't been detected!
Traceback (most recent call last):
  File "C:\Users\macbook\anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\macbook\anaconda3\lib\site-packages\spyder\app\start.py", line 237, in main
    mainwindow.main(options, args)
  File "C:\Users\macbook\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1992, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "C:\Users\macbook\anaconda3\lib\site-packages\spyder\app\utils.py", line 292, in create_window
    main.post_visible_setup()
  File "C:\Users\macbook\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1222, in post_visible_setup
    self.projects.reopen_last_project()
  File "C:\Users\macbook\anaconda3\lib\site-packages\spyder\plugins\projects\plugin.py", line 578, in reopen_last_project
    self.open_project(path=current_project_path,
  File "C:\Users\macbook\anaconda3\lib\site-packages\spyder\plugins\projects\plugin.py", line 433, in open_project
    project_type_class = self._load_project_type_class(path)
  File "C:\Users\macbook\anaconda3\lib\site-packages\spyder\plugins\projects\plugin.py", line 864, in _load_project_type_class
    config.read(fpath)
  File "C:\Users\macbook\anaconda3\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "C:\Users\macbook\anaconda3\lib\configparser.py", line 1020, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 180: illegal multibyte sequence
-------------------------

In order to be able to use spyder 5.1.5, I modified the read function in the file configparser.py,
Modify encoding=None to encoding='utf-8'
Now it can be used normally.
Hope to fix this problem

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.1.5
* Python version: 3.9.7
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @dovsay, thanks for reporting. This problem will be fixed in our next version (5.2.0), to be released next week.
