### ISSUE TITLE
Edited Markdown (or Latex) in Python Comment 

### ISSUE THREAD

**Issue by norbmett** [spyder-ide/spyder#16891]
### What steps will reproduce the problem?

Attempted to edit a comment which included 'resolved Markdown' (copied from Jupyter with UTF-8 byte sequence - pretty cool Spyder allows these at all):
# ∀𝑔∈{0,1,…,20} 𝑠∈{'GP','MS'} .
Wanted to change it to:

# ∀n∈{0,1,…,10}

But as soon as I attempted to replace the first subscript \g with \\n (Note: not really sure how I do Markdown on Latex/Markdown style equation "g" and "n") received the internal problem.

### Traceback
```python-traceback
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\syntaxhighlighters.py", line 319, in highlightBlock
    self.highlight_block(text)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\syntaxhighlighters.py", line 645, in highlight_block
    self.setFormat(0, qstring_length(text), self.formats["normal"])
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\qstringhelpers.py", line 19, in qstring_length
    utf16_text = text.encode('utf16')
UnicodeEncodeError: 'utf-16' codec can't encode character '\udc54' in position 7: surrogates not allowed
Traceback (most recent call last):
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 201, in encode
    return text.encode(coding), coding
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc54' in position 15428: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 135, in do_autosave
    stack.autosave.autosave_all()
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 417, in autosave_all
    self.maybe_autosave(index)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 386, in maybe_autosave
    self.autosave(finfo)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 405, in autosave
    self.stack._write_to_file(finfo, autosave_filename)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2005, in _write_to_file
    fileinfo.encoding = encoding.write(txt, filename, fileinfo.encoding)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 236, in write
    text, encoding = encode(text, encoding)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 203, in encode
    raise RuntimeError("Incorrect encoding (%s)" % coding)
RuntimeError: Incorrect encoding (utf-8)
Traceback (most recent call last):
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 201, in encode
    return text.encode(coding), coding
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc54' in position 15428: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 2141, in save
    return editorstack.save(index=index, force=force)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2060, in save
    self._save_file(finfo, index)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2075, in _save_file
    self._write_to_file(finfo, finfo.filename)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2005, in _write_to_file
    fileinfo.encoding = encoding.write(txt, filename, fileinfo.encoding)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 236, in write
    text, encoding = encode(text, encoding)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 203, in encode
    raise RuntimeError("Incorrect encoding (%s)" % coding)
RuntimeError: Incorrect encoding (utf-8)
Traceback (most recent call last):
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 201, in encode
    return text.encode(coding), coding
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc54' in position 15428: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 2141, in save
    return editorstack.save(index=index, force=force)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2060, in save
    self._save_file(finfo, index)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2075, in _save_file
    self._write_to_file(finfo, finfo.filename)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2005, in _write_to_file
    fileinfo.encoding = encoding.write(txt, filename, fileinfo.encoding)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 236, in write
    text, encoding = encode(text, encoding)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 203, in encode
    raise RuntimeError("Incorrect encoding (%s)" % coding)
RuntimeError: Incorrect encoding (utf-8)
Traceback (most recent call last):
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 201, in encode
    return text.encode(coding), coding
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc54' in position 15428: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 2141, in save
    return editorstack.save(index=index, force=force)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2060, in save
    self._save_file(finfo, index)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2075, in _save_file
    self._write_to_file(finfo, finfo.filename)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2005, in _write_to_file
    fileinfo.encoding = encoding.write(txt, filename, fileinfo.encoding)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 236, in write
    text, encoding = encode(text, encoding)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 203, in encode
    raise RuntimeError("Incorrect encoding (%s)" % coding)
RuntimeError: Incorrect encoding (utf-8)
Traceback (most recent call last):
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 201, in encode
    return text.encode(coding), coding
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc54' in position 15428: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 2141, in save
    return editorstack.save(index=index, force=force)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2060, in save
    self._save_file(finfo, index)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2075, in _save_file
    self._write_to_file(finfo, finfo.filename)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2005, in _write_to_file
    fileinfo.encoding = encoding.write(txt, filename, fileinfo.encoding)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 236, in write
    text, encoding = encode(text, encoding)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 203, in encode
    raise RuntimeError("Incorrect encoding (%s)" % coding)
RuntimeError: Incorrect encoding (utf-8)
Traceback (most recent call last):
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 201, in encode
    return text.encode(coding), coding
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc54' in position 15428: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 2141, in save
    return editorstack.save(index=index, force=force)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2060, in save
    self._save_file(finfo, index)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2075, in _save_file
    self._write_to_file(finfo, finfo.filename)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2005, in _write_to_file
    fileinfo.encoding = encoding.write(txt, filename, fileinfo.encoding)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 236, in write
    text, encoding = encode(text, encoding)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 203, in encode
    raise RuntimeError("Incorrect encoding (%s)" % coding)
RuntimeError: Incorrect encoding (utf-8)
Traceback (most recent call last):
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\syntaxhighlighters.py", line 319, in highlightBlock
    self.highlight_block(text)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\syntaxhighlighters.py", line 645, in highlight_block
    self.setFormat(0, qstring_length(text), self.formats["normal"])
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\qstringhelpers.py", line 19, in qstring_length
    utf16_text = text.encode('utf16')
UnicodeEncodeError: 'utf-16' codec can't encode character '\udc54' in position 7: surrogates not allowed
Traceback (most recent call last):
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 201, in encode
    return text.encode(coding), coding
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc54' in position 15519: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 2141, in save
    return editorstack.save(index=index, force=force)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2037, in save
    return self.save_as(index=index)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2204, in save_as
    ok = self.save(index=new_index, force=True)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2060, in save
    self._save_file(finfo, index)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2075, in _save_file
    self._write_to_file(finfo, finfo.filename)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2005, in _write_to_file
    fileinfo.encoding = encoding.write(txt, filename, fileinfo.encoding)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 236, in write
    text, encoding = encode(text, encoding)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\utils\encoding.py", line 203, in encode
    raise RuntimeError("Incorrect encoding (%s)" % coding)
RuntimeError: Incorrect encoding (utf-8)
```

## Versions

* Spyder version: 4.2.5 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.22.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  4.0.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.23 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.20.1 (OK)
pandas >=1.1.1                  :  1.2.4 (OK)
scipy >=0.17.0                  :  1.6.2 (OK)
sympy >=0.7.3                   :  1.8 (OK)
```

**Comment by dalthviz** [comment]
Hi @norbmett thank you for the feedback! Could it be possible for you to post here and example file with the python comment that is causing this for you? I was not able to reproduce this with the strings you posted here. Also, to input the special characters in the editor, are you using something or somehow copy-pasting the characters? Let us know!

**Comment by dalthviz** [comment]
Closing due to lack of response
