### ISSUE TITLE
Mac app crashes when openning Spyder version 5.2.0

### ISSUE THREAD

**Issue by Haybu** [spyder-ide/spyder#16898]
### What steps will reproduce the problem?

upgraded to latest versio of spyder version 5, it crashes everytime I opened it on my mac.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/Applications/Spyder.app/Contents/Resources/__boot__.py", line 106, in <module>
    _run()
  File "/Applications/Spyder.app/Contents/Resources/__boot__.py", line 84, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Applications/Spyder.app/Contents/Resources/Spyder.py", line 3, in <module>
    start.main()
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/app/start.py", line 250, in main
    mainwindow.main(options, args)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/app/mainwindow.py", line 2036, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/app/utils.py", line 308, in create_window
    CONF.notify_all_observers()
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/config/manager.py", line 301, in notify_all_observers
    self.notify_section_all_observers(section)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/config/manager.py", line 378, in notify_section_all_observers
    self.notify_observers(section, option)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/config/manager.py", line 347, in notify_observers
    self._notify_option(section, option, value)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/config/manager.py", line 358, in _notify_option
    observer.on_configuration_change(option, section, value)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/api/config/mixins.py", line 351, in on_configuration_change
    method(value)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/ipythonconsole/widgets/main_widget.py", line 745, in change_clients_autocall
    self._change_client_conf(
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/ipythonconsole/widgets/main_widget.py", line 892, in _change_client_conf
    client_conf_func(value)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/ipythonconsole/widgets/shell.py", line 407, in set_autocall
    self.execute(cmd.format(autocall), hidden=True)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/ipythonconsole/widgets/shell.py", line 257, in execute
    super(ShellWidget, self).execute(source, hidden, interactive)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/ipythonconsole/widgets/debugging.py", line 569, in execute
    return super(DebuggingWidget, self).execute(
  File "qtconsole/console_widget.pyc", line 647, in execute
  File "qtconsole/frontend_widget.pyc", line 285, in _execute
AttributeError: 'NoneType' object has no attribute 'execute'
```

## Versions

* Spyder version: 5.2.0 
* Python version: 3.9.5
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Darwin 21.1.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.8.9 (OK)
jsonschema >=3.2.0            :  4.2.1 (OK)
keyring >=17.0.0              :  23.2.1 (OK)
nbconvert >=4.0               :  6.3.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0                :  2.11.1 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.1;<1.4.0          :  1.3.1 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.0 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.1 (OK)
qtpy >=1.5.0                  :  1.11.2 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  59.2.0 (OK)
sphinx >=0.6.6                :  4.3.0 (OK)
spyder_kernels >=2.2.0;<2.3.0 :  2.2.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.5.0 (OK)
numpy >=1.7                   :  1.21.4 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by Haybu** [comment]
version 5.2.0 keeps on crashes and never comes up successfully.

**Comment by ccordoba12** [comment]
Hey @Haybu, thanks for reporting. This was flagged incorrectly by our bot, sorry.

Please open `Terminal` and run the following command:

    rm -Rf ~/.spyder-py3

That should solve the problem until we can fix it in our side. And please don't set the `autocall` option for now in our preferences.

**Comment by Haybu** [comment]
Thanks @ccordoba12 I removed `~/.spyder-py3` many times to go around the problem, however, a restart crashes too.

**Comment by ccordoba12** [comment]
But is the IPython console working for you or not? Could you post a screenshot of how Spyder looks for you to check? Please hide the error dialog from it.

**Comment by thluDK** [comment]
Same happens for 5.2.0 @ Windows. 
When starting Spyder from shortcut, main window opens and Issue reporter flashes briefly before both closes.

When starting manually in a console, Issue reporter stays open and shows same error as in top post. 

What is the windows equivalent for `~/.spyder-py3` ?

**Comment by rhkarls** [comment]
> What is the windows equivalent for `~/.spyder-py3` ?

`%userprofile%\.spyder-py3` (will delete all your spyder settings)

I'm running 5.2.0 from installer fine so far on Windows 10 Pro 1909, did not reset settings.

**Comment by thluDK** [comment]
Problem appears when I set a Python interpreter that has an older version of module spyder-kernels

After running `pip install spyder-kernels==2.2.*` in my environment, Spyder can start _and_ restart. And I can use my original  `%userprofile%\.spyder-py3` folder again. 

Steps to reproduce problem:
- Set interpreter to environment having spyder-kernels==2.1.*
- Spyder will crash when restarted
- Run `pip install spyder-kernels==2.2.*` in environment
- Spyder starts
