### ISSUE TITLE
Installing module

### ISSUE THREAD

**Issue by BlauPuppiez** [spyder-ide/spyder#16923]
### What steps will reproduce the problem?

Installed miniconda
installed dlib in miniconda with: conda install -c menpo dlib
could not 'import dlib' in Spyder
then ran: conda install spyder-kernels=2.1
as told by the kernel in spyder
Attempted to close the kernel and this issue reported popped up

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\siuhu\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1746, in close_client
    client.shutdown(last_client)
  File "C:\Users\siuhu\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\client.py", line 585, in shutdown
    self.shellwidget.shutdown(shutdown_kernel)
  File "C:\Users\siuhu\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\shell.py", line 176, in shutdown
    self.kernel_manager.stop_restarter()
AttributeError: 'NoneType' object has no attribute 'stop_restarter'
```

## Versions

* Spyder version: 5.2.0 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.8.9 (OK)
jsonschema >=3.2.0            :  4.2.1 (OK)
keyring >=17.0.0              :  23.2.1 (OK)
nbconvert >=4.0               :  6.3.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.8.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0                :  2.11.1 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.1;<1.4.0          :  1.3.1 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.0 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.1 (OK)
qtpy >=1.5.0                  :  1.11.2 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  59.2.0 (OK)
sphinx >=0.6.6                :  4.3.0 (OK)
spyder_kernels >=2.2.0;<2.3.0 :  2.2.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.5.0 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by dalthviz** [comment]
Hi @BlauPuppiez thanks for the feedback with Spyder 5.2.0 you need to install in the env of your custom interpreter `spyder-kernels` 2.2.0 (there was an issue with the kernel message and some validations in the IPython Console when a kernel can't be started. The issues were resolved by https://github.com/spyder-ide/spyder/pull/16895 available in the next release we do). 

Could you install `spyder-kernels` 2.2.0 and try again?

Let us know if that helps!

**Comment by BlauPuppiez** [comment]
Hi there,

I've reinstalled Spyder since it wouldn't start up again, and I've found another method to use the library. Unfortunately I haven't tried the method you have mentioned.

Kind regards
________________________________
