### ISSUE TITLE
Creating a project causee an internal error..

### ISSUE THREAD

**Issue by richlysakowski** [spyder-ide/spyder#16936]
### What steps will reproduce the problem?

I was trying to create a Spyder Project from inside Spyder, using the "Projects" menu.

I used the "Existing Folder" option, and this dialog box message appeared. 

### Traceback
```python-traceback
--- Logging error ---
Traceback (most recent call last):
  File "C:\ProgramData\WPy64-3940\python-3.9.4.amd64\lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\ProgramData\WPy64-3940\python-3.9.4.amd64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\WPy64-3940\python-3.9.4.amd64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\WPy64-3940\python-3.9.4.amd64\scripts\spyder.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\ProgramData\WPy64-3940\python-3.9.4.amd64\lib\site-packages\spyder\app\start.py", line 213, in main
    mainwindow.main(options, args)
  File "C:\ProgramData\WPy64-3940\python-3.9.4.amd64\lib\site-packages\spyder\app\mainwindow.py", line 2311, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\ProgramData\WPy64-3940\python-3.9.4.amd64\lib\site-packages\spyder\app\mainwindow.py", line 2207, in create_window
    app.exec_()
  File "C:\ProgramData\WPy64-3940\python-3.9.4.amd64\lib\site-packages\qtconsole\frontend_widget.py", line 518, in _handle_kernel_died
    self.log.warning("kernel died: %s", since_last_heartbeat)
Message: 'kernel died: %s'
Arguments: (25.00000023841858,)
```

## Versions

* Spyder version: 5.0.1 
* Python version: 3.9.4
* Qt version: 5.15.1
* PyQt5 version: 5.15.1
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.10.0.dev0 (OK)
setuptools >=39.0.0           :  56.0.0 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.20.2 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by dalthviz** [comment]
Hi @richlysakowski thank you for the feedback. Could you update to at least 5.0.5 and check again? Let us know!

**Comment by dalthviz** [comment]
Closing due to lack of response
