### ISSUE TITLE
CodingPracticee

### ISSUE THREAD

**Issue by NeeceTheGeek** [spyder-ide/spyder#16942]
### What steps will reproduce the problem?

Write practice code from the notes in class so that we have something to look back on for the future. 

### Traceback
```python-traceback
  File "C:\Users\16672\anaconda3\lib\site-packages\spyder\plugins\projects\plugin.py", line 285, in _create_project
    self.open_project(path=path)
  File "C:\Users\16672\anaconda3\lib\site-packages\spyder\plugins\projects\plugin.py", line 326, in open_project
    project = EmptyProject(path)
  File "C:\Users\16672\anaconda3\lib\site-packages\spyder\plugins\projects\projecttypes\__init__.py", line 41, in __init__
    self.config = ProjectMultiConfig(
  File "C:\Users\16672\anaconda3\lib\site-packages\spyder\config\user.py", line 782, in __init__
    self._configs_map[name] = config_class(**new_kwargs)
  File "C:\Users\16672\anaconda3\lib\site-packages\spyder\config\user.py", line 188, in __init__
    super(UserConfig, self).__init__(name=name, path=path)
  File "C:\Users\16672\anaconda3\lib\site-packages\spyder\config\user.py", line 60, in __init__
    os.makedirs(osp.dirname(self._path))
  File "C:\Users\16672\anaconda3\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\16672\anaconda3\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\16672\\CEIS 110: CodingNotes'
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest'}}
```

## Versions

* Spyder version: 4.2.5 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.22.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  4.0.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.23 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.20.1 (OK)
pandas >=1.1.1                  :  1.2.4 (OK)
scipy >=0.17.0                  :  1.6.2 (OK)
sympy >=0.7.3                   :  1.8 (OK)
```

**Comment by CAM-Gerlach** [comment]
Hey, sorry you ran into an an error! It looks like what happened is you entered a project name, `CEIS 110: CodingNotes` that is not a valid filename on your OS (Windows) due to containing a colon (`:`). To avoid this, make sure to enter a name without a colon (`:`) or other special characters.

Also, just FYI, you're using an old version of Spyder (4.2.5, released March 2021) that is no longer supported (5.2.0 is the latest version, 5.1.5 on Anaconda). I can confirm the traceback still occurs on modern Spyder.

I think we can do a much better job handling this, though. @ccordoba12 , for better UX, I suggest that we catch this error, produce an error dialog with an informative message, and return the user to the project creation dialog so they can correct it (we could attempt to validate it ourselves, but the rules vary by platform, and those for Windows are [relatively complex](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#naming-conventions)).

For reference, equivalent traceback on Spyder 5.1.5:

<details>

```python-traceback
Traceback (most recent call last):
  File "C:\Miniconda3\envs\spyder-clean\lib\site-packages\spyder\plugins\projects\plugin.py", line 379, in create_new_project
    self._create_project(root_path, project_type_id=project_type)
  File "C:\Miniconda3\envs\spyder-clean\lib\site-packages\spyder\plugins\projects\plugin.py", line 388, in _create_project
    project = project_type_class(
  File "C:\Miniconda3\envs\spyder-clean\lib\site-packages\spyder\plugins\projects\api.py", line 47, in __init__
    self.config = ProjectMultiConfig(
  File "C:\Miniconda3\envs\spyder-clean\lib\site-packages\spyder\config\user.py", line 786, in __init__
    self._configs_map[name] = config_class(**new_kwargs)
  File "C:\Miniconda3\envs\spyder-clean\lib\site-packages\spyder\config\user.py", line 188, in __init__
    super(UserConfig, self).__init__(name=name, path=path)
  File "C:\Miniconda3\envs\spyder-clean\lib\site-packages\spyder\config\user.py", line 60, in __init__
    os.makedirs(osp.dirname(self._path))
  File "C:\Miniconda3\envs\spyder-clean\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Miniconda3\envs\spyder-clean\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\C. A. M. Gerlach\\Test: Project'
```

</details>
