### ISSUE TITLE
Spyder5 failing to load on windows 10. Error: link image0 hasn't been detected!

### ISSUE THREAD

**Issue by L-F-S** [spyder-ide/spyder#16982]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Spyder 5 fails to even load and just freezes. When launching it from the anaconda prompt, the same happens, but I get an error message.

I then tried to conda upgrade --all, and now,
nothing happens at all, and spyder fails to launch, and I get a different, much shorter, error message. 
Please help me

### What steps reproduce the problem?

1.  Open spyder

### What is the expected output? What do you see instead?
Expected output: Spyder opens.

### Paste Traceback/Error Below (if applicable)

BEFORE UPGRADE (spyder 5.0.3, python 3.8.10) this was the error (This is NOT the error anymore, but I thought it might be useful to post it regardless):
```python-traceback

You have to call load_stylesheet function after instantiation of QApplication to take effect.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1636, in moveEvent
    if not self.isMaximized() and not self.layouts.get_fullscreen_flag():
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1179, in __getattr__
    return self.get_plugin(self._INTERNAL_PLUGINS_MAPPING[attr])
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 169, in get_plugin
    raise SpyderAPIError(
spyder.api.exceptions.SpyderAPIError: Plugin "layout" not found!

```

After the upgrade, I simply get:

```
Error: link image0 hasn't been detected!
```

## Versions

* Spyder version:  5.1.5
* Python version:  3.8.12
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows10

**Comment by dalthviz** [comment]
Hi @L-F-S , sorry to hear that, usually running `conda update --all` can let to some troubles. Could you run from the Anaconda Prompt spyder with the flag `--debug-info verbose` and post here what you are getting. The command is something like this:

     spyder --debug-info verbose

Also, maybe creating a new env with the latest Spyder could help us check if there is a problem with your current env packages or maybe is related to your preferences being corrupted somehow (in which case you will need to reset you preferences by running from an Anaconda Prompt `spyder --reset`). To create a new env and check if spyder runs you can use something like this:

    conda create -n spyder_env -c conda-forge python=3.8.10 spyder=5.1.5
    conda activata spyder_env
    spyder

Let us know if something of the above helps

**Comment by dalthviz** [comment]
I was able to reproduce while checking https://github.com/spyder-ide/spyder/issues/16676#issuecomment-1000910326

**Comment by ccordoba12** [comment]
I think this error only appears in PyQt 5.9 due to the new splash screen we added in 5.1.0.

**Comment by zhbi98** [comment]
I also encountered this mistake `Error: link image0 hasn't been detected!`.

**Comment by dalthviz** [comment]
Rechecking this a little bit seems like as @ccordoba12 suggested this is caused due to having Qt 5.9.7 installed. Seems like the warning message can be suppressed by setting the env var `QT_LOGGING_RULES` to `qt.svg.warning=false`. So for example on Windows, before launching Spyder from the Anaconda prompt, you can run `set QT_LOGGING_RULES=qt.svg.warning=false` (this flag is available starting with Qt 5.9) and you don't see the warning although the splash screen shows the spyder logo in black (should be white):

![imagen](https://user-images.githubusercontent.com/16781833/153433396-6d72052a-2c9e-4fa0-a49b-996a03170866.png)


A post related to the warnings caused by loading a somehow 'buggy'/somehow unsupported svg: https://forum.qt.io/topic/76843/qt-link-path3926-hasn-t-been-detected/3

Another alternative to not see this warning is to create a new env for the spyder installation using the conda-forge channel (which has Qt 5.12 and Spyder 5.2.2 available). Also you could use our standalone installers (available in the [release notes](https://github.com/spyder-ide/spyder/releases/latest) for Windows and MacOs and follow the [FAQ](https://docs.spyder-ide.org/5/faq.html#using-packages-installer) to understand how to use specific packages with them).

**Comment by ccordoba12** [comment]
This is something we need to ask @isabela-pf to help us with. I mean, fixing the splash screen for Qt 5.9.

@isabela-pf, could you take at look at this?
