### ISSUE TITLE
Debug raises "ValueError: unsupported pickle protocol: 3"

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1698]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-01-14T08:40:11Z_

Spyder Version:  2.3.0dev (3483: r94ba40e8a323 )
Python Version:  3.3.3
Qt Version    :  4.8.5, PySide 1.2.1 on Linux
IPython >=0.13  :  1.1.0 (OK)
pyflakes >=0.6.0:  0.7.3 (OK)
pep8 >=0.6      :  1.4 (OK)
sphinx >=0.6.6  :  1.1.3 (OK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.4.1 (OK)
pylint >=0.25   :  1.0.0 (OK) 

What steps will reproduce the problem?

 1. Launch a script in debug mode
2. Hit Ctrl+F12 to run the script What is the expected output? What do you see instead? Nothin is run and I get this in the console (the console corresponding to my script, not spyder's internal console):

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/pdb.py", line 1338, in \<module>
    pdb.main()
  File "/usr/lib/python2.7/pdb.py", line 1330, in main
    pdb.interaction(None, t)
  File "/data/prog/spyderlib/spyderlib/widgets/externalshell/sitecustomize.py", line 436, in interaction
    self.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 143, in cmdloop
    stop = self.postcmd(stop, line)
  File "/data/prog/spyderlib/spyderlib/widgets/externalshell/sitecustomize.py", line 450, in postcmd
    self.notify_spyder(self.curframe)
  File "/data/prog/spyderlib/spyderlib/widgets/externalshell/sitecustomize.py", line 382, in notify_spyder
    monitor.notify_pdb_step(fname, lineno)
  File "/data/prog/spyderlib/spyderlib/widgets/externalshell/monitor.py", line 317, in notify_pdb_step
    dict(command="pdb_step", data=(fname, lineno)))
  File "/data/prog/spyderlib/spyderlib/utils/bsdsocket.py", line 102, in communicate
    return read_packet(sock)
  File "/data/prog/spyderlib/spyderlib/utils/bsdsocket.py", line 83, in read_packet
    return pickle.loads(data)
ValueError: unsupported pickle protocol: 3 

Please provide any additional information below

. Spyder is launched from python3 but the interpreter is python2.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1698_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-01-14T07:27:41Z_

Are you running a PY2 interpreter inside PY3 regularly? What other problems have you had besides this one?

I was planning to disable this possibility because it could lead to ugly problems but I'd like to hear your experiences first.

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-01-14T08:25:58Z_

My developpement is still mainly in python2 (I try to be compatible with both but python2 is the main target). Launching spyder with python3 to run script with python2 was just a test, but it may be common once spyder v2.3 is out: I use arch linux (or Manjaro) where python3 is default.
I understant why you would like to disable this feature, but as a user it is very interesting to be able to test my programs under both version of python without having two editors open at the same time.

The other problems I had are the freezes (see issue `#1697` ). I will try to change the interpreter version, maybe this is the problem.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-10T06:47:05Z_

**Status:** Duplicate  
  **Mergedinto:** 1697
