### ISSUE TITLE
python.exe failed

### ISSUE THREAD

**Issue by ray-at-brunvoll** [spyder-ide/spyder#16980]
### What steps will reproduce the problem?

Changing the python interpreter to the one in anaconda.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\greray\.conda\envs\spyder\lib\site-packages\spyder\plugins\preferences\widgets\configdialog.py", line 127, in accept
    configpage.apply_changes()
  File "C:\Users\greray\.conda\envs\spyder\lib\site-packages\spyder\plugins\preferences\api.py", line 110, in apply_changes
    self.apply_callback()
  File "C:\Users\greray\.conda\envs\spyder\lib\site-packages\spyder\plugins\preferences\api.py", line 142, in <lambda>
    self._apply_settings_tabs(self.changed_options))
  File "C:\Users\greray\.conda\envs\spyder\lib\site-packages\spyder\plugins\preferences\api.py", line 170, in _apply_settings_tabs
    self.apply_settings(options)
  File "C:\Users\greray\.conda\envs\spyder\lib\site-packages\spyder\api\preferences.py", line 101, in wrapper
    opts = self.previous_apply_settings()
TypeError: apply_settings() missing 1 required positional argument: 'options'
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.9.7
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=1.0                  :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.3 (OK)
qtconsole >=5.0.3             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by dalthviz** [comment]
Hi @ray-at-brunvoll thank you for the feedback. Seems like you are using an outdated version of Spyder. Could you update Spyder and try again? 

Also, since seems like you are trying to use the interpreter preference. Keep in mind that you will need to install the correct `spyder-kernels` version in the interpreter env for the IPython Console to work on it (more info about that https://docs.spyder-ide.org/current/troubleshooting/common-illnesses.html#spyder-kernels-not-installed-incompatible). So for example for Spyder 5.2.0 the `spyder-kernels` minimum version is 2.2.0

Let us know if something of the above helps

**Comment by ray-at-brunvoll** [comment]
HI,

I am not able to update spyder from anaconda.

Regards,

Ray

**Comment by dalthviz** [comment]
For the update maybe this could be useful @ray-at-brunvoll : https://stackoverflow.com/a/69713849/15954282

Basically, for your case and if you want to install the latest spyder version, you will need to run something like this in your activated env:

      conda remove spyder
      conda remove python-language-server
      conda install spyder=5.1.5

Let us know if you are able to update using the above

**Comment by dalthviz** [comment]
Closing due to lack of response
