### ISSUE TITLE
Spyder failing to launch: no module named 'PySide'

### ISSUE THREAD

**Issue by amouracook** [spyder-ide/spyder#16993]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Spyder failing to launch: no module named 'PySide'

### What steps reproduce the problem?

1. Launch spyder (either from Anaconda Prompt or from Anaconda Navigator)

### What is the expected output? What do you see instead?

Expected: launch of Spyder
Encountered:  error message: No module named 'PySide'

When I try to do ``conda install pyside`` I get that the package is not available from current channels

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\qtpy\__init__.py", line 209, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\start.py", line 233, in main
    from spyder.app import mainwindow
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 42, in <module>
    requirements.check_qt()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\requirements.py", line 44, in check_qt
    import qtpy
  File "C:\ProgramData\Anaconda3\lib\site-packages\qtpy\__init__.py", line 215, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

```

## Versions

* Spyder version: 5.1.5
* Python version: 3.8.12
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 Enterprise

### Dependencies

```
spyder==5.1.5
  - atomicwrites [required: >=1.2.0, installed: 1.4.0]
  - chardet [required: >=2.0.0, installed: 4.0.0]
  - cloudpickle [required: >=0.5.0, installed: 2.0.0]
  - cookiecutter [required: >=1.6.0, installed: 1.7.2]
    - binaryornot [required: >=0.4.4, installed: 0.4.4]
      - chardet [required: >=3.0.2, installed: 4.0.0]
    - click [required: >=7.0, installed: 8.0.3]
      - colorama [required: Any, installed: 0.4.4]
    - Jinja2 [required: <3.0.0, installed: 2.11.3]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - jinja2-time [required: >=0.2.0, installed: 0.2.0]
      - arrow [required: Any, installed: 0.13.1]
        - python-dateutil [required: Any, installed: 2.8.2]
          - six [required: >=1.5, installed: 1.16.0]
      - jinja2 [required: Any, installed: 2.11.3]
        - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - MarkupSafe [required: <2.0.0, installed: 1.1.1]
    - poyo [required: >=0.5.0, installed: 0.5.0]
    - python-slugify [required: >=4.0.0, installed: 5.0.2]
      - text-unidecode [required: >=1.3, installed: 1.3]
    - requests [required: >=2.23.0, installed: 2.26.0]
      - certifi [required: >=2017.4.17, installed: 2021.10.8]
      - charset-normalizer [required: ~=2.0.0, installed: 2.0.4]
      - idna [required: >=2.5,<4, installed: 3.3]
      - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.7]
    - six [required: >=1.10, installed: 1.16.0]
  - diff-match-patch [required: >=20181111, installed: 20200713]
  - intervaltree [required: >=3.0.2, installed: 3.1.0]
    - sortedcontainers [required: >=2.0,<3.0, installed: 2.4.0]
  - ipython [required: >=7.6.0, installed: 7.29.0]
    - backcall [required: Any, installed: 0.2.0]
    - colorama [required: Any, installed: 0.4.4]
    - decorator [required: Any, installed: 5.1.0]
    - jedi [required: >=0.16, installed: 0.18.0]
      - parso [required: >=0.8.0,<0.9.0, installed: 0.8.2]
    - matplotlib-inline [required: Any, installed: 0.1.2]
      - traitlets [required: Any, installed: 5.1.1]
    - pickleshare [required: Any, installed: 0.7.5]
    - prompt-toolkit [required: >=2.0.0,<3.1.0,!=3.0.1,!=3.0.0, installed: 3.0.20]
      - wcwidth [required: Any, installed: 0.2.5]
    - pygments [required: Any, installed: 2.10.0]
    - setuptools [required: >=18.5, installed: 58.0.4]
    - traitlets [required: >=4.2, installed: 5.1.1]
  - jedi [required: >=0.17.2,<0.19.0, installed: 0.18.0]
    - parso [required: >=0.8.0,<0.9.0, installed: 0.8.2]
  - jsonschema [required: >=3.2.0, installed: 3.2.0]
    - attrs [required: >=17.4.0, installed: 21.2.0]
    - pyrsistent [required: >=0.14.0, installed: 0.18.0]
    - setuptools [required: Any, installed: 58.0.4]
    - six [required: >=1.11.0, installed: 1.16.0]
  - keyring [required: >=17.0.0, installed: 23.4.0]
    - importlib-metadata [required: >=3.6, installed: 4.8.2]
      - zipp [required: >=0.5, installed: 3.6.0]
    - pywin32-ctypes [required: !=0.1.1,!=0.1.0, installed: 0.2.0]
  - nbconvert [required: >=4.0, installed: 6.1.0]
    - bleach [required: Any, installed: 4.0.0]
      - packaging [required: Any, installed: 21.3]
        - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.4]
      - six [required: >=1.9.0, installed: 1.16.0]
      - webencodings [required: Any, installed: 0.5.1]
    - defusedxml [required: Any, installed: 0.7.1]
    - entrypoints [required: >=0.2.2, installed: 0.3]
    - jinja2 [required: >=2.4, installed: 2.11.3]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - jupyter-core [required: Any, installed: 4.9.1]
      - pywin32 [required: >=1.0, installed: 228]
      - traitlets [required: Any, installed: 5.1.1]
    - jupyterlab-pygments [required: Any, installed: 0.1.2]
      - pygments [required: >=2.4.1,<3, installed: 2.10.0]
    - mistune [required: >=0.8.1,<2, installed: 0.8.4]
    - nbclient [required: >=0.5.0,<0.6.0, installed: 0.5.3]
      - async-generator [required: Any, installed: 1.10]
      - jupyter-client [required: >=6.1.5, installed: 6.1.12]
        - jupyter-core [required: >=4.6.0, installed: 4.9.1]
          - pywin32 [required: >=1.0, installed: 228]
          - traitlets [required: Any, installed: 5.1.1]
        - python-dateutil [required: >=2.1, installed: 2.8.2]
          - six [required: >=1.5, installed: 1.16.0]
        - pyzmq [required: >=13, installed: 22.3.0]
        - tornado [required: >=4.1, installed: 6.1]
        - traitlets [required: Any, installed: 5.1.1]
      - nbformat [required: >=5.0, installed: 5.1.3]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - jsonschema [required: >=2.4,!=2.5.0, installed: 3.2.0]
          - attrs [required: >=17.4.0, installed: 21.2.0]
          - pyrsistent [required: >=0.14.0, installed: 0.18.0]
          - setuptools [required: Any, installed: 58.0.4]
          - six [required: >=1.11.0, installed: 1.16.0]
        - jupyter-core [required: Any, installed: 4.9.1]
          - pywin32 [required: >=1.0, installed: 228]
          - traitlets [required: Any, installed: 5.1.1]
        - traitlets [required: >=4.1, installed: 5.1.1]
      - nest-asyncio [required: Any, installed: 1.5.1]
      - traitlets [required: >=4.2, installed: 5.1.1]
    - nbformat [required: >=4.4, installed: 5.1.3]
      - ipython-genutils [required: Any, installed: 0.2.0]
      - jsonschema [required: >=2.4,!=2.5.0, installed: 3.2.0]
        - attrs [required: >=17.4.0, installed: 21.2.0]
        - pyrsistent [required: >=0.14.0, installed: 0.18.0]
        - setuptools [required: Any, installed: 58.0.4]
        - six [required: >=1.11.0, installed: 1.16.0]
      - jupyter-core [required: Any, installed: 4.9.1]
        - pywin32 [required: >=1.0, installed: 228]
        - traitlets [required: Any, installed: 5.1.1]
      - traitlets [required: >=4.1, installed: 5.1.1]
    - pandocfilters [required: >=1.4.1, installed: 1.4.3]
    - pygments [required: >=2.4.1, installed: 2.10.0]
    - testpath [required: Any, installed: 0.5.0]
    - traitlets [required: >=5.0, installed: 5.1.1]
  - numpydoc [required: >=0.6.0, installed: 1.1.0]
    - Jinja2 [required: >=2.3, installed: 2.11.3]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - sphinx [required: >=1.6.5, installed: 4.2.0]
      - alabaster [required: >=0.7,<0.8, installed: 0.7.12]
      - babel [required: >=1.3, installed: 2.9.1]
        - pytz [required: >=2015.7, installed: 2021.3]
      - colorama [required: >=0.3.5, installed: 0.4.4]
      - docutils [required: >=0.14,<0.18, installed: 0.17.1]
      - imagesize [required: Any, installed: 1.3.0]
      - Jinja2 [required: >=2.3, installed: 2.11.3]
        - MarkupSafe [required: >=0.23, installed: 1.1.1]
      - packaging [required: Any, installed: 21.3]
        - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.4]
      - Pygments [required: >=2.0, installed: 2.10.0]
      - requests [required: >=2.5.0, installed: 2.26.0]
        - certifi [required: >=2017.4.17, installed: 2021.10.8]
        - charset-normalizer [required: ~=2.0.0, installed: 2.0.4]
        - idna [required: >=2.5,<4, installed: 3.3]
        - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.7]
      - setuptools [required: Any, installed: 58.0.4]
      - snowballstemmer [required: >=1.1, installed: 2.2.0]
      - sphinxcontrib-applehelp [required: Any, installed: 1.0.2]
      - sphinxcontrib-devhelp [required: Any, installed: 1.0.2]
      - sphinxcontrib-htmlhelp [required: >=2.0.0, installed: 2.0.0]
      - sphinxcontrib-jsmath [required: Any, installed: 1.0.1]
      - sphinxcontrib-qthelp [required: Any, installed: 1.0.3]
      - sphinxcontrib-serializinghtml [required: >=1.1.5, installed: 1.1.5]
  - paramiko [required: >=2.4.0, installed: 2.7.2]
    - bcrypt [required: >=3.1.3, installed: 3.2.0]
      - cffi [required: >=1.1, installed: 1.15.0]
        - pycparser [required: Any, installed: 2.21]
      - six [required: >=1.4.1, installed: 1.16.0]
    - cryptography [required: >=2.5, installed: 3.4.8]
      - cffi [required: >=1.12, installed: 1.15.0]
        - pycparser [required: Any, installed: 2.21]
    - pynacl [required: >=1.0.1, installed: 1.4.0]
      - cffi [required: >=1.4.1, installed: 1.15.0]
        - pycparser [required: Any, installed: 2.21]
      - six [required: Any, installed: 1.16.0]
  - parso [required: >=0.7.0,<0.9.0, installed: 0.8.2]
  - pexpect [required: >=4.4.0, installed: 4.8.0]
    - ptyprocess [required: >=0.5, installed: 0.7.0]
  - pickleshare [required: >=0.4, installed: 0.7.5]
  - psutil [required: >=5.3, installed: 5.8.0]
  - pygments [required: >=2.0, installed: 2.10.0]
  - pylint [required: >=2.5.0,<2.10.0, installed: 2.9.6]
    - astroid [required: >=2.6.5,<2.7, installed: 2.6.6]
      - lazy-object-proxy [required: >=1.4.0, installed: 1.6.0]
      - setuptools [required: >=20.0, installed: 58.0.4]
      - wrapt [required: >=1.11,<1.13, installed: 1.12.1]
    - colorama [required: Any, installed: 0.4.4]
    - isort [required: >=4.2.5,<6, installed: 5.9.3]
    - mccabe [required: >=0.6,<0.7, installed: 0.6.1]
    - toml [required: >=0.7.1, installed: 0.10.2]
  - pyls-spyder [required: >=0.4.0, installed: 0.4.0]
    - python-lsp-server [required: >=1.0.1, installed: 1.2.4]
      - jedi [required: >=0.17.2,<0.19.0, installed: 0.18.0]
        - parso [required: >=0.8.0,<0.9.0, installed: 0.8.2]
      - pluggy [required: Any, installed: 0.13.1]
      - python-lsp-jsonrpc [required: >=1.0.0, installed: 1.0.0]
        - ujson [required: >=3.0.0, installed: 4.0.2]
      - setuptools [required: >=39.0.0, installed: 58.0.4]
      - ujson [required: >=3.0.0, installed: 4.0.2]
  - pyqt5 [required: <5.13, installed: 5.11.2]
    - PyQt5-sip [required: >=4.19.11,<4.20, installed: 4.19.19]
  - pyqtwebengine [required: <5.13, installed: ?]
  - python-lsp-black [required: >=1.0.0, installed: 1.0.0]
    - black [required: >=19.3b0, installed: 19.10b0]
      - appdirs [required: Any, installed: 1.4.4]
      - attrs [required: >=18.1.0, installed: 21.2.0]
      - click [required: >=6.5, installed: 8.0.3]
        - colorama [required: Any, installed: 0.4.4]
      - pathspec [required: >=0.6,<1, installed: 0.7.0]
      - regex [required: Any, installed: 2021.8.3]
      - toml [required: >=0.9.4, installed: 0.10.2]
      - typed-ast [required: >=1.4.0, installed: 1.4.3]
    - python-lsp-server [required: Any, installed: 1.2.4]
      - jedi [required: >=0.17.2,<0.19.0, installed: 0.18.0]
        - parso [required: >=0.8.0,<0.9.0, installed: 0.8.2]
      - pluggy [required: Any, installed: 0.13.1]
      - python-lsp-jsonrpc [required: >=1.0.0, installed: 1.0.0]
        - ujson [required: >=3.0.0, installed: 4.0.2]
      - setuptools [required: >=39.0.0, installed: 58.0.4]
      - ujson [required: >=3.0.0, installed: 4.0.2]
    - toml [required: Any, installed: 0.10.2]
  - python-lsp-server [required: >=1.2.2,<1.3.0, installed: 1.2.4]
    - jedi [required: >=0.17.2,<0.19.0, installed: 0.18.0]
      - parso [required: >=0.8.0,<0.9.0, installed: 0.8.2]
    - pluggy [required: Any, installed: 0.13.1]
    - python-lsp-jsonrpc [required: >=1.0.0, installed: 1.0.0]
      - ujson [required: >=3.0.0, installed: 4.0.2]
    - setuptools [required: >=39.0.0, installed: 58.0.4]
    - ujson [required: >=3.0.0, installed: 4.0.2]
  - pyzmq [required: >=17, installed: 22.3.0]
  - qdarkstyle [required: ==3.0.2, installed: 3.0.2]
    - qtpy [required: >=1.9, installed: 1.10.0]
  - qstylizer [required: >=0.1.10, installed: 0.1.10]
    - inflection [required: >0.3.0,<1, installed: 0.5.1]
    - tinycss [required: >=0.4,<1, installed: 0.4]
  - qtawesome [required: >=1.0.2, installed: 1.0.3]
    - qtpy [required: Any, installed: 1.10.0]
  - qtconsole [required: >=5.1.0, installed: 5.1.1]
    - ipykernel [required: >=4.1, installed: 6.4.1]
      - debugpy [required: >=1.0.0,<2.0, installed: 1.5.1]
      - ipython [required: >=7.23.1,<8.0, installed: 7.29.0]
        - backcall [required: Any, installed: 0.2.0]
        - colorama [required: Any, installed: 0.4.4]
        - decorator [required: Any, installed: 5.1.0]
        - jedi [required: >=0.16, installed: 0.18.0]
          - parso [required: >=0.8.0,<0.9.0, installed: 0.8.2]
        - matplotlib-inline [required: Any, installed: 0.1.2]
          - traitlets [required: Any, installed: 5.1.1]
        - pickleshare [required: Any, installed: 0.7.5]
        - prompt-toolkit [required: >=2.0.0,<3.1.0,!=3.0.1,!=3.0.0, installed: 3.0.20]
          - wcwidth [required: Any, installed: 0.2.5]
        - pygments [required: Any, installed: 2.10.0]
        - setuptools [required: >=18.5, installed: 58.0.4]
        - traitlets [required: >=4.2, installed: 5.1.1]
      - ipython-genutils [required: Any, installed: 0.2.0]
      - jupyter-client [required: <8.0, installed: 6.1.12]
        - jupyter-core [required: >=4.6.0, installed: 4.9.1]
          - pywin32 [required: >=1.0, installed: 228]
          - traitlets [required: Any, installed: 5.1.1]
        - python-dateutil [required: >=2.1, installed: 2.8.2]
          - six [required: >=1.5, installed: 1.16.0]
        - pyzmq [required: >=13, installed: 22.3.0]
        - tornado [required: >=4.1, installed: 6.1]
        - traitlets [required: Any, installed: 5.1.1]
      - matplotlib-inline [required: >=0.1.0,<0.2.0, installed: 0.1.2]
        - traitlets [required: Any, installed: 5.1.1]
      - tornado [required: >=4.2,<7.0, installed: 6.1]
      - traitlets [required: >=4.1.0,<6.0, installed: 5.1.1]
    - ipython-genutils [required: Any, installed: 0.2.0]
    - jupyter-client [required: >=4.1, installed: 6.1.12]
      - jupyter-core [required: >=4.6.0, installed: 4.9.1]
        - pywin32 [required: >=1.0, installed: 228]
        - traitlets [required: Any, installed: 5.1.1]
      - python-dateutil [required: >=2.1, installed: 2.8.2]
        - six [required: >=1.5, installed: 1.16.0]
      - pyzmq [required: >=13, installed: 22.3.0]
      - tornado [required: >=4.1, installed: 6.1]
      - traitlets [required: Any, installed: 5.1.1]
    - jupyter-core [required: Any, installed: 4.9.1]
      - pywin32 [required: >=1.0, installed: 228]
      - traitlets [required: Any, installed: 5.1.1]
    - pygments [required: Any, installed: 2.10.0]
    - pyzmq [required: >=17.1, installed: 22.3.0]
    - qtpy [required: Any, installed: 1.10.0]
    - traitlets [required: Any, installed: 5.1.1]
  - qtpy [required: >=1.5.0, installed: 1.10.0]
  - rtree [required: >=0.9.7, installed: 0.9.7]
  - setuptools [required: >=49.6.0, installed: 58.0.4]
  - sphinx [required: >=0.6.6, installed: 4.2.0]
    - alabaster [required: >=0.7,<0.8, installed: 0.7.12]
    - babel [required: >=1.3, installed: 2.9.1]
      - pytz [required: >=2015.7, installed: 2021.3]
    - colorama [required: >=0.3.5, installed: 0.4.4]
    - docutils [required: >=0.14,<0.18, installed: 0.17.1]
    - imagesize [required: Any, installed: 1.3.0]
    - Jinja2 [required: >=2.3, installed: 2.11.3]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - packaging [required: Any, installed: 21.3]
      - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.4]
    - Pygments [required: >=2.0, installed: 2.10.0]
    - requests [required: >=2.5.0, installed: 2.26.0]
      - certifi [required: >=2017.4.17, installed: 2021.10.8]
      - charset-normalizer [required: ~=2.0.0, installed: 2.0.4]
      - idna [required: >=2.5,<4, installed: 3.3]
      - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.7]
    - setuptools [required: Any, installed: 58.0.4]
    - snowballstemmer [required: >=1.1, installed: 2.2.0]
    - sphinxcontrib-applehelp [required: Any, installed: 1.0.2]
    - sphinxcontrib-devhelp [required: Any, installed: 1.0.2]
    - sphinxcontrib-htmlhelp [required: >=2.0.0, installed: 2.0.0]
    - sphinxcontrib-jsmath [required: Any, installed: 1.0.1]
    - sphinxcontrib-qthelp [required: Any, installed: 1.0.3]
    - sphinxcontrib-serializinghtml [required: >=1.1.5, installed: 1.1.5]
  - spyder-kernels [required: >=2.1.1,<2.2.0, installed: 2.1.3]
    - cloudpickle [required: Any, installed: 2.0.0]
    - ipykernel [required: >=5.3.0, installed: 6.4.1]
      - debugpy [required: >=1.0.0,<2.0, installed: 1.5.1]
      - ipython [required: >=7.23.1,<8.0, installed: 7.29.0]
        - backcall [required: Any, installed: 0.2.0]
        - colorama [required: Any, installed: 0.4.4]
        - decorator [required: Any, installed: 5.1.0]
        - jedi [required: >=0.16, installed: 0.18.0]
          - parso [required: >=0.8.0,<0.9.0, installed: 0.8.2]
        - matplotlib-inline [required: Any, installed: 0.1.2]
          - traitlets [required: Any, installed: 5.1.1]
        - pickleshare [required: Any, installed: 0.7.5]
        - prompt-toolkit [required: >=2.0.0,<3.1.0,!=3.0.1,!=3.0.0, installed: 3.0.20]
          - wcwidth [required: Any, installed: 0.2.5]
        - pygments [required: Any, installed: 2.10.0]
        - setuptools [required: >=18.5, installed: 58.0.4]
        - traitlets [required: >=4.2, installed: 5.1.1]
      - ipython-genutils [required: Any, installed: 0.2.0]
      - jupyter-client [required: <8.0, installed: 6.1.12]
        - jupyter-core [required: >=4.6.0, installed: 4.9.1]
          - pywin32 [required: >=1.0, installed: 228]
          - traitlets [required: Any, installed: 5.1.1]
        - python-dateutil [required: >=2.1, installed: 2.8.2]
          - six [required: >=1.5, installed: 1.16.0]
        - pyzmq [required: >=13, installed: 22.3.0]
        - tornado [required: >=4.1, installed: 6.1]
        - traitlets [required: Any, installed: 5.1.1]
      - matplotlib-inline [required: >=0.1.0,<0.2.0, installed: 0.1.2]
        - traitlets [required: Any, installed: 5.1.1]
      - tornado [required: >=4.2,<7.0, installed: 6.1]
      - traitlets [required: >=4.1.0,<6.0, installed: 5.1.1]
    - ipython [required: >=7.6.0, installed: 7.29.0]
      - backcall [required: Any, installed: 0.2.0]
      - colorama [required: Any, installed: 0.4.4]
      - decorator [required: Any, installed: 5.1.0]
      - jedi [required: >=0.16, installed: 0.18.0]
        - parso [required: >=0.8.0,<0.9.0, installed: 0.8.2]
      - matplotlib-inline [required: Any, installed: 0.1.2]
        - traitlets [required: Any, installed: 5.1.1]
      - pickleshare [required: Any, installed: 0.7.5]
      - prompt-toolkit [required: >=2.0.0,<3.1.0,!=3.0.1,!=3.0.0, installed: 3.0.20]
        - wcwidth [required: Any, installed: 0.2.5]
      - pygments [required: Any, installed: 2.10.0]
      - setuptools [required: >=18.5, installed: 58.0.4]
      - traitlets [required: >=4.2, installed: 5.1.1]
    - jupyter-client [required: >=5.3.4,<7, installed: 6.1.12]
      - jupyter-core [required: >=4.6.0, installed: 4.9.1]
        - pywin32 [required: >=1.0, installed: 228]
        - traitlets [required: Any, installed: 5.1.1]
      - python-dateutil [required: >=2.1, installed: 2.8.2]
        - six [required: >=1.5, installed: 1.16.0]
      - pyzmq [required: >=13, installed: 22.3.0]
      - tornado [required: >=4.1, installed: 6.1]
      - traitlets [required: Any, installed: 5.1.1]
    - pyzmq [required: >=17, installed: 22.3.0]
  - textdistance [required: >=4.2.0, installed: 4.2.1]
  - three-merge [required: >=0.1.1, installed: 0.1.1]
    - diff-match-patch [required: Any, installed: 20200713]
  - watchdog [required: >=0.10.3, installed: 2.1.6]
```

**Comment by amouracook** [comment]
thank you very much for your help in advance

**Comment by amouracook** [comment]
Hi @ccordoba12 , thanks for the quick response. I had done that, but I got the error: "ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'". So then I did a conda install of it, which I guess created the double install....? 

Has the PyQt5 issue occurred before? I found some things on forums but nothing that fixed my issue.

**Comment by ccordoba12** [comment]
The error you reported is typical of mixing pip and conda packages. Please reinstall Anaconda following the instructions in our video and (hopefully) you'll get Spyder working again. It's important to follow our video because we provide additional feedback on how to do a successful re-installation.

**Comment by amouracook** [comment]
Thanks for your help, it's working now.

**Comment by ccordoba12** [comment]
Great! I'm really glad it's working for you again.
