### ISSUE TITLE
Computation stopped with the following error 

### ISSUE THREAD

**Issue by nlqnly** [spyder-ide/spyder#17002]
### What steps will reproduce the problem?
tensor

An error ocurred while starting the kernel
2021󈚰󈚰 11:08:29.160047: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021󈚰󈚰 11:08:30.382128: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance‑critical operations: AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021󈚰󈚰 11:08:30.383689: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2021󈚰󈚰 11:08:30.409150: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1660 computeCapability: 7.5
coreClock: 1.815GHz coreCount: 22 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 178.86GiB/s
2021󈚰󈚰 11:08:30.409170: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021󈚰󈚰 11:08:30.418404: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021󈚰󈚰 11:08:30.418418: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021󈚰󈚰 11:08:30.421303: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021󈚰󈚰 11:08:30.422136: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021󈚰󈚰 11:08:30.428270: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021󈚰󈚰 11:08:30.430688: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021󈚰󈚰 11:08:30.431078: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021󈚰󈚰 11:08:30.431131: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021󈚰󈚰 11:08:30.822901: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021󈚰󈚰 11:08:30.822930: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267] 0 
2021󈚰󈚰 11:08:30.822936: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0: N 
2021󈚰󈚰 11:08:30.823051: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4744 MB memory) ‑> physical GPU (device: 0, name: GeForce GTX 1660, pci bus id: 0000:01:00.0, compute capability: 7.5)
2021󈚰󈚰 11:08:30.823609: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021󈚰󈚰 11:08:30.824491: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021󈚰󈚰 11:08:30.824538: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1660 computeCapability: 7.5
coreClock: 1.815GHz coreCount: 22 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 178.86GiB/s
2021󈚰󈚰 11:08:30.824551: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021󈚰󈚰 11:08:30.824558: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021󈚰󈚰 11:08:30.824565: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021󈚰󈚰 11:08:30.824571: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021󈚰󈚰 11:08:30.824577: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021󈚰󈚰 11:08:30.824583: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021󈚰󈚰 11:08:30.824639: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021󈚰󈚰 11:08:30.824648: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021󈚰󈚰 11:08:30.824690: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021󈚰󈚰 11:08:30.825077: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1660 computeCapability: 7.5
coreClock: 1.815GHz coreCount: 22 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 178.86GiB/s
2021󈚰󈚰 11:08:30.825090: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021󈚰󈚰 11:08:30.825097: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021󈚰󈚰 11:08:30.825103: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021󈚰󈚰 11:08:30.825109: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021󈚰󈚰 11:08:30.825115: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021󈚰󈚰 11:08:30.825121: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021󈚰󈚰 11:08:30.825126: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021󈚰󈚰 11:08:30.825132: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021󈚰󈚰 11:08:30.825172: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021󈚰󈚰 11:08:30.825199: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021󈚰󈚰 11:08:30.825205: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267] 0 
2021󈚰󈚰 11:08:30.825210: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0: N 
2021󈚰󈚰 11:08:30.825257: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4744 MB memory) ‑> physical GPU (device: 0, name: GeForce GTX 1660, pci bus id: 0000:01:00.0, compute capability: 7.5)
2021󈚰󈚰 11:08:30.825273: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021󈚰󈚰 11:08:31.352785: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021󈚰󈚰 11:08:31.424091: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: cond/then/_0/cond/rot90_7/Assert/AssertGuard/branch_executed/_175
2021󈚰󈚰 11:08:32.474415: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021󈚰󈚰 11:08:33.307755: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 0

2021󈚰󈚰 11:08:33.337099: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 0

2021󈚰󈚰 11:08:33.349540: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021󈚰󈚰 11:08:33.735315: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021󈚰󈚰 11:08:35.514919: W tensorflow/core/common_runtime/bfc_allocator.cc:314] Garbage collection: deallocate free memory regions (i.e., allocations) so that we can re‑allocate a larger region to avoid OOM due to memory fragmentation. If you see this message frequently, you are running near the threshold of the available device memory and re‑allocation may incur great performance overhead. You may try smaller batch sizes to observe the performance impact. Set TF_ENABLE_GPU_GARBAGE_COLLECTION=false if you'd like to disable this feature.
2021󈚰󈚰 11:08:35.538438: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 4.00G (4294967296 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021󈚰󈚰 11:08:44.622672: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1660 computeCapability: 7.5
coreClock: 1.815GHz coreCount: 22 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 178.86GiB/s
2021󈚰󈚰 11:08:44.622695: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021󈚰󈚰 11:08:44.622705: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021󈚰󈚰 11:08:44.622713: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021󈚰󈚰 11:08:44.622720: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021󈚰󈚰 11:08:44.622727: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021󈚰󈚰 11:08:44.622733: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021󈚰󈚰 11:08:44.622739: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021󈚰󈚰 11:08:44.622745: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021󈚰󈚰 11:08:44.622772: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021󈚰󈚰 11:08:44.622807: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021󈚰󈚰 11:08:44.622814: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267] 0 
2021󈚰󈚰 11:08:44.622818: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0: N 
2021󈚰󈚰 11:08:44.622914: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4744 MB memory) ‑> physical GPU (device: 0, name: GeForce GTX 1660, pci bus id: 0000:01:00.0, compute capability: 7.5)
2021󈚰󈚰 11:08:44.622932: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021󈚰󈚰 11:08:45.080370: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: cond/then/_0/cond/rot90_6/Assert/AssertGuard/branch_executed/_156
2021󈚰󈚰 11:09:01.042019: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1660 computeCapability: 7.5
coreClock: 1.815GHz coreCount: 22 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 178.86GiB/s
2021󈚰󈚰 11:09:01.042043: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021󈚰󈚰 11:09:01.042052: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021󈚰󈚰 11:09:01.042059: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021󈚰󈚰 11:09:01.042066: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021󈚰󈚰 11:09:01.042073: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021󈚰󈚰 11:09:01.042079: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021󈚰󈚰 11:09:01.042088: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021󈚰󈚰 11:09:01.042096: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021󈚰󈚰 11:09:01.042126: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021󈚰󈚰 11:09:01.042162: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021󈚰󈚰 11:09:01.042168: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267] 0 
2021󈚰󈚰 11:09:01.042173: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0: N 
2021󈚰󈚰 11:09:01.042297: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4744 MB memory) ‑> physical GPU (device: 0, name: GeForce GTX 1660, pci bus id: 0000:01:00.0, compute capability: 7.5)
2021󈚰󈚰 11:09:01.042315: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021󈚰󈚰 11:09:01.496839: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: cond/then/_0/cond/rot90_4/Assert/AssertGuard/branch_executed/_118
2021󈚰󈚰 11:09:47.496688: F tensorflow/core/kernels/training_ops_gpu.cu.cc:662] Non‑OK‑status: GpuLaunchKernel( ApplyAdamKernel, config.block_count, config.thread_per_block, 0, d.stream(), data_dim, var.data(), m.data(), v.data(), beta1_power.data(), beta2_power.data(), lr.data(), beta1.data(), beta2.data(), epsilon.data(), grad.data(), use_nesterov) status: Internal: unspecified launch failure

Tensorflow training process terminate unexpectedly.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "E:\anaconda3\lib\site-packages\qtconsole\manager.py", line 27, in poll
    super().poll()
  File "E:\anaconda3\lib\site-packages\jupyter_client\restarter.py", line 127, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "E:\anaconda3\lib\site-packages\jupyter_client\utils.py", line 25, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))
  File "E:\anaconda3\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "E:\anaconda3\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "E:\anaconda3\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "E:\anaconda3\lib\site-packages\jupyter_client\manager.py", line 477, in _async_restart_kernel
    await ensure_async(self.shutdown_kernel(now=now, restart=True))
  File "E:\anaconda3\lib\site-packages\jupyter_client\utils.py", line 25, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))
  File "E:\anaconda3\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "E:\anaconda3\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "E:\anaconda3\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "E:\anaconda3\lib\site-packages\jupyter_client\manager.py", line 436, in _async_shutdown_kernel
    await ensure_async(self._kill_kernel())
  File "E:\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\utils\manager.py", line 92, in _kill_kernel
    self.kill_proc_tree(self.kernel.pid)
AttributeError: 'SpyderKernelManager' object has no attribute 'kernel'
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.27.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=1.0                  :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.21.2 (OK)
pandas >=1.1.1                :  1.3.3 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by nlqnly** [comment]
> Thanks for reporting. To fix this, please close Spyder, open the Anaconda Prompt and run there:`conda install jupyter_client=6.1.12 freetype=2.10.4`

OK, thanks for your answer, I'll have a try.
