### ISSUE TITLE
Kommt immer beim Starten von Spyder

### ISSUE THREAD

**Issue by DrClaus** [spyder-ide/spyder#17006]
### What steps will reproduce the problem?

start spyder, the error commes immediatly.
Ther is no other action necessary.

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 453, in finish_recv
    return ov.getresult()
OSError: [WinError 995] Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "C:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 995] Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen
```

## Versions

* Spyder version: 4.2.1 
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  2.0.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.29.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  23.4.0 (OK)
nbconvert >=4.0                 :  6.1.0 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.10.0 (OK)
pylint >=1.0                    :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.2 (OK)
qdarkstyle >=2.8                :  3.0.2 (OK)
qtawesome >=0.5.7               :  1.0.3 (OK)
qtconsole >=5.0.1               :  5.1.1 (OK)
qtpy >=1.5.0                    :  1.10.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  58.0.4 (OK)
sphinx >=0.6.6                  :  4.2.0 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  2.1.6 (OK)
zmq >=17                        :  22.3.0 (OK)

# Optional:
cython >=0.21                   :  0.29.24 (OK)
matplotlib >=2.0.0              :  3.5.0 (OK)
numpy >=1.7                     :  1.20.3 (OK)
pandas >=1.1.1                  :  1.3.3 (OK)
scipy >=0.17.0                  :  1.7.1 (OK)
sympy >=0.7.3                   :  1.9 (OK)
```

**Comment by steff456** [comment]
Hi @DrClaus,

Can you let me know how did you installed Spyder in your machine? Also, I invite you to try our latest release of Spyder 5 :)

**Comment by DrClaus** [comment]
Good Morning,
thanks for your answer. I run anaconda on my computer. I can try to install Spyder it self.

**Comment by DrClaus** [comment]
Good morning,
I tried Spyder 5, but when I start it, is appears and immediately disappears. Several times I installed and uninstalled it, but the result is the same. What is wrong?

**Comment by steff456** [comment]
How are you installing Spyder in your machine? We currently have installers for windows and mac available [here](https://github.com/spyder-ide/spyder/releases/tag/v5.2.1). You can also use the anaconda distribution, I personally recommend more the `conda-forge` channel rather than defaults. 

Please let me know if you need further help!

**Comment by ccordoba12** [comment]
Hey @DrClaus. This problem is fixed in our latest Spyder 4 version. Please update by closing Spyder, opening the Anaconda Prompt and running there

    conda install spyder=4.2.5
