### ISSUE TITLE
Terminal and preferences

### ISSUE THREAD

**Issue by khwp** [spyder-ide/spyder#17014]
### What steps will reproduce the problem?

1) Installed terminal plug-in to spyder 5.2.5
2) When accessing Tools->preferences get an "Internal Problem".

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/lenovo/projects/projjunk/venv/lib/python3.8/site-packages/spyder/plugins/preferences/plugin.py", line 276, in <lambda>
    lambda: self.open_dialog(main.prefs_dialog_size))
  File "/home/lenovo/projects/projjunk/venv/lib/python3.8/site-packages/spyder/plugins/preferences/plugin.py", line 256, in open_dialog
    container.create_dialog(
  File "/home/lenovo/projects/projjunk/venv/lib/python3.8/site-packages/spyder/plugins/preferences/widgets/container.py", line 62, in create_dialog
    page.initialize()
  File "/home/lenovo/projects/projjunk/venv/lib/python3.8/site-packages/spyder/plugins/preferences/api.py", line 83, in initialize
    self.setup_page()
  File "/home/lenovo/projects/projjunk/venv/lib/python3.8/site-packages/spyder/api/plugin_registration/_confpage.py", line 71, in setup_page
    plugin_loc_name = PluginClass.get_name()
TypeError: get_name() missing 1 required positional argument: 'self'
```

## Versions

* Spyder version: 5.2.0 
* Python version: 3.8.10
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 5.4.0-91-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.0.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.6.0                      :  7.30.1 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.8.9 (OK)
jsonschema >=3.2.0                   :  4.2.1 (OK)
keyring >=17.0.0                     :  23.4.0 (OK)
nbconvert >=4.0                      :  6.3.0 (OK)
numpydoc >=0.6.0                     :  1.1.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.8.0 (OK)
pygments >=2.0                       :  2.10.0 (OK)
pylint >=2.5.0                       :  2.12.2 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.3.1;<1.4.0                 :  1.3.3 (OK)
pylsp_black >=1.0.0                  :  None (OK)
qdarkstyle =3.0.2                    :  3.0.2 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0             :  5.2.2 (OK)
qtpy >=1.5.0                         :  1.11.3 (OK)
rtree >=0.9.7                        :  0.9.7 (OK)
setuptools >=49.6.0                  :  59.6.0 (OK)
sphinx >=0.6.6                       :  4.3.1 (OK)
spyder_kernels >=2.2.0;<2.3.0        :  2.2.0 (OK)
textdistance >=4.2.0                 :  4.2.2 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.6 (OK)
xdg >=0.26                           :  0.27 (OK)
zmq >=17                             :  22.3.0 (OK)

# Optional:
cython >=0.21                        :  None (OK)
matplotlib >=2.0.0                   :  None (OK)
numpy >=1.7                          :  None (OK)
pandas >=1.1.1                       :  None (OK)
scipy >=0.17.0                       :  None (OK)
sympy >=0.7.3                        :  None (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.1.0 :  1.1.0 (OK)
```

**Comment by steff456** [comment]
Hi @khwp,

Right now we are updating Spyder-terminal to a newer version that supports Spyder 5.2.0 API. For now please uninstall the terminal, we hope to be releasing this new version this week, so please keep an eye on the Spyder-terminal repository and our social media!
