### ISSUE TITLE
Getting error in sypder old versions my python is 3.6.15 and sypder is 3.2.1

### ISSUE THREAD

**Issue by darknightush** [spyder-ide/spyder#17054]
## Description

**What steps will reproduce the problem?**

1. just typing sypder in anaconda, sypder will open and gives error and asked to submit to github

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\UNIQUE\miniconda3\envs\spyenv\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "C:\Users\UNIQUE\miniconda3\envs\spyenv\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "C:\Users\UNIQUE\miniconda3\envs\spyenv\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
      File "C:\Users\UNIQUE\miniconda3\envs\spyenv\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 209, in _handle_execute_reply

Traceback (most recent call last):
  File "C:\Users\UNIQUE\miniconda3\envs\spyenv\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):
  File "C:\Users\UNIQUE\miniconda3\envs\spyenv\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
      File "C:\Users\UNIQUE\miniconda3\envs\spyenv\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 209, in _handle_execute_reply

Traceback (most recent call last):
  File "C:\Users\UNIQUE\miniconda3\envs\spyenv\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
      File "C:\Users\UNIQUE\miniconda3\envs\spyenv\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 209, in _handle_execute_reply

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.6.15
* Qt Versions: 5.12.9, PyQt5 5.12.3 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  2.4.0 (OK)
pycodestyle >=2.3:  2.8.0 (OK)
pygments >=2.0   :  2.10.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  4.3.2 (OK)
rope >=0.9.4     :  0.22.0 (OK)
jedi >=0.9.0     :  0.17.2 (OK)
nbconvert >=4.0  :  6.0.7 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  5.2.2 (OK)
IPython >=4.0    :  7.16.1 (OK)
pylint >=0.25    :  2.11.1 (OK)

```

**Comment by ccordoba12** [comment]
Hey @darknightush, thanks for reporting. Unfortunately, Spyder 3 (and also Spyder 4) are not maintained anymore.

This problem could be fixed in the latest Spyder 3 version. Please update by closing Spyder, opening the Anaconda Prompt and running there

    conda install spyder=3.3.6

If that's not the case, please update to our latest version available in Anaconda (5.1.5).
