### ISSUE TITLE
Spyder Does Not Launch from CMD Windows 7 OS

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1705]
_From [sigmamon...@gmail.com](https://code.google.com/u/105429660792367143447/) on 2014-01-27T12:09:43Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1.From CMD spyer will cause the following message

C:\Users\SigmaDragon>spyder
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\spyder-script.py", line 2, in \<module>
    start_app.main()
  File "C:\Anaconda\lib\site-packages\spyderlib\start_app.py", line 75, in ma
    from spyderlib import spyder
  File "C:\Anaconda\lib\site-packages\spyderlib\spyder.py", line 106, in \<mod
    from spyderlib.plugins.inspector import ObjectInspector
  File "C:\Anaconda\lib\site-packages\spyderlib\plugins\inspector.py", line 3
    from spyderlib.widgets.browser import WebView
  File "C:\Anaconda\lib\site-packages\spyderlib\widgets\browser.py", line 11,
    from spyderlib.qt.QtWebKit import QWebView, QWebPage
  File "C:\Anaconda\lib\site-packages\spyderlib\qt\QtWebKit.py", line 12, in
    from PySide.QtWebKit import *  # analysis:ignore
ImportError: DLL load failed: The specified procedure could not be found. 2. 3. What is the expected output? What do you see instead? I expect to see Spyder start running and have access to Ipython terminal What version of the product are you using? On what operating system? Spyder Version 2.2.5
Windows 7 
Using Anaconda Download 

Please provide any additional information below

. I'm a newer user of Spyder. I hope the format is correct.

If I try to launch Spyder in CMD get an error.

However, if I go to the Anaconda folder and use the spyder-scripty.py Spyder will start up.  However Ipython will not work and I get the follow message 

Python 2.7.3 |Anaconda 1.8.0 (64-bit)| (default, Feb 25 2013, 18:41:24) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Traceback (most recent call last):
  File "C:/Anaconda/Scripts/spyder-script.py", line 2, in \<module>
    start_app.main()
  File "C:\Python27\lib\site-packages\spyderlib\start_app.py", line 75, in main
    from spyderlib import spyder
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 106, in \<module>
    from spyderlib.plugins.inspector import ObjectInspector
  File "C:\Python27\lib\site-packages\spyderlib\plugins\inspector.py", line 32, in \<module>
    from spyderlib.widgets.browser import WebView
  File "C:\Python27\lib\site-packages\spyderlib\widgets\browser.py", line 11, in \<module>
    from spyderlib.qt.QtWebKit import QWebView, QWebPage
  File "C:\Python27\lib\site-packages\spyderlib\qt\QtWebKit.py", line 12, in \<module>
    from PySide.QtWebKit import *  # analysis:ignore
ImportError: DLL load failed: The specified procedure could not be found.
\>>> 

Also, if I use the Spyder.bat file it quickly open the cmd window and just closes again and the application will not start.  

Thanks,
Douglas

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1705_

**Comment by goanpeca** [comment]
@ccordoba12 seems like and old bug, is this fixed?

**Comment by ccordoba12** [comment]
Yeah, please close it.
