### ISSUE TITLE
test_pydocgui.py has a timeout failure on test_get_pydoc

### ISSUE THREAD

**Issue by juliangilbey** [spyder-ide/spyder#17058]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I tried running the package tests (using runtest.py). I get several errors, but it probably makes more sense to deal with each one separately, so that's what I'm doing.  (See #17057 for the first error; this is the second one.)

This issue is about `spyder/plugins/onlinehelp/tests/test_pydocgui.py` in 5.2.0.  All three tests in this file give errors.  It occurs with Python 3.9 and 3.10; I haven't been able to test with other Python versions.

### What steps reproduce the problem?

Here's an attempt at running just these tests; the output from `runtests.py` is essentially identical.  I ran it inside a chroot with only the listed requirements (plus git, which was needed but not listed) installed.  This gave me three errors; I'm snipping most of the second two, as they are very similar to the first one:
```
(sid):~/debian/spyder-packages/spyder/build-area/spyder-5.2.0+dfsg1 $ xvfb-run -a -s "-screen 0 1024x768x24 +extension GLX" python3.9 -m pytest spyder/plugins/onlinehelp/tests/test_pydocgui.py
============================= test session starts ==============================
platform linux -- Python 3.9.9, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
PyQt5 5.15.6 -- Qt runtime 5.15.2 -- Qt compiled 5.15.2
rootdir: /home/jdg/debian/spyder-packages/spyder/build-area/spyder-5.2.0+dfsg1, configfile: pytest.ini
plugins: typeguard-2.11.1, flaky-3.7.0, xvfb-2.0.0, mock-3.6.1, cov-3.0.0, order-1.0.0, qt-4.0.2, lazy-fixture-0.6.3
collected 3 items                                                              

spyder/plugins/onlinehelp/tests/test_pydocgui.py EE                      [100%] [100%] [100%] [100%]E [100%]

==================================== ERRORS ====================================
_____________________ ERROR at setup of test_pydocbrowser ______________________
SETUP ERROR: Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/home/jdg/debian/spyder-packages/spyder/build-area/spyder-5.2.0+dfsg1/spyder/plugins/onlinehelp/widgets.py", line 268, in _continue_initialization
    self.go_home()
  File "/home/jdg/debian/spyder-packages/spyder/build-area/spyder-5.2.0+dfsg1/spyder/plugins/onlinehelp/widgets.py", line 444, in go_home
    self.set_url(self.home_url)
  File "/home/jdg/debian/spyder-packages/spyder/build-area/spyder-5.2.0+dfsg1/spyder/plugins/onlinehelp/widgets.py", line 425, in set_url
    self.go_to(url)
  File "/home/jdg/debian/spyder-packages/spyder/build-area/spyder-5.2.0+dfsg1/spyder/plugins/onlinehelp/widgets.py", line 436, in go_to
    self.webview.load(url)
  File "/home/jdg/debian/spyder-packages/spyder/build-area/spyder-5.2.0+dfsg1/spyder/widgets/browser.py", line 388, in load
    self.focusProxy().installEventFilter(self)
AttributeError: 'NoneType' object has no attribute 'installEventFilter'
________________________________________________________________________________
---------------------------- Captured stderr setup -----------------------------
Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/home/jdg/debian/spyder-packages/spyder/build-area/spyder-5.2.0+dfsg1/spyder/plugins/onlinehelp/widgets.py", line 268, in _continue_initialization
    self.go_home()
  File "/home/jdg/debian/spyder-packages/spyder/build-area/spyder-5.2.0+dfsg1/spyder/plugins/onlinehelp/widgets.py", line 444, in go_home
    self.set_url(self.home_url)
  File "/home/jdg/debian/spyder-packages/spyder/build-area/spyder-5.2.0+dfsg1/spyder/plugins/onlinehelp/widgets.py", line 425, in set_url
    self.go_to(url)
  File "/home/jdg/debian/spyder-packages/spyder/build-area/spyder-5.2.0+dfsg1/spyder/plugins/onlinehelp/widgets.py", line 436, in go_to
    self.webview.load(url)
  File "/home/jdg/debian/spyder-packages/spyder/build-area/spyder-5.2.0+dfsg1/spyder/widgets/browser.py", line 388, in load
    self.focusProxy().installEventFilter(self)
AttributeError: 'NoneType' object has no attribute 'installEventFilter'
________________________________________________________________________________
____________________ ERROR at setup of test_get_pydoc[lib0] ____________________
SETUP ERROR: Exceptions caught in Qt event loop:
[...snipped...]
AttributeError: 'NoneType' object has no attribute 'installEventFilter'
________________________________________________________________________________
____________________ ERROR at setup of test_get_pydoc[lib1] ____________________
SETUP ERROR: Exceptions caught in Qt event loop:
[...snipped...]
  File "/home/jdg/debian/spyder-packages/spyder/build-area/spyder-5.2.0+dfsg1/spyder/widgets/browser.py", line 388, in load
    self.focusProxy().installEventFilter(self)
AttributeError: 'NoneType' object has no attribute 'installEventFilter'
________________________________________________________________________________

	[<TracebackEntry /usr/lib/python3/dist-packages/pytestqt/plugin.py:144>, <TracebackEntry /usr/lib/python3/dist-packages/pytestqt/exceptions.py:68>]

===End Flaky Test Report===
=========================== short test summary info ============================
ERROR spyder/plugins/onlinehelp/tests/test_pydocgui.py::test_pydocbrowser
ERROR spyder/plugins/onlinehelp/tests/test_pydocgui.py::test_get_pydoc[lib0]
ERROR spyder/plugins/onlinehelp/tests/test_pydocgui.py::test_get_pydoc[lib1]
============================== 3 errors in 13.13s ==============================
```

I then ran it on my regular (non-chroot) system, with lots more packages installed, and got a very different result: this time, the first two tests passed, but the second failed on a timeout error:
```
euler:~/debian/spyder-packages/spyder/build-area/spyder-5.2.0+dfsg1 $ xvfb-run -a -s "-screen 0 1024x768x24 +extension GLX" python3.9 -m pytest spyder/plugins/onlinehelp/tests/test_pydocgui.py 
============================= test session starts ==============================
platform linux -- Python 3.9.9, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
PyQt5 5.15.6 -- Qt runtime 5.15.2 -- Qt compiled 5.15.2
rootdir: /home/jdg/debian/spyder-packages/spyder/build-area/spyder-5.2.0+dfsg1, configfile: pytest.ini
plugins: typeguard-2.11.1, lazy-fixture-0.6.3, hypothesis-5.43.3, order-1.0.0, anyio-3.4.0, xvfb-2.0.0, mock-3.6.1, xdist-2.4.0, timeout-2.0.1, cov-3.0.0, forked-1.3.0, qt-4.0.2, dependency-0.5.1, flaky-3.7.0
collected 3 items                                                              

spyder/plugins/onlinehelp/tests/test_pydocgui.py ..                      [100%] [100%] [100%] [100%]F [100%]

=================================== FAILURES ===================================
_____________________________ test_get_pydoc[lib1] _____________________________

pydocbrowser = (<pytestqt.qtbot.QtBot object at 0x7f2c2e0db520>, <spyder.plugins.onlinehelp.widgets.PydocBrowser object at 0x7f2c2e0c4d30>)
lib = ('numpy.compat', 'numpy.compat', 2)

    @flaky(max_runs=5)
    @pytest.mark.parametrize(
        "lib", [('str', 'class str', 1),
                ('numpy.compat', 'numpy.compat', 2)
                ])
    @pytest.mark.skipif(
        sys.platform == 'darwin', reason="Does not work on Mac")
    def test_get_pydoc(pydocbrowser, lib):
        """
        Go to the documentation by url.
        Regression test for spyder-ide/spyder#10740
        """
        qtbot, browser = pydocbrowser
        element, doc, matches = lib
    
        webview = browser.webview
        element_url = browser.text_to_url(element)
        with qtbot.waitSignal(webview.loadFinished):
            browser.set_url(element_url)
    
        # Check number of matches. In Python 2 are 3 matches instead
        # of 2 for numpy.compat
>       qtbot.waitUntil(
            lambda: webview.get_number_matches(doc) in [matches, matches + 1])
E       pytestqt.exceptions.TimeoutError: waitUntil timed out in 5000 milliseconds

spyder/plugins/onlinehelp/tests/test_pydocgui.py:68: TimeoutError
=============================== warnings summary ===============================
../../../../../../../usr/lib/python3/dist-packages/qdarkstyle/__init__.py:207
  /usr/lib/python3/dist-packages/qdarkstyle/__init__.py:207: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    _logger.warn("No QCoreApplication instance found. "

spyder/plugins/onlinehelp/tests/test_pydocgui.py::test_pydocbrowser
  /usr/lib/python3/dist-packages/nbconvert/exporters/html.py:110: DeprecationWarning: 'contextfilter' is renamed to 'pass_context', the old name will be removed in Jinja 3.1.
    def markdown2html(self, context, source):

-- Docs: https://docs.pytest.org/en/stable/warnings.html
===Flaky Test Report===

test_get_pydoc[lib0] passed 1 out of the required 1 times. Success!
test_get_pydoc[lib1] failed (4 runs remaining out of 5).
	<class 'pytestqt.exceptions.TimeoutError'>
	waitUntil timed out in 5000 milliseconds
	[<TracebackEntry /home/jdg/debian/spyder-packages/spyder/build-area/spyder-5.2.0+dfsg1/spyder/plugins/onlinehelp/tests/test_pydocgui.py:68>]
test_get_pydoc[lib1] failed (3 runs remaining out of 5).
	<class 'pytestqt.exceptions.TimeoutError'>
	waitUntil timed out in 5000 milliseconds
	[<TracebackEntry /home/jdg/debian/spyder-packages/spyder/build-area/spyder-5.2.0+dfsg1/spyder/plugins/onlinehelp/tests/test_pydocgui.py:68>]
test_get_pydoc[lib1] failed (2 runs remaining out of 5).
	<class 'pytestqt.exceptions.TimeoutError'>
	waitUntil timed out in 5000 milliseconds
	[<TracebackEntry /home/jdg/debian/spyder-packages/spyder/build-area/spyder-5.2.0+dfsg1/spyder/plugins/onlinehelp/tests/test_pydocgui.py:68>]
test_get_pydoc[lib1] failed (1 runs remaining out of 5).
	<class 'pytestqt.exceptions.TimeoutError'>
	waitUntil timed out in 5000 milliseconds
	[<TracebackEntry /home/jdg/debian/spyder-packages/spyder/build-area/spyder-5.2.0+dfsg1/spyder/plugins/onlinehelp/tests/test_pydocgui.py:68>]
test_get_pydoc[lib1] failed; it passed 0 out of the required 1 times.
	<class 'pytestqt.exceptions.TimeoutError'>
	waitUntil timed out in 5000 milliseconds
	[<TracebackEntry /home/jdg/debian/spyder-packages/spyder/build-area/spyder-5.2.0+dfsg1/spyder/plugins/onlinehelp/tests/test_pydocgui.py:68>]

===End Flaky Test Report===
=========================== short test summary info ============================
FAILED spyder/plugins/onlinehelp/tests/test_pydocgui.py::test_get_pydoc[lib1]
=================== 1 failed, 2 passed, 2 warnings in 34.59s ===================
Release of profile requested but WebEnginePage still not deleted. Expect troubles !
```
So it would seem that there is a missing dependency causing the `'NoneType' object has no attribute 'installEventFilter'` errors, but I don't know what it is.  Do you have any idea?

There's a separate issue around the timeout, but that may or may not be a problem.

### What is the expected output? What do you see instead?

I expect the tests to pass ;-)

## Versions

* Spyder version: 5.2.0
* Python version: 3.9 and 3.10
* Qt version: 5.15.2
* PyQt version: 5.15.6+dfsg-1+b1
* Operating System name/version: Debian unstable and testing

### Dependencies

Erm, easier said than done as I'm not yet running Spyder 5.2.0 live...

**Comment by juliangilbey** [comment]
Ah, first problem solved: I needed to install the `python3-pyqt.qtwebengine` package, obviously; we'd removed it from the `setup.py` file (because of the old version requirements) but not manually specified the dependency.  The third test still fails with a timeout, though.  Looking at the test code more carefully, that is exactly what is being used as the test, so there is an issue here.

**Comment by juliangilbey** [comment]
Update: the timeout error still happens if I set `CI=true` in the environment.

**Comment by juliangilbey** [comment]
I just tried building 5.2.2 in Debian unstable (don't worry - I'm not releasing it yet!), and this test still fails:
```
___________________ ERROR at setup of test_get_pydoc[lib1] ____________________

qtbot = <pytestqt.qtbot.QtBot object at 0x7f8263cf7a30>

    @pytest.fixture
    def pydocbrowser(qtbot):
        """Set up pydocbrowser."""
        plugin_mock = MagicMock()
        plugin_mock.CONF_SECTION = 'onlinehelp'
        widget = PydocBrowser(parent=None, plugin=plugin_mock, name='pydoc')
        widget._setup()
        widget.setup()
        widget.resize(640, 480)
        widget.show()
    
>       with qtbot.waitSignal(widget.sig_load_finished, timeout=6000):
E       pytestqt.exceptions.TimeoutError: Signal sig_load_finished() not emitted after 6000 ms

/tmp/autopkgtest.l2aLOh/build.dEq/src/spyder/plugins/onlinehelp/tests/test_pydocgui.py:35: TimeoutError
```

**Comment by ccordoba12** [comment]
I can't reproduce this failure. Again, this points to a problem in your side.
