### ISSUE TITLE
Cannot open Spyder

### ISSUE THREAD

**Issue by Andry92** [spyder-ide/spyder#17072]
### What steps will reproduce the problem?

When I open Spyder, there is no window appeared.
Even with I open Spyder from Anaconda Navigator

### Traceback
```python-traceback
  File "C:\Users\anaconda3\lib\asyncio\windows_events.py", line 453, in finish_recv
    return ov.getresult()
OSError: [WinError 995] Operazione di I/O terminata a causa dell'uscita dal thread oppure della richiesta di un'applicazione

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\anaconda3\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "C:\Users\anaconda3\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\anaconda3\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 995] Operazione di I/O terminata a causa dell'uscita dal thread oppure della richiesta di un'applicazione
```

## Versions

* Spyder version: 4.2.1 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  2.0.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.29.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  23.4.0 (OK)
nbconvert >=4.0                 :  6.1.0 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.8.1 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.10.0 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.0 (OK)
qdarkstyle >=2.8                :  3.0.2 (OK)
qtawesome >=0.5.7               :  1.0.3 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.10.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  58.0.4 (OK)
sphinx >=0.6.6                  :  4.2.0 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.1 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  2.1.6 (OK)
zmq >=17                        :  22.3.0 (OK)

# Optional:
cython >=0.21                   :  0.29.25 (OK)
matplotlib >=2.0.0              :  3.5.0 (OK)
numpy >=1.7                     :  1.21.2 (OK)
pandas >=1.1.1                  :  1.3.4 (OK)
scipy >=0.17.0                  :  1.7.1 (OK)
sympy >=0.7.3                   :  1.9 (OK)
```

**Comment by dalthviz** [comment]
Hi @Andry92 thank you for the feedback. Could you try to update to Spyder 4.2.5 and check again?

Also, if you want to use a more updated Spyder version (5.2.1) I would suggest for you to create a new env using the conda-forge channel running from an Anaconda Prompt something like this:
    
   conda create -n spyder_env -c conda-forge python=3.8.5 spyder=5.2.1

And then use Spyder from that env

Let us know if something of the above helps!

**Comment by Andry92** [comment]
Hi,
I update from terminal (conda update spyder) ang get to the new Spyder version: 5.1.5
Now it works.
Thanks
