### ISSUE TITLE
MAYAVI 2 AND PYTHON 2.7.5 DO NOT WORK WELL

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1709]
_From [fpauli...@gmail.com](https://code.google.com/u/113453832516014220075/) on 2014-01-28T16:30:13Z_

HI,
WHEN I RUN THE FOLLOWING CODE INSPYDER IDE (Python (x,y) 2.7.5 in
Windows 7 64bit):

import numpy as np
from mayavi import mlab
 
grafic = mlab.surf(np.random.rand(30, 30))
mlab.colorbar(grafic, orientation='horizontal')
mlab.axes(grafic)

I CAN SEE THE SCENE BUT NO INTERACTION AND WITH THE FOLLOW MESSAGE:

Python 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

Imported NumPy 1.8.0, SciPy 0.13.2, Matplotlib 1.3.1
+ guidata 1.6.1, guiqwt 2.3.1
Type "scientific" for more details.
\>>> runfile('C:/Python27/Lib/site-packages/xy/test.py', wdir=r'C:/Python27/Lib/site-packages/xy')
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: vtkOpenGLCamera (0A42B238)
  Debug: Off
  Modified Time: 881536
  Reference Count: 2
  Registered Events: (none)
  ClippingRange: (0.01, 1000.01)
  DirectionOfProjection: (0, 0, -1)
  Distance: 1
  EyeAngle: 2
  FocalDisk: 1
  FocalPoint: (0, 0, 0)
  ViewShear: (0, 0, 1)
  ParallelProjection: Off
  ParallelScale: 1
  Position: (0, 0, 1)
  Stereo: Off
  Left Eye: 1
  Thickness: 1000
  ViewAngle: 30
  UseHorizontalViewAngle: 0
  UserTransform: (none)
(none)
  ViewPlaneNormal: (-0, -0, 1)
  ViewUp: (0, 1, 0)
  WindowCenter: (0, 0)
  UseOffAxisProjection: (0)
  ScreenBottomLeft: (-0.5, -0.5, -0.5)
  ScreenBottomRight: (0.5, -0.5, -0.5)
  ScreenTopRight: (0.5, 0.5, -0.5)
  EyeSeparation: (0.06)
  WorldToScreenMatrix: (04D0D788
    Debug: Off
    Modified Time: 881538
    Reference Count: 1
    Registered Events: (none)
    Elements:
        1 0 0 0 
        0 1 0 0 
        0 0 1 0 
        0 0 0 1 
  )
  EyeTransformMatrix: (04D0D5E8
    Debug: Off
    Modified Time: 881540
    Reference Count: 1
    Registered Events: (none)
    Elements:
        1 0 0 0 
        0 1 0 0 
        0 0 1 0 
        0 0 0 1 
  )
  ModelTransformMatrix: (04D0D1D8
    Debug: Off
    Modified Time: 881542
    Reference Count: 1
    Registered Events: (none)
    Elements:
        1 0 0 0 
        0 1 0 0 
        0 0 1 0 
        0 0 0 1 
  )

, trait: view_plane_normal, old value: [-0. -0.  1.], new value: [-0. -0.  1.]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "C:\Python27\lib\site-packages\tvtk\tvtk_classes.zip\tvtk_classes\camera.py", line 82, in _view_plane_normal_changed
    self._do_change(self._vtk_obj.SetViewPlaneNormal,
AttributeError: SetViewPlaneNormal
Exception occurred in traits notification handler for object: vtkOpenGLCamera (0A42B238)
  Debug: Off
  Modified Time: 886970
  Reference Count: 2
  Registered Events: 
    Registered Observers:
      vtkObserver (09D2B680)
        Event: 33
        EventName: ModifiedEvent
        Command: 0A573688
        Priority: 0
        Tag: 1
  ClippingRange: (0.01, 1000.01)
  DirectionOfProjection: (-0.57735, -0.57735, -0.57735)
  Distance: 1.73205
  EyeAngle: 2
  FocalDisk: 1
  FocalPoint: (0, 0, 0)
  ViewShear: (0, 0, 1)
  ParallelProjection: Off
  ParallelScale: 1
  Position: (1, 1, 1)
  Stereo: Off
  Left Eye: 1
  Thickness: 1000
  ViewAngle: 30
  UseHorizontalViewAngle: 0
  UserTransform: (none)
(none)
  ViewPlaneNormal: (0.57735, 0.57735, 0.57735)
  ViewUp: (0, 1, 0)
  WindowCenter: (0, 0)
  UseOffAxisProjection: (0)
  ScreenBottomLeft: (-0.5, -0.5, -0.5)
  ScreenBottomRight: (0.5, -0.5, -0.5)
  ScreenTopRight: (0.5, 0.5, -0.5)
  EyeSeparation: (0.06)
  WorldToScreenMatrix: (04D0D788
    Debug: Off
    Modified Time: 881538
    Reference Count: 1
    Registered Events: (none)
    Elements:
        1 0 0 0 
        0 1 0 0 
        0 0 1 0 
        0 0 0 1 
  )
  EyeTransformMatrix: (04D0D5E8
    Debug: Off
    Modified Time: 881540
    Reference Count: 1
    Registered Events: (none)
    Elements:
        1 0 0 0 
        0 1 0 0 
        0 0 1 0 
        0 0 0 1 
  )
  ModelTransformMatrix: (04D0D1D8
    Debug: Off
    Modified Time: 881542
    Reference Count: 1
    Registered Events: (none)
    Elements:
        1 0 0 0 
        0 1 0 0 
        0 0 1 0 
        0 0 0 1 
  )

, trait: view_plane_normal, old value: [-0. -0.  1.], new value: [ 0.57735027  0.57735027  0.57735027]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "C:\Python27\lib\site-packages\tvtk\tvtk_classes.zip\tvtk_classes\camera.py", line 82, in _view_plane_normal_changed
    self._do_change(self._vtk_obj.SetViewPlaneNormal,
AttributeError: SetViewPlaneNormal
Exception occurred in traits notification handler for object: vtkOpenGLCamera (0A42B238)
  Debug: Off
  Modified Time: 887006
  Reference Count: 2
  Registered Events: 
    Registered Observers:
      vtkObserver (09D2B680)
        Event: 33
        EventName: ModifiedEvent
        Command: 0A573688
        Priority: 0
        Tag: 1
  ClippingRange: (0.01, 1000.01)
  DirectionOfProjection: (-0.57735, -0.57735, -0.57735)
  Distance: 1.73205
  EyeAngle: 2
  FocalDisk: 1
  FocalPoint: (0, 0, 0)
  ViewShear: (0, 0, 1)
  ParallelProjection: Off
  ParallelScale: 1
  Position: (1, 1, 1)
  Stereo: Off
  Left Eye: 1
  Thickness: 1000
  ViewAngle: 30
  UseHorizontalViewAngle: 0
  UserTransform: (none)
(none)
  ViewPlaneNormal: (0.57735, 0.57735, 0.57735)
  ViewUp: (0, 0, 1)
  WindowCenter: (0, 0)
  UseOffAxisProjection: (0)
  ScreenBottomLeft: (-0.5, -0.5, -0.5)
  ScreenBottomRight: (0.5, -0.5, -0.5)
  ScreenTopRight: (0.5, 0.5, -0.5)
  EyeSeparation: (0.06)
  WorldToScreenMatrix: (04D0D788
    Debug: Off
    Modified Time: 881538
    Reference Count: 1
    Registered Events: (none)
    Elements:
        1 0 0 0 
        0 1 0 0 
        0 0 1 0 
        0 0 0 1 
  )
  EyeTransformMatrix: (04D0D5E8
    Debug: Off
    Modified Time: 881540
    Reference Count: 1
    Registered Events: (none)
    Elements:
        1 0 0 0 
        0 1 0 0 
        0 0 1 0 
        0 0 0 1 
  )
  ModelTransformMatrix: (04D0D1D8
    Debug: Off
    Modified Time: 881542
    Reference Count: 1
    Registered Events: (none)
    Elements:
        1 0 0 0 
        0 1 0 0 
        0 0 1 0 
        0 0 0 1 
  )

, trait: view_plane_normal, old value: [ 0.57735027  0.57735027  0.57735027], new value: [ 0.57735027  0.57735027  0.57735027]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\traits\trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "C:\Python27\lib\site-packages\tvtk\tvtk_classes.zip\tvtk_classes\camera.py", line 82, in _view_plane_normal_changed
    self._do_change(self._vtk_obj.SetViewPlaneNormal,
Attrib...

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1709_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-05T07:43:19Z_

Please report this bug with the PythonXY guys. It seems a problem with the Mayavi version they ship.

**Status:** WontFix
