### ISSUE TITLE
Terminal plugin triggers error in preferences

### ISSUE THREAD

**Issue by suedunham** [spyder-ide/spyder#17113]
### What steps will reproduce the problem?

I installed Anaconda on Windows 10. Yes, I'm aware of the standalone spyder installer, but so many answers to problems seem to be conda this and conda that, so I tried it this way. Anaconda provides an older Spyder version, so first I wanted to update that.

1. Installed Anaconda via exe
2. Opened Anaconda prompt and ran the following commands:
    1. conda update -n base -c defaults conda
    2. conda create -n spyder52 -c conda-forge spyder=5.2.1
3. Opened installation in new environment with the following commands:
    1. conda activate spyder52
    2. spyder

To this point, things are working fine. However, closing Spyder and running another command from the spyder52 environment to install the terminal plugin messes up the installation so that trying to open preferences results in the error.

conda install -c conda-forge spyder-terminal

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\Ed\anaconda3\envs\spyder52\lib\site-packages\spyder\plugins\preferences\plugin.py", line 276, in <lambda>
    lambda: self.open_dialog(main.prefs_dialog_size))
  File "C:\Users\Ed\anaconda3\envs\spyder52\lib\site-packages\spyder\plugins\preferences\plugin.py", line 258, in open_dialog
    self.get_main())
  File "C:\Users\Ed\anaconda3\envs\spyder52\lib\site-packages\spyder\plugins\preferences\widgets\container.py", line 62, in create_dialog
    page.initialize()
  File "C:\Users\Ed\anaconda3\envs\spyder52\lib\site-packages\spyder\plugins\preferences\api.py", line 80, in initialize
    self.setup_page()
  File "C:\Users\Ed\anaconda3\envs\spyder52\lib\site-packages\spyder\api\plugin_registration\_confpage.py", line 71, in setup_page
    plugin_loc_name = PluginClass.get_name()
TypeError: get_name() missing 1 required positional argument: 'self'
```

## Versions

* Spyder version: 5.2.1 
* Python version: 3.7.12
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.0.0 (OK)
cookiecutter >=1.6.0                 :  1.6.0 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.0.2 (OK)
IPython >=7.6.0                      :  7.30.1 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.8.9 (OK)
jsonschema >=3.2.0                   :  4.3.2 (OK)
keyring >=17.0.0                     :  23.4.0 (OK)
nbconvert >=4.0                      :  6.3.0 (OK)
numpydoc >=0.6.0                     :  1.1.0 (OK)
paramiko >=2.4.0                     :  2.9.1 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.8.0 (OK)
pygments >=2.0                       :  2.10.0 (OK)
pylint >=2.5.0                       :  2.12.2 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0                 :  1.3.3 (OK)
pylsp_black >=1.0.0                  :  1.0.1 (OK)
qdarkstyle =3.0.2                    :  3.0.2 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0             :  5.2.2 (OK)
qtpy >=1.5.0                         :  2.0.0 (OK)
rtree >=0.9.7                        :  0.9.7 (OK)
setuptools >=49.6.0                  :  60.1.0 (OK)
sphinx >=0.6.6                       :  4.3.2 (OK)
spyder_kernels >=2.2.0;<2.3.0        :  2.2.0 (OK)
textdistance >=4.2.0                 :  4.2.2 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.6 (OK)
zmq >=17                             :  22.3.0 (OK)

# Optional:
cython >=0.21                        :  None (NOK)
matplotlib >=2.0.0                   :  None (NOK)
numpy >=1.7                          :  None (NOK)
pandas >=1.1.1                       :  None (NOK)
scipy >=0.17.0                       :  None (NOK)
sympy >=0.7.3                        :  None (NOK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.1.0 :  1.1.0 (OK)
```

**Comment by ccordoba12** [comment]
Hey @suedunham, thanks for reporting. Please update to Spyder-terminal 1.2.0, which has a fix for this problem (it's available in conda-forge since today).
