### ISSUE TITLE
window reporting 

### ISSUE THREAD

**Issue by ricbenmar** [spyder-ide/spyder#17123]
### What steps will reproduce the problem?

this window was open at closing one file, it has happened several times 
and I do not know how to solve it.
Regards,
R. Benito

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 1910, in _save_file
    self.modification_changed(index=index)
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 2366, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 1910, in _save_file
    self.modification_changed(index=index)
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 2366, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 1910, in _save_file
    self.modification_changed(index=index)
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 2366, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 1910, in _save_file
    self.modification_changed(index=index)
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 2366, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 1910, in _save_file
    self.modification_changed(index=index)
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 2366, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 1910, in _save_file
    self.modification_changed(index=index)
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 2366, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 1910, in _save_file
    self.modification_changed(index=index)
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 2366, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 1910, in _save_file
    self.modification_changed(index=index)
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 2366, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 1910, in _save_file
    self.modification_changed(index=index)
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 2366, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 1910, in _save_file
    self.modification_changed(index=index)
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 2366, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 1910, in _save_file
    self.modification_changed(index=index)
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 2366, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
```

## Versions

* Spyder version: 5.2.1 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.30.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.8.9 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.3.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.1 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  1.11.3 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  59.6.0 (OK)
sphinx >=0.6.6                :  4.3.1 (OK)
spyder_kernels >=2.2.0;<2.3.0 :  2.2.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.25 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment]
Hola @ricbenmar, gracias por reportar tu problema. Hemos recibido varios reportes de este tipo, pero desafortunadamente no hemos podido arreglarlo porque no hemos sido capaces de reproducirlo.

Así que si pudieses darnos una serie de pasos simples y precisos que siempre generen este error, te lo agradeceríamos mucho. De lo contrario, me temo que tendríamos que cerrar este reporte y esperar a que alguien nos ayude a reproducirlo.

**Comment by ricbenmar** [comment]
I was working with a python file ICE - MEP.py that is about Formula 1 engines and when closing the app a issue reporter: 
Spyder has encountered an internal error

**Comment by ccordoba12** [comment]
@ricbenmar, that description is not enough for us to solve this problem. We need a series of simple steps that always generate this problem, so we can reproduce it on our side.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
