### ISSUE TITLE
spyder

### ISSUE THREAD

**Issue by 0Louis14** [spyder-ide/spyder#17148]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "E:\0clue\anaconda\envs\env_gpu\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):
  File "E:\0clue\anaconda\envs\env_gpu\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "E:\0clue\anaconda\envs\env_gpu\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
      File "E:\0clue\anaconda\envs\env_gpu\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 215, in _handle_execute_reply

Traceback (most recent call last):
  File "E:\0clue\anaconda\envs\env_gpu\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "E:\0clue\anaconda\envs\env_gpu\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):
  File "E:\0clue\anaconda\envs\env_gpu\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):
  File "E:\0clue\anaconda\envs\env_gpu\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):
  File "E:\0clue\anaconda\envs\env_gpu\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):
  File "E:\0clue\anaconda\envs\env_gpu\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
      File "E:\0clue\anaconda\envs\env_gpu\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 215, in _handle_execute_reply

Traceback (most recent call last):
  File "E:\0clue\anaconda\envs\env_gpu\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.15
* Qt Versions: 5.12.9, PyQt5 5.12.3 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  2.4.0 (OK)
pycodestyle >=2.3:  2.8.0 (OK)
pygments >=2.0   :  2.11.1 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.19.5 (OK)
sphinx >=0.6.6   :  4.3.2 (OK)
rope >=0.9.4     :  0.22.0 (OK)
jedi >=0.9.0     :  0.17.2 (OK)
nbconvert >=4.0  :  6.0.7 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  5.2.2 (OK)
IPython >=4.0    :  7.16.1 (OK)
pylint >=0.25    :  1.8.4 (OK)

```

**Comment by ccordoba12** [comment]
Hey @0Louis14, thanks for reporting. This problem is caused because Spyder 3.2.3 (your current version, released more than three years) doesn't work with Qtconsole 5.2.2 (the latest one, released some weeks ago).

To solve it, you have have to remove your `env_gpu` environment and create a new one with the latest Spyder version available in Anaconda on it (5.1.5). Another option is to install older versions of qtconsole until you find one that works.
