### ISSUE TITLE
Console dying(sometimes cant restart kernel without restart Spyder)

### ISSUE THREAD

**Issue by Paul4936** [spyder-ide/spyder#17153]
### What steps will reproduce the problem?

1)install latest Python, spyder and so on(Arch linux...)
2) evaluate with ctrl+enter code below
```
from requests_html import AsyncHTMLSession
from bs4 import BeautifulSoup
import nest_asyncio

asession = AsyncHTMLSession()

nest_asyncio.apply()
async def get_1():
    url="https://browser-info.ru"
    r = await asession.get(url)

    await r.html.arender(timeout=24)
    return r

r = asession.run(get_1)[0]
print(r)
```

3)try to type in console 
`r.html.raw_html`

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.10/site-packages/spyder/plugins/ipythonconsole/widgets/namespacebrowser.py", line 212, in _handle_execute_reply
    super(NamepaceBrowserWidget, self)._handle_execute_reply(msg)
  File "/usr/lib/python3.10/site-packages/qtconsole/jupyter_widget.py", line 196, in _handle_execute_reply
    super()._handle_execute_reply(msg)
  File "/usr/lib/python3.10/site-packages/qtconsole/frontend_widget.py", line 479, in _handle_execute_reply
    self._show_interpreter_prompt_for_reply(msg)
  File "/usr/lib/python3.10/site-packages/qtconsole/jupyter_widget.py", line 447, in _show_interpreter_prompt_for_reply
    self._show_interpreter_prompt(previous_prompt_number + 1)
  File "/usr/lib/python3.10/site-packages/qtconsole/jupyter_widget.py", line 388, in _show_interpreter_prompt
    self._show_prompt(self._make_in_prompt(number), html=True)
  File "/usr/lib/python3.10/site-packages/spyder/plugins/ipythonconsole/widgets/debugging.py", line 630, in _show_prompt
    super(DebuggingWidget, self)._show_prompt(prompt, html, newline)
  File "/usr/lib/python3.10/site-packages/qtconsole/console_widget.py", line 2474, in _show_prompt
    self._flush_pending_stream()
  File "/usr/lib/python3.10/site-packages/qtconsole/console_widget.py", line 1662, in _flush_pending_stream
    self._pending_text_flush_interval.setInterval(max(100,
TypeError: setInterval(self, int): argument 1 has unexpected type 'float'
```

## Versions

* Spyder version: 5.2.0 
* Python version: 3.10.1
* Qt version: 5.15.2
* PyQt5 version: 5.15.6
* Operating System: Linux 5.10.75-1-lts

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.31.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.8.9 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.1 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.1;<1.4.0          :  1.3.2 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle >=3.0.2            :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.1 (OK)
qtpy >=1.5.0                  :  1.11.2 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  57.4.0 (OK)
sphinx >=0.6.6                :  4.3.2 (OK)
spyder_kernels >=2.2.0;<2.3.0 :  2.2.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  0.10.7 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.26 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  None (OK)
```

**Comment by ccordoba12** [comment]
Hey @Paul4936, thanks for reporting. This bug will be fixed in the next version of Qtconsole (one of our dependencies), to be released in a couple of months.

In the meantime, please use Python 3.9 (Spyder is not ready yet for 3.10 due to these small bugs).
