### ISSUE TITLE
Crash after apply En/Disable Linting options

### ISSUE THREAD

**Issue by Arthurob** [spyder-ide/spyder#17160]
### What steps will reproduce the problem?

Crash aftet pressing apply on En/Disable Linting options in preferences

### Traceback
```python-traceback
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 407, in _rpc_call
    meth(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 1599, in call_all_editorstacks
    method = getattr(editorstack, method)
TypeError: getattr(): attribute name must be string
```

## Versions

* Spyder version: 5.1.1 
* Python version: 3.6.13
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 8.1

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.0 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.16.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.17.2 (OK)
jsonschema >=3.2.0            :  4.1.2 (OK)
keyring >=17.0.0              :  23.2.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.9.1 (OK)
parso >=0.7.0;<0.9.0          :  0.7.1 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.1 (OK)
pylint >=2.5.0                :  2.11.1 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.1;<1.3.0          :  1.2.1 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.1.0             :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.0 (OK)
rtree >=0.9.4                 :  0.9.4 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.3.0 (OK)
spyder_kernels >=2.1.0;<2.2.0 :  2.1.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.19.5 (OK)
pandas >=1.1.1                :  1.1.5 (OK)
scipy >=0.17.0                :  1.5.3 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @Arthurob, thanks for reporting. This is fixed in our latest version (5.2.1), so please update to it.

Since it seems you're using conda-forge, you shouldn't have a problem with that.

**Comment by Arthurob** [comment]
Hey @ccordoba12, thanks for the info. Next time a bug happens I will check if it has been reported/fixed already, my apologies.

**Comment by ccordoba12** [comment]
No worries, it's fine. We receive about 200 bug reports per month, so it's not easy to track them.
