### ISSUE TITLE
backend bug: not being able to change backend and connect the kernal

### ISSUE THREAD

**Issue by Radiumpolonide** [spyder-ide/spyder#17180]
### What steps will reproduce the problem?

First raised a problem when I started: raise ValueError(f"Key {key}: {ve}") from None ValueError: Key backend: 'qt4agg' is not a valid value for backend; supported values are ['GTK3Agg', 'GTK3Cairo', 'GTK4Agg', 'GTK4Cairo', 'MacOSX', 'nbAgg', 'QtAgg', 'QtCairo', 'Qt5Agg', 'Qt5Cairo', 'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']

And then I changed the setting in Tools --> Preference--> IPython  console--> Graphic -->backend-->Tkinker, but I cant connect to kernal. 

When I tried to change a new backend, that error appears.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\spyder\plugins\preferences\widgets\configdialog.py", line 127, in accept
    configpage.apply_changes()
  File "D:\Anaconda3\lib\site-packages\spyder\plugins\preferences\api.py", line 110, in apply_changes
    self.apply_callback()
  File "D:\Anaconda3\lib\site-packages\spyder\plugins\preferences\api.py", line 142, in <lambda>
    self._apply_settings_tabs(self.changed_options))
  File "D:\Anaconda3\lib\site-packages\spyder\plugins\preferences\api.py", line 170, in _apply_settings_tabs
    self.apply_settings(options)
  File "D:\Anaconda3\lib\site-packages\spyder\api\preferences.py", line 104, in wrapper
    func(opts)
  File "D:\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 454, in apply_plugin_settings
    for client in self.clients]
  File "D:\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 454, in <listcomp>
    for client in self.clients]
  File "D:\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 353, in get_matplotlib_backend
    blocking=True).get_matplotlib_backend()
  File "D:\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 555, in __call__
    call_dict, call_data, self._comm_id)
  File "D:\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 212, in _get_call_return_value
    raise CommError("Cannot block on a disconnected comm")
spyder_kernels.comms.commbase.CommError: Cannot block on a disconnected comm
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.7.11
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.25 (OK)
matplotlib >=2.0.0            :  3.5.0 (OK)
numpy >=1.7                   :  1.21.2 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by dalthviz** [comment]
Hi @Radiumpolonide thank you for the feedback! I think this is partially a duplicate of #15875. However there are other issues as the one you mentioned about the possible values to set the backend. Our next release (5.2.2) will include multiple fixes regarding the matplotlib backend configuration. To check the latest release available you can go to: https://github.com/spyder-ide/spyder/releases 

Also, If you want to check a more recent version of Spyder you will need to either create a new env using the conda-forge channel (where the latest releases of Spyder are available) or test our standalone installer (link available inside the latest release page description/list of assets).

When our new release is out please let us know if updating helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
