### ISSUE TITLE
Saving variables from the Variables pane

### ISSUE THREAD

**Issue by jaBote** [spyder-ide/spyder#17199]
### What steps will reproduce the problem?

I have tried to save variables on the Variables pane by selecting and saving them via the save feature. This has already happened twice so that's why I find it useful to report.

I have been shown and selected where to save the data with .spydata format.

However, later all variables disappeared and message "Restarting kernel..." showed on the console, then I was presented with the issue reporter.

The variables I have been trying to save are the three variables used in this seaborn call (the program ran succesfully to completiom, manually saving these variables later is what caused this):

```python
ax = sns.heatmap(O1_rel_values, annot=True, fmt=".2f", xticklabels=x_labels, yticklabels=y_labels, linewidths=.5)
```

O1_rel_values is a 10-element list, each one is a 10-element list;
x_labels is a 10-element list;
y_labels is a 10-element list;

Despite using Gurobi for optimization, all these are regular lists and a list of lists.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\javot\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 124, in comm_channel_manager
    yield
  File "C:\Users\javot\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 216, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
  File "C:\Users\javot\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 432, in _get_call_return_value
    self._wait_reply(call_id, call_name, timeout)
  File "C:\Users\javot\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 238, in _wait_reply
    self._wait(got_reply, self._sig_got_reply, timeout_msg, timeout)
  File "C:\Users\javot\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 275, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for {'b3a630cd08aa4eb6a5c1944cd88050e3': (True, None)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\javot\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\main_widget.py", line 236, in <lambda>
    triggered=lambda x: self.save_data(),
  File "C:\Users\javot\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\main_widget.py", line 569, in save_data
    nsb.save_data()
  File "C:\Users\javot\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\namespacebrowser.py", line 255, in save_data
    error_message = self.shellwidget.save_namespace(self.filename)
  File "C:\Users\javot\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 176, in save_namespace
    return self.call_kernel(
  File "C:\Users\javot\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 554, in __call__
    return self._comms_wrapper._get_call_return_value(
  File "C:\Users\javot\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 216, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
  File "C:\Users\javot\anaconda3\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\javot\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 127, in comm_channel_manager
    self._comms[comm_id]['comm']._send_channel = (
KeyError: '8d84824c762111ecaa27f09e4a2f9de1'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.25 (OK)
matplotlib >=2.0.0            :  3.5.0 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment]
@jaBote, thanks for reporting. Please provide the full code example that generated your plots and data, so we can use it on our side to reproduce your problem.

**Comment by jaBote** [comment]
Hello,  @ccordoba12:

I've been able to narrow it down to Gurobi Optimization package (possibly related to my other issue #17016?). 
O1_rel_values, x_labels, y_labels had no interference with that as this code and trying to save these variables runs just fine:

```python
valores  = []
x_labels = []
y_labels = []
for i in range(10):
    valores.append([])
    y_labels.append(i)
    for j in range(10):
        if i == 0: # just all values for j once
            x_labels.append(j)
        valores[i].append(i+2*j)
```

However, this code also runs fine BUT trying to save variables causes a kernel restart, lossing all variables and the issue reporter to appear.

```python
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 17 20:24:11 2022

@author: jaBote
"""

import gurobipy as g

m = g.Model("Test enable disable constraint with M")
 
alfa = m.addVar(vtype=g.GRB.BINARY, name="alfa")
w = m.addVar(vtype=g.GRB.INTEGER, name="w") 
m.update()

val = 1
M = 1000

m.addConstr(M*alfa >= (w+val),"constr1")
m.addConstr(alfa <= (w+val)*M,"constr2")

m.addConstr(w <= 3,"constr3")
m.addConstr(w+val >= 0,"constr4")

m.setObjective(w, g.GRB.MINIMIZE)

m.optimize()

print([ (v.varName, v.x) for v in m.getVars()])
print("Runtime:",m.RunTime,"; MIPgap:",m.MIPgap)
```

I thought selecting both variables then clicking on the "Save Variables" icon would just save the variables I was interested in, but it tries to save everything instead. 

For example, trying to save just val and M...
![imagen](https://user-images.githubusercontent.com/4266028/149832879-821caf1c-20f5-4356-97d3-9b7f0dd02173.png)

For the prior graph, I couldn't have just removed other variables because they were still useful, as I was trying to save the plot data only. 

Maybe this can also serve as a suggestion for a future release?

**Comment by ccordoba12** [comment]
I think this problem happens because the Variable Explorer takes too much time or is unable to save the data you already loaded. So the only thing we can do is to catch the error and inform users about it.
