### ISSUE TITLE
error in layouts

### ISSUE THREAD

**Issue by varadpatil** [spyder-ide/spyder#17211]
### What steps will reproduce the problem?

When i opened spyder the default layout that I has set was not there. Then I switched it to spyder default one, which made the spyder window look darker ( like when there is a pop up window, the main spyder window in the backround looks dark). Then I tried switching it to matlab layout and this error happened.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/varad/miniconda3/envs/ayudev/lib/python3.9/site-packages/spyder/plugins/layout/container.py", line 195, in <lambda>
    return lambda: self.quick_layout_switch(i)
  File "/home/varad/miniconda3/envs/ayudev/lib/python3.9/site-packages/spyder/plugins/layout/container.py", line 439, in quick_layout_switch
    self._current_quick_layout = names.index(
ValueError: 'Matlab layout' is not in list
```

## Versions

* Spyder version: 5.2.1 
* Python version: 3.9.9
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Linux 5.13.0-25-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  8.0.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.1 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.5.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.2.0;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.3.2 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by dalthviz** [comment]
Hi @varadpatil thank you for the feedback! Did you do a clean install to have the latest Spyder or did you update from an old version?

I would suggest to check if resetting the preferences helps. You can do that by running from a terminal with your env activated `spyder --reset`

Let us know if something of the above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
