### ISSUE TITLE
Crash on bad IPython config

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#17213]
## Description
Crash when closing a console which shows an error. The restarter is not properly stopped.

### What steps will reproduce the problem?

 1- Create a console with an error at launch
```python
import os.path as osp
from IPython.core.application import get_ipython_dir
ipy_kernel_cfg = osp.join(get_ipython_dir(), 'profile_default',
                          'ipython_kernel_config.py')
with open(ipy_kernel_cfg, 'w') as f:
    # This option must be a string, not an int
    f.write("c.InteractiveShellApp.extra_extension = 1")
```
 2- close the console
 3- Crash

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\qtconsole\manager.py", line 27, in poll
    super().poll()
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\restarter.py", line 143, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\utils.py", line 26, in wrapped
    raise e
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "C:\ProgramData\Anaconda3\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 517, in _async_restart_kernel
    await ensure_async(self.start_kernel(**self._launch_args))
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\utils.py", line 26, in wrapped
    raise e
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "C:\ProgramData\Anaconda3\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 362, in _async_start_kernel
    raise e
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 351, in _async_start_kernel
    await ensure_async(self._launch_kernel(kernel_cmd, **kw))
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\utils.py", line 26, in wrapped
    raise e
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "C:\ProgramData\Anaconda3\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 269, in _async_launch_kernel
    connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\provisioning\local_provisioner.py", line 179, in launch_kernel
    self.process = launch_kernel(cmd, **scrubbed_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 169, in launch_kernel
    raise ex
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 157, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 804, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1174, in _get_handles
    c2pwrite = msvcrt.get_osfhandle(stdout.fileno())
ValueError: I/O operation on closed file
```

## Versions

* Spyder version: 5.3.0.dev0 075349a769
* Python version: 3.8.5
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jellyfish >=0.7               :  0.8.9 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0                :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.2 (OK)
pylsp_black >=1.0.0           :  1.0.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.2.0 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.2.0;<2.3.0 :  2.3.0.dev0 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.25 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by dalthviz** [comment]
Thanks @impact27! Should we put this for v5.2.2 @ccordoba12 ?

**Comment by ccordoba12** [comment]
I can't reproduce this on Linux and we have a test for this too:

https://github.com/spyder-ide/spyder/blob/966839c79d4cbd1021cccd5c7bbfad9648916118/spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py#L1343-L1371

**Comment by impact27** [comment]
The test doesn’t actually test that. I made some modifications to the tests and this test started to fail, which is how I found this bug. Basically this test primes the bug, but doesn’t close the kernel. The kernel is closed at the beginning of the next test. Pytest doesn’t really care about setup errors and just tries again, which works. I changed it to closing the console at the end of the test, which triggers the bug.

**Comment by impact27** [comment]
Also the crash only happens ~ 30s after closing the errorred kernel

**Comment by impact27** [comment]
This is reproduced in the CI. Example on a random PR: https://github.com/spyder-ide/spyder/runs/4864185692?check_suite_focus=true

On linux, fast test, after the tests suceed, you get:
```
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/test/lib/python3.7/site-packages/qtconsole/manager.py", line 27, in poll
    super().poll()
  File "/usr/share/miniconda3/envs/test/lib/python3.7/site-packages/jupyter_client/restarter.py", line 143, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "/usr/share/miniconda3/envs/test/lib/python3.7/site-packages/jupyter_client/utils.py", line 26, in wrapped
    raise e
  File "/usr/share/miniconda3/envs/test/lib/python3.7/site-packages/jupyter_client/utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "/usr/share/miniconda3/envs/test/lib/python3.7/site-packages/nest_asyncio.py", line 81, in run_until_complete
    return f.result()
  File "/usr/share/miniconda3/envs/test/lib/python3.7/asyncio/futures.py", line 181, in result
    raise self._exception
  File "/usr/share/miniconda3/envs/test/lib/python3.7/asyncio/tasks.py", line 249, in __step
    result = coro.send(None)
  File "/usr/share/miniconda3/envs/test/lib/python3.7/site-packages/jupyter_client/manager.py", line 530, in _async_restart_kernel
    await ensure_async(self.start_kernel(**self._launch_args))
  File "/usr/share/miniconda3/envs/test/lib/python3.7/site-packages/jupyter_client/utils.py", line 26, in wrapped
    raise e
  File "/usr/share/miniconda3/envs/test/lib/python3.7/site-packages/jupyter_client/utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "/usr/share/miniconda3/envs/test/lib/python3.7/site-packages/nest_asyncio.py", line 81, in run_until_complete
    return f.result()
  File "/usr/share/miniconda3/envs/test/lib/python3.7/asyncio/futures.py", line 181, in result
    raise self._exception
  File "/usr/share/miniconda3/envs/test/lib/python3.7/asyncio/tasks.py", line 249, in __step
    result = coro.send(None)
  File "/usr/share/miniconda3/envs/test/lib/python3.7/site-packages/jupyter_client/manager.py", line 79, in wrapper
    raise e
  File "/usr/share/miniconda3/envs/test/lib/python3.7/site-packages/jupyter_client/manager.py", line 71, in wrapper
    out = await method(self, *args, **kwargs)
  File "/usr/share/miniconda3/envs/test/lib/python3.7/site-packages/jupyter_client/manager.py", line 380, in _async_start_kernel
    await ensure_async(self._launch_kernel(kernel_cmd, **kw))
  File "/usr/share/miniconda3/envs/test/lib/python3.7/site-packages/jupyter_client/utils.py", line 26, in wrapped
    raise e
  File "/usr/share/miniconda3/envs/test/lib/python3.7/site-packages/jupyter_client/utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "/usr/share/miniconda3/envs/test/lib/python3.7/site-packages/nest_asyncio.py", line 81, in run_until_complete
    return f.result()
  File "/usr/share/miniconda3/envs/test/lib/python3.7/asyncio/futures.py", line 181, in result
    raise self._exception
  File "/usr/share/miniconda3/envs/test/lib/python3.7/asyncio/tasks.py", line 249, in __step
    result = coro.send(None)
  File "/usr/share/miniconda3/envs/test/lib/python3.7/site-packages/jupyter_client/manager.py", line 300, in _async_launch_kernel
    connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
  File "/usr/share/miniconda3/envs/test/lib/python3.7/site-packages/jupyter_client/provisioning/local_provisioner.py", line 179, in launch_kernel
    self.process = launch_kernel(cmd, **scrubbed_kwargs)
  File "/usr/share/miniconda3/envs/test/lib/python3.7/site-packages/jupyter_client/launcher.py", line 169, in launch_kernel
    raise ex
  File "/usr/share/miniconda3/envs/test/lib/python3.7/site-packages/jupyter_client/launcher.py", line 157, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/usr/share/miniconda3/envs/test/lib/python3.7/subprocess.py", line 753, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/usr/share/miniconda3/envs/test/lib/python3.7/subprocess.py", line 1388, in _get_handles
    c2pwrite = stdout.fileno()
ValueError: I/O operation on closed file

```
