### ISSUE TITLE
Object inspector raises TypeError

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1722]
_From [ibac...@gmail.com](https://code.google.com/u/110943938965681637047/) on 2014-02-04T19:50:37Z_

Spyder Version:  2.1.9
Python Version:  2.7.3
Qt Version:      4.8.1, PyQt4 (API v2) 4.9.1 on Linux
IPython 0.12.1 

What steps will reproduce the problem?

 1. Using an ipython interpreter
2.Typing the opening parentheses of a function in the console.  For example:
plt.plot( What is the expected output? What do you see instead? I expect to the object inspector to show me the doc-string of the function being called.

Sometimes (not always, and I can't reproduce it all the time) I get switched to the Internal Console and an error is raised:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/shell.py", line 300, in keyPressEvent
    self.postprocess_keyevent(event)
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/shell.py", line 795, in postprocess_keyevent
    ShellBaseWidget.postprocess_keyevent(self, event)
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/shell.py", line 435, in postprocess_keyevent
    self._key_parenleft(text)
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/shell.py", line 880, in _key_parenleft
    self.show_docstring(last_obj, call=True)
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/shell.py", line 1056, in show_docstring
    self.inspector.set_object_text(text, ignore_unknown=True)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 531, in set_object_text
    found = self.show_help(text, ignore_unknown=ignore_unknown)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 744, in show_help
    self.set_plain_text(hlp_text, is_code=is_code)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 500, in set_plain_text
    self.plain_text.set_text(text, is_code)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 185, in set_text
    self.editor.set_text(text)
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/sourcecode/codeeditor.py", line 1379, in set_text
    self.setPlainText(text)
TypeError: QPlainTextEdit.setPlainText(QString): argument 1 has unexpected type 'list'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1722_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-02-07T05:16:26Z_

Both your version of Spyder and IPython are way too old (Ubuntu 12.04?). Please update them and report back if you're still having this problem.

**Comment by spyder-issues-migrator** [comment]
_From [ibac...@gmail.com](https://code.google.com/u/110943938965681637047/) on 2014-02-07T09:49:04Z_

According the to standard Ubuntu repositories my IPython and my Spyder are up-to-date.  I've downloaded spyder from github and IPython 1.1.0 via pip.  Hopefully this solves the issue.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-02-07T11:29:26Z_

Please let us know if that's the case.

**Comment by ccordoba12** [comment]
Closing because of lack of feedback.
