### ISSUE TITLE
Printing variable from history

### ISSUE THREAD

**Issue by ChandraRai** [spyder-ide/spyder#17248]
### What steps will reproduce the problem?

# -*- coding: utf-8 -*-
"""
Created on Sun Jan 23 14:41:56 2022

@author: Chandra
"""

# Import libraries
import pandas as pd
import numpy as np

df = pd.read_excel("test.xlsx")
# print(df.dtypes)

# Q1. From Table 1, determine dissimilarity matrices for the numeric data using the following metrics:
# (a) Euclidean
# (b) Manhattan
# (c) Supremum

numeric_data = df.drop(['Gender(M/F)','Smoker(Y/N)', 'Diabetic(Y/N)','Family History of Heart Disease',
                        'Family History of Cancer(Y/N)', 'Family History of Diabetes(Y/N)', 'Family History of Stroke(Y/N)'], axis=1)

numeric_data_numpy = numeric_data.to_numpy()
# print(numeric_data.dtypes)
# print(numeric_data_numpy)
print("\n")

'''
# Euclidean distance
E_List = []
for i in range(len(numeric_data_numpy)):    
    for j in range(len(numeric_data_numpy)):
        val = np.sqrt(sum((numeric_data_numpy[i,:] - numeric_data_numpy[j,:])**2))
        E_List.append(round(val, 2))

e_arr = np.array(E_List)    
print("Euclidean Dissimilarity Proximity: \n", e_arr.reshape(len(numeric_data_numpy), len(numeric_data_numpy)))
 

# Manhattan distance
M_List = []
for i in range(len(numeric_data_numpy)):    
    for j in range(len(numeric_data_numpy)):
        M_List.append(sum(abs(numeric_data_numpy[i,:] - numeric_data_numpy[j,:])))
        
m_arr = np.array(M_List)    
print("\nManhattan Dissimilarity Proximity: \n", m_arr.reshape(len(numeric_data_numpy), len(numeric_data_numpy)))

# Supremum distance
S_List = []
for i in range(len(numeric_data_numpy)):
    # print("\n")
    for j in range(len(numeric_data_numpy)):
        # print(max(abs(numeric_data_numpy[i,:] - numeric_data_numpy[j,:])))
        S_List.append((max(abs(numeric_data_numpy[i,:] - numeric_data_numpy[j,:]))))

s_arr = np.array(S_List)    
print("\nSupremum Dissimilarity Proximity: \n", s_arr.reshape(len(numeric_data_numpy), len(numeric_data_numpy)))
'''

# Q2. From Table 1, determine dissimilarity matrices for the binary data:
# (a) Assuming that all of the attributes are symmetric (Y and N are equally important)
# (b) Assuming that all of the attributes are asymmetric (where we consider Y to be unimportant)

# print(df.dtypes)
binary_data = df.drop(['Age (yrs)','Weight(lbs)', 'Height(in)','Blood Pressure(systolic)',
                        'Blood Pressure(diastolic)', 'Heart Rate(bpm)'], axis=1)
# print(binary_data.dtypes)
# print(binary_data)

binary_data_numpy = binary_data.to_numpy()
# print(binary_data_numpy)

number_of_mismatch = 0
Cxx = np.zeros(12)

for i in range(len(binary_data_numpy)):
    for j in range(len(binary_data_numpy)):        
        for k in range(len(binary_data.columns)):
            if binary_data_numpy[i][k] != binary_data_numpy[j][k]:
                number_of_mismatch += 1 
    
        Cxx[j] = number_of_mismatch    
        number_of_mismatch = 0
    

    
# print(number_of_mismatch)    
# print(Cxx)

   
for k in range(len(binary_data_numpy)):
    for i in range(len(binary_data.columns)):
        if binary_data_numpy[k][i] != binary_data_numpy[k][i]:
            number_of_mismatch += 1 
    
    
Cxx[k] = number_of_mismatch
               
print(number_of_mismatch)    
print(Cxx)
    

### Traceback
```python-traceback
Traceback (most recent call last):
  File "D:\Softwares\AnacodaSys\lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 169, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "D:\Softwares\AnacodaSys\lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 169, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "D:\Softwares\AnacodaSys\lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 169, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "D:\Softwares\AnacodaSys\lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 169, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
ZeroDivisionError: division by zero
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=1.0                  :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.21.2 (OK)
pandas >=1.1.1                :  1.3.3 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ChandraRai** [comment]
Can't reproduce again
