### ISSUE TITLE
Error when trying to open Preferences command

### ISSUE THREAD

**Issue by abbassi95** [spyder-ide/spyder#17277]
### What steps will reproduce the problem?

command Tools
command Preferences, the error appears then 

### Traceback
```python-traceback
Traceback (most recent call last):
  File "c:\tmp\envs\py39\lib\site-packages\spyder\plugins\preferences\plugin.py", line 276, in <lambda>
    lambda: self.open_dialog(main.prefs_dialog_size))
  File "c:\tmp\envs\py39\lib\site-packages\spyder\plugins\preferences\plugin.py", line 256, in open_dialog
    container.create_dialog(
  File "c:\tmp\envs\py39\lib\site-packages\spyder\plugins\preferences\widgets\container.py", line 85, in create_dialog
    self.dialog.show()
RuntimeError: wrapped C/C++ object of type ConfigDialog has been deleted
Traceback (most recent call last):
  File "c:\tmp\envs\py39\lib\site-packages\spyder\plugins\preferences\plugin.py", line 276, in <lambda>
    lambda: self.open_dialog(main.prefs_dialog_size))
  File "c:\tmp\envs\py39\lib\site-packages\spyder\plugins\preferences\plugin.py", line 256, in open_dialog
    container.create_dialog(
  File "c:\tmp\envs\py39\lib\site-packages\spyder\plugins\preferences\widgets\container.py", line 85, in create_dialog
    self.dialog.show()
RuntimeError: wrapped C/C++ object of type ConfigDialog has been deleted
```

## Versions

* Spyder version: 5.2.2 
* Python version: 3.9.5
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.0.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0               :  7.28.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.17.2 (OK)
jellyfish >=0.7                      :  0.8.9 (OK)
jsonschema >=3.2.0                   :  4.0.1 (OK)
keyring >=17.0.0                     :  23.2.1 (OK)
nbconvert >=4.0                      :  6.2.0 (OK)
numpydoc >=0.6.0                     :  1.1.0 (OK)
paramiko >=2.4.0                     :  2.7.2 (OK)
parso >=0.7.0;<0.9.0                 :  0.7.1 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.8.0 (OK)
pygments >=2.0                       :  2.10.0 (OK)
pylint >=2.5.0                       :  2.9.6 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0                 :  1.3.2 (OK)
pylsp_black >=1.0.0                  :  1.0.0 (OK)
qdarkstyle =3.0.2                    :  3.0.2 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.0.3 (OK)
qtconsole >=5.2.1;<5.3.0             :  5.2.1 (OK)
qtpy >=1.5.0                         :  1.11.2 (OK)
rtree >=0.9.7                        :  0.9.7 (OK)
setuptools >=49.6.0                  :  58.2.0 (OK)
sphinx >=0.6.6                       :  4.2.0 (OK)
spyder_kernels >=2.2.1;<2.3.0        :  2.2.1 (OK)
textdistance >=4.2.0                 :  4.2.1 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.6 (OK)
zmq >=17                             :  22.3.0 (OK)

# Optional:
cython >=0.21                        :  0.29.24 (OK)
matplotlib >=2.0.0                   :  3.4.3 (OK)
numpy >=1.7                          :  1.20.0 (OK)
pandas >=1.1.1                       :  1.3.3 (OK)
scipy >=0.17.0                       :  1.7.1 (OK)
sympy >=0.7.3                        :  None (NOK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.1.0 :  1.1.0 (OK)
```

**Comment by ccordoba12** [comment]
Hey @abbassi95, thanks for reporting. Please update spyder-terminal to version 1.2.0 to see if that fixes your problem.

That should do the trick because spyder-terminal 1.1.0 (the version that you have currently installed) is not compatible with Spyder 5.2.

**Comment by abbassi95** [comment]
Thanks @ccordoba12 for the quick reply! That have solved the problem
