### ISSUE TITLE
SpyderShell' object has no attribute '_pdb_obj

### ISSUE THREAD

**Issue by jillhanssen** [spyder-ide/spyder#17285]
### What steps will reproduce the problem?

[SpyderKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\PROGRAMS\Anaconda3\lib\site-packages\spyder_kernels\comms\frontendcomm.py", line 156, in poll_one
    import asyncio
NameError: name 'ipykernel' is not defined

### Traceback
```python-traceback
Exception in comms call get_var_properties:
  File "C:\PROGRAMS\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    return_value = self._remote_callback(
  File "C:\PROGRAMS\Anaconda3\lib\site-packages\spyder_kernels\comms\frontendcomm.py", line 267, in _remote_callback
    return super(FrontendComm, self)._remote_callback(
  File "C:\PROGRAMS\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 356, in _remote_callback
    return self._remote_call_handlers[call_name](
  File "C:\PROGRAMS\Anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 201, in get_var_properties
    ns = self._get_current_namespace()
  File "C:\PROGRAMS\Anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 588, in _get_current_namespace
    ns.update(self.shell.user_ns)
  File "C:\PROGRAMS\Anaconda3\lib\site-packages\spyder_kernels\console\shell.py", line 98, in user_ns
    if self._pdb_frame is not None:
  File "C:\PROGRAMS\Anaconda3\lib\site-packages\spyder_kernels\console\shell.py", line 81, in _pdb_frame
    if self.pdb_session is not None:
  File "C:\PROGRAMS\Anaconda3\lib\site-packages\spyder_kernels\console\shell.py", line 71, in pdb_session
    return self._pdb_obj
AttributeError: 'SpyderShell' object has no attribute '_pdb_obj'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.8.12
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (NOK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.11.2 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.25 (OK)
matplotlib >=2.0.0            :  3.5.0 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment]
Hey @jillhanssen, thanks for reporting. Please close Spyder, open the Anaconda Prompt and run there

    conda install jupyter_client=6.1.12 ipykernel=5

That should fix your problem.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
