### ISSUE TITLE
Spyder_Issue_Class06

### ISSUE THREAD

**Issue by acunning** [spyder-ide/spyder#17309]
### What steps will reproduce the problem?

folding_panel.update_folding(self._folding_info)
AttributeError: 'CodeEditor' object has no attribute '_folding_info'
Traceback (most recent call last):
  File "/Users/annabellecunningham/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1915, in finish_code_folding
    folding_panel.update_folding(self._folding_info)
AttributeError: 'CodeEditor' object has no attribute '_folding_info'

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/Users/annabellecunningham/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1915, in finish_code_folding
    folding_panel.update_folding(self._folding_info)
AttributeError: 'CodeEditor' object has no attribute '_folding_info'
Traceback (most recent call last):
  File "/Users/annabellecunningham/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1915, in finish_code_folding
    folding_panel.update_folding(self._folding_info)
AttributeError: 'CodeEditor' object has no attribute '_folding_info'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.7
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Darwin 20.3.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  None (NOK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment]
Hey @acunning, thanks for reporting. I think this error is fixed in our latest version (5.2.2).

Since it's still not available in Anaconda, please use our Mac installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).

After that, you can connect Spyder to your current Anaconda installation by following these instructions:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

Please do that and let us know if it works for you.
