### ISSUE TITLE
an error occured while starting the kernel

### ISSUE THREAD

**Issue by pmpj22** [spyder-ide/spyder#17305]
kernel shows message 'An error ocurred while starting the kernel'

with the following:
Traceback (most recent call last):
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/spyder_kernels/console/__main__.py", line 24, in 
start.main()
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/spyder_kernels/console/start.py", line 320, in main
kernel.initialize()
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/traitlets/config/application.py", line 88, in inner
return method(app, *args, **kwargs)
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/ipykernel/kernelapp.py", line 635, in initialize
self.write_connection_file()
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/ipykernel/kernelapp.py", line 241, in write_connection_file
write_connection_file(cf, ip=self.ip, key=self.session.key, transport=self.transport,
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/jupyter_client/connect.py", line 164, in write_connection_file
with secure_write(fname) as f:
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/contextlib.py", line 119, in __enter__
return next(self.gen)
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/jupyter_core/paths.py", line 901, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o0600), mode) as f:
IsADirectoryError: [Errno 21] Is a directory: '/Users/polly'
Traceback (most recent call last):
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/spyder_kernels/console/__main__.py", line 24, in 
start.main()
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/spyder_kernels/console/start.py", line 320, in main
kernel.initialize()
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/traitlets/config/application.py", line 88, in inner
return method(app, *args, **kwargs)
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/ipykernel/kernelapp.py", line 635, in initialize
self.write_connection_file()
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/ipykernel/kernelapp.py", line 241, in write_connection_file
write_connection_file(cf, ip=self.ip, key=self.session.key, transport=self.transport,
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/jupyter_client/connect.py", line 164, in write_connection_file
with secure_write(fname) as f:
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/contextlib.py", line 119, in __enter__
return next(self.gen)
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/jupyter_core/paths.py", line 901, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o0600), mode) as f:
IsADirectoryError: [Errno 21] Is a directory: '/Users/polly'
start.main()
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/spyder_kernels/console/start.py", line 320, in main
kernel.initialize()
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/traitlets/config/application.py", line 88, in inner
return method(app, *args, **kwargs)
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/ipykernel/kernelapp.py", line 635, in initialize
self.write_connection_file()
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/ipykernel/kernelapp.py", line 241, in write_connection_file
write_connection_file(cf, ip=self.ip, key=self.session.key, transport=self.transport,
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/jupyter_client/connect.py", line 164, in write_connection_file
with secure_write(fname) as f:
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/contextlib.py", line 119, in __enter__
return next(self.gen)
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/jupyter_core/paths.py", line 901, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o0600), mode) as f:
IsADirectoryError: [Errno 21] Is a directory: '/Users/polly'
Traceback (most recent call last):
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/spyder_kernels/console/__main__.py", line 24, in 
start.main()
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/spyder_kernels/console/start.py", line 320, in main
kernel.initialize()
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/traitlets/config/application.py", line 88, in inner
return method(app, *args, **kwargs)
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/ipykernel/kernelapp.py", line 635, in initialize
self.write_connection_file()
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/ipykernel/kernelapp.py", line 241, in write_connection_file
write_connection_file(cf, ip=self.ip, key=self.session.key, transport=self.transport,
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/jupyter_client/connect.py", line 164, in write_connection_file
with secure_write(fname) as f:
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/contextlib.py", line 119, in __enter__
return next(self.gen)
File "/opt/anaconda3/envs/spyder‑env/lib/python3.9/site‑packages/jupyter_core/paths.py", line 901, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o0600), mode) as f:
IsADirectoryError: [Errno 21] Is a directory: '/Users/polly'

**Comment by ccordoba12** [comment]
Hey @pmpj22, thanks for reporting. Please open Terminal, run `ipython` there and introduce the following commands:

```python
In [1]: from ipykernel.kernelapp import IPKernelApp
    
In [2]: app = IPKernelApp()

In [3]: app.connection_dir

In [4]: app.init_connection_file()

In [5]: app.connection_file
```

Then post a screenshot here of the results you get.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
