### ISSUE TITLE
dispatch_queue     await self.process_one()

### ISSUE THREAD

**Issue by raven44099** [spyder-ide/spyder#17316]
### Issue Report Checklist

* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)

## Problem Description
Whatever code that makes an error message also gives another error message, as follows:
<details><summary>Error</summary>
<p>

```
[SpyderKernelApp] ERROR | Error in message handler
Traceback (most recent call last):
  File "/home/ubuntuds64/miniconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 461, in dispatch_queue
    await self.process_one()
  File "/home/ubuntuds64/miniconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 450, in process_one
    await dispatch(*args)
TypeError: object NoneType can't be used in 'await' expression
```

</p>
</details>

### What steps reproduce the problem?

1.  `SyntaxError: invalid syntax`
2. `SyntaxError: unexpected EOF while parsing`
3. `unmatched ')'`

### What is the expected output? What do you see instead?
I expect only the "syntaxError" and nothing else. This additional lines make programing unclear.

### Paste Traceback/Error Below (if applicable)

```python-traceback

  File "/home/ubuntuds64/miniconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 461, in dispatch_queue
    await self.process_one()
  File "/home/ubuntuds64/miniconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 450, in process_one
    await dispatch(*args)
TypeError: object NoneType can't be used in 'await' expression

```

## Versions

* Spyder version: 5.2.2
* Python version: 3.8.5 64-bit
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: Linux 5.13.0-28-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.1 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.1.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.8.1 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.0 (OK)
scipy >=0.17.0                :  1.8.0 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @raven44099, thanks for reporting. This is a problem with the latest version of IPykernel, not with Spyder. I reported the problem with its maintainers so they can fix it:  ipython/ipykernel#860.

In the meantime, please downgrade to IPykernel 6.8.0 to avoid it with a command like this in a system terminal:

    conda install -c conda-forge ipykernel=6.8.0

**Comment by raven44099** [comment]
Perfect fix, perfect support, thank you!
-
And sorry for addressing it to you.
Have a nice time!

**Comment by ccordoba12** [comment]
No worries and thanks to you too for reporting this problem! Users like you are the ones who help to make Spyder better.

**Comment by FObersteiner** [comment]
upgrading `ipykernel` to 6.9.1 also worked for me.

[related question on stackoverflow](https://stackoverflow.com/q/71116130/10197418)
