### ISSUE TITLE
TypeError: super(type, obj): obj must be an instance or subtype of type

### ISSUE THREAD

**Issue by GuywithSpectacles** [spyder-ide/spyder#17345]
### What steps will reproduce the problem?

Code:

import pdb

def sum_values(a, b):
    return a + b

def test_function():
    pdb.set_trace()  #we have added a breakpoint here. The code pause execution here.
    print('This is the first line')
    print("This is the second line.")
    value  = sum_values(2, 3)
    print('The code is done!')
    return value 

print(test_function())

runfile('D:/Al-Nafi-Tracks/Python/Beta/Code/Debugging/debugging.py', wdir='D:/Al-Nafi-Tracks/Python/Beta/Code/Debugging')
Traceback (most recent call last):

  File "D:\Al-Nafi-Tracks\Python\Beta\Code\Debugging\debugging.py", line 21, in <module>
    print(test_function())

  File "D:\Al-Nafi-Tracks\Python\Beta\Code\Debugging\debugging.py", line 13, in test_function
    pdb.set_trace()  #we have added a breakpoint here. The code pause execution here.

  File "D:\anaconda\lib\site-packages\pdb.py", line 1201, in set_trace
    pdb = Pdb(start_lineno=lineno, start_filename=filename, **kwds)

  File "D:\anaconda\lib\site-packages\pdb.py", line 169, in __init__
    super(Pdb, self).__init__(*args, **kwargs)

TypeError: super(type, obj): obj must be an instance or subtype of type

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by luzgui** [comment]
I am having the same issue.
Is there any solution?
