### ISSUE TITLE
cannot access preferences

### ISSUE THREAD

**Issue by Egranger94** [spyder-ide/spyder#17349]
### What steps will reproduce the problem?

Clicking on preferences button will reproduce this issue.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\Jana\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\preferences\plugin.py", line 276, in <lambda>
    lambda: self.open_dialog(main.prefs_dialog_size))
  File "C:\Users\Jana\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\preferences\plugin.py", line 258, in open_dialog
    self.get_main())
  File "C:\Users\Jana\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\preferences\widgets\container.py", line 62, in create_dialog
    page.initialize()
  File "C:\Users\Jana\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\preferences\api.py", line 80, in initialize
    self.setup_page()
  File "C:\Users\Jana\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\appearance\confpage.py", line 157, in setup_page
    self.update_combobox()
  File "C:\Users\Jana\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\appearance\confpage.py", line 227, in update_combobox
    self.scheme_choices_dict[self.get_option('{0}/name'.format(n))] = n
  File "C:\Users\Jana\AppData\Local\Programs\Spyder\pkgs\spyder\api\plugins\new_api.py", line 484, in get_conf
    return self._conf.get(section, option, default)
  File "C:\Users\Jana\AppData\Local\Programs\Spyder\pkgs\spyder\config\manager.py", line 461, in get
    value = config.get(section=section, option=option, default=default)
  File "C:\Users\Jana\AppData\Local\Programs\Spyder\pkgs\spyder\config\user.py", line 980, in get
    return config.get(section=section, option=option, default=default)
  File "C:\Users\Jana\AppData\Local\Programs\Spyder\pkgs\spyder\config\user.py", line 517, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'custom-0/name' in section: 'appearance'
```

## Versions

* Spyder version: 5.2.2 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.5.0 (OK)
nbconvert >=4.0               :  6.4.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.9.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.1 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.5.0 (OK)
sphinx >=0.6.6                :  4.3.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.26 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by dan123456-eng** [comment]
@Egranger94  
Clicking the preferences button will play a different problem here (Spyder=5.2.2).
```
C 10:16:07 Unhandled exception:
Traceback (most recent call last):
  File "C:\Users\dan-s\miniconda3\envs\ciermag-develop\lib\site-packages\spyder\plugins\preferences\plugin.py", line 276, in <lambda>
    lambda: self.open_dialog(main.prefs_dialog_size))
  File "C:\Users\dan-s\miniconda3\envs\ciermag-develop\lib\site-packages\spyder\plugins\preferences\plugin.py", line 256, in open_dialog
    container.create_dialog(
  File "C:\Users\dan-s\miniconda3\envs\ciermag-develop\lib\site-packages\spyder\plugins\preferences\widgets\container.py", line 62, in create_dialog
    page.initialize()
  File "C:\Users\dan-s\miniconda3\envs\ciermag-develop\lib\site-packages\spyder\plugins\preferences\api.py", line 80, in initialize
    self.setup_page()
  File "C:\Users\dan-s\miniconda3\envs\ciermag-develop\lib\site-packages\spyder\api\plugin_registration\_confpage.py", line 71, in setup_page
    plugin_loc_name = PluginClass.get_name()
TypeError: get_name() missing 1 required positional argument: 'self'
´´´

**Comment by ccordoba12** [comment]
Hey @Egranger94, thanks for reporting. Did you create a custom syntax highlighting theme before this happened?

**Comment by ccordoba12** [comment]
@dan123456-eng, yours is a different problem and it's generated because the `get_name` method of our plugins needs to be a static method after Spyder 5.2.0, like this:

https://github.com/spyder-ide/spyder/blob/17ad955706f54cc0c092814f590af0fe45b327f2/spyder/plugins/explorer/plugin.py#L158-L161

If you're using an old version of Spyder-terminal, please update it to its latest version to fix this problem. Or if you have your own third-party plugins, please make `get_name` and static method in them.

**Comment by dan123456-eng** [comment]
```
@staticmethod 
 def get_name():
       """Return widget title"""
       return _("PyMR")
```

**Comment by ccordoba12** [comment]
Closing due to lack of response.
