### ISSUE TITLE
Turning off Project plugin stops LSP server from starting

### ISSUE THREAD

**Issue by Niceadam** [spyder-ide/spyder#17360]
### What steps will reproduce the problem?

Turn off the Project plugin and restart spyder. The LSP server just says it is starting and never actually starts.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/niceadam/miniconda3/envs/spyder-env/lib/python3.9/site-packages/spyder/plugins/completion/providers/languageserver/widgets/status.py", line 70, in show_menu
    language = self.current_language.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/home/niceadam/miniconda3/envs/spyder-env/lib/python3.9/site-packages/spyder/plugins/completion/providers/languageserver/widgets/status.py", line 70, in show_menu
    language = self.current_language.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

## Versions

* Spyder version: 5.2.2 
* Python version: 3.9.10
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Linux 5.16.8-1-default

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  22.3.0 (OK)
nbconvert >=4.0               :  6.4.2 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.1.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.9.2 (OK)
sphinx >=0.6.6                :  4.3.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by dalthviz** [comment]
Hi @Niceadam thank you for the feedback! I was able to reproduce this! Will work on it for a future release 👍🏼
