### ISSUE TITLE
Show help bring up an internal problem.

### ISSUE THREAD

**Issue by Ali-Flt** [spyder-ide/spyder#17388]
### What steps will reproduce the problem?

i typed isin and wanted to complete it to isinstance and the tip show didn't work

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 3026, in show_hint_for_completion
    self.show_hint(
  File "/usr/lib/python3.10/site-packages/spyder/widgets/mixins.py", line 641, in show_hint
    self.show_tooltip(signature=html_signature, text=extra_text,
  File "/usr/lib/python3.10/site-packages/spyder/widgets/mixins.py", line 620, in show_tooltip
    self.tooltip_widget.show_tip(point, tiptext, cursor=cursor,
  File "/usr/lib/python3.10/site-packages/spyder/widgets/calltip.py", line 192, in show_tip
    point.setY(adjusted_point.y() - tip_height - padding)
TypeError: setY(self, int): argument 1 has unexpected type 'float'
```

## Versions

* Spyder version: 5.2.0 
* Python version: 3.10.2
* Qt version: 5.15.2
* PyQt5 version: 5.15.6
* Operating System: Linux 5.16.10-arch1-1

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.0.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.2 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.1;<1.4.0          :  1.3.2 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle >=3.0.2            :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  1.11.2 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  59.3.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.2.0;<2.3.0 :  2.2.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  0.10.7 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.22.2 (OK)
pandas >=1.1.1                :  None (OK)
scipy >=0.17.0                :  None (OK)
sympy >=0.7.3                 :  None (OK)
```

**Comment by ccordoba12** [comment]
Hey @Ali-Flt, thanks for reporting. This error will be fixed in our next version (5.3.0), to be released next month. In the meantime, please use Spyder with Python 3.9.

Also, it'd be better if you stop using the Arch Linux Spyder package altogether because it's always semi-broken, i.e. some parts work fine on it and others are totally broken.

**Comment by Ali-Flt** [comment]
Thanks @ccordoba12 for the reply.
So what approach do you suggest for using spyder on arch? should I use the spyder-git package on aur?

**Comment by ccordoba12** [comment]
No, that package is broken as well. Please use `pyenv` to create a Python 3.9 environment, then use `pip` to install Spyder, like this

    pip install spyder

I think the Arch maintainers are aware that they are distributing a broken Spyder package, but (I don't know why) they do it anyway, which is really awful.

**Comment by ccordoba12** [comment]
Your other option is to install Miniconda, then install Spyder with conda like this:

    conda create -n spyder-cf -c conda-forge spyder
    conda activate spyder-cf
    spyder

**Comment by Ali-Flt** [comment]
@ccordoba12 thanks,
Yes I also found it very strange that spyder arch packages are so broken. 
I finnaly decided to install anaconda but miniconda would've been a better solution cause anaconda takes so much space

**Comment by ccordoba12** [comment]
I know, that's why I suggested Miniconda to you in the first place.
