### ISSUE TITLE
Spyder hangs when trying to run script second time

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1738]
_From [StephenM...@gmail.com](https://code.google.com/u/114899541919144260151/) on 2014-02-22T18:19:25Z_

Spyder Version:  2.3.0beta2
Python Version:  3.3.3
Qt Version    :  4.8.4, PyQt4 (API v2) 4.9.6 on Windows
pyflakes >=0.6.0:  None (OK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  1.1.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2.1 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.4.1 (OK)
pylint >=0.25   :  1.0.0 (OK) 

What steps will reproduce the problem?

 1. Trying to run script second time. 2. 3. What is the expected output? What do you see instead? >>> Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 260, in 'calling callback function'
  File "C:\Users\Dad\Documents\WinPython-64bit-3.3.3.3\python-3.3.3.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 275, in qt_inputhook
    monitor.refresh_from_inputhook()
  File "C:\Users\Dad\Documents\WinPython-64bit-3.3.3.3\python-3.3.3.amd64\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 309, in refresh_from_inputhook
    self.refresh()
  File "C:\Users\Dad\Documents\WinPython-64bit-3.3.3.3\python-3.3.3.amd64\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 299, in refresh
    communicate(self.n_request, dict(command="refresh"))
  File "C:\Users\Dad\Documents\WinPython-64bit-3.3.3.3\python-3.3.3.amd64\lib\site-packages\spyderlib\utils\bsdsocket.py", line 99, in communicate
    write_packet(sock, command)
  File "C:\Users\Dad\Documents\WinPython-64bit-3.3.3.3\python-3.3.3.amd64\lib\site-packages\spyderlib\utils\bsdsocket.py", line 47, in write_packet
    nsend -= temp_fail_retry(socket.error, sock.send, sent_data)
  File "C:\Users\Dad\Documents\WinPython-64bit-3.3.3.3\python-3.3.3.amd64\lib\site-packages\spyderlib\utils\bsdsocket.py", line 27, in temp_fail_retry
    return fun(*args)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host 

Please provide any additional information below

. Trying to run simple script ....
print ("5 * 10 is ", 5*10)
runs the first time
but second time hangs and then spits out errors captured above.

I am running Windows 7 64-bit machine

Thanks for any help

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1738_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-02-24T04:40:40Z_

This could be caused by your firewall, i.e. by having some too strict rules that block communication between Spyder and the external process where the Python/IPython interpreter runs.

This is my best guess :)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-15T09:31:47Z_

Closing because of lack of feedback. Hope now it's working well for you :-)

**Status:** WontFix
