### ISSUE TITLE
Saving to Dropbox

### ISSUE THREAD

**Issue by luke-ad-murphy** [spyder-ide/spyder#17412]
### What steps will reproduce the problem?

Our orgainsation's dropbox has just increased security to a two-step verification.
Since this change, I cannot save a plot (as png) using either code or by right clicking on the image and choosing the Dropbox path.

The error states "FileNotFoundError: [Errno 2] No such file or directory: ", but this script worked perfectly before Dropbox verification change.

I've had a quick look in the troubleshooting and know bugs links, but can't find a solution, am hoping someone can help.

Thanks,
Luke

NB, not sure you need the code, but here:
dir_name = "C:/Users/LukeMurphy/Dense Air Dropbox/Dense Air's shared workspace/DA Group Sharespace/BigData/Data Science/Altitude analysis/Altitiude research/Tutela data analysis/Westfield Shopping Centre/"
visuals = "C:/Users/LukeMurphy/Dense Air Dropbox/Dense Air's shared workspace/DA Group Sharespace/BigData/Data Science/Altitude analysis/Altitiude research/Tutela data analysis/Westfield Shopping Centre/Validation modelling/"
MNO = 'Vodafone'
Layer = 'More than 72m'
plt.savefig(visuals + MNO + ' RSRP propagation ' + Layer + ' layer.png')

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\LukeMurphy\Envs\geopandas\lib\site-packages\spyder\plugins\plots\widgets\main_widget.py", line 525, in save_plot
    widget.thumbnails_sb.save_current_figure_as()
  File "C:\Users\LukeMurphy\Envs\geopandas\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 669, in save_current_figure_as
    self.save_figure_as(self.current_thumbnail.canvas.fig,
  File "C:\Users\LukeMurphy\Envs\geopandas\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 697, in save_figure_as
    save_figure_tofile(fig, fmt, fname)
  File "C:\Users\LukeMurphy\Envs\geopandas\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 52, in save_figure_tofile
    with open(fname, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: "C:/Users/LukeMurphy/Dense Air Dropbox/Dense Air's shared workspace/DA Group Sharespace/BigData/Data Science/Altitude analysis/Altitiude research/Tutela data analysis/Westfield Shopping Centre/Validation modelling/Vodafone RSRP propagation More than 72m layer.png"
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.10
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  4.2.1 (OK)
keyring >=17.0.0              :  23.2.1 (OK)
nbconvert >=4.0               :  6.2.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.8.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.0 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.11.2 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.3.0 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.21.4 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment]
Hey @luke-ad-murphy, thanks for reporting. It seems the code we use to save plots to disk is unable to see your Dropbox directory in your system, probably due to the two-factor authentication process you mentioned.

To check that, are you able to `cd` into that directory and then save files using Terminal?
