### ISSUE TITLE
gl_context_cgl.cc(136)

### ISSUE THREAD

**Issue by jonzhaopeng** [spyder-ide/spyder#17447]
### What steps will reproduce the problem?

[3114:68371:0307/000623.015347:ERROR:gl_context_cgl.cc(136)] Error creating context.
[3114:68371:0307/000623.022221:ERROR:gl_context_cgl.cc(136)] Error creating context.
[3114:68371:0307/000623.022683:ERROR:gl_context_cgl.cc(136)] Error creating context.
[3114:68371:0307/000623.023749:ERROR:gl_context_cgl.cc(136)] Error creating context.
[3114:68371:0307/000623.167416:ERROR:gl_context_cgl.cc(136)] Error creating context.
[3114:68371:0307/000623.168144:ERROR:gl_context_cgl.cc(136)] Error creating context.
[3114:68371:0307/000623.168689:ERROR:gl_context_cgl.cc(136)] Error creating context.
[3114:68371:0307/000623.169228:ERROR:gl_context_cgl.cc(136)] Error creating context.
[3114:68371:0307/000625.692538:ERROR:gl_context_cgl.cc(136)] Error creating context.
[3114:68371:0307/000625.693377:ERROR:gl_context_cgl.cc(136)] Error creating context.
[3114:68371:0307/000625.694357:ERROR:gl_context_cgl.cc(136)] Error creating context.
[3114:68371:0307/000625.695087:ERROR:gl_context_cgl.cc(136)] Error creating context.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/Users/genghis/miniconda3/envs/pythonic/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 2, in <module>
NameError: name 'gl_context_cgl' is not defined
```

## Versions

* Spyder version: 5.2.2 
* Python version: 3.9.7
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Darwin 21.3.0

### Dependencies

```
# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0;<8.0.0        :  7.32.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.2 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.1.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.9.3 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.22.2 (OK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @jonzhaopeng, thanks for reporting. Please describe the steps that we need to follow to reproduce this error.

Otherwise, we won't be able to help you.

**Comment by jonzhaopeng** [comment]
Hey @ccordoba12 , Thank you for your help。

after run " spyder -p . & " in my project dir

**Comment by ccordoba12** [comment]
According to these links:

https://bugreports.qt.io/browse/QTBUG-73799
https://github.com/qutebrowser/qutebrowser/issues/2671

this seems to be an issue with your graphics card.

Please close Spyder, open Terminal and run there:

    spyder --reset

so your settings are restored to factory defaults, which use software acceleration instead of hardware one.

If that doesn't fix the problem, I'm afraid you'll have to live with it because there's nothing we can do about it.

Well, you could also try to upgrade your graphics card drivers (if that's even possible in Mac).
