### ISSUE TITLE
Errors when running empty cells

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1746]
_From [sylvain....@gmail.com](https://code.google.com/u/102212202545902308399/) on 2014-03-01T20:46:53Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. On the current development version, put one or two cell delimiters in an empty python file. 

    \# &#37;&#37;
    
    
    \# &#37;&#37;   
    
2. Place your cursor in either one of the two cells
3. Hit Ctrl+Enter to run the cell What is the expected output? What do you see instead? Nothing should happen as the cells are empty. Instead, the focus goes to the internal console with errors:

Traceback (most recent call last):
  File "/home/sylvain/spyderlib_remote/spyderlib/widgets/editor.py", line 1995, in run_cell
    text = self.get_current_editor().get_cell_as_executable_code()
  File "/home/sylvain/spyderlib_remote/spyderlib/widgets/sourcecode/base.py", line 502, in get_cell_as_executable_code
    text = self.get_selection_as_executable_code()
  File "/home/sylvain/spyderlib_remote/spyderlib/widgets/sourcecode/base.py", line 466, in get_selection_as_executable_code
    first_line = lines[0].lstrip()
IndexError: list index out of range

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1746_

**Comment by spyder-issues-migrator** [comment]
_From [sylvain....@gmail.com](https://code.google.com/u/102212202545902308399/) on 2014-03-01T18:39:19Z_

PR: https://bitbucket.org/spyder-ide/spyderlib/pull-request/24/solve-issue-1746/diff

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-04-15T13:42:34Z_

This was solved in https://bitbucket.org/spyder-ide/spyderlib/pull-request/25

**Status:** Verified
