### ISSUE TITLE

I can not see anything under Panes menu

### ISSUE THREAD

**Issue by eslamerman** [spyder-ide/spyder#17482]
### What steps will reproduce the problem?

I am trying to use the Terminal as per this link https://docs.spyder-ide.org/4/plugins/terminal.html

as mentioned in the link above :
When the Terminal is installed, it will be available under the menu item View ‣ Panes ‣ Terminal

I can not see anything under Panes. 

I did restart to my machine and IDE, but no avail. 

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\eerman\Anaconda3\envs\pythonenv\lib\site-packages\spyder\plugins\layout\container.py", line 113, in <lambda>
    self._plugin.toggle_lock(),
  File "C:\Users\eerman\Anaconda3\envs\pythonenv\lib\site-packages\spyder\plugins\layout\plugin.py", line 786, in toggle_lock
    if plugin.dockwidget.isFloating():
AttributeError: 'NoneType' object has no attribute 'isFloating'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.2.2 (OK)
qtpy >=1.5.0                  :  1.11.2 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.25 (OK)
matplotlib >=2.0.0            :  3.5.0 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.4.1 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by nikfilippas** [comment]
I have had the same issue. The channel `spyder-ide` contains an outdated version of the terminal. Remove the currently installed terminal and re-install it from `conda-forge` and it will work as intended.

**Comment by eslamerman** [comment]
@nikfilippas  

Thanks. I did remove for spyder, updated Anaconda, and reinstalled Spyder again using conda install -c conda-forge spyder. Works fine.
