### ISSUE TITLE
i keep recieving the same problem

### ISSUE THREAD

**Issue by Jameson33699** [spyder-ide/spyder#17496]
### What steps will reproduce the problem?

please note i am using linux Ubuntu as my native OS
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/__main__.py", line 24, in 
start.main()
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/start.py", line 295, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.8/dist‑packages/ipykernel/kernelapp.py", line 33, in 
from traitlets.utils import filefind
ImportError: cannot import name 'filefind' from 'traitlets.utils' (/usr/lib/python3/dist‑packages/traitlets/utils/__init__.py)
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/__main__.py", line 24, in 
start.main()
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/start.py", line 295, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.8/dist‑packages/ipykernel/kernelapp.py", line 33, in 
from traitlets.utils import filefind
ImportError: cannot import name 'filefind' from 'traitlets.utils' (/usr/lib/python3/dist‑packages/traitlets/utils/__init__.py)
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/__main__.py", line 24, in 
start.main()
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/start.py", line 295, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.8/dist‑packages/ipykernel/kernelapp.py", line 33, in 
from traitlets.utils import filefind
ImportError: cannot import name 'filefind' from 'traitlets.utils' (/usr/lib/python3/dist‑packages/traitlets/utils/__init__.py)
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/__main__.py", line 24, in 
start.main()
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/start.py", line 295, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.8/dist‑packages/ipykernel/kernelapp.py", line 33, in 
from traitlets.utils import filefind
ImportError: cannot import name 'filefind' from 'traitlets.utils' (/usr/lib/python3/dist‑packages/traitlets/utils/__init__.py)
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/__main__.py", line 24, in 
start.main()
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/start.py", line 295, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.8/dist‑packages/ipykernel/kernelapp.py", line 33, in 
from traitlets.utils import filefind
ImportError: cannot import name 'filefind' from 'traitlets.utils' (/usr/lib/python3/dist‑packages/traitlets/utils/__init__.py)
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/__main__.py", line 24, in 
start.main()
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/start.py", line 295, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.8/dist‑packages/ipykernel/kernelapp.py", line 33, in 
from traitlets.utils import filefind
ImportError: cannot import name 'filefind' from 'traitlets.utils' (/usr/lib/python3/dist‑packages/traitlets/utils/__init__.py)
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/__main__.py", line 24, in 
start.main()
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/start.py", line 295, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.8/dist‑packages/ipykernel/kernelapp.py", line 33, in 
from traitlets.utils import filefind
ImportError: cannot import name 'filefind' from 'traitlets.utils' (/usr/lib/python3/dist‑packages/traitlets/utils/__init__.py)
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/__main__.py", line 24, in 
start.main()
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/start.py", line 295, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.8/dist‑packages/ipykernel/kernelapp.py", line 33, in 
from traitlets.utils import filefind
ImportError: cannot import name 'filefind' from 'traitlets.utils' (/usr/lib/python3/dist‑packages/traitlets/utils/__init__.py)
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/__main__.py", line 24, in 
start.main()
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/start.py", line 295, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.8/dist‑packages/ipykernel/kernelapp.py", line 33, in 
from traitlets.utils import filefind
ImportError: cannot import name 'filefind' from 'traitlets.utils' (/usr/lib/python3/dist‑packages/traitlets/utils/__init__.py)
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/__main__.py", line 24, in 
start.main()
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/start.py", line 295, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.8/dist‑packages/ipykernel/kernelapp.py", line 33, in 
from traitlets.utils import filefind
ImportError: cannot import name 'filefind' from 'traitlets.utils' (/usr/lib/python3/dist‑packages/traitlets/utils/__init__.py)
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/__main__.py", line 24, in 
start.main()
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/start.py", line 295, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.8/dist‑packages/ipykernel/kernelapp.py", line 33, in 
from traitlets.utils import filefind
ImportError: cannot import name 'filefind' from 'traitlets.utils' (/usr/lib/python3/dist‑packages/traitlets/utils/__init__.py)
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/__main__.py", line 24, in 
start.main()
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/start.py", line 295, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.8/dist‑packages/ipykernel/kernelapp.py", line 33, in 
from traitlets.utils import filefind
ImportError: cannot import name 'filefind' from 'traitlets.utils' (/usr/lib/python3/dist‑packages/traitlets/utils/__init__.py)

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/qtconsole/manager.py", line 27, in poll
    super().poll()
  File "/usr/local/lib/python3.8/dist-packages/jupyter_client/restarter.py", line 143, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "/usr/local/lib/python3.8/dist-packages/jupyter_client/utils.py", line 26, in wrapped
    raise e
  File "/usr/local/lib/python3.8/dist-packages/jupyter_client/utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "/usr/local/lib/python3.8/dist-packages/nest_asyncio.py", line 81, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.8/dist-packages/jupyter_client/manager.py", line 530, in _async_restart_kernel
    await ensure_async(self.start_kernel(**self._launch_args))
  File "/usr/local/lib/python3.8/dist-packages/jupyter_client/utils.py", line 26, in wrapped
    raise e
  File "/usr/local/lib/python3.8/dist-packages/jupyter_client/utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "/usr/local/lib/python3.8/dist-packages/nest_asyncio.py", line 81, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.8/dist-packages/jupyter_client/manager.py", line 79, in wrapper
    raise e
  File "/usr/local/lib/python3.8/dist-packages/jupyter_client/manager.py", line 71, in wrapper
    out = await method(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jupyter_client/manager.py", line 380, in _async_start_kernel
    await ensure_async(self._launch_kernel(kernel_cmd, **kw))
  File "/usr/local/lib/python3.8/dist-packages/jupyter_client/utils.py", line 26, in wrapped
    raise e
  File "/usr/local/lib/python3.8/dist-packages/jupyter_client/utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "/usr/local/lib/python3.8/dist-packages/nest_asyncio.py", line 81, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.8/dist-packages/jupyter_client/manager.py", line 300, in _async_launch_kernel
    connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
  File "/usr/local/lib/python3.8/dist-packages/jupyter_client/provisioning/local_provisioner.py", line 179, in launch_kernel
    self.process = launch_kernel(cmd, **scrubbed_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jupyter_client/launcher.py", line 169, in launch_kernel
    raise ex
  File "/usr/local/lib/python3.8/dist-packages/jupyter_client/launcher.py", line 157, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 808, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/usr/lib/python3.8/subprocess.py", line 1489, in _get_handles
    c2pwrite = stdout.fileno()
ValueError: I/O operation on closed file
```

## Versions

* Spyder version: 5.2.2 
* Python version: 3.8.10
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 5.13.0-35-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  1.3.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.13.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  18.0.1 (OK)
nbconvert >=4.0               :  5.6.1 (OK)
numpydoc >=0.6.0              :  0.7.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.6.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.5.1 (OK)
pygments >=2.0                :  2.3.1 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.1.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.9.3 (OK)
sphinx >=0.6.6                :  1.8.5 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.26 (OK)
zmq >=17                      :  18.1.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by dalthviz** [comment]
Hi @Jameson33699 thank you for the feedback! Could you describe the way this traceback appeared to you? Did you change some config regarding the Graphics backend preferences for the IPython console ? Also, what version of `ipykernel` do you have installed?

Any new info in order to be able to reproduce this is greatly appreciated. Let us know!

**Comment by Jameson33699** [comment]
hi @dalthviz i had just installed ipykernel version 6.9.2 and the problem has been resolved, thank you

**Comment by dalthviz** [comment]
Awesome, glad is working for you now @Jameson33699 and thank you for letting us know! :+1:
