### ISSUE TITLE
Spyder has encountered a problem

### ISSUE THREAD

**Issue by xiaopengguo** [spyder-ide/spyder#17505]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\xiaopengguo\anaconda31\envs\pyg123\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):
  File "C:\Users\xiaopengguo\anaconda31\envs\pyg123\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "C:\Users\xiaopengguo\anaconda31\envs\pyg123\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "C:\Users\xiaopengguo\anaconda31\envs\pyg123\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):
  File "C:\Users\xiaopengguo\anaconda31\envs\pyg123\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):
  File "C:\Users\xiaopengguo\anaconda31\envs\pyg123\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):
  File "C:\Users\xiaopengguo\anaconda31\envs\pyg123\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):
  File "C:\Users\xiaopengguo\anaconda31\envs\pyg123\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "C:\Users\xiaopengguo\anaconda31\envs\pyg123\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):
  File "C:\Users\xiaopengguo\anaconda31\envs\pyg123\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):
  File "C:\Users\xiaopengguo\anaconda31\envs\pyg123\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.4
* Qt Versions: 5.12.9, PyQt5 5.12.3 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  2.4.0 (OK)
pycodestyle >=2.3:  2.8.0 (OK)
pygments >=2.0   :  2.11.2 (OK)
pandas >=0.13.1  :  1.1.5 (OK)
numpy >=1.7      :  1.19.5 (OK)
sphinx >=0.6.6   :  4.4.0 (OK)
rope >=0.9.4     :  0.23.0 (OK)
jedi >=0.9.0     :  0.17.2 (OK)
nbconvert >=4.0  :  6.0.7 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  5.2.2 (OK)
IPython >=4.0    :  7.16.1 (OK)
pylint >=0.25    :  2.11.1 (OK)

```

**Comment by dalthviz** [comment]
Hi @xiaopengguo thank you for the feedback! Seems like you are using a quite old version of Spyder (the latest version currently is 5.2.2 and you are using 3.2.3). Could you try to update and check again? Also, how did you install Spyder? Let us know!

**Comment by xiaopengguo** [comment]
Thank you for the reply! I have reinstalled Spyder with 5.2.2 version and  it now works. Thanks a lot!
