### ISSUE TITLE
A fix for the behavior of spyderlib\utils\system.py on Windows

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1753]
_From [robro...@gmail.com](https://code.google.com/u/114002459288016453009/) on 2014-03-09T18:22:40Z_

Spyder Version:  2.3.0beta3
Python Version:  3.3.4 | Miniconda3/Anaconda 1.9.1 (64-bit)
Qt Version    :  4.8.4, PySide 1.2.1 on Windows 7
pyflakes >=0.6.0:  0.7.3 (OK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  1.1.0 (OK)
sphinx >=0.6.6  :  1.2.1 (OK)
rope >=0.9.2    :  None (NOK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.4.1 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1. Build and install Spyder on a machine with Windows 7 (and in my case Miniconda3/Anaconda Python 3.3 in my case), with no psutil module installed
2. Launch Spyder
3. Open an Internal Console window (View > Windows > Internal console) What is the expected output? What do you see instead? Expected output: no errors on the Internal Console, and Spyder displays memory usage at the bottom-right corner of the screen

What I see: No memory usage data, and this error message ticking continuously every second on the Internal Console:

Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\spyderlib\widgets\status.py", line 80, in update_label
    self.label.setText('&#37;d &#37;&#37;' &#37; self.get_value())
  File "C:\Miniconda3\lib\site-packages\spyderlib\widgets\status.py", line 93, in get_value
    return memory_usage()
  File "C:\Miniconda3\lib\site-packages\spyderlib\utils\system.py", line 20, in windows_memory_usage
    class MemoryStatus(wintypes.Structure):
AttributeError: 'module' object has no attribute 'Structure' 

Please provide any additional information below

. In my opinion the bug is in spyderlib\utils\system.py . It happens when a machine running on Windows has no psutil module installed. In this case Spyder's system.py will use the windows_memory_usage method. This method has a flaw in my opinion: it tries to use wintypes.Structure, wintypes.c_uint64, wintypes.sizeof and wintypes.byref when I think the correct classes and methods are under wintypes.ctypes (and not just wintypes).  
wintypes.DWORD is correct though, and should not be changed.

Performing these changes to system.py leads Spyder to correctly display the memory usage value, with no errors on the internal console.

For more info: http://stackoverflow.com/questions/22286622/trying-to-understand-an-error-wintypes-structure Thanks!

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1753_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-03-10T10:50:37Z_

I thought psutil came by default on Windows but it seems that's not the case for Anaconda.

I see you posted the fixes in SO, thanks. I'll try to add it as soon as I can.

**Status:** Accepted  
  **Labels:** MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-03-10T10:53:04Z_

An additional question: Does your changes work as expected in Python 2.7?

**Comment by spyder-issues-migrator** [comment]
_From [robro...@gmail.com](https://code.google.com/u/114002459288016453009/) on 2014-03-10T18:21:27Z_

Thanks for your reply! You have indeed a good point there. My change didn't work in Python 2.7 the way it was, I'll update my answer in Stackoverflow now.

From what I understand Python 2.7 and Python 3.3 both have a `ctypes` package that is called "version 1.1.0"... but the two are wAY different.

One of these differences is that in the package found in Python 2.7, wintypes.py starts with
from ctypes import *

while in Python 3.3, wintypes.py starts with
import ctypes

So please confirm this, but I think that's where all the problems originate. What's called wintypes.Structure in Py2.7 is just the ctypes.Structure class, imported as * in wintypes.py - isn't this right?

I'm going to update my answer in SO.

**Comment by spyder-issues-migrator** [comment]
_From [robro...@gmail.com](https://code.google.com/u/114002459288016453009/) on 2014-03-10T18:52:20Z_

Regarding psutil, I did a few tests:
it does get installed in the default Python 2.7 version of Anaconda.
If I keep this installed and create a Py3k environment, this installs Python 3.3.5 and does come with psutil also.
On the other side at first I had installed Miniconda3 and then downloaded Python 3 Anaconda, which installed a Python 3.3.4 version *without* psutil.

The psutil package is listed in the default packages of Anaconda/Python 3.3: http://docs.continuum.io/anaconda/pkgs.html so probably Miniconda3 is just mini and doesn't install it...

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-03-10T19:04:01Z_

Ok, thanks for the info. I think we just need to take into account the import change in wintypes.

Could you take a look at how we handle PY2/PY3 module renames in our spyderlib/py3compat.py module, and determine how we could handle this change there? Thanks.

**Comment by spyder-issues-migrator** [comment]
_From [robro...@gmail.com](https://code.google.com/u/114002459288016453009/) on 2014-03-11T08:40:45Z_

Thank you - it'd really be a pleasure... just let me say clearly that I am a molecular biologist with (so far) a limited amount of programming experience.

This said, what's in py3compat.py is not difficult to implement, but in the specific case of system.py, is there really a need for a Python version check?
See:
Py2: the current windows_memory_usage method in system.py imports byref, sizeof, c_uint64, and Structure from wintypes.py, and up to Python 2.7. these are just pushed from ctypes (from ctypes import *) with no modification. So importing them from ctypes really makes no difference, right?
Py3: this method raises an error, and it does so because again wintypes.py does not mention that class/variable/methods - they are all still in ctypes, just wintypes isn't importing them in its namespace anymore, right?

So, as of today's version of ctypes, both Python 2 and Python 3 can actually push these all from ctypes in the end. Only DWORD would be pushed from wintypes, and in both versions of Python. So the two versions, so far, can really work with the same code here.

**Comment by spyder-issues-migrator** [comment]
_From [robro...@gmail.com](https://code.google.com/u/114002459288016453009/) on 2014-03-11T21:26:46Z_

Ok, now the pull request is sent correctly: https://bitbucket.org/bioruffo/spyderlib/pull-request/1/changed-the-windows_memory_usage-function/diff Thanks!
Roberto

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-03-15T07:36:29Z_

This issue was updated by revision e700fc971086 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-03-15T07:37:20Z_

Thanks Roberto for your help with this one

**Comment by spyder-issues-migrator** [comment]
_From [robro...@gmail.com](https://code.google.com/u/114002459288016453009/) on 2014-03-15T12:28:31Z_

I'm happy to be of help :)
