### ISSUE TITLE
i inserted an envirement  called pip and value 1  and it said     winreg.SetValueEx(key, name, 0, types[name], reg[name])
ValueError: Could not convert the data to the specified type.


### ISSUE THREAD

**Issue by akrtkk** [spyder-ide/spyder#17538]
### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\ambar\anaconda3\lib\site-packages\spyder\utils\environ.py", line 168, in accept
    set_user_env(listdict2envdict(self.get_value()), parent=self)
  File "C:\Users\ambar\anaconda3\lib\site-packages\spyder\utils\environ.py", line 133, in set_user_env
    winreg.SetValueEx(key, name, 0, types[name], reg[name])
ValueError: Could not convert the data to the specified type.
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.7
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by dalthviz** [comment]
Hi @akrtkk thank you for the feedback. I was unable to reproduce this :/ Did you use the `Tools > Current user environmental variables...` action to add the env var `pip=1`?:

![imagen](https://user-images.githubusercontent.com/16781833/159955647-168cd937-1869-4a00-8e17-e2cd8634882c.png)

Also, I tested with Spyder 5.2.2, so could you try to use that version and check again? For that you will need to either create a new env using conda-forge (where Spyder 5.2.2 is available) or use our windows installer.

To create a new env with conda-forge you will need to run with an Anaconda propmt something like:

    conda create -n spyder-env -c conda-forge python=3.9 spyder=5.2.2

To try our Windows installer you will need to download the executable file from our release page here: https://github.com/spyder-ide/spyder/releases/tag/v5.2.2

Let us know if something of the above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
