### ISSUE TITLE
Spyder is not being able to connect to the kernel

### ISSUE THREAD

**Issue by vsapuy** [spyder-ide/spyder#17568]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

This is happening every time I open Spyder

Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError
Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError
Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method

Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply

Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
      File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method

Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method

Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError
Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply

Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method

Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: 
Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method

Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply

Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError
Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
      File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply

Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\d797150\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    TypeError:

**Comment by ccordoba12** [comment]
Hey @vsapuy, thanks for reporting. This error is already fixed in our latest version (5.2.2).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

After that, you can connect Spyder to your base environment by following these instructions:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

**Comment by vsapuy** [comment]
Thank Carlos!!!

It perfectly fine!!!
