### ISSUE TITLE
Connecting to kernels problem

### ISSUE THREAD

**Issue by auyeungquanlap** [spyder-ide/spyder#17669]
Traceback (most recent call last):
  File "/Users/LAP/opt/anaconda3/lib/python3.9/site-packages/qtconsole/manager.py", line 27, in poll
    super().poll()
  File "/Users/LAP/opt/anaconda3/lib/python3.9/site-packages/jupyter_client/restarter.py", line 143, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "/Users/LAP/opt/anaconda3/lib/python3.9/site-packages/jupyter_client/utils.py", line 26, in wrapped
    raise e
  File "/Users/LAP/opt/anaconda3/lib/python3.9/site-packages/jupyter_client/utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "/Users/LAP/opt/anaconda3/lib/python3.9/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "/Users/LAP/opt/anaconda3/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/LAP/opt/anaconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/LAP/opt/anaconda3/lib/python3.9/site-packages/jupyter_client/manager.py", line 523, in _async_restart_kernel
    await ensure_async(self.shutdown_kernel(now=now, restart=True))
  File "/Users/LAP/opt/anaconda3/lib/python3.9/site-packages/jupyter_client/utils.py", line 26, in wrapped
    raise e
  File "/Users/LAP/opt/anaconda3/lib/python3.9/site-packages/jupyter_client/utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "/Users/LAP/opt/anaconda3/lib/python3.9/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "/Users/LAP/opt/anaconda3/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/LAP/opt/anaconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/LAP/opt/anaconda3/lib/python3.9/site-packages/jupyter_client/manager.py", line 79, in wrapper
    raise e
  File "/Users/LAP/opt/anaconda3/lib/python3.9/site-packages/jupyter_client/manager.py", line 71, in wrapper
    out = await method(self, *args, **kwargs)
  File "/Users/LAP/opt/anaconda3/lib/python3.9/site-packages/jupyter_client/manager.py", line 482, in _async_shutdown_kernel
    await ensure_async(self._kill_kernel())
  File "/Users/LAP/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/ipythonconsole/utils/manager.py", line 109, in _kill_kernel
    self.kernel.wait()
AttributeError: 'SpyderKernelManager' object has no attribute 'kernel'
 
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by auyeungquanlap** [comment]
No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect. 
WARNING:traitlets:kernel restarted
WARNING:traitlets:kernel restarted
WARNING:traitlets:kernel restarted
WARNING:traitlets:kernel restarted
WARNING:traitlets:KernelRestarter: restart failed
WARNING:traitlets:kernel died: 25.003736972808838
