### ISSUE TITLE
crash when writing '()' for an undefined function of an undefined object

### ISSUE THREAD

**Issue by devitom** [spyder-ide/spyder#17660]
### What steps will reproduce the problem?

In the edit window, type "foo.bar ()"
Then the Issue reporter screen appears and no further code analysis can occur.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/generic/anaconda3/lib/python3.8/site-packages/spyder/plugins/completion/providers/languageserver/client.py", line 558, in on_msg_received
    handler(resp['result'], req_id)
  File "/home/generic/anaconda3/lib/python3.8/site-packages/spyder/plugins/completion/providers/languageserver/providers/document.py", line 155, in process_signature_completion
    if len(response['signatures']) > 0:
TypeError: list indices must be integers or slices, not str
```

## Versions

* Spyder version: 5.3.0 
* Python version: 3.8.13
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 4.15.0-171-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.32.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.5.0 (OK)
nbconvert >=4.0               :  6.5.0 (OK)
numpydoc >=0.6.0              :  1.2.1 (OK)
parso >=0.7.0;<0.9.0          :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.13.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.0 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.0 (OK)
qtpy >=2.0.1                  :  2.0.1 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  62.1.0 (OK)
sphinx >=0.6.6                :  4.5.0 (OK)
spyder_kernels >=2.3.0;<2.4.0 :  2.3.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.7 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  1.22.3 (OK)
pandas >=1.1.1                :  1.4.1 (OK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @devitom, thanks for reporting. Please install a more recent version of Parso because the one you have now (0.7.0) is incompatible with your Jedi package (0.18.1).

You can do that by running

    conda install -c conda-forge parso=0.8

assuming you're using Conda-forge.

That could solve your problem because I can't reproduce it locally.

**Comment by devitom** [comment]
Thanks @ccordoba12 , the update solved the issue.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
