### ISSUE TITLE
error

### ISSUE THREAD

**Issue by XinxinWu-sysu** [spyder-ide/spyder#17690]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\oak\stanford\groups\omramom\group_members\fvdav\projects\precip_clustering\envstf1\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "D:\oak\stanford\groups\omramom\group_members\fvdav\projects\precip_clustering\envstf1\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "D:\oak\stanford\groups\omramom\group_members\fvdav\projects\precip_clustering\envstf1\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
      File "D:\oak\stanford\groups\omramom\group_members\fvdav\projects\precip_clustering\envstf1\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 215, in _handle_execute_reply

Traceback (most recent call last):
  File "D:\oak\stanford\groups\omramom\group_members\fvdav\projects\precip_clustering\envstf1\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
      File "D:\oak\stanford\groups\omramom\group_members\fvdav\projects\precip_clustering\envstf1\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 215, in _handle_execute_reply

Traceback (most recent call last):
  File "D:\oak\stanford\groups\omramom\group_members\fvdav\projects\precip_clustering\envstf1\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "D:\oak\stanford\groups\omramom\group_members\fvdav\projects\precip_clustering\envstf1\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
      File "D:\oak\stanford\groups\omramom\group_members\fvdav\projects\precip_clustering\envstf1\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 215, in _handle_execute_reply
      File "D:\oak\stanford\groups\omramom\group_members\fvdav\projects\precip_clustering\envstf1\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 60, in refresh_namespacebrowser

Traceback (most recent call last):
  File "D:\oak\stanford\groups\omramom\group_members\fvdav\projects\precip_clustering\envstf1\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "D:\oak\stanford\groups\omramom\group_members\fvdav\projects\precip_clustering\envstf1\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
      File "D:\oak\stanford\groups\omramom\group_members\fvdav\projects\precip_clustering\envstf1\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 215, in _handle_execute_reply

Traceback (most recent call last):
  File "D:\oak\stanford\groups\omramom\group_members\fvdav\projects\precip_clustering\envstf1\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
      File "D:\oak\stanford\groups\omramom\group_members\fvdav\projects\precip_clustering\envstf1\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 215, in _handle_execute_reply

Traceback (most recent call last):
  File "D:\oak\stanford\groups\omramom\group_members\fvdav\projects\precip_clustering\envstf1\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
      File "D:\oak\stanford\groups\omramom\group_members\fvdav\projects\precip_clustering\envstf1\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 215, in _handle_execute_reply

Traceback (most recent call last):

Traceback (most recent call last):
  File "D:\oak\stanford\groups\omramom\group_members\fvdav\projects\precip_clustering\envstf1\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "D:\oak\stanford\groups\omramom\group_members\fvdav\projects\precip_clustering\envstf1\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "D:\oak\stanford\groups\omramom\group_members\fvdav\projects\precip_clustering\envstf1\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "D:\oak\stanford\groups\omramom\group_members\fvdav\projects\precip_clustering\envstf1\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.15
* Qt Versions: 5.12.9, PyQt5 5.12.3 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  2.4.0 (OK)
pycodestyle >=2.3:  2.8.0 (OK)
pygments >=2.0   :  2.11.2 (OK)
pandas >=0.13.1  :  1.1.5 (OK)
numpy >=1.7      :  1.19.5 (OK)
sphinx >=0.6.6   :  4.5.0 (OK)
rope >=0.9.4     :  1.0.0 (OK)
jedi >=0.9.0     :  0.17.2 (OK)
nbconvert >=4.0  :  6.0.7 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  5.2.2 (OK)
IPython >=4.0    :  7.16.1 (OK)
pylint >=0.25    :  1.8.4 (OK)

```

**Comment by ccordoba12** [comment]
Hey @XinxinWu-sysu, thanks for reporting. This error is already fixed in our latest version (5.3.0).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder
