### ISSUE TITLE
 focal-loss version  compatibility with early version of tensorboard at installation.

### ISSUE THREAD

**Issue by ahmedmaalej** [spyder-ide/spyder#17707]
### What steps will reproduce the problem?

executing  pip install focal-loss
in anaconda env opened as administrator
made unwanted uninstall of tensorboard

 Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.2.2
    Uninstalling tensorboard-2.2.2:
      Successfully uninstalled tensorboard-2.2.2
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'D:\\Ahmed\\code\\enviorment\\conda_env_dir\\tf220\\Lib\\site-packages\\tensorflow\\lite\\experimental\\microfrontend\\python\\ops\\_audio_microfrontend_op.so'
Consider using the `--user` option or check the permissions.

### Traceback
```python-traceback
Exception ignored in: <function BaseEventLoop.__del__ at 0x000002BE2ED08B80>
Traceback (most recent call last):
  File "D:\Ahmed\code\enviorment\conda_env_dir\tf220\lib\asyncio\base_events.py", line 648, in __del__
    self.close()
  File "D:\Ahmed\code\enviorment\conda_env_dir\tf220\lib\asyncio\proactor_events.py", line 679, in close
    signal.set_wakeup_fd(-1)
ValueError: set_wakeup_fd only works in main thread
```

## Versions

* Spyder version: 5.2.2 
* Python version: 3.8.0
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.5.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.10.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.1.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.22.0 (OK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  1.4.1 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by dalthviz** [comment]
Hi @ahmedmaalej seems like your issue is not related with Spyder, maybe your issue is related with this one: https://github.com/artemmavrin/focal-loss/issues/17 ?

If you install pip packages maybe creating an enviroment only using pip packages could help. So by running from an Anaconda prompt something like:

    conda create -n pip-tf220 -c conda-forge python=3.8
    conda activate pip-tf220
    pip install <packages you want to use>

Let us know if something of the above helps.

**Comment by dalthviz** [comment]
Closing due to lack of response
