### ISSUE TITLE
Errors while using autocompletion in a debugging session

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1771]
_From [lorenzo....@gmail.com](https://code.google.com/u/110286238015474619838/) on 2014-03-25T10:15:08Z_

Spyder Version:  2.2.5
Python Version:  2.6.6
Qt Version    :  4.8.0, PySide 1.2.1 on Linux
pyflakes >=0.5.0:  0.7.3 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  1.1.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.1.3 (OK)
matplotlib >=1.0:  0.99.1.1 (NOK)
sympy >=0.7.0   :  None (NOK)
pylint >=0.25   :  0.21.1 (NOK) 

What steps will reproduce the problem?

 1. Start a debug session
2. In the debugger console, attempt code autocompletion (TAB or CTRL+SPACE)
3. A python error appears in Spyder internal console (full error message included at the end of this report) What is the expected output? What do you see instead? Expected output: variable name gets autocompleted (or autocompletion fails silently if no completion is available). Instead: error messages pop up in the internal console. 

Please provide any additional information below

. Full error message:

Traceback (most recent call last):
  File "[...]/lib/python2.6/site-packages/spyderlib/widgets/shell.py", line 298, in keyPressEvent
    self.postprocess_keyevent(event)
  File "[...]/lib/python2.6/site-packages/spyderlib/widgets/shell.py", line 718, in postprocess_keyevent
    ShellBaseWidget.postprocess_keyevent(self, event)
  File "[...]/lib/python2.6/site-packages/spyderlib/widgets/shell.py", line 361, in postprocess_keyevent
    self._key_ctrl_space()
  File "[...]/lib/python2.6/site-packages/spyderlib/widgets/shell.py", line 755, in _key_ctrl_space
    self.show_code_completion(automatic=False)
  File "[...]/lib/python2.6/site-packages/spyderlib/widgets/shell.py", line 890, in show_code_completion
    b_k_g = dir(__builtin__)+self.get_globals_keys()+keyword.kwlist
TypeError: can only concatenate list (not "NoneType") to list

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1771_

**Comment by spyder-issues-migrator** [comment]
_From [abhiji...@gmail.com](https://code.google.com/u/113614438108059946047/) on 2014-07-24T22:48:54Z_

Have you found the solution to this issue? If so I would be grateful if you could share it. Thanks.

**Comment by spyder-issues-migrator** [comment]
_From [lorenzo....@gmail.com](https://code.google.com/u/110286238015474619838/) on 2014-07-24T22:51:18Z_

No, I have not found a solution unfortunately :-(

**Comment by spyder-issues-migrator** [comment]
_From [robro...@gmail.com](https://code.google.com/u/114002459288016453009/) on 2014-08-22T19:23:46Z_

Is this still relevant? This line of code has been changed 15 months ago. I can't replicate the error.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-23T08:37:10Z_

Thanks for noticing. I can't reproduce it either.

Please update to 2.3.0, where the error has gone! :)

**Status:** WontFix
