### ISSUE TITLE
spyder's errors

### ISSUE THREAD

**Issue by John36er** [spyder-ide/spyder#17773]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
When start spyder,it shows this error:
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 23, in 
start.main()
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 299, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site‑packages\ipykernel\kernelapp.py", line 42, in 
from traitlets.utils import filefind
ImportError: cannot import name 'filefind' from 'traitlets.utils' (C:\ProgramData\Anaconda3\lib\site‑packages\traitlets\utils\__init__.py)
  
  Hope to get your help.Thanks.

**Comment by ccordoba12** [comment]
Hey @John36er, thanks for reporting. Please remove this directory

    C:\Users\Administrator\AppData\Roaming\Python

to fix your problem. And for next time, please don't install packages using `pip` if they are available with `conda`. That's the source of this problem.

**Comment by John36er** [comment]
OK,I get your suggestions,thank you.






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Carlos ***@***.***&gt;; 
发送时间: 2022年4月27日(星期三) 晚上10:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [spyder-ide/spyder] spyder&#39;s errors (Issue #17773)





 
Hey @John36er, thanks for reporting. Please remove this directory
 C:\Users\Administrator\AppData\Roaming\Python  
to fix your problem. And for next time, please don't install packages using pip if they are available with conda. That's the source of this problem.
