### ISSUE TITLE
spyder issue reporter

### ISSUE THREAD

**Issue by eddaz7** [spyder-ide/spyder#17776]
When closing spyder, issue reporter briefly opens and closes.

I've tried this on 2 different machines on fresh conda environments.

channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20210324.2=h0e60522_0
  - alabaster=0.7.12=py_0
  - argh=0.26.2=pyh9f0ad1d_1002
  - arrow=1.2.2=pyhd8ed1ab_0
  - arrow-cpp=7.0.0=py310he67c4b2_4_cpu
  - astroid=2.11.3=py310h5588dad_0
  - atomicwrites=1.4.0=pyh9f0ad1d_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - autopep8=1.6.0=pyhd8ed1ab_1
  - aws-c-cal=0.5.11=he19cf47_0
  - aws-c-common=0.6.2=h8ffe710_0
  - aws-c-event-stream=0.2.7=h70e1b0c_13
  - aws-c-io=0.10.5=h2fe331c_0
  - aws-checksums=0.1.11=h1e232aa_7
  - aws-sdk-cpp=1.8.186=hb0612c5_3
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bcrypt=3.2.0=py310he2412df_3
  - beautifulsoup4=4.11.1=pyha770c72_0
  - binaryornot=0.4.4=py_1
  - black=22.3.0=pyhd8ed1ab_0
  - bleach=5.0.0=pyhd8ed1ab_0
  - brotli=1.0.9=h8ffe710_7
  - brotli-bin=1.0.9=h8ffe710_7
  - brotlipy=0.7.0=py310he2412df_1004
  - bzip2=1.0.8=h8ffe710_4
  - c-ares=1.18.1=h8ffe710_0
  - ca-certificates=2021.10.8=h5b45459_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2021.10.8=py310h5588dad_2
  - cffi=1.15.0=py310hcbf9ad4_0
  - chardet=4.0.0=py310h5588dad_3
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - click=8.1.2=py310h5588dad_0
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cookiecutter=1.7.3=pyh6c4a22f_1
  - cryptography=36.0.2=py310ha857299_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.6.0=py310h8a704f9_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - diff-match-patch=20200713=pyh9f0ad1d_0
  - dill=0.3.4=pyhd8ed1ab_0
  - docutils=0.17.1=py310h5588dad_2
  - entrypoints=0.4=pyhd8ed1ab_0
  - flake8=4.0.1=pyhd8ed1ab_2
  - fonttools=4.33.3=py310he2412df_0
  - freetype=2.10.4=h546665d_1
  - gflags=2.2.2=ha925a31_1004
  - glog=0.6.0=h4797de2_0
  - grpc-cpp=1.43.2=he33f7c1_1
  - h5py=3.6.0=nompi_py310h00cbb18_100
  - hdf5=1.12.1=nompi_h2a0e4a3_104
  - icu=69.1=h0e60522_0
  - idna=3.3=pyhd8ed1ab_0
  - imagesize=1.3.0=pyhd8ed1ab_0
  - importlib-metadata=4.11.3=py310h5588dad_1
  - importlib_metadata=4.11.3=hd8ed1ab_1
  - importlib_resources=5.7.1=pyhd8ed1ab_0
  - inflection=0.5.1=pyh9f0ad1d_0
  - intel-openmp=2022.0.0=h57928b3_3663
  - intervaltree=3.0.2=py_0
  - ipykernel=6.13.0=py310hbbfc1a7_0
  - ipython=7.32.0=py310h5588dad_0
  - ipython_genutils=0.2.0=py_1
  - isort=5.10.1=pyhd8ed1ab_0
  - jbig=2.1=h8d14728_2003
  - jedi=0.18.1=py310h5588dad_1
  - jellyfish=0.9.0=py310he2412df_1
  - jinja2=3.1.1=pyhd8ed1ab_0
  - jinja2-time=0.2.0=pyhd8ed1ab_3
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h8ffe710_1
  - jsonschema=4.4.0=pyhd8ed1ab_0
  - jupyter_client=7.3.0=pyhd8ed1ab_0
  - jupyter_core=4.9.2=py310h5588dad_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - keyring=23.4.0=py310h5588dad_2
  - kiwisolver=1.4.2=py310h476a331_1
  - krb5=1.19.3=h1176d77_0
  - lazy-object-proxy=1.7.1=py310he2412df_1
  - lcms2=2.12=h2a16943_0
  - lerc=3.0=h0e60522_0
  - libblas=3.9.0=14_win64_mkl
  - libbrotlicommon=1.0.9=h8ffe710_7
  - libbrotlidec=1.0.9=h8ffe710_7
  - libbrotlienc=1.0.9=h8ffe710_7
  - libcblas=3.9.0=14_win64_mkl
  - libclang=13.0.1=default_h81446c8_0
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=7.83.0=h789b8ee_0
  - libdeflate=1.10=h8ffe710_0
  - libffi=3.4.2=h8ffe710_5
  - libgoogle-cloud=1.35.0=h7f3f1e6_2
  - liblapack=3.9.0=14_win64_mkl
  - libpng=1.6.37=h1d00b33_2
  - libprotobuf=3.19.4=h7755175_0
  - libsodium=1.0.18=h8d14728_1
  - libspatialindex=1.9.3=h39d44d4_4
  - libssh2=1.10.0=h680486a_2
  - libthrift=0.16.0=h636ae23_1
  - libtiff=4.3.0=hc4061b1_3
  - libutf8proc=2.7.0=hcb41399_0
  - libwebp=1.2.2=h57928b3_0
  - libwebp-base=1.2.2=h8ffe710_1
  - libxcb=1.13=hcd874cb_1004
  - libzlib=1.2.11=h8ffe710_1014
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.1.1=py310he2412df_1
  - matplotlib-base=3.5.1=py310h79a7439_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py310he2412df_1005
  - mkl=2022.0.0=h0e2418a_796
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=0.4.3=py310h5588dad_5
  - nbclient=0.6.0=pyhd8ed1ab_0
  - nbconvert=6.5.0=pyhd8ed1ab_0
  - nbconvert-core=6.5.0=pyhd8ed1ab_0
  - nbconvert-pandoc=6.5.0=pyhd8ed1ab_0
  - nbformat=5.3.0=pyhd8ed1ab_0
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - numpy=1.22.3=py310hed7ac4c_2
  - numpydoc=1.2.1=pyhd8ed1ab_0
  - openjpeg=2.4.0=hb211442_1
  - openssl=1.1.1n=h8ffe710_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.2=py310hf5e1058_1
  - pandoc=2.18=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - paramiko=2.10.4=pyhd8ed1ab_0
  - parquet-cpp=1.5.1=2
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.1.0=py310h767b3fd_2
  - pip=22.0.4=pyhd8ed1ab_0
  - platformdirs=2.5.1=pyhd8ed1ab_0
  - pluggy=1.0.0=py310h5588dad_3
  - poyo=0.5.0=py_0
  - prompt-toolkit=3.0.29=pyha770c72_0
  - psutil=5.9.0=py310he2412df_1
  - pthread-stubs=0.4=hcd874cb_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pyarrow=7.0.0=py310h4115056_4_cpu
  - pycodestyle=2.8.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydocstyle=6.1.1=pyhd8ed1ab_0
  - pyflakes=2.4.0=pyhd8ed1ab_0
  - pygments=2.12.0=pyhd8ed1ab_0
  - pylint=2.13.5=pyhd8ed1ab_0
  - pyls-spyder=0.4.0=pyhd8ed1ab_0
  - pynacl=1.5.0=py310h4f637d6_1
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.8=pyhd8ed1ab_0
  - pyqt=5.12.3=py310h5588dad_8
  - pyqt-impl=5.12.3=py310h8a704f9_8
  - pyqt5-sip=4.19.18=py310h8a704f9_8
  - pyqtchart=5.12=py310h8a704f9_8
  - pyqtwebengine=5.12.1=py310h8a704f9_8
  - pyrsistent=0.18.1=py310he2412df_1
  - pysocks=1.7.1=py310h5588dad_5
  - python=3.10.4=h9a09f29_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.15.3=pyhd8ed1ab_0
  - python-lsp-black=1.2.1=pyhd8ed1ab_0
  - python-lsp-jsonrpc=1.0.0=pyhd8ed1ab_0
  - python-lsp-server=1.4.1=pyhd8ed1ab_1
  - python-slugify=6.1.1=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2022.1=pyhd8ed1ab_0
  - pywin32=303=py310he2412df_0
  - pywin32-ctypes=0.2.0=py310h5588dad_1005
  - pyyaml=6.0=py310he2412df_4
  - pyzmq=22.3.0=py310h73ada01_2
  - qdarkstyle=3.0.3=pyhd8ed1ab_0
  - qstylizer=0.2.1=pyhd8ed1ab_0
  - qt=5.12.9=h556501e_6
  - qtawesome=1.1.1=pyhd8ed1ab_0
  - qtconsole=5.3.0=pyhd8ed1ab_0
  - qtconsole-base=5.3.0=pyhd8ed1ab_0
  - qtpy=2.0.1=pyhd8ed1ab_0
  - re2=2022.02.01=h0e60522_0
  - requests=2.27.1=pyhd8ed1ab_0
  - rope=1.0.0=pyhd8ed1ab_0
  - rtree=1.0.0=py310h1cbd46b_1
  - scikit-learn=1.0.2=py310h4dafddf_0
  - scipy=1.8.0=py310h33db832_1
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - setuptools=62.1.0=py310h5588dad_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.8=ha925a31_3
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.3.1=pyhd8ed1ab_0
  - sphinx=4.5.0=pyh6c4a22f_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - spyder=5.3.0=py310h5588dad_0
  - spyder-kernels=2.3.0=py310h5588dad_0
  - sqlite=3.38.2=h8ffe710_0
  - statsmodels=0.13.2=py310h2873277_0
  - tbb=2021.5.0=h2d74725_1
  - text-unidecode=1.3=py_0
  - textdistance=4.2.2=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - three-merge=0.1.1=pyh9f0ad1d_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h8ffe710_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.1=py310he2412df_3
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typed-ast=1.5.3=py310he2412df_0
  - typing_extensions=4.2.0=pyha770c72_1
  - tzdata=2022a=h191b570_0
  - ucrt=10.0.20348.0=h57928b3_0
  - ujson=5.2.0=py310h8a704f9_1
  - unicodedata2=14.0.0=py310he2412df_1
  - unidecode=1.3.4=pyhd8ed1ab_0
  - urllib3=1.26.9=pyhd8ed1ab_0
  - vc=14.2=hb210afc_6
  - vs2015_runtime=14.29.30037=h902a5da_6
  - watchdog=2.1.7=py310h5588dad_1
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=py310h5588dad_4
  - wrapt=1.14.0=py310he2412df_1
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.5=h62dcd97_1
  - yaml=0.2.5=h8ffe710_2
  - yapf=0.32.0=pyhd8ed1ab_0
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.11=h8ffe710_1014
  - zstd=1.5.2=h6255e5f_0

**Comment by dalthviz** [comment]
Hi @eddaz7 thank you for the feedback. Could you try to run spyder in debug mode and post the generated log here? For that run from an Anaconda prompt spyder with the `debug-info` flag, so something like `spyder --debug-info verbose`

Let us know

**Comment by eddaz7** [comment]
yes, thanks.

2022-04-27 20:13:43,354 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin editor
2022-04-27 20:13:43,361 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin help
2022-04-27 20:13:43,362 [DEBUG] [spyder.api.widgets.main_widget] -> Docking plugin back to the main window
2022-04-27 20:13:43,363 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin internal_console
2022-04-27 20:13:43,365 [DEBUG] [spyder.api.widgets.main_widget] -> Docking plugin back to the main window
2022-04-27 20:13:43,367 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin onlinehelp
2022-04-27 20:13:43,369 [DEBUG] [spyder.api.widgets.main_widget] -> Docking plugin back to the main window
2022-04-27 20:13:43,370 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin toolbar
2022-04-27 20:13:43,371 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin shortcuts
2022-04-27 20:13:43,375 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin appearance
2022-04-27 20:13:43,375 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin application
2022-04-27 20:13:43,375 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin run
2022-04-27 20:13:43,375 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin completions
2022-04-27 20:13:43,376 [DEBUG] [spyder.plugins.completion.providers.fallback.actor] -> Fallback plugin stopping...
2022-04-27 20:13:43,376 [INFO] [spyder.plugins.completion.providers.languageserver.provider] -> Shutting down LSP manager...
2022-04-27 20:13:43,378 [INFO] [spyder.plugins.completion.providers.languageserver.provider] -> Stopping LSP client for python...
2022-04-27 20:13:43,378 [INFO] [spyder.plugins.completion.providers.languageserver.client] -> Stopping python client...
2022-04-27 20:13:43,413 [DEBUG] [spyder.plugins.editor.widgets.codeeditor] -> Stopping completion services for C:\Users\edudv\.spyder-py3\temp.py
2022-04-27 20:13:43,414 [DEBUG] [spyder.plugins.completion.providers.snippets.actor] -> Snippets plugin stopping...
2022-04-27 20:13:43,415 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin find_in_files
2022-04-27 20:13:43,417 [DEBUG] [spyder.api.widgets.main_widget] -> Docking plugin back to the main window
2022-04-27 20:13:43,424 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin variable_explorer
2022-04-27 20:13:43,426 [DEBUG] [spyder.config.manager] -> Sending notification to observers of __section in configuration section variable_explorer
2022-04-27 20:13:43,428 [DEBUG] [spyder.api.widgets.main_widget] -> Docking plugin back to the main window
2022-04-27 20:13:43,429 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin statusbar
2022-04-27 20:13:43,429 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin historylog
2022-04-27 20:13:43,432 [DEBUG] [spyder.api.widgets.main_widget] -> Docking plugin back to the main window
2022-04-27 20:13:43,432 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin project_explorer
2022-04-27 20:13:43,434 [DEBUG] [spyder.api.widgets.main_widget] -> Docking plugin back to the main window
2022-04-27 20:13:43,436 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin preferences
2022-04-27 20:13:43,436 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin main_interpreter
2022-04-27 20:13:43,437 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin tours
2022-04-27 20:13:43,437 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin outline_explorer
2022-04-27 20:13:43,439 [DEBUG] [spyder.api.widgets.main_widget] -> Docking plugin back to the main window
2022-04-27 20:13:43,439 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin plots
2022-04-27 20:13:43,441 [DEBUG] [spyder.api.widgets.main_widget] -> Docking plugin back to the main window
2022-04-27 20:13:43,441 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin pylint
2022-04-27 20:13:43,443 [DEBUG] [spyder.api.widgets.main_widget] -> Docking plugin back to the main window
2022-04-27 20:13:43,444 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin breakpoints
2022-04-27 20:13:43,446 [DEBUG] [spyder.api.widgets.main_widget] -> Docking plugin back to the main window
2022-04-27 20:13:43,446 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin workingdir
2022-04-27 20:13:43,447 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin mainmenu
2022-04-27 20:13:43,447 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin profiler
2022-04-27 20:13:43,449 [DEBUG] [spyder.api.widgets.main_widget] -> Docking plugin back to the main window
2022-04-27 20:13:43,453 [DEBUG] [asyncio] -> Using proactor: IocpProactor
2022-04-27 20:13:43,671 [DEBUG] [traitlets] -> connecting shell channel to tcp://127.0.0.1:52157
2022-04-27 20:13:43,671 [DEBUG] [traitlets] -> Connecting to: tcp://127.0.0.1:52157
Exception ignored in: <function KernelClient.__del__ at 0x000001BEFFF3A0E0>
Traceback (most recent call last):
  File "C:\Users\edudv\miniconda3\envs\ml\lib\site-packages\jupyter_client\client.py", line 122, in __del__
    if self.channels_running:
AttributeError: 'QtKernelClient' object has no attribute 'channels_running'
2022-04-27 20:13:43,678 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin ipython_console
2022-04-27 20:13:43,680 [DEBUG] [spyder.api.widgets.main_widget] -> Docking plugin back to the main window
2022-04-27 20:13:43,681 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin explorer
2022-04-27 20:13:43,683 [DEBUG] [spyder.api.widgets.main_widget] -> Docking plugin back to the main window
2022-04-27 20:13:43,690 [DEBUG] [spyder.api.plugin_registration.registry] -> Deleting plugin layout
2022-04-27 20:13:43,858 [DEBUG] [spyder.plugins.editor.widgets.editor] -> method 'editorstack_closed':
2022-04-27 20:13:43,858 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     self  : <spyder.plugins.editor.widgets.editor.EditorSplitter object at 0x000001BE8597B130>

**Comment by dalthviz** [comment]
Thanks for the log @eddaz7 ! Seems like an error is being raised from `jupyter_client`:

```
Exception ignored in: <function KernelClient.del at 0x000001BEFFF3A0E0>
Traceback (most recent call last):
File "C:\Users\edudv\miniconda3\envs\ml\lib\site-packages\jupyter_client\client.py", line 122, in del
if self.channels_running:
AttributeError: 'QtKernelClient' object has no attribute 'channels_running'
```

For the moment as a workaround, could you downgrade to `jupyter_client <=7.2.0` and check if you see the Spyder error dialog? Let us know

Also pinging @ccordoba12 just in case.

**Comment by eddaz7** [comment]
thank you, for your response.
When i downgrade to **jupyter_client <=7.2.0** i don't get any errors.
However, when using **jupyter_client <=7.2.2** i did get some **asyncio** and **zmq* errors. I don't know if you are aware of this. If you want i can create other issue with logs.

**Comment by dalthviz** [comment]
About the zmq error that was reported at https://github.com/spyder-ide/spyder/issues/17615 so no need for a new issue but thank you for letting us know :+1:

**Comment by ccordoba12** [comment]
I submitted https://github.com/jupyter/jupyter_client/pull/785 to fix this. If it's not accepted, we'll have to implement the same patch on our side.

**Comment by ccordoba12** [comment]
@dalthviz, my PR was accepted and included in jupyter-client 7.3.1. I'll bump our requirement on that package in Spyder-kernels so that our users don't encounter this bug.

I'll do that in a couple of days because I need to wait for the package to be available in conda-forge.

**Comment by eddaz7** [comment]
nice 👍

**Comment by dalthviz** [comment]
Just in case @ccordoba12 jupyter_client 7.3.1 is already available in conda-forge: https://anaconda.org/conda-forge/jupyter_client

**Comment by ccordoba12** [comment]
Great! Thanks for letting me know about it. I submitted PR https://github.com/spyder-ide/spyder-kernels/pull/382 and now I'll update our subrepo here to close this issue.
