### ISSUE TITLE
not able to run script from editor

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1777]
_From [dinesh.t...@gmail.com](https://code.google.com/u/117148994520783226804/) on 2014-04-02T15:19:21Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1.tried to run a simple print statement from spyder editor
2.i declared a,b=1,2
3.print a,b What is the expected output? What do you see instead? 1,2

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/plugins/externalconsole.py", line 696, in run_script_in_current_shell
    "and try again.") &#37; osp.basename(filename), QMessageBox.Ok)
  File "/usr/lib/python2.7/posixpath.py", line 112, in basename
    i = p.rfind('/') + 1
AttributeError: 'QString' object has no attribute 'rfind' What version of the product are you using? On what operating system? spyder 2.7 on ubuntu 12.04 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1777_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-01T15:22:29Z_

It seems you were using a too old version of Spyder. I hope by updating to 2.3.2 this problem is fixed for you :-)

**Status:** WontFix
