### ISSUE TITLE
Error while importing tensorflow from Spyder

### ISSUE THREAD

**Issue by SanjuSoni** [spyder-ide/spyder#17783]
I am able to import tensorflow from python terminal outside of Spyder editor but unfortunately, it is showing an error while importing tensorflow package. Error is listed below:

```

import tensorflow as tf

2022-04-28 21:44:42.471112: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Error in callback <bound method AutoreloadMagics.post_execute_hook of <autoreload.AutoreloadMagics object at 0x000001E4926584C8>> (for post_execute):
Traceback (most recent call last):

  File "C:\Users\suman\miniconda3\envs\TF15\lib\site-packages\IPython\extensions\autoreload.py", line 538, in post_execute_hook
    _, pymtime = self._reloader.filename_and_mtime(sys.modules[modname])

  File "C:\Users\suman\miniconda3\envs\TF15\lib\site-packages\IPython\extensions\autoreload.py", line 184, in filename_and_mtime
    if not hasattr(module, '__file__') or module.__file__ is None:

  File "C:\Users\suman\miniconda3\envs\TF15\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()

  File "C:\Users\suman\miniconda3\envs\TF15\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)

  File "C:\Users\suman\miniconda3\envs\TF15\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load

  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 728, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "C:\Users\suman\miniconda3\envs\TF15\lib\site-packages\tensorflow_core\contrib\__init__.py", line 39, in <module>
    from tensorflow.contrib import compiler

  File "C:\Users\suman\miniconda3\envs\TF15\lib\site-packages\tensorflow_core\contrib\compiler\__init__.py", line 21, in <module>
    from tensorflow.contrib.compiler import jit

  File "C:\Users\suman\miniconda3\envs\TF15\lib\site-packages\tensorflow_core\contrib\compiler\__init__.py", line 22, in <module>
    from tensorflow.contrib.compiler import xla

  File "C:\Users\suman\miniconda3\envs\TF15\lib\site-packages\tensorflow_core\contrib\compiler\xla.py", line 22, in <module>
    from tensorflow.python.estimator import model_fn as model_fn_lib

  File "C:\Users\suman\miniconda3\envs\TF15\lib\site-packages\tensorflow_core\python\estimator\model_fn.py", line 26, in <module>
    from tensorflow_estimator.python.estimator import model_fn

  File "C:\Users\suman\miniconda3\envs\TF15\lib\site-packages\tensorflow_estimator\__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1 import estimator

  File "C:\Users\suman\miniconda3\envs\TF15\lib\site-packages\tensorflow_estimator\_api\v1\estimator\__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental

  File "C:\Users\suman\miniconda3\envs\TF15\lib\site-packages\tensorflow_estimator\_api\v1\estimator\experimental\__init__.py", line 10, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder

  File "C:\Users\suman\miniconda3\envs\TF15\lib\site-packages\tensorflow_estimator\python\estimator\canned\dnn.py", line 27, in <module>
    from tensorflow_estimator.python.estimator import estimator

  File "C:\Users\suman\miniconda3\envs\TF15\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 36, in <module>
    from tensorflow.python.profiler import trace

ImportError: cannot import name 'trace' from 'tensorflow.python.profiler' (C:\Users\suman\miniconda3\envs\TF15\lib\site-packages\tensorflow_core\python\profiler\__init__.py)


Warning
It seems you're trying to use a module that doesn't come with our installer. Check this FAQ in our docs to learn how to do this.




```

Anyone, please help me to fix it. 

I am using Windows 11 and the latest Spyder editor.

**Comment by dalthviz** [comment]
Hi @SanjuSoni thank you for the feedback. Seems like there is some sort of incompatibilty between the version of tensorflow-estimator and tensorflow-core you are using. How did you install Spyder and tensorflow? Also, you are using Spyder 5.3.0, right? Could you share the conda list of the envs you are using? Let us know

**Comment by SanjuSoni** [comment]
> 

Hii @dalthviz, thanks for pointing out my issue.

The complete information of the spyder editor is 
* Spyder version: 5.3.0 None
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.6
* Operating System: Windows 10

here my OS is windows 11.

==================================


I have created two different environments dedicated to Tensorflow 1.15 and 2.6.0 versions.

The virtual environments are created by conda command and the list of these environments are as follows:

1st environment name ========        TF15             [ tensorflow 1.15 installed here]
2nd environment name========        TF2              [ tensorflow 2.6.0 installed here]

I have installed TensorFlow ver 1.15 in venv TF15 by using the conda command      `conda install tensorflow-gpu=1.15` 


Note: using anaconda kernel, the python interpreter is able to import the TensorFlow properly in both environment. I am using Spyder editor from last two years and it acts like a universal editor for me in case of python scripts.

But, unfortunately, after reinstallation of my OS and spyder version 5.3.0, I am facing such issue.



Kindly provide some alternate/solution for it.

Thanks!!!

**Comment by dalthviz** [comment]
@SanjuSoni you will need to manually downgrade `tensorflow-estimator` to 1.15 (not sure why but `conda install tensorflow-gpu=1.15` installs `tensorflow-estimator` 2.6.0 which I would say is incompatible with `tensorflow` 1.15.0). For that, run from an Anaconda prompt with your env activated `conda install tensorflow-estimator=1.15`

This is issues is not directly related with Spyder but let us know if the above helps

**Comment by SanjuSoni** [comment]
You are Genius @dalthviz SIr.

It works for both environments TF15 and Tf2 after degrading the tensorflow-estimator.



In TF15 env
====================

import tensorflow as tf

2022-04-29 11:48:54.814574: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll

tf.__version__
Out[2]: '1.15.0'

=========================





In TF2 env
==============================
import tensorflow as tf

tf.__version__
Out[2]: '2.6.0'

===========================




Thanks for your valuable support!!!!!!!!

**Comment by parthkvv** [comment]
Using the command conda install tensorflow-estimator=1.15 crashed python on my system.
Package details are as follows:
cudatoolkit     10.0.130                      
cudnn    7.6.5                
cython  0.29.32                  
h5py    2.10.0          
hdf5  1.10.4              
keras    2.1.3                   
keras-applications 1.0.8                  
keras-preprocessing   1.1.2             
numpy  1.18.1                 
numpy-base  1.21.5     
opencv-contrib-python   4.5.5.62                 
opencv-python   4.1.2.30               
opencv-python-headless   4.6.0.66               
pillow    9.2.0                 
python        3.7.13       
scikit-image    0.15.0              
scipy   1.7.3           
shapely 1.7.0                   
tensorboard   2.8.0            
tensorflow   1.15.0          
tensorflow-estimator 1.15.1            
tensorflow-gpu    1.15.0

**Comment by dalthviz** [comment]
@parthkvv seems like you have `tensorboard 2.8.0` which is not following the rest of your related `tensorflow` packages (which have version 1.15.x)
