### ISSUE TITLE
Spyder cannot save the script to a mapped network drive.

### ISSUE THREAD

**Issue by miklos-zoldi** [spyder-ide/spyder#17799]
### Issue Report Checklist

* [ X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [X ] Restarted Spyder
    * [X ] Reset preferences with ``spyder --reset``
    * [ X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I open a new script in Spyder editor and then go to File -> Save as... to save my file. I can save it onto my local drive normally. However, if I select a mapped network drive a network error occurs.

Spyder can reach the network drive - I can load/save a text file from/to the network drive, the only thing which throws an error if I try to save the script itself via Save as. Interestingly, saving without using the Save as function (i.e., modifying a script loaded into Spyder from the network drive, and then simply running it or saving it via ctrl+s) also works. I often get the very same error message if I just try to drag and drop a script from the network drive to Spyder's editor (unfortunately this does not happen always, so I cannot reproduce, and restarting Spyder usually solves this issue, unlike the Save as issue). 

This issue is very similar to that of https://github.com/spyder-ide/spyder/issues/14660, but the workaround suggested there (downgrading Spyder to the version 4.2.1) does not solve it. The mapped drive is a Geode-Project space (https://kb.iu.edu/d/aoyg). 

### What steps reproduce the problem?

1. Open Spyder
2. Click on File -> New file
3. Click on Save as... and select a mapped network drive

### What is the expected output? What do you see instead?
Saving the script onto the chosen file path. A network error occurs instead. 

### Paste Traceback/Error Below (if applicable)

```python-traceback
Traceback (most recent call last):
  File "C:\Users\mzoldi\Anaconda3\lib\ntpath.py", line 647, in realpath
    path = _getfinalpathname(path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'L:\\mzoldi\\untitled0.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mzoldi\Anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 2305, in save_as
    if editorstack.save_as():
  File "C:\Users\mzoldi\Anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1997, in save_as
    ao_index = self.has_filename(filename)
  File "C:\Users\mzoldi\Anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1501, in has_filename
    if fixpath(filename) == fixpath(finfo.filename):
  File "C:\Users\mzoldi\Anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1499, in <lambda>
    fixpath = lambda path: osp.normcase(osp.realpath(path))
  File "C:\Users\mzoldi\Anaconda3\lib\ntpath.py", line 651, in realpath
    path = _getfinalpathname_nonstrict(path)
  File "C:\Users\mzoldi\Anaconda3\lib\ntpath.py", line 601, in _getfinalpathname_nonstrict
    path = _getfinalpathname(path)
OSError: [WinError 59] An unexpected network error occurred: 'L:\\mzoldi'

```

## Versions

* Spyder version: 5.1.5
* Python version:  3.8.13 64-bit
* Qt version: 5.9.7
* PyQt version: 5.9.2 
* Operating System name/version: Windows 10, version 1909

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.2.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.0 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)

```

**Comment by dalthviz** [comment]
Hi @miklos-zoldi ! I did some tests but I was unable to reproduce this error :/ 

Not totally sure if it could be related to this but the Windows machine where I'm testing has Windows 10 21H1.

From the traceback, seems like this is happening when calling `os.path.realpath(path)` and maybe could be related to the character `\` which escaped becomes `\\`. Could you try to replace in your local installation the line 1499 at `C:\Users\mzoldi\Anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py` from this:

```
fixpath = lambda path: osp.normcase(osp.realpath(path))
```

to this:

```
fixpath = lambda path: osp.normcase(osp.realpath(path.replace('\\', '/')))
```

Let us know if that helps

**Comment by miklos-zoldi** [comment]
Hi @dalthviz , thanks for your help! I replaced the above mentioned line with your suggestions but the error still persists.

**Comment by dalthviz** [comment]
Do you still see have the same traceback @miklos-zoldi ? When changing the line you restarted Spyder, right? Also, is there any possibility for you to test the access to the mapped network drive from a different computer (to check if are able to reproduce this outside of your current setup). Let us know!

**Comment by miklos-zoldi** [comment]
Hi @dalthviz! Yes, I restarted Spyder after changing the line. I also tried saving to the mapped network drive from a different computer and could reproduce this error message. Although on this different computer an older version of Spyder (4.2.5) was installed, but the Qt/PyQt5 versions are the same as on mine.

**Comment by dalthviz** [comment]
Thanks for testing @miklos-zoldi :+1: Thinking aout this maybe we could check if using pathlib improves things here. Could you change again the line for something like this?:

```python
from pathlib import Path
fixpath = lambda path: osp.normcase(Path(path).resolve())
```

**Comment by dalthviz** [comment]
Interesting, @miklos-zoldi do you have permissions to write over that path (`L:\mzoldi`) from the Windows explorer? Also, what happens if you try to change the same line to only use `os.path.normcase`? So something like:

```python
fixpath = lambda path: osp.normcase(path)
```

**Comment by miklos-zoldi** [comment]
Yes, I have permission to write over this path from Windows Explorer. 
Changing the line to the above mentioned one will result in a pop-up window with the title:
Save Error: Unable to save file 'intitled0.py'; Error message: [WinError 6] The handle is invalid: 'L:\\mzoldi'

**Comment by ccordoba12** [comment]
@miklos-zoldi, please post the full error to see where it's coming from.

**Comment by dalthviz** [comment]
Thanks for the info @miklos-zoldi my guess is that we need to improve the error dialog you mention above to catch the error you have and also let users know that they probably need to check the write permitions over the current working directory to be able to save files.

As a workaround, could you change your Spyder's current working directory (you can change it from the toolbar at the top-rigth) to a folder in your mapped drive where you know you have write permissions and use it to save your files? Let us know if that helps!

**Comment by miklos-zoldi** [comment]
Thanks @dalthviz for the suggestions! Now I have permission to every folder on the network drive, but none of it works when saving the script via Spyder's Save as function. If I create a .txt file with some content in Spyder, I can save that .txt file into the very same folder which throws the error message when trying to save the script into that folder. 

Right now the workaround I have is that during the day I work on my hard drive and at the end of the day I just copy all the scripts back to the network drive. (Of course, this is not ideal, lets say I forget to do this, and then I want to remotely access my files on the network via vpn, but there I will not have the latest versions of my scripts).

**Comment by dalthviz** [comment]
Do you use the VPN also to connect to the network drive? And yes that is not quite usable :/ Could you revert the changes done to the `editor.py` please? (to see if the same initial error persists even when you changed the permissions over the mapped network drive folders). I'm not totally sure what else could be causing the problem, sorry. However, I will try to replicate this by mapping a read-only network drive :+1:

**Comment by Baugus** [comment]
Just for the reference, I appear to be having a similar error. I have Spyder 5.3.3 loaded via conda into its own env. I have a mapped drive "S:", which is a [Citrix Sharefile](https://www.sharefile.com/) server connected to my computer via [Citrix Files](https://www.citrix.com/downloads/sharefile/clients-and-plug-ins/citrix-files-for-windows.html). I have full Admin permissions (write, read, edit) for the relevant directories of the mapped drive.

I can open a python script that exists on the mapped drive, I can use the terminal in Spyder to create a .txt file and save it to the mapped drive, but I cannot save a script or use "save as" to save a script to the mapped drive. One distinction between @miklos-zoldi 's error and mine is that I am not able to use ctrl+s to save the file (which if I read correctly, @miklos-zoldi was able to do). 

Have there been further developments on this error? Any workarounds other than saving a shadow copy of the script locally?
![Spyder save issue](https://user-images.githubusercontent.com/44503803/206014614-f3dd9f57-45c6-4a55-9338-3e9031999190.PNG)

![Spyder version](https://user-images.githubusercontent.com/44503803/206014019-f85a0934-82eb-455b-a2be-f3ee414cf7a5.PNG)

**Comment by miklos-zoldi** [comment]
Hi @Baugus, you have the very same issue then! Unfortunately, there was no improvement, I still use this shadow copy workaround, which is not really convenient. 

If I open a script in the terminal, neither Save As..., nor ctrl+s will work for me when trying to save onto the network drive.

What works _sometimes_ is that I drag and drop a script from the network drive to Spyder's terminal, edit it, and save it via ctrl+s. Other times this will throw the very same error message I originally posted, and other times even the drag and drop will result in the error message. I could not figure it out why it works at some cases but not in other cases.
