### ISSUE TITLE
After install Qt5 and LabelImg, my spyder stop working.

### ISSUE THREAD

**Issue by wyw1225** [spyder-ide/spyder#17800]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/vin/opt/anaconda3/envs/spyder3.2.6/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/Users/vin/opt/anaconda3/envs/spyder3.2.6/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 349, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/Users/vin/opt/anaconda3/envs/spyder3.2.6/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 128, in get_cwd
    self.silent_exec_method(code)
  File "/Users/vin/opt/anaconda3/envs/spyder3.2.6/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 349, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.13
* Qt Versions: 5.9.6, PyQt5 5.9.2 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  2.4.0 (OK)
pycodestyle >=2.3:  2.8.0 (OK)
pygments >=2.0   :  2.11.2 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  4.4.0 (OK)
rope >=0.9.4     :  0.22.0 (OK)
jedi >=0.9.0     :  0.17.0 (OK)
psutil >=0.3     :  5.8.0 (OK)
nbconvert >=4.0  :  6.0.7 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  5.2.2 (OK)
IPython >=4.0    :  7.16.1 (OK)
pylint >=0.25    :  2.9.6 (OK)

```

**Comment by ccordoba12** [comment]
Hey @wyw1225, thanks for reporting. I see that you have a dedicated version for Spyder 3.2.6, which is very old and no longer supported by us.

To solve this problem, please use our latest version (5.0.3). Since it's still not available in Anaconda, you have two options:

1. Use our Mac installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder
