### ISSUE TITLE
Spyder 5.3 crashes on MacOS

### ISSUE THREAD

**Issue by drlakecoder** [spyder-ide/spyder#17829]
MacBook Pro 2021 M1 Pro
Spyder 5.3.0
Python 3.9.7 64-bit | Qt 5.12.9 | PyQt5 5.12.3 | Darwin 21.4.0 
Non-native python for M1 chip

## Problem Description
Spyder crashes fairly frequently on MacBook Pro 2021 M1 Pro

/opt/anaconda3/lib/python3.9/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: -version- is an invalid version and will not be supported in a future release
  warnings.warn(
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 461, in _handle_events
    self._rebuild_io_state()
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 516, in _rebuild_io_state
    self._update_handler(state)
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 533, in _update_handler
    if state & self.socket.events:
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/sugar/attrsettr.py", line 51, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/sugar/attrsettr.py", line 63, in _get_attr_opt
    return self.get(opt)
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/_future.py", line 215, in get
    result = super(_AsyncSocket, self).get(key)
  File "zmq/backend/cython/socket.pyx", line 464, in zmq.backend.cython.socket.Socket.get
  File "zmq/backend/cython/socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket
ERROR:tornado.application:Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x7f9fb0a22040>)
Traceback (most recent call last):
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 536, in <lambda>
    self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 461, in _handle_events
    self._rebuild_io_state()
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 516, in _rebuild_io_state
    self._update_handler(state)
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 533, in _update_handler
    if state & self.socket.events:
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/sugar/attrsettr.py", line 51, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/sugar/attrsettr.py", line 63, in _get_attr_opt
    return self.get(opt)
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/_future.py", line 215, in get
    result = super(_AsyncSocket, self).get(key)
  File "zmq/backend/cython/socket.pyx", line 464, in zmq.backend.cython.socket.Socket.get
  File "zmq/backend/cython/socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket
 ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=ZMQError('Socket operation on non-socket')>
Traceback (most recent call last):
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/_future.py", line 425, in _add_send_event
    r = send(msg, **nowait_kwargs)
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/sugar/socket.py", line 595, in send_multipart
    self.send(msg, SNDMORE | flags, copy=copy, track=track)
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/sugar/socket.py", line 547, in send
    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 718, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 765, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 247, in zmq.backend.cython.socket._send_copy
  File "zmq/backend/cython/socket.pyx", line 242, in zmq.backend.cython.socket._send_copy
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Socket operation on non-socket
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 461, in _handle_events
    self._rebuild_io_state()
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 516, in _rebuild_io_state
    self._update_handler(state)
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 533, in _update_handler
    if state & self.socket.events:
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/sugar/attrsettr.py", line 51, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/sugar/attrsettr.py", line 63, in _get_attr_opt
    return self.get(opt)
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/_future.py", line 215, in get
    result = super(_AsyncSocket, self).get(key)
  File "zmq/backend/cython/socket.pyx", line 464, in zmq.backend.cython.socket.Socket.get
  File "zmq/backend/cython/socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket
ERROR:tornado.application:Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x7f9f9883fdc0>)
Traceback (most recent call last):
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 536, in <lambda>
    self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 461, in _handle_events
    self._rebuild_io_state()
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 516, in _rebuild_io_state
    self._update_handler(state)
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 533, in _update_handler
    if state & self.socket.events:
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/sugar/attrsettr.py", line 51, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/sugar/attrsettr.py", line 63, in _get_attr_opt
    return self.get(opt)
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/_future.py", line 215, in get
    result = super(_AsyncSocket, self).get(key)
  File "zmq/backend/cython/socket.pyx", line 464, in zmq.backend.cython.socket.Socket.get
  File "zmq/backend/cython/socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket
ERROR:tornado.application:Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x7f9f9882be50>)
Traceback (most recent call last):
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 536, in <lambda>
    self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 445, in _handle_events
    zmq_events = self.socket.EVENTS
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/sugar/attrsettr.py", line 51, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/sugar/attrsettr.py", line 63, in _get_attr_opt
    return self.get(opt)
  File "/Users/xxxxxxx/opt/anaconda3/lib/python3.9/site-packages/zmq/_future.py", line 215, in get
    result = super(_AsyncSocket, self).get(key)
  File "zmq/backend/cython/socket.pyx", line 464, in zmq.backend.cython.socket.Socket.get
  File "zmq/backend/cython/socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Hi @drlakecoder thank you for the feedback! From the traceback seems like this could be related with #17615 Could you check if downgrading or updating `jupyter_client` as discussed there helps? Let us know

**Comment by drlakecoder** [comment]
Thank you, will try downgrading to 7.2.0 as suggested in the other thread and see if it still keeps crashing. I had 7.2.2 jupyter_client currently

**Comment by dalthviz** [comment]
Closing due to lack of response
