### ISSUE TITLE
环境切换时产生错误，我也不知道如何解决

### ISSUE THREAD

**Issue by eshyee** [spyder-ide/spyder#17845]
### What steps will reproduce the problem?

我的环境安装了kernel 2.3.0，但是软件提示没有kernel
啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊

### Traceback
```python-traceback
ERROR:root:Exception in callback AddThreadSelectorEventLoop._handle_select([7280], [])
handle: <Handle AddThreadSelectorEventLoop._handle_select([7280], [])>
Traceback (most recent call last):
  File "asyncio\events.py", line 81, in _run
  File "D:\Spyder\pkgs\tornado\platform\asyncio.py", line 579, in _handle_select
    self._handle_event(r, self._readers)
  File "D:\Spyder\pkgs\tornado\platform\asyncio.py", line 591, in _handle_event
    callback()
  File "D:\Spyder\pkgs\tornado\platform\asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "D:\Spyder\pkgs\zmq\eventloop\zmqstream.py", line 445, in _handle_events
    zmq_events = self.socket.EVENTS
  File "D:\Spyder\pkgs\zmq\sugar\attrsettr.py", line 51, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "D:\Spyder\pkgs\zmq\sugar\attrsettr.py", line 63, in _get_attr_opt
    return self.get(opt)
  File "D:\Spyder\pkgs\zmq\_future.py", line 215, in get
    result = super(_AsyncSocket, self).get(key)
  File "zmq\backend\cython\socket.pyx", line 464, in zmq.backend.cython.socket.Socket.get
  File "zmq\backend\cython\socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: not a socket
```

## Versions

* Spyder version: 5.3.0 
* Python version: 3.8.10
* Qt version: 5.15.2
* PyQt5 version: 5.15.6
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.0.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<8.0.0              :  7.32.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.4.0 (OK)
keyring >=17.0.0                     :  23.5.0 (OK)
nbconvert >=4.0                      :  6.4.5 (OK)
numpydoc >=0.6.0                     :  1.2.1 (OK)
paramiko >=2.4.0                     :  2.10.3 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.0 (OK)
pygments >=2.0                       :  2.11.2 (OK)
pylint >=2.5.0                       :  2.13.3 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0                 :  1.4.1 (OK)
pylsp_black >=1.2.0                  :  1.2.0 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0             :  5.3.0 (OK)
qtpy >=2.0.1                         :  2.0.1 (OK)
rtree >=0.9.7                        :  0.9.7 (OK)
setuptools >=49.6.0                  :  61.2.0 (OK)
sphinx >=0.6.6                       :  4.5.0 (OK)
spyder_kernels >=2.3.0;<2.4.0        :  2.3.0 (OK)
textdistance >=4.2.0                 :  4.2.2 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.1.7 (OK)
zmq >=17                             :  22.3.0 (OK)

# Optional:
cython >=0.21                        :  0.29.28 (OK)
matplotlib >=3.0.0                   :  3.5.1 (OK)
numpy >=1.7                          :  1.22.3 (OK)
pandas >=1.1.1                       :  1.4.1 (OK)
scipy >=0.17.0                       :  1.8.0 (OK)
sympy >=0.7.3                        :  1.10.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by dalthviz** [comment]
Hi @eshyee thank your for the feedback! This seems like a duplicate of #17615 and will be fixed in our next release (Spyder 5.3.1) to be released soon.

Let us know if the info above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response

**Comment by eshyee** [comment]
thank you for your reply！
my device is not so good，I used to install the conda，but it usually hard to download plugins ，so I installed spyder with standalone installer
I am looking forward to your new release for Python310！



---原始邮件---
发件人: "Daniel Althviz ***@***.***&gt;
发送时间: 2022年5月10日(周二) 凌晨1:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [spyder-ide/spyder] 环境切换时产生错误，我也不知道如何解决 (Issue #17845)




 
Also, checking what you commented with a translator and since seems like you are using our Windos standalone installer maybe this could be useful: https://docs.spyder-ide.org/current/faq.html#using-packages-installer
