### ISSUE TITLE
Ocurrió un error mientras iniciaba el núcleo

### ISSUE THREAD

**Issue by Faremar** [spyder-ide/spyder#17885]
### What steps will reproduce the problem?

C:\Users\CARLOS\AppData\Local\Programs\Spyder\pkgs\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\CARLOS\AppData\Local\Programs\Spyder\pkgs\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran‑win_amd64.dll
C:\Users\CARLOS\AppData\Local\Programs\Spyder\pkgs\numpy\.libs\libopenblas.QVLO2T66WEPI7JZ63PS3HMOHFEY472BC.gfortran‑win_amd64.dll
warnings.warn("loaded more than 1 DLL from .libs:"

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\CARLOS\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\editor\plugin.py", line 2813, in stop_debugging
    ipyconsole.stop_debugging()
  File "C:\Users\CARLOS\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\plugin.py", line 712, in stop_debugging
    self.get_widget().stop_debugging()
  File "C:\Users\CARLOS\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 2193, in stop_debugging
    sw.stop_debugging()
  File "C:\Users\CARLOS\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\debugging.py", line 373, in stop_debugging
    self.interrupt_kernel()
  File "C:\Users\CARLOS\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\shell.py", line 259, in interrupt_kernel
    super(ShellWidget, self).interrupt_kernel()
  File "C:\Users\CARLOS\AppData\Local\Programs\Spyder\pkgs\qtconsole\frontend_widget.py", line 639, in interrupt_kernel
    self.kernel_manager.interrupt_kernel()
  File "C:\Users\CARLOS\AppData\Local\Programs\Spyder\pkgs\jupyter_client\utils.py", line 26, in wrapped
    raise e
  File "C:\Users\CARLOS\AppData\Local\Programs\Spyder\pkgs\jupyter_client\utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "C:\Users\CARLOS\AppData\Local\Programs\Spyder\pkgs\nest_asyncio.py", line 81, in run_until_complete
    return f.result()
  File "asyncio\futures.py", line 178, in result
  File "asyncio\tasks.py", line 280, in __step
  File "C:\Users\CARLOS\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 589, in _async_interrupt_kernel
    raise RuntimeError("Cannot interrupt kernel. No kernel is running!")
RuntimeError: Cannot interrupt kernel. No kernel is running!
```

## Versions

* Spyder version: 5.3.0 
* Python version: 3.8.10
* Qt version: 5.15.2
* PyQt5 version: 5.15.6
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.0.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<8.0.0              :  7.32.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.4.0 (OK)
keyring >=17.0.0                     :  23.5.0 (OK)
nbconvert >=4.0                      :  6.4.5 (OK)
numpydoc >=0.6.0                     :  1.2.1 (OK)
paramiko >=2.4.0                     :  2.10.3 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.0 (OK)
pygments >=2.0                       :  2.11.2 (OK)
pylint >=2.5.0                       :  2.13.3 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0                 :  1.4.1 (OK)
pylsp_black >=1.2.0                  :  1.2.0 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0             :  5.3.0 (OK)
qtpy >=2.0.1                         :  2.0.1 (OK)
rtree >=0.9.7                        :  0.9.7 (OK)
setuptools >=49.6.0                  :  61.2.0 (OK)
sphinx >=0.6.6                       :  4.5.0 (OK)
spyder_kernels >=2.3.0;<2.4.0        :  2.3.0 (OK)
textdistance >=4.2.0                 :  4.2.2 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.1.7 (OK)
zmq >=17                             :  22.3.0 (OK)

# Optional:
cython >=0.21                        :  0.29.28 (OK)
matplotlib >=3.0.0                   :  3.5.1 (OK)
numpy >=1.7                          :  1.22.3 (OK)
pandas >=1.1.1                       :  1.4.1 (OK)
scipy >=0.17.0                       :  1.8.0 (OK)
sympy >=0.7.3                        :  1.10.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Hola @Faremar, gracias por reportar este error. Por favor desinstala Spyder, elimina este directorio

    C:\Users\CARLOS\AppData\Local\Programs\Spyder

si es que todavía aparece en tu computador y vuelve a instalarlo. Eso debería solucionar tu problema.
