### ISSUE TITLE
ImportError when trying to display QMessageBox about corrupted configuration files

### ISSUE THREAD

**Issue by abaillet** [spyder-ide/spyder#17889]
An error ocurred while starting the kernel
The error is:

Traceback (most recent call last):
File "C:\Anaconda\lib\site‑packages\spyder\plugins\ipythonconsole\plugin.py", line 1568, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle,
File "C:\Anaconda\lib\site‑packages\jupyter_client\manager.py", line 341, in start_kernel
self.kernel = self._launch_kernel(kernel_cmd, **kw)
File "C:\Anaconda\lib\site‑packages\jupyter_client\manager.py", line 249, in _launch_kernel
return launch_kernel(kernel_cmd, **kw)
File "C:\Anaconda\lib\site‑packages\jupyter_client\launcher.py", line 132, in launch_kernel
proc = Popen(cmd, **kwargs)
File "C:\Anaconda\lib\subprocess.py", line 951, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "C:\Anaconda\lib\subprocess.py", line 1420, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
ValueError: embedded null character

**Comment by abaillet** [comment]
How may I fix this?

**Comment by abaillet** [comment]
Dear @ccordoba12 I tried running the commands you suggested, but this error occured when I tried to run the final command:


(spyder-cf) C:\Users\Alvaro Baillet Boliv>spyder
Traceback (most recent call last):
  File "C:\Anaconda\envs\spyder-cf\lib\site-packages\spyder\config\manager.py", line 642, in <module>
    CONF = ConfigurationManager()
  File "C:\Anaconda\envs\spyder-cf\lib\site-packages\spyder\config\manager.py", line 73, in __init__
    self._user_config = MultiUserConfig(
  File "C:\Anaconda\envs\spyder-cf\lib\site-packages\spyder\config\user.py", line 786, in __init__
    self._configs_map[name] = config_class(**new_kwargs)
  File "C:\Anaconda\envs\spyder-cf\lib\site-packages\spyder\config\user.py", line 226, in __init__
    self.apply_configuration_patches(old_version=old_version)
  File "C:\Anaconda\envs\spyder-cf\lib\site-packages\spyder\config\user.py", line 725, in apply_configuration_patches
    self._update_defaults(self.defaults, old_version)
  File "C:\Anaconda\envs\spyder-cf\lib\site-packages\spyder\config\user.py", line 355, in _update_defaults
    old_defaults = self._load_old_defaults(old_version)
  File "C:\Anaconda\envs\spyder-cf\lib\site-packages\spyder\config\user.py", line 342, in _load_old_defaults
    old_defaults.read(osp.join(path, name + '.ini'))
  File "C:\Anaconda\envs\spyder-cf\lib\configparser.py", line 698, in read
    self._read(fp, filename)
  File "C:\Anaconda\envs\spyder-cf\lib\configparser.py", line 1086, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'C:\\Users\\Alvaro Baillet Boliv\\.spyder-py3\\config\\defaults\\defaults-transient-70.1.0.ini', line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda\envs\spyder-cf\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Anaconda\envs\spyder-cf\lib\site-packages\spyder\app\start.py", line 113, in main
    from spyder.config.manager import CONF
  File "C:\Anaconda\envs\spyder-cf\lib\site-packages\spyder\config\manager.py", line 645, in <module>
    from spyder.app.utils import create_application
  File "C:\Anaconda\envs\spyder-cf\lib\site-packages\spyder\app\utils.py", line 28, in <module>
    from spyder.config.manager import CONF
ImportError: cannot import name 'CONF' from partially initialized module 'spyder.config.manager' (most likely due to a circular import) (C:\Anaconda\envs\spyder-cf\lib\site-packages\spyder\config\manager.py)


Please advise, 

Álvaro

**Comment by ccordoba12** [comment]
Please remove this directory

    C:\Users\Alvaro Baillet Boliv\.spyder-py3

and try again. That should solve your problem.

**Comment by abaillet** [comment]
Dear @ccordoba12 , 

Thank you so much, everything is in order now.

**Comment by ccordoba12** [comment]
@abaillet, thanks for letting us know about it.

I'll reopen this issue so that we can provide a better solution for your problem in the future.
