### ISSUE TITLE
Getting warning "WARNING: Unexpected error discovering local network interfaces: 'SysOutput' object has no attribute 'flush"

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1789]
_From [satishsh...@gmail.com](https://code.google.com/u/100770835801554797979/) on 2014-04-11T17:10:51Z_

Spyder Version:  2.3.0beta4
Python Version:  2.7.6
Qt Version    :  4.8.5, PyQt4 (API v2) 4.10.3 on Linux
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.5 (OK)
IPython >=0.13  :  2.0.0 (OK)
pygments >=1.6  :  1.6 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  2.1.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  1.1.0 (OK) 

What steps will reproduce the problem?

 When I launch spyder I get following, It was working before after I did some updates
 -
user@somemachine:~ >-->   spyder
Unable to load library icui18n "Cannot load library icui18n: (icui18n: cannot open shared object file: No such file or directory)" 
WARNING: Unexpected error discovering local network interfaces: 'SysOutput' object has no attribute 'flush'

1. The message "Unable to load library icui18n "Cannot load library icui18n: (icui18n: cannot open shared object file: No such file or directory)" can be ignored as it is outside the scope of spyder, that error is coming from Qt because I am using spyder on RHEL6 while the tools (Qt) were compiled on RHEL 5.5
2. "WARNING: Unexpected error discovering local network interfaces: 'SysOutput' object has no attribute 'flush"  This is new warning, that started to popup after I updated the dependencies and spyder, I thought it was coming from psutil package but it doesn't seem so. What is the expected output? What do you see instead? There should no warning 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1789_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-04-16T09:11:13Z_

I'm seeing it myself. I think this warning is generated by IPython but I'll have to investigate it further.

**Status:** Accepted  
  **Labels:** Cat-IPythonConsole MS-v2.3.1

**Comment by spyder-issues-migrator** [comment]
_From [ostrok...@gmail.com](https://code.google.com/u/115488699546891761023/) on 2014-06-09T14:31:50Z_

I'm seeing this too...

Spyder Version:  2.3.0rc
Python Version:  2.7.7
IPython >=0.13  :  2.1.0 (OK)
matplotlib >=1.0:  1.3.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
psutil >=0.3    :  2.1.1 (OK)
pyflakes >=0.5.0:  0.8.1 (OK)
pygments >=1.6  :  1.6 (OK)
pylint >=0.25   :  1.1.0 (OK)
rope >=0.9.2    :  0.10.2 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
sympy >=0.7.0   :  0.7.5 (OK)

Thanks for your help.

**Comment by spyder-issues-migrator** [comment]
_From [Shaoxi...@gmail.com](https://code.google.com/u/118288252447746457551/) on 2014-06-20T18:08:54Z_

I just installed Spyder on a new Macbook. When Launch spyder, I got the same warming information. "Unexpected error discovering local network interfaces: 'SysOutput' object has no attribute 'flush'".

what is the problem.

**Comment by spyder-issues-migrator** [comment]
_From [dmilo...@gmail.com](https://code.google.com/u/108237761319924720846/) on 2014-07-04T00:47:17Z_

same here : OSX 10.8
WARNING: Unexpected error discovering local network interfaces: 'SysOutput' object has no attribute 'flush'

**Comment by spyder-issues-migrator** [comment]
_From [dcsro...@gmail.com](https://code.google.com/u/109750631524060351227/) on 2014-07-05T15:43:04Z_

I get the same error with newly installed Spyder on MacBook Pro, OSX 10.9.3,
Python 3.4.1 |Anaconda 2.0.1 (x86_64)| (default, May 19 2014, 13:05:46) 

I always get the following errors when exiting python (Quit Python), even though I don't load or run a file.

1050-XXXXX:~ someuser$ spyder
WARNING: Unexpected error discovering local network interfaces: 'SysOutput' object has no attribute 'flush'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/someuser/anaconda/python.app/Contents/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/Users/someuser/anaconda/python.app/Contents/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/someuser/anaconda/python.app/Contents/lib/python3.4/site-packages/spyderlib/spyder.py", line 2097, in start_open_files_server
    req, dummy = self.open_files_server.accept()
  File "/Users/someuser/anaconda/python.app/Contents/lib/python3.4/socket.py", line 184, in accept
    fd, addr = self._accept()
ConnectionAbortedError: [Errno 53] Software caused connection abort

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-07-06T06:18:54Z_

@-dcsrobts: your second error is not related to the first one. I don't know where it can be coming from.

**Comment by spyder-issues-migrator** [comment]
_From [JordanDo...@gmail.com](https://code.google.com/u/102056157755029758599/) on 2014-07-20T03:55:30Z_

OSX 10.9.4 with the same issue. Happens with both of my environments.
Python 3.4.1 |Anaconda 2.0.1 (x86_64) | IPython 2.1.0
Python 2.7.7 |Anaconda 2.0.1 (x86_64) | IPython 2.1.0

**Comment by spyder-issues-migrator** [comment]
_From [Christop...@gmail.com](https://code.google.com/u/110477898959875543543/) on 2014-08-12T16:25:52Z_

osx 10.9.4  I have the same issue. 
Python 2.7.7 |Anaconda 2.0.1| IPython 2.1.0

**Comment by spyder-issues-migrator** [comment]
_From [eric.del...@aequamcapital.com](https://code.google.com/u/108914500516866989858/) on 2014-08-15T02:39:28Z_

so do i... installed from debian::apt with package spyder3
python 3.4.1 / debian testing

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-17T18:35:50Z_

**Labels:** -MS-v2.3.1 MS-v2.4

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-09-10T13:30:08Z_

I found the error. I'll fix it for 2.3.2

**Labels:** -MS-v2.4 MS-v2.3.2

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-09-19T06:28:22Z_

issue #1971 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-09-19T11:28:05Z_

This issue was closed by revision 7f89d0a8f424 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [Christop...@gmail.com](https://code.google.com/u/110477898959875543543/) on 2014-09-19T11:59:09Z_

what is the fix for this problem

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-09-19T12:08:20Z_

We needed to add a "dummy" flush method to one of our classes.

Click on the revision link above to see the details.
