### ISSUE TITLE
DuplicateOptionError when reading workspace.ini project file

### ISSUE THREAD

**Issue by Gcxchunxia** [spyder-ide/spyder#17907]
### What steps will reproduce the problem?

spyder can not open!!!!!!!spyder can not open!!!!!!!spyder can not open!!!!!!!

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\projects\plugin.py", line 379, in create_new_project
    self._create_project(root_path, project_type_id=project_type)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\projects\plugin.py", line 388, in _create_project
    project = project_type_class(
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\projects\api.py", line 47, in __init__
    self.config = ProjectMultiConfig(
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 786, in __init__
    self._configs_map[name] = config_class(**new_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 212, in __init__
    self._load_from_ini(previous_fpath)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 333, in _load_from_ini
    self.read(fpath, encoding='utf-8')
  File "C:\ProgramData\Anaconda3\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "C:\ProgramData\Anaconda3\lib\configparser.py", line 1096, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from 'D:\\SVN\\2022_NR L1 vRan\\2022_vRAN_L1_Analysis_Tool_Dev\\1.0 Engineering\\3.0 实现\\DevBranch\\NrL1LogAnalyzeTool\\.spyproject\\config\\workspace.ini' [line 10]: option 'recent_files' in section 'workspace' already exists
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.7
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment]
Hey @Gcxchunxia, thanks for reporting. Please remove this file for Spyder to work again:

    D:\\SVN\\2022_NR L1 vRan\\2022_vRAN_L1_Analysis_Tool_Dev\\1.0 Engineering\\3.0 实现\\DevBranch\\NrL1LogAnalyzeTool\\.spyproject\\config\\workspace.ini

We'll make Spyder not to crash for errors like this in a future release.
