### ISSUE TITLE
Mac OS 10.9.2 (Mavericks) installing Spyder from source: Can't start/launch Spyder

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1791]
_From [mike.bie...@gmail.com](https://code.google.com/u/100786552104454369680/) on 2014-04-13T04:26:19Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. Install python, python3, Qt4, Qt5, PyQt4, PyQt5 and all other dependencies using brew/homebrew
2. Download spyder source zip archive (there is NO brew formula)
3. install spyder as per documentation
4. Added
   export LANG=en_US.UTF-8
   export LC_ALL=en_US.UTF-8
to my bash profile to get rid of a nasty "UTF-8 unknown" error
5. start spyder What is the expected output? What do you see instead? I expected a GUI
I get the following warning/error:

  File "/usr/local/lib/python2.7/site-packages/spyderlib/requirements.py", line 24, in show_warning
    raise RuntimeError(message)
RuntimeError: Please check Spyder installation requirements:
PyQt4 4.4+ (or PySide 1.1.1+) is required. What version of the product are you using? On what operating system? Spyder 2.2.5
Mac OS 10.9.2 

Please provide any additional information below

. I have PyQt4 and PyQt5 installed (per homebrew). I noticed Spyder uses Python2, I usually use Python3. So I copied and edited the file /usr/local/bin/spyder to point to Python3:

\#!/usr/local/opt/python3/bin/python3.4
from spyderlib import start_app
start_app.main()

Didn't help, then I get this error:

rerun:bin mike$ pwd
/usr/local/bin
rerun:bin mike$ spyder
Traceback (most recent call last):
  File "/usr/local/bin/spyder", line 2, in \<module>
    from spyderlib import start_app
  File "/usr/local/lib/python3.4/site-packages/spyderlib/start_app.py", line 12, in \<module>
    from spyderlib.baseconfig import get_conf_path
  File "/usr/local/lib/python3.4/site-packages/spyderlib/baseconfig.py", line 184
    except IOError, _e:  # analysis:ignore
                  ^
SyntaxError: invalid syntax
rerun:bin mike$

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1791_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-04-16T08:52:02Z_

Spyder 2.2.5 is not compatible with Python 3. What happens if you use as shebang

\#!/usr/local/opt/python2/bin/python2.7

or the right path to your Python 2 interpreter?

**Comment by spyder-issues-migrator** [comment]
_From [mike.bie...@gmail.com](https://code.google.com/u/100786552104454369680/) on 2014-04-16T23:48:05Z_

Hi
thanks for your help. Obviously, I was not clear (on the web site), my fault. Before trying to point spyder to Python 3, I did try with Python 2 and got the error about missing requirements:

please see screen shot

As I wrote, I have both PyQt4 and PyQt5 installed via brew:

please see screen shot

which is why I don't understand the error message. It might be that spyder does not find PyQt4, but it sure is installed... any other ideas?

Thanks
Mike

**Attachment:** [Screen Shot 2014-04-16 at 20.30.07.png Screen Shot 2014-04-16 at 20.41.34.png](http://code.google.com/p/spyderlib/issues/detail?id=1791#hc2)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-04-17T06:18:54Z_

Are you sure you are installing/starting Spyder with your Homebrew Python version instead of the System one?

What is the output of

which python

in a terminal?

**Labels:** OpSys-OSX Cat-Miscelleneous

**Comment by spyder-issues-migrator** [comment]
_From [mike.bie...@gmail.com](https://code.google.com/u/100786552104454369680/) on 2014-04-17T07:33:47Z_

the output is /usr/local/bin/python
which is the homebrew one (at least that's the way I've set it up)

**Comment by spyder-issues-migrator** [comment]
_From [ebori...@gmail.com](https://code.google.com/u/102672023975932251472/) on 2014-04-19T19:57:14Z_

FWIW, the MacPorts install works on Mavericks.

**Comment by spyder-issues-migrator** [comment]
_From [mike.bie...@gmail.com](https://code.google.com/u/100786552104454369680/) on 2014-04-19T23:24:27Z_

I'm aware of MacPorts, and there are reasons I (and others) are not using it. As I wrote above, I'm using homebrew... and I'll stay with that.
I'm trying to get to the root of the cause to help others as well as myself. If all else fails, I can always use a "all-in-one" Python installation (like e.g. Anaconda) but I'd like to even avoid that...

**Comment by spyder-issues-migrator** [comment]
_From [ebori...@gmail.com](https://code.google.com/u/102672023975932251472/) on 2014-04-20T09:07:44Z_

Not trying to hijack the thread, but if you're willing to share your reasons for not using MP, I'd be interested to hear -- we're always looking for ways to improve it. Feel free to shoot me an e-mail. (eborisch)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-12T17:27:44Z_

I hope you find how to fix this one. I also use Spyder through homebrew and it works just fine.

**Status:** WontFix
