### ISSUE TITLE
macOS standalone application fails to restart

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#17947]
### What steps will reproduce the problem?

A recent macOS installer artifact (d06d05fa) fails to restart from the menubar.

The following traceback indicates indicates the issue.

```python
Traceback (most recent call last):
  File "/Users/rclary/Documents/Repos/Spyder-IDE/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.10/spyder/app/start.py", line 254, in <module>
    main()
  File "/Users/rclary/Documents/Repos/Spyder-IDE/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.10/spyder/app/start.py", line 250, in main
    mainwindow.main(options, args)
  File "/Users/rclary/Documents/Repos/Spyder-IDE/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.10/spyder/app/mainwindow.py", line 2025, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "/Users/rclary/Documents/Repos/Spyder-IDE/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.10/spyder/app/utils.py", line 289, in create_window
    main.setup()
  File "/Users/rclary/Documents/Repos/Spyder-IDE/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.10/spyder/app/mainwindow.py", line 923, in setup
    mainmenu = self.mainmenu
  File "/Users/rclary/Documents/Repos/Spyder-IDE/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.10/spyder/app/mainwindow.py", line 1069, in __getattr__
    return super().__getattr__(attr)
AttributeError: 'MainWindow' object has no attribute 'mainmenu'
```

The issue occurs at startup of the new instance. Since this is a subprocess (start) started from a subprocess (restart) started from the original Spyder application process, the issue is not reported to the debug file nor is the issue reporter dialog launched. Rather just the system crash reporter dialogue window appears.

To get the traceback do the following:
```
>> PYTHONHOME=$HOME/Documents/Repos/Spyder-IDE/spyder/installers/macOS/dist/Spyder.app/Contents/Resources SPYDER_ARGS=[] SPYDER_PID=12345 SPYDER_IS_BOOTSTRAP=False $HOME/Documents/Repos/Spyder-IDE/spyder/installers/macOS/dist/Spyder.app/Contents/MacOS/python $HOME/Documents/Repos/Spyder-IDE/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.10/spyder/app/restart.py
```

## Versions

* Spyder version: 5.4.0.dev0 
* Python version: 3.9.5
* Qt version: 5.15.2
* PyQt5 version: 5.15.6
* Operating System: Darwin 20.6.0

### Dependencies

```
# Mandatory:
applaunchservices >=0.1.7            :  0.3.0 (OK)
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.0.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0              :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.5.1 (OK)
keyring >=17.0.0                     :  23.5.0 (OK)
nbconvert >=4.0                      :  6.5.0 (OK)
numpydoc >=0.6.0                     :  1.3.1 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.0 (OK)
pygments >=2.0                       :  2.12.0 (OK)
pylint >=2.5.0                       :  2.13.8 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0                 :  1.4.1 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0             :  5.4.0.dev0 (OK)
qtpy >=2.1.0                         :  2.1.0 (OK)
rtree >=0.9.7                        :  1.0.0 (OK)
setuptools >=49.6.0                  :  62.2.0 (OK)
sphinx >=0.6.6                       :  4.5.0 (OK)
spyder_kernels >=2.3.0;<2.4.0        :  2.4.0.dev0 (OK)
textdistance >=4.2.0                 :  4.2.2 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.7 (OK)
zmq >=17                             :  22.3.0 (OK)

# Optional:
cython >=0.21                        :  None (NOK)
matplotlib >=3.0.0                   :  None (NOK)
numpy >=1.7                          :  None (NOK)
pandas >=1.1.1                       :  None (NOK)
scipy >=0.17.0                       :  None (NOK)
sympy >=0.7.3                        :  None (NOK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by mrclary** [comment]
I was mistaken. This is not an issue.
