### ISSUE TITLE
"internal problem!!" pop-up cannot be closed

### ISSUE THREAD

**Issue by texadactyl** [spyder-ide/spyder#17974]
### What steps will reproduce the problem?

After a Spyder crash, the "internal problem!!" pop-up cannot be closed.  Clicking on "Close", results in the same pop-up i.e. endless loop.  No, I do not want to report the crash as I need to do something else.

Work-around: kill -9 from a terminal window.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/elkins/.local/lib/python3.10/site-packages/spyder/app/mainwindow.py", line 1318, in plugin_focus_changed
    self.update_search_menu()
  File "/home/elkins/.local/lib/python3.10/site-packages/spyder/app/mainwindow.py", line 1445, in update_search_menu
    self.search_menu_actions[3].setEnabled(readwrite_editor)
RuntimeError: wrapped C/C++ object of type SpyderAction has been deleted
Traceback (most recent call last):
  File "/home/elkins/.local/lib/python3.10/site-packages/spyder/app/mainwindow.py", line 1318, in plugin_focus_changed
    self.update_search_menu()
  File "/home/elkins/.local/lib/python3.10/site-packages/spyder/app/mainwindow.py", line 1445, in update_search_menu
    self.search_menu_actions[3].setEnabled(readwrite_editor)
RuntimeError: wrapped C/C++ object of type SpyderAction has been deleted
```

## Versions

* Spyder version: 5.3.0 
* Python version: 3.10.4
* Qt version: 5.15.2
* PyQt5 version: 5.15.6
* Operating System: Linux 5.15.0-30-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.5.1 (OK)
keyring >=17.0.0              :  23.5.0 (OK)
nbconvert >=4.0               :  6.5.0 (OK)
numpydoc >=0.6.0              :  1.3.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.12.0 (OK)
pylint >=2.5.0                :  2.13.8 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.0 (OK)
qtpy >=2.0.1                  :  2.1.0 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  62.3.1 (OK)
sphinx >=0.6.6                :  4.5.0 (OK)
spyder_kernels >=2.3.0;<2.4.0 :  2.3.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.7 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=3.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.22.3 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.8.0 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @texadactyl, thanks for reporting. This will be fixed in our next version (5.3.1), which I plan to release in a couple of hours.
