### ISSUE TITLE
IPython console: AttributeError: 'module' object has no attribute 'argv'

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1799]
_From [kamil.paral](https://code.google.com/u/kamil.paral/) on 2014-04-23T08:42:23Z_

Spyder Version:  2.2.4
Python Version:  2.7.5
Qt Version    :  4.8.5, PyQt4 (API v2) 4.10.2 on Linux
pyflakes >=0.5.0:  0.7.3 (OK)
pep8 >=0.6      :  1.5.4 (OK)
IPython >=0.13  :  0.13.2 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.1.3 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  None (NOK)
pylint >=0.25   :  1.1.0 (OK) 

What steps will reproduce the problem?

 1. Go to Preferences -> Console -> External modules and uncheck Matplotlib GUI backend
2. Restart Spyder
3. Try to start an IPython console What is the expected output? What do you see instead? IPython console fails to start with error:
" 'import sitecustomize' failed; use -v for traceback "

After debugging, the traceback is:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site.py", line 502, in execsitecustomize
    import sitecustomize
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 171, in \<module>
    from spyderlib.widgets.externalshell.monitor import Monitor
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/externalshell/monitor.py", line 23, in \<module>
    from spyderlib.utils.module_completion import module_completion
  File "/usr/lib/python2.7/site-packages/spyderlib/utils/module_completion.py", line 30, in \<module>
    from spyderlib.baseconfig import get_conf_path
  File "/usr/lib/python2.7/site-packages/spyderlib/baseconfig.py", line 37, in \<module>
    if programs.is_module_installed('IPython', '>=1.0'):
  File "/usr/lib/python2.7/site-packages/spyderlib/utils/programs.py", line 266, in is_module_installed
    actver = get_module_version(module_name)
  File "/usr/lib/python2.7/site-packages/spyderlib/utils/programs.py", line 212, in get_module_version
    mod = __import__(module_name)
  File "/usr/lib/python2.7/site-packages/IPython/__init__.py", line 43, in \<module>
    from .config.loader import Config
  File "/usr/lib/python2.7/site-packages/IPython/config/__init__.py", line 16, in \<module>
    from .application import *
  File "/usr/lib/python2.7/site-packages/IPython/config/application.py", line 67, in \<module>
    """.strip().format(app=os.path.basename(sys.argv[0]))
AttributeError: 'module' object has no attribute 'argv'

When I put the checkbox back, everything is OK. What version of the product are you using? On what operating system? Fedora 20 

Please provide any additional information below

. issue #771 apparently wasn't fixed.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1799_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-15T09:25:34Z_

This was fixed a long time ago by the IPython guys.

**Status:** WontFix
