### ISSUE TITLE
Erros when pressing Tab key in the Editor

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1812]
_From [CTPaHHuK...@gmail.com](https://code.google.com/u/117366882786517374314/) on 2014-05-06T04:20:08Z_

Spyder 2.3.0dev(6 may 2014)
Python 2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit (AMD64)]
IPython 2.0.0
Windows7

1) Error1: 

What steps will reproduce the problem?

 1. New file
2. Print: #
3. Press key 'Tab' 

What is the expected output? What do you see instead?

 Don't TabSPace

2) Error2:
1. Create file 3 line:
\#@@ -6,6 +6,7
\#
\#@@ -1532,70
2. Go in end 2 line
3. Press key 'Tab'

Error:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\widgets\editor.py", line 378, in trigger_token_completion
    self.trigger_code_completion(automatic, token_based=True)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\editor.py", line 369, in trigger_code_completion
    completion_text = re.findall(r"[\w.]+", text, re.UNICODE)[-1]
IndexError: list index out of range

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1812_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-06T06:45:31Z_

* I don't understand your Error 1. Where are you pressing Tab, before '#' or after it?

* Error 2 is certainly a bug.

Steven, can you take a look at it given that it's generated by token completion?

**Summary:** Erros when pressing Tab key in the Editor  \<span class="oldvalue"> (was: Tab in editor) \</span>  
  **Status:** Accepted  
  **Cc:** steven.s...@gmail.com  
  **Labels:** Cat-Editor MS-v2.3.1

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-06T06:47:46Z_

About Error 1: I see, if there's a space after '#' then Tab insert spaces. That's the expected behavior, so there's no Error to fix there.

**Comment by spyder-issues-migrator** [comment]
_From [steven.s...@gmail.com](https://code.google.com/u/118403364018775626054/) on 2014-05-06T16:41:26Z_

I can submit a patch this weekend, but it should be as simple as adding a check for the result if the find all before indexing it.

**Comment by spyder-issues-migrator** [comment]
_From [CTPaHHuK...@gmail.com](https://code.google.com/u/117366882786517374314/) on 2014-05-07T00:22:03Z_

\> I don't understand your Error 1. Where are you pressing Tab, before '#' or after it?

Empty file
Press #
After press Tab
Result: after # - nothing

If after #, press Space and press Tab - all Ok.

**Comment by spyder-issues-migrator** [comment]
_From [steven.s...@gmail.com](https://code.google.com/u/118403364018775626054/) on 2014-05-25T09:20:51Z_

I'm not sure how to handle Error `#2`, but this fixes error `#1`.

diff -r 96ff231ec293 spyderlib/widgets/editor.py
--- a/spyderlib/widgets/editor.py	Sat May 24 10:35:24 2014 -0500
+++ b/spyderlib/widgets/editor.py	Sun May 25 11:20:20 2014 -0500
@@ -366,7 +366,11 @@
                 func = self.introspection_plugin.get_completion_list
             comp_list = func(source_code, offset, self.filename)
             if comp_list:
-                completion_text = re.findall(r"[\w.]+", text, re.UNICODE)[-1]
+                completion_text = re.findall(r"[\w.]+", text, re.UNICODE)
+                if completion_text:
+                    completion_text = completion_text[-1]
+                else:
+                    comp_list = []
                 if '.' in completion_text:
                     completion_text = completion_text.split('.')[-1]
         if comp_list:

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-17T18:52:50Z_

**Labels:** -MS-v2.3.1 MS-v2.3.2

**Comment by spyder-issues-migrator** [comment]
_From [steven.s...@gmail.com](https://code.google.com/u/118403364018775626054/) on 2014-08-17T19:36:38Z_

See https://bitbucket.org/blink1073/spyderlib/pull-request/4/fix-issue-1812-errors-when-pressing-tab/diff for a fix for both issues.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-09-19T11:46:20Z_

This issue was closed by revision cf2ed4c20e5d .

**Status:** Fixed
