### ISSUE TITLE
IPython kernel fails to start with external Python 3.7.12 conda environment in Windows standalone application

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#18139]
### What steps will reproduce the problem?

For the Windows standalone application, the IPython console fails to launch when using external conda environments with Python 3.7.

This does not manifest with Python 3.10 conda environments, nor does it manifest when Spyder is launched from bootstrap (latest 5.x)

1. create a conda environment
```
$ conda create -n test -c conda-forge python=3.7 spyder-kernels=2.3.1
```
2. Restart IPython console kernel with new environment

<details><summary>An error ocurred while starting the kernel</summary>

```
An error ocurred while starting the kernel
Traceback (most recent call last):
File "C:\Users\rclary\Miniconda3\envs\test0\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\rclary\Miniconda3\envs\test0\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\rclary\Miniconda3\envs\test0\lib\site‑packages\spyder_kernels\console\__main__.py", line 22, in
from spyder_kernels.console import start
File "C:\Users\rclary\Miniconda3\envs\test0\lib\site‑packages\spyder_kernels\console\start.py", line 21, in
import ipykernel
File "C:\Users\rclary\Miniconda3\envs\test0\lib\site‑packages\ipykernel\__init__.py", line 5, in
from .connect import * # noqa
File "C:\Users\rclary\Miniconda3\envs\test0\lib\site‑packages\ipykernel\connect.py", line 11, in
import jupyter_client
File "C:\Users\rclary\Miniconda3\envs\test0\lib\site‑packages\jupyter_client\__init__.py", line 6, in
from .asynchronous import AsyncKernelClient # noqa
File "C:\Users\rclary\Miniconda3\envs\test0\lib\site‑packages\jupyter_client\asynchronous\__init__.py", line 1, in
from .client import AsyncKernelClient # noqa
File "C:\Users\rclary\Miniconda3\envs\test0\lib\site‑packages\jupyter_client\asynchronous\client.py", line 6, in
from jupyter_client.channels import HBChannel
File "C:\Users\rclary\Miniconda3\envs\test0\lib\site‑packages\jupyter_client\channels.py", line 12, in
import zmq.asyncio
File "C:\Users\rclary\Miniconda3\envs\test0\lib\site‑packages\zmq\__init__.py", line 103, in
from zmq import backend
File "C:\Users\rclary\Miniconda3\envs\test0\lib\site‑packages\zmq\backend\__init__.py", line 31, in
raise original_error from None
File "C:\Users\rclary\Miniconda3\envs\test0\lib\site‑packages\zmq\backend\__init__.py", line 26, in
_ns = select_backend(first)
File "C:\Users\rclary\Miniconda3\envs\test0\lib\site‑packages\zmq\backend\select.py", line 31, in select_backend
mod = import_module(name)
File "C:\Users\rclary\Miniconda3\envs\test0\lib\importlib\__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "C:\Users\rclary\Miniconda3\envs\test0\lib\site‑packages\zmq\backend\cython\__init__.py", line 6, in
from . import (
ImportError: DLL load failed: The specified module could not be found.
```
</details>

## Versions

* Spyder version: 5.3.1 
* Python version: 3.8.10
* Qt version: 5.15.2
* PyQt5 version: 5.15.6
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.1.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<8.0.0              :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.5.1 (OK)
keyring >=17.0.0                     :  23.5.1 (OK)
nbconvert >=4.0                      :  6.5.0 (OK)
numpydoc >=0.6.0                     :  1.3.1 (OK)
paramiko >=2.4.0                     :  2.11.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.1 (OK)
pygments >=2.0                       :  2.12.0 (OK)
pylint >=2.5.0                       :  2.13.9 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0                 :  1.4.1 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0             :  5.3.0 (OK)
qtpy >=2.1.0                         :  2.1.0 (OK)
rtree >=0.9.7                        :  1.0.0 (OK)
setuptools >=49.6.0                  :  62.3.2 (OK)
sphinx >=0.6.6                       :  4.5.0 (OK)
spyder_kernels >=2.3.1;<2.4.0        :  2.3.1 (OK)
textdistance >=4.2.0                 :  4.2.2 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.1.8 (OK)
zmq >=22.1.0                         :  23.0.0 (OK)

# Optional:
cython >=0.21                        :  0.29.30 (OK)
matplotlib >=3.0.0                   :  3.5.2 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.4.2 (OK)
scipy >=0.17.0                       :  1.8.1 (OK)
sympy >=0.7.3                        :  1.10.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @mrclary, thanks for reporting.

@dalthviz, could you take a look at this one? Thanks!

**Comment by dalthviz** [comment]
@ccordoba12 @mrclary checking, seems like this is related with https://github.com/spyder-ide/spyder/issues/18003. [If I change the installer code at `get_spyder_umamba_path` to return `None`](https://github.com/spyder-ide/spyder/issues/18003#issuecomment-1141303333) the console kernel starts normally.

**Comment by ccordoba12** [comment]
Ok, I thought that was the case. Closing then in favor of #18003.
