### ISSUE TITLE
Spyder can't launch

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1814]
_From [alexandr...@gmail.com](https://code.google.com/u/104581462679240415847/) on 2014-05-09T23:09:32Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. python spyder.bat
2. python install from miniconda3 (python v3.3.5), dependencies from conda or pip 3. 

What is the expected output? What do you see instead?

 Spyder should launch but it actually stops with this error:
Traceback (most recent call last):
  File "C:\Miniconda3\Scripts\spyder", line 3, in \<module>
    start_app.main()
  File "C:\Miniconda3\lib\site-packages\spyderlib\start_app.py", line 91, in main
    spyder.main()
  File "C:\Miniconda3\lib\site-packages\spyderlib\spyder.py", line 2271, in main
    app = initialize()
  File "C:\Miniconda3\lib\site-packages\spyderlib\spyder.py", line 2136, in initialize
    rope_patch.apply()
  File "C:\Miniconda3\lib\site-packages\spyderlib\rope_patch.py", line 53, in apply
    from rope.base import pycore
  File "C:\Miniconda3\lib\site-packages\rope\base\pycore.py", line 6, in \<module>
    import rope.base.oi.doa
  File "C:\Miniconda3\lib\site-packages\rope\base\oi\doa.py", line 117
    except socket.error, e:
                       ^
SyntaxError: invalid syntax

rope version is 0.9.4 installed from conda What version of the product are you using? On what operating system? 2.3.0beta4 

Please provide any additional information below

. Attached is list of packages and crash log

**Attachment:** [spyder_crash.txt](http://code.google.com/p/spyderlib/issues/detail?id=1814)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1814_

**Comment by spyder-issues-migrator** [comment]
_From [alexandr...@gmail.com](https://code.google.com/u/104581462679240415847/) on 2014-05-10T08:08:37Z_

Ok solved, there is a bug in the rope package in conda
line 117, file rope\base\oi\doa.py: change "except socket, e" to "except socket as e"

**Comment by spyder-issues-migrator** [comment]
_From [robro...@gmail.com](https://code.google.com/u/114002459288016453009/) on 2014-05-13T10:40:46Z_

Yes, for Python 3 conda will wrongly install rope instead of rope-py3k. You should uninstall rope, and use pip (from the Python 3 environment) to install rope-py3k.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-16T16:57:39Z_

@-robrosit: Could you try to add a try/except block to avoid this crash in the future?

**Cc:** robro...@gmail.com

**Comment by spyder-issues-migrator** [comment]
_From [robro...@gmail.com](https://code.google.com/u/114002459288016453009/) on 2014-05-17T11:35:40Z_

Hello Carlos! Ok, let me take a look at the code. I'll ask for directions if necessary!
Roberto

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-17T17:19:14Z_

Great, don't hesitate to do it!

**Status:** Accepted

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-23T14:08:43Z_

This error was already fixed by Continuum guys, so please update your Anaconda installation.

**Status:** Invalid
