### ISSUE TITLE
internal problem

### ISSUE THREAD

**Issue by minhazulislam** [spyder-ide/spyder#18179]
### What steps will reproduce the problem?

I am using spyder with arcgis pro and it is crashing

### Traceback
```python-traceback
Exception ignored in: <function BaseEventLoop.__del__ at 0x00000202078E1288>
Traceback (most recent call last):
  File "C:\Users\mislam23\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone-1\lib\asyncio\base_events.py", line 628, in __del__
    self.close()
  File "C:\Users\mislam23\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone-1\lib\asyncio\selector_events.py", line 91, in close
    self._close_self_pipe()
  File "C:\Users\mislam23\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone-1\lib\asyncio\selector_events.py", line 98, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
  File "C:\Users\mislam23\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone-1\lib\asyncio\selector_events.py", line 271, in _remove_reader
    key = self._selector.get_key(fd)
  File "C:\Users\mislam23\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone-1\lib\selectors.py", line 190, in get_key
    return mapping[fileobj]
  File "C:\Users\mislam23\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone-1\lib\selectors.py", line 71, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "C:\Users\mislam23\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone-1\lib\selectors.py", line 225, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "C:\Users\mislam23\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone-1\lib\selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.7.11
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.31.1 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  21.7.0 (OK)
nbconvert >=4.0               :  5.6.1 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=1.0                  :  2.12.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.0 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.20.1 (OK)
pandas >=1.1.1                :  1.2.3 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.5.1 (OK)
```

**Comment by steff456** [comment]
Hi @minhazulislam,

Thanks for opening this issue, in your stacktrace I'm seeing the error is raised by `arcgispro`, have you checked that your file is in the correct format? Please also try to open a clean file and type your code there to see if Spyder crashes again.
