### ISSUE TITLE
Spyder with Python3

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1817]
_From [oma...@gmail.com](https://code.google.com/u/103150235582815115716/) on 2014-05-12T11:49:06Z_

Hi,

I have just downloaded the latest spyder for mac. I have a pre-installed python3 binary that I want to use as the interpreter. However, when I try to start spyder, I get the following message:

Error in sitecustomize; set PYTHONVERBOSE for traceback:
SyntaxError: invalid syntax (sitecustomize.py, line 432)
Python 3.3.5 (v3.3.5:62cf4e77f785, Mar  9 2014, 01:12:57) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/spyderlib/scientific_startup.py", line 57
    print ""
           ^
SyntaxError: invalid syntax

this is because print in python3 is now a function. Should I just change scientific_startup.py? or will that cause more problems? 

also, when I tried to debug my first program I get this error message:

Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
NameError: name 'debugfile' is not defined

Do I need to install something to use the debug tool?

Thanks!

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1817_

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-05-14T15:23:02Z_

The latest stable (2.2.5) version of spyder runs with python2 only. The current development version (2.3b) however works with both python2 and python3.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-16T16:53:34Z_

Yep, please use our beta if you want PY3 support.

**Status:** WontFix
