### ISSUE TITLE
latest libsodium (0.5.0-1) breaks zmq bindings of Spyder's IPython widget

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1818]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-05-14T07:46:01Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 This comment is from Arch Linux for the dev version https://aur.archlinux.org/packages/spyder-hg/ :
"FYI latest libsodium (0.5.0-1) breaks zmq bindings of Spyder's IPython widget" 

What is the expected output? What do you see instead?

 Please use labels and text to provide additional information. I have no more information but I open the issue to keep it in mind.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1818_

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-05-14T06:43:44Z_

Update: https://github.com/jedisct1/libsodium/issues/155

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-16T16:55:41Z_

I think this is an upstream problem. We could just add a try/except (but where?) to avoid this crash.

Joseph, what do you think?

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-05-19T02:00:39Z_

From the updates in https://github.com/jedisct1/libsodium/issues/155 , it looks like it's solved, it was a problem in Arch Linux packaging.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-19T05:19:54Z_

**Status:** WontFix

**Comment by RoyiAvital** [comment]
I have this issue with Spyder 3.2.8:

```
Traceback (most recent call last):
File "/home/royia/anaconda3/envs/PyTorch/bin/spyder", line 7, in 
from spyder.app.start import main
File "/home/royia/anaconda3/envs/PyTorch/lib/python3.6/site-packages/spyder/app/start.py", line 14, in 
import zmq
File "/home/royia/anaconda3/envs/PyTorch/lib/python3.6/site-packages/zmq/__init__.py", line 47, in 
from zmq import backend
File "/home/royia/anaconda3/envs/PyTorch/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in 
reraise(*exc_info)
File "/home/royia/anaconda3/envs/PyTorch/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
raise value
File "/home/royia/anaconda3/envs/PyTorch/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in 
_ns = select_backend(first)
File "/home/royia/anaconda3/envs/PyTorch/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "/home/royia/anaconda3/envs/PyTorch/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: libsodium.so.23: cannot open shared object file: No such file or directory

```

**Comment by RoyiAvital** [comment]
My List of packages from `conda list`:

```
# Name                    Version                   Build  Channel
alabaster                 0.7.10           py36h306e16b_0  
anaconda                  custom           py36hbbc8b67_0  
anaconda-client           1.6.5            py36h19c0dcd_0  
anaconda-navigator        1.6.9            py36h11ddaaa_0  
anaconda-project          0.8.0            py36h29abdf5_0  
asn1crypto                0.22.0           py36h265ca7c_1  
astroid                   1.5.3            py36hbdb9df2_0  
astropy                   2.0.2            py36ha51211e_4  
babel                     2.5.0            py36h7d14adf_0  
backcall                  0.1.0                    py36_0  
backports                 1.0              py36hfa02d7e_1  
backports.shutil_get_terminal_size 1.0.0            py36hfea85ff_2  
beautifulsoup4            4.6.0            py36h49b8c8c_1  
bitarray                  0.8.1            py36h5834eb8_0  
bkcharts                  0.2              py36h735825a_0  
blas                      1.0                         mkl  
blaze                     0.11.3           py36h4e06776_0  
bleach                    2.0.0            py36h688b259_0  
bokeh                     0.12.16                  py36_0  
boto                      2.48.0           py36h6e4cd66_1  
bottleneck                1.2.1            py36haac1ea0_0  
bzip2                     1.0.6                h0376d23_1  
ca-certificates           2018.03.07                    0  
cairo                     1.14.10              haa5651f_5  
certifi                   2018.4.16                py36_0  
cffi                      1.10.0           py36had8d393_1  
chardet                   3.0.4            py36h0f667ec_1  
click                     6.7              py36h5253387_0  
cloudpickle               0.4.0            py36h30f8c20_0  
clyent                    1.2.2            py36h7e57e65_1  
colorama                  0.3.9            py36h489cec4_0  
contextlib2               0.5.5            py36h6c84a62_0  
cryptography              2.0.3            py36ha225213_1  
cudatoolkit               8.0                           3  
cudnn                     7.0.5                 cuda8.0_0  
curl                      7.55.1               hcb0b314_2  
cycler                    0.10.0           py36h93f1223_0  
cython                    0.26.1           py36h21c49d0_0  
cytoolz                   0.8.2            py36h708bfd4_0  
dask                      0.15.3           py36hdc2c8aa_0  
dask-core                 0.15.3           py36h10e6167_0  
datashape                 0.5.4            py36h3ad6b5c_0  
dbus                      1.13.2               hc3f9b76_0  
decorator                 4.1.2            py36hd076ac8_0  
distributed               1.19.1           py36h25f3894_0  
docutils                  0.14             py36hb0f60f5_0  
entrypoints               0.2.3            py36h1aec115_2  
et_xmlfile                1.0.1            py36hd6bccc3_0  
expat                     2.2.5                he0dffb1_0  
fastcache                 1.0.2            py36h5b0c431_0  
filelock                  2.0.12           py36hacfa1f5_0  
flask                     0.12.2           py36hb24657c_0  
flask-cors                3.0.3            py36h2d857d3_0  
fontconfig                2.12.6               h49f89f6_0  
freetype                  2.8                  h52ed37b_0  
get_terminal_size         1.0.0                haa9412d_0  
gevent                    1.2.2            py36h2fe25dc_0  
glib                      2.53.6               hc861d11_1  
glob2                     0.5              py36h2c1b292_1  
gmp                       6.1.2                hb3b607b_0  
gmpy2                     2.0.8            py36h55090d7_1  
graphite2                 1.3.10               hc526e54_0  
greenlet                  0.4.12           py36h2d503a6_0  
gst-plugins-base          1.12.4               h33fb286_0  
gstreamer                 1.12.4               hb53b477_0  
h5py                      2.7.0            py36he81ebca_1  
harfbuzz                  1.5.0                h2545bd6_0  
hdf5                      1.10.1               hb0523eb_0  
heapdict                  1.0.0            py36h79797d7_0  
html5lib                  0.999999999      py36h2cfc398_0  
icu                       58.2                 h211956c_0  
idna                      2.6              py36h82fb2a8_1  
imageio                   2.2.0            py36he555465_0  
imagesize                 0.7.1            py36h52d8127_0  
intel-openmp              2018.0.0             h15fc484_7  
ipykernel                 4.8.2                    py36_0  
ipython                   6.4.0                    py36_0  
ipython_genutils          0.2.0            py36hb52b0d5_0  
ipywidgets                7.0.5            py36h31d6531_0  
isort                     4.2.15           py36had401c0_0  
itsdangerous              0.24             py36h93cc618_1  
jbig                      2.1                  hdba287a_0  
jdcal                     1.3              py36h4c697fb_0  
jedi                      0.10.2           py36h552def0_0  
jinja2                    2.9.6            py36h489bce4_1  
jpeg                      9b                   habf39ab_1  
jsonschema                2.6.0            py36h006f8b5_0  
jupyter                   1.0.0            py36h9896ce5_0  
jupyter_client            5.2.3                    py36_0  
jupyter_console           5.2.0            py36he59e554_1  
jupyter_core              4.4.0            py36h7c827e3_0  
jupyterlab                0.32.1                   py36_0  
jupyterlab_launcher       0.10.5                   py36_0  
kiwisolver                1.0.1            py36h764f252_0  
lazy-object-proxy         1.3.1            py36h10fcdad_0  
libedit                   3.1                  heed3624_0  
libffi                    3.2.1                h4deb6c0_3  
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 7.2.0                h7cc24e2_2  
libgfortran-ng            7.2.0                h9f7466a_2  
libpng                    1.6.34               hb9fc6fc_0  
libsodium                 1.0.13               h31c71d8_2  
libssh2                   1.8.0                h8c220ad_2  
libstdcxx-ng              7.2.0                h7a57d05_2  
libtiff                   4.0.9                h28f6b97_0  
libtool                   2.4.6                hd50d1a6_0  
libxcb                    1.12                 h84ff03f_3  
libxml2                   2.9.8                hf84eae3_0  
libxslt                   1.1.29               hcf9102b_5  
llvmlite                  0.23.1           py36hdbcaa40_0  
locket                    0.2.0            py36h787c0ad_1  
lxml                      4.1.0            py36h5b66e50_0  
lzo                       2.10                 h1bfc0ba_1  
markupsafe                1.0              py36hd9260cd_1  
matplotlib                2.2.2            py36h0e671d2_1  
mccabe                    0.6.1            py36h5ad9710_1  
mistune                   0.8.1            py36h3d5977c_0  
mkl                       2018.0.2                      1  
mkl-service               1.1.2            py36h17a0993_4  
mkl_fft                   1.0.1            py36h3010b51_0  
mkl_random                1.0.1            py36h629b387_0  
mpc                       1.0.3                hf803216_4  
mpfr                      3.1.5                h12ff648_1  
mpmath                    0.19             py36h8cc018b_2  
msgpack-python            0.4.8            py36hec4c5d1_0  
multipledispatch          0.4.9            py36h41da3fb_0  
navigator-updater         0.1.0            py36h14770f7_0  
nbconvert                 5.3.1            py36hb41ffb7_0  
nbformat                  4.4.0            py36h31c9010_0  
nccl                      1.3.4                 cuda8.0_1  
ncurses                   6.0                  h06874d7_1  
networkx                  2.0              py36h7e96fb8_0  
ninja                     1.8.2            py36h6bb024c_1  
nltk                      3.2.4            py36h1a0979f_0  
nose                      1.3.7            py36hcdf7029_2  
notebook                  5.5.0                    py36_0  
numba                     0.38.0           py36h637b7d7_0  
numexpr                   2.6.4            py36hc4a3f9a_0  
numpy                     1.14.3           py36hcd700cb_1  
numpy-base                1.14.3           py36h9be14a7_1  
numpydoc                  0.7.0            py36h18f165f_0  
odo                       0.5.1            py36h90ed295_0  
olefile                   0.44             py36h79f9f78_0  
openpyxl                  2.4.8            py36h41dd2a8_1  
openssl                   1.0.2o               h20670df_0  
packaging                 16.8             py36ha668100_1  
pandas                    0.23.0           py36h637b7d7_0  
pandoc                    1.19.2.1             hea2e7c5_1  
pandocfilters             1.4.2            py36ha6701b7_1  
pango                     1.40.11              h8191d47_0  
partd                     0.3.8            py36h36fd896_0  
patchelf                  0.9                  hf79760b_2  
path.py                   10.3.1           py36he0c6f6d_0  
pathlib2                  2.3.0            py36h49efa8e_0  
patsy                     0.4.1            py36ha3be15e_0  
pcre                      8.41                 hc71a17e_0  
pep8                      1.7.0            py36h26ade29_0  
pexpect                   4.2.1            py36h3b9d41b_0  
pickleshare               0.7.4            py36h63277f8_0  
pillow                    4.3.0            py36h6f462bf_1  
pip                       9.0.1            py36h8ec8b28_3  
pixman                    0.34.0               h83dc358_2  
pkginfo                   1.4.1            py36h215d178_1  
ply                       3.10             py36hed35086_0  
prompt_toolkit            1.0.15           py36h17d85b1_0  
psutil                    5.4.0            py36h84c53db_0  
ptyprocess                0.5.2            py36h69acd42_0  
py                        1.4.34           py36h0712aa3_1  
pycodestyle               2.3.1            py36hf609f19_0  
pycosat                   0.6.2            py36h1a0ea17_1  
pycparser                 2.18             py36hf9f622e_1  
pycrypto                  2.6.1            py36h6998063_1  
pycurl                    7.43.0           py36h5e72054_3  
pyflakes                  1.6.0            py36h7bd6a15_0  
pygments                  2.2.0            py36h0d3125c_0  
pylint                    1.7.4            py36hb9d4533_0  
pyodbc                    4.0.17           py36h999153c_0  
pyopenssl                 17.2.0           py36h5cc804b_0  
pyparsing                 2.2.0            py36hee85983_1  
pyqt                      5.9.2            py36h751905a_0  
pysocks                   1.6.7            py36hd97a5b1_1  
pytables                  3.4.2            py36h3b5282a_2  
pytest                    3.2.1            py36h11ad3bb_1  
python                    3.6.5                hc3d631a_2  
python-dateutil           2.6.1            py36h88d3b88_1  
pytorch                   0.4.0            py36hd73e86b_0  
pytz                      2017.2           py36hc2ccc2a_1  
pywavelets                0.5.2            py36he602eb0_0  
pyyaml                    3.12             py36hafb9ca4_1  
pyzmq                     17.0.0           py36h14c3975_0  
qt                        5.9.4                h4e5bff0_0  
qtawesome                 0.4.4            py36h609ed8c_0  
qtconsole                 4.3.1            py36h8f73b5b_0  
qtpy                      1.3.1            py36h3691cc8_0  
readline                  7.0                  hac23ff0_3  
requests                  2.18.4           py36he2e5f8d_1  
rope                      0.10.5           py36h1f8c17e_0  
ruamel_yaml               0.11.14          py36ha2fb22d_2  
scikit-image              0.13.1           py36h14c3975_1  
scikit-learn              0.19.1           py36h7aa7ec6_0  
scipy                     1.1.0            py36hfc37229_0  
seaborn                   0.8.0            py36h197244f_0  
send2trash                1.5.0                    py36_0  
setuptools                36.5.0           py36he42e2e1_0  
simplegeneric             0.8.1            py36h2cb9092_0  
singledispatch            3.4.0.3          py36h7a266c3_0  
sip                       4.19.8           py36hf484d3e_0  
six                       1.11.0           py36h372c433_1  
snowballstemmer           1.2.1            py36h6febd40_0  
sortedcollections         0.5.3            py36h3c761f9_0  
sortedcontainers          1.5.7            py36hdf89491_0  
sphinx                    1.6.3            py36he5f0bdb_0  
sphinxcontrib             1.0              py36h6d0f590_1  
sphinxcontrib-websupport  1.0.1            py36hb5cb234_1  
spyder                    3.2.8                    py36_0  
sqlalchemy                1.1.13           py36hfb5efd7_0  
sqlite                    3.23.1               he433501_0  
statsmodels               0.8.0            py36h8533d0b_0  
sympy                     1.1.1            py36hc6d1c1c_0  
tblib                     1.3.2            py36h34cf8b6_0  
terminado                 0.8.1                    py36_1  
testpath                  0.3.1            py36h8cadb63_0  
tk                        8.6.7                h5979e9b_1  
toolz                     0.8.2            py36h81f2dff_0  
torchvision               0.2.1                    py36_0  
tornado                   4.5.2            py36h1283b2a_0  
traitlets                 4.3.2            py36h674d592_0  
typing                    3.6.2            py36h7da032a_0  
unicodecsv                0.14.1           py36ha668878_0  
unixodbc                  2.3.4                hc36303a_1  
urllib3                   1.22             py36hbe7ace6_0  
wcwidth                   0.1.7            py36hdf4376a_0  
webencodings              0.5.1            py36h800622e_1  
werkzeug                  0.12.2           py36hc703753_0  
wheel                     0.29.0           py36he7f4e38_1  
widgetsnbextension        3.0.8            py36h25a1d49_0  
wrapt                     1.10.11          py36h28b7045_0  
xlrd                      1.1.0            py36h1db9f0c_1  
xlsxwriter                1.0.2            py36h3de1aca_0  
xlwt                      1.3.0            py36h7b00a1f_0  
xz                        5.2.3                h2bcbf08_1  
yaml                      0.1.7                h96e3832_1  
zeromq                    4.2.3                h439df22_3  
zict                      0.1.3            py36h3a3bf81_0  
zlib                      1.2.11               hfbfcf68_1
```
