### ISSUE TITLE
Launched spyder from terminal in linux on a chrome browser conected to a HPC

### ISSUE THREAD

**Issue by Tyros43** [spyder-ide/spyder#18189]
### What steps will reproduce the problem?

Launc spyder with command "spyder &" in terminal on linux OS. This was done from a Chrome browser on a Windows laptop coneccted to a high performance computing network that my university runs.

### Traceback
```python-traceback
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/jupyter_client/threaded.py", line 117, in _handle_recv
    ident, smsg = self.session.feed_identities(msg_list)
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/jupyter_client/session.py", line 968, in feed_identities
    idx = msg_list.index(DELIM)
AttributeError: '_asyncio.Future' object has no attribute 'index'
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 577, in _handle_events
    self._handle_recv()
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 606, in _handle_recv
    self._run_callback(callback, msg)
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/jupyter_client/threaded.py", line 117, in _handle_recv
    ident, smsg = self.session.feed_identities(msg_list)
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/jupyter_client/session.py", line 968, in feed_identities
    idx = msg_list.index(DELIM)
AttributeError: '_asyncio.Future' object has no attribute 'index'
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(87, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(87, 1)>
Traceback (most recent call last):
  File "/appl/python/3.8.11/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 577, in _handle_events
    self._handle_recv()
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 606, in _handle_recv
    self._run_callback(callback, msg)
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/jupyter_client/threaded.py", line 117, in _handle_recv
    ident, smsg = self.session.feed_identities(msg_list)
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/jupyter_client/session.py", line 968, in feed_identities
    idx = msg_list.index(DELIM)
AttributeError: '_asyncio.Future' object has no attribute 'index'
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/jupyter_client/threaded.py", line 117, in _handle_recv
    ident, smsg = self.session.feed_identities(msg_list)
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/jupyter_client/session.py", line 968, in feed_identities
    idx = msg_list.index(DELIM)
AttributeError: '_asyncio.Future' object has no attribute 'index'
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 577, in _handle_events
    self._handle_recv()
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 606, in _handle_recv
    self._run_callback(callback, msg)
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/jupyter_client/threaded.py", line 117, in _handle_recv
    ident, smsg = self.session.feed_identities(msg_list)
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/jupyter_client/session.py", line 968, in feed_identities
    idx = msg_list.index(DELIM)
AttributeError: '_asyncio.Future' object has no attribute 'index'
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(86, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(86, 1)>
Traceback (most recent call last):
  File "/appl/python/3.8.11/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 577, in _handle_events
    self._handle_recv()
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 606, in _handle_recv
    self._run_callback(callback, msg)
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/jupyter_client/threaded.py", line 117, in _handle_recv
    ident, smsg = self.session.feed_identities(msg_list)
  File "/zhome/7b/0/127317/s1_exercise/lib/python3.8/site-packages/jupyter_client/session.py", line 968, in feed_identities
    idx = msg_list.index(DELIM)
AttributeError: '_asyncio.Future' object has no attribute 'index'
```

## Versions

* Spyder version: 4.2.5 
* Python version: 3.8.11
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 3.10.0-1160.66.1.el7.x86_64

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  2.1.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  8.4.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  4.6.0 (OK)
keyring >=17.0.0                :  23.5.1 (OK)
nbconvert >=4.0                 :  6.5.0 (OK)
numpydoc >=0.6.0                :  1.3.1 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.9.1 (OK)
pygments >=2.0                  :  2.12.0 (OK)
pylint >=1.0                    :  2.14.1 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.7 (OK)
pyls_spyder >=0.3.2             :  0.4.0 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.1.1 (OK)
qtconsole >=5.0.3               :  5.3.1 (OK)
qtpy >=1.5.0                    :  2.1.0 (OK)
setuptools >=39.0.0             :  57.4.0 (OK)
sphinx >=0.6.6                  :  5.0.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.3 (OK)
textdistance >=4.2.0            :  4.2.2 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
xdg >=0.26                      :  0.28 (OK)
zmq >=17                        :  23.1.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.5.2 (OK)
numpy >=1.7                     :  1.22.4 (OK)
pandas >=1.1.1                  :  1.4.2 (OK)
scipy >=0.17.0                  :  None (NOK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by steff456** [comment]
Hi @Tyros43,

I think your issue may be related to https://github.com/spyder-ide/spyder/issues/18174, can you please go and check that thread, maybe downgrading your jupyter client fix this issue.

Let me know if that helps!
