### ISSUE TITLE
Spyder Cannot Connect to Kernel

### ISSUE THREAD

**Issue by stumpyd123** [spyder-ide/spyder#18195]
### What steps will reproduce the problem?

Install Spyder 5.3.1. Open Spyder. Then it never connects to the kernel. It sticks on "Connecting to Kernel". I also tried starting Spyder from Anaconda Prompt, and received the following traceback.

```
AttributeError: '_asyncio.Future' object has no attribute 'index'
ERROR:tornado.application:Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x000001A4F3FAFE20>)
Traceback (most recent call last):
  File "C:\Users\<user>\Anaconda3\envs\gispy\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
    ret = callback()
  File "C:\Users\<user>\Anaconda3\envs\gispy\lib\site-packages\zmq\eventloop\zmqstream.py", line 661, in <lambda>
    self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
  File "C:\Users\<user>\Anaconda3\envs\gispy\lib\site-packages\zmq\eventloop\zmqstream.py", line 577, in _handle_events
    self._handle_recv()
  File "C:\Users\<user>\Anaconda3\envs\gispy\lib\site-packages\zmq\eventloop\zmqstream.py", line 606, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\<user>\Anaconda3\envs\gispy\lib\site-packages\zmq\eventloop\zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\<user>\Anaconda3\envs\gispy\lib\site-packages\jupyter_client\threaded.py", line 117, in _handle_recv
    ident, smsg = self.session.feed_identities(msg_list)
  File "C:\Users\<user>\Anaconda3\envs\gispy\lib\site-packages\jupyter_client\session.py", line 968, in feed_identities
    idx = msg_list.index(DELIM)
AttributeError: '_asyncio.Future' object has no attribute 'index'
```

## Versions

* Spyder version: 5.3.1 
* Python version: 3.10.4
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.1.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.6.0 (OK)
keyring >=17.0.0              :  23.5.1 (OK)
nbconvert >=4.0               :  6.5.0 (OK)
numpydoc >=0.6.0              :  1.2.1 (OK)
paramiko >=2.4.0              :  2.11.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.1 (OK)
pygments >=2.0                :  2.12.0 (OK)
pylint >=2.5.0                :  2.14.1 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.1 (OK)
qtpy >=2.1.0                  :  2.1.0 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  62.3.2 (OK)
sphinx >=0.6.6                :  5.0.1 (OK)
spyder_kernels >=2.3.1;<2.4.0 :  2.3.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.8 (OK)
zmq >=22.1.0                  :  23.1.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.22.4 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.8.1 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by TSwailes** [comment]
I'm having the same issue (also Windows 10), with different versions of some dependencies:

Spyder = 5.3.1
python = 3.9.0
PyQt5 = 5.15.6
spyder-kernels = 2.3.1

Please let me know if I can provide information to support debugging somehow, it hangs on 'connecting to kernel...' so I can't find a traceback to supply (starting spyder from powershell or explorer does not provide any error message, just hangs).

**Comment by Mushoz** [comment]
I am having the same issue on Arch Linux. Spyder 5.3.1 and python 3.10.5. Spyder was working fine yesterday, so it's a regression that was introduced very recently.

**Comment by dalthviz** [comment]
Hi all, I think this most probably is related with https://github.com/spyder-ide/spyder/issues/18174 (jupyter_client >= 7.3.2 is causing issues when starting kernels)

**Comment by Mushoz** [comment]
@dalthviz that could definitely be possible. Looking at the changelog for that package in Arch's repository, I can see that it was upgraded yesterday and today, which coincides with when the issues started.

**Comment by steff456** [comment]
Hi guys!

As @dalthviz already mentioned please use the main issue https://github.com/spyder-ide/spyder/issues/18174 to discuss about possible fixes. I'm going to close this one.

Thanks a lot for reporting!
