### ISSUE TITLE
Spyder kernel is not getting connected

### ISSUE THREAD

**Issue by ParshvaParekh** [spyder-ide/spyder#18198]
### What steps will reproduce the problem?

When ever I open the spyder I found the error. 

I tried to update it several time but negative.

Please help me here

### Traceback
```python-traceback
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 117, in _handle_recv
    ident, smsg = self.session.feed_identities(msg_list)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\session.py", line 968, in feed_identities
    idx = msg_list.index(DELIM)
AttributeError: '_asyncio.Future' object has no attribute 'index'
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 577, in _handle_events
    self._handle_recv()
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 606, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 117, in _handle_recv
    ident, smsg = self.session.feed_identities(msg_list)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\session.py", line 968, in feed_identities
    idx = msg_list.index(DELIM)
AttributeError: '_asyncio.Future' object has no attribute 'index'
ERROR:tornado.application:Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x000002D238DE15E8>)
Traceback (most recent call last):
  File "C:\Users\prpar\Anaconda3\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
    ret = callback()
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 661, in <lambda>
    self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 577, in _handle_events
    self._handle_recv()
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 606, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 117, in _handle_recv
    ident, smsg = self.session.feed_identities(msg_list)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\session.py", line 968, in feed_identities
    idx = msg_list.index(DELIM)
AttributeError: '_asyncio.Future' object has no attribute 'index'
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 117, in _handle_recv
    ident, smsg = self.session.feed_identities(msg_list)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\session.py", line 968, in feed_identities
    idx = msg_list.index(DELIM)
AttributeError: '_asyncio.Future' object has no attribute 'index'
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 577, in _handle_events
    self._handle_recv()
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 606, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 117, in _handle_recv
    ident, smsg = self.session.feed_identities(msg_list)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\session.py", line 968, in feed_identities
    idx = msg_list.index(DELIM)
AttributeError: '_asyncio.Future' object has no attribute 'index'
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(5576, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(5576, 1)>
Traceback (most recent call last):
  File "C:\Users\prpar\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 577, in _handle_events
    self._handle_recv()
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 606, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 117, in _handle_recv
    ident, smsg = self.session.feed_identities(msg_list)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\session.py", line 968, in feed_identities
    idx = msg_list.index(DELIM)
AttributeError: '_asyncio.Future' object has no attribute 'index'
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 117, in _handle_recv
    ident, smsg = self.session.feed_identities(msg_list)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\session.py", line 968, in feed_identities
    idx = msg_list.index(DELIM)
AttributeError: '_asyncio.Future' object has no attribute 'index'
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 577, in _handle_events
    self._handle_recv()
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 606, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 117, in _handle_recv
    ident, smsg = self.session.feed_identities(msg_list)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\session.py", line 968, in feed_identities
    idx = msg_list.index(DELIM)
AttributeError: '_asyncio.Future' object has no attribute 'index'
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(5776, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(5776, 1)>
Traceback (most recent call last):
  File "C:\Users\prpar\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 577, in _handle_events
    self._handle_recv()
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 606, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 117, in _handle_recv
    ident, smsg = self.session.feed_identities(msg_list)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\session.py", line 968, in feed_identities
    idx = msg_list.index(DELIM)
AttributeError: '_asyncio.Future' object has no attribute 'index'
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 117, in _handle_recv
    ident, smsg = self.session.feed_identities(msg_list)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\session.py", line 968, in feed_identities
    idx = msg_list.index(DELIM)
AttributeError: '_asyncio.Future' object has no attribute 'index'
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 577, in _handle_events
    self._handle_recv()
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 606, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 117, in _handle_recv
    ident, smsg = self.session.feed_identities(msg_list)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\session.py", line 968, in feed_identities
    idx = msg_list.index(DELIM)
AttributeError: '_asyncio.Future' object has no attribute 'index'
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(2720, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(2720, 1)>
Traceback (most recent call last):
  File "C:\Users\prpar\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 577, in _handle_events
    self._handle_recv()
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 606, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 117, in _handle_recv
    ident, smsg = self.session.feed_identities(msg_list)
  File "C:\Users\prpar\Anaconda3\lib\site-packages\jupyter_client\session.py", line 968, in feed_identities
    idx = msg_list.index(DELIM)
AttributeError: '_asyncio.Future' object has no attribute 'index'
```

## Versions

* Spyder version: 4.1.4 
* Python version: 3.7.6
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  4.0.0 (OK)
cloudpickle >=0.5.0            :  2.1.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.33.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.5.0 (OK)
numpydoc >=0.6.0               :  1.3.1 (OK)
paramiko >=2.4.0               :  2.11.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.9.1 (OK)
pygments >=2.0                 :  2.12.0 (OK)
pylint >=1.0                   :  2.14.1 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.1.1 (OK)
qtconsole >=4.6.0              :  5.3.1 (OK)
qtpy >=1.5.0                   :  2.1.0 (OK)
rtree >=0.8.3                  :  1.0.0 (OK)
sphinx >=0.6.6                 :  5.0.1 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  23.1.0 (OK)

# Optional:
cython >=0.21                  :  0.29.30 (OK)
matplotlib >=2.0.0             :  3.5.2 (OK)
numpy >=1.7                    :  1.21.5 (OK)
pandas >=0.13.1                :  1.3.4 (OK)
scipy >=0.17.0                 :  1.7.3 (OK)
sympy >=0.7.3                  :  1.10.1 (OK)
```

**Comment by sakimarquis** [comment]
see here https://github.com/spyder-ide/spyder/issues/18174

**Comment by ParshvaParekh** [comment]
> see here #18174

Sorry, but it didn't work either.

**Comment by FrankwaP** [comment]
One of the first error you see is "ERROR:tornado.general:Uncaught exception in zmqstream callback"… which leads [this 2018 post](https://github.com/spyder-ide/spyder/issues/6783) suggesting that it's tornado or ipykernel version problem.

So first, what are your versions?

I also have this problem on Linux and I have:

python                    3.9.13          h9a8a25e_0_cpython    conda-forge
spyder                    5.3.1            py39hf3d152e_0    conda-forge
ipykernel                 6.13.1           py39hef51801_0    conda-forge
tornado                   6.1              py39hb9d737c_3    conda-forge
