### ISSUE TITLE
Quick layout change unsuccessful

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1819]
_From [grzegorz...@gmail.com](https://code.google.com/u/108416573600251500692/) on 2014-05-15T06:18:00Z_

Spyder Version:  2.2.5
Python Version:  2.7.5
Qt Version    :  4.8.4, PyQt4 (API v2) 4.9.6 on Windows
pyflakes >=0.5.0:  0.7.3 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  1.1.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.4 (OK)
pylint >=0.25   :  1.0.0 (OK) 

What steps will reproduce the problem?

 1. Saving a layout
2. changing (closing dockwidgets)
3. saving again under slot number 2
4. trying to change back to layout 1 

What is the expected output? What do you see instead?

 Expected: A change of layout.
Result: Internal console error:

Spyder 2.2.5 internal shell on Python 2.7.5 32bits [Windows]
Inspect Spyder internals:
  spy.app, spy.window, dir(spy)
\>>> Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 965, in \<lambda>
    self.quick_layout_switch(i))
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 1259, in quick_layout_switch
    self.set_window_settings(*self.previous_layout_settings)
TypeError: set_window_settings() takes exactly 7 arguments (8 given)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 965, in \<lambda>
    self.quick_layout_switch(i))
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 1259, in quick_layout_switch
    self.set_window_settings(*self.previous_layout_settings)
TypeError: set_window_settings() takes exactly 7 arguments (8 given)

(I've tried to change the layout twice)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1819_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-16T16:52:41Z_

Thanks for reporting.

**Labels:** MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-05-24T01:57:38Z_

To reproduce the problem, you have to load the same layout twice in a row (changing between two layouts works fine). Spyder tries to switch between the saved layout and the previous state, and this fails.

Looks like the functions load_window_settings and set_window_settings were updated, but get_window_settings was forgotten. I tried to update it but now instead of throwing an exception spyder freezes. I quess that it's a problem with hexstate. Here's what I tried:


    def get_window_settings(self):
        """Return current window settings
        Symetric to the 'set_window_settings' setter"""
        window_size = (self.window_size.width, self.window_size.height)
        is_fullscreen = self.isFullScreen()
        if is_fullscreen:
            is_maximized = self.maximized_flag
        else:
            is_maximized = self.isMaximized()
        pos = (self.window_position.x, self.window_position.y)
        prefs_dialog_size = (self.prefs_dialog_size.width,
                             self.prefs_dialog_size.height)
        hexstate = qbytearray_to_str(self.saveState())
        return (hexstate, window_size, prefs_dialog_size, pos, is_maximized,
                is_fullscreen)

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-05-24T12:56:52Z_

Nevermind, this is now fixed in PR 47: https://bitbucket.org/spyder-ide/spyderlib/pull-request/47/fix-switch-layout-1819/diff

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-28T20:07:01Z_

This issue was updated by revision 0f61527ccba7 .

**Status:** Fixed
