### ISSUE TITLE
Spyder do not start after installing (apt on ubuntu)

### ISSUE THREAD

**Issue by orlapa** [spyder-ide/spyder#18222]
I have installed the default version (repo), and no problems on install.
Even all seems ok, (link in Developmen section of menu, etc), if I try to start it, the splash appear dor a second and close. No aplication is started.
If I try from console, the splash also appear for one or two seconds and close with this message

 orlapalm  ~  spyder 
Traceback (most recent call last):
  File "/usr/bin/spyder", line 33, in <module>
    sys.exit(load_entry_point('spyder==4.2.1', 'gui_scripts', 'spyder')())
  File "/usr/lib/python3/dist-packages/spyder/app/start.py", line 213, in main
    mainwindow.main(options, args)
  File "/usr/lib/python3/dist-packages/spyder/app/mainwindow.py", line 3624, in main
    mainwindow = create_window(app, splash, options, args)
  File "/usr/lib/python3/dist-packages/spyder/app/mainwindow.py", line 3482, in create_window
    main.setup()
  File "/usr/lib/python3/dist-packages/spyder/app/mainwindow.py", line 803, in setup
    self.completions = CompletionManager(self)
  File "/usr/lib/python3/dist-packages/spyder/plugins/completion/plugin.py", line 97, in __init__
    plugin_client = Plugin(self.main)
  File "/usr/lib/python3/dist-packages/spyder/plugins/completion/kite/plugin.py", line 50, in __init__
    self.installer = KiteInstallerDialog(
  File "/usr/lib/python3/dist-packages/spyder/plugins/completion/kite/widgets/install.py", line 287, in __init__
    self._integration_widget = KiteIntegrationInfo(self)
  File "/usr/lib/python3/dist-packages/spyder/plugins/completion/kite/widgets/install.py", line 58, in __init__
    image = image.scaled(image_width, image_height, Qt.KeepAspectRatio,
TypeError: arguments did not match any overloaded call:
  scaled(self, int, int, aspectRatioMode: Qt.AspectRatioMode = Qt.IgnoreAspectRatio, transformMode: Qt.TransformationMode = Qt.FastTransformation): argument 1 has unexpected type 'float'
  scaled(self, QSize, aspectRatioMode: Qt.AspectRatioMode = Qt.IgnoreAspectRatio, transformMode: Qt.TransformationMode = Qt.FastTransformation): argument 1 has unexpected type 'float'

```


* Spyder version: 4.2.1
* Python version: 3.10.4qt
* Qt version: 5.15.3
* PyQt version: 5.15.6
* Operating System name/version: 

```

**Comment by andfoy** [comment]
Hi @orlapa, it seems that you are installing a very old and unsupported version of Spyder via an unofficial installation medium. We invite you to install Spyder via anaconda/conda-forge. Please refer to our installation guide, available on the official Spyder documentation: https://docs.spyder-ide.org/current/installation.html

**Comment by orlapa** [comment]
Hi, thanks for your reply.
I have installed using pip and now is working Ok
Thanks a lot
Regards
