### ISSUE TITLE
ipython console does not start up with an "unsigned message" error.

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1823]
_From [ingo.son...@gmail.com](https://code.google.com/u/106625150125315426199/) on 2014-05-19T12:09:00Z_

Spyder Version:  2.3.0dev
Python Version:  2.7.6
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Linux
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  3.0.0-dev (OK)
pygments >=1.6  :  1.6 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  1.2.1 (OK)
rope >=0.9.2    :  0.9.2 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.4.1 (OK)
pylint >=0.25   :  1.1.0 (OK) 

What steps will reproduce the problem?

 1. Start Spyder
2. Start a new IPython shell 

What is the expected output? What do you see instead?

 - IPython shell should start.
- IPython shell does not start, and in the internal console the following error message is printed (the message contains paths to my local IPython installation):

[IPKernelApp] ERROR | Invalid Message
Traceback (most recent call last):
  File "/mnt/DATA/software/src/ipython/IPython/kernel/zmq/ipkernel.py", line 214, in dispatch_shell
    msg = self.session.unserialize(msg, content=True, copy=False)
  File "/mnt/DATA/software/src/ipython/IPython/kernel/zmq/session.py", line 811, in unserialize
    raise ValueError("Unsigned Message")
ValueError: Unsigned Message
[IPKernelApp] ERROR | Invalid Message
Traceback (most recent call last):
  File "/mnt/DATA/software/src/ipython/IPython/kernel/zmq/ipkernel.py", line 214, in dispatch_shell
    msg = self.session.unserialize(msg, content=True, copy=False)
  File "/mnt/DATA/software/src/ipython/IPython/kernel/zmq/session.py", line 811, in unserialize
    raise ValueError("Unsigned Message")
ValueError: Unsigned Message 

Please provide any additional information below

. I run IPython checked out directly from github. Probably the issue is due to that very recent version (3.0.0-dev). They started "signing/trusting" their notebooks recently; Don't know if these things are related...

Thanks!

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1823_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-01T15:01:29Z_

I hope you have fixed this error by now :-)

**Status:** WontFix
