### ISSUE TITLE
spyder problem 

### ISSUE THREAD

**Issue by Vinodhini12** [spyder-ide/spyder#18239]
### What steps will reproduce the problem?

Traceback (most recent call last):

  File ~\.spyder-py3\temp.py:10 in <module>
    ab=input("Enter ")

  File ~\anaconda3\lib\site-packages\ipykernel\kernelbase.py:1075 in raw_input
    return self._input_request(

  File ~\anaconda3\lib\site-packages\ipykernel\kernelbase.py:1120 in _input_request
    raise KeyboardInterrupt("Interrupted by user") from None

KeyboardInterrupt: Interrupted by user

this issue i have also raised but not resolved

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\Roshini\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Roshini\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 278, in _handle_input_request
    return super(DebuggingWidget, self)._handle_input_request(msg)
  File "C:\Users\Roshini\anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 512, in _handle_input_request
    self._readline(msg['content']['prompt'], callback=callback, password=msg['content']['password'])
  File "C:\Users\Roshini\anaconda3\lib\site-packages\qtconsole\console_widget.py", line 2422, in _readline
    self._show_prompt(prompt, newline=False, separator=False)
TypeError: _show_prompt() got an unexpected keyword argument 'separator'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.3.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.0 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by Vinodhini12** [comment]
i tried this but still not working

**Comment by dalthviz** [comment]
Hi @Vinodhini12 , are you seeing the same traceback?

**Comment by Vinodhini12** [comment]
yes the issue!

**Comment by Vinodhini12** [comment]
i have completed the process of the commands given by the bot but the isssue is still not resolved!
the problem is again raising

**Comment by dalthviz** [comment]
Are you running Spyder from the Anaconda prompt and with the created env activated, right? I'm not totally sure what could be happening if you followed the instrctions step by step and now you are using the create env. Could you record a video or gif of the way you are now running Spyder, please? Let us know

**Comment by Vinodhini12** [comment]
yah i'm running spyder from anaconda prompt with the created enc activated

**Comment by dalthviz** [comment]
Could you post here the output you get when running `conda list` from an anaconda prompt with your env activated?

**Comment by Vinodhini12** [comment]
(base) C:\Users\Roshini>conda activate spyder-cf

(spyder-cf) C:\Users\Roshini>conda list
# packages in environment at C:\Users\Roshini\anaconda3\envs\spyder-cf:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
arrow                     1.2.2              pyhd8ed1ab_0    conda-forge
astroid                   2.11.5          py310h5588dad_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
autopep8                  1.6.0              pyhd8ed1ab_1    conda-forge
babel                     2.10.1             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bcrypt                    3.2.2           py310he2412df_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
black                     22.3.0             pyhd8ed1ab_0    conda-forge
bleach                    5.0.0              pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py310he2412df_1004    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.4.26            haa95532_0    anaconda
certifi                   2020.6.20          pyhd3eb1b0_3    anaconda
cffi                      1.15.0          py310hcbf9ad4_0    conda-forge
chardet                   4.0.0           py310h5588dad_3    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
click                     8.1.3           py310h5588dad_0    conda-forge
cloudpickle               2.1.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cookiecutter              2.1.1              pyh6c4a22f_0    conda-forge
cryptography              37.0.2          py310ha857299_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
debugpy                   1.6.0           py310h8a704f9_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
dill                      0.3.5.1            pyhd8ed1ab_0    conda-forge
docutils                  0.18.1          py310h5588dad_1    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
flake8                    4.0.1              pyhd8ed1ab_2    conda-forge
gettext                   0.19.8.1          ha2e2712_1008    conda-forge
gst-plugins-base          1.20.2               he07aa86_1    conda-forge
gstreamer                 1.20.2               hdff456e_1    conda-forge
icu                       70.1                 h0e60522_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
imagesize                 1.3.0              pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4          py310h5588dad_0    conda-forge
importlib_resources       5.7.1              pyhd8ed1ab_1    conda-forge
inflection                0.5.1              pyh9f0ad1d_0    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 6.13.1          py310hbbfc1a7_0    conda-forge
ipython                   7.33.0          py310h5588dad_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     5.10.1             pyhd8ed1ab_0    conda-forge
jedi                      0.18.1          py310h5588dad_1    conda-forge
jellyfish                 0.9.0           py310he2412df_1    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jinja2-time               0.2.0              pyhd8ed1ab_3    conda-forge
jpeg                      9e                   h8ffe710_1    conda-forge
jsonschema                4.6.0              pyhd8ed1ab_0    conda-forge
jupyter_client            7.3.1              pyhd8ed1ab_0    conda-forge
jupyter_core              4.10.0          py310h5588dad_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
keyring                   23.6.0          py310h5588dad_0    conda-forge
krb5                      1.19.3               h1176d77_0    conda-forge
lazy-object-proxy         1.7.1           py310he2412df_1    conda-forge
libclang                  14.0.4          default_h77d9078_0    conda-forge
libclang13                14.0.4          default_h77d9078_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.70.2               h3be07f2_4    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.2.2                h57928b3_0    conda-forge
libwebp-base              1.2.2                h8ffe710_1    conda-forge
libzlib                   1.2.12               h8ffe710_0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
markupsafe                2.1.1           py310he2412df_1    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py310he2412df_1005    conda-forge
mypy_extensions           0.4.3           py310h5588dad_5    conda-forge
mysql-connector-c         6.1.11               h33f27b4_1    anaconda
nbclient                  0.6.4              pyhd8ed1ab_1    conda-forge
nbconvert                 6.5.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            6.5.0              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          6.5.0              pyhd8ed1ab_0    conda-forge
nbformat                  5.4.0              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
numpydoc                  1.2.1              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1o               h2bbff1b_0
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandoc                    2.18                 h57928b3_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
paramiko                  2.11.0             pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h0e60522_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       22.1.2             pyhd8ed1ab_0    conda-forge
platformdirs              2.5.1              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0           py310h5588dad_3    conda-forge
prompt-toolkit            3.0.29             pyha770c72_0    conda-forge
psutil                    5.9.1           py310he2412df_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycodestyle               2.8.0              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydocstyle                6.1.1              pyhd8ed1ab_0    conda-forge
pyflakes                  2.4.0              pyhd8ed1ab_0    conda-forge
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
pylint                    2.14.1             pyhd8ed1ab_0    conda-forge
pyls-spyder               0.4.0              pyhd8ed1ab_0    conda-forge
pynacl                    1.5.0           py310h4f637d6_1    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.4          py310hbabf5d4_1    conda-forge
pyqt5-sip                 12.9.0          py310h8a704f9_1    conda-forge
pyqtwebengine             5.15.4          py310hbabf5d4_1    conda-forge
pyrsistent                0.18.1          py310he2412df_1    conda-forge
pysocks                   1.7.1           py310h5588dad_5    conda-forge
python                    3.10.4          h9a09f29_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.15.3             pyhd8ed1ab_0    conda-forge
python-lsp-black          1.2.1              pyhd8ed1ab_0    conda-forge
python-lsp-jsonrpc        1.0.0              pyhd8ed1ab_0    conda-forge
python-lsp-server         1.4.1              pyhd8ed1ab_1    conda-forge
python-slugify            6.1.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pywin32                   303             py310he2412df_0    conda-forge
pywin32-ctypes            0.2.0           py310h5588dad_1005    conda-forge
pyyaml                    6.0             py310he2412df_4    conda-forge
pyzmq                     23.1.0          py310h73ada01_0    conda-forge
qdarkstyle                3.0.3              pyhd8ed1ab_0    conda-forge
qstylizer                 0.2.1              pyhd8ed1ab_0    conda-forge
qt-main                   5.15.4               h467ea89_1    conda-forge
qt-webengine              5.15.4               h7325c83_3    conda-forge
qtawesome                 1.1.1              pyhd8ed1ab_0    conda-forge
qtconsole                 5.3.1              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.3.1              pyha770c72_0    conda-forge
qtpy                      2.1.0              pyhd8ed1ab_0    conda-forge
requests                  2.28.0             pyhd8ed1ab_0    conda-forge
rope                      1.1.1              pyhd8ed1ab_0    conda-forge
rtree                     1.0.0           py310h1cbd46b_1    conda-forge
setuptools                62.3.3          py310h5588dad_0    conda-forge
sip                       6.5.1           py310h8a704f9_2    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
sphinx                    5.0.1              pyh6c4a22f_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
spyder                    5.3.1           py310h5588dad_0    conda-forge
spyder-kernels            2.3.1           py310h5588dad_0    conda-forge
sqlite                    3.38.5               h8ffe710_0    conda-forge
text-unidecode            1.3                        py_0    conda-forge
textdistance              4.2.2              pyhd8ed1ab_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlkit                   0.11.0             pyha770c72_0    conda-forge
tornado                   6.1             py310he2412df_3    conda-forge
traitlets                 5.2.2.post1        pyhd8ed1ab_0    conda-forge
typed-ast                 1.5.4           py310he2412df_0    conda-forge
typing                    3.10.0.0           pyhd8ed1ab_0    conda-forge
typing_extensions         4.2.0              pyha770c72_1    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
ujson                     5.3.0           py310h8a704f9_0    conda-forge
unidecode                 1.3.4              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
watchdog                  2.1.8           py310h5588dad_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0           py310h5588dad_4    conda-forge
wrapt                     1.14.1          py310he2412df_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yapf                      0.32.0             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h8ffe710_0    conda-forge
zstd                      1.5.2                h6255e5f_1    conda-forge

(spyder-cf) C:\Users\Roshini>

**Comment by Vinodhini12** [comment]
<img width="960" alt="prompt" src="https://user-images.githubusercontent.com/69148519/173536669-b0016e32-5a75-4793-9df2-ce6b5ea54594.png">
<img width="960" alt="prompt1" src="https://user-images.githubusercontent.com/69148519/173536683-8f635df3-a0c9-453d-bd0f-d7278b35586f.png">
<img width="960" alt="prompt2" src="https://user-images.githubusercontent.com/69148519/173536693-4343579c-8154-44c6-80bd-347fb8746485.png">
<img width="960" alt="prompt3" src="https://user-images.githubusercontent.com/69148519/173536701-9ea7c449-b9f0-4a06-9734-1cd04f420c0c.png">
<img width="960" alt="prompt4" src="https://user-images.githubusercontent.com/69148519/173536707-50fe0436-db7b-4563-8261-2d6c8e2c2d05.png">
<img width="960" alt="prompt5" src="https://user-images.githubusercontent.com/69148519/173536712-bb114cb7-bd96-499e-99a4-3801336dddd9.png">
<img width="960" alt="prompt6" src="https://user-images.githubusercontent.com/69148519/173536721-d76c291d-66c0-4344-a642-b9bc1a993a6a.png">

**Comment by dalthviz** [comment]
I don't see anything strange in you `spyder-cf` env for Spyder to trigger the same `TypeError: _show_prompt() got an unexpected keyword argument 'separator'`(you have QtConsole and Spyder updated), sorry :/ 

Is the error you are seeing still the same as in the original post?

**Comment by Vinodhini12** [comment]
actually how can i connect mysql in this env what command should i use??

**Comment by Vinodhini12** [comment]
how can i import in spyder what syntax should i use
Actually I'm not sure if spyder is working properly or not coz while working with sql i got this error so if u tell me how to connect with spyder's new env i can come to a conclusion

**Comment by Vinodhini12** [comment]
Actually i want to connect tabulate module and mysql.connector in spyder,
In my base(root) env i was able to do it but not in this spyder
How can i install tabulate module and connect mysql

**Comment by Vinodhini12** [comment]
how to install mysql package and not pymysql

**Comment by Vinodhini12** [comment]
how can i import these in spyder, the syntax i used before is **import mysql.connector** but now its not working i even installed in the new env

**Comment by dalthviz** [comment]
Did you restart Spyder after installing?

**Comment by Vinodhini12** [comment]
should i reset or restart the spyder

**Comment by dalthviz** [comment]
Either restart Spyder, restart the Console kernel you are working on or create a new Console should help after you install in the `spyder-cf` env any new packages you want to import.

**Comment by Vinodhini12** [comment]
yes did still same problem

**Comment by Vinodhini12** [comment]
[
<img width="960" alt="Screenshot 2022-06-17 003933" src="https://user-images.githubusercontent.com/69148519/174147032-f8826248-3ae0-40c1-8c5f-c891432b407a.png">
](url)

**Comment by Vinodhini12** [comment]
![Untitled](https://user-images.githubusercontent.com/69148519/174147599-031775bc-4452-4eb2-9839-fafbf2ba8a2f.jpg)

**Comment by dalthviz** [comment]
If you run `conda list` the `mysql-connector-python` package is listed?

**Comment by Vinodhini12** [comment]
yes
<img width="960" alt="Screenshot " src="https://user-images.githubusercontent.com/69148519/174148414-3cbbff1b-e53c-4cf4-b319-c72e09599e2d.png">

**Comment by dalthviz** [comment]
You have `mysql-connector-c`, you need to install `mysql-connector-python`

**Comment by Vinodhini12** [comment]
Ok, Is it same for tabulate module

**Comment by Vinodhini12** [comment]
??

**Comment by Vinodhini12** [comment]
ok thank you so much
