### ISSUE TITLE
Spyder on Mavericks (10.9)

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1825]
_From [maurizio...@gmail.com](https://code.google.com/u/100126257068992071320/) on 2014-05-22T11:15:46Z_

Spyder Version:  2.2.1
Python Version:  2.7.6
Qt Version:      4.8.5, PyQt4 (API v1) 4.10.4 on Darwin 

What steps will reproduce the problem?

 1. Installed python/numpy/scipy/ipython via fink. Clean and smooth installation: Ipython console and notebook with inline plotting work perfectly.
2. Then installed by fink spyder-mac-p27 (or alternatively spyder-x11-p27). When invoked from bash, it gives an error with PyQt4 (although already installed), and cannot even launch sometimes. When it opens it cannot load also an IPython console (says it needs a version of IPython \<1.0 while current one is >2.0) and also gives inside the python shell:

Traceback (most recent call last):
  File "/sw/lib/python2.7/site-packages/spyderlib/scientific_startup.py", line 16, in \<module>
    from pylab import *  #analysis:ignore
  File "/sw/lib/python2.7/site-packages/pylab.py", line 1, in \<module>
    from matplotlib.pylab import *
  File "/sw/lib/python2.7/site-packages/matplotlib/pylab.py", line 269, in \<module>
    from matplotlib.pyplot import *
  File "/sw/lib/python2.7/site-packages/matplotlib/pyplot.py", line 98, in \<module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/sw/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 28, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/sw/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 13, in \<module>
    from backend_qt4 import QtCore, QtGui, FigureManagerQT, FigureCanvasQT,\
  File "/sw/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 25, in \<module>
    from qt4_compat import QtCore, QtGui, _getSaveFileName, __version__
  File "/sw/lib/python2.7/site-packages/matplotlib/backends/qt4_compat.py", line 80, in \<module>
    from PySide import QtCore, QtGui, __version__, __version_info__
ImportError: No module named PySide

Is there any simple workaround to this? I need necessarily to use fink as some of my packages are currently available and properly linked only through this latter. If I need to use other services such as MacPorts or Homebrew, then I don't want to install anything more than spyder (I don't need another python, ipython or whatever).

Thanks in advance for your help.

Maurizio

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1825_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-22T17:25:49Z_

Please consult the Fink Spyder maintainer about this, or open a bug in its bug tracker. I have no idea what could be happening.

Another idea is to download our native Mac App, and change its Python interpreter after installing it to point to the Fink one, as described here: http://stackoverflow.com/a/19813292/438386 Sorry for the inconveniences.

**Status:** WontFix

**Comment by spyder-issues-migrator** [comment]
_From [maurizio...@gmail.com](https://code.google.com/u/100126257068992071320/) on 2014-05-23T02:43:37Z_

Thanks for the prompt reply.
I am going to hear from the Fink guys then.

Concerning the second alternative, you refer to the DMG package that I can download from https://bitbucket.org/spyder-ide/spyderlib/downloads , am I correct? Then I guess that - looking at the size of the file - this will install spyder + all python and the rest again - and then I will just have to link everything from spyder as described at the link that you provided. Before I go for this solution, can I be sure that the DMG installer will not jepardize eventually my Fink-based python/ipython installation (as far as shared libs/dynlibs are involved at least)?

Thanks for the clarification and your patience.

Cheers,

M

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-24T06:36:07Z_

You're right, our DMG comes with a lot of packages (Pandas, SymPy, Matplotlib, IPython) but that's just for our users' convenience so that they can start using Scientific Python right away.

However, all is available only for the Spyder.app application, i.e. it doesn't touch nor changes anything from other Python installations in your system. In other words, it's pretty safe to use.
