### ISSUE TITLE
Variable explorer can not open a DataFrame

### ISSUE THREAD

**Issue by MarcoSimoes** [spyder-ide/spyder#18261]
### What steps will reproduce the problem?

When debugging a program, I've tried to see a DataFrame in a list of DataFrames and this error is generated.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/marco/pyenvs/scipy/lib/python3.6/site-packages/spyder/plugins/variableexplorer/widgets/collectionsdelegate.py", line 203, in createEditor
    if not editor.setup_and_check(value, title=key):
  File "/home/marco/pyenvs/scipy/lib/python3.6/site-packages/spyder/plugins/variableexplorer/widgets/dataframeeditor.py", line 940, in setup_and_check
    self.dataModel = DataFrameModel(data, parent=self)
  File "/home/marco/pyenvs/scipy/lib/python3.6/site-packages/spyder/plugins/variableexplorer/widgets/dataframeeditor.py", line 135, in __init__
    self.max_min_col_update()
  File "/home/marco/pyenvs/scipy/lib/python3.6/site-packages/spyder/plugins/variableexplorer/widgets/dataframeeditor.py", line 255, in max_min_col_update
    max_min = [vmax, vmin - 1]
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

## Versions

* Spyder version: 5.2.1 
* Python version: 3.6.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 5.4.0-117-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.1.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.16.3 (OK)
jedi >=0.17.2;<0.19.0         :  0.17.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.7.1 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.1 (OK)
pygments >=2.0                :  2.12.0 (OK)
pylint >=2.5.0                :  2.13.9 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.1.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  59.6.0 (OK)
sphinx >=0.6.6                :  4.3.2 (OK)
spyder_kernels >=2.2.0;<2.3.0 :  2.2.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
xdg >=0.26                    :  0.28 (OK)
zmq >=17                      :  23.1.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (OK)
numpy >=1.7                   :  None (OK)
pandas >=1.1.1                :  None (OK)
scipy >=0.17.0                :  None (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @MarcoSimoes, thanks for reporting. This error is fixed in our latest version (5.3.1), so please update.
