### ISSUE TITLE
Spyder keeps failing after 1st error in tkinter

### ISSUE THREAD

**Issue by pablorq** [spyder-ide/spyder#18299]
## Problem Description
An easy tkinter script works well until the 1st error, and then starts to fail. You can undo the modifications to return to the original code, but still fails.
It affects any script on Spyder.

### What steps reproduce the problem?

1. Copy the following code:
```python
import tkinter as tk

def main():
    
    icon = 'test-tk.png'
    root = tk.Tk()
    root.title('Test tkinter')
    img = tk.PhotoImage(file=icon)
    root.configure(width=img.width())
    root.resizable(width=False, height=False)
    root.iconphoto(True, tk.PhotoImage(file=icon))
    root.mainloop()
 
if __name__ == '__main__':
    main()
```

2. Run the code.
3. Everything is ok.
4. Modify the icon name to anything else to generate an error:
```python
    icon = 'test-tk1.png'
```
5. Run the code
6. It fails because the icon file doesn't exist. This is expected.
7. Undo the change
```python
    icon = 'test-tk.png'
```
7. Run the code
8. It fails.

### What is the expected output? What do you see instead?
After an error, like in this case pointing to wrong filename, it is expected to solve the filename error and be able to run the script without problem. But instead Spyder can't run the code correctly.
After fixing the wrong filename issue, running the script from the terminal (`pyhton [scriptname.py]` works well, even when Spyder still shows errors.
The only way to make Spyder to run again is closing and reopening Spyder.

### Paste Traceback/Error Below (if applicable)

```python-traceback
Python 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:38:57) [GCC 10.3.0]
Type "copyright", "credits" or "license" for more information.

IPython 7.33.0 -- An enhanced Interactive Python.

In [1]: runfile('/home/user/dev/test-tk.py', wdir='/home/user/dev')

In [2]: runfile('/home/user/dev/test-tk.py', wdir='/home/user/dev')
Traceback (most recent call last):

  File "/home/user/Apps/Anaconda/envs/spyderv5/lib/python3.10/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "/home/user/dev/test-tk.py", line 15, in <module>
    main()

  File "/home/user/dev/test-tk.py", line 8, in main
    img = tk.PhotoImage(file=icon)

  File "/home/user/Apps/Anaconda/envs/spyderv5/lib/python3.10/tkinter/__init__.py", line 4093, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)

  File "/home/user/Apps/Anaconda/envs/spyderv5/lib/python3.10/tkinter/__init__.py", line 4038, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)

TclError: couldn't open "test-tk1.png": no such file or directory


In [3]: runfile('/home/user/dev/test-tk.py', wdir='/home/user/dev')
Traceback (most recent call last):

  File "/home/user/Apps/Anaconda/envs/spyderv5/lib/python3.10/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "/home/user/dev/test-tk.py", line 15, in <module>
    main()

  File "/home/user/dev/test-tk.py", line 11, in main
    root.iconphoto(True, tk.PhotoImage(file=icon))

  File "/home/user/Apps/Anaconda/envs/spyderv5/lib/python3.10/tkinter/__init__.py", line 2154, in wm_iconphoto
    self.tk.call('wm', 'iconphoto', self._w, "-default", *args)

TclError: can't use "pyimage5" as iconphoto: not a photo image

```

## Versions

* Spyder version: 5.3.1
* Python version: 3.10.4 64-bit
* Qt version: 5.15.3
* PyQt version: 5.15.4
* Operating System name/version: Linux 5.13.0-48-generic (Ubuntu 21.10)

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.1.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.6.0 (OK)
keyring >=17.0.0              :  23.6.0 (OK)
nbconvert >=4.0               :  6.5.0 (OK)
numpydoc >=0.6.0              :  1.3.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.1 (OK)
pygments >=2.0                :  2.12.0 (OK)
pylint >=2.5.0                :  2.14.1 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.1 (OK)
qtpy >=2.1.0                  :  2.1.0 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  62.3.3 (OK)
sphinx >=0.6.6                :  5.0.1 (OK)
spyder_kernels >=2.3.1;<2.4.0 :  2.3.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.8 (OK)
xdg >=0.26                    :  0.28 (OK)
zmq >=22.1.0                  :  23.1.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  1.22.4 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by dalthviz** [comment]
Hi @pablorq thank you for the feedback! I was able to reproduce this but after checking for a while I think there is not much we can do about it :/. The main reason for this to happen is that raising the error leaves Tk GUI partially initialized which then collides with newer launches of the script/Tk and the only way to clean up the console is to do a kernel restart, opening a new console or as you where doing closing an reopening Spyder.

Some info regarding this is available at https://stackoverflow.com/a/69513119/15954282

Also, to prevent this to happen, and ensure the mainloop is always run you could try to do this:

```python
import tkinter as tk    


def main():
    icon = 'ILTQq.png'
    root = tk.Tk()

    try:
        root.title('Test tkinter')
        img = tk.PhotoImage(file=icon)
        root.configure(width=img.width())
        root.resizable(width=False, height=False)
        root.iconphoto(True, tk.PhotoImage(file=icon))
    finally:
        root.mainloop()


if __name__ == '__main__':
    main()

```

Let us know if something of the above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
