### ISSUE TITLE
Keyboard shortcuts, Reset to default values errors

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1829]
_From [Cybjit](https://code.google.com/u/Cybjit/) on 2014-05-24T12:55:00Z_

Spyder Version:  2.3.0rc (3680: r96ff231ec293 )
Python Version:  3.4.0
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Linux
IPython >=0.13  :  None (NOK)
pyflakes >=0.6.0:  0.7.3 (OK)
pep8 >=0.6      :  1.4.6 (OK)
pygments >=1.6  :  1.6 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  1.2.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
matplotlib >=1.0:  None (NOK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1. Enter Preferences, Keyboard shortcuts

2. Press 'Reset to default values'

3. Stack trace is printed in terminal.
Traceback (most recent call last):
  File "/home/cybjit/spyderlib/spyderlib/plugins/shortcuts.py", line 354, in reset_to_default
    self.main.apply_shortcuts()
  File "/home/cybjit/spyderlib/spyderlib/spyder.py", line 2053, in apply_shortcuts
    keyseq = QKeySequence( get_shortcut(context, name, default) )
  File "/home/cybjit/spyderlib/spyderlib/guiconfig.py", line 90, in get_shortcut
    return CONF.get('shortcuts', '&#37;s/&#37;s' &#37; (context, name), default=default)
  File "/home/cybjit/spyderlib/spyderlib/userconfig.py", line 371, in get
    raise cp.NoSectionError(section)
configparser.NoSectionError: No section: 'shortcuts'
Traceback (most recent call last):
  File "/usr/lib/python3.4/configparser.py", line 648, in options
    opts = self._sections[section].copy()
KeyError: 'shortcuts'

4. Close Preferences

5. Try to open Preferences again

6. Preferences is not opened. Stack trace is printed in terminal.
Traceback (most recent call last):
  File "/home/cybjit/spyderlib/spyderlib/spyder.py", line 2004, in edit_preferences
    widget.initialize()
  File "/home/cybjit/spyderlib/spyderlib/plugins/configdialog.py", line 62, in initialize
    self.setup_page()
  File "/home/cybjit/spyderlib/spyderlib/plugins/shortcuts.py", line 338, in setup_page
    self.table = ShortcutsTable(self)
  File "/home/cybjit/spyderlib/spyderlib/plugins/shortcuts.py", line 287, in __init__
    self.load_shortcuts()
  File "/home/cybjit/spyderlib/spyderlib/plugins/shortcuts.py", line 296, in load_shortcuts
    for context, name, keystr in iter_shortcuts():
  File "/home/cybjit/spyderlib/spyderlib/guiconfig.py", line 109, in iter_shortcuts
    for option in CONF.options('shortcuts'):
  File "/usr/lib/python3.4/configparser.py", line 650, in options
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'shortcuts' 

What is the expected output? What do you see instead?

 Shortcuts immediately reset.
Shortcuts only reset after restart. 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1829_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-06-11T18:40:31Z_

**Status:** Accepted  
  **Labels:** MS-v2.3 Cat-Editor

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-06-19T14:24:38Z_

This issue was closed by revision 38d8adebeaeb .

**Status:** Fixed
