### ISSUE TITLE
Connecting to remote kernel over SSH

### ISSUE THREAD

**Issue by afernando79** [spyder-ide/spyder#18315]
### What steps will reproduce the problem?

* Start a spyder-kernels server on a remote machine (WSL in this case but appears to be the same if a cloud compute instance)
* Select Consoles / Remote Kernel
* Configure as per instructions for remote connection via SSH
* Click connect (or equivalent)
* crash!

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\spyder\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 1097, in create_client_for_kernel
    self._create_client_for_kernel(connection_file, hostname, sshkey,
  File "C:\ProgramData\Anaconda3\envs\spyder\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 1924, in _create_client_for_kernel
    shellwidget.check_spyder_kernel()
  File "C:\ProgramData\Anaconda3\envs\spyder\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 265, in check_spyder_kernel
    self.silent_exec_method(code)
  File "C:\ProgramData\Anaconda3\envs\spyder\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 629, in silent_exec_method
    self._request_info['execute'][msg_id] = self._ExecutionRequest(msg_id,
TypeError: <lambda>() missing 1 required positional argument: 'hidden'
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.9.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.3.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=1.0                  :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.0 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by afernando79** [comment]
To add to this, I have used various versions of Spyder (5.3.1 included) with the corresponding spyder-kernels package with a similar effect. In later versions of the IDE, the crash reporter crashes and won't even produce the crash report - the process has to be terminated. Spyder v5.0.5 at least creates the crash report so I was able to generate this for you.

**Comment by afernando79** [comment]
As a follow-up, I can confirm using the following versions for both local and remote machines solved the problem:

| Spyder | Spyder-Kernels | SSH key encryption |
|--------|----------------|--------------------|
| 5.3.1  | 2.3.1          | RSA                |

Request: Can the [common illnesses](https://docs.spyder-ide.org/current/troubleshooting/common-illnesses.html) be updated to include the latest versions? I had gone to that page and couldn't see the appropriate versions needed.
