### ISSUE TITLE
Can't save files

### ISSUE THREAD

**Issue by Bose-Priya** [spyder-ide/spyder#18320]
### What steps will reproduce the problem?

I have run my algorithim and created quite a few plots. When I go to hit the save all button for the plots, Spyder keeps encountering this problem.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "D:\Desktop\Grad School\Virginia Tech\Research\Anaconda\lib\site-packages\spyder\plugins\plots\widgets\main_widget.py", line 537, in save_all_plots
    widget.thumbnails_sb.save_all_figures_as()
  File "D:\Desktop\Grad School\Virginia Tech\Research\Anaconda\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 646, in save_all_figures_as
    return self.save_all_figures_todir(dirname)
  File "D:\Desktop\Grad School\Virginia Tech\Research\Anaconda\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 662, in save_all_figures_todir
    save_figure_tofile(fig, fmt, figname)
  File "D:\Desktop\Grad School\Virginia Tech\Research\Anaconda\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 52, in save_figure_tofile
    with open(fname, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:/Desktop/Grad School/Virginia Tech/Research/Papers to Read/Scott and Megan/Potential Project Ideas/Mercury/Thermal Model/Mercury using STO based model Grott Parameters/Inner Core Parameter Test/Simple Q term (sheet 2)/Test 2\\Figure 2022-06-16 123248 (10).png'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (OK)
matplotlib >=2.0.0            :  3.2.2 (OK)
numpy >=1.7                   :  1.21.2 (OK)
pandas >=1.1.1                :  None (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by Bose-Priya** [comment]
> Hi @Bose-Priya, could you please try to install a newer version of spyder? Here are some instructions:
> 
> 1. Use our Windows or Mac installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
> 2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:`conda create -n spyder-cf -c conda-forge spyder jupyter_client=7.3.1``conda activate spyder-cf``spyder`
> 
> Please let us know if updating the Spyder version solves your issue

If I only use Spyder through the Anaconda Environemnet already, do I have to reinstall it, or can I just proceed with step 2?

Thanks,
Bose-Priya

**Comment by andfoy** [comment]
You'll need to proceed to step 2 in that case

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by kt-altyn** [comment]
this is the solution:
https://stackoverflow.com/questions/49165589/python-spyder-ide-plot-to-file-only
