### ISSUE TITLE
changed maximum allowed length in preferences/lining | Code style

### ISSUE THREAD

**Issue by Srilthe** [spyder-ide/spyder#18347]
### What steps will reproduce the problem?

changed maximum allowed length in preferences/lining | Code style
to 120

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/srilthe/.local/lib/python3.8/site-packages/spyder/plugins/editor/plugin.py", line 419, in _rpc_call
    meth(*args, **kwargs)
  File "/home/srilthe/.local/lib/python3.8/site-packages/spyder/plugins/editor/plugin.py", line 1307, in update_source_menu
    state = self.get_option(opt, section=section)
  File "/home/srilthe/.local/lib/python3.8/site-packages/spyder/api/plugins/old_api.py", line 111, in get_option
    return super(BasePlugin, self)._get_option(option, default,
  File "/home/srilthe/.local/lib/python3.8/site-packages/spyder/plugins/base.py", line 71, in _get_option
    return CONF.get(section, option, default)
  File "/home/srilthe/.local/lib/python3.8/site-packages/spyder/config/manager.py", line 460, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option ('editor', 'underline_errors') in section: 'editor'
```

## Versions

* Spyder version: 5.3.0 
* Python version: 3.8.10
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 5.15.0-33-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.32.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.17.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  18.0.1 (OK)
nbconvert >=4.0               :  6.4.2 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
parso >=0.7.0;<0.9.0          :  0.7.1 (OK)
pexpect >=4.4.0               :  4.6.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.5.1 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.0 (OK)
qtpy >=2.0.1                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  57.5.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.3.0;<2.4.0 :  2.3.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.26 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.22.3 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @Srilthe, thanks for reporting. This error will be fixed in our next version (5.3.2), to be released at the beginning of July.

For now you can ignore it because it's harmless.
