### ISSUE TITLE
Qt graphics not work

### ISSUE THREAD

**Issue by edombek** [spyder-ide/spyder#18404]
## Problem Description
Qt graphics not work in spyder ipython console

### What steps reproduce the problem?

1. Activate graphics backend Qt5

### What is the expected output? What do you see instead?
Graphics not work, error

### Paste Traceback/Error Below (if applicable)

```python-traceback

Python 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0]
Type "copyright", "credits" or "license" for more information.

IPython 8.4.0 -- An enhanced Interactive Python.

Populating the interactive namespace from numpy and matplotlib

ERROR:tornado.application:Exception in callback functools.partial(<function Kernel.enter_eventloop.<locals>.advance_eventloop at 0x7f86e20a84c0>)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/usr/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 455, in advance_eventloop
    eventloop(self)
  File "/usr/lib/python3.10/site-packages/ipykernel/eventloops.py", line 141, in loop_qt5
    return loop_qt4(kernel)
  File "/usr/lib/python3.10/site-packages/ipykernel/eventloops.py", line 118, in loop_qt4
    kernel.app = get_app_qt4([" "])
  File "/usr/lib/python3.10/site-packages/IPython/lib/guisupport.py", line 119, in get_app_qt4
    app = QtGui.QApplication(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/spyder_kernels/customize/spydercustomize.py", line 168, in __init__
    super(SpyderQApplication, self).__init__(*args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type

```

## Versions

* Spyder version: 5.3.1
* Python version: 3.10.5
* Qt version: 5.15.5
* PyQt version: 5.15.7
* Operating System name/version: archlinux Linux 5.18.5 x86_64

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.1.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1              :  8.4.0 (OK)
jedi >=0.17.2                 :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.5.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0                 :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.12.0 (OK)
pylint >=2.5.0                :  2.14.3 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1                 :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2            :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.0 (OK)
qtconsole >=5.3.0             :  5.3.0 (OK)
qtpy >=2.1.0                  :  2.1.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.3.0 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.3.1;<2.4.0 :  2.3.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  0.10.7 (OK)
xdg >=0.26                    :  0.28 (OK)
zmq >=22.1.0                  :  23.1.0 (OK)

# Optional:
cython >=0.21                 :  0.29.30 (OK)
matplotlib >=3.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.22.4 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.8.1 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by edombek** [comment]
the problem was solved by removing qt4, I don’t understand why the search for libraries comes from older versions
