### ISSUE TITLE
Save Button Issue

### ISSUE THREAD

**Issue by rbccprg22** [spyder-ide/spyder#18477]
### What steps will reproduce the problem?

The error occurs after clicking the save button in the upper panel. Though the file is being saved just fine. The "Ctrl+S" method does not produce the error.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\MySoftware\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1904, in _save_file
    self.modification_changed(index=index)
  File "C:\MySoftware\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2360, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\MySoftware\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1904, in _save_file
    self.modification_changed(index=index)
  File "C:\MySoftware\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2360, in modification_changed
    finfo = self.data[index]
IndexError: list index out of range
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.7
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.1.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.7.4 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.2.2 (OK)
qtpy >=1.5.0                  :  1.11.2 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  1.0.2 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.1 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  None (OK)
```

**Comment by dalthviz** [comment]
Hi @rbccprg22 thank you for the feedback! This seems like a duplicate of https://github.com/spyder-ide/spyder/issues/14639 To check if that is the case you will need to update to Spyder 5.3.1 where a fix for that issue was released. For that you will need to create a new conda environment using the conda-forge channel. You can do that by running from an Anaconda prompt something like this:

```
conda create -n spyder-cf -c conda-forge spyder
conda activate spyder
spyder
```

Runnnig the above will create for you a new env `spyder-cf` with Spyder 5.3.1 (latest release available at the moment).

Let us know if something of the above helps!

**Comment by rbccprg22** [comment]
Hey @dalthviz, thank you for the quick response -- it helped!
