### ISSUE TITLE
Preferences panel don't appear

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1847]
_From [olivier....@gmail.com](https://code.google.com/u/109001114093748127605/) on 2014-06-10T05:35:40Z_

Spyder Version:  2.3.0rc
Python Version:  2.7.7
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Darwin
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=0.13  :  2.1.0 (OK)
pygments >=1.6  :  1.6 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  2.1.1 (OK)
rope >=0.9.2    :  0.10.2 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1. Start spyder from the terminal with the command line spider;
2. In the menu bar of spyder go to Tools and click on preferences. 

What is the expected output? What do you see instead?

 I expect to see the preferences window but nothing appears and instead in the internal consol window, I have an error report :

Traceback (most recent call last):
  File "/Users/Oliv/anaconda/lib/python2.7/site-packages/spyderlib/spyder.py", line 2004, in edit_preferences
    widget.initialize()
  File "/Users/Oliv/anaconda/lib/python2.7/site-packages/spyderlib/plugins/configdialog.py", line 63, in initialize
    self.load_from_conf()
  File "/Users/Oliv/anaconda/lib/python2.7/site-packages/spyderlib/plugins/configdialog.py", line 276, in load_from_conf
    lineedit.setText(self.get_option(option, default))
  File "/Users/Oliv/anaconda/lib/python2.7/site-packages/spyderlib/plugins/configdialog.py", line 45, in get_option
    return CONF.get(self.CONF_SECTION, option, default)
  File "/Users/Oliv/anaconda/lib/python2.7/site-packages/spyderlib/userconfig.py", line 379, in get
    self.set(section, option, default)
  File "/Users/Oliv/anaconda/lib/python2.7/site-packages/spyderlib/userconfig.py", line 433, in set
    self._save()
  File "/Users/Oliv/anaconda/lib/python2.7/site-packages/spyderlib/userconfig.py", line 126, in _save
    _write_file(fname)
  File "/Users/Oliv/anaconda/lib/python2.7/site-packages/spyderlib/userconfig.py", line 119, in _write_file
    self.write(configfile)
  File "/Users/Oliv/anaconda/python.app/Contents/lib/python2.7/ConfigParser.py", line 412, in write
    key = " = ".join((key, str(value).replace('\n', '\n\t')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0301' in position 40: ordinal not in range(128)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1847_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-26T09:47:52Z_

Please run in a terminal

    spyder --reset

and try again

**Comment by spyder-issues-migrator** [comment]
_From [olivier....@gmail.com](https://code.google.com/u/109001114093748127605/) on 2014-08-27T01:03:14Z_

It worked. Thank you.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-27T06:12:35Z_

Great! Sorry for the huge delay in giving you an answer to your problem.

**Status:** WontFix

**Comment by spyder-issues-migrator** [comment]
_From [tsa...@gmail.com](https://code.google.com/u/107847032315766261726/) on 2014-11-21T05:18:09Z_

Hello guys,

In which folder in terminal? mine is not working, ether in the folder that I have Spyder.app (Applications), ither in the spyder package contents.
It always says "-bash: spyder: command not found"
(as you understand I have MAC)

Thank you!!!!

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-21T10:44:42Z_

@-tsafod: I already fixed this problem. The fix will be present in 2.3.2. Just for the record, this was fixed in revision b653a29d3238 .

To make things work for now you need to open a terminal and run

rm -Rf ~/.spyder2

**Status:** Fixed  
  **Labels:** MS-v2.3.2 Cat-Settings

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-22T13:19:37Z_

issue #2060 has been merged into this issue.
