### ISSUE TITLE
spyder-kernels = 2.3.1 not working

### ISSUE THREAD

**Issue by miguel-graindata** [spyder-ide/spyder#18498]
## Problem Description
I created a new conda environment (using miniconda) with python=3.9 and installed spyder-kernels=2.3.1 from conda-forge to be able to sue this new environment in the spyder standalone app (v5.3.1) in Windows 11, however, I get the following error in the console when starting Spyder:

```python-traceback
Traceback (most recent call last):
File "C:\Users\Gebruiker\miniconda3\envs\miguel_spyder\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\Gebruiker\miniconda3\envs\miguel_spyder\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Users\Gebruiker\miniconda3\envs\miguel_spyder\lib\site‑packages\spyder_kernels\console\__main__.py", line 22, in
from spyder_kernels.console import start
File "C:\Users\Gebruiker\miniconda3\envs\miguel_spyder\lib\site‑packages\spyder_kernels\console\start.py", line 21, in
import ipykernel
File "C:\Users\Gebruiker\miniconda3\envs\miguel_spyder\lib\site‑packages\ipykernel\__init__.py", line 5, in
from .connect import * # noqa
File "C:\Users\Gebruiker\miniconda3\envs\miguel_spyder\lib\site‑packages\ipykernel\connect.py", line 11, in
import jupyter_client
File "C:\Users\Gebruiker\miniconda3\envs\miguel_spyder\lib\site‑packages\jupyter_client\__init__.py", line 8, in
from .asynchronous import AsyncKernelClient # noqa
File "C:\Users\Gebruiker\miniconda3\envs\miguel_spyder\lib\site‑packages\jupyter_client\asynchronous\__init__.py", line 1, in
from .client import AsyncKernelClient # noqa
File "C:\Users\Gebruiker\miniconda3\envs\miguel_spyder\lib\site‑packages\jupyter_client\asynchronous\client.py", line 6, in
from jupyter_client.channels import HBChannel
File "C:\Users\Gebruiker\miniconda3\envs\miguel_spyder\lib\site‑packages\jupyter_client\channels.py", line 12, in
import zmq.asyncio
File "C:\Users\Gebruiker\miniconda3\envs\miguel_spyder\lib\site‑packages\zmq\__init__.py", line 103, in
from zmq import backend
File "C:\Users\Gebruiker\miniconda3\envs\miguel_spyder\lib\site‑packages\zmq\backend\__init__.py", line 31, in
raise original_error from None
File "C:\Users\Gebruiker\miniconda3\envs\miguel_spyder\lib\site‑packages\zmq\backend\__init__.py", line 26, in
_ns = select_backend(first)
File "C:\Users\Gebruiker\miniconda3\envs\miguel_spyder\lib\site‑packages\zmq\backend\select.py", line 31, in select_backend
mod = import_module(name)
File "C:\Users\Gebruiker\miniconda3\envs\miguel_spyder\lib\importlib\__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "C:\Users\Gebruiker\miniconda3\envs\miguel_spyder\lib\site‑packages\zmq\backend\cython\__init__.py", line 6, in
from . import (
ImportError: DLL load failed while importing _device: The specified module could not be found.
```

## Versions
* Conda version: 4.13.0
* Spyder version: 5.3.1 
* Python version: 3.9.12
* Operating System name/version:  Windows 11

Any ideas how to solve this problem?

**Comment by Superberti** [comment]
I've exactly the same problem here. Same versions, same environment. On WIN10. SPYDER 5.3.1 is not able to work with this virtual-env, although spyder-kernels 2.3.1 are installed.
Sorry, no idea what's going wrong here.

**Comment by dalthviz** [comment]
Hi @Superberti and @miguel-graindata, thank you for the feedback! I'm not totally sure but maybe the issue was related with #18594

None the less Spyder 5.3.2 is already available so please try to update and use spyder-kernels 2.3.2 in your envs. Let us know if the update helps!

**Comment by Superberti** [comment]
Hi, now I cleaned up my virtual env and tested it with Spyder 5.3.2 and 2.3.2.
Unfortunately, I got the same results ;-( It's not working.

Bye,
Oliver

**Comment by dalthviz** [comment]
Thank you for testing @Superberti ! Could you share with us an export of the env that is failing for you? I checked locally connecting the standalone version with a new env with spyder-kernels 2.3.2 from conda-forge and seems like the standalone Spyder version 5.3.2 on Windows starts normally.

Just in case the env I created for testing: 

## Command for creation

    conda create -n kernel-env -c conda-forge spyder-kernels

## Env details/export (`conda env export`) output

<details>

```
name: kernel-env
channels:
  - conda-forge
  - defaults
dependencies:
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2022.6.15=h5b45459_0
  - cloudpickle=2.1.0=pyhd8ed1ab_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - debugpy=1.6.0=py310h8a704f9_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - ipykernel=6.15.1=pyh025b116_0
  - ipython=7.33.0=py310h5588dad_0
  - jedi=0.18.1=py310h5588dad_1
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=4.10.0=py310h5588dad_0
  - libffi=3.4.2=h8ffe710_5
  - libsodium=1.0.18=h8d14728_1
  - libzlib=1.2.12=h8ffe710_2
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - openssl=3.0.5=h8ffe710_0
  - packaging=21.3=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=22.1.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.30=pyha770c72_0
  - psutil=5.9.1=py310he2412df_0
  - pygments=2.12.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - python=3.10.5=hcf16a7b_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pywin32=303=py310he2412df_0
  - pyzmq=23.2.0=py310h73ada01_0
  - setuptools=63.2.0=py310h5588dad_0
  - six=1.16.0=pyh6c4a22f_0
  - spyder-kernels=2.3.2=py310h5588dad_0
  - sqlite=3.39.1=h8ffe710_0
  - tk=8.6.12=h8ffe710_0
  - tornado=6.2=py310he2412df_0
  - traitlets=5.3.0=pyhd8ed1ab_0
  - tzdata=2022a=h191b570_0
  - ucrt=10.0.20348.0=h57928b3_0
  - vc=14.2=hb210afc_6
  - vs2015_runtime=14.29.30037=h902a5da_6
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h62dcd97_1
  - zeromq=4.3.4=h0e60522_1
prefix: C:\Users\dalth\anaconda3\envs\kernel-env
```

</details>

**Comment by Superberti** [comment]
Hi,
I created a new environment, here's the output of conda env export:
```
(kernel-env) C:\Users\rutsch>conda env export
name: kernel-env
channels:
  - conda-forge
  - defaults
dependencies:
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2022.6.15=h5b45459_0
  - cloudpickle=2.1.0=pyhd8ed1ab_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - debugpy=1.6.0=py310h8a704f9_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - ipykernel=6.15.1=pyh025b116_0
  - ipython=7.33.0=py310h5588dad_0
  - jedi=0.18.1=py310h5588dad_1
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=4.11.0=py310h5588dad_0
  - libffi=3.4.2=h8ffe710_5
  - libsodium=1.0.18=h8d14728_1
  - libzlib=1.2.12=h8ffe710_2
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - openssl=3.0.5=h8ffe710_0
  - packaging=21.3=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=22.1.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.30=pyha770c72_0
  - psutil=5.9.1=py310he2412df_0
  - pygments=2.12.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - python=3.10.5=hcf16a7b_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pywin32=303=py310he2412df_0
  - pyzmq=23.2.0=py310h73ada01_0
  - setuptools=63.2.0=py310h5588dad_0
  - six=1.16.0=pyh6c4a22f_0
  - spyder-kernels=2.3.2=py310h5588dad_0
  - sqlite=3.39.1=h8ffe710_0
  - tk=8.6.12=h8ffe710_0
  - tornado=6.2=py310he2412df_0
  - traitlets=5.3.0=pyhd8ed1ab_0
  - tzdata=2022a=h191b570_0
  - ucrt=10.0.20348.0=h57928b3_0
  - vc=14.2=hb210afc_6
  - vs2015_runtime=14.29.30037=h902a5da_6
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h62dcd97_1
  - zeromq=4.3.4=h0e60522_1
prefix: C:\Users\rutsch\Miniconda3\envs\kernel-env
```
Additionally I installed matplotlib, nothing else. If I switch the kernel to the new environment I'll get:

```
Traceback (most recent call last):
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\site‑packages\spyder_kernels\console\__main__.py", line 24, in
start.main()
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\site‑packages\spyder_kernels\console\start.py", line 295, in main
import_spydercustomize()
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\site‑packages\spyder_kernels\console\start.py", line 48, in import_spydercustomize
import spydercustomize # noqa
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 25, in
from IPython.core.getipython import get_ipython
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\site‑packages\IPython\__init__.py", line 55, in
from .core.application import Application
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\site‑packages\IPython\core\application.py", line 25, in
from IPython.core import release, crashhandler
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\site‑packages\IPython\core\crashhandler.py", line 27, in
from IPython.core import ultratb
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\site‑packages\IPython\core\ultratb.py", line 116, in
from IPython.utils import path as util_path
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\site‑packages\IPython\utils\path.py", line 17, in
from IPython.utils.process import system
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\site‑packages\IPython\utils\process.py", line 15, in
from ._process_win32 import system, getoutput, arg_split, check_pid
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\site‑packages\IPython\utils\_process_win32.py", line 20, in
import ctypes
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\ctypes\__init__.py", line 8, in
from _ctypes import Union, Structure, Array
ImportError: DLL load failed while importing _ctypes: Das angegebene Modul wurde nicht gefunden.
Traceback (most recent call last):
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\runpy.py", line 86, in _run_code
exec(code, run_globals)
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\site‑packages\spyder_kernels\console\__main__.py", line 24, in
start.main()
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\site‑packages\spyder_kernels\console\start.py", line 295, in main
import_spydercustomize()
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\site‑packages\spyder_kernels\console\start.py", line 48, in import_spydercustomize
import spydercustomize # noqa
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 25, in
from IPython.core.getipython import get_ipython
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\site‑packages\IPython\__init__.py", line 55, in
from .core.application import Application
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\site‑packages\IPython\core\application.py", line 25, in
from IPython.core import release, crashhandler
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\site‑packages\IPython\core\crashhandler.py", line 27, in
from IPython.core import ultratb
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\site‑packages\IPython\core\ultratb.py", line 116, in
from IPython.utils import path as util_path
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\site‑packages\IPython\utils\path.py", line 17, in
from IPython.utils.process import system
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\site‑packages\IPython\utils\process.py", line 15, in
from ._process_win32 import system, getoutput, arg_split, check_pid
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\site‑packages\IPython\utils\_process_win32.py", line 20, in
import ctypes
File "C:\Users\rutsch\Miniconda3\envs\kernel‑env\lib\ctypes\__init__.py", line 8, in
from _ctypes import Union, Structure, Array
ImportError: DLL load failed while importing _ctypes: Das angegebene Modul wurde nicht gefunden.
```

**Comment by dalthviz** [comment]
Seems like the error changed @Superberti ? Seems like now is something about `ctypes` not being able to load a DLL.

Are you able to import `ctypes` from the Python interpreter from an Anaconda prompt with the env activated? If you are unable maybe checking the usage of the [`conda clean`](https://docs.conda.io/projects/conda/en/latest/commands/clean.html) command could be worthy (to clean the packages cache).

Checked locally installing `matplotlib` with the env I was doing the tests and is working for my with the Windows standalone installer. I'm able to import `matplotlib` and `ctypes` without issue. Just in case the env details after installing `matplotlib`:

<details>

```

# packages in environment at C:\Users\dalth\anaconda3\envs\kernel-env:
#
# Name                    Version                   Build  Channel
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h8ffe710_7    conda-forge
brotli-bin                1.0.9                h8ffe710_7    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.6.15            h5b45459_0    conda-forge
certifi                   2022.6.15       py310h5588dad_0    conda-forge
cloudpickle               2.1.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
debugpy                   1.6.0           py310h8a704f9_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
fonttools                 4.34.4          py310he2412df_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
gettext                   0.19.8.1          ha2e2712_1008    conda-forge
glib                      2.72.1               h7755175_0    conda-forge
glib-tools                2.72.1               h7755175_0    conda-forge
gst-plugins-base          1.20.3               he07aa86_0    conda-forge
gstreamer                 1.20.3               hdff456e_0    conda-forge
icu                       70.1                 h0e60522_0    conda-forge
intel-openmp              2022.1.0          h57928b3_3787    conda-forge
ipykernel                 6.15.1             pyh025b116_0    conda-forge
ipython                   7.33.0          py310h5588dad_0    conda-forge
jedi                      0.18.1          py310h5588dad_1    conda-forge
jpeg                      9e                   h8ffe710_2    conda-forge
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.0          py310h5588dad_0    conda-forge
kiwisolver                1.4.4           py310h476a331_0    conda-forge
krb5                      1.19.3               h1176d77_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libblas                   3.9.0              15_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_7    conda-forge
libbrotlidec              1.0.9                h8ffe710_7    conda-forge
libbrotlienc              1.0.9                h8ffe710_7    conda-forge
libcblas                  3.9.0              15_win64_mkl    conda-forge
libclang                  14.0.6          default_h77d9078_0    conda-forge
libclang13                14.0.6          default_h77d9078_0    conda-forge
libdeflate                1.12                 h8ffe710_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.72.1               h3be07f2_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0              15_win64_mkl    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.37               h1d00b33_3    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libtiff                   4.4.0                h2ed3b44_1    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.2.3                h8ffe710_0    conda-forge
libwebp-base              1.2.3                h8ffe710_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libzlib                   1.2.12               h8ffe710_2    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
matplotlib                3.5.2           py310h5588dad_0    conda-forge
matplotlib-base           3.5.2           py310h79a7439_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
numpy                     1.23.1          py310h8a5b91a_0    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1q               h8ffe710_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h0e60522_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0           py310h767b3fd_0    conda-forge
pip                       22.1.2             pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
prompt-toolkit            3.0.30             pyha770c72_0    conda-forge
psutil                    5.9.1           py310he2412df_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7          py310hbabf5d4_0    conda-forge
pyqt5-sip                 12.11.0         py310h8a704f9_0    conda-forge
python                    3.10.5          h9a09f29_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pywin32                   303             py310he2412df_0    conda-forge
pyzmq                     23.2.0          py310h73ada01_0    conda-forge
qt-main                   5.15.4               h467ea89_2    conda-forge
setuptools                63.2.0          py310h5588dad_0    conda-forge
sip                       6.6.2           py310h8a704f9_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
spyder-kernels            2.3.2           py310h5588dad_0    conda-forge
sqlite                    3.39.1               h8ffe710_0    conda-forge
tbb                       2021.5.0             h2d74725_1    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tornado                   6.2             py310he2412df_0    conda-forge
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
unicodedata2              14.0.0          py310he2412df_1    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zlib                      1.2.12               h8ffe710_2    conda-forge
zstd                      1.5.2                h6255e5f_2    conda-forge

```

</details>

Not sure what else to suggest since I haven't been able to reproduce this but if you have any new info let us know!

**Comment by Superberti** [comment]
With the kernel-env activated I'll get the same error:

```
(kernel-env) C:\Users\rutsch\.spyder-py3>python temp.py
Traceback (most recent call last):
  File "C:\Users\rutsch\.spyder-py3\temp.py", line 2, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed while importing _ctypes: Das angegebene Modul wurde nicht gefunden.
```

And yes, it's a different kind of error but I don't know what I made wrong.
I cleaned up everything with `conda clean -a` and created another environment but the ctypes error still remains.

Bye,
Oliver

**Comment by Superberti** [comment]
So I've found the reason!
I invested some time with the famous ProcessMonitor to see what dll is missing (unfortunately the error message doesn't help as it hides the dll name). 
So the python process tries to load "ffi.dll" from various places but this fails as the installed (by conda) dll has the name "ffi-8.dll". Renaming this dll to "ffi.dll" solves the problem and I'm able to use the environment in spyder again.
But it also looks that I've to install the spyder-kernels from conda-forge, right?

Bye,
Oliver

**Comment by dalthviz** [comment]
Thank you for the new info @Superberti ! Glad is working for you :+1: And yes to get the up to date version of Spyder-kernels and Spyder you need to use the conda-forge channel. The thing is that the default anaconda channel just goes up to Spyder 5.1.5 and Spyder-kernels 2.2.1 

Since this seems more like a specific miniconda/conda setup issue I will close this one but if you have more info regarding this let us know!
