### ISSUE TITLE
Crash on start during Ubuntu Lucid 10.04

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#185]
_From [zman...@gmail.com](https://code.google.com/u/103103724147507297760/) on 2010-03-31T13:37:56Z_

Spyderlib crashes on start on Lucid

Traceback

Start of MainWindow constructor
Initializing...
End of MainWindow constructor
*** Start of MainWindow setup ***
Loading workspace...
Loading editor plugin...
Loading workspace plugin...
Loading history plugin...
Loading inspector plugin...
Loading online help plugin...
Loading pylint plugin...
Setting up main window...
Traceback (most recent call last):
  File "/usr/local/bin/spyder", line 3, in \<module>
    spyder.main()
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/spyder.py", line 
1624, in main
    mainwindow = run_spyder(*args)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/spyder.py", line 
1589, in run_spyder
    main.setup()
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/spyder.py", line 
610, in setup
    self.extconsole = ExternalConsole(self, self.commands)
  File "/usr/local/lib/python2.6/dist-
packages/spyderlib/plugins/externalconsole.py", line 50, in __init__
    PluginWidget.__init__(self, parent)
  File "/usr/local/lib/python2.6/dist-
packages/spyderlib/plugins/__init__.py", line 144, in __init__
    PluginMixin.__init__(self, parent)
  File "/usr/local/lib/python2.6/dist-
packages/spyderlib/plugins/__init__.py", line 52, in __init__
    self.menu_actions, self.toolbar_actions = self.set_actions()
  File "/usr/local/lib/python2.6/dist-
packages/spyderlib/plugins/externalconsole.py", line 276, in set_actions
    icontext_action.setChecked( CONF.get(self.ID, 'show_icontext') )
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/userconfig.py", 
line 226, in get
    raise RuntimeError("Unknown option &#37;r" &#37; option)
RuntimeError: Unknown option 'show_icontext'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/spyder.py", line 
890, in closing
    CONF.set('main', prefix+'size', (size.width(), size.height()))
AttributeError: 'NoneType' object has no attribute 'width'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/spyder.py", line 
890, in closing
    CONF.set('main', prefix+'size', (size.width(), size.height()))
AttributeError: 'NoneType' object has no attribute 'width'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=185_

**Comment by spyder-issues-migrator** [comment]
_From [zman...@gmail.com](https://code.google.com/u/103103724147507297760/) on 2010-03-31T11:38:33Z_

This version is from the source tree.

**Comment by spyder-issues-migrator** [comment]
_From [zman...@gmail.com](https://code.google.com/u/103103724147507297760/) on 2010-04-02T16:15:12Z_

Any thoughts on this? I am missing this editor. 

Both 1.0.3 and 1.1.0alpha crash on start for me. If I have time,I'll walk back through 
the revision tree and see exactly where it breaks.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-04-03T07:22:00Z_

Fixed in mercurial repository.
Sorry for the delay... https://code.google.com/p/spyderlib/source/detail r= aa7210f9a2af2ec98169dcc413a8d47f6522b0b3

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [zman...@gmail.com](https://code.google.com/u/103103724147507297760/) on 2010-04-03T10:01:23Z_

Wonderful. Excellent work. 

When this broke for me, I went shopping again for a python editor. Ended up in vim. 
But definitely missed spyder.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-04-03T11:04:56Z_

I'm glad you missed it :)

Please do not hesitate to fill out Issue forms in the future -- for bug reports as well 
as feature requests.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-18T08:51:14Z_

This issue was closed by revision ce3d4d0af8a5 .
