### ISSUE TITLE
the run issue in Spyder 5.1.5

### ISSUE THREAD

**Issue by NiuJun-1015** [spyder-ide/spyder#18524]
When I click 'run' in Spyder 5.1.5 with Python3.9. The issue occurred at once.

The issue report: 

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 278, in _handle_input_request
    return super(DebuggingWidget, self)._handle_input_request(msg)
  File "C:\Anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 512, in _handle_input_request
    self._readline(msg['content']['prompt'], callback=callback, password=msg['content']['password'])
  File "C:\Anaconda3\lib\site-packages\qtconsole\console_widget.py", line 2422, in _readline
    self._show_prompt(prompt, newline=False, separator=False)
TypeError: _show_prompt() got an unexpected keyword argument 'separator'

**Comment by NiuJun-1015** [comment]
I already update to the 7.3.1, but the issue is existed
