### ISSUE TITLE
Running in external system terminals is not working on Windows and Python 3

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1856]
_From [lhe...@gmail.com](https://code.google.com/u/104812375050639788775/) on 2014-06-18T08:04:35Z_

Spyder Version:  2.3.0beta2
Python Version:  3.3.5
Qt Version    :  4.8.4, PyQt4 (API v2) 4.9.6 on Windows
pyflakes >=0.6.0:  None (OK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  2.0.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  1.1.0 (OK) 

What steps will reproduce the problem?

 1.install winpython 3.3.5.0  (note: no python related environment vars are set)
2.create any program, e.g. just:  print('test')
3.set the run settings to "external system terminal"
3.select run 

What is the expected output? What do you see instead?

 The program does not run, instead the internal console pops up, with this message:

Inspect Spyder internals:
  spy.app, spy.window, dir(spy)
\>>> Traceback (most recent call last):
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\plugins\editor.py", line 2006, in edit_run_configurations
    self.run_file()
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\plugins\editor.py", line 2048, in run_file
    self.re_run_file()
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\plugins\editor.py", line 2088, in re_run_file
    systerm)
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\spyder.py", line 1793, in open_external_console
    interact, debug, python_args)
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\utils\programs.py", line 166, in run_python_script_in_terminal
    cwd=encoding.to_fs_from_unicode(wdir))
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\subprocess.py", line 819, in __init__
    restore_signals, start_new_session)
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\subprocess.py", line 1063, in _execute_child
    args = list2cmdline(args)
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\subprocess.py", line 632, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'int' is not iterable
Traceback (most recent call last):
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\plugins\editor.py", line 2006, in edit_run_configurations
    self.run_file()
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\plugins\editor.py", line 2048, in run_file
    self.re_run_file()
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\plugins\editor.py", line 2088, in re_run_file
    systerm)
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\spyder.py", line 1793, in open_external_console
    interact, debug, python_args)
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\utils\programs.py", line 166, in run_python_script_in_terminal
    cwd=encoding.to_fs_from_unicode(wdir))
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\subprocess.py", line 819, in __init__
    restore_signals, start_new_session)
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\subprocess.py", line 1063, in _execute_child
    args = list2cmdline(args)
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\subprocess.py", line 632, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'int' is not iterable
Traceback (most recent call last):
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\plugins\editor.py", line 2048, in run_file
    self.re_run_file()
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\plugins\editor.py", line 2088, in re_run_file
    systerm)
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\spyder.py", line 1793, in open_external_console
    interact, debug, python_args)
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\utils\programs.py", line 166, in run_python_script_in_terminal
    cwd=encoding.to_fs_from_unicode(wdir))
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\subprocess.py", line 819, in __init__
    restore_signals, start_new_session)
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\subprocess.py", line 1063, in _execute_child
    args = list2cmdline(args)
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\subprocess.py", line 632, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'int' is not iterable
Traceback (most recent call last):
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\plugins\editor.py", line 2048, in run_file
    self.re_run_file()
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\plugins\editor.py", line 2088, in re_run_file
    systerm)
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\spyder.py", line 1793, in open_external_console
    interact, debug, python_args)
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\utils\programs.py", line 166, in run_python_script_in_terminal
    cwd=encoding.to_fs_from_unicode(wdir))
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\subprocess.py", line 819, in __init__
    restore_signals, start_new_session)
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\subprocess.py", line 1063, in _execute_child
    args = list2cmdline(args)
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\subprocess.py", line 632, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'int' is not iterable
Traceback (most recent call last):
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\plugins\editor.py", line 2006, in edit_run_configurations
    self.run_file()
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\plugins\editor.py", line 2048, in run_file
    self.re_run_file()
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\plugins\editor.py", line 2088, in re_run_file
    systerm)
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\spyder.py", line 1793, in open_external_console
    interact, debug, python_args)
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\utils\programs.py", line 166, in run_python_script_in_terminal
    cwd=encoding.to_fs_from_unicode(wdir))
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\subprocess.py", line 819, in __init__
    restore_signals, start_new_session)
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\subprocess.py", line 1063, in _execute_child
    args = list2cmdline(args)
  File "D:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\subprocess.py", line 632, in l...

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1856_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-26T08:02:04Z_

Please report this problem in the WinPython bug tracker because things are working just fine out of it.

**Status:** WontFix

**Comment by spyder-issues-migrator** [comment]
_From [steven.s...@pw.utc.com](https://code.google.com/u/113266883879874354807/) on 2015-02-10T12:03:09Z_

Carlos,

I think this may be a legitimate issue in Spyder when running on Python 3.

I was able to reproduce it outside of WinPython in a vanilla Spyder 2.3.2 install on Python 3.4.2.  My stack trace is similar to the OP's:

Traceback (most recent call last):
  File "C:\Python34-x86\lib\site-packages\spyderlib\plugins\editor.py", line 2050, in run_file
    self.re_run_file()
  File "C:\Python34-x86\lib\site-packages\spyderlib\plugins\editor.py", line 2090, in re_run_file
    systerm)
  File "C:\Python34-x86\lib\site-packages\spyderlib\spyder.py", line 1885, in open_external_console
    interact, debug, python_args)
  File "C:\Python34-x86\lib\site-packages\spyderlib\utils\programs.py", line 166, in run_python_script_in_terminal
    cwd=encoding.to_fs_from_unicode(wdir))
  File "C:\Python34-x86\lib\subprocess.py", line 858, in __init__
    restore_signals, start_new_session)
  File "C:\Python34-x86\lib\subprocess.py", line 1085, in _execute_child
    args = list2cmdline(args)
  File "C:\Python34-x86\lib\subprocess.py", line 663, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'int' is not iterable

Line 1084 in subprocess.py explicitly checks to see if 'args' is of type 'str'.  In this case, 'args' is of type 'bytes'.  Thus, 'args' is ultimately (and incorrectly) passed to list2cmdline().  list2cmdline() assumes it is operating on a list of strings.  This leads to a TypeError being raised on line 663 because each 'arg' is actually an 'int' (the iterable type of a byte string) as opposed to a 'str'.  Therefore, it would appear the root cause of the problem is an attempt to pass a byte string to subprocess.Popen() instead of a normal string.

Looking at spyderlib.utils.programs.run_python_script_in_terminal() (064b475), the byte strings are coming from calls to spyderlib.utils.encoding.to_fs_from_unicode() on lines 163 and 166.  The comment above this code refers to a specific comment in Python issue #1759845 ( http://bugs.python.org/issue1759845#msg74142 ).  As later comments suggest, this issue does not seem to affect Python 3.  Therefore, I'm not sure if the calls to to_fs_from_unicode() are applicable when running on Python 3.

I first verified that running Spyder 2.3.2 on Python 2.7.9 produces the expected behavior.  Then, I modified run_python_script_in_terminal() to convert the byte strings returned from to_fs_from_unicode() to normal strings (via decode('utf-8')) and verified it produces the expected behavior on Python 3.4.2.

Please confirm if this is indeed a Spyder issue.  Otherwise, if you still believe it's related to a specific distro, I'd be happy to follow up with the appropriate group.

Regards,
Steve

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-12T08:54:25Z_

I'll take a look into it this weekend :-)

**Summary:** Python consoles are not working under WinPython  \<span class="oldvalue"> (was: external console does not work) \</span>  
  **Status:** New  
  **Labels:** MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-16T16:01:17Z_

**Labels:** -MS-v2.3.3 MS-v2.3.4

**Comment by ssoloff** [comment]
Finally got around to upgrading to the latest WinPython, which includes Spyder 2.3.4, and confirmed this is fixed.  Thank you, Carlos, for taking care of it!

**Comment by ccordoba12** [comment]
@ssoloff, you're welcome!
