### ISSUE TITLE
Copying variables from variable explorer

### ISSUE THREAD

**Issue by vasude1** [spyder-ide/spyder#18621]
### What steps will reproduce the problem?

Copy multiple variables from the variable explorer.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/vasudevan/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/widgets/namespacebrowser.py", line 105, in get_value
    timeout=CALL_KERNEL_TIMEOUT).get_value(name)
  File "/home/vasudevan/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 555, in __call__
    call_dict, call_data, self._comm_id)
  File "/home/vasudevan/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 219, in _get_call_return_value
    call_dict, call_data, comm_id)
  File "/home/vasudevan/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 437, in _get_call_return_value
    return self._sync_error(reply['value'])
  File "/home/vasudevan/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 493, in _sync_error
    error_wrapper.raise_error()
  File "/home/vasudevan/.local/lib/python3.6/site-packages/spyder_kernels/comms/commbase.py", line 90, in raise_error
    raise self.etype(self)
ModuleNotFoundError: No module named 'mlarray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vasudevan/.local/lib/python3.6/site-packages/spyder/plugins/variableexplorer/widgets/main_widget.py", line 560, in copy
    self._current_editor.copy()
  File "/home/vasudevan/.local/lib/python3.6/site-packages/spyder/widgets/collectionseditor.py", line 1096, in copy
    obj = self.delegate.get_value(idx)
  File "/home/vasudevan/.local/lib/python3.6/site-packages/spyder/widgets/collectionseditor.py", line 1437, in get_value
    return self.parent().get_value(name)
  File "/home/vasudevan/.local/lib/python3.6/site-packages/spyder/widgets/collectionseditor.py", line 1495, in get_value
    value = self.shellwidget.get_value(name)
  File "/home/vasudevan/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/widgets/namespacebrowser.py", line 117, in get_value
    raise ValueError(msg % reason_other)
ValueError: An error occured, see the console..<br><br>Note: Please don't report this problem on Github, there's nothing to do about it.
```

## Versions

* Spyder version: 5.2.1 
* Python version: 3.6.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 5.4.0-121-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  2.1.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.16.3 (OK)
jedi >=0.17.2;<0.19.0         :  0.17.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.7.1 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.1 (OK)
pygments >=2.0                :  2.12.0 (OK)
pylint >=2.5.0                :  2.13.9 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.1.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  59.6.0 (OK)
sphinx >=0.6.6                :  4.3.2 (OK)
spyder_kernels >=2.2.0;<2.3.0 :  2.2.0 (OK)
textdistance >=4.2.0          :  4.3.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
xdg >=0.26                    :  0.28 (OK)
zmq >=17                      :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.1.1 (OK)
numpy >=1.7                   :  1.19.5 (OK)
pandas >=1.1.1                :  1.0.1 (NOK)
scipy >=0.17.0                :  1.5.4 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @vasude1, thanks for reporting. Could you try to open each of the variables you're copying to see which one is generating the error?

That will help us to narrow down the problem.

**Comment by ccordoba12** [comment]
Could you post a simple code example that generates the variable you're trying to copy and gives the error you posted above?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
