### ISSUE TITLE
existing kernel

### ISSUE THREAD

**Issue by DiegoAmral** [spyder-ide/spyder#18644]
### What steps will reproduce the problem?

Clicking in "Consoles"
Choosing "Connect to an existing kernel"
Selecting "W:/home/usr/remotemachine.json

the json file was created via miniconda using a Windows Subsystem for Linux (WSL)

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\dego_\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 1097, in create_client_for_kernel
    self._create_client_for_kernel(connection_file, hostname, sshkey,
  File "C:\Users\dego_\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 1924, in _create_client_for_kernel
    shellwidget.check_spyder_kernel()
  File "C:\Users\dego_\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 265, in check_spyder_kernel
    self.silent_exec_method(code)
  File "C:\Users\dego_\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 629, in silent_exec_method
    self._request_info['execute'][msg_id] = self._ExecutionRequest(msg_id,
TypeError: __new__() missing 1 required positional argument: 'hidden'
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.8.10
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.31.1 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=1.0                  :  2.12.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.2.2 (OK)
qtpy >=1.5.0                  :  1.11.2 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.25 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.1 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by steff456** [comment]
Hi @DiegoAmral,

This issue is already fixed in our latest release. Please try to install the latest version to avoid this issue. In case you are using conda, we recommend to use the `conda-forge` channel given that the latest version isn't still available in the defaults channel,

```
 conda create -n spyder-cf -c conda-forge spyder
 conda activate spyder-cf
 spyder
```

Hope this helps and thanks for opening this issue!

**Comment by DiegoAmral** [comment]
> Hi @DiegoAmral,
> 
> This issue is already fixed in our latest release. Please try to install the latest version to avoid this issue. In case you are using conda, we recommend to use the `conda-forge` channel given that the latest version isn't still available in the defaults channel,
> 
> ```
>  conda create -n spyder-cf -c conda-forge spyder
>  conda activate spyder-cf
>  spyder
> ```
> 
> Hope this helps and thanks for opening this issue!

Thank you @steff456, I'll try your suggestion!
