### ISSUE TITLE
no ipython console is currently available

### ISSUE THREAD

**Issue by 8Sherry** [spyder-ide/spyder#18698]
### What steps will reproduce the problem?

no ipython console is currently available, slect a new console

### Traceback
```python-traceback
Exception ignored in: <function ShellWidget.__del__ at 0x0000024749A111F0>
Traceback (most recent call last):
  File "C:\Users\Xueli Zheng\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 139, in __del__
    if (self.shutdown_thread is not None
AttributeError: 'ShellWidget' object has no attribute 'shutdown_thread'
Traceback (most recent call last):
  File "C:\Users\Xueli Zheng\anaconda3\lib\site-packages\traitlets\traitlets.py", line 537, in get
    value = obj._trait_values[self.name]
KeyError: 'config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Xueli Zheng\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 1028, in create_new_client
    client = ClientWidget(self, id_=client_id,
  File "C:\Users\Xueli Zheng\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 139, in __init__
    self.shellwidget = ShellWidget(config=config_options,
  File "C:\Users\Xueli Zheng\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 89, in __init__
    super(ShellWidget, self).__init__(*args, **kw)
  File "C:\Users\Xueli Zheng\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 197, in __init__
    super(DebuggingWidget, self).__init__(*args, **kwargs)
  File "C:\Users\Xueli Zheng\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 67, in __init__
    self._pdb_history_file = PdbHistory()
  File "C:\Users\Xueli Zheng\anaconda3\lib\site-packages\IPython\core\history.py", line 536, in __init__
    super(HistoryManager, self).__init__(shell=shell, config=config,
  File "C:\Users\Xueli Zheng\anaconda3\lib\site-packages\IPython\core\history.py", line 214, in __init__
    super(HistoryAccessor, self).__init__(**traits)
  File "C:\Users\Xueli Zheng\anaconda3\lib\site-packages\traitlets\config\configurable.py", line 110, in __init__
    self._load_config(self.config)
  File "C:\Users\Xueli Zheng\anaconda3\lib\site-packages\traitlets\traitlets.py", line 577, in __get__
    return self.get(obj, cls)
  File "C:\Users\Xueli Zheng\anaconda3\lib\site-packages\traitlets\traitlets.py", line 550, in get
    value = self._validate(obj, default)
  File "C:\Users\Xueli Zheng\anaconda3\lib\site-packages\traitlets\traitlets.py", line 612, in _validate
    value = self.validate(obj, value)
  File "C:\Users\Xueli Zheng\anaconda3\lib\site-packages\traitlets\traitlets.py", line 1851, in validate
    self.error(obj, value)
  File "C:\Users\Xueli Zheng\anaconda3\lib\site-packages\traitlets\traitlets.py", line 692, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'config' trait of a PdbHistory instance expected a Config, not the Config {}.
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.0 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @8Sherry, thanks for reporting. This error is already fixed in our latest version (5.3.2).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder
