### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by Vaibhav5177** [spyder-ide/spyder#18724]
### What steps will reproduce the problem?

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 23, in 
start.main()
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 316, in main
kernel.initialize()
File "C:\ProgramData\Anaconda3\lib\site‑packages\traitlets\config\application.py", line 88, in inner
return method(app, *args, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 632, in initialize
self.init_sockets()
File "C:\ProgramData\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 282, in init_sockets
self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
File "C:\ProgramData\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 229, in _bind_socket
return self._try_bind_socket(s, port)
File "C:\ProgramData\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 205, in _try_bind_socket
s.bind("tcp://%s:%i" % (self.ip, port))
File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\sugar\socket.py", line 214, in bind
super().bind(addr)
File "zmq\backend\cython\socket.pyx", line 540, in zmq.backend.cython.socket.Socket.bind
File "zmq\backend\cython\checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Permission denied

**Comment by ccordoba12** [comment]
Hey @Vaibhav5177, thanks for reporting. This error could be fixed in our latest version (5.3.2).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

Please do that and let us know if it works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by SwissPowershell** [comment]
Had this error and it's the local firewall that prevented to connect to localhost

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know about it.
