### ISSUE TITLE
samba file edit & save error

### ISSUE THREAD

**Issue by bluenote212** [spyder-ide/spyder#18745]
### What steps will reproduce the problem?

1. samba connect
2. samba html file edit
3. file save
4. Error

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\B180093\Anaconda3\lib\ntpath.py", line 647, in realpath
    path = _getfinalpathname(path)
OSError: [WinError 1005] 볼륨에 인식된 파일 시스템이 없습니다.
모든 필요한 파일 시스템 드라이브를 로드했고 볼륨이 손상되지 않았는지 확인하십시오: 'Y:\\anaconda3\\envs\\telechips\\main\\templates\\git.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\B180093\Anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 2187, in load
    current_editor = self.set_current_filename(filename,
  File "C:\Users\B180093\Anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 1721, in set_current_filename
    return editorstack.set_current_filename(filename, focus)
  File "C:\Users\B180093\Anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1512, in set_current_filename
    index = self.has_filename(filename)
  File "C:\Users\B180093\Anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1501, in has_filename
    if fixpath(filename) == fixpath(finfo.filename):
  File "C:\Users\B180093\Anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1499, in <lambda>
    fixpath = lambda path: osp.normcase(osp.realpath(path))
  File "C:\Users\B180093\Anaconda3\lib\ntpath.py", line 651, in realpath
    path = _getfinalpathname_nonstrict(path)
  File "C:\Users\B180093\Anaconda3\lib\ntpath.py", line 601, in _getfinalpathname_nonstrict
    path = _getfinalpathname(path)
OSError: [WinError 1005] 볼륨에 인식된 파일 시스템이 없습니다.
모든 필요한 파일 시스템 드라이브를 로드했고 볼륨이 손상되지 않았는지 확인하십시오: 'Y:\\anaconda3\\envs\\telechips\\main\\templates\\git.html'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.7
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.0 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment]
Hey @bluenote212, thanks for reporting. This error is already fixed in our latest version (5.3.2).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder
