### ISSUE TITLE
Can't start bootstrap.py with pyqt

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1879]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-07-02T02:28:25Z_

Spyder Version:  2.3.0rc (3771: r404e2ec105b9 )
Python Version:  2.7.7
Qt Version    :  4.8.6, PyQt4 (API v2) 4.11 on Linux
pyflakes >=0.5.0:  0.5.0 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  2.1.0 (OK)
pygments >=1.6  :  1.6 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  2.1.1 (OK)
jedi >=0.8.0    :  0.8.0-final0 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  1.2.1 (OK) 

What steps will reproduce the problem?

 1. Try to start spyder using python2 ./bootstrap.py --gui=pyqt 2. 3. 

What is the expected output? What do you see instead?

 I get the following error:

Executing Spyder from source checkout Revision 54e70aafa4dc :3784, Branch: default
01. Patched sys.path with /data/prog/spyderlib
                      and /data/prog/spyderlib/external-py2
02. Skipping GUI toolkit detection
03. Imported Spyder 2.3.0rc
    [Python 2.7.7 64bits, Qt 4.8.6, PyQt4 (API v1) 4.11 on Linux]
04. Executing spyder.main()
Bootstrap completed in 00:00:00.2514
Traceback (most recent call last):
  File "/data/prog/spyderlib/spyderlib/spyder.py", line 2333, in main
    mainwindow = run_spyder(app, options, args)
  File "/data/prog/spyderlib/spyderlib/spyder.py", line 2221, in run_spyder
    main.setup()
  File "/data/prog/spyderlib/spyderlib/spyder.py", line 785, in setup
    from spyderlib.plugins.inspector import ObjectInspector
  File "/data/prog/spyderlib/spyderlib/plugins/inspector.py", line 40, in \<module>
    from spyderlib.widgets.ipython import IPythonControlWidget
  File "/data/prog/spyderlib/spyderlib/widgets/ipython.py", line 29, in \<module>
    from IPython.frontend.qt.console.rich_ipython_widget import RichIPythonWidget
  File "/usr/lib/python2.7/site-packages/IPython/qt/console/rich_ipython_widget.py", line 15, in \<module>
    from IPython.external.qt import QtCore, QtGui
  File "/usr/lib/python2.7/site-packages/IPython/external/qt.py", line 23, in \<module>
    QtCore, QtGui, QtSvg, QT_API = load_qt(api_opts)
  File "/usr/lib/python2.7/site-packages/IPython/external/qt_loaders.py", line 258, in load_qt
    api_options))
ImportError: 
    Could not load requested Qt binding. Please ensure that
    PyQt4 >= 4.7 or PySide >= 1.0.3 is available,
    and only one is imported per session.

    Currently-imported Qt library:   'pyqtv1'
    PyQt4 installed:                 True
    PySide >= 1.0.3 installed:       True
    Tried to load:                   ['pyqt']

Please provide any additional information below

.
It works fine with pyside or python3.
I tried to delete ~/.spyder2 but I got the same error.
The command ipython2 qtconsole works (I don't know if it uses pyside or pyqt)
Also, I just updated the default branch, bitbucket said I was 27 commits behind before sync.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1879_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-07-02T06:40:57Z_

**Labels:** MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-07-02T07:59:31Z_

This issue was closed by revision c2a549e37fb9 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2014-07-02T08:38:25Z_

I'd reopen this until this hack is replaced with proper fix. See discussion at https://bitbucket.org/spyder-ide/spyderlib/commits/226c8cc50cb
