### ISSUE TITLE
Spyder 3.3.3 "Connecting to kernel" stuck

### ISSUE THREAD

**Issue by fadai88** [spyder-ide/spyder#18792]
I usually didn't have problem with launching Spyder. But Spyder Connecting to kernel stuck.  I looked at other answers here and SO but nothing works for me. Rebooted PC, reset Spyder, nothing works.
I got this error:

`    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method

Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method

Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method

Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: 
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method

Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method

Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method

Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: 
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: 
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "C:\Users\Acer\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')`

**Comment by ccordoba12** [comment]
Hey @fadai88, thanks for reporting. Unfortunately we don't support Spyder 3 anymore, but this error is fixed in our latest version (5.3.2).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder
