### ISSUE TITLE
Bootstrap.py won't start with python3

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1881]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-07-03T12:40:20Z_

Spyder Version:  2.3.0rc (3844: rbf8acc10761d )
Python Version:  2.7.7
Qt Version    :  4.8.6, PyQt4 (API v2) 4.11 on Linux
pyflakes >=0.5.0:  0.5.0 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  2.1.0 (OK)
pygments >=1.6  :  1.6 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  2.1.1 (OK)
jedi >=0.8.0    :  None (NOK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  1.2.1 (OK) 

What steps will reproduce the problem?

 1. run python3 ./bootstrap.py 2. 3. 

What is the expected output? What do you see instead?

 I get this:

Executing Spyder from source checkout Revision bf8acc10761d :3844, Branch: my
01. Patched sys.path with /home/joseph/prog/spyderlib
                      and /home/joseph/prog/spyderlib/external-py3
02. Skipping GUI toolkit detection
Traceback (most recent call last):
  File "./bootstrap.py", line 134, in \<module>
    versions = get_versions(reporev=False)
  File "/home/joseph/prog/spyderlib/spyderlib/__init__.py", line 67, in get_versions
    import qt.QtCore
ImportError: No module named 'qt'

Please provide any additional information below

.
Pytho2 works with pyside and pyqt, python3 works with neither.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1881_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-07-04T16:43:29Z_

Totally true :)

**Labels:** MS-v2.3 Component-Python3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-07-05T07:26:19Z_

This issue was closed by revision 2c7d457df27f .

**Status:** Fixed
