### ISSUE TITLE
Socket error when closing console (and auto-opening new one)

### ISSUE THREAD

**Issue by ali-cole** [spyder-ide/spyder#18819]
### What steps will reproduce the problem?

In Spyder window, close the console, which forces a new one to open. Even in an empty, unused console, I get the following error:

### Traceback
```python-traceback
Exception in thread Thread-23:
Traceback (most recent call last):
  File "C:\Users\acole\Miniconda3\envs\windroseenv\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\acole\Miniconda3\envs\windroseenv\lib\site-packages\jupyter_client\threaded.py", line 218, in run
    self.ioloop.start()
  File "C:\Users\acole\Miniconda3\envs\windroseenv\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\acole\Miniconda3\envs\windroseenv\lib\site-packages\nest_asyncio.py", line 72, in run_forever
    self._run_once()
  File "C:\Users\acole\Miniconda3\envs\windroseenv\lib\site-packages\nest_asyncio.py", line 106, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\acole\Miniconda3\envs\windroseenv\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\acole\Miniconda3\envs\windroseenv\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
OSError: [WinError 10038] An operation was attempted on something that is not a socket

```

## Versions

* Spyder version: 5.2.2 
* Python version: 3.7.13
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @ali-cole, thanks for reporting. Please update to our latest version (5.3.2) to see if the error you reported above is no longer present.

Let us know if that works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
