### ISSUE TITLE
Unable to launch, no module named 'jupyter_client.utils'

### ISSUE THREAD

**Issue by mahmoodn** [spyder-ide/spyder#18824]
Hi
I have installed Spyder 5.3.2 on Ubuntu from source. After upgrading some packages, I was able to run the setup file. But the launch command fails as you can see below.

```
$ python3 setup.py install --user
...
Using /home/mahmood/.local/lib/python3.8/site-packages/text_unidecode-1.3-py3.8.egg
Searching for arrow==1.2.2
Best match: arrow 1.2.2
Adding arrow 1.2.2 to easy-install.pth file

Using /home/mahmood/.local/lib/python3.8/site-packages
Searching for six==1.14.0
Best match: six 1.14.0
Adding six 1.14.0 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Finished processing dependencies for spyder==5.3.2
$ spyder
/home/mahmood/.local/lib/python3.8/site-packages/setuptools-63.2.0-py3.8.egg/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/mahmood/.local/lib/python3.8/site-packages/setuptools-63.2.0-py3.8.egg/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 7.6.0ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/mahmood/.local/lib/python3.8/site-packages/setuptools-63.2.0-py3.8.egg/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Traceback (most recent call last):
  File "/home/mahmood/.local/bin/spyder", line 33, in <module>
    sys.exit(load_entry_point('spyder==5.3.2', 'gui_scripts', 'spyder')())
  File "/home/mahmood/.local/lib/python3.8/site-packages/spyder-5.3.2-py3.8.egg/spyder/app/start.py", line 252, in main
    mainwindow.main(options, args)
  File "/home/mahmood/.local/lib/python3.8/site-packages/spyder-5.3.2-py3.8.egg/spyder/app/mainwindow.py", line 2031, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "/home/mahmood/.local/lib/python3.8/site-packages/spyder-5.3.2-py3.8.egg/spyder/app/utils.py", line 289, in create_window
    main.setup()
  File "/home/mahmood/.local/lib/python3.8/site-packages/spyder-5.3.2-py3.8.egg/spyder/app/mainwindow.py", line 820, in setup
    internal_plugins = find_internal_plugins()
  File "/home/mahmood/.local/lib/python3.8/site-packages/spyder-5.3.2-py3.8.egg/spyder/app/find_plugins.py", line 40, in find_internal_plugins
    mod = importlib.import_module(entry_point.module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mahmood/.local/lib/python3.8/site-packages/spyder-5.3.2-py3.8.egg/spyder/plugins/ipythonconsole/plugin.py", line 24, in <module>
    from spyder.plugins.ipythonconsole.widgets.main_widget import (
  File "/home/mahmood/.local/lib/python3.8/site-packages/spyder-5.3.2-py3.8.egg/spyder/plugins/ipythonconsole/widgets/main_widget.py", line 38, in <module>
    from spyder.plugins.ipythonconsole.utils.manager import SpyderKernelManager
  File "/home/mahmood/.local/lib/python3.8/site-packages/spyder-5.3.2-py3.8.egg/spyder/plugins/ipythonconsole/utils/manager.py", line 16, in <module>
    from jupyter_client.utils import run_sync
ModuleNotFoundError: No module named 'jupyter_client.utils'
```
But I don't see any problem with jupyter_client.

```
$ pip3 list | grep jupyter
jupyter                1.0.0               
jupyter-client         7.3.1               
jupyter-console        6.4.3               
jupyter-core           4.11.1              
jupyterlab-widgets     1.1.0               
```
Some other information.
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
$ uname -a
Linux XX 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ pip3 --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
$ python3 --version
Python 3.8.10
```

Any idea about that?

**Comment by ccordoba12** [comment]
I think this problem is caused because you're mixing the Python packages provided from your Linux distro with those you installed with `pip install --user`.

So, my suggestion is for you to remove `/home/mahmood/.local/lib/python3.8/site-packages`, install `virtualenvwrapper` with

    sudo apt install python3-virtualenvwrapper

and then run

    mkvirtualenv spyder-env
    pip install -U pip
    pip install spyder

If `mkvirtualenv` doesn't work for you, you probably need to log out from your session and log in again.

Please do that and let us know if it works for you.

**Comment by mahmoodn** [comment]
Please see the output below
```
$ sudo apt install python3-virtualenvwrapper
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-virtualenvwrapper is already the newest version (4.8.4-4).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
$ mkvirtualenv spyder-env
mkvirtualenv: command not found
```

**Comment by mahmoodn** [comment]
Hi again,
On a new vitual machine running Ubuntu 22.04, I tried to install latest Spyder via pip3. Please see the output below:
```
$ ls /usr/local/lib/python3.10/dist-packages
easy-install.pth                              QDarkStyle-3.0.3-py3.10.egg
numpydoc-1.4.0-py3.10.egg                     qstylizer-0.2.1-py3.10.egg
parso-0.8.3-py3.10.egg                        QtAwesome-1.1.1-py3.10.egg
pickleshare-0.7.5-py3.10.egg                  qtconsole-5.3.1-py3.10.egg
psutil-5.9.1-py3.10-linux-x86_64.egg          QtPy-2.1.0-py3.10.egg
Pygments-2.12.0-py3.10.egg                    Rtree-1.0.0-py3.10-linux-x86_64.egg
pylint-2.14.5-py3.10.egg                      Sphinx-5.1.1-py3.10.egg
pyls_spyder-0.4.0-py3.10.egg                  spyder-5.3.2-py3.10.egg
PyQt5-5.15.7-py3.10-linux-x86_64.egg          spyder_kernels-2.3.2-py3.10.egg
PyQtWebEngine-5.15.6-py3.10-linux-x86_64.egg  textdistance-4.3.0-py3.10.egg
python_lsp_black-1.2.1-py3.10.egg             three_merge-0.1.1-py3.10.egg
python_lsp_server-1.5.0-py3.10.egg            watchdog-2.1.9-py3.10-linux-x86_64.egg
pyzmq-23.2.0-py3.10-linux-x86_64.egg


$ ls .local/lib/python3.10/site-packages/
7b32b9a39ad70713acde__mypyc.cpython-310-x86_64-linux-gnu.so  mistune.py
alabaster                                                    mypy_extensions-0.4.3.dist-info
alabaster-0.7.12.dist-info                                   mypy_extensions.py
arrow                                                        nbclient
arrow-1.2.2.dist-info                                        nbclient-0.6.6.dist-info
astroid                                                      nbconvert
astroid-2.11.7.dist-info                                     nbconvert-6.5.0.dist-info
atomicwrites                                                 nbformat
atomicwrites-1.4.1.dist-info                                 nbformat-5.4.0.dist-info
attr                                                         nest_asyncio-1.5.5.dist-info
attrs                                                        nest_asyncio.py
attrs-21.4.0.dist-info                                       packaging
autopep8-1.6.0.dist-info                                     packaging-21.3.dist-info
autopep8.py                                                  pandocfilters-1.5.0.dist-info
babel                                                        pandocfilters.py
Babel-2.10.3.dist-info                                       pathspec
backcall                                                     pathspec-0.9.0.dist-info
backcall-0.2.0.dist-info                                     platformdirs
beautifulsoup4-4.11.1.dist-info                              platformdirs-2.5.2.dist-info
binaryornot                                                  pluggy
binaryornot-0.4.4.dist-info                                  pluggy-1.0.0.dist-info
black                                                        prompt_toolkit
black-22.6.0.dist-info                                       prompt_toolkit-3.0.30.dist-info
blackd                                                       pvectorc.cpython-310-x86_64-linux-gnu.so
_black_version.py                                            __pycache__
bleach                                                       pycodestyle-2.8.0.dist-info
bleach-5.0.1.dist-info                                       pycodestyle.py
blib2to3                                                     pydocstyle
bs4                                                          pydocstyle-6.1.1.dist-info
cloudpickle                                                  pyflakes
cloudpickle-2.1.0.dist-info                                  pyflakes-2.4.0.dist-info
cookiecutter                                                 pylsp_jsonrpc
cookiecutter-2.1.1.dist-info                                 PyQt5
dateutil                                                     PyQt5_Qt5-5.15.2.dist-info
debugpy                                                      PyQt5_sip-12.11.0.dist-info
debugpy-1.6.2.dist-info                                      PyQtWebEngine_Qt5-5.15.2.dist-info
decorator-5.1.1.dist-info                                    pyrsistent
decorator.py                                                 pyrsistent-0.18.1.dist-info
defusedxml                                                   _pyrsistent_version.py
defusedxml-0.7.1.dist-info                                   python_dateutil-2.8.2.dist-info
diff_match_patch                                             python_lsp_jsonrpc-1.0.0.dist-info
diff_match_patch-20200713.dist-info                          python_slugify-6.1.2.dist-info
dill                                                         pytoolconfig
dill-0.3.5.1.dist-info                                       pytoolconfig-1.2.1.dist-info
docutils                                                     rope
docutils-0.19.dist-info                                      rope-1.2.0.dist-info
entrypoints-0.4.dist-info                                    slugify
entrypoints.py                                               snowballstemmer
fastjsonschema                                               snowballstemmer-2.2.0.dist-info
fastjsonschema-2.16.1.dist-info                              sortedcontainers
flake8                                                       sortedcontainers-2.4.0.dist-info
flake8-4.0.1.dist-info                                       soupsieve
imagesize                                                    soupsieve-2.3.2.post1.dist-info
imagesize-1.4.1.dist-info                                    sphinxcontrib
imagesize.py                                                 sphinxcontrib_applehelp-1.0.2.dist-info
inflection                                                   sphinxcontrib_applehelp-1.0.2-py3.8-nspkg.pth
inflection-0.5.1.dist-info                                   sphinxcontrib_devhelp-1.0.2.dist-info
inflection.py                                                sphinxcontrib_devhelp-1.0.2-py3.8-nspkg.pth
intervaltree                                                 sphinxcontrib_htmlhelp-2.0.0.dist-info
intervaltree-3.1.0.dist-info                                 sphinxcontrib_htmlhelp-2.0.0-py3.9-nspkg.pth
ipykernel                                                    sphinxcontrib_jsmath-1.0.1.dist-info
ipykernel-6.15.1.dist-info                                   sphinxcontrib_jsmath-1.0.1-py3.7-nspkg.pth
ipykernel_launcher.py                                        sphinxcontrib_qthelp-1.0.3.dist-info
IPython                                                      sphinxcontrib_qthelp-1.0.3-py3.8-nspkg.pth
ipython-7.34.0.dist-info                                     sphinxcontrib_serializinghtml-1.1.5.dist-info
ipython_genutils                                             sphinxcontrib_serializinghtml-1.1.5-py3.9-nspkg.pth
ipython_genutils-0.2.0.dist-info                             text_unidecode
isort                                                        text_unidecode-1.3.dist-info
isort-5.10.1.dist-info                                       tinycss2
jedi                                                         tinycss2-1.1.1.dist-info
jedi-0.18.1.dist-info                                        toml
jellyfish                                                    toml-0.10.2.dist-info
jellyfish-0.9.0.dist-info                                    tomli
jinja2                                                       tomli-2.0.1.dist-info
Jinja2-3.1.2.dist-info                                       tomlkit
jinja2_time                                                  tomlkit-0.11.1.dist-info
jinja2_time-0.2.0.dist-info                                  tornado
jsonschema                                                   tornado-6.2.dist-info
jsonschema-4.8.0.dist-info                                   traitlets
jupyter_client                                               traitlets-5.3.0.dist-info
jupyter_client-7.3.4.dist-info                               ujson-5.4.0.dist-info
jupyter_core                                                 ujson.cpython-310-x86_64-linux-gnu.so
jupyter_core-4.11.1.dist-info                                wcwidth
jupyterlab_pygments                                          wcwidth-0.2.5.dist-info
jupyterlab_pygments-0.2.2.dist-info                          webencodings
jupyter.py                                                   webencodings-0.5.1.dist-info
lazy_object_proxy                                            whatthepatch
lazy_object_proxy-1.7.1.dist-info                            whatthepatch-1.0.2.dist-info
markupsafe                                                   wrapt
MarkupSafe-2.1.1.dist-info                                   wrapt-1.14.1.dist-info
matplotlib_inline                                            wurlitzer-3.0.2.dist-info
matplotlib_inline-0.1.3.dist-info                            wurlitzer.py
mccabe-0.6.1.dist-info                                       yapf
mccabe.py                                                    yapf-0.32.0.dist-info
mistune-0.8.4.dist-info                                      yapftests
```
But it complains about PyQt5 version which is weird.
```
$ spyder
Traceback (most recent call last):
  File "/usr/local/bin/spyder", line 33, in <module>
    sys.exit(load_entry_point('spyder==5.3.2', 'gui_scripts', 'spyder')())
  File "/usr/local/lib/python3.10/dist-packages/spyder-5.3.2-py3.10.egg/spyder/app/start.py", line 248, in main
    from spyder.app import mainwindow
  File "/usr/local/lib/python3.10/dist-packages/spyder-5.3.2-py3.10.egg/spyder/app/mainwindow.py", line 41, in <module>
    requirements.check_qt()
  File "/usr/local/lib/python3.10/dist-packages/spyder-5.3.2-py3.10.egg/spyder/requirements.py", line 54, in check_qt
    show_warning("Please check Spyder installation requirements:\n"
  File "/usr/local/lib/python3.10/dist-packages/spyder-5.3.2-py3.10.egg/spyder/requirements.py", line 32, in show_warning
    raise RuntimeError(message)
RuntimeError: Please check Spyder installation requirements:
PyQt5 5.9+ is required (found None).
```

How to fix that?

**Comment by mahmoodn** [comment]
Anyway... I just reinstalled the virtual machine and then ran the following commands:
```
pip3 install spyder --user
~/.local/bin/spyder
```
Closing the issue.
