### ISSUE TITLE
Can't open on iMAC with new Anaconda software

### ISSUE THREAD

**Issue by imrankhansaami** [spyder-ide/spyder#18842]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/imrankhan/opt/anaconda3/envs/blockchainaz/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
      File "/Users/imrankhan/opt/anaconda3/envs/blockchainaz/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 215, in _handle_execute_reply

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):
  File "/Users/imrankhan/opt/anaconda3/envs/blockchainaz/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):
  File "/Users/imrankhan/opt/anaconda3/envs/blockchainaz/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):
  File "/Users/imrankhan/opt/anaconda3/envs/blockchainaz/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.13
* Qt Versions: 5.9.6, PyQt5 5.9.2 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  2.2.0 (OK)
pycodestyle >=2.3:  2.6.0 (OK)
pygments >=2.0   :  2.11.2 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  4.4.0 (OK)
rope >=0.9.4     :  0.22.0 (OK)
jedi >=0.9.0     :  0.17.2 (OK)
psutil >=0.3     :  5.8.0 (OK)
nbconvert >=4.0  :  6.0.7 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  5.2.2 (OK)
IPython >=4.0    :  7.16.1 (OK)
pylint >=0.25    :  2.9.6 (OK)

```

**Comment by ccordoba12** [comment]
Hey @imrankhansaami, thanks for reporting. This error is already fixed in our latest version (5.3.2).

Since it's still not available in Anaconda, you have two options:

1. Use our Mac installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder
