### ISSUE TITLE
Two implementations of Tk; which one is undefined.

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1885]
_From [sahig...@colorado.edu](https://code.google.com/u/112391118755934707631/) on 2014-07-09T11:58:13Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. I am trying to use a Google library that is based on Tk/Tcl. Unfortunately, it seems that Spyder sees Tk in two places. When I try to import the library, I get: 

objc[54988]: Class TKApplication is implemented in both /opt/local/lib/libtk8.6.dylib and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
objc[54988]: Class TKMenu is implemented in both /opt/local/lib/libtk8.6.dylib and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
objc[54988]: Class TKContentView is implemented in both /opt/local/lib/libtk8.6.dylib and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
objc[54988]: Class TKWindow is implemented in both /opt/local/lib/libtk8.6.dylib and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.

Python then crashes. I tried deleting (well, moving to another location) libtk8.6.dylib, and got an error:

 ERROR: A Python library (PIL) used by the Earth Engine API mapclient module
    was not found. Information on PIL can be found at: http://pypi.python.org/pypi/PIL Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 487, in runfile
    execfile(filename, namespace)
  File "/Users/sahiggin/Desktop/python_api/test.py", line 11, in \<module>
    from ee import mapclient
  File "/Library/Python/2.7/site-packages/ee/mapclient.py", line 41, in \<module>
    import ImageTk             # pylint: disable=g-import-not-at-top
  File "/Library/Python/2.7/site-packages/PIL-1.1.7-py2.7-macosx-10.7-intel.egg/ImageTk.py", line 28, in \<module>
    import Tkinter, Image
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 39, in \<module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_tkinter.so, 2): Library not loaded: /opt/local/lib/libtk8.6.dylib
  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_tkinter.so
  Reason: image not found

 I then restored it and tried hiding the Tk framework, and got more errors such as:

Exception in thread Thread-15:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Python/2.7/site-packages/ee/mapclient.py", line 445, in run
    callback(image)
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ee/mapclient.py", line 214, in AddTile
    newtile = ImageTk.PhotoImage(newtile)
  File "/Library/Python/2.7/site-packages/PIL-1.1.7-py2.7-macosx-10.7-intel.egg/ImageTk.py", line 116, in __init__
    self.paste(image)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/Library/Python/2.7/site-packages/PIL-1.1.7-py2.7-macosx-10.7-intel.egg/ImageTk.py", line 181, in paste
    self.run()
    import _imagingtk
ImportError: dlopen(/Library/Python/2.7/site-packages/PIL-1.1.7-py2.7-macosx-10.7-intel.egg/_imagingtk.so, 2): Library not loaded: /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk
  Referenced from: /Library/Python/2.7/site-packages/PIL-1.1.7-py2.7-macosx-10.7-intel.egg/_imagingtk.so
  Reason: image not found

So it seems that Python needs both of these libraries, yet dies at the beginning when it first sees that they are redundant. 

The links all actually work in my command-line version of Python. How can I point Spyder to just one of them on import?

I am using Spyder, Python 2.7.8 (v2.7.8:ee879c0ffa11, Jun 29 2014, 21:07:35) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin. Operating system: Mac OSX 10.7.5

Thank you for your help!!

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1885_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-25T00:38:29Z_

I'm sorry but this is a Mac problem and doesn't have to do with Spyder itself.

I've seen this problem before but with several Qt libraries instead of Tk ones. The way I solved it is by using a tool called macdeploy-qt but I don't know how to do it for Tk.

Sorry for our late response. I hope you've found the solution by now.

**Status:** WontFix
