### ISSUE TITLE
Console crashes when trying to open a variable

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1890]
_From [VanBoxem...@gmail.com](https://code.google.com/u/108779539249446421349/) on 2014-07-16T02:52:23Z_

Spyder Version:  2.3.0beta2
Python Version:  3.3.5
Qt Version    :  4.8.4, PyQt4 (API v2) 4.9.6 on Windows
pyflakes >=0.6.0:  None (OK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  2.0.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  1.1.0 (OK) 

What steps will reproduce the problem?

 1. run script, using new interpreter and keeping it open to interact with after completion (super awesome workflow btw!)
2. open variable in object viewer
3. ???
4. Get this error message:
Inspect Spyder internals:
  spy.app, spy.window, dir(spy)
\>>> Traceback (most recent call last):
  File "C:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\widgets\dicteditor.py", line 444, in \<lambda>
    lambda eid=id(editor): self.editor_accepted(eid))
  File "C:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\widgets\dicteditor.py", line 455, in editor_accepted
    self.set_value(index, conv_func(value))
  File "C:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\widgets\dicteditor.py", line 1193, in set_value
    self.set_value_func(name, value)
  File "C:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\widgets\externalshell\namespacebrowser.py", line 347, in set_value
    monitor_set_global(self._get_sock(), name, value)
  File "C:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 101, in monitor_set_global
    settings=[value])
  File "C:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\utils\bsdsocket.py", line 99, in communicate
    write_packet(sock, command)
  File "C:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\utils\bsdsocket.py", line 47, in write_packet
    nsend -= temp_fail_retry(socket.error, sock.send, sent_data)
AttributeError: 'NoneType' object has no attribute 'send' 

What is the expected output? What do you see instead?

 It should not crash. The whole console subwindow is completely messed up forcing me to restart Spyder.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1890_

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-07-16T01:31:37Z_

I see that Spyder itself uses python3, but is your interpreter python2 or python3 ? You can check in the preferences in the console section.

**Comment by spyder-issues-migrator** [comment]
_From [VanBoxem...@gmail.com](https://code.google.com/u/108779539249446421349/) on 2014-07-16T01:37:12Z_

It uses "Default (the same as Spyder's)."
I have no other Python installed on my system.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-25T00:01:50Z_

You need to give us more info about the variable you're trying to open because without knowing more about it it's very hard to help you.

Also, please try to update to the final version of 2.3.0 because I see you're using beta2.

**Summary:** Console crashes when trying to open a variable  \<span class="oldvalue"> (was: Internal console crashes) \</span>  
  **Labels:** Cat-Console

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T18:00:43Z_

Closing because of lack of further info.

**Status:** WontFix
