### ISSUE TITLE
"TypeError: arguments did not match any overloaded call" in Ubuntu 22.04

### ISSUE THREAD

**Issue by rolandog** [spyder-ide/spyder#18919]
### What steps will reproduce the problem?

1. Try starting Spyder in Ubuntu 22.04.

I was able to follow the workaround detailed in https://stackoverflow.com/a/72453147

### Detailed logs

Here are the detailed logs:

<details>

<summary>error logs from running spyder in terminal</summary>

```console
user@example:~$ spyder --debug-info verbose --debug-output terminal --opengl software
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
2022-08-03 11:16:49,333 [INFO] [spyder.app.mainwindow] -> Start of MainWindow constructor
2022-08-03 11:16:49,645 [INFO] [spyder.app.mainwindow] -> End of MainWindow constructor
2022-08-03 11:16:49,701 [INFO] [spyder.app.mainwindow] -> *** Start of MainWindow setup ***
2022-08-03 11:16:49,701 [INFO] [spyder.app.mainwindow] -> Updating PYTHONPATH
2022-08-03 11:16:49,702 [INFO] [spyder.app.mainwindow] -> Applying theme configuration...
2022-08-03 11:16:49,702 [DEBUG] [qdarkstyle] -> Reading QSS file in: :qdarkstyle/style.qss
2022-08-03 11:16:49,703 [INFO] [qdarkstyle] -> QSS file sucessfuly loaded.
2022-08-03 11:16:49,703 [DEBUG] [qdarkstyle] -> Checking patches for being applied.
2022-08-03 11:16:49,703 [INFO] [qdarkstyle] -> Found application patches to be applied.
2022-08-03 11:16:49,708 [INFO] [spyder.app.mainwindow] -> Creating core actions...
2022-08-03 11:16:49,709 [INFO] [spyder.app.mainwindow] -> Creating toolbars...
2022-08-03 11:16:49,712 [INFO] [spyder.app.mainwindow] -> Creating Tools menu...
2022-08-03 11:16:49,715 [INFO] [spyder.app.mainwindow] -> Creating guidata and sift entries...
2022-08-03 11:16:49,716 [INFO] [spyder.app.mainwindow] -> Loading switcher...
2022-08-03 11:16:49,719 [INFO] [spyder.app.mainwindow] -> Loading internal console...
2022-08-03 11:16:49,799 [INFO] [spyder.plugins.console.plugin] -> Initializing...
2022-08-03 11:16:49,846 [INFO] [spyder.app.mainwindow] -> Starting code completion manager...
2022-08-03 11:16:49,911 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Registering lsp
2022-08-03 11:16:49,911 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Registering fallback
2022-08-03 11:16:49,911 [DEBUG] [spyder.plugins.completion.fallback.actor] -> Fallback plugin starting...
Traceback (most recent call last):
  File "/usr/bin/spyder", line 33, in <module>
    sys.exit(load_entry_point('spyder==4.2.1', 'gui_scripts', 'spyder')())
  File "/usr/lib/python3/dist-packages/spyder/app/start.py", line 213, in main
    mainwindow.main(options, args)
  File "/usr/lib/python3/dist-packages/spyder/app/mainwindow.py", line 3624, in main
    mainwindow = create_window(app, splash, options, args)
  File "/usr/lib/python3/dist-packages/spyder/app/mainwindow.py", line 3482, in create_window
    main.setup()
  File "/usr/lib/python3/dist-packages/spyder/app/mainwindow.py", line 803, in setup
    self.completions = CompletionManager(self)
  File "/usr/lib/python3/dist-packages/spyder/plugins/completion/plugin.py", line 97, in __init__
    plugin_client = Plugin(self.main)
  File "/usr/lib/python3/dist-packages/spyder/plugins/completion/kite/plugin.py", line 50, in __init__
    self.installer = KiteInstallerDialog(
  File "/usr/lib/python3/dist-packages/spyder/plugins/completion/kite/widgets/install.py", line 287, in __init__
    self._integration_widget = KiteIntegrationInfo(self)
  File "/usr/lib/python3/dist-packages/spyder/plugins/completion/kite/widgets/install.py", line 58, in __init__
    image = image.scaled(image_width, image_height, Qt.KeepAspectRatio,
TypeError: arguments did not match any overloaded call:
  scaled(self, int, int, aspectRatioMode: Qt.AspectRatioMode = Qt.IgnoreAspectRatio, transformMode: Qt.TransformationMode = Qt.FastTransformation): argument 1 has unexpected type 'float'
  scaled(self, QSize, aspectRatioMode: Qt.AspectRatioMode = Qt.IgnoreAspectRatio, transformMode: Qt.TransformationMode = Qt.FastTransformation): argument 1 has unexpected type 'float'
```

</details>

In this PC, setting `export QT_QPA_PLATFORM=wayland` before running the command did nothing, but on my laptop (same OS, but not a clean install as this PC), I got the following info:

<details>

<summary>no qt platform plugin found message</summary>

```console
user@example:~$ spyder --debug-info verbose --debug-output terminal
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted (core dumped)
``` 

</details>

### Traceback
```python-traceback
  File "/usr/lib/python3/dist-packages/spyder/app/mainwindow.py", line 3378, in show_tour_message
    self.tour_dialog = tour.OpenTourDialog(
  File "/usr/lib/python3/dist-packages/spyder/app/tour.py", line 1415, in __init__
    image = image.scaled(image_width, image_height, Qt.KeepAspectRatio,
TypeError: arguments did not match any overloaded call:
  scaled(self, int, int, aspectRatioMode: Qt.AspectRatioMode = Qt.IgnoreAspectRatio, transformMode: Qt.TransformationMode = Qt.FastTransformation): argument 1 has unexpected type 'float'
  scaled(self, QSize, aspectRatioMode: Qt.AspectRatioMode = Qt.IgnoreAspectRatio, transformMode: Qt.TransformationMode = Qt.FastTransformation): argument 1 has unexpected type 'float'
```

## Versions

* Spyder version: 4.2.1 
* Python version: 3.10.4
* Qt version: 5.15.3
* PyQt5 version: 5.15.6
* Operating System: Linux 5.15.0-43-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  2.0.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=7.6.0                 :  7.31.1 (OK)
jedi >=0.17.2                   :  0.18.0 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  23.5.0 (OK)
nbconvert >=4.0                 :  6.4.0 (OK)
numpydoc >=0.6.0                :  1.2 (OK)
parso >=0.7.0                   :  0.8.1 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.9.0 (OK)
pygments >=2.0                  :  2.11.2 (OK)
pylint >=1.0                    :  2.12.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.4.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.1.1 (OK)
qtconsole >=5.0.1               :  5.2.2 (OK)
qtpy >=1.5.0                    :  2.0.0 (OK)
setuptools >=39.0.0             :  59.6.0 (OK)
sphinx >=0.6.6                  :  4.3.2 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.2 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  2.1.6 (OK)
xdg >=0.26                      :  0.27 (OK)
zmq >=17                        :  22.3.0 (OK)

# Optional:
cython >=0.21                   :  0.29.28 (OK)
matplotlib >=2.0.0              :  3.5.1 (OK)
numpy >=1.7                     :  1.21.5 (OK)
pandas >=1.1.1                  :  1.3.5 (OK)
scipy >=0.17.0                  :  1.8.0 (OK)
sympy >=0.7.3                   :  1.9 (OK)

# Spyder plugins:
spyder_line_profiler            :  0.2.1 (OK)
spyder_memory_profiler          :  0.2.1 (OK)
spyder_unittest                 :  0.4.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @rolandog, thanks for reporting. As you can read in [my answer](https://stackoverflow.com/a/72502984/438386) posted just below the one you referenced, this is not problem but Ubuntu's one because they packaged a really old Spyder version with a Python one that broke it.

The solution is to either use Anaconda/Miniconda or install Spyder in a virtualenv.

**Comment by rolandog** [comment]
Thanks @ccordoba12  for your reply; I'm sorry for having missed that!  I was in a rush and completely missed your comment, I have added a member of the Debian Science team (listed as maintainers of Ubuntu's Spyder package) to the [relevant bug on Ubuntu's bug tracker](https://bugs.launchpad.net/ubuntu/+source/spyder/+bug/1972112), hopefully this gets Spyder re-packaged.

**Comment by ccordoba12** [comment]
No worries, it's fine. I think @juliangilbey is actively working on getting the latest Spyder packaged in Debian.

**Comment by juliangilbey** [comment]
Hi @rolandog! We have Spyder 5.3.2 in Debian testing now, which should end up in the next Debian stable release (or more likely 5.3.3 or 5.3.4/5.4.0 by then); I presume that Ubuntu will pick this up one of these versions their next release.

**Comment by ccordoba12** [comment]
That's great news! Thanks @juliangilbey for your help with that.

**Comment by rolandog** [comment]
Awesome! Thanks so much @juliangilbey and @ccordoba12 .
