### ISSUE TITLE
Spyder crashes because pyzmq is missing

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1892]
_From [spencern...@gmail.com](https://code.google.com/u/100129837515765351203/) on 2014-07-17T10:24:36Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. starting Spyder from Linux 2. 3. 

What is the expected output? What do you see instead?

 Hoping for Spyder to start.  Instead, saw "Spyder crashed during last session.  If spyder does not start at all and before submitting a bug report, please try to reset settings to defaults by running Spyder with the command line option '--reset': python spyder --reset.  When I tried python spyder --reset, I got to the next line (as if the reset command executed), but when I went to start Spyder again, the same problem came back up. What version of the product are you using? On what operating system? Spyder Python Environment
Linux 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1892_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-24T23:55:18Z_

Does the informative Window appears every time you start Spyder?

Besides, what is your version?

**Comment by spyder-issues-migrator** [comment]
_From [chadharn...@gmail.com](https://code.google.com/u/102960724816149944506/) on 2014-11-05T18:41:41Z_

I am experiencing the same issue on Windows 8.1. Here's the output written to the spyder_crash.txt file: 

Traceback (most recent call last):
  File "C:\Users\Chad\Anaconda\lib\site-packages\spyderlib\spyder.py", line 2346, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\Chad\Anaconda\lib\site-packages\spyderlib\spyder.py", line 2234, in run_spyder
    main.setup()
  File "C:\Users\Chad\Anaconda\lib\site-packages\spyderlib\spyder.py", line 882, in setup
    from spyderlib.plugins.ipythonconsole import IPythonConsole
  File "C:\Users\Chad\Anaconda\lib\site-packages\spyderlib\plugins\ipythonconsole.py", line 32, in \<module>
    from IPython.lib.kernel import find_connection_file, get_connection_info
  File "C:\Users\Chad\Anaconda\lib\site-packages\IPython\lib\kernel.py", line 11, in \<module>
    from IPython.kernel.connect import *
  File "C:\Users\Chad\Anaconda\lib\site-packages\IPython\kernel\__init__.py", line 4, in \<module>
    from . import zmq
  File "C:\Users\Chad\Anaconda\lib\site-packages\IPython\kernel\zmq\__init__.py", line 14, in \<module>
    check_for_zmq('2.1.11', 'IPython.kernel.zmq')
  File "C:\Users\Chad\Anaconda\lib\site-packages\IPython\utils\zmqrelated.py", line 37, in check_for_zmq
    raise ImportError("%s requires pyzmq >= %s"%(required_by, minimum_version))
ImportError: IPython.kernel.zmq requires pyzmq >= 2.1.11

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-06T16:30:17Z_

Mmh, this is a problem with Anaconda. To sole it you need to run

conda install ipython-qtconsole

which will install the dependencies necessary to run the graphical IPython version that we use in Spyder.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-06T16:31:18Z_

**Summary:** Spyder crashes because pyzmq is missing  \<span class="oldvalue"> (was: Spyder crashed during last session) \</span>  
  **Labels:** MS-v2.3.2 Cat-IPythonConsole

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-06T16:32:34Z_

We are going to include a check to pyzmq to avoid this in the future

**Comment by spyder-issues-migrator** [comment]
_From [eduardo....@gmail.com](https://code.google.com/u/111844802485381349187/) on 2014-11-11T04:58:26Z_

I had the same problem in Ubuntu 12.04 (with spyder 2.1.9-1), but once I did "cd /usr/bin" I could successfully execute "python spyder --reset" that removed 6 files. That sorted out the problem and let me use spyder again.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-11T13:40:09Z_

Thanks for the comment Eduardo. In any case, we need to find a more robust approach to embed IPython because it's really bad for new users to see Spyder crashing for no good reason :-)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-12T10:20:39Z_

This issue was closed by revision f42e4199aeef .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-19T10:52:03Z_

issue #2059 has been merged into this issue.
