### ISSUE TITLE
Error when opening Preferences

### ISSUE THREAD

**Issue by suryaanoragajy** [spyder-ide/spyder#18929]
### What steps will reproduce the problem?

I Can't open setting, and it shows spyder has encontered an internal problem

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\Admin ACER\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\preferences\plugin.py", line 276, in <lambda>
    lambda: self.open_dialog(main.prefs_dialog_size))
  File "C:\Users\Admin ACER\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\preferences\plugin.py", line 256, in open_dialog
    container.create_dialog(
  File "C:\Users\Admin ACER\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\preferences\widgets\container.py", line 63, in create_dialog
    page.initialize()
  File "C:\Users\Admin ACER\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\preferences\api.py", line 80, in initialize
    self.setup_page()
  File "C:\Users\Admin ACER\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\appearance\confpage.py", line 157, in setup_page
    self.update_combobox()
  File "C:\Users\Admin ACER\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\appearance\confpage.py", line 240, in update_combobox
    combobox.addItem(self.get_option('{0}/name'.format(name)), name)
TypeError: arguments did not match any overloaded call:
  addItem(self, str, userData: Any = None): argument 1 has unexpected type 'float'
  addItem(self, QIcon, str, userData: Any = None): argument 1 has unexpected type 'float'
```

## Versions

* Spyder version: 5.3.2  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.0.0 (OK)
cloudpickle >=0.5.0                  :  2.1.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<8.0.0              :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.7.2 (OK)
keyring >=17.0.0                     :  23.6.0 (OK)
nbconvert >=4.0                      :  6.5.0 (OK)
numpydoc >=0.6.0                     :  1.4.0 (OK)
paramiko >=2.4.0                     :  2.11.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.1 (OK)
pygments >=2.0                       :  2.12.0 (OK)
pylint >=2.5.0;<3.0                  :  2.14.4 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0                 :  1.5.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0             :  5.3.1 (OK)
qtpy >=2.1.0                         :  2.1.0 (OK)
rtree >=0.9.7                        :  1.0.0 (OK)
setuptools >=49.6.0                  :  63.1.0 (OK)
sphinx >=0.6.6                       :  5.0.2 (OK)
spyder_kernels >=2.3.2;<2.4.0        :  2.3.2 (OK)
textdistance >=4.2.0                 :  4.3.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.1.9 (OK)
zmq >=22.1.0                         :  23.2.0 (OK)

# Optional:
cython >=0.21                        :  0.29.30 (OK)
matplotlib >=3.0.0                   :  3.5.2 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.4.3 (OK)
scipy >=0.17.0                       :  1.8.1 (OK)
sympy >=0.7.3                        :  1.10.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by dalthviz** [comment]
Hi @suryaanoragajy thank you for the feedback! Could you share with us your `spyder.ini` file? It should be at `C:\Users\<your user>\spyder-py3\config\spyder.ini`. Also, do you have custom syntax highlighting themes?

Any new info in order to reproduce this on our side is greatly appreciated. Let us know!

**Comment by dalthviz** [comment]
Note: I was able to reproduce this by naming a custom syntax highlighting theme with a number
