### ISSUE TITLE
nest_asyncio

### ISSUE THREAD

**Issue by kaleb-keny** [spyder-ide/spyder#18932]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
 
I am getting the a persistent error when loading a class through spyder console. Loading the same class on my windows os does not result in this error.
I am not sure if this is related to the usage of nest_asyncio, but removingit seems kill the error.
I'd be happy to share the repo privately.
```
import nest_asyncio
nest_asyncio.apply()
```

### What steps reproduce the problem?

1. Running a py class

### What is the expected output? What do you see instead?

Class loads into memory

### Paste Traceback/Error Below (if applicable)

```python-traceback

[SpyderKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/kaleb/miniconda3/envs/notify/lib/python3.7/site-packages/spyder_kernels/comms/frontendcomm.py", line 164, in poll_one
    asyncio.run(handler(out_stream, ident, msg))
  File "/home/kaleb/miniconda3/envs/notify/lib/python3.7/site-packages/nest_asyncio.py", line 33, in run
    task = asyncio.ensure_future(main)
  File "/home/kaleb/miniconda3/envs/notify/lib/python3.7/asyncio/tasks.py", line 619, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitable is required
[SpyderKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/kaleb/miniconda3/envs/notify/lib/python3.7/site-packages/spyder_kernels/comms/frontendcomm.py", line 164, in poll_one
    asyncio.run(handler(out_stream, ident, msg))
  File "/home/kaleb/miniconda3/envs/notify/lib/python3.7/site-packages/nest_asyncio.py", line 33, in run
    task = asyncio.ensure_future(main)
  File "/home/kaleb/miniconda3/envs/notify/lib/python3.7/asyncio/tasks.py", line 619, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitable is required
```

## Versions

* Spyder version: 5.1.5 None
* Python version: 3.7.13 64-bit
* Qt version: 5.12.1
* PyQt5 version: 5.12
* Operating System: Linux 5.15.0-43-generic
*
### Dependencies

```
NA
```

**Comment by dalthviz** [comment]
Hi @kaleb-keny thank you for feedback! Could you update to the latest release and check again? For that you will need to use the conda-forge channel. If you env uses already the conda-forge channel you can run from a termnial with your env activated something like:

    conda update -c conda-forge spyder

Let us know the update helps!

**Comment by kaleb-keny** [comment]
Hey I tried that 
`conda update -c conda-forge spyder`  it downloaded 5.1.5 automatically I think, I restarted, still same problem 🤔 

```
* Spyder version: 5.1.5 None
* Python version: 3.7.13 64-bit
* Qt version: 5.12.1
* PyQt5 version: 5.12
* Operating System: Linux 5.15.0-43-generic
```
```
[SpyderKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/kaleb/miniconda3/envs/notify/lib/python3.7/site-packages/spyder_kernels/comms/frontendcomm.py", line 164, in poll_one
    asyncio.run(handler(out_stream, ident, msg))
  File "/home/kaleb/miniconda3/envs/notify/lib/python3.7/site-packages/nest_asyncio.py", line 33, in run
    task = asyncio.ensure_future(main)
  File "/home/kaleb/miniconda3/envs/notify/lib/python3.7/asyncio/tasks.py", line 619, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitable is required
[SpyderKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/kaleb/miniconda3/envs/notify/lib/python3.7/site-packages/spyder_kernels/comms/frontendcomm.py", line 164, in poll_one
    asyncio.run(handler(out_stream, ident, msg))
  File "/home/kaleb/miniconda3/envs/notify/lib/python3.7/site-packages/nest_asyncio.py", line 33, in run
    task = asyncio.ensure_future(main)
  File "/home/kaleb/miniconda3/envs/notify/lib/python3.7/asyncio/tasks.py", line 619, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitable is required
```

**Comment by dalthviz** [comment]
🤔 then I think the best will be to create a new env using only the conda-forge channel. For that you can run from a terminal something like:

    conda create -n spyder-cf -c conda-forge spyder
    conda activate spyder-cf
    spyder

Or if you need an specific Python version, something like:

    conda create -n spyder-cf -c conda-forge python=3.7.13 spyder
    conda activate spyder-cf
    spyder

**Comment by kaleb-keny** [comment]
this solution worked perfectly

**Comment by dalthviz** [comment]
Awesome, glad the new env with the latest release worked for you @kaleb-keny :+1:

I'm going to close this one then but if you have any other questions let us know
