### ISSUE TITLE
spyder 2.3.0 won't start

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1897]
_From [nathan.r...@gmail.com](https://code.google.com/u/111915738251701263732/) on 2014-07-18T13:01:45Z_

I am trying to install spyder 2.3.0 on Fedora 20 (Heisenbug).

When I try to run spyder, I get the following output:
\#####################################################################################

[nate@fedora-home ~]$ spyder
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/spyderlib/spyder.py", line 2333, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python2.7/site-packages/spyderlib/spyder.py", line 2221, in run_spyder
    main.setup()
  File "/usr/lib/python2.7/site-packages/spyderlib/spyder.py", line 768, in setup
    message=_("DON'T USE THIS CONSOLE TO RUN CODE!\n\n"
  File "/usr/lib/python2.7/site-packages/spyderlib/plugins/console.py", line 74, in __init__
    self.find_widget.set_editor(self.shell)
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/findreplace.py", line 261, in set_editor
    from spyderlib.qt.QtWebKit import QWebView
  File "/usr/lib/python2.7/site-packages/spyderlib/qt/QtWebKit.py", line 10, in \<module>
    from PyQt4.QtWebKit import *  # analysis:ignore
ImportError: libQtWebKit.so.4: cannot open shared object file: No such file or directory

\#####################################################################################

I get the same result whether I install spyder from the yum repository or from pip.

I am running Python 2.7.5 (default, Jun 25 2014, 10:19:55) 
[GCC 4.8.2 20131212 (Red Hat 4.8.2-7)] on linux2

My machine has PyQt4 4.10.2 installed.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1897_

**Comment by spyder-issues-migrator** [comment]
_From [nathan.r...@gmail.com](https://code.google.com/u/111915738251701263732/) on 2014-07-18T12:02:07Z_

Problem solved. I just needed to install qtwebkit. I discovered this by running: 

yum whatprovides "*/libQtWebKit.so.4"

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-07-19T13:06:59Z_

I remember having this problem on centos too. I created a bug report for Redhat: https://bugzilla.redhat.com/show_bug.cgi?id=1121360

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-07-31T04:19:06Z_

THe bug should be fixed, could you confirm that the dependancy was added in Fedora ?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-17T10:19:52Z_

Out of our reach. I hope Fedora guys fix it.

**Status:** Invalid

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-08-20T00:18:57Z_

Actually, qtwebkit is already a dependancy of spyder via PyQt4 in fedora20. installing from yum should have installed it.
