### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by h0l0gr4ph** [spyder-ide/spyder#19036]
### What steps will reproduce the problem?

starting spyder or literaly doing anything in spyder

### Traceback
```python-traceback
Error on reading from the event loop self pipe
loop: <ProactorEventLoop running=True closed=False debug=False>
Traceback (most recent call last):
  File "D:\WinPython\WPy64-3820\python-3.8.2.amd64\lib\asyncio\windows_events.py", line 453, in finish_recv
    return ov.getresult()
OSError: [WinError 995] Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WinPython\WPy64-3820\python-3.8.2.amd64\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "D:\WinPython\WPy64-3820\python-3.8.2.amd64\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "D:\WinPython\WPy64-3820\python-3.8.2.amd64\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 995] Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen
```

## Versions

* Spyder version: 5.3.2  (pip)
* Python version: 3.8.2 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.4
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.3.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  1.3.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20181111 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0       :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  21.2.0 (OK)
nbconvert >=4.0               :  5.6.1 (OK)
numpydoc >=0.6.0              :  0.9.2 (OK)
paramiko >=2.4.0              :  2.7.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.7.0 (OK)
pygments >=2.0                :  2.6.1 (OK)
pylint >=2.5.0;<3.0           :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.1 (OK)
qtpy >=2.1.0                  :  2.1.0 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  63.4.2 (OK)
sphinx >=0.6.6                :  2.4.4 (OK)
spyder_kernels >=2.3.2;<2.4.0 :  2.3.2 (OK)
textdistance >=4.2.0          :  4.3.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.15 (OK)
matplotlib >=3.0.0            :  3.2.1 (OK)
numpy >=1.7                   :  1.18.2 (OK)
pandas >=1.1.1                :  1.0.3 (NOK)
scipy >=0.17.0                :  1.4.1 (OK)
sympy >=0.7.3                 :  1.5.1 (OK)
```

**Comment by dalthviz** [comment]
Hi @h0l0gr4ph thank you for the feedback! Seems like you are using WinPython? We have had some issues with a similar traceback but we haven't had ways to reproduce this in our side :/

However, checking the traceback, seems like an issue about that is open at https://github.com/ipython/ipython/issues/12049 and also a comment with a workaround/patch code is available https://github.com/ipython/ipython/issues/12049#issuecomment-586544339

Also seems like doing a downgrade to `prompt-toolkit` could help: https://github.com/ipython/ipython/issues/12049#issuecomment-640275866

Let us know if the info above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
