### ISSUE TITLE
the system cannot find path specified

### ISSUE THREAD

**Issue by vidhi0206** [spyder-ide/spyder#19049]
## Problem Description
created a new environment, then installed spyder kernels. then added the environment in the preference.
`The system cannot find the path specified.
Traceback (most recent call last):
File "C:\Users\HP\.conda\envs\myenv\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\HP\.conda\envs\myenv\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\HP\.conda\envs\myenv\lib\site‑packages\spyder_kernels\console\__main__.py", line 22, in 
from spyder_kernels.console import start
File "C:\Users\HP\.conda\envs\myenv\lib\site‑packages\spyder_kernels\console\start.py", line 21, in 
import ipykernel
File "C:\Users\HP\.conda\envs\myenv\lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\HP\.conda\envs\myenv\lib\site‑packages\ipykernel\connect.py", line 10, in 
import jupyter_client
File "C:\Users\HP\.conda\envs\myenv\lib\site‑packages\jupyter_client\__init__.py", line 4, in 
from .connect import *
File "C:\Users\HP\.conda\envs\myenv\lib\site‑packages\jupyter_client\connect.py", line 21, in 
import zmq
File "C:\Users\HP\.conda\envs\myenv\lib\site‑packages\zmq\__init__.py", line 103, in 
from zmq import backend
File "C:\Users\HP\.conda\envs\myenv\lib\site‑packages\zmq\backend\__init__.py", line 31, in 
raise original_error from None
File "C:\Users\HP\.conda\envs\myenv\lib\site‑packages\zmq\backend\__init__.py", line 26, in 
_ns = select_backend(first)
File "C:\Users\HP\.conda\envs\myenv\lib\site‑packages\zmq\backend\select.py", line 31, in select_backend
mod = import_module(name)
File "C:\Users\HP\.conda\envs\myenv\lib\importlib\__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "C:\Users\HP\.conda\envs\myenv\lib\site‑packages\zmq\backend\cython\__init__.py", line 6, in 
from . import (
ImportError: DLL load failed: The specified module could not be found.`

### What steps reproduce the problem?

1. created a new environment, then installed spyder kernels. then added the environment in the preference.
2. Then tried to import cv2 and use it.
3. above issue is occuring.

**Comment by ccordoba12** [comment]
Hey @vidhi0206, thanks for reporting. What command did you use to install spyder-kernels in your environment?

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by carlotaSG** [comment]
Hi! I have the same problem! the command I used to install spyder-kernels was
`conda install -c conda-forge spyder-kernels=2.1.3`

The version of Spyder I have is 5.1.5

**Comment by ccordoba12** [comment]
Hey @carlotaSG, it seems you're missing conda and conda-forge packages, which could be the cause of this problem too. Please open the Anaconda Prompt (or a terminal if you're using Mac or Linux), run there

    conda list

and post the result here.
