### ISSUE TITLE
kivy window closure issue

### ISSUE THREAD

**Issue by githiakalaban** [spyder-ide/spyder#19057]
### What steps will reproduce the problem?

when i try to close the window after running a python kivy file, it tends to hang when i try to close open window

### Traceback
```python-traceback
  File "/usr/lib/python3.9/asyncio/tasks.py", line 258, in __step
    result = coro.throw(exc)
  File "/home/laban/.local/lib/python3.9/site-packages/jupyter_client/manager.py", line 636, in _async_wait
    await asyncio.sleep(pollinterval)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 654, in sleep
    return await future
  File "/usr/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/usr/lib/python3.9/asyncio/futures.py", line 196, in result
    raise exc
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
  File "/usr/lib/python3.9/asyncio/futures.py", line 196, in result
    raise exc
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/laban/.local/lib/python3.9/site-packages/jupyter_client/manager.py", line 433, in _async_finish_shutdown
    await asyncio.wait_for(
  File "/usr/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laban/.local/lib/python3.9/site-packages/jupyter_client/manager.py", line 75, in wrapper
    out = await method(self, *args, **kwargs)
  File "/home/laban/.local/lib/python3.9/site-packages/jupyter_client/manager.py", line 498, in _async_shutdown_kernel
    await ensure_async(self.finish_shutdown(restart=restart))
  File "/home/laban/.local/lib/python3.9/site-packages/jupyter_client/utils.py", line 30, in wrapped
    raise e
  File "/home/laban/.local/lib/python3.9/site-packages/jupyter_client/utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "/home/laban/.local/lib/python3.9/site-packages/nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "/usr/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/usr/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/home/laban/.local/lib/python3.9/site-packages/jupyter_client/manager.py", line 439, in _async_finish_shutdown
    await ensure_async(self._kill_kernel(restart=restart))
TypeError: _kill_kernel() got an unexpected keyword argument 'restart'
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/tasks.py", line 258, in __step
    result = coro.throw(exc)
  File "/home/laban/.local/lib/python3.9/site-packages/jupyter_client/manager.py", line 636, in _async_wait
    await asyncio.sleep(pollinterval)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 654, in sleep
    return await future
  File "/usr/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/usr/lib/python3.9/asyncio/futures.py", line 196, in result
    raise exc
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
  File "/usr/lib/python3.9/asyncio/futures.py", line 196, in result
    raise exc
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/laban/.local/lib/python3.9/site-packages/jupyter_client/manager.py", line 433, in _async_finish_shutdown
    await asyncio.wait_for(
  File "/usr/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spyder/plugins/ipythonconsole/widgets/client.py", line 642, in _restart_thread_main
    self.shellwidget.kernel_manager.restart_kernel(
  File "/home/laban/.local/lib/python3.9/site-packages/jupyter_client/utils.py", line 30, in wrapped
    raise e
  File "/home/laban/.local/lib/python3.9/site-packages/jupyter_client/utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "/home/laban/.local/lib/python3.9/site-packages/nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "/usr/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/usr/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/home/laban/.local/lib/python3.9/site-packages/jupyter_client/manager.py", line 535, in _async_restart_kernel
    await ensure_async(self.shutdown_kernel(now=now, restart=True))
  File "/home/laban/.local/lib/python3.9/site-packages/jupyter_client/utils.py", line 30, in wrapped
    raise e
  File "/home/laban/.local/lib/python3.9/site-packages/jupyter_client/utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "/home/laban/.local/lib/python3.9/site-packages/nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "/usr/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/usr/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/home/laban/.local/lib/python3.9/site-packages/jupyter_client/manager.py", line 83, in wrapper
    raise e
  File "/home/laban/.local/lib/python3.9/site-packages/jupyter_client/manager.py", line 75, in wrapper
    out = await method(self, *args, **kwargs)
  File "/home/laban/.local/lib/python3.9/site-packages/jupyter_client/manager.py", line 498, in _async_shutdown_kernel
    await ensure_async(self.finish_shutdown(restart=restart))
  File "/home/laban/.local/lib/python3.9/site-packages/jupyter_client/utils.py", line 30, in wrapped
    raise e
  File "/home/laban/.local/lib/python3.9/site-packages/jupyter_client/utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "/home/laban/.local/lib/python3.9/site-packages/nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "/usr/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/usr/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/home/laban/.local/lib/python3.9/site-packages/jupyter_client/manager.py", line 439, in _async_finish_shutdown
    await ensure_async(self._kill_kernel(restart=restart))
TypeError: _kill_kernel() got an unexpected keyword argument 'restart'
```

## Versions

* Spyder version: 4.2.1 
* Python version: 3.9.2
* Qt version: 5.15.2
* PyQt5 version: 5.15.2
* Operating System: Linux 5.18.0-14parrot1-amd64

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=7.6.0                 :  8.4.0 (OK)
jedi >=0.17.2                   :  0.18.0 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.0.1 (OK)
nbconvert >=4.0                 :  6.5.3 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso >=0.7.0                   :  0.8.1 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.7.1 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
setuptools >=39.0.0             :  52.0.0 (OK)
sphinx >=0.6.6                  :  3.4.3 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  1.0.2 (OK)
xdg >=0.26                      :  0.27 (OK)
zmq >=17                        :  23.2.1 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.19.5 (OK)
pandas >=1.1.1                  :  1.4.3 (OK)
scipy >=0.17.0                  :  1.6.0 (OK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @githiakalaban, thanks for reporting. Please update to our latest version (5.3.2) and try again. It should solve your problem, but let us know.

By the way, I'd recommend you to stop mixing distro packages (i.e. the one installed in `/usr/lib/python3/dist-packages`) with ones installed by you with pip (i.e. in `/home/laban/.local/lib/python3.9/site-packages`). That's just the source of endless confusions and headaches for users.

Instead, please use Anaconda/Miniconda or `mkvirtualenv` to install and environment and install all packages you need on it.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by typedecker** [comment]
@ccordoba12 im facing a similar issue in spyder version 6.0.5, once the program has stopped execution due to me clicking the exit button on the window, the window just hangs in place after a bit, is there a workaround for this? or a way that I can fix it? I am not sure if I am doing something wrong or it is just a bug with spyder, but I thought I'd ask

**Comment by ccordoba12** [comment]
@typedecker, just to be clear: are you using Kivy in Spyder? If so, please post a simple code example that we can use to reproduce your problem on our side.

**Comment by typedecker** [comment]
@ccordoba12 Yes, and the code I was running was the very base example provided in the docs:

```py
import kivy

from kivy.app import App
from kivy.uix.label import Label


class MyApp(App):

    def build(self):
        return Label(text='Hello world')


if __name__ == '__main__':
    MyApp().run()
```

The window shows up in realtime and it runs perfectly, but when I try to close the window after I am done testing it, it hangs even though the actual program execution stops. I have also tried running this on the command line and it works as intended, so I am guessing that the problem lies somewhere in the way that spyder handles it's execution. Also, using commands within ipython console and running the kivy code that way using the `!python name_of_the_file.py` command, works just as intended as well.

**Comment by DJuego** [comment]
H! @ccordoba12 & Co. I confirm that this problem exists as described by @typedecker. I join him in requesting that this be evaluated for fixing.  That would help me decide on Kivy as my next graphical user interface in Python. Please, would it be possible to reopen this issue? Or perhaps it would be better to create a new issue describing this same problem?  

Thanks!

DJuego

**Comment by ccordoba12** [comment]
According to [this comment](https://github.com/kivy/kivy/issues/6958#issuecomment-646993586) from one of Kivy's maintainers:

> It's not really a great idea to run kivy from jupyter (even if it works, you'll have to restart the kernel after each run, and there is no benefit that i can think of of the way jupyter works with kivy) ,

Since Spyder uses the same execution architecture as Jupyter, it has the same limitations.

The best solution we can offer you for now is to run your Kivy code in an external terminal (instead of in the IPython console). For that, you need to

* Go to the menu entry `Run > Configuration per file`
* Select `External Terminal` runner there and disable the option called `Interact with the interpreter after execution`

    <img width="541" height="645" alt="Image" src="https://github.com/user-attachments/assets/e613b419-26fe-47fa-9ac3-05f6c20255c0" />

* Run the file with the menu entry `Run > Run in external terminal`.

That will give the same experience you get when running `python name_of_the_file.py` in a terminal.

**Comment by typedecker** [comment]
@ccordoba12 Ah thanks so much for reaching out! I do know about this feature and was thinking of using this as a last resort if nothing else could be done about this, so I shall use this then! its understandable (: thanks so much for helping with this though <33 Also, this is an unrelated question, but is there a way for me to run a console command of my own choice programmatically using the spyder python module? I have already used the module to open files programmatically in the past and have been using that at times to make custom scripts for me to run as commands when developing things, and it'd be helpful if I could also do that! or possibly change the current working directory of the ipython console, or modify the command that gets executed in the ipython console when the run button is hit
