### ISSUE TITLE
Cython not imported in Spyder

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1909]
_From [himadrig...@gmail.com](https://code.google.com/u/114957285360917796307/) on 2014-07-26T05:28:22Z_

Spyder Version:  2.1.13.1
Python Version:  2.7.4
Qt Version:      4.8.4, PyQt4 (API v2) 4.10 on Linux 

What steps will reproduce the problem?

 1. Inside Spyder Console (Python 1) type "import cython"
2. Error message "Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
ImportError: No module named cython" 3. 

What is the expected output? What do you see instead?

 Expected: No error message
See instead: Error message "Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
ImportError: No module named cython" 

Please provide any additional information below

. Cython and pyximport are installed on the system. This is tested by running ipython from a terminal. Both "import cython" and "import pyximport" work fine (no error message and can be used to generate cython code). Would like to be able to import cython inside Spyder though. Other packages like numpy, matplotlib, scipy are all imported ok within Spyder.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1909_

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-07-26T12:07:13Z_

It looks like spyder is not using the system interpreter. For example spyder could be launched with python2 while cython is installed for python3. Can you run "import sys; sys.executable" in both consoles to check if there the same ?

Also, your spyder version (2.1) is quite outdated, you should use the version 2.3 which went live very recently.

**Comment by spyder-issues-migrator** [comment]
_From [himadrig...@gmail.com](https://code.google.com/u/114957285360917796307/) on 2014-07-26T13:36:22Z_

Thanks - yes that is the issue. The outputs are different as you suggested.

Ipython from console (cython working ok): '/home/himadri/anaconda/bin/python'
Ipython from spyder: '/usr/bin/python'

(as you can see I installed Anaconda python recently, possibly conflicting with an earlier python install)

Tried to fix it in the preferences dialog to the anaconda path, but spyder gave a series of errors on startup, starting with

"RuntimeError: module compiled against API version 9 but this version of numpy is 7
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/scientific_startup.py", line 16, in \<module>
    from pylab import *  #analysis:ignore
..."

Have noted this does seem to be flagged in (e.g.) issue #1415 , so will see if I can find a workaround...

Thanks again
Himadri

**Comment by spyder-issues-migrator** [comment]
_From [himadrig...@gmail.com](https://code.google.com/u/114957285360917796307/) on 2014-07-26T13:45:34Z_

Sorted following the suggestion of contrebasse by uninstalling earlier Spyder version (probably from the original Linux install) and doing "conda install spyder" in the /home/himadri/anaconda directory. 

Cython and pyximport work fine now from spyder.

Now just need to find a way to add the icon to my start menu...

thanks for the help!

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-24T23:19:33Z_

**Status:** WontFix
