### ISSUE TITLE
Jus' checking the olde preferences menu 

### ISSUE THREAD

**Issue by mccurcio** [spyder-ide/spyder#19178]
### What steps will reproduce the problem?

Checking the preferences menu, changing ipython console confirmations.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/mcc/anaconda3/lib/python3.9/site-packages/spyder/plugins/preferences/widgets/configdialog.py", line 127, in accept
    configpage.apply_changes()
  File "/home/mcc/anaconda3/lib/python3.9/site-packages/spyder/plugins/preferences/api.py", line 108, in apply_changes
    self.apply_callback()
  File "/home/mcc/anaconda3/lib/python3.9/site-packages/spyder/plugins/preferences/api.py", line 140, in <lambda>
    self._apply_settings_tabs(self.changed_options))
  File "/home/mcc/anaconda3/lib/python3.9/site-packages/spyder/plugins/preferences/api.py", line 168, in _apply_settings_tabs
    self.apply_settings(options)
  File "/home/mcc/anaconda3/lib/python3.9/site-packages/spyder/api/preferences.py", line 105, in wrapper
    func(opts)
  File "/home/mcc/anaconda3/lib/python3.9/site-packages/spyder/api/plugins/new_api.py", line 550, in apply_conf
    self.after_configuration_update(list(options_set))
  File "/home/mcc/anaconda3/lib/python3.9/site-packages/spyder/plugins/completion/plugin.py", line 403, in after_configuration_update
    self.unregister_statusbar(provider_name)
  File "/home/mcc/anaconda3/lib/python3.9/site-packages/spyder/plugins/completion/plugin.py", line 477, in unregister_statusbar
    if id_ in container.statusbar_widgets[id_]:
TypeError: argument of type 'KiteStatusWidget' is not iterable
```

## Versions

* Spyder version: 5.2.2 
* Python version: 3.9.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 5.19.0-76051900-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  63.4.1 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.30 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.3 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @mccurcio, thanks for reporting. This error is already fixed in our latest version (5.3.2).

Since it's still not available in Anaconda, you need to create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

    conda create -n spyder-cf -c conda-forge spyder
    conda activate spyder-cf
    spyder
