### ISSUE TITLE
Preferences not showing

### ISSUE THREAD

**Issue by vineetgupta086** [spyder-ide/spyder#19201]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

Go to Tools > Preferences. <br/>
This just would not open. <br/> <br/>
More details: <br/> <br/>
Traceback (most recent call last):
  File "D:\Projects\Python Modelling\lifelib\WPy64-31020\python-3.10.2.amd64\lib\site-packages\spyder\plugins\preferences\plugin.py", line 276, in <lambda>
    lambda: self.open_dialog(main.prefs_dialog_size))
  File "D:\Projects\Python Modelling\lifelib\WPy64-31020\python-3.10.2.amd64\lib\site-packages\spyder\plugins\preferences\plugin.py", line 256, in open_dialog
    container.create_dialog(
  File "D:\Projects\Python Modelling\lifelib\WPy64-31020\python-3.10.2.amd64\lib\site-packages\spyder\plugins\preferences\widgets\container.py", line 62, in create_dialog
    page.initialize()
  File "D:\Projects\Python Modelling\lifelib\WPy64-31020\python-3.10.2.amd64\lib\site-packages\spyder\plugins\preferences\api.py", line 80, in initialize
    self.setup_page()
  File "D:\Projects\Python Modelling\lifelib\WPy64-31020\python-3.10.2.amd64\lib\site-packages\spyder\api\plugin_registration\_confpage.py", line 71, in setup_page
    plugin_loc_name = PluginClass.get_name()
TypeError: ModelxPlugin.get_name() missing 1 required positional argument: 'self'

**Comment by ccordoba12** [comment]
Hey @vineetgupta086, thanks for reporting. This is not a problem with Spyder but with the Modelx external plugin.

So, please report it here:

https://github.com/fumitoh/spyder-modelx
