### ISSUE TITLE
empty cell execution causes internal terminal traceback, user loses editor focus

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1920]
_From [educh...@gmail.com](https://code.google.com/u/100530934175546573091/) on 2014-08-01T03:26:12Z_

Spyder Version:  2.3.0beta2
Python Version:  3.3.5
Qt Version    :  4.8.4, PyQt4 (API v2) 4.9.6 on Windows
pyflakes >=0.6.0:  None (OK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  2.0.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  1.1.0 (OK)

Steps to reproduce the problem:

1. Create an empty cell like:

\#&#37;&#37;

\#

2. Execute the cell in the console (ctrl-enter)

Expected output:
Since the cell is empty, nothing should happend

Instead:
The internal terminal brings to front, with traceback:

\>>> Traceback (most recent call last):
  File "D:\bin\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\widgets\editor.py", line 1948, in run_cell
    text = self.get_current_editor().get_cell_as_executable_code()
  File "D:\bin\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\widgets\sourcecode\base.py", line 504, in get_cell_as_executable_code
    text = self.get_selection_as_executable_code()
  File "D:\bin\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\spyderlib\widgets\sourcecode\base.py", line 466, in get_selection_as_executable_code
    first_line = lines[0].lstrip()
IndexError: list index out of range

and the user loses editor focus 

Additional information.

I've checked that simply adding check in line 466 file 'base.py':

        while first_line == '' or first_line[0] == '#':
            lines.pop(0)
            \# check if no more lines, nothing to do
            if not lines:   
                return ''
            \# end
            first_line = lines[0].lstrip()

solves the problem.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1920_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-17T14:14:46Z_

Please update to the final version of 2.3.0 (because right now you're using beta2). This was fixed a long time ago.

**Status:** WontFix
