### ISSUE TITLE
Bug when changing output and input prompts in the IPython console

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1923]
_From [clgpaste...@gmail.com](https://code.google.com/u/108074911661659942835/) on 2014-08-02T16:30:34Z_

Spyder Version:  2.3.0rc
Python Version:  3.4.1
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Windows
pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  2.1.0 (OK)
pygments >=1.6  :  1.6 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  2.1.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1. go to preferences
2. go to console preference
3. change input and output display
I type:
\>>> for input
and
\<<< for output

Restart a new console (or spyder)
\>>> appears now instead of in[1]
type a number after >>>
EX:
\>>>0.1
A error appears in internal console:
Inspect Spyder internals:
  spy.app, spy.window, dir(spy)
\>>> Traceback (most recent call last):
  File "C:\cpge\Anaconda3\lib\site-packages\IPython\qt\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\cpge\Anaconda3\lib\site-packages\IPython\qt\console\rich_ipython_widget.py", line 138, in _handle_pyout
    return super(RichIPythonWidget, self)._handle_pyout(msg)
  File "C:\cpge\Anaconda3\lib\site-packages\IPython\qt\console\ipython_widget.py", line 237, in _handle_pyout
    self._append_html(self._make_out_prompt(prompt_number), True)
  File "C:\cpge\Anaconda3\lib\site-packages\IPython\qt\console\ipython_widget.py", line 544, in _make_out_prompt
    body = self.out_prompt &#37; number
TypeError: not all arguments converted during string formatting 

What is the expected output? What do you see instead?

 the output expected was just the typed number....
Instead, nothing in python console. 

Please provide any additional information below

. Thank you

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1923_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-17T10:04:37Z_

I confirm the bug. Thanks for reporting.

**Summary:** Bug when changing output and input prompts in the IPython console  \<span class="oldvalue"> (was: console bug when change output (and input display)) \</span>  
  **Status:** Accepted  
  **Labels:** Cat-IPythonConsole MS-v2.3.2

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-17T10:18:00Z_

This is a bug in IPython itself. I'll send them a PR to fix it, so you'll have to wait until they release a new version.

**Labels:** -MS-v2.3.2 MS-v2.4

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-17T13:23:43Z_

This is the corresponding IPython pull request https://github.com/ipython/ipython/pull/6328

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-09-04T15:22:20Z_

My pull request was merged in IPython master, so it'll be released with its 3.0 version (in a couple of months).

**Status:** Fixed
