### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted

### ISSUE THREAD

**Issue by Reguillot** [spyder-ide/spyder#19393]
### What steps will reproduce the problem?

Open 132 python files at once.
Maybe after setting the spyder default view a few times.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/reg/.conda/envs/green2_testing/lib/python3.10/site-packages/spyder/plugins/editor/widgets/editor.py", line 2524, in <lambda>
    lambda: self.update_code_analysis_actions.emit())
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/reg/.conda/envs/green2_testing/lib/python3.10/site-packages/spyder/plugins/editor/widgets/editor.py", line 2524, in <lambda>
    lambda: self.update_code_analysis_actions.emit())
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/reg/.conda/envs/green2_testing/lib/python3.10/site-packages/spyder/plugins/editor/widgets/editor.py", line 2524, in <lambda>
    lambda: self.update_code_analysis_actions.emit())
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/reg/.conda/envs/green2_testing/lib/python3.10/site-packages/spyder/plugins/editor/widgets/editor.py", line 2524, in <lambda>
    lambda: self.update_code_analysis_actions.emit())
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/reg/.conda/envs/green2_testing/lib/python3.10/site-packages/spyder/plugins/editor/widgets/editor.py", line 2524, in <lambda>
    lambda: self.update_code_analysis_actions.emit())
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/reg/.conda/envs/green2_testing/lib/python3.10/site-packages/spyder/plugins/editor/widgets/editor.py", line 2524, in <lambda>
    lambda: self.update_code_analysis_actions.emit())
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/reg/.conda/envs/green2_testing/lib/python3.10/site-packages/spyder/plugins/editor/widgets/editor.py", line 2524, in <lambda>
    lambda: self.update_code_analysis_actions.emit())
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/reg/.conda/envs/green2_testing/lib/python3.10/site-packages/spyder/plugins/editor/widgets/editor.py", line 2524, in <lambda>
    lambda: self.update_code_analysis_actions.emit())
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/reg/.conda/envs/green2_testing/lib/python3.10/site-packages/spyder/plugins/editor/widgets/editor.py", line 2524, in <lambda>
    lambda: self.update_code_analysis_actions.emit())
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/reg/.conda/envs/green2_testing/lib/python3.10/site-packages/spyder/plugins/editor/widgets/editor.py", line 2524, in <lambda>
    lambda: self.update_code_analysis_actions.emit())
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/reg/.conda/envs/green2_testing/lib/python3.10/site-packages/spyder/plugins/editor/widgets/editor.py", line 2524, in <lambda>
    lambda: self.update_code_analysis_actions.emit())
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/reg/.conda/envs/green2_testing/lib/python3.10/site-packages/spyder/plugins/editor/widgets/editor.py", line 2524, in <lambda>
    lambda: self.update_code_analysis_actions.emit())
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/reg/.conda/envs/green2_testing/lib/python3.10/site-packages/spyder/plugins/editor/widgets/editor.py", line 2524, in <lambda>
    lambda: self.update_code_analysis_actions.emit())
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/reg/.conda/envs/green2_testing/lib/python3.10/site-packages/spyder/plugins/editor/widgets/editor.py", line 2524, in <lambda>
    lambda: self.update_code_analysis_actions.emit())
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/reg/.conda/envs/green2_testing/lib/python3.10/site-packages/spyder/plugins/editor/widgets/editor.py", line 2524, in <lambda>
    lambda: self.update_code_analysis_actions.emit())
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/reg/.conda/envs/green2_testing/lib/python3.10/site-packages/spyder/plugins/editor/widgets/editor.py", line 2524, in <lambda>
    lambda: self.update_code_analysis_actions.emit())
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
Traceback (most recent call last):
  File "/home/reg/.conda/envs/green2_testing/lib/python3.10/site-packages/spyder/plugins/editor/widgets/editor.py", line 2524, in <lambda>
    lambda: self.update_code_analysis_actions.emit())
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
```

## Versions

* Spyder version: 5.3.3  (conda)
* Python version: 3.10.6 64-bit
* Qt version: 5.15.4
* PyQt5 version: 5.15.7
* Operating System: Linux 5.19.3-gentoo-x86_64

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.0.0 (OK)
cloudpickle >=0.5.0           :  2.1.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.15.0 (OK)
keyring >=17.0.0              :  23.9.1 (OK)
nbconvert >=4.0               :  7.0.0 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.2 (OK)
pygments >=2.0                :  2.13.0 (OK)
pylint >=2.5.0;<3.0           :  2.15.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.2 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  65.3.0 (OK)
sphinx >=0.6.6                :  5.1.1 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.4.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
xdg >=0.26                    :  0.28 (OK)
zmq >=22.1.0                  :  23.2.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  1.23.2 (OK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @Reguillot, thanks for reporting. We'll try to fix this problem for our next version (5.4.0), to be released next month.
