### ISSUE TITLE
Ipython doesn't open in spyder

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1939]
_From [ualsbo...@gmail.com](https://code.google.com/u/104605628486501250327/) on 2014-08-20T04:33:07Z_

Spyder Version:  2.3.0
Python Version:  2.7.8
Qt Version    :  4.8.5, PyQt4 (API v2) 4.10.4 on Linux
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.6 (OK)
IPython >=0.13  :  2.2.0 (OK)
pygments >=1.6  :  1.6 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  2.1.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  1.1.0 (OK) 

What steps will reproduce the problem?

 1. Opening an IPython Console 2. 3. 

What is the expected output? What do you see instead?

 I expect an IPython console. I get the following error message.

'import sitecustomize' failed; use ‑v for traceback
Traceback (most recent call last):
File "/home/lau/anaconda/lib/python2.7/site‑packages/spyderlib/widgets/externalshell/start_ipython_kernel.py", line 183, in 
from IPython.zmq.ipkernel import IPKernelApp # 0.13 (analysis:ignore)
File "/home/lau/anaconda/lib/python2.7/site‑packages/IPython/__init__.py", line 45, in 
from .config.loader import Config
File "/home/lau/anaconda/lib/python2.7/site‑packages/IPython/config/__init__.py", line 16, in 
from .application import *
File "/home/lau/anaconda/lib/python2.7/site‑packages/IPython/config/application.py", line 104, in 
class LevelFormatter(logging.Formatter):
AttributeError: 'module' object has no attribute 'Formatter' 

Please provide any additional information below

. I'm using Linux Mint 17. I'm in an Anaconda environment

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1939_

**Comment by spyder-issues-migrator** [comment]
_From [Ferdinan...@gmail.com](https://code.google.com/u/109159324361825205743/) on 2014-09-24T00:44:30Z_

Just update your anaconda distribution by writing:

$ conda update ipython

Worked for me at least...

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T17:43:49Z_

Yes, this seems an installation problem. Sorry to not being able to give you more help.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T17:43:59Z_

**Status:** WontFix
