### ISSUE TITLE
installed Spyder-terminal and View menu is missing Spyder-Terminal optino

### ISSUE THREAD

**Issue by richlysakowski** [spyder-ide/spyder#19391]
### What steps will reproduce the problem?

INstall Spyder-Terminal into conda virtual environment.  Restart Spyder, go to View...Panes to enable it, and no menu appears for Terminal 

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\streamlit\lib\site-packages\spyder\plugins\preferences\plugin.py", line 276, in <lambda>
    lambda: self.open_dialog(main.prefs_dialog_size))
  File "C:\ProgramData\Anaconda3\envs\streamlit\lib\site-packages\spyder\plugins\preferences\plugin.py", line 256, in open_dialog
    container.create_dialog(
  File "C:\ProgramData\Anaconda3\envs\streamlit\lib\site-packages\spyder\plugins\preferences\widgets\container.py", line 63, in create_dialog
    page.initialize()
  File "C:\ProgramData\Anaconda3\envs\streamlit\lib\site-packages\spyder\plugins\preferences\api.py", line 80, in initialize
    self.setup_page()
  File "C:\ProgramData\Anaconda3\envs\streamlit\lib\site-packages\spyder\api\plugin_registration\_confpage.py", line 78, in setup_page
    plugin_loc_name = PluginClass.get_name()
TypeError: get_name() missing 1 required positional argument: 'self'
```

## Versions

* Spyder version: 5.3.2  (conda)
* Python version: 3.8.13 64-bit
* Qt version: 5.15.4
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.0.0 (OK)
cloudpickle >=0.5.0           :  2.1.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.7.2 (OK)
keyring >=17.0.0              :  23.7.0 (OK)
nbconvert >=4.0               :  6.5.0 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.11.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.1 (OK)
pygments >=2.0                :  2.12.0 (OK)
pylint >=2.5.0;<3.0           :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.1 (OK)
qtpy >=2.1.0                  :  2.1.0 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  63.2.0 (OK)
sphinx >=0.6.6                :  5.1.1 (OK)
spyder_kernels >=2.3.2;<2.4.0 :  2.3.2 (OK)
textdistance >=4.2.0          :  4.3.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.23.1 (OK)
pandas >=1.1.1                :  1.4.3 (OK)
scipy >=0.17.0                :  1.8.1 (OK)
sympy >=0.7.3                 :  None (NOK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at C:\ProgramData\Anaconda3\envs\streamlit:
#
# Name                    Version                   Build  Channel
abseil-cpp                20210324.2           h0e60522_0    conda-forge
aiodns                    3.0.0                    pypi_0    pypi
aiohttp                   3.8.1                    pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
alabaster                 0.7.12                     py_0    conda-forge
altair                    4.2.0              pyhd8ed1ab_1    conda-forge
anyio                     3.6.1            py38haa244fe_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py38h294d835_2    conda-forge
arrow                     1.2.2              pyhd8ed1ab_0    conda-forge
arrow-cpp                 8.0.0           py38h61ae8a5_3_cpu    conda-forge
astroid                   2.11.6           py38haa244fe_0    conda-forge
asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2                    pypi_0    pypi
async_generator           1.10                       py_0    conda-forge
atomicwrites              1.4.1              pyhd8ed1ab_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
autopep8                  1.6.0              pyhd8ed1ab_1    conda-forge
aws-c-cal                 0.5.11               he19cf47_0    conda-forge
aws-c-common              0.6.2                h8ffe710_0    conda-forge
aws-c-event-stream        0.2.7               h70e1b0c_13    conda-forge
aws-c-io                  0.10.5               h2fe331c_0    conda-forge
aws-checksums             0.1.11               h1e232aa_7    conda-forge
aws-sdk-cpp               1.8.186              hb0612c5_3    conda-forge
babel                     2.10.3             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
backports.zoneinfo        0.2.1            py38h294d835_5    conda-forge
bcrypt                    3.2.2            py38h294d835_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
black                     22.6.0             pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl    conda-forge
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
blinker                   1.4                        py_1    conda-forge
bokeh                     2.4.3            py38haa244fe_0    conda-forge
boost-cpp                 1.79.0               h9f4b32c_0    conda-forge
brotli                    1.0.9                h8ffe710_7    conda-forge
brotli-bin                1.0.9                h8ffe710_7    conda-forge
brotli-python             1.0.9            py38h885f38d_7    conda-forge
brotlipy                  0.7.0           py38h294d835_1004    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
c-ares                    1.18.1               h8ffe710_0    conda-forge
ca-certificates           2022.6.15.1          h5b45459_0    conda-forge
cachetools                5.0.0              pyhd8ed1ab_0    conda-forge
calmap                    0.0.9                    pypi_0    pypi
ccxt                      1.91.101                 pypi_0    pypi
certifi                   2022.6.15.1        pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py38hd8c33c5_0    conda-forge
chardet                   5.0.0            py38haa244fe_0    conda-forge
charset-normalizer        2.1.0              pyhd8ed1ab_0    conda-forge
click                     8.1.3            py38haa244fe_0    conda-forge
cloudpickle               2.1.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
coloredlogs               15.0.1             pyhd8ed1ab_3    conda-forge
commonmark                0.9.1                      py_0    conda-forge
conda                     4.14.0           py38haa244fe_0    conda-forge
conda-package-handling    1.8.1            py38h31c79cd_1    conda-forge
cookiecutter              2.1.1              pyh6c4a22f_0    conda-forge
cryptography              37.0.4           py38hb7941b4_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dash                      2.6.0              pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
debugpy                   1.6.0            py38h885f38d_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
dill                      0.3.5.1            pyhd8ed1ab_0    conda-forge
docutils                  0.19             py38haa244fe_0    conda-forge
easyocr                   1.5.0                    pypi_0    pypi
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
ephem                     4.1.3            py38h294d835_4    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
executing                 0.9.1              pyhd8ed1ab_0    conda-forge
ffmpeg-python             0.2.0                    pypi_0    pypi
filterpy                  1.4.5                    pypi_0    pypi
flake8                    4.0.1              pyhd8ed1ab_2    conda-forge
flask                     2.1.3              pyhd8ed1ab_0    conda-forge
flask-compress            1.12               pyhd8ed1ab_0    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
fonttools                 4.34.4           py38h294d835_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
frozenlist                1.3.1                    pypi_0    pypi
future                    0.18.2           py38haa244fe_5    conda-forge
gettext                   0.19.8.1          ha2e2712_1008    conda-forge
gflags                    2.2.2             ha925a31_1004    conda-forge
gitdb                     4.0.9              pyhd8ed1ab_0    conda-forge
gitpython                 3.1.27             pyhd8ed1ab_0    conda-forge
glib                      2.72.1               h7755175_0    conda-forge
glib-tools                2.72.1               h7755175_0    conda-forge
glog                      0.6.0                h4797de2_0    conda-forge
grpc-cpp                  1.45.2               hc952ed8_3    conda-forge
gst-plugins-base          1.20.3               he07aa86_0    conda-forge
gstreamer                 1.20.3               hdff456e_0    conda-forge
h11                       0.13.0             pyhd8ed1ab_1    conda-forge
humanfriendly             10.0             py38haa244fe_2    conda-forge
icu                       70.1                 h0e60522_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
imageio                   2.20.0                   pypi_0    pypi
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4           py38haa244fe_0    conda-forge
importlib_metadata        4.11.4               hd8ed1ab_0    conda-forge
importlib_resources       5.9.0              pyhd8ed1ab_0    conda-forge
inflection                0.5.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2022.1.0          h57928b3_3787    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 6.15.1             pyh025b116_0    conda-forge
ipython                   7.33.0           py38haa244fe_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.7.1              pyhd8ed1ab_0    conda-forge
isort                     5.10.1             pyhd8ed1ab_0    conda-forge
itsdangerous              2.1.2              pyhd8ed1ab_0    conda-forge
jedi                      0.18.1           py38haa244fe_1    conda-forge
jellyfish                 0.9.0            py38h294d835_1    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jinja2-time               0.2.0              pyhd8ed1ab_3    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
joypy                     0.2.4              pyhd3deb0d_0    conda-forge
jpeg                      9e                   h8ffe710_2    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                4.7.2              pyhd8ed1ab_0    conda-forge
jupyter_client            7.3.1              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1           py38haa244fe_0    conda-forge
jupyter_server            1.18.1             pyhd8ed1ab_0    conda-forge
jupyterlab                3.4.4              pyhd8ed1ab_0    conda-forge
jupyterlab-unfold         0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.15.0             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.1.1              pyhd8ed1ab_0    conda-forge
keyring                   23.7.0           py38haa244fe_0    conda-forge
kiwisolver                1.4.4            py38hbd9d945_0    conda-forge
krb5                      1.19.3               h1176d77_0    conda-forge
lazy-object-proxy         1.7.1            py38h294d835_1    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libblas                   3.9.0              12_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_7    conda-forge
libbrotlidec              1.0.9                h8ffe710_7    conda-forge
libbrotlienc              1.0.9                h8ffe710_7    conda-forge
libcblas                  3.9.0              12_win64_mkl    conda-forge
libclang                  14.0.6          default_h77d9078_0    conda-forge
libclang13                14.0.6          default_h77d9078_0    conda-forge
libcrc32c                 1.1.2                h0e60522_0    conda-forge
libcurl                   7.83.1               h789b8ee_0    conda-forge
libdeflate                1.12                 h8ffe710_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.72.1               h3be07f2_0    conda-forge
libgoogle-cloud           1.40.2               h68f564a_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0              12_win64_mkl    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.37               h1d00b33_3    conda-forge
libprotobuf               3.20.1               h7755175_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libthrift                 0.16.0               h636ae23_1    conda-forge
libtiff                   4.4.0                h2ed3b44_1    conda-forge
libutf8proc               2.7.0                hcb41399_0    conda-forge
libuv                     1.44.2               h8ffe710_0    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.2.3                h8ffe710_1    conda-forge
libwebp-base              1.2.3                h8ffe710_2    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.9.14               hf5bbc77_3    conda-forge
libxslt                   1.1.35               h34f844d_0    conda-forge
libzlib                   1.2.12               h8ffe710_2    conda-forge
lxml                      4.9.1            py38h294d835_0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markdownify               0.11.2                   pypi_0    pypi
markupsafe                2.1.1            py38h294d835_1    conda-forge
matplotlib                3.5.2            py38haa244fe_0    conda-forge
matplotlib-base           3.5.2            py38he529843_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
menuinst                  1.4.18           py38haa244fe_1    conda-forge
mistune                   0.8.4           py38h294d835_1005    conda-forge
mkl                       2021.4.0           h0e2418a_729    conda-forge
mkl-service               2.4.0            py38h4f8af0f_0    conda-forge
mplfinance                0.12.9b1           pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multidict                 6.0.2                    pypi_0    pypi
multitasking              0.0.9              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy_extensions           0.4.3            py38haa244fe_5    conda-forge
nbclassic                 0.4.3              pyhd8ed1ab_0    conda-forge
nbclient                  0.6.6              pyhd8ed1ab_0    conda-forge
nbconvert                 6.5.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            6.5.0              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          6.5.0              pyhd8ed1ab_0    conda-forge
nbformat                  5.4.0              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
networkx                  2.8.5                    pypi_0    pypi
ninja                     1.11.0               h2d74725_0    conda-forge
nltk                      3.6.7              pyhd8ed1ab_0    conda-forge
nodejs                    18.7.0               h57928b3_0    conda-forge
notebook                  6.4.12             pyha770c72_0    conda-forge
notebook-shim             0.1.0              pyhd8ed1ab_0    conda-forge
numpy                     1.23.1           py38h223ccf5_0    conda-forge
numpydoc                  1.4.0              pyhd8ed1ab_1    conda-forge
opencv-python-headless    4.5.4.60                 pypi_0    pypi
openjpeg                  2.4.0                hb211442_1    conda-forge
openpyxl                  3.0.9              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1q               h8ffe710_0    conda-forge
outcome                   1.2.0              pyhd8ed1ab_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.3            py38hcc40339_0    conda-forge
pandas-datareader         0.10.0             pyh6c4a22f_0    conda-forge
pandoc                    2.18                 h57928b3_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
paramiko                  2.11.0             pyhd8ed1ab_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h0e60522_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0            py38hd8e0db4_0    conda-forge
pip                       22.2.2                   pypi_0    pypi
platformdirs              2.5.2              pyhd8ed1ab_1    conda-forge
plotly                    5.9.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0            py38haa244fe_3    conda-forge
ply                       3.11                       py_1    conda-forge
prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.30             pyha770c72_0    conda-forge
protobuf                  3.20.1           py38haa244fe_0    conda-forge
psutil                    5.9.1            py38h294d835_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyarrow                   8.0.0           py38h155c480_3_cpu    conda-forge
pycares                   4.2.2                    pypi_0    pypi
pycodestyle               2.8.0              pyhd8ed1ab_0    conda-forge
pycosat                   0.6.3           py38h294d835_1010    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydeck                    0.7.1              pyh6c4a22f_0    conda-forge
pydocstyle                6.1.1              pyhd8ed1ab_0    conda-forge
pyflakes                  2.4.0              pyhd8ed1ab_0    conda-forge
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
pylint                    2.14.5             pyhd8ed1ab_0    conda-forge
pyls-spyder               0.4.0              pyhd8ed1ab_0    conda-forge
pympler                   1.0.1              pyhd8ed1ab_0    conda-forge
pynacl                    1.5.0            py38h31c79cd_1    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7           py38h75e37d8_0    conda-forge
pyqt5-sip                 12.11.0          py38h885f38d_0    conda-forge
pyqtwebengine             5.15.7           py38h75e37d8_0    conda-forge
pyreadline3               3.4.1            py38haa244fe_0    conda-forge
pyrsistent                0.18.1           py38h294d835_1    conda-forge
pysocks                   1.7.1            py38haa244fe_5    conda-forge
python                    3.8.13          h9a09f29_0_cpython    conda-forge
python-bidi               0.4.2                    pypi_0    pypi
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.1             pyhd8ed1ab_0    conda-forge
python-lsp-black          1.2.1              pyhd8ed1ab_0    conda-forge
python-lsp-jsonrpc        1.0.0              pyhd8ed1ab_0    conda-forge
python-lsp-server         1.5.0              pyhd8ed1ab_0    conda-forge
python-slugify            6.1.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2022.1             pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytoolconfig              1.2.1              pyhd8ed1ab_0    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pytz-deprecation-shim     0.1.0.post0      py38haa244fe_2    conda-forge
pywavelets                1.3.0                    pypi_0    pypi
pywin32                   303              py38h294d835_0    conda-forge
pywin32-ctypes            0.2.0           py38haa244fe_1005    conda-forge
pywinpty                  2.0.6            py38hd3f51b4_0    conda-forge
pyyaml                    6.0              py38h294d835_4    conda-forge
pyzmq                     23.2.0           py38h09162b1_0    conda-forge
qdarkstyle                3.0.3              pyhd8ed1ab_0    conda-forge
qstylizer                 0.2.1              pyhd8ed1ab_0    conda-forge
qt-main                   5.15.4               h467ea89_2    conda-forge
qt-webengine              5.15.4               h7325c83_3    conda-forge
qtawesome                 1.1.1              pyhd8ed1ab_0    conda-forge
qtconsole                 5.3.1              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.3.1              pyha770c72_0    conda-forge
qtpy                      2.1.0              pyhd8ed1ab_0    conda-forge
re2                       2022.04.01           h0e60522_0    conda-forge
regex                     2022.7.25        py38h294d835_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_0    conda-forge
rich                      12.5.1             pyhd8ed1ab_0    conda-forge
rope                      1.3.0              pyhd8ed1ab_0    conda-forge
rtree                     1.0.0            py38h8b54edf_1    conda-forge
ruamel_yaml               0.15.80         py38h294d835_1007    conda-forge
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.1.1            py38h9235413_0    conda-forge
scipy                     1.8.1            py38h4990095_2    conda-forge
seaborn                   0.11.2               hd8ed1ab_0    conda-forge
seaborn-base              0.11.2             pyhd8ed1ab_0    conda-forge
selenium                  4.3.0              pyhd8ed1ab_0    conda-forge
semver                    2.13.0             pyh9f0ad1d_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                63.2.0           py38haa244fe_0    conda-forge
simplejson                3.17.6                   pypi_0    pypi
sip                       6.6.2            py38h885f38d_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
snappy                    1.1.9                h82413e6_1    conda-forge
sniffio                   1.2.0            py38haa244fe_3    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sphinx                    5.1.1              pyh6c4a22f_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
spyder                    5.3.2            py38haa244fe_0    conda-forge
spyder-kernels            2.3.2            py38haa244fe_0    conda-forge
spyder-terminal           1.0.0            py38haa244fe_1    spyder-ide
sqlite                    3.39.2               h8ffe710_0    conda-forge
squarify                  0.4.3                    pypi_0    pypi
stack_data                0.3.0              pyhd8ed1ab_0    conda-forge
statsmodels               0.13.2           py38hbdcd294_0    conda-forge
streamlit                 1.11.1             pyhd8ed1ab_0    conda-forge
streamlit-aggrid          0.2.2.post2              pypi_0    pypi
streamlit-lottie          0.0.3                    pypi_0    pypi
streamlit-terran-timeline 0.0.19                   pypi_0    pypi
streamlit-timeline        0.0.2                    pypi_0    pypi
tbb                       2021.5.0             h2d74725_1    conda-forge
tenacity                  8.0.1              pyhd8ed1ab_0    conda-forge
terminado                 0.15.0           py38haa244fe_0    conda-forge
terran                    0.1.2                    pypi_0    pypi
text-unidecode            1.3                        py_0    conda-forge
textdistance              4.3.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
tifffile                  2022.7.28                pypi_0    pypi
tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlkit                   0.11.1             pyha770c72_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
torch                     1.12.0                   pypi_0    pypi
torchvision               0.13.0                   pypi_0    pypi
tornado                   6.2              py38h294d835_0    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
trio                      0.21.0           py38haa244fe_0    conda-forge
trio-websocket            0.9.2              pyhd8ed1ab_0    conda-forge
typed-ast                 1.5.4            py38h294d835_0    conda-forge
typing                    3.10.0.0           pyhd8ed1ab_0    conda-forge
typing-extensions         4.3.0                hd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
tzlocal                   4.2              py38haa244fe_1    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
ujson                     5.3.0            py38h885f38d_0    conda-forge
unicodedata2              14.0.0           py38h294d835_1    conda-forge
unidecode                 1.3.4              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
utf8proc                  2.6.1                h2bbff1b_0  
validators                0.18.2             pyhd3deb0d_0    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
watchdog                  2.1.9            py38haa244fe_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.3.3              pyhd8ed1ab_0    conda-forge
werkzeug                  2.2.1              pyhd8ed1ab_0    conda-forge
whatthepatch              1.0.2              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.6.1              pyha770c72_0    conda-forge
win_inet_pton             1.1.0            py38haa244fe_4    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.14.1           py38h294d835_0    conda-forge
wsproto                   1.1.0            py38haa244fe_1    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yapf                      0.32.0             pyhd8ed1ab_0    conda-forge
yarl                      1.7.2                    pypi_0    pypi
yfinance                  0.1.74             pyhd8ed1ab_0    conda-forge
youtube-dl                2021.12.17               pypi_0    pypi
zeromq                    4.3.4                h0e60522_1    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h8ffe710_2    conda-forge
zstd                      1.5.2                h6255e5f_2    conda-forge

```
</details>

**Comment by richlysakowski** [comment]
Here is a screen shot of the result.  

![Spyder-Terminal corrupted menu](https://user-images.githubusercontent.com/9345711/189495200-c7047aa8-3f3f-4fbf-83d7-1616b510e7f3.png)

I need to uninstall Spyder-Terminal until this is fixed.

**Comment by ccordoba12** [comment]
Hey @richlysakowski, it seems you didn't install the latest Spyder-terminal version because that version shouldn't give the error that appears in the `Traceback` section above.

What is the command you used to install Spyder-terminal? And what's the version you installed?

**Comment by ccordoba12** [comment]
Note: I'm moving this to the Spyder-terminal repo. Please open additional problems with that plugin there.
