### ISSUE TITLE
TypeError: register_cmap()

### ISSUE THREAD

**Issue by sq0346** [spyder-ide/spyder#19419]
I'm trying to get the ProXAS_v2.43 running. I installed the necessary packages the manual provided, but when I try to start the program I get the following error:  **TypeError: register_cmap() got an unexpected keyword argument 'lut'**
Hopefully someone has an idea how to fix this.

Packages necessary according to the manual:
conda install –c GSECARS xraylarch
conda install –c conda-forge numpy-indexed

**Full error:**

`Traceback (most recent call last):
  File "ProXAS_v2.43.py", line 9, in <module>
    import tkinter, time, os, psutil, subprocess, sys, shutil, ast, codecs, re, larch, gc, peakutils.peak, itertools
  File "C:\Users\sq0346\Anaconda3\envs\py38\lib\site-packages\larch\__init__.py", line 47, in <module>
    from . import builtins
  File "C:\Users\sq0346\Anaconda3\envs\py38\lib\site-packages\larch\builtins.py", line 45, in <module>
    from . import wxlib
  File "C:\Users\sq0346\Anaconda3\envs\py38\lib\site-packages\larch\wxlib\__init__.py", line 36, in <module>
    from . import larchframe
  File "C:\Users\sq0346\Anaconda3\envs\py38\lib\site-packages\larch\wxlib\larchframe.py", line 17, in <module>
    from .columnframe import ColumnDataFileFrame
  File "C:\Users\sq0346\Anaconda3\envs\py38\lib\site-packages\larch\wxlib\columnframe.py", line 15, in <module>
    from wxmplot import PlotPanel
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\sq0346\Anaconda3\envs\py38\lib\site-packages\wxmplot-0.9.43-py3.8.egg\wxmplot\__init__.py", line 41, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\sq0346\Anaconda3\envs\py38\lib\site-packages\wxmplot-0.9.43-py3.8.egg\wxmplot\imagepanel.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\sq0346\Anaconda3\envs\py38\lib\site-packages\wxmplot-0.9.43-py3.8.egg\wxmplot\imageconf.py", line 24, in <module>
  File "C:\Users\sq0346\Anaconda3\envs\py38\lib\site-packages\wxmplot-0.9.43-py3.8.egg\wxmplot\colors.py", line 432, in register_custom_colormaps
TypeError: register_cmap() got an unexpected keyword argument 'lut' `

**Comment by ccordoba12** [comment]
Hey @sq0346, thanks for reporting. Unfortunately we can't help you with this problem because it's about packages we haven't used before.

I think you can have better luck by asking on StackOverflow:

https://stackoverflow.com
