### ISSUE TITLE
get_name() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by nbonacchi** [spyder-ide/spyder#19410]
### What steps will reproduce the problem?

Fresh install --> Tools --> Preferences --> Crash 

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/nico/miniconda3/envs/aulas/lib/python3.9/site-packages/spyder/plugins/preferences/plugin.py", line 275, in <lambda>
    lambda: self.open_dialog(main.prefs_dialog_size))
  File "/home/nico/miniconda3/envs/aulas/lib/python3.9/site-packages/spyder/plugins/preferences/plugin.py", line 255, in open_dialog
    container.create_dialog(
  File "/home/nico/miniconda3/envs/aulas/lib/python3.9/site-packages/spyder/plugins/preferences/widgets/container.py", line 60, in create_dialog
    page.initialize()
  File "/home/nico/miniconda3/envs/aulas/lib/python3.9/site-packages/spyder/plugins/preferences/api.py", line 86, in initialize
    self.setup_page()
  File "/home/nico/miniconda3/envs/aulas/lib/python3.9/site-packages/spyder/api/plugin_registration/_confpage.py", line 78, in setup_page
    plugin_loc_name = PluginClass.get_name()
TypeError: get_name() missing 1 required positional argument: 'self'
```

## Versions

* Spyder version: 5.3.3  (conda)
* Python version: 3.9.7 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 5.15.0-48-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.0.0 (OK)
cookiecutter >=1.6.0                 :  1.7.2 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0              :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  3.2.0 (OK)
keyring >=17.0.0                     :  23.4.0 (OK)
nbconvert >=4.0                      :  6.4.4 (OK)
numpydoc >=0.6.0                     :  1.1.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.8.0 (OK)
pygments >=2.0                       :  2.10.0 (OK)
pylint >=2.5.0;<3.0                  :  2.9.6 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0                 :  1.5.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.2 (OK)
qstylizer >=0.1.10                   :  0.1.10 (OK)
qtawesome >=1.0.2                    :  1.0.3 (OK)
qtconsole >=5.3.2;<5.4.0             :  5.3.2 (OK)
qtpy >=2.1.0                         :  2.2.0 (OK)
rtree >=0.9.7                        :  0.9.7 (OK)
setuptools >=49.6.0                  :  58.0.4 (OK)
sphinx >=0.6.6                       :  4.2.0 (OK)
spyder_kernels >=2.3.3;<2.4.0        :  2.3.3 (OK)
textdistance >=4.2.0                 :  4.2.1 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.6 (OK)
xdg >=0.26                           :  0.27 (OK)
zmq >=22.1.0                         :  23.2.1 (OK)

# Optional:
cython >=0.21                        :  None (NOK)
matplotlib >=3.0.0                   :  3.5.3 (OK)
numpy >=1.7                          :  1.23.3 (OK)
pandas >=1.1.1                       :  1.4.4 (OK)
scipy >=0.17.0                       :  1.9.1 (OK)
sympy >=0.7.3                        :  None (NOK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.1.0 :  1.1.0 (OK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at /home/nico/miniconda3/envs/aulas:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
alabaster                 0.7.12             pyhd3eb1b0_0  
anyio                     3.5.0                    pypi_0    pypi
appdirs                   1.4.4              pyhd3eb1b0_0  
argon2-cffi               20.1.0           py39h3811e60_2    conda-forge
arrow                     0.13.1           py39h06a4308_0  
astroid                   2.6.6            py39h06a4308_0  
async_generator           1.10               pyhd3eb1b0_0  
atomicwrites              1.4.0                      py_0  
attrs                     21.4.0             pyhd3eb1b0_0  
autopep8                  1.6.0                    pypi_0    pypi
babel                     2.9.1              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
beautifulsoup4            4.10.0                   pypi_0    pypi
binaryornot               0.4.4              pyhd3eb1b0_1  
black                     22.8.0                   pypi_0    pypi
bleach                    4.1.0              pyhd3eb1b0_0  
brotlipy                  0.7.0           py39h27cfd23_1003  
ca-certificates           2021.10.26           h06a4308_2  
certifi                   2021.10.8        py39h06a4308_2  
cffi                      1.15.0           py39hd667e15_1  
chardet                   4.0.0           py39h06a4308_1003  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.3              pyhd3eb1b0_0  
cloudpickle               2.0.0              pyhd3eb1b0_0  
colorama                  0.4.4              pyhd3eb1b0_0  
coloredlogs               15.0.1           py39hf3d152e_2    conda-forge
comtypes                  1.1.10                   pypi_0    pypi
cookiecutter              1.7.2              pyhd3eb1b0_0  
cryptography              36.0.0           py39h9ce1e76_0  
cycler                    0.11.0                   pypi_0    pypi
dbus                      1.13.18              hb2f20db_0  
debugpy                   1.5.1            py39h295c915_0  
decorator                 5.1.0              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
diff-match-patch          20200713           pyhd3eb1b0_0  
docutils                  0.17.1           py39h06a4308_1  
entrypoints               0.3              py39h06a4308_0  
expat                     2.4.1                h2531618_2  
fastjsonschema            2.16.1                   pypi_0    pypi
flake8                    4.0.1                    pypi_0    pypi
fontconfig                2.13.1               h6c09931_0  
fonttools                 4.33.3                   pypi_0    pypi
freetype                  2.11.0               h70c0345_0  
glib                      2.69.1               h4ff587b_1  
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
humanfriendly             10.0             py39hf3d152e_2    conda-forge
icu                       58.2                 he6710b0_3  
idna                      3.3                pyhd3eb1b0_0  
imagesize                 1.3.0              pyhd3eb1b0_0  
importlib-metadata        4.8.2            py39h06a4308_0  
importlib_metadata        4.8.2                hd3eb1b0_0  
inflection                0.5.1            py39h06a4308_0  
intervaltree              3.1.0              pyhd3eb1b0_0  
ipykernel                 6.15.2                   pypi_0    pypi
ipython                   7.34.0                   pypi_0    pypi
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.5                    pypi_0    pypi
isort                     5.9.3              pyhd3eb1b0_0  
jedi                      0.18.1           py39h06a4308_0  
jeepney                   0.7.1              pyhd3eb1b0_0  
jellyfish                 0.9.0                    pypi_0    pypi
jinja2                    2.11.3             pyhd3eb1b0_0  
jinja2-time               0.2.0              pyhd3eb1b0_2  
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9d                   h7f8727e_0  
json5                     0.9.6                    pypi_0    pypi
jsonschema                3.2.0              pyhd3eb1b0_2  
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            7.3.5                    pypi_0    pypi
jupyter-console           6.4.0                    pypi_0    pypi
jupyter-core              4.11.1                   pypi_0    pypi
jupyter-server            1.18.1                   pypi_0    pypi
jupyterlab                3.4.6                    pypi_0    pypi
jupyterlab-server         2.10.3                   pypi_0    pypi
jupyterlab-widgets        1.0.2                    pypi_0    pypi
jupyterlab_pygments       0.1.2                      py_0  
keyring                   23.4.0           py39h06a4308_0  
kiwisolver                1.4.2                    pypi_0    pypi
lazy-object-proxy         1.6.0            py39h27cfd23_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgomp                   9.3.0               h5101ec6_17  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h7b6447c_0  
libspatialindex           1.9.3                h2531618_0  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libuuid                   1.0.3                h7f8727e_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.12               h03d6c58_0  
libxslt                   1.1.34               hc22bd24_0  
lxml                      4.7.1            py39h1f438cf_1  
markupsafe                1.1.1            py39h27cfd23_0  
matplotlib                3.5.3                    pypi_0    pypi
matplotlib-inline         0.1.2              pyhd3eb1b0_2  
mccabe                    0.6.1            py39h06a4308_1  
mistune                   0.8.4           py39h27cfd23_1000  
mouseinfo                 0.1.3                    pypi_0    pypi
mypy_extensions           0.4.3            py39h06a4308_1  
nbclassic                 0.3.5                    pypi_0    pypi
nbclient                  0.5.3              pyhd3eb1b0_0  
nbconvert                 6.4.4                    pypi_0    pypi
nbformat                  5.4.0                    pypi_0    pypi
ncurses                   6.3                  h7f8727e_2  
nest-asyncio              1.5.5                    pypi_0    pypi
networkx                  2.8.6                    pypi_0    pypi
nltk                      3.7                      pypi_0    pypi
notebook                  6.4.8              pyha770c72_0    conda-forge
numpy                     1.23.3                   pypi_0    pypi
numpydoc                  1.1.0              pyhd3eb1b0_1  
openssl                   1.1.1m               h7f8727e_0  
packaging                 21.3               pyhd3eb1b0_0  
pandas                    1.4.4                    pypi_0    pypi
pandocfilters             1.4.3            py39h06a4308_1  
parso                     0.8.3              pyhd3eb1b0_0  
pathspec                  0.10.1                   pypi_0    pypi
pcre                      8.45                 h295c915_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.1.0                    pypi_0    pypi
pip                       21.2.4           py39h06a4308_0  
platformdirs              2.5.2                    pypi_0    pypi
pluggy                    1.0.0            py39h06a4308_0  
poyo                      0.5.0              pyhd3eb1b0_0  
prometheus_client         0.13.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.20             pyhd3eb1b0_0  
psutil                    5.8.0            py39h27cfd23_1  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pyautogui                 0.9.53                   pypi_0    pypi
pycodestyle               2.8.0                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pydocstyle                6.1.1              pyhd3eb1b0_0  
pyflakes                  2.4.0                    pypi_0    pypi
pygetwindow               0.0.9                    pypi_0    pypi
pygments                  2.10.0             pyhd3eb1b0_0  
pylint                    2.9.6            py39h06a4308_1  
pyls-spyder               0.4.0              pyhd3eb1b0_0  
pymsgbox                  1.0.9                    pypi_0    pypi
pyopenssl                 21.0.0             pyhd3eb1b0_1  
pyparsing                 3.0.9                    pypi_0    pypi
pyperclip                 1.8.2                    pypi_0    pypi
pyqt                      5.9.2            py39h2531618_6  
pyqt5                     5.12.3                   pypi_0    pypi
pyqt5-sip                 12.9.0                   pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrect                    0.1.4                    pypi_0    pypi
pyrsistent                0.18.0           py39heee7806_0  
pyscreeze                 0.1.28                   pypi_0    pypi
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.7                h12debd9_1  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-decouple           3.5                      pypi_0    pypi
python-lsp-black          1.2.1                    pypi_0    pypi
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0  
python-lsp-server         1.5.0                    pypi_0    pypi
python-slugify            5.0.2              pyhd3eb1b0_0  
python3-xlib              0.15                     pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pyttsx3                   2.90                     pypi_0    pypi
pytweening                1.0.4                    pypi_0    pypi
pytz                      2021.3             pyhd3eb1b0_0  
pywhatkit                 5.3                      pypi_0    pypi
pyxdg                     0.27               pyhd3eb1b0_0  
pyyaml                    6.0              py39h7f8727e_1  
pyzmq                     23.2.1                   pypi_0    pypi
qdarkstyle                3.0.2              pyhd3eb1b0_0  
qstylizer                 0.1.10             pyhd3eb1b0_0  
qt                        5.9.7                h5867ecd_1  
qtawesome                 1.0.3              pyhd3eb1b0_0  
qtconsole                 5.3.2                    pypi_0    pypi
qtpy                      2.2.0                    pypi_0    pypi
readline                  8.1.2                h7f8727e_1  
regex                     2021.11.2        py39h7f8727e_0  
requests                  2.27.1             pyhd3eb1b0_0  
rope                      0.21.1             pyhd3eb1b0_0  
rtree                     0.9.7            py39h06a4308_1  
scikit-learn              1.1.2                    pypi_0    pypi
scipy                     1.9.1                    pypi_0    pypi
secretstorage             3.3.1            py39h06a4308_0  
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                58.0.4           py39h06a4308_0  
sip                       4.19.13          py39h295c915_0  
six                       1.16.0             pyhd3eb1b0_0  
sniffio                   1.2.0                    pypi_0    pypi
snowballstemmer           2.2.0              pyhd3eb1b0_0  
sortedcontainers          2.4.0              pyhd3eb1b0_0  
soupsieve                 2.3.1                    pypi_0    pypi
speechrecognition         3.8.1                    pypi_0    pypi
sphinx                    4.2.0              pyhd3eb1b0_1  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0  
spyder                    5.3.3                    pypi_0    pypi
spyder-kernels            2.3.3                    pypi_0    pypi
spyder-notebook           0.1.4                      py_0    spyder-ide
spyder-terminal           1.1.0            py39hf3d152e_1    conda-forge
spyder-unittest           0.3.1                      py_1    conda-forge
sqlite                    3.37.0               hc218d9a_0  
terminado                 0.12.1           py39hf3d152e_1    conda-forge
testpath                  0.5.0              pyhd3eb1b0_0  
text-unidecode            1.3                pyhd3eb1b0_0  
textblob                  0.17.1                   pypi_0    pypi
textdistance              4.2.1              pyhd3eb1b0_0  
threadpoolctl             3.1.0                    pypi_0    pypi
three-merge               0.1.1              pyhd3eb1b0_0  
tinycss                   0.4             pyhd3eb1b0_1002  
tk                        8.6.11               h1ccaba5_0  
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.1                    pypi_0    pypi
tornado                   6.2                      pypi_0    pypi
tqdm                      4.64.0                   pypi_0    pypi
traitlets                 5.1.1              pyhd3eb1b0_0  
typed-ast                 1.4.3            py39h7f8727e_1  
typing_extensions         3.10.0.2           pyh06a4308_0  
tzdata                    2021e                hda174b7_0  
ujson                     4.2.0            py39h295c915_0  
unidecode                 1.2.0              pyhd3eb1b0_0  
urllib3                   1.26.7             pyhd3eb1b0_0  
watchdog                  2.1.6            py39h06a4308_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1            py39h06a4308_1  
websocket-client          1.3.1                    pypi_0    pypi
whatthepatch              1.0.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
whichcraft                0.6.1              pyhd3eb1b0_0  
widgetsnbextension        3.5.2                    pypi_0    pypi
wikipedia                 1.4.0                    pypi_0    pypi
wordcloud                 1.8.2.2                  pypi_0    pypi
wrapt                     1.12.1           py39he8ac12f_1  
wurlitzer                 3.0.2            py39h06a4308_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
yapf                      0.31.0             pyhd3eb1b0_0  
zeromq                    4.3.4                h2531618_0  
zipp                      3.7.0              pyhd3eb1b0_0  
zlib                      1.2.11               h7f8727e_4  

```
</details>

**Comment by ccordoba12** [comment]
Hey @nbonacchi, thanks for reporting. You have an outdated version of Spyder-terminal, which is causing the error.

Please update to the latest one (1.2.2) and try again. That should fix your problem.

**Comment by nbonacchi** [comment]
All good thanks!

**Comment by GaoWeiCHN** [comment]
Hi, @ccordoba12. I use [spyder5-plugin-cookiecutter](https://github.com/spyder-ide/spyder5-plugin-cookiecutter) to generate a new template plugin(default settings, didn't do anything), and then the "spyder-boilerplate" plugin is installed successfully. When I click the "Preferences", it will crash and show the same error above.  Before that, "Preferences" works fine.
Versions: 
Python 3.9.12
spyder 5.4.2 (pip )
spyder-kernels 2.4.2
QtPy 2.3.0
PyQt5 5.15.9
Operating System： Win10 x64
