### ISSUE TITLE
Disk Error Error 122 Preventing Saving Files

### ISSUE THREAD

**Issue by harshamarupudi56** [spyder-ide/spyder#19442]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am having an issue executing code that has saving files as a step. For example saving STL files, writing to csv file, have all returned Errorno122 disk quota error. I checked my storage and there is more than enough space. I have reset spyder which has caused no change. I have tried to uninstall spyder, update conda, and update spyder but all of these result in the following error report. 

    Traceback (most recent call last):
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1125, in __call__
        return func(*args, **kwargs)
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/cli/main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
        return getattr(module, func_name)(args, parser)
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/notices/core.py", line 72, in wrapper
        return_value = func(*args, **kwargs)
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/cli/main_update.py", line 22, in execute
        install(args, parser, 'update')
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/cli/install.py", line 256, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 195, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 300, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/common/io.py", line 86, in decorated
        return f(*args, **kwds)
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 463, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 1057, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/core/index.py", line 297, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 152, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
        yield fs.pop().result()
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 446, in result
        return self.__get_result()
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
        raise self._exception
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 144, in <lambda>
        subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 157, in query
        self.load()
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 222, in load
        _internal_state = self._load()
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 413, in _load
        fh.write(raw_repodata_str or '{}')
    OSError: [Errno 122] Disk quota exceeded

`$ /gpfs_projects/sriharsha.marupudi/anaconda3/bin/conda update spyder`

  environment variables:
                 CIO_TEST=<not set>
   CONDA_BACKUP_JAVA_HOME=:-
CONDA_BACKUP_JAVA_LD_LIBRARY_PATH=:-
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/gpfs_projects/sriharsha.marupudi/anaconda3/bin/conda
             CONDA_PREFIX=/gpfs_projects/sriharsha.marupudi/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/gpfs_projects/sriharsha.marupudi/anaconda3/bin/python
               CONDA_ROOT=/gpfs_projects/sriharsha.marupudi/anaconda3
              CONDA_SHLVL=1
                CUDA_PATH=/gpfs_projects/sriharsha.marupudi/anaconda3
           CURL_CA_BUNDLE=<not set>
     JAVA_LD_LIBRARY_PATH=/gpfs_projects/sriharsha.marupudi/anaconda3/lib/server
                     PATH=/gpfs_projects/sriharsha.marupudi/anaconda3/bin:/gpfs_projects/srihars
                          ha.marupudi/anaconda3/bin:/gpfs_projects/sriharsha.marupudi/anaconda3/
                          condabin:/gpfs_projects/sriharsha.marupudi/anaconda3/bin:/usr/local/sb
                          in:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/
                          games:/snap/bin:/usr/lpp/mmfs/bin:/home/sriharsha.marupudi/.local/bin:
                          /home/sriharsha.marupudi/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /gpfs_projects/sriharsha.marupudi/anaconda3
            shell level : 1
       user config file : /home/sriharsha.marupudi/.condarc
 populated config files : /home/sriharsha.marupudi/.condarc
          conda version : 4.14.0
    conda-build version : 3.21.9
         python version : 3.9.12.final.0
       virtual packages : __cuda=11.7=0
                          __linux=5.4.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /gpfs_projects/sriharsha.marupudi/anaconda3  (writable)
      conda av data dir : /gpfs_projects/sriharsha.marupudi/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /gpfs_projects/sriharsha.marupudi/anaconda3/pkgs
                          /home/sriharsha.marupudi/.conda/pkgs
       envs directories : /gpfs_projects/sriharsha.marupudi/anaconda3/envs
                          /home/sriharsha.marupudi/.conda/envs
               platform : linux-64
             user-agent : conda/4.14.0 requests/2.28.1 CPython/3.9.12 Linux/5.4.0-121-generic ubuntu/18.04.6 glibc/2.27
                UID:GID : 5856:5856
             netrc file : None
           offline mode : False

    Traceback (most recent call last):
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1125, in __call__
        return func(*args, **kwargs)
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/cli/main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
        return getattr(module, func_name)(args, parser)
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/notices/core.py", line 72, in wrapper
        return_value = func(*args, **kwargs)
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/cli/main_update.py", line 22, in execute
        install(args, parser, 'update')
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/cli/install.py", line 256, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 195, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 300, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/common/io.py", line 86, in decorated
        return f(*args, **kwds)
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 463, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 1057, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/core/index.py", line 297, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 152, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
        yield fs.pop().result()
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 446, in result
        return self.__get_result()
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
        raise self._exception
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 144, in <lambda>
        subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 157, in query
        self.load()
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 222, in load
        _internal_state = self._load()
      File "/gpfs_projects/sriharsha.marupudi/anaconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 413, in _load
        fh.write(raw_repodata_str or '{}')
    OSError: [Errno 122] Disk quota exceeded

`$ /gpfs_projects/sriharsha.marupudi/anaconda3/bin/conda update spyder`

  environment variables:
                 CIO_TEST=<not set>
   CONDA_BACKUP_JAVA_HOME=:-
CONDA_BACKUP_JAVA_LD_LIBRARY_PATH=:-
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/gpfs_projects/sriharsha.marupudi/anaconda3/bin/conda
             CONDA_PREFIX=/gpfs_projects/sriharsha.marupudi/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/gpfs_projects/sriharsha.marupudi/anaconda3/bin/python
               CONDA_ROOT=/gpfs_projects/sriharsha.marupudi/anaconda3
              CONDA_SHLVL=1
                CUDA_PATH=/gpfs_projects/sriharsha.marupudi/anaconda3
           CURL_CA_BUNDLE=<not set>
     JAVA_LD_LIBRARY_PATH=/gpfs_projects/sriharsha.marupudi/anaconda3/lib/server
                     PATH=/gpfs_projects/sriharsha.marupudi/anaconda3/bin:/gpfs_projects/srihars
                          ha.marupudi/anaconda3/bin:/gpfs_projects/sriharsha.marupudi/anaconda3/
                          condabin:/gpfs_projects/sriharsha.marupudi/anaconda3/bin:/usr/local/sb
                          in:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/
                          games:/snap/bin:/usr/lpp/mmfs/bin:/home/sriharsha.marupudi/.local/bin:
                          /home/sriharsha.marupudi/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /gpfs_projects/sriharsha.marupudi/anaconda3
            shell level : 1
       user config file : /home/sriharsha.marupudi/.condarc
 populated config files : /home/sriharsha.marupudi/.condarc
          conda version : 4.14.0
    conda-build version : 3.21.9
         python version : 3.9.12.final.0
       virtual packages : __cuda=11.7=0
                          __linux=5.4.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /gpfs_projects/sriharsha.marupudi/anaconda3  (writable)
      conda av data dir : /gpfs_projects/sriharsha.marupudi/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /gpfs_projects/sriharsha.marupudi/anaconda3/pkgs
                          /home/sriharsha.marupudi/.conda/pkgs
       envs directories : /gpfs_projects/sriharsha.marupudi/anaconda3/envs
                          /home/sriharsha.marupudi/.conda/envs
               platform : linux-64
             user-agent : conda/4.14.0 requests/2.28.1 CPython/3.9.12 Linux/5.4.0-121-generic ubuntu/18.04.6 glibc/2.27
                UID:GID : 5856:5856
             netrc file : None
           offline mode : False

### What steps reproduce the problem?

1. Run a script that saves data to a csv 
2. Try and save a newly written script 
3. Copy a file to storage 

### What is the expected output? What do you see instead?
Running a script that saves a fiel or saving a newly written script result in Error 122. I have also tried editing a file I already had which was unable to be saved due to this error. Somehow all of the code in that file was erased as well. 

### Paste Traceback/Error Below (if applicable)

```python-traceback


Error message:
[Errno 122] Disk quota exceeded



```

## Versions

* Spyder version: 5.2.2 None
* Python version: 3.9.12 64-bit
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 5.4.0-110-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.30 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.3 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)```

**Comment by ccordoba12** [comment]
Hey @harshamarupudi56, thanks for reporting. It seems you don't have enough space assigned to you in your cluster to run

    conda update spyder

If you only need to use Spyder, or a small number of the packages that come with Anaconda, I'd suggest you to uninstall it and install [Miniconda](https://docs.conda.io/en/latest/miniconda.html) instead.

After that you can create an environment only with what you need, by running the following commands in a terminal

    conda create -n myenv spyder python=3.9
    conda activate myenv
    conda install <additional packages that you need>

Perhaps that help you to save enough space to keep working in your cluster. Let us know if it works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by Tanmay-codeol** [comment]
Still an issue

**Comment by ccordoba12** [comment]
@Tanmay-codeol, as you can see in the initial post, this is not an error with Spyder but with Anaconda not having enough space. So, there's nothing we can do about it.
