### ISSUE TITLE
cannot lanuching

### ISSUE THREAD

**Issue by hohowaterboy** [spyder-ide/spyder#19451]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method

Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply

Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method

Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: 
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: 
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: 
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    TypeError: 
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method

Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: 
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method

Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: 
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply

Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: 
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
      File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

**Comment by hohowaterboy** [comment]
after I update conda and navigator I can't lanuching spyder.
anaconda version: 2019-10
after installation, I running below:
conda deactivate
conda install anaconda=custom
conda update conda
conda update anaconda-navigator

I can lanuching spyder before update conda, then I can't lanuching spyder.
First the errors message: ModuleNotFoundError: No module named ‘importlib-metadata’
then I uninstall spyder and reinstall
then the above error message showing
