### ISSUE TITLE
TypeError: <lambda>() missing 1 required positional argument: 'hidden'

### ISSUE THREAD

**Issue by Manjiro005** [spyder-ide/spyder#19463]
### What steps will reproduce the problem?

Open Spyder with Anaconda3, on the right, the kernel is loading eternally please help me

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\corentinverbreghe\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 1105, in create_client_for_kernel
    self._create_client_for_kernel(connection_file, hostname, sshkey,
  File "C:\Users\corentinverbreghe\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 1935, in _create_client_for_kernel
    shellwidget.check_spyder_kernel()
  File "C:\Users\corentinverbreghe\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 266, in check_spyder_kernel
    self.silent_exec_method(code)
  File "C:\Users\corentinverbreghe\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 667, in silent_exec_method
    self._request_info['execute'][msg_id] = self._ExecutionRequest(msg_id,
TypeError: <lambda>() missing 1 required positional argument: 'hidden'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.2.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.0 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by dalthviz** [comment]
Hi @Manjiro005 this seems a similar traceback as https://github.com/spyder-ide/spyder/issues/17772 are you trying to connect to a remote kernel? If that is the case be sure that both setups have the same versions of spyder-kernels.

Any further information to understand better the steps to reproduce the issue are greatly appreciated, let us know!

**Comment by Manjiro005** [comment]
Hi, I do not know I took the kernel that you have when you first open the
software
Have a good evening
Manjiro5

**Comment by dalthviz** [comment]
I see, maybe updating Spyder could help then. For that, close Spyder and run from an Anaconda prompt something like:

    conda update anaconda
    conda install spyder=5.2.2

Let us know if that helps!

**Comment by Manjiro005** [comment]
Thank you very much, but I already have the most recent version

**Comment by dalthviz** [comment]
Oh I see, I though you needed an update since the issue info shows Spyder 5.1.5 installed (so an update to Spyder 5.2.2 could be worthy to try). Maybe try to reset your Spyder preferences then by running from an Anaconda prompt `spyder --reset`

**Comment by dalthviz** [comment]
Closing due to lack of response
