### ISSUE TITLE
 raise ConnectionResetError and ConnectionResetError

### ISSUE THREAD

**Issue by opamuk** [spyder-ide/spyder#19505]
## Description
After the spyder update, I am getting an error message at each time I start spyder. The version is 5.3.3 now, the problem has started with the previous version(I think it was something like 5.2.2)

f.result()  # may raise
value = callback(transferred, key, ov)
raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request

### Traceback
```python-traceback
Error on reading from the event loop self pipe
loop: <ProactorEventLoop running=True closed=False debug=False>
Traceback (most recent call last):
  File "C:\Users\......\anaconda3\lib\asyncio\windows_events.py", line 453, in finish_recv
    return ov.getresult()
OSError: [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\....\anaconda3\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "C:\Users\....\anaconda3\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\.....\anaconda3\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request
```

## Versions

* Spyder version: 5.3.3  (conda)
* Python version: 3.8.3 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 8.1

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  2.6.0 (NOK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  63.4.1 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  1.23.1 (OK)
pandas >=1.1.1                :  1.1.3 (OK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at C:\Users\Freeware Sys\anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0  
alabaster                 0.7.12             pyhd3eb1b0_0  
altgraph                  0.17               pyhd3eb1b0_0  
anaconda-client           1.11.0           py38haa95532_0  
anaconda-navigator        1.9.12                   py38_0  
anyio                     3.5.0            py38haa95532_0  
apscheduler               3.6.3                    pypi_0    pypi
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py38h2bbff1b_0  
arrow                     1.2.2              pyhd3eb1b0_0  
asgiref                   3.3.1                    pypi_0    pypi
astroid                   2.11.7           py38haa95532_0  
atomicwrites              1.4.0                      py_0  
attrs                     21.4.0             pyhd3eb1b0_0  
autopep8                  1.6.0              pyhd3eb1b0_1  
babel                     2.9.1              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
backports                 1.1                pyhd3eb1b0_0  
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0  
backports.tempfile        1.0                pyhd3eb1b0_1  
backports.weakref         1.0.post1                  py_1  
bcrypt                    3.2.0            py38h2bbff1b_1  
beautifulsoup4            4.9.3              pyhb0f4dca_0  
binaryornot               0.4.4              pyhd3eb1b0_1  
black                     22.6.0           py38haa95532_0  
blas                      1.0                         mkl  
bleach                    4.1.0              pyhd3eb1b0_0  
brotlipy                  0.7.0           py38h2bbff1b_1003  
bzip2                     1.0.8                he774522_0  
ca-certificates           2022.07.19           haa95532_0  
certifi                   2022.6.15        py38haa95532_0  
cffi                      1.15.1           py38h2bbff1b_0  
chardet                   4.0.0           py38haa95532_1003  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
clarifai                  2.6.2                    pypi_0    pypi
click                     8.0.4            py38haa95532_0  
cloudpickle               2.0.0              pyhd3eb1b0_0  
clyent                    1.2.2                    py38_1  
colorama                  0.4.5            py38haa95532_0  
conda                     4.14.0           py38haa95532_0  
conda-build               3.22.0           py38haa95532_0  
conda-env                 2.6.0                         1  
conda-package-handling    1.8.1            py38h8cc25b3_0  
conda-verify              3.4.2                      py_1  
configobj                 5.0.6                    pypi_0    pypi
configparser              5.0.1                    pypi_0    pypi
console_shortcut          0.1.1                         4  
cookiecutter              1.7.3              pyhd3eb1b0_0  
cryptography              37.0.1           py38h21b164f_0  
cssutils                  1.0.2                    pypi_0    pypi
currency-symbols          1.0.0                    pypi_0    pypi
cytoolz                   0.11.0           py38he774522_0  
debugpy                   1.5.1            py38hd77b12b_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
diff-match-patch          20200713           pyhd3eb1b0_0  
dill                      0.3.4              pyhd3eb1b0_0  
django                    3.1.7                    pypi_0    pypi
docutils                  0.18.1           py38haa95532_3  
easyprocess               0.3                      pypi_0    pypi
emoji                     0.6.0                    pypi_0    pypi
entrypoints               0.4              py38haa95532_0  
et_xmlfile                1.1.0            py38haa95532_0  
filelock                  3.6.0              pyhd3eb1b0_0  
flake8                    4.0.1              pyhd3eb1b0_1  
fonttools                 4.18.2                   pypi_0    pypi
freetype                  2.11.0               ha860e81_0  
future                    0.18.2                   py38_1  
glib                      2.69.1               h5dc1a3c_1  
glob2                     0.7                pyhd3eb1b0_0  
googleapis-common-protos  1.52.0                   pypi_0    pypi
grpcio                    1.32.0                   pypi_0    pypi
gst-plugins-base          1.18.5               h9e645db_0  
gstreamer                 1.18.5               hd78058f_0  
httplib2                  0.18.1                   pypi_0    pypi
icu                       58.2                 ha925a31_3  
idna                      3.3                pyhd3eb1b0_0  
image                     1.5.33                   pypi_0    pypi
image-slicer              2.1.1                    pypi_0    pypi
imagesize                 1.4.1            py38haa95532_0  
importlib-metadata        4.11.3           py38haa95532_0  
importlib_metadata        4.11.3               hd3eb1b0_0  
inflection                0.5.1            py38haa95532_0  
instapy                   0.6.11                   pypi_0    pypi
intel-openmp              2021.4.0          haa95532_3556  
intervaltree              3.1.0              pyhd3eb1b0_0  
ipykernel                 6.15.2           py38haa95532_0  
ipython                   7.31.1           py38haa95532_1  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.5              pyhd3eb1b0_1  
isodate                   0.6.0                    pypi_0    pypi
isort                     5.9.3              pyhd3eb1b0_0  
jdcal                     1.4.1              pyhd3eb1b0_0  
jedi                      0.18.1           py38haa95532_1  
jellyfish                 0.9.0            py38h2bbff1b_0  
jinja2                    2.11.3             pyhd3eb1b0_0  
jinja2-time               0.2.0              pyhd3eb1b0_3  
jpeg                      9e                   h2bbff1b_0  
json5                     0.9.6              pyhd3eb1b0_0  
jsonschema                2.6.0                    pypi_0    pypi
jupyter_client            7.3.5            py38haa95532_0  
jupyter_core              4.10.0           py38haa95532_0  
jupyter_server            1.18.1           py38haa95532_0  
jupyterlab                3.4.4            py38haa95532_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.10.3             pyhd3eb1b0_1  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
keyring                   23.4.0           py38haa95532_0  
lazy-object-proxy         1.6.0            py38h2bbff1b_0  
lerc                      3.0                  hd77b12b_0  
libarchive                3.6.1                hebabd0d_0  
libclang                  12.0.0          default_h627e005_2  
libdeflate                1.8                  h2bbff1b_5  
libffi                    3.4.2                hd77b12b_4  
libiconv                  1.16                 h2bbff1b_2  
liblief                   0.11.5               hd77b12b_1  
libogg                    1.3.5                h2bbff1b_1  
libpng                    1.6.37               h2a8f88b_0  
libpq                     12.9                 hb652d5d_3  
libsodium                 1.0.18               h62dcd97_0  
libspatialindex           1.9.3                h6c2663c_0  
libtiff                   4.4.0                h8a3f274_0  
libvorbis                 1.3.7                he774522_0  
libwebp                   1.2.2                h2bbff1b_0  
libxml2                   2.9.14               h0ad7f3c_0  
libxslt                   1.1.35               h2bbff1b_0  
lml                       0.1.0                    pypi_0    pypi
lz4-c                     1.9.3                h2bbff1b_1  
m2-msys2-runtime          2.5.0.17080.65c939c               3  
m2-patch                  2.7.5                         2  
macholib                  1.14               pyhd3eb1b0_1  
markupsafe                2.0.1            py38h2bbff1b_0  
matplotlib-inline         0.1.6            py38haa95532_0  
mccabe                    0.6.1            py38haa95532_2  
meaningcloud-python       2.0.0                    pypi_0    pypi
menuinst                  1.4.18           py38h59b6b97_0  
mistune                   0.8.4           py38he774522_1000  
mkl                       2021.4.0           haa95532_640  
mkl-service               2.4.0            py38h2bbff1b_0  
mkl_fft                   1.3.1            py38h277e83a_0  
mkl_random                1.2.2            py38hf11a4ad_0  
modulegraph               0.18                     pypi_0    pypi
msys2-conda-epoch         20160418                      1  
mypy_extensions           0.4.3            py38haa95532_1  
navigator-updater         0.2.1                    py38_0  
nbclassic                 0.3.5              pyhd3eb1b0_0  
nbclient                  0.5.13           py38haa95532_0  
nbconvert                 6.4.4            py38haa95532_0  
nbformat                  5.3.0            py38haa95532_0  
nest-asyncio              1.5.5            py38haa95532_0  
nibabel                   3.1.1                    pypi_0    pypi
notebook                  6.4.12           py38haa95532_0  
numpy                     1.23.1           py38h7a0a035_0  
numpy-base                1.23.1           py38hca35cd5_0  
numpydoc                  1.4.0            py38haa95532_0  
olefile                   0.46               pyhd3eb1b0_0  
openpyxl                  3.0.5                      py_0  
openssl                   1.1.1q               h2bbff1b_0  
packaging                 21.3               pyhd3eb1b0_0  
pandas                    1.1.3            py38ha925a31_0  
pandocfilters             1.5.0              pyhd3eb1b0_0  
paramiko                  2.8.1              pyhd3eb1b0_0  
parso                     0.8.3              pyhd3eb1b0_0  
pathspec                  0.9.0            py38haa95532_0  
pcre                      8.45                 hd77b12b_0  
pdfminer                  20191125                 pypi_0    pypi
pdfminer-six              20200517                 pypi_0    pypi
pdfminer3k                1.3.4                    pypi_0    pypi
pdfplumber                0.5.23                   pypi_0    pypi
pefile                    2019.4.18                  py_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    7.2.0                    pypi_0    pypi
pip                       22.1.2           py38haa95532_0  
pkginfo                   1.8.2              pyhd3eb1b0_0  
platformdirs              2.5.2            py38haa95532_0  
pluggy                    1.0.0            py38haa95532_1  
ply                       3.11                     py38_0  
plyer                     1.4.3                    pypi_0    pypi
powershell_shortcut       0.0.1                         3  
poyo                      0.5.0              pyhd3eb1b0_0  
prometheus_client         0.14.1           py38haa95532_0  
prompt-toolkit            3.0.20             pyhd3eb1b0_0  
protobuf                  3.13.0                   pypi_0    pypi
psutil                    5.9.0            py38h2bbff1b_0  
psycopg2                  2.8.5            py38h7a1dbc1_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
py-lief                   0.11.5           py38hd77b12b_1  
py2app                    0.23                     pypi_0    pypi
py4j                      0.10.9.1                 pypi_0    pypi
pycodestyle               2.8.0              pyhd3eb1b0_0  
pycosat                   0.6.3            py38h2bbff1b_0  
pycparser                 2.21               pyhd3eb1b0_0  
pycryptodome              3.15.0           py38h2bbff1b_0  
pydocstyle                6.1.1              pyhd3eb1b0_0  
pydot                     1.4.1                    pypi_0    pypi
pydotplus                 2.0.2                    pypi_0    pypi
pyexcel                   0.6.6                    pypi_0    pypi
pyexcel-cli               0.0.3                    pypi_0    pypi
pyexcel-io                0.6.4                    pypi_0    pypi
pyexcel-xls               0.6.2                    pypi_0    pypi
pyexcel-xlsx              0.6.0                    pypi_0    pypi
pyflakes                  2.4.0              pyhd3eb1b0_0  
pygments                  2.11.2             pyhd3eb1b0_0  
pyinstaller               3.6              py38h62dcd97_5  
pylint                    2.14.5           py38haa95532_0  
pyls-spyder               0.4.0              pyhd3eb1b0_0  
pymupdf                   1.17.7                   pypi_0    pypi
pynacl                    1.5.0            py38h8cc25b3_0  
pynput                    1.7.1                    pypi_0    pypi
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pyparsing                 3.0.9            py38haa95532_0  
pypdf2                    1.26.0                   pypi_0    pypi
pypdf4                    1.27.0                   pypi_0    pypi
pyperclip                 1.8.0                    pypi_0    pypi
pyqt                      5.15.7           py38hd77b12b_0  
pyqt5-sip                 12.11.0          py38hd77b12b_0  
pyqtwebengine             5.15.7           py38hd77b12b_0  
pyrsistent                0.18.0           py38h196d8e1_0  
pysocks                   1.7.1            py38haa95532_0  
python                    3.8.3                he1778fa_2  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.16.2           py38haa95532_0  
python-libarchive-c       2.9                pyhd3eb1b0_1  
python-lsp-black          1.2.1            py38haa95532_0  
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0  
python-lsp-server         1.5.0            py38haa95532_0  
python-slugify            5.0.2              pyhd3eb1b0_0  
python-telegram-bot       13.0                     pypi_0    pypi
pytz                      2022.1           py38haa95532_0  
pywin32                   302              py38h2bbff1b_2  
pywin32-ctypes            0.2.0                 py38_1000  
pywinpty                  2.0.2            py38h5da7b33_0  
pyxnat                    1.3                      pypi_0    pypi
pyyaml                    6.0              py38h2bbff1b_1  
pyzmq                     23.2.0           py38hd77b12b_0  
qdarkstyle                3.0.2              pyhd3eb1b0_0  
qstylizer                 0.1.10             pyhd3eb1b0_0  
qt-main                   5.15.2               he8e5bd7_7  
qt-webengine              5.15.9               hb9a9bb5_4  
qtawesome                 1.0.3              pyhd3eb1b0_0  
qtconsole                 5.3.2            py38haa95532_0  
qtpy                      2.2.0            py38haa95532_0  
qtwebkit                  5.212                h3ad3cdb_4  
rdflib                    5.0.0                    pypi_0    pypi
requests                  2.28.1           py38haa95532_0  
rope                      0.22.0             pyhd3eb1b0_0  
rtree                     0.9.7            py38h2eaa2aa_1  
ruamel_yaml               0.15.100         py38h2bbff1b_0  
selenium                  3.141.0         py38he774522_1000  
send2trash                1.8.0              pyhd3eb1b0_1  
setuptools                63.4.1           py38haa95532_0  
simplejson                3.17.2                   pypi_0    pypi
sip                       6.6.2            py38hd77b12b_0  
six                       1.16.0             pyhd3eb1b0_1  
slate3k                   0.5.3                    pypi_0    pypi
sniffio                   1.2.0            py38haa95532_1  
snowballstemmer           2.2.0              pyhd3eb1b0_0  
sortedcontainers          2.4.0              pyhd3eb1b0_0  
soupsieve                 2.3.1              pyhd3eb1b0_0  
sphinx                    5.0.2            py38haa95532_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0  
spyder                    5.3.3            py38haa95532_0  
spyder-kernels            2.3.3            py38haa95532_0  
sqlite                    3.39.2               h2bbff1b_0  
sqlparse                  0.4.1                    pypi_0    pypi
terminado                 0.13.1           py38haa95532_0  
testpath                  0.6.0            py38haa95532_0  
text-unidecode            1.3                pyhd3eb1b0_0  
textdistance              4.2.1              pyhd3eb1b0_0  
texttable                 1.6.3                    pypi_0    pypi
three-merge               0.1.1              pyhd3eb1b0_0  
tika                      1.24                     pypi_0    pypi
tinycss                   0.4             pyhd3eb1b0_1002  
tk                        8.6.12               h2bbff1b_0  
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.1            py38haa95532_0  
tomlkit                   0.11.1           py38haa95532_0  
toolz                     0.11.2             pyhd3eb1b0_0  
tornado                   6.2              py38h2bbff1b_0  
tqdm                      4.64.0           py38haa95532_0  
traitlets                 5.1.1              pyhd3eb1b0_0  
typing-extensions         4.3.0            py38haa95532_0  
typing_extensions         4.3.0            py38haa95532_0  
tzlocal                   2.1                      pypi_0    pypi
ujson                     5.4.0            py38hd77b12b_0  
unidecode                 1.2.0              pyhd3eb1b0_0  
urllib3                   1.26.11          py38haa95532_0  
vc                        14.2                 h21ff451_1  
vs2015_runtime            14.27.29016          h5e58377_2  
wand                      0.6.3                    pypi_0    pypi
watchdog                  2.1.6            py38haa95532_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webcolors                 1.5                      pypi_0    pypi
webdriverdownloader       1.1.0.3                  pypi_0    pypi
webencodings              0.5.1                    py38_1  
websocket-client          0.58.0           py38haa95532_4  
whatthepatch              1.0.2            py38haa95532_0  
wheel                     0.37.1             pyhd3eb1b0_0  
widgetsnbextension        3.5.2            py38haa95532_0  
win_inet_pton             1.1.0            py38haa95532_0  
wincertstore              0.2              py38haa95532_2  
winpty                    0.4.3                         4  
wrapt                     1.14.1           py38h2bbff1b_0  
xlrd                      1.2.0                    pypi_0    pypi
xls2xlsx                  0.1.5                    pypi_0    pypi
xlsxwriter                1.3.4                      py_0  
xmltodict                 0.10.2                   pypi_0    pypi
xz                        5.2.5                h8cc25b3_1  
yaml                      0.2.5                he774522_0  
yapf                      0.31.0             pyhd3eb1b0_0  
zeromq                    4.3.4                hd77b12b_0  
zipp                      3.8.0            py38haa95532_0  
zlib                      1.2.12               h8cc25b3_3  
zstd                      1.5.2                h19a0ad4_0  

```
</details>

**Comment by ccordoba12** [comment]
Hey @opamuk, thanks for reporting. Please try to disable your antivirus or firewall, close Spyder and try again. That could be the cause of your problem.

**Comment by ccordoba12** [comment]
@opamuk, another option is for update your Pythoh version. For that, please close Spyder, open the Anaconda Prompt and run there

    conda update python

Hope that helps.

**Comment by opamuk** [comment]
Thanks @ccordoba12 , updating Python has worked for me.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
