### ISSUE TITLE
Spyder doesn't install correctly in a virtual environment

### ISSUE THREAD

**Issue by aldendy** [spyder-ide/spyder#19572]
### What steps will reproduce the problem?

1) install anaconda
2) clean and update anaconda
3) create a second environement
4) remove spyder from the base environement
5) install spyder in the second environement

### Traceback
```python-traceback
Error on reading from the event loop self pipe
loop: <ProactorEventLoop running=True closed=False debug=False>
Traceback (most recent call last):
  File "C:\Users\Super\anaconda3\envs\ansys_env\lib\asyncio\windows_events.py", line 453, in finish_recv
    return ov.getresult()
OSError: [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Super\anaconda3\envs\ansys_env\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "C:\Users\Super\anaconda3\envs\ansys_env\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\Super\anaconda3\envs\ansys_env\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request
```

## Versions

* Spyder version: 5.3.3  (conda)
* Python version: 3.8.0 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  63.4.1 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at C:\Users\Super\anaconda3\envs\ansys_env:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12             pyhd3eb1b0_0  
arrow                     1.2.2              pyhd3eb1b0_0  
astroid                   2.11.7           py38haa95532_0  
atomicwrites              1.4.0                      py_0  
attrs                     21.4.0             pyhd3eb1b0_0  
autopep8                  1.6.0              pyhd3eb1b0_1  
babel                     2.9.1              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
bcrypt                    3.2.0            py38h2bbff1b_1  
beautifulsoup4            4.11.1           py38haa95532_0  
binaryornot               0.4.4              pyhd3eb1b0_1  
black                     22.6.0           py38haa95532_0  
bleach                    4.1.0              pyhd3eb1b0_0  
brotlipy                  0.7.0           py38h2bbff1b_1003  
ca-certificates           2022.07.19           haa95532_0  
certifi                   2022.9.14        py38haa95532_0  
cffi                      1.15.1           py38h2bbff1b_0  
chardet                   4.0.0           py38haa95532_1003  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4            py38haa95532_0  
cloudpickle               2.0.0              pyhd3eb1b0_0  
colorama                  0.4.5            py38haa95532_0  
cookiecutter              1.7.3              pyhd3eb1b0_0  
cryptography              37.0.1           py38h21b164f_0  
debugpy                   1.5.1            py38hd77b12b_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
diff-match-patch          20200713           pyhd3eb1b0_0  
dill                      0.3.4              pyhd3eb1b0_0  
docutils                  0.18.1           py38haa95532_3  
entrypoints               0.4              py38haa95532_0  
flake8                    4.0.1              pyhd3eb1b0_1  
glib                      2.69.1               h5dc1a3c_1  
gst-plugins-base          1.18.5               h9e645db_0  
gstreamer                 1.18.5               hd78058f_0  
icu                       58.2                 ha925a31_3  
idna                      3.3                pyhd3eb1b0_0  
imagesize                 1.4.1            py38haa95532_0  
importlib-metadata        4.11.3           py38haa95532_0  
importlib_metadata        4.11.3               hd3eb1b0_0  
importlib_resources       5.2.0              pyhd3eb1b0_1  
inflection                0.5.1            py38haa95532_0  
intervaltree              3.1.0              pyhd3eb1b0_0  
ipykernel                 6.15.2           py38haa95532_0  
ipython                   7.31.1           py38haa95532_1  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
isort                     5.9.3              pyhd3eb1b0_0  
jedi                      0.18.1           py38haa95532_1  
jellyfish                 0.9.0            py38h2bbff1b_0  
jinja2                    3.0.3              pyhd3eb1b0_0  
jinja2-time               0.2.0              pyhd3eb1b0_3  
jpeg                      9e                   h2bbff1b_0  
jsonschema                4.4.0            py38haa95532_0  
jupyter_client            7.3.5            py38haa95532_0  
jupyter_core              4.10.0           py38haa95532_0  
jupyterlab_pygments       0.1.2                      py_0  
keyring                   23.4.0           py38haa95532_0  
lazy-object-proxy         1.6.0            py38h2bbff1b_0  
libclang                  12.0.0          default_h627e005_2  
libffi                    3.4.2                hd77b12b_4  
libiconv                  1.16                 h2bbff1b_2  
libogg                    1.3.5                h2bbff1b_1  
libpng                    1.6.37               h2a8f88b_0  
libsodium                 1.0.18               h62dcd97_0  
libspatialindex           1.9.3                h6c2663c_0  
libvorbis                 1.3.7                he774522_0  
libwebp                   1.2.2                h2bbff1b_0  
libxml2                   2.9.14               h0ad7f3c_0  
libxslt                   1.1.35               h2bbff1b_0  
lz4-c                     1.9.3                h2bbff1b_1  
markupsafe                2.1.1            py38h2bbff1b_0  
matplotlib-inline         0.1.6            py38haa95532_0  
mccabe                    0.7.0              pyhd3eb1b0_0  
mistune                   0.8.4           py38he774522_1000  
mypy_extensions           0.4.3            py38haa95532_1  
nbclient                  0.5.13           py38haa95532_0  
nbconvert                 6.4.4            py38haa95532_0  
nbformat                  5.5.0            py38haa95532_0  
nest-asyncio              1.5.5            py38haa95532_0  
numpydoc                  1.4.0            py38haa95532_0  
openssl                   1.1.1q               h2bbff1b_0  
packaging                 21.3               pyhd3eb1b0_0  
pandocfilters             1.5.0              pyhd3eb1b0_0  
paramiko                  2.8.1              pyhd3eb1b0_0  
parso                     0.8.3              pyhd3eb1b0_0  
pathspec                  0.9.0            py38haa95532_0  
pcre                      8.45                 hd77b12b_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pip                       22.1.2           py38haa95532_0  
platformdirs              2.5.2            py38haa95532_0  
pluggy                    1.0.0            py38haa95532_1  
ply                       3.11                     py38_0  
poyo                      0.5.0              pyhd3eb1b0_0  
prompt-toolkit            3.0.20             pyhd3eb1b0_0  
psutil                    5.9.0            py38h2bbff1b_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pycodestyle               2.8.0              pyhd3eb1b0_0  
pycparser                 2.21               pyhd3eb1b0_0  
pydocstyle                6.1.1              pyhd3eb1b0_0  
pyflakes                  2.4.0              pyhd3eb1b0_0  
pygments                  2.11.2             pyhd3eb1b0_0  
pylint                    2.14.5           py38haa95532_0  
pyls-spyder               0.4.0              pyhd3eb1b0_0  
pynacl                    1.5.0            py38h8cc25b3_0  
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pyparsing                 3.0.9            py38haa95532_0  
pyqt                      5.15.7           py38hd77b12b_0  
pyqt5-sip                 12.11.0          py38hd77b12b_0  
pyqtwebengine             5.15.7           py38hd77b12b_0  
pyrsistent                0.18.0           py38h196d8e1_0  
pysocks                   1.7.1            py38haa95532_0  
python                    3.8.0                hff0d562_2  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.16.2           py38haa95532_0  
python-lsp-black          1.2.1            py38haa95532_0  
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0  
python-lsp-server         1.5.0            py38haa95532_0  
python-slugify            5.0.2              pyhd3eb1b0_0  
pytz                      2022.1           py38haa95532_0  
pywin32                   302              py38h2bbff1b_2  
pywin32-ctypes            0.2.0                 py38_1000  
pyyaml                    6.0              py38h2bbff1b_1  
pyzmq                     23.2.0           py38hd77b12b_0  
qdarkstyle                3.0.2              pyhd3eb1b0_0  
qstylizer                 0.1.10             pyhd3eb1b0_0  
qt-main                   5.15.2               he8e5bd7_7  
qt-webengine              5.15.9               hb9a9bb5_4  
qtawesome                 1.0.3              pyhd3eb1b0_0  
qtconsole                 5.3.2            py38haa95532_0  
qtpy                      2.2.0            py38haa95532_0  
qtwebkit                  5.212                h3ad3cdb_4  
requests                  2.28.1           py38haa95532_0  
rope                      0.22.0             pyhd3eb1b0_0  
rtree                     0.9.7            py38h2eaa2aa_1  
setuptools                63.4.1           py38haa95532_0  
sip                       6.6.2            py38hd77b12b_0  
six                       1.16.0             pyhd3eb1b0_1  
snowballstemmer           2.2.0              pyhd3eb1b0_0  
sortedcontainers          2.4.0              pyhd3eb1b0_0  
soupsieve                 2.3.1              pyhd3eb1b0_0  
sphinx                    5.0.2            py38haa95532_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0  
spyder                    5.3.3            py38haa95532_0  
spyder-kernels            2.3.3            py38haa95532_0  
sqlite                    3.39.2               h2bbff1b_0  
testpath                  0.6.0            py38haa95532_0  
text-unidecode            1.3                pyhd3eb1b0_0  
textdistance              4.2.1              pyhd3eb1b0_0  
three-merge               0.1.1              pyhd3eb1b0_0  
tinycss                   0.4             pyhd3eb1b0_1002  
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.1            py38haa95532_0  
tomlkit                   0.11.1           py38haa95532_0  
tornado                   6.2              py38h2bbff1b_0  
traitlets                 5.1.1              pyhd3eb1b0_0  
typing-extensions         4.3.0            py38haa95532_0  
typing_extensions         4.3.0            py38haa95532_0  
ujson                     5.4.0            py38hd77b12b_0  
unidecode                 1.2.0              pyhd3eb1b0_0  
urllib3                   1.26.11          py38haa95532_0  
vc                        14.2                 h21ff451_1  
vs2015_runtime            14.27.29016          h5e58377_2  
watchdog                  2.1.6            py38haa95532_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1                    py38_1  
whatthepatch              1.0.2            py38haa95532_0  
wheel                     0.37.1             pyhd3eb1b0_0  
win_inet_pton             1.1.0            py38haa95532_0  
wincertstore              0.2              py38haa95532_2  
wrapt                     1.14.1           py38h2bbff1b_0  
yaml                      0.2.5                he774522_0  
yapf                      0.31.0             pyhd3eb1b0_0  
zeromq                    4.3.4                hd77b12b_0  
zipp                      3.8.0            py38haa95532_0  
zlib                      1.2.12               h8cc25b3_3  
zstd                      1.5.2                h19a0ad4_0  

```
</details>

**Comment by ccordoba12** [comment]
Hey @aldendy, thanks for reporting. That problem can be fixed by updating your Python version iin your env. For that, please close Spyder, open the Anaconda prompt and run there

    conda activate ansys_env
    conda update python
