### ISSUE TITLE
opening bracket in editor or console: focus switches to internal console (which also display an error)

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1961]
_From [chfreund...@gmail.com](https://code.google.com/u/112873540000874214429/) on 2014-09-10T10:09:48Z_

Hi,

opening a round bracket in either the editor or  a console lets spyder switch focus immediately to the internal console (i.e. if I continue typing that ends up in the internal console). I have installed spyder on a 32 bit ubuntu 12.04 via apt-get only two weeks ago.

The error message displayed in the console is as follows:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spyder-2.3.0-py2.7.egg/spyderlib/widgets/shell.py", line 298, in keyPressEvent
    self.postprocess_keyevent(event)
  File "/usr/local/lib/python2.7/dist-packages/spyder-2.3.0-py2.7.egg/spyderlib/widgets/shell.py", line 727, in postprocess_keyevent
    ShellBaseWidget.postprocess_keyevent(self, event)
  File "/usr/local/lib/python2.7/dist-packages/spyder-2.3.0-py2.7.egg/spyderlib/widgets/shell.py", line 438, in postprocess_keyevent
    self._key_parenleft(text)
  File "/usr/local/lib/python2.7/dist-packages/spyder-2.3.0-py2.7.egg/spyderlib/widgets/shell.py", line 797, in _key_parenleft
    self.show_object_info(last_obj, call=True)
  File "/usr/local/lib/python2.7/dist-packages/spyder-2.3.0-py2.7.egg/spyderlib/widgets/mixins.py", line 608, in show_object_info
    signature=True, color='#2D62FF')
  File "/usr/local/lib/python2.7/dist-packages/spyder-2.3.0-py2.7.egg/spyderlib/widgets/mixins.py", line 108, in show_calltip
    self.calltip_widget.show_tip(point, tiptext, wrapped_textlines)
  File "/usr/local/lib/python2.7/dist-packages/spyder-2.3.0-py2.7.egg/spyderlib/widgets/calltip.py", line 157, in show_tip
    forward=False)
  File "/usr/local/lib/python2.7/dist-packages/spyder-2.3.0-py2.7.egg/spyderlib/widgets/calltip.py", line 252, in _find_parenthesis
    while category(char) != 'Cc' and position > 0:
TypeError: need a single Unicode character as parameter

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1961_

**Comment by spyder-issues-migrator** [comment]
_From [chfreund...@gmail.com](https://code.google.com/u/112873540000874214429/) on 2014-09-11T06:06:42Z_

okay, nevermind... my own stupidity...I simply overlooked the option to turn it off in the preferences. (ashamed.)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-12T14:20:45Z_

This error will be fixed in our next release. I already did it in revision 76f249aa2ab3 because another user reported it to me personally and mentioned the fix.

Thanks for reporting though :-)

**Status:** Fixed  
  **Labels:** MS-v2.3.2 Cat-Editor

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-12T17:19:46Z_

issue #1989 has been merged into this issue.
