### ISSUE TITLE
Empty spydercell error

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1967]
_From [chennip...@gmail.com](https://code.google.com/u/111424170065783049590/) on 2014-09-15T07:10:10Z_

Spyder Version:  2.3.0beta2
Python Version:  3.3.5
Qt Version    :  4.8.4, PyQt4 (API v2) 4.9.6 on Windows
pyflakes >=0.6.0:  None (OK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  2.0.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  1.1.0 (OK) 

What steps will reproduce the problem?

 1.Create a spydercell without any computations in it. 

What is the expected output? What do you see instead?

 I would expect that nothing would happen. Instead I get an error of the internal console. 

Please provide any additional information below

. This is my first error report, so please do not be harsh to me. 

Example code:
some_code = 1

\#&#37;&#37; nothing happens in this cell

\#&#37;&#37; and this gives a problem

Traceback (most recent call last):
  File "C:\Users\(my-user-name)\Documents\Python\python-3.3.5.amd64\lib\site-packages\spyderlib\plugins\editor.py", line 2103, in run_cell_and_advance
    editorstack.run_cell_and_advance()
  File "C:\Users\(my-user-name)\Documents\Python\python-3.3.5.amd64\lib\site-packages\spyderlib\widgets\editor.py", line 1956, in run_cell_and_advance
    self.run_cell(focus_to_editor=True)
  File "C:\Users\(my-user-name)\Documents\Python\python-3.3.5.amd64\lib\site-packages\spyderlib\widgets\editor.py", line 1948, in run_cell
    text = self.get_current_editor().get_cell_as_executable_code()
  File "C:\Users\(my-user-name)\Documents\Python\python-3.3.5.amd64\lib\site-packages\spyderlib\widgets\sourcecode\base.py", line 502, in get_cell_as_executable_code
    text = self.get_selection_as_executable_code()
  File "C:\Users\(my-user-name)\Documents\Python\python-3.3.5.amd64\lib\site-packages\spyderlib\widgets\sourcecode\base.py", line 466, in get_selection_as_executable_code
    first_line = lines[0].lstrip()
IndexError: list index out of range

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1967_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-09-16T06:31:17Z_

This was fixed a long time ago. Please update from 2.3.0beta2 to 2.3.0 (which was released two months ago).

**Status:** WontFix

**Comment by spyder-issues-migrator** [comment]
_From [chennip...@gmail.com](https://code.google.com/u/111424170065783049590/) on 2014-09-18T06:43:31Z_

Thanks for your reaction. I used the newest version of WinPhyton, so I thought that I would also have the newest version of Spyder. As long as WinPhython is not updated I will simply not use empty cells. Thanks for your good work!!

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-09-18T07:40:11Z_

I don't know if WinPython will continue to be updated in the future. In any case, you can manually update Spyder by using our zip file from here: https://bitbucket.org/spyder-ide/spyderlib/downloads
