### ISSUE TITLE
Bug when creating a new console when spyder‑kernels requirement is not OK

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#19695]
## Problem Description

A bug occurs when creating a new console when spyder‑kernels requirement is not OK.

### What steps reproduce the problem?

1. Use an interpreter where `spyder‑kernels` is not installed or with an outdated version
2. Create a new console

### What is the expected output? What do you see instead?

It should not cause a bug.

### Paste Traceback/Error Below (if applicable)

```python-traceback
Traceback (most recent call last):
  File "C:\Users\jean-\Documents\Projets\spyder\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1797, in close_client
    self.create_new_client()
  File "C:\Users\jean-\Documents\Projets\spyder\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1530, in create_new_client
    client.show_kernel_error(
  File "C:\Users\jean-\Documents\Projets\spyder\spyder\plugins\ipythonconsole\widgets\client.py", line 536, in show_kernel_error
    self.shellwidget.shutdown()
  File "C:\Users\jean-\Documents\Projets\spyder\spyder\plugins\ipythonconsole\widgets\shell.py", line 178, in shutdown
    self.kernel_manager.stop_restarter()
AttributeError: 'NoneType' object has no attribute 'stop_restarter'
```

## Versions

* Spyder version: 5.3.0.dev0 b563ebda0
* Python version: 3.8.10 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.0.0 (OK)
cloudpickle >=0.5.0           :  2.2.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.9.3 (OK)
nbconvert >=4.0               :  7.1.0 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.11.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.2 (OK)
pygments >=2.0                :  2.13.0 (OK)
pylint >=2.5.0                :  2.15.3 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.2 (OK)
pylsp_black >=1.0.0           :  1.1.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.2 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.2.1 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  56.0.0 (OK)
sphinx >=0.6.6                :  5.2.3 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.3.0.dev0 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
zmq >=17                      :  24.0.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)

```

**Comment by jnsebgosselin** [comment]
I updated to latest 5.x commit and this seems to be fixed. Sorry for the noise.
