### ISSUE TITLE
syper

### ISSUE THREAD

**Issue by silpasuneesh** [spyder-ide/spyder#19707]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/asus/.local/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):
  File "/home/asus/.local/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "/home/asus/.local/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):
  File "/home/asus/.local/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):
  File "/home/asus/.local/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
      File "/usr/lib/python3/dist-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):
  File "/home/asus/.local/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):
  File "/home/asus/.local/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):
  File "/home/asus/.local/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.9
* Qt Versions: 5.9.5, PyQt5 5.10.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.12.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  1.6.7 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.17.2 (OK)
psutil >=0.3     :  5.4.2 (OK)
nbconvert >=4.0  :  6.0.7 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  5.2.2 (OK)
IPython >=4.0    :  7.16.3 (OK)
pylint >=0.25    :  1.8.3 (OK)

```

**Comment by ccordoba12** [comment]
Hey @silpasuneesh, thanks for reporting. This problem is fixed in a more recent Spyder version. Please update by closing Spyder, removing Anaconda and reinstalling it again.
