### ISSUE TITLE
MacOS+anaconda+Spyder crash

### ISSUE THREAD

**Issue by wyfwps** [spyder-ide/spyder#19739]
After I updated my macbook OS to Version 12.6,my Spyder IDE in Anaconda won't work. 
It crashed after I run the line "spyder run" in the terminal.
## Problem Description
The error infomations it applied were as follows:

The available OpenGL surface format was either not version 3.2 or higher or not a Core Profile.
Chromium on macOS will fall back to software rendering in this case.
Hardware acceleration and features such as WebGL will not be available.
fromIccProfile: failed minimal tag size sanity
Traceback (most recent call last):
  File "/Users/leonyfwu/opt/anaconda3/bin/Spyder", line 11, in <module>
    sys.exit(main())
  File "/Users/leonyfwu/opt/anaconda3/lib/python3.9/site-packages/spyder/app/start.py", line 252, in main
    mainwindow.main(options, args)
  File "/Users/leonyfwu/opt/anaconda3/lib/python3.9/site-packages/spyder/app/mainwindow.py", line 1956, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "/Users/leonyfwu/opt/anaconda3/lib/python3.9/site-packages/spyder/app/utils.py", line 300, in create_window
    main.post_visible_setup()
  File "/Users/leonyfwu/opt/anaconda3/lib/python3.9/site-packages/spyder/app/mainwindow.py", line 1085, in post_visible_setup
    self.reopen_last_session()
  File "/Users/leonyfwu/opt/anaconda3/lib/python3.9/site-packages/spyder/app/mainwindow.py", line 1123, in reopen_last_session
    editor.setup_open_files(close_previous_files=False)
  File "/Users/leonyfwu/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 3481, in setup_open_files
    self.load(filenames[index], goto=clines[index], set_focus=True)
  File "/Users/leonyfwu/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/editor/plugin.py", line 2265, in load
    finfo = self.editorstacks[0].load(
  File "/Users/leonyfwu/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/editor/widgets/editor.py", line 2691, in load
    text, enc = encoding.read(filename)
  File "/Users/leonyfwu/opt/anaconda3/lib/python3.9/site-packages/spyder/utils/encoding.py", line 308, in read
    text, encoding = decode( open(filename, 'rb').read() )
PermissionError: [Errno 1] Operation not permitted: '/Users/leonyfwu/Desktop/ml/perceptron.py'
/Users/leonyfwu/opt/anaconda3/bin/pythonw: line 3:  9687 Bus error: 10           /Users/leonyfwu/opt/anaconda3/python.app/Contents/MacOS/python "$@"

### What steps reproduce the problem?

1. update macbook OS 
2. update the whole packages with "conda update --all"
3. activate Spyder with "spyder run"

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.3.3
* Python version: 3.9.13
* Qt version: 5.15.9
* PyQt version: 5.15.7
* Operating System name/version: MacOS 12.6 Montery

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @wyfwps, thanks for reporting. Please open a terminal and run there

    conda install -f python.app

That should fix your problem. However, if it doesn't work, I'm afraid you'll have to reinstall Anaconda. As a general advice, in the future please avoid doing

    conda update --all

because it can introduce problems like this. It's better to update only the packages that you need and run

    conda update anaconda

when a new Anaconda version is released.
