### ISSUE TITLE
1

### ISSUE THREAD

**Issue by nikoioi** [spyder-ide/spyder#19768]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Dicer\AppData\Local\Programs\Python\Python36\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):
  File "C:\Users\Dicer\AppData\Local\Programs\Python\Python36\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):
  File "C:\Users\Dicer\AppData\Local\Programs\Python\Python36\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.7
* Qt Versions: 5.10.1, PyQt5 5.10.1 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  2.5.0 (OK)
pycodestyle >=2.3:  2.9.1 (OK)
pygments >=2.0   :  2.13.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  5.2.3 (OK)
rope >=0.9.4     :  1.1.1 (OK)
jedi >=0.9.0     :  0.17.2 (OK)
nbconvert >=4.0  :  6.0.7 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  5.2.2 (OK)
IPython >=4.0    :  7.16.3 (OK)
pylint >=0.25    :  2.13.9 (OK)

```

**Comment by ccordoba12** [comment]
Hey @nikoioi, thanks for reporting. This error happened because you're using a very old version of Spyder.

To fix it you need to update it by opening a system terminal (i.e. cmd.exe) and running there

    pip install -U spyder

That will give you a more recent Spyder version.
