### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by sivakannan87** [spyder-ide/spyder#19767]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
The error is:

Traceback (most recent call last):
File "C:\Users\sivak\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1554, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\sivak\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\Users\sivak\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 472, in write_connection_file
kernel_name=self.kernel_name
File "C:\Users\sivak\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 101, in write_connection_file
sock.bind((ip, 0))
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

**Comment by ccordoba12** [comment]
Hey @sivakannan87, thanks for reporting. This problem could be caused by your firewall and/or antivirus, so please disable them temporarily and try again.

Also, please go to the menu `Help > About Spyder`, click the button `Copy version info` and paste the result here. That could be useful to better understand your problem.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
