### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by abani-nayak** [spyder-ide/spyder#19877]
Can you help me on how to resolve the following issue?

I followed the tutorial for creating new environments and spyder kernels as mentioned in your youtube channel:
https://www.youtube.com/watch?v=Ul79ihg41Rs

My spyder version is: 3.1.4
Below is my conda version that I retrieved from Anaconda prompt:
Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.6
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3\envs\abani-env
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\nayak\AppData\Local\conda\conda\envs
                          C:\Users\nayak\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\nayak\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.14393
          administrator : False

When I am launching spyder, I am getting the following error in the IPython console window:

      Error in sitecustomize; set PYTHONVERBOSE for traceback:
      AttributeError: module 'collections' has no attribute 'MutableMapping'
      Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 231, in 
      main()
      File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 204, in main
      from ipykernel.kernelapp import IPKernelApp
      File "C:\ProgramData\Anaconda3\lib\site‑packages\ipykernel\__init__.py", line 2, in 
      from .connect import *
      File "C:\ProgramData\Anaconda3\lib\site‑packages\ipykernel\connect.py", line 18, in 
      import jupyter_client
      File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\__init__.py", line 4, in 
      from .connect import *
      File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 22, in 
      import zmq
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\__init__.py", line 34, in 
      from zmq import backend
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 40, in 
      reraise(*exc_info)
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\utils\sixcerpt.py", line 34, in reraise
      raise value
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 27, in 
      _ns = select_backend(first)
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\select.py", line 26, in select_backend
      mod = __import__(name, fromlist=public_api)
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\cython\__init__.py", line 6, in 
      from . import (constants, error, message, context,
      ImportError: cannot import name 'constants' from partially initialized module 'zmq.backend.cython' (most likely due to a circular import) (C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\cython\__init__.py)
      Error in sitecustomize; set PYTHONVERBOSE for traceback:
      AttributeError: module 'collections' has no attribute 'MutableMapping'
      Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 231, in 
      main()
      File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 204, in main
      from ipykernel.kernelapp import IPKernelApp
      File "C:\ProgramData\Anaconda3\lib\site‑packages\ipykernel\__init__.py", line 2, in 
      from .connect import *
      File "C:\ProgramData\Anaconda3\lib\site‑packages\ipykernel\connect.py", line 18, in 
      import jupyter_client
      File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\__init__.py", line 4, in 
      from .connect import *
      File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 22, in 
      import zmq
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\__init__.py", line 34, in 
      from zmq import backend
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 40, in 
      reraise(*exc_info)
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\utils\sixcerpt.py", line 34, in reraise
      raise value
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 27, in 
      _ns = select_backend(first)
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\select.py", line 26, in select_backend
      mod = __import__(name, fromlist=public_api)
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\cython\__init__.py", line 6, in 
      from . import (constants, error, message, context,
      ImportError: cannot import name 'constants' from partially initialized module 'zmq.backend.cython' (most likely due to a circular import) (C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\cython\__init__.py)
      Error in sitecustomize; set PYTHONVERBOSE for traceback:
      AttributeError: module 'collections' has no attribute 'MutableMapping'
      Traceback (most recent call last):
      from ipykernel.kernelapp import IPKernelApp
      File "C:\ProgramData\Anaconda3\lib\site‑packages\ipykernel\__init__.py", line 2, in 
      from .connect import *
      File "C:\ProgramData\Anaconda3\lib\site‑packages\ipykernel\connect.py", line 18, in 
      import jupyter_client
      File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\__init__.py", line 4, in 
      from .connect import *
      File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 22, in 
      import zmq
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\__init__.py", line 34, in 
      from zmq import backend
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 40, in 
      reraise(*exc_info)
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\utils\sixcerpt.py", line 34, in reraise
      raise value
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 27, in 
      _ns = select_backend(first)
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\select.py", line 26, in select_backend
      mod = __import__(name, fromlist=public_api)
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\cython\__init__.py", line 6, in 
      from . import (constants, error, message, context,
      ImportError: cannot import name 'constants' from partially initialized module 'zmq.backend.cython' (most likely due to a circular import) (C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\cython\__init__.py)
      Error in sitecustomize; set PYTHONVERBOSE for traceback:
      AttributeError: module 'collections' has no attribute 'MutableMapping'
      Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 231, in 
      main()
      File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 204, in main
      from ipykernel.kernelapp import IPKernelApp
      File "C:\ProgramData\Anaconda3\lib\site‑packages\ipykernel\__init__.py", line 2, in 
      from .connect import *
      File "C:\ProgramData\Anaconda3\lib\site‑packages\ipykernel\connect.py", line 18, in 
      import jupyter_client
      File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\__init__.py", line 4, in 
      from .connect import *
      File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 22, in 
      import zmq
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\__init__.py", line 34, in 
      from zmq import backend
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 40, in 
      reraise(*exc_info)
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\utils\sixcerpt.py", line 34, in reraise
      raise value
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 27, in 
      _ns = select_backend(first)
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\select.py", line 26, in select_backend
      mod = __import__(name, fromlist=public_api)
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\cython\__init__.py", line 6, in 
      from . import (constants, error, message, context,
      ImportError: cannot import name 'constants' from partially initialized module 'zmq.backend.cython' (most likely due to a circular import) (C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\cython\__init__.py)
      Error in sitecustomize; set PYTHONVERBOSE for traceback:
      AttributeError: module 'collections' has no attribute 'MutableMapping'
      Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 231, in 
      main()
      File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 204, in main
      from ipykernel.kernelapp import IPKernelApp
      File "C:\ProgramData\Anaconda3\lib\site‑packages\ipykernel\__init__.py", line 2, in 
      from .connect import *
      File "C:\ProgramData\Anaconda3\lib\site‑packages\ipykernel\connect.py", line 18, in 
      import jupyter_client
      File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\__init__.py", line 4, in 
      from .connect import *
      File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 22, in 
      import zmq
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\__init__.py", line 34, in 
      from zmq import backend
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 40, in 
      reraise(*exc_info)
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\utils\sixcerpt.py", line 34, in reraise
      raise value
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 27, in 
      _ns = select_backend(first)
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\select.py", line 26, in select_backend
      mod = __import__(name, fromlist=public_api)
      File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\cython\__init__.py", line 6, in 
      from . import (constants, error, message, context,
      ImportError: cannot import name 'constants' from partially initialized module 'zmq.backend.cython' (most likely due to a circular import) (C:\ProgramData\Anaconda3\lib\site‑packages\zmq\backend\cython\__init__.py)

**Comment by ccordoba12** [comment]
Hey @abani-nayak, thanks for reporting. You said

> My spyder version is: 3.1.4

That version is four years old now, which is probably the reason why the kernel is failing to start for you.

So, please remove Anaconda as described in the Youtube video you mentioned and install its latest version instead. Almost surely you'll see the error fixed, but let us know if it doesn't work for you.

**Comment by abani-nayak** [comment]
Hii @ccordoba12 

Thanks for the solution. I have installed the latest version. But, now I am facing a different problem. Whenever, I am trying to install packages from conda-forge, after the creation of a new environment, I am getting the following error:

> (env) C:\Users\nayak>conda install -c conda-forge numpy
      
    Collecting package metadata (current_repodata.json): failed
    
    CondaSSLError: OpenSSL appears to be unavailable on this machine. OpenSSL is required to
    download and install packages.
    
    Exception: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/win-64/current_repodata.json (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
    


 

You can see the information about my current conda version below:

> (env) C:\Users\nayak>conda info

    active environment : env
        active env location : C:\Users\nayak\Anaconda3\envs\env
                shell level : 2
           user config file : C:\Users\nayak\.condarc
     populated config files : C:\Users\nayak\.condarc
              conda version : 22.9.0
        conda-build version : 3.22.0
             python version : 3.9.13.final.0
           virtual packages : __win=0=0
                              __archspec=1=x86_64
           base environment : C:\Users\nayak\Anaconda3  (writable)
          conda av data dir : C:\Users\nayak\Anaconda3\etc\conda
      conda av metadata url : None
               channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                              https://repo.anaconda.com/pkgs/main/noarch
                              https://repo.anaconda.com/pkgs/r/win-64
                              https://repo.anaconda.com/pkgs/r/noarch
                              https://repo.anaconda.com/pkgs/msys2/win-64
                              https://repo.anaconda.com/pkgs/msys2/noarch
              package cache : C:\Users\nayak\Anaconda3\pkgs
                              C:\Users\nayak\.conda\pkgs
                              C:\Users\nayak\AppData\Local\conda\conda\pkgs
           envs directories : C:\Users\nayak\Anaconda3\envs
                              C:\Users\nayak\.conda\envs
                              C:\Users\nayak\AppData\Local\conda\conda\envs
                   platform : win-64
                 user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.13 Windows/10 Windows/10.0.19044
              administrator : False
                 netrc file : None
               offline mode : False

I do not know how to install packages now. Can you please help me?

**Comment by ccordoba12** [comment]
What command did you use to create your environment?

**Comment by abani-nayak** [comment]
I have used the following command:

> conda create -n env -c conda-forge python=3

**Comment by ccordoba12** [comment]
Ok, that's the right command. Perhaps the installation of packages is blocked because you have a proxy or firewall that is blocking internet connections?

**Comment by abani-nayak** [comment]
The problem is fixed now partially. I used the anaconda navigator -- the graphical user interface to install packages. Because, that is also an option to install packages and creating new environments for non-terminal users. I was able to install packages using anaconda navigator into my environment without any problem or issue. Though, I did not interfere with my internet connections.  

For now, the spyder is working fine. But, I do not know where the problem is with the anaconda prompt terminal.

**Comment by ccordoba12** [comment]
> For now, the spyder is working fine.

Ok, that's great! Thanks for letting us know about it.

> But, I do not know where the problem is with the anaconda prompt terminal.

I don't know either.

I'm going to close this issue because your Spyder problem was solved.
