### ISSUE TITLE
fail to kill the procedure

### ISSUE THREAD

**Issue by twinkling688** [spyder-ide/spyder#19878]
### What steps will reproduce the problem?

wrong code make the procedure keep running and cannot kill it.

### Traceback
```python-traceback
  File "D:\Anaconda3\lib\asyncio\base_events.py", line 656, in __del__
    self.close()
  File "D:\Anaconda3\lib\asyncio\selector_events.py", line 92, in close
    self._close_self_pipe()
  File "D:\Anaconda3\lib\asyncio\selector_events.py", line 99, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
  File "D:\Anaconda3\lib\asyncio\selector_events.py", line 274, in _remove_reader
    key = self._selector.get_key(fd)
  File "D:\Anaconda3\lib\selectors.py", line 190, in get_key
    return mapping[fileobj]
  File "D:\Anaconda3\lib\selectors.py", line 71, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "D:\Anaconda3\lib\selectors.py", line 225, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "D:\Anaconda3\lib\selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
Exception ignored in: <function BaseEventLoop.__del__ at 0x00000295CDFC7EE0>
Traceback (most recent call last):
  File "D:\Anaconda3\lib\asyncio\base_events.py", line 656, in __del__
    self.close()
  File "D:\Anaconda3\lib\asyncio\selector_events.py", line 92, in close
    self._close_self_pipe()
  File "D:\Anaconda3\lib\asyncio\selector_events.py", line 99, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
  File "D:\Anaconda3\lib\asyncio\selector_events.py", line 274, in _remove_reader
    key = self._selector.get_key(fd)
  File "D:\Anaconda3\lib\selectors.py", line 190, in get_key
    return mapping[fileobj]
  File "D:\Anaconda3\lib\selectors.py", line 71, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "D:\Anaconda3\lib\selectors.py", line 225, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "D:\Anaconda3\lib\selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
```

## Versions

* Spyder version: 4.1.4 
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  2.0.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  8.4.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.4.4 (OK)
numpydoc >=0.6.0               :  1.4.0 (OK)
paramiko >=2.4.0               :  2.8.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.9.0 (OK)
pygments >=2.0                 :  2.11.2 (OK)
pylint >=1.0                   :  2.12.2 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  3.0.2 (OK)
qtawesome >=0.5.7              :  1.0.3 (OK)
qtconsole >=4.6.0              :  5.3.1 (OK)
qtpy >=1.5.0                   :  2.0.1 (OK)
rtree >=0.8.3                  :  0.9.7 (OK)
sphinx >=0.6.6                 :  5.0.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  23.2.0 (OK)

# Optional:
cython >=0.21                  :  0.29.30 (OK)
matplotlib >=2.0.0             :  3.5.1 (OK)
numpy >=1.7                    :  1.21.5 (OK)
pandas >=0.13.1                :  1.4.3 (OK)
scipy >=0.17.0                 :  1.7.3 (OK)
sympy >=0.7.3                  :  1.10.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @twinkling688, thanks for reporting. Please close Spyder, open the Anaconda Prompt and run there

    conda update python

then try again. If that doesn't work, you have to update Spyder to a more recent version. For that, close Spyder again and run

    conda remove spyder
    conda update anaconda
    conda install spyder=5.3.3

Let us know if that works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
