### ISSUE TITLE
Error internal console

### ISSUE THREAD

**Issue by JahongirQurbonov** [spyder-ide/spyder#19881]
### What steps will reproduce the problem?

Internal console error

  File "/usr/lib/python3.10/code.py", line 63, in runsource
    code = self.compile(source, filename, symbol)
  File "/usr/lib/python3.10/codeop.py", line 153, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
  File "/usr/lib/python3.10/codeop.py", line 73, in _maybe_compile
    return compiler(source, filename, symbol)
  File "/usr/lib/python3.10/codeop.py", line 118, in __call__
    codeob = compile(source, filename, symbol, self.flags, True)
  File "<console>", line 2
    dir
    ^
SyntaxError: invalid syntax

### Traceback
```python-traceback
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.10/code.py", line 63, in runsource
    code = self.compile(source, filename, symbol)
  File "/usr/lib/python3.10/codeop.py", line 153, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
  File "/usr/lib/python3.10/codeop.py", line 73, in _maybe_compile
    return compiler(source, filename, symbol)
  File "/usr/lib/python3.10/codeop.py", line 118, in __call__
    codeob = compile(source, filename, symbol, self.flags, True)
  File "<console>", line 2
    dir
    ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jahongir/.envs/spyder-env/lib/python3.10/site-packages/spyder/plugins/console/widgets/internalshell.py", line 245, in stderr_avail
    self.write(data, error=True)
  File "/home/jahongir/.envs/spyder-env/lib/python3.10/site-packages/spyder/plugins/console/widgets/shell.py", line 545, in write
    self.flush(error=error)
  File "/home/jahongir/.envs/spyder-env/lib/python3.10/site-packages/spyder/plugins/console/widgets/internalshell.py", line 338, in flush
    raise KeyboardInterrupt
KeyboardInterrupt
  File "/usr/lib/python3.10/code.py", line 63, in runsource
    code = self.compile(source, filename, symbol)
  File "/usr/lib/python3.10/codeop.py", line 153, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
  File "/usr/lib/python3.10/codeop.py", line 73, in _maybe_compile
    return compiler(source, filename, symbol)
  File "/usr/lib/python3.10/codeop.py", line 118, in __call__
    codeob = compile(source, filename, symbol, self.flags, True)
  File "<console>", line 2
    dir
    ^
SyntaxError: invalid syntax
```

## Versions

* Spyder version: 5.3.3  (pip)
* Python version: 3.10.8 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Linux 6.0.2-arch1-1

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.0.0 (OK)
cloudpickle >=0.5.0                  :  2.2.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0              :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.16.0 (OK)
keyring >=17.0.0                     :  23.9.3 (OK)
nbconvert >=4.0                      :  7.2.1 (OK)
numpydoc >=0.6.0                     :  1.5.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.2 (OK)
pygments >=2.0                       :  2.13.0 (OK)
pylint >=2.5.0;<3.0                  :  2.15.4 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0                 :  1.5.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.2 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.2;<5.4.0             :  5.3.2 (OK)
qtpy >=2.1.0                         :  2.2.1 (OK)
rtree >=0.9.7                        :  1.0.1 (OK)
setuptools >=49.6.0                  :  63.2.0 (OK)
sphinx >=0.6.6                       :  5.3.0 (OK)
spyder_kernels >=2.3.3;<2.4.0        :  2.3.3 (OK)
textdistance >=4.2.0                 :  4.5.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.9 (OK)
xdg >=0.26                           :  0.28 (OK)
zmq >=22.1.0                         :  24.0.1 (OK)

# Optional:
cython >=0.21                        :  None (NOK)
matplotlib >=3.0.0                   :  None (NOK)
numpy >=1.7                          :  None (NOK)
pandas >=1.1.1                       :  None (NOK)
scipy >=0.17.0                       :  None (NOK)
sympy >=0.7.3                        :  None (NOK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

### Environment

<details><summary>Environment</summary>

```
Package                       Version
----------------------------- -----------
alabaster                     0.7.12
arrow                         1.2.3
astroid                       2.12.11
atomicwrites                  1.4.1
attrs                         22.1.0
autopep8                      1.6.0
Babel                         2.10.3
backcall                      0.2.0
beautifulsoup4                4.11.1
binaryornot                   0.4.4
black                         22.10.0
bleach                        5.0.1
certifi                       2022.9.24
cffi                          1.15.1
chardet                       5.0.0
charset-normalizer            2.1.1
click                         8.1.3
cloudpickle                   2.2.0
coloredlogs                   15.0.1
cookiecutter                  2.1.1
cryptography                  38.0.1
debugpy                       1.6.3
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20200713
dill                          0.3.5.1
docutils                      0.19
entrypoints                   0.4
fastjsonschema                2.16.2
flake8                        4.0.1
humanfriendly                 10.0
idna                          3.4
imagesize                     1.4.1
inflection                    0.5.1
intervaltree                  3.1.0
ipykernel                     6.16.0
ipython                       7.34.0
ipython-genutils              0.2.0
isort                         5.10.1
jaraco.classes                3.2.3
jedi                          0.18.1
jeepney                       0.8.0
jellyfish                     0.9.0
Jinja2                        3.1.2
jinja2-time                   0.2.0
jsonschema                    4.16.0
jupyter_client                7.4.2
jupyter-core                  4.11.1
jupyterlab-pygments           0.2.2
keyring                       23.9.3
lazy-object-proxy             1.7.1
MarkupSafe                    2.1.1
matplotlib-inline             0.1.6
mccabe                        0.6.1
mistune                       2.0.4
more-itertools                9.0.0
mypy-extensions               0.4.3
nbclient                      0.7.0
nbconvert                     7.2.1
nbformat                      5.7.0
nest-asyncio                  1.5.6
numpydoc                      1.5.0
packaging                     21.3
pandocfilters                 1.5.0
parso                         0.8.3
pathspec                      0.10.1
pexpect                       4.8.0
pickleshare                   0.7.5
pip                           22.3
platformdirs                  2.5.2
pluggy                        1.0.0
prompt-toolkit                3.0.31
psutil                        5.9.2
ptyprocess                    0.7.0
pycodestyle                   2.8.0
pycparser                     2.21
pydocstyle                    6.1.1
pyflakes                      2.4.0
Pygments                      2.13.0
pylint                        2.15.4
pyls-spyder                   0.4.0
pyparsing                     3.0.9
PyQt5                         5.15.7
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.11.0
PyQtWebEngine                 5.15.6
PyQtWebEngine-Qt5             5.15.2
pyrsistent                    0.18.1
python-dateutil               2.8.2
python-lsp-black              1.2.1
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.5.0
python-slugify                6.1.2
pytoolconfig                  1.2.2
pytz                          2022.5
pyxdg                         0.28
PyYAML                        6.0
pyzmq                         24.0.1
QDarkStyle                    3.0.3
qstylizer                     0.2.2
QtAwesome                     1.1.1
qtconsole                     5.3.2
QtPy                          2.2.1
requests                      2.28.1
rope                          1.3.0
Rtree                         1.0.1
SecretStorage                 3.3.3
setuptools                    63.2.0
six                           1.16.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.3.2.post1
Sphinx                        5.3.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.3.3
spyder-kernels                2.3.3
spyder-terminal               1.2.2
terminado                     0.16.0
text-unidecode                1.3
textdistance                  4.5.0
three-merge                   0.1.1
tinycss2                      1.2.1
toml                          0.10.2
tomli                         2.0.1
tomlkit                       0.11.5
tornado                       6.2
traitlets                     5.5.0
ujson                         5.5.0
urllib3                       1.26.12
watchdog                      2.1.9
wcwidth                       0.2.5
webencodings                  0.5.1
whatthepatch                  1.0.2
wrapt                         1.14.1
wurlitzer                     3.0.2
yapf                          0.32.0

```
</details>

**Comment by ccordoba12** [comment]
Hey @JahongirQurbonov, thanks for reporting. I don't understand what kind of code you're running that generates this error, but the Internal console is only meant it to explore Spyder internals, as mentioned on its header message

![image](https://user-images.githubusercontent.com/365293/196544468-adf7ba99-c046-4fa6-9375-42c31941dbca.png)

Furthermore, any error generated on it will be reported as an internal Spyder error. But that's because of the way Spyder is designed.

So, I'd like to ask you: any reason why you're using that console instead of the IPython one?

**Comment by JahongirQurbonov** [comment]
I sent an error without understanding some things. It was stupid. Sorry to take up your time.

**Comment by ccordoba12** [comment]
Ok, no problem. Thanks for letting us know about it.
