### ISSUE TITLE
Errors when using ")" character and when trying to use "Report issue" or "Version"

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1989]
_From [19.jaime...@gmail.com](https://code.google.com/u/100448590108324513221/) on 2014-09-28T06:57:33Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 ")" character, "Report issue", "version" 

What is the expected output? What do you see instead?

 What version of the product are you using? On what operating system? SteamOS (Debian wheezy moded) 
\#####
sudo pip install spyder --upgrade
[sudo] password for desktop: 
Requirement already up-to-date: spyder in /usr/local/lib/python2.7/dist-packages
Cleaning up...
\### 

Please provide any additional information below

. Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

\>>> Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/sourcecode/base.py", line 138, in keyPressEvent
    self.textedit.keyPressEvent(event)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/shell.py", line 298, in keyPressEvent
    self.postprocess_keyevent(event)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/shell.py", line 727, in postprocess_keyevent
(    ShellBaseWidget.postprocess_keyevent(self, event)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/shell.py", line 438, in postprocess_keyevent
    self._key_parenleft(text)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/shell.py", line 797, in _key_parenleft
    self.show_object_info(last_obj, call=True)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/mixins.py", line 608, in show_object_info
    signature=True, color='#2D62FF')
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/mixins.py", line 108, in show_calltip
    self.calltip_widget.show_tip(point, tiptext, wrapped_textlines)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/calltip.py", line 157, in show_tip
    forward=False)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/calltip.py", line 252, in _find_parenthesis
    while category(char) != 'Cc' and position > 0:
TypeError: need a single Unicode character as parameter
)
  File "<console>", line 2
    )
    ^
SyntaxError: invalid syntax
\>>> Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/editor.py", line 461, in show_object_info
    at_position=position)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/mixins.py", line 108, in show_calltip
    self.calltip_widget.show_tip(point, tiptext, wrapped_textlines)
)  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/calltip.py", line 157, in show_tip
    forward=False)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/calltip.py", line 252, in _find_parenthesis
    while category(char) != 'Cc' and position > 0:
TypeError: need a single Unicode character as parameter
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/editor.py", line 461, in show_object_info
    at_position=position)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/mixins.py", line 108, in show_calltip
    self.calltip_widget.show_tip(point, tiptext, wrapped_textlines)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/calltip.py", line 157, in show_tip
    forward=False)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/calltip.py", line 252, in _find_parenthesis
    while category(char) != 'Cc' and position > 0:
TypeError: need a single Unicode character as parameter
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/spyder.py", line 1720, in about
    versions = get_versions()
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/__init__.py", line 66, in get_versions
    from IPython.external import qt
  File "/usr/lib/python2.7/dist-packages/IPython/external/qt.py", line 47, in \<module>
    prepare_pyqt4()
  File "/usr/lib/python2.7/dist-packages/IPython/external/qt.py", line 20, in prepare_pyqt4
    sip.setapi('QString', 2)
ValueError: API 'QString' has already been set to version 1
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/spyder.py", line 1775, in report_issue
    versions = get_versions()
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/__init__.py", line 66, in get_versions
    from IPython.external import qt
  File "/usr/lib/python2.7/dist-packages/IPython/external/qt.py", line 47, in \<module>
    prepare_pyqt4()
  File "/usr/lib/python2.7/dist-packages/IPython/external/qt.py", line 20, in prepare_pyqt4
    sip.setapi('QString', 2)
ValueError: API 'QString' has already been set to version 1

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1989_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-12T17:19:45Z_

I fixed this one. Please check when 2.3.2 is released, else open a new issue.

**Status:** Duplicate  
  **Mergedinto:** 1961
