### ISSUE TITLE
exception in spyder internal console when typing 'exit(' in editor

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1990]
_From [12w13d2...@gmail.com](https://code.google.com/u/114540585018913879598/) on 2014-09-30T04:00:06Z_

Spyder Version:  2.3.1
Python Version:  2.7.6
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Linux
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  1.2.1 (OK)
pygments >=1.6  :  1.6 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  None (NOK)
rope >=0.9.2    :  0.10.2 (OK)
matplotlib >=1.0:  1.4.0 (OK)
sympy >=0.7.0   :  None (NOK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1. type 'exit(' in the editor 2. 3. 

What is the expected output? What do you see instead?

 output of internal console:

Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

\>>> Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/editor.py", line 433, in show_object_info
    signature = getsignaturefromtext(doc_text, obj_name)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/utils/dochelpers.py", line 178, in getsignaturefromtext
    sigs_1 = re.findall(oneline_re + '|' + multiline_re, text)
  File "/usr/lib/python2.7/re.py", line 177, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or buffer 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1990_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T15:31:05Z_

**Labels:** MS-v2.3.3 Cat-Editor

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-18T13:33:51Z_

This was fixed in revision b31892ba739e

**Status:** Fixed
