### ISSUE TITLE
[BUG] Syntax highlight fails on broken emoji and Spyder will rise error

### ISSUE THREAD

**Issue by Parlazo** [spyder-ide/spyder#19930]
### What steps will reproduce the problem?

```
# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a script file.
"""

print("""
      🐛🌿�
      """)
print("this is now without syntax highlight")

### What steps will reproduce the problem?

<!--- You can use Markdown here --->

# just copythis into an UTF-8 windows *.py file

# print("""
#       🐛🌿�
#       """)

# i try spyder 1th time and did copy this from a text editor into spyder.

# in text editor some emojis appear as a combination or two letters
# on some emojis if i hit backspace after them they turn into an other symbol or unknown symbol
# but they do not break syntax highlight
# the code with this fragment i did run many times in CMD and had no problem
# Editor can handle the may  unknown broken symbol and python can handle it too
# Spyder cant handle it an will rise an error and asks to send this description
# it will break the sntax highlight.
# this emojy string i got from an telegram chat title
# so even if it is a broken emoji i consider it as correct
# Spyder should be able to handle weird stuff even if it is odd
# The rest looks cool so far, so please fix this error in Spyder
```

**Comment by Parlazo** [comment]
this is in details

```
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 325, in highlightBlock
    self.highlight_block(text)
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 644, in highlight_block
    self.setFormat(0, qstring_length(text), self.formats["normal"])
  File "C:\Program Files\Spyder\pkgs\spyder\utils\qstringhelpers.py", line 19, in qstring_length
    utf16_text = text.encode('utf16')
UnicodeEncodeError: 'utf-16' codec can't encode character '\udd0d' in position 9: surrogates not allowed
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 325, in highlightBlock
    self.highlight_block(text)
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 644, in highlight_block
    self.setFormat(0, qstring_length(text), self.formats["normal"])
  File "C:\Program Files\Spyder\pkgs\spyder\utils\qstringhelpers.py", line 19, in qstring_length
    utf16_text = text.encode('utf16')
UnicodeEncodeError: 'utf-16' codec can't encode character '\udd0d' in position 11: surrogates not allowed
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 325, in highlightBlock
    self.highlight_block(text)
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 644, in highlight_block
    self.setFormat(0, qstring_length(text), self.formats["normal"])
  File "C:\Program Files\Spyder\pkgs\spyder\utils\qstringhelpers.py", line 19, in qstring_length
    utf16_text = text.encode('utf16')
UnicodeEncodeError: 'utf-16' codec can't encode character '\udd0d' in position 12: surrogates not allowed
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 325, in highlightBlock
    self.highlight_block(text)
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 644, in highlight_block
    self.setFormat(0, qstring_length(text), self.formats["normal"])
  File "C:\Program Files\Spyder\pkgs\spyder\utils\qstringhelpers.py", line 19, in qstring_length
    utf16_text = text.encode('utf16')
UnicodeEncodeError: 'utf-16' codec can't encode character '\udd0d' in position 10: surrogates not allowed
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 325, in highlightBlock
    self.highlight_block(text)
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 644, in highlight_block
    self.setFormat(0, qstring_length(text), self.formats["normal"])
  File "C:\Program Files\Spyder\pkgs\spyder\utils\qstringhelpers.py", line 19, in qstring_length
    utf16_text = text.encode('utf16')
UnicodeEncodeError: 'utf-16' codec can't encode character '\udd0d' in position 11: surrogates not allowed
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 325, in highlightBlock
    self.highlight_block(text)
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 644, in highlight_block
    self.setFormat(0, qstring_length(text), self.formats["normal"])
  File "C:\Program Files\Spyder\pkgs\spyder\utils\qstringhelpers.py", line 19, in qstring_length
    utf16_text = text.encode('utf16')
UnicodeEncodeError: 'utf-16' codec can't encode character '\udd0d' in position 12: surrogates not allowed
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 325, in highlightBlock
    self.highlight_block(text)
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 644, in highlight_block
    self.setFormat(0, qstring_length(text), self.formats["normal"])
  File "C:\Program Files\Spyder\pkgs\spyder\utils\qstringhelpers.py", line 19, in qstring_length
    utf16_text = text.encode('utf16')
UnicodeEncodeError: 'utf-16' codec can't encode character '\udd0d' in position 12: surrogates not allowed
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 325, in highlightBlock
    self.highlight_block(text)
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 644, in highlight_block
    self.setFormat(0, qstring_length(text), self.formats["normal"])
  File "C:\Program Files\Spyder\pkgs\spyder\utils\qstringhelpers.py", line 19, in qstring_length
    utf16_text = text.encode('utf16')
UnicodeEncodeError: 'utf-16' codec can't encode character '\udd0d' in position 12: surrogates not allowed
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 325, in highlightBlock
    self.highlight_block(text)
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 644, in highlight_block
    self.setFormat(0, qstring_length(text), self.formats["normal"])
  File "C:\Program Files\Spyder\pkgs\spyder\utils\qstringhelpers.py", line 19, in qstring_length
    utf16_text = text.encode('utf16')
UnicodeEncodeError: 'utf-16' codec can't encode character '\udd0d' in position 8: surrogates not allowed
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 325, in highlightBlock
    self.highlight_block(text)
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 644, in highlight_block
    self.setFormat(0, qstring_length(text), self.formats["normal"])
  File "C:\Program Files\Spyder\pkgs\spyder\utils\qstringhelpers.py", line 19, in qstring_length
    utf16_text = text.encode('utf16')
UnicodeEncodeError: 'utf-16' codec can't encode character '\udd0d' in position 9: surrogates not allowed
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 325, in highlightBlock
    self.highlight_block(text)
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 644, in highlight_block
    self.setFormat(0, qstring_length(text), self.formats["normal"])
  File "C:\Program Files\Spyder\pkgs\spyder\utils\qstringhelpers.py", line 19, in qstring_length
    utf16_text = text.encode('utf16')
UnicodeEncodeError: 'utf-16' codec can't encode character '\udd0d' in position 10: surrogates not allowed
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 1178, in highlightBlock
    self.setFormat(0, qstring_length(text), self.formats["normal"])
  File "C:\Program Files\Spyder\pkgs\spyder\utils\qstringhelpers.py", line 19, in qstring_length
    utf16_text = text.encode('utf16')
UnicodeEncodeError: 'utf-16' codec can't encode character '\udd0d' in position 8: surrogates not allowed
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\utils\syntaxhighlighters.py", line 1178, in highlightBlock
    self.setFormat(0, qstring_length(text), self.formats["normal"])
  File "C:\Program Files\Spyder\pkgs\spyder\utils\qstringhelpers.py", line 19, in qstring_length
    utf16_text = text.encode('utf16')
UnicodeEncodeError: 'utf-16' codec can't encode character '\udd0d' in position 10: surrogates not allowed

```

**Comment by Parlazo** [comment]
this is in about text
```

* Spyder version: 5.3.3  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

```

**Comment by dalthviz** [comment]
Hi @Parlazo thank you for the feedback! I was able to copy paste the text provided but seems like the syntax hightlithting still works:

![imagen](https://user-images.githubusercontent.com/16781833/198082445-7dfd5c9f-c892-4d4b-9a65-e53fee4743ef.png)

Could you share with us an example file which causes this issue, please? Any further info in order to reproduce this is greatly appreciated!

**Comment by ccordoba12** [comment]
This seems to me more a problem with the font being used in the editor than with Spyder. Also, maybe @impact27 knows better what's happening here.

**Comment by dalthviz** [comment]
Closing due to lack of response
