### ISSUE TITLE
Spyder failed to launch

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1995]
_From [lyfjx...@gmail.com](https://code.google.com/u/100514145633851816459/) on 2014-10-04T09:32:27Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. Spyder worked well.
2. Spyder was terminated when computer power was suddenly off.
3. "D:\Program Files\Python27\pythonw.exe" "D:\Program Files\Python27\scripts\spyder" 

What is the expected output? What do you see instead?

 Spyder did not start.
"D:\Program Files\Python27\pythonw.exe" "D:\Program Files\Python27\scripts\spyder"
Traceback (most recent call last):
  File "D:\Program Files\Python27\scripts\spyder", line 3, in \<module>
    start_app.main()
  File "D:\Program Files\Python27\lib\site-packages\spyderlib\start_app.py", line 85, in main
    if not lock.lock():
  File "D:\Program Files\Python27\lib\site-packages\spyderlib\utils\external\lockfile.py", line 174, in lock
    kill(int(pid), 0)
UnicodeEncodeError: 'decimal' codec can't encode characters in position 0-3: invalid decimal Unicode string

"D:\Program Files\Python27\pythonw.exe" "D:\Program Files\Python27\scripts\spyder" --light
Traceback (most recent call last):
  File "D:\Program Files\Python27\scripts\spyder", line 3, in \<module>
    start_app.main()
  File "D:\Program Files\Python27\lib\site-packages\spyderlib\start_app.py", line 85, in main
    if not lock.lock():
  File "D:\Program Files\Python27\lib\site-packages\spyderlib\utils\external\lockfile.py", line 174, in lock
    kill(int(pid), 0)
UnicodeEncodeError: 'decimal' codec can't encode characters in position 0-3: invalid decimal Unicode string

"D:\Program Files\Python27\pythonw.exe" "D:\Program Files\Python27\scripts\spyder" --reset
Traceback (most recent call last):
  File "D:\Program Files\Python27\scripts\spyder", line 3, in \<module>
    start_app.main()
  File "D:\Program Files\Python27\lib\site-packages\spyderlib\start_app.py", line 85, in main
    if not lock.lock():
  File "D:\Program Files\Python27\lib\site-packages\spyderlib\utils\external\lockfile.py", line 174, in lock
    kill(int(pid), 0)
UnicodeEncodeError: 'decimal' codec can't encode characters in position 0-3: invalid decimal Unicode string What version of the product are you using? On what operating system? - spyder-2.3.1.win-amd64-py2.7.exe
- Win7 SP1 64-bit
- Python 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)] on win32
- >pip list
backports.ssl-match-hostname (3.4.0.2)
certifi (14.05.14)
docutils (0.12)
ipython (2.1.0)
jinja2 (2.7.3)
markupsafe (0.23)
matplotlib (1.4.0)
numpy (1.9.0)
Pillow (2.6.0)
pip (1.5.6)
Pygments (1.6)
pyparsing (2.0.2)
pyreadline (2.0)
python-dateutil (2.2)
pytz (2014.7)
pyzmq (14.3.1)
scipy (0.14.0)
setuptools (6.0.2)
six (1.8.0)
Sphinx (1.2.3)
spyder (2.3.1)
sympy (0.7.5)
tornado (4.0.2) 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1995_

**Comment by spyder-issues-migrator** [comment]
_From [lyfjx...@gmail.com](https://code.google.com/u/100514145633851816459/) on 2014-10-05T02:19:39Z_

Okay... I solved this issue

by removing the directory: %userprofile%\.spyder2\spyder.lock

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T15:23:00Z_

Glad to know.

**Status:** WontFix

**Comment by ccordoba12** [comment]
This is a duplicate of issue #2363
