### ISSUE TITLE
QT Gui integration with traitsui Spyder 5.2/5.3

### ISSUE THREAD

**Issue by chnce** [spyder-ide/spyder#19954]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I run a traitsui application from Spyder. The application allows for scripting from the console and uses the QT gui integration (%gui qt) to allow console access while the gui is running. Starting with Spyder 5.2 the tree_editor module from traitsui stopped working (traceback below).

### What steps reproduce the problem?

1. Download tree editor demo from: https://github.com/enthought/traitsui/blob/main/traitsui/examples/demo/Standard_Editors/TreeEditor_demo.py
2. change last line from `demo.configure_traits()` to `ui = demo.edit_traits()` in order to use the QT gui integration and allow console access while the gui is running.
3. Run the demo. Add a new employee from the gui.

<img width="474" alt="Screenshot 2022-10-31 at 07 57 00" src="https://user-images.githubusercontent.com/16875251/198952256-b8f3b3f9-e71b-4094-a0ef-d661b5f0f10d.png">

### What is the expected output? What do you see instead?
Expected output is an additional tree node with a new employee. Actual result is the error message below.

The same example is working in:
- Spyder 5.1.5
- qtconsole (with %gui qt)
- ipython console (with %gui qt)

Tested and reproduce in MacOS and Windows 10.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "/Users/.../mambaforge/envs/more/lib/python3.8/site-packages/pyface/ui/qt4/action/action_item.py", line 184, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/.../mambaforge/envs/more/lib/python3.8/site-packages/traitsui/qt4/tree_editor.py", line 1166, in perform
    self.ui.do_undoable(self._perform, action)
  File "/Users/.../mambaforge/envs/more/lib/python3.8/site-packages/traitsui/ui.py", line 645, in do_undoable
    action(*args, **kw)
  File "/Users/.../mambaforge/envs/more/lib/python3.8/site-packages/traitsui/qt4/tree_editor.py", line 1169, in _perform
    node, object, nid = self._data
TypeError: cannot unpack non-iterable NoneType object

```

## Versions

* Spyder version: 5.3.3
* Python version:  3.8.13
* Qt version: 5.15.6
* PyQt version: 5.15.7
* Operating System name/version: Darwin 22.1.0

### Dependencies

```
# Mandatory:
applaunchservices >=0.3.0     :  0.3.0 (OK)
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.1.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0       :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.13.0 (OK)
pylint >=2.5.0;<3.0           :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.2 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  63.4.1 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.4.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.22.3 (OK)
pandas >=1.1.1                :  1.4.3 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @chnce, thanks for reporting. We'll take a look at this in a future release.

**Comment by ccordoba12** [comment]
But in the meantime, could you check if commenting this piece of code in spyder-kernels solves the problem for you?

https://github.com/spyder-ide/spyder-kernels/blob/2.x/spyder_kernels/customize/spydercustomize.py#L152-L173

Let us know if it helps.

**Comment by chnce** [comment]
Thank you for getting back so quickly. I tested your suggestion. Unfortunately I don't see any change in the behaviour.

Let me know if I can help with testing something else.

**Comment by ccordoba12** [comment]
Sorry, that was my quick hunch. Other than that, I don't know what could be causing the problem.
