### ISSUE TITLE
Pathing Issues with VENVs

### ISSUE THREAD

**Issue by Chemist-pp** [spyder-ide/spyder#19964]
### What steps will reproduce the problem?

I wish I knew... what I can say is that I have a base conda environment.  Spyder 5.3.3 on it.  Then I install Python 10 into a virual env.  Then I add spyder-kernels to it.  And then some issues begin.  It's an odd issue.  So i set the interpertor in spyder ide to use venv and start.. VENV 1 (Raptor) -> Red Box Error: Cannot Start Kernel or something like that.  The system cannot find the path specified in the box.  If I restart kernel, nothing.  Then I hit 'x' on kernel and it will start Console 2/A and then I get a message that says "Cannot find the path specified" but just like a line under IPython -- An enanced Interactive Python.  But I can still like run it and stuff.  sys.prefix and sys.base_prefix report venv Raptor.  VENV-2 (CalStation) -> On start, just the white line that says cannot find the path specified.  On restarting the kernel this error pops up.  No idea what is going on right now.. figuring it out.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\i12500198\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 762, in _restart_thread_main
    self.shellwidget.kernel_manager.restart_kernel(
  File "C:\Users\i12500198\Anaconda3\lib\site-packages\jupyter_client\utils.py", line 30, in wrapped
    raise e
  File "C:\Users\i12500198\Anaconda3\lib\site-packages\jupyter_client\utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "C:\Users\i12500198\Anaconda3\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Users\i12500198\Anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\i12500198\Anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\i12500198\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 535, in _async_restart_kernel
    await ensure_async(self.shutdown_kernel(now=now, restart=True))
  File "C:\Users\i12500198\Anaconda3\lib\site-packages\jupyter_client\utils.py", line 30, in wrapped
    raise e
  File "C:\Users\i12500198\Anaconda3\lib\site-packages\jupyter_client\utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "C:\Users\i12500198\Anaconda3\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Users\i12500198\Anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\i12500198\Anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\i12500198\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 83, in wrapper
    raise e
  File "C:\Users\i12500198\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 75, in wrapper
    out = await method(self, *args, **kwargs)
  File "C:\Users\i12500198\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 494, in _async_shutdown_kernel
    await ensure_async(self.request_shutdown(restart=restart))
  File "C:\Users\i12500198\Anaconda3\lib\site-packages\jupyter_client\utils.py", line 30, in wrapped
    raise e
  File "C:\Users\i12500198\Anaconda3\lib\site-packages\jupyter_client\utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "C:\Users\i12500198\Anaconda3\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Users\i12500198\Anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\i12500198\Anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\i12500198\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 399, in _async_request_shutdown
    self._connect_control_socket()
  File "C:\Users\i12500198\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 318, in _connect_control_socket
    self._control_socket = self._create_connected_socket("control")
  File "C:\Users\i12500198\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 605, in _create_connected_socket
    sock = self.context.socket(socket_type)
  File "C:\Users\i12500198\Anaconda3\lib\site-packages\zmq\sugar\context.py", line 290, in socket
    raise ZMQError(Errno.ENOTSUP)
zmq.error.ZMQError: Not supported
```

## Versions

* Spyder version: 5.3.3  (conda)
* Python version: 3.9.13 64-bit
* Qt version: 5.15.4
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.0.0 (OK)
cloudpickle >=0.5.0           :  2.2.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.9.3 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  2.11.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.3 (OK)
pygments >=2.0                :  2.13.0 (OK)
pylint >=2.5.0;<3.0           :  2.15.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.2 (OK)
qtawesome >=1.0.2             :  1.2.1 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.1 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.5.0 (OK)
sphinx >=0.6.6                :  5.0.0 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
zmq >=22.1.0                  :  24.0.1 (OK)

# Optional:
cython >=0.21                 :  0.29.32 (OK)
matplotlib >=3.0.0            :  3.6.1 (OK)
numpy >=1.7                   :  1.21.6 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.9.3 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at C:\Users\i12500198\Anaconda3\envs\CalStation:
#
# Name                    Version                   Build  Channel
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.9.24            h5b45459_0    conda-forge
cloudpickle               2.2.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
debugpy                   1.6.3           py310h00ffb61_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
intel-openmp              2022.1.0          h57928b3_3787    conda-forge
ipykernel                 6.16.2             pyh025b116_0    conda-forge
ipython                   7.33.0          py310h5588dad_0    conda-forge
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jupyter_client            7.4.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1          py310h5588dad_1    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libsqlite                 3.39.4               hcfcfb64_0    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
numpy                     1.23.4          py310h4a8f9c9_1    conda-forge
openssl                   3.0.5                hcfcfb64_2    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       22.3               pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.31             pyha770c72_0    conda-forge
psutil                    5.9.3           py310h8d17308_1    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
python                    3.10.6          hcf16a7b_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pywin32                   303             py310h8d17308_1    conda-forge
pyzmq                     24.0.1          py310hcd737a0_1    conda-forge
scikit-learn              1.1.3           py310had3394f_0    conda-forge
scipy                     1.9.3           py310h578b7cb_1    conda-forge
setuptools                65.5.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
spyder-kernels            2.3.3           py310h5588dad_0    conda-forge
tbb                       2021.6.0             h91493d7_1    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tornado                   6.2             py310h8d17308_1    conda-forge
traitlets                 5.5.0              pyhd8ed1ab_0    conda-forge
tzdata                    2022e                h191b570_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
vc                        14.3                 h3d8a991_9    conda-forge
vs2015_runtime            14.32.31332          h1d6e394_9    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge

```
</details>

**Comment by Chemist-pp** [comment]
Removing venv, creating fresh env.  Starting spyder connected to that IDE went even worse lol.  Just looped a failed console start until I closed the console.  Which then on restart gave the expected error about not having spyder-kernels installed.  So it seems to be more related to the base env and spyder so I'm trying to repair there and see how it goes

**Comment by Chemist-pp** [comment]
I reinstalled Anaconda and there are some serious issues going on that I cannot really now say what is happening in an intellegent manner.  I can say I have some issue with _nsis.py module, hand to delete keys from windows after uninstalling, etc...  I'll follow up if I resolve issue.
