### ISSUE TITLE
RuntimeError: no running event loop and PermissionError: [WinError 10013]

### ISSUE THREAD

**Issue by Vinodhini12** [spyder-ide/spyder#19968]
The error is:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\utils.py", line 14, in wrapped
loop = asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1974, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle,
File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\utils.py", line 18, in wrapped
loop = asyncio.get_event_loop_policy().get_event_loop()
File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 639, in get_event_loop
self.set_event_loop(self.new_event_loop())
File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 659, in new_event_loop
return self._loop_factory()
File "C:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 315, in __init__
super().__init__(proactor)
File "C:\ProgramData\Anaconda3\lib\asyncio\proactor_events.py", line 630, in __init__
self._make_self_pipe()
File "C:\ProgramData\Anaconda3\lib\asyncio\proactor_events.py", line 761, in _make_self_pipe
self._ssock, self._csock = socket.socketpair()
File "C:\ProgramData\Anaconda3\lib\socket.py", line 631, in socketpair
lsock.bind((host, 0))
PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by dalthviz** [comment]
Hi @Vinodhini12 , could it be possible for you to share your setup (Python version, Spyder version, dependencies, etc)? Also, where you running something when this happened?

Without further information there is not much we can do besides suggesting you to check that you have the latest Spyder release installed and update if that is not the case. Let us know if you have more info.

**Comment by Vinodhini12** [comment]
python version=3.9
spyder=5.2.2

**Comment by Vinodhini12** [comment]
what other dependencies you need to know?

**Comment by Vinodhini12** [comment]
I'm using spyder through anaconda and also in anaconda prompt while i was trying to reset the spyder I got a error as "conda is not recognized as an external problem"

**Comment by Vinodhini12** [comment]
how can I fix this

**Comment by Vinodhini12** [comment]
kernel's problem is also still there?

**Comment by Vinodhini12** [comment]
also that i was starting the spyder for very first time in my system, I'm getting this issue.
i was just running hello program on it

**Comment by ccordoba12** [comment]
This looks like problem with your firewall or antivirus. So I'd recommend you to disable them and try again.

**Comment by Vinodhini12** [comment]
tried it ! still the same issue!

**Comment by ccordoba12** [comment]
Please restart your PC or laptop and try again. That could also help.

**Comment by Vinodhini12** [comment]
done yet the same!

**Comment by dalthviz** [comment]
Could you create a new conda environment and install the Spyder 5.3.3? For that you will need to open an Anaconda prompt and the run something like the following to create the new env, activate the new env and launch Spyder:

```
conda create -c spyder-env python=3.9 spyder=5.3.3
conda activate spyder-env
spyder
```

Let us know if installing newer version of Spyder helps!
