### ISSUE TITLE
broken install

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1997]
_From [w...@chem.ubc.ca](https://code.google.com/u/106036726426276625409/) on 2014-10-05T18:20:27Z_

Perhaps as a consequence of bash updating, my spyder is now broken.

Command line execution yields:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/spyderlib/spyder.py", line 2333, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python2.7/site-packages/spyderlib/spyder.py", line 2221, in run_spyder
    main.setup()
  File "/usr/lib/python2.7/site-packages/spyderlib/spyder.py", line 876, in setup
    from spyderlib.plugins.ipythonconsole import IPythonConsole
  File "/usr/lib/python2.7/site-packages/spyderlib/plugins/ipythonconsole.py", line 29, in \<module>
    from IPython.config.loader import Config, load_pyconfig_files
ImportError: cannot import name load_pyconfig_files

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1997_

**Comment by spyder-issues-migrator** [comment]
_From [w...@chem.ubc.ca](https://code.google.com/u/106036726426276625409/) on 2014-10-05T17:20:09Z_

I undid my update to spyder2.3 went back to spyder2.1 and it works again.

This is a problem with spyder 2.3 and/or the updates that it required.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T15:19:37Z_

You need to upload IPython too. We support IPytho versions higher than 0.13

**Status:** Invalid

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T16:51:48Z_

Sorry, I meant update instead of upload.
