### ISSUE TITLE
unknow error on stating spyder

### ISSUE THREAD

**Issue by brbamford** [spyder-ide/spyder#19988]
### What steps will reproduce the problem?

Starting spyder, gives this error everytime, new installation Window 10 VM  on parallels

### Traceback
```python-traceback
Error on reading from the event loop self pipe
loop: <ProactorEventLoop running=True closed=False debug=False>
Traceback (most recent call last):
  File "C:\Users\brbamford\anaconda3\lib\asyncio\windows_events.py", line 453, in finish_recv
    return ov.getresult()
OSError: [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\brbamford\anaconda3\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "C:\Users\brbamford\anaconda3\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\brbamford\anaconda3\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request
```

## Versions

* Spyder version: 5.3.3  (conda)
* Python version: 3.8.5 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  65.5.0 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at C:\Users\brbamford\anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0  
alabaster                 0.7.12             pyhd3eb1b0_0  
anaconda-client           1.11.0           py38haa95532_0  
anaconda-navigator        2.3.2            py38haa95532_0  
anyio                     3.5.0            py38haa95532_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py38h2bbff1b_0  
arrow                     1.2.3            py38haa95532_0  
astroid                   2.11.7           py38haa95532_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
atomicwrites              1.4.0                      py_0  
attrs                     21.4.0             pyhd3eb1b0_0  
autopep8                  1.6.0              pyhd3eb1b0_1  
babel                     2.9.1              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
backports                 1.1                pyhd3eb1b0_0  
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0  
backports.tempfile        1.0                pyhd3eb1b0_1  
backports.weakref         1.0.post1                  py_1  
bcrypt                    3.2.0            py38h2bbff1b_1  
beautifulsoup4            4.11.1           py38haa95532_0  
binaryornot               0.4.4              pyhd3eb1b0_1  
black                     22.6.0           py38haa95532_0  
bleach                    4.1.0              pyhd3eb1b0_0  
brotlipy                  0.7.0           py38h2bbff1b_1003  
bzip2                     1.0.8                he774522_0  
ca-certificates           2022.10.11           haa95532_0  
certifi                   2022.9.24        py38haa95532_0  
cffi                      1.15.1           py38h2bbff1b_0  
chardet                   4.0.0           py38haa95532_1003  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4            py38haa95532_0  
cloudpickle               2.0.0              pyhd3eb1b0_0  
clyent                    1.2.2                    py38_1  
colorama                  0.4.5            py38haa95532_0  
conda                     22.9.0           py38haa95532_0  
conda-build               3.22.0           py38haa95532_0  
conda-content-trust       0.1.3            py38haa95532_0  
conda-env                 2.6.0                         1  
conda-package-handling    1.9.0            py38h8cc25b3_1  
conda-repo-cli            1.0.24           py38haa95532_0  
conda-token               0.4.0              pyhd3eb1b0_0  
conda-verify              3.4.2                      py_1  
console_shortcut          0.1.1                         4  
cookiecutter              1.7.3              pyhd3eb1b0_0  
cryptography              38.0.1           py38h21b164f_0  
debugpy                   1.5.1            py38hd77b12b_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
diff-match-patch          20200713           pyhd3eb1b0_0  
dill                      0.3.4              pyhd3eb1b0_0  
docutils                  0.18.1           py38haa95532_3  
entrypoints               0.4              py38haa95532_0  
executing                 0.8.3              pyhd3eb1b0_0  
filelock                  3.6.0              pyhd3eb1b0_0  
flake8                    4.0.1              pyhd3eb1b0_1  
freetype                  2.12.1               ha860e81_0  
future                    0.18.2                   py38_1  
glib                      2.69.1               h5dc1a3c_1  
glob2                     0.7                pyhd3eb1b0_0  
gst-plugins-base          1.18.5               h9e645db_0  
gstreamer                 1.18.5               hd78058f_0  
icu                       58.2                 ha925a31_3  
idna                      3.4              py38haa95532_0  
imagesize                 1.4.1            py38haa95532_0  
importlib-metadata        4.11.3           py38haa95532_0  
importlib_metadata        4.11.3               hd3eb1b0_0  
importlib_resources       5.2.0              pyhd3eb1b0_1  
inflection                0.5.1            py38haa95532_0  
intervaltree              3.1.0              pyhd3eb1b0_0  
ipykernel                 6.15.2           py38haa95532_0  
ipython                   7.31.1           py38haa95532_1  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.5              pyhd3eb1b0_1  
isort                     5.9.3              pyhd3eb1b0_0  
jedi                      0.18.1           py38haa95532_1  
jellyfish                 0.9.0            py38h2bbff1b_0  
jinja2                    2.11.3             pyhd3eb1b0_0  
jinja2-time               0.2.0              pyhd3eb1b0_3  
jpeg                      9e                   h2bbff1b_0  
json5                     0.9.6              pyhd3eb1b0_0  
jsonschema                4.16.0           py38haa95532_0  
jupyter_client            7.3.5            py38haa95532_0  
jupyter_core              4.11.1           py38haa95532_0  
jupyter_server            1.18.1           py38haa95532_0  
jupyterlab                3.4.4            py38haa95532_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.10.3             pyhd3eb1b0_1  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
keyring                   23.4.0           py38haa95532_0  
lazy-object-proxy         1.6.0            py38h2bbff1b_0  
lerc                      3.0                  hd77b12b_0  
libarchive                3.6.1                hebabd0d_0  
libclang                  12.0.0          default_h627e005_2  
libdeflate                1.8                  h2bbff1b_5  
libffi                    3.4.2                hd77b12b_4  
libiconv                  1.16                 h2bbff1b_2  
liblief                   0.11.5               hd77b12b_1  
libogg                    1.3.5                h2bbff1b_1  
libpng                    1.6.37               h2a8f88b_0  
libsodium                 1.0.18               h62dcd97_0  
libspatialindex           1.9.3                h6c2663c_0  
libtiff                   4.4.0                h8a3f274_1  
libvorbis                 1.3.7                he774522_0  
libwebp                   1.2.4                h2bbff1b_0  
libwebp-base              1.2.4                h2bbff1b_0  
libxml2                   2.9.14               h0ad7f3c_0  
libxslt                   1.1.35               h2bbff1b_0  
lz4-c                     1.9.3                h2bbff1b_1  
m2-msys2-runtime          2.5.0.17080.65c939c               3  
m2-patch                  2.7.5                         2  
markupsafe                2.0.1            py38h2bbff1b_0  
matplotlib-inline         0.1.6            py38haa95532_0  
mccabe                    0.7.0              pyhd3eb1b0_0  
menuinst                  1.4.19           py38h59b6b97_0  
mistune                   0.8.4           py38he774522_1000  
msys2-conda-epoch         20160418                      1  
mypy_extensions           0.4.3            py38haa95532_1  
navigator-updater         0.2.1                    py38_0  
nbclassic                 0.3.5              pyhd3eb1b0_0  
nbclient                  0.5.13           py38haa95532_0  
nbconvert                 6.4.4            py38haa95532_0  
nbformat                  5.5.0            py38haa95532_0  
nest-asyncio              1.5.5            py38haa95532_0  
notebook                  6.4.12           py38haa95532_0  
numpydoc                  1.4.0            py38haa95532_0  
openssl                   1.1.1s               h2bbff1b_0  
packaging                 21.3               pyhd3eb1b0_0  
pandocfilters             1.5.0              pyhd3eb1b0_0  
paramiko                  2.8.1              pyhd3eb1b0_0  
parso                     0.8.3              pyhd3eb1b0_0  
pathlib                   1.0.1              pyhd3eb1b0_1  
pathspec                  0.9.0            py38haa95532_0  
pcre                      8.45                 hd77b12b_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.2.0            py38hdc2b20a_1  
pip                       22.2.2           py38haa95532_0  
pkginfo                   1.8.3            py38haa95532_0  
pkgutil-resolve-name      1.3.10           py38haa95532_0  
platformdirs              2.5.2            py38haa95532_0  
pluggy                    1.0.0            py38haa95532_1  
ply                       3.11                     py38_0  
powershell_shortcut       0.0.1                         3  
poyo                      0.5.0              pyhd3eb1b0_0  
prometheus_client         0.14.1           py38haa95532_0  
prompt-toolkit            3.0.20             pyhd3eb1b0_0  
psutil                    5.9.0            py38h2bbff1b_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
py-lief                   0.11.5           py38hd77b12b_1  
pycodestyle               2.8.0              pyhd3eb1b0_0  
pycosat                   0.6.4            py38h2bbff1b_0  
pycparser                 2.21               pyhd3eb1b0_0  
pydocstyle                6.1.1              pyhd3eb1b0_0  
pyflakes                  2.4.0              pyhd3eb1b0_0  
pygments                  2.11.2             pyhd3eb1b0_0  
pyjwt                     2.4.0            py38haa95532_0  
pylint                    2.14.5           py38haa95532_0  
pyls-spyder               0.4.0              pyhd3eb1b0_0  
pynacl                    1.5.0            py38h8cc25b3_0  
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pyparsing                 3.0.9            py38haa95532_0  
pyqt                      5.15.7           py38hd77b12b_0  
pyqt5-sip                 12.11.0          py38hd77b12b_0  
pyqtwebengine             5.15.7           py38hd77b12b_0  
pyrsistent                0.18.0           py38h196d8e1_0  
pysocks                   1.7.1            py38haa95532_0  
python                    3.8.5                h5fd99cc_1  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.16.2           py38haa95532_0  
python-libarchive-c       2.9                pyhd3eb1b0_1  
python-lsp-black          1.2.1            py38haa95532_0  
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0  
python-lsp-server         1.5.0            py38haa95532_0  
python-slugify            5.0.2              pyhd3eb1b0_0  
pytz                      2022.1           py38haa95532_0  
pywin32                   302              py38h2bbff1b_2  
pywin32-ctypes            0.2.0                 py38_1000  
pywinpty                  2.0.2            py38h5da7b33_0  
pyyaml                    6.0              py38h2bbff1b_1  
pyzmq                     23.2.0           py38hd77b12b_0  
qdarkstyle                3.0.2              pyhd3eb1b0_0  
qstylizer                 0.1.10             pyhd3eb1b0_0  
qt-main                   5.15.2               he8e5bd7_7  
qt-webengine              5.15.9               hb9a9bb5_4  
qtawesome                 1.0.3              pyhd3eb1b0_0  
qtconsole                 5.3.2            py38haa95532_0  
qtpy                      2.2.0            py38haa95532_0  
qtwebkit                  5.212                h3ad3cdb_4  
requests                  2.28.1           py38haa95532_0  
rope                      0.22.0             pyhd3eb1b0_0  
rtree                     0.9.7            py38h2eaa2aa_1  
ruamel_yaml               0.15.100         py38h2bbff1b_0  
send2trash                1.8.0              pyhd3eb1b0_1  
setuptools                65.5.0           py38haa95532_0  
sip                       6.6.2            py38hd77b12b_0  
six                       1.16.0             pyhd3eb1b0_1  
sniffio                   1.2.0            py38haa95532_1  
snowballstemmer           2.2.0              pyhd3eb1b0_0  
sortedcontainers          2.4.0              pyhd3eb1b0_0  
soupsieve                 2.3.2.post1      py38haa95532_0  
sphinx                    5.0.2            py38haa95532_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0  
spyder                    5.3.3            py38haa95532_0  
spyder-kernels            2.3.3            py38haa95532_0  
sqlite                    3.39.3               h2bbff1b_0  
stack_data                0.2.0              pyhd3eb1b0_0  
terminado                 0.13.1           py38haa95532_0  
testpath                  0.6.0            py38haa95532_0  
text-unidecode            1.3                pyhd3eb1b0_0  
textdistance              4.2.1              pyhd3eb1b0_0  
three-merge               0.1.1              pyhd3eb1b0_0  
tinycss                   0.4             pyhd3eb1b0_1002  
tk                        8.6.12               h2bbff1b_0  
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.1            py38haa95532_0  
tomlkit                   0.11.1           py38haa95532_0  
toolz                     0.12.0           py38haa95532_0  
tornado                   6.2              py38h2bbff1b_0  
tqdm                      4.64.1           py38haa95532_0  
traitlets                 5.1.1              pyhd3eb1b0_0  
typing-extensions         4.3.0            py38haa95532_0  
typing_extensions         4.3.0            py38haa95532_0  
ujson                     5.4.0            py38hd77b12b_0  
unidecode                 1.2.0              pyhd3eb1b0_0  
urllib3                   1.26.12          py38haa95532_0  
vc                        14.2                 h21ff451_1  
vs2015_runtime            14.27.29016          h5e58377_2  
watchdog                  2.1.6            py38haa95532_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1                    py38_1  
websocket-client          0.58.0           py38haa95532_4  
whatthepatch              1.0.2            py38haa95532_0  
wheel                     0.37.1             pyhd3eb1b0_0  
widgetsnbextension        3.5.2            py38haa95532_0  
win_inet_pton             1.1.0            py38haa95532_0  
wincertstore              0.2              py38haa95532_2  
winpty                    0.4.3                         4  
wrapt                     1.14.1           py38h2bbff1b_0  
xz                        5.2.6                h8cc25b3_0  
yaml                      0.2.5                he774522_0  
yapf                      0.31.0             pyhd3eb1b0_0  
zeromq                    4.3.4                hd77b12b_0  
zipp                      3.8.0            py38haa95532_0  
zlib                      1.2.13               h8cc25b3_0  
zstd                      1.5.2                h19a0ad4_0  

```
</details>

**Comment by ccordoba12** [comment]
Hey @brbamford, thanks for reporting. Please close Spyder, open the Anaconda Prompt and run there

    conda update python

then restart Spyder again. That should solve your problem, but let us know if it works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
