### ISSUE TITLE
unable to open terminal

### ISSUE THREAD

**Issue by DEsmondkele** [spyder-ide/spyder#19996]
### What steps will reproduce the problem?

Terminal and console refuse to open,
`sympy`: error downloading `sympy`

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 762, in _restart_thread_main
    self.shellwidget.kernel_manager.restart_kernel(
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\site-packages\jupyter_client\utils.py", line 30, in wrapped
    raise e
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\site-packages\jupyter_client\utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\asyncio\futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\site-packages\jupyter_client\manager.py", line 535, in _async_restart_kernel
    await ensure_async(self.shutdown_kernel(now=now, restart=True))
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\site-packages\jupyter_client\utils.py", line 30, in wrapped
    raise e
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\site-packages\jupyter_client\utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\asyncio\futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\site-packages\jupyter_client\manager.py", line 83, in wrapper
    raise e
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\site-packages\jupyter_client\manager.py", line 75, in wrapper
    out = await method(self, *args, **kwargs)
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\site-packages\jupyter_client\manager.py", line 494, in _async_shutdown_kernel
    await ensure_async(self.request_shutdown(restart=restart))
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\site-packages\jupyter_client\utils.py", line 30, in wrapped
    raise e
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\site-packages\jupyter_client\utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\asyncio\futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\site-packages\jupyter_client\manager.py", line 399, in _async_request_shutdown
    self._connect_control_socket()
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\site-packages\jupyter_client\manager.py", line 318, in _connect_control_socket
    self._control_socket = self._create_connected_socket("control")
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\site-packages\jupyter_client\connect.py", line 605, in _create_connected_socket
    sock = self.context.socket(socket_type)
  File "C:\Users\DELL\Anaconda\envs\chatting\lib\site-packages\zmq\sugar\context.py", line 258, in socket
    raise ZMQError(Errno.ENOTSUP)
zmq.error.ZMQError: Not supported
```

## Versions

* Spyder version: 5.3.3  (conda)
* Python version: 3.10.6 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  65.5.0 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @DEsmondkele, thanks for reporting. Please open the Anaconda Prompt, run the following commands here

    conda activate chatting
    conda list

and post the output of the last one here. That will help us to better understand your problem.

**Comment by ccordoba12** [comment]
I'm going to close this due to lack if response.
