### ISSUE TITLE
spyder python 2.7 won't launch

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2000]
_From [Pylesj...@gmail.com](https://code.google.com/u/113514557905797700414/) on 2014-10-08T09:13:20Z_

I have built a new python 2.7 environment from the Anaconda Launcher (Version 1.0.0 [node-webkit 0.10.1]; Conda Version: 3.7.1). I have installed the python-notebook, ipython-qtconsole and spyder-app. When I go to launch the spyder-app I get the following: 

"Spyder crashed during last session" 

It then goes on to tell me to try to reset defaults of Spyder by running 'python spyder --reset'. When I try to reset the settings to default I get 'python: can't open file 'spyder': [Errno 2] No such file or directory [1]+  Done                    spyder python2.7' 

I then tried to open spyder from my terminal and specifying python2.7 (my new environment name) by typing 'spyder python2.7'. This did open spyder, but with python 3.4, not 2.7. 

I did find a file named 'spyder_crash.log' with the following within it: 

Traceback (most recent call last):
  File "//anaconda/envs/Python2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 2346, in main
    mainwindow = run_spyder(app, options, args)
  File "//anaconda/envs/Python2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 2234, in run_spyder
    main.setup()
  File "//anaconda/envs/Python2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 791, in setup
    from spyderlib.plugins.inspector import ObjectInspector
  File "//anaconda/envs/Python2.7/lib/python2.7/site-packages/spyderlib/plugins/inspector.py", line 48, in \<module>
    from spyderlib.utils.inspector.sphinxify import (CSS_PATH, sphinxify,
  File "//anaconda/envs/Python2.7/lib/python2.7/site-packages/spyderlib/utils/inspector/sphinxify.py", line 28, in \<module>
    from docutils.utils import SystemMessage as SystemMessage
ImportError: No module named docutils.utils

In the end I just want to be able to start up Spyder and use python 2.7. I am using OSX 10.9.5.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2000_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T15:14:41Z_

Please run

conda install docutils

to fix this problem. It seems you installed sphinx but not docutils.

**Status:** Invalid
