### ISSUE TITLE
Problem when spyder starts

### ISSUE THREAD

**Issue by MariaLRendon** [spyder-ide/spyder#20008]
### What steps will reproduce the problem?

when starting spyder the problem is generated. The problem detection window appears

### Traceback
```python-traceback
  File "/usr/lib/python3/dist-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1511, in handle_hover_response
    self.show_hint(content, inspect_word=word,
  File "/usr/lib/python3/dist-packages/spyder/widgets/mixins.py", line 652, in show_hint
    self.show_tooltip(signature=html_signature, text=extra_text,
  File "/usr/lib/python3/dist-packages/spyder/widgets/mixins.py", line 631, in show_tooltip
    self.tooltip_widget.show_tip(point, tiptext, cursor=cursor,
  File "/usr/lib/python3/dist-packages/spyder/widgets/calltip.py", line 192, in show_tip
    point.setY(adjusted_point.y() - tip_height - padding)
TypeError: setY(self, int): argument 1 has unexpected type 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "/usr/bin/spyder", line 33, in <module>
    sys.exit(load_entry_point('spyder==4.2.1', 'gui_scripts', 'spyder')())
  File "/usr/lib/python3/dist-packages/spyder/app/start.py", line 213, in main
    mainwindow.main(options, args)
  File "/usr/lib/python3/dist-packages/spyder/app/mainwindow.py", line 3624, in main
    mainwindow = create_window(app, splash, options, args)
  File "/usr/lib/python3/dist-packages/spyder/app/mainwindow.py", line 3523, in create_window
    app.exec_()
  File "/usr/lib/python3/dist-packages/spyder/plugins/completion/languageserver/client.py", line 531, in on_msg_received
    handler(resp['result'], req_id)
  File "/usr/lib/python3/dist-packages/spyder/plugins/completion/languageserver/providers/document.py", line 167, in process_hover_result
    self.req_reply[req_id](
  File "/usr/lib/python3/dist-packages/spyder/plugins/completion/languageserver/plugin.py", line 560, in receive_response
    self.sig_response_ready.emit(
  File "/usr/lib/python3/dist-packages/spyder/plugins/completion/plugin.py", line 125, in receive_response
    self.howto_send_to_codeeditor(req_id)
  File "/usr/lib/python3/dist-packages/spyder/plugins/completion/plugin.py", line 183, in howto_send_to_codeeditor
    self.skip_and_send_to_codeeditor(req_id)
  File "/usr/lib/python3/dist-packages/spyder/plugins/completion/plugin.py", line 211, in skip_and_send_to_codeeditor
    self.gather_and_send_to_codeeditor(request_responses)
  File "/usr/lib/python3/dist-packages/spyder/plugins/completion/plugin.py", line 279, in gather_and_send_to_codeeditor
    response_instance.handle_response(req_type, responses)
  File "/usr/lib/python3/dist-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1095, in handle_response
    handler(params)
  File "/usr/lib/python3/dist-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1519, in handle_hover_response
    self.log_lsp_handle_errors("Error when processing hover")
  File "/usr/lib/python3/dist-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1126, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1511, in handle_hover_response
    self.show_hint(content, inspect_word=word,
  File "/usr/lib/python3/dist-packages/spyder/widgets/mixins.py", line 652, in show_hint
    self.show_tooltip(signature=html_signature, text=extra_text,
  File "/usr/lib/python3/dist-packages/spyder/widgets/mixins.py", line 631, in show_tooltip
    self.tooltip_widget.show_tip(point, tiptext, cursor=cursor,
  File "/usr/lib/python3/dist-packages/spyder/widgets/calltip.py", line 192, in show_tip
    point.setY(adjusted_point.y() - tip_height - padding)
TypeError: setY(self, int): argument 1 has unexpected type 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
ValueError: incomplete format
Call stack:
  File "/usr/bin/spyder", line 33, in <module>
    sys.exit(load_entry_point('spyder==4.2.1', 'gui_scripts', 'spyder')())
  File "/usr/lib/python3/dist-packages/spyder/app/start.py", line 213, in main
    mainwindow.main(options, args)
  File "/usr/lib/python3/dist-packages/spyder/app/mainwindow.py", line 3624, in main
    mainwindow = create_window(app, splash, options, args)
  File "/usr/lib/python3/dist-packages/spyder/app/mainwindow.py", line 3523, in create_window
    app.exec_()
  File "/usr/lib/python3/dist-packages/spyder/plugins/completion/languageserver/client.py", line 531, in on_msg_received
    handler(resp['result'], req_id)
  File "/usr/lib/python3/dist-packages/spyder/plugins/completion/languageserver/providers/document.py", line 167, in process_hover_result
    self.req_reply[req_id](
  File "/usr/lib/python3/dist-packages/spyder/plugins/completion/languageserver/plugin.py", line 560, in receive_response
    self.sig_response_ready.emit(
  File "/usr/lib/python3/dist-packages/spyder/plugins/completion/plugin.py", line 125, in receive_response
    self.howto_send_to_codeeditor(req_id)
  File "/usr/lib/python3/dist-packages/spyder/plugins/completion/plugin.py", line 183, in howto_send_to_codeeditor
    self.skip_and_send_to_codeeditor(req_id)
  File "/usr/lib/python3/dist-packages/spyder/plugins/completion/plugin.py", line 211, in skip_and_send_to_codeeditor
    self.gather_and_send_to_codeeditor(request_responses)
  File "/usr/lib/python3/dist-packages/spyder/plugins/completion/plugin.py", line 279, in gather_and_send_to_codeeditor
    response_instance.handle_response(req_type, responses)
  File "/usr/lib/python3/dist-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1095, in handle_response
    handler(params)
  File "/usr/lib/python3/dist-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1519, in handle_hover_response
    self.log_lsp_handle_errors("Error when processing hover")
  File "/usr/lib/python3/dist-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1126, in log_lsp_handle_errors
    logger.error('%', 1, stack_info=True)
Message: '%'
Arguments: (1,)
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest'}}
```

## Versions

* Spyder version: 4.2.1 
* Python version: 3.10.6
* Qt version: 5.15.3
* PyQt5 version: 5.15.6
* Operating System: Linux 5.19.11-051911-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  2.0.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=7.6.0                 :  7.31.1 (OK)
jedi >=0.17.2                   :  0.18.0 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  23.5.0 (OK)
nbconvert >=4.0                 :  6.4.0 (OK)
numpydoc >=0.6.0                :  1.2 (OK)
parso >=0.7.0                   :  0.8.1 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.9.0 (OK)
pygments >=2.0                  :  2.11.2 (OK)
pylint >=1.0                    :  2.12.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.4.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.1.1 (OK)
qtconsole >=5.0.1               :  5.2.2 (OK)
qtpy >=1.5.0                    :  2.0.0 (OK)
setuptools >=39.0.0             :  59.6.0 (OK)
sphinx >=0.6.6                  :  4.3.2 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.2 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  2.1.6 (OK)
xdg >=0.26                      :  0.27 (OK)
zmq >=17                        :  22.3.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.6.1 (OK)
numpy >=1.7                     :  1.21.5 (OK)
pandas >=1.1.1                  :  1.3.5 (OK)
scipy >=0.17.0                  :  1.8.0 (OK)
sympy >=0.7.3                   :  1.9 (OK)
```

**Comment by ccordoba12** [comment]
Closing due to lack of response.
