### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by madworm** [spyder-ide/spyder#20017]
Just trying to start spyder3 on opensuse Leap 15.4 leads to the following. Tried a fresh install as well. Same thing :-(

Information for package spyder3:
--------------------------------
Repository     : Main Repository
Name           : spyder3
Version        : 3.2.8-bp154.1.32
Arch           : noarch
Vendor         : openSUSE
Installed Size : 9.9 MiB
Installed      : Yes
Status         : up-to-date
Source package : spyder3-3.2.8-bp154.1.32.src
Upstream URL   : https://github.com/spyder-ide/spyder

```
      File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
      File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    'silent_exec_method')TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    'silent_exec_method')
TypeError
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
      File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    'silent_exec_method')TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
      File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    'silent_exec_method')
TypeError
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
      File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    'silent_exec_method')
TypeError
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
      File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    'silent_exec_method')
TypeError
Traceback (most recent call last):

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 218, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 350, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
```

**Comment by ccordoba12** [comment]
Hey @madworm, thanks for reporting. You're using a Spyder version that is terribly outdated and not supported anymore.

So, your only option is uninstall that version and install either Anaconda, which comes with Spyder, or install Spyder in a virtualenv with pip. Both methods are described in detail in our [documentation](http://docs.spyder-ide.org/current/installation.html).

**Comment by bnavigator** [comment]
https://bugzilla.opensuse.org/show_bug.cgi?id=1205199

A more recent spyder is not compatible with Python 3.6. The rpm package won't be updated.

Your only option for Leap is to use the python3.10 interpreter from the python310-base package and pip install spyder with it. Preferably in a venv:

    zypper in python310-base
    python3.10 -m venv spyderenv
    . spyderenv/bin/activate
    python -m pip install spyder

https://docs.spyder-ide.org/current/installation.html#using-pip
