### ISSUE TITLE
Le programme se lance pas

### ISSUE THREAD

**Issue by LeSaucssiondelaPop** [spyder-ide/spyder#20018]
### What steps will reproduce the problem?

Je lance Spyder
J'ouvre mon fichier
Je lance mon super programme
Et j'ai ensuite cette fenetre qui s'ouvre

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Program Files\WPy64-3940\python-3.9.4.amd64\lib\site-packages\spyder\plugins\editor\plugin.py", line 2795, in run_file
    self.re_run_file(save_new_files=False)
  File "C:\Program Files\WPy64-3940\python-3.9.4.amd64\lib\site-packages\spyder\plugins\editor\plugin.py", line 2819, in re_run_file
    all_saved = self.save_all(save_new_files=save_new_files)
  File "C:\Program Files\WPy64-3940\python-3.9.4.amd64\lib\site-packages\spyder\plugins\editor\plugin.py", line 2322, in save_all
    self.get_current_editorstack().save_all(save_new_files=save_new_files)
  File "C:\Program Files\WPy64-3940\python-3.9.4.amd64\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2074, in save_all
    all_saved &= self.save(index, save_new_files=save_new_files)
  File "C:\Program Files\WPy64-3940\python-3.9.4.amd64\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1863, in save
    self._save_file(finfo, index)
  File "C:\Program Files\WPy64-3940\python-3.9.4.amd64\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1881, in _save_file
    self.autosave.remove_autosave_file(finfo.filename)
  File "C:\Program Files\WPy64-3940\python-3.9.4.amd64\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 318, in remove_autosave_file
    del self.file_hashes[autosave_filename]
KeyError: 'C:\\Users\\LUYDLIT\\.spyder-py3\\autosave\\TP1InfoMrNaudy.py'
```

## Versions

* Spyder version: 5.0.1 
* Python version: 3.9.4
* Qt version: 5.15.1
* PyQt5 version: 5.15.1
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.10.0.dev0 (OK)
setuptools >=39.0.0           :  56.0.0 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.20.2 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @LeSaucssiondelaPop, merci de le signaler. Ce problème est corrigé dans notre dernière version. Veuillez mettre à jour en téléchargeant une version plus récente de WinPython.

(Ce message a été auto-traduit de l'anglais au français)
