### ISSUE TITLE
python_type error

### ISSUE THREAD

**Issue by MaViolet** [spyder-ide/spyder#20038]
### What steps will reproduce the problem?

import pickle
with open('filename.pickle', 'rb') as data:
	name = pickle.load(data)

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/widgets/collectionseditor.py", line 435, in data
    return to_qvariant(self.get_bgcolor(index))
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/widgets/collectionseditor.py", line 522, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/widgets/collectionseditor.py", line 435, in data
    return to_qvariant(self.get_bgcolor(index))
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/widgets/collectionseditor.py", line 522, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/widgets/collectionseditor.py", line 435, in data
    return to_qvariant(self.get_bgcolor(index))
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/widgets/collectionseditor.py", line 522, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/widgets/collectionseditor.py", line 435, in data
    return to_qvariant(self.get_bgcolor(index))
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/widgets/collectionseditor.py", line 522, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/widgets/collectionseditor.py", line 435, in data
    return to_qvariant(self.get_bgcolor(index))
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/widgets/collectionseditor.py", line 522, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
Traceback (most recent call last):
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/widgets/collectionseditor.py", line 435, in data
    return to_qvariant(self.get_bgcolor(index))
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/widgets/collectionseditor.py", line 522, in get_bgcolor
    python_type = value['python_type']
KeyError: 'python_type'
```

## Versions

* Spyder version: 5.4.0 510c6249c (standalone)
* Python version: 3.9.14 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Darwin 20.6.0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.0.0 (OK)
cloudpickle >=0.5.0                  :  2.2.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0              :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.17.0 (OK)
keyring >=17.0.0                     :  23.9.3 (OK)
nbconvert >=4.0                      :  7.2.3 (OK)
numpydoc >=0.6.0                     :  1.5.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.3 (OK)
pygments >=2.0                       :  2.13.0 (OK)
pylint >=2.5.0;<3.0                  :  2.15.5 (OK)
pylint_venv >=2.1.1                  :  None (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.6.0;<1.7.0                 :  1.6.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.2.2                    :  0.2.2 (OK)
qtawesome >=1.2.1                    :  1.2.1 (OK)
qtconsole >=5.4.0;<5.5.0             :  5.4.0 (OK)
qtpy >=2.1.0                         :  2.2.1 (OK)
rtree >=0.9.7                        :  1.0.1 (OK)
setuptools >=49.6.0                  :  65.5.1 (OK)
sphinx >=0.6.6                       :  5.1.1 (OK)
spyder_kernels >=2.4.0;<2.5.0        :  2.4.0 (OK)
textdistance >=4.2.0                 :  4.5.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.9 (OK)
zmq >=22.1.0                         :  24.0.1 (OK)

# Optional:
cython >=0.21                        :  0.29.32 (OK)
matplotlib >=3.0.0                   :  3.6.2 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.5.1 (OK)
scipy >=0.17.0                       :  1.9.3 (OK)
sympy >=0.7.3                        :  1.11.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

### Environment

<details><summary>Environment</summary>

```

```
</details>

**Comment by ccordoba12** [comment]
Hey @MaViolet, thanks for reporting. Could you upload the `filename.pickle` file you're trying to load? Or a simple version of it that also generates this error? That will help us to reproduce this error on our side so we can better understand what's happening.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
