### ISSUE TITLE
Typing In IPython Console Results In Error Popup

### ISSUE THREAD

**Issue by rafaelcoldatoms** [spyder-ide/spyder#20057]
### What steps will reproduce the problem?

Typed some basic commands in the IPython Console, and the "internal error" popup kept coming up.
I don't know why it happens, but I think it's related to parentethes ().
Spyder from Fedora RPM, with python 3.10, using wayland on Fedora 36.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.10/site-packages/spyder/plugins/ipythonconsole/widgets/help.py", line 170, in _handle_inspect_reply
    self._control.show_calltip(
  File "/usr/lib/python3.10/site-packages/spyder/widgets/mixins.py", line 603, in show_calltip
    self.calltip_widget.show_tip(point, text, [])
  File "/usr/lib/python3.10/site-packages/spyder/widgets/calltip.py", line 506, in show_tip
    point.setY(adjusted_point.y() - tip_height - padding)
TypeError: setY(self, int): argument 1 has unexpected type 'float'
```

## Versions

* Spyder version: 5.2.1 
* Python version: 3.10.8
* Qt version: 5.15.6
* PyQt5 version: 5.15.6
* Operating System: Linux 6.0.5-200.fc36.x86_64

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.3.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.8.3 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.9.3 (OK)
nbconvert >=4.0               :  6.4.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.13.7 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  59.6.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.2.0;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.32 (OK)
matplotlib >=2.0.0            :  3.6.1 (OK)
numpy >=1.7                   :  1.23.4 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.9.3 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @rafaelcoldatoms, thanks for reporting. This was fixed months ago, so please update to a more recent version (our latest one is 5.4.0).

If that's possible for you in Fedora, we recommend you to install either Anaconda or Spyder in a virtualenv, as described in [our documentation](http://docs.spyder-ide.org/current/installation.html).
