### ISSUE TITLE
RuntimeError when closing file in the editor

### ISSUE THREAD

**Issue by masum1490** [spyder-ide/spyder#20071]
### What steps will reproduce the problem?

This is Clock  for pc This is Clock  for pc This is Clock  for pc This is Clock  for pc 

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\plugin.py", line 1672, in file_renamed_in_data_in_editorstack
    editorstack.rename_in_data(original_filename, filename)
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\editor.py", line 1343, in rename_in_data
    finfo.editor.notify_close()
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\completion\decorators.py", line 20, in wrapper
    params = req(self, *args, **kwargs)
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\widgets\codeeditor.py", line 2031, in notify_close
    self._server_requests_timer.stop()
RuntimeError: wrapped C/C++ object of type QTimer has been deleted
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\utils\autosave.py", line 134, in do_autosave
    stack = self.editor.get_current_editorstack()
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\plugin.py", line 1745, in get_current_editorstack
    editorstack = self.__get_focused_editorstack()
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\editor\plugin.py", line 1431, in __get_focused_editorstack
    if editorstack.isAncestorOf(fwidget):
RuntimeError: wrapped C/C++ object of type EditorStack has been deleted
```

## Versions

* Spyder version: 5.4.0  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.0.0 (OK)
cloudpickle >=0.5.0                  :  2.2.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<8.0.0              :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.17.0 (OK)
keyring >=17.0.0                     :  23.9.3 (OK)
nbconvert >=4.0                      :  7.2.3 (OK)
numpydoc >=0.6.0                     :  1.5.0 (OK)
paramiko >=2.4.0                     :  2.11.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.3 (OK)
pygments >=2.0                       :  2.13.0 (OK)
pylint >=2.5.0;<3.0                  :  2.15.5 (OK)
pylint_venv >=2.1.1                  :  2.3.0 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.6.0;<1.7.0                 :  1.6.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.2.2                    :  0.2.2 (OK)
qtawesome >=1.2.1                    :  1.2.1 (OK)
qtconsole >=5.4.0;<5.5.0             :  5.4.0 (OK)
qtpy >=2.1.0                         :  2.2.1 (OK)
rtree >=0.9.7                        :  1.0.1 (OK)
setuptools >=49.6.0                  :  65.5.1 (OK)
sphinx >=0.6.6                       :  5.3.0 (OK)
spyder_kernels >=2.4.0;<2.5.0        :  2.4.0 (OK)
textdistance >=4.2.0                 :  4.5.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.1.9 (OK)
zmq >=22.1.0                         :  24.0.1 (OK)

# Optional:
cython >=0.21                        :  0.29.32 (OK)
matplotlib >=3.0.0                   :  3.6.2 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.5.1 (OK)
scipy >=0.17.0                       :  1.9.3 (OK)
sympy >=0.7.3                        :  1.11.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @masum1490, thanks for reporting. This is actually a real bug (even if you're unable to reproduce it anymore), so I'm going to reopen it.

We'll fix it in our next version (5.4.1), to be released before the end of the year.
