### ISSUE TITLE
 ModuleNotFoundError: No module named 'ipykernel'

### ISSUE THREAD

**Issue by QUANTA2004** [spyder-ide/spyder#20088]
### What steps will reproduce the problem?

raceback (most recent call last):
File "C:\Users\oggya\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\oggya\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
exec(code, run_globals)
File "C:\Users\oggya\AppData\Local\Programs\Python\Python310\lib\site‑packages\spyder_kernels\console\__main__.py", line 22, in
from spyder_kernels.console import start
File "C:\Users\oggya\AppData\Local\Programs\Python\Python310\lib\site‑packages\spyder_kernels\console\start.py", line 21, in
import ipykernel
ModuleNotFoundError: No module named 'ipykernel'

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\oggya\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 85, in wrapper
    self._ready.set_result(None)
asyncio.exceptions.InvalidStateError: invalid state

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\oggya\AppData\Local\Programs\Spyder\pkgs\qtconsole\manager.py", line 27, in poll
    super().poll()
  File "C:\Users\oggya\AppData\Local\Programs\Spyder\pkgs\jupyter_client\restarter.py", line 143, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "C:\Users\oggya\AppData\Local\Programs\Spyder\pkgs\jupyter_client\utils.py", line 30, in wrapped
    raise e
  File "C:\Users\oggya\AppData\Local\Programs\Spyder\pkgs\jupyter_client\utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "C:\Users\oggya\AppData\Local\Programs\Spyder\pkgs\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "asyncio\futures.py", line 178, in result
  File "asyncio\tasks.py", line 280, in __step
  File "C:\Users\oggya\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 547, in _async_restart_kernel
    await ensure_async(self.start_kernel(**self._launch_args))
  File "C:\Users\oggya\AppData\Local\Programs\Spyder\pkgs\jupyter_client\utils.py", line 30, in wrapped
    raise e
  File "C:\Users\oggya\AppData\Local\Programs\Spyder\pkgs\jupyter_client\utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "C:\Users\oggya\AppData\Local\Programs\Spyder\pkgs\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "asyncio\futures.py", line 178, in result
  File "asyncio\tasks.py", line 280, in __step
  File "C:\Users\oggya\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 88, in wrapper
    self._ready.set_exception(e)
asyncio.exceptions.InvalidStateError: invalid state
```

## Versions

* Spyder version: 5.4.0  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.0.0 (OK)
cloudpickle >=0.5.0                  :  2.2.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<8.0.0              :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.17.0 (OK)
keyring >=17.0.0                     :  23.9.3 (OK)
nbconvert >=4.0                      :  7.2.3 (OK)
numpydoc >=0.6.0                     :  1.5.0 (OK)
paramiko >=2.4.0                     :  2.11.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.3 (OK)
pygments >=2.0                       :  2.13.0 (OK)
pylint >=2.5.0;<3.0                  :  2.15.5 (OK)
pylint_venv >=2.1.1                  :  2.3.0 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.6.0;<1.7.0                 :  1.6.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.2.2                    :  0.2.2 (OK)
qtawesome >=1.2.1                    :  1.2.1 (OK)
qtconsole >=5.4.0;<5.5.0             :  5.4.0 (OK)
qtpy >=2.1.0                         :  2.2.1 (OK)
rtree >=0.9.7                        :  1.0.1 (OK)
setuptools >=49.6.0                  :  65.5.1 (OK)
sphinx >=0.6.6                       :  5.3.0 (OK)
spyder_kernels >=2.4.0;<2.5.0        :  2.4.0 (OK)
textdistance >=4.2.0                 :  4.5.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.1.9 (OK)
zmq >=22.1.0                         :  24.0.1 (OK)

# Optional:
cython >=0.21                        :  0.29.32 (OK)
matplotlib >=3.0.0                   :  3.6.2 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.5.1 (OK)
scipy >=0.17.0                       :  1.9.3 (OK)
sympy >=0.7.3                        :  1.11.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

### Environment

<details><summary>Environment</summary>

```
Package                       Version
----------------------------- -----------
alabaster                     0.7.12
arrow                         1.2.3
astroid                       2.12.12
attrs                         22.1.0
autopep8                      1.6.0
Babel                         2.11.0
backcall                      0.2.0
beautifulsoup4                4.11.1
binaryornot                   0.4.4
black                         22.10.0
bleach                        5.0.1
certifi                       2022.9.24
cffi                          1.15.1
chardet                       5.0.0
charset-normalizer            2.1.1
click                         8.1.3
cloudpickle                   2.2.0
colorama                      0.4.6
coloredlogs                   15.0.1
contourpy                     1.0.6
cookiecutter                  2.1.1
cryptography                  38.0.3
cycler                        0.11.0
Cython                        0.29.32
debugpy                       1.6.3
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20200713
dill                          0.3.6
docstring-to-markdown         0.10
docutils                      0.19
entrypoints                   0.4
et-xmlfile                    1.1.0
fastjsonschema                2.16.2
feedparser                    6.0.10
flake8                        5.0.4
fonttools                     4.38.0
fortls                        2.13.0
googlesearch-python           1.1.0
gTTS                          2.2.4
humanfriendly                 10.0
idna                          3.4
imagesize                     1.4.1
importlib-metadata            5.0.0
importlib-resources           5.10.0
inflection                    0.5.1
ipykernel                     6.17.0
ipython                       7.34.0
ipython-genutils              0.2.0
isort                         5.10.1
itsdangerous                  2.1.2
jaraco.classes                3.2.3
jaraco.context                4.1.1
jedi                          0.18.1
jellyfish                     0.9.0
Jinja2                        3.1.2
jinja2-time                   0.2.0
joblib                        1.1.0
json5                         0.9.10
jsonschema                    4.17.0
jupyter_client                7.4.4
jupyter_core                  4.11.2
jupyterlab-pygments           0.2.2
keyring                       23.9.3
kiwisolver                    1.4.4
lazy-object-proxy             1.8.0
lxml                          4.9.0
MarkupSafe                    2.1.1
matplotlib                    3.6.2
matplotlib-inline             0.1.6
mccabe                        0.7.0
mistune                       2.0.4
modules                       1.0.0
more-itertools                9.0.0
MouseInfo                     0.1.3
mpmath                        1.2.1
multitasking                  0.0.10
mypy-extensions               0.4.3
nbclient                      0.7.0
nbconvert                     7.2.3
nbformat                      5.7.0
nest-asyncio                  1.5.6
numpy                         1.22.4
numpydoc                      1.5.0
opencv-contrib-python         4.6.0.66
opencv-python                 4.6.0.66
openpyxl                      3.0.10
packages                      0.1.0
packaging                     21.3
pandas                        1.5.1
pandocfilters                 1.5.0
paramiko                      2.11.0
parso                         0.8.3
pathspec                      0.10.1
pefile                        2022.5.30
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.3.0
pip                           22.1.2
pkgutil_resolve_name          1.3.10
platformdirs                  2.5.2
playsound                     1.3.0
pluggy                        1.0.0
prompt-toolkit                3.0.32
psutil                        5.9.3
ptyprocess                    0.7.0
pure-eval                     0.2.2
PyAudio                       0.2.11
PyAutoGUI                     0.9.53
pycodestyle                   2.9.1
pycparser                     2.21
pydocstyle                    6.1.1
pyflakes                      2.5.0
pygame                        2.1.2
PyGetWindow                   0.0.9
Pygments                      2.13.0
pyinstaller                   5.1
pyinstaller-hooks-contrib     2022.7
pyjokes                       0.6.0
pylint                        2.15.5
pylint-venv                   2.3.0
pyls-spyder                   0.4.0
PyMsgBox                      1.0.9
PyNaCl                        1.5.0
pyparsing                     3.0.9
pyperclip                     1.8.2
pypiwin32                     223
PyQt5                         5.15.7
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.11.0
PyQtWebEngine                 5.15.6
PyQtWebEngine-Qt5             5.15.2
pyreadline3                   3.4.1
PyRect                        0.2.0
pyrsistent                    0.19.2
PyScreeze                     0.1.28
python-dateutil               2.8.2
python-decouple               3.6
python-lsp-black              1.2.1
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.6.0
pytoolconfig                  1.2.2
pyttsx3                       2.90
pytweening                    1.0.4
pytz                          2022.6
pywhatkit                     5.3
pywin32                       304
pywin32-ctypes                0.2.0
pywinpty                      2.0.9
pyxdg                         0.28
PyYAML                        6.0
pyzmq                         24.0.1
QDarkStyle                    3.0.3
qstylizer                     0.2.2
QtAwesome                     1.2.1
qtconsole                     5.4.0
QtPy                          2.2.1
ratelimit                     2.2.1
requests                      2.28.1
rope                          1.4.0
scikit-learn                  1.1.2
scipy                         1.9.3
setuptools                    65.5.1
sgmllib3k                     1.0.0
six                           1.16.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.3.2.post1
SpeechRecognition             3.8.1
Sphinx                        5.3.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.4.0
spyder-kernels                2.4.0
spyder-terminal               1.2.2
stack-data                    0.3.0
sympy                         1.11.1
terminado                     0.17.0
text-unidecode                1.3
textdistance                  4.5.0
threadpoolctl                 3.1.0
three-merge                   0.1.1
tinycss2                      1.2.1
toml                          0.10.2
tomli                         2.0.1
tomlkit                       0.11.6
torch                         1.12.0
torchaudio                    0.12.0
torchvision                   0.13.0
tornado                       6.2
traitlets                     5.5.0
turtles                       1.0.0
typing_extensions             4.4.0
ujson                         5.5.0
urllib3                       1.26.12
watchdog                      2.1.9
wcwidth                       0.2.5
webencodings                  0.5.1
Werkzeug                      2.1.2
whatthepatch                  1.0.2
wheel                         0.38.1
wikipedia                     1.4.0
winshell                      0.6
wolframalpha                  5.0.0
wrapt                         1.14.1
xmltodict                     0.13.0
yapf                          0.32.0
yfinance                      0.1.70
zipp                          3.10.0

[notice] A new release of pip available: 22.1.2 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

```
</details>

**Comment by ccordoba12** [comment]
Hey @QUANTA2004, thanks for reporting. I have a question for you to better understand your problem:

Are you trying to connect Spyder to a Python 3.10 environment in your computer, which you installed separately?
