### ISSUE TITLE
IPython Kernal Fail to Start

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2009]
_From [jesse.en...@gmail.com](https://code.google.com/u/103620588905886731599/) on 2014-10-15T17:06:55Z_

Spyder Version:  2.3.1
Python Version:  2.7.8
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Darwin
pyflakes >=0.5.0:  0.7.3 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  2.3.0 (OK)
pygments >=1.6  :  1.6 (OK)
pandas >=0.13.1 :  0.12.0 (NOK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  1.1.2 (OK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.3 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1. On startup and when restarting an IPython Kernel, I am unable to do so. 

What is the expected output? What do you see instead?

 Should just see the standard IPython Prompt, instead I get,

An error ocurred while starting the kernel
Traceback (most recent call last):
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/spyderlib/widgets/externalshell/start_ipython_kernel.py", line 183, in 
from IPython.zmq.ipkernel import IPKernelApp # 0.13 (analysis:ignore)
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/IPython/__init__.py", line 45, in 
from .config.loader import Config
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/IPython/config/__init__.py", line 16, in 
from .application import *
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/IPython/config/application.py", line 23, in 
import logging
File "/Users/jengel/anaconda/lib/python2.7/logging/__init__.py", line 26, in 
import sys, os, time, cStringIO, traceback, warnings, weakref, collections
File "collections.py", line 13, in 
import numpy as np
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/numpy/__init__.py", line 142, in 
import add_newdocs
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/numpy/add_newdocs.py", line 9, in 
from numpy.lib import add_newdoc
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/numpy/lib/__init__.py", line 4, in 
from type_check import *
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/numpy/lib/type_check.py", line 8, in 
import numpy.core.numeric as _nx
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/numpy/core/__init__.py", line 45, in 
from numpy.testing import Tester
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/numpy/testing/__init__.py", line 8, in 
from unittest import TestCase
File "/Users/jengel/anaconda/lib/python2.7/unittest/__init__.py", line 58, in 
from .result import TestResult
File "/Users/jengel/anaconda/lib/python2.7/unittest/result.py", line 9, in 
from . import util
File "/Users/jengel/anaconda/lib/python2.7/unittest/util.py", line 2, in 
from collections import namedtuple, OrderedDict
ImportError: cannot import name namedtuple 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2009_

**Comment by spyder-issues-migrator** [comment]
_From [jesse.en...@gmail.com](https://code.google.com/u/103620588905886731599/) on 2014-10-15T22:08:49Z_

It's worth noting that when I just load up an IPython session and do:

from collections import namedtuple

I don't get an error

**Comment by spyder-issues-migrator** [comment]
_From [jesse.en...@gmail.com](https://code.google.com/u/103620588905886731599/) on 2014-10-15T22:21:51Z_

Update: I've upgrade to numpy 1.9 using conda (anaconda)

numpy                     1.9.0                   py27_p0  [mkl]

and now I get this error on startup, still with numpy:

An error ocurred while starting the kernel
Traceback (most recent call last):
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/spyderlib/widgets/externalshell/start_ipython_kernel.py", line 183, in 
from IPython.zmq.ipkernel import IPKernelApp # 0.13 (analysis:ignore)
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/IPython/__init__.py", line 45, in 
from .config.loader import Config
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/IPython/config/__init__.py", line 16, in 
from .application import *
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/IPython/config/application.py", line 23, in 
import logging
File "/Users/jengel/anaconda/lib/python2.7/logging/__init__.py", line 26, in 
import sys, os, time, cStringIO, traceback, warnings, weakref, collections
File "collections.py", line 13, in 
import numpy as np
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/numpy/__init__.py", line 172, in 
from . import add_newdocs
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/numpy/add_newdocs.py", line 13, in 
from numpy.lib import add_newdoc
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/numpy/lib/__init__.py", line 8, in 
from .type_check import *
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/numpy/lib/type_check.py", line 11, in 
import numpy.core.numeric as _nx
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/numpy/core/__init__.py", line 6, in 
from . import multiarray
ImportError: cannot import name multiarray

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-16T16:20:22Z_

I think this errors arises (in both cases) because you have a file called "collections.py" in your folder or current working directory. I say it because of this line

    File "collections.py", line 13, in

in your tracebacks.

This makes the logging module to import the wrong module, as can be seen from one line above the previous one:

    File "/Users/jengel/anaconda/lib/python2.7/logging/__init__.py", line 26, in 
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections


The problem should be solved by renaming "collections.py" to another thing.

**Comment by spyder-issues-migrator** [comment]
_From [jesse.en...@gmail.com](https://code.google.com/u/103620588905886731599/) on 2014-10-16T19:41:22Z_

Thanks for the hint. I've followed up on it, and this is what I've found. The error seems to come from loading numpy in line 17 of 'collections.py'

ERROR TRACE:
File "/Users/jengel/anaconda/lib/python2.7/logging/__init__.py", line 26, in 
import sys, os, time, cStringIO, traceback, warnings, weakref, collections
File "collections.py", line 17, in 
import numpy as np
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/numpy/__init__.py", line 172, in 
from . import add_newdocs
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/numpy/add_newdocs.py", line 13, in 
from numpy.lib import add_newdoc
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/numpy/lib/__init__.py", line 8, in 
from .type_check import *
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/numpy/lib/type_check.py", line 11, in 
import numpy.core.numeric as _nx
File "/Users/jengel/anaconda/lib/python2.7/site‑packages/numpy/core/__init__.py", line 6, in 
from . import multiarray
ImportError: cannot import name multiarray



There are several collections.py files in my site-packages folder: 
[~/anaconda/lib/python2.7]$ find . -name collections.py
./collections.py
./site-packages/astropy/utils/collections.py
./site-packages/binstar_client/mixins/collections.py
./site-packages/matplotlib/collections.py
./site-packages/sqlalchemy/orm/collections.py
./site-packages/statsmodels/compatnp/collections.py


I think 'logging.py' imported by Ipython.confg.application means to load the base 'collections.py' from the site-packages folder.

Instead it seems to be loading the matplotlib version of collections.py which has
import numpy as np 
on line 17.


I've tried uninstalling and reinstalling spyder, numpy, and matplotlib, all to no avail. Same error message. There are no other 'collections.py' files in my PYTHONPATH.

Given that collections.py is a part of matplotlib, I can't just go renaming it.

Any thoughts?

**Comment by spyder-issues-migrator** [comment]
_From [jesse.en...@gmail.com](https://code.google.com/u/103620588905886731599/) on 2014-10-16T19:46:07Z_

I also tried reinstalling ipython to no avail.

The problem seems to be something about the ipython startup procedure through spyder (embedded app) which is different that a normal qtconsole. I can run qtconsole fine, and can even connect the spyder ipython console to a running ipython kernel fine. I just can't start a new ipython console from within spyder.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T15:07:00Z_

But those are the collections files you have under /anaconda/lib/python2.7. However, I think the problem is you have another collections named file somewhere else in your hard drive that somehow is picked up instead of the standard library one.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
