### ISSUE TITLE
Missing dependecies not declared!

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2011]
_From [alabdelo...@gmail.com](https://code.google.com/u/114214539224837625032/) on 2014-10-17T15:18:59Z_

Spyder dident declare two important dependecies (docutils.utils, jinja2), and by so, Spyder dident launch (spyder 2.3.1, windows 7 64)!

untill checking the bug report (appended one):

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 2346, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 2234, in run_spyder
    main.setup()
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 791, in setup
    from spyderlib.plugins.inspector import ObjectInspector
  File "C:\Python27\lib\site-packages\spyderlib\plugins\inspector.py", line 48, in \<module>
    from spyderlib.utils.inspector.sphinxify import (CSS_PATH, sphinxify,
  File "C:\Python27\lib\site-packages\spyderlib\utils\inspector\sphinxify.py", line 28, in \<module>
    from docutils.utils import SystemMessage as SystemMessage
ImportError: No module named docutils.utils

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 2346, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 2234, in run_spyder
    main.setup()
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 791, in setup
    from spyderlib.plugins.inspector import ObjectInspector
  File "C:\Python27\lib\site-packages\spyderlib\plugins\inspector.py", line 48, in \<module>
    from spyderlib.utils.inspector.sphinxify import (CSS_PATH, sphinxify,
  File "C:\Python27\lib\site-packages\spyderlib\utils\inspector\sphinxify.py", line 29, in \<module>
    from jinja2 import Environment, FileSystemLoader
ImportError: No module named jinja2

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2011_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-17T16:42:17Z_

It seems you installed Sphinx without its dependencies. I mean, docutils and jinja2 are Sphinx dependencies, so we don't declare them as Spyder dependencies because we only look for Sphinx as a dep. If we don't find Sphinx, we deactivate the features related to it, and hence we don't import docutils and jinja2.

I don't know how did that happen to you but I guess you didn't follow our installation instructions: http://pythonhosted.org/spyder/installation.html Anyway, thanks for your interest in improving Spyder :-)

**Status:** WontFix

**Comment by spyder-issues-migrator** [comment]
_From [alabdelo...@gmail.com](https://code.google.com/u/114214539224837625032/) on 2014-10-17T20:36:18Z_

hi, thanks for the reply

i formatted the machine, and installed spyder just after python, and then followed the dependecies list from the help menu, so it seems this is why.

NB: i dont have Sphinx installed yet, and it is not declared in the help list:

IPython >=0.13  :  2.3.0 (OK)
matplotlib >=1.0:  1.4.0 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
pyflakes >=0.5.0:  0.8.1 (OK)
pygments >=1.6  :  1.6 (OK)
pylint >=0.25   :  1.3.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
sympy >=0.7.0   :  0.7.5 (OK)

**Comment by spyder-issues-migrator** [comment]
_From [alabdelo...@gmail.com](https://code.google.com/u/114214539224837625032/) on 2014-10-17T20:37:33Z_

update: it seems that it was installed as some library dependecies and not by itself, so maybe the installation of that library that called him that was broken.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-18T10:58:50Z_

I think you need to look closely, because it's listed there as the second last entry:

sphinx >=0.6.6  :  1.2.3 (OK)

As I said, this seems a problem with your installation. We recommend you to use one of our traditional methods (i.e. the ones present in the page I referenced in comment `#1`).

**Comment by spyder-issues-migrator** [comment]
_From [alabdelo...@gmail.com](https://code.google.com/u/114214539224837625032/) on 2014-10-18T12:27:38Z_

yes, that is what isaid in the comment just after :D

and i precised that maybe it must come from one of the libraries that installed sphinx without calling jinja

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-18T12:32:12Z_

Ok, I didn't understand you :-)

Glad you figured it out what was happening!

**Comment by spyder-issues-migrator** [comment]
_From [alabdelo...@gmail.com](https://code.google.com/u/114214539224837625032/) on 2014-10-18T13:11:36Z_

thank you for this beautiful piece :*

(i use this for Python, and sadly because it dont support HTML (autocomplete) i use Brackets.)

Thank you again.
