### ISSUE TITLE
Problems with trying to open sockets on Windows

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2016]
_From [sage.mad...@gmail.com](https://code.google.com/u/112673853446120906536/) on 2014-10-20T10:35:52Z_

Spyder Version:  2.3.1
Python Version:  2.7.8
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Windows
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=0.13  :  2.2.0 (OK)
pygments >=1.6  :  1.6 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.4.0 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1.I tried to just print "Hello World"
2.I tried just copying and pasting a file from the tutorial
3.I tried running anything else. 

What is the expected output? What do you see instead?

 I expect to just see "Hello World."  Instead, I see:

'import sitecustomize' failed; use -v for traceback
Python 2.7.8 |Anaconda 2.1.0 (64-bit)| (default, Jul  2 2014, 15:12:11) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org >>> runfile('C:/Users/User/Documents/Python Scripts/Practice_1.py', wdir=r'C:/Users/User/Documents/Python Scripts')
Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
NameError: name 'runfile' is not defined
\>>> runfile('C:/Users/User/Documents/Python Scripts/Practice_1.py', wdir=r'C:/Users/User/Documents/Python Scripts')
Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
NameError: name 'runfile' is not defined
\>>> runfile('C:/Users/User/Documents/Python Scripts/hello.py', wdir=r'C:/Users/User/Documents/Python Scripts')
Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
NameError: name 'runfile' is not defined
\>>> >>> runfile('C:/Users/User/Documents/Python Scripts/hello.py', wdir=r'C:/Users/User/Documents/Python Scripts')
Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
NameError: name 'runfile' is not defined
\>>> 

Please provide any additional information below

. I also got this when I first opened the program without doing anything at all:

'import sitecustomize' failed; use -v for traceback
Assertion failed: Socket operation on non-socket (bundled\zeromq\src\select.cpp:170)
\---------------------------------------------------------------------------
ZMQError                                  Traceback (most recent call last)
C:\Users\User\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\start_ipython_kernel.py in \<module>()
    185 ipk_temp = IPKernelApp.instance()
    186 ipk_temp.config = kernel_config()
--> 187 ipk_temp.initialize()
        global ipk_temp.initialize = \<bound method IPKernelApp.initialize of \<IPython.kernel.zmq.kernelapp.IPKernelApp object at 0x000000000AA597F0>>
    188 
    189 # Grabbing the kernel's shell to share its namespace with our

C:\Users\User\Anaconda\lib\site-packages\IPython\kernel\zmq\kernelapp.py in initialize(self=<IPython.kernel.zmq.kernelapp.IPKernelApp object>, argv=None)

C:\Users\User\Anaconda\lib\site-packages\IPython\config\application.pyc in catch_config_error(method=<function initialize>, app=<IPython.kernel.zmq.kernelapp.IPKernelApp object>, *args=(None,), **kwargs={})
     90     """
     91     try:
---> 92         return method(app, *args, **kwargs)
        method = \<function initialize at 0x000000000AA62D68>
        app = \<IPython.kernel.zmq.kernelapp.IPKernelApp object at 0x000000000AA597F0>
        args = (None,)
        kwargs = {}
     93     except (TraitError, ArgumentError) as e:
     94         app.print_help()

C:\Users\User\Anaconda\lib\site-packages\IPython\kernel\zmq\kernelapp.py in initialize(self=<IPython.kernel.zmq.kernelapp.IPKernelApp object>, argv=None)
    433         self.init_session()
    434         self.init_poller()
--> 435         self.init_sockets()
        self.init_sockets = \<bound method IPKernelApp.init_sockets of \<IPython.kernel.zmq.kernelapp.IPKernelApp object at 0x000000000AA597F0>>
    436         self.init_heartbeat()
    437         # writing/displaying connection info must be *after* init_sockets/heartbeat

C:\Users\User\Anaconda\lib\site-packages\IPython\kernel\zmq\kernelapp.py in init_sockets(self=<IPython.kernel.zmq.kernelapp.IPKernelApp object>)
    298         # atexit.register(context.term)
    299 
--> 300         self.shell_socket = context.socket(zmq.ROUTER)
        self.shell_socket = undefined
        context.socket = \<bound method Context.socket of \<zmq.sugar.context.Context object at 0x000000000ACA89E8>>
        global zmq.ROUTER = 6
    301         self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
    302         self.log.debug("shell ROUTER Channel on port: &#37;i" &#37; self.shell_port)

C:\Users\User\Anaconda\lib\site-packages\zmq\sugar\context.pyc in socket(self=<zmq.sugar.context.Context object>, socket_type=6)
    135         if self.closed:
    136             raise ZMQError(ENOTSUP)
--> 137         s = self._socket_class(self, socket_type)
        s = undefined
        self._socket_class = \<class 'zmq.sugar.socket.Socket'>
        self = \<zmq.sugar.context.Context object at 0x000000000ACA89E8>
        socket_type = 6
    138         for opt, value in self.sockopts.items():
    139             try:

C:\Users\User\Anaconda\lib\site-packages\zmq\backend\cython\socket.pyd in zmq.backend.cython.socket.Socket.__cinit__ (zmq\backend\cython\socket.c:2481)()

ZMQError: Network is down
Assertion failed: Socket operation on non-socket (bundled\zeromq\src\select.cpp:170)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2016_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-20T09:47:58Z_

It seems you're firewall/antivirus is blocking the option to open sockets in your computer.

You need to add an option to it to stop this behavior. That depends on what firewall/antivirus you have.

**Comment by spyder-issues-migrator** [comment]
_From [sage.mad...@gmail.com](https://code.google.com/u/112673853446120906536/) on 2014-10-22T07:35:51Z_

I'm not sure how to do this.  I only use regular Windows firewall and Microsoft Security Essentials.  Do you know how I could add the option to open sockets?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-29T09:52:56Z_

I would recommend you to disconnect from the Internetm turn off the Windows firewall and security essentials, and then try to start Spyder again.

That would help you to identify if the firewall is the problem or not.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-29T09:57:27Z_

**Summary:** Problems with trying to open sockets on Windows  \<span class="oldvalue"> (was: Just installed spyder and I get errors any time I run anything.) \</span>  
  **Labels:** Cat-Console OpSys-Windows

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T14:57:16Z_

I'm sorry but there's nothing we can do on our side to help you solve this problem.

So I'm closing this issue. I hope you're able to figure it out what's happening.

**Status:** WontFix
