### ISSUE TITLE
Exiting Spyder causes freeze

### ISSUE THREAD

**Issue by taylorpetty** [spyder-ide/spyder#20182]
### What steps will reproduce the problem?

Every time I exit Spyder, it glitches like this. It doesn't show up on Task Manager so I just have to restart the computer, and the error message pops up "Shutting down will interfere with this program" and it's showing that Spyder is still running. The code disappears but the window stays open. Just now I tried to open Spyder again while it was frozen and it brought up the error report.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1289, in plugin_focus_changed
    self.update_search_menu()
  File "C:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1416, in update_search_menu
    self.search_menu_actions[3].setEnabled(readwrite_editor)
RuntimeError: wrapped C/C++ object of type SpyderAction has been deleted
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1289, in plugin_focus_changed
    self.update_search_menu()
  File "C:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1416, in update_search_menu
    self.search_menu_actions[3].setEnabled(readwrite_editor)
RuntimeError: wrapped C/C++ object of type SpyderAction has been deleted
```

## Versions

* Spyder version: 5.3.1 
* Python version: 3.8.13
* Qt version: 5.15.4
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.0.0 (OK)
cloudpickle >=0.5.0           :  2.1.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.7.2 (OK)
keyring >=17.0.0              :  23.6.0 (OK)
nbconvert >=4.0               :  6.5.0 (OK)
numpydoc >=0.6.0              :  1.2.1 (OK)
paramiko >=2.4.0              :  2.11.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.1 (OK)
pygments >=2.0                :  2.12.0 (OK)
pylint >=2.5.0                :  2.14.4 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.1 (OK)
qtpy >=2.1.0                  :  2.1.0 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  63.1.0 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.3.1;<2.4.0 :  2.3.2 (OK)
textdistance >=4.2.0          :  4.3.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.22.4 (OK)
pandas >=1.1.1                :  1.4.3 (OK)
scipy >=0.17.0                :  1.8.1 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @taylorpetty, thanks for reporting. This bug will be fixed in our next version (5.4.1), to be released before the end of the month. In the meantime, please don't report it again.
