### ISSUE TITLE
Error in starting of Kernel

### ISSUE THREAD

**Issue by kanishkjoshi3** [spyder-ide/spyder#20188]
### What steps will reproduce the problem?

An error ocurred while starting the kernel
Traceback (most recent call last):
File "C:\Users\Ta92\OneDrive\Documents\New folder\pkgs\spyder_kernels\console\__main__.py", line 24, in
start.main()
File "C:\Users\Ta92\OneDrive\Documents\New folder\pkgs\spyder_kernels\console\start.py", line 328, in main
kernel.initialize()
File "C:\Users\Ta92\OneDrive\Documents\New folder\pkgs\traitlets\config\application.py", line 110, in inner
return method(app, *args, **kwargs)
File "C:\Users\Ta92\OneDrive\Documents\New folder\pkgs\ipykernel\kernelapp.py", line 681, in initialize
self.init_kernel()
File "C:\Users\Ta92\OneDrive\Documents\New folder\pkgs\ipykernel\kernelapp.py", line 528, in init_kernel
kernel = kernel_factory(
File "C:\Users\Ta92\OneDrive\Documents\New folder\pkgs\traitlets\config\configurable.py", line 551, in instance
inst = cls(*args, **kwargs)
File "C:\Users\Ta92\OneDrive\Documents\New folder\pkgs\spyder_kernels\console\kernel.py", line 57, in __init__
self.frontend_comm = FrontendComm(self)
File "C:\Users\Ta92\OneDrive\Documents\New folder\pkgs\spyder_kernels\comms\frontendcomm.py", line 61, in __init__
self.context = zmq.Context()
NameError: name 'zmq' is not defined
Traceback (most recent call last):
File "runpy.py", line 194, in _run_module_as_main
File "runpy.py", line 87, in _run_code
File "C:\Users\Ta92\OneDrive\Documents\New folder\pkgs\spyder_kernels\console\__main__.py", line 24, in
start.main()
File "C:\Users\Ta92\OneDrive\Documents\New folder\pkgs\spyder_kernels\console\start.py", line 328, in main
kernel.initialize()
File "C:\Users\Ta92\OneDrive\Documents\New folder\pkgs\traitlets\config\application.py", line 110, in inner
return method(app, *args, **kwargs)
File "C:\Users\Ta92\OneDrive\Documents\New folder\pkgs\ipykernel\kernelapp.py", line 681, in initialize
self.init_kernel()
File "C:\Users\Ta92\OneDrive\Documents\New folder\pkgs\ipykernel\kernelapp.py", line 528, in init_kernel
kernel = kernel_factory(
File "C:\Users\Ta92\OneDrive\Documents\New folder\pkgs\traitlets\config\configurable.py", line 551, in instance
inst = cls(*args, **kwargs)
File "C:\Users\Ta92\OneDrive\Documents\New folder\pkgs\spyder_kernels\console\kernel.py", line 57, in __init__
self.frontend_comm = FrontendComm(self)
File "C:\Users\Ta92\OneDrive\Documents\New folder\pkgs\spyder_kernels\comms\frontendcomm.py", line 61, in __init__
self.context = zmq.Context()
NameError: name 'zmq' is not defined

## Versions

* Spyder version: 5.3.3  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.0.0 (OK)
cloudpickle >=0.5.0                  :  2.1.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<8.0.0              :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.14.0 (OK)
keyring >=17.0.0                     :  23.8.2 (OK)
nbconvert >=4.0                      :  7.0.0 (OK)
numpydoc >=0.6.0                     :  1.4.0 (OK)
paramiko >=2.4.0                     :  2.11.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.1 (OK)
pygments >=2.0                       :  2.13.0 (OK)
pylint >=2.5.0;<3.0                  :  2.15.0 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0                 :  1.5.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.2;<5.4.0             :  5.3.2 (OK)
qtpy >=2.1.0                         :  2.2.0 (OK)
rtree >=0.9.7                        :  1.0.0 (OK)
setuptools >=49.6.0                  :  65.3.0 (OK)
sphinx >=0.6.6                       :  5.1.1 (OK)
spyder_kernels >=2.3.3;<2.4.0        :  2.3.3 (OK)
textdistance >=4.2.0                 :  4.4.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.1.9 (OK)
zmq >=22.1.0                         :  23.2.1 (OK)

# Optional:
cython >=0.21                        :  0.29.32 (OK)
matplotlib >=3.0.0                   :  3.5.3 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.4.3 (OK)
scipy >=0.17.0                       :  1.9.1 (OK)
sympy >=0.7.3                        :  1.11 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @kanishkjoshi3, thanks for reporting. Please uninstall Spyder and install it out of your OneDrive folder. The problem is files in that folder appear and disappear for a little while being synced, which could be the cause of this bug.

Let us know if it works for you.

**Comment by kanishkjoshi3** [comment]
Please tell how to uninstall and install

**Comment by ccordoba12** [comment]
> Please tell how to uninstall

As you would install any other Windows application, which is described in detail [here](https://support.microsoft.com/en-us/windows/uninstall-or-remove-apps-and-programs-in-windows-4b55f974-2cc6-2d2b-d092-5905080eaf98#ID0EBD=Windows_10).

> and install

Go to this [webpage](https://github.com/spyder-ide/spyder/releases/tag/v5.3.3), download our Windows installer and install it again.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
