### ISSUE TITLE
Internal problem

### ISSUE THREAD

**Issue by shape2452** [spyder-ide/spyder#20219]
### What steps will reproduce the problem?

Open the spyder......
  File "C:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 453, in finish_recv
    return ov.getresult()
OSError: [WinError 995] 由于线程退出或应用程序请求，已中止 I/O 操作。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "C:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 995] 由于线程退出或应用程序请求，已中止 I/O 操作。

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 453, in finish_recv
    return ov.getresult()
OSError: [WinError 995] 由于线程退出或应用程序请求，已中止 I/O 操作。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "C:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 995] 由于线程退出或应用程序请求，已中止 I/O 操作。
```

## Versions

* Spyder version: 4.2.5 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  2.0.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  8.6.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  4.16.0 (OK)
keyring >=17.0.0                :  23.4.0 (OK)
nbconvert >=4.0                 :  6.5.4 (OK)
numpydoc >=0.6.0                :  1.5.0 (OK)
paramiko >=2.4.0                :  2.8.1 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.9.0 (OK)
pygments >=2.0                  :  2.11.2 (OK)
pylint >=1.0                    :  2.14.5 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.3 (OK)
qtconsole >=5.0.3               :  5.3.2 (OK)
qtpy >=1.5.0                    :  2.2.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  65.5.0 (OK)
sphinx >=0.6.6                  :  5.0.2 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  23.2.0 (OK)

# Optional:
cython >=0.21                   :  0.29.32 (OK)
matplotlib >=2.0.0              :  3.6.2 (OK)
numpy >=1.7                     :  1.23.4 (OK)
pandas >=1.1.1                  :  1.5.2 (OK)
scipy >=0.17.0                  :  1.9.3 (OK)
sympy >=0.7.3                   :  1.11.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @shape2452  thanks for reporting. This problem is fixed in our latest version available in Anaconda (5.3.3). Please update by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).

After doing that, please run

    conda update python

That should solve your problem.
