### ISSUE TITLE
the program is running without giving plots as output

### ISSUE THREAD

**Issue by Nashid89** [spyder-ide/spyder#20214]
### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\nm86611\Anaconda3\envs\pythonProject\lib\site-packages\jupyter_client\utils.py", line 14, in wrapped
    loop = asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nm86611\Anaconda3\envs\pythonProject\lib\site-packages\jupyter_client\utils.py", line 18, in wrapped
    loop = asyncio.get_event_loop_policy().get_event_loop()
  File "C:\Users\nm86611\Anaconda3\envs\pythonProject\lib\asyncio\events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Dummy-60'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nm86611\Anaconda3\envs\pythonProject\lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 682, in _restart_thread_main
    stdout=self.stdout_obj.handle)
  File "C:\Users\nm86611\Anaconda3\envs\pythonProject\lib\site-packages\jupyter_client\utils.py", line 20, in wrapped
    loop = asyncio.new_event_loop()
  File "C:\Users\nm86611\Anaconda3\envs\pythonProject\lib\asyncio\events.py", line 762, in new_event_loop
    return get_event_loop_policy().new_event_loop()
  File "C:\Users\nm86611\Anaconda3\envs\pythonProject\lib\asyncio\events.py", line 660, in new_event_loop
    return self._loop_factory()
  File "C:\Users\nm86611\Anaconda3\envs\pythonProject\lib\asyncio\selector_events.py", line 60, in __init__
    self._make_self_pipe()
  File "C:\Users\nm86611\Anaconda3\envs\pythonProject\lib\asyncio\selector_events.py", line 107, in _make_self_pipe
    self._ssock, self._csock = socket.socketpair()
  File "C:\Users\nm86611\Anaconda3\envs\pythonProject\lib\socket.py", line 516, in socketpair
    lsock.bind((host, 0))
OSError: [WinError 10055] An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full
```

## Versions

* Spyder version: 5.2.2 
* Python version: 3.7.13
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  65.5.0 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @Nashid89, thanks for reporting. This problem could be fixed in our latest version available in Anaconda (5.3.3). So, please update by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).

Let us know if it works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by Nashid89** [comment]
Thank you so much.

I apologize for my delayed response.

 Happy holidays.

Regards
Nashid Mumtaz

**Comment by ccordoba12** [comment]
No problem, I hope the problem was fixed for you.

**Comment by Nashid89** [comment]
Yes, it is working.

Thank you very much. 😊

Regards
Nashid
