### ISSUE TITLE
Internal problem

### ISSUE THREAD

**Issue by RuiStar** [spyder-ide/spyder#20229]
### What steps will reproduce the problem?

When you start Spyder and when you start console, it will pops up.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/Users/huangrui/.local/lib/python3.9/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/huangrui/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/ipythonconsole/widgets/namespacebrowser.py", line 214, in _handle_execute_reply
    super(NamepaceBrowserWidget, self)._handle_execute_reply(msg)
  File "/Users/huangrui/.local/lib/python3.9/site-packages/qtconsole/jupyter_widget.py", line 191, in _handle_execute_reply
    self._show_interpreter_prompt(number)
  File "/Users/huangrui/.local/lib/python3.9/site-packages/qtconsole/jupyter_widget.py", line 382, in _show_interpreter_prompt
    self._show_prompt(self._make_in_prompt(number), html=True)
  File "/Users/huangrui/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/ipythonconsole/widgets/debugging.py", line 672, in _show_prompt
    super(DebuggingWidget, self)._show_prompt(prompt, html, newline,
TypeError: _show_prompt() takes from 1 to 4 positional arguments but 5 were given
Traceback (most recent call last):
  File "/Users/huangrui/.local/lib/python3.9/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/huangrui/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/ipythonconsole/widgets/namespacebrowser.py", line 214, in _handle_execute_reply
    super(NamepaceBrowserWidget, self)._handle_execute_reply(msg)
  File "/Users/huangrui/.local/lib/python3.9/site-packages/qtconsole/jupyter_widget.py", line 194, in _handle_execute_reply
    super()._handle_execute_reply(msg)
  File "/Users/huangrui/.local/lib/python3.9/site-packages/qtconsole/frontend_widget.py", line 476, in _handle_execute_reply
    self._show_interpreter_prompt_for_reply(msg)
  File "/Users/huangrui/.local/lib/python3.9/site-packages/qtconsole/jupyter_widget.py", line 441, in _show_interpreter_prompt_for_reply
    self._show_interpreter_prompt(previous_prompt_number + 1)
  File "/Users/huangrui/.local/lib/python3.9/site-packages/qtconsole/jupyter_widget.py", line 382, in _show_interpreter_prompt
    self._show_prompt(self._make_in_prompt(number), html=True)
  File "/Users/huangrui/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/ipythonconsole/widgets/debugging.py", line 672, in _show_prompt
    super(DebuggingWidget, self)._show_prompt(prompt, html, newline,
TypeError: _show_prompt() takes from 1 to 4 positional arguments but 5 were given
Traceback (most recent call last):
  File "/Users/huangrui/.local/lib/python3.9/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/huangrui/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/ipythonconsole/widgets/namespacebrowser.py", line 214, in _handle_execute_reply
    super(NamepaceBrowserWidget, self)._handle_execute_reply(msg)
  File "/Users/huangrui/.local/lib/python3.9/site-packages/qtconsole/jupyter_widget.py", line 191, in _handle_execute_reply
    self._show_interpreter_prompt(number)
  File "/Users/huangrui/.local/lib/python3.9/site-packages/qtconsole/jupyter_widget.py", line 382, in _show_interpreter_prompt
    self._show_prompt(self._make_in_prompt(number), html=True)
  File "/Users/huangrui/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/ipythonconsole/widgets/debugging.py", line 672, in _show_prompt
    super(DebuggingWidget, self)._show_prompt(prompt, html, newline,
TypeError: _show_prompt() takes from 1 to 4 positional arguments but 5 were given
Traceback (most recent call last):
  File "/Users/huangrui/.local/lib/python3.9/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/huangrui/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/ipythonconsole/widgets/namespacebrowser.py", line 214, in _handle_execute_reply
    super(NamepaceBrowserWidget, self)._handle_execute_reply(msg)
  File "/Users/huangrui/.local/lib/python3.9/site-packages/qtconsole/jupyter_widget.py", line 194, in _handle_execute_reply
    super()._handle_execute_reply(msg)
  File "/Users/huangrui/.local/lib/python3.9/site-packages/qtconsole/frontend_widget.py", line 476, in _handle_execute_reply
    self._show_interpreter_prompt_for_reply(msg)
  File "/Users/huangrui/.local/lib/python3.9/site-packages/qtconsole/jupyter_widget.py", line 441, in _show_interpreter_prompt_for_reply
    self._show_interpreter_prompt(previous_prompt_number + 1)
  File "/Users/huangrui/.local/lib/python3.9/site-packages/qtconsole/jupyter_widget.py", line 382, in _show_interpreter_prompt
    self._show_prompt(self._make_in_prompt(number), html=True)
  File "/Users/huangrui/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/ipythonconsole/widgets/debugging.py", line 672, in _show_prompt
    super(DebuggingWidget, self)._show_prompt(prompt, html, newline,
TypeError: _show_prompt() takes from 1 to 4 positional arguments but 5 were given
```

## Versions

* Spyder version: 5.3.3  (conda)
* Python version: 3.9.13 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Darwin 21.6.0

### Dependencies

```
# Mandatory:
applaunchservices >=0.3.0     :  0.3.0 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.23.1 (NOK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=2.5.0;<3.0           :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.1.0 (NOK)
qtpy >=2.1.0                  :  1.9.0 (NOK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  63.4.1 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  22.0.3 (NOK)

# Optional:
cython >=0.21                 :  0.29.32 (OK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.4 (OK)
scipy >=0.17.0                :  1.9.1 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @RuiStar, thanks for reporting. To fix this error you need to close Spyder, open a terminal and run there

    rm -Rf /Users/huangrui/.local/lib/python3.9

The problem is you have some Python packages installed in that directory which are interfering with your Anaconda installation.
