### ISSUE TITLE
Error with Python 3 if non-ASCII Unicode appears in script

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2023]
_From [dave.lin...@gmail.com](https://code.google.com/u/107110792395568123171/) on 2014-10-25T12:59:57Z_

Spyder Version:  2.3.0beta2
Python Version:  3.3.3
Qt Version    :  4.8.4, PyQt4 (API v2) 4.9.6 on Windows
pyflakes >=0.6.0:  None (OK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  1.1.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2.1 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.4.1 (OK)
pylint >=0.25   :  1.0.0 (OK) 

What steps will reproduce the problem?

 1. Write a script that uses non-ASCII Unicode in the script
 Example:
      SEP  = "‖"

2. Run it.

3. Output is:

Inspect Spyder internals:
  spy.app, spy.window, dir(spy)
\>>> Traceback (most recent call last):
  File "C:\WinPython-64bit-3.3.3.3\python-3.3.3.amd64\lib\site-packages\spyderlib\widgets\editor.py", line 1486, in analyze_script
    finfo.run_code_analysis(run_pyflakes, run_pep8)
  File "C:\WinPython-64bit-3.3.3.3\python-3.3.3.amd64\lib\site-packages\spyderlib\widgets\editor.py", line 450, in run_code_analysis
    source_code = self.get_source_code().encode(enc)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2016' in position 1510: ordinal not in range(128) 

What is the expected output? What do you see instead?

 It's Python 3, so I expect it to handle Unicode smoothly.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2023_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-25T11:06:17Z_

Phew! So glad we are on the way of fixing this! Could you test this pull request https://bitbucket.org/spyder-ide/spyderlib/pull-request/83/fixes-for-various-unicode-issues-in-python to see if it fixes your problem?

**Summary:** Error with Python 3 if non-ASCII Unicode appears in script  \<span class="oldvalue"> (was: Error w/Python 3 if non-ASCII Unicode appears in script) \</span>  
  **Labels:** MS-v2.3.2 Cat-Editor

**Comment by spyder-issues-migrator** [comment]
_From [dave.lin...@gmail.com](https://code.google.com/u/107110792395568123171/) on 2014-10-25T11:41:43Z_

@-ccordoba12: Thanks. Updating to the latest WinPython (3.3.5 from April) seems to have fixed it.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-26T10:33:20Z_

Ok, great. Thanks for letting us know

**Status:** WontFix  
  **Labels:** -MS-v2.3.2
