### ISSUE TITLE
Spyder crashes because matplotlib cannot read its config file in a non-ascii account on Windows

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2025]
_From [i.ri...@gmail.com](https://code.google.com/u/103802026608335163677/) on 2014-10-26T14:32:59Z_

Running on Windows 7 64-bit

C:\Users\Иван\Anaconda\Scripts>python -V
Python 2.7.8 :: Anaconda 2.1.0 (32-bit)

C:\Users\Иван\Anaconda\Scripts>spyder
Traceback (most recent call last):
  File "C:\Users\╚трэ\Anaconda\Scripts\spyder-script.py", line 1,
in \<module>
    from spyderlib import start_app
  File "C:\Users\╚трэ\Anaconda\lib\site-packages\spyderlib\start_a
pp.py", line 14, in \<module>
    from spyderlib.config import CONF
  File "C:\Users\╚трэ\Anaconda\lib\site-packages\spyderlib\config.
py", line 22, in \<module>
    from spyderlib.utils import iofuncs, codeanalysis
  File "C:\Users\╚трэ\Anaconda\lib\site-packages\spyderlib\utils\i
ofuncs.py", line 26, in \<module>
    import pandas as pd
  File "C:\Users\╚трэ\Anaconda\lib\site-packages\pandas\__init__.p
y", line 41, in \<module>
    from pandas.core.api import *
  File "C:\Users\╚трэ\Anaconda\lib\site-packages\pandas\core\api.p
y", line 9, in \<module>
    from pandas.core.groupby import Grouper
  File "C:\Users\╚трэ\Anaconda\lib\site-packages\pandas\core\group
by.py", line 15, in \<module>
    from pandas.core.frame import DataFrame
  File "C:\Users\╚трэ\Anaconda\lib\site-packages\pandas\core\frame
.py", line 38, in \<module>
    from pandas.core.series import Series
  File "C:\Users\╚трэ\Anaconda\lib\site-packages\pandas\core\serie
s.py", line 2524, in \<module>
    import pandas.tools.plotting as _gfx
  File "C:\Users\╚трэ\Anaconda\lib\site-packages\pandas\tools\plot
ting.py", line 26, in \<module>
    import pandas.tseries.converter as conv
  File "C:\Users\╚трэ\Anaconda\lib\site-packages\pandas\tseries\co
nverter.py", line 7, in \<module>
    import matplotlib.units as units
  File "C:\Users\╚трэ\Anaconda\lib\site-packages\matplotlib\__init
__.py", line 1048, in \<module>
    rcParams = rc_params()
  File "C:\Users\╚трэ\Anaconda\lib\site-packages\matplotlib\__init
__.py", line 897, in rc_params
    fname = matplotlib_fname()
  File "C:\Users\╚трэ\Anaconda\lib\site-packages\matplotlib\__init
__.py", line 748, in matplotlib_fname
    fname = os.path.join(os.getcwd(), 'matplotlibrc')
  File "C:\Users\╚трэ\Anaconda\lib\ntpath.py", line 84, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 7: ordinal
not in range(128)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2025_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-29T09:50:17Z_

What I can see from this error is a problem with matplotlib, not with Spyder. The second last line in the traceback is:

    fname = os.path.join(os.getcwd(), 'matplotlibrc')

which means that matplotlib is trying to read its configuration file but it cannot do it because your user name contains non-ascii chars.

A couple of questions:

1. Were you able to use matplotlib before?

2. What do you get if you run this code in a python interpreter in a cmd.exe?

     import matplotlib

**Summary:** Spyder crashes because matplotlib cannot read its config file in a non-ascii account on Windows  \<span class="oldvalue"> (was: Spyder crashes while start just after installation) \</span>  
  **Labels:** Cat-SpyderGUI

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T14:47:33Z_

Please update to matplotlb version 1.4.2. This problem was fixed in that version.

**Status:** WontFix
