### ISSUE TITLE
Typing 'import' or 'from' into the IPython console causes TypeError in pygment.

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2031]
_From [cookieof...@gmail.com](https://code.google.com/u/114956027056399625538/) on 2014-10-28T14:57:03Z_

Spyder Version:  2.3.1
Python Version:  2.7.2
Qt Version    :  4.8.5, PySide 1.2.1 on Windows
IPython >=0.13  :  2.3.0 (OK)
matplotlib >=1.0:  1.4.2 (OK)
pandas >=0.13.1 :  0.15.0 (OK)
pep8 >=0.6      :  1.5.7 (OK)
pyflakes >=0.5.0:  0.5.0 (OK)
pygments >=1.6  :  2.0rc1 (OK)
pylint >=0.25   :  1.0.0 (OK)
rope >=0.9.2    :  0.10.2 (OK)
sphinx >=0.6.6  :  1.3b1 (OK)
sympy >=0.7.0   :  0.7.1 (OK) 

What steps will reproduce the problem?

 1. Type 'import' or 'from' into the IPython console.
2. Internal console opens and displays error.
3. Step 2 keeps occurring when typing until the line is executed. 

What is the expected output? What do you see instead?

 Expects no error. Instead internal console shows this:

 Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\ipython-2.3.0-py2.7.egg\IPython\qt\console\frontend_widget.py", line 60, in highlightBlock
    super(FrontendHighlighter, self).highlightBlock(string)
  File "C:\Python27\lib\site-packages\ipython-2.3.0-py2.7.egg\IPython\qt\console\pygments_highlighter.py", line 115, in highlightBlock
    for token, text in self._lexer.get_tokens(string):
  File "C:\Python27\lib\site-packages\pygments 

Please provide any additional information below

. Does not appear to trigger on any other commands.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2031_

**Comment by spyder-issues-migrator** [comment]
_From [cookieof...@gmail.com](https://code.google.com/u/114956027056399625538/) on 2014-10-28T12:58:15Z_

Traceback got truncated, here is the full trace:

 Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\ipython-2.3.0-py2.7.egg\IPython\qt\console\frontend_widget.py", line 60, in highlightBlock
    super(FrontendHighlighter, self).highlightBlock(string)
  File "C:\Python27\lib\site-packages\ipython-2.3.0-py2.7.egg\IPython\qt\console\pygments_highlighter.py", line 115, in highlightBlock
    for token, text in self._lexer.get_tokens(string):
  File "C:\Python27\lib\site-packages\pygments-2.0rc1-py2.7.egg\pygments\lexer.py", line 193, in streamer
    for i, t, v in self.get_tokens_unprocessed(text):
  File "C:\Python27\lib\site-packages\ipython-2.3.0-py2.7.egg\IPython\qt\console\pygments_highlighter.py", line 30, in get_tokens_unprocessed
    for item in action(self, m):
TypeError: 'NoneType' object is not callable

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-28T17:39:37Z_

I see you're using a beta version of pygments, so my best bet is that that is the main source of the problem.

Please open an issue in IPython issue tracker: https://github.com/ipython/ipython/issues/ to let them know about it because we can't solve it in Spyder.

**Status:** WontFix
