### ISSUE TITLE
kernel not connected

### ISSUE THREAD

**Issue by natrichards** [spyder-ide/spyder#20343]
### What steps will reproduce the problem?

Traceback (most recent call last):
File "", line 198, in _run_module_as_main
File "", line 88, in _run_code
File "C:\Users\ac39981\AppData\Local\Programs\Python\Python311\spyder_kernels\console\__main__.py", line 22, in
from spyder_kernels.console import start
ImportError: cannot import name 'start' from 'spyder_kernels.console' (C:\Users\ac39981\AppData\Local\Programs\Python\Python311\spyder_kernels\console\__init__.py)

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\ac39981\AppData\Local\Programs\Python\pkgs\jupyter_client\manager.py", line 85, in wrapper
    self._ready.set_result(None)
asyncio.exceptions.InvalidStateError: invalid state

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ac39981\AppData\Local\Programs\Python\pkgs\qtconsole\manager.py", line 27, in poll
    super().poll()
  File "C:\Users\ac39981\AppData\Local\Programs\Python\pkgs\jupyter_client\restarter.py", line 143, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "C:\Users\ac39981\AppData\Local\Programs\Python\pkgs\jupyter_client\utils.py", line 30, in wrapped
    raise e
  File "C:\Users\ac39981\AppData\Local\Programs\Python\pkgs\jupyter_client\utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "C:\Users\ac39981\AppData\Local\Programs\Python\pkgs\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "asyncio\futures.py", line 178, in result
  File "asyncio\tasks.py", line 280, in __step
  File "C:\Users\ac39981\AppData\Local\Programs\Python\pkgs\jupyter_client\manager.py", line 548, in _async_restart_kernel
    await ensure_async(self.start_kernel(**self._launch_args))
  File "C:\Users\ac39981\AppData\Local\Programs\Python\pkgs\jupyter_client\utils.py", line 30, in wrapped
    raise e
  File "C:\Users\ac39981\AppData\Local\Programs\Python\pkgs\jupyter_client\utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "C:\Users\ac39981\AppData\Local\Programs\Python\pkgs\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "asyncio\futures.py", line 178, in result
  File "asyncio\tasks.py", line 280, in __step
  File "C:\Users\ac39981\AppData\Local\Programs\Python\pkgs\jupyter_client\manager.py", line 88, in wrapper
    self._ready.set_exception(e)
asyncio.exceptions.InvalidStateError: invalid state
```

## Versions

* Spyder version: 5.4.1  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.1.0 (OK)
cloudpickle >=0.5.0                  :  2.2.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<9.0.0              :  8.7.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.2 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.17.3 (OK)
keyring >=17.0.0                     :  23.13.1 (OK)
nbconvert >=4.0                      :  7.2.7 (OK)
numpydoc >=0.6.0                     :  1.5.0 (OK)
paramiko >=2.4.0                     :  2.12.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.4 (OK)
pygments >=2.0                       :  2.13.0 (OK)
pylint >=2.5.0;<3.0                  :  2.15.9 (OK)
pylint_venv >=2.1.1                  :  2.3.0 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.7.0;<1.8.0                 :  1.7.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.2.2                    :  0.2.2 (OK)
qtawesome >=1.2.1                    :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0             :  5.4.0 (OK)
qtpy >=2.1.0                         :  2.3.0 (OK)
rtree >=0.9.7                        :  1.0.1 (OK)
setuptools >=49.6.0                  :  65.6.3 (OK)
sphinx >=0.6.6                       :  6.0.0 (OK)
spyder_kernels >=2.4.1;<2.5.0        :  2.4.1 (OK)
textdistance >=4.2.0                 :  4.5.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.2.0 (OK)
zmq >=22.1.0                         :  24.0.1 (OK)

# Optional:
cython >=0.21                        :  0.29.32 (OK)
matplotlib >=3.0.0                   :  3.6.2 (OK)
numpy >=1.7                          :  1.24.1 (OK)
pandas >=1.1.1                       :  1.5.2 (OK)
scipy >=0.17.0                       :  1.9.3 (OK)
sympy >=0.7.3                        :  1.11.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @natrichards, thanks for reporting. Please open this directory

    C:\Users\ac39981\AppData\Local\Programs

in the Windows file explorer and remove the `Python` directory in it. That should fix your problem.

**Comment by ccordoba12** [comment]
Let us know if it works for you.

**Comment by ccordoba12** [comment]
Great! Closing then.
