### ISSUE TITLE
Unable to switch environment to different python env when spyder opened through windows shortcut.

### ISSUE THREAD

**Issue by anuragsodhi** [spyder-ide/spyder#20357]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am facing this issue with spyder 5.4.1. I am trying to use this version of spyder and activate a different python env in which i have spyder kernels 2.4.1 installed. What is strange is if i open anaconda prompt activate the python env containing spyder (and latest 3.11 python) and run spyder from there, change python env to one containing python 3.7 and spyder kernels 2.4.1, i dont get any error. But when i run spyder from windows shortcut, i get this error upon switching to python 3.7 env (which has 2.4.1 kernel)

### What steps reproduce the problem?

1. Make two conda env (one with spyder 5.4.1 and python 3.10 and other with python 3.7 and spyder kernel 2.4.1)
2.  start spyder with windows shortcut
3. switch to env containing py 3.7. It crashes with folloing error

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
File "C:\Dev\python_envs\spyder_5_4_1\Lib\site‑packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 2136, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle,
File "C:\Dev\python_envs\spyder_5_4_1\Lib\site‑packages\jupyter_client\utils.py", line 30, in wrapped
raise e
File "C:\Dev\python_envs\spyder_5_4_1\Lib\site‑packages\jupyter_client\utils.py", line 27, in wrapped
return loop.run_until_complete(future)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Dev\python_envs\spyder_5_4_1\Lib\site‑packages\nest_asyncio.py", line 90, in run_until_complete
return f.result()
^^^^^^^^^^
File "C:\Dev\python_envs\spyder_5_4_1\Lib\asyncio\futures.py", line 203, in result
raise self._exception.with_traceback(self._exception_tb)
File "C:\Dev\python_envs\spyder_5_4_1\Lib\asyncio\tasks.py", line 267, in __step
result = coro.send(None)
^^^^^^^^^^^^^^^
File "C:\Dev\python_envs\spyder_5_4_1\Lib\site‑packages\jupyter_client\manager.py", line 90, in wrapper
raise e
File "C:\Dev\python_envs\spyder_5_4_1\Lib\site‑packages\jupyter_client\manager.py", line 82, in wrapper
out = await method(self, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Dev\python_envs\spyder_5_4_1\Lib\site‑packages\jupyter_client\manager.py", line 391, in _async_start_kernel
kernel_cmd, kw = await ensure_async(self.pre_start_kernel(**kw))
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Dev\python_envs\spyder_5_4_1\Lib\site‑packages\jupyter_client\utils.py", line 30, in wrapped
raise e
File "C:\Dev\python_envs\spyder_5_4_1\Lib\site‑packages\jupyter_client\utils.py", line 27, in wrapped
return loop.run_until_complete(future)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Dev\python_envs\spyder_5_4_1\Lib\site‑packages\nest_asyncio.py", line 90, in run_until_complete
return f.result()
^^^^^^^^^^
File "C:\Dev\python_envs\spyder_5_4_1\Lib\asyncio\futures.py", line 203, in result
raise self._exception.with_traceback(self._exception_tb)
File "C:\Dev\python_envs\spyder_5_4_1\Lib\asyncio\tasks.py", line 267, in __step
result = coro.send(None)
^^^^^^^^^^^^^^^
File "C:\Dev\python_envs\spyder_5_4_1\Lib\site‑packages\jupyter_client\manager.py", line 356, in _async_pre_start_kernel
kw = await self.provisioner.pre_launch(**kw)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Dev\python_envs\spyder_5_4_1\Lib\site‑packages\jupyter_client\provisioning\local_provisioner.py", line 193, in pre_launch
kernel_cmd = km.format_kernel_cmd(
^^^^^^^^^^^^^^^^^^^^^
File "C:\Dev\python_envs\spyder_5_4_1\Lib\site‑packages\jupyter_client\manager.py", line 265, in format_kernel_cmd
cmd = self.kernel_spec.argv + extra_arguments
^^^^^^^^^^^^^^^^^^^^^
File "C:\Dev\python_envs\spyder_5_4_1\Lib\site‑packages\spyder\plugins\ipythonconsole\utils\kernelspec.py", line 107, in argv
get_conda_activation_script(),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Dev\python_envs\spyder_5_4_1\Lib\site‑packages\spyder\utils\conda.py", line 76, in get_conda_activation_script
if osp.basename(exe).startswith('micromamba'):
^^^^^^^^^^^^^^^^^
File "", line 242, in basename
File "", line 211, in split
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @anuragsodhi, thanks for reporting. We'll fix this problem in our next version (5.4.2), to be released next week.

**Comment by ccordoba12** [comment]
@anuragsodhi, this turned out not so easy to solve so we'll have to leave it for 5.4.3. However, I'd like to ask you a couple of questions to better understand your setup:

1. Did you install Anaconda/Miniconda in a non-standard location? I mean, a directory that's not `C:\Users\Anaconda` or something similar?
2. If you start a regular terminal (i.e. not the Anaconda Prompt), are you able to run the `conda` command? It seems you are not, but I'd like to confirm with you.

**Comment by anuragsodhi** [comment]
Thanks for looking at it.
1. Yes, it is installed in C:Dev location.
2. Correct, I am not able to

**Comment by ccordoba12** [comment]
Ok, thanks for your answers. They confirm my expectations about your setup.

So, the problem is that Spyder detects that you want to use an external Conda environment but it can't find `conda` to activate it. For now, the best we can do is to detect that situation and report it to the user in a message similar to the one we show when there are errors while starting the kernel. In Spyder 6 we could add an entry field similar to the one we offer to select a Python interpreter, so that users can introduce the path where `conda` is located in their systems.

What you need to do on your side to solve this problem is to add `conda` to your `PATH`. On Windows, that path should be

    C:\<your Anaconda installation directory>\Scripts

if I'm not mistaken (I can't test it right now). [Here](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/) you can find a guide on how to do that.

**Comment by anuragsodhi** [comment]
Thanks, due to IT security issues adding to sys env variables is not allowed on my machine, i'll check if i can use usr env variables. If not i'll wait for v6. Thanks for all the work

**Comment by anuragsodhi** [comment]
> an use usr env vari

i was able to add env/scipts to user path variable and 5.4.3 works

**Comment by ccordoba12** [comment]
Hey guys, good news about this issue: it'll be mitigated in 5.5.2 (our next version) in case you don't install envs outside our conda-based installation and are using Miniconda or have `conda` installed in your base env.

Additional improvements to really solve it will come in Spyder 6.

**Comment by mvbentes** [comment]
I just update to 5.5.4 and the problem is now gone. Thank you!
