### ISSUE TITLE
Fehlermeldung01_2023

### ISSUE THREAD

**Issue by FHJ-HM** [spyder-ide/spyder#20361]
### What steps will reproduce the problem?

nach upgrade mit PIP gibt es in der neuen Umgebung keinen Verbindungsaufbau mit Kernel

### Traceback
```python-traceback
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/home/fhj/.local/lib/python3.8/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/home/fhj/.local/lib/python3.8/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x7f6911a1e280>)
Traceback (most recent call last):
  File "/home/fhj/.local/lib/python3.8/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 705, in <lambda>
    self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/home/fhj/.local/lib/python3.8/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/home/fhj/.local/lib/python3.8/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/home/fhj/.local/lib/python3.8/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x7f6911a1e310>)
Traceback (most recent call last):
  File "/home/fhj/.local/lib/python3.8/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 705, in <lambda>
    self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/home/fhj/.local/lib/python3.8/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/home/fhj/.local/lib/python3.8/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/home/fhj/.local/lib/python3.8/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x7f6911a22c10>)
Traceback (most recent call last):
  File "/home/fhj/.local/lib/python3.8/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 705, in <lambda>
    self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/home/fhj/.local/lib/python3.8/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/home/fhj/.local/lib/python3.8/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/home/fhj/.local/lib/python3.8/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x7f6911a1e160>)
Traceback (most recent call last):
  File "/home/fhj/.local/lib/python3.8/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 705, in <lambda>
    self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/fhj/.local/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/home/fhj/.local/lib/python3.8/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/home/fhj/.local/lib/python3.8/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
```

## Versions

* Spyder version: 5.4.1  (pip)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Linux 5.4.0-136-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  1.3.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<9.0.0       :  8.8.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  18.0.1 (OK)
nbconvert >=4.0               :  5.6.1 (OK)
numpydoc >=0.6.0              :  0.7.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.6.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.5.1 (OK)
pygments >=2.0                :  2.14.0 (OK)
pylint >=2.5.0;<3.0           :  2.15.10 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.0;<1.8.0          :  1.7.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.3.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  57.0.0 (OK)
sphinx >=0.6.6                :  1.8.5 (OK)
spyder_kernels >=2.4.1;<2.5.0 :  2.4.1 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.2.1 (OK)
xdg >=0.26                    :  0.26 (OK)
zmq >=22.1.0                  :  25.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.1.2 (OK)
numpy >=1.7                   :  1.24.1 (OK)
pandas >=1.1.1                :  1.2.5 (OK)
scipy >=0.17.0                :  1.3.3 (OK)
sympy >=0.7.3                 :  None (NOK)
```

### Environment

<details><summary>Environment</summary>

```
Package                      Version
---------------------------- --------------------
absl-py                      1.4.0
alabaster                    0.7.8
apturl                       0.5.2
arrow                        1.2.3
asn1crypto                   0.24.0
astroid                      2.13.2
asttokens                    2.2.1
astunparse                   1.6.3
atomicwrites                 1.4.1
attrs                        19.3.0
autopep8                     1.6.0
Babel                        2.6.0
backcall                     0.1.0
bcrypt                       3.1.7
binaryornot                  0.4.4
black                        22.12.0
bleach                       3.1.1
blinker                      1.4
Brlapi                       0.7.0
cachetools                   4.2.2
certifi                      2019.11.28
chardet                      3.0.4
charset-normalizer           2.1.1
click                        8.1.3
cloudpickle                  1.3.0
colorama                     0.4.3
comm                         0.1.2
command-not-found            0.3
cookiecutter                 2.1.1
cryptography                 2.8
cupshelpers                  1.0
cycler                       0.10.0
dbus-python                  1.2.16
debugpy                      1.6.5
decorator                    4.4.2
defer                        1.0.6
defusedxml                   0.6.0
diff-match-patch             20200713
dill                         0.3.6
distro                       1.4.0
distro-info                  0.23ubuntu1
docstring-to-markdown        0.11
docutils                     0.16
duplicity                    0.8.12.0
entrypoints                  0.3
et-xmlfile                   1.1.0
executing                    1.2.0
fasteners                    0.14.1
flake8                       6.0.0
flatbuffers                  23.1.4
future                       0.18.2
gast                         0.4.0
google-auth                  1.32.0
google-auth-oauthlib         0.4.4
google-pasta                 0.2.0
grpcio                       1.34.1
h5py                         3.1.0
html5lib                     1.0.1
httplib2                     0.14.0
idna                         2.8
imagesize                    1.2.0
importlib-metadata           1.5.0
inflection                   0.5.1
intervaltree                 3.1.0
ipykernel                    6.20.1
ipython                      8.8.0
ipython_genutils             0.2.0
isort                        4.3.4
jedi                         0.18.2
jellyfish                    0.9.0
Jinja2                       2.10.1
jinja2-time                  0.2.0
joblib                       0.14.0
jsonschema                   3.2.0
jupyter_client               7.4.8
jupyter_core                 5.1.3
keras                        2.11.0
keras-nightly                2.5.0.dev2021032900
Keras-Preprocessing          1.1.2
keyring                      18.0.1
keyrings.alt                 3.4.0
kiwisolver                   1.0.1
language-selector            0.1
launchpadlib                 1.10.13
lazr.restfulclient           0.14.2
lazr.uri                     1.0.3
lazy-object-proxy            1.4.3
libclang                     15.0.6.1
lockfile                     0.12.2
logilab-common               1.4.3
louis                        3.12.0
lxml                         4.6.3
macaroonbakery               1.3.1
Mako                         1.1.0
Markdown                     3.3.4
MarkupSafe                   1.1.0
matplotlib                   3.1.2
matplotlib-inline            0.1.6
mccabe                       0.7.0
mistune                      0.8.4
mock                         3.0.5
monotonic                    1.5
more-itertools               4.2.0
mypy-extensions              0.4.3
mysql-connector-python       8.0.15
mysqlclient                  1.4.4
nbconvert                    5.6.1
nbformat                     5.0.4
nest-asyncio                 1.5.6
netifaces                    0.10.4
nose                         1.3.7
numpy                        1.24.1
numpydoc                     0.7.0
oauth                        1.0.1
oauthlib                     3.1.0
olefile                      0.46
openpyxl                     3.0.7
opt-einsum                   3.3.0
packaging                    23.0
pandas                       1.2.5
pandocfilters                1.4.2
paramiko                     2.6.0
parso                        0.8.3
pathspec                     0.10.3
pbr                          5.4.5
pexpect                      4.6.0
pickleshare                  0.7.5
Pillow                       7.0.0
pip                          22.3.1
platformdirs                 2.6.2
pluggy                       1.0.0
prompt-toolkit               3.0.36
protobuf                     3.17.3
psutil                       5.5.1
pure-eval                    0.2.2
py                           1.8.1
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pycairo                      1.16.2
pycodestyle                  2.10.0
pycrypto                     2.6.1
pycups                       1.9.73
pydocstyle                   6.2.3
pyflakes                     3.0.1
Pygments                     2.14.0
PyGObject                    3.36.0
PyJWT                        1.7.1
pylint                       2.15.10
pylint-venv                  2.3.0
pyls-spyder                  0.4.0
pymacaroons                  0.13.0
PyNaCl                       1.3.0
pyparsing                    2.4.6
PyQt5                        5.15.7
PyQt5-Qt5                    5.15.2
PyQt5-sip                    12.11.0
PyQt6                        6.4.0
PyQt6-Qt6                    6.4.1
PyQt6-sip                    13.4.0
PyQtWebEngine                5.15.6
PyQtWebEngine-Qt5            5.15.2
pyRFC3339                    1.1
pyrsistent                   0.15.5
pysvn                        1.9.9
pytest                       4.6.9
python-apt                   2.0.0+ubuntu0.20.4.8
python-dateutil              2.8.2
python-debian                0.1.36ubuntu1
python-docx                  0.8.11
python-lsp-black             1.2.1
python-lsp-jsonrpc           1.0.0
python-lsp-server            1.7.0
python-slugify               7.0.0
pytoolconfig                 1.2.4
pytz                         2019.3
pyxdg                        0.26
PyYAML                       5.3.1
pyzmq                        25.0.0
QDarkStyle                   3.0.3
qstylizer                    0.2.2
QtAwesome                    1.2.2
qtconsole                    5.4.0
QtPy                         2.3.0
reportlab                    3.5.34
requests                     2.28.1
requests-oauthlib            1.3.0
requests-unixsocket          0.2.0
retrying                     1.3.3
roman                        2.0.0
rope                         1.6.0
rsa                          4.7.2
Rtree                        1.0.1
scikit-learn                 0.22.2.post1
scipy                        1.3.3
SecretStorage                2.3.1
setuptools                   57.0.0
simplejson                   3.16.0
sip                          4.19.21
six                          1.15.0
snowballstemmer              2.2.0
sortedcontainers             2.4.0
Sphinx                       1.8.5
spyder                       5.4.1
spyder-kernels               2.4.1
stack-data                   0.6.2
system-service               0.3
systemd-python               234
tensorboard                  2.11.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.0
tensorflow                   2.11.0
tensorflow-estimator         2.11.0
tensorflow-io-gcs-filesystem 0.29.0
termcolor                    1.1.0
testpath                     0.4.4
text-unidecode               1.3
textdistance                 4.5.0
three-merge                  0.1.1
tinycss2                     1.2.1
toml                         0.10.2
tomli                        2.0.1
tomlkit                      0.11.6
tornado                      6.2
traitlets                    5.8.1
typing_extensions            4.4.0
ubuntu-advantage-tools       27.12
ubuntu-drivers-common        0.0.0
ufw                          0.36
ujson                        5.7.0
unattended-upgrades          0.1
urllib3                      1.25.8
usb-creator                  0.3.7
wadllib                      1.3.3
watchdog                     2.2.1
wcwidth                      0.1.8
webencodings                 0.5.1
Werkzeug                     2.0.1
whatthepatch                 1.0.3
wheel                        0.36.2
wrapt                        1.12.1
wurlitzer                    3.0.3
xkit                         0.0.0
xlrd                         2.0.1
yapf                         0.32.0
zipp                         1.0.0
zope.interface               4.7.1

```
</details>

**Comment by ccordoba12** [comment]
Hey @FHJ-HM, thanks for reporting. Please see my comment on issue #20359 for a temporary fix to this problem.
