### ISSUE TITLE
cant openmy kernel

### ISSUE THREAD

**Issue by Kimsw-G** [spyder-ide/spyder#20387]
### What steps will reproduce the problem?

connecting to kernel with infinite loop
plz help me

### Traceback
```python-traceback
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\ds\anaconda3\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Users\ds\anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\ds\anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\ds\anaconda3\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Users\ds\anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\ds\anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback AddThreadSelectorEventLoop._handle_select([6680], [])
handle: <Handle AddThreadSelectorEventLoop._handle_select([6680], [])>
Traceback (most recent call last):
  File "C:\Users\ds\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ds\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 647, in _handle_select
    self._handle_event(r, self._readers)
  File "C:\Users\ds\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 661, in _handle_event
    callback()
  File "C:\Users\ds\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\ds\anaconda3\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Users\ds\anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\ds\anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\ds\anaconda3\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Users\ds\anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\ds\anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\ds\anaconda3\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Users\ds\anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\ds\anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x0000020EA69F1C10>)
Traceback (most recent call last):
  File "C:\Users\ds\anaconda3\lib\site-packages\tornado\ioloop.py", line 740, in _run_callback
    ret = callback()
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 705, in <lambda>
    self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\ds\anaconda3\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Users\ds\anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\ds\anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\ds\anaconda3\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Users\ds\anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\ds\anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\ds\anaconda3\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Users\ds\anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\ds\anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x0000020EA6A230D0>)
Traceback (most recent call last):
  File "C:\Users\ds\anaconda3\lib\site-packages\tornado\ioloop.py", line 740, in _run_callback
    ret = callback()
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 705, in <lambda>
    self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\ds\anaconda3\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Users\ds\anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\ds\anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\ds\anaconda3\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Users\ds\anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\ds\anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\ds\anaconda3\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Users\ds\anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\ds\anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x0000020EA69F5A60>)
Traceback (most recent call last):
  File "C:\Users\ds\anaconda3\lib\site-packages\tornado\ioloop.py", line 740, in _run_callback
    ret = callback()
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 705, in <lambda>
    self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\ds\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\ds\anaconda3\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Users\ds\anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\ds\anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\ds\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
```

## Versions

* Spyder version: 5.3.3  (conda)
* Python version: 3.9.15 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  65.6.3 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  25.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.6.3 (OK)
numpy >=1.7                   :  1.23.5 (OK)
pandas >=1.1.1                :  1.5.2 (OK)
scipy >=0.17.0                :  1.9.3 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by Kimsw-G** [comment]
sry i solved it
