### ISSUE TITLE
`spyder-line-profiler` fails silently with latest 5.x due to missing import in `py3compat`

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#20430]
## Problem Description

Running Spyder 5.x from `bootstrap.py` in an env with `spyder-line-profiler` 0.3.1 shows a traceback in the cmd/terminal from where Spyder was launched and the plugin doesn't load.

Maybe related with https://github.com/spyder-ide/spyder/pull/20366 and probably also affects other external plugins which rely on the `py3compat` module

### What steps reproduce the problem?

1. Install  `spyder-line-profiler` 0.3.1 
2. Run Spyder from `bootstrap.py`

### What is the expected output? What do you see instead?

The plugin to be able to load

### Paste Traceback/Error Below (if applicable)

```python-traceback
spyder_line_profiler: cannot import name 'pickle' from 'spyder.py3compat' (e:\acer\documentos\spyder\spyder\spyder\py3compat.py)
Traceback (most recent call last):
  File "e:\acer\documentos\spyder\spyder\spyder\app\find_plugins.py", line 67, in find_external_plugins
    mod = importlib.import_module(entry_point.module_name)
  File "C:\Users\dalth\anaconda3\envs\spyder-env-manager\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\dalth\anaconda3\envs\spyder-env-manager\lib\site-packages\spyder_line_profiler\spyder\plugin.py", line 29, in <module>
    from spyder_line_profiler.spyder.confpage import SpyderLineProfilerConfigPage
  File "C:\Users\dalth\anaconda3\envs\spyder-env-manager\lib\site-packages\spyder_line_profiler\spyder\confpage.py", line 19, in <module>
    from .widgets import SpyderLineProfilerWidget
  File "C:\Users\dalth\anaconda3\envs\spyder-env-manager\lib\site-packages\spyder_line_profiler\spyder\widgets.py", line 38, in <module>
    from spyder.py3compat import to_text_string, pickle
ImportError: cannot import name 'pickle' from 'spyder.py3compat' (e:\acer\documentos\spyder\spyder\spyder\py3compat.py)
```

## Versions

* Spyder version: 5.5.0.dev0 4a5d86ecd (conda)
* Python version: 3.9.15 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

**Comment by ccordoba12** [comment]
Thanks @dalthviz for reporting. I didn't know external plugins were importing directly from our `py3compat` module, which I think it's really bad because that's not public API. Fortunately, this is easy to solve: we only need to restore the missing `pickle` import in `py3compat` and remove it in `master`, which I'll do right away so that previous versions of `spyder-line-profiler` don't break.

I also quickly checked if the other external plugins we maintain (unittest, terminal, vim and notebook) import from `py3compat`, but fortunately they don't.

**Comment by ccordoba12** [comment]
@dalthviz, could you also open a PR in `spyder-line-profiler` to remove all references to `py3compat`? That way that plugin will be ready when we remove that module in Spyder 6.
