### ISSUE TITLE
Error running external system terminal with current working directory setting

### ISSUE THREAD

**Issue by cdfredrick** [spyder-ide/spyder#20432]
### What steps will reproduce the problem?

An internal Spyder error is produced when trying to run a file with the "Run configuration per file" set for excecution in an external system terminal with the working directory set to the current working directory. There are no problems when using the directory of the file being excecuted or a user input directory as the working directory.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\default\Lib\site-packages\spyder\plugins\editor\plugin.py", line 2972, in edit_run_configurations
    self.run_file()
  File "C:\Users\User\miniconda3\envs\default\Lib\site-packages\spyder\plugins\editor\plugin.py", line 3038, in run_file
    self.re_run_file(save_new_files=False)
  File "C:\Users\User\miniconda3\envs\default\Lib\site-packages\spyder\plugins\editor\plugin.py", line 3073, in re_run_file
    self.main.open_external_console(
  File "C:\Users\User\miniconda3\envs\default\Lib\site-packages\spyder\app\mainwindow.py", line 1490, in open_external_console
    programs.run_python_script_in_terminal(
  File "C:\Users\User\miniconda3\envs\default\Lib\site-packages\spyder\utils\programs.py", line 748, in run_python_script_in_terminal
    if osp.splitdrive(wdir)[0].startswith("\\\\"): #UNC paths start with \\
       ^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 169, in splitdrive
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

## Versions

* Spyder version: 5.4.2  (conda)
* Python version: 3.11.0 64-bit
* Qt version: 5.15.6
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.1.0 (OK)
cloudpickle >=0.5.0           :  2.2.1 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<9.0.0       :  8.8.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.13.1 (OK)
nbconvert >=4.0               :  7.2.9 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  2.12.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.4 (OK)
pygments >=2.0                :  2.14.0 (OK)
pylint >=2.5.0;<3.0           :  2.15.10 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0          :  1.7.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.3.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  66.1.1 (OK)
sphinx >=0.6.6                :  6.1.3 (OK)
spyder_kernels >=2.4.2;<2.5.0 :  2.4.2 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.2.1 (OK)
zmq >=22.1.0                  :  25.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.6.3 (OK)
numpy >=1.7                   :  1.24.1 (OK)
pandas >=1.1.1                :  1.5.3 (OK)
scipy >=0.17.0                :  1.10.0 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @cdfredrick, thanks for reporting. This problem was reported before and we'll fix it in our next version (5.4.3), to be released in March. In the meantime, please avoid running files with the configuration you mentioned to not encounter it again.
