### ISSUE TITLE
Spyder won't launch, on only 1 of 4 comparably configured Windows machines

### ISSUE THREAD

**Issue by mcovington** [spyder-ide/spyder#20461]
## Problem Description

Spyder shows its splash screen briefly, then vanishes.  If launched from within Navigator or from the command line, it produces the error messages that are at the end of this report.

### What steps reproduce the problem?

1.  Download and install Anaconda3 for Windows (64-bit) on a Windows 10 machine that already has Python 3.11 installed and on its path.  Take recommended settings (Anaconda not on path, Anaconda installed for me only).  Then `conda update anaconda` and `conda update spyder`.  (NOTE: I have tried many variations of the installation options.  Only one of my 4 computers is affected, and the others appear to be comparably configured in all the ways I am aware of.)

2. Launch Spyder, from icon, from within Navigator, or from command line at a Conda prompt.

3.  See above.  Splash screen appears for a few seconds and goes away.  In Navigator or command line, there are error messages.
 

### What is the expected output? What do you see instead?

See above.

### Paste Traceback/Error Below (if applicable)

```
(base) C:\Users\Michael>spyder
fromIccProfile: failed minimal tag size sanity
C:\Users\Michael\anaconda3\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Traceback (most recent call last):
  File "C:\Users\Michael\anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Michael\anaconda3\lib\site-packages\spyder\app\start.py", line 252, in main
    mainwindow.main(options, args)
  File "C:\Users\Michael\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1956, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "C:\Users\Michael\anaconda3\lib\site-packages\spyder\app\utils.py", line 289, in create_window
    main.setup()
  File "C:\Users\Michael\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 736, in setup
    internal_plugins = find_internal_plugins()
  File "C:\Users\Michael\anaconda3\lib\site-packages\spyder\app\find_plugins.py", line 40, in find_internal_plugins
    mod = importlib.import_module(entry_point.module_name)
  File "C:\Users\Michael\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Michael\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 24, in <module>
    from spyder.plugins.ipythonconsole.widgets.main_widget import (
  File "C:\Users\Michael\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 38, in <module>
    from spyder.plugins.ipythonconsole.utils.manager import SpyderKernelManager
  File "C:\Users\Michael\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\utils\manager.py", line 16, in <module>
    from jupyter_client.utils import run_sync
ModuleNotFoundError: No module named 'jupyter_client.utils'
```

## Versions

* Spyder version:  5.3.3
* Python version:   3.9.13
* Qt version:  5.15.7
* PyQt version:  5.15.7
* Operating System name/version:  Windows 10 Professional (64-bit) fully updated

### Dependencies

Cannot launch Spyder and so cannot use this menu option.

**Comment by ccordoba12** [comment]
Hey @mcovington, thanks for reporting. This could be caused because you have another installation of `jupyter_client` in your affected computer.

So, please run a wide search for `jupyter_client` in your computer and remove any folder with that name that's outside of your Anaconda installation.

**Comment by mcovington** [comment]
Thanks, @ccordoba12 .   I found it under %appdata%\Roaming\Python\Python39, apparently left over from an old Visual Studio install that included parts of Anaconda.   Removing all of %appdata%\Roaming\Python cleared up the problem.  I wonder if the Anaconda installer should check for this situation.
