### ISSUE TITLE
internal problem

### ISSUE THREAD

**Issue by S-Lute** [spyder-ide/spyder#20484]
### What steps will reproduce the problem?

TypeError: object list can't be used in 'await' expression

### Traceback
```python-traceback
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/Users/saralute/.local/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/Users/saralute/.local/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x7f77bfe740d0>)
Traceback (most recent call last):
  File "/Users/saralute/.local/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 705, in <lambda>
    self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/Users/saralute/.local/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/Users/saralute/.local/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/Users/saralute/.local/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback BaseAsyncIOLoop._handle_events(95, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(95, 1)>
Traceback (most recent call last):
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/saralute/.local/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/Users/saralute/.local/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/Users/saralute/.local/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/Users/saralute/.local/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback BaseAsyncIOLoop._handle_events(177, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(177, 1)>
Traceback (most recent call last):
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/saralute/.local/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/Users/saralute/.local/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/Users/saralute/.local/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/Users/saralute/.local/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback BaseAsyncIOLoop._handle_events(175, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(175, 1)>
Traceback (most recent call last):
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/saralute/.local/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/saralute/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 124, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/Users/saralute/.local/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/saralute/opt/anaconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/saralute/.local/lib/python3.9/site-packages/jupyter_client/threaded.py", line 35, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Darwin 22.2.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.8.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.2 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.4 (OK)
pygments >=2.0                :  2.14.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.0 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  25.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @S-Lute, thanks for reporting. You have some extra packages outside of your Anaconda installation which are interfering with it and causing this problem. To fix it, please open a terminal and run there:

    rm - Rf /Users/saralute/.local/lib/python3.9

which will effectively remove those packages.

We also recommend you to update to our latest version available in Anaconda (5.3.3) to have a much better experience. For that, please close Spyder, open a terminal and run there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).
