### ISSUE TITLE
Pandas Dataframe not opening in Variable Explorer

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2049]
_From [cheezep...@googlemail.com](https://code.google.com/u/112596313778178449620/) on 2014-11-13T13:06:54Z_

Spyder Version:  2.3.1
Python Version:  2.7.8
Qt Version    :  4.8.5, PyQt4 (API v2) 4.10.4 on Linux
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.6 (OK)
IPython >=0.13  :  2.3.0 (OK)
pygments >=1.6  :  1.6 (OK)
pandas >=0.13.1 :  0.15.1 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.1.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1. having pandas version 0.15 (problem was not appearing with earlier verions)
2. loading pandas dataframe (a stata dataset in this case)
3. trying to open the dataframe object within the variable explorer

This is the error messsage:

Traceback (most recent call last):
  File "/usr/local/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dicteditor.py", line 411, in createEditor
    if not editor.setup_and_check(value):
  File "/usr/local/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dataframeeditor.py", line 409, in setup_and_check
    self.dataModel = DataFrameModel(data, parent=self)
  File "/usr/local/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dataframeeditor.py", line 75, in __init__
    self.max_min_col_update()
  File "/usr/local/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dataframeeditor.py", line 90, in max_min_col_update
    df_abs = self.df[self.complex_intran].abs()
  File "/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 1776, in __getitem__
    return self._getitem_frame(key)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 1849, in _getitem_frame
    return self.where(key)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 3348, in where
    try_cast=try_cast)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 2515, in where
    return self.apply('where', **kwargs)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 2497, in apply
    applied = getattr(b, f)(**kwargs)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 1105, in where
    ndim=self.ndim, placement=self.mgr_locs)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 2139, in make_block
    placement=placement)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 1439, in __init__
    placement=placement)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 76, in __init__
    len(self.values), len(self.mgr_locs)))
ValueError: Wrong number of items passed 3340, placement implies 1
Traceback (most recent call last):
  File "/usr/local/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dicteditor.py", line 411, in createEditor
    if not editor.setup_and_check(value):
  File "/usr/local/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dataframeeditor.py", line 409, in setup_and_check
    self.dataModel = DataFrameModel(data, parent=self)
  File "/usr/local/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dataframeeditor.py", line 75, in __init__
    self.max_min_col_update()
  File "/usr/local/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dataframeeditor.py", line 90, in max_min_col_update
    df_abs = self.df[self.complex_intran].abs()
  File "/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 1776, in __getitem__
    return self._getitem_frame(key)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 1849, in _getitem_frame
    return self.where(key)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 3348, in where
    try_cast=try_cast)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 2515, in where
    return self.apply('where', **kwargs)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 2497, in apply
    applied = getattr(b, f)(**kwargs)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 1105, in where
    ndim=self.ndim, placement=self.mgr_locs)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 2139, in make_block
    placement=placement)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 1439, in __init__
    placement=placement)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 76, in __init__
    len(self.values), len(self.mgr_locs)))
ValueError: Wrong number of items passed 3340, placement implies 1

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2049_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-15T09:32:48Z_

Please upload a dataset that's showing the problem and we can test in our side to fix it.

Daniel, do you know what could be happening?

**Cc:** dhoeg...@gmail.com  
  **Labels:** -pandas Cat-VariableExplorer MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [dhoeg...@gmail.com](https://code.google.com/u/100712947103652895129/) on 2014-11-15T10:42:37Z_

cheezeplay could you try and open dataframeeditor.py and run the file, and se if the test cases also fail under pandas 0.15?

**Comment by spyder-issues-migrator** [comment]
_From [cheezep...@googlemail.com](https://code.google.com/u/112596313778178449620/) on 2014-11-15T11:17:44Z_

Thank you for your fast responses. The file attached is the one which created problems for me. dhoeg could u please explain me how to do this? I have no clue unfortunately. I know for sure that the issues was not appearing with pandas 14.1.

**Attachment:** [allbus2012.dta](http://code.google.com/p/spyderlib/issues/detail?id=2049#hc3)

**Comment by spyder-issues-migrator** [comment]
_From [dhoeg...@gmail.com](https://code.google.com/u/100712947103652895129/) on 2014-11-15T11:23:46Z_

If you with spyder open this file: /usr/local/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dataframeeditor.py
and then just run the file in spyder (F5), then there will pop som dataframe views op, just press ok until no more dataframe views pops up, does this produce any errors in the terminal?

**Comment by spyder-issues-migrator** [comment]
_From [dhoeg...@gmail.com](https://code.google.com/u/100712947103652895129/) on 2014-11-15T12:12:42Z_

How should the data be loaded?

**Comment by spyder-issues-migrator** [comment]
_From [cheezep...@googlemail.com](https://code.google.com/u/112596313778178449620/) on 2014-11-15T12:24:05Z_

you can open the file with the following code:

import scipy
import pandas as pd

reader = pd.io.stata.StataReader(path3/allbus2012.dta")
d =reader.data(convert_categoricals=False)

after that try to open the datafame in the variable explorer and u should see the error with the latest panda version.

**Comment by spyder-issues-migrator** [comment]
_From [cheezep...@googlemail.com](https://code.google.com/u/112596313778178449620/) on 2014-11-15T12:26:10Z_

i got no errors when following your description and running dataframeeditor.py, every df opened without problems.

**Comment by spyder-issues-migrator** [comment]
_From [dhoeg...@gmail.com](https://code.google.com/u/100712947103652895129/) on 2014-11-15T14:08:22Z_

I just tried with python 3.4 on windows and I cannot reproduce the problem with pandas 0.15 on the data set you sent.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-20T08:38:19Z_

This issue was closed by revision f993e0d3e40c .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-20T08:40:49Z_

Although I was not able to reproduce your problem, I took the opportunity to add further optimizations to our DataFrames viewer: now it not only loads rows in demand but also columns.

Besides, it doesn't add background colors if the size if bigger than 5e5 to improve responsiveness.
