### ISSUE TITLE
spyder-vim problem

### ISSUE THREAD

**Issue by clip222** [spyder-ide/spyder#20513]
### What steps will reproduce the problem?

spyder-vim using visual command "a p to insert buffer after a :y a command

### Traceback
```python-traceback
Traceback (most recent call last):
  File "c:\users\c16825\anaconda3\envs\crypto\lib\site-packages\spyder_vim\spyder\widgets.py", line 1609, in on_text_changed
    self.vim_keys(key, repeat)
  File "c:\users\c16825\anaconda3\envs\crypto\lib\site-packages\spyder_vim\spyder\widgets.py", line 101, in __call__
    method(repeat=repeat)
  File "c:\users\c16825\anaconda3\envs\crypto\lib\site-packages\spyder_vim\spyder\widgets.py", line 1138, in p
    self.P()
TypeError: VimKeys.P() missing 1 required positional argument: 'repeat'
```

## Versions

* Spyder version: 5.3.3  (conda)
* Python version: 3.10.9 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.0.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0              :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.16.0 (OK)
keyring >=17.0.0                     :  23.4.0 (OK)
nbconvert >=4.0                      :  6.5.4 (OK)
numpydoc >=0.6.0                     :  1.5.0 (OK)
paramiko >=2.4.0                     :  2.8.1 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.0 (OK)
pygments >=2.0                       :  2.11.2 (OK)
pylint >=2.5.0;<3.0                  :  2.14.5 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0                 :  1.5.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.2 (OK)
qstylizer >=0.1.10                   :  0.2.2 (OK)
qtawesome >=1.0.2                    :  1.2.2 (OK)
qtconsole >=5.3.2;<5.4.0             :  5.3.2 (OK)
qtpy >=2.1.0                         :  2.2.0 (OK)
rtree >=0.9.7                        :  0.9.7 (OK)
setuptools >=49.6.0                  :  65.6.3 (OK)
sphinx >=0.6.6                       :  5.0.2 (OK)
spyder_kernels >=2.3.3;<2.4.0        :  2.3.3 (OK)
textdistance >=4.2.0                 :  4.2.1 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.6 (OK)
zmq >=22.1.0                         :  23.2.0 (OK)

# Optional:
cython >=0.21                        :  0.29.32 (OK)
matplotlib >=3.0.0                   :  3.6.2 (OK)
numpy >=1.7                          :  1.21.5 (OK)
pandas >=1.1.1                       :  1.5.2 (OK)
scipy >=0.17.0                       :  1.9.3 (OK)
sympy >=0.7.3                        :  1.11.1 (OK)

# Spyder plugins:
spyder_notebook.notebookplugin 0.4.0 :  0.4.0 (OK)
spyder_vim.spyder.plugin 0.1.0       :  0.1.0 (OK)
```

**Comment by ccordoba12** [comment]
Hey @clip222, thanks for reporting. I'm going to move this bug report to it respective repo.
