### ISSUE TITLE
Python_Pytorch has a problem

### ISSUE THREAD

**Issue by study-cnn-lstm** [spyder-ide/spyder#20577]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 60, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 330, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 127, in get_cwd
    self.silent_exec_method(code)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 330, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.15
* Qt Versions: 5.12.9, PyQt5 5.12.3 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  3.0.1 (OK)
pycodestyle >=2.3:  2.10.0 (OK)
pygments >=2.0   :  2.14.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.19.5 (OK)
sphinx >=0.6.6   :  5.1.1 (OK)
rope >=0.9.4     :  1.1.1 (OK)
jedi >=0.9.0     :  0.17.2 (OK)
nbconvert >=4.0  :  6.0.7 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  5.2.2 (OK)
IPython >=4.0    :  7.16.1 (OK)
pylint >=0.25    :  2.11.1 (OK)

```

**Comment by ccordoba12** [comment]
Hey @study-cnn-lstm, thanks for reporting. This problem is fixed in our latest version available in Anaconda (5.3.3). Please update by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).

If those commands fail to work for you, I'm afraid you'll have to remove your current Anaconda installation, download its latest version and install it again.
