### ISSUE TITLE
Unable to Lanch spyder in ubuntu

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2057]
_From [yaswanth.gavini](https://code.google.com/u/yaswanth.gavini/) on 2014-11-18T23:23:02Z_

When i open it return error like this
Traceback (most recent call last):
  File "/usr/bin/spyder", line 2, in \<module>
    from spyderlib import spyder
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 87, in \<module>
    from spyderlib.utils.environ import WinUserEnvDialog
  File "/usr/lib/python2.7/dist-packages/spyderlib/utils/environ.py", line 17, in \<module>
    from spyderlib.widgets.dicteditor import DictEditor
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/dicteditor.py", line 31, in \<module>
    from spyderlib.config import get_icon, get_font
  File "/usr/lib/python2.7/dist-packages/spyderlib/config.py", line 27, in \<module>
    from spyderlib.utils import iofuncs, codeanalysis
  File "/usr/lib/python2.7/dist-packages/spyderlib/utils/iofuncs.py", line 61, in \<module>
    import numpy as np
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 137, in \<module>
    import add_newdocs
  File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 9, in \<module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 13, in \<module>
    from polynomial import *
  File "/usr/lib/python2.7/dist-packages/numpy/lib/polynomial.py", line 11, in \<module>
    import numpy.core.numeric as NX
AttributeError: 'module' object has no attribute 'core'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2057_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-19T10:21:07Z_

What's your Ubuntu version?

**Labels:** OpSys-Linux

**Comment by spyder-issues-migrator** [comment]
_From [yaswanth.gavini](https://code.google.com/u/yaswanth.gavini/) on 2014-11-19T20:16:12Z_

Ubuntu vertion is !2.04LST

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-01T14:53:59Z_

This doesn't seem a problem in Spyder. Have you been able to solve it?

**Comment by spyder-issues-migrator** [comment]
_From [yaswanth.gavini](https://code.google.com/u/yaswanth.gavini/) on 2015-01-01T21:30:19Z_

Yes, This problem is solved after reinstallation of Qt, liblapack, libblas

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-02T17:38:30Z_

Thanks for letting us know and happy coding :-)

**Status:** Invalid
