### ISSUE TITLE
Issue occurring intemittently in Spyder

### ISSUE THREAD

**Issue by YYahiaoui** [spyder-ide/spyder#20591]
### What steps will reproduce the problem?

Bad pipe message: %s [b'\x0c\xeb}\x87P\x99`\xbb\xda\xe3\x89\xeb\xf7\xc3\x8a\x1b\xa2\xf8\x00\x01p\x00\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00\x07\x00\x08\x00\t\x00\n\x00\x0b\x00\x0c\x00\r\x00\x0e\x00\x0f\x00\x10\x00\x11\x00\x12\x00\x13\x00\x14\x00\x15\x00\x16\x00\x17\x00\x18\x00\x19\x00\x1a\x00\x1b\x00/\x000\x001\x002\x003\x004\x005\x006\x007\x008\x009\x00:\x00;\x00<\x00=\x00>\x00?\x00@\x00g\x00h\x00i\x00j\x00k\x00l\x00m\x00A\x00B\x00C\x00D\x00E\x00F\x00\x84\x00\x85\x00\x86\x00\x87\x00\x88\x00\x89\x00\xba\x00\xbb\x00\xbc\x00\xbd\x00\xbe\x00\xbf\x00\xc0\x00\xc1\x00\xc2\x00\xc3\x00\xc4\x00\xc5\x00\x9c\x00\x9d\x00\x9e\x00\x9f\x00\xa0\x00\xa1\x00\xa2\x00\xa3\x00\xa4\x00\xa5\x00\xa6\x00\xa7\xc0\x01\xc0\x02\xc0\x03\xc0\x04\xc0\x05\xc0\x06\xc0\x07\xc0\x08\xc0\t\xc0\n\xc0\x0b\xc0\x0c\xc0\r\xc0']
Bad pipe message: %s [b'\x0f\xc0\x10\xc0\x11\xc0\x12\xc0\x13\xc0\x14\xc0\x15']
Bad pipe message: %s [b'\xb2\xa8H\x08\xcfN8\x86\xe6\xa4\x140i\xc1\xc2\x8b\xb1}\x00\x01p\x00\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00\x07\x00\x08\x00\t\x00\n\x00\x0b\x00\x0c\x00\r\x00\x0e\x00\x0f\x00\x10\x00\x11\x00\x12\x00\x13\x00\x14\x00\x15\x00\x16\x00\x17\x00']
Bad pipe message: %s [b'\x19\x00\x1a\x00\x1b\x00/\x000\x001\x002\x003\x004\x005\x006\x007']

Bad pipe message: %s [b'\x0c\xeb}\x87P\x99`\xbb\xda\xe3\x89\xeb\xf7\xc3\x8a\x1b\xa2\xf8\x00\x01p\x00\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00\x07\x00\x08\x00\t\x00\n\x00\x0b\x00\x0c\x00\r\x00\x0e\x00\x0f\x00\x10\x00\x11\x00\x12\x00\x13\x00\x14\x00\x15\x00\x16\x00\x17\x00\x18\x00\x19\x00\x1a\x00\x1b\x00/\x000\x001\x002\x003\x004\x005\x006\x007\x008\x009\x00:\x00;\x00<\x00=\x00>\x00?\x00@\x00g\x00h\x00i\x00j\x00k\x00l\x00m\x00A\x00B\x00C\x00D\x00E\x00F\x00\x84\x00\x85\x00\x86\x00\x87\x00\x88\x00\x89\x00\xba\x00\xbb\x00\xbc\x00\xbd\x00\xbe\x00\xbf\x00\xc0\x00\xc1\x00\xc2\x00\xc3\x00\xc4\x00\xc5\x00\x9c\x00\x9d\x00\x9e\x00\x9f\x00\xa0\x00\xa1\x00\xa2\x00\xa3\x00\xa4\x00\xa5\x00\xa6\x00\xa7\xc0\x01\xc0\x02\xc0\x03\xc0\x04\xc0\x05\xc0\x06\xc0\x07\xc0\x08\xc0\t\xc0\n\xc0\x0b\xc0\x0c\xc0\r\xc0']
Bad pipe message: %s [b'\x0f\xc0\x10\xc0\x11\xc0\x12\xc0\x13\xc0\x14\xc0\x15']
Bad pipe message: %s [b'\xb2\xa8H\x08\xcfN8\x86\xe6\xa4\x140i\xc1\xc2\x8b\xb1}\x00\x01p\x00\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00\x07\x00\x08\x00\t\x00\n\x00\x0b\x00\x0c\x00\r\x00\x0e\x00\x0f\x00\x10\x00\x11\x00\x12\x00\x13\x00\x14\x00\x15\x00\x16\x00\x17\x00']
Bad pipe message: %s [b'\x19\x00\x1a\x00\x1b\x00/\x000\x001\x002\x003\x004\x005\x006\x007']
[SpyderKernelApp] ERROR | Error in message handler
Traceback (most recent call last):
  File "C:\Users\C18196\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 471, in dispatch_queue
    await self.process_one()
  File "C:\Users\C18196\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 460, in process_one
    await dispatch(*args)
  File "C:\Users\C18196\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 324, in dispatch_shell
    idents, msg = self.session.feed_identities(msg, copy=False)
  File "C:\Users\C18196\Anaconda3\lib\site-packages\jupyter_client\session.py", line 859, in feed_identities
    raise ValueError("DELIM not in msg_list")
ValueError: DELIM not in msg_list
[SpyderKernelApp] ERROR | Error in message handler
Traceback (most recent call last):
  File "C:\Users\C18196\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 471, in dispatch_queue
    await self.process_one()
  File "C:\Users\C18196\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 460, in process_one
    await dispatch(*args)
  File "C:\Users\C18196\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 324, in dispatch_shell
    idents, msg = self.session.feed_identities(msg, copy=False)
  File "C:\Users\C18196\Anaconda3\lib\site-packages\jupyter_client\session.py", line 859, in feed_identities
    raise ValueError("DELIM not in msg_list")
ValueError: DELIM not in msg_list
[SpyderKernelApp] ERROR | Error in message handler
Traceback (most recent call last):
  File "C:\Users\C18196\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 471, in dispatch_queue
    await self.process_one()
  File "C:\Users\C18196\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 460, in process_one
    await dispatch(*args)
  File "C:\Users\C18196\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 324, in dispatch_shell
    idents, msg = self.session.feed_identities(msg, copy=False)
  File "C:\Users\C18196\Anaconda3\lib\site-packages\jupyter_client\session.py", line 859, in feed_identities
    raise ValueError("DELIM not in msg_list")
ValueError: DELIM not in msg_list

Bad pipe message: %s [b'\x0c\xeb}\x87P\x99`\xbb\xda\xe3\x89\xeb\xf7\xc3\x8a\x1b\xa2\xf8\x00\x01p\x00\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00\x07\x00\x08\x00\t\x00\n\x00\x0b\x00\x0c\x00\r\x00\x0e\x00\x0f\x00\x10\x00\x11\x00\x12\x00\x13\x00\x14\x00\x15\x00\x16\x00\x17\x00\x18\x00\x19\x00\x1a\x00\x1b\x00/\x000\x001\x002\x003\x004\x005\x006\x007\x008\x009\x00:\x00;\x00<\x00=\x00>\x00?\x00@\x00g\x00h\x00i\x00j\x00k\x00l\x00m\x00A\x00B\x00C\x00D\x00E\x00F\x00\x84\x00\x85\x00\x86\x00\x87\x00\x88\x00\x89\x00\xba\x00\xbb\x00\xbc\x00\xbd\x00\xbe\x00\xbf\x00\xc0\x00\xc1\x00\xc2\x00\xc3\x00\xc4\x00\xc5\x00\x9c\x00\x9d\x00\x9e\x00\x9f\x00\xa0\x00\xa1\x00\xa2\x00\xa3\x00\xa4\x00\xa5\x00\xa6\x00\xa7\xc0\x01\xc0\x02\xc0\x03\xc0\x04\xc0\x05\xc0\x06\xc0\x07\xc0\x08\xc0\t\xc0\n\xc0\x0b\xc0\x0c\xc0\r\xc0']
Bad pipe message: %s [b'\x0f\xc0\x10\xc0\x11\xc0\x12\xc0\x13\xc0\x14\xc0\x15']
Bad pipe message: %s [b'\xb2\xa8H\x08\xcfN8\x86\xe6\xa4\x140i\xc1\xc2\x8b\xb1}\x00\x01p\x00\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00\x07\x00\x08\x00\t\x00\n\x00\x0b\x00\x0c\x00\r\x00\x0e\x00\x0f\x00\x10\x00\x11\x00\x12\x00\x13\x00\x14\x00\x15\x00\x16\x00\x17\x00']
Bad pipe message: %s [b'\x19\x00\x1a\x00\x1b\x00/\x000\x001\x002\x003\x004\x005\x006\x007']
[SpyderKernelApp] ERROR | Error in message handler
Traceback (most recent call last):
  File "C:\Users\C18196\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 471, in dispatch_queue
    await self.process_one()
  File "C:\Users\C18196\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 460, in process_one
    await dispatch(*args)
  File "C:\Users\C18196\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 324, in dispatch_shell
    idents, msg = self.session.feed_identities(msg, copy=False)
  File "C:\Users\C18196\Anaconda3\lib\site-packages\jupyter_client\session.py", line 859, in feed_identities
    raise ValueError("DELIM not in msg_list")
ValueError: DELIM not in msg_list
[SpyderKernelApp] ERROR | Error in message handler
Traceback (most recent call last):
  File "C:\Users\C18196\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 471, in dispatch_queue
    await self.process_one()
  File "C:\Users\C18196\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 460, in process_one
    await dispatch(*args)
  File "C:\Users\C18196\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 324, in dispatch_shell
    idents, msg = self.session.feed_identities(msg, copy=False)
  File "C:\Users\C18196\Anaconda3\lib\site-packages\jupyter_client\session.py", line 859, in feed_identities
    raise ValueError("DELIM not in msg_list")
ValueError: DELIM not in msg_list
[SpyderKernelApp] ERROR | Error in message handler
Traceback (most recent call last):
  File "C:\Users\C18196\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 471, in dispatch_queue
    await self.process_one()
  File "C:\Users\C18196\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 460, in process_one
    await dispatch(*args)
  File "C:\Users\C18196\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 324, in dispatch_shell
    idents, msg = self.session.feed_identities(msg, copy=False)
  File "C:\Users\C18196\Anaconda3\lib\site-packages\jupyter_client\session.py", line 859, in feed_identities
    raise ValueError("DELIM not in msg_list")
ValueError: DELIM not in msg_list
[SpyderKernelApp] WARNING | Invalid Message:
Traceback (most recent call last):
  File "C:\Users\C18196\Anaconda3\lib\site-packages\spyder_kernels\comms\frontendcomm.py", line 135, in poll_one
    ident, msg = self.kernel.session.recv(self.comm_socket, 0)
  File "C:\Users\C18196\Anaconda3\lib\site-packages\jupyter_client\session.py", line 819, in recv
    idents, msg_list = self.feed_identities(msg_list, copy)
  File "C:\Users\C18196\Anaconda3\lib\site-packages\jupyter_client\session.py", line 850, in feed_identities
    idx = msg_list.index(DELIM)
ValueError: b'<IDS|MSG>' is not in list
[SpyderKernelApp] WARNING | Invalid Message:
Traceback (most recent call last):
  File "C:\Users\C18196\Anaconda3\lib\site-packages\spyder_kernels\comms\frontendcomm.py", line 135, in poll_one
    ident, msg = self.kernel.session.recv(self.comm_socket, 0)
  File "C:\Users\C18196\Anaconda3\lib\site-packages\jupyter_client\session.py", line 819, in recv
    idents, msg_list = self.feed_identities(msg_list, copy)
  File "C:\Users\C18196\Anaconda3\lib\site-packages\jupyter_client\session.py", line 850, in feed_identities
    idx = msg_list.index(DELIM)
ValueError: b'<IDS|MSG>' is not in list

### Traceback
```python-traceback
Exception in thread Thread-11:
Traceback (most recent call last):
  File "C:\Users\C18196\Anaconda3\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\C18196\Anaconda3\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\C18196\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1837, in start_open_files_server
    fname = fname.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 4: invalid start byte
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.2.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.0 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @YYahiaoui, thanks for reporting. This problem could be fixed in our latest version available in Anaconda (5.3.3). Please update by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).

Let us know if that works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by iojjjjiiii** [comment]
I'm getting this in 5.4.3. Restarting the kernel makes it go away, but it returns after the kernel is left running for a while.

**Comment by ccordoba12** [comment]
@iojjjjiiii, this could be an issue with your firewall or antivirus ending the connection between Spyder and the console after a while.

**Comment by iojjjjiiii** [comment]
> @iojjjjiiii, this could be an issue with your firewall or antivirus ending the connection between Spyder and the console after a while.

OK, that actually makes sense, as it would explain why I am getting this error on two different company computers, but never at home. I guess not much can be done about it, since I don't control firewall/antivirus settings at work. Thanks for the tip all the same.
