### ISSUE TITLE
Unable to turn off kite

### ISSUE THREAD

**Issue by Briley645** [spyder-ide/spyder#20594]
### What steps will reproduce the problem?

I'm trying to troubleshoot other issues with Spyder. The current version (5.3.3 i think) gives an error about not finding the path when launching the kernel inside any conda env besides my base. That issue doesn't seem to happen in 5.2 all else being the same, but now I'm having issues with linting notifications. They either don't show up or show up but don't update. I tried resetting spyder defaults and conda updating dependencies, allowing firewall, etc.

I remember having problems with Kite in a previous version so I thought I'd try to disable it.

Every time I uncheck "Enable Kite provider" I get an error message. I can reset the defaults and let this be the first setting I change and I still get an error.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\brile\anaconda3\lib\site-packages\spyder\plugins\preferences\widgets\configdialog.py", line 136, in button_clicked
    configpage.apply_changes()
  File "C:\Users\brile\anaconda3\lib\site-packages\spyder\plugins\preferences\api.py", line 108, in apply_changes
    self.apply_callback()
  File "C:\Users\brile\anaconda3\lib\site-packages\spyder\plugins\preferences\api.py", line 140, in <lambda>
    self._apply_settings_tabs(self.changed_options))
  File "C:\Users\brile\anaconda3\lib\site-packages\spyder\plugins\preferences\api.py", line 168, in _apply_settings_tabs
    self.apply_settings(options)
  File "C:\Users\brile\anaconda3\lib\site-packages\spyder\api\preferences.py", line 105, in wrapper
    func(opts)
  File "C:\Users\brile\anaconda3\lib\site-packages\spyder\api\plugins\new_api.py", line 550, in apply_conf
    self.after_configuration_update(list(options_set))
  File "C:\Users\brile\anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 403, in after_configuration_update
    self.unregister_statusbar(provider_name)
  File "C:\Users\brile\anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 477, in unregister_statusbar
    if id_ in container.statusbar_widgets[id_]:
TypeError: argument of type 'KiteStatusWidget' is not iterable
```

## Versions

* Spyder version: 5.2.2 
* Python version: 3.9.16
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.16.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.2 (OK)
qtawesome >=1.0.2             :  1.2.2 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.6.3 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.33 (OK)
matplotlib >=2.0.0            :  3.6.2 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.4 (OK)
scipy >=0.17.0                :  1.10.0 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)
```

**Comment by Briley645** [comment]
Update: I installed 5.1.5 and it resolved:
1. No issues w/ connecting kernel in other environments.
2. No issues disabling Kite.
3. Code linting works perfectly.

So far 5.1.5 seems to work great for me, but I have progressively worse issues in 5.2 and 5.3.

**Comment by dalthviz** [comment]
Hi @Briley645 thank you for the feedback! Could it be possible for you to create a new conda environment using the conda-forge channel ? With that you will get the latest Spyder release (5.4.2) which maybe could solve the problem with your conda envs.

To prevent the error when disabling Kite you will need to use at least Spyder 5.3.0. The related issue https://github.com/spyder-ide/spyder/issues/17262 was fixed in that version and also, after version 5.3.0, Kite is completly disabled from inside Spyder.

Also, with Spyder 5.3.3 what is exactly the error that you get related to not finding the path? Could it be related to https://github.com/spyder-ide/spyder/issues/16562

Any new info you could give us in order to see better understand the path issue you are experiencing and the check if it is still present in the latest Spyder version will be greatly appreciated!

**Comment by chriswilly** [comment]
Hi,
I've uninstalled anaconda and spyder entirely. I am using Mac OS with a python.org dist using python -m pip for any dependencies.

I keep getting a ~/.kite dot folder that is recreated if I delete it. I've scrubbed /Library/Launchdaemons and /Library/Launchagents & userspace ~/Applications/ or ~/Library/Launchagents, the obvious areas for application utils to be running a login or background service.

Since kite.com decided to remove the uninstall command line instructions from their site (that I followed in the past), I'd like to ask Spyder devs to help troubleshoot complete removal of Kite. Spyder opted me in by default for a closed source monitoring tool that was missed deselecting when troubleshooting an anaconda install.

Please help remove kite entirely from my mac OS. Please provide known install locations and any CLI prompts to ensure I do not have an unauthorized background service running. Spyder needs to take responsibility for bundling of that software and opting users in by default.

Thank you,

Michael

**Comment by dalthviz** [comment]
Hi @chriswilly sorry for the inconvenience there, maybe this could be useful for you: https://gist.github.com/tangoabcdelta/cec7514e3ef13d50a50bfc5e22f8d00f 

Let us know if the steps there help!

**Comment by chriswilly** [comment]
Hi, thank you for the instructions link! That is along the lines of what I was looking for.

If anything it'd be great if there is documentation for posterity of what CLI commands are in this install path because I'd previously uninstalled and rm -rf'ed one userspace dir.

    ~/.local/share/kite/uninstall
    
This referenced link to uninstall all editor plugins was dead https://help.kite.com/article/62-managing-editor-plugins but I followed the contents of Kite instructions back in 2021. 

# Solution:

I found a residual kite dir under ~/.vim/pack/ and reproduced creating a ~/.kite dir by launching vi! That explains the randomness of the ~/.kite dir popping into existence without doing it at startup or after any regular amount of time. I normally use another editor.

    ~/.vim/pack/kite/start/vim-plugin


Here is internet archive for the uninstall page in Oct 2022, let me know if I should remove this :

"""

    https://help.kite.com/article/68-how-to-uninstall-kite

# How to uninstall Kite

To completely remove Kite from your system, here are OS specific commands to:

    Uninstall all editor plugins
    Quit Kite and stop other Kite services
    Uninstall Kite

# Mac

Using your preferred Terminal:

    curl -X "DELETE" localhost:46624/clientapi/plugins/installed && \
    killall "Kite" && \
    launchctl remove com.kite.KiteAutostart && launchctl remove com.kite.KiteHelper && \
    rm -rf /Applications/Kite.app

# Windows

Using PowerShell:

    Invoke-WebRequest 'http://localhost:46624/clientapi/plugins/installed' `
    -Method 'DELETE' -UseBasicParsing
    & 'C:\Program Files\Kite\Uninstaller.exe'

# Linux

Using your preferred Terminal:

    curl -X "DELETE" localhost:46624/clientapi/plugins/installed && \
    ~/.local/share/kite/uninstall


# GUI

Alternatively, you can also perform the following steps to uninstall Kite:

    First, you will need to 

    [uninstall the editor plugins](https://web.archive.org/web/20221004032713/https://help.kite.com/article/62-managing-editor-plugins)

Kite has installed.

    Next, you will need to quit Kite. You can do so from the [menu bar icon]

    [menu bar icon](https://web.archive.org/web/20221004032713/https://help.kite.com/article/117-menu-bar-icon). 

If you don't have the menu bar icon shown, you can manually close all the [Kite processes]

    [Kite processes](https://web.archive.org/web/20221004032713/https://help.kite.com/article/54-the-kite-processes)

    Run uninstaller

        On macOS, drag Kite.app from your Applications folder to the trash.

        On Windows, you can uninstall Kite using the Add or Remove Programs tool.

        On Linux, run the uninstaller located at ~/.local/share/kite/uninstall

# Remove Kite data

Finally, you can remove the local Kite data and preferences stored on your system.

    On macOS and Linux, run the terminal command rm -rf ~/.kite 
    On Windows, remove the directory %USERPROFILE%\AppData\Local\Kite 

Last updated on March 16, 2021

"""
