### ISSUE TITLE
Run unit tests causes internal problem when no tests defined

### ISSUE THREAD

**Issue by apodhorski-student** [spyder-ide/spyder#20628]
### What steps will reproduce the problem?

1. Clean Anaconda install
2. conda install -c spyder-ide spyder-unittest
3. Within Spyder with a random Python file open and with no tests defined (no test directory, no test files, nothing else exists apart from that source Python file), go to the menu Run and click Run unit tests.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\Adam\anaconda3\lib\site-packages\spyder_unittest\unittestplugin.py", line 290, in maybe_configure_and_start
    self.get_widget().maybe_configure_and_start()
  File "C:\Users\Adam\anaconda3\lib\site-packages\spyder_unittest\widgets\unittestgui.py", line 340, in maybe_configure_and_start
    self.configure()
  File "C:\Users\Adam\anaconda3\lib\site-packages\spyder_unittest\widgets\unittestgui.py", line 312, in configure
    versions = self.get_versions(use_cached=True)
  File "C:\Users\Adam\anaconda3\lib\site-packages\spyder_unittest\widgets\unittestgui.py", line 278, in get_versions
    executable = self.get_conf('executable', section='main_interpreter')
  File "C:\Users\Adam\anaconda3\lib\site-packages\spyder\api\config\mixins.py", line 77, in get_conf
    return self.CONFIGURATION.get(section, option, default)
  File "C:\Users\Adam\anaconda3\lib\site-packages\spyder\config\manager.py", line 461, in get
    value = config.get(section=section, option=option, default=default)
  File "C:\Users\Adam\anaconda3\lib\site-packages\spyder\config\user.py", line 980, in get
    return config.get(section=section, option=option, default=default)
  File "C:\Users\Adam\anaconda3\lib\site-packages\spyder\config\user.py", line 517, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'executable' in section: 'main_interpreter'
```

## Versions

* Spyder version: 5.2.2 
* Python version: 3.9.13
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.0.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0               :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.16.0 (OK)
keyring >=17.0.0                     :  23.4.0 (OK)
nbconvert >=4.0                      :  6.4.4 (OK)
numpydoc >=0.6.0                     :  1.4.0 (OK)
paramiko >=2.4.0                     :  2.8.1 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.0 (OK)
pygments >=2.0                       :  2.11.2 (OK)
pylint >=2.5.0                       :  2.14.5 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0                 :  1.3.3 (OK)
pylsp_black >=1.0.0                  :  1.0.0 (OK)
qdarkstyle =3.0.2                    :  3.0.2 (OK)
qstylizer >=0.1.10                   :  0.1.10 (OK)
qtawesome >=1.0.2                    :  1.0.3 (OK)
qtconsole >=5.2.1;<5.3.0             :  5.2.2 (OK)
qtpy >=1.5.0                         :  2.2.0 (OK)
rtree >=0.9.7                        :  0.9.7 (OK)
setuptools >=49.6.0                  :  63.4.1 (OK)
sphinx >=0.6.6                       :  5.0.2 (OK)
spyder_kernels >=2.2.1;<2.3.0        :  2.2.1 (OK)
textdistance >=4.2.0                 :  4.2.1 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.6 (OK)
zmq >=17                             :  23.2.0 (OK)

# Optional:
cython >=0.21                        :  0.29.32 (OK)
matplotlib >=2.0.0                   :  3.5.2 (OK)
numpy >=1.7                          :  1.21.5 (OK)
pandas >=1.1.1                       :  1.4.4 (OK)
scipy >=0.17.0                       :  1.9.1 (OK)
sympy >=0.7.3                        :  1.10.1 (OK)

# Spyder plugins:
spyder_unittest.unittestplugin 0.5.1 :  0.5.1 (OK)
```

**Comment by dalthviz** [comment]
Hi @apodhorski-student thank you for the feedback! Seems like this could be a duplicate of https://github.com/spyder-ide/spyder-unittest/issues/188 Could you check if updating Spyder helps as suggested at https://github.com/spyder-ide/spyder-unittest/issues/188#issuecomment-1304563820 ? Let us know!

**Comment by dalthviz** [comment]
Closing due to lack of response
