### ISSUE TITLE
"About spyder" and "Report issue ..." output errors

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2064]
_From [Jer.Bu...@gmail.com](https://code.google.com/u/113762932654911968433/) on 2014-11-25T02:40:51Z_

When trying to open the "About spyder" or "Report issue ..." windows the following error appears in the internal console instead:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/spyder.py", line 1720, in about
    versions = get_versions()
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/__init__.py", line 66, in get_versions
    from IPython.external import qt
  File "/usr/lib/python2.7/dist-packages/IPython/external/qt.py", line 46, in \<module>
    prepare_pyqt4()
  File "/usr/lib/python2.7/dist-packages/IPython/external/qt.py", line 20, in prepare_pyqt4
    sip.setapi('QString', 2)
ValueError: API 'QString' has already been set to version 1 

What steps will reproduce the problem?

 1. Selecting "Help" > "About spyder ..." or "Help" > "Report issue" 

What is the expected output? What do you see instead?

 In both cases a window should pop up, but instead only an error is outputted What version of the product are you using? On what operating system? Spyderlib is version 2.3.1 (installed via pip). OS is Ubuntu 12.04 LTS. 

Please provide any additional information below

. Only just upgraded from 2.1.x which didn't have these issues

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2064_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-25T08:39:25Z_

Thanks for reporting. What's your IPython version?

**Labels:** MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [Jer.Bu...@gmail.com](https://code.google.com/u/113762932654911968433/) on 2014-11-25T23:13:02Z_

IPython is version 2.3.1

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-16T15:23:09Z_

What if you add a ValueError exception in line 67 of spyderlib/__init__.py? Like this

65    try:
66        from IPython.external import qt
67    except (ImportError, ValueError):
68        pass

That should fix the error (I hope :-)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-10T11:19:59Z_

This issue was closed by revision d1fb96b4676b .

**Status:** Fixed
