### ISSUE TITLE
Spyder wont launch PyQt5.QtWebEngineWidgets import QWebEnginePage ImportError:

### ISSUE THREAD

**Issue by blubye** [spyder-ide/spyder#20657]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder wont launch.  

$ spyder
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/spyder/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/envs/spyder/lib/python3.9/site-packages/spyder/app/start.py", line 249, in main
    from spyder.app import mainwindow
  File "/usr/local/anaconda3/envs/spyder/lib/python3.9/site-packages/spyder/app/mainwindow.py", line 56, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/usr/local/anaconda3/envs/spyder/lib/python3.9/site-packages/qtpy/QtWebEngineWidgets.py", line 28, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: /lib64/libgssapi_krb5.so.2: undefined symbol: k5_sname_compare, version krb5_3_MIT

$

### What steps reproduce the problem?

1.  just run spyder and it wont launch right after a conda installation.
2. installed as per Installation Guideline : 
3. conda create -c conda-forge -n spyder-env spyder numpy scipy pandas matplotlib sympy cython

* Spyder version: 5.4
* Python version:  3.9.16
* Qt version: 
* PyQt version:  5.15.7
* Operating System name/version:   rhel9.0

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @blubye, thanks for reporting. This happens because you're mixing Conda and system packages somehow. I think the issue could be that you're setting `LD_LIBRARY_PATH` somewhere in your system, which leads the Conda PyQt to try to use your system Kerberos library instead of the one provided by Conda itself, as can be seen here:

    ImportError: -->/lib64/libgssapi_krb5.so.2<--: undefined symbol: k5_sname_compare, version krb5_3_MIT

So, it's up to you to find and fix what's causing that mixing.
