### ISSUE TITLE
Spyder is not starting up

### ISSUE THREAD

**Issue by Payalparikh007** [spyder-ide/spyder#20655]
### What steps will reproduce the problem?

1. I upgrade the syderversion and its not starting u p

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Program Files\Python36\Lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1942, in finish_code_folding
    folding_panel.update_folding(self._folding_info)
AttributeError: 'CodeEditor' object has no attribute '_folding_info'
Traceback (most recent call last):
  File "C:\Program Files\Python36\Lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1942, in finish_code_folding
    folding_panel.update_folding(self._folding_info)
AttributeError: 'CodeEditor' object has no attribute '_folding_info'
Traceback (most recent call last):
  File "C:\Program Files\Python36\Lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1942, in finish_code_folding
    folding_panel.update_folding(self._folding_info)
AttributeError: 'CodeEditor' object has no attribute '_folding_info'
Traceback (most recent call last):
  File "C:\Program Files\Python36\Lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1942, in finish_code_folding
    folding_panel.update_folding(self._folding_info)
AttributeError: 'CodeEditor' object has no attribute '_folding_info'
Traceback (most recent call last):
  File "C:\Program Files\Python36\Lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1942, in finish_code_folding
    folding_panel.update_folding(self._folding_info)
AttributeError: 'CodeEditor' object has no attribute '_folding_info'
Traceback (most recent call last):
  File "C:\Program Files\Python36\Lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1942, in finish_code_folding
    folding_panel.update_folding(self._folding_info)
AttributeError: 'CodeEditor' object has no attribute '_folding_info'
```

## Versions

* Spyder version: 5.2.1 
* Python version: 3.6.8
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.0.0 (OK)
cloudpickle >=0.5.0           :  2.2.1 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.16.3 (OK)
jedi >=0.17.2;<0.19.0         :  0.17.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  3.0.0 (OK)
parso >=0.7.0;<0.9.0          :  0.7.1 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.4 (OK)
pygments >=2.0                :  2.14.0 (OK)
pylint >=2.5.0                :  2.13.9 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.1.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.2 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  59.6.0 (OK)
sphinx >=0.6.6                :  4.3.2 (OK)
spyder_kernels >=2.2.0;<2.3.0 :  2.2.0 (OK)
textdistance >=4.2.0          :  None (NOK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.3.1 (OK)
zmq >=17                      :  25.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  1.19.5 (OK)
pandas >=1.1.1                :  1.1.5 (OK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @Payalparikh007, thanks for reporting. This error is fixed in our latest version (5.4.2). However, that version doesn't work with Python 3.6 anymore.

So, I'm afraid you'll have to remove your current installation completely and reinstall Python 3.10 or 3.11. Then you'll be able to install Spyder 5.4.2 and get a fix for this error.

Sorry for the inconvenience, but it's the only solution we can offer for your problem.
