### ISSUE TITLE
Error when typing an opening bracket

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2065]
_From [Jer.Bu...@gmail.com](https://code.google.com/u/113762932654911968433/) on 2014-11-25T02:55:30Z_

When typing an opening bracket after an existing function name, the following error is thrown:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/editor.py", line 461, in show_object_info
    at_position=position)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/mixins.py", line 108, in show_calltip
    self.calltip_widget.show_tip(point, tiptext, wrapped_textlines)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/calltip.py", line 157, in show_tip
    forward=False)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/calltip.py", line 252, in _find_parenthesis
    while category(char) != 'Cc' and position > 0:
TypeError: need a single Unicode character as parameter 

What steps will reproduce the problem?

 1. Simply typing eg. "max(" 

What is the expected output? What do you see instead?

 The object inspector should give information about the functions and a calltip window should appear. Instead, the error is thrown and nothing happens. The closing bracket is automatically added though. What version of the product are you using? On what operating system? Spyderlib is version 2.3.1 and I'm running Ubuntu 12.04 LTS. 

Please provide any additional information below

. This problem started appearing when I upgraded from spyderlib 2.1.x to the current version. I have tried locally implementing revision 76f249aa2ab3 (as suggested in issue #1961 ), but without avail. Some testing suggests that crash occurs on the first evaluation of the while-expression in calltip.py, line 252, and never even enters the loop.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2065_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-25T08:45:13Z_

What do you have in line 249 of calltip.py? It should be this https://bitbucket.org/spyder-ide/spyderlib/src/1489769116ffa475d23ce84bc9a5830a692bab5a/spyderlib/widgets/calltip.py?at=default#cl-249

**Labels:** MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [Jer.Bu...@gmail.com](https://code.google.com/u/113762932654911968433/) on 2014-11-25T23:10:38Z_

That is what I have there too.
I found a related issue ( issue #1989 ) in which roughly the same problems that I'm experiencing are described. Maybe it's fixed already and I should just wait untill the next release?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-26T05:19:46Z_

Yes, please wait until 2.3.2. Else I'll fix it for 2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-09T17:48:22Z_

Closing because of lack of response

**Status:** WontFix
