### ISSUE TITLE
Problems with importing matplotlib from macports

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2066]
_From [tarahami...@gmail.com](https://code.google.com/u/113642637509869160878/) on 2014-11-26T01:51:07Z_

Spyder Version:  2.3.0
Python Version:  2.7.7
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Darwin
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=0.13  :  2.1.0 (OK)
pygments >=1.6  :  1.6 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  2.1.1 (OK)
rope >=0.9.2    :  0.10.2 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  1.2.1 (OK) 

What steps will reproduce the problem?

 1. type in the console or in a file: import matplotlib.pyplot as plt 2. 3. 

What is the expected output? What do you see instead?

 Expected output: program runs and produces plots

What I get:
\>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/pyplot.py", line 28, in \<module>
    from matplotlib import style
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/style/__init__.py", line 3, in \<module>
    from .core import use, context, available, library, reload_library
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/style/core.py", line 149, in \<module>
    _base_library = load_base_library()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/style/core.py", line 94, in load_base_library
    library.update(read_style_directory(BASE_LIBRARY_PATH))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/style/core.py", line 126, in read_style_directory
    for path, name in iter_style_files(style_dir):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/style/core.py", line 115, in iter_style_files
    for path in os.listdir(style_dir):
OSError: [Errno 2] No such file or directory: '/Applications/Spyder.app/Contents/Resources/mpl-data/stylelib' 

Please provide any additional information below

. It has only stopped working after I installed PyQt4 using macports.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2066_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-26T05:21:11Z_

Are you using Spyder from macports or from our dmg?

**Labels:** MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [tarahami...@gmail.com](https://code.google.com/u/113642637509869160878/) on 2014-11-26T12:36:31Z_

I used your dmg.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-27T07:11:38Z_

If you're using our dmg, how are you importing matplotlib from macports?

**Summary:** Problems with importing matplotlib from macports  \<span class="oldvalue"> (was: Problems with matplotlib) \</span>  
  **Labels:** OpSys-OSX

**Comment by spyder-issues-migrator** [comment]
_From [tarahami...@gmail.com](https://code.google.com/u/113642637509869160878/) on 2014-11-30T14:33:34Z_

The short answer is: Im not sure.  I had a lot of trouble installing
matplotlib but I did have it working.  Its only since Ive installed
opencv (also using macports) that this problem has manifest itself.
Should I install spyder using macports?  Do you think that might fix it?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-08T15:02:08Z_

Yes, I think you should try to install Spyder with MacPorts too.

I'm going to close this bug given that it doesn't seem related to Spyder itself.

**Status:** Invalid
