### ISSUE TITLE
New Project Crash

### ISSUE THREAD

**Issue by erussell92** [spyder-ide/spyder#20663]
### What steps will reproduce the problem?

I simply opened Spyder

Select Projects

Select New Project

Browsed for folder to save

Titled Project

Clicked Create

This window poped up

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\eruss\anaconda3\lib\site-packages\spyder\plugins\projects\plugin.py", line 347, in create_new_project
    self._create_project(root_path, project_type_id=project_type)
  File "C:\Users\eruss\anaconda3\lib\site-packages\spyder\plugins\projects\plugin.py", line 371, in _create_project
    self.open_project(path=root_path, project=project)
  File "C:\Users\eruss\anaconda3\lib\site-packages\spyder\plugins\projects\plugin.py", line 443, in open_project
    self.watcher.start(path)
  File "C:\Users\eruss\anaconda3\lib\site-packages\spyder\plugins\projects\utils\watcher.py", line 153, in start
    raise e
  File "C:\Users\eruss\anaconda3\lib\site-packages\spyder\plugins\projects\utils\watcher.py", line 128, in start
    self.observer.start()
  File "C:\Users\eruss\anaconda3\lib\site-packages\watchdog\observers\api.py", line 256, in start
    emitter.start()
  File "C:\Users\eruss\anaconda3\lib\site-packages\watchdog\utils\__init__.py", line 93, in start
    self.on_thread_start()
  File "C:\Users\eruss\anaconda3\lib\site-packages\watchdog\observers\read_directory_changes.py", line 67, in on_thread_start
    self._handle = get_directory_handle(self.watch.path)
  File "C:\Users\eruss\anaconda3\lib\site-packages\watchdog\observers\winapi.py", line 316, in get_directory_handle
    return CreateFileW(path, FILE_LIST_DIRECTORY, WATCHDOG_FILE_SHARE_FLAGS,
  File "C:\Users\eruss\anaconda3\lib\site-packages\watchdog\observers\winapi.py", line 112, in _errcheck_handle
    raise ctypes.WinError()
FileNotFoundError: [WinError 2] The system cannot find the file specified.
Traceback (most recent call last):
  File "C:\Users\eruss\anaconda3\lib\site-packages\spyder\plugins\projects\plugin.py", line 347, in create_new_project
    self._create_project(root_path, project_type_id=project_type)
  File "C:\Users\eruss\anaconda3\lib\site-packages\spyder\plugins\projects\plugin.py", line 371, in _create_project
    self.open_project(path=root_path, project=project)
  File "C:\Users\eruss\anaconda3\lib\site-packages\spyder\plugins\projects\plugin.py", line 443, in open_project
    self.watcher.start(path)
  File "C:\Users\eruss\anaconda3\lib\site-packages\spyder\plugins\projects\utils\watcher.py", line 153, in start
    raise e
  File "C:\Users\eruss\anaconda3\lib\site-packages\spyder\plugins\projects\utils\watcher.py", line 128, in start
    self.observer.start()
  File "C:\Users\eruss\anaconda3\lib\site-packages\watchdog\observers\api.py", line 256, in start
    emitter.start()
  File "C:\Users\eruss\anaconda3\lib\site-packages\watchdog\utils\__init__.py", line 93, in start
    self.on_thread_start()
  File "C:\Users\eruss\anaconda3\lib\site-packages\watchdog\observers\read_directory_changes.py", line 67, in on_thread_start
    self._handle = get_directory_handle(self.watch.path)
  File "C:\Users\eruss\anaconda3\lib\site-packages\watchdog\observers\winapi.py", line 316, in get_directory_handle
    return CreateFileW(path, FILE_LIST_DIRECTORY, WATCHDOG_FILE_SHARE_FLAGS,
  File "C:\Users\eruss\anaconda3\lib\site-packages\watchdog\observers\winapi.py", line 112, in _errcheck_handle
    raise ctypes.WinError()
FileNotFoundError: [WinError 2] The system cannot find the file specified.
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.8.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.4.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=1.0                  :  2.12.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.1 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.30 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.3 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by dalthviz** [comment]
Hi @erussell92 thank you for the feedback! Could it be possible for you to update Spyder to the latest release (5.4.2) and check again? Also, could you share with us the specific name you used for your project and directory structure? Maybe this could be related to https://github.com/spyder-ide/spyder/issues/16942 where the project naming causes problems if some characters that Windows doesn't support are present somewhere in the path.

Any new info in order to better understand what could be happening and reproduce this locally is greatly appreciated. Let us know if updating Spyder helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
