### ISSUE TITLE
Import Issue - Model X / LifeLib

### ISSUE THREAD

**Issue by Charlie-Wong-Actuary** [spyder-ide/spyder#20703]
### What steps will reproduce the problem?

When I import a Fibo function through reading from "https://docs.modelx.io/en/latest/tutorial/fibonacci.html#creating-a-cells-and-defining-its-formula"

It fails.

thanks!

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\loklo\anaconda3\envs\ActuarialWebDev\Lib\site-packages\spyder_modelx\widgets\mxexplorer.py", line 344, in contextMenuEvent
    self.shell.read_model(modelpath, name, define_var, varname)
  File "C:\Users\loklo\anaconda3\envs\ActuarialWebDev\Lib\site-packages\spyder_modelx\widgets\mxshell.py", line 525, in read_model
    timeout=CALL_KERNEL_TIMEOUT).mx_read_model(
                                 ^^^^^^^^^^^^^^
  File "C:\Users\loklo\anaconda3\envs\ActuarialWebDev\Lib\site-packages\spyder_kernels\comms\commbase.py", line 557, in __call__
    return self._comms_wrapper._get_call_return_value(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\loklo\anaconda3\envs\ActuarialWebDev\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 221, in _get_call_return_value
    raise CommError("Cannot block on a disconnected comm")
spyder_kernels.comms.commbase.CommError: Cannot block on a disconnected comm
```

## Versions

* Spyder version: 5.4.2  (conda)
* Python version: 3.11.0 64-bit
* Qt version: 5.15.6
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                         :  1.4.1 (OK)
chardet >=2.0.0                              :  5.1.0 (OK)
cloudpickle >=0.5.0                          :  2.2.1 (OK)
cookiecutter >=1.6.0                         :  2.1.1 (OK)
diff_match_patch >=20181111                  :  20200713 (OK)
intervaltree >=3.0.2                         :  3.0.2 (OK)
IPython >=7.31.1;<9.0.0                      :  8.11.0 (OK)
jedi >=0.17.2;<0.19.0                        :  0.18.2 (OK)
jellyfish >=0.7                              :  0.9.0 (OK)
jsonschema >=3.2.0                           :  4.17.3 (OK)
keyring >=17.0.0                             :  23.13.1 (OK)
nbconvert >=4.0                              :  7.2.9 (OK)
numpydoc >=0.6.0                             :  1.5.0 (OK)
paramiko >=2.4.0                             :  3.1.0 (OK)
parso >=0.7.0;<0.9.0                         :  0.8.3 (OK)
pexpect >=4.4.0                              :  4.8.0 (OK)
pickleshare >=0.4                            :  0.7.5 (OK)
psutil >=5.3                                 :  5.9.4 (OK)
pygments >=2.0                               :  2.14.0 (OK)
pylint >=2.5.0;<3.0                          :  2.17.0 (OK)
pylint_venv >=2.1.1                          :  3.0.1 (OK)
pyls_spyder >=0.4.0                          :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0                         :  1.7.1 (OK)
pylsp_black >=1.2.0                          :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0                    :  3.0.3 (OK)
qstylizer >=0.2.2                            :  0.2.2 (OK)
qtawesome >=1.2.1                            :  1.2.3 (OK)
qtconsole >=5.4.0;<5.5.0                     :  5.4.1 (OK)
qtpy >=2.1.0                                 :  2.3.0 (OK)
rtree >=0.9.7                                :  1.0.1 (OK)
setuptools >=49.6.0                          :  67.6.0 (OK)
sphinx >=0.6.6                               :  6.1.3 (OK)
spyder_kernels >=2.4.2;<2.5.0                :  2.4.2 (OK)
textdistance >=4.2.0                         :  4.5.0 (OK)
three_merge >=0.1.1                          :  0.1.1 (OK)
watchdog >=0.10.3                            :  2.3.1 (OK)
zmq >=22.1.0                                 :  25.0.1 (OK)

# Optional:
cython >=0.21                                :  None (NOK)
matplotlib >=3.0.0                           :  None (NOK)
numpy >=1.7                                  :  1.24.2 (OK)
pandas >=1.1.1                               :  1.5.3 (OK)
scipy >=0.17.0                               :  1.10.0 (OK)
sympy >=0.7.3                                :  None (NOK)

# Spyder plugins:
spyder_modelx.plugins.analyzer_plugin 0.13.3 :  0.13.3 (OK)
spyder_modelx.plugins.dataview_plugin 0.13.3 :  0.13.3 (OK)
spyder_modelx.plugins.mxplugin 0.13.3        :  0.13.3 (OK)
```

**Comment by ccordoba12** [comment]
Hey @Charlie-Wong-Actuary, thanks for reporting. Since This is not a problem with Spyder but with ModelX, I suggest you to report it there:

https://github.com/fumitoh/modelx
