### ISSUE TITLE
import module fails in ipython console; works when running a file

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2073]
_From [and...@flappingbird.com](https://code.google.com/u/105523113257294688942/) on 2014-12-03T14:40:23Z_

Spyder Version:  2.3.1
Python Version:  2.7.8
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Windows
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=0.13  :  2.3.1 (OK)
pygments >=1.6  :  2.0.1 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.4.2 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  None (OK) 

What steps will reproduce the problem?

 Open up an ipython console; try to type 'import' (without quotes) and as soon as you add a space to put the name of the library, you get an error. 

What is the expected output? What do you see instead?

 Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\IPython\qt\console\frontend_widget.py", line 60, in highlightBlock
    super(FrontendHighlighter, self).highlightBlock(string)
  File "C:\Anaconda\lib\site-packages\IPython\qt\console\pygments_highlighter.py", line 115, in highlightBlock
    for token, text in self._lexer.get_tokens(string):
  File "C:\Anaconda\lib\site-packages\pygments\lexer.py", line 192, in streamer
    for i, t, v in self.get_tokens_unprocessed(text):
  File "C:\Anaconda\lib\site-packages\IPython\qt\console\pygments_highlighter.py", line 30, in get_tokens_unprocessed
    for item in action(self, m):
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\IPython\qt\console\frontend_widget.py", line 60, in highlightBlock
    super(FrontendHighlighter, self).highlightBlock(string)
  File "C:\Anaconda\lib\site-packages\IPython\qt\console\pygments_highlighter.py", line 115, in highlightBlock
    for token, text in self._lexer.get_tokens(string):
  File "C:\Anaconda\lib\site-packages\pygments\lexer.py", line 192, in streamer
    for i, t, v in self.get_tokens_unprocessed(text):
  File "C:\Anaconda\lib\site-packages\IPython\qt\console\pygments_highlighter.py", line 30, in get_tokens_unprocessed
    for item in action(self, m):
TypeError: 'NoneType' object is not callable
 Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\IPython\qt\console\frontend_widget.py", line 60, in highlightBlock
    super(FrontendHighlighter, self).highlightBlock(string)
  File "C:\Anaconda\lib\site-packages\IPython\qt\console\pygments_highlighter.py", line 115, in highlightBlock
    for token, text in self._lexer.get_tokens(string):
  File "C:\Anaconda\lib\site-packages\pygments\lexer.py", line 192, in streamer
    for i, t, v in self.get_tokens_unprocessed(text):
  File "C:\Anaconda\lib\site-packages\IPython\qt\console\pygments_highlighter.py", line 30, in get_tokens_unprocessed
    for item in action(self, m):
TypeError: 'NoneType' object is not callable 

Please provide any additional information below

. When you run a script, this works.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2073_

**Comment by spyder-issues-migrator** [comment]
_From [and...@flappingbird.com](https://code.google.com/u/105523113257294688942/) on 2014-12-03T11:42:18Z_

Note that this fails in Spyder, but not when running ipython from a Windows 7 console.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-04T13:07:16Z_

Please update to 2.3.2. This was already fixed :-)

**Status:** Duplicate  
  **Mergedinto:** 2042
