### ISSUE TITLE
zmq.error.ZMQError: not a socket

### ISSUE THREAD

**Issue by Sun-kangning** [spyder-ide/spyder#20769]
### Issue Report Checklist
Exception in callback AddThreadSelectorEventLoop._handle_select([5532], [])
handle: <Handle AddThreadSelectorEventLoop._handle_select([5532], [])>
Traceback (most recent call last):
  File "G:\Software\Anaconda\envs\BeA_cloud_beta\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Software\Anaconda\envs\BeA_cloud_beta\lib\site-packages\tornado\platform\asyncio.py", line 647, in _handle_select
    self._handle_event(r, self._readers)
  File "G:\Software\Anaconda\envs\BeA_cloud_beta\lib\site-packages\tornado\platform\asyncio.py", line 661, in _handle_event
    callback()
  File "G:\Software\Anaconda\envs\BeA_cloud_beta\lib\site-packages\tornado\platform\asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "G:\Software\Anaconda\envs\BeA_cloud_beta\lib\site-packages\zmq\eventloop\zmqstream.py", line 614, in _handle_events
    zmq_events = self.socket.EVENTS
  File "G:\Software\Anaconda\envs\BeA_cloud_beta\lib\site-packages\zmq\sugar\attrsettr.py", line 55, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "G:\Software\Anaconda\envs\BeA_cloud_beta\lib\site-packages\zmq\sugar\attrsettr.py", line 67, in _get_attr_opt
    return self.get(opt)
  File "zmq\backend\cython\socket.pyx", line 512, in zmq.backend.cython.socket.Socket.get
  File "zmq\backend\cython\socket.pyx", line 270, in zmq.backend.cython.socket._getsockopt
  File "zmq\backend\cython\checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: not a socket

### What steps reproduce the problem?
Spyder used to pop up this error on its own.

After viewing the variable browser, sometimes this error will pop up.

**Comment by Sun-kangning** [comment]
I'll try the new version, thank you very much.
