### ISSUE TITLE
does not work on m1 mac

### ISSUE THREAD

**Issue by MaykThewessen** [spyder-ide/spyder#20775]
### What steps will reproduce the problem?

An error ocurred while starting the kernel
/Library/spyder𔂯.4.2/conda.exe: line 1: Οϊνώ: command not found
Traceback (most recent call last):
File "/Users/mayk/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Users/mayk/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/Users/mayk/miniconda3/lib/python3.10/site‑packages/spyder_kernels/console/__main__.py", line 22, in
from spyder_kernels.console import start
File "/Users/mayk/miniconda3/lib/python3.10/site‑packages/spyder_kernels/console/start.py", line 21, in
import ipykernel
File "/Users/mayk/miniconda3/lib/python3.10/site‑packages/ipykernel/__init__.py", line 5, in
from .connect import * # noqa
File "/Users/mayk/miniconda3/lib/python3.10/site‑packages/ipykernel/connect.py", line 11, in
import jupyter_client
File "/Users/mayk/miniconda3/lib/python3.10/site‑packages/jupyter_client/__init__.py", line 8, in
from .asynchronous import AsyncKernelClient # noqa
File "/Users/mayk/miniconda3/lib/python3.10/site‑packages/jupyter_client/asynchronous/__init__.py", line 1, in
from .client import AsyncKernelClient # noqa
File "/Users/mayk/miniconda3/lib/python3.10/site‑packages/jupyter_client/asynchronous/client.py", line 6, in
from jupyter_client.channels import HBChannel
File "/Users/mayk/miniconda3/lib/python3.10/site‑packages/jupyter_client/channels.py", line 12, in
import zmq.asyncio
File "/Users/mayk/miniconda3/lib/python3.10/site‑packages/zmq/__init__.py", line 61, in
_load_libzmq()
File "/Users/mayk/miniconda3/lib/python3.10/site‑packages/zmq/__init__.py", line 23, in _load_libzmq
import ctypes
File "/Users/mayk/miniconda3/lib/python3.10/ctypes/__init__.py", line 8, in
from _ctypes import Union, Structure, Array
ImportError: dlopen(/Users/mayk/miniconda3/lib/python3.10/lib‑dynload/_ctypes.cpython�‑darwin.so, 0x0002): Library not loaded: @rpath/libffi.8.dylib
Referenced from: /Users/mayk/miniconda3/lib/python3.10/lib‑dynload/_ctypes.cpython�‑darwin.so
Reason: tried: '/Users/mayk/miniconda3/lib/python3.10/lib‑dynload/../../libffi.8.dylib' (mach‑o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/mayk/miniconda3/lib/python3.10/lib‑dynload/../../libffi.8.dylib' (mach‑o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/mayk/miniconda3/bin/../lib/libffi.8.dylib' (mach‑o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/mayk/miniconda3/bin/../lib/libffi.8.dylib' (mach‑o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/libffi.8.dylib' (no such file), '/usr/lib/libffi.8.dylib' (no such file, not in dyld cache)

and

An error ocurred while starting the kernel
Traceback (most recent call last):
File "/Users/mayk/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Users/mayk/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/Users/mayk/miniconda3/lib/python3.10/site‑packages/spyder_kernels/console/__main__.py", line 22, in
from spyder_kernels.console import start
File "/Users/mayk/miniconda3/lib/python3.10/site‑packages/spyder_kernels/console/start.py", line 21, in
import ipykernel
File "/Users/mayk/miniconda3/lib/python3.10/site‑packages/ipykernel/__init__.py", line 5, in
from .connect import * # noqa
File "/Users/mayk/miniconda3/lib/python3.10/site‑packages/ipykernel/connect.py", line 11, in
import jupyter_client
File "/Users/mayk/miniconda3/lib/python3.10/site‑packages/jupyter_client/__init__.py", line 8, in
from .asynchronous import AsyncKernelClient # noqa
File "/Users/mayk/miniconda3/lib/python3.10/site‑packages/jupyter_client/asynchronous/__init__.py", line 1, in
from .client import AsyncKernelClient # noqa
File "/Users/mayk/miniconda3/lib/python3.10/site‑packages/jupyter_client/asynchronous/client.py", line 6, in
from jupyter_client.channels import HBChannel
File "/Users/mayk/miniconda3/lib/python3.10/site‑packages/jupyter_client/channels.py", line 12, in
import zmq.asyncio
File "/Users/mayk/miniconda3/lib/python3.10/site‑packages/zmq/__init__.py", line 61, in
_load_libzmq()
File "/Users/mayk/miniconda3/lib/python3.10/site‑packages/zmq/__init__.py", line 23, in _load_libzmq
import ctypes
File "/Users/mayk/miniconda3/lib/python3.10/ctypes/__init__.py", line 8, in
from _ctypes import Union, Structure, Array
ImportError: dlopen(/Users/mayk/miniconda3/lib/python3.10/lib‑dynload/_ctypes.cpython�‑darwin.so, 0x0002): Library not loaded: @rpath/libffi.8.dylib
Referenced from: /Users/mayk/miniconda3/lib/python3.10/lib‑dynload/_ctypes.cpython�‑darwin.so
Reason: tried: '/Users/mayk/miniconda3/lib/python3.10/lib‑dynload/../../libffi.8.dylib' (mach‑o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/mayk/miniconda3/lib/python3.10/lib‑dynload/../../libffi.8.dylib' (mach‑o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/mayk/miniconda3/bin/../lib/libffi.8.dylib' (mach‑o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/mayk/miniconda3/bin/../lib/libffi.8.dylib' (mach‑o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/libffi.8.dylib' (no such file), '/usr/lib/libffi.8.dylib' (no such file, not in dyld cache)

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/jupyter_client/manager.py", line 85, in wrapper
    self._ready.set_result(None)
asyncio.exceptions.InvalidStateError: invalid state

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qtconsole/manager.pyc", line 27, in poll
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/jupyter_client/restarter.py", line 143, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/jupyter_client/utils.py", line 30, in wrapped
    raise e
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/jupyter_client/utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "nest_asyncio.pyc", line 90, in run_until_complete
  File "asyncio/futures.pyc", line 201, in result
  File "asyncio/tasks.pyc", line 256, in __step
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/jupyter_client/manager.py", line 548, in _async_restart_kernel
    await ensure_async(self.start_kernel(**self._launch_args))
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/jupyter_client/utils.py", line 30, in wrapped
    raise e
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/jupyter_client/utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "nest_asyncio.pyc", line 90, in run_until_complete
  File "asyncio/futures.pyc", line 201, in result
  File "asyncio/tasks.pyc", line 256, in __step
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/jupyter_client/manager.py", line 88, in wrapper
    self._ready.set_exception(e)
asyncio.exceptions.InvalidStateError: invalid state
```

## Versions

* Spyder version: 5.4.2 93124668b (standalone)
* Python version: 3.9.14 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Darwin 22.4.0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.1.0 (OK)
cloudpickle >=0.5.0                  :  2.2.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.31.1;<9.0.0              :  8.8.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.2 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.17.3 (OK)
keyring >=17.0.0                     :  23.13.1 (OK)
nbconvert >=4.0                      :  7.2.8 (OK)
numpydoc >=0.6.0                     :  1.5.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.4 (OK)
pygments >=2.0                       :  2.14.0 (OK)
pylint >=2.5.0;<3.0                  :  2.15.10 (OK)
pylint_venv >=2.1.1                  :  None (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0                 :  1.7.1 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.2.2                    :  0.2.2 (OK)
qtawesome >=1.2.1                    :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0             :  5.4.0 (OK)
qtpy >=2.1.0                         :  2.3.0 (OK)
rtree >=0.9.7                        :  1.0.1 (OK)
setuptools >=49.6.0                  :  66.0.0 (OK)
sphinx >=0.6.6                       :  5.1.1 (OK)
spyder_kernels >=2.4.2;<2.5.0        :  2.4.2 (OK)
textdistance >=4.2.0                 :  4.5.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.2.1 (OK)
zmq >=22.1.0                         :  24.0.1 (OK)

# Optional:
cython >=0.21                        :  0.29.33 (OK)
matplotlib >=3.0.0                   :  3.6.3 (OK)
numpy >=1.7                          :  1.24.1 (OK)
pandas >=1.1.1                       :  1.5.2 (OK)
scipy >=0.17.0                       :  1.10.0 (OK)
sympy >=0.7.3                        :  1.11.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

### Environment

<details><summary>Environment</summary>

```

```
</details>

**Comment by dalthviz** [comment]
Hi @MaykThewessen thank you for the feedback! Could you try installing/updating to the latest release (Spyder 5.4.3) and check again? This seems like a duplicate of https://github.com/spyder-ide/spyder/issues/20637 which was fixed on Spyder 5.4.3.

Let us know if the info above helps!

**Comment by MaykThewessen** [comment]
Dear,

I did install version Spyder 5.4.3 yesterday, and i have the exact same error

Van: Daniel Althviz Moré ***@***.***>
Datum: donderdag, 6 april 2023 om 19:34
Aan: spyder-ide/spyder ***@***.***>
CC: Mayk Thewessen ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [spyder-ide/spyder] does not work on m1 mac (Issue #20775)

Hi @MaykThewessen<https://github.com/MaykThewessen> thank you for the feedback! Could you try installing/updating to the latest release (Spyder 5.4.3) and check again? This seems like a duplicate of #20637<https://github.com/spyder-ide/spyder/issues/20637> which was fixed on Spyder 5.4.3.

Let us know if the info above helps!

**Comment by dalthviz** [comment]
Thank you for trying the updating suggestion @MaykThewessen ! I'm not totally sure then what we could do besides trying to fully uninstall first and then install again 🤔,could you try to do that? Also, pinging @mrclary, maybe he could have some ideas about how to debug this or more suggestions.

Any new info that you could give us to understand this is appreciated!

**Comment by mrclary** [comment]
@MaykThewessen, you may try to reset Spyder's configuration.
1. Make a backup of your existing configuration
   ```
   $ mv ~/.spyder-py3 ~/.spyder-py3.bak
   ```
2. Restart Spyder by double clicking the application icon

I'm hoping that the system PYTHONPATH issue (#20637) is just persisting due to a problematic path remaining in the configuration, in which case starting with a fresh configuration should resolve it.

**Comment by dalthviz** [comment]
Closing due to lack of response
