### ISSUE TITLE
Internal problem

### ISSUE THREAD

**Issue by AmLunaW** [spyder-ide/spyder#20797]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "C:\Users\yuewang92\.conda\envs\py37\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'

**Comment by ccordoba12** [comment]
Hey @AmLunaW, thanks for reporting. You're using a very old Spyder version, which is not supported anymore.

This problem is fixed in our latest version available in Anaconda (5.4.2). Please update by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).

If that doesn't work, I'm afraid you'll have to remove and reinstall Anaconda.

**Comment by AmLunaW** [comment]
Hi there,

Thank you for the prompt response. I needed to use Python 3.7 to run my Gurobi, which is an optimization solver, and I thought python 3.7 only supports Spyder 3.3? I just figured out that Gurobi now actually supports python 3.9 as well. I have switched to python 3.9 and of course the newer version of Spyder. It is working well.

Thanks!

________________________________

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
