### ISSUE TITLE
pandas dataframe not visible in varialble explorer

### ISSUE THREAD

**Issue by mhaskeswapnil43** [spyder-ide/spyder#20801]
### What steps will reproduce the problem?

pandas dataframe not visible in varialble explorer, however visible in terminal

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\Welcome\.conda\envs\angel\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionsdelegate.py", line 210, in createEditor
    if not editor.setup_and_check(value, title=key):
  File "C:\Users\Welcome\.conda\envs\angel\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 957, in setup_and_check
    self.dataModel = DataFrameModel(data, parent=self)
  File "C:\Users\Welcome\.conda\envs\angel\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 135, in __init__
    self.max_min_col_update()
  File "C:\Users\Welcome\.conda\envs\angel\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 244, in max_min_col_update
    for __, col in self.df.iteritems():
  File "C:\Users\Welcome\.conda\envs\angel\lib\site-packages\pandas\core\generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'iteritems'
```

## Versions

* Spyder version: 5.3.3  (conda)
* Python version: 3.8.16 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.5.4 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.2 (OK)
qtawesome >=1.0.2             :  1.2.2 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.6.3 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  1.24.2 (OK)
pandas >=1.1.1                :  2.0.0 (OK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at C:\Users\Welcome\.conda\envs\angel:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12             pyhd3eb1b0_0    anaconda
arrow                     1.2.3            py38haa95532_0    anaconda
astroid                   2.11.7           py38haa95532_0    anaconda
atomicwrites              1.4.0                      py_0    anaconda
attrs                     22.1.0           py38haa95532_0    anaconda
autopep8                  1.6.0              pyhd3eb1b0_1    anaconda
babel                     2.11.0           py38haa95532_0    anaconda
backcall                  0.2.0              pyhd3eb1b0_0    anaconda
bcrypt                    3.2.0            py38h2bbff1b_1    anaconda
beautifulsoup4            4.11.1           py38haa95532_0    anaconda
binaryornot               0.4.4              pyhd3eb1b0_1    anaconda
black                     22.6.0           py38haa95532_0    anaconda
bleach                    4.1.0              pyhd3eb1b0_0    anaconda
boltons                   23.0.0           py38haa95532_0  
brotlipy                  0.7.0           py38h2bbff1b_1003    anaconda
ca-certificates           2023.01.10           haa95532_0  
certifi                   2022.12.7        py38haa95532_0  
cffi                      1.15.1           py38h2bbff1b_3    anaconda
chardet                   4.0.0           py38haa95532_1003    anaconda
charset-normalizer        2.0.4              pyhd3eb1b0_0    anaconda
click                     8.0.4            py38haa95532_0    anaconda
cloudpickle               2.0.0              pyhd3eb1b0_0    anaconda
colorama                  0.4.6            py38haa95532_0    anaconda
comm                      0.1.2            py38haa95532_0    anaconda
conda                     23.3.1           py38haa95532_0  
conda-package-handling    2.0.2            py38haa95532_0  
conda-package-streaming   0.7.0            py38haa95532_0  
cookiecutter              1.7.3              pyhd3eb1b0_0    anaconda
cryptography              38.0.4           py38h21b164f_0    anaconda
debugpy                   1.5.1            py38hd77b12b_0    anaconda
decorator                 5.1.1              pyhd3eb1b0_0    anaconda
defusedxml                0.7.1              pyhd3eb1b0_0    anaconda
diff-match-patch          20200713           pyhd3eb1b0_0    anaconda
dill                      0.3.6            py38haa95532_0    anaconda
docutils                  0.18.1           py38haa95532_3    anaconda
entrypoints               0.4              py38haa95532_0    anaconda
flake8                    4.0.1              pyhd3eb1b0_1    anaconda
flit-core                 3.6.0              pyhd3eb1b0_0    anaconda
glib                      2.69.1               h5dc1a3c_2    anaconda
gst-plugins-base          1.18.5               h9e645db_0    anaconda
gstreamer                 1.18.5               hd78058f_0    anaconda
icu                       58.2             vc14hc45fdbb_0  [vc14]  anaconda
idna                      3.4              py38haa95532_0    anaconda
imagesize                 1.4.1            py38haa95532_0    anaconda
importlib-metadata        4.11.3           py38haa95532_0    anaconda
importlib_metadata        4.11.3               hd3eb1b0_0    anaconda
importlib_resources       5.2.0              pyhd3eb1b0_1    anaconda
inflection                0.5.1            py38haa95532_0    anaconda
intervaltree              3.1.0              pyhd3eb1b0_0    anaconda
ipykernel                 6.19.2           py38hd4e2768_0    anaconda
ipython                   7.31.1           py38haa95532_1    anaconda
ipython_genutils          0.2.0              pyhd3eb1b0_1    anaconda
isort                     5.9.3              pyhd3eb1b0_0    anaconda
jedi                      0.18.1           py38haa95532_1    anaconda
jellyfish                 0.9.0            py38h2bbff1b_0    anaconda
jinja2                    3.1.2            py38haa95532_0    anaconda
jinja2-time               0.2.0              pyhd3eb1b0_3    anaconda
jpeg                      9e                   h2bbff1b_0    anaconda
jsonpatch                 1.32               pyhd3eb1b0_0  
jsonpointer               2.1                pyhd3eb1b0_0  
jsonschema                4.16.0           py38haa95532_0    anaconda
jupyter_client            7.4.8            py38haa95532_0    anaconda
jupyter_core              5.1.1            py38haa95532_0    anaconda
jupyterlab_pygments       0.1.2                      py_0    anaconda
keyring                   23.4.0           py38haa95532_0    anaconda
lazy-object-proxy         1.6.0            py38h2bbff1b_0    anaconda
libclang                  12.0.0          default_h627e005_2    anaconda
libffi                    3.4.2                hd77b12b_6  
libiconv                  1.16                 h2bbff1b_2    anaconda
libogg                    1.3.5                h2bbff1b_1    anaconda
libpng                    1.6.37               h2a8f88b_0    anaconda
libsodium                 1.0.18               h62dcd97_0    anaconda
libspatialindex           1.9.3                h6c2663c_0    anaconda
libvorbis                 1.3.7                he774522_0    anaconda
libwebp                   1.2.4                h2bbff1b_0    anaconda
libwebp-base              1.2.4                h2bbff1b_0    anaconda
libxml2                   2.9.14               h0ad7f3c_0    anaconda
libxslt                   1.1.35               h2bbff1b_0    anaconda
lxml                      4.9.1            py38h1985fb9_0    anaconda
lz4-c                     1.9.4                h2bbff1b_0    anaconda
markupsafe                2.1.1            py38h2bbff1b_0    anaconda
matplotlib-inline         0.1.6            py38haa95532_0    anaconda
mccabe                    0.7.0              pyhd3eb1b0_0    anaconda
menuinst                  1.4.19           py38h59b6b97_0  
mistune                   0.8.4           py38he774522_1000    anaconda
mypy_extensions           0.4.3            py38haa95532_1    anaconda
nbclient                  0.5.13           py38haa95532_0    anaconda
nbconvert                 6.5.4            py38haa95532_0    anaconda
nbformat                  5.7.0            py38haa95532_0    anaconda
nest-asyncio              1.5.6            py38haa95532_0    anaconda
numpy                     1.24.2                   pypi_0    pypi
numpydoc                  1.5.0            py38haa95532_0    anaconda
openssl                   1.1.1t               h2bbff1b_0  
packaging                 22.0             py38haa95532_0    anaconda
pandas                    2.0.0                    pypi_0    pypi
pandocfilters             1.5.0              pyhd3eb1b0_0    anaconda
paramiko                  2.8.1              pyhd3eb1b0_0    anaconda
parso                     0.8.3              pyhd3eb1b0_0    anaconda
pathspec                  0.10.3           py38haa95532_0    anaconda
pcre                      8.45                 hd77b12b_0    anaconda
pexpect                   4.8.0              pyhd3eb1b0_3    anaconda
pickleshare               0.7.5           pyhd3eb1b0_1003    anaconda
pip                       23.0.1           py38haa95532_0  
pkgutil-resolve-name      1.3.10           py38haa95532_0    anaconda
platformdirs              2.5.2            py38haa95532_0    anaconda
pluggy                    1.0.0            py38haa95532_1    anaconda
ply                       3.11                     py38_0    anaconda
poyo                      0.5.0              pyhd3eb1b0_0    anaconda
prompt-toolkit            3.0.36           py38haa95532_0    anaconda
psutil                    5.9.0            py38h2bbff1b_0    anaconda
ptyprocess                0.7.0              pyhd3eb1b0_2    anaconda
pycodestyle               2.8.0              pyhd3eb1b0_0    anaconda
pycosat                   0.6.4            py38h2bbff1b_0  
pycparser                 2.21               pyhd3eb1b0_0    anaconda
pydocstyle                6.3.0            py38haa95532_0    anaconda
pyflakes                  2.4.0              pyhd3eb1b0_0    anaconda
pygments                  2.11.2             pyhd3eb1b0_0    anaconda
pylint                    2.14.5           py38haa95532_0    anaconda
pyls-spyder               0.4.0              pyhd3eb1b0_0    anaconda
pynacl                    1.5.0            py38h8cc25b3_0    anaconda
pyopenssl                 22.0.0             pyhd3eb1b0_0    anaconda
pyotp                     2.8.0                    pypi_0    pypi
pyqt                      5.15.7           py38hd77b12b_0    anaconda
pyqt5-sip                 12.11.0          py38hd77b12b_0    anaconda
pyqtwebengine             5.15.7           py38hd77b12b_0    anaconda
pyrsistent                0.18.0           py38h196d8e1_0    anaconda
pysocks                   1.7.1            py38haa95532_0    anaconda
python                    3.8.16               h6244533_3  
python-dateutil           2.8.2              pyhd3eb1b0_0    anaconda
python-fastjsonschema     2.16.2           py38haa95532_0    anaconda
python-lsp-black          1.2.1            py38haa95532_0    anaconda
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0    anaconda
python-lsp-server         1.5.0            py38haa95532_0    anaconda
python-slugify            5.0.2              pyhd3eb1b0_0    anaconda
pytz                      2022.7           py38haa95532_0    anaconda
pywin32                   305              py38h2bbff1b_0    anaconda
pywin32-ctypes            0.2.0                 py38_1000    anaconda
pyyaml                    6.0              py38h2bbff1b_1    anaconda
pyzmq                     23.2.0           py38hd77b12b_0    anaconda
qdarkstyle                3.0.2              pyhd3eb1b0_0    anaconda
qstylizer                 0.2.2            py38haa95532_0    anaconda
qt-main                   5.15.2               he8e5bd7_7    anaconda
qt-webengine              5.15.9               hb9a9bb5_5    anaconda
qtawesome                 1.2.2            py38haa95532_0    anaconda
qtconsole                 5.3.2            py38haa95532_0    anaconda
qtpy                      2.2.0            py38haa95532_0    anaconda
qtwebkit                  5.212                h3ad3cdb_4    anaconda
requests                  2.28.1           py38haa95532_0    anaconda
rope                      0.22.0             pyhd3eb1b0_0    anaconda
rtree                     1.0.1            py38h2eaa2aa_0    anaconda
ruamel.yaml               0.17.21          py38h2bbff1b_0  
ruamel.yaml.clib          0.2.6            py38h2bbff1b_1  
setuptools                65.6.3           py38haa95532_0  
sip                       6.6.2            py38hd77b12b_0    anaconda
six                       1.16.0             pyhd3eb1b0_1    anaconda
smartapi-python           1.3.0                    pypi_0    pypi
snowballstemmer           2.2.0              pyhd3eb1b0_0    anaconda
sortedcontainers          2.4.0              pyhd3eb1b0_0    anaconda
soupsieve                 2.3.2.post1      py38haa95532_0    anaconda
sphinx                    5.0.2            py38haa95532_0    anaconda
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0    anaconda
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0    anaconda
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0    anaconda
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0    anaconda
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0    anaconda
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0    anaconda
spyder                    5.3.3            py38haa95532_0    anaconda
spyder-kernels            2.3.3            py38haa95532_0    anaconda
sqlite                    3.41.1               h2bbff1b_0  
text-unidecode            1.3                pyhd3eb1b0_0    anaconda
textdistance              4.2.1              pyhd3eb1b0_0    anaconda
three-merge               0.1.1              pyhd3eb1b0_0    anaconda
tinycss2                  1.2.1            py38haa95532_0    anaconda
toml                      0.10.2             pyhd3eb1b0_0    anaconda
tomli                     2.0.1            py38haa95532_0    anaconda
tomlkit                   0.11.1           py38haa95532_0    anaconda
toolz                     0.12.0           py38haa95532_0  
tornado                   6.2              py38h2bbff1b_0    anaconda
tqdm                      4.65.0           py38hd4e2768_0  
traitlets                 5.7.1            py38haa95532_0    anaconda
typing-extensions         4.4.0            py38haa95532_0    anaconda
typing_extensions         4.4.0            py38haa95532_0    anaconda
tzdata                    2023.3                   pypi_0    pypi
ujson                     5.4.0            py38hd77b12b_0    anaconda
unidecode                 1.2.0              pyhd3eb1b0_0    anaconda
urllib3                   1.26.14          py38haa95532_0    anaconda
vc                        14.2                 h21ff451_1  
vs2015_runtime            14.27.29016          h5e58377_2  
watchdog                  2.1.6            py38haa95532_0    anaconda
wcwidth                   0.2.5              pyhd3eb1b0_0    anaconda
webencodings              0.5.1                    py38_1    anaconda
websocket-client          1.5.1                    pypi_0    pypi
whatthepatch              1.0.2            py38haa95532_0    anaconda
wheel                     0.38.4           py38haa95532_0  
win_inet_pton             1.1.0            py38haa95532_0    anaconda
wincertstore              0.2              py38haa95532_2  
wrapt                     1.14.1           py38h2bbff1b_0    anaconda
yaml                      0.2.5                he774522_0    anaconda
yapf                      0.31.0             pyhd3eb1b0_0    anaconda
zeromq                    4.3.4                hd77b12b_0    anaconda
zipp                      3.11.0           py38haa95532_0    anaconda
zlib                      1.2.13               h8cc25b3_0    anaconda
zstandard                 0.19.0           py38h2bbff1b_0  
zstd                      1.5.2                h19a0ad4_0    anaconda

```
</details>

**Comment by dalthviz** [comment]
Hi @mhaskeswapnil43 thank you for the feedback! Seems like this is a duplicate of https://github.com/spyder-ide/spyder/issues/20496 To get the fix you will need to update to Spyder 5.4.3

Let us know if updating helps!

**Comment by dalthviz** [comment]
Closing as a duplicate of https://github.com/spyder-ide/spyder/issues/20496
