### ISSUE TITLE
Issue with spyder

### ISSUE THREAD

**Issue by sleveneu** [spyder-ide/spyder#20807]
Dear all, 
If someone could help me
My spyder worked very well, then I got an issue with the kernel 

The error is:

Traceback (most recent call last):
File "C:\Users\sleveneu\AppData\Local\anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 2136, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle,
File "C:\Users\sleveneu\AppData\Local\anaconda3\lib\site‑packages\jupyter_client\utils.py", line 30, in wrapped
raise e
File "C:\Users\sleveneu\AppData\Local\anaconda3\lib\site‑packages\jupyter_client\utils.py", line 27, in wrapped
return loop.run_until_complete(future)
File "C:\Users\sleveneu\AppData\Local\anaconda3\lib\site‑packages\nest_asyncio.py", line 90, in run_until_complete
return f.result()
File "C:\Users\sleveneu\AppData\Local\anaconda3\lib\asyncio\futures.py", line 201, in result
raise self._exception.with_traceback(self._exception_tb)
File "C:\Users\sleveneu\AppData\Local\anaconda3\lib\asyncio\tasks.py", line 232, in __step
result = coro.send(None)
File "C:\Users\sleveneu\AppData\Local\anaconda3\lib\site‑packages\jupyter_client\manager.py", line 90, in wrapper
raise e
File "C:\Users\sleveneu\AppData\Local\anaconda3\lib\site‑packages\jupyter_client\manager.py", line 82, in wrapper
out = await method(self, *args, **kwargs)
File "C:\Users\sleveneu\AppData\Local\anaconda3\lib\site‑packages\jupyter_client\manager.py", line 391, in _async_start_kernel
kernel_cmd, kw = await ensure_async(self.pre_start_kernel(**kw))
File "C:\Users\sleveneu\AppData\Local\anaconda3\lib\site‑packages\jupyter_client\utils.py", line 30, in wrapped
raise e
File "C:\Users\sleveneu\AppData\Local\anaconda3\lib\site‑packages\jupyter_client\utils.py", line 27, in wrapped
return loop.run_until_complete(future)
File "C:\Users\sleveneu\AppData\Local\anaconda3\lib\site‑packages\nest_asyncio.py", line 90, in run_until_complete
return f.result()
File "C:\Users\sleveneu\AppData\Local\anaconda3\lib\asyncio\futures.py", line 201, in result
raise self._exception.with_traceback(self._exception_tb)
File "C:\Users\sleveneu\AppData\Local\anaconda3\lib\asyncio\tasks.py", line 232, in __step
result = coro.send(None)
File "C:\Users\sleveneu\AppData\Local\anaconda3\lib\site‑packages\jupyter_client\manager.py", line 356, in _async_pre_start_kernel
kw = await self.provisioner.pre_launch(**kw)
File "C:\Users\sleveneu\AppData\Local\anaconda3\lib\site‑packages\jupyter_client\provisioning\local_provisioner.py", line 190, in pre_launch
km.write_connection_file()
File "C:\Users\sleveneu\AppData\Local\anaconda3\lib\site‑packages\jupyter_client\connect.py", line 503, in write_connection_file
self.connection_file, cfg = write_connection_file(
File "C:\Users\sleveneu\AppData\Local\anaconda3\lib\site‑packages\jupyter_client\connect.py", line 164, in write_connection_file
with secure_write(fname) as f:
File "C:\Users\sleveneu\AppData\Local\anaconda3\lib\contextlib.py", line 135, in __enter__
return next(self.gen)
File "C:\Users\sleveneu\AppData\Local\anaconda3\lib\site‑packages\jupyter_core\paths.py", line 983, in secure_write
win32_restrict_file_to_user(fname)
File "C:\Users\sleveneu\AppData\Local\anaconda3\lib\site‑packages\jupyter_core\paths.py", line 536, in win32_restrict_file_to_user
sd = win32security.GetFileSecurity(fname, win32security.DACL_SECURITY_INFORMATION)
pywintypes.error: (50, 'GetFileSecurity', 'Cette demande n’est pas prise en charge.')

**Comment by dalthviz** [comment]
Hi @sleveneu thank you for the feedback! What version of Spyder are you using? Could check if updating Spyder to a more recent version helps? The lastest version available from the main anaconda channel is Spyder 5.4.2 and 5.4.3 from the conda-forge channel. To update/install a more recent version of Spyder you can check the installation guide at: https://docs.spyder-ide.org/current/installation.html?highlight=update#anaconda-base

This could be related with https://github.com/spyder-ide/spyder/issues/18186 but no specific way to reproduce this has been provided, so any new info you could give us to understand what could be happening here is appreciated!

Let us know if the info above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response

**Comment by sleveneu** [comment]
Thanks Dalthviz
I'm using spyder 5.4.3

**Comment by dalthviz** [comment]
Hi @sleveneu are you still getting the error? If so, please let us know any other detail on how to reproduce it at #18186

**Comment by sleveneu** [comment]
Hi @dalthviz , actually I needed to reinstal anaconda, and use one of the last version of spyder 5.4.3 
It is very stable now

**Comment by dalthviz** [comment]
Awesome @sleveneu ! Thank you for letting us know!
