### ISSUE TITLE
removed pathlib

### ISSUE THREAD

**Issue by greeenboi** [spyder-ide/spyder#20826]
### What steps will reproduce the problem?

```
conda remove pathlib
```
<b>I was told that pathlib was a depreciated package by pyinstaller and was told to type in console the above command</b>

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\suvan\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1480, in create_new_client
  File "C:\Users\suvan\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 164, in __init__
  File "C:\Users\suvan\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 247, in _create_loading_page
AttributeError: 'NoneType' object has no attribute 'replace'
```

## Versions

* Spyder version: 5.4.1  (conda)
* Python version: 3.10.9 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<9.0.0       :  8.10.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.5.4 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.16.2 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.0;<1.8.0          :  1.7.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.6.3 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.4.1;<2.5.0 :  2.4.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.7.0 (OK)
numpy >=1.7                   :  1.23.5 (OK)
pandas >=1.1.1                :  1.5.3 (OK)
scipy >=0.17.0                :  1.10.0 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at C:\Users\suvan\anaconda3:
#
# Name                    Version                   Build  Channel
absl-py                   1.4.0                    pypi_0    pypi
altgraph                  0.17.3                   pypi_0    pypi
anaconda-client           1.11.1          py310haa95532_0  
anaconda-project          0.11.1          py310haa95532_0  
astunparse                1.6.3                    pypi_0    pypi
attrs                     22.1.0          py310haa95532_0  
auto-py-to-exe            2.33.0                   pypi_0    pypi
backports                 1.1                pyhd3eb1b0_0  
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0  
backports.tempfile        1.0                pyhd3eb1b0_1  
backports.weakref         1.0.post1                  py_1  
beautifulsoup4            4.12.2          py310haa95532_0  
boltons                   23.0.0          py310haa95532_0  
bottle                    0.12.25                  pypi_0    pypi
bottle-websocket          0.2.9                    pypi_0    pypi
brotlipy                  0.7.0           py310h2bbff1b_1002  
bzip2                     1.0.8                he774522_0  
ca-certificates           2023.01.10           haa95532_0  
cachetools                5.3.0                    pypi_0    pypi
certifi                   2022.12.7       py310haa95532_0  
cffi                      1.15.1          py310h2bbff1b_3  
chardet                   4.0.0           py310haa95532_1003  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4           py310haa95532_0  
clyent                    1.2.2           py310haa95532_1  
colorama                  0.4.6           py310haa95532_0  
conda                     23.3.1          py310haa95532_0  
conda-build               3.23.3          py310haa95532_0  
conda-content-trust       0.1.3           py310haa95532_0  
conda-pack                0.6.0              pyhd3eb1b0_0  
conda-package-handling    2.0.2           py310haa95532_0  
conda-package-streaming   0.7.0           py310haa95532_0  
conda-token               0.4.0              pyhd3eb1b0_0  
conda-verify              3.4.2                      py_1  
console_shortcut          0.1.1                         4  
cryptography              39.0.1          py310h21b164f_0  
customtkinter             5.1.2                    pypi_0    pypi
darkdetect                0.8.0                    pypi_0    pypi
defusedxml                0.7.1              pyhd3eb1b0_0  
eel                       0.16.0                   pypi_0    pypi
filelock                  3.9.0           py310haa95532_0  
flatbuffers               23.3.3                   pypi_0    pypi
future                    0.18.3          py310haa95532_0  
gast                      0.4.0                    pypi_0    pypi
gevent                    22.10.2                  pypi_0    pypi
gevent-websocket          0.10.1                   pypi_0    pypi
glob2                     0.7                pyhd3eb1b0_0  
google-auth               2.17.2                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.53.0                   pypi_0    pypi
idna                      3.4             py310haa95532_0  
jax                       0.4.8                    pypi_0    pypi
jinja2                    3.1.2           py310haa95532_0  
jsonpatch                 1.32               pyhd3eb1b0_0  
jsonpointer               2.1                pyhd3eb1b0_0  
jsonschema                4.17.3          py310haa95532_0  
jupyter_core              5.3.0           py310haa95532_0  
keras                     2.12.0                   pypi_0    pypi
libarchive                3.6.2                h2033e3e_1  
libclang                  16.0.0                   pypi_0    pypi
libffi                    3.4.2                hd77b12b_6  
libiconv                  1.16                 h2bbff1b_2  
liblief                   0.12.3               hd77b12b_0  
libxml2                   2.10.3               h0ad7f3c_0  
lz4-c                     1.9.4                h2bbff1b_0  
m2-msys2-runtime          2.5.0.17080.65c939c               3  
m2-patch                  2.7.5                         2  
markupsafe                2.1.1           py310h2bbff1b_0  
menuinst                  1.4.19          py310h59b6b97_0  
ml-dtypes                 0.0.4                    pypi_0    pypi
msys2-conda-epoch         20160418                      1  
nbformat                  5.7.0           py310haa95532_0  
oauthlib                  3.2.2                    pypi_0    pypi
opencv-python             4.7.0.72                 pypi_0    pypi
openssl                   1.1.1t               h2bbff1b_0  
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 23.0            py310haa95532_0  
pefile                    2023.2.7                 pypi_0    pypi
pip                       22.3.1          py310haa95532_0  
pkginfo                   1.9.6           py310haa95532_0  
platformdirs              2.5.2           py310haa95532_0  
pluggy                    1.0.0           py310haa95532_1  
powershell_shortcut       0.0.1                         3  
protobuf                  4.22.1                   pypi_0    pypi
psutil                    5.9.0           py310h2bbff1b_0  
py-lief                   0.12.3          py310hd77b12b_0  
pycosat                   0.6.4           py310h2bbff1b_0  
pycparser                 2.21               pyhd3eb1b0_0  
pygame                    2.3.0                    pypi_0    pypi
pyinstaller               5.10.0                   pypi_0    pypi
pyinstaller-hooks-contrib 2023.2                   pypi_0    pypi
pyopenssl                 23.0.0          py310haa95532_0  
pypng                     0.20220715.0             pypi_0    pypi
pyrsistent                0.18.0          py310h2bbff1b_0  
pysocks                   1.7.1           py310haa95532_0  
python                    3.10.9               h966fe2a_1  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.16.2          py310haa95532_0  
python-libarchive-c       2.9                pyhd3eb1b0_1  
python-time               0.3.0                    pypi_0    pypi
pytz                      2022.7          py310haa95532_0  
pywin32                   305             py310h2bbff1b_0  
pyyaml                    6.0             py310h2bbff1b_1  
qrcode                    7.4.2                    pypi_0    pypi
requests                  2.28.1          py310haa95532_1  
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
ruamel.yaml               0.17.21         py310h2bbff1b_0  
ruamel.yaml.clib          0.2.6           py310h2bbff1b_1  
ruamel_yaml               0.17.21         py310h2bbff1b_0  
setuptools                65.6.3          py310haa95532_0  
six                       1.16.0             pyhd3eb1b0_1  
soupsieve                 2.4             py310haa95532_0  
sqlite                    3.41.2               h2bbff1b_0  
tensorboard               2.12.1                   pypi_0    pypi
tensorboard-data-server   0.7.0                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.12.0                   pypi_0    pypi
tensorflow-estimator      2.12.0                   pypi_0    pypi
tensorflow-intel          2.12.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.31.0                   pypi_0    pypi
termcolor                 2.2.0                    pypi_0    pypi
tk                        0.1.0                    pypi_0    pypi
toml                      0.10.2             pyhd3eb1b0_0  
toolz                     0.12.0          py310haa95532_0  
tornado                   6.2             py310h2bbff1b_0  
tqdm                      4.65.0          py310h9909e9c_0  
traitlets                 5.7.1           py310haa95532_0  
tzdata                    2023c                h04d1e81_0  
urllib3                   1.26.15         py310haa95532_0  
vc                        14.2                 h21ff451_1  
vs2015_runtime            14.27.29016          h5e58377_2  
wheel                     0.38.4          py310haa95532_0  
whichcraft                0.6.1                    pypi_0    pypi
win_inet_pton             1.1.0           py310haa95532_0  
wincertstore              0.2             py310haa95532_2  
xz                        5.2.10               h8cc25b3_1  
yaml                      0.2.5                he774522_0  
zlib                      1.2.13               h8cc25b3_0  
zope-event                4.6                      pypi_0    pypi
zstandard                 0.19.0          py310h2bbff1b_0  
zstd                      1.5.5                hd43e919_0  

```
</details>

**Comment by ccordoba12** [comment]
Hey @greeenboi, thanks for reporting. You said:

> I was told that pathlib was a depreciated package by pyinstaller and was told to type in console the above command

Conda commands are not meant to be run in Spyder's IPython console. Instead, you need to close Spyder, open the Anaconda Prompt and run them there.

In addition, the error you reported above is caused because Spyder was not installed correctly. So we recommend you to run the following commands to fix that

    conda remove spyder
    conda install spyder=5.4.2

Let us know if that works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
