### ISSUE TITLE
UnicodeDecodeError in opening Ipython console

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2091]
_From [damien.b...@gmail.com](https://code.google.com/u/112162359373200157181/) on 2014-12-22T04:57:56Z_

Spyder Version:  2.3.1
Python Version:  2.7.8
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Windows
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=0.13  :  2.2.0 (OK)
pygments >=1.6  :  1.6 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.4.0 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1. Start Spyder 

What is the expected output? What do you see instead?

 I expect a Ipython console, and I get this message : 

Une erreur est survenue lors du démarrage du noyau.
'import sitecustomize' failed; use ‑v for traceback
Traceback (most recent call last):
File "C:\Users\D19\AppData\Local\Continuum\Anaconda\lib\site‑packages\spyderlib\widgets\externalshell\start_ipython_kernel.py", line 186, in 
ipk_temp.config = kernel_config()
File "C:\Users\D19\AppData\Local\Continuum\Anaconda\lib\site‑packages\spyderlib\widgets\externalshell\start_ipython_kernel.py", line 45, in kernel_config
from spyderlib.config import CONF
File "C:\Users\D19\AppData\Local\Continuum\Anaconda\lib\site‑packages\spyderlib\config.py", line 22, in 
from spyderlib.utils import iofuncs, codeanalysis
File "C:\Users\D19\AppData\Local\Continuum\Anaconda\lib\site‑packages\spyderlib\utils\iofuncs.py", line 26, in 
import pandas as pd
File "C:\Users\D19\AppData\Local\Continuum\Anaconda\lib\site‑packages\pandas\__init__.py", line 41, in 
from pandas.core.api import *
File "C:\Users\D19\AppData\Local\Continuum\Anaconda\lib\site‑packages\pandas\core\api.py", line 9, in 
from pandas.core.groupby import Grouper
File "C:\Users\D19\AppData\Local\Continuum\Anaconda\lib\site‑packages\pandas\core\groupby.py", line 15, in 
from pandas.core.frame import DataFrame
File "C:\Users\D19\AppData\Local\Continuum\Anaconda\lib\site‑packages\pandas\core\frame.py", line 38, in 
from pandas.core.series import Series
File "C:\Users\D19\AppData\Local\Continuum\Anaconda\lib\site‑packages\pandas\core\series.py", line 2524, in 
import pandas.tools.plotting as _gfx
File "C:\Users\D19\AppData\Local\Continuum\Anaconda\lib\site‑packages\pandas\tools\plotting.py", line 26, in 
import pandas.tseries.converter as conv
File "C:\Users\D19\AppData\Local\Continuum\Anaconda\lib\site‑packages\pandas\tseries\converter.py", line 7, in 
import matplotlib.units as units
File "C:\Users\D19\AppData\Local\Continuum\Anaconda\lib\site‑packages\matplotlib\__init__.py", line 1048, in 
rcParams = rc_params()
File "C:\Users\D19\AppData\Local\Continuum\Anaconda\lib\site‑packages\matplotlib\__init__.py", line 897, in rc_params
fname = matplotlib_fname()
File "C:\Users\D19\AppData\Local\Continuum\Anaconda\lib\site‑packages\matplotlib\__init__.py", line 748, in matplotlib_fname
fname = os.path.join(os.getcwd(), 'matplotlibrc')
File "C:\Users\D19\AppData\Local\Continuum\Anaconda\lib\ntpath.py", line 84, in join
result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 27: ordinal not in range(128) 

Please provide any additional information below

. I can open a IPython console outside Spyder. When I shut down the computer on friday, everything was working fine.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2091_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-01T14:12:12Z_

This error in caused by matplotlib, not by Spyder. To solve it you just need to update to matplotlib 1.4.2.

**Status:** WontFix
