### ISSUE TITLE
WinError 10038 error

### ISSUE THREAD

**Issue by jayaeros** [spyder-ide/spyder#20921]
### What steps will reproduce the problem?

it has happens randomly when i run a program after certain number of consecutive execution

### Traceback
```python-traceback
Exception in thread Tornado selector:
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\tf2.4\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\User\miniconda3\envs\tf2.4\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\miniconda3\envs\tf2.4\lib\site-packages\tornado\platform\asyncio.py", line 605, in _run_select
    rs, ws, xs = select.select(to_read, to_write, to_write)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
```

## Versions

* Spyder version: 5.4.2  (conda)
* Python version: 3.8.15 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.1.0 (OK)
cloudpickle >=0.5.0           :  2.2.1 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<9.0.0       :  8.11.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.13.1 (OK)
nbconvert >=4.0               :  7.2.9 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  3.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.4 (OK)
pygments >=2.0                :  2.14.0 (OK)
pylint >=2.5.0;<3.0           :  2.17.0 (OK)
pylint_venv >=2.1.1           :  3.0.1 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0          :  1.7.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.3 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.1 (OK)
qtpy >=2.1.0                  :  2.3.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  67.6.0 (OK)
sphinx >=0.6.6                :  6.1.3 (OK)
spyder_kernels >=2.4.2;<2.5.0 :  2.4.2 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.3.1 (OK)
zmq >=22.1.0                  :  25.0.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.22.3 (OK)
pandas >=1.1.1                :  1.4.3 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  None (NOK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at C:\Users\User\miniconda3\envs\tf2.4:
#
# Name                    Version                   Build  Channel
absl-py                   1.2.0                    pypi_0    pypi
alabaster                 0.7.13             pyhd8ed1ab_0    conda-forge
anyio                     3.6.2              pyhd8ed1ab_0    conda-forge
aom                       3.5.0                h63175ca_0    conda-forge
app                       0.0.1                    pypi_0    pypi
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py38h91455d4_3    conda-forge
arrow                     1.2.3              pyhd8ed1ab_0    conda-forge
astroid                   2.15.0           py38haa244fe_0    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3                    pypi_0    pypi
atomicwrites              1.4.1              pyhd8ed1ab_0    conda-forge
attrs                     22.2.0             pyh71513ae_0    conda-forge
autopep8                  1.6.0              pyhd8ed1ab_1    conda-forge
babel                     2.12.1             pyhd8ed1ab_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bcrypt                    3.2.2            py38h91455d4_1    conda-forge
beautifulsoup4            4.11.2             pyha770c72_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
black                     23.1.0           py38haa244fe_0    conda-forge
blas                      1.0                         mkl  
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.3               hdccc3a2_0    conda-forge
bottleneck                1.3.7            py38hbaf524b_0    conda-forge
brotli                    1.0.9                hcfcfb64_8    conda-forge
brotli-bin                1.0.9                hcfcfb64_8    conda-forge
brotlipy                  0.7.0           py38h91455d4_1005    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
c-blosc2                  2.7.1                h183a6f4_0    conda-forge
ca-certificates           2023.5.7             h56e8100_0    conda-forge
cachetools                5.2.0                    pypi_0    pypi
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py38h57701bc_3    conda-forge
cfitsio                   4.2.0                h9ebe7e4_0    conda-forge
chardet                   5.1.0            py38haa244fe_0    conda-forge
charls                    2.4.1                h1537add_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3           win_pyhd8ed1ab_2    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.1.2              pyhd8ed1ab_0    conda-forge
conda                     4.14.0           py38haa244fe_0    conda-forge
conda-package-handling    2.0.2              pyh38be061_0    conda-forge
conda-package-streaming   0.7.0              pyhd8ed1ab_1    conda-forge
cookiecutter              2.1.1              pyh6c4a22f_0    conda-forge
cryptography              38.0.4           py38h086c683_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.12.0           py38h91455d4_1    conda-forge
dask-core                 2023.3.1           pyhd8ed1ab_0    conda-forge
dav1d                     1.0.0                h8ffe710_1    conda-forge
debugpy                   1.6.6            py38hd3f51b4_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
dill                      0.3.6              pyhd8ed1ab_1    conda-forge
docstring-to-markdown     0.11               pyhd8ed1ab_0    conda-forge
docutils                  0.19             py38haa244fe_1    conda-forge
eigen                     3.4.0                h2d74725_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
et_xmlfile                1.1.0              pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
fftw                      3.3.10          nompi_h38027f0_106    conda-forge
flake8                    6.0.0              pyhd8ed1ab_0    conda-forge
flask                     2.2.2            py38haa95532_0    anaconda
flatbuffers               1.12                     pypi_0    pypi
flit-core                 3.8.0              pyhd8ed1ab_0    conda-forge
fonttools                 4.39.2           py38h91455d4_0    conda-forge
freetype                  2.12.1               h546665d_1    conda-forge
frozendict                2.3.8            py38h91455d4_0    conda-forge
fsspec                    2023.3.0           pyhd8ed1ab_1    conda-forge
gast                      0.4.0                    pypi_0    pypi
gettext                   0.21.1               h5728263_0    conda-forge
giflib                    5.2.1                h64bf75a_3    conda-forge
glib                      2.74.1               h12be248_1    conda-forge
glib-tools                2.74.1               h12be248_1    conda-forge
glob2                     0.7                        py_0    conda-forge
google-api-core           2.11.0                   pypi_0    pypi
google-api-python-client  2.48.0                   pypi_0    pypi
google-auth               2.16.2                   pypi_0    pypi
google-auth-httplib2      0.1.0                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-images-search      1.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
googleapis-common-protos  1.58.0                   pypi_0    pypi
grpcio                    1.48.1                   pypi_0    pypi
gst-plugins-base          1.18.5               h9e645db_0  
gstreamer                 1.18.5               hd78058f_0  
h5py                      3.7.0                    pypi_0    pypi
hdf5                      1.14.0          nompi_h97a5375_103    conda-forge
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
httplib2                  0.21.0                   pypi_0    pypi
icc_rt                    2022.1.0             h6049295_2  
icu                       58.2                 ha925a31_3  
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagecodecs               2023.1.23        py38h38923f3_0    conda-forge
imageio                   2.26.0             pyh24c5eb1_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
imglyb                    2.1.0              pyha21a80b_0    conda-forge
importlib-metadata        4.12.0                   pypi_0    pypi
importlib_metadata        6.1.0                hd8ed1ab_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
inflection                0.5.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2023.0.0         h57928b3_25922    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 6.21.3             pyh025b116_0    conda-forge
ipython                   8.11.0             pyh08f2357_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                8.0.4              pyhd8ed1ab_0    conda-forge
isort                     5.12.0             pyhd8ed1ab_1    conda-forge
itsdangerous              2.1.2              pyhd8ed1ab_0    conda-forge
jaraco.classes            3.2.3              pyhd8ed1ab_0    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jellyfish                 0.9.0            py38h91455d4_2    conda-forge
jgo                       1.0.4              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jinja2-time               0.2.0              pyhd8ed1ab_3    conda-forge
jpeg                      9e                   hcfcfb64_3    conda-forge
jpype1                    1.4.1            py38hb1fd069_1    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0            py38haa95532_8  
jupyter_client            7.4.9              pyhd8ed1ab_0    conda-forge
jupyter_console           6.6.3              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.0            py38haa244fe_0    conda-forge
jupyter_events            0.6.3              pyhd8ed1ab_0    conda-forge
jupyter_server            2.5.0              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab                3.5.0              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.20.0             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.5              pyhd8ed1ab_0    conda-forge
jxrlib                    1.1                  h8ffe710_2    conda-forge
keras                     2.9.0                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
keyring                   23.13.1          py38haa244fe_0    conda-forge
kiwisolver                1.4.4            py38hb1fd069_1    conda-forge
krb5                      1.20.1               h6609f42_0    conda-forge
labeling                  0.1.12             pyhd8ed1ab_1    conda-forge
lazy-object-proxy         1.9.0            py38h91455d4_0    conda-forge
lcms2                     2.15                 ha5c8aab_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libaec                    1.0.6                h63175ca_1    conda-forge
libarchive                3.5.2                hb45042f_3    conda-forge
libavif                   0.11.1               h8f5c5bc_0    conda-forge
libblas                   3.9.0              12_win64_mkl    conda-forge
libbrotlicommon           1.0.9                hcfcfb64_8    conda-forge
libbrotlidec              1.0.9                hcfcfb64_8    conda-forge
libbrotlienc              1.0.9                hcfcfb64_8    conda-forge
libcblas                  3.9.0              12_win64_mkl    conda-forge
libclang                  14.0.6                   pypi_0    pypi
libcurl                   7.88.1               h68f0423_1    conda-forge
libdeflate                1.17                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.74.1               he8f3873_1    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
liblapack                 3.9.0              12_win64_mkl    conda-forge
libmamba                  0.25.0               h81a967f_2    conda-forge
libmambapy                0.25.0           py38hf902ccc_2    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libprotobuf               3.20.2               h12be248_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libsolv                   0.7.23               h12be248_0    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libssh2                   1.10.0               h680486a_3    conda-forge
libtiff                   4.5.0                hf8721a0_2    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.2.4                hbc33d0d_1  
libwebp-base              1.2.4                h2bbff1b_1  
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.9.14               hc3477c8_4    conda-forge
libxslt                   1.1.35               h2bbff1b_0  
libzlib                   1.2.13               hcfcfb64_4    conda-forge
libzopfli                 1.0.3                h0e60522_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lxml                      4.9.1            py38h1985fb9_0  
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
lzo                       2.10              he774522_1000    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mamba                     0.25.0           py38hecfeebb_2    conda-forge
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.2            py38h91455d4_0    conda-forge
matplotlib                3.5.2            py38haa95532_0  
matplotlib-base           3.5.2            py38hd77b12b_0  
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
maven                     3.9.1                h57928b3_0    conda-forge
mccabe                    0.7.0              pyhd8ed1ab_0    conda-forge
menuinst                  1.4.19           py38haa244fe_1    conda-forge
mistune                   2.0.5              pyhd8ed1ab_0    conda-forge
mkl                       2021.4.0           h0e2418a_729    conda-forge
mkl-service               2.4.0            py38h4f8af0f_0    conda-forge
mnist                     0.2.2                      py_0    conda-forge
more-itertools            9.1.0              pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multitasking              0.0.9              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
nbclassic                 0.5.3              pyhb4ecaf3_3    conda-forge
nbclient                  0.7.2              pyhd8ed1ab_0    conda-forge
nbconvert                 7.2.9              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.2.9              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.2.9              pyhd8ed1ab_0    conda-forge
nbformat                  5.7.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
networkx                  3.0                pyhd8ed1ab_0    conda-forge
notebook                  6.5.3              pyha770c72_0    conda-forge
notebook-shim             0.2.2              pyhd8ed1ab_0    conda-forge
numexpr                   2.8.4            py38h5b0cc5e_0  
numpy                     1.22.4                   pypi_0    pypi
numpydoc                  1.5.0              pyhd8ed1ab_0    conda-forge
oauthlib                  3.2.0                    pypi_0    pypi
opencv                    4.6.0            py38h104de81_2  
opencv-contrib-python     4.7.0.72                 pypi_0    pypi
openjdk                   8.0.152              h7382acf_1  
openjpeg                  2.5.0                ha2aaf27_2    conda-forge
openpyxl                  3.0.10           py38h2bbff1b_0  
openssl                   1.1.1t               hcfcfb64_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pandas                    1.4.3            py38hd77b12b_0  
pandoc                    3.1.1                h57928b3_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
paramiko                  3.1.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.3.0              pyhd8ed1ab_0    conda-forge
pathspec                  0.11.1             pyhd8ed1ab_0    conda-forge
pcre2                     10.40                h17e33f8_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.4.0            py38h087119c_1    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              3.1.1              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
ply                       3.11                       py_1    conda-forge
prometheus_client         0.16.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.38             pyha770c72_0    conda-forge
prompt_toolkit            3.0.38               hd8ed1ab_0    conda-forge
protobuf                  3.20.0                   pypi_0    pypi
psutil                    5.9.4            py38h91455d4_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycodestyle               2.10.0             pyhd8ed1ab_0    conda-forge
pycosat                   0.6.4            py38h91455d4_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydocstyle                6.2.3              pyhd8ed1ab_0    conda-forge
pyfiglet                  0.8.post1                pypi_0    pypi
pyflakes                  3.0.1              pyhd8ed1ab_0    conda-forge
pygments                  2.14.0             pyhd8ed1ab_0    conda-forge
pyimagej                  1.4.1            py38haa244fe_0    conda-forge
pylint                    2.17.0             pyhd8ed1ab_0    conda-forge
pylint-venv               3.0.1              pyhd8ed1ab_0    conda-forge
pyls-spyder               0.4.0              pyhd8ed1ab_0    conda-forge
pynacl                    1.5.0            py38hbc1c497_2    conda-forge
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7           py38hd77b12b_0  
pyqt5-sip                 12.11.0          py38hd77b12b_0  
pyqtwebengine             5.15.7           py38hd77b12b_0  
pyrsistent                0.19.3           py38h91455d4_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.8.15               h6244533_2  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.3             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-lsp-black          1.2.1              pyhd8ed1ab_0    conda-forge
python-lsp-jsonrpc        1.0.0              pyhd8ed1ab_0    conda-forge
python-lsp-server         1.7.1                hd8ed1ab_0    conda-forge
python-lsp-server-base    1.7.1              pyhd8ed1ab_0    conda-forge
python-resize-image       1.1.20                   pypi_0    pypi
python-slugify            8.0.1              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytoolconfig              1.2.5              pyhd8ed1ab_0    conda-forge
pytz                      2022.7.1           pyhd8ed1ab_0    conda-forge
pywavelets                1.4.1            py38hbaf524b_0    conda-forge
pywin32                   304              py38hd3f51b4_2    conda-forge
pywin32-ctypes            0.2.0           py38haa244fe_1006    conda-forge
pywinpty                  2.0.10           py38hd3f51b4_0    conda-forge
pyyaml                    6.0              py38h91455d4_5    conda-forge
pyzmq                     25.0.1           py38ha85f68a_0    conda-forge
qdarkstyle                3.0.3              pyhd8ed1ab_0    conda-forge
qstylizer                 0.2.2              pyhd8ed1ab_0    conda-forge
qt-main                   5.15.2               he8e5bd7_7  
qt-webengine              5.15.9               hb9a9bb5_5  
qtawesome                 1.2.3              pyhd8ed1ab_0    conda-forge
qtconsole                 5.4.1              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.4.1              pyha770c72_0    conda-forge
qtpy                      2.3.0              pyhd8ed1ab_0    conda-forge
qtwebkit                  5.212                h3ad3cdb_4  
reproc                    14.2.4               hcfcfb64_0    conda-forge
reproc-cpp                14.2.4               h63175ca_0    conda-forge
requests                  2.28.2             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.1                    pypi_0    pypi
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rope                      1.7.0              pyhd8ed1ab_0    conda-forge
rsa                       4.9                      pypi_0    pypi
rtree                     1.0.1            py38h8b54edf_1    conda-forge
ruamel_yaml               0.15.80         py38h91455d4_1008    conda-forge
scikit-image              0.19.3           py38hd77b12b_1    anaconda
scipy                     1.7.3            py38h7a0a035_2  
scyjava                   1.9.0              pyhd8ed1ab_0    conda-forge
seaborn                   0.12.2           py38haa95532_0    anaconda
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                67.6.0             pyhd8ed1ab_0    conda-forge
sip                       6.6.2            py38h885f38d_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               hfb803bf_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sphinx                    6.1.3              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.4              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
split-folders             0.5.1                    pypi_0    pypi
spyder                    5.4.2            py38haa95532_0  
spyder-kernels            2.4.2           win_pyhd8ed1ab_0    conda-forge
sqlite                    3.40.0               hcfcfb64_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
tbb                       2021.7.0             h59b6b97_0  
tensorboard               2.9.1                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.9.1                    pypi_0    pypi
tensorflow-estimator      2.9.0                    pypi_0    pypi
tensorflow-io-gcs-filesystem 0.26.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.15.0           py38haa244fe_0    conda-forge
text-unidecode            1.3                        py_0    conda-forge
textdistance              4.5.0              pyhd8ed1ab_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
tifffile                  2023.3.15          pyhd8ed1ab_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlkit                   0.11.6             pyha770c72_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2              py38h91455d4_1    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
typing                    3.10.0.0           pyhd8ed1ab_0    conda-forge
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
ujson                     5.7.0            py38hd3f51b4_0    conda-forge
unicodedata2              15.0.0           py38h91455d4_0    conda-forge
unidecode                 1.3.6              pyhd8ed1ab_0    conda-forge
uritemplate               4.1.1                    pypi_0    pypi
urllib3                   1.26.12                  pypi_0    pypi
vc                        14.3                hb6edc58_10    conda-forge
vs2015_runtime            14.34.31931         h4c5c07a_10    conda-forge
watchdog                  2.3.1            py38haa244fe_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.5.1              pyhd8ed1ab_0    conda-forge
werkzeug                  2.2.3              pyhd8ed1ab_0    conda-forge
whatthepatch              1.0.4              pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.5              pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
windows-curses            2.3.0            py38h82bb817_0    labscript-suite
winpty                    0.4.3                         4    conda-forge
wrapt                     1.15.0           py38h91455d4_0    conda-forge
xarray                    2022.11.0          pyhd8ed1ab_0    conda-forge
xlrd                      2.0.1              pyhd3eb1b0_0  
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yaml-cpp                  0.7.0                h63175ca_2    conda-forge
yapf                      0.32.0             pyhd8ed1ab_0    conda-forge
yfinance                  0.2.18             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zfp                       1.0.0                h63175ca_3    conda-forge
zipp                      3.8.1                    pypi_0    pypi
zlib                      1.2.13               hcfcfb64_4    conda-forge
zlib-ng                   2.0.7                hcfcfb64_0    conda-forge
zstandard                 0.19.0           py38hea8d35e_1    conda-forge
zstd                      1.5.2                h12be248_6    conda-forge

```
</details>

**Comment by ccordoba12** [comment]
Hey @jayaeros, thanks for reporting. I think this problem is fixed in our latest version (5.4.3). Please update by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-conda).

Let us know if it works for you.

**Comment by jayaeros** [comment]
I have updated the spyder and will be in contact again if the issue persists. Thank you

**Comment by ccordoba12** [comment]
Ok, thanks! Hopefully that's not the case.

**Comment by jayaeros** [comment]
Thank you very much. The issue is no longer there

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know about it. Closing this issue then.
