### ISSUE TITLE
error with IPython console: [SpyderKernelApp] ERROR | Exception in message handler: 

### ISSUE THREAD

**Issue by yixingwang0517** [spyder-ide/spyder#20932]
## Problem Description

A = np.arange(9).reshape(3,3)

A
Out[161]: 
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

x = np.arange(3)

x
Out[163]: array([0, 1, 2])

np.dot(A, x)
Out[164]: array([ 5, 14, 23])

A.dot(x)
Out[165]: array([ 5, 14, 23])
[SpyderKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/opt/anaconda/anaconda3/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/opt/anaconda/anaconda3/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 796, in inspect_request
    reply_content = self.do_inspect(
  File "/opt/anaconda/anaconda3/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 544, in do_inspect
    bundle = self.shell.object_inspect_mime(
  File "/opt/anaconda/anaconda3/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1838, in object_inspect_mime
    return self.inspector._get_info(
  File "/opt/anaconda/anaconda3/lib/python3.10/site-packages/IPython/core/oinspect.py", line 738, in _get_info
    info_dict = self.info(obj, oname=oname, info=info, detail_level=detail_level)
  File "/opt/anaconda/anaconda3/lib/python3.10/site-packages/IPython/core/oinspect.py", line 838, in info
    if info and info.parent and hasattr(info.parent, HOOK_NAME):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.10.11 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Linux 5.19.0-41-generic

**Comment by ccordoba12** [comment]
Hey @yixingwang0517, thanks for reporting. This problem is fixed in the latest IPython version (8.13.2), which is not available in Anacondq yet. To fix it for now, please close pyder, open the Anaconda Prompt and run there the command:

    conda install ipython=8.7.0
