### ISSUE TITLE
Anacondo spyder application launch error

### ISSUE THREAD

**Issue by cmtata** [spyder-ide/spyder#20941]
I couldn't open spyder all of a sudden someday, so I reinstall anacondo but still didn't work.
I downloaded anacondo windows python 3.10 version 64bits, and when I open anacondo and launch spyder it apperared "application launch error" and the description said:

![螢幕擷取畫面 2023-05-18 132809](https://github.com/spyder-ide/spyder/assets/133943421/abdb9c41-f543-4499-91a7-c438b76b5d5d)

C:\Users\USER\anaconda3\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
"class": algorithms.Blowfish,
Traceback (most recent call last):
File "C:\Users\USER\anaconda3\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\USER\anaconda3\lib\site-packages\spyder\app\start.py", line 252, in main
mainwindow.main(options, args)
File "C:\Users\USER\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1822, in main
mainwindow = create_window(MainWindow, app, splash, options, args)
File "C:\Users\USER\anaconda3\lib\site-packages\spyder\app\utils.py", line 289, in create_window
main.setup()
File "C:\Users\USER\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 773, in setup
PLUGIN_REGISTRY.register_plugin(self, PluginClass,
File "C:\Users\USER\anaconda3\lib\site-packages\spyder\api\plugin_registration\registry.py", line 342, in register_plugin
instance = self._instantiate_spyder5_plugin(
File "C:\Users\USER\anaconda3\lib\site-packages\spyder\api\plugin_registration\registry.py", line 184, in _instantiate_spyder5_plugin
plugin_instance = PluginClass(main_window, configuration=CONF)
File "C:\Users\USER\anaconda3\lib\site-packages\spyder\api\plugins\new_api.py", line 331, in __init__
container.setup()
File "C:\Users\USER\anaconda3\lib\site-packages\spyder\plugins\pythonpath\container.py", line 55, in setup
self._load_pythonpath()
File "C:\Users\USER\anaconda3\lib\site-packages\spyder\plugins\pythonpath\container.py", line 136, in _load_pythonpath
system_path = get_system_pythonpath()
File "C:\Users\USER\anaconda3\lib\site-packages\spyder\plugins\pythonpath\utils.py", line 31, in get_system_pythonpath
env = get_user_env()
File "C:\Users\USER\anaconda3\lib\site-packages\spyder\utils\environ.py", line 71, in get_user_env
env_dict = get_user_environment_variables()
File "C:\Users\USER\anaconda3\lib\site-packages\spyder\utils\environ.py", line 60, in get_user_environment_variables
res = stdout.decode().strip().split(os.linesep)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 832: invalid start byte

**Comment by ccordoba12** [comment]
Hey @cmtata, thanks for reporting. This problem is fixed in our latest version available in Anaconda (5.4.3). Please update by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).

Let us know if it works for you.

**Comment by cmtata** [comment]
I use “ conda update spyder” at anaconda prompt, and it works! Thank you 🙏
