### ISSUE TITLE
crash on start of spyder from command line

### ISSUE THREAD

**Issue by 2sn** [spyder-ide/spyder#20999]
### What steps will reproduce the problem?

I just started spyder, that's all I know.  Python console seem stuck.

Use Vanilla Python 3.11.3, compiled from source, on Fedora 38.

### Traceback
```python-traceback
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/alex/Python/lib/python3.11/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/jupyter_client/threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/home/alex/Python/lib/python3.11/asyncio/tasks.py", line 267, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/jupyter_client/threaded.py", line 34, in get_msg
    return await msg
           ^^^^^^^^^
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/home/alex/Python/lib/python3.11/site-packages/zmq/eventloop/zmqstream.py", line 634, in _handle_events
    self._handle_recv()
  File "/home/alex/Python/lib/python3.11/site-packages/zmq/eventloop/zmqstream.py", line 663, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/alex/Python/lib/python3.11/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/jupyter_client/threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/home/alex/Python/lib/python3.11/asyncio/tasks.py", line 267, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/jupyter_client/threaded.py", line 34, in get_msg
    return await msg
           ^^^^^^^^^
TypeError: object list can't be used in 'await' expression
Exception in callback BaseAsyncIOLoop._handle_events(138, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(138, 1)>
Traceback (most recent call last):
  File "/home/alex/Python/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/alex/Python/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 192, in _handle_events
    handler_func(fileobj, events)
  File "/home/alex/Python/lib/python3.11/site-packages/zmq/eventloop/zmqstream.py", line 634, in _handle_events
    self._handle_recv()
  File "/home/alex/Python/lib/python3.11/site-packages/zmq/eventloop/zmqstream.py", line 663, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/alex/Python/lib/python3.11/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/jupyter_client/threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/home/alex/Python/lib/python3.11/asyncio/tasks.py", line 267, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/jupyter_client/threaded.py", line 34, in get_msg
    return await msg
           ^^^^^^^^^
TypeError: object list can't be used in 'await' expression
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/alex/Python/lib/python3.11/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/jupyter_client/threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/home/alex/Python/lib/python3.11/asyncio/tasks.py", line 267, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/jupyter_client/threaded.py", line 34, in get_msg
    return await msg
           ^^^^^^^^^
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/home/alex/Python/lib/python3.11/site-packages/zmq/eventloop/zmqstream.py", line 634, in _handle_events
    self._handle_recv()
  File "/home/alex/Python/lib/python3.11/site-packages/zmq/eventloop/zmqstream.py", line 663, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/alex/Python/lib/python3.11/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/jupyter_client/threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/home/alex/Python/lib/python3.11/asyncio/tasks.py", line 267, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/jupyter_client/threaded.py", line 34, in get_msg
    return await msg
           ^^^^^^^^^
TypeError: object list can't be used in 'await' expression
Exception in callback BaseAsyncIOLoop._handle_events(135, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(135, 1)>
Traceback (most recent call last):
  File "/home/alex/Python/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/alex/Python/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 192, in _handle_events
    handler_func(fileobj, events)
  File "/home/alex/Python/lib/python3.11/site-packages/zmq/eventloop/zmqstream.py", line 634, in _handle_events
    self._handle_recv()
  File "/home/alex/Python/lib/python3.11/site-packages/zmq/eventloop/zmqstream.py", line 663, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/alex/Python/lib/python3.11/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/jupyter_client/threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/home/alex/Python/lib/python3.11/asyncio/tasks.py", line 267, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/jupyter_client/threaded.py", line 34, in get_msg
    return await msg
           ^^^^^^^^^
TypeError: object list can't be used in 'await' expression
```

## Versions

* Spyder version: 5.4.3  (pip)
* Python version: 3.11.3 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Linux 6.3.5-200.fc38.x86_64

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.1 (OK)
chardet >=2.0.0                                  :  5.1.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  2.1.1 (OK)
diff_match_patch >=20181111                      :  20230430 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.14.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.2 (OK)
jellyfish >=0.7                                  :  0.11.2 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  7.4.0 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.5 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.17.4 (OK)
pylint_venv >=2.1.1                              :  3.0.1 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.3 (OK)
pylsp_black >=1.2.0                              :  1.3.0 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.1 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.3 (OK)
qtpy >=2.1.0                                     :  2.3.1 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  65.5.0 (OK)
sphinx >=0.6.6                                   :  6.2.1 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.3 (OK)
textdistance >=4.2.0                             :  4.5.0 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  3.0.0 (OK)
xdg >=0.26                                       :  0.27 (OK)
zmq >=22.1.0                                     :  25.1.0 (OK)

# Optional:
cython >=0.21                                    :  0.29.35 (OK)
matplotlib >=3.0.0                               :  3.7.1 (OK)
numpy >=1.7                                      :  1.24.3 (OK)
pandas >=1.1.1                                   :  2.0.2 (OK)
scipy >=0.17.0                                   :  1.10.1 (OK)
sympy >=0.7.3                                    :  1.12 (OK)
```

### Environment

<details><summary>Environment</summary>

```
Package                           Version
--------------------------------- -----------
absl-py                           1.4.0
aiofiles                          22.1.0
aiohttp                           3.8.4
aiosignal                         1.3.1
aiosqlite                         0.19.0
alabaster                         0.7.13
ansible                           8.0.0
ansible-core                      2.15.0
anyio                             3.7.0
apipkg                            3.0.1
apng                              0.3.4
appdirs                           1.4.4
apptools                          5.2.0
argcomplete                       3.0.8
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
argopt                            0.8.2
arrow                             1.2.3
asgiref                           3.7.2
asn1crypto                        1.5.1
astor                             0.8.1
astroid                           2.15.5
astropy                           5.3
asttokens                         2.2.1
astunparse                        1.6.3
async-generator                   1.10
async-lru                         2.0.2
async-timeout                     4.0.2
atom                              0.10.0
atomicwrites                      1.4.1
attrdict3                         2.0.2
attrs                             23.1.0
autobahn                          23.1.2
Automat                           22.10.0
autopep8                          2.0.2
Babel                             2.12.1
backcall                          0.2.0
basemap-data                      1.3.2
bcrypt                            4.0.1
Beaker                            1.12.1
beautifulsoup4                    4.12.2
billiard                          4.1.0
binaryornot                       0.4.4
binwalk                           2.1.0
black                             23.3.0
bleach                            6.0.0
blessed                           1.20.0
blessings                         1.7
blinker                           1.6.2
brewer2mpl                        1.4.1
bs4                               0.0.1
cachetools                        5.3.1
cairocffi                         1.5.1
Cartopy                           0.21.1
certifi                           2023.5.7
cffi                              1.15.1
cfgv                              3.3.1
ChainConsumer                     0.34.0
chardet                           5.1.0
charset-normalizer                3.1.0
click                             8.1.3
cloudpickle                       2.2.1
cmyt                              1.2.0
colorama                          0.4.6
colorspacious                     1.1.2
comm                              0.1.3
commonmark                        0.9.1
configobj                         5.0.8
constantly                        15.1.0
contourpy                         1.0.7
cookiecutter                      2.1.1
corner                            2.2.2
coverage                          7.2.7
cryptography                      41.0.1
cssselect                         1.2.0
cycler                            0.11.0
Cython                            0.29.35
debugpy                           1.6.7
decorator                         5.1.1
defusedxml                        0.7.1
Deprecated                        1.2.14
diff-match-patch                  20230430
dill                              0.3.6
distlib                           0.3.6
distro                            1.8.0
Django                            4.2.1
dnspython                         2.3.0
docker                            6.1.3
docker-pycreds                    0.4.0
docopt                            0.6.2
docstring-to-markdown             0.12
docutils                          0.18.1
emcee                             3.1.4
entrypoints                       0.4
envisage                          7.0.3
et-xmlfile                        1.1.0
ewah-bool-utils                   1.0.2
exceptiongroup                    1.1.1
executing                         1.2.0
fabric                            3.1.0
fasteners                         0.18
fastjsonschema                    2.17.1
file-magic                        0.4.1
filelock                          3.12.0
flake8                            6.0.0
Flask                             2.3.2
flatbuffers                       23.5.26
fonttools                         4.39.4
fortdepend                        2.1.0
fortran-language-server           1.12.0
fqdn                              1.5.1
frozenlist                        1.3.3
future                            0.18.3
gast                              0.5.4
gdata                             2.0.18
ggplot                            0.11.5
git-archive-all                   1.23.1
git-fame                          2.0.1
git-review                        2.3.1
google                            3.0.0
google-api-core                   2.11.0
google-api-python-client          2.88.0
google-auth                       2.19.1
google-auth-httplib2              0.1.0
google-auth-oauthlib              1.0.0
google-pasta                      0.2.0
googleapis-common-protos          1.59.0
graphviz                          0.20.1
grip                              4.6.1
grpcio                            1.54.2
gspread                           5.9.0
gTTS                              2.3.2
gTTS-token                        1.1.4
h5py                              3.8.0
html2text                         2020.1.16
html5lib                          1.1
httplib2                          0.22.0
humanize                          4.6.0
hyperlink                         21.0.0
hypothesis                        6.76.0
identify                          2.5.24
idna                              3.4
imageio                           2.30.0
imagesize                         1.4.1
importlib-metadata                6.6.0
importlib-resources               5.12.0
inception                         0.0.3
incremental                       22.10.0
inflection                        0.5.1
iniconfig                         2.0.0
iniparse                          0.5
inquirer                          3.1.3
intervaltree                      3.1.0
invoke                            2.1.2
IPy                               1.1
ipykernel                         6.23.1
ipyparallel                       8.6.1
ipython                           8.14.0
ipython-genutils                  0.2.0
ipytree                           0.2.2
ipywidgets                        8.0.6
isoduration                       20.11.0
isort                             5.12.0
itsdangerous                      2.1.2
jaraco.classes                    3.2.3
jedi                              0.18.2
jeepney                           0.8.0
jellyfish                         0.11.2
Jinja2                            3.1.2
jinja2-time                       0.2.0
json5                             0.9.14
jsonpointer                       2.3
jsonschema                        4.17.3
jupyter                           1.0.0
jupyter_client                    7.4.1
jupyter-console                   6.6.3
jupyter-contrib-core              0.4.2
jupyter-contrib-nbextensions      0.7.0
jupyter_core                      5.3.0
jupyter-events                    0.6.3
jupyter-highlight-selected-word   0.2.0
jupyter-lsp                       2.2.0
jupyter-nbextensions-configurator 0.6.3
jupyter-server                    1.24.0
jupyter_server_fileid             0.9.0
jupyter_server_terminals          0.4.4
jupyter_server_ydoc               0.8.0
jupyter-ydoc                      0.3.4
jupyterlab                        4.0.1
jupyterlab-pygments               0.2.2
jupyterlab_server                 2.22.1
jupyterlab-widgets                3.0.7
Keras-Applications                1.0.8
Keras-Preprocessing               1.1.2
keyring                           23.13.1
kiwisolver                        1.4.4
lazy-object-proxy                 1.9.0
lxml                              4.9.2
Mako                              1.2.4
Markdown                          3.4.3
markdown-it-py                    2.2.0
MarkupSafe                        2.1.3
matplotlib                        3.7.1
matplotlib-inline                 0.1.6
mccabe                            0.7.0
mdurl                             0.1.2
mistune                           2.0.5
mock                              5.0.2
monotonic                         1.6
more-itertools                    9.1.0
mpi4py                            3.1.4
mpldatacursor                     0.7.1
mpmath                            1.3.0
multidict                         6.0.4
mypy-extensions                   1.0.0
nbclassic                         1.0.0
nbclient                          0.7.4
nbconvert                         7.4.0
nbformat                          5.9.0
nest-asyncio                      1.5.6
networkx                          3.1
NeuroTools                        0.3.1
nodeenv                           1.8.0
nose                              1.3.7
notebook                          6.5.4
notebook_shim                     0.2.3
ntplib                            0.4.0
numexpr                           2.8.4
numpy                             1.24.3
numpy-quaternion                  2022.4.3
numpydoc                          1.5.0
oauth2client                      4.1.3
oauthlib                          3.2.2
olefile                           0.46
openconnect-sso                   0.7.3
opencv-python                     4.7.0.72
openpyxl                          3.1.2
opt-einsum                        3.3.0
ordered-set                       4.1.0
overrides                         7.3.1
packaging                         23.1
pandas                            2.0.2
pandas-datareader                 0.10.0
pandocfilters                     1.5.0
paramiko                          3.2.0
parso                             0.8.3
path                              16.6.0
path-and-address                  2.0.1
path.py                           12.5.0
pathlib2                          2.3.7.post1
pathspec                          0.11.1
patsy                             0.5.3
pbr                               5.11.1
pcpp                              1.30
pdf2image                         1.16.3
pep8                              1.7.1
pexpect                           4.8.0
pickleshare                       0.7.5
pid                               3.0.4
Pillow                            9.5.0
pip                               23.1.2
pip-review                        1.3.0
pipdate                           0.5.6
platformdirs                      3.5.1
plotly                            5.14.1
pluggy                            1.0.0
plumbum                           1.8.2
ply                               3.11
pre-commit                        3.3.2
prometheus-client                 0.17.0
prompt-toolkit                    3.0.38
protobuf                          4.23.2
psutil                            5.9.5
ptyprocess                        0.7.0
pure-eval                         0.2.2
py                                1.11.0
py-cpuinfo                        9.0.0
pyasn1                            0.5.0
pyasn1-modules                    0.3.0
pycairo                           1.23.0
pycodestyle                       2.10.0
pycparser                         2.21
pycups                            2.0.1
pydocstyle                        6.3.0
pydot                             1.4.2
pydotplus                         2.0.2
pyenchant                         3.2.2
pyerfa                            2.0.0.3
pyface                            8.0.0
pyflakes                          3.0.1
Pygments                          2.15.1
PyGObject                         3.44.1
pyinotify                         0.9.6
PyLaTeX                           1.4.1
pylint                            2.17.4
pylint-venv                       3.0.1
pyls-spyder                       0.4.0
PyNaCl                            1.5.0
PyOpenGL                          3.1.7
pypandoc                          1.11
pyparsing                         3.0.9
pypdf                             3.9.1
PyPDF2                            3.0.1
pyproj                            3.5.0
Pypubsub                          4.0.3
PyQt5                             5.15.9
PyQt5-Qt                          5.15.2
PyQt5-Qt5                         5.15.2
PyQt5-sip                         12.12.1
PyQt6                             6.5.1
PyQt6-Qt6                         6.5.1
PyQt6-sip                         13.5.1
PyQtWebEngine                     5.15.6
PyQtWebEngine-Qt5                 5.15.2
Pyro4                             4.82
pyrsistent                        0.19.3
pyshp                             2.3.1
PySide2                           5.13.2
PySocks                           1.7.1
pytest                            7.3.1
python-augeas                     1.1.0
python-dateutil                   2.8.2
python-editor                     1.0.4
python-json-logger                2.0.7
python-lsp-black                  1.3.0
python-lsp-jsonrpc                1.0.0
python-lsp-server                 1.7.3
python-slugify                    8.0.1
pytoolconfig                      1.2.5
pytz                              2023.3
pyudev                            0.24.1
pyusb                             1.2.1
pyxdg                             0.27
PyYAML                            6.0
pyzmq                             25.1.0
QDarkStyle                        3.1
qstylizer                         0.2.2
QtAwesome                         1.2.3
qtconsole                         5.4.3
QtPy                              2.3.1
readchar                          4.0.5
redis                             4.5.5
requests                          2.31.0
requests-file                     1.5.1
requests-ftp                      0.3.1
requests-oauthlib                 1.3.1
resolvelib                        1.0.1
retrying                          1.3.4
rfc3339-validator                 0.1.4
rfc3986-validator                 0.1.1
rich                              13.4.1
rope                              1.8.0
rope-py3k                         0.9.4.post1
rq                                1.15.0
rsa                               4.9
Rtree                             1.0.1
scikit-build                      0.17.6
scikit-umfpack                    0.3.3
scipy                             1.10.1
SecretStorage                     3.3.3
Send2Trash                        1.8.2
serpent                           1.41
setproctitle                      1.3.2
setuptools                        65.5.0
setuptools-scm                    7.1.0
shapely                           2.0.1
shiboken2                         5.13.2
simplegeneric                     0.8.1
simplejson                        3.19.1
sip                               6.7.9
six                               1.16.0
sniffio                           1.3.0
snowballstemmer                   2.2.0
sortedcontainers                  2.4.0
sos                               0.24.0
sos-bioinfo                       0.17.4
sos-pbs                           0.20.8
sos-rq                            0.18.0
soupsieve                         2.4.1
Sphinx                            6.2.1
sphinx-bootstrap-theme            0.8.1
sphinx-rtd-theme                  1.2.1
sphinxcontrib-applehelp           1.0.4
sphinxcontrib-devhelp             1.0.2
sphinxcontrib-htmlhelp            2.0.1
sphinxcontrib-jquery              4.1
sphinxcontrib-jsmath              1.0.1
sphinxcontrib-lunrsearch          0.4
sphinxcontrib-qthelp              1.0.3
sphinxcontrib-serializinghtml     1.1.5
sphinxcontrib-websupport          1.2.4
spyder                            5.4.3
spyder-kernels                    2.4.3
sqlparse                          0.4.4
stack-data                        0.6.2
statsmodels                       0.14.0
structlog                         21.1.0
sympy                             1.12
systemd-python                    235
tabulate                          0.9.0
tenacity                          8.2.2
tensorboard                       2.13.0
tensorboard-data-server           0.7.0
tensorboard-plugin-wit            1.8.1
tensorflow-estimator              2.12.0
termcolor                         2.3.0
terminado                         0.17.1
testpath                          0.6.0
text-unidecode                    1.3
textdistance                      4.5.0
threadpoolctl                     3.1.0
three-merge                       0.1.1
tikzplotlib                       0.10.1
tinycss2                          1.2.1
toml                              0.10.2
tomli                             2.0.1
tomli_w                           1.0.0
tomlkit                           0.11.8
tornado                           6.3.2
tqdm                              4.65.0
traitlets                         5.9.0
traits                            6.4.1
traitsui                          8.0.0
Twisted                           22.10.0
txaio                             23.1.1
typed-ast                         1.5.4
typing_extensions                 4.6.3
tzdata                            2023.3
ujson                             5.7.0
unyt                              2.9.5
uri-template                      1.2.0
uritemplate                       4.1.1
urllib3                           1.26.16
virtualenv                        20.23.0
voila                             0.4.0
vtk                               9.2.6
watchdog                          3.0.0
wcwidth                           0.2.6
webcolors                         1.13
webencodings                      0.5.1
websocket-client                  1.5.2
websockets                        11.0.3
Werkzeug                          2.3.4
whatthepatch                      1.0.5
wheel                             0.40.0
widgetsnbextension                4.0.7
wrapt                             1.15.0
wslink                            1.10.2
wurlitzer                         3.0.3
wxPython                          4.2.0
xlrd                              2.0.1
xlwt                              1.3.0
xxhash                            3.2.0
y-py                              0.6.0
yapf                              0.33.0
yarl                              1.9.2
youtube-dl                        2021.12.17
ypy-websocket                     0.8.4
yt                                4.2.0
zipp                              3.15.0
zope.interface                    6.0

```
</details>

**Comment by 2sn** [comment]
I have been using sypder for 3 h, no it no longer starts.  
Seemed nice, but apparently it is too unstable to be usable.

**Comment by 2sn** [comment]
It seemed I needed to remove the file `~/.config/spyder-py3/spyder.lock`.  (No, it was no longer running.)  Maybe spyder startup can cah whether locks are actually real?

**Comment by ccordoba12** [comment]
Hey @2sn, thanks for reporting. To fix the error you reported initially, you need to update to the latest Jupyter-client (i.e. 8.2.0). Let us know if it works for you.

You also said:

> How can it be reset?

    spyder --reset

> Maybe spyder startup can cah whether locks are actually real?

We do that but the process that holds the lock could be zombie. However, you can bypass that by running:

    spyder --new-instance

You could have learned about both those options by simply running

    spyder --help

Finally, we recommend to use Spyder with Anaconda/Miniconda instead of a custom Python installation. It should be more stable in that case.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
