### ISSUE TITLE
Focus change causes traceback

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#21]
_From [goth...@gmail.com](https://code.google.com/u/107413083286304800601/) on 2009-09-02T00:36:40Z_

What steps will reproduce the problem?

 1. Loose conection with volume that contains an active file
2. klick on the file in the editor.
3. Traceback produced What is the expected output? What do you see instead? IOexception should probably be caught. 

the output:

\>>> Traceback (most recent call last):   
File "C:\Python26\lib\site-packages\spyderlib\plugins\editor.py", line 378,
in focus_changed     self.refresh()   
File "C:\Python26\lib\site-packages\spyderlib\plugins\editor.py", line 454,
in refresh     self.__check_last_modified(index)   
File "C:\Python26\lib\site-packages\spyderlib\plugins\editor.py", line 435,
in __check_last_modified     self.reload(index)  
File "C:\Python26\lib\site-packages\spyderlib\plugins\editor.py", line 517,
in reload     txt, finfo.encoding = encoding.read(finfo.filename)   File
"C:\Python26\lib\site-packages\spyderlib\encoding.py", line 169, in read  
  text, encoding = decode( file(filename, 'rb').read() ) IOError: [Errno 2]
No such file or directory: u'E:\\henriksdal-3D-test.py' What version of the product are you using? On what operating system? python(x,y) 2.6.0 beta 3 on XP 

Please provide any additional information below

. This is not a showstopper but it should be an easy fix. It is getting
harder and harder to find those little bugs but I am still trying. =)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=21_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2009-09-02T05:46:52Z_

**Status:** Accepted

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2009-09-03T14:09:58Z_

fixed in v1.0.0beta6

Keep trying :)

**Status:** Fixed
