### ISSUE TITLE
`re.error` when running some searches in the Find/Replace widget

### ISSUE THREAD

**Issue by n100820a** [spyder-ide/spyder#21007]
### What steps will reproduce the problem?

ctrl+f 
to replace all `\u00b-2` with `$\mathregular{m^-2}$` 

### Traceback
```python-traceback
Traceback (most recent call last):
  File "D:\Python\lib\sre_parse.py", line 1051, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\m'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\lib\site-packages\spyder\widgets\findreplace.py", line 692, in replace_find_all
    cursor.insertText(re_pattern.sub(replace_text, text))
  File "D:\Python\lib\re.py", line 326, in _subx
    template = _compile_repl(template, pattern)
  File "D:\Python\lib\re.py", line 317, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "D:\Python\lib\sre_parse.py", line 1054, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \m at position 1
```

## Versions

* Spyder version: 5.4.1  (conda)
* Python version: 3.10.9 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<9.0.0       :  8.12.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.5.4 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.16.2 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.0;<1.8.0          :  1.7.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.2 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.6.3 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.4.1;<2.5.0 :  2.4.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.7.0 (OK)
numpy >=1.7                   :  1.23.5 (OK)
pandas >=1.1.1                :  1.5.3 (OK)
scipy >=0.17.0                :  1.10.0 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @n100820a, thanks for reporting. Could you post a screenshot of what exactly you wrote in the search and replace fields (in case you did, that's not clear from your description) that generated this error? Please don't forget to include the buttons that you toggled as well.

That will help us to reproduce your error on our side, which will make easier for us to solve it.

**Comment by FormalSymmetry** [comment]
I have experienced a similar error using search and replace. Spyder crashes when searching and replacing all occurrences of the following:
- Code to be searched: `plt.ylabel(r'$\Psi(t) = [\psi, \phi]^\mathrm{T}$')`
- Replacement code: `plt.ylabel(r'$$\Psi(t) = [\psi \; \phi]^\mathrm{T}$')`

**Comment by FormalSymmetry** [comment]
Here is the Traceback:
```
Traceback (most recent call last):
  File "sre_parse.py", line 1039, in parse_template
KeyError: '\\P'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\widgets\findreplace.py", line 697, in replace_find_all
    cursor.insertText(re_pattern.sub(replace_text, text))
  File "re.py", line 327, in _subx
  File "re.py", line 318, in _compile_repl
  File "sre_parse.py", line 1042, in parse_template
re.error: bad escape \P at position 14 (line 1, column 15)
```

**Comment by FormalSymmetry** [comment]
Happy to have helped, I appreciate your work! @ccordoba12
