### ISSUE TITLE
Kernel cannot be started

### ISSUE THREAD

**Issue by Hugo-vd-Wilt** [spyder-ide/spyder#21004]
### What steps will reproduce the problem?

Kernel gave an error saying it couldnt be started. I then tried to restart it, gave me a small error "Cannot restart a kernel not started by Spyder". When I then clicked on enter this error occured.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/Users/Hugo/opt/anaconda3/lib/python3.9/site-packages/qtconsole/console_widget.py", line 427, in eventFilter
    return self._event_filter_console_keypress(event)
  File "/Users/Hugo/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/ipythonconsole/widgets/debugging.py", line 652, in _event_filter_console_keypress
    return super(DebuggingWidget,
  File "/Users/Hugo/opt/anaconda3/lib/python3.9/site-packages/qtconsole/frontend_widget.py", line 378, in _event_filter_console_keypress
    return super()._event_filter_console_keypress(event)
  File "/Users/Hugo/opt/anaconda3/lib/python3.9/site-packages/qtconsole/console_widget.py", line 1272, in _event_filter_console_keypress
    self.execute(interactive = not shift_down)
  File "/Users/Hugo/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/ipythonconsole/widgets/shell.py", line 243, in execute
    super(ShellWidget, self).execute(source, hidden, interactive)
  File "/Users/Hugo/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/ipythonconsole/widgets/debugging.py", line 572, in execute
    return super(DebuggingWidget, self).execute(
  File "/Users/Hugo/opt/anaconda3/lib/python3.9/site-packages/qtconsole/console_widget.py", line 650, in execute
    self._register_is_complete_callback(
  File "/Users/Hugo/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/ipythonconsole/widgets/debugging.py", line 663, in _register_is_complete_callback
    return super(DebuggingWidget, self)._register_is_complete_callback(
  File "/Users/Hugo/opt/anaconda3/lib/python3.9/site-packages/qtconsole/console_widget.py", line 600, in _register_is_complete_callback
    self._is_complete_msg_id = self.kernel_client.is_complete(source)
AttributeError: 'NoneType' object has no attribute 'is_complete'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.7
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Darwin 22.3.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by dalthviz** [comment]
Hi @Hugo-vd-Wilt thank you for the feedback! I think this seems related with https://github.com/spyder-ide/spyder/issues/16381 . Also, maybe updating Spyder to the latest release (5.4.3) could help.

Let us know if the info above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
