### ISSUE TITLE
Latex rendering for plots fails.

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2102]
_From [hembreer...@gmail.com](https://code.google.com/u/112689957933859838790/) on 2015-01-02T11:32:12Z_

Spyder Version:  2.3.0rc
Python Version:  3.4.1
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Windows
pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  2.1.0 (OK)
pygments >=1.6  :  1.6 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  2.1.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1. Attempt to render latex text on a plot. This used to work and has recently stopped for some unidentified reason. 2. 3. 

What is the expected output? What do you see instead?

 I expect to see a plot with properly formatted labels from latex. Instead I get a plot with no labels and a series of errors from the python console. 

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt4.py", line 299, in resizeEvent
    self.draw()
  File "C:\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt4agg.py", line 154, in draw
    FigureCanvasAgg.draw(self)
  File "C:\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 451, in draw
    self.figure.draw(self.renderer)
  File "C:\Anaconda3\lib\site-packages\matplotlib\artist.py", line 56, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\matplotlib\figure.py", line 1035, in draw
    func(*args)
  File "C:\Anaconda3\lib\site-packages\matplotlib\artist.py", line 56, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\matplotlib\axes.py", line 2088, in draw
    a.draw(renderer)
  File "C:\Anaconda3\lib\site-packages\matplotlib\artist.py", line 56, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\matplotlib\axis.py", line 1094, in draw
    renderer)
  File "C:\Anaconda3\lib\site-packages\matplotlib\axis.py", line 1043, in _get_tick_bboxes
    extent = tick.label1.get_window_extent(renderer)
  File "C:\Anaconda3\lib\site-packages\matplotlib\text.py", line 755, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "C:\Anaconda3\lib\site-packages\matplotlib\text.py", line 321, in _get_layout
    ismath=False)
  File "C:\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 205, in get_text_width_height_descent
    renderer=self)
  File "C:\Anaconda3\lib\site-packages\matplotlib\texmanager.py", line 669, in get_text_width_height_descent
    page = next(iter(dvi))
  File "C:\Anaconda3\lib\site-packages\matplotlib\dviread.py", line 85, in __iter__
    have_page = self._read()
  File "C:\Anaconda3\lib\site-packages\matplotlib\dviread.py", line 146, in _read
    self._dispatch(byte)
  File "C:\Anaconda3\lib\site-packages\matplotlib\dviread.py", line 234, in _dispatch
    self._fnt_def(k, c, s, d, a, l, n)
  File "C:\Anaconda3\lib\site-packages\matplotlib\dviread.py", line 394, in _fnt_def
    tfm = _tfmfile(n[-l:].decode('ascii'))
  File "C:\Anaconda3\lib\site-packages\matplotlib\dviread.py", line 901, in _tfmfile
    return _fontfile(texname, Tfm, '.tfm', _tfmcache)
  File "C:\Anaconda3\lib\site-packages\matplotlib\dviread.py", line 891, in _fontfile
    filename = find_tex_file(texname + suffix)
  File "C:\Anaconda3\lib\site-packages\matplotlib\dviread.py", line 872, in find_tex_file
    stderr=subprocess.PIPE)
  File "C:\Anaconda3\lib\subprocess.py", line 858, in __init__
    restore_signals, start_new_session)
  File "C:\Anaconda3\lib\subprocess.py", line 1111, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt4.py", line 299, in resizeEvent
    self.draw()
  File "C:\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt4agg.py", line 154, in draw
    FigureCanvasAgg.draw(self)
  File "C:\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 451, in draw
    self.figure.draw(self.renderer)
  File "C:\Anaconda3\lib\site-packages\matplotlib\artist.py", line 56, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\matplotlib\figure.py", line 1035, in draw
    func(*args)
  File "C:\Anaconda3\lib\site-packages\matplotlib\artist.py", line 56, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\matplotlib\axes.py", line 2088, in draw
    a.draw(renderer)
  File "C:\Anaconda3\lib\site-packages\matplotlib\artist.py", line 56, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\matplotlib\axis.py", line 1094, in draw
    renderer)
  File "C:\Anaconda3\lib\site-packages\matplotlib\axis.py", line 1043, in _get_tick_bboxes
    extent = tick.label1.get_window_extent(renderer)
  File "C:\Anaconda3\lib\site-packages\matplotlib\text.py", line 755, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "C:\Anaconda3\lib\site-packages\matplotlib\text.py", line 321, in _get_layout
    ismath=False)
  File "C:\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 205, in get_text_width_height_descent
    renderer=self)
  File "C:\Anaconda3\lib\site-packages\matplotlib\texmanager.py", line 669, in get_text_width_height_descent
    page = next(iter(dvi))
  File "C:\Anaconda3\lib\site-packages\matplotlib\dviread.py", line 85, in __iter__
    have_page = self._read()
  File "C:\Anaconda3\lib\site-packages\matplotlib\dviread.py", line 146, in _read
    self._dispatch(byte)
  File "C:\Anaconda3\lib\site-packages\matplotlib\dviread.py", line 234, in _dispatch
    self._fnt_def(k, c, s, d, a, l, n)
  File "C:\Anaconda3\lib\site-packages\matplotlib\dviread.py", line 394, in _fnt_def
    tfm = _tfmfile(n[-l:].decode('ascii'))
  File "C:\Anaconda3\lib\site-packages\matplotlib\dviread.py", line 901, in _tfmfile
    return _fontfile(texname, Tfm, '.tfm', _tfmcache)
  File "C:\Anaconda3\lib\site-packages\matplotlib\dviread.py", line 891, in _fontfile
    filename = find_tex_file(texname + suffix)
  File "C:\Anaconda3\lib\site-packages\matplotlib\dviread.py", line 872, in find_tex_file
    stderr=subprocess.PIPE)
  File "C:\Anaconda3\lib\subprocess.py", line 858, in __init__
    restore_signals, start_new_session)
  File "C:\Anaconda3\lib\subprocess.py", line 1111, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified 

Please provide any additional information below

. Pasting of relevant code
import matplotlib
import numpy as np
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import os
from matplotlib.colors import LinearSegmentedColormap
import scipy.io as sio
\#####
\# Several hundred lines of data generation and formatting
\####...

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2102_

**Comment by spyder-issues-migrator** [comment]
_From [hembreer...@gmail.com](https://code.google.com/u/112689957933859838790/) on 2015-01-02T08:52:23Z_

reinstallling everything seems to have fixed the issue

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-02T17:35:19Z_

Ok, thanks for letting us know.

**Status:** Invalid
