### ISSUE TITLE
I am just trying to add to the path

### ISSUE THREAD

**Issue by dmebane** [spyder-ide/spyder#21121]
### What steps will reproduce the problem?

Add to the path -- it's a Google Drive path but it is also local

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/Users/dsmebane/anaconda3/lib/python3.10/site-packages/spyder/plugins/pythonpath/widgets/pathmanager.py", line 169, in <lambda>
    triggered=lambda x: self.add_path())
  File "/Users/dsmebane/anaconda3/lib/python3.10/site-packages/spyder/plugins/pythonpath/widgets/pathmanager.py", line 456, in add_path
    if self.listwidget.row(self.user_header) < 0:
RuntimeError: wrapped C/C++ object of type QListWidgetItem has been deleted
```

## Versions

* Spyder version: 5.4.1  (conda)
* Python version: 3.10.9 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Darwin 22.5.0

### Dependencies

```
# Mandatory:
applaunchservices >=0.3.0     :  0.3.0 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<9.0.0       :  8.10.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.5.4 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.16.2 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.0;<1.8.0          :  1.7.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.6.3 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.4.1;<2.5.0 :  2.4.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.7.0 (OK)
numpy >=1.7                   :  1.23.5 (OK)
pandas >=1.1.1                :  1.5.3 (OK)
scipy >=0.17.0                :  1.10.0 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at /Users/dsmebane/anaconda3:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12             pyhd3eb1b0_0  
anaconda-client           1.11.2          py310hca03da5_0  
anaconda-navigator        2.4.2           py310hca03da5_0  
anaconda-project          0.11.1          py310hca03da5_0  
anyio                     3.5.0           py310hca03da5_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
applaunchservices         0.3.0           py310hca03da5_0  
appnope                   0.1.2           py310hca03da5_1001  
appscript                 1.1.2           py310h1a28f6b_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0          py310h1a28f6b_0  
arrow                     1.2.3           py310hca03da5_1  
astroid                   2.14.2          py310hca03da5_0  
astropy                   5.1             py310h96f19d2_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
atomicwrites              1.4.0                      py_0  
attrs                     22.1.0          py310hca03da5_0  
automat                   20.2.0                     py_0  
autopep8                  1.6.0              pyhd3eb1b0_1  
babel                     2.11.0          py310hca03da5_0  
backcall                  0.2.0              pyhd3eb1b0_0  
backports                 1.1                pyhd3eb1b0_0  
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0  
backports.tempfile        1.0                pyhd3eb1b0_1  
backports.weakref         1.0.post1                  py_1  
bcrypt                    3.2.0           py310h1a28f6b_1  
beautifulsoup4            4.11.1          py310hca03da5_0  
binaryornot               0.4.4              pyhd3eb1b0_1  
black                     22.6.0          py310hca03da5_0  
blas                      1.0                    openblas  
bleach                    4.1.0              pyhd3eb1b0_0  
blosc                     1.21.3               h313beb8_0  
bokeh                     2.4.3           py310hca03da5_0  
boltons                   23.0.0          py310hca03da5_0  
bottleneck                1.3.5           py310h96f19d2_0  
brotli                    1.0.9                h1a28f6b_7  
brotli-bin                1.0.9                h1a28f6b_7  
brotlipy                  0.7.0           py310h1a28f6b_1002  
brunsli                   0.1                  hc377ac9_1  
bzip2                     1.0.8                h620ffc9_4  
c-ares                    1.18.1               h1a28f6b_0  
ca-certificates           2023.05.30           hca03da5_0  
cctools                   949.0.1             hc179dcd_25  
cctools_osx-arm64         949.0.1             h332cad3_25  
certifi                   2023.5.7        py310hca03da5_0  
cffi                      1.15.1          py310h80987f9_3  
cfitsio                   3.470                h7f6438f_7  
chardet                   4.0.0           py310hca03da5_1003  
charls                    2.2.0                hc377ac9_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4           py310hca03da5_0  
cloudpickle               2.0.0              pyhd3eb1b0_0  
clyent                    1.2.2           py310hca03da5_1  
colorama                  0.4.6           py310hca03da5_0  
colorcet                  3.0.1           py310hca03da5_0  
comm                      0.1.2           py310hca03da5_0  
conda                     23.3.1          py310hca03da5_0  
conda-build               3.24.0          py310hca03da5_0  
conda-content-trust       0.1.3           py310hca03da5_0  
conda-pack                0.6.0              pyhd3eb1b0_0  
conda-package-handling    2.0.2           py310hca03da5_0  
conda-package-streaming   0.7.0           py310hca03da5_0  
conda-repo-cli            1.0.41          py310hca03da5_0  
conda-token               0.4.0              pyhd3eb1b0_0  
conda-verify              3.4.2                      py_1  
constantly                15.1.0          py310hca03da5_0  
contourpy                 1.0.5           py310h525c30c_0  
cookiecutter              1.7.3              pyhd3eb1b0_0  
cryptography              39.0.1          py310h834c97f_0  
cssselect                 1.1.0              pyhd3eb1b0_0  
curl                      7.87.0               h80987f9_0  
cycler                    0.11.0             pyhd3eb1b0_0  
cytoolz                   0.12.0          py310h1a28f6b_0  
dask                      2022.7.0        py310hca03da5_0  
dask-core                 2022.7.0        py310hca03da5_0  
datashader                0.14.4          py310hca03da5_0  
datashape                 0.5.4           py310hca03da5_1  
debugpy                   1.5.1           py310hc377ac9_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
diff-match-patch          20200713           pyhd3eb1b0_0  
dill                      0.3.6           py310hca03da5_0  
distributed               2022.7.0        py310hca03da5_0  
docstring-to-markdown     0.11            py310hca03da5_0  
docutils                  0.18.1          py310hca03da5_3  
entrypoints               0.4             py310hca03da5_0  
et_xmlfile                1.1.0           py310hca03da5_0  
executing                 0.8.3              pyhd3eb1b0_0  
filelock                  3.9.0           py310hca03da5_0  
flake8                    6.0.0           py310hca03da5_0  
flask                     2.2.2           py310hca03da5_0  
flit-core                 3.6.0              pyhd3eb1b0_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.12.1               h1192e45_0  
fsspec                    2022.11.0       py310hca03da5_0  
future                    0.18.3          py310hca03da5_0  
gensim                    4.3.0           py310h46d7db6_0  
gettext                   0.21.0               h826f4ad_0  
giflib                    5.2.1                h80987f9_3  
glib                      2.69.1               h514c7bf_2  
glob2                     0.7                pyhd3eb1b0_0  
gmp                       6.2.1                hc377ac9_3  
gmpy2                     2.1.2           py310h8c48613_0  
greenlet                  2.0.1           py310h313beb8_0  
gst-plugins-base          1.14.1               h313beb8_1  
gstreamer                 1.14.1               h80987f9_1  
h5py                      3.7.0           py310h181c318_0  
hdf5                      1.12.1               h160e8cb_2  
heapdict                  1.0.1              pyhd3eb1b0_0  
holoviews                 1.15.4          py310hca03da5_0  
huggingface_hub           0.10.1          py310hca03da5_0  
hvplot                    0.8.2           py310hca03da5_0  
hyperlink                 21.0.0             pyhd3eb1b0_0  
icu                       68.1                 hc377ac9_0  
idna                      3.4             py310hca03da5_0  
imagecodecs               2021.8.26       py310h48bc37f_2  
imageio                   2.26.0          py310hca03da5_0  
imagesize                 1.4.1           py310hca03da5_0  
imbalanced-learn          0.10.1          py310hca03da5_0  
importlib-metadata        4.11.3          py310hca03da5_0  
importlib_metadata        4.11.3               hd3eb1b0_0  
incremental               21.3.0             pyhd3eb1b0_0  
inflection                0.5.1           py310hca03da5_0  
iniconfig                 1.1.1              pyhd3eb1b0_0  
intake                    0.6.7           py310hca03da5_0  
intervaltree              3.1.0              pyhd3eb1b0_0  
ipykernel                 6.19.2          py310h33ce5c2_0  
ipython                   8.10.0          py310hca03da5_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
isort                     5.9.3              pyhd3eb1b0_0  
itemadapter               0.3.0              pyhd3eb1b0_0  
itemloaders               1.0.4              pyhd3eb1b0_1  
itsdangerous              2.0.1              pyhd3eb1b0_0  
jedi                      0.18.1          py310hca03da5_1  
jellyfish                 0.9.0           py310h1a28f6b_0  
jinja2                    3.1.2           py310hca03da5_0  
jinja2-time               0.2.0              pyhd3eb1b0_3  
jmespath                  0.10.0             pyhd3eb1b0_0  
joblib                    1.1.1           py310hca03da5_0  
jpeg                      9e                   h80987f9_1  
jq                        1.6                  h1a28f6b_1  
json5                     0.9.6              pyhd3eb1b0_0  
jsonpatch                 1.32               pyhd3eb1b0_0  
jsonpointer               2.1                pyhd3eb1b0_0  
jsonschema                4.17.3          py310hca03da5_0  
jupyter_client            7.3.4           py310hca03da5_0  
jupyter_core              5.2.0           py310hca03da5_0  
jupyter_server            1.23.4          py310hca03da5_0  
jupyterlab                3.5.3           py310hca03da5_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.19.0          py310hca03da5_0  
jxrlib                    1.1                  h1a28f6b_2  
keyring                   23.4.0          py310hca03da5_0  
kiwisolver                1.4.4           py310h313beb8_0  
krb5                      1.19.4               h8380606_0  
lazy-object-proxy         1.6.0           py310h1a28f6b_0  
lcms2                     2.12                 hba8e193_0  
ld64                      530                 hb29bf3f_25  
ld64_osx-arm64            530                 h001ce53_25  
ldid                      2.1.2                h64d1936_2  
lerc                      3.0                  hc377ac9_0  
libaec                    1.0.4                hc377ac9_1  
libarchive                3.6.2                h3d4dd14_0  
libbrotlicommon           1.0.9                h1a28f6b_7  
libbrotlidec              1.0.9                h1a28f6b_7  
libbrotlienc              1.0.9                h1a28f6b_7  
libclang                  12.0.0          default_hc321e17_4  
libcurl                   7.87.0               h0f1d93c_0  
libcxx                    14.0.6               h848a8c0_0  
libdeflate                1.17                 h80987f9_0  
libedit                   3.1.20221030         h80987f9_0  
libev                     4.33                 h1a28f6b_1  
libffi                    3.4.2                hca03da5_6  
libgfortran               5.0.0           11_3_0_hca03da5_28  
libgfortran5              11.3.0              h009349e_28  
libiconv                  1.16                 h1a28f6b_2  
liblief                   0.12.3               h313beb8_0  
libllvm11                 11.1.0               h12f7ac0_6  
libllvm12                 12.0.0               h12f7ac0_4  
libllvm14                 14.0.6               h7ec7a93_2  
libnghttp2                1.46.0               h95c9599_0  
libopenblas               0.3.21               h269037a_0  
libpng                    1.6.39               h80987f9_0  
libpq                     12.9                 h65cfe13_3  
libprotobuf               3.20.3               h514c7bf_0  
libsodium                 1.0.18               h1a28f6b_0  
libspatialindex           1.9.3                hc377ac9_0  
libssh2                   1.10.0               hf27765b_0  
libtiff                   4.5.0                h313beb8_2  
libuv                     1.44.2               h80987f9_0  
libwebp                   1.2.4                ha3663a8_1  
libwebp-base              1.2.4                h80987f9_1  
libxml2                   2.9.14               h8c5e841_0  
libxslt                   1.1.35               h9833966_0  
libzopfli                 1.0.3                hc377ac9_0  
llvm-openmp               14.0.6               hc6e5704_0  
llvmlite                  0.39.1          py310h98b2900_0  
locket                    1.0.0           py310hca03da5_0  
lxml                      4.9.1           py310h2fae87d_0  
lz4                       3.1.3           py310h1a28f6b_0  
lz4-c                     1.9.4                h313beb8_0  
lzo                       2.10                 h1a28f6b_2  
markdown                  3.4.1           py310hca03da5_0  
markupsafe                2.1.1           py310h1a28f6b_0  
matplotlib                3.7.0           py310hca03da5_0  
matplotlib-base           3.7.0           py310h46d7db6_0  
matplotlib-inline         0.1.6           py310hca03da5_0  
mccabe                    0.7.0              pyhd3eb1b0_0  
mistune                   0.8.4           py310h1a28f6b_1000  
mock                      4.0.3              pyhd3eb1b0_0  
mpc                       1.1.0                h8c48613_1  
mpfr                      4.0.2                h695f6f0_1  
mpmath                    1.2.1                    pypi_0    pypi
msgpack-python            1.0.3           py310h525c30c_0  
multipledispatch          0.6.0           py310hca03da5_0  
munkres                   1.1.4                      py_0  
mypy_extensions           0.4.3           py310hca03da5_1  
navigator-updater         0.3.0           py310hca03da5_0  
nbclassic                 0.5.2           py310hca03da5_0  
nbclient                  0.5.13          py310hca03da5_0  
nbconvert                 6.5.4           py310hca03da5_0  
nbformat                  5.7.0           py310hca03da5_0  
ncurses                   6.4                  h313beb8_0  
nest-asyncio              1.5.6           py310hca03da5_0  
networkx                  2.8.4           py310hca03da5_0  
ninja                     1.10.2               hca03da5_5  
ninja-base                1.10.2               h525c30c_5  
nltk                      3.7                pyhd3eb1b0_0  
notebook                  6.5.2           py310hca03da5_0  
notebook-shim             0.2.2           py310hca03da5_0  
nspr                      4.33                 hc377ac9_0  
nss                       3.74                 h142855e_0  
numba                     0.56.4          py310h46d7db6_0  
numexpr                   2.8.4           py310hecc3335_0  
numpy                     1.23.5          py310hb93e574_0  
numpy-base                1.23.5          py310haf87e8b_0  
numpydoc                  1.5.0           py310hca03da5_0  
oniguruma                 6.9.7.1              h1a28f6b_0  
openjpeg                  2.3.0                h7a6adac_2  
openpyxl                  3.0.10          py310h1a28f6b_0  
openssl                   1.1.1u               h1a28f6b_0  
packaging                 22.0            py310hca03da5_0  
pandas                    1.5.3           py310h46d7db6_0  
pandocfilters             1.5.0              pyhd3eb1b0_0  
panel                     0.14.3          py310hca03da5_0  
param                     1.12.3          py310hca03da5_0  
parsel                    1.6.0           py310hca03da5_0  
parso                     0.8.3              pyhd3eb1b0_0  
partd                     1.2.0              pyhd3eb1b0_1  
patch                     2.7.6             h1a28f6b_1001  
pathlib                   1.0.1              pyhd3eb1b0_1  
pathspec                  0.10.3          py310hca03da5_0  
patsy                     0.5.3           py310hca03da5_0  
pcre                      8.45                 hc377ac9_0  
pep8                      1.7.1           py310hca03da5_1  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.4.0           py310h313beb8_0  
pip                       22.3.1          py310hca03da5_0  
pkginfo                   1.9.6           py310hca03da5_0  
platformdirs              2.5.2           py310hca03da5_0  
plotly                    5.9.0           py310hca03da5_0  
pluggy                    1.0.0           py310hca03da5_1  
ply                       3.11            py310hca03da5_0  
pooch                     1.4.0              pyhd3eb1b0_0  
poyo                      0.5.0              pyhd3eb1b0_0  
prometheus_client         0.14.1          py310hca03da5_0  
prompt-toolkit            3.0.36          py310hca03da5_0  
protego                   0.1.16                     py_0  
psutil                    5.9.0           py310h1a28f6b_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
py                        1.11.0             pyhd3eb1b0_0  
py-lief                   0.12.3          py310h313beb8_0  
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                      py_0  
pycodestyle               2.10.0          py310hca03da5_0  
pycosat                   0.6.4           py310h1a28f6b_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyct                      0.5.0           py310hca03da5_0  
pycurl                    7.45.1                   pypi_0    pypi
pydispatcher              2.0.5           py310hca03da5_2  
pydocstyle                6.3.0           py310hca03da5_0  
pyerfa                    2.0.0           py310h1a28f6b_0  
pyflakes                  3.0.1           py310hca03da5_0  
pygments                  2.11.2             pyhd3eb1b0_0  
pyhamcrest                2.0.2              pyhd3eb1b0_2  
pyjwt                     2.4.0           py310hca03da5_0  
pylint                    2.16.2          py310hca03da5_0  
pylint-venv               2.3.0           py310hca03da5_0  
pyls-spyder               0.4.0              pyhd3eb1b0_0  
pyobjc-core               9.0             py310h3eb5a62_1  
pyobjc-framework-cocoa    9.0             py310hb094c41_0  
pyobjc-framework-coreservices 9.0             py310hdd8dd1f_0  
pyobjc-framework-fsevents 9.0             py310hca03da5_0  
pyodbc                    4.0.34          py310hc377ac9_0  
pyopenssl                 23.0.0          py310hca03da5_0  
pyparsing                 3.0.9           py310hca03da5_0  
pyqt                      5.15.7          py310hc377ac9_0  
pyqt5-sip                 12.11.0                  pypi_0    pypi
pyqtwebengine             5.15.7          py310hc377ac9_0  
pyrsistent                0.18.0          py310h1a28f6b_0  
pysocks                   1.7.1           py310hca03da5_0  
pytables                  3.7.0           py310ha5d4e50_1  
pytest                    7.1.2           py310hca03da5_0  
python                    3.10.9               hc0d8a6c_1  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.16.2          py310hca03da5_0  
python-libarchive-c       2.9                pyhd3eb1b0_1  
python-lsp-black          1.2.1           py310hca03da5_0  
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0  
python-lsp-server         1.7.1           py310hca03da5_0  
python-slugify            5.0.2              pyhd3eb1b0_0  
python-snappy             0.6.1           py310h313beb8_0  
python.app                3               py310h1a28f6b_0  
pytoolconfig              1.2.5           py310hca03da5_1  
pytorch                   1.12.1          cpu_py310h8370978_1  
pytz                      2022.7          py310hca03da5_0  
pyviz_comms               2.0.2              pyhd3eb1b0_0  
pywavelets                1.4.1           py310h80987f9_0  
pyyaml                    6.0             py310h80987f9_1  
pyzmq                     23.2.0          py310hc377ac9_0  
qdarkstyle                3.0.2              pyhd3eb1b0_0  
qstylizer                 0.2.2           py310hca03da5_0  
qt-main                   5.15.2               ha2d02b5_7  
qt-webengine              5.15.9               h2903aaf_4  
qtawesome                 1.2.2           py310hca03da5_0  
qtconsole                 5.4.0           py310hca03da5_0  
qtpy                      2.2.0           py310hca03da5_0  
qtwebkit                  5.212                h0f11f3c_4  
queuelib                  1.5.0           py310hca03da5_0  
readline                  8.2                  h1a28f6b_0  
regex                     2022.7.9        py310h1a28f6b_0  
requests                  2.28.1          py310hca03da5_0  
requests-file             1.5.1              pyhd3eb1b0_0  
requests-toolbelt         0.9.1              pyhd3eb1b0_0  
rope                      1.7.0           py310hca03da5_0  
rtree                     1.0.1           py310hca03da5_0  
ruamel.yaml               0.17.21         py310h1a28f6b_0  
ruamel.yaml.clib          0.2.6           py310h1a28f6b_1  
ruamel_yaml               0.17.21         py310h1a28f6b_0  
scikit-image              0.19.3          py310h313beb8_1  
scikit-learn              1.2.1           py310h313beb8_0  
scipy                     1.10.0          py310h20cbe94_1  
scrapy                    2.8.0           py310hca03da5_0  
seaborn                   0.12.2          py310hca03da5_0  
send2trash                1.8.0              pyhd3eb1b0_1  
service_identity          18.1.0             pyhd3eb1b0_1  
setuptools                65.6.3          py310hca03da5_0  
sip                       6.6.2           py310hc377ac9_0  
six                       1.16.0             pyhd3eb1b0_1  
sleef                     3.5.1                hf27765b_1  
smart_open                5.2.1           py310hca03da5_0  
snappy                    1.1.9                hc377ac9_0  
sniffio                   1.2.0           py310hca03da5_1  
snowballstemmer           2.2.0              pyhd3eb1b0_0  
sortedcontainers          2.4.0              pyhd3eb1b0_0  
soupsieve                 2.3.2.post1     py310hca03da5_0  
sphinx                    5.0.2           py310hca03da5_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0  
spyder                    5.4.1           py310hca03da5_0  
spyder-kernels            2.4.1           py310hca03da5_0  
sqlalchemy                1.4.39          py310h1a28f6b_0  
sqlite                    3.40.1               h7a7dc30_0  
stack_data                0.2.0              pyhd3eb1b0_0  
statsmodels               0.13.5          py310hbda83bc_1  
sympy                     1.11.1          py310hca03da5_0  
tabulate                  0.8.10          py310hca03da5_0  
tapi                      1100.0.11            h8754e6a_1  
tbb                       2021.7.0             h48ca7d4_0  
tbb4py                    2021.7.0        py310h48ca7d4_0  
tblib                     1.7.0              pyhd3eb1b0_0  
tenacity                  8.0.1           py310hca03da5_1  
terminado                 0.17.1          py310hca03da5_0  
text-unidecode            1.3                pyhd3eb1b0_0  
textdistance              4.2.1              pyhd3eb1b0_0  
threadpoolctl             2.2.0              pyh0d69192_0  
three-merge               0.1.1              pyhd3eb1b0_0  
tifffile                  2021.7.2           pyhd3eb1b0_2  
tinycss2                  1.2.1           py310hca03da5_0  
tk                        8.6.12               hb8d0fd4_0  
tldextract                3.2.0              pyhd3eb1b0_0  
tokenizers                0.11.4          py310h5c5695e_1  
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.1           py310hca03da5_0  
tomlkit                   0.11.1          py310hca03da5_0  
toolz                     0.12.0          py310hca03da5_0  
tornado                   6.1             py310h1a28f6b_0  
tqdm                      4.64.1          py310hca03da5_0  
traitlets                 5.7.1           py310hca03da5_0  
transformers              4.24.0          py310hca03da5_0  
twisted                   22.2.0          py310h1a28f6b_1  
typing-extensions         4.4.0           py310hca03da5_0  
typing_extensions         4.4.0           py310hca03da5_0  
tzdata                    2022g                h04d1e81_0  
ujson                     5.4.0           py310hc377ac9_0  
unidecode                 1.2.0              pyhd3eb1b0_0  
unixodbc                  2.3.11               h1a28f6b_0  
urllib3                   1.26.14         py310hca03da5_0  
w3lib                     1.21.0             pyhd3eb1b0_0  
watchdog                  2.1.6           py310h1a28f6b_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1           py310hca03da5_1  
websocket-client          0.58.0          py310hca03da5_4  
werkzeug                  2.2.2           py310hca03da5_0  
whatthepatch              1.0.2           py310hca03da5_0  
wheel                     0.38.4          py310hca03da5_0  
wrapt                     1.14.1          py310h1a28f6b_0  
wurlitzer                 3.0.2           py310hca03da5_0  
xarray                    2022.11.0       py310hca03da5_0  
xlwings                   0.29.1          py310hca03da5_0  
xz                        5.2.10               h80987f9_1  
yaml                      0.2.5                h1a28f6b_0  
yapf                      0.31.0             pyhd3eb1b0_0  
zeromq                    4.3.4                hc377ac9_0  
zfp                       0.5.5                hc377ac9_6  
zict                      2.1.0           py310hca03da5_0  
zipp                      3.11.0          py310hca03da5_0  
zlib                      1.2.13               h5a0b063_0  
zope                      1.0             py310hca03da5_1  
zope.interface            5.4.0           py310h1a28f6b_0  
zstandard                 0.19.0          py310h80987f9_0  
zstd                      1.5.2                h8574219_0  

```
</details>

**Comment by ccordoba12** [comment]
Hey @dmebane, thanks for reporting. This problem is fixed in our latest version available in Anaconda (5.4.3). Please update by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).
