### ISSUE TITLE
'metadata-generation-failed' on MacBook M2 Pro

### ISSUE THREAD

**Issue by enesgencer18** [spyder-ide/spyder#21138]
## Problem Description
Hello everyone,

I tried to download Spyder in a Python environment and I faced with the following error. The problem appeared to be because of PyQt5. 

However, I already downloaded PyQt5 with 'brew', but the version is different 5.15.7_2.

Also, I downloaded Spyder from the official web page and it works without any problem.

Why I can't download it to a specific environment.

Thanks.

```
Collecting pyqt5<5.16 (from spyder)
  Using cached PyQt5-5.15.9.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "/Users/enesgencer/Documents/PyEnvironments/crop-classification/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/enesgencer/Documents/PyEnvironments/crop-classification/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/enesgencer/Documents/PyEnvironments/crop-classification/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/bh/pzyttl2s1mv01_bycqsg_qpr0000gn/T/pip-build-env-uktw3jou/overlay/lib/python3.11/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/bh/pzyttl2s1mv01_bycqsg_qpr0000gn/T/pip-build-env-uktw3jou/overlay/lib/python3.11/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/bh/pzyttl2s1mv01_bycqsg_qpr0000gn/T/pip-build-env-uktw3jou/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 586, in setup
          self.apply_user_defaults(tool)
        File "/private/var/folders/bh/pzyttl2s1mv01_bycqsg_qpr0000gn/T/pip-install-xgpy9oaq/pyqt5_7a65d00099d34111a7861e1846fc1824/project.py", line 68, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/bh/pzyttl2s1mv01_bycqsg_qpr0000gn/T/pip-build-env-uktw3jou/overlay/lib/python3.11/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/bh/pzyttl2s1mv01_bycqsg_qpr0000gn/T/pip-build-env-uktw3jou/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/bh/pzyttl2s1mv01_bycqsg_qpr0000gn/T/pip-build-env-uktw3jou/overlay/lib/python3.11/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

```

* Operating System name/version: macOS 13.4.1
* Chip: Apple M2 Pro

**Comment by ccordoba12** [comment]
Hey @enesgencer18, thanks for reporting. You said:

> I tried to download Spyder in a Python environment and I faced with the following error. The problem appeared to be because of PyQt5.

This error means that there are no wheels available for your platform (i.e. Python binary packages) for the graphical toolkit Spyder is built on (i.e. PyQt5).

> However, I already downloaded PyQt5 with 'brew', but the version is different 5.15.7_2.

For that to work, you need to install Spyder in the same Python installation provided by brew, not in another environment.

> Also, I downloaded Spyder from the official web page and it works without any problem.

That's our main recommendation, i.e. please use our Mac app to save yourself a lot of troubles.

> Why I can't download it to a specific environment.

You can, but using regular Python environments because of the lack of PyQt5 wheels. Instead, you need to use conda environments, as described in [our documentation](http://docs.spyder-ide.org/current/installation.html#conda-based-distributions).

**Comment by ccordoba12** [comment]
I'm going to close this issue because I answered all your questions.
