### ISSUE TITLE
crash when disabling linting

### ISSUE THREAD

**Issue by CTAYLOR888** [spyder-ide/spyder#21147]
### What steps will reproduce the problem?

In Preferences - General uncheck Enable Kite Provider and Enable LSP Provider

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/ctaylor888/miniconda3/envs/sb3-2/lib/python3.10/site-packages/spyder/plugins/preferences/widgets/configdialog.py", line 136, in button_clicked
    configpage.apply_changes()
  File "/home/ctaylor888/miniconda3/envs/sb3-2/lib/python3.10/site-packages/spyder/plugins/preferences/api.py", line 108, in apply_changes
    self.apply_callback()
  File "/home/ctaylor888/miniconda3/envs/sb3-2/lib/python3.10/site-packages/spyder/plugins/preferences/api.py", line 140, in <lambda>
    self._apply_settings_tabs(self.changed_options))
  File "/home/ctaylor888/miniconda3/envs/sb3-2/lib/python3.10/site-packages/spyder/plugins/preferences/api.py", line 168, in _apply_settings_tabs
    self.apply_settings(options)
  File "/home/ctaylor888/miniconda3/envs/sb3-2/lib/python3.10/site-packages/spyder/api/preferences.py", line 105, in wrapper
    func(opts)
  File "/home/ctaylor888/miniconda3/envs/sb3-2/lib/python3.10/site-packages/spyder/api/plugins/new_api.py", line 550, in apply_conf
    self.after_configuration_update(list(options_set))
  File "/home/ctaylor888/miniconda3/envs/sb3-2/lib/python3.10/site-packages/spyder/plugins/completion/plugin.py", line 403, in after_configuration_update
    self.unregister_statusbar(provider_name)
  File "/home/ctaylor888/miniconda3/envs/sb3-2/lib/python3.10/site-packages/spyder/plugins/completion/plugin.py", line 477, in unregister_statusbar
    if id_ in container.statusbar_widgets[id_]:
TypeError: argument of type 'KiteStatusWidget' is not iterable
```

## Versions

* Spyder version: 5.2.2 
* Python version: 3.10.11
* Qt version: 5.15.4
* PyQt5 version: 5.15.7
* Operating System: Linux 5.15.90.1-microsoft-standard-WSL2

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.2.1 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.13.1 (OK)
nbconvert >=4.0               :  6.5.4 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.15.1 (OK)
pylint >=2.5.0                :  2.16.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.2 (OK)
qtawesome >=1.0.2             :  1.2.2 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  67.8.0 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  25.1.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.7.1 (OK)
numpy >=1.7                   :  1.24.3 (OK)
pandas >=1.1.1                :  2.0.3 (OK)
scipy >=0.17.0                :  1.11.1 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @CTAYLOR888, thanks for reporting. This problem is fixed in our latest version available in Anaconda (5.4.3). Please update by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-conda).
