### ISSUE TITLE
Variable explorer is not working

### ISSUE THREAD

**Issue by bulentkarakus** [spyder-ide/spyder#21211]
### What steps will reproduce the problem?

I am getting issue reporter screen when I try to view a dataframe in variable explorer. I updated my spyder but it didn't resolve the issue.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\open_ai\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionsdelegate.py", line 211, in createEditor
    if not editor.setup_and_check(value, title=key):
  File "C:\ProgramData\Miniconda3\envs\open_ai\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 957, in setup_and_check
    self.dataModel = DataFrameModel(data, parent=self)
  File "C:\ProgramData\Miniconda3\envs\open_ai\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 135, in __init__
    self.max_min_col_update()
  File "C:\ProgramData\Miniconda3\envs\open_ai\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 244, in max_min_col_update
    for __, col in self.df.iteritems():
  File "C:\ProgramData\Miniconda3\envs\open_ai\lib\site-packages\pandas\core\generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'iteritems'
```

## Versions

* Spyder version: 5.4.0  (conda)
* Python version: 3.9.15 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.1.0 (OK)
cloudpickle >=0.5.0           :  2.2.1 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20230430 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.2 (OK)
jellyfish >=0.7               :  1.0.0 (OK)
jsonschema >=3.2.0            :  4.18.6 (OK)
keyring >=17.0.0              :  24.2.0 (OK)
nbconvert >=4.0               :  7.7.3 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  3.3.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.5 (OK)
pygments >=2.0                :  2.15.1 (OK)
pylint >=2.5.0;<3.0           :  2.17.5 (OK)
pylint_venv >=2.1.1           :  3.0.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.6.0;<1.7.0          :  1.6.0 (OK)
pylsp_black >=1.2.0           :  1.3.0 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.3 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.3 (OK)
qtpy >=2.1.0                  :  2.3.1 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  68.0.0 (OK)
sphinx >=0.6.6                :  5.3.0 (OK)
spyder_kernels >=2.4.0;<2.5.0 :  2.4.4 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  3.0.0 (OK)
zmq >=22.1.0                  :  25.1.0 (OK)

# Optional:
cython >=0.21                 :  0.29.36 (OK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  1.25.2 (OK)
pandas >=1.1.1                :  2.0.3 (OK)
scipy >=0.17.0                :  1.11.1 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @bulentkarakus, thanks for reporting. This problem is fixed in our latest version available in Anaconda (5.4.3). Please update by closing Spyder, opening the Anaconda Prompt and running the commands

    conda activate open_ai
    conda install spyder=5.4.3
