### ISSUE TITLE
Changed python interpreter to anaconda env

### ISSUE THREAD

**Issue by C1earwater** [spyder-ide/spyder#21268]
### What steps will reproduce the problem?

1. new env on anaconda, install python and pygame
2. python interpreter, use the python in the new env
3. restart kernel

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1945, in close_client
  File "C:\ProgramData\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1478, in create_new_client
  File "C:\ProgramData\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 163, in __init__
  File "C:\ProgramData\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 251, in _create_loading_page
AttributeError: 'NoneType' object has no attribute 'replace'
```

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.11.4 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  1.7.3 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.12.2 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  0.9.0 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  6.5.4 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.2.0 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.0.0 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.4 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  23.2.0 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.7.1 (OK)
numpy >=1.7                                      :  1.24.3 (OK)
pandas >=1.1.1                                   :  2.0.3 (OK)
scipy >=0.17.0                                   :  1.11.1 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)
```

### Environment

<details><summary>Environment</summary>

```

```
</details>

**Comment by dalthviz** [comment]
Hi @C1earwater thank you for the feedback! Seems like a similar traceback has appeared in the issue tracker before (https://github.com/spyder-ide/spyder/issues/21052 https://github.com/spyder-ide/spyder/issues/20826) when running some commands to install packages 🤔 

Also, seems like you are using Spyder from the anaconda base env and then you created a new env and set is Python interpreter as the custom one Spyder uses, rigth? Did you install `spyder-kernels` in the new env?

Any other info in order to better understand what could be causing the traceback is greatly appreciated. Let us know!

**Comment by dalthviz** [comment]
Closing due to lack of response
