### ISSUE TITLE
`PermissionError` when trying to set icon for files in Files pane

### ISSUE THREAD

**Issue by FredJiangpingfei** [spyder-ide/spyder#21304]
### What steps will reproduce the problem?

import nltk
# nltk.download('punkt')
from nltk.tokenize import word_tokenize
import numpy as np
import pandas as pd
from gensim.models.doc2vec import Doc2Vec, TaggedDocument

file_path = "C:/Users/jiang/OneDrive - Kingston University/RESEARCH/Python Files/ChatGPT project Raw data.xlsx"
df = pd.read_excel(file_path, sheet_name = "Raw data")

# =============================================================================
# Doc2Vec
# =============================================================================
tagged_data_PD = []
tagged_data_GPT = []
# tokenizing each observation of the variable "product description"
for i, doc_text in enumerate(df["Product_description"]):  
    tokens = word_tokenize(doc_text.lower())
    tagged_data_PD.append(TaggedDocument(words=tokens, tags=[str(i)]))
    
for i, doc_text in enumerate(df["ChatGPT_result"]):  
    tokens = word_tokenize(doc_text.lower())
    tagged_data_GPT.append(TaggedDocument(words=tokens, tags=[str(i)]))

    
# Doc2Vec model training
PD_model = Doc2Vec(vector_size=20, window=5, min_count=1, workers=4, epochs=100)
PD_model.build_vocab(tagged_data_PD)
PD_model.train(tagged_data_PD, total_examples=PD_model.corpus_count, epochs=PD_model.epochs)

GPT_model = Doc2Vec(vector_size=20, window=5, min_count=1, workers=4, epochs=100)
GPT_model.build_vocab(tagged_data_GPT)
GPT_model.train(tagged_data_GPT, total_examples=GPT_model.corpus_count, epochs=GPT_model.epochs)

# Get the document vector for a specific document (e.g., the first document in the XLSX)
PD_document_vectors = []
for i, j in enumerate(tagged_data_PD):
    PD_document_vectors.append(PD_model.docvecs[str(i)])
    
df["doc2vec_PD"] = PD_document_vectors

GPT_document_vectors = []
for i, j in enumerate(tagged_data_GPT):
    GPT_document_vectors.append(GPT_model.docvecs[str(i)])
    
df["doc2vec_GPT"] = GPT_document_vectors

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\plugins\explorer\widgets\utils.py", line 111, in icon
    icon = ima.get_icon_by_extension_or_type(fname,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\utils\icon_manager.py", line 457, in get_icon_by_extension_or_type
    mime_type, __ = mime.guess_type(basename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 306, in guess_type
    init()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 368, in init
    db.read_windows_registry()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 253, in read_windows_registry
    _mimetypes_read_windows_registry(add_type)
PermissionError: [WinError 5] Access is denied
Traceback (most recent call last):
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\plugins\explorer\widgets\utils.py", line 111, in icon
    icon = ima.get_icon_by_extension_or_type(fname,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\utils\icon_manager.py", line 457, in get_icon_by_extension_or_type
    mime_type, __ = mime.guess_type(basename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 306, in guess_type
    init()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 368, in init
    db.read_windows_registry()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 253, in read_windows_registry
    _mimetypes_read_windows_registry(add_type)
PermissionError: [WinError 5] Access is denied
Traceback (most recent call last):
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\plugins\explorer\widgets\utils.py", line 111, in icon
    icon = ima.get_icon_by_extension_or_type(fname,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\utils\icon_manager.py", line 457, in get_icon_by_extension_or_type
    mime_type, __ = mime.guess_type(basename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 306, in guess_type
    init()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 368, in init
    db.read_windows_registry()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 253, in read_windows_registry
    _mimetypes_read_windows_registry(add_type)
PermissionError: [WinError 5] Access is denied
Traceback (most recent call last):
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\plugins\explorer\widgets\utils.py", line 111, in icon
    icon = ima.get_icon_by_extension_or_type(fname,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\utils\icon_manager.py", line 457, in get_icon_by_extension_or_type
    mime_type, __ = mime.guess_type(basename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 306, in guess_type
    init()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 368, in init
    db.read_windows_registry()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 253, in read_windows_registry
    _mimetypes_read_windows_registry(add_type)
PermissionError: [WinError 5] Access is denied
Traceback (most recent call last):
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\plugins\explorer\widgets\utils.py", line 111, in icon
    icon = ima.get_icon_by_extension_or_type(fname,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\utils\icon_manager.py", line 457, in get_icon_by_extension_or_type
    mime_type, __ = mime.guess_type(basename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 306, in guess_type
    init()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 368, in init
    db.read_windows_registry()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 253, in read_windows_registry
    _mimetypes_read_windows_registry(add_type)
PermissionError: [WinError 5] Access is denied
Traceback (most recent call last):
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\plugins\explorer\widgets\utils.py", line 111, in icon
    icon = ima.get_icon_by_extension_or_type(fname,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\utils\icon_manager.py", line 457, in get_icon_by_extension_or_type
    mime_type, __ = mime.guess_type(basename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 306, in guess_type
    init()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 368, in init
    db.read_windows_registry()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 253, in read_windows_registry
    _mimetypes_read_windows_registry(add_type)
PermissionError: [WinError 5] Access is denied
Traceback (most recent call last):
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\plugins\explorer\widgets\utils.py", line 111, in icon
    icon = ima.get_icon_by_extension_or_type(fname,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\utils\icon_manager.py", line 457, in get_icon_by_extension_or_type
    mime_type, __ = mime.guess_type(basename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 306, in guess_type
    init()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 368, in init
    db.read_windows_registry()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 253, in read_windows_registry
    _mimetypes_read_windows_registry(add_type)
PermissionError: [WinError 5] Access is denied
Traceback (most recent call last):
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\plugins\explorer\widgets\utils.py", line 111, in icon
    icon = ima.get_icon_by_extension_or_type(fname,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\utils\icon_manager.py", line 457, in get_icon_by_extension_or_type
    mime_type, __ = mime.guess_type(basename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 306, in guess_type
    init()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 368, in init
    db.read_windows_registry()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 253, in read_windows_registry
    _mimetypes_read_windows_registry(add_type)
PermissionError: [WinError 5] Access is denied
Traceback (most recent call last):
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\plugins\explorer\widgets\utils.py", line 111, in icon
    icon = ima.get_icon_by_extension_or_type(fname,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\utils\icon_manager.py", line 457, in get_icon_by_extension_or_type
    mime_type, __ = mime.guess_type(basename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 306, in guess_type
    init()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 368, in init
    db.read_windows_registry()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 253, in read_windows_registry
    _mimetypes_read_windows_registry(add_type)
PermissionError: [WinError 5] Access is denied
Traceback (most recent call last):
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\plugins\explorer\widgets\utils.py", line 111, in icon
    icon = ima.get_icon_by_extension_or_type(fname,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\utils\icon_manager.py", line 457, in get_icon_by_extension_or_type
    mime_type, __ = mime.guess_type(basename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 306, in guess_type
    init()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 368, in init
    db.read_windows_registry()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 253, in read_windows_registry
    _mimetypes_read_windows_registry(add_type)
PermissionError: [WinError 5] Access is denied
Traceback (most recent call last):
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\plugins\explorer\widgets\utils.py", line 111, in icon
    icon = ima.get_icon_by_extension_or_type(fname,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\utils\icon_manager.py", line 457, in get_icon_by_extension_or_type
    mime_type, __ = mime.guess_type(basename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 306, in guess_type
    init()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 368, in init
    db.read_windows_registry()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 253, in read_windows_registry
    _mimetypes_read_windows_registry(add_type)
PermissionError: [WinError 5] Access is denied
Traceback (most recent call last):
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\plugins\explorer\widgets\utils.py", line 111, in icon
    icon = ima.get_icon_by_extension_or_type(fname,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\utils\icon_manager.py", line 457, in get_icon_by_extension_or_type
    mime_type, __ = mime.guess_type(basename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 306, in guess_type
    init()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 368, in init
    db.read_windows_registry()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 253, in read_windows_registry
    _mimetypes_read_windows_registry(add_type)
PermissionError: [WinError 5] Access is denied
Traceback (most recent call last):
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\plugins\explorer\widgets\utils.py", line 111, in icon
    icon = ima.get_icon_by_extension_or_type(fname,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\utils\icon_manager.py", line 457, in get_icon_by_extension_or_type
    mime_type, __ = mime.guess_type(basename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 306, in guess_type
    init()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 368, in init
    db.read_windows_registry()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 253, in read_windows_registry
    _mimetypes_read_windows_registry(add_type)
PermissionError: [WinError 5] Access is denied
Traceback (most recent call last):
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\plugins\explorer\widgets\utils.py", line 111, in icon
    icon = ima.get_icon_by_extension_or_type(fname,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\utils\icon_manager.py", line 457, in get_icon_by_extension_or_type
    mime_type, __ = mime.guess_type(basename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 306, in guess_type
    init()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 368, in init
    db.read_windows_registry()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 253, in read_windows_registry
    _mimetypes_read_windows_registry(add_type)
PermissionError: [WinError 5] Access is denied
Traceback (most recent call last):
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\plugins\explorer\widgets\utils.py", line 111, in icon
    icon = ima.get_icon_by_extension_or_type(fname,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\utils\icon_manager.py", line 457, in get_icon_by_extension_or_type
    mime_type, __ = mime.guess_type(basename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 306, in guess_type
    init()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 368, in init
    db.read_windows_registry()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 253, in read_windows_registry
    _mimetypes_read_windows_registry(add_type)
PermissionError: [WinError 5] Access is denied
Traceback (most recent call last):
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\plugins\explorer\widgets\utils.py", line 111, in icon
    icon = ima.get_icon_by_extension_or_type(fname,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\utils\icon_manager.py", line 457, in get_icon_by_extension_or_type
    mime_type, __ = mime.guess_type(basename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 306, in guess_type
    init()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 368, in init
    db.read_windows_registry()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 253, in read_windows_registry
    _mimetypes_read_windows_registry(add_type)
PermissionError: [WinError 5] Access is denied
Traceback (most recent call last):
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\plugins\explorer\widgets\utils.py", line 111, in icon
    icon = ima.get_icon_by_extension_or_type(fname,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\site-packages\spyder\utils\icon_manager.py", line 457, in get_icon_by_extension_or_type
    mime_type, __ = mime.guess_type(basename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 306, in guess_type
    init()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 368, in init
    db.read_windows_registry()
  File "C:\Users\jiang\anaconda3\Lib\mimetypes.py", line 253, in read_windows_registry
    _mimetypes_read_windows_registry(add_type)
PermissionError: [WinError 5] Access is denied
```

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.11.4 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  1.7.3 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.12.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  0.9.0 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  6.5.4 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.2.0 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.0.0 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.3 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  23.2.0 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.7.1 (OK)
numpy >=1.7                                      :  1.24.3 (OK)
pandas >=1.1.1                                   :  1.5.3 (OK)
scipy >=0.17.0                                   :  1.10.1 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @FredJiangpingfei, thanks for reporting. We'll take a look at this problem in our next version (5.5.0), to be released next month.

In the meantime, I suggest to move the files you're working with out of your One Drive directory.
