### ISSUE TITLE
Charles - student (cdonisth@gmail.com)

### ISSUE THREAD

**Issue by cdonisth** [spyder-ide/spyder#21339]
I (cdonisth@gmail.com) am trying to install onto my M1 MAC Mini. Affter in stall I start Spyder and get the following errors then it hangs.  I have run navigot before - 2 years ago. what's changed? I want to run with Python 3.7 . Error messages follow: 

    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: 
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
      File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    'silent_exec_method')TypeError
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method

Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method

Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply

Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
      File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: 
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
      File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: 
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
      File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method

Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
      File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
      File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
      File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
      File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
      File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
      File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    'silent_exec_method')TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
      File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 352, in silent_exec_method
    'silent_exec_method')
TypeError: 
Traceback (most recent call last):
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
      File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/charlesd/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')

Charles

**Comment by ccordoba12** [comment]
Hey @cdonisth, thanks for reporting. You said:

> Affter in stall I start Spyder and get the following errors then it hangs. I have run navigot before - 2 years ago. what's changed?

Open source software changes quite quickly and it's not expected for it to keep working as with old versions (although we try our best to make that happen).

> I want to run with Python 3.7 . Error messages follow:

You should be able to solve this problem by closing Spyder, opening a terminal and running there

    conda install qtconsole=5.3.2

If that doesn't help, I'm afraid you'll have to remove Anaconda and reinstall its latest version instead.

Let us know if that works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by cdonisth** [comment]
Sorry for the delay.
Fixed! Thanks

From: Carlos Cordoba ***@***.***>
Date: Sunday, 1 October 2023 at 03:01
To: spyder-ide/spyder ***@***.***>
Cc: cdonisth ***@***.***>, Mention ***@***.***>
Subject: Re: [spyder-ide/spyder] Charles - student ***@***.***) (Issue #21339)

Closing due to lack of response.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
