### ISSUE TITLE
Error changing the default layout

### ISSUE THREAD

**Issue by adrielcgx** [spyder-ide/spyder#21354]
### What steps will reproduce the problem?

I use the default layout and from the view menu Id change to the R layout and got an error.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/spyder/plugins/layout/container.py", line 192, in <lambda>
    return lambda: self.quick_layout_switch(i)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/spyder/plugins/layout/container.py", line 438, in quick_layout_switch
    self._current_quick_layout = names.index(
                                 ^^^^^^^^^^^^
ValueError: 'Rstudio layout' is not in list
```

## Versions

* Spyder version: 5.4.4  (pip)
* Python version: 3.11.5 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Linux-6.1.53-1-lts-x86_64-with-glibc2.38

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                                                        :  1.4.1 (OK)
chardet >=2.0.0                                                             :  5.2.0 (OK)
cloudpickle >=0.5.0                                                         :  2.2.1 (OK)
cookiecutter >=1.6.0                                                        :  2.3.0 (OK)
diff_match_patch >=20181111                                                 :  20200713 (OK)
intervaltree >=3.0.2                                                        :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0,!=8.11.0,!=8.12.0,!=8.12.1 :  8.15.0 (OK)
jedi >=0.17.2,<0.19.0                                                       :  0.19.0 (NOK)
jellyfish >=0.7                                                             :  1.0.1 (OK)
jsonschema >=3.2.0                                                          :  4.19.0 (OK)
keyring >=17.0.0                                                            :  24.2.0 (OK)
nbconvert >=4.0                                                             :  7.8.0 (OK)
numpydoc >=0.6.0                                                            :  1.5.0 (OK)
parso >=0.7.0,<0.9.0                                                        :  0.8.3 (OK)
pexpect >=4.4.0                                                             :  4.8.0 (OK)
pickleshare >=0.4                                                           :  0.7.5 (OK)
psutil >=5.3                                                                :  5.9.5 (OK)
pygments >=2.0                                                              :  2.16.1 (OK)
pylint >=2.5.0,<3.0                                                         :  2.17.5 (OK)
pylint_venv >=3.0.2                                                         :  3.0.2 (OK)
pyls_spyder >=0.4.0                                                         :  0.4.0 (OK)
pylsp >=1.7.4,<1.8.0                                                        :  1.7.4 (OK)
pylsp_black >=1.2.0,<3.0.0                                                  :  1.3.0 (OK)
qdarkstyle >=3.0.2,<3.2.0                                                   :  3.1 (OK)
qstylizer >=0.2.2                                                           :  0.2.2 (OK)
qtawesome >=1.2.1                                                           :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                                                    :  5.4.3 (OK)
qtpy >=2.1.0                                                                :  2.3.1 (OK)
rtree >=0.9.7                                                               :  1.0.1 (OK)
setuptools >=49.6.0                                                         :  68.0.0 (OK)
sphinx >=0.6.6                                                              :  7.2.6 (OK)
spyder_kernels >=2.4.4,<2.5.0                                               :  2.4.4 (OK)
textdistance >=4.2.0                                                        :  4.5.0 (OK)
three_merge >=0.1.1                                                         :  0.1.1 (OK)
watchdog >=0.10.3                                                           :  2.3.0 (OK)
xdg >=0.26                                                                  :  0.28 (OK)
zmq >=22.1.0                                                                :  25.1.1 (OK)

# Optional:
cython >=0.21                                                               :  3.0.2 (OK)
matplotlib >=3.0.0                                                          :  3.7.3 (OK)
numpy >=1.7                                                                 :  1.25.2 (OK)
pandas >=1.1.1                                                              :  1.5.3 (OK)
scipy >=0.17.0                                                              :  None (NOK)
sympy >=0.7.3                                                               :  None (NOK)
```

### Environment

<details><summary>Environment</summary>

```

```
</details>

**Comment by ccordoba12** [comment]
Hey @adrielcgx, thanks for reporting. Please close Spyder, open a terminal and run there

    spyder --reset

Then start Spyder and try again. Hopefully that will solve your problem.

**Comment by adrielcgx** [comment]
Thanks @ccordoba12 that work well.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it
