### ISSUE TITLE
Errors when running a file in PyQt API #1

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2137]
_From [vuribe1...@gmail.com](https://code.google.com/u/108827072894102038659/) on 2015-01-25T13:22:46Z_

Spyder Version:  2.2.5
Python Version:  2.7.6
Qt Version    :  4.8.6, PyQt4 (API v1) 4.10.4 on Linux
pyflakes >=0.5.0:  None (NOK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  1.2.1 (OK)
rope >=0.9.2    :  None (NOK)
sphinx >=0.6.6  :  None (NOK)
matplotlib >=1.0:  None (NOK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1. try to run any program or blank file
2. get error
3. be disappointed (cuz this was a really cool program) 

What is the expected output? What do you see instead?

 Very simple string manipulation is what I expect...but still gives error below with empty py file.

\>>> Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/externalconsole.py", line 696, in run_script_in_current_shell
    "and try again.") &#37; osp.basename(filename), QMessageBox.Ok)
  File "/usr/lib/python2.7/posixpath.py", line 121, in basename
    i = p.rfind('/') + 1
AttributeError: 'QString' object has no attribute 'rfind' 

Please provide any additional information below

. I can not access the settings/preferences menu at all. The problem above might be fixed by changing the python interpreter but I can not access the preferences menu. Where is the config file?

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2137_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-25T21:39:09Z_

Please update to Spyder 2.3.2 and try again. The 2.2 series is now unsupported.

**Summary:** Errors when running a file in PyQt API `#1`  \<span class="oldvalue"> (was: Traceback line 121 and 696) \</span>  
  **Labels:** Cat-Console

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-30T14:17:37Z_

Closing because of lack of response. I hope your error is fixed after updating :-)

**Status:** WontFix
