### ISSUE TITLE
Can not reach Preferences window

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2138]
_From [vuribe1...@gmail.com](https://code.google.com/u/108827072894102038659/) on 2015-01-25T13:29:40Z_

Spyder Version:  2.2.5
Python Version:  2.7.6
Qt Version    :  4.8.6, PyQt4 (API v1) 4.10.4 on Linux
pyflakes >=0.5.0:  None (NOK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  1.2.1 (OK)
rope >=0.9.2    :  None (NOK)
sphinx >=0.6.6  :  None (NOK)
matplotlib >=1.0:  None (NOK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1. click preferences icon
2. get error
3. be sad 

What is the expected output? What do you see instead?

 preferences window

\>>> Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 1853, in edit_preferences
    widget = plugin.create_configwidget(dlg)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/__init__.py", line 179, in create_configwidget
    configwidget.initialize()
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/externalconsole.py", line 67, in initialize
    PluginConfigPage.initialize(self)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/configdialog.py", line 49, in initialize
    self.setup_page()
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/externalconsole.py", line 307, in setup_page
    interpreter=interpreter)
  File "/usr/lib/python2.7/dist-packages/spyderlib/utils/programs.py", line 255, in is_module_installed
    return eval(output)
  File "<string>", line 1
    [0;36m  File [0;32m"/tmp/spyder-biktor/tmpDH4jIb.py"[0;36m, line [0;32m114[0m
    ^
SyntaxError: invalid syntax 

Please provide any additional information below

. I cannot find the config file to try and reset the setting to default on linux

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2138_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-08T11:18:37Z_

No idea what you did ;-) But you can fix it by running in a console:

    spyder --reset

and then you'll be happy again!

**Status:** WontFix
