### ISSUE TITLE
Connecting to kernel takes eternity

### ISSUE THREAD

**Issue by anouarlachheb** [spyder-ide/spyder#21385]
### What steps will reproduce the problem?

1. Open/Add a new unit test file
2. Rename that fiel from the Hard disk
3. Close Spyder
4. Re-open Spyder

### Traceback
```python-traceback
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\site-packages\jupyter_client\threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\site-packages\jupyter_client\threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\site-packages\zmq\eventloop\zmqstream.py", line 634, in _handle_events
    self._handle_recv()
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\site-packages\zmq\eventloop\zmqstream.py", line 663, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\site-packages\jupyter_client\threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\site-packages\jupyter_client\threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback AddThreadSelectorEventLoop._handle_select([5232], [])
handle: <Handle AddThreadSelectorEventLoop._handle_select([5232], [])>
Traceback (most recent call last):
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\site-packages\tornado\platform\asyncio.py", line 620, in _handle_select
    self._handle_event(r, self._readers)
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\site-packages\tornado\platform\asyncio.py", line 634, in _handle_event
    callback()
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\site-packages\tornado\platform\asyncio.py", line 192, in _handle_events
    handler_func(fileobj, events)
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\site-packages\zmq\eventloop\zmqstream.py", line 634, in _handle_events
    self._handle_recv()
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\site-packages\zmq\eventloop\zmqstream.py", line 663, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\site-packages\jupyter_client\threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\LAA6RT\.conda\envs\Ariso\lib\site-packages\jupyter_client\threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
```

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.9.13 64-bit
* Qt version: 5.15.6
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.1 (OK)
chardet >=2.0.0                                  :  5.1.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  2.1.1 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.0.2 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.12.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.2 (OK)
jellyfish >=0.7                                  :  0.9.0 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  7.3.1 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  3.1.0 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.5 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.17.3 (OK)
pylint_venv >=2.1.1                              :  3.0.1 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.1 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.3.1 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  67.7.2 (OK)
sphinx >=0.6.6                                   :  6.2.1 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.3 (OK)
textdistance >=4.2.0                             :  4.5.0 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  3.0.0 (OK)
zmq >=22.1.0                                     :  25.0.2 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.7.1 (OK)
numpy >=1.7                                      :  1.24.3 (OK)
pandas >=1.1.1                                   :  2.0.1 (OK)
scipy >=0.17.0                                   :  1.10.1 (OK)
sympy >=0.7.3                                    :  None (NOK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at C:\Users\LAA6RT\.conda\envs\Ariso:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.13             pyhd8ed1ab_0    conda-forge
anyio                     3.7.1                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.2.3              pyhd8ed1ab_0    conda-forge
astroid                   2.15.4           py39hcbf5309_0    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.3                    pypi_0    pypi
atomicwrites              1.4.1              pyhd8ed1ab_0    conda-forge
attrs                     22.2.0             pyh71513ae_0    conda-forge
autopep8                  2.0.2              pyhd8ed1ab_0    conda-forge
babel                     2.12.1             pyhd8ed1ab_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bcrypt                    3.2.2            py39ha55989b_1    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
black                     23.3.0           py39hcbf5309_0    conda-forge
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
bosch-ca                  1.0                           1    defaults
brotli                    1.0.9                hcfcfb64_8    conda-forge
brotli-bin                1.0.9                hcfcfb64_8    conda-forge
brotlipy                  0.7.0           py39ha55989b_1005    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2023.5.7             h56e8100_0    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39h68f70e3_3    conda-forge
chardet                   5.1.0            py39hcbf5309_0    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
click                     8.1.3           win_pyhd8ed1ab_2    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
clr_loader                0.2.5              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.1.3              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.7            py39h1f6ef14_0    conda-forge
cookiecutter              2.1.1              pyh6c4a22f_0    conda-forge
cryptography              40.0.2           py39hb6bd5e6_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
debugpy                   1.6.7            py39h99910a6_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
dill                      0.3.6              pyhd8ed1ab_1    conda-forge
docstring-to-markdown     0.12               pyhd8ed1ab_0    conda-forge
docutils                  0.19             py39hcbf5309_1    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.2                    pypi_0    pypi
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
flake8                    6.0.0              pyhd8ed1ab_0    conda-forge
fonttools                 4.39.3           py39ha55989b_0    conda-forge
fqdn                      1.5.1                    pypi_0    pypi
freetype                  2.12.1               h546665d_1    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
glib                      2.76.2               h12be248_0    conda-forge
glib-tools                2.76.2               h12be248_0    conda-forge
gst-plugins-base          1.22.0               h001b923_2    conda-forge
gstreamer                 1.22.0               h6b5321d_2    conda-forge
icu                       72.1                 h63175ca_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        6.6.0              pyha770c72_0    conda-forge
importlib-resources       5.12.0             pyhd8ed1ab_0    conda-forge
importlib_metadata        6.6.0                hd8ed1ab_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
inflection                0.5.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2023.1.0         h57928b3_46319    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 6.22.0             pyh025b116_0    conda-forge
ipython                   8.12.0             pyh08f2357_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isoduration               20.11.0                  pypi_0    pypi
isort                     5.12.0             pyhd8ed1ab_1    conda-forge
jaraco.classes            3.2.3              pyhd8ed1ab_0    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jellyfish                 0.9.0            py39ha55989b_2    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jinja2-time               0.2.0              pyhd8ed1ab_3    conda-forge
json5                     0.9.14                   pypi_0    pypi
jsonpointer               2.4                      pypi_0    pypi
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter-client            7.4.1                    pypi_0    pypi
jupyter-events            0.6.3                    pypi_0    pypi
jupyter-lsp               2.2.0                    pypi_0    pypi
jupyter-server            1.24.0                   pypi_0    pypi
jupyter-server-terminals  0.4.4                    pypi_0    pypi
jupyter_core              5.3.0            py39hcbf5309_0    conda-forge
jupyterlab                4.0.2                    pypi_0    pypi
jupyterlab-server         2.23.0                   pypi_0    pypi
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
keyring                   23.13.1          py39hcbf5309_0    conda-forge
kiwisolver                1.4.4            py39h1f6ef14_1    conda-forge
krb5                      1.20.1               heb0366b_0    conda-forge
lazy-object-proxy         1.9.0            py39ha55989b_0    conda-forge
lcms2                     2.15                 h3e3b177_1    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libbrotlicommon           1.0.9                hcfcfb64_8    conda-forge
libbrotlidec              1.0.9                hcfcfb64_8    conda-forge
libbrotlienc              1.0.9                hcfcfb64_8    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libclang                  16.0.2          default_h8b4101f_0    conda-forge
libclang13                16.0.2          default_h45d3cf4_0    conda-forge
libdeflate                1.18                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.76.2               he8f3873_0    conda-forge
libhwloc                  2.9.1                h51c2c0f_0    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
libjpeg-turbo             2.1.5.1              hcfcfb64_0    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libsqlite                 3.40.0               hcfcfb64_1    conda-forge
libtiff                   4.5.0                h6c8260b_6    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.3.0                hcfcfb64_0    conda-forge
libwebp-base              1.3.0                hcfcfb64_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.10.4               hc3477c8_0    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.1.2            py39ha55989b_0    conda-forge
matplotlib                3.7.1            py39hcbf5309_0    conda-forge
matplotlib-base           3.7.1            py39haf65ace_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mccabe                    0.7.0              pyhd8ed1ab_0    conda-forge
mistune                   2.0.5              pyhd8ed1ab_0    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
more-itertools            9.1.0              pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
nbclassic                 1.0.0                    pypi_0    pypi
nbclient                  0.7.4              pyhd8ed1ab_0    conda-forge
nbconvert                 7.3.1              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.3.1              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.3.1              pyhd8ed1ab_0    conda-forge
nbformat                  5.8.0              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
notebook                  6.5.4                    pypi_0    pypi
notebook-shim             0.2.3                    pypi_0    pypi
numpy                     1.24.3           py39h816b6a6_0    conda-forge
numpydoc                  1.5.0              pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.0                ha2aaf27_2    conda-forge
openssl                   3.1.0                hcfcfb64_2    conda-forge
overrides                 7.3.1                    pypi_0    pypi
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    2.0.1            py39h1679cfb_0    conda-forge
pandoc                    2.19.2               h57928b3_2    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
paramiko                  3.1.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pathspec                  0.11.1             pyhd8ed1ab_0    conda-forge
pcre2                     10.40                h17e33f8_0    conda-forge
pdb-attach                3.0.0                    pypi_0    pypi
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.5.0            py39haa1d754_0    conda-forge
pip                       23.1.1             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              3.3.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
ply                       3.11                       py_1    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
prometheus-client         0.17.1                   pypi_0    pypi
prompt-toolkit            3.0.38             pyha770c72_0    conda-forge
prompt_toolkit            3.0.38               hd8ed1ab_0    conda-forge
psutil                    5.9.5            py39ha55989b_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycodestyle               2.10.0             pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydocstyle                6.3.0              pyhd8ed1ab_0    conda-forge
pyflakes                  3.0.1              pyhd8ed1ab_0    conda-forge
pygments                  2.15.1             pyhd8ed1ab_0    conda-forge
pylint                    2.17.3             pyhd8ed1ab_0    conda-forge
pylint-venv               3.0.1              pyhd8ed1ab_0    conda-forge
pyls-spyder               0.4.0              pyhd8ed1ab_0    conda-forge
pynacl                    1.5.0            py39h09fa780_2    conda-forge
pyopenssl                 23.1.1             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7           py39hb77abff_3    conda-forge
pyqt5-sip                 12.11.0          py39h99910a6_3    conda-forge
pyqtwebengine             5.15.7           py39h2f4a3f1_3    conda-forge
pyrsistent                0.19.3           py39ha55989b_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.9.13          hcf16a7b_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.3             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7                    pypi_0    pypi
python-lsp-black          1.2.1              pyhd8ed1ab_0    conda-forge
python-lsp-jsonrpc        1.0.0              pyhd8ed1ab_0    conda-forge
python-lsp-server         1.7.2              pyhd8ed1ab_0    conda-forge
python-lsp-server-base    1.7.2              pyhd8ed1ab_0    conda-forge
python-slugify            8.0.1              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      3_cp39    conda-forge
pythonnet                 3.0.1              pyhd8ed1ab_0    conda-forge
pytoolconfig              1.2.5              pyhd8ed1ab_0    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyvisa                    1.13.0           py39hcbf5309_0    conda-forge
pywin32                   304              py39h99910a6_2    conda-forge
pywin32-ctypes            0.2.0           py39hcbf5309_1006    conda-forge
pywinpty                  2.0.10                   pypi_0    pypi
pyyaml                    6.0              py39ha55989b_5    conda-forge
pyzmq                     25.0.2           py39hea35a22_0    conda-forge
qdarkstyle                3.1                pyhd8ed1ab_0    conda-forge
qstylizer                 0.2.2              pyhd8ed1ab_0    conda-forge
qt-main                   5.15.8               h7f2b912_9    conda-forge
qt-webengine              5.15.8               h5b1ea0b_0    conda-forge
qtawesome                 1.2.3              pyhd8ed1ab_0    conda-forge
qtconsole                 5.4.2              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.4.2              pyha770c72_0    conda-forge
qtpy                      2.3.1              pyhd8ed1ab_0    conda-forge
requests                  2.28.2             pyhd8ed1ab_1    conda-forge
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rope                      1.7.0              pyhd8ed1ab_0    conda-forge
rtree                     1.0.1            py39h09fdee3_1    conda-forge
scipy                     1.10.1           py39hde5eda1_0    conda-forge
send2trash                1.8.2                    pypi_0    pypi
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
sip                       6.7.9            py39h99910a6_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.3.0                    pypi_0    pypi
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sphinx                    6.2.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.4              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
spyder                    5.4.3            py39hcbf5309_0    conda-forge
spyder-kernels            2.4.3           win_pyhd8ed1ab_0    conda-forge
sqlite                    3.40.0               hcfcfb64_1    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
tbb                       2021.9.0             h91493d7_0    conda-forge
terminado                 0.17.1                   pypi_0    pypi
text-unidecode            1.3                        py_0    conda-forge
textdistance              4.5.0              pyhd8ed1ab_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlkit                   0.11.7             pyha770c72_0    conda-forge
tornado                   6.3              py39ha55989b_0    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
typing                    3.10.0.0           pyhd8ed1ab_0    conda-forge
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
ujson                     5.7.0            py39h99910a6_0    conda-forge
unicodedata2              15.0.0           py39ha55989b_0    conda-forge
unidecode                 1.3.6              pyhd8ed1ab_0    conda-forge
uri-template              1.3.0                    pypi_0    pypi
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
vc                        14.3                h3d8a991_11    conda-forge
visa                      1.0.0                    pypi_0    pypi
voila                     0.4.1                    pypi_0    pypi
vs2015_runtime            14.34.31931         h4c5c07a_11    conda-forge
watchdog                  3.0.0            py39hcbf5309_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
webcolors                 1.13                     pypi_0    pypi
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.6.1                    pypi_0    pypi
websockets                11.0.3                   pypi_0    pypi
whatthepatch              1.0.4              pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
wrapt                     1.15.0           py39ha55989b_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yapf                      0.32.0             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zstd                      1.5.2                h12be248_6    conda-forge

```
</details>

**Comment by ccordoba12** [comment]
Hey @anouarlachheb, thanks for reporting. Please close Spyder, open the Anaconda Prompt and run there

    conda activate Ariso
    conda install jupyter_client=8

That should fix your problem, but let us know if it really does.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by anouarlachheb** [comment]
Hi @ccordoba12, sorry for the delay, the problem has been fixed. Thanks.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
