### ISSUE TITLE
use numpy to convert list data to array and check array content

### ISSUE THREAD

**Issue by Tai-ShengYeh** [spyder-ide/spyder#21410]
### What steps will reproduce the problem?

I use numpy to convert list data to array and check array content

response = requests.get("https://soprano.kikirpa.be/index.php?lib=sop&id=PR3_A_785_kikirpa&ds=baseline%20corrected&dl=1vca4d")
content = response.content.splitlines()
content = [line.decode("utf-8") for line in content]
data_dict = content[123]

data_array = np.array(data_dict)

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\Lib\site-packages\spyder\plugins\variableexplorer\widgets\arrayeditor.py", line 426, in setEditorData
    text = from_qvariant(index.model().data(index, Qt.DisplayRole), str)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\spyder\plugins\variableexplorer\widgets\arrayeditor.py", line 269, in data
    value = self.get_value(index)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\spyder\plugins\variableexplorer\widgets\arrayeditor.py", line 262, in get_value
    value = self._data[i, j]
            ~~~~~~~~~~^^^^^^
IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed
```

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.11.4 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  1.7.3 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.12.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  0.9.0 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  6.5.4 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.2.0 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.0.0 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.3 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  23.2.0 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.7.1 (OK)
numpy >=1.7                                      :  1.24.3 (OK)
pandas >=1.1.1                                   :  1.5.3 (OK)
scipy >=0.17.0                                   :  1.10.1 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)
```

**Comment by dalthviz** [comment]
Hi @Tai-ShengYeh thank you for reaching out! I tried locally and seems like things are working 🤔:

![image](https://github.com/spyder-ide/spyder/assets/16781833/05c84c3d-1dd2-4f07-a32d-670ce67ada2d)

However, checking my testing setup, seems like I have `numpy` 1.26.0. Could you check if updating `numpy` in your setup helps? Let us know!

**Comment by dalthviz** [comment]
Closing due to lack of response
