### ISSUE TITLE
Data frame not shown

### ISSUE THREAD

**Issue by SharowarKhan** [spyder-ide/spyder#21437]
### What steps will reproduce the problem?

I failed to see my dataframe from variable explorer. 

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\variableexplorer\widgets\collectionsdelegate.py", line 213, in createEditor
    if not editor.setup_and_check(value, title=key):
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 957, in setup_and_check
    self.dataModel = DataFrameModel(data, parent=self)
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 138, in __init__
    self.max_min_col_update()
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 247, in max_min_col_update
    for __, col in self.df.items():
  File "C:\Program Files\Spyder\pkgs\pandas\core\frame.py", line 1349, in items
    yield k, self._get_item_cache(k)
  File "C:\Program Files\Spyder\pkgs\pandas\core\frame.py", line 4255, in _get_item_cache
    loc = self.columns.get_loc(item)
  File "C:\Program Files\Spyder\pkgs\pandas\core\indexes\multi.py", line 2825, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 832, in pandas._libs.index.BaseMultiIndexCodesEngine.get_loc
  File "pandas\_libs\index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2152, in pandas._libs.hashtable.UInt64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2176, in pandas._libs.hashtable.UInt64HashTable.get_item
KeyError: 10
```

## Versions

* Spyder version: 5.4.5  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.22621-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                                                        :  1.4.1 (OK)
chardet >=2.0.0                                                             :  5.2.0 (OK)
cloudpickle >=0.5.0                                                         :  2.2.1 (OK)
cookiecutter >=1.6.0                                                        :  2.3.0 (OK)
diff_match_patch >=20181111                                                 :  20230430 (OK)
intervaltree                                                                :  None (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0,!=8.11.0,!=8.12.0,!=8.12.1 :  8.12.2 (OK)
jedi >=0.17.2,<0.19.0                                                       :  0.18.2 (OK)
jellyfish >=0.7                                                             :  1.0.0 (OK)
jsonschema >=3.2.0                                                          :  4.19.0 (OK)
keyring >=17.0.0                                                            :  24.2.0 (OK)
nbconvert >=4.0                                                             :  7.8.0 (OK)
numpydoc >=0.6.0                                                            :  1.5.0 (OK)
paramiko >=2.4.0                                                            :  3.3.1 (OK)
parso >=0.7.0,<0.9.0                                                        :  0.8.3 (OK)
pexpect >=4.4.0                                                             :  4.8.0 (OK)
pickleshare >=0.4                                                           :  0.7.5 (OK)
psutil >=5.3                                                                :  5.9.5 (OK)
pygments >=2.0                                                              :  2.16.1 (OK)
pylint >=2.5.0,<3.0                                                         :  2.17.5 (OK)
pylint_venv >=3.0.2                                                         :  3.0.2 (OK)
pyls_spyder >=0.4.0                                                         :  0.4.0 (OK)
pylsp >=1.7.4,<1.8.0                                                        :  1.7.4 (OK)
pylsp_black >=1.2.0,<3.0.0                                                  :  1.3.0 (OK)
qdarkstyle >=3.0.2,<3.2.0                                                   :  3.1 (OK)
qstylizer >=0.2.2                                                           :  0.2.2 (OK)
qtawesome >=1.2.1                                                           :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                                                    :  5.4.3 (OK)
qtpy >=2.1.0                                                                :  2.4.0 (OK)
rtree >=0.9.7                                                               :  1.0.1 (OK)
setuptools >=49.6.0                                                         :  68.1.2 (OK)
sphinx >=0.6.6                                                              :  7.1.2 (OK)
spyder_kernels >=2.4.4,<2.5.0                                               :  2.4.4 (OK)
textdistance >=4.2.0                                                        :  4.5.0 (OK)
three_merge >=0.1.1                                                         :  0.1.1 (OK)
watchdog                                                                    :  3.0.0 (OK)
zmq >=22.1.0                                                                :  25.1.1 (OK)

# Optional:
cython >=0.21                                                               :  3.0.2 (OK)
matplotlib >=3.0.0                                                          :  3.7.2 (OK)
numpy >=1.7                                                                 :  1.24.4 (OK)
pandas >=1.1.1                                                              :  2.0.3 (OK)
scipy >=0.17.0                                                              :  1.10.1 (OK)
sympy >=0.7.3                                                               :  1.12 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2                                        :  1.2.2 (OK)
```

**Comment by dalthviz** [comment]
Hi @SharowarKhan thank you for the feedback and sorry for the late response! Could you provide a code example to reproduce this locally? Also, doing a quick check, seems like this could be related with the data from where the dataframe is being created. For more info on that you can check this SO: https://stackoverflow.com/a/43736331/15954282

Any other info in order to reproduce this is greatly appreciated. Let us know if the link above helps!
