### ISSUE TITLE
ImportError: libpci.so.3

### ISSUE THREAD

**Issue by schaefersa** [spyder-ide/spyder#21449]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder in Anaconda wont launch.

### What steps reproduce the problem?

1. Install Anaconda
2. try to open spyder
3. 

### What is the expected output? What do you see instead?
Spyder should now open, but instead there is an error.

### Paste Traceback/Error Below (if applicable)

~$ spyder
Traceback (most recent call last):
  File "/home/samuelschaefer/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/samuelschaefer/anaconda3/lib/python3.11/site-packages/spyder/app/start.py", line 252, in main
    from spyder.app import mainwindow
  File "/home/samuelschaefer/anaconda3/lib/python3.11/site-packages/spyder/app/mainwindow.py", line 57, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samuelschaefer/anaconda3/lib/python3.11/site-packages/qtpy/QtWebEngineWidgets.py", line 29, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: libpci.so.3: cannot open shared object file: No such file or directory

## Versions

* Spyder version: 5.4.3           py311h06a4308_1
* Python version: 3.11.5               h955ad1f_0
* Qt version: 5.15.2               h7358343_9
* PyQt version: 5.15.7          py311h6a678d5_0
* Operating System name/version:  Debian GNU/Linux 11 (bullseye)

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @schaefersa, thanks for reporting. To fix this error, please open a terminal and run there

    sudo apt install libpci

Then try to start Spyder again.

Let us know if it works for you.

**Comment by uninem** [comment]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libpci
