### ISSUE TITLE
Just want to install tensorflow..

### ISSUE THREAD

**Issue by ArsenyKornilcev** [spyder-ide/spyder#21464]
### What steps will reproduce the problem?

I just wanted to install tensorflow. According to your FAQ, I downloaded Manaconda, then did everything according to your video instructions https://www.youtube.com/watch?v=i7Njb3xO4Fw&t=29s . When restarting the kernel, I got an error that in the directory where the new one is located python.exe (in Miniconda), there is no kernel file of the required version or something like that. At your prompt in the console, in Anaconda Prompt(Miniconda3) I executed the command: conda install spyder-kernels=2.4. After that, I clicked "restart kernel" again and got this error (in the logs)

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\sieni\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\client.py", line 772, in _restart_thread_main
    self.shellwidget.kernel_manager.restart_kernel(
  File "C:\Users\sieni\AppData\Local\Programs\Spyder\pkgs\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "C:\Users\sieni\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 555, in _async_restart_kernel
    await self._async_shutdown_kernel(now=now, restart=True)
  File "C:\Users\sieni\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 94, in wrapper
    raise e
  File "C:\Users\sieni\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 85, in wrapper
    out = await method(self, *args, **kwargs)
  File "C:\Users\sieni\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 513, in _async_shutdown_kernel
    await self._async_request_shutdown(restart=restart)
  File "C:\Users\sieni\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 415, in _async_request_shutdown
    self._connect_control_socket()
  File "C:\Users\sieni\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 333, in _connect_control_socket
    self._control_socket = self._create_connected_socket("control")
  File "C:\Users\sieni\AppData\Local\Programs\Spyder\pkgs\jupyter_client\connect.py", line 647, in _create_connected_socket
    sock = self.context.socket(socket_type)
  File "C:\Users\sieni\AppData\Local\Programs\Spyder\pkgs\zmq\sugar\context.py", line 359, in socket
    raise ZMQError(Errno.ENOTSUP)
zmq.error.ZMQError: Not supported
```

## Versions

* Spyder version: 5.4.5  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                                                        :  1.4.1 (OK)
chardet >=2.0.0                                                             :  5.2.0 (OK)
cloudpickle >=0.5.0                                                         :  2.2.1 (OK)
cookiecutter >=1.6.0                                                        :  2.3.0 (OK)
diff_match_patch >=20181111                                                 :  20230430 (OK)
intervaltree                                                                :  None (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0,!=8.11.0,!=8.12.0,!=8.12.1 :  8.12.2 (OK)
jedi >=0.17.2,<0.19.0                                                       :  0.18.2 (OK)
jellyfish >=0.7                                                             :  1.0.0 (OK)
jsonschema >=3.2.0                                                          :  4.19.0 (OK)
keyring >=17.0.0                                                            :  24.2.0 (OK)
nbconvert >=4.0                                                             :  7.8.0 (OK)
numpydoc >=0.6.0                                                            :  1.5.0 (OK)
paramiko >=2.4.0                                                            :  3.3.1 (OK)
parso >=0.7.0,<0.9.0                                                        :  0.8.3 (OK)
pexpect >=4.4.0                                                             :  4.8.0 (OK)
pickleshare >=0.4                                                           :  0.7.5 (OK)
psutil >=5.3                                                                :  5.9.5 (OK)
pygments >=2.0                                                              :  2.16.1 (OK)
pylint >=2.5.0,<3.0                                                         :  2.17.5 (OK)
pylint_venv >=3.0.2                                                         :  3.0.2 (OK)
pyls_spyder >=0.4.0                                                         :  0.4.0 (OK)
pylsp >=1.7.4,<1.8.0                                                        :  1.7.4 (OK)
pylsp_black >=1.2.0,<3.0.0                                                  :  1.3.0 (OK)
qdarkstyle >=3.0.2,<3.2.0                                                   :  3.1 (OK)
qstylizer >=0.2.2                                                           :  0.2.2 (OK)
qtawesome >=1.2.1                                                           :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                                                    :  5.4.3 (OK)
qtpy >=2.1.0                                                                :  2.4.0 (OK)
rtree >=0.9.7                                                               :  1.0.1 (OK)
setuptools >=49.6.0                                                         :  68.1.2 (OK)
sphinx >=0.6.6                                                              :  7.1.2 (OK)
spyder_kernels >=2.4.4,<2.5.0                                               :  2.4.4 (OK)
textdistance >=4.2.0                                                        :  4.5.0 (OK)
three_merge >=0.1.1                                                         :  0.1.1 (OK)
watchdog                                                                    :  3.0.0 (OK)
zmq >=22.1.0                                                                :  25.1.1 (OK)

# Optional:
cython >=0.21                                                               :  3.0.2 (OK)
matplotlib >=3.0.0                                                          :  3.7.2 (OK)
numpy >=1.7                                                                 :  1.24.4 (OK)
pandas >=1.1.1                                                              :  2.0.3 (OK)
scipy >=0.17.0                                                              :  1.10.1 (OK)
sympy >=0.7.3                                                               :  1.12 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2                                        :  1.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @ArsenyKornilcev, thanks for reporting. What happens if you close Spyder and start it again? Does this problem still appears after that?

**Comment by ArsenyKornilcev** [comment]
Yes, it works! But after that I had to install a bunch of tensorflow
dependencies and gave up on it.

пт, 27 окт. 2023 г. в 20:45, Carlos Cordoba ***@***.***>:

**Comment by GitKia1392** [comment]
Same thing happend with me. Solution is to first run it as admin
2nd solution is to update or repair python
OR go into: **Windows Security -> Protection History -> Click on any one of the options -> Controlled Folder Access Settings ->
under controlled folder access click Protected Folders -> If the drive you install python is there click on it and click remove.
LAST solution is to redo the steps but at controlled folder access click Protected Folders -> If the drive you install python is there click on it and click remove.
LAST solution is to redo the steps but at controlled folder access click allow an app through controlled folder access -> add python.**

Thanks a lot

**Comment by ccordoba12** [comment]
> Yes, it works!

Great! Thanks for letting us know about it.

> But after that I had to install a bunch of tensorflow dependencies and gave up on it.

Sorry to hear that. We're working to make that process simpler for users.

For now I'm going to close this issue but let us know if we can help you in another way.
