### ISSUE TITLE
[5.5.0] `AttributeError: type object 'DarkPalette' has no attribute 'COLOR_DISABLED'`

### ISSUE THREAD

**Issue by Ancieg** [spyder-ide/spyder#21507]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

In ALTLinux Sisyphus the IDE fails to launch if run without any configuration.

### What steps reproduce the problem?

1. `# apt-get install spyder`
2. `$ spyder --reset`
3. `$ spyder`

### What is the expected output? What do you see instead?

I expect IDE launching, but it crashes instead.

### Paste Traceback/Error Below (if applicable)

```python-traceback

fromIccProfile: failed minimal tag size sanity
Traceback (most recent call last):
  File "/usr/bin/spyder", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib64/python3/site-packages/spyder/app/start.py", line 256, in main
    mainwindow.main(options, args)
  File "/usr/lib64/python3/site-packages/spyder/app/mainwindow.py", line 1847, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3/site-packages/spyder/app/utils.py", line 289, in create_window
    main.setup()
  File "/usr/lib64/python3/site-packages/spyder/app/mainwindow.py", line 752, in setup
    internal_plugins = find_internal_plugins()
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3/site-packages/spyder/app/find_plugins.py", line 40, in find_internal_plugins
    mod = importlib.import_module(entry_point.module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib64/python3/site-packages/spyder/plugins/pylint/plugin.py", line 22, in <module>
    from spyder.plugins.pylint.confpage import PylintConfigPage
  File "/usr/lib64/python3/site-packages/spyder/plugins/pylint/confpage.py", line 16, in <module>
    from spyder.plugins.pylint.main_widget import (MAX_HISTORY_ENTRIES,
  File "/usr/lib64/python3/site-packages/spyder/plugins/pylint/main_widget.py", line 90, in <module>
    class CategoryItem(QTreeWidgetItem):
  File "/usr/lib64/python3/site-packages/spyder/plugins/pylint/main_widget.py", line 102, in CategoryItem
    'icon': ima.icon("convention")
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3/site-packages/spyder/utils/icon_manager.py", line 439, in icon
    kwargs['color_disabled'] = QStylePalette.COLOR_DISABLED
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'DarkPalette' has no attribute 'COLOR_DISABLED'

```

## Versions

* Spyder version: 5.5.0 (from tag `v5.5.0`)
* Python version: 3.11.6 (package `python3-3.11.6-alt1.x86_64`)
* Qt version: 5.15.10 (package `qt5-base-common-5.15.10-alt2.x86_64`)
* PyQt version: 5.15.7 (package `python3-module-PyQt5-5.15.7-alt1.1.x86_64`)
* Operating System name/version: ALT Workstation K 10.2 (updated to Sisyphus 09.11.2023)

### Dependencies

No access to `Help` > `Dependencies` (IDE doesn't launch).

**Comment by ccordoba12** [comment]
Hey @Ancieg, thanks for reporting. Please ask your distro maintainers to update the QDarkstyle package, which is the cause of this error.

The new QDarkstyle version Spyder 5.5.0 depends on (3.2.0) comes with the constant `COLOR_DISABLED`, which appears in the error you referenced above:

    AttributeError: type object 'DarkPalette' has no attribute 'COLOR_DISABLED'

That constant is not available in previous versions of the package.
