### ISSUE TITLE
`RuntimeError: wrapped C/C++ object of type FrameWebView has been deleted` while doing basic operations (edit file, minimize/un-minimize Spyder window)

### ISSUE THREAD

**Issue by SubjectivelyCoolGuy** [spyder-ide/spyder#21509]
### What steps will reproduce the problem?

1. Open Spyder
2. Write some code
3. Minimize Spyder
4. Un-minimize Spyder

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1176, in refresh_container
    self.infowidget.hide()
RuntimeError: wrapped C/C++ object of type FrameWebView has been deleted
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1176, in refresh_container
    self.infowidget.hide()
RuntimeError: wrapped C/C++ object of type FrameWebView has been deleted
```

## Versions

* Spyder version: 5.5.0  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.22621-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.2.0 (OK)
cloudpickle >=0.5.0           :  3.0.0 (OK)
cookiecutter >=1.6.0          :  2.4.0 (OK)
diff_match_patch >=20181111   :  20230430 (OK)
intervaltree                  :  None (OK)
IPython >=8.12.2,<8.13.0      :  8.12.3 (OK)
jedi >=0.17.2,<0.20.0         :  0.19.1 (OK)
jellyfish >=0.7               :  1.0.1 (OK)
jsonschema >=3.2.0            :  4.19.2 (OK)
keyring >=17.0.0              :  24.2.0 (OK)
nbconvert >=4.0               :  7.11.0 (OK)
numpydoc >=0.6.0              :  1.6.0 (OK)
paramiko >=2.4.0              :  3.3.1 (OK)
parso >=0.7.0,<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.6 (OK)
pygments >=2.0                :  2.16.1 (OK)
pylint >=2.5.0,<3.1           :  3.0.2 (OK)
pylint_venv >=3.0.2           :  3.0.3 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.9.0,<1.10.0         :  1.9.0 (OK)
pylsp_black >=1.2.0,<3.0.0    :  1.3.0 (OK)
qdarkstyle >=3.2.0,<3.3.0     :  3.2 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.3 (OK)
qtconsole >=5.5.0,<5.6.0      :  5.5.0 (OK)
qtpy >=2.1.0                  :  2.4.1 (OK)
rtree >=0.9.7                 :  1.1.0 (OK)
setuptools >=49.6.0           :  68.2.2 (OK)
sphinx >=0.6.6                :  7.1.2 (OK)
spyder_kernels >=2.5.0,<2.6.0 :  2.5.0 (OK)
textdistance >=4.2.0          :  4.6.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  3.0.0 (OK)
zmq >=22.1.0                  :  25.1.1 (OK)

# Optional:
cython >=0.21                 :  3.0.5 (OK)
matplotlib >=3.0.0            :  3.7.3 (OK)
numpy >=1.7                   :  1.24.4 (OK)
pandas >=1.1.1                :  2.0.3 (OK)
scipy >=0.17.0                :  1.10.1 (OK)
sympy >=0.7.3                 :  1.12 (OK)
```

**Comment by dalthviz** [comment]
Hi @SubjectivelyCoolGuy thank you for the feedback! I tried to reproduce this error but I was unable to 🤔 Maybe there are some other steps that could be needed to reproduce this? In case you are able to reproduce this reliably, could you submit here a GIF or video showing the steps you are following to trigger the error please?

Any other info in order to reproduce this is greatly apprecited, let us know!

**Comment by ccordoba12** [comment]
@dalthviz, perhaps we should catch and pass on that error because it doesn't seem to break other things.

What do you think?

**Comment by dalthviz** [comment]
I guess we could do that (I think in the past that's has been the approach to handle such `RuntimeErrors`) :+1: Still, it could be nice to actually understand what could be causing this
