### ISSUE TITLE
Spyder opening error

### ISSUE THREAD

**Issue by GitKia1392** [spyder-ide/spyder#21521]
Traceback (most recent call last):
File "K:\anaconda\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
^^^^^^
File "K:\anaconda\Lib\site-packages\spyder\app\start.py", line 256, in main
mainwindow.main(options, args)
File "K:\anaconda\Lib\site-packages\spyder\app\mainwindow.py", line 1823, in main
mainwindow = create_window(MainWindow, app, splash, options, args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\anaconda\Lib\site-packages\spyder\app\utils.py", line 289, in create_window
main.setup()
File "K:\anaconda\Lib\site-packages\spyder\app\mainwindow.py", line 732, in setup
internal_plugins = find_internal_plugins()
^^^^^^^^^^^^^^^^^^^^^^^
File "K:\anaconda\Lib\site-packages\spyder\app\find_plugins.py", line 40, in find_internal_plugins
mod = importlib.import_module(entry_point.module_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\anaconda\Lib\importlib\__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "", line 1204, in _gcd_import
File "", line 1176, in _find_and_load
File "", line 1147, in _find_and_load_unlocked
File "", line 690, in _load_unlocked
File "", line 940, in exec_module
File "", line 241, in _call_with_frames_removed
File "K:\anaconda\Lib\site-packages\spyder\plugins\application\plugin.py", line 30, in 
from spyder.plugins.application.container import (
File "K:\anaconda\Lib\site-packages\spyder\plugins\application\container.py", line 34, in 
from spyder.plugins.console.api import ConsoleActions
File "K:\anaconda\Lib\site-packages\spyder\plugins\console\api.py", line 12, in 
from spyder.plugins.console.widgets.main_widget import (
File "K:\anaconda\Lib\site-packages\spyder\plugins\console\widgets\main_widget.py", line 35, in 
from spyder.plugins.console.widgets.internalshell import InternalShell
File "K:\anaconda\Lib\site-packages\spyder\plugins\console\widgets\internalshell.py", line 31, in 
from spyder.plugins.console.utils.interpreter import Interpreter
File "K:\anaconda\Lib\site-packages\spyder\plugins\console\utils\interpreter.py", line 17, in 
from code import InteractiveConsole
ImportError: cannot import name 'InteractiveConsole' from 'code' (K:\code.py)

**Comment by ccordoba12** [comment]
Hey @GitKia1392, thanks for reporting. To fix this problem, please remove, rename or move to another directory this file:

    K:\code.py

Let us know if that solves this issue for you.

**Comment by GitKia1392** [comment]
Hey @ccordoba12 thanks for responding. Same error.
