### ISSUE TITLE
Spyder Kernel error

### ISSUE THREAD

**Issue by vhiwase** [spyder-ide/spyder#21523]
### What steps will reproduce the problem?

I am getting following error in mac while changing spyder env:

An error ocurred while starting the kernel
Traceback (most recent call last):
File "/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/spyder_kernels/console/__main__.py", line 24, in
start.main()
File "/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/spyder_kernels/console/start.py", line 294, in main
from ipykernel.kernelapp import IPKernelApp
File "/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/ipykernel/kernelapp.py", line 52, in
from .ipkernel import IPythonKernel
File "/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/ipykernel/ipkernel.py", line 20, in
from .comm.comm import BaseComm
File "/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/ipykernel/comm/__init__.py", line 3, in
from .comm import Comm
File "/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/ipykernel/comm/comm.py", line 15, in
from ipykernel.kernelbase import Kernel
File "/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/ipykernel/kernelbase.py", line 38, in
import psutil
File "/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/psutil/__init__.py", line 123, in
from . import _psosx as _psplatform
File "/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/psutil/_psosx.py", line 13, in
from . import _psposix
File "/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/psutil/_psposix.py", line 28, in
from . import _psutil_osx
ImportError: dlopen(/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/psutil/_psutil_osx.abi3.so, 0x0002): tried: '/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/psutil/_psutil_osx.abi3.so' (mach‑o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/psutil/_psutil_osx.abi3.so' (no such file), '/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/psutil/_psutil_osx.abi3.so' (mach‑o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
Traceback (most recent call last):
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/spyder_kernels/console/__main__.py", line 24, in
start.main()
File "/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/spyder_kernels/console/start.py", line 294, in main
from ipykernel.kernelapp import IPKernelApp
File "/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/ipykernel/kernelapp.py", line 52, in
from .ipkernel import IPythonKernel
File "/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/ipykernel/ipkernel.py", line 20, in
from .comm.comm import BaseComm
File "/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/ipykernel/comm/__init__.py", line 3, in
from .comm import Comm
File "/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/ipykernel/comm/comm.py", line 15, in
from ipykernel.kernelbase import Kernel
File "/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/ipykernel/kernelbase.py", line 38, in
import psutil
File "/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/psutil/__init__.py", line 123, in
from . import _psosx as _psplatform
File "/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/psutil/_psosx.py", line 13, in
from . import _psposix
File "/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/psutil/_psposix.py", line 28, in
from . import _psutil_osx
ImportError: dlopen(/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/psutil/_psutil_osx.abi3.so, 0x0002): tried: '/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/psutil/_psutil_osx.abi3.so' (mach‑o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/psutil/_psutil_osx.abi3.so' (no such file), '/Users/vaibhav/Desktop/Github/document_processing/venv/lib/python3.9/site‑packages/psutil/_psutil_osx.abi3.so' (mach‑o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/jupyter_client/manager.py", line 91, in wrapper
    self._ready.set_result(None)
asyncio.exceptions.InvalidStateError: invalid state

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qtconsole/manager.pyc", line 27, in poll
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/jupyter_client/restarter.py", line 143, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "jupyter_core/utils/__init__.pyc", line 173, in wrapped
  File "asyncio/base_events.pyc", line 647, in run_until_complete
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/jupyter_client/manager.py", line 596, in _async_restart_kernel
    await self._async_start_kernel(**self._launch_args)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/jupyter_client/manager.py", line 94, in wrapper
    self._ready.set_exception(e)
asyncio.exceptions.InvalidStateError: invalid state
```

## Versions

* Spyder version: 5.5.0 b4c4e1a16 (standalone)
* Python version: 3.9.14 64-bit
* Qt version: 5.15.11
* PyQt5 version: 5.15.10
* Operating System: macOS-13.4-x86_64-i386-64bit

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.4.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.17.2 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.1 (OK)
jsonschema >=3.2.0               :  4.19.2 (OK)
keyring >=17.0.0                 :  24.2.0 (OK)
nbconvert >=4.0                  :  7.11.0 (OK)
numpydoc >=0.6.0                 :  1.6.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.6 (OK)
pygments >=2.0                   :  2.16.1 (OK)
pylint >=2.5.0,<3.1              :  3.0.2 (OK)
pylint_venv >=3.0.2              :  None (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.9.0,<1.10.0            :  1.9.0 (OK)
pylsp_black >=1.2.0,<3.0.0       :  1.3.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.2.3 (OK)
qtconsole >=5.5.0,<5.6.0         :  5.5.0 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.1.0 (OK)
setuptools >=49.6.0              :  68.2.2 (OK)
sphinx >=0.6.6                   :  5.1.1 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.0 (OK)
textdistance >=4.2.0             :  4.6.0 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  3.0.0 (OK)
zmq >=22.1.0                     :  25.1.1 (OK)

# Optional:
cython >=0.21                    :  3.0.5 (OK)
matplotlib >=3.0.0               :  3.8.1 (OK)
numpy >=1.7                      :  1.26.1 (OK)
pandas >=1.1.1                   :  2.1.2 (OK)
scipy >=0.17.0                   :  1.11.3 (OK)
sympy >=0.7.3                    :  1.12 (OK)
```

**Comment by vhiwase** [comment]
Issue was already solved in : 

[m1-mac-spyder-issue](https://stackoverflow.com/questions/72619143/unable-to-import-psutil-on-m1-mac-with-miniforge-mach-o-file-but-is-an-incomp)

Go to your virtual environment which you are using in spyder > Preferences > Python Interpreter > Use the following Python interpreter > (virtual env python3.x path> and run the following commands:

`pip uninstall psutil`

followed by:

`pip install --no-binary :all: psutil`

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
