### ISSUE TITLE
Spyder 5.5.0 not launching

### ISSUE THREAD

**Issue by saswatrkp** [spyder-ide/spyder#21526]
## Problem Description
spyder not opening after being installed through pip .  completed all the usual troubleshooting mentioned on the website, but nothing works.

### What steps reproduce the problem?

1. Just typing in 'spyder' in the terminal

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "/usr/local/bin/spyder", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/spyder/app/start.py", line 252, in main
    from spyder.app import mainwindow
  File "/usr/local/lib/python3.8/dist-packages/spyder/app/mainwindow.py", line 69, in <module>
    from spyder.app.find_plugins import (
  File "/usr/local/lib/python3.8/dist-packages/spyder/app/find_plugins.py", line 17, in <module>
    from spyder.api.plugins import Plugins
  File "/usr/local/lib/python3.8/dist-packages/spyder/api/plugins/__init__.py", line 25, in <module>
    from .old_api import SpyderPlugin, SpyderPluginWidget  # noqa
  File "/usr/local/lib/python3.8/dist-packages/spyder/api/plugins/old_api.py", line 21, in <module>
    from spyder.plugins.base import BasePluginMixin, BasePluginWidgetMixin
  File "/usr/local/lib/python3.8/dist-packages/spyder/plugins/base.py", line 33, in <module>
    from spyder.utils.stylesheet import APP_STYLESHEET
  File "/usr/local/lib/python3.8/dist-packages/spyder/utils/stylesheet.py", line 197, in <module>
    APP_STYLESHEET = AppStylesheet()
  File "/usr/local/lib/python3.8/dist-packages/spyder/utils/stylesheet.py", line 76, in __init__
    super().__init__()
  File "/usr/local/lib/python3.8/dist-packages/spyder/utils/stylesheet.py", line 36, in __init__
    self.set_stylesheet()
  File "/usr/local/lib/python3.8/dist-packages/spyder/utils/stylesheet.py", line 90, in set_stylesheet
    stylesheet = qdarkstyle.load_stylesheet(palette=QStylePalette)
  File "/home/user/.local/lib/python3.8/site-packages/qdarkstyle/__init__.py", line 368, in load_stylesheet
    stylesheet = _load_stylesheet(palette=palette_arg)
  File "/home/user/.local/lib/python3.8/site-packages/qdarkstyle/__init__.py", line 273, in _load_stylesheet
    raise FileNotFoundError("Unable to find QSS file '{}' "
FileNotFoundError: Unable to find QSS file ':qdarkstyle/dark/darkstyle.qss' in resources.


```

## Versions

* Spyder version: 5.5.0
* Python version: 3.8.10
* Qt version: 
* PyQt version: 
* Operating System name/version:  Ubuntu

**Comment by dalthviz** [comment]
Hi @saswatrkp thank you for the feedback! Seems like you installed Spyder directly running `pip install spyder`? I think in that way you can get quite a good number of issues. Could it be possible for you to create a Python virtual environment and then install there Spyder? You also probably will need to delete the `/home/user/.local/lib/python3.8/` dir to prevent further errors. For more info about the steps we recommend following to install Spyder using pip you can check https://docs.spyder-ide.org/current/installation.html#using-pip

Let us know if the info above helps!

**Comment by saswatrkp** [comment]
Hi @dalthviz ! Thank you for your reply. Indeed there is no issue when I make a virtual env and install spyder there. However, I wanted to know what exactly was the issue with directly installing spyder through pip. what I could gather from the traceback is that spyder is not able to a find a .qss stylesheet. but I could manually locate the same file in the directory. Could you please give a brief feedback regarding what exactly was going wrong? I am very new to this, so I might be totally wrong here.

**Comment by dalthviz** [comment]
Oh I see, thank you for letting us know! And I think the main issue comes from mixing a global vs a local pip installation. If you carefully look the traceback you can see that Spyder code is being retrieved from `/usr/local/lib/python3.8/` (global install) while the QDarkStyle code comes from `/home/user/.local/lib/python3.8/` (user local install). I'm not completly sure how that affects path resolution for packages assets but seems like in this case that mix causes the QDarkStyle error related with not being able to find a `.qss` file to load. Here a post I found regarding global vs local pip installations https://askubuntu.com/a/1087684 

Let us know if the info above clarifies a little bit more how things work!

**Comment by saswatrkp** [comment]
Thank you for the clarification and the link to the post. I will try to do some further reading on this.

**Comment by dalthviz** [comment]
Awesome! Since seems like there is not much we can do from the Spyder side and this at the end is not directly related with Spyder itself I'm closing it. However, if you face any other issue with Spyder in the future let us know!
