### ISSUE TITLE
Tab autocomplete not working in the IPython console

### ISSUE THREAD

**Issue by sharon92** [spyder-ide/spyder#21533]
### What steps will reproduce the problem?

import a module, type dot, hit tab -> Issue Reporter pops up

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\S.Shaji\AppData\Local\Programs\Spyder\pkgs\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\S.Shaji\AppData\Local\Programs\Spyder\pkgs\qtconsole\jupyter_widget.py", line 176, in _handle_complete_reply
    self._complete_with_items(cursor, matches)
  File "C:\Users\S.Shaji\AppData\Local\Programs\Spyder\pkgs\qtconsole\console_widget.py", line 1090, in _complete_with_items
    self._completion_widget.show_items(cursor, items,
  File "C:\Users\S.Shaji\AppData\Local\Programs\Spyder\pkgs\qtconsole\completion_html.py", line 315, in show_items
    items_m, ci = compute_item_matrix(items, empty=" ", displaywidth=displaywidth)
TypeError: compute_item_matrix() got an unexpected keyword argument 'displaywidth'
```

## Versions

* Spyder version: 5.5.0  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.22631-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.2.0 (OK)
cloudpickle >=0.5.0           :  3.0.0 (OK)
cookiecutter >=1.6.0          :  2.4.0 (OK)
diff_match_patch >=20181111   :  20230430 (OK)
intervaltree                  :  None (OK)
IPython >=8.12.2,<8.13.0      :  8.12.3 (OK)
jedi >=0.17.2,<0.20.0         :  0.19.1 (OK)
jellyfish >=0.7               :  1.0.1 (OK)
jsonschema >=3.2.0            :  4.19.2 (OK)
keyring >=17.0.0              :  24.2.0 (OK)
nbconvert >=4.0               :  7.11.0 (OK)
numpydoc >=0.6.0              :  1.6.0 (OK)
paramiko >=2.4.0              :  3.3.1 (OK)
parso >=0.7.0,<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.6 (OK)
pygments >=2.0                :  2.16.1 (OK)
pylint >=2.5.0,<3.1           :  3.0.2 (OK)
pylint_venv >=3.0.2           :  3.0.3 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.9.0,<1.10.0         :  1.9.0 (OK)
pylsp_black >=1.2.0,<3.0.0    :  1.3.0 (OK)
qdarkstyle >=3.2.0,<3.3.0     :  3.2 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.3 (OK)
qtconsole >=5.5.0,<5.6.0      :  5.5.0 (OK)
qtpy >=2.1.0                  :  2.4.1 (OK)
rtree >=0.9.7                 :  1.1.0 (OK)
setuptools >=49.6.0           :  68.2.2 (OK)
sphinx >=0.6.6                :  7.1.2 (OK)
spyder_kernels >=2.5.0,<2.6.0 :  2.5.0 (OK)
textdistance >=4.2.0          :  4.6.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  3.0.0 (OK)
zmq >=22.1.0                  :  25.1.1 (OK)

# Optional:
cython >=0.21                 :  3.0.5 (OK)
matplotlib >=3.0.0            :  3.7.3 (OK)
numpy >=1.7                   :  1.24.4 (OK)
pandas >=1.1.1                :  2.0.3 (OK)
scipy >=0.17.0                :  1.10.1 (OK)
sympy >=0.7.3                 :  1.12 (OK)
```

### Environment

<details><summary>Environment</summary>

```
Package                       Version
----------------------------- ------------
affine                        2.4.0
alabaster                     0.7.13
altgraph                      0.17.3
arrow                         1.3.0
astroid                       3.0.1
asttokens                     2.4.1
attrs                         23.1.0
autopep8                      2.0.4
Babel                         2.13.1
backcall                      0.2.0
beautifulsoup4                4.12.2
binaryornot                   0.4.4
black                         23.10.1
bleach                        6.1.0
certifi                       2023.7.22
cffi                          1.16.0
chardet                       5.2.0
charset-normalizer            3.3.2
click                         8.1.7
click-plugins                 1.1.1
cligj                         0.7.2
cloudpickle                   3.0.0
colorama                      0.4.6
comm                          0.2.0
contourpy                     1.1.1
cookiecutter                  2.4.0
cryptography                  41.0.5
cycler                        0.12.1
Cython                        3.0.5
debugpy                       1.8.0
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20230430
dill                          0.3.7
docstring-to-markdown         0.13
docutils                      0.20.1
entrypoints                   0.4
et-xmlfile                    1.1.0
executing                     2.0.1
fastjsonschema                2.18.1
Fiona                         1.9.4.post1
flake8                        6.1.0
fonttools                     4.44.0
freetype-py                   2.4.0
future                        0.18.3
GDAL                          3.7.1
geopandas                     0.14.0
h5py                          3.9.0
idna                          3.4
imageio                       2.31.0
imagesize                     1.4.1
importlib-metadata            6.8.0
importlib-resources           6.1.1
inflection                    0.5.1
ipykernel                     6.26.0
ipython                       8.12.3
isort                         5.12.0
jaraco.classes                3.3.0
jedi                          0.19.1
jellyfish                     1.0.1
Jinja2                        3.1.2
jsonschema                    4.19.2
jsonschema-specifications     2023.7.1
jupyter_client                8.6.0
jupyter_core                  5.5.0
jupyterlab-pygments           0.2.2
keyring                       24.2.0
kiwisolver                    1.4.5
lazy-object-proxy             1.9.0
markdown-it-py                3.0.0
MarkupSafe                    2.1.3
matplotlib                    3.7.3
matplotlib-inline             0.1.6
mccabe                        0.7.0
mdurl                         0.1.2
MeshParser                    0.7.0
mf-visuals                    0.0.7
mistune                       3.0.2
more-itertools                10.1.0
mpmath                        1.3.0
munch                         2.5.0
mypy                          1.4.1
mypy-extensions               1.0.0
nbclient                      0.9.0
nbconvert                     7.11.0
nbformat                      5.9.2
nest-asyncio                  1.5.8
numpy                         1.24.4
numpydoc                      1.6.0
opencv-python                 4.7.0.72
openpyxl                      3.1.2
packaging                     23.2
pandas                        2.0.3
pandocfilters                 1.5.0
paramiko                      3.3.1
parso                         0.8.3
pathspec                      0.11.2
pefile                        2023.2.7
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        10.1.0
pip                           23.3.1
pkgutil_resolve_name          1.3.10
platformdirs                  3.11.0
pluggy                        1.3.0
prompt-toolkit                3.0.39
psutil                        5.9.6
ptyprocess                    0.7.0
pure-eval                     0.2.2
pyarrow                       14.0.1
pycodestyle                   2.11.1
pycparser                     2.21
pydocstyle                    6.3.0
pyflakes                      3.1.0
pygfx                         0.1.13
Pygments                      2.16.1
pyinstaller                   5.13.2
pyinstaller-hooks-contrib     2023.0
pylinalg                      0.4.1
pylint                        3.0.2
pylint-venv                   3.0.3
pyls-spyder                   0.4.0
pylsp-mypy                    0.6.7
pyodbc                        5.0.1
pyogrio                       0.6.0
pyparsing                     3.1.1
pyproj                        3.4.1
PyQt5                         5.15.10
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.13.0
PyQt6                         6.5.2
PyQt6-Qt6                     6.5.0
PyQt6-sip                     13.4.1
pyqtgraph                     0.13.3
PyQtWebEngine                 5.15.6
PyQtWebEngine-Qt5             5.15.2
pyshp                         2.3.1
python-dateutil               2.8.2
python-lsp-black              1.3.0
python-lsp-jsonrpc            1.1.2
python-lsp-server             1.9.0
pytoolconfig                  1.2.6
pytz                          2023.3.post1
pywin32                       306
pywin32-ctypes                0.2.2
pyxdg                         0.28
PyYAML                        6.0.1
pyzmq                         25.1.1
QDarkStyle                    3.2
qstylizer                     0.2.2
QtAwesome                     1.2.3
qtconsole                     5.5.0
QtPy                          2.4.1
rasterio                      1.3.9
referencing                   0.30.2
requests                      2.31.0
rich                          13.6.0
rope                          1.11.0
rpds-py                       0.12.0
scipy                         1.10.1
setuptools                    68.2.2
shapely                       2.0.2
six                           1.16.0
snowballstemmer               2.2.0
snuggs                        1.4.7
sortedcontainers              2.4.0
soupsieve                     2.5
Sphinx                        7.1.2
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.5.0
spyder-kernels                2.5.0
stack-data                    0.6.3
superqt                       0.4.1
sympy                         1.12
tabulate                      0.9.0
text-unidecode                1.3
textdistance                  4.6.0
three-merge                   0.1.1
tinycss2                      1.2.1
tomli                         2.0.1
tomlkit                       0.12.2
tornado                       6.3.3
tqdm                          4.66.1
traitlets                     5.13.0
types-python-dateutil         2.8.19.14
typing_extensions             4.8.0
tzdata                        2023.3
uharfbuzz                     0.37.0
ujson                         5.8.0
urllib3                       2.0.7
watchdog                      3.0.0
wcwidth                       0.2.9
webencodings                  0.5.1
wgpu                          0.9.4
whatthepatch                  1.0.5
wheel                         0.41.3
wrapt                         1.15.0
XlsxWriter                    3.0.8
yapf                          0.40.2
zipp                          3.17.0

```
</details>

**Comment by sharon92** [comment]
there is a typo here:

Spyder\pkgs\qtconsole\util.py

`def compute_item_matrix(items, empty=None, *, separator_size=2, displaywith=80):`

**Comment by ccordoba12** [comment]
Hey @sharon92, thanks for reporting. That's indeed the case and it was fixed in Qtconsole version 5.5.1.

@dalthviz, I think this requires a new Spyder 5.5.1 release so that our installers don't have this bug. What do you think?

**Comment by dalthviz** [comment]
I think we could manually trigger the installers build and update the assets in the 5.5.0 release. That should take into account QtConsole 5.5.1 being available. Or there is a need for some change to be done over the Spyder code side?

**Comment by ccordoba12** [comment]
> I think we could manually trigger the installers build and update the assets in the 5.5.0 release. That should take into account QtConsole 5.5.1 being available.

That's a very good idea! I haven't thought about it.

> Or there is a need for some change to be done over the Spyder code side @ccordoba12 ?

Nop, we don't need to do anything on our side. So, please proceed with your suggestion to generate new installers.

**Comment by dalthviz** [comment]
So I rerunned the workflows to generated the installers. For Windows and macOS the installera were build without issues and the new assets were uploaded to the Github release (I left the old ones just in case renaming them to have as suffix `_qtconsole_550` or `-qtconsole-550`). However, I was unable to run the conda-based linux installer workflow. [It fails with a message regarding mamba command not being found ](https://github.com/spyder-ide/spyder/actions/runs/6793367922/job/18907230390)🤔

**Comment by ccordoba12** [comment]
Thanks @dalthviz! Did you test the Windows and Mac installers? If they're working fine, please remove the Qtconsole 5.5.0 assets.

And don't worry about the Linux installers. Since it's still labeled as experimental, I don't think we should spend time to update it.

**Comment by dalthviz** [comment]
> Did you test the Windows and Mac installers?

Checked and seems like they are working :+1: So I removed the installers from the release assets that had QtConsole 5.5.0

**Comment by ccordoba12** [comment]
Thanks @dalthviz! Closing this one then.
