### ISSUE TITLE
Spyder not launching via standalone app or Anaconda Navigator

### ISSUE THREAD

**Issue by DLW09** [spyder-ide/spyder#21671]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Hello all,

Thank you in advance for checking this out. I am submitting this on behalf of the actual user as a forewarning. Each time we go to launch Spyder on this machine it must be reinstalled. Once uninstalled and reinstalled the program works as expected; however, when attempting to open the program the next day it will not launch via the App icon in the Windows start menu or via the Anaconda Navigator. I could not find a similar open ticket so I am submitting this as a last-chance step to workaround this issue.

### What steps reproduce the problem?

1. Open Spyder via Desktop app -- initializes then closes
2.Open Spyder via Anaconda Navigator -- gives Traceback/error below

### What is the expected output? What do you see instead?
Expected Spyder to open as normal

Instead the app closed or gave Traceback/error below

### Paste Traceback/Error Below (if applicable)

```
Traceback (most recent call last):
File "C:ProgramDataanaconda3Scriptsspyder-script.py", line 10, in 
sys.exit(main())
^^^^^^
File "C:ProgramDataanaconda3Libsite-packagesspyderappstart.py", line 256, in main
mainwindow.main(options, args)
File "C:ProgramDataanaconda3Libsite-packagesspyderappmainwindow.py", line 1823, in main
mainwindow = create_window(MainWindow, app, splash, options, args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:ProgramDataanaconda3Libsite-packagesspyderapputils.py", line 289, in create_window
main.setup()
File "C:ProgramDataanaconda3Libsite-packagesspyderappmainwindow.py", line 732, in setup
internal_plugins = find_internal_plugins()
^^^^^^^^^^^^^^^^^^^^^^^
File "C:ProgramDataanaconda3Libsite-packagesspyderappfind_plugins.py", line 40, in find_internal_plugins
mod = importlib.import_module(entry_point.module_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:ProgramDataanaconda3Libimportlib\__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "", line 1204, in _gcd_import
File "", line 1176, in _find_and_load
File "", line 1147, in _find_and_load_unlocked
File "", line 690, in _load_unlocked
File "", line 940, in exec_module
File "", line 241, in _call_with_frames_removed
File "C:ProgramDataanaconda3Libsite-packagesspyderpluginseditorplugin.py", line 49, in 
from spyder.plugins.editor.widgets.codeeditor import CodeEditor
File "C:ProgramDataanaconda3Libsite-packagesspyderpluginseditorwidgetscodeeditor.py", line 33, in 
from IPython.core.inputtransformer2 import TransformerManager
File "C:ProgramDataanaconda3Libsite-packagesIPython\__init__.py", line 54, in 
from .terminal.embed import embed
File "C:ProgramDataanaconda3Libsite-packagesIPython	erminalembed.py", line 15, in 
from IPython.core.interactiveshell import DummyMod, InteractiveShell
File "C:ProgramDataanaconda3Libsite-packagesIPythoncoreinteractiveshell.py", line 73, in 
from IPython.core.history import HistoryManager
File "C:ProgramDataanaconda3Libsite-packagesIPythoncorehistory.py", line 11, in 
import sqlite3
File "C:ProgramDataanaconda3Libsqlite3\__init__.py", line 57, in 
from sqlite3.dbapi2 import *
File "C:ProgramDataanaconda3Libsqlite3dbapi2.py", line 27, in 
from _sqlite3 import *
ImportError: DLL load failed while importing _sqlite3: The specified procedure could not be found.
``

## Versions
<!--- You can get this information from Help > About Spyder...
or (if Spyder won't launch) the "conda list" command
from the Anaconda Prompt/Terminal/command line. --->

* Spyder version: 
* Python version: Python 3.11.5
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10 Professional Edition (Build 19045) (64-bit) (Release ID 22H2)

### Dependencies
<!--- Please go to the menu entry Help > Dependencies,
press the Copy to clipboard button and paste below --->

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @DLW09, thanks for reporting and sorry for the late reply. You said:

> Each time we go to launch Spyder on this machine it must be reinstalled. Once uninstalled and reinstalled the program works as expected; however, when attempting to open the program the next day it will not launch

Are some additional packages installed automatically between one day and the next one? Or how does the setup of that computer changes from day to day?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
