### ISSUE TITLE
Spyder IPython Console throwing " An error ocurred while starting the kernel"

### ISSUE THREAD

**Issue by Lilly024** [spyder-ide/spyder#21717]
Hello I got this eror when launching Sypder IDE:

The error is:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 100, in secure_write
win32_restrict_file_to_user(fname)
File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 53, in win32_restrict_file_to_user
import win32api
ImportError: DLL load failed: The specified procedure could not be found.

Does anyone know how to fix this? THank you

**Comment by Lilly024** [comment]
solved it. I needed different version of pywin32.

**Comment by GitKia1392** [comment]
And does anyone know why so recently the devs r taking so long to respond.
