### ISSUE TITLE
error opening spyder in Macbook M1 chip

### ISSUE THREAD

**Issue by kshtjkumar** [spyder-ide/spyder#21720]
## Problem Description
Traceback (most recent call last):
  File "/Users/kshitijkumar/miniconda3/bin/spyder", line 8, in <module>
    sys.exit(main())
  File "/Users/kshitijkumar/miniconda3/lib/python3.10/site-packages/spyder/app/start.py", line 132, in main
    from spyder.config.manager import CONF
  File "/Users/kshitijkumar/miniconda3/lib/python3.10/site-packages/spyder/config/manager.py", line 22, in <module>
    from spyder.config.main import CONF_VERSION, DEFAULTS, NAME_MAP
  File "/Users/kshitijkumar/miniconda3/lib/python3.10/site-packages/spyder/config/main.py", line 21, in <module>
    from spyder.config.appearance import APPEARANCE
  File "/Users/kshitijkumar/miniconda3/lib/python3.10/site-packages/spyder/config/appearance.py", line 15, in <module>
    from spyder.plugins.help.utils.sphinxify import CSS_PATH
  File "/Users/kshitijkumar/miniconda3/lib/python3.10/site-packages/spyder/plugins/help/utils/sphinxify.py", line 37, in <module>
    from sphinx.application import Sphinx
  File "/Users/kshitijkumar/miniconda3/lib/python3.10/site-packages/sphinx/application.py", line 25, in <module>
    from sphinx.config import Config
  File "/Users/kshitijkumar/miniconda3/lib/python3.10/site-packages/sphinx/config.py", line 13, in <module>
    from sphinx.util import logging
  File "/Users/kshitijkumar/miniconda3/lib/python3.10/site-packages/sphinx/util/__init__.py", line 24, in <module>
    from sphinx.util.nodes import (  # noqa: F401
  File "/Users/kshitijkumar/miniconda3/lib/python3.10/site-packages/sphinx/util/nodes.py", line 12, in <module>
    from sphinx import addnodes
  File "/Users/kshitijkumar/miniconda3/lib/python3.10/site-packages/sphinx/addnodes.py", line 18, in <module>
    'meta': (nodes.meta, 'docutils.nodes.meta'),  # type: ignore[attr-defined]
AttributeError: module 'docutils.nodes' has no attribute 'meta'

**Comment by ccordoba12** [comment]
Hey @kshtjkumar, thanks for reporting. I have some questions for you:

1. What's your Spyder version?
2. What command did you use to install it?
3. What's your Sphinx version?

**Comment by kshtjkumar** [comment]
Spyder version  5.5.0
pip install spyder
sphinx-build 7.2.6
docutils (Docutils 0.20.1, Python 3.10.13, on darwin)

**Comment by ccordoba12** [comment]
Ok, the problem could be that you used pip to install Spyder in a conda environment. That's not a good thing to do because pip and conda packages are binary incompatible. Furthermore, you shouldn't have done that in your base Miniconda environment because that probably broke it too.

So, my recommendations for you are the following:

* Remove and reinstall Miniconda.
* Use the following commands to install and run Spyder from Conda-forge:

      conda create -n spyder-env -c conda-forge spyder=5.5
      conda activate spyder-env
      spyder

Let us know if that works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
