### ISSUE TITLE
spyder issue

### ISSUE THREAD

**Issue by el-izzz** [spyder-ide/spyder#21727]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/elizabethdeng/anaconda3/envs/spyder-3.2.3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 60, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/Users/elizabethdeng/anaconda3/envs/spyder-3.2.3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 330, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):
  File "/Users/elizabethdeng/anaconda3/envs/spyder-3.2.3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 127, in get_cwd
    self.silent_exec_method(code)
  File "/Users/elizabethdeng/anaconda3/envs/spyder-3.2.3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 330, in silent_exec_method
    'silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.13
* Qt Versions: 5.9.6, PyQt5 5.9.2 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  2.4.0 (OK)
pycodestyle >=2.3:  2.8.0 (OK)
pygments >=2.0   :  2.11.2 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  4.4.0 (OK)
rope >=0.9.4     :  0.22.0 (OK)
jedi >=0.9.0     :  0.18.0 (OK)
psutil >=0.3     :  5.8.0 (OK)
nbconvert >=4.0  :  6.0.7 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  5.2.2 (OK)
IPython >=4.0    :  5.8.0 (OK)
pylint >=0.25    :  2.9.6 (OK)

```

**Comment by ccordoba12** [comment]
Hey @el-izzz, thanks for reporting. I'm afraid you'll have to remove and [reinstall Anaconda](https://www.anaconda.com/download) because you're using a very old version of it, and with it an old Spyder version. If you do that, you'll get Spyder 5.4.3, which doesn't have this error (you're using Spyder 3.2.3 now).
