### ISSUE TITLE
error while starting Kernel

### ISSUE THREAD

**Issue by Tech33Blue** [spyder-ide/spyder#21726]
### What steps will reproduce the problem?

opening spyder. when I open spyder, it crashes.
chcp is not recognized.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\mgraz\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 91, in wrapper
    self._ready.set_result(None)
asyncio.exceptions.InvalidStateError: invalid state

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mgraz\AppData\Local\Programs\Spyder\pkgs\qtconsole\manager.py", line 27, in poll
    super().poll()
  File "C:\Users\mgraz\AppData\Local\Programs\Spyder\pkgs\jupyter_client\restarter.py", line 143, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "C:\Users\mgraz\AppData\Local\Programs\Spyder\pkgs\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "C:\Users\mgraz\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 596, in _async_restart_kernel
    await self._async_start_kernel(**self._launch_args)
  File "C:\Users\mgraz\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 94, in wrapper
    self._ready.set_exception(e)
asyncio.exceptions.InvalidStateError: invalid state
```

## Versions

* Spyder version: 5.5.0  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.2.0 (OK)
cloudpickle >=0.5.0           :  3.0.0 (OK)
cookiecutter >=1.6.0          :  2.5.0 (OK)
diff_match_patch >=20181111   :  20230430 (OK)
intervaltree                  :  None (OK)
IPython >=8.12.2,<8.13.0      :  8.12.3 (OK)
jedi >=0.17.2,<0.20.0         :  0.19.1 (OK)
jellyfish >=0.7               :  1.0.3 (OK)
jsonschema >=3.2.0            :  4.20.0 (OK)
keyring >=17.0.0              :  24.3.0 (OK)
nbconvert >=4.0               :  7.11.0 (OK)
numpydoc >=0.6.0              :  1.6.0 (OK)
paramiko >=2.4.0              :  3.3.1 (OK)
parso >=0.7.0,<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.6 (OK)
pygments >=2.0                :  2.17.1 (OK)
pylint >=2.5.0,<3.1           :  3.0.2 (OK)
pylint_venv >=3.0.2           :  3.0.3 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.9.0,<1.10.0         :  1.9.0 (OK)
pylsp_black >=1.2.0,<3.0.0    :  1.3.0 (OK)
qdarkstyle >=3.2.0,<3.3.0     :  3.2.1 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.3 (OK)
qtconsole >=5.5.0,<5.6.0      :  5.5.1 (OK)
qtpy >=2.1.0                  :  2.4.1 (OK)
rtree >=0.9.7                 :  1.1.0 (OK)
setuptools >=49.6.0           :  69.0.2 (OK)
sphinx >=0.6.6                :  7.1.2 (OK)
spyder_kernels >=2.5.0,<2.6.0 :  2.5.0 (OK)
textdistance >=4.2.0          :  4.6.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  3.0.0 (OK)
zmq >=22.1.0                  :  25.1.1 (OK)

# Optional:
cython >=0.21                 :  3.0.5 (OK)
matplotlib >=3.0.0            :  3.7.4 (OK)
numpy >=1.7                   :  1.24.4 (OK)
pandas >=1.1.1                :  2.0.3 (OK)
scipy >=0.17.0                :  1.10.1 (OK)
sympy >=0.7.3                 :  1.12 (OK)
```

**Comment by ccordoba12** [comment]
Hey @Tech33Blue, thanks for reporting. Did you change the Python interpreter used by Spyder in

    Preferences > Python interpreter

?

**Comment by Tech33Blue** [comment]
Hi,
Thanks for helping. Yes I change the interpreter. It turned out the issue
was in the "PATH" for user variable, that had been mistakenly changed by
some previous installation. After I amended the PATH
[image: path for fixing spyder.jpg]
 back to "windows/system32", everything worked fine.

Mobile: +44 7948046491
E-mail: ***@***.*** ***@***.***>
Linkedin: https://www.linkedin.com/in/marcello-graziosi/

**Comment by Tech33Blue** [comment]
![path for fixing spyder](https://github.com/spyder-ide/spyder/assets/157184267/cba33406-1741-4f4d-8e2c-52b561fb3145)

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know about it and glad you were able to solve the problem on your own.
