### ISSUE TITLE
DLL load failed while importing _sqlite3

### ISSUE THREAD

**Issue by albe-jj** [spyder-ide/spyder#21731]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Created a new environment 
``` 
conda create -n spyder54 spyder=5.4
activate spyder54
```

run spyder from anaconda terminal in the spyder54 environemnt

got the following error and Spyder closes down at startup.
```python
fromIccProfile: failed minimal tag size sanity
Traceback (most recent call last):
  File "C:\Users\atosato\Anaconda3\envs\spyder54\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\atosato\Anaconda3\envs\spyder54\Lib\site-packages\spyder\app\start.py", line 256, in main
    mainwindow.main(options, args)
  File "C:\Users\atosato\Anaconda3\envs\spyder54\Lib\site-packages\spyder\app\mainwindow.py", line 1823, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\atosato\Anaconda3\envs\spyder54\Lib\site-packages\spyder\app\utils.py", line 289, in create_window
    main.setup()
  File "C:\Users\atosato\Anaconda3\envs\spyder54\Lib\site-packages\spyder\app\mainwindow.py", line 732, in setup
    internal_plugins = find_internal_plugins()
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\atosato\Anaconda3\envs\spyder54\Lib\site-packages\spyder\app\find_plugins.py", line 40, in find_internal_plugins
    mod = importlib.import_module(entry_point.module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\atosato\Anaconda3\envs\spyder54\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\atosato\Anaconda3\envs\spyder54\Lib\site-packages\spyder\plugins\editor\plugin.py", line 49, in <module>
    from spyder.plugins.editor.widgets.codeeditor import CodeEditor
  File "C:\Users\atosato\Anaconda3\envs\spyder54\Lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 33, in <module>
    from IPython.core.inputtransformer2 import TransformerManager
  File "C:\Users\atosato\Anaconda3\envs\spyder54\Lib\site-packages\IPython\__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "C:\Users\atosato\Anaconda3\envs\spyder54\Lib\site-packages\IPython\terminal\embed.py", line 15, in <module>
    from IPython.core.interactiveshell import DummyMod, InteractiveShell
  File "C:\Users\atosato\Anaconda3\envs\spyder54\Lib\site-packages\IPython\core\interactiveshell.py", line 97, in <module>
    from IPython.core.history import HistoryManager
  File "C:\Users\atosato\Anaconda3\envs\spyder54\Lib\site-packages\IPython\core\history.py", line 11, in <module>
    import sqlite3
  File "C:\Users\atosato\Anaconda3\envs\spyder54\Lib\sqlite3\__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "C:\Users\atosato\Anaconda3\envs\spyder54\Lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed while importing _sqlite3: The specified procedure could not be found.
```

## Versions

* Spyder version: 5.4.3
* Python version: 3.11.7
* Qt version: seems not to be installed in my env
* PyQt version: 5.15.10
* Operating System name/version:

**Comment by albe-jj** [comment]
I fixed this by downloading the sqlite3 ddl [here](https://www.sqlite.org/download.html) and copying the downloaded files (`sqlite3.dll`, `sqlite3.def`)  into `C:\Users\yor_user_name\Anaconda3\envs\your_environment_name\DLLs`

**Comment by ccordoba12** [comment]
Hey @albe-jj, thanks for reporting and letting us know how you managed to fix this problem.

**Comment by TomBlackH** [comment]
> I fixed this by downloading the sqlite3 ddl [here](https://www.sqlite.org/download.html) and copying the downloaded files (`sqlite3.dll`, `sqlite3.def`) into `C:\Users\yor_user_name\Anaconda3\envs\your_environment_name\DLLs`

You are my HERO!!! Thank you!!!!

**Comment by Dr-Spicy** [comment]
> I fixed this by downloading the sqlite3 ddl [here](https://www.sqlite.org/download.html) and copying the downloaded files (`sqlite3.dll`, `sqlite3.def`) into `C:\Users\yor_user_name\Anaconda3\envs\your_environment_name\DLLs`

Thanks very much, OP! Just add a minor explanation to newbies like me, from the website, you download the 'Precompiled Binaries' for your OS and unzip them into wherever your environment is located '...\Anaconda3\envs\your_enviroment_name\DLLs' , not necessarily on the C: drive.

**Comment by neEdsMorepaIsLeY** [comment]
> I fixed this by downloading the sqlite3 ddl [here](https://www.sqlite.org/download.html) and copying the downloaded files (`sqlite3.dll`, `sqlite3.def`) into `C:\Users\yor_user_name\Anaconda3\envs\your_environment_name\DLLs`

This worked for me as well! Thank you.
