### ISSUE TITLE
Spyder shutdown

### ISSUE THREAD

**Issue by dbenjamin9** [spyder-ide/spyder#21732]
### What steps will reproduce the problem?

Bad address (C:\ci\zeromq_1616055400030\work\src\epoll.cpp:100)
Traceback (most recent call last):
File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
self._poll(timeout)
RuntimeError: still has pending operation at deallocation, the process may crash
Bad address (C:\ci\zeromq_1616055400030\work\src\epoll.cpp:100)
Bad address (C:\ci\zeromq_1616055400030\work\src\epoll.cpp:100)
Bad address (C:\ci\zeromq_1616055400030\work\src\epoll.cpp:100)

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEACF30> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DADCBAB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DADCBAB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAED30> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEDF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\dushi\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000280DAEAEBB0> still has pending operation at deallocation, the process may crash
```

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.11.7 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  2.5.0 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.20.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  1.0.1 (OK)
jsonschema >=3.2.0                               :  4.19.2 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  7.10.0 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.4.1 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.2.2 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.4 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  25.1.2 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.8.0 (OK)
numpy >=1.7                                      :  1.26.3 (OK)
pandas >=1.1.1                                   :  2.1.4 (OK)
scipy >=0.17.0                                   :  1.11.4 (OK)
sympy >=0.7.3                                    :  1.12 (OK)
```

**Comment by ccordoba12** [comment]
Hey @dbenjamin9, thanks for reporting. We don't know why this happens but let's try this: please close Spyder, open the Anaconda prompt and run the following command there:

    conda install pyzmq=25.0

Then start Spyder and check again. Perhaps that solves your problem.

**Comment by GitKia1392** [comment]
@dbenjamin9 oh hell nah bro wtf is that bro got 3 billion errors in three sec while OPENING spyder. bro....
