### ISSUE TITLE
Crash after setting empty high DPI scaling factor

### ISSUE THREAD

**Issue by jeremymatt** [spyder-ide/spyder#21733]
### What steps will reproduce the problem?

Spyder crashed after I did the following:
1. Set the custom high DPI scaling to 2
1. Restarted Spyder 
1. After realizing that was too large, I deleted the custom DPI scaling value
1. I then selected "Enable auto high DPI scaling"
1. Click apply

Not sure if this is repeatable, this is the first time it's crashed.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\jerem\anaconda3\envs\shadow\lib\site-packages\spyder\plugins\preferences\widgets\configdialog.py", line 142, in button_clicked
    configpage.apply_changes()
  File "C:\Users\jerem\anaconda3\envs\shadow\lib\site-packages\spyder\plugins\preferences\api.py", line 118, in apply_changes
    self.apply_callback()
  File "C:\Users\jerem\anaconda3\envs\shadow\lib\site-packages\spyder\plugins\preferences\api.py", line 150, in <lambda>
    self._apply_settings_tabs(self.changed_options))
  File "C:\Users\jerem\anaconda3\envs\shadow\lib\site-packages\spyder\plugins\preferences\api.py", line 178, in _apply_settings_tabs
    self.apply_settings(options)
  File "C:\Users\jerem\anaconda3\envs\shadow\lib\site-packages\spyder\plugins\application\confpage.py", line 249, in apply_settings
    scale_factor = float(scale_factor)
ValueError: could not convert string to float: ''
```

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.10.12 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  1.7.3 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.12.2 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  0.9.0 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  6.5.4 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.2.0 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.0.0 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.4 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  25.1.0 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.7.2 (OK)
numpy >=1.7                                      :  1.25.2 (OK)
pandas >=1.1.1                                   :  2.0.3 (OK)
scipy >=0.17.0                                   :  1.11.1 (OK)
sympy >=0.7.3                                    :  None (NOK)
```

**Comment by jeremymatt** [comment]
After some testing, it does appear that the "Spyder encountered an internal error" warning does appear when switching from custom to auto scaling if the custom scaling field is empty.  I haven't checked to see if this is a known issue, so my apologies if it's a duplicate.

**Comment by GitKia1392** [comment]
Could you tell me how much DPI, mine has 7200 dpi and it's flawless.

Thanks

**Comment by jeremymatt** [comment]
The spyder version is 5.4.3.  I'm not sure of the DPI, but its 1920x1200 on a 17-inch screen.  I'm not sure if it's a matter of screen resolution though, as it only seems to happen when the "custom scaling" field is blank.

**Comment by ccordoba12** [comment]
Hey @jeremymatt, thanks for reporting. I was able to reproduce this error and it'll be fixed in our next version (5.5.1), to be released at the end of the week.

**Comment by jeremymatt** [comment]
@ccordoba12 Thanks!  Your work on Spyder is appreciated!

**Comment by GitKia1392** [comment]
--close issue 21733 merge none comment ---
Hey sorry i thought yo ment yo mouse DPI

--end comment at 0x02630137 21733
