### ISSUE TITLE
Installed Pycharm broke Sypder

### ISSUE THREAD

**Issue by WillItWithWill** [spyder-ide/spyder#21753]
### What steps will reproduce the problem?

I installed pycharm and it broke the kernel for spyder

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\Canib\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 91, in wrapper
    self._ready.set_result(None)
asyncio.exceptions.InvalidStateError: invalid state

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Canib\AppData\Local\Programs\Spyder\pkgs\qtconsole\manager.py", line 27, in poll
    super().poll()
  File "C:\Users\Canib\AppData\Local\Programs\Spyder\pkgs\jupyter_client\restarter.py", line 143, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "C:\Users\Canib\AppData\Local\Programs\Spyder\pkgs\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "C:\Users\Canib\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 596, in _async_restart_kernel
    await self._async_start_kernel(**self._launch_args)
  File "C:\Users\Canib\AppData\Local\Programs\Spyder\pkgs\jupyter_client\manager.py", line 94, in wrapper
    self._ready.set_exception(e)
asyncio.exceptions.InvalidStateError: invalid state
```

## Versions

* Spyder version: 5.5.0  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.2.0 (OK)
cloudpickle >=0.5.0           :  3.0.0 (OK)
cookiecutter >=1.6.0          :  2.4.0 (OK)
diff_match_patch >=20181111   :  20230430 (OK)
intervaltree                  :  None (OK)
IPython >=8.12.2,<8.13.0      :  8.12.3 (OK)
jedi >=0.17.2,<0.20.0         :  0.19.1 (OK)
jellyfish >=0.7               :  1.0.1 (OK)
jsonschema >=3.2.0            :  4.19.2 (OK)
keyring >=17.0.0              :  24.2.0 (OK)
nbconvert >=4.0               :  7.11.0 (OK)
numpydoc >=0.6.0              :  1.6.0 (OK)
paramiko >=2.4.0              :  3.3.1 (OK)
parso >=0.7.0,<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.6 (OK)
pygments >=2.0                :  2.16.1 (OK)
pylint >=2.5.0,<3.1           :  3.0.2 (OK)
pylint_venv >=3.0.2           :  3.0.3 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.9.0,<1.10.0         :  1.9.0 (OK)
pylsp_black >=1.2.0,<3.0.0    :  1.3.0 (OK)
qdarkstyle >=3.2.0,<3.3.0     :  3.2 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.3 (OK)
qtconsole >=5.5.0,<5.6.0      :  5.5.0 (OK)
qtpy >=2.1.0                  :  2.4.1 (OK)
rtree >=0.9.7                 :  1.1.0 (OK)
setuptools >=49.6.0           :  68.2.2 (OK)
sphinx >=0.6.6                :  7.1.2 (OK)
spyder_kernels >=2.5.0,<2.6.0 :  2.5.0 (OK)
textdistance >=4.2.0          :  4.6.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  3.0.0 (OK)
zmq >=22.1.0                  :  25.1.1 (OK)

# Optional:
cython >=0.21                 :  3.0.5 (OK)
matplotlib >=3.0.0            :  3.7.3 (OK)
numpy >=1.7                   :  1.24.4 (OK)
pandas >=1.1.1                :  2.0.3 (OK)
scipy >=0.17.0                :  1.10.1 (OK)
sympy >=0.7.3                 :  1.12 (OK)
```

**Comment by WillItWithWill** [comment]
Error still present

Traceback (most recent call last):
File "Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "Python\Python310\lib\runpy.py", line 86, in _run_code
exec(code, run_globals)
File
"Python\Python310\lib\site‑packages\spyder_kernels\console\__main__.py",
line 22, in
from spyder_kernels.console import start
File "Python\Python310\lib\site‑packages\spyder_kernels\console\start.py",
line 20, in
import ipykernel
ModuleNotFoundError: No module named 'ipykernel'

**Comment by ccordoba12** [comment]
Ok, so according to the info you posted you installed the standalone version of Spyder and are trying to connect it to another Python 3.10 installation.

Is that correct?

**Comment by WillItWithWill** [comment]
Yes. Originally, I had this issue and installed the kernel to my python but
it has recently broken again but I am not sure if the error is the same or
different as it was quite some time ago. But I am having other issues as
well even in pycharm i am having issues currently not finding packages that
are surely there as I believe is triggering this error as well. I repaired
the python 3.10 and the error persists.

**Comment by WillItWithWill** [comment]
I fixed the issue by using "pip install --upgrade spyder-kernels" which I
believe reinstalled dependencies as well.

**Comment by ccordoba12** [comment]
Ok, great! Thanks for letting us know about it.
