### ISSUE TITLE
Wont save to downloads folder

### ISSUE THREAD

**Issue by angusGibsoN** [spyder-ide/spyder#21768]
### What steps will reproduce the problem?

Treid to save to download folder got this popup. 

opend this file from a network drive.

made changes, then went to save to local drive and got error

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\NenMa\anaconda3\Lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1532, in has_filename
    return data_filenames.index(filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 'C:\\Users\\NenMa\\Downloads\\DataProcessingV2.py' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen ntpath>", line 696, in realpath
OSError: [WinError 1326] The user name or password is incorrect: 'H:\\EE106\\DataProcessing.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NenMa\anaconda3\Lib\site-packages\spyder\plugins\editor\plugin.py", line 2444, in save_as
    if editorstack.save_as():
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NenMa\anaconda3\Lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2089, in save_as
    ao_index = self.has_filename(filename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NenMa\anaconda3\Lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1542, in has_filename
    if filename == fixpath(editor_filename):
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NenMa\anaconda3\Lib\site-packages\spyder\plugins\explorer\widgets\utils.py", line 54, in fixpath
    return norm(osp.abspath(osp.realpath(path)))
                            ^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 702, in realpath
  File "<frozen ntpath>", line 650, in _getfinalpathname_nonstrict
OSError: [WinError 1326] The user name or password is incorrect: 'H:\\EE106\\DataProcessing.py'
```

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.11.4 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  1.7.3 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.12.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  0.9.0 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  6.5.4 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.2.0 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.0.0 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.3 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  23.2.0 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.7.1 (OK)
numpy >=1.7                                      :  1.24.3 (OK)
pandas >=1.1.1                                   :  1.5.3 (OK)
scipy >=0.17.0                                   :  1.10.1 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @angusGibsoN, thanks for reporting. I have a quick question for you: is you network drive password-protected?

**Comment by angusGibsoN** [comment]
ye

**Comment by ccordoba12** [comment]
Ok, but just to be sure: were you able to view that file in Spyder despite being in a password-protected drive?

**Comment by angusGibsoN** [comment]
ye I opened it and was editing it in spyder

**Comment by ccordoba12** [comment]
Ok, thanks for the confirmation. It seems that we're mapping the drive correctly because you said you're using a network drive but in the error report there's this line

    OSError: [WinError 1326] The user name or password is incorrect: 'H:\\EE106\\DataProcessing.py'

So, is your drive mounted at `H:\`? Or is that not incorrect?

**Comment by angusGibsoN** [comment]
yes its H:
