### ISSUE TITLE
Issue launching Spyder: "configparser.NoSectionError: No section: 'workingdir'"

### ISSUE THREAD

**Issue by cppt** [spyder-ide/spyder#21800]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

After recently maxing out (and subsequently making more space on) my system HD, Spyder doesn't launch via command line or Anaconda Navigator giving an error:

```
File "/home/chris/anaconda3/lib/python3.9/site-packages/spyder/config/manager.py", line 499, in get
value = config.get(section=section, option=option, default=default)
File "/home/chris/anaconda3/lib/python3.9/site-packages/spyder/config/user.py", line 980, in get
return config.get(section=section, option=option, default=default)
File "/home/chris/anaconda3/lib/python3.9/site-packages/spyder/config/user.py", line 511, in get
raise cp.NoSectionError(section)
configparser.NoSectionError: No section: 'workingdir'
```
Imagine some config file got crunched/truncated but not sure where/how/why.  

### What steps reproduce the problem?

1. 
2. 
3. 

### What is the expected output? What do you see instead?
Spyder launch successfully

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
File "/home/chris/anaconda3/bin/spyder", line 11, in 
sys.exit(main())
File "/home/chris/anaconda3/lib/python3.9/site-packages/spyder/app/start.py", line 252, in main
mainwindow.main(options, args)
File "/home/chris/anaconda3/lib/python3.9/site-packages/spyder/app/mainwindow.py", line 1956, in main
mainwindow = create_window(MainWindow, app, splash, options, args)
File "/home/chris/anaconda3/lib/python3.9/site-packages/spyder/app/utils.py", line 289, in create_window
main.setup()
File "/home/chris/anaconda3/lib/python3.9/site-packages/spyder/app/mainwindow.py", line 778, in setup
PLUGIN_REGISTRY.register_plugin(self, PluginClass,
File "/home/chris/anaconda3/lib/python3.9/site-packages/spyder/api/plugin_registration/registry.py", line 342, in register_plugin
instance = self._instantiate_spyder5_plugin(
File "/home/chris/anaconda3/lib/python3.9/site-packages/spyder/api/plugin_registration/registry.py", line 193, in _instantiate_spyder5_plugin
plugin_instance.initialize()
File "/home/chris/anaconda3/lib/python3.9/site-packages/spyder/api/plugins/new_api.py", line 669, in initialize
self.on_initialize()
File "/home/chris/anaconda3/lib/python3.9/site-packages/spyder/plugins/workingdirectory/plugin.py", line 82, in on_initialize
container.set_history(
File "/home/chris/anaconda3/lib/python3.9/site-packages/spyder/plugins/workingdirectory/container.py", line 323, in set_history
workdir = self._get_init_workdir()
File "/home/chris/anaconda3/lib/python3.9/site-packages/spyder/plugins/workingdirectory/container.py", line 183, in _get_init_workdir
workdir = self.get_conf('startup/fixed_directory')
File "/home/chris/anaconda3/lib/python3.9/site-packages/spyder/api/config/mixins.py", line 76, in get_conf
return CONF.get(section, option, default)
File "/home/chris/anaconda3/lib/python3.9/site-packages/spyder/config/manager.py", line 499, in get
value = config.get(section=section, option=option, default=default)
File "/home/chris/anaconda3/lib/python3.9/site-packages/spyder/config/user.py", line 980, in get
return config.get(section=section, option=option, default=default)
File "/home/chris/anaconda3/lib/python3.9/site-packages/spyder/config/user.py", line 511, in get
raise cp.NoSectionError(section)
configparser.NoSectionError: No section: 'workingdir'

```

## Versions

* Spyder version: 5.3.3
* Python version:  3.9
* Qt version: 5.15.2
* PyQt version: NA
* Operating System name/version:  Ubuntu 22.04

**Comment by Jammi-Dodgers** [comment]
I had the same issue and fixed it by resetting Spyder's configuration settings.
spyder --reset

**Comment by GardillA** [comment]
Thank you 🙏 I just ran into this exact issue (windows 11) and have been trying to solve the issue for the last full day. I just reset spyder and it now opens again.
