### ISSUE TITLE
Spyder: Cannot connect to iPython console

### ISSUE THREAD

**Issue by LOScott-Models** [spyder-ide/spyder#21866]
### What steps will reproduce the problem?

I received the error messages below.  I have already uninstalled anaconda and re-installed anaconda.  Whe I start spyder, the iPython does not start.  It spins with the following message:  "Connecting to kernel"

I am on Github:  LOScott-Models with email: LOScott@outlook.com

### Traceback
```python-traceback
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\threaded.py", line 147, in _handle_recv
    msg = self.session.deserialize(smsg)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\session.py", line 1079, in deserialize
    message["header"] = extract_dates(header)
                        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\jsonutil.py", line 75, in extract_dates
    new_obj[k] = extract_dates(v)
                 ^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\jsonutil.py", line 80, in extract_dates
    obj = parse_date(obj)
          ^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\jsonutil.py", line 65, in parse_date
    dt = _dateutil_parse(s)
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\losco\AppData\Roaming\Python\Python311\site-packages\dateutil\parser.py", line 748, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\losco\AppData\Roaming\Python\Python311\site-packages\dateutil\parser.py", line 324, in parse
    if isinstance(tzinfos, collections.Callable) or tzinfos and res.tzname in tzinfos:
                           ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\zmq\eventloop\zmqstream.py", line 634, in _handle_events
    self._handle_recv()
  File "C:\ProgramData\anaconda3\Lib\site-packages\zmq\eventloop\zmqstream.py", line 663, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\ProgramData\anaconda3\Lib\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\threaded.py", line 147, in _handle_recv
    msg = self.session.deserialize(smsg)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\session.py", line 1079, in deserialize
    message["header"] = extract_dates(header)
                        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\jsonutil.py", line 75, in extract_dates
    new_obj[k] = extract_dates(v)
                 ^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\jsonutil.py", line 80, in extract_dates
    obj = parse_date(obj)
          ^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\jsonutil.py", line 65, in parse_date
    dt = _dateutil_parse(s)
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\losco\AppData\Roaming\Python\Python311\site-packages\dateutil\parser.py", line 748, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\losco\AppData\Roaming\Python\Python311\site-packages\dateutil\parser.py", line 324, in parse
    if isinstance(tzinfos, collections.Callable) or tzinfos and res.tzname in tzinfos:
                           ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'
Exception in callback AddThreadSelectorEventLoop._handle_select([5644], [])
handle: <Handle AddThreadSelectorEventLoop._handle_select([5644], [])>
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 620, in _handle_select
    self._handle_event(r, self._readers)
  File "C:\ProgramData\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 634, in _handle_event
    callback()
  File "C:\ProgramData\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 192, in _handle_events
    handler_func(fileobj, events)
  File "C:\ProgramData\anaconda3\Lib\site-packages\zmq\eventloop\zmqstream.py", line 634, in _handle_events
    self._handle_recv()
  File "C:\ProgramData\anaconda3\Lib\site-packages\zmq\eventloop\zmqstream.py", line 663, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\ProgramData\anaconda3\Lib\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\threaded.py", line 147, in _handle_recv
    msg = self.session.deserialize(smsg)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\session.py", line 1079, in deserialize
    message["header"] = extract_dates(header)
                        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\jsonutil.py", line 75, in extract_dates
    new_obj[k] = extract_dates(v)
                 ^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\jsonutil.py", line 80, in extract_dates
    obj = parse_date(obj)
          ^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\jsonutil.py", line 65, in parse_date
    dt = _dateutil_parse(s)
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\losco\AppData\Roaming\Python\Python311\site-packages\dateutil\parser.py", line 748, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\losco\AppData\Roaming\Python\Python311\site-packages\dateutil\parser.py", line 324, in parse
    if isinstance(tzinfos, collections.Callable) or tzinfos and res.tzname in tzinfos:
                           ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'
```

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.11.7 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  2.5.0 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.20.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  1.0.1 (OK)
jsonschema >=3.2.0                               :  4.19.2 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  7.10.0 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.4.1 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.2.2 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.4 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  25.1.2 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  None (NOK)
numpy >=1.7                                      :  1.26.4 (OK)
pandas >=1.1.1                                   :  2.1.4 (OK)
scipy >=0.17.0                                   :  1.11.4 (OK)
sympy >=0.7.3                                    :  1.12 (OK)
```

**Comment by LOScott-Models** [comment]
I found the problem in the spyder documentation.  Had to run "pip install spyder-kernels==2.4.3" and there were some changes made to my packages.  Problem started when I load the bdateutil package.

**Comment by ccordoba12** [comment]
Hey @LOScott-Models, thanks for reporting. You need to remove this directory to solve your problem:

    C:\Users\losco\AppData\Roaming\Python\Python311

Also, please avoid using pip to install packages in your Anaconda installation because pip and conda packages are incompatible.
