### ISSUE TITLE
Spyder 5.5.2 crashes with RuntimeError: wrapped C/C++ object of type SpyderKernelManager has been deleted

### ISSUE THREAD

**Issue by moschles** [spyder-ide/spyder#21898]
## Problem Description

Spyder 5.5.2 crashes when attempting to access any main menu item.

### What steps reproduce the problem?

1.  Open Spyder 
2.  Graphical IDE loads fine.
3.  Click on any menu, or any menu item such as  "File>>Open" . Spyder crashes with the message below.  

This reproduces the crash identically every time. 

### What is the expected output? What do you see instead?

The entire IDE is crashing to command line. 

### Paste Traceback/Error Below (if applicable)

```
fromIccProfile: failed minimal tag size sanity
Traceback (most recent call last):
  File "/home/xpswhite/cfpga/cfpga_venv/bin/spyder", line 8, in <module>
    sys.exit(main())
  File "/home/xpswhite/cfpga/cfpga_venv/lib/python3.8/site-packages/spyder/app/start.py", line 256, in main
    mainwindow.main(options, args)
  File "/home/xpswhite/cfpga/cfpga_venv/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 1847, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "/home/xpswhite/cfpga/cfpga_venv/lib/python3.8/site-packages/spyder/app/utils.py", line 300, in create_window
    main.post_visible_setup()
  File "/home/xpswhite/cfpga/cfpga_venv/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 1050, in post_visible_setup
    plugin.on_mainwindow_visible()
  File "/home/xpswhite/cfpga/cfpga_venv/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 401, in on_mainwindow_visible
    self.create_new_client(give_focus=False)
  File "/home/xpswhite/cfpga/cfpga_venv/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 538, in create_new_client
    self.get_widget().create_new_client(
  File "/home/xpswhite/cfpga/cfpga_venv/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/widgets/main_widget.py", line 1522, in create_new_client
    self.connect_client_to_kernel(client, km, kc)
  File "/home/xpswhite/cfpga/cfpga_venv/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/widgets/main_widget.py", line 1792, in connect_client_to_kernel
    kc.start_channels(shell=True, iopub=True)
  File "/home/xpswhite/cfpga/cfpga_venv/lib/python3.8/site-packages/qtconsole/kernel_mixins.py", line 47, in start_channels
    super().start_channels(*args, **kw)
  File "/home/xpswhite/cfpga/cfpga_venv/lib/python3.8/site-packages/jupyter_client/threaded.py", line 319, in start_channels
    self.shell_channel._inspect = self._check_kernel_info_reply
  File "/home/xpswhite/cfpga/cfpga_venv/lib/python3.8/site-packages/jupyter_client/client.py", line 352, in shell_channel
    self._shell_channel = self.shell_channel_class(socket, self.session, self.ioloop)
  File "/home/xpswhite/cfpga/cfpga_venv/lib/python3.8/site-packages/jupyter_client/threaded.py", line 73, in __init__
    f.result(timeout=10)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 446, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError
Exception ignored in: <function KernelManager.__del__ at 0x7fdc98d833a0>
Traceback (most recent call last):
  File "/home/xpswhite/cfpga/cfpga_venv/lib/python3.8/site-packages/jupyter_client/manager.py", line 217, in __del__
  File "/home/xpswhite/cfpga/cfpga_venv/lib/python3.8/site-packages/jupyter_client/manager.py", line 336, in _close_control_socket
  File "/home/xpswhite/cfpga/cfpga_venv/lib/python3.8/site-packages/traitlets/traitlets.py", line 732, in __set__
  File "/home/xpswhite/cfpga/cfpga_venv/lib/python3.8/site-packages/traitlets/traitlets.py", line 721, in set
  File "/home/xpswhite/cfpga/cfpga_venv/lib/python3.8/site-packages/traitlets/traitlets.py", line 1505, in _notify_trait
  File "/home/xpswhite/cfpga/cfpga_venv/lib/python3.8/site-packages/traitlets/traitlets.py", line 1517, in notify_change
  File "/home/xpswhite/cfpga/cfpga_venv/lib/python3.8/site-packages/traitlets/traitlets.py", line 1540, in _notify_observers
RuntimeError: wrapped C/C++ object of type SpyderKernelManager has been deleted
```

## Versions
* Spyder version:  5.5.2 
* Python version:  3.8.18
* QtAwesome  1.2.3
* QtPy  2.4.1     
* PyQt5                         5.15.10
* PyQt5-Qt5                     5.15.2
* PyQt5-sip                     12.13.0
* PyQtWebEngine-Qt5             5.15.2
* Operating System name/version:  Ubuntu 22.04.1 jammy x86_64 x86_64 x86_64 GNU/Linux
* Operating System Kernel: 6.5.0-25-generic 
* Operating System GUI : KDE Plasma Version 5.24.7

### Dependencies
```
PyOpenGL                      3.1.7
qtconsole                     5.5.1
rope                          1.12.0
jedi                          0.18.2
pyflakes                      3.2.0
Sphinx                        7.1.2
Pygments                      2.15.1
pylint                        3.0.4
pycodestyle                   2.11.1
psutil                        5.9.5
nbconvert                     7.16.2
QtAwesome                     1.2.3
pickleshare                   0.7.5
pyzmq                         25.0.2
QtPy                          2.4.1
chardet                       5.2.0
numpydoc                      1.6.0
cloudpickle                   2.2.1
```

**Comment by ccordoba12** [comment]
Hey @moschles, thanks for reporting. It seems you're mixing your Linux distro Python packages with the ones installed from PyPI in your venv, which could be the cause of this problem.

To avoid it, please remove that venv and install Spyder in a clean virtualenv, as described in our documentation:

http://docs.spyder-ide.org/current/installation.html#using-pip

Let us know if that works for you.

**Comment by moschles** [comment]
@ccordoba12    Thank you for the response.  Unfortunately, that virtual environment is absolutely required for a large framework within Matlab, Simulink, and a 3rd-party python library that interops with those two.   I am not the creator or maintainer of that venv, and it uses path variables that are initialized by their own scripts.   Since I require Spyder solely for the purposes of using that framework , there is no point in me playing around with freshly-created  virtual environments for no other purpose than to get Spyder working.

**Comment by moschles** [comment]
@ccordoba12  I have working 5.5.3 now, as per your directions.   One extra step was required after installation. 
```
spyder --reset 
```
That enabled the IPython Console .

**Comment by ccordoba12** [comment]
Great! I'm glad you're able to use Spyder now.
