### ISSUE TITLE
remote ssh kernel connection

### ISSUE THREAD

**Issue by mikesmith5446** [spyder-ide/spyder#21923]
### What steps will reproduce the problem?

tried to connect to posgres database and it encountered a problem with sqlalchemy

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
Traceback (most recent call last):
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 437, in data
    return to_qvariant(self.get_bgcolor(index))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msqm\AppData\Local\Programs\Python\Python311\Lib\site-packages\spyder\widgets\collectionseditor.py", line 524, in get_bgcolor
    python_type = value['python_type']
                  ~~~~~^^^^^^^^^^^^^^^
KeyError: 'python_type'
```

## Versions

* Spyder version: 5.5.1  (pip)
* Python version: 3.11.7 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.22.2 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.3 (OK)
jsonschema >=3.2.0               :  4.21.1 (OK)
keyring >=17.0.0                 :  24.3.1 (OK)
nbconvert >=4.0                  :  7.16.2 (OK)
numpydoc >=0.6.0                 :  1.6.0 (OK)
paramiko >=2.4.0                 :  3.4.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.8 (OK)
pygments >=2.0                   :  2.17.2 (OK)
pylint >=2.5.0,<3.1              :  3.0.4 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.10.0,<1.11.0           :  1.10.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.3.0 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.1 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.2.0 (OK)
setuptools >=49.6.0              :  65.5.0 (OK)
sphinx >=0.6.6                   :  7.2.6 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.1 (OK)
textdistance >=4.2.0             :  4.6.1 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.0 (OK)
zmq >=22.1.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  3.8.3 (OK)
numpy >=1.7                      :  1.26.4 (OK)
pandas >=1.1.1                   :  2.2.1 (OK)
scipy >=0.17.0                   :  1.12.0 (OK)
sympy >=0.7.3                    :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @mikesmith5446, thanks for reporting. It seems there's a mismatch between your Spyder and remote Spyder-kernels version. Please be sure of having at least version 2.5.0 of Spyder-kernels before trying to connect to it.

**Comment by mikesmith5446** [comment]
Ok thanks, I will try that

Best regards,

Mike A. Smith
Senior Digital Development Specialist

Novonesis
PO BOX 576
77 Perrys Chapel Church Road
Franklinton NC 27525 USA
Phone: +1 9194941706
Mobile: +1 9196185811
E-mail: ***@***.******@***.***>
Teams: ***@***.******@***.***>

Find Novonesis on: Web<https://www.novonesis.com/> | LinkedIn<https://www.linkedin.com/company/novonesis> | X<https://twitter.com/novonesis> | Facebook<https://www.facebook.com/novonesisbio> | Instagram<https://www.instagram.com/novonesis/>

Novozymes North America, Inc. (reg. no.: 13-2639630). Registered address: CT Corporation System, 111 8th Avenue, New York, NY 10011, United States of America, part of Novonesis Group.
This e-mail (including any attachments) is for the intended addressee(s) only and may contain confidential and/or proprietary information protected by law. You are hereby notified that any unauthorized reading, disclosure, copying or distribution of this e-mail or use of information herein is strictly prohibited. If you are not an intended recipient, you should delete this e-mail immediately. Thank you.
Your personal data will be processed in accordance with our privacy policy<https://www.novonesis.com/en/privacy-policy>.

**Comment by ccordoba12** [comment]
Closing due to lack of response. Hopefully, you managed to fix this problem.
