### ISSUE TITLE
Cannot get spyder to work in new environment

### ISSUE THREAD

**Issue by cbedick** [spyder-ide/spyder#21957]
### What steps will reproduce the problem?

I installed the latest version of anaconda. Then, I tried to create a new environment, specifically to install opencv from conda-forge. This all worked. Then, I installed the default anaconda packages so that I had spyder, etc. First time I launched spyder, this error happened. I am unable to re-launch spyder afterward. Additionllly -and most odd, is that my python.exe in the new environment is now gone after launching spyder. 

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\site-packages\qtconsole\manager.py", line 27, in poll
    super().poll()
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\site-packages\jupyter_client\restarter.py", line 143, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\site-packages\jupyter_client\manager.py", line 596, in _async_restart_kernel
    await self._async_start_kernel(**self._launch_args)
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\site-packages\jupyter_client\manager.py", line 96, in wrapper
    raise e
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\site-packages\jupyter_client\manager.py", line 87, in wrapper
    out = await method(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\site-packages\jupyter_client\manager.py", line 439, in _async_start_kernel
    await self._async_launch_kernel(kernel_cmd, **kw)
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\site-packages\jupyter_client\manager.py", line 354, in _async_launch_kernel
    connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\site-packages\jupyter_client\provisioning\local_provisioner.py", line 210, in launch_kernel
    self.process = launch_kernel(cmd, **scrubbed_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\site-packages\jupyter_client\launcher.py", line 170, in launch_kernel
    raise ex
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\site-packages\jupyter_client\launcher.py", line 155, in launch_kernel
    proc = Popen(cmd, **kwargs)  # noqa
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\site-packages\qtconsole\manager.py", line 27, in poll
    super().poll()
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\site-packages\jupyter_client\restarter.py", line 143, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\site-packages\jupyter_client\manager.py", line 596, in _async_restart_kernel
    await self._async_start_kernel(**self._launch_args)
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\site-packages\jupyter_client\manager.py", line 96, in wrapper
    raise e
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\site-packages\jupyter_client\manager.py", line 87, in wrapper
    out = await method(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\site-packages\jupyter_client\manager.py", line 439, in _async_start_kernel
    await self._async_launch_kernel(kernel_cmd, **kw)
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\site-packages\jupyter_client\manager.py", line 354, in _async_launch_kernel
    connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\site-packages\jupyter_client\provisioning\local_provisioner.py", line 210, in launch_kernel
    self.process = launch_kernel(cmd, **scrubbed_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\site-packages\jupyter_client\launcher.py", line 170, in launch_kernel
    raise ex
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\site-packages\jupyter_client\launcher.py", line 155, in launch_kernel
    proc = Popen(cmd, **kwargs)  # noqa
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\clint\anaconda3\envs\cv2_env\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

## Versions

* Spyder version: 5.5.1  (conda)
* Python version: 3.12.2 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  2.2.1 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.20.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.18.1 (OK)
jellyfish >=0.7                  :  1.0.1 (OK)
jsonschema >=3.2.0               :  4.19.2 (OK)
keyring >=17.0.0                 :  24.3.1 (OK)
nbconvert >=4.0                  :  7.10.0 (OK)
numpydoc >=0.6.0                 :  1.5.0 (OK)
paramiko >=2.4.0                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.0 (OK)
pygments >=2.0                   :  2.15.1 (OK)
pylint >=2.5.0,<3.1              :  2.16.2 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.10.0,<1.11.0           :  1.10.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.2.2 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.1 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.0.1 (OK)
setuptools >=49.6.0              :  68.2.2 (OK)
sphinx >=0.6.6                   :  5.0.2 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.0 (OK)
textdistance >=4.2.0             :  4.2.1 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.0 (OK)
zmq >=22.1.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  3.8.0 (OK)
numpy >=1.7                      :  1.26.4 (OK)
pandas >=1.1.1                   :  2.1.4 (OK)
scipy >=0.17.0                   :  1.12.0 (OK)
sympy >=0.7.3                    :  1.12 (OK)
```

**Comment by ccordoba12** [comment]
Hey @cbedick, thanks for reporting. You said:

> I installed the latest version of anaconda. Then, I tried to create a new environment, specifically to install opencv from conda-forge. This all worked. Then, I installed the default anaconda packages so that I had spyder, etc.

I think the issue lies in the second step you took, i.e. installing Spyder from Anaconda in an environment that you created previously with conda-forge packages. The thing is Anaconda and conda-forge packages are binary incompatible, so they shouldn't be mixed in the same environment.

To fix this, open the Anaconda Prompt and run there the following commands:

    conda env remove -n cv2_env
    conda create -n cv2_env_new -c conda-forge opencv spyder
    conda activate spyder
    spyder

Let us know if that fixes the problem for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
