### ISSUE TITLE
Newly installed Spyder: Kernel doesn't start

### ISSUE THREAD

**Issue by cl-ifg** [spyder-ide/spyder#21972]
### What steps will reproduce the problem?

* Spyder version: 5.5.3  (conda)
* Python version: 3.12.2 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Windows-11-10.0.22631-SP0

On fresh Spyder install via miniconda(
conda create -c conda-forge -n spyder-env spyder numpy scipy pandas matplotlib sympy cython
conda activate spyder-env
conda config --env --add channels conda-forge
conda config --env --set channel_priority strict
spyder
), Kernel does not start. Either I get the following error message, or eternally looping "connecting to kernel" message

Traceback (most recent call last):
File "C:\ProgramData\miniforge3\envs\spyder‑env\Lib\site‑packages\spyder_kernels\console\__main__.py", line 24, in
start.main()
File "C:\ProgramData\miniforge3\envs\spyder‑env\Lib\site‑packages\spyder_kernels\console\start.py", line 319, in main
kernel.initialize()
File "C:\ProgramData\miniforge3\envs\spyder‑env\Lib\site‑packages\traitlets\config\application.py", line 118, in inner
return method(app, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ProgramData\miniforge3\envs\spyder‑env\Lib\site‑packages\ipykernel\kernelapp.py", line 692, in initialize
self.init_sockets()
File "C:\ProgramData\miniforge3\envs\spyder‑env\Lib\site‑packages\ipykernel\kernelapp.py", line 331, in init_sockets
self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ProgramData\miniforge3\envs\spyder‑env\Lib\site‑packages\ipykernel\kernelapp.py", line 253, in _bind_socket
return self._try_bind_socket(s, port)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ProgramData\miniforge3\envs\spyder‑env\Lib\site‑packages\ipykernel\kernelapp.py", line 229, in _try_bind_socket
s.bind("tcp://%s:%i" % (self.ip, port))
File "C:\ProgramData\miniforge3\envs\spyder‑env\Lib\site‑packages\zmq\sugar\socket.py", line 302, in bind
super().bind(addr)
File "zmq/backend/cython/socket.pyx", line 564, in zmq.backend.cython.socket.Socket.bind
File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address in use (addr='tcp://127.0.0.1:57809')
Traceback (most recent call last):
File "", line 198, in _run_module_as_main
File "", line 88, in _run_code
File "C:\ProgramData\miniforge3\envs\spyder‑env\Lib\site‑packages\spyder_kernels\console\__main__.py", line 24, in
start.main()
File "C:\ProgramData\miniforge3\envs\spyder‑env\Lib\site‑packages\spyder_kernels\console\start.py", line 319, in main
kernel.initialize()
File "C:\ProgramData\miniforge3\envs\spyder‑env\Lib\site‑packages\traitlets\config\application.py", line 118, in inner
return method(app, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ProgramData\miniforge3\envs\spyder‑env\Lib\site‑packages\ipykernel\kernelapp.py", line 692, in initialize
self.init_sockets()
File "C:\ProgramData\miniforge3\envs\spyder‑env\Lib\site‑packages\ipykernel\kernelapp.py", line 331, in init_sockets
self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ProgramData\miniforge3\envs\spyder‑env\Lib\site‑packages\ipykernel\kernelapp.py", line 253, in _bind_socket
return self._try_bind_socket(s, port)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ProgramData\miniforge3\envs\spyder‑env\Lib\site‑packages\ipykernel\kernelapp.py", line 229, in _try_bind_socket
s.bind("tcp://%s:%i" % (self.ip, port))
File "C:\ProgramData\miniforge3\envs\spyder‑env\Lib\site‑packages\zmq\sugar\socket.py", line 302, in bind
super().bind(addr)
File "zmq/backend/cython/socket.pyx", line 564, in zmq.backend.cython.socket.Socket.bind
File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address in use (addr='tcp://127.0.0.1:57809')

**Comment by ccordoba12** [comment]
Hey @cl-ifg, thanks for reporting. I think this problem is caused by your antivirus, firewall or VPN. Please disable them (if you have any of them enabled) and try again.

Let us know if that works for you.

**Comment by cl-ifg** [comment]
The problem still persists with deactivated VPN, firewall, or antivirus.

However, I can get a working sypder if I use an older spyder version: With

### ``conda create -c conda-forge -n spyder-old-env spyder=5.4 numpy scipy pandas matplotlib sympy cython`

I can start spyder without issue in the spyder-old-env environment

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know @cl-ifg. Another idea that could help is restarting your computer to see if that frees the ports that are found to be taken.

But if that doesn't work, at least you're be able to use Spyder 5.4.3 for now.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
