### ISSUE TITLE
error popped up after short inactivity (screensaver was not active though)

### ISSUE THREAD

**Issue by juergen-bullinger** [spyder-ide/spyder#21984]
### What steps will reproduce the problem?

don't know, sorry, this was the first time this happend

### Traceback
```python-traceback
Traceback (most recent call last):

Cannot open file '/home/juergen/miniconda3/envs/project_part_3/lib/python3.7/site-packages/spyder/images/spyder.svg', because: No such file or directory
Cannot open file '/home/juergen/miniconda3/envs/project_part_3/lib/python3.7/site-packages/spyder/images/spyder.svg', because: No such file or directory
Cannot open file '/home/juergen/miniconda3/envs/project_part_3/lib/python3.7/site-packages/spyder/images/spyder.svg', because: No such file or directory
Cannot open file '/home/juergen/miniconda3/envs/project_part_3/lib/python3.7/site-packages/spyder/images/spyder.svg', because: No such file or directory
Cannot open file '/home/juergen/miniconda3/envs/project_part_3/lib/python3.7/site-packages/spyder/images/spyder.svg', because: No such file or directory
Cannot open file '/home/juergen/miniconda3/envs/project_part_3/lib/python3.7/site-packages/spyder/images/spyder.svg', because: No such file or directory
Cannot open file '/home/juergen/miniconda3/envs/project_part_3/lib/python3.7/site-packages/spyder/images/spyder.svg', because: No such file or directory
  File "/home/juergen/miniconda3/envs/project_part_3/lib/python3.7/site-packages/spyder/plugins/help/plugin.py", line 368, in set_editor_doc
  File "/home/juergen/miniconda3/envs/project_part_3/lib/python3.7/site-packages/spyder/plugins/help/widgets.py", line 982, in set_editor_doc
  File "/home/juergen/miniconda3/envs/project_part_3/lib/python3.7/site-packages/spyder/plugins/help/widgets.py", line 1031, in render_sphinx_doc
  File "/home/juergen/miniconda3/envs/project_part_3/lib/python3.7/site-packages/spyder/plugins/help/widgets.py", line 773, in show_loading_message
  File "/home/juergen/miniconda3/envs/project_part_3/lib/python3.7/site-packages/spyder/plugins/help/utils/sphinxify.py", line 104, in loading
  File "/home/juergen/miniconda3/envs/project_part_3/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
  File "/home/juergen/miniconda3/envs/project_part_3/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
  File "/home/juergen/miniconda3/envs/project_part_3/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
  File "/home/juergen/miniconda3/envs/project_part_3/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
jinja2.exceptions.TemplateNotFound: loading.html
```

## Versions

* Spyder version: 5.3.3  (conda)
* Python version: 3.7.16 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Linux 6.5.0-27-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (NOK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.5.4 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.16.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.2 (OK)
qtawesome >=1.0.2             :  1.2.2 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.6.3 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Closing due to lack of response.
