### ISSUE TITLE
Big Big problem

### ISSUE THREAD

**Issue by Flobenj** [spyder-ide/spyder#21982]
### What steps will reproduce the problem?

Hello so firstly when I started creating my program it didn't work let me know why. 
But then when it completly fucked up, and my computer didn't had enough space left. 
It by magic totally made my program of 5 hours of work disapered like my father. 
Have a good day 
soso

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.10/site-packages/spyder/app/start.py", line 219, in main
    lock_created = lock.lock()
  File "/opt/anaconda3/lib/python3.10/site-packages/spyder/utils/external/lockfile.py", line 164, in lock
    symlink(str(os.getpid()), self.name)
OSError: [Errno 28] No space left on device: '40982' -> '/amuhome/d22004836/.config/spyder-py3/spyder.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.10/site-packages/spyder/plugins/editor/utils/autosave.py", line 342, in get_autosave_filename
    autosave_filename = self.name_mapping[filename]
KeyError: '/amuhome/d22004836/Bureau/AUV_v4.6_Etud/sanstitre2.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.10/site-packages/spyder/plugins/editor/utils/autosave.py", line 135, in do_autosave
    stack.autosave.autosave_all()
  File "/opt/anaconda3/lib/python3.10/site-packages/spyder/plugins/editor/utils/autosave.py", line 425, in autosave_all
    self.maybe_autosave(index)
  File "/opt/anaconda3/lib/python3.10/site-packages/spyder/plugins/editor/utils/autosave.py", line 397, in maybe_autosave
    self.autosave(finfo)
  File "/opt/anaconda3/lib/python3.10/site-packages/spyder/plugins/editor/utils/autosave.py", line 410, in autosave
    autosave_filename = self.get_autosave_filename(finfo.filename)
  File "/opt/anaconda3/lib/python3.10/site-packages/spyder/plugins/editor/utils/autosave.py", line 355, in get_autosave_filename
    self.save_autosave_mapping()
  File "/opt/anaconda3/lib/python3.10/site-packages/spyder/plugins/editor/utils/autosave.py", line 288, in save_autosave_mapping
    with open(pidfile_name, 'w') as pidfile:
OSError: [Errno 28] Aucun espace disponible sur le périphérique: '/amuhome/d22004836/.config/spyder-py3/autosave/pid40982.txt'
```

## Versions

* Spyder version: 5.4.1  (conda)
* Python version: 3.10.9 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Linux 5.15.0-100-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<9.0.0       :  8.10.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.5.4 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.16.2 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.0;<1.8.0          :  1.7.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.6.3 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.4.1;<2.5.0 :  2.4.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.35 (OK)
matplotlib >=3.0.0            :  3.7.0 (OK)
numpy >=1.7                   :  1.23.5 (OK)
pandas >=1.1.1                :  1.5.3 (OK)
scipy >=0.17.0                :  1.10.0 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @Flobenj, thanks for reporting. Unfortunately, this is an issue we decided not to address because it's users' responsibility to check there's enough disk space to run their computations (see issue #1167 for our decision)

I'm also sorry that you lost your work but Spyder was unable to save a copy of your file because there was not enough space to do it either.
