### ISSUE TITLE
a leading line with a 'for' case was giving an IndentationError, despite there being nothing syntactically wrong with this. Recurrently attempting in spite of it caused this error.

### ISSUE THREAD

**Issue by nstac** [spyder-ide/spyder#21981]
### What steps will reproduce the problem?

```python
import string

str_String = string.punctuation

for str_Character in "+-=":
    str_String = str_String.replace(str_Character, "")

print(str_String)



^^^^^^
the above kept producing the error


    for str_Character in "+-=":
    ^
IndentationError: unexpected indent
```

despite there being no indent.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\nstac\Documents\WPy64-31220\python-3.12.2.amd64\Lib\site-packages\spyder\plugins\editor\panels\scrollflag.py", line 176, in paintEvent
    scale_factor = groove_rect.height() / self.get_scrollbar_value_height()
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
```

## Versions

* Spyder version: 5.5.0  (pip)
* Python version: 3.12.2 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.3.0 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
intervaltree >=3.0.2             :  3.0.2 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.20.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.3 (OK)
jsonschema >=3.2.0               :  4.19.2 (OK)
keyring >=17.0.0                 :  24.2.0 (OK)
nbconvert >=4.0                  :  7.10.0 (OK)
numpydoc >=0.6.0                 :  1.3 (OK)
paramiko >=2.4.0                 :  2.8.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.5 (OK)
pygments >=2.0                   :  2.16.1 (OK)
pylint >=2.5.0,<3.1              :  3.0.2 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.9.0,<1.10.0            :  1.9.0 (OK)
pylsp_black >=1.2.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.2.3 (OK)
qtconsole >=5.5.0,<5.6.0         :  5.5.1 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.1.0 (OK)
setuptools >=49.6.0              :  69.0.3 (OK)
sphinx >=0.6.6                   :  7.2.6 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.0 (OK)
textdistance >=4.2.0             :  4.5.0 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  2.2.0 (OK)
zmq >=22.1.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  3.0.7 (OK)
matplotlib >=3.0.0               :  3.8.2 (OK)
numpy >=1.7                      :  1.26.3 (OK)
pandas >=1.1.1                   :  2.2.0 (OK)
scipy >=0.17.0                   :  1.12.0 (OK)
sympy >=0.7.3                    :  1.12 (OK)
```

**Comment by ccordoba12** [comment]
Hey @nstac, thanks for reporting. Did you copy your code from a webpage? I'm asking that because sometimes webpages have weird, invisible characters that can affect code. So, a simple copy/paste could cause this issue.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
