### ISSUE TITLE
HiDPI + Wayland + Spyder 6: bad window size in preferences

### ISSUE THREAD

**Issue by Firestar-Reimu** [spyder-ide/spyder#21980]
![图片](https://github.com/spyder-ide/spyder/assets/65082432/879b5e8d-ff11-49ea-b783-c6a3eda38531)

You can see that the font of **Syntax Highlighting** is cut by the window, and the window for previewing is also too small

![图片](https://github.com/spyder-ide/spyder/assets/65082432/dba06ccd-354b-48f1-851b-3490849c14ed)

the line height can be adjusted by dragging the window border but the window of `Appearance` cannot be bigger

I have tested on `Screen Resolution` of `Normal/Enable Auto HiDPI/Manual Scaling`

**Comment by majneb** [comment]
> 
> In fact Spyder 5 looks worse, small icons on big icon boxes, the left menu of `preferences` is also bad

As a workaround (at least for spyder 5) you can try to run spyder like this : `QT_AUTO_SCREEN_SCALE_FACTOR=1 spyder`.
For me it solved the issue you described with spyder 5.

**Comment by ccordoba12** [comment]
Hey @Firestar-Reimu, thanks for reporting. Could you try @majneb workaround and let us if it works for you?

**Comment by Firestar-Reimu** [comment]
![image](https://github.com/user-attachments/assets/f97b3ffc-ce5a-476f-8008-2ea064cf2318)

OK on Spyder 6, the icons looks a lot bigger, but the preferences window looks better (although it fills the entire screen)

![image](https://github.com/user-attachments/assets/dbc092a1-d249-4f5e-8fe3-dc9771c978a1)

Notebook also seems fine:

![image](https://github.com/user-attachments/assets/3da4d39d-f743-4d2e-98db-8526a8c9e23b)

**Comment by Firestar-Reimu** [comment]
BUT after I turn it off and re-open spyder, I cannot start with `spyder` or it will stuck:

```
Could not find the Qt platform plugin "wayland" in ""
^CTraceback (most recent call last):
  File "/home/firestar/.miniconda/bin/spyder", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/firestar/.miniconda/lib/python3.12/site-packages/spyder/app/start.py", line 286, in main
    mainwindow.main(options, args)
  File "/home/firestar/.miniconda/lib/python3.12/site-packages/spyder/app/mainwindow.py", line 1364, in main
    app = create_application()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/firestar/.miniconda/lib/python3.12/site-packages/spyder/app/utils.py", line 298, in create_application
    app.set_font()
  File "/home/firestar/.miniconda/lib/python3.12/site-packages/spyder/utils/qthelpers.py", line 824, in set_font
    self.set_monospace_interface_font(app_font)
  File "/home/firestar/.miniconda/lib/python3.12/site-packages/spyder/utils/qthelpers.py", line 849, in set_monospace_interface_font
    plain_font.setPointSize(monospace_size)
KeyboardInterrupt
```

Only I start it with `QT_AUTO_SCREEN_SCALE_FACTOR=1 spyder` every time will it load swiftly

**Comment by ccordoba12** [comment]
Sorry for the late reply @Firestar-Reimu. You said:

> OK on Spyder 6, the icons looks a lot bigger, but the preferences window looks better (although it fills the entire screen)

That's the way we designed the interface, so there's no problem with that.

> BUT after I turn it off and re-open spyder, I cannot start with spyder or it will stuck

We'll try to fix that in a future version, but I think running `spyder --reset` in a terminal should solve that problem.
