### ISSUE TITLE
Intertnal Spyder problem

### ISSUE THREAD

**Issue by Elepfant** [spyder-ide/spyder#22019]
### What steps will reproduce the problem?

Openin Spyder (without Admin rights). Just a minute ago, Spyder worked fine.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\jupyter_client\manager.py", line 91, in wrapper
    self._ready.set_result(None)
asyncio.exceptions.InvalidStateError: invalid state

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Spyder\pkgs\qtconsole\manager.py", line 27, in poll
    super().poll()
  File "C:\Program Files\Spyder\pkgs\jupyter_client\restarter.py", line 143, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "C:\Program Files\Spyder\pkgs\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "C:\Program Files\Spyder\pkgs\jupyter_client\manager.py", line 596, in _async_restart_kernel
    await self._async_start_kernel(**self._launch_args)
  File "C:\Program Files\Spyder\pkgs\jupyter_client\manager.py", line 94, in wrapper
    self._ready.set_exception(e)
asyncio.exceptions.InvalidStateError: invalid state
```

## Versions

* Spyder version: 5.5.4  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.2.0 (OK)
cloudpickle >=0.5.0           :  3.0.0 (OK)
cookiecutter >=1.6.0          :  2.6.0 (OK)
diff_match_patch >=20181111   :  20230430 (OK)
intervaltree                  :  None (OK)
IPython >=8.12.2,<8.13.0      :  8.12.3 (OK)
jedi >=0.17.2,<0.20.0         :  0.19.1 (OK)
jellyfish >=0.7               :  1.0.3 (OK)
jsonschema >=3.2.0            :  4.21.1 (OK)
keyring >=17.0.0              :  25.1.0 (OK)
nbconvert >=4.0               :  7.16.3 (OK)
numpydoc >=0.6.0              :  1.7.0 (OK)
paramiko >=2.4.0              :  3.4.0 (OK)
parso >=0.7.0,<0.9.0          :  0.8.4 (OK)
pexpect >=4.4.0               :  4.9.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.8 (OK)
pygments >=2.0                :  2.17.2 (OK)
pylint >=3.1,<4               :  3.1.0 (OK)
pylint_venv >=3.0.2           :  3.0.3 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.11.0,<1.12.0        :  1.11.0 (OK)
pylsp_black >=2.0.0,<3.0.0    :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0     :  3.2.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0      :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0      :  5.5.1 (OK)
qtpy >=2.1.0                  :  2.4.1 (OK)
rtree >=0.9.7                 :  1.2.0 (OK)
setuptools >=49.6.0           :  69.2.0 (OK)
sphinx >=0.6.6                :  7.1.2 (OK)
spyder_kernels >=2.5.1,<2.6.0 :  2.5.1 (OK)
textdistance >=4.2.0          :  4.6.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  4.0.0 (OK)
zmq >=24.0.0                  :  25.1.2 (OK)

# Optional:
cython >=0.21                 :  3.0.10 (OK)
matplotlib >=3.0.0            :  3.7.5 (OK)
numpy >=1.7                   :  1.24.4 (OK)
pandas >=1.1.1                :  2.0.3 (OK)
scipy >=0.17.0                :  1.10.1 (OK)
sympy >=0.7.3                 :  1.12 (OK)
```

### Environment

<details><summary>Environment</summary>

```
Package                       Version
----------------------------- --------------
alabaster                     0.7.13
arrow                         1.3.0
astroid                       3.1.0
asttokens                     2.4.1
attrs                         23.2.0
autopep8                      2.0.4
Babel                         2.14.0
backcall                      0.2.0
backports.tarfile             1.0.0
beautifulsoup4                4.12.3
binaryornot                   0.4.4
black                         24.3.0
bleach                        6.1.0
certifi                       2024.2.2
cffi                          1.16.0
chardet                       5.2.0
charset-normalizer            3.3.2
click                         8.1.7
cloudpickle                   3.0.0
colorama                      0.4.6
comm                          0.2.2
contourpy                     1.1.1
cookiecutter                  2.6.0
cryptography                  42.0.5
cycler                        0.12.1
Cython                        3.0.10
debugpy                       1.8.1
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20230430
dill                          0.3.8
docstring-to-markdown         0.15
docutils                      0.20.1
et-xmlfile                    1.1.0
executing                     2.0.1
fastjsonschema                2.19.1
flake8                        7.0.0
fonttools                     4.51.0
idna                          3.6
imagesize                     1.4.1
importlib_metadata            7.1.0
importlib_resources           6.4.0
inflection                    0.5.1
ipykernel                     6.29.4
ipython                       8.12.3
isort                         5.13.2
jaraco.classes                3.4.0
jaraco.context                5.3.0
jaraco.functools              4.0.0
jedi                          0.19.1
jellyfish                     1.0.3
Jinja2                        3.1.3
joblib                        1.4.0
jsonschema                    4.21.1
jsonschema-specifications     2023.12.1
jupyter_client                8.6.1
jupyter_core                  5.7.2
jupyterlab_pygments           0.3.0
keyring                       25.1.0
kiwisolver                    1.4.5
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
matplotlib                    3.7.5
matplotlib-inline             0.1.6
mccabe                        0.7.0
mdurl                         0.1.2
mistune                       3.0.2
more-itertools                10.2.0
mpmath                        1.3.0
mypy-extensions               1.0.0
nbclient                      0.10.0
nbconvert                     7.16.3
nbformat                      5.10.4
nest-asyncio                  1.6.0
numpy                         1.24.4
numpydoc                      1.7.0
opencv-python                 4.9.0.80
openpyxl                      3.1.2
packaging                     24.0
pandas                        2.0.3
pandocfilters                 1.5.1
paramiko                      3.4.0
parso                         0.8.4
pathspec                      0.12.1
pexpect                       4.9.0
pickleshare                   0.7.5
pillow                        10.3.0
pip                           24.0
pkgutil_resolve_name          1.3.10
platformdirs                  4.2.0
pluggy                        1.4.0
prompt-toolkit                3.0.43
ptyprocess                    0.7.0
pure-eval                     0.2.2
pycodestyle                   2.11.1
pycparser                     2.22
pydocstyle                    6.3.0
pyflakes                      3.2.0
Pygments                      2.17.2
pylint                        3.1.0
pylint-venv                   3.0.3
pyls-spyder                   0.4.0
pyparsing                     3.1.2
PyQt5                         5.15.10
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.13.0
PyQtWebEngine                 5.15.6
PyQtWebEngine-Qt5             5.15.2
python-dateutil               2.9.0.post0
python-lsp-black              2.0.0
python-lsp-jsonrpc            1.1.2
python-lsp-server             1.11.0
pytoolconfig                  1.3.1
pytz                          2024.1
pywin32                       306
pywin32-ctypes                0.2.2
pyxdg                         0.28
PyYAML                        6.0.1
pyzmq                         25.1.2
QDarkStyle                    3.2.3
qstylizer                     0.2.2
QtAwesome                     1.3.1
qtconsole                     5.5.1
QtPy                          2.4.1
referencing                   0.34.0
requests                      2.31.0
rich                          13.7.1
rope                          1.13.0
rpds-py                       0.18.0
scikit-learn                  1.4.2
scipy                         1.10.1
setuptools                    69.2.0
six                           1.16.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.5
Sphinx                        7.1.2
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.5.4
spyder-kernels                2.5.1
stack-data                    0.6.3
sympy                         1.12
tabulate                      0.9.0
text-unidecode                1.3
textdistance                  4.6.1
threadpoolctl                 3.4.0
three-merge                   0.1.1
tinycss2                      1.2.1
tomli                         2.0.1
tomlkit                       0.12.4
tornado                       6.4
traitlets                     5.14.2
types-python-dateutil         2.9.0.20240316
typing_extensions             4.11.0
tzdata                        2024.1
ujson                         5.9.0
urllib3                       2.2.1
watchdog                      4.0.0
wcwidth                       0.2.13
webencodings                  0.5.1
whatthepatch                  1.0.5
wheel                         0.43.0
yapf                          0.40.2
zipp                          3.18.1

```
</details>

**Comment by ccordoba12** [comment]
Closing due to lack of response.
