### ISSUE TITLE
Spyder has encountered an internal problem

### ISSUE THREAD

**Issue by vw511** [spyder-ide/spyder#22087]
### What steps will reproduce the problem?

Issue reporter poped up, saying "Spyder has encountered an internal problem". Not sure what's going on. The window would keep popping up if I keep hitting "Close".

### Traceback
```python-traceback
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "C:\Users\VWANG\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\site-packages\jupyter_client\threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\site-packages\jupyter_client\threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "C:\Users\VWANG\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 634, in _handle_events
    self._handle_recv()
  File "C:\Users\VWANG\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 663, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\VWANG\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\site-packages\jupyter_client\threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\site-packages\jupyter_client\threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x0000024F88B091F0>)
Traceback (most recent call last):
  File "C:\Users\VWANG\AppData\Roaming\Python\Python39\site-packages\tornado\ioloop.py", line 750, in _run_callback
    ret = callback()
  File "C:\Users\VWANG\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 718, in <lambda>
    self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
  File "C:\Users\VWANG\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 634, in _handle_events
    self._handle_recv()
  File "C:\Users\VWANG\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 663, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\VWANG\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\site-packages\jupyter_client\threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\site-packages\jupyter_client\threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "C:\Users\VWANG\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\site-packages\jupyter_client\threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\site-packages\jupyter_client\threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "C:\Users\VWANG\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 634, in _handle_events
    self._handle_recv()
  File "C:\Users\VWANG\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 663, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\VWANG\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\site-packages\jupyter_client\threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\site-packages\jupyter_client\threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x0000024F88AF03A0>)
Traceback (most recent call last):
  File "C:\Users\VWANG\AppData\Roaming\Python\Python39\site-packages\tornado\ioloop.py", line 750, in _run_callback
    ret = callback()
  File "C:\Users\VWANG\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 718, in <lambda>
    self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
  File "C:\Users\VWANG\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 634, in _handle_events
    self._handle_recv()
  File "C:\Users\VWANG\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 663, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\VWANG\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\site-packages\jupyter_client\threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\VWANG\.conda\envs\pyqlib-dev\lib\site-packages\jupyter_client\threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
```

## Versions

* Spyder version: 5.2.2 
* Python version: 3.9.13
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.1.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.2 (OK)
qtawesome >=1.0.2             :  1.3.0 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.4.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  50.3.2 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  25.1.2 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.23.5 (OK)
pandas >=1.1.1                :  1.4.4 (OK)
scipy >=0.17.0                :  1.8.1 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @vw511, thanks for reporting. It seems you're mixing packages from two different Python installations, one located in

    C:\Users\VWANG\AppData\Roaming\Python\Python39\

and the other in

    C:\Users\VWANG\.conda\envs\pyqlib-dev\

If you want to use Spyder through conda, please remove the first directory. Otherwise, you need to uninstall Anaconda.

Let us know if that helps you to solve this problem.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
