### ISSUE TITLE
kernel restart error

### ISSUE THREAD

**Issue by rdfgdfgdfg** [spyder-ide/spyder#22094]
### What steps will reproduce the problem?

Spyder said kernel should < 2.5 so I uninstall spyder_kernel and reinstall it by pip. But pip said `spyder 5.5.1 requires spyder-kernels<2.6.0,>=2.5.0, but you have spyder-kernels 2.4.4 which is incompatible.`. So I want to reinstall it again. When I run the command,it suddenly occured me that maybe the environment is right and I don't need to reinstall it. When prompt ask `Proceed (Y/n)?`,I don't answer and restart the spyder kernel, then something error. About 1 hour earlier,spyder checked for update but I ignore it, so the spyder may be old.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 772, in _restart_thread_main
    self.shellwidget.kernel_manager.restart_kernel(
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\utils.py", line 30, in wrapped
    raise e
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\ProgramData\anaconda3\Lib\asyncio\tasks.py", line 267, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\manager.py", line 541, in _async_restart_kernel
    await ensure_async(self.shutdown_kernel(now=now, restart=True))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\utils.py", line 30, in wrapped
    raise e
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\ProgramData\anaconda3\Lib\asyncio\tasks.py", line 267, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\manager.py", line 90, in wrapper
    raise e
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\manager.py", line 82, in wrapper
    out = await method(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\manager.py", line 500, in _async_shutdown_kernel
    await ensure_async(self.request_shutdown(restart=restart))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\utils.py", line 30, in wrapped
    raise e
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\ProgramData\anaconda3\Lib\asyncio\tasks.py", line 267, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\manager.py", line 405, in _async_request_shutdown
    self._connect_control_socket()
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\manager.py", line 323, in _connect_control_socket
    self._control_socket = self._create_connected_socket("control")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_client\connect.py", line 658, in _create_connected_socket
    sock = self.context.socket(socket_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\zmq\sugar\context.py", line 258, in socket
    raise ZMQError(Errno.ENOTSUP)
zmq.error.ZMQError: Not supported
```

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.11.5 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  1.7.3 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.15.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  1.0.1 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  6.5.4 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.2.0 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.0.0 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.4 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  23.2.0 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.7.2 (OK)
numpy >=1.7                                      :  1.24.3 (OK)
pandas >=1.1.1                                   :  2.0.3 (OK)
scipy >=0.17.0                                   :  1.11.1 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at C:\ProgramData\anaconda3\envs\web:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12             pyhd3eb1b0_0    defaults
arrow                     1.2.3           py310haa95532_1    defaults
astroid                   2.14.2          py310haa95532_0    defaults
asttokens                 2.0.5              pyhd3eb1b0_0    defaults
atomicwrites              1.4.0                      py_0    defaults
attrs                     23.1.0          py310haa95532_0    defaults
autopep8                  2.0.4              pyhd3eb1b0_0    defaults
babel                     2.11.0          py310haa95532_0    defaults
bcrypt                    3.2.0           py310h2bbff1b_1    defaults
beautifulsoup4            4.12.3                   pypi_0    pypi
binaryornot               0.4.4              pyhd3eb1b0_1    defaults
black                     24.3.0          py310haa95532_0    defaults
bleach                    4.1.0              pyhd3eb1b0_0    defaults
brotli-python             1.0.9           py310hd77b12b_8    defaults
bzip2                     1.0.8                h2bbff1b_6    defaults
ca-certificates           2024.3.11            haa95532_0    defaults
certifi                   2024.2.2        py310haa95532_0    defaults
cffi                      1.16.0          py310h2bbff1b_1    defaults
chardet                   4.0.0           py310haa95532_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.1.7           py310haa95532_0    defaults
cloudpickle               2.2.1           py310haa95532_0    defaults
colorama                  0.4.6           py310haa95532_0    defaults
coloredlogs               15.0.1                   pypi_0    pypi
comm                      0.2.1           py310haa95532_0    defaults
cookiecutter              2.6.0           py310haa95532_0    defaults
cryptography              41.0.3          py310h3438e0d_0    defaults
ddddocr                   1.5.3                    pypi_0    pypi
debugpy                   1.6.7           py310hd77b12b_0    defaults
decorator                 5.1.1              pyhd3eb1b0_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
diff-match-patch          20200713           pyhd3eb1b0_0    defaults
dill                      0.3.8           py310haa95532_0    defaults
docstring-to-markdown     0.11            py310haa95532_0    defaults
docutils                  0.18.1          py310haa95532_3    defaults
exceptiongroup            1.2.0           py310haa95532_0    defaults
executing                 0.8.3              pyhd3eb1b0_0    defaults
flake8                    7.0.0           py310haa95532_0    defaults
flatbuffers               24.3.25                  pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
icu                       73.1                 h6c2663c_0    defaults
idna                      3.7             py310haa95532_0    defaults
imagesize                 1.4.1           py310haa95532_0    defaults
importlib-metadata        7.0.1           py310haa95532_0    defaults
importlib_metadata        7.0.1                hd3eb1b0_0    defaults
inflection                0.5.1           py310haa95532_0    defaults
intervaltree              3.1.0              pyhd3eb1b0_0    defaults
ipykernel                 6.28.0          py310haa95532_0    defaults
ipython                   8.20.0          py310haa95532_0    defaults
isort                     5.9.3              pyhd3eb1b0_0    defaults
jaraco.classes            3.2.1              pyhd3eb1b0_0    defaults
jedi                      0.18.1          py310haa95532_1    defaults
jellyfish                 1.0.1           py310h36a85e1_0    defaults
jinja2                    3.1.3           py310haa95532_0    defaults
jpeg                      9e                   h2bbff1b_1    defaults
jsonschema                4.19.2          py310haa95532_0    defaults
jsonschema-specifications 2023.7.1        py310haa95532_0    defaults
jupyter_client            8.6.0           py310haa95532_0    defaults
jupyter_core              5.5.0           py310haa95532_0    defaults
jupyterlab_pygments       0.2.2           py310haa95532_0    defaults
keyring                   24.3.1          py310haa95532_0    defaults
krb5                      1.20.1               h5b6d351_1    defaults
lazy-object-proxy         1.10.0          py310h2bbff1b_0    defaults
libclang                  14.0.6          default_hb5a9fac_1    defaults
libclang13                14.0.6          default_h8e68704_1    defaults
libffi                    3.4.4                hd77b12b_1    defaults
libpng                    1.6.39               h8cc25b3_0    defaults
libpq                     12.15                hb652d5d_1    defaults
libsodium                 1.0.18               h62dcd97_0    defaults
libspatialindex           1.9.3                h6c2663c_0    defaults
lxml                      5.2.2                    pypi_0    pypi
lz4-c                     1.9.4                h2bbff1b_1    defaults
markdown-it-py            2.2.0           py310haa95532_1    defaults
markupsafe                2.1.3           py310h2bbff1b_0    defaults
matplotlib-inline         0.1.6           py310haa95532_0    defaults
mccabe                    0.7.0              pyhd3eb1b0_0    defaults
mdurl                     0.1.0           py310haa95532_0    defaults
mistune                   2.0.4           py310haa95532_0    defaults
more-itertools            10.1.0          py310haa95532_0    defaults
mpmath                    1.3.0                    pypi_0    pypi
mypy_extensions           1.0.0           py310haa95532_0    defaults
nbclient                  0.8.0           py310haa95532_0    defaults
nbconvert                 7.10.0          py310haa95532_0    defaults
nbformat                  5.9.2           py310haa95532_0    defaults
nest-asyncio              1.6.0           py310haa95532_0    defaults
numpy                     1.26.4                   pypi_0    pypi
numpydoc                  1.5.0           py310haa95532_0    defaults
onnxruntime               1.17.3                   pypi_0    pypi
opencv-python-headless    4.9.0.80                 pypi_0    pypi
openssl                   1.1.1w               h2bbff1b_0    defaults
packaging                 24.0                     pypi_0    pypi
pandocfilters             1.5.0              pyhd3eb1b0_0    defaults
paramiko                  2.8.1              pyhd3eb1b0_0    defaults
parso                     0.8.3              pyhd3eb1b0_0    defaults
pathspec                  0.10.3          py310haa95532_0    defaults
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    10.3.0                   pypi_0    pypi
pip                       24.0            py310haa95532_0    defaults
platformdirs              3.10.0          py310haa95532_0    defaults
pluggy                    1.0.0           py310haa95532_1    defaults
ply                       3.11            py310haa95532_0    defaults
prompt-toolkit            3.0.43          py310haa95532_0    defaults
prompt_toolkit            3.0.43               hd3eb1b0_0    defaults
protobuf                  5.26.1                   pypi_0    pypi
psutil                    5.9.0           py310h2bbff1b_0    defaults
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
pure_eval                 0.2.2              pyhd3eb1b0_0    defaults
pycodestyle               2.11.1          py310haa95532_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pydocstyle                6.3.0           py310haa95532_0    defaults
pyflakes                  3.2.0           py310haa95532_0    defaults
pygments                  2.15.1          py310haa95532_1    defaults
pylint                    2.16.2          py310haa95532_0    defaults
pylint-venv               3.0.3           py310haa95532_0    defaults
pyls-spyder               0.4.0              pyhd3eb1b0_0    defaults
pynacl                    1.5.0           py310h8cc25b3_0    defaults
pyqt                      5.15.10         py310hd77b12b_0    defaults
pyqt5-sip                 12.13.0         py310h2bbff1b_0    defaults
pyqtwebengine             5.15.10         py310hd77b12b_0    defaults
pyreadline3               3.4.1                    pypi_0    pypi
pysocks                   1.7.1           py310haa95532_0    defaults
python                    3.10.0               h96c0403_3    defaults
python-dateutil           2.9.0post0      py310haa95532_0    defaults
python-fastjsonschema     2.16.2          py310haa95532_0    defaults
python-lsp-black          2.0.0           py310haa95532_0    defaults
python-lsp-jsonrpc        1.1.2              pyhd3eb1b0_0    defaults
python-lsp-server         1.10.0          py310haa95532_0    defaults
python-slugify            5.0.2              pyhd3eb1b0_0    defaults
pytoolconfig              1.2.6           py310haa95532_0    defaults
pytz                      2024.1          py310haa95532_0    defaults
pywin32                   305             py310h2bbff1b_0    defaults
pywin32-ctypes            0.2.2           py310haa95532_0    defaults
pyyaml                    6.0.1           py310h2bbff1b_0    defaults
pyzmq                     25.1.2          py310hd77b12b_0    defaults
qdarkstyle                3.2.3              pyhd3eb1b0_0    defaults
qstylizer                 0.2.2                    pypi_0    pypi
qt-main                   5.15.2              he2df7e6_10    defaults
qt-webengine              5.15.9               h5bd16bc_7    defaults
qtawesome                 1.2.2                    pypi_0    pypi
qtconsole                 5.5.1           py310haa95532_0    defaults
qtpy                      2.4.1           py310haa95532_0    defaults
referencing               0.30.2          py310haa95532_0    defaults
requests                  2.31.0          py310haa95532_1    defaults
rich                      13.3.5          py310haa95532_0    defaults
rope                      1.12.0          py310haa95532_0    defaults
rpds-py                   0.10.6          py310h062c2fa_0    defaults
rtree                     1.0.1           py310h2eaa2aa_0    defaults
selenium                  3.141.0         py310h2bbff1b_1000    defaults
setuptools                69.5.1          py310haa95532_0    defaults
sip                       6.7.12          py310hd77b12b_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
snowballstemmer           2.2.0              pyhd3eb1b0_0    defaults
sortedcontainers          2.4.0              pyhd3eb1b0_0    defaults
soupsieve                 2.5             py310haa95532_0    defaults
sphinx                    5.0.2           py310haa95532_0    defaults
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0    defaults
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0    defaults
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0    defaults
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0    defaults
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0    defaults
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0    defaults
spyder                    5.5.1           py310haa95532_0    defaults
spyder-kernels            2.4.4                    pypi_0    pypi
sqlite                    3.45.3               h2bbff1b_0    defaults
stack_data                0.2.0              pyhd3eb1b0_0    defaults
sympy                     1.12                     pypi_0    pypi
text-unidecode            1.3                pyhd3eb1b0_0    defaults
textdistance              4.2.1              pyhd3eb1b0_0    defaults
three-merge               0.1.1              pyhd3eb1b0_0    defaults
tinycss2                  1.2.1           py310haa95532_0    defaults
tk                        8.6.14               h0416ee5_0    defaults
tomli                     2.0.1           py310haa95532_0    defaults
tomlkit                   0.11.1          py310haa95532_0    defaults
tornado                   6.3.3           py310h2bbff1b_0    defaults
traitlets                 5.7.1           py310haa95532_0    defaults
typing-extensions         4.11.0          py310haa95532_0    defaults
typing_extensions         4.11.0          py310haa95532_0    defaults
tzdata                    2024a                h04d1e81_0    defaults
ujson                     5.4.0           py310hd77b12b_0    defaults
unidecode                 1.2.0              pyhd3eb1b0_0    defaults
urllib3                   1.26.2                   pypi_0    pypi
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
watchdog                  2.1.6           py310haa95532_0    defaults
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
webencodings              0.5.1           py310haa95532_1    defaults
whatthepatch              1.0.2           py310haa95532_0    defaults
wheel                     0.43.0          py310haa95532_0    defaults
win_inet_pton             1.1.0           py310haa95532_0    defaults
wrapt                     1.14.1          py310h2bbff1b_0    defaults
xz                        5.4.6                h8cc25b3_1    defaults
yaml                      0.2.5                he774522_0    defaults
yapf                      0.40.2          py310haa95532_0    defaults
zeromq                    4.3.5                hd77b12b_0    defaults
zipp                      3.17.0          py310haa95532_0    defaults
zlib                      1.2.13               h8cc25b3_1    defaults
zstd                      1.5.5                hd43e919_2    defaults

```
</details>

**Comment by ccordoba12** [comment]
Hey @rdfgdfgdfg, thanks for reporting. Quick question for you: did you install Spyder-kernels with `pip` at the end?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
