### ISSUE TITLE
Failer kernel restart

### ISSUE THREAD

**Issue by alkhwarizmi** [spyder-ide/spyder#22115]
### What steps will reproduce the problem?

estarting kernel from the consolle windows after installation of spyder-kernels for Python 3.10

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\spyder-env\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 772, in _restart_thread_main
    self.shellwidget.kernel_manager.restart_kernel(
  File "C:\Anaconda3\envs\spyder-env\Lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\envs\spyder-env\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Anaconda3\envs\spyder-env\Lib\site-packages\jupyter_client\manager.py", line 548, in _async_restart_kernel
    await self._async_shutdown_kernel(now=now, restart=True)
  File "C:\Anaconda3\envs\spyder-env\Lib\site-packages\jupyter_client\manager.py", line 93, in wrapper
    raise e
  File "C:\Anaconda3\envs\spyder-env\Lib\site-packages\jupyter_client\manager.py", line 85, in wrapper
    out = await method(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\envs\spyder-env\Lib\site-packages\jupyter_client\manager.py", line 506, in _async_shutdown_kernel
    await self._async_request_shutdown(restart=restart)
  File "C:\Anaconda3\envs\spyder-env\Lib\site-packages\jupyter_client\manager.py", line 411, in _async_request_shutdown
    self._connect_control_socket()
  File "C:\Anaconda3\envs\spyder-env\Lib\site-packages\jupyter_client\manager.py", line 329, in _connect_control_socket
    self._control_socket = self._create_connected_socket("control")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\envs\spyder-env\Lib\site-packages\jupyter_client\connect.py", line 644, in _create_connected_socket
    sock = self.context.socket(socket_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\envs\spyder-env\Lib\site-packages\zmq\sugar\context.py", line 359, in socket
    raise ZMQError(Errno.ENOTSUP)
zmq.error.ZMQError: Not supported
```

## Versions

* Spyder version: 5.5.4  (conda)
* Python version: 3.11.3 64-bit
* Qt version: 5.15.6
* PyQt5 version: 5.15.7
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.1.0 (OK)
cloudpickle >=0.5.0              :  2.2.1 (OK)
cookiecutter >=1.6.0             :  2.1.1 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.14.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.18.2 (OK)
jellyfish >=0.7                  :  0.9.0 (OK)
jsonschema >=3.2.0               :  4.17.3 (OK)
keyring >=17.0.0                 :  23.13.1 (OK)
nbconvert >=4.0                  :  7.4.0 (OK)
numpydoc >=0.6.0                 :  1.5.0 (OK)
paramiko >=2.4.0                 :  3.2.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.5 (OK)
pygments >=2.0                   :  2.15.1 (OK)
pylint >=3.1,<4                  :  3.2.2 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.11.0,<1.12.0           :  1.11.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.1 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.0.1 (OK)
setuptools >=49.6.0              :  67.7.2 (OK)
sphinx >=0.6.6                   :  7.0.1 (OK)
spyder_kernels >=2.5.1,<2.6.0    :  2.5.1 (OK)
textdistance >=4.2.0             :  4.5.0 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  3.0.0 (OK)
zmq >=24.0.0                     :  25.1.0 (OK)

# Optional:
cython >=0.21                    :  0.29.35 (OK)
matplotlib >=3.0.0               :  3.7.1 (OK)
numpy >=1.7                      :  1.24.3 (OK)
pandas >=1.1.1                   :  2.0.2 (OK)
scipy >=0.17.0                   :  1.10.1 (OK)
sympy >=0.7.3                    :  1.12 (OK)
```

**Comment by ccordoba12** [comment]
Hey @alkhwarizmi, thanks for reporting. Please close Spyder, restart your computer and try again. Perhaps that will solve your problem, but let us know if it does.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
