### ISSUE TITLE
not connecting to kernel

### ISSUE THREAD

**Issue by kpondaugusto** [spyder-ide/spyder#22145]
### What steps will reproduce the problem?

I opened spyder and it won't connect to the kernel

### Traceback
```python-traceback
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/jupyter_client/threaded.py", line 121, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/jupyter_client/threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 634, in _handle_events
    self._handle_recv()
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 663, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/jupyter_client/threaded.py", line 121, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/jupyter_client/threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback BaseAsyncIOLoop._handle_events(100, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(100, 1)>
Traceback (most recent call last):
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 192, in _handle_events
    handler_func(fileobj, events)
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 634, in _handle_events
    self._handle_recv()
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 663, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/jupyter_client/threaded.py", line 121, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/jupyter_client/threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/jupyter_client/threaded.py", line 121, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/jupyter_client/threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 634, in _handle_events
    self._handle_recv()
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 663, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/jupyter_client/threaded.py", line 121, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/jupyter_client/threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback BaseAsyncIOLoop._handle_events(98, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(98, 1)>
Traceback (most recent call last):
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 192, in _handle_events
    handler_func(fileobj, events)
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 634, in _handle_events
    self._handle_recv()
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 663, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/jupyter_client/threaded.py", line 121, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/kierapond/opt/miniconda3/lib/python3.9/site-packages/jupyter_client/threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
```

## Versions

* Spyder version: 4.2.5 
* Python version: 3.9.7
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Darwin 23.4.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7       :  0.3.0 (OK)
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  2.2.1 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  8.15.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  4.19.2 (OK)
keyring >=17.0.0                :  24.3.1 (OK)
nbconvert >=4.0                 :  7.10.0 (OK)
numpydoc >=0.6.0                :  1.5.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.9.0 (OK)
pygments >=2.0                  :  2.15.1 (OK)
pylint >=1.0                    :  2.16.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.2.2 (OK)
qtconsole >=5.0.3               :  5.5.1 (OK)
qtpy >=1.5.0                    :  2.4.1 (OK)
rtree >=0.8.3                   :  1.0.1 (OK)
setuptools >=39.0.0             :  69.5.1 (OK)
sphinx >=0.6.6                  :  5.0.2 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  25.1.2 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.5.1 (OK)
numpy >=1.7                     :  1.24.3 (OK)
pandas >=1.1.1                  :  2.2.2 (OK)
scipy >=0.17.0                  :  1.9.3 (OK)
sympy >=0.7.3                   :  1.9 (OK)

# Spyder plugins:
spyder_terminal                 :  0.5.0 (OK)
```

**Comment by ccordoba12** [comment]
Hey @kpondaugusto, thanks for reporting. This problem is fixed in our latest version available in Anaconda (5.5.1). Please update by closing Spyder, opening a terminal and running there

    conda install spyder=5.5.1
