### ISSUE TITLE
Cannot open spyder on Anaconda when using Mac

### ISSUE THREAD

**Issue by booc24** [spyder-ide/spyder#22144]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```
/opt/anaconda3/bin/pythonw: line 3: 51257 Segmentation fault: 11  /opt/anaconda3/python.app/Contents/MacOS/python "$@"

**Comment by booc24** [comment]
spyder-env) CHANGs-MacBook-Pro:~ changbowen$ spyder                            
/opt/anaconda3/envs/spyder-env/bin/pythonw: line 3: 50508 Segmentation fault: 11  /opt/anaconda3/envs/spyder-env/python.app/Contents/MacOS/python "$@"

**Comment by booc24** [comment]
Already tried everything

**Comment by ccordoba12** [comment]
Hey @booc24, thanks for reporting. Please try this to see if it helps:

    conda install -f python.app

Let us know if that solves your problem.

**Comment by peter930736** [comment]
There is still a problem after installing python.app
❯ spyder
/opt/anaconda3/envs/env1/bin/pythonw: line 3: 29705 Segmentation fault: 11  /opt/anaconda3/envs/env1/python.app/Contents/MacOS/python "$@"

**Comment by ccordoba12** [comment]
Then you can try to run

    conda remove --force python.app

and after that

    conda install python.app

to see if that solves the problem.

**Comment by Mitternacht** [comment]
I have the same issue. Brand new device (MacBook Pro M3 Max with the latest MacOS) with a freshly installed Anaconda Distro (today, 28th June 2024). The previously suggested solutions have not resolved the issue for me. The only thing that works is to create a new environment with Spyder 5.4.3.

**Comment by booc24** [comment]
Done

**Comment by ccordoba12** [comment]
@mrclary, could you check this in your Mac? For that, please download the latest Anaconda and check if Spyder works for you in your computer after installing it.

**Comment by mrclary** [comment]
I gather from the above comments:
* macOS arm64 and/or x86-64 platforms
* Anaconda installed for all users (i.e. `/opt/anaconda3`)
* Dedicated Spyder environment (i.e. `envs/env1`, `envs/spyder-env`)
* Root environment (i.e. `/opt/anaconda3/bin`)
* Spyder 5.5.1

Has anyone tried the latest version, Spyder 5.5.5?

I'll poke around and report back.

**Comment by mrclary** [comment]
Okay, this issue only affects arm64 and `python.app=3` (though I have not tested `python.app=2`).

* the main channel only has `python.app` versions 2 and 3. Version 3 is what ships with Anaconda and is installed when creating additional environments for Spyder. Version 2 is not available for Python 3.12, only 3.8, 3.9, and 3.11.
* the conda-forge channel only has `python.app` up to version 1.4, but this works.

I recommend creating a dedicated Spyder environment using the conda-forge channel:
```
(base) >> conda create -n spy-env -c conda-forge --override-channels python=3.12 spyder=5.5.5
```
This will install Python 3.12 and Spyder 5.5.5, but you can specify whichever Python or Spyder version you like by modifying the command accordingly. `python.app=1.4` from conda-forge will be installed and Spyder should launch successfully.

I _do not_ recommend installing `python.app=1.4` into your Anaconda base environment or other existing environments that are created with packages from the main channel. Doing so will cause Python 3.12 to be reinstalled from the conda-forge channel and result in a mixed channel environment which may cause other issues.

**Comment by ccordoba12** [comment]
> Okay, this issue only affects arm64 and python.app=3 (though I have not tested python.app=2)

Thanks for checking this @mrclary! So `python-app=2` works well for Python 3.8 to 3.11 in M1 Macs?

**Comment by mrclary** [comment]
Spyder=5.5.1 + Python=3.9.19 + python.app=2 on M1 works fine.
Spyder=5.5.1 + Python=3.11.9 + python.app=2 on M1 does not work:
```
Traceback (most recent call last):
  File "/Users/ryan/.conda/envs/spy551_py311_defaults/bin/spyder", line 7, in <module>
    from spyder.app.start import main
  File "/Users/ryan/.conda/envs/spy551_py311_defaults/lib/python3.11/site-packages/spyder/app/start.py", line 28, in <module>
    import random
  File "/Users/ryan/.conda/envs/spy551_py311_defaults/lib/python3.11/random.py", line 49, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: dlopen(/Users/ryan/.conda/envs/spy551_py311_defaults/lib/python3.11/lib-dynload/math.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '__PyModule_Add'
```
Though I don't think this has anything to do with python.app=2. It appears something may be wrong with the python 3.11.9 build from the defaults channel.

**Comment by ccordoba12** [comment]
@mrclary, and are there also startup errors with Python 3.12 from the defaults channel?

**Comment by mrclary** [comment]
> @mrclary, and are there also startup errors with Python 3.12 from the defaults channel?

Yes, due to `python.app=3`. This is the condition for the original post.

**Comment by VanniPham** [comment]
> @ccordoba12 I have the same issue. Brand new device (MacBook Pro M3 Max with the latest MacOS) with a freshly installed Anaconda Distro (today, 28th June 2024). The previously suggested solutions have not resolved the issue for me. The only thing that works is to create a new environment with Spyder 5.4.3, instead of 5.5.1.

This actually works for me. I'm using a Mac M1. Thank you!

**Comment by rswitt** [comment]
@ccordoba12 , @mrclary ,

I've discussed some issues with @ccordoba12 previously, I teach a course on computational methods using Spyder every Fall and Spring semester.  I currently have 53 students and 5-10 of them were encountering this issue, all on Arm based Macs, as @mrclary  identified.  I tried several workarounds, but @mrclary's suggestion of creating a new environment from conda-forge seems to have worked on at least 1 student system:

`(base) >> conda create -n spy-env -c conda-forge --override-channels python=3.12 spyder=5.5.6`

I will be announcing this to the class as a possible solution this evening.  If you'd like, I will report back on the success rate.

With @cbouss reporting that the origin of the issue may be resolved it may be difficult to ascertain what fix works, but hopefully it'll be fixed one way or the other!

**Comment by ccordoba12** [comment]
> Could you try updating python.app to the latest (conda install python.app) and verify whether the issue starting spyder is resolved?

Thanks for your help @cbouss!

@mrclary, could you check if the new `python.app` fixes the problem?

@rswitt, sorry for the late reply but we were quite busy preparing everything to release Spyder 6 during the last couple of weeks. But even if we had time to address this, it was really out of our hands, as the solution had to come directly from Anaconda (and it eventually did thanks to @cbouss).

**Comment by rswitt** [comment]
No issues @ccordoba12 , at least @mrclary id'd the issue and provided a solution!  It seems like every semester there's a new completely unrelated issue that crops up ;-).

**Comment by mrclary** [comment]
> > Could you try updating python.app to the latest (conda install python.app) and verify whether the issue starting spyder is resolved?

```
conda create -n spy551 -c defaults --override-channels python=3.11 spyder=5.5.1
conda run --live-stream -n spy551 spyder
```
This now works for me.
```
* Spyder version: 5.5.1  (conda)
* Python version: 3.11.9 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: macOS-14.6.1-arm64-arm-64bit
* python.app: 3=py311h80987f9_1
```
So updating `python.app` (notice the `*_1` build) in any Anaconda environment that uses the defaults channel should resolve the issue.

**Comment by mrclary** [comment]
Thanks, @cbouss!
