### ISSUE TITLE
New console not opening

### ISSUE THREAD

**Issue by rayyankhan1234567890** [spyder-ide/spyder#22159]
### What steps will reproduce the problem?

Not sure. It fails to open a new console. This has happened after using Spyder for a while. 

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\rayya\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1478, in create_new_client
  File "C:\Users\rayya\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 163, in __init__
  File "C:\Users\rayya\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 251, in _create_loading_page
AttributeError: 'NoneType' object has no attribute 'replace'
```

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.11.5 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  1.7.3 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.15.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  1.0.1 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  6.5.4 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.2.0 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.0.0 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.4 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  23.2.0 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.7.2 (OK)
numpy >=1.7                                      :  1.24.3 (OK)
pandas >=1.1.1                                   :  2.0.3 (OK)
scipy >=0.17.0                                   :  1.11.1 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at C:\Users\rayya\anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2023.09             py311_mkl_1  
abseil-cpp                20211102.0           hd77b12b_0  
aiohttp                   3.9.5                    pypi_0    pypi
aioitertools              0.7.1              pyhd3eb1b0_0  
aiosignal                 1.2.0              pyhd3eb1b0_0  
alabaster                 0.7.12             pyhd3eb1b0_0  
anaconda-anon-usage       0.4.2           py311hfc23b7f_0  
anaconda-catalogs         0.2.0           py311haa95532_0  
anaconda-client           1.12.1          py311haa95532_0  
anaconda-cloud-auth       0.1.3           py311haa95532_0  
anaconda-navigator        2.5.0           py311haa95532_0  
anaconda-project          0.11.1          py311haa95532_0  
anyio                     4.2.0                    pypi_0    pypi
aom                       3.6.0                hd77b12b_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0          py311h2bbff1b_0  
arrow                     1.2.3           py311haa95532_1  
astroid                   2.14.2          py311haa95532_0  
astropy-iers-data         0.2024.6.3.0.31.14          pypi_0    pypi
asttokens                 2.0.5              pyhd3eb1b0_0  
async-lru                 2.0.4                    pypi_0    pypi
atomicwrites              1.4.0                      py_0  
attrs                     23.1.0                   pypi_0    pypi
automat                   20.2.0                     py_0  
autopep8                  2.0.4                    pypi_0    pypi
babel                     2.11.0          py311haa95532_0  
backports                 1.1                pyhd3eb1b0_0  
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0  
backports.tempfile        1.0                pyhd3eb1b0_1  
backports.weakref         1.0.post1                  py_1  
bcrypt                    3.2.0           py311h2bbff1b_1  
beautifulsoup4            4.12.2          py311haa95532_0  
binaryornot               0.4.4              pyhd3eb1b0_1  
black                     24.4.2                   pypi_0    pypi
blas                      1.0                         mkl  
bleach                    4.1.0              pyhd3eb1b0_0  
blinker                   1.6.2                    pypi_0    pypi
blosc                     1.21.3               h6c2663c_0  
boltons                   23.0.0          py311haa95532_0  
botocore                  1.34.69                  pypi_0    pypi
brotli                    1.0.9                    pypi_0    pypi
c-ares                    1.19.1               h2bbff1b_0  
certifi                   2024.6.2                 pypi_0    pypi
cffi                      1.16.0                   pypi_0    pypi
cfitsio                   3.470                h2bbff1b_7  
chardet                   4.0.0           py311haa95532_1003  
charls                    2.2.0                h6c2663c_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.1.7                    pypi_0    pypi
cloudpickle               2.2.1           py311haa95532_0  
clyent                    1.2.2           py311haa95532_1  
colorama                  0.4.6           py311haa95532_0  
colorcet                  3.1.0                    pypi_0    pypi
comm                      0.2.1                    pypi_0    pypi
conda                     23.7.4          py311haa95532_0  
conda-build               3.26.1          py311haa95532_0  
conda-content-trust       0.2.0           py311haa95532_0  
conda-index               0.4.0                    pypi_0    pypi
conda-libmamba-solver     23.7.0          py311haa95532_0  
conda-pack                0.6.0              pyhd3eb1b0_0  
conda-package-handling    2.2.0           py311haa95532_0  
conda-package-streaming   0.9.0           py311haa95532_0  
conda-repo-cli            1.0.88                   pypi_0    pypi
conda-token               0.4.0              pyhd3eb1b0_0  
conda-verify              3.4.2                      py_1  
console_shortcut          0.1.1                         4  
constantly                23.10.4                  pypi_0    pypi
cryptography              42.0.5                   pypi_0    pypi
cssselect                 1.2.0                    pypi_0    pypi
cycler                    0.11.0             pyhd3eb1b0_0  
cytoolz                   0.12.2                   pypi_0    pypi
daal4py                   2023.1.1        py311h30df693_0  
dask                      2024.5.0                 pypi_0    pypi
dav1d                     1.2.1                h2bbff1b_0  
debugpy                   1.6.7           py311hd77b12b_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
diff-match-patch          20200713           pyhd3eb1b0_0  
dill                      0.3.8                    pypi_0    pypi
distributed               2024.5.0                 pypi_0    pypi
docstring-to-markdown     0.11            py311haa95532_0  
docutils                  0.18.1          py311haa95532_3  
entrypoints               0.4             py311haa95532_0  
et_xmlfile                1.1.0           py311haa95532_0  
executing                 0.8.3              pyhd3eb1b0_0  
filelock                  3.13.1                   pypi_0    pypi
flake8                    7.0.0                    pypi_0    pypi
flask                     3.0.3                    pypi_0    pypi
fonttools                 4.51.0                   pypi_0    pypi
freetype                  2.12.1               ha860e81_0  
frozenlist                1.4.0                    pypi_0    pypi
fsspec                    2024.3.1                 pypi_0    pypi
future                    0.18.3          py311haa95532_0  
giflib                    5.2.1                h8cc25b3_3  
glob2                     0.7                pyhd3eb1b0_0  
gmpy2                     2.1.2                    pypi_0    pypi
greenlet                  3.0.1                    pypi_0    pypi
grpc-cpp                  1.48.2               hfe90ff0_1  
hdf5                      1.12.1               h51c971a_3  
heapdict                  1.0.1              pyhd3eb1b0_0  
huggingface-hub           0.23.1                   pypi_0    pypi
hyperlink                 21.0.0             pyhd3eb1b0_0  
icc_rt                    2022.1.0             h6049295_2  
idna                      3.7                      pypi_0    pypi
imagecodecs               2023.1.23       py311he6ff3c7_0  
imagesize                 1.4.1           py311haa95532_0  
importlib-metadata        7.0.1                    pypi_0    pypi
incremental               22.10.0                  pypi_0    pypi
inflection                0.5.1           py311haa95532_0  
iniconfig                 1.1.1              pyhd3eb1b0_0  
intervaltree              3.1.0              pyhd3eb1b0_0  
isort                     5.9.3              pyhd3eb1b0_0  
itemadapter               0.3.0              pyhd3eb1b0_0  
itemloaders               1.1.0                    pypi_0    pypi
itsdangerous              2.2.0                    pypi_0    pypi
jaraco.classes            3.2.1              pyhd3eb1b0_0  
jedi                      0.18.1          py311haa95532_1  
jellyfish                 1.0.1           py311h36a85e1_0  
jinja2                    3.1.4                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
joblib                    1.4.0                    pypi_0    pypi
jpeg                      9e                   h2bbff1b_1  
jq                        1.6                  haa95532_1  
json5                     0.9.6              pyhd3eb1b0_0  
jsonpatch                 1.33                     pypi_0    pypi
jsonpointer               2.1                pyhd3eb1b0_0  
jsonschema                4.19.2                   pypi_0    pypi
jsonschema-specifications 2023.7.1                 pypi_0    pypi
jupyter-client            8.6.0                    pypi_0    pypi
jupyter-core              5.5.0                    pypi_0    pypi
jupyter-events            0.8.0                    pypi_0    pypi
jupyter-server-terminals  0.4.4                    pypi_0    pypi
jupyter_console           6.6.3           py311haa95532_0  
jupyterlab-widgets        3.0.10                   pypi_0    pypi
jupyterlab_pygments       0.1.2                      py_0  
kaleido-core              0.2.1                h2bbff1b_0  
keyring                   24.3.1                   pypi_0    pypi
kiwisolver                1.4.4           py311hd77b12b_0  
krb5                      1.20.1               h5b6d351_0  
lazy-loader               0.3                      pypi_0    pypi
lazy-object-proxy         1.10.0                   pypi_0    pypi
lcms2                     2.12                 h83e58a3_0  
lerc                      3.0                  hd77b12b_0  
libaec                    1.0.4                h33f27b4_1  
libavif                   0.11.1               h2bbff1b_0  
libclang                  14.0.6          default_hb5a9fac_1  
libclang13                14.0.6          default_h8e68704_1  
libevent                  2.1.12               h56d1f94_1  
liblief                   0.12.3               hd77b12b_0  
libmambapy                1.5.8                    pypi_0    pypi
libpng                    1.6.39               h8cc25b3_0  
libprotobuf               3.20.3               h23ce68f_0  
libsodium                 1.0.18               h62dcd97_0  
libspatialindex           1.9.3                h6c2663c_0  
libthrift                 0.15.0               h4364b78_2  
libtiff                   4.5.1                hd77b12b_0  
libwebp-base              1.3.2                h2bbff1b_0  
libxslt                   1.1.37               h2bbff1b_1  
libzopfli                 1.0.3                ha925a31_0  
linkify-it-py             2.0.0           py311haa95532_0  
llvmlite                  0.42.0                   pypi_0    pypi
locket                    1.0.0           py311haa95532_0  
lxml                      5.2.1                    pypi_0    pypi
lz4                       4.3.2           py311h2bbff1b_0  
lzo                       2.10                 he774522_2  
m2-msys2-runtime          2.5.0.17080.65c939c               3  
m2-patch                  2.7.5                         2  
m2w64-libwinpthread-git   5.0.0.4634.697f757               2  
markdown                  3.4.1           py311haa95532_0  
markdown-it-py            2.2.0           py311haa95532_1  
markupsafe                2.1.3                    pypi_0    pypi
mathjax                   2.7.5                haa95532_0  
matplotlib-inline         0.1.6           py311haa95532_0  
mccabe                    0.7.0              pyhd3eb1b0_0  
mdit-py-plugins           0.3.0           py311haa95532_0  
mdurl                     0.1.0           py311haa95532_0  
menuinst                  1.4.19          py311h59b6b97_1  
mistune                   2.0.4                    pypi_0    pypi
mkl-service               2.4.0           py311h2bbff1b_1  
mkl_fft                   1.3.8           py311h2bbff1b_0  
mkl_random                1.2.4           py311h59b6b97_0  
more-itertools            10.1.0                   pypi_0    pypi
mpmath                    1.3.0           py311haa95532_0  
msgpack-python            1.0.3           py311h59b6b97_0  
msys2-conda-epoch         20160418                      1  
multidict                 6.0.4                    pypi_0    pypi
multipledispatch          0.6.0           py311haa95532_0  
mypy_extensions           1.0.0           py311haa95532_0  
navigator-updater         0.5.0                    pypi_0    pypi
nbformat                  5.9.2           py311haa95532_0  
nest-asyncio              1.6.0                    pypi_0    pypi
networkx                  3.2.1                    pypi_0    pypi
nltk                      3.8.1           py311haa95532_0  
numpy                     1.26.4                   pypi_0    pypi
numpydoc                  1.5.0           py311haa95532_0  
openjpeg                  2.4.0                h4fc8c34_0  
openpyxl                  3.1.2                    pypi_0    pypi
orc                       1.7.4                h623e30f_1  
overrides                 7.4.0                    pypi_0    pypi
packaging                 23.2                     pypi_0    pypi
pandocfilters             1.5.0              pyhd3eb1b0_0  
param                     2.1.0                    pypi_0    pypi
paramiko                  2.8.1              pyhd3eb1b0_0  
parsel                    1.8.1                    pypi_0    pypi
parso                     0.8.3              pyhd3eb1b0_0  
partd                     1.4.1                    pypi_0    pypi
pathspec                  0.10.3          py311haa95532_0  
patsy                     0.5.3           py311haa95532_0  
pep8                      1.7.1           py311haa95532_1  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    10.3.0                   pypi_0    pypi
pip                       23.2.1          py311haa95532_0  
pkce                      1.0.3           py311haa95532_0  
pkginfo                   1.10.0                   pypi_0    pypi
platformdirs              3.10.0          py311haa95532_0  
plotly                    5.19.0                   pypi_0    pypi
pluggy                    1.0.0           py311haa95532_1  
ply                       3.11            py311haa95532_0  
powershell_shortcut       0.0.1                         3  
prometheus_client         0.14.1          py311haa95532_0  
prompt-toolkit            3.0.43                   pypi_0    pypi
protego                   0.1.16                     py_0  
psutil                    5.9.0           py311h2bbff1b_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
py-cpuinfo                9.0.0                    pypi_0    pypi
py-lief                   0.12.3          py311hd77b12b_0  
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                      py_0  
pycodestyle               2.11.1                   pypi_0    pypi
pycosat                   0.6.6                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pyct                      0.5.0           py311haa95532_0  
pycurl                    7.45.2          py311he2ea4bf_1  
pydantic                  1.10.12                  pypi_0    pypi
pydispatcher              2.0.5           py311haa95532_2  
pydocstyle                6.3.0           py311haa95532_0  
pyflakes                  3.2.0                    pypi_0    pypi
pygments                  2.15.1          py311haa95532_1  
pyjwt                     2.8.0                    pypi_0    pypi
pylint                    2.16.2          py311haa95532_0  
pylint-venv               3.0.3                    pypi_0    pypi
pyls-spyder               0.4.0              pyhd3eb1b0_0  
pynacl                    1.5.0           py311h8cc25b3_0  
pyodbc                    5.0.1                    pypi_0    pypi
pyopenssl                 24.0.0                   pypi_0    pypi
pyparsing                 3.0.9           py311haa95532_0  
pyqt5                     5.15.10                  pypi_0    pypi
pyqt5-sip                 12.13.0                  pypi_0    pypi
pyqtwebengine             5.15.6                   pypi_0    pypi
pysocks                   1.7.1           py311haa95532_0  
pytest                    7.4.4                    pypi_0    pypi
python                    3.11.5               he1021f5_0  
python-dateutil           2.9.0.post0              pypi_0    pypi
python-dotenv             0.21.0          py311haa95532_0  
python-fastjsonschema     2.16.2          py311haa95532_0  
python-json-logger        2.0.7           py311haa95532_0  
python-kaleido            0.2.1           py311haa95532_0  
python-libarchive-c       2.9                pyhd3eb1b0_1  
python-lmdb               1.4.1           py311hd77b12b_0  
python-lsp-jsonrpc        1.1.2                    pypi_0    pypi
python-lsp-server         1.10.0                   pypi_0    pypi
python-slugify            5.0.2              pyhd3eb1b0_0  
python-snappy             0.6.1           py311hd77b12b_0  
python-tzdata             2023.3             pyhd3eb1b0_0  
pytoolconfig              1.2.6                    pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pyviz-comms               3.0.2                    pypi_0    pypi
pywin32                   305             py311h2bbff1b_0  
pywin32-ctypes            0.2.2                    pypi_0    pypi
pywinpty                  2.0.10          py311h5da7b33_0  
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     25.1.2                   pypi_0    pypi
qdarkstyle                3.2.3                    pypi_0    pypi
qstylizer                 0.2.2           py311haa95532_0  
qt-webengine              5.15.9               h5bd16bc_7  
qtawesome                 1.2.2           py311haa95532_0  
qtpy                      2.4.1                    pypi_0    pypi
queuelib                  1.6.2                    pypi_0    pypi
re2                       2022.04.01           hd77b12b_0  
referencing               0.30.2                   pypi_0    pypi
regex                     2023.10.3                pypi_0    pypi
requests                  2.32.2                   pypi_0    pypi
requests-file             1.5.1              pyhd3eb1b0_0  
requests-toolbelt         1.0.0           py311haa95532_0  
rfc3339-validator         0.1.4           py311haa95532_0  
rfc3986-validator         0.1.1           py311haa95532_0  
rich                      13.3.5                   pypi_0    pypi
rope                      1.12.0                   pypi_0    pypi
rpds-py                   0.10.6                   pypi_0    pypi
rtree                     1.0.1           py311h2eaa2aa_0  
ruamel.yaml               0.17.21         py311h2bbff1b_0  
ruamel_yaml               0.17.21         py311h2bbff1b_0  
safetensors               0.4.2                    pypi_0    pypi
scikit-learn-intelex      2023.1.1        py311haa95532_0  
seaborn                   0.12.2          py311haa95532_0  
send2trash                1.8.2                    pypi_0    pypi
service_identity          18.1.0             pyhd3eb1b0_1  
setuptools                68.0.0          py311haa95532_0  
sip                       6.7.12                   pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1  
smart_open                5.2.1           py311haa95532_0  
sniffio                   1.3.0                    pypi_0    pypi
snowballstemmer           2.2.0              pyhd3eb1b0_0  
sortedcontainers          2.4.0              pyhd3eb1b0_0  
soupsieve                 2.5                      pypi_0    pypi
sphinx                    5.0.2           py311haa95532_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0  
sqlalchemy                2.0.25                   pypi_0    pypi
stack_data                0.2.0              pyhd3eb1b0_0  
statsmodels               0.14.0          py311hd7041d2_0  
sympy                     1.12                     pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tbb                       2021.8.0             h59b6b97_0  
tbb4py                    2021.8.0        py311h59b6b97_0  
tblib                     1.7.0              pyhd3eb1b0_0  
tenacity                  8.2.2           py311haa95532_0  
terminado                 0.17.1          py311haa95532_0  
text-unidecode            1.3                pyhd3eb1b0_0  
textdistance              4.2.1              pyhd3eb1b0_0  
threadpoolctl             2.2.0              pyh0d69192_0  
three-merge               0.1.1              pyhd3eb1b0_0  
tifffile                  2023.4.12       py311haa95532_0  
tinycss2                  1.2.1           py311haa95532_0  
tldextract                3.2.0              pyhd3eb1b0_0  
tokenizers                0.15.1                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
tomlkit                   0.11.1          py311haa95532_0  
toolz                     0.12.0          py311haa95532_0  
tornado                   6.3.3                    pypi_0    pypi
tqdm                      4.66.4                   pypi_0    pypi
traitlets                 5.7.1           py311haa95532_0  
twisted                   23.10.0                  pypi_0    pypi
twisted-iocpsupport       1.0.2           py311h2bbff1b_0  
typing-extensions         4.11.0                   pypi_0    pypi
uc-micro-py               1.0.1           py311haa95532_0  
ujson                     5.10.0                   pypi_0    pypi
unicodedata2              15.1.0                   pypi_0    pypi
unidecode                 1.2.0              pyhd3eb1b0_0  
urllib3                   2.2.1                    pypi_0    pypi
w3lib                     2.1.2                    pypi_0    pypi
watchdog                  4.0.1                    pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1           py311haa95532_1  
websocket-client          1.8.0                    pypi_0    pypi
werkzeug                  3.0.3                    pypi_0    pypi
whatthepatch              1.0.2           py311haa95532_0  
wheel                     0.38.4          py311haa95532_0  
widgetsnbextension        4.0.10                   pypi_0    pypi
win_inet_pton             1.1.0           py311haa95532_0  
winpty                    0.4.3                         4  
wrapt                     1.14.1          py311h2bbff1b_0  
xarray                    2023.6.0        py311haa95532_0  
xlwings                   0.31.4                   pypi_0    pypi
xyzservices               2022.9.0        py311haa95532_1  
yaml                      0.2.5                he774522_0  
yapf                      0.40.2                   pypi_0    pypi
yarl                      1.9.3                    pypi_0    pypi
zfp                       1.0.0                hd77b12b_0  
zict                      3.0.0                    pypi_0    pypi
zipp                      3.17.0                   pypi_0    pypi
zlib-ng                   2.0.7                h2bbff1b_0  
zope                      1.0             py311haa95532_1  
zope.interface            5.4.0           py311h2bbff1b_0  
zstandard                 0.22.0                   pypi_0    pypi

```
</details>

**Comment by ccordoba12** [comment]
Hey @rayyankhan1234567890, thanks for reporting. This problem should be fixed in our latest version available in Anaconda (5.5.1). Please update by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).
