### ISSUE TITLE
Can't open file due to lack of resources

### ISSUE THREAD

**Issue by lucamian** [spyder-ide/spyder#22153]
### What steps will reproduce the problem?

Simply trying to open a Pyhton file generates the problem

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\TemporaryWorkingArea\anaconda3\lib\ntpath.py", line 647, in realpath
    path = _getfinalpathname(path)
OSError: [WinError 1816] Non c'è abbastanza disponibilità per elaborare il comando: '\\\\fileshare\\UserProfile$\\mianluc39165\\Desktop\\Seizures_Weighted_log\\6\\6_Almaqableh22a_seizures_weighted_log.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\TemporaryWorkingArea\anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 2187, in load
    current_editor = self.set_current_filename(filename,
  File "C:\TemporaryWorkingArea\anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 1721, in set_current_filename
    return editorstack.set_current_filename(filename, focus)
  File "C:\TemporaryWorkingArea\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1512, in set_current_filename
    index = self.has_filename(filename)
  File "C:\TemporaryWorkingArea\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1501, in has_filename
    if fixpath(filename) == fixpath(finfo.filename):
  File "C:\TemporaryWorkingArea\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1499, in <lambda>
    fixpath = lambda path: osp.normcase(osp.realpath(path))
  File "C:\TemporaryWorkingArea\anaconda3\lib\ntpath.py", line 651, in realpath
    path = _getfinalpathname_nonstrict(path)
  File "C:\TemporaryWorkingArea\anaconda3\lib\ntpath.py", line 601, in _getfinalpathname_nonstrict
    path = _getfinalpathname(path)
OSError: [WinError 1816] Non c'è abbastanza disponibilità per elaborare il comando: '\\\\fileshare\\UserProfile$\\mianluc39165\\Desktop\\Seizures_Weighted_log\\6\\6_Almaqableh22a_seizures_weighted_log.py'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.2.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.0 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by dalthviz** [comment]
Hi @lucamian thank you for the report and sorry for the late response! Seems like this error could be caused do to lack of resources when syncing a file. Checking around found a couple of post related with the error: https://answers.microsoft.com/en-us/windows/forum/all/error-0x80070718-not-enough-quota-is-available-to/c8fdb95f-1a6d-4b81-b9d3-1ce180bea2af 

Let us know if the info above helps!

Also, @ccordoba12 maybe we should try to catch such error?

**Comment by ccordoba12** [comment]
Yeah, I think that's a good idea. I'm going to leave this bug for 6.0.4 then.

**Comment by dalthviz** [comment]
Checking the related code on the latest version (Spyder 6.0.4) seems like this could have been solved when a solution for #17685 was done:

https://github.com/spyder-ide/spyder/blob/32984cb323ccb594fee5e168f8ed52de3163573f/spyder/plugins/editor/widgets/editorstack/editorstack.py#L1473-L1486

Checking again, the issue appeared while using Spyder 5.1.5 so maybe just updating (at least to version 5.3.1) could prevent it or maybe there is something here that still needs to be done 🤔 What do you think @ccordoba12 ?

**Comment by ccordoba12** [comment]
Yeah, that could work, thanks for checking that @dalthviz!

@lucamian, please update to a more recent Spyder 5 version (the latest one in Anaconda is 5.5.1) and let us know if that solves the problem for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
