### ISSUE TITLE
`OSError: [WinError 4350] This file is currently not available for use on this computer` when renaming network drive file outside Spyder

### ISSUE THREAD

**Issue by AdrienKroese** [spyder-ide/spyder#22175]
### What steps will reproduce the problem?

Change file name in windows explorer
When prompted to save file in Spyder after "file was changed" click save
Overwrite renamed file

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\adke0002\Anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1532, in has_filename
    return data_filenames.index(filename)
ValueError: '\\\\storage.slu.se\\Home$\\adke0002\\My Documents\\Git\\digital_welfare_SLU\\Papers + abstracts\\Paper 2 CEA lying down\\2.1 Lying down event detection.py' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\adke0002\Anaconda3\lib\ntpath.py", line 647, in realpath
    path = _getfinalpathname(path)
OSError: [WinError 4350] This file is currently not available for use on this computer: '\\\\storage.slu.se\\Home$\\adke0002\\My Documents\\Git\\digital_welfare_SLU\\Papers + abstracts\\Paper 2 CEA lying down\\2.1 Lying down feature extraction.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\adke0002\Anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1918, in save
    return self.save_as(index=index)
  File "C:\Users\adke0002\Anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 2097, in save_as
    ao_index = self.has_filename(filename)
  File "C:\Users\adke0002\Anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1542, in has_filename
    if filename == fixpath(editor_filename):
  File "C:\Users\adke0002\Anaconda3\lib\site-packages\spyder\plugins\explorer\widgets\utils.py", line 54, in fixpath
    return norm(osp.abspath(osp.realpath(path)))
  File "C:\Users\adke0002\Anaconda3\lib\ntpath.py", line 651, in realpath
    path = _getfinalpathname_nonstrict(path)
  File "C:\Users\adke0002\Anaconda3\lib\ntpath.py", line 601, in _getfinalpathname_nonstrict
    path = _getfinalpathname(path)
OSError: [WinError 4350] This file is currently not available for use on this computer: '\\\\storage.slu.se\\Home$\\adke0002\\My Documents\\Git\\digital_welfare_SLU\\Papers + abstracts\\Paper 2 CEA lying down\\2.1 Lying down feature extraction.py'
```

## Versions

* Spyder version: 5.5.1  (conda)
* Python version: 3.9.18 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  2.2.1 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.15.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.18.1 (OK)
jellyfish >=0.7                  :  1.0.1 (OK)
jsonschema >=3.2.0               :  4.19.2 (OK)
keyring >=17.0.0                 :  23.13.1 (OK)
nbconvert >=4.0                  :  7.10.0 (OK)
numpydoc >=0.6.0                 :  1.5.0 (OK)
paramiko >=2.4.0                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.0 (OK)
pygments >=2.0                   :  2.15.1 (OK)
pylint >=2.5.0,<3.1              :  2.16.2 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.10.0,<1.11.0           :  1.10.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.2.2 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.1 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.0.1 (OK)
setuptools >=49.6.0              :  68.2.2 (OK)
sphinx >=0.6.6                   :  5.0.2 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.0 (OK)
textdistance >=4.2.0             :  4.2.1 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  2.1.6 (OK)
zmq >=22.1.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  3.8.0 (OK)
numpy >=1.7                      :  1.26.4 (OK)
pandas >=1.1.1                   :  2.2.1 (OK)
scipy >=0.17.0                   :  1.11.4 (OK)
sympy >=0.7.3                    :  None (NOK)
```

**Comment by dalthviz** [comment]
Hi @AdrienKroese thank you for the report and sorry for such a late response! I was unable to reproduce this with Spyder 6.0.4 (latest version) but also checking the traceback posted seems like you were opening the file from a network drive? Maybe renaming the file caused an inconsistency while the file was being synced? From a quick check seems like such an error `OSError: [WinError 4350] This file is currently not available for use on this computer` due to sync files config for offline files (https://community.spiceworks.com/t/this-file-is-currently-not-available-for-use-on-this-computer/327260/3) 🤔 

Should we try to maybe catch this type of error @ccordoba12 and instead show an error dialog with something like the info above?

**Comment by ccordoba12** [comment]
> Should we try to maybe catch this type of error @ccordoba12 and instead show an error dialog with something like the info above?

I think we should not offer the option to save the file if we detect is renamed and placed in a network drive, due to what @AdrienKroese said:

>> When prompted to save file in Spyder after "file was changed" click save
>> **Overwrite renamed file**

That's an unpleasant surprise, so we should prevent it.

**Comment by ccordoba12** [comment]
@AdrienKroese, unfortunately, we were unable to reproduce this problem. So, we're unsure how we could fix it, sorry.
