### ISSUE TITLE
Error in opening spyder

### ISSUE THREAD

**Issue by crtchakri** [spyder-ide/spyder#22182]
Traceback (most recent call last):
File "C:\Anaconda3\envs\ocm_evm\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
^^^^^^
File "C:\Anaconda3\envs\ocm_evm\Lib\site-packages\spyder\app\start.py", line 257, in main
mainwindow.main(options, args)
File "C:\Anaconda3\envs\ocm_evm\Lib\site-packages\spyder\app\mainwindow.py", line 1847, in main
mainwindow = create_window(MainWindow, app, splash, options, args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Anaconda3\envs\ocm_evm\Lib\site-packages\spyder\app\utils.py", line 289, in create_window
main.setup()
File "C:\Anaconda3\envs\ocm_evm\Lib\site-packages\spyder\app\mainwindow.py", line 752, in setup
internal_plugins = find_internal_plugins()
^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Anaconda3\envs\ocm_evm\Lib\site-packages\spyder\app\find_plugins.py", line 40, in find_internal_plugins
mod = importlib.import_module(entry_point.module_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Anaconda3\envs\ocm_evm\Lib\importlib\__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "", line 1204, in _gcd_import
File "", line 1176, in _find_and_load
File "", line 1147, in _find_and_load_unlocked
File "", line 690, in _load_unlocked
File "", line 940, in exec_module
File "", line 241, in _call_with_frames_removed
File "C:\Anaconda3\envs\ocm_evm\Lib\site-packages\spyder\plugins\pylint\plugin.py", line 22, in 
from spyder.plugins.pylint.confpage import PylintConfigPage
File "C:\Anaconda3\envs\ocm_evm\Lib\site-packages\spyder\plugins\pylint\confpage.py", line 16, in 
from spyder.plugins.pylint.main_widget import (MAX_HISTORY_ENTRIES,
File "C:\Anaconda3\envs\ocm_evm\Lib\site-packages\spyder\plugins\pylint\main_widget.py", line 90, in 
class CategoryItem(QTreeWidgetItem):
File "C:\Anaconda3\envs\ocm_evm\Lib\site-packages\spyder\plugins\pylint\main_widget.py", line 102, in CategoryItem
'icon': ima.icon("convention")
^^^^^^^^^^^^^^^^^^^^^^
File "C:\Anaconda3\envs\ocm_evm\Lib\site-packages\spyder\utils\icon_manager.py", line 433, in icon
qta.load_font('spyder', 'spyder.ttf', 'spyder-charmap.json',
File "C:\Anaconda3\envs\ocm_evm\Lib\site-packages\qtawesome\__init__.py", line 280, in load_font
return _instance().load_font(prefix, ttf_filename, charmap_filename, directory)
^^^^^^^^^^^
File "C:\Anaconda3\envs\ocm_evm\Lib\site-packages\qtawesome\__init__.py", line 130, in _instance
_resource['iconic'] = IconicFont(*_BUNDLED_FONTS)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Anaconda3\envs\ocm_evm\Lib\site-packages\qtawesome\iconic_font.py", line 338, in __init__
self.load_font(*fargs)
File "C:\Anaconda3\envs\ocm_evm\Lib\site-packages\qtawesome\iconic_font.py", line 374, in load_font
directory = self._get_fonts_directory()
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Anaconda3\envs\ocm_evm\Lib\site-packages\qtawesome\iconic_font.py", line 593, in _get_fonts_directory
fonts_directory = self._install_fonts(fonts_directory)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Anaconda3\envs\ocm_evm\Lib\site-packages\qtawesome\iconic_font.py", line 623, in _install_fonts
shutil.copy(src_path, user_fonts_dir)
File "C:\Anaconda3\envs\ocm_evm\Lib\shutil.py", line 431, in copy
copyfile(src, dst, follow_symlinks=follow_symlinks)
File "C:\Anaconda3\envs\ocm_evm\Lib\shutil.py", line 258, in copyfile
with open(dst, 'wb') as fdst:
^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\chakri\\AppData\\Local\\Microsoft\\Windows\\Fonts\\codicon.ttf'

**Comment by ccordoba12** [comment]
Hey @crtchakri, thanks for reporting. This problem is fixed in the latest version of one of our dependencies: QtAwesome 1.3.1.

Since it's not available in Anaconda yet, you need to install Spyder in a new environment from Conda-forge (a community maintained set of conda packages). For that, you need to open the Anaconda Prompt and run the following commands:

    conda create -n spyder-env -c conda-forge spyder
    conda activate spyder-env
    spyder

Let us know if it works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
