### ISSUE TITLE
Trying to install Spyder 2.3.3 on Ubuntu 14.04.2 LTS for Python 3.4.x

### ISSUE THREAD

**Issue by s0r2637** [spyder-ide/spyder#2220]
Hi,
I am trying to install Spyder 2.3.3 on Ubuntu 14.04.2 LTS for Python 3.4.x.  I try to build/install from the source in GitHub through the following steps:

1) git clone https://github.com/spyder-ide/spyder
2) cd ~/spyder
3) sudo python3 setup.py install

I get the following message:

**WARNING: unable to build documentation because Sphinx is not installed
running install
running build
running build_py
running build_scripts
running install_lib
running install_scripts
changing mode of /usr/local/bin/spyder3 to 755
changing mode of /usr/local/bin/spyder_win_post_install.py to 775
running install_data
running install_egg_info
Removing /usr/local/lib/python3.4/dist-packages/spyder-2.4.0dev.egg-info
Writing /usr/local/lib/python3.4/dist-packages/spyder-2.4.0dev.egg-info**

When I run 'spyder3,' I get the following error:
**Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/spyderlib/requirements.py", line 41, in check_qt
    from spyderlib import qt
  File "/usr/local/lib/python3.4/dist-packages/spyderlib/qt/__init__.py", line 32, in <module>
    import sip
ImportError: No module named 'sip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/spyder3", line 3, in <module>
    start_app.main()
  File "/usr/local/lib/python3.4/dist-packages/spyderlib/start_app.py", line 85, in main
    from spyderlib import spyder
  File "/usr/local/lib/python3.4/dist-packages/spyderlib/spyder.py", line 46, in <module>
    requirements.check_qt()
  File "/usr/local/lib/python3.4/dist-packages/spyderlib/requirements.py", line 51, in check_qt
    % (qt_infos['pyqt']+qt_infos['pyside']))
  File "/usr/local/lib/python3.4/dist-packages/spyderlib/requirements.py", line 25, in show_warning
    raise RuntimeError(message)
RuntimeError: Please check Spyder installation requirements:
PyQt4 4.6+ (or PySide 1.2.0+) is required.**

I did install PyQt4 from Ubuntu software center.  Could someone please help me in resolving the issue?

**Comment by s0r2637** [comment]
Sorry I misled on my previous statement that PyQt4 was installed.  It was installed, but only for Python2.7.x.  I went and installed it for Python3.4.x.  Now Spyder3 works fine.
