### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by shukai-lu-int** [spyder-ide/spyder#22216]
### What steps will reproduce the problem?

Opening Spyder after installing a list of packages such as panadas, matplotlib, pyyaml etc, a window pops up saying Spyder has a bug that states that nbconvert>=4.0 as a dependency is not installed. However, I do have nbconvert 6.1.0, which is strange that this error pops up.

### Traceback
```python-traceback

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\spyder\dependencies.py", line 425, in declare_dependencies
    add(dep['modname'], dep['package_name'],
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\spyder\dependencies.py", line 350, in add
    DEPENDENCIES += [Dependency(modname, package_name, features,
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\spyder\dependencies.py", line 307, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\spyder\utils\programs.py", line 852, in get_module_version
    mod = __import__(module_name)
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\matplotlib\rcsetup.py", line 26, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\matplotlib\colors.py", line 82, in <module>
    from matplotlib import _api, cbook, scale
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\matplotlib\scale.py", line 18, in <module>
    from matplotlib.ticker import (
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\matplotlib\ticker.py", line 179, in <module>
    from matplotlib import transforms as mtransforms
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\matplotlib\transforms.py", line 46, in <module>
    from matplotlib._path import (
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\spyder\dependencies.py", line 425, in declare_dependencies
    add(dep['modname'], dep['package_name'],
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\spyder\dependencies.py", line 350, in add
    DEPENDENCIES += [Dependency(modname, package_name, features,
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\spyder\dependencies.py", line 307, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\spyder\utils\programs.py", line 852, in get_module_version
    mod = __import__(module_name)
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\pandas\__init__.py", line 77, in <module>
    from pandas.core.api import (
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\pandas\core\arrays\arrow\array.py", line 50, in <module>
    from pandas.core import (
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\pandas\core\ops\__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\pandas\core\ops\array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\shukai.lu.int\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\numexpr\__init__.py", line 26, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\spyder\dependencies.py", line 425, in declare_dependencies
    add(dep['modname'], dep['package_name'],
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\spyder\dependencies.py", line 350, in add
    DEPENDENCIES += [Dependency(modname, package_name, features,
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\spyder\dependencies.py", line 307, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\spyder\utils\programs.py", line 852, in get_module_version
    mod = __import__(module_name)
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\pandas\__init__.py", line 77, in <module>
    from pandas.core.api import (
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\pandas\core\arrays\arrow\array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\pandas\core\arrays\masked.py", line 60, in <module>
    from pandas.core import (
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\pandas\core\nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\shukai.lu.int\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\shukai.lu.int\Anaconda3\lib\site-packages\bottleneck\__init__.py", line 2, in <module>
    from .reduce import (
AttributeError: _ARRAY_API not found
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.7
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  None (NOK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  2.0.0 (OK)
pandas >=1.1.1                :  2.2.2 (OK)
scipy >=0.17.0                :  1.13.1 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment]
Hey @shukai-lu-int, thanks for reporting. You said:

> Opening Spyder after installing a list of packages such as panadas, matplotlib, pyyaml etc, a window pops up saying Spyder has a bug that states that nbconvert>=4.0 as a dependency is not installed. However, I do have nbconvert 6.1.0, which is strange that this error pops up.

You probably used pip to install those packages. If that's the case I'm afraid that broke your Anaconda installation and now you'll have to reinstall it. That's because pip and conda packages are binary incompatible, so they can't be mixed in the same environment.

Please see [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs&feature=youtu.be) to better understand what happened and how to correctly reinstall Anaconda.
