### ISSUE TITLE
I used pip to update spyder

### ISSUE THREAD

**Issue by elenichrr** [spyder-ide/spyder#22226]
### What steps will reproduce the problem?

I used pip and now i can use my spyder... I was trying to update my spyder but because im using anacoda now is not working

### Traceback
```python-traceback

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\dependencies.py", line 425, in declare_dependencies
    add(dep['modname'], dep['package_name'],
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\dependencies.py", line 350, in add
    DEPENDENCIES += [Dependency(modname, package_name, features,
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\dependencies.py", line 307, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\programs.py", line 852, in get_module_version
    mod = __import__(module_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\rcsetup.py", line 26, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\colors.py", line 82, in <module>
    from matplotlib import _api, cbook, scale
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\scale.py", line 18, in <module>
    from matplotlib.ticker import (
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\ticker.py", line 179, in <module>
    from matplotlib import transforms as mtransforms
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\transforms.py", line 46, in <module>
    from matplotlib._path import (
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\ProgramData\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\start.py", line 228, in main
    mainwindow.main(options, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1992, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\utils.py", line 326, in create_window
    app.exec_()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\reporterror.py", line 367, in _submit_to_github
    issue_text = self.render_issue(description=description,
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\reporterror.py", line 318, in render_issue
    dependencies=dependencies.status())
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\dependencies.py", line 378, in status
    data.append([dep_order[dep.kind], title, dep.get_installed_version()])
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\dependencies.py", line 326, in get_installed_version
    if self.check():
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\dependencies.py", line 319, in check
    return programs.is_module_installed(self.modname,
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\programs.py", line 918, in is_module_installed
    module_version = get_module_version(module_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\programs.py", line 852, in get_module_version
    mod = __import__(module_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\rcsetup.py", line 26, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\colors.py", line 82, in <module>
    from matplotlib import _api, cbook, scale
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\scale.py", line 18, in <module>
    from matplotlib.ticker import (
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\ticker.py", line 179, in <module>
    from matplotlib import transforms as mtransforms
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\transforms.py", line 46, in <module>
    from matplotlib._path import (
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 164, in lock
    symlink(str(os.getpid()), self.name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 96, in symlink
    rename(newlinkname, filename)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\eleni\\.spyder-py3\\spyder.lock.1719999834742.newlink' -> 'C:\\Users\\eleni\\.spyder-py3\\spyder.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 191, in lock
    kill(int(pid), 0)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 80, in kill
    raise OSError(errno.ESRCH, None)
ProcessLookupError: [Errno 3] None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\start.py", line 204, in main
    lock_created = lock.lock()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 199, in lock
    rmlink(self.name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 122, in rmlink
    os.rmdir(filename)
OSError: [WinError 145] The directory is not empty: 'C:\\Users\\eleni\\.spyder-py3\\spyder.lock'

During handling of the above exception, another exception occurred:

AttributeError: _ARRAY_API not found
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.7
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  2.0.0 (OK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment]
Hey @elenichrr, thanks for reporting. You said:

> I used pip and now i can use my spyder... I was trying to update my spyder but because im using anacoda now is not working

I'm afraid that broke your Anaconda installation and now you'll have to reinstall it. That's because pip and conda packages are binary incompatible, so they can't be mixed in the same environment.

Please see [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs&feature=youtu.be) to better understand what happened and how to correctly reinstall Anaconda.
