### ISSUE TITLE
chcp  and findstr are recognized as an internal or external command

### ISSUE THREAD

**Issue by nayan-markali** [spyder-ide/spyder#22229]
### What steps will reproduce the problem?

after launching spyder console is opened and it shows error "An error occured while starting the kernel"
'chcp' is not recognised as an internal or external command, operable program or batch file.'findstr' is not recognised as an internal or external command, operable program or batch file

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\Nayan\anaconda3\Lib\site-packages\jupyter_client\manager.py", line 91, in wrapper
    self._ready.set_result(None)
asyncio.exceptions.InvalidStateError: invalid state

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nayan\anaconda3\Lib\site-packages\qtconsole\manager.py", line 27, in poll
    super().poll()
  File "C:\Users\Nayan\anaconda3\Lib\site-packages\jupyter_client\restarter.py", line 143, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "C:\Users\Nayan\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nayan\anaconda3\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Nayan\anaconda3\Lib\site-packages\jupyter_client\manager.py", line 596, in _async_restart_kernel
    await self._async_start_kernel(**self._launch_args)
  File "C:\Users\Nayan\anaconda3\Lib\site-packages\jupyter_client\manager.py", line 94, in wrapper
    self._ready.set_exception(e)
asyncio.exceptions.InvalidStateError: invalid state
```

## Versions

* Spyder version: 5.5.1  (conda)
* Python version: 3.12.4 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-11-10.0.22631-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  2.2.1 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.25.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.18.1 (OK)
jellyfish >=0.7                  :  1.0.1 (OK)
jsonschema >=3.2.0               :  4.19.2 (OK)
keyring >=17.0.0                 :  24.3.1 (OK)
nbconvert >=4.0                  :  7.10.0 (OK)
numpydoc >=0.6.0                 :  1.7.0 (OK)
paramiko >=2.4.0                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.0 (OK)
pygments >=2.0                   :  2.15.1 (OK)
pylint >=2.5.0,<3.1              :  2.16.2 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.10.0,<1.11.0           :  1.10.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.2.2 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.1 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.0.1 (OK)
setuptools >=49.6.0              :  69.5.1 (OK)
sphinx >=0.6.6                   :  7.3.7 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.0 (OK)
textdistance >=4.2.0             :  4.2.1 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.1 (OK)
zmq >=22.1.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  3.8.4 (OK)
numpy >=1.7                      :  1.26.4 (OK)
pandas >=1.1.1                   :  2.2.2 (OK)
scipy >=0.17.0                   :  1.13.1 (OK)
sympy >=0.7.3                    :  1.12 (OK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at C:\Users\Nayan\anaconda3\envs\example:
#
# Name                    Version                   Build  Channel
asttokens                 2.0.5              pyhd3eb1b0_0  
bzip2                     1.0.8                h2bbff1b_6  
ca-certificates           2024.3.11            haa95532_0  
cloudpickle               2.2.1           py312haa95532_0  
colorama                  0.4.6           py312haa95532_0  
comm                      0.2.1           py312haa95532_0  
debugpy                   1.6.7           py312hd77b12b_0  
decorator                 5.1.1              pyhd3eb1b0_0  
executing                 0.8.3              pyhd3eb1b0_0  
expat                     2.6.2                hd77b12b_0  
ipykernel                 6.28.0          py312haa95532_0  
ipython                   8.25.0          py312haa95532_0  
jedi                      0.18.1          py312haa95532_1  
jupyter_client            8.6.0           py312haa95532_0  
jupyter_core              5.7.2           py312haa95532_0  
libffi                    3.4.4                hd77b12b_1  
libsodium                 1.0.18               h62dcd97_0  
matplotlib-inline         0.1.6           py312haa95532_0  
nest-asyncio              1.6.0           py312haa95532_0  
openssl                   3.0.14               h827c3e9_0  
packaging                 23.2            py312haa95532_0  
parso                     0.8.3              pyhd3eb1b0_0  
pip                       24.0            py312haa95532_0  
platformdirs              3.10.0          py312haa95532_0  
prompt-toolkit            3.0.43          py312haa95532_0  
prompt_toolkit            3.0.43               hd3eb1b0_0  
psutil                    5.9.0           py312h2bbff1b_0  
pure_eval                 0.2.2              pyhd3eb1b0_0  
pygments                  2.15.1          py312haa95532_1  
python                    3.12.4               h14ffc60_1  
python-dateutil           2.9.0post0      py312haa95532_2  
pywin32                   305             py312h2bbff1b_0  
pyzmq                     25.1.2          py312hd77b12b_0  
setuptools                69.5.1          py312haa95532_0  
six                       1.16.0             pyhd3eb1b0_1  
spyder-kernels            2.5.0           py312haa95532_0  
sqlite                    3.45.3               h2bbff1b_0  
stack_data                0.2.0              pyhd3eb1b0_0  
tk                        8.6.14               h0416ee5_0  
tornado                   6.4.1           py312h827c3e9_0  
traitlets                 5.14.3          py312haa95532_0  
tzdata                    2024a                h04d1e81_0  
vc                        14.2                 h2eaa2aa_4  
vs2015_runtime            14.29.30133          h43f2093_4  
wcwidth                   0.2.5              pyhd3eb1b0_0  
wheel                     0.43.0          py312haa95532_0  
xz                        5.4.6                h8cc25b3_1  
zeromq                    4.3.5                hd77b12b_0  
zlib                      1.2.13               h8cc25b3_1  

```
</details>

**Comment by dalthviz** [comment]
Hi @nayan-markali thank you for the feedback! What happens if you try to run something like `where chcp` from a cmd? I would say that seems like your machine is having some issues with the `PATH` environment variable  value. Maybe giving a check to something like https://stackoverflow.com/a/8143664 could help.

Let us know if the info above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
