### ISSUE TITLE
difficulties openning spyder

### ISSUE THREAD

**Issue by humeaf** [spyder-ide/spyder#22236]
### What steps will reproduce the problem?

when I try to open spyder from the environment on terminal on a Mac I get these errors 

Traceback (most recent call last):
File "/Users/hume/miniforge3/envs/tf/lib/python3.10/site‑packages/spyder_kernels/console/__main__.py", line 24, in
start.main()
File "/Users/hume/miniforge3/envs/tf/lib/python3.10/site‑packages/spyder_kernels/console/start.py", line 284, in main
import_spydercustomize()
File "/Users/hume/miniforge3/envs/tf/lib/python3.10/site‑packages/spyder_kernels/console/start.py", line 47, in import_spydercustomize
import spydercustomize # noqa
File "/Users/hume/miniforge3/envs/tf/lib/python3.10/site‑packages/spyder_kernels/customize/spydercustomize.py", line 25, in
from IPython.core.getipython import get_ipython
File "/Users/hume/miniforge3/envs/tf/lib/python3.10/site‑packages/IPython/__init__.py", line 55, in
from .terminal.embed import embed
File "/Users/hume/miniforge3/envs/tf/lib/python3.10/site‑packages/IPython/terminal/embed.py", line 15, in
from IPython.core.interactiveshell import DummyMod, InteractiveShell
File "/Users/hume/miniforge3/envs/tf/lib/python3.10/site‑packages/IPython/core/interactiveshell.py", line 110, in
from IPython.core.history import HistoryManager
File "/Users/hume/miniforge3/envs/tf/lib/python3.10/site‑packages/IPython/core/history.py", line 10, in
import sqlite3
File "/Users/hume/miniforge3/envs/tf/lib/python3.10/sqlite3/__init__.py", line 57, in
from sqlite3.dbapi2 import *
File "/Users/hume/miniforge3/envs/tf/lib/python3.10/sqlite3/dbapi2.py", line 27, in
from _sqlite3 import *
ImportError: dlopen(/Users/hume/miniforge3/envs/tf/lib/python3.10/lib‑dynload/_sqlite3.cpython�‑darwin.so, 0x0002): Symbol not found: _sqlite3_enable_load_extension
Referenced from: <2EB36E11�𔂭C25𔂳AE5󈚺D0DE8AFB9B> /Users/hume/miniforge3/envs/tf/lib/python3.10/lib‑dynload/_sqlite3.cpython�‑darwin.so
Expected in: /usr/lib/libsqlite3.dylib
Traceback (most recent call last):
File "/Users/hume/miniforge3/envs/tf/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Users/hume/miniforge3/envs/tf/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/Users/hume/miniforge3/envs/tf/lib/python3.10/site‑packages/spyder_kernels/console/__main__.py", line 24, in
start.main()
File "/Users/hume/miniforge3/envs/tf/lib/python3.10/site‑packages/spyder_kernels/console/start.py", line 284, in main
import_spydercustomize()
File "/Users/hume/miniforge3/envs/tf/lib/python3.10/site‑packages/spyder_kernels/console/start.py", line 47, in import_spydercustomize
import spydercustomize # noqa
File "/Users/hume/miniforge3/envs/tf/lib/python3.10/site‑packages/spyder_kernels/customize/spydercustomize.py", line 25, in
from IPython.core.getipython import get_ipython
File "/Users/hume/miniforge3/envs/tf/lib/python3.10/site‑packages/IPython/__init__.py", line 55, in
from .terminal.embed import embed
File "/Users/hume/miniforge3/envs/tf/lib/python3.10/site‑packages/IPython/terminal/embed.py", line 15, in
from IPython.core.interactiveshell import DummyMod, InteractiveShell
File "/Users/hume/miniforge3/envs/tf/lib/python3.10/site‑packages/IPython/core/interactiveshell.py", line 110, in
from IPython.core.history import HistoryManager
File "/Users/hume/miniforge3/envs/tf/lib/python3.10/site‑packages/IPython/core/history.py", line 10, in
import sqlite3
File "/Users/hume/miniforge3/envs/tf/lib/python3.10/sqlite3/__init__.py", line 57, in
from sqlite3.dbapi2 import *
File "/Users/hume/miniforge3/envs/tf/lib/python3.10/sqlite3/dbapi2.py", line 27, in
from _sqlite3 import *
ImportError: dlopen(/Users/hume/miniforge3/envs/tf/lib/python3.10/lib‑dynload/_sqlite3.cpython�‑darwin.so, 0x0002): Symbol not found: _sqlite3_enable_load_extension
Referenced from: <2EB36E11�𔂭C25𔂳AE5󈚺D0DE8AFB9B> /Users/hume/miniforge3/envs/tf/lib/python3.10/lib‑dynload/_sqlite3.cpython�‑darwin.so
Expected in: /usr/lib/libsqlite3.dylib

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/Users/hume/miniforge3/envs/spyder-env/lib/python3.12/site-packages/jupyter_client/manager.py", line 91, in wrapper
    self._ready.set_result(None)
asyncio.exceptions.InvalidStateError: invalid state

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hume/miniforge3/envs/spyder-env/lib/python3.12/site-packages/qtconsole/manager.py", line 27, in poll
    super().poll()
  File "/Users/hume/miniforge3/envs/spyder-env/lib/python3.12/site-packages/jupyter_client/restarter.py", line 143, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "/Users/hume/miniforge3/envs/spyder-env/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hume/miniforge3/envs/spyder-env/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/hume/miniforge3/envs/spyder-env/lib/python3.12/site-packages/jupyter_client/manager.py", line 596, in _async_restart_kernel
    await self._async_start_kernel(**self._launch_args)
  File "/Users/hume/miniforge3/envs/spyder-env/lib/python3.12/site-packages/jupyter_client/manager.py", line 94, in wrapper
    self._ready.set_exception(e)
asyncio.exceptions.InvalidStateError: invalid state
```

## Versions

* Spyder version: 5.5.5  (conda)
* Python version: 3.12.4 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: macOS-14.5-arm64-arm-64bit

### Dependencies

```
# Mandatory:
applaunchservices >=0.3.0        :  0.3.0 (OK)
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.26.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.4 (OK)
jsonschema >=3.2.0               :  4.22.0 (OK)
keyring >=17.0.0                 :  25.2.1 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.7.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  6.0.0 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.2.5 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.11.0,<1.12.0           :  1.11.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.2 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.2.0 (OK)
setuptools >=49.6.0              :  70.1.1 (OK)
sphinx >=0.6.6                   :  7.3.7 (OK)
spyder_kernels >=2.5.2,<2.6.0    :  2.5.2 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.1 (OK)
zmq >=24.0.0                     :  26.0.3 (OK)

# Optional:
cython >=0.21                    :  3.0.10 (OK)
matplotlib >=3.0.0               :  3.8.4 (OK)
numpy >=1.7                      :  2.0.0 (OK)
pandas >=1.1.1                   :  2.2.2 (OK)
scipy >=0.17.0                   :  1.14.0 (OK)
sympy >=0.7.3                    :  1.12.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @humeaf, thanks for reporting. Quick question for you: did you connect the Spyder installed in `spyder-env` to another environment called `tf`?

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by humeaf** [comment]
I figured it out,

Thank you,
--hume.
Sent from my tiny-ish machine

On Jul 17, 2024, at 9:45 AM, Carlos Cordoba ***@***.***> wrote:

﻿

Closing due to lack of response.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
