### ISSUE TITLE
Spyder has encountered an internal problem

### ISSUE THREAD

**Issue by devsuperrk** [spyder-ide/spyder#22301]
### What steps will reproduce the problem?

I installed Spyder using Anaconda Navigater and launched it there. But I got this error.

Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\ksbek\anaconda3\envs\windtl\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000024F36602130> still has pending operation at deallocation, the process may crash
```

## Versions

* Spyder version: 5.5.1  (conda)
* Python version: 3.11.3 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.26.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.1 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  24.3.1 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.7.0 (OK)
paramiko >=2.4.0                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  6.0.0 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=2.5.0,<3.1              :  2.16.2 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.10.0,<1.11.0           :  1.10.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.2.2 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.1 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.3.0 (OK)
setuptools >=49.6.0              :  71.0.4 (OK)
sphinx >=0.6.6                   :  7.3.7 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.0 (OK)
textdistance >=4.2.0             :  4.2.1 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.1 (OK)
zmq >=22.1.0                     :  26.0.3 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  3.7.1 (OK)
numpy >=1.7                      :  1.25.2 (OK)
pandas >=1.1.1                   :  1.5.3 (OK)
scipy >=0.17.0                   :  1.11.1 (OK)
sympy >=0.7.3                    :  None (NOK)
```

**Comment by ccordoba12** [comment]
@devsuperrk, thanks for reporting. Please close Spyder and any other Python program you have open (like Jupyter or JupyterLab), open the Anaconda Prompt and run there

    conda install python=3.11.9

Then start Spyder again.

Let us know if that solves your problem..

**Comment by devsuperrk** [comment]
@ccordoba12 thanks for the reply. I updated the python version to 3.11.9 and reinstalled Spyder. But still the same error.

**Comment by ccordoba12** [comment]
Ok, please open the Anaconda Prompt, run the following commands there and post the out here:

    conda activate windtl
    conda list

**Comment by ccordoba12** [comment]
Closing due to lack of response.
