### ISSUE TITLE
Spyder keeps crashing

### ISSUE THREAD

**Issue by mortuarybees** [spyder-ide/spyder#22314]
### What steps will reproduce the problem?

i installed backtrader on my computer terminal but can't open spyder without it crashing anymore

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/preferences/widgets/configdialog.py", line 142, in button_clicked
    configpage.apply_changes()
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/preferences/api.py", line 118, in apply_changes
    self.apply_callback()
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/maininterpreter/confpage.py", line 259, in perform_adjustments
    self.warn_python_compatibility(executable)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/maininterpreter/confpage.py", line 166, in warn_python_compatibility
    proc = programs.run_program(pyexec, args, env={})
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/utils/programs.py", line 259, in run_program
    raise ProgramError("Program %s was not found" % program)
spyder.utils.programs.ProgramError: Program myenv/bin/python was not found
```

## Versions

* Spyder version: 5.5.5 bef1bdcdc (standalone)
* Python version: 3.9.14 64-bit
* Qt version: 5.15.11
* PyQt5 version: 5.15.10
* Operating System: macOS-11.6-x86_64-i386-64bit

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.18.1 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.4 (OK)
jsonschema >=3.2.0               :  4.22.0 (OK)
keyring >=17.0.0                 :  25.2.1 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.6.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.8 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.2.3 (OK)
pylint_venv >=3.0.2              :  None (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.11.0,<1.12.0           :  1.11.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.2 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.2.0 (OK)
setuptools >=49.6.0              :  58.1.0 (OK)
sphinx >=0.6.6                   :  5.1.1 (OK)
spyder_kernels >=2.5.2,<2.6.0    :  2.5.2 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.1 (OK)
zmq >=24.0.0                     :  26.0.3 (OK)

# Optional:
cython >=0.21                    :  3.0.10 (OK)
matplotlib >=3.0.0               :  3.9.0 (OK)
numpy >=1.7                      :  1.26.4 (OK)
pandas >=1.1.1                   :  2.2.2 (OK)
scipy >=0.17.0                   :  1.13.1 (OK)
sympy >=0.7.3                    :  1.12.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @mortuarybees, thanks for reporting. Please go to the menu entry

    Tools > Reset to factory defaults

and restart Spyder after that. That should fix your problem.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
