### ISSUE TITLE
Error when creating postgress table

### ISSUE THREAD

**Issue by ZDraper12** [spyder-ide/spyder#22356]
### What steps will reproduce the problem?

OperationalError: (psycopg2.OperationalError) FATAL:  database "Fractal_Analysis" does not exist

(Background on this error at: https://sqlalche.me/e/14/e3q8)

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\zachary.draper\AppData\Local\anaconda3\envs\analysis\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 2164, in restart_kernel
    client.restart_kernel()
  File "C:\Users\zachary.draper\AppData\Local\anaconda3\envs\analysis\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 733, in restart_kernel
    if self._abort_kernel_restart():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zachary.draper\AppData\Local\anaconda3\envs\analysis\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 335, in _abort_kernel_restart
    if not self.has_spyder_kernels():
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zachary.draper\AppData\Local\anaconda3\envs\analysis\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 839, in has_spyder_kernels
    has_spyder_kernels = programs.is_module_installed(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zachary.draper\AppData\Local\anaconda3\envs\analysis\Lib\site-packages\spyder\utils\programs.py", line 947, in is_module_installed
    output = output and check_version(module_version, ver, symb)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zachary.draper\AppData\Local\anaconda3\envs\analysis\Lib\site-packages\spyder\utils\programs.py", line 822, in check_version
    return parse(actver) >= parse(version)
           ^^^^^^^^^^^^^
  File "C:\Users\zachary.draper\AppData\Local\anaconda3\envs\analysis\Lib\site-packages\packaging\version.py", line 56, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\zachary.draper\AppData\Local\anaconda3\envs\analysis\Lib\site-packages\packaging\version.py", line 202, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: ''
```

## Versions

* Spyder version: 5.5.5  (conda)
* Python version: 3.11.8 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.11
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.26.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.1.0 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  25.3.0 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.8.0 (OK)
paramiko >=2.4.0                 :  3.4.1 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  6.0.0 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.2.6 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.11.0,<1.12.0           :  1.11.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.2 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.3.0 (OK)
setuptools >=49.6.0              :  68.2.2 (OK)
sphinx >=0.6.6                   :  8.0.2 (OK)
spyder_kernels >=2.5.2,<2.6.0    :  2.5.2 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.2 (OK)
zmq >=24.0.0                     :  26.1.0 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  None (NOK)
numpy >=1.7                      :  None (OK)
pandas >=1.1.1                   :  None (OK)
scipy >=0.17.0                   :  None (NOK)
sympy >=0.7.3                    :  None (NOK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at C:\Users\zachary.draper\AppData\Local\anaconda3\envs\analysis:
#
# Name                    Version                   Build  Channel
alabaster                 1.0.0                    pypi_0    pypi
arrow                     1.3.0                    pypi_0    pypi
astroid                   3.2.4                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
atomicwrites              1.4.1                    pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
autopep8                  2.0.4                    pypi_0    pypi
babel                     2.16.0                   pypi_0    pypi
backports-tarfile         1.2.0                    pypi_0    pypi
bcrypt                    4.2.0                    pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
binaryornot               0.4.4                    pypi_0    pypi
black                     24.8.0                   pypi_0    pypi
bleach                    6.1.0                    pypi_0    pypi
certifi                   2024.7.4                 pypi_0    pypi
cffi                      1.17.0                   pypi_0    pypi
chardet                   5.2.0                    pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               3.0.0                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
comm                      0.2.2                    pypi_0    pypi
cookiecutter              2.6.0                    pypi_0    pypi
cryptography              43.0.0                   pypi_0    pypi
debugpy                   1.8.5                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
diff-match-patch          20230430                 pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
docstring-to-markdown     0.15                     pypi_0    pypi
docutils                  0.21.2                   pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
fastjsonschema            2.20.0                   pypi_0    pypi
flake8                    7.0.0                    pypi_0    pypi
greenlet                  3.0.1           py311hd77b12b_0  
idna                      3.7                      pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        8.2.0                    pypi_0    pypi
inflection                0.5.1                    pypi_0    pypi
intervaltree              3.1.0                    pypi_0    pypi
ipykernel                 6.29.5                   pypi_0    pypi
ipython                   8.26.0                   pypi_0    pypi
isort                     5.13.2                   pypi_0    pypi
jaraco-classes            3.4.0                    pypi_0    pypi
jaraco-context            5.3.0                    pypi_0    pypi
jaraco-functools          4.0.2                    pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jellyfish                 1.1.0                    pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jupyter-client            8.6.2                    pypi_0    pypi
jupyter-core              5.7.2                    pypi_0    pypi
jupyterlab-pygments       0.3.0                    pypi_0    pypi
keyring                   25.3.0                   pypi_0    pypi
krb5                      1.21.2                        1    esri
libpq                     12.17                h906ac69_1    esri
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
mccabe                    0.7.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mistune                   3.0.2                    pypi_0    pypi
more-itertools            10.4.0                   pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
nbclient                  0.10.0                   pypi_0    pypi
nbconvert                 7.16.4                   pypi_0    pypi
nbformat                  5.10.4                   pypi_0    pypi
nest-asyncio              1.6.0                    pypi_0    pypi
numpy                     2.0.1                    pypi_0    pypi
numpydoc                  1.8.0                    pypi_0    pypi
openssl                   3.0.13                        0    esri
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
pandocfilters             1.5.1                    pypi_0    pypi
paramiko                  3.4.1                    pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
pathspec                  0.12.1                   pypi_0    pypi
pexpect                   4.9.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pip                       23.3.2                  py311_0    esri
platformdirs              4.2.2                    pypi_0    pypi
pluggy                    1.5.0                    pypi_0    pypi
prompt-toolkit            3.0.47                   pypi_0    pypi
psutil                    6.0.0                    pypi_0    pypi
psycopg2                  2.9.9           py311h2bbff1b_0  
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.3                    pypi_0    pypi
pycodestyle               2.11.1                   pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pydocstyle                6.3.0                    pypi_0    pypi
pyflakes                  3.2.0                    pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pylint                    3.2.6                    pypi_0    pypi
pylint-venv               3.0.3                    pypi_0    pypi
pyls-spyder               0.4.0                    pypi_0    pypi
pynacl                    1.5.0                    pypi_0    pypi
pyqt5                     5.15.11                  pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.15.0                  pypi_0    pypi
pyqtwebengine             5.15.7                   pypi_0    pypi
pyqtwebengine-qt5         5.15.2                   pypi_0    pypi
python                    3.11.8                        5    esri
python-dateutil           2.9.0.post0              pypi_0    pypi
python-lsp-black          2.0.0                    pypi_0    pypi
python-lsp-jsonrpc        1.1.2                    pypi_0    pypi
python-lsp-server         1.11.0                   pypi_0    pypi
python-slugify            8.0.4                    pypi_0    pypi
pytoolconfig              1.3.1                    pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pywin32                   306                      pypi_0    pypi
pywin32-ctypes            0.2.3                    pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
pyzmq                     26.1.0                   pypi_0    pypi
qdarkstyle                3.2.3                    pypi_0    pypi
qstylizer                 0.2.3                    pypi_0    pypi
qtawesome                 1.3.1                    pypi_0    pypi
qtconsole                 5.5.2                    pypi_0    pypi
qtpy                      2.4.1                    pypi_0    pypi
referencing               0.35.1                   pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
rich                      13.7.1                   pypi_0    pypi
rope                      1.13.0                   pypi_0    pypi
rpds-py                   0.20.0                   pypi_0    pypi
rtree                     1.3.0                    pypi_0    pypi
setuptools                68.2.2                  py311_0    esri
six                       1.16.0                   pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
soupsieve                 2.6                      pypi_0    pypi
sphinx                    8.0.2                    pypi_0    pypi
sphinxcontrib-applehelp   2.0.0                    pypi_0    pypi
sphinxcontrib-devhelp     2.0.0                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.1.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      2.0.0                    pypi_0    pypi
sphinxcontrib-serializinghtml 2.0.0                    pypi_0    pypi
spyder                    5.5.5                    pypi_0    pypi
spyder-kernels            2.5.2                    pypi_0    pypi
sqlalchemy                1.4.51          py311h2bbff1b_0  
sqlite                    3.45.1                        0    esri
stack-data                0.6.3                    pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
text-unidecode            1.3                      pypi_0    pypi
textdistance              4.6.3                    pypi_0    pypi
three-merge               0.1.1                    pypi_0    pypi
tinycss2                  1.3.0                    pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
tomlkit                   0.13.2                   pypi_0    pypi
tornado                   6.4.1                    pypi_0    pypi
tqdm                      4.66.5                   pypi_0    pypi
traitlets                 5.14.3                   pypi_0    pypi
types-python-dateutil     2.9.0.20240316           pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
ujson                     5.10.0                   pypi_0    pypi
urllib3                   2.2.2                    pypi_0    pypi
vc                        14.2                 h21ff451_1  
vs2015_runtime            14.27.29016          h5e58377_2    esri
watchdog                  4.0.2                    pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
whatthepatch              1.0.6                    pypi_0    pypi
wheel                     0.43.0          py311haa95532_0  
yapf                      0.40.2                   pypi_0    pypi
zipp                      3.20.0                   pypi_0    pypi
zlib                      1.3.1                         1    esri
zlib-ng                   2.1.6                         0    esri

```
</details>

**Comment by ccordoba12** [comment]
Hey @ZDraper12, thanks for reporting. Quick question for you: did you connect Spyder to another environment in `Preferences > Python interpreter`?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
