### ISSUE TITLE
Spyder consistent  Segmentation fault and crash

### ISSUE THREAD

**Issue by shimakazexkaki** [spyder-ide/spyder#22410]
### What steps will reproduce the problem?

Open spyder and then this pops out, sometimes spyder crash immediately, sometimes it opens, can't find the problem

[SpyderKernelApp] CRITICAL | Bad config encountered during initialization: The 'prefilter_manager' trait of an AssignmentChecker instance expected a PrefilterManager or None, not the Instance at '0x7f0b47512490'.

Traceback (most recent call last):
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_cython_wrapper.py", line 4, in <module>
    from _pydevd_bundle_ext import pydevd_cython as mod
ModuleNotFoundError: No module named '_pydevd_bundle_ext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named '_pydevd_bundle._pydevd_bundle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/spyder_kernels/console/__main__.py", line 24, in <module>
    start.main()
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/spyder_kernels/console/start.py", line 295, in main
    from ipykernel.kernelapp import IPKernelApp
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 42, in <module>
    from .ipkernel import IPythonKernel
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 38, in <module>
    from .debugger import Debugger
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/ipykernel/debugger.py", line 23, in <module>
    from debugpy.server import api  # noqa
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/debugpy/server/__init__.py", line 9, in <module>
    import debugpy._vendored.force_pydevd  # noqa
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/debugpy/_vendored/force_pydevd.py", line 54, in <module>
    'pydevd',
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/debugpy/_vendored/__init__.py", line 128, in preimport
    import_module(name)
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 47, in <module>
    from _pydev_bundle.pydev_console_utils import DebugConsoleStdIn
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/pydev_console_utils.py", line 6, in <module>
    from _pydevd_bundle import pydevd_vars
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 13, in <module>
    from _pydevd_bundle.pydevd_thread_lifecycle import resume_threads, mark_thread_suspended, suspend_all_threads
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_thread_lifecycle.py", line 2, in <module>
    from _pydevd_bundle.pydevd_additional_thread_info import set_additional_thread_info
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_additional_thread_info.py", line 16, in <module>
    from _pydevd_bundle.pydevd_cython_wrapper import PyDBAdditionalThreadInfo, set_additional_thread_info, _set_additional_thread_info_lock
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_cython_wrapper.py", line 7, in <module>
    from _pydevd_bundle import pydevd_cython as mod
  File "_pydevd_bundle/pydevd_cython.pyx", line 151, in init _pydevd_bundle.pydevd_cython
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 152, in __exit__
  File "<frozen importlib._bootstrap>", line 105, in release
AttributeError: 'int' object has no attribute 'lock'
Traceback (most recent call last):
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_cython_wrapper.py", line 4, in <module>
    from _pydevd_bundle_ext import pydevd_cython as mod
ModuleNotFoundError: No module named '_pydevd_bundle_ext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named '_pydevd_bundle._pydevd_bundle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/spyder_kernels/console/__main__.py", line 24, in <module>
    start.main()
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/spyder_kernels/console/start.py", line 295, in main
    from ipykernel.kernelapp import IPKernelApp
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 42, in <module>
    from .ipkernel import IPythonKernel
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 38, in <module>
    from .debugger import Debugger
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/ipykernel/debugger.py", line 23, in <module>
    from debugpy.server import api  # noqa
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/debugpy/server/__init__.py", line 9, in <module>
    import debugpy._vendored.force_pydevd  # noqa
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/debugpy/_vendored/force_pydevd.py", line 54, in <module>
    'pydevd',
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/debugpy/_vendored/__init__.py", line 128, in preimport
    import_module(name)
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 47, in <module>
    from _pydev_bundle.pydev_console_utils import DebugConsoleStdIn
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/pydev_console_utils.py", line 6, in <module>
    from _pydevd_bundle import pydevd_vars
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 13, in <module>
    from _pydevd_bundle.pydevd_thread_lifecycle import resume_threads, mark_thread_suspended, suspend_all_threads
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_thread_lifecycle.py", line 2, in <module>
    from _pydevd_bundle.pydevd_additional_thread_info import set_additional_thread_info
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_additional_thread_info.py", line 16, in <module>
    from _pydevd_bundle.pydevd_cython_wrapper import PyDBAdditionalThreadInfo, set_additional_thread_info, _set_additional_thread_info_lock
  File "/home/lab688/work/anaconda3/envs/matlab/lib/python3.7/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_cython_wrapper.py", line 7, in <module>
    from _pydevd_bundle import pydevd_cython as mod
  File "_pydevd_bundle/pydevd_cython.pyx", line 151, in init _pydevd_bundle.pydevd_cython
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 152, in __exit__
  File "<frozen importlib._bootstrap>", line 105, in release
AttributeError: 'int' object has no attribute 'lock'

## Versions

* Spyder version: 5.2.2 
* Python version: 3.7.13
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 5.15.0-86-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.11.2 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.7.4 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.3.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  25.0.2 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.1.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by dalthviz** [comment]
Hi @shimakazexkaki thank you for the report! Could it be possible for you to run Spyder with the `safe-mode` flag and check if the crash persists? So running from an Anaconda prompt with the env you have Spyder installed activated something like `spyder --safe-mode`. Let us know!

**Comment by dalthviz** [comment]
Closing due to lack of response
