### ISSUE TITLE
Spyder 5.5.1

### ISSUE THREAD

**Issue by Divya31-tech** [spyder-ide/spyder#22426]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I am having the following error on Spyder 5.5.1. I reinstalled Anaconda and am still having the same issue. Would anyone be able to help?

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)
The error is:

Traceback (most recent call last):
File "C:\Users\cont9209\AppData\Local\anaconda3\Lib\site‑packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 2142, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle,
File "C:\Users\cont9209\AppData\Local\anaconda3\Lib\site‑packages\jupyter_core\utils\__init__.py", line 165, in wrapped
return loop.run_until_complete(inner)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\cont9209\AppData\Local\anaconda3\Lib\asyncio\base_events.py", line 687, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File "C:\Users\cont9209\AppData\Local\anaconda3\Lib\site‑packages\jupyter_client\manager.py", line 96, in wrapper
raise e
File "C:\Users\cont9209\AppData\Local\anaconda3\Lib\site‑packages\jupyter_client\manager.py", line 87, in wrapper
out = await method(self, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\cont9209\AppData\Local\anaconda3\Lib\site‑packages\jupyter_client\manager.py", line 435, in _async_start_kernel
kernel_cmd, kw = await self._async_pre_start_kernel(**kw)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\cont9209\AppData\Local\anaconda3\Lib\site‑packages\jupyter_client\manager.py", line 400, in _async_pre_start_kernel
kw = await self.provisioner.pre_launch(**kw)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\cont9209\AppData\Local\anaconda3\Lib\site‑packages\jupyter_client\provisioning\local_provisioner.py", line 193, in pre_launch
km.write_connection_file(jupyter_session=jupyter_session)
File "C:\Users\cont9209\AppData\Local\anaconda3\Lib\site‑packages\jupyter_client\connect.py", line 500, in write_connection_file
self.connection_file, cfg = write_connection_file(
^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\cont9209\AppData\Local\anaconda3\Lib\site‑packages\jupyter_client\connect.py", line 156, in write_connection_file
with secure_write(fname) as f:
File "C:\Users\cont9209\AppData\Local\anaconda3\Lib\contextlib.py", line 137, in __enter__
return next(self.gen)
^^^^^^^^^^^^^^
File "C:\Users\cont9209\AppData\Local\anaconda3\Lib\site‑packages\jupyter_core\paths.py", line 990, in secure_write
fd = os.open(fname, open_flag, 0o0600)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\cont9209\\AppData\\Roaming\\jupyter\\runtime\\kernel𔂳e18b0b36252.json'

## Versions

* Spyder version: 5.5.1
* Python version: 3.12
* Qt version: NA
* PyQt version: NA
* Operating System name/version: Windows

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @Divya31-tech, thanks for report. This problem is generated because your user doesn't have permissions to write in this directory:

    C:\Users\cont9209\AppData\Roaming\jupyter

Please go to that directory with the Windows explorer and make sure that you can create files inside it. For that you can follow the instructions found in this page:

https://answers.microsoft.com/en-us/windows/forum/all/how-do-i-change-folder-and-file-permissions/465f2b42-63dd-4486-8dd1-c870290efeed

Let us know if it works for you!

**Comment by ccordoba12** [comment]
Closing due to lack of response.
