### ISSUE TITLE
6.0.0: TypeError: KernelComm._get_call_return_value() missing 1 required positional argument: 'comm_id'

### ISSUE THREAD

**Issue by yurivict** [spyder-ide/spyder#22449]
## Problem Description

spyder-6.0.0 fails after start:
```
$ spyder
fromIccProfile: failed minimal tag size sanity
Traceback (most recent call last):
  File "/usr/local/bin/spyder", line 33, in <module>
    sys.exit(load_entry_point('spyder==5.5.5', 'gui_scripts', 'spyder')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/spyder/app/start.py", line 256, in main
    mainwindow.main(options, args)
  File "/usr/local/lib/python3.11/site-packages/spyder/app/mainwindow.py", line 1847, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/spyder/app/utils.py", line 300, in create_window
    main.post_visible_setup()
  File "/usr/local/lib/python3.11/site-packages/spyder/app/mainwindow.py", line 1050, in post_visible_setup
    plugin.on_mainwindow_visible()
  File "/usr/local/lib/python3.11/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 401, in on_mainwindow_visible
    self.create_new_client(give_focus=False)
  File "/usr/local/lib/python3.11/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 538, in create_new_client
    self.get_widget().create_new_client(
  File "/usr/local/lib/python3.11/site-packages/spyder/plugins/ipythonconsole/widgets/main_widget.py", line 1525, in create_new_client
    self.register_client(client, give_focus=give_focus)
  File "/usr/local/lib/python3.11/site-packages/spyder/plugins/ipythonconsole/widgets/main_widget.py", line 1851, in register_client
    client.configure_shellwidget(give_focus=give_focus)
  File "/usr/local/lib/python3.11/site-packages/spyder/plugins/ipythonconsole/widgets/client.py", line 477, in configure_shellwidget
    self.shellwidget.call_kernel()._send_comm_config()
  File "/usr/local/lib/python3.11/site-packages/spyder_kernels/comms/commbase.py", line 611, in __call__
    return self._comms_wrapper._get_call_return_value(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: KernelComm._get_call_return_value() missing 1 required positional argument: 'comm_id'
Segmentation fault
```

### What steps reproduce the problem?

1. build
2. install
3. run

## Versions

* Spyder version: 5.5.5
* Python version: 3.11
* Qt version: 5.15.17
* PyQt version: 5.15.17
* Operating System name/version: FreeBSD 14.1
spyder_kernels-3.0.0

**Comment by ccordoba12** [comment]
Hey @yurivict, thanks for reporting. Unfortunately, we don't support any BSD variant, so it's up to you debug and solve this error.

We're really sorry about that but we're a small team and only have time to support the main OSes, However, given this line in your traceback:

    sys.exit(load_entry_point('spyder==5.5.5', 'gui_scripts', 'spyder')())

it seems you're mixing Spyder 5 and 6 packages or modules somehow. Hope that's helpful.

**Comment by yurivict** [comment]
@ccordoba12 

This has nothing to do whatsoever with BSD. This has to do with the bug in Spyder.
Why did you close this report?

**Comment by ccordoba12** [comment]
It seems you added this bit to the OP after I posted my comment:

> /usr/local/lib/python3.11/site-packages/spyder/plugins/ipythonconsole/comms/kernelcomm.py was installed by > spyder-5.5.5 and it has a function like this:
>
>    def _get_call_return_value(self, call_dict, call_data, comm_id):
>
> /usr/local/lib/python3.11/site-packages/spyder_kernels/comms/commbase.py was installed by py311-spyder-kernels-3.0.0 and it contains the call:
>
>       return self._comms_wrapper._get_call_return_value(
>           call_dict, self._comm_id)

This is no bug, it's an problem on your side. That's because Spyder 5 is only compatible with Spyder-kernels version 2, not 3. And that's even more fine-grained: Spyder 5.5.x is only compatible with Spyder-kernels 2.5.x, 5.4.x with 2.4.x, etc.

As I said before, you're mixing incompatible versions, hence the error. But that's not an issue on our side.
