### ISSUE TITLE
ValueError: numpy.dtype has the wrong size, try recompiling

### ISSUE THREAD

**Issue by yuxiaorui** [spyder-ide/spyder#2244]
root@bogon:~/Desktop# spyder
Traceback (most recent call last):
  File "/usr/local/bin/spyder", line 4, in <module>
    __import__('pkg_resources').run_script('spyder==2.3.3', 'spyder')
  File "/usr/local/lib/python2.7/dist-packages/setuptools-14.0-py2.7.egg/pkg_resources/__init__.py", line 698, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-14.0-py2.7.egg/pkg_resources/__init__.py", line 1616, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/spyder-2.3.3-py2.7.egg/EGG-INFO/scripts/spyder", line 2, in <module>
    from spyderlib import start_app
  File "/usr/local/lib/python2.7/dist-packages/spyder-2.3.3-py2.7.egg/spyderlib/start_app.py", line 14, in <module>
    from spyderlib.config import CONF
  File "/usr/local/lib/python2.7/dist-packages/spyder-2.3.3-py2.7.egg/spyderlib/config.py", line 22, in <module>
    from spyderlib.utils import iofuncs, codeanalysis
  File "/usr/local/lib/python2.7/dist-packages/spyder-2.3.3-py2.7.egg/spyderlib/utils/iofuncs.py", line 158, in <module>
    import scipy.io as spio
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.15.1-py2.7-linux-x86_64.egg/scipy/io/__init__.py", line 85, in <module>
    from .matlab import loadmat, savemat, whosmat, byteordercodes
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.15.1-py2.7-linux-x86_64.egg/scipy/io/matlab/__init__.py", line 13, in <module>
    from .mio import loadmat, savemat, whosmat
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.15.1-py2.7-linux-x86_64.egg/scipy/io/matlab/mio.py", line 12, in <module>
    from .miobase import get_matfile_version, docfiller
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.15.1-py2.7-linux-x86_64.egg/scipy/io/matlab/miobase.py", line 22, in <module>
    from scipy.misc import doccer
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.15.1-py2.7-linux-x86_64.egg/scipy/misc/__init__.py", line 47, in <module>
    from scipy.special import comb, factorial, factorial2, factorialk
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.15.1-py2.7-linux-x86_64.egg/scipy/special/__init__.py", line 586, in <module>
    from ._ufuncs import *
  File "__init__.pxd", line 155, in init scipy.special._ufuncs (scipy/special/_ufuncs.c:27042)
ValueError: numpy.dtype has the wrong size, try recompiling

**Comment by ccordoba12** [comment]
This is not a Spyder error, as can be seen from the entire traceback. It seems you have compiled numpy and scipy by hand, so you have to figure it our what you've done wrong.

I'm sorry but we don't have time to help you with that. I'd recommend you to use [Anaconda](http://continuum.io/downloads.html) which won't give you these problems.
