### ISSUE TITLE
Install librosa with pip

### ISSUE THREAD

**Issue by ncva73** [spyder-ide/spyder#22481]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
pip install librosa
Traceback (most recent call last):
  File "C:\Users\ncva7\AppData\Local\spyder-6\envs\spyder-runtime\Lib\code.py", line 63, in runsource
    code = self.compile(source, filename, symbol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ncva7\AppData\Local\spyder-6\envs\spyder-runtime\Lib\codeop.py", line 160, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ncva7\AppData\Local\spyder-6\envs\spyder-runtime\Lib\codeop.py", line 73, in _maybe_compile
    return compiler(source, filename, symbol, incomplete_input=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ncva7\AppData\Local\spyder-6\envs\spyder-runtime\Lib\codeop.py", line 125, in __call__
    codeob = compile(source, filename, symbol, flags, True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<console>", line 2
    pip install librosa
        ^^^^^^^
SyntaxError: invalid syntax
>>>

**Comment by ccordoba12** [comment]
Hey @ncva73, thanks for reporting. It's not possible to use pip nor conda to install packages in our installers.

Instead, you need to install a different Python distribution and install the packages you need in it. That's explained in detail in our documentation:

http://docs.spyder-ide.org/current/faq.html#using-packages-installer
