### ISSUE TITLE
Branch change with project open

### ISSUE THREAD

**Issue by dbrose** [spyder-ide/spyder#22495]
### What steps will reproduce the problem?

Changed git branches with project open. Details of error look like they're related to break points in a file that's been replaced when I changed branches, and Spyder wasn't expecting it and didn't know how to handle it.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\rosed2\AppData\Local\anaconda3\envs\py312\Lib\site-packages\spyder\plugins\editor\utils\debugger.py", line 160, in breakpoints_changed
    breakpoints = self.get_breakpoints()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rosed2\AppData\Local\anaconda3\envs\py312\Lib\site-packages\spyder\plugins\editor\utils\debugger.py", line 131, in get_breakpoints
    if data and data.breakpoint:
                ^^^^^^^^^^^^^^^
AttributeError: 'QTextBlockUserData' object has no attribute 'breakpoint'
```

## Versions

* Spyder version: 5.5.5  (conda)
* Python version: 3.12.5 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                     :  1.4.1 (OK)
chardet >=2.0.0                          :  5.2.0 (OK)
cloudpickle >=0.5.0                      :  3.0.0 (OK)
cookiecutter >=1.6.0                     :  2.6.0 (OK)
diff_match_patch >=20181111              :  20230430 (OK)
intervaltree >=3.0.2                     :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1         :  8.26.0 (OK)
jedi >=0.17.2,<0.20.0                    :  0.19.1 (OK)
jellyfish >=0.7                          :  1.1.0 (OK)
jsonschema >=3.2.0                       :  4.23.0 (OK)
keyring >=17.0.0                         :  25.3.0 (OK)
nbconvert >=4.0                          :  7.16.4 (OK)
numpydoc >=0.6.0                         :  1.8.0 (OK)
paramiko >=2.4.0                         :  3.4.1 (OK)
parso >=0.7.0,<0.9.0                     :  0.8.4 (OK)
pexpect >=4.4.0                          :  4.9.0 (OK)
pickleshare >=0.4                        :  0.7.5 (OK)
psutil >=5.3                             :  6.0.0 (OK)
pygments >=2.0                           :  2.18.0 (OK)
pylint >=3.1,<4                          :  3.2.6 (OK)
pylint_venv >=3.0.2                      :  3.0.3 (OK)
pyls_spyder >=0.4.0                      :  0.4.0 (OK)
pylsp >=1.11.0,<1.12.0                   :  1.11.0 (OK)
pylsp_black >=2.0.0,<3.0.0               :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0                :  3.2.3 (OK)
qstylizer >=0.2.2                        :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0                 :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0                 :  5.5.2 (OK)
qtpy >=2.1.0                             :  2.4.1 (OK)
rtree >=0.9.7                            :  1.3.0 (OK)
setuptools >=49.6.0                      :  72.1.0 (OK)
sphinx >=0.6.6                           :  8.0.2 (OK)
spyder_kernels >=2.5.2,<2.6.0            :  2.5.2 (OK)
textdistance >=4.2.0                     :  4.6.2 (OK)
three_merge >=0.1.1                      :  0.1.1 (OK)
watchdog >=0.10.3                        :  4.0.1 (OK)
zmq >=24.0.0                             :  26.1.0 (OK)

# Optional:
cython >=0.21                            :  None (NOK)
matplotlib >=3.0.0                       :  3.9.1 (OK)
numpy >=1.7                              :  1.26.4 (OK)
pandas >=1.1.1                           :  2.2.2 (OK)
scipy >=0.17.0                           :  1.14.0 (OK)
sympy >=0.7.3                            :  1.13.2 (OK)

# Spyder plugins:
spyder_line_profiler.spyder.plugin 0.3.2 :  0.3.2 (OK)
spyder_notebook.notebookplugin 0.5.1     :  0.5.1 (OK)
spyder_terminal.terminalplugin 1.2.2     :  1.2.2 (OK)
spyder_unittest.unittestplugin 0.6.0     :  0.6.0 (OK)
```

**Comment by dalthviz** [comment]
Hi @dbrose sorry for such a late response and thank you for the report! Did a quick check for this with Spyder 6.0.3 from the Windows installer but I was able to change branches with an active project while having files with breakpoints set 🤔 

Could it be possible for you to check if this is still an issue on your side even after updating to the latest Spyder release (6.0.3) ?

Let us know!
