### ISSUE TITLE
Error while changing the layout and a plugin was closed while undocked

### ISSUE THREAD

**Issue by rassul** [spyder-ide/spyder#22494]
### What steps will reproduce the problem?

I tried to set the layout to default. Originally wanted to create my workspace layout by positioning the panes with a snip in but I was not successful.

### Traceback
```python-traceback

Traceback (most recent call last):
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\layout\plugin.py", line 484, in quick_layout_switch
    settings = self.load_window_settings(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\layout\plugin.py", line 546, in load_window_settings
    window_size = get_func(prefix + 'size', section=section)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\api\plugins\new_api.py", line 510, in get_conf
    return self._conf.get(section, option, default, secure=secure)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\config\manager.py", line 519, in get
    value = config.get(
            ^^^^^^^^^^^
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\config\user.py", line 943, in get
    return config.get(section=section, option=option, default=default)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\config\user.py", line 498, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'layout_Spyder Default Layout/size' in section: 'quick_layouts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\layout\container.py", line 191, in <lambda>
    return lambda: self.quick_layout_switch(i)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\layout\container.py", line 430, in quick_layout_switch
    possible_current_layout = self._plugin.quick_layout_switch(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\layout\plugin.py", line 510, in quick_layout_switch
    layout.set_main_window_layout(
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\layout\api.py", line 408, in set_main_window_layout
    base_plugin.toggle_view(True)
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\api\plugins\new_api.py", line 1146, in toggle_view
    self.get_widget().toggle_view(value)
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\api\widgets\main_widget.py", line 954, in toggle_view
    self.create_window()
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\api\widgets\main_widget.py", line 725, in create_window
    self.windowwidget.sig_closed.connect(self.close_window)
TypeError: connect() failed between SpyderWindowWidget.sig_closed[] and close_window()
Traceback (most recent call last):
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\workingdirectory\plugin.py", line 78, in <lambda>
    lambda path, plugin=None: self.chdir(path, plugin))
                              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\workingdirectory\plugin.py", line 184, in chdir
    ipyconsole.set_current_client_working_directory(directory)
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 955, in set_current_client_working_directory
    self.get_widget().set_current_client_working_directory(directory)
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 2436, in set_current_client_working_directory
    shellwidget = self.get_current_shellwidget()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1669, in get_current_shellwidget
    client = self.get_current_client()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1663, in get_current_client
    client = self.tabwidget.currentWidget()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: wrapped C/C++ object of type Tabs has been deleted
Traceback (most recent call last):
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 955, in set_current_client_working_directory
    self.get_widget().set_current_client_working_directory(directory)
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 2436, in set_current_client_working_directory
    shellwidget = self.get_current_shellwidget()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1669, in get_current_shellwidget
    client = self.get_current_client()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1663, in get_current_client
    client = self.tabwidget.currentWidget()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: wrapped C/C++ object of type Tabs has been deleted
Traceback (most recent call last):
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\workingdirectory\plugin.py", line 78, in <lambda>
    lambda path, plugin=None: self.chdir(path, plugin))
                              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\workingdirectory\plugin.py", line 184, in chdir
    ipyconsole.set_current_client_working_directory(directory)
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 955, in set_current_client_working_directory
    self.get_widget().set_current_client_working_directory(directory)
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 2436, in set_current_client_working_directory
    shellwidget = self.get_current_shellwidget()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1669, in get_current_shellwidget
    client = self.get_current_client()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1663, in get_current_client
    client = self.tabwidget.currentWidget()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: wrapped C/C++ object of type Tabs has been deleted
Traceback (most recent call last):
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 955, in set_current_client_working_directory
    self.get_widget().set_current_client_working_directory(directory)
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 2436, in set_current_client_working_directory
    shellwidget = self.get_current_shellwidget()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1669, in get_current_shellwidget
    client = self.get_current_client()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rassu\utils\spyder\envs\spyder-runtime\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1663, in get_current_client
    client = self.tabwidget.currentWidget()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: wrapped C/C++ object of type Tabs has been deleted
```

## Versions

* Spyder version: 6.0.0rc2  (standalone)
* Python version: 3.11.9 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.22631-SP0

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                    :  3.10.5 (OK)
asyncssh >=2.14.0,<3.0.0           :  2.16.0 (OK)
atomicwrites >=1.2.0               :  1.4.1 (OK)
chardet >=2.0.0                    :  5.2.0 (OK)
cloudpickle >=0.5.0                :  3.0.0 (OK)
cookiecutter >=1.6.0               :  2.6.0 (OK)
diff_match_patch >=20181111        :  20230430 (OK)
github >=2.3.0                     :  2.4.0 (OK)
importlib_metadata >=4.6.0         :  8.4.0 (OK)
intervaltree >=3.0.2               :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1   :  8.27.0 (OK)
jedi >=0.17.2,<0.20.0              :  0.19.1 (OK)
jellyfish >=0.7                    :  1.1.0 (OK)
jsonschema >=3.2.0                 :  4.23.0 (OK)
keyring >=17.0.0                   :  25.3.0 (OK)
nbconvert >=4.0                    :  7.16.4 (OK)
numpydoc >=0.6.0                   :  1.8.0 (OK)
parso >=0.7.0,<0.9.0               :  0.8.4 (OK)
pexpect >=4.4.0                    :  4.9.0 (OK)
pickleshare >=0.4                  :  0.7.5 (OK)
psutil >=5.3                       :  6.0.0 (OK)
pygments >=2.0                     :  2.18.0 (OK)
pylint >=3.1,<4                    :  3.2.7 (OK)
pylint_venv >=3.0.2                :  3.0.3 (OK)
pyls_spyder >=0.4.0                :  0.4.0 (OK)
pylsp >=1.11.0,<1.12.0             :  1.11.0 (OK)
pylsp_black >=2.0.0,<3.0.0         :  2.0.0 (OK)
pyuca >=1.2                        :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0          :  3.2.3 (OK)
qstylizer >=0.2.2                  :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0           :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0           :  5.5.2 (OK)
qtpy >=2.4.0                       :  2.4.1 (OK)
rtree >=0.9.7                      :  1.3.0 (OK)
setuptools >=49.6.0                :  72.2.0 (OK)
sphinx >=0.6.6,<7.4.0              :  7.3.7 (OK)
spyder_kernels >=3.0.0b9,<3.0.0b10 :  3.0.0b9 (OK)
superqt >=0.6.2,<1.0.0             :  0.6.7 (OK)
textdistance >=4.2.0               :  4.6.2 (OK)
three_merge >=0.1.1                :  0.1.1 (OK)
watchdog >=0.10.3                  :  5.0.0 (OK)
yarl >=1.9.4                       :  1.9.7 (OK)
zmq >=24.0.0                       :  26.2.0 (OK)

# Optional:
cython >=0.21                      :  3.0.11 (OK)
matplotlib >=3.0.0                 :  3.9.2 (OK)
numpy >=1.7                        :  2.1.0 (OK)
pandas >=1.1.1                     :  2.2.2 (OK)
scipy >=0.17.0                     :  1.14.1 (OK)
sympy >=0.7.3                      :  1.13.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @rassul, thanks for reporting. I was able to reproduce this error and it'll be fixed in our next version (6.0.1), to be released next week.
