### ISSUE TITLE
When processing a large amount of data, the computer suddenly crashed and this report dialog box popped up.

### ISSUE THREAD

**Issue by JunTingLin** [spyder-ide/spyder#22573]
### What steps will reproduce the problem?

When processing a large amount of data, the computer suddenly crashed and this report dialog box popped up.

A crash occurs when executing this line `broker_transactions_grouped_short = broker_transactions_grouped[-100:]`

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\junting\anaconda3\envs\stock-analysis\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 105, in get_value
    timeout=CALL_KERNEL_TIMEOUT).get_value(name)
  File "C:\Users\junting\anaconda3\envs\stock-analysis\lib\site-packages\spyder_kernels\comms\commbase.py", line 557, in __call__
    return self._comms_wrapper._get_call_return_value(
  File "C:\Users\junting\anaconda3\envs\stock-analysis\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 224, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
  File "C:\Users\junting\anaconda3\envs\stock-analysis\lib\site-packages\spyder_kernels\comms\commbase.py", line 435, in _get_call_return_value
    self._wait_reply(call_id, call_name, timeout)
  File "C:\Users\junting\anaconda3\envs\stock-analysis\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 246, in _wait_reply
    self._wait(got_reply, self._sig_got_reply, timeout_msg, timeout)
  File "C:\Users\junting\anaconda3\envs\stock-analysis\lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 283, in _wait
    raise TimeoutError(timeout_msg)
TimeoutError: Timeout while waiting for {'9149f92be2ca4ed1988055e44b7c64fe': (True, None)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\junting\anaconda3\envs\stock-analysis\lib\site-packages\spyder\plugins\variableexplorer\widgets\main_widget.py", line 561, in copy
    self._current_editor.copy()
  File "C:\Users\junting\anaconda3\envs\stock-analysis\lib\site-packages\spyder\widgets\collectionseditor.py", line 1219, in copy
    obj = self.delegate.get_value(idx)
  File "C:\Users\junting\anaconda3\envs\stock-analysis\lib\site-packages\spyder\widgets\collectionseditor.py", line 1555, in get_value
    return self.parent().get_value(name)
  File "C:\Users\junting\anaconda3\envs\stock-analysis\lib\site-packages\spyder\widgets\collectionseditor.py", line 1614, in get_value
    value = self.shellwidget.get_value(name)
  File "C:\Users\junting\anaconda3\envs\stock-analysis\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 107, in get_value
    raise ValueError(msg % reason_big)
ValueError: <br><i>The variable is too big to be retrieved.</i><br><br><br><b>Note</b>: Please don't report this problem on Github, there's nothing to do about it.
```

## Versions

* Spyder version: 5.5.6  (conda)
* Python version: 3.10.14 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.22631-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
importlib_metadata >=4.6.0       :  8.4.0 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.27.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.1.0 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  23.5.0 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.8.0 (OK)
paramiko >=2.4.0                 :  3.4.1 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  6.0.0 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.2.7 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.2 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.3.0 (OK)
setuptools >=49.6.0              :  73.0.1 (OK)
sphinx >=0.6.6                   :  8.0.2 (OK)
spyder_kernels >=2.5.2,<2.6.0    :  2.5.2 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  5.0.1 (OK)
zmq >=24.0.0                     :  26.2.0 (OK)

# Optional:
cython >=0.21                    :  3.0.11 (OK)
matplotlib >=3.0.0               :  None (NOK)
numpy >=1.7                      :  1.26.4 (OK)
pandas >=1.1.1                   :  2.2.2 (OK)
scipy >=0.17.0                   :  None (NOK)
sympy >=0.7.3                    :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @JunTingLin, thanks for reporting. It seems that you were trying to copy a variable that is too big in the Variable Explorer. Could you confirm that?

In any case, we'll try to address this error in a future version.

**Comment by dalthviz** [comment]
Just in case, there are a couple of issues that could be related with this one: https://github.com/spyder-ide/spyder/issues/22121 https://github.com/spyder-ide/spyder/issues/22393

**Comment by ccordoba12** [comment]
You're right @dalthviz. Let's close everything in favor of #12913, which is the oldest issue.
