### ISSUE TITLE
An error occurred while starting the kernel

### ISSUE THREAD

**Issue by iffatebu** [spyder-ide/spyder#22581]
### What steps will reproduce the problem?

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last): File "C:\Users\iffat\anaconda3\envs\myenv\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\iffat\anaconda3\envs\myenv\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\__main__.py", line 24, in
start.main()
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\start.py", line 165, in main
from spyder_kernels.console.kernel import SpyderKernel
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\kernel.py", line 47, in
from spyder_kernels.utils.mpl import automatic_backend, MPL_BACKENDS_TO_SPYDER
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\spyder_kernels\utils\mpl.py", line 15, in
if is_module_installed('matplotlib_inline'):
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\spyder_kernels\utils\misc.py", line 22, in is_module_installed
mod = __import__(module_name)
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\matplotlib_inline\__init__.py", line 1, in
from . import backend_inline, config # noqa
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\matplotlib_inline\backend_inline.py", line 6, in
import matplotlib
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\matplotlib\__init__.py", line 109, in
from . import _api, _version, cbook, docstring, rcsetup
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\matplotlib\rcsetup.py", line 27, in
from matplotlib.colors import Colormap, is_color_like
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\matplotlib\colors.py", line 56, in
from matplotlib import _api, cbook, scale
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\matplotlib\scale.py", line 23, in
from matplotlib.ticker import (
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\matplotlib\ticker.py", line 136, in
from matplotlib import transforms as mtransforms
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\matplotlib\transforms.py", line 46, in
from matplotlib._path import (
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last): File "C:\Users\iffat\anaconda3\envs\myenv\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\iffat\anaconda3\envs\myenv\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\__main__.py", line 24, in
start.main()
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\start.py", line 192, in main
kernel.config = kernel_config()
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\start.py", line 96, in kernel_config
if is_module_installed('matplotlib'):
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\spyder_kernels\utils\misc.py", line 22, in is_module_installed
mod = __import__(module_name)
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\matplotlib\__init__.py", line 109, in
from . import _api, _version, cbook, docstring, rcsetup
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\matplotlib\rcsetup.py", line 27, in
from matplotlib.colors import Colormap, is_color_like
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\matplotlib\colors.py", line 56, in
from matplotlib import _api, cbook, scale
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\matplotlib\scale.py", line 23, in
from matplotlib.ticker import (
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\matplotlib\ticker.py", line 136, in
from matplotlib import transforms as mtransforms
File "C:\Users\iffat\anaconda3\envs\myenv\lib\site‑packages\matplotlib\transforms.py", line 46, in
from matplotlib._path import (
AttributeError: _ARRAY_API not found

### Traceback
```python-traceback

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\spyder\plugins\application\container.py", line 234, in _compute_dependencies
    dependencies.declare_dependencies()
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\spyder\dependencies.py", line 485, in declare_dependencies
    add(dep['modname'], dep['package_name'],
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\spyder\dependencies.py", line 416, in add
    DEPENDENCIES += [Dependency(modname, package_name, features,
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\spyder\dependencies.py", line 355, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\spyder\utils\programs.py", line 1004, in get_module_version
    mod = __import__(module_name)
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\matplotlib\__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\matplotlib\colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\matplotlib\scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\matplotlib\ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\matplotlib\transforms.py", line 46, in <module>
    from matplotlib._path import (
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\iffat\anaconda3\envs\myenv\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\iffat\anaconda3\envs\myenv\Scripts\spyder.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\spyder\app\start.py", line 285, in main
    mainwindow.main(options, args)
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\spyder\app\mainwindow.py", line 1425, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\spyder\app\utils.py", line 412, in create_window
    app.exec_()
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\spyder\plugins\application\container.py", line 221, in _set_dependencies
    self.dependencies_dialog.set_data(dependencies.DEPENDENCIES)
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\spyder\widgets\dependencies.py", line 182, in set_data
    self.treewidget.update_dependencies(dependencies)
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\spyder\widgets\dependencies.py", line 63, in update_dependencies
    if dependency.check():
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\spyder\dependencies.py", line 376, in check
    installed = programs.is_module_installed(
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\spyder\utils\programs.py", line 1050, in is_module_installed
    module_version = get_module_version(module_name)
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\spyder\utils\programs.py", line 1004, in get_module_version
    mod = __import__(module_name)
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\matplotlib\__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\matplotlib\colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\matplotlib\scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\matplotlib\ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "C:\Users\iffat\anaconda3\envs\myenv\lib\site-packages\matplotlib\transforms.py", line 46, in <module>
    from matplotlib._path import (
AttributeError: _ARRAY_API not found
```

## Versions

* Spyder version: 6.0.1  (conda)
* Python version: 3.9.19 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.11
* Operating System: Windows-10-10.0.22631-SP0

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.10.6 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.17.0 (OK)
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
github >=2.3.0                   :  2.4.0 (OK)
importlib_metadata >=4.6.0       :  8.5.0 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.18.1 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.1.0 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  25.4.1 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.8.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  6.0.0 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.3.1 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0         :  5.6.0 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.3.0 (OK)
setuptools >=49.6.0              :  72.1.0 (OK)
sphinx >=0.6.6                   :  7.4.7 (OK)
spyder_kernels >=3.0.0,<3.1.0    :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  5.0.2 (OK)
yarl >=1.9.4                     :  1.12.1 (OK)
zmq >=24.0.0                     :  26.2.0 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  None (NOK)
numpy >=1.7                      :  2.0.2 (OK)
pandas >=1.1.1                   :  None (NOK)
scipy >=0.17.0                   :  1.13.1 (OK)
sympy >=0.7.3                    :  1.13.3 (OK)
```

**Comment by ccordoba12** [comment]
Hey @iffatebu, thanks for reporting. It seems you installed some packages with pip in your `myenv` environment and now it's broken.

To fix this error, please remove that environment and recreate it again. Also, take care of installing everything with conda. That's important because conda and pip packages are binary incompatible, as described in [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs).

**Comment by iffatebu** [comment]
Thanks a lot, it worked.
