### ISSUE TITLE
ipython console does not start on Ubuntu 2404

### ISSUE THREAD

**Issue by 0x1orz** [spyder-ide/spyder#22603]
## Problem Description

I finished running `conda create -c conda-forge -n spyder-ide spyder numpy scipy pandas matplotlib sympy cython` on Ubuntu 2404, then started   sypder, while ipython console failed to work  and  throwed the error log as following, 
```
Traceback (most recent call last):
File "/opt/envs/spyder‑ide/lib/python3.12/site‑packages/spyder/plugins/ipythonconsole/widgets/main_widget.py", line 1719, in create_new_client
kernel_handler = self.get_cached_kernel(kernel_spec, cache=cache)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/envs/spyder‑ide/lib/python3.12/site‑packages/spyder/plugins/ipythonconsole/widgets/mixins.py", line 59, in get_cached_kernel
new_kernel_handler = KernelHandler.new_from_spec(kernel_spec)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/envs/spyder‑ide/lib/python3.12/site‑packages/spyder/plugins/ipythonconsole/utils/kernel_handler.py", line 393, in new_from_spec
kernel_manager.start_kernel(
File "/opt/envs/spyder‑ide/lib/python3.12/site‑packages/jupyter_core/utils/__init__.py", line 165, in wrapped
return loop.run_until_complete(inner)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/envs/spyder‑ide/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File "/opt/envs/spyder‑ide/lib/python3.12/site‑packages/jupyter_client/manager.py", line 96, in wrapper
raise e
File "/opt/envs/spyder‑ide/lib/python3.12/site‑packages/jupyter_client/manager.py", line 87, in wrapper
out = await method(self, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/envs/spyder‑ide/lib/python3.12/site‑packages/jupyter_client/manager.py", line 435, in _async_start_kernel
kernel_cmd, kw = await self._async_pre_start_kernel(**kw)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/envs/spyder‑ide/lib/python3.12/site‑packages/jupyter_client/manager.py", line 400, in _async_pre_start_kernel
kw = await self.provisioner.pre_launch(**kw)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/envs/spyder‑ide/lib/python3.12/site‑packages/jupyter_client/provisioning/local_provisioner.py", line 198, in pre_launch
kernel_cmd = km.format_kernel_cmd(
^^^^^^^^^^^^^^^^^^^^^
File "/opt/envs/spyder‑ide/lib/python3.12/site‑packages/jupyter_client/manager.py", line 307, in format_kernel_cmd
cmd = self.kernel_spec.argv + extra_arguments
^^^^^^^^^^^^^^^^^^^^^
File "/opt/envs/spyder‑ide/lib/python3.12/site‑packages/spyder/plugins/ipythonconsole/utils/kernelspec.py", line 136, in argv
if conda_exe.endswith('micromamba'):
^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'endswith'
```

### What steps reproduce the problem?

1.   mkdir -p /opt/envs && sudo chown -R $USER /opt/envs
2.  `conda create -c conda-forge  spyder numpy scipy pandas matplotlib sympy cython -p /opt/envs/spyder-ide
3.  start spyder 6

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:    spyder                    6.0.1           py312h7900ff3_1    conda-forge
* Python version:    python                    3.12.6          hc5c86c4_1_cpython    conda-forge
* Qt version: 
* PyQt version:        pyqt                      5.15.9          py312h949fe66_5    conda-forge
* Operating System name/version:  ubuntu 2404

**Comment by abentwrygrin** [comment]
@0x1orz What was the solution to this? I'm having the same problem in miniforge on Windows 10.

**Comment by gul916** [comment]
Hi,
Thank you for this wonderful software.

I am observing the same ipython start problem using pixi after uninstalling Anaconda due to its licence change. It's bugging the same way under Windows and Linux. I bypassed the problem by installing the Spyder standalone version and calling the desired python kernel.

Regards

### What steps reproduce the problem?
1. pixi add spyder
2. pixi run spyder

### Paste Traceback/Error Below (if applicable)
    An error occurred while starting the kernel
    L'erreur est :
    
    Traceback (most recent call last):
    File "C:\Users\Gul91\.pixi\IDE�\envs\default\Lib\site‑packages\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1719, in create_new_client
    kernel_handler = self.get_cached_kernel(kernel_spec, cache=cache)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Gul91\.pixi\IDE�\envs\default\Lib\site‑packages\spyder\plugins\ipythonconsole\widgets\mixins.py", line 59, in get_cached_kernel
    new_kernel_handler = KernelHandler.new_from_spec(kernel_spec)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Gul91\.pixi\IDE�\envs\default\Lib\site‑packages\spyder\plugins\ipythonconsole\utils\kernel_handler.py", line 393, in new_from_spec
    kernel_manager.start_kernel(
    File "C:\Users\Gul91\.pixi\IDE�\envs\default\Lib\site‑packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Gul91\.pixi\IDE�\envs\default\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
    ^^^^^^^^^^^^^^^
    File "C:\Users\Gul91\.pixi\IDE�\envs\default\Lib\site‑packages\jupyter_client\manager.py", line 96, in wrapper
    raise e
    File "C:\Users\Gul91\.pixi\IDE�\envs\default\Lib\site‑packages\jupyter_client\manager.py", line 87, in wrapper
    out = await method(self, *args, **kwargs)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Gul91\.pixi\IDE�\envs\default\Lib\site‑packages\jupyter_client\manager.py", line 435, in _async_start_kernel
    kernel_cmd, kw = await self._async_pre_start_kernel(**kw)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Gul91\.pixi\IDE�\envs\default\Lib\site‑packages\jupyter_client\manager.py", line 400, in _async_pre_start_kernel
    kw = await self.provisioner.pre_launch(**kw)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Gul91\.pixi\IDE�\envs\default\Lib\site‑packages\jupyter_client\provisioning\local_provisioner.py", line 198, in pre_launch
    kernel_cmd = km.format_kernel_cmd(
    ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Gul91\.pixi\IDE�\envs\default\Lib\site‑packages\jupyter_client\manager.py", line 307, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
    ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Gul91\.pixi\IDE�\envs\default\Lib\site‑packages\spyder\plugins\ipythonconsole\utils\kernelspec.py", line 136, in argv
    if conda_exe.endswith('micromamba'):
    ^^^^^^^^^^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'endswith'

Note: the full directory is IDE-4858935620482225222. The output is as above, with the numbers replaced by the question mark.

### Versions
    Spyder version: spyder-6.0.2-py312h2e8e312_4.conda
    Python version: python-3.12.7-hce54a09_0_cpython.conda
    Qt version: qt-main-5.15.15-h264fbc2_0.conda
    PyQt version: pyqt-5.15.9-py312he09f080_5.conda
    Operating System name/version: Windows 11 & Linux CentOS 9

**Comment by ccordoba12** [comment]
@abentwrygrin, this problem happens because you installed Anaconda/Miniconda in a non-standard location. So, Spyder can't detect where Conda is located to activate the IPython console kernels and fails with this error.

The only workaround for the moment is to install any Conda-based distro in locations such as:

* `C:\Users\<your user>\Miniconda`
* `C:\Users\<your user>\Miniconda3`
* `C:\Users\<your user>\Anaconda`
* `C:\Users\<your user>\Anaconda3`

@gul916, your problem happens because we don't support pixi yet. We'll try to add support for it in 6.0.5 or 6.0.6.
