### ISSUE TITLE
Spyder 6.0.1 virtually crashing the whole PC upon startup + other issues (Win 11/Micromamba)

### ISSUE THREAD

**Issue by arpitg95** [spyder-ide/spyder#22614]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am on Windows 11 and installed python, spyder, etc. using Micromamba. After updating from Spyder 5.5.6 to 6.0.x, I first encoutered the `--no-capture-output` error when Spyder tried to launch a kernel. That was kind of fixed on my end by modifying `envs\<env_name>\Lib\site-packages\spyder\plugins\ipythonconsole\utils\kernelspec.py` -> micromamba to micromamba.exe

```python
136: if conda_exe.endswith('micromamba.exe'):
                kernel_cmd.extend(['--attach', '""'])
```

That being said, after launching spyder, it just plain crashes the PC. Sometimes it causes some other applications to close. One time it caused dwm.exe to crash. Most of the time it just causes a black screen, and I have to restart the whole PC. Though I did manage to see Spyder load the IPython kernel for a second before the screen crashed to black.

### What steps reproduce the problem?

1. Modify kernelspec.py file in ipythonconsole utils and make it say micromamba.exe instead of micromamba only.
2. Launch spyder.
3. Restart PC and try again.

### What is the expected output? What do you see instead?
Expected output - See spyder load ipython kernel
Actual output - black screen

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 6.0.1
* Python version: 3.12.6
* Qt version: qt-main = 5.15.8
* PyQt version: 5.15.9
* Operating System name/version: Windows 11 

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.10.8 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.17.0 (OK)
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
github >=2.3.0                   :  2.4.0 (OK)
importlib_metadata >=4.6.0       :  8.5.0 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.27.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.1.0 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  25.4.1 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.8.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  6.0.0 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.3.1 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0         :  5.6.0 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.3.0 (OK)
setuptools >=49.6.0              :  75.1.0 (OK)
sphinx >=0.6.6                   :  8.0.2 (OK)
spyder_kernels >=3.0.0,<3.1.0    :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  5.0.3 (OK)
yarl >=1.9.4                     :  1.13.1 (OK)
zmq >=24.0.0                     :  26.2.0 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  3.9.2 (OK)
numpy >=1.7                      :  2.1.1 (OK)
pandas >=1.1.1                   :  2.2.3 (OK)
scipy >=0.17.0                   :  1.14.1 (OK)
sympy >=0.7.3                    :  1.13.3 (OK)

```

**Comment by ccordoba12** [comment]
Hey @arpitg95, thanks for reporting. A couple of questions for you:

* What's your micromamba version?
* You said

    > Most of the time it just causes a black screen, and I have to restart the whole PC.

    What do you by black screen? You don't even see the famous Windows blue screen of death?

**Comment by arpitg95** [comment]
> What's your micromamba version?
```
libmamba version : 1.5.8
micromamba version : 1.5.8
```
> What do you by black screen? You don't even see the famous Windows blue screen of death?
I tried launching spyder a few more times since then. One time I got the message that Windows had to sign me out because DWM.exe has crashed. So, it is not exactly a hard crash to BSoD.

**Comment by ccordoba12** [comment]
Thanks for the extra info @arpitg95.

@dalthviz, could you check if you're getting the same behavior on Windows when using micromamba? For that you also need to apply the smalll fix mentioned by @arpitg95 in the OP.

**Comment by dalthviz** [comment]
So I checked installing Spyder 6.0.1 via micromamba and got a couple of messages from the installation:

```powershell
Linking spyder-6.0.1-py312h2e8e312_2
error    libmamba Creation of shortcut was not successful [json.exception.type_error.302] type must be string, but is object
"chcp" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"chcp" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
""C:\Users\dalth\micromambaenv\condabin\micromamba"" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

Transaction finished
```

Launch Spyder via powershell showed another message:

```python-traceback
C:\Users\dalth\micromambaenv\envs\micro_spyder\Lib\site-packages\qstylizer\style.py:68: SyntaxWarning: invalid escape sequence '\*'
  _split_regex = '\*|\[[A-Za-z0-9=\'"_:]+\]|\W*\w*'
```

Checking the IPython Console I got an error but seems to me that is related with trying to activate the micromamba created env via the conda from the Anaconda distribution I have installed?:

```python-traceback
"chcp" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

Traceback (most recent call last):
File "C:\Users\dalth\anaconda3\lib\site‑packages\conda\exception_handler.py", line 17, in __call__
return func(*args, **kwargs)
File "C:\Users\dalth\anaconda3\lib\site‑packages\conda\cli\main.py", line 105, in main_sourced
print(activator.execute(), end="")
File "C:\Users\dalth\anaconda3\lib\site‑packages\conda\activate.py", line 199, in execute
return getattr(self, self.command)()
File "C:\Users\dalth\anaconda3\lib\site‑packages\conda\activate.py", line 165, in activate
builder_result = self.build_activate(self.env_name_or_prefix)
File "C:\Users\dalth\anaconda3\lib\site‑packages\conda\activate.py", line 343, in build_activate
return self._build_activate_stack(env_name_or_prefix, False)
File "C:\Users\dalth\anaconda3\lib\site‑packages\conda\activate.py", line 367, in _build_activate_stack
return self.build_reactivate()
File "C:\Users\dalth\anaconda3\lib\site‑packages\conda\activate.py", line 558, in build_reactivate
self._replace_prefix_in_path(conda_prefix, conda_prefix)
File "C:\Users\dalth\anaconda3\lib\site‑packages\conda\activate.py", line 677, in _replace_prefix_in_path
if path_list[last_idx + 1] == library_bin_dir:
IndexError: list index out of range

`$ C:\Users\dalth\anaconda3\Scripts\conda‑script.py shell.cmd.exe activate C:\Users\dalth\micromambaenv\envs\micro_spyder`
``` 

Closed Spyder and did the `micromamba.exe` change over `kernelspec.py`, tried to launch Spyder but I got the same error

**Comment by ccordoba12** [comment]
@dalthviz, I agree with @arpitg95, please test with micromamba 1.5.10 because version 2.0 seems broken or semi-broken.

**Comment by dalthviz** [comment]
Gave a check using micromamba version 1.5.10 and I was able to launch Spyder from the previously created env as well as seeing the IPython Console work/start:

![image](https://github.com/user-attachments/assets/83d4d994-fec8-4c5b-b915-ce4b7becd8da)

However, I'm using Windows 10 so, maybe I should try to create a virtual machine with Windows 11 @ccordoba12 ?

**Comment by ccordoba12** [comment]
> However, I'm using Windows 10 so, maybe I should try to create a virtual machine with Windows 11 @ccordoba12 ?

Good point @dalthviz, that could be the problem. Please do that and report back what you find.

**Comment by ccordoba12** [comment]
@dalthviz, did you manage to check this on a Windows 11 machine?

**Comment by dalthviz** [comment]
> @dalthviz, did you manage to check this on a Windows 11 machine?

Nop, and although I downloaded a Windows 11 .iso file sometime ago I haven't go any futher into setting up a VM or something like that. Should I try to test this ASAP?

**Comment by ccordoba12** [comment]
No, there's no rush because no one else has reported an issue like this. But it'd be good if you could do it in the next two or three weeks.

**Comment by JakeHightower** [comment]
I am having the same problem. Created a new, fresh env, only installing dependencies for numpy, pandas, and ipfn. Launching Spyder 6.0.1 silent fails (launching, Spyder logo, then nothing, Anaconda Navigator shows the option still to launch). On second attempt I get a crash error and no BSOD, but  an instant "Windows Shutting Down." I'm able to run on earlier releases of Spyder.

**Comment by dalthviz** [comment]
Hi @JakeHightower thank you for the info! Are you also using micromamba and you are on Windows 11, right? Or is your setup different but the error is also happening to you? Also, could it be possible for you to update to the latest Spyder 6 release (6.0.3) and check again if such a crash persists? Let us know!

**Comment by sk-ys** [comment]
I encountered the same issue. My environment is as follows:

- Windows 11
- micromamba 2.0.5
- Spyder 6.0.3

After some analysis, I believe the cause might be the following:
When installing micromamba, the `micromamba shell init` command updates the PowerShell profile script. Its content looks like this (replace `[path]` with the actual path):
```powershell
#region mamba initialize
# !! Contents within this block are managed by 'mamba shell init' !!
$Env:MAMBA_ROOT_PREFIX = "[path]\.micromamba" 
$Env:MAMBA_EXE = "[path]\micromamba.exe" 
(& $Env:MAMBA_EXE 'shell' 'hook' -s 'powershell' -r $Env:MAMBA_ROOT_PREFIX) | Out-String | Invoke-Expression
#endregion
```

As a result, when PowerShell starts, the environment variable `MAMBA_EXE` is automatically set to a string ending in `micromamba.exe`.

Therefore, as a temporary workaround, I edited the `profile.ps1` file to remove `.exe` as follows, and confirmed that Spyder Ipython Console starts successfully:
```powershell
#region mamba initialize
# !! Contents within this block are managed by 'mamba shell init' !!
$Env:MAMBA_ROOT_PREFIX = "[path]\.micromamba" 
$Env:MAMBA_EXE = "[path]\micromamba" 
(& $Env:MAMBA_EXE 'shell' 'hook' -s 'powershell' -r $Env:MAMBA_ROOT_PREFIX) | Out-String | Invoke-Expression
#endregion
```

Also, I did not encounter any issue right after the initial micromamba installation. However, after installing and then uninstalling Anaconda, the Spyder IPython Console not working. There might be some relation to these changes.

**Comment by ccordoba12** [comment]
Thanks @sk-ys for digging into this issue! You said:

> As a result, when PowerShell starts, the environment variable MAMBA_EXE is automatically set to a string ending in micromamba.exe
Therefore, as a temporary workaround, I edited the profile.ps1 file to remove .exe as follows, and confirmed that Spyder Ipython Console starts successfully

This means that `micromamba.exe` is not available in your system but `micromamba` is?

**Comment by ccordoba12** [comment]
> Yes, that's right to launch spyder with ’spyder’ command in powershell.

@dalthviz, could you install micromamba 2 in an env and check what's the name of its executable? Thanks!

> However, to launch spyder.exe generated in the micromamba environment by mouse click, it was necessary to set the same content as the previously edited profile script as environment variables permanently.

@sk-ys, you shouldn't need to do that. Spyder 6 creates a shortcut per env in the Windows Start Menu to launch Spyder. Could you check if you have it and it's working as expected?

**Comment by sk-ys** [comment]
> @sk-ys, you shouldn't need to do that. Spyder 6 creates a shortcut per env in the Windows Start Menu to launch Spyder. Could you check if you have it and it's working as expected?

@ccordoba12, Thank you for your response. In my environment, micromamba fails to generate shortcuts. The cause is unknown.
![image](https://github.com/user-attachments/assets/c1916ded-d193-4efc-825f-7a06409b28e7)

**Comment by ccordoba12** [comment]
> In my environment, micromamba fails to generate shortcuts. The cause is unknown.

Ok, that's not good. @mrclary, could you take a look at that?

**Comment by mrclary** [comment]
As @sk-ys discovered,
https://github.com/spyder-ide/spyder/blob/3f64ee3c2fb7c4ae9af4b9969b66de64d0c3ffe2/spyder/plugins/ipythonconsole/utils/kernelspec.py#L136-L137
should be modified to
```python
if conda_exe.endswith(('micromamba', 'micromamba.exe')):
```

> @ccordoba12, Thank you for your response. In my environment, micromamba fails to generate shortcuts. The cause is unknown.

I don't know what is going on with the shortcut. However, I suspect that `micromamba` may be using an old version of `menuinst` or it may not be implemented correctly. It may be related to another comment/issue that I can't locate right now ☹️. Pinging @wolfv.

**Comment by ccordoba12** [comment]
> should be modified to
> if conda_exe.endswith(('micromamba', 'micromamba.exe')):

Ok, thanks for confirming that. I'll open a PR to address it.

> don't know what is going on with the shortcut. However, I suspect that micromamba may be using an old version of menuinst or it may not be implemented correctly.

Could you open an issue in the [Mamba repository](https://github.com/mamba-org/mamba) to continue the discussion there? Thanks!

**Comment by ccordoba12** [comment]
Closing because we were unable to reproduce this one.
