### ISSUE TITLE
File name issue

### ISSUE THREAD

**Issue by DharmJarwani** [spyder-ide/spyder#22639]
### What steps will reproduce the problem?

When i tried to add title 12.7.py it show this dialog box 'issue reporter'

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\spyder-6\envs\spyder-runtime\Lib\site-packages\spyder\app\mainwindow.py", line 552, in switch_to_plugin
    self.layouts.switch_to_plugin(plugin, force_focus=force_focus)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'switch_to_plugin'
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\spyder-6\envs\spyder-runtime\Lib\site-packages\spyder\app\mainwindow.py", line 552, in switch_to_plugin
    self.layouts.switch_to_plugin(plugin, force_focus=force_focus)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'switch_to_plugin'
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\spyder-6\envs\spyder-runtime\Lib\site-packages\spyder\app\mainwindow.py", line 552, in switch_to_plugin
    self.layouts.switch_to_plugin(plugin, force_focus=force_focus)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'switch_to_plugin'
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\spyder-6\envs\spyder-runtime\Lib\site-packages\spyder\app\mainwindow.py", line 552, in switch_to_plugin
    self.layouts.switch_to_plugin(plugin, force_focus=force_focus)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'switch_to_plugin'
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\spyder-6\envs\spyder-runtime\Lib\site-packages\spyder\app\mainwindow.py", line 552, in switch_to_plugin
    self.layouts.switch_to_plugin(plugin, force_focus=force_focus)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'switch_to_plugin'
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\spyder-6\envs\spyder-runtime\Lib\site-packages\spyder\app\mainwindow.py", line 552, in switch_to_plugin
    self.layouts.switch_to_plugin(plugin, force_focus=force_focus)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'switch_to_plugin'
```

## Versions

* Spyder version: 6.0.1  (standalone)
* Python version: 3.11.9 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.10.5 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.17.0 (OK)
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
github >=2.3.0                   :  2.4.0 (OK)
importlib_metadata >=4.6.0       :  8.5.0 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.27.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.1.0 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  25.4.1 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.8.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  6.0.0 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.3.0 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0         :  5.6.0 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.3.0 (OK)
setuptools >=49.6.0              :  74.1.2 (OK)
sphinx >=0.6.6                   :  8.0.2 (OK)
spyder_kernels >=3.0.0,<3.1.0    :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  5.0.2 (OK)
yarl >=1.9.4                     :  1.9.4 (OK)
zmq >=24.0.0                     :  26.2.0 (OK)

# Optional:
cython >=0.21                    :  3.0.11 (OK)
matplotlib >=3.0.0               :  3.9.2 (OK)
numpy >=1.7                      :  2.1.1 (OK)
pandas >=1.1.1                   :  2.2.3 (OK)
scipy >=0.17.0                   :  1.14.1 (OK)
sympy >=0.7.3                    :  1.13.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @DharmJarwani, thanks for reporting. Could you upload a video that shows how your error is generated?

We need that to try to reproduce and fix it our side. Thanks!

**Comment by ccordoba12** [comment]
We still don't know why this bug happens but if there's someone interested in helping us to solve it, these are the steps you need to do follow to give us the info we need:

1. Open this file in Spyder or another text editor:

       C:\Users\<your user>\AppData\Local\spyder-6\envs\spyder-runtime\Lib\site-packages\spyder\app\mainwindow.py

2. Go to line **788**, which should appear like this:

    https://github.com/spyder-ide/spyder/blob/49a9cca8f4b7b20a5a4afdb451b2797a775ca788/spyder/app/mainwindow.py#L785-L791

3. Change there `error=False` to `error=True`.
4. Close Spyder (if you have it open) and start it again.
5. Do the same things you did before that generated the error.
6. Clicking on the `Show details` button of the window that shows up after the error appears and copy/paste its text here.

**Comment by TheophileLaPelouse** [comment]
Hello, the issue I posted was indeed a duplicate of this issue (but the window to raise an issue kept poping up, I could not resist to raise one), and the fix you suggested work for me, thank you !

**Comment by CAM-Gerlach** [comment]
I've managed to run into this myself on 6.0.7/Windows 11/Standalone installer while developing Spyder itself; the specific circumstances was clicking a search result in the Find pane to open the corresponding file in the Editor (which I had done a number of times before in the session with no error). There wasn't anything particularly unusual I'd been doing prior to that, just editing the file, aside from testing the Search --> Search text in the Find pane menu item (which had been some time prior, and appeared to work).

I tried to repro it in my development copy of Spyder (latest 6.1.0.dev0), opening/switching to many different files from multiple searches and doing different things in the Editor (including trying the same Search menu option) but it not trigger; however, in my production copy I modified the file accordingly so I'll get a full traceback if the error triggers again.

One thing I did notice when it happened, however, is my View menu now looks like this:

![Image](https://github.com/user-attachments/assets/71727150-642b-4b13-8bae-955d0f9044b1)

All the other menus appear to be unchanged. Seems like the plugin registry has somehow been lost? When I close Spyder, it then crashes immediately with no message.

**Comment by ccordoba12** [comment]
@dalthviz, please try to reproduce and fix this issue. I still don't understand why it happens but we can't simply catch the exception and pass because the Layouts plugins shouldn't be `None`.
