### ISSUE TITLE
AttributeError in tour when Help plugin is not available

### ISSUE THREAD

**Issue by soda92** [spyder-ide/spyder#22635]
### What steps will reproduce the problem?

1. install spyder in MSYS2 ucrt64 using pacman
2. fireup spyder, and go over tour
3. the issue appears automatically

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:/msys64/ucrt64/lib/python3.11/site-packages/spyder/plugins/tours/widgets.py", line 740, in _process_widgets
    temp = getattr(spy_window, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/ucrt64/lib/python3.11/site-packages/spyder/app/mainwindow.py", line 983, in __getattr__
    return super().__getattr__(attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'help'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/msys64/ucrt64/lib/python3.11/site-packages/spyder/plugins/tours/widgets.py", line 701, in _move_step
    self._set_data()
  File "C:/msys64/ucrt64/lib/python3.11/site-packages/spyder/plugins/tours/widgets.py", line 785, in _set_data
    widgets, dockwidgets = self._process_widgets(widget_names,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/ucrt64/lib/python3.11/site-packages/spyder/plugins/tours/widgets.py", line 750, in _process_widgets
    temp = eval(f"spy_window.{name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "C:/msys64/ucrt64/lib/python3.11/site-packages/spyder/app/mainwindow.py", line 983, in __getattr__
    return super().__getattr__(attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'help'
```

## Versions

* Spyder version: 5.5.6  (pip)
* Python version: 3.11.10 64-bit
* Qt version: 5.15.15
* PyQt5 version: 5.15.11
* Operating System: Windows-10-10.0.22631-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
importlib_metadata >=4.6.0       :  8.0.0 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.27.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.1.0 (OK)
jsonschema >=3.2.0               :  4.22.0 (OK)
keyring >=17.0.0                 :  25.2.1 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.7.0 (OK)
paramiko >=2.4.0                 :  3.4.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.8 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.3.1 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.2 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.2.0 (OK)
setuptools >=49.6.0              :  75.1.0 (OK)
sphinx >=0.6.6                   :  7.4.7 (OK)
spyder_kernels >=2.5.2,<2.6.0    :  2.5.2 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  3.0.0 (OK)
zmq >=24.0.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  None (NOK)
numpy >=1.7                      :  None (NOK)
pandas >=1.1.1                   :  None (NOK)
scipy >=0.17.0                   :  None (NOK)
sympy >=0.7.3                    :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @soda92, thanks for reporting. This happens because the Help pane is not available in your installation, probably due to the lack of the Qt WebEngine package.

We'll take care of this in our 6.0.3 version, to be released in a few weeks.

**Comment by soda92** [comment]
thank you
