### ISSUE TITLE
F9 (run selection) fails from .md file

### ISSUE THREAD

**Issue by esskov** [spyder-ide/spyder#22630]
### What steps will reproduce the problem?

1. write a few lines of Python code as part of an .md file
2. select the lines of code
3. press F9 to execute the code in the Concole
4. This Error occurs

nb: copy-pasting the code into the Console works just fine, and the code is executes as expected.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Miniconda3\envs\mt_drc_39_e\lib\site-packages\spyder\plugins\run\container.py", line 176, in anonymous_execution_run
    last_executor = self.executor_model.get_default_executor(
  File "C:\Miniconda3\envs\mt_drc_39_e\lib\site-packages\spyder\plugins\run\models.py", line 131, in get_default_executor
    executors = self.inverted_pos[input]
KeyError: ('md', 'selection')
```

## Versions

* Spyder version: 6.0.1  (conda)
* Python version: 3.9.16 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                      :  3.10.5 (OK)
asyncssh >=2.14.0,<3.0.0             :  2.17.0 (OK)
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.1.0 (OK)
cloudpickle >=0.5.0                  :  2.2.1 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20230430 (OK)
github >=2.3.0                       :  2.4.0 (OK)
importlib_metadata >=4.6.0           :  6.6.0 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1     :  8.14.0 (OK)
jedi >=0.17.2,<0.20.0                :  0.18.2 (OK)
jellyfish >=0.7                      :  0.11.2 (OK)
jsonschema >=3.2.0                   :  4.19.1 (OK)
keyring >=17.0.0                     :  23.13.1 (OK)
nbconvert >=4.0                      :  7.9.2 (OK)
numpydoc >=0.6.0                     :  1.5.0 (OK)
parso >=0.7.0,<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.5 (OK)
pygments >=2.0                       :  2.15.1 (OK)
pylint >=3.1,<4                      :  3.1.0 (OK)
pylint_venv >=3.0.2                  :  3.0.2 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0               :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0           :  2.0.0 (OK)
pyuca >=1.2                          :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0            :  3.2.3 (OK)
qstylizer >=0.2.2                    :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0             :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0             :  5.6.0 (OK)
qtpy >=2.4.0                         :  2.4.1 (OK)
rtree >=0.9.7                        :  1.0.1 (OK)
setuptools >=49.6.0                  :  67.8.0 (OK)
sphinx >=0.6.6                       :  7.0.1 (OK)
spyder_kernels >=3.0.0,<3.1.0        :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0               :  0.6.7 (OK)
textdistance >=4.2.0                 :  4.5.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  3.0.0 (OK)
yarl >=1.9.4                         :  1.12.1 (OK)
zmq >=24.0.0                         :  25.1.0 (OK)

# Optional:
cython >=0.21                        :  None (NOK)
matplotlib >=3.0.0                   :  3.7.1 (OK)
numpy >=1.7                          :  1.24.3 (OK)
pandas >=1.1.1                       :  2.0.2 (OK)
scipy >=0.17.0                       :  1.11.2 (OK)
sympy >=0.7.3                        :  1.12 (OK)

# Spyder plugins:
spyder_notebook.notebookplugin 0.6.1 :  0.6.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @esskov, thanks for reporting and the clear instructions to reproduce this problem. We'll take care of it in a future release.
