### ISSUE TITLE
Failure to connect to kernal

### ISSUE THREAD

**Issue by ben-rowlinson** [spyder-ide/spyder#22634]
### What steps will reproduce the problem?

Edited $PATH using 

export PATH=$PATH:/home/browlins/.local/bin

### Traceback
```python-traceback
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/browlins/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 560, in _run_callback
    f = callback(*args, **kwargs)
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/site-packages/jupyter_client/threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/site-packages/jupyter_client/threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/home/browlins/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 610, in _handle_events
    self._handle_recv()
  File "/home/browlins/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 639, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/browlins/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 560, in _run_callback
    f = callback(*args, **kwargs)
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/site-packages/jupyter_client/threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/site-packages/jupyter_client/threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback BaseAsyncIOLoop._handle_events(107, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(107, 1)>
Traceback (most recent call last):
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "/home/browlins/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 610, in _handle_events
    self._handle_recv()
  File "/home/browlins/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 639, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/browlins/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 560, in _run_callback
    f = callback(*args, **kwargs)
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/site-packages/jupyter_client/threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/site-packages/jupyter_client/threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/browlins/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 560, in _run_callback
    f = callback(*args, **kwargs)
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/site-packages/jupyter_client/threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/site-packages/jupyter_client/threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/home/browlins/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 610, in _handle_events
    self._handle_recv()
  File "/home/browlins/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 639, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/browlins/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 560, in _run_callback
    f = callback(*args, **kwargs)
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/site-packages/jupyter_client/threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/site-packages/jupyter_client/threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback BaseAsyncIOLoop._handle_events(106, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(106, 1)>
Traceback (most recent call last):
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "/home/browlins/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 610, in _handle_events
    self._handle_recv()
  File "/home/browlins/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 639, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/browlins/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 560, in _run_callback
    f = callback(*args, **kwargs)
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/site-packages/jupyter_client/threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9/site-packages/jupyter_client/threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
```

## Versions

* Spyder version: 5.4.0  (conda)
* Python version: 3.9.13 64-bit
* Qt version: 5.15.6
* PyQt5 version: 5.15.7
* Operating System: Linux 3.10.0-1160.118.1.el7.x86_64

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.0.0 (OK)
cloudpickle >=0.5.0           :  2.2.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.0 (OK)
keyring >=17.0.0              :  23.9.3 (OK)
nbconvert >=4.0               :  7.2.3 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.3 (OK)
pygments >=2.0                :  2.13.0 (OK)
pylint >=2.5.0;<3.0           :  2.15.5 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.6.0;<1.7.0          :  1.6.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.1 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.2.1 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.5.1 (OK)
sphinx >=0.6.6                :  5.3.0 (OK)
spyder_kernels >=2.4.0;<2.5.0 :  2.4.0 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
xdg >=0.26                    :  0.28 (OK)
zmq >=22.1.0                  :  26.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.32 (OK)
matplotlib >=3.0.0            :  3.9.2 (OK)
numpy >=1.7                   :  1.26.4 (OK)
pandas >=1.1.1                :  2.2.3 (OK)
scipy >=0.17.0                :  1.13.1 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @ben-rowlinson, thanks for reporting. You said:

> Edited $PATH using
>
> export PATH=$PATH:/home/browlins/.local/bin

What happens if you remove that extra path from PATH? Do things work as expected in that case?

**Comment by ben-rowlinson** [comment]
Hi,

What's the best way to remove the additional path part from the PATH? Is this different from PYTHONPATH - I've been reading that this might come into it too.

Based on the readback it seems to be more of an issue with installing an upgraded matplotlib package that causes an uncaught exception in ZMQStream library.

Kind regards,
Ben

________________________________

**Comment by ccordoba12** [comment]
> What's the best way to remove the additional path part from the PATH?

You said you did

    export PATH=$PATH:/home/browlins/.local/bin

So, where did you do that? In the console? Or did you add that line to your `.bashrc`?

> Is this different from PYTHONPATH - I've been reading that this might come into it too.

Yes, PATH is the set of directories used by the system to find executables.

> Based on the readback it seems to be more of an issue with installing an upgraded matplotlib package that causes an uncaught exception in ZMQStream library.

It could be. Did you use pip to do do that?

If so, then that would explain why you ended up mixing Python packages from two different environments: `/opt/spyder-5.4.1/envs/spyder-5.4.1.dev0/lib/python3.9` and `/home/browlins/.local/lib/python3.9/` (which is shown in your error report above).

**Comment by ben-rowlinson** [comment]
Hi Carlos,

Yep, it was in the terminal that I changed the PATH. The console in Spyder wouldn't start at all.

I have reset the PATH variable to remove the added parts and deleted the zmq folder from my local site-packages folder.

The kernel is running as expected when using the command:


LIBGL_ALWAYS_SOFTWARE=1 spyder5


Thanks for your help with this!

Kind regards,
Ben


________________________________

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
