### ISSUE TITLE
New installation on Macbook Pro (Apple Silicon - M1 Pro)

### ISSUE THREAD

**Issue by sakileswar** [spyder-ide/spyder#22735]
### What steps will reproduce the problem?

Start up spyder for first time after pip install spyder. 

### Traceback
```python-traceback

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/homebrew/lib/python3.11/site-packages/spyder/plugins/application/container.py", line 234, in _compute_dependencies
    dependencies.declare_dependencies()
  File "/opt/homebrew/lib/python3.11/site-packages/spyder/dependencies.py", line 485, in declare_dependencies
    add(dep['modname'], dep['package_name'],
  File "/opt/homebrew/lib/python3.11/site-packages/spyder/dependencies.py", line 416, in add
    DEPENDENCIES += [Dependency(modname, package_name, features,
  File "/opt/homebrew/lib/python3.11/site-packages/spyder/dependencies.py", line 355, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "/opt/homebrew/lib/python3.11/site-packages/spyder/utils/programs.py", line 1004, in get_module_version
    mod = __import__(module_name)
  File "/opt/homebrew/lib/python3.11/site-packages/matplotlib/__init__.py", line 131, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/opt/homebrew/lib/python3.11/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/opt/homebrew/lib/python3.11/site-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "/opt/homebrew/lib/python3.11/site-packages/matplotlib/scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "/opt/homebrew/lib/python3.11/site-packages/matplotlib/ticker.py", line 138, in <module>
    from matplotlib import transforms as mtransforms
  File "/opt/homebrew/lib/python3.11/site-packages/matplotlib/transforms.py", line 49, in <module>
    from matplotlib._path import (
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/homebrew/bin/spyder", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.11/site-packages/spyder/app/start.py", line 285, in main
    mainwindow.main(options, args)
  File "/opt/homebrew/lib/python3.11/site-packages/spyder/app/mainwindow.py", line 1425, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "/opt/homebrew/lib/python3.11/site-packages/spyder/app/utils.py", line 412, in create_window
    app.exec_()
  File "/opt/homebrew/lib/python3.11/site-packages/spyder/plugins/application/container.py", line 221, in _set_dependencies
    self.dependencies_dialog.set_data(dependencies.DEPENDENCIES)
  File "/opt/homebrew/lib/python3.11/site-packages/spyder/widgets/dependencies.py", line 182, in set_data
    self.treewidget.update_dependencies(dependencies)
  File "/opt/homebrew/lib/python3.11/site-packages/spyder/widgets/dependencies.py", line 63, in update_dependencies
    if dependency.check():
  File "/opt/homebrew/lib/python3.11/site-packages/spyder/dependencies.py", line 376, in check
    installed = programs.is_module_installed(
  File "/opt/homebrew/lib/python3.11/site-packages/spyder/utils/programs.py", line 1050, in is_module_installed
    module_version = get_module_version(module_name)
  File "/opt/homebrew/lib/python3.11/site-packages/spyder/utils/programs.py", line 1004, in get_module_version
    mod = __import__(module_name)
  File "/opt/homebrew/lib/python3.11/site-packages/matplotlib/__init__.py", line 131, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/opt/homebrew/lib/python3.11/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/opt/homebrew/lib/python3.11/site-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "/opt/homebrew/lib/python3.11/site-packages/matplotlib/scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "/opt/homebrew/lib/python3.11/site-packages/matplotlib/ticker.py", line 138, in <module>
    from matplotlib import transforms as mtransforms
  File "/opt/homebrew/lib/python3.11/site-packages/matplotlib/transforms.py", line 49, in <module>
    from matplotlib._path import (
AttributeError: _ARRAY_API not found
```

## Versions

* Spyder version: 6.0.1  (pip)
* Python version: 3.11.10 64-bit
* Qt version: 5.15.14
* PyQt5 version: 5.15.11
* Operating System: macOS-15.0.1-arm64-arm-64bit

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.10.10 (OK)
applaunchservices >=0.3.0        :  0.3.0 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.17.0 (OK)
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.1.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20241021 (OK)
github >=2.3.0                   :  2.4.0 (OK)
importlib_metadata >=4.6.0       :  8.5.0 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.29.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.18.2 (OK)
jellyfish >=0.7                  :  1.1.0 (OK)
jsonschema >=3.2.0               :  4.17.3 (OK)
keyring >=17.0.0                 :  25.4.1 (OK)
nbconvert >=4.0                  :  7.2.9 (OK)
numpydoc >=0.6.0                 :  1.8.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.4 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.3.1 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0         :  5.6.0 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.3.0 (OK)
setuptools >=49.6.0              :  74.1.2 (OK)
sphinx >=0.6.6                   :  8.1.3 (OK)
spyder_kernels >=3.0.0,<3.1.0    :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  5.0.3 (OK)
yarl >=1.9.4                     :  1.16.0 (OK)
zmq >=24.0.0                     :  25.0.0 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  None (NOK)
numpy >=1.7                      :  2.1.2 (OK)
pandas >=1.1.1                   :  None (NOK)
scipy >=0.17.0                   :  1.11.2 (OK)
sympy >=0.7.3                    :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @sakileswar, thanks for reporting. This problem happens because you have an outdated version of Matplotlib, so please update it to the latest one.

I don't know how you can do that in a Homebrew installation, but in a regular one it is as simple as running this in a terminal:

    pip install -U matplotlib
