### ISSUE TITLE
Can not start spyder under python2 because guidata doesn't support PyQt5

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#2274]
Started from bootstrap.py with today's last master:
```
Traceback (most recent call last):
  File "/home/joseph/prog/spyder.git/spyderlib/spyder.py", line 2865, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/joseph/prog/spyder.git/spyderlib/spyder.py", line 2755, in run_spyder
    main.setup()
  File "/home/joseph/prog/spyder.git/spyderlib/spyder.py", line 736, in setup
    if is_module_installed('guidata'):
  File "/home/joseph/prog/spyder.git/spyderlib/utils/programs.py", line 292, in is_module_installed
    actver = get_module_version(module_name)
  File "/home/joseph/prog/spyder.git/spyderlib/utils/programs.py", line 238, in get_module_version
    mod = __import__(module_name)
  File "/usr/lib/python2.7/site-packages/guidata/__init__.py", line 539, in <module>
    import guidata.config
  File "/usr/lib/python2.7/site-packages/guidata/config.py", line 15, in <module>
    from guidata.configtools import add_image_module_path, get_translation
  File "/usr/lib/python2.7/site-packages/guidata/configtools.py", line 22, in <module>
    from guidata.qt.QtGui import (QFont, QLabel, QPixmap, QIcon, QHBoxLayout,
  File "/usr/lib/python2.7/site-packages/guidata/qt/__init__.py", line 13, in <module>
    assert _modname in ('pyqt', 'pyside')
AssertionError
```

**Comment by ccordoba12** [comment]
This is not an issue with Spyder but with guidata. It seems it doesn't support Qt5?

Since guitadata is now on Github, please report this issue there https://github.com/PierreRaybaut/guidata/issues

But until @PierreRaybaut fixes this error, we need to fix the crash in our side :-)

**Comment by Nodd** [comment]
Yeah, the doc states that it requires PyQt4, so it's not a bug but a missing feature. The last commit is 2 years old, is it still maintained ?

**Comment by ccordoba12** [comment]
I don't know :-)

**Comment by ccordoba12** [comment]
@Nodd, I can't test this because Ubuntu doesn't have pyqt5 for Python 2.

Please test it in your side and report back if my commit fixes the problem for you.

**Comment by Nodd** [comment]
```
Traceback (most recent call last):
  File "/data/prog/spyder.git/spyderlib/spyder.py", line 2870, in main
    mainwindow = run_spyder(app, options, args)
  File "/data/prog/spyder.git/spyderlib/spyder.py", line 2760, in run_spyder
    main.setup()
  File "/data/prog/spyder.git/spyderlib/spyder.py", line 736, in setup
    if is_module_installed('guidata'):
  File "/data/prog/spyder.git/spyderlib/utils/programs.py", line 292, in is_module_installed
    actver = get_module_version(module_name)
  File "/data/prog/spyder.git/spyderlib/utils/programs.py", line 238, in get_module_version
Sadly, it doesn't :
    mod = __import__(module_name)
  File "/usr/lib/python2.7/site-packages/guidata/__init__.py", line 539, in <module>
    import guidata.config
  File "/usr/lib/python2.7/site-packages/guidata/config.py", line 15, in <module>
    from guidata.configtools import add_image_module_path, get_translation
  File "/usr/lib/python2.7/site-packages/guidata/configtools.py", line 22, in <module>
    from guidata.qt.QtGui import (QFont, QLabel, QPixmap, QIcon, QHBoxLayout,
  File "/usr/lib/python2.7/site-packages/guidata/qt/__init__.py", line 13, in <module>
    assert _modname in ('pyqt', 'pyside')
AssertionError
```
I'm at commit 1d40965c917da3490aa01de4154aea1b9548732a so it includes your commit.

The problem is when testing if guidata is installed, so it's the line right before your modifications: https://github.com/spyder-ide/spyder/commit/55b30d8ad2d703f1451db1d2e3d51c13e9449caf#diff-e13742a2ff2d16fb2f96574ff7b24a5cR736

**Comment by ccordoba12** [comment]
Ok, I see. Thanks for reopening.

**Comment by ccordoba12** [comment]
@Nodd, please test again. I think I fixed the error now :-)

**Comment by ccordoba12** [comment]
@Nodd, can you give me confirmation on this issue? I need to be sure my last fix is working for beta1.

**Comment by Nodd** [comment]
It works now, thanks !

**Comment by Nodd** [comment]
Oh yeah, forgot to close it...
