### ISSUE TITLE
Can't start kernel

### ISSUE THREAD

**Issue by Mark531** [spyder-ide/spyder#22840]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
After installing tensorflow, Spyder couldn't start the kernel anymore... I don't know exactly what happened, but I can't fix it. I tried to reinstall spyder-kernels and typing-extensions to no avail.

### What steps reproduce the problem?

1. pip install tensorflow
2. Run spyder

### What is the expected output? What do you see instead?
I get an error message in the console panel. Could you help me fix the issue and maybe improve the error message so that users could fix it by themselves?

### Paste Traceback/Error Below (if applicable)

```python-traceback
Path not found.
Traceback (most recent call last):
File "C:\Users\kevguima\Anaconda3\envs\new_env\lib\site‑packages\spyder_kernels\console\__main__.py", line 24, in
start.main()
File "C:\Users\kevguima\Anaconda3\envs\new_env\lib\site‑packages\spyder_kernels\console\start.py", line 283, in main
import_spydercustomize()
File "C:\Users\kevguima\Anaconda3\envs\new_env\lib\site‑packages\spyder_kernels\console\start.py", line 47, in import_spydercustomize
import spydercustomize # noqa
File "C:\Users\kevguima\Anaconda3\envs\new_env\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 25, in
from IPython.core.getipython import get_ipython
File "C:\Users\kevguima\Anaconda3\envs\new_env\lib\site‑packages\IPython\__init__.py", line 55, in
from .terminal.embed import embed
File "C:\Users\kevguima\Anaconda3\envs\new_env\lib\site‑packages\IPython\terminal\embed.py", line 16, in
from IPython.terminal.interactiveshell import TerminalInteractiveShell
File "C:\Users\kevguima\Anaconda3\envs\new_env\lib\site‑packages\IPython\terminal\interactiveshell.py", line 48, in
from .debugger import TerminalPdb, Pdb
File "C:\Users\kevguima\Anaconda3\envs\new_env\lib\site‑packages\IPython\terminal\debugger.py", line 6, in
from IPython.core.completer import IPCompleter
File "C:\Users\kevguima\Anaconda3\envs\new_env\lib\site‑packages\IPython\core\completer.py", line 219, in
from IPython.core.guarded_eval import guarded_eval, EvaluationContext
File "C:\Users\kevguima\Anaconda3\envs\new_env\lib\site‑packages\IPython\core\guarded_eval.py", line 40, in
from typing_extensions import TypeAliasType
ImportError: cannot import name 'TypeAliasType' from 'typing_extensions' (C:\Users\kevguima\Anaconda3\envs\new_env\lib\site‑packages\typing_extensions.py)
Traceback (most recent call last):
File "C:\Users\kevguima\Anaconda3\envs\new_env\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\kevguima\Anaconda3\envs\new_env\lib\runpy.py", line 86, in _run_code
exec(code, run_globals)
File "C:\Users\kevguima\Anaconda3\envs\new_env\lib\site‑packages\spyder_kernels\console\__main__.py", line 24, in
start.main()
File "C:\Users\kevguima\Anaconda3\envs\new_env\lib\site‑packages\spyder_kernels\console\start.py", line 283, in main
import_spydercustomize()
File "C:\Users\kevguima\Anaconda3\envs\new_env\lib\site‑packages\spyder_kernels\console\start.py", line 47, in import_spydercustomize
import spydercustomize # noqa
File "C:\Users\kevguima\Anaconda3\envs\new_env\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 25, in
from IPython.core.getipython import get_ipython
File "C:\Users\kevguima\Anaconda3\envs\new_env\lib\site‑packages\IPython\__init__.py", line 55, in
from .terminal.embed import embed
File "C:\Users\kevguima\Anaconda3\envs\new_env\lib\site‑packages\IPython\terminal\embed.py", line 16, in
from IPython.terminal.interactiveshell import TerminalInteractiveShell
File "C:\Users\kevguima\Anaconda3\envs\new_env\lib\site‑packages\IPython\terminal\interactiveshell.py", line 48, in
from .debugger import TerminalPdb, Pdb
File "C:\Users\kevguima\Anaconda3\envs\new_env\lib\site‑packages\IPython\terminal\debugger.py", line 6, in
from IPython.core.completer import IPCompleter
File "C:\Users\kevguima\Anaconda3\envs\new_env\lib\site‑packages\IPython\core\completer.py", line 219, in
from IPython.core.guarded_eval import guarded_eval, EvaluationContext
File "C:\Users\kevguima\Anaconda3\envs\new_env\lib\site‑packages\IPython\core\guarded_eval.py", line 40, in
from typing_extensions import TypeAliasType
ImportError: cannot import name 'TypeAliasType' from 'typing_extensions' (C:\Users\kevguima\Anaconda3\envs\new_env\lib\site‑packages\typing_extensions.py)
```

## Versions

* Spyder version: 5.4.3
* Python version: 3.10.15
* Qt version: not found
* PyQt version: not found
* Operating System name/version: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  2.6.0 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.15.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  1.0.1 (OK)
jsonschema >=3.2.0                               :  4.19.2 (OK)
keyring >=17.0.0                                 :  24.3.1 (OK)
nbconvert >=4.0                                  :  7.10.0 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  3.0.3 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  2.0.0 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.4.1 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  69.5.1 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.4 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  25.1.2 (OK)

# Optional:
cython >=0.21                                    :  0.29.28 (OK)
matplotlib >=3.0.0                               :  3.8.4 (OK)
numpy >=1.7                                      :  1.26.4 (OK)
pandas >=1.1.1                                   :  1.4.2 (OK)
scipy >=0.17.0                                   :  1.13.0 (OK)
sympy >=0.7.3                                    :  1.12 (OK)
```

**Comment by Mark531** [comment]
Actually, reinstalling typing-extensions **and** restarting Spyder solved the issue.
