### ISSUE TITLE
RuntimeError when trying to compute the console banner

### ISSUE THREAD

**Issue by jdkolcz** [spyder-ide/spyder#22929]
unsure of how to reproduce it just froze and I exited out with right corner close red x

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\JDK Sci\AppData\Local\Programs\Python\Python312\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 322, in handle_kernel_is_ready
    self._show_banner()
  File "C:\Users\JDK Sci\AppData\Local\Programs\Python\Python312\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 1201, in _show_banner
    banner = self.long_banner()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\JDK Sci\AppData\Local\Programs\Python\Python312\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 785, in long_banner
    env_info = self.get_pythonenv_info()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JDK Sci\AppData\Local\Programs\Python\Python312\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 1079, in get_pythonenv_info
    ).get_pythonenv_info()
      ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JDK Sci\AppData\Local\Programs\Python\Python312\Lib\site-packages\spyder_kernels\comms\commbase.py", line 611, in __call__
    return self._comms_wrapper._get_call_return_value(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JDK Sci\AppData\Local\Programs\Python\Python312\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 171, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JDK Sci\AppData\Local\Programs\Python\Python312\Lib\site-packages\spyder_kernels\comms\commbase.py", line 464, in _get_call_return_value
    self._wait_reply(comm_id, call_id, call_name, timeout)
  File "C:\Users\JDK Sci\AppData\Local\Programs\Python\Python312\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 195, in _wait_reply
    self._wait(got_reply, self._sig_got_reply, timeout_msg, timeout)
  File "C:\Users\JDK Sci\AppData\Local\Programs\Python\Python312\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 231, in _wait
    raise RuntimeError("Kernel is dead")
RuntimeError: Kernel is dead
```

## Versions

* Spyder version: 6.0.2  (pip)
* Python version: 3.12.6 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.11
* Operating System: Windows-11-10.0.22631-SP0

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.10.10 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.18.0 (OK)
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.1.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20241021 (OK)
github >=2.3.0                   :  2.5.0 (OK)
importlib_metadata >=4.6.0       :  8.5.0 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.29.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.1.0 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  25.5.0 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.8.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  6.1.0 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.3.1 (OK)
pylint_venv >=3.0.2              :  3.0.4 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.1,<5.7.0         :  5.6.1 (OK)
qtpy >=2.4.0                     :  2.4.2 (OK)
rtree >=0.9.7                    :  1.3.0 (OK)
setuptools >=49.6.0              :  74.1.2 (OK)
sphinx >=0.6.6                   :  8.1.3 (OK)
spyder_kernels >=3.0.1,<3.1.0    :  3.0.1 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  6.0.0 (OK)
yarl >=1.9.4                     :  1.17.1 (OK)
zmq >=24.0.0                     :  26.2.0 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  3.9.2 (OK)
numpy >=1.7                      :  2.1.1 (OK)
pandas >=1.1.1                   :  2.2.2 (OK)
scipy >=0.17.0                   :  1.14.1 (OK)
sympy >=0.7.3                    :  None (NOK)
```

### Environment

<details><summary>Environment</summary>

```
Package                       Version
----------------------------- --------------
aiohappyeyeballs              2.4.3
aiohttp                       3.10.10
aiosignal                     1.3.1
alabaster                     1.0.0
annotated-types               0.6.0
anyio                         4.0.0
arrow                         1.3.0
astroid                       3.3.5
asttokens                     2.4.1
asyncssh                      2.18.0
atomicwrites                  1.4.1
attrs                         24.2.0
autopep8                      2.0.4
babel                         2.16.0
beautifulsoup4                4.12.3
binaryornot                   0.4.4
black                         24.10.0
bleach                        6.2.0
bottle                        0.13.1
certifi                       2023.7.22
cffi                          1.17.1
chardet                       5.2.0
charset-normalizer            3.4.0
click                         8.1.7
cloudpickle                   3.1.0
clr-loader                    0.2.6
colorama                      0.4.6
comm                          0.2.2
contourpy                     1.3.0
cookiecutter                  2.6.0
cryptography                  43.0.3
cycler                        0.12.1
DateTime                      5.5
debugpy                       1.8.8
decorator                     5.1.1
defusedxml                    0.7.1
Deprecated                    1.2.14
diff-match-patch              20241021
dill                          0.3.9
docstring-to-markdown         0.15
docutils                      0.21.2
executing                     2.1.0
fastjsonschema                2.20.0
flake8                        7.1.1
fonttools                     4.53.1
frozenlist                    1.5.0
h11                           0.14.0
httpcore                      0.18.0
httpx                         0.25.0
idna                          3.4
imagesize                     1.4.1
importlib_metadata            8.5.0
inflection                    0.5.1
intervaltree                  3.1.0
ipykernel                     6.29.5
ipython                       8.29.0
isort                         5.13.2
jaraco.classes                3.4.0
jaraco.context                6.0.1
jaraco.functools              4.1.0
jedi                          0.19.1
jellyfish                     1.1.0
Jinja2                        3.1.4
joblib                        1.4.2
jsonschema                    4.23.0
jsonschema-specifications     2024.10.1
jupyter_client                8.6.3
jupyter_core                  5.7.2
jupyterlab_pygments           0.3.0
keyring                       25.5.0
kiwisolver                    1.4.7
markdown-it-py                3.0.0
MarkupSafe                    3.0.2
matplotlib                    3.9.2
matplotlib-inline             0.1.7
mccabe                        0.7.0
mdurl                         0.1.2
mistune                       3.0.2
more-itertools                10.5.0
multidict                     6.1.0
mypy-extensions               1.0.0
nbclient                      0.10.0
nbconvert                     7.16.4
nbformat                      5.10.4
nest-asyncio                  1.6.0
numpy                         2.1.1
numpydoc                      1.8.0
packaging                     24.1
pandas                        2.2.2
pandocfilters                 1.5.1
parso                         0.8.4
pathspec                      0.12.1
pexpect                       4.9.0
pickleshare                   0.7.5
pillow                        10.4.0
pip                           24.3.1
platformdirs                  4.3.6
pluggy                        1.5.0
prompt_toolkit                3.0.48
propcache                     0.2.0
proxy_tools                   0.1.0
psutil                        6.1.0
ptyprocess                    0.7.0
pure_eval                     0.2.3
pycodestyle                   2.12.1
pycparser                     2.22
pydantic                      2.4.2
pydantic_core                 2.10.1
pydocstyle                    6.3.0
pyflakes                      3.2.0
PyGithub                      2.5.0
Pygments                      2.18.0
PyJWT                         2.9.0
pylint                        3.3.1
pylint-venv                   3.0.4
pyls-spyder                   0.4.0
PyNaCl                        1.5.0
pyparsing                     3.1.4
PyQt5                         5.15.11
PyQt5-Qt5                     5.15.2
PyQt5_sip                     12.15.0
PyQtWebEngine                 5.15.7
PyQtWebEngine-Qt5             5.15.2
python-dateutil               2.9.0.post0
python-lsp-black              2.0.0
python-lsp-jsonrpc            1.1.2
python-lsp-server             1.12.0
python-slugify                8.0.4
pythonnet                     3.0.3
pytoolconfig                  1.3.1
pytz                          2024.1
pyuca                         1.2
pywebview                     5.2
pywin32                       308
pywin32-ctypes                0.2.3
PyYAML                        6.0.2
pyzmq                         26.2.0
QDarkStyle                    3.2.3
qstylizer                     0.2.3
QtAwesome                     1.3.1
qtconsole                     5.6.1
QtPy                          2.4.2
referencing                   0.35.1
requests                      2.32.3
rich                          13.9.4
rope                          1.13.0
rpds-py                       0.21.0
Rtree                         1.3.0
scikit-learn                  1.5.1
scipy                         1.14.1
setuptools                    74.1.2
six                           1.16.0
sniffio                       1.3.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.6
Sphinx                        8.1.3
sphinxcontrib-applehelp       2.0.0
sphinxcontrib-devhelp         2.0.0
sphinxcontrib-htmlhelp        2.1.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          2.0.0
sphinxcontrib-serializinghtml 2.0.0
spyder                        6.0.2
spyder-kernels                3.0.1
stack-data                    0.6.3
superqt                       0.6.7
tabulate                      0.9.0
text-unidecode                1.3
textdistance                  4.6.3
threadpoolctl                 3.5.0
three-merge                   0.1.1
tinycss2                      1.4.0
tkcalendar                    1.6.1
tkcalendar2                   1.1.0
tomli                         2.0.2
tomlkit                       0.13.2
tornado                       6.4.1
traitlets                     5.14.3
ttkbootstrap                  1.10.1
types-python-dateutil         2.9.0.20241003
typing_extensions             4.8.0
tzdata                        2024.1
ujson                         5.10.0
urllib3                       2.2.3
watchdog                      6.0.0
wcwidth                       0.2.13
webencodings                  0.5.1
websockets                    11.0.3
whatthepatch                  1.0.6
wrapt                         1.16.0
yapf                          0.40.2
yarl                          1.17.1
zipp                          3.21.0
zope.interface                7.0.3

```
</details>

**Comment by ccordoba12** [comment]
Hey @jdkolcz, thanks for reporting. We'll try to fix this error in our next version (6.0.3), to be released at the end of the month.
