### ISSUE TITLE
closing tab automatically

### ISSUE THREAD

**Issue by ksresh** [spyder-ide/spyder#22964]
### What steps will reproduce the problem?

closing tab automatically. i kjngwkhiohowrgkwrihkbjhkbw,u

### Traceback
```python-traceback
Traceback (most recent call last):

  File "/opt/anaconda3/envs/tensorflow1/lib/python3.10/site-packages/spyder/plugins/run/container.py", line 214, in run_file
    self.edit_run_configurations(
  File "/opt/anaconda3/envs/tensorflow1/lib/python3.10/site-packages/spyder/plugins/run/container.py", line 232, in edit_run_configurations
    self.dialog.setup()
  File "/opt/anaconda3/envs/tensorflow1/lib/python3.10/site-packages/spyder/plugins/run/widgets.py", line 746, in setup
    self.run_conf_model.get_initial_index())
  File "/opt/anaconda3/envs/tensorflow1/lib/python3.10/site-packages/spyder/plugins/run/models.py", line 192, in get_initial_index
    return self.inverted_index[self.current_configuration]
KeyError: None
```

## Versions

* Spyder version: 6.0.1  (conda)
* Python version: 3.10.8 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: macOS-15.1-arm64-arm-64bit

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.10.5 (OK)
applaunchservices >=0.3.0        :  0.3.0 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.17.0 (OK)
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
github >=2.3.0                   :  2.4.0 (OK)
importlib_metadata >=4.6.0       :  8.5.0 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.29.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  0.9.0 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  24.3.1 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.7.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  6.1.0 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.2.7 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0         :  5.6.0 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.0.1 (OK)
setuptools >=49.6.0              :  75.3.0 (OK)
sphinx >=0.6.6                   :  7.3.7 (OK)
spyder_kernels >=3.0.0,<3.1.0    :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.2.1 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.1 (OK)
yarl >=1.9.4                     :  1.11.0 (OK)
zmq >=24.0.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  3.9.2 (OK)
numpy >=1.7                      :  1.23.5 (OK)
pandas >=1.1.1                   :  2.2.3 (OK)
scipy >=0.17.0                   :  1.14.1 (OK)
sympy >=0.7.3                    :  None (NOK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at /opt/anaconda3/envs/tensorflow1:
#
# Name                    Version                   Build  Channel
abseil-cpp                20211102.0           hc377ac9_0  
absl-py                   2.1.0           py310hca03da5_0  
aiohappyeyeballs          2.4.0           py310hca03da5_0  
aiohttp                   3.10.5          py310h80987f9_0  
aiosignal                 1.2.0              pyhd3eb1b0_0  
alabaster                 0.7.16          py310hca03da5_0  
anyio                     4.6.2.post1        pyhd8ed1ab_0    conda-forge
applaunchservices         0.3.0           py310hca03da5_0  
appnope                   0.1.4              pyhd8ed1ab_0    conda-forge
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py310h493c2e1_5    conda-forge
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
astroid                   3.2.4           py310hca03da5_0  
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3                      py_0  
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.3           py310hca03da5_0  
asyncssh                  2.17.0          py310hca03da5_0  
atomicwrites              1.4.0                      py_0  
attrs                     24.2.0             pyh71513ae_0    conda-forge
autopep8                  2.0.4              pyhd3eb1b0_0  
babel                     2.14.0             pyhd8ed1ab_0    conda-forge
bayesian-optimization     2.0.0                    pypi_0    pypi
beautifulsoup4            4.12.3             pyha770c72_0    conda-forge
binaryornot               0.4.4              pyhd3eb1b0_1  
black                     24.8.0          py310hca03da5_0  
blas                      1.0                    openblas  
bleach                    6.2.0              pyhd8ed1ab_0    conda-forge
blinker                   1.8.2              pyhd8ed1ab_0    conda-forge
boto3                     1.35.54            pyhd8ed1ab_0    conda-forge
botocore                  1.35.54         pyge310_1234567_0    conda-forge
brotli                    1.1.0                hd74edd7_2    conda-forge
brotli-bin                1.1.0                hd74edd7_2    conda-forge
brotli-python             1.1.0           py310hb4ad77e_2    conda-forge
bzip2                     1.0.8                h99b78c6_7    conda-forge
c-ares                    1.34.2               h7ab814d_0    conda-forge
ca-certificates           2024.9.24            hca03da5_0  
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.3.3           py310hca03da5_0  
cairo                     1.16.0               h302bd0f_5  
certifi                   2024.8.30       py310hca03da5_0  
cffi                      1.17.1          py310h497396d_0    conda-forge
chardet                   4.0.0           py310hca03da5_1003  
charset-normalizer        3.4.0              pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
cloudpickle               3.1.0                    pypi_0    pypi
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
contourpy                 1.3.0           py310h6000651_2    conda-forge
cookiecutter              2.6.0           py310hca03da5_0  
cryptography              41.0.3          py310h3c57c4d_0  
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
debugpy                   1.8.7           py310hb4ad77e_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
deprecated                1.2.13          py310hca03da5_0  
diff-match-patch          20200713           pyhd3eb1b0_0  
dill                      0.3.8           py310hca03da5_0  
docstring-to-markdown     0.11            py310hca03da5_0  
docutils                  0.18.1          py310hca03da5_3  
eigen                     3.4.0                h48ca7d4_0  
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
executing                 2.1.0              pyhd8ed1ab_0    conda-forge
expat                     2.6.3                h313beb8_0  
ffmpeg                    4.2.2                h04105a8_0  
flake8                    7.1.1           py310hca03da5_0  
flask                     3.0.3              pyhd8ed1ab_0    conda-forge
flatbuffers               24.3.25              h313beb8_0  
fontconfig                2.14.1               hee714a5_2  
fonttools                 4.54.1          py310h5799be4_1    conda-forge
fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               hadb7bae_2    conda-forge
frozenlist                1.4.0           py310h80987f9_0  
gast                      0.6.0                    pypi_0    pypi
gettext                   0.21.0               h13f89a0_1  
giflib                    5.2.2                h80987f9_0  
glib                      2.78.4               h313beb8_0  
glib-tools                2.78.4               h313beb8_0  
gmp                       6.2.1                hc377ac9_3  
gnutls                    3.6.15               h887c41c_0  
google-auth               2.29.0          py310hca03da5_0  
google-auth-oauthlib      0.5.2           py310hca03da5_0  
google-pasta              0.2.0              pyhd3eb1b0_0  
graphite2                 1.3.14               hc377ac9_1  
grpc-cpp                  1.48.2               h877324c_0  
grpcio                    1.67.1                   pypi_0    pypi
gst-plugins-base          1.14.1               h313beb8_1  
gstreamer                 1.14.1               h80987f9_1  
gym                       0.26.2                   pypi_0    pypi
gym-notices               0.0.8                    pypi_0    pypi
h11                       0.14.0             pyhd8ed1ab_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
h5py                      3.12.1          py310h8456320_0  
harfbuzz                  4.3.0                he9eebac_1  
hdf5                      1.12.1               h160e8cb_2  
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
httpcore                  1.0.6              pyhd8ed1ab_0    conda-forge
httpx                     0.27.2             pyhd8ed1ab_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       68.1                 hc377ac9_0  
idna                      3.10               pyhd8ed1ab_0    conda-forge
imagesize                 1.4.1           py310hca03da5_0  
importlib-metadata        8.5.0              pyha770c72_0    conda-forge
importlib_metadata        8.5.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.5              pyhd8ed1ab_0    conda-forge
inflection                0.5.1           py310hca03da5_0  
intervaltree              3.1.0              pyhd3eb1b0_0  
ipykernel                 6.29.5             pyh57ce528_0    conda-forge
ipython                   8.29.0             pyh707e725_0    conda-forge
ipywidgets                8.1.5              pyhd8ed1ab_0    conda-forge
isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
isort                     5.13.2          py310hca03da5_0  
itsdangerous              2.2.0              pyhd8ed1ab_0    conda-forge
jaraco.classes            3.2.1              pyhd3eb1b0_0  
jax                       0.4.30                   pypi_0    pypi
jaxlib                    0.4.30                   pypi_0    pypi
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jellyfish                 0.9.0           py310h1a28f6b_0  
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
joblib                    1.4.2              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h80987f9_3  
json5                     0.9.25             pyhd8ed1ab_0    conda-forge
jsonpointer               3.0.0           py310hbe9552e_1    conda-forge
jsonschema                4.23.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2024.10.1          pyhd8ed1ab_0    conda-forge
jsonschema-with-format-nongpl 4.23.0               hd8ed1ab_0    conda-forge
jupyter                   1.1.1              pyhd8ed1ab_0    conda-forge
jupyter-lsp               2.2.5              pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.3              pyhd8ed1ab_0    conda-forge
jupyter_console           6.6.3              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2              pyh31011fe_1    conda-forge
jupyter_events            0.10.0             pyhd8ed1ab_0    conda-forge
jupyter_server            2.14.2             pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.5.3              pyhd8ed1ab_0    conda-forge
jupyterlab                4.2.5              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_1    conda-forge
jupyterlab_server         2.27.3             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.13             pyhd8ed1ab_0    conda-forge
kaggle                    1.6.17                   pypi_0    pypi
keras                     3.6.0                    pypi_0    pypi
keras-preprocessing       1.1.2              pyhd3eb1b0_0  
keras-tuner               1.4.7                    pypi_0    pypi
keyring                   24.3.1          py310hca03da5_0  
kiwisolver                1.4.7           py310h7306fd8_0    conda-forge
krb5                      1.20.1               h127bd45_0    conda-forge
kt-legacy                 1.0.5                    pypi_0    pypi
lame                      3.100                h1a28f6b_0  
lcms2                     2.12                 hba8e193_0  
lerc                      4.0.0                h9a09cb3_0    conda-forge
libaec                    1.1.3                hebf3989_0    conda-forge
libblas                   3.9.0           25_osxarm64_openblas    conda-forge
libbrotlicommon           1.1.0                hd74edd7_2    conda-forge
libbrotlidec              1.1.0                hd74edd7_2    conda-forge
libbrotlienc              1.1.0                hd74edd7_2    conda-forge
libcblas                  3.9.0           25_osxarm64_openblas    conda-forge
libclang                  18.1.1                   pypi_0    pypi
libcurl                   8.2.1                h0f1d93c_0  
libcxx                    19.1.3               ha82da77_0    conda-forge
libdeflate                1.22                 hd74edd7_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h93a5062_2    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_3    conda-forge
libgfortran5              13.2.0               hf226fd6_3    conda-forge
libglib                   2.78.4               h0a96307_0  
libiconv                  1.17                 h0d3ecfb_2    conda-forge
libidn2                   2.3.4                h80987f9_0  
libjpeg-turbo             2.0.0                h1a28f6b_0  
liblapack                 3.9.0           25_osxarm64_openblas    conda-forge
libllvm12                 12.0.0               h12f7ac0_4  
libnghttp2                1.52.0               h10c0552_1  
libopenblas               0.3.28          openmp_h517c56d_0    conda-forge
libopus                   1.3.1                h80987f9_1  
libpng                    1.6.39               h80987f9_0  
libpq                     12.15                h449679c_1  
libprotobuf               3.20.3               h514c7bf_0  
libsodium                 1.0.18               h1a28f6b_0  
libspatialindex           1.9.3                hc377ac9_0  
libsqlite                 3.46.0               hfb93653_0    conda-forge
libssh2                   1.10.0               h449679c_2  
libtasn1                  4.19.0               h80987f9_0  
libtiff                   4.2.0                had003b8_2  
libunistring              0.9.10               h1a28f6b_0  
libvpx                    1.10.0               hc377ac9_0  
libwebp                   1.3.2                ha3663a8_0  
libwebp-base              1.3.2                h80987f9_1  
libxcb                    1.17.0               hdb1d25a_0    conda-forge
libxml2                   2.10.4               h372ba2a_0  
libxslt                   1.1.37               habca612_0  
libzlib                   1.2.13               hfb2fe0b_6    conda-forge
llvm-openmp               19.1.3               hb52a8e5_0    conda-forge
lxml                      5.2.1           py310h50ffb84_0  
markdown                  3.7                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                3.0.2           py310h5799be4_0    conda-forge
matplotlib                3.9.2           py310hb6292c7_1    conda-forge
matplotlib-base           3.9.2           py310h2a20ac7_1    conda-forge
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
mccabe                    0.7.0              pyhd3eb1b0_0  
mdurl                     0.1.2                    pypi_0    pypi
mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
ml-dtypes                 0.3.2                    pypi_0    pypi
more-itertools            10.3.0          py310hca03da5_0  
multidict                 6.0.4           py310h80987f9_0  
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy_extensions           1.0.0           py310hca03da5_0  
namex                     0.0.8                    pypi_0    pypi
nbclient                  0.10.0             pyhd8ed1ab_0    conda-forge
nbconvert                 7.16.4               hd8ed1ab_1    conda-forge
nbconvert-core            7.16.4             pyhd8ed1ab_1    conda-forge
nbconvert-pandoc          7.16.4               hd8ed1ab_1    conda-forge
nbformat                  5.10.4             pyhd8ed1ab_0    conda-forge
ncurses                   6.5                  h7bae524_1    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
nettle                    3.7.3                h84b5d62_1  
notebook                  7.2.2              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.4              pyhd8ed1ab_0    conda-forge
nspr                      4.35                 h313beb8_0  
nss                       3.89.1               h313beb8_0  
numpy                     1.26.4                   pypi_0    pypi
numpy-base                1.23.5          py310haf87e8b_0  
numpydoc                  1.7.0           py310hca03da5_0  
oauthlib                  3.2.2           py310hca03da5_0  
opencv                    4.6.0           py310hc90a7da_5  
opencv-python             4.8.0.74                 pypi_0    pypi
openh264                  1.8.0                h98b2900_0  
openjpeg                  2.4.0                h0ed58ac_2  
openssl                   1.1.1w               h1a28f6b_0  
opt-einsum                3.4.0                    pypi_0    pypi
opt_einsum                3.3.0              pyhd3eb1b0_1  
optree                    0.13.0                   pypi_0    pypi
overrides                 7.7.0              pyhd8ed1ab_0    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.3           py310hfd37619_1    conda-forge
pandas-datareader         0.10.0             pyh6c4a22f_0    conda-forge
pandoc                    2.12                 hca03da5_3  
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
pathspec                  0.10.3          py310hca03da5_0  
pcre2                     10.42                hb066dcc_1  
pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.4.0          py310h80987f9_0  
pip                       24.3.1             pyh8b19718_0    conda-forge
pixman                    0.40.0               h1a28f6b_0  
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.3.6              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0           py310hca03da5_1  
ply                       3.11            py310hca03da5_0  
prometheus_client         0.21.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.48             pyha770c72_0    conda-forge
prompt_toolkit            3.0.48               hd8ed1ab_0    conda-forge
protobuf                  4.25.5                   pypi_0    pypi
psutil                    6.1.0           py310hf9df320_0    conda-forge
pthread-stubs             0.4               hd74edd7_1002    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.3              pyhd8ed1ab_0    conda-forge
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                      py_0  
pycodestyle               2.12.1          py310hca03da5_0  
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pydocstyle                6.3.0           py310hca03da5_0  
pyflakes                  3.2.0           py310hca03da5_0  
pyforest                  1.1.2                    pypi_0    pypi
pygithub                  2.4.0           py310hca03da5_0  
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyjwt                     2.8.0           py310hca03da5_0  
pylint                    3.2.7           py310hca03da5_0  
pylint-venv               3.0.3           py310hca03da5_0  
pyls-spyder               0.4.0              pyhd3eb1b0_0  
pynacl                    1.5.0           py310h1a28f6b_0  
pyobjc-core               10.3.1          py310hb3dec1a_1    conda-forge
pyobjc-framework-cocoa    10.3.1          py310hb3dec1a_1    conda-forge
pyobjc-framework-coreservices 10.1            py310hdd8dd1f_0  
pyobjc-framework-fsevents 10.1            py310hca03da5_0  
pyopenssl                 23.2.0          py310hca03da5_0  
pyparsing                 3.2.0              pyhd8ed1ab_1    conda-forge
pyqt                      5.15.10         py310h313beb8_0  
pyqt5-sip                 12.13.0         py310h80987f9_0  
pyqtwebengine             5.15.10         py310h313beb8_0  
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.8          hf452327_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.20.0             pyhd8ed1ab_0    conda-forge
python-flatbuffers        24.3.25         py310hca03da5_0  
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-lsp-black          2.0.0           py310hca03da5_0  
python-lsp-jsonrpc        1.1.2              pyhd3eb1b0_0  
python-lsp-server         1.12.0          py310h33ce5c2_0  
python-slugify            8.0.4                    pypi_0    pypi
python-tzdata             2024.2             pyhd8ed1ab_0    conda-forge
python.app                3               py310h80987f9_1  
python_abi                3.10                    5_cp310    conda-forge
pytoolconfig              1.2.6           py310hca03da5_0  
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyuca                     1.2             py310hca03da5_1  
pyyaml                    6.0.2           py310h493c2e1_1    conda-forge
pyzmq                     25.1.2          py310h313beb8_0  
qdarkstyle                3.2.3              pyhd3eb1b0_0  
qhull                     2020.2               h420ef59_5    conda-forge
qstylizer                 0.2.2           py310hca03da5_0  
qt-main                   5.15.2               ha2d02b5_7  
qt-webengine              5.15.9               h2903aaf_7  
qtawesome                 1.3.1           py310hca03da5_0  
qtconsole                 5.6.0           py310hca03da5_0  
qtpy                      2.4.1           py310hca03da5_0  
qtwebkit                  5.212                h19f419d_5  
re2                       2022.04.01           hc377ac9_0  
readline                  8.2                  h92ec313_1    conda-forge
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
requests-oauthlib         2.0.0           py310hca03da5_0  
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rich                      13.9.4                   pypi_0    pypi
rope                      1.12.0          py310hca03da5_0  
rpds-py                   0.20.1          py310hde4708a_0    conda-forge
rsa                       4.7.2              pyhd3eb1b0_1  
rtree                     1.0.1           py310hca03da5_0  
s3transfer                0.10.3             pyhd8ed1ab_0    conda-forge
scikit-learn              1.5.2           py310h0b94ddc_1    conda-forge
scipy                     1.14.1          py310hc05a576_1    conda-forge
seaborn                   0.13.2                   pypi_0    pypi
send2trash                1.8.3              pyh31c8845_0    conda-forge
setuptools                75.3.0             pyhd8ed1ab_0    conda-forge
sip                       6.7.12          py310h313beb8_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.2.1                h313beb8_0  
sniffio                   1.3.1              pyhd8ed1ab_0    conda-forge
snowballstemmer           2.2.0              pyhd3eb1b0_0  
sortedcontainers          2.4.0              pyhd3eb1b0_0  
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
sphinx                    7.3.7           py310hca03da5_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.10          py310hca03da5_0  
spyder                    6.0.1           py310hca03da5_0  
spyder-kernels            3.0.0           py310h33ce5c2_0  
sqlite                    3.45.3               h80987f9_0  
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
superqt                   0.6.7           py310h33ce5c2_0  
tabulate                  0.9.0           py310hca03da5_0  
tensorboard               2.16.2                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1           py310hca03da5_0  
tensorflow                2.16.2                   pypi_0    pypi
tensorflow-base           2.12.0          eigen_py310h0a52ebb_0  
tensorflow-estimator      2.12.0          py310hca03da5_0  
tensorflow-io-gcs-filesystem 0.37.1                   pypi_0    pypi
tensorflow-macos          2.16.2                   pypi_0    pypi
tensorflow-metal          1.1.0                    pypi_0    pypi
termcolor                 2.5.0                    pypi_0    pypi
terminado                 0.18.1             pyh31c8845_0    conda-forge
text-unidecode            1.3                pyhd3eb1b0_0  
textdistance              4.2.1              pyhd3eb1b0_0  
threadpoolctl             3.5.0              pyhc1e730c_0    conda-forge
three-merge               0.1.1              pyhd3eb1b0_0  
tinycss2                  1.4.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h5083fa2_1    conda-forge
tomli                     2.0.2              pyhd8ed1ab_0    conda-forge
tomlkit                   0.13.2          py310hca03da5_0  
tornado                   6.4.1           py310h493c2e1_1    conda-forge
tqdm                      4.66.6             pyhd8ed1ab_0    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
types-python-dateutil     2.9.0.20241003     pyhff2d567_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
ujson                     5.10.0          py310h313beb8_0  
unicodedata2              15.1.0          py310hf9df320_1    conda-forge
unidecode                 1.3.8           py310hca03da5_0  
uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
urllib3                   2.2.3              pyhd8ed1ab_0    conda-forge
watchdog                  4.0.1           py310h80987f9_0  
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
webcolors                 24.8.0             pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
websocket-client          1.8.0              pyhd8ed1ab_0    conda-forge
werkzeug                  3.1.1              pyhd8ed1ab_0    conda-forge
whatthepatch              1.0.2           py310hca03da5_0  
wheel                     0.35.1             pyhd3eb1b0_0  
widgetsnbextension        4.0.13             pyhd8ed1ab_0    conda-forge
wrapt                     1.16.0                   pypi_0    pypi
wurlitzer                 3.0.2           py310hca03da5_0  
x264                      1!152.20180806       h1a28f6b_0  
xorg-libxau               1.0.11               hd74edd7_1    conda-forge
xorg-libxdmcp             1.1.5                hd74edd7_0    conda-forge
xz                        5.4.6                h80987f9_1  
yaml                      0.2.5                h3422bc3_2    conda-forge
yapf                      0.40.2          py310hca03da5_0  
yarl                      1.11.0          py310h80987f9_0  
zeromq                    4.3.5                h313beb8_0  
zipp                      3.20.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hfb2fe0b_6    conda-forge
zstandard                 0.23.0          py310h2665a74_1    conda-forge
zstd                      1.5.6                hb46c0d2_0    conda-forge

```
</details>

**Comment by dalthviz** [comment]
Hi @ksresh thank you for the report! I think this could be a duplicate of https://github.com/spyder-ide/spyder/issues/22607 A fix for that issue was done over PR https://github.com/spyder-ide/spyder/pull/22819 and it will be part of the upcoming Spyder 6.0.3, so once Spyder 6.0.3 is released updating Spyder should be enough to prevent this issue.

Let us know if the info above helps!

**Comment by ccordoba12** [comment]
Hey @ksresh, thanks for reporting. This error should be fixed in our latest version (6.0.3).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with Conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-env -c conda-forge spyder
        conda activate spyder-env
        spyder

If you need to use more packages than just Spyder, you have to:

1. Follow [our documentation](https://docs.spyder-ide.org/5/faq.html#using-packages-installer) about that in case you're using our installer.
2. If you followed the Conda-forge path, you need to close Spyder, open the Anaconda Prompt and run

        conda activate spyder-env
        conda install scikit-learn

    in case you need to work with Scikit-Learn, or do the same for the packages you need to install.
