### ISSUE TITLE
Start Spyder with --show-console

### ISSUE THREAD

**Issue by gs112145** [spyder-ide/spyder#22991]
### What steps will reproduce the problem?

I'm starting Spyder from the console with the following params:
spyder --show-console
(Deprecated) --show console does nothing, now the default  behavior is to show the console, use --hide-console if you want to hide it

### Traceback
```python-traceback

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\gs1\anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\app\start.py", line 286, in main
    mainwindow.main(options, args)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\app\mainwindow.py", line 1425, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\app\utils.py", line 412, in create_window
    app.exec_()
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\utils\kernel_handler.py", line 279, in check_spyder_kernel_info
    self.handle_comm_ready()
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\utils\kernel_handler.py", line 294, in handle_comm_ready
    self.sig_kernel_is_ready.emit()
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 322, in handle_kernel_is_ready
    self._show_banner()
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 1201, in _show_banner
    banner = self.long_banner()
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 785, in long_banner
    env_info = self.get_pythonenv_info()
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 1079, in get_pythonenv_info
    ).get_pythonenv_info()
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder_kernels\comms\commbase.py", line 611, in __call__
    return self._comms_wrapper._get_call_return_value(
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 171, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder_kernels\comms\commbase.py", line 464, in _get_call_return_value
    self._wait_reply(comm_id, call_id, call_name, timeout)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 195, in _wait_reply
    self._wait(got_reply, self._sig_got_reply, timeout_msg, timeout)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 233, in _wait
    wait_loop.exec_()
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\widgets\collectionseditor.py", line 473, in data
    display = value_to_display(value, minmax=self.minmax)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder_kernels\utils\nsview.py", line 364, in value_to_display
    elif isinstance(value, pd.DataFrame):
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder_kernels\utils\lazymodules.py", line 50, in __getattr__
    if is_module_installed(self.__spy_modname__):
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder_kernels\utils\misc.py", line 22, in is_module_installed
    mod = __import__(module_name)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\pandas\__init__.py", line 26, in <module>
    from pandas.compat import (
  File "C:\Users\gs1\anaconda3\Lib\site-packages\pandas\compat\__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\gs1\anaconda3\Lib\site-packages\pandas\compat\pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "C:\Users\gs1\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
Traceback (most recent call last):
  File "C:\Users\gs1\anaconda3\Lib\site-packages\numpy\core\_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\gs1\anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\app\start.py", line 286, in main
    mainwindow.main(options, args)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\app\mainwindow.py", line 1425, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\app\utils.py", line 412, in create_window
    app.exec_()
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\utils\kernel_handler.py", line 279, in check_spyder_kernel_info
    self.handle_comm_ready()
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\utils\kernel_handler.py", line 294, in handle_comm_ready
    self.sig_kernel_is_ready.emit()
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 322, in handle_kernel_is_ready
    self._show_banner()
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 1201, in _show_banner
    banner = self.long_banner()
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 785, in long_banner
    env_info = self.get_pythonenv_info()
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 1079, in get_pythonenv_info
    ).get_pythonenv_info()
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder_kernels\comms\commbase.py", line 611, in __call__
    return self._comms_wrapper._get_call_return_value(
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 171, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder_kernels\comms\commbase.py", line 464, in _get_call_return_value
    self._wait_reply(comm_id, call_id, call_name, timeout)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 195, in _wait_reply
    self._wait(got_reply, self._sig_got_reply, timeout_msg, timeout)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 233, in _wait
    wait_loop.exec_()
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\widgets\collectionseditor.py", line 473, in data
    display = value_to_display(value, minmax=self.minmax)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder_kernels\utils\nsview.py", line 364, in value_to_display
    elif isinstance(value, pd.DataFrame):
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder_kernels\utils\lazymodules.py", line 50, in __getattr__
    if is_module_installed(self.__spy_modname__):
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder_kernels\utils\misc.py", line 22, in is_module_installed
    mod = __import__(module_name)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\pandas\__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "C:\Users\gs1\anaconda3\Lib\site-packages\pandas\core\api.py", line 1, in <module>
    from pandas._libs import (
  File "C:\Users\gs1\anaconda3\Lib\site-packages\pandas\_libs\__init__.py", line 17, in <module>
    import pandas._libs.pandas_datetime  # noqa: F401 # isort: skip # type: ignore[reportUnusedImport]
Traceback (most recent call last):
  File "C:\Users\gs1\anaconda3\Lib\site-packages\numpy\core\_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\plugins\application\container.py", line 234, in _compute_dependencies
    dependencies.declare_dependencies()
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\dependencies.py", line 485, in declare_dependencies
    add(dep['modname'], dep['package_name'],
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\dependencies.py", line 416, in add
    DEPENDENCIES += [Dependency(modname, package_name, features,
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\dependencies.py", line 355, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\utils\programs.py", line 1004, in get_module_version
    mod = __import__(module_name)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\matplotlib\__init__.py", line 159, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:\Users\gs1\anaconda3\Lib\site-packages\matplotlib\rcsetup.py", line 28, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Users\gs1\anaconda3\Lib\site-packages\matplotlib\colors.py", line 57, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "C:\Users\gs1\anaconda3\Lib\site-packages\matplotlib\scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "C:\Users\gs1\anaconda3\Lib\site-packages\matplotlib\ticker.py", line 144, in <module>
    from matplotlib import transforms as mtransforms
  File "C:\Users\gs1\anaconda3\Lib\site-packages\matplotlib\transforms.py", line 49, in <module>
    from matplotlib._path import (
Traceback (most recent call last):
  File "C:\Users\gs1\anaconda3\Lib\site-packages\numpy\core\_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\plugins\application\container.py", line 234, in _compute_dependencies
    dependencies.declare_dependencies()
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\dependencies.py", line 485, in declare_dependencies
    add(dep['modname'], dep['package_name'],
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\dependencies.py", line 416, in add
    DEPENDENCIES += [Dependency(modname, package_name, features,
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\dependencies.py", line 355, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\utils\programs.py", line 1004, in get_module_version
    mod = __import__(module_name)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\pandas\__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "C:\Users\gs1\anaconda3\Lib\site-packages\pandas\core\api.py", line 1, in <module>
    from pandas._libs import (
  File "C:\Users\gs1\anaconda3\Lib\site-packages\pandas\_libs\__init__.py", line 17, in <module>
    import pandas._libs.pandas_datetime  # noqa: F401 # isort: skip # type: ignore[reportUnusedImport]
Traceback (most recent call last):
  File "C:\Users\gs1\anaconda3\Lib\site-packages\numpy\core\_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\gs1\anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\app\start.py", line 286, in main
    mainwindow.main(options, args)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\app\mainwindow.py", line 1425, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\app\utils.py", line 412, in create_window
    app.exec_()
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\plugins\application\container.py", line 221, in _set_dependencies
    self.dependencies_dialog.set_data(dependencies.DEPENDENCIES)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\widgets\dependencies.py", line 182, in set_data
    self.treewidget.update_dependencies(dependencies)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\widgets\dependencies.py", line 63, in update_dependencies
    if dependency.check():
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\dependencies.py", line 376, in check
    installed = programs.is_module_installed(
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\utils\programs.py", line 1050, in is_module_installed
    module_version = get_module_version(module_name)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\utils\programs.py", line 1004, in get_module_version
    mod = __import__(module_name)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\matplotlib\__init__.py", line 159, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:\Users\gs1\anaconda3\Lib\site-packages\matplotlib\rcsetup.py", line 28, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Users\gs1\anaconda3\Lib\site-packages\matplotlib\colors.py", line 57, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "C:\Users\gs1\anaconda3\Lib\site-packages\matplotlib\scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "C:\Users\gs1\anaconda3\Lib\site-packages\matplotlib\ticker.py", line 144, in <module>
    from matplotlib import transforms as mtransforms
  File "C:\Users\gs1\anaconda3\Lib\site-packages\matplotlib\transforms.py", line 49, in <module>
    from matplotlib._path import (
Traceback (most recent call last):
  File "C:\Users\gs1\anaconda3\Lib\site-packages\numpy\core\_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\gs1\anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\app\start.py", line 286, in main
    mainwindow.main(options, args)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\app\mainwindow.py", line 1425, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\app\utils.py", line 412, in create_window
    app.exec_()
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\plugins\application\container.py", line 221, in _set_dependencies
    self.dependencies_dialog.set_data(dependencies.DEPENDENCIES)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\widgets\dependencies.py", line 182, in set_data
    self.treewidget.update_dependencies(dependencies)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\widgets\dependencies.py", line 63, in update_dependencies
    if dependency.check():
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\dependencies.py", line 376, in check
    installed = programs.is_module_installed(
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\utils\programs.py", line 1050, in is_module_installed
    module_version = get_module_version(module_name)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\spyder\utils\programs.py", line 1004, in get_module_version
    mod = __import__(module_name)
  File "C:\Users\gs1\anaconda3\Lib\site-packages\pandas\__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "C:\Users\gs1\anaconda3\Lib\site-packages\pandas\core\api.py", line 1, in <module>
    from pandas._libs import (
  File "C:\Users\gs1\anaconda3\Lib\site-packages\pandas\_libs\__init__.py", line 17, in <module>
    import pandas._libs.pandas_datetime  # noqa: F401 # isort: skip # type: ignore[reportUnusedImport]
Traceback (most recent call last):
  File "C:\Users\gs1\anaconda3\Lib\site-packages\numpy\core\_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.


```

## Versions

* Spyder version: 6.0.1  (conda)
* Python version: 3.12.7 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-11-10.0.22631-SP0

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.10.5 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.17.0 (OK)
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
github >=2.3.0                   :  2.4.0 (OK)
importlib_metadata >=4.6.0       :  7.0.1 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.27.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.1 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  24.3.1 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.7.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.0 (OK)
pygments >=2.0                   :  2.15.1 (OK)
pylint >=3.1,<4                  :  3.2.7 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0         :  5.6.0 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.0.1 (OK)
setuptools >=49.6.0              :  75.1.0 (OK)
sphinx >=0.6.6                   :  7.3.7 (OK)
spyder_kernels >=3.0.0,<3.1.0    :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.2.1 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.1 (OK)
yarl >=1.9.4                     :  1.11.0 (OK)
zmq >=24.0.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  None (NOK)
numpy >=1.7                      :  2.0.2 (OK)
pandas >=1.1.1                   :  None (NOK)
scipy >=0.17.0                   :  1.13.1 (OK)
sympy >=0.7.3                    :  1.13.2 (OK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at C:\Users\gs1\anaconda3\envs\address_cpys:
#
# Name                    Version                   Build  Channel
annotated-types           0.7.0              pyhd8ed1ab_0    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.3             pyha770c72_0    conda-forge
brotli-python             1.1.0           py311hda3d55a_2    conda-forge
bzip2                     1.0.8                h2466b09_7    conda-forge
ca-certificates           2024.8.30            h56e8100_0    conda-forge
catalogue                 2.0.10          py311h1ea47a8_0    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py311he736701_0    conda-forge
charset-normalizer        3.4.0              pyhd8ed1ab_0    conda-forge
click                     8.1.7           win_pyh7428d3b_0    conda-forge
cloudpathlib              0.20.0             pyhd8ed1ab_0    conda-forge
cloudpickle               3.1.0              pyhd8ed1ab_1    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
confection                0.1.4           py311h3810d55_0    conda-forge
cpython                   3.11.10         py311hd8ed1ab_3    conda-forge
cymem                     2.0.8           py311hda3d55a_2    conda-forge
cython-blis               0.7.10          py311h59ca53f_2    conda-forge
debugpy                   1.8.7           py311hda3d55a_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
en-core-web-sm            3.7.1                    pypi_0    pypi
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
executing                 2.1.0              pyhd8ed1ab_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
idna                      3.10               pyhd8ed1ab_0    conda-forge
importlib-metadata        8.5.0              pyha770c72_0    conda-forge
intel-openmp              2024.2.1          h57928b3_1083    conda-forge
ipykernel                 6.29.5             pyh4bbf305_0    conda-forge
ipython                   8.29.0             pyh7428d3b_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.3              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2              pyh5737063_1    conda-forge
krb5                      1.21.3               hdf4eb48_0    conda-forge
langcodes                 3.4.1              pyhd8ed1ab_0    conda-forge
language-data             1.2.0              pyhd8ed1ab_0    conda-forge
libblas                   3.9.0              25_win64_mkl    conda-forge
libcblas                  3.9.0              25_win64_mkl    conda-forge
libexpat                  2.6.3                he0c23c2_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libhwloc                  2.11.1          default_h8125262_1000    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
liblapack                 3.9.0              25_win64_mkl    conda-forge
libsodium                 1.0.20               hc70643c_0    conda-forge
libsqlite                 3.47.0               h2466b09_1    conda-forge
libxml2                   2.13.4               h442d1da_2    conda-forge
libzlib                   1.3.1                h2466b09_2    conda-forge
marisa-trie               1.2.0           py311hda3d55a_0    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                3.0.2           py311h5082efb_0    conda-forge
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
mdurl                     0.1.2              pyhd8ed1ab_0    conda-forge
mkl                       2024.2.2            h66d3029_14    conda-forge
murmurhash                1.0.10          py311hda3d55a_2    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
numpy                     1.26.4          py311h0b4df5a_0    conda-forge
openssl                   3.4.0                h2466b09_0    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.3           py311hcf9f919_1    conda-forge
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       24.3.1             pyh8b19718_0    conda-forge
platformdirs              4.3.6              pyhd8ed1ab_0    conda-forge
preshed                   3.0.9           py311hda3d55a_2    conda-forge
prompt-toolkit            3.0.48             pyha770c72_0    conda-forge
psutil                    6.1.0           py311he736701_0    conda-forge
pthreads-win32            2.9.1                h2466b09_4    conda-forge
pure_eval                 0.2.3              pyhd8ed1ab_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pydantic                  2.9.2              pyhd8ed1ab_0    conda-forge
pydantic-core             2.23.4          py311h533ab2d_0    conda-forge
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.11.10         hce54a09_3_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.2             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    5_cp311    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pywin32                   307             py311hda3d55a_3    conda-forge
pyzmq                     26.2.0          py311h484c95c_3    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rich                      13.9.4             pyhd8ed1ab_0    conda-forge
setuptools                75.3.0             pyhd8ed1ab_0    conda-forge
shellingham               1.5.4              pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smart-open                7.0.5                hd8ed1ab_1    conda-forge
smart_open                7.0.5              pyhd8ed1ab_1    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
spacy                     3.7.6           py311hebdfa2d_0    conda-forge
spacy-legacy              3.0.12             pyhd8ed1ab_0    conda-forge
spacy-loggers             1.0.5              pyhd8ed1ab_0    conda-forge
spyder-kernels            3.0.1           win_pyh7428d3b_0    conda-forge
srsly                     2.4.8           py311h12c1d0e_1    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
tbb                       2021.13.0            hc790b64_0    conda-forge
thinc                     8.2.5           py311hebdfa2d_0    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
tornado                   6.4.1           py311he736701_1    conda-forge
tqdm                      4.66.6             pyhd8ed1ab_0    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
typer                     0.12.5             pyhd8ed1ab_0    conda-forge
typer-slim                0.12.5             pyhd8ed1ab_0    conda-forge
typer-slim-standard       0.12.5               hd8ed1ab_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_1    conda-forge
urllib3                   2.2.3              pyhd8ed1ab_0    conda-forge
vc                        14.3                h8a93ad2_22    conda-forge
vc14_runtime              14.40.33810         hcc2c482_22    conda-forge
vs2015_runtime            14.40.33810         h3bf8584_22    conda-forge
wasabi                    1.1.2           py311h1ea47a8_1    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
weasel                    0.4.1              pyhd8ed1ab_1    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyh7428d3b_7    conda-forge
wrapt                     1.16.0          py311he736701_1    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zeromq                    4.3.5                ha9f60a1_6    conda-forge
zipp                      3.20.2             pyhd8ed1ab_0    conda-forge
zstandard                 0.23.0          py311h53056dc_1    conda-forge
zstd                      1.5.6                h0ea2cb4_0    conda-forge

```
</details>

**Comment by gs112145** [comment]
Can you tell me how to identify the  NumPy 1.x modue to fix this problem. Thanks.

**Comment by dalthviz** [comment]
Hi @gs112145, from the traceback seems like the packages showing the error are pandas, matplotlib and pyarrow. Also a check to issue https://github.com/spyder-ide/spyder/issues/22483 could be useful.

Let us know if the info above helps!
