### ISSUE TITLE
TypeError: can only concatenate list (not "NoneType") to list

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#230]
_From [nils...@googlemail.com](https://code.google.com/u/106566353379983024643/) on 2010-06-10T13:06:20Z_

What steps will reproduce the problem?

 1. Install spyerlib via svn
2. Run spyder 3. What is the expected output? 

What do you see instead?
/home/nwagner/local/bin/spyder:4: UserWarning: Module pkg_resources was already imported from /home/nwagner/local/lib64/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/pkg_resources.py, but /home/nwagner/local/lib64/python2.6/site-packages/distribute-0.6.4-py2.6.egg is being added to sys.path                                                                            
  import pkg_resources                                                                                                      
/home/nwagner/local/bin/spyder:4: UserWarning: Module site was already imported from /usr/lib64/python2.6/site.pyc, but /home/nwagner/local/lib64/python2.6/site-packages/distribute-0.6.4-py2.6.egg is being added to sys.path                         
  import pkg_resources                                                                                                      
Traceback (most recent call last):
  File "/home/nwagner/local/bin/spyder", line 5, in \<module>
    pkg_resources.run_script('spyder==1.1.0rc1', 'spyder')
  File "/home/nwagner/local/lib64/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/pkg_resources.py", line 448, in run_script
    """Yield distributions for non-duplicate projects in the working set
  File "/home/nwagner/local/lib64/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/pkg_resources.py", line 1166, in run_script
    if os.path.exists(script_filename):
  File "/home/nwagner/local/lib/python2.6/site-packages/spyder-1.1.0rc1-py2.6.egg/EGG-INFO/scripts/spyder", line 2, in \<module>
    from spyderlib import spyder
  File "/home/nwagner/local/lib/python2.6/site-packages/spyder-1.1.0rc1-py2.6.egg/spyderlib/spyder.py", line 46, in \<module>
    from spyderlib.plugins.inspector import ObjectInspector
  File "/home/nwagner/local/lib/python2.6/site-packages/spyder-1.1.0rc1-py2.6.egg/spyderlib/plugins/inspector.py", line 24, in \<module>
    from spyderlib.widgets.externalshell.pythonshell import ExtPyQsciShell
  File "/home/nwagner/local/lib/python2.6/site-packages/spyder-1.1.0rc1-py2.6.egg/spyderlib/widgets/externalshell/pythonshell.py", line 25, in \<module>
    from spyderlib.widgets.externalshell.globalsexplorer import GlobalsExplorer
  File "/home/nwagner/local/lib/python2.6/site-packages/spyder-1.1.0rc1-py2.6.egg/spyderlib/widgets/externalshell/globalsexplorer.py", line 20, in \<module>
    from spyderlib.widgets.externalshell.monitor import (monitor_get_remote_view,
  File "/home/nwagner/local/lib/python2.6/site-packages/spyder-1.1.0rc1-py2.6.egg/spyderlib/widgets/externalshell/monitor.py", line 12, in \<module>
    from spyderlib.utils.iofuncs import iofunctions
  File "/home/nwagner/local/lib/python2.6/site-packages/spyder-1.1.0rc1-py2.6.egg/spyderlib/utils/iofuncs.py", line 361, in \<module>
    iofunctions.setup()
  File "/home/nwagner/local/lib/python2.6/site-packages/spyder-1.1.0rc1-py2.6.egg/spyderlib/utils/iofuncs.py", line 284, in setup
    iofuncs = self.get_internal_funcs()+self.get_3rd_party_funcs()
TypeError: can only concatenate list (not "NoneType") to list What version of the product are you using? On what operating system? 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=230_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-06-10T13:17:45Z_

**Status:** Fixed
