### ISSUE TITLE
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash.

### ISSUE THREAD

**Issue by andreiajc** [spyder-ide/spyder#23007]
### What steps will reproduce the problem?

# I have the following issue when I open my spyder on Anaconda

### Traceback
```python-traceback

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/plugins/application/container.py", line 234, in _compute_dependencies
    dependencies.declare_dependencies()
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/dependencies.py", line 485, in declare_dependencies
    add(dep['modname'], dep['package_name'],
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/dependencies.py", line 416, in add
    DEPENDENCIES += [Dependency(modname, package_name, features,
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/dependencies.py", line 355, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/utils/programs.py", line 1004, in get_module_version
    mod = __import__(module_name)
  File "/opt/anaconda3/lib/python3.12/site-packages/matplotlib/__init__.py", line 159, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/opt/anaconda3/lib/python3.12/site-packages/matplotlib/rcsetup.py", line 28, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/opt/anaconda3/lib/python3.12/site-packages/matplotlib/colors.py", line 57, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "/opt/anaconda3/lib/python3.12/site-packages/matplotlib/scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "/opt/anaconda3/lib/python3.12/site-packages/matplotlib/ticker.py", line 144, in <module>
    from matplotlib import transforms as mtransforms
  File "/opt/anaconda3/lib/python3.12/site-packages/matplotlib/transforms.py", line 49, in <module>
    from matplotlib._path import (
Traceback (most recent call last):
  File "/Users/andreiajuliana/.local/lib/python3.12/site-packages/numpy/core/_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/plugins/application/container.py", line 234, in _compute_dependencies
    dependencies.declare_dependencies()
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/dependencies.py", line 485, in declare_dependencies
    add(dep['modname'], dep['package_name'],
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/dependencies.py", line 416, in add
    DEPENDENCIES += [Dependency(modname, package_name, features,
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/dependencies.py", line 355, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/utils/programs.py", line 1004, in get_module_version
    mod = __import__(module_name)
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/__init__.py", line 26, in <module>
    from pandas.compat import (
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/compat/__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/compat/pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "/opt/anaconda3/lib/python3.12/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
Traceback (most recent call last):
  File "/Users/andreiajuliana/.local/lib/python3.12/site-packages/numpy/core/_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/plugins/application/container.py", line 234, in _compute_dependencies
    dependencies.declare_dependencies()
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/dependencies.py", line 485, in declare_dependencies
    add(dep['modname'], dep['package_name'],
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/dependencies.py", line 416, in add
    DEPENDENCIES += [Dependency(modname, package_name, features,
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/dependencies.py", line 355, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/utils/programs.py", line 1004, in get_module_version
    mod = __import__(module_name)
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/core/api.py", line 1, in <module>
    from pandas._libs import (
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/_libs/__init__.py", line 17, in <module>
    import pandas._libs.pandas_datetime  # noqa: F401 # isort: skip # type: ignore[reportUnusedImport]
Traceback (most recent call last):
  File "/Users/andreiajuliana/.local/lib/python3.12/site-packages/numpy/core/_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/app/start.py", line 286, in main
    mainwindow.main(options, args)
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/app/mainwindow.py", line 1425, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/app/utils.py", line 412, in create_window
    app.exec_()
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/plugins/application/container.py", line 221, in _set_dependencies
    self.dependencies_dialog.set_data(dependencies.DEPENDENCIES)
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/widgets/dependencies.py", line 182, in set_data
    self.treewidget.update_dependencies(dependencies)
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/widgets/dependencies.py", line 63, in update_dependencies
    if dependency.check():
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/dependencies.py", line 376, in check
    installed = programs.is_module_installed(
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/utils/programs.py", line 1050, in is_module_installed
    module_version = get_module_version(module_name)
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/utils/programs.py", line 1004, in get_module_version
    mod = __import__(module_name)
  File "/opt/anaconda3/lib/python3.12/site-packages/matplotlib/__init__.py", line 159, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/opt/anaconda3/lib/python3.12/site-packages/matplotlib/rcsetup.py", line 28, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/opt/anaconda3/lib/python3.12/site-packages/matplotlib/colors.py", line 57, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "/opt/anaconda3/lib/python3.12/site-packages/matplotlib/scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "/opt/anaconda3/lib/python3.12/site-packages/matplotlib/ticker.py", line 144, in <module>
    from matplotlib import transforms as mtransforms
  File "/opt/anaconda3/lib/python3.12/site-packages/matplotlib/transforms.py", line 49, in <module>
    from matplotlib._path import (
Traceback (most recent call last):
  File "/Users/andreiajuliana/.local/lib/python3.12/site-packages/numpy/core/_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/app/start.py", line 286, in main
    mainwindow.main(options, args)
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/app/mainwindow.py", line 1425, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/app/utils.py", line 412, in create_window
    app.exec_()
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/plugins/application/container.py", line 221, in _set_dependencies
    self.dependencies_dialog.set_data(dependencies.DEPENDENCIES)
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/widgets/dependencies.py", line 182, in set_data
    self.treewidget.update_dependencies(dependencies)
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/widgets/dependencies.py", line 63, in update_dependencies
    if dependency.check():
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/dependencies.py", line 376, in check
    installed = programs.is_module_installed(
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/utils/programs.py", line 1050, in is_module_installed
    module_version = get_module_version(module_name)
  File "/opt/anaconda3/lib/python3.12/site-packages/spyder/utils/programs.py", line 1004, in get_module_version
    mod = __import__(module_name)
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/core/api.py", line 1, in <module>
    from pandas._libs import (
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/_libs/__init__.py", line 17, in <module>
    import pandas._libs.pandas_datetime  # noqa: F401 # isort: skip # type: ignore[reportUnusedImport]
Traceback (most recent call last):
  File "/Users/andreiajuliana/.local/lib/python3.12/site-packages/numpy/core/_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.


```

## Versions

* Spyder version: 6.0.1  (conda)
* Python version: 3.12.7 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: macOS-10.15.7-x86_64-i386-64bit

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.10.5 (OK)
applaunchservices >=0.3.0        :  0.3.0 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.17.0 (OK)
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
github >=2.3.0                   :  2.4.0 (OK)
importlib_metadata >=4.6.0       :  7.0.1 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.27.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.1 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  24.3.1 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.7.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.0 (OK)
pygments >=2.0                   :  2.15.1 (OK)
pylint >=3.1,<4                  :  3.2.7 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0         :  5.6.0 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.0.1 (OK)
setuptools >=49.6.0              :  75.1.0 (OK)
sphinx >=0.6.6                   :  7.3.7 (OK)
spyder_kernels >=3.0.0,<3.1.0    :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.2.1 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.1 (OK)
yarl >=1.9.4                     :  1.11.0 (OK)
zmq >=24.0.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  None (NOK)
numpy >=1.7                      :  2.1.3 (OK)
pandas >=1.1.1                   :  None (NOK)
scipy >=0.17.0                   :  1.13.1 (OK)
sympy >=0.7.3                    :  1.13.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @andreiajc, thanks for reporting. This problem happens because you used pip to install Numpy, or a package that depends on it, in your Anaconda installation.

To fix it, you need to close Spyder and any other Python program you have open, open a terminal and run

    rm -Rf /Users/andreiajuliana/.local/lib/python3.12

If the problem persists, I'm afraid you'll have to remove and reinstall Anaconda. To properly do that, please follow the instructions in the second part of [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) (the first part explains why you can't mix pip and conda packages).

And let us know if you manage to solve this problem.

**Comment by ccordoba12** [comment]
Ok, sorry to hear that. Don't hesitate to post additional comments in case you have problems while doing it.

**Comment by ccordoba12** [comment]
Hopefully everything went well for you with the Anaconda reinstallation.

I'm going to close this issue now since there's not much else we can do for you.

**Comment by giritharv** [comment]
hey im getting the same error

**Comment by ccordoba12** [comment]
Hey @giritharv. To solve this problem for good, I'm afraid you'll have to remove and reinstall Anaconda. And to properly do that, please follow the instructions in the second part of [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) about that (the first part describes in more detail why you can't mix pip and conda packages).
