### ISSUE TITLE
Unable to start my Spyder

### ISSUE THREAD

**Issue by StonerYan** [spyder-ide/spyder#2300]
My Os: Windows 8.1 32bit

C:\Users\Administrator>spyder
Traceback (most recent call last):
  File "D:\Anaconda\Scripts\spyder-script.py", line 1, in <module>
    from spyderlib import start_app
  File "D:\Anaconda\lib\site-packages\spyderlib\start_app.py", line 14, in <modu
le>
    from spyderlib.config import CONF
  File "D:\Anaconda\lib\site-packages\spyderlib\config.py", line 22, in <module>
    from spyderlib.utils import iofuncs, codeanalysis
  File "D:\Anaconda\lib\site-packages\spyderlib\utils\iofuncs.py", line 26, in <
module>
    import pandas as pd
  File "D:\Anaconda\lib\site-packages\pandas\__init__.py", line 47, in <module>
    import pandas.core.config_init
  File "D:\Anaconda\lib\site-packages\pandas\core\config_init.py", line 17, in <
module>
    from pandas.core.format import detect_console_encoding
  File "D:\Anaconda\lib\site-packages\pandas\core\format.py", line 24, in <modul
e>
    from pandas.tseries.period import PeriodIndex, DatetimeIndex
  File "D:\Anaconda\lib\site-packages\pandas\tseries\period.py", line 8, in <mod
ule>
    import pandas.tseries.frequencies as frequencies
  File "D:\Anaconda\lib\site-packages\pandas\tseries\frequencies.py", line 9, in
 <module>
    from pandas.tseries.offsets import DateOffset
  File "D:\Anaconda\lib\site-packages\pandas\tseries\offsets.py", line 2152, in
<module>
    class Nano(Tick):
  File "D:\Anaconda\lib\site-packages\pandas\tseries\offsets.py", line 2153, in
Nano
    _inc = Timedelta(nanoseconds=1)
  File "pandas\tslib.pyx", line 1722, in pandas.tslib.Timedelta.__new__ (pandas\
tslib.c:29720)
ValueError: cannot construct a TimeDelta from the passed arguments, allowed keyw
ords are [days, seconds, microseconds, milliseconds, minutes, hours, weeks]

**Comment by ccordoba12** [comment]
@StonerYan, what's your pandas version?

----

@blink1073, this is killing me! Why on earth pandas is breaking us like that?

Should we surround our importing of pandas in `iofuncs` like this

```python
try:
    import pandas as pd
except:
    pd = None
```

to avoid this kind of ugly crashes?

**Comment by jreback** [comment]
you don't have a completed install, prob because it was running when you updated

try

```
conda remove pandas
conda install pandas -f
```

**Comment by blink1073** [comment]
@ccordoba12, I'd say yes, we don't want an optional feature to bring down the whole IDE.

**Comment by ccordoba12** [comment]
Thanks @jreback. @StonerYan, could you confirm @jreback suggestion?

@blink1073, I'll do the change :-)
