### ISSUE TITLE
Error when linking notebook to console

### ISSUE THREAD

**Issue by bakj1979** [spyder-ide/spyder#23059]
### What steps will reproduce the problem?

Open spyder notebook, run notebook, launch console linked to notebook, remove variables, run notebook again.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/Users/jeffreybaker/miniforge3/envs/spyder-env/lib/python3.12/site-packages/spyder_notebook/notebookplugin.py", line 106, in _open_console
    ipyconsole.create_client_for_kernel(connection_file)
  File "/Users/jeffreybaker/miniforge3/envs/spyder-env/lib/python3.12/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 749, in create_client_for_kernel
    return self.get_widget().create_client_for_kernel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeffreybaker/miniforge3/envs/spyder-env/lib/python3.12/site-packages/spyder/plugins/ipythonconsole/widgets/main_widget.py", line 1767, in create_client_for_kernel
    client = ClientWidget(
             ^^^^^^^^^^^^^
  File "/Users/jeffreybaker/miniforge3/envs/spyder-env/lib/python3.12/site-packages/spyder/plugins/ipythonconsole/widgets/client.py", line 173, in __init__
    self.layout.addWidget(self.infowidget)
RuntimeError: wrapped C/C++ object of type FrameWebView has been deleted
Traceback (most recent call last):
  File "/Users/jeffreybaker/miniforge3/envs/spyder-env/lib/python3.12/site-packages/spyder_notebook/notebookplugin.py", line 106, in _open_console
    ipyconsole.create_client_for_kernel(connection_file)
  File "/Users/jeffreybaker/miniforge3/envs/spyder-env/lib/python3.12/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 749, in create_client_for_kernel
    return self.get_widget().create_client_for_kernel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeffreybaker/miniforge3/envs/spyder-env/lib/python3.12/site-packages/spyder/plugins/ipythonconsole/widgets/main_widget.py", line 1767, in create_client_for_kernel
    client = ClientWidget(
             ^^^^^^^^^^^^^
  File "/Users/jeffreybaker/miniforge3/envs/spyder-env/lib/python3.12/site-packages/spyder/plugins/ipythonconsole/widgets/client.py", line 173, in __init__
    self.layout.addWidget(self.infowidget)
RuntimeError: wrapped C/C++ object of type FrameWebView has been deleted
```

## Versions

* Spyder version: 6.0.2  (conda)
* Python version: 3.12.7 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: macOS-15.2-arm64-arm-64bit

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                      :  3.10.10 (OK)
applaunchservices >=0.3.0            :  0.3.0 (OK)
asyncssh >=2.14.0,<3.0.0             :  2.18.0 (OK)
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.2.0 (OK)
cloudpickle >=0.5.0                  :  3.1.0 (OK)
cookiecutter >=1.6.0                 :  2.6.0 (OK)
diff_match_patch >=20181111          :  20241021 (OK)
github >=2.3.0                       :  2.5.0 (OK)
importlib_metadata >=4.6.0           :  8.5.0 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1     :  8.29.0 (OK)
jedi >=0.17.2,<0.20.0                :  0.19.2 (OK)
jellyfish >=0.7                      :  1.1.0 (OK)
jsonschema >=3.2.0                   :  4.23.0 (OK)
keyring >=17.0.0                     :  25.5.0 (OK)
nbconvert >=4.0                      :  7.16.4 (OK)
numpydoc >=0.6.0                     :  1.8.0 (OK)
parso >=0.7.0,<0.9.0                 :  0.8.4 (OK)
pexpect >=4.4.0                      :  4.9.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  6.1.0 (OK)
pygments >=2.0                       :  2.18.0 (OK)
pylint >=3.1,<4                      :  3.3.1 (OK)
pylint_venv >=3.0.2                  :  3.0.4 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0               :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0           :  2.0.0 (OK)
pyuca >=1.2                          :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0            :  3.2.3 (OK)
qstylizer >=0.2.2                    :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0             :  1.3.1 (OK)
qtconsole >=5.6.1,<5.7.0             :  5.6.1 (OK)
qtpy >=2.4.0                         :  2.4.2 (OK)
rtree >=0.9.7                        :  1.3.0 (OK)
setuptools >=49.6.0                  :  75.3.0 (OK)
sphinx >=0.6.6                       :  8.1.3 (OK)
spyder_kernels >=3.0.1,<3.1.0        :  3.0.1 (OK)
superqt >=0.6.2,<1.0.0               :  0.6.7 (OK)
textdistance >=4.2.0                 :  4.6.2 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  6.0.0 (OK)
yarl >=1.9.4                         :  1.17.1 (OK)
zmq >=24.0.0                         :  26.2.0 (OK)

# Optional:
cython >=0.21                        :  3.0.11 (OK)
matplotlib >=3.0.0                   :  3.9.2 (OK)
numpy >=1.7                          :  2.1.3 (OK)
pandas >=1.1.1                       :  2.2.3 (OK)
scipy >=0.17.0                       :  1.14.1 (OK)
sympy >=0.7.3                        :  1.13.3 (OK)

# Spyder plugins:
spyder_notebook.notebookplugin 0.6.1 :  0.6.1 (OK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at /Users/jeffreybaker/miniforge3/envs/spyder-env:
#
# Name                    Version                   Build  Channel
aiohappyeyeballs          2.4.3              pyhd8ed1ab_0    conda-forge
aiohttp                   3.10.10         py312h906988d_0    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
alabaster                 1.0.0              pyhd8ed1ab_0    conda-forge
anyio                     4.6.2.post1        pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
applaunchservices         0.3.0              pyh534df25_3    conda-forge
appnope                   0.1.4              pyhd8ed1ab_0    conda-forge
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py312h024a12e_5    conda-forge
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
astroid                   3.3.5           py312h81bd7bf_0    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
asyncssh                  2.18.0             pyhd8ed1ab_0    conda-forge
atomicwrites              1.4.1              pyhd8ed1ab_0    conda-forge
attrs                     24.2.0             pyh71513ae_0    conda-forge
autopep8                  2.0.4              pyhd8ed1ab_0    conda-forge
babel                     2.16.0             pyhd8ed1ab_0    conda-forge
backports                 1.0                pyhd8ed1ab_4    conda-forge
backports.tarfile         1.2.0              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.3             pyha770c72_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
black                     24.10.0         py312h81bd7bf_0    conda-forge
bleach                    6.2.0              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                hd74edd7_2    conda-forge
brotli-bin                1.1.0                hd74edd7_2    conda-forge
brotli-python             1.1.0           py312hde4cb15_2    conda-forge
bzip2                     1.0.8                h99b78c6_7    conda-forge
ca-certificates           2024.8.30            hf0a4a13_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py312h0fad829_0    conda-forge
chardet                   5.2.0           py312h81bd7bf_2    conda-forge
charset-normalizer        3.4.0              pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
cloudpickle               3.1.0              pyhd8ed1ab_1    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
contourpy                 1.3.1           py312hb23fbb9_0    conda-forge
cookiecutter              2.6.0              pyhca7485f_0    conda-forge
cpython                   3.12.7          py312hd8ed1ab_0    conda-forge
cryptography              43.0.3          py312h5fad481_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
cython                    3.0.11          py312hde4cb15_2    conda-forge
debugpy                   1.8.8           py312hd8f9ff3_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
deprecated                1.2.14             pyh1a96a4e_0    conda-forge
diff-match-patch          20241021           pyhd8ed1ab_0    conda-forge
dill                      0.3.9              pyhd8ed1ab_0    conda-forge
docstring-to-markdown     0.15               pyhd8ed1ab_0    conda-forge
docutils                  0.21.2             pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
executing                 2.1.0              pyhd8ed1ab_0    conda-forge
flake8                    7.1.1              pyhd8ed1ab_0    conda-forge
fonttools                 4.55.0          py312h998013c_0    conda-forge
fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               hadb7bae_2    conda-forge
frozendict                2.4.6           py312h0bf5046_0    conda-forge
frozenlist                1.5.0           py312h0bf5046_0    conda-forge
fzf                       0.56.3               h145549b_0    conda-forge
giflib                    5.2.2                h93a5062_0    conda-forge
glib                      2.82.2               hb1db9eb_0    conda-forge
glib-tools                2.82.2               h25d4a46_0    conda-forge
gmp                       6.3.0                h7bae524_2    conda-forge
gmpy2                     2.1.5           py312h87fada9_2    conda-forge
gst-plugins-base          1.24.7               hb49d354_0    conda-forge
gstreamer                 1.24.7               hc3f5269_0    conda-forge
h11                       0.14.0             pyhd8ed1ab_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
html5lib                  1.1                pyhd8ed1ab_1    conda-forge
httpcore                  1.0.6              pyhd8ed1ab_0    conda-forge
httpx                     0.27.2             pyhd8ed1ab_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       75.1                 hfee45f7_0    conda-forge
idna                      3.10               pyhd8ed1ab_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        8.5.0              pyha770c72_0    conda-forge
importlib_metadata        8.5.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.5              pyhd8ed1ab_0    conda-forge
inflection                0.5.1              pyh9f0ad1d_0    conda-forge
intervaltree              3.1.0              pyhd8ed1ab_1    conda-forge
ipykernel                 6.29.5             pyh57ce528_0    conda-forge
ipython                   8.29.0             pyh707e725_0    conda-forge
isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
isort                     5.13.2             pyhd8ed1ab_0    conda-forge
jaraco.classes            3.4.0              pyhd8ed1ab_1    conda-forge
jaraco.context            5.3.0              pyhd8ed1ab_1    conda-forge
jaraco.functools          4.0.0              pyhd8ed1ab_0    conda-forge
jedi                      0.19.2             pyhff2d567_0    conda-forge
jellyfish                 1.1.0           py312he431725_1    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
json5                     0.9.28             pyhff2d567_0    conda-forge
jsonpointer               3.0.0           py312h81bd7bf_1    conda-forge
jsonschema                4.23.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2024.10.1          pyhd8ed1ab_0    conda-forge
jsonschema-with-format-nongpl 4.23.0               hd8ed1ab_0    conda-forge
jupyter-lsp               2.2.5              pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.3              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2              pyh31011fe_1    conda-forge
jupyter_events            0.10.0             pyhd8ed1ab_0    conda-forge
jupyter_server            2.14.2             pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.5.3              pyhd8ed1ab_0    conda-forge
jupyterlab                4.2.5              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_1    conda-forge
jupyterlab_server         2.27.3             pyhd8ed1ab_0    conda-forge
keyring                   25.5.0             pyh534df25_0    conda-forge
kiwisolver                1.4.7           py312h6142ec9_0    conda-forge
krb5                      1.21.3               h237132a_0    conda-forge
lcms2                     2.16                 ha0e7c42_0    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libblas                   3.9.0           25_osxarm64_openblas    conda-forge
libbrotlicommon           1.1.0                hd74edd7_2    conda-forge
libbrotlidec              1.1.0                hd74edd7_2    conda-forge
libbrotlienc              1.1.0                hd74edd7_2    conda-forge
libcblas                  3.9.0           25_osxarm64_openblas    conda-forge
libclang-cpp17            17.0.6          default_h146c034_7    conda-forge
libclang13                19.1.3          default_h5f28f6d_0    conda-forge
libcxx                    19.1.3               ha82da77_0    conda-forge
libdeflate                1.22                 hd74edd7_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libexpat                  2.6.4                h286801f_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_3    conda-forge
libgfortran5              13.2.0               hf226fd6_3    conda-forge
libglib                   2.82.2               h07bd6cf_0    conda-forge
libiconv                  1.17                 h0d3ecfb_2    conda-forge
libintl                   0.22.5               h8414b35_3    conda-forge
libintl-devel             0.22.5               h8414b35_3    conda-forge
libjpeg-turbo             3.0.0                hb547adb_1    conda-forge
liblapack                 3.9.0           25_osxarm64_openblas    conda-forge
libllvm17                 17.0.6               h5090b49_2    conda-forge
libllvm19                 19.1.3               haf57ff0_0    conda-forge
libogg                    1.3.5                h99b78c6_0    conda-forge
libopenblas               0.3.28          openmp_hf332438_1    conda-forge
libopus                   1.3.1                h27ca646_1    conda-forge
libpng                    1.6.44               hc14010f_0    conda-forge
libpq                     16.5                 h0224a88_0    conda-forge
libsodium                 1.0.20               h99b78c6_0    conda-forge
libspatialindex           2.0.0                h00cdb27_0    conda-forge
libsqlite                 3.47.0               hbaaea75_1    conda-forge
libtiff                   4.7.0                hfce79cd_1    conda-forge
libvorbis                 1.3.7                h9f76cd9_0    conda-forge
libwebp                   1.4.0                h54798ee_0    conda-forge
libwebp-base              1.4.0                h93a5062_0    conda-forge
libxcb                    1.17.0               hdb1d25a_0    conda-forge
libxml2                   2.13.5               hbbdcc80_0    conda-forge
libxslt                   1.1.39               h223e5b9_0    conda-forge
libzlib                   1.3.1                h8359307_2    conda-forge
llvm-openmp               19.1.3               hb52a8e5_0    conda-forge
lxml                      5.3.0           py312ha59c1f6_2    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                3.0.2           py312ha0ccf2a_0    conda-forge
matplotlib                3.9.2           py312h1f38498_2    conda-forge
matplotlib-base           3.9.2           py312h9bd0bc6_2    conda-forge
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
mccabe                    0.7.0              pyhd8ed1ab_0    conda-forge
mdurl                     0.1.2              pyhd8ed1ab_0    conda-forge
mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
more-itertools            10.5.0             pyhd8ed1ab_0    conda-forge
mpc                       1.3.1                h8f1351a_1    conda-forge
mpfr                      4.2.1                hb693164_3    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
multidict                 6.1.0           py312hdb8e49c_1    conda-forge
multitasking              0.0.9              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
mysql-common              9.0.1                h0887d5e_2    conda-forge
mysql-libs                9.0.1                he9bc4e1_2    conda-forge
nbclient                  0.10.0             pyhd8ed1ab_0    conda-forge
nbconvert                 7.16.4               hd8ed1ab_1    conda-forge
nbconvert-core            7.16.4             pyhd8ed1ab_1    conda-forge
nbconvert-pandoc          7.16.4               hd8ed1ab_1    conda-forge
nbformat                  5.10.4             pyhd8ed1ab_0    conda-forge
ncurses                   6.5                  h7bae524_1    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
notebook                  7.2.2              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.4              pyhd8ed1ab_0    conda-forge
nspr                      4.36                 h5833ebf_0    conda-forge
nss                       3.106                h6f44f80_0    conda-forge
numpy                     2.1.3           py312h94ee1e1_0    conda-forge
numpydoc                  1.8.0              pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.2                h9f1df11_0    conda-forge
openssl                   3.4.0                h39f12f2_0    conda-forge
overrides                 7.7.0              pyhd8ed1ab_0    conda-forge
packaging                 24.2               pyhd8ed1ab_0    conda-forge
pandas                    2.2.3           py312hcd31e36_1    conda-forge
pandoc                    3.5                  hce30654_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
pathspec                  0.12.1             pyhd8ed1ab_0    conda-forge
patsy                     1.0.1              pyhff2d567_0    conda-forge
pcre2                     10.44                h297a79d_2    conda-forge
peewee                    3.17.7          py312ha63d2eb_0    conda-forge
pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    11.0.0          py312haf37ca6_0    conda-forge
pip                       24.3.1             pyh8b19718_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.3.6              pyhd8ed1ab_0    conda-forge
pluggy                    1.5.0              pyhd8ed1ab_0    conda-forge
ply                       3.11               pyhd8ed1ab_2    conda-forge
prometheus_client         0.21.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.48             pyha770c72_0    conda-forge
propcache                 0.2.0           py312h024a12e_2    conda-forge
psutil                    6.1.0           py312h0bf5046_0    conda-forge
pthread-stubs             0.4               hd74edd7_1002    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.3              pyhd8ed1ab_0    conda-forge
pycodestyle               2.12.1             pyhd8ed1ab_0    conda-forge
pyconify                  0.1.6              pyhd8ed1ab_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pydocstyle                6.3.0              pyhd8ed1ab_0    conda-forge
pyflakes                  3.2.0              pyhd8ed1ab_0    conda-forge
pygithub                  2.5.0              pyhd8ed1ab_0    conda-forge
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyjwt                     2.9.0              pyhd8ed1ab_1    conda-forge
pylint                    3.3.1              pyhd8ed1ab_0    conda-forge
pylint-venv               3.0.4              pyhd8ed1ab_0    conda-forge
pyls-spyder               0.4.0              pyhd8ed1ab_0    conda-forge
pynacl                    1.5.0           py312h024a12e_4    conda-forge
pyobjc-core               10.3.1          py312hd24fc31_1    conda-forge
pyobjc-framework-cocoa    10.3.1          py312hd24fc31_1    conda-forge
pyobjc-framework-coreservices 10.3.1          py312h024a12e_1    conda-forge
pyobjc-framework-fsevents 10.3.1          py312h81bd7bf_1    conda-forge
pyopenssl                 24.2.1             pyhd8ed1ab_2    conda-forge
pyparsing                 3.2.0              pyhd8ed1ab_1    conda-forge
pyqt                      5.15.9          py312h550cae4_5    conda-forge
pyqt5-sip                 12.12.2         py312h9f69965_5    conda-forge
pyqtwebengine             5.15.9          py312h14105d7_5    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.12.7          h739c21a_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.20.0             pyhd8ed1ab_0    conda-forge
python-gssapi             1.9.0           py312h63f4dd6_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-lsp-black          2.0.0              pyhd8ed1ab_0    conda-forge
python-lsp-jsonrpc        1.1.2              pyhd8ed1ab_0    conda-forge
python-lsp-server         1.12.0             pyhd8ed1ab_0    conda-forge
python-lsp-server-base    1.12.0             pyhd8ed1ab_0    conda-forge
python-slugify            8.0.4              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.2             pyhd8ed1ab_0    conda-forge
python.app                1.4             py312h830b0dc_4    conda-forge
python_abi                3.12                    5_cp312    conda-forge
pytoolconfig              1.2.5              pyhd8ed1ab_0    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyuca                     1.2                        py_1    conda-forge
pyxdg                     0.28               pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.2           py312h024a12e_1    conda-forge
pyzmq                     26.2.0          py312hf8a1cbd_3    conda-forge
qdarkstyle                3.2.3              pyhd8ed1ab_0    conda-forge
qhull                     2020.2               h420ef59_5    conda-forge
qstylizer                 0.2.3              pyhd8ed1ab_0    conda-forge
qt-main                   5.15.15              h7d33341_0    conda-forge
qt-webengine              5.15.15              h5422c0a_1    conda-forge
qtawesome                 1.3.1              pyh9208f05_0    conda-forge
qtconsole                 5.6.1              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.6.1              pyha770c72_0    conda-forge
qtpy                      2.4.2              pyhdecd6ff_0    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rich                      13.9.4             pyhd8ed1ab_0    conda-forge
rope                      1.13.0             pyhd8ed1ab_0    conda-forge
rpds-py                   0.21.0          py312hcd83bfe_0    conda-forge
rtree                     1.3.0           py312heed235c_2    conda-forge
scipy                     1.14.1          py312h20deb59_1    conda-forge
seaborn                   0.13.2               hd8ed1ab_2    conda-forge
seaborn-base              0.13.2             pyhd8ed1ab_2    conda-forge
send2trash                1.8.3              pyh31c8845_0    conda-forge
setuptools                75.3.0             pyhd8ed1ab_0    conda-forge
sip                       6.8.6           py312hde4cb15_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.3.1              pyhd8ed1ab_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
sphinx                    8.1.3              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-htmlhelp    2.1.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-qthelp      2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-serializinghtml 1.1.10             pyhd8ed1ab_0    conda-forge
spyder                    6.0.2           osx_pyh1a5313d_2    conda-forge
spyder-kernels            3.0.1           unix_pyh707e725_0    conda-forge
spyder-notebook           0.6.1              pyhff2d567_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.4          py312h755e627_0    conda-forge
superqt                   0.6.7              pyh9208f05_0    conda-forge
sympy                     1.13.3           pyh2585a3b_104    conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
terminado                 0.18.1             pyh31c8845_0    conda-forge
text-unidecode            1.3                pyhd8ed1ab_1    conda-forge
textdistance              4.6.3              pyhd8ed1ab_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
tinycss2                  1.4.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h5083fa2_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.1.0              pyhff2d567_0    conda-forge
tomlkit                   0.13.2             pyha770c72_0    conda-forge
tornado                   6.4.1           py312h024a12e_1    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
types-python-dateutil     2.9.0.20241003     pyhff2d567_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
ujson                     5.10.0          py312hde4cb15_1    conda-forge
unicodedata2              15.1.0          py312h0bf5046_1    conda-forge
uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
urllib3                   2.2.3              pyhd8ed1ab_0    conda-forge
watchdog                  6.0.0           py312hea69d52_0    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
webcolors                 24.8.0             pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
websocket-client          1.8.0              pyhd8ed1ab_0    conda-forge
whatthepatch              1.0.6              pyhd8ed1ab_0    conda-forge
wheel                     0.45.0             pyhd8ed1ab_0    conda-forge
wrapt                     1.16.0          py312h024a12e_1    conda-forge
wurlitzer                 3.1.1              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hd74edd7_1    conda-forge
xorg-libxdmcp             1.1.5                hd74edd7_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
yapf                      0.40.1             pyhd8ed1ab_0    conda-forge
yarl                      1.17.1          py312hea69d52_1    conda-forge
yfinance                  0.2.49             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.5                hc1bb282_7    conda-forge
zipp                      3.21.0             pyhd8ed1ab_0    conda-forge
zstandard                 0.23.0          py312h15fbf35_1    conda-forge
zstd                      1.5.6                hb46c0d2_0    conda-forge

```
</details>

**Comment by ccordoba12** [comment]
Closing due to lack of response.
