### ISSUE TITLE
Profiling error

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#2305]
## Description

* *What steps will reproduce the problem?*
   1. Run a script with a profiler

* *What is the expected output? What do you see instead?*

I see this in the internal console:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/spyderplugins/widgets/profilergui.py", line 253, in <lambda>
    self.finished(ec, es))
  File "/usr/lib/python2.7/site-packages/spyderplugins/widgets/profilergui.py", line 318, in finished
    self.show_data(justanalyzed=True)
  File "/usr/lib/python2.7/site-packages/spyderplugins/widgets/profilergui.py", line 339, in show_data
    self.datatree.load_data(self.DATAPATH)
  File "/usr/lib/python2.7/site-packages/spyderplugins/widgets/profilergui.py", line 427, in load_data
    map(lambda x: x.calc_callees().stats, stats_indi)
  File "/usr/lib/python2.7/site-packages/spyderplugins/widgets/profilergui.py", line 427, in <lambda>
    map(lambda x: x.calc_callees().stats, stats_indi)
AttributeError: 'NoneType' object has no attribute 'stats'
```

* *Please provide any additional information below*

## Version and main components

* Spyder Version:  3.0.0dev 
* Python Version:  2.7.9
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Linux

## Optional dependencies

pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=3.0   :  3.0.0 (OK)
zmq >=13.0.0    :  14.5.0 (OK)
pandas >=0.13.1 :  0.16.0 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.10.2 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  1.4.3 (OK)

**Comment by ccordoba12** [comment]
@dhoegh, you were the last one to touch our profiler. Could you look at this one?

**Comment by Nodd** [comment]
To add more information: the script runs fine and the error appears before displaying the results.
