### ISSUE TITLE
My Spyder graphical user interface (GUI) does not run.

### ISSUE THREAD

**Issue by acaihello** [spyder-ide/spyder#23068]
My operating system is Ubuntu 24.04. After installing Spyder using Miniconda (following the instructions in the documentation), I tried to start Spyder from the command line but found that there was no graphical interface; Spyder only runs in the background. When I terminate it from the command line, the following message appears. Could you please help me with how to resolve this issue?
```
Traceback (most recent call last):
  File "/home/acai/miniconda3/envs/spyder-env/bin/spyder", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/acai/miniconda3/envs/spyder-env/lib/python3.12/site-packages/spyder/app/start.py", line 286, in main
    mainwindow.main(options, args)
  File "/home/acai/miniconda3/envs/spyder-env/lib/python3.12/site-packages/spyder/app/mainwindow.py", line 1375, in main
    app = create_application()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/acai/miniconda3/envs/spyder-env/lib/python3.12/site-packages/spyder/app/utils.py", line 298, in create_application
    app.set_font()
  File "/home/acai/miniconda3/envs/spyder-env/lib/python3.12/site-packages/spyder/utils/qthelpers.py", line 824, in set_font
    self.set_monospace_interface_font(app_font)
  File "/home/acai/miniconda3/envs/spyder-env/lib/python3.12/site-packages/spyder/utils/qthelpers.py", line 849, in set_monospace_interface_font
    plain_font.setPointSize(monospace_size)
KeyboardInterrupt
```

**Comment by ccordoba12** [comment]
Hey @acaihello, thanks for reporting. This bug was already reported and it'll be fixed in our next version (6.0.3), to be released in a couple of weeks.

In the meantime, please run in a terminal

    spyder --reset

and then try to start Spyder again. That should fix your problem.
