### ISSUE TITLE
Can run a program from Spyder

### ISSUE THREAD

**Issue by onanysunday** [spyder-ide/spyder#23065]
### What steps will reproduce the problem?

I had not used Navigaor in a while, months at least. I was asked to update Navigator (2.5 i think) and I did. Then I restarted and it asked me to update to (2.6 I think) so I did. Then I created a new default environment. When I launced Spyder I got a console error and could not even run a "Hello World." In Jupyter notebook I could run "hello" so it seems to be with Spyder.

Error while loading conda entry point: anaconda‑cloud‑auth (cannot import name 'ChannelAuthBase' from 'conda.plugins.types' (/Users/charleskrajewski/anaconda3/lib/python3.11/site‑packages/conda/plugins/types.py))

### Traceback
```python-traceback
Traceback (most recent call last):

  File "/Users/charleskrajewski/anaconda3/envs/bitcoin_analyze_00/lib/python3.11/site-packages/spyder/plugins/run/container.py", line 214, in run_file
    self.edit_run_configurations(
  File "/Users/charleskrajewski/anaconda3/envs/bitcoin_analyze_00/lib/python3.11/site-packages/spyder/plugins/run/container.py", line 232, in edit_run_configurations
    self.dialog.setup()
  File "/Users/charleskrajewski/anaconda3/envs/bitcoin_analyze_00/lib/python3.11/site-packages/spyder/plugins/run/widgets.py", line 746, in setup
    self.run_conf_model.get_initial_index())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/charleskrajewski/anaconda3/envs/bitcoin_analyze_00/lib/python3.11/site-packages/spyder/plugins/run/models.py", line 192, in get_initial_index
    return self.inverted_index[self.current_configuration]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: None
```

## Versions

* Spyder version: 6.0.1  (conda)
* Python version: 3.11.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: macOS-14.6.1-arm64-arm-64bit

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.10.5 (OK)
applaunchservices >=0.3.0        :  0.3.0 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.17.0 (OK)
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
github >=2.3.0                   :  2.4.0 (OK)
importlib_metadata >=4.6.0       :  7.0.1 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.27.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  0.9.0 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  24.3.1 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.7.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.0 (OK)
pygments >=2.0                   :  2.15.1 (OK)
pylint >=3.1,<4                  :  3.2.7 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0         :  5.6.0 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.0.1 (OK)
setuptools >=49.6.0              :  75.1.0 (OK)
sphinx >=0.6.6                   :  7.3.7 (OK)
spyder_kernels >=3.0.0,<3.1.0    :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.1 (OK)
yarl >=1.9.4                     :  1.11.0 (OK)
zmq >=24.0.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  None (NOK)
numpy >=1.7                      :  None (NOK)
pandas >=1.1.1                   :  None (NOK)
scipy >=0.17.0                   :  None (NOK)
sympy >=0.7.3                    :  None (NOK)
```

### Environment

<details><summary>Environment</summary>

```

```
</details>

**Comment by ccordoba12** [comment]
Hey @onanysunday, thanks for reporting. This bug was already reported and it'll be fixed in our next version (6.0.3), to be released in a couple of weeks.

In the meantime, you need to manually select the Python file you want to run in the editor (this error happens when you try to run non-Python files after Spyder starts).

Finally, Anaconda is always behind our latest release (lately by several months). So we recommend you to use our own Windows installer, or install Spyder from Conda-forge, as described in [our documentation](http://docs.spyder-ide.org/current/installation.html).

**Comment by onanysunday** [comment]
Thank you for the valuable information.
Prior to getting this email I backed down to Spyder 5.5 and so far so good.
Thanks again, looking forward to running 6.0.3, I really like Spyder.
Charlie


    On Sunday, November 24, 2024 at 10:02:11 AM EST, Carlos Cordoba ***@***.***> wrote:  
 
 


Hey @onanysunday, thanks for reporting. This bug was already reported and it'll be fixed in our next version (6.0.3), to be released in a couple of weeks.

In the meantime, you need to manually select the Python file you want to run in the editor (this error happens when you try to run non-Python files after Spyder starts).

Finally, Anaconda is always behind our latest release (lately by several months). So we recommend you to use our own Windows installer, or install Spyder from Conda-forge, as described in our documentation.
