### ISSUE TITLE
Spyder has encountered an internal problem

### ISSUE THREAD

**Issue by Roya-prog** [spyder-ide/spyder#23098]
### What steps will reproduce the problem?

Running the program is not working in spyder.
How to solve the issue

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\Sina_Laptop\anaconda3\Lib\site-packages\spyder\plugins\run\container.py", line 214, in run_file
    self.edit_run_configurations(
  File "C:\Users\Sina_Laptop\anaconda3\Lib\site-packages\spyder\plugins\run\container.py", line 232, in edit_run_configurations
    self.dialog.setup()
  File "C:\Users\Sina_Laptop\anaconda3\Lib\site-packages\spyder\plugins\run\widgets.py", line 746, in setup
    self.run_conf_model.get_initial_index())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sina_Laptop\anaconda3\Lib\site-packages\spyder\plugins\run\models.py", line 192, in get_initial_index
    return self.inverted_index[self.current_configuration]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: None
```

## Versions

* Spyder version: 6.0.1  (conda)
* Python version: 3.12.7 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.10.5 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.17.0 (OK)
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
github >=2.3.0                   :  2.4.0 (OK)
importlib_metadata >=4.6.0       :  8.5.0 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.27.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.1 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  24.3.1 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.7.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.0 (OK)
pygments >=2.0                   :  2.15.1 (OK)
pylint >=3.1,<4                  :  3.2.7 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0         :  5.6.0 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.0.1 (OK)
setuptools >=49.6.0              :  75.1.0 (OK)
sphinx >=0.6.6                   :  7.3.7 (OK)
spyder_kernels >=3.0.0,<3.1.0    :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.1 (OK)
yarl >=1.9.4                     :  1.11.0 (OK)
zmq >=24.0.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  None (NOK)
numpy >=1.7                      :  2.1.3 (OK)
pandas >=1.1.1                   :  None (NOK)
scipy >=0.17.0                   :  None (NOK)
sympy >=0.7.3                    :  None (NOK)
```

**Comment by dalthviz** [comment]
Hi @Roya-prog thank you for the report! I think this could be a duplicate of https://github.com/spyder-ide/spyder/issues/22607 A fix for that issue was done over PR https://github.com/spyder-ide/spyder/pull/22819 and it will be part of the upcoming Spyder 6.0.3, so once Spyder 6.0.3 is released updating Spyder should be enough to prevent this issue.

Let us know if the info above helps!

**Comment by ccordoba12** [comment]
Hey @Roya-prog, thanks for reporting. This error should be fixed in our latest version (6.0.3).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with Conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-env -c conda-forge spyder
        conda activate spyder-env
        spyder

If you need to use more packages than just Spyder, you have to:

1. Follow [our documentation](https://docs.spyder-ide.org/5/faq.html#using-packages-installer) about that in case you're using our installer.
2. If you followed the Conda-forge path, you need to close Spyder, open the Anaconda Prompt and run

        conda activate spyder-env
        conda install scikit-learn

    in case you need to work with Scikit-Learn, or do the same for the packages you need to install.
