### ISSUE TITLE
External consoles don't launch correctly

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#231]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2010-06-11T12:01:22Z_

What steps will reproduce the problem?

 1. Double-click on spyder.pyw to launch Spyder
2. Launch either IPython or regular Python external console from "External consoles" menu. What is the expected output? What do you see instead? Should get a working external console. Instead, this error message results in the console window:

Traceback (most recent call last):
  File "C:\src\spyderlib\spyderlib\widgets\externalshell\startup.py", line 51, in \<module>
    __patching_matplotlib__()
  File "C:\src\spyderlib\spyderlib\widgets\externalshell\startup.py", line 25, in __patching_matplotlib__
    if programs.is_module_installed('matplotlib'):
AttributeError: 'module' object has no attribute 'is_module_installed' What version of the product are you using? On what operating system? 1.1.0rc1 on XP using Python 2.6. 

Please provide any additional information below

. Ironically, everything works fine if spyder is launched from within Eclipse. It's only if I try to launch spyder directly from the OS that the problem results.

**Attachment:** [ipython_window.png](http://code.google.com/p/spyderlib/issues/detail?id=231)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=231_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-06-11T13:45:59Z_

This should be fixed by the following change: https://code.google.com/p/spyderlib/source/detail?r=88877adf330af499a64a9b07d69c0b95ae69209b Could you please check if it works for you? (as I was not able to reproduce this bug!)

**Comment by spyder-issues-migrator** [comment]
_From [DavidAnt...@gmail.com](https://code.google.com/u/108698404730356683634/) on 2010-06-12T03:49:52Z_

I found a similar error when running spyder directly from the source directory.  Once I ran an installed version, this problem went away.

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2010-06-12T10:17:02Z_

Well, in retrospect this probably wasn't a bug, so this might not be too helpful anymore, but here's what I did:

I applied the change set provided above, and after double clicking on spyder.pyw from the SOURCE directory, I went to launch an external console. I received a very similar but slightly different error message as before but unfortunately didn't preserve it. At any rate, it was clear that some module related the matplotlib patch was not being located appropriately.

Noticing David's comment above, I went ahead and ran the installer. Everything works fine after running the installer. I didn't do this initially because I wasn't quite sure I wanted to replace my existing install. After running the installer, Spyder can be run from the typical installed location AND from the source directory by double click, and the external consoles launch fine. This only makes sense in retrospect since the installer would be placing modules into the standard Python path so they would be locatable regardless of the location of the python.pyw being run.

It's probably not reasonable to expect that spyder.pyw always be launchable from the source directory by simply double clicking, but I seem to recall previous versions working correctly when I ran this way on occasion. I'm guessing I was getting lucky and that all the required modules were already somewhere on the Python path, even if they were potentially outdated versions of the modules :). I'll abandon my sinful ways and launch from inside Pydev when testing from source.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-06-13T00:51:22Z_

Actually that is because in previous versions, the external console's startup script (which is executed in another process) was not importing anything from the spyderlib module. Now it's trying to patch matplotlib thanks to the module spyderlib.mpl_patch. So spyderlib must be in PYTHONPATH or in your site-packages directory for the external Python interpreter to be able to find it and import it. The rest of Spyder features do work because the process in which you've started Spyder has added the right folder (spyderlib) in sys.path (that is one of the things Python does: it automatically adds the current directory to sys.path -- and in the external console, the current directory has nothing to do with the one where you have initially launched Spyder).

Oh, I'm realizing that it's not entirely true: there was already an import of spyderlib, the external console's monitor. So, even before, your external console was not full featured: there was no code completion or variable explorer support...

So this is definitely a 'WontFix' ;)

**Status:** WontFix

**Comment by spyder-issues-migrator** [comment]
_From [DavidAnt...@gmail.com](https://code.google.com/u/108698404730356683634/) on 2010-06-13T01:53:15Z_

It might be worth adding something to the wiki for hg users just to explain that spyder is not intended to be run without installation.  I had actually been doing this the whole time, until I noticed this problem.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-06-13T03:45:35Z_

Actually that is standard procedure. Even if you are using the hg repository, you always have to add the root directory to PYTHONPATH.
But you're right, it might be worth mentioning somewhere.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-06-13T03:57:33Z_

Done: https://code.google.com/p/spyderlib/wiki/NoteForBetaTesters

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2010-06-15T09:42:22Z_

I agree, this isn't a bug. Rather, it's an improper run-time configuration issue only related to running directly from source. The wiki documentation should help prevent this type of error in the future.
