### ISSUE TITLE
Not Sure What or Why This Internal Spyder Issue Came Up

### ISSUE THREAD

**Issue by sbewaji** [spyder-ide/spyder#23119]
### What steps will reproduce the problem?

Not sure what the error is or why I get it. All I was trying to do was test the fredapi package 

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/spyder/plugins/run/container.py", line 214, in run_file
    self.edit_run_configurations(
  File "/usr/lib/python3.12/site-packages/spyder/plugins/run/container.py", line 232, in edit_run_configurations
    self.dialog.setup()
  File "/usr/lib/python3.12/site-packages/spyder/plugins/run/widgets.py", line 746, in setup
    self.run_conf_model.get_initial_index())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/spyder/plugins/run/models.py", line 192, in get_initial_index
    return self.inverted_index[self.current_configuration]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: None
```

## Versions

* Spyder version: 6.0.2  (pip)
* Python version: 3.12.7 64-bit
* Qt version: 5.15.14
* PyQt5 version: 5.15.11
* Operating System: Linux-6.10.7-zen1-1-zen-x86_64-with-glibc2.40

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.10.5 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.18.0 (OK)
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.1.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
github >=2.3.0                   :  2.3.0 (OK)
importlib_metadata >=4.6.0       :  7.2.1 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.29.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.1.0 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  25.5.0 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.8.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  6.1.0 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.3.1 (OK)
pylint_venv >=3.0.2              :  3.0.4 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.1,<5.7.0         :  5.6.1 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.3.0 (OK)
setuptools >=49.6.0              :  75.2.0 (OK)
sphinx >=0.6.6                   :  8.1.3 (OK)
spyder_kernels >=3.0.1,<3.1.0    :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.8 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  3.0.0 (OK)
xdg >=0.26                       :  0.28 (OK)
yarl >=1.9.4                     :  1.9.4 (OK)
zmq >=24.0.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  3.0.11 (OK)
matplotlib >=3.0.0               :  3.9.2 (OK)
numpy >=1.7                      :  2.1.3 (OK)
pandas >=1.1.1                   :  2.2.2 (OK)
scipy >=0.17.0                   :  1.14.1 (OK)
sympy >=0.7.3                    :  1.13.3 (OK)
```

### Environment

<details><summary>Environment</summary>

```
Package                       Version
----------------------------- -------------------------------
absl-py                       2.1.0
abydos                        0.5.0
aiohappyeyeballs              2.4.3
aiohttp                       3.10.5
aiosignal                     1.3.1
aiosqlite                     0.20.0
alabaster                     1.0.0
aniso8601                     9.0.1
annotated-types               0.7.0
anyio                         4.6.2.post1
apipkg                        3.0.2
apparmor                      4.0.3
appdirs                       1.4.4
argcomplete                   3.4.0
argh                          0.29.1
argon2-cffi                   23.1.0
argon2-cffi-bindings          21.2.0
arrow                         1.3.0
astor                         0.8.1
astroid                       3.3.5
asttokens                     2.4.1
astunparse                    1.6.3
async-lru                     2.0.4
async-timeout                 4.0.3
asyncssh                      2.18.0
atomicwrites                  1.4.1
attrs                         23.2.1.dev0
autocommand                   2.2.2
autopep8                      2.3.1
Babel                         2.15.0
bcrypt                        4.2.1
beautifulsoup4                4.12.3
binaryornot                   0.4.4
black                         24.10.0
bleach                        6.1.0
blinker                       1.8.2
blosc                         1.11.2
blosc2                        2.7.1
boto3                         1.35.36
botocore                      1.35.36
bottle                        0.12.25
Bottleneck                    1.4.0
bowler                        0.9.0
Brlapi                        0.8.6
btrfsutil                     6.10
build                         1.2.2
CacheControl                  0.14.1
cachetools                    5.5.0
Cerberus                      1.3.5
certifi                       2024.8.30
cffi                          1.17.1
chardet                       5.2.0
charset-normalizer            3.4.0
cheroot                       10.0.1
CherryPy                      18.10.0
click                         8.1.7
click-plugins                 1.1.1
cligj                         0.7.2
cloudpickle                   3.1.0
cockpit                       329
colorama                      0.4.6
comm                          0.2.2
commonmark                    0.9.1
ConfigArgParse                1.5.5
configobj                     5.0.8
confuse                       2.0.1
construct                     2.10.70
contourpy                     1.3.1
cookiecutter                  2.6.0
coverage                      7.6.3
CppHeaderParser               2.7.4
crit                          4.0
cryptography                  43.0.3
cssselect                     1.2.0
cupshelpers                   1.0
cycler                        0.12.1
Cython                        3.0.11
dask                          2024.11.2
dbus-python                   1.3.2
debugpy                       1.8.9
decorator                     5.1.1
defusedxml                    0.7.1
Deprecated                    1.2.15
deprecation                   2.1.0
diff-match-patch              20230430
dill                          0.3.8
distlib                       0.3.9
distributed                   2024.11.2
distro                        1.9.0
dnspython                     2.6.1
docstring-to-markdown         0.15
docutils                      0.21.2
ecdsa                         0.19.0
elastic-transport             8.15.1
elasticsearch                 8.16.0
entrypoints                   0.4
et_xmlfile                    1.1.0
evdev                         1.7.1
exceptiongroup                1.2.1
executing                     2.1.0
fastjsonschema                2.20.0
filelock                      3.16.1
fiona                         1.9.6
fissix                        21.11.13
flake8                        7.1.1
Flask                         2.3.3
Flask-Cors                    5.0.0
Flask-RESTful                 0.3.10
flatbuffers                   24.3.25
flexcache                     0.3
flexparser                    0.3.1
flit_core                     3.10.1
fonttools                     4.55.0
fqdn                          1.5.1
fredapi                       0.5.1
frozenlist                    1.4.1
fsspec                        2024.10.0
future                        1.0.0
gast                          0.6.0
geographiclib                 2.0
geopandas                     1.0.1
geopy                         2.4.1
gevent                        24.2.1
gmpy2                         2.2.1
google-api-core               2.19.1
google-api-python-client      2.140.0
google-auth                   2.35.0
google-auth-httplib2          0.2.0
google-auth-oauthlib          1.2.1
google-pasta                  0.2.0
googleapis-common-protos      1.63.2
gps                           3.25
greenlet                      3.1.0
grpcio                        1.67.1
grpcio-tools                  1.67.1
h11                           0.14.0
h5py                          3.12.1
HeapDict                      1.0.1
helpdev                       0.7.1
hidapi                        0.14.0
html5lib                      1.1
htmlmin                       0.1.12
httpcore                      1.0.5
httplib2                      0.22.0
httpx                         0.27.2
idna                          3.10
imageio                       2.36.0
imagesize                     1.4.1
importlib_metadata            7.2.1
inflect                       7.4.0
inflection                    0.5.1
iniconfig                     2.0.0
installer                     0.7.0
intervaltree                  3.1.0
ipykernel                     6.29.5
ipython                       8.29.0
ipython_genutils              0.2.0
ipywidgets                    8.1.5
iso8601                       2.1.0
isodate                       0.6.1
isoduration                   20.11.0
isort                         5.13.2
itsdangerous                  2.1.2
jaraco.classes                3.4.0
jaraco.collections            5.0.1
jaraco.context                5.3.0
jaraco.functools              4.0.2
jaraco.text                   4.0.0
jedi                          0.19.1
jeepney                       0.8.0
jellyfish                     1.1.0
Jinja2                        3.1.4
jmespath                      1.0.1
joblib                        1.4.2
json5                         0.10.0
jsonpointer                   3.0.0
jsonschema                    4.23.0
jsonschema-specifications     2023.12.1
jupyter_client                8.6.3
jupyter-collaboration-ui      1.0.1
jupyter-console               6.6.3
jupyter_core                  5.7.2
jupyter-docprovider           1.0.1
jupyter-events                0.10.0
jupyter_packaging             0.12.3
jupyter_server                2.14.2
jupyter_server_fileid         0.9.3
jupyter_server_terminals      0.5.3
jupyter-server-ydoc           1.0.1
jupyter-ydoc                  3.0.1
jupyterlab                    4.3.1
jupyterlab_pygments           0.3.0
jupyterlab_server             2.27.3
jupyterlab_widgets            3.0.13
keras                         3.4.1
Keras_Applications            1.0.8
keyring                       25.5.0
kiwisolver                    1.4.5
lazy-object-proxy             1.10.0
lensfun                       0.3.4
Levenshtein                   0.25.0
LibAppArmor                   4.0.3
libfdt                        1.7.2
libinput_gestures_qt          0.3
libtorrent                    2.0.10
libusb1                       3.1.0
libvirt-python                10.9.0
lit                           18.1.8.dev0
locket                        1.0.0
lockfile                      0.12.2
logutils                      0.3.5
louis                         3.31.0
lxml                          5.3.0
lz4                           4.3.3
Mako                          1.3.6.dev0
Markdown                      3.7
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
matplotlib                    3.9.2
matplotlib-inline             0.1.7
mccabe                        0.7.0
mdurl                         0.1.2
mercurial                     6.9
meson                         1.6.0
mistune                       3.0.2
ml_dtypes                     0.4.0
mock                          5.1.0
moddb                         0.11.0
more-itertools                10.3.0
moreorless                    0.4.0
mpmath                        1.3.0
msgpack                       1.0.5
multidict                     6.0.5
multipledispatch              1.0.0
munch                         4.0.0
mypy                          1.13.0
mypy_extensions               1.0.0
nbclassic                     1.1.0
nbclient                      0.10.0
nbconvert                     7.16.4
nbformat                      5.10.4
ndg_httpsclient               0.5.1
ndindex                       1.9.2
nest_asyncio                  1.6.0
netsnmp-python                1.0a1
networkx                      3.3
nftables                      0.1
nose                          1.3.7
notebook                      7.2.2
notebook_shim                 0.2.4
nspektr                       0.5.0
numexpr                       2.10.1
numpy                         2.1.3
numpydoc                      1.8.0
oauth2client                  4.1.3
oauthlib                      3.2.2
OpenCC                        1.1.8
openpyxl                      3.1.5
opt_einsum                    0+unknown
optree                        0.12.1
ordered-set                   4.1.0
orjson                        3.10.11
outcome                       1.3.0.post0
overrides                     7.7.0
packaging                     24.2
pandas                        2.2.2
pandas-datareader             0.10.0
pandocfilters                 1.5.1
parso                         0.8.4
partd                         1.4.1
pathspec                      0.12.1
patsy                         0.5.6
pbr                           6.1.0
pecan                         1.5.1
petsc4py                      3.17.3
pexpect                       4.9.0
pickleshare                   0.7.5
pillow                        11.0.0
Pint                          0.24.3
pip                           24.3.1
pkgconfig                     1.5.5
platformdirs                  4.3.6
plotly                        5.23.0+0.g83c7c850f.dirty
pluggy                        1.5.0
plumbum                       1.9.0
ply                           3.11
pooch                         1.8.2
portend                       3.2.0
powerline-status              2.8.4
prettytable                   3.11.0
prometheus_client             0.21.0
prompt_toolkit                3.0.48
protobuf                      5.28.3
ProtonUp-Qt                   2.10.0
pspdfutils                    3.3.6
psutil                        6.1.0
psycopg2                      2.9.9
ptyprocess                    0.7.0
pure_eval                     0.2.3
puremagic                     1.28
pwquality                     1.4.5
py                            1.11.1.dev0+g447bac51.d20240403
py-cpuinfo                    9.0.0
pyaml                         24.9.0
pyasn1                        0.6.0
pyasn1_modules                0.4.0
pybind11                      2.13.6
pycairo                       1.27.0
pycodestyle                   2.12.1
pycountry                     24.6.1
pycparser                     2.22
pycrdt                        0.10.6
pycrdt-websocket              0.15.1
pycriu                        4.0
pycryptodome                  3.21.0
pycryptodomex                 3.21.0
pycups                        2.0.4
pycurl                        7.45.3
pydantic                      2.9.2
pydantic_core                 2.23.4
pydocstyle                    6.3.0
pydot                         3.0.1
pyflakes                      3.2.0
pygdbmi                       0.11.0.0
PyGithub                      2.3.0
Pygments                      2.18.0
PyGObject                     3.50.0
PyJWT                         2.9.0
pylint                        3.3.1
pylint-venv                   3.0.4
pyls-spyder                   0.4.0
PyMySQL                       1.1.1
PyNaCl                        1.5.0
PyOpenGL                      3.1.7
pyOpenSSL                     24.2.1
pypandoc                      1.13
pyparsing                     3.1.2
pypdf                         5.1.0
pyproj                        3.6.1
pyproject_hooks               1.2.0
PyQt5                         5.15.11
PyQt5_sip                     12.15.0
PyQt6                         6.8.0.dev2410211537
PyQt6_sip                     13.8.0
PyQtWebEngine                 5.15.7
pyrate-limiter                3.7.0
pyrsistent                    0.19.3
pyserial                      3.5
PySide6                       6.8.0.2
pysmbc                        1.0.25.1
PySocks                       1.7.1
pytest                        8.3.3
pytest-cov                    5.0.0
pytest-subtests               0.12.1
python-dateutil               2.9.0
python-json-logger            2.0.7
python-lsp-black              2.0.0
python-lsp-jsonrpc            1.1.2
python-lsp-server             1.12.0
python-prctl                  1.8.1
python-slugify                8.0.4
python-xlib                   0.33
pytoolconfig                  1.3.1
pytz                          2024.2
pyuca                         1.2
pyudev                        0.24.3
PyWavelets                    1.7.0
pyxDamerauLevenshtein         1.7.1
pyxdg                         0.28
PyYAML                        6.0.2
pyzmq                         25.1.2
QDarkStyle                    3.2.3
qstylizer                     0.2.2
QtAwesome                     1.3.1
qtconsole                     5.6.1
QTermWidget                   2.1.0
QtPy                          2.4.1
rapidfuzz                     3.6.2
recommonmark                  0.7.1
referencing                   0.35.1
Reflector                     2023.6.28.0.36.1
regex                         2024.9.11
reportlab                     4.2.2
repoze.lru                    0.7
requests                      2.32.3
requests-oauthlib             1.3.1
requests-unixsocket           0.3.0
resolvelib                    1.1.0
retrying                      1.3.4
rfc3339_validator             0.1.4
rfc3986_validator             0.1.1
rfc3987                       1.3.8
rich                          13.9.4
rope                          1.13.0
Routes                        2.5.1
rpds-py                       0.19.0
rpyc                          6.0.1
rsa                           4.9
Rtree                         1.3.0
ruamel.yaml                   0.18.6
ruamel.yaml.clib              0.2.12
s3transfer                    0.10.3
scikit-build                  0.17.6
scikit-learn                  1.5.2
scipy                         1.14.1
scour                         0.38.2
seaborn                       0.13.2
SecretStorage                 3.3.3
semver                        3.0.2
Send2Trash                    1.8.3
sentry-sdk                    2.19.0
setproctitle                  1.3.3
setuptools                    75.2.0
setuptools-scm                8.1.0
sh                            2.0.7
shapely                       2.0.6
shellingham                   1.5.4
shiboken6                     6.8.0.2
shiboken6-generator           6.8.0.2
simplejson                    3.19.2
six                           1.16.0
smbus                         1.1
sniffio                       1.3.1
snowballstemmer               2.2.0
solaar                        1.1.13
sortedcontainers              2.4.0
soundconverter                4.0.5
soupsieve                     2.6
Sphinx                        8.1.3
sphinx-autodoc-typehints      2.5.0
sphinx_rtd_theme              2.0.0
sphinxcontrib-applehelp       2.0.0
sphinxcontrib-devhelp         2.0.0
sphinxcontrib-htmlhelp        2.1.0
sphinxcontrib-jquery          4.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          2.0.0
sphinxcontrib-serializinghtml 2.0.0
spyder                        6.0.2
spyder-kernels                3.0.0
SQLAlchemy                    2.0.36.dev0
sqlite-anyio                  0.2.3
stack_data                    0.6.3
statsmodels                   0.14.2
steam                         1.6.1
streamlink                    7.0.0
superqt                       0.6.8
sympy                         1.13.3
systemd-python                235
tables                        3.10.1
tabulate                      0.9.0
TBB                           0.2
tblib                         2.0.0
tempora                       5.7.0No clue what is
tenacity                      9.0.0
tensorboard                   2.18.0
tensorboard_data_server       0.8.0a0
tensorboard_plugin_wit        1.8.1
tensorflow_cpu                2.18.0
tensorflow_estimator          2.15.0
termcolor                     2.4.0
terminado                     0.18.1
testpath                      0.6.0
text-unidecode                1.3
textdistance                  4.6.3
threadpoolctl                 3.4.0
three-merge                   0.1.1
tifffile                      2024.9.20
tinycss2                      1.4.0
toml                          0.10.2
tomli                         2.0.1
tomli_w                       1.0.0
tomlkit                       0.13.2
toolz                         1.0.0
torch                         2.5.1
tornado                       6.4.1
tqdm                          4.67.1
traitlets                     5.14.3
trio                          0.26.2
trio-websocket                0.11.1
trove-classifiers             2024.10.21.16
typed_ast                     1.5.5
typeguard                     4.3.0
typing_extensions             4.12.2
tzdata                        2024.2
tzlocal                       5.2
uc-micro-py                   1.0.3
ufw                           0.36.2
ujson                         5.10.0
Unidecode                     1.3.8
uri-template                  1.3.0
uritemplate                   4.1.1
urllib3                       1.26.20
validate                      5.0.8
validate-pyproject            0.22
variety                       0.8.12
vboxapi                       1
vdf                           4.0
virtualenv                    20.27.1
volatile                      2.1.0
waitress                      3.0.0
watchdog                      3.0.0
wcwidth                       0.2.13
webcolors                     24.8.0
webencodings                  0.5.1
WebOb                         1.8.7
websocket-client              1.8.0
websockets                    12.0
WebTest                       3.0.0
Werkzeug                      3.0.4
whatthepatch                  1.0.5
wheel                         0.45.0
wrapt                         1.16.0
wsproto                       1.2.0
wurlitzer                     3.1.1
wxPython                      4.2.2
xarray                        2024.7.0
xlrd                          2.0.1
XlsxWriter                    3.1.9
xlwt                          1.3.0
xmlsec                        1.3.14
xmltodict                     0.13.0
y-py                          0.6.2
yapf                          0.40.2
yarl                          1.9.4
yaspin                        3.1.0
ypy-websocket                 0.12.4
yq                            3.4.3
zc.lockfile                   3.0.post1
zict                          3.0.0
zipp                          3.19.3.dev0+gc6a3339.d20240728
zope.event                    5.0
zope.interface                7.1.1
zstandard                     0.22.0

```
</details>

**Comment by dalthviz** [comment]
Hi @sbewaji thank you for the report! I think this could be a duplicate of https://github.com/spyder-ide/spyder/issues/22607 A fix for that issue was done over PR https://github.com/spyder-ide/spyder/pull/22819 and it will be part of the upcoming Spyder 6.0.3 release. Once Spyder 6.0.3 is available, updating Spyder should be enough to prevent this issue.

Let us know if the info above helps!

**Comment by ccordoba12** [comment]
Closing as fixed in 6.0.3. @sbewaji, please update by using your Linux distro package manager.
