### ISSUE TITLE
Spyder crashing on startup

### ISSUE THREAD

**Issue by OnePunchcardMan** [spyder-ide/spyder#23185]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I had problems with pip and decided to reinstall anaconda. After doing so, Spyder would give an error on startup: 
I tried updating and upgrading Spyder, uninstalling it and reinstalling it, making a new environment and installing. Always gave the same error.

### What steps reproduce the problem?

1.  Install anaconda and start up Spyder.

### What is the expected output? What do you see instead?

Spyder starts up and then crashes, not what I expected!

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE
Traceback (most recent call last):
  File "C:\Users\brwt\AppData\Local\anaconda3\envs\FlaskTest\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\brwt\AppData\Local\anaconda3\envs\FlaskTest\Lib\site-packages\spyder\app\start.py", line 286, in main
    mainwindow.main(options, args)
  File "C:\Users\brwt\AppData\Local\anaconda3\envs\FlaskTest\Lib\site-packages\spyder\app\mainwindow.py", line 1425, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brwt\AppData\Local\anaconda3\envs\FlaskTest\Lib\site-packages\spyder\app\utils.py", line 359, in create_window
    main.setup()
  File "C:\Users\brwt\AppData\Local\anaconda3\envs\FlaskTest\Lib\site-packages\spyder\app\mainwindow.py", line 747, in setup
    PLUGIN_REGISTRY.register_plugin(self, PluginClass,
  File "C:\Users\brwt\AppData\Local\anaconda3\envs\FlaskTest\Lib\site-packages\spyder\api\plugin_registration\registry.py", line 344, in register_plugin
    instance = self._instantiate_spyder5_plugin(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brwt\AppData\Local\anaconda3\envs\FlaskTest\Lib\site-packages\spyder\api\plugin_registration\registry.py", line 186, in _instantiate_spyder5_plugin
    plugin_instance = PluginClass(main_window, configuration=CONF)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brwt\AppData\Local\anaconda3\envs\FlaskTest\Lib\site-packages\spyder\plugins\completion\plugin.py", line 248, in __init__
    raise e
  File "C:\Users\brwt\AppData\Local\anaconda3\envs\FlaskTest\Lib\site-packages\spyder\plugins\completion\plugin.py", line 244, in __init__
    self._instantiate_and_register_provider(Provider)
  File "C:\Users\brwt\AppData\Local\anaconda3\envs\FlaskTest\Lib\site-packages\spyder\plugins\completion\plugin.py", line 825, in _instantiate_and_register_provider
    provider_config = self.get_provider_configuration(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brwt\AppData\Local\anaconda3\envs\FlaskTest\Lib\site-packages\spyder\plugins\completion\plugin.py", line 756, in get_provider_configuration
    provider_defaults) = self._merge_default_configurations(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brwt\AppData\Local\anaconda3\envs\FlaskTest\Lib\site-packages\spyder\plugins\completion\plugin.py", line 714, in _merge_default_configurations
    provider_config = provider_configurations[provider_name]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'


```

## Versions

* Spyder version:  6 (newest)
* Python version: Python 3.12.7
* Qt version: 
* PyQt version: 
* Operating System name/version:  windows 11 Enterprise, version 23H2

### Dependencies

```
PASTE DEPENDENCIES HERE
```
Clean installation. No dependencies.

**Comment by ccordoba12** [comment]
Hey @OnePunchcardMan, thanks for reporting. Please open the Anaconda Prompt and run there:

    spyder --reset

Then start Spyder again.

That should solve your problem, but let us know if it doesn't.

**Comment by OnePunchcardMan** [comment]
Hey, thanks for fast response. No, that didn't help.

**Comment by ccordoba12** [comment]
Great! Thanks for lettings us know about it.
