### ISSUE TITLE
simnibs spyder version 5

### ISSUE THREAD

**Issue by ovgu365** [spyder-ide/spyder#23198]
### What steps will reproduce the problem?

I need to use spyder 5 and it seems that it encounter a problem when we use simnibs module

### Traceback
```python-traceback

Traceback (most recent call last):
  File "C:\Users\User\SimNIBS-4.1\simnibs_env\lib\site-packages\spyder\plugins\maininterpreter\widgets\status.py", line 169, in update_envs
    self.envs.update(**output)
TypeError: dict.update() argument after ** must be a mapping, not NoneType

Traceback (most recent call last):
  File "C:\Users\User\SimNIBS-4.1\simnibs_env\lib\site-packages\spyder\plugins\maininterpreter\widgets\status.py", line 169, in update_envs
    self.envs.update(**output) 
TypeError: dict.update() argument after ** must be a mapping, not NoneType

Traceback (most recent call last):
  File "C:\Users\User\SimNIBS-4.1\simnibs_env\lib\site-packages\spyder\plugins\maininterpreter\widgets\status.py", line 169, in update_envs
    self.envs.update(**output) 
TypeError: dict.update() argument after ** must be a mapping, not NoneType

Traceback (most recent call last):
  File "C:\Users\User\SimNIBS-4.1\simnibs_env\lib\site-packages\spyder\plugins\maininterpreter\widgets\status.py", line 169, in update_envs
    self.envs.update(**output) 
TypeError: dict.update() argument after ** must be a mapping, not NoneType

Traceback (most recent call last):
  File "C:\Users\User\SimNIBS-4.1\simnibs_env\lib\site-packages\spyder\plugins\maininterpreter\widgets\status.py", line 169, in update_envs
    self.envs.update(**output) 
TypeError: dict.update() argument after ** must be a mapping, not NoneType

Traceback (most recent call last):
  File "C:\Users\User\SimNIBS-4.1\simnibs_env\lib\site-packages\spyder\plugins\maininterpreter\widgets\status.py", line 169, in update_envs
    self.envs.update(**output) 
TypeError: dict.update() argument after ** must be a mapping, not NoneType
```

## Versions

* Spyder version: 5.3.1 
* Python version: 3.9.12
* Qt version: 5.15.2
* PyQt5 version: 5.15.11
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  5.2.0 (OK)
cloudpickle >=0.5.0           :  3.1.0 (OK)
cookiecutter >=1.6.0          :  2.6.0 (OK)
diff_match_patch >=20181111   :  20241021 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.2 (OK)
jellyfish >=0.7               :  1.1.2 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  25.5.0 (OK)
nbconvert >=4.0               :  7.16.4 (OK)
numpydoc >=0.6.0              :  1.8.0 (OK)
paramiko >=2.4.0              :  3.5.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.4 (OK)
pexpect >=4.4.0               :  4.9.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  6.1.0 (OK)
pygments >=2.0                :  2.18.0 (OK)
pylint >=2.5.0                :  3.3.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  2.0.0 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.4 (OK)
qtawesome >=1.0.2             :  1.3.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.4.2 (OK)
rtree >=0.9.7                 :  1.3.0 (OK)
setuptools >=49.6.0           :  68.2.2 (OK)
sphinx >=0.6.6                :  7.4.7 (OK)
spyder_kernels >=2.3.1;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.6.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  6.0.0 (OK)
zmq >=22.1.0                  :  26.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=3.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.22.0 (OK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  1.9.3 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @KO287, thanks for reporting. Please update to the latest Spyder 5 version to see if that solves your problem.

To do that, please close Spyder, open the Anaconda Prompt and run there

    conda activate simnibs_env
    conda install spyder=5.5.1
    spyder

Let us know if that works.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
