### ISSUE TITLE
OMP_NUM_THREADS

### ISSUE THREAD

**Issue by denisnpg** [spyder-ide/spyder#23193]
### What steps will reproduce the problem?

Problems when i try to assign 

OMP_NUM_THREADS = 1

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\adm\anaconda3\envs\rdkit-env\lib\site-packages\spyder\utils\environ.py", line 243, in accept
    set_user_env(listdict2envdict(self.get_value()), parent=self)
  File "C:\Users\adm\anaconda3\envs\rdkit-env\lib\site-packages\spyder\utils\environ.py", line 107, in set_user_env
    winreg.SetValueEx(key, name, 0, types[name], env_dict[name])
ValueError: Could not convert the data to the specified type.
```

## Versions

* Spyder version: 5.4.5  (conda)
* Python version: 3.9.12 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.6
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                                                        :  1.4.0 (OK)
chardet >=2.0.0                                                             :  4.0.0 (OK)
cloudpickle >=0.5.0                                                         :  2.0.0 (OK)
cookiecutter >=1.6.0                                                        :  1.7.3 (OK)
diff_match_patch >=20181111                                                 :  20200713 (OK)
intervaltree >=3.0.2                                                        :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0,!=8.11.0,!=8.12.0,!=8.12.1 :  7.32.0 (OK)
jedi >=0.17.2,<0.19.0                                                       :  0.18.1 (OK)
jellyfish >=0.7                                                             :  0.9.0 (OK)
jsonschema >=3.2.0                                                          :  4.4.0 (OK)
keyring >=17.0.0                                                            :  23.5.0 (OK)
nbconvert >=4.0                                                             :  6.5.0 (OK)
numpydoc >=0.6.0                                                            :  1.2.1 (OK)
paramiko >=2.4.0                                                            :  2.10.3 (OK)
parso >=0.7.0,<0.9.0                                                        :  0.8.3 (OK)
pexpect >=4.4.0                                                             :  4.8.0 (OK)
pickleshare >=0.4                                                           :  0.7.5 (OK)
psutil >=5.3                                                                :  5.9.0 (OK)
pygments >=2.0                                                              :  2.11.2 (OK)
pylint >=2.5.0,<3.0                                                         :  2.13.5 (OK)
pylint_venv >=3.0.2                                                         :  3.0.3 (OK)
pyls_spyder >=0.4.0                                                         :  0.4.0 (OK)
pylsp >=1.7.4,<1.8.0                                                        :  1.7.4 (OK)
pylsp_black >=1.2.0,<3.0.0                                                  :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                                                   :  3.0.3 (OK)
qstylizer >=0.2.2                                                           :  0.2.2 (OK)
qtawesome >=1.2.1                                                           :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                                                    :  5.4.4 (OK)
qtpy >=2.1.0                                                                :  2.4.1 (OK)
rtree >=0.9.7                                                               :  1.0.0 (OK)
setuptools >=49.6.0                                                         :  62.1.0 (OK)
sphinx >=0.6.6                                                              :  4.5.0 (OK)
spyder_kernels >=2.4.4,<2.5.0                                               :  2.4.4 (OK)
textdistance >=4.2.0                                                        :  4.2.2 (OK)
three_merge >=0.1.1                                                         :  0.1.1 (OK)
watchdog >=0.10.3                                                           :  2.1.7 (OK)
zmq >=22.1.0                                                                :  23.2.0 (OK)

# Optional:
cython >=0.21                                                               :  None (NOK)
matplotlib >=3.0.0                                                          :  3.5.1 (OK)
numpy >=1.7                                                                 :  1.23.5 (OK)
pandas >=1.1.1                                                              :  1.5.3 (OK)
scipy >=0.17.0                                                              :  1.7.3 (OK)
sympy >=0.7.3                                                               :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @denisnpg, thanks for reporting. This problem should be fixed in our latest Spyder 5 version available in Anaconda (5.5.1). Please update by closing Spyder, opening the Anaconda Prompt and running there:

    conda activate rdkit-env
    conda install spyder=5.5.1
    spyder

Let us know if it works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
