### ISSUE TITLE
Menuinst error related with the reset shortcut

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#23203]
## Problem Description

A traceback is shown after Spyder 6.0.3rc1 is installed with conda:

```python-traceback
Warning: Using menuinst v1
Please update to menuinst >=2.1.2 in the base environment and reinstall Spyder

\ Insufficient permissions to write menu folder.  Falling back to user location

| menuinst Exception
Traceback (most recent call last):
  File "C:\Users\dalth\anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 267, in make_menu
    menuinst.install(join(prefix, win_path_ok(file_path)), remove, prefix)
  File "C:\Users\dalth\anaconda3\lib\site-packages\menuinst\__init__.py", line 75, in install
    _install(path, remove, prefix, mode='user', root_prefix=root_prefix)
  File "C:\Users\dalth\anaconda3\lib\site-packages\menuinst\__init__.py", line 33, in _install
    data = json.load(open(path))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dalth\\anaconda3\\envs\\spyder_603rc1\\Menu\\spyder-menu-reset.jsodone
```

## Versions

* Spyder version: 6.0.3rc1  (conda)
* Python version: 3.10.16 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.19045-SP0

**Comment by ccordoba12** [comment]
@mrclary, please take a look at this one.
