### ISSUE TITLE
Issue: Anaconda Python V3.12

### ISSUE THREAD

**Issue by Santosh-Katuwal** [spyder-ide/spyder#23224]
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\ProgramData\anaconda3\Lib\site-packages\spyder\plugins\application\container.py", line 492, in _compute_dependencies
    dependencies.declare_dependencies()
  File "C:\ProgramData\anaconda3\Lib\site-packages\spyder\dependencies.py", line 458, in declare_dependencies
    add(dep['modname'], dep['package_name'],
  File "C:\ProgramData\anaconda3\Lib\site-packages\spyder\dependencies.py", line 389, in add
    DEPENDENCIES += [Dependency(modname, package_name, features,
  File "C:\ProgramData\anaconda3\Lib\site-packages\spyder\dependencies.py", line 331, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "C:\ProgramData\anaconda3\Lib\site-packages\spyder\utils\programs.py", line 839, in get_module_version
    mod = __import__(module_name)
  File "C:\ProgramData\anaconda3\Lib\site-packages\matplotlib\__init__.py", line 159, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:\ProgramData\anaconda3\Lib\site-packages\matplotlib\rcsetup.py", line 28, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\ProgramData\anaconda3\Lib\site-packages\matplotlib\colors.py", line 57, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "C:\ProgramData\anaconda3\Lib\site-packages\matplotlib\scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "C:\ProgramData\anaconda3\Lib\site-packages\matplotlib\ticker.py", line 144, in <module>
    from matplotlib import transforms as mtransforms
  File "C:\ProgramData\anaconda3\Lib\site-packages\matplotlib\transforms.py", line 49, in <module>
    from matplotlib._path import (
Traceback (most recent call last):
  File "C:\Users\Santosh\AppData\Roaming\Python\Python312\site-packages\numpy\core\_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\ProgramData\anaconda3\Lib\site-packages\spyder\plugins\application\container.py", line 492, in _compute_dependencies
    dependencies.declare_dependencies()
  File "C:\ProgramData\anaconda3\Lib\site-packages\spyder\dependencies.py", line 458, in declare_dependencies
    add(dep['modname'], dep['package_name'],
  File "C:\ProgramData\anaconda3\Lib\site-packages\spyder\dependencies.py", line 389, in add
    DEPENDENCIES += [Dependency(modname, package_name, features,
  File "C:\ProgramData\anaconda3\Lib\site-packages\spyder\dependencies.py", line 331, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "C:\ProgramData\anaconda3\Lib\site-packages\spyder\utils\programs.py", line 839, in get_module_version
    mod = __import__(module_name)
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\__init__.py", line 26, in <module>
    from pandas.compat import (
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\compat\__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\compat\pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "C:\ProgramData\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
Traceback (most recent call last):
  File "C:\Users\Santosh\AppData\Roaming\Python\Python312\site-packages\numpy\core\_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\ProgramData\anaconda3\Lib\site-packages\spyder\plugins\application\container.py", line 492, in _compute_dependencies
    dependencies.declare_dependencies()
  File "C:\ProgramData\anaconda3\Lib\site-packages\spyder\dependencies.py", line 458, in declare_dependencies
    add(dep['modname'], dep['package_name'],
  File "C:\ProgramData\anaconda3\Lib\site-packages\spyder\dependencies.py", line 389, in add
    DEPENDENCIES += [Dependency(modname, package_name, features,
  File "C:\ProgramData\anaconda3\Lib\site-packages\spyder\dependencies.py", line 331, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "C:\ProgramData\anaconda3\Lib\site-packages\spyder\utils\programs.py", line 839, in get_module_version
    mod = __import__(module_name)
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\core\api.py", line 1, in <module>
    from pandas._libs import (
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\_libs\__init__.py", line 17, in <module>
    import pandas._libs.pandas_datetime  # noqa: F401 # isort: skip # type: ignore[reportUnusedImport]
Traceback (most recent call last):
  File "C:\Users\Santosh\AppData\Roaming\Python\Python312\site-packages\numpy\core\_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

**Comment by ccordoba12** [comment]
Hey @Santosh-Katuwal, thanks for reporting. To fix this problem, please go to this directory in the Windows Explorer:

    C:\Users\Santosh\AppData\Roaming\Python

and remove it.

In addition, please avoid installing Numpy or other packages that depend on it with pip (that's what caused the problem in the first place).
