### ISSUE TITLE
can't use spyder 6

### ISSUE THREAD

**Issue by todoshi-max** [spyder-ide/spyder#23238]
### What steps will reproduce the problem?

cant use spyder v6 after i install it in my computer so i just use spyder 5.4

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\spyder-env\lib\site-packages\spyder\plugins\maininterpreter\widgets\status.py", line 177, in update_envs
    self.envs.update(**output)
TypeError: dict.update() argument after ** must be a mapping, not NoneType
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\spyder-env\lib\site-packages\spyder\plugins\maininterpreter\widgets\status.py", line 177, in update_envs
    self.envs.update(**output)
TypeError: dict.update() argument after ** must be a mapping, not NoneType
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\spyder-env\lib\site-packages\spyder\plugins\maininterpreter\widgets\status.py", line 177, in update_envs
    self.envs.update(**output)
TypeError: dict.update() argument after ** must be a mapping, not NoneType
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\spyder-env\lib\site-packages\spyder\plugins\maininterpreter\widgets\status.py", line 177, in update_envs
    self.envs.update(**output)
TypeError: dict.update() argument after ** must be a mapping, not NoneType
```

## Versions

* Spyder version: 5.4.0  (conda)
* Python version: 3.9.19 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  3.0.0 (OK)
cookiecutter >=1.6.0          :  2.6.0 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  1.0.1 (OK)
jsonschema >=3.2.0            :  4.19.2 (OK)
keyring >=17.0.0              :  24.3.1 (OK)
nbconvert >=4.0               :  7.10.0 (OK)
numpydoc >=0.6.0              :  1.7.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.15.1 (OK)
pylint >=2.5.0;<3.0           :  2.16.2 (OK)
pylint_venv >=2.1.1           :  3.0.3 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.6.0;<1.7.0          :  1.6.0 (OK)
pylsp_black >=1.2.0           :  2.0.0 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.3.1 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.2 (OK)
qtpy >=2.1.0                  :  2.4.1 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  75.1.0 (OK)
sphinx >=0.6.6                :  7.3.7 (OK)
spyder_kernels >=2.4.0;<2.5.0 :  2.4.4 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  4.0.1 (OK)
zmq >=22.1.0                  :  25.1.2 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.9.2 (OK)
numpy >=1.7                   :  1.26.4 (OK)
pandas >=1.1.1                :  2.2.2 (OK)
scipy >=0.17.0                :  1.13.1 (OK)
sympy >=0.7.3                 :  1.12 (OK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at C:\ProgramData\Miniconda3\envs\spyder-env:
#
# Name                    Version                   Build  Channel
affine                    2.3.0              pyhd3eb1b0_0  
aiohappyeyeballs          2.4.3            py39haa95532_0  
aiohttp                   3.10.5           py39h827c3e9_0  
aiosignal                 1.2.0              pyhd3eb1b0_0  
alabaster                 0.7.16           py39haa95532_0  
arrow                     1.2.3            py39haa95532_1  
arrow-cpp                 16.1.0               h7cd61ee_0  
astroid                   2.14.2           py39haa95532_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
async-timeout             4.0.3            py39haa95532_0  
asyncssh                  2.17.0           py39haa95532_0  
atomicwrites              1.4.0                      py_0  
attrs                     23.1.0           py39haa95532_0  
autopep8                  1.6.0              pyhd3eb1b0_1  
aws-c-auth                0.6.19               h2bbff1b_0  
aws-c-cal                 0.5.20               h2bbff1b_0  
aws-c-common              0.8.5                h2bbff1b_0  
aws-c-compression         0.2.16               h2bbff1b_0  
aws-c-event-stream        0.2.15               hd77b12b_0  
aws-c-http                0.6.25               h2bbff1b_0  
aws-c-io                  0.13.10              h2bbff1b_0  
aws-c-mqtt                0.7.13               h2bbff1b_0  
aws-c-s3                  0.1.51               h2bbff1b_0  
aws-c-sdkutils            0.1.6                h2bbff1b_0  
aws-checksums             0.1.13               h2bbff1b_0  
aws-crt-cpp               0.18.16              hd77b12b_0  
aws-sdk-cpp               1.10.55              hd77b12b_0  
babel                     2.11.0           py39haa95532_0  
backcall                  0.2.0              pyhd3eb1b0_0  
bcrypt                    3.2.0            py39h2bbff1b_1  
beautifulsoup4            4.12.3           py39haa95532_0  
binaryornot               0.4.4              pyhd3eb1b0_1  
black                     24.8.0           py39haa95532_0  
blas                      1.0                         mkl  
bleach                    4.1.0              pyhd3eb1b0_0  
blosc                     1.21.3               h6c2663c_0  
bokeh                     3.4.3            py39h9909e9c_0  
boost-cpp                 1.82.0               h59b6b97_2  
bottleneck                1.3.7            py39h9128911_0  
branca                    0.6.0            py39haa95532_0  
brotli                    1.0.9                h2bbff1b_8  
brotli-bin                1.0.9                h2bbff1b_8  
brotli-python             1.0.9            py39hd77b12b_8  
bzip2                     1.0.8                h2bbff1b_6  
c-ares                    1.19.1               h2bbff1b_0  
ca-certificates           2024.11.26           haa95532_0  
cairo                     1.16.0               haedb8bc_5  
cartopy                   0.22.0           py39h4748b25_0  
certifi                   2024.8.30        py39haa95532_0  
cffi                      1.17.1           py39h827c3e9_0  
cfitsio                   3.470                h2bbff1b_7  
cftime                    1.6.2            py39h080aedc_0  
chardet                   4.0.0           py39haa95532_1003  
charset-normalizer        3.3.2              pyhd3eb1b0_0  
click                     8.1.7            py39haa95532_0  
click-plugins             1.1.1              pyhd3eb1b0_0  
cligj                     0.7.2            py39haa95532_0  
cloudpickle               3.0.0            py39haa95532_0  
colorama                  0.4.6            py39haa95532_0  
comm                      0.2.1            py39haa95532_0  
condacolab                0.1.6                    pypi_0    pypi
contourpy                 1.2.0            py39h59b6b97_0  
cookiecutter              2.6.0            py39haa95532_0  
cryptography              43.0.0           py39h89fc84f_0  
cycler                    0.12.1                   pypi_0    pypi
cytoolz                   0.12.2           py39h2bbff1b_0  
dask                      2024.5.0         py39haa95532_0  
dask-core                 2024.5.0         py39haa95532_0  
dask-expr                 1.1.0            py39haa95532_0  
debugpy                   1.6.7            py39hd77b12b_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
deprecated                1.2.13           py39haa95532_0  
diff-match-patch          20200713           pyhd3eb1b0_0  
dill                      0.3.8            py39haa95532_0  
distributed               2024.5.0         py39haa95532_0  
docstring-to-markdown     0.11             py39haa95532_0  
docutils                  0.18.1           py39haa95532_3  
et_xmlfile                1.1.0            py39haa95532_0  
exceptiongroup            1.1.3                    pypi_0    pypi
executing                 0.8.3              pyhd3eb1b0_0  
expat                     2.6.3                h5da7b33_0  
fiona                     1.9.5            py39h4ed8f06_0  
flake8                    5.0.4              pyhd8ed1ab_0    conda-forge
folium                    0.14.0           py39haa95532_0  
fontconfig                2.14.1               hb33846d_3  
fonttools                 4.47.2                   pypi_0    pypi
freetype                  2.12.1               ha860e81_0  
freexl                    2.0.0                hd7a5696_0  
frozenlist                1.5.0            py39h827c3e9_0  
fsspec                    2024.6.1         py39haa95532_0  
gdal                      3.6.2            py39h7670e6c_5  
geopandas                 0.9.0              pyhd8ed1ab_0    conda-forge
geopandas-base            0.14.2           py39haa95532_0  
geos                      3.8.0                h33f27b4_0  
geotiff                   1.7.0                h4545760_3  
gflags                    2.2.2                hd77b12b_1  
glib                      2.78.4               hd77b12b_0  
glib-tools                2.78.4               hd77b12b_0  
glog                      0.5.0                hd77b12b_1  
hdf4                      4.2.13               h712560f_2  
hdf5                      1.12.1               h51c971a_3  
heapdict                  1.0.1              pyhd3eb1b0_0  
icc_rt                    2022.1.0             h6049295_2  
icu                       73.1                 h6c2663c_0  
idna                      3.7              py39haa95532_0  
imagesize                 1.4.1            py39haa95532_0  
importlib-metadata        7.0.1            py39haa95532_0  
importlib_metadata        7.0.1                hd3eb1b0_0  
importlib_resources       6.4.0            py39haa95532_0  
inflection                0.5.1            py39haa95532_0  
iniconfig                 2.0.0                    pypi_0    pypi
intel-openmp              2023.1.0         h59b6b97_46320  
intervaltree              3.1.0              pyhd3eb1b0_0  
ipykernel                 6.29.5           py39haa95532_0  
ipython                   7.31.1           py39haa95532_1  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
isort                     5.13.2           py39haa95532_0  
jaraco.classes            3.2.1              pyhd3eb1b0_0  
jedi                      0.18.1           py39haa95532_1  
jellyfish                 1.0.1            py39h36a85e1_0  
jinja2                    3.1.4            py39haa95532_0  
joblib                    1.4.2            py39haa95532_0  
jpeg                      9e                   h827c3e9_3  
jsonschema                4.19.2           py39haa95532_0  
jsonschema-specifications 2023.7.1         py39haa95532_0  
jupyter_client            8.6.0            py39haa95532_0  
jupyter_core              5.7.2            py39haa95532_0  
jupyterlab_pygments       0.2.2            py39haa95532_0  
kealib                    1.5.0                hde4a422_1  
keyring                   24.3.1           py39haa95532_0  
kiwisolver                1.4.5                    pypi_0    pypi
krb5                      1.20.1               h5b6d351_0  
lazy-object-proxy         1.10.0           py39h2bbff1b_0  
lcms2                     2.12                 h83e58a3_0  
lerc                      3.0                  hd77b12b_0  
libabseil                 20240116.2      cxx17_h5da7b33_0  
libboost                  1.82.0               h3399ecb_2  
libbrotlicommon           1.0.9                h2bbff1b_8  
libbrotlidec              1.0.9                h2bbff1b_8  
libbrotlienc              1.0.9                h2bbff1b_8  
libclang                  14.0.6          default_hb5a9fac_1  
libclang13                14.0.6          default_h8e68704_1  
libcurl                   8.9.1                h0416ee5_0  
libdeflate                1.17                 h2bbff1b_1  
libevent                  2.1.12               h56d1f94_1  
libffi                    3.4.4                hd77b12b_1  
libgdal                   3.6.2                h0e70117_5  
libglib                   2.78.4               ha17d25a_0  
libgrpc                   1.62.2               hf25190f_0  
libiconv                  1.16                 h2bbff1b_3  
libkml                    1.3.0                h63940dd_7  
libnetcdf                 4.8.1                h6685c40_4  
libpng                    1.6.39               h8cc25b3_0  
libpq                     12.17                h906ac69_0  
libprotobuf               4.25.3               hf2fb9eb_0  
libsodium                 1.0.18               h62dcd97_0  
libspatialindex           1.9.3                h6c2663c_0  
libspatialite             5.1.0                h25d3e1c_1  
libssh2                   1.11.0               h291bd65_0  
libthrift                 0.15.0               h4364b78_2  
libtiff                   4.5.1                hd77b12b_0  
libwebp-base              1.3.2                h2bbff1b_0  
libxml2                   2.13.1               h24da03e_2  
libzip                    1.8.0                h289538f_1  
locket                    1.0.0            py39haa95532_0  
lz4                       4.3.2            py39h2bbff1b_0  
lz4-c                     1.9.4                h2bbff1b_1  
mapclassify               2.5.0            py39haa95532_0  
markdown-it-py            2.2.0            py39haa95532_1  
markupsafe                2.1.3            py39h2bbff1b_0  
matplotlib                3.8.2                    pypi_0    pypi
matplotlib-base           3.9.2            py39he19b0ae_0  
matplotlib-inline         0.1.6            py39haa95532_0  
mccabe                    0.7.0              pyhd3eb1b0_0  
mdurl                     0.1.0            py39haa95532_0  
minizip                   4.0.3                hb68bac4_0  
mistune                   2.0.4            py39haa95532_0  
mkl                       2023.1.0         h6b88ed4_46358  
mkl-service               2.4.0            py39h2bbff1b_1  
mkl_fft                   1.3.10           py39h827c3e9_0  
mkl_random                1.2.7            py39hc64d2fc_0  
more-itertools            10.1.0           py39haa95532_0  
mpmath                    1.3.0                    pypi_0    pypi
msgpack-python            1.0.3            py39h59b6b97_0  
multidict                 6.1.0            py39h827c3e9_0  
mypy_extensions           1.0.0            py39haa95532_0  
nbclient                  0.8.0            py39haa95532_0  
nbconvert                 7.10.0           py39haa95532_0  
nbformat                  5.9.2            py39haa95532_0  
nest-asyncio              1.6.0            py39haa95532_0  
netcdf4                   1.6.2            py39hda396d2_0  
networkx                  3.2.1            py39haa95532_0  
numexpr                   2.8.7            py39h2cd9be0_0  
numpy                     1.26.4           py39h055cbcc_0  
numpy-base                1.26.4           py39h65a83cf_0  
numpydoc                  1.7.0            py39haa95532_0  
openjpeg                  2.5.2                hae555c5_0  
openpyxl                  3.1.5            py39h827c3e9_0  
openssl                   3.0.15               h827c3e9_0  
orc                       2.0.1                hd8d391b_0  
packaging                 23.2                     pypi_0    pypi
pandas                    2.2.2            py39h5da7b33_0  
pandocfilters             1.5.0              pyhd3eb1b0_0  
paramiko                  2.8.1              pyhd3eb1b0_0  
parso                     0.8.3              pyhd3eb1b0_0  
partd                     1.4.1            py39haa95532_0  
pathspec                  0.10.3           py39haa95532_0  
patsy                     0.5.3                    pypi_0    pypi
pcre2                     10.42                h0ff8eda_1  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    10.2.0                   pypi_0    pypi
pip                       24.2             py39haa95532_0  
pixman                    0.40.0               h2bbff1b_1  
platformdirs              3.10.0           py39haa95532_0  
pluggy                    1.0.0            py39haa95532_1  
ply                       3.11             py39haa95532_0  
poppler                   22.12.0              h0bf3bde_3  
poppler-data              0.4.11               haa95532_1  
proj                      9.3.1                ha107b6e_0  
prompt-toolkit            3.0.43           py39haa95532_0  
propcache                 0.2.0            py39h827c3e9_0  
psutil                    5.9.0            py39h2bbff1b_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
pyarrow                   16.1.0           py39hc64d2fc_0  
pybind11-abi              5                    hd3eb1b0_0  
pycodestyle               2.9.1              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd3eb1b0_0  
pydocstyle                6.3.0            py39haa95532_0  
pyflakes                  2.5.0              pyhd8ed1ab_0    conda-forge
pygithub                  2.4.0            py39haa95532_0  
pygments                  2.15.1           py39haa95532_1  
pyjwt                     2.9.0            py39haa95532_0  
pylint                    2.16.2           py39haa95532_0  
pylint-venv               3.0.3            py39haa95532_0  
pyls-spyder               0.4.0              pyhd3eb1b0_0  
pynacl                    1.5.0            py39h8cc25b3_0  
pyparsing                 3.1.1                    pypi_0    pypi
pyproj                    3.6.1            py39h8d66fa9_0  
pyqt                      5.15.10          py39hd77b12b_0  
pyqt5-sip                 12.13.0          py39h2bbff1b_0  
pyqtwebengine             5.15.10          py39hd77b12b_0  
pyshp                     2.3.1            py39haa95532_0  
pysocks                   1.7.1            py39haa95532_0  
pytest                    7.4.3                    pypi_0    pypi
python                    3.9.19               h1aa4202_1  
python-dateutil           2.9.0post0       py39haa95532_2  
python-fastjsonschema     2.16.2           py39haa95532_0  
python-lmdb               1.4.1            py39hd77b12b_0  
python-lsp-black          2.0.0            py39haa95532_0  
python-lsp-jsonrpc        1.1.2              pyhd3eb1b0_0  
python-lsp-server         1.6.0                hd8ed1ab_0    conda-forge
python-lsp-server-base    1.6.0              pyhd8ed1ab_0    conda-forge
python-slugify            5.0.2              pyhd3eb1b0_0  
python-tzdata             2023.3             pyhd3eb1b0_0  
python_abi                3.9                      2_cp39    conda-forge
pytoolconfig              1.2.6            py39haa95532_0  
pytz                      2024.1           py39haa95532_0  
pyuca                     1.2              py39haa95532_1  
pywin32                   305              py39h2bbff1b_0  
pywin32-ctypes            0.2.2            py39haa95532_0  
pyyaml                    6.0.1            py39h2bbff1b_0  
pyzmq                     25.1.2           py39hd77b12b_0  
qdarkstyle                3.0.2              pyhd3eb1b0_0  
qhull                     2020.2               h59b6b97_2  
qstylizer                 0.2.2            py39haa95532_0  
qt-main                   5.15.2              h19c9488_10  
qt-webengine              5.15.9               h5bd16bc_7  
qtawesome                 1.3.1            py39haa95532_0  
qtconsole                 5.4.2            py39haa95532_0  
qtpy                      2.4.1            py39haa95532_0  
rasterio                  1.3.10           py39had1fd89_0  
re2                       2022.04.01           hd77b12b_0  
referencing               0.30.2           py39haa95532_0  
requests                  2.32.3           py39haa95532_1  
rich                      13.7.1           py39haa95532_0  
rioxarray                 0.13.4             pyhd8ed1ab_0    conda-forge
rope                      1.12.0           py39haa95532_0  
rpds-py                   0.10.6           py39h062c2fa_0  
rtree                     1.0.1            py39h2eaa2aa_0  
scikit-learn              1.5.1            py39hc64d2fc_0  
scipy                     1.11.3                   pypi_0    pypi
seaborn                   0.13.2           py39haa95532_0  
setuptools                75.1.0           py39haa95532_0  
shapely                   1.7.0                    pypi_0    pypi
sip                       6.7.12           py39hd77b12b_0  
six                       1.16.0             pyhd3eb1b0_1  
snappy                    1.2.1                hcdb6601_0  
snowballstemmer           2.2.0              pyhd3eb1b0_0  
snuggs                    1.4.7              pyhd3eb1b0_0  
sortedcontainers          2.4.0              pyhd3eb1b0_0  
soupsieve                 2.5              py39haa95532_0  
sphinx                    7.3.7            py39h827c3e9_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.10           py39haa95532_0  
spyder                    5.4.0            py39hcbf5309_0    conda-forge
spyder-kernels            2.4.4            py39haa95532_0  
sqlite                    3.45.3               h2bbff1b_0  
stack_data                0.2.0              pyhd3eb1b0_0  
state-space               0.0.3                    pypi_0    pypi
statsmodels               0.14.0                   pypi_0    pypi
superqt                   0.6.7            py39h9909e9c_0  
sympy                     1.12                     pypi_0    pypi
tabulate                  0.9.0            py39haa95532_0  
tbb                       2021.8.0             h59b6b97_0  
tblib                     1.7.0              pyhd3eb1b0_0  
text-unidecode            1.3                pyhd3eb1b0_0  
textdistance              4.2.1              pyhd3eb1b0_0  
threadpoolctl             3.5.0            py39h9909e9c_0  
three-merge               0.1.1              pyhd3eb1b0_0  
tiledb                    2.3.3                hd8964de_3  
tinycss2                  1.2.1            py39haa95532_0  
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.1            py39haa95532_0  
tomlkit                   0.11.1           py39haa95532_0  
toolz                     0.12.0           py39haa95532_0  
tornado                   6.4.1            py39h827c3e9_0  
traitlets                 5.14.3           py39haa95532_0  
typing-extensions         4.11.0           py39haa95532_0  
typing_extensions         4.11.0           py39haa95532_0  
tzdata                    2024a                h04d1e81_0  
ujson                     5.10.0           py39h5da7b33_0  
unicodedata2              15.1.0           py39h2bbff1b_0  
unidecode                 1.3.8            py39haa95532_0  
uriparser                 0.9.7                h2bbff1b_0  
urllib3                   2.2.2            py39haa95532_0  
utf8proc                  2.6.1                h2bbff1b_1  
vc                        14.40                h2eaa2aa_1  
vs2015_runtime            14.40.33807          h98bb1dd_1  
watchdog                  4.0.1            py39haa95532_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1            py39haa95532_1  
whatthepatch              1.0.2            py39haa95532_0  
wheel                     0.44.0           py39haa95532_0  
win_inet_pton             1.1.0            py39haa95532_0  
wrapt                     1.14.1           py39h2bbff1b_0  
xarray                    2023.6.0         py39haa95532_0  
xerces-c                  3.2.4                hd77b12b_1  
xyzservices               2022.9.0         py39haa95532_1  
xz                        5.4.6                h8cc25b3_1  
yaml                      0.2.5                he774522_0  
yapf                      0.40.2           py39haa95532_0  
yarl                      1.18.0           py39h827c3e9_0  
zeromq                    4.3.5                hd77b12b_0  
zict                      3.0.0            py39haa95532_0  
zipp                      3.17.0           py39haa95532_0  
zlib                      1.2.13               h8cc25b3_1  
zstd                      1.5.5                hd43e919_2  

```
</details>

**Comment by dalthviz** [comment]
Hi @todoshi-max thank you for the feedback! Could you give some more info about your current setup and how did you try to install Spyder 6? From the env information that in the report seems like you are mixing pip with conda and also conda channels (defaults vs conda-forge) which usually can cause problems. For more info on that you can check the Spyder docs FAQ page: https://docs.spyder-ide.org/5/en/faq.html#using-spyder

Also, are you seeing some error when installing Spyder 6? Or there is some other specific reason why you prefer Spyder 5? If you want to still use Spyder 5 I would suggest you to use the latest version available (5.5.6) from conda-forge (creating a new conda environment that only uses the conda-forge channel).

Let us know if the info above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
