### ISSUE TITLE
UnboundLocalError when checking for updates on non-recognized platforms

### ISSUE THREAD

**Issue by boilednut** [spyder-ide/spyder#23237]
### What steps will reproduce the problem?

Run Spyder on a platform other than Windows, Lixus, or MacOS. Check for an software update.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/spyder/plugins/updatemanager/widgets/update.py", line 230, in _process_check_update
    self.start_update()
  File "/usr/local/lib/python3.11/site-packages/spyder/plugins/updatemanager/widgets/update.py", line 290, in start_update
    self._set_installer_path()
  File "/usr/local/lib/python3.11/site-packages/spyder/plugins/updatemanager/widgets/update.py", line 252, in _set_installer_path
    fname = f'Spyder-{plat}-{mach}.{ext}'
                      ^^^^
UnboundLocalError: cannot access local variable 'plat' where it is not associated with a value
```

## Versions

* Spyder version: 6.0.1  (pip)
* Python version: 3.11.10 64-bit
* Qt version: 5.15.16
* PyQt5 version: 5.15.11
* Operating System: FreeBSD-13.4-RELEASE-p1-amd64-64bit-ELF

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.11.7 (OK)
asyncssh >=2.14.0                :  2.18.0 (OK)
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.1.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20241021 (OK)
github >=2.3.0                   :  2.5.0 (OK)
importlib_metadata >=4.6.0       :  8.5.0 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.18.1 (OK)
jedi >=0.17.2                    :  0.19.1 (OK)
jellyfish >=0.7                  :  0.11.2 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  23.9.3 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.6.0 (OK)
parso >=0.7.0                    :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  6.1.0 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1                     :  3.3.1 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0                   :  1.12.0 (OK)
pylsp_black >=2.0.0              :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0               :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.4 (OK)
qtawesome >=1.3.1                :  1.3.1 (OK)
qtconsole >=5.6.0                :  5.6.1 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.2.0 (OK)
setuptools >=49.6.0              :  63.1.0 (OK)
sphinx >=0.6.6                   :  5.3.0 (OK)
spyder_kernels >=3.0.0           :  3.0.2 (OK)
superqt >=0.6.2                  :  0.6.7 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.2 (OK)
yarl >=1.9.4                     :  1.18.0 (OK)
zmq >=24.0.0                     :  25.0.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  None (NOK)
numpy >=1.7                      :  1.26.4 (OK)
pandas >=1.1.1                   :  2.1.4 (OK)
scipy >=0.17.0                   :  1.11.1 (OK)
sympy >=0.7.3                    :  1.11.1 (OK)
```

### Environment

<details><summary>Environment</summary>

```
Package                       Version
----------------------------- -----------
aiohappyeyeballs              2.4.3
aiohttp                       3.11.7
aioitertools                  0.12.0
aioquic                       1.2.0
aiosignal                     1.3.1
alabaster                     0.7.16
anyio                         4.6.2
arrow                         1.3.0
asgiref                       3.8.1
astroid                       3.3.5
asttokens                     2.4.1
async-generator               1.10
asyncssh                      2.18.0
atomicwrites                  1.4.1
attrs                         24.2.0
autopep8                      2.3.1
babel                         2.16.0
bcrypt                        3.2.2
beautifulsoup4                4.12.3
binaryornot                   0.4.4
black                         24.10.0
bleach                        6.2.0
blinker                       1.9.0
bottleneck                    1.3.8
cattrs                        24.1.2
certifi                       2024.8.30
cffi                          1.17.1
chardet                       5.2.0
charset-normalizer            3.4.0
click                         8.1.7
cloudpickle                   3.1.0
colorama                      0.4.6
comm                          0.2.2
cookiecutter                  2.6.0
crosshair-tool                0.0.78
cryptography                  42.0.8
cupshelpers                   1.0
debugpy                       1.8.3
decorator                     5.1.1
defusedxml                    0.7.1
deprecated                    1.2.14
diff-match-patch              20241021
dill                          0.3.9
django                        4.2.17
dnspython                     2.7.0
docstring-to-markdown         0.15
docutils                      0.21.2
dpcontracts                   0.6.0
evdev                         1.7.0
executing                     2.1.0
fastjsonschema                2.19.1
fido2                         1.1.3
flake8                        7.1.1
Flask                         3.1.0
frozenlist                    1.5.0
future                        0.18.3
gmpy2                         2.2.1
graphviz                      0.10.1
greenbone-feed-sync           24.3.0
h11                           0.14.0
h2                            4.1.0
helpdev                       0.7.1
hpack                         4.0.0
html5lib                      1.1
httpcore                      1.0.7
httpx                         0.27.2
hyperframe                    6.0.0
hypothesis                    6.119.3
hypothesis-crosshair          0.0.18
idna                          3.10
imagesize                     1.4.1
impacket                      0.11.0
importlib-metadata            8.5.0
importlib-resources           6.4.5
inflection                    0.5.1
iniconfig                     1.1.1
interegular                   0.3.3
intervaltree                  3.1.0
ipykernel                     6.29.5
ipyparallel                   9.0.0
ipython                       8.18.1
isort                         5.13.2
itsdangerous                  2.2.0
jaraco.classes                3.4.0
jedi                          0.19.1
jeepney                       0.8.0
jellyfish                     0.11.2
Jinja2                        3.1.4
joblib                        1.3.2
jsonschema                    4.23.0
jsonschema-specifications     2024.10.1
jupyter_client                8.6.3
jupyter_core                  5.7.2
jupyterlab_pygments           0.3.0
keyring                       23.9.3
lark                          1.1.9
ldap3                         2.9.1
ldapdomaindump                0.9.4
lsprotocol                    2023.0.1
lxml                          4.9.3
markdown                      3.6
markdown-it-py                3.0.0
markupsafe                    2.1.5
matplotlib-inline             0.1.6
mccabe                        0.7.0
mdurl                         0.1.2
mistune                       3.0.2
more-itertools                10.5.0
mpmath                        1.3.0
multidict                     6.1.0
mypy                          1.13.0
mypy-extensions               1.0.0
nbclient                      0.10.0
nbconvert                     7.16.4
nbformat                      5.10.4
nest-asyncio                  1.6.0
numexpr                       2.10.1
numpy                         1.26.4
numpydoc                      1.6.0
orjson                        3.10.11
outcome                       1.3.0.post0
packaging                     24.2
pandas                        2.1.4
pandocfilters                 1.5.1
parso                         0.8.4
pathspec                      0.12.1
patsy                         1.0.1
pexpect                       4.9.0
pickleshare                   0.7.5
pip                           23.3.2
platformdirs                  4.3.6
pluggy                        1.5.0
poyo                          0.5.0
prompt-toolkit                3.0.48
propcache                     0.2.0
psutil                        6.1.0
ptyprocess                    0.7.0
pure-eval                     0.2.3
pwquality                     1.4.5
pyasn1                        0.6.0
pyasn1-modules                0.4.0
pycairo                       1.21.0
pycodestyle                   2.12.1
pycparser                     2.22
pycryptodomex                 3.21.0
pycups                        2.0.4
pycurl                        7.45.3
pydantic                      1.10.18
pydocstyle                    6.3.0
pyflakes                      3.2.0
PyGithub                      2.5.0
pygls                         1.3.1
pygments                      2.18.0
PyGObject                     3.50.0
pyjwt                         2.8.0
pylint                        3.3.1
pylint-venv                   3.0.3
pyls-black                    0.4.7
pyls-spyder                   0.4.0
pylsqpack                     0.3.18
PyNaCl                        1.5.0
pyOpenSSL                     24.1.0
PyQt5                         5.15.11
PyQt5-sip                     12.15.0
PyQtWebEngine                 5.15.7
pysocks                       1.7.1
PyStemmer                     2.0.1
pytest                        8.1.1
python-dateutil               2.9.0
python-lsp-black              2.0.0
python-lsp-jsonrpc            1.1.2
python-lsp-server             1.12.0
python-slugify                8.0.4
pytoolconfig                  1.3.1
pytz                          2024.2
pyuca                         1.2
pyudev                        0.24.1
pyxdg                         0.28
PyYAML                        6.0.1
pyzmq                         25.0.2
QDarkStyle                    3.2.3
qstylizer                     0.2.4
QtAwesome                     1.3.1
qtconsole                     5.6.1
QtPy                          2.4.1
redis                         5.2.0
referencing                   0.35.1
regex                         2024.7.24
requests                      2.32.3
rich                          13.9.4
rope                          1.7.0
rpds-py                       0.13.2
Rtree                         1.2.0
ruff                          0.7.3
scikit-learn                  1.4.0
SciPy                         1.11.1
SecretStorage                 3.3.3
service-identity              24.2.0
setuptools                    63.1.0
shtab                         1.7.1
six                           1.16.0
sniffio                       1.3.1
snowballstemmer               2.2.0
socksio                       1.0.0
sortedcontainers              2.4.0
soupsieve                     2.0.1
Sphinx                        5.3.0
sphinx-autodoc-typehints      1.23.0
sphinx-rtd-theme              1.0.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.1.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          2.0.0
sphinxcontrib-serializinghtml 2.0.0
spyder                        6.0.1
spyder-kernels                3.0.2
sqlite3                       0.0.0
sqlparse                      0.5.2
stack-data                    0.6.3
statsmodels                   0.14.1
superqt                       0.6.7
sympy                         1.11.1
tabulate                      0.9.0
text-unidecode                1.3
textdistance                  4.6.3
threadpoolctl                 3.5.0
three-merge                   0.1.1
tinycss2                      1.4.0
Tkinter                       0.0.0
toml                          0.10.2
tomli                         2.1.0
tomlkit                       0.13.2
tornado                       6.4
tqdm                          4.67.0
traitlets                     5.14.3
trio                          0.27.0
truststore                    0.10.0
types-python-dateutil         2.8.19.14
typeshed-client               2.7.0
typing_extensions             4.12.2
typing-inspect                0.9.0
tzdata                        2024.2
ujson                         5.10.0
urllib3                       1.26.20
watchdog                      4.0.2
wcwidth                       0.2.8
webencodings                  0.5.1
werkzeug                      3.1.3
whatthepatch                  1.0.2
wrapt                         1.16.0
wurlitzer                     3.1.1
xarray                        2024.10.0
yapf                          0.32.0
yarl                          1.18.0
zipp                          3.21.0

```
</details>

**Comment by dalthviz** [comment]
Hi @boilednut thank you for the report! Could it be possible for you to manually update Spyder to 6.0.2 and then try to check for an update again? I think over version 6.0.2 some changes where done to the update check process and since Spyder 6.0.3 was released then we could check if when trying to update from 6.0.2 to 6.0.3 the error persist.

Let us know!

**Comment by boilednut** [comment]
Hello. On FreeBSD, 'Spyder-Linux-x86_64.sh' (which is the auto-detection installation option) doesn't install properly. So, fixing this issue with 'update.py' is moot given that your update script will fail anyway. I'll just

**Comment by boilednut** [comment]
Hello. 

On FreeBSD, 'Spyder-Linux-x86_64.sh' (which is the auto-detection installation option) doesn't install properly. So, fixing this issue with 'update.py' is moot given that your update script will fail anyway. I'll just disable the update check startup option to keep the error from firing.

FYI, I originally installed Spyder via the FreeBSD package repository.

Thank you.

**Comment by ccordoba12** [comment]
> On FreeBSD, 'Spyder-Linux-x86_64.sh' (which is the auto-detection installation option) doesn't install properly.

That's because it's meant for Linux only (hence the `Linux` in its name and not `Unix`).

> I'll just disable the update check startup option to keep the error from firing.

We'll address that by not offering updates for platforms we don't recognize (like FreeBSD).

@mrclary, could you take care of that?

> FYI, I originally installed Spyder via the FreeBSD package repository.

Perhaps that's the best way to install it because the FreeBSD maintainers probably patch Spyder to work with it. Our pip package is only meant for Linux and Linux only.

By the way, we don't plan to support other Unix flavors because we don't have the resources nor the expertise to do that. So, it's up to you if you want to use it in FreeBSD, but don't expect it to behave the same as on Linux.

**Comment by boilednut** [comment]
> Our latest version can be installed with pip and you can manually update to it by using it (which is what I think @dalthviz meant).

As you stated in a previous reply,

> Spyder to work with it. **Our pip package is only meant for Linux and Linux only.**

So...a failure would've occurred...regardless.

**Comment by ccordoba12** [comment]
> As you stated in a previous reply,

Sure, good point.

> So...a failure would've occurred...regardless.

Well, for pip installations I don't think it's worth taking the time to do that because we have received very very few bug reports from other Unixes throughout the years (not more than 20 for sure). And for the official FreeBSD port, we can't control how other people packages Spyder (as I also said, probably its devs patch it to work with it).
