### ISSUE TITLE
Itis not responding properly like not giving desired output

### ISSUE THREAD

**Issue by RCS007** [spyder-ide/spyder#23249]
### What steps will reproduce the problem?

while trying to run code, spyder shows an error. It dose not run the code properly. 

### Traceback
```python-traceback
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 560, in _run_callback
    f = callback(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "D:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "D:\ProgramData\Anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "D:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 610, in _handle_events
    self._handle_recv()
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 639, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 560, in _run_callback
    f = callback(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "D:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "D:\ProgramData\Anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "D:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback SelectorThread._handle_select([7016], [])
handle: <Handle SelectorThread._handle_select([7016], [])>
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\tornado\platform\asyncio.py", line 616, in _handle_select
    self._handle_event(r, self._readers)
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\tornado\platform\asyncio.py", line 630, in _handle_event
    callback()
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\tornado\platform\asyncio.py", line 202, in _handle_events
    handler_func(fileobj, events)
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 610, in _handle_events
    self._handle_recv()
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 639, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 560, in _run_callback
    f = callback(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "D:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "D:\ProgramData\Anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "D:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 560, in _run_callback
    f = callback(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "D:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "D:\ProgramData\Anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "D:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 610, in _handle_events
    self._handle_recv()
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 639, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 560, in _run_callback
    f = callback(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "D:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "D:\ProgramData\Anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "D:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x0000026C37CA60D0>)
Traceback (most recent call last):
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\tornado\ioloop.py", line 750, in _run_callback
    ret = callback()
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 694, in <lambda>
    self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 610, in _handle_events
    self._handle_recv()
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 639, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 560, in _run_callback
    f = callback(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "D:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "D:\ProgramData\Anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "D:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 560, in _run_callback
    f = callback(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "D:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "D:\ProgramData\Anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "D:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 610, in _handle_events
    self._handle_recv()
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 639, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 560, in _run_callback
    f = callback(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "D:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "D:\ProgramData\Anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "D:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x0000026C37C99DC0>)
Traceback (most recent call last):
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\tornado\ioloop.py", line 750, in _run_callback
    ret = callback()
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 694, in <lambda>
    self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 610, in _handle_events
    self._handle_recv()
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 639, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 560, in _run_callback
    f = callback(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "D:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "D:\ProgramData\Anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "D:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 560, in _run_callback
    f = callback(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "D:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "D:\ProgramData\Anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "D:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 610, in _handle_events
    self._handle_recv()
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 639, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 560, in _run_callback
    f = callback(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "D:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "D:\ProgramData\Anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "D:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x0000026C37C824C0>)
Traceback (most recent call last):
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\tornado\ioloop.py", line 750, in _run_callback
    ret = callback()
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 694, in <lambda>
    self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 610, in _handle_events
    self._handle_recv()
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 639, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\Rajashree Sabale\AppData\Roaming\Python\Python39\site-packages\zmq\eventloop\zmqstream.py", line 560, in _run_callback
    f = callback(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 123, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "D:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "D:\ProgramData\Anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "D:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 34, in get_msg
    return await msg
TypeError: object list can't be used in 'await' expression
```

## Versions

* Spyder version: 5.2.2 
* Python version: 3.9.13
* Qt version: 5.15.2
* PyQt5 version: 5.15.11
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.17.2 (OK)
pylint >=2.5.0                :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.12.0 (NOK)
pylsp_black >=1.0.0           :  1.0.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.4 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.4.2 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  63.4.1 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  26.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.32 (OK)
matplotlib >=2.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.24.0 (OK)
pandas >=1.1.1                :  1.4.4 (OK)
scipy >=0.17.0                :  1.9.1 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @RCS007, thanks for reporting. Please locate this directory with the Windows file explorer:

    C:\Users\Rajashree Sabale\AppData\Roaming\Python

and remove it.

That should fix your problem but let us know if it really does.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
