### ISSUE TITLE
Error after update offered

### ISSUE THREAD

**Issue by remi-pr** [spyder-ide/spyder#23257]
### What steps will reproduce the problem?

Just opened Spyder. New version was offered for update. Update was declined. Error followed. 

As is made clear by the error message the `WorkerUpdate` class does not have a `channel` attribute. It is not created in the init nor anywhere else as far as I could tell.

I did not check if this is corrected in newer versions.

Thanks for the good work!

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/remi/.virtualenvs/test/lib/python3.8/site-packages/spyder/plugins/updatemanager/widgets/update.py", line 230, in _process_check_update
    self.start_update()
  File "/home/remi/.virtualenvs/test/lib/python3.8/site-packages/spyder/plugins/updatemanager/widgets/update.py", line 314, in start_update
    self, self.latest_release, self.update_worker.channel
AttributeError: 'WorkerUpdate' object has no attribute 'channel'
```

## Versions

* Spyder version: 6.0.1  (pip)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Linux-5.4.0-200-generic-x86_64-with-glibc2.29

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3               :  3.10.10 (OK)
asyncssh >=2.14.0,<3.0.0      :  2.17.0 (OK)
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  3.1.0 (OK)
cookiecutter >=1.6.0          :  2.6.0 (OK)
diff_match_patch >=20181111   :  20230430 (OK)
github >=2.3.0                :  2.4.0 (OK)
importlib_metadata >=4.6.0    :  8.5.0 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=8.12.2,<8.13.0      :  8.12.3 (OK)
jedi >=0.17.2,<0.20.0         :  0.18.0 (OK)
jellyfish >=0.7               :  1.1.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  25.4.1 (OK)
nbconvert >=4.0               :  5.6.1 (OK)
numpydoc >=0.6.0              :  1.7.0 (OK)
parso >=0.7.0,<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  6.1.0 (OK)
pygments >=2.0                :  2.18.0 (OK)
pylint >=3.1,<4               :  3.2.7 (OK)
pylint_venv >=3.0.2           :  3.0.3 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0        :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0    :  2.0.0 (OK)
pyuca >=1.2                   :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0     :  3.2.3 (OK)
qstylizer >=0.2.2             :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0      :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0      :  5.6.0 (OK)
qtpy >=2.4.0                  :  2.4.1 (OK)
rtree >=0.9.7                 :  1.3.0 (OK)
setuptools >=49.6.0           :  59.1.1 (OK)
sphinx >=0.6.6                :  7.1.2 (OK)
spyder_kernels >=3.0.0,<3.1.0 :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0        :  0.6.7 (OK)
textdistance >=4.2.0          :  4.6.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  4.0.2 (OK)
xdg >=0.26                    :  0.28 (OK)
yarl >=1.9.4                  :  1.15.2 (OK)
zmq >=24.0.0                  :  26.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.4.0 (OK)
numpy >=1.7                   :  1.21.4 (OK)
pandas >=1.1.1                :  1.3.2 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.12 (OK)
```

**Comment by ccordoba12** [comment]
Hey @remi-pr, thanks for reporting. To fix this problem you need to manually update Spyder to its latest version. You can do that by enabling your virtualenv and then running

    pip install -U spyder
