### ISSUE TITLE
Loading and Installing Packages

### ISSUE THREAD

**Issue by mcarlson45** [spyder-ide/spyder#23259]
### What steps will reproduce the problem?

Installing and loading certain packages returns an error, such as tabula

### Traceback
```python-traceback

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\plugins\application\container.py", line 414, in _compute_dependencies
    dependencies.declare_dependencies()
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\dependencies.py", line 453, in declare_dependencies
    add(dep['modname'], dep['package_name'],
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\dependencies.py", line 384, in add
    DEPENDENCIES += [Dependency(modname, package_name, features,
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\dependencies.py", line 326, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\utils\programs.py", line 839, in get_module_version
    mod = __import__(module_name)
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\matplotlib\__init__.py", line 131, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\matplotlib\colors.py", line 56, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\matplotlib\scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\matplotlib\ticker.py", line 138, in <module>
    from matplotlib import transforms as mtransforms
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\matplotlib\transforms.py", line 49, in <module>
    from matplotlib._path import (
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\plugins\application\container.py", line 414, in _compute_dependencies
    dependencies.declare_dependencies()
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\dependencies.py", line 453, in declare_dependencies
    add(dep['modname'], dep['package_name'],
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\dependencies.py", line 384, in add
    DEPENDENCIES += [Dependency(modname, package_name, features,
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\dependencies.py", line 326, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\utils\programs.py", line 839, in get_module_version
    mod = __import__(module_name)
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\__init__.py", line 39, in <module>
    from pandas.compat import (
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\compat\__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\compat\pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\plugins\application\container.py", line 414, in _compute_dependencies
    dependencies.declare_dependencies()
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\dependencies.py", line 453, in declare_dependencies
    add(dep['modname'], dep['package_name'],
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\dependencies.py", line 384, in add
    DEPENDENCIES += [Dependency(modname, package_name, features,
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\dependencies.py", line 326, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\utils\programs.py", line 839, in get_module_version
    mod = __import__(module_name)
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\core\dtypes\dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\plugins\application\container.py", line 414, in _compute_dependencies
    dependencies.declare_dependencies()
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\dependencies.py", line 453, in declare_dependencies
    add(dep['modname'], dep['package_name'],
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\dependencies.py", line 384, in add
    DEPENDENCIES += [Dependency(modname, package_name, features,
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\dependencies.py", line 326, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\utils\programs.py", line 839, in get_module_version
    mod = __import__(module_name)
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 50, in <module>
    from pandas.core import (
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\core\ops\__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\core\ops\array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\plugins\application\container.py", line 414, in _compute_dependencies
    dependencies.declare_dependencies()
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\dependencies.py", line 453, in declare_dependencies
    add(dep['modname'], dep['package_name'],
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\dependencies.py", line 384, in add
    DEPENDENCIES += [Dependency(modname, package_name, features,
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\dependencies.py", line 326, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\spyder\utils\programs.py", line 839, in get_module_version
    mod = __import__(module_name)
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py", line 60, in <module>
    from pandas.core import (
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\core\nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\mcarlson\AppData\Local\anaconda3\Lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,
AttributeError: _ARRAY_API not found
```

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.11.4 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  1.7.3 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.12.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  0.9.0 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  6.5.4 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.2.0 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.0.0 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.3 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  23.2.0 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  None (NOK)
numpy >=1.7                                      :  2.2.0 (OK)
pandas >=1.1.1                                   :  2.2.3 (OK)
scipy >=0.17.0                                   :  1.10.1 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)
```

**Comment by dalthviz** [comment]
Hi @mcarlson45 sorry for the late response! Seems like you installed an incompatible version of numpy in your conda base environment. There is not much we can do from the Spyder side but here a couple of related issues that you could check for more info: https://github.com/spyder-ide/spyder/issues/22667

**Comment by ccordoba12** [comment]
Closing due to lack of response.
