### ISSUE TITLE
Remote server connection from kernel 

### ISSUE THREAD

**Issue by rishannp** [spyder-ide/spyder#23282]
### What steps will reproduce the problem?

Connecting to remote server via remote connection
Then creating a new kernel from remote connection

### Traceback
```python-traceback
failed to create kernel_spec=None
exception calling callback for <Future at 0x15805bb08c0 state=finished raised ValueError>
Traceback (most recent call last):
  File "C:\Users\uceerjp\anaconda3\Lib\concurrent\futures\_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "C:\Users\uceerjp\anaconda3\Lib\site-packages\spyder\api\asyncdispatcher.py", line 128, in _callback_task_done
    raise exception
  File "C:\Users\uceerjp\anaconda3\Lib\site-packages\spyder\plugins\remoteclient\plugin.py", line 333, in _start_new_kernel
    return await client.start_new_kernel_ensure_server()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uceerjp\anaconda3\Lib\site-packages\spyder\plugins\remoteclient\api\client.py", line 697, in start_new_kernel_ensure_server
    kernel_id = await self.start_new_kernel()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uceerjp\anaconda3\Lib\site-packages\spyder\plugins\remoteclient\api\client.py", line 754, in start_new_kernel
    response = await jupyter.create_kernel(kernel_spec=kernel_spec)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uceerjp\anaconda3\Lib\site-packages\spyder\plugins\remoteclient\api\jupyterhub\__init__.py", line 303, in create_kernel
    raise ValueError(
ValueError: {"message": "Unhandled error", "reason": null, "traceback": ""}
exception calling callback for <Future at 0x15805bb08c0 state=finished raised ValueError>
Traceback (most recent call last):
  File "C:\Users\uceerjp\anaconda3\Lib\concurrent\futures\_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "C:\Users\uceerjp\anaconda3\Lib\site-packages\spyder\plugins\remoteclient\plugin.py", line 294, in <lambda>
    ipyclient, future.result()
               ^^^^^^^^^^^^^^^
  File "C:\Users\uceerjp\anaconda3\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uceerjp\anaconda3\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\uceerjp\anaconda3\Lib\concurrent\futures\_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "C:\Users\uceerjp\anaconda3\Lib\site-packages\spyder\api\asyncdispatcher.py", line 128, in _callback_task_done
    raise exception
  File "C:\Users\uceerjp\anaconda3\Lib\site-packages\spyder\plugins\remoteclient\plugin.py", line 333, in _start_new_kernel
    return await client.start_new_kernel_ensure_server()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uceerjp\anaconda3\Lib\site-packages\spyder\plugins\remoteclient\api\client.py", line 697, in start_new_kernel_ensure_server
    kernel_id = await self.start_new_kernel()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uceerjp\anaconda3\Lib\site-packages\spyder\plugins\remoteclient\api\client.py", line 754, in start_new_kernel
    response = await jupyter.create_kernel(kernel_spec=kernel_spec)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uceerjp\anaconda3\Lib\site-packages\spyder\plugins\remoteclient\api\jupyterhub\__init__.py", line 303, in create_kernel
    raise ValueError(
ValueError: {"message": "Unhandled error", "reason": null, "traceback": ""}
```

## Versions

* Spyder version: 6.0.1  (conda)
* Python version: 3.12.7 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-11-10.0.22631-SP0

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.10.5 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.17.0 (OK)
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
github >=2.3.0                   :  2.4.0 (OK)
importlib_metadata >=4.6.0       :  7.0.1 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.27.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.1 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  24.3.1 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.7.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.0 (OK)
pygments >=2.0                   :  2.15.1 (OK)
pylint >=3.1,<4                  :  3.2.7 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0         :  5.6.0 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.0.1 (OK)
setuptools >=49.6.0              :  67.6.1 (OK)
sphinx >=0.6.6                   :  7.3.7 (OK)
spyder_kernels >=3.0.0,<3.1.0    :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.2.1 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.1 (OK)
yarl >=1.9.4                     :  1.11.0 (OK)
zmq >=24.0.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  3.9.2 (OK)
numpy >=1.7                      :  1.26.4 (OK)
pandas >=1.1.1                   :  2.2.2 (OK)
scipy >=0.17.0                   :  1.13.1 (OK)
sympy >=0.7.3                    :  1.13.2 (OK)
```

**Comment by dalthviz** [comment]
Hi @rishannp sorry for the late response and thank you for the report! Could it be possible for you to update to the latest Spyder 6 release (6.0.3) and try again? Also, not totally sure what the error could be but pinging @ccordoba12 just in case (maybe something is missing to be setup over the remote server?)

**Comment by dalthviz** [comment]
Giving this a check seems like the code that handles the remote kernel start has changed  location a little bit. I think the current related line that could be linked to this issue is at https://github.com/spyder-ide/spyder/blob/24f491c015b2a091151f50eae7849438245fd32b/spyder/plugins/remoteclient/api/manager.py#L864

Also, the `create_kernel` method still raises a `ValueError` in case the response is not the expected one https://github.com/spyder-ide/spyder/blob/24f491c015b2a091151f50eae7849438245fd32b/spyder/plugins/remoteclient/api/modules/base.py#L354-L365

My guess is that we should try to handle this kind of error somehow? Maybe over https://github.com/spyder-ide/spyder/blob/24f491c015b2a091151f50eae7849438245fd32b/spyder/api/asyncdispatcher.py#L141-L142

Adding some sort of error dialog indicating that starting a kernel in the remote server was not possible? What do you think @ccordoba12 ?

**Comment by ccordoba12** [comment]
Since the Remote client plugin has changed so much between 6.x and master, let's leave this for 6.1.
