### ISSUE TITLE
Suggestions on Spyder

### ISSUE THREAD

**Issue by eqionger** [spyder-ide/spyder#23302]
### What steps will reproduce the problem?

For developers using Spyder, it's advisable to regularly update to the latest version for optimal performance and security fixes. Leverage built-in debugging tools and the variable explorer to enhance coding efficiency. When encountering issues, consulting official documentation or community forums often provides solutions. Customize keyboard shortcuts, themes, and settings to personalize your workflow and boost productivity. If internal errors occur, try restarting Spyder or the entire development environment, such as Anaconda Navigator, and ensure adequate system resources. For complex problems, examining log files or searching the GitHub issues list can offer valuable insights. Engaging with the Spyder community and support forums not only helps resolve issues but also facilitates knowledge exchange and best practices among developers.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\env3.7\lib\site-packages\spyder\plugins\maininterpreter\widgets\status.py", line 177, in update_envs
    self.envs.update(**output)
TypeError: update() argument after ** must be a mapping, not NoneType
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\env3.7\lib\site-packages\spyder\plugins\maininterpreter\widgets\status.py", line 177, in update_envs
    self.envs.update(**output)
TypeError: update() argument after ** must be a mapping, not NoneType
```

## Versions

* Spyder version: 5.3.3  (conda)
* Python version: 3.7.16 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.5.4 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.16.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.2 (OK)
qtawesome >=1.0.2             :  1.2.2 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.6.3 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.5.3 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  None (NOK)
```

### Environment

<details><summary>Environment</summary>

```
# packages in environment at C:\Users\Administrator\anaconda3\envs\env3.7:
#
# Name                    Version                   Build  Channel
absl-py                   2.1.0                    pypi_0    pypi
alabaster                 0.7.12             pyhd3eb1b0_0    defaults
arrow                     1.2.3            py37haa95532_1    defaults
astor                     0.8.1                    pypi_0    pypi
astroid                   2.14.2           py37haa95532_0    defaults
atomicwrites              1.4.0                      py_0    defaults
attrs                     22.1.0           py37haa95532_0    defaults
autopep8                  1.6.0              pyhd3eb1b0_1    defaults
babel                     2.11.0           py37haa95532_0    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
bcrypt                    3.2.0            py37h2bbff1b_1    defaults
beautifulsoup4            4.11.1           py37haa95532_0    defaults
binaryornot               0.4.4              pyhd3eb1b0_1    defaults
black                     22.6.0           py37haa95532_0    defaults
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
bleach                    4.1.0              pyhd3eb1b0_0    defaults
bottleneck                1.3.5            py37h080aedc_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
brotlipy                  0.7.0           py37h2bbff1b_1003    defaults
bzip2                     1.0.8                h2bbff1b_6    defaults
ca-certificates           2024.11.26           haa95532_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
certifi                   2022.12.7        py37haa95532_0    defaults
cffi                      1.15.1           py37h2bbff1b_3    defaults
chardet                   4.0.0           py37haa95532_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.0.4            py37haa95532_0    defaults
cloudpickle               2.0.0              pyhd3eb1b0_0    defaults
colorama                  0.4.6            py37haa95532_0    defaults
cookiecutter              1.7.3              pyhd3eb1b0_0    defaults
cryptography              43.0.3                   pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.5.1            py37hd77b12b_0    defaults
decorator                 5.1.1              pyhd3eb1b0_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
diff-match-patch          20200713           pyhd3eb1b0_0    defaults
dill                      0.3.6            py37haa95532_0    defaults
docutils                  0.17.1           py37haa95532_1    defaults
entrypoints               0.4              py37haa95532_0    defaults
fftw                      3.3.9                h2bbff1b_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
flake8                    4.0.1              pyhd3eb1b0_1    defaults
flit-core                 3.6.0              pyhd3eb1b0_0    defaults
fonttools                 4.38.0                   pypi_0    pypi
gast                      0.2.2                    pypi_0    pypi
giflib                    5.2.2                h7edc060_0    defaults
glib                      2.78.4               hd77b12b_0    defaults
glib-tools                2.78.4               hd77b12b_0    defaults
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.62.3                   pypi_0    pypi
h5py                      3.8.0                    pypi_0    pypi
icc_rt                    2022.1.0             h6049295_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
icu                       58.2                 ha925a31_3    defaults
idna                      3.4              py37haa95532_0    defaults
imagesize                 1.4.1            py37haa95532_0    defaults
importlib-metadata        4.2.0                    pypi_0    pypi
importlib_metadata        3.10.0               hd3eb1b0_0    defaults
importlib_resources       5.2.0              pyhd3eb1b0_1    defaults
inflection                0.5.1            py37haa95532_0    defaults
intel-openmp              2021.4.0          haa95532_3556    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
intervaltree              3.1.0              pyhd3eb1b0_0    defaults
ipykernel                 6.15.2           py37haa95532_0    defaults
ipython                   7.31.1           py37haa95532_1    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
isort                     5.9.3              pyhd3eb1b0_0    defaults
jedi                      0.18.1           py37haa95532_1    defaults
jellyfish                 0.9.0            py37h2bbff1b_0    defaults
jinja2                    3.1.2            py37haa95532_0    defaults
jinja2-time               0.2.0              pyhd3eb1b0_3    defaults
jpeg                      9e                   h827c3e9_3    defaults
jsonschema                4.17.3           py37haa95532_0    defaults
jupyter_client            7.4.9            py37haa95532_0    defaults
jupyter_core              4.11.2           py37haa95532_0    defaults
jupyterlab_pygments       0.1.2                      py_0    defaults
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
keyring                   23.4.0           py37haa95532_0    defaults
kiwisolver                1.4.5                    pypi_0    pypi
krb5                      1.20.1               h5b6d351_1    defaults
lazy-object-proxy         1.6.0            py37h2bbff1b_0    defaults
lerc                      3.0                  hd77b12b_0    defaults
libclang                  14.0.6          default_hb5a9fac_1    defaults
libclang13                14.0.6          default_h8e68704_1    defaults
libdeflate                1.17                 h2bbff1b_1    defaults
libffi                    3.4.4                hd77b12b_1    defaults
libglib                   2.78.4               ha17d25a_0    defaults
libiconv                  1.16                 h2bbff1b_3    defaults
libpng                    1.6.39               h8cc25b3_0    defaults
libpq                     12.15                hb652d5d_1    defaults
libsodium                 1.0.18               h62dcd97_0    defaults
libspatialindex           1.9.3                h6c2663c_0    defaults
libtiff                   4.5.1                hd77b12b_0    defaults
libwebp                   1.2.4                hbc33d0d_1    defaults
libwebp-base              1.2.4                h2bbff1b_1    defaults
libxml2                   2.9.14               h0ad7f3c_0    defaults
libxslt                   1.1.35               h2bbff1b_0    defaults
llvmlite                  0.39.1                   pypi_0    pypi
lxml                      4.9.1            py37h1985fb9_0    defaults
lz4-c                     1.9.4                h2bbff1b_1    defaults
markdown                  3.4.4                    pypi_0    pypi
markupsafe                2.1.1            py37h2bbff1b_0    defaults
matplotlib                3.5.3                    pypi_0    pypi
matplotlib-inline         0.1.6            py37haa95532_0    defaults
mccabe                    0.6.1                    pypi_0    pypi
mistune                   0.8.4           py37hfa6e2cd_1001    defaults
mkl                       2021.4.0           haa95532_640    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl-service               2.4.0            py37h2bbff1b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_fft                   1.3.1            py37h277e83a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_random                1.2.2            py37hf11a4ad_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mypy_extensions           0.4.3            py37haa95532_1    defaults
nbclient                  0.5.13           py37haa95532_0    defaults
nbconvert                 6.5.4            py37haa95532_0    defaults
nbformat                  5.7.0            py37haa95532_0    defaults
nest-asyncio              1.5.6            py37haa95532_0    defaults
numba                     0.56.4                   pypi_0    pypi
numexpr                   2.8.4            py37h5b0cc5e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy                     1.21.6                   pypi_0    pypi
numpy-base                1.21.5           py37hca35cd5_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpydoc                  1.5.0            py37haa95532_0    defaults
opencv-python             4.10.0.84                pypi_0    pypi
openssl                   1.1.1w               h2bbff1b_0    defaults
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 22.0             py37haa95532_0    defaults
pandas                    1.3.5            py37h6214cd6_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pandocfilters             1.5.0              pyhd3eb1b0_0    defaults
paramiko                  3.5.0                    pypi_0    pypi
parso                     0.8.3              pyhd3eb1b0_0    defaults
pathspec                  0.10.3           py37haa95532_0    defaults
pcre2                     10.42                h0ff8eda_1    defaults
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    9.5.0                    pypi_0    pypi
pip                       22.3.1           py37haa95532_0    defaults
pkgutil-resolve-name      1.3.10           py37haa95532_0    defaults
platformdirs              2.5.2            py37haa95532_0    defaults
pluggy                    1.0.0            py37haa95532_1    defaults
ply                       3.11                     py37_0    defaults
poyo                      0.5.0              pyhd3eb1b0_0    defaults
prompt-toolkit            3.0.36           py37haa95532_0    defaults
protobuf                  3.20.3                   pypi_0    pypi
psutil                    5.9.0            py37h2bbff1b_0    defaults
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
pycodestyle               2.8.0              pyhd3eb1b0_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pydocstyle                6.3.0            py37haa95532_0    defaults
pyflakes                  2.4.0              pyhd3eb1b0_0    defaults
pygments                  2.11.2             pyhd3eb1b0_0    defaults
pylint                    2.16.2           py37haa95532_0    defaults
pyls-spyder               0.4.0              pyhd3eb1b0_0    defaults
pynacl                    1.5.0            py37h8cc25b3_0    defaults
pyopenssl                 23.0.0           py37haa95532_0    defaults
pyparsing                 3.1.4                    pypi_0    pypi
pyqt                      5.15.7           py37hd77b12b_0    defaults
pyqt5-sip                 12.11.0          py37hd77b12b_0    defaults
pyqtwebengine             5.15.7           py37hd77b12b_0    defaults
pyrsistent                0.18.0           py37h196d8e1_0    defaults
pysocks                   1.7.1                    py37_1    defaults
python                    3.7.16               h6244533_0    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-fastjsonschema     2.16.2           py37haa95532_0    defaults
python-lsp-black          1.2.1            py37haa95532_0    defaults
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0    defaults
python-lsp-server         1.5.0            py37haa95532_0    defaults
python-slugify            5.0.2              pyhd3eb1b0_0    defaults
pytoolconfig              1.2.5            py37haa95532_1    defaults
pytz                      2022.7           py37haa95532_0    defaults
pywin32                   305              py37h2bbff1b_0    defaults
pywin32-ctypes            0.2.0                 py37_1001    defaults
pyyaml                    6.0              py37h2bbff1b_1    defaults
pyzmq                     23.2.0           py37hd77b12b_0    defaults
qdarkstyle                3.0.2              pyhd3eb1b0_0    defaults
qstylizer                 0.2.2            py37haa95532_0    defaults
qt-main                   5.15.2               h6072711_9    defaults
qt-webengine              5.15.9               h5bd16bc_7    defaults
qtawesome                 1.2.2            py37haa95532_0    defaults
qtconsole                 5.3.2            py37haa95532_0    defaults
qtpy                      2.2.0            py37haa95532_0    defaults
qtwebkit                  5.212                h3ad3cdb_4    defaults
requests                  2.28.1           py37haa95532_0    defaults
rope                      1.7.0            py37haa95532_0    defaults
rtree                     1.0.1            py37h2eaa2aa_0    defaults
scipy                     1.7.3            py37h7a0a035_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
setuptools                65.6.3           py37haa95532_0    defaults
sip                       6.6.2            py37hd77b12b_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
snowballstemmer           2.2.0              pyhd3eb1b0_0    defaults
sortedcontainers          2.4.0              pyhd3eb1b0_0    defaults
soupsieve                 2.3.2.post1      py37haa95532_0    defaults
sphinx                    4.2.0              pyhd3eb1b0_1    defaults
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0    defaults
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0    defaults
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0    defaults
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0    defaults
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0    defaults
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0    defaults
spyder                    5.3.3            py37haa95532_0    defaults
spyder-kernels            2.3.3            py37haa95532_0    defaults
sqlite                    3.45.3               h2bbff1b_0    defaults
tensorboard               1.15.0                   pypi_0    pypi
tensorflow                1.15.0                   pypi_0    pypi
tensorflow-estimator      1.15.1                   pypi_0    pypi
termcolor                 2.3.0                    pypi_0    pypi
text-unidecode            1.3                pyhd3eb1b0_0    defaults
textdistance              4.2.1              pyhd3eb1b0_0    defaults
three-merge               0.1.1              pyhd3eb1b0_0    defaults
tinycss2                  1.2.1            py37haa95532_0    defaults
toml                      0.10.2             pyhd3eb1b0_0    defaults
tomli                     2.0.1            py37haa95532_0    defaults
tomlkit                   0.11.1           py37haa95532_0    defaults
tornado                   6.2              py37h2bbff1b_0    defaults
traitlets                 5.7.1            py37haa95532_0    defaults
typed-ast                 1.4.3            py37h2bbff1b_1    defaults
typing-extensions         4.4.0            py37haa95532_0    defaults
typing_extensions         4.4.0            py37haa95532_0    defaults
ujson                     5.4.0            py37hd77b12b_0    defaults
unidecode                 1.2.0              pyhd3eb1b0_0    defaults
urllib3                   1.26.14          py37haa95532_0    defaults
vc                        14.40                h2eaa2aa_1    defaults
vs2015_runtime            14.40.33807          h98bb1dd_1    defaults
watchdog                  2.1.6            py37haa95532_0    defaults
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
webencodings              0.5.1                    py37_1    defaults
werkzeug                  2.2.3                    pypi_0    pypi
whatthepatch              1.0.2            py37haa95532_0    defaults
wheel                     0.38.4           py37haa95532_0    defaults
win_inet_pton             1.1.0            py37haa95532_0    defaults
wincertstore              0.2              py37haa95532_2    defaults
wrapt                     1.14.1           py37h2bbff1b_0    defaults
xz                        5.4.6                h8cc25b3_1    defaults
yaml                      0.2.5                he774522_0    defaults
yapf                      0.31.0             pyhd3eb1b0_0    defaults
zeromq                    4.3.4                hd77b12b_0    defaults
zipp                      3.11.0           py37haa95532_0    defaults
zlib                      1.2.13               h8cc25b3_1    defaults
zstd                      1.5.6                h8880b57_0    defaults

```
</details>

**Comment by ccordoba12** [comment]
Closing as a duplicate of #23306.
