### ISSUE TITLE
upgraded spyder to new version 

### ISSUE THREAD

**Issue by ShrinivasIyer** [spyder-ide/spyder#23300]
### What steps will reproduce the problem?

upgraded spyder to new version since then this error message pops up. Also I cannot see the console.

### Traceback
```python-traceback

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\user\anaconda3\lib\site-packages\spyder\plugins\application\container.py", line 234, in _compute_dependencies
    dependencies.declare_dependencies()
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\dependencies.py", line 485, in declare_dependencies
    add(dep['modname'], dep['package_name'],
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\dependencies.py", line 416, in add
    DEPENDENCIES += [Dependency(modname, package_name, features,
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\dependencies.py", line 355, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\utils\programs.py", line 1004, in get_module_version
    mod = __import__(module_name)
  File "C:\Users\user\anaconda3\lib\site-packages\matplotlib\__init__.py", line 144, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:\Users\user\anaconda3\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Users\user\anaconda3\lib\site-packages\matplotlib\colors.py", line 56, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "C:\Users\user\anaconda3\lib\site-packages\matplotlib\scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "C:\Users\user\anaconda3\lib\site-packages\matplotlib\ticker.py", line 138, in <module>
    from matplotlib import transforms as mtransforms
  File "C:\Users\user\anaconda3\lib\site-packages\matplotlib\transforms.py", line 49, in <module>
    from matplotlib._path import (
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\user\anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\start.py", line 286, in main
    mainwindow.main(options, args)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1425, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\utils.py", line 412, in create_window
    app.exec_()
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\plugins\application\container.py", line 221, in _set_dependencies
    self.dependencies_dialog.set_data(dependencies.DEPENDENCIES)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\widgets\dependencies.py", line 182, in set_data
    self.treewidget.update_dependencies(dependencies)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\widgets\dependencies.py", line 63, in update_dependencies
    if dependency.check():
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\dependencies.py", line 376, in check
    installed = programs.is_module_installed(
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\utils\programs.py", line 1050, in is_module_installed
    module_version = get_module_version(module_name)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\utils\programs.py", line 1004, in get_module_version
    mod = __import__(module_name)
  File "C:\Users\user\anaconda3\lib\site-packages\matplotlib\__init__.py", line 144, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:\Users\user\anaconda3\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Users\user\anaconda3\lib\site-packages\matplotlib\colors.py", line 56, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "C:\Users\user\anaconda3\lib\site-packages\matplotlib\scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "C:\Users\user\anaconda3\lib\site-packages\matplotlib\ticker.py", line 138, in <module>
    from matplotlib import transforms as mtransforms
  File "C:\Users\user\anaconda3\lib\site-packages\matplotlib\transforms.py", line 49, in <module>
    from matplotlib._path import (
AttributeError: _ARRAY_API not found
```

## Versions

* Spyder version: 6.0.1  (conda)
* Python version: 3.10.9 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.22631-SP0

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.10.5 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.17.0 (OK)
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
github >=2.3.0                   :  2.4.0 (OK)
importlib_metadata >=4.6.0       :  8.5.0 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.27.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.2 (OK)
jellyfish >=0.7                  :  1.0.1 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  24.3.1 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.7.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.0 (OK)
pygments >=2.0                   :  2.15.1 (OK)
pylint >=3.1,<4                  :  3.2.7 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0         :  5.6.0 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.0.1 (OK)
setuptools >=49.6.0              :  68.2.2 (OK)
sphinx >=0.6.6                   :  7.3.7 (OK)
spyder_kernels >=3.0.0,<3.1.0    :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.0 (OK)
yarl >=1.9.4                     :  1.18.0 (OK)
zmq >=24.0.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  None (NOK)
numpy >=1.7                      :  2.1.3 (OK)
pandas >=1.1.1                   :  2.2.3 (OK)
scipy >=0.17.0                   :  1.11.1 (OK)
sympy >=0.7.3                    :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @ShrinivasIyer, thanks for reporting. This problem is caused by installing Numpy, or a package that depends on it, with pip in a conda environment. Since pip and conda packages are binary incompatible, they can't be mixed in the same environment.

To solve it, I'm afraid you'll have to remove and reinstall Anaconda. And to properly do that, please follow the instructions in the second part of [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) about that (the first part describes in more detail why you can't mix pip and conda packages).

**Comment by ShrinivasIyer** [comment]
i just did this and it worked later. No need to uninstall complete anaconda. That would have been a huge set back.

conda install "numpy<2"
uninstall spyder 
reinstall spyder
restart system
