### ISSUE TITLE
unknown spyder issue

### ISSUE THREAD

**Issue by hamedmh** [spyder-ide/spyder#23329]
### What steps will reproduce the problem?

I do not know why spyder says that there is an issue.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/hamed/anaconda3/envs/tf_pt/lib/python3.11/site-packages/spyder/plugins/run/container.py", line 214, in run_file
    self.edit_run_configurations(
  File "/home/hamed/anaconda3/envs/tf_pt/lib/python3.11/site-packages/spyder/plugins/run/container.py", line 232, in edit_run_configurations
    self.dialog.setup()
  File "/home/hamed/anaconda3/envs/tf_pt/lib/python3.11/site-packages/spyder/plugins/run/widgets.py", line 746, in setup
    self.run_conf_model.get_initial_index())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hamed/anaconda3/envs/tf_pt/lib/python3.11/site-packages/spyder/plugins/run/models.py", line 192, in get_initial_index
    return self.inverted_index[self.current_configuration]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: None
```

## Versions

* Spyder version: 6.0.1  (conda)
* Python version: 3.11.9 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Linux-6.8.0-51-generic-x86_64-with-glibc2.39

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.10.5 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.17.0 (OK)
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  2.2.1 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
github >=2.3.0                   :  2.4.0 (OK)
importlib_metadata >=4.6.0       :  7.0.1 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.25.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.18.1 (OK)
jellyfish >=0.7                  :  1.0.1 (OK)
jsonschema >=3.2.0               :  4.19.2 (OK)
keyring >=17.0.0                 :  24.3.1 (OK)
nbconvert >=4.0                  :  7.10.0 (OK)
numpydoc >=0.6.0                 :  1.7.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.0 (OK)
pygments >=2.0                   :  2.15.1 (OK)
pylint >=3.1,<4                  :  3.2.7 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0         :  5.6.0 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.0.1 (OK)
setuptools >=49.6.0              :  69.5.1 (OK)
sphinx >=0.6.6                   :  7.3.7 (OK)
spyder_kernels >=3.0.0,<3.1.0    :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.2.1 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.1 (OK)
xdg >=0.26                       :  0.27 (OK)
yarl >=1.9.4                     :  1.11.0 (OK)
zmq >=24.0.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  3.9.2 (OK)
numpy >=1.7                      :  1.24.3 (OK)
pandas >=1.1.1                   :  2.2.2 (OK)
scipy >=0.17.0                   :  1.14.1 (OK)
sympy >=0.7.3                    :  1.12.1 (OK)
```

**Comment by dalthviz** [comment]
Hi @hamedmh thank you for the report! I think this could be a duplicate of https://github.com/spyder-ide/spyder/issues/22607 A fix for that issue was done over PR https://github.com/spyder-ide/spyder/pull/22819 and it is part of the latest Spyder version ( 6.0.3). Not totally sure if you are using Spyder from the default conda channel but for the moment the latest version is only available thorugh the conda-forge channel (as a conda package). If you want to check the latest version I would suggest to create a new conda environment that only uses conda-forge packages.

Let us know if the info above helps!

**Comment by dalthviz** [comment]
Closing as a duplicate of https://github.com/spyder-ide/spyder/issues/22607
