### ISSUE TITLE
Remote connections error with `Key file` authentication method

### ISSUE THREAD

**Issue by miv2004** [spyder-ide/spyder#23375]
### What steps will reproduce the problem?

Tools > Manage remote connections... > New connection > Authentication method: Key file

When trying to establish a remote connection using a Key file and the corresponding Passphrase I get this error. Other than the "Issue reporter" pop-up in the "Connection status" tab "Status: Connecting...", in the "Connection messages" instead of an error there is only "Info: Opening SSH connection — TIMESTAMP" it doesnt appear to change even after some time.

I have tried to change Key file and Passphrase without success.

### Traceback
```python-traceback
exception calling callback for <Future at 0x1c1b048ffd0 state=finished raised TypeError>
Traceback (most recent call last):
  File "C:\Users\manue\AppData\Local\spyder-6\envs\spyder-runtime\Lib\concurrent\futures\_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "C:\Users\manue\AppData\Local\spyder-6\envs\spyder-runtime\Lib\site-packages\spyder\api\asyncdispatcher.py", line 128, in _callback_task_done
    raise exception
  File "C:\Users\manue\AppData\Local\spyder-6\envs\spyder-runtime\Lib\site-packages\spyder\plugins\remoteclient\plugin.py", line 195, in start_remote_server
    await client.connect_and_ensure_server()
  File "C:\Users\manue\AppData\Local\spyder-6\envs\spyder-runtime\Lib\site-packages\spyder\plugins\remoteclient\api\client.py", line 288, in connect_and_ensure_server
    if await self.create_new_connection() and not self.server_started:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manue\AppData\Local\spyder-6\envs\spyder-runtime\Lib\site-packages\spyder\plugins\remoteclient\api\client.py", line 525, in create_new_connection
    if await self.__create_new_connection():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manue\AppData\Local\spyder-6\envs\spyder-runtime\Lib\site-packages\spyder\plugins\remoteclient\api\client.py", line 566, in __create_new_connection
    self._ssh_connection = await asyncssh.connect(
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manue\AppData\Local\spyder-6\envs\spyder-runtime\Lib\site-packages\asyncssh\connection.py", line 8861, in connect
    new_options = await SSHClientConnectionOptions.construct(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manue\AppData\Local\spyder-6\envs\spyder-runtime\Lib\site-packages\asyncssh\connection.py", line 7132, in construct
    return cast(_Options, await loop.run_in_executor(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manue\AppData\Local\spyder-6\envs\spyder-runtime\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manue\AppData\Local\spyder-6\envs\spyder-runtime\Lib\site-packages\asyncssh\connection.py", line 7123, in __init__
    super().__init__(options=options, last_config=last_config, **kwargs)
  File "C:\Users\manue\AppData\Local\spyder-6\envs\spyder-runtime\Lib\site-packages\asyncssh\misc.py", line 454, in __init__
    self.prepare(**self.kwargs)
TypeError: SSHClientConnectionOptions.prepare() got an unexpected keyword argument 'passpharse'
```

## Versions

* Spyder version: 6.0.3  (standalone)
* Python version: 3.11.10 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.11.10 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.18.0 (OK)
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.1.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20241021 (OK)
github >=2.3.0                   :  2.5.0 (OK)
importlib_metadata >=4.6.0       :  8.5.0 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.30.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.2 (OK)
jellyfish >=0.7                  :  1.1.2 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  25.5.0 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.8.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  6.1.0 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.3.2 (OK)
pylint_venv >=3.0.2              :  3.0.4 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.4 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.1,<5.7.0         :  5.6.1 (OK)
qtpy >=2.4.0                     :  2.4.2 (OK)
rtree >=0.9.7                    :  1.3.0 (OK)
setuptools >=49.6.0              :  75.6.0 (OK)
sphinx >=0.6.6                   :  8.1.3 (OK)
spyder_kernels >=3.0.2,<3.1.0    :  3.0.2 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  6.0.0 (OK)
yarl >=1.9.4                     :  1.18.3 (OK)
zmq >=24.0.0                     :  26.2.0 (OK)

# Optional:
cython >=0.21                    :  3.0.11 (OK)
matplotlib >=3.0.0               :  3.9.3 (OK)
numpy >=1.7                      :  2.2.0 (OK)
pandas >=1.1.1                   :  2.2.3 (OK)
scipy >=0.17.0                   :  1.14.1 (OK)
sympy >=0.7.3                    :  1.13.3 (OK)
```

**Comment by dalthviz** [comment]
Hi @miv2004 thank you for the feedback! Will try to give this a check in a future release! Pinging @ccordoba12 just in case

**Comment by ccordoba12** [comment]
It seems `passphrase` is not the right argument to pass to the asyncssh constructor.

**Comment by CULTofBEETROOT** [comment]
Hi both, what a honor to share this with you.
A true beginner I humbly present a possible hint: 

AsyncSSH front webpage states: 

Server host key checking can be disabled by setting the known_hosts argument to None, but that’s not recommended as it makes the connection vulnerable to a man-in-the-middle attack.

To log in as a different remote user, the username argument can be provided:

    async with asyncssh.connect('localhost', username='user123') as conn:

To use a different set of client keys for authentication, they can be provided in the client_keys argument:

    async with asyncssh.connect('localhost', client_keys=['my_ssh_key']) as conn:

Password authentication can be used by providing a password argument:

    async with asyncssh.connect('localhost', password='secretpw') as conn:


...and this higly support ccordoba12's intuition and I suggest:

On the spyder interface there is a doubt as to what precisely the form is requesting called passphrase:
+ are we talking about git login passphrase?
+ are we on the opposite talking about security key protection passphrase?

both should be required and yet we can't match THEM to asyncSSH because asyncSSH is offering the "Password" argument only for ssh (USER) authentication, plus this being in ALTERNATIVE or ADDITION to the security key autentication. 

Most novice users like I must missunderstand (unprecise Spyder interface wording) that a remote git on a self-hosted like, server, is not also allowing github or gitlab remote ssh connections.
This form must precise, from my guess, that it cannot yet be used for online account connections.


I hope to have stolen only a minute of your time and take the opportunity to express my gratitude.

**Comment by ccordoba12** [comment]
Hey @CULTofBEETROOT, thanks for chiming in! You said:

> To use a different set of client keys for authentication, they can be provided in the client_keys argument:

That seems the argument we need to pass to the asyncssh constructor. Thanks for pointing it out.

> On the spyder interface there is a doubt as to what precisely the form is requesting called passphrase

We're requesting what you called the "security key protection passphrase" (the git passphrase is not required for SSH connections).

> Most novice users like I must missunderstand (unprecise Spyder interface wording) that a remote git on a self-hosted like, server, is not also allowing github or gitlab remote ssh connections.

It seems you don't understand very well how this functionality works (and that's not entirely our fault). It's not about allowing users to work with remote Git servers, but to create an IPython console connected to a kernel started in remote machine, as mentioned in the main tooltip of that dialog:

![Image](https://github.com/user-attachments/assets/d4d2fa43-30ad-4655-be09-3d67d01d5737)

The Git SSH support you're referring to simply allows users to push without requesting user and password/token to Github/Gitlab. And that's a totally different thing.

But we could be more specific about what the Passphrase field in that dialog refers to.

**Comment by ccordoba12** [comment]
I found the error: there's a typo in the option name we're trying to pass to Asyncssh. What we have right now is `passpharse` and it should be (of course) `passphrase`.

We'll fix this in 6.0.6, to be released in a couple of months, because it also requires to add a new dependency (`bcrypt`) so that Asyncssh can decrypt the passphrase.

Sorry for the inconvenience @miv2004, we didn't have time to properly test this before releasing 6.0.

**Comment by ccordoba12** [comment]
The only workaround is to manually apply the changes in PR #24086 and install the `bcrypt` package.
