### ISSUE TITLE
Code completion raise exception when the editor widget is floating

### ISSUE THREAD

**Issue by cheneave** [spyder-ide/spyder#2404]
I'm using dual monitor and the editor widget is floating so I can put it in another monitor.
When the editor widget is floating, the code completion  will raise an exception

    Traceback (most recent call last):
    File "d:\spyder\spyderlib\utils\introspection\plugin_manager.py", line 402, in _introspection_complete
      self._handle_pending()
    File "d:\spyder\spyderlib\utils\introspection\plugin_manager.py", line 356, in _handle_pending
      self._post_message('')
    File "d:\spyder\spyderlib\utils\introspection\plugin_manager.py", line 480, in _post_message
        try:
    AttributeError: 'SpyderDockWidget' object has no attribute 'statusBar'

**Comment by ccordoba12** [comment]
@cheneave, we just committed a fix for the problem you reported, but when the Editor is undocked, the completion widget is not shown above it. That is an old bug we don't know how to fix.

So the solution to use the Editor in another screen is **not** to undock it, but to generate a new Editor window. This can be done by clicking the Editor options menu (the one to the right of all tabs), and selecting the option called *New window*.

**Comment by cheneave** [comment]
Thank you, It works.
