### ISSUE TITLE
Exception on autocomplete in the internal console

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#2408]
## Description

* *What steps will reproduce the problem?*

1. Press `Ctrl+Esc` in the internal console without any text

* *What is the expected output? What do you see instead?*
This traceback shows up:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/spyderlib/widgets/internalshell.py", line 348, in keyPressEvent
    self.postprocess_keyevent(event)
  File "/usr/lib/python3.4/site-packages/spyderlib/widgets/shell.py", line 744, in postprocess_keyevent
    ShellBaseWidget.postprocess_keyevent(self, event)
  File "/usr/lib/python3.4/site-packages/spyderlib/widgets/shell.py", line 375, in postprocess_keyevent
    self._key_ctrl_space()
  File "/usr/lib/python3.4/site-packages/spyderlib/widgets/shell.py", line 781, in _key_ctrl_space
    self.show_code_completion(automatic=False)
  File "/usr/lib/python3.4/site-packages/spyderlib/widgets/shell.py", line 909, in show_code_completion
    obj_dir = self.get_dir(last_obj)
  File "/usr/lib/python3.4/site-packages/spyderlib/widgets/internalshell.py", line 419, in get_dir
    obj, valid = self._eval(objtxt)
  File "/usr/lib/python3.4/site-packages/spyderlib/widgets/internalshell.py", line 415, in _eval
    return self.interpreter.eval(text)
  File "/usr/lib/python3.4/site-packages/spyderlib/interpreter.py", line 305, in eval
    assert is_text_string(text)
AssertionError
```

* *Please provide any additional information below*

## Version and main components

* Spyder Version:  3.0.0dev 
* Python Version:  3.4.3
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Linux

## Optional dependencies

pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=3.0   :  3.1.0 (OK)
zmq >=13.0.0    :  14.5.0 (OK)
pandas >=0.13.1 :  0.16.0 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  None (NOK)
pylint >=0.25   :  1.4.3 (OK)

**Comment by ccordoba12** [comment]
@Nodd, what is `Ctrl+Esc` supposed to do?

Also, I can't reproduce this error :-)

**Comment by Nodd** [comment]
It's a typo for `Ctrl+Space` (autocompletion), sorry.
