### ISSUE TITLE
External consoles have startup errors

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#242]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2010-06-24T17:35:04Z_

What steps will reproduce the problem?

 1. Open Spyder
2. Launch an IPython or Python external console. What is the expected output? What do you see instead? Expected error free launch. 

Here is the startup trace from an IPython external console:

'import site' failed; use -v for traceback
\------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\spyderlib\widgets\externalshell\startup.py", line 75, in \<module>
    __ipythonshell__ = IPython.Shell.start()
  File "C:\Python26\lib\site-packages\IPython\Shell.py", line 1241, in start
    return shell(user_ns = user_ns)
  File "C:\Python26\lib\site-packages\IPython\Shell.py", line 1126, in __init__
    shell_class=MatplotlibMTShell)
  File "C:\Python26\lib\site-packages\IPython\Shell.py", line 870, in __init__
    on_kill=[self.wxexit])
  File "C:\Python26\lib\site-packages\IPython\ipmaker.py", line 104, in make_IPython
    from site import _Helper
  File "C:\Python26\lib\site.py", line 513, in \<module>
    main()
  File "C:\Python26\lib\site.py", line 504, in main
    execsitecustomize()
  File "C:\Python26\lib\site.py", line 472, in execsitecustomize
    import sitecustomize
  File "C:\Python26\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 9, in \<module>
    win32console.SetConsoleCP(_cp)
error: (6, 'SetConsoleCP', 'The handle is invalid.')

Python external consoles have an import error at startup, too:

Python 2.6.2 ( r262 :71605, Apr 14 2009, 22:40:02) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license" for more information.
'import site' failed; use -v for traceback
\>>> What version of the product are you using? On what operating system? Spyder 1.1.0, Python 2.6 on XP 

Please provide any additional information below

. This was not an issue in the previous release candidate. I suspect changeset 3b3e417407d8 is the culprit.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=242_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-06-25T01:10:16Z_

Could you please add a "print _cp" just before line 9 in "C:\Python26\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py"?

**Status:** Accepted

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2010-06-25T07:40:14Z_

Done. Here are the new error traces.

IPython External Console:

1252
'import site' failed; use -v for traceback
1252
\------------------------------------------------------------
Traceback (most recent call last):
  File "C:\\Python26\\lib\\site-packages\\spyderlib\\widgets\\externalshell\\startup.py", line 75, in \<module>
    __ipythonshell__ = IPython.Shell.start()
  File "C:\Python26\lib\site-packages\IPython\Shell.py", line 1241, in start
    return shell(user_ns = user_ns)
  File "C:\Python26\lib\site-packages\IPython\Shell.py", line 1126, in __init__
    shell_class=MatplotlibMTShell)
  File "C:\Python26\lib\site-packages\IPython\Shell.py", line 870, in __init__
    on_kill=[self.wxexit])
  File "C:\Python26\lib\site-packages\IPython\ipmaker.py", line 104, in make_IPython
    from site import _Helper
  File "C:\Python26\lib\site.py", line 513, in \<module>
    main()
  File "C:\Python26\lib\site.py", line 504, in main
    execsitecustomize()
  File "C:\Python26\lib\site.py", line 472, in execsitecustomize
    import sitecustomize
  File "C:\Python26\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 10, in \<module>
    win32console.SetConsoleCP(_cp)
error: (6, 'SetConsoleCP', 'The handle is invalid.')


Python External Console:

1252
Python 2.6.2 ( r262 :71605, Apr 14 2009, 22:40:02) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license" for more information.
'import site' failed; use -v for traceback
\>>>

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-06-25T09:56:52Z_

Fixed here: https://code.google.com/p/spyderlib/source/detail?r=97f352324825da89ddbd5f16f0c847046f867dcb&repo=v11

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-06-25T09:57:57Z_

issue #244 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [grosser....@googlemail.com](https://code.google.com/u/113541239102293836474/) on 2010-06-25T10:02:16Z_

Could this be released as hotfix package (1.1.1) over the week-end? I would like to use spyder together with IPython in an internal seminar on monday, and a bug-fixed version that is easy to install for the participants would be awesome.

Thanks!

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-06-25T10:05:18Z_

This is already available ;)

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2010-06-25T10:10:53Z_

Downloaded version 1.1.1, Python 2.6, Windows XP. Looks like it's fixed.

**Comment by spyder-issues-migrator** [comment]
_From [eryksun](https://code.google.com/u/eryksun/) on 2010-06-29T02:24:21Z_

This fix causes an error on non-Windows systems. You can't try to import "pwintypes" and attempt to catch "pywintypes.error" (line 10 of sitecustomize.py). It yields a NameError.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-06-29T04:34:11Z_

Damn, I'm an idiot...
Fixed and will be part of forthcoming v1.1.2: https://code.google.com/p/spyderlib/source/detail?r=262c2f4d9d8613bb5339d2a250fcca78c7ae0313&repo=v11
