### ISSUE TITLE
Left Parenthesis in Ipython console result in kernel closing

### ISSUE THREAD

**Issue by bo92wen** [spyder-ide/spyder#2429]
## Description

* *What steps will reproduce the problem?*
1.Open the Spyder
2.Type in a left parenthesis( '(' ) in the IPython console

* *What is the expected output? What do you see instead?*
I expected to see a left parenthesis shown in the IPython console. I jumped to the internal console immediately and see the following information:

>ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/zmq/eventloop/zmqstream.py", line 407, in _run_callback
  File "/Library/Python/2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/IPython/kernel/threaded.py", line 88, in _handle_recv
  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/IPython/kernel/zmq/session.py", line 848, in deserialize
  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/IPython/kernel/adapter.py", line 367, in adapt
  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/IPython/kernel/adapter.py", line 70, in __call__
  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/IPython/kernel/adapter.py", line 295, in inspect_reply
KeyError: 'oname'
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/zmq/eventloop/zmqstream.py", line 433, in _handle_events
  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/zmq/eventloop/zmqstream.py", line 407, in _run_callback
  File "/Library/Python/2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/IPython/kernel/threaded.py", line 88, in _handle_recv
  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/IPython/kernel/zmq/session.py", line 848, in deserialize
  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/IPython/kernel/adapter.py", line 367, in adapt
  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/IPython/kernel/adapter.py", line 70, in __call__
  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/IPython/kernel/adapter.py", line 295, in inspect_reply
KeyError: 'oname'
ERROR:tornado.application:Exception in callback None
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado/ioloop.py", line 840, in start
  File "/Library/Python/2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/zmq/eventloop/zmqstream.py", line 433, in _handle_events
  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/zmq/eventloop/zmqstream.py", line 407, in _run_callback
  File "/Library/Python/2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/IPython/kernel/threaded.py", line 88, in _handle_recv
  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/IPython/kernel/zmq/session.py", line 848, in deserialize
  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/IPython/kernel/adapter.py", line 367, in adapt
  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/IPython/kernel/adapter.py", line 70, in __call__
  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/IPython/kernel/adapter.py", line 295, in inspect_reply
KeyError: 'oname'

* *Please provide any additional information below*

Started to have this problem after upgrade Spyder to version 2.3.4.
Having been using Spyder for 9 months, no similar problem happened before this upgrade.

## Version and main components

* Spyder Version:  2.3.4
* Python Version:  2.7.8
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.1 on Darwin

## Optional dependencies

pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.0.0 (OK)
zmq >=2.1.11    :  14.5.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.16.0 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.10.2 (OK)
jedi >=0.8.1    :  None (NOK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  1.4.1 (OK)

**Comment by bilderbuchi** [comment]
sounds similar to #2341

**Comment by ccordoba12** [comment]
@bo92wen, why are lines (on your error report) that start with this?

    /Library/Python/2.7/site-packages

To me this indicates that: a) you're using an external interpreter, and b) there's a mismatch between your IPython versions in your interpreter and the one that comes with the Spyder app.

**Comment by ccordoba12** [comment]
Closing because of lack of further info
