### ISSUE TITLE
property.setter problem / Python 2.5

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#243]
_From [hs.s12...@gmail.com](https://code.google.com/u/108575517440597017558/) on 2010-06-24T21:55:27Z_

What steps will reproduce the problem?

 1. Install spyder-1.1.0_py25.exe
2. Run spyder.py What is the expected output? What do you see instead? Spyder stops with following message.
\-----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python25\Scripts\spyder.py", line 2, in \<module>
    from spyderlib import spyder
  File "C:\Python25\lib\site-packages\spyderlib\spyder.py", line 60, in \<module>

    from spyderlib.plugins.projectexplorer import ProjectExplorer
  File "C:\Python25\lib\site-packages\spyderlib\plugins\projectexplorer.py", line 20, in \<module>
    from spyderlib.widgets.projectexplorer import ProjectExplorerWidget
  File "C:\Python25\lib\site-packages\spyderlib\widgets\projectexplorer.py", line 94, in \<module>
    class Project(object):
  File "C:\Python25\lib\site-packages\spyderlib\widgets\projectexplorer.py", line 119, in Project
    @relative_pythonpath.setter
AttributeError: 'property' object has no attribute 'setter'
----------------------------------------------------------------------- What version of the product are you using? On what operating system? PC1: Windows XP sp3 (x86), python2.5.2
PC2: Windows 7 (x64), python2.5.4 

Please provide any additional information below

. spyder_1.1.0beta5_py25.exe and spyder_1.1.0beta7_py25.exe worked fine.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=243_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-06-25T01:20:36Z_

Damned, this feature (property's attribute "setter") has been introduced in Python 2.6....

I'll fix this as soon as possible.
In the meantime, you may disable the Project Explorer plugin. Edit the file .spyder\.spyder.ini in your Home directory: search for project explorer section, and write "False" instead of True in option "enable".

Thanks for the report.

**Summary:** property.setter problem / Python 2.5  
  **Status:** Accepted  
  **Labels:** -Priority-Medium Priority-HIgh

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-06-25T09:56:23Z_

Fixed here: https://code.google.com/p/spyderlib/source/detail?r=eb25ecd1938e4034a85b7697afbd2ff7e24fa168&repo=v11

**Status:** Fixed
