### ISSUE TITLE
AttributeError: 'module' object has no attribute 'has'

### ISSUE THREAD

**Issue by mcleung** [spyder-ide/spyder#2443]
Hi!

Perhaps someone can give me a hand here. I can not launch Spyder anymore.
I am using Anaconda with Python 2.7.8, Build 0. Spyder version I have is 2.3.4. I am running Windows 8.1 Pro, 32 Bit.

I have iPython-Notebook and iPython-QTConsole installed, version 3.1.0 (Installed through Anaconda)

When I try to run spyder, I get the following error (This was obtained using cmd, and running ''spyder'')
I've also tried to ''spyder --reset'' with no luck.

I can open python without error on cmd
Python 2.7.8 |Anaconda 2.1.0 (32-bit)| (default, Jul  2 2014, 15:13:35) [MSC v.1500 32 bit (Intel)] on win32

```
C:\Anaconda\lib\site-packages\zmq\backend\cffi\__pycache__\_cffi_ext.c:186:20: fatal error: sys/un.h: No such file or directory compilation terminated.
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\spyder-script.py", line 2, in <module>
    start_app.main()
  File "C:\Anaconda\lib\site-packages\spyderlib\start_app.py", line 85, in main
    from spyderlib import spyder
  File "C:\Anaconda\lib\site-packages\spyderlib\spyder.py", line 47, in <module>
    from spyderlib.ipythonconfig import IPYTHON_QT_INSTALLED, SUPPORTED_IPYTHON
  File "C:\Anaconda\lib\site-packages\spyderlib\ipythonconfig.py", line 24, in <module>
    IPYTHON_QT_INSTALLED = is_qtconsole_installed()
  File "C:\Anaconda\lib\site-packages\spyderlib\ipythonconfig.py", line 15, in is_qtconsole_installed
    pyzmq_installed = programs.is_module_installed('zmq')
  File "C:\Anaconda\lib\site-packages\spyderlib\utils\programs.py", line 284, in is_module_installed
    actver = get_module_version(module_name)
  File "C:\Anaconda\lib\site-packages\spyderlib\utils\programs.py", line 230, in get_module_version
    mod = __import__(module_name)
  File "C:\Anaconda\lib\site-packages\zmq\__init__.py", line 49, in <module>
    from zmq import backend
  File "C:\Anaconda\lib\site-packages\zmq\backend\__init__.py", line 41, in <module>
    reraise(*exc_info)
  File "C:\Anaconda\lib\site-packages\zmq\backend\__init__.py", line 29, in <module>
    _ns = select_backend(first)
  File "C:\Anaconda\lib\site-packages\zmq\backend\select.py", line 38, in select_backend
    ns[key] = getattr(mod, key)
AttributeError: 'module' object has no attribute 'has'
```

**Comment by ccordoba12** [comment]
Please close Spyder, the IPython notebook and any other process Python process that can be importing a Python module.

Then run this command

    conda install -f pyzmq

That should fix your problem :-)

**Comment by NK001** [comment]
hey if anyone of you can help me.I am using spyder and opencv .whenever i run my script it shows attribute error: 'module' object has not attribute LoadImage

**Comment by mcleung** [comment]
@NK001 I would start a new issue report.
It would be helpful to provide your entire script and error output.
It looks like you are not calling the LoadImage properly.
