### ISSUE TITLE
RuntimeError: the sip module implements API v7.0 to v7.1 but the PyQt4.Qsci module requires API v6.0

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#245]
_From [nils...@googlemail.com](https://code.google.com/u/106566353379983024643/) on 2010-06-25T12:17:57Z_

What steps will reproduce the problem?

 1.python setup.py install --prefix=$HOME/local 2. 3. What is the expected output? 

What do you see instead?
Traceback (most recent call last):
  File "/home/nwagner/local/bin/spyder", line 5, in \<module>
    pkg_resources.run_script('spyder==2.0alpha1', 'spyder')
  File "/home/nwagner/local/lib64/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/pkg_resources.py", line 448, in run_script
    """Yield distributions for non-duplicate projects in the working set
  File "/home/nwagner/local/lib64/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/pkg_resources.py", line 1166, in run_script
    if os.path.exists(script_filename):
  File "/home/nwagner/local/lib/python2.6/site-packages/spyder-2.0alpha1-py2.6.egg/EGG-INFO/scripts/spyder", line 2, in \<module>
    from spyderlib import spyder
  File "/home/nwagner/local/lib/python2.6/site-packages/spyder-2.0alpha1-py2.6.egg/spyderlib/spyder.py", line 45, in \<module>
    from spyderlib.plugins.console import Console
  File "/home/nwagner/local/lib/python2.6/site-packages/spyder-2.0alpha1-py2.6.egg/spyderlib/plugins/__init__.py", line 34, in \<module>
    from spyderlib.widgets.editor import CodeEditor
  File "/home/nwagner/local/lib/python2.6/site-packages/spyder-2.0alpha1-py2.6.egg/spyderlib/widgets/editor.py", line 41, in \<module>
    from spyderlib.widgets.qscieditor.qscieditor import QsciEditor as CodeEditor
  File "/home/nwagner/local/lib/python2.6/site-packages/spyder-2.0alpha1-py2.6.egg/spyderlib/widgets/qscieditor/qscieditor.py", line 21, in \<module>
    from PyQt4.Qsci import (QsciScintilla, QsciAPIs, QsciLexerCPP, QsciLexerCSS,
RuntimeError: the sip module implements API v7.0 to v7.1 but the PyQt4.Qsci module requires API v6.0

What version of the product are you using? 
changeset:   658:c65331bb6940
tag:         tip
user:        Pierre Raybaut \<pierre.raybaut@gmail.com>
date:        Fri Jun 25 16:59:21 2010 +0200
summary:     Project explorer/ issue #243 : fixed Python 2.5 compatibility issue with property setter decorator

On what operating system?
Linux linux-mogv 2.6.31.12-0.2-default `#1` SMP 2010-03-16 21:25:39 +0100 x86_64 x86_64 x86_64 GNU/Linux 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=245_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-06-25T10:34:55Z_

This is not a Spyder bug.

This issue is related to your Python libraries installation: apparently you have installed a version of QScintilla which is not compatible with your version of PyQt.

This may happen if you have upgraded PyQt without upgrading QScintilla.

**Status:** WontFix
