### ISSUE TITLE
Launching IPython console fails because of errors importing Pandas or Matplotlib

### ISSUE THREAD

**Issue by Linruixp** [spyder-ide/spyder#2456]
## Description

* *What steps will reproduce the problem?*
1. I want to Open an IPython Console, but fails.

* *What is the expected output? What do you see instead?*
The expected output is an open IPython Console, But I get error message like below:

```
An error ocurred while starting the kernel
'import sitecustomize' failed; use ‑v for traceback
Traceback (most recent call last):
File "/Users/LinRui/anaconda/lib/python2.7/site‑packages/spyderlib/widgets/externalshell/start_ipython_kernel.py", line 163, in 
ipk_temp.config = kernel_config()
File "/Users/LinRui/anaconda/lib/python2.7/site‑packages/spyderlib/widgets/externalshell/start_ipython_kernel.py", line 27, in kernel_config
from spyderlib.config import CONF
File "/Users/LinRui/anaconda/lib/python2.7/site‑packages/spyderlib/config.py", line 22, in 
from spyderlib.utils import iofuncs, codeanalysis
File "/Users/LinRui/anaconda/lib/python2.7/site‑packages/spyderlib/utils/iofuncs.py", line 26, in 
import pandas as pd
File "/Users/LinRui/anaconda/lib/python2.7/site‑packages/pandas/__init__.py", line 41, in 
from pandas.core.api import *
File "/Users/LinRui/anaconda/lib/python2.7/site‑packages/pandas/core/api.py", line 9, in 
from pandas.core.groupby import Grouper
File "/Users/LinRui/anaconda/lib/python2.7/site‑packages/pandas/core/groupby.py", line 15, in 
from pandas.core.frame import DataFrame
File "/Users/LinRui/anaconda/lib/python2.7/site‑packages/pandas/core/frame.py", line 38, in 
from pandas.core.series import Series
File "/Users/LinRui/anaconda/lib/python2.7/site‑packages/pandas/core/series.py", line 2524, in 
import pandas.tools.plotting as _gfx
File "/Users/LinRui/anaconda/lib/python2.7/site‑packages/pandas/tools/plotting.py", line 26, in 
import pandas.tseries.converter as conv
File "/Users/LinRui/anaconda/lib/python2.7/site‑packages/pandas/tseries/converter.py", line 7, in 
import matplotlib.units as units
File "/Users/LinRui/anaconda/lib/python2.7/site‑packages/matplotlib/__init__.py", line 1048, in 
rcParams = rc_params()
File "/Users/LinRui/anaconda/lib/python2.7/site‑packages/matplotlib/__init__.py", line 897, in rc_params
fname = matplotlib_fname()
File "/Users/LinRui/anaconda/lib/python2.7/site‑packages/matplotlib/__init__.py", line 748, in matplotlib_fname
fname = os.path.join(os.getcwd(), 'matplotlibrc')
File "/Users/LinRui/anaconda/lib/python2.7/posixpath.py", line 80, in join
path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 24: ordinal not in range(128)
```

* *Please provide any additional information below*

## Version and main components

* Spyder Version:  2.3.4
* Python Version:  2.7.9
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Darwin

## Optional dependencies

pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.1.0 (OK)
zmq >=2.1.11    :  14.5.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.1.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.0 (OK)
sympy >=0.7.3   :  0.7.5 (OK)
pylint >=0.25   :  None (NOK)

**Comment by ccordoba12** [comment]
Thanks for reporting.This will be fixed in our next version.
