### ISSUE TITLE
Spyder 2.0alpha1 - Error in IPython shell on startup

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#248]
_From [koverholt](https://code.google.com/u/koverholt/) on 2010-06-30T16:40:11Z_

What version of the product are you using? On what operating system? Spyder 2.0alpha1
Mac OS X 10.6.4, Python 2.6.5

Please provide any additional information below

:
Spyder 1.1.2 works fine, this problem seems limited to the IPython shell. I can import IPython.Shell in a separate IPython process just fine. 

What steps will reproduce the problem?

 1. Start spyder normally or with --light option
2. IPython shell shows the following error:

'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "spyderlib/widgets/externalshell/startup.py", line 103, in \<module>
    import IPython.Shell
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/IPython/__init__.py", line 58, in \<module>
    __import__(name,glob,loc,[])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/IPython/ipstruct.py", line 17, in \<module>
    from IPython.genutils import list2dict2
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/IPython/genutils.py", line 114, in \<module>
    import IPython.rlineimpl as readline
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/IPython/rlineimpl.py", line 36, in \<module>
    (status, result) = commands.getstatusoutput( "otool -L &#37;s | grep libedit" &#37; _rl.__file__ )
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/commands.py", line 56, in getstatusoutput
    text = pipe.read()
IOError: [Errno 4] Interrupted system call

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=248_

**Comment by spyder-issues-migrator** [comment]
_From [koverholt](https://code.google.com/u/koverholt/) on 2010-07-10T22:11:26Z_

Something in the recent commits has fixed this, it now works on OS X and IPython starts fine in Spyder. Thanks for the hard work!

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-07-12T01:24:29Z_

Perfect!

I think this commit has fixed your problem (Matplotlib's patch was applied systematically): https://code.google.com/p/spyderlib/source/detail?r=5e61a29085ef378db1063cf130543f5cf2027d4c

**Status:** Fixed
