### ISSUE TITLE
Spyder 2.3.5.2 Mac, Preferences window does not open

### ISSUE THREAD

**Issue by markushartmann** [spyder-ide/spyder#2516]
Hello, 

up to now I used Spyder 2.2.5 on my Mac with Yosemite, I like to update to Spyder 2.3.5.2.. In the new version when I try to open the preference window this error occurs:

    >> Traceback (most recent call last):
    File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/spyderlib/spyder.py", line     2005, in edit_preferences
      widget.initialize()
    File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/spyderlib/plugins/configdialog.py", line 59, in initialize
      self.setup_page()
    File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/spyderlib/plugins/shortcuts.py", line 338, in setup_page
      self.table = ShortcutsTable(self)
    File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/spyderlib/plugins/shortcuts.py", line 287, in __init__
      self.load_shortcuts()
    File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/spyderlib/plugins/shortcuts.py", line 297, in load_shortcuts
      shortcut = Shortcut(context, name, keystr)
    File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/spyderlib/plugins/shortcuts.py", line 110, in __init__
      key = keystr2key(key)
    File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/spyderlib/plugins/shortcuts.py", line 103, in keystr2key
      return Key(Key.key_from_str(keylist[-1]), *mods)
    File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/spyderlib/plugins/shortcuts.py", line 63, in __init__
      assert all([mod in self.MODIFIERS for mod in modifiers])
     AssertionError

I think the wrong interpreter is used because when I open a new python console in the newer version it shows

    Python 2.7.10 (default, Jun  1 2015, 09:45:55) 
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.

in the older version it shows

    Python 2.7.5 (default, Jul 13 2013, 20:37:32) 
    [GCC 4.2.1 Compatible Apple Clang 3.1 (tags/Apple/clang-318.0.61)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    
    Imported NumPy 1.7.1, SciPy 0.12.0, Matplotlib 1.3.0
    
    Type "scientific" for more details.
    >>> 

Or do I search in a wrong way, any ideas? 

Thanks

Regards Markus

**Comment by ccordoba12** [comment]
Please run

    rm -R ~/.spyder2

in a terminal and try again.

**Comment by markushartmann** [comment]
Thank you very very much, thats it, not sure how many hours I searched for this error.

**Comment by ccordoba12** [comment]
Great! In Spyder 3.0 there's going to be an option to do this from our interface.

**Comment by ccordoba12** [comment]
I mean, a menu entry.
