### ISSUE TITLE
Spyder crashes on startup: PyQt 4.7.4 / Python 2.7

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#253]
_From [charles....@gmail.com](https://code.google.com/u/106742389533905007142/) on 2010-07-21T20:58:54Z_

What steps will reproduce the problem?

 1. open terminal
2. invoke the spyder command What is the expected output? What do you see instead? First time trying to use the product- so not sure what it should look like.  This is what I get:

spyder --debug

Start of MainWindow constructor
Initializing...
End of MainWindow constructor
*** Start of MainWindow setup ***
Loading workspace...
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 1559, in main
    mainwindow = run_spyder(app, commands, intitle, message, options)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 1503, in run_spyder
    main.setup()
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 386, in setup
    self.debug, self.closing, self.profile)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/plugins/console.py", line 54, in __init__
    debug, exitfunc, profile)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/interactiveshell.py", line 113, in __init__
    debug, profile)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/shell.py", line 698, in __init__
    ShellBaseWidget.__init__(self, parent, history_filename, debug, profile)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/shell.py", line 53, in __init__
    ConsoleBaseWidget.__init__(self, parent)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/qteditor/qtebase.py", line 874, in __init__
    TextEditBaseWidget.__init__(self, parent)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/qteditor/qtebase.py", line 160, in __init__
    self.completion_widget = CompletionWidget(self, parent)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/qteditor/qtebase.py", line 40, in __init__
    srect = QApplication.desktop().availableGeometry(self)
TypeError: an integer is required
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/Current/bin/spyder", line 3, in \<module>
    spyder.main()
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 1565, in main
    if mainwindow is None:
UnboundLocalError: local variable 'mainwindow' referenced before assignment What version of the product are you using? On what operating system? spyder 1.1.2 installed via pip

Qt 4.6.3
SIP 4.10.5
PyQt 4.7.4
QScintilla2 2.4.4

NumPy 1.3.0
Matplotlib 1.0.0

Python 2.7

OS X 10.6.4 x86_64 kernel 

Please provide any additional information below

. Tried running with the --reset flag, didn't help anything.

Crash log attached- seems like the application is failing due to a type error when trying to determine the size of a window.

**Attachment:** [spyder_crash.log](http://code.google.com/p/spyderlib/issues/detail?id=253)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=253_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-07-22T01:11:00Z_

Could you please apply the following patch to see if it works for you: https://code.google.com/p/spyderlib/source/diff?spec=svn.v11.56d98673196c0a7fdcce1138bbb0dc49efc236ab&repo=v11&r=56d98673196c0a7fdcce1138bbb0dc49efc236ab&format=side&path=/spyderlib/widgets/qteditor/qtebase.py

**Status:** Accepted

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-07-22T01:25:20Z_

You may try and install v1.1.3 in which patch above is included.

**Comment by spyder-issues-migrator** [comment]
_From [charles....@gmail.com](https://code.google.com/u/106742389533905007142/) on 2010-07-22T01:44:45Z_

Thanks for the help- the patch did something as Spyder now makes it past the "Loading workspace" phase of MainWindow setup.  However, I'm getting another crash:

$spyder --debug

Start of MainWindow constructor
Initializing...
End of MainWindow constructor
*** Start of MainWindow setup ***
Loading workspace...
Loading editor plugin...
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 1559, in main
    mainwindow = run_spyder(app, commands, intitle, message, options)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 1503, in run_spyder
    main.setup()
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 403, in setup
    self.editor = Editor(self)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/plugins/editor.py", line 189, in __init__
    self.__load_temp_file()
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/plugins/editor.py", line 964, in __load_temp_file
    self.load(self.TEMPFILE_PATH)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/plugins/editor.py", line 1111, in load
    editor = editorstack.load(filename, set_current=is_current)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/editor.py", line 1152, in load
    self._refresh_classbrowser(index, update=True)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/editor.py", line 899, in _refresh_classbrowser
    update=update)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/editortools.py", line 548, in set_current_editor
    self.treewidget.set_current_editor(editor, fname, update)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/editortools.py", line 285, in set_current_editor
    root_item = FileRootItem(fname, self)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/editortools.py", line 91, in __init__
    QTreeWidgetItem.__init__(self, treewidget)
TypeError: an integer is required
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/spyder", line 3, in \<module>
    spyder.main()
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 1565, in main
    if mainwindow is None:
UnboundLocalError: local variable 'mainwindow' referenced before assignment
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 922, in closing
    CONF.set('main', prefix+'size', (size.width(), size.height()))
AttributeError: 'NoneType' object has no attribute 'width'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 922, in closing
    CONF.set('main', prefix+'size', (size.width(), size.height()))
AttributeError: 'NoneType' object has no attribute 'width'


Looks like another Type Error in QTreeWidgetItem.__init__(self, treewidget).  Crash log attached.

**Attachment:** [spyder_crash.log](http://code.google.com/p/spyderlib/issues/detail?id=253#hc3)

**Comment by spyder-issues-migrator** [comment]
_From [charles....@gmail.com](https://code.google.com/u/106742389533905007142/) on 2010-07-22T01:45:40Z_

Oh, I should mention that I did not apply the patch directly, I reinstalled using the tarball:

pip install http://spyderlib.googlecode.com/files/spyder-1.1.3.tar.gz

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-07-22T02:03:47Z_

I'm afraid there could be a lot of other bugs like this: I suppose you are one of the first users to test Spyder with Python 2.7 and PyQt 4.7.4.

Could you please try to replace line 91 in "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/editortools.py" by:
    QTreeWidgetItem.__init__(self, treewidget, QTreeWidgetItem.Type)

**Summary:** Spyder crashes on startup: PyQt 4.7.4 / Python 2.7  
  **Labels:** OpSys-OSX

**Comment by spyder-issues-migrator** [comment]
_From [charles....@gmail.com](https://code.google.com/u/106742389533905007142/) on 2010-07-22T12:38:12Z_

Tried your suggestion, and got the same result:


  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/editortools.py", line 91, in __init__
    QTreeWidgetItem.__init__(self, treewidget, QTreeWidgetItem.Type)
TypeError: an integer is required


Full crash log attached.

**Attachment:** [spyder_crash.log](http://code.google.com/p/spyderlib/issues/detail?id=253#hc6)

**Comment by spyder-issues-migrator** [comment]
_From [sherdim](https://code.google.com/u/sherdim/) on 2010-07-28T09:39:59Z_

Spyder crashes together with console on Windows 7 (Vista too), PyQt 4.5.4 / Python 2.6
during import:

from spyderlib import spyder
more exactly on string:
from spyderlib.plugins.inspector import ObjectInspector
in [spyderlib\plugins\inspector.py]:
from spyderlib.widgets.externalshell.pythonshell import ExtPyQsciShell

and may be in other places but all crashes...

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-07-28T12:20:43Z_

Please provide the full traceback.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-07-28T23:00:13Z_

I doubt that this is the same issue as above because Spyder has been widely tested on this configuration which happens to be the same as distributed together with Python(x,y) for almost a year now. 

So could you please provide the full traceback ?
(mentioning the fact tha the error happenhere or there without the full traceback does nothelp)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-08-26T13:50:27Z_

**Status:** Duplicate  
  **Mergedinto:** 317

**Comment by spyder-issues-migrator** [comment]
_From [dweber.c...@gmail.com](https://code.google.com/u/100607128787105116242/) on 2010-08-26T13:52:09Z_

RE Comment 6 above.

I found a hack for line 91 of editortools.py, but this is most likely a disfunctional solution, as it discards __init__ args:
\#QTreeWidgetItem.__init__(self, treewidget)
QTreeWidgetItem.__init__(self)

Perhaps  "def __init__(self, path, treewidget):" could have default values set?  The call to FileRootItem from line 285 doesn't provide all the input values.

I'm also using python2.7, which seems to generate a ton of bugs similar to this one.

Regards,
Darren

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-08-26T14:01:36Z_

The right bugfix should be this:
QTreeWidgetItem.__init__(self, treewidget, QTreeWidgetItem.Type)
