### ISSUE TITLE
Spyder crash on launch with Babel 2.0/Python 3.4

### ISSUE THREAD

**Issue by JGoutin** [spyder-ide/spyder#2566]
Hello,

Babel was updated to 2.0, unfortunately, Spyder crash with this version. I gone back to 1.3 to fix that problem.

spyder_crash.log : 

```
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\spyderlib\spyder.py", line 2336, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Python34\lib\site-packages\spyderlib\spyder.py", line 2220, in run_spyder
    main.setup()
  File "C:\Python34\lib\site-packages\spyderlib\spyder.py", line 766, in setup
    from spyderlib.plugins.inspector import ObjectInspector
  File "C:\Python34\lib\site-packages\spyderlib\plugins\inspector.py", line 47, in <module>
    from spyderlib.utils.inspector.sphinxify import (CSS_PATH, sphinxify,
  File "C:\Python34\lib\site-packages\spyderlib\utils\inspector\sphinxify.py", line 31, in <module>
    from sphinx.application import Sphinx
  File "C:\Python34\lib\site-packages\sphinx\application.py", line 37, in <module>
    from sphinx.builders import BUILTIN_BUILDERS
  File "C:\Python34\lib\site-packages\sphinx\builders\__init__.py", line 23, in <module>
    from sphinx.util import i18n, path_stabilize
  File "C:\Python34\lib\site-packages\sphinx\util\i18n.py", line 15, in <module>
    from babel.messages.pofile import read_po
  File "C:\Python34\lib\site-packages\babel\messages\__init__.py", line 12, in <module>
    from babel.messages.catalog import *
  File "C:\Python34\lib\site-packages\babel\messages\catalog.py", line 23, in <module>
    from babel.dates import format_datetime
  File "C:\Python34\lib\site-packages\babel\dates.py", line 28, in <module>
    from babel.util import UTC, LOCALTZ
  File "C:\Python34\lib\site-packages\babel\util.py", line 278, in <module>
    from babel import localtime
  File "C:\Python34\lib\site-packages\babel\localtime\__init__.py", line 21, in <module>
    from babel.localtime._win32 import _get_localzone
  File "C:\Python34\lib\site-packages\babel\localtime\_win32.py", line 18, in <module>
    tz_names = get_global('windows_zone_mapping')
  File "C:\Python34\lib\site-packages\babel\core.py", line 58, in get_global
    _global_data = pickle.load(fileobj)
TypeError: an integer is required (got type str)
```

**Comment by ccordoba12** [comment]
Thanks for reporting, we'll try to fix it ASAP :-)

**Comment by ccordoba12** [comment]
I can confirm the error, but it seems a problem with `babel`, not with Spyder, at least according to

http://stackoverflow.com/questions/31708355/python-flask-typeerror-an-integer-is-required-got-type-str

**Comment by jrminter** [comment]
I confirm the problem and the fix listed above did not work

**Comment by jrminter** [comment]
The problem is indeed with Babel. I ended up downloading babel from github and building from source. Then I build spyder from github. all works now.

**Comment by ccordoba12** [comment]
Yes, the solution is really to downgrade to babel 1.3

**Comment by stonebig** [comment]
Hi. I'm not sure. Is Babel 2.0 ok and functional with Spyder under Python 3.4 now ?

**Comment by ccordoba12** [comment]
If a `TypeError` is generated by Babel, then the Rich mode of the Object Inspector is deactivated.

The advantage is to avoid a crash at Spyder startup.

**Comment by stonebig** [comment]
ok. It looks better to stay on Babel 1.3, for Python 3.4 users.
