### ISSUE TITLE
Spyder is crashing with PyQt5.5.0 on Windows / Python 3.4

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#2573]
Hi dear Spyder team,

When I try to start Spyder 3.0.0dev of this morning :
- first time is ok,
- second time I get a crash, which requires a spyder --reset.

Any idea if it's me/Pyqt5/spyder problem ?

````
Traceback (most recent call last):
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\spyderlib\spyder.py", line 3180, in main
    mainwindow = run_spyder(app, options, args)
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\spyderlib\spyder.py", line 3066, in run_spyder
    main.setup()
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\spyderlib\spyder.py", line 846, in setup
    self.editor = Editor(self)
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\spyderlib\plugins\editor.py", line 462, in __init__
    self.splitter.restoreState( QByteArray().fromHex(str(state)) )
TypeError: QByteArray.fromHex(QByteArray): argument 1 has unexpected type 'str'
````
A wild guess seems maybe when I close spyder something doesn't close/cleanup: the "restart" option fails too

**Comment by ccordoba12** [comment]
No idea what can be happening here. Any ideas @goanpeca?

@stonebig, if it was working before, could you use `git bisect` ot `git blame` to detect the faulty commit?

**Comment by goanpeca** [comment]
Hmmmm, maybe it is a Qt5 issue, @ccordoba12 can you check on python 3.4 with Qt5 ?

**Comment by stonebig** [comment]
hi again,

Apparently, I have no issue when downgrading to PyQt5.4.1. So the issue seems related to PyQt5.5.0, but I'm not expert enough even to fomulate the issue on PyQt Mailing list.

**Comment by goanpeca** [comment]
@stonebig, I think we can tackle the issue with the info you provide :-)

Cheers

**Comment by stonebig** [comment]
My two wired bugs are suddenly gone when I downgrade to PyQt5.4.1 https://github.com/winpython/winpython/issues/34#issuecomment-126021578

**Comment by stonebig** [comment]
update: rechecking myself, maybe I used the July 22nd tree for my test and not July 30th.

**Comment by ccordoba12** [comment]
So master on July 30th is working fine?

**Comment by stonebig** [comment]
I didn't try that yet, as in the mean time I found that only PyQt5.4.1 was fixing my others issues.

**Comment by stonebig** [comment]
ok, it's still crashing with July 30th, but differently (maybe my fault ?):
````
Traceback (most recent call last):
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\spyderlib\spyder.py", line 3182, in main
    mainwindow = run_spyder(app, options, args)
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\spyderlib\spyder.py", line 3068, in run_spyder
    main.setup()
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\spyderlib\spyder.py", line 830, in setup
    from spyderlib.plugins.inspector import ObjectInspector
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\spyderlib\plugins\inspector.py", line 49, in <module>
    from spyderlib.utils.inspector.sphinxify import (CSS_PATH, sphinxify,
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\spyderlib\utils\inspector\sphinxify.py", line 32, in <module>
    from sphinx.application import Sphinx
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\sphinx\application.py", line 37, in <module>
    from sphinx.builders import BUILTIN_BUILDERS
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\sphinx\builders\__init__.py", line 23, in <module>
    from sphinx.util import i18n, path_stabilize
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\sphinx\util\i18n.py", line 15, in <module>
    from babel.messages.pofile import read_po
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\babel\messages\__init__.py", line 12, in <module>
    from babel.messages.catalog import *
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\babel\messages\catalog.py", line 23, in <module>
    from babel.dates import format_datetime
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\babel\dates.py", line 28, in <module>
    from babel.util import UTC, LOCALTZ
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\babel\util.py", line 278, in <module>
    from babel import localtime
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\babel\localtime\__init__.py", line 21, in <module>
    from babel.localtime._win32 import _get_localzone
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\babel\localtime\_win32.py", line 18, in <module>
    tz_names = get_global('windows_zone_mapping')
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\babel\core.py", line 58, in get_global
    _global_data = pickle.load(fileobj)
TypeError: an integer is required (got type str)
````

**Comment by stonebig** [comment]
and back to PyQt5.4, I just switched to babel 2.0, and it seems babel 2.0 is causing troubles to Spyder
````
Traceback (most recent call last):
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\spyderlib\spyder.py", line 3182, in main
    mainwindow = run_spyder(app, options, args)
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\spyderlib\spyder.py", line 3068, in run_spyder
    main.setup()
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\spyderlib\spyder.py", line 830, in setup
    from spyderlib.plugins.inspector import ObjectInspector
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\spyderlib\plugins\inspector.py", line 49, in <module>
    from spyderlib.utils.inspector.sphinxify import (CSS_PATH, sphinxify,
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\spyderlib\utils\inspector\sphinxify.py", line 32, in <module>
    from sphinx.application import Sphinx
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\sphinx\application.py", line 37, in <module>
    from sphinx.builders import BUILTIN_BUILDERS
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\sphinx\builders\__init__.py", line 23, in <module>
    from sphinx.util import i18n, path_stabilize
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\sphinx\util\i18n.py", line 15, in <module>
    from babel.messages.pofile import read_po
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\babel\messages\__init__.py", line 12, in <module>
    from babel.messages.catalog import *
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\babel\messages\catalog.py", line 23, in <module>
    from babel.dates import format_datetime
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\babel\dates.py", line 28, in <module>
    from babel.util import UTC, LOCALTZ
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\babel\util.py", line 278, in <module>
    from babel import localtime
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\babel\localtime\__init__.py", line 21, in <module>
    from babel.localtime._win32 import _get_localzone
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\babel\localtime\_win32.py", line 18, in <module>
    tz_names = get_global('windows_zone_mapping')
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.5_build6Qt5.amd64\python-3.4.3.amd64\lib\site-packages\babel\core.py", line 58, in get_global
    _global_data = pickle.load(fileobj)
TypeError: an integer is required (got type str)
````

**Comment by stonebig** [comment]
hi,

Now it looks much more stable on python3.4 64 / windows 7: still no crash after 4 start and stop.
