### ISSUE TITLE
UnboundLocalError: local variable 'prevline' referenced before assignment

### ISSUE THREAD

**Issue by naught101** [spyder-ide/spyder#2600]
Spyder 3.0.0-beta1, on python 3.4, you can check my install via https://binstar.org/naught101/spyder/files

I get this on startup:

```
Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> Traceback (most recent call last):
  File "/home/naught101/miniconda3/envs/science/lib/python3.4/site-packages/spyderlib/widgets/sourcecode/codeeditor.py", line 2643, in keyPressEvent
    self.intelligent_tab()
  File "/home/naught101/miniconda3/envs/science/lib/python3.4/site-packages/spyderlib/widgets/sourcecode/codeeditor.py", line 824, in intelligent_tab
    self.indent_or_replace()
  File "/home/naught101/miniconda3/envs/science/lib/python3.4/site-packages/spyderlib/widgets/sourcecode/codeeditor.py", line 2016, in indent_or_replace
    self.indent()
  File "/home/naught101/miniconda3/envs/science/lib/python3.4/site-packages/spyderlib/widgets/sourcecode/codeeditor.py", line 2002, in indent
    if not self.fix_indent(forward=True):
  File "/home/naught101/miniconda3/envs/science/lib/python3.4/site-packages/spyderlib/widgets/sourcecode/codeeditor.py", line 1906, in fix_indent
    correct_indent = self.get_block_indentation(prevline)
UnboundLocalError: local variable 'prevline' referenced before assignment
```

**Comment by ccordoba12** [comment]
Please try to run

    spyder --reset

and try again. Maybe that helps :-)

**Comment by naught101** [comment]
Yep, that did sort it out, thanks.
