### ISSUE TITLE
ipython update breaks spyder

### ISSUE THREAD

**Issue by thewhitetulip** [spyder-ide/spyder#2616]
/usr/local/lib/python2.7/dist-packages/IPython/qt.py:13: ShimWarning: The `IPython.qt` package has been deprecated. You should import from qtconsole instead.

  "You should import from qtconsole instead.", ShimWarning)

Traceback (most recent call last):
  File "/home/thewhitetulip/code/spyder_work/spyder/spyderlib/spyder.py", line 3103, in main
    mainwindow = run_spyder(app, options, args)

  File "/home/thewhitetulip/code/spyder_work/spyder/spyderlib/spyder.py", line 2989, in run_spyder
    main.setup()

  File "/home/thewhitetulip/code/spyder_work/spyder/spyderlib/spyder.py", line 830, in setup
    from spyderlib.plugins.inspector import ObjectInspector

  File "/home/thewhitetulip/code/spyder_work/spyder/spyderlib/plugins/inspector.py", line 43, in <module>
    from spyderlib.widgets.ipython import IPythonControlWidget

  File "/home/thewhitetulip/code/spyder_work/spyder/spyderlib/widgets/ipython.py", line 29, in 

<module>
    from IPython.qt.console.rich_ipython_widget import RichIPythonWidget
ImportError: No module named rich_ipython_widget

**Comment by ccordoba12** [comment]
You need to install the qtconsole package for Spyder to work, with

    pip install qtconsole

Closing as duplicate of issue #2608, to consolidate everything in one place.
