### ISSUE TITLE
Spyder crashes because of an incomplete psutil installation

### ISSUE THREAD

**Issue by vchollati** [spyder-ide/spyder#2642]
Crash log-
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\spyderlib\spyder.py", line 3103, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Anaconda\lib\site-packages\spyderlib\spyder.py", line 2989, in run_spyder
    main.setup()
  File "C:\Anaconda\lib\site-packages\spyderlib\spyder.py", line 1111, in setup
    self.cpu_status = CPUStatus(self, status)
  File "C:\Anaconda\lib\site-packages\spyderlib\widgets\status.py", line 57, in __init__
    if self.is_supported():
  File "C:\Anaconda\lib\site-packages\spyderlib\widgets\status.py", line 77, in is_supported
    self.import_test()
  File "C:\Anaconda\lib\site-packages\spyderlib\widgets\status.py", line 110, in import_test
    if not programs.is_module_installed('psutil', '>=0.2.0'):
  File "C:\Anaconda\lib\site-packages\spyderlib\utils\programs.py", line 319, in is_module_installed
    actver = get_module_version(module_name)
  File "C:\Anaconda\lib\site-packages\spyderlib\utils\programs.py", line 263, in get_module_version
    mod = __import__(module_name)
  File "C:\Anaconda\lib\site-packages\psutil\__init__.py", line 139, in <module>
    import psutil._pswindows as _psplatform
AttributeError: 'module' object has no attribute '_pswindows'

**Comment by ccordoba12** [comment]
This seems a problem with your installation. Please close Spyder, the IPython notebook, and every other program that uses Python. Then run these commands

    conda install -f conda
    conda install -f psutil
    conda install -f jupyter

That should fix your problem.

**Comment by vchollati** [comment]
first conda install failed with error [WindowsError: [Error 5] Access is denied: u'C:\\Anaconda\\pkgs\\conda-3.16.0-py27_0\\Scripts\\conda.exe'].
next 2 commands succeeded and it works now. Thanks a lot :+1:

**Comment by ccordoba12** [comment]
You're welcome!
