### ISSUE TITLE
IPython console crashes when starting Spyder 2.3.6

### ISSUE THREAD

**Issue by abhayap** [spyder-ide/spyder#2653]
My IPython console crashes after updating my anaconda distribution. This is the error I get:

```python
Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> /Users/abparthy/miniconda3/lib/python3.4/site-packages/IPython/nbformat/current.py:19: UserWarning: IPython.nbformat.current is deprecated.

- use IPython.nbformat for read/write/validate public API
- use IPython.nbformat.vX directly to composing notebooks of a particular version

  """)
Traceback (most recent call last):
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/spyderlib/plugins/ipythonconsole.py", line 656, in toggle_view
    self.create_new_client(give_focus=False)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/spyderlib/plugins/ipythonconsole.py", line 830, in create_new_client
    menu_actions=self.menu_actions)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/spyderlib/widgets/ipython.py", line 407, in __init__
    local_kernel=False)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/spyderlib/widgets/ipython.py", line 175, in __init__
    super(IPythonShellWidget, self).__init__(*args, **kw)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/qtconsole/rich_jupyter_widget.py", line 49, in __init__
    super(RichJupyterWidget, self).__init__(*args, **kw)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/qtconsole/jupyter_widget.py", line 112, in __init__
    super(JupyterWidget, self).__init__(*args, **kw)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/qtconsole/frontend_widget.py", line 153, in __init__
    super(FrontendWidget, self).__init__(*args, **kw)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/qtconsole/history_console_widget.py", line 28, in __init__
    super(HistoryConsoleWidget, self).__init__(*args, **kw)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/qtconsole/console_widget.py", line 211, in __init__
    LoggingConfigurable.__init__(self, **kw)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/traitlets/config/configurable.py", line 85, in __init__
    self.config = config
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/traitlets/traitlets.py", line 450, in __set__
    new_value = self._validate(obj, value)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/traitlets/traitlets.py", line 471, in _validate
    value = self.validate(obj, value)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/traitlets/traitlets.py", line 1045, in validate
    self.error(obj, value)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/traitlets/traitlets.py", line 899, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'config' trait of an IPythonShellWidget instance must be a Config, but a value of class 'IPython.config.loader.Config' (i.e. {'IPythonWidget': {'enable_calltips': True, 'kind': 'rich', 'gui_completion': 'droplist', 'buffer_size': 500, 'paging': 'none'}}) was specified.
Traceback (most recent call last):
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/spyderlib/plugins/ipythonconsole.py", line 830, in create_new_client
    menu_actions=self.menu_actions)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/spyderlib/widgets/ipython.py", line 407, in __init__
    local_kernel=False)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/spyderlib/widgets/ipython.py", line 175, in __init__
    super(IPythonShellWidget, self).__init__(*args, **kw)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/qtconsole/rich_jupyter_widget.py", line 49, in __init__
    super(RichJupyterWidget, self).__init__(*args, **kw)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/qtconsole/jupyter_widget.py", line 112, in __init__
    super(JupyterWidget, self).__init__(*args, **kw)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/qtconsole/frontend_widget.py", line 153, in __init__
    super(FrontendWidget, self).__init__(*args, **kw)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/qtconsole/history_console_widget.py", line 28, in __init__
    super(HistoryConsoleWidget, self).__init__(*args, **kw)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/qtconsole/console_widget.py", line 211, in __init__
    LoggingConfigurable.__init__(self, **kw)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/traitlets/config/configurable.py", line 85, in __init__
    self.config = config
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/traitlets/traitlets.py", line 450, in __set__
    new_value = self._validate(obj, value)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/traitlets/traitlets.py", line 471, in _validate
    value = self.validate(obj, value)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/traitlets/traitlets.py", line 1045, in validate
    self.error(obj, value)
  File "/Users/abparthy/miniconda3/lib/python3.4/site-packages/traitlets/traitlets.py", line 899, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'config' trait of an IPythonShellWidget instance must be a Config, but a value of class 'IPython.config.loader.Config' (i.e. {'IPythonWidget': {'enable_calltips': True, 'kind': 'rich', 'gui_completion': 'droplist', 'buffer_size': 500, 'paging': 'none'}}) was specified.
```

**Comment by ccordoba12** [comment]
Could you run

    spyder --reset

and try again?

**Comment by abhayap** [comment]
I just tried that and it still crashed.

**Comment by chemnteach** [comment]
I am running into a similar issue.  I have looked in various places and none of the fixes have helped.  I am using Spyder 2.3.5.2 in an Anaconda build.  It has worked great until today.  I ran an Anaconda update but that did not help.  Traceback is as follows:

Traceback (most recent call last):
  File "C:\Users\cdbrown\AppData\Local\Continuum\Anaconda\lib\site.py", line 498, in execsitecustomize
    import sitecustomize
  File "C:\Users\cdbrown\AppData\Local\Continuum\Anaconda\Lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 234, in <module>
    os.environ["SPYDER_AR_STATE"].lower() == "true")
  File "C:\Users\cdbrown\AppData\Local\Continuum\Anaconda\Lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 145, in __init__
    self.i_request.connect( (host, introspection_port) )
  File "C:\Users\cdbrown\AppData\Local\Continuum\Anaconda\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

The error comes after this line:

# C:\Users\cdbrown\AppData\Local\Continuum\Anaconda\Lib\site-packages\spyderlib\qt\QtCore.pyc matches C:\Users\cdbrown\AppData\Local\Continuum\Anaconda\Lib\site-packages\spyderlib\qt\QtCore.py
import spyderlib.qt.QtCore # precompiled from C:\Users\cdbrown\AppData\Local\Continuum\Anaconda\Lib\site-packages\spyderlib\qt\QtCore.pyc

I can not start QtCore manually.  Any advice would be much appreciated.

**Comment by Zaharid** [comment]
This can be worked around by upgrading to IPython 4.0.

**Comment by alibeyram** [comment]
I have exactly the same problem. This happened after I upgraded my IPython to version 4.0. 
BTW, I do not have any problem when I am using spyder with Python3 .

**Comment by abhayap** [comment]
Anaconda upgraded to IPython 4.0 so the crash has gone away now.

**Comment by cwhits** [comment]
same problem in Anaconda with python 2.7.10, spyder 2.3.6, ipython 4.0 and ipython-qtconsole 4.0.1.

same with spyder 2.3.6, and ipython 3.2.1

```
Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> //anaconda/lib/python2.7/site-packages/IPython/utils/log.py:5: UserWarning: IPython.utils.log has moved to traitlets.log
  warn("IPython.utils.log has moved to traitlets.log")
//anaconda/lib/python2.7/site-packages/IPython/nbformat/current.py:19: UserWarning: IPython.nbformat.current is deprecated.

- use IPython.nbformat for read/write/validate public API
- use IPython.nbformat.vX directly to composing notebooks of a particular version

  """)
//anaconda/lib/python2.7/site-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/spyderlib/plugins/ipythonconsole.py", line 830, in create_new_client
    menu_actions=self.menu_actions)
  File "//anaconda/lib/python2.7/site-packages/spyderlib/widgets/ipython.py", line 407, in __init__
    local_kernel=False)
  File "//anaconda/lib/python2.7/site-packages/spyderlib/widgets/ipython.py", line 175, in __init__
    super(IPythonShellWidget, self).__init__(*args, **kw)
  File "//anaconda/lib/python2.7/site-packages/qtconsole/rich_jupyter_widget.py", line 49, in __init__
    super(RichJupyterWidget, self).__init__(*args, **kw)
  File "//anaconda/lib/python2.7/site-packages/qtconsole/jupyter_widget.py", line 112, in __init__
    super(JupyterWidget, self).__init__(*args, **kw)
  File "//anaconda/lib/python2.7/site-packages/qtconsole/frontend_widget.py", line 153, in __init__
    super(FrontendWidget, self).__init__(*args, **kw)
  File "//anaconda/lib/python2.7/site-packages/qtconsole/history_console_widget.py", line 28, in __init__
    super(HistoryConsoleWidget, self).__init__(*args, **kw)
  File "//anaconda/lib/python2.7/site-packages/qtconsole/console_widget.py", line 211, in __init__
    LoggingConfigurable.__init__(self, **kw)
  File "//anaconda/lib/python2.7/site-packages/traitlets/config/configurable.py", line 85, in __init__
    self.config = config
  File "//anaconda/lib/python2.7/site-packages/traitlets/traitlets.py", line 450, in __set__
    new_value = self._validate(obj, value)
  File "//anaconda/lib/python2.7/site-packages/traitlets/traitlets.py", line 471, in _validate
    value = self.validate(obj, value)
  File "//anaconda/lib/python2.7/site-packages/traitlets/traitlets.py", line 1045, in validate
    self.error(obj, value)
  File "//anaconda/lib/python2.7/site-packages/traitlets/traitlets.py", line 899, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'config' trait of an IPythonShellWidget instance must be a Config, but a value of class 'IPython.config.loader.Config' (i.e. {'IPythonWidget': {'gui_completion': 'droplist', 'enable_calltips': True, 'kind': 'rich', 'paging': 'none', 'buffer_size': 500}}) was specified.
```

**Comment by ccordoba12** [comment]
@cwhits, it seems your installation is in an inconsistent state. Could you run

    conda install jupyter

and then

    spyder --reset

to see if that fixes your problem?

**Comment by ccordoba12** [comment]
@alibeyram, what problem exactly?

**Comment by ccordoba12** [comment]
@chemnteach, try to remove

    C:\Users\cdbrown\AppData\Local\Continuum\Anaconda\Lib\site-packages\spyderlib\qt\QtCore.pyc

to see if that helps

**Comment by alibeyram** [comment]
I am using arch linux and spyder 2.3.5.2 ipython 4.
when I run spyder under python 2.7 I get a crash in the ipython console
This is the error:

Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> /usr/lib/python2.7/site-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)
/usr/lib/python2.7/site-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
/usr/lib/python2.7/site-packages/IPython/nbconvert.py:13: ShimWarning: The `IPython.nbconvert` package has been deprecated. You should import from ipython_nbconvert instead.
  "You should import from ipython_nbconvert instead.", ShimWarning)
/usr/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
/usr/lib/python2.7/site-packages/IPython/utils/log.py:5: UserWarning: IPython.utils.log has moved to traitlets.log
  warn("IPython.utils.log has moved to traitlets.log")
/usr/lib/python2.7/site-packages/qtconsole/rich_jupyter_widget.py:366: UserWarning: RichIPythonWidget is deprecated, use RichJupyterWidget
  warn("RichIPythonWidget is deprecated, use RichJupyterWidget")
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/spyderlib/plugins/ipythonconsole.py", line 656, in toggle_view
    self.create_new_client(give_focus=False)
  File "/usr/lib/python2.7/site-packages/spyderlib/plugins/ipythonconsole.py", line 830, in create_new_client
    menu_actions=self.menu_actions)
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/ipython.py", line 404, in __init__
    local_kernel=False)
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/ipython.py", line 172, in __init__
    super(IPythonShellWidget, self).__init__(*args, **kw)
  File "/usr/lib/python2.7/site-packages/qtconsole/rich_jupyter_widget.py", line 367, in __init__
    super(RichIPythonWidget, self).__init__(*a, **kw)
  File "/usr/lib/python2.7/site-packages/qtconsole/rich_jupyter_widget.py", line 49, in __init__
    super(RichJupyterWidget, self).__init__(*args, **kw)
  File "/usr/lib/python2.7/site-packages/qtconsole/jupyter_widget.py", line 112, in __init__
    super(JupyterWidget, self).__init__(*args, **kw)
  File "/usr/lib/python2.7/site-packages/qtconsole/frontend_widget.py", line 153, in __init__
    super(FrontendWidget, self).__init__(*args, **kw)
  File "/usr/lib/python2.7/site-packages/qtconsole/history_console_widget.py", line 28, in __init__
    super(HistoryConsoleWidget, self).__init__(*args, **kw)
  File "/usr/lib/python2.7/site-packages/qtconsole/console_widget.py", line 211, in __init__
    LoggingConfigurable.__init__(self, **kw)
  File "/usr/lib/python2.7/site-packages/traitlets/config/configurable.py", line 85, in __init__
    self.config = config
  File "/usr/lib/python2.7/site-packages/traitlets/traitlets.py", line 450, in __set__
    new_value = self._validate(obj, value)
  File "/usr/lib/python2.7/site-packages/traitlets/traitlets.py", line 471, in _validate
    value = self.validate(obj, value)
  File "/usr/lib/python2.7/site-packages/traitlets/traitlets.py", line 1045, in validate
    self.error(obj, value)
  File "/usr/lib/python2.7/site-packages/traitlets/traitlets.py", line 899, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'config' trait of an IPythonShellWidget instance must be a Config, but a value of class 'IPython.config.loader.Config' (i.e. {'IPythonWidget': {'gui_completion': 'droplist', 'enable_calltips': True, 'kind': 'rich', 'paging': 'none', 'buffer_size': 500}}) was specified.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/spyderlib/plugins/ipythonconsole.py", line 830, in create_new_client
    menu_actions=self.menu_actions)
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/ipython.py", line 404, in __init__
    local_kernel=False)
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/ipython.py", line 172, in __init__
    super(IPythonShellWidget, self).__init__(*args, **kw)
  File "/usr/lib/python2.7/site-packages/qtconsole/rich_jupyter_widget.py", line 367, in __init__
    super(RichIPythonWidget, self).__init__(*a, **kw)
  File "/usr/lib/python2.7/site-packages/qtconsole/rich_jupyter_widget.py", line 49, in __init__
    super(RichJupyterWidget, self).__init__(*args, **kw)
  File "/usr/lib/python2.7/site-packages/qtconsole/jupyter_widget.py", line 112, in __init__
    super(JupyterWidget, self).__init__(*args, **kw)
  File "/usr/lib/python2.7/site-packages/qtconsole/frontend_widget.py", line 153, in __init__
    super(FrontendWidget, self).__init__(*args, **kw)
  File "/usr/lib/python2.7/site-packages/qtconsole/history_console_widget.py", line 28, in __init__
    super(HistoryConsoleWidget, self).__init__(*args, **kw)
  File "/usr/lib/python2.7/site-packages/qtconsole/console_widget.py", line 211, in __init__
    LoggingConfigurable.__init__(self, **kw)
  File "/usr/lib/python2.7/site-packages/traitlets/config/configurable.py", line 85, in __init__
    self.config = config
  File "/usr/lib/python2.7/site-packages/traitlets/traitlets.py", line 450, in __set__
    new_value = self._validate(obj, value)
  File "/usr/lib/python2.7/site-packages/traitlets/traitlets.py", line 471, in _validate
    value = self.validate(obj, value)
  File "/usr/lib/python2.7/site-packages/traitlets/traitlets.py", line 1045, in validate
    self.error(obj, value)
  File "/usr/lib/python2.7/site-packages/traitlets/traitlets.py", line 899, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'config' trait of an IPythonShellWidget instance must be a Config, but a value of class 'IPython.config.loader.Config' (i.e. {'IPythonWidget': {'gui_completion': 'droplist', 'enable_calltips': True, 'kind': 'rich', 'paging': 'none', 'buffer_size': 500}}) was specified

I tried the newer version of Spyder(2.3.6) and run it with bootstrap.py I got the same error.

This error does not happen when I use python3

**Comment by ccordoba12** [comment]
@alibeyram, **2.3.5.2** is not compatible with Jupyter/IPython 4.0, so I don't understand how you're seeing this error with that version.

**2.3.6** is compatible with Jupyter 4.0, but I can't reproduce this error. Could you run

    spyder --reset

and try again, to see if that fixes the problem?

**Comment by alibeyram** [comment]
How can I use --reset option while using bootstrap? If I cannot I will install the 2.3.6 from the source.
2.3.6 is not available in arch linux repository.

**Comment by ccordoba12** [comment]
It's like this:

     python bootstrap.py -- --reset

**Comment by alibeyram** [comment]
Same error happens

**Comment by ccordoba12** [comment]
How did you update IPython/Jupyter? By using `pip` or `pacman`?

**Comment by alibeyram** [comment]
pacman

**Comment by ccordoba12** [comment]
What command did you run? I mean, this seems to be caused by an installation problem...

**Comment by alibeyram** [comment]
In the first place I just update/upgrade with pacman -Syu 
But I did remove and install both ipython, Jupyter, and Spyder too.
I think something is wrong with ipython2-notebook package because that does not run either.

**Comment by ccordoba12** [comment]
Ok, good to know! :-) So my guess seems to be right.

I'll leave this open, but as @abhayap pointed out, once the installation is correct, the error seems to go away.

**Comment by chemnteach** [comment]
I apologize for the delay in my response.  I did a full update of my Anaconda build, which included IPython 4.0 and the issue was fixed.  Thank you very much for your support!

**Comment by ccordoba12** [comment]
@chemnteach, thanks for letting us know about it :-)

**Comment by ccordoba12** [comment]
I found what's causing this problem a couple of hours ago. The error all of you are reporting is generated when you have:

1. An **IPython** (not Jupyter, just IPython) version less than 4.0, e.g. 3.2.1, which was the last one before the [Big Split](http://blog.jupyter.org/2015/04/15/the-big-split/) of IPython packages into the Jupyter ones.
2. The new **qtconsole** package, i.e. the one generated after the Big Split.

So, for everyone that comes here with the same problem, the solution is very simple: update IPython to **4.0.0**. That will solve the crash :-)

This can be done (depending on your installation) with:

    conda update ipython

or

    pip install -U ipython

----

**Note**: If you have time, please read the link above about the Big Split, to understand why this change from IPython to Jupyter was necessary.

**Comment by anderflash** [comment]
Same problem, even though with jupyter and --reset. I have also Archlinux.
```bash
$ spyder3
pyqt
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 432, in __get__
    value = obj._trait_values[self.name]
KeyError: 'parent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/spyderlib/spyder.py", line 3075, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python3.4/site-packages/spyderlib/spyder.py", line 2961, in run_spyder
    main.setup()
  File "/usr/lib/python3.4/site-packages/spyderlib/spyder.py", line 1198, in setup
    self.setup_layout(default=False)
  File "/usr/lib/python3.4/site-packages/spyderlib/spyder.py", line 1414, in setup_layout
    self.setup_default_layouts('default', settings)
  File "/usr/lib/python3.4/site-packages/spyderlib/spyder.py", line 1642, in setup_default_layouts
    widget.toggle_view(True)
  File "/usr/lib/python3.4/site-packages/spyderlib/plugins/ipythonconsole.py", line 648, in toggle_view
    self.create_new_client(give_focus=False)
  File "/usr/lib/python3.4/site-packages/spyderlib/plugins/ipythonconsole.py", line 823, in create_new_client
    menu_actions=self.menu_actions)
  File "/usr/lib/python3.4/site-packages/spyderlib/widgets/ipython.py", line 395, in __init__
    local_kernel=False)
  File "/usr/lib/python3.4/site-packages/spyderlib/widgets/ipython.py", line 180, in __init__
    super(IPythonShellWidget, self).__init__(*args, **kw)
  File "/usr/lib/python3.4/site-packages/IPython/qt/console/rich_ipython_widget.py", line 39, in __init__
    super(RichIPythonWidget, self).__init__(*args, **kw)
  File "/usr/lib/python3.4/site-packages/IPython/qt/console/ipython_widget.py", line 118, in __init__
    super(IPythonWidget, self).__init__(*args, **kw)
  File "/usr/lib/python3.4/site-packages/IPython/qt/console/frontend_widget.py", line 155, in __init__
    super(FrontendWidget, self).__init__(*args, **kw)
  File "/usr/lib/python3.4/site-packages/IPython/qt/console/history_console_widget.py", line 27, in __init__
    super(HistoryConsoleWidget, self).__init__(*args, **kw)
  File "/usr/lib/python3.4/site-packages/IPython/qt/console/console_widget.py", line 245, in __init__
    LoggingConfigurable.__init__(self, **kw)
  File "/usr/lib/python3.4/site-packages/IPython/config/configurable.py", line 80, in __init__
    self.config = config
  File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 465, in __set__
    obj._notify_trait(self.name, old_value, new_value)
  File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 683, in _notify_trait
    c(name, old_value, new_value)
  File "/usr/lib/python3.4/site-packages/IPython/config/configurable.py", line 159, in _config_changed
    self._load_config(new, traits=traits, section_names=section_names)
  File "/usr/lib/python3.4/site-packages/IPython/config/configurable.py", line 132, in _load_config
    my_config = self._find_my_config(cfg)
  File "/usr/lib/python3.4/site-packages/IPython/config/configurable.py", line 113, in _find_my_config
    if self.parent:
  File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 439, in __get__
    value = self._validate(obj, dynamic_default())
  File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 471, in _validate
    value = self.validate(obj, value)
  File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 1045, in validate
    self.error(obj, value)
  File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 899, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'parent' trait of an IPythonShellWidget instance must be a Configurable, but a value of class 'NoneType' (i.e. None) was specified.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 432, in __get__
    value = obj._trait_values[self.name]
KeyError: 'parent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/spyderlib/spyder.py", line 3075, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python3.4/site-packages/spyderlib/spyder.py", line 2961, in run_spyder
    main.setup()
  File "/usr/lib/python3.4/site-packages/spyderlib/spyder.py", line 1198, in setup
    self.setup_layout(default=False)
  File "/usr/lib/python3.4/site-packages/spyderlib/spyder.py", line 1414, in setup_layout
    self.setup_default_layouts('default', settings)
  File "/usr/lib/python3.4/site-packages/spyderlib/spyder.py", line 1642, in setup_default_layouts
    widget.toggle_view(True)
  File "/usr/lib/python3.4/site-packages/spyderlib/plugins/ipythonconsole.py", line 648, in toggle_view
    self.create_new_client(give_focus=False)
  File "/usr/lib/python3.4/site-packages/spyderlib/plugins/ipythonconsole.py", line 823, in create_new_client
    menu_actions=self.menu_actions)
  File "/usr/lib/python3.4/site-packages/spyderlib/widgets/ipython.py", line 395, in __init__
    local_kernel=False)
  File "/usr/lib/python3.4/site-packages/spyderlib/widgets/ipython.py", line 180, in __init__
    super(IPythonShellWidget, self).__init__(*args, **kw)
  File "/usr/lib/python3.4/site-packages/IPython/qt/console/rich_ipython_widget.py", line 39, in __init__
    super(RichIPythonWidget, self).__init__(*args, **kw)
  File "/usr/lib/python3.4/site-packages/IPython/qt/console/ipython_widget.py", line 118, in __init__
    super(IPythonWidget, self).__init__(*args, **kw)
  File "/usr/lib/python3.4/site-packages/IPython/qt/console/frontend_widget.py", line 155, in __init__
    super(FrontendWidget, self).__init__(*args, **kw)
  File "/usr/lib/python3.4/site-packages/IPython/qt/console/history_console_widget.py", line 27, in __init__
    super(HistoryConsoleWidget, self).__init__(*args, **kw)
  File "/usr/lib/python3.4/site-packages/IPython/qt/console/console_widget.py", line 245, in __init__
    LoggingConfigurable.__init__(self, **kw)
  File "/usr/lib/python3.4/site-packages/IPython/config/configurable.py", line 80, in __init__
    self.config = config
  File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 465, in __set__
    obj._notify_trait(self.name, old_value, new_value)
  File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 683, in _notify_trait
    c(name, old_value, new_value)
  File "/usr/lib/python3.4/site-packages/IPython/config/configurable.py", line 159, in _config_changed
    self._load_config(new, traits=traits, section_names=section_names)
  File "/usr/lib/python3.4/site-packages/IPython/config/configurable.py", line 132, in _load_config
    my_config = self._find_my_config(cfg)
  File "/usr/lib/python3.4/site-packages/IPython/config/configurable.py", line 113, in _find_my_config
    if self.parent:
  File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 439, in __get__
    value = self._validate(obj, dynamic_default())
  File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 471, in _validate
    value = self.validate(obj, value)
  File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 1045, in validate
    self.error(obj, value)
  File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 899, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'parent' trait of an IPythonShellWidget instance must be a Configurable, but a value of class 'NoneType' (i.e. None) was specified.
```

**Comment by ccordoba12** [comment]
You need to be sure that IPython 4 is installed too.

Although I haven't seen this error, I'm sorry but this is an 
installation problem and it's not directly related to Spyder :-)

**Comment by anderflash** [comment]
```
/usr/lib/python3.4/site-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)
/usr/lib/python3.4/site-packages/IPython/nbconvert.py:13: ShimWarning: The `IPython.nbconvert` package has been deprecated. You should import from ipython_nbconvert instead.
  "You should import from ipython_nbconvert instead.", ShimWarning)
/usr/lib/python3.4/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)
/usr/lib/python3.4/site-packages/qtconsole/rich_jupyter_widget.py:366: UserWarning: RichIPythonWidget is deprecated, use RichJupyterWidget
  warn("RichIPythonWidget is deprecated, use RichJupyterWidget")
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/spyderlib/plugins/externalconsole.py", line 922, in <lambda>
    give_focus=give_ipyclient_focus))
  File "/usr/lib/python3.4/site-packages/spyderlib/plugins/externalconsole.py", line 1029, in register_ipyclient
    give_focus=give_focus)
  File "/usr/lib/python3.4/site-packages/spyderlib/plugins/ipythonconsole.py", line 829, in register_client
    self.connect_client_to_kernel(client)
  File "/usr/lib/python3.4/site-packages/spyderlib/plugins/ipythonconsole.py", line 1034, in connect_client_to_kernel
    client.password)
  File "/usr/lib/python3.4/site-packages/spyderlib/plugins/ipythonconsole.py", line 1003, in create_kernel_manager_and_client
    cf = find_connection_file(connection_file, profile='default')
  File "/usr/lib/python3.4/site-packages/ipykernel/connect.py", line 85, in find_connection_file
    return jupyter_client.find_connection_file(filename, path=['.', security_dir])
  File "/usr/lib/python3.4/site-packages/jupyter_client/connect.py", line 185, in find_connection_file
    raise IOError("Could not find %r in %r" % (filename, path))
OSError: Could not find 'kernel-24943.json' in ['.', '/home/acmt/.ipython/profile_default/security']
```
Spyder for python2 works, but this is the error for spyder3, even though with --reset

**Comment by anderflash** [comment]
I removed everything (jupyter, ipython, ipython2, ipython-git, ipython2-git..., spyder-git, spyder3-git...), and installed just spyder3-git (I removed all ~/.spyder* config paths). Now the console is working.

**Comment by ccordoba12** [comment]
Great!

**Comment by ribby** [comment]
I had this problem as well, but thankfully just got it fixed, so I'll toss in my two cents if that helps anyone.

WHAT DIDN'T SOLVE THE PROBLEM:
spyder --reset
pip install -U ipython

WHAT SOLVED IT:
conda update spyder

My thoughts: 
"pip install -U ipython" claimed to upgrade ipython to 4.0.1 from version 3, but when I ran "conda update spyder" a few lines later it also said it was upgrading ipython 3.2.1  --> 4.0.0 . Perhaps for me, the problem stemmed from the way conda and pip handles installs differently?

**Comment by ccordoba12** [comment]
I'm glad you solved the problem, but you shouldn't be mixing pip and 
conda packages.

What i mean is that IPython is also a conda package, so you don't need to do

     pip install -U ipython

Besides, Spyder doesn't depend now on IPython but on a new package 
called qtconsole.
