### ISSUE TITLE
TypeError during interactive console autocompletion

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#268]
_From [akes...@gmail.com](https://code.google.com/u/113577650587847141142/) on 2010-08-08T16:55:33Z_

I have not figured out how to consistently reproduce the problem. Nevertheless, I think the stack trace and problem description might be enough for someone clever to fix it.

Ocassionally, when I press TAB for autocomplete in the interactive console, I instead get the following stack trace in the interactive console:

"
Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\spyderlib\widgets\interactiveshell.py", line 367, in keyPressEvent
    self.postprocess_keyevent(event)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\shell.py", line 787, in postprocess_keyevent
    ShellBaseWidget.postprocess_keyevent(self, event)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\shell.py", line 352, in postprocess_keyevent
    self._key_tab()
  File "C:\Python26\lib\site-packages\spyderlib\widgets\shell.py", line 827, in _key_tab
    self.show_code_completion()
  File "C:\Python26\lib\site-packages\spyderlib\widgets\shell.py", line 984, in show_code_completion
    self.show_completion_list(b_k_g, completion_text=last_obj)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\shell.py", line 913, in show_completion_list
    self.show_completion_widget(sorted(completions, key=key))
TypeError: descriptor 'lower' requires a 'str' object but received a 'unicode'
"

This seems to only happen if I am starting to type the name of an imported package. For instance, I if I have a package name "mypackage", then on a new line I type
"myp" and then TAB then instead of the expected autocomplete, I get the above stack trace.

The problem is not fully reproducible -- if I restart spyder and re-import the modules, it goes away. If I run for long enough it seems to come back, I haven't figured out what triggers it yet. What version of the product are you using? On what operating system? I am running Spyder (all) 1.1.3, on Windows 7, with Python 2.6.5, Qt 4.6.2, PyQt 4.7.4.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=268_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-08-10T02:27:44Z_

Fixed in both v1.1 and v2.0 branches, respectively: https://code.google.com/p/spyderlib/source/detail?r=abaf7155ebb8e9447eaa4b248b74e71420e653d1&repo=v11 https://code.google.com/p/spyderlib/source/detail?r=0957518a5bb09de6a7c9cdbe5fe635b29d6d437b

**Status:** Fixed
