### ISSUE TITLE
IPython Console Error

### ISSUE THREAD

**Issue by IM312** [spyder-ide/spyder#2690]
## Description

**What steps will reproduce the problem?**

1. starting Spyder from Anaconda Launcher
2. opening an IPython Console
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 2.3.6 
* Python Version: 2.7.8
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.10.4 on Windows

## Optional dependencies
```
pyflakes >=0.5.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=1.0   :  3.2.1 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.5 (OK)
pylint >=0.25   :  None (NOK)

```
Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> C:\Users\Ian\Anaconda\lib\site-packages\IPython\nbformat\current.py:19: UserWarning: IPython.nbformat.current is deprecated.

- use IPython.nbformat for read/write/validate public API
- use IPython.nbformat.vX directly to composing notebooks of a particular version

  """)
Traceback (most recent call last):
  File "C:\Users\Ian\Anaconda\lib\site-packages\spyderlib\plugins\ipythonconsole.py", line 656, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\Ian\Anaconda\lib\site-packages\spyderlib\plugins\ipythonconsole.py", line 830, in create_new_client
    menu_actions=self.menu_actions)
  File "C:\Users\Ian\Anaconda\lib\site-packages\spyderlib\widgets\ipython.py", line 407, in __init__
    local_kernel=False)
  File "C:\Users\Ian\Anaconda\lib\site-packages\spyderlib\widgets\ipython.py", line 175, in __init__
    super(IPythonShellWidget, self).__init__(*args, **kw)
  File "C:\Users\Ian\Anaconda\lib\site-packages\qtconsole\rich_jupyter_widget.py", line 49, in __init__
    super(RichJupyterWidget, self).__init__(*args, **kw)
  File "C:\Users\Ian\Anaconda\lib\site-packages\qtconsole\jupyter_widget.py", line 112, in __init__
    super(JupyterWidget, self).__init__(*args, **kw)
  File "C:\Users\Ian\Anaconda\lib\site-packages\qtconsole\frontend_widget.py", line 153, in __init__
    super(FrontendWidget, self).__init__(*args, **kw)
  File "C:\Users\Ian\Anaconda\lib\site-packages\qtconsole\history_console_widget.py", line 28, in __init__
    super(HistoryConsoleWidget, self).__init__(*args, **kw)
  File "C:\Users\Ian\Anaconda\lib\site-packages\qtconsole\console_widget.py", line 211, in __init__
    LoggingConfigurable.__init__(self, **kw)
  File "C:\Users\Ian\Anaconda\lib\site-packages\traitlets\config\configurable.py", line 85, in __init__
    self.config = config
  File "C:\Users\Ian\Anaconda\lib\site-packages\traitlets\traitlets.py", line 450, in __set__
    new_value = self._validate(obj, value)
  File "C:\Users\Ian\Anaconda\lib\site-packages\traitlets\traitlets.py", line 471, in _validate
    value = self.validate(obj, value)
  File "C:\Users\Ian\Anaconda\lib\site-packages\traitlets\traitlets.py", line 1045, in validate
    self.error(obj, value)
  File "C:\Users\Ian\Anaconda\lib\site-packages\traitlets\traitlets.py", line 899, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'config' trait of an IPythonShellWidget instance must be a Config, but a value of class 'IPython.config.loader.Config' (i.e. {'IPythonWidget': {'gui_completion': 'droplist', 'enable_calltips': True, 'kind': 'rich', 'paging': 'none', 'buffer_size': 500}}) was specified.
Traceback (most recent call last):
  File "C:\Users\Ian\Anaconda\lib\site-packages\spyderlib\plugins\ipythonconsole.py", line 830, in create_new_client
    menu_actions=self.menu_actions)
  File "C:\Users\Ian\Anaconda\lib\site-packages\spyderlib\widgets\ipython.py", line 407, in __init__
    local_kernel=False)
  File "C:\Users\Ian\Anaconda\lib\site-packages\spyderlib\widgets\ipython.py", line 175, in __init__
    super(IPythonShellWidget, self).__init__(*args, **kw)
  File "C:\Users\Ian\Anaconda\lib\site-packages\qtconsole\rich_jupyter_widget.py", line 49, in __init__
    super(RichJupyterWidget, self).__init__(*args, **kw)
  File "C:\Users\Ian\Anaconda\lib\site-packages\qtconsole\jupyter_widget.py", line 112, in __init__
    super(JupyterWidget, self).__init__(*args, **kw)
  File "C:\Users\Ian\Anaconda\lib\site-packages\qtconsole\frontend_widget.py", line 153, in __init__
    super(FrontendWidget, self).__init__(*args, **kw)
  File "C:\Users\Ian\Anaconda\lib\site-packages\qtconsole\history_console_widget.py", line 28, in __init__
    super(HistoryConsoleWidget, self).__init__(*args, **kw)
  File "C:\Users\Ian\Anaconda\lib\site-packages\qtconsole\console_widget.py", line 211, in __init__
    LoggingConfigurable.__init__(self, **kw)
  File "C:\Users\Ian\Anaconda\lib\site-packages\traitlets\config\configurable.py", line 85, in __init__
    self.config = config
  File "C:\Users\Ian\Anaconda\lib\site-packages\traitlets\traitlets.py", line 450, in __set__
    new_value = self._validate(obj, value)
  File "C:\Users\Ian\Anaconda\lib\site-packages\traitlets\traitlets.py", line 471, in _validate
    value = self.validate(obj, value)
  File "C:\Users\Ian\Anaconda\lib\site-packages\traitlets\traitlets.py", line 1045, in validate
    self.error(obj, value)
  File "C:\Users\Ian\Anaconda\lib\site-packages\traitlets\traitlets.py", line 899, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'config' trait of an IPythonShellWidget instance must be a Config, but a value of class 'IPython.config.loader.Config' (i.e. {'IPythonWidget': {'gui_completion': 'droplist', 'enable_calltips': True, 'kind': 'rich', 'paging': 'none', 'buffer_size': 500}}) was specified.
Traceback (most recent call last):
  File "C:\Users\Ian\Anaconda\lib\site-packages\spyderlib\plugins\ipythonconsole.py", line 830, in create_new_client
    menu_actions=self.menu_actions)
  File "C:\Users\Ian\Anaconda\lib\site-packages\spyderlib\widgets\ipython.py", line 407, in __init__
    local_kernel=False)
  File "C:\Users\Ian\Anaconda\lib\site-packages\spyderlib\widgets\ipython.py", line 175, in __init__
    super(IPythonShellWidget, self).__init__(*args, **kw)
  File "C:\Users\Ian\Anaconda\lib\site-packages\qtconsole\rich_jupyter_widget.py", line 49, in __init__
    super(RichJupyterWidget, self).__init__(*args, **kw)
  File "C:\Users\Ian\Anaconda\lib\site-packages\qtconsole\jupyter_widget.py", line 112, in __init__
    super(JupyterWidget, self).__init__(*args, **kw)
  File "C:\Users\Ian\Anaconda\lib\site-packages\qtconsole\frontend_widget.py", line 153, in __init__
    super(FrontendWidget, self).__init__(*args, **kw)
  File "C:\Users\Ian\Anaconda\lib\site-packages\qtconsole\history_console_widget.py", line 28, in __init__
    super(HistoryConsoleWidget, self).__init__(*args, **kw)
  File "C:\Users\Ian\Anaconda\lib\site-packages\qtconsole\console_widget.py", line 211, in __init__
    LoggingConfigurable.__init__(self, **kw)
  File "C:\Users\Ian\Anaconda\lib\site-packages\traitlets\config\configurable.py", line 85, in __init__
    self.config = config
  File "C:\Users\Ian\Anaconda\lib\site-packages\traitlets\traitlets.py", line 450, in __set__
    new_value = self._validate(obj, value)
  File "C:\Users\Ian\Anaconda\lib\site-packages\traitlets\traitlets.py", line 471, in _validate
    value = self.validate(obj, value)
  File "C:\Users\Ian\Anaconda\lib\site-packages\traitlets\traitlets.py", line 1045, in validate
    self.error(obj, value)
  File "C:\Users\Ian\Anaconda\lib\site-packages\traitlets\traitlets.py", line 899, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'config' trait of an IPythonShellWidget instance must be a Config, but a value of class 'IPython.config.loader.Config' (i.e. {'IPythonWidget': {'gui_completion': 'droplist', 'enable_calltips': True, 'kind': 'rich', 'paging': 'none', 'buffer_size': 500}}) was specified.

**Comment by ccordoba12** [comment]
Please run (after closing Spyder and the IPython notebook) this command:

    conda update ipython

to fix this error.
