### ISSUE TITLE
Internal consol error message

### ISSUE THREAD

**Issue by Temmplar** [spyder-ide/spyder#2729]
>>> /home/george/anaconda/lib/python2.7/site-packages/IPython/nbformat/current.py:19: UserWarning: IPython.nbformat.current is deprecated.

- use IPython.nbformat for read/write/validate public API
- use IPython.nbformat.vX directly to composing notebooks of a particular version

  """)
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/george/anaconda/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/george/anaconda/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/george/anaconda/lib/python2.7/site-packages/spyderlib/utils/introspection/jedi_plugin.py", line 246, in preload
    jedi.preload_module(lib)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/api/__init__.py", line 716, in preload_module
    Script(s, 1, len(s), None).completions()
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/api/__init__.py", line 157, in completions
    completions = get_completions(user_stmt, b)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/api/__init__.py", line 136, in get_completions
    return self._simple_complete(path, like)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/api/__init__.py", line 203, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/api/__init__.py", line 265, in _prepare_goto
    scopes = self._evaluator.eval_statement(eval_stmt)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/recursion.py", line 24, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 132, in eval_statement
    result = self.eval_expression_list(expression_list)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 170, in eval_expression_list
    return self.process_precedence_element(p) or []
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 180, in process_precedence_element
    return self.eval_statement_element(el)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 215, in eval_statement_element
    return self.eval_call(element)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 226, in eval_call
    return self.eval_call_path(path, par, s.start_pos)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 244, in eval_call_path
    types = imports.follow_imports(self, types)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 482, in follow_imports
    for r in ImportWrapper(evaluator, s).follow():
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 181, in follow
    star_imports = remove_star_imports(self._evaluator, module)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/cache.py", line 171, in wrapper
    mods = func(evaluator, scope, *args, **kwargs)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 500, in remove_star_imports
    modules = follow_imports(evaluator, (i for i in scope.get_imports() if i.star))
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 482, in follow_imports
    for r in ImportWrapper(evaluator, s).follow():
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 181, in follow
    star_imports = remove_star_imports(self._evaluator, module)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/cache.py", line 171, in wrapper
    mods = func(evaluator, scope, *args, **kwargs)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 500, in remove_star_imports
    modules = follow_imports(evaluator, (i for i in scope.get_imports() if i.star))
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 482, in follow_imports
    for r in ImportWrapper(evaluator, s).follow():
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 171, in follow
    module, rest = self._importer.follow_file_system()
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 365, in follow_file_system
    module, rest = self._follow_sys_path(sys_path_mod)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 469, in _follow_sys_path
    return _load_module(path, source, sys_path=sys_path), rest
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 526, in _load_module
    cached = cache.load_parser(path, name)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/cache.py", line 227, in load_parser
    return ParserPickling.load_parser(n, p_time)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/cache.py", line 285, in load_parser
    parser_cache_item = pickle.load(f)
TypeError: list indices must be integers, not Name

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/george/anaconda/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/george/anaconda/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/george/anaconda/lib/python2.7/site-packages/spyderlib/utils/introspection/jedi_plugin.py", line 246, in preload
    jedi.preload_module(lib)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/api/__init__.py", line 716, in preload_module
    Script(s, 1, len(s), None).completions()
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/api/__init__.py", line 157, in completions
    completions = get_completions(user_stmt, b)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/api/__init__.py", line 136, in get_completions
    return self._simple_complete(path, like)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/api/__init__.py", line 203, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/api/__init__.py", line 265, in _prepare_goto
    scopes = self._evaluator.eval_statement(eval_stmt)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/recursion.py", line 24, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 132, in eval_statement
    result = self.eval_expression_list(expression_list)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 170, in eval_expression_list
    return self.process_precedence_element(p) or []
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 180, in process_precedence_element
    return self.eval_statement_element(el)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 215, in eval_statement_element
    return self.eval_call(element)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 226, in eval_call
    return self.eval_call_path(path, par, s.start_pos)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 244, in eval_call_path
    types = imports.follow_imports(self, types)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 482, in follow_imports
    for r in ImportWrapper(evaluator, s).follow():
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 181, in follow
    star_imports = remove_star_imports(self._evaluator, module)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/cache.py", line 171, in wrapper
    mods = func(evaluator, scope, *args, **kwargs)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 500, in remove_star_imports
    modules = follow_imports(evaluator, (i for i in scope.get_imports() if i.star))
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 482, in follow_imports
    for r in ImportWrapper(evaluator, s).follow():
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 181, in follow
    star_imports = remove_star_imports(self._evaluator, module)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/cache.py", line 171, in wrapper
    mods = func(evaluator, scope, *args, **kwargs)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 500, in remove_star_imports
    modules = follow_imports(evaluator, (i for i in scope.get_imports() if i.star))
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 482, in follow_imports
    for r in ImportWrapper(evaluator, s).follow():
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 171, in follow
    module, rest = self._importer.follow_file_system()
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 365, in follow_file_system
    module, rest = self._follow_sys_path(sys_path_mod)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 469, in _follow_sys_path
    return _load_module(path, source, sys_path=sys_path), rest
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 526, in _load_module
    cached = cache.load_parser(path, name)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/cache.py", line 227, in load_parser
    return ParserPickling.load_parser(n, p_time)
  File "/home/george/anaconda/lib/python2.7/site-packages/jedi/cache.py", line 285, in load_parser

**Comment by ccordoba12** [comment]
Thanks for reporting. This error was already fixed by not allowing Jedi 0.9 as a version that Spyder can use to do code completions on the Editor. However, Jedi 0.8.1 is working correctly :-)

This will fixed in Spyder 2.3.7, but in the mean time you can run

    conda install jedi==0.8.1

to fix this problem.

**Comment by Temmplar** [comment]
@ccordoba12 Thank you very much!

**Comment by Temmplar** [comment]
I have to say that this is far far the best support I ever met. :) Thank you.
