### ISSUE TITLE
Cannot connect to kernel

### ISSUE THREAD

**Issue by kim2207** [spyder-ide/spyder#2742]
I cannot run any of my code and my Ipython console keeps trying to connect to the kernel

As soon as I run a file the following error is reproduced
```
Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\plugins\externalconsole.py", line 1246, in toggle_view
    self.open_interpreter()
  File "C:\Python27\lib\site-packages\spyderlib\plugins\externalconsole.py", line 1258, in open_interpreter
    interact=True, debug=False, python=True)
  File "C:\Python27\lib\site-packages\spyderlib\plugins\externalconsole.py", line 832, in start
    show_elapsed_time=show_elapsed_time)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\pythonshell.py", line 207, in __init__
    show_elapsed_time=show_elapsed_time)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\baseshell.py", line 73, in __init__
    self.shell = self.SHELL_CLASS(parent, get_conf_path(history_filename))
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\pythonshell.py", line 39, in __init__
    PythonShellWidget.__init__(self, parent, history_filename, profile)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\shell.py", line 673, in __init__
    ShellBaseWidget.__init__(self, parent, history_filename, profile)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\shell.py", line 63, in __init__
    self.history = self.load_history()
  File "C:\Python27\lib\site-packages\spyderlib\widgets\shell.py", line 494, in load_history
    if rawhistory[1] != self.INITHISTORY[1]:
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\plugins\ipythonconsole.py", line 656, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Python27\lib\site-packages\spyderlib\plugins\ipythonconsole.py", line 832, in create_new_client
    self.main.extconsole.start_ipykernel(client, give_focus=give_focus)
  File "C:\Python27\lib\site-packages\spyderlib\plugins\externalconsole.py", line 1273, in start_ipykernel
    ipyclient=client, give_ipyclient_focus=give_focus)
  File "C:\Python27\lib\site-packages\spyderlib\plugins\externalconsole.py", line 832, in start
    show_elapsed_time=show_elapsed_time)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\pythonshell.py", line 207, in __init__
    show_elapsed_time=show_elapsed_time)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\baseshell.py", line 73, in __init__
    self.shell = self.SHELL_CLASS(parent, get_conf_path(history_filename))
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\pythonshell.py", line 39, in __init__
    PythonShellWidget.__init__(self, parent, history_filename, profile)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\shell.py", line 673, in __init__
    ShellBaseWidget.__init__(self, parent, history_filename, profile)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\shell.py", line 63, in __init__
    self.history = self.load_history()
  File "C:\Python27\lib\site-packages\spyderlib\widgets\shell.py", line 494, in load_history
    if rawhistory[1] != self.INITHISTORY[1]:
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\plugins\ipythonconsole.py", line 803, in run_script_in_current_client
    self.execute_python_code(line)
  File "C:\Python27\lib\site-packages\spyderlib\plugins\ipythonconsole.py", line 816, in execute_python_code
    client.shellwidget.execute(to_text_string(lines))
  File "C:\Python27\lib\site-packages\IPython\qt\console\history_console_widget.py", line 46, in execute
    source, hidden, interactive)
  File "C:\Python27\lib\site-packages\IPython\qt\console\console_widget.py", line 655, in execute
    self._execute(source, hidden)
  File "C:\Python27\lib\site-packages\IPython\qt\console\frontend_widget.py", line 243, in _execute
    msg_id = self.kernel_client.execute(source, hidden)
AttributeError: 'NoneType' object has no attribute 'execute'
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\plugins\ipythonconsole.py", line 803, in run_script_in_current_client
    self.execute_python_code(line)
  File "C:\Python27\lib\site-packages\spyderlib\plugins\ipythonconsole.py", line 816, in execute_python_code
    client.shellwidget.execute(to_text_string(lines))
  File "C:\Python27\lib\site-packages\IPython\qt\console\history_console_widget.py", line 46, in execute
    source, hidden, interactive)
  File "C:\Python27\lib\site-packages\IPython\qt\console\console_widget.py", line 655, in execute
    self._execute(source, hidden)
  File "C:\Python27\lib\site-packages\IPython\qt\console\frontend_widget.py", line 243, in _execute
    msg_id = self.kernel_client.execute(source, hidden)
AttributeError: 'NoneType' object has no attribute 'execute'




```

**Comment by ccordoba12** [comment]
It seems you have a mismatch of IPython versions. I don't know how you installed Spyder and IPython, so I can't give you further help.

If you're new to Python, I'd recommend you to use Anaconda or WinPython, instead of installing things by yourself :-)

**Comment by ccordoba12** [comment]
Closing because of lack of response.
