### ISSUE TITLE
After startup, new IPython terminals cannot be opened

### ISSUE THREAD

**Issue by tomas-teijeiro** [spyder-ide/spyder#2753]
## Description

On Spyder startup, an IPython terminal is correctly opened and is fully operational. However, if I try to open new IPython terminals, the "Connecting to kernel" message never disappears, and an internal exception is raised with the following traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/plugins/externalconsole.py", line 925, in <lambda>
    give_focus=give_ipyclient_focus))
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/plugins/externalconsole.py", line 1033, in register_ipyclient
    give_focus=give_focus)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/plugins/ipythonconsole.py", line 836, in register_client
    self.connect_client_to_kernel(client)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/plugins/ipythonconsole.py", line 1048, in connect_client_to_kernel
    client.password)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/plugins/ipythonconsole.py", line 1017, in create_kernel_manager_and_client
    cf = find_connection_file(connection_file)
  File "/usr/lib/python2.7/dist-packages/IPython/kernel/connect.py", line 203, in find_connection_file
    app = IPApp.instance()
  File "/usr/lib/python2.7/dist-packages/IPython/config/configurable.py", line 360, in instance
    '%s are being created.' % cls.__name__
IPython.config.configurable.MultipleInstanceError: Multiple incompatible subclass instances of BaseIPythonApplication are being created.
```

**What steps will reproduce the problem?**

1. Start Spyder
2. Try to start a new IPython terminal.

## Version and main components

* Spyder Version: 2.3.7 
* Python Version: 2.7.6
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.10.4 on Linux

## Optional dependencies
```
IPython >=1.0      :  1.2.1 (OK)
jedi >=0.8.1;<0.9.0:  None (NOK)
matplotlib >=1.0   :  1.3.1 (OK)
pandas >=0.13.1    :  0.17.0 (OK)
pep8 >=0.6         :  None (NOK)
psutil >=0.3       :  1.2.1 (OK)
pyflakes >=0.5.0   :  0.8.1 (OK)
pygments >=1.6     :  1.6 (OK)
pylint >=0.25      :  1.4.4 (OK)
rope >=0.9.2       :  0.9.2 (OK)
sphinx >=0.6.6     :  1.2.2 (OK)
sympy >=0.7.3      :  None (NOK)
zmq >=2.1.11       :  14.0.1 (OK)

```

**Comment by tomas-teijeiro** [comment]
The problem was due to the IPython version. Upgrading to IPython 4.0 via pip solved the problem. I think optional dependencies requirements should therefore be updated.

**Comment by ccordoba12** [comment]
Yes, that was the problem. Glad that you figured out by yourself :-)
