### ISSUE TITLE
Unable to start IPython console

### ISSUE THREAD

**Issue by l2** [spyder-ide/spyder#2755]
**Context**
I am working on a OSX 10.10.5 and I have install the required package for python using Homebrew. Spyder has been install from source (version 2.3.7). Spyder works well but I can't run a IPython console. I obtain the following error
>    Traceback (most recent call last):
       File "/usr/local/lib/python2.7/site-packages/spyderlib/plugins/ipythonconsole.py", line 830, in create_new_client
    menu_actions=self.menu_actions)
  File "/usr/local/lib/python2.7/site-packages/spyderlib/widgets/ipython.py", line 407, in __init__
    local_kernel=False)
  File "/usr/local/lib/python2.7/site-packages/spyderlib/widgets/ipython.py", line 175, in __init__
    super(IPythonShellWidget, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/qtconsole/rich_jupyter_widget.py", line 49, in __init__
    super(RichJupyterWidget, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/qtconsole/jupyter_widget.py", line 112, in __init__
    super(JupyterWidget, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/qtconsole/frontend_widget.py", line 153, in __init__
    super(FrontendWidget, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/qtconsole/history_console_widget.py", line 28, in __init__
    super(HistoryConsoleWidget, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/qtconsole/console_widget.py", line 211, in __init__
    LoggingConfigurable.__init__(self, **kw)
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/configurable.py", line 85, in __init__
    self.config = config
  File "/usr/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 450, in __set__
    new_value = self._validate(obj, value)
  File "/usr/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 471, in _validate
    value = self.validate(obj, value)
  File "/usr/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 1045, in validate
    self.error(obj, value)
  File "/usr/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 899, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'config' trait of an IPythonShellWidget instance must be a Config, but a value of class 'IPython.config.loader.Config' (i.e. {'IPythonWidget': {'gui_completion': 'droplist', 'enable_calltips': True, 'kind': 'rich', 'paging': 'none', 'buffer_size': 500}}) was specified.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spyderlib/plugins/ipythonconsole.py", line 830, in create_new_client
    menu_actions=self.menu_actions)
  File "/usr/local/lib/python2.7/site-packages/spyderlib/widgets/ipython.py", line 407, in __init__
    local_kernel=False)
  File "/usr/local/lib/python2.7/site-packages/spyderlib/widgets/ipython.py", line 175, in __init__
    super(IPythonShellWidget, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/qtconsole/rich_jupyter_widget.py", line 49, in __init__
    super(RichJupyterWidget, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/qtconsole/jupyter_widget.py", line 112, in __init__
    super(JupyterWidget, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/qtconsole/frontend_widget.py", line 153, in __init__
    super(FrontendWidget, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/qtconsole/history_console_widget.py", line 28, in __init__
    super(HistoryConsoleWidget, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/qtconsole/console_widget.py", line 211, in __init__
    LoggingConfigurable.__init__(self, **kw)
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/configurable.py", line 85, in __init__
    self.config = config
  File "/usr/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 450, in __set__
    new_value = self._validate(obj, value)
  File "/usr/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 471, in _validate
    value = self.validate(obj, value)
  File "/usr/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 1045, in validate
    self.error(obj, value)
  File "/usr/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 899, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'config' trait of an IPythonShellWidget instance must be a Config, but a value of class 'IPython.config.loader.Config' (i.e. {'IPythonWidget': {'gui_completion': 'droplist', 'enable_calltips': True, 'kind': 'rich', 'paging': 'none', 'buffer_size': 500}}) was specified.

I have installed IPython 3.0.0.

**Comment by ccordoba12** [comment]
You to need to do

    pip install -U ipython

to fix this problem.

If that doesn't work, then please also run

    pip install -U qtconsole

**Comment by l2** [comment]
I have ran the first command and now I have the following message and I can't use Spyder anymore.

![capture d ecran 2015-10-11 a 20 34 48](https://cloud.githubusercontent.com/assets/147177/10418335/a8b5fdfe-7057-11e5-9d96-29ced3efa9a6.png)

**Comment by ccordoba12** [comment]
What happens if you run the second?

**Comment by l2** [comment]
exactly the same thing...

**Comment by l2** [comment]
The command  `pip install -U ipython` installs `ipython-4.0.0`. Is this version compatible with spyder?

**Comment by l2** [comment]
Any solution of my issue?

**Comment by ccordoba12** [comment]
Just install ipython 4.0.0, that should fix your issue, along with installing spyder 2.3.7 and qtconsole 4.1.0.

**Comment by l2** [comment]
I have ran `pip install --upgrade ipython qtconsole` and now I have the following error:

![capture d ecran 2015-10-19 a 16 05 58](https://cloud.githubusercontent.com/assets/147177/10579976/7b083726-767b-11e5-9cc5-051cae2dcd35.png)

**Comment by ccordoba12** [comment]
I'll test this configuration on my Mac machine and come back to you with 
my findings :-)

**Comment by l2** [comment]
It's very weird. I have tried two things:
1. obtaining  the source of `spyder 2.3.7`, execute `python bootstrap.py`. I obtain the following error message :
![capture d ecran 2015-10-19 a 16 25 11](https://cloud.githubusercontent.com/assets/147177/10580477/fd201880-767d-11e5-8b88-2e3f241a8c98.png)

2. obtaining the DMG `spyder 2.3.7`, install it and run, I obtain the following error message: 
![capture d ecran 2015-10-19 a 16 26 13](https://cloud.githubusercontent.com/assets/147177/10580525/238a59a4-767e-11e5-91b9-131a554318cc.png)

`Optional dependencies` says:

    IPython >=1.0      :  4.0.0 (OK)
    jedi >=0.8.1;<0.9.0:  None (NOK)
    matplotlib >=1.0   :  1.4.3 (OK)
    pandas >=0.13.1    :  0.16.2 (OK)
    pep8 >=0.6         :  1.6.2 (OK)
    psutil >=0.3       :  3.2.2 (OK)
    pyflakes >=0.5.0   :  1.0.0 (OK)
    pygments >=1.6     :  2.0.2 (OK)
    pylint >=0.25      :  1.4.4 (OK)
    qtconsole >=4.0    :  4.0.1 (OK)
    rope >=0.9.2       :  0.10.2 (OK)
    sphinx >=0.6.6     :  1.3.1 (OK)
    sympy >=0.7.3      :  0.7.6.1 (OK)
    zmq >=2.1.11       :  14.7.0 (OK)

**Comment by l2** [comment]
up!
