### ISSUE TITLE
Either update to El Capitan or to Spyder 2.3.7 broke it

### ISSUE THREAD

**Issue by sschloesser** [spyder-ide/spyder#2760]
I'm not sure which of these updates might have caused the problem because I did both before trying to open Spyder. I use the Anaconda launcher to start it, and it just stopped working. I went into the terminal and tried launching from there, which gave the following error:

```
tatan:~ Sebastian$ spyder
Traceback (most recent call last):
  File "/Users/Sebastian/anaconda/bin/spyder", line 3, in <module>
    start_app.main()
  File "/Users/Sebastian/anaconda/lib/python3.4/site-packages/spyderlib/start_app.py", line 114, in main
    from spyderlib import spyder
  File "/Users/Sebastian/anaconda/lib/python3.4/site-packages/spyderlib/spyder.py", line 155, in <module>
    from spyderlib.utils.environ import WinUserEnvDialog
  File "/Users/Sebastian/anaconda/lib/python3.4/site-packages/spyderlib/utils/environ.py", line 17, in <module>
    from spyderlib.widgets.dicteditor import DictEditor
  File "/Users/Sebastian/anaconda/lib/python3.4/site-packages/spyderlib/widgets/dicteditor.py", line 39, in <module>
    from spyderlib.widgets.dicteditorutils import (sort_against, get_size,
  File "/Users/Sebastian/anaconda/lib/python3.4/site-packages/spyderlib/widgets/dicteditorutils.py", line 62, in <module>
    required_version=PANDAS_REQVER)
  File "/Users/Sebastian/anaconda/lib/python3.4/site-packages/spyderlib/dependencies.py", line 70, in add
    installed_version)]
  File "/Users/Sebastian/anaconda/lib/python3.4/site-packages/spyderlib/dependencies.py", line 32, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "/Users/Sebastian/anaconda/lib/python3.4/site-packages/spyderlib/utils/programs.py", line 238, in get_module_version
    mod = __import__(module_name)
  File "/Users/Sebastian/anaconda/lib/python3.4/site-packages/pandas/__init__.py", line 7, in <module>
    from pandas import hashtable, tslib, lib
  File "pandas/tslib.pyx", line 42, in init pandas.tslib (pandas/tslib.c:73814)
  File "/Users/Sebastian/anaconda/lib/python3.4/site-packages/dateutil/tz.py", line 78
    `self._name`,
    ^
SyntaxError: invalid syntax
```
For now, I just made a new environment with Anaconda with Python 2.7 and installed Spyder for that version, which is working.

**Comment by ccordoba12** [comment]
There seems to be a problem with your installation because Pandas is corrupted. Please try to run

    conda install -f pandas

to see if that fixes your problem.

**Comment by DSLituiev** [comment]
In my case running:

    conda install -f python-dateutil
    conda install -f pandas

resolved the issue

**Comment by ccordoba12** [comment]
@sschloesser, could you confirm @DSLituiev suggestion?

**Comment by ccordoba12** [comment]
Closing because of lack of response.
