### ISSUE TITLE
spyder crash with ipython 4.0 after spyder --reset

### ISSUE THREAD

**Issue by zastrugi** [spyder-ide/spyder#2769]
My system is ubuntu 12.04 with python 2.7.3. Just to clarify, I have ipython in my machine for several years and there is no problem with it. When I first install spyder, it does start, but the ipython console is not connected. I thought it might be because the ipython was too old (2.8.x). So I did a `pip install -U ipython` and got it to 4.0. It still does not work. Using `import IPython` then `IPython.start_ipython()` in python console does bring up ipython and seems to work fine. I still want to have it launched when spyder starts so I tried something else. I did `spyder --reset`. This time spyder won't start at all, with long error messages. Any idea why does this happen and any suggestions?
I have seen other reports of issues related ipython 4.0, not sure this is related though. 

The messages are attached below:
```
Traceback (most recent call last):
  File "/home/user123/Downloads/tmp/spyder/spyder/spyderlib/spyder.py", line 3135, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/user123/Downloads/tmp/spyder/spyder/spyderlib/spyder.py", line 3021, in run_spyder
    main.setup()
  File "/home/user123/Downloads/tmp/spyder/spyder/spyderlib/spyder.py", line 1213, in setup
    self.setup_layout(default=False)
  File "/home/user123/Downloads/tmp/spyder/spyder/spyderlib/spyder.py", line 1436, in setup_layout
    self.setup_default_layouts('default', settings)
  File "/home/user123/Downloads/tmp/spyder/spyder/spyderlib/spyder.py", line 1611, in setup_default_layouts
    widget.toggle_view(True)
  File "/home/user123/Downloads/tmp/spyder/spyder/spyderlib/plugins/ipythonconsole.py", line 680, in toggle_view
    self.create_new_client(give_focus=False)
  File "/home/user123/Downloads/tmp/spyder/spyder/spyderlib/plugins/ipythonconsole.py", line 855, in create_new_client
    menu_actions=self.menu_actions)
  File "/home/user123/Downloads/tmp/spyder/spyder/spyderlib/widgets/ipython.py", line 416, in __init__
    local_kernel=False)
  File "/home/user123/Downloads/tmp/spyder/spyder/spyderlib/widgets/ipython.py", line 184, in __init__
    super(IPythonShellWidget, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/qtconsole/rich_jupyter_widget.py", line 49, in __init__
    super(RichJupyterWidget, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/qtconsole/jupyter_widget.py", line 112, in __init__
    super(JupyterWidget, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/qtconsole/frontend_widget.py", line 153, in __init__
    super(FrontendWidget, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/qtconsole/history_console_widget.py", line 28, in __init__
    super(HistoryConsoleWidget, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/qtconsole/console_widget.py", line 211, in __init__
    LoggingConfigurable.__init__(self, **kw)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/configurable.py", line 85, in __init__
    self.config = config
  File "/usr/local/lib/python2.7/dist-packages/traitlets/traitlets.py", line 450, in __set__
    new_value = self._validate(obj, value)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/traitlets.py", line 471, in _validate
    value = self.validate(obj, value)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/traitlets.py", line 1045, in validate
    self.error(obj, value)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/traitlets.py", line 899, in error
    raise TraitError(e)
TraitError: The 'config' trait of an IPythonShellWidget instance must be a Config, but a value of class 'IPython.config.loader.Config' (i.e. {'IPythonWidget': {'gui_completion': 'droplist', 'enable_calltips': True, 'kind': 'rich', 'paging': 'none', 'buffer_size': 500}}) was specified.
```

**Comment by ccordoba12** [comment]
Please run

    pip install -U qtconsole
    pip install -U spyder

to see if that fixes the problem

**Comment by zastrugi** [comment]
Tried the first now working. I installed spyder using source from github. Also I have tried to git pull to get most recent code. Tested python bootstrap.py gives the same output. I did find that setting the below statement (line 946 in spyderlib/spyder.py) to False (keep self.ipyconsole to None) does get spyder started but without ipython console of course:
"        if IPYTHON_QT_INSTALLED and not self.light:
            self.set_splash(_("Loading IPython console..."))
            from spyderlib.plugins.ipythonconsole import IPythonConsole
            self.ipyconsole = IPythonConsole(self)
            self.ipyconsole.register_plugin()"

Once the spyder is started, reversing the code back does not matter unless I do another "spyder --reset". Something is wrong with the ipython console setup. I use python as substitute to matlab, so this is as far as I can go. Hope it helps.
I am happy that I have the spyder back up again, but still looking forward for a fix to get ipython console back.

**Comment by ccordoba12** [comment]
This is an installation problem. You need to properly install IPython, qtconsole and Spyder to their latest versions to have everything working correctly.

If you are unsure on how to do that, I suggest you to install [Anaconda](https://www.continuum.io/downloads), which has everything configured for you.
