### ISSUE TITLE
Changing IPython graphics backend to "Qt" will result in error when using Qt5

### ISSUE THREAD

**Issue by yw5aj** [spyder-ide/spyder#2792]
Dear all,

Thanks to @stonebig for catching the bug on discussion at https://groups.google.com/forum/?fromgroups#!topic/winpython/QnSEg4hKxYE

Environment: Win 7 64 bit (I don't think it matters though)
Python 3.4 64 bit
Spyder 3.0.0dev (using Qt5)

How to reproduce:

Open spyder -> Tools -> Preferences -> IPython console -> Graphics -> Change the Backend from "Inline" to "Qt" -> restart spyder -> in the IPython QtConsole, enter `import matplotlib.pyplot as plt`

Error:

```python
In [1]: import matplotlib.pyplot as plt

Traceback (most recent call last):



File "<ipython-input-1-eff513f636fd>", line 1, in <module>

import matplotlib.pyplot as plt



File "X:\WinPython3Qt5\python-3.4.3.amd64\lib\site-packages\matplotlib\pyplot.py", line 114, in <module>

_backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()



File "X:\WinPython3Qt5\python-3.4.3.amd64\lib\site-packages\matplotlib\backends\__init__.py", line 32, in pylab_setup

globals(),locals(),[backend_name],0)



File "X:\WinPython3Qt5\python-3.4.3.amd64\lib\site-packages\matplotlib\backends\backend_qt4agg.py", line 18, in <module>

from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase



File "X:\WinPython3Qt5\python-3.4.3.amd64\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 15, in <module>

from .backend_qt5 import QtCore



File "X:\WinPython3Qt5\python-3.4.3.amd64\lib\site-packages\matplotlib\backends\backend_qt5.py", line 31, in <module>

from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__



File "X:\WinPython3Qt5\python-3.4.3.amd64\lib\site-packages\matplotlib\backends\qt_compat.py", line 124, in <module>

from PyQt4 import QtCore, QtGui



ImportError: No module named 'PyQt4'
```

stonebig pointed out that why this happend:

Doing this change, you get in the"spyder.ini file:
`ets_backend = qt4`

**Comment by ccordoba12** [comment]
@stonebig, what do you think we need to do to fix this problem? Removing the `ets_backend` option?

**Comment by stonebig** [comment]
Hi Carlos,

I don't feel expert on this. 

I would suggest that this option (and current 'Qt4' value), if kept,  should be understood as "use the default Qt", this one being Qt4 or Qt5.

**Comment by ccordoba12** [comment]
So ETS is available for Qt5 too?

**Comment by ccordoba12** [comment]
I think last time I checked it wasn't

**Comment by stonebig** [comment]
What is ETS ?

**Comment by ccordoba12** [comment]
@stonebig, don't worry. I found where the error was (and it wasn't related to ETS = Entought Tool Suite).

**Comment by stonebig** [comment]
great !

**Comment by stonebig** [comment]
hope you will soon do a 3.0.0 beta2 to celebrate this

**Comment by ccordoba12** [comment]
Yep, I only have to solve issue #2748 before releasing it.

**Comment by stonebig** [comment]
(silent hope)
