### ISSUE TITLE
spyder crash with ipython 4.0

### ISSUE THREAD

**Issue by applecool** [spyder-ide/spyder#2799]
I am on Mac OS X 10.11.1 ElCapitan. Whenever I try to run the Spyder, it crashes and shows me the following pop-up window. 
<img width="959" alt="screen shot 2015-11-04 at 1 04 26 pm" src="https://cloud.githubusercontent.com/assets/1661749/10949181/3cf040b8-82f7-11e5-8b85-784527a062fa.png">

I did the reset and tried to re-launch it. Then I get the following stack trace:

```wlan-net173-83:~ ShellZero$ spyder
/Users/ShellZero/anaconda/lib/python2.7/site-packages/IPython/qt.py:13: ShimWarning: The `IPython.qt` package has been deprecated. You should import from qtconsole instead.
  "You should import from qtconsole instead.", ShimWarning)
2015-11-04 13:12:53.386 python[4857:759429] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
Traceback (most recent call last):
  File "/Users/ShellZero/anaconda/lib/python2.7/site-packages/spyderlib/spyder.py", line 2336, in main
    mainwindow = run_spyder(app, options, args)
  File "/Users/ShellZero/anaconda/lib/python2.7/site-packages/spyderlib/spyder.py", line 2220, in run_spyder
    main.setup()
  File "/Users/ShellZero/anaconda/lib/python2.7/site-packages/spyderlib/spyder.py", line 766, in setup
    from spyderlib.plugins.inspector import ObjectInspector
  File "/Users/ShellZero/anaconda/lib/python2.7/site-packages/spyderlib/plugins/inspector.py", line 41, in <module>
    from spyderlib.widgets.ipython import IPythonControlWidget
  File "/Users/ShellZero/anaconda/lib/python2.7/site-packages/spyderlib/widgets/ipython.py", line 28, in <module>
    pygments_patch.apply()
  File "/Users/ShellZero/anaconda/lib/python2.7/site-packages/spyderlib/pygments_patch.py", line 27, in apply
    from IPython.frontend.qt.console.pygments_highlighter import RegexLexer
ImportError: No module named pygments_highlighter```

**Comment by applecool** [comment]
I think this problem was occurring because of the older version of the spyder (2.3.5.2). Just updated spyder to 2.3.7 and other packages by doing
`conda update spyder`

The update fixed the issue. 

Thanks.

**Comment by ccordoba12** [comment]
Fantastic to know!

**Comment by emirshekari** [comment]
conda update anaconda
worked in my case.
