### ISSUE TITLE
Spyder fails to start because of an error with scipy

### ISSUE THREAD

**Issue by weitongwei** [spyder-ide/spyder#2819]
I have anaconda2 installed (python-2.7.10).
Through conda installed mayavi which requires  numpy downgraded:    1.10.1-py27_0 --> 1.9.3-py27_0.

After that, spyder cannot start anymore.

```python-traceback
Traceback (most recent call last):
  File "/opt/anaconda2/bin/spyder", line 2, in <module>
    from spyderlib import start_app
  File "/opt/anaconda2/lib/python2.7/site-packages/spyderlib/start_app.py", line 13, in <module>
    from spyderlib.config import CONF
  File "/opt/anaconda2/lib/python2.7/site-packages/spyderlib/config.py", line 22, in <module>
    from spyderlib.utils import iofuncs, codeanalysis
  File "/opt/anaconda2/lib/python2.7/site-packages/spyderlib/utils/iofuncs.py", line 163, in <module>
    import scipy.io as spio
  File "/opt/anaconda2/lib/python2.7/site-packages/scipy/io/__init__.py", line 85, in <module>
    from .matlab import loadmat, savemat, whosmat, byteordercodes
  File "/opt/anaconda2/lib/python2.7/site-packages/scipy/io/matlab/__init__.py", line 13, in <module>
    from .mio import loadmat, savemat, whosmat
  File "/opt/anaconda2/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 12, in <module>
    from .miobase import get_matfile_version, docfiller
  File "/opt/anaconda2/lib/python2.7/site-packages/scipy/io/matlab/miobase.py", line 22, in <module>
    from scipy.misc import doccer
  File "/opt/anaconda2/lib/python2.7/site-packages/scipy/misc/__init__.py", line 49, in <module>
    from scipy.special import comb, factorial, factorial2, factorialk
  File "/opt/anaconda2/lib/python2.7/site-packages/scipy/special/__init__.py", line 601, in <module>
    from ._ufuncs import *
  File "__init__.pxd", line 155, in init scipy.special._ufuncs (scipy/special/_ufuncs.c:27221)
ValueError: numpy.dtype has the wrong size, try recompiling
```

**Comment by ccordoba12** [comment]
Thanks for reporting. I'll fix this for 2.3.8.
