### ISSUE TITLE
issue importing matplotlib.pyplot with spyder

### ISSUE THREAD

**Issue by jeportillo** [spyder-ide/spyder#2833]
hello - I'm having the following error when importing matplotlib.pyplot from the IPython console or the Python console. It is my first time using Spyder and I'm just learning Python (I'm a 15+ yr experienced Matlab user), but could not find any help for this error on the various sites I visited. Below is a copy paste of the error I get with running this command in the console:

thanks for your help
Enrique

#--------------------------------------------------------

import matplotlib.pyplot
Traceback (most recent call last):

  File "<ipython-input-31-6f467123fe04>", line 1, in <module>
    import matplotlib.pyplot

  File "C:\Users\mami\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 27, in <module>
    import matplotlib.colorbar

  File "C:\Users\mami\Anaconda3\lib\site-packages\matplotlib\colorbar.py", line 34, in <module>
    import matplotlib.collections as collections

  File "C:\Users\mami\Anaconda3\lib\site-packages\matplotlib\collections.py", line 27, in <module>
    import matplotlib.backend_bases as backend_bases

  File "C:\Users\mami\Anaconda3\lib\site-packages\matplotlib\backend_bases.py", line 56, in <module>
    import matplotlib.textpath as textpath

  File "C:\Users\mami\Anaconda3\lib\site-packages\matplotlib\textpath.py", line 19, in <module>
    import matplotlib.font_manager as font_manager

  File "C:\Users\mami\Anaconda3\lib\site-packages\matplotlib\font_manager.py", line 1415, in <module>
    _rebuild()

  File "C:\Users\mami\Anaconda3\lib\site-packages\matplotlib\font_manager.py", line 1400, in _rebuild
    fontManager = FontManager()

  File "C:\Users\mami\Anaconda3\lib\site-packages\matplotlib\font_manager.py", line 1040, in __init__
    self.ttffiles = findSystemFonts(paths) + findSystemFonts()

  File "C:\Users\mami\Anaconda3\lib\site-packages\matplotlib\font_manager.py", line 312, in findSystemFonts
    for f in win32InstalledFonts(fontdir):

  File "C:\Users\mami\Anaconda3\lib\site-packages\matplotlib\font_manager.py", line 231, in win32InstalledFonts
    direc = os.path.abspath(direc).lower()

  File "C:\Users\mami\Anaconda3\lib\ntpath.py", line 535, in abspath
    path = _getfullpathname(path)

ValueError: _getfullpathname: embedded null character

**Comment by ccordoba12** [comment]
@tacaswell, have you seen this error before? I don't know where it could be coming from...

**Comment by tacaswell** [comment]
my guess is that are some non-ascii characters in a font path (see http://stackoverflow.com/questions/33977519/valueerror-embedded-null-character-when-using-open ?) and the encoding is not what ever python is assuming it is. 

@jeportillo Can you try the same thing in an IPython shell and use `%debug` to sort out what value of `direc` is causing the problem?

**Comment by jeportillo** [comment]
Thomas/Carlos -- thanks for your help!

I am printing the value of "direc" before being calling by
"abspath(direc)". Since it is being called inside a for loop, I also
printed the index. Attached is a screenshot of what I get: Basically, the
"BrushSci.tff" file has some characters associated to it during the 246th
iteration.

let me know if you need me to run anything else - thanks again

PS. I'm running on Windows 7

Enrique

**Comment by tacaswell** [comment]
I think this is the same issue reported at http://matplotlib.1069221.n5.nabble.com/Error-on-import-matplotlib-pyplot-on-Anaconda3-for-Windows-10-Home-64-bit-PC-td46477.html

**Comment by tacaswell** [comment]
cpython bug report: https://bugs.python.org/issue25778

SO question: http://stackoverflow.com/questions/34004063/error-on-import-matplotlib-pyplot-on-anaconda3-for-windows-10-home-64-bit-pc/34007642#34007642

**Comment by jeportillo** [comment]
many thanks Thomas -- I added the patch provided in the link you sent out
and was able to make my first ever plot in Python :-)


direc = direc.split('\0', 1)[0]
