### ISSUE TITLE
Spyder doesn't update from 2.2.5

### ISSUE THREAD

**Issue by fchirono** [spyder-ide/spyder#2864]
Hi all. I had a working spyder 2.2.5 install on a Ubuntu 14.04 and decided to upgrade ipython to 4.0.1; this, however, made spyder stop working:

```
fch1g10@fch1g10-DQ77MK:~$ spyder
/usr/local/lib/python2.7/dist-packages/IPython/qt.py:13: ShimWarning: The `IPython.qt` package has been deprecated. You should import from qtconsole instead.
  "You should import from qtconsole instead.", ShimWarning)
/usr/local/lib/python2.7/dist-packages/IPython/frontend.py:21: ShimWarning: The top-level `frontend` package has been deprecated. All its subpackages have been moved to the top `IPython` level.
  "All its subpackages have been moved to the top `IPython` level.", ShimWarning)
Traceback (most recent call last):
  File "/usr/local/bin/spyder", line 3, in <module>
    start_app.main()
  File "/usr/lib/python2.7/dist-packages/spyderlib/start_app.py", line 72, in main
    from spyderlib import spyder
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 106, in <module>
    from spyderlib.plugins.inspector import ObjectInspector
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 39, in <module>
    from spyderlib.widgets.ipython import IPythonControlWidget
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/ipython.py", line 15, in <module>
    from IPython.frontend.qt.console.rich_ipython_widget import RichIPythonWidget
ImportError: No module named rich_ipython_widget
```

Following some previous recommendations to upgrade spyder, however, gave me the following (error?) message:

```
fch1g10@fch1g10-DQ77MK:~$ sudo pip install --upgrade spyder
Downloading/unpacking spyder from https://pypi.python.org/packages/source/s/spyder/spyder-2.3.8.zip#md5=fb890dc956f606c43d560558159f3491
  Downloading spyder-2.3.8.zip (3.0MB): 3.0MB downloaded
  Running setup.py (path:/tmp/pip_build_root/spyder/setup.py) egg_info for package spyder
    
    warning: no files found matching '*.pot' under directory 'spyderlibplugins'
    warning: no files found matching '*.po' under directory 'spyderlibplugins'
    warning: no files found matching '*.svg' under directory 'spyderlibplugins'
    warning: no files found matching '*.png' under directory 'spyderlibplugins'
    warning: no files found matching '*.' under directory 'doc'
    warning: no files found matching '*.bat' under directory 'app_example'
    warning: no files found matching '*.qm' under directory 'app_example'
    warning: no files found matching '*.svg' under directory 'app_example'
    warning: no files found matching '*.png' under directory 'app_example'
    warning: no files found matching 'CHANGELOG'
Installing collected packages: spyder
  Found existing installation: spyder 2.2.5
    Not uninstalling spyder at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for spyder
    changing mode of build/scripts-2.7/spyder_win_post_install.py from 644 to 755
    changing mode of build/scripts-2.7/spyder from 644 to 755
    Running Sphinx v1.2.2
    loading pickled environment... not yet created
    building [html]: targets for 18 source files that are out of date
    updating environment: 18 added, 0 changed, 0 removed
    
    looking for now-outdated files... none found
    pickling environment... done
    checking consistency... done
    preparing documents... done
    
    
    dumping search index... done
    dumping object inventory... done
    build succeeded.
    
    warning: no files found matching '*.pot' under directory 'spyderlibplugins'
    warning: no files found matching '*.po' under directory 'spyderlibplugins'
    warning: no files found matching '*.svg' under directory 'spyderlibplugins'
    warning: no files found matching '*.png' under directory 'spyderlibplugins'
    warning: no files found matching '*.' under directory 'doc'
    warning: no files found matching '*.bat' under directory 'app_example'
    warning: no files found matching '*.qm' under directory 'app_example'
    warning: no files found matching '*.svg' under directory 'app_example'
    warning: no files found matching '*.png' under directory 'app_example'
    warning: no files found matching 'CHANGELOG'
    changing mode of /usr/local/bin/spyder_win_post_install.py to 755
    changing mode of /usr/local/bin/spyder to 755
Successfully installed spyder
Cleaning up...
```

And when I check it using pip freeze, my spyder hasn't been upgraded (still at version 2.2.5). I tried downgraded ipython to 3.2.1 and then spyder works, but trying to upgrade spyder (with the downgraded ipython) still fails and gives me the same message as above. Any ideas on what's going on?

**Comment by ccordoba12** [comment]
I think you need to install `qtconsole` to fix this problem.

**Comment by ccordoba12** [comment]
Closing because of lack of response.

**Comment by fchirono** [comment]
Hi. Thanks for your reply, and apologies for the delay in responding; I was on holidays and thus away from my work pc.

qtconsole 4.1.1 is already installed, and seems to be the latest version.

**Comment by ccordoba12** [comment]
You need to update Spdyer too, at least to version 2.3.6, which was the first one to support IPython/qtconsole 4.

Spyder 2.2.5 is way too old to support the newest IPython.

**Comment by ccordoba12** [comment]
Sorry, I just saw that you updated Spyder too. There's no error in your installation message.

Did you try to use it after that? If so, what's the error reported in the console?

**Comment by fchirono** [comment]
I tried to upgrade Spyder, but it gives me the same message as described above and it doesn't work; pip freeze still says it is version 2.2.5. Trying to run Spyder with the newest IPython (4.0.1) gives me the same error message as reported above as well.

Funny enough, I am pretty sure two weeks ago (when I opened the issue) I managed to make Spyder work once I downgraded IPython to 3.2.1, but when doing that now Spyder starts but doesn't open a Python (or IPython) console. Perhaps it's easier if I simply reinstall everything?

**Comment by ccordoba12** [comment]
> pip freeze still says it is version 2.2.5

if you installed 2.2.5 with `apt-get`, `pip` can't remove it. So you need to uninstall it using `apt-get` too, and then pip can do it's magic :-)

> Perhaps it's easier if I simply reinstall everything?

I think it's the best thing to do :-)

**Comment by fchirono** [comment]
> if you installed 2.2.5 with apt-get, pip can't remove it. So you need to uninstall it using apt-get too, 
> and then pip can do it's magic :-)

Yeah, removing and reinstalling everything with `pip` did the trick :) As you said, there was probably a conflict between `apt-get` and `pip` over the permissions, and this solved the issue. Thanks a lot for the help!
