### ISSUE TITLE
pep8.py: AttributeError: 'module' object has no attribute 'getmodule'

### ISSUE THREAD

**Issue by bmer** [spyder-ide/spyder#2916]
When starting Spyder, I get the following error:

```
Traceback (most recent call last):
  File "A:\anaconda2\Scripts\spyder-script.py", line 1, in <module>
    from spyderlib import start_app
  File "A:\anaconda2\lib\site-packages\spyderlib\start_app.py", line 13, in <module>
    from spyderlib.config import CONF
  File "A:\anaconda2\lib\site-packages\spyderlib\config.py", line 22, in <module>
    from spyderlib.utils import iofuncs, codeanalysis
  File "A:\anaconda2\lib\site-packages\spyderlib\utils\codeanalysis.py", line 97, in <module>
    required_version=PEP8_REQVER)
  File "A:\anaconda2\lib\site-packages\spyderlib\dependencies.py", line 70, in add
    installed_version)]
  File "A:\anaconda2\lib\site-packages\spyderlib\dependencies.py", line 32, in __init__
    self.installed_version = programs.get_module_version(modname)
  File "A:\anaconda2\lib\site-packages\spyderlib\utils\programs.py", line 238, in get_module_version
    mod = __import__(module_name)
  File "A:\anaconda2\lib\site-packages\pep8.py", line 1343, in <module>
    init_checks_registry()
  File "A:\anaconda2\lib\site-packages\pep8.py", line 1340, in init_checks_registry
    mod = inspect.getmodule(register_check)
AttributeError: 'module' object has no attribute 'getmodule'
```

Why might this be happening? I am on Windows 10, and I have Spyder installed through Anaconda.

**Comment by ccordoba12** [comment]
What's your pep8 version?

**Comment by ccordoba12** [comment]
Closing because of lack of response.
