### ISSUE TITLE
Variable explorer can't show Pandas objects containing timezone aware columns

### ISSUE THREAD

**Issue by iyer** [spyder-ide/spyder#2940]
I'm encountering an issue with spyder 2.3.8 when printing pandas objects (Series, DataFrame) that have columns containing timezone aware timestamps. I cannot view the object in a viewer.

Key things to note
1) This has happens only in pandas 0.17.0 or greater and may relate to the following http://pandas.pydata.org/pandas-docs/version/0.17.1/whatsnew.html#whatsnew-0170-tz

2) This only happens when the column is timezone aware

```python

import pandas as pd

# causes an issue when we try to open s in Variable explorer
s = pd.Series(pd.date_range('20150101', periods=5, tz='UTC'))

# no issue when we try to open s in Variable explorer
s = pd.Series(pd.date_range('20150101', periods=5))

```

Below is the error I get

``` python

Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> /export/data/anaconda/anaconda3.2.4/lib/python3.5/site-packages/nbformat/current.py:19: UserWarning: nbformat.current is deprecated.

- use nbformat for read/write/validate public API
- use nbformat.vX directly to composing notebooks of a particular version

  """)
Traceback (most recent call last):
  File "/export/data/anaconda/anaconda3.2.4/lib/python3.5/site-packages/spyderlib/widgets/dicteditor.py", line 503, in createEditor
    if not editor.setup_and_check(value, title=key):
  File "/export/data/anaconda/anaconda3.2.4/lib/python3.5/site-packages/spyderlib/widgets/dataframeeditor.py", line 497, in setup_and_check
    self.dataModel = DataFrameModel(data, parent=self)
  File "/export/data/anaconda/anaconda3.2.4/lib/python3.5/site-packages/spyderlib/widgets/dataframeeditor.py", line 90, in __init__
    self.max_min_col_update()
  File "/export/data/anaconda/anaconda3.2.4/lib/python3.5/site-packages/spyderlib/widgets/dataframeeditor.py", line 124, in max_min_col_update
    float_intran = self.df.applymap(lambda e: isinstance(e, _sup_nr))
  File "/export/data/anaconda/anaconda3.2.4/lib/python3.5/site-packages/pandas/core/frame.py", line 4143, in applymap
    return self.apply(infer)
  File "/export/data/anaconda/anaconda3.2.4/lib/python3.5/site-packages/pandas/core/frame.py", line 3972, in apply
    return self._apply_standard(f, axis, reduce=reduce)
  File "/export/data/anaconda/anaconda3.2.4/lib/python3.5/site-packages/pandas/core/frame.py", line 4019, in _apply_standard
    empty_arr = np.empty(len(index), dtype=values.dtype)
TypeError: data type not understood
Traceback (most recent call last):
  File "/export/data/anaconda/anaconda3.2.4/lib/python3.5/site-packages/spyderlib/widgets/dicteditor.py", line 503, in createEditor
    if not editor.setup_and_check(value, title=key):
  File "/export/data/anaconda/anaconda3.2.4/lib/python3.5/site-packages/spyderlib/widgets/dataframeeditor.py", line 497, in setup_and_check
    self.dataModel = DataFrameModel(data, parent=self)
  File "/export/data/anaconda/anaconda3.2.4/lib/python3.5/site-packages/spyderlib/widgets/dataframeeditor.py", line 90, in __init__
    self.max_min_col_update()
  File "/export/data/anaconda/anaconda3.2.4/lib/python3.5/site-packages/spyderlib/widgets/dataframeeditor.py", line 124, in max_min_col_update
    float_intran = self.df.applymap(lambda e: isinstance(e, _sup_nr))
  File "/export/data/anaconda/anaconda3.2.4/lib/python3.5/site-packages/pandas/core/frame.py", line 4143, in applymap
    return self.apply(infer)
  File "/export/data/anaconda/anaconda3.2.4/lib/python3.5/site-packages/pandas/core/frame.py", line 3972, in apply
    return self._apply_standard(f, axis, reduce=reduce)
  File "/export/data/anaconda/anaconda3.2.4/lib/python3.5/site-packages/pandas/core/frame.py", line 4019, in _apply_standard
    empty_arr = np.empty(len(index), dtype=values.dtype)
TypeError: data type not understood
3

```

I am using Python 3.5/pandas/spyder packaged in anaconda 3.2.4

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at it to see what's happening.
