### ISSUE TITLE
Spyder3.0.0dev crashing on startup

### ISSUE THREAD

**Issue by malfatti** [spyder-ide/spyder#2999]
## Description of the problem

After `git clone`, running `python bootstrap.py` results in crash.

**What steps will reproduce the problem?**

1. `git clone`, `cd spyder`
2. `python bootstrap.py`

**What is the expected output? What do you see instead?**
Open spyder; instead, spyder crashes

**Please provide any additional information below**

Python 3.5:
```bash
$ python3.5 bootstrap.py 
Executing Spyder from source checkout
Revision abaf8a0, Branch: master
01. Patched sys.path with /home/malfatti/NotSynced/SoftwareTest/spyder
02. PyQt5 is detected, selecting
03. Imported Spyder 3.0.0dev
    [Python 3.5.1 64bits, Qt 5.4.2, PyQt5 5.5 on Linux]
04. Running Spyder
Bootstrap completed in 00:00:00.4902
Unhandled Python exception
Aborted
```
Python 3.4:
```bash
$ python3.4 bootstrap.py
Executing Spyder from source checkout
Revision abaf8a0, Branch: master
01. Patched sys.path with /home/malfatti/NotSynced/SoftwareTest/spyder
02. PyQt5 is detected, selecting
03. Imported Spyder 3.0.0dev
    [Python 3.4.3 64bits, Qt 5.4.2, PyQt5 5.5 on Linux]
04. Running Spyder
Bootstrap completed in 00:00:00.6927
Unhandled Python exception
Aborted
```
Python 2.7:
```bash
$ python2.7 bootstrap.py 
Executing Spyder from source checkout
Revision abaf8a0, Branch: master
01. Patched sys.path with /home/malfatti/NotSynced/SoftwareTest/spyder
02. PyQt5 is detected, selecting
03. Imported Spyder 3.0.0dev
    [Python 2.7.11 64bits, Qt 5.4.2, PyQt5 5.5 on Linux]
04. Running Spyder
Bootstrap completed in 00:00:00.3920
Traceback (most recent call last):
  File "/home/malfatti/NotSynced/SoftwareTest/spyder/spyderlib/widgets/variableexplorer/namespacebrowser.py", line 282, in toggle_auto_refresh
    "set_monitor_auto_refresh(%r)" % state)
  File "/home/malfatti/NotSynced/SoftwareTest/spyder/spyderlib/utils/bsdsocket.py", line 104, in communicate
    write_packet(sock, command)
  File "/home/malfatti/NotSynced/SoftwareTest/spyder/spyderlib/utils/bsdsocket.py", line 51, in write_packet
    nsend -= temp_fail_retry(socket.error, sock.send, sent_data)
  File "/home/malfatti/NotSynced/SoftwareTest/spyder/spyderlib/utils/bsdsocket.py", line 31, in temp_fail_retry
    return fun(*args)
socket.error: [Errno 32] Broken pipe
Aborted
```

If spyder is started with `--gui pyqt`, then it starts but IPython kernel dies:
```python
>>> Traceback (most recent call last):
  File "/home/malfatti/NotSynced/SoftwareTest/spyder/spyderlib/widgets/variableexplorer/namespacebrowser.py", line 282, in toggle_auto_refresh
    "set_monitor_auto_refresh(%r)" % state)
  File "/home/malfatti/NotSynced/SoftwareTest/spyder/spyderlib/utils/bsdsocket.py", line 104, in communicate
    write_packet(sock, command)
  File "/home/malfatti/NotSynced/SoftwareTest/spyder/spyderlib/utils/bsdsocket.py", line 51, in write_packet
    nsend -= temp_fail_retry(socket.error, sock.send, sent_data)
  File "/home/malfatti/NotSynced/SoftwareTest/spyder/spyderlib/utils/bsdsocket.py", line 31, in temp_fail_retry
    return fun(*args)
BrokenPipeError: [Errno 32] Broken pipe
WARNING:root:kernel died: 3.0020015239715576
```
for any python version.

I can `import IPython; IPython.start_ipython()` from a console, but it is not as functional as an IPython console.

## Versions and main components

* Spyder Version: Spyder 3.0.0dev
* Python Version:  2.7, 3.4 and 3.5
* Operating system: Gentoo 

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
nbconvert >=4.0    :  4.1.0 (OK)
numpy >=1.7        :  1.10.4 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
pep8 >=0.6         :  1.7.0 (OK)
psutil >=0.3       :  3.4.2 (OK)
pyflakes >=0.6.0   :  0.8.1 (OK)
pygments >=1.6     :  2.1.1 (OK)
pylint >=0.25      :  1.5.4 (OK)
qtconsole >=4.0    :  4.1.1 (OK)
rope >=0.9.4       :  None (NOK)
sphinx >=0.6.6     :  1.3.5 (OK)
sympy >=0.7.3      :  None (NOK)

Box:
```bash
$ uname -a
Linux MalfattiTux 4.1.15-gentoo-r1 #1 SMP PREEMPT Thu Feb 18 13:06:37 BRST 2016 x86_64 Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz GenuineIntel GNU/Linux
```
Python (all compiled w/ support to 2.7, 3.4 and 3.5):
```bash
$ equery list python jedi jupyter matplotlib nbconvert numpy pandas pep8 pickleshare psutil pyflakes pygments pylint PyQt4 PyQt5 qtconsole rope sphinx
[IP-] [  ] dev-lang/python-2.7.11-r2:2.7
[IP-] [  ] dev-lang/python-3.4.3-r7:3.4/3.4m
[IP-] [  ] dev-lang/python-3.5.1-r2:3.5/3.5m
[IP-] [  ] dev-python/jedi-0.9.0:0
[IP-] [  ] dev-python/jupyter-1.0.0:0
[IP-] [  ] dev-python/matplotlib-1.5.1:0
[IP-] [  ] dev-python/nbconvert-4.1.0:0
[IP-] [  ] dev-python/numpy-1.10.4:0
[IP-] [  ] dev-python/pandas-0.17.1:0
[IP-] [  ] dev-python/pep8-1.7.0:0
[IP-] [  ] dev-python/pickleshare-0.6:0
[IP-] [  ] dev-python/psutil-3.4.2:0
[IP-] [  ] dev-python/pyflakes-0.8.1:0
[IP-] [  ] dev-python/pygments-2.1.1:0
[IP-] [  ] dev-python/pylint-1.5.4:0
[IP-] [  ] dev-python/PyQt4-4.11.4:0
[IP-] [  ] dev-python/PyQt5-5.5:0
[IP-] [  ] dev-python/qtconsole-4.1.1:0
[IP-] [  ] dev-python/rope-0.10.3:0
[IP-] [  ] dev-python/sphinx-1.3.5:0

$ pip freeze | grep -i qtawesome
QtAwesome==0.2.0
```

**Comment by malfatti** [comment]
Just to complement: after downgrading colorama (#2984 ) the python3.4 error log becames exactly like the one with python3.5.

**Comment by malfatti** [comment]
If spyder is started with `--gui pyqt`, then it starts but IPython kernel dies:
```python
>>> Traceback (most recent call last):
  File "/home/malfatti/NotSynced/SoftwareTest/spyder/spyderlib/widgets/variableexplorer/namespacebrowser.py", line 282, in toggle_auto_refresh
    "set_monitor_auto_refresh(%r)" % state)
  File "/home/malfatti/NotSynced/SoftwareTest/spyder/spyderlib/utils/bsdsocket.py", line 104, in communicate
    write_packet(sock, command)
  File "/home/malfatti/NotSynced/SoftwareTest/spyder/spyderlib/utils/bsdsocket.py", line 51, in write_packet
    nsend -= temp_fail_retry(socket.error, sock.send, sent_data)
  File "/home/malfatti/NotSynced/SoftwareTest/spyder/spyderlib/utils/bsdsocket.py", line 31, in temp_fail_retry
    return fun(*args)
BrokenPipeError: [Errno 32] Broken pipe
WARNING:root:kernel died: 3.0020015239715576
```
for any python version.

I can `import IPython; IPython.start_ipython()` from a console, but it is not as functional as an IPython console.

**Comment by ccordoba12** [comment]
There is a mismatch between your Qt5 and PyQt5 versions, as it can be seen in these lines:

    03. Imported Spyder 3.0.0dev
    [Python 3.5.1 64bits, Qt 5.4.2, PyQt5 5.5 on Linux]

So either you need to install PyQt5 **5.4** or Qt5 **5.5**.

Maybe that's causing your problem.

**Comment by malfatti** [comment]
Hey! Thanks for the response!
I tried, but no change :(

```bash
$ python bootstrap.py
Executing Spyder from source checkout
Revision abaf8a0, Branch: master
01. Patched sys.path with /home/malfatti/NotSynced/SoftwareTest/spyder
02. PyQt5 is detected, selecting
03. Imported Spyder 3.0.0dev
    [Python 3.5.1 64bits, Qt 5.5.1, PyQt5 5.5.1 on Linux]
04. Running Spyder
Bootstrap completed in 00:00:00.4805
Unhandled Python exception
Aborted
```
using PyQt4, it starts but IPython dies:
```bash
$ python bootstrap.py --gui pyqt
Executing Spyder from source checkout
Revision abaf8a0, Branch: master
01. Patched sys.path with /home/malfatti/NotSynced/SoftwareTest/spyder
02. Skipping GUI toolkit detection
03. Imported Spyder 3.0.0dev
    [Python 3.5.1 64bits, Qt 4.8.6, PyQt4 (API v2) 4.11.4 on Linux]
04. Running Spyder
Bootstrap completed in 00:00:00.5132
```
```python
>>> Traceback (most recent call last):
  File "/home/malfatti/NotSynced/SoftwareTest/spyder/spyderlib/widgets/variableexplorer/namespacebrowser.py", line 282, in toggle_auto_refresh
    "set_monitor_auto_refresh(%r)" % state)
  File "/home/malfatti/NotSynced/SoftwareTest/spyder/spyderlib/utils/bsdsocket.py", line 104, in communicate
    write_packet(sock, command)
  File "/home/malfatti/NotSynced/SoftwareTest/spyder/spyderlib/utils/bsdsocket.py", line 51, in write_packet
    nsend -= temp_fail_retry(socket.error, sock.send, sent_data)
  File "/home/malfatti/NotSynced/SoftwareTest/spyder/spyderlib/utils/bsdsocket.py", line 31, in temp_fail_retry
    return fun(*args)
BrokenPipeError: [Errno 32] Broken pipe
WARNING:root:kernel died: 3.0020878314971924
WARNING:root:kernel died: 3.00211501121521
WARNING:root:kernel died: 3.0021169185638428
WARNING:root:kernel died: 3.0020461082458496
...
```
:(

**Comment by ccordoba12** [comment]
No idea them sorry...

**Comment by malfatti** [comment]
If anyone has the same problem, I just upgraded zeromq and everything is magically solved now :)

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know about it.
