### ISSUE TITLE
Spyder crashes on Mac 10.11.2 

### ISSUE THREAD

**Issue by rousseau** [spyder-ide/spyder#3025]
## Description of your problem

**What steps will reproduce the problem?**

1. Spyder is installed through MacPorts

**What is the expected output? What do you see instead?**

Spyder is crashing when opening

**Please provide any additional information below**

Message from command line : 
2016-03-03 10:50:44.125 Python[83875:155440741] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 2331, in main
    mainwindow = run_spyder(app, options, args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 2215, in run_spyder
    main.setup()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 734, in setup
    message=_("Spyder Internal Console\n\n"
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/plugins/console.py", line 74, in __init__
    self.find_widget.set_editor(self.shell)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/findreplace.py", line 260, in set_editor
    from spyderlib.qt.QtWebKit import QWebView
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/qt/QtWebKit.py", line 10, in <module>
    from PyQt4.QtWebKit import *  # analysis:ignore
ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyQt4/QtWebKit.so, 2): Symbol not found: _SSLv2_client_method
  Referenced from: /opt/local/libexec/qt4/Library/Frameworks/QtNetwork.framework/Versions/4/QtNetwork
  Expected in: /opt/local/lib/libssl.1.0.0.dylib
 in /opt/local/libexec/qt4/Library/Frameworks/QtNetwork.framework/Versions/4/QtNetwork

## Versions and main components

* Spyder Version: 2.3.8
* Python Version: 2.7.11
* Operating system: Mac El Capitan 10.11.2

**Comment by ccordoba12** [comment]
This is problem with how Qt4 was compiled in MacPorts, and not with Spyder itself. I say it because of this part in your error message:

> ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyQt4/QtWebKit.so, 2): Symbol not found: _SSLv2_client_method 

So please open an issue in the MacPorts issue tracker instead :-)
