### ISSUE TITLE
RuntimeError: Please define environment variable $HOME

### ISSUE THREAD

**Issue by picca** [spyder-ide/spyder#3046]
Hello, AS I am packaging a software which use spyder, I get this error message

/«BUILDDIR»/taurus-3.7.0+dfsg/doc/source/devel/api/taurus/qt/qtgui/editor.rst:8: WARNING: autodoc: failed to import module u'taurus.qt.qtgui.editor'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    **import**(self.modname)
  File "/«BUILDDIR»/taurus-3.7.0+dfsg/lib/taurus/qt/qtgui/editor/**init**.py", line 30, in <module>
    from .tauruseditor import *
  File "/«BUILDDIR»/taurus-3.7.0+dfsg/lib/taurus/qt/qtgui/editor/tauruseditor.py", line 46, in <module>
    from spyderlib.utils.qthelpers import create_toolbutton
  File "/usr/lib/python2.7/dist-packages/spyderlib/utils/qthelpers.py", line 24, in <module>
    from spyderlib.guiconfig import get_shortcut
  File "/usr/lib/python2.7/dist-packages/spyderlib/guiconfig.py", line 22, in <module>
    from spyderlib.config import CONF
  File "/usr/lib/python2.7/dist-packages/spyderlib/config.py", line 736, in <module>
    subfolder=SUBFOLDER, backup=True, raw_mode=True)
  File "/usr/lib/python2.7/dist-packages/spyderlib/userconfig.py", line 207, in **init**
    fname = self.filename()
  File "/usr/lib/python2.7/dist-packages/spyderlib/userconfig.py", line 143, in filename
    folder = get_home_dir()
  File "/usr/lib/python2.7/dist-packages/spyderlib/baseconfig.py", line 98, in get_home_dir
    raise RuntimeError('Please define environment variable $HOME')
RuntimeError: Please define environment variable $HOME

this is spyder 2.3.8

It seems to me that spyder should work even if the HOME env was not set.

Indeed this is during a chroot build, so it is a little bit weard :)

Cheers

Fred

**Comment by ccordoba12** [comment]
@picca, Spyder needs $HOME to save its configuration settings. I don't know how to help you because I don't understand how Spyder is used as a library by the project you're packaging.

However, you're welcome to send us a pull request that improves the situation for you.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
