### ISSUE TITLE
Can't start an IPython kernel, calling code from the wrong spyder install

### ISSUE THREAD

**Issue by joshburnett** [spyder-ide/spyder#3047]
## Can't start an IPython kernel, calling code from the wrong spyder install
Trying to run the dev version of Spyder.  I have Spyder 2.3.8 installed as well, via a fresh install today of Anaconda 2.5.0.  Using the dev version, Spyder launches successfully, but gives an error when trying to connect to the IPython kernel:

	Traceback (most recent call last):
	File "C:\Users\usplmujbu\Dropbox\code\spyder‑master\spyderlib\widgets\externalshell\start_ipython_kernel.py", line 189, in 
	ipk_temp.config = kernel_config()
	File "C:\Users\usplmujbu\Dropbox\code\spyder‑master\spyderlib\widgets\externalshell\start_ipython_kernel.py", line 36, in kernel_config
	from spyderlib.config.main import CONF
	ImportError: No module named main

It looks like it's loading the spyderlib associated with the Spyder 2.3.8 install, despite saying that it's patched sys.path with the path to the dev Spyder.

If I go to line 36 of start_ipython_kernel.py and insert a `print sys.path` I do not see the dev Spyder path in the list.  Additionally, if I insert `import spyderlib` and `print spyderlib.__file__` there it shows that it is indeed pointing to `C:\Anaconda2\lib\site‑packages\spyderlib\__init__.pyc`.

## Versions and main components

* Spyder Version: 3.0.0dev
* Python Version: Python 2.7.11 |Anaconda 2.5.0 (64-bit)| (default, Jan 29 2016, 14:26:21) [MSC v.1500 64 bit (AMD64)] on win32
* Operating system: Windows 7

## Dependencies

jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.5.1 (OK)
nbconvert >=4.0 :  4.1.0 (OK)
numpy >=1.7     :  1.10.4 (OK)
pandas >=0.13.1 :  0.17.1 (OK)
pep8 >=0.6      :  1.7.0 (OK)
pyflakes >=0.5.0:  1.0.0 (OK)
pygments >=1.6  :  2.1 (OK)
pylint >=0.25   :  1.5.4 (OK)
qtconsole >=4.0 :  4.1.1 (OK)
rope >=0.9.4    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.3.5 (OK)
sympy >=0.7.3   :  0.7.6.1 (OK)

**Comment by joshburnett** [comment]
Update: I uninstalled Anaconda 2.5.0 entirely, and then reinstalled Anaconda 2.4.1, since I had the installer still lying around.  I can run the dev version of Spyder now, so it must have been something in the Anaconda installation.
