### ISSUE TITLE
Spyder 2.0.0alpha5 pylint tab/window will not open on Win7 x64

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#307]
_From [osborne....@gmail.com](https://code.google.com/u/101753710418958586736/) on 2010-08-23T02:37:44Z_

What steps will reproduce the problem?

 1. On Windows 7 (x64), install Spyder 2.0.0alpha5 and required software.

2. Open Spyder, create a project, load a source file

3. Try to do a pylint code analysis

What is the expected output?
I expected to be able to "Run pylint code analysis" with the "Source" menu or by pressing F8.

What do you see instead?
Neither the menu item nor F8 work.  The menu item is grayed out. What version of the product are you using? On what operating system? spyder-2.0.0alpha5-py2.6 (installed using hg clone https://spyderlib.googlecode.com/hg/ )
on Win7x64.
Also Installed are:
Python 2.6.5
PyQT4 v4.7.3 (packaged with QTScintilla2)
pylint-0.21.1-py2.6 (easy_installed)
rope-0.9.2 (using python setup.py install)
pyflakes-0.4.0-py2.6 (easy_installed)
Nb: I do not use the Python X,Y package, but rather create my own software configuration. 

Please provide any additional information below

. I tried adding Spyder and Pylint directories to the Windows PATH system environment variable to see if this helps, but it still does not work.
I also noticed that these features work fine on my Ubuntu 32 bit installation of Spyder.  I've reproduced this problem on 3 different computers that run Win7 x64.  This appears to be a Windows specific problem.

**Attachment:** [Spyder 2.0.0alpha5 Pylint problem on Win7x64.jpg](http://code.google.com/p/spyderlib/issues/detail?id=307)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=307_

**Comment by spyder-issues-migrator** [comment]
_From [osborne....@gmail.com](https://code.google.com/u/101753710418958586736/) on 2010-08-23T00:42:08Z_

I forgot to mention:
The pylint window still does appear when you select "View"-"Pylint" from the menu. So the window itself kinda works. However it is not focused on the currently open file (you have to browse to the file).

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-08-24T04:55:21Z_

Please try the following:
  - open a command window (cmd.exe)
  - type 'pylint'
This should show pylint help.

**Comment by spyder-issues-migrator** [comment]
_From [osborne....@gmail.com](https://code.google.com/u/101753710418958586736/) on 2010-08-24T05:57:35Z_

Hi Perre,
Thanks for the feedback.  I get the standard pylint help output when I type 'pylint'.  The attached picture shows a screenshot of my Win7x64 terminal beside a screenshot of my Ubuntu32bit computer's terminal.  Both terminals show the same output after typing 'pylint'.  As I mentioned in my first post, the Ubuntu computer has no problem (i.e. the Pylint menu item in Spyder is not grayed out & works fine on Ubuntu).  It looks like its Windows that has the problem.

**Attachment:** [Spyder 2.0.0alpha5 Pylint problem on Win7x64 - pic 2.jpg](http://code.google.com/p/spyderlib/issues/detail?id=307#hc4)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-08-24T06:06:07Z_

Could you please check if the Python scripts directory is in your PATH environment variable?
(C:\Python26\Scripts)

**Comment by spyder-issues-migrator** [comment]
_From [osborne....@gmail.com](https://code.google.com/u/101753710418958586736/) on 2010-08-24T06:22:16Z_

Yes, it's in my PATH variable.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-08-24T10:09:21Z_

That's weird. I've never seen this bug (pylint plugin is mature for at least a year now). 
Could you please post a screenshot of the pylint dock window? (which is not working but you are able to show it anyway as you wrote earlier)

**Comment by spyder-issues-migrator** [comment]
_From [osborne....@gmail.com](https://code.google.com/u/101753710418958586736/) on 2010-08-24T21:55:19Z_

Hi,
Here's a screenshot of the pylint dock window. I had to enter the path manually.  But the dock window works after that.  The pylint menu item is still grayed out.
Daniel

**Attachment:** [Spyder 2.0.0alpha5 Pylint problem on Win7x64 - pic 3.jpg](http://code.google.com/p/spyderlib/issues/detail?id=307#hc8)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-08-25T09:46:40Z_

In a python interpreter, could you please type the following:
from spyderlib.widgets import pylint
print pylint.PYLINT_PATH

And also this:
import os
print os.environ["PATH"]

These tests should help me understand the situation.

**Comment by spyder-issues-migrator** [comment]
_From [osborne....@gmail.com](https://code.google.com/u/101753710418958586736/) on 2010-08-25T12:56:56Z_

The result was:
Python 2.6.5 ( r265 :79096, Mar 19 2010, 21:48:26) [MSC v.1500 32 bit (Intel)] on
win32
Type "help", "copyright", "credits" or "license" for more information.
\>>> from spyderlib.widgets import pylint
Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
ImportError: cannot import name pylint
\>>> print pylint.PYLINT_PATH
Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
NameError: name 'pylint' is not defined
\>>> import os
\>>> print os.environ["PATH"]
C:\Python26\Lib\site-packages\PyQt4\bin;c:\Program Files (x86)\NVIDIA Corporatio
n\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Window
s\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common Files\Acronis\S
napAPI\;c:\cygwin\bin;C:\Program Files (x86)\vim\vim72;C:\Python26;C:\Python26\S
cripts;C:\Python26\Lib\site-packages\ipython-0.10-py2.6.egg\IPython\gui\wx;C:\Pr
ogram Files\Windows NT\Accessories;C:\Program Files (x86)\Java\jdk1.6.0_20\bin;C
:\Program Files (x86)\TortoiseSVN\bin;C:\Program Files\TortoiseSVN\bin;C:\Progra
m Files (x86)\TortoiseHg\;C:\Python26\Lib\site-packages\spyder-2.0.0alpha5-py2.6
.egg\spyderlib\;C:\Python26\Lib\site-packages\pylint-0.21.1-py2.6.egg\pylint;C:\
Program Files (x86)\Acronis\BackupAndRecovery\;C:\Program Files (x86)\OpenVPN\bi
n
\>>>

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-08-26T11:16:53Z_

Sorry, I made a mistake in my last comment.
In a python interpreter, could you please type the following:
from spyderlib.widgets import pylintgui
print repr(pylintgui.PYLINT_PATH)

thx

**Comment by spyder-issues-migrator** [comment]
_From [osborne....@gmail.com](https://code.google.com/u/101753710418958586736/) on 2010-08-27T01:07:48Z_

Hi, here's what happened:
C:\Users\daniel>python
Python 2.6.5 ( r265 :79096, Mar 19 2010, 21:48:26) [MSC v.1500 32 bit (Intel)] on
win32
Type "help", "copyright", "credits" or "license" for more information.
\>>> from spyderlib.widgets import pylintgui
\>>> print repr(pylintgui.PYLINT_PATH)
'pylint.bat'
\>>>

**Comment by spyder-issues-migrator** [comment]
_From [osborne....@gmail.com](https://code.google.com/u/101753710418958586736/) on 2010-09-07T10:00:28Z_

Hi Pierre,
I've just updated to Beta 1.  It looks good.  The pylint problem (no F8 or menu command available) remains in the windows version on my PC. I was just wondering if you had gotten any further with this?
All the best,
Daniel

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-09-07T10:41:10Z_

Actually no because I'm still unable to reproduce this bug.

To make progress on this issue, we would have to debug the function 'is_program_installed' located in spyderlib/utils/programs.py.

This function should return True when passing 'pylint.bat' as argument. In your case, it appears like it's returning False... but why?

I don't understand why because your os.environ['PATH'] contains the C:\Python26\Scripts directory which itself contains 'pylint.bat' (correct me if I'm wrong).

**Comment by spyder-issues-migrator** [comment]
_From [osborne....@gmail.com](https://code.google.com/u/101753710418958586736/) on 2010-09-07T11:49:06Z_

Hi,
I found a fix. I installed winpdb on my windows machine and suddenly the pylint F8 and menu command works.  I had winpdb installed on my linux machines already.
Daniel

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-09-08T05:33:57Z_

That's it! I found out where it comes from: this last hint was very useful to find this ugly bug. 

I'll fix this very soon.

**Status:** Accepted

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-17T13:05:34Z_

**Status:** Fixed
