### ISSUE TITLE
spyder, anaconda, python35, module bs4 has no attribute element

### ISSUE THREAD

**Issue by liubenyuan** [spyder-ide/spyder#3089]
## Spyder failed to start after install `beautifulsoup-4.4.1` using anaconda

Similar issue #1910 

**What steps will reproduce the problem?**

1. install anaconda
2. install `beautifulsoup-4.4.1` using `conda.exe install beautifulsoup4` in `python-3.5` environment, and remove `beautiful-soup 4.3.2` which do not support python 3.5
3. run `spyder.exe --reset` or `python bootstrap.py`

**What is the expected output? What do you see instead?**

```bash
Bootstrap completed in 00:00:01.6720
Traceback (most recent call last):
  File "bootstrap.py", line 162, in <module>
    start.main()
  File "C:\cem\github\spyder\spyderlib\app\start.py", line 118, in main
    from spyderlib.app import spyder
  File "C:\cem\github\spyder\spyderlib\app\spyder.py", line 148, in <module>
    from spyderlib.utils.environ import WinUserEnvDialog
  File "C:\cem\github\spyder\spyderlib\utils\environ.py", line 18, in <module>
    from spyderlib.widgets.variableexplorer.collectionseditor import CollectionsEditor
  File "C:\cem\github\spyder\spyderlib\widgets\variableexplorer\collectionseditor.py", line 42, in <module>
    from spyderlib.widgets.variableexplorer.utils import (sort_against, get_size,
  File "C:\cem\github\spyder\spyderlib\widgets\variableexplorer\utils.py", line 100, in <module>
    NavigableString = bs4.element.NavigableString
AttributeError: module 'bs4' has no attribute 'element'
```

When I open ipython console, and type
```python
import bs4 # ok !
import bs4.element # fail
```

**Please provide any additional information below**

## Versions and main components

* Spyder Version: spyder-git, spyder 2.3.8, spyder 3.0.0b2
* Python Version: python-3.5
* Operating system: windows 10 x64

## Dependencies

Spyder failed to run.

**Comment by liubenyuan** [comment]
This can be solved by
```bash
conda.exe remove beautiful-soup beautifulsoup4 qtawesome pyqt
conda.exe update anaconda
```

close this issue
