### ISSUE TITLE
Spyder locking up Windows 7

### ISSUE THREAD

**Issue by Will282** [spyder-ide/spyder#3097]
## Description of your problem

Please run the following code in a Spyder Python/iPython console:
```python
a = ['test','\xb1']
for value in a:
    print 'test'
```
Expected output is for the code to print 'test' twice. 

Instead Spyder locks up. On the "pythonw.exe is not responding" dialog box it allows windows to try and restore the program. On doing this, Spyder gives the following error:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 569, in run
    self.update_remote_view()
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 450, in update_remote_view
    remote_view = make_remote_view(ns, settings, more_excluded_names)
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 79, in make_remote_view
    minmax=settings['minmax'])
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\dicteditorutils.py", line 225, in value_to_display
    return display
UnboundLocalError: local variable 'display' referenced before assignment

When trying to use this console again, an internal console error appears:

Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\pythonshell.py", line 575, in send_to_process
    "toggle_inputhook_flag(True)")
  File "C:\Anaconda2\lib\site-packages\spyderlib\utils\bsdsocket.py", line 104, in communicate
    write_packet(sock, command)
  File "C:\Anaconda2\lib\site-packages\spyderlib\utils\bsdsocket.py", line 51, in write_packet
    nsend -= temp_fail_retry(socket.error, sock.send, sent_data)
  File "C:\Anaconda2\lib\site-packages\spyderlib\utils\bsdsocket.py", line 31, in temp_fail_retry
    return fun(*args)
socket.error: [Errno 10054] An existing connection was forcibly closed by the remote host

## Versions and main components

* Spyder Version: 2.3.8
* Python Version: 2.7.11 64 bit
* Operating system: Windows 7 64 bit

## Dependencies

IPython >=1.0      :  4.1.2 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.18.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.5.0   :  1.1.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.2.0 (OK)
rope >=0.9.2       :  0.9.4 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
sympy >=0.7.3      :  1.0 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by Qlogin** [comment]
Same as #3031.

**Comment by ccordoba12** [comment]
Right, thanks for pointing it out @Qlogin!

@Will282, this error will be fixed in Spyder 2.3.9

**Comment by Will282** [comment]
Thanks very much.
