### ISSUE TITLE
GUI won't even start on current master (some kind of setuptools problem?)

### ISSUE THREAD

**Issue by drammock** [spyder-ide/spyder#3111]
## Description of your problem

**What steps will reproduce the problem?**

1. clone current master
2. run `python bootstrap.py`

**What is the expected output?**
IDE should launch
**What do you see instead?**
```
[~/B/spyder] $ python bootstrap.py 
Executing Spyder from source checkout
Revision 3525c73, Branch: master
01. Patched sys.path with /home/drmccloy/Builds/spyder
02. PyQt4 is detected, selecting
03. Imported Spyder 3.0.0dev
    [Python 2.7.6 64bits, Qt 4.8.6, PyQt4 (API v2) 4.10.4 on Linux]
04. Running Spyder
Bootstrap completed in 00:00:00.4123
Traceback (most recent call last):
  File "/home/drmccloy/Builds/spyder/spyderlib/app/spyder.py", line 3125, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/drmccloy/Builds/spyder/spyderlib/app/spyder.py", line 3011, in run_spyder
    main.setup()
  File "/home/drmccloy/Builds/spyder/spyderlib/app/spyder.py", line 876, in setup
    self.findinfiles = FindInFiles(self)
  File "/home/drmccloy/Builds/spyder/spyderlib/plugins/findinfiles.py", line 49, in __init__
    include = self.include_patterns()
  File "/home/drmccloy/Builds/spyder/spyderlib/plugins/findinfiles.py", line 98, in include_patterns
    edit_ext = get_edit_extensions()
  File "/home/drmccloy/Builds/spyder/spyderlib/config/utils.py", line 131, in get_edit_extensions
    edit_filetypes = get_edit_filetypes()
  File "/home/drmccloy/Builds/spyder/spyderlib/config/utils.py", line 110, in get_edit_filetypes
    pygments_exts = _get_pygments_extensions()
  File "/home/drmccloy/Builds/spyder/spyderlib/config/utils.py", line 85, in _get_pygments_extensions
    for lx in all_lexers:
  File "/home/drmccloy/.local/lib/python2.7/site-packages/Pygments-2.1.3-py2.7.egg/pygments/lexers/__init__.py", line 53, in get_all_lexers
    for lexer in find_plugin_lexers():
  File "/home/drmccloy/.local/lib/python2.7/site-packages/Pygments-2.1.3-py2.7.egg/pygments/plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2087, in load
    if require: self.require(env, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2100, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer)))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2291, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2484, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2501, in _compute_dependencies
    from _markerlib import compile as compile_marker
ImportError: No module named _markerlib
```

**Please provide any additional information below**
```
[~] $ pip list | grep Pygments
Pygments (2.1.3)
[~] $ pip list | grep setuptools
setuptools (20.7.0)
```

## Versions and main components
```
[~] $ lsb_release -d
Description:	Ubuntu 14.04.4 LTS
[~] $ python --version
Python 2.7.6
```

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

*Not possible, GUI won't even start*

**Comment by drammock** [comment]
After doing this: 
```
pip uninstall setuptools
pip install setuptools==20.1.1
```
things work again.  The version number was a guess, based on searching for `_markerlib` on [this page](https://pythonhosted.org/setuptools/history.html) and picking a version older than [20.2](https://pythonhosted.org/setuptools/history.html#id10) (which is where the most recent `_markerlib`-related changes happened).

**Comment by ccordoba12** [comment]
This error seems unrelated to Spyder. @drammock, do you think there's something we can do about it?

**Comment by drammock** [comment]
Looks like it's related to pypa/setuptools#535.
