### ISSUE TITLE
Unittest module doesn't work in the interactive console

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#316]
_From [matthew....@gmail.com](https://code.google.com/u/103821680580507266599/) on 2010-08-26T10:05:51Z_

Creating a unittest testcase suite and running it:

import unittest    

class TestSequenceFunctions(unittest.TestCase):
            
    def test_case1(self):
        self.assertEqual(1,1)
        self.assertNotEqual(1,2)

suite = unittest.TestLoader().loadTestsFromTestCase(TestSequenceFunctions)
unittest.TextTestRunner().run(suite)

causes an IOError when run in the interactive console (but not the external one) What is the expected output? What do you see instead? The simple example included always passes and should display 'ran test in 0.00 seconds' - this is true when run in the external console.

Instead the following error message is seen in the interactive console:

Traceback (most recent call last):
  File "C:\Analysis\test_Spyder_Unittest.py", line 11, in \<module>
    unittest.TextTestRunner().run(suite)
  File "C:\Python26\lib\unittest.py", line 753, in run
    test(result)
  File "C:\Python26\lib\unittest.py", line 464, in __call__
    return self.run(*args, **kwds)
  File "C:\Python26\lib\unittest.py", line 460, in run
    test(result)
  File "C:\Python26\lib\unittest.py", line 300, in __call__
    return self.run(*args, **kwds)
  File "C:\Python26\lib\unittest.py", line 295, in run
    if ok: result.addSuccess(self)
  File "C:\Python26\lib\unittest.py", line 703, in addSuccess
    self.stream.flush()
IOError: [Errno 9] Bad file descriptor

It appears there is some confusion regarding sys.stderr (I think this is what self.stream is referring to here) What version of the product are you using? On what operating system? Currently running spyder 1.03 as part of pythonxy distribution 2.6.5.1 running on windows XP.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=316_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-08-26T11:14:51Z_

I would expect this kind of behavior in the interactive console which is only emulating a Python interpreter whereas the external console is a real interpreter in a separate process.

So I would recommend to run unit test scripts in the external console, that's all. Note  that the interactive console has been removed from Spyder since v2.0 (version which is already available in alpha version and will be released in beta version very soon).

**Status:** WontFix
