### ISSUE TITLE
Kernel starting error

### ISSUE THREAD

**Issue by cyrilfurtado** [spyder-ide/spyder#3168]
## Description

**What steps will reproduce the problem?**
1. Mac OS 10.11.3, python 2.7.1
2. Installed  Tensorflow
3.  Start spyder (from anaconda launcher)

**What is the expected output? What do you see instead?**
**It should show the kernel started instead you see**

```
An error ocurred while starting the kernel
Traceback (most recent call last):
File "/Users/U5/Downloads/Software/anaconda/lib/python2.7/site‑packages/spyderlib/widgets/externalshell/start_ipython_kernel.py", line 183, in 
from IPython.kernel.zmq.kernelapp import IPKernelApp
File "/Users/U5/Downloads/Software/User/lib/python2.7/site‑packages/IPython/kernel/__init__.py", line 4, in 
from . import zmq
File "/Users/U5/Downloads/Software/User/lib/python2.7/site‑packages/IPython/kernel/zmq/__init__.py", line 8, in 
check_for_zmq('13', 'IPython.kernel.zmq')
File "/Users/U5/Downloads/Software/User/lib/python2.7/site‑packages/IPython/utils/zmqrelated.py", line 12, in check_for_zmq
raise ImportError("%s requires pyzmq >= %s"%(required_by, minimum_version))
ImportError: IPython.kernel.zmq requires pyzmq >= 1
```

**Please provide any additional information below**
## Version and main components
- Spyder Version: 2.3.8 
- Python Version: 2.7.11
- Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Darwin
## Optional dependencies

```
pyflakes >=0.5.0   :  1.2.2 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pygments >=1.6     :  2.1.3 (OK)
IPython >=1.0      :  4.2.0 (OK)
zmq >=2.1.11       :  15.2.0 (OK)
qtconsole >=4.0    :  4.2.1 (OK)
pandas >=0.13.1    :  0.17.0 (OK)
sphinx >=0.6.6     :  1.4.1 (OK)
psutil >=0.3       :  4.1.0 (OK)
rope >=0.9.2       :  0.9.4 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.4.3 (OK)
sympy >=0.7.3      :  0.7.6 (OK)
pylint >=0.25      :  None (NOK)

```

**Comment by ccordoba12** [comment]
It seems you have two Python versions, which are getting mixed somehow. I say it because the first line of your error is:

    File "/Users/U5/Downloads/Software/anaconda/lib/python2.7/site‑packages/spyderlib/widgets/externalshell/start_ipython_kernel.py"

while the second line is

    File "/Users/U5/Downloads/Software/User/lib/python2.7/site‑packages/IPython/kernel/__init__.py"

As you can see, after the `Software` directory things are very different :-)

**Comment by ccordoba12** [comment]
Closing because of lack of response.
