### ISSUE TITLE
spyder (1.1.3 & 1.1.4) with PyQt 4.7 / Python 2.7

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#317]
_From [dweber.c...@gmail.com](https://code.google.com/u/100607128787105116242/) on 2010-08-26T15:16:21Z_

What steps will reproduce the problem?

 I'm trying to get spyder to work within a virtualenv based on a python2.7 build from the UCSF-Chimera project.  See my notes about this here: http://plato.cgl.ucsf.edu/trac/chimera/wiki/VirtualEnv What is the expected output? What do you see instead? spyder will not launch, traceback indicates (more details below):

  File "/home/dweber/src/chimera-virtualenv/lib/python2.7/site-packages/spyder-1.1.3-py2.7.egg/spyderlib/widgets/editortools.py", line 91, in __init__
    QTreeWidgetItem.__init__(self, treewidget)
TypeError: an integer is required What version of the product are you using? On what operating system? I've tried with v1.1.3 and v1.1.4 from the google code downloads.  I'm working with Ubuntu 10.04 (lucid). 

Please provide any additional information below

. See my notes at: http://plato.cgl.ucsf.edu/trac/chimera/wiki/VirtualEnv A startup with 'spyder -l' works fine.  The test_qsci.py and test_qt.py scripts are working too.

This is the startup traceback (within a virtualenv):
$ spyder
Traceback (most recent call last):
  File "/home/dweber/src/chimera-virtualenv/lib/python2.7/site-packages/spyder-1.1.3-py2.7.egg/spyderlib/spyder.py", line 1559, in main
    mainwindow = run_spyder(app, commands, intitle, message, options)
  File "/home/dweber/src/chimera-virtualenv/lib/python2.7/site-packages/spyder-1.1.3-py2.7.egg/spyderlib/spyder.py", line 1503, in run_spyder
    main.setup()
  File "/home/dweber/src/chimera-virtualenv/lib/python2.7/site-packages/spyder-1.1.3-py2.7.egg/spyderlib/spyder.py", line 403, in setup
    self.editor = Editor(self)
  File "/home/dweber/src/chimera-virtualenv/lib/python2.7/site-packages/spyder-1.1.3-py2.7.egg/spyderlib/plugins/editor.py", line 189, in __init__
    self.__load_temp_file()
  File "/home/dweber/src/chimera-virtualenv/lib/python2.7/site-packages/spyder-1.1.3-py2.7.egg/spyderlib/plugins/editor.py", line 964, in __load_temp_file
    self.load(self.TEMPFILE_PATH)
  File "/home/dweber/src/chimera-virtualenv/lib/python2.7/site-packages/spyder-1.1.3-py2.7.egg/spyderlib/plugins/editor.py", line 1111, in load
    editor = editorstack.load(filename, set_current=is_current)
  File "/home/dweber/src/chimera-virtualenv/lib/python2.7/site-packages/spyder-1.1.3-py2.7.egg/spyderlib/widgets/editor.py", line 1152, in load
    self._refresh_classbrowser(index, update=True)
  File "/home/dweber/src/chimera-virtualenv/lib/python2.7/site-packages/spyder-1.1.3-py2.7.egg/spyderlib/widgets/editor.py", line 899, in _refresh_classbrowser
    update=update)
  File "/home/dweber/src/chimera-virtualenv/lib/python2.7/site-packages/spyder-1.1.3-py2.7.egg/spyderlib/widgets/editortools.py", line 548, in set_current_editor
    self.treewidget.set_current_editor(editor, fname, update)
  File "/home/dweber/src/chimera-virtualenv/lib/python2.7/site-packages/spyder-1.1.3-py2.7.egg/spyderlib/widgets/editortools.py", line 285, in set_current_editor
    root_item = FileRootItem(fname, self)
  File "/home/dweber/src/chimera-virtualenv/lib/python2.7/site-packages/spyder-1.1.3-py2.7.egg/spyderlib/widgets/editortools.py", line 91, in __init__
    QTreeWidgetItem.__init__(self, treewidget)
TypeError: an integer is required
(chimera-virtualenv)dweber@rbvi-gassho:~/Downloads/spyder-1.1.3$ 
(chimera-virtualenv)dweber@rbvi-gassho:~/Downloads/spyder-1.1.3$ 
(chimera-virtualenv)dweber@rbvi-gassho:~/Downloads/spyder-1.1.3$ python /home/dweber/Downloads/test_qsci.py 
QScintilla2 v2.4.3 is installed (Spyder requires QScintilla2 >=v2.2)
(chimera-virtualenv)dweber@rbvi-gassho:~/Downloads/spyder-1.1.3$ python /home/dweber/Downloads/test_qt.py 
PyQt4 v4.7.2 is installed (Spyder requires PyQt4 >=v4.4)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=317_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-08-26T13:50:11Z_

Apparently that is the same bug as in here: https://code.google.com/p/spyderlib/issues/detail?id=253 (ignored comment `#7` which is clearly off-topic...)

That is probably a Python 2.7 / PyQt 4.7 related issue.
I'll have to test this configuration to debug this.

**Summary:** spyder (1.1.3 &amp; 1.1.4) with PyQt 4.7 / Python 2.7  
  **Status:** Accepted

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-08-26T13:50:27Z_

issue #253 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [dweber.c...@gmail.com](https://code.google.com/u/100607128787105116242/) on 2010-08-26T14:07:53Z_

spyder 1.1.3 is installed under python2.6 on my Ubuntu 10.04 (lucid) system, i.e.:

dweber@rbvi-gassho:~$ pip install spyder
Requirement already satisfied: spyder in /usr/local/lib/python2.6/dist-packages/spyder-1.1.3-py2.6.egg
Installing collected packages: spyder
Successfully installed spyder
dweber@rbvi-gassho:~$ 
dweber@rbvi-gassho:~$ python /home/dweber/Downloads/test_qt.py 
PyQt4 v4.7.2 is installed (Spyder requires PyQt4 >=v4.4)
dweber@rbvi-gassho:~$ 
dweber@rbvi-gassho:~$ python /home/dweber/Downloads/test_qsci.py 
QScintilla2 v2.4.3 is installed (Spyder requires QScintilla2 >=v2.2)

This installation will load and run just fine.  The Chimera python2.7 installation should have bindings to the same PyQt4 and QScintilla2 libs, but perhaps the bindings generate a slightly different API under python2.7?

**Comment by spyder-issues-migrator** [comment]
_From [dweber.c...@gmail.com](https://code.google.com/u/100607128787105116242/) on 2010-08-26T14:52:11Z_

FYI, the configure for PyQt indicates:
Qt v4.6.2 free edition is being used.
SIP 4.10.1 is being used.

**Comment by spyder-issues-migrator** [comment]
_From [charles....@gmail.com](https://code.google.com/u/106742389533905007142/) on 2010-09-11T13:14:06Z_

Still broken with:

Python 2.7
SIP 11.1
Qt 6.3
PyQt 4.7.6

Both Spyder 1.1.5 and 2.0.0beta1 fail with the following:

grendel:~ sharpie$ spyder --debug
Start of MainWindow constructor
Initializing...
End of MainWindow constructor
*** Start of MainWindow setup ***
Loading object inspector...
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/codeeditor/codeeditor.py", line 770, in viewportEvent
    +self.fontMetrics().width('9')*self.edge_line.column+5
TypeError: a float is required
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/codeeditor/codeeditor.py", line 770, in viewportEvent
    +self.fontMetrics().width('9')*self.edge_line.column+5
TypeError: a float is required
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/codeeditor/codeeditor.py", line 770, in viewportEvent
    +self.fontMetrics().width('9')*self.edge_line.column+5
TypeError: a float is required
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/codeeditor/codeeditor.py", line 770, in viewportEvent
    +self.fontMetrics().width('9')*self.edge_line.column+5
TypeError: a float is required
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/codeeditor/codeeditor.py", line 770, in viewportEvent
    +self.fontMetrics().width('9')*self.edge_line.column+5
TypeError: a float is required
Loading editor...
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/codeeditor/codeeditor.py", line 770, in viewportEvent
    +self.fontMetrics().width('9')*self.edge_line.column+5
TypeError: a float is required
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/codeeditor/codeeditor.py", line 770, in viewportEvent
    +self.fontMetrics().width('9')*self.edge_line.column+5
TypeError: a float is required
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/codeeditor/codeeditor.py", line 770, in viewportEvent
    +self.fontMetrics().width('9')*self.edge_line.column+5
TypeError: a float is required
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/codeeditor/codeeditor.py", line 770, in viewportEvent
    +self.fontMetrics().width('9')*self.edge_line.column+5
TypeError: a float is required
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/codeeditor/codeeditor.py", line 770, in viewportEvent
    +self.fontMetrics().width('9')*self.edge_line.column+5
TypeError: a float is required
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/codeeditor/codeeditor.py", line 770, in viewportEvent
    +self.fontMetrics().width('9')*self.edge_line.column+5
TypeError: a float is required
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 1385, in main
    mainwindow = run_spyder(app, options)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 1326, in run_spyder
    main.setup()
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 535, in setup
    self.editor = Editor(self)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/plugins/editor.py", line 348, in __init__
    self.__load_temp_file()
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/plugins/editor.py", line 1180, in __load_temp_file
    self.load(self.TEMPFILE_PATH)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/plugins/editor.py", line 1334, in load
    editor = editorstack.load(filename, set_current=is_current)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/editor.py", line 1549, in load
    self._refresh_outlineexplorer(index, update=True)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/editor.py", line 1269, in _refresh_outlineexplorer
    update=update)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/editortools.py", line 552, in set_current_editor
    self.treewidget.set_current_editor(editor, fname, update)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/editortools.py", line 295, in set_current_editor
    root_item = FileRootItem(fname, self)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/editortools.py", line 98, in __init__
    QTreeWidgetItem.__init__(self, treewidget)
TypeError: an integer is required
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/spyder", line 3, in \<module>
    spyder.main()
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 1391, in main
    if mainwindow is None:
UnboundLocalError: local variable 'mainwindow' referenced before assignment
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 913, in closing
    CONF.set('main', prefix+'size', (size.width(), size.height()))
AttributeError: 'NoneType' object has no attribute 'width'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/...

**Comment by spyder-issues-migrator** [comment]
_From [charles....@gmail.com](https://code.google.com/u/106742389533905007142/) on 2010-09-11T13:14:06Z_

...2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/Cellar/python/2.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 913, in closing
    CONF.set('main', prefix+'size', (size.width(), size.height()))
AttributeError: 'NoneType' object has no attribute 'width'

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-09-25T00:36:23Z_

These specific errors are fixed in Spyder v1.1 and v2.0 mercurial repositories.
Maybe there are still compatibility issues with Python 2.7/PyQt 4.7.

**Status:** Fixed
