### ISSUE TITLE
Spyder won't start, complains about PyQt, but PyQT5 present and works.

### ISSUE THREAD

**Issue by FayeG** [spyder-ide/spyder#3171]
## Description of your problem

**What steps will reproduce the problem?**

1. Installed python 3.5.1
2. installed PyQt5
3. did not install PySide as it only support up to Python 3.4

**What is the expected output? What do you see instead?**
The spyder runs but what I get is:
-bash-4.2$ spyder3
Traceback (most recent call last):
  File "/usr/local/mnt/vega_python/python-3.5.1/lib/python3.5/site-packages/spyderlib/qt/__init__.py", line 48, in <module>
    from PySide import __version__  # analysis:ignore
ImportError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/mnt/vega_python/python-3.5.1/lib/python3.5/site-packages/spyderlib/requirements.py", line 40, in check_qt
    from spyderlib import qt
  File "/usr/local/mnt/vega_python/python-3.5.1/lib/python3.5/site-packages/spyderlib/qt/__init__.py", line 50, in <module>
    raise ImportError("Spyder requires PySide or PyQt to be installed")
ImportError: Spyder requires PySide or PyQt to be installed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/export/vega_python/python-3.5.1/bin/spyder3", line 3, in <module>
    start_app.main()
  File "/usr/local/mnt/vega_python/python-3.5.1/lib/python3.5/site-packages/spyderlib/start_app.py", line 114, in main
    from spyderlib import spyder
  File "/usr/local/mnt/vega_python/python-3.5.1/lib/python3.5/site-packages/spyderlib/spyder.py", line 48, in <module>
    requirements.check_qt()
  File "/usr/local/mnt/vega_python/python-3.5.1/lib/python3.5/site-packages/spyderlib/requirements.py", line 50, in check_qt
    % (qt_infos['pyqt']+qt_infos['pyside']))
  File "/usr/local/mnt/vega_python/python-3.5.1/lib/python3.5/site-packages/spyderlib/requirements.py", line 25, in show_warning
    raise RuntimeError(message)
RuntimeError: Please check Spyder installation requirements:
PyQt4 4.6+ (or PySide 1.2.0+) is required.
-bash-4.2$

**Please provide any additional information below**

However I can import PyQt5, viz:
-bash-4.2$ /usr/local/export/vega_python/python-3.5.1/bin/python
Python 3.5.1 (default, May 12 2016, 11:46:34)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5 import QtGui
>>>

## Versions and main components

* Spyder Version: 2.3.9
* Python Version: 3.5.1
* Operating system: RHEL 7

**Comment by ccordoba12** [comment]
Spyder 2.3.9 (or any previous version) doesn't work with PyQt5. You need to run Spyder from git or install our latest beta with

    pip install --pre spyder

to make it run with PyQt5.

However, there are some problems with PyQt 5.6 that we are trying to solve right now :-)

**Comment by rajathsingh12** [comment]
All I did was removed all pyqt versions and installed pyqt5 using pip and spyder launched,

**Comment by amanwalia92** [comment]
This fixed it for me:
`sudo apt-get install python-qtpy`

**Comment by carlord** [comment]
I don't know why this issue is considered closed, I'm working with arecent version of soyder, recommendation is to upgrade to 5.2.2 there is where the issues started, now I can't put my IDE to work, nor from DNf instalation nor from pip installation, I validate dependendies and it remains crashing and giving:
-   PyQt5 5.6+ is required (found vNone).
had validated that pyqt is in version 5.12.3 and pyqt5_sip
real help needed please
