### ISSUE TITLE
AttributeError: module 'numpy.core.multiarray' has no attribute 'MAY_SHARE_BOUNDS'

### ISSUE THREAD

**Issue by kvazipushka** [spyder-ide/spyder#3178]
Hello, 

I've updated numpy package and now Spyder IDE is not starting. 

After performing  `conda update --all` I see:

numpy:          1.10.4-py35_2   --> 1.11.0-py35_1

Now when I try to run Spyder I get: 

ERROR: 3rd party plugin import failed for `io_hdf5`
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\spyderlib\otherplugins.py", line 53, in get_spyderplugins_mods
    __import__(name)
  File "C:\Anaconda3\lib\site-packages\spyderplugins\io_hdf5.py", line 38, in <module>
    import numpy as np
  File "C:\Anaconda3\lib\site-packages\numpy\__init__.py", line 180, in <module>
    from . import add_newdocs
  File "C:\Anaconda3\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Anaconda3\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Anaconda3\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 25, in <module>
    from . import numeric
  File "C:\Anaconda3\lib\site-packages\numpy\core\numeric.py", line 73, in <module>
    MAY_SHARE_BOUNDS = multiarray.MAY_SHARE_BOUNDS
AttributeError: module 'numpy.core.multiarray' has no attribute 'MAY_SHARE_BOUNDS'
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\spyder-script.py", line 2, in <module>
    start_app.main()
  File "C:\Anaconda3\lib\site-packages\spyderlib\start_app.py", line 114, in main
    from spyderlib import spyder
  File "C:\Anaconda3\lib\site-packages\spyderlib\spyder.py", line 155, in <module>
    from spyderlib.utils.environ import WinUserEnvDialog
  File "C:\Anaconda3\lib\site-packages\spyderlib\utils\environ.py", line 17, in <module>
    from spyderlib.widgets.dicteditor import DictEditor
  File "C:\Anaconda3\lib\site-packages\spyderlib\widgets\dicteditor.py", line 39, in <module>
    from spyderlib.widgets.dicteditorutils import (sort_against, get_size,
  File "C:\Anaconda3\lib\site-packages\spyderlib\widgets\dicteditorutils.py", line 31, in <module>
    from numpy import ndarray, array, matrix, recarray
  File "C:\Anaconda3\lib\site-packages\numpy\__init__.py", line 180, in <module>
    from . import add_newdocs
  File "C:\Anaconda3\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Anaconda3\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Anaconda3\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 25, in <module>
    from . import numeric
  File "C:\Anaconda3\lib\site-packages\numpy\core\numeric.py", line 73, in <module>
    MAY_SHARE_BOUNDS = multiarray.MAY_SHARE_BOUNDS
AttributeError: module 'numpy.core.multiarray' has no attribute 'MAY_SHARE_BOUNDS'

When I revert back to previously installed numpy package everything works fine. 

I have:

Spyder Version: 2.3.8
Python Version: 3.5.1
Operating system: Windows 10 x64

Thanks in advance for any suggestions.

**Comment by jitseniesen** [comment]
At first sight, this seems to be a problem in the numpy package. Can you check that numpy works outside Spyder? That is, open a python prompt and type `import numpy` . Sorry if this is obvious and you have already done this.

**Comment by kvazipushka** [comment]
Hello, thanks for the quick response! 
Actually, I've managed to fix the problem myself :) 
I've updated all outdate packages using pip. After that spyder is working correctly with new numpy package. Suppose, that problem was because I had Spyder 2.3.8, not the newer one (2.3.9).
