### ISSUE TITLE
Spyder won't load

### ISSUE THREAD

**Issue by benbuckmd** [spyder-ide/spyder#3278]
Hi all,

Spyder will not load for me today after installing the graphviz library. When I click on the Spyder button on the start menu, nothing happens. When I try running "spyder" from the command prompt, I get the following message:

`Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Benjamin>spyder
Traceback (most recent call last):
  File "C:\Users\Benjamin\Anaconda3-4\lib\site-packages\spyderlib\qt\__init__.py", line 48, in <module>
    from PySide import __version__  # analysis:ignore
ImportError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Benjamin\Anaconda3-4\lib\site-packages\spyderlib\requirements.py", line 40, in check_qt
    from spyderlib import qt
  File "C:\Users\Benjamin\Anaconda3-4\lib\site-packages\spyderlib\qt\__init__.py", line 50, in <module>
    raise ImportError("Spyder requires PySide or PyQt to be installed")
ImportError: Spyder requires PySide or PyQt to be installed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Benjamin\Anaconda3-4\Scripts\spyder-script.py", line 2, in <module>
    start_app.main()
  File "C:\Users\Benjamin\Anaconda3-4\lib\site-packages\spyderlib\start_app.py", line 114, in main
    from spyderlib import spyder
  File "C:\Users\Benjamin\Anaconda3-4\lib\site-packages\spyderlib\spyder.py", line 48, in <module>
    requirements.check_qt()
  File "C:\Users\Benjamin\Anaconda3-4\lib\site-packages\spyderlib\requirements.py", line 50, in check_qt
    % (qt_infos['pyqt']+qt_infos['pyside']))
  File "C:\Users\Benjamin\Anaconda3-4\lib\site-packages\spyderlib\requirements.py", line 25, in show_warning
    raise RuntimeError(message)
RuntimeError: Please check Spyder installation requirements:
PyQt4 4.6+ (or PySide 1.2.0+) is required.
`
I've tried uninstalling PyQt4 and graphviz, then reinstalling PyQt4, but I get the same result.

* Python Version: 3.5.1
* Operating system: Windows 10

**Comment by jitseniesen** [comment]
It may be that at some point, your version of pyqt4 got upgraded, and it is now too new for spyder, in which case a solution is to upgrade spyder. What versions of spyder and pyqt4 do you have installed?

**Comment by ccordoba12** [comment]
This is a problem with Anaconda and not with Spyder itself. Until the official graphviz package is updated, you have this solution to work with Spyder and graphviz:

    conda remove graphviz
    conda install -c conda-forge graphviz
