### ISSUE TITLE
"import x" and "from x import y" code completion is not working on the editor and the console

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#328]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2010-09-04T12:58:19Z_

I really like this Ipython's feature, because it lets me quickly explore a new module or those big modules I know nothing about.

Unfortunately it's not working on the embedded ipython console nor on the editor. I have to use this feature in a console, then paste the results on spyder for now.

This is my major complaint about spyder. I've found it really really useful for my work and I like it a lot. Thanks for taking the time to develop it.

Carlos

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=328_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-09-12T10:14:09Z_

**Summary:** v2.0: "import x" and "from x import y" code completion (editor + console)  
  **Labels:** -Type-Defect Type-Enhancement

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-09-12T10:15:07Z_

issue #275 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-09-12T10:15:41Z_

issue #257 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-17T13:15:07Z_

**Labels:** -Priority-Medium Priority-High

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-04-22T17:57:44Z_

I have a working code that will solve this issue for the console. I hope I could add it to the Editor too, but I don't know how well it can work with rope.

I'll try to publish a branch as soon as a I can.

Cheers,
Carlos

**Summary:** "import x" and "from x import y" code completion is not working on the editor and the console  
  **Status:** Accepted  
  **Owner:** ccordoba12  
  **Labels:** Milestone-Release2.1

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-04-27T08:52:42Z_

I've added module completion to the console (both ipython and python). Please check my branch called ccordoba12-module-completion, test it and tell what you think. I've tried to cover all corner cases (especially in statements of the form "from x import y") but you never know :). All in all I think it's working quite well and it'll be a great addition for 2.1!

There is one important drawback though: this feature can work really slowly on old computers. IPython guys solved this issue by creating a simple database of all installed modules so that it hasn't to be recomputed every single time. I guess we'll have to replicate this functionality, just in case.

I still have to add this feature to the editor. Pierre, where can I start to look at to develop this? Can I use rope for this?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-05-01T20:26:20Z_

I've now added it to the editor. It's working better than what I expected. For example, it's working on multi-line line statements such as this one:

from PyQt4.QtGui import (QAction, QAbstractTextDocumentLayout,
                         qAlpha, QColor)

Besides, I've been investigating the slowness issue: it's only noticeable (again, only on old computers) when you're trying to get the list of all modules in your PYTHONPATH for the first time in your session. It could be annoying though, because the widget could take 2 or 3 seconds to appear.

I have a solution for this based on the work of the Ipython guys. I hope to publish it on the next days.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-05-09T15:33:00Z_

Pierre, I think I've finished my work. I've added the solution I mentioned in my last comment and also an entry in the Tools menu to update the modules list, in case the user consider it necessary (for example, if he/she installs modules not present the first time they were saved)

Could you please review my branch and if you're ok with it, merge it?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-06-01T09:58:03Z_

I've rebased my branch to work with the latest tips of 2.1dev and 2.2dev. This means I resolved all merge conflicts and added a simple fix because of config/baseconfig recent split, that maybe are preventing this to go into the main repos.

My new branches are: https://code.google.com/r/ccordoba12-module-completion-v22/ https://code.google.com/r/ccordoba12-module-completion-v21/ Besides, I've tested every branch on Windows and I can confirm they're working as expected. Well, I couldn't test in the ipython console on 2.2 because it doesn't start. Instead, I'm getting this traceback:

Traceback (most recent call last):
  File "C:\Documents and Settings\carlos\Mis documentos\Spyder test\module-completion-v22\spyderlib\widgets\externalshell\startup.py", line 184, in \<module>
    'debugfile': debugfile})
  File "C:\Python26\lib\site-packages\IPython\Shell.py", line 1259, in start
    return shell(user_ns = user_ns)
  File "C:\Python26\lib\site-packages\IPython\Shell.py", line 1146, in __init__
    shell_class=MatplotlibMTShell)
  File "C:\Python26\lib\site-packages\IPython\Shell.py", line 1045, in __init__
    on_kill=[QtGui.qApp.exit])
  File "C:\Python26\lib\site-packages\IPython\ipmaker.py", line 100, in make_IPython
    embedded=embedded,**kw)
  File "C:\Python26\lib\site-packages\IPython\Shell.py", line 636, in __init__
    user_ns,user_global_ns,b2 = self._matplotlib_config(name,user_ns,user_global_ns)
  File "C:\Python26\lib\site-packages\IPython\Shell.py", line 556, in _matplotlib_config
    import matplotlib.pylab as pylab
  File "C:\Python26\lib\site-packages\matplotlib\pylab.py", line 263, in \<module>
    from matplotlib.pyplot import *
  File "C:\Python26\lib\site-packages\matplotlib\pyplot.py", line 95, in \<module>
    new_figure_manager, draw_if_interactive, show = pylab_setup()
  File "C:\Python26\lib\site-packages\matplotlib\backends\__init__.py", line 25, in pylab_setup
    globals(),locals(),[backend_name])
  File "C:\Python26\lib\site-packages\matplotlib\backends\backend_qt4agg.py", line 12, in \<module>
    from backend_qt4 import QtCore, QtGui, FigureManagerQT, FigureCanvasQT,\
  File "C:\Python26\lib\site-packages\matplotlib\backends\backend_qt4.py", line 18, in \<module>
    import matplotlib.backends.qt4_editor.figureoptions as figureoptions
  File "C:\Python26\lib\site-packages\matplotlib\backends\qt4_editor\figureoptions.py", line 11, in \<module>
    import matplotlib.backends.qt4_editor.formlayout as formlayout
  File "C:\Python26\lib\site-packages\matplotlib\backends\qt4_editor\formlayout.py", line 59, in \<module>
    from PyQt4.QtCore import (Qt, SIGNAL, SLOT, QSize, QString,
ImportError: cannot import name QString

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-06-04T13:05:53Z_

This traceback means that Matplotlib is trying to import QString which does not exist because v2.2dev is using PyQt API `#2` -- and spyderlib has been imported in IPython's process (probably because the Matplotlib patch is enabled -- try to disable it, and it should work).

As for your code, I have to check it out... still haven't got the time yet. But will do very soon!

**Comment by spyder-issues-migrator** [comment]
_From [david.ve...@gmail.com](https://code.google.com/u/108342766018366950755/) on 2011-06-08T02:27:42Z_

Ran into the same problem as described by Carlos. A long trace ending with:
ImportError: cannot import name QString

I can confirm that disabling the Matplotlib patch (tools > preferences > console > external modules) solves that problem.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-06-25T05:45:55Z_

BTW all your issues with PyQt4 API (QString related errors) should be fixed as Spyder v2.1 (default repository) is now compatible with both API 1 and 2 (and even with PySide, partly on Windows, almost completely on Linux).

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-06-25T06:23:17Z_

Carlos, I've just merged your clone to the main repository!

I have tested the feature very quickly but it seems to work nicely.
Great work, Carlos!

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-06-27T17:27:29Z_

Thanks, I'm really glad you like it! I checked the new 2.1 on Windows and the QString problem disappeared. Great work to you too!

I'm reopening this issue because I would like to discuss one thing a bit further. I don't know if you noticed, but I included two libraries from the Ipython project to speed up these kind of completions on old computers (in utils/external). I was having second thoughts on this because it's known that linux distros don't like this kind of behavior, i.e. to use bundled libraries of other projects.

What do you think about it? Should we leave them or better add a warning telling the user to install ipython to speed things up?

**Status:** Started

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-07-04T13:25:49Z_

Yes, I'm aware of these external modules.

And you are right regarding most Linux distributions policy. For Debian for instance, I was asked to be very careful about this: that's why I didn't include pyflakes or rope inside Spyder's source package.

Pros:
1. It would be cleaner to remove those modules for Linux package maintainers.
2. It would also mean less code to maintain.

Cons:
3. As pyflakes or rope tend to be very stable and move very slowly, it is quite confortable to build a library on top of them. On the contrary, I wouldn't do so with IPython since compatibility is regularly broken between releases.
4. Moreover, the IPython package import process is not as clean as it should be (after all it's not meant to be a library).

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-10-07T13:42:59Z_

I think we should leave those modules, especially now that you're trying to distribute Spyder as a self contained package.

**Labels:** Cat-CodeCompletion

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-11T10:34:31Z_

Ok, let's close this issue then.

**Status:** Done
