### ISSUE TITLE
Variable Explorer fails to display DataFrame with categories

### ISSUE THREAD

**Issue by jobar8** [spyder-ide/spyder#3308]
## Description of your problem
If a pandas DataFrame contains categorical data, it is not possible to browse the content with the Variable Explorer.

**What steps will reproduce the problem?**

1. In the IPython console, create a DataFrame with a column of type "category".
```python
    import pandas as pd
    df = pd.DataFrame({"id":[1,2,3,4,5,6], "raw_grade":['a', 'b', 'b', 'a', 'a', 'e']})
    df["grade"] = df["raw_grade"].astype("category")
```

2. Double-click on the row with the DataFrame in the Variable Explorer

**What is the expected output? What do you see instead?**
Instead of displaying the table, I get the following errors in the Internal Console:
```
>>> Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\variableexplorer\collectionseditor.py", line 464, in createEditor
    if not editor.setup_and_check(value, title=key):
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\variableexplorer\dataframeeditor.py", line 523, in setup_and_check
    self.dataModel = DataFrameModel(data, parent=self)
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\variableexplorer\dataframeeditor.py", line 93, in __init__
    self.max_min_col_update()
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\variableexplorer\dataframeeditor.py", line 132, in max_min_col_update
    df_abs = self.df[self.complex_intran].abs()
  File "C:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 1993, in __getitem__
    return self._getitem_frame(key)
  File "C:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 2069, in _getitem_frame
    return self.where(key)
  File "C:\Anaconda2\lib\site-packages\pandas\core\generic.py", line 4491, in where
    transpose=self._AXIS_REVERSED)
  File "C:\Anaconda2\lib\site-packages\pandas\core\internals.py", line 2908, in where
    return self.apply('where', **kwargs)
  File "C:\Anaconda2\lib\site-packages\pandas\core\internals.py", line 2890, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\Anaconda2\lib\site-packages\pandas\core\internals.py", line 1240, in where
    return self.make_block(result)
  File "C:\Anaconda2\lib\site-packages\pandas\core\internals.py", line 181, in make_block
    return make_block(values, placement=placement, ndim=ndim, **kwargs)
  File "C:\Anaconda2\lib\site-packages\pandas\core\internals.py", line 2518, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "C:\Anaconda2\lib\site-packages\pandas\core\internals.py", line 1663, in __init__
    placement=placement, **kwargs)
  File "C:\Anaconda2\lib\site-packages\pandas\core\internals.py", line 81, in __init__
    raise ValueError('Wrong number of dimensions')
ValueError: Wrong number of dimensions
```

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.0.0.dev0
* Python Version: 2.7.11
* Operating system: Windows 10

Qt 4.8.7
PyQt4 4.11.4

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  4.1.0 (OK)
numpy >=1.7      :  1.11.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.1.0 (OK)
pygments >=2.0   :  2.1.1 (OK)
qtconsole >=4.2.0:  4.2.0 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.3.5 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by jitseniesen** [comment]
Thanks for the report. We should fix this. I can reproduce with current HEAD and Python 3.5 on Linux.

**Comment by ccordoba12** [comment]
@jitseniesen, could you take a look at this one?

**Comment by niketmistry** [comment]
Has anyone ever encountered an error where variable explorer doesn't show the dataframe if you name dataframe more than 2 letters?
