### ISSUE TITLE
Spyder Unable to Start Win 10, 64bit, spyder2.3.9

### ISSUE THREAD

**Issue by collawolley** [spyder-ide/spyder#3320]
Hi, I have a problem with spyder. I have been using it for several months on windows 10 without any problem until 3 days ago when it just wouldn't come up again.
I have tried to re install but i keep getting the same error and same same issue of not starting up. To be specific, it worked immediately after I uninstall anaconda and reinstalled anaconda but when i restarted my laptop for work the following day, Spyder again refused to come up and I keep getting the same error messages as before.
Please see the error message below for both for starting spyder as well as attempting to rreset. The issue has been the same ever.

C:\Users\user>spyder --reset
Traceback (most recent call last):
  File "C:\Users\user\Anaconda2\Scripts\spyder-script.py", line 2, in <module>
    start_app.main()
  File "C:\Users\user\Anaconda2\lib\site-packages\spyderlib\start_app.py", line 114, in main
    from spyderlib import spyder
  File "C:\Users\user\Anaconda2\lib\site-packages\spyderlib\spyder.py", line 155, in <module>
    from spyderlib.utils.environ import WinUserEnvDialog
  File "C:\Users\user\Anaconda2\lib\site-packages\spyderlib\utils\environ.py", line 17, in <module>
    from spyderlib.widgets.dicteditor import DictEditor
  File "C:\Users\user\Anaconda2\lib\site-packages\spyderlib\widgets\dicteditor.py", line 39, in <module>
    from spyderlib.widgets.dicteditorutils import (sort_against, get_size,
  File "C:\Users\user\Anaconda2\lib\site-packages\spyderlib\widgets\dicteditorutils.py", line 78, in <module>
    import bs4
  File "C:\Users\user\Anaconda2\lib\site-packages\bs4\__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "C:\Users\user\Anaconda2\lib\site-packages\bs4\builder\__init__.py", line 314, in <module>
    from . import _html5lib
  File "C:\Users\user\Anaconda2\lib\site-packages\bs4\builder\_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

C:\Users\user>spyder
Traceback (most recent call last):
  File "C:\Users\user\Anaconda2\Scripts\spyder-script.py", line 2, in <module>
    start_app.main()
  File "C:\Users\user\Anaconda2\lib\site-packages\spyderlib\start_app.py", line 114, in main
    from spyderlib import spyder
  File "C:\Users\user\Anaconda2\lib\site-packages\spyderlib\spyder.py", line 155, in <module>
    from spyderlib.utils.environ import WinUserEnvDialog
  File "C:\Users\user\Anaconda2\lib\site-packages\spyderlib\utils\environ.py", line 17, in <module>
    from spyderlib.widgets.dicteditor import DictEditor
  File "C:\Users\user\Anaconda2\lib\site-packages\spyderlib\widgets\dicteditor.py", line 39, in <module>
    from spyderlib.widgets.dicteditorutils import (sort_against, get_size,
  File "C:\Users\user\Anaconda2\lib\site-packages\spyderlib\widgets\dicteditorutils.py", line 78, in <module>
    import bs4
  File "C:\Users\user\Anaconda2\lib\site-packages\bs4\__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "C:\Users\user\Anaconda2\lib\site-packages\bs4\builder\__init__.py", line 314, in <module>
    from . import _html5lib
  File "C:\Users\user\Anaconda2\lib\site-packages\bs4\builder\_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

I am using Windows 10, 64 bit machine, python 2.7 and anaconda 2-4.1.1.1, spyder 2.3.9
I will appreciate any help in resolving this issue.
Thanks

**Comment by ccordoba12** [comment]
This problem was already fixed in Spyder master. For now I think you need to run

    conda install html5lib

to avoid it.

**Comment by collawolley** [comment]
thanks. that solved it!
