### ISSUE TITLE
input() with non-string argument results in internal error

### ISSUE THREAD

**Issue by zoquda** [spyder-ide/spyder#3346]
## Description of your problem

Calling `input()` with a non-string argument seems to cause a Spyder internal error.

**What steps will reproduce the problem?**
1. Enter `input(101)` in the IPython console.

**What is the expected output?**
Expected would be that the IPython console displays `101` and then lets the user type in a line. 

**What do you see instead?**
The Spyder Internal console displays the following error message:

```
Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> C:\Software\Anaconda3\lib\site-packages\nbformat\current.py:19: UserWarning: nbformat.current is deprecated.

- use nbformat for read/write/validate public API
- use nbformat.vX directly to composing notebooks of a particular version

  """)
Traceback (most recent call last):
  File "C:\Software\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "C:\Software\Anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 515, in _handle_input_request
    self._readline(msg['content']['prompt'], callback=callback, password=msg['content']['password'])
  File "C:\Software\Anaconda3\lib\site-packages\qtconsole\console_widget.py", line 2010, in _readline
    self._show_prompt(prompt, newline=False)
  File "C:\Software\Anaconda3\lib\site-packages\qtconsole\console_widget.py", line 2098, in _show_prompt
    self._append_plain_text(prompt)
  File "C:\Software\Anaconda3\lib\site-packages\qtconsole\console_widget.py", line 924, in _append_plain_text
    self._append_custom(self._insert_plain_text, text, before_prompt)
  File "C:\Software\Anaconda3\lib\site-packages\qtconsole\console_widget.py", line 894, in _append_custom
    result = insert(cursor, input, *args, **kwargs)
  File "C:\Software\Anaconda3\lib\site-packages\qtconsole\console_widget.py", line 1761, in _insert_plain_text
    self._pending_insert_text, buffer_size)Traceback (most recent call last):
  File "C:\Software\Anaconda3\lib\site-packages\qtconsole\console_widget.py", line 1494, in _on_flush_pending_stream_timer
    self._flush_pending_stream()
  File "C:\Software\Anaconda3\lib\site-packages\qtconsole\console_widget.py", line 1507, in _flush_pending_stream
    text = self._get_last_lines_from_list(text, buffer_size)
  File "C:\Software\Anaconda3\lib\site-packages\qtconsole\console_widget.py", line 1635, in _get_last_lines_from_list
    return_count=True)
  File "C:\Software\Anaconda3\lib\site-packages\qtconsole\console_widget.py", line 1610, in _get_last_lines
    pos = len(text)
TypeError: object of type 'int' has no len()

  File "C:\Software\Anaconda3\lib\site-packages\qtconsole\console_widget.py", line 1635, in _get_last_lines_from_list
    return_count=True)
  File "C:\Software\Anaconda3\lib\site-packages\qtconsole\console_widget.py", line 1610, in _get_last_lines
    pos = len(text)
TypeError: object of type 'int' has no len()
```

**Please provide any additional information below**
A similar error occurs when `input()` is called with any other type of argument that is not a string. E.g. running `input(101.0)` or `input(True)` also results in a Spyder internal error.
## Versions and main components
- Spyder Version: 2.3.9
- Python Version: 3.5.2
- Operating system: Windows 10 (Version 1607, OS Build 14393.10)
## Dependencies

IPython >=1.0      :  4.2.0 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.18.1 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.6.0   :  1.2.3 (OK)
pygments >=1.6     :  2.1.3 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.2.1 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
sympy >=0.7.3      :  1.0 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by goanpeca** [comment]
This seems no longer valid

<img width="598" alt="Screen Shot 2019-11-27 at 17 31 53" src="https://user-images.githubusercontent.com/3627835/69763642-d4d9af00-113b-11ea-97b8-2581482188a5.png">

Closing.
