### ISSUE TITLE
Debugger crashes spyder

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#336]
_From [anatoliy...@gmail.com](https://code.google.com/u/101136359641652000647/) on 2010-09-08T13:47:36Z_

What steps will reproduce the problem?

 1.  Create a simple program in .temp.  For example:
j = 2;
for i in range(0, 10):
    j+=i;
2.  Run->Debug
3.  Do whatever -- issue a couple of "next" commands, or click on the variable explorer.  I am not sure exactly which steps reproduce this problem, but activating the variable explorer and clicking on next seem to be the triggers. What is the expected output? What do you see instead? Spyder freezes and needs to be killed from console. What version of the product are you using? On what operating system? 2.0.0beta1 on Ubuntu Lucid, running inside VirtualBox on a Windows host 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=336_

**Comment by spyder-issues-migrator** [comment]
_From [anatoliy...@gmail.com](https://code.google.com/u/101136359641652000647/) on 2010-09-17T12:07:08Z_

Bug still present in beta3.  Maybe it's related to the bug 381 I submitted?

**Comment by spyder-issues-migrator** [comment]
_From [anatoliy...@gmail.com](https://code.google.com/u/101136359641652000647/) on 2010-10-06T14:20:53Z_

Bug still present in beta4.  I am now confident that it has to do with the object explorer.  When I set the autorefresh interval to 10 seconds instead of 3, I can go on debugging for a lot longer before it freezes.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-07T12:50:37Z_

This issue was closed by revision 65a4023618 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-07T12:50:47Z_

It should be fixed in mercurial repository.
Please check if it works for you.
thx!

**Comment by spyder-issues-migrator** [comment]
_From [anatoliy...@gmail.com](https://code.google.com/u/101136359641652000647/) on 2010-10-15T14:54:47Z_

I believe the bug is still present in beta5:-(  However, I just upgraded from Lucid to Meerkat -- bad idea!  It is possible that the new problems stem from that upgrade, but honestly my intuition is that the two are independent.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-16T02:48:28Z_

**Status:** Accepted  
  **Labels:** -Priority-Medium Priority-High

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-16T02:48:55Z_

**Cc:** timmiche...@gmx-topmail.de

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-16T02:49:43Z_

**Labels:** OpSys-Linux

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-16T04:03:50Z_

To help me debug this, try to enable the debug mode in Spyder's 
monitor by replacing DEBUG = False by DEBUG = True in spyderlib/ 
widgets/externalshell/monitor.py, line 17. 
If it works, it should write a log file named 'monitor_errors.txt' in 
your ~/.spyder2 directory. 
thx!

**Comment by spyder-issues-migrator** [comment]
_From [anatoliy...@gmail.com](https://code.google.com/u/101136359641652000647/) on 2010-10-16T21:45:51Z_

This is still happening on a fresh install of 64-bit Meerkat inside a VirtualBox.  The debug mode is enabled:
\>>> import spyderlib
\>>> spyderlib.widgets.externalshell.monitor.DEBUG
True

However, no log file is produced:

akats@nevsky:~/.spyder2$ ls -all
total 56
drwxr-xr-x  3 akats akats  4096 2010-10-17 00:15 .
drwxr-xr-x 32 akats akats  4096 2010-10-16 23:53 ..
-rw-r--r--  1 akats akats    67 2010-10-17 00:17 .history_internal.py
-rw-r--r--  1 akats akats   756 2010-10-17 00:24 .history.py
-rw-r--r--  1 akats akats     0 2010-10-17 00:22 .inspector
-rw-r--r--  1 akats akats     0 2010-10-17 00:17 .onlinehelp
-rw-r--r--  1 akats akats     6 2010-10-17 00:17 .projects
drwxr-xr-x  2 akats akats  4096 2010-10-17 00:17 .ropeproject
-rw-r--r--  1 akats akats 15393 2010-10-17 00:24 .spyder.ini
-rw-r--r--  1 akats akats    88 2010-10-17 00:17 .spyderproject
-rw-r--r--  1 akats akats    75 2010-10-16 17:10 template.py
-rw-r--r--  1 akats akats   176 2010-10-17 00:22 .temp.py
-rw-r--r--  1 akats akats    11 2010-10-17 00:17 .workingdir
akats@nevsky:~/.spyder2$ 

This does not happen every time -- once I was able to go through one loop of that simple program, and saw the variables i and j in the variable explorer--yess!. But it froze before the second loop.  Also, even though my autorefresh was set for 3 seconds, it took a lot longer than that for these variables to appear.  On other runs, it froze before showing anything in the variable explorer.

I tried to find the file that implements the variable explorer and enable a debugging mode there, but I was not able to.  Really looking forward to this feature, and wish I could be more help!  Let me know what else I can do.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-17T00:36:36Z_

Would it be possible for you to send me the script which cause this crash?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-17T01:05:02Z_

Oh sorry, I completely forgot that you already did:
j = 2;
for i in range(0, 10):
    j+=i;

So, basically, if you debug this script in a *dedicated* interpreter (not in the current interpreter, isn't it?), and type 'n' several times in pdb, Spyder crashes.

Is that it?
Or is it necessary to edit variables in the variable explorer?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-17T07:35:36Z_

Bug reproduced!

I should be able to propose a bug fix very soon (in the next hours...).

**Status:** Started

**Comment by spyder-issues-migrator** [comment]
_From [anatoliy...@gmail.com](https://code.google.com/u/101136359641652000647/) on 2010-10-17T08:52:53Z_

Perfect!

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-17T12:34:35Z_

This issue was closed by revision deeed3f88f .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-17T12:48:14Z_

So now it should be fixed... keep me posted!

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-17T13:20:46Z_

issue #365 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [anatoliy...@gmail.com](https://code.google.com/u/101136359641652000647/) on 2010-10-17T17:57:56Z_

Much better, thanks!

Continuing with the same example, try Run->Debug, continue a few times, and then wait.  Even though my autorefresh is defaulted at 3000ms, it takes nearly 20 seconds for the updated j to appear in the variable explorer, unless I click refresh.  Now quit debugger, and double-click on the value for j.  I get the following traceback:  

\>>> Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/widgets/objecteditor.py", line 46, in oedit
    raise RuntimeError("Unsupported datatype")
RuntimeError: Unsupported datatype
\>>> 

Also, in the mercurial head, variable explorer does not work for IPython consoles.  I would type k=6, wait, refresh, and nothing would happen.  Is that normal?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-19T01:06:46Z_

Of course that's not normal... The variable explorer should work with IPython consoles. On my machine (Ubuntu 10.10, up-to-date), it works with both IPython and Python interpreters.

Could you please give me more details about your machine configuration: Python version, IPython version, ...

BTW, please check again for the 'monitor_errors.txt' file in folder '~/.spyder2'.

**Status:** Started

**Comment by spyder-issues-migrator** [comment]
_From [anatoliy...@gmail.com](https://code.google.com/u/101136359641652000647/) on 2010-10-19T10:05:25Z_

I have amd64 Ubuntu 10.10, also up to date:

akats@nevsky:~/.spyder2$ python --version
Python 2.6.6
akats@nevsky:~/.spyder2$ 
akats@nevsky:~/.spyder2$ ipython -Version
0.10
akats@nevsky:~/.spyder2$ 

I made the following experiment
1.  delete monitor_errors.txt
2.  run spyder
3.  open IPYthon interpeter
4.  k=10
5.  k

This displays k=10 in the output, but the variable explorer is not updated.  Repeating the experiment with python console updates the variable explorer promptly.
In my Ubuntu software center, it lists my IPython version as 0.10.2-ubuntu1.  Does the variable explorer depend on any other external packages?

I may have solved my configuration issues on my 32-bit Meerkat.  If it helps you, I can try(fingers crossed) to repeat the experiment there.  I did verify that Debug=True in monitor.py

**Comment by spyder-issues-migrator** [comment]
_From [anatoliy...@gmail.com](https://code.google.com/u/101136359641652000647/) on 2010-10-19T10:34:39Z_

Experiment 2:
Run->Debug that simple script.  Press continue a few times, then press quit.  After quitting debug , double-click on the '8' of 'j' in the variable explorer.  I get this:
(Pdb) c
\> /home/akats/.spyder2/.temp.py(11)<module>()
-> j = j + i;
(Pdb) c
\> /home/akats/.spyder2/.temp.py(11)<module>()
-> j = j + i;
(Pdb) c
\> /home/akats/.spyder2/.temp.py(11)<module>()
-> j = j + i;
(Pdb) c
\> /home/akats/.spyder2/.temp.py(11)<module>()
-> j = j + i;
(Pdb) c
\> /home/akats/.spyder2/.temp.py(11)<module>()
-> j = j + i;
(Pdb) q
\>>> Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/widgets/objecteditor.py", line 46, in oedit
    raise RuntimeError("Unsupported datatype")
RuntimeError: Unsupported datatype
\>>> 

Also it takes between 6 and 28 seconds between when I press 'c' in pdb, and the value is updated.  All of this is in python interpreter.  This does not happen every time.  So maybe you won't be able to reproduce it.  monitor_errors.txt stays empty throughout this whole process.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-26T09:58:56Z_

This issue was closed by revision e54e1fd772 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [anatoliy...@gmail.com](https://code.google.com/u/101136359641652000647/) on 2010-10-29T10:15:59Z_

Fix verified.  Thanks Pierre!

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-29T13:15:23Z_

Good.

Feels really great to have finally kicked this bug's ass!! :))

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-24T07:36:09Z_

This issue was closed by revision 65a4023618cb .

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-24T07:36:16Z_

This issue was closed by revision deeed3f88f2d .

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-24T07:36:21Z_

This issue was closed by revision e54e1fd7724b .
