### ISSUE TITLE
Spyder wont start unless file ".spyderproject" is deleted. UnpicklingError

### ISSUE THREAD

**Issue by MakGre** [spyder-ide/spyder#3363]
## Description of your problem

**What steps will reproduce the problem?**

1. python spyder --reset, uninstall and reinstall via Ubuntu Software Center
2. create spyder workspace in empty directory "~/workspace/"
3. create new Project called "Mixture_Model"
4. close spyder
5. start spyder (via Ubuntu launcher), startup fails, spyder crashes
6. after deleting "~/workspace/Mixture_Model/.spyderproject" spyder starts, automatically recreates the .spyderproject file
7. after closing spyder, same behavior as in step 5

**What is the expected output? What do you see instead?**

Expected spyder to start, instead it crashed

**Please provide any additional information below**

Repeating the exact same procedure but with project name "A" results in no crash, but normal startup.

## content of spyder_crash.log

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 2152, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 2047, in run_spyder
    main.setup()
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 793, in setup
    self.projectexplorer = ProjectExplorer(self)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/projectexplorer.py", line 37, in __init__
    self.load_config()
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/projectexplorer.py", line 137, in load_config
    self.set_workspace(self.get_option('workspace', None))
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/projectexplorer.py", line 1296, in set_workspace
    self.treewidget.set_workspace(path)
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/projectexplorer.py", line 696, in set_workspace
    self.workspace.set_root_path(root_path)
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/projectexplorer.py", line 278, in set_root_path
    self.load()
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/projectexplorer.py", line 307, in load
    setattr(self, attr, data[attr])
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/projectexplorer.py", line 257, in _set_project_paths
    self.add_project(root_path)
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/projectexplorer.py", line 382, in add_project
    project.set_root_path(root_path)
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/projectexplorer.py", line 86, in set_root_path
    self.load()
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/projectexplorer.py", line 125, in load
    data = cPickle.loads(fdesc.read())
UnpicklingError: unpickling stack underflow

## Versions and main components

* Spyder Version: v2.2.5+dfsg from Ubuntu Software Center
* Python Version: 2.7.6
* Operating system: ubuntu 14.04 LTS (latest updates as of August 19, 2016)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=0.13  :  1.2.1 (OK)
matplotlib >=1.0:  1.3.1 (OK)
pep8 >=0.6      :  1.4.6 (OK)
pyflakes >=0.5.0:  0.8.1 (OK)
pylint >=0.25   :  1.1.0 (OK)
rope >=0.9.2    :  0.9.2 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
sympy >=0.7.0   :  None (NOK)

**Comment by ccordoba12** [comment]
This will be solved in Spyder 3.0, thanks for reporting.
