### ISSUE TITLE
IPython kernels fail to start because of problems with history

### ISSUE THREAD

**Issue by llirikkcoder** [spyder-ide/spyder#3376]
Please, answer hot to fix this problem:

```
"Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> C:\Users\Legolas\Anaconda3\lib\site-packages\nbformat\current.py:19: UserWarning: nbformat.current is deprecated.

- use nbformat for read/write/validate public API
- use nbformat.vX directly to composing notebooks of a particular version

  """)
Traceback (most recent call last):
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\plugins\externalconsole.py", line 1246, in toggle_view
    self.open_interpreter()
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\plugins\externalconsole.py", line 1258, in open_interpreter
    interact=True, debug=False, python=True)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\plugins\externalconsole.py", line 832, in start
    show_elapsed_time=show_elapsed_time)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\pythonshell.py", line 207, in __init__
    show_elapsed_time=show_elapsed_time)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\baseshell.py", line 73, in __init__
    self.shell = self.SHELL_CLASS(parent, get_conf_path(history_filename))
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\pythonshell.py", line 39, in __init__
    PythonShellWidget.__init__(self, parent, history_filename, profile)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\shell.py", line 673, in __init__
    ShellBaseWidget.__init__(self, parent, history_filename, profile)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\shell.py", line 63, in __init__
    self.history = self.load_history()
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\shell.py", line 494, in load_history
    if rawhistory[1] != self.INITHISTORY[1]:
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\plugins\ipythonconsole.py", line 656, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\plugins\ipythonconsole.py", line 832, in create_new_client
    self.main.extconsole.start_ipykernel(client, give_focus=give_focus)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\plugins\externalconsole.py", line 1273, in start_ipykernel
    ipyclient=client, give_ipyclient_focus=give_focus)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\plugins\externalconsole.py", line 832, in start
    show_elapsed_time=show_elapsed_time)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\pythonshell.py", line 207, in __init__
    show_elapsed_time=show_elapsed_time)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\baseshell.py", line 73, in __init__
    self.shell = self.SHELL_CLASS(parent, get_conf_path(history_filename))
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\pythonshell.py", line 39, in __init__
    PythonShellWidget.__init__(self, parent, history_filename, profile)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\shell.py", line 673, in __init__
    ShellBaseWidget.__init__(self, parent, history_filename, profile)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\shell.py", line 63, in __init__
    self.history = self.load_history()
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\shell.py", line 494, in load_history
    if rawhistory[1] != self.INITHISTORY[1]:
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\plugins\ipythonconsole.py", line 832, in create_new_client
    self.main.extconsole.start_ipykernel(client, give_focus=give_focus)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\plugins\externalconsole.py", line 1273, in start_ipykernel
    ipyclient=client, give_ipyclient_focus=give_focus)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\plugins\externalconsole.py", line 832, in start
    show_elapsed_time=show_elapsed_time)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\pythonshell.py", line 207, in __init__
    show_elapsed_time=show_elapsed_time)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\baseshell.py", line 73, in __init__
    self.shell = self.SHELL_CLASS(parent, get_conf_path(history_filename))
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\pythonshell.py", line 39, in __init__
    PythonShellWidget.__init__(self, parent, history_filename, profile)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\shell.py", line 673, in __init__
    ShellBaseWidget.__init__(self, parent, history_filename, profile)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\shell.py", line 63, in __init__
    self.history = self.load_history()
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\shell.py", line 494, in load_history
    if rawhistory[1] != self.INITHISTORY[1]:
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\plugins\ipythonconsole.py", line 832, in create_new_client
    self.main.extconsole.start_ipykernel(client, give_focus=give_focus)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\plugins\externalconsole.py", line 1273, in start_ipykernel
    ipyclient=client, give_ipyclient_focus=give_focus)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\plugins\externalconsole.py", line 832, in start
    show_elapsed_time=show_elapsed_time)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\pythonshell.py", line 207, in __init__
    show_elapsed_time=show_elapsed_time)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\baseshell.py", line 73, in __init__
    self.shell = self.SHELL_CLASS(parent, get_conf_path(history_filename))
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\pythonshell.py", line 39, in __init__
    PythonShellWidget.__init__(self, parent, history_filename, profile)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\shell.py", line 673, in __init__
    ShellBaseWidget.__init__(self, parent, history_filename, profile)
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\shell.py", line 63, in __init__
    self.history = self.load_history()
  File "C:\Users\Legolas\Anaconda3\lib\site-packages\spyderlib\widgets\shell.py", line 494, in load_history
    if rawhistory[1] != self.INITHISTORY[1]:
IndexError: list index out of range"
```

**Comment by ccordoba12** [comment]
Running

    spyder --reset

in a console should fix the problem for you.

**Comment by ccordoba12** [comment]
Closing because this is a very old bug.
