### ISSUE TITLE
Spyder does not launch, throws an AttributeError instead

### ISSUE THREAD

**Issue by DominikKyriakos** [spyder-ide/spyder#3424]
I tried installing Spyder 3.0.0 beta6 on my Ubuntu 14.04 machine with Python 3.5 both with pip and using conda as recommended. In both cases, trying to launch spyder resulted in the following AttributeError:

Traceback (most recent call last):
  File "/home/domi89/anaconda3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 3025, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/domi89/anaconda3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 2929, in run_spyder
    main.setup()
  File "/home/domi89/anaconda3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 1156, in setup
    self.setup_layout(default=False)
  File "/home/domi89/anaconda3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 1417, in setup_layout
    self.setup_default_layouts('default', settings)
  File "/home/domi89/anaconda3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 1596, in setup_default_layouts
    widget.toggle_view(True)
  File "/home/domi89/anaconda3/lib/python3.5/site-packages/spyder/plugins/__init__.py", line 521, in toggle_view
    self.dockwidget.show()
AttributeError: 'NoneType' object has no attribute 'show'

## Versions and main components

* Spyder Version: Spyder 3.0.0 beta6
* Python Version: 3.5
* Operating system: Ubuntu 14.04

**Comment by jitseniesen** [comment]
Thanks for your report. I think this is fixed in commit a75acf41 which will be part of the forthcoming 3.0.0 beta7 release.So either wait till that release or install the version from git (or add the two lines from that commit yourself).

Potentially, un-installing the offending plugin may be a workaround.

**Comment by DominikKyriakos** [comment]
Many thanks back! I will wait for beta7.

**Comment by ccordoba12** [comment]
Thanks for reporting. As @jitseniesen said, this is going to be fixed in beta7 ;-)
