### ISSUE TITLE
Spyder 3.0.0: ImportError: No module named 'PyQt4' on fresh conda env Python 3.5/2.7

### ISSUE THREAD

**Issue by scienceopen** [spyder-ide/spyder#3485]
## Upon importing Matplotlib.figure, get PyQt4 import error.
This happens even when not using Spyder, so now I can't use matplotlib at all even without Spyder.

**What steps will reproduce the problem?**

1. conda update conda; conda create -n spydtest; source activate spydtest
2. conda install spyder matplotlib
3. from matplotlib.pyplot import figure

**What is the expected output? What do you see instead?**
> from matplotlib.pyplot import figure
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/miniconda3/envs/spyd/lib/python3.5/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "~/miniconda3/envs/spyd/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "~/miniconda3/envs/spyd/lib/python3.5/site-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "~/miniconda3/envs/spyd/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import QtCore
  File "~/miniconda3/envs/spyd/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "~/miniconda3/envs/spyd/lib/python3.5/site-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named 'PyQt4'

**Please provide any additional information below**
Spyder 3.0 beta 1-6 worked fine. Spyder 3.0 release newly installed PyQT5 (i had pyqt4 before) then this error started

## Versions and main components

* Spyder Version: 3.0.0 release
* Python Version: 3.5.2
* Operating system: Ubuntu 16.04
* Matplotlib: 1.5.3

## Dependencies
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  None (NOK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by scienceopen** [comment]
This is resolved by editing `~/.config/matplotlib/matplotlibrc` and setting

    backend: qt5agg
