### ISSUE TITLE
spyder internal console error

### ISSUE THREAD

**Issue by frankforp** [spyder-ide/spyder#3531]
Hi everybody,

when starting Spyder i get the following error:

Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> Traceback (most recent call last):
  File "C:\Users\pwang\Works\Tools\spyder-master\spyderlib\app\spyder.py", line 2610, in edit_preferences
    widget = plugin.create_configwidget(dlg)
  File "C:\Users\pwang\Works\Tools\spyder-master\spyderlib\plugins\__init__.py", line 395, in create_configwidget
    configwidget.initialize()
  File "C:\Users\pwang\Works\Tools\spyder-master\spyderlib\plugins\configdialog.py", line 71, in initialize
    self.setup_page()
  File "C:\Users\pwang\Works\Tools\spyder-master\spyderlib\plugins\ipythonconsole.py", line 255, in setup_page
    if programs.is_module_installed('wxPython'):
  File "C:\Users\pwang\Works\Tools\spyder-master\spyderlib\utils\programs.py", line 440, in is_module_installed
    actver = get_module_version(module_name)
  File "C:\Users\pwang\Works\Tools\spyder-master\spyderlib\utils\programs.py", line 382, in get_module_version
    mod = __import__(module_name)
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wxPython\__init__.py", line 15, in <module>
    import _wx
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wxPython\_wx.py", line 3, in <module>
    from _core import *
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wxPython\_core.py", line 34, in <module>
    wxDEFAULT_CONTROL_BORDER = wx._core.DEFAULT_CONTROL_BORDER
AttributeError: 'module' object has no attribute 'DEFAULT_CONTROL_BORDER'
Traceback (most recent call last):
  File "C:\Users\pwang\Works\Tools\spyder-master\spyderlib\app\spyder.py", line 2610, in edit_preferences
    widget = plugin.create_configwidget(dlg)
  File "C:\Users\pwang\Works\Tools\spyder-master\spyderlib\plugins\__init__.py", line 395, in create_configwidget
    configwidget.initialize()
  File "C:\Users\pwang\Works\Tools\spyder-master\spyderlib\plugins\configdialog.py", line 71, in initialize
    self.setup_page()
  File "C:\Users\pwang\Works\Tools\spyder-master\spyderlib\plugins\ipythonconsole.py", line 255, in setup_page
    if programs.is_module_installed('wxPython'):
  File "C:\Users\pwang\Works\Tools\spyder-master\spyderlib\utils\programs.py", line 440, in is_module_installed
    actver = get_module_version(module_name)
  File "C:\Users\pwang\Works\Tools\spyder-master\spyderlib\utils\programs.py", line 382, in get_module_version
    mod = __import__(module_name)
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wxPython\__init__.py", line 15, in <module>
    import _wx
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wxPython\_wx.py", line 3, in <module>
    from _core import *
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wxPython\_core.py", line 34, in <module>
    wxDEFAULT_CONTROL_BORDER = wx._core.DEFAULT_CONTROL_BORDER
AttributeError: 'module' object has no attribute 'DEFAULT_CONTROL_BORDER'

when I run the py scripts, the spyder IDE will crashed , also i can not debug the programs, it will lead to the same result,

I just update the spyder to the latest version as
![spyder version](https://cloud.githubusercontent.com/assets/5992008/19335046/d202fe08-9132-11e6-8fb0-516fe6847e9d.png)

Can anyone help?

Thank you very much！

**Comment by frankforp** [comment]
I install the spyder  again after deleting all the spyder files, it woks fine now.
