### ISSUE TITLE
Problem with User Module Deleter (UMD)?

### ISSUE THREAD

**Issue by ethankruse** [spyder-ide/spyder#3547]
## Description of your problem
I can only run my script in a console once. If I hit run on the exact same script again, I get import errors, and it seems to be due to UMD problems. 

**What steps will reproduce the problem?**

1. Run a script that loads some local packages twice in the same ipython console.

**What is the expected output? What do you see instead?**
The same output as before. Instead I get this mess

```
runfile('/astro/users/eakruse/circumbinary/code/examine_qats_out.py', wdir='/astro/users/eakruse/circumbinary/code')
0.5 2
remove_flares now part of remove_outliers.

runfile('/astro/users/eakruse/circumbinary/code/examine_qats_out.py', wdir='/astro/users/eakruse/circumbinary/code')
Reloaded modules: ekruse.qatsparams, everest.config, everest.usertools,
 k2plr.huber, ekruse.supplements, everest.fits, mpl_toolkits, ekruse.QATSanalysis, 
pysyzygy, everest.compute, ekruse.sin_fit, k2plr.config, everest.utils, 
ekruse.runQATS, everest.detrend, everest, mpl_toolkits.axes_grid1.mpl_axes,
 mpl_toolkits.axisartist.clip_path, george, ekruse.settings, k2plr,
 mpl_toolkits.axes_grid.axislines, everest.sources, ekruse, george.kernels, 
george._kernels, k2plr.mast, mpl_toolkits.axes_grid.inset_locator,
 mpl_toolkits.axes_grid.axes_grid, pysyzygy.plot, mpl_toolkits.axisartist.grid_helper_curvelinear,
 mpl_toolkits.axes_grid1.axes_grid, mpl_toolkits.axisartist.axislines, george.gp,
 everest.usertools.ui, everest.crowding, k2plr.api, mpl_toolkits.axes_grid1, 
mpl_toolkits.axes_grid.axes_size, george.utils, ekruse.transit_mcmc, ekruse.QATS, 
mpl_toolkits.axes_grid1.inset_locator, k2plr.ld, ekruse.loadlc_db, mpl_toolkits.axes_grid.axes_divider,
 ekruse.river_plot, mpl_toolkits.axes_grid1.axes_divider, everest.gp, everest.run,
 mpl_toolkits.axisartist.floating_axes, george.basic, everest.transit, everest.usertools.ccd, 
mpl_toolkits.axes_grid1.axes_size, everest.plot, mpl_toolkits.axes_grid1.colorbar,
 mpl_toolkits.axisartist, ekruse.lightcurve, everest.usertools.selector, ekruse.deltachisquare,
 everest.data, everest.pool, mpl_toolkits.axisartist.grid_finder, pysyzygy.transit,
 ekruse.transit_times, ekruse.mandel_agol_py, k2plr.kplr, mpl_toolkits.axes_grid1.parasite_axes, 
everest.kernels, mpl_toolkits.axisartist.axis_artist, george.hodlr, everest.usertools.detector, 
mpl_toolkits.axisartist.axisline_style, mpl_toolkits.axes_grid
Traceback (most recent call last):

  File "<ipython-input-2-acda52d58609>", line 1, in <module>
    runfile('/astro/users/eakruse/circumbinary/code/examine_qats_out.py', wdir='/astro/users/eakruse/circumbinary/code')

  File "/astro/apps6/anaconda2.0/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "/astro/apps6/anaconda2.0/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)

  File "/astro/users/eakruse/circumbinary/code/examine_qats_out.py", line 4, in <module>
    import ekruse as ek

  File "/astro/users/eakruse/ekruse/ekruse/__init__.py", line 27, in <module>
    from transit_mcmc import tran_chi, initerr, run_mcmc, everest_fix, transit_mcmc, make_plots

  File "/astro/users/eakruse/ekruse/ekruse/transit_mcmc.py", line 16, in <module>
    from everest import Everest

  File "/astro/users/eakruse/everest/everest/__init__.py", line 38, in <module>
    from . import config, compute, crowding, data, detrend, fits, gp, kernels, pool, \

  File "/astro/users/eakruse/everest/everest/usertools/__init__.py", line 5, in <module>
    from .ui import Everest, Mask

  File "/astro/users/eakruse/everest/everest/usertools/ui.py", line 21, in <module>
    from .detector import Detector

  File "/astro/users/eakruse/everest/everest/usertools/detector.py", line 25, in <module>
    from mpl_toolkits.axes_grid1 import make_axes_locatable

ImportError: No module named axes_grid1
```

**Please provide any additional information below**
I guess my main question is why is mpl_toolkits getting reloaded at all? That's not a user module.

Then, how can I turn the reloading off or only have it work for certain user modules? I thought
I was able to do that in previous versions of Spyder, but I've looked in the documentation, I've googled, and gone through all the preferences and can't seem to find any mention of the UMD anymore.

## Versions and main components

* Spyder Version: 3.0.0
* Python Version:  2.7.12
* Operating system: CentOS 7.2

**Comment by ccordoba12** [comment]
UMR, as it's called now, it's located in

    Preferences > Python Interpreter

in Spyder 3.0. There you add `mpl_toolkits` as an excluded module :-)

**Comment by ethankruse** [comment]
Sigh. I swear I went through all the preferences 5 times. Thanks, things look much better now. This is closed on my end now, though I guess I'm still confused why mpl_toolkits was being reloaded at all since that's not a user module.

**Comment by ccordoba12** [comment]
Probably because it's installed in a writable location.

**Comment by ethankruse** [comment]
@ccordoba12 Thanks for being so kind and helping out so fast. I appreciate it!
