### ISSUE TITLE
Unable to launch spyder From Anaaconda Navigator

### ISSUE THREAD

**Issue by RG2007** [spyder-ide/spyder#3644]
## Description of your problem
When I try to launch spyder getting Spyder crashed during last session. Try python spyder --reset.
I tried  python -c "from spyderlib.spyder import main; main()" --reset but still no luck. Can anyone please help me to solve this issue.

Thank you
**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
* Python Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
You don't even what Spyder version are using. Closing, we don't have time for this :-)

**Comment by RG2007** [comment]
Sorry for the inconvenience. I am using spyder 2.3.9 and python 3.4. If you have time please help me or else Thank you for your patience.

**Comment by jitseniesen** [comment]
@RG2007 Try upgrading spyder to 3.0.1 and/or python to 3.5. There are some issues with Python 3.4 and Qt 4 on Windows (like issue #2858). I doubt anybody has time to look at older versions at the moment.

**Comment by RG2007** [comment]
Thank you @jitseniesen .

**Comment by RG2007** [comment]
I did upgrade spyder to 3.0.1 and python to 3.5. Still I am unable to launch spyder.  This is the error that I m getting.
Traceback (most recent call last):
  File "C:\Users\RG\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2998, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\RG\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2902, in run_spyder
    main.setup()
  File "C:\Users\RG\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1005, in setup
    from xy.config import DOC_PATH as xy_doc_path
  File "C:\Users\RG\xy.py", line 34, in <module>
    Data=numpy.genfromtxt('MyData.csv',usecols=rndm_indx);
  File "C:\Users\RG\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\lib\npyio.py", line 1453, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rb'))
  File "C:\Users\RG\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\lib\_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "C:\Users\RG\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\lib\_datasource.py", line 501, in open
    raise IOError("%s not found." % path)
OSError: MyData.csv not found.

**Comment by ccordoba12** [comment]
Please remove or rename this file

    C:\Users\RG\xy.py

and try again

**Comment by RG2007** [comment]
It worked. Thank you.
