### ISSUE TITLE
Cannot launch Spyder after latest Ubuntu update

### ISSUE THREAD

**Issue by albertprinn** [spyder-ide/spyder#3649]
When I try to launch Spyder I receive this error message:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 2331, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 2215, in run_spyder
    main.setup()
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 734, in setup
    message=_("Spyder Internal Console\n\n"
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/console.py", line 74, in __init__
    self.find_widget.set_editor(self.shell)
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/findreplace.py", line 260, in set_editor
    from spyderlib.qt.QtWebKit import QWebView
  File "/usr/lib/python2.7/dist-packages/spyderlib/qt/QtWebKit.py", line 10, in <module>
    from PyQt4.QtWebKit import *  # analysis:ignore
ImportError: No module named QtWebKit

## Versions and main components

* Spyder Version: 2.3.8+dfsg1-1build1
* Python Version: 2.7
* Operating system: Ubuntu 16.10

**Comment by ccordoba12** [comment]
Ubuntu/Debian broke Spyder by removing the Qt4 QtWebKit module, which is not our fault.

We recommend you to use the Anaconda Python distribution instead.
