### ISSUE TITLE
namespace browser crashes on debug

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#365]
_From [christop...@gmail.com](https://code.google.com/u/105753816054647931594/) on 2010-09-16T04:11:48Z_

What steps will reproduce the problem?

 1. run a debug session in the current console (with any file) 2. 3. What is the expected output? What do you see instead? 'Variable explorer' does not work anymore. See trace back below. What version of the product are you using? On what operating system? spyder-2.0.0beta3 

Please provide any additional information below

. Traceback on the internal console:

Traceback (most recent call last):
  File "/Library/Python/2.5/site-packages/spyder-2.0.0beta3-py2.5.egg/spyderlib/widgets/externalshell/namespacebrowser.py", line 210, in auto_refresh
    self.refresh_table()
  File "/Library/Python/2.5/site-packages/spyder-2.0.0beta3-py2.5.egg/spyderlib/widgets/externalshell/namespacebrowser.py", line 227, in refresh_table
    self.set_data( monitor_get_remote_view(sock, settings) )
  File "/Library/Python/2.5/site-packages/spyder-2.0.0beta3-py2.5.egg/spyderlib/widgets/externalshell/monitor.py", line 85, in monitor_get_remote_view
    return pickle.loads( read_packet(sock) )
cPickle.UnpicklingError: invalid load key, '/'.
Traceback (most recent call last):
  File "/Library/Python/2.5/site-packages/spyder-2.0.0beta3-py2.5.egg/spyderlib/widgets/externalshell/namespacebrowser.py", line 210, in auto_refresh
    self.refresh_table()
  File "/Library/Python/2.5/site-packages/spyder-2.0.0beta3-py2.5.egg/spyderlib/widgets/externalshell/namespacebrowser.py", line 227, in refresh_table
    self.set_data( monitor_get_remote_view(sock, settings) )
  File "/Library/Python/2.5/site-packages/spyder-2.0.0beta3-py2.5.egg/spyderlib/widgets/externalshell/monitor.py", line 85, in monitor_get_remote_view
    return pickle.loads( read_packet(sock) )
cPickle.UnpicklingError: invalid load key, '7'.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=365_

**Comment by spyder-issues-migrator** [comment]
_From [christop...@gmail.com](https://code.google.com/u/105753816054647931594/) on 2010-09-16T02:23:40Z_

issue #336 seems to be related

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-17T13:19:28Z_

Exactly, this is related, and the bug is now fixed.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-17T13:19:58Z_

(in v2.0 mercurial repository)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-17T13:20:46Z_

**Status:** Duplicate  
  **Mergedinto:** 336
