### ISSUE TITLE
Spyder can't read unicode files

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#3665]
## Description of your problem

**What steps will reproduce the problem?**

Execute the following code:
```
with open('utf8.txt') as f:
    f.read()
```
Where utf8.txt contains:

> 你好

**What is the expected output? What do you see instead?**
I would expect to be able to read utf8 as I am using Python3

instead:
```
Traceback (most recent call last):

  File "<ipython-input-1-78db4c0e2afa>", line 1, in <module>
    runfile('/Users/local/Documents/PHD/Python/publications_update/untitled0.py', wdir='/Users/local/Documents/PHD/Python/publications_update')

  File "/Users/local/pyscripts/spyder/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "/Users/local/pyscripts/spyder/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/local/Documents/PHD/Python/publications_update/untitled0.py", line 8, in <module>
    f.read()

  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
```

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 4.0.0.dev0
* Python Version:3.5.2 64bits
* Operating system: OSX 10.11.6

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.2 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.5a1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by impact27** [comment]
This doesn't happens with the pip-installed spyder 3.0.1

**Comment by impact27** [comment]
Wait I have to investigate that a bit more
