### ISSUE TITLE
Variable explorer wouldn't work - how can I revert to spyder 2?

### ISSUE THREAD

**Issue by Paul-Yuchao-Dong** [spyder-ide/spyder#3686]
## Description of your problem

After many trys to get the variable explorer to work, i.e. showing the variable of current namespace, I realized that I'm not well equipped to solve this problem, and not be side-tracked with what I'm actually working on, I want to go back to spyder 2. Overall, the project is still great! Thanks Devs!

The variable explorer is just showing blanks now, no matter what kind of configuration.

I'm on Ubuntu 16.04, and I used `pip install -U --ignore-installed spyder` to upgrade the spyder 2 that shipped with anaconda to spyder 3, about 2 days ago.

now if I try to uninstall spyder 3, I get confirmation from pip asking if I want to uninstall spyder 2. 

Would someone tell me how to revert to Spyder 2?

**What steps will reproduce the problem?**

1. Fix the variable explorer in spyder 3, make it show the current namespace

**What is the expected output? What do you see instead?**
variables, I see blank

**Please provide any additional information below**
The internal console is showing below after I ran a script:
```
>>> Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/paul/anaconda3/lib/python3.5/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/home/paul/anaconda3/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 180, in _handle_execute_reply
    exec_count = msg['content']['execution_count']
KeyError: 'execution_count'
  File "/home/paul/anaconda3/lib/python3.5/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/home/paul/anaconda3/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 180, in _handle_execute_reply
    exec_count = msg['content']['execution_count']
KeyError: 'execution_count'
  File "/home/paul/anaconda3/lib/python3.5/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/home/paul/anaconda3/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 180, in _handle_execute_reply
    exec_count = msg['content']['execution_count']
KeyError: 'execution_count'
  File "/home/paul/anaconda3/lib/python3.5/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/home/paul/anaconda3/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 180, in _handle_execute_reply
    exec_count = msg['content']['execution_count']
KeyError: 'execution_count'
  File "/home/paul/anaconda3/lib/python3.5/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/home/paul/anaconda3/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 180, in _handle_execute_reply
    exec_count = msg['content']['execution_count']
KeyError: 'execution_count'
  File "/home/paul/anaconda3/lib/python3.5/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/home/paul/anaconda3/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 180, in _handle_execute_reply
    exec_count = msg['content']['execution_count']
KeyError: 'execution_count'
  File "/home/paul/anaconda3/lib/python3.5/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/home/paul/anaconda3/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 180, in _handle_execute_reply
    exec_count = msg['content']['execution_count']
KeyError: 'execution_count'
  File "/home/paul/anaconda3/lib/python3.5/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/home/paul/anaconda3/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 180, in _handle_execute_reply
    exec_count = msg['content']['execution_count']
KeyError: 'execution_count'
  File "/home/paul/anaconda3/lib/python3.5/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/home/paul/anaconda3/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 180, in _handle_execute_reply
    exec_count = msg['content']['execution_count']
KeyError: 'execution_count'
  File "/home/paul/anaconda3/lib/python3.5/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/home/paul/anaconda3/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 180, in _handle_execute_reply
    exec_count = msg['content']['execution_count']
KeyError: 'execution_count'
  File "/home/paul/anaconda3/lib/python3.5/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/home/paul/anaconda3/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 180, in _handle_execute_reply
    exec_count = msg['content']['execution_count']
KeyError: 'execution_count'
  File "/home/paul/anaconda3/lib/python3.5/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/home/paul/anaconda3/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 180, in _handle_execute_reply
    exec_count = msg['content']['execution_count']
KeyError: 'execution_count'
```

## Versions and main components

* Spyder Version: 3
* Python Version: 3.5
* Operating system: Ubuntu 16.04

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
> I'm on Ubuntu 16.04, and I used pip install -U --ignore-installed spyder to upgrade the spyder 2 that shipped with anaconda to spyder 3, about 2 days ago.

You did wrong here. Please uninstall Anaconda (because you most probably broke your installation by using pip in Anaconda), then reinstall it and to update Spyder please use conda instead of pip, like this

    conda update spyder

**Comment by Paul-Yuchao-Dong** [comment]
Wow thanks for the quick response! Yes, I tried to do conda update and it didn't work, that's why I switched to pip.

So I pip uninstalled spyder 3 and conda installed spyder 2, now it seems to be working and I'm not messing around with the upgrade.

bests

**Comment by ccordoba12** [comment]
Problem is Spyder 2 is not going to br maintained anymore. I don't understand why `conda update` didn't work for you :-/
