### ISSUE TITLE
Dependency to latest pyzmq-16.0.2 bugs: spyder crashes at launch. Partial solution:  pyzmq-16.0.1 works fine.

### ISSUE THREAD

**Issue by LeBarbouze** [spyder-ide/spyder#3725]
## Description of your problem

**What steps will reproduce the problem?**

1. Upgrade spyder to the latest version (3.0.2) `pip install --upgrade spyder`
2. Launch `spyder` from the command line crashes 
3. Dependency on the pyzmq package seems to be the problem

**What is the expected output? What do you see instead?**

Instead of launching the spyder GUI, it crashes with a window bug report. Here's the Traceback from command line:

```python
Boulot/anaconda2/lib/python2.7/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.c:212:17: fatal error: zmq.h: Aucun fichier ou dossier de ce type
compilation terminated.
Boulot/anaconda2/lib/python2.7/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.c:212:17: fatal error: zmq.h: Aucun fichier ou dossier de ce type
compilation terminated.
Traceback (most recent call last):
  File "/home/joachim/Boulot/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2998, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/joachim/Boulot/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2902, in run_spyder
    main.setup()
  File "/home/joachim/Boulot/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 808, in setup
    from spyder.plugins.editor import Editor
  File "/home/joachim/Boulot/anaconda2/lib/python2.7/site-packages/spyder/plugins/editor.py", line 41, in <module>
    from spyder.utils.introspection.manager import IntrospectionManager
  File "/home/joachim/Boulot/anaconda2/lib/python2.7/site-packages/spyder/utils/introspection/manager.py", line 20, in <module>
    from spyder.utils.introspection.plugin_client import PluginClient
  File "/home/joachim/Boulot/anaconda2/lib/python2.7/site-packages/spyder/utils/introspection/plugin_client.py", line 18, in <module>
    import zmq
  File "/home/joachim/Boulot/anaconda2/lib/python2.7/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/home/joachim/Boulot/anaconda2/lib/python2.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/joachim/Boulot/anaconda2/lib/python2.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/joachim/Boulot/anaconda2/lib/python2.7/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/joachim/Boulot/anaconda2/lib/python2.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /home/joachim/Boulot/anaconda2/lib/python2.7/site-packages/zmq/backend/cython/error.so: undefined symbol: zmq_strerror
```

**Please provide any additional information below**

The bug window raised by the spyder app advices to reset the config files, which I did by typing `spyder --reset`, but it didn't solve the problem.

It works back by reinstalling manually the earlier version of pyzmq package
```
pip install pyzmq==16.0.1
```

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 2.7
* Operating system: GNU Linux/Ubuntu

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.0 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
@minrk, do you know something about this error?

**Comment by minrk** [comment]
Something must have gone wrong in the manylinux wheels. I'll investigate.

**Comment by ccordoba12** [comment]
Thanks!

**Comment by minrk** [comment]
@LeBarbouze if you still have it, can you zip up the not-working site-packages/zmq and share it, so I can see what went wrong?

It looks like the manylinux wheels hadn't been uploaded yet for 16.0.2. Can you try installing again, now?

    pip uninstall pyzmq
    pip install -v pyzmq

**Comment by LeBarbouze** [comment]
Hi, here it is:

[zmp.zip](https://github.com/spyder-ide/spyder/files/607071/zmp.zip)

**Comment by LeBarbouze** [comment]
I upgraded pyzmq and it works fine now! Thanks.
