### ISSUE TITLE
Fast switch between files gives error for unicode files

### ISSUE THREAD

**Issue by wtjcn** [spyder-ide/spyder#3737]
## Fast switch between files Error
when have unicode in opened file name, and then
push “Fast switch between files (Ctrl+P)” on toolbar, Internal Console show:

>>> WARNING:traitlets:kernel restarted
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spyder/plugins/editor.py", line 1700, in call_file_switcher
    self.get_current_editorstack().open_fileswitcher_dlg()
  File "/usr/local/lib/python2.7/dist-packages/spyder/widgets/editor.py", line 590, in open_fileswitcher_dlg
    self.fileswitcher_dlg = FileSwitcher(self, self.tabs, self.data)
  File "/usr/local/lib/python2.7/dist-packages/spyder/widgets/fileswitcher.py", line 278, in __init__
    self.setup()
  File "/usr/local/lib/python2.7/dist-packages/spyder/widgets/fileswitcher.py", line 609, in setup
    self.setup_file_list(filter_text, current_path)
  File "/usr/local/lib/python2.7/dist-packages/spyder/widgets/fileswitcher.py", line 509, in setup_file_list
    text_item += "<br><i>{0:}</i>".format(short_paths[index])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 21-25: ordinal not in range(128)

no unicode, no error.

## Versions and main components
* Spyder Version: 3.0.2
* Python Version: 2.7.6
* Operating system: ubuntu linux

## Dependencies

Spyder 3.0.2 
Python 2.7.6 32bits, Qt 4.8.6, PyQt4 (API v2) 4.10.4 on Linux

**Comment by ccordoba12** [comment]
@dalthviz, please work on this one. It seems our switcher doesn't accept filenames with non-ascii characters on it.
