### ISSUE TITLE
IPython console stuck in "connecting to kernel"

### ISSUE THREAD

**Issue by mickeydonkey** [spyder-ide/spyder#3750]
## Description of your problem
launch spyder in terminal and IPython console stuck in "connecting to kernel", here is the info from Internal console:
```
Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> Traceback (most recent call last):
  File "/home/luot/miniconda2/envs/bk/lib/python3.4/site-packages/spyder/plugins/__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "/home/luot/miniconda2/envs/bk/lib/python3.4/site-packages/spyder/plugins/ipythonconsole.py", line 677, in toggle_view
    self.create_new_client(give_focus=False)
  File "/home/luot/miniconda2/envs/bk/lib/python3.4/site-packages/spyder/plugins/ipythonconsole.py", line 878, in create_new_client
    interpreter=pyexec)
  File "/home/luot/miniconda2/envs/bk/lib/python3.4/site-packages/spyder/utils/programs.py", line 427, in is_module_installed
    return eval(output.decode())
  File "<string>", line 1
    ]0;IPython: home/luotTrue
    ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/luot/miniconda2/envs/bk/lib/python3.4/site-packages/spyder/app/mainwindow.py", line 2568, in edit_preferences
    widget = plugin.create_configwidget(dlg)
  File "/home/luot/miniconda2/envs/bk/lib/python3.4/site-packages/spyder/plugins/__init__.py", line 378, in create_configwidget
    configwidget.initialize()
  File "/home/luot/miniconda2/envs/bk/lib/python3.4/site-packages/spyder/plugins/configdialog.py", line 71, in initialize
    self.setup_page()
  File "/home/luot/miniconda2/envs/bk/lib/python3.4/site-packages/spyder/plugins/externalconsole.py", line 245, in setup_page
    interpreter=interpreter))
  File "/home/luot/miniconda2/envs/bk/lib/python3.4/site-packages/spyder/utils/programs.py", line 427, in is_module_installed
    return eval(output.decode())
  File "<string>", line 1
    ]0;IPython: home/luotFalse
    ^
SyntaxError: invalid syntax

```

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 3.4.5
* Operating system: Ubuntu 16.04LTS

## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Please run in a terminal

    spyder --reset

and try again

**Comment by mickeydonkey** [comment]
That addresses my problem, Thank you ! @ccordoba12

**Comment by ccordoba12** [comment]
By the way, I think your problem was due to the fact that you selected the `ipython` executable as your Python interpreter in

    Preferences > Main Interpreter

But you must always select a Python interpreter there, i.e. `/usr/bin/python{2,3}`
