### ISSUE TITLE
Spyder 3.0.2 fails to start after --reset

### ISSUE THREAD

**Issue by chrjakob** [spyder-ide/spyder#3789]
## Description of your problem
I first installed Python 3.5 with Anaconda, then created a new environment for Python 2.7 under Anaconda. Spyder has been working fine under both Python versions until yesterday. Spyder is still working fine under Python 3.5. I recently updated to Spyder 3.0.2

**What steps will reproduce the problem?**

 I used the --reset command and can see some files are being deleted. I also tried deleting the .Spyder folder.

**What is the expected output? What do you see instead?**
After a reset, Spyder tries to launch as normal and I can see the splash scree, which disappears after a short while, but Spyder never launches. I then kill the python.exe processed (3 in total), and when launching Spyder again I get the "Spyder crashed during last session"-screen. 

**Please provide any additional information below**
I have also tried to uninstall and install spyder under the Python 2.7 environment, but no change. 

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 2.7
* Operating system: Windows 10

**Comment by ccordoba12** [comment]
Please run in a terminal

    spyder --show-console

and post here any errors shown by that command.

**Comment by chrjakob** [comment]
(py27) C:\Users\Christian>spyder --show-console
Traceback (most recent call last):
  File "C:\Users\Christian\Anaconda3\envs\py27\lib\site-packages\spyder\app\mainwindow.py", line 3001, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\Christian\Anaconda3\envs\py27\lib\site-packages\spyder\app\mainwindow.py", line 2905, in run_spyder
    main.setup()
  File "C:\Users\Christian\Anaconda3\envs\py27\lib\site-packages\spyder\app\mainwindow.py", line 888, in setup
    from spyder.plugins.ipythonconsole import IPythonConsole
  File "C:\Users\Christian\Anaconda3\envs\py27\lib\site-packages\spyder\plugins\ipythonconsole.py", line 59, in <module>
    from spyder.widgets.ipythonconsole import ClientWidget
  File "C:\Users\Christian\Anaconda3\envs\py27\lib\site-packages\spyder\widgets\ipythonconsole\__init__.py", line 14, in <module>
    from .namespacebrowser import NamepaceBrowserWidget
  File "C:\Users\Christian\Anaconda3\envs\py27\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 14, in <module>
    from ipykernel.pickleutil import CannedObject
  File "C:\Users\Christian\Anaconda3\envs\py27\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\Christian\Anaconda3\envs\py27\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "C:\Users\Christian\Anaconda3\envs\py27\lib\site-packages\IPython\__init__.py", line 48, in <module>
    from .core.application import Application
  File "C:\Users\Christian\Anaconda3\envs\py27\lib\site-packages\IPython\core\application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "C:\Users\Christian\Anaconda3\envs\py27\lib\site-packages\IPython\core\crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "C:\Users\Christian\Anaconda3\envs\py27\lib\site-packages\IPython\core\ultratb.py", line 128, in <module>
    from IPython.utils.terminal import get_terminal_size
  File "C:\Users\Christian\Anaconda3\envs\py27\lib\site-packages\IPython\utils\terminal.py", line 22, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size

**Comment by ccordoba12** [comment]
Please run

    conda install get_terminal_size

and try again to see if the problem is fixed :-)

**Comment by chrjakob** [comment]
# All requested packages already installed.
# packages in environment at C:\Users\Christian\Anaconda3\envs\py27:
#
get_terminal_size         1.0.0                    py27_0

**Comment by chrjakob** [comment]
I did pip uninstall backports.shutil_get_terminal_size and then installed it again. I'm now able to start Spyder but getting the following message: You have missing dependencies!
nbconvert >=4.0 None (NOK)

I checked and nbconvert 4.2.0 is installed..

**Comment by ccordoba12** [comment]
That's something for you to see how to solve :-)

At least Spyder is not crashing for you anymore.

**Comment by chrjakob** [comment]
Tnx for your help!
