### ISSUE TITLE
Spyder crashed at the beginning not able to import from hashlib

### ISSUE THREAD

**Issue by xgfanwku** [spyder-ide/spyder#3839]
## Description of your problem
On a Mac OSX 10.8.5, installed Anaconda2, updated all packages. 
A new environment condaX was then created, updated, and then installed netcdf4 and basemap and updated again (conda update --all). Tested in running directly at command line and in spyder, both matplotlib and basemap worked well.
Then, condaX was cloned to metuse, by command "conda create -n metuse --clone condaX"
Running python was okay and the above to modules were imported fine. Wanted to run spyder (3.0.2), spyder won't start and give the following messages:

(metuse) FXG-MacBook:~ xng02546$ spyder &
[1] 43659
(metuse) FXG-MacBook:~ xng02546$ ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/Users/xng02546/anaconda2/envs/metuse/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Users/xng02546/anaconda2/envs/metuse/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/Users/xng02546/anaconda2/envs/metuse/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Users/xng02546/anaconda2/envs/metuse/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/Users/xng02546/anaconda2/envs/metuse/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Users/xng02546/anaconda2/envs/metuse/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/Users/xng02546/anaconda2/envs/metuse/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Users/xng02546/anaconda2/envs/metuse/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/Users/xng02546/anaconda2/envs/metuse/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Users/xng02546/anaconda2/envs/metuse/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/Users/xng02546/anaconda2/envs/metuse/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Users/xng02546/anaconda2/envs/metuse/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512

(metuse) FXG-MacBook:~ xng02546$ Traceback (most recent call last):
  File "/Users/xng02546/anaconda2/envs/metuse/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 3001, in main
    mainwindow = run_spyder(app, options, args)
  File "/Users/xng02546/anaconda2/envs/metuse/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2905, in run_spyder
    main.setup()
  File "/Users/xng02546/anaconda2/envs/metuse/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 799, in setup
    from spyder.plugins.help import Help
  File "/Users/xng02546/anaconda2/envs/metuse/lib/python2.7/site-packages/spyder/plugins/help.py", line 33, in <module>
    from spyder.utils.help.sphinxify import (CSS_PATH, generate_context,
  File "/Users/xng02546/anaconda2/envs/metuse/lib/python2.7/site-packages/spyder/utils/help/sphinxify.py", line 30, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/Users/xng02546/anaconda2/envs/metuse/lib/python2.7/site-packages/jinja2/__init__.py", line 36, in <module>
    from jinja2.loaders import BaseLoader, FileSystemLoader, PackageLoader, \
  File "/Users/xng02546/anaconda2/envs/metuse/lib/python2.7/site-packages/jinja2/loaders.py", line 16, in <module>
    from hashlib import sha1
ImportError: cannot import name sha1

[1]+  Done                    spyder

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 2.7.12
* Operating system: Mac OSX 10.8.5

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by xgfanwku** [comment]
First using this place to find help and solutions. Let me know if anything is not right. Thanks!

**Comment by ccordoba12** [comment]
The problem is not with Spyder, it's with Jinja2, which can't load `hashlib.sha1`. I don't understand why it can't do it though :-/

**Comment by xgfanwku** [comment]
Thanks ccordoba12 for looking into this!  The problem might be also from the conda clone, I don't know. The "conda list" for both environments showed same packages, including jinja2 (2.8). Spyder started and ran well in environment condaX, but failed in the cloned one.

**Comment by ccordoba12** [comment]
Yeah, I'd say the problem lies in how conda is cloning envs. Maybe it's leaving some packages behind?

**Comment by xgfanwku** [comment]
Spyder starting problem solved. During the clone process, adding option "--copy" helped.
conda create -n metuse --clone condaX --copy

Sorry for raising this issue here.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it :-)
