### ISSUE TITLE
Object inspector prevents entering left parenthesis

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#386]
_From [H.Moritz...@gmail.com](https://code.google.com/u/104201738537083677924/) on 2010-09-20T05:33:55Z_

After some commands, entering left parenthesis after commands does not work in the ipython-shell any more. 

What steps will reproduce the problem?

 0. start a fresh ipython-shell in spyder
1. import os
2. os.system('ls')
3. figure()   # on my system, I cannot enter the left parenthesis What is the expected output? What do you see instead? I cannot enter the left parenthesis after the figure-command and other valid commands, but after invalid commands like "figu()" I can enter the left parenthesis. 
I think this has something to do with the object inspector, because it turns mad (shows either "no documentation available" even if there is a docstring, or shows the documentation of a previously entered command instead of the current command) What version of the product are you using? On what operating system? I'm using spyder2.0beta3 on a ubuntu10.04-64 bit system
IPython options:
-pylab -q4thread -colors LightBG -xmode Plain -editor gedit 

Please provide any additional information below

. This occurred also with other commands than "os.system", but on my system this bug is very reproducible. 

When I disable the "balloon-tips", the problem disappears... (-> bug in object explorer?)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=386_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-09-20T06:16:19Z_

Could you please show the 'internal console' ('View' menu > Internal console) and post its contents here: there's probably some traceback.

**Comment by spyder-issues-migrator** [comment]
_From [H.Moritz...@gmail.com](https://code.google.com/u/104201738537083677924/) on 2010-09-20T06:29:25Z_

This is the internal console's output:

Python 2.6.5 ( r265 :79063, Apr 16 2010, 13:57:41) 
[GCC 4.4.3] on linux2
Type "copyright", "credits" or "license" for more information.

\>>> Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/widgets/shell.py", line 300, in keyPressEvent
    self.postprocess_keyevent(event)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/widgets/shell.py", line 787, in postprocess_keyevent
    ShellBaseWidget.postprocess_keyevent(self, event)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/widgets/shell.py", line 444, in postprocess_keyevent
    self._key_parenleft(text)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/widgets/shell.py", line 864, in _key_parenleft
    self.show_docstring(self.get_last_obj(), call=True)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/widgets/shell.py", line 1005, in show_docstring
    self.inspector.set_object_text(text)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/plugins/inspector.py", line 221, in set_object_text
    self.show_help(text)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/plugins/inspector.py", line 342, in show_help
    self.editor.set_text(hlp_text)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/widgets/codeeditor/codeeditor.py", line 857, in set_text
    self.setPlainText(text)
TypeError: QPlainTextEdit.setPlainText(QString): argument 1 has unexpected type 'bool'

**Comment by spyder-issues-migrator** [comment]
_From [mproel...@googlemail.com](https://code.google.com/u/105494983286078857315/) on 2010-09-20T23:02:01Z_

Hello,

just to inform, I often issue the same problem, also in pdb sessions and didn't know how to reproduce it.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-09-25T07:18:56Z_

**Status:** Fixed
