### ISSUE TITLE
There was a power cut after which spyder doesn't launch.

### ISSUE THREAD

**Issue by tarunkhandelwal86** [spyder-ide/spyder#3862]
## Description of your problem
There was a power cut during the time I was suing spyder. After power suppy was restored I restarted the system and tried to launch spyder. It didn't work. Then I ran the command:
`spyder --show-console` 
Following was the error message which got printed:
Traceback (most recent call last):
  File "C:\Users\User-pc\Anaconda\lib\site-packages\spyderlib\spyder.py", line 2331, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\User-pc\Anaconda\lib\site-packages\spyderlib\spyder.py", line 2215, in run_spyder
    main.setup()
  File "C:\Users\User-pc\Anaconda\lib\site-packages\spyderlib\spyder.py", line 734, in setup
    message=_("Spyder Internal Console\n\n"
  File "C:\Users\User-pc\Anaconda\lib\site-packages\spyderlib\plugins\console.py", line 56, in __init__
    light_background=light_background)
  File "C:\Users\User-pc\Anaconda\lib\site-packages\spyderlib\widgets\internalshell.py", line 119, in __init__
    profile)
  File "C:\Users\User-pc\Anaconda\lib\site-packages\spyderlib\widgets\shell.py", line 673, in __init__
    ShellBaseWidget.__init__(self, parent, history_filename, profile)
  File "C:\Users\User-pc\Anaconda\lib\site-packages\spyderlib\widgets\shell.py", line 63, in __init__
    self.history = self.load_history()
  File "C:\Users\User-pc\Anaconda\lib\site-packages\spyderlib\widgets\shell.py", line 494, in load_history
    if rawhistory[1] != self.INITHISTORY[1]:
IndexError: list index out of range

Please help me with this.

**Comment by ccordoba12** [comment]
Please run in a terminal

    spyder --reset

and restart it again :-)

**Comment by tarunkhandelwal86** [comment]
@ccordoba12 Thank you so much for such a quick response. Spyder is working for me. :)
