### ISSUE TITLE
Spyder crashed during last session.

### ISSUE THREAD

**Issue by alihb** [spyder-ide/spyder#3868]
## Description of your problem

**What steps will reproduce the problem?**

1. my spyder3 error Spyder crashed during last session.
2. what is it?
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
* Python Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by bucricket** [comment]
I have the same issue using Spyder in environments other than root.  Any solution?

**Comment by ccordoba12** [comment]
Please run

    spyder --show-console

in a terminal and post here any errors you see there.

**Comment by bucricket** [comment]
Thanks! Please see the results.

Traceback (most recent call last):
  File "/Applications/anaconda/envs/pyDisALEXI/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 3001, in main
    mainwindow = run_spyder(app, options, args)
  File "/Applications/anaconda/envs/pyDisALEXI/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2905, in run_spyder
    main.setup()
  File "/Applications/anaconda/envs/pyDisALEXI/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 839, in setup
    self.findinfiles = FindInFiles(self)
  File "/Applications/anaconda/envs/pyDisALEXI/lib/python2.7/site-packages/spyder/plugins/findinfiles.py", line 52, in __init__
    include = self.include_patterns()
  File "/Applications/anaconda/envs/pyDisALEXI/lib/python2.7/site-packages/spyder/plugins/findinfiles.py", line 105, in include_patterns
    for ext in get_edit_extensions():
  File "/Applications/anaconda/envs/pyDisALEXI/lib/python2.7/site-packages/spyder/config/utils.py", line 139, in get_edit_extensions
    edit_filetypes = get_edit_filetypes()
  File "/Applications/anaconda/envs/pyDisALEXI/lib/python2.7/site-packages/spyder/config/utils.py", line 118, in get_edit_filetypes
    pygments_exts = _get_pygments_extensions()
  File "/Applications/anaconda/envs/pyDisALEXI/lib/python2.7/site-packages/spyder/config/utils.py", line 85, in _get_pygments_extensions
    for lx in lexers.get_all_lexers():
  File "/Applications/anaconda/envs/pyDisALEXI/lib/python2.7/site-packages/pygments/lexers/__init__.py", line 53, in get_all_lexers
    for lexer in find_plugin_lexers():
  File "/Applications/anaconda/envs/pyDisALEXI/lib/python2.7/site-packages/pygments/plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "/Applications/anaconda/envs/pyDisALEXI/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2290, in load
    self.require(*args, **kwargs)
  File "/Applications/anaconda/envs/pyDisALEXI/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2307, in require
    items = working_set.resolve(reqs, env, installer)
  File "/Applications/anaconda/envs/pyDisALEXI/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
DistributionNotFound: The 'gnureadline; sys_platform == "darwin" and platform_python_implementation == "CPython"' distribution was not found and is required by the application

**Comment by ccordoba12** [comment]
Try to run

    conda update setuptools

to see if that fixes your error.

**Comment by bucricket** [comment]
Running conda update setuptools didn’t seem to fix the problem.  I tried uninstalling and reinstalling Spyder and I get the same error.

Mitch

**Comment by ccordoba12** [comment]
Closing as there's nothing we can do about this one in our side, sorry.

**Comment by juliennyambal** [comment]
Hi everyone and hope that this would help.
I couldn't open spyder without sudo command. You should try 
`spyder --show-console`

My last line was:
OSError: [Errno 13] Permission denied: '/home/julien/.spyder2/.ropeproject/config.py' and some other files. Those files were only available to the root user. You should just remove the root privileges from each file that is blocking spyder from starting and you are ready to go. 

(I have used nautilus)

**Comment by Peyman87** [comment]
I ran this "pip install --upgrade spyder" in "Anaconda prompt" and then used "spyder --show-console" and it worked.

**Comment by Gabrielvon** [comment]
Hi.
I  came across same issue.  I tried `spyder --show-console`  and it show same error.  And I also tried all solutions mentioned up to my post, all of them don't work for my situations.

**Comment by Pechi77** [comment]
spyder show cons

> spyder show-console  gives

Spyder is already running. If you want to open a new
instance, please pass to it the --new-instance option

but still I am getting spyder crashed during  last session. pls help

**Comment by HomaiRS** [comment]
I have the exact same issue, please help....

1. I got the same error "spyder crashed during the last session".
2. I did "spyder --show-console", and it did not solve the error.
3. Then I did "pip install --upgrade spyder" in mac terminal.
4. Then again  "spyder --show-console".

BUT still I get the "spyder crashed during the last session" error :(((.... I appreciate any comment or feedback.

**Comment by ccordoba12** [comment]
Look for a file called `spyder_crash.log` and remove it.

**Comment by triggerhappy88** [comment]
help i also experience the same problem:

Traceback (most recent call last):
File "C:\Users\asus\Anaconda3\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\asus\Anaconda3\lib\site-packages\spyder\app\start.py", line 200, in main
from spyder.app import mainwindow
File "C:\Users\asus\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 167, in 
from spyder.utils.environ import WinUserEnvDialog
File "C:\Users\asus\Anaconda3\lib\site-packages\spyder\utils\environ.py", line 19, in 
from spyder.plugins.variableexplorer.widgets.collectionseditor import (
File "C:\Users\asus\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 57, in 
from spyder.plugins.variableexplorer.widgets.collectionsdelegate import (
File "C:\Users\asus\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionsdelegate.py", line 31, in 
from spyder.plugins.variableexplorer.widgets.objectexplorer.attribute_model \
File "C:\Users\asus\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\objectexplorer\__init__.py", line 19, in 
from .attribute_model import DEFAULT_ATTR_COLS, DEFAULT_ATTR_DETAILS
File "C:\Users\asus\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\objectexplorer\attribute_model.py", line 29, in 
import numpy as np
File "C:\Users\asus\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 140, in 
from . import _distributor_init
File "C:\Users\asus\AppData\Roaming\Python\Python37\site-packages\numpy\_distributor_init.py", line 26, in 
WinDLL(os.path.abspath(filename))
File "C:\Users\asus\Anaconda3\lib\ctypes\__init__.py", line 364, in __init__
self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by ccordoba12** [comment]
@triggerhappy88, please remove this directory

    C:\Users\asus\AppData\Roaming\Python

to fix your problem and **avoid** using pip to install packages that can be installed with conda in the future.

**Comment by triggerhappy88** [comment]
im not really sure what im doing, im not really good with these things, sorry. i just uninstalled anaconda which includes the spyder and jupyter notebook.  im trying to reinstall anaconda

**Comment by triggerhappy88** [comment]
![image](https://user-images.githubusercontent.com/60514321/73550876-59b8b000-4480-11ea-8b16-91abfb142625.png)

**Comment by triggerhappy88** [comment]
i cant see any AppData in C:\Users\asus\

**Comment by ccordoba12** [comment]
It's probably a hidden directory on Windows. So you need to remove it using the command prompt (cmd.exe).

@dalthviz, what's the command to remove directories on Windows?

**Comment by triggerhappy88** [comment]
![image](https://user-images.githubusercontent.com/60514321/73551983-5cb4a000-4482-11ea-9b59-35165a43f9aa.png)

**Comment by triggerhappy88** [comment]
i saw this one, do you think should i follow the above suggestion? I am not really sure where to type those "pip install ipython", "pip install spyder" and "spyder --reset", is it on ANaconda prompt or command prompt? :(

**Comment by dalthviz** [comment]
@ccordoba12 I think the command using [`rd`](https://www.computerhope.com/rmdirhlp.htm) for a recursive use the flag is `\S`

**Comment by ccordoba12** [comment]
> i saw this one, do you think should i follow the above suggestion?

No. Simply uninstall Anaconda, reinstall it and remove the directory I told you about with the command mentioned by @dalthviz in a command prompt, i.e.

    rd \S C:\Users\asus\AppData\Roaming\Python

**Comment by triggerhappy88** [comment]
i dont know how to insert that rd \S in the cmd, so i manually searched for that appdata roaming thing. it is working now, thank you very much for your help ,:D
i really appreciate it, i hope it will not crash again later because i have class

**Comment by triggerhappy88** [comment]
Hi im desperate for some help 😭

**Comment by triggerhappy88** [comment]
![CaseStudy](https://user-images.githubusercontent.com/60514321/73894064-452c4b80-48b6-11ea-87e9-6b8fb35ef62a.jpg)

**Comment by triggerhappy88** [comment]
![Annotation 2020-02-06 075814](https://user-images.githubusercontent.com/60514321/73894160-8c1a4100-48b6-11ea-86e4-08a138fa02d5.jpg)

**Comment by triggerhappy88** [comment]
Im left with only one item i cant figure out,  question 2.2.6.

**Comment by triggerhappy88** [comment]
Im hoping you can help me determine the code to determine the average number of repeat calls please

**Comment by dalthviz** [comment]
Hi @triggerhappy88, I think that is out of the scope of Spyder as an application and what we can help over here. Sorry to not be helpful at that level, but we are glad that you're using Spyder for your classes :)

**Comment by Downloadroot** [comment]
> I ran this "pip install --upgrade spyder" in "Anaconda prompt" and then used "spyder --show-console" and it worked.

This works for me, Thank you so much

**Comment by rajputking1106** [comment]
No need to upgrade spyder. your ipykernel and qtpy is not of required version.
So use this
"pip install --upgrade ipykernel"
"pip install --upgrade qtpy"

**Comment by utkarshsharma1** [comment]
I just upgraded spyder using this command & the issue resolved
`conda upgrade spyder`
 on anaconda console.

**Comment by Hilaren** [comment]
Also ran into same issue here with the traceback below : 

```
Traceback (most recent call last):
  File "/Users/renna/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "/Users/renna/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3559, in run_spyder
    main.setup()
  File "/Users/renna/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 960, in setup
    self.completions.start()
  File "/Users/renna/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/plugin.py", line 292, in start
    client_info['plugin'].start()
  File "/Users/renna/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/kite/plugin.py", line 144, in start
    self.client.start()
  File "/Users/renna/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/kite/client.py", line 62, in start
    self.sig_client_started.emit(self.languages)
TypeError: KiteClient.sig_client_started[list].emit(): argument 1 has unexpected type 'str'

```

I've tried quite a lot ways to solve the issue while failed : 
1. spyder --reset (doesn't work)
2. spyder --show-console (got the traceback)
3. uninstall and re-install spyder (doesn't work)

I've been working on it for a few days, can anyone help? Thank you so much!!

**Comment by fabioalvescarvalho** [comment]
> Hi.
> I came across same issue. I tried `spyder --show-console` and it show same error. And I also tried all solutions mentioned up to my post, all of them don't work for my situations.

It worked for me! Thanks

**Comment by fabioalvescarvalho** [comment]
> I ran this "pip install --upgrade spyder" in "Anaconda prompt" and then used "spyder --show-console" and it worked.

This worked for me too, thanks!!!
