### ISSUE TITLE
Ubuntu 16.10 and spyder beginner report

### ISSUE THREAD

**Issue by sebfoy** [spyder-ide/spyder#3912]
I can't run Spyder or Spyder3. 

**What steps will reproduce the problem?**

1. open Spyder or Spyder3 either on a graphical way or from a terminal
2. 
3. 

**What is the expected output? What do you see instead?**
`foy@foy-N150-N210-N220:~$ spyder
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 2331, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 2215, in run_spyder
    main.setup()
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 734, in setup
    message=_("Spyder Internal Console\n\n"
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/console.py", line 74, in __init__
    self.find_widget.set_editor(self.shell)
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/findreplace.py", line 260, in set_editor
    from spyderlib.qt.QtWebKit import QWebView
  File "/usr/lib/python2.7/dist-packages/spyderlib/qt/QtWebKit.py", line 10, in <module>
    from PyQt4.QtWebKit import *  # analysis:ignore
ImportError: No module named QtWebKit
foy@foy-N150-N210-N220:~$ spyder3
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spyderlib/spyder.py", line 2331, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python3/dist-packages/spyderlib/spyder.py", line 2215, in run_spyder
    main.setup()
  File "/usr/lib/python3/dist-packages/spyderlib/spyder.py", line 734, in setup
    message=_("Spyder Internal Console\n\n"
  File "/usr/lib/python3/dist-packages/spyderlib/plugins/console.py", line 74, in __init__
    self.find_widget.set_editor(self.shell)
  File "/usr/lib/python3/dist-packages/spyderlib/widgets/findreplace.py", line 260, in set_editor
    from spyderlib.qt.QtWebKit import QWebView
  File "/usr/lib/python3/dist-packages/spyderlib/qt/QtWebKit.py", line 10, in <module>
    from PyQt4.QtWebKit import *  # analysis:ignore
ImportError: No module named 'PyQt4.QtWebKit'`

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 2.3.8+dfsg1-1build1 either for spyder or spyder3 it seems on synaptics
* Python Version:2.7.12 or 3.5.2
* Operating system: lubuntu16.10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
I can't

**Comment by jitseniesen** [comment]
I'm afraid we can't do anything about this, because it is a problem with Ubuntu: https://bugs.launchpad.net/ubuntu/+source/spyder/+bug/1620300 . From that page, it looks like they have released a fix.

**Comment by sebfoy** [comment]
Thanks,
It didn't work for me...
I may go back to 16.04 it seems...
Incredible...

2017-01-04 19:51 GMT+11:00 Jitse Niesen <notifications@github.com>:

**Comment by ccordoba12** [comment]
@sebfoy, you have to *thank* Debian developers for this disruptive decision. Fortunately, this is going to be fixed in Ubuntu 17.04.

**Comment by sebfoy** [comment]
I can't write exactly my meaning for I'm far from fluent. There was no bad
thought.

2017-01-05 10:34 GMT+11:00 Carlos Cordoba <notifications@github.com>:
