### ISSUE TITLE
Error when editing markdown

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/spyder#3970]
## Description of your problem

**What steps will reproduce the problem?**

1. Open a File with .md extension (I'm not sure if happen with other extensions)
2. Press enter

**What is the expected output? What do you see instead?**
Some lines will throw an error

**Please provide any additional information below**
```
Traceback (most recent call last):
  File "/home/rlaverde/code/spyder/spyder/widgets/sourcecode/codeeditor.py", line 2695, in keyPressEvent
    cmt_or_str = self.in_comment_or_string()
  File "/home/rlaverde/code/spyder/spyder/widgets/sourcecode/codeeditor.py", line 2392, in in_comment_or_string
    current_color = self.__get_current_color()
  File "/home/rlaverde/code/spyder/spyder/widgets/sourcecode/codeeditor.py", line 2384, in __get_current_color
    color = current_format.foreground().color().name()
AttributeError: 'NoneType' object has no attribute 'foreground'
```

## Versions and main components

* Spyder Version: 3.x and master branch

**Comment by ccordoba12** [comment]
Probably happens with markdown because we don't have a color scheme associated with it.
