### ISSUE TITLE
spyder no longer starts after update

### ISSUE THREAD

**Issue by beew** [spyder-ide/spyder#3976]
After running pip install -ugrade spyder it no longer starts

Running python spyder --reset
it says
```
/usr/bin/python: can't find '__main__' module in 'spyder'
```
running the command 
```
spyder
```
results in 
```Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spyder/app/mainwindow.py", line 3001, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/local/lib/python2.7/dist-packages/spyder/app/mainwindow.py", line 2905, in run_spyder
    main.setup()
  File "/usr/local/lib/python2.7/dist-packages/spyder/app/mainwindow.py", line 869, in setup
    self.projects = Projects(self)
  File "/usr/local/lib/python2.7/dist-packages/spyder/plugins/projects.py", line 71, in __init__
    self.setup_project(self.get_active_project_path())
  File "/usr/local/lib/python2.7/dist-packages/spyder/widgets/projects/explorer.py", line 226, in setup_project
    show_all=self.show_all)
  File "/usr/local/lib/python2.7/dist-packages/spyder/widgets/explorer.py", line 195, in setup
    self.common_actions = self.setup_common_actions()
  File "/usr/local/lib/python2.7/dist-packages/spyder/widgets/projects/explorer.py", line 55, in setup_common_actions
    self.toggle_hscrollbar(self.show_hscrollbar)
  File "/usr/local/lib/python2.7/dist-packages/spyder/widgets/projects/explorer.py", line 70, in toggle_hscrollbar
    self.header().setResizeMode(QHeaderView.ResizeToContents)
  File "/usr/local/lib/python2.7/dist-packages/qtpy/_patch/qheaderview.py", line 83, in setResizeMode
    raise Exception('setResizeMode is only available in Qt4. Use '
Exception: setResizeMode is only available in Qt4. Use setSectionResizeMode instead.
```

It was working before. spyder version 3.0.2. OS is Ubuntu 16.04 64 bits.

P.S.Cloning the git repository and running python bootstrap.py does work, for both master and 3.1.0dev

**Comment by ccordoba12** [comment]
Thanks for reporting. This will fixed in Spyder 3.1 (to be released tomorrow :-)
