### ISSUE TITLE
Spyder ipython console crashes on highlighting "import" or "from"

### ISSUE THREAD

**Issue by BeateBier** [spyder-ide/spyder#3977]
## Description of your problem

Hi.

I made some updates yesterday (see below in the additional information area) and suddenly spyder "crashes" on entering `import` in the ipython console of spyder.
To be precise: The moment you are entering the "t" of "import", the "crash" occurs, which is also the moment the syntax highlighting of `import`starts.

Then I'm thrown back to the internal console, which shows some error code (see below in "What do you see instead".)

But the ipython console is still working.
I can enter additional things, but if the next character after the "t" of import is a blank, I get thrown to the internal console after every character I enter. When I finish the module name in this way, I can press Enter and the module is imported. After that the console is working as expected.

If the next character after "import" is a letter, a number, ... (so that the word is no recognized command anymore and is therefor not highlighted anymore; e.g. `importe`) you can write normally.

This also applies to entering `from`: Once I enter the last letter "m" (the moment the highlighting starts), I have the same behaviour.

When entering `as`, I do not see this behaviour, although "as" is highlighted in the same way.

Also, other, differently highlighted commands and keywords (`sum`, `max`, `min`) do not seem to show this behaviour.

If you mix `from` and `import`, as in `from module import function as func`, you get a mixed result:
I entered `fro module impor function as func` ("from" and "import" not yet highlighted, "as" highlighted) and no error. If I complete one of the two commands ("from" OR "import") the error occurs. If you then complete the second command ("import" or "from") this second command is highlighted, but no error occurs.

Everything else seems to work fine, I can run my programs for example.

I already de- and reinstalled spyder. I also deleted the .spyder-directory in my home-directory.

**What steps will reproduce the problem?**

1. Entering `import` or `from` in any ipython console in spyder.
It appears after a restart of spyder or in between work sessions.
It appears also in newly started ipython consoles.
It does NOT appear in regular ipython sessions (in bash).

**What is the expected output? What do you see instead?**

Expected:
To be able to enter the commands `import` and `from` with highlighting and without being thrown to the internal console.

What I see instead:
After entering the last letter of `from` or `import` (the moment the highlighting starts), I get thrown to the internal console and see an error message:

> Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/IPython/qt/console/frontend_widget.py", line 60, in highlightBlock
    super(FrontendHighlighter, self).highlightBlock(string)
  File "/usr/lib/python2.7/site-packages/IPython/qt/console/pygments_highlighter.py", line 115, in highlightBlock
    for token, text in self._lexer.get_tokens(string):
  File "/usr/lib/python2.7/site-packages/pygments/lexer.py", line 191, in streamer
    for _, t, v in self.get_tokens_unprocessed(text):
  File "/usr/lib/python2.7/site-packages/IPython/qt/console/pygments_highlighter.py", line 30, in get_tokens_unprocessed
    for item in action(self, m):
TypeError: 'NoneType' object is not callable

After that, the ipython console can be used again (see above in the description part)

**Please provide any additional information below**
Updates I made, before the problem occured:

> 2017-01-16 19:02:02|install|gdk-pixbuf-query-loaders|2.32.3-13.1|x86_64||repo-update|87802c6fa49568783e3658d9ac43048ccaaf8b2179ba53fcd0ff5c8b480abea6|
2017-01-16 19:02:03|install|gdk-pixbuf-query-loaders-32bit|2.32.3-13.1|x86_64||repo-update|ed6dafde1b800f7d4637e34af4aedc0fee276a8bac281aa6270db0aa28a9fe6f|
2017-01-16 19:02:04|install|libgdk_pixbuf-2_0-0|2.32.3-13.1|x86_64||repo-update|793976d188786b0d7c49ebbd510ac8eee0a14b6dce1c214ef2db4887138cc5f4|
2017-01-16 19:02:05|install|libgdk_pixbuf-2_0-0-32bit|2.32.3-13.1|x86_64||repo-update|a8e7064c12994784af302cf0bd4fce5f5dc36825d4da3e36a8bbc1efb680a0db|
2017-01-16 19:02:05|install|typelib-1_0-GdkPixbuf-2_0|2.32.3-13.1|x86_64||repo-update|31194fd23f984d9f489c832f484ee65184bd512e5cb1c492f3439b52a752dbaf|
2017-01-16 19:02:06|install|gdk-pixbuf-lang|2.32.3-13.1|noarch||repo-update|a46ec5a5e9902e36ad1e1a3bd41033c46e7752239974b260e2a6f8172081d1b8|
2017-01-16 19:02:07|install|gdk-pixbuf-devel|2.32.3-13.1|x86_64||repo-update|fd8f4a1d1aa230d546fb443fdb86bed33ac47f8324d059c98812ce32cdd035d4|
2017-01-16 19:02:42|install|gstreamer-plugins-base|1.4.3-3.1|x86_64||repo-update|1aa991a1f64746e4608b90f725431aceef1da0ae0f88a77e5387b955bd3ad181|
2017-01-16 19:02:43|install|libMagickCore-6_Q16-2|6.8.9.8-48.1|x86_64||repo-update|a6a1ad86816d13ac6cc150cc7e7ee3127124636ff9b95d002b269a99f7d82a1b|
2017-01-16 19:02:43|install|libgstbadbase-1_0-0|1.4.3-6.1|x86_64||repo-update|276b38ebe268d6be8a1a631195ba9a6176acd30d6844f14acede5d51f5a37ecd|
2017-01-16 19:02:43|install|libgstcodecparsers-1_0-0|1.4.3-6.1|x86_64||repo-update|6d45ee4f354dd4241ee3d7e20a9bca98137f71f86a591f92fb2c0b5f914b582e|
2017-01-16 19:02:43|install|libgstinterfaces-0_10-0|0.10.36-11.3.1|x86_64||repo-update|4275ef4b1748c72d19b24ef1e3d09f03acedc5f0e9bd3f94a21dd2ea9f68cc2f|
2017-01-16 19:02:44|install|libgstmpegts-1_0-0|1.4.3-6.1|x86_64||repo-update|dd6c42b094d08d2190775174ba46499188aceb7a0022b8e872ac23fc57ea86cb|
2017-01-16 19:02:44|install|libgstphotography-1_0-0|1.4.3-6.1|x86_64||repo-update|24a1c8835073aa65bf4300e40708d93e320e2dfe7a543809d4cbd5b4b4652450|
2017-01-16 19:02:44|install|libgstvideo-1_0-0|1.4.3-3.1|x86_64||repo-update|e6d917257d31fa1f76f9ee522559dbc9af1b115a7d9bd0b16f79ca5243cef844|
2017-01-16 19:02:44|install|libMagickWand-6_Q16-2|6.8.9.8-48.1|x86_64||repo-update|7af4191f286aa895f42b163a04929c4d8c47fb76199c63d6504f4ce3c131bf71|
2017-01-16 19:02:45|install|gstreamer-0_10-plugins-base|0.10.36-11.3.1|x86_64||repo-update|43bb4810258bee55acef15279d1eb6684827c9f640dae909a2270fde77394f5a|
2017-01-16 19:02:45|install|libgsttag-1_0-0|1.4.3-3.1|x86_64||repo-update|4c27d6c818bb47b1f3e8def5c3f18ada05c22f12fdcfba348b55ec2603a905f3|
2017-01-16 19:02:45|install|libgstgl-1_0-0|1.4.3-6.1|x86_64||repo-update|b53acd2a7cb460864f127d52075cd7badb6c67153f0a886e429e60d4c8d6a410|
2017-01-16 19:02:45|install|libgstbadvideo-1_0-0|1.4.3-6.1|x86_64||repo-update|4b494028877efac2634609eb7496dcb21ea60dc1e9151475121ae25aee2fef20|
2017-01-16 19:02:45|install|ImageMagick|6.8.9.8-48.1|x86_64||repo-update|c6eec76aa3804080668a34e8bbb980815c441e40b7bfddaf5870a7b0ec61d7e8|
2017-01-16 19:02:46|install|libgstapp-0_10-0|0.10.36-11.3.1|x86_64||repo-update|95f2c1576a453405d62ed48cbaece75651065111bee723f3a8f5374f1a005394|
2017-01-16 19:02:46|install|libgstaudio-1_0-0|1.4.3-3.1|x86_64||repo-update|609ceb55b0bcfefa134cc39305d8106ac74c88e6689a71ebc8b9a19a69c7f4aa|
2017-01-16 19:02:46|install|libMagick++-6_Q16-5|6.8.9.8-48.1|x86_64||repo-update|ad97dd51616b1a08de61d5bbf906979a8411548beb68362e35af2e602485d0e7|
2017-01-16 19:02:47|install|gstreamer-0_10-plugins-good|0.10.31-13.3.1|x86_64||repo-update|8bba2a104ee3c24598e9a732ca7d2fd878ed4c223869ceb5fb0efe82296cc8f2|
2017-01-16 19:02:47|install|gstreamer-0_10-plugin-gnomevfs|0.10.36-11.3.1|x86_64||repo-update|4ec3a31f37507e7b3da5f5d2b7604f5e0acdfe2f50d2d187ad16211fc32458b4|
2017-01-16 19:02:47|install|libgstpbutils-1_0-0|1.4.3-3.1|x86_64||repo-update|35061816e86eb2c7e21ddd1c18f356408ff63eaaf9b40e14725b1fffa3042817|
2017-01-16 19:02:47|install|gstreamer-0_10-plugin-esd|0.10.31-13.3.1|x86_64||repo-update|d63b25861fd755139620a4f6f3713f100cf13747730b6d71b03f824ecf6211a9|
2017-01-16 19:02:47|install|libgstapp-1_0-0|1.4.3-3.1|x86_64||repo-update|a142e90e42628123a6f8aa58fef1bfa5c79f10d7ee7bf49cbc1ce2c80d380dd5|
2017-01-16 19:02:47|install|libgstriff-1_0-0|1.4.3-3.1|x86_64||repo-update|81e00c18220d36df5d828c4817be24ca9afa166c50449861593df76e4f6586c5|
2017-01-16 19:02:48|install|libgstbasecamerabinsrc-1_0-0|1.4.3-6.1|x86_64||repo-update|27cff1ccf9e0f5a1fa841f274f180ae3dd32b1c3555ee1390de4b980db38077e|
2017-01-16 19:02:48|install|libgstsdp-1_0-0|1.4.3-3.1|x86_64||repo-update|9074bb7d56a1271b86647b3dd07888d1a456e35dbdb6833217f8360229d9d017|
2017-01-16 19:02:48|install|libgstrtsp-1_0-0|1.4.3-3.1|x86_64||repo-update|f7b150b0ba563d939f682efafaa896535850cb1625ac67974cf2473fcad98353|
2017-01-16 19:02:48|install|libgstrtp-1_0-0|1.4.3-3.1|x86_64||repo-update|487e2aa492feeb50b1ecffc047c98d15456883d99f32064062711b7ed47493c7|
2017-01-16 19:02:48|install|libgstfft-1_0-0|1.4.3-3.1|x86_64||repo-update|86b2756fc97191960a0a4c77a76a1cf67948fb4e47c9f8d012f86fade73e9b02|
2017-01-16 19:02:48|install|libgstallocators-1_0-0|1.4.3-3.1|x86_64||repo-update|c5b1956c97995a0956eb0150291d099953632ddcfd7d8fcc5051214802839b6c|
2017-01-16 19:02:49|install|gstreamer-plugins-good|1.4.3-3.1|x86_64||repo-update|945c056c9f3e2c5a60859f615ed07a9a009f8ac2376c53cfcee857cbe7fd7bf0|
2017-01-16 20:10:26|remove |spyder-doc|2.3.1-2.1|noarch|user@computer|
2017-01-16 20:10:27|remove |spyder-lang|2.3.1-2.1|noarch|user@computer|
2017-01-16 20:10:28|remove |spyder|2.3.1-2.1|noarch|user@computer|
2017-01-16 20:10:37|remove |python-spyderlib|2.3.1-2.1|noarch|user@computer|
2017-01-16 20:11:00|install|python-spyderlib|2.3.1-2.1|noarch|user@computer|download.opensuse.org-oss|149b1e8e917676455a20d6cc22e4361f25a93b0d|
2017-01-16 20:11:00|install|spyder|2.3.1-2.1|noarch|user@computer|download.opensuse.org-oss|9fd72245bd7ffc4070aaffaa8bc357495bb01be8|
2017-01-16 20:11:00|install|spyder-lang|2.3.1-2.1|noarch|user@computer|download.opensuse.org-oss|f5fbf29ab1ba022c49f3c5738fa306d8cd2b6bf9|
2017-01-16 20:11:00|install|spyder-doc|2.3.1-2.1|noarch|user@computer|download.opensuse.org-oss|168dcc1d0e0291afe67328383acfa8ea023f6676|

## Versions and main components

* Spyder Version: 2.3.1 (Distribution package manager version 2.3.1-2.1)
* Python Version: 2.7.12
* Operating system: OpenSuse 13.2
* Output of Help -> About Spyder: Python 2.7.12 64bits, Qt 4.8.6, PyQt4 (API v2) 4.11.1 on Linux

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=0.13  :  2.2.0 (OK)
matplotlib >=1.0:  1.4.0 (OK)
pandas >=0.13.1 :  None (NOK)
pep8 >=0.6      :  1.5.7 (OK)
psutil >=0.3    :  2.1.2 (OK)
pyflakes >=0.5.0:  0.8.1 (OK)
pygments >=1.6  :  2.1.3 (OK)
pylint >=0.25   :  None (NOK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
sympy >=0.7.0   :  None (NOK)

**Comment by ccordoba12** [comment]
I'm sorry to say that Spyder 2.3.1 is almost two years old and not supported by us anymore.

Please update to Spyder 3.0.2 (and preferably PyQt5 too) and open a new bug report if you see the same error in that version.

Thanks!
