### ISSUE TITLE
Spyder 3.1.0 does not work with Python 3.6 due to PySide incompatibility

### ISSUE THREAD

**Issue by LJWilliams** [spyder-ide/spyder#4009]
## Description of your problem

**What steps will reproduce the problem?**
On Python 3.6
1. pip install spyder
2. spyder
3. pip install PySide

**What is the expected output? What do you see instead?**
Call to spyder:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtpy/__init__.py", line 119, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spyder/requirements.py", line 39, in check_qt
    import qtpy
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtpy/__init__.py", line 125, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

**Please provide any additional information below**
Call to Pyside:
Collecting PySide
  Downloading PySide-1.2.4.tar.gz (9.3MB)
    100% |████████████████████████████████| 9.3MB 131kB/s 
    Complete output from command python setup.py egg_info:
    only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/g6/d2_31_gs2ql0wvkkz3g4yd440000gn/T/pip-build-2cnk3otu/PySide/

## Versions and main components

* Spyder Version: 3.1.0
* Python Version: 3.6
* Operating system: OSX 10.9.5

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Spyder 3 doesn't work with PySide, please install PyQt5 instead with

    pip install pyqt5
