### ISSUE TITLE
Spyder Crashes after Pip upgrade

### ISSUE THREAD

**Issue by joedrisc** [spyder-ide/spyder#4015]
## Description of your problem

While doing pip upgrade on several packages my terminal crashed. Now I can no longer open spyder and I get the error message 

2017-01-20 11:06:21.914 Python[1547:20542] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2979, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/local/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2883, in run_spyder
    main.setup()
  File "/usr/local/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 1124, in setup
    self.setup_layout(default=False)
  File "/usr/local/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 1395, in setup_layout
    self.setup_default_layouts('default', settings)
  File "/usr/local/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 1576, in setup_default_layouts
    action.setChecked(widget.dockwidget.isVisible())
AttributeError: 'NoneType' object has no attribute 'isVisible'
Traceback (most recent call last):
  File "/usr/local/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/spyder/app/start.py", line 104, in main
    mainwindow.main()
  File "/usr/local/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2991, in main
    traceback.print_exc(file=open('spyder_crash.log', 'w'))
IOError: [Errno 13] Permission denied: 'spyder_crash.log'

If i run python spyder --reset I get 

/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'spyder': [Errno 2] No such file or directory

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3
* Python Version: 2.7
* Operating system: Mac OS

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by joedrisc** [comment]
I was able to reset spyder and still no luck. 

I think the issue is with the error 

AttributeError: 'NoneType' object has no attribute 'isVisible'

Thank for your help

**Comment by ccordoba12** [comment]
Do you have Spyder third-party plugins (like memory-profiler or line-profiler) installed too?

**Comment by joedrisc** [comment]
No 3rd party plug-ins.

**Comment by ccordoba12** [comment]
We're sorry but we have no idea how else to help you.

**Comment by andfoy** [comment]
@ccordoba12 @joedrisc I could reproduce this one as of Spyder 4, somehow, by uninstalling Spyder-Vim, the problem was gone

**Comment by ccordoba12** [comment]
@andfoy, please open an issue about it in `spyder-vim`, mentioning this one as well.
