### ISSUE TITLE
Object inspector crashes with some mpmath functions (no 'self' in class constructors)

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#402]
_From [pg...@laposte.net](https://code.google.com/u/111357432601046728586/) on 2010-10-06T03:28:27Z_

What steps will reproduce the problem?

 1. from mpmath import *
2. findroot( 3. What is the expected output? What do you see instead? When I type the ( after findroot, I get an error message :

\>>> findrootTraceback (most recent call last):
  File "C:\Python26\lib\site-packages\spyderlib\widgets\interactiveshell.py", line 367, in keyPressEvent
    self.postprocess_keyevent(event)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\shell.py", line 794, in postprocess_keyevent
    ShellBaseWidget.postprocess_keyevent(self, event)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\shell.py", line 444, in postprocess_keyevent
    self._key_parenleft(text)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\shell.py", line 880, in _key_parenleft
    self.show_docstring(self.get_last_obj(), call=True)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\shell.py", line 1032, in show_docstring
    arglist = self.get_arglist(text)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\interactiveshell.py", line 538, in get_arglist
    return getargtxt(obj)
  File "C:\Python26\lib\site-packages\spyderlib\utils\dochelpers.py", line 120, in getargtxt
    textlist.remove('self'+sep)
ValueError: list.remove(x): x not in list What version of the product are you using? On what operating system? I use Python 2.6.6 and I tried with Spyder 2 beta 4 and with Spyder 1.1.7 

Please provide any additional information below

. Sometimes when I type a function and then a ( I get this message.

Can you help me. Certainly I missed something.

Pascal Grandeau

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=402_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-06T13:10:02Z_

**Summary:** Object inspector crashes with some mpmath functions (no 'self' in class constructors)  
  **Status:** Accepted

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-06T13:10:49Z_

This issue was closed by revision ab7d157e65 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-24T07:36:08Z_

This issue was closed by revision ab7d157e65a3 .
