### ISSUE TITLE
Error when running cell for the first time in the Editor

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#4025]
I'm getting this error when I try to run a cell for the first time

```python-traceback
Traceback (most recent call last):
  File "/home/carlos/Projects/spyder/github-repo/spyder/app/mainwindow.py", line 1916, in plugin_focus_changed
    self.update_edit_menu()
  File "/home/carlos/Projects/spyder/github-repo/spyder/app/mainwindow.py", line 1965, in update_edit_menu
    widget, textedit_properties = self.get_focus_widget_properties()
  File "/home/carlos/Projects/spyder/github-repo/spyder/app/mainwindow.py", line 1953, in get_focus_widget_properties
    widget = self.previous_focused_widget
AttributeError: 'MainWindow' object has no attribute 'previous_focused_widget'
```

@rlaverde, this one is for you because this bug was introduced on PR #4022.

**Comment by ccordoba12** [comment]
After the first time this doesn't happen anymore so it's not that bad.
