### ISSUE TITLE
fails to start after --reset

### ISSUE THREAD

**Issue by Annie123123** [spyder-ide/spyder#4103]
## Description of your problem

**What steps will reproduce the problem?**
It show "Connecting kernel" in IPython console.
And then,
I used the --reset command and can see some files are being deleted. I also tried deleting the .Spyder folder.

**What is the expected output? What do you see instead?**
After a reset, Spyder tries to launch as normal and I can see the splash scree, which disappears after a short while, but Spyder never launches. I then kill the python.exe processed (3 in total), and when launching Spyder again I get the "Spyder crashed during last session"-screen.

and run in a terminal:
spyder --show-console

(C:\Users\Administrator\Anaconda2) C:\Users\Administrator>spyder --show-console
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 2998, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 2902, in run_spyder
    main.setup()
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 1153, in setup
    self.setup_layout(default=False)
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 1414, in setup_layout
    self.setup_default_layouts('default', settings)
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 1593, in setup_default_layouts
    widget.toggle_view(True)
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 677, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 886, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 903, in connect_client_to_kernel
    km, kc = self.create_kernel_manager_and_kernel_client(connection_file)
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1276, in create_kernel_manager_and_kernel_client
    kernel_manager._kernel_spec = self.create_kernel_spec()
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1256, in create_kernel_spec
    uv = to_text_string(v)
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\spyder\py3compat.py", line 135, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbd in position 37: ordinal not in range(128)

**Please provide any additional information below**
I have also tried to uninstall and install spyder under the Python 2.7 environment, but no change.

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 2.7
* Operating system: win 10

**Comment by ccordoba12** [comment]
Please run

    conda update spyder

and try again. The error you report should be fixed in the latest version of Spyder.

**Comment by ccordoba12** [comment]
Closing for now. Please let us know (in this issue) if that fixed the problem for you.
