### ISSUE TITLE
failed to launch spyder with error message ValueError, 'unknown locale: %s' % localename

### ISSUE THREAD

**Issue by Po-Hsuan-Huang** [spyder-ide/spyder#4131]
I just installed Spyder3 under miniconda2 and when I tried to launch it, it gave the error:
```
Traceback (most recent call last):
  File "/home/po-hsuan/miniconda2/envs/autodrive/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2989, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/po-hsuan/miniconda2/envs/autodrive/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2893, in run_spyder
    main.setup()
  File "/home/po-hsuan/miniconda2/envs/autodrive/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 859, in setup
    from spyder.plugins.externalconsole import ExternalConsole
  File "/home/po-hsuan/miniconda2/envs/autodrive/lib/python2.7/site-packages/spyder/plugins/externalconsole.py", line 39, in <module>
    from spyder.widgets.externalshell.pythonshell import ExternalPythonShell
  File "/home/po-hsuan/miniconda2/envs/autodrive/lib/python2.7/site-packages/spyder/widgets/externalshell/pythonshell.py", line 34, in <module>
    from spyder.widgets.variableexplorer.namespacebrowser import NamespaceBrowser
  File "/home/po-hsuan/miniconda2/envs/autodrive/lib/python2.7/site-packages/spyder/widgets/variableexplorer/namespacebrowser.py", line 26, in <module>
    import ipykernel.pickleutil
  File "/home/po-hsuan/miniconda2/envs/autodrive/lib/python2.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/home/po-hsuan/miniconda2/envs/autodrive/lib/python2.7/site-packages/ipykernel/connect.py", line 18, in <module>
    import jupyter_client
  File "/home/po-hsuan/miniconda2/envs/autodrive/lib/python2.7/site-packages/jupyter_client/__init__.py", line 7, in <module>
    from .manager import KernelManager, run_kernel
  File "/home/po-hsuan/miniconda2/envs/autodrive/lib/python2.7/site-packages/jupyter_client/manager.py", line 32, in <module>
    from .session import Session
  File "/home/po-hsuan/miniconda2/envs/autodrive/lib/python2.7/site-packages/jupyter_client/session.py", line 53, in <module>
    from jupyter_client.jsonutil import extract_dates, squash_dates, date_default
  File "/home/po-hsuan/miniconda2/envs/autodrive/lib/python2.7/site-packages/jupyter_client/jsonutil.py", line 24, in <module>
    datetime.strptime("1", "%d")
  File "/home/po-hsuan/miniconda2/envs/autodrive/lib/python2.7/_strptime.py", line 274, in <module>
    _TimeRE_cache = TimeRE()
  File "/home/po-hsuan/miniconda2/envs/autodrive/lib/python2.7/_strptime.py", line 192, in __init__
    self.locale_time = LocaleTime()
  File "/home/po-hsuan/miniconda2/envs/autodrive/lib/python2.7/_strptime.py", line 70, in __init__
    self.lang = _getlang()
  File "/home/po-hsuan/miniconda2/envs/autodrive/lib/python2.7/_strptime.py", line 29, in _getlang
    return locale.getlocale(locale.LC_TIME)
  File "/home/po-hsuan/miniconda2/envs/autodrive/lib/python2.7/locale.py", line 564, in getlocale
    return _parse_localename(localename)
  File "/home/po-hsuan/miniconda2/envs/autodrive/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: lzh_TW

```
This issue is similar to what was found on [MacOS](https://coderwall.com/p/-k_93g/mac-os-x-valueerror-unknown-locale-utf-8-in-python)

But it does not seem to happen before on Linux, so I suspect I did something wrong went installing.

Here is the $locale setting on my machine :
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=lzh_TW
LC_TIME=lzh_TW
LC_COLLATE=en_US.UTF-8
LC_MONETARY=lzh_TW
LC_MESSAGES=en_US.UTF-8
LC_PAPER=lzh_TW
LC_NAME=lzh_TW
LC_ADDRESS=lzh_TW
LC_TELEPHONE=lzh_TW
LC_MEASUREMENT=lzh_TW
LC_IDENTIFICATION=lzh_TW
LC_ALL=

I tried add  the following to my .bashrc file in my home dir, but it did not work.

`export LANG= lzh_TW

export LANGUAGE=lzh_TW

export LC_CTYPE=lzh_TW

export LC_COLLATE=lzh_TW

export LC_MESSAGES=lzh_TW`

## Versions and main components

* Spyder Version: 3.1.12
* Python Version:2.7.13
* Qt Version:5.6.2
* PyQt Version:5.6.0
* Operating system: Ubuntu 10.04 LTS

**Comment by jitseniesen** [comment]
Does it work if you change `lzh_TW` to `zh_TW`?

**Comment by Po-Hsuan-Huang** [comment]
Hi, Jitseniesen,
```
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
```

**Comment by Po-Hsuan-Huang** [comment]
Hi, Jitseniesne,
The problelm is solved. I installed the zh_TW.utf-8
with either ```sudo locale-gen zh_TW.UTF-8``` , or
```sudo dpkg-reconfigure locales ``` if the former does not work.

Thank you very much !!

po-hsuan@pohsuan-Aspire-VN7-791:$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="zh_TW.utf8"
LC_NUMERIC="zh_TW.utf8"
LC_TIME="zh_TW.utf8"
LC_COLLATE="zh_TW.utf8"
LC_MONETARY="zh_TW.utf8"
LC_MESSAGES="zh_TW.utf8"
LC_PAPER="zh_TW.utf8"
LC_NAME="zh_TW.utf8"
LC_ADDRESS="zh_TW.utf8"
LC_TELEPHONE="zh_TW.utf8"
LC_MEASUREMENT="zh_TW.utf8"
LC_IDENTIFICATION="zh_TW.utf8"
LC_ALL=zh_TW.utf8
po-hsuan@pohsuan-Aspire-VN7-791:~$
