### ISSUE TITLE
Spyder Wont Work

### ISSUE THREAD

**Issue by shilowilson31** [spyder-ide/spyder#4143]
## Description

This occurs whenever I open spyder 

**What steps will reproduce the problem?**
Error in sitecustomize; set PYTHONVERBOSE for traceback:
AttributeError: module 'datetime' has no attribute 'datetime'
Traceback (most recent call last):
File "C:\Users\wilso\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 227, in 
main()
File "C:\Users\wilso\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 200, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\wilso\Anaconda3\lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\wilso\Anaconda3\lib\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "C:\Users\wilso\Anaconda3\lib\site‑packages\IPython\__init__.py", line 49, in 
from .terminal.embed import embed
File "C:\Users\wilso\Anaconda3\lib\site‑packages\IPython\terminal\embed.py", line 15, in 
from IPython.core.magic import Magics, magics_class, line_magic
File "C:\Users\wilso\Anaconda3\lib\site‑packages\IPython\core\magic.py", line 22, in 
from IPython.core import oinspect
File "C:\Users\wilso\Anaconda3\lib\site‑packages\IPython\core\oinspect.py", line 33, in 
from IPython.lib.pretty import pretty
File "C:\Users\wilso\Anaconda3\lib\site‑packages\IPython\lib\pretty.py", line 85, in 
import datetime
File "C:\Users\wilso\Prog
1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.2 
* Python Version: 3.6.0
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by jitseniesen** [comment]
The error message got truncated so I am not sure what is going on, but my guess would be that you have a `datetime` module somewhere that shadows the `datetime` module in the standard Python library. The Python command `import datetime; print(datetime)` shows which `datetime` module gets imported.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
