### ISSUE TITLE
Keyboard shortcut dialog unuseable / crash

### ISSUE THREAD

**Issue by x49** [spyder-ide/spyder#4146]
## Description of your problem

When opening the keyboard shortcut dialog, a backtrace is printed and the dialog is not functional.

**What steps will reproduce the problem?**

1. Open the keyboard shortcuts page in the settings  (Tools -> Preferences -> Keyboard Shortcuts).
2. Observe the output in the internal console.
3. After some time, spyder crashes.

**What is the expected output? What do you see instead?**

Expected behaviour would be for the keyboard dialog to function properly, displaying the shortcut and the assigned action.

Actual behaviour is a dialog with not displayed or mostly empty fields, not showing either the shortcut or the assigned action. See screenshot:
![spyder_keyboardshortcuts](https://cloud.githubusercontent.com/assets/5230949/22966634/5878e168-f363-11e6-9828-5107f5e87fc2.png)

**Please provide any additional information below**
Reinstalled spyder and cleaned config directory.

Output from Internal console:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 123, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 123, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 123, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 123, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 123, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 123, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 123, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 123, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 123, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 123, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 123, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 123, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 123, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 123, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 123, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 123, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 123, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 123, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 123, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 123, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
```

## Versions and main components

* Spyder Version: spyder3 git master commit: 49c321d3
* Python Version: 3.6.0
* Qt Version: 5.8.0
* PyQt Version: 5.7.1
* Operating system: Linux 4.9.8-1-ARCH #1 SMP PREEMPT Mon Feb 6 12:59:40 CET 2017 x86_64 GNU/Linux

## Dependencies
jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.0.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
psutil >=0.3     :  5.1.3 (OK)
pycodestyle >=0.6:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  2.0.0 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.2 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Maybe it's a problem with Qt 5.8, which we haven't tested yet.

**Comment by goanpeca** [comment]
>Maybe it's a problem with Qt 5.8

Very likely

**Comment by banan314** [comment]
The problem disappeared for me after update from v3.1.4 to v3.2.0. I think the issue can be closed now.

**Comment by ccordoba12** [comment]
Thanks for letting us know about it!
