### ISSUE TITLE
Spyder won't work

### ISSUE THREAD

**Issue by SaintNazaire** [spyder-ide/spyder#4149]
## Description of your problem

**What steps will reproduce the problem?**

1. installed OSGeo64W QGIS as usual
2. went to OSGeo64W directory, launched OSGeo64W.bat as usual
3. installed dependencies from wheel windows binaries as usual including:
- lxml incl. libxml2, libxlst 1.129
- scandir
- scipy
- Visual Studio C++ 9.0 for Python 2.7
4. C:\OSGEO4 1>pip install spyder
5. spyder installs all dependencies just fine
6. C:\OSGEO4 1>spyder
    python: can't open file 'c:\OSGEO4~1\apps\Python27\Scripts\spyder': [Errno 2] No such file or directory
8. C:\OSGEO4 1>python -c "from spyderlib.spyder import main; main()" --reset
   Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\OSGEO4 1\apps\Python27\lib\site-packages\spyderlib\spyder.py", line 88, in <module>
    from spyderlib.qt.QtGui import (QApplication, QMainWindow, QSplashScreen,
ImportError: No module named QtGui
9. C:\OSGEO4 1>pip install qtgui
   Requirement already up-to-date: qtpy in c:\osgeo4 1\apps\python27\lib\site-packages
10. C:\OSGEO4 1>pip install qtawesome
   Requirement already satisfied: qtawesome in c:\osgeo4 1\apps\python27\lib\site-packages
   Requirement already satisfied: qtpy in c:\osgeo4 1\apps\python27\lib\site-packages (from qtawesome)
   Requirement already satisfied: six in c:\osgeo4 1\apps\python27\lib\site-packages (from qtawesome)

## Softwares versions

* Spyder Version: 3.1.2
* Python Version: 2.7.5
* Qt Version: 5.3.0-5.7.0
* PyQt Version: pyQt4 4.11.4, pyQt5.7.1
* Operating system: Windows 10

**Comment by SaintNazaire** [comment]
And the reason for my entire day lost chasing ghost issues is Bitdefender Internet Security 2016...
zxwzrtsztpqqqzstz!!!
