### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by oztalha** [spyder-ide/spyder#4207]
## Description

**What steps will reproduce the problem?**

1. pip install spyder
2. pip install pyqt5
3. spyder3

**What is the expected output? What do you see instead?**
I expected ipython console prompter to show up,
I got this instead:

> An error ocurred while starting the kernel
Traceback (most recent call last):
File "/usr/local/lib/python3.5/site‑packages/spyder/utils/ipython/start_kernel.py", line 227, in 
main()
File "/usr/local/lib/python3.5/site‑packages/spyder/utils/ipython/start_kernel.py", line 200, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.5/site‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/usr/local/lib/python3.5/site‑packages/ipykernel/connect.py", line 18, in 
import jupyter_client
File "/usr/local/lib/python3.5/site‑packages/jupyter_client/__init__.py", line 7, in 
from .manager import KernelManager, run_kernel
File "/usr/local/lib/python3.5/site‑packages/jupyter_client/manager.py", line 32, in 
from .session import Session
File "/usr/local/lib/python3.5/site‑packages/jupyter_client/session.py", line 56, in 
from zmq.eventloop.ioloop import IOLoop
File "/usr/local/lib/python3.5/site‑packages/zmq/eventloop/__init__.py", line 3, in 
from zmq.eventloop.ioloop import IOLoop
File "/usr/local/lib/python3.5/site‑packages/zmq/eventloop/ioloop.py", line 35, in 
from tornado.ioloop import PollIOLoop, PeriodicCallback
File "/usr/local/lib/python3.5/site‑packages/tornado/ioloop.py", line 46, in 
from tornado.concurrent import TracebackFuture, is_future
File "/usr/local/lib/python3.5/site‑packages/tornado/concurrent.py", line 37, in 
from concurrent import futures
File "/usr/local/lib/python3.5/site‑packages/concurrent/futures/__init__.py", line 8, in 
from concurrent.futures._base import (FIRST_COMPLETED,
File "/usr/local/lib/python3.5/site‑packages/concurrent/futures/_base.py", line 357
raise type(self._exception), self._exception, self._traceback
^
SyntaxError: invalid syntax

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.3 
* Python Version: 3.5.1
* Qt Versions: 5.8.0, PyQt5 5.8 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.12.0 (OK)
sphinx >=0.6.6   :  1.5.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi =0.9.0      :  0.9.0 (OK)
psutil >=0.3     :  5.1.3 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.5 (OK)

```

**Comment by ccordoba12** [comment]
The error seems to be in `concurrent` package, which is not really a Spyder dependency, but seems to be an Tornado one. Please check that you have the right version for your Python version. If you don't understand how to fix this error, we recommend you to use Anaconda instead, which is easier to install. Installing with pip requires more knowledge of the package ecosystem than Anaconda.

To finish, since this is not a Spyder bug, I'm closing this issue.
