### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by CHHobday** [spyder-ide/spyder#4235]
## Description

**What steps will reproduce the problem?**

1. happens everything I start spyder
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
was running code that got lost in loop around methods

## Version and main components

* Spyder Version: 3.1.3 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
Please give us a reproducible and simple example code that generates your problem so we can run and debug it in our side.

**Comment by CHHobday** [comment]
I reset to factory default and the kernel loaded ok. 
Thanks for replying, new to this sorry for the trouble.
Chris

**Comment by ccordoba12** [comment]
No worries! Glad things are working fine for you now :-)

**Comment by shireesha1998** [comment]
An error ocurred while starting the kernel

**Comment by shireesha1998** [comment]
An error ocurred while starting the kernel
Traceback (most recent call last):
File "C:\Users\Admin\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\Admin\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\Admin\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\Admin\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 279, in main
import_spydercustomize()
File "C:\Users\Admin\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 39, in import_spydercustomize
import spydercustomize
File "C:\Users\Admin\Anaconda3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 25, in 
from IPython.core.getipython import get_ipython
File "C:\Users\Admin\Anaconda3\lib\site‑packages\IPython\__init__.py", line 55, in 
from .terminal.embed import embed
File "C:\Users\Admin\Anaconda3\lib\site‑packages\IPython\terminal\embed.py", line 17, in 
from IPython.terminal.ipapp import load_default_config
File "C:\Users\Admin\Anaconda3\lib\site‑packages\IPython\terminal\ipapp.py", line 28, in 
from IPython.core.magics import (
File "C:\Users\Admin\Anaconda3\lib\site‑packages\IPython\core\magics\__init__.py", line 18, in 
from .code import CodeMagics, MacroToEdit
File "C:\Users\Admin\Anaconda3\lib\site‑packages\IPython\core\magics\code.py", line 23, in 
from urllib.request import urlopen
File "C:\Users\Admin\Anaconda3\lib\urllib\request.py", line 86, in 
import email
File "C:\Users\Admin\email.py", line 8, in 
import smtplib
File "C:\Users\Admin\Anaconda3\lib\smtplib.py", line 47, in 
import email.utils
ModuleNotFoundError: No module named 'email.utils'; 'email' is not a package
