### ISSUE TITLE
Kernel Error in python code in Spyder3

### ISSUE THREAD

**Issue by tejashreegore** [spyder-ide/spyder#4239]
## Description of your problem
After opening spyder3, an error is displayed. The code was running smoothly a few hours ago and now I cannot even run it. The following error is displayed:

An error ocurred while starting the kernel
Error in sitecustomize; set PYTHONVERBOSE for traceback:
IndentationError: expected an indented block (code.py, line 352)
Traceback (most recent call last):
File "C:\Users\Acer\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 227, in 
main()
File "C:\Users\Acer\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 200, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\Acer\Anaconda3\lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Acer\Anaconda3\lib\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "C:\Users\Acer\Anaconda3\lib\site‑packages\IPython\__init__.py", line 48, in 
from .core.application import Application
File "C:\Users\Acer\Anaconda3\lib\site‑packages\IPython\core\application.py", line 25, in 
from IPython.core import release, crashhandler
File "C:\Users\Acer\Anaconda3\lib\site‑packages\IPython\core\crashhandler.py", line 28, in 
from IPython.core import ultratb
File "C:\Users\Acer\Anaconda3\lib\site‑packages\IPython\core\ultratb.py", line 119, in 
from IPython.core import debugger
File "C:\Users\Acer\Anaconda3\lib\site‑packages\IPython\core\debugger.py", line 45, in 
from pdb import Pdb as OldPdb
File "C:\Users\Acer\Anaconda3\lib\pdb.py", line 76, in 
import code
File "C:\Users\Acer\Documents\Python Scripts\theano\code.py", line 352
j = idxs[pos] 
^
IndentationError: expected an indented block

Also I am not able to solve this indentation problem. Someone plz help me with this.

**What steps will reproduce the problem?**
1. Starting Spyder3

**What is the expected output? What do you see instead?**
This error shouldn't be visible instead I expect to see In[1].

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: 3.6.0
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Windows 8.1

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Please rename the file `....\theano\code.py` to something else. That seems to be interfering with other code in Spyder.
