### ISSUE TITLE
Pull request: Pull branch ccordoba12-object-inspector-html

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#425]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2010-10-22T11:34:52Z_

For about a month and a half I've been working on a better version of the object inspector that could show docstrings in html after they have been parsed by sphinx.

The results so far are quite beautiful, pleasant and, as far as I can tell, free of bugs, so I would like my work to be merged with the main tree.

I attach a screenshot so you can see the results.

Thanks,
Carlos

**Attachment:** [new_inspector.png](http://code.google.com/p/spyderlib/issues/detail?id=425)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=425_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-23T09:23:47Z_

That's pretty cool indeed :)

Thanks a lot for your work, you're now an official contributor to the project!

I've just pulled your changes to my local repo. Let me take a look at them (as soon as I can) and I'll push back all these changes to Spyder's repo.

**Status:** Accepted

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2010-10-23T16:10:54Z_

Thanks for your words and for your trust! I'm glad you liked my work. It has been a pleasure to work with your code, it's quite well structured and easy to read.

I also want to say that this is just the beginning: I have bigger plans for the inspector. I want to turn it into something like Mathematica's documentation center (which I miss a lot now that I'm on Python). QtWebkit is a fantastic technology and I'm sure it will let us do a lot of crazy stuff!

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-24T02:01:03Z_

I've just tested it.
I didn't have the time to look further but I get the following traceback when trying to show any valid object in the object inspector:
(does it ring any bell?)

Python 2.6.2 ( r262 :71605, Apr 14 2009, 22:40:02) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license" for more information.

\>>> Traceback (most recent call last):
  File "D:\Python\spyder\spyderlib\plugins\inspector.py", line 118, in \<lambda>
    lambda valid: self.force_refresh())
  File "D:\Python\spyder\spyderlib\plugins\inspector.py", line 249, in force_refresh
    self.set_object_text(None, force_refresh=True)
  File "D:\Python\spyder\spyderlib\plugins\inspector.py", line 261, in set_object_text
    found = self.show_help(text, ignore_unknown=ignore_unknown)
  File "D:\Python\spyder\spyderlib\plugins\inspector.py", line 403, in show_help
    html_text = sphinxify(doc_text)
  File "D:\Python\spyder\spyderlib\plugins\sphinxify.py", line 120, in sphinxify
    sphinx_app.build(None, [rst_name])
  File "C:\Python26\lib\site-packages\sphinx\application.py", line 205, in build
    self.builder.build_specific(filenames)
  File "C:\Python26\lib\site-packages\sphinx\builders\__init__.py", line 187, in build_specific
    'line' % len(to_write))
  File "C:\Python26\lib\site-packages\sphinx\builders\__init__.py", line 257, in build
    self.finish()
  File "C:\Python26\lib\site-packages\sphinx\builders\html.py", line 442, in finish
    self.copy_static_files()
  File "C:\Python26\lib\site-packages\sphinx\builders\html.py", line 567, in copy_static_files
    icontarget)
  File "C:\Python26\lib\site-packages\sphinx\util\osutil.py", line 114, in copyfile
    shutil.copyfile(source, dest)
  File "C:\Python26\lib\shutil.py", line 52, in copyfile
    fsrc = open(src, 'rb')
IOError: [Errno 2] No such file or directory: 'd:\\tempor~1\\fichie~1\\tmpgi0_08\\favicon.ico'

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-24T02:01:22Z_

**Labels:** -Type-Defect Type-Enhancement

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2010-10-24T08:56:33Z_

I'll take a look on Windows as soon as I can. I developed everything on Linux :-)

Which sphinx version are you using? On Ubuntu we're still on version 0.6.6

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-24T13:58:32Z_

That is sphinx v1.0.3.
I've just had the time to take a look at it, and it's fixed. Everything seems to work -- I'm commiting changes and pushing them in a few seconds. I did some minor changes to integrate things.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-24T14:04:20Z_

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2010-10-24T16:31:00Z_

Ok Pierre, thanks for taking the time to fix the bug.
