### ISSUE TITLE
python(x,y) doesn't run on Windows 7

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#426]
_From [madc...@gmail.com](https://code.google.com/u/118355754945936399225/) on 2010-10-24T00:58:15Z_

Plugin 'spyder' was found (Version: 1.1.5)
Traceback (most recent call last):
  File "C:\Python26\Scripts\xyhome.pyw", line 21, in \<module>
    xyhome.main()
  File "C:\Python26\lib\site-packages\xy\xyhome.pyw", line 672, in main
    form=MainWindow(options)
  File "C:\Python26\lib\site-packages\xy\xyhome.pyw", line 130, in __init__
    self.scanstartup()
  File "C:\Python26\lib\site-packages\xy\xyhome.pyw", line 561, in scanstartup
    default_startup()
  File "C:\Python26\lib\site-packages\xy\config.py", line 85, in default_startup

    filename=osp.join(STARTUP_PATH, CONF.get(None, 'startup'))
  File "C:\Python26\lib\ntpath.py", line 108, in join
    path += "\\" + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 9: ordinal
not in range(128)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=426_

**Comment by spyder-issues-migrator** [comment]
_From [madc...@gmail.com](https://code.google.com/u/118355754945936399225/) on 2010-10-23T23:03:35Z_

python(x,y) doesn't run on Windows 7. 
When run it in interactive mode console output error.
It seems that cant't process russian symbols in path.

(sorry for bad report, i have accidentally press enter and bug committed. Now i can't change it, only comment)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-26T04:28:45Z_

**Summary:** python(x,y) doesn't run on Windows 7

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-27T13:01:42Z_

This bug is directly related to Python(x,y) and has nothing to do with Spyder.
I see that you have submitted the same "Issue" on the Python(x,y) bug tracker: this issue will be handle there.

**Status:** Invalid
