### ISSUE TITLE
Spyder starting issues within Anaconda, Python 2.7.x, Windows 10, with Spyder 3.1.3

### ISSUE THREAD

**Issue by s0r2637** [spyder-ide/spyder#4271]
## Description of your problem
Spyder does not run after running conda update anaconda. 
**What steps will reproduce the problem?**
On the command prompt running Spyder gives the following error

```
Traceback (most recent call last):
  File "C:\Users\srajaraman\AppData\Local\Continuum\Anaconda2\Scripts\spyder-script.py", line 5, in <module>
    sys.exit(spyder.app.start.main())
  File "C:\Users\srajaraman\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\app\start.py", line 103, in main
    from spyder.app import mainwindow
  File "C:\Users\srajaraman\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "C:\Users\srajaraman\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\requirements.py", line 39, in check_qt
    import qtpy
  File "C:\Users\srajaraman\AppData\Local\Continuum\Anaconda2\lib\site-packages\qtpy\__init__.py", line 125, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: 2.7.13
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Windows 10

I need urgent help.   Do I need to re-install a fresh Anaconda all over?  Is there a package conflict problem?

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by s0r2637** [comment]
I found the problem.  I saw somewhere else that PyQt5 does not support Python 2.x.  The latest Ananconda update bumped the PyQt from 4.x to 5.x.  Therefore, Spyder could not start.  I reverted back to PyQt 4.x and now the problem seems to be resolved.  Why would Anaconda not keep in mind that PyQt5.x does not support Python 2.x? I thought Anaconda knows this conflict already before applying updates when I issue the command: `conda update anaconda`

**Comment by ccordoba12** [comment]
Anaconda supports PyQt5 in Python 2. In fact, it's the only distribution that does it at the moment.

I don't understand why things are broken for you, sorry.

**Comment by s0r2637** [comment]
Could the problem be related to the Qt version installed by Anaconda?  I want PyQt5 to work as it is the only PyQt version in Anaconda that supports matplotlib 2.x.  Is there something I can provide you to diagnose the problem?  I thought anaconda installation would be better than pip, but anaconda seems to be as much complicated from what I gather from my experience.  Any help would be appreciated.

**Comment by ccordoba12** [comment]
Please uninstall Anaconda and install it in a directory that contains less characters (e.g. `C:\Users\<your user>\Anaconda2`). Then try again.

**Comment by ccordoba12** [comment]
Closing because of lack of response.

**Comment by amberbhardwaj** [comment]
> Anaconda supports PyQt5 in Python 2. In fact, it's the only distribution that does it at the moment.
> 
> I don't understand why things are broken for you, sorry.

I am having the same issue for me the logs are :

C:\windows\system32>spyder
Traceback (most recent call last):
  File "C:\Users\H307839\AppData\Local\Continuum\anaconda2\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\H307839\AppData\Local\Continuum\anaconda2\lib\site-packages\spyder\app\start.py", line 186, in main
    from spyder.app import mainwindow
  File "C:\Users\H307839\AppData\Local\Continuum\anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 48, in <module>
    requirements.check_qt()
  File "C:\Users\H307839\AppData\Local\Continuum\anaconda2\lib\site-packages\spyder\requirements.py", line 41, in check_qt
    import qtpy
  File "C:\Users\H307839\AppData\Local\Continuum\anaconda2\lib\site-packages\qtpy\__init__.py", line 205, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
