### ISSUE TITLE
Spyder won't open

### ISSUE THREAD

**Issue by carllacan** [spyder-ide/spyder#4288]
## Description of your problem

Spyder won't open. The splash screen appears for a moment and then dissappears.

**What steps will reproduce the problem?**

1. Open Spyder

**What is the expected output? What do you see instead?**

I expect it to open, it doesn't. The splash screen appears for a moment.

**Please provide any additional information below**

Deleting the spyder.ini file didn't solve the problem. Neither reinstalling.

If I try to run Spyder in the console (spyder --show-console) I get the following input:
Traceback (most recent call last):
```
  File "/usr/bin/spyder", line 3, in <module>
    start_app.main()
  File "/usr/lib/python2.7/dist-packages/spyderlib/start_app.py", line 114, in main
    from spyderlib import spyder
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 155, in <module>
    from spyderlib.utils.environ import WinUserEnvDialog
  File "/usr/lib/python2.7/dist-packages/spyderlib/utils/environ.py", line 17, in <module>
    from spyderlib.widgets.dicteditor import DictEditor
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/dicteditor.py", line 39, in <module>
    from spyderlib.widgets.dicteditorutils import (sort_against, get_size,
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/dicteditorutils.py", line 78, in <module>
    import bs4
  File "/usr/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
```

## Versions and main components

* Spyder Version:   Spyder 2.3.8.
* Python Version: Python 2.7.12
* Qt Version:
* PyQt Version:
* Operating system: Ubuntu 16.04

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

Since I cannot execute Spyder I cannot provide this info.

**Comment by ccordoba12** [comment]
We don't support Spyder 2.3 anymore. Please install our latest version (3.1.3) and try again.
