### ISSUE TITLE
Spyder 3.1.3 crashes on OS X El capitan on python 3.6.0

### ISSUE THREAD

**Issue by pathcl** [spyder-ide/spyder#4294]
## Description of your problem

**What steps will reproduce the problem?**

1. Install python 3.6.0 
2. Install spyder 3.1.3
3. Open spyder3

**What is the expected output? What do you see instead?**
I see these errors:

An error ocurred while starting the kernel
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 227, in 
main()
File "/usr/local/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 200, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.6/site‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/usr/local/lib/python3.6/site‑packages/ipykernel/connect.py", line 18, in 
import jupyter_client
File "/usr/local/lib/python3.6/site‑packages/jupyter_client/__init__.py", line 7, in 
from .manager import KernelManager, run_kernel
File "/usr/local/lib/python3.6/site‑packages/jupyter_client/manager.py", line 32, in 
from .session import Session
File "/usr/local/lib/python3.6/site‑packages/jupyter_client/session.py", line 48, in 
from zmq.eventloop.ioloop import IOLoop
File "/usr/local/lib/python3.6/site‑packages/zmq/eventloop/__init__.py", line 3, in 
from zmq.eventloop.ioloop import IOLoop
File "/usr/local/lib/python3.6/site‑packages/zmq/eventloop/ioloop.py", line 35, in 
from tornado.ioloop import PollIOLoop, PeriodicCallback
File "/usr/local/lib/python3.6/site‑packages/tornado/ioloop.py", line 46, in 
from tornado.concurrent import TracebackFuture, is_future
File "/usr/local/lib/python3.6/site‑packages/tornado/concurrent.py", line 37, in 
from concurrent import futures
File "/usr/local/lib/python3.6/site‑packages/concurrent/futures/__init__.py", line 8, in 
from concurrent.futures._base import (FIRST_COMPLETED,
File "/usr/local/lib/python3.6/site‑packages/concurrent/futures/_base.py", line 357
raise type(self._exception), self._exception, self._traceback
^
SyntaxError: invalid syntax
Traceback (most recent call last):

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: 3.6.0
* Qt Version: 1.2.1
* PyQt Version: 5.8.1
* Operating system: Mac OS X Capitan

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
From your error report it can be seen clearly that the error is in the Tornado package, not in Spyder.

Please try to update it to see if that fixes the error.

**Comment by pathcl** [comment]
@ccordoba12 you're damn right! didn't notice it. I was using tornado (4.2) and upgraded to (4.4.2) however the error persists

**Comment by ccordoba12** [comment]
Sorry, it seems a problem in the `concurrent` package.

**Comment by pathcl** [comment]
I'll dig deeper tomorrow

**Comment by pathcl** [comment]
I upgraded to python 3.6.1 and the error goes away :)

**Comment by ccordoba12** [comment]
:+1: Great!
