### ISSUE TITLE
Spyder won't start on Ubuntu 16.04

### ISSUE THREAD

**Issue by sophia-wright-blue** [spyder-ide/spyder#4309]
I updated Spyder on Ubuntu 16.04, and now it won't start. This is the error that I get:

```
 $spyder
Traceback (most recent call last):
  File "/usr/local/bin/spyder", line 3, in <module>
    start_app.main()
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/start_app.py", line 114, in main
    from spyderlib import spyder
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/spyder.py", line 155, in <module>
    from spyderlib.utils.environ import WinUserEnvDialog
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/utils/environ.py", line 17, in <module>
    from spyderlib.widgets.dicteditor import DictEditor
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/dicteditor.py", line 39, in <module>
    from spyderlib.widgets.dicteditorutils import (sort_against, get_size,
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/dicteditorutils.py", line 78, in <module>
    import bs4
  File "/usr/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):

AttributeError: 'module' object has no attribute '_base'

```

## Versions and main components

* Spyder Version: 3.
* Python Version: 2.7
* Qt Version:
* PyQt Version:
* Operating system: Ubuntu 16.04

Any help to fix this problem would be greatly appreciated. Thank you.

**Comment by ccordoba12** [comment]
You *don't* have Spyder 3 installed. That's wrong.

**Comment by sophia-wright-blue** [comment]
You're right, I updated Spyder from the terminal again, and it works now! sorry about this, thank you for replying

**Comment by ccordoba12** [comment]
Great!! I'm glad that a simple update solved your problem :-)

Don't hesitate to open more issue if you need to.

**Comment by EvaldoAraujo** [comment]
Isso resolveu meu problema.
That solved my problem.
sudo pip3 install html5lib==0.9999999
Link: https://bugs.launchpad.net/beautifulsoup/+bug/1603299
:)

**Comment by wcipriano** [comment]
the solution given by EvaldoAraujo solved my problem. Thanks!
