### ISSUE TITLE
IPython Kernel not working

### ISSUE THREAD

**Issue by wa1618i** [spyder-ide/spyder#4331]
## Description of your problem

I want to use Ipython as my Spyder 3 console but it won't show.
I have researched possible solutions from web but still won't solve my problem.
Note that i have python2.7 and python 3. Python 3 was set to be within ENVIRONMENT/WORKSPACE (conda create --name NN python=3.5)

**What is the expected output? What do you see instead?**
An error ocurred while starting the kernel
Traceback (most recent call last):
File "C:\Users\Allan\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 227, in 
main()
File "C:\Users\Allan\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 200, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\Allan\AppData\Roaming\Python\Python27\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Allan\AppData\Roaming\Python\Python27\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\__init__.py", line 48, in 
from .core.application import Application
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\application.py", line 25, in 
from IPython.core import release, crashhandler
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\crashhandler.py", line 28, in 
from IPython.core import ultratb
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\ultratb.py", line 128, in 
from IPython.utils.terminal import get_terminal_size
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\utils\terminal.py", line 22, in 
from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size
Traceback (most recent call last):
File "C:\Users\Allan\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 227, in 
main()
File "C:\Users\Allan\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 200, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\Allan\AppData\Roaming\Python\Python27\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Allan\AppData\Roaming\Python\Python27\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\__init__.py", line 48, in 
from .core.application import Application
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\application.py", line 25, in 
from IPython.core import release, crashhandler
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\crashhandler.py", line 28, in 
from IPython.core import ultratb
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\ultratb.py", line 128, in 
from IPython.utils.terminal import get_terminal_size
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\utils\terminal.py", line 22, in 
from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size
Traceback (most recent call last):
File "C:\Users\Allan\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 227, in 
main()
File "C:\Users\Allan\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 200, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\Allan\AppData\Roaming\Python\Python27\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Allan\AppData\Roaming\Python\Python27\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\__init__.py", line 48, in 
from .core.application import Application
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\application.py", line 25, in 
from IPython.core import release, crashhandler
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\crashhandler.py", line 28, in 
from IPython.core import ultratb
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\ultratb.py", line 128, in 
from IPython.utils.terminal import get_terminal_size
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\utils\terminal.py", line 22, in 
from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size
Traceback (most recent call last):
File "C:\Users\Allan\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 227, in 
main()
File "C:\Users\Allan\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 200, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\Allan\AppData\Roaming\Python\Python27\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Allan\AppData\Roaming\Python\Python27\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\__init__.py", line 48, in 
from .core.application import Application
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\application.py", line 25, in 
from IPython.core import release, crashhandler
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\crashhandler.py", line 28, in 
from IPython.core import ultratb
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\ultratb.py", line 128, in 
from IPython.utils.terminal import get_terminal_size
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\utils\terminal.py", line 22, in 
from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size
Traceback (most recent call last):
File "C:\Users\Allan\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 227, in 
main()
File "C:\Users\Allan\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 200, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\Allan\AppData\Roaming\Python\Python27\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Allan\AppData\Roaming\Python\Python27\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\__init__.py", line 48, in 
from .core.application import Application
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\application.py", line 25, in 
from IPython.core import release, crashhandler
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\crashhandler.py", line 28, in 
from IPython.core import ultratb
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\ultratb.py", line 128, in 
from IPython.utils.terminal import get_terminal_size
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\utils\terminal.py", line 22, in 
from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size
Traceback (most recent call last):
File "C:\Users\Allan\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 227, in 
main()
File "C:\Users\Allan\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 200, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\Allan\AppData\Roaming\Python\Python27\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Allan\AppData\Roaming\Python\Python27\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\__init__.py", line 48, in 
from .core.application import Application
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\application.py", line 25, in 
from IPython.core import release, crashhandler
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\crashhandler.py", line 28, in 
from IPython.core import ultratb
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\ultratb.py", line 128, in 
from IPython.utils.terminal import get_terminal_size
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\utils\terminal.py", line 22, in 
from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size
Traceback (most recent call last):
File "C:\Users\Allan\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 232, in 
main()
File "C:\Users\Allan\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 205, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\Allan\AppData\Roaming\Python\Python27\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Allan\AppData\Roaming\Python\Python27\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\__init__.py", line 48, in 
from .core.application import Application
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\application.py", line 25, in 
from IPython.core import release, crashhandler
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\crashhandler.py", line 28, in 
from IPython.core import ultratb
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\ultratb.py", line 128, in 
from IPython.utils.terminal import get_terminal_size
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\utils\terminal.py", line 22, in 
from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size
Traceback (most recent call last):
File "C:\Users\Allan\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 232, in 
main()
File "C:\Users\Allan\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 205, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\Allan\AppData\Roaming\Python\Python27\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Allan\AppData\Roaming\Python\Python27\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\__init__.py", line 48, in 
from .core.application import Application
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\application.py", line 25, in 
from IPython.core import release, crashhandler
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\crashhandler.py", line 28, in 
from IPython.core import ultratb
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\ultratb.py", line 128, in 
from IPython.utils.terminal import get_terminal_size
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\utils\terminal.py", line 22, in 
from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size
Traceback (most recent call last):
File "C:\Users\Allan\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 232, in 
main()
File "C:\Users\Allan\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 205, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\Allan\AppData\Roaming\Python\Python27\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Allan\AppData\Roaming\Python\Python27\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\__init__.py", line 48, in 
from .core.application import Application
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\application.py", line 25, in 
from IPython.core import release, crashhandler
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\crashhandler.py", line 28, in 
from IPython.core import ultratb
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\ultratb.py", line 128, in 
from IPython.utils.terminal import get_terminal_size
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\utils\terminal.py", line 22, in 
from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size
Traceback (most recent call last):
File "C:\Users\Allan\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 232, in 
main()
File "C:\Users\Allan\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 205, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\Allan\AppData\Roaming\Python\Python27\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Allan\AppData\Roaming\Python\Python27\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\__init__.py", line 48, in 
from .core.application import Application
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\application.py", line 25, in 
from IPython.core import release, crashhandler
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\crashhandler.py", line 28, in 
from IPython.core import ultratb
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\ultratb.py", line 128, in 
from IPython.utils.terminal import get_terminal_size
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\utils\terminal.py", line 22, in 
from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size
Traceback (most recent call last):
File "C:\Users\Allan\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 232, in 
main()
File "C:\Users\Allan\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 205, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\Allan\AppData\Roaming\Python\Python27\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Allan\AppData\Roaming\Python\Python27\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\__init__.py", line 48, in 
from .core.application import Application
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\application.py", line 25, in 
from IPython.core import release, crashhandler
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\crashhandler.py", line 28, in 
from IPython.core import ultratb
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\core\ultratb.py", line 128, in 
from IPython.utils.terminal import get_terminal_size
File "C:\Users\Allan\Anaconda2\lib\site‑packages\IPython\utils\terminal.py", line 22, in 
from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size

**Please provide any additional information below**

## Versions and main components

* Spyder Version:3.1.3
* Python Version:2.7 and 3.5
* Qt Version:5.6.2
* PyQt Version:5.6.0
* Operating system: Windows7

## Dependencies

jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.5.4 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by wa1618i** [comment]
Here is my Python 27 (my root):
(C:\Users\Allan\Anaconda2) C:\Users\Allan>conda list
# packages in environment at C:\Users\Allan\Anaconda2:
#
_license                  1.1                      py27_1
alabaster                 0.7.10                   py27_0
anaconda                  custom                   py27_0
anaconda-client           1.6.2                    py27_0
anaconda-navigator        1.5.1                    py27_0
anaconda-project          0.4.1                    py27_0
appdirs                   1.4.3                     <pip>
argcomplete               1.0.0                    py27_1
astroid                   1.4.9                    py27_0
astropy                   1.3.2               np111py27_0
babel                     2.4.0                    py27_0
backports                 1.0                      py27_0
backports.shutil_get_terminal_size 1.0.0                    py27_1    conda-forge
backports_abc             0.5                      py27_0
bayesian-optimization     0.4.0                     <pip>
beautifulsoup4            4.5.3                    py27_0
bitarray                  0.8.1                    py27_1
blaze                     0.10.1                   py27_0
bleach                    1.5.0                    py27_0
bokeh                     0.12.5                   py27_0
boto                      2.46.1                   py27_0
bottleneck                1.2.0               np111py27_0
bzip2                     1.0.6                     vc9_3  [vc9]
cdecimal                  2.3                      py27_2
certifi                   2017.1.23                 <pip>
cffi                      1.9.1                    py27_0
chardet                   2.3.0                    py27_0
chest                     0.2.3                    py27_0
click                     6.7                      py27_0
cloudpickle               0.2.2                    py27_0
clyent                    1.2.2                    py27_0
colorama                  0.3.7                    py27_0
comtypes                  1.1.2                    py27_0
conda                     4.2.13                   py27_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
configobj                 5.0.6                    py27_0
configparser              3.5.0                    py27_0
console_shortcut          0.1.1                    py27_1
contextlib2               0.5.4                    py27_0
cryptography              1.7.1                    py27_0
curl                      7.52.1                    vc9_0  [vc9]
cycler                    0.10.0                   py27_0
cython                    0.25.2                   py27_0
cytoolz                   0.8.2                    py27_0
dask                      0.14.1                   py27_0
datashape                 0.5.4                    py27_0
decorator                 4.0.11                   py27_0
dill                      0.2.5                    py27_0
docutils                  0.13.1                   py27_0
entrypoints               0.2.2                    py27_1
enum34                    1.1.6                    py27_0
et_xmlfile                1.0.1                    py27_0
fastcache                 1.0.2                    py27_1
flask                     0.12.1                   py27_0
flask-cors                3.0.2                    py27_0
freetype                  2.5.5                     vc9_2  [vc9]
funcsigs                  1.0.2                    py27_0
functools32               3.2.3.2                  py27_0
futures                   3.0.5                    py27_0
get_terminal_size         1.0.0                    py27_0
gevent                    1.2.1                    py27_0
greenlet                  0.4.12                   py27_0
grin                      1.2.1                    py27_3
h5py                      2.7.0               np111py27_0
hdf5                      1.8.15.1                  vc9_4  [vc9]
heapdict                  1.0.0                    py27_1
html5lib                  0.999                    py27_0
icu                       57.1                      vc9_0  [vc9]
idna                      2.2                      py27_0
imagesize                 0.7.1                    py27_0
ipaddress                 1.0.18                   py27_0
ipykernel                 4.6.0                    py27_0
ipython                   5.3.0                    py27_0
ipython-genutils          0.2.0                     <pip>
ipython_genutils          0.2.0                    py27_0
ipywidgets                6.0.0                    py27_0
isort                     4.2.5                    py27_0
itsdangerous              0.24                     py27_0
jdcal                     1.3                      py27_0
jedi                      0.9.0                    py27_1
jinja2                    2.9.5                    py27_0
jpeg                      9b                        vc9_0  [vc9]
jsonschema                2.5.1                    py27_0
jupyter                   1.0.0                    py27_3
jupyter_client            5.0.1                    py27_0
jupyter_console           5.1.0                    py27_0
jupyter_core              4.3.0                    py27_0
Keras                     2.0.2                     <pip>
lazy-object-proxy         1.2.2                    py27_0
libgpuarray               0.6.2                     vc9_0  [vc9]
libpng                    1.6.27                    vc9_0  [vc9]
libpython                 2.0                      py27_0
libtiff                   4.0.6                     vc9_3  [vc9]
llvmlite                  0.16.0                   py27_0
locket                    0.2.0                    py27_1
lxml                      3.7.3                    py27_0
m2w64-binutils            2.25.1                        5
m2w64-bzip2               1.0.6                         6
m2w64-crt-git             5.0.0.4636.2595836               2
m2w64-gcc                 5.3.0                         6
m2w64-gcc-ada             5.3.0                         6
m2w64-gcc-fortran         5.3.0                         6
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gcc-objc            5.3.0                         6
m2w64-gmp                 6.1.0                         2
m2w64-headers-git         5.0.0.4636.c0ad18a               2
m2w64-isl                 0.16.1                        2
m2w64-libiconv            1.14                          6
m2w64-libmangle-git       5.0.0.4509.2e5a9a2               2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-make                4.1.2351.a80a8b8               2
m2w64-mpc                 1.0.3                         3
m2w64-mpfr                3.1.4                         4
m2w64-pkg-config          0.29.1                        2
m2w64-toolchain           5.3.0                         7
m2w64-tools-git           5.0.0.4592.90b8472               2
m2w64-windows-default-manifest 6.4                           3
m2w64-winpthreads-git     5.0.0.4634.697f757               2
m2w64-zlib                1.2.8                        10
mako                      1.0.6                    py27_0
markupsafe                0.23                     py27_2
matplotlib                2.0.0               np111py27_0
menuinst                  1.4.4                    py27_0
mistune                   0.7.4                    py27_0
mkl                       2017.0.1                      0
mkl-service               1.1.2                    py27_3
mpmath                    0.19                     py27_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.4.9                    py27_0
nbconvert                 5.1.1                    py27_0
nbformat                  4.3.0                    py27_0
networkx                  1.11                     py27_0
nltk                      3.2.2                    py27_0
nose                      1.3.7                    py27_1
notebook                  5.0.0                    py27_0
numba                     0.31.0              np111py27_0
numexpr                   2.6.2               np111py27_0
numpy                     1.11.3                   py27_0
numpy                     1.12.1                    <pip>
numpydoc                  0.6.0                    py27_0
odo                       0.5.0                    py27_1
olefile                   0.44                     py27_0
openpyxl                  2.4.1                    py27_0
openssl                   1.0.2k                    vc9_0  [vc9]
packaging                 16.8                      <pip>
pandas                    0.19.2              np111py27_1
pandocfilters             1.4.1                    py27_0
partd                     0.3.7                    py27_0
path.py                   10.1                     py27_0
pathlib2                  2.2.0                    py27_0
patsy                     0.4.1                    py27_0
pep8                      1.7.0                    py27_0
pickleshare               0.7.4                    py27_0
pillow                    4.1.0                    py27_0
pip                       9.0.1                    py27_1
ply                       3.10                     py27_0
prompt_toolkit            1.0.14                   py27_0
psutil                    5.2.1                    py27_0
py                        1.4.32                   py27_0
pyasn1                    0.2.3                    py27_0
pycosat                   0.6.2                    py27_0
pycparser                 2.17                     py27_0
pycrypto                  2.6.1                    py27_5
pycurl                    7.43.0                   py27_2
pyflakes                  1.5.0                    py27_0
pygments                  2.2.0                    py27_0
Pygments                  2.2.0                     <pip>
pygpu                     0.6.2                    py27_0
pyLightGBM                0.2.6                     <pip>
pylint                    1.6.4                    py27_1
pyopenssl                 16.2.0                   py27_0
pyparsing                 2.2.0                     <pip>
pyparsing                 2.1.4                    py27_0
pyqt                      5.6.0                    py27_2
pytables                  3.2.2               np111py27_4
pytest                    3.0.7                    py27_0
python                    2.7.13                        0
python-dateutil           2.6.0                    py27_0
pytz                      2017.2                   py27_0
pywavelets                0.5.2               np111py27_0
pywFM                     0.9.0                     <pip>
pywin32                   220                      py27_2
pyyaml                    3.12                     py27_0
pyzmq                     16.0.2                   py27_0
qt                        5.6.2                     vc9_3  [vc9]
qtawesome                 0.4.4                    py27_0
qtconsole                 4.3.0                    py27_0
qtpy                      1.2.1                    py27_0
requests                  2.13.0                   py27_0
rope                      0.9.4                    py27_1
ruamel_yaml               0.11.14                  py27_1
runipy                    0.1.5                    py27_0
scandir                   1.5                      py27_0
scikit-image              0.13.0              np111py27_0
scikit-learn              0.18.1              np111py27_1
scipy                     0.19.0              np111py27_0
seaborn                   0.7.1                    py27_0
setuptools                27.2.0                   py27_1
setuptools                34.3.3                    <pip>
simplegeneric             0.8.1                    py27_1
singledispatch            3.4.0.3                  py27_0
sip                       4.18                     py27_0
six                       1.10.0                   py27_0
snowballstemmer           1.2.1                    py27_0
sockjs-tornado            1.0.3                    py27_0
sphinx                    1.5.4                    py27_0
spyder                    3.1.3                    py27_0
sqlalchemy                1.1.8                    py27_0
ssl_match_hostname        3.4.0.2                  py27_1
statsmodels               0.8.0               np111py27_0
subprocess32              3.2.7                    py27_0
sympy                     1.0                      py27_0
testpath                  0.3                      py27_0
theano                    0.9.0                    py27_0
tk                        8.5.18                    vc9_0  [vc9]
toolz                     0.8.2                    py27_0
tornado                   4.4.2                    py27_0
traitlets                 4.3.2                     <pip>
traitlets                 4.3.2                    py27_0
unicodecsv                0.14.1                   py27_0
vs2008_runtime            9.00.30729.5054               0
wcwidth                   0.1.7                    py27_0
werkzeug                  0.12.1                   py27_0
wheel                     0.29.0                   py27_0
widgetsnbextension        2.0.0                    py27_0
win_unicode_console       0.5                      py27_0
wrapt                     1.10.10                  py27_0
xgboost                   0.6                       <pip>
xlrd                      1.0.0                    py27_0
xlsxwriter                0.9.6                    py27_0
xlwings                   0.10.4                   py27_0
xlwt                      1.2.0                    py27_0
zlib                      1.2.8                     vc9_3  [vc9]


Actually Ipython console working fine in Python 3.5 Spyder but most of my working is still in Python 27 so hopefully can be fixed. 
Anyway, here is my Python 3.5: 
(C:\Users\Allan\Anaconda2) C:\Users\Allan>activate neuralnets
(neuralnets) C:\Users\Allan>conda list
# packages in environment at C:\Users\Allan\Anaconda2\envs\neuralnets:
#
alabaster                 0.7.10                   py35_0
astroid                   1.4.9                    py35_0
babel                     2.4.0                    py35_0
bleach                    1.5.0                    py35_0
chardet                   2.3.0                    py35_0
cloudpickle               0.2.2                    py35_0
colorama                  0.3.7                    py35_0
decorator                 4.0.11                   py35_0
docutils                  0.13.1                   py35_0
entrypoints               0.2.2                    py35_1
html5lib                  0.999                    py35_0
icu                       57.1                     vc14_0  [vc14]
imagesize                 0.7.1                    py35_0
ipykernel                 4.6.0                    py35_0
ipython                   5.3.0                    py35_0
ipython_genutils          0.2.0                    py35_0
isort                     4.2.5                    py35_0
jedi                      0.9.0                    py35_1
jinja2                    2.9.5                    py35_0
jpeg                      9b                       vc14_0  [vc14]
jsonschema                2.5.1                    py35_0
jupyter_client            5.0.1                    py35_0
jupyter_core              4.3.0                    py35_0
Keras                     2.0.2                     <pip>
lazy-object-proxy         1.2.2                    py35_0
libgpuarray               0.6.2                    vc14_0  [vc14]
libpng                    1.6.27                   vc14_0  [vc14]
libpython                 2.0                      py35_0
m2w64-binutils            2.25.1                        5
m2w64-bzip2               1.0.6                         6
m2w64-crt-git             5.0.0.4636.2595836               2
m2w64-gcc                 5.3.0                         6
m2w64-gcc-ada             5.3.0                         6
m2w64-gcc-fortran         5.3.0                         6
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gcc-objc            5.3.0                         6
m2w64-gmp                 6.1.0                         2
m2w64-headers-git         5.0.0.4636.c0ad18a               2
m2w64-isl                 0.16.1                        2
m2w64-libiconv            1.14                          6
m2w64-libmangle-git       5.0.0.4509.2e5a9a2               2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-make                4.1.2351.a80a8b8               2
m2w64-mpc                 1.0.3                         3
m2w64-mpfr                3.1.4                         4
m2w64-pkg-config          0.29.1                        2
m2w64-toolchain           5.3.0                         7
m2w64-tools-git           5.0.0.4592.90b8472               2
m2w64-windows-default-manifest 6.4                           3
m2w64-winpthreads-git     5.0.0.4634.697f757               2
m2w64-zlib                1.2.8                        10
mako                      1.0.6                    py35_0
markupsafe                0.23                     py35_2
mingw                     4.7                           1
mistune                   0.7.4                    py35_0
mkl                       2017.0.1                      0
mkl-service               1.1.2                    py35_3
msys2-conda-epoch         20160418                      1
nbconvert                 5.1.1                    py35_0
nbformat                  4.3.0                    py35_0
numpy                     1.12.1                   py35_0
numpydoc                  0.6.0                    py35_0
openssl                   1.0.2k                   vc14_0  [vc14]
pandas                    0.19.2              np112py35_1
pandocfilters             1.4.1                    py35_0
path.py                   10.1                     py35_0
pep8                      1.7.0                    py35_0
pickleshare               0.7.4                    py35_0
pip                       9.0.1                    py35_1
prompt_toolkit            1.0.14                   py35_0
protobuf                  3.2.0                     <pip>
psutil                    5.2.1                    py35_0
pyflakes                  1.5.0                    py35_0
pygments                  2.2.0                    py35_0
pygpu                     0.6.2                    py35_0
pylint                    1.6.4                    py35_1
pyqt                      5.6.0                    py35_2
python                    3.5.3                         0
python-dateutil           2.6.0                    py35_0
pytz                      2017.2                   py35_0
pywin32                   220                      py35_2
PyYAML                    3.12                      <pip>
pyzmq                     16.0.2                   py35_0
qt                        5.6.2                    vc14_3  [vc14]
qtawesome                 0.4.4                    py35_0
qtconsole                 4.3.0                    py35_0
qtpy                      1.2.1                    py35_0
requests                  2.13.0                   py35_0
rope                      0.9.4                    py35_1
scikit-learn              0.18.1              np112py35_1
scipy                     0.19.0              np112py35_0
setuptools                27.2.0                   py35_1
simplegeneric             0.8.1                    py35_1
sip                       4.18                     py35_0
six                       1.10.0                   py35_0
snowballstemmer           1.2.1                    py35_0
sphinx                    1.5.4                    py35_0
spyder                    3.1.3                    py35_0
tensorflow                1.0.1                     <pip>
testpath                  0.3                      py35_0
theano                    0.9.0                    py35_0
tornado                   4.4.2                    py35_0
traitlets                 4.3.2                    py35_0
vs2015_runtime            14.0.25123                    0
wcwidth                   0.1.7                    py35_0
wheel                     0.29.0                   py35_0
win_unicode_console       0.5                      py35_0
wrapt                     1.10.10                  py35_0
xgboost                   0.6                       <pip>
zlib                      1.2.8                    vc14_3  [vc14]

**Comment by wa1618i** [comment]
Finally after countless try from all possible solutions around the web, this solution works:
pip install --user --upgrade ipython==4.1.1

such a frustration!

**Comment by ccordoba12** [comment]
Nop, this was your problem

    backports.shutil_get_terminal_size 1.0.0 py27_1 conda-forge

You need to stop mixing conda-forge, Anaconda and pip packages. This is the idea:

1. Create and install conda-forge packages in a new environment. Never, ever, use the root environment to install them. This is because conda-forge pretends to be a *full* replacement for all packages provided by Anaconda, so it needs to be installed separately.
2. Use pip packages *only* when Anaconda doesn't provide a similar package (e.g. Django or Flask plugins). Using pip packages instead of Anaconda ones is a recipe for disaster too because pip installs compiled wheels, which can very easily break other Anaconda packages.

**Comment by wa1618i** [comment]
Ohh that news to me. Thanks I'll keep that in mind.
