### ISSUE TITLE
Upgrading to Spyder 3.1.3 causes failure due to QtWebKitWidgets

### ISSUE THREAD

**Issue by mat2py** [spyder-ide/spyder#4336]
## Description of your problem

**What steps will reproduce the problem?**

1. I ran conda to check for an upgrade and it upgraded from:
`spyder:             3.1.3-py27_1      conda-forge --> 3.1.3-py27_2      conda-forge`

Full upgrade list:
```
The following packages will be UPDATED:

    anaconda-navigator: 1.2.3-py27_0                  --> 1.3.2-py27_0                 
    matplotlib:         1.5.3-np111py27_7 conda-forge --> 2.0.0-np111py27_3 conda-forge
    pyqt:               4.11.4-py27_2     conda-forge --> 5.6.0-py27_0      conda-forge
    qt:                 4.8.7-7           conda-forge --> 5.6.2-1           conda-forge
    qtconsole:          4.2.1-py27_1      conda-forge --> 4.3.0-py27_0      conda-forge
    spyder:             3.1.3-py27_1      conda-forge --> 3.1.3-py27_2      conda-forge

The following packages will be DOWNGRADED due to dependency conflicts:

    obspy:              1.0.3-py27_0      conda-forge --> 1.0.2-py27_1      conda-forge
```

2. Running `spyder` from terminal causes failure:
```
Traceback (most recent call last):
  File "/home/mplain/anaconda2/envs/rootclone/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/home/mplain/anaconda2/envs/rootclone/lib/python2.7/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/home/mplain/anaconda2/envs/rootclone/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/home/mplain/anaconda2/envs/rootclone/lib/python2.7/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: No module named QtWebKitWidgets
```

## Versions and main components

* Spyder Version: 3.1.3-py27_2
* Python Version: 2.7
* Qt Version: 5.6.2-1
* PyQt Version: 5.6.0-py27_0
* Operating system: Ubuntu 16.04

**Comment by mat2py** [comment]
Unfortunately I can't downgrade again because it only updated from:
`spyder:             3.1.3-py27_1      conda-forge --> 3.1.3-py27_2      conda-forge`

and so doing the following command doesn't register:
`conda install spyder-app=3.1.3-py27_1`

**Comment by mat2py** [comment]
temporary fix is to downgrade spyder:

```
conda remove spyder
conda install spyder=3.1.2
```

**Comment by ccordoba12** [comment]
This is a problem with conda-forge, right now it's been discussed how to solve it.

However, there's nothing we can do about it in Spyder, sorry.
