### ISSUE TITLE
Spyder Crashed During Last Session

### ISSUE THREAD

**Issue by cagataytanyildiz** [spyder-ide/spyder#4343]
## Description of your problem
I installed anaconda(https://www.continuum.io/downloads#linux). After that I update anaconda-navigator and lastly tried to open spyder. Then I got that error (spyder crashed during last session). I tried these commands:

Command: pyhton spyder --reset
Result: python: can't open file 'spyder': [Errno 2] No such file or directory

Command: spyder --show-console
Result:
Traceback (most recent call last):
  File "/home/user/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2999, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/user/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2901, in run_spyder
    main.setup()
  File "/home/user/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 766, in setup
    message=_("Spyder Internal Console\n\n"
  File "/home/user/anaconda2/lib/python2.7/site-packages/spyder/plugins/console.py", line 65, in __init__
    light_background=light_background)
  File "/home/user/anaconda2/lib/python2.7/site-packages/spyder/widgets/internalshell.py", line 141, in __init__
    profile)
  File "/home/user/anaconda2/lib/python2.7/site-packages/spyder/widgets/shell.py", line 687, in __init__
    self.shortcuts = self.create_shortcuts()
  File "/home/user/anaconda2/lib/python2.7/site-packages/spyder/widgets/shell.py", line 699, in create_shortcuts
    parent=self)
  File "/home/user/anaconda2/lib/python2.7/site-packages/spyder/config/gui.py", line 121, in config_shortcut
    keystr = get_shortcut(context, name)
  File "/home/user/anaconda2/lib/python2.7/site-packages/spyder/config/gui.py", line 95, in get_shortcut
    return CONF.get('shortcuts', '%s/%s' % (context, name))
  File "/home/user/anaconda2/lib/python2.7/site-packages/spyder/config/user.py", line 375, in get
    raise cp.NoOptionError(option, section)
NoOptionError: No option 'Console/Inspect current object' in section: 'shortcuts'
user@makine:~/Downloads$ spyder --show-console
Traceback (most recent call last):
  File "/home/user/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2999, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/user/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2901, in run_spyder
    main.setup()
  File "/home/user/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 766, in setup
    message=_("Spyder Internal Console\n\n"
  File "/home/user/anaconda2/lib/python2.7/site-packages/spyder/plugins/console.py", line 65, in __init__
    light_background=light_background)
  File "/home/user/anaconda2/lib/python2.7/site-packages/spyder/widgets/internalshell.py", line 141, in __init__
    profile)
  File "/home/user/anaconda2/lib/python2.7/site-packages/spyder/widgets/shell.py", line 687, in __init__
    self.shortcuts = self.create_shortcuts()
  File "/home/user/anaconda2/lib/python2.7/site-packages/spyder/widgets/shell.py", line 699, in create_shortcuts
    parent=self)
  File "/home/user/anaconda2/lib/python2.7/site-packages/spyder/config/gui.py", line 121, in config_shortcut
    keystr = get_shortcut(context, name)
  File "/home/user/anaconda2/lib/python2.7/site-packages/spyder/config/gui.py", line 95, in get_shortcut
    return CONF.get('shortcuts', '%s/%s' % (context, name))
  File "/home/user/anaconda2/lib/python2.7/site-packages/spyder/config/user.py", line 375, in get
    raise cp.NoOptionError(option, section)
NoOptionError: No option 'Console/Inspect current object' in section: 'shortcuts'

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: 2.7
* PyQt Version: 4.3.0
* Operating system: BunsenLabs GNU/Linux 8.7 (Hydrogen)

**Comment by cagataytanyildiz** [comment]
I found solution. https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/m-jaCWgcF-s
According to this Turkish language can be problem. So please, add support for Turkish. After I read this article I can use Spyder just typing LANG=C spyder.

**Comment by cagataytanyildiz** [comment]
"LANG=c anaconda-navigator"  is also worked for me.

**Comment by ccordoba12** [comment]
In the post you referenced you can see that there is a general problem with using Turkish with Python 2.7. You should use Python 3 instead.

There's nothing we can do in our side, sorry.
