### ISSUE TITLE
Spyder crashed during last session

### ISSUE THREAD

**Issue by dgvisnadi** [spyder-ide/spyder#4364]
## Description of your problem

My Spyder is crashing when opening it. 
I tried to both:
`spyder --reset`
`python spyder --reset`

It seems to run as it says:
`$ spyder --reset
*** Reset Spyder settings to defaults ***
removing: /Users/Dimitri/.spyder-py3/spyder.ini
removing: /Users/Dimitri/.spyder-py3/temp.py
removing: /Users/Dimitri/.spyder-py3/template.py
removing: /Users/Dimitri/.spyder-py3/history_internal.py
removing: /Users/Dimitri/.spyder-py3/workingdir
removing: /Users/Dimitri/.spyder-py3/.ropeproject
removing: /Users/Dimitri/.spyder-py3/langconfig
removing: /Users/Dimitri/.spyder-py3/spyder.lock`

**What is the expected output? What do you see instead?**
The Spyder crash log says the following:

`Traceback (most recent call last):
  File "//anaconda/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 2999, in main
    mainwindow = run_spyder(app, options, args)
  File "//anaconda/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 2901, in run_spyder
    main.setup()
  File "//anaconda/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 824, in setup
    self.findinfiles = FindInFiles(self)
  File "//anaconda/lib/python3.5/site-packages/spyder/plugins/findinfiles.py", line 52, in __init__
    include = self.include_patterns()
  File "//anaconda/lib/python3.5/site-packages/spyder/plugins/findinfiles.py", line 105, in include_patterns
    for ext in get_edit_extensions():
  File "//anaconda/lib/python3.5/site-packages/spyder/config/utils.py", line 140, in get_edit_extensions
    edit_filetypes = get_edit_filetypes()
  File "//anaconda/lib/python3.5/site-packages/spyder/config/utils.py", line 118, in get_edit_filetypes
    pygments_exts = _get_pygments_extensions()
  File "//anaconda/lib/python3.5/site-packages/spyder/config/utils.py", line 85, in _get_pygments_extensions
    for lx in lexers.get_all_lexers():
  File "//anaconda/lib/python3.5/site-packages/pygments/lexers/__init__.py", line 53, in get_all_lexers
    for lexer in find_plugin_lexers():
  File "//anaconda/lib/python3.5/site-packages/pygments/plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "//anaconda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2301, in load
    self.require(*args, **kwargs)
  File "//anaconda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2324, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "//anaconda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pytz 2017.2 (/anaconda/lib/python3.5/site-packages), Requirement.parse('pytz<2017.0,>=2016.3'))
`

## Versions and main components

* Spyder Version: Spyder 3.0.0
* Python Version: Python 3.5.2 :: Anaconda custom (x86_64)
* Qt Version:
* PyQt Version:
* Operating system: macOS Sierra

**Comment by dgvisnadi** [comment]
Sorry, for being impatient. I deleted Anaconda and reinstalled it. Everything works now.
