### ISSUE TITLE
cannot run spyder - KeyError: 'DocPath'

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#440]
_From [NvSolodk...@gmail.com](https://code.google.com/u/100184571128128238043/) on 2010-11-07T16:18:12Z_

Traceback (most recent call last):
  File "d:\Python26\lib\site-packages\spyderlib\spyder.py", line 1470, in main
    mainwindow = run_spyder(app, options)
  File "d:\Python26\lib\site-packages\spyderlib\spyder.py", line 1407, in run_sp
yder
    main.setup()
  File "d:\Python26\lib\site-packages\spyderlib\spyder.py", line 648, in setup
    from xy.config import DOC_PATH as xy_doc_path
  File "d:\Python26\lib\site-packages\xy\config.py", line 123, in \<module>
    DOC_PATH = REGXY['DocPath']
KeyError: 'DocPath'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=440_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-11-09T10:01:09Z_

This issue was closed by revision e156747e8e .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-24T07:36:51Z_

This issue was closed by revision e156747e8ebe .
