### ISSUE TITLE
Error while starting the Ipyhon console

### ISSUE THREAD

**Issue by ciornav** [spyder-ide/spyder#4413]
## Description

An error occurred while starting the kernel:

Error in sitecustomize; set PYTHONVERBOSE for traceback:
AttributeError: '_NamespacePath' object has no attribute 'sort'
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 227, in 
main()
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 200, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\ProgramData\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 24, in 
from IPython.core.shellapp import (
File "C:\Users\aa82758\AppData\Roaming\Python\Python36\site‑packages\IPython\core\shellapp.py", line 20, in 
from IPython.core import pylabtools
File "C:\Users\aa82758\AppData\Roaming\Python\Python36\site‑packages\IPython\__init__.py", line 49, in 
from .terminal.embed import embed
File "C:\Users\aa82758\AppData\Roaming\Python\Python36\site‑packages\IPython\terminal\embed.py", line 19, in 
from IPython.terminal.ipapp import load_default_config
File "C:\Users\aa82758\AppData\Roaming\Python\Python36\site‑packages\IPython\terminal\ipapp.py", line 31, in 
from IPython.core.shellapp import (
ImportError: cannot import name 'InteractiveShellApp'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
AttributeError: '_NamespacePath' object has no attribute 'sort'
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 227, in 
main()
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 200, in main
...

**What steps will reproduce the problem?**

1. Restart kernel
2. Restart spyder
3. Open a new Ipython console

**What is the expected output? What do you see instead?**
Normal Ipython console

**Please provide any additional information below**
Spyder  3.1.2 installed with Anaconda 3

## Version and main components

* Spyder Version: 3.1.2 
* Python Version: 3.6.0
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  None (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  None (NOK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
You have another Python version installed in

    C:\Users\aa82758\AppData\Roaming\Python\Python36

which is interfering with your main Anaconda installation. Please remove it to fix this error.

**Comment by ciornav** [comment]
Thank you!
