### ISSUE TITLE
QWebSettings.setFontFamily() has an invalid type

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#445]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-11-09T10:41:25Z_

http://groups.google.com/group/spyderlib/t/9ca46232ef4bc3f?hl=en Dear All,

I apologise if this is to do with my python install, but any
suggestions will be most appreciated.

I have just updated to spyder-2.0.0beta6b on a 32-bit openSuSE 11.1
machine. When I start spyder from the command line, the splash logo
appears, and the it crashes with the following

  File "/usr/local/lib/python2.6/site-packages/spyder-2.0.0beta6b-
py2.6.egg/spyderlib/spyder.py", line 1470, in main
    mainwindow = run_spyder(app, options)
  File "/usr/local/lib/python2.6/site-packages/spyder-2.0.0beta6b-
py2.6.egg/spyderlib/spyder.py", line 1407, in run_spyder
    main.setup()
  File "/usr/local/lib/python2.6/site-packages/spyder-2.0.0beta6b-
py2.6.egg/spyderlib/spyder.py", line 550, in setup
    self.inspector = ObjectInspector(self)
  File "/usr/local/lib/python2.6/site-packages/spyder-2.0.0beta6b-
py2.6.egg/spyderlib/plugins/inspector.py", line 114, in __init__
    self.rich_text.webview.set_font(self.get_plugin_font('rich_text'))
  File "/usr/local/lib/python2.6/site-packages/spyder-2.0.0beta6b-
py2.6.egg/spyderlib/widgets/browser.py", line 56, in set_font
    self.page().settings().setFontFamily(0, family) # Standard
TypeError: argument 1 of QWebSettings.setFontFamily() has an invalid
type

I can start spyder with the --light argument. I started spyder with
the --debug argument and the following was produced.

Start of MainWindow constructor
Initializing...
End of MainWindow constructor
*** Start of MainWindow setup ***
Loading object inspector...
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/site-packages/spyder-2.0.0beta6b-
py2.6.egg/spyderlib/spyder.py", line 1470, in
main
    mainwindow = run_spyder(app,
options)
  File "/usr/local/lib/python2.6/site-packages/spyder-2.0.0beta6b-
py2.6.egg/spyderlib/spyder.py", line 1407, in
run_spyder

main.setup()
  File "/usr/local/lib/python2.6/site-packages/spyder-2.0.0beta6b-
py2.6.egg/spyderlib/spyder.py", line 550, in
setup
    self.inspector =
ObjectInspector(self)
  File "/usr/local/lib/python2.6/site-packages/spyder-2.0.0beta6b-
py2.6.egg/spyderlib/plugins/inspector.py", line 114, in
__init__

self.rich_text.webview.set_font(self.get_plugin_font('rich_text'))
  File "/usr/local/lib/python2.6/site-packages/spyder-2.0.0beta6b-
py2.6.egg/spyderlib/widgets/browser.py", line 56, in
set_font
    self.page().settings().setFontFamily(0, family) #
Standard
TypeError: argument 1 of QWebSettings.setFontFamily() has an invalid
type
Traceback (most recent call
last):
  File "/usr/local/bin/spyder", line 5, in
\<module>
    pkg_resources.run_script('spyder==2.0.0beta6b',
'spyder')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 448,
in run_script
    self.require(requires)[0].run_script(script_name,
ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1166,
in run_script
    execfile(script_filename, namespace,
namespace)
  File "/usr/local/lib/python2.6/site-packages/spyder-2.0.0beta6b-
py2.6.egg/EGG-INFO/scripts/spyder", line 3, in
\<module>

spyder.main()
  File "/usr/local/lib/python2.6/site-packages/spyder-2.0.0beta6b-
py2.6.egg/spyderlib/spyder.py", line 1476, in main
    if mainwindow is None:
UnboundLocalError: local variable 'mainwindow' referenced before
assignment
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.6/site-packages/spyder-2.0.0beta6b-
py2.6.egg/spyderlib/spyder.py", line 942, in closing
    CONF.set('main', prefix+'size', (size.width(), size.height()))
AttributeError: 'NoneType' object has no attribute 'width'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.6/site-packages/spyder-2.0.0beta6b-
py2.6.egg/spyderlib/spyder.py", line 942, in closing
    CONF.set('main', prefix+'size', (size.width(), size.height()))
AttributeError: 'NoneType' object has no attribute 'width'

If you need any further information, then please let me know.

Peter

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=445_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-11-09T10:01:10Z_

This issue was closed by revision 7044d1e5d6 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-24T07:36:54Z_

This issue was closed by revision 7044d1e5d6b7 .
