### ISSUE TITLE
Strange raw_input problems

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#449]
_From [castillo...@gmail.com](https://code.google.com/u/112724398185925855351/) on 2010-11-12T11:58:21Z_

What steps will reproduce the problem?

 1. Define this class in a file:
class test:
    def Pause(self,s):
        raw_input(s)
    def Test(self):
        print 'this is a test'
        self.Pause('press enter to continue')
        print '2nd part'
        self.Pause('press enter to continue')
        print '3rd part'
        self.Pause('press enter to continue')

2. Write the following in another file:
from test2Class import * #test2Class is the name of the file where the test class is defined

t=test()
t.Test()

3. Run (F9) the 2nd file What is the expected output? What do you see instead? Expected output (my comments between []'s):
this is a test
press enter to continue [pause here, until I press enter]
2nd part
press enter to continue [pause here, until I press enter]
3rd part
press enter to continue [pause here, until I press enter]

Actual output:
this is a test [pause here, until I press enter]

press enter to continueTraceback (most recent call last):
  File "<executed_script>", line 11, in \<module>
  File "test2Class.py", line 13, in Test
    self.Pause('press enter to continue')
  File "test2Class.py", line 10, in Pause
    raw_input(s)
EOFError: EOF when reading a line What version of the product are you using? On what operating system? spyderlib 1.1.8 in Ubuntu 10.10 x64. 

Please provide any additional information below

. If I define the class and use it in one file instead of two (joining the two aforementioned files), I get the expected output.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=449_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-05-16T01:17:20Z_

Please update to Spyder v2.x as the v1.x branch is no longer maintained.

Here is the official Debian package: http://packages.debian.org/fr/sid/spyder

**Status:** WontFix  
  **Labels:** Cat-Console
