### ISSUE TITLE
Spyder iPython console shows "An error occurred while starting the kernel"

### ISSUE THREAD

**Issue by aaronpoh23** [spyder-ide/spyder#4514]
## Description of your problem

1.  This problem occurred after I changed the default python interpreter from 3.6 to 3.5.3 under the tensorflow environment.
2.  After using conda to install ipykernel, it showed the following error:

*********ERROR MESSAGE******************************************************************************
An error ocurred while starting the kernel

Traceback (most recent call last):
File "C:\Users\user\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 231, in 
main()
File "C:\Users\user\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 204, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\user\Anaconda3\lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\user\Anaconda3\lib\site‑packages\ipykernel\connect.py", line 18, in 
import jupyter_client
File "C:\Users\user\Anaconda3\lib\site‑packages\jupyter_client\__init__.py", line 4, in 
from .connect import *
File "C:\Users\user\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 21, in 
import zmq
File "C:\Users\user\Anaconda3\lib\site‑packages\zmq\__init__.py", line 34, in 
from zmq import backend
File "C:\Users\user\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 40, in 
reraise(*exc_info)
File "C:\Users\user\Anaconda3\lib\site‑packages\zmq\utils\sixcerpt.py", line 34, in reraise
raise value
File "C:\Users\user\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 27, in 
_ns = select_backend(first)
File "C:\Users\user\Anaconda3\lib\site‑packages\zmq\backend\select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "C:\Users\user\Anaconda3\lib\site‑packages\zmq\backend\cython\__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'

**********************************************************************************************************

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: root: 3.6, tensorflow: 3.5.3
* Qt Version:
* PyQt Version:
* Operating system: Windows 10

This problem occurred after my numerous attempts to import tensorflow on Spyder iPython. It works fine on the terminal, but not on Spyder iPython.

Kindly help me with this issue, or better yet, kindly teach me how to set up the appropriate environment to use tensorflow on Spyder iPython.

Thank You!!

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
The error message you're reporting seems to occur in your root environment, not in your `tensorflow` one. So I'm a bit confused by it.

**Comment by aaronpoh23** [comment]
thank you for your prompt reply! 
I actually managed to fix it (luckily) by using conda to install spyder in the tensorflow environment. 
thanks again!

**Comment by ccordoba12** [comment]
Ok, no problem. Glad to hear things are working for you now.

**Comment by F-Gomes** [comment]
aaronpoh23, how did you fix it? I installed spyder in the tensorflow environment and still get the following error:

![image](https://user-images.githubusercontent.com/32467740/31274563-c953cdc2-aa69-11e7-8148-aaee8df444ee.png)

**Comment by hcloud00** [comment]
I am having the same issue what steps did you take to fix this?

**Comment by natnij** [comment]
I am having the same issue and installing spyder in either root or the new environment didn't help. what did you do? thanks!

**Comment by pawanvirsingh** [comment]
i am facing the same problem when I added a new python path (anaconda version  )

**Comment by pawanvirsingh** [comment]
Traceback (most recent call last):
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 231, in 
main()
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 204, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/lib/python3/dist‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/usr/lib/python3/dist‑packages/ipykernel/connect.py", line 18, in 
import jupyter_client
File "/usr/lib/python3/dist‑packages/jupyter_client/__init__.py", line 4, in 
from .connect import *
File "/usr/lib/python3/dist‑packages/jupyter_client/connect.py", line 22, in 
import zmq
File "/usr/lib/python3/dist‑packages/zmq/__init__.py", line 34, in 
from zmq import backend
File "/usr/lib/python3/dist‑packages/zmq/backend/__init__.py", line 40, in 
reraise(*exc_info)
File "/usr/lib/python3/dist‑packages/zmq/utils/sixcerpt.py", line 34, in reraise
raise value
File "/usr/lib/python3/dist‑packages/zmq/backend/__init__.py", line 27, in 
_ns = select_backend(first)
File "/usr/lib/python3/dist‑packages/zmq/backend/select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "/usr/lib/python3/dist‑packages/zmq/backend/cython/__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
Traceback (most recent call last):
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 231, in 
main()
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 204, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/lib/python3/dist‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/usr/lib/python3/dist‑packages/ipykernel/connect.py", line 18, in 
import jupyter_client
File "/usr/lib/python3/dist‑packages/jupyter_client/__init__.py", line 4, in 
from .connect import *
File "/usr/lib/python3/dist‑packages/jupyter_client/connect.py", line 22, in 
import zmq
File "/usr/lib/python3/dist‑packages/zmq/__init__.py", line 34, in 
from zmq import backend
File "/usr/lib/python3/dist‑packages/zmq/backend/__init__.py", line 40, in 
reraise(*exc_info)
File "/usr/lib/python3/dist‑packages/zmq/utils/sixcerpt.py", line 34, in reraise
raise value
File "/usr/lib/python3/dist‑packages/zmq/backend/__init__.py", line 27, in 
_ns = select_backend(first)
File "/usr/lib/python3/dist‑packages/zmq/backend/select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "/usr/lib/python3/dist‑packages/zmq/backend/cython/__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
Traceback (most recent call last):
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 231, in 
main()
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 204, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/lib/python3/dist‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/usr/lib/python3/dist‑packages/ipykernel/connect.py", line 18, in 
import jupyter_client
File "/usr/lib/python3/dist‑packages/jupyter_client/__init__.py", line 4, in 
from .connect import *
File "/usr/lib/python3/dist‑packages/jupyter_client/connect.py", line 22, in 
import zmq
File "/usr/lib/python3/dist‑packages/zmq/__init__.py", line 34, in 
from zmq import backend
File "/usr/lib/python3/dist‑packages/zmq/backend/__init__.py", line 40, in 
reraise(*exc_info)
File "/usr/lib/python3/dist‑packages/zmq/utils/sixcerpt.py", line 34, in reraise
raise value
File "/usr/lib/python3/dist‑packages/zmq/backend/__init__.py", line 27, in 
_ns = select_backend(first)
File "/usr/lib/python3/dist‑packages/zmq/backend/select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "/usr/lib/python3/dist‑packages/zmq/backend/cython/__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
Traceback (most recent call last):
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 231, in 
main()
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 204, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/lib/python3/dist‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/usr/lib/python3/dist‑packages/ipykernel/connect.py", line 18, in 
import jupyter_client
File "/usr/lib/python3/dist‑packages/jupyter_client/__init__.py", line 4, in 
from .connect import *
File "/usr/lib/python3/dist‑packages/jupyter_client/connect.py", line 22, in 
import zmq
File "/usr/lib/python3/dist‑packages/zmq/__init__.py", line 34, in 
from zmq import backend
File "/usr/lib/python3/dist‑packages/zmq/backend/__init__.py", line 40, in 
reraise(*exc_info)
File "/usr/lib/python3/dist‑packages/zmq/utils/sixcerpt.py", line 34, in reraise
raise value
File "/usr/lib/python3/dist‑packages/zmq/backend/__init__.py", line 27, in 
_ns = select_backend(first)
File "/usr/lib/python3/dist‑packages/zmq/backend/select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "/usr/lib/python3/dist‑packages/zmq/backend/cython/__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
Traceback (most recent call last):
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 231, in 
main()
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 204, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/lib/python3/dist‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/usr/lib/python3/dist‑packages/ipykernel/connect.py", line 18, in 
import jupyter_client
File "/usr/lib/python3/dist‑packages/jupyter_client/__init__.py", line 4, in 
from .connect import *
File "/usr/lib/python3/dist‑packages/jupyter_client/connect.py", line 22, in 
import zmq
File "/usr/lib/python3/dist‑packages/zmq/__init__.py", line 34, in 
from zmq import backend
File "/usr/lib/python3/dist‑packages/zmq/backend/__init__.py", line 40, in 
reraise(*exc_info)
File "/usr/lib/python3/dist‑packages/zmq/utils/sixcerpt.py", line 34, in reraise
raise value
File "/usr/lib/python3/dist‑packages/zmq/backend/__init__.py", line 27, in 
_ns = select_backend(first)
File "/usr/lib/python3/dist‑packages/zmq/backend/select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "/usr/lib/python3/dist‑packages/zmq/backend/cython/__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'

**Comment by ccordoba12** [comment]
@pawanvirsingh, you *can't* mix two different Python versions (Anaconda and your System Python) by the adding one to the PYTHONPATH of the other.

That's because they are compiled under different circumstances and so they are binary incompatible.

**Comment by AltairCA** [comment]
In the spyder Goto tools, then click on "PYTHONPATH manager" give your Environment's python path Normally stored in C:\User\{yourComputerAccountUserName}\Anaconda3\envs\YourEnvironment

and untick other paths if there any in PYTHONPATH manager

**Comment by gaurkuber** [comment]
I did the following to resolve this. Not sure which one clicked but here's a comprehensive listing 

1. conda install spyder   ( in my py35 virtual env )
2. set PYTHONPATH as suggested by AltairCA above

      C:/Users/<userName>/AppData/Local/conda/conda/envs/py35
3. set the python interpreter in spyder (Tools>Preferences>Python Interpreter) to - 

C:/Users/<userName>/AppData/Local/conda/conda/envs/py35/python.exe

After this the IPython console came up fine.

**Comment by sas1an** [comment]
Python 3.6.7 |Anaconda, Inc.| (default, Dec 10 2018, 20:35:02) [MSC v.1915 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.2.0 -- An enhanced Interactive Python.

NOTE: The following error appeared when setting your Matplotlib backend

Traceback (most recent call last):
  File "C:\Users\fghjk\Anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 475, in _set_mpl_backend
    get_ipython().run_line_magic(magic, backend)
  File "C:\Users\fghjk\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2287, in run_line_magic
    result = fn(*args,**kwargs)
  File "<decorator-gen-108>", line 2, in matplotlib
  File "C:\Users\fghjk\Anaconda3\lib\site-packages\IPython\core\magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "C:\Users\fghjk\Anaconda3\lib\site-packages\IPython\core\magics\pylab.py", line 99, in matplotlib
    gui, backend = self.shell.enable_matplotlib(args.gui)
  File "C:\Users\fghjk\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3355, in enable_matplotlib
    pt.activate_matplotlib(backend)
  File "C:\Users\fghjk\Anaconda3\lib\site-packages\IPython\core\pylabtools.py", line 313, in activate_matplotlib
    import matplotlib.pyplot
  File "C:\Users\fghjk\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 31, in <module>
    import matplotlib.colorbar
  File "C:\Users\fghjk\Anaconda3\lib\site-packages\matplotlib\colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
  File "C:\Users\fghjk\Anaconda3\lib\site-packages\matplotlib\artist.py", line 16, in <module>
    from .path import Path
  File "C:\Users\fghjk\Anaconda3\lib\site-packages\matplotlib\path.py", line 21, in <module>
    from . import _path, rcParams
ImportError: cannot import name '_path'

ImportError: cannot import name '_path' is causing problem as shown above before running on a spider run as an anaconda. What should I do?

**Comment by wangbinhu** [comment]
when run python coding :
![image](https://user-images.githubusercontent.com/45450311/51242049-05987600-19ba-11e9-93a5-83c0a0f1ec6d.png)
coding:
list = [5,6,3,8,6,9,4,3,2,1,7]   #要排序的列表

def quickly_sort(list):
    if len(list) < 2:
        return list
    else:
        jizhunshu = list[0]  #以每一次列表的第一个数为基准数
        small_list = [ i < jizhunshu for i in list]  #产生一个比基准数小的列表
        big_list = [i > jizhunshu for i in list]    #产生一个比基准数大的表
        sort_list = quickly_sort(small_list) + [jizhunshu] + quickly_sort(big_list)          #注意基准数必须加[],使其还原为list
        return sort_list

quickly_sort(list)


how to slove ?,thank you !
