### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt4.QtWebKit'

### ISSUE THREAD

**Issue by JohnRobson** [spyder-ide/spyder#4564]
I installed qtpy, qtawesome, qt5-webkit; but I got this error:

Traceback (most recent call last):
  File "/usr/bin/spyder3", line 3, in <module>
    start.main()
  File "/usr/lib/python3.6/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/usr/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/usr/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 31, in <module>
    from PyQt4.QtWebKit import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt4.QtWebKit'

I'm using Archlinux

**Comment by JohnRobson** [comment]
https://bugs.archlinux.org/task/54277

Move to: https://github.com/spyder-ide/spyder/issues/4552#issuecomment-305976379
