### ISSUE TITLE
Find in Files not working

### ISSUE THREAD

**Issue by mat2py** [spyder-ide/spyder#4576]
## Description of your problem

**What steps will reproduce the problem?**

1. Search -> find in files
2. put in a word and search
3. fails

**What is the expected output? What do you see instead?**
The search

**Please provide any additional information below**
Traceback:
```
Traceback (most recent call last):
  File "/home/mplain/anaconda2/envs/rootclone2/lib/python2.7/site-packages/spyder/widgets/findinfiles.py", line 150, in run
    ok = self.find_files_in_path(self.rootpath)
  File "/home/mplain/anaconda2/envs/rootclone2/lib/python2.7/site-packages/spyder/widgets/findinfiles.py", line 217, in find_files_in_path
    for path, dirs, files in os.walk(path):
  File "/home/mplain/anaconda2/envs/rootclone2/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/home/mplain/anaconda2/envs/rootclone2/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/home/mplain/anaconda2/envs/rootclone2/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/home/mplain/anaconda2/envs/rootclone2/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/home/mplain/anaconda2/envs/rootclone2/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 25: ordinal not in range(128)
```

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 2.7.13 64 bits
* Qt Version: 5.6.2
* PyQt Version: PyQt5 5.6 on Linux
* Operating system: Ubuntu 16.04 LTS

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.9.0     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.2.1 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.5 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. This was fixed in PR #4056, and it'll be part of Spyder 3.2.
