### ISSUE TITLE
Spyder 2.0.0rc1 IPython console fails with exception caused by sys.platform = 'fake' in spiderlib/widgets/externalshell/sptartup.py on Windows XP

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#460]
_From [todor.bu...@gmail.com](https://code.google.com/u/113727712193522578806/) on 2010-11-20T10:29:31Z_

What steps will reproduce the problem?

 1. Install spyder 2.0.0.rc1 via easy_install on Windows XP SP3 system.
2. Start Spyder by clicking on spyder.pyw in C:\Python27\Scrypts\spyder.pyw
3. The IPython console throws exception:

Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\spyder-2.0.0rc1-py2.7.egg\spyderlib\widgets\externalshell\startup.py", line 163, in \<module>
    import IPython.Shell
  File "c:\Python27\lib\site-packages\ipython-0.10-py2.7-win32.egg\IPython\__init__.py", line 58, in \<module>
    __import__(name,glob,loc,[])
  File "c:\Python27\lib\site-packages\ipython-0.10-py2.7-win32.egg\IPython\ipstruct.py", line 17, in \<module>
    from IPython.genutils import list2dict2
  File "c:\Python27\lib\site-packages\ipython-0.10-py2.7-win32.egg\IPython\genutils.py", line 28, in \<module>
    import subprocess
  File "c:\Python27\lib\subprocess.py", line 432, in \<module>
    import fcntl
ImportError: No module named fcntl What is the expected output? What do you see instead? IPython console prompt should be shown. An exception is thrown instead. What version of the product are you using? On what operating system? OS: Windows XP SP3
Python: 2.7.0
PyQT: 4.7.4
QT: 4.6.2
IPython: 0.10 

Please provide any additional information below

. After commenting the following line in C:\Python27\Lib\site-packages\spyder-2.0.0rc1-py2.7.egg\spyderlib\widgets\externalshell\startup.py :

Line 162: sys.platform = 'fake'

the problem was resolved. The issue is that when importing subprocess module, the check in file subprocess.py on line 392: 
mswindows = (sys.platform == "win32")
resolves to False causing further down the file an attempt to import module fcntl which is Linux/Unix only. This of course causes the above exception on Windows.

Changing sys.platform on the fly seems to be a fragile solution that should be avoided and replaced with better alternative. For now, commenting the line on Windows platform resolves the problem.

**Attachment:** [startup.py](http://code.google.com/p/spyderlib/issues/detail?id=460)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=460_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-11-21T06:10:48Z_

This issue was closed by revision 964599a03b .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-11-21T06:14:28Z_

Note: commenting line 162 in startup.py was not as solution as IPython I/O streams won't work this way (i.e. no error output... which is kind of a problem!).

The old patch was very ugly, I do agree. But it was working on most machines until now.

Your bug report made me think of another way to do this monkey-patch. After some thinking, the solution implemented now should be working on all Windows machines.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-24T07:37:23Z_

This issue was closed by revision 964599a03b66 .
