### ISSUE TITLE
Spyder3 crash on startup, "ValueError:Dependency has already been registred: pandas"

### ISSUE THREAD

**Issue by adamlek** [spyder-ide/spyder#4675]
## Description of your problem
Spyder3 crashes when started. 

**What steps will reproduce the problem?**
Not sure, unclear what was done before it broke.

**What is the expected output? What do you see instead?**
Expected output: Spyder3 starts

Output: When starting spyder3 from the terminal, the following message is displayed:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spyderlib/spyder.py", line 2336, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python3/dist-packages/spyderlib/spyder.py", line 2220, in run_spyder
    main.setup()
  File "/usr/lib/python3/dist-packages/spyderlib/spyder.py", line 744, in setup
    from spyderlib.plugins.console import Console
  File "/usr/lib/python3/dist-packages/spyderlib/plugins/console.py", line 30, in <module>
    from spyderlib.utils.environ import EnvDialog
  File "/usr/lib/python3/dist-packages/spyderlib/utils/environ.py", line 17, in <module>
    from spyderlib.widgets.dicteditor import DictEditor
  File "/usr/lib/python3/dist-packages/spyderlib/widgets/dicteditor.py", line 39, in <module>
    from spyderlib.widgets.dicteditorutils import (sort_against, get_size,
  File "/usr/lib/python3/dist-packages/spyderlib/widgets/dicteditorutils.py", line 61, in <module>
    required_version=PANDAS_REQVER)
  File "/usr/lib/python3/dist-packages/spyderlib/dependencies.py", line 68, in add
    % modname)
ValueError: Dependency has already been registered: pandas

**Please provide any additional information below**
spyder3 crashes when launched from terminal (and menu) when using "spyder3", however when starting spyder with "spyder" it starts. 

Have tried: 
* reinstall spyder3 (sudo apt-get install spyder3)
* reinstall pandas
* spyder3 --reset

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.6.1
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Ubuntu 15.04 XFCE

## Dependencies

jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.2.2 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

Not sure what the issue is, any help is appriciated (best IDE). 
Thanks in advance

**Comment by ccordoba12** [comment]
It seems you installed Spyder with Anaconda and apt-get. Please only use one (preferably Anaconda's Spyder because the apt-get one is very old).
