### ISSUE TITLE
Cant' build sphinx documentation

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#469]
_From [miniw...@gmail.com](https://code.google.com/u/102264527247906612870/) on 2010-11-26T05:06:18Z_

With Spyder 2.0.0rc3 and with sphinx 1.0.5 spyder fail to duild at documentation steep because of ascii/utf8 error.

When performing "python setup.py install" i have the following traceback :

_____________________________________________
running install
running build
running build_py
running build_scripts
running build_doc
Running Sphinx v1.0.5
WARNING: the config value '__file__' is set to a string with non-ASCII characters; this can lead to Unicode errors occurring. Please use Unicode strings, e.g. u"Content".
loading pickled environment... done
building [html]: targets for 2 source files that are out of date
updating environment: Traceback (most recent call last):
  File "setup.py", line 97, in \<module>
    cmdclass=cmdclass)
  File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.6/distutils/command/install.py", line 582, in run
    self.run_command('build')
  File "/usr/lib64/python2.6/distutils/cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.6/distutils/command/build.py", line 134, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python2.6/distutils/cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "setup.py", line 51, in run
    setup_command.BuildDoc.run(self)
  File "/home/titi/Developpement/virtualenvs/spyder/lib/python2.6/site-packages/sphinx/setup_command.py", line 143, in run
    app.builder.build_update()
  File "/home/titi/Developpement/virtualenvs/spyder/lib/python2.6/site-packages/sphinx/builders/__init__.py", line 198, in build_update
    'out of date' &#37; len(to_build))
  File "/home/titi/Developpement/virtualenvs/spyder/lib/python2.6/site-packages/sphinx/builders/__init__.py", line 215, in build
    self.doctreedir, self.app)
  File "/home/titi/Developpement/virtualenvs/spyder/lib/python2.6/site-packages/sphinx/environment.py", line 488, in update
    added, changed, removed = self.get_outdated_files(config_changed)
  File "/home/titi/Developpement/virtualenvs/spyder/lib/python2.6/site-packages/sphinx/environment.py", line 430, in get_outdated_files
    newmtime = path.getmtime(self.doc2path(docname))
  File "/home/titi/Developpement/virtualenvs/spyder/lib/python2.6/site-packages/sphinx/environment.py", line 385, in doc2path
    docname.replace(SEP, path.sep)) + suffix
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)

This is probably related to this warning :
WARNING: the config value '__file__' is set to a string with non-ASCII characters; this can lead to Unicode errors occurring. Please use Unicode strings, e.g. u"Content".

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=469_

**Comment by spyder-issues-migrator** [comment]
_From [miniw...@gmail.com](https://code.google.com/u/102264527247906612870/) on 2010-11-26T02:14:38Z_

Stragely, if y try to install spyder with pip i do not have this error, and spyder install well

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-11-27T06:22:25Z_

I've done some research about this warning. The '__file__' value is basically the full path name of the Sphinx configuration script ('conf.py').
So the problem is probably on your side: check the full path where you have extracted Spyder source package, because this error means that this full path contains non-ascii characters.

**Status:** Done
