### ISSUE TITLE
spyder3 will not start

### ISSUE THREAD

**Issue by ulfmichel** [spyder-ide/spyder#4703]
## Description of your problem

**What steps will reproduce the problem?**

1. spyder3
2. 
3. 

**What is the expected output? 
spyder3 would start

What do you see instead?**
Instead it outputs the following messages:

Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2998, in main
mainwindow = run_spyder(app, options, args)
File "/usr/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2902, in run_spyder
main.setup()
File "/usr/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 864, in setup
self.projects = Projects(self)
File "/usr/lib/python3.6/site-packages/spyder/plugins/projects.py", line 71, in init
self.setup_project(self.get_active_project_path())
File "/usr/lib/python3.6/site-packages/spyder/widgets/projects/explorer.py", line 209, in setup_project
show_all=self.show_all)
File "/usr/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 193, in setup
self.common_actions = self.setup_common_actions()
File "/usr/lib/python3.6/site-packages/spyder/widgets/projects/explorer.py", line 53, in setup_common_actions
self.toggle_hscrollbar(self.show_hscrollbar)
File "/usr/lib/python3.6/site-packages/spyder/widgets/projects/explorer.py", line 68, in toggle_hscrollbar
self.header().setResizeMode(QHeaderView.ResizeToContents)
File "/usr/lib/python3.6/site-packages/qtpy/_patch/qheaderview.py", line 83, in setResizeMode
raise Exception('setResizeMode is only available in Qt4. Use '
Exception: setResizeMode is only available in Qt4. Use setSectionResizeMode instead.
Speicherzugriffsfehler (Speicherabzug geschrieben)
**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.0.0-1.3
* Python Version: 3.6.1-180.1
* Qt Version: 4.8.7
* PyQt Version: 4.12-6.1, 5.8.2-3.1 
* Operating system: OpenSuse Tumbleweed (spyder3 works well with 42.2)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

I don't understand this. Which Help?

**Comment by ulfmichel** [comment]
spyder3
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2998, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2902, in run_spyder
    main.setup()
  File "/usr/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 864, in setup
    self.projects = Projects(self)
  File "/usr/lib/python3.6/site-packages/spyder/plugins/projects.py", line 71, in __init__
    self.setup_project(self.get_active_project_path())
  File "/usr/lib/python3.6/site-packages/spyder/widgets/projects/explorer.py", line 209, in setup_project
    show_all=self.show_all)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 193, in setup
    self.common_actions = self.setup_common_actions()
  File "/usr/lib/python3.6/site-packages/spyder/widgets/projects/explorer.py", line 53, in setup_common_actions
    self.toggle_hscrollbar(self.show_hscrollbar)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/projects/explorer.py", line 68, in toggle_hscrollbar
    self.header().setResizeMode(QHeaderView.ResizeToContents)
  File "/usr/lib/python3.6/site-packages/qtpy/_patch/qheaderview.py", line 83, in setResizeMode
    raise Exception('setResizeMode is only available in Qt4. Use '
Exception: setResizeMode is only available in Qt4. Use setSectionResizeMode instead.
Speicherzugriffsfehler (Speicherabzug geschrieben)

**Comment by ccordoba12** [comment]
Please report this with the OpenSuse maintainers. I think it's an issue with Spyder using a recent version of qtpy.

**Comment by rlaverde** [comment]
This is the same as #3943, that was solved in Spyder3.1

**Comment by ulfmichel** [comment]
Thank you very much for this suggestion.
