### ISSUE TITLE
ValueError: API 'QString' has already been set to version 1

### ISSUE THREAD

**Issue by wtliao** [spyder-ide/spyder#4727]
## Description of your problem
When I launched spyder in terminal with command line: spyder
there war following error

Traceback (most recent call last):
  File "/home/xx/anaconda2/bin/spyder", line 3, in <module>
    start_app.main()
  File "/home/xx/anaconda2/lib/python2.7/site-packages/spyderlib/start_app.py", line 114, in main
    from spyderlib import spyder
  File "/home/xx/anaconda2/lib/python2.7/site-packages/spyderlib/spyder.py", line 48, in <module>
    requirements.check_qt()
  File "/home/xx/anaconda2/lib/python2.7/site-packages/spyderlib/requirements.py", line 40, in check_qt
    from spyderlib import qt
  File "/home/xx/anaconda2/lib/python2.7/site-packages/spyderlib/qt/__init__.py", line 22, in <module>
    sip.setapi('QString', 2)
ValueError: API 'QString' has already been set to version 1

If I lauched from the start menue, no respond (the spyder icon exists)

**Please provide any additional information below**
I have tried to re-installed spyder. It doesn't work

I have no idea why there exist two qtconsole as follows
qtconsole                 4.3.0                     <pip>
qtconsole                 4.1.1                    py27_0 

The anaconda-navigator (1.2.3) doesn't work either.
Traceback (most recent call last):
  File "/home/xx/anaconda2/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/home/xx/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 70, in main
    window = run_app(splash)
  File "/home/xx/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 38, in run_app
    window = MainWindow(splash=splash)
  File "/home/xx/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 169, in __init__
    self.environments_tab = EnvironmentsTab(parent=self)
  File "/home/xx/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/tabs/environments.py", line 120, in __init__
    data_directory=CHANNELS_PATH,
  File "/home/liao/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/manager/packages.py", line 266, in __init__
    self.table = TableCondaPackages(self)
  File "/home/xx/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/manager/table.py", line 155, in __init__
    self._hheader.setResizeMode(self._hheader.Fixed)
  File "/home/xx/anaconda2/lib/python2.7/site-packages/qtpy/_patch/qheaderview.py", line 83, in setResizeMode
    raise Exception('setResizeMode is only available in Qt4. Use '
Exception: setResizeMode is only available in Qt4. Use setSectionResizeMode instead.

However, my Qt is 4 not 5.

## Versions and main components

* Spyder Version: 2.3.8-py27_1  anaconda
* Python Version: 2.7
* Qt Version: 4.8.7
* PyQt Version:     4.11.4                   py27_1
* Operating system: openSUSE 13.2 (Harlequin) (x86_64)

It worked in the morning, but not since this afternoon. What I have changed in the anaconda is that I installed package nb_conda.

This problem make me crazy now....

Thanks so much if anyone help

**Comment by ccordoba12** [comment]
Please update Spyder. You're working with Spyder 2.3, which is not supported anymore.

**Comment by wtliao** [comment]
thanks for your reply. I have tried to upgrade the spyder to 3.1.4 and other dependecies to (automatically)



    astroid:           1.4.9-py27_0           
    chardet:           3.0.4-py27_0           
    isort:             4.2.15-py27_0          
    lazy-object-proxy: 1.3.1-py27_0           
    numpydoc:          0.6.0-py27_0           
    pylint:            1.6.4-py27_1           
    qtawesome:         0.4.4-py27_0           
    spyder:            3.1.4-py27_0           
    wrapt:             1.10.10-py27_0    
qtconsole:         4.1.1-py27_0            --> 4.2.1-py27_0 

But the problem is still there. :(

**Comment by ccordoba12** [comment]
Please run

    conda update qtpy

to see if that fixes your problem.

**Comment by wtliao** [comment]
I ran "conda update qtpy" and got

Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/liao/anaconda2:
#
qtpy                      1.2.1                    py27_0  

but the problem is not fixed :(

**Comment by ccordoba12** [comment]
I don't know what could be the cause then, sorry.

**Comment by wtliao** [comment]
As I guess, the problem is the API Qt being changed to version 1 by some package. I read the __init__ file in spyder and found that spyder only supports for Qt v2 (right?). Is there anyway to change the Qt to version2? Thanks

**Comment by jitseniesen** [comment]
@wtliao That's right, spyder needs Qt API v2, so you need to find out which package sets it to v1 before Syder tries to set it to v2. 

It may help to update pyqt as well (which is not the same as qtpy!).

If it's possible for you, you can side step the problem by upgrading qt and pyqt to version 5, because that version does not have the old Qt API v1 available anymore.

**Comment by wtliao** [comment]
@jitseniesen Thanks so much. My problem is fixed. I upgrade all qt and pyqt to v5, also in the env.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
