### ISSUE TITLE
OK Button does not always dismiss Preferences Dialog

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#474]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2010-11-29T12:08:43Z_

Similar to `#462` 

What steps will reproduce the problem?

 Not sure how to reproduce. I was just browsing the preferences dialog and hit OK to dismiss it. What version of the product are you using? On what operating system? spyder 2.0.0rc3, python 2.6.1, Windows XP SP3 

Please provide any additional information below

. Traceback info from Internal Console:
\>>> Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\spyderlib\widgets\editor.py", line 1356, in _refresh_outlineexplorer
    update=update)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\editortools.py", line 577, in set_current_editor
    self.treewidget.set_current_editor(editor, fname, update)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\editortools.py", line 308, in set_current_editor
    self.populate_branch(editor, item, tree_cache)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\editortools.py", line 436, in populate_branch
    item = TreeItem(data.text, line_nb, parent, preceding)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\editortools.py", line 123, in __init__
    while preceding.parent() is not parent:
AttributeError: 'NoneType' object has no attribute 'parent'
Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\spyderlib\plugins\configdialog.py", line 146, in button_clicked
    configpage.apply_changes()
  File "C:\Python26\lib\site-packages\spyderlib\plugins\configdialog.py", line 67, in apply_changes
    self.apply_callback()
  File "C:\Python26\lib\site-packages\spyderlib\plugins\configdialog.py", line 169, in \<lambda>
    self.apply_settings(self.changed_options))
  File "C:\Python26\lib\site-packages\spyderlib\plugins\editor.py", line 1837, in apply_plugin_settings
    self.outlineexplorer.update()
  File "C:\Python26\lib\site-packages\spyderlib\widgets\editortools.py", line 595, in update
    self.treewidget.update_all()
  File "C:\Python26\lib\site-packages\spyderlib\widgets\editortools.py", line 339, in update_all
    self.populate_branch(editor, item, tree_cache)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\editortools.py", line 436, in populate_branch
    item = TreeItem(data.text, line_nb, parent, preceding)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\editortools.py", line 123, in __init__
    while preceding.parent() is not parent:
AttributeError: 'NoneType' object has no attribute 'parent'
Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\spyderlib\plugins\configdialog.py", line 137, in accept
    configpage.apply_changes()
  File "C:\Python26\lib\site-packages\spyderlib\plugins\configdialog.py", line 67, in apply_changes
    self.apply_callback()
  File "C:\Python26\lib\site-packages\spyderlib\plugins\configdialog.py", line 169, in \<lambda>
    self.apply_settings(self.changed_options))
  File "C:\Python26\lib\site-packages\spyderlib\plugins\editor.py", line 1837, in apply_plugin_settings
    self.outlineexplorer.update()
  File "C:\Python26\lib\site-packages\spyderlib\widgets\editortools.py", line 595, in update
    self.treewidget.update_all()
  File "C:\Python26\lib\site-packages\spyderlib\widgets\editortools.py", line 339, in update_all
    self.populate_branch(editor, item, tree_cache)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\editortools.py", line 436, in populate_branch
    item = TreeItem(data.text, line_nb, parent, preceding)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\editortools.py", line 123, in __init__
    while preceding.parent() is not parent:
AttributeError: 'NoneType' object has no attribute 'parent'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=474_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-11-29T23:11:45Z_

**Status:** Fixed
