### ISSUE TITLE
Switching from editor to notebook - ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by dataenthusiast** [spyder-ide/spyder#4780]
## Description of your problem

**What steps will reproduce the problem?**

1. Initial Install / Never worked before
2. Open spyder, click on new file (its currently in editor mode), then click notebook tab 
3. Nothing happens for about 10-15 secs, then get error popup (see below)

**What is the expected output? What do you see instead?**
Switches to notebook as expected 

**Please provide any additional information below**
Error:

  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

Traceback (most recent call last):
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\http\client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\http\client.py", line 1151, in _send_request
    self.endheaders(body)
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\http\client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\http\client.py", line 934, in _send_output
    self.send(msg)
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\http\client.py", line 877, in send
    self.connect()
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\urllib3\connection.py", line 166, in connect
    conn = self._new_conn()
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000187740B3048>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

Traceback (most recent call last):
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /api/sessions?token=28748a150ad772aefeede535ba84ca6576eefafbecd851cc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000187740B3048>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

Traceback (most recent call last):
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder_notebook-0.1.0.dev0-py3.5.egg\spyder_notebook\notebookplugin.py", line 350, in close_client
    client.shutdown_kernel()
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder_notebook-0.1.0.dev0-py3.5.egg\spyder_notebook\widgets\client.py", line 229, in shutdown_kernel
    kernel_id = self.get_kernel_id()
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder_notebook-0.1.0.dev0-py3.5.egg\spyder_notebook\widgets\client.py", line 214, in get_kernel_id
    sessions_req = requests.get(sessions_url).content.decode()
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\[username]\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /api/sessions?token=28748a150ad772aefeede535ba84ca6576eefafbecd851cc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000187740B3048>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

## Versions and main components

* Spyder Version: 4.0.0.dev0
* Python Version: 3.5.2 64 bit
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.24.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
I think your title says it all

> ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

It seems your firewall/antivirus is blocking network connections and so the notebook can't start. Please try to deactivate them for a while and try again.

I'm closing this issue because there's nothing we can do about it in Spyder, sorry.

**Comment by ehiverson** [comment]
If the firewall/antivirus is not causing this (I've turned it completely off), what else might it be? 
After I updated spyder a couple weeks ago, I started running into this - jupyter notebook not opening with the ConnectionRefusedError. Oddly, if I restarted my computer, and opened up spyder again, it worked. Is that a clue?
