### ISSUE TITLE
Cannot run Spyder any more

### ISSUE THREAD

**Issue by Strong-Curious** [spyder-ide/spyder#4790]
## Description of your problem

Spyder wont lunch!

**What steps will reproduce the problem?**

When I'm lunching Spyder via cmd (Windows 10), i'm getting:

`Traceback (most recent call last):
  File "D:\Anaconda3\Scripts\spyder-script.py", line 2, in <module>
    start_app.main()
  File "D:\Anaconda3\lib\site-packages\spyderlib\start_app.py", line 114, in main
    from spyderlib import spyder
  File "D:\Anaconda3\lib\site-packages\spyderlib\spyder.py", line 155, in <module>
    from spyderlib.utils.environ import WinUserEnvDialog
  File "D:\Anaconda3\lib\site-packages\spyderlib\utils\environ.py", line 17, in <module>
    from spyderlib.widgets.dicteditor import DictEditor
  File "D:\Anaconda3\lib\site-packages\spyderlib\widgets\dicteditor.py", line 39, in <module>
    from spyderlib.widgets.dicteditorutils import (sort_against, get_size,
  File "D:\Anaconda3\lib\site-packages\spyderlib\widgets\dicteditorutils.py", line 78, in <module>
    import bs4
  File "D:\Anaconda3\lib\site-packages\bs4\__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "D:\Anaconda3\lib\site-packages\bs4\builder\__init__.py", line 314, in <module>
    from . import _html5lib
  File "D:\Anaconda3\lib\site-packages\bs4\builder\_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'`

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

I've tried to upgrade the version and reset but the problem still exists.

## Versions and main components

* Spyder Version: Latest
* Python Version: 3.5.2
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please run

    conda update html5lib

to fix this problem.
