### ISSUE TITLE
static code analysis exception raised

### ISSUE THREAD

**Issue by nikosT** [spyder-ide/spyder#4802]
## Description

Clicking on "static code analysis" for a particular python file, I got a Python exception raised window

**What is the expected output? What do you see instead?**

```python-traceback
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/pylint/__main__.py", line 7, in <module>
    pylint.run_pylint()
  File "/usr/local/lib/python2.7/dist-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/pylint/lint.py", line 1218, in __init__
    ), option_groups=self.option_groups, pylintrc=self._rcfile)
  File "/usr/local/lib/python2.7/dist-packages/pylint/lint.py", line 434, in __init__
    config_file=pylintrc or config.PYLINTRC)
  File "/usr/local/lib/python2.7/dist-packages/pylint/config.py", line 448, in __init__
    self.reset_parsers(usage, version=version)
  File "/usr/local/lib/python2.7/dist-packages/pylint/config.py", line 462, in reset_parsers
    self.cfgfile_parser = configparser.ConfigParser(inline_comment_prefixes=('#', ';'))
TypeError: __init__() got an unexpected keyword argument 'inline_comment_prefixes'
```

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 2.7.6
* Qt Versions: 4.8.6, PyQt4 (API v2) 4.10.4 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.13.1 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
It seems like an error in pylint, I mean, I don't see anything about Spyder in your error.

Could you downgrade to `pylint` 1.6.4 and try again?

**Comment by ccordoba12** [comment]
I'm closing this issue because this is not a Spyder problem, but a pylint one.

Please report this issue in the pylint issue tracker.
