### ISSUE TITLE
Add pylint required version in docs

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#481]
_From [miniw...@gmail.com](https://code.google.com/u/102264527247906612870/) on 2010-12-01T05:18:58Z_

It is just a doc remarks.

The v2 docs say than pylint is an optional require to use pylint ins spyder but do not give required version number.

But, apparently pylint version 0.22 is required because the 0.21 from my vendor did not work with spyder (no results at all).

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=481_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-12-01T04:41:43Z_

I've tested it with arbitrary old pylint versions, that's why I did not care to mention a version requirement. 
If  had to, I'd say v0.18 because that's the oldest version I remember trying but it would certainly work with older releases. 0.22 is very recent: Ive just installed it yesterday.

**Comment by spyder-issues-migrator** [comment]
_From [miniw...@gmail.com](https://code.google.com/u/102264527247906612870/) on 2010-12-01T06:06:23Z_

You are right i have just tested with pip 'install pylint==0.18' and it works. I have retested with my vender version with no problem. Maybe it was just a .pylintrc file issue.

**Comment by spyder-issues-migrator** [comment]
_From [miniw...@gmail.com](https://code.google.com/u/102264527247906612870/) on 2010-12-01T06:20:53Z_

Ok i get it, it is probably a bug from mu vendor package version and not form spyder :
Traceback (most recent call last):
  File "/usr/bin/pylint", line 3, in \<module>
    from pylint import lint
  File "/usr/lib/python2.6/site-packages/pylint/lint.py", line 46, in \<module>
    from logilab.common.graph import ordered_nodes
ImportError: cannot import name ordered_nodes

The same version form pip install work perfectly. I will open a bug at Novell for this.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-12-01T08:36:40Z_

**Status:** Done
