### ISSUE TITLE
Monitor log is huge

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#487]
_From [skr...@gmail.com](https://code.google.com/u/113978530372034429162/) on 2010-12-02T13:20:50Z_

What steps will reproduce the problem?

 1. Running spyder with monitor option turned on produces a huge monitor log What is the expected output? What do you see instead? After a few hours the monitor log is about 32G. What version of the product are you using? On what operating system? 2.0.0.rc1, OpenSuse 11.3

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=487_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-12-02T10:38:02Z_

Could you please delete it and re-run Spyder with monitor enabled, and then look inside it?

This file contains precious data regarding console/monitor errors.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-12-02T10:39:03Z_

Oh, BTW, please upgrade your Spyder installation to latest stable release (currently v2.0.2 and very soon v2.0.3).

**Comment by spyder-issues-migrator** [comment]
_From [skr...@gmail.com](https://code.google.com/u/113978530372034429162/) on 2010-12-07T09:44:31Z_

The log shows the same information many times at different times:


======================================
Logging time: Thu Dec  2 09:36:00 2010

======================================

Context
\-------

\<spyderlib.widgets.externalshell.monitor.PacketNotReceived object at 0xafed50>

Traceback
\---------

Traceback (most recent call last):
  File "/usr/local/lib/python2.6/site-packages/spyderlib/widgets/externalshell/monitor.py", line 401, in run
    command = read_packet(self.i_request, timeout=timeout)
  File "/usr/local/lib/python2.6/site-packages/spyderlib/widgets/externalshell/monitor.py", line 80, in read_packet
    dlen, = struct.unpack("l", datalen)
error: unpack requires a string argument of length 8

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-05-16T01:20:40Z_

**Labels:** Cat-Console

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-14T00:07:41Z_

This issue being very old, I will assume that the problem may have been solved in the meantime. If not, please do not hesitate to re-open this issue.

**Status:** Done
