### ISSUE TITLE
Error when trying to get a very large namespace view from the kernel

### ISSUE THREAD

**Issue by Mpagkalos93** [spyder-ide/spyder#4873]
I keep getting the same error after running the following code:

`from brian import *`
`brian_sample_run()`

However the output seems to be fine on IPython console.

**Error**

```python-traceback
  File "/home/biomike/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
Traceback (most recent call last):
  File "/home/biomike/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/home/biomike/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 214, in _handle_execute_reply
    self.handle_exec_method(msg)
  File "/home/biomike/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 317, in handle_exec_method
    properties = ast.literal_eval(data['text/plain'])
  File "/home/biomike/anaconda2/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/home/biomike/anaconda2/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 9001
    ...}
    ^
SyntaxError: invalid syntax
    handler(msg)
  File "/home/biomike/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 214, in _handle_execute_reply
    self.handle_exec_method(msg)
  File "/home/biomike/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 311, in handle_exec_method
    view = ast.literal_eval(data['text/plain'])
  File "/home/biomike/anaconda2/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/home/biomike/anaconda2/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 4001
    ...}
    ^
SyntaxError: invalid syntax
```

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.1 (OK)
sphinx >=0.6.6    :  1.6.2 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0;<6.0:  5.3.0 (OK)
pylint >=0.25     :  1.6.4 (OK)
```

**Comment by Mpagkalos93** [comment]
Update:
i get the same error everytime i am trying to import everything from a module
for example just running:
`from numpy import *`

will result to the same error

**Comment by ccordoba12** [comment]
I know where this error is coming from. We'll fix it in Spyder 3.2.1, to be released this weekend.

In the meantime, please avoid star imports (i.e. `from foo import *`) because they can't be handled by Spyder.

**Comment by goanpeca** [comment]
What is the error @ccordoba12 ?

**Comment by ccordoba12** [comment]
It's not our fault (I think). IPython is not sending the namespace representation that we build in the kernel correctly, but as a truncated dictionary (because it contains too much elements).

That's why we get something like `...` at the end of representation, which makes `ast` to fail.

**Comment by goanpeca** [comment]
Hmm, ok, how do we even fix that :-| ?

**Comment by ccordoba12** [comment]
I was thinking to call `repr` in the kernel side, to avoid this truncation. Then we would need to call `ast` twice in our side.

**Comment by ccordoba12** [comment]
@dalthviz, please help me with this one. I think the idea is to use `repr` in these places:

https://github.com/spyder-ide/spyder/blob/3.x/spyder/utils/ipython/spyder_kernel.py#L113

and

https://github.com/spyder-ide/spyder/blob/3.x/spyder/utils/ipython/spyder_kernel.py#L141

Then we need to use `ast.literal_eval` twice in these places:

https://github.com/spyder-ide/spyder/blob/3.x/spyder/widgets/ipythonconsole/shell.py#L330

and

https://github.com/spyder-ide/spyder/blob/3.x/spyder/widgets/ipythonconsole/shell.py#L336
