### ISSUE TITLE
2.0.3 Installation Error on Ubuntu 10.10

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#493]
_From [dramac.n...@gmail.com](https://code.google.com/u/116034263768925772318/) on 2010-12-08T02:48:32Z_

On installing Spyder 2.0.3 the python setup.py install fail What is the expected output? What do you see instead? I would have Spyder installed What version of the product are you using? On what operating system? On my Ubuntu 10.10 gnome, The version 1.1.8 do not error, but the 2.0.3 do not install 

Please provide any additional information below

. The problem seems to come from Sphinx package. I tried it with the repository version (old) and the last one (1.0.5) install via pip and setuptools.
Here you see the complete traceback:

user@xps-m1330:~/Download/spyder-2.0.3$ sudo python setup.py install
running install
running build
running build_py
running build_scripts
running build_doc
Running Sphinx v1.0.5
WARNING: the config value '__file__' is set to a string with non-ASCII characters; this can lead to Unicode errors occurring. Please use Unicode strings, e.g. u"Content".
loading pickled environment... not yet created
/usr/lib/pymodules/python2.6/pygments/plugin.py:39: UserWarning: Module spyderlib was already imported from /home/dramac/Téléchargements/spyder-2.0.3/spyderlib/__init__.pyc, but /usr/local/lib/python2.6/dist-packages/spyder-1.1.8-py2.6.egg is being added to sys.path
  import pkg_resources
building [html]: targets for 16 source files that are out of date
updating environment: 16 added, 0 changed, 0 removed
Traceback (most recent call last):                                              
  File "setup.py", line 98, in \<module>
    cmdclass=cmdclass)
  File "/usr/lib/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.6/distutils/command/install.py", line 615, in run
    self.run_command('build')
  File "/usr/lib/python2.6/distutils/cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.6/distutils/cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "setup.py", line 52, in run
    setup_command.BuildDoc.run(self)
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0.5-py2.6.egg/sphinx/setup_command.py", line 143, in run
    app.builder.build_update()
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0.5-py2.6.egg/sphinx/builders/__init__.py", line 198, in build_update
    'out of date' &#37; len(to_build))
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0.5-py2.6.egg/sphinx/builders/__init__.py", line 218, in build
    purple, length):
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0.5-py2.6.egg/sphinx/builders/__init__.py", line 120, in status_iterator
    for item in iterable:
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0.5-py2.6.egg/sphinx/environment.py", line 511, in update_generator
    self.read_doc(docname, app=app)
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0.5-py2.6.egg/sphinx/environment.py", line 659, in read_doc
    self.process_images(docname, doctree)
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0.5-py2.6.egg/sphinx/environment.py", line 836, in process_images
    if not os.access(path.join(self.srcdir, imgpath), os.R_OK):
  File "/usr/lib/python2.6/posixpath.py", line 70, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=493_

**Comment by spyder-issues-migrator** [comment]
_From [dramac.n...@gmail.com](https://code.google.com/u/116034263768925772318/) on 2010-12-08T00:21:35Z_

The installation can be executed via pip if no older installation of spyder is on the system.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-12-11T04:07:17Z_

This bug is now handled in Spyder's development version (Mercurial repository): this is actually just a workaround for the Sphinx bug (Sphinx building process is failing when the source package path contains non-ASCII characters).

**Status:** Fixed
