### ISSUE TITLE
I can not open spyder 2.7. ValueError: Dependency has already been registered: pandas

### ISSUE THREAD

**Issue by LDONT** [spyder-ide/spyder#4940]
## Description of your problem
It seems that there are some conflicts with pandas. If I uninstall pandas, it works again. However, I need pandas.
Here is the log:
Traceback (most recent call last):
  File "C:\Users\toluo\AppData\Local\Continuum\Anaconda\lib\site-packages\spyderlib\spyder.py", line 2367, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\toluo\AppData\Local\Continuum\Anaconda\lib\site-packages\spyderlib\spyder.py", line 2255, in run_spyder
    main.setup()
  File "C:\Users\toluo\AppData\Local\Continuum\Anaconda\lib\site-packages\spyderlib\spyder.py", line 779, in setup
    from spyderlib.plugins.console import Console
  File "C:\Users\toluo\AppData\Local\Continuum\Anaconda\lib\site-packages\spyderlib\plugins\console.py", line 30, in <module>
    from spyderlib.utils.environ import EnvDialog
  File "C:\Users\toluo\AppData\Local\Continuum\Anaconda\lib\site-packages\spyderlib\utils\environ.py", line 17, in <module>
    from spyderlib.widgets.dicteditor import DictEditor
  File "C:\Users\toluo\AppData\Local\Continuum\Anaconda\lib\site-packages\spyderlib\widgets\dicteditor.py", line 39, in <module>
    from spyderlib.widgets.dicteditorutils import (sort_against, get_size,
  File "C:\Users\toluo\AppData\Local\Continuum\Anaconda\lib\site-packages\spyderlib\widgets\dicteditorutils.py", line 61, in <module>
    required_version=PANDAS_REQVER)
  File "C:\Users\toluo\AppData\Local\Continuum\Anaconda\lib\site-packages\spyderlib\dependencies.py", line 68, in add
    % modname)
ValueError: Dependency has already been registered: pandas
**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
* Python Version:2.7.13
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by goanpeca** [comment]
@ccordoba12 it seems we are registering pandas twice, maybe we should not error, but simply ignore this if already registered?, or replace with the one already set. Although it would be nice to make sure we are not doing this twice, so a warning would still be useful

**Comment by ccordoba12** [comment]
This error was present in Spyder 2.3 but it was fixed a long time ago. Please update to our latest version (3.2.0) and try again.

**Comment by LDONT** [comment]
@ccordoba12  You are right. Thank you!
