### ISSUE TITLE
Error message when starting latest spyder git clone from bootstrap.py

### ISSUE THREAD

**Issue by yaceben** [spyder-ide/spyder#4952]
## Description
Error message when starting latest spyder git clone from bootstrap.py
**What steps will reproduce the problem?**

1. cd into spyder git clone
2. python2 bootstrap.py

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/me/spyder/spyder/otherplugins.py", line 79, in _import_plugin
    module = _import_module_from_path(module_name, plugin_path)
  File "/home/me/spyder/spyder/otherplugins.py", line 103, in _import_module_from_path
    module = imp.load_module(module_name, *info)
  File "/usr/lib/python2.7/site-packages/spyder_pylint/__init__.py", line 6, in <module>
    from .pylint import Pylint as PLUGIN_CLASS
  File "/usr/lib/python2.7/site-packages/spyder_pylint/pylint.py", line 23, in <module>
    from spyder.plugins import SpyderPluginMixin
ImportError: cannot import name SpyderPluginMixin
ERROR: 3rd party plugin import failed for `spyder_profiler`
Traceback (most recent call last):
  File "/home/me/spyder/spyder/otherplugins.py", line 79, in _import_plugin
    module = _import_module_from_path(module_name, plugin_path)
  File "/home/me/spyder/spyder/otherplugins.py", line 103, in _import_module_from_path
    module = imp.load_module(module_name, *info)
  File "/usr/lib/python2.7/site-packages/spyder_profiler/__init__.py", line 6, in <module>
    from .profiler import Profiler as PLUGIN_CLASS
  File "/usr/lib/python2.7/site-packages/spyder_profiler/profiler.py", line 20, in <module>
    from spyder.plugins import SpyderPluginMixin
ImportError: cannot import name SpyderPluginMixin
ERROR: 3rd party plugin import failed for `spyder_breakpoints`
Traceback (most recent call last):
  File "/home/me/spyder/spyder/otherplugins.py", line 79, in _import_plugin
    module = _import_module_from_path(module_name, plugin_path)
  File "/home/me/spyder/spyder/otherplugins.py", line 103, in _import_module_from_path
    module = imp.load_module(module_name, *info)
  File "/usr/lib/python2.7/site-packages/spyder_breakpoints/__init__.py", line 6, in <module>
    from .breakpoints import Breakpoints as PLUGIN_CLASS
  File "/usr/lib/python2.7/site-packages/spyder_breakpoints/breakpoints.py", line 22, in <module>
    from spyder.plugins import SpyderPluginMixin
ImportError: cannot import name SpyderPluginMixin

## Version and main components

* Spyder Version: 4.0.0.dev0 0faa90e
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux 64bit (Fedora 24)

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.18.0 (OK)
numpy >=1.7       :  1.11.0 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.26 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
You're mixing Spyder 3.2 and master branches because you 3.2 installed system-wide, according to this line:

    /usr/lib/python2.7/site-packages/spyder_breakpoints/init.py

So this is not a bug in Spyder, just an installation problem in your side.
