### ISSUE TITLE
Parallel Python clash

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#496]
_From [NBrier...@gmail.com](https://code.google.com/u/117470284559110323276/) on 2010-12-10T09:16:17Z_

What steps will reproduce the problem?

 Running any (apparently) code involving Parallel Python in Spyder, when creating a server for the jobs to run using pp.Server() What is the expected output? What do you see instead? Code should run just fine, as it does in other IDEs e.g. PyLab. Instead I get:

Exception raised:
    Traceback (most recent call last):
      File "C:\Python26_64\lib\doctest.py", line 1248, in __run
        compileflags, 1) in test.globs
      File "<doctest optimsurface.OptimSurf[21]>", line 1, in \<module>
        opsurf.surfsamples()['regError'].shape
      File "C:\Python26_64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 102, in displayhook
        monitor.refresh()
      File "C:\Python26_64\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 259, in refresh
        communicate(self.n_request, dict(command="refresh"))
      File "C:\Python26_64\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 121, in communicate
        return read_packet(sock)
      File "C:\Python26_64\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 96, in read_packet
        dlen, = struct.unpack("l", datalen)
    error: unpack requires a string argument of length 4
Traceback (most recent call last):
  File "..\pyTest.py", line 217, in \<module>
    doctest.testmod(m)
  File "C:\Python26_64\lib\doctest.py", line 1837, in testmod
    runner.run(test)
  File "C:\Python26_64\lib\doctest.py", line 1372, in run
    self.debugger.reset()
  File "C:\Python26_64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 134, in reset
    self.set_spyder_breakpoints() #-----Spyder-specific---------------------
  File "C:\Python26_64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 158, in set_spyder_breakpoints
    monitor.notify_pdb_breakpoints()
  File "C:\Python26_64\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 268, in notify_pdb_breakpoints
    communicate(self.n_request, dict(command="pdb_breakpoints"))
  File "C:\Python26_64\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 117, in communicate
    write_packet(sock, command)
  File "C:\Python26_64\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 85, in write_packet
    sock.send(struct.pack("l", len(sent_data)) + sent_data)
socket.error: [Errno 10053] An established connection was aborted by the software in your host machine What version of the product are you using? On what operating system? I'm using Spyder 2.0.3 with Python 2.6.5 (Enthought) and Parallel Python 1.6 on 64-bit Windows 7 

Please provide any additional information below

. I've seen the related issues and apparent fix found here: https://code.google.com/p/spyderlib/issues/detail?id=108 https://code.google.com/p/spyderlib/source/detail?r=44dea5560bb10098bccf75d1b222613ba288d4ce

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=496_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-07-22T16:00:14Z_

I tried a couple of Parallel Python examples with 2.1 and 2.2 versions and they seem to be working just fine. Probably this was fixed a long time ago (and please forgive us for coming back to you after so much time).

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [alvarez....@gmail.com](https://code.google.com/u/117398193241321780002/) on 2012-10-21T14:01:33Z_

I have the same problem :_(

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-10-26T07:52:56Z_

Please provide us with an example script that is failing for you, along with the pertinent information: your platform (Linux, Windows, Mac?), Spyder, Qt and PyQt versions.

As I said before, I tried several examples under Linux and all was working fine for me.

**Cc:** alvarez....@gmail.com
