### ISSUE TITLE
An error occurred while starting the Kernel

### ISSUE THREAD

**Issue by dhirendradas** [spyder-ide/spyder#4969]
## Description
I saw number of users facing this problem and the solutions proposed. It didn't resolve mine. Please help.

An error ocurred while starting the kernel
Traceback (most recent call last):
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 231, in 
main()
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 204, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\ipykernel\connect.py", line 18, in 
import jupyter_client
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\jupyter_client\__init__.py", line 4, in 
from .connect import *
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 22, in 
import zmq
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\__init__.py", line 34, in 
from zmq import backend
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 40, in 
reraise(*exc_info)
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\utils\sixcerpt.py", line 34, in reraise
raise value
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 27, in 
_ns = select_backend(first)
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\cython\__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
Traceback (most recent call last):
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 231, in 
main()
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 204, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\ipykernel\connect.py", line 18, in 
import jupyter_client
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\jupyter_client\__init__.py", line 4, in 
from .connect import *
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 22, in 
import zmq
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\__init__.py", line 34, in 
from zmq import backend
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 40, in 
reraise(*exc_info)
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\utils\sixcerpt.py", line 34, in reraise
raise value
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 27, in 
_ns = select_backend(first)
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\cython\__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
Traceback (most recent call last):
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 231, in 
main()
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 204, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\ipykernel\connect.py", line 18, in 
import jupyter_client
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\jupyter_client\__init__.py", line 4, in 
from .connect import *
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 22, in 
import zmq
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\__init__.py", line 34, in 
from zmq import backend
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 40, in 
reraise(*exc_info)
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\utils\sixcerpt.py", line 34, in reraise
raise value
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 27, in 
_ns = select_backend(first)
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\cython\__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
Traceback (most recent call last):
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 231, in 
main()
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 204, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\ipykernel\connect.py", line 18, in 
import jupyter_client
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\jupyter_client\__init__.py", line 4, in 
from .connect import *
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 22, in 
import zmq
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\__init__.py", line 34, in 
from zmq import backend
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 40, in 
reraise(*exc_info)
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\utils\sixcerpt.py", line 34, in reraise
raise value
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 27, in 
_ns = select_backend(first)
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\cython\__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
Traceback (most recent call last):
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 231, in 
main()
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 204, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\ipykernel\connect.py", line 18, in 
import jupyter_client
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\jupyter_client\__init__.py", line 4, in 
from .connect import *
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 22, in 
import zmq
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\__init__.py", line 34, in 
from zmq import backend
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 40, in 
reraise(*exc_info)
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\utils\sixcerpt.py", line 34, in reraise
raise value
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 27, in 
_ns = select_backend(first)
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\cython\__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
Traceback (most recent call last):
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 231, in 
main()
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 204, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\ipykernel\connect.py", line 18, in 
import jupyter_client
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\jupyter_client\__init__.py", line 4, in 
from .connect import *
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 22, in 
import zmq
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\__init__.py", line 34, in 
from zmq import backend
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 40, in 
reraise(*exc_info)
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\utils\sixcerpt.py", line 34, in reraise
raise value
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\__init__.py", line 27, in 
_ns = select_backend(first)
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "C:\Users\Basundhara\Anaconda3\lib\site‑packages\zmq\backend\cython\__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'

I have used pip to update and how do I rectify it? Reinstalling didn't resolve the issue.

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
> I have used pip to update and how do I rectify it?

There's no easy way you can rectify that. Please uninstall and reinstall Anaconda again, and never, ever, use pip to install/update a package already provided by conda.

**Comment by dhirendradas** [comment]
Ccordoba12, I uninstalled and installed it again, but it still throws the error. Is there any registry entries I have to delete?

**Comment by ccordoba12** [comment]
No idea, sorry. This looks like an installation problem, other than that I don't know how to help you.

**Comment by dhirendradas** [comment]
Thanks for the suggestion. I reinstalled it and problem is resolved now.
