### ISSUE TITLE
problem with strptime only in spyder's ipython console

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#498]
_From [tditt...@physik.net](https://code.google.com/u/107874965214553814381/) on 2010-12-11T21:26:14Z_

Hi,

currently I am trying to read some mass spectrometry data which have been exportet into a ascii file.
Unfortunately I run into some problems with spyder's ipython console. 
I deviced the following test code to reproduce the problem

import time 
line = """"10/27/2010 1:15:51 PM"	9019	-3.1797e-013	4.0939e-012	1.4309e-012	-2.5835e-012	2.5835e-012	3.4977e-012	2.5835e-012 """
tokens = line.split('\t') 
timeOfSampling = time.mktime(time.strptime(tokens[0],'"&#37;m/&#37;d/&#37;Y &#37;I:&#37;M:&#37;S &#37;p"'))

when I run the test code in the ipython console I get: 

In [12]: import time 

In [13]: line = """"10/27/2010 1:15:51 PM"	9019	-3.1797e-013	4.0939e-012	1.4309e-012	-2.5835e-012	2.5835e-012	3.4977e-012	2.5835e-012 """

In [14]: tokens = line.split('\t') 

In [15]: timeOfSampling = time.mktime(time.strptime(tokens[0],'"&#37;m/&#37;d/&#37;Y &#37;I:&#37;M:&#37;S &#37;p"'))
\------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython console>", line 1, in \<module>
  File "/usr/lib/python2.6/_strptime.py", line 454, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib/python2.6/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '"10/27/2010 1:15:51 PM"' does not match format '"&#37;m/&#37;d/&#37;Y &#37;I:&#37;M:&#37;S &#37;p"'

it works fine in the normal python console:

\>>> import time 
\>>> line = """"10/27/2010 1:15:51 PM"	9019	-3.1797e-013	4.0939e-012	1.4309e-012	-2.5835e-012	2.5835e-012	3.4977e-012	2.5835e-012 """
\>>> tokens = line.split('\t') 
\>>> timeOfSampling = time.mktime(time.strptime(tokens[0],'"&#37;m/&#37;d/&#37;Y &#37;I:&#37;M:&#37;S &#37;p"'))

I also testet the code sniped in an external ipython instance and ther eit worked too.
So the problem seems to be related to spyder, but to be honest I have no idea what could be the problem.

I run spyder 2.0.3 with Python 2.6.6, Qt 4.6.3, PyQt 4.7.3 on Debian-testing 
 
Timo

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=498_

**Comment by spyder-issues-migrator** [comment]
_From [tditt...@physik.net](https://code.google.com/u/107874965214553814381/) on 2011-03-02T11:05:48Z_

I think this issue can be closed. 

The problem was not with spyder but with a subtle interaction of the -pylab and/or -q4thread options for Ipython.

When Ipython is called with the q4thread or pylab option, automatically the system default is set as locale. In my case this is de_DE and UTF8 which implies a 24 hour time format.

On a plain python or Ipython interpreter the 'C' locale is used which implies a 12 hour time format.

Since spyder calls Ipython with the -pylab  option, setting the german locale, my the example code did not run as expected.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-03-02T11:18:50Z_

Glad to hear you find the way to solve your problem. Thanks a lot for posting back your solution and of course, for using Spyder :-)

Cheers,
Carlos

**Status:** Invalid
