### ISSUE TITLE
can't start spyder

### ISSUE THREAD

**Issue by boazdori** [spyder-ide/spyder#5007]
## Description of your problem

**What steps will reproduce the problem?**

1. try starting spyder
2. it stopes the process and dosent come up.
3. the following is the error i printed from the anaconda application louncher

Traceback (most recent call last):
File "C:\Users\user\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3067, in main
mainwindow = run_spyder(app, options, args)
File "C:\Users\user\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2969, in run_spyder
main.setup()
File "C:\Users\user\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 899, in setup
from spyder.plugins.variableexplorer import VariableExplorer
File "C:\Users\user\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer.py", line 18, in 
from spyder.widgets.variableexplorer.namespacebrowser import NamespaceBrowser
File "C:\Users\user\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\namespacebrowser.py", line 25, in 
import ipykernel.pickleutil
File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "C:\Users\user\Anaconda3\lib\site-packages\IPython\__init__.py", line 55, in 
from .terminal.embed import embed
File "C:\Users\user\Anaconda3\lib\site-packages\IPython\terminal\embed.py", line 15, in 
from IPython.core.interactiveshell import DummyMod, InteractiveShell
File "C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 61, in 
from IPython.utils import io
File "C:\Users\user\Anaconda3\lib\site-packages\IPython\utils\io.py", line 88, in 
devnull = open(os.devnull, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'nul'

## Versions and main components

* Spyder Version:3.21
* Python Version:3.6.2
* Qt Version:5.6.2
* PyQt Version:5.6.0
* Operating system:win 10

**Comment by ccordoba12** [comment]
I answer to this in anaconda-issues already.
