### ISSUE TITLE
spyder runtime bug caused by htm5lib on Windows

### ISSUE THREAD

**Issue by girardinsamuel** [spyder-ide/spyder#5018]
## Description of your problem
When I upgraded spyder (and its dependencies) then I wasn't able to run Spyder. There was the following error at runtime:
```
Traceback (most recent call last):
  File "C:\Python27\Scripts\spyder", line 3, in <module>
    start_app.main()
  File "C:\Python27\lib\site-packages\spyderlib\start_app.py", line 114, in main
    from spyderlib import spyder
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 155, in <module>
    from spyderlib.utils.environ import WinUserEnvDialog
  File "C:\Python27\lib\site-packages\spyderlib\utils\environ.py", line 17, in <module>
    from spyderlib.widgets.dicteditor import DictEditor
  File "C:\Python27\lib\site-packages\spyderlib\widgets\dicteditor.py", line 39, in <module>
    from spyderlib.widgets.dicteditorutils import (sort_against, get_size,
  File "C:\Python27\lib\site-packages\spyderlib\widgets\dicteditorutils.py", line 78, in <module>
    import bs4
  File "C:\Python27\lib\site-packages\bs4\__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "C:\Python27\lib\site-packages\bs4\builder\__init__.py", line 311, in <module>
    from . import _html5lib
  File "C:\Python27\lib\site-packages\bs4\builder\_html5lib.py", line 57, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
```

**What steps will reproduce the problem?**
1. pip install --upgrade spyder
2. spyder &

**What is the expected output? What do you see instead?**
Spyder should start and this error located in beautifulsoup / html5lib package prevents Spyder to start.

**Please provide any additional information below**
I managed to solve the problem by downgrading the version of htm5lib package with the following command:
`pip install --upgrade html5lib==1.0b8`
from https://stackoverflow.com/a/41161317

## Versions and main components

* Spyder Version: 2.3.8
* Python Version: 2.7.12
* Qt Version: 4.8.7
* PySide Version: 1.2.4
* Operating system: windows 7 - 64 bits

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=1.0      :  5.4.1 (OK)
jedi >=0.8.1;<0.9.0:  0.10.2 (NOK)
matplotlib >=1.0   :  1.5.3 (OK)
pandas >=0.13.1    :  0.18.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.5.0   :  1.6.0 (OK)
pygments >=1.6     :  2.2.0 (OK)
pylint >=0.25      :  1.7.2 (OK)
qtconsole >=4.0    :  4.3.1 (OK)
rope >=0.9.2       :  0.10.2 (OK)
sphinx >=0.6.6     :  1.6.3 (OK)
sympy >=0.7.3      :  1.0 (OK)
zmq >=2.1.11       :  16.0.2 (OK)

**Comment by ccordoba12** [comment]
We fixed this bug in Spyder 3.2.0, please update to that version (you're using 2.3.8, which is very old).
