### ISSUE TITLE
Spyder error when opening after setting it up as an app in Mac

### ISSUE THREAD

**Issue by abhayap** [spyder-ide/spyder#5022]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/abhaya/miniconda3/lib/python3.6/site-packages/spyder/config/user.py", line 111, in _save
    _write_file(fname)
  File "/Users/abhaya/miniconda3/lib/python3.6/site-packages/spyder/config/user.py", line 107, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: 'sn_0_553095/.spyproject/workspace.ini'

Traceback (most recent call last):
  File "/Users/abhaya/miniconda3/lib/python3.6/site-packages/spyder/plugins/projects.py", line 148, in <lambda>
    lambda v: self.editor.setup_open_files())
  File "/Users/abhaya/miniconda3/lib/python3.6/site-packages/spyder/plugins/editor.py", line 2662, in setup_open_files
    filenames = self.projects.get_project_filenames()
  File "/Users/abhaya/miniconda3/lib/python3.6/site-packages/spyder/plugins/projects.py", line 316, in get_project_filenames
    recent_files = self.current_active_project.get_recent_files()
  File "/Users/abhaya/miniconda3/lib/python3.6/site-packages/spyder/widgets/projects/type/__init__.py", line 78, in get_recent_files
    default=[])
  File "/Users/abhaya/miniconda3/lib/python3.6/site-packages/spyder/config/user.py", line 377, in get
    self.set(section, option, default)
  File "/Users/abhaya/miniconda3/lib/python3.6/site-packages/spyder/config/user.py", line 445, in set
    self._save()
  File "/Users/abhaya/miniconda3/lib/python3.6/site-packages/spyder/config/user.py", line 121, in _save
    raise(e)
  File "/Users/abhaya/miniconda3/lib/python3.6/site-packages/spyder/config/user.py", line 117, in _save
    _write_file(fname)
  File "/Users/abhaya/miniconda3/lib/python3.6/site-packages/spyder/config/user.py", line 107, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: 'sn_0_553095/.spyproject/workspace.ini'

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
We don't support this method, sorry. Someone else reported this problem a couple of weeks ago, so please search our issues to find the solution (I don't remember what was the issue, sorry again).
