### ISSUE TITLE
Error when trying to open table in variable explorer

### ISSUE THREAD

**Issue by I022044** [spyder-ide/spyder#5050]
## Description

**What steps will reproduce the problem?**

1.   Open a table in variable explorer
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 262, in get_value
    value = self.df.iloc[row, column]
  File "C:\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1322, in __getitem__
    return self._getitem_scalar(key)
  File "C:\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1629, in _getitem_scalar
    values = self.obj.get_value(*key, takeable=True)
  File "C:\Anaconda3\lib\site-packages\pandas\core\frame.py", line 1915, in get_value
    return _maybe_box_datetimelike(series._values[index])
  File "C:\Anaconda3\lib\site-packages\pandas\core\common.py", line 172, in _maybe_box_datetimelike
    value = tslib.Timestamp(value)
  File "pandas\_libs\tslib.pyx", line 402, in pandas._libs.tslib.Timestamp.__new__ (pandas\_libs\tslib.c:10051)
  File "pandas\_libs\tslib.pyx", line 1517, in pandas._libs.tslib.convert_to_tsobject (pandas\_libs\tslib.c:28598)
  File "pandas\_libs\tslib.pyx", line 1774, in pandas._libs.tslib._check_dts_bounds (pandas\_libs\tslib.c:32752)
pandas._libs.tslib.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 9999-12-31 00:00:00
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\data

**Comment by ccordoba12** [comment]
This is an error in Pandas, not Spyder. Unfortunately the error is not complete, but that seems to be the case, so I'm closing this issue.
