### ISSUE TITLE
Error when viewing dataframes and arrays in environments without Numpy and Pandas

### ISSUE THREAD

**Issue by anandrathidev** [spyder-ide/spyder#5061]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\ProgramData\Anaconda3\envs\tensor\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 633, in process
    self.clip_data = self._get_table_data()
  File "D:\ProgramData\Anaconda3\envs\tensor\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 613, in _get_table_data
    return array(data)
NameError: name 'array' is not defined
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\tensor\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 633, in process
    self.clip_data = self._get_table_data()
  File "D:\ProgramData\Anaconda3\envs\tensor\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 613, in _get_table_data
    return array(data)
NameError: name 'array' is not defined

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.5.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (OK)
numpy >=1.7      :  None (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.9.

**Comment by ccordoba12** [comment]
You don't have Numpy nor Pandas installed in your `tensor` environment.

**Comment by goanpeca** [comment]
If I try to import without numpy installed, the options are no longer available:

<img width="542" alt="Screen Shot 2019-11-29 at 19 38 22" src="https://user-images.githubusercontent.com/3627835/69893477-dd6aea80-12df-11ea-9af7-4b4c7663e467.png">


Closing.
