### ISSUE TITLE
Jupyter Notebook fails on Win7,32bit machine with vague error message ("DLL load failed")

### ISSUE THREAD

**Issue by ventilator** [spyder-ide/spyder#5098]
## Description

**What steps will reproduce the problem?**

1. download WinPython-32bit-3.6.2.0Qt5.exe
2. install on a Win7/32bit machine
3.  start spyder.exe
4. some error occurs because jupyter notebook does not work
5. spyder gives errormessage (see below)

**What is the expected output? What do you see instead?**
I guess spyder tries to display some failure message box, but fails to do so.
Jupyter Notebook does not start, with vague message it misses a DLL

**Please provide any additional information below**
The underlying problem is that jupyter notebook does not work on my machine for some unknown reason

```
"Traceback (most recent call last):
  File "C:\WinPython\32bit-3.6.2.0Qt5\python-3.6.2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\WinPython\32bit-3.6.2.0Qt5\python-3.6.2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\WinPython\32bit-3.6.2.0Qt5\python-3.6.2\scripts\jupyter-notebook.exe\__main__.py", line 5, in <module>
  File "C:\WinPython\32bit-3.6.2.0Qt5\python-3.6.2\lib\site-packages\notebook\notebookapp.py", line 46, in <module>
    from zmq.eventloop import ioloop
  File "C:\WinPython\32bit-3.6.2.0Qt5\python-3.6.2\lib\site-packages\zmq\__init__.py", line 34, in <module>
    from zmq import backend
  File "C:\WinPython\32bit-3.6.2.0Qt5\python-3.6.2\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\WinPython\32bit-3.6.2.0Qt5\python-3.6.2\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\WinPython\32bit-3.6.2.0Qt5\python-3.6.2\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\WinPython\32bit-3.6.2.0Qt5\python-3.6.2\lib\site-packages\zmq\backend\select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\WinPython\32bit-3.6.2.0Qt5\python-3.6.2\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module
>
    **from . import (constants, error, message, context,
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.**
```
Error message coming from spyder:

  File "C:\WinPython\32bit-3.6.2.0Qt5\python-3.6.2\lib\site-packages\spyder_terminal\terminalplugin.py", line 156, in __wait_server_to_start
    QMessageBox.Ok)
TypeError: 'Icon' object is not callable

## Version and main components

* Spyder Version: 3.2.1.dev0 
* Python Version: 3.6.2
* Qt Versions: 5.9.1, PyQt5 5.9 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by rlaverde** [comment]
The backtrace coming from spyder correspond to this error https://github.com/spyder-ide/spyder-terminal/issues/96 that's already fixed, please update spyder-terminal

The other one looks like a WinPython error.
