### ISSUE TITLE
Internal console error when selecting Source -> Next warning/error (or Previous warning/error)

### ISSUE THREAD

**Issue by csabella** [spyder-ide/spyder#5116]
## Description of your problem
When running master branch, get the following in the Internal console when selecting Source -> Next warning/error:
>>> Traceback (most recent call last):
  File "/home/cheryl/spyder/spyder/plugins/editor.py", line 2151, in go_to_next_warning
    position = editor.go_to_next_warning()
  File "/home/cheryl/spyder/spyder/widgets/sourcecode/codeeditor.py", line 1433, in go_to_next_warning
    self.__show_code_analysis_results(line_number, data.code_analysis)
AttributeError: 'CodeEditor' object has no attribute '_CodeEditor__show_code_analysis_results'

**What steps will reproduce the problem?**

1.   Open source in Editor.
2.   From the menu, select Source -> Next warning/error
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:  4.0.0.dev0
* Python Version:  3.6.2
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by csabella** [comment]
I have researched this issue and found that PR#3463 changed `__show_code_analysis_results` to `show_code_analysis_results`, but didn't update `go_to_next_warning` and `go_to_previous_warning`.

I'm submitting a PR with a fix.

This is for 4.0.0 only.
