### ISSUE TITLE
After updating spyder to 3.2.1 notebook is not working

### ISSUE THREAD

**Issue by gchandra33** [spyder-ide/spyder#5135]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "D:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "D:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

Traceback (most recent call last):
  File "D:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "D:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\urllib3\connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=en

**Comment by ccordoba12** [comment]
I think this line

    ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

indicates that your PC is refusing internet connections. So the problem doesn't seem to be with Spyder but probably with your firewall and/or antivirus.
