### ISSUE TITLE
"name 'locale_encoding' is not defined" ?

### ISSUE THREAD

**Issue by omeras** [spyder-ide/spyder#5155]
Hey all. Spyder crashes every time I try to run it.
I assume it is related somehow to the fact that I have Hebrew language installed, but I understand absolutely nothing about it. Tried to reset spyder, to no avail. Other applications (firefox \ libreoffice) works flawlessly with Hebrew.

**What is the expected output? What do you see instead?**
Traceback (most recent call last):
  File "/home/omera/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3093, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/omera/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2995, in run_spyder
    main.setup()
  File "/home/omera/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 832, in setup
    from spyder.plugins.help import Help
  File "/home/omera/anaconda3/lib/python3.6/site-packages/spyder/plugins/help.py", line 32, in <module>
    from spyder.utils.help.sphinxify import (CSS_PATH, generate_context,
  File "/home/omera/anaconda3/lib/python3.6/site-packages/spyder/utils/help/sphinxify.py", line 29, in <module>
    from docutils.utils import SystemMessage as SystemMessage
  File "/home/omera/anaconda3/lib/python3.6/site-packages/docutils/utils/__init__.py", line 20, in <module>
    import docutils.io
  File "/home/omera/anaconda3/lib/python3.6/site-packages/docutils/io.py", line 18, in <module>
    from docutils.utils.error_reporting import locale_encoding, ErrorString, ErrorOutput
  File "/home/omera/anaconda3/lib/python3.6/site-packages/docutils/utils/error_reporting.py", line 60, in <module>
    codecs.lookup(locale_encoding or '') # None -> ''
NameError: name 'locale_encoding' is not defined

## Versions and main components

* Spyder Version: 3.2.2 (via latest anaconda 3).
* Python Version: 3.6.1
* Qt Version: 5.6.2
* PyQt Version: no idea what is that
* Operating system: Ubuntu 17.04 (a fresh install)

Thanks!

**Comment by ccordoba12** [comment]
Please try to start Spyder with this command

    LC_ALL=C spyder

to see if it works.

**Comment by omeras** [comment]
It works! Thank you very much. I'm new to linux environment, if you can explain what was the issue - I'd be grateful . Thanks again.
