### ISSUE TITLE
Preferences Dialog Dismissal Problem

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#516]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2010-12-29T11:08:35Z_

I was changing some settings in the editor section of the Preferences Dialog and when I hit OK the dialog would not be dismissed.  I was able to Cancel out.

Spyder 2.0.5, Python 2.6.1, Windows XP SP3

Additional info:
Internal Console Output:
\>>> Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\spyderlib\plugins\configdialog.py", line 137, in accept
    configpage.apply_changes()
  File "C:\Python26\lib\site-packages\spyderlib\plugins\configdialog.py", line 67, in apply_changes
    self.apply_callback()
  File "C:\Python26\lib\site-packages\spyderlib\plugins\configdialog.py", line 169, in \<lambda>
    self.apply_settings(self.changed_options))
  File "C:\Python26\lib\site-packages\spyderlib\plugins\variableexplorer.py", line 205, in apply_plugin_settings
    shellwidget.set_autorefresh_timeout(ar_timeout)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\externalshell\pythonshell.py", line 223, in set_autorefresh_timeout
    "set_monitor_timeout(&#37;d)" &#37; interval)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 117, in communicate
    write_packet(sock, command)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 85, in write_packet
    sock.send(struct.pack("l", len(sent_data)) + sent_data)
socket.error: [Errno 10054] An existing connection was forcibly closed by the remote host

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=516_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-01-09T06:49:37Z_

**Status:** Accepted

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-05-16T01:25:39Z_

I'm closing this issue as -apparently- this bug did not happen since then.

**Status:** WontFix  
  **Labels:** Cat-Settings
