### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ryarlagadda** [spyder-ide/spyder#5174]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/RaviTeja/anaconda/lib/python2.7/site-packages/spyder/plugins/projects.py", line 233, in _create_project
    self.open_project(path=path)
  File "/Users/RaviTeja/anaconda/lib/python2.7/site-packages/spyder/plugins/projects.py", line 269, in open_project
    self.restart_consoles()
  File "/Users/RaviTeja/anaconda/lib/python2.7/site-packages/spyder/plugins/projects.py", line 386, in restart_consoles
    self.main.ipyconsole.restart()
  File "/Users/RaviTeja/anaconda/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 1286, in restart
    self.create_new_client(give_focus=False)
  File "/Users/RaviTeja/anaconda/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 977, in create_new_client
    self.connect_client_to_kernel(client)
  File "/Users/RaviTeja/anaconda/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 998, in connect_client_to_kernel
    stderr_file)
  File "/Users/RaviTeja/anaconda/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 1386, in create_kernel_manager_and_kernel_client
    stderr = codecs.open(stderr_file, 'w', encoding='utf-8')
  File "/Users/RaviTeja/anaconda/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'/var/folders/0s/47z92ltn01b9rck276wy6r100000gn/T/spyder-RaviTeja/kernel-1fda197fb976.stderr'
Traceback (most recent call last):
  File "/Users/RaviTeja/anaconda/lib/python2.7/site-packages/spyder/plugins/projects.py", line 229, in create_new_project
    self.restart_consoles()
  File "/Users/RaviTeja/anaconda/lib/python2.7/site-packages/spyder/plugins/projects.py", line 386, in restart_consoles
    self.main.ipyconsole.restart()
  File "/Users/RaviTeja/anaconda/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 1286, in restart
    self.create_new_client(give_focus=False)
  File "/Users/RaviTeja/anaconda/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 977, in create_new_client
    self.connect_client_to_kernel(client)
  File "/Users/RaviTeja/anaconda/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 998, in connect_client_to_kernel
    stderr_file)
  File "/Users/RaviTeja/anaconda/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 1386, in create_kernel_manager_and_kernel_client
    stderr = codecs.open(stderr_file, 'w', encoding='utf-8')
  File "/Users/RaviTeja/anaconda/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'/var/folders/0s/47z92ltn01b9rck276wy6r100000gn/T/spyder-RaviTeja/kernel-9e95e84e9000.stderr'

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.1 (OK)
numpy >=1.7       :  1.12.1 (OK)
sphinx >=0.6.6    :  1.5.6 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  5.1.1 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0;<6.0:  5.3.0 (OK)
pylint >=0.25     :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
This was fixed in Spyder 3.2.2, please update.
