### ISSUE TITLE
pdb.pm() raises an Error

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#5200]
## Description

**What steps will reproduce the problem?**

1. create an error
2. Try to debug using pdb.pm()

**Please provide any additional information below**

Traceback (most recent call last):

  File "<ipython-input-3-619d77b83f20>", line 1, in <module>
    pdb.pm()

  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pdb.py", line 1604, in pm
    post_mortem(sys.last_traceback)

  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pdb.py", line 1601, in post_mortem
    p.interaction(None, t)

  File "/Users/quentinpeter/pyscripts/spyder/spyder/utils/site/sitecustomize.py", line 440, in interaction
    if "sitecustomize.py" not in frame.f_code.co_filename:

AttributeError: 'NoneType' object has no attribute 'f_code'

## Version and main components

* Spyder Version: 4.0.0.dev0 474e59379
* Python Version: 3.6.2
* Qt Versions: 5.9.1, PyQt5 5.9 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.
