### ISSUE TITLE
spyder

### ISSUE THREAD

**Issue by eric0371** [spyder-ide/spyder#5208]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\Anaconda3\lib\site-packages\pandas\core\common.py", line 172, in _maybe_box_datetimelike
    value = tslib.Timestamp(value)
  File "pandas\_libs\tslib.pyx", line 402, in pandas._libs.tslib.Timestamp.__new__ (pandas\_libs\tslib.c:10051)
  File "pandas\_libs\tslib.pyx", line 1517, in pandas._libs.tslib.convert_to_tsobject (pandas\_libs\tslib.c:28598)
  File "pandas\_libs\tslib.pyx", line 1774, in pandas._libs.tslib._check_dts_bounds (pandas\_libs\tslib.c:32752)
pandas._libs.tslib.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 9999-09-09 00:00:00
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 260, in get_value
    value = self.df.iat[row, column]
  File "D:\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1786, in __getitem__
    return self.obj.get_value(*key, takeable=self._takeable)
  File "D:\Anaconda3\lib\site-packages\pandas\core\frame.py", line 1915, in get_value
    return _maybe_box_datetimelike(series._values[index])
  File "D:\Anaconda3\lib\site-packages\pandas\core\common.py", line 172, in _maybe_box_datetimelike
    value = tslib.Timestamp(value)
  File "pandas\_libs\tslib.pyx", line 402, in pandas._libs.tsli

**Comment by ccordoba12** [comment]
This looks like a bug in Pandas. Please close Spyder and any other program that's using Python, then run in a system terminal (cmd.exe) this

    conda install -f pandas

That should fix your problem.
