### ISSUE TITLE
error in saving python file

### ISSUE THREAD

**Issue by Irfan19-84** [spyder-ide/spyder#5209]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Irfan\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1474, in save
    finfo.encoding)
  File "C:\Users\Irfan\Anaconda3\lib\site-packages\spyder\utils\encoding.py", line 227, in write
    with open(filename, mode) as textfile:
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\Odoo 8.0-20170902\\server\\openerp\\custom_addons\\irfan\\__init__.py'

Traceback (most recent call last):
  File "C:\Users\Irfan\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 1978, in save
    return editorstack.save(index=index, force=force)
  File "C:\Users\Irfan\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1507, in save
    self)
TypeError:   QMessageBox(QMessageBox.Icon, str, str, buttons: Union[QMessageBox.StandardButtons, QMessageBox.StandardButton] = QMessageBox.NoButton, parent: QWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.Dialog|Qt.MSWindowsFixedSizeDialogHint): argument 4 has unexpected type 'EditorStack'

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.

**Comment by rlaverde** [comment]
This is duplicated of #5111 and was fixed in Spyder3.2.2. Please update.
