### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by SlideLucask** [spyder-ide/spyder#5233]
## An error ocurred while starting the kernel

I run the spyder ide , in the ipython-console shows like this below:

An error ocurred while starting the kernel
Traceback (most recent call last):
File "/home/lucask/anaconda2/lib/python2.7/site‑packages/spyder/utils/ipython/start_kernel.py", line 231, in 
main()
File "/home/lucask/anaconda2/lib/python2.7/site‑packages/spyder/utils/ipython/start_kernel.py", line 212, in main
from utils.ipython.spyder_kernel import SpyderKernel
ImportError: No module named ipython.spyder_kernel
Traceback (most recent call last):
File "/home/lucask/anaconda2/lib/python2.7/site‑packages/spyder/utils/ipython/start_kernel.py", line 231, in 
main()
File "/home/lucask/anaconda2/lib/python2.7/site‑packages/spyder/utils/ipython/start_kernel.py", line 212, in main
from utils.ipython.spyder_kernel import SpyderKernel
ImportError: No module named ipython.spyder_kernel
Traceback (most recent call last):
File "/home/lucask/anaconda2/lib/python2.7/site‑packages/spyder/utils/ipython/start_kernel.py", line 231, in 
main()
File "/home/lucask/anaconda2/lib/python2.7/site‑packages/spyder/utils/ipython/start_kernel.py", line 212, in main
from utils.ipython.spyder_kernel import SpyderKernel
ImportError: No module named ipython.spyder_kernel
Traceback (most recent call last):
File "/home/lucask/anaconda2/lib/python2.7/site‑packages/spyder/utils/ipython/start_kernel.py", line 231, in 
main()
File "/home/lucask/anaconda2/lib/python2.7/site‑packages/spyder/utils/ipython/start_kernel.py", line 212, in main
from utils.ipython.spyder_kernel import SpyderKernel
ImportError: No module named ipython.spyder_kernel
Traceback (most recent call last):
File "/home/lucask/anaconda2/lib/python2.7/site‑packages/spyder/utils/ipython/start_kernel.py", line 231, in 
main()
File "/home/lucask/anaconda2/lib/python2.7/site‑packages/spyder/utils/ipython/start_kernel.py", line 212, in main
from utils.ipython.spyder_kernel import SpyderKernel
ImportError: No module named ipython.spyder_kernel

I have tried use this command :  `conda update setuptools`

but it still shows this problem , anyone knows how to deal with it ?
Many Thanks!!!

**Comment by ccordoba12** [comment]
Do you have a module called `utils` in your current working directory?

**Comment by ccordoba12** [comment]
Closing because of lack of response.

**Comment by JamesOwers** [comment]
@ccordoba12 - I have this issue too and yes I do have a module called utils in my wd. Does this mean I can't use spyder for any project with a utils module?

**Comment by ccordoba12** [comment]
@JamesOwers, yes, that's right. We'll fix this in Spyder 4, sorry for the inconvenience in the meantime.

**Comment by JamesOwers** [comment]
Thanks for response ok - I've moved my module to `my_utils` and refactored code...but I imagine this would be very annoying for established libraries being developed e.g. sklearn! What sort of date are you looking at for Spyder 4?

**Comment by ccordoba12** [comment]
There's no clear release date, sorry. Please read

https://github.com/spyder-ide/spyder/wiki/Anaconda-stopped-funding-Spyder

for the details.

**Comment by bmilde** [comment]
I also get 

main()
File "/usr/lib/python3/dist‑packages/spyder/utils/ipython/start_kernel.py", line 239, in main
from spyder.utils.ipython.spyder_kernel import SpyderKernel
ModuleNotFoundError: No module named 'spyder.utils.ipython.spyder_kernel

when starting an ipython console after updating spyder to the newest version.

I no longer have a utils.py file in my working directory and still have the the problem

**Comment by ccordoba12** [comment]
@bmilde, from your error above, it seems clear that you installed a new Spyder version over or next to an older one. That could have corrupted your Linux installation, which will force you to reinstall. You also need to uninstall the old version (no idea how, you were the one that installed it) to let the new one work correctly.

**Comment by bmilde** [comment]
Thank you! The problem was indeed related to a corrupt installation from
having both the ubuntu version of spyder (after a recent dist-upgrade) and
the pip version installed. After removing the apt version, spyder works now
again!

Btw, does the limitation to have no local utils module on the current
wokring dir still exist, or is this solved now?

Carlos Cordoba <notifications@github.com> schrieb am Mi., 20. März 2019,
10:18:

**Comment by ccordoba12** [comment]
> Btw, does the limitation to have no local utils module on the current wokring dir still exist, or is this solved now?

It should be solved now.
