### ISSUE TITLE
ipython console won't start in spyder

### ISSUE THREAD

**Issue by InitialConditions** [spyder-ide/spyder#5261]
## Description of your problem
Hi all,

The ipython console within Spyder won't start up. Some sort of inport error (see below). Essentially, the ipython kernel won't start.

**What steps will reproduce the problem?**

1. Starting Spyder
2. 
3. 

**What is the expected output? What do you see instead?**
ipython console opens within Spyder

**Please provide any additional information below**
Here is the error message, which repeats several times.
Traceback (most recent call last):
File "C:\Users\eedjs\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 241, in 
main()
File "C:\Users\eedjs\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 209, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\eedjs\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 36, in 
from .iostream import IOPubThread
File "C:\Users\eedjs\Anaconda3\lib\site‑packages\ipykernel\iostream.py", line 25, in 
from IPython.utils.warn import warn
ImportError: No module named 'IPython.utils.warn'

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.5
* Qt Version:
* PyQt Version:
* Operating system: Windows 7

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by InitialConditions** [comment]
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.23.4 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  4.1.0 (OK)
numpy >=1.7      :  1.11.0 (OK)
pandas >=0.13.1  :  None (NOK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.1.0 (OK)
pygments >=2.0   :  2.1.1 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.2.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.3.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by InitialConditions** [comment]
Ok, I solved this by updating ipykernel. This was one package I had forgotten to update!
