### ISSUE TITLE
spyder 3 IPython error on startup

### ISSUE THREAD

**Issue by simonvandekar** [spyder-ide/spyder#5273]
## Description

**What steps will reproduce the problem?**

1. upgrade spyder: pip3 install --upgrade spyder
2. Run spyder3

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/local/lib/python3.6/site-packages/spyder/widgets/status.py", line 108, in update_label
    def update_label(self):
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/spyder/utils/introspection/plugin_client.py", line 184, in _heartbeat
    def _heartbeat(self):
KeyboardInterrupt
WARNING:traitlets:kernel died: 6.001477956771851
WARNING:traitlets:kernel died: 6.004408121109009

In the IPython console I get the following error:

An error ocurred while starting the kernel
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 241, in 
main()
File "/usr/local/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 209, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.6/site‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/usr/local/lib/python3.6/site‑packages/ipykernel/connect.py", line 18, in 
import jupyter_client
File "/usr/local/lib/python3.6/site‑packages/jupyter_client/__init__.py", line 4, in 
from .connect import *
File "/usr/local/lib/python3.6/site‑packages/jupyter_client/connect.py", line 22, in 
import zmq
File "/usr/local/lib/python3.6/site‑packages/zmq/__init__.py", line 34, in 
from zmq import backend
File "/usr/local/lib/python3.6/site‑packages/zmq/backend/__init__.py", line 40, in 
reraise(*exc_info)
File "/usr/local/lib/python3.6/site‑packages/zmq/utils/sixcerpt.py", line 34, in reraise
raise value
File "/usr/local/lib/python3.6/site‑packages/zmq/backend/__init__.py", line 27, in 
_ns = select_backend(first)
File "/usr/local/lib/python3.6/site‑packages/zmq/backend/select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "/usr/local/lib/python3.6/site‑packages/zmq/backend/cython/__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 241, in 
main()
File "/usr/local/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 209, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.6/site‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/usr/local/lib/python3.6/site‑packages/ipykernel/connect.py", line 18, in 
import jupyter_client
File "/usr/local/lib/python3.6/site‑packages/jupyter_client/__init__.py", line 4, in 
from .connect import *
File "/usr/local/lib/python3.6/site‑packages/jupyter_client/connect.py", line 22, in 
import zmq
File "/usr/local/lib/python3.6/site‑packages/zmq/__init__.py", line 34, in 
from zmq import backend
File "/usr/local/lib/python3.6/site‑packages/zmq/backend/__init__.py", line 40, in 
reraise(*exc_info)
File "/usr/local/lib/python3.6/site‑packages/zmq/utils/sixcerpt.py", line 34, in reraise
raise value
File "/usr/local/lib/python3.6/site‑packages/zmq/backend/__init__.py", line 27, in 
_ns = select_backend(first)
File "/usr/local/lib/python3.6/site‑packages/zmq/backend/select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "/usr/local/lib/python3.6/site‑packages/zmq/backend/cython/__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 241, in 
main()
File "/usr/local/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 209, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.6/site‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/usr/local/lib/python3.6/site‑packages/ipykernel/connect.py", line 18, in 
import jupyter_client
File "/usr/local/lib/python3.6/site‑packages/jupyter_client/__init__.py", line 4, in 
from .connect import *
File "/usr/local/lib/python3.6/site‑packages/jupyter_client/connect.py", line 22, in 
import zmq
File "/usr/local/lib/python3.6/site‑packages/zmq/__init__.py", line 34, in 
from zmq import backend
File "/usr/local/lib/python3.6/site‑packages/zmq/backend/__init__.py", line 40, in 
reraise(*exc_info)
File "/usr/local/lib/python3.6/site‑packages/zmq/utils/sixcerpt.py", line 34, in reraise
raise value
File "/usr/local/lib/python3.6/site‑packages/zmq/backend/__init__.py", line 27, in 
_ns = select_backend(first)
File "/usr/local/lib/python3.6/site‑packages/zmq/backend/select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "/usr/local/lib/python3.6/site‑packages/zmq/backend/cython/__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 241, in 
main()
File "/usr/local/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 209, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.6/site‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/usr/local/lib/python3.6/site‑packages/ipykernel/connect.py", line 18, in 
import jupyter_client
File "/usr/local/lib/python3.6/site‑packages/jupyter_client/__init__.py", line 4, in 
from .connect import *
File "/usr/local/lib/python3.6/site‑packages/jupyter_client/connect.py", line 22, in 
import zmq
File "/usr/local/lib/python3.6/site‑packages/zmq/__init__.py", line 34, in 
from zmq import backend
File "/usr/local/lib/python3.6/site‑packages/zmq/backend/__init__.py", line 40, in 
reraise(*exc_info)
File "/usr/local/lib/python3.6/site‑packages/zmq/utils/sixcerpt.py", line 34, in reraise
raise value
File "/usr/local/lib/python3.6/site‑packages/zmq/backend/__init__.py", line 27, in 
_ns = select_backend(first)
File "/usr/local/lib/python3.6/site‑packages/zmq/backend/select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "/usr/local/lib/python3.6/site‑packages/zmq/backend/cython/__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 241, in 
main()
File "/usr/local/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 209, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.6/site‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/usr/local/lib/python3.6/site‑packages/ipykernel/connect.py", line 18, in 
import jupyter_client
File "/usr/local/lib/python3.6/site‑packages/jupyter_client/__init__.py", line 4, in 
from .connect import *
File "/usr/local/lib/python3.6/site‑packages/jupyter_client/connect.py", line 22, in 
import zmq
File "/usr/local/lib/python3.6/site‑packages/zmq/__init__.py", line 34, in 
from zmq import backend
File "/usr/local/lib/python3.6/site‑packages/zmq/backend/__init__.py", line 40, in 
reraise(*exc_info)
File "/usr/local/lib/python3.6/site‑packages/zmq/utils/sixcerpt.py", line 34, in reraise
raise value
File "/usr/local/lib/python3.6/site‑packages/zmq/backend/__init__.py", line 27, in 
_ns = select_backend(first)
File "/usr/local/lib/python3.6/site‑packages/zmq/backend/select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "/usr/local/lib/python3.6/site‑packages/zmq/backend/cython/__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'

## Version and main components

On Mac Sierra OS Version 10.12.6
* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.9.1, PyQt5 5.9 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.3.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
It's an error in `zmq`, so it's not really a Spyder error.

Besides, `pip` installations are for experts or very knowledgeable users only, so it's up to you to figure it out why this error appears.

If you can't figure it out, we kindly recommend you to use Anaconda.
