### ISSUE TITLE
IPython console error: "An error occurred while starting the kernel"

### ISSUE THREAD

**Issue by burtonlm** [spyder-ide/spyder#5307]
## Description of your problem

**What steps will reproduce the problem?**

1. Open Spyder

**What is the expected output? What do you see instead?**
Expected Output: New IPython Console

Actual Output: The following error message in the IPython console window:

"An error occurred while starting the kernel
The kernel failed to start!! That's all we know... Please close this console and open a new one."

I get the same error when re-open a console as follows:
1. Go to 'Consoles' menu
2. Click 'Open an IPython console'

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 2.3.1
* Python Version: 2.7.8
* Qt Version: 4.8.6
* PyQt Version: 4.10.4
* Operating system: Windows 10 Home

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=0.13  :  2.2.0 (OK)
matplotlib >=1.0:  1.4.0 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
pyflakes >=0.5.0:  0.8.1 (OK)
pygments >=1.6  :  1.6 (OK)
pylint >=0.25   :  None (NOK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
sympy >=0.7.0   :  0.7.5 (OK)

**Comment by ccordoba12** [comment]
We don't support Spyder 2.3 anymore, sorry. Please install the latest version (3.2.3) and try again.

**Comment by eduamf** [comment]
I get the same error, but after ugrade Spyder:
```
An error ocurred while starting the kernel
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
callback(*args, **kwargs)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\tornado\stack_context.py", line 276, in null_wrapper
return fn(*args, **kwargs)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\ipykernel\kernelbase.py", line 283, in dispatcher
return self.dispatch_shell(stream, msg)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
self.pre_handler_hook()
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\ipykernel\kernelbase.py", line 248, in pre_handler_hook
self.saved_sigint_handler = signal(SIGINT, default_int_handler)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\signal.py", line 47, in signal
handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
self._handle_recv()
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
self._run_callback(callback, msg)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
callback(*args, **kwargs)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\tornado\stack_context.py", line 276, in null_wrapper
return fn(*args, **kwargs)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\ipykernel\kernelbase.py", line 283, in dispatcher
return self.dispatch_shell(stream, msg)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
self.pre_handler_hook()
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\ipykernel\kernelbase.py", line 248, in pre_handler_hook
self.saved_sigint_handler = signal(SIGINT, default_int_handler)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\signal.py", line 47, in signal
handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
ERROR:tornado.application:Exception in callback functools.partial(.null_wrapper at 0x0000000011984D08>)
Traceback (most recent call last):
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\tornado\ioloop.py", line 760, in _run_callback
ret = callback()
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\tornado\stack_context.py", line 276, in null_wrapper
return fn(*args, **kwargs)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\zmq\eventloop\zmqstream.py", line 536, in 
self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
self._handle_recv()
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
self._run_callback(callback, msg)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
callback(*args, **kwargs)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\tornado\stack_context.py", line 276, in null_wrapper
return fn(*args, **kwargs)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\ipykernel\kernelbase.py", line 283, in dispatcher
return self.dispatch_shell(stream, msg)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
self.pre_handler_hook()
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\ipykernel\kernelbase.py", line 248, in pre_handler_hook
self.saved_sigint_handler = signal(SIGINT, default_int_handler)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\signal.py", line 47, in signal
handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
Traceback (most recent call last):
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 269, in 
main()
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 265, in main
kernel.start()
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\ipykernel\kernelapp.py", line 477, in start
ioloop.IOLoop.instance().start()
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\tornado\platform\asyncio.py", line 112, in start
self.asyncio_loop.run_forever()
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\asyncio\base_events.py", line 408, in run_forever
raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```
