### ISSUE TITLE
I can´t install DRAWNOW package on anaconda environment

### ISSUE THREAD

**Issue by sripetta** [spyder-ide/spyder#5369]
## Problem Description  
I need to install drawnow package.
I tried to use Anaconda Navigator and the package don't exist.
Then, I tried to use Anaconda console:
1) conda install drawone

PackageNotFoundError: Packages missing in current channels:

  - drawnow

We have searched for the packages in the following channels:

  - https://repo.continuum.io/pkgs/main/win-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch

2) pip install drawnow
Exception:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\basecommand.py", line 215
, in main
    status = self.run(options, args)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\commands\install.py", lin
e 335, in run
    wb.build(autobuilding=True)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\wheel.py", line 749, in b
uild
    self.requirement_set.prepare_files(self.finder)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\req\req_set.py", line 380
, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\req\req_set.py", line 554
, in _prepare_file
    require_hashes
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\req\req_install.py", line
 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 465, in f
ind_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 423, in f
ind_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 568, in _
get_pages
    page = self._get_page(location)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 683, in _
get_page
    return HTMLPage.get_page(link, session=self.session)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 811, in g
et_page
    inst = cls(resp.content, resp.url, resp.headers)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\index.py", line 731, in _
_init__
    namespaceHTMLElements=False,
TypeError: parse() got an unexpected keyword argument 'transport_encoding'

I don't know what to do. It's package is very important for me because I need it to migrate from MATLAB.
I am using Windows platform, Windows 7.

**Comment by ccordoba12** [comment]
Sorry, we can't help you with this. Please open an issue in the `drawnow` repo to ask for help there:

https://github.com/stsievert/python-drawnow/issues
