### ISSUE TITLE
Error in spyder3

### ISSUE THREAD

**Issue by challenger8** [spyder-ide/spyder#5391]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

    module = _import_module_from_path(module_name, plugin_path)
    module = spec.loader.load_module(module_name)
  File "<frozen importlib._bootstrap_external>", line 396, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 817, in load_module
  File "<frozen importlib._bootstrap_external>", line 676, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 626, in _exec
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
    from .pylint import Pylint as PLUGIN_CLASS
    from .widgets.pylintgui import PylintWidget
    import pylint
ImportError: No module named 'pylint'
ERROR: 3rd party plugin import failed for `spyder_pylint`
Traceback (most recent call last):
    module = _import_module_from_path(module_name, plugin_path)
    module = spec.loader.load_module(module_name)
  File "<frozen importlib._bootstrap_external>", line 396, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 817, in load_module
  File "<frozen importlib._bootstrap_external>", line 676, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 626, in _exec
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
    from .pylint import Pylint as PLUGIN_CLASS
    from .widgets.pylintgui import PylintWidget
    import pylint
ImportError: No module named 'pylint'
ERROR: 3rd party plugin import failed for `spyder_pylint`
Traceback (most recent call last):
    module = _import_module_from_path(module_name, plugin_path)
    module = spec.loader.load_module(module_name)
  File "<frozen importlib._bootstrap_external>", line 396, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 817, in load_module
  File "<frozen importlib._bootstrap_external>", line 676, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 626, in _exec
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
    from .pylint import Pylint as PLUGIN_CLASS
    from .widgets.pylintgui import PylintWidget
    import pylint
ImportError: No module named 'pylint'
ERROR: 3rd party plugin import failed for `spyder_pylint`
Traceback (most recent call last):
    module = _import_module_from_path(module_name, plugin_path)
    module = spec.loader.load_module(module_name)
  File "<frozen importlib._bootstrap_external>", line 396, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 817, in load_module
  File "<frozen importlib._bootstrap_external>", line 676, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 626, in _exec
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
    from .pylint import Pylint as PLUGIN_CLASS
    from .widgets.pylintgui import (PYLINT_PATH, PylintWidget)
    import pylint
ImportError: No module named 'pylint'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.5.3
* Qt Versions: 5.7.1, PyQt5 5.7 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)

```

**Comment by ccordoba12** [comment]
It seems Pylint is not installed in your system. Please install it to solve this problem.

**Comment by challenger8** [comment]
Hello there

thank you for your helping.I work on interactions of proteins structure and looking for new challenge in this field .I,m interested to get join your research .how can do it?

best regards

Anvar Salehi.Gil


----- Original Message -----
