### ISSUE TITLE
Spyder - Text Editor - Scroll Bug

### ISSUE THREAD

**Issue by RaulGhizzi** [spyder-ide/spyder#5394]
## Description

**What steps will reproduce the problem?**

1. I was editing a script (nothing out of the usual) and when I scrolled down i got this errors.
2. I got the error with both mouse scroll and keyboard scroll.
3. Once I closed the file and reopened, it worked normally.

**What is the expected output? What do you see instead?**
For the editor to scroll down, but i got tons of error messages every scroll

**Please provide any additional information below**

  File "/home/gaulbg/anaconda3/envs/intexfy/lib/python3.6/site-packages/spyder/widgets/sourcecode/codeeditor.py", line 205, in <lambda>
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/gaulbg/anaconda3/envs/intexfy/lib/python3.6/site-packages/spyder/widgets/sourcecode/codeeditor.py", line 205, in <lambda>
    lambda value: self.repaint())
NameError: free variable 'self' referenced before assignment in enclosing scope
Traceback (most recent call last):
  File "/home/gaulbg/anaconda3/envs/intexfy/lib/python3.6/site-packages/spyder/widgets/sourcecode/codeeditor.py", line 534, in <lambda>
    lambda value: self.rehighlight_cells())
NameError: free variable 'self' referenced before assignment in enclosing scope
  File "/home/gaulbg/anaconda3/envs/intexfy/lib/python3.6/site-packages/spyder/widgets/sourcecode/codeeditor.py", line 205, in <lambda>
    lambda value: self.repaint())
NameError: free variable 'self' referenced before assignment in enclosing scope
Traceback (most recent call last):
  File "/home/gaulbg/anaconda3/envs/intexfy/lib/python3.6/site-packages/spyder/widgets/sourcecode/codeeditor.py", line 534, in <lambda>
    lambda value: self.rehighlight_cells())
NameError: free variable 'self' referenced before assignment in enclosing scope
  File "/home/gaulbg/anaconda3/envs/intexfy/lib/python3.6/site-packages/spyder/widgets/sourcecode/codeeditor.py", line 205, in <lambda>
    lambda value: self.repaint())
NameError: free variable 'self' referenced before assignment in enclosing scope
Traceback (most recent call last):
  File "/home/gaulbg/anaconda3/envs/intexfy/lib/python3.6/site-packages/spyder/widgets/sourcecode/codeeditor.py", line 534, in <lambda>
    lambda value: self.rehighlight_cells())
NameError: free variable 'self' referenced before assignment in enclosing scope
  File "/home/gaulbg/anaconda3/envs/intexfy/lib/python3.6/site-packages/spyder/widgets/sourcecode/codeeditor.py", line 205, in <lambda>
    lambda value: self.repaint())
NameError: free variable 'self' referenced before assignment in enclosing scope
Traceback (most recent call last):
  File "/home/gaulbg/anaconda3/envs/intexfy/lib/python3.6/site-packages/spyder/widgets/sourcecode/codeeditor.py", line 534, in <lambda>
    lambda value: self.rehighlight_cells())
NameError: free variable 'self' referenced before assignment in enclosing scope
    lambda value: self.repaint())
NameError: free variable 'self' referenced before assignment in enclosing scope
Traceback (most recent call last):
  File "/home/gaulbg/anaconda3/envs/intexfy/lib/python3.6/site-packages/spyder/widgets/sourcecode/codeeditor.py", line 534, in <lambda>
    lambda value: self.rehighlight_cells())
NameError: free variable 'self' referenced before assignment in enclosing scope

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.0.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Could you post an screenshot of the script you were editing when this error appeared?

**Comment by goanpeca** [comment]
It seems this is no longer an issue. Closing.
