### ISSUE TITLE
spyder-notebook crashed after opening a second new notebook and closing it

### ISSUE THREAD

**Issue by rmaurer-sfly** [spyder-ide/spyder#5435]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\rmaurer\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder_notebook\notebookplugin.py", line 372, in close_client
    client.shutdown_kernel()
  File "C:\Users\rmaurer\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder_notebook\widgets\client.py", line 236, in shutdown_kernel
    Traceback (most recent call last):
  File "C:\Users\rmaurer\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder_notebook\notebookplugin.py", line 372, in close_client
    client.shutdown_kernel()
  File "C:\Users\rmaurer\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder_notebook\widgets\client.py", line 236, in shutdown_kernel
    kernel_id = self.get_kernel_id()
  File "C:\Users\rmaurer\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder_notebook\widgets\client.py", line 230, in get_kernel_id
    if session['notebook']['path'] == path:
KeyError: 'notebook'
kernel_id = self.get_kernel_id()
  File "C:\Users\rmaurer\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder_notebook\widgets\client.py", line 230, in get_kernel_id
    if session['notebook']['path'] == path:
KeyError: 'notebook'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.1
*

**Comment by dalthviz** [comment]
Issue moved to [spyder-ide/spyder-notebook #119](https://github.com/spyder-ide/spyder-notebook/issues/119) via [**ZenHub**](https://www.zenhub.com/)
