### ISSUE TITLE
Error when opening Spyder from Anaconda Navigator

### ISSUE THREAD

**Issue by rbx24** [spyder-ide/spyder#5446]
Hello,
I'm trying to launch Spyder from Anaconda Navigator 1.6.8.
I tried the reset command line option but there it does not solve my issue.

**What steps will reproduce the problem?**

1. Launch Anaconda Navigator
2. Click on Launch Spyder
**What is the expected output? What do you see instead?**

Spyder should open but I get this error message instead:

_Traceback (most recent call last):
File "/Users/johndoe/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3093, in main
mainwindow = run_spyder(app, options, args)
File "/Users/johndoe/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2995, in run_spyder
main.setup()
File "/Users/johndoe/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 810, in setup
from spyder.plugins.console import Console
File "/Users/johndoe/anaconda3/lib/python3.6/site-packages/spyder/plugins/console.py", line 34, in 
from spyder.widgets.internalshell import InternalShell
File "/Users/johndoe/anaconda3/lib/python3.6/site-packages/spyder/widgets/internalshell.py", line 27, in 
from spyder.interpreter import Interpreter
File "/Users/johndoe/anaconda3/lib/python3.6/site-packages/spyder/interpreter.py", line 14, in 
import ctypes
File "/Users/johndoe/anaconda3/lib/python3.6/ctypes/__init__.py", line 7, in 
from _ctypes import Union, Structure, Array
ImportError: dlopen(/Users/johndoe/anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so, 2): Symbol not found: __PyUnicode_AsWideCharString
Referenced from: /Users/johndoe/anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so
Expected in: flat namespace
in /Users/johndoe/anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so_

## Versions and main components

* Spyder Version:3.2.3
* Python Version:3.6.3
* Qt Version:5.6.2
* PyQt Version:5.6.0
* Operating system: MacOS High Sierra 10.13

Thank you

Romain

**Comment by ccordoba12** [comment]
@mingwandroid, have you seen this error before?

**Comment by abhayap** [comment]
I am getting the same error but when I launch it from the command line in anaconda

**Comment by MarcosCarreira** [comment]
Same problem - Spyder won't open (Anaconda Navigator and terminal).

Traceback (most recent call last):
File "/Users/marcoscscarreira/anaconda/bin/spyder", line 4, in 
import spyder.app.start
File "/Users/marcoscscarreira/anaconda/lib/python3.6/site-packages/spyder/app/start.py", line 14, in 
from OpenGL import GL
File "/Users/marcoscscarreira/anaconda/lib/python3.6/site-packages/OpenGL/GL/__init__.py", line 3, in 
from OpenGL import error as _error
File "/Users/marcoscscarreira/anaconda/lib/python3.6/site-packages/OpenGL/error.py", line 12, in 
from OpenGL import platform, _configflags
File "/Users/marcoscscarreira/anaconda/lib/python3.6/site-packages/OpenGL/platform/__init__.py", line 35, in 
_load()
File "/Users/marcoscscarreira/anaconda/lib/python3.6/site-packages/OpenGL/platform/__init__.py", line 29, in _load
plugin = plugin_class()
TypeError: 'NoneType' object is not callable

Spyder 3.2.3
Python 3.6.3
MacOS Sierra 10.12.6

**Comment by ccordoba12** [comment]
@MarcosCarreira, yours is a problem with OpenGL. Please uninstall it and things should work as expected.

**Comment by MarcosCarreira** [comment]
Yes, reinstalled Anaconda and Spyder is working now.

**Comment by ccordoba12** [comment]
Great!

**Comment by mingwandroid** [comment]
No, I am unable to look into `MacOS High Sierra` bugs until we can update to that version.

**Comment by mingwandroid** [comment]
This is fixed now:

`conda update python.app`

**Comment by abhayap** [comment]
Thanks @mingwandroid it works for me now.

**Comment by rbx24** [comment]
the condo update python.app works also for me
Thank you @mingwandroid

**Comment by ccordoba12** [comment]
Great! Thanks a lot Ray for your help!

**Comment by zackankner** [comment]
I had the same problem. For me it was as simple as reverting my version of python from 3.6.3 to 3.6.2. To do this, all you have to do is go to terminal and first type: conda search python. Next input conda install python=3.6.2. Hope this helps any body with the same problem
