### ISSUE TITLE
Wrapped C/C++ object of type BaseTabs has been deleted

### ISSUE THREAD

**Issue by wefwefd** [spyder-ide/spyder#5484]
## Description

**What steps will reproduce the problem?**

1.i don`t know why it accured,i just coding as usual .
2. when i press character '.' 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 234, in show_object_info
    info = self._get_code_info('info', position, auto=auto)
  File "D:\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 202, in _get_code_info
    editor = self.editor_widget.get_current_editor()
  File "D:\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1145, in get_current_editor
    return self.tabs.currentWidget()
RuntimeError: wrapped C/C++ object of type BaseTabs has been deleted
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 220, in get_completions
    info = self._get_code_info('completions', automatic=automatic)
  File "D:\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 202, in _get_code_info
    editor = self.editor_widget.get_current_editor()
  File "D:\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1145, in get_current_editor
    return self.tabs.currentWidget()
RuntimeError: wrapped C/C++ object of type BaseTabs has been deleted
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 220, in get_comp

**Comment by ccordoba12** [comment]
Thanks for reporting. This error probably happens if you close a Project while for a code completion call.

**Comment by ccordoba12** [comment]
This no longer applies.
