### ISSUE TITLE
TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#550]
_From [sforne...@gmail.com](https://code.google.com/u/111755250279932874604/) on 2011-02-01T06:08:06Z_

What steps will reproduce the problem?

 just use spyderlib everyday. What is the expected output? What do you see instead? regularly (say about every 5-10 launches), the application does not want to start and produce the following traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/spyder.py", line 1477, in main
    mainwindow = run_spyder(app, options)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/spyder.py", line 1413, in run_spyder
    main.setup()
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/spyder.py", line 557, in setup
    self.editor = Editor(self)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/plugins/editor.py", line 427, in __init__
    None)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/plugins/__init__.py", line 196, in get_option
    return CONF.get(self.CONF_SECTION, option, default)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/userconfig.py", line 242, in get
    value = ConfigParser.get(self, section, option)
  File "/usr/lib/python2.6/ConfigParser.py", line 546, in get
    return self._interpolate(section, option, value, d)
  File "/usr/lib/python2.6/ConfigParser.py", line 589, in _interpolate
    value = value &#37; vars
TypeError: not enough arguments for format string What version of the product are you using? On what operating system? ubuntu64 10.10. spyderlib 2.06 but the problem was under other spyderlib version too (sure on 2.05). 

Please provide any additional information below

. then it suggests to run spyder with --reset option. this works but we lost all the settings that are reset to defaults... and need to reconfigure, that is annoying.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=550_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-02-06T06:42:10Z_

This issue was closed by revision c18c5952a5 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-24T07:38:20Z_

This issue was closed by revision c18c5952a53e .
