### ISSUE TITLE
Spyder3 crashed

### ISSUE THREAD

**Issue by Alcasser** [spyder-ide/spyder#5506]
## Description

**What steps will reproduce the problem?**

1. Open 5 files
2. Change from one tab to another

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/local/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 607, in setModelData
    self.get_value(index),
  File "/usr/local/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 1364, in get_value
    name = index.model().keys[index.row()]
IndexError: list index out of range

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.3
* Qt Versions: 5.9.1, PyQt5 5.9 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  1.6.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
psutil >=0.3     :  5.4.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by chicomalu** [comment]
Mine is crashing too. I'm new to spyder, so can anyone help me, please.
This is the error report I am getting.

Traceback (most recent call last):
File "E:\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3093, in main
mainwindow = run_spyder(app, options, args)
File "E:\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 2995, in run_spyder
main.setup()
File "E:\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 832, in setup
from spyder.plugins.help import Help
File "E:\Anaconda\lib\site-packages\spyder\plugins\help.py", line 32, in 
from spyder.utils.help.sphinxify import (CSS_PATH, generate_context,
File "E:\Anaconda\lib\site-packages\spyder\utils\help\sphinxify.py", line 32, in 
from sphinx.application import Sphinx
File "E:\Anaconda\lib\site-packages\sphinx\application.py", line 30, in 
from sphinx.config import Config
File "E:\Anaconda\lib\site-packages\sphinx\config.py", line 21, in 
from sphinx.util.i18n import format_date
File "E:\Anaconda\lib\site-packages\sphinx\util\i18n.py", line 19, in 
import babel.dates
File "E:\Anaconda\lib\site-packages\Babel-2.5.0-py3.6.egg\babel\__init__.py", line 20, in 
from babel.core import UnknownLocaleError, Locale, default_locale, \
ModuleNotFoundError: No module named 'babel.core'

**Comment by Alcasser** [comment]
@chicomalu Try upgrading spyder:
`pip3 install --upgrade spyder `

**Comment by ccordoba12** [comment]
@Alcasser, are you sure you didn't run anything the IPython console? I say it because the error you reported is related to the Variable Explorer.

**Comment by ccordoba12** [comment]
@chicomalu, you are mixing pip and conda packages, and that's a recipe for disaster. You most probably will need to reinstall Anaconda.

**Comment by ccordoba12** [comment]
@chicomalu, what version of Anaconda are you using?

**Comment by chicomalu** [comment]
@ccordoba12 I've downloaded the it today, but in the "about" menu it says 1.6.9.

**Comment by ccordoba12** [comment]
Are you removing `E:\Anaconda\` before reinstalling?

**Comment by chicomalu** [comment]
@ccordoba12 Yep. But I will try again and will let you know in a few..

**Comment by chicomalu** [comment]
@ccordoba12  I've just uninstall Anaconda and deleted all folders related to it, including folders in Appdata. Reinstall it and conda navigator opens fine, but when I try to open spyder, it shows the opening sreen and then crashes wit the following message
Traceback (most recent call last):
File "E:\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3093, in main
mainwindow = run_spyder(app, options, args)
File "E:\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 2995, in run_spyder
main.setup()
File "E:\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 832, in setup
from spyder.plugins.help import Help
File "E:\Anaconda\lib\site-packages\spyder\plugins\help.py", line 32, in 
from spyder.utils.help.sphinxify import (CSS_PATH, generate_context,
File "E:\Anaconda\lib\site-packages\spyder\utils\help\sphinxify.py", line 32, in 
from sphinx.application import Sphinx
File "E:\Anaconda\lib\site-packages\sphinx\application.py", line 30, in 
from sphinx.config import Config
File "E:\Anaconda\lib\site-packages\sphinx\config.py", line 21, in 
from sphinx.util.i18n import format_date
File "E:\Anaconda\lib\site-packages\sphinx\util\i18n.py", line 19, in 
import babel.dates
File "E:\Anaconda\lib\site-packages\Babel-2.5.0-py3.6.egg\babel\__init__.py", line 20, in 
from babel.core import UnknownLocaleError, Locale, default_locale, \
ModuleNotFoundError: No module named 'babel.core'

**Comment by ccordoba12** [comment]
@chicomalu, I really don't understand why that error is happening. What if you run in a terminal

    conda install -f babel

?

**Comment by chicomalu** [comment]
@ccordoba12 @ Thanks for the reply Carlos. I tried to run babel but it didnt work. it returned "CondaError: PermissionError(13, 'Permission denied')".
I'm doing it in my work computer and the network here has a proxy server. In my notebook it is working perfectly. 
I'm taking MIT's online Python course and they suggest conda. Maybe I will use my notebook only. I appreciate your time.

**Comment by ccordoba12** [comment]
@Alcasser, sorry we can't reproduce this error with your instructions.

@chicomalu, instead of installing Anaconda in `E:\`, maybe it could help to install it in `C:\`.

**Comment by amracel** [comment]
I had the same problem. I finally solved it by manually downloading babel.core and babel.dates from Github and placing them in the lib/site-packages/babel folder. Apparently these two modules are not included in the Anaconda installation. I did try reinstalling babel and that didn't help.
