### ISSUE TITLE
ver 3.2.4 error report

### ISSUE THREAD

**Issue by jomosi** [spyder-ide/spyder#5523]
## Description

**What steps will reproduce the problem?**

everytime running any small code.

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\widgets\explorer.py", line 156, in icon
    file_type, bin_name = mime_type.split('/')
ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\widgets\explorer.py", line 156, in icon
    file_type, bin_name = mime_type.split('/')
ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\widgets\explorer.py", line 156, in icon
    file_type, bin_name = mime_type.split('/')
ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\widgets\explorer.py", line 156, in icon
    file_type, bin_name = mime_type.split('/')
ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\spyder\widgets\explorer.py", line 156, in icon
    file_type, bin_name = mime_type.split('/')
ValueError: n

**Comment by ccordoba12** [comment]
Please post the code that's giving you problems.

**Comment by jomosi** [comment]
every code like this.

print('hello')

**Comment by ccordoba12** [comment]
Please post the out of

    conda list

here

**Comment by timhoffm** [comment]
likely the same as #5080

**Comment by ccordoba12** [comment]
Right, thanks for pointing it out.
