### ISSUE TITLE
spyder crashes before it launches. 

### ISSUE THREAD

**Issue by mrudulbhanu** [spyder-ide/spyder#5539]
## Description of your problem
 It started when i tried to save the file.Now it wont launch itself

1. when i launch spyder using windows launcher. 
2. when i launch using anaconda launcher.

Attached the jpg file showing the message that comes after crashing.

## Versions and main components

* Spyder Version:3.2
* Python Version:5.0
* Qt Version:
* PyQt Version:
* Operating system:windows 10

## Dependencies

I did update using update command in anaconda promt.
This is the error message I got.
Traceback (most recent call last):
File "C:\Users\mrudulbhanu\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3099, in main
mainwindow = run_spyder(app, options, args)
File "C:\Users\mrudulbhanu\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3001, in run_spyder
main.setup()
File "C:\Users\mrudulbhanu\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 819, in setup
message=_("Spyder Internal Console\n\n"
File "C:\Users\mrudulbhanu\Anaconda3\lib\site-packages\spyder\plugins\console.py", line 67, in __init__
light_background=light_background)
File "C:\Users\mrudulbhanu\Anaconda3\lib\site-packages\spyder\widgets\internalshell.py", line 141, in __init__
profile)
File "C:\Users\mrudulbhanu\Anaconda3\lib\site-packages\spyder\widgets\shell.py", line 636, in __init__
initial_message)
File "C:\Users\mrudulbhanu\Anaconda3\lib\site-packages\spyder\widgets\shell.py", line 70, in __init__
self.history = self.load_history()
File "C:\Users\mrudulbhanu\Anaconda3\lib\site-packages\spyder\widgets\shell.py", line 514, in load_history
encoding.writelines(rawhistory, self.history_filename)
File "C:\Users\mrudulbhanu\Anaconda3\lib\site-packages\spyder\utils\encoding.py", line 236, in writelines
return write(os.linesep.join(lines), filename, encoding, mode)
File "C:\Users\mrudulbhanu\Anaconda3\lib\site-packages\spyder\utils\encoding.py", line 227, in write
with open(filename, mode)
![spyder crach](https://user-images.githubusercontent.com/33002985/31863002-209ff918-b765-11e7-9e8e-ac1e0a851cac.JPG)
 as textfile:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\mrudulbhanu\\.spyder-py3\\history_internal.py'

**Comment by ccordoba12** [comment]
Please run in a system terminal (cmd.exe)

    spyder --reset

That should fix your problem.

**Comment by avaz-dot** [comment]
I have also the same problem. I have tried re-installation, reset, upgrade, restart of computer. Does not work.
