### ISSUE TITLE
Reported issued after importing Python libraries (at the beginning), running Python 3.6

### ISSUE THREAD

**Issue by NormaH** [spyder-ide/spyder#5616]
## Description

**What steps will reproduce the problem?**

1. At the beginning when importing libraries and attempting to read the files;, running Python 3.6
2.  Spyder screens come up alerting it should be reported and the program does not run (it ran before)
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\t\Anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 150, in lock
    symlink(str(os.getpid()), self.name)
  File "C:\Users\t\Anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 88, in symlink
    rename(newlinkname, filename)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\t\\.spyder-py3\\spyder.lock.1508512464094.newlink' -> 'C:\\Users\\t\\.spyder-py3\\spyder.lock'

Traceback (most recent call last):
  File "C:\Users\t\Anaconda3\lib\site-packages\spyder\app\start.py", line 109, in main
    lock_created = lock.lock()
  File "C:\Users\t\Anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 159, in lock
    pid = readlink(self.name)
  File "C:\Users\t\Anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 96, in readlink
    fObj = _open(os.path.join(filename, 'symlink'), 'rb')
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\t\\.spyder-py3\\spyder.lock\\symlink'

Traceback (most recent call last):
  File "C:\Users\t\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2446, in execute_in_external_console
    console.ex

**Comment by Jeroendevr** [comment]
Are you running this program as an user with administrator rights? If not could you try that and see what happens?

**Comment by ccordoba12** [comment]
Please open a terminal (cmd.exe), run

    spyder --reset

and try to start Spyder again.

**Comment by NormaH** [comment]
This worked.   Thanks

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it!
