### ISSUE TITLE
Spyder always crashes upon restarting

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#562]
_From [lucalf...@gmail.com](https://code.google.com/u/110172231726017228940/) on 2011-02-22T04:10:35Z_

What steps will reproduce the problem?

 1.Open spider
2.set the path
3.load a file What is the expected output? What do you see instead? Spyder works fine, but only once.  The next time it does not open anymore.  After that the "Spyder crashed during last session." dialog appears.  The spyder.py --reset workaround works: spyder starts again, but only once.  The next time it will again not start. What version of the product are you using? On what operating system? pythonxy 2.6.5.6
spyder 2.0.6 (2.0.5 had the same behavior)
windows 7 

Please provide any additional information below

. This problem did not occur at first, it suddenly appeared a few days ago.
I discovered that Spyder will restart only if I manually delete the 
outline_explorer/expanded_state = ...
entry in spyder.ini before restarting.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=562_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-02-22T01:53:11Z_

Could you try running Spyder in debug mode?
(python spyder -d)

Also there is maybe a spyder_crash.txt file somewhere which was generated by the crash.

**Comment by spyder-issues-migrator** [comment]
_From [lucalf...@gmail.com](https://code.google.com/u/110172231726017228940/) on 2011-02-22T02:38:30Z_

Running Spyder in debug mode produces:

Start of MainWindow constructor
Initializing...
End of MainWindow constructor
*** Start of MainWindow setup ***
Loading object inspector...
Loading editor...
Traceback (most recent call last):
  File "C:\Python26\Lib\site-packages\spyderlib\spyder.py", line 1477, in main
    mainwindow = run_spyder(app, options)
  File "C:\Python26\Lib\site-packages\spyderlib\spyder.py", line 1413, in run_spyder
    main.setup()
  File "C:\Python26\Lib\site-packages\spyderlib\spyder.py", line 557, in setup
    self.editor = Editor(self)
  File "C:\Python26\lib\site-packages\spyderlib\plugins\editor.py", line 429, in __init__
    self.outlineexplorer.treewidget.set_expanded_state(expanded_state)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\onecolumntree.py", line 177, in set_expanded_state
    self.restore_expanded_state()
  File "C:\Python26\lib\site-packages\spyderlib\widgets\onecolumntree.py", line 201, in restore_expanded_state
    is_expanded = self.__expanded_state.get(user_text)
AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Python26\Lib\site-packages\spyderlib\spyder.py", line 1505, in \<module>
    main()
  File "C:\Python26\Lib\site-packages\spyderlib\spyder.py", line 1483, in main
    if mainwindow is None:
UnboundLocalError: local variable 'mainwindow' referenced before assignment
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python26\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python26\Lib\site-packages\spyderlib\spyder.py", line 953, in closing
    CONF.set('main', prefix+'size', (size.width(), size.height()))
AttributeError: 'NoneType' object has no attribute 'width'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "C:\Python26\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python26\Lib\site-packages\spyderlib\spyder.py", line 953, in closing
    CONF.set('main', prefix+'size', (size.width(), size.height()))
AttributeError: 'NoneType' object has no attribute 'width'

And I also found spyder_crash.log:

Traceback (most recent call last):
  File "C:\Python26\Lib\site-packages\spyderlib\spyder.py", line 1477, in main
    mainwindow = run_spyder(app, options)
  File "C:\Python26\Lib\site-packages\spyderlib\spyder.py", line 1413, in run_spyder
    main.setup()
  File "C:\Python26\Lib\site-packages\spyderlib\spyder.py", line 557, in setup
    self.editor = Editor(self)
  File "C:\Python26\lib\site-packages\spyderlib\plugins\editor.py", line 429, in __init__
    self.outlineexplorer.treewidget.set_expanded_state(expanded_state)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\onecolumntree.py", line 177, in set_expanded_state
    self.restore_expanded_state()
  File "C:\Python26\lib\site-packages\spyderlib\widgets\onecolumntree.py", line 201, in restore_expanded_state
    is_expanded = self.__expanded_state.get(user_text)
AttributeError: 'str' object has no attribute 'get'

**Comment by spyder-issues-migrator** [comment]
_From [lucalf...@gmail.com](https://code.google.com/u/110172231726017228940/) on 2011-02-22T06:32:24Z_

Hi Pierre,

See the debug output at  code.google.

But meanwhile I discovered something that may be important: the problem
seems to be related to 1 particular file: if I close this file before
closing Spyder, then Spyder will start next time...
So hopefully this file may help you to reproduce the problem.  See
attachment.

rgds,
Luc

**Comment by spyder-issues-migrator** [comment]
_From [lucalf...@gmail.com](https://code.google.com/u/110172231726017228940/) on 2011-03-08T00:30:47Z_

I keep forgetting to close this file that causes the crashes (yes its silly, I know), so I keep experiencing the crashes.  I was only wondering: perhaps the bug is difficult for you to fix and the fix will not be available soon, but perhaps you know what it is in my file that triggers the crashes?   I would be thankful for a tip about what I could change in my code that makes the crashes disappear...

**Comment by spyder-issues-migrator** [comment]
_From [lucalf...@gmail.com](https://code.google.com/u/110172231726017228940/) on 2011-03-08T00:33:42Z_

I should also have mentioned that I'm now using 2.0.8 and it still crashes.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-03-08T10:07:39Z_

Could you please re-send the file which causing this bug?
(I can't open the link above: server error)

**Comment by spyder-issues-migrator** [comment]
_From [lucalf...@gmail.com](https://code.google.com/u/110172231726017228940/) on 2011-03-10T01:35:08Z_

here you are...

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-03-10T01:47:32Z_

Ok, this 'email' link above is clearly not working: still a server error -- I can't access to your file.

Could you please attach the file to your comment?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-03-10T23:38:09Z_

Or if you like, you may send me an email directly.

**Comment by spyder-issues-migrator** [comment]
_From [lucalf...@gmail.com](https://code.google.com/u/110172231726017228940/) on 2011-03-11T05:03:13Z_

Is this still needed?  If yes: to what address?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-03-11T05:58:54Z_

My email address is available when you click on my profile link (see every single of my comments here).

Otherwise, the *simplest* solution is to fill a comment here (i.e. *not* by email: by logging here on the Google Code website of Spyder) and to attach the script to your comment -- see the link below "Attach a file".

And yes, this is still needed: I'm more than ready to solve this issue... I'm only missing this script.

**Comment by spyder-issues-migrator** [comment]
_From [lucalf...@gmail.com](https://code.google.com/u/110172231726017228940/) on 2011-03-11T06:57:30Z_

I was only wondering if you were enable to get it from the body of my
previous email...
I'll try again sending via google code, ok.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-03-12T00:20:42Z_

This issue was closed by revision 45463050a9 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-24T07:38:31Z_

This issue was closed by revision 45463050a921 .
