### ISSUE TITLE
OpenType support missing for script 66

### ISSUE THREAD

**Issue by VanitarNordic** [spyder-ide/spyder#5664]
Hello,

When I work with spyder, I get these errors in console, but the Spyder does not crash.
Spyder = 3.2.4
Python = 3.6.3
Platform = Windows 10 x64
Installation = Anaconda

```
QWindowsWindow::setGeometry: Unable to set geometry 1260x1391+18+41 on QWidgetWindow/'MainWindowClassWindow'. Resulting geometry:  1260x1061+18+41 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 398x494, maximum size: 16777215x16777215).
  OpenType support missing for script 66
  OpenType support missing for script 66
  OpenType support missing for script 66
  OpenType support missing for script 66
  OpenType support missing for script 66
  OpenType support missing for script 66
```

**Comment by VanitarNordic** [comment]
before this incident, I had a crash which was solved using `spyder --reset` as the notification suggested

```
Traceback (most recent call last):
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\P-3.6.3-CPU\lib\site-packages\spyder\app\mainwindow.py", line 3099, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\P-3.6.3-CPU\lib\site-packages\spyder\app\mainwindow.py", line 3001, in run_spyder
    main.setup()
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\P-3.6.3-CPU\lib\site-packages\spyder\app\mainwindow.py", line 830, in setup
    self.workingdirectory = WorkingDirectory(self, self.init_workdir, main=self)
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\P-3.6.3-CPU\lib\site-packages\spyder\plugins\workingdirectory.py", line 151, in __init__
    wdhistory = self.load_wdhistory(workdir)
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\P-3.6.3-CPU\lib\site-packages\spyder\plugins\workingdirectory.py", line 223, in load_wdhistory
    wdhistory = [name for name in wdhistory if os.path.isdir(name)]
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\P-3.6.3-CPU\lib\site-packages\spyder\plugins\workingdirectory.py", line 223, in <listcomp>
    wdhistory = [name for name in wdhistory if os.path.isdir(name)]
ValueError: _isdir: embedded null character in path
```

**Comment by ccordoba12** [comment]
In what language does come your Windows 10 computer?

**Comment by ccordoba12** [comment]
This is a Qt bug:

https://bugreports.qt.io/browse/QTBUG-30213

so I think we can't do anything about it, sorry.

**Comment by VanitarNordic** [comment]
Of course it is English, but you know it is solved after I restarted the computer, but it is amazing why it has happened on its own. I just remember that I had left the computer for a few hours (not standby)

**Comment by ccordoba12** [comment]
Really weird! But thanks for letting us know that it was solved after a restart.
