### ISSUE TITLE
error

### ISSUE THREAD

**Issue by vcxiaoshuai** [spyder-ide/spyder#5672]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\software\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\site-packages\spyder\widgets\editor.py", line 1474, in save
    finfo.encoding)
  File "C:\software\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\site-packages\spyder\utils\encoding.py", line 227, in write
    with open(filename, mode) as textfile:
PermissionError: [Errno 13] Permission denied: 'D:\\cw\\workbook\\11月第1周\\sklearn2pmml_union_model_20171103.py'

Traceback (most recent call last):
  File "C:\software\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\site-packages\spyder\plugins\editor.py", line 2338, in run_file
    if editorstack.save():
  File "C:\software\WinPython-64bit-3.5.4.0Qt5\python-3.5.4.amd64\lib\site-packages\spyder\widgets\editor.py", line 1507, in save
    self)
TypeError:   QMessageBox(QMessageBox.Icon, str, str, buttons: Union[QMessageBox.StandardButtons, QMessageBox.StandardButton] = QMessageBox.NoButton, parent: QWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.Dialog|Qt.MSWindowsFixedSizeDialogHint): argument 4 has unexpected type 'EditorStack'

## Version and main components

* Spyder Version: 3.2.1.dev0 
* Python Version: 3.5.4
* Qt Versions: 5.9.1, PyQt5 5.9 on Windows

## Dependencies
```

**Comment by ccordoba12** [comment]
It seems you don't have write permissions in your `D:\` drive, so please use your `C:\` one instead.
