### ISSUE TITLE
"An error occured while starting kernel" on console output 

### ISSUE THREAD

**Issue by AaronAngJW** [spyder-ide/spyder#5686]
## Description of your problem

**What steps will reproduce the problem?**

1.  Pythonpathing to the Psychopy folder (in order to import psychopy modules) led to this error
2.  
3. 

**What is the expected output? What do you see instead?**

An error ocurred while starting the kernel
'import sitecustomize' failed; use ‑v for traceback
Traceback (most recent call last):
File "C:\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 245, in 
main()
File "C:\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 213, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Anaconda2\lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Anaconda2\lib\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "C:\Program Files (x86)\PsychoPy2\Lib\site‑packages\IPython\__init__.py", line 48, in 
from .core.application import Application
File "C:\Program Files (x86)\PsychoPy2\Lib\site‑packages\IPython\core\application.py", line 22, in 
from traitlets.config.application import Application, catch_config_error
File "C:\Program Files (x86)\PsychoPy2\Lib\site‑packages\traitlets\config\__init__.py", line 6, in 
from .application import *
File "C:\Program Files (x86)\PsychoPy2\Lib\site‑packages\traitlets\config\application.py", line 87, in 
class LevelFormatter(logging.Formatter):
AttributeError: 'module' object has no attribute 'Formatter'
'import sitecustomize' failed; use ‑v for traceback
Traceback (most recent call last):
File "C:\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 245, in 
main()
File "C:\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 213, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Anaconda2\lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Anaconda2\lib\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "C:\Program Files (x86)\PsychoPy2\Lib\site‑packages\IPython\__init__.py", line 48, in 
from .core.application import Application
File "C:\Program Files (x86)\PsychoPy2\Lib\site‑packages\IPython\core\application.py", line 22, in 
from traitlets.config.application import Application, catch_config_error
File "C:\Program Files (x86)\PsychoPy2\Lib\site‑packages\traitlets\config\__init__.py", line 6, in 
from .application import *
File "C:\Program Files (x86)\PsychoPy2\Lib\site‑packages\traitlets\config\application.py", line 87, in 
class LevelFormatter(logging.Formatter):
AttributeError: 'module' object has no attribute 'Formatter'
'import sitecustomize' failed; use ‑v for traceback
Traceback (most recent call last):
File "C:\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 245, in 
main()
File "C:\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 213, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Anaconda2\lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Anaconda2\lib\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "C:\Program Files (x86)\PsychoPy2\Lib\site‑packages\IPython\__init__.py", line 48, in 
from .core.application import Application
File "C:\Program Files (x86)\PsychoPy2\Lib\site‑packages\IPython\core\application.py", line 22, in 
from traitlets.config.application import Application, catch_config_error
File "C:\Program Files (x86)\PsychoPy2\Lib\site‑packages\traitlets\config\__init__.py", line 6, in 
from .application import *
File "C:\Program Files (x86)\PsychoPy2\Lib\site‑packages\traitlets\config\application.py", line 87, in 
class LevelFormatter(logging.Formatter):
AttributeError: 'module' object has no attribute 'Formatter'
'import sitecustomize' failed; use ‑v for traceback
Traceback (most recent call last):
File "C:\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 245, in 
main()
File "C:\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 213, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Anaconda2\lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Anaconda2\lib\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "C:\Program Files (x86)\PsychoPy2\Lib\site‑packages\IPython\__init__.py", line 48, in 
from .core.application import Application
File "C:\Program Files (x86)\PsychoPy2\Lib\site‑packages\IPython\core\application.py", line 22, in 
from traitlets.config.application import Application, catch_config_error
File "C:\Program Files (x86)\PsychoPy2\Lib\site‑packages\traitlets\config\__init__.py", line 6, in 
from .application import *
File "C:\Program Files (x86)\PsychoPy2\Lib\site‑packages\traitlets\config\application.py", line 87, in 
class LevelFormatter(logging.Formatter):
AttributeError: 'module' object has no attribute 'Formatter'
'import sitecustomize' failed; use ‑v for traceback
Traceback (most recent call last):
File "C:\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 245, in 
main()
File "C:\Anaconda2\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 213, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Anaconda2\lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Anaconda2\lib\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "C:\Program Files (x86)\PsychoPy2\Lib\site‑packages\IPython\__init__.py", line 48, in 
from .core.application import Application
File "C:\Program Files (x86)\PsychoPy2\Lib\site‑packages\IPython\core\application.py", line 22, in 
from traitlets.config.application import Application, catch_config_error
File "C:\Program Files (x86)\PsychoPy2\Lib\site‑packages\traitlets\config\__init__.py", line 6, in 
from .application import *
File "C:\Program Files (x86)\PsychoPy2\Lib\site‑packages\traitlets\config\application.py", line 87, in 
class LevelFormatter(logging.Formatter):
AttributeError: 'module' object has no attribute 'Formatter'

**Please provide any additional information below**

Removing the path to the psychopy folder fixed the issue. But that is not ideal as I need to import the modules that I need to run the stuff I am working on. This issue did not happen for my other machines, running on Spyder 2 or 3, on both windows 8 and linux ubuntu 14.04 system.

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 2.7.11
* Qt Version: 
* PyQt Version:
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0;<6.0:  5.4.1 (OK)
cython >=0.21     :  0.26.1 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.13.3 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.7.4 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.5 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
sympy >=0.7.3     :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
Sorry but you can't mix two Python installations

    C:\Anaconda2\
    C:\Program Files (x86)\PsychoPy2

as you're trying to do here. As you correctly found out, that's the root of your problem.

Instead, you have to find a way to install `psychopy` in your Anaconda installation.
