### ISSUE TITLE
No idea

### ISSUE THREAD

**Issue by BarataAP** [spyder-ide/spyder#5700]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\apbar\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 294, in data
    display = to_text_string(value)
  File "C:\Users\apbar\Anaconda2\lib\site-packages\spyder\py3compat.py", line 123, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\Users\apbar\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 294, in data
    display = to_text_string(value)
  File "C:\Users\apbar\Anaconda2\lib\site-packages\spyder\py3compat.py", line 123, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\Users\apbar\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 294, in data
    display = to_text_string(value)
  File "C:\Users\apbar\Anaconda2\lib\site-packages\spyder\py3compat.py", line 123, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)
T

**Comment by ccordoba12** [comment]
What were you doing when you got this error?

**Comment by ccordoba12** [comment]
Closing because of lack of response.
