### ISSUE TITLE
Auto-complete failed to work

### ISSUE THREAD

**Issue by versatran01** [spyder-ide/spyder#5720]
## Description

**What steps will reproduce the problem?**

1. Upgraded all python packages with pip-review

**What is the expected output? What do you see instead?**

Tab auto-complete doesn't work.

**Please provide any additional information below**

  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2920, in _dep_map
    w/metadata, .dist-info style.
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2731, in __getattr__
    else:
AttributeError: _DistInfoDistribution__dep_map

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2911, in _parsed_pkg_info
    md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2731, in __getattr__
    else:
AttributeError: _pkg_info

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/spyder/utils/introspection/manager.py", line 220, in get_completions
    info = self._get_code_info('completions', automatic=automatic)
  File "/usr/local/lib/python3.5/dist-packages/spyder/utils/introspection/manager.py", line 216, in _get_code_info
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/spyder/utils/introspection/utils.py", line 75, in __init__
    self._get_info()
  File "/usr/local/lib/python3.5/dist-packages/spyder/utils/introspection/utils.py", line 87, in _get_info
    lexer = find_lexer_for_filename(self.filename)
  File "/usr/local/lib/python3.5/dist-packages/spyder/utils/introspection/utils.py", line 180, in find_lexer_for_filename
    lexer = get_lexer_for_filename(filename)
  File "/usr/local/lib/python3.5/dist-packages/pygments/lexers/__init__.py", line 203, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "/usr/local/lib/python3.5/dist-packages/pygments/lexers/__init__.py", line 168, in find_lexer_class_for_filename
    for cls in find_plugin_lexers():
  File "/usr/local/lib/python3.5/dist-packages/pygments/plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2408, in load
    
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2431, in require
    except AttributeError as exc:
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2675, in requires
    if extra:
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2922, in _dep_map
    PKG_INFO = 'METADATA'
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2931, in _compute_dependencies
    metadata = self.get_metadata(self.PKG_INFO)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2913, in _parsed_pkg_info
    self._version = md_version
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1486, in get_metadata
    
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1595, in _get
    def _listdir(self, path):
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/setuptools-36.6.0.dist-info/METADATA'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.5.2
* Qt Versions: 5.9.1, PyQt5 5.9 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
psutil >=0.3     :  5.4.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
Please update `setuptools` and try again.

Also, please note that this is an error with an external and indirect Spyder dependency. So in reality this is not a Spyder bug and I'm closing it.

If you're unable to solve it, we recommend you to install Anaconda instead. Pip installations are for experts, i.e. people who knows how to solve these bugs with Spyder dependencies by themselves.
