### ISSUE TITLE
easy_install problem

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#573]
_From [tim.mich...@gmail.com](https://code.google.com/u/117399810383525443135/) on 2011-03-08T18:56:19Z_

Hi,
with the lasted source code I have the following problem:

easy_install .
Processing .
Running setup.py -q bdist_egg --dist-dir D:\spyderlib_2.x\egg-dist-tmp-24xdmr
Traceback (most recent call last):
  File "C:\Python26\Scripts\easy_install-script.py", line 8, in \<module>
    load_entry_point('setuptools==0.6c12dev- r88124 ', 'console_scripts', 'easy_install')()
  File "C:\Python26\lib\site-packages\setuptools-0.6c12dev_r88124-py2.6.egg\setuptools\command\easy_install.py", line 1712, in main

  File "C:\Python26\lib\site-packages\setuptools-0.6c12dev_r88124-py2.6.egg\setuptools\command\easy_install.py", line 1700, in with_ei_usage

  File "C:\Python26\lib\site-packages\setuptools-0.6c12dev_r88124-py2.6.egg\setuptools\command\easy_install.py", line 1716, in \<lambda>

  File "C:\Python26\lib\distutils\core.py", line 152, in setup
    dist.run_commands()
  File "C:\Python26\lib\distutils\dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "C:\Python26\lib\distutils\dist.py", line 995, in run_command
    cmd_obj.run()
  File "C:\Python26\lib\site-packages\setuptools-0.6c12dev_r88124-py2.6.egg\setuptools\command\easy_install.py", line 211, in run

  File "C:\Python26\lib\site-packages\setuptools-0.6c12dev_r88124-py2.6.egg\setuptools\command\easy_install.py", line 427, in easy_install

  File "C:\Python26\lib\site-packages\setuptools-0.6c12dev_r88124-py2.6.egg\setuptools\command\easy_install.py", line 476, in install_item

  File "C:\Python26\lib\site-packages\setuptools-0.6c12dev_r88124-py2.6.egg\setuptools\command\easy_install.py", line 655, in install_eggs

  File "C:\Python26\lib\site-packages\setuptools-0.6c12dev_r88124-py2.6.egg\setuptools\command\easy_install.py", line 930, in build_and_install

  File "C:\Python26\lib\site-packages\setuptools-0.6c12dev_r88124-py2.6.egg\setuptools\command\easy_install.py", line 919, in run_setup

  File "C:\Python26\lib\site-packages\setuptools-0.6c12dev_r88124-py2.6.egg\setuptools\sandbox.py", line 62, in run_setup
  File "C:\Python26\lib\site-packages\setuptools-0.6c12dev_r88124-py2.6.egg\setuptools\sandbox.py", line 105, in run
  File "C:\Python26\lib\site-packages\setuptools-0.6c12dev_r88124-py2.6.egg\setuptools\sandbox.py", line 64, in \<lambda>
  File "setup.py", line 63, in \<module>
    from spyderlib import __version__
  File "D:\spyderlib_2.x\spyderlib\__init__.py", line 33, in \<module>
    from spyderlib import qt
  File "D:\spyderlib_2.x\spyderlib\qt\__init__.py", line 17, in \<module>
    sip.setapi('QString', 1)
AttributeError: 'module' object has no attribute 'setapi'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=573_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-03-09T09:25:49Z_

This issue was closed by revision 8e46d7c6cc .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-24T07:38:28Z_

This issue was closed by revision 8e46d7c6cc76 .
