### ISSUE TITLE
FileNotFoundError when creating or opening projects

### ISSUE THREAD

**Issue by peleonard** [spyder-ide/spyder#5765]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/LZQ/anaconda/lib/python3.6/site-packages/spyder/config/user.py", line 114, in _save
    _write_file(fname)
  File "/Users/LZQ/anaconda/lib/python3.6/site-packages/spyder/config/user.py", line 110, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/LZQ/Google drive/self-learning/Python4DS/CH9-10/.spyproject/workspace.ini'

Traceback (most recent call last):
  File "/Users/LZQ/anaconda/lib/python3.6/site-packages/spyder/plugins/projects.py", line 94, in <lambda>
    triggered=lambda v: self.open_project())
  File "/Users/LZQ/anaconda/lib/python3.6/site-packages/spyder/plugins/projects.py", line 261, in open_project
    self.set_project_filenames(self.editor.get_open_filenames())
  File "/Users/LZQ/anaconda/lib/python3.6/site-packages/spyder/plugins/projects.py", line 325, in set_project_filenames
    self.current_active_project.set_recent_files(recent_files)
  File "/Users/LZQ/anaconda/lib/python3.6/site-packages/spyder/widgets/projects/type/__init__.py", line 74, in set_recent_files
    list(OrderedDict.fromkeys(recent_files)))
  File "/Users/LZQ/anaconda/lib/python3.6/site-packages/spyder/config/user.py", line 448, in set
    self._save()
  File "/Users/LZQ/anaconda/lib/python3.6/site-packages/spyder/config/user.py", line 124, in _save
    raise(e)
  File "/Users/LZQ/anaconda/lib/python3.6/site-packages/spyder/config/user.py", line 120, in _save
    _write_file(fname)
  File "/Users/LZQ/anaconda/lib/python3.6/site-packages/spyder/config/user.py", line 110, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/LZQ/Google drive/self-learning/Python4DS/CH9-10/.spyproject/workspace.ini'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
What were you doing when this error appeared?

**Comment by LEOLI3** [comment]
I tried to open a project. But that is fixed by restart the spyder. Thank you so much.

On 15 Nov 2017, at 16:23, Carlos Cordoba <notifications@github.com<mailto:notifications@github.com>> wrote:


What were you doing when this error appeared?

**Comment by CAM-Gerlach** [comment]
Seeing that the path appeared to be in a Google drive, is it possible that for whatever reason that become disconnected, inaccessible, offline etc., or a related issued which resulted in Spyder not being able to create a new file there?

**Comment by ccordoba12** [comment]
There's a good description to reproduce this on issue #6036.
