### ISSUE TITLE
qtconsole >=4.2.0:  4.1.1 (NOK)

### ISSUE THREAD

**Issue by zlinao** [spyder-ide/spyder#5806]
File "/Users/lin/anaconda/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
Traceback (most recent call last):
  File "/Users/lin/anaconda/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/Users/lin/anaconda/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    super(NamepaceBrowserWidget, self)._handle_execute_reply(msg)
  File "/Users/lin/anaconda/lib/python3.6/site-packages/qtconsole/jupyter_widget.py", line 182, in _handle_execute_reply
    super(JupyterWidget, self)._handle_execute_reply(msg)
  File "/Users/lin/anaconda/lib/python3.6/site-packages/qtconsole/frontend_widget.py", line 496, in _handle_execute_reply
    super(FrontendWidget, self)._handle_execute_reply(msg)
AttributeError: 'super' object has no attribute '_handle_execute_reply'
    handler(msg)
  File "/Users/lin/anaconda/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    super(NamepaceBrowserWidget, self)._handle_execute_reply(msg)
  File "/Users/lin/anaconda/lib/python3.6/site-packages/qtconsole/jupyter_widget.py", line 182, in _handle_execute_reply
    super(JupyterWidget, self)._handle_execute_reply(msg)
  File "/Users/lin/anaconda/lib/python3.6/site-packages/qtconsole/frontend_widget.py", line 496, in _handle_execute_reply
    super(FrontendWidget, self)._handle_execute_reply(msg)
AttributeError: 'super' object has no attribute '_handle_execute_reply'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.0.2 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  4.1.0 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.1.1 (NOK)
IPython >=4.0    :  4.0.1 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
Please update qtconsole to fix this error.

**Comment by ccordoba12** [comment]
You can do that with

    conda update qtconsole
