### ISSUE TITLE
undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by hiteshnitetc** [spyder-ide/spyder#5874]
I am unable to start spyder, getting following problem:
```
Traceback (most recent call last):
  File "/home/nd/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3093, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/nd/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2995, in run_spyder
    main.setup()
  File "/home/nd/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 847, in setup
    from spyder.plugins.editor import Editor
  File "/home/nd/anaconda3/lib/python3.6/site-packages/spyder/plugins/editor.py", line 41, in <module>
    from spyder.utils.introspection.manager import IntrospectionManager
  File "/home/nd/anaconda3/lib/python3.6/site-packages/spyder/utils/introspection/manager.py", line 21, in <module>
    from spyder.utils.introspection.plugin_client import PluginClient
  File "/home/nd/anaconda3/lib/python3.6/site-packages/spyder/utils/introspection/plugin_client.py", line 18, in <module>
    import zmq
  File "/home/nd/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 49, in <module>
    _libzmq = ctypes.CDLL(bundled[0], mode=ctypes.RTLD_GLOBAL)
  File "/home/nd/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/nd/anaconda3/lib/python3.6/site-packages/zmq/libzmq.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE
```
When i go to anaconda-navigator and then click spyder then getting following error:
```
2017-12-02 11:51:29,740 - ERROR download_api._download:192
Invalid url http://content.continuum.io/api/events

2017-12-02 11:51:29,812 - ERROR download_api._download:192
Invalid url http://content.continuum.io/api/videos

2017-12-02 11:51:30,133 - ERROR download_api._download:192
Invalid url http://content.continuum.io/api/webinars

libpng warning: iCCP: known incorrect sRGB profile
2017-12-02 11:51:45,214 - ERROR download_api._download:192
Invalid url https://continuum.io/sites/default/files/Discover the Next Generation Data Science IDE
```

## Versions and main components

* Spyder Version:3.2.3
* Python Version:3.6.2
* Operating system:ubuntu 16.04

**Comment by jitseniesen** [comment]
It looks like your installion of the `zmq` package is messed up. Try to upgrade it with `conda upgrade zmq` or if that does not work, `conda upgrade --force zmq`.

**Comment by hiteshnitetc** [comment]
Thnx  jitseniesen 
when i typed `conda upgrade zmq` and `conda upgrade --force zmq` i get :                                                                      
 ```
prefix: /home/nd/anaconda3
  package name: zmq
```

then i use: `conda install pyzmq` 


    pyzmq:  16.0.2-py36_0 --> 16.0.3-py36he2533c7_0
    zeromq: 4.1.5-0       --> 4.2.2-hbedb6e5_2     

```
Now i getting following error while starting spyder:
/home/nd/anaconda3/compiler_compat/ld: cannot find -lpthread
/home/nd/anaconda3/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/home/nd/anaconda3/bin/spyder", line 7, in <module>
    from spyder.app.start import main
  File "/home/nd/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 13, in <module>
    import zmq
  File "/home/nd/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/home/nd/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/nd/anaconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/nd/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/nd/anaconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/nd/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /home/nd/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/nd/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/../../../../../libzmq.so.5.1.2)
```
Please help.

**Comment by ccordoba12** [comment]
What happens if you now run

    conda install libgcc

and try again?

**Comment by hiteshnitetc** [comment]
Hi @ccordoba12 . When i run `conda install libgcc` i got following message:
```
# All requested packages already installed.
# packages in environment at /home/nd/anaconda3:
#
libgcc                    7.2.0                h69d50b8_2  
```
when i again run spyder i got same error in above mention comments.

**Comment by ccordoba12** [comment]
What's your Linux distro?

**Comment by hiteshnitetc** [comment]
I am ubuntu 16.04

**Comment by hiteshnitetc** [comment]
When i type `cat /etc/*-release` i got following:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by hiteshnitetc** [comment]
@jitseniesen @ccordoba12 waiting for further help.

**Comment by jitseniesen** [comment]
@hiteshnitetc I don't know, sorry. It does not look anything to do with Spyder. To check, run `import pyzmq` from a Python prompt outside Spyder; I suspect you get the same error. I don't understand how Conda handles compilers and libraries.

If it were my machine, I would wipe Anaconda and re-install it, but that is rather heavy-handed. You can try opening an issue at https://github.com/ContinuumIO/anaconda-issues , especially if you have the same error outside Spyder. Otherwise try pasting the complete output of `conda list`; maybe somebody can spot the problem from that.

**Comment by hiteshnitetc** [comment]
@ccordoba12 should i have to open this issue at [https://github.com/ContinuumIO/anaconda-issues](https://github.com/ContinuumIO/anaconda-issues)

**Comment by ccordoba12** [comment]
@hiteshnitetc, I'm almost sure you have some special setting turned on (e.g. `LD_LIBRARY_PATH` or `PATH`) that is messing with your Anaconda installation. This looks quite fishy, for instance:

    /home/nd/anaconda3/compiler_compat/ld: cannot find -lpthread
    /home/nd/anaconda3/compiler_compat/ld: cannot find -lc
    collect2: error: ld returned 1 exit status

So, I'm sorry to say it but it's up to you to figure it out this problem. You could fill an issue in Anaconda issues, but you probably won't get too far there either.
