### ISSUE TITLE
Spyder 2.08 crash

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#589]
_From [vinjv...@gmail.com](https://code.google.com/u/100700717462274045854/) on 2011-03-17T21:53:20Z_

What steps will reproduce the problem?

 1. Spyder 2.08 and earlier versions, python 2.6

Pyqt version:
\>>> QtCore.PYQT_VERSION
263940

Stack trace is below. When I run it through Wing IDE it works. Any ideas on what the problem is?

Traceback (most recent call last):
  File "spyder.py", line 1552, in main
    mainwindow = run_spyder(app, options)
  File "spyder.py", line 1467, in run_spyder
    main.setup()
  File "spyder.py", line 575, in setup
    self.editor = Editor(self)
  File ".././spyderlib/plugins/editor.py", line 408, in __init__
    self.load(filenames)
  File ".././spyderlib/plugins/editor.py", line 1470, in load
    editor = editorstack.load(filename, set_current=is_current)
  File ".././spyderlib/widgets/editor.py", line 1646, in load
    self._refresh_outlineexplorer(index, update=True)
  File ".././spyderlib/widgets/editor.py", line 1392, in _refresh_outlineexplorer
    update=update)
  File ".././spyderlib/widgets/editortools.py", line 568, in set_current_editor
    self.treewidget.set_current_editor(editor, fname, update)
  File ".././spyderlib/widgets/editortools.py", line 304, in set_current_editor
    root_item = FileRootItem(fname, self)
  File ".././spyderlib/widgets/editortools.py", line 101, in __init__
    QTreeWidgetItem.__init__(self, treewidget, QTreeWidgetItem.Type)
TypeError: an integer is required

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=589_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-03-18T02:09:56Z_

Thanks for your feedback.

Could you please print PyQt's string version:
QtCore.PYQT_VERSION_STR

**Comment by spyder-issues-migrator** [comment]
_From [vinjv...@gmail.com](https://code.google.com/u/100700717462274045854/) on 2011-03-18T13:17:59Z_

'4.7.4'

Now the app dies in wing3.2 as well and I can't run it. Any and all help
would be appreciated. I can also downgrade my Qt if that would help. What is
the recommended version?

Vineet

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-03-19T06:38:49Z_

Could you please post your complete configuration details?

**Comment by spyder-issues-migrator** [comment]
_From [vinjv...@gmail.com](https://code.google.com/u/100700717462274045854/) on 2011-03-23T10:16:27Z_

Is this in a file somewhere? what config file do you need. Looking through
google, it seems other people have had similar issues with a newer pyqt
version.

Vineet

**Comment by spyder-issues-migrator** [comment]
_From [vinjv...@gmail.com](https://code.google.com/u/100700717462274045854/) on 2011-03-25T12:58:27Z_

It works with python2.6 but when I use python2.7 which is also installed on
my machine it fails.

Vineet

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-03-26T07:37:17Z_

Thanks Vineet,

This is really helpful. I think Pierre refers to:

1. Which operating system are you using? And what version of it?
2. What's your Qt version?

I would also like to ask: why are you trying to run spyder through wing IDE? What do you gain from that?

Thanks,
Carlos

**Comment by spyder-issues-migrator** [comment]
_From [vinjv...@gmail.com](https://code.google.com/u/100700717462274045854/) on 2011-03-26T09:24:21Z_

Ubuntu 10.10


 \>>> QtCore.PYQT_VERSION_STR
'4.7.4'

I would also like to ask: why are you trying to run spyder through wing IDE?

I jut run it through wing ide when I want to debug spyderlib. It's much
better to run it directly.

I installed python2.7 in addition to python2.6 that comes with the OS. When
I run spyder with python2.7 it fails and I get all those exception. When I
run it through python2.6 it works fine.

I think the problem is that I'm using all the python2.6 extensions with
python2.7 and that is where the problem is. Thanks for all your help

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-02T06:25:25Z_

**Status:** Done
