### ISSUE TITLE
Spyder won't open

### ISSUE THREAD

**Issue by varun-bandha** [spyder-ide/spyder#5954]
It's giving me this error when I try to open spyder:
`/usr/local/lib/python2.7/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.c:212:10: fatal error: 'zmq.h' file not found`

I tried resetting spyder but that didn't solve the issue

**Please provide any additional information below**
this is the full error message:
`/usr/local/lib/python2.7/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.c:212:10: fatal error: 'zmq.h' file not found
#include 
^
1 error generated.
Error in sitecustomize; set PYTHONVERBOSE for traceback:
KeyError: 'PYTHONPATH'
Traceback (most recent call last):
File "/Users/Varun/anaconda/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 3093, in main
mainwindow = run_spyder(app, options, args)
File "/Users/Varun/anaconda/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 2995, in run_spyder
main.setup()
File "/Users/Varun/anaconda/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 847, in setup
from spyder.plugins.editor import Editor
File "/Users/Varun/anaconda/lib/python3.5/site-packages/spyder/plugins/editor.py", line 41, in 
from spyder.utils.introspection.manager import IntrospectionManager
File "/Users/Varun/anaconda/lib/python3.5/site-packages/spyder/utils/introspection/manager.py", line 21, in 
from spyder.utils.introspection.plugin_client import PluginClient
File "/Users/Varun/anaconda/lib/python3.5/site-packages/spyder/utils/introspection/plugin_client.py", line 18, in 
import zmq
File "/usr/local/lib/python2.7/site-packages/zmq/__init__.py", line 34, in 
from zmq import backend
File "/usr/local/lib/python2.7/site-packages/zmq/backend/__init__.py", line 40, in 
reraise(*exc_info)
File "/usr/local/lib/python2.7/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
raise value
File "/usr/local/lib/python2.7/site-packages/zmq/backend/__init__.py", line 27, in 
_ns = select_backend(first)
File "/usr/local/lib/python2.7/site-packages/zmq/backend/select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "/usr/local/lib/python2.7/site-packages/zmq/backend/cython/__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/zmq/backend/cython/constants.so, 2): Symbol not found: _PyInt_FromLong
Referenced from: /usr/local/lib/python2.7/site-packages/zmq/backend/cython/constants.so
Expected in: flat namespace
in /usr/local/lib/python2.7/site-packages/zmq/backend/cython/constants.so
`

**Comment by ccordoba12** [comment]
It seems you're mixing two different Python installations (`/usr/local/lib/python2.7/` and `/Users/Varun/anaconda/lib/python3.5/`) through `PYTHONPATH`.

Removing `PYTHONPATH` wherever you set it should fix this problem.

**Comment by varun-bandha** [comment]
I fixed it by deleting homebrew file at path `~/.local/lib/python3.5`
