### ISSUE TITLE
NameError: name 'Image' is not defined

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#596]
_From [rogiereg...@gmail.com](https://code.google.com/u/112534227745351719178/) on 2011-03-22T17:54:53Z_

What steps will reproduce the problem?

 1.start spyder 1.0.3-1 on Ubuntu 10.10 from command line What is the expected output? What do you see instead? I expect the application to open, however instead the following is printed on the command line:
"$ spyder
Traceback (most recent call last):
  File "/usr/bin/spyder", line 2, in \<module>
    from spyderlib import spyder
  File "/usr/lib/pymodules/python2.6/spyderlib/spyder.py", line 47, in \<module>
    from spyderlib.plugins.workspace import Workspace
  File "/usr/lib/pymodules/python2.6/spyderlib/plugins/workspace.py", line 34, in \<module>
    FILTERS = tuple(str2type(CONF.get('workspace', 'filters')))
  File "/usr/lib/pymodules/python2.6/spyderlib/config.py", line 46, in str2type
    return tuple( [eval(string) for string in strings] )
  File "<string>", line 1, in \<module>
NameError: name 'Image' is not defined What version of the product are you using? On what operating system? Spyder 1.0.3-1 on Ubuntu 10.10 

Please provide any additional information below

. No additional information. Please tell me if anything is required.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=596_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-03-22T19:51:02Z_

Spyder 1 is not maintained anymore. Please update to Spyder 2 (download it from the Downloads tab) and tell us if it works well for you.

Thanks for your interest in Spyder,
Carlos

**Comment by spyder-issues-migrator** [comment]
_From [rogiereg...@gmail.com](https://code.google.com/u/112534227745351719178/) on 2011-03-24T16:16:36Z_

Indeed Spyder 2 works without any trouble. It's a bit unfortunate that Spyder 1 is still provided in the Ubuntu Maverick Universe repository.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-03-24T20:02:26Z_

Thanks for your feedback. Unfortunately Spyder 2 was launched after Maverick, but hopefully it will be added to the Natty repos.

**Status:** WontFix
