### ISSUE TITLE
can't paste into a new external shell

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#599]
_From [christop...@gmail.com](https://code.google.com/u/105753816054647931594/) on 2011-03-28T03:34:28Z_

What steps will reproduce the problem?

 1. on OS X start a new external shell
2. try to paste some text into it 3. What is the expected output? What do you see instead? Nothing happens. If I execute a command before that, the paste works. Please use labels and text to provide additional information. I guess this is due to a missing initialization (why only OS X? On windows it works.). When i run 

$ python spyderlib/widgets/externalshell/baseshell.py

and paste into there i get

Traceback (most recent call last):
  File "/Library/Python/2.6/site-packages/spyderlib/widgets/shell.py", line 298, in keyPressEvent
    self.postprocess_keyevent(event)
  File "/Library/Python/2.6/site-packages/spyderlib/widgets/shell.py", line 799, in postprocess_keyevent
    ShellBaseWidget.postprocess_keyevent(self, event)
  File "/Library/Python/2.6/site-packages/spyderlib/widgets/shell.py", line 421, in postprocess_keyevent
    self.paste()
  File "/Library/Python/2.6/site-packages/spyderlib/widgets/shell.py", line 901, in paste
    lines = self.get_current_line_to_cursor() + text + end
  File "/Library/Python/2.6/site-packages/spyderlib/widgets/shell.py", line 158, in get_current_line_to_cursor
    return self.get_text(self.current_prompt_pos, 'cursor')
  File "/Library/Python/2.6/site-packages/spyderlib/widgets/codeeditor/base.py", line 602, in get_text
    cursor = self.__select_text(position_from, position_to)
  File "/Library/Python/2.6/site-packages/spyderlib/widgets/codeeditor/base.py", line 589, in __select_text
    cursor.setPosition(position_from)
TypeError: QTextCursor.setPosition(int, QTextCursor.MoveMode mode=QTextCursor.MoveAnchor): argument 1 has unexpected type 'NoneType'

Might be related to issue #502 .

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=599_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-02T06:36:44Z_

This issue was closed by revision 3c789eabdcc0 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-02T06:37:06Z_

This issue was closed by revision a13eba8a0719 .

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-24T07:38:45Z_

This issue was closed by revision a13eba8a0719 .
