### ISSUE TITLE
error in h5 file check

### ISSUE THREAD

**Issue by Childhoo** [spyder-ide/spyder#6006]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "h5py\_objects.pyx", line 200, in h5py._objects.ObjectID.__dealloc__
KeyError: Traceback (most recent call last):
  File "h5py\_objects.pyx", line 200, in h5py._objects.ObjectID.__dealloc__
KeyError: 0
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py\_objects.pyx", line 200, in h5py._objects.ObjectID.__dealloc__
KeyError: 0
0
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py\_objects.pyx", line 200, in h5py._objects.ObjectID.__dealloc__
KeyError: 0
Traceback (most recent call last):
  File "c:\users\chen.admin\miniconda2\envs\tensorflow\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 859, in keyPressEvent
    self.copy()
  File "c:\users\chen.admin\miniconda2\envs\tensorflow\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 1082, in copy
    obj = self.delegate.get_value(idx)
  File "c:\users\chen.admin\miniconda2\envs\tensorflow\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 1365, in get_value
    return self.get_value_func(name)
  File "c:\users\chen.admin\miniconda2\envs\tensorflow\lib\site-packages\spyder\widgets\variableexplorer\namespacebrowser.py", lin

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. The error message is incomplete; please copy and paste the entire thing here so we can properly diagnose the error; also, please describe step by step how you got this error. Without that, we won't be able to fix it, and so we'll have to close this issue in a week (7 days) from now. Thanks.

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response.
