### ISSUE TITLE
Variable Explorer crashes when scrolling

### ISSUE THREAD

**Issue by hilldog1378** [spyder-ide/spyder#6030]
## Description

**What steps will reproduce the problem?**

1.  Opened up a dataFrame in Spyder (70851,19)
2. Did a fast scroll though the data
3. 

**What is the expected output? What do you see instead?**
Was expecting to scroll though the data.  Instead, had a crash.

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 260, in get_value
    value = self.df.iat[row, column]
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1869, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py", line 1979, in _get_value
    return _maybe_box_datetimelike(series._values[index])
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\common.py", line 174, in _maybe_box_datetimelike
    value = tslib.Timestamp(value)
  File "pandas/_libs/tslib.pyx", line 390, in pandas._libs.tslib.Timestamp.__new__
  File "pandas/_libs/tslib.pyx", line 1575, in pandas._libs.tslib.convert_to_tsobject
  File "pandas/_libs/tslib.pyx", line 1669, in pandas._libs.tslib.convert_datetime_to_tsobject
  File "pandas/_libs/tslib.pyx", line 1848, in pandas._libs.tslib._check_dts_bounds
pandas._libs.tslib.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 9999-01-01 00:00:00

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 279, in data
    value = self.get_value(row, column-1)
  F

**Comment by ccordoba12** [comment]
This looks like an error in Pandas. Please post the code you use to generate the Dataframe you're trying to visualize in Spyder.

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. Please re-open if you can provide an example to reproduce this, thanks.
