### ISSUE TITLE
kernel error

### ISSUE THREAD

**Issue by danass** [spyder-ide/spyder#6124]
## Description of your problem
can't run kernel
**What steps will reproduce the problem?**

1. Open
2. Reset kernel
3. reboot, close, open

**What is the expected output? What do you see instead?**
An error ocurred while starting the kernel
Traceback (most recent call last):
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 267, in 
main()
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 235, in main
from ipykernel.kernelapp import IPKernelApp
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelapp.py", line 40, in 
from .ipkernel import IPythonKernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/ipkernel.py", line 12, in 
from .comm import CommManager
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/__init__.py", line 1, in 
from .manager import *
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/manager.py", line 15, in 
from .comm import Comm
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/comm.py", line 9, in 
from ipykernel.kernelbase import Kernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelbase.py", line 705
c password=False,
^
SyntaxError: invalid syntax
Traceback (most recent call last):
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 267, in 
main()
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 235, in main
from ipykernel.kernelapp import IPKernelApp
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelapp.py", line 40, in 
from .ipkernel import IPythonKernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/ipkernel.py", line 12, in 
from .comm import CommManager
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/__init__.py", line 1, in 
from .manager import *
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/manager.py", line 15, in 
from .comm import Comm
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/comm.py", line 9, in 
from ipykernel.kernelbase import Kernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelbase.py", line 705
c password=False,
^
SyntaxError: invalid syntax
Traceback (most recent call last):
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 267, in 
main()
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 235, in main
from ipykernel.kernelapp import IPKernelApp
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelapp.py", line 40, in 
from .ipkernel import IPythonKernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/ipkernel.py", line 12, in 
from .comm import CommManager
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/__init__.py", line 1, in 
from .manager import *
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/manager.py", line 15, in 
from .comm import Comm
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/comm.py", line 9, in 
from ipykernel.kernelbase import Kernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelbase.py", line 705
c password=False,
^
SyntaxError: invalid syntax
Traceback (most recent call last):
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 267, in 
main()
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 235, in main
from ipykernel.kernelapp import IPKernelApp
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelapp.py", line 40, in 
from .ipkernel import IPythonKernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/ipkernel.py", line 12, in 
from .comm import CommManager
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/__init__.py", line 1, in 
from .manager import *
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/manager.py", line 15, in 
from .comm import Comm
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/comm.py", line 9, in 
from ipykernel.kernelbase import Kernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelbase.py", line 705
c password=False,
^
SyntaxError: invalid syntax
Traceback (most recent call last):
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 267, in 
main()
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 235, in main
from ipykernel.kernelapp import IPKernelApp
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelapp.py", line 40, in 
from .ipkernel import IPythonKernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/ipkernel.py", line 12, in 
from .comm import CommManager
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/__init__.py", line 1, in 
from .manager import *
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/manager.py", line 15, in 
from .comm import Comm
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/comm.py", line 9, in 
from ipykernel.kernelbase import Kernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelbase.py", line 705
c password=False,
^
SyntaxError: invalid syntax
Traceback (most recent call last):
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 267, in 
main()
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 235, in main
from ipykernel.kernelapp import IPKernelApp
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelapp.py", line 40, in 
from .ipkernel import IPythonKernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/ipkernel.py", line 12, in 
from .comm import CommManager
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/__init__.py", line 1, in 
from .manager import *
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/manager.py", line 15, in 
from .comm import Comm
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/comm.py", line 9, in 
from ipykernel.kernelbase import Kernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelbase.py", line 705
c password=False,
^
SyntaxError: invalid syntax
Traceback (most recent call last):
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 267, in 
main()
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 235, in main
from ipykernel.kernelapp import IPKernelApp
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelapp.py", line 40, in 
from .ipkernel import IPythonKernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/ipkernel.py", line 12, in 
from .comm import CommManager
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/__init__.py", line 1, in 
from .manager import *
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/manager.py", line 15, in 
from .comm import Comm
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/comm.py", line 9, in 
from ipykernel.kernelbase import Kernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelbase.py", line 705
c password=False,
^
SyntaxError: invalid syntax
Traceback (most recent call last):
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 267, in 
main()
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 235, in main
from ipykernel.kernelapp import IPKernelApp
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelapp.py", line 40, in 
from .ipkernel import IPythonKernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/ipkernel.py", line 12, in 
from .comm import CommManager
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/__init__.py", line 1, in 
from .manager import *
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/manager.py", line 15, in 
from .comm import Comm
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/comm.py", line 9, in 
from ipykernel.kernelbase import Kernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelbase.py", line 705
c password=False,
^
SyntaxError: invalid syntax
Traceback (most recent call last):
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 267, in 
main()
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 235, in main
from ipykernel.kernelapp import IPKernelApp
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelapp.py", line 40, in 
from .ipkernel import IPythonKernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/ipkernel.py", line 12, in 
from .comm import CommManager
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/__init__.py", line 1, in 
from .manager import *
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/manager.py", line 15, in 
from .comm import Comm
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/comm.py", line 9, in 
from ipykernel.kernelbase import Kernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelbase.py", line 705
c password=False,
^
SyntaxError: invalid syntax
Traceback (most recent call last):
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 267, in 
main()
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 235, in main
from ipykernel.kernelapp import IPKernelApp
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelapp.py", line 40, in 
from .ipkernel import IPythonKernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/ipkernel.py", line 12, in 
from .comm import CommManager
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/__init__.py", line 1, in 
from .manager import *
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/manager.py", line 15, in 
from .comm import Comm
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/comm.py", line 9, in 
from ipykernel.kernelbase import Kernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelbase.py", line 705
c password=False,
^
SyntaxError: invalid syntax
Traceback (most recent call last):
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 267, in 
main()
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 235, in main
from ipykernel.kernelapp import IPKernelApp
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelapp.py", line 40, in 
from .ipkernel import IPythonKernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/ipkernel.py", line 12, in 
from .comm import CommManager
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/__init__.py", line 1, in 
from .manager import *
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/manager.py", line 15, in 
from .comm import Comm
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/comm.py", line 9, in 
from ipykernel.kernelbase import Kernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelbase.py", line 705
c password=False,
^
SyntaxError: invalid syntax
Traceback (most recent call last):
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 267, in 
main()
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 235, in main
from ipykernel.kernelapp import IPKernelApp
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelapp.py", line 40, in 
from .ipkernel import IPythonKernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/ipkernel.py", line 12, in 
from .comm import CommManager
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/__init__.py", line 1, in 
from .manager import *
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/manager.py", line 15, in 
from .comm import Comm
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/comm/comm.py", line 9, in 
from ipykernel.kernelbase import Kernel
File "/Users/danass/Installed/anaconda3/lib/python3.6/site‑packages/ipykernel/kernelbase.py", line 705
c password=False,
^
SyntaxError: invalid syntax

**Please provide any additional information below**
using anaconda

## Versions and main components

* Spyder Version: 3.2.5
* Python Version: 3.6.3 64
* Qt Version: 5.9.3
* PyQt Version: 5.9.2 on darwin
* Operating system: mac sierra 10.12.6

## Dependencies
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
psutil >=0.3     :  5.4.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Not sure exactly what's going on with this error, but very likely to be something specific to your machine. Please follow our [troubleshooting guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the **Basic First Aid** and then **Emergency CPR** sections, and more than likely your problem will be resolved. In case you are still having trouble, please respond with the requested items under the **Calling for Help** heading, and we'll see what we can do. Otherwise, if we don't hear from you after a week (7 days), this issue will be closed. Best of luck!

**Comment by danass** [comment]
well, i delete my install, redownloaded and reinstalled
now its ok. but i think it happened when i tried to update and now it says again that i should update to 3.2.5
but i don't feel like doing it again as it may lead me to the previous situation

**Comment by CAM-Gerlach** [comment]
Glad you got it fixed. Unless something is going on with your install, which is outside of Spyder's control, updating properly via ``conda update spyder`` shouldn't cause Spyder to crash, and we recommend always updating to the latest version as it often fixes many of the bugs people report. Best of luck!
