### ISSUE TITLE
Uncaught error when opening a pandas DataFrame with out of bounds timestamps

### ISSUE THREAD

**Issue by pfreiberger** [spyder-ide/spyder#6177]
## Description

**What steps will reproduce the problem?**

1. Create a Dataframe with list of dictionaries
2. two elements of the dictionary are type of datetime
3. Try open it in spyder via click in variable explorer
4. Throws a lot of exceptions until it crashes

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\pfr\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 260, in get_value
    value = self.df.iat[row, column]
  File "C:\Users\pfr\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1786, in __getitem__
    return self.obj.get_value(*key, takeable=self._takeable)
  File "C:\Users\pfr\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 1817, in get_value
    return _maybe_box_datetimelike(series._values[index])
  File "C:\Users\pfr\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\common.py", line 172, in _maybe_box_datetimelike
    value = tslib.Timestamp(value)
  File "pandas/_libs/tslib.pyx", line 402, in pandas._libs.tslib.Timestamp.__new__ (pandas\_libs\tslib.c:10051)
  File "pandas/_libs/tslib.pyx", line 1517, in pandas._libs.tslib.convert_to_tsobject (pandas\_libs\tslib.c:28598)
  File "pandas/_libs/tslib.pyx", line 1774, in pandas._libs.tslib._check_dts_bounds (pandas\_libs\tslib.c:32752)
pandas._libs.tslib.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 9999-01-01 00:00:00

Traceback (most recent call last):
  File "C:\Users\pfr\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widge

**Comment by pfreiberger** [comment]
It turns out the issue is related to the representable dates in pandas. My dataset time stamps with 9999-1-1 00:00:00
There is no issue when creating the dataframe, it just fails when you try to open it in the variable viewer.

**Comment by ccordoba12** [comment]
Ok, thanks for reporting. We just need to catch that error and skip to open our dataframe viewer if it happens.

**Comment by Prikers** [comment]
@pfreiberger how did you create a `DataFrame `with a `datetime `column with timestamps like "9999-1-1 00:00:00" without getting a `OutOfBoundsDatetime` in the first place from pandas? I am not able to reproduce this problem as I am not able to create such a `DataFrame`.

**Comment by pfreiberger** [comment]
Here is a minimal reproducible example:

```
import pandas as pd
from datetime import datetime
df = pd.DataFrame([{"datetime": datetime.strptime("9999-1-1T00:00", "%Y-%m-%dT%H:%M")}])
 
```'

This will work fine in the iPython console and will show you the dataframe without an issues.
Just when trying to open it in the variable viewer it keeps on crashing.

I hope this helps :)

**Comment by Prikers** [comment]
Oh I see you had to use the `datetime `library. I was using the `to_datetime()` method of a dataframe. Thanks @pfreiberger for the example. It is a feature of pandas to not be able to represent dates way in the future or in the past ([doc](https://pandas.pydata.org/pandas-docs/stable/timeseries.html#timestamp-limitations)).
So I guess it is just a matter of catching the error and representing the value as a string instead (👍) or not displaying the dataframe explorer at all with an error message.
