### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yangfeiran** [spyder-ide/spyder#6192]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/yang/anaconda/envs/py3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/yang/anaconda/envs/py3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/Users/yang/anaconda/envs/py3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 221, in _handle_execute_reply
    super(NamepaceBrowserWidget, self)._handle_execute_reply(msg)
  File "/Users/yang/anaconda/envs/py3/lib/python3.6/site-packages/qtconsole/jupyter_widget.py", line 182, in _handle_execute_reply
    super(JupyterWidget, self)._handle_execute_reply(msg)
  File "/Users/yang/anaconda/envs/py3/lib/python3.6/site-packages/qtconsole/frontend_widget.py", line 496, in _handle_execute_reply
    super(FrontendWidget, self)._handle_execute_reply(msg)
AttributeError: 'super' object has no attribute '_handle_execute_reply'
  File "/Users/yang/anaconda/envs/py3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/Users/yang/anaconda/envs/py3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 221, in _handle_execute_reply
    super(NamepaceBrowserWidget, self)._handle_execute_reply(msg)
  File "/Users/yang/anaconda/envs/py3/lib/python3.6/site-packages/qtconsole/jupyter_widget.py", line 182, in _handle_execute_reply
    super(JupyterWidget, self)._handle_execute_reply(msg)
  File "/Users/yang/anaconda/envs/py3/lib/python3.6/site-packages/qtconsole/frontend_widget.py", line 496, in _handle_execute_reply
    super(FrontendWidget, self)._handle_execute_reply(msg)
AttributeError: 'super' object has no attribute '_handle_execute_reply'
    handler(msg)
  File "/Users/yang/anaconda/envs/py3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 221, in _handle_execute_reply
    super(NamepaceBrowserWidget, self)._handle_execute_reply(msg)
  File "/Users/yang/anaconda/envs/py3/lib/python3.6/site-packages/qtconsole/jupyter_widget.py", line 182, in _handle_execute_reply
    super(JupyterWidget, self)._handle_execute_reply(msg)
  File "/Users/yang/anaconda/envs/py3/lib/python3.6/site-packages/qtconsole/frontend_widget.py", line 496, in _handle_execute_reply
    super(FrontendWidget, self)._handle_execute_reply(msg)
AttributeError: 'super' object has no attribute '_handle_execute_reply'

## Version and main components

* Spyder Version: 3.2.5 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.0.2 (OK)
pandas >=0.13.1  :  0.21.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
psutil >=0.3     :  5.4.1 (OK)
nbconvert >=4.0  :  4.1.0 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  0.23.4 (OK)
qtconsole >=4.2.0:  4.1.1 (NOK)
IPython >=4.0    :  4.0.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
You need to update console to fix this problem. Please do that by opening a system terminal and typing

    conda update qtconsole
