### ISSUE TITLE
on opening jupyter notebook

### ISSUE THREAD

**Issue by samarthiith** [spyder-ide/spyder#6193]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Kumar\Anaconda3\envs\pygdx\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Users\Kumar\Anaconda3\envs\pygdx\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "C:\Users\Kumar\Anaconda3\envs\pygdx\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte

Traceback (most recent call last):
  File "C:\Users\Kumar\Anaconda3\envs\pygdx\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\Kumar\Anaconda3\envs\pygdx\lib\site-packages\urllib3\connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Kumar\Anaconda3\envs\pygdx\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Kumar\Anaconda3\envs\pygdx\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File

**Comment by ccordoba12** [comment]
It seems your PC is blocking internet connections, so you need to add a rule to your firewall/antivirus to prevent that.
