### ISSUE TITLE
New file in file explorer error. 

### ISSUE THREAD

**Issue by daweicheng** [spyder-ide/spyder#6209]
## Description

**What steps will reproduce the problem?**

1. in file explorer, new -> file
2. input XXX.py
3. confirm

**What is the expected output? What do you see instead?**
No responding, the spider crashed. 

**Please provide any additional information below**

  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\pkg_resources\__init__.py", line 2814, in _dep_map
    return self.__dep_map
  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\pkg_resources\__init__.py", line 2625, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

Traceback (most recent call last):
  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\pkg_resources\__init__.py", line 2805, in _parsed_pkg_info
    return self._pkg_info
  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\pkg_resources\__init__.py", line 2625, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

Traceback (most recent call last):
  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\spyder\app\mainwindow.py", line 2476, in open_file
    self.editor.load(fname)
  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\spyder\plugins\editor.py", line 1913, in load
    finfo = self.editorstacks[0].load(filename, set_current=False)
  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\spyder\widgets\editor.py", line 2135, in load
    finfo = self.create_new_editor(filename, enc, text, set_current)
  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\spyder\widgets\editor.py", line 2055, in create_new_editor
    filename=fname)
  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 730, in setup_editor
    self.set_language(language, filename)
  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 835, in set_language
    sh_class = sh.guess_pygments_highlighter(filename)
  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\spyder\utils\syntaxhighlighters.py", line 1187, in guess_pygments_highlighter
    lexer = get_lexer_for_filename(filename)
  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\pygments\lexers\__init__.py", line 203, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\pygments\lexers\__init__.py", line 168, in find_lexer_class_for_filename
    for cls in find_plugin_lexers():
  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\pygments\plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\pkg_resources\__init__.py", line 2302, in load
    self.require(*args, **kwargs)
  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\pkg_resources\__init__.py", line 2325, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\pkg_resources\__init__.py", line 863, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\pkg_resources\__init__.py", line 2569, in requires
    dm = self._dep_map
  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\pkg_resources\__init__.py", line 2816, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\pkg_resources\__init__.py", line 2825, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\pkg_resources\__init__.py", line 2807, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\pkg_resources\__init__.py", line 1469, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "C:\Users\dawei\AppData\Local\Programs\Python\Python35\lib\site-packages\pkg_resources\__init__.py", line 1578, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\dawei\\appdata\\local\\programs\\python\\python35\\lib\\site-packages\\decorator-4.0.11.dist-info\\METADATA'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.5.3
* Qt Versions: 5.9.3, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.2 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Unfortunately, I could not reproduce your error on Spyder 3.2.6 and Python 3.6.3 on Windows 8.1 , following the procedure you specified. Additionally, it appears you've installed Spyder with ``pip``, which can cause various installation issues that we currently lack the resources to support. Therefore, we recommend you reinstall with an up to date version of the Anaconda distribution, and update to the latest version of Spyder. Additionally, please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch).

If it still isn't working, provide the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Calling for Help section. Otherwise, your issue will have to be closed after one week (7 days). Thanks, and best of luck!

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response.
