### ISSUE TITLE
Problem with importing eras library on Spyder 3.2.6

### ISSUE THREAD

**Issue by ahmed3205** [spyder-ide/spyder#6227]
## Description

**What steps will reproduce the problem?**

1. typing "import keras" in the ipython console or running the line "import eras" into the script file
and in both cases this error shows: "ModuleNotFoundError: No module named 'tensor flow' "
2. 
3. 
**What is the expected output? What do you see instead?**

Using TensorFlow backend.
Traceback (most recent call last):

  File "<ipython-input-3-c74e2bd4ca71>", line 1, in <module>
    import keras

  File "/Users/User/anaconda/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils

  File "/Users/User/anaconda/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils

  File "/Users/User/anaconda/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K

  File "/Users/User/anaconda/lib/python3.6/site-packages/keras/backend/__init__.py", line 83, in <module>
    from .tensorflow_backend import *

  File "/Users/User/anaconda/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

Traceback (most recent call last):

  File "<ipython-input-3-c74e2bd4ca71>", line 1, in <module>
    import keras

  File "/Users/User/anaconda/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils

  File "/Users/User/anaconda/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils

  File "/Users/User/anaconda/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K

  File "/Users/User/anaconda/lib/python3.6/site-packages/keras/backend/__init__.py", line 83, in <module>
    from .tensorflow_backend import *

  File "/Users/User/anaconda/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

**Please provide any additional information below**

  File "/Users/User/anaconda/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/Users/User/anaconda/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 417, in _handle_error
    super(ShellWidget, self)._handle_error(msg)
AttributeError: 'super' object has no attribute '_handle_error'

## Version and main components

* Spyder Version: 3.2.2 
* Python Version: 3.6.0
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Did you install ``tensorflow`` properly into the same Anaconda environment? Can you describe your setup and what you tried in more detail?

**Comment by ahmed3205** [comment]
I have a macbook pro 2011, and the Python distribution I'm using is
Anaconda. I used the tensorflow installation page (
https://www.tensorflow.org/versions/r0.12/get_started/os_setup#anaconda_installation)
  and I followed the steps for Anaconda installation. This included:

Step 1: Create a conda environment called tensorflow, so I ran the
following line in my terminal:

conda create -n tensorflow python=3.5


Step 2:Activate the environment and use conda or pip to install, so I used
pip and ran the following line in terminal:

source activate tensorflow


Step 3: Now, install TensorFlow just as you would for a regular Pip
installation. First select the correct binary to install, so I used Mac OS
X CPU binary to run the line starting with export in my terminal:

# Mac OS X, CPU only, Python 3.4 or 3.5:
(tensorflow)$ export
TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.1-py3-none-any.whl


Step 4:Finally install TensorFlow,so I first used;  pip3 install
--ignore-installed
--upgrade $TF_BINARY_URL  because I have python 3.6, however i got an error
saying ;  -bash: pip3:command not found    so I used this line in
terminal:  pip install --ignore-installed --upgrade $TF_BINARY_URL
for python 2 (which I don't have) and it installed with no errors

and now when I open spyder and *import keras* I get that error I posted. I
installe keras after closing terminal using the line:  pip install
--upgrade keras. Please help me to use the keras package with tensorflow in
spyder

Thank you

**Comment by ahmed3205** [comment]
this is my terminal window of the keras and tensorflow window

**Comment by ahmed3205** [comment]
sorry I meant keras and tensorflow install

**Comment by CAM-Gerlach** [comment]
Thanks for your detailed followup. The most important thing to test (which I should have asked you earlier, sorry) is whether you get the same behavior in qtconsole (``jupyter qtconsole``), ``IPython``, and/or the standard ``python`` interpreters. If it occurs then any of them, then the problem is almost certainly outside of Spyder's control, either something with your install, configuration, or tensorflow/keras themselves.

> -bash: pip3:command not found so I used this line in terminal: pip install --ignore-installed --upgrade $TF_BINARY_URL for python 2 (which I don't have) and it installed with no errors

To my knowledge (I honestly don't use it much, since I use ``conda`` almost exclusively) its just called ``pip`` at least in modern Anaconda, so you got that error, but not 100% sure.

> this is my terminal window of the keras and tensorflow window

Can't see anything; I don't think Github processes email attachments. You have to post from the web UI.

**Comment by ahmed3205** [comment]
Ok thank you

Ahmed Osman

**Comment by CAM-Gerlach** [comment]
Any updates? If we don't hear from you after a few days, this will end up getting closed. Thanks!
