### ISSUE TITLE
Spyder segfaults under EPD 7.0+ and Ubuntu

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#627]
_From [stefan.r...@gmail.com](https://code.google.com/u/111201285089679297844/) on 2011-04-17T12:49:37Z_

What steps will reproduce the problem?

 1. Install enthought python 7.0 (python 2.7) on ubuntu
2. Satisfy dependencies for spyderlib
3. Start spyder What is the expected output? What do you see instead? I am getting a bit of a splash screen, a short flicker of a window opening and then a segfault. What version of the product are you using? On what operating system? Ubuntu 10.04, EPD 7.0 

Please provide any additional information below

. output of python -v spyder is attached

**Attachment:** [x](http://code.google.com/p/spyderlib/issues/detail?id=627)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=627_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-17T13:07:24Z_

Could you run Spyder in debug mode?
(python spyder -d)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-17T13:10:12Z_

You may also try to run some Spyder tests which are included in the library code:
spyderlib/widgets/arrayeditor.py
spyderlib/widgets/dicteditor.py
spyderlib/widgets/editor.py
spyderlib/widgets/codeeditor/codeeditor.py

**Comment by spyder-issues-migrator** [comment]
_From [stefan.r...@gmail.com](https://code.google.com/u/111201285089679297844/) on 2011-04-17T14:25:13Z_

spyder debug mode:

$ python /usr/local/bin/spyder -d
Start of MainWindow constructor
Initializing...
End of MainWindow constructor
*** Start of MainWindow setup ***
Loading object inspector...
Loading editor...

Loading file explorer...
Loading history plugin...
Loading online help...
Loading project explorer...
Loading external console...
Loading namespace browser...
Setting up main window...
Setting up window...
*** End of MainWindow setup ***
Segmentation fault

**Comment by spyder-issues-migrator** [comment]
_From [stefan.r...@gmail.com](https://code.google.com/u/111201285089679297844/) on 2011-04-17T14:29:28Z_

and I think we have more help from running the tests you gave:
arrayeditor.py, dicteditor and editor all run.
However this happens with codeeditor:

/opt/epd-7.0-2-rh5-x86/lib/python2.7/site-packages/spyderlib/widgets$ python codeeditor/codeeditor.py
Traceback (most recent call last):
  File "codeeditor/codeeditor.py", line 1798, in \<module>
    test(fname)
  File "codeeditor/codeeditor.py", line 1780, in test
    win.load(fname)
  File "codeeditor/codeeditor.py", line 1772, in load
    self.editor.load(filename)
  File "codeeditor/codeeditor.py", line 1755, in load
    self.set_text(file(filename, 'rb').read())
IOError: [Errno 2] No such file or directory: 'C:\\Python26\\Lib\\pdb.py'

**Comment by spyder-issues-migrator** [comment]
_From [stefan.r...@gmail.com](https://code.google.com/u/111201285089679297844/) on 2011-04-17T15:58:01Z_

Although, after further tests I am bit puzzled: When I run these tests under the stock-ubuntu python (Python 2.6.5), I get the same result: i.e. 
IOError: [Errno 2] No such file or directory: 'C:\\Python26\\Lib\\pdb.py'
Segmentation fault

However, spyder itself runs OK.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-17T23:00:44Z_

This error is perfectly normal - you would have to change the opened filename in the test codeeditor/codeeditor.py on Linux (this path is related to a Windows installation).

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-20T04:59:40Z_

Did you try commenting the line "fname = r'C:\Python26\Lib\pdb.py'" and re-running this test?

What about the other tests?

**Comment by spyder-issues-migrator** [comment]
_From [stefan.r...@gmail.com](https://code.google.com/u/111201285089679297844/) on 2011-04-20T14:21:06Z_

Thanks for getting back: When commented out it happily opens and runs - all the other  tests also run fine.
So in summary: all tests (in widgets) run OK. 
Only when I start 'python spyder' do I get a segfault. Meh.

FYI, I have downloaded EPD 7.0 installed into a separate directory, pointed the links in /usr/bin/python to the new python binary and checked that the entries in sys.path make sense (i.e. they are pointing to the new and hopefully 'self-consistent' set of modules).

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-21T02:32:39Z_

Another test would be to try and run Spyder in light mode:
python spyder --light

**Comment by spyder-issues-migrator** [comment]
_From [stefan.r...@gmail.com](https://code.google.com/u/111201285089679297844/) on 2011-04-21T08:57:38Z_

If I do the light mode test (with either EPD python 2.7 or ubuntu python 2.6), I get a problem with spyder.py:

spyderlib/spyder.py", line 1531, in main
    if mainwindow is None:
UnboundLocalError: local variable 'mainwindow' referenced before assignment

This seems unrelated but I can' tell... (spyder_crash.log attached)

**Attachment:** [spyder-light.trace](http://code.google.com/p/spyderlib/issues/detail?id=627#hc10)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-23T00:41:36Z_

I see, this bug has already been fixed in v2.0.11 and v2.1.0dev (both are available through their respective Mercurial repositories).

**Comment by spyder-issues-migrator** [comment]
_From [stefan.r...@gmail.com](https://code.google.com/u/111201285089679297844/) on 2011-04-23T11:09:23Z_

I tried to look for these versions (v2.0.11 & v2.1.0dev) in the Mercurial repos: https://spyderlib.googlecode.com/hg/ The most recent tags are:
tip                             1332:ecb04480c61b
v2.0.8                          1224:cb9a8613693d
v2.0.7                          1214:08d31dc629ee

Should I just install the tip or am I looking in the wrong place? (Sorry, but my experience with hg is limited to issuing an hg command once and looking at the google web interface...)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-23T13:04:13Z_

This is the v2.1 repo: https://code.google.com/p/spyderlib/source/checkout and this is the v2.0 repo: https://code.google.com/p/spyderlib/source/checkout?repo=v20 You may try the last revision (not tagged indeed), i.e. the 'tip'. I try to keep the repositories always usable -- you may encounter bugs but not critical ones.

**Comment by spyder-issues-migrator** [comment]
_From [stefan.r...@gmail.com](https://code.google.com/u/111201285089679297844/) on 2011-04-26T14:05:02Z_

I'm afraid neither of the later releases (tip nor v2.0) changed anything. I'm still getting a segfault. It's something about my EPD setup and I am lacking the tools to pinpoint where it crashes. Back to python 2.6 might be the easiest answer.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-09-24T05:25:08Z_

Stefan,

The situation may have changed here.

1. I may now suggest you to follow a new wiki page on "how to debug a segfault": https://code.google.com/p/spyderlib/wiki/HowToDebugQtCrash 2. In the current development version (and in v2.1.0beta1 too), I have fixed a lot of segfaults lately, so it might be worth trying to upgrade your Spyder version.

Keep me posted.
-Pierre

**Comment by spyder-issues-migrator** [comment]
_From [Sol....@gmail.com](https://code.google.com/u/108920836940323815713/) on 2012-04-24T09:23:16Z_

I just wanted to point out that I'm getting the same segfault as the OP's. I'm also on ubuntu 10.04 and epd 7.1. I tried installing spyder 2.1.9. I hope there is some fix for this as spyder makes my coding tasks a pleasant experience.
-Solomon

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-24T14:02:36Z_

Ok, thanks for the feedback. 

Then could you please follow the wiki page mentioned above to help us understand what's going wrong here?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-04-24T14:40:27Z_

The thing is: how are you running spyder? Using the EPD python interpreter or the one that comes with Ubuntu (i.e. /usr/bin/python)? If your answer is the first one, then it's not surprise that Spyder crashes because EPD comes with PySide (the python bindings to Qt, the graphical toolkit in which Spyder is written) which is quite buggy. The second option (i.e. using Ubuntu's python) shouldn't give any error.

If you want to use EPD, you just have to change the interpreter used for the console, going to:

Tools > Preferences > Console > Advanced Settings > Python executable

and writing there the path to EPD's python.

**Comment by spyder-issues-migrator** [comment]
_From [stefan.r...@gmail.com](https://code.google.com/u/111201285089679297844/) on 2012-04-24T15:42:03Z_

So the segfaulting has now resolved itself for me with 
EPD 7.2-2 (64-bit) and spyder 2.1.9 and ubuntu 11.10:

If I run spyder with EPD python I do get a segfault just as Carlos (ccordoba12) promised:
(python:4730): Gtk-CRITICAL **: IA__gtk_widget_style_get: assertion `GTK_IS_WIDGET (widget)' failed
Segmentation fault

If I run spyder with the stock python, it starts. If I then set the python interpreter to EPD python, I get an ImportError as in the attached trace. That error goes away if I use the system spyderlib startup rather than the one installed in the packages of EPD python.

**Attachment:** [spyderlibg-startup](http://code.google.com/p/spyderlib/issues/detail?id=627#hc19)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-04-24T20:55:00Z_

The error probably comes from a mismatched version between what comes in EPD versus what comes in Ubuntu. If you're using 10.04 there surely has to be a mismatch because it's too old.

I'm very very sorry but there is nothing else we can do to support EPD but just wait until they ship with a PySide version that works with Spyder too. The other alternative is for you to update to 12.04, the new LTS (when it's ready, of course). It'll probably fix the ImportError...

Pierre, do you think we can do something else?

**Summary:** Spyder segfaults under EPD 7.0+ and Ubuntu

**Comment by spyder-issues-migrator** [comment]
_From [lisaandr...@gmail.com](https://code.google.com/u/104903765775459874735/) on 2012-04-24T21:02:36Z_

Ubuntu 12.04 LTS is just around the corner (coming out in a day) and I can make do with the situation as it is. No need to do anything, at least not on my account. I was just reporting/updating this in case someone finds this a useful data point in the ongoing development.

Thanks, Stefan

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-04-25T06:38:22Z_

I'm not really sure if this will fix your problem, but if it does please let us know so we can add a note to our installation instructions

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-28T05:07:40Z_

Ok, please let us know if the new Ubuntu LTS release (which is now available) is helping or not.

**Comment by spyder-issues-migrator** [comment]
_From [stefan.r...@gmail.com](https://code.google.com/u/111201285089679297844/) on 2012-06-22T17:36:21Z_

SO, I finally got around to installing 12.04 LTS. Unfortunately, the situation has not really improved. 

However, 12.04 comes with spyderlib 2.1.9 which will do. When I try to bootstrap spyder 2.2.0dev using EPD python it segfaults as before (presumably due to PySide instability in the version shipped by EPD). When I run it with ubuntu's python it works except during the startup I get ImportErrors (different from comment 19 but similar in taste and texture).

When I then change to the default startup those ImportErrors disappear and I am then running the newest spyder using ubuntu's python while using the EPD python in the console. I'd call this a working solution until EPD improves PySide.

**Comment by spyder-issues-migrator** [comment]
_From [christop...@gmail.com](https://code.google.com/u/105753816054647931594/) on 2012-12-13T20:34:09Z_

I also see erratic (sometimes there sometimes not) segfaults in the following configuration during startup:

Spyder 2.2.0dev (2440+:d4ba28eadeb5+), MacOSX 10.8.2, Python 2.7.3 64bits, Qt 4.7.4, PySide 1.1.0

Stack trace attached. All libraries (except QT itself) where built here.

Cheers,
Christoph

**Attachment:** [spyder_stacktrace.rtf](http://code.google.com/p/spyderlib/issues/detail?id=627#hc25)

**Comment by spyder-issues-migrator** [comment]
_From [zho...@gmail.com](https://code.google.com/u/109498967421423882018/) on 2012-12-31T22:34:32Z_

After hours of trial and error I found installing Qt4 and then PyQt4 under EPD enables me to use EPD with Spyder. To give proper credit, several of the steps below borrowed from tips that were found online.

Following steps are done on Ubuntu 12.04 LTS, EPD 7.3-2 (64-bit) with Python 2.7.3, and Spyder 2.1.11

0. If you have installed Spyderlib from Ubuntu Software Center, uninstall it, and make sure all shortcuts to it are deleted.

1. Install EPD. Assume it is installed to /home/epd/. Add /home/epd/bin to $PATH. There are many ways to do so, but the one that matches Ubuntu style (reference) is:

Create a new file epd.sh under /etc/profile.d/

sudo nano /etc/profile.d/epd.sh

add there

export PATH=$PATH:/home/epd/bin

and give right on executable

sudo chmod a+x /etc/profile.d/epd.sh

Note EPD Python path is added after $PATH which contains /usr/bin that points to Ubuntu system Python. This is deliberate as some programs (e.g. MySQL Workbench) use packages that are included in the system Python but not in EPD Python, and you don't want to break those.

2. Install PyQt4 under EPD python:

(1) Download, unpack/decompress, make, and install Qt4 to have "qmake" and related libraries. I used version 4.8.4.

Download link: http://qt-project.org/downloads Installation instruction: http://qt-project.org/doc/qt-4.8/install-x11.html Before running ./configure, make sure the following command is executed first, otherwise there may be a failure "Basic XLib functionality test failed"

sudo apt-get install libx11-dev libfreetype6-dev libavahi-gobject-dev libSM-dev libXrender-dev libfontconfig-dev libXext-dev

The other 3 commands I used to make and install Qt4 (see installation instruction for full detail):

sudo ./configure
sudo make
sudo make install

The step of making Qt4 make take very long (a couple hours).

(2) Download, unpack/decompress, make, and install sip:

Download link: http://www.riverbankcomputing.com/software/sip/ Installation instruction: http://www.riverbankcomputing.com/static/Docs/sip4/installation.html The 3 key commands used:

sudo /home/epd/bin/python configure.py
sudo make
sudo make install

(3) Download and install PyQt4:

Download link: http://www.riverbankcomputing.com/software/pyqt/download Installation instruction: http://www.riverbankcomputing.com/static/Docs/PyQt4/html/installation.html Note: even if you have configured PATH properly for locating qmake (e.g. by adding /usr/local/Trolltech/Qt-4.8.4/bin to the file /etc/profile.d/epd.sh which was created in step 1 above), somehow you may still need to specify the path to find qmake for configure.py, i.e. you should use

sudo /home/epd/bin/python configure.py -q /usr/local/Trolltech/Qt-4.8.4/bin/qmake

The remaining 2 key commands are, again,

sudo make
sudo make install


3. Download and install Spyder:
Download link: https://code.google.com/p/spyderlib/downloads/list To install:
sudo /home/epd/bin/python setup.py install

To run:
/home/epd/bin/python /home/epd/bin/spyder&

Make a shortcut of this command for fast launch later.

4. If you had installed Spyderlib from Ubuntu Software Center and uninstalled, now check again to make sure under Spyder "Tools", "Preferences", "Console", "Advanced settings", "PYTHONSTARTUP replacement" is pointing to the startup script under Spyderlib in EPD (/home/epd/lib/python2.7/site-packages/spyderlib/scientific_startup.py), NOT the old Spyder under /usr/...

Enjoy!!

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-01-02T06:04:17Z_

Thanks for sharing these informations.

**Status:** Done
