### ISSUE TITLE
spyder light crashes

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#630]
_From [asterbom...@gmail.com](https://code.google.com/u/111310574906366460267/) on 2011-04-18T07:27:15Z_

What steps will reproduce the problem?

 1.open the python(x,y) home dialog
2.select Spyder --light 
3.press the button to start it What is the expected output? What do you see instead? The dialog "Spyder crashed during last session" appears. 

Please provide any additional information below

. spyder_crash.log contains:

Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\spyderlib\spyder.py", line 1525, in main
    mainwindow = run_spyder(app, options)
  File "C:\Python26\lib\site-packages\spyderlib\spyder.py", line 1461, in run_spyder
    main.setup()
  File "C:\Python26\lib\site-packages\spyderlib\spyder.py", line 773, in setup
    self.setup_layout(default=False)
  File "C:\Python26\lib\site-packages\spyderlib\spyder.py", line 799, in setup_layout
    is_maximized =  get_func('main', prefix+'is_maximized')
  File "C:\Python26\lib\site-packages\spyderlib\userconfig.py", line 238, in get
    raise RuntimeError("Unknown option &#37;r" &#37; option)
RuntimeError: Unknown option 'lightwindow/is_maximized'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=630_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-20T13:21:14Z_

This issue was closed by revision 81349f7afd69 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-20T13:21:14Z_

This issue was closed by revision d559253cf944 .

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-24T07:38:52Z_

This issue was closed by revision d559253cf944 .
