### ISSUE TITLE
Please look into this matter. I tried to update Spyder as well as qtconsole but still this error keeps coming.

### ISSUE THREAD

**Issue by AniketFadia** [spyder-ide/spyder#6315]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Aniket\Anaconda3\envs\py271\lib\site-packages\qtconsole\base_frontend_mixin.py", line 157, in _dispatch
    handler(msg)
  File "C:\Users\Aniket\Anaconda3\envs\py271\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 221, in _handle_execute_reply
    super(NamepaceBrowserWidget, self)._handle_execute_reply(msg)
  File "C:\Users\Aniket\Anaconda3\envs\py271\lib\site-packages\qtconsole\jupyter_widget.py", line 182, in _handle_execute_reply
    super(JupyterWidget, self)._handle_execute_reply(msg)
  File "C:\Users\Aniket\Anaconda3\envs\py271\lib\site-packages\qtconsole\frontend_widget.py", line 463, in _handle_execute_reply
    super(FrontendWidget, self)._handle_execute_reply(msg)
AttributeError: 'super' object has no attribute '_handle_execute_reply'
Traceback (most recent call last):
  File "C:\Users\Aniket\Anaconda3\envs\py271\lib\site-packages\qtconsole\base_frontend_mixin.py", line 157, in _dispatch
    handler(msg)
Traceback (most recent call last):
  File "C:\Users\Aniket\Anaconda3\envs\py271\lib\site-packages\qtconsole\base_frontend_mixin.py", line 157, in _dispatch
    handler(msg)
  File "C:\Users\Aniket\Anaconda3\envs\py271\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 221, in _handle_execute_reply
    super(NamepaceBrowserWidget, self)._handle_execute_reply(msg)
  File "C:\Users\Aniket\Anaconda3\envs\py271\lib\site-packages\qtconsole\jupyter_widget.py", line 182, in _handle_execute_reply
    super(JupyterWidget, self)._handle_execute_reply(msg)
  File "C:\Users\Aniket\Anaconda3\envs\py271\lib\site-packages\qtconsole\frontend_widget.py", line 463, in _handle_execute_reply
    super(FrontendWidget, self)._handle_execute_reply(msg)
AttributeError: 'super' object has no attribute '_handle_execute_reply'
  File "C:\Users\Aniket\Anaconda3\envs\py271\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 221, in _handle_execute_reply
    super(NamepaceBrowserWidget, self)._handle_execute_reply(msg)
  File "C:\Users\Aniket\Anaconda3\envs\py271\lib\site-packages\qtconsole\jupyter_widget.py", line 182, in _handle_execute_reply
    super(JupyterWidget, self)._handle_execute_reply(msg)
  File "C:\Users\Aniket\Anaconda3\envs\py271\lib\site-packages\qtconsole\frontend_widget.py", line 463, in _handle_execute_reply
    super(FrontendWidget, self)._handle_execute_reply(msg)
AttributeError: 'super' object has no attribute '_handle_execute_reply'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.3 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26.1 (OK)
qtconsole >=4.2.0 :  4.0.1 (NOK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.4 (OK)

```

**Comment by jitseniesen** [comment]
Your attempt to update qtconsole must have been unsuccessful, as your report indicates that you have version 4.0.1 of qtconsole installed while Spyder requires version 4.2.0 of qtconsole. This issue tracker is for bugs in Spyder, not for installation problems with other software, so I will close this issue. 

Please find a more appropriate place to ask for support. I suggest you also provide more details: how did you try to upgrade qtconsole and what happened?
