### ISSUE TITLE
AttributeError on import telegram, even though there is now error in other python consoles

### ISSUE THREAD

**Issue by Rudgas** [spyder-ide/spyder#6378]
## Description of your problem

Package in question: python-telegram-bot
I get an "AttributeError: module 'telegram' has no attribute 'vendor'" even though the module telegram has this attribute.

**What steps will reproduce the problem?**

1.  import telegram (in IPython Console)
2.  import telegram (in script via any execution command)
3. 

**What is the expected output? What do you see instead?**
Expected output is none for import

Error:
In [2]: import telegram
`Traceback (most recent call last):

  File "<ipython-input-2-e2e4c7fd4697>", line 1, in <module>
    import telegram

  File "/home/user/.local/lib/python3.6/site-packages/telegram/__init__.py", line 94, in <module>
    from .bot import Bot

  File "/home/user/.local/lib/python3.6/site-packages/telegram/bot.py", line 37, in <module>
    from telegram.utils.request import Request

  File "/home/user/.local/lib/python3.6/site-packages/telegram/utils/request.py", line 34, in <module>
    import telegram.vendor.ptb_urllib3.urllib3 as urllib3

AttributeError: module 'telegram' has no attribute 'vendor'`

**Please provide any additional information below**
if I run python via Geany or from Bash it works as expected. Specifically tried:
"from telegram import vendor" which works as well

Output from dir(telegram):
['Animation', 'Audio', 'Bot', 'CallbackGame', 'CallbackQuery', 'Chat', 'ChatAction', 'ChatMember', 'ChatPhoto', 'ChosenInlineResult', 'Contact', 'Document', 'File', 'ForceReply', 'Game', 'GameHighScore', 'InlineKeyboardButton', 'InlineKeyboardMarkup', 'InlineQuery', 'InlineQueryResult', 'InlineQueryResultArticle', 'InlineQueryResultAudio', 'InlineQueryResultCachedAudio', 'InlineQueryResultCachedDocument', 'InlineQueryResultCachedGif', 'InlineQueryResultCachedMpeg4Gif', 'InlineQueryResultCachedPhoto', 'InlineQueryResultCachedSticker', 'InlineQueryResultCachedVideo', 'InlineQueryResultCachedVoice', 'InlineQueryResultContact', 'InlineQueryResultDocument', 'InlineQueryResultGame', 'InlineQueryResultGif', 'InlineQueryResultLocation', 'InlineQueryResultMpeg4Gif', 'InlineQueryResultPhoto', 'InlineQueryResultVenue', 'InlineQueryResultVideo', 'InlineQueryResultVoice', 'InputContactMessageContent', 'InputFile', 'InputLocationMessageContent', 'InputMedia', 'InputMediaPhoto', 'InputMediaVideo', 'InputMessageContent', 'InputTextMessageContent', 'InputVenueMessageContent', 'Invoice', 'KeyboardButton', 'LabeledPrice', 'Location', 'MAX_CAPTION_LENGTH', 'MAX_FILESIZE_DOWNLOAD', 'MAX_FILESIZE_UPLOAD', 'MAX_MESSAGES_PER_MINUTE_PER_GROUP', 'MAX_MESSAGES_PER_SECOND', 'MAX_MESSAGES_PER_SECOND_PER_CHAT', 'MAX_MESSAGE_LENGTH', 'MaskPosition', 'Message', 'MessageEntity', 'OrderInfo', 'ParseMode', 'PhotoSize', 'PreCheckoutQuery', 'ReplyKeyboardMarkup', 'ReplyKeyboardRemove', 'ReplyMarkup', 'SUPPORTED_WEBHOOK_PORTS', 'ShippingAddress', 'ShippingOption', 'ShippingQuery', 'Sticker', 'StickerSet', 'SuccessfulPayment', 'TelegramError', 'TelegramObject', 'Update', 'User', 'UserProfilePhotos', 'Venue', 'Video', 'VideoNote', 'Voice', 'WebhookInfo', '__all__', '__author__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'base', 'bot', 'callbackquery', 'chat', 'chataction', 'chatmember', 'choseninlineresult', 'constants', 'error', 'files', 'forcereply', 'games', 'inline', 'keyboardbutton', 'message', 'messageentity', 'parsemode', 'payment', 'replykeyboardmarkup', 'replykeyboardremove', 'replymarkup', 'update', 'user', 'userprofilephotos', 'utils', 'vendor', 'version', 'webhookinfo']`

## Versions and main components

* Spyder Version: 3.2.6
* Python Version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
* Qt Version:
* PyQt Version:
* Operating system: LINUX 4.14.15-1-ARCH x86_64

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.3 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.0 (OK)
pandas >=0.13.1  :  None (NOK)
psutil >=0.3     :  5.4.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
Please run in a system terminal

    spyder --reset

and try again.

**Comment by Rudgas** [comment]
Did so, produces this error on `import telegram` in ipython console:

```
Python 3.6.4 (default, Jan  5 2018, 02:35:40)
Type "copyright", "credits" or "license" for more information.

IPython 6.2.1 -- An enhanced Interactive Python.

import telegram
Traceback (most recent call last):

  File "<ipython-input-1-e2e4c7fd4697>", line 1, in <module>
    import telegram

  File "/home/user/.local/lib/python3.6/site-packages/telegram/__init__.py", line 94, in <module>
    from .bot import Bot

  File "/home/user/.local/lib/python3.6/site-packages/telegram/bot.py", line 37, in <module>
    from telegram.utils.request import Request

  File "/home/user/.local/lib/python3.6/site-packages/telegram/utils/request.py", line 35, in <module>
    import telegram.vendor.ptb_urllib3.urllib3.contrib.appengine as appengine

  File "/home/user/.local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/contrib/appengine.py", line 63, in <module>
    from google.appengine.api import urlfetch

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load

  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 890, in _find_spec

  File "<frozen importlib._bootstrap>", line 864, in _find_spec_legacy

  File "/usr/lib/python3.6/site-packages/pyximport/pyximport.py", line 253, in find_module
    fp, pathname, (ext,mode,ty) = imp.find_module(fullname,package_path)

  File "/usr/lib/python3.6/imp.py", line 271, in find_module
    "not {}".format(type(path)))

RuntimeError: 'path' must be None or a list, not <class '_frozen_importlib_external._NamespacePath'>
```

**Comment by Rudgas** [comment]
Thanks, will check it.
