### ISSUE TITLE
Error in starting kernel

### ISSUE THREAD

**Issue by andreagrusso** [spyder-ide/spyder#6388]
## Description of your problem
Spyder is not working, because it cannot start the kernel. What's happening? I've used it several times in the last months without any problem..
**What steps will reproduce the problem?**

1. When I open Spyder 
2. 
3. 

**What is the expected output? What do you see instead?**
An ipython console in the Spyder GUI is the expected output. However, I see a window with an error message (see below)

An error ocurred while starting the kernel
Traceback (most recent call last):
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/spyder/utils/ipython/start_kernel.py", line 236, in main
from ipykernel.kernelapp import IPKernelApp
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/ipykernel/connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/IPython/__init__.py", line 48, in 
from .core.application import Application
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/IPython/core/application.py", line 18, in 
import logging
File "/usr/lib/python2.7/dist‑packages/psychopy/logging.py", line 37, in 
from psychopy import clock
ImportError: No module named psychopy
Traceback (most recent call last):
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/spyder/utils/ipython/start_kernel.py", line 236, in main
from ipykernel.kernelapp import IPKernelApp
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/ipykernel/connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/IPython/__init__.py", line 48, in 
from .core.application import Application
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/IPython/core/application.py", line 18, in 
import logging
File "/usr/lib/python2.7/dist‑packages/psychopy/logging.py", line 37, in 
from psychopy import clock
ImportError: No module named psychopy
Traceback (most recent call last):
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/spyder/utils/ipython/start_kernel.py", line 236, in main
from ipykernel.kernelapp import IPKernelApp
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/ipykernel/connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/IPython/__init__.py", line 48, in 
from .core.application import Application
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/IPython/core/application.py", line 18, in 
import logging
File "/usr/lib/python2.7/dist‑packages/psychopy/logging.py", line 37, in 
from psychopy import clock
ImportError: No module named psychopy
Traceback (most recent call last):
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/spyder/utils/ipython/start_kernel.py", line 236, in main
from ipykernel.kernelapp import IPKernelApp
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/ipykernel/connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/IPython/__init__.py", line 48, in 
from .core.application import Application
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/IPython/core/application.py", line 18, in 
import logging
File "/usr/lib/python2.7/dist‑packages/psychopy/logging.py", line 37, in 
from psychopy import clock
ImportError: No module named psychopy
Traceback (most recent call last):
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/spyder/utils/ipython/start_kernel.py", line 236, in main
from ipykernel.kernelapp import IPKernelApp
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/ipykernel/connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/IPython/__init__.py", line 48, in 
from .core.application import Application
File "/home/andrea/miniconda2/lib/python2.7/site‑packages/IPython/core/application.py", line 18, in 
import logging
File "/usr/lib/python2.7/dist‑packages/psychopy/logging.py", line 37, in 
from psychopy import clock
ImportError: No module named psychopy

**Please provide any additional information below**
I've tried to uninstall Anaconda by deleting its folder, and also all the spyder folders, but then, after downloading and re-installing a new version of Anaconda, the problem remains the same.

## Versions and main components

* Spyder Version: 3
* Python Version: 2.7
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Ubuntu 12.04

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0;<6.0:  5.4.1 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.11.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  None (NOK)
pandas >=0.13.1   :  None (NOK)
psutil >=0.3      :  5.4.3 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.8.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.6.6 (OK)
sympy >=0.7.3     :  None (NOK)

**Comment by ccordoba12** [comment]
Please run in a system terminal (xterm)

    spyder --reset

and try again.

**Comment by andreagrusso** [comment]
Thank you! It worked!
