### ISSUE TITLE
Popup Error Repeating

### ISSUE THREAD

**Issue by acudworth3** [spyder-ide/spyder#6443]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\a0c00vw\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 277, in data
Traceback (most recent call last):
  File "C:\Users\a0c00vw\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 277, in data
Traceback (most recent call last):
  File "C:\Users\a0c00vw\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 277, in data
    return to_qvariant(to_text_string(self.df_index[row]))
  File "C:\Users\a0c00vw\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\py3compat.py", line 123, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xca in position 5: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\Users\a0c00vw\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 277, in data
    return to_qvariant(to_text_string(self.df_index[row]))
  File "C:\Users\a0c00vw\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\py3compat.py", line 123, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decod

**Comment by CAM-Gerlach** [comment]
You already reported this error as #6442 . Therefore, this one will be closed.
