### ISSUE TITLE
Problem opening pandas dataframe in variable explorer

### ISSUE THREAD

**Issue by Kritika101** [spyder-ide/spyder#6454]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\kritika.sharma1\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 260, in get_value
    value = self.df.iat[row, column]
  File "C:\Users\kritika.sharma1\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1786, in __getitem__
    return self.obj.get_value(*key, takeable=self._takeable)
  File "C:\Users\kritika.sharma1\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 1817, in get_value
    return _maybe_box_datetimelike(series._values[index])
  File "C:\Users\kritika.sharma1\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\common.py", line 172, in _maybe_box_datetimelike
    value = tslib.Timestamp(value)
  File "pandas/_libs/tslib.pyx", line 402, in pandas._libs.tslib.Timestamp.__new__ (pandas\_libs\tslib.c:10051)
  File "pandas/_libs/tslib.pyx", line 1517, in pandas._libs.tslib.convert_to_tsobject (pandas\_libs\tslib.c:28598)
  File "pandas/_libs/tslib.pyx", line 1774, in pandas._libs.tslib._check_dts_bounds (pandas\_libs\tslib.c:32752)
pandas._libs.tslib.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1-01-01 00:00:00

Traceback (most recent call last):
  File "C:\Users\kritika.sharma1\AppData\Local\Con

**Comment by jitseniesen** [comment]
Thanks for your report. I am pretty sure this is the same issue that was previous reported in #6177. A fix is included in the current development version which will be released as Spyder version 3.2.7 shortly.

Therefore I'll be closing this issue.
