### ISSUE TITLE
Errors when selecting a kernel from a different Python installation

### ISSUE THREAD

**Issue by beew** [spyder-ide/spyder#6469]
This is more of a question than an issue. I have two versions of python 3 on my Ubuntu 16.04 system. It has python 3.5 form the system and python 3.6 from Anaconda. I would like to be able to switch between them in spyder. However changing the python interpreter in Spyder doesn't work  because of https://github.com/spyder-ide/spyder/issues/4514.

The answer to that issue was that spyder was compiled under different versions of python3 and there is no binary compatibility. My solution is to run  the same copy of spyder from source using different versions of python and that works, but is there a more elegant way to do it? I am puzzled because if there is no binary compatibility then why the option of choosing different paython interpreter?

Thanks.

**Comment by ccordoba12** [comment]
> However changing the python interpreter in Spyder doesn't work because of #4514.

#4514 was about adding to PYTHONPATH the site-packages directory of another Python version. Are you doing that?

**Comment by beew** [comment]
For example, I have spyder from anaconda, I go to Tools > Preferences and check use the following python interpreter instead of the default and put /usr/bin/python3. Then restart spyder , the kernel struggles to start and gives a bunch of import error. Same if I try the other way: install spyder via pip (python 3.5 from /usr/bin/python3 is the default) and  use the alternative from ~/anaconda3/bin/python.

**Comment by ccordoba12** [comment]
> the kernel struggles to start and gives a bunch of import error

Please post the error so we can help you.

**Comment by beew** [comment]
Hi,  setting python interpreter to /usr/bin/python3 in spyder installed from anaconda, restart spyder and got these errors
```
An error ocurred while starting the kernel
Traceback (most recent call last):
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 236, in main
from ipykernel.kernelapp import IPKernelApp
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/ipykernel/connect.py", line 18, in 
import jupyter_client
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/jupyter_client/__init__.py", line 4, in
from .connect import *
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/jupyter_client/connect.py", line 22, in
import zmq
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/__init__.py", line 34, in 
from zmq import backend
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/backend/__init__.py", line 40, in 
reraise(*exc_info)
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/utils/sixcerpt.py", line 34, in reraise
raise value
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/backend/__init__.py", line 27, in 
_ns = select_backend(first)
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/backend/select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/backend/cython/__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
Traceback (most recent call last):
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 236, in main
from ipykernel.kernelapp import IPKernelApp
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/ipykernel/connect.py", line 18, in 
import jupyter_client
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/jupyter_client/__init__.py", line 4, in
from .connect import *
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/jupyter_client/connect.py", line 22, in
import zmq
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/__init__.py", line 34, in 
from zmq import backend
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/backend/__init__.py", line 40, in 
reraise(*exc_info)
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/utils/sixcerpt.py", line 34, in reraise
raise value
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/backend/__init__.py", line 27, in 
_ns = select_backend(first)
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/backend/select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/backend/cython/__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
Traceback (most recent call last):
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 236, in main
from ipykernel.kernelapp import IPKernelApp
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/ipykernel/connect.py", line 18, in 
import jupyter_client
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/jupyter_client/__init__.py", line 4, in
from .connect import *
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/jupyter_client/connect.py", line 22, in
import zmq
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/__init__.py", line 34, in 
from zmq import backend
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/backend/__init__.py", line 40, in 
reraise(*exc_info)
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/utils/sixcerpt.py", line 34, in reraise
raise value
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/backend/__init__.py", line 27, in 
_ns = select_backend(first)
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/backend/select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/backend/cython/__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
Traceback (most recent call last):
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 236, in main
from ipykernel.kernelapp import IPKernelApp
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/ipykernel/connect.py", line 18, in 
import jupyter_client
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/jupyter_client/__init__.py", line 4, in
from .connect import *
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/jupyter_client/connect.py", line 22, in
import zmq
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/__init__.py", line 34, in 
from zmq import backend
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/backend/__init__.py", line 40, in 
reraise(*exc_info)
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/utils/sixcerpt.py", line 34, in reraise
raise value
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/backend/__init__.py", line 27, in 
_ns = select_backend(first)
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/backend/select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/backend/cython/__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
Traceback (most recent call last):
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 268, in 
main()
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 236, in main
from ipykernel.kernelapp import IPKernelApp
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/ipykernel/connect.py", line 18, in 
import jupyter_client
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/jupyter_client/__init__.py", line 4, in
from .connect import *
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/jupyter_client/connect.py", line 22, in
import zmq
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/__init__.py", line 34, in 
from zmq import backend
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/backend/__init__.py", line 40, in 
reraise(*exc_info)
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/utils/sixcerpt.py", line 34, in reraise
raise value
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/backend/__init__.py", line 27, in 
_ns = select_backend(first)
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/backend/select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "/home/bernard/anaconda3/lib/python3.6/site‑packages/zmq/backend/cython/__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
```

**Comment by ccordoba12** [comment]
Ok, thanks for the error report. We'll take a look at it in a future release.

**Comment by beew** [comment]
So it seems that even when python interpreter is set to /usr/bin/python3 spyder(?) still tries to import site packages from anaconda.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 FYI I was able to reproduce this, (attempting to use an already installed python 3.5, with IPython, cloudpickle and their deps successfully installed via ``pip``) and I get the same error as the OP.
