### ISSUE TITLE
Error In opening file by draging

### ISSUE THREAD

**Issue by ShivamSharma1997** [spyder-ide/spyder#6482]
## Description

**What steps will reproduce the problem?**

1. Drag a file from folder to already opened spyder console. Should open the .py file but adds the file path to the already opened code.
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Shivam\Anaconda2\envs\tensor3\lib\site-packages\spyder\widgets\editor.py", line 2206, in dragEnterEvent
    text = [encoding.is_text_file(url) for url in all_urls]
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\Shivam\Anaconda2\envs\tensor3\lib\site-packages\spyder\widgets\editor.py", line 2206, in dragEnterEvent
    text = [encoding.is_text_file(url) for url in all_urls]
TypeError: 'NoneType' object is not iterable

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.1 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.3.0 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by CAM-Gerlach** [comment]
For reference, duplicate of #5218 , fixed in 3.2.5. You can update with 
```
conda update conda
conda update anaconda
conda update spyder
```
