### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Eastkap** [spyder-ide/spyder#6488]
## Description

**What steps will reproduce the problem?**

1.  launch spyder3
**What is the expected output? What do you see instead?**
the rror

**Please provide any additional information below**

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.10.0, PyQt5 5.10 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.7.0 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.
