### ISSUE TITLE
Spyder doesn't start with "UnicodeDecodeError" if username contains non-ASCII characters

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#651]
_From [ghost261...@gmail.com](https://code.google.com/u/104053305717132899609/) on 2011-05-11T14:32:31Z_

Downloaded "spyder-2.0.11_py27.exe". 
I am using russian WinXP.
Installed. Run.
Spyder doesn't start in command line with the output:

C:\temp>spyder
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\spyderlib\spyder.py", line 1537, in main
    mainwindow = run_spyder(app, options)
  File "c:\python27\lib\site-packages\spyderlib\spyder.py", line 1461, in run_spyder
    main.setup()
  File "c:\python27\lib\site-packages\spyderlib\spyder.py", line 609, in setup
    self.projectexplorer = ProjectExplorer(self)
  File "c:\python27\lib\site-packages\spyderlib\plugins\projectexplorer.py", line 35, in __init__
    default_project_path=get_conf_path())
  File "c:\python27\lib\site-packages\spyderlib\widgets\projectexplorer.py", line 1495, in __init__
    default_project_path=default_project_path)
  File "c:\python27\lib\site-packages\spyderlib\widgets\projectexplorer.py", line 656, in setup
    self.default_project = Project(default_project_path)
  File "c:\python27\lib\site-packages\spyderlib\widgets\projectexplorer.py", line 126, in __init__
    self.root_path = unicode(root_path)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 26: ordinal not in range(128)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=651_

**Comment by spyder-issues-migrator** [comment]
_From [ghost261...@gmail.com](https://code.google.com/u/104053305717132899609/) on 2011-05-11T18:05:17Z_

The problem is in non ascii path names?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-05-12T03:39:13Z_

My guess is that your Windows account username contains non-ASCII characters. Can you confirm that? If so, please post your username here to help us try and reproduce this bug.

**Comment by spyder-issues-migrator** [comment]
_From [ghost261...@gmail.com](https://code.google.com/u/104053305717132899609/) on 2011-05-12T12:28:47Z_

\>> your Windows account username contains non-ASCII characters
yes. 'Ёжик'

The same error appears when you do this in command line:
    \>>> s1 = 'Ёжик'
    \>>> s1
    '\xa8\xe6\xe8\xea'
    \>>> s2 = unicode(s1)

    Traceback (most recent call last):
      File "<pyshell#2>", line 1, in \<module>
        s2 = unicode(s1)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xa8 in position 0: ordinal not in range(128)
    \>>> s2 = unicode(s1, 'cp1251')
    \>>> s2
    u'\u0401\u0436\u0438\u043a'

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-05-28T08:54:12Z_

What should be done to solve this problem Pierre? Do we need to check if the username has non-ASCII characters before trying to encode it in UTF-8?

**Summary:** Spyder doesn't start with "UnicodeDecodeError" if username contains non-ASCII characters  
  **Status:** Accepted  
  **Labels:** Cat-Miscelleneous

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-23T13:10:07Z_

issue #812 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-23T13:12:24Z_

**Labels:** -Priority-Medium Priority-Critical

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-24T12:49:03Z_

**Status:** Fixed
