### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by Patrick160893** [spyder-ide/spyder#6557]
### What steps will reproduce the problem?

I am currently receiving the following error message:

  File "/Users/patrickorourke/anaconda/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'session'

Traceback (most recent call last):
  File "/Users/patrickorourke/anaconda/lib/python3.6/site-packages/jupyter_client/session.py", line 473, in _check_packers
    packed = pack(msg)
  File "/Users/patrickorourke/anaconda/lib/python3.6/site-packages/jupyter_client/session.py", line 95, in <lambda>
    ensure_ascii=False, allow_nan=False,
  File "/Users/patrickorourke/anaconda/lib/python3.6/site-packages/zmq/utils/jsonapi.py", line 40, in dumps
    s = jsonmod.dumps(o, **kwargs)
  File "/Users/patrickorourke/anaconda/lib/python3.6/site-packages/simplejson/__init__.py", line 369, in dumps
    **kw).encode(obj)
  File "/Users/patrickorourke/anaconda/lib/python3.6/site-packages/simplejson/encoder.py", line 262, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/patrickorourke/anaconda/lib/python3.6/site-packages/simplejson/encoder.py", line 329, in iterencode
    Decimal)
TypeError: Required argument 'iterable_as_array' (pos 20) not found

Traceback (most recent call last):
  File "/Users/patrickorourke/anaconda/lib/python3.6/site-packages/spyder/plugins/__init__.py", line 514, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "/Users/patrickorourke/anaconda/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "/Users/patrickorourke/anaconda/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1038, in create_new_client
    self.connect_client_to_kernel(client)
  File "/Users/patrickorourke/anaconda/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1064, in connect_client_to_kernel
    stderr_file)
  File "/Users/patrickorourke/anaconda/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1511, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "/Users/patrickorourke/anaconda/lib/python3.6/site-packages/jupyter_client/manager.py", line 224, in start_kernel
    self.write_connection_file()
  File "/Users/patrickorourke/anaconda/lib/python3.6/site-packages/jupyter_client/connect.py", line 402, in write_connection_file
    transport=self.transport, ip=self.ip, key=self.session.key,
  File "/Users/patrickorourke/anaconda/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/Users/patrickorourke/anaconda/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/Users/patrickorourke/anaconda/lib/python3.6/site-packages/jupyter_client/connect.py", line 321, in _session_default
    return Session(parent=self)
  File "/Users/patrickorourke/anaconda/lib/python3.6/site-packages/jupyter_client/session.py", line 451, in __init__
    self._check_packers()
  File "/Users/patrickorourke/anaconda/lib/python3.6/site-packages/jupyter_client/session.py", line 481, in _check_packers
    msg.format(packer=self.packer, e=e, jsonmsg=jsonmsg)
ValueError: zmq.utils.jsonapi.jsonmod = <module 'simplejson' from '/Users/patrickorourke/anaconda/lib/python3.6/site-packages/simplejson/__init__.py'>

  
 I would appreciate any help on this matter.
  Thank you!

**Comment by ccordoba12** [comment]
Because of this

> File "/Users/patrickorourke/anaconda/lib/python3.6/site-packages/simplejson/encoder.py", line 329, in iterencode
Decimal)
TypeError: Required argument 'iterable_as_array' (pos 20) not found

I'd say you have a corrupt installation. Please uninstall and reinstall Anaconda again and report if the error was fixed for you.

**Comment by CAM-Gerlach** [comment]
Also, you can try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

If it still isn't working, please describe in detail the circumstances in which the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Calling for Help section as a comment to this issue, and we'll try to help if we can. Otherwise, your issue will likely have to be closed after one week (7 days). Thanks, and best of luck!

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response.
