### ISSUE TITLE
Spyder can't open a local socket to use monitor

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#657]
_From [uch...@gmail.com](https://code.google.com/u/103824496511937168390/) on 2011-05-17T10:28:26Z_

spyder -d
Start of MainWindow constructor
Initializing...
End of MainWindow constructor
*** Start of MainWindow setup ***
Loading object inspector...
Loading outline explorer...
Loading editor...

Loading file explorer...
Loading history plugin...
Loading online help...
Loading project explorer...
Loading external console...
Loading namespace browser...

very long loading and  I press Ctrl-C 
^CTraceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/spyder.py", line 1604, in main
    mainwindow = run_spyder(app, options)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/spyder.py", line 1528, in run_spyder
    main.setup()
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/spyder.py", line 640, in setup
    self.extconsole.open_interpreter_at_startup()
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/plugins/externalconsole.py", line 845, in open_interpreter_at_startup
    self.open_ipython()
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/plugins/externalconsole.py", line 877, in open_ipython
    interact=True, debug=False, python=True, ipython=True)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/plugins/externalconsole.py", line 655, in start
    shellwidget.start_shell()
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/widgets/externalshell/baseshell.py", line 225, in start_shell
    self.create_process()
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/widgets/externalshell/pythonshell.py", line 398, in create_process
    introspection_server = introspection.start_introspection_server()
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/widgets/externalshell/introspection.py", line 110, in start_introspection_server
    INTROSPECTION_SERVER = IntrospectionServer()
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/widgets/externalshell/introspection.py", line 48, in __init__
    self.port = SPYDER_PORT = select_port(default_port=SPYDER_PORT)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/utils/__init__.py", line 59, in select_port
    sock.bind( ("127.0.0.1", default_port) )
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/local/bin/spyder", line 3, in \<module>
    spyder.main()
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/spyder.py", line 1610, in main
    if mainwindow is None:
UnboundLocalError: local variable 'mainwindow' referenced before assignment
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/spyder.py", line 1074, in closing
    self.save_current_window_settings(prefix)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/spyder.py", line 862, in save_current_window_settings
    CONF.set(section, prefix+'size', (size.width(), size.height()))
AttributeError: 'NoneType' object has no attribute 'width'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/spyder.py", line 1074, in closing
    self.save_current_window_settings(prefix)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/spyder.py", line 862, in save_current_window_settings
    CONF.set(section, prefix+'size', (size.width(), size.height()))
AttributeError: 'NoneType' object has no attribute 'width'

cat spyder_crash.log

Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/spyder.py", line 1604, in main
    mainwindow = run_spyder(app, options)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/spyder.py", line 1528, in run_spyder
    main.setup()
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/spyder.py", line 640, in setup
    self.extconsole.open_interpreter_at_startup()
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/plugins/externalconsole.py", line 845, in open_interpreter_at_startup
    self.open_ipython()
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/plugins/externalconsole.py", line 877, in open_ipython
    interact=True, debug=False, python=True, ipython=True)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/plugins/externalconsole.py", line 655, in start
    shellwidget.start_shell()
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/widgets/externalshell/baseshell.py", line 225, in start_shell
    self.create_process()
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/widgets/externalshell/pythonshell.py", line 398, in create_process
    introspection_server = introspection.start_introspection_server()
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/widgets/externalshell/introspection.py", line 110, in start_introspection_server
    INTROSPECTION_SERVER = IntrospectionServer()
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/widgets/externalshell/introspection.py", line 48, in __init__
    self.port = SPYDER_PORT = select_port(default_port=SPYDER_PORT)
  File "/usr/local/lib/python2.6/dist-packages/spyderlib/utils/__init__.py", line 65, in select_port
    sock.close()
AttributeError: 'NoneType' object has no attribute 'close'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=657_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-05-17T11:15:54Z_

From the log I can see that Spyder can't open a local socket on your machine.

Do you have iptables installed or something like that that is blocking the opening of ports on localhost?

What distribution are you using?

**Summary:** Spyder can't open a local socket to use monitor  
  **Labels:** Cat-Console

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-01T20:32:44Z_

Closing because of no response from the OP

**Status:** WontFix
