### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by rkdasari** [spyder-ide/spyder#6622]
File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\spyder\plugins\__init__.py", line 514, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1038, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1073, in connect_client_to_kernel
    kc.start_channels(shell=True, iopub=True)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\qtconsole\kernel_mixins.py", line 43, in start_channels
    super(QtKernelClientMixin, self).start_channels(*args, **kw)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\jupyter_client\threaded.py", line 212, in start_channels
    self.shell_channel._inspect = self._check_kernel_info_reply
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\jupyter_client\client.py", line 143, in shell_channel
    socket, self.session, self.ioloop
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\jupyter_client\threaded.py", line 205, in ioloop
    self._ioloop = ioloop.IOLoop()
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\tornado\util.py", line 312, in __new__
    instance.initialize(*args, **init_kwargs)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\zmq\eventloop\ioloop.py", line 139, in initialize
    super(ZMQIOLoop, self).initialize(impl=impl, **kwargs)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\tornado\ioloop.py", line 845, in initialize
    super(PollIOLoop, self).initialize(**kwargs)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\tornado\ioloop.py", line 357, in initialize
    self.make_current()
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\tornado\ioloop.py", line 315, in make_current
    assert asyncio is None
AssertionError
Traceback (most recent call last):
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\qtconsole\manager.py", line 27, in poll
    super(QtKernelRestarter, self).poll()
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\jupyter_client\restarter.py", line 113, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\jupyter_client\manager.py", line 367, in restart_kernel
    self.start_kernel(**self._launch_args)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\jupyter_client\manager.py", line 239, in start_kernel
    self.write_connection_file()
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\jupyter_client\connect.py", line 472, in write_connection_file
    kernel_name=self.kernel_name
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\jupyter_client\connect.py", line 137, in write_connection_file
    with open(fname, 'w') as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Radha\\AppData\\Roaming\\jupyter\\runtime\\kernel-16eae32a20f1.json'

### Traceback
```python-traceback
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\spyder\plugins\__init__.py", line 514, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1038, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1073, in connect_client_to_kernel
    kc.start_channels(shell=True, iopub=True)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\qtconsole\kernel_mixins.py", line 43, in start_channels
    super(QtKernelClientMixin, self).start_channels(*args, **kw)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\jupyter_client\threaded.py", line 212, in start_channels
    self.shell_channel._inspect = self._check_kernel_info_reply
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\jupyter_client\client.py", line 143, in shell_channel
    socket, self.session, self.ioloop
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\jupyter_client\threaded.py", line 205, in ioloop
    self._ioloop = ioloop.IOLoop()
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\tornado\util.py", line 312, in __new__
    instance.initialize(*args, **init_kwargs)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\zmq\eventloop\ioloop.py", line 139, in initialize
    super(ZMQIOLoop, self).initialize(impl=impl, **kwargs)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\tornado\ioloop.py", line 845, in initialize
    super(PollIOLoop, self).initialize(**kwargs)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\tornado\ioloop.py", line 357, in initialize
    self.make_current()
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\tornado\ioloop.py", line 315, in make_current
    assert asyncio is None
AssertionError
Traceback (most recent call last):
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\qtconsole\manager.py", line 27, in poll
    super(QtKernelRestarter, self).poll()
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\jupyter_client\restarter.py", line 113, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\jupyter_client\manager.py", line 367, in restart_kernel
    self.start_kernel(**self._launch_args)
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\jupyter_client\manager.py", line 239, in start_kernel
    self.write_connection_file()
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\jupyter_client\connect.py", line 472, in write_connection_file
    kernel_name=self.kernel_name
  File "C:\Users\Radha\Anaconda3\envs\tensorflow2\lib\site-packages\jupyter_client\connect.py", line 137, in write_connection_file
    with open(fname, 'w') as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Radha\\AppData\\Roaming\\jupyter\\runtime\\kernel-16eae32a20f1.json'
```

## Package Versions

* Spyder 3.2.7 ``
* Python 3.5.4
* Qt 5.6.2
* PyQt5 5.6
* Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.14.1 (OK)
sphinx >=0.6.6   :  1.7.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)
```

**Comment by ccordoba12** [comment]
> PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Radha\\AppData\\Roaming\\jupyter\\runtime\\kernel-16eae32a20f1.json'

Well, the error says it all. You don't have reading nor writing permissions in that directory and Spyder needs that to start an IPython console. Please fix that in your end because there's nothing we can do about it.

**Comment by CAM-Gerlach** [comment]
Other than that, please do try what is listed in #6627 if you haven't already; namely, run ``conda install tornado=4.5.3`` from the Anaconda Prompt in the ``conda`` environment that Spyder is installed in.

**Comment by CAM-Gerlach** [comment]
@rkdasari I presume one of these resolved the issue? What in particular, for future reference for us and others who might have the same problem. Thanks.
