### ISSUE TITLE
Spyder crashing - Linux

### ISSUE THREAD

**Issue by FLOURA71196** [spyder-ide/spyder#6640]
## Problem Description
Spyder is not responding, crashes every time

### What steps will reproduce the problem?

1. On launch
2. 
3. 

### What is the expected output? What do you see instead?
Spyder IDE, but it fails to launch. Asks to use spyder --reset but after that again error message

### Paste Traceback/Error Below (if applicable)

Traceback (most recent call last):
File "/home/floura/anaconda3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 3208, in main
mainwindow = run_spyder(app, options, args)
File "/home/floura/anaconda3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 3084, in run_spyder
main.setup()
File "/home/floura/anaconda3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 835, in setup
from spyder.plugins.help import Help
File "/home/floura/anaconda3/lib/python3.5/site-packages/spyder/plugins/help.py", line 32, in 
from spyder.utils.help.sphinxify import (CSS_PATH, generate_context,
File "/home/floura/anaconda3/lib/python3.5/site-packages/spyder/utils/help/sphinxify.py", line 32, in 
from sphinx.application import Sphinx
File "/home/floura/anaconda3/lib/python3.5/site-packages/sphinx/application.py", line 21, in 
from typing import TYPE_CHECKING
ImportError: cannot import name 'TYPE_CHECKING'
```python-traceback

PASTE TRACEBACK HERE

```

## Package Versions

* Spyder:3.2.7
* Python:3.5.0
* Qt:
* PyQt:
* Operating System:Linux Sylvia

### Dependencies

```
PASTE DEPENDENCIES HERE
```
Traceback (most recent call last):
File "/home/floura/anaconda3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 3208, in main
mainwindow = run_spyder(app, options, args)
File "/home/floura/anaconda3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 3084, in run_spyder
main.setup()
File "/home/floura/anaconda3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 835, in setup
from spyder.plugins.help import Help
File "/home/floura/anaconda3/lib/python3.5/site-packages/spyder/plugins/help.py", line 32, in 
from spyder.utils.help.sphinxify import (CSS_PATH, generate_context,
File "/home/floura/anaconda3/lib/python3.5/site-packages/spyder/utils/help/sphinxify.py", line 32, in 
from sphinx.application import Sphinx
File "/home/floura/anaconda3/lib/python3.5/site-packages/sphinx/application.py", line 21, in 
from typing import TYPE_CHECKING
ImportError: cannot import name 'TYPE_CHECKING'

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Do you happen to have any files or variables named "application.py" or "typing" on your path or in your working dir, just to make sure that isn't the issue? Furthermore, your anaconda and python versions look very out of date; the most likely fix is just to do a clean uninstall and reinstall to the latest version from the website (5.1.0, with Python 3.6.4). Python 3.5.0 is many years out of date even for Python 3.5.

In any case, as by all appearances this is an install-related issue, please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

If it still isn't working, please describe in detail the circumstances in which the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Calling for Help section as a comment to this issue, and we'll try to help if we can. Otherwise, your issue will likely have to be closed after one week (7 days). Thanks, and best of luck!

**Comment by csabella** [comment]
`typing.TYPE_CHECKING` was added in Python 3.5.2 according to the [docs](https://docs.python.org/3.8/library/typing.html#typing.TYPE_CHECKING).  Since the error is happening in Sphinx, I think you have two options - downgrade Sphinx or upgrade Python to at least 3.5.2.  :-)
