### ISSUE TITLE
Spyder is crashing when opening

### ISSUE THREAD

**Issue by jpiabrantes** [spyder-ide/spyder#6657]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 114, in _save
    _write_file(fname)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 110, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ID Kas\\.spyder-py3\\spyder.ini'

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\__init__.py", line 437, in set_option
    CONF.set(self.CONF_SECTION, str(option), value)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 448, in set
    self._save()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 124, in _save
    raise(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 118, in _save
    os.remove(fname)
PermissionError: proces wordt gebruikt: 'C:\\Users\\ID Kas\\.spyder-py3\\spyder.ini'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle

**Comment by ccordoba12** [comment]
> PermissionError: [Errno 13] Permission denied: 'C:\Users\ID Kas\.spyder-py3\spyder.ini'

It seems you don't have permissions to read/write in that directory, and Spyder needs to do it to save your Preferences.

Please change your permissions in that folder to fix this problem.

**Comment by CAM-Gerlach** [comment]
Sorry, accidentally hit the wrong button,

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.
