### ISSUE TITLE
Spyder hangs - X Error: BadLength (poly request too large or internal Xlib length error) 16

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#674]
_From [kamil.paral](https://code.google.com/u/kamil.paral/) on 2011-06-01T04:06:09Z_

I can't reproduce it, but generally about once a day Spyder freezes for me. The window is all gray and in the titlebar there is "not responding" sentence. I have to kill the window (and then kill some other Python stray process that eats all CPU).

This is written out to stderr:

X Error: BadLength (poly request too large or internal Xlib length error) 16
  Extension:    148 (RENDER)
  Minor opcode: 5 (RenderChangePicture)
  Resource id:  0x5c64e86

I have googled about that problem and found this thread: http://lists.trolltech.com/qt-interest/2006-02/thread00266-0.html Citing:
"Doing "gui things" in another thread is *not* supported in Qt. See http://doc.trolltech.com/3.3/threads.html or http://doc.trolltech.com/4.1/threads.html (depending on the version you are using)"

Can it be the cause also in Spyder? What version of the product are you using? On what operating system? Fedora 14, Spyder 2.0.11 

Please provide any additional information below

. I attach last 10,000 lines of output from strace.

**Attachment:** [strace.log](http://code.google.com/p/spyderlib/issues/detail?id=674)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=674_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-06-01T04:54:19Z_

I think I've already had the same issue on Ubuntu -- even if I didn't look further and find out about this "X Error: BadLength..." error.

If you could enable the "debug mode" in 'spyderlib/widgets/externalshell/monitor/py': https://code.google.com/p/spyderlib/source/browse/spyderlib/widgets/externalshell/monitor.py?repo=v20#18 (simply replace "DEBUG = False" by "DEBUG = True")
This should create a log file ('monitor_debug.log') in your $HOME/.spyder2 directory.

The next time Spyder hangs, you may post this log here.

Note: it does log a lot of things, so do not hesitate to remove the file from time to time and to remove old lines from the file before attaching it to this Issue (there are timestamps all over the file).

**Status:** Accepted  
  **Labels:** OpSys-Linux

**Comment by spyder-issues-migrator** [comment]
_From [kamil.paral](https://code.google.com/u/kamil.paral/) on 2011-06-01T05:18:29Z_

OK, I'll do that.

**Comment by spyder-issues-migrator** [comment]
_From [kamil.paral](https://code.google.com/u/kamil.paral/) on 2011-06-06T08:25:23Z_

Today it froze again for me. This error was in ~/.spyder2/monitor.log:


======================================
Logging time: Mon Jun  6 16:25:51 2011

======================================

Context
\-------

\<spyderlib.widgets.externalshell.monitor.PacketNotReceived object at 0x14bc090>

Traceback
\---------

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/spyder-2.0.11-py2.7.egg/spyderlib/widgets/externalshell/monitor.py", line 459, in run
    command = read_packet(self.i_request, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/spyder-2.0.11-py2.7.egg/spyderlib/widgets/externalshell/monitor.py", line 96, in read_packet
    dlen, = struct.unpack("l", datalen)
error: unpack requires a string argument of length 8



It was repeated there a million times. But I suspect that is more probably related to issue `#618` , when a stray process loops.


I also attach ~/.spyder2/monitor_debug.log. But I don't see the error in there.

**Attachment:** [monitor_debug.log](http://code.google.com/p/spyderlib/issues/detail?id=674#hc3)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-09-24T05:29:01Z_

Please follow this new wiki page to help us debugging this crash: https://code.google.com/p/spyderlib/wiki/HowToDebugQtCrash

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-10-08T07:03:46Z_

**Labels:** -Priority-Medium Priority-High Cat-SpyderGUI

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-17T05:19:30Z_

Following recent changes (in the past weeks), I'm hoping that this issue has been fixed so I'm closing it. If the problem persists, please follow the wiki page as suggested in my previous comment.

**Status:** Done
