### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by play5835835** [spyder-ide/spyder#6740]
### What steps will reproduce the problem?

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 114, in _save
_write_file(fname)
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 110, in _write_file
with open(fname, 'w', encoding='utf-8') as configfile:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Administrator.USER-20141018HE\\.spyder-py3\\spyder.ini'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\start.py", line 158, in main
from spyder.app import mainwindow
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 112, in 
from spyder.utils.qthelpers import qapplication, MENU_SEPARATOR
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\qthelpers.py", line 26, in 
from spyder.config.gui import get_shortcut
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\gui.py", line 168, in 
set_default_color_scheme(_name, replace=False)
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\gui.py", line 164, in set_default_color_scheme
set_color_scheme(name, sh.get_color_scheme(name), replace=replace)
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\gui.py", line 158, in set_color_scheme
CONF.set(section, "names", sorted(list(set(names))))
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 449, in set
self._save()
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 124, in _save
raise(e)
File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 118, in _save
os.remove(fname)
PermissionError: [WinError 32] 程序無法存取檔案，因為檔案正由另一個程序使用。: 'C:\\Users\\Administrator.USER-20141018HE\\.spyder-py3\\spyder.ini'

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 114, in _save
    _write_file(fname)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 110, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Administrator.USER-20141018HE\\.spyder-py3\\spyder.ini'

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\__init__.py", line 440, in set_option
    CONF.set(self.CONF_SECTION, str(option), value)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 449, in set
    self._save()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 124, in _save
    raise(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 118, in _save
    os.remove(fname)
PermissionError: [WinError 32] 程序無法存取檔案，因為檔案正由另一個程序使用。: 'C:\\Users\\Administrator.USER-20141018HE\\.spyder-py3\\spyder.ini'
```

## Package Versions

* Spyder 3.2.7 ``
* Python 3.6.4
* Qt 5.10.1
* PyQt5 5.10.1
* Windows 7

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)
```

**Comment by CAM-Gerlach** [comment]
Closed by author; likely install issue.

**Comment by ccordoba12** [comment]
It's the typical `PermissionsError` on Windows. My new theory is that this happens because users run Spyder as an admin in an unprivileged account and then they try to run it as the user of that account, resulting in the error above.

@CAM-Gerlach, could you try my theory to see if it reproduces the problem?

**Comment by CAM-Gerlach** [comment]
@ccordoba12 I can, it just requires a full backup, uninstall, reinstall, uninstall, reinstall, and re-setup of Anaconda and all my packages, which especially on my personal laptop is not a trivial affair, especially considering I can't be logged into my main account in order to fully replicate the circumstances. I'll try to boot up my backup laptop and do it on that later tonight.

In other news, I just accidentally discovered that github has searchable saved replies...well, my job just got a whole heck of a lot less tedious; I'd been using a text document and manually looking through/copy pasting up until now.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Okay, so on a clean laptop I installed Anaconda as a standard user, with the option "All users (requires admin)", elevated at the UAC prompt with my admin credentials, then ran Spyder from the shortcut as that same user. No error occurred launching Spyder, and I was able to run simple commands in the Console without issue as well as change preferences. Anything else you want me to test while I've got this laptop setup and standing by?

**Comment by ccordoba12** [comment]
> Anything else you want me to test while I've got this laptop setup and standing by?

Yes. Please:

1. Remove `.spyder` or `.spyder-py3`
2. Start Spyder as admin in your standard user account.
3. Close Spyder
4. Start Spyder as your standard user.

That should produce the `PermissionError` we're seeing because after step 2. the Spyder settings directory has higher permissions than the ones available to your standard user, so the standard user can't do anything inside it (i.e. nor write and remove files).

I mean, it's like running  `sudo spyder` and then just `spyder` on Linux after a clean installation. I'm almost sure the result should be a `PermissionError` too (I'll try that this weekend on my end :-).

**Comment by CAM-Gerlach** [comment]
@ccordoba12 I went through that procedure, and also tried running as admin again before and after, to no effect (as I in fact expected). When running as admin, it runs in the context of the specific admin user account used, not just with admin-level permissions, and so the new ``.spyder-py3`` dir is created in the _admin account's user folder``, and does not get recreated in the user's dir until they re-open it with their own account. Both have separate, unrelated preferences. Its really more like ``login admin_user``  and then launching Spyder from there and not really like ``sudo`` that just gives you the permissions and ownership rights of the target user, but otherwise leaves your environment unchanged...and just one more thing I hate about windows, as it makes it a major pain to run as a standard user on a regular basis.
