### ISSUE TITLE
Spyder crashing on opening

### ISSUE THREAD

**Issue by vishnurapps** [spyder-ide/spyder#6761]
## Description

**What steps will reproduce the problem?**

1. Open Anaconda navigator
2. Click on launch in Spyder
3. You can observe a screen poping up saying spyder has crashed

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/vishnu/anaconda3/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 144, in icon
    if osp.isdir(fname):
  File "/home/vishnu/anaconda3/lib/python3.6/genericpath.py", line 42, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 16: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/vishnu/anaconda3/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 144, in icon
    if osp.isdir(fname):
  File "/home/vishnu/anaconda3/lib/python3.6/genericpath.py", line 42, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character '\ufffd' in position 16: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/vishnu/anaconda3/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 144, in icon
    if osp.isdir(fname):
  File "/home/vishnu/anaconda3/lib/python3.6/genericpath.py", line 42, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character '\ufffd' in position 16: ordinal not in range(128)

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

to see if you can fix your problem by following it.

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.
