### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

### ISSUE THREAD

**Issue by angelalarc99** [spyder-ide/spyder#6767]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\usuario\ANACONDA\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 561, in show_time
    elapsed_time = time() - self.t0
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Traceback (most recent call last):
  File "C:\Users\usuario\ANACONDA\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 561, in show_time
    elapsed_time = time() - self.t0
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Traceback (most recent call last):
WARNING:traitlets:kernel died: 3.0197155475616455
  File "C:\Users\usuario\ANACONDA\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 561, in show_time
    elapsed_time = time() - self.t0
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Traceback (most recent call last):
  File "C:\Users\usuario\ANACONDA\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 561, in show_time
    elapsed_time = time() - self.t0
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Traceback (most recent call last):
  File "C:\Users\usuario\ANACONDA\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 561, in show_time
    ela

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll fix this problem in our next release.

@csabella, this one is yours :-) I think it happens when the kernel takes too much time to start.

**Comment by csabella** [comment]
This is the old code before my change in #6699, but we don't know what version of Spyder the OP is running.  @ccordoba12 , do you think one of the other fixes to the console would have helped with the kernel start up time?  Just thinking if @angelalarc99 updates to 3.2.8, then it may resolve their issue.

I will, however, also put in a check to make sure self.t0 isn't None.  :-)

**Comment by ccordoba12** [comment]
> do you think one of the other fixes to the console would have helped with the kernel start up time?

I made several changes to improve kernel startup time in the same release the timing functionality was introduced. After that, nothing significant has changed in that regard.

> I will, however, also put in a check to make sure self.t0 isn't None. :-)

Thanks a lot for your quick response!
