### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by zhiyuanzhai** [spyder-ide/spyder#6782]
### What steps will reproduce the problem?

Just open Spyder. Well I don't know why this message came up.

### Traceback
```python-traceback
  File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/spyder/plugins/__init__.py", line 514, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/spyder/plugins/ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/spyder/plugins/ipythonconsole.py", line 1038, in create_new_client
    self.connect_client_to_kernel(client)
  File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/spyder/plugins/ipythonconsole.py", line 1073, in connect_client_to_kernel
    kc.start_channels(shell=True, iopub=True)
  File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/qtconsole/kernel_mixins.py", line 43, in start_channels
    super(QtKernelClientMixin, self).start_channels(*args, **kw)
  File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/jupyter_client/threaded.py", line 212, in start_channels
    self.shell_channel._inspect = self._check_kernel_info_reply
  File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/jupyter_client/client.py", line 143, in shell_channel
    socket, self.session, self.ioloop
  File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/jupyter_client/threaded.py", line 205, in ioloop
    self._ioloop = ioloop.IOLoop()
  File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/tornado/util.py", line 312, in __new__
    instance.initialize(*args, **init_kwargs)
  File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 139, in initialize
    super(ZMQIOLoop, self).initialize(impl=impl, **kwargs)
  File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 845, in initialize
    super(PollIOLoop, self).initialize(**kwargs)
  File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 357, in initialize
    self.make_current()
  File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 315, in make_current
    assert asyncio is None
AssertionError
```

## Package Versions

* Spyder 3.2.7 ``
* Python 3.5.4
* Qt 5.6.2
* PyQt5 5.6
* Darwin 17.4.0

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.2 (OK)
sphinx >=0.6.6   :  1.7.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)
```

**Comment by ccordoba12** [comment]
Please open Terminal.app and run

    conda update pyzmq tornado ipykernel

to fix this problem.

**Comment by zhiyuanzhai** [comment]
Thank you, but I've got a new problem.
Now I can not even launch the Spyder or anything with Anaconda.
Here's the traceback.
`
Traceback (most recent call last):
File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 3208, in main
mainwindow = run_spyder(app, options, args)
File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 3084, in run_spyder
main.setup()
File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 848, in setup
from spyder.plugins.editor import Editor
File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/spyder/plugins/editor.py", line 41, in 
from spyder.utils.introspection.manager import IntrospectionManager
File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/spyder/utils/introspection/manager.py", line 21, in 
from spyder.utils.introspection.plugin_client import PluginClient
File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/spyder/utils/introspection/plugin_client.py", line 18, in 
import zmq
File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/zmq/__init__.py", line 47, in 
from zmq import backend
File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/zmq/backend/__init__.py", line 40, in 
reraise(*exc_info)
File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
raise value
File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/zmq/backend/__init__.py", line 27, in 
_ns = select_backend(first)
File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/zmq/backend/select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/zmq/backend/cython/__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: dlopen(/Users/xuzhiyuan/anaconda3/lib/python3.5/site-packages/zmq/backend/cython/error.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libsodium.23.dylib
Referenced from: /Users/xuzhiyuan/anaconda3/lib/libzmq.5.dylib
Reason: image not found
`

**Comment by CAM-Gerlach** [comment]
> or anything with Anaconda.

Then the problem is not with Spyder, but rather your installation or other packages, and thus we have no control over it. Try downgrading everything again and wait for a fix on their end; specifically, try ``conda install tornado=4.5.3``` and if that doesn't work, ``conda install anaconda``.

**Comment by CAM-Gerlach** [comment]
Original problem is yet another duplicate of #6627

**Comment by ccordoba12** [comment]
@zhiyuanzhai, it looks like you corrupted your Anaconda installation. You should remove and reinstall Anaconda to fix this problem.

**Comment by zhiyuanzhai** [comment]
Thanks! @CAM-Gerlach @ccordoba12 Finally I reinstalled the Anaconda. It worked.
