### ISSUE TITLE
Error after upgrade Spyder

### ISSUE THREAD

**Issue by eduamf** [spyder-ide/spyder#6788]
I'm using WinPython. 

After upgrade and start Spyder (version 3.2.8), I received the following error message:

```
An error ocurred while starting the kernel
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
callback(*args, **kwargs)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\tornado\stack_context.py", line 276, in null_wrapper
return fn(*args, **kwargs)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\ipykernel\kernelbase.py", line 283, in dispatcher
return self.dispatch_shell(stream, msg)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
self.pre_handler_hook()
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\ipykernel\kernelbase.py", line 248, in pre_handler_hook
self.saved_sigint_handler = signal(SIGINT, default_int_handler)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\signal.py", line 47, in signal
handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
self._handle_recv()
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
self._run_callback(callback, msg)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
callback(*args, **kwargs)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\tornado\stack_context.py", line 276, in null_wrapper
return fn(*args, **kwargs)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\ipykernel\kernelbase.py", line 283, in dispatcher
return self.dispatch_shell(stream, msg)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
self.pre_handler_hook()
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\ipykernel\kernelbase.py", line 248, in pre_handler_hook
self.saved_sigint_handler = signal(SIGINT, default_int_handler)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\signal.py", line 47, in signal
handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
ERROR:tornado.application:Exception in callback functools.partial(.null_wrapper at 0x0000000011984D08>)
Traceback (most recent call last):
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\tornado\ioloop.py", line 760, in _run_callback
ret = callback()
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\tornado\stack_context.py", line 276, in null_wrapper
return fn(*args, **kwargs)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\zmq\eventloop\zmqstream.py", line 536, in 
self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
self._handle_recv()
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
self._run_callback(callback, msg)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
callback(*args, **kwargs)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\tornado\stack_context.py", line 276, in null_wrapper
return fn(*args, **kwargs)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\ipykernel\kernelbase.py", line 283, in dispatcher
return self.dispatch_shell(stream, msg)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
self.pre_handler_hook()
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\ipykernel\kernelbase.py", line 248, in pre_handler_hook
self.saved_sigint_handler = signal(SIGINT, default_int_handler)
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\signal.py", line 47, in signal
handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
Traceback (most recent call last):
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 269, in 
main()
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 265, in main
kernel.start()
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\ipykernel\kernelapp.py", line 477, in start
ioloop.IOLoop.instance().start()
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\site‑packages\tornado\platform\asyncio.py", line 112, in start
self.asyncio_loop.run_forever()
File "E:\WinPython󈛤bit\python𔂭.6.3.amd64\Lib\asyncio\base_events.py", line 408, in run_forever
raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```
## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.3
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating system: Windows 7

### Dependencies

```
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.2 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.2 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
```

**Comment by ccordoba12** [comment]
Please open this bug in the WinPython repo

https://github.com/winpython/winpython/

and don't open more issues here. Thanks.

**Comment by eduamf** [comment]
Wow, the error messages pop up in the Spyder console. Very cordial response.

**Comment by ccordoba12** [comment]
We know, but this is a WinPython error and not a Spyder one. Hence the reply.

**Comment by CAM-Gerlach** [comment]
@eduamf Sorry if it came across the wrong way; we appreciate you taking the time to report. However, the reason we stated that was due to previously bringing up the same issue on the comment of another one, and we want to avoid people posting multiple duplicate issues we have no control over and clogging up our tracker, as has happened a number of times in the past. 

Also, I would like to note that in our Troubleshooting guide (which ask users to read before submitting an issue in a prominent reminder at the top of our issue template you filled out), at the top of our Contributing Guidelines (linked even more emphatically at the top of the new issue page), and in our Readme, Install Instructions and several places in our documentation, we make clear we currently lack the resources to provide individual support for install- or user-related issues for distributions other than Anaconda, and recommend users switch to the latter should they be unable to solve their problems with the former by other means as that avoids many issues like this one.

**Comment by eduamf** [comment]
I fixed it installing WinPython again.


Ok


________________________________
De: C.A.M. Gerlach <notifications@github.com>
Enviado: domingo, 18 de março de 2018 23:04
Para: spyder-ide/spyder
Cc: Eduardo Antonio Mello Freitas; Mention
Assunto: Re: [spyder-ide/spyder] Error after upgrade Spyder (#6788)


@eduamf<https://github.com/eduamf> Sorry if it came across the wrong way; we appreciate you taking the time to report. However, the reason we stated that was due to previously bringing up the same issue on the comment of another one, and we want to avoid people posting multiple duplicate issues we have no control over and clogging up our tracker, as has happened a number of times in the past.

Also, I would like to note that in our Troubleshooting guide (which ask users to read before submitting an issue in a prominent reminder at the top of our issue template you filled out), at the top of our Contributing Guidelines (linked even more emphatically at the top of the new issue page), and in our Readme, Install Instructions and several places in our documentation, we make clear we currently lack the resources to provide individual support for install- or user-related issues for distributions other than Anaconda, and recommend users switch to the latter should they be unable to solve their problems with the former by other means as that avoids many issues like this one.

-

**Comment by eduamf** [comment]
?Thank you

________________________________
De: Carlos Cordoba <notifications@github.com>
Enviado: domingo, 18 de março de 2018 18:21
Para: spyder-ide/spyder
Cc: Eduardo Antonio Mello Freitas; Author
Assunto: Re: [spyder-ide/spyder] Error after upgrade Spyder (#6788)


We know, but this is a WinPython error and not a Spyder one. Hence the reply.

-
