### ISSUE TITLE
python bootstrap.py error

### ISSUE THREAD

**Issue by rohshall** [spyder-ide/spyder#6789]
### What steps will reproduce the problem?

Opened by running - python bootstrap.py

[salil@ultrabook spyder]$ python bootstrap.py
Executing Spyder from source checkout
Revision 73c9e1c66, Branch: master
01. Patched sys.path with /home/salil/spyder
02. PyQt5 is detected, selecting
03. Imported Spyder 4.0.0.dev0
    [Python 3.6.4 64bits, Qt 5.10.1, PyQt5 5.8.2 on Linux]
04. Running Spyder
Bootstrap completed in 00:00:00.2399

### Traceback
```python-traceback
    module = _import_module_from_path(module_name, plugin_path)
    module = spec.loader.load_module(module_name)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 262, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    from .pylint import Pylint as PLUGIN_CLASS
    from .widgets.pylintgui import PylintWidget
    import pylint
ModuleNotFoundError: No module named 'pylint'
ERROR: 3rd party plugin import failed for `spyder_pylint`
Traceback (most recent call last):
    module = _import_module_from_path(module_name, plugin_path)
    module = spec.loader.load_module(module_name)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 262, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    from .pylint import Pylint as PLUGIN_CLASS
    from .widgets.pylintgui import PylintWidget
    import pylint
ModuleNotFoundError: No module named 'pylint'
```

## Package Versions

* Spyder version: 4.0.0.dev0 73c9e1c66
* Python version: 3.6.4
* Qt version: 5.10.1
* PyQt5 version: 5.8.2
* Operating system: Linux 4.9.81_1

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  1.7.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.11.0    :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
```
`
`

**Comment by ccordoba12** [comment]
Did you install pylint? The error is pretty clear.

**Comment by rohshall** [comment]
Yes, I did not see the error till the log was submitted to github. Closing it.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Maybe we should have the "show details" pane open by default? What's the UX reason for hiding it in the first place?

**Comment by ccordoba12** [comment]
It's hard for most people to understand tracebacks. But we could leave it open by default when running from bootstrap.py
