### ISSUE TITLE
ERROR WHILE USING MATLAB ENGINE IN PYTHON

### ISSUE THREAD

**Issue by gdu2003** [spyder-ide/spyder#6808]
## Problem Description

I have installed matlab engine by using help from:
[http://in.mathworks.com/help/matlab/matlab_external/install-the-matlab-engine-for-python.html]

While i am trying to use this matlab engine in spyder. This error pops up.
If i close this error dialog box and try to use matlab engine , it does not return any output.

e.g. if i want to just use eng.sqrt(4) it does not work.
On top of it the help window appearance changes as below: The good looking heading disappears.
![spyder](https://user-images.githubusercontent.com/31308740/37695967-37a51d28-2cf9-11e8-9a13-4af7cb681036.JPG)

**_['<matlabvar>']
['<matlabvar>']=vardata

    Pass a variable into the MATLAB workspace and copy a
    variable from the MATLAB workspace.

    Parameters
        <matlabvar>: str
            Variable name to be used in the MATLAB workspace.

        vardata: object
            A Python variable to be passed into the MATLAB workspace.

    Returns
        ['<matlabvar>'] returns the variable copied from the
        MATLAB workspace.

        ['<matlabvar>']=vardata returns None.

    Raises
        NameError - if there is no such variable in the MATLAB
        workspace.

        SyntaxError - if the data is passed to the MATLAB
        workspace with an illegal variable name.

        TypeError - if <matlabvar> is not a string, or if
        the data type of vardata is not supported.

        ValueError - if <matlabvar> is empty.

        RejectedExecutionError - if the Engine is terminated._**
### What steps will reproduce the problem?

import matlab.engine
eng = matlab.engine.start_matlab()
eng.workspace(
Just after typing first bracket after eng.workspace this error appears

### Traceback
```python-traceback
  File "c:\python35\lib\site-packages\spyder\plugins\help.py", line 400, in <lambda>
    self.combo.valid.connect(lambda valid: self.force_refresh())
  File "c:\python35\lib\site-packages\spyder\plugins\help.py", line 759, in force_refresh
    self.set_object_text(None, force_refresh=True)
  File "c:\python35\lib\site-packages\spyder\plugins\help.py", line 774, in set_object_text
    found = self.show_help(text, ignore_unknown=ignore_unknown)
  File "c:\python35\lib\site-packages\spyder\plugins\help.py", line 983, in show_help
    self.set_plain_text(hlp_text, is_code=is_code)
  File "c:\python35\lib\site-packages\spyder\plugins\help.py", line 683, in set_plain_text
    self.plain_text.set_text(full_text, is_code)
  File "c:\python35\lib\site-packages\spyder\plugins\help.py", line 241, in set_text
    self.editor.set_text(text)
  File "c:\python35\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 1595, in set_text
    self.setPlainText(text)
TypeError: setPlainText(self, str): argument 1 has unexpected type 'bool'
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\spyder\plugins\help.py", line 400, in <lambda>
    self.combo.valid.connect(lambda valid: self.force_refresh())
  File "c:\python35\lib\site-packages\spyder\plugins\help.py", line 759, in force_refresh
    self.set_object_text(None, force_refresh=True)
  File "c:\python35\lib\site-packages\spyder\plugins\help.py", line 774, in set_object_text
    found = self.show_help(text, ignore_unknown=ignore_unknown)
  File "c:\python35\lib\site-packages\spyder\plugins\help.py", line 983, in show_help
    self.set_plain_text(hlp_text, is_code=is_code)
  File "c:\python35\lib\site-packages\spyder\plugins\help.py", line 683, in set_plain_text
    self.plain_text.set_text(full_text, is_code)
  File "c:\python35\lib\site-packages\spyder\plugins\help.py", line 241, in set_text
    self.editor.set_text(text)
  File "c:\python35\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 1595, in set_text
    self.setPlainText(text)
TypeError: setPlainText(self, str): argument 1 has unexpected type 'bool'
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.5.3
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating system: Windows 7

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.2 (OK)
sphinx >=0.6.6   :  1.7.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.3 (OK)
```

**Comment by ccordoba12** [comment]
We're very sorry but we don't have access to a Matlab installation on Windows to help you with this problem.

However, you're welcome to submit a pull request to fix it, if/when you find its cause and how to solve it.
