### ISSUE TITLE
Explorer and projectexplorer cause Spyder Segmentation fault at start.

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#682]
_From [stuart.k...@gmail.com](https://code.google.com/u/105509517255172870109/) on 2011-06-06T17:49:48Z_

What steps will reproduce the problem?

 1.Install EPD 7.0-2-rh5-x86_64
2.Install dependencies: sip-4.12.3; qt 4.7.1; PyQt-x11-gpl-4.8.4; logilab-common-0.55.2; ; logilab-astng-0.21.1; pylint-0.23.0; rope-0.9.3.
3.Install spyder-2.0.11
4.run spyder What is the expected output? What do you see instead? Instead of starting Spyder produces a Segmentation fault, after splash but before the spyder window opens. What version of the product are you using? On what operating system? Spyder 2.11, EPD 7.0-2-rh5-x86_64, CentOS 5.6. 

Please provide any additional information below

. Running the tests available in the spyderlib/widgets directory I encountered the following:

    editor.py still tries to load 
        "codeeditor/codeeditor.py"
    instead of 
        "sourcecode/codeeditor.py"
    after correcting this the editor test runs without error.
 
 
    explorer.py
        Segmentation fault
    with no further information. System logs show error type 4, if that is of any help.

    arrayeditor.py, opens fine but on quit leaves a 100&#37; python process and a stream of errors of the form:
        out: None
        (<unknown>:5971): Gtk-CRITICAL **: gtk_container_add: assertion `GTK_IS_CONTAINER (container)' failed
        (<unknown>:5971): Gtk-CRITICAL **: gtk_widget_realize: assertion `GTK_WIDGET_ANCHORED (widget) || GTK_IS_INVISIBLE (widget)' failed
        (<unknown>:5971): Gtk-CRITICAL **: gtk_widget_realize: assertion `GTK_WIDGET_ANCHORED (widget) || GTK_IS_INVISIBLE (widget)' failed
        ...

    projectexplorer.py
        Traceback (most recent call last):
          File "projectexplorer.py", line 1618, in \<module>
            test = Test()
          File "projectexplorer.py", line 1586, in __init__
            self.explorer = ProjectExplorerWidget()
          File "projectexplorer.py", line 1495, in __init__
            default_project_path=default_project_path)
          File "projectexplorer.py", line 655, in setup
            assert default_project_path is not None
        AssertionError
        
        
    dicteditor.py
        Traceback (most recent call last):
          File "dicteditor.py", line 1439, in \<module>
            test()
          File "dicteditor.py", line 1421, in test
            out = dedit( get_test_data() )
          File "dicteditor.py", line 1399, in get_test_data
            image = PIL.Image.fromarray(np.random.random_integers(255, size=(100, 100)))
          File "/usr/local/epd/epd-7.0-2-rh5-x86_64/lib/python2.7/site-packages/PIL/Image.py", line 1886, in fromarray
            raise TypeError("Cannot handle this data type")
        TypeError: Cannot handle this data type
        
        
    formlayout.py
        result:
        Traceback (most recent call last):
          File "formlayout.py", line 541, in \<module>
            apply=apply_test)
          File "formlayout.py", line 505, in fedit
            dialog = FormDialog(data, title, comment, icon, parent, apply)
          File "formlayout.py", line 421, in __init__
            self.formwidget.setup()
          File "formlayout.py", line 271, in setup
            selindex = value.pop(0)
        AttributeError: 'tuple' object has no attribute 'pop'

    objecteditor.py
        Traceback (most recent call last):
          File "objecteditor.py", line 134, in \<module>
            test()
          File "objecteditor.py", line 117, in test
            image = PIL.Image.fromarray(np.random.random_integers(255, size=(100, 100)))
          File "/usr/local/epd/epd-7.0-2-rh5-x86_64/lib/python2.7/site-packages/PIL/Image.py", line 1886, in fromarray
            raise TypeError("Cannot handle this data type")
        TypeError: Cannot handle this data type

All other tests, that is, those in:
    texteditor.py
    pathmanager.py
    outlineexplorer.py
    findinfiles.py
    importwizard.py
run without error. 

 
Disabling the explorer and project_explorer in ~/.spyder2/.spyder.ini,
that is, setting:
    [project_explorer]
    enable = False
and
    [explorer]
    enable = False
is sufficient to enable Spyder to start without segfault. However, any attempt to navigate to files again causes a Segmentation fault.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=682_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-09-24T05:31:01Z_

We would appreciate if you could do the following to help us solve this issue:
1. Please upgrade your Spyder version up to v2.1.0beta1 at least.
2. If the problem persists, you may follow these instructions: https://code.google.com/p/spyderlib/wiki/HowToDebugQtCrash

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-10-29T06:14:39Z_

**Labels:** Cat-SpyderGUI

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2014-06-30T21:27:52Z_

Is it still actual?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-23T13:41:48Z_

I also think this is too old.

**Status:** WontFix
