### ISSUE TITLE
Saving figures fails with matplotlib patch enabled

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#686]
_From [DavidAnt...@gmail.com](https://code.google.com/u/108698404730356683634/) on 2011-06-08T18:14:51Z_

I am running the latest development version, Python 2.6.5, Qt 4.6.2, PyQt4 4.7.2, matplotlib 0.99.1.1 on Ubuntu 10.04 64 bit.

When clicking on the save icon of a figure, I get the following error message:

Traceback (most recent call last):
  File "/home/dap124/external_code/spyder/spyderlib/mpl_patch.py", line 134, in save_figure
    super(NavigationToolbar2QT, self).save_figure()
  File "/usr/lib/pymodules/python2.6/matplotlib/backends/backend_qt4.py", line 399, in save_figure
    self, "Choose a filename to save to", start, filters, selectedFilter)
TypeError: QFileDialog.getSaveFileName(QWidget parent=None, QString caption=QString(), QString directory=QString(), QString filter=QString(), QString selectedFilter=None, QFileDialog.Options options=0): argument 5 has unexpected type 'str'

This error does not occur if I disable the matplotlib patch.  I believe that it is a relatively recent error as I haven't had this problem until now.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=686_

**Comment by spyder-issues-migrator** [comment]
_From [DavidAnt...@gmail.com](https://code.google.com/u/108698404730356683634/) on 2011-09-06T23:42:45Z_

Today I had a look at this issue, and noticed that it occurred regardless of whether or not I had the matplotlib patch option installed.

However, I did upgrade to matplotlib 1.01, and the problem now seems to be gone.

Does spyder have a minimum requirement for matplotlib? If so, then I suggest at the very least it should be added to the installation wiki (which currently mentions no version requirements), and perhaps some kind of check should be done when importing matplotlib (although apart from saving it seems to work fine, so this might be a bit draconian).

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-09-07T01:46:32Z_

Looking at the traceback, it seems that the error is coming from Matplotlib itself, not Spyder. Maybe this had something to do with PyQt API version...

I'll try to reproduce the bug with the same configuration as you mentionned in your initial report.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-09T05:26:47Z_

I confirm that this is a Matplotlib bug. Upgrading to v1.0.1 indeed fixes this issue.

**Status:** Done
