### ISSUE TITLE
Missing context in keyboard shortcut.

### ISSUE THREAD

**Issue by lycsjm** [spyder-ide/spyder#6862]
### What steps will reproduce the problem?

![keyboard shortcut setting](https://user-images.githubusercontent.com/1042553/38095020-f44fdde2-33a1-11e8-87b2-f816945a2722.png)
Open perferencesw and switch to keyboard shortcut session

### Traceback
```python-traceback
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
```

## Package Versions

* Spyder 3.2.7 ``
* Python 3.6.4
* Qt 5.10.1
* PyQt5 5.10.1
* Linux 4.15.12-1-ARCH

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.2 (OK)
sphinx >=0.6.6   :  1.7.2 (OK)
rope >=0.9.4     :  0.10.6 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)
```

**Comment by ccordoba12** [comment]
> PyQt5 5.10.1

This version is not supported by us because it causes a lot strange problems, like the one you're seeing above. Please downgrade to Qt/PyQt 5.9 to fix it.
