### ISSUE TITLE
Spyder 3.2.8 crashes at launch on macOS 10.13.3

### ISSUE THREAD

**Issue by nikon95** [spyder-ide/spyder#6879]
## Problem Description
After spyder update to 3.2.8 via conda not able to launch.

Problem persists after dongrading to 3.2.7 and spyder --reset.

### What steps will reproduce the problem?

1. Run Spyder through anaconda distribution
2. Get traceback
3. 

### What is the expected output? What do you see instead?
Application launch. Instead spyder quits and traceback on terminal output.

### Paste Traceback/Error Below (if applicable)
Unable to open dependencies, installed though conda.
PASTE TRACEBACK HERE
Traceback (most recent call last):
  File "/Users/user/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3208, in main
    mainwindow = run_spyder(app, options, args)
  File "/Users/user/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3084, in run_spyder
    main.setup()
  File "/Users/user/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 848, in setup
    from spyder.plugins.editor import Editor
  File "/Users/user/anaconda3/lib/python3.6/site-packages/spyder/plugins/editor.py", line 41, in <module>
    from spyder.utils.introspection.manager import IntrospectionManager
  File "/Users/user/anaconda3/lib/python3.6/site-packages/spyder/utils/introspection/manager.py", line 21, in <module>
    from spyder.utils.introspection.plugin_client import PluginClient
  File "/Users/user/anaconda3/lib/python3.6/site-packages/spyder/utils/introspection/plugin_client.py", line 18, in <module>
    import zmq
  File "/Users/user/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/Users/user/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 21, in <module>
    if platform.python_implementation() == 'PyPy':
  File "/Users/user/anaconda3/lib/python3.6/platform.py", line 1234, in python_implementation
    return _sys_version()[0]
  File "/Users/user/anaconda3/lib/python3.6/platform.py", line 1192, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.6.3 |Anaconda custom (64-bit)| (default, Oct  6 2017, 12:04:38) \n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]'

## Package Versions

* Spyder: 3.2.8
* Python: 3.6.3 |Anaconda custom (64-bit)| (default, Oct  6 2017, 12:04:38) \n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)
* Qt:5.6.2
* PyQt:1.3.1
* Operating System: macOS 10.13.3

### Dependencies
Unable to open tab

**Comment by ccordoba12** [comment]
Please open Terminal.app and run there

    conda update python pyzmq python.app

to see if that fixes your problem.

**Comment by nikon95** [comment]
It worked, it just wanted to update pyzmq.

Thank a lot!!

**Comment by CAM-Gerlach** [comment]
Closed as user resolved issue.

**Comment by colasbd** [comment]
It worked here as well. 👍
