### ISSUE TITLE
Spyder fails to start when trying to set language on Windows

### ISSUE THREAD

**Issue by shadab-shah** [spyder-ide/spyder#6886]
I have install anaconda and trying to open spyder, but i am getting the below error.

Traceback (most recent call last):
File "C:\Users\admin\Anaconda3\Scripts\spyder-script.py", line 6, in
from spyder.app.start import main
File "C:\Users\admin\Anaconda3\lib\site-packages\spyder\app\start.py", line 25, in
from spyder.config.base import get_conf_path, running_in_mac_app
File "C:\Users\admin\Anaconda3\lib\site-packages\spyder\config\base.py", line 362, in
_ = get_translation("spyder")
File "C:\Users\admin\Anaconda3\lib\site-packages\spyder\config\base.py", line 336, in get_translation
os.environ["LANG"] = language # Works on Windows
File "C:\Users\admin\Anaconda3\lib\os.py", line 675, in setitem
self.putenv(key, value)
ValueError: embedded null character

I had install-re-install anaconda couple of times.
tried --reset command too, but nothing is working as of now.

Thanks for the help.

**Comment by shuvayan** [comment]
I am not sure if this is related but I am unable to open up the Spyder IDE from Windows. I have uninstalled and installed Anaconda, added the path to environment variables during installation also.
It was working fine 12 hours back. I am not being able to grasp what has happened but found this issue.

The attached image shows the status when I click on spyder within anaconda.
![spyder_errror](https://user-images.githubusercontent.com/11851253/38439721-6633e7b8-39fc-11e8-9b62-0a8a2c3838ff.png)

**Comment by CAM-Gerlach** [comment]
@shuvayan Possible, but unlikely, unless you are getting the error traceback specified above. 
Thanks for reporting. Please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

**Comment by MrEleden** [comment]
HI ! i got the same problem !
spyder --reset / anaconda clean uninstall and reinstall doesn't work ;)

Traceback (most recent call last):
File "C:\Users\admin\AppData\Local\Continuum\anaconda3\Scripts\spyder-script.py", line 6, in 
from spyder.app.start import main
File "C:\Users\admin\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\app\start.py", line 25, in 
from spyder.config.base import (get_conf_path, running_in_mac_app,
File "C:\Users\admin\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\config\base.py", line 383, in 
_ = get_translation("spyder")
File "C:\Users\admin\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\config\base.py", line 357, in get_translation
os.environ["LANG"] = language # Works on Windows
File "C:\Users\admin\AppData\Local\Continuum\anaconda3\lib\os.py", line 675, in __setitem__
self.putenv(key, value)
ValueError: embedded null character

**Comment by CAM-Gerlach** [comment]
Thanks for the information; seems to be a pretty critical error then. Can you try the other steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

**Comment by ccordoba12** [comment]
I'll take a look at this one.

**Comment by sonusingh99** [comment]
Traceback (most recent call last):
File "C:\Users\hp\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3285, in main
mainwindow = run_spyder(app, options, args)
File "C:\Users\hp\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3140, in run_spyder
main.setup()
File "C:\Users\hp\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 824, in setup
self.workingdirectory = WorkingDirectory(self, self.init_workdir, main=self)
File "C:\Users\hp\Anaconda3\lib\site-packages\spyder\plugins\workingdirectory.py", line 149, in __init__
wdhistory = self.load_wdhistory(workdir)
File "C:\Users\hp\Anaconda3\lib\site-packages\spyder\plugins\workingdirectory.py", line 221, in load_wdhistory
wdhistory = [name for name in wdhistory if os.path.isdir(name)]
File "C:\Users\hp\Anaconda3\lib\site-packages\spyder\plugins\workingdirectory.py", line 221, in 
wdhistory = [name for name in wdhistory if os.path.isdir(name)]
ValueError: _isdir: embedded null character in path


I am also getting this same error please help

**Comment by ccordoba12** [comment]
@sonusingh99, that's a different problem from the one reported here. So please open a new issue about it.

**Comment by huang961372045** [comment]
Traceback (most recent call last):
  File "D:\Software\Academy\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3285, in main
    mainwindow = run_spyder(app, options, args)
  File "D:\Software\Academy\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3140, in run_spyder
    main.setup()
  File "D:\Software\Academy\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 824, in setup
    self.workingdirectory = WorkingDirectory(self, self.init_workdir, main=self)
  File "D:\Software\Academy\Anaconda\lib\site-packages\spyder\plugins\workingdirectory.py", line 149, in __init__
    wdhistory = self.load_wdhistory(workdir)
  File "D:\Software\Academy\Anaconda\lib\site-packages\spyder\plugins\workingdirectory.py", line 221, in load_wdhistory
    wdhistory = [name for name in wdhistory if os.path.isdir(name)]
  File "D:\Software\Academy\Anaconda\lib\site-packages\spyder\plugins\workingdirectory.py", line 221, in <listcomp>
    wdhistory = [name for name in wdhistory if os.path.isdir(name)]
ValueError: _isdir: embedded null character in path
  

I got this problem, too! Please HELP!

**Comment by CAM-Gerlach** [comment]
See the comment right above yours, responding to a user who reported an identical issue:

> @sonusingh99, that's a different problem from the one reported here. So please open a new issue about it.

**Comment by CAM-Gerlach** [comment]
This appears to be a duplicate of #10676 , which can be solved by running the following in Anaconda prompt:

```bash
spyder --reset
```
