### ISSUE TITLE
pyside2 support

### ISSUE THREAD

**Issue by looooo** [spyder-ide/spyder#6894]
I am trying to get spyder working with pyside2. I am using qt5.6 and pyside2 from conda-forge channel.

So far there are some problems in the initialization (qtpy) and some not available members of QtCore:
- QtCore.qround  which I replaced with pythons round
```
  File "~/conda/envs/pyside2/lib/python3.6/site-packages/qtawesome/iconic_font.py", line 24, in <module>
    from qtpy.QtCore import QObject, QPoint, QRect, qRound, Qt
ImportError: cannot import name 'qRound'

```
- QWebEngineSettings (which I simple disabled)
```
  File "~/projects/spyder/spyder/widgets/browser.py", line 18, in <module>
    from qtpy.QtWebEngineWidgets import (QWebEnginePage, QWebEngineSettings,
ImportError: cannot import name 'QWebEngineSettings'
Fatal Python error: deallocating None

```
- QRegularExpression (should be the same as QRegExpr)
```
  File "~/projects/spyder/spyder/widgets/mixins.py", line 40, in <module>
    from qtpy.QtCore import QRegularExpression
ImportError: cannot import name 'QRegularExpression'
Fatal Python error: deallocating None
```
- QAbstractItemModel.index (no idea)
```
Traceback (most recent call last):
  File "~/projects/spyder/spyder/widgets/explorer.py", line 969, in filterAcceptsRow
    index = self.sourceModel().index(row, 0, parent_index)
NotImplementedError: pure virtual method 'QAbstractItemModel.index()' not implemented.
```
depends on https://bugreports.qt.io/browse/PYSIDE-570

are there any plans to support pyside2. It seems like it is almost possible.

**Comment by ccordoba12** [comment]
> are there any plans to support pyside2. It seems like it is almost possible.

No. It'd be a terrible waste of time for us to support PySide2 when it's still very buggy and it doesn't offer any gain to the project.

Closing this one for the time being.

**Comment by stonebig** [comment]
@looooo You may check at the bottom of this page the advance of PySide2 towards PyQt5 parity https://wiki.qt.io/Qt_for_Python_Missing_Bindings

Today they are 75 points behind PyQt5, at PySide-5.11a1 (alpha1)

You may check their progress on this metric after their preview release, end of may 2018.

**Comment by stonebig** [comment]
the patch for Qround is there https://github.com/spyder-ide/qtawesome/pull/81/files.  will re-propose in a more compatible way

**Comment by stonebig** [comment]
no change of mind ?

**Comment by ccordoba12** [comment]
If you're willing to put from your own time and add PySide2 to CircleCI, fix all failing tests and be willing to keep fixing tests in the future, then sure, we'll support PySide2.

If not, then we're happy to be a PyQt5 project only because there's nothing important to gain for us in supporting PySide2.

**Comment by stonebig** [comment]
there may be a bus factor

**Comment by looooo** [comment]
Is there any work going on for PySide2 support? I would like to make a tight integration of FreeCAD and spyder for development but this is currently not possible because FreeCAD uses PySide2 and is not able to use PyQt, while for spyder it is exactly the other way...

I tried this (branch)[https://github.com/spyder-ide/spyder/pull/9953] but I get:
```
pkg_resources.DistributionNotFound: The 'pyqtwebengine<5.13' distribution was not found and is required by spyder
```

Is there any work going on in this direction? What can we do to accelerate development?

**Comment by ccordoba12** [comment]
Sorry but we haven't had time to work on this. You're welcome to continue my work on master and add support.

Otherwise you'll have to wait for Spyder 5 (to be released next year), which will come for sure with support for PySide2.

**Comment by stonebig** [comment]
small remark: Qt is working on PyPy support for PySide6 (as of 24 june 2021) https://wiki.qt.io/Qt_for_Python_Development_Notes

**Comment by ccordoba12** [comment]
Wow, that's really impressive!
