### ISSUE TITLE
Error when launching Spyder under python 3

### ISSUE THREAD

**Issue by YIJUNDONGMIT** [spyder-ide/spyder#6897]
## Problem Description
I can't launch Spyder.

The error is showed below:
Traceback (most recent call last):
File "C:\Users\dongy\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3208, in main
mainwindow = run_spyder(app, options, args)
File "C:\Users\dongy\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3084, in run_spyder
main.setup()
File "C:\Users\dongy\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1172, in setup
self.setup_layout(default=False)
File "C:\Users\dongy\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1457, in setup_layout
self.setup_default_layouts('default', settings)
File "C:\Users\dongy\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1633, in setup_default_layouts
widget.toggle_view(True)
File "C:\Users\dongy\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 725, in toggle_view
self.create_new_client(give_focus=False)
File "C:\Users\dongy\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1046, in create_new_client
self.connect_client_to_kernel(client, is_cython=is_cython)
File "C:\Users\dongy\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1084, in connect_client_to_kernel
kc.start_channels(shell=True, iopub=True)
File "C:\Users\dongy\Anaconda3\lib\site-packages\qtconsole\kernel_mixins.py", line 43, in start_channels
super(QtKernelClientMixin, self).start_channels(*args, **kw)
File "C:\Users\dongy\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 212, in start_channels
self.shell_channel._inspect = self._check_kernel_info_reply
File "C:\Users\dongy\Anaconda3\lib\site-packages\jupyter_client\client.py", line 143, in shell_channel
socket, self.session, self.ioloop
File "C:\Users\dongy\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 205, in ioloop
self._ioloop = ioloop.IOLoop()
File "C:\Users\dongy\Anaconda3\lib\site-packages\tornado\util.py", line 312, in __new__
instance.initialize(*args, **init_kwargs)
File "C:\Users\dongy\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 139, in initialize
super(ZMQIOLoop, self).initialize(impl=impl, **kwargs)
File "C:\Users\dongy\Anaconda3\lib\site-packages\tornado\ioloop.py", line 845, in initialize
super(PollIOLoop, self).initialize(**kwargs)
File "C:\Users\dongy\Anaconda3\lib\site-packages\tornado\ioloop.py", line 357, in initialize
self.make_current()
File "C:\Users\dongy\Anaconda3\lib\site-packages\tornado\ioloop.py", line 315, in make_current
assert asyncio is None
AssertionError

Thank you for help.

**Comment by ccordoba12** [comment]
Please update pyzmq and jupyter_client to fix this. For that, you need to open the Anaconda Prompt and run there

    conda update pyzmq jupyter_client

**Comment by CAM-Gerlach** [comment]
Just to be clear, this error is well outside of Spyder's control.
