### ISSUE TITLE
Spyder went crashed when I start it

### ISSUE THREAD

**Issue by Kimilovesy** [spyder-ide/spyder#6907]
## Problem Description
My spyder works well yesterday, while it displays the following error when I start it this morning. Quite wired, does anyone know where it comes from? 

### What steps will reproduce the problem?

1.  Start the Spyder....
2. 
3. 

### What is the expected output? What do you see instead?
I expect that I can simply run the kernel, while it went crashed incidently.

### Paste Traceback/Error Below (if applicable)

```python-traceback

An error ocurred while starting the kernel
Traceback (most recent call last):
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/spyder/utils/ipython/start_kernel.py", line 269, in 
main()
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/spyder/utils/ipython/start_kernel.py", line 237, in main
from ipykernel.kernelapp import IPKernelApp
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/ipykernel/connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/IPython/core/profiledir.py", line 11, in 
from traitlets.config.configurable import LoggingConfigurable
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/traitlets/config/__init__.py", line 6, in 
from .application import *
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/traitlets/config/application.py", line 19, in 
from traitlets.config.configurable import Configurable, SingletonConfigurable
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/traitlets/config/configurable.py", line 12, in 
from .loader import Config, LazyConfigValue, _is_section_key
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/traitlets/config/loader.py", line 16, in 
from ipython_genutils.path import filefind
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/ipython_genutils/path.py", line 13, in 
import random
File "/Users/Kimi/Desktop/AudioSet/Playground/random.py", line 9, in 
import tensorflow as tf
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/tensorflow/__init__.py", line 24, in 
from tensorflow.python import *
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/tensorflow/python/__init__.py", line 49, in 
import numpy as np
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/numpy/__init__.py", line 142, in 
from . import add_newdocs
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/numpy/add_newdocs.py", line 13, in 
from numpy.lib import add_newdoc
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/numpy/lib/__init__.py", line 8, in 
from .type_check import *
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/numpy/lib/type_check.py", line 11, in 
import numpy.core.numeric as _nx
AttributeError: module 'numpy' has no attribute 'core'
Traceback (most recent call last):
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/spyder/utils/ipython/start_kernel.py", line 269, in 
main()
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/spyder/utils/ipython/start_kernel.py", line 237, in main
from ipykernel.kernelapp import IPKernelApp
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/ipykernel/connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/IPython/core/profiledir.py", line 11, in 
from traitlets.config.configurable import LoggingConfigurable
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/traitlets/config/__init__.py", line 6, in 
from .application import *
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/traitlets/config/application.py", line 19, in 
from traitlets.config.configurable import Configurable, SingletonConfigurable
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/traitlets/config/configurable.py", line 12, in 
from .loader import Config, LazyConfigValue, _is_section_key
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/traitlets/config/loader.py", line 16, in 
from ipython_genutils.path import filefind
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/ipython_genutils/path.py", line 13, in 
import random
File "/Users/Kimi/Desktop/AudioSet/Playground/random.py", line 9, in 
import tensorflow as tf
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/tensorflow/__init__.py", line 24, in 
from tensorflow.python import *
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/tensorflow/python/__init__.py", line 49, in 
import numpy as np
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/numpy/__init__.py", line 142, in 
from . import add_newdocs
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/numpy/add_newdocs.py", line 13, in 
from numpy.lib import add_newdoc
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/numpy/lib/__init__.py", line 8, in 
from .type_check import *
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/numpy/lib/type_check.py", line 11, in 
import numpy.core.numeric as _nx
AttributeError: module 'numpy' has no attribute 'core'
Traceback (most recent call last):
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/spyder/utils/ipython/start_kernel.py", line 269, in 
main()
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/spyder/utils/ipython/start_kernel.py", line 237, in main
from ipykernel.kernelapp import IPKernelApp
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/ipykernel/connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/IPython/core/profiledir.py", line 11, in 
from traitlets.config.configurable import LoggingConfigurable
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/traitlets/config/__init__.py", line 6, in 
from .application import *
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/traitlets/config/application.py", line 19, in 
from traitlets.config.configurable import Configurable, SingletonConfigurable
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/traitlets/config/configurable.py", line 12, in 
from .loader import Config, LazyConfigValue, _is_section_key
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/traitlets/config/loader.py", line 16, in 
from ipython_genutils.path import filefind
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/ipython_genutils/path.py", line 13, in 
import random
File "/Users/Kimi/Desktop/AudioSet/Playground/random.py", line 9, in 
import tensorflow as tf
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/tensorflow/__init__.py", line 24, in 
from tensorflow.python import *
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/tensorflow/python/__init__.py", line 49, in 
import numpy as np
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/numpy/__init__.py", line 142, in 
from . import add_newdocs
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/numpy/add_newdocs.py", line 13, in 
from numpy.lib import add_newdoc
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/numpy/lib/__init__.py", line 8, in 
from .type_check import *
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/numpy/lib/type_check.py", line 11, in 
import numpy.core.numeric as _nx
AttributeError: module 'numpy' has no attribute 'core'
Traceback (most recent call last):
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/spyder/utils/ipython/start_kernel.py", line 269, in 
main()
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/spyder/utils/ipython/start_kernel.py", line 237, in main
from ipykernel.kernelapp import IPKernelApp
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/ipykernel/connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/IPython/core/profiledir.py", line 11, in 
from traitlets.config.configurable import LoggingConfigurable
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/traitlets/config/__init__.py", line 6, in 
from .application import *
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/traitlets/config/application.py", line 19, in 
from traitlets.config.configurable import Configurable, SingletonConfigurable
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/traitlets/config/configurable.py", line 12, in 
from .loader import Config, LazyConfigValue, _is_section_key
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/traitlets/config/loader.py", line 16, in 
from ipython_genutils.path import filefind
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/ipython_genutils/path.py", line 13, in 
import random
File "/Users/Kimi/Desktop/AudioSet/Playground/random.py", line 9, in 
import tensorflow as tf
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/tensorflow/__init__.py", line 24, in 
from tensorflow.python import *
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/tensorflow/python/__init__.py", line 49, in 
import numpy as np
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/numpy/__init__.py", line 142, in 
from . import add_newdocs
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/numpy/add_newdocs.py", line 13, in 
from numpy.lib import add_newdoc
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/numpy/lib/__init__.py", line 8, in 
from .type_check import *
File "/Users/Kimi/anaconda/envs/py35/lib/python3.5/site‑packages/numpy/lib/type_check.py", line 11, in 
import numpy.core.numeric as _nx
AttributeError: module 'numpy' has no attribute 'core'

```

## Package Versions

* Spyder: 3.2.6
* Python: python 3.5.3
* Qt: 5.6.2
* PyQt: 5.6.0
* Operating System: MacOS

### Dependencies

```
IPython >=4.0    :  5.3.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
psutil >=0.3     :  5.2.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.0 (OK)
```

**Comment by ccordoba12** [comment]
> AttributeError: module 'numpy' has no attribute 'core'

This looks like an installation problem with Numpy, not with Spyder. Please try to fix it by running in a terminal

    conda install -f numpy

If you installed Numpy with pip, I'm afraid you corrupted your Anaconda installation and you'll have to reinstall again.

**Comment by CAM-Gerlach** [comment]
You can also try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

**Comment by Kimilovesy** [comment]
Hi,

I have tried your method. It still has the same error. I installed the Numpy using conda install numpy. I also tried to uninstall conda and install again. It doesn't work. It is quite wired for me. It works perfectly yesterday and I didn't change anything. Then it went crashed when I start it today. Could you be so kind to helo me on that?

**Comment by CAM-Gerlach** [comment]
> I have tried your method.

Which one? @ccordoba12 's suggestion? There are dozens of potential troubleshooting steps listed in the guide.

> I also tried to uninstall conda and install again.

Do you mean Anaconda? You can't really uninstall conda by itself unless you're an expert at least...

> Could you be so kind to helo me on that?

As we've stated, your problem is with your install, specifically Numpy, and there is nothing we can do about it on Spyder's side—this is a bug tracker for Spyder, not a help forum. As I suggested before, your problem will almost certainly be fixed if you carefully go through all the steps of the Spyder Troubleshooting Guide sections linked above, particularly a clean reinstall of Anaconda. Best of luck!
