### ISSUE TITLE
Mayavi graphics is broken in spyder 3.2.5

### ISSUE THREAD

**Issue by xaverm** [spyder-ide/spyder#6912]
Hi,
for me, _mayavi_ with _spyder_ is broken since the last update of my Python3.5 environment in conda.
Using mayavi in a plain IPython terminal or a jupyter-notebook works for me.
I already reported a similar issue in **#6339**, where downgrading to spyder 3.2.5 helped.
Now the issue has reoccurred, even though I've pinned spyder to version 3.2.5.
On Spyder 3.2.5 startup I get
Issue 1
```
Python 3.5.4 | packaged by conda-forge | (default, Dec  9 2017, 16:18:50)
Type "copyright", "credits" or "license" for more information.
IPython 6.3.1 -- An enhanced Interactive Python.
NOTE: Spyder *can't* set your selected Matplotlib backend because there is a previous backend already in use.
Your backend will be Qt4Agg
In [1]: 
```
I've seen reports of this strange _NOTE: Spyder *can't* set..._ elsewhere. I don't know if I should worry and if it is related to the mayavi issue. I am using a Python 3.5.x environment in Anaconda with 
pyqt 4.11.4 and qt 4.8.7 since mayavi is known to have issues with Python 3.6.x and Qt5.

Now, when trying to import mayvi's mlab module, I get
Issue 2
```
In [1]: from mayavi import mlab
Changing backend to Qt for Mayavi
Traceback (most recent call last):

  File "<ipython-input-1-67847bc6bfd0>", line 1, in <module>
    from mayavi import mlab

  File "/home/userxyzy/.anaconda3/envs/py35/lib/python3.5/site-packages/mayavi/mlab.py", line 27, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move

  File "/home/userxyzy/.anaconda3/envs/py35/lib/python3.5/site-packages/mayavi/tools/camera.py", line 25, in <module>
    from .engine_manager import get_engine

  File "/home/userxyzy/.anaconda3/envs/py35/lib/python3.5/site-packages/mayavi/tools/engine_manager.py", line 12, in <module>
    from mayavi.preferences.api import preference_manager

  File "/home/userxyzy/.anaconda3/envs/py35/lib/python3.5/site-packages/mayavi/preferences/api.py", line 4, in <module>
    from .preference_manager import preference_manager

  File "/home/userxyzy/.anaconda3/envs/py35/lib/python3.5/site-packages/mayavi/preferences/preference_manager.py", line 29, in <module>
    from traitsui.api import View, Group, Item

  File "/home/userxyzy/.anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/api.py", line 36, in <module>
    from .editors.api import ArrayEditor

  File "/home/userxyzy/.anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/editors/__init__.py", line 23, in <module>
    from .api import ArrayEditor

  File "/home/userxyzy/.anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/editors/api.py", line 24, in <module>
    from .code_editor import CodeEditor

  File "/home/userxyzy/.anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/editors/code_editor.py", line 36, in <module>
    class ToolkitEditorFactory ( EditorFactory ):

  File "/home/userxyzy/.anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/editors/code_editor.py", line 48, in ToolkitEditorFactory
    mark_color = Color( 0xECE9D8 )

  File "/home/userxyzy/.anaconda3/envs/py35/lib/python3.5/site-packages/traits/traits.py", line 522, in __call__
    return self.maker_function( *args, **metadata )

  File "/home/userxyzy/.anaconda3/envs/py35/lib/python3.5/site-packages/traits/traits.py", line 1236, in Color
    return ColorTrait( *args, **metadata )

  File "/home/userxyzy/.anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/toolkit_traits.py", line 7, in ColorTrait
    return toolkit().color_trait( *args, **traits )

  File "/home/userxyzy/.anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/toolkit.py", line 161, in toolkit
    _toolkit = _import_toolkit(toolkit_name)

  File "/home/userxyzy/.anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/toolkit.py", line 83, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit

  File "/home/userxyzy/.anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/qt4/__init__.py", line 18, in <module>
    import pyface.qt

  File "/home/userxyzy/.anaconda3/envs/py35/lib/python3.5/site-packages/pyface/qt/__init__.py", line 44, in <module>
    % qt_api)

RuntimeError: Invalid Qt API 'pyqt5', valid values are: 'pyqt' or 'pyside'


In [2]: 
```
The latter statement seems to be true at least somehow, since in the IPython console of spyder there is an environment variable button which tells me that: `QT_API | str | 1 | pyqt5`.

Moreover, in a plain IPython console outside of spyder I can get an issue similar to the one under 'Issue 2' in this post, if I start IPython with `ipython --matplotlib=qt5` if I do `ipython --matplotlib=qt4`, I can import `from mayavi import mlab` without a problem.

So, maybe it would help if I'd know how to start spyder using qt4. Can one do that?

Any help would be greatly appreciated, Xaver

PS.: why has Anaconda, Inc dared to stop funding Spyder development? Surreal! It is the only reasonable scientific IDE out there. Many of my colleagues heavily depend on it for their daily work. There is no replacement. Very sad.

## Package Versions
Spyder 3.2.5, Python 3.5.4 64bits, Qt 4.8.7, PyQt4 (API v2) 4.11.4 on Linux 
### Dependencies
IPython >=4.0    :  6.3.1 (OK)
cython >=0.21    :  0.28.1 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
psutil >=0.3     :  5.4.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.2 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
> I already reported a similar issue in #6339

Ok, let's merge this one with that issue to consolidate everything in one place and because #6339 is scheduled for Spyder 3.3.

> PS.: why has Anaconda, Inc dared to stop funding Spyder development? Surreal! It is the only reasonable scientific IDE out there. Many of my colleagues heavily depend on it for their daily work. There is no replacement. Very sad.

Now you know why it takes more time to solve things. But please don't despair, we're looking for new ways of funding.

**Comment by CAM-Gerlach** [comment]
@xaverm Shameless plug, but you, your coworkers and your company can help fund Spyder continued Spyder matinence, development and new features by becoming a backer or supporter on our [OpenCollective](https://opencollective.com/spyder). Thanks for your kind words!
