### ISSUE TITLE
Spyder problem：Connecting to kernel...

### ISSUE THREAD

**Issue by wishing-candle** [spyder-ide/spyder#6913]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "E:\anaconda\envs\tensorflow\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'session'

Traceback (most recent call last):
  File "E:\anaconda\envs\tensorflow\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1273, in close_client
    self.create_new_client()
  File "E:\anaconda\envs\tensorflow\lib\site-packages\spyder\plugins\ipythonconsole.py", line 991, in create_new_client
    self.connect_client_to_kernel(client)
  File "E:\anaconda\envs\tensorflow\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1018, in connect_client_to_kernel
    stderr_file)
  File "E:\anaconda\envs\tensorflow\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1420, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "E:\anaconda\envs\tensorflow\lib\site-packages\jupyter_client\manager.py", line 238, in start_kernel
    self.write_connection_file()
  File "E:\anaconda\envs\tensorflow\lib\site-packages\jupyter_client\connect.py", line 426, in write_connection_file
    transport=self.transport, ip=self.ip, key=self.session.key,
  File "E:\anaconda\envs\tensorflow\lib\site-packages\traitlets\traitlets.py", line 556, in __get__

**Comment by ccordoba12** [comment]
> File "E:\anaconda\envs\tensorflow\lib\site-packages\traitlets\traitlets.py", line 528, in get
value = obj._trait_values[self.name]
KeyError: 'session'

This error doesn't come from Spyder but from the `traitlets` package, so we can't help you about it. My only recommendation is that you should try to remove your tensorflow environment and install recreate it again, to see if things are fixed that way.
