### ISSUE TITLE
Anaconda failed to load spyder

### ISSUE THREAD

**Issue by RayLei** [spyder-ide/spyder#6926]
## Description

When opening Spyder from Anaconda, following message pop up.  Spyder is  unable to connect to  Console, showing 'Connecting to kernel' forever.

## Error message
 
  File "/anaconda/lib/python3.6/site-packages/spyder/plugins/__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "/anaconda/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "/anaconda/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1033, in create_new_client
    self.connect_client_to_kernel(client)
  File "/anaconda/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1068, in connect_client_to_kernel
    kc.start_channels(shell=True, iopub=True)
  File "/anaconda/lib/python3.6/site-packages/qtconsole/kernel_mixins.py", line 43, in start_channels
    super(QtKernelClientMixin, self).start_channels(*args, **kw)
  File "/anaconda/lib/python3.6/site-packages/jupyter_client/threaded.py", line 206, in start_channels
    self.shell_channel._inspect = self._check_kernel_info_reply
  File "/anaconda/lib/python3.6/site-packages/jupyter_client/client.py", line 143, in shell_channel
    socket, self.session, self.ioloop
  File "/anaconda/lib/python3.6/site-packages/jupyter_client/threaded.py", line 199, in ioloop
    self._ioloop = ioloop.IOLoop()
  File "/anaconda/lib/python3.6/site-packages/tornado/util.py", line 312, in __new__
    instance.initialize(*args, **init_kwargs)
  File "/anaconda/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 139, in initialize
    super(ZMQIOLoop, self).initialize(impl=impl, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/tornado/ioloop.py", line 845, in initialize
    super(PollIOLoop, self).initialize(**kwargs)
  File "/anaconda/lib/python3.6/site-packages/tornado/ioloop.py", line 357, in initialize
    self.make_current()
  File "/anaconda/lib/python3.6/site-packages/tornado/ioloop.py", line 315, in make_current
    assert asyncio is None
AssertionError
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1033, in create_new_client
    self.connect_client_to_kernel(client)
  File "/anaconda/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1068, in connect_client_to_kernel
    kc.start_channels(shell=True, iopub=True)
  File "/anaconda/lib/python3.6/site-packages/qtconsole/kernel_mixins.py", line 43, in start_channels
    super(QtKernelClientMixin, self).start_channels(*args, **kw)
  File "/anaconda/lib/python3.6/site-packages/jupyter_client/threaded.py", line 206, in start_channels
    self.shell_channel._inspect = self._check_kernel_info_reply
  File "/anaconda/lib/python3.6/site-packages/jupyter_client/client.py", line 143, in shell_channel
    socket, self.session, self.ioloop
  File "/anaconda/lib/python3.6/site-packages/jupyter_client/threaded.py", line 199, in ioloop
    self._ioloop = ioloop.IOLoop()
  File "/anaconda/lib/python3.6/site-packages/tornado/util.py", line 312, in __new__
    instance.initialize(*args, **init_kwargs)
  File "/anaconda/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 139, in initialize
    super(ZMQIOLoop, self).initialize(impl=impl, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/tornado/ioloop.py", line 845, in initialize
    super(PollIOLoop, self).initialize(**kwargs)
  File "/anaconda/lib/python3.6/site-packages/tornado/ioloop.py", line 357, in initialize
    self.make_current()
  File "/anaconda/lib/python3.6/site-packages/tornado/ioloop.py", line 315, in make_current
    assert asyncio is None
AssertionError

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
To fix error, please update pyzmq and jupyter_client. You can do that by opening the Anaconda prompt and running there

    conda update pyzmq jupyter_client
