### ISSUE TITLE
Spyder hangs on arrays with "show min and max" checked

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#694]
_From [pavi...@gmail.com](https://code.google.com/u/117959836646743258567/) on 2011-06-22T09:07:31Z_

What steps will reproduce the problem?

 1. Import numpy
2. Make two integer arrays, x1 and x2, ie. x1=array([1,2,3,4,5],int8)  
3. x3=array([x1,x2])
4. x3 What is the expected output? What do you see instead? Should see x3, instead Spyder hangs What version of the product are you using? On what operating system? 2.0.11 on Windows 7 Enterprise 64 

Please provide any additional information below

. This appears to be a consequence of having "show array min and max" checked in variable explorer. If this isn't checked, x3 is shown, and if you then check the option, Spyder hangs.

Please see the last entry of the monitor log:

======================================
Logging time: Wed Jun 22 15:47:40 2011

======================================

Context
\-------

\<spyderlib.widgets.externalshell.monitor.PacketNotReceived object at 0x05BE0ED0>

Traceback
\---------

Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 484, in run
    self.update_remote_view(namespace)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 390, in update_remote_view
    remote_view = make_remote_view(glbs, settings, more_excluded_names)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 69, in make_remote_view
    collvalue=settings['collvalue'])
  File "C:\Python26\lib\site-packages\spyderlib\widgets\dicteditor.py", line 118, in value_to_display
    return 'Min: &#37;r\nMax: &#37;r' &#37; (value.min(), value.max())
ValueError: operands could not be broadcast together with shapes (3) (4)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=694_

**Comment by spyder-issues-migrator** [comment]
_From [DavidAnt...@gmail.com](https://code.google.com/u/108698404730356683634/) on 2011-09-07T00:11:23Z_

I tried to reproduce this, and couldn't see the error (on Ubuntu 10.04 x64). However, the instructions aren't complete - you don't show what you assign to x2. If you give the exact code which causes the problem then there is more chance of someone else reproducing it.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-09-07T01:53:01Z_

I can't reproduce this either.

**Status:** Invalid
