### ISSUE TITLE
The variable explorer is not working 

### ISSUE THREAD

**Issue by dantheman3232** [spyder-ide/spyder#6945]
File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser
      File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
      File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser
      File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
      File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
      File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
      File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
      File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
      File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
      File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: 
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser
      File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser
      File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser
      File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser
      File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser
      File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
      File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 341, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 212, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 61, in refresh_namespacebrowser

**Comment by CAM-Gerlach** [comment]
Apparently its a problem with Python itself, according to @ccordoba12 in #6876 , and according to him there's nothing we can really do about it, so not sure what to tell you...
