### ISSUE TITLE
sklearn is not imported due to a .dll failure

### ISSUE THREAD

**Issue by yiorgos1973** [spyder-ide/spyder#6959]
## Problem Description
no import for sklearn

### What steps will reproduce the problem?
2. import sklearn
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):

  File "<ipython-input-1-73edc048c06b>", line 1, in <module>
    from sklearn.model_selection import train_test_split

  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\__init__.py", line 134, in <module>
    from .base import clone

  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py", line 13, in <module>
    from .utils.fixes import signature

  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\__init__.py", line 11, in <module>
    from .validation import (as_float_array,

  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 18, in <module>
    from ..utils.fixes import signature

  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\fixes.py", line 144, in <module>
    from scipy.sparse.linalg import lsqr as sparse_lsqr  # noqa

  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\sparse\linalg\__init__.py", line 118, in <module>
    from .matfuncs import *

  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\sparse\linalg\matfuncs.py", line 19, in <module>
    import scipy.special

  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\special\__init__.py", line 640, in <module>
    from ._ufuncs import *

ImportError: DLL load failed: The specified procedure could not be found.

```

## Package Versions

* Spyder:3.2.6 or 3.2.8 
* Python:3.6.4
* Qt:
* PyQt:
* Operating System:windows7

### Dependencies

```
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.3 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

```
Problem was detected after upgrading Anaconda3 and Spyder. After uninstalling and reinstalling Anaconda3 problem continued

**Comment by ccordoba12** [comment]
> File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\special\__init__.py", line 640, in <module>
    from ._ufuncs import *

Sorry but this has nothing to do with Spyder but with Scipy instead. One thing you can try is to open the Anaconda Prompt and run there

    conda install -f scipy

to see if that solves this problem. Other than this advice, we can't help you, sorry.
