### ISSUE TITLE
Spyder fails to start on Linux

### ISSUE THREAD

**Issue by rmahajan14** [spyder-ide/spyder#6990]
## Problem Description
Installed Anaconda on Ubuntu, and it was successful.

However, when i try to launch spyder, I get an error. It is related to PyQt5. 
I noticed some issues related to the problem I am having:
#3383 (https://github.com/spyder-ide/spyder/issues/3383)
#3145 (https://github.com/spyder-ide/spyder/issues/3145)

but according to those, this issue was fixed in spyder 3.0 and up... so i am not sure what i am doing wrong..

### What steps will reproduce the problem?

1. Trying to run spyder
spyder

### What is the expected output? What do you see instead?
I expect to see an spyder launched, instead i get this error:

"Traceback (most recent call last):
  File "/home/rmahajan14/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rmahajan14/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/home/rmahajan14/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 144, in main
    from spyder.app import mainwindow
  File "/home/rmahajan14/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/home/rmahajan14/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: libXrender.so.1: cannot open shared object file: No such file or directory
"

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Package Versions

* Spyder:  3.2.6
* Python:  3.6.4
* Qt: 5.6.2
* PyQt: 5.6.0
* Operating System: 4.4.0-112-generic GNU/Linux

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by rmahajan14** [comment]
Based on some comments on the issues, i tried the following things as well:

1. conda update qt5

"PackageNotInstalledError: Package is not installed in prefix.
  prefix: /home/rmahajan14/anaconda3
  package name: qt5"

2.  conda update qtpy - this works, and I get

" qtpy:            1.3.1-py36h3691cc8_0  --> 1.4.0-py36_0"


However, i still have this same issue

**Comment by rmahajan14** [comment]
As a last resort, i did 
"conda update --all"
 My new versions are:
spyder                    3.2.8
pyqt                      5.9.2
qt                        5.9.5
qtpy                      1.4.0


I now get a different error related to QtWebEngineWidgets

"Traceback (most recent call last):
  File "/home/rmahajan14/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: libXcomposite.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rmahajan14/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/home/rmahajan14/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 159, in main
    from spyder.app import mainwindow
  File "/home/rmahajan14/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/home/rmahajan14/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
"

**Comment by rmahajan14** [comment]
I am sorry, but what do you man by headless server? How can i find out whether it is a headless server?

**Comment by rmahajan14** [comment]
I tried many things since then, and installed xterm too.

I now have the following errors:

"~ $ spyder
Traceback (most recent call last):
  File "/home/rmahajan14/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: libasound.so.2: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rmahajan14/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/home/rmahajan14/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 159, in main
    from spyder.app import mainwindow
  File "/home/rmahajan14/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/home/rmahajan14/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
"

**Comment by rmahajan14** [comment]
Specifically, based on another similar issue which i was seeing, i had done this

"sudo apt-get install libsm6 libxrender1 libfontconfig1"

@ccordoba12 

After that the libXrender disppeared, and I think now the error is basically that it is not finding 'PyQt5.QtWebKitWidgets' right?

**Comment by rmahajan14** [comment]
@ccordoba12  if you mean its a virtual machine, then yes, I have windows OS, so i created a virtual box for ubuntu.. I didnt think that would be a problem..

Just one last question - since i did install those 3 libraries  and that error relating to that disappeared, isnt it true that the error i am getting now basically states that it is not finding 'PyQt5.QtWebKitWidgets' right? So, are you saying that this "QtWebKitWidgets" is also specific to ubuntu installation?

It seems to me from the error (in this line -> from PyQt5.QtWebEngineWidgets import QWebEnginePage) that the error is related to PyQt5 installation(which does come with anaconda)?

Thankyou for all your help ! :)

**Comment by ccordoba12** [comment]
> if you mean its a virtual machine

No, I didn't.

> isnt it true that the error i am getting now basically states that it is not finding 'PyQt5.QtWebKitWidgets' right?

No, that's incorrect. Look at the error again:

    ImportError: libasound.so.2: cannot open shared object file: No such file or directory

That means you're missing Alsa too.

----

Look, it's clear you don't know how Linux works. Simply remove your virtual machine and install a new one with *all* default options from the Ubuntu installer. Don't customize anything during installation, and then you'll get all that Spyder needs to run.

**Comment by shaunster0** [comment]
I'm getting this issue too, trying to use spyder on bash for Windows (a.k.a. linux subsystem for windows). I did a default installation of Ubuntu on that, and get the errors

from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: libQt5WebEngineCore.so.5: cannot enable executable stack as shared object requires: Invalid argument

and

from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

**Comment by YBrule** [comment]
Same issue with a Debian bash for Windows (Debian subsystem for Windows), same error, conda is up-to-date, qtpy too, I'm using Xming as X server for Windows which works for other applications.

**Comment by nabriis** [comment]
You are most likely missing many graphics related interfaces if you are running on a sub-system or docker container of ubunto etc.

I had similar issues and ended up installing the following
´sudo apt-get install alsa'
for your particular issue.

I suggest installing ´apt-file´ using that to search for the missing files. Works many times (although not in this case)

**Comment by ssugrim** [comment]
For any one arriving here while trying to upgrade the pip installed version of spyder on an Ubuntu 16.04 Linux box the solution that worked for me was:

sudo apt-get install python-pyqt5.qtwebkit

**Comment by VishalVaddina** [comment]
sudo apt-get install python-pyqt5.qtwebkit

Just checked; This also works for Ubuntu-18.04-LTS.

**Comment by A7medAbdeldaim** [comment]
For me, i had some conflicts in installing so i did:
- pip uninstall spyder 
- apt remove spyder spyder3

then installing it again using apt:
- apt-get install spyder3

It works.

**Comment by Russell-Jones-OxPhys** [comment]
Try
python3 -m pip install --upgrade PyQtWebEngine

**Comment by ivitan** [comment]
It work for me.
`sudo pip install pyqt5==5.11.2`

**Comment by JDYG** [comment]
I want to install spyder in a docker that based on `pytorch/pytorch`. And I also confront this problem. I try many ways and finally fixed the problem. I think the steps may help you.
```
docker pull pytorch/pytorch # Ubuntu 16.04.5 LTS  Python 3.6.6
conda install -c anaconda spyder #install spyder
apt update #
apt install libgl1-mesa-glx  #fix that libGL.so.1: cannot open shared object file: No such file or directory
conda install pyqt=5.9.2     #I don't known why this version is 5.9.2 but it works
apt-get install python-pyqt5.qtwebkit
conda update -c conda-forge qt pyqt # this step is also important
```

**Comment by gussmith** [comment]
@JDYG 
> I want to install spyder in a docker that based on `pytorch/pytorch`. And I also confront this problem. I try many ways and finally fixed the problem. I think the steps may help you.
> 
> ```
> docker pull pytorch/pytorch # Ubuntu 16.04.5 LTS  Python 3.6.6
> conda install -c anaconda spyder #install spyder
> apt update #
> apt install libgl1-mesa-glx  #fix that libGL.so.1: cannot open shared object file: No such file or directory
> conda install pyqt=5.9.2     #I don't known why this version is 5.9.2 but it works
> apt-get install python-pyqt5.qtwebkit
> conda update -c conda-forge qt pyqt # this step is also important
> ```

Thanks for the post, I had been looking for a solution to run Spyder inside a docker container based on NVIDIA Pytorch. 
Unfortunately I followed all the steps listed, including downloading the docker pytorch/pytorch image, and I still get the error,
in addition to a missing library, which I will search: 

$ spyder 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: libXss.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/spyder/app/start.py", line 201, in main
    from spyder.app import mainwindow
  File "/opt/conda/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 84, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/opt/conda/lib/python3.7/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
