### ISSUE TITLE
Kernel not starting when using spyder

### ISSUE THREAD

**Issue by rohith402** [spyder-ide/spyder#6997]
## Description

**What steps will reproduce the problem?**

1. Before opening Spyder using Anaconda I've killed the process that was running on port 8888.

**What is the expected output? What do you see instead?**
Error ocurred while starting the kernel 

**Please provide any additional information below**

  File "C:\Users\sande\Anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 532, in _handle_kernel_died
    self.reset()
  File "C:\Users\sande\Anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 665, in reset
    self._show_interpreter_prompt()
  File "C:\Users\sande\Anaconda3\lib\site-packages\qtconsole\jupyter_widget.py", line 348, in _show_interpreter_prompt
    msg_id = self.kernel_client.execute('', silent=True)
  File "C:\Users\sande\Anaconda3\lib\site-packages\jupyter_client\client.py", line 254, in execute
    self.shell_channel.send(msg)
  File "C:\Users\sande\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 78, in send
    self.ioloop.add_callback(thread_send)
  File "C:\Users\sande\Anaconda3\lib\site-packages\tornado\ioloop.py", line 885, in add_callback
    raise RuntimeError("IOLoop is closing")
RuntimeError: IOLoop is closing

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
You need to update pyzmq ad jupyter_client to fix this. Please do that by opening the Anaconda Prompt and running there

    conda update pyzmq jupyter_client

**Comment by rohith402** [comment]
<b>Hi Carlos,

I've updated both pyzmq and jupyter_client but the problem still exists. This is the entire error I get in the IPython Console.</b>

Traceback (most recent call last):
File "C:\Users\sande\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 268, in 
main()
File "C:\Users\sande\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 252, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\sande\Anaconda3\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\sande\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 448, in initialize
self.init_sockets()
File "C:\Users\sande\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 251, in init_sockets
self.init_iopub(context)
File "C:\Users\sande\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 259, in init_iopub
self.iopub_thread = IOPubThread(self.iopub_socket, pipe=True)
File "C:\Users\sande\Anaconda3\lib\site‑packages\ipykernel\iostream.py", line 66, in __init__
self.io_loop = IOLoop(make_current=False)
File "C:\Users\sande\Anaconda3\lib\site‑packages\tornado\util.py", line 208, in __new__
instance.initialize(**args)
File "C:\Users\sande\Anaconda3\lib\site‑packages\tornado\platform\select.py", line 76, in initialize
super(SelectIOLoop, self).initialize(impl=_Select(), **kwargs)
TypeError: initialize() got an unexpected keyword argument 'make_current'
Traceback (most recent call last):
File "C:\Users\sande\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 268, in 
main()
File "C:\Users\sande\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 252, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\sande\Anaconda3\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\sande\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 448, in initialize
self.init_sockets()
File "C:\Users\sande\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 251, in init_sockets
self.init_iopub(context)
File "C:\Users\sande\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 259, in init_iopub
self.iopub_thread = IOPubThread(self.iopub_socket, pipe=True)
File "C:\Users\sande\Anaconda3\lib\site‑packages\ipykernel\iostream.py", line 66, in __init__
self.io_loop = IOLoop(make_current=False)
File "C:\Users\sande\Anaconda3\lib\site‑packages\tornado\util.py", line 208, in __new__
instance.initialize(**args)
File "C:\Users\sande\Anaconda3\lib\site‑packages\tornado\platform\select.py", line 76, in initialize
super(SelectIOLoop, self).initialize(impl=_Select(), **kwargs)
TypeError: initialize() got an unexpected keyword argument 'make_current'
Traceback (most recent call last):
File "C:\Users\sande\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 268, in 
main()
File "C:\Users\sande\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 252, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\sande\Anaconda3\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\sande\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 448, in initialize
self.init_sockets()
File "C:\Users\sande\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 251, in init_sockets
self.init_iopub(context)
File "C:\Users\sande\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 259, in init_iopub
self.iopub_thread = IOPubThread(self.iopub_socket, pipe=True)
File "C:\Users\sande\Anaconda3\lib\site‑packages\ipykernel\iostream.py", line 66, in __init__
self.io_loop = IOLoop(make_current=False)
File "C:\Users\sande\Anaconda3\lib\site‑packages\tornado\util.py", line 208, in __new__
instance.initialize(**args)
File "C:\Users\sande\Anaconda3\lib\site‑packages\tornado\platform\select.py", line 76, in initialize
super(SelectIOLoop, self).initialize(impl=_Select(), **kwargs)
TypeError: initialize() got an unexpected keyword argument 'make_current'
Traceback (most recent call last):
File "C:\Users\sande\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 268, in 
main()
File "C:\Users\sande\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 252, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\sande\Anaconda3\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\sande\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 448, in initialize
self.init_sockets()
File "C:\Users\sande\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 251, in init_sockets
self.init_iopub(context)
File "C:\Users\sande\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 259, in init_iopub
self.iopub_thread = IOPubThread(self.iopub_socket, pipe=True)
File "C:\Users\sande\Anaconda3\lib\site‑packages\ipykernel\iostream.py", line 66, in __init__
self.io_loop = IOLoop(make_current=False)
File "C:\Users\sande\Anaconda3\lib\site‑packages\tornado\util.py", line 208, in __new__
instance.initialize(**args)
File "C:\Users\sande\Anaconda3\lib\site‑packages\tornado\platform\select.py", line 76, in initialize
super(SelectIOLoop, self).initialize(impl=_Select(), **kwargs)
TypeError: initialize() got an unexpected keyword argument 'make_current'
Traceback (most recent call last):
File "C:\Users\sande\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 268, in 
main()
File "C:\Users\sande\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 252, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\sande\Anaconda3\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\sande\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 448, in initialize
self.init_sockets()
File "C:\Users\sande\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 251, in init_sockets
self.init_iopub(context)
File "C:\Users\sande\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 259, in init_iopub
self.iopub_thread = IOPubThread(self.iopub_socket, pipe=True)
File "C:\Users\sande\Anaconda3\lib\site‑packages\ipykernel\iostream.py", line 66, in __init__
self.io_loop = IOLoop(make_current=False)
File "C:\Users\sande\Anaconda3\lib\site‑packages\tornado\util.py", line 208, in __new__
instance.initialize(**args)
File "C:\Users\sande\Anaconda3\lib\site‑packages\tornado\platform\select.py", line 76, in initialize
super(SelectIOLoop, self).initialize(impl=_Select(), **kwargs)
TypeError: initialize() got an unexpected keyword argument 'make_current'


<b>Thanks.</b>

**Comment by CAM-Gerlach** [comment]
Maybe also try ``conda update tornado ipykernel spyder``?
