### ISSUE TITLE
profiler fails with non-ascii characters in source file

### ISSUE THREAD

**Issue by sbyrnes321** [spyder-ide/spyder#7031]
## Problem Description

Very similar to #3322 - the profiler won't work with non-ascii characters (e.g. β) in the source file. Unlike #3322, I get a "Profiler output" complaint box, it doesn't crash the whole program, but it also doesn't profile the code. The source file is UTF-8 encoded (I'm sure, I double-checked this in Notepad++) and runs fine with "F5".

### What steps will reproduce the problem?

1. Make a new py file with the line `print('β=1')`
2. Press F10 to profile it.

### What is the expected output? What do you see instead?

I expect it to profile the file. Instead an error box pops up as shown below:

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "C:\Users\steve\AppData\Local\Continuum\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\steve\AppData\Local\Continuum\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\steve\AppData\Local\Continuum\miniconda3\lib\cProfile.py", line 160, in <module>
    main()
  File "C:\Users\steve\AppData\Local\Continuum\miniconda3\lib\cProfile.py", line 153, in main
    runctx(code, globs, None, options.outfile, options.sort)
  File "C:\Users\steve\AppData\Local\Continuum\miniconda3\lib\cProfile.py", line 20, in runctx
    filename, sort)
  File "C:\Users\steve\AppData\Local\Continuum\miniconda3\lib\profile.py", line 64, in runctx
    prof.runctx(statement, globals, locals)
  File "C:\Users\steve\AppData\Local\Continuum\miniconda3\lib\cProfile.py", line 100, in runctx
    exec(cmd, globals, locals)
  File "C:/Users/steve/Desktop/untitled0.py", line 8, in <module>
    print('\u03b2=1')
  File "C:\Users\steve\AppData\Local\Continuum\miniconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u03b2' in position 0: character maps to <undefined>


```

## Package Versions

* Spyder: 3.2.8
* Python: 3.6.5 64bits
* Qt: 5.9.4
* PyQt5: 5.9.2
* Operating System: Windows 7 (with miniconda)

### Dependencies

```
IPython >=4.0    :  6.3.1 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.2 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
```

**Comment by CAM-Gerlach** [comment]
Thanks for the detailed report. I indeed was able to reproduce the error following the above procedure. @ccordoba12 ?

**Comment by sbyrnes321** [comment]
I just changed the title and description, the mere presence of β in the source file seems to be fine; the issue is when β is in a `print` command.

**Comment by oscargus** [comment]
The reason is that QProcess where the profiling code is executed is using the default system encoding when it executes the profiling code.

This can be solved by adding:
            `processEnvironment.insert("PYTHONIOENCODING", "utf8")`
here in profilergui.py:
```
            for envItem in env:
                envName, separator, envValue = envItem.partition('=')
                processEnvironment.insert(envName, envValue)
-->         processEnvironment.insert("PYTHONIOENCODING", "utf8")
            self.process.setProcessEnvironment(processEnvironment)
```
However, I assume that using utf8 may not always be the best approach. Instead, one would like to use the best guess of the file encoding, right? Or is utf8 considered so common that it can be used as a default and then one can live with the consequences?

A similar fix should work for #9356 as the error seems similar.

**Comment by sbyrnes321** [comment]
FYI, bug still exists in 4.0.0b6

**Comment by CAM-Gerlach** [comment]
@oscargus I'm not sure how that would make a difference since ``PYTHONIOENCODING`` only controls encoding for standard streams (stdin, stdout and stderr) which in Python 3.6+ on Windows (as well as Mac OS and on the vast majority of Linux systems) is already UTF-8 by default, which is the OP's platform and version. Furthermore, the [Python docs state](https://docs.python.org/3/using/cmdline.html) 

> Changed in version 3.6: On Windows, the encoding specified by this variable is ignored for interactive console buffers unless PYTHONLEGACYWINDOWSSTDIO is also specified. Files and pipes redirected through the standard streams are not affected. 

It seems unlikely the OP enabled `` PYTHONLEGACYWINDOWSFSENCODING`` without knowing it, but that would explain the problem since I can't repro it on Python 3.7, Spyder 4 and my Windows 8.1 box.

However ``systempreferredencoding`` is still the local code page on Windows (though generally nowadays the most people prefer and tend to even assume `utf-8` for it and are surprised at the default behavior) but AFAIK that's mostly just used for ``open``. ``PYTHONUTF8`` would coerce that to UTF-8 as well but that's only available on Python 3.7+.

Also to the note, the default source file encoding for Python 3 is UTF-8 and in working with dozens if not hundreds of different projects over the years from countries all around the world I don't think I've ever seen any Python 3 code written in a different encoding; by design it would need to declared at the top of the source file with a vi or emacs-style encoding message but I've never seen it done with an encoding other than UTF-8. The default standard stream and filesystem encoding for Python is UTF-8 on all platforms except for esoteric *nixes where it is explicitly configured to someone other than the default of either UTF-8, ASCII or the legacy C locale.

**Comment by CAM-Gerlach** [comment]
Also to the note, the default source file encoding for Python 3 is UTF-8 and in working with dozens if not hundreds of different projects over the years from countries all around the world I don't think I've ever seen any Python 3 code written in a different encoding; by design it would need to declared at the top of the source file with a vi or emacs-style encoding message but I've never seen it done with an encoding other than UTF-8. The default standard stream and filesystem encoding for Python is UTF-8 on all platforms except for esoteric *nixes where it is explicitly configured to someone other than the default of either UTF-8, ASCII or the legacy C locale.

**Comment by ccordoba12** [comment]
@steff456, please take a look at this one.
