### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by notuntoward** [spyder-ide/spyder#7040]
### What steps will reproduce the problem?

I don't know how to reproduce this, but this crash occured when I did a paste with Ctrl-V in the editor

### Traceback
```python-traceback
  File "C:\Users\scotto\Anaconda3\lib\site-packages\spyder\config\user.py", line 114, in _save
    _write_file(fname)
  File "C:\Users\scotto\Anaconda3\lib\site-packages\spyder\config\user.py", line 110, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\scotto\\OneDrive\\scotto\\.spyder-py3\\spyder.ini'

Traceback (most recent call last):
  File "C:\Users\scotto\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 1667, in save_breakpoints
    save_breakpoints(filename, breakpoints)
  File "C:\Users\scotto\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 84, in save_breakpoints
    CONF.set('run', 'breakpoints', bp_dict)
  File "C:\Users\scotto\Anaconda3\lib\site-packages\spyder\config\user.py", line 449, in set
    self._save()
  File "C:\Users\scotto\Anaconda3\lib\site-packages\spyder\config\user.py", line 124, in _save
    raise(e)
  File "C:\Users\scotto\Anaconda3\lib\site-packages\spyder\config\user.py", line 118, in _save
    os.remove(fname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\scotto\\OneDrive\\scotto\\.spyder-py3\\spyder.ini'
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.4
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.7.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.3 (OK)
```

**Comment by CAM-Gerlach** [comment]
Or, something else has a lock on the file...e.g. you've got it open somewhere.

**Comment by notuntoward** [comment]
I write protection doesn't seem to be the problem because I can write to C:\Users\scotto\OneDrive\scotto and C:\Users\scotto\OneDrive\scotto\.spyder-py3

Maybe a previous Spyder crash left the file locked?  In any case, I don't have any problems now.
