### ISSUE TITLE
cannot launch spyder in Terminal

### ISSUE THREAD

**Issue by daisy20170101** [spyder-ide/spyder#7054]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/duoli/anaconda3/lib/python3.6/site-packages/spyder/plugins/__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "/Users/duoli/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "/Users/duoli/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1033, in create_new_client
    self.connect_client_to_kernel(client)
  File "/Users/duoli/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1059, in connect_client_to_kernel
    stderr_file)
  File "/Users/duoli/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1485, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "/Users/duoli/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 239, in start_kernel
    self.write_connection_file()
  File "/Users/duoli/anaconda3/lib/python3.6/site-packages/jupyter_client/connect.py", line 472, in write_connection_file
    kernel_name=self.kernel_name
  File "/Users/duoli/anaconda3/lib/python3.6/site-packages/jupyter_client/connect.py", line 137, in write_connection_file
    with open(fname, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/Users/duoli/Library/Jupyter/runtime/kernel-0a2b7ec62dd8.json'
Traceback (most recent call last):
  File "/Users/duoli/anaconda3/lib/python3.6/site-packages/spyder/plugins/editor.py", line 1853, in load
    self.edit_filetypes = get_edit_filetypes()
  File "/Users/duoli/anaconda3/lib/python3.6/site-packages/spyder/config/utils.py", line 124, in get_edit_filetypes
    supported_exts = _get_pygments_extensions()
  File "/Users/duoli/anaconda3/lib/python3.6/site-packages/spyder/config/utils.py", line 86, in _get_pygments_extensions
    for lx in lexers.get_all_lexers():
  File "/Users/duoli/anaconda3/lib/python3.6/site-packages/pygments/lexers/__init__.py", line 53, in get_all_lexers
    for lexer in find_plugin_lexers():
  File "/Users/duoli/anaconda3/lib/python3.6/site-packages/pygments/plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (setuptools 18.2 (/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages), Requirement.parse('setuptools>=18.5'))
Traceback (most recent call last):
  File "/Users/duoli/anaconda3/lib/python3.6/site-packages/spyder/plugins/editor.py", line 1853, in load
    self.edit_filetypes = get_edit_filetypes()
  File "/Users/duoli/anaconda3/lib/python3.6/site-packages/spyder/config/utils.py", line 124, in get_edit_filetypes
    supported_exts = _get_pygments_extensions()
  File "/Users/duoli/anaconda3/lib/python3.6/site-packages/spyder/config/utils.py", line 86, in _get_pygments_extensions
    for lx in lexers.get_all_lexers():
  File "/Users/duoli/anaconda3/lib/python3.6/site-packages/pygments/lexers/__init__.py", line 53, in get_all_lexers
    for lexer in find_plugin_lexers():
  File "/Users/duoli/anaconda3/lib/python3.6/site-packages/pygments/plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (setuptools 18.2 (/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages), Requirement.parse('setuptools>=18.5'))

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
There are two errors you're experiencing:

> PermissionError: [Errno 13] Permission denied: '/Users/duoli/Library/Jupyter/runtime/kernel-0a2b7ec62dd8.json'

You don't have write permissions to this directory, which is needed to create json file for the IPython console. Please be sure that that directory is writable.

> pkg_resources.VersionConflict: (setuptools 18.2 (/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages), Requirement.parse('setuptools>=18.5'))

You need to update `setuptools` to a more recent version. You can do that with `pip install -U setuptools`. However, is very bad practice to install new stuff in your system Python. I'd recommend you to remove every new package you installed there and install Anaconda instead.
