### ISSUE TITLE
Configuration file error when starting Spyder

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#707]
_From [ajac...@gmail.com](https://code.google.com/u/110491667261836467246/) on 2011-07-07T03:19:32Z_

What steps will reproduce the problem?

 When I try to run Spyder nothing happens (not even the splash screen appears). 

If I run it from the command line I get the following error (full traceback is detailed bellow):

IOError: [Errno 22] invalid mode ('w') or filename: 'C:\\Users\\Adrian\\.spyder2\\.spyder.ini'

If I try to open the .spyder.ini file from a python shell by doing

foo=file('C:\\Users\\Adrian\\.spyder2\\.spyder.ini','w')

It opens Ok, I don't get the same error.
Finally I've found out that if I keep the '.spyder.ini' file open in a python shell and then run Spyder, then it runs Ok.
(I've checked the file permissions, reinstalled Spyder several times, erased the .spyder2 folder, but nothing seems to work) What version of the product are you using? On what operating system? I'm using Spyder 2.0.12 on Windows 7 

Please provide any additional information below

. Traceback (most recent call last):
  File "spyder", line 2, in \<module>
    from spyderlib import spyder
  File "C:\Python26\lib\site-packages\spyderlib\spyder.py", line 49, in \<module>
    from spyderlib.utils.environ import WinUserEnvDialog
  File "C:\Python26\lib\site-packages\spyderlib\utils\environ.py", line 16, in \<module>
    from spyderlib.config import _
  File "C:\Python26\lib\site-packages\spyderlib\config.py", line 476, in \<module>
    set_default_color_scheme(_name, replace=False)
  File "C:\Python26\lib\site-packages\spyderlib\config.py", line 473, in set_default_color_scheme
    set_color_scheme(name, COLORS[name], replace=replace)
  File "C:\Python26\lib\site-packages\spyderlib\config.py", line 466, in set_color_scheme
    CONF.set(section, option, color_scheme[key])
  File "C:\Python26\lib\site-packages\spyderlib\userconfig.py", line 306, in set
    self.__save()
  File "C:\Python26\lib\site-packages\spyderlib\userconfig.py", line 150, in __save
    conf_file = file(self.filename(),'w')
IOError: [Errno 22] invalid mode ('w') or filename: 'C:\\Users\\Adrian\\.spyder2\\.spyder.ini'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=707_

**Comment by spyder-issues-migrator** [comment]
_From [kmiec.r...@gmail.com](https://code.google.com/u/111432019875440097143/) on 2011-07-20T18:30:55Z_

I'm experiencing the same thing (Win 7 pro, 64-bit, Spyder 2.0.12).  If I try it from the command line (C:\Python26>python.exe Scripts\spyder) several times in a row it seems to work occasionally.  Perhaps some sort of race condition?

**Comment by spyder-issues-migrator** [comment]
_From [kmiec.r...@gmail.com](https://code.google.com/u/111432019875440097143/) on 2011-10-01T19:11:25Z_

In my case, this turned out to be due to antivirus software (AVG 2011, and 2012), apparently; I added an exception for the %HOMEPATH%\.spyder2 directory and it works fine now.  Found this after reading a posting on another site mentioning another anti-virus program... so perhaps something with whatever is going during Spyder startup looks suspicious to AV program heuristics...

**Comment by spyder-issues-migrator** [comment]
_From [ajac...@gmail.com](https://code.google.com/u/110491667261836467246/) on 2011-10-02T08:57:31Z_

I also have AVG installed. The problem was weird because it happened only some times, and some others spyder opened just fine. Since I've added the exception to AVG I didn't have the problem any more. Thanks for the solution!

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-06T07:39:31Z_

**Status:** Done
