### ISSUE TITLE
ImportError starting spyder: cannot import name '_overlapped'

### ISSUE THREAD

**Issue by marepobeda** [spyder-ide/spyder#7083]
Hi -

Completely new to Python.  Fresh install on Windows 10.  Produces the following error when I open Spyder from the Anaconda Navigator.

I can simply click "OK" to the pop-up window which reports application launch error and open/read what ever I'm doing.  Just don't want this problem to haunt me later.  All of this info is above my pay grade and I have no clue as to where to start.

Thanks!

![image](https://user-images.githubusercontent.com/39059240/39712107-d818c488-51ef-11e8-9a8e-4413d6f6dd8b.png)

(base) C:\Users\Marko Kraljevic>spyder --reset
Traceback (most recent call last):
  File "C:\Users\Marko Kraljevic\Anaconda\lib\asyncio\__init__.py", line 16, in <module>
    from . import _overlapped
ImportError: cannot import name '_overlapped'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Marko Kraljevic\Anaconda\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Marko Kraljevic\Anaconda\lib\site-packages\spyder\app\start.py", line 155, in main
    from spyder.app import mainwindow
  File "C:\Users\Marko Kraljevic\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 69, in <module>
    import rope.base.project  # analysis:ignore
  File "C:\Users\Marko Kraljevic\Anaconda\lib\site-packages\rope\base\project.py", line 9, in <module>
    from rope.base import exceptions, taskhandle, prefs, history, pycore, utils
  File "C:\Users\Marko Kraljevic\Anaconda\lib\site-packages\rope\base\pycore.py", line 6, in <module>
    import rope.base.libutils
  File "C:\Users\Marko Kraljevic\Anaconda\lib\site-packages\rope\base\libutils.py", line 6, in <module>
    from rope.base import pyobjectsdef
  File "C:\Users\Marko Kraljevic\Anaconda\lib\site-packages\rope\base\pyobjectsdef.py", line 5, in <module>
    import rope.base.oi.soi
  File "C:\Users\Marko Kraljevic\Anaconda\lib\site-packages\rope\base\oi\soi.py", line 11, in <module>
    from rope.base.oi.type_hinting.factory import get_type_hinting_factory
  File "C:\Users\Marko Kraljevic\Anaconda\lib\site-packages\rope\base\oi\type_hinting\factory.py", line 2, in <module>
    from rope.base.oi.type_hinting.providers import (
  File "C:\Users\Marko Kraljevic\Anaconda\lib\site-packages\rope\base\oi\type_hinting\providers\numpydocstrings.py", line 11, in <module>
    from numpydoc.docscrape import NumpyDocString
  File "C:\Users\Marko Kraljevic\Anaconda\lib\site-packages\numpydoc\__init__.py", line 5, in <module>
    from .numpydoc import setup
  File "C:\Users\Marko Kraljevic\Anaconda\lib\site-packages\numpydoc\numpydoc.py", line 31, in <module>
    from .docscrape_sphinx import get_doc_object, SphinxDocString
  File "C:\Users\Marko Kraljevic\Anaconda\lib\site-packages\numpydoc\docscrape_sphinx.py", line 11, in <module>
    from jinja2 import FileSystemLoader
  File "C:\Users\Marko Kraljevic\Anaconda\lib\site-packages\jinja2\__init__.py", line 82, in <module>
    _patch_async()
  File "C:\Users\Marko Kraljevic\Anaconda\lib\site-packages\jinja2\__init__.py", line 78, in _patch_async
    from jinja2.asyncsupport import patch_all
  File "C:\Users\Marko Kraljevic\Anaconda\lib\site-packages\jinja2\asyncsupport.py", line 13, in <module>
    import asyncio
  File "C:\Users\Marko Kraljevic\Anaconda\lib\asyncio\__init__.py", line 18, in <module>
    import _overlapped  # Will also be exported.
OSError: [WinError 0] The operation completed successfully

### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
I don't know why this error appears. I'd recommend you to uninstall and reinstall Anaconda again.

**Comment by ccordoba12** [comment]
Please let us know if that fixes your problem or not.

**Comment by marepobeda** [comment]
Still the same. Reinstalled Anaconda, even tried older and newer versions of spyder. I will post if anything can fix it.

**Comment by ccordoba12** [comment]
This looks like an installation problem, but I haven't seen it before, so I don't know what else to advise you.

@goanpeca, have you seen something like this before?

**Comment by ccordoba12** [comment]
Ok, here it seems a solution for this:

https://stackoverflow.com/questions/48077745/python-asyncio-overlapped-is-not-imported

Since this is not a problem directly related to Spyder, I'm closing this issue.
