### ISSUE TITLE
an unknown error

### ISSUE THREAD

**Issue by SirHao** [spyder-ide/spyder#7093]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "F:\Anaconda\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'session'

Traceback (most recent call last):
  File "F:\Anaconda\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "F:\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole.py", line 713, in toggle_view
    self.create_new_client(give_focus=False)
  File "F:\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1009, in create_new_client
    self.connect_client_to_kernel(client)
  File "F:\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1035, in connect_client_to_kernel
    stderr_file)
  File "F:\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1440, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "F:\Anaconda\lib\site-packages\jupyter_client\manager.py", line 238, in start_kernel
    self.write_connection_file()
  File "F:\Anaconda\lib\site-packages\jupyter_client\connect.py", line 426, in write_connection_file
    transport=self.transport, ip=self.ip, key=self.session.key,
  File "F:\Anaconda\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "F:\Anaconda\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "F:\Anaconda\lib\site-packages\jupyter_client\connect.py", line 344, in _session_default
    return Session(parent=self)
  File "F:\Anaconda\lib\site-packages\jupyter_client\session.py", line 482, in __init__
    self._check_packers()
  File "F:\Anaconda\lib\site-packages\jupyter_client\session.py", line 535, in _check_packers
    raise ValueError("message packed to %r, but bytes are required"%type(packed))
ValueError: message packed to <class 'str'>, but bytes are required

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
> File "F:\Anaconda\lib\site-packages\traitlets\traitlets.py", line 528, in get
value = obj._trait_values[self.name]
KeyError: 'session'

This looks like an installation issue. Please run in a system terminal (cmd.exe)

    conda update --all

and try again.

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response, as an assumed installation issue. If you can provide more information, please re-open and do so. Thanks.
