### ISSUE TITLE
Random segmentation faults

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#710]
_From [pmav99@gmail.com](https://code.google.com/u/pmav99@gmail.com/) on 2011-07-14T05:47:12Z_

Lately I've experienced quite a few random crashes with spyder. They happen when I try to run syntactically wrong code. 

What steps will reproduce the problem?

 - Run the code at the end of the report What is the expected output? What do you see instead? - Spyder crashes. If I start spyder the app from command line (even in debug mode)all I get is a segmentation fault error What version of the product are you using? On what operating system? - Python 2.7.2
 - Qt 4.7.2
 - PyQt4 4.8.4
 - Linux x86
 - Spyder 2.1.0alpha1 

Please provide any additional information below

. - The segmentation faults happened even in previous versions of Spyder (maybe the last 2 months more or less
 - This is the code that causes the segmentation fault

\#!/usr/bin/env python
\# -*- coding: utf-8 -*-
 
\#Importing libraries
import sys
from PyQt4 import QtGui, QtCore
 
\# Create a custom sub-Class
\# This time we inherit from the QLabel class
class HelloWorld(QtGui.QLabel):
    def __init__(self, msg):
        super(HelloWorld, self).__init__(msg)

        self.set    # This is the line that causes the problem
        self.setToolTip('This is a \<b>QWidget</b> widget')
        
        quit = QtGui.QPushButton('Close', self)
        quit.setGeometry(10, 10, 60, 35)

        self.connect(quit, QtCore.SIGNAL('clicked()'),
            QtGui.qApp, QtCore.SLOT('quit()'))
        
def main():
    app = QtGui.QApplication(sys.argv)
    window = HelloWorld("My first GUI!!!")
    window.show()
    sys.exit(app.exec_())
 
if __name__=='__main__':
    main()

 - The traceback is the following one:

Traceback (most recent call last):
  File "example.py", line 30, in \<module>
    main()
  File "example.py", line 25, in main
    window = HelloWorld("My first GUI!!!")
  File "example.py", line 14, in __init__
    self.set
AttributeError: 'HelloWorld' object has no attribute 'set'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=710_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-07-14T05:42:32Z_

Not reproduced on Windows XP, Python 2.6.2, Qt 4.7.1, PyQt 4.8.4, latest Spyder from default repository.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-07-14T05:51:08Z_

Not reproduced on Linux x86 (Ubuntu 10.04 LTS), Python 2.6.5, Qt 4.6.2, PyQt 4.7.2, latest Spyder from default repository.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-07-14T05:52:47Z_

BTW, to try and reproduce the problem you described, I'm opening a file containing the lines attached above and executing it, nothing happens except the expected traceback in the console.

**Comment by spyder-issues-migrator** [comment]
_From [pmav99@gmail.com](https://code.google.com/u/pmav99@gmail.com/) on 2011-07-14T06:56:24Z_

I know that it is strange. But It is not the first time I've experienced such a problem. The code snippet is just one example. Last month or two, on various occasions I had random crashes. This is just one example.

I am also using the latest Spyder from the default repo.

Is there a switch or something that i can activate in order to get some debugging info?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-07-19T12:56:02Z_

issue #712 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-07-19T13:03:55Z_

Unfortunately, debugging a segfault of PyQt4 is not an easy task. 

I have recently done a lot of changes that should improve stability. But you will have to pull these changes directly from the development version (Mercurial repository).

**Comment by spyder-issues-migrator** [comment]
_From [pmav99@gmail.com](https://code.google.com/u/pmav99@gmail.com/) on 2011-07-20T02:29:19Z_

Thank you!

I updated to the last dev version. And the above snippet no longer crashes the application. I hope the problems have been fixed. 

If anything else comes up, I will inform you.

**Comment by spyder-issues-migrator** [comment]
_From [pmav99@gmail.com](https://code.google.com/u/pmav99@gmail.com/) on 2011-07-20T02:56:54Z_

Unfortunately the problem still exists. I run another snippet without syntactical errors this time, although it leads to an exception.

Toggling the "Interact with the Interpreter after the execution" option makes the application stable.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-08-22T02:40:19Z_

Sorry for the delay. I was in vacations.

I've just added a wiki page to help people debugging segfaults: https://code.google.com/p/spyderlib/wiki/HowToDebugQtCrash To improve Spyder stability, please post here the backtrace and list of threads or anything else that seems significant.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-08-29T12:43:47Z_

I've recently made significant changes affecting Spyder's stability: https://code.google.com/p/spyderlib/source/detail?r=dc0ef68a90e82af3e9e6336fa5a22570c5819ed9 https://code.google.com/p/spyderlib/source/detail?r=4936b315cecc0e07e234be39f72edb89b0c54888 Could you please try again with the latest development version?

**Status:** Started  
  **Labels:** -Priority-Medium Priority-Critical Cat-SpyderGUI

**Comment by spyder-issues-migrator** [comment]
_From [pmav99@gmail.com](https://code.google.com/u/pmav99@gmail.com/) on 2011-08-29T13:40:02Z_

Hi Pierre, 

I believe that vacations, should never be a reason for apologizing!!! :D

Anyway, I just tried the example of the initial post with the latest dev version, and unfortunately it results into a segfault. Actually the first time I (re)ran it worked ok, but on all the subsequent runs it crashed spyder.


I will try to build the debug version of pyqt and python and report back.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-08-30T00:05:29Z_

Check with your Linux distribution package manager, but I'm sure you don't have to actually build these packages: they are probably available.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-09-01T04:49:41Z_

issue #745 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-09-24T06:20:40Z_

Is this issue still valid with Spyder v2.1.0beta1?

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2011-09-26T08:56:34Z_

I confirm segfault on current HEAD with PyQT4. I did the following:
1. New file, paste
2. Save in folder, parent to current project
3. Main Menu -> Run -> ... Traceback in console, no segfault
4. Press 'Run' button with white man in green circle  -> segfault

Backtrace is here - http://pastebin.com/cQUrZpJG Python backtrace is at http://pastebin.com/CscBXGkk Threads info:
  Id   Target Id         Frame 
  20   Thread 0xad350b70 (LWP 8238) "python" 0x00110424 in __kernel_vsyscall ()
  19   Thread 0xadb51b70 (LWP 8235) "python" 0x00110424 in __kernel_vsyscall ()
  18   Thread 0xae352b70 (LWP 8234) "python" 0x00110424 in __kernel_vsyscall ()
  17   Thread 0xaeb53b70 (LWP 8233) "python" 0x00110424 in __kernel_vsyscall ()
  16   Thread 0xaf354b70 (LWP 8232) "python" 0x00110424 in __kernel_vsyscall ()
  15   Thread 0xafb55b70 (LWP 8231) "python" 0x00110424 in __kernel_vsyscall ()
  14   Thread 0xb0356b70 (LWP 8230) "python" 0x00110424 in __kernel_vsyscall ()
  13   Thread 0xb58ffb70 (LWP 8229) "python" 0x00110424 in __kernel_vsyscall ()
  12   Thread 0xb6283b70 (LWP 8228) "python" 0x00110424 in __kernel_vsyscall ()
  3    Thread 0xb7058b70 (LWP 8219) "python" 0x00110424 in __kernel_vsyscall ()
  2    Thread 0xb7a37b70 (LWP 8218) "python" 0x00110424 in __kernel_vsyscall ()
* 1    Thread 0xb7fe46c0 (LWP 8214) "python" 0x42724867 in ?? () from /usr/lib/libQtCore.so.4

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-09-27T04:53:23Z_

Thanks for the update.

What happens if you comment the line 516 and line 517? https://code.google.com/p/spyderlib/source/browse/spyderlib/widgets/externalshell/pythonshell.py#516 https://code.google.com/p/spyderlib/source/browse/spyderlib/widgets/externalshell/pythonshell.py#517

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2011-09-27T23:50:01Z_

Everything is ok in this case.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-09-30T04:27:24Z_

This issue was closed by revision d0ca5a96132c .

**Status:** Fixed
