### ISSUE TITLE
Problem when starting Anaconda

### ISSUE THREAD

**Issue by khaledhamdi** [spyder-ide/spyder#7106]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\hamdi\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'session'

Traceback (most recent call last):
  File "C:\Users\hamdi\Anaconda3\lib\site-packages\jupyter_client\session.py", line 522, in _check_packers
    packed = pack(msg)
  File "C:\Users\hamdi\Anaconda3\lib\site-packages\jupyter_client\session.py", line 103, in <lambda>
    ensure_ascii=False, allow_nan=False,
  File "C:\Users\hamdi\Anaconda3\lib\site-packages\zmq\utils\jsonapi.py", line 43, in dumps
    s = s.encode('utf8, udc92')
LookupError: unknown encoding: utf8, udc92

Traceback (most recent call last):
  File "C:\Users\hamdi\Anaconda3\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\Users\hamdi\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\hamdi\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1033, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\Users\hamdi\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1059, in connect_client_to_kernel
    stderr_file)
  File "C:\Users\hamdi\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1485, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "C:\Users\hamdi\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 239, in start_kernel
    self.write_connection_file()
  File "C:\Users\hamdi\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 467, in write_connection_file
    transport=self.transport, ip=self.ip, key=self.session.key,
  File "C:\Users\hamdi\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "C:\Users\hamdi\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "C:\Users\hamdi\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 354, in _session_default
    return Session(parent=self)
  File "C:\Users\hamdi\Anaconda3\lib\site-packages\jupyter_client\session.py", line 482, in __init__
    self._check_packers()
  File "C:\Users\hamdi\Anaconda3\lib\site-packages\jupyter_client\session.py", line 530, in _check_packers
    msg.format(packer=self.packer, e=e, jsonmsg=jsonmsg)
ValueError: zmq.utils.jsonapi.jsonmod = <module 'json' from 'C:\\Users\\hamdi\\Anaconda3\\lib\\json\\__init__.py'>

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.2 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Looks similar to #7093 , and a likely installation issue. Please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues. Also, are you using any non-standard file encodings for anything? Also, try ``conda update --all`` in the Anaconda prompt.

If it still isn't working, please describe in detail the circumstances in which the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Calling for Help section as a comment to this issue, and we'll try to help if we can. Otherwise, your issue will likely have to be closed after one week (7 days). Thanks, and best of luck!

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.
