### ISSUE TITLE
Spyder3 crash on start.

### ISSUE THREAD

**Issue by Sasanita** [spyder-ide/spyder#7128]
```
An error ocurred while starting the kernel
Error in sitecustomize; set PYTHONVERBOSE for traceback:
AttributeError: module 'enum' has no attribute 'IntFlag'
Traceback (most recent call last):
File "/home/zparcheta/.local/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 245, in 
main()
File "/home/zparcheta/.local/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py", line 213, in main
from ipykernel.kernelapp import IPKernelApp
File "/home/zparcheta/.local/lib/python3.6/site‑packages/ipykernel/__init__.py", line 2, in 
from .connect import *
File "/home/zparcheta/.local/lib/python3.6/site‑packages/ipykernel/connect.py", line 8, in
import json
File "/home/zparcheta/anaconda2/envs/spyder/lib/python3.6/json/__init__.py", line 106, in 
from .decoder import JSONDecoder, JSONDecodeError
File "/home/zparcheta/anaconda2/envs/spyder/lib/python3.6/json/decoder.py", line 3, in 
import re
File "/home/zparcheta/anaconda2/envs/spyder/lib/python3.6/re.py", line 142, in 
class RegexFlag(enum.IntFlag):
```
I run spyder on python3 environment.
I uninstall anaconda and install it back but this error persists. 
I am using ubuntu.

**Comment by ccordoba12** [comment]
This line in your error

    File "/home/zparcheta/.local/lib/python3.6/site‑packages/spyder/utils/ipython/start_kernel.py

and this one

    /home/zparcheta/anaconda2/envs/spyder/lib/python3.6/json/__init__.py"

show that you mixing packages installed by pip and conda. That's a very, very bad strategy, because they are usually incompatible.

My suggestion is to remove this directory

   /home/zparcheta/.local/lib/python3.6/site‑packages/

and use only Anaconda to install the packages you need.

Other than that, we can't help you further, because it's up to you to fix the mess you made, sorry.

**Comment by CAM-Gerlach** [comment]
Also, our Readme, Installation Guide, Troubleshooting Guide, wiki, and documentation all warn against this.
