### ISSUE TITLE
Fatal error in Spyder

### ISSUE THREAD

**Issue by amit-sahu** [spyder-ide/spyder#7192]
An error ocurred while starting the kernel
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\io.py", line 52, in 
File "C:/Aarena/Arena\Movie_rating\abc.py", line 2, in 
ModuleNotFoundError: No module named 'scrapy'
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\io.py", line 52, in 
File "C:/Aarena/Arena\Movie_rating\abc.py", line 2, in 
ModuleNotFoundError: No module named 'scrapy'
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\io.py", line 52, in 
File "C:/Aarena/Arena\Movie_rating\abc.py", line 2, in 
ModuleNotFoundError: No module named 'scrapy'
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\io.py", line 52, in 
File "C:/Aarena/Arena\Movie_rating\abc.py", line 2, in 
ModuleNotFoundError: No module named 'scrapy'
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\io.py", line 52, in 
File "C:/Aarena/Arena\Movie_rating\abc.py", line 2, in 
ModuleNotFoundError: No module named 'scrapy'
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\io.py", line 52, in 
File "C:/Aarena/Arena\Movie_rating\abc.py", line 2, in 
ModuleNotFoundError: No module named 'scrapy'
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\io.py", line 52, in 
File "C:/Aarena/Arena\Movie_rating\abc.py", line 2, in 
ModuleNotFoundError: No module named 'scrapy'
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\io.py", line 52, in 
File "C:/Aarena/Arena\Movie_rating\abc.py", line 2, in 
ModuleNotFoundError: No module named 'scrapy'
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\io.py", line 52, in 
File "C:/Aarena/Arena\Movie_rating\abc.py", line 2, in 
ModuleNotFoundError: No module named 'scrapy'
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\io.py", line 52, in 
File "C:/Aarena/Arena\Movie_rating\abc.py", line 2, in 
ModuleNotFoundError: No module named 'scrapy'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
> File "C:/Aarena/Arena\Movie_rating\abc.py

This happens because you have this file is called `abc.py`. Please rename it to something else and you'll see the error go away.

**Comment by amit-sahu** [comment]
Dear Sir / Madam,

Thank you for suggesting it  but I have also tried renaming it ,it is not
working. The kernel has crashed it seems. I have reinstalled 3-4 time
anaconda but failed.


Thanking you
Amit
