### ISSUE TITLE
Spyder cannot open project on remote sharing folders

### ISSUE THREAD

**Issue by agzpaoyi** [spyder-ide/spyder#7219]
### What steps will reproduce the problem?
1. Put some python scripts on remote share folder,  "xx.xx.xx.xx\\some folder\\your project folder"
2. Create project from the directory on spyder, the internal concole will report some errs. 
3. Project explorer will not show the project file list.

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.0
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Windows 7

### Dependencies

```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.6.7 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
```

**Comment by ccordoba12** [comment]
> Create project from the directory on spyder, the internal concole will report some errs.

Please be specific: what errors are you seeing?

**Comment by agzpaoyi** [comment]
>>> Failed to write user configuration file.
Please submit a bug report.
Traceback (most recent call last):
  File "C:\Users\IV TEST\Anaconda3\lib\site-packages\spyder\config\user.py", line 114, in _save
    _write_file(fname)
  File "C:\Users\IV TEST\Anaconda3\lib\site-packages\spyder\config\user.py", line 110, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: '//109.104.115.26/Automation/Python-Scripts/PYTS\\.spyproject\\workspace.ini'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\IV TEST\Anaconda3\lib\site-packages\spyder\plugins\projects.py", line 241, in _create_project
    self.open_project(path=path)
  File "C:\Users\IV TEST\Anaconda3\lib\site-packages\spyder\plugins\projects.py", line 274, in open_project
    self.set_project_filenames(self.editor.get_open_filenames())
  File "C:\Users\IV TEST\Anaconda3\lib\site-packages\spyder\plugins\projects.py", line 349, in set_project_filenames
    self.current_active_project.set_recent_files(recent_files)
  File "C:\Users\IV TEST\Anaconda3\lib\site-packages\spyder\widgets\projects\type\__init__.py", line 74, in set_recent_files
    list(OrderedDict.fromkeys(recent_files)))
  File "C:\Users\IV TEST\Anaconda3\lib\site-packages\spyder\config\user.py", line 449, in set
    self._save()
  File "C:\Users\IV TEST\Anaconda3\lib\site-packages\spyder\config\user.py", line 124, in _save
    raise(e)
  File "C:\Users\IV TEST\Anaconda3\lib\site-packages\spyder\config\user.py", line 120, in _save
    _write_file(fname)
  File "C:\Users\IV TEST\Anaconda3\lib\site-packages\spyder\config\user.py", line 110, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: '//109.104.115.26/Automation/Python-Scripts/PYTS\\.spyproject\\workspace.ini'

**Comment by agzpaoyi** [comment]
The above errors occurred because I deleted the '.spyproject' folder and tried to open the project. So I have tried to open project on different PCs, there is no above error. But Project explorer still keeps empty, maybe because the directory contails IP address.

**Comment by ccordoba12** [comment]
> maybe because the directory contails IP address

Yes, I also think that's the reason for this problem. Are you able to browse your shared folder using the File Explorer?

**Comment by agzpaoyi** [comment]
Oh yes, Spyder's file explorer can show the files.

**Comment by CAM-Gerlach** [comment]
Hmm, interesting. So just to confirm, did you recreate the Spyder project in that directory? The project explorer won't be able to show you anything if it doesn't think it is in a valid project directory.

**Comment by agzpaoyi** [comment]
Yes, I have tried both ways, to open and to recreate the Spyder project. They behave the same.

**Comment by furste** [comment]
Same for me (spyder 3.3.1, spyder-kernels 0.2.6, Python 3.7.0, Win7-64bit):
If the share is connected as network drive (X:\some_folder), the project explorer works.
If the share is connected as network path like \\srv-01\some_folder, the project explorer stays empty (but everything else works)

**Comment by CAM-Gerlach** [comment]
@furste Did you receive the above error traceback? Assuming so, can you paste the last line (starting with ``FileNotFoundError``? Perhaps its an issue with Spyder not handling the syntax of the network path correctly, but I don't have one handy to test it on. Also, if you paste the path listed on that line into your file manage (e.g. Windows Explorer), does it work? Does Spyder's File Explorer pane work?

**Comment by furste** [comment]
@CAM-Gerlach I don't get any errors in the console. 
Spyder's File Explorer pane works.
If I enter the path visible in the 'Current working directory' toolbar into the windows explorer, I always end in the correct folder, regardless if `\\srv-01\some_folder` or `X:\some_folder`.

**Comment by CAM-Gerlach** [comment]
Okay, thanks @furste . As a final question, just to confirm—does the project actually open—i.e. does your session (previously open files with that project) load up?

@ccordoba12 Any insight on what might be occurring such that the File Explorer works, but the project explorer does not? My naive guess is that it might have to do with some edge case/mishandling of paths and path separators in this case vs. other Windows paths, but I don't have a network drive like this to test it on.

**Comment by ccordoba12** [comment]
Nop, sorry. It's probably a file uri thing that we need to pass correctly to Qt after taking it from the OS.

**Comment by furste** [comment]
@ccordoba12 Yes, if I open a `\\srv-01\some_folder` project, the lasst session of this project is properly restored. Everything is fine, except that the project explorer is empty.

**Comment by jasonmaskell** [comment]
I updated to beta 4.0.0b4 from 4.0.0b2 - and now I get this issue when opening a project folder - it's stored on a network drive. Here is the output from the error dialog:

```
  File "c:\program files (x86)\python365_64bit\lib\site-packages\spyder\plugins\projects\plugin.py", line 97, in <lambda>
    triggered=lambda v: self.open_project())
  File "c:\program files (x86)\python365_64bit\lib\site-packages\spyder\plugins\projects\plugin.py", line 319, in open_project
    self.main.editor.get_open_filenames())
  File "c:\program files (x86)\python365_64bit\lib\site-packages\spyder\plugins\projects\plugin.py", line 427, in set_project_filenames
    self.current_active_project.set_recent_files(recent_files)
  File "c:\program files (x86)\python365_64bit\lib\site-packages\spyder\plugins\projects\api.py", line 76, in set_recent_files
    for recent_file in recent_files]
  File "c:\program files (x86)\python365_64bit\lib\site-packages\spyder\plugins\projects\api.py", line 76, in <listcomp>
    for recent_file in recent_files]
  File "c:\program files (x86)\python365_64bit\lib\ntpath.py", line 586, in relpath
    path_drive, start_drive))
ValueError: path is on mount 'C:', start on mount '\\\\networkDrive\\users'

```

That last line appears to indicate that it is an issue related to the URI file path. If I try to explicitly use the drive letter instead (in the open dialog), I still get the same error.

I'm on Windows 10.

```
pygments >=2.0    :  2.4.0 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.0.1 (OK)
pyls >=0.27.0     :  v0.28.1 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.3 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.5.2 :  4.5.3 (OK)
IPython >=4.0     :  7.5.0 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)

```

**Comment by ccordoba12** [comment]
@jasonmaskell, your problem is being tracked on issue #10045. Please report it there so we don't forget to consider testing things on network drives.
