### ISSUE TITLE
I tried to import a dataset into spyder when I got this error

### ISSUE THREAD

**Issue by vickylance** [spyder-ide/spyder#7220]
## Description

**What steps will reproduce the problem?**

1. Import a csv dataset with '~' as the delimiter

**What is the expected output? What do you see instead?**

I expected it to import the dataset into a variable called traincsv

**Please provide any additional information below**

  File "C:\Softwares\Miniconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 575, in _set_step
    self.text_widget.get_comments())
  File "C:\Softwares\Miniconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 477, in open_data
    skiprows, comments)
  File "C:\Softwares\Miniconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 410, in process_data
    comments)
  File "C:\Softwares\Miniconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 386, in _shape_text
    line = [try_to_parse(to_text_string(x)) for x in line]
  File "C:\Softwares\Miniconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 386, in <listcomp>
    line = [try_to_parse(to_text_string(x)) for x in line]
  File "C:\Softwares\Miniconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 45, in try_to_parse
    _val = eval("%s('%s')" % (_t, value))
  File "<string>", line 1, in <module>
TypeError: bad operand type for unary -: 'str'
Traceback (most recent call last):
  File "C:\Softwares\Miniconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 575, in _set_step
    self.text_widget.get_comments())
  File "C:\Softwares\Miniconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 477, in open_data
    skiprows, comments)
  File "C:\Softwares\Miniconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 410, in process_data
    comments)
  File "C:\Softwares\Miniconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 386, in _shape_text
    line = [try_to_parse(to_text_string(x)) for x in line]
  File "C:\Softwares\Miniconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 386, in <listcomp>
    line = [try_to_parse(to_text_string(x)) for x in line]
  File "C:\Softwares\Miniconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 45, in try_to_parse
    _val = eval("%s('%s')" % (_t, value))
  File "<string>", line 1, in <module>
TypeError: bad operand type for unary -: 'str'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (OK)
numpy >=1.7      :  None (OK)
sphinx >=0.6.6   :  1.7.0 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by vickylance** [comment]
@ccordoba12 Unfortunately it cannot be done because the dataset contains reviews and it contains both tabs and commas

**Comment by ccordoba12** [comment]
The please use `pandas.read_csv` to read it. It has a lot of options you can adjust to make the job done.

**Comment by CAM-Gerlach** [comment]
You could also always try a different deliminator (e.g. any ASCII punctuation that isn't in your data, and preferably isn't particularly meaningful to Python). The problem occurs, as you may have guessed by now, due to Python interpreting the ``~`` as the bitwise inversion operator rather than just as a character.

**Comment by goanpeca** [comment]
I don't think this is an issue. Closing

**Comment by CAM-Gerlach** [comment]
Yeah, this doesn't really seem within scope to fix in the forseeable future.
