### ISSUE TITLE
Spyder throw "An error ocurred while starting the kernel"

### ISSUE THREAD

**Issue by Zeroto521** [spyder-ide/spyder#7227]
Update Anacoda to a new version(1.8.5)  happened that "An error ocurred while starting the kernel".

# Spyder Ipython Showing 
```
An error ocurred while starting the kernel
Unhandled exception in thread started by Traceback (most recent call last):
File "C:\Software\Anaconda3\lib\site‑packages\zmq\eventloop\ioloop.py", line 177, in start
File "C:\Software\Anaconda3\lib\site‑packages\tornado\ioloop.py", line 863, in start
event_pairs = self._impl.poll(poll_timeout)
File "C:\Software\Anaconda3\lib\site‑packages\zmq\eventloop\ioloop.py", line 123, in poll
File "C:\Software\Anaconda3\lib\site‑packages\zmq\eventloop\ioloop.py", line 123, in 
File "C:\Software\Anaconda3\lib\site‑packages\zmq\eventloop\ioloop.py", line 100, in _remap_events
"""
NameError: name 'POLLIN' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Software\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
self.run()
File "C:\Software\Anaconda3\lib\threading.py", line 864, in run
self._target(*self._args, **self._kwargs)
File "C:\Software\Anaconda3\lib\site‑packages\ipykernel\iostream.py", line 78, in _thread_main
self.io_loop.start()
File "C:\Software\Anaconda3\lib\site‑packages\zmq\eventloop\ioloop.py", line 178, in start
NameError: name 'ZMQError' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Software\Anaconda3\lib\site‑packages\ipykernel\iostream.py", line 97, in _event_pipe
event_pipe = self._local.event_pipe
AttributeError: '_thread._local' object has no attribute 'event_pipe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Software\Anaconda3\lib\threading.py", line 884, in _bootstrap
self._bootstrap_inner()
File "C:\Software\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
(self.name, _format_exc()), file=_sys.stderr)
File "C:\Software\Anaconda3\lib\site‑packages\ipykernel\iostream.py", line 376, in write
self.pub_thread.schedule(lambda : self._buffer.write(string))
File "C:\Software\Anaconda3\lib\site‑packages\ipykernel\iostream.py", line 203, in schedule
self._event_pipe.send(b'')
File "C:\Software\Anaconda3\lib\site‑packages\ipykernel\iostream.py", line 101, in _event_pipe
event_pipe = ctx.socket(zmq.PUSH)
File "C:\Software\Anaconda3\lib\site‑packages\zmq\sugar\context.py", line 146, in socket
s = self._socket_class(self, socket_type, **kwargs)
File "C:\Software\Anaconda3\lib\site‑packages\zmq\sugar\socket.py", line 58, in __init__
super(Socket, self).__init__(*a, **kw)
TypeError: super(type, obj): obj must be an instance or subtype of type
Traceback (most recent call last):
File "C:\Software\Anaconda3\lib\site‑packages\zmq\eventloop\ioloop.py", line 177, in start
File "C:\Software\Anaconda3\lib\site‑packages\tornado\ioloop.py", line 863, in start
event_pairs = self._impl.poll(poll_timeout)
File "C:\Software\Anaconda3\lib\site‑packages\zmq\eventloop\ioloop.py", line 123, in poll
File "C:\Software\Anaconda3\lib\site‑packages\zmq\eventloop\ioloop.py", line 123, in 
File "C:\Software\Anaconda3\lib\site‑packages\zmq\eventloop\ioloop.py", line 100, in _remap_events
"""
NameError: name 'POLLIN' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Software\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 269, in 
main()
File "C:\Software\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 265, in main
kernel.start()
File "C:\Software\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 478, in start
self.io_loop.start()
File "C:\Software\Anaconda3\lib\site‑packages\zmq\eventloop\ioloop.py", line 178, in start
NameError: name 'ZMQError' is not defined
```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.
