### ISSUE TITLE
numpy test all pass in terminal but some failed in spyder

### ISSUE THREAD

**Issue by beew** [spyder-ide/spyder#7309]
Perform numpy test in terminal, all passed

```
$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.14.5'
>>> np.__file__
'/home/beew/.local/lib/python3.5/site-packages/numpy-1.14.5-py3.5-linux-x86_64.egg/numpy/__init__.py'
>>> np.show_config()
lapack_mkl_info:
    library_dirs = ['/opt/intel/mkl/lib/intel64/']
    include_dirs = ['/opt/intel/mkl/include']
    libraries = ['mkl_rt', 'pthread']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['/opt/intel/mkl/lib/intel64/']
    include_dirs = ['/opt/intel/mkl/include']
    libraries = ['mkl_rt', 'pthread']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['/opt/intel/mkl/lib/intel64/']
    include_dirs = ['/opt/intel/mkl/include']
    libraries = ['mkl_rt', 'pthread']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
blas_mkl_info:
    library_dirs = ['/opt/intel/mkl/lib/intel64/']
    include_dirs = ['/opt/intel/mkl/include']
    libraries = ['mkl_rt', 'pthread']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
>>> np.test(verbose=3)
.............
Ran 6821 tests in 28.792s

OK (KNOWNFAIL=14, SKIP=15)
<nose.result.TextTestResult run=6821 errors=0 failures=0>

```
Doing same in spyder
```
======================================================================
FAIL: numpy.core.tests.test_scalarprint.TestRealScalars.test_py2_float_print
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/beew/.local/lib/python3.5/site-packages/numpy-1.14.5-py3.5-linux-x86_64.egg/numpy/core/tests/test_scalarprint.py", line 96, in test_py2_float_print
    assert_equal(capture, repr(np.sqrt(2)))
  File "/home/beew/.local/lib/python3.5/site-packages/numpy-1.14.5-py3.5-linux-x86_64.egg/numpy/testing/nose_tools/utils.py", line 411, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: ''
 DESIRED: '1.4142135623730951'

======================================================================
FAIL: numpy.lib.tests.test_regression.TestRegression.test_refcount_vectorize
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/beew/.local/lib/python3.5/site-packages/numpy-1.14.5-py3.5-linux-x86_64.egg/numpy/lib/tests/test_regression.py", line 55, in test_refcount_vectorize
    _assert_valid_refcount(v)
  File "/home/beew/.local/lib/python3.5/site-packages/numpy-1.14.5-py3.5-linux-x86_64.egg/numpy/testing/nose_tools/utils.py", line 1337, in _assert_valid_refcount
    assert_(sys.getrefcount(i) >= rc)
  File "/home/beew/.local/lib/python3.5/site-packages/numpy-1.14.5-py3.5-linux-x86_64.egg/numpy/testing/nose_tools/utils.py", line 93, in assert_
    raise AssertionError(smsg)
AssertionError

----------------------------------------------------------------------
Ran 6821 tests in 39.514s
FAILED (KNOWNFAIL=14, SKIP=15, failures=2)
```
Spyder version: 3.2.8, installed with pip

Python version: 3.5.2

Operating System name/version: Ubuntu 16.04 64 bits

numpy 1.14.5 (previously 1.14.4) compiled myself against intel mkl.

P.S switch blas backend to openblas (by update-alternatives) same result. All passed running tests in terminal, same two failed in spyder

**Comment by dalthviz** [comment]
Hi @beew could you check if the standalone `qtconsole` presents the same results? I think you could run it with `jupyter qtconsole`. If something shows there maybe an issue in the [qtconsole project](https://github.com/jupyter/qtconsole) should be created.

**Comment by beew** [comment]
@dalthviz 

Hi, you are right, same errors occurs in jupyter qtconsole.

**Comment by ccordoba12** [comment]
Closing because this was reported upstream.
