### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by fdev31** [spyder-ide/spyder#7315]
### What steps will reproduce the problem?

I just started spyder automatically after downloading some .py file.

### Traceback
```python-traceback
  File "/usr/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 144, in icon
    if osp.isdir(fname):
  File "/usr/lib/python3.6/genericpath.py", line 42, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe8' in position 13: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 144, in icon
    if osp.isdir(fname):
  File "/usr/lib/python3.6/genericpath.py", line 42, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 11: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 144, in icon
    if osp.isdir(fname):
  File "/usr/lib/python3.6/genericpath.py", line 42, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 13: ordinal not in range(128)
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.11.0
* PyQt5 version: 5.10.1
* Operating system: Linux 4.16.13-2-ARCH

### Dependencies

```
pyflakes >=0.6.0 :  2.0.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.14.3 (OK)
sphinx >=0.6.6   :  1.7.5 (OK)
rope >=0.9.4     :  0.10.6 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
psutil >=0.3     :  5.4.6 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  0.28.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.3.1 (OK)
pylint >=0.25    :  1.9.2 (OK)
```

**Comment by ccordoba12** [comment]
I really don't understand this error. Is there more info you can provide us about it?

**Comment by ccordoba12** [comment]
Closing because of lack of response.
