### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by jeremymatt** [spyder-ide/spyder#7316]
### What steps will reproduce the problem?

I did not notice any problem whatsoever - I just got this message when I re-started spyder.  I had closed the program to use conda to update some packages. Everything seems fine, so I'm not sure why i'm getting this.   Using Anaconda(1.8.7) spyder

### Traceback
```python-traceback
  File "C:\Users\mattje\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'context'

Traceback (most recent call last):
  File "C:\Users\mattje\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\__init__.py", line 514, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\Users\mattje\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\mattje\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1046, in create_new_client
    self.connect_client_to_kernel(client, is_cython=is_cython)
  File "C:\Users\mattje\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1074, in connect_client_to_kernel
    is_cython=is_cython)
  File "C:\Users\mattje\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1522, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "C:\Users\mattje\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client\manager.py", line 261, in start_kernel
    self._connect_control_socket()
  File "C:\Users\mattje\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client\manager.py", line 210, in _connect_control_socket
    self._control_socket = self.connect_control()
  File "C:\Users\mattje\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client\connect.py", line 571, in connect_control
    return self._create_connected_socket('control', identity=identity)
  File "C:\Users\mattje\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client\connect.py", line 543, in _create_connected_socket
    sock = self.context.socket(socket_type)
  File "C:\Users\mattje\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "C:\Users\mattje\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "C:\Users\mattje\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client\manager.py", line 42, in _context_default
    return zmq.Context.instance()
  File "C:\Users\mattje\AppData\Local\Continuum\anaconda3\lib\site-packages\zmq\sugar\context.py", line 108, in instance
    cls._instance = cls(io_threads=io_threads)
  File "zmq/backend/cython/context.pyx", line 49, in zmq.backend.cython.context.Context.__cinit__
zmq.error.ZMQError: Connection refused
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating system: Windows 7

### Dependencies

```
pyflakes >=0.6.0 :  2.0.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.7.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.4.0 (OK)
pylint >=0.25    :  1.9.2 (OK)
```

**Comment by ccordoba12** [comment]
> zmq.error.ZMQError: Connection refused

This means that your firewall/antivirus is blocking all local network traffic in your PC. You need to add rules to allow Anaconda's `python.exe` and `pythonw.exe` to be able to open ports and create traffic internally (they don't need access outside your computer).

**Comment by jeremymatt** [comment]
Thanks for the response!  This seems to be a fairly rare occurrence - most of the time it starts up fine.  Can't easily edit firewall/antivirus though - IT has it locked down.
