### ISSUE TITLE
IPython v0.11: module code completion is failing

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#732]
_From [rustiksn...@gmail.com](https://code.google.com/u/113969073312347819745/) on 2011-08-16T02:16:45Z_

\>> 

What steps will reproduce the problem?

1. Run IPython console
2. type "fro" and hit Tab button

\>> What is the expected output? What do you see instead?
Some error to the stdout and no completion for this.

\>> What version of the product are you using? On what operating system?
Linux, mercurial version

\>> 

Please provide any additional information below

.
You can add try-except block to line 896-900 to remove this bug.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=732_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-08-16T07:20:25Z_

Hi,

1. What version of IPython are you running?
2. Please post the stdout error that you are seeing.
3. To which file do we have to add the try-except block?

**Summary:** IPython module code completion is failing  
  **Labels:** Cat-CodeCompletion

**Comment by spyder-issues-migrator** [comment]
_From [edpra...@googlemail.com](https://code.google.com/u/102353052357015570174/) on 2011-08-21T05:22:25Z_

same here. TAB completion on objects/variables etc. in Ipython console is not working.
I'm using the current spyder development version and Ipython 0.11.

Here is what I get from the internal console. This is probably the same message rustiksn... got:


Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spyderlib/widgets/shell.py", line 297, in keyPressEvent
    self.postprocess_keyevent(event)
  File "/usr/local/lib/python2.7/site-packages/spyderlib/widgets/shell.py", line 777, in postprocess_keyevent
    ShellBaseWidget.postprocess_keyevent(self, event)
  File "/usr/local/lib/python2.7/site-packages/spyderlib/widgets/shell.py", line 352, in postprocess_keyevent
    self._key_tab()
  File "/usr/local/lib/python2.7/site-packages/spyderlib/widgets/shell.py", line 809, in _key_tab
    self.show_code_completion(automatic=False)
  File "/usr/local/lib/python2.7/site-packages/spyderlib/widgets/shell.py", line 973, in show_code_completion
    automatic=automatic)
  File "/usr/local/lib/python2.7/site-packages/spyderlib/widgets/sourcecode/base.py", line 897, in show_completion_list
    underscore = set([comp for comp in completions if comp.startswith('_')])
AttributeError: 'list' object has no attribute 'startswith'

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-08-21T06:25:41Z_

**Summary:** IPython v0.11: module code completion is failing  
  **Labels:** -Cat-CodeCompletion Cat-Console

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-08-21T06:30:37Z_

This issue was closed by revision 942edf322a13 .

**Status:** Fixed
