### ISSUE TITLE
Spyder Crashes:Does not launch

### ISSUE THREAD

**Issue by skandaswamy** [spyder-ide/spyder#7342]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?
Launch Spyder after installation. 
1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'context'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3208, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3084, in run_spyder
    main.setup()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1172, in setup
    self.setup_layout(default=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1457, in setup_layout
    self.setup_default_layouts('default', settings)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1633, in setup_default_layouts
    widget.toggle_view(True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1046, in create_new_client
    self.connect_client_to_kernel(client, is_cython=is_cython)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1074, in connect_client_to_kernel
    is_cython=is_cython)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1522, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 261, in start_kernel
    self._connect_control_socket()
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 210, in _connect_control_socket
    self._control_socket = self.connect_control()
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 571, in connect_control
    return self._create_connected_socket('control', identity=identity)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 543, in _create_connected_socket
    sock = self.context.socket(socket_type)
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 42, in _context_default
    return zmq.Context.instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\sugar\context.py", line 108, in instance
    cls._instance = cls(io_threads=io_threads)
  File "zmq/backend/cython/context.pyx", line 49, in zmq.backend.cython.context.Context.__cinit__
zmq.error.ZMQError: Unknown error

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  3.2.8 
* Python version:  3.6.5
* Qt version:  5.9.5
* PyQt version:  5.9.2
* Operating System name/version: Windows 10 Home 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
This is not a error in Spyder. It seems you corrupted your Anaconda installation, so you have two options:

1. Open an Anaconda Prompt, run there `conda install -f pyzmq` and try again.
2. If that doesn't work, I'm afraid you'll have to reinstall Anaconda.

**Comment by rahulbhatkar690** [comment]
When I start Spyder after installation, I get the following error message. Please suggest what should be done to rectify this issue:
----------------------------------------
Traceback (most recent call last):
File "C:\Program Files\Spyder\pkgs\traitlets\traitlets.py", line 535, in get
value = obj._trait_values[self.name]
KeyError: 'context'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Program Files\Spyder\pkgs\spyder\plugins\ipythonconsole\plugin.py", line 1498, in create_kernel_manager_and_kernel_client
env=kernel_spec.env)
File "C:\Program Files\Spyder\pkgs\jupyter_client\manager.py", line 342, in start_kernel
self.post_start_kernel(**kw)
File "C:\Program Files\Spyder\pkgs\qtconsole\manager.py", line 60, in post_start_kernel
super().post_start_kernel(**kw)
File "C:\Program Files\Spyder\pkgs\jupyter_client\manager.py", line 323, in post_start_kernel
self._connect_control_socket()
File "C:\Program Files\Spyder\pkgs\jupyter_client\manager.py", line 255, in _connect_control_socket
self._control_socket = self._create_connected_socket('control')
File "C:\Program Files\Spyder\pkgs\jupyter_client\connect.py", line 548, in _create_connected_socket
sock = self.context.socket(socket_type)
File "C:\Program Files\Spyder\pkgs\traitlets\traitlets.py", line 575, in __get__
return self.get(obj, cls)
File "C:\Program Files\Spyder\pkgs\traitlets\traitlets.py", line 538, in get
default = obj.trait_defaults(self.name)
File "C:\Program Files\Spyder\pkgs\traitlets\traitlets.py", line 1578, in trait_defaults
return self._get_trait_default_generator(names[0])(self)
File "C:\Program Files\Spyder\pkgs\jupyter_client\manager.py", line 64, in _context_default
return zmq.Context()
File "zmq\backend\cython\context.pyx", line 48, in zmq.backend.cython.context.Context.__cinit__
zmq.error.ZMQError: timed out
--------------------------------------

**Comment by ccordoba12** [comment]
@rahulbhatkar690, this could be caused by your firewall and/or antivirus, which is blocking inter-process communications in your computer.

Please disable them and try again.
