### ISSUE TITLE
Spyder crashed during last session

### ISSUE THREAD

**Issue by Xinrux** [spyder-ide/spyder#7345]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I installed anaconde3 on my mac. When I launched Spyder I got the "Spyder crashed during last session" statement window. I tried to use the command line option '--reset':
spyder --reset but it did not work. 

By the way, when I managed to launch jupyter notebook. However, when I tried to open a .ipynb and open a new .ipynb, I got 'notebook loading error'  and "Unexpected error while saving file: Untitled.ipynb [Errno 13] Permission denied: ". 

I have been stuck in these two problems two days. Please help!

### What steps reproduce the problem?

1. installed anaconde3 on my mac
2. launched Spyder in anaconda-navigator
3. 'Spyder crashed during last session' came out  

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.2.8
* Python version: 3.6
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Please launch Spyder from Terminal.app to see if there are some errors reported there.

**Comment by Xinrux** [comment]
Hi @ccordoba12 , I launch Spyder from Terminal.app and got the errors below

Traceback (most recent call last):
  File "/Users/Xinru/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3208, in main
    mainwindow = run_spyder(app, options, args)
  File "/Users/Xinru/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3084, in run_spyder
    main.setup()
  File "/Users/Xinru/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1172, in setup
    self.setup_layout(default=False)
  File "/Users/Xinru/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1457, in setup_layout
    self.setup_default_layouts('default', settings)
  File "/Users/Xinru/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1633, in setup_default_layouts
    widget.toggle_view(True)
  File "/Users/Xinru/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "/Users/Xinru/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1046, in create_new_client
    self.connect_client_to_kernel(client, is_cython=is_cython)
  File "/Users/Xinru/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1074, in connect_client_to_kernel
    is_cython=is_cython)
  File "/Users/Xinru/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1522, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "/Users/Xinru/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "/Users/Xinru/anaconda3/lib/python3.6/site-packages/jupyter_client/connect.py", line 472, in write_connection_file
    kernel_name=self.kernel_name
  File "/Users/Xinru/anaconda3/lib/python3.6/site-packages/jupyter_client/connect.py", line 137, in write_connection_file
    with open(fname, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/Users/Xinru/Library/Jupyter/runtime/kernel-bf43eeecf888.json'

**Comment by ccordoba12** [comment]
> PermissionError: [Errno 13] Permission denied: '/Users/Xinru/Library/Jupyter/runtime/kernel-bf43eeecf888.json'

Well, the error message is clear: you don't have permissions to write in the directory mentioned above, which is needed by Spyder to create kernels.

To fix it you need to run the following command in Terminal.app

    chmod -R u+rw /Users/Xinru/Library/Jupyter/runtime

If that doesn't work, then you could try

    chmod -R a+rw /Users/Xinru/Library/Jupyter/runtime

or

    sudo chmod -R a+rw /Users/Xinru/Library/Jupyter/runtime

**Comment by avaz-dot** [comment]
hello friends. I am new in programming.  I have an issue when open spyder. It was working today but after open saved file this
![prob](https://user-images.githubusercontent.com/64730965/83147662-0b06e400-a109-11ea-9ac4-bfbf37e43d21.PNG)
 problem displayed on the screen. Can you please help me?
