### ISSUE TITLE
script execution generates trace back in debug mode

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#735]
_From [david.ve...@gmail.com](https://code.google.com/u/108342766018366950755/) on 2011-08-18T10:18:40Z_

What steps will reproduce the problem?

 When a python console is closed there is a traceback visible when running in debug mode. This only persist when multiple consoles are open. Note that closing an Ipython console does not give this traceback.

Traceback when closing a console (consistent for python and Ipython):
Traceback (most recent call last):
  File "/home/dave/Projects/spyderlib/spyderlib/plugins/externalconsole.py", line 685, in \<lambda>
    lambda sid=id(shellwidget): self.process_finished(sid))
  File "/home/dave/Projects/spyderlib/spyderlib/plugins/externalconsole.py", line 716, in process_finished
    self.inspector.shell_terminated(shell.shell)
  File "/home/dave/Projects/spyderlib/spyderlib/plugins/inspector.py", line 657, in shell_terminated
    self.shell = self.get_running_python_shell()
  File "/home/dave/Projects/spyderlib/spyderlib/plugins/inspector.py", line 646, in get_running_python_shell
    shell = self.external_console.get_running_python_shell()
  File "/home/dave/Projects/spyderlib/spyderlib/plugins/externalconsole.py", line 455, in get_running_python_shell
    if shellwidget.is_interpreter():
TypeError: 'bool' object is not callable

Further, executing a script in the current console fails (for both python and Ipython) and delivers following traceback:

Traceback (most recent call last):
  File "/home/dave/Projects/spyderlib/spyderlib/plugins/externalconsole.py", line 462, in run_script_in_current_shell
    shellwidget = self.__find_python_shell(interpreter_only=True)
  File "/home/dave/Projects/spyderlib/spyderlib/plugins/externalconsole.py", line 435, in __find_python_shell
    if not interpreter_only or shellwidget.is_interpreter():
TypeError: 'bool' object is not callable What version of the product are you using? On what operating system? Ubuntu 10.04 64bit
Python 2.6.5, Qt 4.6.2, pyqt 4.7.2, IPython 0.10
Spyder 2.1.0dev ()
The problem appeared after following commit:
(95f5eaa15e09) Added new IPython plugin supporting IPython Qt console (requires IPython v0.12dev)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=735_

**Comment by spyder-issues-migrator** [comment]
_From [david.ve...@gmail.com](https://code.google.com/u/108342766018366950755/) on 2011-08-19T01:34:14Z_

There is a contradiction in the post:
Traceback when closing a console (consistent for python and Ipython):
is contradicting:
Note that closing an Ipython console does not give this traceback.

It seems that it kind of depends on how many consoles you have open whether or not closing an Ipython consoles results in the traceback.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-08-21T06:35:20Z_

This issue was closed by revision be83f1c93b0c .

**Status:** Fixed
