### ISSUE TITLE
Can't launch nothing from Anaconda

### ISSUE THREAD

**Issue by rb1990** [spyder-ide/spyder#7378]
## Problem Description
I am new with anaconda spyder and python, but I just downloaded anaconda and trying to launch spyder. The window with spyder 3 it does open (check the image) but nothing come up. after few minutes everything disappear and I get this error (check image 2).
Can please someone help me? Thanks a lot.
I've got the same error with qtconsole.
### What steps reproduce the problem?

1. download anaconda 5.2 python 3.6 spyder 3.2.8 on windows 10 64bit
2. open anaconda launcher
3. launch spyder

### What is the expected output? What do you see instead?
I expected spyder to open, but I don't see anything happening. It seems spyder is running, but it doesn't show on screen.

`(base) C:\Users\Riccardo>spyder
Traceback (most recent call last):
  File "C:\Users\Riccardo\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'context'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Riccardo\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3208, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\Riccardo\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3084, in run_spyder
    main.setup()
  File "C:\Users\Riccardo\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1172, in setup
    self.setup_layout(default=False)
  File "C:\Users\Riccardo\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1457, in setup_layout
    self.setup_default_layouts('default', settings)
  File "C:\Users\Riccardo\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1633, in setup_default_layouts
    widget.toggle_view(True)
  File "C:\Users\Riccardo\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\Riccardo\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1046, in create_new_client
    self.connect_client_to_kernel(client, is_cython=is_cython)
  File "C:\Users\Riccardo\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1074, in connect_client_to_kernel
    is_cython=is_cython)
  File "C:\Users\Riccardo\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1522, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "C:\Users\Riccardo\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 261, in start_kernel
    self._connect_control_socket()
  File "C:\Users\Riccardo\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 210, in _connect_control_socket
    self._control_socket = self.connect_control()
  File "C:\Users\Riccardo\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 571, in connect_control
    return self._create_connected_socket('control', identity=identity)
  File "C:\Users\Riccardo\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 543, in _create_connected_socket
    sock = self.context.socket(socket_type)
  File "C:\Users\Riccardo\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "C:\Users\Riccardo\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "C:\Users\Riccardo\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 42, in _context_default
    return zmq.Context.instance()
  File "C:\Users\Riccardo\Anaconda3\lib\site-packages\zmq\sugar\context.py", line 108, in instance
    cls._instance = cls(io_threads=io_threads)
  File "zmq/backend/cython/context.pyx", line 49, in zmq.backend.cython.context.Context.__cinit__
zmq.error.ZMQError: Unknown error
[4164:9312:0703/153514.462:ERROR:broker_win.cc(59)] Error reading broker pipe: Pipe terminata. (0x6D)
[2164:2136:0703/153514.463:ERROR:broker_win.cc(59)] Error reading broker pipe: Pipe terminata. (0x6D)
![cattura2](https://user-images.githubusercontent.com/40750862/42200533-11b53866-7ed7-11e8-9419-fbc284e432dc.PNG)
![cattura](https://user-images.githubusercontent.com/40750862/42200534-11e3102e-7ed7-11e8-9fb3-4209302b8a85.PNG)

`

**Comment by ccordoba12** [comment]
Did you try my last comment yesterday? Please open the Anaconda prompt and run there

    conda install -f zeromq pyzmq

**Comment by ccordoba12** [comment]
@mingwandroid: any ideas about this one? Google doesn't seem to help...

**Comment by mingwandroid** [comment]
Probably a virus scanner getting in the way?

**Comment by ccordoba12** [comment]
Good advice @mingwandroid, thanks!

@rb1990, I hope deactivating your antivirus/firewall works for you because I'm really out of ideas.

**Comment by rb1990** [comment]
![image](https://user-images.githubusercontent.com/40750862/42254062-2fae6868-7f88-11e8-9f26-639546a355e7.png)
Can't believe, I finally get it. Was definitely a virus scanner in the way. thanks @mingwandroid and @ccordoba12 for helping me. Really thanks!!

**Comment by rb1990** [comment]
Sorry for the late reply. Anyway, was an antivirus getting in the way. I just uninstalled "malwarebytes" and then install again Anaconda. Everything was fine. Thanks again
