### ISSUE TITLE
Spyder crash with a system wide installation of Sage

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#739]
_From [lopezto...@gmail.com](https://code.google.com/u/116115558710812750203/) on 2011-08-28T14:42:44Z_

What steps will reproduce the problem?

 1.Execute spyder and the program crash with this error message:

Traceback (most recent call last):
  File "spyder", line 2, in \<module>
    from spyderlib import spyder
  File "/home/tobal/Descargas/spyder-2.0.12/spyderlib/spyder.py", line 60, in \<module>
    from spyderlib.plugins.inspector import ObjectInspector
  File "/home/tobal/Descargas/spyder-2.0.12/spyderlib/plugins/inspector.py", line 34, in \<module>
    from spyderlib.utils.sphinxify import CSS_PATH, sphinxify
  File "/home/tobal/Descargas/spyder-2.0.12/spyderlib/utils/sphinxify.py", line 30, in \<module>
    from sage.misc.misc import SAGE_DOC
  File "/usr/lib/python2.7/site-packages/sage/misc/misc.py", line 42, in \<module>
    SAGE_ROOT = os.environ["SAGE_ROOT"]
  File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'SAGE_ROOT' What version of the product are you using? On what operating system? Version 2.0.12 from Mandriva 2011.0 with an official rpm package. And I'm using SageMath from Mandriva 2011.0, too 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=739_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-08-28T12:45:34Z_

Apparently there's something wrong with your Sage installation.

Carlos, can you handle this one?

**Summary:** spyder crash with Mandriva 2011.0 / Sage  
  **Status:** Accepted  
  **Owner:** ccordoba12  
  **Labels:** Cat-ObjectInspector

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-08-28T13:58:32Z_

Sure, I'll take a look at it as soon as I can. But from the traceback the problem seems that we left around some Sage variables in our sphinxify version that are clashing with a proper and system wide installation of Sage.

I thought only Gentoo provided this kind of installation. Kudos to Mandriva! Sage is quite a beast to handle as a package.

Carlos

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-08-28T19:23:13Z_

Could you please replace the file /home/tobal/Descargas/spyder-2.0.12/spyderlib/utils/sphinxify.py with the version I'm attaching here?

My initial thought was right. We left some Sage variables behind which I tried to remove in this version (at least all the harmful ones).

If you confirm me that Spyder works ok after these changes, I'll push them to version 2.1.

**Summary:** Spyder crash with Mandriva 2011.0 and a system wide installation of Sage  
  **Labels:** Milestone-Release2.1  


**Attachment:** [sphinxify.py](http://code.google.com/p/spyderlib/issues/detail?id=739#hc3)

**Comment by spyder-issues-migrator** [comment]
_From [lopezto...@gmail.com](https://code.google.com/u/116115558710812750203/) on 2011-08-28T22:35:56Z_

yeah, now it works good.
Please, tell me when you add this file in 2.1 version, and if it is stable.

Thank you very much for your fast solution.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-09-06T15:26:53Z_

This issue was closed by revision 36917926d100 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-09-06T15:28:22Z_

It was added just now. Version 2.1 has entered beta and it will be stable at the end of the month.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-09-06T15:29:51Z_

**Summary:** Spyder crash with a system wide installation of Sage

**Comment by spyder-issues-migrator** [comment]
_From [lopezto...@gmail.com](https://code.google.com/u/116115558710812750203/) on 2011-09-15T07:40:13Z_

ok, thanks. I've packaged this beta version for Mandriva to Mandriva MIB project because of i've tested it and it works very good to me, even iPython works okay in this release. MIB project is here http://mib.pianetalinux.org/mib/ When the program is stable version i'll propose it this version at official Mandriva repositories.
I'm very glad with this program, it is very useful to me, i'm a mathematician and I like so much its instant help.
Thank you very much.
