### ISSUE TITLE
Why does the 'tensorflow' module import fail in Spyder and not in Python prompt?

### ISSUE THREAD

**Issue by HJH12315** [spyder-ide/spyder#7396]
## Problem Description
I install Spyder in UBuntu app store. And I don't install Anaconda. Tensorflow can work in terminal,but not works in Spyder IPython consle.
### Paste Traceback/Error Below (if applicable)
Traceback (most recent call last):

  File "<ipython-input-1-2e68733dc9a0>", line 1, in <module>
    runfile('/home/junhao/.config/spyder-py3/temp.py', wdir='/home/junhao/.config/spyder-py3')

  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/junhao/.config/spyder-py3/temp.py", line 8, in <module>
    import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

## Versions

* Spyder version: 3.2.6
* Python version: 3.6
* Operating System name/version: Ubuntu18.04

**Comment by danieltomasz** [comment]
What are you getting when typing
```
which python3
```
Is the same path you have in spyder > preferences >python interpreter >use the folowing python interpreter?

Are you sure you installed tensorflow by  pip3 not by  pip (for python2)?

**Comment by HJH12315** [comment]
@danieltomasz  When I  installed tensorflow by pip3 and set python interpreter as /usr/bin/python3.6, the error in IPython console as follow:

In [1]: import tensorflow as tf
Traceback (most recent call last):

  File "<ipython-input-4-64156d691fe5>", line 1, in <module>
    import tensorflow as tf

  File "/home/junhao/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File "/home/junhao/.local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "/home/junhao/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "/home/junhao/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/junhao/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/junhao/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.


But in the Ubuntu terminal ,it can work with tensorflow.

**Comment by HJH12315** [comment]
@danieltomasz 
I run as follow in terminal and success:
sudo echo "/usr/local/cuda-9.0/lib64" >> /etc/ld.so.conf.d/cuda.conf
sudo ldconfig
