### ISSUE TITLE
hey guys ! 

### ISSUE THREAD

**Issue by STAIBI** [spyder-ide/spyder#7427]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Utilisateur\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2862, in _dep_map
    try:
  File "C:\Users\Utilisateur\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2669, in __getattr__
    def __dir__(self):
AttributeError: _DistInfoDistribution__dep_map

Traceback (most recent call last):
  File "C:\Users\Utilisateur\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2853, in _parsed_pkg_info
    Wrap an actual or potential sys.path entry
  File "C:\Users\Utilisateur\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2669, in __getattr__
    def __dir__(self):
AttributeError: _pkg_info

Traceback (most recent call last):
  File "C:\Users\Utilisateur\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 234, in show_object_info
    info = self._get_code_info('info', position, auto=auto)
  File "C:\Users\Utilisateur\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 216, in _get_code_info
    **kwargs)
  File "C:\Users\Utilisateur\Anaconda3\lib\site-packages\spyder\utils\introspection\utils.py", line 75, in __init__
    self._get_info()
  File "C:\Users\Utilisateur\Anaconda3\lib\site-packages\spyder\utils\introspection\utils.py", line 87, in _get_info
    lexer = find_lexer_for_filename(self.filename)
  File "C:\Users\Utilisateur\Anaconda3\lib\site-packages\spyder\utils\introspection\utils.py", line 180, in find_lexer_for_filename
    lexer = get_lexer_for_filename(filename)
  File "C:\Users\Utilisateur\Anaconda3\lib\site-packages\pygments\lexers\__init__.py", line 203, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "C:\Users\Utilisateur\Anaconda3\lib\site-packages\pygments\lexers\__init__.py", line 168, in find_lexer_class_for_filename
    for cls in find_plugin_lexers():
  File "C:\Users\Utilisateur\Anaconda3\lib\site-packages\pygments\plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "C:\Users\Utilisateur\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2323, in load
    def resolve(self):
  File "C:\Users\Utilisateur\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2346, in require
    pattern = re.compile(
  File "C:\Users\Utilisateur\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 786, in resolve
    requirements.extend(new_requirements)
  File "C:\Users\Utilisateur\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2613, in requires
    for ext in extras:
  File "C:\Users\Utilisateur\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2864, in _dep_map
    except AttributeError:
  File "C:\Users\Utilisateur\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2873, in _compute_dependencies
    except AttributeError:
  File "C:\Users\Utilisateur\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2855, in _parsed_pkg_info
    """
  File "C:\Users\Utilisateur\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1404, in get_metadata
    return value.decode('utf-8') if six.PY3 else value
  File "C:\Users\Utilisateur\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1516, in _get
    return stream.read()
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\utilisateur\\anaconda3\\lib\\site-packages\\setuptools-39.0.1.dist-info\\METADATA'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.14.2 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
This is already fixed in Spyder 3.3, released last week. New conda packages for it should be available in this week.
