### ISSUE TITLE
error dialogue on opening file

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [spyder-ide/spyder#7431]
## Description

**What steps will reproduce the problem?**

1.  press the open button to choose a file
2. 
3. 

**What is the expected output? What do you see instead?**
error dialog

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 150, in lock
    symlink(str(os.getpid()), self.name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 88, in symlink
    rename(newlinkname, filename)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Dell\\.spyder-py3\\spyder.lock.1531376947967.newlink' -> 'C:\\Users\\Dell\\.spyder-py3\\spyder.lock'

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\start.py", line 114, in main
    lock_created = lock.lock()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 159, in lock
    pid = readlink(self.name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\external\lockfile.py", line 96, in readlink
    fObj = _open(os.path.join(filename, 'symlink'), 'rb')
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Dell\\.spyder-py3\\spyder.lock\\symlink'

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 1840, in load
    self.edit_fi

**Comment by ccordoba12** [comment]
> PermissionError: [Errno 13] Permission denied: 'C:\Users\Dell\.spyder-py3\spyder.lock\symlink'

The error is clear: you need to make `C:\Users\Dell\.spyder-py3` and all directories inside writable for your own user.
