### ISSUE TITLE
NameError: name '_' is not defined

### ISSUE THREAD

**Issue by TFDeeplearner** [spyder-ide/spyder#7489]
After "spyder --reset", "NameError: name '_' is not defined" show up, spyder cann't start up
spyder version 3.3.0
conda version 4.5.8

------

The problem content:

```python
Traceback (most recent call last):
  File "/home/yang/anaconda3/bin/spyder", line 7, in <module>
    from spyder.app.start import main
  File "/home/yang/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 37, in <module>
    from spyder.config.base import (get_conf_path, running_in_mac_app,
  File "/home/yang/anaconda3/lib/python3.6/site-packages/spyder/config/base.py", line 415, in <module>
    _ = get_translation("spyder")
  File "/home/yang/anaconda3/lib/python3.6/site-packages/spyder/config/base.py", line 386, in get_translation
    language = load_lang_conf()
  File "/home/yang/anaconda3/lib/python3.6/site-packages/spyder/config/base.py", line 359, in load_lang_conf
    lang = get_interface_language()
  File "/home/yang/anaconda3/lib/python3.6/site-packages/spyder/config/base.py", line 330, in get_interface_language
    spyder_languages = get_available_translations()
  File "/home/yang/anaconda3/lib/python3.6/site-packages/spyder/config/base.py", line 297, in get_available_translations
    error = _('Update LANGUAGE_CODES (inside config/base.py) if a new '
NameError: name '_' is not defined
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll fix this problem in our next version.
