### ISSUE TITLE
Outline Explorer: Duplicate entries

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#749]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2011-09-02T12:23:37Z_

What steps will reproduce the problem?

 1. Unsure how to reproduce What is the expected output? What do you see instead? Every once in a while I see duplicate entries in the Outline Explorer.  it's usually after I've been running Spyder for several days.  When it does occur, all global level functions/comments are duplicated 1 or more times. What version of the product are you using? On what operating system? spyder 2.0.12, python 2.6.1, Windows XP SP3

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=749_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-09-02T10:36:39Z_

Steve, as a regular user of Spyder, you may try to use the development version which is very close from the first public beta release.

I personnally am using the development version every day for all my projects (even to develop Spyder itself), quite intensively. And it's quite stable. From time to time, there may be critical bugs as this is an unstable version but there are always very quickly fixed as this is my main development tool (I need it to be stable).

So the next step would be to try the dev version and report back if the problems you describe happen again.

If you are reluctant to use Mercurial and synchronize regularly with the main repository, you may also wait a few days until the v2.1.0beta1 release.

**Comment by spyder-issues-migrator** [comment]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2011-09-02T11:11:53Z_

Am I using the correct repository?  spyderlib.googlecode.com/hg/spyderlib/v21

Has anything changed about installation/execution?  I ran setup.py install and am immediately presented with this import error:



C:\Python26\Scripts>spyder.bat
Traceback (most recent call last):
  File "C:\Python26\Scripts\spyder", line 2, in \<module>
    from spyderlib import spyder
  File "C:\Python26\Lib\site-packages\spyderlib\spyder.py", line 54, in \<module>

    from spyderlib.plugins.console import Console
  File "C:\Python26\Lib\site-packages\spyderlib\plugins\console.py", line 31, in
 \<module>
    from spyderlib.utils.environ import EnvDialog
  File "C:\Python26\Lib\site-packages\spyderlib\utils\environ.py", line 17, in \<
module>
    from spyderlib.widgets.dicteditor import DictEditor
  File "C:\Python26\Lib\site-packages\spyderlib\widgets\dicteditor.py", line 33,
 in \<module>
    from spyderlib.widgets.dicteditorutils import (sort_against, get_size, get_t
ype,
ImportError: cannot import name array

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-09-02T14:12:08Z_

That's not the correct repository -- it's outdated (I forgot to disable it, now it's done).

You must use the default repository: https://code.google.com/p/spyderlib/source/checkout

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2011-09-22T08:05:12Z_

**Labels:** Cat-OutlineExplorer

**Comment by spyder-issues-migrator** [comment]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2011-11-30T13:41:46Z_

This is still an issue in 2.1.4.

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2011-12-01T00:30:46Z_

Did you figure out how to reproduce this?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-01T05:06:48Z_

I've just fixed this. I'll push changes ASAP.

**Status:** Started  
  **Owner:** pierre.raybaut

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-02T07:17:28Z_

This issue was updated by revision 43b2bbe49cbc .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2012-01-23T11:25:34Z_

This appears to still be an issue in 2.1.7.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-01-23T12:38:03Z_

Then we need a procedure describing how to reproduce this bug.

**Comment by spyder-issues-migrator** [comment]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2012-01-23T13:55:43Z_

Hmm.. not sure what it means, but the first of each duplicate item does not have the child items nested beneath it.  The duplicate items always select the line two below the real line.  If I modify and save the file the outline explorer corrects itself until some time in the future at which point it will be messed up.  I don't know how to forcibly reproduce this bug, it's just a matter of time.

**Comment by spyder-issues-migrator** [comment]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2012-01-27T14:22:42Z_

There was a previous issue where special comments were causing items in the outline to nest incorrectly, so it made me think of this.

I've noticed that ONLY files with "misaligned incomplete" special comments are showing the duplicate outline explorer entries.  (#------)  I have support for the special comments enabled because they don't normally show up since they require some text at the end.  I have created a very small test file to see if I can use it to replicate the issue.  If I can replicate with this file I can submit it.

**Comment by spyder-issues-migrator** [comment]
_From [stefan.r...@gmail.com](https://code.google.com/u/111201285089679297844/) on 2013-03-13T23:00:08Z_

I think I can now provide a reproducible method to make the Outline misbehave:

1. create the following file and save:
class testclass:
    def testmethod(self):
        
class anothertestclass:
    def anothermethod:

2. have the outline explorer visible on your screen (or do this before 1.)
3. change the file on disk (but not in the editor)
- this might happen as you switch branches while your file are open in spyder
- I just fired up my trusty spyder alternative (vi) and changed the above file to 
class testclass:
    def testmethod(self):
        print
        print

class anothertestclass:
    def anothermethod:
        print
        print

4. Now you have to somehow coax spyder into recognizing the changed state of the file on disk. (Sometimes revert works or sometimes spyder picks up a changed file without prodding)

5. walla (sorry, Pierre, just kidding)
my outline explorer now shows the entry for anothertestclass twice

**Attachment:** [untitled1.py](http://code.google.com/p/spyderlib/issues/detail?id=749#hc14)

**Comment by spyder-issues-migrator** [comment]
_From [stefan.r...@gmail.com](https://code.google.com/u/111201285089679297844/) on 2013-03-13T23:01:21Z_

sorry meant to say this is on the recent 2.2 beta4 release

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-03-14T00:50:09Z_

**Status:** Accepted  
  **Labels:** -Priority-Medium Priority-High MS-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-04-29T15:08:36Z_

**Labels:** MS-v2.2.1

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-04-29T15:10:06Z_

**Labels:** -MS-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-06-04T05:46:32Z_

I am also running into this.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-06-10T18:47:58Z_

**Labels:** -MS-v2.2.1 MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [david.ve...@gmail.com](https://code.google.com/u/108342766018366950755/) on 2013-07-10T15:27:08Z_

Or what about this, using stefan's approach, but now:
3. Duplicates arise for all classes/methods after the point where lines were added. Adding and removing lines at various places in the other editor can now create an interesting outline in Spyder. Not adding/removing any lines keeps the outline intact.

I tried poking around a bit, and found that this can be fixed as follows:
diff -r d6e84fc69ab6 spyderlib/widgets/editor.py
--- a/spyderlib/widgets/editor.py	Sun Jul 07 13:59:10 2013 -0500
+++ b/spyderlib/widgets/editor.py	Thu Jul 11 00:20:16 2013 +0200
@@ -1742,7 +1742,15 @@
         finfo.editor.document().setModified(False)
         finfo.editor.set_cursor_position(position)
         codeeditor.validate_rope_project()
-        self._refresh_outlineexplorer(index, update=True, clear=True)
+        
+        #XXX CodeEditor-only: re-scan the whole text to rebuild outline 
+        # explorer data from scratch (could be optimized because 
+        # rehighlighting text means searching for all syntax coloring 
+        # patterns instead of only searching for class/def patterns which 
+        # would be sufficient for outline explorer data.
+        finfo.editor.rehighlight()
+        index = self.get_stack_index()
+        self._refresh_outlineexplorer(index)
         
     def revert(self):
         """Revert file from disk"""

This is exactly the same as when a file is saved in the editor, because I noticed that saving the file in spyder restores the outline again. It still does not fix the suggested optimization as mentioned in EditorStack.save().

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-08-15T04:52:50Z_

This issue was updated by revision c40d00c19c71 .


Implemented the approach suggested by David Verelst. The performance issue seems
perfectly acceptable (at least as acceptable as in the context of saving files).

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-15T07:51:52Z_

**Labels:** -MS-v2.3 MS-v2.2.3

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-08-15T08:57:21Z_

Verified on Windows 7, 32-bit Python 2.7.5.

**Status:** Verified
