### ISSUE TITLE
tensorflow警告信息

### ISSUE THREAD

**Issue by bingnan125** [spyder-ide/spyder#7507]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2872, in _dep_map
    reqs.extend(parse_requirements(req))
  File "D:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2666, in __getattr__
    if attr.startswith('_'):
AttributeError: _DistInfoDistribution__dep_map

Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2863, in _parsed_pkg_info
    return self.__dep_map
  File "D:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2666, in __getattr__
    if attr.startswith('_'):
AttributeError: _pkg_info

Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 220, in get_completions
    info = self._get_code_info('completions', automatic=automatic)
  File "D:\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 216, in _get_code_info
    **kwargs)
  File "D:\Anaconda3\lib\site-packages\spyder\utils\introspection\utils.py", line 75, in __init__
    self._get_info()
  File "D:\Anaconda3\lib\site-packages\spyder\utils\introspection\utils.py", line 87, in _get_info
    lexer = find_lexer_for_filename(self.filename)
  File "D:\Anaconda3\lib\site-packages\spyder\utils\introspection\utils.py", line 180, in find_lexer_for_filename
    lexer = get_lexer_for_filename(filename)
  File "D:\Anaconda3\lib\site-packages\pygments\lexers\__init__.py", line 203, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "D:\Anaconda3\lib\site-packages\pygments\lexers\__init__.py", line 168, in find_lexer_class_for_filename
    for cls in find_plugin_lexers():
  File "D:\Anaconda3\lib\site-packages\pygments\plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "D:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2320, in load
    if require:
  File "D:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2343, in require
    reqs = self.dist.requires(self.extras)
  File "D:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 785, in resolve
    # push the new requirements onto the stack
  File "D:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2610, in requires
    """List of Requirements needed for this distro if `extras` are used"""
  File "D:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2874, in _dep_map
    def reqs_for_extra(extra):
  File "D:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2883, in _compute_dependencies
    s_extra = safe_extra(extra.strip())
  File "D:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2865, in _parsed_pkg_info
    def _compute_dependencies(self):
  File "D:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1403, in get_metadata
    return ""
  File "D:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1515, in _get
    def _get(self, path):
FileNotFoundError: [Errno 2] No such file or directory: 'd:\\anaconda3\\lib\\site-packages\\setuptools-40.0.0.dist-info\\METADATA'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.9.4, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.3 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.0). Please update by opening the Anaconda Prompt and running there

    conda update spyder

If an update to that version is not available, please be patient, it should be shortly.
