### ISSUE TITLE
Failed to run debug in windows x64

### ISSUE THREAD

**Issue by machsix** [spyder-ide/spyder#7514]
## Problem Description
Failed to run debug

### What steps reproduce the problem?

1.  A simple python script with a breakpoint on second line
```python
if __name__ == '__main__':
    a=2
    print(a
```
2. Run debug

### What is the expected output? What do you see instead?
Program should pause at the breakpoint but I saw the following error in ipython console
``` python
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 6.4.0 -- An enhanced Interactive Python.

Restarting kernel... 


 

debugfile('E:/Git/personal-scripts/Scrapy/test.py', wdir='E:/Git/personal-scripts/Scrapy')
Traceback (most recent call last):

  File "<ipython-input-1-ea393d5eed0a>", line 1, in <module>
    debugfile('E:/Git/personal-scripts/Scrapy/test.py', wdir='E:/Git/personal-scripts/Scrapy')

  File "C:\Users\Han\Miniconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 728, in debugfile
    debugger.run("runfile(%r, args=%r, wdir=%r)" % (filename, args, wdir))

  File "C:\Users\Han\Miniconda3\lib\bdb.py", line 434, in run
    exec(cmd, globals, locals)

  File "<string>", line 1, in <module>

  File "C:\Users\Han\Miniconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\Han\Miniconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    with open(filename, 'rb') as f:

FileNotFoundError: [Errno 2] No such file or directory: 'e:/git/personal-scripts/scrapy/test.py'
```

### Paste Traceback/Error Below (if applicable)

Internal console is empty

## Versions

Spyder was installed with the latest miniconda. I did a fresh reinstall with "conda install spyder numpy scipy matplotlib jupyter cython pandas sympy". I also tried to reset spyder but it didn't work.

* Spyder version: 3.2.8 (There is no latest 3.3.0 in the default channel yet)
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version:  windows 10 build 17134 x64

### Dependencies

```
IPython >=4.0    :  6.4.0 (OK)
cython >=0.21    :  0.28.3 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.5 (OK)
pandas >=0.13.1  :  0.23.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.9.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.5 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

```

**Comment by machsix** [comment]
It works if I place it at `C:\` or any subdirectory like `C:\Users\Foobar\`. Mysteriously, if I placed it in `E:\Git`, it also works. But neither `E:/Git/personal-scripts/Scrapy/` nor `E:/Git/personalscripts/Scrapy/` works.

**Comment by ccordoba12** [comment]
We'll take a look at this in our next release.

**Comment by getvenkat** [comment]
I have the same issue. The file path is turned into lowercase when the FileNotFoundError reported.  Wondering if they are related.

Only happens in Windows (Windows 10, x64) with windows versions of Spyder.

If I run the WSL version (WSL-1, Ubuntu on Windows) it works fine.

**Comment by matthiasLevy** [comment]
I everyone,
Has anyone found a solution to this issue ? Still present in v4.0.0.b4, thought I'm running Spyder in a virtualenv.
Thanks in advance...
M.

**Comment by ccordoba12** [comment]
> canonic = os.path.normcase(canonic)

This is very interesting!! Thanks for letting us know about it!

Question: What's the path of the file you're trying to run?

**Comment by ccordoba12** [comment]
Sorry, the file you're trying to *debug*.

**Comment by matthiasLevy** [comment]
Nothing really special... Not even a whitespace
'C:\Users\Myname\Documents\GitHub\EMS_framework_WIN\EMS\Tools\TypeFunc.py'

**Comment by ccordoba12** [comment]
Ok, thanks anyway. Your feedback is very valuable because we were totally lost about this bug.

**Comment by Dollarius** [comment]
This bug seems to have reappeared on Windows.
The filename of the running script is turned in lowercase.

The simple code
```
import time
print(__file__)
time.sleep(5)
```
if run as standalone .py file returns
C:\Data\2022\06 Jun\22 Wed\FileNameTest.py

but if run in Spyder console returns the lowercase string:
**c**:\\**d**ata\2022\06 **j**un\22 **w**ed\\**f**ile**n**ame**t**est.py

Is this a bug or a choice?

Python 3.8.0 64-bit | Qt 5.12.10 | PyQt5 5.12.3 | Windows 10

**Comment by ccordoba12** [comment]
@Dollarius, Windows filesystem is case insensitive, i.e. it doesn't matter if files use capital letters or not. So, I'd like to ask you: are you experiencing problems due to that? If not, you can simply ignore it.

**Comment by Dollarius** [comment]
@ccordoba12 thanks for your reply. I know that Windows is case insensitive, but I need to output thousands of files based on the filename of the running script. I will need those files to be used on other systems (Mac/Unix), so it would be nice if the case could be preserved.
Is there any other/new way to get the case-preserved .py script filename in Spyder?
It was possible to do so up to some Spyder versions ago (certainly <5.0)
Thanks for your help.
