### ISSUE TITLE
spyder 2.1.0beta1 won't start after install

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#753]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2011-09-07T11:27:15Z_

I just installed spyder 2.1.0beta1.  I clicked the spyder icon and it did not start.  I had to drop to a console and run spyder form there to see the exception.  It would be nice if there was a way to notify the user of these kinds of exceptions without forcing them to go to the command line to figure it out.  It turns out PIL is now required?  I also didn't see this new required module documented anywhere, but I may have just missed it. What version of the product are you using? On what operating system? spyder 2.1.0beta1, python 2.6.1, Windows XP SP3 

Please provide any additional information below

. Traceback (most recent call last):
  File "c:\Python26\Scripts\spyder", line 2, in \<module>
    from spyderlib import spyder
  File "c:\python26\lib\site-packages\spyderlib\spyder.py", line 94, in \<module>

    from spyderlib.plugins.console import Console
  File "c:\python26\lib\site-packages\spyderlib\plugins\console.py", line 32, in
 \<module>
    from spyderlib.utils.environ import EnvDialog
  File "c:\python26\lib\site-packages\spyderlib\utils\environ.py", line 17, in \<
module>
    from spyderlib.widgets.dicteditor import DictEditor
  File "c:\python26\lib\site-packages\spyderlib\widgets\dicteditor.py", line 34,
 in \<module>
    from spyderlib.widgets.dicteditorutils import (sort_against, get_size, get_t
ype,
ImportError: cannot import name PIL

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=753_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-10-08T10:35:48Z_

**Status:** Duplicate  
  **Mergedinto:** 788
