### ISSUE TITLE
TypeError: scaledToWidth in the IPython console

### ISSUE THREAD

**Issue by llsouza** [spyder-ide/spyder#7552]
### What steps will reproduce the problem?

Example from http://nbviewer.jupyter.org/github/donnemartin/data-science-ipython-notebooks/blob/master/scikit-learn/scikit-learn-intro.ipynb

Error when executing
Image("http://scikit-learn.org/dev/_static/ml_map.png", width=800)

System: Windows 10 / Anaconda3 (64 bit) / iPython / Python 3.6

### Traceback
```python-traceback
  File "D:\ProgramData\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "D:\ProgramData\Anaconda3\lib\site-packages\qtconsole\rich_jupyter_widget.py", line 135, in _handle_execute_result
    self._append_png(png, True, metadata=metadata.get('image/png', None))
  File "D:\ProgramData\Anaconda3\lib\site-packages\qtconsole\rich_jupyter_widget.py", line 234, in _append_png
    self._append_custom(self._insert_png, png, before_prompt, metadata=metadata)
  File "D:\ProgramData\Anaconda3\lib\site-packages\qtconsole\console_widget.py", line 894, in _append_custom
    result = insert(cursor, input, *args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\qtconsole\rich_jupyter_widget.py", line 347, in _insert_png
    self._insert_img(cursor, png, 'png', metadata=metadata)
  File "D:\ProgramData\Anaconda3\lib\site-packages\qtconsole\rich_jupyter_widget.py", line 362, in _insert_img
    image = image.scaledToWidth(width, transformMode=QtCore.Qt.SmoothTransformation)
TypeError: scaledToWidth(self, int, mode: Qt.TransformationMode = Qt.FastTransformation): 'transformMode' is not a valid keyword argument
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
numpy >=1.7      :  1.14.3 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.4.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
```

**Comment by bcolsen** [comment]
This might be qtconsole bug.

When I type this in qtconsole:

```python
from IPython.display import Image
Image("http://scikit-learn.org/dev/_static/ml_map.png", width=800)
```
I get the same trace back:
```
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/home/user/anaconda3/lib/python3.6/site-packages/qtconsole/rich_jupyter_widget.py", line 135, in _handle_execute_result
    self._append_png(png, True, metadata=metadata.get('image/png', None))
  File "/home/user/anaconda3/lib/python3.6/site-packages/qtconsole/rich_jupyter_widget.py", line 234, in _append_png
    self._append_custom(self._insert_png, png, before_prompt, metadata=metadata)
  File "/home/user/anaconda3/lib/python3.6/site-packages/qtconsole/console_widget.py", line 894, in _append_custom
    result = insert(cursor, input, *args, **kwargs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/qtconsole/rich_jupyter_widget.py", line 347, in _insert_png
    self._insert_img(cursor, png, 'png', metadata=metadata)
  File "/home/user/anaconda3/lib/python3.6/site-packages/qtconsole/rich_jupyter_widget.py", line 362, in _insert_img
    image = image.scaledToWidth(width, transformMode=QtCore.Qt.SmoothTransformation)
TypeError: scaledToWidth(self, int, mode: Qt.TransformationMode = Qt.FastTransformation): 'transformMode' is not a valid keyword argument
Aborted (core dumped)
```

**Comment by ccordoba12** [comment]
Right, thanks @bcolsen. I'm working on it right now.
