### ISSUE TITLE
Cannot open Spyder after updates 

### ISSUE THREAD

**Issue by darlastill** [spyder-ide/spyder#7587]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [x ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x ] Tried the other applicable steps from the Troubleshooting Guide
* [x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Trying to open Spyder after some time and had to update pip and Anaconda in the process. I am still encountering issues that I am struggling to figure out. I have been reading and circling back to the boards with similar issues. The final step was uninstalling/reinstalling Anaconda, and I still cannot open Spyder. I've pasted as much trace-back as I can, including where I tried updating Spyder, and tried to conda install pyside and uninstall it, but I'm still getting an error. Help.

### What steps reproduce the problem?

1. spyder.exe
2. pip install PySide
3. pip install msgpack
4. pip install PySide
5. conda install pyside

### Paste Traceback/Error Below (if applicable)

```python-traceback

C:\Users\dmsti>spyder.exe
Traceback (most recent call last):
  File "C:\Users\dmsti\Anaconda3\lib\site-packages\qtpy\__init__.py", line 166, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dmsti\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\dmsti\Anaconda3\lib\site-packages\spyder\app\start.py", line 159, in main
    from spyder.app import mainwindow
  File "C:\Users\dmsti\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "C:\Users\dmsti\Anaconda3\lib\site-packages\spyder\requirements.py", line 39, in check_qt
    import qtpy
  File "C:\Users\dmsti\Anaconda3\lib\site-packages\qtpy\__init__.py", line 172, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

C:\Users\dmsti>pip install PySide
Collecting PySide
  Using cached https://files.pythonhosted.org/packages/36/ac/ca31db6f2225844d37a41b10615c3d371587677efd074db29855e7035de6/PySide-1.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\dmsti\AppData\Local\Temp\pip-install-hlkjk0cb\PySide\
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\dmsti>python -m pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/5f/25/e52d3f31441505a5f3af41213346e5b6c221c9e086a166f3703d2ddaf940/pip-18.0-py2.py3-none-any.whl
distributed 1.21.8 requires msgpack, which is not installed.
Installing collected packages: pip
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-18.0

C:\Users\dmsti>pip install PySide
Collecting PySide
  Using cached https://files.pythonhosted.org/packages/36/ac/ca31db6f2225844d37a41b10615c3d371587677efd074db29855e7035de6/PySide-1.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\dmsti\AppData\Local\Temp\pip-install-it2i79pw\PySide\

C:\Users\dmsti>pip install --upgrade spyder
Collecting spyder
  Using cached https://files.pythonhosted.org/packages/45/1e/5e7a1932b5a569ec3072cd1fabc663a081345a2e2e0d16bc09e5213dea1b/spyder-3.3.0-py3-none-any.whl
Requirement already satisfied, skipping upgrade: qtpy>=1.2.0 in c:\users\dmsti\anaconda3\lib\site-packages (from spyder) (1.4.1)
Requirement already satisfied, skipping upgrade: pygments>=2.0 in c:\users\dmsti\anaconda3\lib\site-packages (from spyder) (2.2.0)
Collecting spyder-kernels<1.0 (from spyder)
  Using cached https://files.pythonhosted.org/packages/1d/6c/2d151d2711baed6fd40383d7f24307eb190b38293d80b3ef7e585f72c58e/spyder_kernels-0.2.4-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: cloudpickle in c:\users\dmsti\anaconda3\lib\site-packages (from spyder) (0.5.3)
Requirement already satisfied, skipping upgrade: sphinx in c:\users\dmsti\anaconda3\lib\site-packages (from spyder) (1.7.4)
Requirement already satisfied, skipping upgrade: pylint in c:\users\dmsti\anaconda3\lib\site-packages (from spyder) (1.8.4)
Requirement already satisfied, skipping upgrade: pickleshare in c:\users\dmsti\anaconda3\lib\site-packages (from spyder) (0.7.4)
Requirement already satisfied, skipping upgrade: qtconsole>=4.2.0 in c:\users\dmsti\anaconda3\lib\site-packages (from spyder) (4.3.1)
Requirement already satisfied, skipping upgrade: pyflakes in c:\users\dmsti\anaconda3\lib\site-packages (from spyder) (1.6.0)
Requirement already satisfied, skipping upgrade: nbconvert in c:\users\dmsti\anaconda3\lib\site-packages (from spyder) (5.3.1)
Requirement already satisfied, skipping upgrade: chardet>=2.0.0 in c:\users\dmsti\anaconda3\lib\site-packages (from spyder) (3.0.4)
Requirement already satisfied, skipping upgrade: pycodestyle in c:\users\dmsti\anaconda3\lib\site-packages (from spyder) (2.4.0)
Collecting pyqt5<5.10; python_version >= "3" (from spyder)
  Using cached https://files.pythonhosted.org/packages/67/ad/5ce6033bded3c39043a2c67cc46b3976427187f68c9dbaf5533884899086/PyQt5-5.9.2-5.9.3-cp35.cp36.cp37-none-win_amd64.whl
Requirement already satisfied, skipping upgrade: qtawesome>=0.4.1 in c:\users\dmsti\anaconda3\lib\site-packages (from spyder) (0.4.4)
Requirement already satisfied, skipping upgrade: numpydoc in c:\users\dmsti\anaconda3\lib\site-packages (from spyder) (0.8.0)
Collecting keyring (from spyder)
  Using cached https://files.pythonhosted.org/packages/88/a8/341fa4686e98bf10289eb4eaea89e8176b93c1e38de52e3c42d9112baae1/keyring-13.2.1-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: pyzmq in c:\users\dmsti\anaconda3\lib\site-packages (from spyder) (17.0.0)
Requirement already satisfied, skipping upgrade: rope>=0.10.5 in c:\users\dmsti\anaconda3\lib\site-packages (from spyder) (0.10.7)
Requirement already satisfied, skipping upgrade: jedi>=0.9.0 in c:\users\dmsti\anaconda3\lib\site-packages (from spyder) (0.12.0)
Requirement already satisfied, skipping upgrade: psutil in c:\users\dmsti\anaconda3\lib\site-packages (from spyder) (5.4.5)
Requirement already satisfied, skipping upgrade: ipykernel in c:\users\dmsti\anaconda3\lib\site-packages (from spyder-kernels<1.0->spyder) (4.8.2)
Requirement already satisfied, skipping upgrade: six>=1.5 in c:\users\dmsti\anaconda3\lib\site-packages (from sphinx->spyder) (1.11.0)
Requirement already satisfied, skipping upgrade: Jinja2>=2.3 in c:\users\dmsti\anaconda3\lib\site-packages (from sphinx->spyder) (2.10)
Requirement already satisfied, skipping upgrade: docutils>=0.11 in c:\users\dmsti\anaconda3\lib\site-packages (from sphinx->spyder) (0.14)
Requirement already satisfied, skipping upgrade: snowballstemmer>=1.1 in c:\users\dmsti\anaconda3\lib\site-packages (from sphinx->spyder) (1.2.1)
Requirement already satisfied, skipping upgrade: babel!=2.0,>=1.3 in c:\users\dmsti\anaconda3\lib\site-packages (from sphinx->spyder) (2.5.3)
Requirement already satisfied, skipping upgrade: alabaster<0.8,>=0.7 in c:\users\dmsti\anaconda3\lib\site-packages (from sphinx->spyder) (0.7.10)
Requirement already satisfied, skipping upgrade: imagesize in c:\users\dmsti\anaconda3\lib\site-packages (from sphinx->spyder) (1.0.0)
Requirement already satisfied, skipping upgrade: requests>=2.0.0 in c:\users\dmsti\anaconda3\lib\site-packages (from sphinx->spyder) (2.18.4)
Requirement already satisfied, skipping upgrade: setuptools in c:\users\dmsti\anaconda3\lib\site-packages (from sphinx->spyder) (39.1.0)
Requirement already satisfied, skipping upgrade: packaging in c:\users\dmsti\anaconda3\lib\site-packages (from sphinx->spyder) (17.1)
Requirement already satisfied, skipping upgrade: sphinxcontrib-websupport in c:\users\dmsti\anaconda3\lib\site-packages (from sphinx->spyder) (1.0.1)
Requirement already satisfied, skipping upgrade: colorama>=0.3.5 in c:\users\dmsti\anaconda3\lib\site-packages (from sphinx->spyder) (0.3.9)
Requirement already satisfied, skipping upgrade: astroid<2.0,>=1.6 in c:\users\dmsti\anaconda3\lib\site-packages (from pylint->spyder) (1.6.3)
Requirement already satisfied, skipping upgrade: isort>=4.2.5 in c:\users\dmsti\anaconda3\lib\site-packages (from pylint->spyder) (4.3.4)
Requirement already satisfied, skipping upgrade: mccabe in c:\users\dmsti\anaconda3\lib\site-packages (from pylint->spyder) (0.6.1)
Requirement already satisfied, skipping upgrade: mistune>=0.7.4 in c:\users\dmsti\anaconda3\lib\site-packages (from nbconvert->spyder) (0.8.3)
Requirement already satisfied, skipping upgrade: traitlets>=4.2 in c:\users\dmsti\anaconda3\lib\site-packages (from nbconvert->spyder) (4.3.2)
Requirement already satisfied, skipping upgrade: jupyter_core in c:\users\dmsti\anaconda3\lib\site-packages (from nbconvert->spyder) (4.4.0)
Requirement already satisfied, skipping upgrade: nbformat>=4.4 in c:\users\dmsti\anaconda3\lib\site-packages (from nbconvert->spyder) (4.4.0)
Requirement already satisfied, skipping upgrade: entrypoints>=0.2.2 in c:\users\dmsti\anaconda3\lib\site-packages (from nbconvert->spyder) (0.2.3)
Requirement already satisfied, skipping upgrade: bleach in c:\users\dmsti\anaconda3\lib\site-packages (from nbconvert->spyder) (2.1.3)
Requirement already satisfied, skipping upgrade: pandocfilters>=1.4.1 in c:\users\dmsti\anaconda3\lib\site-packages (from nbconvert->spyder) (1.4.2)
Requirement already satisfied, skipping upgrade: testpath in c:\users\dmsti\anaconda3\lib\site-packages (from nbconvert->spyder) (0.3.1)
Collecting sip<4.20,>=4.19.4 (from pyqt5<5.10; python_version >= "3"->spyder)
  Downloading https://files.pythonhosted.org/packages/30/fa/90ea79d7b6b21a50e16d2e1214bd4d45390ee1b5393dc09c3785a3dc9c7e/sip-4.19.8-cp36-none-win_amd64.whl (51kB)
    100% |████████████████████████████████| 51kB 517kB/s
Collecting pywin32-ctypes!=0.1.0,!=0.1.1; sys_platform == "win32" (from keyring->spyder)
  Using cached https://files.pythonhosted.org/packages/3f/ff/da0e68961128f36b5df94d2442fede4e7c0401488e41db0016278822b01c/pywin32-ctypes-0.1.2.tar.gz
Requirement already satisfied, skipping upgrade: parso>=0.2.0 in c:\users\dmsti\anaconda3\lib\site-packages (from jedi>=0.9.0->spyder) (0.2.0)
Requirement already satisfied, skipping upgrade: ipython>=4.0.0 in c:\users\dmsti\anaconda3\lib\site-packages (from ipykernel->spyder-kernels<1.0->spyder) (6.4.0)
Requirement already satisfied, skipping upgrade: jupyter_client in c:\users\dmsti\anaconda3\lib\site-packages (from ipykernel->spyder-kernels<1.0->spyder) (5.2.3)
Requirement already satisfied, skipping upgrade: tornado>=4.0 in c:\users\dmsti\anaconda3\lib\site-packages (from ipykernel->spyder-kernels<1.0->spyder) (5.0.2)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in c:\users\dmsti\anaconda3\lib\site-packages (from Jinja2>=2.3->sphinx->spyder) (1.0)
Requirement already satisfied, skipping upgrade: pytz>=0a in c:\users\dmsti\anaconda3\lib\site-packages (from babel!=2.0,>=1.3->sphinx->spyder) (2018.4)
Requirement already satisfied, skipping upgrade: idna<2.7,>=2.5 in c:\users\dmsti\anaconda3\lib\site-packages (from requests>=2.0.0->sphinx->spyder) (2.6)
Requirement already satisfied, skipping upgrade: urllib3<1.23,>=1.21.1 in c:\users\dmsti\anaconda3\lib\site-packages (from requests>=2.0.0->sphinx->spyder) (1.22)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\dmsti\anaconda3\lib\site-packages (from requests>=2.0.0->sphinx->spyder) (2018.4.16)
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in c:\users\dmsti\anaconda3\lib\site-packages (from packaging->sphinx->spyder) (2.2.0)
Requirement already satisfied, skipping upgrade: lazy_object_proxy in c:\users\dmsti\anaconda3\lib\site-packages (from astroid<2.0,>=1.6->pylint->spyder) (1.3.1)
Requirement already satisfied, skipping upgrade: wrapt in c:\users\dmsti\anaconda3\lib\site-packages (from astroid<2.0,>=1.6->pylint->spyder) (1.10.11)
Requirement already satisfied, skipping upgrade: ipython_genutils in c:\users\dmsti\anaconda3\lib\site-packages (from traitlets>=4.2->nbconvert->spyder) (0.2.0)
Requirement already satisfied, skipping upgrade: decorator in c:\users\dmsti\anaconda3\lib\site-packages (from traitlets>=4.2->nbconvert->spyder) (4.3.0)
Requirement already satisfied, skipping upgrade: jsonschema!=2.5.0,>=2.4 in c:\users\dmsti\anaconda3\lib\site-packages (from nbformat>=4.4->nbconvert->spyder) (2.6.0)
Requirement already satisfied, skipping upgrade: html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre in c:\users\dmsti\anaconda3\lib\site-packages (from bleach->nbconvert->spyder) (1.0.1)
Requirement already satisfied, skipping upgrade: prompt-toolkit<2.0.0,>=1.0.15 in c:\users\dmsti\anaconda3\lib\site-packages (from ipython>=4.0.0->ipykernel->spyder-kernels<1.0->spyder) (1.0.15)
Requirement already satisfied, skipping upgrade: simplegeneric>0.8 in c:\users\dmsti\anaconda3\lib\site-packages (from ipython>=4.0.0->ipykernel->spyder-kernels<1.0->spyder) (0.8.1)
Requirement already satisfied, skipping upgrade: backcall in c:\users\dmsti\anaconda3\lib\site-packages (from ipython>=4.0.0->ipykernel->spyder-kernels<1.0->spyder) (0.1.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in c:\users\dmsti\anaconda3\lib\site-packages (from jupyter_client->ipykernel->spyder-kernels<1.0->spyder) (2.7.3)
Requirement already satisfied, skipping upgrade: webencodings in c:\users\dmsti\anaconda3\lib\site-packages (from html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre->bleach->nbconvert->spyder) (0.5.1)
Requirement already satisfied, skipping upgrade: wcwidth in c:\users\dmsti\anaconda3\lib\site-packages (from prompt-toolkit<2.0.0,>=1.0.15->ipython>=4.0.0->ipykernel->spyder-kernels<1.0->spyder) (0.1.7)
Building wheels for collected packages: pywin32-ctypes
  Running setup.py bdist_wheel for pywin32-ctypes ... done
  Stored in directory: C:\Users\dmsti\AppData\Local\pip\Cache\wheels\71\5b\2a\f50cada52700b961b596c9a8b8ed1a9a9d23e6b190759b90fd
Successfully built pywin32-ctypes
Installing collected packages: spyder-kernels, sip, pyqt5, pywin32-ctypes, keyring, spyder
  Found existing installation: spyder 3.2.8
Cannot uninstall 'spyder'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

C:\Users\dmsti>pip install msgpack
Collecting msgpack
  Downloading https://files.pythonhosted.org/packages/04/81/c6363198f24ec1c56e5c48ce685cb532e175125adade0cdb181c8c5fea6e/msgpack-0.5.6-cp36-cp36m-win_amd64.whl (85kB)
    100% |████████████████████████████████| 92kB 844kB/s
Installing collected packages: msgpack
Successfully installed msgpack-0.5.6

C:\Users\dmsti>pip install PySide
Collecting PySide
  Using cached https://files.pythonhosted.org/packages/36/ac/ca31db6f2225844d37a41b10615c3d371587677efd074db29855e7035de6/PySide-1.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\dmsti\AppData\Local\Temp\pip-install-0j4921ax\PySide\

C:\Users\dmsti>conda install pyside
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda==5.2.0=py36_3
  - pyside
Use "conda info <package>" to see the dependencies for each package.

```

## Versions

* Spyder version: 3.3.0 or it may be 3.3.8 per above traceback
* Python version: 3.6.5
* Anaconda version: 5.2.0 64-bit
* Qt version: not sure
* PyQt version: 5
* Operating System name/version: Windows [Version 10.0.17134.165]

**Comment by ccordoba12** [comment]
> Trying to open Spyder after some time and had to update pip and Anaconda in the process

> spyder.exe
    pip install PySide
    pip install msgpack
    pip install PySide
    conda install pyside

I'm afraid you corrupted your installation by trying to install PySide (PySide is not really needed). Our only advice is for you to remove and reinstall the latest Anaconda, sorry.

**Comment by darlastill** [comment]
figured it out by going back and forth with conda and pip uninstall/install, it is magically working.
