### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by HYL-Dave** [spyder-ide/spyder#7595]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 3, in 
start.main()
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 270, in main
import_spydercustomize()
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 30, in import_spydercustomize
import spydercustomize
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 17, in 
import pdb
File "C:\ProgramData\Anaconda3\lib\pdb.py", line 76, in 
import code
File "C:\Users\seaso\code.py", line 1, in 
import sample
File "C:\Users\seaso\sample.py", line 2, in 
print(hello(TOM));
NameError: name 'hello' is not defined
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 3, in 
start.main()
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 270, in main
import_spydercustomize()
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 30, in import_spydercustomize
import spydercustomize
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 17, in 
import pdb
File "C:\ProgramData\Anaconda3\lib\pdb.py", line 76, in 
import code
File "C:\Users\seaso\code.py", line 1, in 
import sample
File "C:\Users\seaso\sample.py", line 2, in 
print(hello(TOM));
NameError: name 'hello' is not defined
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 3, in 
start.main()
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 270, in main
import_spydercustomize()
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 30, in import_spydercustomize
import spydercustomize
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 17, in 
import pdb
File "C:\ProgramData\Anaconda3\lib\pdb.py", line 76, in 
import code
File "C:\Users\seaso\code.py", line 1, in 
import sample
File "C:\Users\seaso\sample.py", line 2, in 
print(hello(TOM));
NameError: name 'hello' is not defined
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 3, in 
start.main()
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 270, in main
import_spydercustomize()
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 30, in import_spydercustomize
import spydercustomize
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 17, in 
import pdb
File "C:\ProgramData\Anaconda3\lib\pdb.py", line 76, in 
import code
File "C:\Users\seaso\code.py", line 1, in 
import sample
File "C:\Users\seaso\sample.py", line 2, in 
print(hello(TOM));
NameError: name 'hello' is not defined
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 3, in 
start.main()
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 270, in main
import_spydercustomize()
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 30, in import_spydercustomize
import spydercustomize
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 17, in 
import pdb
File "C:\ProgramData\Anaconda3\lib\pdb.py", line 76, in 
import code
File "C:\Users\seaso\code.py", line 1, in 
import sample
File "C:\Users\seaso\sample.py", line 2, in 
print(hello(TOM));
NameError: name 'hello' is not defined

### What steps reproduce the problem?

1. Start the spyder ide
2. It fails to connect to kernel and displays the above error
3. 

### What is the expected output? What do you see instead?
Expected output is ipython kernel gets connected.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.0
* Python version: 3.6.6 64bits
* Qt version: 5.9.4
* PyQt version: 5.9.2
* Operating System name/version:  Windows 10 Pro

### Dependencies

```
IPython >=4.0     :  6.5.0 (OK)
cython >=0.21     :  0.28.4 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.15.0 (OK)
pandas >=0.13.1   :  0.23.3 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.9.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.7.6 (OK)
sympy >=0.7.3     :  1.2 (OK)

```

**Comment by jitseniesen** [comment]
The problem is the file `C:\Users\seaso\code.py`. This file has the same name as a standard library in Python; see https://docs.python.org/3/library/code.html . This confuses Python and Spyder. Please do not use `code.py` as a file name and rename the file `C:\Users\seaso\code.py`; this should fix your problem.

**Comment by ccordoba12** [comment]
Yes, that's the solution @HYL-Dave.
