### ISSUE TITLE
AttributeError: module 'spyder_kernels.utils.iofuncs' has no attribute 'iofunctions'

### ISSUE THREAD

**Issue by adaaaaaa** [spyder-ide/spyder#7671]
error code here:
Traceback (most recent call last):
  File "/usr/sbin/spyder3", line 7, in <module>
    from spyder.app.start import main
  File "/usr/lib/python3.6/site-packages/spyder/app/start.py", line 27, in <module>
    from spyder.config.main import CONF
  File "/usr/lib/python3.6/site-packages/spyder/config/main.py", line 21, in <module>
    from spyder.config.fonts import BIG, MEDIUM, MONOSPACE, SANS_SERIF
  File "/usr/lib/python3.6/site-packages/spyder/config/fonts.py", line 14, in <module>
    from spyder.config.utils import is_ubuntu
  File "/usr/lib/python3.6/site-packages/spyder/config/utils.py", line 56, in <module>
    IMPORT_EXT = list(iofuncs.iofunctions.load_extensions.values())
AttributeError: module 'spyder_kernels.utils.iofuncs' has no attribute 'iofunctions'

how can i deal with it?
python 3.6.6
spyder 3.3.1
OS: Manjaro x64

**Comment by ccordoba12** [comment]
As I told you before, if you are unwilling to use Anaconda, you have to find how to solve this problem because I have no idea where it comes from.

Please don't report this problem again.

**Comment by adaaaaaa** [comment]
@ccordoba12 
3.3.1 can't work well
but 4.0beta1 work fine...
what's the different?

**Comment by ccordoba12** [comment]
> what's the different?

It should be the version of `spyder-kernels` because `spyder-kernels < 1.0` is required for `spyder >= 3.3.0; < 4.0beta` and `spyder-kernels >= 1.0` is required for `spyder >= 4.0beta`.
