### ISSUE TITLE
Spyder crashes with 'FileSystemCommands' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#772]
_From [dima.o...@gmail.com](https://code.google.com/u/115031812180225163431/) on 2011-09-28T14:22:54Z_

After upgrade to spyder-2.1.0beta2 in Ubuntu 11.04 the program cannot start, giving either a window with a --reset option or an error:

File "/usr/local/lib/python2.7/dist-packages/spyderlib/spyder.py", line 1869, in main
    mainwindow = run_spyder(app, options)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/spyder.py", line 1780, in run_spyder
    main.setup()
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/spyder.py", line 633, in setup
    self.editor = Editor(self)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/plugins/editor.py", line 411, in __init__
    self.__load_temp_file()
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/plugins/editor.py", line 1290, in __load_temp_file
    self.load(self.TEMPFILE_PATH)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/plugins/editor.py", line 1472, in load
    current_editor = current.load(filename, set_current=True)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/editor.py", line 1740, in load
    finfo = self.create_new_editor(filename, enc, text, set_current)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/editor.py", line 1628, in create_new_editor
    finfo = FileInfo(fname, enc, editor, new, self.threadmanager)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/editor.py", line 259, in __init__
    self.rope_project = codeeditor.get_rope_project()
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/sourcecode/codeeditor.py", line 213, in get_rope_project
    ROPE_PROJECT = RopeProject()
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/sourcecode/codeeditor.py", line 91, in __init__
    self.create_rope_project(root_path=get_conf_path())
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/sourcecode/codeeditor.py", line 98, in create_rope_project
    **ROPE_PREFS)
  File "/usr/lib/python2.7/dist-packages/rope/base/project.py", line 140, in __init__
    super(Project, self).__init__(fscommands)
  File "/usr/lib/python2.7/dist-packages/rope/base/project.py", line 130, in __init__
    projectroot = _realpath(projectroot).rstrip('/\\')
  File "/usr/lib/python2.7/dist-packages/rope/base/project.py", line 428, in _realpath
    return os.path.realpath(os.path.abspath(os.path.expanduser(path)))
  File "/usr/lib/python2.7/posixpath.py", line 252, in expanduser
    if not path.startswith('~'):
AttributeError: 'FileSystemCommands' object has no attribute 'startswith'

Downgrading gives now the same error, though was working before installation of spyder-2.1.0beta2.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=772_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-09-28T20:50:34Z_

I can confirm this on Linux, but for me Spyder works again if I go back a few commits. Seems a problem with the Editor, but I'm not really sure.

I bisected the thing to revision 7ae42efeb11f . This seems to deserve a beta3 :)

**Summary:** Spyder crashes with 'FileSystemCommands' object has no attribute 'startswith'  
  **Status:** Accepted  
  **Labels:** -Priority-Medium Priority-Critical Cat-Editor OpSys-Linux

**Comment by spyder-issues-migrator** [comment]
_From [david.trem@gmail.com](https://code.google.com/u/david.trem@gmail.com/) on 2011-09-28T21:45:16Z_

Same problem on Mac OS.

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2011-09-29T03:06:28Z_

$ hg bisect -g
The first bad revision is:
changeset:   1608:7ae42efeb11f
parent:      1606:871fbd11f11e
user:        Pierre Raybaut \<pierre.raybaut@gmail.com>
date:        Wed Sep 28 16:38:55 2011 +0200
summary:     Improved Spyder's stand-alone version for Windows platforms: Spyder may now be distributed as a self-consistent executable (a Python installation is still needed on target machine of course but PyQt/PySide is not needed for example)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-09-29T07:36:35Z_

More exactly, the problem was introduced in: https://code.google.com/p/spyderlib/source/browse/spyderlib/rope_patch.py#31 to line 46. Since this is needed by py2exe/cx_Freeze (two Windows tools, I guess), wouldn't it be better to enclose those lines in an

if os.name == 'nt'

block?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-09-29T07:38:06Z_

**Labels:** OpSys-OSX

**Comment by spyder-issues-migrator** [comment]
_From [dima.o...@gmail.com](https://code.google.com/u/115031812180225163431/) on 2011-09-29T08:14:00Z_

I have removed spyderlib and spyderplugins folders from python2.7/dist-packages folder and .spyder2 from my home folder.
After that I installed spyder-2.0.12 - and it works. Old configurations were lost, but I can use the ide, which I like very much.
Thanks for your help, guys.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-09-29T23:39:46Z_

Carlos, I think you have found the source of the problem. 
Actually it's my fault: this was poorly written. I should have called the non-patched method in case of a IOError, an exception raised only for py2exe/cx_Freeze distributions. Note that the cx_Freeze distribution could also be used on Linux. 

I'll take a care of it and clean my mess. 
Sorry for the inconvenience.

**Owner:** pierre.raybaut

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-09-30T04:27:23Z_

This issue was closed by revision 17f780fcbffb .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-09-30T07:31:49Z_

Ok, thanks for the fix, Spyder starts just fine now.

**Comment by spyder-issues-migrator** [comment]
_From [dima.o...@gmail.com](https://code.google.com/u/115031812180225163431/) on 2011-09-30T08:42:37Z_

No, it does not. I am sorry to say, but I have the same problem with it again.
Here is the error:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/spyder.py", line 1869, in main
    mainwindow = run_spyder(app, options)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/spyder.py", line 1780, in run_spyder
    main.setup()
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/spyder.py", line 633, in setup
    self.editor = Editor(self)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/plugins/editor.py", line 411, in __init__
    self.__load_temp_file()
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/plugins/editor.py", line 1290, in __load_temp_file
    self.load(self.TEMPFILE_PATH)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/plugins/editor.py", line 1472, in load
    current_editor = current.load(filename, set_current=True)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/editor.py", line 1740, in load
    finfo = self.create_new_editor(filename, enc, text, set_current)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/editor.py", line 1628, in create_new_editor
    finfo = FileInfo(fname, enc, editor, new, self.threadmanager)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/editor.py", line 259, in __init__
    self.rope_project = codeeditor.get_rope_project()
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/sourcecode/codeeditor.py", line 213, in get_rope_project
    ROPE_PROJECT = RopeProject()
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/sourcecode/codeeditor.py", line 91, in __init__
    self.create_rope_project(root_path=get_conf_path())
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/sourcecode/codeeditor.py", line 98, in create_rope_project
    **ROPE_PREFS)
  File "/usr/lib/python2.7/dist-packages/rope/base/project.py", line 140, in __init__
    super(Project, self).__init__(fscommands)
  File "/usr/lib/python2.7/dist-packages/rope/base/project.py", line 130, in __init__
    projectroot = _realpath(projectroot).rstrip('/\\')
  File "/usr/lib/python2.7/dist-packages/rope/base/project.py", line 428, in _realpath
    return os.path.realpath(os.path.abspath(os.path.expanduser(path)))
  File "/usr/lib/python2.7/posixpath.py", line 252, in expanduser
    if not path.startswith('~'):
AttributeError: 'FileSystemCommands' object has no attribute 'startswith'

I upgraded from spyder-2.0.12. I ran Ubuntu 11.04.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-09-30T08:57:04Z_

Dima, did you just unzip spyder-2.1.0beta2.zip again or did you do 'hg clone' to obtain the latest release?

**Comment by spyder-issues-migrator** [comment]
_From [dima.o...@gmail.com](https://code.google.com/u/115031812180225163431/) on 2011-09-30T09:04:15Z_

I am sorry for being that stupid. I have unzipped spyder-2.1.0beta2 file. How can I get the 'hg clone'?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-09-30T09:24:11Z_

You have to excuse us too for not releasing a new beta fixing this problem. To do 'hg clone' you need to install mercurial first (a revision control system). In Ubuntu, you have to do:

$ sudo apt-get install mercurial

Then you have to go to a directory where you want to download Spyder and write:

$ hg clone https://code.google.com/p/spyderlib/ spyder

Finally, you can check that everything is working well before installing with:

$ cd spyder
$ python bootstrap.py

This will open an spyder window
