### ISSUE TITLE
run configuration stopped working

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#774]
_From [ichigo....@gmail.com](https://code.google.com/u/103498341940052785456/) on 2011-09-29T07:23:15Z_

when press run, internal console says:

\>>> Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\plugins\editor.py", line 1781, in run_file
    runconf = get_run_configuration(fname)
  File "C:\Python27\lib\site-packages\spyderlib\plugins\runconfig.py", line 97, in get_run_configuration
    configurations = _get_run_configurations()
  File "C:\Python27\lib\site-packages\spyderlib\plugins\runconfig.py", line 88, in _get_run_configurations
    for filename, options in CONF.get('run', 'configurations', [])
ValueError: need more than 1 value to unpack

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=774_

**Comment by spyder-issues-migrator** [comment]
_From [ichigo....@gmail.com](https://code.google.com/u/103498341940052785456/) on 2011-09-29T06:34:56Z_

managed to clear this by changing [run]/configuration = [] in $HOME/.spyder2/spyder.ini

not sure the cause of corruption though

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-02T05:03:02Z_

Thanks for reporting.
I can't do much about it except handling this corruption, so if it happens again, it will fail silently and run configurations will be reset (like you did manually).

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-02T05:03:25Z_

This issue was closed by revision d9ba26c3a8db .

**Status:** Fixed
