### ISSUE TITLE
Spyder crash since last session

### ISSUE THREAD

**Issue by surain82** [spyder-ide/spyder#7749]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [x ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am trying to run Anaconda Spyder and there is message popping up is showing Spyder crashed during last session, I tried reset command, I unstilled anaconda and re installed it and I am still having same issue.

### What steps reproduce the problem?

1. Just trying to open spyder in new day in my class
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: Anaconda 3 5.20
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Please close Spyder, open an Anaconda Prompt, run there

    spyder

and report back any errors printed there. Thanks!

**Comment by surain82** [comment]
Hi, Actually I was able to fix it.. Thanks for following up and for the update!

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.

**Comment by ClaudiaMarchPiris** [comment]
Hello, I have the same problem and don't know how to fix it.
I run spyder3 in my terminal, and this are the errors I get:

libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spyder/app/mainwindow.py", line 3126, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python3/dist-packages/spyder/app/mainwindow.py", line 3023, in run_spyder
    main.setup()
  File "/usr/lib/python3/dist-packages/spyder/app/mainwindow.py", line 932, in setup
    from spyder.plugins.ipythonconsole import IPythonConsole
  File "/usr/lib/python3/dist-packages/spyder/plugins/ipythonconsole.py", line 59, in <module>
    from spyder.widgets.ipythonconsole import ClientWidget
  File "/usr/lib/python3/dist-packages/spyder/widgets/ipythonconsole/__init__.py", line 12, in <module>
    from .debugging import DebuggingWidget
  File "/usr/lib/python3/dist-packages/spyder/widgets/ipythonconsole/debugging.py", line 16, in <module>
    from qtconsole.rich_jupyter_widget import RichJupyterWidget
  File "/usr/lib/python3/dist-packages/qtconsole/rich_jupyter_widget.py", line 14, in <module>
    from .jupyter_widget import JupyterWidget
  File "/usr/lib/python3/dist-packages/qtconsole/jupyter_widget.py", line 19, in <module>
    from IPython.lib.lexers import IPythonLexer, IPython3Lexer
  File "/usr/lib/python3/dist-packages/IPython/__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "/usr/lib/python3/dist-packages/IPython/terminal/embed.py", line 18, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/usr/lib/python3/dist-packages/IPython/terminal/interactiveshell.py", line 20, in <module>
    from prompt_toolkit.shortcuts import create_prompt_application, create_eventloop, create_prompt_layout, create_output
ImportError: cannot import name 'create_prompt_application'

Can you help me?

**Comment by ccordoba12** [comment]
@ClaudiaMarchPiris, simply download and install Anaconda instead of trying to use Spyder through your Linux distro because it seems broken.

**Comment by JuanDtM23** [comment]
I've been trying for a while, and the only solution I found, is to uninstall anaconda (if you have installed it), and after that, delete all folders manually using the explorer
then, reinstall anaconda and it should works

**Comment by yogivaidya** [comment]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3559, in run_spyder
    main.setup()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 960, in setup
    self.completions.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 292, in start
    client_info['plugin'].start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\plugin.py", line 141, in start
    self.kite_process = run_program(path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\programs.py", line 214, in run_program
    return subprocess.Popen(fullcmd, **subprocess_kwargs)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application
