### ISSUE TITLE
Failed to write user configuration file. Every time i open spyder using base or a new enviroment it shows up this mention.

### ISSUE THREAD

**Issue by nikospps** [spyder-ide/spyder#7775]
### What steps will reproduce the problem?

Failed to write user configuration file. Every time i open spyder using base or a new enviroment it shows up this mention.

### Traceback
```python-traceback
  File "/home/nikospps/.conda/envs/myenv/lib/python3.6/site-packages/spyder/utils/external/lockfile.py", line 154, in lock
    symlink(str(os.getpid()), self.name)
FileExistsError: [Errno 17] File exists: '12414' -> '/home/nikospps/.config/spyder-py3/spyder.lock'

Traceback (most recent call last):
  File "/home/nikospps/.conda/envs/myenv/lib/python3.6/site-packages/spyder/utils/external/lockfile.py", line 181, in lock
    kill(int(pid), 0)
ProcessLookupError: [Errno 3] No such process

Traceback (most recent call last):
  File "/home/nikospps/.conda/envs/myenv/lib/python3.6/site-packages/spyder/app/start.py", line 161, in main
    lock_created = lock.lock()
  File "/home/nikospps/.conda/envs/myenv/lib/python3.6/site-packages/spyder/utils/external/lockfile.py", line 204, in lock
    rmlink(self.name)
PermissionError: [Errno 13] Permission denied: '/home/nikospps/.config/spyder-py3/spyder.lock'

Traceback (most recent call last):
  File "/home/nikospps/.conda/envs/myenv/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1961, in valid_project
    if bool(self.projects.get_active_project_path()):
AttributeError: 'NoneType' object has no attribute 'get_active_project_path'
```

## Versions

* Spyder version: 3.3.0 
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-33-generic

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.6 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
psutil >=0.3      :  5.4.6 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.3 (OK)
numpy >=1.7       :  1.15.0 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
pylint >=0.25     :  1.9.2 (OK)
```

**Comment by ccordoba12** [comment]
Are you using an NFS mounted home?

**Comment by goanpeca** [comment]
We did not get any reply here, closing @ccordoba12 ?
