### ISSUE TITLE
Copy and &#37;paste not working from Editor to IPython 0.11 console

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#778]
_From [jones...@gmail.com](https://code.google.com/u/115331508125287012580/) on 2011-10-01T09:32:41Z_

What steps will reproduce the problem?

 1. Copy a string like print "foo"
2. &#37;paste in console (magic paste) 3. What is the expected output? What do you see instead? In [13]: &#37;paste
print "foo"
[?][?][?]a My comment: here are some strange characters, the [?] are single chars representing some strange data?
\## -- End pasted text --
\---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
C:\EclipsePython\EvolveDesign\src\<ipython-input-13-771cb64cec93> in \<module>()
----> 1 get_ipython().magic(u"paste")

C:\Python26\lib\site-packages\ipython-0.11-py2.6.egg\IPython\core\interactiveshell.pyc in magic(self, arg_s, next_input)
   1892                 self._magic_locals = sys._getframe(1).f_locals
   1893             with self.builtin_trap:
-> 1894                 result = fn(magic_args)
   1895             # Ensure we're not keeping object references around:

   1896             self._magic_locals = {}

C:\Python26\lib\site-packages\ipython-0.11-py2.6.egg\IPython\frontend\terminal\interactiveshell.pyc in magic_paste(self, parameter_s)
    588             write("## -- End pasted text --\n")
    589 
--> 590         self._execute_block(block, par)
    591 
    592     def showindentationerror(self):

C:\Python26\lib\site-packages\ipython-0.11-py2.6.egg\IPython\core\magic.pyc in _execute_block(self, block, par)
   3211             b = textwrap.dedent(block)
   3212             self.user_ns['pasted_block'] = b
-> 3213             exec b in self.user_ns
   3214         else:
   3215             self.user_ns[par] = SList(block.splitlines())

TypeError: expected string without null bytes What version of the product are you using? On what operating system? Windows XP
Spyder 2.1.0beta1
IPython 0.11 

Please provide any additional information below

. Sorry if this is the wrong place, first time poster!

Whenever I try to copy from the spyder editor (like print "foo") and magic &#37;paste into the console, I get the following error. However, when I copy from, say, notepad++, it works fine. Editor adding extra characters to the clipboard string?

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=778_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-10-07T15:24:34Z_

Hi Jones, don't worry, this is the right place to post this stuff. Our support for IPython 0.11 is very limited right but will improve in future versions with the inclusion of qtconsole.

At this moment I recommend you to downgrade IPython to version 0.10.2, which has much better support and it can handle matplotlib plots.

Nevertheless, I have to say that %paste is working for me in Linux.

Carlos

**Summary:** Copy and %paste not working from Editor to IPython 0.11 console  
  **Labels:** Cat-Console OpSys-Windows

**Comment by spyder-issues-migrator** [comment]
_From [jones...@gmail.com](https://code.google.com/u/115331508125287012580/) on 2011-10-08T02:01:41Z_

Thanks for the feedback, but no luck with IPython 0.10 either. Copy and pasting straight to the buffer with %paste in Spyder seems to add from what I can tell random information to the end of the string. But when I ctrl-v paste a single line it works fine, as in line [1]. 

This is a critical feature for me, since I also generally have problems with the ctrl-v copy paste (F9) into the console with indenting and dedenting. It's very slow, and just doesn't understand the whitespace very well. I love the concept of Spyder and am looking for a Matlab killer, but F9 in Matlab works smoothly and seamlessly. 

Will try a clean install when I get some time. 

Thanks again.




In [1]: print "foo"
------> print("foo")
foo

In [2]: %paste
\------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython console>", line 1, in \<module>
  File "C:\Python26\lib\site-packages\ipython-0.10-py2.6.egg\IPython\iplib.py", line 1182, in ipmagic
    return fn(magic_args)
  File "C:\Python26\lib\site-packages\ipython-0.10-py2.6.egg\IPython\Magic.py", line 3401, in magic_paste
    self._execute_block(block, par)
  File "C:\Python26\lib\site-packages\ipython-0.10-py2.6.egg\IPython\Magic.py", line 3319, in _execute_block
    exec b in self.user_ns
TypeError: expected string without null bytes

**Comment by spyder-issues-migrator** [comment]
_From [jones...@gmail.com](https://code.google.com/u/115331508125287012580/) on 2011-10-08T05:05:22Z_

Some more info:
The %paste function stores the clipboard text as a variable "pasted_block". Here is what happens when;

1. I copy this line from the editor:
print "foo"

2. %paste into console
TypeError: expected string without null bytes

3. Now let's look;
In [44]: repr(pasted_block)
Out[44]: '\'print "foo"\\x00\\x00\\x00\\x00\\x00\\n\''

4. Paste into Notepad++

5. Copy from Notepad++

6. %paste
In [45]: %paste
foo

7. Look at pasted_block
In [46]: repr(pasted_block)
Out[46]: '\'print "foo"\\n\''

Therefore somehow NULL is getting added to my paste from spyder editor. I should also mention that I recall %paste working fine up to some point a few weeks ago, after which it produced the above behavior. 

Cheers

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-08T05:18:19Z_

To help us debug this (unfortunately I can't reproduce this bug neither), try to add the lines:
print >>STDOUT, "selectedText():", unicode(self.textCursor().selectedText())
print >>STDOUT, "get_line_separator():", self.get_line_separator()
print >>STDOUT, "get_selected_text():", self.get_selected_text()
right before this line (with the appropriate indentation): https://code.google.com/p/spyderlib/source/browse/spyderlib/widgets/sourcecode/base.py#608 You should see these informations printed in the Spyder's parent console (on Windows, this console may be hidden: running Spyder in debug mode will avoid that).

**Comment by spyder-issues-migrator** [comment]
_From [jones...@gmail.com](https://code.google.com/u/115331508125287012580/) on 2011-10-29T01:46:08Z_

Issue resolved. I have uninstalled/ reinstalled Python(x,y) version 2.7.2.0, with Spyder 2.0.13. The %paste command now works. 

As I said, this command is fairly critical to me, since I have limited success using the F9 paste and run selection command - I often get the "unexpected indent" error, and I notice that F9 is slow, and gets slower with repeated use. 

This is in sharp contrast with the Matlab F9, where F9 commands are instant and robust. Any way I can help with this issue? Any planned improvements? 

Cheers

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-29T02:24:55Z_

Thanks for the update.
I suggest closing this issue (as the reported bug has been solved) and discuss further the improvements to be made to the "Run selection or current block" feature in issue #819 (just created).

**Status:** Done
