### ISSUE TITLE
Spyder cannot start kernel

### ISSUE THREAD

**Issue by 0novice** [spyder-ide/spyder#7855]
## Problem Description
Spyder cannot start kernel

Please note: Spyder works fine when launched from my conda root environment. However, it does not work when launched from 'myenv'.

I tried 
spyder --reset, 
restarted spyder and 
rebooted computer

### What steps reproduce the problem?

From anaconda command prompt:
>  conda create -n myenv pip python=3.5
>  activate myenv
(myenv) > conda install spyder
(myenv) >  spyder
 

### What is the expected output? What do you see instead?
Expected ipython kernel prompt

In Anaconda command window, I see:
js: Not allowed to load local resource: file:///Anaconda3/envs/myenv/lib/site-packages/spyder/utils/help/static/css/default.css

In Spyder Ipython console, I see error messages (included below).

### Paste Traceback/Error Below (if applicable)
An error ocurred while starting the kernel
Traceback (most recent call last):
File "Anaconda3\envs\myenv\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "Anaconda3\envs\myenv\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "Anaconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "Anaconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\start.py", line 284, in main
kernel.initialize()
File "", line 2, in initialize
File "Anaconda3\envs\myenv\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "Anaconda3\envs\myenv\lib\site‑packages\ipykernel\kernelapp.py", line 474, in initialize
self.init_io()
File "Anaconda3\envs\myenv\lib\site‑packages\ipykernel\kernelapp.py", line 326, in init_io
sys.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
Traceback (most recent call last):
File "Anaconda3\envs\myenv\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "Anaconda3\envs\myenv\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "Anaconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "Anaconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\start.py", line 284, in main
kernel.initialize()
File "", line 2, in initialize
File "Anaconda3\envs\myenv\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "Anaconda3\envs\myenv\lib\site‑packages\ipykernel\kernelapp.py", line 474, in initialize
self.init_io()
File "Anaconda3\envs\myenv\lib\site‑packages\ipykernel\kernelapp.py", line 326, in init_io
sys.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
Traceback (most recent call last):
File "Anaconda3\envs\myenv\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "Anaconda3\envs\myenv\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "Anaconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "Anaconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\start.py", line 284, in main
kernel.initialize()
File "", line 2, in initialize
File "Anaconda3\envs\myenv\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "Anaconda3\envs\myenv\lib\site‑packages\ipykernel\kernelapp.py", line 474, in initialize
self.init_io()
File "Anaconda3\envs\myenv\lib\site‑packages\ipykernel\kernelapp.py", line 326, in init_io
sys.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
Traceback (most recent call last):
File "Anaconda3\envs\myenv\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "Anaconda3\envs\myenv\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "Anaconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "Anaconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\start.py", line 284, in main
kernel.initialize()
File "", line 2, in initialize
File "Anaconda3\envs\myenv\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "Anaconda3\envs\myenv\lib\site‑packages\ipykernel\kernelapp.py", line 474, in initialize
self.init_io()
File "Anaconda3\envs\myenv\lib\site‑packages\ipykernel\kernelapp.py", line 326, in init_io
sys.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
Traceback (most recent call last):
File "Anaconda3\envs\myenv\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "Anaconda3\envs\myenv\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "Anaconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "Anaconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\start.py", line 284, in main
kernel.initialize()
File "", line 2, in initialize
File "Anaconda3\envs\myenv\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "Anaconda3\envs\myenv\lib\site‑packages\ipykernel\kernelapp.py", line 474, in initialize
self.init_io()
File "Anaconda3\envs\myenv\lib\site‑packages\ipykernel\kernelapp.py", line 326, in init_io
sys.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'flush'

## Versions

* Spyder version: 3.3.1
* Python version: 3.5.6
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 64-bit

### Dependencies
IPython >=4.0     :  6.5.0 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.12.1 (OK)
matplotlib >=2.0.0:  None (NOK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  None (NOK)
pandas >=0.13.1   :  None (NOK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  2.1.1 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.7.8 (OK)
sympy >=0.7.3     :  None (NOK)

**Comment by ccordoba12** [comment]
This is fixed by running in your env

    conda install ipykernel=4.8.2

It's not a problem with Spyder, so I'm closing this issue.

**Comment by ccordoba12** [comment]
You don't need to since our 3.3.1 version. Please take a look at our blog post about it:

https://www.spyder-ide.org/blog/release-spyder-330/

**Comment by 0novice** [comment]
Perfect. Thank you! @ccordoba12 
(Now if only all my other packages would also not require separate identical version installations :-)
  jupyter notebook, scikit-learn etc
