### ISSUE TITLE
DictEditor crashes on edit

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#786]
_From [christop...@gmail.com](https://code.google.com/u/105753816054647931594/) on 2011-10-05T16:22:00Z_

What steps will reproduce the problem?

 1. open dict editor on an existing dict
2. try edit one value 3. What is the expected output? What do you see instead? value should change. instead an exception is thrown:

\------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/christoph/Documents/Prog/Python/spyderlib-hg/spyderlib/spyderlib/widgets/dicteditor.py", line 458, in setModelData
    ignore_errors=False)
  File "/Users/christoph/Documents/Prog/Python/spyderlib-hg/spyderlib/spyderlib/widgets/dicteditor.py", line 48, in display_to_value
    np_dtype = get_numpy_dtype(default_value)
  File "/Users/christoph/Documents/Prog/Python/spyderlib-hg/spyderlib/spyderlib/widgets/dicteditorutils.py", line 30, in get_numpy_dtype
    for np_dtype in (np.complex192, np.complex128,
AttributeError: 'module' object has no attribute 'complex192' Please use labels and text to provide additional information. this is caused by float96 not being existent on (as far as I know) 64bit systems...). There on has to use float128, complex256 etc.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=786_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-06T07:06:18Z_

I'll take care of it. Thanks for reporting.

**Owner:** pierre.raybaut  
  **Cc:** christop...@gmail.com  
  **Labels:** Milestone-Release2.1

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-06T08:33:10Z_

**Summary:** DictEditor crashes on edit  
  **Labels:** Cat-VariableExplorer

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-06T08:33:44Z_

This issue was closed by revision bf0f5ddcbfa0 .

**Status:** Fixed
