### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by wufangzhao** [spyder-ide/spyder#7871]
### What steps will reproduce the problem?

```
Traceback (most recent call last):
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\spyder_kernels\console\start.py", line 284, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\ipykernel\kernelapp.py", line 474, in initialize
self.init_io()
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\ipykernel\kernelapp.py", line 326, in init_io
sys.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
Traceback (most recent call last):
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\spyder_kernels\console\start.py", line 284, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\ipykernel\kernelapp.py", line 474, in initialize
self.init_io()
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\ipykernel\kernelapp.py", line 326, in init_io
sys.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
Traceback (most recent call last):
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\spyder_kernels\console\start.py", line 284, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\ipykernel\kernelapp.py", line 474, in initialize
self.init_io()
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\ipykernel\kernelapp.py", line 326, in init_io
sys.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
Traceback (most recent call last):
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\spyder_kernels\console\start.py", line 284, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\ipykernel\kernelapp.py", line 474, in initialize
self.init_io()
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\ipykernel\kernelapp.py", line 326, in init_io
sys.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
Traceback (most recent call last):
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\spyder_kernels\console\start.py", line 284, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\ipykernel\kernelapp.py", line 474, in initialize
self.init_io()
File "C:\Users\wufangzhao\AppData\Local\Programs\Python\Python36󈛄\lib\site‑packages\ipykernel\kernelapp.py", line 326, in init_io
sys.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
```

## Versions

* Spyder version: 4.0.0.dev0 7e4c213
* Python version: 3.6.6
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.8 (OK)
pyls >=0.19.0     :  0.21.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  None (NOK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
This is fixed by running in a system terminal (cmd.exe)

    pip install ipykernel==4.8.2
