### ISSUE TITLE
Invalid import in spyderlib.widgets.dicteditor

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#788]
_From [adriaan....@gmail.com](https://code.google.com/u/105761755411544425242/) on 2011-10-07T06:31:50Z_

Spyder Version:  2.1.0beta3
Python Version:  2.6.6
Qt Version:      4.7.1, PyQt4 (API v1) 4.8.2 on Windows 

What steps will reproduce the problem?

 1. download the installation software
2. run installer
3. start spyder What is the expected output? What do you see instead? expect: spyder IDE
experience: 
Traceback (most recent call last):
  File "C:\Program Files\Python26\Scripts\spyder", line 2, in \<module>
    from spyderlib import spyder
  File "c:\program files\python26\lib\site-packages\spyderlib\spyder.py", line 97, in \<module>
    from spyderlib.plugins.console import Console
  File "c:\program files\python26\lib\site-packages\spyderlib\plugins\console.py", line 32, in \<module>
    from spyderlib.utils.environ import EnvDialog
  File "c:\program files\python26\lib\site-packages\spyderlib\utils\environ.py", line 17, in \<module>
    from spyderlib.widgets.dicteditor import DictEditor
  File "c:\program files\python26\lib\site-packages\spyderlib\widgets\dicteditor.py", line 34, in \<module>
    from spyderlib.widgets.dicteditorutils import (sort_against, get_size,ImportError: cannot import name PIL 

Please provide any additional information below

. it seems that dicteditor imports Image and PIL, where Image = PIL.Image. dicteditor then uses both Image and PIL.Image (2 occurrances). i solved the issue by simply replacing "PIL.Image" with "Image" in dicteditor.py

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=788_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-10-07T14:08:25Z_

This one affects Mac users and everyone who is installing Spyder in a bare bones Python distribution. I think I've seen it mentioned on the mailing list too.

Should we mention PIL as a new Spyder dependency or can we replace "PIL.Image" with "Image", as adriaan suggests?

**Summary:** Invalid import in spyderlib.widgets.dicteditor  
  **Status:** Accepted  
  **Labels:** Cat-VariableExplorer

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-10-08T10:35:49Z_

issue #753 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-09T07:37:36Z_

I vote for handling missing PIL dependency.
Spyder strictly requires only Python and PyQt (or PySide) and I think it's good thing.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-09T07:37:57Z_

This issue was closed by revision b7e67a814802 .

**Status:** Fixed
