### ISSUE TITLE
Error while starting kernel

### ISSUE THREAD

**Issue by MrSrSan** [spyder-ide/spyder#7889]
Hello i've got an issue when starting Spyder, the Terminal shows the next message:

Ocurrió un error mientras iniciaba el núcleo (An error has ocurred while starting the kernel)
El error es: (The error is:)

Traceback (most recent call last):
File "C:\Users\Admin\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1525, in create_kernel_manager_and_kernel_client
config=None, autorestart=True)
File "C:\Users\Admin\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 958, in __new__
inst.setup_instance(*args, **kwargs)
File "C:\Users\Admin\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 986, in setup_instance
super(HasTraits, self).setup_instance(*args, **kwargs)
File "C:\Users\Admin\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 977, in setup_instance
value.instance_init(self)
File "C:\Users\Admin\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1691, in instance_init
self._resolve_classes()
File "C:\Users\Admin\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1696, in _resolve_classes
self.klass = self._resolve_string(self.klass)
File "C:\Users\Admin\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1507, in _resolve_string
return import_item(string)
File "C:\Users\Admin\Anaconda3\lib\site‑packages\traitlets\utils\importstring.py", line 34, in import_item
module = __import__(package, fromlist=[obj])
File "C:\Users\Admin\Anaconda3\lib\site‑packages\jupyter_client\session.py", line 61, in 
from jupyter_client.jsonutil import extract_dates, squash_dates, date_default
File "C:\Users\Admin\Anaconda3\lib\site‑packages\jupyter_client\jsonutil.py", line 11, in 
from dateutil.parser import parse as _dateutil_parse
File "C:\Users\Admin\Anaconda3\lib\site‑packages\dateutil\parser.py", line 158
l.append("%s=%s" % (attr, `value`))
^
SyntaxError: invalid syntax

I've tryied updating Anaconda, Spyder, also spyder reset and reinstalling but the still the same.
Thanks for reading and for the help.

**Comment by ccordoba12** [comment]
I don't understand this error but it should be fixed by removing and reinstalling Anaconda again.

**Comment by MrSrSan** [comment]
Thanks, was very helpfull, i did so, but now i'm getting a new error while trying to run the next code:

```
nc = netCDF4.Dataset('path/to/file.nc4', mode='r')
nc.variables.keys()

time_var = nc.variables['time'] 
dtime = netCDF4.num2date(time_var[:],time_var.units)
```
# This is the error I get:

In [X]: dtime = netCDF4.num2date(time_var[:],time_var.units) 
Traceback (most recent call last):

  File "<ipython-input-151-73626dd46727>", line 1, in <module>
    dtime = netCDF4.num2date(time_var[:],time_var.units)

  File "cftime/_cftime.pyx", line 290, in cftime._cftime.num2date

  File "cftime/_cftime.pyx", line 1211, in cftime._cftime.utime.num2date

  File "C:\Users\Admin\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 257, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)

  File "C:\Users\Admin\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)

ValueError: cannot reshape array of size 1 into shape (24,)

# So i fixed it by using a for:

```
time_var = nc.variables['time']
dtime = []
for k in range(len(time_var)) :
    dtime.append(netCDF4.num2date(time_var[k],time_var.units))

```

The thing is the code worked just fine before unisntalling and reinstalling Anaconda, any idea of what could be happening? 

Thanks for the help.

**Comment by ccordoba12** [comment]
Sorry, I don't know.
