### ISSUE TITLE
An error ocurred while starting the kernel: ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by DataXujing** [spyder-ide/spyder#7897]
## Problem Description

```
An error ocurred while starting the kernel
Error in sitecustomize; set PYTHONVERBOSE for traceback:
ValueError: source code string cannot contain null bytes
Traceback (most recent call last):
File "D:\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 269, in 
main()
File "D:\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 237, in main
from ipykernel.kernelapp import IPKernelApp
File "D:\Anaconda3\lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "D:\Anaconda3\lib\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "D:\Anaconda3\lib\site‑packages\IPython\__init__.py", line 52, in 
from .core.getipython import get_ipython
ValueError: source code string cannot contain null bytes
Error in sitecustomize; set PYTHONVERBOSE for traceback:
ValueError: source code string cannot contain null bytes
Traceback (most recent call last):
File "D:\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 269, in 
main()
File "D:\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 237, in main
from ipykernel.kernelapp import IPKernelApp
File "D:\Anaconda3\lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "D:\Anaconda3\lib\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "D:\Anaconda3\lib\site‑packages\IPython\__init__.py", line 52, in 
from .core.getipython import get_ipython
ValueError: source code string cannot contain null bytes
Error in sitecustomize; set PYTHONVERBOSE for traceback:
ValueError: source code string cannot contain null bytes
Traceback (most recent call last):
File "D:\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 269, in 
main()
File "D:\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 237, in main
from ipykernel.kernelapp import IPKernelApp
File "D:\Anaconda3\lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "D:\Anaconda3\lib\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "D:\Anaconda3\lib\site‑packages\IPython\__init__.py", line 52, in 
from .core.getipython import get_ipython
ValueError: source code string cannot contain null bytes
Error in sitecustomize; set PYTHONVERBOSE for traceback:
ValueError: source code string cannot contain null bytes
Traceback (most recent call last):
File "D:\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 269, in 
main()
File "D:\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 237, in main
from ipykernel.kernelapp import IPKernelApp
File "D:\Anaconda3\lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "D:\Anaconda3\lib\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "D:\Anaconda3\lib\site‑packages\IPython\__init__.py", line 52, in 
from .core.getipython import get_ipython
ValueError: source code string cannot contain null bytes
Error in sitecustomize; set PYTHONVERBOSE for traceback:
ValueError: source code string cannot contain null bytes
Traceback (most recent call last):
File "D:\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 269, in 
main()
File "D:\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 237, in main
from ipykernel.kernelapp import IPKernelApp
File "D:\Anaconda3\lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "D:\Anaconda3\lib\site‑packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "D:\Anaconda3\lib\site‑packages\IPython\__init__.py", line 52, in 
from .core.getipython import get_ipython
ValueError: source code string cannot contain null bytes
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating system: Windows 7

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
numpy >=1.7      :  1.14.3 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.4.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
```

**Comment by ccordoba12** [comment]
> ValueError: source code string cannot contain null bytes

This indicates to me that your installation is corrupt. So our only recommendation is for you to remove and reinstall Anaconda again.
