### ISSUE TITLE
Spyder launch error

### ISSUE THREAD

**Issue by kfaheem** [spyder-ide/spyder#7931]
## Problem Description - I get a spyder launch error while trying to launch spyder in Anaconda Navigator after a fresh download. Running on Linux Fedora.

Traceback (most recent call last):
File "/home/cloudera/anaconda3/lib/python3.7/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in 
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: libEGL.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/cloudera/anaconda3/bin/spyder", line 11, in 
sys.exit(main())
File "/home/cloudera/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 190, in main
from spyder.app import mainwindow
File "/home/cloudera/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 92, in 
from qtpy import QtWebEngineWidgets # analysis:ignore
File "/home/cloudera/anaconda3/lib/python3.7/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in 
from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

**Comment by ccordoba12** [comment]
> ImportError: libEGL.so.1: cannot open shared object file: No such file or directory

The error is clear: you need to install a package with your Linux package manager that provides that library. In Debian/Ubuntu, the command to do that is

    sudo apt-get install libegl1-mesa

I don't what command you need in Fedora, sorry. But I guess you can easily google for it.

**Comment by kfaheem** [comment]
Thanks for the comment. I tried installing the library using >> sudo yum install libegl1-mesa. It returned 'no package libegl1-mesa available'. Could you please help me with an alternative?
