### ISSUE TITLE
Unable to open Spyder, KeyError: 'pyside'

### ISSUE THREAD

**Issue by OD1995** [spyder-ide/spyder#7932]
## Problem Description
![pyside](https://user-images.githubusercontent.com/34351331/45909095-f16fae00-bdf7-11e8-8637-b5b95a81a91c.PNG)

### What steps reproduce the problem?

1. Run spyder from Anaconda Prompt. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

C:\ProgramData\Anaconda3\lib\site-packages\qtpy\__init__.py:211: RuntimeWarning: Selected binding "pyqt5" could not be found, using "pyside"
  'using "{}"'.format(initial_api, API), RuntimeWarning)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\start.py", line 190, in main
    from spyder.app import mainwindow
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 50, in <module>
    requirements.check_qt()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\requirements.py", line 42, in check_qt
    package_name, required_ver = qt_infos[qtpy.API]
KeyError: 'pyside'

```

## Versions

* Spyder version: 3.3.1
* Python version: 3.6.6
* Qt version: 4.8.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

**Comment by ccordoba12** [comment]
> Qt version: 4.8.7

We don't support Qt4 anymore. Please Qt5 instead.

**Comment by adaaaaaa** [comment]
have you solve the problem?
