### ISSUE TITLE
ipython console in miniconda not starting

### ISSUE THREAD

**Issue by mayurpande** [spyder-ide/spyder#7957]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Ipython Console not working in miniconda virtual environment

### What steps reproduce the problem?

1. Created a virtual env like so;
```
conda create -n myenv python=3.7
activate myenv
conda install -n myenv spyder
spyder
```

### What is the expected output? What do you see instead?
Ipython to work instead I see;

![screenshot 337](https://user-images.githubusercontent.com/6522456/46141330-ef707980-c253-11e8-97fc-de030cf23b99.png)

### Paste Traceback/Error Below (if applicable)

```python-traceback

An error ocurred while starting the kernel
Traceback (most recent call last):
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\start.py", line 284, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\ipykernel\kernelapp.py", line 474, in initialize
self.init_io()
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\ipykernel\kernelapp.py", line 326, in init_io
sys.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
Traceback (most recent call last):
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\start.py", line 284, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\ipykernel\kernelapp.py", line 474, in initialize
self.init_io()
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\ipykernel\kernelapp.py", line 326, in init_io
sys.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
Traceback (most recent call last):
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\start.py", line 284, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\ipykernel\kernelapp.py", line 474, in initialize
self.init_io()
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\ipykernel\kernelapp.py", line 326, in init_io
sys.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
Traceback (most recent call last):
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\start.py", line 284, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\ipykernel\kernelapp.py", line 474, in initialize
self.init_io()
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\ipykernel\kernelapp.py", line 326, in init_io
sys.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
Traceback (most recent call last):
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\spyder_kernels\console\start.py", line 284, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\ipykernel\kernelapp.py", line 474, in initialize
self.init_io()
File "C:\Users\mwx611650\AppData\Local\Continuum\miniconda3\envs\myenv\lib\site‑packages\ipykernel\kernelapp.py", line 326, in init_io
sys.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'flush'

```

## Versions

* Spyder version: 3.31
* Python version: 3.7
* Qt version: 5.9.6 vc14h1e9a669_2
* PyQt version: 5.9.2  py37h6538335_2
* Operating System name/version: windows 10

**Comment by mayurpande** [comment]
solved I had to follow this. https://github.com/spyder-ide/spyder/issues/7821

**Comment by mayurpande** [comment]
do I need to install spyder in each virtual environment I create? Seems like a bit of an overkill

**Comment by ccordoba12** [comment]
No, please see

https://www.spyder-ide.org/blog/release-spyder-330/
