### ISSUE TITLE
spyderlib/qt/QtGui.py -- ImportError: cannot import name QKeySequence (on Ubuntu 10.04)

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#797]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-11T12:47:15Z_

Bug submitted to me recently by a user:
\--------------------------------------

"I was not coding for a while, but today starting spyder (the latest linux version, 2.0.12), I had the following error message:

Traceback (most recent call last):
 File "/usr/local/bin/spyder", line 2, in \<module>
   from spyderlib import spyder
 File "/usr/local/lib/python2.6/dist-packages/spyderlib/spyder.py", line 38, in \<module>
   from spyderlib.qt.QtGui import (QApplication, QMainWindow, QSplashScreen,
 File "/usr/local/lib/python2.6/dist-packages/spyderlib/qt/QtGui.py", line 10, in \<module>
   from PyQt4.Qt import QKeySequence, QTextCursor
ImportError: cannot import name QKeySequence

I guess that there was an update in PyQt4 or something, because I tried also on my laptop and I had the same issue... Do you have any idea on how to solve the problem? I am using ubuntu 10.4 LTS 64 on both my machines. My version of PyQt4 is 4.7.2-0ubuntu1."

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=797_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-10-20T19:32:02Z_

**Labels:** Cat-SpyderGUI Component-PyQt

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-22T02:38:05Z_

Tested Spyder v2.0.12 and v2.1.0dev on an up-to-date Ubuntu 10.04 LTS:
unable to reproduce this issue.

This must be the result of a non-standard PyQt installation.
With standard Ubuntu 10.04 python-qt4 package the following line works in a standard Python interpreter:
from PyQt4.Qt import QKeySequence, QTextCursor

**Status:** Invalid

**Comment by spyder-issues-migrator** [comment]
_From [lisa...@gmail.com](https://code.google.com/u/113086228506834329690/) on 2012-02-03T19:42:57Z_

I've got this exact same problem on Mac 10.7.2 with PyQt-mac-4.9 and spyder 2.1.7. No errors while installing.

**Comment by spyder-issues-migrator** [comment]
_From [ungaming...@gmail.com](https://code.google.com/u/111025579261102121920/) on 2012-12-30T23:20:16Z_

Got same error running windows 7 and python(x,y).

**Comment by spyder-issues-migrator** [comment]
_From [johannes...@googlemail.com](https://code.google.com/u/106772984759351281130/) on 2013-08-18T11:12:58Z_

The import should be

from PyQt4.QtGui import QKeySequence

**Comment by spyder-issues-migrator** [comment]
_From [strickla...@gmail.com](https://code.google.com/u/111045366386016874016/) on 2015-02-16T10:49:21Z_

I get this error when trying to run spyder.exe on windows 8.1 with Anaconda installed for all useres. It effectively prevents spyder from loading via the start menu (though you never see the error there, since it occurs in the background). Hitting WindowsButton+R and running cmd /k C:\Anaconda\Scripts\spyder.exe will reproduce the error.

**Comment by spyder-issues-migrator** [comment]
_From [strickla...@gmail.com](https://code.google.com/u/111045366386016874016/) on 2015-02-16T12:26:20Z_

I've been hunting this bug all day and I finally got it figured out.

Symptoms:
-- Start menu shortcut for spyder -> nothing happens. (this is because pythonw.exe runs in the background, so you don't see the traceback.

-- Running spyder.exe by double clicking in Windows explorer at C:\Anaconda\Scripts does nothing either.

-- If you open a terminal (cmd.exe) and try running spyder via typing in the full path of spyder.exe (i.e. C:\Anaconda\Scripts\spyder.exe) you finally get an error message:
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\spyder-script.py", line 2, in \<module>
    start_app.main()
  File "C:\Anaconda\lib\site-packages\spyderlib\start_app.py", line 91, in main
    from spyderlib import spyder
  File "C:\Anaconda\lib\site-packages\spyderlib\spyder.py", line 101, in \<module>
    from spyderlib.qt.QtGui import (QApplication, QMainWindow, QSplashScreen,
  File "C:\Anaconda\lib\site-packages\spyderlib\qt\QtGui.py", line 10, in \<module>
    from PyQt4.Qt import QKeySequence, QTextCursor  # analysis:ignore
ImportError: cannot import name QKeySequence

-- You previously or currently have another Python distribution on your computer. In my case, it was a WinPython distribution that I had once registered with the system. This meant that opening up cmd.exe and just typing spyder actually worked... it launched spyder from the portable WinPython distribution sitting somewhere else on my computer, not from Anaconda.

Solution:
If another python distribution is registered with the system, its directories are listed in the system variables Path, likely in an order so that the system searches there before in the Anaconda folders. You can verify this by going to Advanced system settings in PC Info or Control Panel->System, Environment Variables, and look under System Variables for Path. Click and hit Edit. You get a possibly long semi-colon list of directories. Look for those belonging to another python distribution and delete only those, so that everything else including the Anaconda folders remain. It might also be possible to just reorder so that the Anaconda folders are first. I haven't tried this.

Now restart your computer to reload the Path variable and check that everything works.
