### ISSUE TITLE
Error while starting kernel

### ISSUE THREAD

**Issue by Wanhope** [spyder-ide/spyder#7973]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When I start spyder via the GUI I get an error message on startup in the IPython console that repeats itself at short intervals. If I open spyder via the terminal a different error is printed every few seconds in the console.

### What steps reproduce the problem?

1. starting spyder via GUI 
2. starting spyder via terminal
3. 

### What is the expected output? What do you see instead?

I dont expect a startup error from the kernel. cant run any programs in spyder.

### Paste Traceback/Error Below (if applicable)

```python-traceback

An error ocurred while starting the kernel
Traceback (most recent call last):
File "/home/alexander/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/home/alexander/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/alexander/anaconda3/lib/python3.6/site‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/home/alexander/anaconda3/lib/python3.6/site‑packages/spyder_kernels/console/start.py", line 272, in main
import_spydercustomize()
File "/home/alexander/anaconda3/lib/python3.6/site‑packages/spyder_kernels/console/start.py", line 32, in import_spydercustomize
import spydercustomize
File "/home/alexander/anaconda3/lib/python3.6/site‑packages/spyder_kernels/customize/spydercustomize.py", line 25, in 
from IPython.core.getipython import get_ipython
File "/home/alexander/anaconda3/lib/python3.6/site‑packages/IPython/__init__.py", line 54, in 
from .core.application import Application
File "/home/alexander/anaconda3/lib/python3.6/site‑packages/IPython/core/application.py", line 23, in 
from traitlets.config.application import Application, catch_config_error
File "/home/alexander/anaconda3/lib/python3.6/site‑packages/traitlets/config/__init__.py", line 6, in 
from .application import *
File "/home/alexander/anaconda3/lib/python3.6/site‑packages/traitlets/config/application.py", line 19, in 
from traitlets.config.configurable import Configurable, SingletonConfigurable
File "/home/alexander/anaconda3/lib/python3.6/site‑packages/traitlets/config/configurable.py", line 12, in 
from .loader import Config, LazyConfigValue, _is_section_key
File "/home/alexander/anaconda3/lib/python3.6/site‑packages/traitlets/config/loader.py", line 16, in 
from ipython_genutils.path import filefind
File "/home/alexander/anaconda3/lib/python3.6/site‑packages/ipython_genutils/path.py", line 13, in 
import random
File "/home/alexander/random.py", line 9, in 
import numpy.random as rd
File "/home/alexander/anaconda3/lib/python3.6/site‑packages/numpy/__init__.py", line 142, in 
from . import add_newdocs
File "/home/alexander/anaconda3/lib/python3.6/site‑packages/numpy/add_newdocs.py", line 13, in 
from numpy.lib import add_newdoc
File "/home/alexander/anaconda3/lib/python3.6/site‑packages/numpy/lib/__init__.py", line 8, in 
from .type_check import *
File "/home/alexander/anaconda3/lib/python3.6/site‑packages/numpy/lib/type_check.py", line 11, in 
import numpy.core.numeric as _nx
File "/home/alexander/anaconda3/lib/python3.6/site‑packages/numpy/core/__init__.py", line 103, in 
from numpy.testing._private.pytesttester import PytestTester
File "/home/alexander/anaconda3/lib/python3.6/site‑packages/numpy/testing/__init__.py", line 12, in 
from ._private.utils import *
File "/home/alexander/anaconda3/lib/python3.6/site‑packages/numpy/testing/_private/utils.py", line 16, in 
from tempfile import mkdtemp, mkstemp
File "/home/alexander/anaconda3/lib/python3.6/tempfile.py", line 45, in 
from random import Random as _Random
ImportError: cannot import name 'Random'


Terminal error:
js: Not allowed to load local resource: file:///home/alexander/anaconda3/lib/python3.6/site.packages/spyder/utils/help/static/css/default.css
```

## Versions

* Spyder version: 3.1.1
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: ubtunu 18.04.1 LTS

### Dependencies

```
IPython >=4.0     :  6.5.0 (OK)
cython >=0.21     :  0.28.5 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.15.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
psutil >=0.3      :  5.4.7 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  2.1.1 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
sympy >=0.7.3     :  1.2 (OK)
```

**Comment by ccordoba12** [comment]
This is not an error in Spyder, but most probably caused because you created a file called `random.py` in the working directory the kernel starts (your home is the default working directory used by Spyder).
