### ISSUE TITLE
Traceback with PySide 1.0.7/1.0.8 when Outline item is clicked

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#800]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2011-10-16T04:33:29Z_

Spyder Version:  2.1.0beta3
Python Version:  2.7.1
Qt Version:      4.7.4, PySide 1.0.7 on Linux 

What steps will reproduce the problem?

 It is hard to reproduce 100&#37;. Seems like the problem is caused by destroyed scrollbar object. Backtrace is at http://pastebin.com/pmNHYtKm I'll attach more info if it repeats

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=800_

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2011-10-16T02:57:25Z_

Here is the traceback after which Spyder starts quitting with SegFault. Seems like it is caused by interaction with Outline.

Traceback (most recent call last):
  File "/home/user07/spyderlib/spyderlib/widgets/sourcecode/codeeditor.py", line 345, in paintEvent
    self.code_editor.scrollflagarea_paint_event(event)
  File "/home/user07/spyderlib/spyderlib/widgets/sourcecode/codeeditor.py", line 1223, in scrollflagarea_paint_event
    position = self.scrollflagarea.value_to_position(line_number)
  File "/home/user07/spyderlib/spyderlib/widgets/sourcecode/codeeditor.py", line 364, in value_to_position
    return (y-self.vsb.minimum())*self.get_scale_factor(slider)+offset
RuntimeError: Internal C++ object (PySide.QtGui.QScrollBar) already deleted.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-16T04:04:23Z_

This is still too vague for me to understand exactly what's going on.
Keep me posted if you are able to reproduce it.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-10-20T19:26:04Z_

**Labels:** Component-PySide Cat-SpyderGUI

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2011-10-21T02:47:11Z_

It appeared that it is really easy to reproduce. Just start Spyder RC1 with PySide 1.0.8 and click on any Outline item. In less than a second a traceback appears in internal console.

**Summary:** Traceback with PySide 1.0.8 when Outline item is clicked

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2011-10-21T07:43:21Z_

Filed to PySide, because with PyQt everything is ok. http://bugs.pyside.org/show_bug.cgi?id=1030 (round number too) =)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-22T09:46:33Z_

I don't know why exactly, but with PySide, the editor's (QPlainTextEdit) vertical scroll bar is at some point deleted and re-created. As a consequence, the first reference pointing to it (stored in the editor widget's constructor) is later pointing to a Python object associated with a deleted underlying C++ object...

So calling editor.verticalScrollBar() each time (instead of using the old reference) solved the problem.

See the fix in next comment.

I'm not so sure that it's a PySide bug -- all I can tell is that it just behaves differently from PyQt, but anyway informing PySide developers was a good idea as this may be a bug or a misbehavior of PySide.

**Status:** Started

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-22T09:47:01Z_

This issue was closed by revision 9e20bc8ccc63 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2011-10-22T14:44:16Z_

The bad side that with this fix the problem is not reproducible anymore as described in http://bugs.pyside.org/show_bug.cgi?id=1030

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-23T00:41:57Z_

If they take a look at my comments (the fact that the vertical scroll bar is deleted and recreated...) maybe they will be able to conclude on this anyway. 

Note that updating to the revision just before this fix will allow to reproduce the bug.
