### ISSUE TITLE
An error ocurred while starting the kernel Traceback (most recent call last):

### ISSUE THREAD

**Issue by ElectroSpaghetti** [spyder-ide/spyder#8006]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Cannot connect to the kernel

### What steps reproduce the problem?

1. Every time I launch spyder
2. 
3. 

### What is the expected output? What do you see instead?
a functioning kernel.

### Paste Traceback/Error Below (if applicable)
An error ocurred while starting the kernel
Traceback (most recent call last):
File "C:\Users\Ely\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\Ely\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\Ely\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\Ely\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 272, in main
import_spydercustomize()
File "C:\Users\Ely\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 32, in import_spydercustomize
import spydercustomize
File "C:\Users\Ely\Anaconda3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 25, in 
from IPython.core.getipython import get_ipython
File "C:\Users\Ely\Anaconda3\lib\site‑packages\IPython\__init__.py", line 54, in 
from .core.application import Application
File "C:\Users\Ely\Anaconda3\lib\site‑packages\IPython\core\application.py", line 26, in 
from IPython.core.profiledir import ProfileDir, ProfileDirError
File "C:\Users\Ely\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 12, in 
from IPython.paths import get_ipython_package_dir
File "C:\Users\Ely\Anaconda3\lib\site‑packages\IPython\paths.py", line 5, in 
import tempfile
File "C:\Users\Ely\Anaconda3\lib\tempfile.py", line 45, in 
from random import Random as _Random
ImportError: cannot import name 'Random' from 'random' (C:\Users\Ely\Desktop\spyder\random.py)
Traceback (most recent call last):
File "C:\Users\Ely\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\Ely\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\Ely\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\Ely\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 272, in main
import_spydercustomize()
File "C:\Users\Ely\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 32, in import_spydercustomize
import spydercustomize
File "C:\Users\Ely\Anaconda3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 25, in 
from IPython.core.getipython import get_ipython
File "C:\Users\Ely\Anaconda3\lib\site‑packages\IPython\__init__.py", line 54, in 
from .core.application import Application
File "C:\Users\Ely\Anaconda3\lib\site‑packages\IPython\core\application.py", line 26, in 
from IPython.core.profiledir import ProfileDir, ProfileDirError
File "C:\Users\Ely\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 12, in 
from IPython.paths import get_ipython_package_dir
File "C:\Users\Ely\Anaconda3\lib\site‑packages\IPython\paths.py", line 5, in 
import tempfile
File "C:\Users\Ely\Anaconda3\lib\tempfile.py", line 45, in 
from random import Random as _Random
ImportError: cannot import name 'Random' from 'random' (C:\Users\Ely\Desktop\spyder\random.py)
Traceback (most recent call last):
File "C:\Users\Ely\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\Ely\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\Ely\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\Ely\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 272, in main
import_spydercustomize()
File "C:\Users\Ely\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 32, in import_spydercustomize
import spydercustomize
File "C:\Users\Ely\Anaconda3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 25, in 
from IPython.core.getipython import get_ipython
File "C:\Users\Ely\Anaconda3\lib\site‑packages\IPython\__init__.py", line 54, in 
from .core.application import Application
File "C:\Users\Ely\Anaconda3\lib\site‑packages\IPython\core\application.py", line 26, in 
from IPython.core.profiledir import ProfileDir, ProfileDirError
File "C:\Users\Ely\Anaconda3\lib\site‑packages\IPython\core\profiledir.py", line 12, in 
from IPython.paths import get_ipython_package_dir
File "C:\Users\Ely\Anaconda3\lib\site‑packages\IPython\paths.py", line 5, in 
import tempfile
File "C:\Users\Ely\Anaconda3\lib\tempfile.py", line 45, in 
from random import Random as _Random
ImportError: cannot import name 'Random' from 'random' (C:\Users\Ely\Desktop\spyder\random.py)
Traceback (most recent call last):

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3
* Python version: 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10
### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
As I told you before, this is not an error in Spyder but due to you having a file called `random.py` in the same directory where a kernel is trying to start. This time the traceback is even telling you where it's located, it's here:

    ImportError: cannot import name 'Random' from 'random' (C:\Users\Ely\Desktop\spyder\random.py)

Please don't post the same error again and just rename that file.

**Comment by ccordoba12** [comment]
Sorry if it wasn't you the same author of #7973, but it's the exact same problem.

**Comment by ccordoba12** [comment]
@ElectroSpaghetti, since I recalled someone reported the same problem a couple of days ago, I thought you were the same person. So I apologize too for assuming that.

Glad you found the `random.py` that was causing problems.
