### ISSUE TITLE
Kernel crash due to file with the same name of a stdlib Python module present in current working directory

### ISSUE THREAD

**Issue by SaranshBakshi** [spyder-ide/spyder#8007]
So this is the issue I am facing in the Spyder Console. Help. 

An error ocurred while starting the kernel
Traceback (most recent call last):
File "/Users/saranshbakshi/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/Users/saranshbakshi/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/spyder_kernels/console/start.py", line 272, in main
import_spydercustomize()
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/spyder_kernels/console/start.py", line 32, in import_spydercustomize
import spydercustomize
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/spyder_kernels/customize/spydercustomize.py", line 25, in 
from IPython.core.getipython import get_ipython
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/__init__.py", line 48, in 
from .core.application import Application
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/core/application.py", line 25, in 
from IPython.core import release, crashhandler
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/core/crashhandler.py", line 28, in 
from IPython.core import ultratb
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/core/ultratb.py", line 124, in 
from IPython.utils import path as util_path
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/utils/path.py", line 18, in 
from IPython.utils.process import system
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/utils/process.py", line 19, in 
from ._process_posix import system, getoutput, arg_split, check_pid
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/utils/_process_posix.py", line 21, in 
import subprocess as sp
File "/Users/saranshbakshi/anaconda2/lib/python2.7/subprocess.py", line 79, in 
import pickle
File "pickle.py", line 11, in 
img1=mpimg.imread("/Users/saranshbakshi/Desktop/.jpg")
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/matplotlib/image.py", line 1357, in imread
im = pilread(fname)
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/matplotlib/image.py", line 1335, in pilread
with Image.open(fname) as image:
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/PIL/Image.py", line 2609, in open
fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '/Users/saranshbakshi/Desktop/.jpg'
Traceback (most recent call last):
File "/Users/saranshbakshi/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/Users/saranshbakshi/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/spyder_kernels/console/start.py", line 272, in main
import_spydercustomize()
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/spyder_kernels/console/start.py", line 32, in import_spydercustomize
import spydercustomize
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/spyder_kernels/customize/spydercustomize.py", line 25, in 
from IPython.core.getipython import get_ipython
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/__init__.py", line 48, in 
from .core.application import Application
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/core/application.py", line 25, in 
from IPython.core import release, crashhandler
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/core/crashhandler.py", line 28, in 
from IPython.core import ultratb
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/core/ultratb.py", line 124, in 
from IPython.utils import path as util_path
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/utils/path.py", line 18, in 
from IPython.utils.process import system
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/utils/process.py", line 19, in 
from ._process_posix import system, getoutput, arg_split, check_pid
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/utils/_process_posix.py", line 21, in 
import subprocess as sp
File "/Users/saranshbakshi/anaconda2/lib/python2.7/subprocess.py", line 79, in 
import pickle
File "pickle.py", line 11, in 
img1=mpimg.imread("/Users/saranshbakshi/Desktop/.jpg")
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/matplotlib/image.py", line 1357, in imread
im = pilread(fname)
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/matplotlib/image.py", line 1335, in pilread
with Image.open(fname) as image:
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/PIL/Image.py", line 2609, in open
fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '/Users/saranshbakshi/Desktop/.jpg'
Traceback (most recent call last):
File "/Users/saranshbakshi/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/Users/saranshbakshi/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/spyder_kernels/console/start.py", line 272, in main
import_spydercustomize()
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/spyder_kernels/console/start.py", line 32, in import_spydercustomize
import spydercustomize
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/spyder_kernels/customize/spydercustomize.py", line 25, in 
from IPython.core.getipython import get_ipython
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/__init__.py", line 48, in 
from .core.application import Application
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/core/application.py", line 25, in 
from IPython.core import release, crashhandler
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/core/crashhandler.py", line 28, in 
from IPython.core import ultratb
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/core/ultratb.py", line 124, in 
from IPython.utils import path as util_path
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/utils/path.py", line 18, in 
from IPython.utils.process import system
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/utils/process.py", line 19, in 
from ._process_posix import system, getoutput, arg_split, check_pid
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/utils/_process_posix.py", line 21, in 
import subprocess as sp
File "/Users/saranshbakshi/anaconda2/lib/python2.7/subprocess.py", line 79, in 
import pickle
File "pickle.py", line 11, in 
img1=mpimg.imread("/Users/saranshbakshi/Desktop/.jpg")
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/matplotlib/image.py", line 1357, in imread
im = pilread(fname)
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/matplotlib/image.py", line 1335, in pilread
with Image.open(fname) as image:
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/PIL/Image.py", line 2609, in open
fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '/Users/saranshbakshi/Desktop/.jpg'
Traceback (most recent call last):
File "/Users/saranshbakshi/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/Users/saranshbakshi/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/spyder_kernels/console/start.py", line 272, in main
import_spydercustomize()
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/spyder_kernels/console/start.py", line 32, in import_spydercustomize
import spydercustomize
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/spyder_kernels/customize/spydercustomize.py", line 25, in 
from IPython.core.getipython import get_ipython
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/__init__.py", line 48, in 
from .core.application import Application
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/core/application.py", line 25, in 
from IPython.core import release, crashhandler
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/core/crashhandler.py", line 28, in 
from IPython.core import ultratb
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/core/ultratb.py", line 124, in 
from IPython.utils import path as util_path
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/utils/path.py", line 18, in 
from IPython.utils.process import system
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/utils/process.py", line 19, in 
from ._process_posix import system, getoutput, arg_split, check_pid
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/utils/_process_posix.py", line 21, in 
import subprocess as sp
File "/Users/saranshbakshi/anaconda2/lib/python2.7/subprocess.py", line 79, in 
import pickle
File "pickle.py", line 11, in 
img1=mpimg.imread("/Users/saranshbakshi/Desktop/.jpg")
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/matplotlib/image.py", line 1357, in imread
im = pilread(fname)
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/matplotlib/image.py", line 1335, in pilread
with Image.open(fname) as image:
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/PIL/Image.py", line 2609, in open
fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '/Users/saranshbakshi/Desktop/.jpg'
Traceback (most recent call last):
File "/Users/saranshbakshi/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/Users/saranshbakshi/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/spyder_kernels/console/start.py", line 272, in main
import_spydercustomize()
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/spyder_kernels/console/start.py", line 32, in import_spydercustomize
import spydercustomize
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/spyder_kernels/customize/spydercustomize.py", line 25, in 
from IPython.core.getipython import get_ipython
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/__init__.py", line 48, in 
from .core.application import Application
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/core/application.py", line 25, in 
from IPython.core import release, crashhandler
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/core/crashhandler.py", line 28, in 
from IPython.core import ultratb
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/core/ultratb.py", line 124, in 
from IPython.utils import path as util_path
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/utils/path.py", line 18, in 
from IPython.utils.process import system
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/utils/process.py", line 19, in 
from ._process_posix import system, getoutput, arg_split, check_pid
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/IPython/utils/_process_posix.py", line 21, in 
import subprocess as sp
File "/Users/saranshbakshi/anaconda2/lib/python2.7/subprocess.py", line 79, in 
import pickle
File "pickle.py", line 11, in 
img1=mpimg.imread("/Users/saranshbakshi/Desktop/.jpg")
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/matplotlib/image.py", line 1357, in imread
im = pilread(fname)
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/matplotlib/image.py", line 1335, in pilread
with Image.open(fname) as image:
File "/Users/saranshbakshi/anaconda2/lib/python2.7/site‑packages/PIL/Image.py", line 2609, in open
fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '/Users/saranshbakshi/Desktop/.jpg'

**Comment by ccordoba12** [comment]
You have a file called `pickle.py`, most probably located in `/Users/saranshbakshi`, which is causing the kernel to crash because it assumes it corresponds to the Pickle module that comes with Python.

The solution is for you to locate that file and rename it.

**Comment by ccordoba12** [comment]
I'll fix this in `spyder-kernels`.
