### ISSUE TITLE
Object inspector rich text mode fails for non-ascii docstrings

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#801]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-16T15:22:46Z_

Here is a traceback if we call "raise" here: https://code.google.com/p/spyderlib/source/browse/spyderlib/plugins/inspector.py#674 Traceback (most recent call last):
  File "D:\Python\spyder\spyderlib\widgets\editor.py", line 1719, in send_to_inspector
    force_refresh=force)
  File "D:\Python\spyder\spyderlib\plugins\inspector.py", line 554, in set_rope_doc
    self.set_sphinx_text(doctxt)
  File "D:\Python\spyder\spyderlib\plugins\inspector.py", line 672, in set_sphinx_text
    html_text = sphinxify(unicode(text))
  File "D:\Python\spyder\spyderlib\utils\sphinxify.py", line 105, in sphinxify
    filed.write(docstring)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 15: ordinal not in range(128)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=801_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-16T13:22:55Z_

**Labels:** Cat-ObjectInspector

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-10-16T20:27:32Z_

I'm working on this one.

**Status:** Started  
  **Owner:** ccordoba12

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-10-16T20:52:55Z_

This issue was closed by revision cfc507c44927 .

**Status:** Fixed
