### ISSUE TITLE
Problem with kernel in spyder

### ISSUE THREAD

**Issue by jorafb** [spyder-ide/spyder#8016]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/lib/python3/dist-packages/spyder/widgets/ipythonconsole/client.py", line 561, in show_time
    elapsed_time = time() - self.t0
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spyder/widgets/ipythonconsole/client.py", line 561, in show_time
    elapsed_time = time() - self.t0
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spyder/widgets/ipythonconsole/client.py", line 561, in show_time
    elapsed_time = time() - self.t0
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
WARNING:traitlets:kernel died: 2.9995148181915283
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spyder/widgets/ipythonconsole/client.py", line 561, in show_time
    elapsed_time = time() - self.t0
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spyder/widgets/ipythonconsole/client.py", line 561, in show_time
    elapsed_time = time() - self.t0
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.6
* Qt Versions: 5.9.5, PyQt5 5.10.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.15.2 (OK)
sphinx >=0.6.6   :  1.6.7 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  0.28.5 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  5.5.0 (OK)
pylint >=0.25    :  1.8.3 (OK)

```

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.1). Please update by opening the Anaconda Prompt and running there

    conda update spyder
