### ISSUE TITLE
requirements pyqt5<5.10 and spyder-kernels<1.0 

### ISSUE THREAD

**Issue by daviddoji** [spyder-ide/spyder#8027]
## Problem Description
Updated pip list and found those two in red:
```
spyder 3.3.1 has requirement pyqt5<5.10; python_version >= "3", but you'll have pyqt5 5.11.3 which is incompatible.
spyder 3.3.1 has requirement spyder-kernels<1.0, but you'll have spyder-kernels 1.1.0 which is incompatible.
```

Coming back to:
1. pyqt5 == 5.9.2
2. spyder-kernels == 0.2.6

I could launch Spyder

### What steps reproduce the problem?

1. Update pip list
2. Uninstalling spyder-kernels-0.2.6
3. Uninstalling PyQt5-5.9.2
4. Install spyder-kernels-1.1.0
5. Install PyQt5-5.11.3

### What is the expected output? What do you see instead?

Spyder3 should start but I get the message below

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "/datos/Nextcloud/Scripts/Development/UOC_tests/venv/bin/spyder3", line 11, in <module>
    sys.exit(main())
  File "/datos/Nextcloud/Scripts/Development/UOC_tests/venv/lib/python3.7/site-packages/spyder/app/start.py", line 178, in main
    from spyder.app import mainwindow
  File "/datos/Nextcloud/Scripts/Development/UOC_tests/venv/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 51, in <module>
    requirements.check_spyder_kernels()
  File "/datos/Nextcloud/Scripts/Development/UOC_tests/venv/lib/python3.7/site-packages/spyder/requirements.py", line 66, in check_spyder_kernels
    % actual_ver)
  File "/datos/Nextcloud/Scripts/Development/UOC_tests/venv/lib/python3.7/site-packages/spyder/requirements.py", line 24, in show_warning
    raise RuntimeError(message)
RuntimeError: Please check Spyder installation requirements:
spyder-kernels < 1.0 is required (found 1.1.0).


```

## Versions

* Spyder version: 3.3.1
* Python version: 3.7
* Qt version: 5.11.2
* PyQt version: 5.11.3
* Operating System name/version: Archlinux up-to-date

### Dependencies

```

```

**Comment by hmaarrfk** [comment]
The error messages you are getting are quite explicative of what is needed:
spyder (3) requires spyder-kernel < 1.0

https://github.com/spyder-ide/spyder/blob/3.x/setup.py#L241

By going through the steps you are doing, you are forcing pip to do things that spyder doesn't want.

spyder-kernels 1.0 is for spyder 4. 

If you need Qt 5.11, then spyder won't work (at least not now).

**Comment by daviddoji** [comment]
No, I updated a bunch of outdated packages via pip. Apparently my bug report has not been clear enough.

**Comment by ccordoba12** [comment]
> pip list -o | cut -d " " -f 1 | tail -n +3 | xargs pip install -U

This is just forcing pip to install everything without respecting specific version requirements, which makes no sense, so closing.

**Comment by brahmateja143** [comment]
**I tried to launch spyder after updating to pyqt5 it is showing following error can tell me the solution**



Traceback (most recent call last):
File "/home/teja/anaconda3/bin/spyder", line 11, in 
sys.exit(main())
File "/home/teja/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 186, in main
from spyder.app import mainwindow
File "/home/teja/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 90, in 
from qtpy import QtWebEngineWidgets # analysis:ignore
File "/home/teja/anaconda3/lib/python3.7/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in 
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ValueError: PyCapsule_GetPointer called with incorrect name
