### ISSUE TITLE
Kernel failed to start 

### ISSUE THREAD

**Issue by eadonyo** [spyder-ide/spyder#8030]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

An error ocurred while starting the kernel
Traceback (most recent call last):
File "C:\Users\User\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "C:\Users\User\Anaconda2\lib\runpy.py", line 72, in _run_code
exec code in run_globals
File "C:\Users\User\Anaconda2\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\User\Anaconda2\lib\site‑packages\spyder_kernels\console\start.py", line 272, in main
import_spydercustomize()
File "C:\Users\User\Anaconda2\lib\site‑packages\spyder_kernels\console\start.py", line 32, in import_spydercustomize
import spydercustomize
File "C:\Users\User\Anaconda2\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 2, in 
fh = open("test22.txt", 'r')
IOError: [Errno 2] No such file or directory: 'test22.txt'
Traceback (most recent call last):
File "C:\Users\User\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "C:\Users\User\Anaconda2\lib\runpy.py", line 72, in _run_code
exec code in run_globals
File "C:\Users\User\Anaconda2\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\User\Anaconda2\lib\site‑packages\spyder_kernels\console\start.py", line 272, in main
import_spydercustomize()
File "C:\Users\User\Anaconda2\lib\site‑packages\spyder_kernels\console\start.py", line 32, in import_spydercustomize
import spydercustomize
File "C:\Users\User\Anaconda2\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 2, in 
fh = open("test22.txt", 'r')
IOError: [Errno 2] No such file or directory: 'test22.txt'
Traceback (most recent call last):
File "C:\Users\User\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "C:\Users\User\Anaconda2\lib\runpy.py", line 72, in _run_code
exec code in run_globals
File "C:\Users\User\Anaconda2\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\User\Anaconda2\lib\site‑packages\spyder_kernels\console\start.py", line 272, in main
import_spydercustomize()
File "C:\Users\User\Anaconda2\lib\site‑packages\spyder_kernels\console\start.py", line 32, in import_spydercustomize
import spydercustomize
File "C:\Users\User\Anaconda2\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 2, in 
fh = open("test22.txt", 'r')
IOError: [Errno 2] No such file or directory: 'test22.txt'
Traceback (most recent call last):
File "C:\Users\User\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "C:\Users\User\Anaconda2\lib\runpy.py", line 72, in _run_code
exec code in run_globals
File "C:\Users\User\Anaconda2\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\User\Anaconda2\lib\site‑packages\spyder_kernels\console\start.py", line 272, in main
import_spydercustomize()
File "C:\Users\User\Anaconda2\lib\site‑packages\spyder_kernels\console\start.py", line 32, in import_spydercustomize
import spydercustomize
File "C:\Users\User\Anaconda2\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 2, in 
fh = open("test22.txt", 'r')
IOError: [Errno 2] No such file or directory: 'test22.txt'
Traceback (most recent call last):
File "C:\Users\User\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "C:\Users\User\Anaconda2\lib\runpy.py", line 72, in _run_code
exec code in run_globals
File "C:\Users\User\Anaconda2\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\User\Anaconda2\lib\site‑packages\spyder_kernels\console\start.py", line 272, in main
import_spydercustomize()
File "C:\Users\User\Anaconda2\lib\site‑packages\spyder_kernels\console\start.py", line 32, in import_spydercustomize
import spydercustomize
File "C:\Users\User\Anaconda2\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 2, in 
fh = open("test22.txt", 'r')
IOError: [Errno 2] No such file or directory: 'test22.txt'

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Closing because of lack of response.
