### ISSUE TITLE
Spyder fails to open IPython frontend

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#805]
_From [n.eckers...@gmail.com](https://code.google.com/u/102953704161041174147/) on 2011-10-19T00:33:19Z_

This may be related to the known sip api problem. Having said problem, I read the old posts trying to figure out how to fix it. Having said that, all I needed to do (using trunk) to fix the 
{{{ValueError: API 'QString' has already been set to version 1}}}
was to disable introspection (monitor).

I can now successfully start an IPython console, but no frontend is opened, and the console output 
{{{
[IPKernelApp] To connect another client to this kernel, use:
[IPKernelApp] --existing kernel-18188.json
}}}
leaves me unable to start a frontend "manually".

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=805_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-10-20T19:25:17Z_

We haven't updated the (limited) support for the newest IPython. Its API has changed again and we have to adapt to it.

We do this after releasing 2.1

**Labels:** Cat-Console

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-21T08:11:43Z_

Could you please tell us more about your configuration:
versions of Python, PyQt, IPython...

I'm not sure to understand why it would raise an API change error when trying to open an IPython *kernel*: I need to test this with the same version of IPython as you did, which is?

Carlos, what do you mean by "its API has changed again"? (I haven't follow IPython development lately)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-10-21T08:23:06Z_

I don't know if it can be called correctly an API change. It's just that during kernel creation the ports are not written to stdout. Now they are written to a file for security reasons.

I imagine you're trying to read the ports from stdout and that's why things are not working anymore.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-22T03:17:36Z_

Actually, no I'm not parsing the stdout, I'm directly using the kernel object instance (so I guess this hasn't changed yet): https://code.google.com/p/spyderlib/source/browse/spyderlib/widgets/externalshell/monitor.py#462

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-01T00:56:52Z_

**Labels:** Component-IPython

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-01-19T05:06:56Z_

I experience the same problem but only when running Spyder 2.1.7 using PyQt4. Everything works fine with PySide. On PyQt4, the kernel appears to launch, but the associated front end fails. I get this traceback in the internal console:

Traceback (most recent call last):
  File "C:\src\spyderlib-jedludlow\spyderlib\plugins\externalconsole.py", line 790, in \<lambda>
    kernel_name=kernel_name))
  File "C:\src\spyderlib-jedludlow\spyderlib\spyder.py", line 1551, in new_ipython_frontend
    from spyderlib.plugins.ipython import IPythonPlugin
  File "C:\src\spyderlib-jedludlow\spyderlib\plugins\ipython.py", line 12, in \<module>
    from spyderlib.widgets.ipython import create_widget
  File "C:\src\spyderlib-jedludlow\spyderlib\widgets\ipython.py", line 17, in \<module>
    from IPython.frontend.qt.console.qtconsoleapp import IPythonQtConsoleApp
  File "C:\Python27\lib\site-packages\IPython\frontend\qt\console\qtconsoleapp.py", line 30, in \<module>
    from IPython.external.qt import QtCore, QtGui
  File "C:\Python27\lib\site-packages\IPython\external\qt.py", line 46, in \<module>
    prepare_pyqt4()
  File "C:\Python27\lib\site-packages\IPython\external\qt.py", line 20, in prepare_pyqt4
    sip.setapi('QString', 2)
ValueError: API 'QString' has already been set to version 1

It looks like IPython is insisting on using API version 2, but somehow API version 1 has already been specified for the interpreter in which the IPython frontend is trying to launch. I suspect since PySide only uses API version 2 there is never a conflict, and things work fine.

BTW, I'm running:
Spyder 2.1.7
Python 2.7.2
IPython 0.12
PyQt4 4.8.5
PySide 1.1.0

**Comment by spyder-issues-migrator** [comment]
_From [Salamank...@gmail.com](https://code.google.com/u/102684031691045351424/) on 2012-01-19T06:34:17Z_

Same problem with QString beeing set up to value 1

Spyder 2.1.7
Python 2.6.5
IPython 0.12
PyQt4 4.7.2

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T07:39:09Z_

This issue was closed by revision 1e065b203d3d .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T07:39:19Z_

This issue was closed by revision b47b9be148d0 .
