### ISSUE TITLE
Profiling is broken on Linux

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#806]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2011-10-19T07:53:06Z_

Spyder Version:  2.1.0rc1
Python Version:  2.7.1
Qt Version:      4.7.1, PyQt4 (API v1) 4.8.3 on Linux 

What steps will reproduce the problem?

 1.Press F10 or Run -> Profile What is the expected output? What do you see instead? Traceback (most recent call last):
  File "/home/user07/spyderlib/spyderplugins/widgets/profilergui.py", line 274, in finished
    self.show_data(justanalyzed=True)
  File "/home/user07/spyderlib/spyderplugins/widgets/profilergui.py", line 295, in show_data
    self.datatree.show_tree()
  File "/home/user07/spyderlib/spyderplugins/widgets/profilergui.py", line 384, in show_tree
    self.populate_tree(self, self.find_callees(rootKey))
  File "/home/user07/spyderlib/spyderplugins/widgets/profilergui.py", line 375, in find_callees
    return self.profdata.all_callees[parent]
KeyError: ('~', 0, '<execfile>')

Please provide any additional information below

.
It is hard for me to understand how should a root node look like.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=806_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-20T04:25:30Z_

This issue was closed by revision 12fa8d9f76ec .

**Status:** Fixed
