### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by RellRex** [spyder-ide/spyder#8083]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "H:\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 218, in headerData
    return to_qvariant(to_text_string(header, encoding=coding))
  File "H:\Anaconda2\lib\site-packages\spyder\py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb5 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "H:\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 218, in headerData
    return to_qvariant(to_text_string(header, encoding=coding))
  File "H:\Anaconda2\lib\site-packages\spyder\py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "H:\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 218, in headerData
    return to_qvariant(to_text_string(header, encoding=coding))
  File "H:\Anaconda2\lib\site-packages\spyder\py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "H:\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 218, in headerData
    return to_qvariant(to_text_string(header, encoding=coding))
  File "H:\Anaconda2\lib\site-packages\spyder\py3compat.py", line 136, in to_text_string
    return unicode(obj, encoding)
  File "H:\Anaconda2\lib\encodings\tis_620.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0xde in position 3: character maps to <undefined>
Traceback (most recent call last):
  File "H:\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 218, in headerData
    return to_qvariant(to_text_string(header, encoding=coding))
  File "H:\Anaconda2\lib\site-packages\spyder\py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd3 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "H:\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 218, in headerData
    return to_qvariant(to_text_string(header, encoding=coding))
  File "H:\Anaconda2\lib\site-packages\spyder\py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb5 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "H:\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 218, in headerData
    return to_qvariant(to_text_string(header, encoding=coding))
  File "H:\Anaconda2\lib\site-packages\spyder\py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "H:\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 218, in headerData
    return to_qvariant(to_text_string(header, encoding=coding))
  File "H:\Anaconda2\lib\site-packages\spyder\py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "H:\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 218, in headerData
    return to_qvariant(to_text_string(header, encoding=coding))
  File "H:\Anaconda2\lib\site-packages\spyder\py3compat.py", line 136, in to_text_string
    return unicode(obj, encoding)
  File "H:\Anaconda2\lib\encodings\tis_620.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0xde in position 3: character maps to <undefined>
Traceback (most recent call last):
  File "H:\Anaconda2\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 218, in headerData
    return to_qvariant(to_text_string(header, encoding=coding))
  File "H:\Anaconda2\lib\site-packages\spyder\py3compat.py", line 134, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd3 in position 0: ordinal not in range(128)

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.11.3 (OK)
sphinx >=0.6.6    :  1.6.6 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.27.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.1). Please update by opening the Anaconda Prompt and running there

    conda update spyder
