### ISSUE TITLE
Kernel died,restarting

### ISSUE THREAD

**Issue by VijayaLakshmiArthanari** [spyder-ide/spyder#8085]
### What steps will reproduce the problem?

When i am trying to debug the code, at the first line itself the kernel was died.

### Traceback
```python-traceback
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
    sys.exit(main())
    mainwindow.main()
    mainwindow = run_spyder(app, options, args)
    app.exec_()
    super(QtKernelRestarter, self).poll()
    self._fire_callbacks('restart')
    callback()
    self.kernel_restarted.emit()
    self.log.warn("kernel restarted")
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\vijv2c13136\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\external\github.py", line 252, in _http
    response = meth(req, response)
    'http', request, response, code, msg, hdrs)
    return self._call_chain(*args)
    result = func(*args)
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

Traceback (most recent call last):
  File "C:\Users\vijv2c13136\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\github\backend.py", line 140, in send_report
  File "C:\Users\vijv2c13136\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\external\github.py", line 130, in __call__
  File "C:\Users\vijv2c13136\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\external\github.py", line 266, in _http
spyder.utils.external.github.ApiError: https://api.github.com/repos/spyder-ide/spyder/issues

Traceback (most recent call last):
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users\vijv2c13136\AppData\Local\Continuum\anaconda3\Scripts\spyder-script.py", line 10, in <module>
  File "C:\Users\vijv2c13136\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\app\start.py", line 183, in main
  File "C:\Users\vijv2c13136\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3177, in main
  File "C:\Users\vijv2c13136\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3087, in run_spyder
  File "C:\Users\vijv2c13136\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\reporterror.py", line 280, in _submit_to_github
  File "C:\Users\vijv2c13136\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\widgets\github\backend.py", line 143, in send_report
Arguments: ()
```

## Versions

* Spyder version: 4.0.0b1 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
pyflakes >=0.6.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.4 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.11.0     :  0.12.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.0 (OK)
numpy >=1.7       :  1.15.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.4.0 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
pylint >=0.25     :  1.8.4 (OK)
```

**Comment by VijayaLakshmiArthanari** [comment]
Thank you! But,It will shows the jupyter qtconsole. Then how can i run my spyder code in that console.

**Comment by ccordoba12** [comment]
Are you able to run any code there?

**Comment by ccordoba12** [comment]
Sorry, that means that this is not a Spyder problem, so we can't help you here.

Unfortunately, I have no idea why this error can be happening, but you can report it here:

https://github.com/ipython/ipykernel/

**Comment by VijayaLakshmiArthanari** [comment]
Thank you for your suggestion.

**Comment by VijayaLakshmiArthanari** [comment]
I founded solution for my issue. I am running my code on windows machine. Most of the machine learning algorithms works well on ubuntu machine.So i am tried it in ubuntu and it was gave a result.
