### ISSUE TITLE
unable to start spyder 3.3.1, fedora 28, missing dependancy? solved by installing libXScrnSaver

### ISSUE THREAD

**Issue by jontis** [spyder-ide/spyder#8097]
Fedora 28
Spyder 3.3.1
Installed through conda.

Trying to run spyder chrashes on start (no graphics output at all).
$ spyder 

 Traceback (most recent call last):
  File "/home/jonathan/miniconda3/lib/python3.7/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: libXss.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jonathan/miniconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/home/jonathan/miniconda3/lib/python3.7/site-packages/spyder/app/start.py", line 190, in main
    from spyder.app import mainwindow
  File "/home/jonathan/miniconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/home/jonathan/miniconda3/lib/python3.7/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

This was solved by installing libXScrnSaver

$ sudo dnf install libXScrnSaver

**Comment by jonpovey** [comment]
Same issue on fresh desktop Gnome install of Centos 7, solved by:
`sudo yum install libXScrnSaver`
