### ISSUE TITLE
iconsole wont load

### ISSUE THREAD

**Issue by chrisreddersen** [spyder-ide/spyder#8129]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I upgraded spyder to 4, and when it threw the error i downgraded but with no success. I have since preformed a new clean install of anaconda(twice), and currently have spyder3.3 installed but the error remains. I am on a linux(mint) system. 3.1 had been working fine. ALSO, I updated qtconsole, but i get a 'kernel died, restarting..'when launching the console. when killing the process the error message is the same. 

### What steps reproduce the problem?

1. launch spyder3, either through anaconda-navigator or from the cmd line
2. launch qtconsole
3. 

### What is the expected output? What do you see instead?
Expect console to open
error message

### Paste Traceback/Error Below (if applicable)

```python-traceback


An error ocurred while starting the kernel
Traceback (most recent call last):
File "/home/chris/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/home/chris/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/main.py", line 11, in
start.main()
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 272, in main
import_spydercustomize()
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 32, in import_spydercustomize
import spydercustomize
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/customize/spydercustomize.py", line 25, in
from IPython.core.getipython import get_ipython
File "/home/chris/anaconda3/lib/python3.7/site‑packages/IPython/init.py", line 54, in
from .core.application import Application
File "/home/chris/anaconda3/lib/python3.7/site‑packages/IPython/core/application.py", line 23, in
from traitlets.config.application import Application, catch_config_error
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/init.py", line 6, in
from .application import *
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/application.py", line 19, in
from traitlets.config.configurable import Configurable, SingletonConfigurable
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/configurable.py", line 12, in
from .loader import Config, LazyConfigValue, _is_section_key
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/loader.py", line 16, in
from ipython_genutils.path import filefind
File "/home/chris/anaconda3/lib/python3.7/site‑packages/ipython_genutils/path.py", line 13, in
import random
File "/home/chris/anaconda3/lib/python3.7/random.py", line 42, in
from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: cannot import name 'log' from 'math' (/home/chris/math.py)
Traceback (most recent call last):
File "/home/chris/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/home/chris/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/main.py", line 11, in
start.main()
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 272, in main
import_spydercustomize()
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 32, in import_spydercustomize
import spydercustomize
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/customize/spydercustomize.py", line 25, in
from IPython.core.getipython import get_ipython
File "/home/chris/anaconda3/lib/python3.7/site‑packages/IPython/init.py", line 54, in
from .core.application import Application
File "/home/chris/anaconda3/lib/python3.7/site‑packages/IPython/core/application.py", line 23, in
from traitlets.config.application import Application, catch_config_error
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/init.py", line 6, in
from .application import *
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/application.py", line 19, in
from traitlets.config.configurable import Configurable, SingletonConfigurable
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/configurable.py", line 12, in
from .loader import Config, LazyConfigValue, _is_section_key
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/loader.py", line 16, in
from ipython_genutils.path import filefind
File "/home/chris/anaconda3/lib/python3.7/site‑packages/ipython_genutils/path.py", line 13, in
import random
File "/home/chris/anaconda3/lib/python3.7/random.py", line 42, in
from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: cannot import name 'log' from 'math' (/home/chris/math.py)
Traceback (most recent call last):
File "/home/chris/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/home/chris/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/main.py", line 11, in
start.main()
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 272, in main
import_spydercustomize()
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 32, in import_spydercustomize
import spydercustomize
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/customize/spydercustomize.py", line 25, in
from IPython.core.getipython import get_ipython
File "/home/chris/anaconda3/lib/python3.7/site‑packages/IPython/init.py", line 54, in
from .core.application import Application
File "/home/chris/anaconda3/lib/python3.7/site‑packages/IPython/core/application.py", line 23, in
from traitlets.config.application import Application, catch_config_error
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/init.py", line 6, in
from .application import *
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/application.py", line 19, in
from traitlets.config.configurable import Configurable, SingletonConfigurable
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/configurable.py", line 12, in
from .loader import Config, LazyConfigValue, _is_section_key
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/loader.py", line 16, in
from ipython_genutils.path import filefind
File "/home/chris/anaconda3/lib/python3.7/site‑packages/ipython_genutils/path.py", line 13, in
import random
File "/home/chris/anaconda3/lib/python3.7/random.py", line 42, in
from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: cannot import name 'log' from 'math' (/home/chris/math.py)
Traceback (most recent call last):
File "/home/chris/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/home/chris/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/main.py", line 11, in
start.main()
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 272, in main
import_spydercustomize()
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 32, in import_spydercustomize
import spydercustomize
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/customize/spydercustomize.py", line 25, in
from IPython.core.getipython import get_ipython
File "/home/chris/anaconda3/lib/python3.7/site‑packages/IPython/init.py", line 54, in
from .core.application import Application
File "/home/chris/anaconda3/lib/python3.7/site‑packages/IPython/core/application.py", line 23, in
from traitlets.config.application import Application, catch_config_error
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/init.py", line 6, in
from .application import *
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/application.py", line 19, in
from traitlets.config.configurable import Configurable, SingletonConfigurable
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/configurable.py", line 12, in
from .loader import Config, LazyConfigValue, _is_section_key
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/loader.py", line 16, in
from ipython_genutils.path import filefind
File "/home/chris/anaconda3/lib/python3.7/site‑packages/ipython_genutils/path.py", line 13, in
import random
File "/home/chris/anaconda3/lib/python3.7/random.py", line 42, in
from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: cannot import name 'log' from 'math' (/home/chris/math.py)

```

## Versions

* Spyder version: 3.3
* Python version: 3.7
* Qt version: qt-5.9.6
* PyQt version: pyqt-5.9.2
* Operating System name/version: linux mint

### Dependencies

```
PASTE DEPENDENCIES HERE
```chris@chris-MS-7823 ~ $ apt-cache depends spyder3
spyder3
  Depends: <python3:any>
    python3:i386
    python3
  Depends: python3-spyderlib
  Breaks: python3-spyderlib
  Replaces: python3-spyderlib

**Comment by ccordoba12** [comment]
> ImportError: cannot import name 'log' from 'math' (/home/chris/math.py)

This is the problem: you have a file called `math.py` in your home and that creates a conflict with the `math` library that comes with Python.

Simply renaming or removing that file will fix the error.

**Comment by chrisreddersen** [comment]
embarrassingly simple. This worked. wont make that mistake again. thank you
