### ISSUE TITLE
When multiple files are open, close-clicking one file closes two files

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#813]
_From [christ...@prinoth.name](https://code.google.com/u/105811080570817470869/) on 2011-10-24T04:46:06Z_

What steps will reproduce the problem?

 1. Open multiple files in the editor
2. click the "x" icon in the tab list to close a single file
3. the "right-adjacent" file is closed as well What is the expected output? What do you see instead? I expect only the select file to close ;) What version of the product are you using? On what operating system? Spyder 2.1.0rc1, Python 2.6.1, Qt 4.7.2, PyQt4 (API v1) 4.8.3 on Darwin 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=813_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-24T03:05:22Z_

I can't reproduce this on Windows, nor on Linux. 

Is it easily reproducible?

Is it happening when closing tabs with the following methods?
1. Shortcut Ctrl+F4
2. Shortcut Ctrl+W
3. Right-click on tab > Close
If it's not happening in all those cases, it can only mean that either you are a frenetic clicker ;-) (you are clicking two times instead of once, hence closing the current file and the file at its right) or that's a PyQt bug.

**Comment by spyder-issues-migrator** [comment]
_From [christ...@prinoth.name](https://code.google.com/u/105811080570817470869/) on 2011-10-24T03:15:52Z_

Sorry for the hasty bug submission, but apparently the problem went away
killing and restarting spyder. I am not sure what happened, but works fine
now.

Again, sorry
Christian

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-24T03:18:59Z_

No problem.

**Status:** Invalid

**Comment by spyder-issues-migrator** [comment]
_From [christ...@prinoth.name](https://code.google.com/u/105811080570817470869/) on 2011-10-25T05:45:22Z_

Hi, just wanted to give you an update, since the issue represents itself at
irregular intervals. I have not yet been able to figure it out, but
"sometimes" closing one tab close another one as well.
I will try to install another app that uses pyqt to see if that's the
culprit.

Cheers

\-- 
Christian Prinoth

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG/MacGPG2 v2.0.17 (Darwin)
Comment: GPGTools - http://gpgtools.org mQENBE5p7L4BCADE1w1iBGAyutyi80A3AfzjXb2BuYGuvu/WPBVFzWtI5lNb5d0I
M9UrddNrNGWdVrhH3IraKHxKkOJIg/APcQ1GsgqDBsMEv18BQWOL19ItAHbaQgCl
aOXPT9BaHr168/N0zE3JwUYlThJhQCvPE9tM9zkJuqHzpHI0U6MHnJ7CxvVPCoSi
iiF14qHGG76rsgwxshFz+4EZ2cYqEPx909AARJQnAfFwp3x/4SqH7ECdQK9bPCB/
5gGUt+1yEIQ40KzJH1KNqTa4fK5Nn+1yEQShkjjTaKzCiTQnc2ekEihiCFVrdPJJ
4ihblbOFnWgeqif/x0i+H2ibna3t3f/y2w7NABEBAAG0KkNocmlzdGlhbiBQcmlu
b3RoIDxjaHJpc3RpYW5AcHJpbm90aC5uYW1lPokBOAQTAQIAIgUCTmnvhAIbLwYL
CQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQPC08J9vIDo2V3wf8DZzSHR0CcRu8
+Br8Qhwy2FBaAmH4Oueqy78y7S87+Lu17X3iBWZwRomWx1jSmuU1cJ8BOs/T8EMp
xbgx6NHnRHpunEws7QPFtiSzeHmiMgp6WMdbpSAOOGmJahJqVAJt7SDPpwLXgXkA
L2cHIis8yYJsR1CvTqNgJGNoyQ1QzxOBnW3ynLDtZOVTvV6irGPJWXjUYGIvylxa
Z4d2yTkUiV11akoWHHQC5MMyUOPNlDutvNL9L4NVtOXkZafwBIr8n3PaeoBgRhcp
1fGwhaf+qR59KqAwugNw2fRal79/Vp1LLYRcqH5G8cIti1pCkKEfK/BfAmmcVEoa
PzrzQMbRTrQxQ2hyaXN0aWFuIFByaW5vdGggPGMucHJpbm90aEBxdWFlc3Rpb2Nh
cGl0YWwuY29tPokBOwQTAQIAJQIbLwYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AF
Ak5p8HoCGQEACgkQPC08J9vIDo39XAgAgv5BiQnqxGsamr/7s6j4uvtZJn1zRgqP
6kIQc78uWv2SWPgIyyGNuzpuxnjwXuONQbk0CyPteqZaW5UP78TvKnuZy0cvLidH
jzJ/kw+K9Np2nL7ezfgwjbNSQhIauyp1gqa5EAmWC5DeO4vpOc1lcup8MGiGkf2w
89CVjx8e+rIkbV6MDjDu7elw35ns5E3+dIzjxROoWBPEvrIVcXx2J3kW0QtYYRvx
DOtdjCukmCChD/D+yTh3/on00SDvhFJubYWGurTkMPD74hOL7XcrTsaV0nPly91e
ta7EPsGv1y1RVHBZpDDv0PZ/rogsHeKQZ26IQQC5bWSvImn6foeW67kBDQROaey+
AQgA2wKCdS6bWrDw4c5ohXUXSZCKf8HQPPYcOgh9zO9y1sSW04Z5MwSaTZyM9x+x
FK1lkcieSJ0hQre4YaApQw2zrFfnhdSr3209t7fZghJDAplo+fAbpAr/js5GtXqr
UQ5pvcfj1X2TUyyFH/sIuK94TzEmDJb7G3B1lpT9b+hKlKlHgbD/YmobM+r/+63g
++XkTA8lW1dvsCJlFq3YIJiFX3Cr7qvzgZ3bAaQQgoveoJGeOYjdKWzr3O+Qz6a0
Q8JaLNyn3fXdgjpU/xfWWVEGVjoald89Owp0/jqB6jYI4c1WP6SDr8TKlJB/EW6S
dFRJKe/AvzSCT0GzBuLh8uZoSwARAQABiQJEBBgBAgAPAhsuBQJOae30BQkSz/i2
ASnAXSAEGQECAAYFAk5p7L4ACgkQ2ShSn21Z3FBTzAgA2pXFuJf6E6L+9WzVUKBo
SYxIf22nNB/dvRLkZsmkcjY5VfIRgE9ZU5eHt3Ynp8g95rNWnbhMNHsX984m6+Ot
mvm1Fh3LGq2vbIWYdHi+dB1R/YAvt6vv4agC/3jDuENGE932PGLFEawX3xXUGE1I
U/d6juqq6n7wOFBXIFcZq10kVm5ofzdCvmxpdrHtURzlqT8hOw63qplz+jmpOM5+
lQ1TipBuYtgOCTR6Rv5PggT/L+h44yOr9SDDbPIn7NqHGVp6KdtLz5qFoUVNjSmM
K0ZsXjm6+kvYM5inQgnXbsMCqnGrMnk1+3oyeHN1IKZ3o09x9xCT7roPenQgJAJa
EAkQPC08J9vIDo370AgAtC06/qVvMapEgwLJnsJo0FyaE7obDXHp1F4AABK4VS5S
xaUukE8il1EPqgVphda9VTQd3YMNvSd2DP7a/629n9JbxxQ4pp0iuYR7qJX/bZLM
T3esuO0bmQNcJ+U7DHCcw+6MIY5NESXYW5XFJ23niB9jsoK9edEQ4EPqzDd/WN9c
dTd5DRBQoaXmQR42XRQcy/DffMbsTAcNpeFZyHMh94k2Dajm5xPI5MrSXNM6MZUB
yPAVE/ohKYd9IZT6qryaKwkOdDzui4PBL3HL0mutH6cwdnXr4l1jE+34aXNq8y4j
nLTEaduhZs6CTPgdxRLyfyu8puTdfAhgjIxS//9/dg==
=br0S
-----END PGP PUBLIC KEY BLOCK-----

**Comment by spyder-issues-migrator** [comment]
_From [lecomte....@gmail.com](https://code.google.com/u/106842762804833487475/) on 2012-01-10T04:46:18Z_

Hi! I am using Spyder on MacOSX, installed with 'pip install spyder', and I suffer from the very same problem, which is highly annoying.

I am currently running version 2.1.6, but I remember that I also had the problem with previous versions.
Spyder is running against PyQt 4.9 and Qt 4.8.0 installed with Homebrew.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-01-15T00:51:21Z_

Carlos, would you be able to reproduce this bug on MacOSX?

**Labels:** OpSys-OSX

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-01-15T00:52:29Z_

Is it happening only for the editor tabs or is it happening with the console tabs too?

**Status:** Accepted  
  **Labels:** -Priority-Medium Priority-High

**Comment by spyder-issues-migrator** [comment]
_From [Potdevin...@gmail.com](https://code.google.com/u/105305097468848868443/) on 2012-02-06T06:23:06Z_

I suffer from the same bug, but only with the editor tabs, not the console one. 

To be more precise, when either by clicking on the tab cross, or using the dedicated shortcut, the tab as well as the one directly to the right of it gets closed. When clicking on the rightmost tab, only one tab is closed as expected. 

From what I could see, the bug is dependent on the use of pyqt or pyside:
if I use the bootstrap startup script using

python bootstrap --gui=pyqt
then the bug occurs. with
python bootstrap --gui=pyside
then only one tab is closed, but funnily, the editor switches to the tab next/next to the one which was closed. That means, if I closed tab n, then what was tab n+2 gets opened, but with tab n+1 still there.

Hope this helps

spyder 2.1.7 on a Mac Os system

**Comment by spyder-issues-migrator** [comment]
_From [andreas....@gmail.com](https://code.google.com/u/106271308227181205074/) on 2012-02-08T06:07:05Z_

When closing the rightmost editor tab, only this one is closed, but the internal console shows:

\>>> Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/plugins/editor.py", line 1060, in close_file_in_all_editorstacks
    editorstack.close_file(index, force=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/editor.py", line 1196, in close_file
    finfo = self.data[index]
IndexError: list index out of range

My environment:
Spyder 2.1.7, Python 2.7.2, Qt 4.7.4, PyQt4 (API v1) 4.9 on Darwin

**Comment by spyder-issues-migrator** [comment]
_From [r.lup...@gmail.com](https://code.google.com/u/105767089042807008718/) on 2012-04-07T04:46:49Z_

I have seen the same bug on OS X using the latest 2.2.0dev, and I think I have found the problem.

When the file is closed in the editorstack, it sends a file_closed(int,int) signal which is connected to close_file_in_all_editorstacks in the EditorPlugin. The first argument is the id() of the editorstack, but the value that is received by close_file_in_all_editorstacks is different, and so it asks the original editorstack to close the same index again -- closing the next file, or giving the IndexError if not enough files remain.

I think this might be a 64bit issue, where the id (which is the memory address) is too big for an int. Changing the file_closed signal to file_closed(long,long) solves the problem.

I don't know much about Mercurial, but here is the result of "hg diff". Is this the best way of giving a patch?


=================================

diff -r 6f33167046c7 spyderlib/plugins/editor.py
--- a/spyderlib/plugins/editor.py	Sat Apr 07 10:05:01 2012 +0200
+++ b/spyderlib/plugins/editor.py	Sat Apr 07 12:41:45 2012 +0100
@@ -1005,7 +1005,7 @@
         self.connect(self, SIGNAL('editor_focus_changed()'),
                      self.main.plugin_focus_changed)
         
-        self.connect(editorstack, SIGNAL('close_file(int,int)'),
+        self.connect(editorstack, SIGNAL('close_file(long,long)'),
                      self.close_file_in_all_editorstacks)
         self.connect(editorstack, SIGNAL('file_saved(int,int)'),
                      self.file_saved_in_editorstack)
diff -r 6f33167046c7 spyderlib/widgets/editor.py
--- a/spyderlib/widgets/editor.py	Sat Apr 07 10:05:01 2012 +0200
+++ b/spyderlib/widgets/editor.py	Sat Apr 07 12:41:45 2012 +0100
@@ -1209,7 +1209,7 @@
                 self.outlineexplorer.remove_editor(finfo.editor)
             
             self.remove_from_data(index)
-            self.emit(SIGNAL('close_file(int,int)'), id(self), index)
+            self.emit(SIGNAL('close_file(long,long)'), id(self), index)
             if not self.data and self.is_closable:
                 \# editortabwidget is empty: removing it
                 \# (if it's not the first editortabwidget)
@@ -2346,7 +2346,7 @@
         font = QFont("Courier New")
         font.setPointSize(10)
         editorstack.set_default_font(font, color_scheme='Spyder')
-        self.connect(editorstack, SIGNAL('close_file(int,int)'),
+        self.connect(editorstack, SIGNAL('close_file(long,long)'),
                      self.close_file_in_all_editorstacks)
         self.connect(editorstack, SIGNAL("create_new_window()"),
                      self.create_new_window)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-07T06:16:25Z_

Thanks very much for your help on this matter!

I also fixed the 'file_saved' signal for the same reason.

The easiest way to contribute is to attach a .patch file directly.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-07T06:17:02Z_

This issue was updated by revision 466e2f7679e9 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-07T06:18:43Z_

This issue was updated by revision 29b7e270e1a1 .

**Comment by spyder-issues-migrator** [comment]
_From [lecomte....@gmail.com](https://code.google.com/u/106842762804833487475/) on 2012-04-11T02:11:00Z_

I have checked out Spyder's code from the trunk and indeed the problem is solved. Thank you very much !

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-21T00:05:03Z_

issue #1000 has been merged into this issue.
