### ISSUE TITLE
Kernel error ZMQError

### ISSUE THREAD

**Issue by slaxys** [spyder-ide/spyder#8230]
### What steps reproduce the problem?

Launching spyder from anaconda prompt or spyder shortcut, I get this kernel error.  I have already tried to uninstall/reinstall, run in administrator, turn off all anti-virus and firewalls, along with all the approaches on the troubleshooting but still no idea where to start.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
File "C:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 284, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Anaconda3\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 469, in initialize
self.init_sockets()
File "C:\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 233, in init_sockets
context = zmq.Context.instance()
File "C:\Anaconda3\lib\site‑packages\zmq\sugar\context.py", line 108, in instance
cls._instance = cls(io_threads=io_threads)
File "zmq/backend/cython/context.pyx", line 49, in zmq.backend.cython.context.Context.__cinit__
zmq.error.ZMQError: Permission denied

```

## Versions

* Spyder version: 3.3.1
* Python version: 3.7.0 32bits
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 7

### Dependencies

```
IPython >=4.0     :  6.5.0 (OK)
cython >=0.21     :  0.28.5 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
numpy >=1.7       :  1.15.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  2.1.1 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
sympy >=0.7.3     :  1.2 (OK)

```

**Comment by ccordoba12** [comment]
This could be caused by your firewall and/or antivirus. Please disable them and try again.

**Comment by bcolsen** [comment]
You could try down grading python to 3.6

**Comment by ccordoba12** [comment]
Is the Jupyter notebook working for you?
