### ISSUE TITLE
Spyder fails with: "ValueError: numpy.ufunc has the wrong size, try recompiling"

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#827]
_From [martinzi...@gmail.com](https://code.google.com/u/111935897003828349007/) on 2011-11-07T09:17:46Z_

I am unable to install and run spyder 2.0.12 or 2.1.1 on my Mac OS X 10.7 (Lion) due to the error above, from both MacPorts and a download form this site.

I would be very grateful if someone could help out - I am missing spyder!

Thanks, 

Martin.

More details:

I have installed all the dependencies of py27-spyder (and py27-spyder-beta) using MacPorts. I've used spotlight search to try to indentify any alternative builds of numpy, but only see the py27-numpy 1.6.1 installed from macports. (I've also verified that I am able to use numpy and matplotlib functions from the install).

If I then try to install py27-spyder or py27-spyder-beta from MacPorts (using 'sudo port install py27-spyder-beta') it fails like this (full log file attached). 

:info:destroot   File "/Library/Python/2.7/site-packages/scipy-0.10.0.dev_20110723-py2.7-macosx-10.7-x86_64.egg/scipy/io/matlab/mio4.py", line 15, in \<module>
:info:destroot     from mio_utils import squeeze_element, chars_to_strings
:info:destroot   File "numpy.pxd", line 849, in init scipy.io.matlab.mio_utils (scipy/io/matlab/mio_utils.c:3468)
:info:destroot ValueError: numpy.ufunc has the wrong size, try recompiling

If I download spyder-2.1.1.zip from this site, and install using 'sudo python setup.py install', the install completes, but then it fails to start with the same error:

MZOffice:spyder-2.1.1 martin$ spyder
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/spyder", line 2, in \<module>
    from spyderlib import spyder
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 60, in \<module>
    from spyderlib.plugins.inspector import ObjectInspector
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/plugins/inspector.py", line 30, in \<module>
    from spyderlib.widgets.externalshell.pythonshell import ExtPythonShellWidget
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/externalshell/pythonshell.py", line 27, in \<module>
    from spyderlib.widgets.externalshell.namespacebrowser import NamespaceBrowser
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/externalshell/namespacebrowser.py", line 31, in \<module>
    from spyderlib.utils.iofuncs import iofunctions
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/utils/iofuncs.py", line 26, in \<module>
    import scipy.io as spio
  File "/Library/Python/2.7/site-packages/scipy-0.10.0.dev_20110723-py2.7-macosx-10.7-x86_64.egg/scipy/io/__init__.py", line 11, in \<module>
    from matlab import loadmat, savemat, byteordercodes
  File "/Library/Python/2.7/site-packages/scipy-0.10.0.dev_20110723-py2.7-macosx-10.7-x86_64.egg/scipy/io/matlab/__init__.py", line 11, in \<module>
    from mio import loadmat, savemat
  File "/Library/Python/2.7/site-packages/scipy-0.10.0.dev_20110723-py2.7-macosx-10.7-x86_64.egg/scipy/io/matlab/mio.py", line 15, in \<module>
    from mio4 import MatFile4Reader, MatFile4Writer
  File "/Library/Python/2.7/site-packages/scipy-0.10.0.dev_20110723-py2.7-macosx-10.7-x86_64.egg/scipy/io/matlab/mio4.py", line 15, in \<module>
    from mio_utils import squeeze_element, chars_to_strings
  File "numpy.pxd", line 849, in init scipy.io.matlab.mio_utils (scipy/io/matlab/mio_utils.c:3468)
ValueError: numpy.ufunc has the wrong size, try recompiling

**Attachment:** [log.txt](http://code.google.com/p/spyderlib/issues/detail?id=827)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=827_

**Comment by spyder-issues-migrator** [comment]
_From [martinzi...@gmail.com](https://code.google.com/u/111935897003828349007/) on 2011-11-07T10:36:09Z_

Sorry -I  found the issue. Somehow there was an old scipy dev build on my system that was interfering (see where the message is actually coming from):

File "/Library/Python/2.7/site-packages/scipy-0.10.0.dev_20110723-py2.7-macosx-10.7-x86_64.egg/scipy/io/matlab/mio4.py", line 15, in \<module>

I deleted the egg, uninstalled and reinstalled scipy before rebuilding spyder, and all is now well. This can be closed.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-11-08T09:46:33Z_

Hi Martin,

I thought you had a problem like that. I'm glad you fixed it quickly. If you need any other help, don't hesitate to open an issue or leave a message in our mailing list.

Cheers,
Carlos

**Status:** WontFix

**Comment by spyder-issues-migrator** [comment]
_From [fhe...@gmail.com](https://code.google.com/u/111731474599148743921/) on 2011-11-10T05:05:43Z_

I think we may add this information somewhere more appropriate and visible? maybe an 'Install issues' section or something?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-11-10T05:12:37Z_

This should be mentioned in SciPy installation notes, not in Spyder's. Not that I don't think it's important to install SciPy in conjunction with Spyder but we can't handle this kind of troubleshooting: we simply don't have the manpower. 

Anyway thanks for keeping us informed of this.
