### ISSUE TITLE
Unicode decode error (user name / windows)

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#828]
_From [philippe...@gmail.com](https://code.google.com/u/116766910402148161239/) on 2011-11-08T07:40:57Z_

What steps will reproduce the problem?

 I installed spyder 2.1.1 on windows 7
The user name is "françois"

Spyder does not start and stops with this traceback:

C:\Python27\Scripts>spyder
Traceback (most recent call last):
  File "C:\Python27\Scripts\spyder", line 2, in \<module>
    from spyderlib import spyder
  File "c:\Python27\lib\site-packages\spyderlib\spyder.py", line 99, in \<module>

    from spyderlib.plugins.editor import Editor
  File "c:\Python27\lib\site-packages\spyderlib\plugins\editor.py", line 36, in
\<module>
    from spyderlib.widgets.editor import (ReadWriteStatus, EncodingStatus,
  File "c:\Python27\lib\site-packages\spyderlib\widgets\editor.py", line 29, in
\<module>
    from spyderlib.utils.module_completion import moduleCompletion
  File "c:\Python27\lib\site-packages\spyderlib\utils\module_completion.py", lin
e 31, in \<module>
    db = PickleShareDB(MODULES_PATH)
  File "c:\Python27\lib\site-packages\spyderlib\utils\external\pickleshare.py",
line 52, in __init__
    self.root = Path(root).expanduser().abspath()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 13: ordinal
 not in range(128)

The problem is probably the user name with a "ç"

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=828_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-11-08T09:49:37Z_

Hi,

We are aware of this problem. It's very annoying. We are trying to fix at the issue you'll be redirected.

I'll try to come up with a solution by the end of a week. Thanks for your interest in Spyder.

Cheers,
Carlos

**Status:** Duplicate  
  **Mergedinto:** 812
