### ISSUE TITLE
Fail to start conda-forge-installed spyder

### ISSUE THREAD

**Issue by SylvainCorlay** [spyder-ide/spyder#8316]
I am unable to launch spyder after a fresh install on OS X.

```
Traceback (most recent call last):
  File "/Users/scorlay/miniconda3/bin/spyder", line 7, in <module>
    from spyder.app.start import main
  File "/Users/scorlay/miniconda3/lib/python3.6/site-packages/spyder/app/start.py", line 12, in <module>
    import zmq
  File "/Users/scorlay/miniconda3/lib/python3.6/site-packages/zmq/__init__.py", line 42, in <module>
    _load_libzmq()
  File "/Users/scorlay/miniconda3/lib/python3.6/site-packages/zmq/__init__.py", line 13, in _load_libzmq
    PYPY = platform.python_implementation().lower() == 'pypy'
  File "/Users/scorlay/miniconda3/lib/python3.6/platform.py", line 1234, in python_implementation
    return _sys_version()[0]
  File "/Users/scorlay/miniconda3/lib/python3.6/platform.py", line 1192, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:14:23) \n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]'
```

The installed versions from conda-forge:

```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    lazy-object-proxy-1.3.1    |   py36h470a237_0          29 KB  conda-forge
    qt-5.6.2                   |       hd4c90f3_9        35.2 MB  conda-forge
    sip-4.18.1                 |   py36hfc679d8_0         242 KB  conda-forge
    astroid-2.1.0              |        py36_1000         256 KB  conda-forge
    rope-0.10.7                |             py_1         113 KB  conda-forge
    pyflakes-2.0.0             |             py_0          41 KB  conda-forge
    pycodestyle-2.4.0          |             py_1          34 KB  conda-forge
    mccabe-0.6.1               |             py_1           8 KB  conda-forge
    keyring-16.1.0             |        py36_1000          47 KB  conda-forge
    isort-4.3.4                |        py36_1000          58 KB  conda-forge
    qtconsole-4.4.3            |             py_0          81 KB  conda-forge
    qtpy-1.5.2                 |     pyh8a2030e_0          29 KB  conda-forge
    typed-ast-1.1.0            |   py36h470a237_0         209 KB  conda-forge
    spyder-kernels-0.2.6       |             py_1          37 KB  conda-forge
    numpydoc-0.8.0             |             py_1          21 KB  conda-forge
    wrapt-1.10.11              |   py36h470a237_1          42 KB  conda-forge
    spyder-3.3.2               |        py36_1000         2.5 MB  conda-forge
    pyqt-5.6.0                 |   py36h8210e8a_7         4.2 MB  conda-forge
    pylint-2.2.0               |        py36_1000         812 KB  conda-forge
    qtawesome-0.5.3            |     pyh8a2030e_0         591 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        44.4 MB

The following NEW packages will be INSTALLED:

    astroid:           2.1.0-py36_1000        conda-forge
    isort:             4.3.4-py36_1000        conda-forge
    keyring:           16.1.0-py36_1000       conda-forge
    lazy-object-proxy: 1.3.1-py36h470a237_0   conda-forge
    mccabe:            0.6.1-py_1             conda-forge
    numpydoc:          0.8.0-py_1             conda-forge
    pycodestyle:       2.4.0-py_1             conda-forge
    pyflakes:          2.0.0-py_0             conda-forge
    pylint:            2.2.0-py36_1000        conda-forge
    pyqt:              5.6.0-py36h8210e8a_7   conda-forge
    qt:                5.6.2-hd4c90f3_9       conda-forge
    qtawesome:         0.5.3-pyh8a2030e_0     conda-forge
    qtconsole:         4.4.3-py_0             conda-forge
    qtpy:              1.5.2-pyh8a2030e_0     conda-forge
    rope:              0.10.7-py_1            conda-forge
    sip:               4.18.1-py36hfc679d8_0  conda-forge
    spyder:            3.3.2-py36_1000        conda-forge
    spyder-kernels:    0.2.6-py_1             conda-forge
    typed-ast:         1.1.0-py36h470a237_0   conda-forge
    wrapt:             1.10.11-py36h470a237_1 conda-forge

Proceed ([y]/n)? y
```

**Comment by ccordoba12** [comment]
This requires https://github.com/conda-forge/qt-feedstock/pull/82 and https://github.com/conda-forge/spyder-feedstock/pull/47

Once they are merged, I'll let you know so you can test things again.

**Comment by pgunn** [comment]
@SylvainCorlay 

ccordoba12's upstream fixes worked for me - might want to give it another look

**Comment by ccordoba12** [comment]
Closing for now because there's evidence things are working again now.
