### ISSUE TITLE
Crash at launching

### ISSUE THREAD

**Issue by JmiXIII** [spyder-ide/spyder#8319]
### Issue Report Checklist

* [ X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1.  launch from git clone current master 
2. python bootstrap.py
3. 

### What is the expected output? What do you see instead?
previous build were launching correctly

c:\spyder\spyder (master -> origin)
λ python bootstrap.py
Executing Spyder from source checkout
Revision bc6d741, Branch: master
01. Patched sys.path with c:\spyder\spyder
02. PyQt5 is detected, selecting
03. Imported Spyder 4.0.0.dev0
    [Python 3.6.5 64bits, Qt 5.11.2, PyQt5 5.11.3 on Windows]
04. Running Spyder
Bootstrap completed in 00:00:02.3202
Traceback (most recent call last):
  File "c:\spyder\spyder\spyder\app\mainwindow.py", line 3347, in main
    mainwindow = run_spyder(app, options, args)
  File "c:\spyder\spyder\spyder\app\mainwindow.py", line 3196, in run_spyder
    main.setup()
  File "c:\spyder\spyder\spyder\app\mainwindow.py", line 845, in setup
    message=_("Spyder Internal Console\n\n"
  File "c:\spyder\spyder\spyder\plugins\console\plugin.py", line 79, in __init__
    self.find_widget = FindReplace(self)
  File "c:\spyder\spyder\spyder\widgets\findreplace.py", line 100, in __init__
    self.re_button = create_toolbutton(self, icon=ima.icon('regex'),
  File "c:\spyder\spyder\spyder\utils\icon_manager.py", line 300, in icon
    return qta.icon(*args, **kwargs)
  File "C:\Users\user11.HPO-SAMAT\AppData\Local\Continuum\Anaconda3\lib\site-packages\qtawesome\__init__.py", line 125, in icon
    return _instance().icon(*names, **kwargs)
  File "C:\Users\user11.HPO-SAMAT\AppData\Local\Continuum\Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 261, in icon
    names[i]))
  File "C:\Users\user11.HPO-SAMAT\AppData\Local\Continuum\Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 308, in _parse_options
    prefix, chars = self._get_prefix_chars(names)
  File "C:\Users\user11.HPO-SAMAT\AppData\Local\Continuum\Anaconda3\lib\site-packages\qtawesome\iconic_font.py", line 342, in _get_prefix_chars
    raise Exception(error)
Exception: Invalid font prefix "mdi"

**Comment by ccordoba12** [comment]
You need to update QtAwesome to `0.5+` to fix that. It's already mentioned in our setup.py.
