### ISSUE TITLE
qtawsome 0.5.0 requirements is not high enough for master

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#8330]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Spyder doesn't start on latest master with QtAwesome 0.5.0 or 0.5.1. Updating QtAwesome solve the problem.

### What steps reproduce the problem?

1. Try to start Spyder with QtAwesome 0.5.0 or 0.5.1 

### Paste Traceback/Error Below (if applicable)

```python-traceback
Traceback (most recent call last):
  File "C:\Users\User\spyder\spyder\app\mainwindow.py", line 3355, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\User\spyder\spyder\app\mainwindow.py", line 3204, in run_spyder
    main.setup()
  File "C:\Users\User\spyder\spyder\app\mainwindow.py", line 853, in setup
    message=_("Spyder Internal Console\n\n"
  File "C:\Users\User\spyder\spyder\plugins\console\plugin.py", line 79, in __init__
    self.find_widget = FindReplace(self)
  File "C:\Users\User\spyder\spyder\widgets\findreplace.py", line 107, in __init__
    "format_letter_case"),
  File "C:\Users\User\spyder\spyder\utils\icon_manager.py", line 300, in icon
    return qta.icon(*args, **kwargs)
  File "C:\Anaconda3\envs\Spyder\lib\site-packages\qtawesome\__init__.py", line 145, in icon
    return _instance().icon(*names, **kwargs)
  File "C:\Anaconda3\envs\Spyder\lib\site-packages\qtawesome\iconic_font.py", line 269, in icon
    names[i]))
  File "C:\Anaconda3\envs\Spyder\lib\site-packages\qtawesome\iconic_font.py", line 316, in _parse_options
    prefix, chars = self._get_prefix_chars(names)
  File "C:\Anaconda3\envs\Spyder\lib\site-packages\qtawesome\iconic_font.py", line 347, in _get_prefix_chars
    raise Exception(error)
Exception: Invalid icon name "format-letter-case" in font "mdi"
```

## Versions

* Spyder version: Spyder 4.0.0.dev0 
* Python version: Python 3.6.6 64-bit
* Qt version: Qt 5.9.4
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
pygments >=2.0    :  2.2.0 (OK)
qdarkstyle >=2.6.4:  2.6.4 (OK)
sphinx >=0.6.6    :  1.8.1 (OK)
pyls >=0.19.0     :  0.19.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.5.0.dev0 (OK)
IPython >=4.0     :  7.0.1 (OK)
matplotlib >=2.0.0:  3.0.1 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by jnsebgosselin** [comment]
It works with 0.5.2.

So yes, we need to demand >=0.5.2

**Comment by ccordoba12** [comment]
Thanks!

**Comment by ccordoba12** [comment]
@juanis2112, an easy one for you: Please change this condition in our setup.py, Readme and requirement files.
