### ISSUE TITLE
"Open Interpreter" command causes windows python.exe error

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#835]
_From [vgrin...@gmail.com](https://code.google.com/u/116158211225176796421/) on 2011-11-13T22:09:25Z_

What steps will reproduce the problem?

 1.Run Spyder as normal
2.Open Interpreter (automatically on start-up or manually) What is the expected output? What do you see instead? Expect for console/interpreter to run error-free.  Instead, a Windows popup comes up saying: 
"python.exe has encountered a problem and needs to close.  We are sorry for the inconvenience." What version of the product are you using? On what operating system? Spyderlib 2.1.1 with Python 2.5.4, installed from spyder-2.1.1_py25.exe on Windows XP SP3 

Please provide any additional information below

. While in debug mode, I typed some commands into the console and got the following trace...

Microsoft Windows XP [Version 5.1.2600]
(C) Copyright 1985-2001 Microsoft Corp.

L:\>c:

C:\>cd python25\scripts

C:\Python25\Scripts>spyder -d
Start of MainWindow constructor
Initializing...
End of MainWindow constructor
*** Start of MainWindow setup ***
Loading object inspector...
Loading outline explorer...
Loading editor...
Loading file explorer...
Loading history plugin...
Loading online help...
Loading project explorer...
Loading external console...
Loading namespace browser...
Setting up main window...
Setting up window...
*** End of MainWindow setup ***
Traceback (most recent call last):
  File "C:\Python25\lib\site-packages\spyderlib\widgets\externalshell\pythonshel
l.py", line 522, in send_to_process
    "toggle_inputhook_flag(True)")
  File "C:\Python25\lib\site-packages\spyderlib\utils\bsdsocket.py", line 52, in
 communicate
    write_packet(sock, command)
  File "C:\Python25\lib\site-packages\spyderlib\utils\bsdsocket.py", line 20, in
 write_packet
    sock.send(struct.pack("l", len(sent_data)) + sent_data)
AttributeError: 'NoneType' object has no attribute 'send'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=835_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-11-14T05:00:52Z_

Thanks for reporting this bug. 
Just a preliminary note: the traceback with the AttributeError exception is unfortunately irrelevant (it simply means that the interpreter is shutting down but does not help to understand why). 

To better understand where this is coming from:
1. Is this a new installation of Spyder or an upgrade? If this is an upgrade, I suppose that this bug was not present in the previous version? (which version?)
2. Could you please to try and disable all the options of the console and see of this fixes this bug? (Preferences > Console > disable the monitor, the Matplotlib patch and all other options that are tweaking the interpreter)

**Comment by spyder-issues-migrator** [comment]
_From [vgrin...@gmail.com](https://code.google.com/u/116158211225176796421/) on 2011-11-14T17:57:03Z_

This is a new installation of Spyder - I'm looking for a better Python IDE and this one is really close.

There seem to be two possible causes:
1. When introspection monitor in console is clicked on, it gives me the python.exe error as well as the warning below.

warning: Not importing directory 'C:\Python25\lib\site-packages\spyderlib\locale': missing __init__.py

2. The bigger issue seems to be coming from the "External Modules" tab in Console.  

When the Matplotlib patch is checked, I get the same error as described before.

Thanks for your help! Please let me know if you need more diagnostics.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-11-15T00:51:06Z_

1. This warning message is really nothing (we are importing the standard module 'locale' and Python tries to import the folder 'locale' which contains translations but then it really imports the module 'locale').

2. So everything works if you uncheck the Matplotlib patch?

**Comment by spyder-issues-migrator** [comment]
_From [vgrin...@gmail.com](https://code.google.com/u/116158211225176796421/) on 2011-11-15T04:46:29Z_

1. To make everything work, I need to uncheck Matplotlib patch AND the introspection monitor.

2.  If I don't uncheck either one of these, I see the "python.exe has encountered a problem and needs to close" pop-up message, and the console will not work.

3. The warning message also  just happened to pop-up and I thought it was worth mentioning. Sorry for the confusion!

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-11-20T22:22:56Z_

**Summary:** "Open Interpreter" command causes windows python.exe error  
  **Labels:** Cat-Console OpSys-Windows

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-23T13:19:25Z_

This is too old now. If you have the same problem, please open a new issue.

**Status:** WontFix
