### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by UgurcanAkkok** [spyder-ide/spyder#8398]
### What steps will reproduce the problem?

I installed it from stable repo, opened it for the first time from Whisker menu, not the terminal.
Clicked a link that says "Are you new to Spyder?".
 It showed me an error about Sphinx and (i couldnt read it carefully) said something like "Target and source(?) destination cant be same", and in the upper right box, it said "No documentation available".
Then without too much waiting i clicked preferences and error showed up. 
Other than not being able to reach the docs, there was no problem.

### Traceback
```python-traceback
  File "/usr/lib/python3.7/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.7.1
* Qt version: 5.11.2
* PyQt5 version: 5.11.3
* Operating system: Linux 4.19.6-1-MANJARO

### Dependencies

```
pyflakes >=0.6.0 :  2.0.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.3.0 (OK)
pandas >=0.13.1  :  0.23.4 (OK)
numpy >=1.7      :  1.15.4 (OK)
sphinx >=0.6.6   :  1.8.1 (OK)
rope >=0.9.4     :  0.11.0 (OK)
jedi >=0.9.0     :  0.13.1 (OK)
psutil >=0.3     :  5.4.8 (OK)
nbconvert >=4.0  :  5.4.0 (OK)
sympy >=0.7.3    :  1.3 (OK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.4.1 (OK)
IPython >=4.0    :  7.1.1 (OK)
pylint >=0.25    :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
> Qt version: 5.11.2
> PyQt5 version: 5.11.3

We don't support this Qt/PyQt versions yet. Please use PyQt 5.9 instead.
