### ISSUE TITLE
 'Editor' object has no attribute 'editorstacks'

### ISSUE THREAD

**Issue by Viterzgir** [spyder-ide/spyder#8400]
### What steps will reproduce the problem?

Everytimme i start app i see this error.          

### Traceback
```python-traceback
  File "/usr/lib/python3.7/site-packages/spyder/plugins/editor/plugin.py", line 1319, in toogle
    conf_name)
  File "/usr/lib/python3.7/site-packages/spyder/plugins/editor/plugin.py", line 1336, in _toggle_checkable_action
    if self.editorstacks:
AttributeError: 'Editor' object has no attribute 'editorstacks'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/spyder/plugins/editor/plugin.py", line 1319, in toogle
    conf_name)
  File "/usr/lib/python3.7/site-packages/spyder/plugins/editor/plugin.py", line 1336, in _toggle_checkable_action
    if self.editorstacks:
AttributeError: 'Editor' object has no attribute 'editorstacks'
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 4.0.0.dev0 
* Python version: 3.7.1
* Qt version: 5.11.2
* PyQt5 version: 5.11.3
* Operating System: Linux 4.19.4-arch1-1-ARCH

### Dependencies

```
pygments >=2.0    :  2.3.0 (OK)
sphinx >=0.6.6    :  1.8.1 (OK)
psutil >=0.3      :  5.4.8 (OK)
pyls >=0.19.0     :  0.21.4 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.1 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  7.1.1 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by jnsebgosselin** [comment]
Thanks for reporting! This was fixed in PR #8249.

However, if you pull the latest master, you are likely to see another error instead that was shadowed by that one. We are working tho fix it.
