### ISSUE TITLE
uuid.py error at Spyder launch after OS X update

### ISSUE THREAD

**Issue by LudgerHentschel** [spyder-ide/spyder#8408]
I just updated to Mac OS X version 10.13.6 (a security update for High Sierra). When I launch Spyder now, it fails to launch the ipython console and reports an error

  File "/Users/ludgerhentschel/anaconda2/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/ludgerhentschel/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 223, in _handle_execute_reply
    self.refresh_namespacebrowser()
  File "/Users/ludgerhentschel/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 67, in refresh_namespacebrowser
    'get_ipython().kernel.get_namespace_view()')
  File "/Users/ludgerhentschel/anaconda2/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 343, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/Users/ludgerhentschel/anaconda2/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/Users/ludgerhentschel/anaconda2/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Traceback (most recent call last):

Spyder gets stuck there. If I close the "Issue reporter" dialog it simply reopens with the same problem

Launching spyder from anaconda-navigator or from Terminal produces the same result.

This error message is similar to prior problems but the solutions posted there don't seem to work for me. Things I have tried:

1. Install latest Anaconda (5.3.1) from scratch
2. Update Spyder
3. Update qtconsole
4. "conda update python python.app" in Terminal
5. "conda update python" in Terminal

I encountered this problem after a previous OS update. I think "conda update python python.app" solved the problem at the time. 

Versions
---------
Mac OS X 10.13.6
Anaconda 5.3.1
Python 2.7.15
ipython 5.8.0
qtconsole 4.4.2
Spyder 3.3.2 (3.3.1 behaves the same way)

I hope there is a simple solution. 

Thank you, 

Ludger

**Comment by LudgerHentschel** [comment]
Alas, I have resolved this issue in a way I cannot reproduce. But I no longer have this problem. 

I re-installed and updated several times. The first few tries produced the same problem. The most recent attempt has revived Spyder on my installation.
