### ISSUE TITLE
Filepath change

### ISSUE THREAD

**Issue by hika-ru** [spyder-ide/spyder#8439]
### What steps will reproduce the problem?

I pulled a new version of a repository from github and some file locations were changed (moved into a new folder). When I used the "open recent" dialogue to open one of these files, while in the Notebook environment, a "404: Not found" window opened up and then the "Issue reporter" opened up.

### Traceback
```python-traceback
  File "/home/victor/anaconda3/lib/python3.6/site-packages/spyder_notebook/notebookplugin.py", line 366, in close_client
    nb_contents = nbformat.read(path, as_version=4)
  File "/home/victor/anaconda3/lib/python3.6/site-packages/nbformat/__init__.py", line 138, in read
    with io.open(fp, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/victor/Documents/Studium/Master-Studium/NT2/NT2-Uebungen/uebungsblatt3.ipynb'
Traceback (most recent call last):
  File "/home/victor/anaconda3/lib/python3.6/site-packages/spyder_notebook/notebookplugin.py", line 366, in close_client
    nb_contents = nbformat.read(path, as_version=4)
  File "/home/victor/anaconda3/lib/python3.6/site-packages/nbformat/__init__.py", line 138, in read
    with io.open(fp, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/victor/Documents/Studium/Master-Studium/NT2/NT2-Uebungen/uebungsblatt3.ipynb'
Traceback (most recent call last):
  File "/home/victor/anaconda3/lib/python3.6/site-packages/spyder_notebook/notebookplugin.py", line 366, in close_client
    nb_contents = nbformat.read(path, as_version=4)
  File "/home/victor/anaconda3/lib/python3.6/site-packages/nbformat/__init__.py", line 138, in read
    with io.open(fp, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/victor/Documents/Studium/Master-Studium/NT2/NT2-Uebungen/uebungsblatt3.ipynb'
Traceback (most recent call last):
  File "/home/victor/anaconda3/lib/python3.6/site-packages/spyder_notebook/notebookplugin.py", line 366, in close_client
    nb_contents = nbformat.read(path, as_version=4)
  File "/home/victor/anaconda3/lib/python3.6/site-packages/nbformat/__init__.py", line 138, in read
    with io.open(fp, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/victor/Documents/Studium/Master-Studium/NT2/NT2-Uebungen/uebungsblatt3.ipynb'
Traceback (most recent call last):
  File "/home/victor/anaconda3/lib/python3.6/site-packages/spyder_notebook/notebookplugin.py", line 366, in close_client
    nb_contents = nbformat.read(path, as_version=4)
  File "/home/victor/anaconda3/lib/python3.6/site-packages/nbformat/__init__.py", line 138, in read
    with io.open(fp, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/victor/Documents/Studium/Master-Studium/NT2/NT2-Uebungen/uebungsblatt3.ipynb'
WARNING:spyder.widgets.github.backend:failed to send bug report on github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.1 
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-42-generic

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.1 (OK)
psutil >=0.3      :  5.4.8 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
numpy >=1.7       :  1.14.0 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29 (OK)
qtconsole >=4.2.0 :  4.4.2 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by hika-ru** [comment]
I noticed that I can trigger the "issue reporter" window by trying to close the 404-not-found-Tab inside the notebook environment. Alo, it's not possible to close this tab.
