### ISSUE TITLE
An error occured while starting the kernel in Spyder

### ISSUE THREAD

**Issue by Debparno** [spyder-ide/spyder#8484]
I have installed Anaconda. Now when I am starting Spyder the following error is showing up on the Console. Can somebody help me out with this?

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1554, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 472, in write_connection_file
kernel_name=self.kernel_name
File "C:\ProgramData\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 101, in write_connection_file
sock.bind((ip, 0))
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

**Comment by ccordoba12** [comment]
This is not a problem with Spyder but a problem with your firewall/antivirus. You need to allow it to open sockets in your own machine to fix this.

This is all the advice we can give you because things depend on your own firewall/antivirus.
