### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by derech** [spyder-ide/spyder#8490]
### What steps will reproduce the problem?

Open spyder and work in ipython consol
Open a new ipython console tab, or restart current kernel

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
It seems you're Anaconda installation is corrupted. Please reinstall and try again.

**Comment by ccordoba12** [comment]
Closing because of lack of response.

**Comment by filipmihal** [comment]
Hey, 
I have the same problem, but instead of Anaconda, I am using Virtualenv. Do you have any idea what might the problem?

**Comment by Rak355** [comment]
I am having the same issue

Traceback (most recent call last):
File "C:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 306, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Anaconda3\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 484, in initialize
self.init_kernel()
File "C:\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 389, in init_kernel
user_ns=self.user_ns,
File "C:\Anaconda3\lib\site‑packages\traitlets\config\configurable.py", line 412, in instance
inst = cls(*args, **kwargs)
File "C:\Anaconda3\lib\site‑packages\spyder_kernels\console\kernel.py", line 37, in __init__
super(SpyderKernel, self).__init__(*args, **kwargs)
File "C:\Anaconda3\lib\site‑packages\ipykernel\ipkernel.py", line 67, in __init__
kernel = self,
File "C:\Anaconda3\lib\site‑packages\traitlets\config\configurable.py", line 412, in instance
inst = cls(*args, **kwargs)
File "C:\Anaconda3\lib\site‑packages\IPython\core\interactiveshell.py", line 693, in __init__
self.init_magics()
File "C:\Anaconda3\lib\site‑packages\ipykernel\zmqshell.py", line 593, in init_magics
super(ZMQInteractiveShell, self).init_magics()
File "C:\Anaconda3\lib\site‑packages\IPython\core\interactiveshell.py", line 2245, in init_magics
m.PylabMagics, m.ScriptMagics,
File "C:\Anaconda3\lib\site‑packages\IPython\core\magic.py", line 405, in register
m = m(shell=self.shell)
File "C:\Anaconda3\lib\site‑packages\IPython\core\magics\osm.py", line 52, in __init__
self.execre = re.compile(r'(.*)\.(%s)$' % winext,re.IGNORECASE)
File "C:\Anaconda3\lib\re.py", line 234, in compile
return _compile(pattern, flags)
File "C:\Anaconda3\lib\re.py", line 286, in _compile
p = sre_compile.compile(pattern, flags)
File "C:\Anaconda3\lib\sre_compile.py", line 764, in compile
p = sre_parse.parse(p, flags)
File "C:\Anaconda3\lib\sre_parse.py", line 930, in parse
p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
File "C:\Anaconda3\lib\sre_parse.py", line 426, in _parse_sub
not nested and not items))
File "C:\Anaconda3\lib\sre_parse.py", line 816, in _parse
p = _parse_sub(source, state, sub_verbose, nested + 1)
File "C:\Anaconda3\lib\sre_parse.py", line 426, in _parse_sub
not nested and not items))
File "C:\Anaconda3\lib\sre_parse.py", line 507, in _parse
code = _escape(source, this, state)
File "C:\Anaconda3\lib\sre_parse.py", line 402, in _escape
raise source.error("bad escape %s" % escape, len(escape))
re.error: bad escape \P at position 52

Spyder version: 3.3.6
Python version: 3.7.3

**Comment by santule** [comment]
I have the same issue. I uninstalled and reinstalled anaconda but still get the same error
