### ISSUE TITLE
An erro occurs after the spyder is restarted after computer restarting. It cannot connect to kernels

### ISSUE THREAD

**Issue by zhchyang2004** [spyder-ide/spyder#8491]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\tools\Anaconda3\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "D:\tools\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "D:\tools\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1033, in create_new_client
    self.connect_client_to_kernel(client)
  File "D:\tools\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1059, in connect_client_to_kernel
    stderr_file)
  File "D:\tools\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1477, in create_kernel_manager_and_kernel_client
    config=None, autorestart=True)
  File "D:\tools\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 958, in __new__
    inst.setup_instance(*args, **kwargs)
  File "D:\tools\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 986, in setup_instance
    super(HasTraits, self).setup_instance(*args, **kwargs)
  File "D:\tools\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 977, in setup_instance
    value.instance_init(self)
  File "D:\tools\Anaconda3\lib\site-packages\traitlets\traitlets.

**Comment by zhchyang2004** [comment]
The erro happened after a VTK is sinstalled via https://www.vtk.org/files/release/7.1/vtkpython-7.1.1-Windows-64bit.exe.
--------------------------------------------------------------------------------------------------------------
An error ocurred while starting the kernel
The error is:

Traceback (most recent call last):
File "D:\tools\anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1544, in create_kernel_manager_and_kernel_client
config=None, autorestart=True)
File "D:\tools\anaconda3\lib\site‑packages\traitlets\traitlets.py", line 958, in __new__
inst.setup_instance(*args, **kwargs)
File "D:\tools\anaconda3\lib\site‑packages\traitlets\traitlets.py", line 986, in setup_instance
super(HasTraits, self).setup_instance(*args, **kwargs)
File "D:\tools\anaconda3\lib\site‑packages\traitlets\traitlets.py", line 977, in setup_instance
value.instance_init(self)
File "D:\tools\anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1691, in instance_init
self._resolve_classes()
File "D:\tools\anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1696, in _resolve_classes
self.klass = self._resolve_string(self.klass)
File "D:\tools\anaconda3\lib\site‑packages\traitlets\traitlets.py", line 1507, in _resolve_string
return import_item(string)
File "D:\tools\anaconda3\lib\site‑packages\traitlets\utils\importstring.py", line 34, in import_item
module = __import__(package, fromlist=[obj])
File "D:\tools\anaconda3\lib\site‑packages\jupyter_client\session.py", line 61, in 
from jupyter_client.jsonutil import extract_dates, squash_dates, date_default
File "D:\tools\anaconda3\lib\site‑packages\jupyter_client\jsonutil.py", line 11, in 
from dateutil.parser import parse as _dateutil_parse
File "C:\Program Files\VTK 7.1.1\bin\Lib\site‑packages\dateutil\parser.py", line 158
l.append("%s=%s" % (attr, `value`))
^
SyntaxError: invalid syntax

**Comment by zhchyang2004** [comment]
After VTK is uninstalled, Spyder recovered well.

**Comment by ccordoba12** [comment]
The problem is you're mixing these two Python installations

    D:\tools\anaconda3\lib\site‑packages
    C:\Program Files\VTK 7.1.1\bin\Lib\site‑packages

So, instead of mixing them, you just need to install VTK with with conda and forget about the second installation. For that you need to open an Anaconda prompt and run there

    conda install vtk

**Comment by zhchyang2004** [comment]
Thanks！The problem is solved after VTK is installed via 'whl' file:
VTK‑8.1.2‑cp36‑cp36m‑win_amd64.whl

**Comment by ccordoba12** [comment]
If you're using Anaconda, that's really not the way to go. You should use conda to install vtk instead of pip, as I told you.

**Comment by zhchyang2004** [comment]
I really use pip solving problem well.
