### ISSUE TITLE
Error while importing dataset

### ISSUE THREAD

**Issue by OrhanAbuska** [spyder-ide/spyder#8522]
## Description

**What steps will reproduce the problem?**

1.  
2. 
3. 

**What is the expected output? What do you see instead?**
Hi I was working on a Machine Learning Data Analysis project and when I was trying to import a .CSV dataset as array, list and timeframe, that error appeared on the screen.

**Please provide any additional information below**

  File "C:\anaconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 633, in process
    self.clip_data = self._get_table_data()
  File "C:\anaconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 617, in _get_table_data
    return pd.read_csv(buf, **info)
  File "C:\anaconda3\lib\site-packages\pandas\io\parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\anaconda3\lib\site-packages\pandas\io\parsers.py", line 455, in _read
    data = parser.read(nrows)
  File "C:\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1069, in read
    ret = self._engine.read(nrows)
  File "C:\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1839, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 902, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 924, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 978, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 965, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2208, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 13 fields in line 722, saw 14

Traceback (most recent call last):
  File "C:\anaconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 633, in process
    self.clip_data = self._get_table_data()
  File "C:\anaconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 617, in _get_table_data
    return pd.read_csv(buf, **info)
  File "C:\anaconda3\lib\site-packages\pandas\io\parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\anaconda3\lib\site-packages\pandas\io\parsers.py", line 455, in _read
    data = parser.read(nrows)
  File "C:\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1069, in read
    ret = self._engine.read(nrows)
  File "C:\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1839, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 902, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 924, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 978, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 965, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2208, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 13 fields in line 722, saw 14

Traceback (most recent call last):
  File "C:\anaconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 633, in process
    self.clip_data = self._get_table_data()
  File "C:\anaconda3\lib\site-packages\spyder\widgets\variableexplorer\importwizard.py", line 617, in _get_table_data
    return pd.read_csv(buf, **info)
  File "C:\anaconda3\lib\site-packages\pandas\io\parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\anaconda3\lib\site-packages\pandas\io\parsers.py", line 455, in _read
    data = parser.read(nrows)
  File "C:\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1069, in read
    ret = self._engine.read(nrows)
  File "C:\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1839, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 902, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 924, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 978, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 965, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2208, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 13 fields in line 722, saw 14

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.2 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
> when I was trying to import a .CSV dataset as array, list and timeframe, that error appeared on the screen

Please upload the CSV you're working somewhere so we can test and fix this error in our side. Thanks!

**Comment by ccordoba12** [comment]
Closing because of lack of response.
