### ISSUE TITLE
Spyder error

### ISSUE THREAD

**Issue by soanduong** [spyder-ide/spyder#8536]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2876, in _dep_map
    class DistInfoDistribution(Distribution):
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2670, in __getattr__
    if self.platform:
AttributeError: _DistInfoDistribution__dep_map

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2867, in _parsed_pkg_info
    take an extra step and try to get the version number from
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2670, in __getattr__
    if self.platform:
AttributeError: _pkg_info

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\spyder\utils\introspection\manager.py", line 220, in get_completions
    info = self._get_code_info('completions', automatic=automatic)
  File "C:\Python36\lib\site-packages\spyder\utils\introspection\manager.py", line 216, in _get_code_info
    **kwargs)
  File "C:\Python36\lib\site-packages\spyder\utils\introspection\utils.py", line 75, in __init__
    self._get_info()
  File "C:\Python36\lib\site-packages\spyder\utils\introspection\utils.py", line 87, in _get_info
    lexer = find_lexer_for_filename(self.filename)

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.2). Please update by opening the Anaconda Prompt and running there

    conda update spyder
