### ISSUE TITLE
Lots of error messages when starting spyder 4 beta1

### ISSUE THREAD

**Issue by RnoldR** [spyder-ide/spyder#8553]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Install spyder 4.0b1
start it
A lot of error messages are listed about notebook (which is not running).
```$ spyder
[I 07:48:07.156 NotebookApp] Serving notebooks from local directory: /tmp/spyder-arnold/notebooks
[I 07:48:07.156 NotebookApp] The Jupyter Notebook is running at:
[I 07:48:07.156 NotebookApp] http://localhost:8888/?token=c44794cfb2c835bd8f3e49926301bd58c2fef16f7a4d7203
[I 07:48:07.156 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 07:48:07.159 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///run/user/1000/jupyter/nbserver-7636-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=c44794cfb2c835bd8f3e49926301bd58c2fef16f7a4d7203
js: Uncaught TypeError: Cannot set property 'className' of null
js: Uncaught TypeError: Cannot set property 'className' of null
js: Uncaught TypeError: Cannot set property 'className' of null
js: WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.
js: Uncaught TypeError: Cannot set property 'className' of null
js: Uncaught TypeError: Cannot set property 'className' of null
js: actions
[W 07:48:08.688 NotebookApp] Notebook untitled0.ipynb is not trusted
[I 07:48:08.801 NotebookApp] Kernel started: 44d0f4d9-053c-4c88-9699-8b5e01a36e7d
js: Exception in event handler for spec_changed.Kernel
[W 07:48:08.813 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190111074807 (127.0.0.1) 10.10ms referer=http://localhost:8888/notebooks/untitled0.ipynb
js: Widgets are not available.  Please install widgetsnbextension or ipywidgets 4.0
[I 07:48:09.567 NotebookApp] Adapting to protocol v5.1 for kernel 44d0f4d9-053c-4c88-9699-8b5e01a36e7d
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f9569964d90>)
Traceback (most recent call last):
  File "/home/arnold/bin/anaconda/envs/nlp/lib/python3.6/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/home/arnold/bin/anaconda/envs/nlp/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/arnold/bin/anaconda/envs/nlp/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 306, in advance_eventloop
    eventloop(self)
TypeError: 'NoneType' object is not callable
```

After these messages Spyder 4 runs fine. 

My compliments about the new version! It just works without hassles, but got a better project interface and I am glad with the improved variable page. I use it for a week now in production and found no errors (except that the startup is quite noisy :-)).

### What steps reproduce the problem?

1. Start spyder 4

**Comment by ccordoba12** [comment]
Simply uninstall and the errors will go away.

**Comment by ccordoba12** [comment]
Uninstall spyder-notebok
