### ISSUE TITLE
Can't edit variables in Variable explorer for IPython Console

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#857]
_From [ruoyu0...@gmail.com](https://code.google.com/u/112768690977086123209/) on 2011-12-01T02:14:17Z_

Spyder Version:  2.1.4
Python Version:  2.6.5
Qt Version:      4.7.2, PyQt4 (API v1) 4.8.4 on Windows 

What steps will reproduce the problem?

 1. run "a=1" in IPython Console
2. a is shown in Variable explorer
3. try edit it. What is the expected output? What do you see instead? I got error messagebox or traceback in Internal console:

Here is the traceback in Internal console:

\>>> Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\spyderlib\widgets\dicteditor.py", line 486, in setModelData
    self.get_value(index),
  File "C:\Python26\lib\site-packages\spyderlib\widgets\dicteditor.py", line 1174, in get_value
    return self.get_value_func(name)
  File "C:\Python26\lib\site-packages\spyderlib\widgets\externalshell\namespacebrowser.py", line 334, in get_value
    raise pickle.PicklingError(msg)
pickle.PicklingError: Object \<b>a</b> is not picklable 

Please provide any additional information below

.

**Attachment:** [edititem.png](http://code.google.com/p/spyderlib/issues/detail?id=857)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=857_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-01T00:36:58Z_

Ok, I know exactly what it is.
This is a regression of v2.1.4.

Please downgrade to v2.1.2 if possible.
I'm fixing this ASAP.

**Status:** Started  
  **Labels:** -Priority-Medium Priority-Critical Cat-VariableExplorer Milestone-Release2.1

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-01T00:57:01Z_

**Labels:** Component-IPython

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-01T02:02:34Z_

I thought I knew what is was about, but actually I don't and I even can't reproduce it. 

Is anyone able to reproduce this bug?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-01T05:21:24Z_

You may post here the monitor.log file that may have been created in Spyder's conf directory (in your home directory: folder named .spyder2). 

Or, you could try to enable the Debug mode in the monitor (set the DEBUG global to True in spyderlib/widgets/monitor.py) and take a look at the monitor_debug.log.

**Comment by spyder-issues-migrator** [comment]
_From [ruoyu0...@gmail.com](https://code.google.com/u/112768690977086123209/) on 2011-12-01T16:45:36Z_

There is nothing in monitor.log. I enabled the DEBUG=True,

When I double "a" in the variable explorer, I got the error message, and here is the monitor_debug.log.

DEBUG:root:****** Introspection request /Begin ******
DEBUG:root:command: 'set_remote_view_settings()'
DEBUG:root: result: None
DEBUG:root:updating remote view
DEBUG:root:sending result
DEBUG:root:****** Introspection request /End ******
DEBUG:root:****** Introspection request /Begin ******
DEBUG:root:command: u"isdefined('m.getglobal', force_import=False)"
DEBUG:root: result: False
DEBUG:root:updating remote view
DEBUG:root:sending result
DEBUG:root:****** Introspection request /End ******
DEBUG:root:****** Introspection request /Begin ******
DEBUG:root:connection timed out -> updating remote view
DEBUG:root:****** Introspection request /End ******
DEBUG:root:updating remote view
DEBUG:root:sending result
DEBUG:root:****** Introspection request /End ******
DEBUG:root:****** Introspection request /Begin ******
DEBUG:root:connection timed out -> updating remote view
DEBUG:root:****** Introspection request /End ******
DEBUG:root:updating remote view
DEBUG:root:sending result
DEBUG:root:****** Introspection request /End ******
DEBUG:root:****** Introspection request /Begin ******
DEBUG:root:command: '__get_global__("a")'
DEBUG:root: result: 1
DEBUG:root:updating remote view
DEBUG:root:sending result
DEBUG:root:****** Introspection request /End ******
DEBUG:root:****** Introspection request /Begin ******
DEBUG:root:connection timed out -> updating remote view
DEBUG:root:****** Introspection request /End ******
DEBUG:root:updating remote view
DEBUG:root:sending result
DEBUG:root:****** Introspection request /End ******
DEBUG:root:****** Introspection request /Begin ******
DEBUG:root:connection timed out -> updating remote view
DEBUG:root:****** Introspection request /End ******
DEBUG:root:updating remote view
DEBUG:root:sending result
DEBUG:root:****** Introspection request /End ******
DEBUG:root:****** Introspection request /Begin ******

I will do some debug, and report later.

**Comment by spyder-issues-migrator** [comment]
_From [ruoyu0...@gmail.com](https://code.google.com/u/112768690977086123209/) on 2011-12-01T17:38:25Z_

I add some print code in communicate(), write_packet(), read_packet() in bsdsocket.py:

When I double click the "a=1" in variable explorer

In the spyder GUI process, bsdsocket.communicate() output:


===================================================
communicate write_packet __get_global__("a")
write_packet 1a000000800255135f5f6765745f676c6f62616c5f5f282261222971012e

communicate read_packet
read_packet 4 80024e2e     

communicate write_packet a is not None
write_packet 140000008002550d61206973206e6f74204e6f6e6571012e

communicate read_packet
read_packet 5 80024b012e

===================================================

here "80024e2e" is None:

\>>> print pickle.loads(binascii.unhexlify("80024e2e"))

"80024b012e" is 1:

\>>> print pickle.loads(binascii.unhexlify("80024b012e"))

In the IPython process:


===================================================
read_packet 4 80024e2e
write_packet 0400000080024e2e
read_packet 26 800255135f5f6765745f676c6f62616c5f5f282261222971012e
command: '__get_global__("a")'
write_packet 0500000080024b012e
read_packet 20 8002550d61206973206e6f74204e6f6e6571012e command: 'a is not None'

===================================================

So, afther it get the __get_global__("a") command, it write 1 to the socket.
It seems that the None object sent before __get_global__("a") is received by
the GUI process.

**Comment by spyder-issues-migrator** [comment]
_From [ruoyu0...@gmail.com](https://code.google.com/u/112768690977086123209/) on 2011-12-01T18:37:36Z_

I changed the communicate function to:

def communicate(sock, command, settings=[]):
\## new com implementation: (see solution (2) in issue #434 )
\#def communicate(sock, command, settings=[], timeout=None):
    """Communicate with monitor"""
    flag = False
    if command == '__get_global__("a")':
        flag = True
    if flag: print "communicate", command
    write_packet(sock, command)
    if flag: print "after write"
    
    for option in settings:
        write_packet(sock, option)
    if flag: print "after option"
    \# old com implementation: (see solution (1) in issue #434 )
    try:
        output = read_packet(sock)
    except:
        output = "read_packet error"
    if flag: print "after output", output
    if flag and output is None:
        output = read_packet(sock)
        print "read again", output
    return output

here is the output, the first time __get_global__("a") will get a None object and then the correct object 1. After this, the communication is OK. And it also fixes issue #858 .


=======================================

communicate __get_global__("a")
after write
after option
after output None
read again 1
communicate __get_global__("a")
after write
after option
after output 1
communicate __get_global__("a")
after write
after option
after output 1
communicate __get_global__("a")
after write
after option
after output 2
communicate __get_global__("a")
after write
after option
after output 2
communicate __get_global__("a")
after write
after option
after output 2
communicate __get_global__("a")
after write
after option
after output 3

**Comment by spyder-issues-migrator** [comment]
_From [ruoyu0...@gmail.com](https://code.google.com/u/112768690977086123209/) on 2011-12-01T18:51:55Z_

I added the following code before write_packet(sock, command) in communicate() to clear the receive buffer, and it fixed the problem. I don't know how to figure out why IPython process send an excess None object yet.

    timeout = sock.gettimeout()
    sock.settimeout(0)
    try:
        sock.recv(1024)
    except:
        pass
    sock.settimeout(timeout)

**Comment by spyder-issues-migrator** [comment]
_From [ruoyu0...@gmail.com](https://code.google.com/u/112768690977086123209/) on 2011-12-01T21:32:07Z_

it seems that I got why there is an excess None object.

I added the following lines at the beginning of communicate():

    import threading
    print "communicate", sock, command, threading.current_thread().name

and add a line in ask_monitor() in pythonshell.py after except MemoryError:

    print "ask_monitor MemoryError"

and some codes that output what is received and returned in Monitor.run() in monitor.py.

When I start spyder, the Internal console shows :

\---------------------------
communicate \<socket._socketobject object at 0x074DEEA0> set_remote_view_settings() Thread-2
communicate \<socket._socketobject object at 0x074DEEA0> isdefined('gc.get_objects', force_import=False) MainThread
ask_monitor MemoryError
\---------------------------
So, two thread Thread-2 and MainThread use the same socket to send command. the isdefined() command is failed by MemoryError exception. 

the IPython console shows:

read_packet set_remote_view_settings()
communicate \<socket._socketobject object at 0x050C8F48> {'data': {}, 'command': 'remote_view'} Thread-1
write_packet 4 bytes
read_packet isdefined('gc.get_objects', force_import=False)
write_packet 4 bytes

both the set_remote_view_settings() and isdefined() commands are received and None object is returned. 

Because the call of communicate() in ask_monitor() failed, one of the None object is remained.

So a quick fix is by using a Lock:

from threading import Lock
communicate_lock = Lock()
def communicate(sock, command, settings=[]):
    """Communicate with monitor"""
    try:
        communicate_lock.acquire()
        write_packet(sock, command)
        for option in settings:
            write_packet(sock, option)
        \# old com implementation: (see solution (1) in issue #434 )
        return read_packet(sock)
    finally:
        communicate_lock.release()

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-03T00:41:11Z_

Thank you very much for all this debugging work.
I'll take a look at it today or tomorrow.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-04T00:30:05Z_

This issue was updated by revision bb5e4d94bc3d .

Thanks a lot for your contribution to the project.

Update issue `#858` Status: Fixed

**Status:** Fixed
