### ISSUE TITLE
An error occurred while starting the kernel 

### ISSUE THREAD

**Issue by vishu15v** [spyder-ide/spyder#8589]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I have install the pandas package and after that this issue came.
I don't know much about this i am beginner.

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

An error ocurred while starting the kernel
Traceback (most recent call last):
File "C:\Users\vaibhav\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\vaibhav\miniconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\vaibhav\miniconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\vaibhav\miniconda3\lib\site‑packages\spyder_kernels\console\start.py", line 279, in main
import_spydercustomize()
File "C:\Users\vaibhav\miniconda3\lib\site‑packages\spyder_kernels\console\start.py", line 39, in import_spydercustomize
import spydercustomize
File "C:\Users\vaibhav\miniconda3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 25, in 
from IPython.core.getipython import get_ipython
File "C:\Users\vaibhav\miniconda3\lib\site‑packages\IPython\__init__.py", line 54, in 
from .core.application import Application
File "C:\Users\vaibhav\miniconda3\lib\site‑packages\IPython\core\application.py", line 16, in 
from copy import deepcopy
File "C:\Users\vaibhav\AppData\Roaming\SPB_Data\copy.py", line 1, in 
import matplotlib.pyplot as plt
File "C:\Users\vaibhav\miniconda3\lib\site‑packages\matplotlib\__init__.py", line 141, in 
from . import cbook, rcsetup
File "C:\Users\vaibhav\miniconda3\lib\site‑packages\matplotlib\rcsetup.py", line 25, in 
from matplotlib.fontconfig_pattern import parse_fontconfig_pattern
File "C:\Users\vaibhav\miniconda3\lib\site‑packages\matplotlib\fontconfig_pattern.py", line 19, in 
from pyparsing import (Literal, ZeroOrMore, Optional, Regex, StringEnd,
File "C:\Users\vaibhav\miniconda3\lib\site‑packages\pyparsing.py", line 4914, in 
_reBracketExpr = Literal("[") + Optional("^").setResultsName("negate") + Group( OneOrMore( _charRange | _singleChar ) ).setResultsName("body") + "]"
File "C:\Users\vaibhav\miniconda3\lib\site‑packages\pyparsing.py", line 1234, in setResultsName
newself = self.copy()
File "C:\Users\vaibhav\miniconda3\lib\site‑packages\pyparsing.py", line 1193, in copy
cpy = copy.copy( self )
AttributeError: module 'copy' has no attribute 'copy'

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
This problem is caused because you have a file called `copy.py` either in `C:\Users\vaibhav` or in your current working directory.

So to fix it, you need to remove or rename that file.

**Comment by vishu15v** [comment]
Thanks so much. Problem resolved

**Comment by JASHWANTHREDDYTUPILI** [comment]
@vishu15v , hey I got same error as yours , can you tell me how did you fix it ??
I tried deleting the copy.py but still it doesn't work
