### ISSUE TITLE
Cannoot change theme colours

### ISSUE THREAD

**Issue by marinaesp** [spyder-ide/spyder#8592]
### What steps will reproduce the problem?

Could not change preset colours of themes and could not save my own theme. The new theme does not save the colours I changes and use only the defaults. 

### Traceback
```python-traceback
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/configdialog.py", line 1320, in update_preview
    scheme_name = self.current_scheme
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/configdialog.py", line 1249, in current_scheme
    return self.scheme_choices_dict[self.current_scheme_name]
KeyError: ''
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/configdialog.py", line 1291, in update_buttons
    current_scheme = self.current_scheme
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/configdialog.py", line 1249, in current_scheme
    return self.scheme_choices_dict[self.current_scheme_name]
KeyError: ''
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/configdialog.py", line 224, in button_clicked
    configpage.apply_changes()
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/configdialog.py", line 105, in apply_changes
    self.apply_callback()
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/configdialog.py", line 270, in <lambda>
    self.apply_settings(self.changed_options))
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/configdialog.py", line 1239, in apply_settings
    self.update_preview()
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/configdialog.py", line 1320, in update_preview
    scheme_name = self.current_scheme
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/configdialog.py", line 1249, in current_scheme
    return self.scheme_choices_dict[self.current_scheme_name]
KeyError: ''
WARNING:spyder.widgets.github.backend:failed to send bug report on github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
WARNING:spyder.widgets.github.backend:failed to send bug report on github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.1 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.2.0

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
psutil >=0.3      :  5.4.7 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.1 (OK)
sympy >=0.7.3     :  1.2 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this in a future release.
