### ISSUE TITLE
Error message upon execution of any command in remote ipython kernal

### ISSUE THREAD

**Issue by selahlynch** [spyder-ide/spyder#8619]
## Description

**What steps will reproduce the problem?**

1. `conda install spyder-kernals` on remote linux server
    anaconda:        2018.12-py36h44efdcc_0 --> custom-py36hbbc8b67_0
    ca-certificates: 2018.03.07-0           --> 2018.12.5-0          

2. In Spyder 3.2.3 Ipython console window, Rclick -> Connect to an existing console
3. Supply local json configuration file in dialog box.
4. Check "This is a remote kernel"
5. Fill out hostname and password
6. Click OK
7. Enter any command into console and press enter.

**What is the expected output? What do you see instead?**
Expected output is that the command executes with no problems.
Instead...
An error message pops up.  This happens every time I execute any command in the ipython window.  That said, the commands seem to execute successfully.

**Please provide any additional information below**

  File "/Users/selah/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 912, in set_working_directory
    refresh_console=False)
  File "/Users/selah/anaconda3/lib/python3.6/site-packages/spyder/plugins/workingdirectory.py", line 286, in chdir
    os.chdir(directory)
FileNotFoundError: [Errno 2] No such file or directory: '/data1/home/selah'
Traceback (most recent call last):
  File "/Users/selah/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 912, in set_working_directory
    refresh_console=False)
  File "/Users/selah/anaconda3/lib/python3.6/site-packages/spyder/plugins/workingdirectory.py", line 286, in chdir
    os.chdir(directory)
FileNotFoundError: [Errno 2] No such file or directory: '/data1/home/selah'
Traceback (most recent call last):
  File "/Users/selah/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 912, in set_working_directory
    refresh_console=False)
  File "/Users/selah/anaconda3/lib/python3.6/site-packages/spyder/plugins/workingdirectory.py", line 286, in chdir
    os.chdir(directory)
FileNotFoundError: [Errno 2] No such file or directory: '/data1/home/selah'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.5
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.4 (OK)
numpy >=1.7      :  1.15.0 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by selahlynch** [comment]
All seems to be working fine after update to Spyder 3.3.2.  Sorry for the false alarm.  Thanks for the frikin' fantastic tool!!!
