### ISSUE TITLE
Can´t access preferences menu

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#863]
_From [nunoport...@gmail.com](https://code.google.com/u/108617919618299841919/) on 2011-12-02T05:24:37Z_

What steps will reproduce the problem?

 1.Click on preferences under tools menu 2. 3. What is the expected output? What do you see instead? open preferences window. Nothing happens What version of the product are you using? On what operating system? Spyder 2.1.3 and win7 x64 

Please provide any additional information below

. Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 1616, in edit_p
references
    widget = plugin.create_configwidget(dlg)
  File "C:\Python27\lib\site-packages\spyderlib\plugins\__init__.py", line 155,
in create_configwidget
    configwidget.initialize()
  File "C:\Python27\lib\site-packages\spyderlib\plugins\configdialog.py", line 4
5, in initialize
    self.setup_page()
  File "C:\Python27\lib\site-packages\spyderplugins\p_profiler.py", line 36, in
setup_page
    )+("\n&#37;s\n" &#37; ProfilerWidget.DATAPATH))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 18: ordinal
 not in range(128)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=863_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-03T10:14:17Z_

To help us debug this, please do the following in a standard Python interpreter outside Spyder (simply run 'python' in a command window):

\>>> from spyderplugins.widgets.profilergui import ProfilerWidget
\>>> print ProfilerWidget.DATAPATH

And post here the output... which I guess contains non-ASCII characters because I guess your Windows account's username itself contains non-ASCII characters.

**Comment by spyder-issues-migrator** [comment]
_From [nunoport...@gmail.com](https://code.google.com/u/108617919618299841919/) on 2011-12-03T12:54:59Z_

Hi,

i got this result:

C:\Users\Nuno Gonþalves\.spyder2\.profiler.results

my username in Windows contains this "ç" character... so changing my account username is sufficient for solving the problem?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-04T03:42:05Z_

Generally speaking, I would strongly recommend to set a username containing only ASCII characters. A lot of applications won't handle this. But we have already done a lot of work for Spyder to be compatible with such accounts.

So, for this particular issue, you are not forced to change your account username which is a rather radical solution.
I'm fixing this and this will be part of the forthcoming v2.1.5 release.

**Status:** Started

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-04T03:42:26Z_

This issue was updated by revision 3cc963d4f26f .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [nunoport...@gmail.com](https://code.google.com/u/108617919618299841919/) on 2011-12-04T08:36:18Z_

Hi, 

sorry for reopening this issue but i'v modified baseconfig.py and p_profiler.py has in your revision. But i'm getting this error when trying to open spyder from pythonxy.

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\xy\xyhome.pyw", line 609, in l_spyder
    from spyderlib import spyder
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 98, in \<module>

    from spyderlib.plugins.workingdirectory import WorkingDirectory
  File "C:\Python27\lib\site-packages\spyderlib\plugins\workingdirectory.py", li
ne 141, in \<module>
    class WorkingDirectory(QToolBar, SpyderPluginMixin):
  File "C:\Python27\lib\site-packages\spyderlib\plugins\workingdirectory.py", li
ne 147, in WorkingDirectory
    LOG_PATH = get_conf_path('.workingdir')
  File "C:\Python27\lib\site-packages\spyderlib\baseconfig.py", line 33, in get_
conf_path
    conf_dir = osp.join( decode( get_home_dir() ), SUBFOLDER )
  File "C:\Python27\lib\ntpath.py", line 108, in join
    path += "\\" + b
TypeError: can only concatenate tuple (not "str") to tuple

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-04T09:22:06Z_

Sorry for this: the commit was not complete.
See revision 68bcc293d8f1 .

**Comment by spyder-issues-migrator** [comment]
_From [nunoport...@gmail.com](https://code.google.com/u/108617919618299841919/) on 2011-12-04T12:55:49Z_

I've applied last revision for baseconfig.py and previous revision for p_profiler.py but now i can't even open spyder.

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\xy\xyhome.pyw", line 609, in l_spyder
    from spyderlib import spyder
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 99, in \<module>

    from spyderlib.plugins.editor import Editor
  File "C:\Python27\lib\site-packages\spyderlib\plugins\editor.py", line 36, in
\<module>
    from spyderlib.widgets.editor import (ReadWriteStatus, EncodingStatus,
  File "C:\Python27\lib\site-packages\spyderlib\widgets\editor.py", line 29, in
\<module>
    from spyderlib.utils.module_completion import moduleCompletion
  File "C:\Python27\lib\site-packages\spyderlib\utils\module_completion.py", lin
e 31, in \<module>
    db = PickleShareDB(MODULES_PATH)
  File "C:\Python27\lib\site-packages\spyderlib\utils\external\pickleshare.py",
line 52, in __init__
    self.root = Path(root).expanduser().abspath()
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 17:
 ordinal not in range(128)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-04T14:06:14Z_

I see... I think that I'd need to change the fix. I'll keep you posted.

**Status:** Started

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-04T23:05:56Z_

And if you do the following in baseconfig.py, does it help?
(I've just added "unicode( )" around "home_dir")

def get_conf_path(filename=None):
    """Return absolute path for configuration file with specified filename
    as a unicode string (decoding it by guessing the codec if necessary)"""
    from spyderlib import userconfig
    from spyderlib.utils import encoding
    home_dir, _enc = encoding.decode(userconfig.get_home_dir())
    conf_dir = osp.join(unicode(home_dir), SUBFOLDER)
    if not osp.isdir(conf_dir):
        os.mkdir(conf_dir)
    if filename is None:
        return conf_dir
    else:
        return osp.join(conf_dir, filename)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-04T23:08:18Z_

This issue was updated by revision a661b678aad4 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [nunoport...@gmail.com](https://code.google.com/u/108617919618299841919/) on 2011-12-05T01:43:18Z_

Still not working... 

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\xy\xyhome.pyw", line 609, in l_spyder
    from spyderlib import spyder
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 99, in \<module>

    from spyderlib.plugins.editor import Editor
  File "C:\Python27\lib\site-packages\spyderlib\plugins\editor.py", line 36, in
\<module>
    from spyderlib.widgets.editor import (ReadWriteStatus, EncodingStatus,
  File "C:\Python27\lib\site-packages\spyderlib\widgets\editor.py", line 29, in
\<module>
    from spyderlib.utils.module_completion import moduleCompletion
  File "C:\Python27\lib\site-packages\spyderlib\utils\module_completion.py", lin
e 31, in \<module>
    db = PickleShareDB(MODULES_PATH)
  File "C:\Python27\lib\site-packages\spyderlib\utils\external\pickleshare.py",
line 52, in __init__
    self.root = Path(root).expanduser().abspath()
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 17:
 ordinal not in range(128)

Thank you for your patience!

**Comment by spyder-issues-migrator** [comment]
_From [nunoport...@gmail.com](https://code.google.com/u/108617919618299841919/) on 2011-12-05T01:50:32Z_

I tried to use initial version of baseconfig.py file but with another user name without  non ascii characters and for now i can open spyder, but i still can't access preferences menu.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-05T06:17:41Z_

Ok do let's forget about the two fixes that don't work (I'll remove them and restore the original 'baseconfig.py' file). 

Could you please just comment lines 33-42 in spyderplugins/p_profiler.py ?
(this just display so consequences are limited)
I suspect that other similar bugs could happen then.

**Status:** Started

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-05T06:26:23Z_

Oh that's dumb... I think I know where it comes from. 
Simply changing "\n%s\n" by u"\n%s\n" at line 36 should do the trick. I don't know I didn't see it earlier. 

Or (this should be equivalent):

Replace:

"are stored here:"
)+("\n%s\n" % ProfilerWidget.DATAPATH))

By:

"are stored here:\n%s\n" % ProfilerWidget.DATAPATH))

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-12-05T07:23:18Z_

Regarding comment 11, it's the same problem as reported in issue #814 . This almost surely means that my previous fix is not working as expected.

Nuno, could you tell me what output do you get from this?

\>>> import locale
\>>> locale.getpreferredencoding()

**Comment by spyder-issues-migrator** [comment]
_From [nunoport...@gmail.com](https://code.google.com/u/108617919618299841919/) on 2011-12-05T07:23:32Z_

let me see if i understood right: restore baseconfig.py and p_profiler.py to their original version (installation version) and then simple do your last suggestion on comment 14. is this right?

have you already restored original files?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-12-05T07:24:30Z_

Sorry, it was issue #812

**Comment by spyder-issues-migrator** [comment]
_From [nunoport...@gmail.com](https://code.google.com/u/108617919618299841919/) on 2011-12-05T07:38:22Z_

the output from 

\>>> import locale
\>>> locale.getpreferredencoding()

is:

cp1252

i want to ask you if you could please supply me the original "baseconfig.py" and "p_profiler.py" files. because i'm not sure of which modifications i have made so far... i didn't backup my files... so i can work from there...

I also made the modifications suggested on issue #146 , don't know if this could be a problem....

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-05T08:11:06Z_

To restore baseconfig.py, use this version: https://code.google.com/p/spyderlib/source/browse/spyderlib/baseconfig.py?spec=svn3cc963d4f26f83f80557205d17b89a98d9460741&r=ae3269b7aceb8d282ff5b900d900d5106b5d2752

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-12-05T08:11:48Z_

Don't worry Nuno, let's wait until Pierre restore baseconfig.py

Could you do me another favor? Please evaluate these commands and tell what you get:

\>>> from spyderlib.utils.module_completion import MODULES_PATH
\>>> from spyderlib.utils.external.pickleshare import PickleShareDB
\>>> PickleShareDB(MODULES_PATH)

Thanks

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-05T08:16:56Z_

Carlos, I think that my second (horrible) fix for this issue was causing the same error that you fixed recently only because I was changing path from str to unicode, that's all. I'm quite convinced that if my last proposal is implemented, there won't be any other similar issue, at least with the "external.path" library.

**Comment by spyder-issues-migrator** [comment]
_From [nunoport...@gmail.com](https://code.google.com/u/108617919618299841919/) on 2011-12-05T08:19:39Z_

i think i'll just unistall and do a fresh installation and proceed from there...

meanwhile i did as you requested, the output is:

PickleShareDB('C:\Users\Nuno Gonþalves\.spyder2\db')

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-12-05T08:26:14Z_

Nuno, thanks for your patience too and for handling all our requests almost instantly :)

Ok Pierre, I'll let you handle it. I thought it was horrible issue #812 hitting us again and I wanted to squash it once and for all! ;)

**Comment by spyder-issues-migrator** [comment]
_From [nunoport...@gmail.com](https://code.google.com/u/108617919618299841919/) on 2011-12-05T09:12:31Z_

Unistalled pythonxy and installed again (now with backups!!), modified files as in issue #146 so i can open pythonxy and spyder, also modified p_profiler.py as suggested in comment 13 and 14 but still no good...

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-05T09:45:01Z_

Please note that you don't need to uninstall/reinstall the whole Python(x,y) distribution: Spyder, as all other Python(x,y) plugins, is available as a stand-alone plugin that you may upgrade independantly from the whole distribution.

So, are you using the very last version (i.e. v2.1.4) or the current stable release (v2.1.2)?
Here it is (if you are using Python 2.7): https://code.google.com/p/spyderlib/downloads/detail?name=spyder-2.1.4_py27.exe On top of v2.1.4's spyderplugins/p_profiler.py, you may replace:

"are stored here:"
)+("\n%s\n" % ProfilerWidget.DATAPATH))

by:

"are stored here:\n%s\n" % ProfilerWidget.DATAPATH))

And if it does not work, please specify if:
1. this is the original bug (UnicodeDecodeError in spyderplugins/p_profiler.py)
2. this is the other bug (UnicodeEncodeError in spyderlib\utils\external\pickleshare.py)
3. another one: please join the traceback

I'm joining Carlos to thank you again for your help regarding this issue.

**Comment by spyder-issues-migrator** [comment]
_From [nunoport...@gmail.com](https://code.google.com/u/108617919618299841919/) on 2011-12-06T02:28:05Z_

Hi, I've upgraded Spyder for 2.1.4 version and patch it as you suggested. i got a different bug, not the original and not the pickleshare bug... :S 


 Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 1617, in edit_p
references
    widget = plugin.create_configwidget(dlg)
  File "C:\Python27\lib\site-packages\spyderlib\plugins\__init__.py", line 155,
in create_configwidget
    configwidget.initialize()
  File "C:\Python27\lib\site-packages\spyderlib\plugins\configdialog.py", line 4
5, in initialize
    self.setup_page()
  File "C:\Python27\lib\site-packages\spyderplugins\p_profiler.py", line 35, in
setup_page
    "are stored here:\n%s\n" % ProfilerWidget.DATAPATH))
  File "C:\Python27\lib\site-packages\spyderlib\baseconfig.py", line 124, in tra
nslate_dumb
    return unicode(x, "utf-8")
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe7 in position 100: invalid
 continuation byte

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-06T03:17:11Z_

Could you please do the following changes:
1. Try to move the closing parenthesis from the right of % Profiler.DATAPATH to its left:
replace this:
" % Profiler.DATAPATH)
by this:
") % Profiler.DATAPATH

2. If there is still an error, please post the traceback, and as a last resort, comment the lines that mentioned in comment 13 (see above) to check I there will be other bugs once this one is fixed.

**Comment by spyder-issues-migrator** [comment]
_From [nunoport...@gmail.com](https://code.google.com/u/108617919618299841919/) on 2011-12-06T04:37:55Z_

1 - I guess you meant to say to modify the line % ProfilerWidget.DATAPATH... but still no good.

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 1617, in edit_p
references
    widget = plugin.create_configwidget(dlg)
  File "C:\Python27\lib\site-packages\spyderlib\plugins\__init__.py", line 155,
in create_configwidget
    configwidget.initialize()
  File "C:\Python27\lib\site-packages\spyderlib\plugins\configdialog.py", line 4
5, in initialize
    self.setup_page()
  File "C:\Python27\lib\site-packages\spyderplugins\p_profiler.py", line 35, in
setup_page
    "are stored here:\n%s\n" ) % ProfilerWidget.DATAPATH )
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 17: ordinal
 not in range(128)

2 - Commented lines 32-42... 

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 1617, in edit_p
references
    widget = plugin.create_configwidget(dlg)
  File "C:\Python27\lib\site-packages\spyderlib\plugins\__init__.py", line 155,
in create_configwidget
    configwidget.initialize()
  File "C:\Python27\lib\site-packages\spyderlib\plugins\configdialog.py", line 4
5, in initialize
    self.setup_page()
  File "C:\Python27\lib\site-packages\spyderplugins\p_profiler.py", line 44, in
setup_page
    vlayout.addWidget(results_group)
NameError: global name 'results_group' is not defined

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-06T06:24:42Z_

Let's comment this line too (starting with vlayout.).

**Comment by spyder-issues-migrator** [comment]
_From [nunoport...@gmail.com](https://code.google.com/u/108617919618299841919/) on 2011-12-06T06:33:18Z_

i have 3 lines starting with vlayout, commented just the first got error, commented the 3 and got another error message.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-06T09:10:03Z_

Ok, actually you may simply remove the 'p_profiler.py' file and see what happens.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-06T09:11:35Z_

By the way, thanks again for your help.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-06T09:13:36Z_

After removing that file, you might have the exact same error with p_pylint.py. If this happens, simply remove this file too. And check if everything else works fine.

**Comment by spyder-issues-migrator** [comment]
_From [nunoport...@gmail.com](https://code.google.com/u/108617919618299841919/) on 2011-12-06T09:34:17Z_

Problem solved! :) There is nothing more effective than deleting what's causing the problems!! 

will this solution interfere with any other functions on spyder?

Thanks again for your patience and availability for solving this issue!

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-06T10:04:22Z_

You didn't mention if it was necessary to remove p_pylint.py as well. Was it necessary?

Anyway, by removing these two files, you have removed the two corresponding features: the Profiler plugin (code profiling) and the Pylint plugin (code analysis).

But this is only temporary. We will be able to restore those files once the problem is solved. And apparently this is only a display issue (both Profiler and Pylint plugin show the path of their configuration file in the Preferences dialog box), so I should come with a working fix rapidly (hopefully).

**Comment by spyder-issues-migrator** [comment]
_From [nunoport...@gmail.com](https://code.google.com/u/108617919618299841919/) on 2011-12-06T10:54:28Z_

You're right i forgot... :)

Yes, after removing p_profiler.py a p_pylint.py error came up so i removed it too.

Without pylint i'm not able to see if my code has errors before i run it? is this correct?

I hope you can find a fix for this! 

Thank you

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-06T12:57:06Z_

The Pylint plugin is for deep code analysis. The real-time code analysis is powered by the `rope` library. So you will be able to see errors/warnings in your source code.

Could you please try those versions of p_pylint.py and p_profiler.py?

**Attachment:** [p_profiler.py p_pylint.py](http://code.google.com/p/spyderlib/issues/detail?id=863#hc37)

**Comment by spyder-issues-migrator** [comment]
_From [nunoport...@gmail.com](https://code.google.com/u/108617919618299841919/) on 2011-12-06T13:37:48Z_

The files you supplied work fine so far! 

Thanks

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-06T13:41:59Z_

Ok, great news!

I'll commit those changes very soon. 

Thanks again!

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-06T22:39:57Z_

This issue was closed by revision 1fab090898e2 .

**Status:** Fixed
