### ISSUE TITLE
An Error occured while starting the kernel

### ISSUE THREAD

**Issue by MayankMadhav13** [spyder-ide/spyder#8638]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE
Traceback (most recent call last):
File "C:\Users\MAYANK\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\MAYANK\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\MAYANK\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\MAYANK\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 279, in main
import_spydercustomize()
File "C:\Users\MAYANK\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 39, in import_spydercustomize
import spydercustomize
File "C:\Users\MAYANK\Anaconda3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 25, in 
from IPython.core.getipython import get_ipython
File "C:\Users\MAYANK\Anaconda3\lib\site‑packages\IPython\__init__.py", line 54, in 
from .core.application import Application
File "C:\Users\MAYANK\Anaconda3\lib\site‑packages\IPython\core\application.py", line 25, in 
from IPython.core import release, crashhandler
File "C:\Users\MAYANK\Anaconda3\lib\site‑packages\IPython\core\crashhandler.py", line 27, in 
from IPython.core import ultratb
File "C:\Users\MAYANK\Anaconda3\lib\site‑packages\IPython\core\ultratb.py", line 119, in 
from IPython.utils import path as util_path
File "C:\Users\MAYANK\Anaconda3\lib\site‑packages\IPython\utils\path.py", line 17, in 
from IPython.utils.process import system
File "C:\Users\MAYANK\Anaconda3\lib\site‑packages\IPython\utils\process.py", line 15, in 
from ._process_win32 import system, getoutput, arg_split, check_pid
File "C:\Users\MAYANK\Anaconda3\lib\site‑packages\IPython\utils\_process_win32.py", line 20, in 
import ctypes
File "C:\Users\MAYANK\Anaconda3\lib\ctypes\__init__.py", line 7, in 
from _ctypes import Union, Structure, Array
ImportError: Module use of python27.dll conflicts with this version of Python.
```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Did you add a Python 2 conda environment or separate installation to your PYTHONPATH environment variable? Or perhaps by using our PYTHONPATH manager?

**Comment by ccordoba12** [comment]
Closing because of lack of response.
