### ISSUE TITLE
Python 3.7 Spyder Console Error: An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by FreshWindSailor** [spyder-ide/spyder#8669]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

My Python 3.7 Spyder Console shows the Error Message:  An error ocurred while starting the kernel

### What steps reproduce the problem?

1. Open and Close Anaconda Navigator and Spyder 
2. Restart Computer 
3. Following Recommendations as listed in Troubleshooting Guide etc. 

### What is the expected output? What do you see instead?

Console in Spyder shows this:  
An error ocurred while starting the kernel
Traceback (most recent call last):
File "C:\Users\Bernd\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\Bernd\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\Bernd\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\Bernd\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 298, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\Bernd\Anaconda3\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\Bernd\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 484, in initialize
self.init_kernel()
File "C:\Users\Bernd\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 389, in init_kernel
user_ns=self.user_ns,
File "C:\Users\Bernd\Anaconda3\lib\site‑packages\traitlets\config\configurable.py", line 412, in instance
inst = cls(*args, **kwargs)
File "C:\Users\Bernd\Anaconda3\lib\site‑packages\spyder_kernels\console\kernel.py", line 37, in __init__
super(SpyderKernel, self).__init__(*args, **kwargs)
File "C:\Users\Bernd\Anaconda3\lib\site‑packages\ipykernel\ipkernel.py", line 67, in __init__
kernel = self,
File "C:\Users\Bernd\Anaconda3\lib\site‑packages\traitlets\config\configurable.py", line 412, in instance
inst = cls(*args, **kwargs)
File "C:\Users\Bernd\Anaconda3\lib\site‑packages\IPython\core\interactiveshell.py", line 679, in __init__
self.init_magics()
File "C:\Users\Bernd\Anaconda3\lib\site‑packages\ipykernel\zmqshell.py", line 593, in init_magics
super(ZMQInteractiveShell, self).init_magics()
File "C:\Users\Bernd\Anaconda3\lib\site‑packages\IPython\core\interactiveshell.py", line 2223, in init_magics
m.NamespaceMagics, m.OSMagics, m.PylabMagics, m.ScriptMagics,
File "C:\Users\Bernd\Anaconda3\lib\site‑packages\IPython\core\magic.py", line 386, in register
m = m(shell=self.shell)
File "C:\Users\Bernd\Anaconda3\lib\site‑packages\IPython\core\magics\osm.py", line 52, in __init__
self.execre = re.compile(r'(.*)\.(%s)$' % winext,re.IGNORECASE)
File "C:\Users\Bernd\Anaconda3\lib\re.py", line 234, in compile
return _compile(pattern, flags)
File "C:\Users\Bernd\Anaconda3\lib\re.py", line 286, in _compile
p = sre_compile.compile(pattern, flags)
File "C:\Users\Bernd\Anaconda3\lib\sre_compile.py", line 764, in compile
p = sre_parse.parse(p, flags)
File "C:\Users\Bernd\Anaconda3\lib\sre_parse.py", line 930, in parse
p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
File "C:\Users\Bernd\Anaconda3\lib\sre_parse.py", line 426, in _parse_sub
not nested and not items))
File "C:\Users\Bernd\Anaconda3\lib\sre_parse.py", line 816, in _parse
p = _parse_sub(source, state, sub_verbose, nested + 1)
File "C:\Users\Bernd\Anaconda3\lib\sre_parse.py", line 426, in _parse_sub
not nested and not items))
File "C:\Users\Bernd\Anaconda3\lib\sre_parse.py", line 507, in _parse
code = _escape(source, this, state)
File "C:\Users\Bernd\Anaconda3\lib\sre_parse.py", line 402, in _escape
raise source.error("bad escape %s" % escape, len(escape))
re.error: bad escape \P at position 52

### Paste Traceback/Error Below (if applicable)

```python-traceback

Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> WARNING:traitlets:kernel restarted
WARNING:traitlets:kernel restarted
WARNING:traitlets:kernel restarted
WARNING:traitlets:kernel restarted
WARNING:traitlets:KernelRestarter: restart failed
WARNING:traitlets:kernel died: 18.01023769378662
WARNING:traitlets:kernel died: 18.009416580200195
WARNING:traitlets:kernel died: 18.014978170394897
WARNING:traitlets:kernel died: 18.01053261756897
WARNING:traitlets:kernel died: 18.00669264793396
WARNING:traitlets:kernel died: 18.010286569595337
WARNING:traitlets:kernel died: 18.004303693771362
WARNING:traitlets:kernel died: 18.009784936904907
WARNING:traitlets:kernel died: 18.012989282608032
WARNING:traitlets:kernel died: 18.00294065475464
WARNING:traitlets:kernel died: 18.011216402053833
WARNING:traitlets:kernel died: 18.003687858581543
WARNING:traitlets:kernel died: 18.002440214157104
WARNING:traitlets:kernel died: 18.004209995269775
WARNING:traitlets:kernel died: 18.00095224380493
WARNING:traitlets:kernel died: 18.00247049331665


```

## Versions

* Spyder version: 3.3.2
* Python version: 3.7.1 64-bit
* Qt version: Qt 5.9.6
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Windows 8.1

### Dependencies

```
IPython >=4.0     :  7.2.0 (OK)
cython >=0.21     :  0.29.2 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
numpy >=1.7       :  1.15.4 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.2.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
sympy >=0.7.3     :  1.3 (OK)

```

**Comment by ccordoba12** [comment]
> File "C:\Users\Bernd\Anaconda3\lib\sre_parse.py", line 402, in _escape
raise source.error("bad escape %s" % escape, len(escape))
re.error: bad escape \P at position 52

This error is very, very strange. The only thing I can recommend you is to reinstall Anaconda because it seems somehow your current installation was corrupted (I don't understand how that could have happened but it's the only possible explanation for me).

**Comment by FreshWindSailor** [comment]
I re-installed Anaconda 3-4 times.  I also tried WinPython.  What seems to work -- I am new to Python -- is PyCharm.  No problems with it so far.

**Comment by ccordoba12** [comment]
Sorry for not being more helpful but I have no more advice to offer you.

**Comment by shubham2k6** [comment]
please help on the error. I have tried reinstalling anaconda, resetting spyder:

Traceback (most recent call last):
File "/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 289, in main
from ipykernel.kernelapp import IPKernelApp
File "/anaconda3/lib/python3.7/site‑packages/ipykernel/kernelapp.py", line 37, in 
from .iostream import IOPubThread
File "/anaconda3/lib/python3.7/site‑packages/ipykernel/iostream.py", line 25, in 
from jupyter_client.session import extract_header
File "/anaconda3/lib/python3.7/site‑packages/jupyter_client/session.py", line 61, in 
from jupyter_client.jsonutil import extract_dates, squash_dates, date_default
File "/anaconda3/lib/python3.7/site‑packages/jupyter_client/jsonutil.py", line 11, in 
from dateutil.parser import parse as _dateutil_parse
File "/anaconda3/lib/python3.7/site‑packages/dateutil/parser/__init__.py", line 2, in 
from ._parser import parse, parser, parserinfo
File "/anaconda3/lib/python3.7/site‑packages/dateutil/parser/_parser.py", line 45, in 
from decimal import Decimal
File "/anaconda3/lib/python3.7/decimal.py", line 3, in 
from _decimal import *
AttributeError: module 'numbers' has no attribute 'Number'

**Comment by ananyamaurya** [comment]
The error occurred with me when I changed the settings in Preferences -> Current Working Directory
when I changed it back to ( The Current project directory or user home directory )
The error didn't show up...
That surmise Spyder require the working directory at startup to be user's home directory if no project is active.
i.e,  C:\Users\user_name\.spyder-py3   (the directory where spyder's installed components are)

Otherwise the above error with occur.

**Comment by namanchauhan8998** [comment]
Traceback (most recent call last):
File "C:\Users\naman\anaconda3\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\naman\anaconda3\lib\site-packages\spyder\app\start.py", line 205, in main
mainwindow.main()
File "C:\Users\naman\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3763, in main
mainwindow = run_spyder(app, options, args)
File "C:\Users\naman\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3638, in run_spyder
main.setup()
File "C:\Users\naman\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 945, in setup
from spyder.plugins.ipythonconsole.plugin import IPythonConsole
File "C:\Users\naman\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 46, in 
from spyder.plugins.ipythonconsole.widgets import (ClientWidget,
File "C:\Users\naman\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\__init__.py", line 16, in 
from .debugging import DebuggingWidget
File "C:\Users\naman\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 15, in 
from IPython.core.history import HistoryManager
File "C:\Users\naman\anaconda3\lib\site-packages\IPython\__init__.py", line 56, in 
from .terminal.embed import embed
File "C:\Users\naman\anaconda3\lib\site-packages\IPython\terminal\embed.py", line 16, in 
from IPython.terminal.interactiveshell import TerminalInteractiveShell
File "C:\Users\naman\anaconda3\lib\site-packages\IPython\terminal\interactiveshell.py", line 19, in 
from prompt_toolkit.enums import DEFAULT_BUFFER, EditingMode
ModuleNotFoundError: No module named 'prompt_toolkit'

**Comment by ccordoba12** [comment]
@namanchauhan8998, you probably need to reinstall Anaconda. Please see [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) on how to solve this kind of problems.
