### ISSUE TITLE
Error - 'an error occurred while starting the kernnel'.

### ISSUE THREAD

**Issue by avm5998** [spyder-ide/spyder#8670]
### What steps will reproduce the problem?

Installed Anaconda after uninstalling and reinstalling it a couple of times.The reason for this was that Jupyter notebook wasn't opening.Opened Spyder immidiately after installing anaconda and this error msg is thrown at me.
It starts with 
' Traceback (most recent call last) '

### Traceback
```python-traceback
  File "C:\Users\Atharva\Anaconda3\lib\site-packages\qtconsole\manager.py", line 27, in poll
    super(QtKernelRestarter, self).poll()
  File "C:\Users\Atharva\Anaconda3\lib\site-packages\jupyter_client\restarter.py", line 113, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "C:\Users\Atharva\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 368, in restart_kernel
    self.start_kernel(**self._launch_args)
  File "C:\Users\Atharva\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
    **kw)
  File "C:\Users\Atharva\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Users\Atharva\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 138, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Users\Atharva\Anaconda3\lib\subprocess.py", line 658, in __init__
    _cleanup()
  File "C:\Users\Atharva\Anaconda3\lib\subprocess.py", line 228, in _cleanup
    res = inst._internal_poll(_deadstate=sys.maxsize)
  File "C:\Users\Atharva\Anaconda3\lib\subprocess.py", line 1210, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
PermissionError: [WinError 5] Access is denied
```

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
> The reason for this was that Jupyter notebook wasn't opening

Well, Jupyter and Spyder use the same technology so you have to solve the same problem for both.

> File "C:\Users\Atharva\Anaconda3\lib\subprocess.py", line 1210, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
PermissionError: [WinError 5] Access is denied

This is probably a problem with your firewall/antivirus preventing Python to launch an external process. Please turn them off and try again.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
