### ISSUE TITLE
problem during startup

### ISSUE THREAD

**Issue by menzeln** [spyder-ide/spyder#8688]
### What steps will reproduce the problem?

Start the application. (Actually, no idea what happend, I have started spyder and the error message appeared without me interacting with the program in any way.)

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 110, in _save
    _write_file(fname)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 106, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\menze\\.spyder-py3\\spyder.ini'

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\__init__.py", line 514, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 766, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1096, in create_new_client
    self.connect_client_to_kernel(client, is_cython=is_cython)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1124, in connect_client_to_kernel
    is_cython=is_cython)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1520, in create_kernel_manager_and_kernel_client
    kernel_spec = self.create_kernel_spec(is_cython=is_cython)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1513, in create_kernel_spec
    self.main.get_spyder_pythonpath())
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 445, in set
    self._save()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 120, in _save
    raise(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 114, in _save
    os.remove(fname)
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'C:\\Users\\menze\\.spyder-py3\\spyder.ini'
```

## Versions

* Spyder version: 3.3.1 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.2). Please update by opening the Anaconda Prompt and running there

    conda update spyder
