### ISSUE TITLE
Anaconda/Spyder won't launch

### ISSUE THREAD

**Issue by PinguIT** [spyder-ide/spyder#8698]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ X] Tried basic troubleshooting (if a bug/error)
    * [X ] Restarted Spyder
    * [X ] Reset preferences with ``spyder --reset``
    * [ X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ X] Tried the other applicable steps from the Troubleshooting Guide
* [ X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Anaconda Navigator doesn't launch and Spyder says it crashed during the last session but does not launch either.

### What steps reproduce the problem?

1. Attempting to launch Spyder (crash)
2. Attempting to launch Anaconda (nothing happens)
3. 

### What is the expected output? What do you see instead?
![image](https://user-images.githubusercontent.com/15250743/52177464-5cc38680-27c1-11e9-9d68-91148dee37f8.png)

### Paste Traceback/Error Below (if applicable)

```python-traceback

(base) C:\ProgramData\Anaconda3\pkgs\spyder-3.3.2-py37_0\Lib\site-packages\spyder\app>python start.py
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\external\github.py", line 51, in <module>
    from urllib2 import build_opener, HTTPSHandler, Request, HTTPError
ModuleNotFoundError: No module named 'urllib2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3284, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3139, in run_spyder
    main.setup()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 809, in setup
    from spyder.plugins.console import Console
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\console.py", line 37, in <module>
    from spyder.widgets.reporterror import SpyderErrorDialog
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\reporterror.py", line 26, in <module>
    from spyder.widgets.github.backend import GithubBackend
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\github\backend.py", line 33, in <module>
    from spyder.utils.external import github
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\external\github.py", line 58, in <module>
    from urllib.request import build_opener, HTTPSHandler, HTTPError, Request
ImportError: cannot import name 'HTTPSHandler' from 'urllib.request' (C:\ProgramData\Anaconda3\lib\urllib\request.py)

(base) C:\ProgramData\Anaconda3\pkgs\spyder-3.3.2-py37_0\Lib\site-packages\spyder\app>python mainwindow.py
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\external\github.py", line 51, in <module>
    from urllib2 import build_opener, HTTPSHandler, Request, HTTPError
ModuleNotFoundError: No module named 'urllib2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mainwindow.py", line 3284, in main
    mainwindow = run_spyder(app, options, args)
  File "mainwindow.py", line 3139, in run_spyder
    main.setup()
  File "mainwindow.py", line 809, in setup
    from spyder.plugins.console import Console
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\console.py", line 37, in <module>
    from spyder.widgets.reporterror import SpyderErrorDialog
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\reporterror.py", line 26, in <module>
    from spyder.widgets.github.backend import GithubBackend
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\github\backend.py", line 33, in <module>
    from spyder.utils.external import github
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\external\github.py", line 58, in <module>
    from urllib.request import build_opener, HTTPSHandler, HTTPError, Request
ImportError: cannot import name 'HTTPSHandler' from 'urllib.request' (C:\ProgramData\Anaconda3\lib\urllib\request.py)


```

## Versions

* Spyder version: 3.3.2
* Python version: 3.7.1
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 Home 64 bit

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Please reinstall Anaconda because it seems your current installation is corrupted.
