### ISSUE TITLE
spyder won't launch after upgrade

### ISSUE THREAD

**Issue by lihaooooo** [spyder-ide/spyder#8699]
Spyder cannot launch in Anaconda after I upgraded Anaconda and Spyder. Here's the info that I got:

Traceback (most recent call last):
File "/Users/lihao/anaconda3/bin/spyder", line 7, in 
from spyder.app.start import main
File "/Users/lihao/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 35, in 
from spyder.config.main import CONF
File "/Users/lihao/anaconda3/lib/python3.6/site-packages/spyder/config/main.py", line 22, in 
from spyder.config.user import UserConfig
File "/Users/lihao/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 26, in 
from spyder.utils.programs import check_version
File "/Users/lihao/anaconda3/lib/python3.6/site-packages/spyder/utils/programs.py", line 18, in 
import subprocess
File "/Users/lihao/anaconda3/lib/python3.6/subprocess.py", line 136, in 
import _posixsubprocess
ImportError: dlopen(/Users/lihao/anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so, 2): Symbol not found: __Py_set_inheritable_async_safe
Referenced from: /Users/lihao/anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so
Expected in: flat namespace
in /Users/lihao/anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so

**Comment by ccordoba12** [comment]
Please run in Terminal.app

    conda update python.app
