### ISSUE TITLE
Spyder crash or error on IPython console

### ISSUE THREAD

**Issue by daybreak0901** [spyder-ide/spyder#8725]
### What steps will reproduce the problem?

An error ocurred while starting the kernel！
Hello everyone, I am a newcomer to Python. I just downloaded anaconda3 from the website, but every time I open the spyder, the spyder crashes. After a while, the spyder can be opened, but the IPython console reports an error.
I don't know where the problem is. I am using the windows10 operating system. I have tried upgrading the spyder and anaconda, reset spyder, restarting my computer, and uninstalling and reinstalling anaconda, but it doesn't work.
I have been entangled in this issue for two days, which makes me feel bad now, I hope that experienced people can give me some advice and help! Thank you very much!

### Traceback
```python-traceback
  File "F:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'context'

Traceback (most recent call last):
  File "F:\Anaconda3\lib\site-packages\qtconsole\manager.py", line 27, in poll
    super(QtKernelRestarter, self).poll()
  File "F:\Anaconda3\lib\site-packages\jupyter_client\restarter.py", line 113, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "F:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 368, in restart_kernel
    self.start_kernel(**self._launch_args)
  File "F:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 261, in start_kernel
    self._connect_control_socket()
  File "F:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 210, in _connect_control_socket
    self._control_socket = self.connect_control()
  File "F:\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 571, in connect_control
    return self._create_connected_socket('control', identity=identity)
  File "F:\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 543, in _create_connected_socket
    sock = self.context.socket(socket_type)
  File "F:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "F:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "F:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 42, in _context_default
    return zmq.Context.instance()
  File "F:\Anaconda3\lib\site-packages\zmq\sugar\context.py", line 108, in instance
    cls._instance = cls(io_threads=io_threads)
  File "zmq/backend/cython/context.pyx", line 49, in zmq.backend.cython.context.Context.__cinit__
zmq.error.ZMQError: Unknown error
Traceback (most recent call last):
  File "F:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'context'

Traceback (most recent call last):
  File "F:\Anaconda3\lib\site-packages\qtconsole\manager.py", line 27, in poll
    super(QtKernelRestarter, self).poll()
  File "F:\Anaconda3\lib\site-packages\jupyter_client\restarter.py", line 113, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "F:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 368, in restart_kernel
    self.start_kernel(**self._launch_args)
  File "F:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 261, in start_kernel
    self._connect_control_socket()
  File "F:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 210, in _connect_control_socket
    self._control_socket = self.connect_control()
  File "F:\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 571, in connect_control
    return self._create_connected_socket('control', identity=identity)
  File "F:\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 543, in _create_connected_socket
    sock = self.context.socket(socket_type)
  File "F:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "F:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "F:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 42, in _context_default
    return zmq.Context.instance()
  File "F:\Anaconda3\lib\site-packages\zmq\sugar\context.py", line 108, in instance
    cls._instance = cls(io_threads=io_threads)
  File "zmq/backend/cython/context.pyx", line 49, in zmq.backend.cython.context.Context.__cinit__
zmq.error.ZMQError: Unknown error
Traceback (most recent call last):
  File "F:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'context'

Traceback (most recent call last):
  File "F:\Anaconda3\lib\site-packages\qtconsole\manager.py", line 27, in poll
    super(QtKernelRestarter, self).poll()
  File "F:\Anaconda3\lib\site-packages\jupyter_client\restarter.py", line 113, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "F:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 368, in restart_kernel
    self.start_kernel(**self._launch_args)
  File "F:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 261, in start_kernel
    self._connect_control_socket()
  File "F:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 210, in _connect_control_socket
    self._control_socket = self.connect_control()
  File "F:\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 571, in connect_control
    return self._create_connected_socket('control', identity=identity)
  File "F:\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 543, in _create_connected_socket
    sock = self.context.socket(socket_type)
  File "F:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "F:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "F:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 42, in _context_default
    return zmq.Context.instance()
  File "F:\Anaconda3\lib\site-packages\zmq\sugar\context.py", line 108, in instance
    cls._instance = cls(io_threads=io_threads)
  File "zmq/backend/cython/context.pyx", line 49, in zmq.backend.cython.context.Context.__cinit__
zmq.error.ZMQError: Unknown error
Traceback (most recent call last):
  File "F:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'context'

Traceback (most recent call last):
  File "F:\Anaconda3\lib\site-packages\qtconsole\manager.py", line 27, in poll
    super(QtKernelRestarter, self).poll()
  File "F:\Anaconda3\lib\site-packages\jupyter_client\restarter.py", line 113, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "F:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 368, in restart_kernel
    self.start_kernel(**self._launch_args)
  File "F:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 261, in start_kernel
    self._connect_control_socket()
  File "F:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 210, in _connect_control_socket
    self._control_socket = self.connect_control()
  File "F:\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 571, in connect_control
    return self._create_connected_socket('control', identity=identity)
  File "F:\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 543, in _create_connected_socket
    sock = self.context.socket(socket_type)
  File "F:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "F:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "F:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 42, in _context_default
    return zmq.Context.instance()
  File "F:\Anaconda3\lib\site-packages\zmq\sugar\context.py", line 108, in instance
    cls._instance = cls(io_threads=io_threads)
  File "zmq/backend/cython/context.pyx", line 49, in zmq.backend.cython.context.Context.__cinit__
zmq.error.ZMQError: Unknown error
Traceback (most recent call last):
  File "F:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'context'

Traceback (most recent call last):
  File "F:\Anaconda3\lib\site-packages\qtconsole\manager.py", line 27, in poll
    super(QtKernelRestarter, self).poll()
  File "F:\Anaconda3\lib\site-packages\jupyter_client\restarter.py", line 113, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "F:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 368, in restart_kernel
    self.start_kernel(**self._launch_args)
  File "F:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 261, in start_kernel
    self._connect_control_socket()
  File "F:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 210, in _connect_control_socket
    self._control_socket = self.connect_control()
  File "F:\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 571, in connect_control
    return self._create_connected_socket('control', identity=identity)
  File "F:\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 543, in _create_connected_socket
    sock = self.context.socket(socket_type)
  File "F:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "F:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "F:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 42, in _context_default
    return zmq.Context.instance()
  File "F:\Anaconda3\lib\site-packages\zmq\sugar\context.py", line 108, in instance
    cls._instance = cls(io_threads=io_threads)
  File "zmq/backend/cython/context.pyx", line 49, in zmq.backend.cython.context.Context.__cinit__
zmq.error.ZMQError: Unknown error
Traceback (most recent call last):
```

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.0
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
We think this is related to your firewall or antivirus, so please deactivate them and try again.

If you also denied `python.exe` permissions to be executed while Spyder was starting (something that it's blocked by Windows Defender), you'll get this error too.

Other than this, we don't have more advice to give you, sorry.
