### ISSUE TITLE
error while starting kernel

### ISSUE THREAD

**Issue by abhi123321** [spyder-ide/spyder#8750]
The error is:

Traceback (most recent call last):
File "C:\Users\dell\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 528, in get
value = obj._trait_values[self.name]
KeyError: 'context'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\dell\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1554, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\dell\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 261, in start_kernel
self._connect_control_socket()
File "C:\Users\dell\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 210, in _connect_control_socket
self._control_socket = self.connect_control()
File "C:\Users\dell\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 571, in connect_control
return self._create_connected_socket('control', identity=identity)
File "C:\Users\dell\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 543, in _create_connected_socket
sock = self.context.socket(socket_type)
File "C:\Users\dell\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 556, in __get__
return self.get(obj, cls)
File "C:\Users\dell\Anaconda3\lib\site‑packages\traitlets\traitlets.py", line 535, in get
value = self._validate(obj, dynamic_default())
File "C:\Users\dell\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 42, in _context_default
return zmq.Context.instance()
File "C:\Users\dell\Anaconda3\lib\site‑packages\zmq\sugar\context.py", line 108, in instance
cls._instance = cls(io_threads=io_threads)
File "zmq/backend/cython/context.pyx", line 49, in zmq.backend.cython.context.Context.__cinit__
zmq.error.ZMQError: Unknown error

**Comment by ccordoba12** [comment]
This is most probably caused by your firewall/antivirus, so please deactivate them and try again. Other than that, we don't know the cause for this, sorry.
