### ISSUE TITLE
Spyder runs but complains if PyQt isn't installed even when PySide is installed

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#876]
_From [jmtrup...@gmail.com](https://code.google.com/u/101831974170186564227/) on 2011-12-08T16:37:49Z_

What steps will reproduce the problem?

 1. Install Spyder with PySide and without PyQt
2. Run Spyder What is the expected output? What do you see instead? Spyder runs, but throws an exception in the console What version of the product are you using? On what operating system? Spyder 2.1.2 for Python 2.7 on W7 64 

Please provide any additional information below

. Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\startup.py", line 205, in \<module>
    __run_pythonstartup_script(globals())
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\startup.py", line 15, in __run_pythonstartup_script
    execfile(filename, namespace)
  File "C:\Python27\lib\site-packages\spyderlib\scientific_startup.py", line 14, in \<module>
    from pylab import *  #analysis:ignore
  File "C:\Python27\lib\site-packages\pylab.py", line 1, in \<module>
    from matplotlib.pylab import *
  File "C:\Python27\lib\site-packages\matplotlib\pylab.py", line 263, in \<module>
    from matplotlib.pyplot import *
  File "C:\Python27\lib\site-packages\matplotlib\pyplot.py", line 95, in \<module>
    new_figure_manager, draw_if_interactive, show = pylab_setup()
  File "C:\Python27\lib\site-packages\matplotlib\backends\__init__.py", line 25, in pylab_setup
    globals(),locals(),[backend_name])
  File "C:\Python27\lib\site-packages\matplotlib\backends\backend_qt4agg.py", line 12, in \<module>
    from backend_qt4 import QtCore, QtGui, FigureManagerQT, FigureCanvasQT,\
  File "C:\Python27\lib\site-packages\matplotlib\backends\backend_qt4.py", line 18, in \<module>
    import matplotlib.backends.qt4_editor.figureoptions as figureoptions
  File "C:\Python27\lib\site-packages\matplotlib\backends\qt4_editor\figureoptions.py", line 12, in \<module>
    from PyQt4.QtGui import QIcon
ImportError: No module named PyQt4.QtGui

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=876_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-12T08:48:53Z_

This issue was updated by revision 3eb6025e31db .


This revision should fix this Issue or at least provide the necessary options to
come up with a workaround accessible to the end-user.
This needs to be tested on Linux: once someone has done the tests, please mark
the Issue as Verified.

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2011-12-12T13:04:57Z_

I guess you need to have matplotlib installed to test that. I can't remember any such warnings in Linux.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-12T13:14:10Z_

Yes, to test this, you need Matplotlib v1.1 which is PySide compatible.
