### ISSUE TITLE
cannot set WRITEABLE flag to True of this array

### ISSUE THREAD

**Issue by Sushanti99** [spyder-ide/spyder#8858]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Sushanti\vbn\lib\site-packages\spyder\utils\external\lockfile.py", line 150, in lock
    symlink(str(os.getpid()), self.name)
  File "C:\Users\Sushanti\vbn\lib\site-packages\spyder\utils\external\lockfile.py", line 88, in symlink
    rename(newlinkname, filename)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Sushanti\\.spyder-py3\\spyder.lock.1551265457042.newlink' -> 'C:\\Users\\Sushanti\\.spyder-py3\\spyder.lock'

Traceback (most recent call last):
  File "C:\Users\Sushanti\vbn\lib\site-packages\spyder\utils\external\lockfile.py", line 177, in lock
    kill(int(pid), 0)
  File "C:\Users\Sushanti\vbn\lib\site-packages\spyder\utils\external\lockfile.py", line 72, in kill
    raise OSError(errno.ESRCH, None)
ProcessLookupError: [Errno 3] None

Traceback (most recent call last):
  File "C:\Users\Sushanti\vbn\lib\site-packages\spyder\app\start.py", line 114, in main
    lock_created = lock.lock()
  File "C:\Users\Sushanti\vbn\lib\site-packages\spyder\utils\external\lockfile.py", line 196, in lock
    rmlink(self.name)
  File "C:\Users\Sushanti\vbn\lib\site-packages\spyder\utils\external\lockfile.py", line 108, in rmlink
    os.rmdir(filename)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Sushanti\\.spyder-py3\\spyder.lock'

Traceback (most recent call last):
  File "C:\Users\Sushanti\vbn\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 455, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "C:\Users\Sushanti\vbn\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 610, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.1
* Qt Versions: 5.9.6, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.16.1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.3). Please update by opening the Anaconda Prompt and running there

    conda update spyder
