### ISSUE TITLE
Code completion in editor not working anymore in Spyder 2.1.5

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#886]
_From [jorisvan...@gmail.com](https://code.google.com/u/101707288318167035253/) on 2011-12-15T11:35:35Z_

What steps will reproduce the problem?

 1. Try to complete some code in the editor, for example the function np.array What is the expected output? What do you see instead? There appears no code completion balloon, not automatically, not with Ctrl-space. I also noticed that the object inspector is not updated for functions in the editor.

Everything is working fine in the console.

I just noticed it today that it isn't working anymore, and I don't know what I could have done wrong to disable it (I checked the preferences, and code completion is checked). What version of the product are you using? On what operating system? Spyder 2.1.5 (I just did a hg pull -u), Ubuntu 11.10, Python 2.7

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=886_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-15T14:47:54Z_

Please update to the latest revision (by doing again `hg pull -u`): this will provides a simpler way to turn on the debug mode.

Then, turn on the debug mode by creating a non-empty environment variable named SPYDER_DEBUG.
This should generates a couple of .log files in your HOME directory. Please attached them here if they seem relevant. (rope.log should be the one of interest)

**Comment by spyder-issues-migrator** [comment]
_From [jorisvan...@gmail.com](https://code.google.com/u/101707288318167035253/) on 2011-12-15T16:01:27Z_

How do I do this exactly? First I was trying with something like
import os
os.environ['SPYDER_DEBUG'] = "True"

and then in the terminal with
export $SPYDER_DEBUG=True

but both doesn't seem to work.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-12-15T18:29:08Z_

I'm not seeing this issue with an updated trunk.

Joris, you can use 'hg bisect' to try to find when it stopped to work for you. Read the help for it, it's not that hard to use.

**Labels:** Cat-Editor

**Comment by spyder-issues-migrator** [comment]
_From [jorisvan...@gmail.com](https://code.google.com/u/101707288318167035253/) on 2011-12-17T02:18:56Z_

OK, it was working with export $SPYDER_DEBUG=True, but I was looking in the wrong place for the logging files (in .spyder2 in home, not just in home).

And the output was useful! This was in rope.log:


======================================
Logging time: Fri Dec 16 18:05:16 2011

======================================

Context
\-------

get_calltip_text

Traceback
\---------

Traceback (most recent call last):
  File "/home/joris/spyderlib/spyderlib/widgets/sourcecode/codeeditor.py", line 158, in get_calltip_text
    ignore_unknown=False, remove_self=True)
  File "/home/joris/spyderlib/rope/contrib/codeassist.py", line 93, in get_calltip
    pymodule = fixer.get_pymodule()
  File "/home/joris/spyderlib/rope/base/utils.py", line 10, in _wrapper
    setattr(self, name, func(self, *args, **kwds))
  File "/home/joris/spyderlib/rope/contrib/fixsyntax.py", line 42, in get_pymodule
    new_message)
ModuleSyntaxError: Syntax error in file \</media/DATA/bio-ingenieur/thesis/PAPER/analyse/validatie.py> line \<290>: 
Syntax errors in file /media/DATA/bio-ingenieur/thesis/PAPER/analyse/validatie.py:
  * line 280: invalid syntax ... fixed
  * line 290: invalid syntax ... raised!


Sot it seemed rope had a problem with some syntax error, and indeed, there was a 'Code analysis: invalid syntax' in my file. And for this reason, the code completion didn't work anymore. When I removed the invalid syntax, the code completion was working again.

So the issue is that code completion does not work when invalid syntax (somewhere else in the file) is present. 
Is this a bug, or normal behaviour of rope?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-21T13:36:48Z_

Yes, this is the expected behavior with rope default settings.
I'm changing them so that at maximum 3 syntax errors will be ignored.

BTW, this is then a duplicate of issue #542 .

**Status:** Duplicate  
  **Mergedinto:** 542
