### ISSUE TITLE
Can not double-click variable in variable explorer

### ISSUE THREAD

**Issue by ArronQiu** [spyder-ide/spyder#8883]
### What steps will reproduce the problem?

This window pops up when double-clicking a varialbe in variable explorer.

### Traceback
```python-traceback
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 476, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 620, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array
Traceback (most recent call last):
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 476, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 620, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array
```

## Versions

* Spyder version: 3.3.1 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.3). Please update by opening the Anaconda Prompt and running there

    conda update spyder
