### ISSUE TITLE
spyder console is not working

### ISSUE THREAD

**Issue by hadeeld7** [spyder-ide/spyder#8889]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
An error ocurred while starting the kernel 

### What steps reproduce the problem?

1. run the code 
2. imported random module
3. 

### What is the expected output? What do you see instead?

a code , but  i get error message

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
File "/Users/mac/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/Users/mac/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/Users/mac/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/Users/mac/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 279, in main
import_spydercustomize()
File "/Users/mac/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 39, in import_spydercustomize
import spydercustomize
File "/Users/mac/anaconda3/lib/python3.7/site‑packages/spyder_kernels/customize/spydercustomize.py", line 27, in 
from IPython.core.getipython import get_ipython
File "/Users/mac/anaconda3/lib/python3.7/site‑packages/IPython/__init__.py", line 55, in 
from .terminal.embed import embed
File "/Users/mac/anaconda3/lib/python3.7/site‑packages/IPython/terminal/embed.py", line 17, in 
from IPython.terminal.ipapp import load_default_config
File "/Users/mac/anaconda3/lib/python3.7/site‑packages/IPython/terminal/ipapp.py", line 28, in 
from IPython.core.magics import (
File "/Users/mac/anaconda3/lib/python3.7/site‑packages/IPython/core/magics/__init__.py", line 18, in 
from .code import CodeMagics, MacroToEdit
File "/Users/mac/anaconda3/lib/python3.7/site‑packages/IPython/core/magics/code.py", line 23, in 
from urllib.request import urlopen
File "/Users/mac/anaconda3/lib/python3.7/urllib/request.py", line 88, in 
import http.client
File "/Users/mac/anaconda3/lib/python3.7/http/client.py", line 72, in 
import email.message
File "/Users/mac/anaconda3/lib/python3.7/email/message.py", line 10, in 
import uu
File "/Users/mac/uu.py", line 9, in 
y=int(input('guess the number '))
EOFError: EOF when reading a line

```

## Versions

* Spyder version: 3.3.3
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
IPython >=4.0     :  7.2.0 (OK)
cython >=0.21     :  0.29.2 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
numpy >=1.7       :  1.15.4 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
psutil >=0.3      :  5.4.8 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.2.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
```

**Comment by ccordoba12** [comment]
Please remove or rename this file

    /Users/mac/uu.py

to something other than uu.py
