### ISSUE TITLE
I cant figure out how to make a new notebook for class

### ISSUE THREAD

**Issue by Wholinator** [spyder-ide/spyder#8902]
### What steps will reproduce the problem?

just make a new text file, rename it to .ipynb and try to open it

### Traceback
```python-traceback
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\reader.py", line 14, in parse_json
    nb_dict = json.loads(s, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_notebook\notebookplugin.py", line 374, in close_client
    nb_contents = nbformat.read(path, as_version=4)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\__init__.py", line 139, in read
    return read(f, as_version, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\__init__.py", line 141, in read
    return reads(fp.read(), as_version, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\__init__.py", line 74, in reads
    nb = reader.reads(s, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\reader.py", line 58, in reads
    nb_dict = parse_json(s, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\reader.py", line 17, in parse_json
    raise NotJSONError(("Notebook does not appear to be JSON: %r" % s)[:77] + "...")
nbformat.reader.NotJSONError: Notebook does not appear to be JSON: ''...
Traceback (most recent call last):
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\reader.py", line 14, in parse_json
    nb_dict = json.loads(s, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_notebook\notebookplugin.py", line 374, in close_client
    nb_contents = nbformat.read(path, as_version=4)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\__init__.py", line 139, in read
    return read(f, as_version, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\__init__.py", line 141, in read
    return reads(fp.read(), as_version, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\__init__.py", line 74, in reads
    nb = reader.reads(s, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\reader.py", line 58, in reads
    nb_dict = parse_json(s, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\reader.py", line 17, in parse_json
    raise NotJSONError(("Notebook does not appear to be JSON: %r" % s)[:77] + "...")
nbformat.reader.NotJSONError: Notebook does not appear to be JSON: ''...
Traceback (most recent call last):
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\reader.py", line 14, in parse_json
    nb_dict = json.loads(s, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_notebook\notebookplugin.py", line 374, in close_client
    nb_contents = nbformat.read(path, as_version=4)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\__init__.py", line 139, in read
    return read(f, as_version, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\__init__.py", line 141, in read
    return reads(fp.read(), as_version, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\__init__.py", line 74, in reads
    nb = reader.reads(s, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\reader.py", line 58, in reads
    nb_dict = parse_json(s, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\reader.py", line 17, in parse_json
    raise NotJSONError(("Notebook does not appear to be JSON: %r" % s)[:77] + "...")
nbformat.reader.NotJSONError: Notebook does not appear to be JSON: ''...
Traceback (most recent call last):
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\reader.py", line 14, in parse_json
    nb_dict = json.loads(s, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_notebook\notebookplugin.py", line 374, in close_client
    nb_contents = nbformat.read(path, as_version=4)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\__init__.py", line 139, in read
    return read(f, as_version, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\__init__.py", line 141, in read
    return reads(fp.read(), as_version, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\__init__.py", line 74, in reads
    nb = reader.reads(s, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\reader.py", line 58, in reads
    nb_dict = parse_json(s, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\reader.py", line 17, in parse_json
    raise NotJSONError(("Notebook does not appear to be JSON: %r" % s)[:77] + "...")
nbformat.reader.NotJSONError: Notebook does not appear to be JSON: ''...
Traceback (most recent call last):
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\reader.py", line 14, in parse_json
    nb_dict = json.loads(s, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_notebook\notebookplugin.py", line 374, in close_client
    nb_contents = nbformat.read(path, as_version=4)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\__init__.py", line 139, in read
    return read(f, as_version, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\__init__.py", line 141, in read
    return reads(fp.read(), as_version, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\__init__.py", line 74, in reads
    nb = reader.reads(s, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\reader.py", line 58, in reads
    nb_dict = parse_json(s, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\reader.py", line 17, in parse_json
    raise NotJSONError(("Notebook does not appear to be JSON: %r" % s)[:77] + "...")
nbformat.reader.NotJSONError: Notebook does not appear to be JSON: ''...
Traceback (most recent call last):
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\reader.py", line 14, in parse_json
    nb_dict = json.loads(s, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_notebook\notebookplugin.py", line 374, in close_client
    nb_contents = nbformat.read(path, as_version=4)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\__init__.py", line 139, in read
    return read(f, as_version, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\__init__.py", line 141, in read
    return reads(fp.read(), as_version, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\__init__.py", line 74, in reads
    nb = reader.reads(s, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\reader.py", line 58, in reads
    nb_dict = parse_json(s, **kwargs)
  File "C:\Users\s524063\AppData\Local\Continuum\anaconda3\lib\site-packages\nbformat\reader.py", line 17, in parse_json
    raise NotJSONError(("Notebook does not appear to be JSON: %r" % s)[:77] + "...")
nbformat.reader.NotJSONError: Notebook does not appear to be JSON: ''...
```

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
> just make a new text file, rename it to .ipynb and try to open it

This is not the way to create a new notebook because even an empty notebook has some structure inside it to define it. In other words, an empty notebook is not an empty file.

To make a new notebook, simply close an untitled notebook in our plugin and save it in the directory you want to place it and with the name you want to put to it.
