### ISSUE TITLE
error while launching spider

### ISSUE THREAD

**Issue by subhasrisuresh** [spyder-ide/spyder#8954]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
The error is:

Traceback (most recent call last):
File "C:\Users\suresh\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1554, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\suresh\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\Users\suresh\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 472, in write_connection_file
kernel_name=self.kernel_name
File "C:\Users\suresh\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 101, in write_connection_file
sock.bind((ip, 0))
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

**Comment by ccordoba12** [comment]
This is (most probably) an error with your firewall and/or antivirus, that's all we know about it.

Please deactivate them and try again.
