### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by prdp13** [spyder-ide/spyder#8963]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Ipython console fails to load when i open spyder console. Throws the below traceback

### What steps reproduce the problem?

1. launch spyder from anaconda-navigator

### What is the expected output? What do you see instead?
I expect to see a ipython kernel, instead i see the below error message 

### Paste Traceback/Error Below (if applicable)
Traceback (most recent call last):
File "/home/ppp/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/home/ppp/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/ppp/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/home/ppp/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 279, in main
import_spydercustomize()
File "/home/ppp/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 39, in import_spydercustomize
import spydercustomize
File "/home/ppp/anaconda3/lib/python3.7/site‑packages/spyder_kernels/customize/spydercustomize.py", line 27, in 
from IPython.core.getipython import get_ipython
File "/home/ppp/anaconda3/lib/python3.7/site‑packages/IPython/__init__.py", line 54, in 
from .core.application import Application
File "/home/ppp/anaconda3/lib/python3.7/site‑packages/IPython/core/application.py", line 23, in 
from traitlets.config.application import Application, catch_config_error
File "/home/ppp/anaconda3/lib/python3.7/site‑packages/traitlets/config/__init__.py", line 6, in 
from .application import *
File "/home/ppp/anaconda3/lib/python3.7/site‑packages/traitlets/config/application.py", line 17, in 
from decorator import decorator
ImportError: cannot import name 'decorator' from 'decorator' (/home/ppp/decorator.py)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.3
* Python version: 3.7
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Ubuntu 18.04.2 LTS

### Dependencies

```
IPython >=4.0     :  7.2.0 (OK)
cython >=0.21     :  0.29.2 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
numpy >=1.7       :  1.15.4 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
psutil >=0.3      :  5.4.8 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.2.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
```

**Comment by ccordoba12** [comment]
Please remove or rename this file

    /home/ppp/decorator.py

to fix this problem.
