### ISSUE TITLE
Preferences window is not showing up with PySide 1.0.9+

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#897]
_From [shchelok...@gmail.com](https://code.google.com/u/107123717305448090090/) on 2011-12-28T14:19:26Z_

What steps will reproduce the problem?

 Try to open "Preferences" window in any way (from menu, toolbar or with keyboard shortcut). What is the expected output? What do you see instead? Expected is Preferences dialog opening. Instead it fails to open. What version of the product are you using? On what operating system? Spyder 2.1.6, on Windows 7 64-bit, with Python 2.7.2 64-bit, Qt 4.7.4, PySide 1.0.9 

Please provide any additional information below

. This affects also Spyder 2.1.5, but not 2.1.4. I see that in the change log for 2.1.5 there is an entry for fixed bug for Windows: "Preferences" dialog was not shown if account username contained non-ASCII characters"... My account name does not contain non-ASCII characters.

Below is an error trace when Spyder run with --debug option:

Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\spyderlib\spyder.py", line 1616, in edit_preferences
    widget = plugin.create_configwidget(dlg)
  File "c:\Python27\lib\site-packages\spyderlib\plugins\__init__.py", line 159,
in create_configwidget
    configwidget.initialize()
  File "c:\Python27\lib\site-packages\spyderlib\plugins\configdialog.py", line 46, in initialize
    self.load_from_conf()
  File "c:\Python27\lib\site-packages\spyderlib\plugins\configdialog.py", line 241, in load_from_conf
    checkbox.setChecked(self.get_option(option, default))
RuntimeError: Internal C++ object (PySide.QtGui.QCheckBox) already deleted.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=897_

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2011-12-28T14:17:58Z_

Does --reset help?

**Labels:** Component-PySide

**Comment by spyder-issues-migrator** [comment]
_From [shchelok...@gmail.com](https://code.google.com/u/107123717305448090090/) on 2011-12-30T14:08:23Z_

No, it does not. In fact, I was manually removing ~/.spyder2 folder each time after removing one Spyder version and installing another when trying for this bug.

What did help though is installing PyQt4. Then Spyder picked up PyQt as the bindings to use, and the problem was gone. I was using the most recent PyQt4 version. So, the bottom line is 
- problem is present with PySide 1.0.9 on Qt 4.7.4
- problem is absent with PyQt4 4.9.1 on Qt 4.8.0
So it looks indeed like PySide problem, but may be (just may be) it is a problem of Qt in general. Unfortunately I can not find Windows downloads of older PyQt versions to try PyQt based on the same Qt as current PySide.

**Comment by spyder-issues-migrator** [comment]
_From [haber...@schaeffler.com](https://code.google.com/u/109249120741023918513/) on 2012-01-27T05:23:30Z_

Same here with Spyder 2.1.7, Python 2.7.3 64-bit, PySide 1.1.0 and Qt 4.7.4 on Windows 7 64-bit

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-01-27T07:11:37Z_

I almost sure this is a problem with PySide and not on our side. For me Spyder doesn't even start on Linux with PySide 1.1.0.

Please try to install PyQt to see if that solves the problem

**Summary:** Preferences window is not showing up with PySide 1.0.9+  
  **Labels:** Cat-SpyderGUI OpSys-Windows

**Comment by spyder-issues-migrator** [comment]
_From [shchelok...@gmail.com](https://code.google.com/u/107123717305448090090/) on 2012-01-29T01:53:30Z_

I also can confirm that the bug is not 64-bit related, since using the following setup

Windows 7 Starter (32bit), Python 2.7.2, spyderlib 2.1.7
- PySide 1.1.0 with Qt 4.7.4 bug is present (with the same error message)
- PyQt 4.9 (API v1), Qt 4.8.0 bug is abscent

I am totally not an expert but I've read that PySide supports only Qt APIv2. May this be the source of the error (if Spyder at some point explicitly uses APIv1)?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-01-29T06:13:23Z_

Spyder is supporting both PyQt API v1 and v2, so that's not the good explanation here.

Like Carlos, I've tested Spyder v2.1.7 on Linux with PySide v1.1.0 and it doesn't start at all (segfault). On Windows 7, no problem with Spyder v2.1.7, PySide v1.1.0, Python 2.7.2.

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-01-31T03:13:52Z_

Spyder on Linux won't start with PySide 1.1.0. Known problem that is fixed and will be released with PySide 1.1.1 - http://bugs.pyside.org/show_bug.cgi?id=1105

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-02-10T07:26:29Z_

issue #934 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-03-07T00:24:18Z_

issue #963 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-03-07T00:39:10Z_

**Labels:** -Priority-Medium Priority-High

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-03-08T05:13:48Z_

issue #966 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-17T06:14:55Z_

This issue was updated by revision 74ee33aecead .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-01-27T01:04:17Z_

issue #1223 has been merged into this issue.
