### ISSUE TITLE
Spyder crashes with UnicodeDecodeError (conda 4.6.8, Windows10 x64)

### ISSUE THREAD

**Issue by katastrofa999** [spyder-ide/spyder#8974]
## Problem Description

Spyder crashes when started in Anaconda Prompt or via shortcut.

### What steps reproduce the problem?

1. Open Anaconda prompt (conda 4.6.8)
2. Type "spyder"
3. Press <Enter>

### What is the expected output? What do you see instead?

Expected output: Spyder application window.

What I see: traceback (see below)

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "C:\Users\katastrofa999\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3285, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\katastrofa999\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3140, in run_spyder
    main.setup()
  File "C:\Users\katastrofa999\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 832, in setup
    self.help = Help(self)
  File "C:\Users\katastrofa999\Anaconda3\lib\site-packages\spyder\plugins\help.py", line 462, in __init__
    html_text_no_doc=warning(self.no_doc_string))
  File "C:\Users\katastrofa999\Anaconda3\lib\site-packages\spyder\utils\help\sphinxify.py", line 76, in warning
    warning = env.get_template("warning.html")
  File "C:\Users\katastrofa999\Anaconda3\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\katastrofa999\Anaconda3\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Users\katastrofa999\Anaconda3\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\katastrofa999\Anaconda3\lib\site-packages\jinja2\loaders.py", line 175, in get_source
    contents = f.read().decode(self.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdd in position 24: invalid continuation byte
[6132:16772:0318/214928.316:ERROR:broker_win.cc(59)] Error reading broker pipe: The pipe has been ended. (0x6D)

```

## Versions

* Spyder version: 3.3.3
* Python version: 3.7.2
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 64-bit 10.0.17763 Build 17763

**Comment by ccordoba12** [comment]
Please reinstall Anaconda and try again.

**Comment by katastrofa999** [comment]
Problem solved.
