### ISSUE TITLE
erro starting kernel

### ISSUE THREAD

**Issue by ANULIautomation** [spyder-ide/spyder#9018]
### What steps will reproduce the problem?

An error ocurred while starting the kernel
Traceback (most recent call last):
File "/home/anuli/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/home/anuli/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/anuli/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/home/anuli/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 279, in main
import_spydercustomize()
File "/home/anuli/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 39, in import_spydercustomize
import spydercustomize
File "/home/anuli/anaconda3/lib/python3.7/site‑packages/spyder_kernels/customize/spydercustomize.py", line 25, in 
from IPython.core.getipython import get_ipython
File "/home/anuli/anaconda3/lib/python3.7/site‑packages/IPython/__init__.py", line 54, in 
from .core.application import Application
File "/home/anuli/anaconda3/lib/python3.7/site‑packages/IPython/core/application.py", line 23, in 
from traitlets.config.application import Application, catch_config_error
File "/home/anuli/anaconda3/lib/python3.7/site‑packages/traitlets/config/__init__.py", line 6, in 
from .application import *
File "/home/anuli/anaconda3/lib/python3.7/site‑packages/traitlets/config/application.py", line 19, in 
from traitlets.config.configurable import Configurable, SingletonConfigurable
File "/home/anuli/anaconda3/lib/python3.7/site‑packages/traitlets/config/configurable.py", line 12, in 
from .loader import Config, LazyConfigValue, _is_section_key
File "/home/anuli/anaconda3/lib/python3.7/site‑packages/traitlets/config/loader.py", line 16, in 
from ipython_genutils.path import filefind
File "/home/anuli/anaconda3/lib/python3.7/site‑packages/ipython_genutils/path.py", line 13, in 
import random
File "/home/anuli/anaconda3/lib/python3.7/random.py", line 46, in 
from hashlib import sha512 as _sha512
ImportError: cannot import name 'sha512' from 'hashlib' (/home/anuli/hashlib.py)

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-43-generic

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
psutil >=0.3      :  5.4.8 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
To fix this problem please remove or rename this file:

    /home/anuli/hashlib.py
