### ISSUE TITLE
Spyder won't run on Windows Vista if user name/home folder contains non-ascii characters

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#902]
_From [ilya.mal...@gmail.com](https://code.google.com/u/117768920982057857358/) on 2012-01-04T08:52:34Z_

What steps will reproduce the problem?

 1. Install fresh Spyder
2. Run
3. See it crashed What version of the product are you using? On what operating system? Python 2.7.2 on Windows Vista x32, Spyder 2.1.6

I use cyrillic user name in Windows, so the Spyder2 data directory is:
C:\Users\Илья\.spyder2

Although .history.py is in place, it cannot be open

spyder_crash.log:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 1896, in main
    mainwindow = run_spyder(app, options)
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 1817, in run_spyder
    main.post_visible_setup()
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 912, in post_visible_setup
    self.extconsole.open_interpreter_at_startup()
  File "C:\Python27\lib\site-packages\spyderlib\plugins\externalconsole.py", line 1064, in open_interpreter_at_startup
    self.open_interpreter()
  File "C:\Python27\lib\site-packages\spyderlib\plugins\externalconsole.py", line 1071, in open_interpreter
    interact=True, debug=False, python=True)
  File "C:\Python27\lib\site-packages\spyderlib\plugins\externalconsole.py", line 762, in start
    self.historylog.add_history(shellwidget.shell.history_filename)
  File "C:\Python27\lib\site-packages\spyderlib\plugins\history.py", line 223, in add_history
    text, _ = encoding.read(filename)
  File "C:\Python27\lib\site-packages\spyderlib\utils\encoding.py", line 151, in read
    text, encoding = decode( file(filename, 'rb').read() )
IOError: [Errno 2] No such file or directory: u'C:\\Users\\\xc8\xeb\xfc\xff\\.spyder2\\.history.py'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=902_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-01-05T16:02:32Z_

This is a well known bug and I've been trying hard to fix it during the last month.

Please continue the discussion on the issue you're going to be redirected. I'll post there my fixes very soon.

Thanks for your interest in Spyder,
Carlos

**Status:** Duplicate  
  **Mergedinto:** 812
