### ISSUE TITLE
Block Comment uncomment does not work (for me).

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#905]
_From [is.that....@googlemail.com](https://code.google.com/u/104809195094697849765/) on 2012-01-09T21:21:25Z_

Spyder Version:  2.1.6
Python Version:  2.7.2 
Qt Version:      4.7.3, PyQt4 (API v1) 4.8.5 on Linux 

What steps will reproduce the problem?

 1. block comment
2. unblock comment (either per ctrl+5 or via menu) What is the expected output? What do you see instead? expected would be to remove the leading # and the lines 
above and beneath the codeblock that was blockcommented,
while either marking every line inside a block,
or the whole block
(like when block commented through ctrl+4 or menu)

\---------
hope its not my fault ;)
thx for the otherwise very fine working program

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=905_

**Comment by spyder-issues-migrator** [comment]
_From [is.that....@googlemail.com](https://code.google.com/u/104809195094697849765/) on 2012-01-09T18:24:38Z_

btw im running from source like so

$ ./bootstrap.py --gui=pyqt
Executing Spyder from source checkout Revision 1850 +:7bf24a9ca99d+, Branch: default
01. Patched sys.path with /home/spider/workspace_python/spyderlib
02. Skipping GUI toolkit detection
03. Imported Spyder 2.1.6 (Qt 4.7.3 via PyQt4 (API v1) 4.8.5)
0x. Enforcing parent console (Windows only)
04. Executing spyder.main()

**Comment by spyder-issues-migrator** [comment]
_From [daniel...@gmail.com](https://code.google.com/u/108214387417749460284/) on 2012-10-15T01:21:06Z_

I have the same issue (and I hope this respond helps):

Spyder Version:  2.1.9
Python Version:  2.7.3
Qt Version:      4.8.1, PyQt4 (API v2) 4.9.1 on Linux



What steps will reproduce the problem?


1. on any file use block comment
2. try to remove block comment (either via ctrl+5 or the menu)

What is the expected output? What do you see instead?
I'm expecting the block comment to disappear.
Instead nothing changes in the editor and I get an "AttributeError: 'unicode' object has no attribute 'startsWith'" in the internal console window.



Please provide any additional information below

.
Here's the traceback from the internal console:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/sourcecode/codeeditor.py", line 1903, in unblockcomment
    if __is_comment_bar(cursor1):
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/sourcecode/codeeditor.py", line 1900, in __is_comment_bar
    return cursor.block().text().startsWith('#' + '='*79)
AttributeError: 'unicode' object has no attribute 'startsWith'

In case this is important: I'm running Kubuntu 12.04 and installed python and spyder from the standard ubuntu repository.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-11-04T13:05:09Z_

It sure helps, thanks for the additionnal infos.

**Status:** Started

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-11-04T13:07:22Z_

This issue was updated by revision cf84cba775cf .

**Status:** Fixed
