### ISSUE TITLE
Can't display list of special comment

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#906]
_From [esilonze](https://code.google.com/u/esilonze/) on 2012-01-11T08:48:21Z_

Spyder Version:  2.1.6
Python Version:  2.7.1
Qt Version:      4.7.3, PyQt4 (API v1) 4.8.5 on Windows 

What steps will reproduce the problem?

 1. Open a source with # XXX: test of action-save
2. Click on button "show comment TODO, FIXME, ... " What is the expected output? What do you see instead? 1. The clickable list of comments isn't displayed ...
2. Click on button move cursor on next "special comment"
3. In other words, I can't select on which comment I will going 

Please provide any additional information below

. 1. Works fine up to Spyder 2.1.2 ~

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=906_

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-01-12T21:16:49Z_

Out of curiosity, I was able to reproduce this and bisect it back to revision 49b7dd15e1e5 . I've committed a fix to my clone if you'd like to review it. It's on a branch called Issue906 , located here: https://code.google.com/r/jedludlow-spyderlib/source/detail?r=cc6971d252f8cb7831cf09f9d472cffb4e53baa1&name=Issue906 I think the updated regular expression does what was intended with the earlier change. If you're satisfied, go ahead and pull it from my branch.

**Status:** Fixed  
  **Owner:** pierre.raybaut

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-01-12T21:18:11Z_

Maybe a "Fixed" status is presumptuous :). We'll leave it "Started" instead.

**Status:** Started

**Comment by spyder-issues-migrator** [comment]
_From [esilonze](https://code.google.com/u/esilonze/) on 2012-01-17T02:10:08Z_

Not solved with Spyder 2.1.7 !

When I click on little arrow near "... TODO, XXX, ..." I receive this Traceback:

Python 2.7.1 ( r271 :86832, Nov 27 2010, 18:30:46) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license" for more information.

\>>> Traceback (most recent call last):
  File "C:\Py27\lib\site-packages\spyderlib\plugins\editor.py", line 1213, in update_todo_menu
    action = create_action(self, text=text, icon=icon, triggered=slot)
  File "C:\Py27\lib\site-packages\spyderlib\utils\qthelpers.py", line 187, in create_action
    action = QAction(text, parent)
TypeError: arguments did not match any overloaded call:
  QAction(QObject): argument 1 has unexpected type 'tuple'
  QAction(QString, QObject): argument 1 has unexpected type 'tuple'
  QAction(QIcon, QString, QObject): argument 1 has unexpected type 'tuple'

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-01-17T07:27:14Z_

The change I proposed was made in my own personal clone repository and has not been pulled to the main project repository. As such, it has not been built into version 2.1.7. In the short term, you can test the change on your own install by modifying three lines of code manually. The required change can be seen here: https://code.google.com/r/jedludlow-spyderlib/source/diff?spec=svncc6971d252f8cb7831cf09f9d472cffb4e53baa1&name=Issue906&r=cc6971d252f8cb7831cf09f9d472cffb4e53baa1&format=side&path=/spyderlib/utils/codeanalysis.py Based upon your traceback above, it looks like you would need to modify this file on your system:

C:\Py27\Lib\site-packages\spyderlib\utils\codeanalysis.py

**Comment by spyder-issues-migrator** [comment]
_From [esilonze](https://code.google.com/u/esilonze/) on 2012-01-18T13:50:00Z_

Thanks for this updates: it's works.
I'm a lambda user, and I doesn't try any updates of Spyder.

I have analoguous problem when I click on the little arrow at right of "code-analyser". Messages:

\>>> Traceback (most recent call last):
  File "C:\Py27\lib\site-packages\spyderlib\plugins\editor.py", line 1183, in update_warning_menu
    for message, line0, error in check_results:
ValueError: need more than 2 values to unpack

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-01-18T18:38:55Z_

Actually this looks like a separate problem altogether. I've created issue #912 for it.

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-01-21T14:42:05Z_

issue #915 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-01-21T14:45:41Z_

Created a patch file for this fix, attached to issue #915 , to remove dependence on the existence of my personal clone.

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-01-22T11:37:49Z_

Looks like Pierre took care of this as part of issue #912 .

Fixed in revision 3d00dd565031 .

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-01-22T13:43:03Z_

Yes, that's right.
I completely missed this Issue... I simply found out about this problem after fixing the code analysis button which is right next to the task list button.

**Status:** Fixed
