### ISSUE TITLE
The Kernel doesn't start, even with restart or update of setup tools.


### ISSUE THREAD

**Issue by WaliedShehata** [spyder-ide/spyder#9066]
### What steps will reproduce the problem?

An error ocurred while starting the kernel
Traceback (most recent call last):
File "C:\anaconda\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\anaconda\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\anaconda\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\anaconda\lib\site‑packages\spyder_kernels\console\start.py", line 279, in main
import_spydercustomize()
File "C:\anaconda\lib\site‑packages\spyder_kernels\console\start.py", line 39, in import_spydercustomize
import spydercustomize
File "C:\anaconda\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 27, in 
from IPython.core.getipython import get_ipython
File "C:\anaconda\lib\site‑packages\IPython\__init__.py", line 54, in 
from .core.application import Application
File "C:\anaconda\lib\site‑packages\IPython\core\application.py", line 18, in 
import logging
File "C:\anaconda\lib\logging\__init__.py", line 41, in 
import threading
File "C:\Users\Walied\Desktop\Useful codes\threading.py", line 10, in 
import multiprocessing
File "C:\anaconda\lib\multiprocessing\__init__.py", line 16, in 
from . import context
File "C:\anaconda\lib\multiprocessing\context.py", line 344, in 
_tls = threading.local()
AttributeError: module 'threading' has no attribute 'local'

## Versions

* Spyder version: 3.3.3 
* Python version: 3.6.4
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating System: Windows 10

### Dependencies

```
IPython >=4.0     :  6.2.1 (OK)
cython >=0.21     :  0.27.3 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
matplotlib >=2.0.0:  2.1.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.14.2 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.6.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.8.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.6.6 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
```

**Comment by ccordoba12** [comment]
Please remove or rename this file

    C:\Users\Walied\Desktop\Useful codes\threading.py

to fix this problem.
