### ISSUE TITLE
smc.git browse does not work

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#908]
_From [Imposeren](https://code.google.com/u/Imposeren/) on 2012-01-14T09:25:12Z_

What steps will reproduce the problem?

 1. run git browse on any git repo What is the expected output? What do you see instead? git gui shoud be  runned but i get:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/spyderlib/widgets/explorer.py", line 276, in \<lambda>
    self.scm_command(fnames, tool='browse'))
  File "/usr/lib64/python2.7/site-packages/spyderlib/widgets/explorer.py", line 646, in scm_command
    scm.run_scm_tool(path, tool=tool)
  File "/usr/lib64/python2.7/site-packages/spyderlib/utils/scm.py", line 67, in run_scm_tool
    for (name, args) in infos[tool]:
ValueError: too many values to unpack What version of the product are you using? On what operating system? spyder trunk, gentoo 

Please provide any additional information below

. Patch:
--- scm.py      2012-01-14 16:18:25.831515359 +0200
+++ scm.py.old  2012-01-14 16:19:16.870518856 +0200
@@ -23,7 +23,7 @@
                           ),
              '.git': dict(name="git",
                           commit=( ('gitk', []), ),
-                          browse=( ('git', ['gui']), )
+                          browse=( ('git', ['gui']) )
                           ),
              }

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=908_

**Comment by spyder-issues-migrator** [comment]
_From [Imposeren](https://code.google.com/u/Imposeren/) on 2012-01-14T06:26:41Z_

sorry patch is wrong. Here is correct:
--- scm.py.old  2012-01-14 16:25:29.520544391 +0200                                     
+++ scm.py      2012-01-14 16:25:35.806544822 +0200
@@ -23,7 +23,7 @@
                           ),
              '.git': dict(name="git",
                           commit=( ('gitk', []), ),
-                          browse=( ('git', ['gui']) )
+                          browse=( ('git', ['gui']), )
                           ),
              }

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-05-22T07:00:11Z_

This issue was closed by revision 4cf56792af28 .

**Status:** Fixed
