### ISSUE TITLE
Unicode issue in worspace plugin: does not support 'é' in self.TEMPFILE_PATH

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#91]
_From [laurent....@gmail.com](https://code.google.com/u/106736747232444095024/) on 2009-10-21T07:16:05Z_

What steps will reproduce the problem?

 1. run spyder installed with python(x,y) 2.6.3.0 on vista
2. have a user directory with accent like c:/users/Sébastien
3. the crash appears while loading plugin workspace What is the expected output? What do you see instead? Spyder crash:

see below the buggy self.TEMPFILE_PATH:

debug_print: self.TEMPFILE_PATH= C:\Users\Sébastien\.spyder\.temp.spydata

Traceback (most recent call last):
  File "spyder.py", line 3, in \<module>
    spyder.main()
  File "C:\Python26\lib\site-packages\spyderlib\spyder.py", line 1421, in main
    mainwindow = run_spyder(*args)
  File "C:\Python26\lib\site-packages\spyderlib\spyder.py", line 1387, in
run_spyder
    main.setup()
  File "C:\Python26\lib\site-packages\spyderlib\spyder.py", line 343, in setup
    self.workspace = Workspace(self)
  File "C:\Python26\lib\site-packages\spyderlib\plugins\workspace.py", line
71, in __init__
    self.load_temp_namespace()
  File "C:\Python26\lib\site-packages\spyderlib\plugins\workspace.py", line
299, in load_temp_namespace
    print >>sys.__stdout__,">>>"+unicode(self.TEMPFILE_PATH)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 10:
ordinal not in range(128)

I've tried different things, but i'm bad at codec issues sorry :(

Laurent

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=91_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2009-10-25T08:27:09Z_

Have you tried to simply remove the 'unicode' function?
--> "self.filename = self.TEMPFILE_PATH" on line 297 in spyderlib\plugins\workspace.py

**Status:** Accepted

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2009-10-25T10:01:50Z_

I've just tested some other changes in a VM and it works with this revision: https://code.google.com/p/spyderlib/source/detail?r=25dd8c5e961696b89153b32a4464f6ea0cf6643f

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2009-10-25T14:59:08Z_

**Status:** Fixed
