### ISSUE TITLE
Error: failed to parse CPython

### ISSUE THREAD

**Issue by elinoraviv** [spyder-ide/spyder#9111]
Hello,
during the last session working with spyder my computer crushed.
now, it won't open, even after trying to reset it using Spyder --reset
any help will be appreciated.

this is the err msg Im receiving:

Traceback (most recent call last):
File "/Users/general1/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3285, in main
mainwindow = run_spyder(app, options, args)
File "/Users/general1/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3140, in run_spyder
main.setup()
File "/Users/general1/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 844, in setup
from spyder.plugins.editor import Editor
File "/Users/general1/anaconda3/lib/python3.6/site-packages/spyder/plugins/editor.py", line 41, in 
from spyder.utils.introspection.manager import IntrospectionManager
File "/Users/general1/anaconda3/lib/python3.6/site-packages/spyder/utils/introspection/manager.py", line 21, in 
from spyder.utils.introspection.plugin_client import PluginClient
File "/Users/general1/anaconda3/lib/python3.6/site-packages/spyder/utils/introspection/plugin_client.py", line 18, in 
import zmq
File "/Users/general1/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 42, in 
_load_libzmq()
File "/Users/general1/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 13, in _load_libzmq
PYPY = platform.python_implementation().lower() == 'pypy'
File "/Users/general1/anaconda3/lib/python3.6/platform.py", line 1265, in python_implementation
return _sys_version()[0]
File "/Users/general1/anaconda3/lib/python3.6/platform.py", line 1223, in _sys_version
repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:07:29) \n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]'

**Comment by ccordoba12** [comment]
Please update Spyder to its latest version by opening Terminal.app and running there:

    conda update spyder

This problem should be fixed in our latest version.

**Comment by elinoraviv** [comment]
thank you, it worked
