### ISSUE TITLE
1

### ISSUE THREAD

**Issue by bmlh** [spyder-ide/spyder#9160]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'
WARNING:traitlets:kernel died: 6.002900123596191

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.8
* Qt Versions: 5.9.6, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by bmlh** [comment]
Traceback (most recent call last):

  File "<ipython-input-8-32992b7fa2f7>", line 1, in <module>
    runfile('D:/文件/毕设/guo/yun.py', wdir='D:/文件/毕设/guo')

  File "D:\anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "D:\anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/文件/毕设/guo/yun.py", line 210, in <module>
    train()

  File "D:/文件/毕设/guo/yun.py", line 50, in train
    sess.run(tf.cast(pred_out_softmax,tf.int64))

  File "D:\anaconda\lib\site-packages\tensorflow\python\client\session.py", line 887, in run
    run_metadata_ptr)

  File "D:\anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)

  File "D:\anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1286, in _do_run
    run_metadata)

  File "D:\anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1308, in _do_call
    self._config.experimental.client_handles_error_formatting):

FailedPreconditionError: Attempting to use uninitialized value conv7/batch_normalization/moving_variance
	 [[{{node conv7/batch_normalization/moving_variance/read}} = Identity[T=DT_FLOAT, _class=["loc:@conv7/batch_normalization/cond/FusedBatchNorm_1/Switch_4"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](conv7/batch_normalization/moving_variance)]]

Caused by op 'conv7/batch_normalization/moving_variance/read', defined at:
  File "D:\anaconda\lib\site-packages\spyder\utils\ipython\start_kernel.py", line 241, in <module>
    main()
  File "D:\anaconda\lib\site-packages\spyder\utils\ipython\start_kernel.py", line 237, in main
    kernel.start()
  File "D:\anaconda\lib\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "D:\anaconda\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "D:\anaconda\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "D:\anaconda\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\anaconda\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "D:\anaconda\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "D:\anaconda\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "D:\anaconda\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\anaconda\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "D:\anaconda\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "D:\anaconda\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "D:\anaconda\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "D:\anaconda\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "D:\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "D:\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2808, in run_ast_nodes
    if self.run_code(code, result):
  File "D:\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-32992b7fa2f7>", line 1, in <module>
    runfile('D:/文件/毕设/guo/yun.py', wdir='D:/文件/毕设/guo')
  File "D:\anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)
  File "D:\anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "D:/文件/毕设/guo/yun.py", line 210, in <module>
    train()
  File "D:/文件/毕设/guo/yun.py", line 37, in train
    pred_out = mo.unet(x, training)
  File "D:\文件\毕设\guo\mo.py", line 41, in unet
    conv7   = conv("conv7", concat3, [7, 3, 128,  64], [64], training, add_bias=False, norm=True, relu=True)
  File "D:\文件\毕设\guo\func.py", line 74, in conv
    con = tf.layers.batch_normalization(con, training=training_flag)#批量归一化
  File "D:\anaconda\lib\site-packages\tensorflow\python\layers\normalization.py", line 309, in batch_normalization
    return layer.apply(inputs, training=training)
  File "D:\anaconda\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 828, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "D:\anaconda\lib\site-packages\tensorflow\python\layers\base.py", line 364, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "D:\anaconda\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 759, in __call__
    self.build(input_shapes)
  File "D:\anaconda\lib\site-packages\tensorflow\python\keras\layers\normalization.py", line 327, in build
    aggregation=tf_variables.VariableAggregation.MEAN)
  File "D:\anaconda\lib\site-packages\tensorflow\python\layers\base.py", line 278, in add_weight
    getter=vs.get_variable)
  File "D:\anaconda\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 586, in add_weight
    aggregation=aggregation)
  File "D:\anaconda\lib\site-packages\tensorflow\python\training\checkpointable\base.py", line 591, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "D:\anaconda\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1484, in get_variable
    aggregation=aggregation)
  File "D:\anaconda\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1234, in get_variable
    aggregation=aggregation)
  File "D:\anaconda\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 538, in get_variable
    aggregation=aggregation)
  File "D:\anaconda\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 492, in _true_getter
    aggregation=aggregation)
  File "D:\anaconda\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 920, in _get_single_variable
    aggregation=aggregation)
  File "D:\anaconda\lib\site-packages\tensorflow\python\ops\variables.py", line 145, in __call__
    return cls._variable_call(*args, **kwargs)
  File "D:\anaconda\lib\site-packages\tensorflow\python\ops\variables.py", line 141, in _variable_call
    aggregation=aggregation)
  File "D:\anaconda\lib\site-packages\tensorflow\python\ops\variables.py", line 120, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "D:\anaconda\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2441, in default_variable_creator
    expected_shape=expected_shape, import_scope=import_scope)
  File "D:\anaconda\lib\site-packages\tensorflow\python\ops\variables.py", line 147, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "D:\anaconda\lib\site-packages\tensorflow\python\ops\variables.py", line 1104, in __init__
    constraint=constraint)
  File "D:\anaconda\lib\site-packages\tensorflow\python\ops\variables.py", line 1266, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "D:\anaconda\lib\site-packages\tensorflow\python\ops\array_ops.py", line 81, in identity
    return gen_array_ops.identity(input, name=name)
  File "D:\anaconda\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3353, in identity
    "Identity", input=input, name=name)
  File "D:\anaconda\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\anaconda\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "D:\anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 3272, in create_op
    op_def=op_def)
  File "D:\anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value conv7/batch_normalization/moving_variance
	 [[{{node conv7/batch_normalization/moving_variance/read}} = Identity[T=DT_FLOAT, _class=["loc:@conv7/batch_normalization/cond/FusedBatchNorm_1/Switch_4"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](conv7/batch_normalization/moving_variance)]]

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda update spyder
