### ISSUE TITLE
Memory Error (64bit 8gb Ram)

### ISSUE THREAD

**Issue by Harrish-Selvarajah** [spyder-ide/spyder#9172]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```runfile('E:/Recommender vids/RecSys-Materials/RecSys-Materials/Framework/RecsBakeOff.py', wdir='E:/Recommender vids/RecSys-Materials/RecSys-Materials/Framework')
Reloaded modules: MovieLens, Evaluator, EvaluationData, EvaluatedAlgorithm, RecommenderMetrics
Loading movie ratings...

Computing movie popularity ranks so we can measure novelty later...
Estimating biases using als...
Computing the cosine similarity matrix...
Traceback (most recent call last):

  File "<ipython-input-3-491a7f5338b5>", line 1, in <module>
    runfile('E:/Recommender vids/RecSys-Materials/RecSys-Materials/Framework/RecsBakeOff.py', wdir='E:/Recommender vids/RecSys-Materials/RecSys-Materials/Framework')

  File "C:\Users\harrish\Anaconda3\envs\RecSys\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\harrish\Anaconda3\envs\RecSys\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/Recommender vids/RecSys-Materials/RecSys-Materials/Framework/RecsBakeOff.py", line 31, in <module>
    evaluator = Evaluator(evaluationData, rankings)

  File "E:\Recommender vids\RecSys-Materials\RecSys-Materials\Framework\Evaluator.py", line 15, in __init__
    ed = EvaluationData(dataset, rankings)

  File "E:\Recommender vids\RecSys-Materials\RecSys-Materials\Framework\EvaluationData.py", line 36, in __init__
    self.simsAlgo.fit(self.fullTrainSet)

  File "C:\Users\harrish\Anaconda3\envs\RecSys\lib\site-packages\surprise\prediction_algorithms\knns.py", line 281, in fit
    self.sim = self.compute_similarities()

  File "C:\Users\harrish\Anaconda3\envs\RecSys\lib\site-packages\surprise\prediction_algorithms\algo_base.py", line 293, in compute_similarities
    sim = construction_func[name](*args)

  File "surprise/similarities.pyx", line 72, in surprise.similarities.cosine

MemoryError

## Versions
<!--- You can get this information from Help > About Spyder...
or (if Spyder won't launch) the "conda list" command
from the Anaconda Prompt/Terminal/command line. --->

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies
<!--- Please go to the menu entry Help > Dependencies,
press the Copy to clipboard button and paste below --->

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
That's a problem with your code, not with Spyder. I think your system went out of memory.
