### ISSUE TITLE
Spyder doesn't start ufter 3.3.4 update

### ISSUE THREAD

**Issue by emilmirzayev** [spyder-ide/spyder#9178]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset`` Reset throws error. See below
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
After updating Spyder via pip from version 3.3.3 -> 3.3.4 it doesn't start any more.
Also, tried to delete its dependencies, install again, and also `spyder --reset`. Which threw another error:
```
C:\Users\Emil Mirzayev\AppData\Local\Programs\Python\Python37\Scripts>python spyder3.exe --reset
Traceback (most recent call last):
  File "C:\Users\Emil Mirzayev\AppData\Local\Programs\Python\Python37\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Emil Mirzayev\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Emil Mirzayev\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "spyder3.exe\__main__.py", line 9, in <module>
  File "C:\Users\Emil Mirzayev\AppData\Local\Programs\Python\Python37\lib\site-packages\spyder\app\start.py", line 192, in main
    from spyder.app import mainwindow
  File "C:\Users\Emil Mirzayev\AppData\Local\Programs\Python\Python37\lib\site-packages\spyder\app\mainwindow.py", line 90, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "C:\Users\Emil Mirzayev\AppData\Local\Programs\Python\Python37\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
```

### What steps reproduce the problem?

1. Updated spyder to 3.3.4 via pip
2. It doesn't launch any more

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.4
* Python version: 3.7.2
* Qt version: QtPy?? -> 1.7.0
* PyQt version: 5.12.1
* Operating System name/version: Win10 Pro, x64

### Dependencies

```
Package                       Version
----------------------------- ----------
alabaster                     0.7.12
altgraph                      0.16.1
astroid                       2.2.5
Babel                         2.6.0
backcall                      0.1.0
Bext                          0.0.2
bleach                        3.0.2
certifi                       2018.11.29
chardet                       3.0.4
cloudpickle                   0.8.1
coconut                       1.4.0
colorama                      0.4.1
cycler                        0.10.0
Cython                        0.29.2
decorator                     4.3.0
defusedxml                    0.5.0
docutils                      0.14
entrypoints                   0.2.3
fortran-magic                 0.7
future                        0.17.1
idna                          2.8
imagesize                     1.1.0
ipykernel                     5.1.0
ipython                       7.2.0
ipython-genutils              0.2.0
ipywidgets                    7.4.2
isort                         4.3.4
jedi                          0.13.1
Jinja2                        2.10
jsonschema                    2.6.0
jupyter                       1.0.0
jupyter-client                5.2.3
jupyter-console               6.0.0
jupyter-core                  4.4.0
jupyterlab                    0.35.4
jupyterlab-server             0.2.0
keyring                       19.0.1
kiwisolver                    1.0.1
lazy-object-proxy             1.3.1
llvmlite                      0.27.0
logitboost                    0.5
macholib                      1.11
MarkupSafe                    1.1.0
matplotlib                    3.0.2
mccabe                        0.6.1
mistune                       0.8.4
nbconvert                     5.4.1
nbformat                      4.4.0
notebook                      5.7.2
numba                         0.42.0
numpy                         1.15.4
numpydoc                      0.8.0
oauthlib                      3.0.0
packaging                     18.0
pandas                        0.23.4
pandocfilters                 1.4.2
parso                         0.3.1
patsy                         0.5.1
pefile                        2018.8.8
pickleshare                   0.7.5
pip                           19.0.3
pipenv                        2018.11.26
prometheus-client             0.5.0
prompt-toolkit                2.0.7
psutil                        5.6.1
pycodestyle                   2.4.0
pyflakes                      2.0.0
Pygments                      2.3.1
PyInstaller                   3.4
pylint                        2.3.1
pyparsing                     2.2.0
pypng                         0.0.19
PyQt5                         5.12.1
PyQt5-sip                     4.19.15
PyQtWebEngine                 5.12.1
PySocks                       1.6.8
python-dateutil               2.7.5
pytz                          2018.7
pywin32-ctypes                0.2.0
pywinpty                      0.5.5
pyzmq                         18.0.1
QtAwesome                     0.5.7
qtconsole                     4.4.3
QtPy                          1.7.0
requests                      2.21.0
requests-oauthlib             1.2.0
rope                          0.11.0
scikit-learn                  0.20.1
scipy                         1.1.0
seaborn                       0.9.0
Send2Trash                    1.5.0
setuptools                    39.0.1
sip                           4.19.8
six                           1.12.0
sklearn                       0.0
snowballstemmer               1.2.1
Sphinx                        2.0.1
sphinxcontrib-applehelp       1.0.1
sphinxcontrib-devhelp         1.0.1
sphinxcontrib-htmlhelp        1.0.2
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.2
sphinxcontrib-serializinghtml 1.1.3
sphinxcontrib-websupport      1.1.0
spyder                        3.3.4
spyder-kernels                0.4.4
statsmodels                   0+unknown
tabulate                      0.8.2
terminado                     0.8.1
testpath                      0.4.2
tornado                       5.1.1
tqdm                          4.29.1
traitlets                     4.3.2
tweepy                        3.7.0
typed-ast                     1.3.4
urllib3                       1.24.1
virtualenv                    16.1.0
virtualenv-clone              0.4.0
wcwidth                       0.1.7
webencodings                  0.5.1
wget                          3.2
widgetsnbextension            3.4.2
wrapt                         1.10.11
```

**Comment by ccordoba12** [comment]
Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

**Comment by emilmirzayev** [comment]
I have been using Spyder without Anaconda up to today and never encountered this problem. Only after the newest update, it happened. Thanks anyway, will find some way around

**Comment by ccordoba12** [comment]
This is not a problem with Spyder but with PyQt5. The simplest solution is to downgrade PyQt5 to 5.11:

    pip install pyqt5==5.11

**Comment by MGBergweiler** [comment]
Córdoba's solution worked fine for me, had to choose version 5.11.3, though (5.11 not offered)

`pip install pyqt5==5.11.3`

**Comment by DavCza** [comment]
Upgrading PyQt5 from 5.9.2 to 5.11.3 also worked fine for me to start Spyder again.
