### ISSUE TITLE
Double clicking dict variable in Variable Explorer

### ISSUE THREAD

**Issue by AyFahrettin** [spyder-ide/spyder#9183]
### What steps will reproduce the problem?

the code is below;

frame = pd.read_csv("file.csv", sep="," index_col=None)
tmp = frame.groupby("Title").groups

-----
After that, I double clicked to the tmp (type: dict, size: 815) on Variable explorer to see the groups

Note: the frame shape is (976,9)

### Traceback
```python-traceback
  File "/home/ayf/anaconda2/lib/python2.7/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 329, in data
    display = to_text_string(value)
  File "/home/ayf/anaconda2/lib/python2.7/site-packages/spyder/py3compat.py", line 135, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 17: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/ayf/anaconda2/lib/python2.7/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 329, in data
    display = to_text_string(value)
  File "/home/ayf/anaconda2/lib/python2.7/site-packages/spyder/py3compat.py", line 135, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 17: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/ayf/anaconda2/lib/python2.7/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 329, in data
    display = to_text_string(value)
  File "/home/ayf/anaconda2/lib/python2.7/site-packages/spyder/py3compat.py", line 135, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 17: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/ayf/anaconda2/lib/python2.7/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 329, in data
    display = to_text_string(value)
  File "/home/ayf/anaconda2/lib/python2.7/site-packages/spyder/py3compat.py", line 135, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 17: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/ayf/anaconda2/lib/python2.7/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 329, in data
    display = to_text_string(value)
  File "/home/ayf/anaconda2/lib/python2.7/site-packages/spyder/py3compat.py", line 135, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 76: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/ayf/anaconda2/lib/python2.7/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 329, in data
    display = to_text_string(value)
  File "/home/ayf/anaconda2/lib/python2.7/site-packages/spyder/py3compat.py", line 135, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 76: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/ayf/anaconda2/lib/python2.7/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 329, in data
    display = to_text_string(value)
  File "/home/ayf/anaconda2/lib/python2.7/site-packages/spyder/py3compat.py", line 135, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 76: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/ayf/anaconda2/lib/python2.7/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 329, in data
    display = to_text_string(value)
  File "/home/ayf/anaconda2/lib/python2.7/site-packages/spyder/py3compat.py", line 135, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 76: ordinal not in range(128)
```

## Versions

* Spyder version: 4.0.0b1 
* Python version: 2.7.15
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-47-generic

### Dependencies

```
pyflakes >=0.5.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.11.0     :  0.12.1 (OK)
psutil >=0.3      :  5.4.7 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.2 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0;<6.0:  5.8.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  1.9.2 (OK)
```

**Comment by CAM-Gerlach** [comment]
Your error is due to one or more non-ASCII character somewhere in the dict name, keys, values, etc, while using Python 2, which lacks proper Unicode support. Please upgrade to a modern version of Python 3 (e.g. 3.6 or 3.7) to fix this; Python 2 is EoL in less than 8 months and we will not be supporting it after that date. Alternatively, as a temporary solution, do not use any non-ASCII characters within your dict names, keys or values.
