### ISSUE TITLE
not sure what is happening

### ISSUE THREAD

**Issue by kurtrhee** [spyder-ide/spyder#9201]
### What steps will reproduce the problem?

i opened spyder in a virtual environment in anaconda and now i cannot close it

### Traceback
```python-traceback
  File "C:\Users\simon.rhee\AppData\Local\Continuum\anaconda3\envs\batt_env\lib\site-packages\spyder\utils\introspection\plugin_client.py", line 187, in _heartbeat
    def _heartbeat(self):
KeyboardInterrupt
Traceback (most recent call last):
  File "C:\Users\simon.rhee\AppData\Local\Continuum\anaconda3\envs\batt_env\lib\site-packages\qtconsole\manager.py", line 26, in poll
    def poll(self):
KeyboardInterrupt
```

## Versions

* Spyder version: 3.3.4 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  2.0.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.3 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
It seems you're trying to run `Ctrl+C` on the terminal you started Spyder. Is that right?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
