### ISSUE TITLE
Accessing dictionary containing HDF5 File

### ISSUE THREAD

**Issue by gr4yh4t-0** [spyder-ide/spyder#9222]
### What steps will reproduce the problem?

```python

import h5py as h5

file = h5.File(<filepath>)

dict = {}

key1 = 'scan <number>'
key2 = 'scan H5'

dict.setdefault(key1, <scan number>)
dict.setdefault(key2, file)             
# i think this last line is causing trouble
```
# 
the code successfully runs without any error or warning, but when i try to access the above dictionary object in the vairable explorer, i receive the error attached to this issue report.

#
i belive this is a problem with the linux diribution of spyder only, but have not tried it on Windows 7 yet

### Traceback
```python-traceback
  File "h5py/_objects.pyx", line 200, in h5py._objects.ObjectID.__dealloc__
KeyError: 0
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 200, in h5py._objects.ObjectID.__dealloc__
KeyError: 0
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.4 
* Python version: 3.6.8
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-47-generic

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  2.0.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
psutil >=0.3      :  5.6.1 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.3 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.7 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by goanpeca** [comment]
@gr4yh4t-0 could you share a simple hdf5 file so we can test this on our side?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
