### ISSUE TITLE
Internal Console exception while searching for text in a console window

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#928]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2012-02-02T17:43:54Z_

What steps will reproduce the problem?

 1. Place focus into a console window that contains some text
2. Press Ctrl + F to open the find box
3. Enter something to search for
4. Hit F3 for next or click the back/forward buttons and the internal console will output the following traceback

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\widgets\findreplace.py", line 257, in find_next
    state = self.find(changed=False, forward=True, rehighlight=False)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\findreplace.py", line 302, in find
    if rehighlight or not self.editor.found_results:
AttributeError: 'ExtPythonShellWidget' object has no attribute 'found_results' What is the expected output? What do you see instead? I'm not sure if anything is broken per se, because I can still correctly jump forwards and backwards to whatever search phrase I am looking for. What version of the product are you using? On what operating system? spyder 2.1.7, win 7 64-bit, python 2.7.2

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=928_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-01T16:41:15Z_

This is fixed now.

**Status:** Fixed
