### ISSUE TITLE
Internal console displays error when running or debugging faulty code

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#931]
_From [anatoliy...@gmail.com](https://code.google.com/u/101136359641652000647/) on 2012-02-07T15:58:30Z_

What steps will reproduce the problem?

 1.  Input code that has a syntax error into the editor, and press 'debug' or 'run'
2. Internal console will produce the following traceback (not every time):  

\>>> Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/introspection.py", line 65, in run
    self.send_socket(shell_id, conn)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/introspection.py", line 49, in send_socket
    shell.set_introspection_socket(sock)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/pythonshell.py", line 248, in set_introspection_socket
    'set_remote_view_settings()', settings=[settings])
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/utils/bsdsocket.py", line 67, in communicate
    return read_packet(sock)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/utils/bsdsocket.py", line 36, in read_packet
    dlen, = struct.unpack("l", datalen)
error: unpack requires a string argument of length 8

3. Spyder continues to run normally and the program executes after the syntax error is corrected. What version of the product are you using? On what operating system? 2.1.7 oneiric

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=931_

**Comment by spyder-issues-migrator** [comment]
_From [misterpr...@gmail.com](https://code.google.com/u/112589489140406980563/) on 2012-02-16T17:18:58Z_

I'm seeing exactly the same thing in py26-spyder (Spyder under Python 2.6) as installed by the current MacPorts version, so this error seems not to be platform-specific.

**Comment by spyder-issues-migrator** [comment]
_From [pmav99@gmail.com](https://code.google.com/u/pmav99@gmail.com/) on 2012-02-21T08:20:28Z_

I confirm this one too on Linux x64, running from the source the latest version

It must be the same issues as the following ones: https://code.google.com/p/spyderlib/issues/detail?id=941 https://code.google.com/p/spyderlib/issues/detail?id=113 Perhaps they should be merged.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-11T07:09:47Z_

**Status:** Duplicate  
  **Mergedinto:** 113
