### ISSUE TITLE
Automatic error report 

### ISSUE THREAD

**Issue by leilahawa** [spyder-ide/spyder#9313]
Spyder error:

 File "C:\ProgramFolder\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 950, in set_working_directory
    refresh_console=False)
  File "C:\ProgramFolder\Anaconda3\lib\site-packages\spyder\plugins\workingdirectory.py", line 296, in chdir
    self.refresh_plugin()
  File "C:\ProgramFolder\Anaconda3\lib\site-packages\spyder\plugins\workingdirectory.py", line 204, in refresh_plugin
    self.save_wdhistory()
  File "C:\ProgramFolder\Anaconda3\lib\site-packages\spyder\plugins\workingdirectory.py", line 234, in save_wdhistory
    encoding.writelines(text, self.LOG_PATH)
  File "C:\ProgramFolder\Anaconda3\lib\site-packages\spyder\utils\encoding.py", line 236, in writelines
    return write(os.linesep.join(lines), filename, encoding, mode)
  File "C:\ProgramFolder\Anaconda3\lib\site-packages\spyder\utils\encoding.py", line 227, in write
    with open(filename, mode) as textfile:
FileNotFoundError: [Errno 2] No such file or directory: 'P:\\.spyder-py3\\workingdir'

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.4

**Comment by leilahawa** [comment]
I also encountered this problem, is it Spyder related?

runfile('D:/every5min10to11.py', wdir='D:')
Traceback (most recent call last):

  File "<ipython-input-2-1a935aa3d14f>", line 1, in <module>
    runfile('D:/every5min10to11.py', wdir='D:')

  File "C:\ProgramFolder\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\ProgramFolder\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/every5min10to11.py", line 79, in <module>
    with urlopen("https://lime.bike/api/partners/v1/gbfs/free_bike_status.json") as response:

  File "C:\ProgramFolder\Anaconda3\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)

  File "C:\ProgramFolder\Anaconda3\lib\urllib\request.py", line 532, in open
    response = meth(req, response)

  File "C:\ProgramFolder\Anaconda3\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)

  File "C:\ProgramFolder\Anaconda3\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)

  File "C:\ProgramFolder\Anaconda3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)

  File "C:\ProgramFolder\Anaconda3\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

HTTPError: Bad Gateway

**Comment by ccordoba12** [comment]
No, it's an error in your code.
