### ISSUE TITLE
Tools->preferences fails on mac

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#934]
_From [jon.cham...@gmail.com](https://code.google.com/u/104556211888717111926/) on 2012-02-08T11:32:23Z_

What steps will reproduce the problem?

 1.Run spyder from source using bootstrap.py
2.Click on tools -> preferences What is the expected output? What do you see instead? Preferences window should show. Instead get big error log in internal console window (see below) What version of the product are you using? On what operating system? 2.1.7 on OSX Lion, using pyside 1.0.7 and qt 4.7 

Please provide any additional information below

. Traceback (most recent call last):
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 656, in get_source_project
    return self.workspace.get_source_project(fname)
AttributeError: 'ExplorerTreeWidget' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/Users/jonathanchambers/codespace/spyderlib/spyderlib/widgets/projectexplorer.py", line 455, in icon
    project = self.treeview.get_source_project(fname)
  File "/Users/jonathanchambers/codes...

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=934_

**Comment by spyder-issues-migrator** [comment]
_From [jon.cham...@gmail.com](https://code.google.com/u/104556211888717111926/) on 2012-02-08T16:13:37Z_

Confirmed the same error occurs with spyderlib installed to site-packages

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-02-10T07:26:29Z_

Jon, this is a PySide problem which we're hoping to be fixed in version 1.1.1. Please see the Issue I'm merging this one to.

**Status:** Duplicate  
  **Mergedinto:** 897
