### ISSUE TITLE
matplotlib 0.99 with PyQt4 v4.6 bug: underlying C/C++ object has been deleted

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#94]
_From [b.ber...@gmail.com](https://code.google.com/u/112339487763423702333/) on 2009-10-22T03:19:11Z_

Ciao,

I've this problem, for the last version of spyder running on Win XP /
Python 2.6 and with the last PyQt freshly installed on.

To get the "bug", I create a test file like this:

\#####################
from numpy import *
from pylab import *

t=linspace(0,1,100)

plot(t)
show()
\#####################

Then, I run it using the shortcut that runs: 
execfile(u'C:\\[...]\\test.py') 

The first time I run the script, a figure window normally opens.
But, without changing anything else, I use again the same command:
execfile(u'C:\\[...]\\test.py')

This time I get the following error:

\################################## 
Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\matplotlib\backends\backend_qt4.py",
line 205, in idle_draw
    self.draw()
  File
"C:\Python26\lib\site-packages\matplotlib\backends\backend_qt4agg.py", line
131, in draw
    self.update()
RuntimeError: underlying C/C++ object has been deleted
Traceback (most recent call last):
  File "C:\[...]\test.py", line 9, in \<module>
    show()
  File "C:\Python26\lib\site-packages\matplotlib\backends\backend_qt4.py",
line 63, in show
    manager.window.show()
RuntimeError: underlying C/C++ object has been deleted
\#####################################

Do I forget something in particular or is it a bug?
Notice that on another computer with python(x,y) installed, and the last
release of spyder, I did not get the bug. On the current installation, I
don't have python(x,y) installed.

Best regards,
By the way, congratulations for this great work.

Bastien.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=94_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2009-10-25T08:04:34Z_

You may be the first to try Spyder with PyQt4 v4.6 on Windows. So this bug may be
related to this PyQt4 version -- Python(x,y) includes PyQt4 v4.5.4.

I'll have to do some tests to confirm this.

**Status:** Accepted

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2009-11-04T08:38:01Z_

Actually I found out that it's a matplotlib's bug with PyQt4 v4.6+
I'll see what I can do from Spyder.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2009-11-04T08:39:47Z_

**Summary:** matplotlib 0.99 with PyQt4 v4.6 bug: underlying C/C++ object has been deleted

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2009-11-04T08:40:02Z_

issue #104 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2009-11-04T14:32:36Z_

Fixed in mercurial repository: https://code.google.com/p/spyderlib/source/detail?r=640cc0ac2a53b241a3cb12fff3dc1f2d52183c91

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [b.ber...@gmail.com](https://code.google.com/u/112339487763423702333/) on 2009-11-15T12:09:23Z_

Using this version from mercurial repository and kubuntu karmic, fresh installation,
I still get this error:
\---------------------
Traceback (most recent call last):
  File "/home/bastien/.spyder/.temp.py", line 13, in \<module>
    show()
  File "/usr/lib/pymodules/python2.6/matplotlib/backends/backend_qt4.py", line 63, in
show
    manager.window.show()
RuntimeError: underlying C/C++ object has been deleted
\---------------------

So maybe I am unlucky, but are you sure it has been definitely fixed?

Best regards,
Bastien.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-01-07T09:53:41Z_

issue #134 has been merged into this issue.
