### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#944]
_From [pmav99@gmail.com](https://code.google.com/u/pmav99@gmail.com/) on 2012-02-21T14:16:44Z_

Just a feature request.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=944_

**Comment by spyder-issues-migrator** [comment]
_From [code3rea...@gmail.com](https://code.google.com/u/107926469365988394793/) on 2012-03-26T16:14:27Z_

Spyder is now the only python package I use without Python3 support.

**Comment by spyder-issues-migrator** [comment]
_From [giulio.g...@gmail.com](https://code.google.com/u/100539497942729673669/) on 2012-06-04T10:22:30Z_

I am fairly new to python, but does the library update fine using the 2to3 script?

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-06-04T10:31:07Z_

I guess nobody tried. =)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-07-15T09:37:55Z_

Actually somebody did try: https://groups.google.com/d/msg/spyderlib/lPmDpwsvXJE/YAYqiqFjM-0J

**Comment by spyder-issues-migrator** [comment]
_From [trueflyi...@gmail.com](https://code.google.com/u/103824930862744342842/) on 2012-12-18T07:32:57Z_

any progress? i exclusively use python3, so it would be really awesome to be able to use spyder!

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-12-18T07:36:38Z_

For me the progress stopped with the stop of PySide development.

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2012-12-18T07:43:57Z_

PySide development stopped ? When ?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-12-18T07:45:00Z_

What do you mean Anatoly? I think PyQt is working just fine in Python3

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-12-18T08:01:10Z_

Although there is a recent activity on PySide related to leaks IIUC, but there are 98 non-evaluated issues on a tracker. https://bugreports.qt-project.org/browse/PYSIDE#selectedTab=com.atlassian.jira.plugin.system.project%3Aissues-panel I can't use PyQt, because it's viral and I am not sure where the snippets I write may come in handy.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-01-02T07:22:24Z_

The v21 repository should now be compatible with Python 3: https://code.google.com/p/spyderlib/source/checkout?repo=v21 See also this discussion: https://groups.google.com/group/spyderlib/browse_thread/thread/1b223083632bf073

**Status:** Started  
  **Owner:** pierre.raybaut  
  **Labels:** -Type-Defect -Priority-Medium Type-Enh Priority-High MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-01-02T07:24:17Z_

issue #1209 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [disjunc...@gmail.com](https://code.google.com/u/106020477681701760090/) on 2013-01-04T02:12:40Z_

openSuSE 12.2 x86_64

ipython3 --version
0.13.1

python3 --version
Python 3.2.3

Spyderlib started after running 2to3 and fixing sitecustomize.py: 
os.environ['SPYDER_ENCODING'] = "en_US.UTF-8"

IPython console & workflow looks broken (pylab does not start properly, matplotlib can't paint figures), IPython starts with:
Error in sitecustomize; set PYTHONVERBOSE for traceback:
ValueError: Attempted relative import in non-package
Python 3.2.3 (default, May 18 2012, 11:54:24) [GCC]
Type "copyright", "credits" or "license" for more information.



Internal console continuously reports: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/site-packages/spyderlib/widgets/sourcecode/codeeditor.py", line 334, in paintEvent
    self.code_editor.linenumberarea_paint_event(event)
  File "/usr/local/lib/python3.2/site-packages/spyderlib/widgets/sourcecode/codeeditor.py", line 1087, in linenumberarea_paint_event
    block = next(block)
TypeError: QTextBlock object is not an iterator

**Comment by spyder-issues-migrator** [comment]
_From [disjunc...@gmail.com](https://code.google.com/u/106020477681701760090/) on 2013-01-04T04:05:17Z_

After applying the path https://code.google.com/p/spyderlib/issues/attachmentText?id=1209&aid=12090000000&name=p3hg.txt&token=yQp3_yOGIIVIxo-SvGRuLRx1tfU%3A1357294755258 I was able to start IPython, but console-painting issues remain.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-01-04T05:34:49Z_

You must be using the wrong repository because this patch is not necessary.
See: https://code.google.com/p/spyderlib/source/browse/spyderlib/scientific_startup.py?repo=v21

**Comment by spyder-issues-migrator** [comment]
_From [lizhenqi...@gmail.com](https://code.google.com/u/102288932687224218465/) on 2013-02-11T20:44:54Z_

Hi,

Thank you for the hard work. I actually checked out the latest source tree and after install I got the following error messages when I want to start spyder:
Traceback (most recent call last):
  File "/usr/local/bin/spyder", line 2, in \<module>
    from spyderlib import spyder
  File "/usr/local/lib/python3.2/dist-packages/spyderlib/spyder.py", line 83, in \<module>
    from spyderlib.utils.environ import WinUserEnvDialog
  File "/usr/local/lib/python3.2/dist-packages/spyderlib/utils/environ.py", line 17, in \<module>
    from spyderlib.widgets.dicteditor import DictEditor
  File "/usr/local/lib/python3.2/dist-packages/spyderlib/widgets/dicteditor.py", line 35, in \<module>
    from spyderlib.config import get_icon, get_font
  File "/usr/local/lib/python3.2/dist-packages/spyderlib/config.py", line 530, in \<module>
    set_default_color_scheme(_name, replace=False)
  File "/usr/local/lib/python3.2/dist-packages/spyderlib/config.py", line 527, in set_default_color_scheme
    set_color_scheme(name, COLORS[name], replace=replace)
  File "/usr/local/lib/python3.2/dist-packages/spyderlib/config.py", line 521, in set_color_scheme
    names.append(to_text_string(name))
AttributeError: 'str' object has no attribute 'append'

Thank you very much.

Sincerely,
Zhenqing

**Comment by spyder-issues-migrator** [comment]
_From [lizhenqi...@gmail.com](https://code.google.com/u/102288932687224218465/) on 2013-02-11T21:18:19Z_

Hi,

By removing the old spyder config files, I was able to avoid the previous error message. However, this time I got the following error messages. I am running Ubuntu 12.10 amd64 version with python3.2. Thank you.

  File "/usr/local/lib/python3.2/dist-packages/spyderlib/spyder.py", line 2037, in main
    mainwindow = run_spyder(app, options)
  File "/usr/local/lib/python3.2/dist-packages/spyderlib/spyder.py", line 1951, in run_spyder
    main.setup()
  File "/usr/local/lib/python3.2/dist-packages/spyderlib/spyder.py", line 701, in setup
    self.editor = Editor(self)
  File "/usr/local/lib/python3.2/dist-packages/spyderlib/plugins/editor.py", line 417, in __init__
    self.editorsplitter.set_layout_settings(layout)
  File "/usr/local/lib/python3.2/dist-packages/spyderlib/widgets/editor.py", line 1984, in set_layout_settings
    splitsettings = settings.get('splitsettings')
AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/spyderlib/widgets/editor.py", line 1893, in \<lambda>
    lambda: self.editorstack_closed())
  File "/usr/local/lib/python3.2/dist-packages/spyderlib/widgets/editor.py", line 1915, in editorstack_closed
    self.unregister_editorstack_cb(self.editorstack)
  File "/usr/local/lib/python3.2/dist-packages/spyderlib/plugins/editor.py", line 1042, in unregister_editorstack
    self.remove_last_focus_editorstack(editorstack)
  File "/usr/local/lib/python3.2/dist-packages/spyderlib/plugins/editor.py", line 899, in remove_last_focus_editorstack
    for editorwindow, widget in list(self.last_focus_editorstack.items()):
AttributeError: 'Editor' object has no attribute 'last_focus_editorstack'
Segmentation fault (core dumped)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-02-12T00:41:33Z_

There are still known issues with Python 3.0-3.2. 

For now, I've only tested Python 3.3 on Windows, thanks to WinPython. 

Further testing on Linux and on Python versions prior to v3.3 still need to be done.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-03-17T01:50:49Z_

I propose to reorganize Spyder's repository first, so that the future changesets related to Python 3 compatibility will be more readable.

**Summary:** Add Python 3 support  \<span class="oldvalue"> (was: Python3 support) \</span>  
  **Blockedon:** spyderlib:1320

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-04-30T08:10:02Z_

issue #1246 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-05-12T05:36:46Z_

@Carlos, @-Jed:
Maybe I should wait until 2.2.1 is released to begin coding Python 3 support? or not?

**Cc:** ccordoba12 jed.lud...@gmail.com

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-05-12T06:45:05Z_

I don't think you have to wait. From the bug report rate on the 2.2.0 release I don't see a pressing need for a 2.2.1 to be released quickly. On the other hand, getting Python 3 support out quickly so it can be tested would really allow progress on new features planned for 2.4.

It's inevitable that the 2.2 branch will gradually diverge from the default branch, and that will make pulling changes from 2.2 more challenging to merge. But I don't believe that is a good enough reason to hold back.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-05-12T06:53:57Z_

I agree with Jed. There isn't too much things to do for 2.2.1 and the sooner you start the migration the better for the project because more people will have the opportunity to test our support.

But I see that you blocked this issue on issue #1320 , so what are your plans exactly? Do you plan to reorganize the code first and then start with Python 3?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-05-12T07:09:56Z_

@-Carlos: fixing issue #1320 before issue #944 was the original plan but there is no strong relationship between those two issues, so I'm removing the link between them.

**Blockedon:** -spyderlib:1320

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-05-12T07:14:57Z_

Ok, then please go ahead with Python 3 :) I just tried 2.1dev with 3.3 and it's working superb!

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-05-17T00:51:36Z_

Spyder v2.3.0dev (default branch, default repository) has now experimental support for Python 3!

Everything seems to work fine (from a superficial point of view) but further testing is certainly needed. For instance, IPython console plugin has not been tested at all (don't have IPython 1.0 installed).

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-05-17T02:08:49Z_

Impossible to test the IPython console plugin as the IPython repository ( https://github.com/ipython/ipython ) seems to be broken with Python 3. I don't know why... it's supposed be supporting both Python 2 and Python 3.

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-05-17T07:56:24Z_

Verified that launch is successful with Python 3.2.3 on Ubuntu 12.04 using revision 666e04a7301a . Had to start from clean user configuration file, but we knew that already.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-05-17T09:03:08Z_

Resetting Spyder configuration file is only required for Python 3.2 if I remember correctly, isn't it?

BTW, after that, are you able to switch from Python 3.2 to Python 2.7 and vice-versa without having to do a 'spyder --reset' systematically?

**Comment by spyder-issues-migrator** [comment]
_From [tak...@gmail.com](https://code.google.com/u/116141806100272241943/) on 2013-05-18T03:34:13Z_

IPython is definitely working on Python 3 (tested nightly at https://jenkins.shiningpanda-ci.com/ipython/job/ipython-multi/ ). But you can't run it directly from the repository, because it relies on setup.py invoking 2to3. So you'll need to install it to test it.

Ubuntu users can also get it through Julian Taylor's ipython-dev PPA: https://launchpad.net/~jtaylor/+archive/ipython-dev

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-05-18T06:01:38Z_

@-takowl: thanks for the info! didn't know about the fact that IPython calls on 2to3 during installation.

**Comment by spyder-issues-migrator** [comment]
_From [lizhenqi...@gmail.com](https://code.google.com/u/102288932687224218465/) on 2013-05-18T08:35:50Z_

Hi,

I just pulled out the latest default revision and everything works fine under my Ubuntu 12.10 system after I deleted the old configuration files. Thanks for the hard work!

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-05-20T00:16:17Z_

Added guidelines for developers to maintain Python 2/Python 3 compatibility: https://code.google.com/p/spyderlib/wiki/NoteForContributors?ts=1369034125&updated=NoteForContributors#Python_2_/_Python_3_compatibility

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-05-20T09:03:19Z_

@-Pierre, regarding comment 28:

The short answer is that a reset is not always required but it seems to be the safest route to avoid other problems. Detailed answers below. 

There are really two things that drive whether a configuration reset is required. The first is the presence of u'' strings in .spyder.ini itself. The other is the path to the external Python interpreter. In that light, there are two system configurations that result in different problems. By the way, all of this testing is using Ubuntu 12.04 for the 3.2 results and Ubuntu 13.04 for the 3.3 results.

Switching between Python 2.7 and 3.2
\------------------------------------

Since 3.2 can't understand the u'' strings, a reset is required before you can launch with this version of Python. After that, it is possible to launch with Python 2.7 without doing a reset, however any external consoles will launch using Python 3.2 since the preferences will still point to that executable. This arrangement doesn't seem to play nicely, which may be an indicator of deeper problems with trying to run consoles with an interpreter environment other than the one in which Spyder itself is running. That probably deserves investigation elsewhere. So after you change the preferences to point to Python 2.7 for external consoles things start to improve. However, I have found that you really have to quit Spyder and start over after changing the external interpreter preference. At any rate, after going back to Python 2.7, if you want to switch to Python 3.2 again another configuration reset is required.

Switching between Python 2.7 and 3.3
\------------------------------------

Since the u'' syntax is supported with 3.3, Spyder launches fine with 3.3 without requiring a reset. It does, however, remove any u'' strings when it rewrites the configuration file out. This might cause problems going backward to 2.7 if any paths contain special characters. This has not been tested. The same problems with external console preferences show up as described in the 3.2 results. Having Spyder running in 3.3 while trying to run external consoles in 2.7 doesn't play well together (and vice versa), so you generally have to set the path to external interpreters appropriately so that versions match and then restart Spyder to avoid strange error messages in the consoles.

As a side effect of this testing, it seems that the option to set external consoles to use a different interpreter environment other than the one in which Spyder itself is running may not be functioning completely. We may not have done everything required to treat external consoles, their interpreters, and installed modules for those interpreters as completely independent of Spyder's interpreter environment (much like PyDev). Hard to know if we really *want* to follow that model given the complexity it brings.

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2013-05-21T06:49:11Z_

About the string, using from __future__ import unicode_literals can provide compatibility for python 2.7 and python 3.3 with unicode strings even after a configuration file rewrite.

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-05-21T13:31:29Z_

Revision d12c3026caee implements the change suggested by contrebasse in comment 36. However, the need to reset configuration when switching between Python versions is still required as described in comment 35. String literals are still stored to the config file with syntax u'' under Python 2.7 and with '' syntax under Python 3.X. This is because the __set method of UserConfig basically calls repr(text) on any string-like setting, which under Python 2.7 will produce u'text' and under 3.X would produce 'text'. https://code.google.com/p/spyderlib/source/browse/spyderlib/userconfig.py#321

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-05-21T13:48:16Z_

Correction to my last comment. UserConfig.__set() only calls repr() if the item isn't already text. If it is text, it just takes whatever the text object is and passes it along to RawConfigParser which basically just writes out the object as is. That would be u'text' for 2.7 and 'text' for 3.X.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-05-22T01:00:43Z_

**Blockedon:** spyderlib:1402

**Comment by spyder-issues-migrator** [comment]
_From [VanBoxem...@gmail.com](https://code.google.com/u/108779539249446421349/) on 2013-06-04T04:41:01Z_

Using Winpython's Spyder 2.3.0dev1, the object inspector is disabled. It used to give an error message though, you can still see it here: https://code.google.com/p/winpython/issues/detail?id=44 Is this a known issue or is it already fixed or should I open a seperate issue for this?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-06-04T08:47:49Z_

This is a known bug from WinPython.

See here: http://groups.google.com/group/winpython/browse_thread/thread/c65d379c912c3cc0 and there: https://code.google.com/p/winpython/issues/detail?id=50

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-09-09T07:23:06Z_

**Cc:** -jed.lud...@gmail.com

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-10-15T07:10:57Z_

I'd say this is fixed now. I'm developing Spyder using its Python 3 incarnation to catch any further errors, which need to be reported separately.

**Status:** Fixed  
  **Labels:** -Priority-High Priority-Critical
