### ISSUE TITLE
Spyder issue interfacing with external console

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#945]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2012-02-21T17:26:51Z_

Spyder Version:  2.2.0dev
Python Version:  2.7.2
Qt Version:      4.7.4, PyQt4 (API v1) 4.8.6 on Windows 7 

What steps will reproduce the problem?

 1. Run a long running script that contains a call to raw_input
2. That script executes an external process through subprocess.call
3. After the raw_input output appears if I attempt to type in the console I get the traceback listed below in the internal console window. What is the expected output? What do you see instead? Interaction should continue working as desired. What version of the product are you using? On what operating system? spyder 2.1. 

Please provide any additional information below

. Traceback (most recent call last):
  File "D:\Devel\spyderlib\spyderlib\widgets\externalshell\pythonshell.py", line 537, in send_to_process
    "toggle_inputhook_flag(True)")
  File "D:\Devel\spyderlib\spyderlib\utils\bsdsocket.py", line 64, in communicate
    write_packet(sock, command)
  File "D:\Devel\spyderlib\spyderlib\utils\bsdsocket.py", line 24, in write_packet
    sock.send(struct.pack("l", len(sent_data)) + sent_data)
socket.error: [Errno 10054] An existing connection was forcibly closed by the remote host

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=945_

**Comment by spyder-issues-migrator** [comment]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2012-02-21T15:43:35Z_

You should consider adding a timestamp (if possible) to the output in the internal console.

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-05-14T22:17:09Z_

Needs a test case to reproduce.

**Labels:** Cat-Console

**Comment by spyder-issues-migrator** [comment]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2012-06-01T15:44:41Z_

I was hoping someone might add some instrumentation to spyder so I could attempt to capture some information on this issue.  It's not one I have been able to forcibly reproduce as it only happens occasionally.  I'm pretty much running devel all the time now, so this would be no problem for me.

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-06-03T01:09:33Z_

If it helps, I actually have a patch that writes all bsdsocket communication to a file. I guess it is repeatable for dev, so here is it for dev.

**Cc:** techtonik@gmail.com  


**Attachment:** [bsdsocket_debug.diff](http://code.google.com/p/spyderlib/issues/detail?id=945#hc4)

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-06-02T01:16:00Z_

The external console is probably blocked by raw_input call and can not respond. issue #1016 contained similar traceback attempting to send data to dead console. This was fixed in 4032473a38f7 and may affect this issue as well.

**Blockedon:** spyderlib:1016

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-02T18:03:29Z_

I think this is fixed by now.

**Status:** Fixed
