### ISSUE TITLE
Hi I have this error when starting spyder through ananconda . what can I do to solve?

### ISSUE THREAD

**Issue by akbar1111111** [spyder-ide/spyder#9486]
Traceback (most recent call last):
File "C:\Users\Redbull\AppData\Local\conda\conda\envs\se4g\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\Redbull\AppData\Local\conda\conda\envs\se4g\lib\site-packages\spyder\app\start.py", line 179, in main
from spyder.app import mainwindow
File "C:\Users\Redbull\AppData\Local\conda\conda\envs\se4g\lib\site-packages\spyder\app\mainwindow.py", line 50, in 
requirements.check_qt()
File "C:\Users\Redbull\AppData\Local\conda\conda\envs\se4g\lib\site-packages\spyder\requirements.py", line 42, in check_qt
package_name, required_ver = qt_infos[qtpy.API]
KeyError: 'pyqt'

**Comment by ccordoba12** [comment]
Spyder doesn't work with PyQt4 anymore. Please use PyQt5 instead.

**Comment by akbar1111111** [comment]
Tnx @ccordoba12
