### ISSUE TITLE
importing from the wrong env halfway during startup

### ISSUE THREAD

**Issue by hungrayho** [spyder-ide/spyder#9509]
### What steps will reproduce the problem?

conda create --name p27 python=2.7 spyder
conda create --name p36 python=3.6 spyder
conda activate p36
spyder

### Traceback
```python-traceback
  File "/home/ray/anaconda3/envs/tfp36/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 153, in icon
    mime_type, _ = mime.guess_type(basename)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 294, in guess_type
    return _db.guess_type(url, strict)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 114, in guess_type
    scheme, url = urllib.splittype(url)
AttributeError: module 'urllib' has no attribute 'splittype'
Traceback (most recent call last):
  File "/home/ray/anaconda3/envs/tfp36/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 153, in icon
    mime_type, _ = mime.guess_type(basename)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 294, in guess_type
    return _db.guess_type(url, strict)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 114, in guess_type
    scheme, url = urllib.splittype(url)
AttributeError: module 'urllib' has no attribute 'splittype'
Traceback (most recent call last):
  File "/home/ray/anaconda3/envs/tfp36/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 153, in icon
    mime_type, _ = mime.guess_type(basename)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 294, in guess_type
    return _db.guess_type(url, strict)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 114, in guess_type
    scheme, url = urllib.splittype(url)
AttributeError: module 'urllib' has no attribute 'splittype'
Traceback (most recent call last):
  File "/home/ray/anaconda3/envs/tfp36/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 153, in icon
    mime_type, _ = mime.guess_type(basename)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 294, in guess_type
    return _db.guess_type(url, strict)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 114, in guess_type
    scheme, url = urllib.splittype(url)
AttributeError: module 'urllib' has no attribute 'splittype'
Traceback (most recent call last):
  File "/home/ray/anaconda3/envs/tfp36/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 153, in icon
    mime_type, _ = mime.guess_type(basename)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 294, in guess_type
    return _db.guess_type(url, strict)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 114, in guess_type
    scheme, url = urllib.splittype(url)
AttributeError: module 'urllib' has no attribute 'splittype'
Traceback (most recent call last):
  File "/home/ray/anaconda3/envs/tfp36/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 153, in icon
    mime_type, _ = mime.guess_type(basename)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 294, in guess_type
    return _db.guess_type(url, strict)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 114, in guess_type
    scheme, url = urllib.splittype(url)
AttributeError: module 'urllib' has no attribute 'splittype'
Traceback (most recent call last):
  File "/home/ray/anaconda3/envs/tfp36/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 153, in icon
    mime_type, _ = mime.guess_type(basename)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 294, in guess_type
    return _db.guess_type(url, strict)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 114, in guess_type
    scheme, url = urllib.splittype(url)
AttributeError: module 'urllib' has no attribute 'splittype'
Traceback (most recent call last):
  File "/home/ray/anaconda3/envs/tfp36/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 153, in icon
    mime_type, _ = mime.guess_type(basename)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 294, in guess_type
    return _db.guess_type(url, strict)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 114, in guess_type
    scheme, url = urllib.splittype(url)
AttributeError: module 'urllib' has no attribute 'splittype'
Traceback (most recent call last):
  File "/home/ray/anaconda3/envs/tfp36/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 153, in icon
    mime_type, _ = mime.guess_type(basename)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 294, in guess_type
    return _db.guess_type(url, strict)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 114, in guess_type
    scheme, url = urllib.splittype(url)
AttributeError: module 'urllib' has no attribute 'splittype'
Traceback (most recent call last):
  File "/home/ray/anaconda3/envs/tfp36/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 153, in icon
    mime_type, _ = mime.guess_type(basename)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 294, in guess_type
    return _db.guess_type(url, strict)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 114, in guess_type
    scheme, url = urllib.splittype(url)
AttributeError: module 'urllib' has no attribute 'splittype'
Traceback (most recent call last):
  File "/home/ray/anaconda3/envs/tfp36/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 153, in icon
    mime_type, _ = mime.guess_type(basename)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 294, in guess_type
    return _db.guess_type(url, strict)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 114, in guess_type
    scheme, url = urllib.splittype(url)
AttributeError: module 'urllib' has no attribute 'splittype'
Traceback (most recent call last):
  File "/home/ray/anaconda3/envs/tfp36/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 153, in icon
    mime_type, _ = mime.guess_type(basename)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 294, in guess_type
    return _db.guess_type(url, strict)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 114, in guess_type
    scheme, url = urllib.splittype(url)
AttributeError: module 'urllib' has no attribute 'splittype'
Traceback (most recent call last):
  File "/home/ray/anaconda3/envs/tfp36/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 153, in icon
    mime_type, _ = mime.guess_type(basename)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 294, in guess_type
    return _db.guess_type(url, strict)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 114, in guess_type
    scheme, url = urllib.splittype(url)
AttributeError: module 'urllib' has no attribute 'splittype'
Traceback (most recent call last):
  File "/home/ray/anaconda3/envs/tfp36/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 153, in icon
    mime_type, _ = mime.guess_type(basename)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 294, in guess_type
    return _db.guess_type(url, strict)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 114, in guess_type
    scheme, url = urllib.splittype(url)
AttributeError: module 'urllib' has no attribute 'splittype'
WARNING:traitlets:kernel restarted
WARNING:traitlets:kernel restarted
WARNING:traitlets:kernel restarted
WARNING:traitlets:kernel restarted
WARNING:traitlets:KernelRestarter: restart failed
WARNING:traitlets:kernel died: 18.01430344581604
WARNING:traitlets:kernel died: 18.01720094680786
WARNING:traitlets:kernel died: 18.017199516296387
WARNING:traitlets:kernel died: 18.01717758178711
WARNING:traitlets:kernel died: 18.014400243759155
WARNING:traitlets:kernel died: 18.017199516296387
```

## Versions

* Spyder version: 3.3.4 
* Python version: 3.6.8
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-50-generic

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  2.0.1 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
psutil >=0.3      :  5.6.1 (OK)
nbconvert >=4.0   :  None (NOK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
> Traceback (most recent call last):
  File "/home/ray/anaconda3/envs/tfp36/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 153, in icon
    mime_type, _ = mime.guess_type(basename)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 294, in guess_type
    return _db.guess_type(url, strict)
  File "/home/ray/anaconda3/envs/tfp27/lib/python2.7/mimetypes.py", line 114, in guess_type
    scheme, url = urllib.splittype(url)
AttributeError: module 'urllib' has no attribute 'splittype'

You can see from your traceback that (somehow) you're mixing two envs: `tfp36` and `tfp27`. I don't know how you managed to do that (probably a wrong PATH manipulation), but that's not a Spyder problem, just an issue in your side that you need to fix by yourself.
