### ISSUE TITLE
Closing additional editor window produces traceback and primary editor breakdown

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#951]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-02-24T18:15:40Z_

What steps will reproduce the problem?

 1. From the primary editor, right click on the tab for a file currently open.
2. Select "New window"
3. Do some editing work in the new window.
4. Close the new window. What is the expected output? What do you see instead? Expect window to close quietly. Instead, the following traceback appears in the internal console:

Traceback (most recent call last):
  File "C:\src\spyderlib-default\spyderlib\widgets\editor.py", line 228, in update_queue
    end_callback = self.end_callbacks.pop(id(thread))
KeyError: 232249072
  File "C:\src\spyderlib-default\spyderlib\plugins\editor.py", line 1227, in todo_results_changed
    editorstack = self.get_current_editorstack()
  File "C:\src\spyderlib-default\spyderlib\plugins\editor.py", line 1134, in get_current_editorstack
    editorstack = self.__get_focus_editorstack()
  File "C:\src\spyderlib-default\spyderlib\plugins\editor.py", line 891, in __get_focus_editorstack
    if editorstack.isAncestorOf(fwidget):
RuntimeError: underlying C/C++ object has been deleted

Editing and saving in the primary editor then produces more tracebacks. Double clicking a file in the Project explorer to open it no longer opens the file in the primary editor. Any attempt to open another new editor window produces more similar tracebacks. Please use labels and text to provide additional information. Python 2.7.2 on Windows 7
Spyder 2.2.0dev ( revision b35ae3d27441 )
PyQt4 4.8.5
Qt 4.7.3

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=951_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-02-26T07:05:00Z_

This issue was closed by revision 34cddf5267f4 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-02-26T07:05:11Z_

This issue was closed by revision ad9883e06bfd .
