### ISSUE TITLE
qtpy.PythonQtError: No Qt bindings could be found

### ISSUE THREAD

**Issue by alainagiangbui** [spyder-ide/spyder#9525]
Hi, so I downloaded Anaconda and tried opening it on terminal using the command $ anaconda-navigator, and it gave me this issue instead of normally opening it: 

Traceback (most recent call last):
  File "/Users/alainagiangbui/anaconda2/bin/anaconda-navigator", line 7, in <module>
    from anaconda_navigator.app.main import main
  File "/Users/alainagiangbui/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 22, in <module>
    from anaconda_navigator.utils.conda import is_conda_available
  File "/Users/alainagiangbui/anaconda2/lib/python2.7/site-packages/anaconda_navigator/utils/__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "/Users/alainagiangbui/anaconda2/lib/python2.7/site-packages/qtpy/__init__.py", line 208, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

I've tried looking at other issues / threads that has this problem, but none of the suggestions I tried worked for me. I've successfully opened Anaconda to use Spyder and Jupyter Notebook before. I think this is because I've played around with brew and conda and installed some things for another project, and now Anaconda is not opening. 

Can someone help me please? I'd really appreciate it. Thank you! 

Python version: 2.7.16
OS: macOS Sierra version 10.12.6

**Comment by ccordoba12** [comment]
Sorry, this is not a problem with Spyder but with Anaconda, so please report it there:

https://github.com/ContinuumIO/anaconda-issues/issues/
