### ISSUE TITLE
an error occure while starting the kernel

### ISSUE THREAD

**Issue by shireesha1998** [spyder-ide/spyder#9579]
### What steps will reproduce the problem?

An error ocurred while starting the kernel
Traceback (most recent call last):
File "C:\Users\Admin\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\Admin\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\Admin\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\Admin\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 279, in main
import_spydercustomize()
File "C:\Users\Admin\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 39, in import_spydercustomize
import spydercustomize
File "C:\Users\Admin\Anaconda3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 25, in 
from IPython.core.getipython import get_ipython
File "C:\Users\Admin\Anaconda3\lib\site‑packages\IPython\__init__.py", line 55, in 
from .terminal.embed import embed
File "C:\Users\Admin\Anaconda3\lib\site‑packages\IPython\terminal\embed.py", line 17, in 
from IPython.terminal.ipapp import load_default_config
File "C:\Users\Admin\Anaconda3\lib\site‑packages\IPython\terminal\ipapp.py", line 28, in 
from IPython.core.magics import (
File "C:\Users\Admin\Anaconda3\lib\site‑packages\IPython\core\magics\__init__.py", line 18, in 
from .code import CodeMagics, MacroToEdit
File "C:\Users\Admin\Anaconda3\lib\site‑packages\IPython\core\magics\code.py", line 23, in 
from urllib.request import urlopen
File "C:\Users\Admin\Anaconda3\lib\urllib\request.py", line 86, in 
import email
File "C:\Users\Admin\email.py", line 8, in 
import smtplib
File "C:\Users\Admin\Anaconda3\lib\smtplib.py", line 47, in 
import email.utils
ModuleNotFoundError: No module named 'email.utils'; 'email' is not a package

## Versions

* Spyder version: 3.3.4 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
> C:\Users\Admin\email.py

Please remove or rename this file to avoid this problem.

**Comment by shireesha1998** [comment]
How can I rename it

**Comment by ccordoba12** [comment]
Put it a different name, whatever name you like but email.py

**Comment by shireesha1998** [comment]
I am receiving the same problem

**Comment by shireesha1998** [comment]
When I restart the kernel it's saying kernal died

**Comment by shireesha1998** [comment]
Sorry the problem is solved thank you very much
