### ISSUE TITLE
refresh problem n the console

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#961]
_From [pi...@synchrotron-soleil.fr](https://code.google.com/u/111976521841338120241/) on 2012-03-03T11:44:39Z_

What steps will reproduce the problem?

 Open spyder 2.1.8 (Debia unstable)

and switch from one virtual desktop to another one

and sometimes I got this error message 

Please provide any additional information below

. Python 2.7.2+ (default, Jan 20 2012, 23:05:38) 
[GCC 4.6.2] on linux2
Type "copyright", "credits" or "license" for more information.

\>>> Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/__init__.py", line 201, in visibility_changed
    self.refresh_plugin() #XXX Is it a good idea?
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 368, in refresh_plugin
    self.set_object_text(None, force_refresh=False)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 531, in set_object_text
    found = self.show_help(text, ignore_unknown=ignore_unknown)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 719, in show_help
    self.set_sphinx_text(doc_text)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 683, in set_sphinx_text
    ) &#37; (sphinx.__version__, str(error)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 43: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/__init__.py", line 201, in visibility_changed
    self.refresh_plugin() #XXX Is it a good idea?
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 368, in refresh_plugin
    self.set_object_text(None, force_refresh=False)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 531, in set_object_text
    found = self.show_help(text, ignore_unknown=ignore_unknown)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 719, in show_help
    self.set_sphinx_text(doc_text)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 683, in set_sphinx_text
    ) &#37; (sphinx.__version__, str(error)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 43: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/__init__.py", line 201, in visibility_changed
    self.refresh_plugin() #XXX Is it a good idea?
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 368, in refresh_plugin
    self.set_object_text(None, force_refresh=False)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 531, in set_object_text
    found = self.show_help(text, ignore_unknown=ignore_unknown)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 719, in show_help
    self.set_sphinx_text(doc_text)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 683, in set_sphinx_text
    ) &#37; (sphinx.__version__, str(error)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 43: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/__init__.py", line 201, in visibility_changed
    self.refresh_plugin() #XXX Is it a good idea?
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 368, in refresh_plugin
    self.set_object_text(None, force_refresh=False)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 531, in set_object_text
    found = self.show_help(text, ignore_unknown=ignore_unknown)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 719, in show_help
    self.set_sphinx_text(doc_text)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 683, in set_sphinx_text
    ) &#37; (sphinx.__version__, str(error)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 43: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/__init__.py", line 201, in visibility_changed
    self.refresh_plugin() #XXX Is it a good idea?
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 368, in refresh_plugin
    self.set_object_text(None, force_refresh=False)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 531, in set_object_text
    found = self.show_help(text, ignore_unknown=ignore_unknown)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 719, in show_help
    self.set_sphinx_text(doc_text)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 683, in set_sphinx_text
    ) &#37; (sphinx.__version__, str(error)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 43: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/__init__.py", line 201, in visibility_changed
    self.refresh_plugin() #XXX Is it a good idea?
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 368, in refresh_plugin
    self.set_object_text(None, force_refresh=False)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 531, in set_object_text
    found = self.show_help(text, ignore_unknown=ignore_unknown)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 719, in show_help
    self.set_sphinx_text(doc_text)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 683, in set_sphinx_text
    ) &#37; (sphinx.__version__, str(error)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 43: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/__init__.py", line 201, in visibility_changed
    self.refresh_plugin() #XXX Is it a good idea?
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 368, in refresh_plugin
    self.set_object_text(None, force_refresh=False)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 531, in set_object_text
    found = self.show_help(text, ignore_unknown=ignore_unknown)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 719, in show_help
    self.set_sphinx_text(doc_text)
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 683, in set_sphinx_text
    ) &#37; (sphinx.__version__, str(error)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 43: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/__init__.py", line 201, in visibility_changed
    self.refresh_plugin() #XXX Is it a good idea?
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 368, in refresh_plugin
    self.set_object_text(None, force_refresh=Fal...

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=961_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T08:31:19Z_

This issue was closed by revision 1f190b5e05d7 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T08:31:20Z_

This issue was closed by revision abf65b6de70c .
