### ISSUE TITLE
traceback importing existing directory

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#962]
_From [gerard.l...@adfonic.com](https://code.google.com/u/108422329362870420158/) on 2012-03-04T15:47:22Z_

What steps will reproduce the problem?

 1. git pull a program
2. open spyder and select Import > Existing directory
3. browse to the path containing .py files What is the expected output? What do you see instead? Expected - all .py and associated files are imported into a new project
Actual - a traceback occurs:

Python 2.7.2 (default, Jan 31 2012, 13:19:49) 
[GCC 4.6.2 20120120 (prerelease)] on linux2
Type "copyright", "credits" or "license" for more information.

\>>> Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 830, in import_existing_directory
    self.add_project(folder)
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/projectexplorer.py", line 686, in add_project
    shutil.copytree(folder, dst)
  File "/usr/lib/python2.7/shutil.py", line 174, in copytree
    os.makedirs(dst)
  File "/usr/lib/python2.7/os.py", line 145, in makedirs
    head, tail = path.split(name)
  File "/usr/lib/python2.7/posixpath.py", line 83, in split
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind' What version of the product are you using? On what operating system? spyder 2.1.8
python 2.7

Archlinux, using aur build https://aur.archlinux.org/packages.php?ID=56569 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=962_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T08:43:19Z_

This issue was updated by revision 5f8cf5aafd20 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T08:43:19Z_

This issue was updated by revision de0701ab38c9 .

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T08:50:58Z_

issue #967 has been merged into this issue.
