### ISSUE TITLE
Tools-> Preferences Throws Exception

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#963]
_From [efeldma...@gmail.com](https://code.google.com/u/117275408094784049799/) on 2012-03-05T23:44:42Z_

Spyder Version:  2.1.8
Python Version:  2.7.2
Qt Version:      4.7.4, PySide 1.0.9 on Windows 

What steps will reproduce the problem?

 1. Attempt to go to tools->Preferences
2. In python interpreter on right side there is a stack trace What is the expected output? What do you see instead? I see stack trace listed below 

Please provide any additional information below

. Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 1632, in edit_preferences
    widget = plugin.create_configwidget(dlg)
  File "C:\Python27\lib\site-packages\spyderlib\plugins\__init__.py", line 159, in create_configwidget
    configwidget.initialize()
  File "C:\Python27\lib\site-packages\spyderlib\plugins\configdialog.py", line 46, in initialize
    self.load_from_conf()
  File "C:\Python27\lib\site-packages\spyderlib\plugins\configdialog.py", line 241, in load_from_conf
    checkbox.setChecked(self.get_option(option, default))
RuntimeError: Internal C++ object (PySide.QtGui.QCheckBox) already deleted.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=963_

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-03-06T23:47:48Z_

Hi.

Is this repeatable?

If yes, can you try with newer PySide 1.1.0 at http://qt-project.org/wiki/PySide_Binaries_Windows so we can boost our requirements?

**Labels:** Component-PySide

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-03-07T00:24:18Z_

A known problem, actually. We are waiting for PySide 1.1.1 to see if we can properly debug the issue, which I believe everyone can do only on Linux right now.

**Status:** Duplicate  
  **Mergedinto:** 897
