### ISSUE TITLE
Need help to finding error line in Spyder IDE

### ISSUE THREAD

**Issue by bestazad** [spyder-ide/spyder#9645]
I use Spyder IDE, but most of the time I can not find the line that the error occurred easily. For example this is one of those errrors:

    runfile('C:/Users/m/Desktop/python/third.py', wdir='C:/Users/m/Desktop/python')
    Traceback (most recent call last):
    
      File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3267, in run_code
        exec(code_obj, self.user_global_ns, self.user_ns)
    
      File "<ipython-input-1-22ecdcbaada4>", line 1, in <module>
        runfile('C:/Users/m/Desktop/python/third.py', wdir='C:/Users/m/Desktop/python')
    
      File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
        execfile(filename, namespace)
    
      File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
        exec(compile(f.read(), filename, 'exec'), namespace)
    
      File "C:/Users/m/Desktop/python/third.py", line 134
        predicted_stock_price = (predicted_stock_price + 1) *
                                                              ^
    SyntaxError: invalid syntax

How can I understand which line of code caused the error? Why this IDE doesn't show the error line simply like other IDEs?

**Comment by ccordoba12** [comment]
You have to start reading errors from the bottom to the top. In this case, the error is found in the last lines:

```
File "C:/Users/m/Desktop/python/third.py", line 134
    predicted_stock_price = (predicted_stock_price + 1) *

SyntaxError: invalid syntax
```

I'm closing this because it's not a Spyder problem, just a question.
