### ISSUE TITLE
Can not open Preferences Dialog

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#966]
_From [rajabiy@gmail.com](https://code.google.com/u/rajabiy@gmail.com/) on 2012-03-08T04:17:21Z_

Spyder Version:  2.1.8
Python Version:  2.7.2
Qt Version:      4.7.4, PySide 1.1.0 on Windows 

What steps will reproduce the problem?

 1.When I click "Preferences" button I Get This

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 1632, in edit_preferences
    widget = plugin.create_configwidget(dlg)
  File "C:\Python27\lib\site-packages\spyderlib\plugins\__init__.py", line 159, in create_configwidget
    configwidget.initialize()
  File "C:\Python27\lib\site-packages\spyderlib\plugins\configdialog.py", line 46, in initialize
    self.load_from_conf()
  File "C:\Python27\lib\site-packages\spyderlib\plugins\configdialog.py", line 241, in load_from_conf
    checkbox.setChecked(self.get_option(option, default))
RuntimeError: Internal C++ object (PySide.QtGui.QCheckBox) already deleted.

**Attachment:** [err.PNG](http://code.google.com/p/spyderlib/issues/detail?id=966)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=966_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-03-08T05:13:47Z_

This is a known problem and seems to be fixed in the PySide 1.1.1

**Status:** Duplicate  
  **Mergedinto:** 897
