### ISSUE TITLE
Clicking right in spyder for first time led to this error

### ISSUE THREAD

**Issue by RnoldR** [spyder-ide/spyder#9664]
### What steps will reproduce the problem?

Create new environment
Install spyder 4.0b2
start5 spyder
right click in window
and get into issue reporter

### Traceback
```python-traceback
  File "/home/arnold/bin/anaconda/envs/GIS/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 744, in <lambda>
    lambda c=client: self.process_started(c))
  File "/home/arnold/bin/anaconda/envs/GIS/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 1380, in process_started
    self.main.variableexplorer.add_shellwidget(client.shellwidget)
  File "/home/arnold/bin/anaconda/envs/GIS/lib/python3.7/site-packages/spyder/plugins/variableexplorer/plugin.py", line 137, in add_shellwidget
    nsb.setup(**self.get_settings())
  File "/home/arnold/bin/anaconda/envs/GIS/lib/python3.7/site-packages/spyder/plugins/variableexplorer/plugin.py", line 71, in get_settings
    settings[name] = self.get_option(name)
  File "/home/arnold/bin/anaconda/envs/GIS/lib/python3.7/site-packages/spyder/api/plugins.py", line 172, in get_option
    return CONF.get(self.CONF_SECTION, option, default)
  File "/home/arnold/bin/anaconda/envs/GIS/lib/python3.7/site-packages/spyder/config/user.py", line 382, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'show_callable_attributes' in section: 'variable_explorer'
Traceback (most recent call last):
  File "/home/arnold/bin/anaconda/envs/GIS/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/home/arnold/bin/anaconda/envs/GIS/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/widgets/namespacebrowser.py", line 224, in _handle_execute_reply
    self.set_namespace_view_settings()  File "/home/arnold/bin/anaconda/envs/GIS/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/widgets/namespacebrowser.py", line 77, in set_namespace_view_settings
    self.namespacebrowser.get_view_settings())
  File "/home/arnold/bin/anaconda/envs/GIS/lib/python3.7/site-packages/spyder/plugins/variableexplorer/widgets/namespacebrowser.py", line 244, in get_view_settings
    settings[name] = getattr(self, name)
AttributeError: 'NamespaceBrowser' object has no attribute 'show_callable_attributes'
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 4.0.0b2 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-51-generic

### Dependencies

```
pygments >=2.0     :  2.4.2 (OK)
qdarkstyle >=2.6.4 :  2.7 (OK)
sphinx >=0.6.6     :  2.1.0 (OK)
psutil >=0.3       :  5.6.2 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.5.0 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.16.4 (OK)
sympy >=0.7.3      :  None (NOK)
cython >=0.21      :  None (NOK)
qtconsole >=4.2.0  :  4.5.1 (OK)
IPython >=4.0      :  7.5.0 (OK)
matplotlib >=2.0.0 :  3.1.0 (OK)
pylint >=0.25      :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
This will be solved in our next beta, to be released in a couple of days.
