### ISSUE TITLE
Spyder has encountered an internal problem

### ISSUE THREAD

**Issue by rmondo** [spyder-ide/spyder#9675]
### What steps will reproduce the problem?

conda install -c spyder-ide spyder-kernels
open anaconda
launch spyder

### Traceback
```python-traceback
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 744, in <lambda>
    lambda c=client: self.process_started(c))
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 1380, in process_started
    self.main.variableexplorer.add_shellwidget(client.shellwidget)
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/variableexplorer/plugin.py", line 137, in add_shellwidget
    nsb.setup(**self.get_settings())
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/variableexplorer/plugin.py", line 71, in get_settings
    settings[name] = self.get_option(name)
  File "/anaconda3/lib/python3.7/site-packages/spyder/api/plugins.py", line 172, in get_option
    return CONF.get(self.CONF_SECTION, option, default)
  File "/anaconda3/lib/python3.7/site-packages/spyder/config/user.py", line 382, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'show_callable_attributes' in section: 'variable_explorer'
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/widgets/namespacebrowser.py", line 224, in _handle_execute_reply
    self.set_namespace_view_settings()
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/widgets/namespacebrowser.py", line 77, in set_namespace_view_settings
    self.namespacebrowser.get_view_settings())
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/variableexplorer/widgets/namespacebrowser.py", line 244, in get_view_settings
    settings[name] = getattr(self, name)
AttributeError: 'NamespaceBrowser' object has no attribute 'show_callable_attributes'
```

## Versions

* Spyder version: 4.0.0b2 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.6.0

### Dependencies

```
pygments >=2.0     :  2.3.1 (OK)
qdarkstyle >=2.6.4 :  2.7 (OK)
sphinx >=0.6.6     :  1.8.5 (OK)
psutil >=0.3       :  5.6.1 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.4.1 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.16.2 (OK)
sympy >=0.7.3      :  1.3 (OK)
cython >=0.21      :  0.29.6 (OK)
qtconsole >=4.2.0  :  4.4.3 (OK)
IPython >=4.0      :  7.4.0 (OK)
matplotlib >=2.0.0 :  3.0.3 (OK)
pylint >=0.25      :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
This error will be fixed in our next beta, to be released in a couple of days. For now, please downgrade to spyder-kernel 1.3.3
