### ISSUE TITLE
Internal Python Language Server error

### ISSUE THREAD

**Issue by shreyaskamathkm** [spyder-ide/spyder#9676]
### What steps will reproduce the problem?

Updated the conda environment using conda update --all. This downgraded the spyder to 3.3.4. After the install, updated the spyder using 

conda update qt pyqt
conda install -c spyder-ide spyder=4.0.0b2

Now the spyder is not able to connect to the kernel.

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyls_jsonrpc\endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyls_jsonrpc\endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyls_jsonrpc\dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyls\python_ls.py", line 236, in m_text_document__did_close
    self.workspace.rm_document(textDocument['uri'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyls\workspace.py", line 74, in rm_document
    self._docs.pop(doc_uri)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyls_jsonrpc\endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyls_jsonrpc\endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyls_jsonrpc\dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyls\python_ls.py", line 236, in m_text_document__did_close
    self.workspace.rm_document(textDocument['uri'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyls\workspace.py", line 74, in rm_document
    self._docs.pop(doc_uri)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 744, in <lambda>
    lambda c=client: self.process_started(c))
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 1380, in process_started
    self.main.variableexplorer.add_shellwidget(client.shellwidget)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\plugin.py", line 137, in add_shellwidget
    nsb.setup(**self.get_settings())
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\plugin.py", line 71, in get_settings
    settings[name] = self.get_option(name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\api\plugins.py", line 172, in get_option
    return CONF.get(self.CONF_SECTION, option, default)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 382, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'show_callable_attributes' in section: 'variable_explorer'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 224, in _handle_execute_reply
    self.set_namespace_view_settings()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 77, in set_namespace_view_settings
    self.namespacebrowser.get_view_settings())
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\namespacebrowser.py", line 244, in get_view_settings
    settings[name] = getattr(self, name)
AttributeError: 'NamespaceBrowser' object has no attribute 'show_callable_attributes'
```

## Versions

* Spyder version: 4.0.0b2 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0     :  2.4.2 (OK)
qdarkstyle >=2.6.4 :  2.6.8 (OK)
sphinx >=0.6.6     :  2.1.0 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.5.0 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.16.4 (OK)
sympy >=0.7.3      :  1.4 (OK)
cython >=0.21      :  0.29.10 (OK)
qtconsole >=4.2.0  :  4.5.1 (OK)
IPython >=4.0      :  7.5.0 (OK)
matplotlib >=2.0.0 :  3.1.0 (OK)
pylint >=0.25      :  2.3.1 (OK)
```

**Comment by shreyaskamathkm92** [comment]
Applying `conda install spyder-kernels=1.3` fixed the problem.

**Comment by ccordoba12** [comment]
Yes, that's the right fix. You can also run

    conda install -c spyder-ide -f spyder=4.0.0b2

to get a new build of beta2 that has a fix for this.
