### ISSUE TITLE
Console not starting

### ISSUE THREAD

**Issue by harshit1008** [spyder-ide/spyder#9683]
### What steps will reproduce the problem?

How to solve this problem so that I can work on the python

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 744, in <lambda>
    lambda c=client: self.process_started(c))
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 1380, in process_started
    self.main.variableexplorer.add_shellwidget(client.shellwidget)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\plugin.py", line 137, in add_shellwidget
    nsb.setup(**self.get_settings())
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\plugin.py", line 71, in get_settings
    settings[name] = self.get_option(name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\api\plugins.py", line 172, in get_option
    return CONF.get(self.CONF_SECTION, option, default)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\config\user.py", line 382, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'show_callable_attributes' in section: 'variable_explorer'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 224, in _handle_execute_reply
    self.set_namespace_view_settings()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 77, in set_namespace_view_settings
    self.namespacebrowser.get_view_settings())
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\namespacebrowser.py", line 244, in get_view_settings
    settings[name] = getattr(self, name)
AttributeError: 'NamespaceBrowser' object has no attribute 'show_callable_attributes'
```

## Versions

* Spyder version: 4.0.0b2 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0     :  2.3.1 (OK)
qdarkstyle >=2.6.4 :  2.7 (OK)
sphinx >=0.6.6     :  1.8.2 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.4.0 (OK)
pandas >=0.13.1    :  0.23.4 (OK)
numpy >=1.7        :  1.16.4 (OK)
sympy >=0.7.3      :  1.3 (OK)
cython >=0.21      :  0.29.2 (OK)
qtconsole >=4.2.0  :  4.4.3 (OK)
IPython >=4.0      :  7.2.0 (OK)
matplotlib >=2.0.0 :  3.0.2 (OK)
pylint >=0.25      :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Please downgrade spyder-kernels with the following command

    conda install spyder-kernels=1.3

**Comment by harshit1008** [comment]
Brother, Thank you very much!

**Comment by harshit1008** [comment]
Thank you vry much, now it's working.....
