### ISSUE TITLE
Issue to start on ubuntu 19.04

### ISSUE THREAD

**Issue by sednabcn** [spyder-ide/spyder#9701]
### What steps will reproduce the problem?

namespacebrowser.py
 line 138 in dispatch handler(msg)
 line 224, in handle_execute_reply

### Traceback
```python-traceback
  File "/usr/local/lib/python3.7/dist-packages/spyder/plugins/ipythonconsole/plugin.py", line 744, in <lambda>
    lambda c=client: self.process_started(c))
  File "/usr/local/lib/python3.7/dist-packages/spyder/plugins/ipythonconsole/plugin.py", line 1380, in process_started
    self.main.variableexplorer.add_shellwidget(client.shellwidget)
  File "/usr/local/lib/python3.7/dist-packages/spyder/plugins/variableexplorer/plugin.py", line 137, in add_shellwidget
    nsb.setup(**self.get_settings())
  File "/usr/local/lib/python3.7/dist-packages/spyder/plugins/variableexplorer/plugin.py", line 71, in get_settings
    settings[name] = self.get_option(name)
  File "/usr/local/lib/python3.7/dist-packages/spyder/api/plugins.py", line 172, in get_option
    return CONF.get(self.CONF_SECTION, option, default)
  File "/usr/local/lib/python3.7/dist-packages/spyder/config/user.py", line 382, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'show_callable_attributes' in section: 'variable_explorer'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/local/lib/python3.7/dist-packages/spyder/plugins/ipythonconsole/widgets/namespacebrowser.py", line 224, in _handle_execute_reply

WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Must specify two-factor authentication OTP code.', 'documentation_url': 'https://developer.github.com/v3/auth#working-with-two-factor-authentication'}}
```

## Versions

* Spyder version: 4.0.0b2 
* Python version: 3.7.3
* Qt version: 5.12.2
* PyQt5 version: 5.12.1
* Operating System: Linux 5.0.0-17-generic

### Dependencies

```
pygments >=2.0     :  2.4.0 (OK)
qdarkstyle >=2.6.4 :  2.7 (OK)
sphinx >=0.6.6     :  1.8.5 (OK)
psutil >=0.3       :  5.5.1 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.5.0 (OK)
pandas >=0.13.1    :  0.23.3 (OK)
numpy >=1.7        :  1.16.2 (OK)
sympy >=0.7.3      :  None (NOK)
cython >=0.21      :  None (NOK)
qtconsole >=4.2.0  :  4.4.4 (OK)
IPython >=4.0      :  7.5.0 (OK)
matplotlib >=2.0.0 :  3.1.0 (OK)
pylint >=0.25      :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Please downgrade spyder-kernels with

    pip install spyder-kernels==1.3.3

to fix this.
