### ISSUE TITLE
can't see variables

### ISSUE THREAD

**Issue by mashagua** [spyder-ide/spyder#9702]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "F:\Users\masha\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 260, in get_value
    value = self.df.iat[row, column]
  File "F:\Users\masha\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 2142, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "F:\Users\masha\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2530, in _get_value
    return com._maybe_box_datetimelike(series._values[index])
  File "F:\Users\masha\Anaconda3\lib\site-packages\pandas\core\common.py", line 87, in _maybe_box_datetimelike
    value = tslib.Timestamp(value)
  File "pandas\_libs\tslibs\timestamps.pyx", line 635, in pandas._libs.tslibs.timestamps.Timestamp.__new__
  File "pandas\_libs\tslibs\conversion.pyx", line 300, in pandas._libs.tslibs.conversion.convert_to_tsobject
  File "pandas\_libs\tslibs\conversion.pyx", line 394, in pandas._libs.tslibs.conversion.convert_datetime_to_tsobject
  File "pandas\_libs\tslibs\np_datetime.pyx", line 121, in pandas._libs.tslibs.np_datetime.check_dts_bounds
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 9999-12-31 00:00:00

Traceback (most recent call last):
  File "F:\Users\masha\Anaconda3\lib\site-packages\spyder\widgets\var

**Comment by ccordoba12** [comment]
This is not a problem with Spyder, it's an installation issue with Pandas.

If you used pip to install/update any package present in Anaconda, you most probably corrupted your installation and now you have to reinstall it.
