### ISSUE TITLE
Console window not working - traceback generated

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#976]
_From [shivakum...@gmail.com](https://code.google.com/u/116188783840908192901/) on 2012-03-22T23:24:11Z_

Spyder Version:  2.1.8
Python Version:  2.5.4
Qt Version:      4.8.0, PyQt4 (API v1) 4.9.1 on Windows 

What steps will reproduce the problem?

 1.Install spyder
2.Start
3.Traceback is generated for python shell handling
4.Press enter in console window, the traceback appears again
5.Close all interpreters in the console part of spyder
6.Right click and choose open interpreter or open IPython interpreter
7.In both cases python crashes and empty console window is opened, now go to step [4] - press enter to generate traceback What is the expected output? What do you see instead? Shell is expected to appear
Instead, traceback is seen 

Please provide any additional information below

. Traceback is as below:

D:\spyder>python c:\Python25\Scripts\spyder -d
Start of MainWindow constructor
Initializing...
End of MainWindow constructor
*** Start of MainWindow setup ***
Loading object inspector...
Loading outline explorer...
Loading editor...
Loading file explorer...
Loading history plugin...
Loading online help...
Loading project explorer...
Loading external console...
Loading namespace browser...
Setting up main window...
Setting up window...
*** End of MainWindow setup ***
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
Traceback (most recent call last):
  File "C:\Python25\Lib\site-packages\spyderlib\widgets\externalshell\pythonshell.py", line 537, in send_to_process
    "toggle_inputhook_flag(True)")
  File "C:\Python25\Lib\site-packages\spyderlib\utils\bsdsocket.py", line 64, in communicate
    write_packet(sock, command)
  File "C:\Python25\Lib\site-packages\spyderlib\utils\bsdsocket.py", line 24, in write_packet
    sock.send(struct.pack("l", len(sent_data)) + sent_data)
AttributeError: 'NoneType' object has no attribute 'send'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=976_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-24T00:59:28Z_

Already fixed by this changeset: https://code.google.com/p/spyderlib/source/detail?r=c7b02e997b7bc645240eea923cd49d43f1431138

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [shivakum...@gmail.com](https://code.google.com/u/116188783840908192901/) on 2012-03-24T08:32:48Z_

Issue is does not seem to be fixed with the correction indicated.

I applied the change in my installed version of spyder.

The exception is not occurring BUT, when "open interpreter" is chosen python.exe crashes, shell does not appear.
