### ISSUE TITLE
Adding site-packages to PYTHONPATH causes weird errors

### ISSUE THREAD

**Issue by BJWiley233** [spyder-ide/spyder#9775]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When I go to Preferences to change the Python interpreter for the virtual environment I created and restart the kernel I get an error saying `cannot import name 'constants'` and when I also try starting Spyder from inside the environment from cmd or bash shell I get a different error `cannot import name '_psutil_windows'`.  However when I remove PYTHONPATH from user variables it works.

### What steps reproduce the problem?

First 
1. Create new environment
2. Inside Spyder go to Tools >> Preferences >> Python Interpreter >> Change from default to Python 3.6.8 from new environment
3. Restart kernel and get below message 
```
An error ocurred while starting the kernel
Traceback (most recent call last):
File "C:\Users\bjwil\Anaconda3\envs\camelot\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\bjwil\Anaconda3\envs\camelot\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\bjwil\Anaconda3\Lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\bjwil\Anaconda3\Lib\site‑packages\spyder_kernels\console\start.py", line 297, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\bjwil\Anaconda3\Lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\bjwil\Anaconda3\Lib\site‑packages\ipykernel\connect.py", line 18, in 
import jupyter_client
File "C:\Users\bjwil\Anaconda3\Lib\site‑packages\jupyter_client\__init__.py", line 4, in 
from .connect import *
File "C:\Users\bjwil\Anaconda3\Lib\site‑packages\jupyter_client\connect.py", line 23, in 
import zmq
File "C:\Users\bjwil\Anaconda3\Lib\site‑packages\zmq\__init__.py", line 47, in 
from zmq import backend
File "C:\Users\bjwil\Anaconda3\Lib\site‑packages\zmq\backend\__init__.py", line 40, in 
reraise(*exc_info)
File "C:\Users\bjwil\Anaconda3\Lib\site‑packages\zmq\utils\sixcerpt.py", line 34, in reraise
raise value
File "C:\Users\bjwil\Anaconda3\Lib\site‑packages\zmq\backend\__init__.py", line 27, in 
_ns = select_backend(first)
File "C:\Users\bjwil\Anaconda3\Lib\site‑packages\zmq\backend\select.py", line 27, in select_backend
mod = __import__(name, fromlist=public_api)
File "C:\Users\bjwil\Anaconda3\Lib\site‑packages\zmq\backend\cython\__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
```

Second
1. In Anaconda interface in newly created environment install Spyder 3.3.5
2. From cmd.exe or bash shell activate environment
3. Call `spyder` inside shell and get below message
```
Traceback (most recent call last):
  File "C:\Users\bjwil\Anaconda3\envs\oetoolkits\Scripts\spyder-script.py", line 6, in <module>
    from spyder.app.start import main
  File "C:\Users\bjwil\Anaconda3\Lib\site-packages\spyder\app\start.py", line 36, in <module>
    from spyder.utils.external import lockfile
  File "C:\Users\bjwil\Anaconda3\Lib\site-packages\spyder\utils\external\lockfile.py", line 30, in <module>
    import psutil
  File "C:\Users\bjwil\Anaconda3\Lib\site-packages\psutil\__init__.py", line 146, in <module>
    from . import _pswindows as _psplatform
  File "C:\Users\bjwil\Anaconda3\Lib\site-packages\psutil\_pswindows.py", line 17, in <module>
    from . import _psutil_windows as cext
ImportError: cannot import name '_psutil_windows'
```

After I remove `C:\Users\*****\Anaconda3\Lib\site-packages` from `PYTHONPATH` under user variables and restart Spyder IDE and shell both ways above work with no errors.  I forget why I added a PYTHONPATH since I did it so long ago and it is personal computer so I don't document everything I do but will this always effect accessing different environment interpreters in Spyder?

## Versions

* Spyder version: 3.3.5
* Python version: 3.6.8
* Qt version: 5.9.3
* PyQt version: 5.9.2
* Operating System name/version: 
Windows 10 Home

**Comment by ccordoba12** [comment]
> After I remove C:\Users\*****\Anaconda3\Lib\site-packages from PYTHONPATH

You can't do that. By adding the site-packages of another environment to PYTHONPATH, you are effectively mixing the packages of two different Python installations, which causes the kind of errors you reported above.

The only thing you need to do to use a different Python interpreter in the IPython console is to select it in `Tools > Preferences > Python Interpreter`, as you mentioned above. You **don't** need to add the site-packages of your current interpreter or the one you want to select to PYTHONPATH for that.

**Comment by ccordoba12** [comment]
To avoid this in the future, we're going to forbid users to add a `site-packages` directory (or any sub-directory of it) through our PYTHONPATH manager in Spyder 4.

**Comment by ccordoba12** [comment]
> we're going to forbid users to add a site-packages directory

This was fixed already.
