### ISSUE TITLE
Preferences doesn't open

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#980]
_From [LordF...@gmail.com](https://code.google.com/u/108517049192670066680/) on 2012-03-30T06:28:33Z_

Spyder Version:  2.1.8
Python Version:  2.7.2
Qt Version:      4.7.4, PySide 1.1.0 on Windows 

What steps will reproduce the problem?

 1. Click the Tools menu header and then click the Preferences menu item What is the expected output? What do you see instead? The preferences window should display.  Instead, errors show up in the internal console. 

Please provide any additional information below

. Internal console output:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 1632, in edit_preferences
    widget = plugin.create_configwidget(dlg)
  File "C:\Python27\lib\site-packages\spyderlib\plugins\__init__.py", line 159, in create_configwidget
    configwidget.initialize()
  File "C:\Python27\lib\site-packages\spyderlib\plugins\configdialog.py", line 46, in initialize
    self.load_from_conf()
  File "C:\Python27\lib\site-packages\spyderlib\plugins\configdialog.py", line 241, in load_from_conf
    checkbox.setChecked(self.get_option(option, default))
RuntimeError: Internal C++ object (PySide.QtGui.QCheckBox) already deleted.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=980_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-30T09:46:51Z_

This is already fixed in the development version (I'll have check the revision number before closing this issue). 

So this is fixed in forthcoming v2.1.9.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-30T13:53:29Z_

**Status:** Duplicate  
  **Mergedinto:** 897
