### ISSUE TITLE
Have Py2.7 and Spyder, but spyder won't open

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#982]
_From [chain.k...@gmail.com](https://code.google.com/u/101822032233939817967/) on 2012-04-01T10:04:06Z_

As listed in summary, I have python 2.7 and spyder-2.1.9_py27.exe, both correctly installed (at least Spyder appears to be).

When I try to open Spyder it does nothing.  I am new to python and IDE in general, so is do I have to open this through python or do I have the incorrect version?

I am using a Windows 7 64-bit OS.

Thanks

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=982_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-01T10:00:12Z_

Spyder requires some other libraries to be installed, as mentioned here in the documentation: http://packages.python.org/spyder/installation.html#dependencies Please check if your Python installation meets those requirements.

Besides, to be able to see the traceback (there is probably a traceback, i.e. an error message), you need to launch Spyder from a command window:
1. open a command window (Windows button+R, then type cmd.exe)
2. change directory to Spyder's main directory:
cd C:\Python27\Lib\site-packages\spyderlib
3. then launch Spyder:
python spyder.py --debug

Please post the full traceback here.

**Comment by spyder-issues-migrator** [comment]
_From [nar...@gmail.com](https://code.google.com/u/113789293587390882172/) on 2013-05-21T13:02:41Z_

Traceback (most recent call last):
  File "spyder.py", line 34, in \<module>
    from spyderlib.baseconfig import SUPPORTED_IPYTHON
ImportError: cannot import name SUPPORTED_IPYTHON

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-05-25T09:59:09Z_

This is the kind of traceback that may result from an incomplete uninstall. Please try to uninstall Spyder and remove manually the Lib\site-packages\spyderlib directory if necessary, then reinstall Spyder.

**Comment by spyder-issues-migrator** [comment]
_From [compas...@gmail.com](https://code.google.com/u/116371769291089086905/) on 2013-07-17T03:08:35Z_

I have the same issue in windows 7 (32bit) my traceback is


C:\Python27\Lib\site-packages\spyderlib>python spyder.py --debug
Traceback (most recent call last):
  File "spyder.py", line 33, in \<module>
    from spyderlib.utils.programs import is_module_installed
ImportError: No module named spyderlib.utils.programs

**Comment by spyder-issues-migrator** [comment]
_From [compas...@gmail.com](https://code.google.com/u/116371769291089086905/) on 2013-07-17T03:15:20Z_

reinstalled - same error - really looks like you guys have not included all the required elements in the win32 installer.

**Comment by spyder-issues-migrator** [comment]
_From [david.wa...@gmail.com](https://code.google.com/u/105247620634203395877/) on 2013-07-25T15:44:19Z_

C:\Python27\Lib\site-packages\spyderlib>python spyder.py --debug
Traceback (most recent call last):
  File "spyder.py", line 100, in \<module>
    from spyderlib.plugins.inspector import ObjectInspector
  File "C:\Python27\lib\site-packages\spyderlib\plugins\inspector.py", line 36,
in \<module>
    from spyderlib.widgets.ipython import IPythonControlWidget
  File "C:\Python27\lib\site-packages\spyderlib\widgets\ipython.py", line 12, in
 \<module>
    from IPython.frontend.qt.console.rich_ipython_widget import RichIPythonWidge
t
  File "C:\Python27\lib\site-packages\IPython\frontend\qt\console\rich_ipython_w
idget.py", line 15, in \<module>
    from IPython.external.qt import QtCore, QtGui
  File "C:\Python27\lib\site-packages\IPython\external\qt.py", line 53, in \<modu
le>
    raise ImportError("IPython requires PyQt4 >= 4.7, found %s"%QtCore.PYQT_VERS
ION_STR)
ImportError: IPython requires PyQt4 >= 4.7, found 4.10.2

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-09T20:04:59Z_

@-david: you need to update your IPython version to 0.13.2

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-09T20:07:23Z_

@-compass2k: You are running Spyder from its site-packages directory. That's not the way to do it, you just need to start it with by writing "spyder" in a cmd.exe

**Comment by spyder-issues-migrator** [comment]
_From [compas...@gmail.com](https://code.google.com/u/116371769291089086905/) on 2013-08-09T20:15:34Z_

Microsoft Windows [Version 6.1.7600]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\compass2k>spyder
'spyder' is not recognized as an internal or external command,
operable program or batch file.

\--------------------------
Microsoft Windows [Version 6.1.7600]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\compass2k>spyder
'spyder' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\compass2k>python spyder.py
python: can't open file 'spyder.py': [Errno 2] No such file or directory

\-------------------------
Still nothing.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-09T20:26:12Z_

Then you haven't installed it correctly (because it should work as I told you).

How did you install Spyder?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-01T20:42:01Z_

This clearly is an installation problem

**Status:** WontFix
