### ISSUE TITLE
Error in Ipython console when starting the kernel on Spyder startup 

### ISSUE THREAD

**Issue by jaib1** [spyder-ide/spyder#9832]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Error in Ipython console when launching Spyder: "An error occurred while starting the kernel"

```
Traceback (most recent call last):
File "C:\Users\Jai\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\Jai\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\Jai\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\Jai\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 298, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\Jai\Anaconda3\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\Jai\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 484, in initialize
self.init_kernel()
File "C:\Users\Jai\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 389, in init_kernel
user_ns=self.user_ns,
File "C:\Users\Jai\Anaconda3\lib\site‑packages\traitlets\config\configurable.py", line 412, in instance
inst = cls(*args, **kwargs)
File "C:\Users\Jai\Anaconda3\lib\site‑packages\spyder_kernels\console\kernel.py", line 37, in __init__
super(SpyderKernel, self).__init__(*args, **kwargs)
File "C:\Users\Jai\Anaconda3\lib\site‑packages\ipykernel\ipkernel.py", line 67, in __init__
kernel = self,
File "C:\Users\Jai\Anaconda3\lib\site‑packages\traitlets\config\configurable.py", line 412, in instance
inst = cls(*args, **kwargs)
File "C:\Users\Jai\Anaconda3\lib\site‑packages\IPython\core\interactiveshell.py", line 687, in __init__
self.init_magics()
File "C:\Users\Jai\Anaconda3\lib\site‑packages\ipykernel\zmqshell.py", line 593, in init_magics
super(ZMQInteractiveShell, self).init_magics()
File "C:\Users\Jai\Anaconda3\lib\site‑packages\IPython\core\interactiveshell.py", line 2239, in init_magics
m.PylabMagics, m.ScriptMagics,
File "C:\Users\Jai\Anaconda3\lib\site‑packages\IPython\core\magic.py", line 405, in register
m = m(shell=self.shell)
File "C:\Users\Jai\Anaconda3\lib\site‑packages\IPython\core\magics\osm.py", line 52, in __init__
self.execre = re.compile(r'(.*)\.(%s)$' % winext,re.IGNORECASE)
File "C:\Users\Jai\Anaconda3\lib\re.py", line 234, in compile
return _compile(pattern, flags)
File "C:\Users\Jai\Anaconda3\lib\re.py", line 286, in _compile
p = sre_compile.compile(pattern, flags)
File "C:\Users\Jai\Anaconda3\lib\sre_compile.py", line 764, in compile
p = sre_parse.parse(p, flags)
File "C:\Users\Jai\Anaconda3\lib\sre_parse.py", line 930, in parse
p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
File "C:\Users\Jai\Anaconda3\lib\sre_parse.py", line 426, in _parse_sub
not nested and not items))
File "C:\Users\Jai\Anaconda3\lib\sre_parse.py", line 816, in _parse
p = _parse_sub(source, state, sub_verbose, nested + 1)
File "C:\Users\Jai\Anaconda3\lib\sre_parse.py", line 426, in _parse_sub
not nested and not items))
File "C:\Users\Jai\Anaconda3\lib\sre_parse.py", line 507, in _parse
code = _escape(source, this, state)
File "C:\Users\Jai\Anaconda3\lib\sre_parse.py", line 369, in _escape
raise source.error("incomplete escape %s" % escape, len(escape))
re.error: incomplete escape \U at position 9
```
After getting this error, I tried the following:
`spyder --reset` 
`conda install spyder=3.3.6` (hangs while solving the environment)
`conda remove spyder` (errored: I have a very long error message I can add as a comment if helpful)
`conda remove ipykernel` (works)
`conda install ipykernel` (errored: I have a very long error message I can add as a comment if helpful)
`conda update conda -v` (errored: I have a very long error message I can add as a comment if helpful)

I also tried running `anaconda-clean --all` and uninstalling and reinstalling anaconda multiple times and restarting my PC, but this same error still occurs. I am thinking it may be an Anaconda issue, but installing new packages not related to Spyder seems to work fine.

### What steps reproduce the problem?

This error occurs upon launching spyder.

### What is the expected output? What do you see instead?

I want to use the Ipython console within Spyder, however the console is unusable.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
File "C:\Users\Jai\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\Jai\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\Jai\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\Jai\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 298, in main
kernel.initialize()
File "", line 2, in initialize
File "C:\Users\Jai\Anaconda3\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\Jai\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 484, in initialize
self.init_kernel()
File "C:\Users\Jai\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 389, in init_kernel
user_ns=self.user_ns,
File "C:\Users\Jai\Anaconda3\lib\site‑packages\traitlets\config\configurable.py", line 412, in instance
inst = cls(*args, **kwargs)
File "C:\Users\Jai\Anaconda3\lib\site‑packages\spyder_kernels\console\kernel.py", line 37, in __init__
super(SpyderKernel, self).__init__(*args, **kwargs)
File "C:\Users\Jai\Anaconda3\lib\site‑packages\ipykernel\ipkernel.py", line 67, in __init__
kernel = self,
File "C:\Users\Jai\Anaconda3\lib\site‑packages\traitlets\config\configurable.py", line 412, in instance
inst = cls(*args, **kwargs)
File "C:\Users\Jai\Anaconda3\lib\site‑packages\IPython\core\interactiveshell.py", line 687, in __init__
self.init_magics()
File "C:\Users\Jai\Anaconda3\lib\site‑packages\ipykernel\zmqshell.py", line 593, in init_magics
super(ZMQInteractiveShell, self).init_magics()
File "C:\Users\Jai\Anaconda3\lib\site‑packages\IPython\core\interactiveshell.py", line 2239, in init_magics
m.PylabMagics, m.ScriptMagics,
File "C:\Users\Jai\Anaconda3\lib\site‑packages\IPython\core\magic.py", line 405, in register
m = m(shell=self.shell)
File "C:\Users\Jai\Anaconda3\lib\site‑packages\IPython\core\magics\osm.py", line 52, in __init__
self.execre = re.compile(r'(.*)\.(%s)$' % winext,re.IGNORECASE)
File "C:\Users\Jai\Anaconda3\lib\re.py", line 234, in compile
return _compile(pattern, flags)
File "C:\Users\Jai\Anaconda3\lib\re.py", line 286, in _compile
p = sre_compile.compile(pattern, flags)
File "C:\Users\Jai\Anaconda3\lib\sre_compile.py", line 764, in compile
p = sre_parse.parse(p, flags)
File "C:\Users\Jai\Anaconda3\lib\sre_parse.py", line 930, in parse
p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
File "C:\Users\Jai\Anaconda3\lib\sre_parse.py", line 426, in _parse_sub
not nested and not items))
File "C:\Users\Jai\Anaconda3\lib\sre_parse.py", line 816, in _parse
p = _parse_sub(source, state, sub_verbose, nested + 1)
File "C:\Users\Jai\Anaconda3\lib\sre_parse.py", line 426, in _parse_sub
not nested and not items))
File "C:\Users\Jai\Anaconda3\lib\sre_parse.py", line 507, in _parse
code = _escape(source, this, state)
File "C:\Users\Jai\Anaconda3\lib\sre_parse.py", line 369, in _escape
raise source.error("incomplete escape %s" % escape, len(escape))
re.error: incomplete escape \U at position 9

```

## Versions

* Spyder version: 3.3.3
* Python version: 3.7.3
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10
* ipykernel version: 5.1.0
* conda version: 4.7.5
* conda-build version: 3.18.7
*Anaconda installer: Anaconda3-2019.03-Windows-x86_64.exe installer

**Comment by ccordoba12** [comment]
This is an installation problem and not an Spyder issue. Given that you tried of ways to fix this problem, my only recommendation at this point is for you to reinstall Anaconda, sorry.
