### ISSUE TITLE
client.py issue

### ISSUE THREAD

**Issue by cqkdzy** [spyder-ide/spyder#9833]
## Description

**What steps will reproduce the problem?**

1. After launch spyder through anaconda, it will occur.
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
```
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 571, in show_time
    "</b></span>" % (color, strftime(fmt, gmtime(elapsed_time)))
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 571, in show_time
    "</b></span>" % (color, strftime(fmt, gmtime(elapsed_time)))
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 571, in show_time
    "</b></span>" % (color, strftime(fmt, gmtime(elapsed_time)))
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 571, in show_time
    "</b></span>" % (color, strftime(fmt, gmtime(elapsed_time)))
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 571, in show_time
    "</b></spa
```

**Comment by oscargus** [comment]
What platform are you running on?

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.6
