### ISSUE TITLE
Spyder 2.1.9 crashes at startup with error: TypeError: _isdir() takes exactly 1 argument (0 given)

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#989]
_From [dev.to...@gmail.com](https://code.google.com/u/104562894473287603910/) on 2012-04-12T13:30:38Z_

What steps will reproduce the problem?

 1. Install Python 2.7.3 under Windows XP
2. Install spyder: pip install spyder
3. Start the IDE via spyder.bat
4. Observe an error What is the expected output? What do you see instead? Instead of starting Spyder IDE, the following error occurs:
C:\Python27\Scripts>spyder
Traceback (most recent call last):
  File "C:\Python27\Scripts\spyder", line 2, in \<module>
    from spyderlib import spyder
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 96, in \<module>
    from spyderlib.plugins.editor import Editor
  File "C:\Python27\lib\site-packages\spyderlib\plugins\editor.py", line 35, in \<module>
    from spyderlib.widgets.editor import (ReadWriteStatus, EncodingStatus,
  File "C:\Python27\lib\site-packages\spyderlib\widgets\editor.py", line 32, in \<module>
    from spyderlib.utils.module_completion import moduleCompletion
  File "C:\Python27\lib\site-packages\spyderlib\utils\module_completion.py", line 31, in \<module>
    db = PickleShareDB(MODULES_PATH)
  File "C:\Python27\lib\site-packages\spyderlib\utils\external\pickleshare.py", line 53, in __init__
    if not self.root.isdir():
TypeError: _isdir() takes exactly 1 argument (0 given) What version of the product are you using? On what operating system? Spyder: 2.1.9
Python: 2.7.3
OS: Windows XP 

Please provide any additional information below

. The issue is likely caused due to old version of the bundled path.py library (version 2.2) In this version the os.path functions are not bounded thus causing the exception. See this commit for more details: https://github.com/dottedmag/path.py/commit/bee13d0de4d44599d397b603e1c83dce1ce9818d Replacing path.py in C:\Python27\Lib\site-packages\spyderlib\utils\external\path.py with the latest version of from Github (located at https://github.com/dottedmag/path.py/blob/master/path.py ) resolves the problem.

The same issue affects IPython (version 0.10.2) and the resolution is the same - swap the bundled version of path.py (located at C:\Python27\Lib\site-packages\IPython\external\path.py) with the latest from Github.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=989_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-13T04:18:18Z_

We will take action on this but I'm quite surprised because the bug seems related to Python 3. And I can't reproduce it with Python 2.7.2.
Any idea?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-13T05:55:56Z_

Ok, I've done some research about this: this bug has probably been backported from Python 3 to Python 2.7.3 ( http://bugs.python.org/issue11583 ).

Let's update the path.py module.

**Status:** Started  
  **Owner:** pierre.raybaut  
  **Labels:** -Priority-High -Cat-SpyderGUI -Component-IPython -Usability Priority-Critical Cat-Miscelleneous MS-v2.1

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-13T06:13:49Z_

This issue was updated by revision a9e776d6aa91 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-04-13T08:33:34Z_

This changed caused the following failure:

Executing Spyder from source checkout Revision 1970 :a9e776d6aa91, Branch: default
01. Patched sys.path with C:\src\jedludlow-spyderlib-default
02. Skipping GUI toolkit detection
Traceback (most recent call last):
  File "C:\src\jedludlow-spyderlib-default\bootstrap.py", line 77, in \<module>
    from spyderlib import spyder
  File "C:\src\jedludlow-spyderlib-default\spyderlib\spyder.py", line 101, in \<m
odule>
    from spyderlib.plugins.editor import Editor
  File "C:\src\jedludlow-spyderlib-default\spyderlib\plugins\editor.py", line 35
, in \<module>
    from spyderlib.widgets.editor import (ReadWriteStatus, EncodingStatus,
  File "C:\src\jedludlow-spyderlib-default\spyderlib\widgets\editor.py", line 32
, in \<module>
    from spyderlib.utils.module_completion import moduleCompletion
  File "C:\src\jedludlow-spyderlib-default\spyderlib\utils\module_completion.py"
, line 26, in \<module>
    from spyderlib.utils.external.pickleshare import PickleShareDB
  File "C:\src\jedludlow-spyderlib-default\spyderlib\utils\external\pickleshare.
py", line 36, in \<module>
    from spyderlib.utils.external.path import path as Path
  File "C:\src\jedludlow-spyderlib-default\spyderlib\utils\external\path.py", li
ne 70, in \<module>
    locale.getpreferredencoding() == 'UTF-8':
NameError: name 'locale' is not defined

The locale module was inadvertently removed from the list of imports. The attached patch fixes the problem.

**Attachment:** [locale_patch.patch](http://code.google.com/p/spyderlib/issues/detail?id=989#hc4)

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-04-13T08:34:00Z_

**Status:** Started

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-13T09:36:18Z_

This issue was updated by revision a57ea04afae4 .


Sorry for this ugly bug.
To avoid this missing import statement issue to happen again (at the next
update of this `path` external module), I've moved the import statement to its
right place, i.e. inside the "Spyder patch".

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-04-13T09:47:02Z_

Tested with Python 2.7.2 on Windows 7.

**Status:** Verified

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-14T23:15:44Z_

issue #992 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2012-05-15T09:27:23Z_

Isn't this a critical issue for 2.1.9?  I just ran into this at both home (not a big deal, just annoying since I didn't actually have time to initially figure it out) and now at work trying to deploy new machines with python 2.7.3 + spyder 2.1.9.  I'd really like to see a 2.1.10, because I doubt we'll be seeing a 2.7.4 anytime soon...

**Comment by spyder-issues-migrator** [comment]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2012-05-15T09:28:24Z_

I hadn't ran into the issue on my personal work machine because I've been running devel from hg and only recently updated to 2.7.3.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-05-15T11:04:15Z_

There is one minor problem ( issue #1027 ) that I hope Jed and I can solve this week so we can make a new release the next one.
