### ISSUE TITLE
KeyError: 'willSave' when splitting the editor

### ISSUE THREAD

**Issue by hamddan4** [spyder-ide/spyder#9908]
### What steps will reproduce the problem?

Everytime I open Spyder4 or split the editor vertically/horizontally i get a KeyError error.

I can ignore it for every session but it gets annoying.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/spyder/plugins/editor/plugin.py", line 302, in report_open_file
    language.lower()])
  File "/usr/local/lib/python3.6/dist-packages/spyder/plugins/editor/plugin.py", line 326, in lsp_server_ready
    editorstack.notify_server_ready(language, configuration)
  File "/usr/local/lib/python3.6/dist-packages/spyder/plugins/editor/widgets/editor.py", line 1557, in notify_server_ready
    editor.start_lsp_services(config)
  File "/usr/local/lib/python3.6/dist-packages/spyder/plugins/editor/widgets/codeeditor.py", line 871, in start_lsp_services
    self.parse_lsp_config(config)
  File "/usr/local/lib/python3.6/dist-packages/spyder/plugins/editor/widgets/codeeditor.py", line 888, in parse_lsp_config
    self.will_save_notify = sync_options['willSave']
KeyError: 'willSave'
```

## Versions

* Spyder version: 4.0.0b3 
* Python version: 3.6.8
* Qt version: 5.12.3
* PyQt5 version: 5.12.2
* Operating System: Linux 4.18.0-25-generic

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
psutil >=0.3      :  5.6.3 (OK)
pyls >=0.27.0     :  0.28.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  0.29.10 (OK)
qtconsole >=4.5.0 :  4.5.1 (OK)
IPython >=4.0     :  7.5.0 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
This was fixed by PR #9887, which will be included in our next beta (beta4, to be released this week).

For now please downgrade `python-language-server` with

    pip install python-language-server==0.27

to not see this bug.

Also, as a general advice: you should stop installing things with `sudo pip` in your system because that will most probably break your Linux distro. You should use virtualenvs instead.
