### ISSUE TITLE
spyder-2.1.9 fails with Python 2.7.3 on Windows

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#992]
_From [cjgoh...@gmail.com](https://code.google.com/u/116229337564687281159/) on 2012-04-14T16:11:28Z_

Spyder-2.1.9 fails to start with Python 2.7.3 on Windows (was working with Python 2.7.2):

python.exe -c"from spyderlib import spyder;spyder.main()"
Traceback (most recent call last):
  File "<string>", line 1, in \<module>
  File "X:\Python27-x64\lib\site-packages\spyderlib\spyder.py", line 96, in \<module>
    from spyderlib.plugins.editor import Editor
  File "X:\Python27-x64\lib\site-packages\spyderlib\plugins\editor.py", line 35, in \<module>
    from spyderlib.widgets.editor import (ReadWriteStatus, EncodingStatus,
  File "X:\Python27-x64\lib\site-packages\spyderlib\widgets\editor.py", line 32, in \<module>
    from spyderlib.utils.module_completion import moduleCompletion
  File "X:\Python27-x64\lib\site-packages\spyderlib\utils\module_completion.py", line 31, in \<module>
    db = PickleShareDB(MODULES_PATH)
  File "X:\Python27-x64\lib\site-packages\spyderlib\utils\external\pickleshare.py", line 53, in __init__
    if not self.root.isdir():
TypeError: _isdir() takes exactly 1 argument (0 given)

The following patch to the spyderlib\utils\external\path.py module might fix this: https://github.com/dottedmag/path.py/commit/bee13d0de4d44599d397b603e1c83dce1ce9818d

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=992_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-14T23:15:44Z_

**Status:** Duplicate  
  **Mergedinto:** 989

**Comment by spyder-issues-migrator** [comment]
_From [cjgoh...@gmail.com](https://code.google.com/u/116229337564687281159/) on 2012-04-14T23:20:32Z_

Sorry for the duplicate. I did search the open issues for the error but nothing shows up.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-14T23:57:06Z_

No problem, it happens.
