### ISSUE TITLE
Variable explorer is not working

### ISSUE THREAD

**Issue by caiogirao** [spyder-ide/spyder#9922]
### What steps will reproduce the problem?

The window of variable explorer is not showing anything - and that is one of the main attributes of spyder...

### Traceback
```python-traceback
  File "C:\Users\cgirao\Desktop\spyder\spyder\plugins\ipythonconsole\plugin.py", line 742, in <lambda>
    lambda c=client: self.process_started(c))
  File "C:\Users\cgirao\Desktop\spyder\spyder\plugins\ipythonconsole\plugin.py", line 1378, in process_started
    self.main.variableexplorer.add_shellwidget(client.shellwidget)
  File "C:\Users\cgirao\Desktop\spyder\spyder\plugins\variableexplorer\plugin.py", line 138, in add_shellwidget
    nsb.setup(**self.get_settings())
TypeError: setup() got an unexpected keyword argument 'show_callable_attributes'
Traceback (most recent call last):
  File "C:\Users\cgirao\AppData\Local\Programs\Python\Python36\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
      File "C:\Users\cgirao\Desktop\spyder\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 224, in _handle_execute_reply
    self.set_namespace_view_settings()
  File "C:\Users\cgirao\Desktop\spyder\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 77, in set_namespace_view_settings
    self.namespacebrowser.get_view_settings())
  File "C:\Users\cgirao\Desktop\spyder\spyder\plugins\variableexplorer\widgets\namespacebrowser.py", line 244, in get_view_settings
    settings[name] = getattr(self, name)
AttributeError: 'NamespaceBrowser' object has no attribute 'show_callable_attributes'
```

## Versions

* Spyder version: 4.0.0.dev0 e49611571
* Python version: 3.6.5
* Qt version: 5.9.1
* PyQt5 version: 5.9
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0     :  2.4.2 (OK)
qdarkstyle >=2.6.4 :  2.6.8 (OK)
sphinx >=0.6.6     :  2.1.2 (OK)
pyls >=0.19.0;<0.25:  None (NOK)
nbconvert >=4.0    :  5.5.0 (OK)
pandas >=0.13.1    :  0.25.0 (OK)
numpy >=1.7        :  1.17.0 (OK)
sympy >=0.7.3      :  1.3 (OK)
cython >=0.21      :  0.29.2 (OK)
qtconsole >=4.2.0  :  4.4.4 (OK)
IPython >=4.0      :  7.5.0 (OK)
matplotlib >=2.0.0 :  3.1.1 (OK)
pylint >=0.25      :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
You need to update `spyder-kernels` to fix this. And you'll get a lot more errors if you don't fix this

    pyls >=0.19.0;<0.25:  None (NOK)

Look, if you're not prepared to run things from master, just stick to installing our betas, which have all these problems sorted out, or wait for the final release of version 4.

**Comment by ccordoba12** [comment]
And also, you should Anaconda instead of a custom Python installation if you're new to Python.
