### ISSUE TITLE
Memory and CPU use widget (change b5670c37c544) causes spyder to crash on startup

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#993]
_From [DavidAnt...@gmail.com](https://code.google.com/u/108698404730356683634/) on 2012-04-15T18:22:18Z_

I have checked that this error only occurs at changes after and including b5670c37c544. I am using the hg clone of spyder, on ubuntu 10.04 x64.

Executing Spyder using bootstrap.py, it fails to start, and yields the following message: Revision 2001 :b5670c37c544, Branch: default
01. Patched sys.path with /home/dap124/external_code/spyderlib-clean-server-clone
02. No PySide detected, using PyQt4 if available
03. Imported Spyder 2.2.0dev (Qt 4.6.2 via PyQt4 (API v1) 4.7.2)
0x. Enforcing parent console (Windows only)
04. Executing spyder.main()
Traceback (most recent call last):
  File "/home/dap124/external_code/spyderlib-clean-server-clone/spyderlib/spyder.py", line 1945, in main
    mainwindow = run_spyder(app, options)
  File "/home/dap124/external_code/spyderlib-clean-server-clone/spyderlib/spyder.py", line 1857, in run_spyder
    main.setup()
  File "/home/dap124/external_code/spyderlib-clean-server-clone/spyderlib/spyder.py", line 814, in setup
    self.apply_statusbar_settings()
  File "/home/dap124/external_code/spyderlib-clean-server-clone/spyderlib/spyder.py", line 1651, in apply_statusbar_settings
    widget.set_interval(CONF.get('main', '&#37;s/timeout' &#37; name))
  File "/home/dap124/external_code/spyderlib-clean-server-clone/spyderlib/widgets/status.py", line 56, in set_interval
    self.timer.setInterval(interval)
AttributeError: 'MemoryStatus' object has no attribute 'timer'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=993_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-16T02:32:27Z_

Oh I see exactly what it is. I'll fix this ASAP.

**Status:** Accepted

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-16T05:26:11Z_

This issue was updated by revision 32085ff749a8 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [DavidAnt...@gmail.com](https://code.google.com/u/108698404730356683634/) on 2012-04-16T17:38:46Z_

Yes, I can confirm that this is now fixed. Thanks Pierre for your quick work.

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-04-16T23:08:01Z_

**Status:** Verified
