### ISSUE TITLE
BSD socket not found

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#995]
_From [tokidrvic](https://code.google.com/u/tokidrvic/) on 2012-04-16T10:18:00Z_

Problem is at startup spyder. Print this error to the internal console:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/home/t0ki/.local/lib/python2.6/site-packages/spyderlib/widgets/externalshell/introspection.py", line 63, in run
    shell_id = read_packet(conn)
  File "/home/t0ki/.local/lib/python2.6/site-packages/spyderlib/utils/bsdsocket.py", line 43, in read_packet
    data += sock.recv(dlen)
TypeError: an integer is required

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/home/t0ki/.local/lib/python2.6/site-packages/spyderlib/widgets/externalshell/introspection.py", line 63, in run
    shell_id = read_packet(conn)
  File "/home/t0ki/.local/lib/python2.6/site-packages/spyderlib/utils/bsdsocket.py", line 43, in read_packet
    data += sock.recv(dlen)
TypeError: an integer is required

Version of the product and operating system:
Spyder 2.2.0dev 
Python 2.6.6, Qt 4.6.3, PyQt4 (API v1) 4.7.3 on Linux (Debian squeeze)
pyflakes 0.4.0

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=995_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-05-01T02:40:20Z_

Is this happening every time you open an interpreter inside Spyder's console plugin?

**Comment by spyder-issues-migrator** [comment]
_From [tokidrvic](https://code.google.com/u/tokidrvic/) on 2012-06-09T17:45:46Z_

I was update spyder and this problem is fixed.

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-06-09T23:06:30Z_

Good to know. =)

**Status:** Fixed
