### ISSUE TITLE
Mac OS spyder won't launch: python.app directory mismatch

### ISSUE THREAD

**Issue by xxiro** [spyder-ide/spyder#9951]
## Problem Description
Spyder won't launch. `.../python.app/.../python` directory does not match that in `../anaconda3/bin/pythonw`

### What steps reproduce the problem?

1. Spyder (3.3.6) installed through anaconda navigator
2. Launching spyder through navigator gives no response
3. Typing `spyder` in terminal returned error

### Paste Traceback/Error Below (if applicable)
```
/Users/xyan/anaconda3/bin/pythonw: line 3: /Users/xyan/anaconda3/python.app/Contents/MacOS/python: No such file or directory
```

## Versions

* Spyder version: 3.3.6
* Python version: 3.7.3
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Mac Mojave 10.14.6

**Comment by xxiro** [comment]
### Attempted Solutiom
I opened /Users/xyan/anaconda3/bin/pythonw, which is simply:
```
#!/bin/bash
export PYTHONEXECUTABLE=/Users/xyan/anaconda3/bin/python
/Users/xyan/anaconda3/python.app/Contents/MacOS/python "$@"
```
while I found the python binary is actually in 
```
/Users/xyan/anaconda3/python.app/pythonapp/Contents/MacOS/python
```
I changed the directory manually and spyder can launch without problem.

Since everything involved here is from the native anaconda, I suspect other people might have the same issue.

**Comment by ccordoba12** [comment]
Please run

    conda install -f python.app

to see if that helps.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by HassnaIrzan** [comment]
Had the same issue. @ccordoba12 your solution worked for me. Thanks

**Comment by Wikstahl** [comment]
> conda install -f python.app

This worked for me which had the same issue as OP!

**Comment by pjk645** [comment]
@ccordoba12 your solution worked for me as well

**Comment by nihalsahan** [comment]
Yeah, it works for me as well. Thanks!

**Comment by leebond** [comment]
@ccordoba12 your answer worked for me! I started having errors after updating conda. Lucky things are back to normal after running your command.

**Comment by mattwilliams06** [comment]
> Please run
> 
> ```
> conda install -f python.app
> ```
> 
> to see if that helps.

Carlos, this is an old issue, but your solution worked for me as well. Also, is that you at 77 Mass Ave?

**Comment by ccordoba12** [comment]
> Carlos, this is an old issue, but your solution worked for me as well.

Glad to know that old advice it's helpful!

> Also, is that you at 77 Mass Ave?

Sorry to disappoint you but I don't live in USA. But just out of curiosity, who are you talking about?

**Comment by mattwilliams06** [comment]
Where you’re standing looks like the main entrance to MIT.

**Comment by ccordoba12** [comment]
Lol, I understand your comment now! Actually, I've never been to MIT.

I took that photo in front of "El Prado" museum in Madrid, a long long time ago.

**Comment by mattwilliams06** [comment]
Cool.

**Comment by AminDar** [comment]
didn't work for me
conda update --all  also didn't

Traceback (most recent call last):
File "/Users/amin/anaconda3/bin/spyder", line 7, in 
from spyder.app.start import main
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 35, in 
from spyder.config.main import CONF
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder/config/main.py", line 21, in 
from spyder.config.fonts import BIG, MEDIUM, MONOSPACE, SANS_SERIF
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder/config/fonts.py", line 14, in 
from spyder.config.utils import is_ubuntu
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder/config/utils.py", line 15, in 
from spyder_kernels.utils import iofuncs
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder_kernels/utils/iofuncs.py", line 521, in 
iofunctions.setup()
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder_kernels/utils/iofuncs.py", line 445, in setup
iofuncs = self.get_internal_funcs()+self.get_3rd_party_funcs()
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder_kernels/utils/iofuncs.py", line 496, in get_3rd_party_funcs
for mod in get_spyderplugins_mods(io=True):
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder/otherplugins.py", line 42, in get_spyderplugins_mods
_get_spyderplugins(plugin_path, io, modnames, modlist)
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder/otherplugins.py", line 51, in _get_spyderplugins
for name in os.listdir(plugin_path):
PermissionError: [Errno 13] Permission denied: '/Users/amin/.local/lib/python3.7/site-packages'

**Comment by ptoche** [comment]
`conda install -f python.app` did it for me today. Great tip!

`conda update -n env --all` is broken. Second time the update breaks python.

**Comment by ccordoba12** [comment]
Yeah, `conda update --all` is usually not your best friend.

**Comment by AminDar** [comment]
> Yeah, `conda update --all` is usually not your best friend.

didn't work either


Traceback (most recent call last):
File "/Users/amin/anaconda3/bin/spyder", line 7, in 
from spyder.app.start import main
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 35, in 
from spyder.config.manager import CONF
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder/config/manager.py", line 17, in 
from spyder.config.main import CONF_VERSION, DEFAULTS, NAME_MAP
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder/config/main.py", line 19, in 
from spyder.config.fonts import MEDIUM, SANS_SERIF
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder/config/fonts.py", line 14, in 
from spyder.config.utils import is_ubuntu
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder/config/utils.py", line 17, in 
from spyder_kernels.utils import iofuncs
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder_kernels/utils/iofuncs.py", line 523, in 
iofunctions.setup()
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder_kernels/utils/iofuncs.py", line 447, in setup
iofuncs = self.get_internal_funcs()+self.get_3rd_party_funcs()
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder_kernels/utils/iofuncs.py", line 498, in get_3rd_party_funcs
for mod in get_spyderplugins_mods(io=True):
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder/otherplugins.py", line 45, in get_spyderplugins_mods
_get_spyderplugins(plugin_path, io, modnames, modlist)
File "/Users/amin/anaconda3/lib/python3.7/site-packages/spyder/otherplugins.py", line 54, in _get_spyderplugins
for name in os.listdir(plugin_path):
PermissionError: [Errno 13] Permission denied: '/Users/amin/.local/lib/python3.7/site-packages'

**Comment by qbao96xb** [comment]
> Please run
> 
> ```
> conda install -f python.app
> ```
> 
> to see if that helps.

This work for me (y), thank for your help. The problem happens after I tried to update conda (base) python version.

**Comment by deborabah** [comment]
@ccordoba12 thank you!

**Comment by shero6** [comment]
This worked for me also! Thank you..

**Comment by angelina-abitino** [comment]
`conda install -f python.app` got Spyder to open for me for a second and then quit immediately with an error message "python quit unexpectedly"

**Comment by sisams** [comment]
@ccordoba12  Thank you!

**Comment by Farah9494** [comment]
I have this error message whenever I go to launch Spyder on Mac: 
Traceback (most recent call last):
File "/Users/farah/opt/anaconda3/lib/python3.9/site-packages/spyder/app/utils.py", line 281, in create_window
main.setup()
File "/Users/farah/opt/anaconda3/lib/python3.9/site-packages/spyder/app/mainwindow.py", line 875, in setup
PLUGIN_REGISTRY.register_plugin(self, PluginClass,
File "/Users/farah/opt/anaconda3/lib/python3.9/site-packages/spyder/api/plugin_registration/registry.py", line 274, in register_plugin
instance = self._instantiate_spyder5_plugin(
File "/Users/farah/opt/anaconda3/lib/python3.9/site-packages/spyder/api/plugin_registration/registry.py", line 152, in _instantiate_spyder5_plugin
plugin_instance = PluginClass(main_window, configuration=CONF)
File "/Users/farah/opt/anaconda3/lib/python3.9/site-packages/spyder/api/plugins/new_api.py", line 890, in __init__
super().__init__(parent, configuration=configuration)
File "/Users/farah/opt/anaconda3/lib/python3.9/site-packages/spyder/api/plugins/new_api.py", line 294, in __init__
self._container = container = self.CONTAINER_CLASS(
File "/Users/farah/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/console/widgets/main_widget.py", line 123, in __init__
self.shell = InternalShell( # TODO: Move to use SpyderWidgetMixin?
File "/Users/farah/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/console/widgets/internalshell.py", line 153, in __init__
super().__init__(parent, get_conf_path('history_internal.py'),
File "/Users/farah/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/console/widgets/shell.py", line 665, in __init__
ShellBaseWidget.__init__(self, parent, history_filename,
File "/Users/farah/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/console/widgets/shell.py", line 75, in __init__
self.history = self.load_history()
File "/Users/farah/opt/anaconda3/lib/python3.9/site-packages/spyder/plugins/console/widgets/shell.py", line 503, in load_history
if rawhistory[1] != self.INITHISTORY[1]:
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/farah/opt/anaconda3/bin/spyder", line 11, in 
sys.exit(main())
File "/Users/farah/opt/anaconda3/lib/python3.9/site-packages/spyder/app/start.py", line 237, in main
mainwindow.main(options, args)
File "/Users/farah/opt/anaconda3/lib/python3.9/site-packages/spyder/app/mainwindow.py", line 1992, in main
mainwindow = create_window(MainWindow, app, splash, options, args)
File "/Users/farah/opt/anaconda3/lib/python3.9/site-packages/spyder/app/utils.py", line 283, in create_window
if main.console is not None:
File "/Users/farah/opt/anaconda3/lib/python3.9/site-packages/spyder/app/mainwindow.py", line 1088, in __getattr__
return self.get_plugin(self._INTERNAL_PLUGINS_MAPPING[attr])
File "/Users/farah/opt/anaconda3/lib/python3.9/site-packages/spyder/app/mainwindow.py", line 165, in get_plugin
raise SpyderAPIError(f'Plugin "{plugin_name}" not found!')
spyder.api.exceptions.SpyderAPIError: Plugin "internal_console" not found!

I tried: conda install -f python.app 
Still got the same error

**Comment by ashwin-h** [comment]
i created a new conda environment with
```
onda create --name uquant python=3.11
```
Then
```
conda activate uquant
```
```
 conda install spyder=5.4.3
```

With this i am able to start spyder
