### ISSUE TITLE
ipython does not work

### ISSUE THREAD

**Issue by manuelmolano** [spyder-ide/spyder#9954]
### What steps will reproduce the problem?

The problem arises when starting spyder. The ipython terminal says "connecting to nucleus" (in spanish)

### Traceback
```python-traceback
  File "/home/molano/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole.py", line 1178, in <lambda>
    kc.started_channels.connect(lambda c=client: self.process_started(c))
  File "/home/molano/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole.py", line 1753, in process_started
    self.variableexplorer.add_shellwidget(client.shellwidget)
  File "/home/molano/anaconda3/lib/python3.7/site-packages/spyder/plugins/variableexplorer.py", line 171, in add_shellwidget
    nsb.setup(**self.get_settings())
  File "/home/molano/anaconda3/lib/python3.7/site-packages/spyder/plugins/variableexplorer.py", line 107, in get_settings
    settings[name] = self.get_option(name)
  File "/home/molano/anaconda3/lib/python3.7/site-packages/spyder/api/plugins.py", line 177, in get_option
    return CONF.get(self.CONF_SECTION, option, default)
  File "/home/molano/anaconda3/lib/python3.7/site-packages/spyder/config/user.py", line 382, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'show_callable_attributes' in section: 'variable_explorer'
Traceback (most recent call last):
  File "/home/molano/anaconda3/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/home/molano/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 219, in _handle_execute_reply
    self.set_namespace_view_settings()
  File "/home/molano/anaconda3/lib/python3.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 73, in set_namespace_view_settings
    settings = to_text_string(self.namespacebrowser.get_view_settings())
  File "/home/molano/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/namespacebrowser.py", line 239, in get_view_settings
    settings[name] = getattr(self, name)
AttributeError: 'NamespaceBrowser' object has no attribute 'show_callable_attributes'
```

## Versions

* Spyder version: 4.0.0b1 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-54-generic

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.11.0     :  0.13.3 (OK)
psutil >=0.3      :  5.6.1 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
> Spyder version: 4.0.0b1

This is fixed beta4, please update.
