### ISSUE TITLE
 TypeError in object explorer

### ISSUE THREAD

**Issue by leavor** [spyder-ide/spyder#9959]
## Problem Description
I used the statsmodels package for nominal logistic regression **in spyder IDE 4.0.0b4**, when I double click to return results, there is an error viewing the variables,the result like this:
![image](https://user-images.githubusercontent.com/1759365/62448960-9f2f4580-b79b-11e9-8889-c296a4d01f47.png)

When I double click the "rslt",an error occurs:
![image](https://user-images.githubusercontent.com/1759365/62449070-f6cdb100-b79b-11e9-8ad1-3fbac88248e0.png)

Details as follow:

<details>
```python-traceback
  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\spyder\plugins\variableexplorer\widgets\objectexplorer\tree_model.py", line 267, in fetchMore
    parent_item.obj_path)
  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\spyder\plugins\variableexplorer\widgets\objectexplorer\tree_model.py", line 322, in _fetchObjectChildren
    for attr_name, attr_value in sorted(inspect.getmembers(obj)):
  File "d:\ProgramData\Anaconda3\envs\python37\lib\inspect.py", line 341, in getmembers
    value = getattr(object, key)
  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\statsmodels\base\wrapper.py", line 41, in __getattribute__
    obj = data.wrap_output(obj, how=how)
  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\statsmodels\base\data.py", line 413, in wrap_output
    return self.attach_rows(obj)
  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\statsmodels\base\data.py", line 552, in attach_rows
    columns=self.ynames)
  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\pandas\core\frame.py", line 424, in __init__
    copy=copy)
  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\pandas\core\internals\construction.py", line 158, in init_ndarray
    index, columns = _get_axes(*values.shape, index=index, columns=columns)
  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\pandas\core\internals\construction.py", line 375, in _get_axes
    columns = ensure_index(columns)
  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\pandas\core\indexes\base.py", line 5378, in ensure_index
    return Index(index_like)
  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\pandas\core\indexes\base.py", line 468, in __new__
    cls._scalar_data_error(data)
  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\pandas\core\indexes\base.py", line 3799, in _scalar_data_error
    repr(data)))
TypeError: Index(...) must be called with a collection of some kind, '科目' was passed
Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\spyder\plugins\variableexplorer\widgets\objectexplorer\tree_model.py", line 267, in fetchMore
    parent_item.obj_path)
  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\spyder\plugins\variableexplorer\widgets\objectexplorer\tree_model.py", line 322, in _fetchObjectChildren
    for attr_name, attr_value in sorted(inspect.getmembers(obj)):
  File "d:\ProgramData\Anaconda3\envs\python37\lib\inspect.py", line 341, in getmembers
    value = getattr(object, key)
  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\statsmodels\base\wrapper.py", line 41, in __getattribute__
    obj = data.wrap_output(obj, how=how)
  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\statsmodels\base\data.py", line 413, in wrap_output
    return self.attach_rows(obj)
  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\statsmodels\base\data.py", line 552, in attach_rows
    columns=self.ynames)
  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\pandas\core\frame.py", line 424, in __init__
    copy=copy)
  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\pandas\core\internals\construction.py", line 158, in init_ndarray
    index, columns = _get_axes(*values.shape, index=index, columns=columns)
  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\pandas\core\internals\construction.py", line 375, in _get_axes
    columns = ensure_index(columns)
  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\pandas\core\indexes\base.py", line 5378, in ensure_index
    return Index(index_like)
  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\pandas\core\indexes\base.py", line 468, in __new__
    cls._scalar_data_error(data)
  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\pandas\core\indexes\base.py", line 3799, in _scalar_data_error
    repr(data)))
TypeError: Index(...) must be called with a collection of some kind, '科目' was passed
</details>

I also used **spyder IDE 3.3.6**,The 'rslt' variable shows ok:
![image](https://user-images.githubusercontent.com/1759365/62449369-9a1ec600-b79c-11e9-8635-370b5c40681f.png)

### Paste Traceback/Error Below (if applicable)
<!--- Copy from error dialog or View > Panes > Internal Console --->

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.0.0b4
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version:win7 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Thanks for reporting. Please post a simple code that generates the `rslt` object you're trying to inspect in the Variable Explorer.

**Comment by leavor** [comment]
import pandas as pd
import statsmodels.api as sm
subject = ['数学','自然科学','自然科学','数学','数学','自然科学','数学','数学',
              '艺术','自然科学','艺术','数学','自然科学','自然科学','艺术','自然科学',
              '自然科学','自然科学','艺术','数学','数学','艺术','艺术','数学','艺术',
              '艺术','数学','自然科学','数学','艺术']
age = [10,10,10,10,10,10,10,11,11,11,11,11,11,11,11,12,12,12,12,12,12,12,
           13,13,13,13,13,13,13,13]
rsp = pd.Series(subject,name='sub')
pvar_con = pd.Series(age,name='age')
X = sm.add_constant(pvar_con)
model = sm.MNLogit(rsp,X)
rslt = model.fit()

**Comment by ccordoba12** [comment]
Thanks for the quick response @leavor! We'll try to fix this for our next beta.

@dalthviz, please take a look at this one.
