### ISSUE TITLE
Can't get spyder running on Snow Leopard

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#996]
_From [alan...@gmail.com](https://code.google.com/u/100660010062345065648/) on 2012-04-18T04:29:51Z_

Hi,
I've installed py-spyder from macports. 

re-doing it from terminal gives me

me$ sudo port install py-spyder
--->  Computing dependencies for py-spyder
--->  Cleaning py-spyder

(guess this means it worked)

However, typing "spyder" in the terminal gives me

me$ spyder
Traceback (most recent call last):
  File "/opt/local/bin/spyder", line 2, in \<module>
    from spyderlib import spyder
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/spyder.py", line 87, in \<module>
    from spyderlib.utils.environ import WinUserEnvDialog
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/utils/environ.py", line 16, in \<module>
    from spyderlib.baseconfig import _
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/baseconfig.py", line 138, in \<module>
    _ = get_translation("spyderlib")
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/baseconfig.py", line 117, in get_translation
    lang = locale.getdefaultlocale()[0]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 503, in getdefaultlocale
    return _parse_localename(localename)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 435, in _parse_localename
    raise ValueError, 'unknown locale: &#37;s' &#37; localename
ValueError: unknown locale: UTF-8

Any help?
Thanks,
Dubbard.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=996_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-21T00:30:57Z_

See this thread: http://groups.google.com/group/spyderlib/browse_thread/thread/299e11c6e677b277 Just added a note here: https://code.google.com/p/spyderlib/wiki/Installation?ts=1334993393&updated=Installation#Installing_on_MacOS_X

**Status:** Started

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-21T00:33:27Z_

This issue was updated by revision 9ef18eb7712f .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-21T00:36:23Z_

As a consequence, there is also a note here: http://packages.python.org/spyder/installation.html#id1
