### ISSUE TITLE
Spyder crash on startup

### ISSUE THREAD

**Issue by brodinew** [spyder-ide/spyder#9968]
## Problem Description
Spyder crashing on startup. Opening spyder from Anaconda prompt shows an ImportError: cannot import name 'constants' from 'zmq.backend.cython'

### What steps reproduce the problem?

1. Open spyder 

### What is the expected output? What do you see instead?
Expect to open spyder, getting error message below by opening it in the Anaconda Prompt and an error dialogue window when opening it through the windows start menu.

### Paste Traceback/Error Below (if applicable)
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3285, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3140, in run_spyder
    main.setup()
  File "C:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 844, in setup
    from spyder.plugins.editor import Editor
  File "C:\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 41, in <module>
    from spyder.utils.introspection.manager import IntrospectionManager
  File "C:\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 21, in <module>
    from spyder.utils.introspection.plugin_client import PluginClient
  File "C:\Anaconda3\lib\site-packages\spyder\utils\introspection\plugin_client.py", line 18, in <module>
    import zmq
  File "C:\Users\Erik Brodin\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Users\Erik Brodin\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\Erik Brodin\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\Erik Brodin\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\Erik Brodin\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\Erik Brodin\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name 'constants' from 'zmq.backend.cython' (C:\Users\Erik Brodin\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\zmq\backend\cython\__init__.py)
[13456:13432:0805/171436.298:ERROR:broker_win.cc(59)] Error reading broker pipe: The pipe has been ended. (0x6D)

```

## Versions

* Spyder version: 3.3.6
* Python version: 3.7.3
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 Pro (Version 1803)

**Comment by ccordoba12** [comment]
This is a problem with our firewall and/or antivirus. You need to deactivate them or add a rule to avoid them to block your python.exe to open ports in your machine.

**Comment by ccordoba12** [comment]
This could also be caused by you using pip to install Python packages provided by Anaconda. If the above doesn't fix your problem, I'm afraid you'll have to reinstall Anaconda (and in the future please avoid using pip as much as possible).

**Comment by tnankie** [comment]
I have exactly the same problem.
I've reinstalled 3 times today.
Once for all users and installed to c:\anaconda.
Once ran the installer as administrator and installed for just me to C:\ apps\anaconda.
Once followed all the defaults and ignored the warning about spaces in the directory path.

I'm not using any third party anti-virus or firewalls.

(I don't want to open a new issue for a reported problem, but the advised fix doesn't fix anything)

(base) C:\Users\Grey Ghost>spyder --reset
*** Reset Spyder settings to defaults ***
removing: C:\Users\Grey Ghost\.spyder-py3\spyder.ini
removing: C:\Users\Grey Ghost\.spyder-py3\history_internal.py
removing: C:\Users\Grey Ghost\.spyder-py3\workingdir
removing: C:\Users\Grey Ghost\.spyder-py3\langconfig
removing: C:\Users\Grey Ghost\.spyder-py3\spyder.lock

(base) C:\Users\Grey Ghost>spyder
Traceback (most recent call last):
  File "C:\Users\Grey Ghost\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3285, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\Grey Ghost\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3140, in run_spyder
    main.setup()
  File "C:\Users\Grey Ghost\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 844, in setup
    from spyder.plugins.editor import Editor
  File "C:\Users\Grey Ghost\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 41, in <module>
    from spyder.utils.introspection.manager import IntrospectionManager
  File "C:\Users\Grey Ghost\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 21, in <module>
    from spyder.utils.introspection.plugin_client import PluginClient
  File "C:\Users\Grey Ghost\Anaconda3\lib\site-packages\spyder\utils\introspection\plugin_client.py", line 18, in <module>
    import zmq
  File "C:\Users\Grey Ghost\AppData\Roaming\Python\Python37\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Users\Grey Ghost\AppData\Roaming\Python\Python37\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\Grey Ghost\AppData\Roaming\Python\Python37\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\Grey Ghost\AppData\Roaming\Python\Python37\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\Grey Ghost\AppData\Roaming\Python\Python37\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\Grey Ghost\AppData\Roaming\Python\Python37\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name 'constants' from 'zmq.backend.cython' (C:\Users\Grey Ghost\AppData\Roaming\Python\Python37\site-packages\zmq\backend\cython\__init__.py)
[5600:10928:1030/210745.547:ERROR:broker_win.cc(59)] Error reading broker pipe: The pipe has been ended. (0x6D)

**Comment by ccordoba12** [comment]
You have some leftovers of a previous pip installation here:

    C:\Users\Grey Ghost\AppData\Roaming\Python\Python37\

and that's what's causing the error. Just remove that directory and you'll be set.

**Comment by tnankie** [comment]
thanks I think. I had got it working using pip to reinstall zmq. but I know this isn't best practice so I've now uninstalled anaconda and deleted that entire directory and in the process of reinstalling.

Hopefully I'll then have a functional and stable (and hopefully update-able) Anaconda install. Will let you know if it is still broken.

**Comment by r3klaw** [comment]
I had the same issue, I solved mine by uninstalling pylint and reinstalling it.
