### ISSUE TITLE
How to shut down this issue while opening ini file 

### ISSUE THREAD

**Issue by jhonti034** [spyder-ide/spyder#9971]
### What steps will reproduce the problem?

This screen keeps coming even i try to delete the file from spyder system

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 171, in paintEvent

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 213, in paintEvent
    self.code_editor.scrollflagarea_paint_event(event)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 1445, in scrollflagarea_paint_event
    painter.fillRect(event.rect(), self.sideareas_color)
TypeError:   fillRect(self, QRectF, Qt.BrushStyle): argument 1 has unexpected type 'QRect'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 171, in paintEvent
    self.code_editor.linenumberarea_paint_event(event)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 1178, in linenumberarea_paint_event
    painter.fillRect(event.rect(), self.sideareas_color)
TypeError:   fillRect(self, QRectF, Qt.BrushStyle): argument 1 has unexpected type 'QRect'
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.3 
* Python version: 3.7.2
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.25.0 (OK)
numpy >=1.7       :  1.17.0 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. @goanpeca, please take a look at this one.

**Comment by ccordoba12** [comment]
@goanpeca, I meant in the 3.x branch. This issue was reported before and I don't know what's causing it.

**Comment by ccordoba12** [comment]
> This screen keeps coming even i try to delete the file from spyder system

@jhonti034, what do you mean by this?

**Comment by goanpeca** [comment]
Will take a look at it!

**Comment by ccordoba12** [comment]
@goanpeca, I'll create one if you manage to reproduce and fix this bug.

**Comment by goanpeca** [comment]
I have not been able to reproduce this 🤷‍♂

**Comment by ccordoba12** [comment]
Closing then. @jhonti034 this is probably fixed in Spyder 4, so please update to it when it comes out (in about a month or so).
